### ISSUE TITLE
conda env create -f file.yml throwing UnicodeError 

### ISSUE THREAD

**Issue by AlexAMR** [conda/conda#10009]
**I'm submitting a...**

* [X ] bug report

## Current Behavior
Running conda env create -f file.yml hits a UnicodeError before it even starts downloading packages. I have enabled UTF-8 encoding for both console and yml file. 

### Steps to Reproduce

    conda env create -f environment.yml    
    
     Traceback (most recent call last):
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 80, in do_call
            exit_code = getattr(module, func_name)(args, parser)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 111, in execute
            result[installer_type] = installer.install(prefix, pkg_specs, args, env)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\installers\conda.py", line 32, in install
            prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
            should_retry_solve)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
            force_remove, should_retry_solve)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
            ssc = self._collect_all_metadata(ssc)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
            return f(*args, **kwds)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
            index, r = self._prepare(prepared_specs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 1011, in _prepare
            self.subdirs, prepared_specs, self._repodata_fn)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 228, in get_reduced_index
            repodata_fn=repodata_fn)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
            result = tuple(concat(executor.map(subdir_query, channel_urls)))
          File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
            yield fs.pop().result()
          File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 435, in result
            return self.__get_result()
          File "C:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
            raise self._exception
          File "C:\ProgramData\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
            result = self.fn(*self.args, **self.kwargs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
            package_ref_or_match_spec))
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
            self.load()
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
            _internal_state = self._load()
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 270, in _load
            fh.write(raw_repodata_str or '{}')
          File "C:\ProgramData\Anaconda3\lib\encodings\cp1252.py", line 19, in encode
            return codecs.charmap_encode(input,self.errors,encoding_table)[0]
        UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 241: character maps to <undefined>
    
    `$ C:\ProgramData\Anaconda3\Scripts\conda-env-script.py create -f environment.yml`## Expected Behavior

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\amoldovan\.condarc
 populated config files : C:\Users\amoldovan\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.2
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\amoldovan\.conda\pkgs
                          C:\Users\amoldovan\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\amoldovan\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\amoldovan\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-76)

**Comment by chenghlee** [comment]
Can you please attach the "environment.yml" that's causing this issue?
