### ISSUE TITLE
`conda info --json` returns an error, although just `conda info` works

### ISSUE THREAD

**Issue by stefanches7** [conda/conda#10019]
## Current Behavior
`conda info --json` throws "ValueError('embedded null byte')", whereas `conda info` yields correct output and terminates with 0

### Steps to Reproduce
```
conda info --json
```

in an environment as well as after `conda deactivate`

## Expected Behavior
`conda info --json` should give the same information as `conda info`, just in JSON format

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : V-pipe
    active env location : /opt/modules/i12g/anaconda/envs/V-pipe
            shell level : 2
       user config file : /data/ouga/home/ag_gagneur/dvoretsk/.condarc
 populated config files : /opt/modules/i12g/anaconda/3-2019.10/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __cuda=9.1
                          __glibc=2.17
       base environment : /opt/modules/i12g/anaconda/3-2019.10  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/plotly/linux-64
                          https://conda.anaconda.org/plotly/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/modules/i12g/anaconda/3-2019.10/pkgs
                          /data/ouga/home/ag_gagneur/dvoretsk/.conda/pkgs
       envs directories : /opt/modules/i12g/anaconda/envs
                          /opt/modules/i12g/anaconda/3-2018.12/envs
                          /opt/modules/i12g/anaconda/3-5.0.1/envs
                          /data/ouga/home/ag_gagneur/dvoretsk/.conda/envs
                          /opt/modules/i12g/anaconda/3-2019.10/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/3.10.0-1062.18.1.el7.x86_64 scientific/7.8 glibc/2.17
                UID:GID : 5567:501918
             netrc file : /data/ouga/home/ag_gagneur/dvoretsk/.netrc
           offline mode : False

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /opt/modules/i12g/anaconda/3-2019.10/.condarc <==
auto_activate_base: False
envs_dirs:
  - /opt/modules/i12g/anaconda/envs/
  - /opt/modules/i12g/anaconda/3-2018.12/envs/
  - /opt/modules/i12g/anaconda/3-5.0.1/envs/
channel_priority: flexible
channels:
  - conda-forge
  - bioconda
  - plotly
  - defaults

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/modules/i12g/anaconda/envs/V-pipe:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
brotlipy                  0.7.0           py38h1e0a361_1000    conda-forge
ca-certificates           2020.4.5.2           hecda079_0    conda-forge
certifi                   2020.4.5.2       py38h32f6830_0    conda-forge
cffi                      1.14.0           py38hd463f26_0    conda-forge
chardet                   3.0.4           py38h32f6830_1006    conda-forge
configargparse            1.2.3              pyh9f0ad1d_0    conda-forge
cryptography              2.9.2            py38h766eaa4_0    conda-forge
datrie                    0.8.2            py38h1e0a361_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docutils                  0.16             py38h32f6830_1    conda-forge
gitdb                     4.0.5                      py_0    conda-forge
gitpython                 3.1.3                      py_0    conda-forge
idna                      2.9                        py_1    conda-forge
importlib-metadata        1.6.1            py38h32f6830_0    conda-forge
importlib_metadata        1.6.1                         0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jsonschema                3.2.0            py38h32f6830_1    conda-forge
jupyter_core              4.6.3            py38h32f6830_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
psutil                    5.7.0            py38h1e0a361_1    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyrsistent                0.16.0           py38h1e0a361_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.3           cpython_he5300dc_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pyyaml                    5.3.1            py38h1e0a361_0    conda-forge
ratelimiter               1.2.0           py38h32f6830_1001    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
setuptools                47.3.1           py38h32f6830_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
smmap                     3.0.4              pyh9f0ad1d_0    conda-forge
snakemake-minimal         5.14.0                     py_1    bioconda
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
toposort                  1.5                        py_3    conda-forge
traitlets                 4.3.3            py38h32f6830_1    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
wrapt                     1.12.1           py38h1e0a361_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-82)

**Comment by Hoeze** [comment]
Hi, I end up having the same problem.
Error log:
```python
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/cli/main_info.py", line 325, in execute
    info_dict['envs'] = list_all_known_prefixes()
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/core/envs_manager.py", line 85, in list_all_known_prefixes
    all_env_paths.update(_clean_environments_txt(environments_txt_file))
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/core/envs_manager.py", line 113, in _clean_environments_txt
    prefix for prefix in environments_txt_lines
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/core/envs_manager.py", line 114, in <genexpr>
    if prefix != remove_location and is_conda_environment(prefix)
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/gateways/disk/test.py", line 87, in is_conda_environment
    return isfile(join(prefix, PREFIX_MAGIC_FILE))
  File "/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
ValueError: embedded null byte
```
Full output:
<details>
```bash
#$ conda info --json
{
  "command": "/opt/modules/i12g/anaconda/3-2019.10/bin/conda info --json",
  "conda_info": {},
  "error": "ValueError('embedded null byte')",
  "exception_name": "ValueError",
  "exception_type": "<class 'ValueError'>",
  "traceback": "Traceback (most recent call last):\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/exceptions.py\", line 1079, in __call__\n    return func(*args, **kwargs)\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/cli/main.py\", line 84, in _main\n    exit_code = do_call(args, p)\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/cli/conda_argparse.py\", line 83, in do_call\n    return getattr(module, func_name)(args, parser)\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/cli/main_info.py\", line 325, in execute\n    info_dict['envs'] = list_all_known_prefixes()\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/core/envs_manager.py\", line 85, in list_all_known_prefixes\n    all_env_paths.update(_clean_environments_txt(environments_txt_file))\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/core/envs_manager.py\", line 113, in _clean_environments_txt\n    prefix for prefix in environments_txt_lines\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/core/envs_manager.py\", line 114, in <genexpr>\n    if prefix != remove_location and is_conda_environment(prefix)\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/site-packages/conda/gateways/disk/test.py\", line 87, in is_conda_environment\n    return isfile(join(prefix, PREFIX_MAGIC_FILE))\n  File \"/opt/modules/i12g/anaconda/3-2019.10/lib/python3.7/genericpath.py\", line 30, in isfile\n    st = os.stat(path)\nValueError: embedded null byte\n"
}
```
</details>

**Comment by Hoeze** [comment]
Solution:
`mv ~/.conda ~/.conda.bak`
Seems like there was some broken file in the conda folder.
