### ISSUE TITLE
conda 4.3.16 signal handler bug

### ISSUE THREAD

**Issue by benjaminpthomas** [conda/conda#10035]
I'm attempting to use conda on one of the machines at the Texas Advanced Computing Centre (TACC). This TypeError occurs every time I try to use conda to either update beyond this version, or to create an environment from a .yml file. I've tried quite a few different versions of Anaconda install to resolve this bug, but no cigar.

Any help appreciated.

Current conda install:

```
           platform : linux-64
      conda version : 4.3.16
   conda is private : False
  conda-env version : 4.3.16
conda-build version : 3.18.9
     python version : 3.7.4.final.0
   requests version : 2.24.0
   root environment : /scratch/06567/bpthomas/anaconda3  (writable)
default environment : /scratch/06567/bpthomas/anaconda3
   envs directories : /scratch/06567/bpthomas/anaconda3/envs
                      /home1/06567/bpthomas/.conda/envs
      package cache : /scratch/06567/bpthomas/anaconda3/pkgs
                      /home1/06567/bpthomas/.conda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/linux-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/linux-64
                      https://repo.continuum.io/pkgs/pro/noarch
        config file : None
       offline mode : False
         user-agent : conda/4.3.16 requests/2.24.0 CPython/3.7.4 Linux/3.10.0-957.5.1.el7.x86_64 CentOS Linux/7.6.1810 glibc/2.17
            UID:GID : 858670:816081
```

`$ /scratch/06567/bpthomas/anaconda3/bin/conda update conda`

```
Traceback (most recent call last):
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/cli/main.py", line 134, in _main
    exit_code = args.func(args, p)
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/cli/install.py", line 357, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/plan.py", line 809, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/core/package_cache.py", line 491, in execute
    self._execute_action(action)
  File "/scratch/06567/bpthomas/anaconda3/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/home1/06567/bpthomas/.local/lib/python3.7/site-packages/conda/common/signals.py", line 48, in signal_handler
    signal.signal(sig, previous_handler)
  File "/scratch/06567/bpthomas/anaconda3/lib/python3.7/signal.py", line 47, in signal
    handler = _signal.signal(_enum_to_int(signalnum), _enum_to_int(handler))
TypeError: signal handler must be signal.SIG_IGN, signal.SIG_DFL, or a callable object
```

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-92)

**Comment by angloyna** [comment]
Hi @benjaminpthomas . Sorry for the late response. Did you say you've tried to do a fresh install of a later version of the Anaconda installer? ( https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh ) I also noticed that the channels that you're installing from don't appear to include the `main` channels where our maintained packages are hosted (https://repo.continuum.io/pkgs/main/linux-64 and https://repo.continuum.io/pkgs/main/noarch).
