### ISSUE TITLE
[76760] Failed to execute script entry_point

### ISSUE THREAD

**Issue by starman86** [conda/conda#10038]
I am trying to install anaconda3 on Kubuntu ,I have done it 
in the past ,but now it does not work
```bash
 Welcome to Anaconda3 2020.02

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>> 
==================================
....
==================================
Last updated February 25, 2020


Do you accept the license terms? [yes|no]
[no] >>> 
Please answer 'yes' or 'no':'
>>> yes

Anaconda3 will now be installed into this location:
/home/nnamdi/anaconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/nnamdi/anaconda3] >>>             
PREFIX=/home/nnamdi/anaconda3

WARNING: md5sum mismatch of tar archive
expected: 826b70d8ad34b7d9230d4da350d1b598
     got: a1852b864ef187e50fd508043cf58429  -
Unpacking payload ...
concurrent.futures.process._RemoteTraceback:                                             
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 367, in _queue_management_worker
  File "multiprocessing/connection.py", line 251, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 483, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 598, in result_iterator
  File "concurrent/futures/_base.py", line 435, in result
  File "concurrent/futures/_base.py", line 384, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[80886] Failed to execute script entry_point

```

**Comment by shreeju** [comment]
Isn't it similar to a previously closed issue:
https://github.com/conda/conda/issues/9125

**Comment by starman86** [comment]
I get a different a sha checksum
