### ISSUE TITLE
installing untools from esri channel

### ISSUE THREAD

**Issue by jmadrid250** [conda/conda#10048]
(local252onbeta) C:\Users\jmadrid\AppData\Local\ESRI\conda\envs\local252onbeta>conda install --channel esri untools --no-shortcuts --verbose --insecure
Fetching package metadata .............
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : win-64
      conda version : 4.3.27
   conda is private : False
  conda-env version : 4.3.27
conda-build version : 3.18.9
     python version : 3.6.8.final.0
   requests version : 2.22.0
   root environment : C:\Program Files\ArcGIS\Pro\bin\Python  (writable)
default environment : C:\Users\jmadrid\AppData\Local\ESRI\conda\envs\local252onbeta
   envs directories : C:\Program Files\ArcGIS\Pro\bin\Python\envs
                      C:\Users\jmadrid\AppData\Local\ESRI\conda\envs
                      C:\Users\jmadrid\.conda\envs
      package cache : C:\Users\jmadrid\AppData\Local\ESRI\conda\pkgs
                      C:\Program Files\ArcGIS\Pro\bin\Python\pkgs
       channel URLs : https://conda.anaconda.org/esri/win-64
                      https://conda.anaconda.org/esri/noarch
                      https://repo.anaconda.com/pkgs/main/win-64
                      https://repo.anaconda.com/pkgs/main/noarch
                      https://repo.anaconda.com/pkgs/free/win-64
                      https://repo.anaconda.com/pkgs/free/noarch
                      https://repo.anaconda.com/pkgs/r/win-64
                      https://repo.anaconda.com/pkgs/r/noarch
                      https://repo.anaconda.com/pkgs/msys2/win-64
                      https://repo.anaconda.com/pkgs/msys2/noarch
        config file : C:\Program Files\ArcGIS\Pro\bin\Python\.condarc
         netrc file : None
       offline mode : False
         user-agent : conda/4.3.27 requests/2.22.0 CPython/3.6.8 Windows/10 Windows/10.0.18362
      administrator : True
```

`$ conda install --channel esri untools --no-shortcuts --verbose --insecure`

```
Traceback (most recent call last):
  File "conda\exceptions.py", line 641, in conda_exception_handler
  File "conda\cli\main.py", line 144, in _main
  File "conda\cli\main_install.py", line 80, in execute
  File "conda\cli\install.py", line 264, in install
  File "conda\plan.py", line 489, in install_actions_list
  File "conda\plan.py", line 489, in <listcomp>
  File "conda\plan.py", line 634, in get_actions_for_dists
  File "conda\resolve.py", line 813, in install
  File "conda\resolve.py", line 868, in solve
  File "conda\resolve.py", line 369, in find_conflicts
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - arcgispro 2.6.*
  - untools -> arcgispro 2.2
Use "conda info <package>" to see the dependencies for each package.
```

(local252onbeta) C:\Users\jmadrid\AppData\Local\ESRI\conda\envs\local252onbeta>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-100)

**Comment by angloyna** [comment]
Hi @jmadrid250 , I think we might need the contents of your ` C:\Users\jmadrid\AppData\Local\ESRI\conda\envs\local252onbet\conda-meta\history` file to know a little more about the conflict. I ran your command in a clean environment and it seemed to install perfectly well. On the face of it, it looks like untools requires version 2.2 of arcgispro and something else in the environment has brought in a more recent version of arcgispro. Let me know if you're able to find the history file at %CONDA_PREFIX\conda-meta\history`

**Comment by chenghlee** [comment]
Can you try `conda install` with the `--no-channel-priority` option?
