### ISSUE TITLE
launcher failing to run ipython in windows - anaconda 32 (64 same issues) 3.4

### ISSUE THREAD

**Issue by coynage** [conda/conda#1005]
C:\Anaconda3>conda info
Current conda install:

             platform : win-32
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-32/
                        http://repo.continuum.io/pkgs/pro/win-32/
          config file : None
    is foreign system : False

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_run.py", line 64, in execute
    for pkg in get_package_versions(args.package):
  File "C:\Anaconda3\lib\site-packages\conda\api.py", line 166, in get_package_versions
    index = get_index()
  File "C:\Anaconda3\lib\site-packages\conda\api.py", line 40, in get_index
    unknown=unknown)
  File "C:\Anaconda3\lib\site-packages\conda\utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 197, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 395, in result
    return self.__get_result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 354, in __get_result
    raise self._exception
  File "C:\Anaconda3\lib\concurrent\futures\thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 90, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
  File "C:\Anaconda3\lib\bz2.py", line 510, in decompress
    res = decomp.decompress(data)
OSError: Invalid data stream

**Comment by soapy1** [comment]
@coynage is this problem persisting for you?
