### ISSUE TITLE
Unable to start Anaconda-navigator.

### ISSUE THREAD

**Issue by ashita03** [conda/conda#10055]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-103)

**Comment by shahrruck2000** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 147, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 259, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\Shahrruck\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 160, in start_app
    "There is an instance of "
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 451, in __init__
    type_=self.INFORMATION_BOX,
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 295, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 102, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'
