### ISSUE TITLE
Having trouble in opening Anaconda . 

### ISSUE THREAD

**Issue by amit82saini2003** [conda/conda#10061]
Following is the error it is generating. 

"An unexpected error occurred on Navigator start-up" 

following is the full code I got - when I open Anaconda 

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(_args, *_kwargs)
  File "E:\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "E:\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "E:\anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in **init**
    self.api = AnacondaAPI()
  File "E:\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "E:\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in **init**
    self._conda_api = CondaAPI()
  File "E:\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "E:\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in **init**
    self.set_conda_prefix(info=get_conda_info())
  File "E:\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-107)

**Comment by shahrruck2000** [comment]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 147, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\external\filelock.py", line 259, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\Shahrruck\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 160, in start_app
    "There is an instance of "
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 451, in __init__
    type_=self.INFORMATION_BOX,
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 295, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\utils\analytics.py", line 102, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\Shahrruck\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**Comment by Murraymaina** [comment]
Just Delete the file .condarc in Drive C/user then run Anaconda again
