### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: WSL2 Conda Crash

### ISSUE THREAD

**Issue by Kogam22** [conda/conda#10066]
## If your issue is a bug report for **commands under 'conda env'**:
I installed WSL2 Kernel on my Win 10 machine. Then I installed Ubuntu 18.04 LTS. Then I installed latest Miniconda - 4.8.3. I created an environment using the `conda env create -f environment.yml` command.

## Current Behavior

So there's two parts to the installation. Some modules are to be installed by conda and some by pip. I think the pip packages are not installing and its crashing before that. It says permission denied. I run windows terminal in administrator mode. These are the logs: 
```bash
(base) kogam22@HOME-3700X-2060:~/code/fastai$ conda env create -f environment.yml
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages
libuuid-1.0.3        | 15 KB     | ############################################################################# | 100%
prompt-toolkit-3.0.5 | 245 KB    | ############################################################################# | 100%
chardet-3.0.4        | 180 KB    | ############################################################################# | 100%
pyyaml-5.3.1         | 180 KB    | ############################################################################# | 100%
freetype-2.10.2      | 608 KB    | ############################################################################# | 100%
spacy-2.1.8          | 92.8 MB   | ############################################################################# | 100%
ipywidgets-7.5.1     | 104 KB    | ############################################################################# | 100%
html5lib-1.1         | 93 KB     | ############################################################################# | 100%
mkl_fft-1.1.0        | 144 KB    | ############################################################################# | 100%
lz4-c-1.9.2          | 191 KB    | ############################################################################# | 100%
pixman-0.40.0        | 370 KB    | ############################################################################# | 100%
pillow-7.2.0         | 619 KB    | ############################################################################# | 100%
toolz-0.10.0         | 52 KB     | ############################################################################# | 100%
pip-20.1.1           | 1.8 MB    | ############################################################################# | 100%
cycler-0.10.0        | 13 KB     | ############################################################################# | 100%
cloudpickle-1.5.0    | 22 KB     | ############################################################################# | 100%
msgpack-python-1.0.0 | 90 KB     | ############################################################################# | 100%
jedi-0.17.1          | 921 KB    | ############################################################################# | 100%
wcwidth-0.2.5        | 29 KB     | ############################################################################# | 100%
terminado-0.8.3      | 26 KB     | ############################################################################# | 100%
mkl-2020.1           | 129.0 MB  | ############################################################################# | 100%
mistune-0.8.4        | 55 KB     | ############################################################################# | 100%
jupyter_core-4.6.3   | 71 KB     | ############################################################################# | 100%
zict-2.0.0           | 13 KB     | ############################################################################# | 100%
urllib3-1.25.9       | 103 KB    | ############################################################################# | 100%
pyzmq-19.0.1         | 460 KB    | ############################################################################# | 100%
packaging-20.4       | 36 KB     | ############################################################################# | 100%
pyrsistent-0.16.0    | 94 KB     | ############################################################################# | 100%
matplotlib-2.2.3     | 4.8 MB    | ############################################################################# | 100%
pytables-3.6.1       | 1.3 MB    | ############################################################################# | 100%
mock-4.0.2           | 32 KB     | ############################################################################# | 100%
ptyprocess-0.6.0     | 23 KB     | ############################################################################# | 100%
dbus-1.13.16         | 501 KB    | ############################################################################# | 100%
gstreamer-1.14.0     | 3.1 MB    | ############################################################################# | 100%
expat-2.2.9          | 156 KB    | ############################################################################# | 100%
scipy-1.5.0          | 14.4 MB   | ############################################################################# | 100%
jupyter_console-6.1. | 24 KB     | ############################################################################# | 100%
tqdm-4.47.0          | 62 KB     | ############################################################################# | 100%
qtconsole-4.7.5      | 96 KB     | ############################################################################# | 100%
zstd-1.4.4           | 447 KB    | ############################################################################# | 100%
dask-1.1.4           | 11 KB     | ############################################################################# | 100%
plac-0.9.6           | 40 KB     | ############################################################################# | 100%
libpng-1.6.37        | 278 KB    | ############################################################################# | 100%
qt-5.9.7             | 68.5 MB   | ############################################################################# | 100%
lcms2-2.11           | 307 KB    | ############################################################################# | 100%
wheel-0.34.2         | 51 KB     | ############################################################################# | 100%
jupyter_client-6.1.5 | 76 KB     | ############################################################################# | 100%
jinja2-2.11.2        | 103 KB    | ############################################################################# | 100%
python-3.6.10        | 29.7 MB   | ############################################################################# | 100%
notebook-5.7.9       | 4.2 MB    | ############################################################################# | 100%
simplegeneric-0.8.1  | 10 KB     | ############################################################################# | 100%
sip-4.19.8           | 274 KB    | ############################################################################# | 100%
pytz-2020.1          | 184 KB    | ############################################################################# | 100%
traitlets-4.3.3      | 140 KB    | ############################################################################# | 100%
testpath-0.4.4       | 82 KB     | ############################################################################# | 100%
heapdict-1.0.1       | 9 KB      | ############################################################################# | 100%
requests-2.24.0      | 56 KB     | ############################################################################# | 100%
pcre-8.44            | 212 KB    | ############################################################################# | 100%
markupsafe-1.1.1     | 29 KB     | ############################################################################# | 100%
pexpect-4.8.0        | 82 KB     | ############################################################################# | 100%
fontconfig-2.13.0    | 227 KB    | ############################################################################# | 100%
path-13.1.0          | 35 KB     | ############################################################################# | 100%
seaborn-0.10.1       | 163 KB    | ############################################################################# | 100%
icu-58.2             | 10.5 MB   | ############################################################################# | 100%
patsy-0.5.1          | 274 KB    | ############################################################################# | 100%
snappy-1.1.8         | 40 KB     | ############################################################################# | 100%
pyopenssl-19.1.0     | 48 KB     | ############################################################################# | 100%
tornado-4.5.3        | 583 KB    | ############################################################################# | 100%
mkl_random-1.1.1     | 327 KB    | ############################################################################# | 100%
tblib-1.6.0          | 16 KB     | ############################################################################# | 100%
libxml2-2.9.10       | 1.2 MB    | ############################################################################# | 100%
partd-1.1.0          | 20 KB     | ############################################################################# | 100%
brotlipy-0.7.0       | 323 KB    | ############################################################################# | 100%
cffi-1.14.0          | 223 KB    | ############################################################################# | 100%
pyparsing-2.4.7      | 65 KB     | ############################################################################# | 100%
graphite2-1.3.14     | 99 KB     | ############################################################################# | 100%
numexpr-2.7.1        | 186 KB    | ############################################################################# | 100%
cuda90-1.0           | 3 KB      | ############################################################################# | 100%
send2trash-1.5.0     | 16 KB     | ############################################################################# | 100%
jupyter-1.0.0        | 6 KB      | ############################################################################# | 100%
zeromq-4.3.2         | 510 KB    | ############################################################################# | 100%
bleach-3.1.5         | 116 KB    | ############################################################################# | 100%
fribidi-1.0.9        | 104 KB    | ############################################################################# | 100%
pickleshare-0.7.5    | 13 KB     | ############################################################################# | 100%
blas-1.0             | 6 KB      | ############################################################################# | 100%
libedit-3.1.20191231 | 116 KB    | ############################################################################# | 100%
libxcb-1.14          | 505 KB    | ############################################################################# | 100%
libgfortran-ng-7.3.0 | 1006 KB   | ############################################################################# | 100%
decorator-4.4.2      | 14 KB     | ############################################################################# | 100%
gst-plugins-base-1.1 | 4.8 MB    | ############################################################################# | 100%
cudnn-7.6.5          | 184.3 MB  | ############################################################################# | 100%
bokeh-1.4.0          | 8.2 MB    | ############################################################################# | 100%
widgetsnbextension-3 | 862 KB    | ############################################################################# | 100%
dask-core-1.1.4      | 1.1 MB    | ############################################################################# | 100%
hdf5-1.10.4          | 3.9 MB    | ############################################################################# | 100%
statsmodels-0.11.1   | 7.9 MB    | ############################################################################# | 100%
prometheus_client-0. | 47 KB     | ############################################################################# | 100%
importlib-metadata-1 | 51 KB     | ############################################################################# | 100%
bcolz-1.2.1          | 707 KB    | ############################################################################# | 100%
ipython_genutils-0.2 | 39 KB     | ############################################################################# | 100%
libffi-3.2.1         | 40 KB     | ############################################################################# | 100%
locket-0.2.0         | 9 KB      | ############################################################################# | 100%
glib-2.63.1          | 2.9 MB    | ############################################################################# | 100%
jpeg-9b              | 214 KB    | ############################################################################# | 100%
cryptography-2.9.2   | 556 KB    | ############################################################################# | 100%
qtpy-1.9.0           | 38 KB     | ############################################################################# | 100%
pandocfilters-1.4.2  | 13 KB     | ############################################################################# | 100%
thinc-7.0.8          | 1.7 MB    | ############################################################################# | 100%
attrs-19.3.0         | 40 KB     | ############################################################################# | 100%
python-dateutil-2.8. | 215 KB    | ############################################################################# | 100%
cairo-1.14.12        | 906 KB    | ############################################################################# | 100%
harfbuzz-1.8.8       | 507 KB    | ############################################################################# | 100%
setuptools-47.3.1    | 514 KB    | ############################################################################# | 100%
pango-1.42.4         | 464 KB    | ############################################################################# | 100%
srsly-0.1.0          | 209 KB    | ############################################################################# | 100%
cymem-2.0.2          | 40 KB     | ############################################################################# | 100%
lzo-2.10             | 184 KB    | ############################################################################# | 100%
numpy-1.18.5         | 5 KB      | ############################################################################# | 100%
libsodium-1.0.18     | 244 KB    | ############################################################################# | 100%
pandoc-2.9.2.1       | 12.3 MB   | ############################################################################# | 100%
numpy-base-1.18.5    | 4.1 MB    | ############################################################################# | 100%
zipp-3.1.0           | 13 KB     | ############################################################################# | 100%
cudatoolkit-10.2.89  | 365.1 MB  | ############################################################################# | 100%
ipython-7.16.1       | 999 KB    | ############################################################################# | 100%
yaml-0.2.5           | 75 KB     | ############################################################################# | 100%
certifi-2020.6.20    | 156 KB    | ############################################################################# | 100%
intel-openmp-2020.1  | 780 KB    | ############################################################################# | 100%
ca-certificates-2020 | 125 KB    | ############################################################################# | 100%
mkl-service-2.3.0    | 219 KB    | ############################################################################# | 100%
wasabi-0.2.2         | 18 KB     | ############################################################################# | 100%
path.py-12.4.0       | 7 KB      | ############################################################################# | 100%
sortedcontainers-2.2 | 29 KB     | ############################################################################# | 100%
murmurhash-1.0.2     | 27 KB     | ############################################################################# | 100%
pysocks-1.7.1        | 30 KB     | ############################################################################# | 100%
defusedxml-0.6.0     | 23 KB     | ############################################################################# | 100%
tk-8.6.10            | 3.0 MB    | ############################################################################# | 100%
click-7.1.2          | 71 KB     | ############################################################################# | 100%
cytoolz-0.10.1       | 377 KB    | ############################################################################# | 100%
testfixtures-6.14.1  | 72 KB     | ############################################################################# | 100%
importlib_metadata-1 | 11 KB     | ############################################################################# | 100%
nbformat-5.0.7       | 89 KB     | ############################################################################# | 100%
idna-2.10            | 50 KB     | ############################################################################# | 100%
blosc-1.19.0         | 71 KB     | ############################################################################# | 100%
nbconvert-5.6.1      | 460 KB    | ############################################################################# | 100%
pyqt-5.9.2           | 4.5 MB    | ############################################################################# | 100%
cython-blis-0.2.4    | 3.1 MB    | ############################################################################# | 100%
graphviz-2.40.1      | 6.5 MB    | ############################################################################# | 100%
preshed-2.0.1        | 78 KB     | ############################################################################# | 100%
ipykernel-5.3.0      | 177 KB    | ############################################################################# | 100%
parso-0.7.0          | 72 KB     | ############################################################################# | 100%
distributed-1.26.0   | 802 KB    | ############################################################################# | 100%
libtiff-4.1.0        | 449 KB    | ############################################################################# | 100%
kiwisolver-1.2.0     | 84 KB     | ############################################################################# | 100%
cython-0.29.20       | 1.9 MB    | ############################################################################# | 100%
pytorch-0.3.1        | 486.5 MB  | ############################################################################# | 100%
jsonschema-3.2.0     | 95 KB     | ############################################################################# | 100%
six-1.15.0           | 13 KB     | ############################################################################# | 100%
pycparser-2.20       | 94 KB     | ############################################################################# | 100%
entrypoints-0.3      | 12 KB     | ############################################################################# | 100%
psutil-5.7.0         | 315 KB    | ############################################################################# | 100%
backcall-0.2.0       | 15 KB     | ############################################################################# | 100%
libiconv-1.15        | 721 KB    | ############################################################################# | 100%
olefile-0.46         | 48 KB     | ############################################################################# | 100%
pygments-2.6.1       | 654 KB    | ############################################################################# | 100%
prompt_toolkit-3.0.5 | 11 KB     | ############################################################################# | 100%
pandas-1.0.5         | 7.8 MB    | ############################################################################# | 100%
webencodings-0.5.1   | 19 KB     | ############################################################################# | 100%
bzip2-1.0.8          | 78 KB     | ############################################################################# | 100%
sqlite-3.32.3        | 1.1 MB    | ############################################################################# | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kogam22/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/kogam22/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/kogam22/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/kogam22/miniconda3/lib/python3.7/site-packages/conda_env/installers/pip.py", line 41, in _pip_install_via_requirements
        delete=False)
      File "/home/kogam22/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/compat.py", line 80, in Utf8NamedTemporaryFile
        dir=dir, delete=delete)
      File "/home/kogam22/miniconda3/lib/python3.7/tempfile.py", line 547, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/home/kogam22/miniconda3/lib/python3.7/tempfile.py", line 258, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/home/kogam22/code/fastai/condaenv.avujjgvc.requirements.txt'

`$ /home/kogam22/miniconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/kogam22/miniconda3/bin/conda
             CONDA_PREFIX=/home/kogam22/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/kogam22/miniconda3/bin/python
               CONDA_ROOT=/home/kogam22/miniconda3
              CONDA_SHLVL=1
                     PATH=/home/kogam22/miniconda3/bin:/home/kogam22/miniconda3/bin:/home/kogam2
                          2/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bi
                          n:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Windows/system32:/mnt/
                          c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/Windows
                          PowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:/mnt/c/Program Files
                          (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA
                          Corporation/NVIDIA NvDLISR:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt
                          /c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.
                          0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program
                          Files/Git/cmd:/mnt/c/Program Files/PowerShell/7:/mnt/c/Users/kogam/App
                          Data/Local/Programs/Python/Python38/Scripts:/mnt/c/Users/kogam/AppData
                          /Local/Programs/Python/Python38:/mnt/c/Users/kogam/AppData/Local/Micro
                          soft/WindowsApps:/mnt/c/Users/kogam/AppData/Local/Microsoft/WindowsApp
                          s:/mnt/c/Users/kogam/AppData/Local/Programs/Microsoft VS
                          Code/bin:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/kogam22/miniconda3
            shell level : 1
       user config file : /home/kogam22/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.27
       base environment : /home/kogam22/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kogam22/miniconda3/pkgs
                          /home/kogam22/.conda/pkgs
       envs directories : /home/kogam22/miniconda3/envs
                          /home/kogam22/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/4.19.104-microsoft-standard ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.
```

### Steps to Reproduce

Install WSL2 on Win 10. Then do
```bash
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
git clone https://github.com/fastai/fastai
cd fastai
conda env create -f environment.yml
```

## Expected Behavior

It should install the packages and exit properly.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```bash
(fastai) kogam22@HOME-3700X-2060:~/code/fastai$ conda info

     active environment : fastai
    active env location : /home/kogam22/miniconda3/envs/fastai
            shell level : 2
       user config file : /home/kogam22/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.27
       base environment : /home/kogam22/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kogam22/miniconda3/pkgs
                          /home/kogam22/.conda/pkgs
       envs directories : /home/kogam22/miniconda3/envs
                          /home/kogam22/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Linux/4.19.104-microsoft-standard ubuntu/18.04.4 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary>No Output
<p>

```

```
</p></details> 

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```bash
(fastai) kogam22@HOME-3700X-2060:~/code/fastai$ conda list --show-channel-urls
# packages in environment at /home/kogam22/miniconda3/envs/fastai:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
attrs                     19.3.0                     py_0    defaults
backcall                  0.2.0                      py_0    defaults
bcolz                     1.2.1            py36h04863e7_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.5                      py_0    defaults
blosc                     1.19.0               hd408876_0    defaults
bokeh                     1.4.0                    py36_0    defaults
brotlipy                  0.7.0           py36h7b6447c_1000    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.6.24                     0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2020.6.20                py36_0    defaults
cffi                      1.14.0           py36h2e261b9_0    defaults
chardet                   3.0.4                 py36_1003    defaults
click                     7.1.2                      py_0    defaults
cloudpickle               1.5.0                      py_0    defaults
cryptography              2.9.2            py36h1ba5d50_0    defaults
cuda90                    1.0                  h6433d27_0    pytorch
cudatoolkit               10.2.89              hfd86e86_1    defaults
cudnn                     7.6.5                cuda10.2_0    defaults
cycler                    0.10.0                   py36_0    defaults
cymem                     2.0.2            py36he1b5a44_0    fastai
cython                    0.29.20          py36he6710b0_0    defaults
cython-blis               0.2.4            py36h516909a_1    fastai
cytoolz                   0.10.1           py36h7b6447c_0    defaults
dask                      1.1.4                    py36_1    defaults
dask-core                 1.1.4                    py36_1    defaults
dbus                      1.13.16              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               1.26.0                   py36_0    defaults
entrypoints               0.3                      py36_0    defaults
expat                     2.2.9                he6710b0_2    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.10.2               h5ab3b9f_0    defaults
fribidi                   1.0.9                h7b6447c_0    defaults
glib                      2.63.1               h5a9c865_0    defaults
graphite2                 1.3.14               h23475e2_0    defaults
graphviz                  2.40.1               h21bd128_2    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
heapdict                  1.0.1                      py_0    defaults
html5lib                  1.1                        py_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.10                       py_0    defaults
importlib-metadata        1.7.0                    py36_0    defaults
importlib_metadata        1.7.0                         0    defaults
intel-openmp              2020.1                      217    defaults
ipykernel                 5.3.0            py36h5ca1d4c_0    defaults
ipython                   7.16.1           py36h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                7.5.1                      py_0    defaults
jedi                      0.17.1                   py36_0    defaults
jinja2                    2.11.2                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                    py36_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            6.1.5                      py_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.3                    py36_0    defaults
kiwisolver                1.2.0            py36hfd86e86_0    defaults
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libiconv                  1.15                 h63c8f33_5    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.10               he19cac6_1    defaults
locket                    0.2.0                    py36_1    defaults
lz4-c                     1.9.2                he6710b0_0    defaults
lzo                       2.10                 h7b6447c_2    defaults
markupsafe                1.1.1            py36h7b6447c_0    defaults
matplotlib                2.2.3            py36hb69df0a_0    defaults
mistune                   0.8.4            py36h7b6447c_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py36he904b0f_0    defaults
mkl_fft                   1.1.0            py36h23d657b_0    defaults
mkl_random                1.1.1            py36h0573a6f_0    defaults
mock                      4.0.2                      py_0    defaults
msgpack-python            1.0.0            py36hfd86e86_1    defaults
murmurhash                1.0.2            py36he6710b0_0    defaults
nbconvert                 5.6.1                    py36_0    defaults
nbformat                  5.0.7                      py_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
notebook                  5.7.9                    py36_0    defaults
numexpr                   2.7.1            py36h423224d_0    defaults
numpy                     1.18.5           py36ha1c710e_0    defaults
numpy-base                1.18.5           py36hde5b4d6_0    defaults
olefile                   0.46                     py36_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
packaging                 20.4                       py_0    defaults
pandas                    1.0.5            py36h0573a6f_0    defaults
pandoc                    2.9.2.1                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.1.0                      py_0    defaults
path                      13.1.0                   py36_0    defaults
path.py                   12.4.0                        0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.44                 he6710b0_0    defaults
pexpect                   4.8.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    7.2.0            py36hb39fc2d_0    defaults
pip                       20.1.1                   py36_1    defaults
pixman                    0.40.0               h7b6447c_0    defaults
plac                      0.9.6                    py36_1    defaults
preshed                   2.0.1            py36he6710b0_0    defaults
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.5                      py_0    defaults
prompt_toolkit            3.0.5                         0    defaults
psutil                    5.7.0            py36h7b6447c_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.6.1                      py_0    defaults
pyopenssl                 19.1.0                     py_1    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
pyrsistent                0.16.0           py36h7b6447c_0    defaults
pysocks                   1.7.1                    py36_0    defaults
pytables                  3.6.1            py36h71ec239_0    defaults
python                    3.6.10               hcf32534_1    defaults
python-dateutil           2.8.1                      py_0    defaults
pytorch                   0.3.1           py36_cuda9.0.176_cudnn7.0.5_2  [cuda90]  pytorch
pytz                      2020.1                     py_0    defaults
pyyaml                    5.3.1            py36h7b6447c_1    defaults
pyzmq                     19.0.1           py36he6710b0_1    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 4.7.5                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
readline                  8.0                  h7b6447c_0    defaults
requests                  2.24.0                     py_0    defaults
scipy                     1.5.0            py36h0b6359f_0    defaults
seaborn                   0.10.1                     py_0    defaults
send2trash                1.5.0                    py36_0    defaults
setuptools                47.3.1                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.15.0                     py_0    defaults
snappy                    1.1.8                he6710b0_0    defaults
sortedcontainers          2.2.2                      py_0    defaults
spacy                     2.1.8            py36hc9558a2_0    fastai
sqlite                    3.32.3               h62c20be_0    defaults
srsly                     0.1.0            py36he1b5a44_0    fastai
statsmodels               0.11.1           py36h7b6447c_0    defaults
tblib                     1.6.0                      py_0    defaults
terminado                 0.8.3                    py36_0    defaults
testfixtures              6.14.1                     py_0    defaults
testpath                  0.4.4                      py_0    defaults
thinc                     7.0.8            py36hc9558a2_0    fastai
tk                        8.6.10               hbc83047_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   4.5.3                    py36_0    defaults
tqdm                      4.47.0                     py_0    defaults
traitlets                 4.3.3                    py36_0    defaults
urllib3                   1.25.9                     py_0    defaults
wasabi                    0.2.2                      py_0    fastai
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py36_1    defaults
wheel                     0.34.2                   py36_0    defaults
widgetsnbextension        3.5.1                    py36_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zeromq                    4.3.2                he6710b0_2    defaults
zict                      2.0.0                      py_0    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.4                h0b5b093_3    defaults
```
</p></details>

**Comment by Kogam22** [comment]
This error is also same as referenced here https://github.com/explosion/spaCy/issues/3363
