### ISSUE TITLE
Errors occur when installing Anaconda on Windows Server 2016

### ISSUE THREAD

**Issue by crrrr30** [conda/conda#10081]
When I was trying to install Anaconda3 to a remote folder (in UNC path, \\A_REMOTE_PATH\anaconda\), errors occur saying that: 

```
Extract: seaborn-0.9.0-py37_0.conda
Extract: anaconda-2019.07-py37_0.tar.bz2
Unpacking : alabaster-0.7.12-py37_0.conda
[12748] Failed to execute script conda.exe
Traceback (most recent call last):
  File "site-packages\conda_package_handling\api.py", line 49, in extract
  File "site-packages\conda_package_handling\conda_fmt.py", line 55, in extract
  File "site-packages\conda_package_handling\conda_fmt.py", line 37, in _extract_component
  File "site-packages\conda_package_handling\tarball.py", line 77, in _tar_xf
  File "site-packages\libarchive\extract.py", line 70, in extract_file
  File "site-packages\libarchive\extract.py", line 50, in extract_entries
  File "site-packages\libarchive\ffi.py", line 91, in check_int
  File "site-packages\libarchive\ffi.py", line 75, in archive_error
libarchive.exception.ArchiveError: Can't create '\\?\A_REMOTE_PATH\anaconda\pkgs\alabaster-0.7.12-py37_0\info\hash_input.json' (errno=2, retcode=-25, archive_p=2290590071216)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "conda.exe.py", line 60, in <module>
  File "conda.exe.py", line 55, in _extract
  File "site-packages\conda_package_handling\api.py", line 51, in extract
conda_package_handling.exceptions.InvalidArchiveError: Error with archive \\A_REMOTE_PATH\anaconda\pkgs\alabaster-0.7.12-py37_0.conda.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:

Can't create '\\?\A_REMOTE_PATH\anaconda\pkgs\alabaster-0.7.12-py37_0\info\hash_input.json' (errno=2, retcode=-25, archive_p=2290590071216)
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pyyaml==5.1.1=py37he774522_0
  - ......
```

I am sure that there was enough space (more than 1 TB), I had admin access to the location, and all characters in the remote path are ASCII characters. This happens to `Anaconda 2019.07` and `Anaconda 2020.02` on Windows Server 2016 (x86_64).

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-119)

**Comment by chenghlee** [comment]
Does the UNC remote path contain a space?

**Comment by crrr-dl** [comment]
> Does the UNC remote path contain a space?

No. The path contains only A-Z, 0-9, and dashes (-).
