### ISSUE TITLE
BUG: Conflicts with pyface >= 7 and Python >= 3.7

### ISSUE THREAD

**Issue by larsoner** [conda/conda#10095]
## Current Behavior

1. Conda cannot create an environment without conflicts (the CUDA stuff is unrelated I think):

<details>
<summary>Traceback</summary>

```
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                              

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package python conflicts for:
traitsui[version='>=6'] -> pyface[version='>=6'] -> python[version='>=3.8,<3.9.0a0']
pyface[version='>=7'] -> python[version='>=3.6,<3.7.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
pyface[version='>=7'] -> pygments -> python[version='>=2.7,<2.8.0a0|>=3.5|>=3.5,<3.6.0a0']
python[version='>=3.8']
traitsui[version='>=6'] -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Package _libgcc_mutex conflicts for:
traits[version='>=6'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
python[version='>=3.8'] -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]

Package pyface conflicts for:
traitsui[version='>=6'] -> pyface[version='>=6']
pyface[version='>=7']

Package traits conflicts for:
traits[version='>=6']
traitsui[version='>=6'] -> traits
pyface[version='>=7'] -> traits

Package ca-certificates conflicts for:
traitsui[version='>=6'] -> python -> ca-certificates
python[version='>=3.8'] -> openssl[version='>=1.1.1g,<1.1.2a'] -> ca-certificates

Package setuptools conflicts for:
pyface[version='>=7'] -> pygments -> setuptools
python[version='>=3.8'] -> pip -> setuptoolsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==10.2=0
  - feature:|@/linux-64::__cuda==10.2=0

Your installed CUDA driver is: 10.2
```

</details>

2. Also there is an issue that you must pin `traits>=6` and `traitsui>=6` not just `pyface>=7` otherwise traits 5.2.0 gets installed, then when you actually try to use it there is an error. Removing the `traits` and `traitsui` pinning the env gets created, but then `python -c "import pyface"` you get:

<details>
<summary>Additional traceback</summary>

```
(bad) larsoner@bunk:~/python/mne-python$ python -c "from traitsui.api import View"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/editors/__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/editors/code_editor.py", line 37, in <module>
    class ToolkitEditorFactory(EditorFactory):
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/editors/code_editor.py", line 49, in ToolkitEditorFactory
    mark_color = Color(0xECE9D8)
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traits/traits.py", line 655, in __call__
    return self.maker_function(*args, **metadata)
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traits/traits.py", line 1414, in Color
    return ColorTrait(*args, **metadata)
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/toolkit_traits.py", line 8, in ColorTrait
    return toolkit().color_trait(*args, **traits)
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/traitsui/toolkit.py", line 109, in toolkit
    _toolkit = find_toolkit('traitsui.toolkits')
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/pyface/base_toolkit.py", line 279, in find_toolkit
    toolkit = plugin.load()
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2460, in load
    self.require(*args, **kwargs)
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2483, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages/pkg_resources/__init__.py", line 790, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (traits 5.2.0 (/home/larsoner/anaconda3/envs/bad/lib/python3.8/site-packages), Requirement.parse('traits>=6'), {'pyface'})
```

</details>

### Steps to Reproduce
env_bad.yml
```
dependencies:
- python>=3.7
- traits>=6
- pyface>=7
- traitsui>=6
```
bash
```
$ conda env create -n bad -f env_bad.yml
```

## Expected Behavior
Create a usable env

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

So it seems like the dependencies for traits/traitsui/pyface are messed up in some way.

**Comment by angloyna** [comment]
@larsoner I think the culprit was a missing compatible traitsui. When you get a chance, try this again and let me know if you're still having the problem.

**Comment by larsoner** [comment]
Indeed it seems fixed, thanks @angloyna !
