### ISSUE TITLE
anaconda install on ubuntu 18.04

### ISSUE THREAD

**Issue by mczakk** [conda/conda#10103]
**I'm submitting a...**

* [* ] bug report
* [ ] feature request

## Current Behavior
I have followed the install instructions, then when I run source ~/anaconda3/bin/activate root I get the following message

### Steps to Reproduce

```
matt@zakk-jr:~/anaconda3$ source ~/anaconda3/bin/activate root 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/matt/.local/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/matt/.local/lib/python3.8/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/matt/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/matt/.local/lib/python3.8/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/matt/.local/lib/python3.8/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/matt/.local/lib/python3.8/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/matt/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/matt/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/matt/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/matt/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/matt/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matt/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/matt/.local/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/matt/.local/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/matt/.local/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/matt/.local/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/matt/.local/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/matt/.local/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/matt/.local/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/matt/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/matt/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/matt/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/matt/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/matt/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
matt@zakk-jr:~/anaconda3$ 


```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-128)

**Comment by ccordoba12** [comment]
It seems you installed conda with `pip --user` and that's interfering with you Anaconda installation in `~/anaconda3/`. Please remove this directory

    /home/matt/.local/lib/python3.8

and try again.
