### ISSUE TITLE
importerror:cannot import name "where"

### ISSUE THREAD

**Issue by tanjia123456** [conda/conda#10124]
Traceback (most recent call last):
  File "D:\anaconda3.4\lib\site-packages\conda\cli\main.py", line 168, in main
    activate.main()
  File "D:\anaconda3.4\lib\site-packages\conda\cli\activate.py", line 174, in main
    from ..install import symlink_conda
  File "D:\anaconda3.4\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "D:\anaconda3.4\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "D:\anaconda3.4\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "D:\anaconda3.4\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "D:\anaconda3.4\lib\site-packages\requests\**init**.py", line 120, in <module>
    from . import utils
  File "D:\anaconda3.4\lib\site-packages\requests\utils.py", line 25, in <module>
    from . import certs
  File "D:\anaconda3.4\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ImportError: cannot import name 'where'

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-140)

**Comment by chenghlee** [comment]
We will need the information requested in the bug report template before we can provide any help; namely, steps to reproduce, and the outputs of `conda info`, `conda list --show-channel-urls`, and `conda config --show-sources`.

**Comment by tanjia123456** [comment]
anaconda version:3.4    I have installed it in D:/anaconda3.4, but when i open the anaonda prompt , The error message :ImportError: cannot import name 'where'  appears. 
what's more,  when open prompt,it shows C:\Users\hp> ,it should show D:/anaconda3.4?

**Comment by Cynthyi** [comment]
Have this problem solved? I've met the same problem.
