### ISSUE TITLE
Issue with reinstall of Conda

### ISSUE THREAD

**Issue by menkem2003** [conda/conda#10120]
**I'm submitting a...**
  - [x ] bug report
  - [ ] feature request

## Current Behavior

Output from terminal is posted below:  

### Steps to Reproduce

```
While attempting to create a new env I received the following error info.  The command I used from terminal was: conda create --name pyenv 




```

## Expected Behavior
 I expected conda to create an environment I could use with Pycharm.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Message received:Traceback (most recent call last):
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/werewolf/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/werewolf/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/werewolf/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by chenghlee** [comment]
Can your please provide some information about how you installed conda? Based on the stack trace, it's not clear if you used the miniconda or Anaconda installer, or you `pip install conda` using another python interpreter.

**Comment by menkem2003** [comment]
Good afternoon,
Because of my newness to linux I tried everything I saw except miniconda.
So I did a pip install, an apt-get install. Thank you.

**Comment by chenghlee** [comment]
Try `/usr/bin/pip3 uninstall conda`, if you get something like the following output indicating conda < 4.8.x is installed in `~/.local`:
```
Found existing installation: conda 4.3.16
Uninstalling conda-4.3.16:
  Would remove:
    /home/user/.local/bin/conda
    /home/user/.local/lib/python3.8/site-packages/conda-4.3.16-py3.8.egg-info
    /home/user/.local/lib/python3.8/site-packages/conda/*
    /home/user/.local/lib/python3.8/site-packages/conda_env/*
  Would not remove (might be manually added):
    /home/user/.local/lib/python3.8/site-packages/conda/.version
Proceed (y/n)?
```
reply `y` to remove it and see if that fixes your issue.

**Comment by menkem2003** [comment]
Thank you for your email, that did it.

**Comment by chenghlee** [comment]
Glad to hear it's been fixed! I'll go ahead and closet this ticket.
