### ISSUE TITLE
Updating python3.7 to python3.8 crashed conda.

### ISSUE THREAD

**Issue by Sohit1212** [conda/conda#10139]
## Current Behavior

```
Traceback (most recent call last):
  File "/home/sohit/anaconda3/bin/conda", line 8, in <module>
    sys.exit(main())
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

```

### Steps to Reproduce

I tried updating a package wrapt using
``` conda update wrapt ```
This led to installing python3.8 and some other packages and conda crashed immediately.

```
Traceback (most recent call last):
  File "/home/sohit/anaconda3/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

After that I tried 

```
pip install conda
```

which did not work.

Again I tried

```
conda info
```

gave following output

```
Traceback (most recent call last):
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/common/configuration.py", line 42, in <module>
    from cytoolz.dicttoolz import merge
ModuleNotFoundError: No module named 'cytoolz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 85, in _main
    from ..base.context import context
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/base/context.py", line 21, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/common/configuration.py", line 47, in <module>
    from .._vendor.toolz.functoolz import excepts
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/_vendor/toolz/functoolz.py", line 467
    f.__name__ for f in reversed((self.first,) + self.funcs),
    ^
SyntaxError: Generator expression must be parenthesized
```

I installed cytoolz using

```
pip install cytoolz
```

## Expected Behavior

I was trying to istall Tensorflow using pip. For that I had to update the wrapt package, which led to all this mess.
Is there a way to update conda to use python3.8 properly or to make conda use python3.7

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Traceback (most recent call last):
  File "/home/sohit/anaconda3/bin/conda", line 8, in <module>
    sys.exit(main())
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Traceback (most recent call last):
  File "/home/sohit/anaconda3/bin/conda", line 8, in <module>
    sys.exit(main())
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Traceback (most recent call last):
  File "/home/sohit/anaconda3/bin/conda", line 8, in <module>
    sys.exit(main())
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/sohit/anaconda3/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

```

</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-148)

**Comment by cjmartian** [comment]
Is there a particular reason why you are wanting to install these packages with `pip` instead of `conda`?
https://anaconda.org/anaconda/cytoolz
https://anaconda.org/anaconda/conda
https://anaconda.org/anaconda/tensorflow

**Comment by cjmartian** [comment]
Can you please provide some details on how you installed conda? Was it via miniconda or Anaconda installer, or did you use pip?
