### ISSUE TITLE
A problem with "conda init powershell"

### ISSUE THREAD

**Issue by AR-jpeg** [conda/conda#10151]
I saw that conda has recently added support for powershell, *but* you need to say "conda init powershell", so I used and Admin cmd window and typed that but got this:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\cli\main_init.py", line 16, in execute
        from ..core.initialize import initialize, initialize_dev, install
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\core\initialize.py", line 73, in <module>
        from menuinst.knownfolders import get_folder_path, FOLDERID
      File "C:\Users\Owner\anaconda3\lib\site-packages\menuinst\__init__.py", line 23, in <module>
        from .win32 import Menu, ShortCut
      File "C:\Users\Owner\anaconda3\lib\site-packages\menuinst\win32.py", line 11, in <module>
        import pywintypes
      File "C:\Users\Owner\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 136, in <module>
        __import_pywin32_system_module__("pywintypes", globals())
      File "C:\Users\Owner\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 64, in __import_pywin32_system_module__
        import _win32sysloader
    ImportError: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application.

`$ C:\Users\Owner\anaconda3\Scripts\conda-script.py init powershell`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\Owner\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Owner\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\Owner\anaconda3
                   GOPATH=C:\Users\Owner\go
                 HOMEPATH=\Users\Owner
                     PATH=C:\Users\Owner\anaconda3;C:\Users\Owner\anaconda3\Library\mingw-w64\bi
                          n;C:\Users\Owner\anaconda3\Library\usr\bin;C:\Users\Owner\anaconda3\Li
                          brary\bin;C:\Users\Owner\anaconda3\Scripts;C:\Users\Owner\anaconda3\bi
                          n;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program
                          Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows
                          ;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
                          C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\IVI
                          Foundation\VISA\WinNT\Bin;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\ProgramDa
                          ta\chocolatey\bin;C:\Go\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\
                          System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\S
                          ystem32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files
                          (x86)\Certbot\bin;C:\Program Files\Git\cmd;C:\Python\Scripts\;C:\Pytho
                          n\;C:\Users\Owner\scoop\shims;C:\Users\Owner\anaconda3;C:\Users\Owner\
                          anaconda3\Library\mingw-w64\bin;C:\Users\Owner\anaconda3\Library\usr\b
                          in;C:\Users\Owner\anaconda3\Library\bin;C:\Users\Owner\anaconda3\Scrip
                          ts;C:\Users\Owner\.poetry\bin;C:\Users\Owner\AppData\Local\Microsoft\W
                          indowsApps;C:\Users\Owner\AppData\Local\Programs\Microsoft VS
                          Code\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2
                          \bin;C:\Users\Owner\AppData\Roaming\npm;C:\Users\Owner\AppData\Local\a
                          tom\bin;C:\Program Files\heroku\bin;C:\Users\Owner\AppData\Local\GitHu
                          bDesktop\bin;C:\Users\Owner\go\bin;C:\Users\Owner\.deno\bin;C:\Users\O
                          wner\AppData\Local\Microsoft\WindowsApps;C:\Users\Owner\flutter\bin;C:
                          \Users\Owner\AppData\Local\Programs\VSCodium\bin;C:\Program
                          Files\Git\usr\bin;;C:\Program Files\Git\usr\bin;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn\;C:\UsersOwner\Anaconda3;C:\
                          Users\Owner\Anaconda3\Scripts;C:\Users\Owner\Anaconda3\Library\bin;C:\
                          Users\Owner\.dotnet\tools;C:\tools\neovim\Neovim\bin
             PSMODULEPATH=C:\Users\Owner\Documents\WindowsPowerShell\Modules;C:\Program Files\Wi
                          ndowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mod
                          ules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               VXIPNPPATH=C:\Program Files (x86)\IVI Foundation\VISA\

     active environment : None
       user config file : C:\Users\Owner\.condarc
 populated config files : C:\Users\Owner\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages :
       base environment : C:\Users\Owner\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Owner\anaconda3\pkgs
                          C:\Users\Owner\.conda\pkgs
                          C:\Users\Owner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Owner\anaconda3\envs
                          C:\Users\Owner\.conda\envs
                          C:\Users\Owner\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

My current `conda info` reads:
```
     active environment : None
       user config file : C:\Users\Owner\.condarc
 populated config files : C:\Users\Owner\.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages :
       base environment : C:\Users\Owner\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Owner\anaconda3\pkgs
                          C:\Users\Owner\.conda\pkgs
                          C:\Users\Owner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Owner\anaconda3\envs
                          C:\Users\Owner\.conda\envs
                          C:\Users\Owner\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : True
             netrc file : None
           offline mode : False
```

**Comment by cjmartian** [comment]
Hey @AR-jpeg 

Just looking at the stack here, it looks like you might have downloaded the 32-bit installer on a 64-bit system. Can you provide the link from which you downloaded the installer?

`ImportError: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application.`

The channel URLs suggest that you're running a 64-bit system.

```
channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
```

**Comment by AR-jpeg** [comment]
It looks like I got it from https://repo.anaconda.com/archive/Anaconda3-2020.07-Windows-x86_64.exe

**Comment by AR-jpeg** [comment]
Update, I reinstalled conda clicking the 64 bit option
![image](https://user-images.githubusercontent.com/58893337/90080402-1a410b00-dcd0-11ea-8cbf-85cc853b3b4a.png)
but it still doesn't work

**Comment by cjmartian** [comment]
@AR-jpeg 

Thank you for doing that. Thats exactly what I was going to ask for. 

I'll look more deeply into this issue tomorrow and get back to you as soon as I learn more.

**Comment by cjmartian** [comment]
Alright, so after some digging this morning I've been able to `conda init powershell` without any issues.
Here are the steps I took. Please let me know if I missed anything in recreating your issue, I'd like to be able to get to the bottom of this.

After removing my existing install, I downloaded and ran the [installer](https://repo.anaconda.com/archive/Anaconda3-2020.07-Windows-x86_64.exe) with the default settings. I then ran cmd as admin. Running `conda init powershell` gave me the following output:
![image](https://user-images.githubusercontent.com/47338163/90153273-616de100-dd4e-11ea-8c7d-a02f0750db82.png)


I then closed my cmd window and brought up a powershell window. Running `conda --help` gave the expected output.

![image](https://user-images.githubusercontent.com/47338163/90153406-8e21f880-dd4e-11ea-904c-f115883e04e4.png)

**Comment by AR-jpeg** [comment]
weird, it still gives me 
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\cli\main_init.py", line 16, in execute
        from ..core.initialize import initialize, initialize_dev, install
      File "C:\Users\Owner\anaconda3\lib\site-packages\conda\core\initialize.py", line 73, in <module>
        from menuinst.knownfolders import get_folder_path, FOLDERID
      File "C:\Users\Owner\anaconda3\lib\site-packages\menuinst\__init__.py", line 23, in <module>
        from .win32 import Menu, ShortCut
      File "C:\Users\Owner\anaconda3\lib\site-packages\menuinst\win32.py", line 11, in <module>
        import pywintypes
      File "C:\Users\Owner\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 136, in <module>
        __import_pywin32_system_module__("pywintypes", globals())
      File "C:\Users\Owner\AppData\Roaming\Python\Python38\site-packages\win32\lib\pywintypes.py", line 64, in __import_pywin32_system_module__
        import _win32sysloader
    ImportError: DLL load failed while importing _win32sysloader: %1 is not a valid Win32 application.

`$ C:\Users\Owner\anaconda3\Scripts\conda-script.py init powershell`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=C:\Users\Owner\anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\Users\Owner\anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=C:\Users\Owner\anaconda3
                   GOPATH=C:\Users\Owner\go
                 HOMEPATH=\Users\Owner
                     PATH=C:\Users\Owner\anaconda3;C:\Users\Owner\anaconda3\Library\mingw-w64\bi
                          n;C:\Users\Owner\anaconda3\Library\usr\bin;C:\Users\Owner\anaconda3\Li
                          brary\bin;C:\Users\Owner\anaconda3\Scripts;C:\Users\Owner\anaconda3\bi
                          n;C:\Program Files\ConEmu\ConEmu\Scripts;C:\Program
                          Files\ConEmu;C:\Program Files\ConEmu\ConEmu;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows
                          ;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;
                          C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\IVI
                          Foundation\VISA\WinNT\Bin;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\ProgramDa
                          ta\chocolatey\bin;C:\Go\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\
                          System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\S
                          ystem32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files
                          (x86)\Certbot\bin;C:\Program Files\Git\cmd;C:\Python\Scripts\;C:\Pytho
                          n\;C:\Users\Owner\scoop\shims;C:\Users\Owner\anaconda3;C:\Users\Owner\
                          anaconda3\Library\mingw-w64\bin;C:\Users\Owner\anaconda3\Library\usr\b
                          in;C:\Users\Owner\anaconda3\Library\bin;C:\Users\Owner\anaconda3\Scrip
                          ts;C:\Users\Owner\.poetry\bin;C:\Users\Owner\AppData\Local\Microsoft\W
                          indowsApps;C:\Users\Owner\AppData\Local\Programs\Microsoft VS
                          Code\bin;C:\Program Files\JetBrains\PyCharm Community Edition 2019.3.2
                          \bin;C:\Users\Owner\AppData\Roaming\npm;C:\Users\Owner\AppData\Local\a
                          tom\bin;C:\Program Files\heroku\bin;C:\Users\Owner\AppData\Local\GitHu
                          bDesktop\bin;C:\Users\Owner\go\bin;C:\Users\Owner\.deno\bin;C:\Users\O
                          wner\AppData\Local\Microsoft\WindowsApps;C:\Users\Owner\flutter\bin;C:
                          \Users\Owner\AppData\Local\Programs\VSCodium\bin;C:\Program
                          Files\Git\usr\bin;;C:\Program Files\Git\usr\bin;C:\Program
                          Files\Microsoft SQL Server\130\Tools\Binn\;C:\UsersOwner\Anaconda3;C:\
                          Users\Owner\Anaconda3\Scripts;C:\Users\Owner\Anaconda3\Library\bin;C:\
                          Users\Owner\.dotnet\tools;C:\tools\neovim\Neovim\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               VXIPNPPATH=C:\Program Files (x86)\IVI Foundation\VISA\

     active environment : None
       user config file : C:\Users\Owner\.condarc
 populated config files : C:\Users\Owner\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages :
       base environment : C:\Users\Owner\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Owner\anaconda3\pkgs
                          C:\Users\Owner\.conda\pkgs
                          C:\Users\Owner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Owner\anaconda3\envs
                          C:\Users\Owner\.conda\envs
                          C:\Users\Owner\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.3 Windows/10 Windows/10.0.19041
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by AR-jpeg** [comment]
Hmmmmm, After removing my existing install, I downloaded and ran the **32 bit** installer, which worked!

![image](https://user-images.githubusercontent.com/58893337/90159159-9af61a80-dd55-11ea-9bf3-5f042097ec85.png)

**Comment by cjmartian** [comment]
Glad to hear it! Sorry I wasn't more help, but I'm happy that it was resolved. 

I'm going to close this issue, if that sounds good to you.

**Comment by AR-jpeg** [comment]
Thanks for the support!

**Comment by peterskurt** [comment]
It wasn't resolved!  He had to use the 32 bit version!
