### ISSUE TITLE
Failed to create Py 3.3 env

### ISSUE THREAD

**Issue by mark-summerfield** [conda/conda#1016]
Hi,
I installed Anaconda3 and then tried to create a Python 3.3 environment.
Unfortunately, my virtualbox crashed in the middle so I had to delete the py33 folder and clean the locks and repeat so maybe that had a bad effect?

C:\>conda create -n py33 python=3.3 anaconda
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment C:\Users\mark\Anaconda3\envs\py33:
...
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the####        |  85%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\mark\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\cli\main.py", line 201,
in main
    args_func(args, p)
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\cli\main.py", line 206,
in args_func
    args.func(args, p)
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\cli\main_create.py", lin
e 50, in execute
    install.install(args, parser, 'create')
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\cli\install.py", line 38
7, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\plan.py", line 587, in e
xecute_actions
    execute_plan(plan, index, verbose)
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\plan.py", line 569, in e
xecute_plan
    link(prefix, arg, index=index)
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\plan.py", line 525, in l
ink
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Users\mark\Anaconda3\lib\site-packages\conda\install.py", line 507, i
n link
    if os.path.exists(dst):
  File "C:\Users\mark\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: path too long for Windows

**Comment by soapy1** [comment]
@mark-summerfield is this still an issue for you?

**Comment by mark-summerfield** [comment]
No, I stopped using this some time ago.
