### ISSUE TITLE
Error: code for hash md5 was not found

### ISSUE THREAD

**Issue by DamienIrving** [conda/conda#1018]
I tried to install a new library today on my Macbook Pro (running Mavricks) - `sudo conda install seaborn` - and got the following error message.

In fact, I get the same error even when I try `sudo conda update conda`

```
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/Users/damienirving/anaconda/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/damienirving/anaconda/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/Users/damienirving/anaconda/lib/python2.7/hashlib.py", line 139, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/Users/damienirving/anaconda/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
Traceback (most recent call last):
  File "/Users/damienirving/anaconda/bin/conda", line 3, in <module>
    from conda.cli import main
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from conda.cli.main import main
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 48, in <module>
    from conda.cli import main_create
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 11, in <module>
    from conda.cli import common, install
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 18, in <module>
    import conda.plan as plan
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/plan.py", line 22, in <module>
    from conda.fetch import fetch_pkg
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 23, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/conda/connection.py", line 22, in <module>
    import requests
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 31, in <module>
    from .connection import (
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 36, in <module>
    from .util.ssl_ import (
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/Users/damienirving/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 2, in <module>
    from hashlib import md5, sha1
ImportError: cannot import name md5
```

**Comment by scottstewartt** [comment]
Had same problem (both conda and ipython throwing 'code for hash md5 was not found') after updating conda on OS X Yosemite. Was working fine before conda update. history:
conda update
conda update python
conda update conda

**Comment by sanada1615** [comment]
I'm having this same error message after installing Anaconda2 Linux using the Bash for Ubuntu for Windows built into Windows 10. I've tried several rounds of clean installing to no avail.

**Comment by ealbin** [comment]
Anaconda2 Linux (Bash for Ubuntu for Windows, Windows 10) .. same problem :-(

**Comment by santiagocasas** [comment]
I'm javing the same problem on Linux Mint after doing:

conda update conda

Actually many things in my system were ruined with this, openssh, libcrypto and so on.

**Comment by iparask** [comment]
I am also getting the same error when trying to install either Anaconda2 or miniconda2 for linux using the Ubuntu app offered for windows 10

**Comment by mingwandroid** [comment]
Please test the previews here: https://repo.continuum.io/pkgs/misc/preview/

**Comment by iparask** [comment]
Miniconda rc installation failed with:
```
installing: conda-4.3.29-py27h13e2077_0 ...
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/home/iparask/miniconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
installation finished.
Do you wish the installer to prepend the Miniconda2 install location
to PATH in your /home/iparask/.bashrc ? [yes|no]
[no] >>> no
```

Anaconda2 dev1 did not show any error, but when I tried to install a package or create an environment variable through conda I got a ```conda not found message```

**Comment by mingwandroid** [comment]
4.3.29 is 9 days old, you should be using 4.3.30.

**Comment by iparask** [comment]
Okay, it works! Thank you!
