### ISSUE TITLE
Conda completely broken after conda update on OSX Mojave

### ISSUE THREAD

**Issue by din14970** [conda/conda#10202]
Maybe my issue is quite specific and may not be an issue for most people. I'm posting it here mainly to ask whether there is a quick fix besides reinstalling conda.

## Current Behavior
Not a single conda command works anymore. Any conda command is met with:

```bash
Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 151, in main
    from ..exceptions import conda_exception_handler
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 25, in <module>
    from .common.io import dashlist, timeout
  File "/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 29, in <module>
    from .path import expand
  File "/anaconda3/lib/python3.6/site-packages/conda/common/path.py", line 17, in <module>
    from distutils.spawn import find_executable
  File "/anaconda3/lib/python3.6/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/nielscautaerts/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 5, in <module>
    import distutils.core
  File "/anaconda3/lib/python3.6/site-packages/_distutils_hack/__init__.py", line 82, in create_module
    return importlib.import_module('._distutils', 'setuptools')
  File "/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'setuptools._distutils'
```

### Steps to Reproduce
I was alerted of a new version of conda and tried to update with

```
$ conda update -n base conda
```

However, I got some error at the end of the process, basically the same one as mentioned above. I was alerted everything would roll back. Conda was still working but always gave me this error when I tried to update anything. I figured there was some issue with setuptools, so I tried:

```
$ conda install setuptools
```

I was met with the same issue, and in hindsignt it was pretty stupid. After this no conda command works anymore and I always get the error message as shown above.

## Expected Behavior
For conda to update and function.

## Environment Information
Since the "conda" command doesn't work at all anymore I unfortunately can't provide this information. I know I was using conda 4.8.3 and was trying to update to 4.8.4. I'm on Mac OSX Mojave. My condarc looks as follows:

```
env_prompt: ({name})
channels:
  - conda-forge
  - defaults
channel_priority: strict
```

I guess something got messed up along the way by installing stuff from conda-forge into the base environment.

Is there any way to fix this other than doing a full re-install?

**Comment by Spazzlo** [comment]
I'm having the same import error on Linux, but with some package installs. Since the conda command works for me, I can provide debugging info if it's required.

**Comment by pglombardo** [comment]
This is related to a bad setuptools release.  `export SETUPTOOLS_USE_DISTUTILS=stdlib` is a temporary work-around: https://github.com/pypa/setuptools/issues/2350

**Comment by din14970** [comment]
unfortunately it was such a long time ago I don't have any more details. I think I simply reinstalled conda to fix the issue at the time.
