### ISSUE TITLE
Unexpected error on trying to create environment using conda env create -f environment.yml

### ISSUE THREAD

**Issue by ManuMahadevaswamy** [conda/conda#10212]
````
(base) manu@manu-VirtualBox:~$ conda env create -f environment.yml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
```
Traceback (most recent call last):
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 86, in execute
    spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
    if spec.can_handle():
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
    self._environment = env.from_file(self.filename)
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda_env/env.py", line 157, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda_env/env.py", line 138, in from_yaml
    data = yaml_safe_load(yamlstr)
  File "/home/manu/miniconda3/lib/python3.8/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
    return yaml.safe_load(string, version="1.2")
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/main.py", line 980, in safe_load
    return load(stream, SafeLoader, version)
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/main.py", line 935, in load
    return loader._constructor.get_single_data()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/composer.py", line 104, in compose_document
    self.parser.get_event()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/parser.py", line 163, in get_event
    self.current_event = self.state()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/parser.py", line 239, in parse_document_end
    token = self.scanner.peek_token()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 182, in peek_token
    self.fetch_more_tokens()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 282, in fetch_more_tokens
    return self.fetch_value()
  File "/home/manu/miniconda3/lib/python3.8/site-packages/ruamel_yaml/scanner.py", line 651, in fetch_value
    raise ScannerError(
ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 128, column 34:
        <span style="background-color: #79b8ff;width: 0%;" class="Pro ... 
                                     ^ (line: 128)
```

`$ /home/manu/miniconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/manu/miniconda3/bin/conda
             CONDA_PREFIX=/home/manu/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/manu/miniconda3/bin/python
               CONDA_ROOT=/home/manu/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/manu/miniconda3/bin:/home/manu/miniconda3/bin:/home/manu/minicon
                          da3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/
                          bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

```
 active environment : base
active env location : /home/manu/miniconda3
        shell level : 1
   user config file : /home/manu/.condarc
```

 populated config files : /home/manu/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.31
       base environment : /home/manu/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/manu/miniconda3/pkgs
                          /home/manu/.conda/pkgs
       envs directories : /home/manu/miniconda3/envs
                          /home/manu/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Linux/5.4.0-40-generic ubuntu/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 
Timeout reached. No report sent.
````

**Comment by saucoide** [comment]
how does your `environment.yml` look? that's probably from a badly formatted yaml file
