### ISSUE TITLE
AttributeError: module 'platform' has no attribute 'linux_distribution'

### ISSUE THREAD

**Issue by sahilohe** [conda/conda#10246]
I got this error

 root@sahilohe: conda --version

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/fsociety/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fsociety/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/fsociety/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

**Comment by chenghlee** [comment]
Do you have `lsb_release` installed on your system? (You can use `command -v lsb_release` to check.)

**Comment by sahilohe** [comment]
This is what I got
  /usr/bin/lsb_release

**Comment by chenghlee** [comment]
How did you install conda? `connection.py` was removed from the code base a long time ago, so I suspect you are running an old, unsupported version.

**Comment by sahilohe** [comment]
I download the Anaconda3-2020.07-Linux-x86_64.sh file and simply executed it

**Comment by chenghlee** [comment]
Do you remember where you installed it? It looks like you have more than one version installed in `~/.local`. (Generally speaking, we advise against installing Anaconda into `~/.local`.)

**Comment by sahilohe** [comment]
it's in "/home/username/anaconda3"

**Comment by chenghlee** [comment]
It really looks like you have an old, incompatible version of conda installed into `~/.local`, . If you are _absolutely sure_ your current Aanconda installation is in `/home/username/anaconda3`, try running `pip uninstall conda`; if you get the following output indicating conda 4.3.x is installed in `~/.local`:
```
Found existing installation: conda 4.3.16
Uninstalling conda-4.3.16:
  Would remove:
    /home/user/.local/bin/conda
    /home/user/.local/lib/python3.8/site-packages/conda-4.3.16-py3.8.egg-info
    /home/user/.local/lib/python3.8/site-packages/conda/*
    /home/user/.local/lib/python3.8/site-packages/conda_env/*
  Would not remove (might be manually added):
    /home/user/.local/lib/python3.8/site-packages/conda/.version
Proceed (y/n)?
```
reply `y` to remove it and see if that fixes your issue.

**Comment by Shoklan** [comment]
Just posting since this also came up for me.
When I did the uninstall per the above comment, it didn't show the .local paths but it still fixed the issue and let it install correctly.

**Comment by tejeshvaish** [comment]
It workedd!!!! Thank you!

**Comment by ericsantosbr** [comment]
Worked here! Thank you!

**Comment by AhmedFakhry47** [comment]
Worked. Thank you !

**Comment by AbdelhamedAbdin** [comment]
you saved my life, Thx

**Comment by VarianceFang** [comment]
yyyyyyy saved my life! Thank you!

**Comment by rajeshmanchikanti10** [comment]
Thanks a lot!

**Comment by jasperhyp** [comment]
Great fix!  Looks like I installed conda via `pip` and also via the `.sh` release.
