### ISSUE TITLE
Anaconda3 initialization error

### ISSUE THREAD

**Issue by VicCruces** [conda/conda#10242]
## Current Behavior

Hello, 

First of all, I would like to apologize due to it is my first time that I report an issue.

### Steps to Reproduce

I was trying to install anaconda on Arch Linux following step by step the tutorial of the link https://docs.anaconda.com/anaconda/install/linux/, and I was in somehow successful because I have the following message:

> Thank you for installing Anaconda3!

But, I have also the following error when I said yes to the question:

> Do you wish the installer to initialize Anaconda3 by running conda init?
> My answer was 'yes'

And, I got the next error message:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/vcruces/programs/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vcruces/programs/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File `"/home/vcruces/.local/lib/python3.8/site-packages/conda/gateways/download.py",` line 16, in <module>
    from ..connection import CondaSession
  File "/home/vcruces/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

```
I was checking a little about the problem and it seems that the platform python module
does not support or do not have the object platform.linux_distribution for python 3.8. I attach the
link of python 3.8 platform module.
https://docs.python.org/3.8/library/platform.html

## Environment Information

```
I am using Arch Linux distribution and python 3.8
```

**Comment by VicCruces** [comment]
It was already commented:

https://github.com/conda/conda/issues/10139

**Comment by VicCruces** [comment]
I was trying during all the weekend and finally, I managed. It was a file conflict, I am so sorry. 
I will close this issue

**Comment by VicCruces** [comment]
/home/vcruces/.local/lib/python3.8/site-packages/conda/connection.py

**Comment by VicCruces** [comment]
I was trying during all the weekend and finally, I managed. It was a file conflict, I am so sorry.
I will close this issue

**Comment by joesp1998** [comment]
What needs to be done to fix this? I am having the same issue on Ubuntu 20.04.
Thanks!

**Comment by VicCruces** [comment]
Most likely, you have a file conflict. In my case, the solution was to remove all files, where anaconda was,
and to reinstall again from scratch. It was my solution, I hope it will fix it.

**Comment by joesp1998** [comment]
Thanks for the reply, that doesn't seem to have fixed it. I will keep looking.

**Comment by VicCruces** [comment]
Did you check your files in /home/user_name/.conda/ or in /home/user_name/.local/? 
In my case, I removed all previous conda files and I installed again. Perhaps, I was not
clear enough in my previous message.

**Comment by joesp1998** [comment]
I ended up completely uninstalling all python packages and that solved the issue. 
Thanks a lot for your help once again.

**Comment by VicCruces** [comment]
You are welcome, have a nice weekend
