### ISSUE TITLE
miniconda3 library error

### ISSUE THREAD

**Issue by cwb14** [conda/conda#10274]
Hi,

When I run any `conda` command, I get the following error message. This started happening three days ago. I tried reinstalling a fresh instillation of `miniconda3` but still seem to generated the same error report. For example, this error report was made with `conda install -c bioconda repeatmodeler `, but I can also generate with `conda search repeatmodeler`.

    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
            return self.connection.recv_into(*args, **kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
            self._raise_ssl_error(self._ssl, result)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1646, in _raise_ssl_error
            raise WantReadError()
        OpenSSL.SSL.WantReadError
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
            return self.connection.recv_into(*args, **kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
            self._raise_ssl_error(self._ssl, result)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
            raise SysCallError(errno, errorcode.get(errno))
        OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 425, in _error_catcher
            yield
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 752, in read_chunked
            self._update_chunk_length()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 682, in _update_chunk_length
            line = self._fp.fp.readline()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/socket.py", line 669, in readinto
            return self._sock.recv_into(b)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 328, in recv_into
            return self.recv_into(*args, **kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
            raise SocketError(str(e))
        OSError: (104, 'ECONNRESET')
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/requests/models.py", line 751, in generate
            for chunk in self.raw.stream(chunk_size, decode_content=True):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 560, in stream
            for line in self.read_chunked(amt, decode_content=decode_content):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 781, in read_chunked
            self._original_response.close()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
            self.gen.throw(type, value, traceback)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
            raise ProtocolError("Connection broken: %r" % e, e)
        urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
            return getattr(module, func_name)(args, parser)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
            install(args, parser, 'install')
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
            unlink_link_transaction = solver.solve_for_transaction(
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
            unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
            final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
            ssc = self._collect_all_metadata(ssc)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
            return f(*args, **kwds)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
            index, r = self._prepare(prepared_specs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1010, in _prepare
            reduced_index = get_reduced_index(self.prefix, self.channels,
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 227, in get_reduced_index
            new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 105, in query_all
            result = tuple(concat(executor.map(subdir_query, channel_urls)))
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
            yield fs.pop().result()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
            return self.__get_result()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
            raise self._exception
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 97, in <lambda>
            subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 110, in query
            self.load()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 174, in load
            _internal_state = self._load()
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 244, in _load
            raw_repodata_str = fetch_repodata_remote_request(
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 484, in fetch_repodata_remote_request
            resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
            return self.request('GET', url, **kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
            resp = self.send(prep, **send_kwargs)
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 683, in send
            r.content
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/requests/models.py", line 829, in content
            self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
          File "/storage/home/cwb14/work/miniconda3/lib/python3.8/site-packages/requests/models.py", line 754, in generate
            raise ChunkedEncodingError(e)
        requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
    
    `$ /storage/home/cwb14/work/miniconda3/bin/conda install -c bioconda repeatmodeler`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=repeatmodeler
                    CONDA_EXE=/storage/home/cwb14/work/miniconda3/bin/conda
                 CONDA_PREFIX=/storage/home/cwb14/work/miniconda3/envs/repeatmodeler
               CONDA_PREFIX_1=/storage/home/cwb14/work/miniconda3
        CONDA_PROMPT_MODIFIER=(repeatmodeler)
             CONDA_PYTHON_EXE=/storage/home/cwb14/work/miniconda3/bin/python
                   CONDA_ROOT=/storage/home/cwb14/work/miniconda3
                  CONDA_SHLVL=2
                     INFOPATH=/storage/home/c/cwb14/.linuxbrew/share/info:
      LMOD_DEFAULT_MODULEPATH=/opt/aci/modulefiles/Core:/etc/modulefiles:/usr/share/modulefiles:/usr
                              /share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/l
                              mod/modulefiles/Core
            LMOD_PACKAGE_PATH=/opt/aci/modulefiles
                      MANPATH=/storage/home/c/cwb14/.linuxbrew/share/man:::
                   MODULEPATH=/opt/aci/modulefiles/Core:/etc/modulefiles:/usr/share/modulefiles:/usr
                              /share/modulefiles/Linux:/usr/share/modulefiles/Core:/usr/share/lmod/l
                              mod/modulefiles/Core
                         PATH=/storage/home/cwb14/work/miniconda3/bin:/Users/chrisbenson/work/minico
                              nda3/bin:/storage/home/c/cwb14/.linuxbrew/bin:/storage/home/c/cwb14/.l
                              inuxbrew/sbin:/storage/home/cwb14/bin:/storage/home/cwb14/work/minicon
                              da3/envs/repeatmodeler/bin:/storage/home/cwb14/work/miniconda3/condabi
                              n:/usr/lpp/mmfs/bin:/usr/local/bin:/usr/local/sbin:/usr/lib64/qt-3.3/b
                              in:/opt/moab/bin:/opt/mam/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/opens
                              sh-7.4p1-el7/bin:/usr/local/sbin:/opt/ibutils/bin:/opt/puppetlabs/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : repeatmodeler
        active env location : /storage/home/cwb14/work/miniconda3/envs/repeatmodeler
                shell level : 2
           user config file : /storage/home/cwb14/.condarc
     populated config files : /storage/home/cwb14/.condarc
              conda version : 4.8.3
        conda-build version : not installed
             python version : 3.8.3.final.0
           virtual packages : __glibc=2.12
           base environment : /storage/home/cwb14/work/miniconda3  (writable)
               channel URLs : https://conda.anaconda.org/bioconda/linux-64
                              https://conda.anaconda.org/bioconda/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /storage/home/cwb14/work/miniconda3/pkgs
                              /storage/home/cwb14/.conda/pkgs
           envs directories : /storage/home/cwb14/work/miniconda3/envs
                              /storage/home/cwb14/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/2.6.32-754.33.1.el6.x86_64 rhel/6.10 glibc/2.12
                    UID:GID : 18521:18521
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.I cant tell if this is a `conda` bug or a dependency issue that I unknowingly caused. Any feedback is helpful. 

Thanks,
Chris

**Comment by chenghlee** [comment]
Can you please provide the output of `conda config --show-sources` and `conda list --show-channel-urls`? I'm having trouble replicating this issue. (HTTP 104 errors are typically a local network issue, so retrying later may also help.)

**Comment by cwb14** [comment]
Thanks for the quick feedback. Ahhh, I didn't realize it was a network issue. I was barking up the wrong tree then. I played with my network settings and seem to gotten rid of the error message. For reference, here is the output of `conda list --show-channel-urls`:

```
# packages in environment at /Users/cbenson/miniconda3:
#
# Name                    Version                   Build  Channel
bcftools                  1.11                 he8d9d6d_0    bioconda
brotlipy                  0.7.0           py37h60d8a13_1000    conda-forge
bzip2                     1.0.8                haf1e3a3_3    conda-forge
c-ares                    1.16.1               haf1e3a3_3    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge
cffi                      1.14.3           py37hf5b7abd_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1007    conda-forge
conda                     4.8.5            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.7.0            py37h60d8a13_5    conda-forge
cryptography              3.1.1            py37h94e4008_0    conda-forge
gsl                       2.6                  ha2d443c_0    conda-forge
htslib                    1.11                 h422799e_0    bioconda
idna                      2.10               pyh9f0ad1d_0    conda-forge
krb5                      1.17.1               h75d18d8_3    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    10.0.1               h5f48129_0    conda-forge
libdeflate                1.6                  h0b31af3_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.2.1             hb1e8313_1007    conda-forge
libgfortran               4.0.0               h2d743fc_11    conda-forge
libgfortran4              7.5.0               h2d743fc_11    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.10          openmp_h63d9170_4    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
llvm-openmp               10.0.1               h28b9765_0    conda-forge
ncurses                   6.2                  hb1e8313_1    conda-forge
openssl                   1.1.1h               haf1e3a3_0    conda-forge
perl                      5.30.3               h6156909_1    conda-forge
pip                       20.2.3                     py_0    conda-forge
pycosat                   0.6.3           py37h60d8a13_1004    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.8           hc9dea61_1_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
ruamel_yaml               0.15.80         py37h60d8a13_1002    conda-forge
setuptools                49.6.0           py37hc8dfbb8_1    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h960bd1c_0    conda-forge
tk                        8.6.10               hb0a8c7a_0    conda-forge
tqdm                      4.50.0             pyh9f0ad1d_0    conda-forge
urllib3                   1.25.10                    py_0    conda-forge
wheel                     0.35.1             pyh9f0ad1d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11            h7795811_1009    conda-forge
```

Here is the output of `conda config --show-sources`:

```
==> /Users/cbenson/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
```

Hopefully the network error doesn't reoccur! I'll let you know if it does. Thank you! I greatly appreciate your help :)

**Comment by chenghlee** [comment]
What does `curl -L -D/dev/stderr -s -o/dev/null https://conda.anaconda.org/bioconda/linux-64/repodata.json.bz2` output?

**Comment by cwb14** [comment]
Here is the output of `curl -L -D/dev/stderr -s -o/dev/null https://conda.anaconda.org/bioconda/linux-64/repodata.json.bz2`

```
HTTP/1.1 200 OK
Date: Mon, 12 Oct 2020 17:14:13 GMT
Content-Type: application/json
Content-Length: 2519156
Connection: keep-alive
Set-Cookie: __cfduid=d6fbc98b97b01fd91072cbaaefb954cd51602522853; expires=Wed, 11-Nov-20 17:14:13 GMT; path=/; domain=.anaconda.org; HttpOnly; SameSite=Lax
CF-Ray: 5e1274b8bbece11a-IAD
Accept-Ranges: bytes
Age: 18496
Cache-Control: public, max-age=1200
ETag: "06ff42f134129ff6291becd841b58e7a"
Expires: Mon, 12 Oct 2020 17:34:13 GMT
Last-Modified: Mon, 12 Oct 2020 11:44:32 GMT
Vary: Accept-Encoding
CF-Cache-Status: HIT
cf-request-id: 05bf6747730000e11ae0bf4200000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
x-amz-id-2: evBt5I2lIBUagL8/UTkSDrw/MQf+DIUtcFTZckqSayKYzU7jcdn6YIbRkzIJMpEoqSIdYc5w15A=
x-amz-request-id: DX6S9QDX9NERAJCR
x-amz-version-id: null
Server: cloudflare
```
Thanks!

**Comment by cwb14** [comment]
Apparently this is an issue with our HPC cluster. I contacted our IT and they are working to resolve it. Thank you for notifying me that it was a networking error! That helped send me on the right path.

Best,
Chris

**Comment by schorlton** [comment]
Hi @cwb14, I'm wondering what the issue was on your HPC cluster or if you know the resolution? I'm getting the same error, connected directly to my modem.

**Comment by cwb14** [comment]
Unfortunately, IT didn't specify. They just said that they were aware of the issue and would let me know when it was resolved. If you are using an HPC, then you might wanna contact admin. If running locally on desktop, maybe play around with network settings?? Sorry I cant be more help.

**Comment by schorlton** [comment]
> Unfortunately, IT didn't specify. They just said that they were aware of the issue and would let me know when it was resolved. If you are using an HPC, then you might wanna contact admin. If running locally on desktop, maybe play around with network settings?? Sorry I cant be more help.

Thanks for responding!
