### ISSUE TITLE
Import/platform no attribute 'linux_distribution' unexpected error occured.

### ISSUE THREAD

**Issue by nerd2ninja** [conda/conda#10276]
This is my first time trying to use conda. When running conda --help or conda init or conda anything really, I get this exact same traceback. I figured eh yeah I ran the script and restarted my computer but maybe there's some more configuring it wants or something, but I can't tell from this what it is that it wants. I'm a lot more familiar with ruby so this is a learning curve for me.

Traceback (most recent call last):
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/waifuaiv2/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/waifuaiv2/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/waifuaiv2/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()

**Comment by chenghlee** [comment]
Can you please provide the output of `pip3 list --format=columns | grep -i conda`?

**Comment by nerd2ninja** [comment]
This is the output of the command you told me to run:

waifuaiv2@waifuaiv2:~/brain/gpt-2$ pip3 list --format=columns | grep -i conda
conda                   4.3.16
waifuaiv2@waifuaiv2:~/brain/gpt-2$

Oh and I forgot to mention, I'm running Ubuntu 20.04

**Comment by chenghlee** [comment]
Somehow, you ended up with an old, incompatible version of the conda libraries. Try `/usr/bin/pip3 uninstall conda`, and if you get something like the following output:
```
Found existing installation: conda 4.3.16
Uninstalling conda-4.3.16:
  Would remove:
    /home/user/.local/bin/conda
    /home/user/.local/lib/python3.8/site-packages/conda-4.3.16-py3.8.egg-info
    /home/user/.local/lib/python3.8/site-packages/conda/*
    /home/user/.local/lib/python3.8/site-packages/conda_env/*
  Would not remove (might be manually added):
    /home/user/.local/lib/python3.8/site-packages/conda/.version
Proceed (y/n)?
```
reply `y` to remove it and see if that fixes your issue.

**Comment by nerd2ninja** [comment]
Huh, weird. Yeah it uninstalled and now I can run conda commands. Thanks for your help!
