### ISSUE TITLE
error installing package with conda

### ISSUE THREAD

**Issue by ekuser** [conda/conda#1028]
Iwas trying to install the egenix-mx-base package using conda an got the following error: 

$ conda install egenix-mx-base-3.2.8.tar.bz2 
[      COMPLETE      ] |##################################################| 100%
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the#############| 100%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 210, in install
    verbose=not args.quiet)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/misc.py", line 213, in install_local_packages
    execute_actions(actions, verbose=verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 569, in execute_plan
    link(prefix, arg, index=index)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 525, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 499, in link
    files = list(yield_lines(join(info_dir, 'files')))
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 191, in yield_lines
    for line in open(path):
IOError: [Errno 2] No such file or directory: '/opt/anaconda/pkgs/egenix-mx-base-3.2.8/info/files'

$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.7.3
```

  conda-build version : 1.3.5
       python version : 2.7.8.final.0
     requests version : 2.5.0
     root environment : /opt/anaconda  (writable)
  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

The files were installed in /opt/anaconda/pkgs/egenix-mx-base-3.2.8/, but there is no info directory  created and I cannot import any of libraries from the package. 

Any suggestions?

**Comment by soapy1** [comment]
@ekuser is this still an issue for you?
