### ISSUE TITLE
conda update conda - error report - POP os

### ISSUE THREAD

**Issue by AlbertUlysses** [conda/conda#10301]
## Current Behavior

Receiving an error report while trying to update conda
I tried to remove the conda ssl verify and allowing conda to downgrade, neither helped
### Steps to Reproduce

```
conda install conda
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/session.py", line 60, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1021, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/albertulysses/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/home/albertulysses/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/home/albertulysses/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/home/albertulysses/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
        self.load()
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 470, in fetch_repodata_remote_request
        session = CondaSession()
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/session.py", line 62, in __call__
        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
      File "/home/albertulysses/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/session.py", line 88, in __init__
        raise_on_status=False)
    TypeError: __init__() got an unexpected keyword argument 'raise_on_status'

`$ /home/albertulysses/anaconda3/bin/conda update conda`

```

## Expected Behavior

conda should update to latest

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : base
    active env location : /home/albertulysses/anaconda3
            shell level : 1
       user config file : /home/albertulysses/.condarc
 populated config files : /home/albertulysses/.condarc
          conda version : 4.8.4
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages : __glibc=2.31
       base environment : /home/albertulysses/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/albertulysses/anaconda3/pkgs
                          /home/albertulysses/.conda/pkgs
       envs directories : /home/albertulysses/anaconda3/envs
                          /home/albertulysses/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.24.0 CPython/3.7.7 Linux/5.4.0-7634-generic pop/20.04 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
allow_conda_downgrades: True
ssl_verify: False

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# Name                    Version                   Build  Channel
_anaconda_depends         2020.02                  py37_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_libgcc_mutex             0.1                        main    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  custom                   py37_1    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.12                   py37_1    defaults
anaconda-project          0.8.4                      py_0    defaults
argh                      0.26.2                   py37_0    defaults
asn1crypto                1.3.0                    py37_0    defaults
astroid                   2.3.3                    py37_0    defaults
astropy                   4.0.1.post1      py37h7b6447c_1    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     19.3.0                     py_0    defaults
autopep8                  1.5.3                      py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.2.0                      py_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.9.1                    py37_0    defaults
bitarray                  1.2.2            py37h7b6447c_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.5                      py_0    defaults
blosc                     1.19.0               hd408876_0    defaults
bokeh                     2.1.1                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.3.2            py37heb32a55_1    defaults
brotlipy                  0.7.0           py37h7b6447c_1000    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2020.6.24                     0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2020.6.20                py37_0    defaults
cffi                      1.14.0           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.1.2                      py_0    defaults
cloudpickle               1.4.1                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.3                      py_0    defaults
conda                     4.8.4                    py37_0    defaults
conda-build               3.18.11                  py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.1            py37h7b6447c_0    defaults
conda-verify              3.4.2                      py_1    defaults
configargparse            1.2.3                    pypi_0    pypi
contextlib2               0.6.0.post1                py_0    defaults
cryptography              2.9.2            py37h1ba5d50_0    defaults
curl                      7.71.0               hbc83047_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.20          py37he6710b0_0    defaults
cytoolz                   0.10.1           py37h7b6447c_0    defaults
dask                      2.19.0                     py_0    defaults
dask-core                 2.19.0                     py_0    defaults
dbus                      1.13.16              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
diff-match-patch          20181111                   py_0    defaults
distributed               2.19.0                   py37_0    defaults
docutils                  0.16                     py37_1    defaults
emoji                     0.5.4                    pypi_0    pypi
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.9                he6710b0_2    defaults
fastcache                 1.1.0            py37h7b6447c_0    defaults
filelock                  3.0.12                     py_0    defaults
flake8                    3.8.3                      py_0    defaults
flask                     1.1.2                      py_0    defaults
flask-basicauth           0.2.0                    pypi_0    pypi
flask-sqlalchemy          2.4.1                    pypi_0    pypi
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.10.2               h5ab3b9f_0    defaults
fribidi                   1.0.9                h7b6447c_0    defaults
fsspec                    0.7.4                      py_0    defaults
future                    0.18.2                   py37_1    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    20.6.2           py37h7b6447c_0    defaults
geventhttpclient          1.4.2                    pypi_0    pypi
glib                      2.63.1               h5a9c865_0    defaults
glob2                     0.7                        py_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py37h10f8cd9_2    defaults
graphite2                 1.3.14               h23475e2_0    defaults
greenlet                  0.4.16           py37h7b6447c_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.10.0           py37h7918eee_0    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
heapdict                  1.0.1                      py_0    defaults
html5lib                  1.1                        py_0    defaults
hypothesis                5.18.3                     py_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.10                       py_0    defaults
imageio                   2.8.0                      py_0    defaults
imagesize                 1.2.0                      py_0    defaults
importlib-metadata        1.7.0                    py37_0    defaults
importlib_metadata        1.7.0                         0    defaults
intel-openmp              2020.1                      217    defaults
intervaltree              3.0.2                      py_0    defaults
ipykernel                 5.3.0            py37h5ca1d4c_0    defaults
ipython                   7.16.1           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.17.1                   py37_0    defaults
jeepney                   0.4.3                      py_0    defaults
jinja2                    2.11.2                     py_0    defaults
joblib                    0.15.1                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
json5                     0.9.5                      py_0    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            6.1.3                      py_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.3                    py37_0    defaults
jupyterlab                2.1.5                      py_0    defaults
jupyterlab_server         1.1.5                      py_0    defaults
keyring                   21.2.1                   py37_0    defaults
kiwisolver                1.2.0            py37hfd86e86_0    defaults
krb5                      1.18.2               h173b8e3_0    defaults
lazy-object-proxy         1.5.0            py37h7b6447c_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libarchive                3.4.2                h62408e4_0    defaults
libcurl                   7.71.0               h20c2e04_0    defaults
libedit                   3.1.20191231         h7b6447c_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblief                   0.10.1               he6710b0_0    defaults
libllvm9                  9.0.1                h4a3c616_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libspatialindex           1.9.3                he6710b0_0    defaults
libssh2                   1.9.0                h1ba5d50_1    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.1.0                h2733197_1    defaults
libtool                   2.4.6                h7b6447c_5    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.10               he19cac6_1    defaults
libxslt                   1.1.34               hc22bd24_0    defaults
llvmlite                  0.33.0           py37hd408876_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.5.1            py37hefd8a0e_0    defaults
lz4-c                     1.9.2                he6710b0_0    defaults
lzo                       2.10                 h7b6447c_2    defaults
markdown2                 2.3.8                    pypi_0    pypi
markupsafe                1.1.1            py37h7b6447c_0    defaults
matplotlib                3.2.2                         0    defaults
matplotlib-base           3.2.2            py37hef1b27d_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h7b6447c_0    defaults
mkl                       2020.1                      217    defaults
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.1.0            py37h23d657b_0    defaults
mkl_random                1.1.1            py37h0573a6f_0    defaults
mock                      4.0.2                      py_0    defaults
more-itertools            8.4.0                      py_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            1.0.0            py37hfd86e86_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  5.0.7                      py_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
networkx                  2.4                        py_0    defaults
nltk                      3.5                        py_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.3                    py37_0    defaults
numba                     0.50.1           py37h0573a6f_0    defaults
numexpr                   2.7.1            py37h423224d_0    defaults
numpy                     1.18.5           py37ha1c710e_0    defaults
numpy-base                1.18.5           py37hde5b4d6_0    defaults
numpydoc                  1.0.0                      py_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  3.0.3                      py_0    defaults
openssl                   1.1.1g               h7b6447c_0    defaults
packaging                 20.4                       py_0    defaults
pandas                    1.1.0            py37he6710b0_0    defaults
pandoc                    2.9.2.1                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.1.0                      py_0    defaults
patchelf                  0.11                 he6710b0_0    defaults
path                      13.1.0                   py37_0    defaults
path.py                   12.4.0                        0    defaults
pathlib2                  2.3.5                    py37_0    defaults
pathtools                 0.1.2                      py_1    defaults
patsy                     0.5.1                    py37_0    defaults
pcre                      8.44                 he6710b0_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.8.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    7.1.2            py37hb39fc2d_0    defaults
pip                       20.1.1                   py37_1    defaults
pixman                    0.40.0               h7b6447c_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.13.1                   py37_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.8.0                      py_0    defaults
prompt-toolkit            3.0.5                      py_0    defaults
prompt_toolkit            3.0.5                         0    defaults
psutil                    5.7.0            py37h7b6447c_0    defaults
psycopg2                  2.8.4                    pypi_0    pypi
ptyprocess                0.6.0                    py37_0    defaults
py                        1.9.0                      py_0    defaults
py-lief                   0.10.1           py37h403a769_0    defaults
pycodestyle               2.6.0                      py_0    defaults
pycosat                   0.6.3            py37h7b6447c_0    defaults
pycparser                 2.20                       py_0    defaults
pycrypto                  2.6.1           py37h7b6447c_10    defaults
pycurl                    7.43.0.5         py37h1ba5d50_0    defaults
pydocstyle                5.0.2                      py_0    defaults
pyflakes                  2.2.0                      py_0    defaults
pygments                  2.6.1                      py_0    defaults
pylint                    2.4.4                    py37_0    defaults
pyodbc                    4.0.30           py37he6710b0_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.7                      py_0    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.16.0           py37h7b6447c_0    defaults
pysocks                   1.7.1                    py37_0    defaults
pytables                  3.6.1            py37h71ec239_0    defaults
pytest                    5.4.3                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.8.0                      py_0    defaults
pytest-astropy-header     0.1.2                      py_0    defaults
pytest-doctestplus        0.7.0                      py_0    defaults
pytest-openfiles          0.5.0                      py_0    defaults
pytest-remotedata         0.3.2                    py37_0    defaults
python                    3.7.7           hcf32534_0_cpython    defaults
python-dateutil           2.8.1                      py_0    defaults
python-jsonrpc-server     0.3.4                      py_0    defaults
python-language-server    0.33.3                   py37_0    defaults
python-libarchive-c       2.9                        py_0    defaults
pytz                      2020.1                     py_0    defaults
pywavelets                1.1.1            py37h7b6447c_0    defaults
pyxdg                     0.26                       py_0    defaults
pyyaml                    5.3.1            py37h7b6447c_1    defaults
pyzmq                     19.0.1           py37he6710b0_1    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtawesome                 0.7.2                      py_0    defaults
qtconsole                 4.7.5                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
readline                  8.0                  h7b6447c_0    defaults
regex                     2020.6.8         py37h7b6447c_0    defaults
requests                  2.5.0                    pypi_0    pypi
ripgrep                   11.0.2               he32d670_0    defaults
rope                      0.17.0                     py_0    defaults
rtree                     0.9.4                    py37_1    defaults
ruamel_yaml               0.15.87          py37h7b6447c_1    defaults
scikit-image              0.16.2           py37h0573a6f_0    defaults
scikit-learn              0.23.1           py37h423224d_0    defaults
scipy                     1.5.0            py37h0b6359f_0    defaults
seaborn                   0.10.1                     py_0    defaults
secretstorage             3.1.2                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                47.3.1                   py37_0    defaults
simpledbf                 0.2.6                    pypi_0    pypi
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.8.0                    pypi_0    pypi
slack-export-viewer       1.0.0                    pypi_0    pypi
snappy                    1.1.8                he6710b0_0    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcollections         1.2.1                      py_0    defaults
sortedcontainers          2.2.2                      py_0    defaults
soupsieve                 2.0.1                      py_0    defaults
sphinx                    3.1.1                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.2                      py_0    defaults
sphinxcontrib-devhelp     1.0.2                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.3                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.3                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.4                      py_0    defaults
sphinxcontrib-websupport  1.2.3                      py_0    defaults
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.2                    py37_0    defaults
sqlalchemy                1.3.18           py37h7b6447c_0    defaults
sqlite                    3.32.3               h62c20be_0    defaults
statsmodels               0.11.1           py37h7b6447c_0    defaults
sympy                     1.6                      py37_0    defaults
tbb                       2020.0               hfd86e86_0    defaults
tblib                     1.6.0                      py_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.1                     py_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.4            py37h7b6447c_1    defaults
tqdm                      4.47.0                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
typing_extensions         3.7.4.2                    py_0    defaults
ujson                     1.33                     pypi_0    pypi
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h14c3975_0    defaults
urllib3                   1.25.9                     py_0    defaults
visidata                  1.5.2                      py_0    conda-forge
watchdog                  0.10.3                   py37_0    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  1.0.1                      py_0    defaults
wheel                     0.34.2                   py37_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
wrapt                     1.12.1           py37h7b6447c_1    defaults
wurlitzer                 2.0.0                    py37_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.2.9                      py_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xmltodict                 0.12.0                     py_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yapf                      0.30.0                     py_0    defaults
zeromq                    4.3.2                he6710b0_2    defaults
zict                      2.0.0                      py_0    defaults
zipp                      3.1.0                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zope                      1.0                      py37_1    defaults
zope.event                4.4                      py37_0    defaults
zope.interface            4.7.1            py37h7b6447c_0    defaults
zstd                      1.4.4                h0b5b093_3    defaults

```
</p></details>
con

**Comment by AlbertUlysses** [comment]
ended up uninstalling and reinstalling conda. the issue could have occured when I updated my os.
