### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by rexdougie** [conda/conda#10327]
```
Traceback (most recent call last):
  File "/home/doug/.local/lib/python3.8/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(_args, *_kwargs)
  File "/home/doug/.local/lib/python3.8/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/doug/anaconda3/lib/python3.8/importlib/**init**.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/doug/.local/lib/python3.8/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/doug/.local/lib/python3.8/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/doug/.local/lib/python3.8/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/doug/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/doug/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/doug/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/doug/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/doug/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/doug/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/doug/.local/lib/python3.8/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/doug/.local/lib/python3.8/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/doug/.local/lib/python3.8/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/doug/.local/lib/python3.8/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/doug/.local/lib/python3.8/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/doug/.local/lib/python3.8/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/doug/.local/lib/python3.8/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/doug/.local/lib/python3.8/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/doug/.local/lib/python3.8/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/doug/.local/lib/python3.8/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/doug/.local/lib/python3.8/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/home/doug/.local/lib/python3.8/site-packages/conda/connection.py", line 44, in <module>
    distinfo = platform.linux_distribution()
AttributeError: module 'platform' has no attribute 'linux_distribution'
If you'd prefer that conda's base environment not be activated on startup, 
   set the auto_activate_base parameter to false: 

conda config --set auto_activate_base false

Thank you for installing Anaconda3!
```

**Comment by chenghlee** [comment]
You may have picked up an older, incompatible version from pypi; try running `/usr/bin/pip3 uninstall conda`, and if you get something like the following output:
```
Found existing installation: conda 4.3.16
Uninstalling conda-4.3.16:
  Would remove:
    /home/user/.local/bin/conda
    /home/user/.local/lib/python3.8/site-packages/conda-4.3.16-py3.8.egg-info
    /home/user/.local/lib/python3.8/site-packages/conda/*
    /home/user/.local/lib/python3.8/site-packages/conda_env/*
  Would not remove (might be manually added):
    /home/user/.local/lib/python3.8/site-packages/conda/.version
Proceed (y/n)?
```
reply `y` to remove it and see if that fixes your issue.

**Comment by SpethHJH** [comment]
I got the same issue with you.
After installing conda under root, I switched to another user, and pasted the following code to ~/.bashrc:

`# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/amax/anaconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/amax/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/home/amax/anaconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/amax/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<`

Then:
`source ~/.bashrc`

But failed to activate the environment.
When I run `conda` alone, I got the same issue with you.

**Comment by beeankha** [comment]
@SpethHJH what you are reporting seems to be a different issue than the one that was originally filed here. Closing this issue; if the problems you described above are persisting, please open a new ticket.
