### ISSUE TITLE
"conda update conda" error

### ISSUE THREAD

**Issue by drZhan** [conda/conda#10333]
Hi guys, recently I'd updated the conda via 'conda update conda', but it ended up something weird. I've tried uninstalled and reinstalled the conda, however, the error was the same one. By the way I run the conda under the window wsl for ubuntu.

Here are the error report.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 317, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 346, in handle_txn
        unlink_link_transaction.execute()
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 231, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 590, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/link.py", line 411, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/d/Ubuntu/miniconda3/lib/python3.8/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/d/Ubuntu/miniconda3/pkgs/ncurses-6.2-he1b5a44_2/share/terminfo/N/NCR260VT300WPP'

`$ /mnt/d/Ubuntu/miniconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/mnt/d/Ubuntu/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/mnt/d/Ubuntu/miniconda3/bin/python
               CONDA_ROOT=/mnt/d/Ubuntu/miniconda3
              CONDA_SHLVL=0
                     PATH=/mnt/d/Ubuntu/miniconda3/bin:/mnt/d/Ubuntu/miniconda3/condabin:/usr/lo
                          cal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
                          local/games:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/Syst
                          em32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0:/mnt/c/Window
                          s/System32/OpenSSH:/mnt/c/Users/Zhanjr/AppData/Local/Microsoft/Windows
                          Apps:/mnt/d/Program Files/Bandizip:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/zhanjr/.condarc
 populated config files : /home/zhanjr/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.31
       base environment : /mnt/d/Ubuntu/miniconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/d/Ubuntu/miniconda3/pkgs
                          /home/zhanjr/.conda/pkgs
       envs directories : /mnt/d/Ubuntu/miniconda3/envs
                          /home/zhanjr/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/4.4.0-19041-Microsoft ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

**Comment by chenghlee** [comment]
Can you provide the output of `findmnt -T /mnt/d/Ubuntu/miniconda3`?

**Comment by ewidl** [comment]
I experience the same problem. Even uninstalling and installing another version of miniconda did not help ...

Any news on this? Were you able to solve this?

**Comment by atsuyaw** [comment]
When I tried to install miniconda, I also encountered this problem.

In my case, the problem could not been cleared by just replacing the files two file: `pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/ncr260vt300wpp` and  `pkgs/ncurses-6.2-h58526e2_4/share/terminfo/E/Eterm` by ones provied as ncurses pkg referencing @cvjjm's above https://github.com/conda/conda/issues/10333#issuecomment-836803901.

But replacing `ncr260vt300wpp` by `/miniconda3/share/terminfo/N/ncr260vt300wpp` instead of ncurses's one, conda was installed successfully.

Thank you

**Comment by agilgur5** [comment]
I removed the entire directory `pkgs/ncurses-6.2-h58526e2_4` dir and then on re-install / upgrade / update it replaced it and started working normally again

**Comment by dzyim** [comment]
I tried all the other advices above and failed.
And then I changed the installation path from /mnt/d/... to ~/..., and it works now. Thanks to @ewidl 
(on Windows WSL with Ubuntu)

**Comment by joshuacwnewton** [comment]
I've run into this issue in multiple different contexts, and I can confirm that the problem occurs when I mix the "standard Windows file system" with the "WSL file system", as mentioned by https://github.com/conda/conda/issues/10333#issuecomment-746659284.

### Context 1: Vampire/setup-wsl@v1

When I used the [Vampire/setup-wsl@v1](https://github.com/marketplace/actions/setup-wsl) GitHub Action, the `$GITHUB_WORKSPACE`/working directory for my project remained in the "Windows" part of the filesystem:

```
/mnt/d/a/repo_name/repo_name
```

My GitHub Actions workflow involved [`actions/checkout@v2`](https://github.com/actions/checkout) + installing my project into a `conda` environment. I wasn't changing directories from the default, so I was unknowingly working within the "Windows" part of the filesystem the whole time. To fix it, I made sure that any subsequent `run` steps were performed in `~` instead.

### Context 2: Starting WSL via the command line

This time was on my personal computer, where I fell into a silly trap:

* I opened cmd via the Start Menu (which stuck me in `C:/Users/username` by default)
* Then I used `wsl -d Ubuntu` to start WSL, not realizing that this caused me to stay in my Windows user directory on `/mnt/c/users/username`. 
* Then I unknowingly installed conda in my Windows user directory from WSL, which caused the error. Oops. 😅 

And, again keeping conda inside WSL's filesystem fixed the issue for me.

**Comment by aubrey-y** [comment]
@joshuacwnewton what do you mean "keeping conda inside WSL's filesystem"? Should miniconda not be installed in `/mnt/c/Users/$$USERNAME$$/miniconda`?

**Comment by cvjjm** [comment]
I guess what is meant is to not use a part of the directory tree that is shared with Windows.

**Comment by jwalewski** [comment]
Hello all,

I was attempting to create a second conda enviornment on my WSL machine to debug some bioinformatics software. I initially attempted to create a second conda enviornment outside WSL (the base enviornment works fine on the Windows file structure)  and then ran into the same issue as above (ncurses creating too many soft links).

I then, however, tried to create a new conda enviornment under the home directory and seemingly still ran into the soft links issue. Let me know if I did anything wrong.

```
(base) rednewt@Enceladus:~$ conda create --prefix ./TEST_ENV_LOC
WARNING: A directory already exists at the target location '/home/rednewt/TEST_ENV_LOC'
but it is not a conda environment.
Continue creating environment (y/[n])? y

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/rednewt/TEST_ENV_LOC



Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate /home/rednewt/TEST_ENV_LOC
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) rednewt@Enceladus:~$ conda activate /home/rednewt/TEST_ENV_LOC
(/home/rednewt/TEST_ENV_LOC) rednewt@Enceladus:~$ conda install longstitch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/rednewt/TEST_ENV_LOC

  added / updated specs:
    - longstitch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bedtools-2.30.0            |       h468198e_3        15.5 MB  bioconda
    htslib-1.15                |       h9753748_0         2.1 MB  bioconda
    k8-0.2.5                   |       hd03093a_2         1.7 MB  bioconda
    libdeflate-1.10            |       h7f98852_0          77 KB  conda-forge
    libnghttp2-1.47.0          |       h727a467_0         808 KB  conda-forge
    minimap2-2.24              |       h7132678_1         484 KB  bioconda
    pybedtools-0.9.0           |   py39h6935b12_1        12.1 MB  bioconda
    pysam-0.18.0               |   py39h5030a8b_2         2.6 MB  bioconda
    samtools-1.15              |       h1170115_1         392 KB  bioconda
    ------------------------------------------------------------
                                           Total:        35.7 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  abyss              bioconda/linux-64::abyss-2.3.4-h41cdee2_1
  arcs               bioconda/linux-64::arcs-1.2.3-h7ff8a90_1
  arpack             conda-forge/linux-64::arpack-3.7.0-hdefa2d7_2
  bedtools           bioconda/linux-64::bedtools-2.30.0-h468198e_3
  bwa                bioconda/linux-64::bwa-0.7.17-h7132678_9
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h7f98852_4
  c-ares             conda-forge/linux-64::c-ares-1.18.1-h7f98852_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2021.10.8-ha878542_0
  glpk               conda-forge/linux-64::glpk-4.65-h9202a9a_1004
  gmp                conda-forge/linux-64::gmp-6.2.1-h58526e2_0
  htslib             bioconda/linux-64::htslib-1.15-h9753748_0
  icu                conda-forge/linux-64::icu-69.1-h9c3ff4c_0
  intervaltree       conda-forge/noarch::intervaltree-3.0.2-py_0
  k8                 bioconda/linux-64::k8-0.2.5-hd03093a_2
  krb5               conda-forge/linux-64::krb5-1.19.2-hcc1bbae_3
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.36.1-hea4e1c9_2
  libblas            conda-forge/linux-64::libblas-3.9.0-13_linux64_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-13_linux64_openblas
  libcurl            conda-forge/linux-64::libcurl-7.81.0-h2574ce0_0
  libdeflate         conda-forge/linux-64::libdeflate-1.10-h7f98852_0
  libedit            conda-forge/linux-64::libedit-3.1.20191231-he28a2e2_2
  libev              conda-forge/linux-64::libev-4.33-h516909a_1
  libffi             conda-forge/linux-64::libffi-3.4.2-h7f98852_5
  libgcc-ng          conda-forge/linux-64::libgcc-ng-11.2.0-h1d223b6_12
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-11.2.0-h69a702a_12
  libgfortran5       conda-forge/linux-64::libgfortran5-11.2.0-h5c6108e_12
  libgomp            conda-forge/linux-64::libgomp-11.2.0-h1d223b6_12
  libiconv           conda-forge/linux-64::libiconv-1.16-h516909a_0
  liblapack          conda-forge/linux-64::liblapack-3.9.0-13_linux64_openblas
  libnghttp2         conda-forge/linux-64::libnghttp2-1.47.0-h727a467_0
  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.18-pthreads_h8fe5266_0
  libssh2            conda-forge/linux-64::libssh2-1.10.0-ha56f1ee_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-11.2.0-he4da1e4_12
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h7f98852_1000
  libxml2            conda-forge/linux-64::libxml2-2.9.12-h885dcf4_1
  libzlib            conda-forge/linux-64::libzlib-1.2.11-h36c2ea0_1013
  links              bioconda/linux-64::links-2.0.1-h9f5acd7_2
  longstitch         bioconda/noarch::longstitch-1.0.1-hdfd78af_1
  make               conda-forge/linux-64::make-4.3-hd18ef5c_1
  metis              conda-forge/linux-64::metis-5.1.0-h58526e2_1006
  minimap2           bioconda/linux-64::minimap2-2.24-h7132678_1
  mpfr               conda-forge/linux-64::mpfr-4.1.0-h9202a9a_1
  mpi                conda-forge/linux-64::mpi-1.0-openmpi
  ncurses            conda-forge/linux-64::ncurses-6.3-h9c3ff4c_0
  ntlink             bioconda/linux-64::ntlink-1.1.2-py39h6935b12_1
  numpy              conda-forge/linux-64::numpy-1.22.2-py39h91f2184_0
  openmpi            conda-forge/linux-64::openmpi-4.1.2-hbfc84c5_0
  openssl            conda-forge/linux-64::openssl-1.1.1l-h7f98852_0
  pandas             conda-forge/linux-64::pandas-1.4.1-py39hde0f152_0
  pcre               conda-forge/linux-64::pcre-8.45-h9c3ff4c_0
  perl               conda-forge/linux-64::perl-5.32.1-2_h7f98852_perl5
  pip                conda-forge/noarch::pip-22.0.3-pyhd8ed1ab_0
  pybedtools         bioconda/linux-64::pybedtools-0.9.0-py39h6935b12_1
  pysam              bioconda/linux-64::pysam-0.18.0-py39h5030a8b_2
  python             conda-forge/linux-64::python-3.9.10-h85951f9_2_cpython
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0
  python-igraph      conda-forge/linux-64::python-igraph-0.9.9-py39hfef886c_0
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39
  pytz               conda-forge/noarch::pytz-2021.3-pyhd8ed1ab_0
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  samtools           bioconda/linux-64::samtools-1.15-h1170115_1
  setuptools         conda-forge/linux-64::setuptools-60.9.3-py39hf3d152e_0
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0
  sortedcontainers   conda-forge/noarch::sortedcontainers-2.4.0-pyhd8ed1ab_0
  sqlite             conda-forge/linux-64::sqlite-3.37.0-h9cd32fc_0
  suitesparse        conda-forge/linux-64::suitesparse-5.10.1-h9e50725_1
  tbb                conda-forge/linux-64::tbb-2021.5.0-h4bd325d_0
  texttable          conda-forge/noarch::texttable-1.6.4-pyhd8ed1ab_0
  tigmint            bioconda/linux-64::tigmint-1.2.5-py39h6935b12_1
  tk                 conda-forge/linux-64::tk-8.6.12-h27826a3_0
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  util-linux         conda-forge/linux-64::util-linux-2.36-py39h28948ff_1
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h36c2ea0_1013
  zsh                conda-forge/linux-64::zsh-5.8-h8f967e6_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
bedtools-2.30.0      | 15.5 MB   | ############################################################################# | 100%
pybedtools-0.9.0     | 12.1 MB   | ############################################################################# | 100%
minimap2-2.24        | 484 KB    | ############################################################################# | 100%
libdeflate-1.10      | 77 KB     | ############################################################################# | 100%
htslib-1.15          | 2.1 MB    | ############################################################################# | 100%
libnghttp2-1.47.0    | 808 KB    | ############################################################################# | 100%
k8-0.2.5             | 1.7 MB    | ############################################################################# | 100%
pysam-0.18.0         | 2.6 MB    | ############################################################################# | 100%
samtools-1.15        | 392 KB    | ############################################################################# | 100%
Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 315, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 344, in handle_txn
        unlink_link_transaction.execute()
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 245, in execute
        self.verify()
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 232, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 591, in _verify
        for exc in self.verify_executor.map(UnlinkLinkTransaction._verify_individual_level,
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 525, in map
        yield func(thing)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/core/link.py", line 412, in _verify_individual_level
        error_result = axn.verify()
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 323, in verify
        source_size_in_bytes = getsize(self.source_full_path)
      File "/mnt/c/ultimate/other_software/miniconda3/lib/python3.9/genericpath.py", line 50, in getsize
        return os.stat(filename).st_size
    OSError: [Errno 40] Too many levels of symbolic links: '/mnt/c/ultimate/other_software/miniconda3/pkgs/ncurses-6.3-h9c3ff4c_0/share/terminfo/N/NCR260VT300WPP'

`$ /mnt/c/ultimate/other_software/miniconda3/bin/conda install longstitch`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=/home/rednewt/TEST_ENV_LOC
                CONDA_EXE=/mnt/c/ultimate/other_software/miniconda3/bin/conda
             CONDA_PREFIX=/home/rednewt/TEST_ENV_LOC
           CONDA_PREFIX_1=/mnt/c/ultimate/other_software/miniconda3
    CONDA_PROMPT_MODIFIER=(/home/rednewt/TEST_ENV_LOC)
         CONDA_PYTHON_EXE=/mnt/c/ultimate/other_software/miniconda3/bin/python
               CONDA_ROOT=/mnt/c/ultimate/other_software/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/mnt/c/ultimate/other_software/miniconda3/bin:/home/rednewt/.cargo/bin
                          :/home/rednewt/TEST_ENV_LOC/bin:/mnt/c/ultimate/other_software/minicon
                          da3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/
                          bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/Canon
                          icalGroupLimited.UbuntuonWindows_2004.2021.825.0_x64__79rhkp1fndgsc:/m
                          nt/c/Program Files/PerkinElmerInformatics/ChemOffice2020/ChemScript/Li
                          b:/mnt/c/Program Files (x86)/Common Files/Oracle/Java/javapath:/mnt/c/
                          Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Wi
                          ndows/System32/WindowsPowerShell/v1.0:/mnt/c/Windows/System32/OpenSSH:
                          /mnt/c/Program Files/WorldPainter:/mnt/c/Program
                          Files/Git/cmd:/mnt/c/Ultimate/Other Software/7-preview/preview:/mnt/c/
                          ProgramData/chocolatey/bin:/mnt/c/Users/Joseph/AppData/Local/Microsoft
                          /WindowsApps:/mnt/c/Users/Joseph/AppData/Local/Programs/Microsoft VS
                          Code/bin:/mnt/c/Program Files/mingw-w64/x86_64-8.1.0-posix-seh-rt_v6-r
                          ev0/mingw64/bin:/mnt/c/Users/Joseph/AppData/Local/GitHubDesktop/bin:/s
                          nap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : /home/rednewt/TEST_ENV_LOC
    active env location : /home/rednewt/TEST_ENV_LOC
            shell level : 2
       user config file : /home/rednewt/.condarc
 populated config files : /home/rednewt/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=4.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/c/ultimate/other_software/miniconda3  (writable)
      conda av data dir : /mnt/c/ultimate/other_software/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/c/ultimate/other_software/miniconda3/pkgs
                          /home/rednewt/.conda/pkgs
       envs directories : /mnt/c/ultimate/other_software/miniconda3/envs
                          /home/rednewt/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.25.1 CPython/3.9.5 Linux/4.4.0-19041-Microsoft ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by runette** [comment]
Just for information - I hit this problem while trying to use the subdir `linux-64` on macos (I am trying to create an environment for cross compiling) and realized that the problem is caused by loading a package that is designed for a file system that is case sensitive (i.e. linux) onto a filesystem that is not case sensitive (i.e. mac or windows).

So - whilst on Linux a symbolic link from `THIS_FILE` to `this_file` is valid, the same link on a non-case-sensitive files system is circular.

**Comment by Sankar57** [comment]
I tried everyday still I'm facing the same issue, help me !!!

**Comment by Sankar57** [comment]
I tried every way still facing the same issue, help me

**Comment by drZhan** [comment]
> I am also affected by this problem and reinstalling conda and deleting .cache does not solve it for me.
> 
> For me the steps to reproduce are:
> 
> * install a fresh version of miniforge in the standard path (under ubuntu running on WLS2)
> * execute `conda create --name foo python=3.8`
> 
> During installation ncurses actually does create a self referencing symbolic link under `pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/ncr260vt300wpp -> ../N/NCR260VT300WPP` linking to itself in upper case. I am not sure whether this is caused by conda or a problem with ncurses.
> 
> If I replace this self-referencing symbolic link manually with an empty file before trying to create the first environment, a subsequent `conda create --name bar python=3.8` "works" and only produces the following warning:
> 
> ```
> SafetyError: The package for ncurses located at /home/cvjjm/miniforge3/pkgs/ncurses-6.2-h58526e2_4
> appears to be corrupted. The path 'share/terminfo/E/Eterm'
> has an incorrect size.
>   reported size: 2224 bytes
>   actual size: 842 bytes
> 
> SafetyError: The package for ncurses located at /home/cvjjm/miniforge3/pkgs/ncurses-6.2-h58526e2_4
> appears to be corrupted. The path 'share/terminfo/N/NCR260VT300WPP'
> has an incorrect size.
>   reported size: 1754 bytes
>   actual size: 0 bytes
> ```
> 
> Replacing those two files with the files that are actually in the ncurses tar.bz2 from [here](https://anaconda.org/conda-forge/ncurses/files) makes these errors go away.

@Sankar57 recently I tried this way and errors went away

**Comment by DeepSmeag** [comment]
> I am also affected by this problem and reinstalling conda and deleting .cache does not solve it for me.
> 
> For me the steps to reproduce are:
> 
> * install a fresh version of miniforge in the standard path (under ubuntu running on WLS2)
> * execute `conda create --name foo python=3.8`
> 
> During installation ncurses actually does create a self referencing symbolic link under `pkgs/ncurses-6.2-h58526e2_4/share/terminfo/N/ncr260vt300wpp -> ../N/NCR260VT300WPP` linking to itself in upper case. I am not sure whether this is caused by conda or a problem with ncurses.
> 
> If I replace this self-referencing symbolic link manually with an empty file before trying to create the first environment, a subsequent `conda create --name bar python=3.8` "works" and only produces the following warning:
> 
> ```
> SafetyError: The package for ncurses located at /home/cvjjm/miniforge3/pkgs/ncurses-6.2-h58526e2_4
> appears to be corrupted. The path 'share/terminfo/E/Eterm'
> has an incorrect size.
>   reported size: 2224 bytes
>   actual size: 842 bytes
> 
> SafetyError: The package for ncurses located at /home/cvjjm/miniforge3/pkgs/ncurses-6.2-h58526e2_4
> appears to be corrupted. The path 'share/terminfo/N/NCR260VT300WPP'
> has an incorrect size.
>   reported size: 1754 bytes
>   actual size: 0 bytes
> ```
> 
> Replacing those two files with the files that are actually in the ncurses tar.bz2 from [here](https://anaconda.org/conda-forge/ncurses/files) makes these errors go away.

I have MiniConda + python envs in the Windows file system (so /mnt/...). I've been having it this way for at least 1 year. No problems until today. (Today) I tried making a new environment via the same commands I did before, in the same folder that holds the envs (Window file system) and the errors from above appeared. I had a problem with ncurses-6.4 (I did not find files for this one online). 

One mention: Last time I created an environment via conda was last fall (2022). I didn't do any kind of update or modification in the WSL system.

The empty-file-replacement trick worked for me. I had some warnings, but the environment was created correctly.  As I'm typing this, I'm loading the environment with libraries.

For reference, I wanted to install Python 3.10.9 this time; my other envs had 3.9.something or lower versions

Hope this helps someone; if you have enough space in your C (Windows) partition for the envs, I would recommend not dealing with the windows file system and just keeping it all there.
