### ISSUE TITLE
An unexpected error has occurred when installing outside package

### ISSUE THREAD

**Issue by boki-p** [conda/conda#1034]
I was installing MNE package downloaded from https://pypi.python.org/pypi/mne/0.8.1 , but error occured. 

Appreciate your help! 
-----
Details:
E:\Programming Program Files\Anaconda>conda install E:\mne-0.8.1.tar
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "E:\Programming Program Files\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "E:\Programming Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "E:\Programming Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "E:\Programming Program Files\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "E:\Programming Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 221, in install
    depends = install_tar(prefix, tar_path, verbose=not args.quiet)
  File "E:\Programming Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 32, in install_tar
    t = tarfile.open(tar_path, 'r')
  File "E:\Programming Program Files\Anaconda\lib\tarfile.py", line 1660, in open
    return func(name, "r", fileobj, **kwargs)
  File "E:\Programming Program Files\Anaconda\lib\tarfile.py", line 1722, in gzopen
    fileobj = bltn_open(name, mode + "b")
IOError: [Errno 2] No such file or directory: 'E:\\mne-0.8.1.tar'
Current conda install:

             platform : win-64
        conda version : 3.7.3
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.5.0
     root environment : E:\Programming Program Files\Anaconda  (writable)
  default environment : E:\Programming Program Files\Anaconda
     envs directories : E:\Programming Program Files\Anaconda\envs
        package cache : E:\Programming Program Files\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
Conda can't install packages straight from pypi, they need to be conda packages. Instead, you should use `conda install -c asmeurer mne=0.7.1` which will install the mne conda package from https://anaconda.org/asmeurer/mne
