### ISSUE TITLE
Cannot change the version of python 

### ISSUE THREAD

**Issue by NataCalc** [conda/conda#10353]
Hello,

I installed anaconda with python 3.8.3 with an idea to install mayavi. Prior last command I have to install vtk:
**conda install -c anaconda vtk** which is not compatible with python 3.8.3. I tried to change the version of python from 3.8.3 to 3.5.5, results dozens of conflicts. What should I do about it?

Regards,
Nataliya

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-274)

**Comment by chenghlee** [comment]
Create and use a new environment for vtk, rather than installing it in the base environment; conda has not supported Python 3.5 since conda 4.5.11, and downgrading your base environment would likely break many things.
```
conda create -n vtk-env -c anaconda vtk
conda activate vtk-env
```

**Comment by NataCalc** [comment]
I did what you suggested followed by installation of mayavi and faced vtk problem. 


```
  509  conda create -n vtk-env -c anaconda vtk
  510  conda activate vtk-env
  511  conda install -c anaconda mayavi

(vtk-env) s2986149@pc063723:~$ mayavi2
Traceback (most recent call last):
  File "/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/vtkmodules/vtkIOExodus.py", line 5, in <module>
    from .vtkIOExodusPython import *
ImportError: dlopen(/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/vtkmodules/vtkIOExodusPython.so, 2): Library not loaded: @rpath/libnetcdf.13.dylib
  Referenced from: /opt/anaconda3/envs/vtk-env/lib/libvtkexodusII-8.2.1.dylib
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/mayavi/scripts/mayavi2.py", line 453, in <module>
    import vtk
  File "/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/vtkmodules/all.py", line 70, in <module>
    from .vtkIOExodus import *
  File "/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/vtkmodules/vtkIOExodus.py", line 9, in <module>
    from vtkIOExodusPython import *
ModuleNotFoundError: No module named 'vtkIOExodusPython'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/envs/vtk-env/bin/mayavi2", line 7, in <module>
    from mayavi.scripts.mayavi2 import main
  File "/opt/anaconda3/envs/vtk-env/lib/python3.7/site-packages/mayavi/scripts/mayavi2.py", line 459, in <module>
    raise ImportError(msg)
ImportError: No module named 'vtkIOExodusPython'
________________________________________________________________________________
Do you have vtk installed properly?
VTK (and build instructions) can be obtained from http://www.vtk.org

(vtk-env) s2986149@pc063723:~$ import vtk
Version: ImageMagick 7.0.10-37 Q16 x86_64 2020-11-09 https://imagemagick.org
Copyright: © 1999-2020 ImageMagick Studio LLC
License: https://imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules OpenMP(4.5) 
Delegates (built-in): bzlib freetype gslib heic jng jp2 jpeg lcms lqr ltdl lzma openexr png ps tiff webp xml zlib
Usage: import [options ...] [ file ]

```
