### ISSUE TITLE
Error: 'bytes' object has no attribute 'get', Anaconda - Python

### ISSUE THREAD

**Issue by Jairo-cm** [conda/conda#10359]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'bytes' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(_args, *_kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 170, in **init**
    self.api = AnacondaAPI()
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 77, in **init**
    self._conda_api = CondaAPI()
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1804, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 371, in **init**
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\HP\anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 533, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'bytes' object has no attribute 'get'

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-278)

**Comment by chenghlee** [comment]
Can you please provide the information requested in the issue template (outputs of `conda info`, `conda conda --show-sources`, `conda list --show-channel-urls`)?
