### ISSUE TITLE
Current conda install:

### ISSUE THREAD

**Issue by fenglei1999** [conda/conda#10363]
platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\Carlos Fung\Anaconda3  (writable)
    default environment : C:\Users\Carlos Fung\Anaconda3
       envs directories : C:\Users\Carlos Fung\Anaconda3\envs
                          C:\Users\Carlos Fung\AppData\Local\conda\conda\envs
                          C:\Users\Carlos Fung\.conda\envs
          package cache : C:\Users\Carlos Fung\Anaconda3\pkgs
                          C:\Users\Carlos Fung\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Carlos Fung\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.19041
          administrator : False

`$ C:\Users\Carlos Fung\Anaconda3\Scripts\conda install -c conda-forge scrapy`

```
Traceback (most recent call last):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 280, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1625, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1431, in _raise_ssl_error
    raise WantReadError()
OpenSSL.SSL.WantReadError
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 280, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1625, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1448, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\response.py", line 302, in _error_catcher
    yield
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\response.py", line 601, in read_chunked
    chunk = self._handle_chunk(amt)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\response.py", line 557, in _handle_chunk
    value = self._fp._safe_read(amt)
  File "C:\Users\Carlos Fung\Anaconda3\lib\http\client.py", line 612, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "C:\Users\Carlos Fung\Anaconda3\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 296, in recv_into
    return self.recv_into(*args, **kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\contrib\pyopenssl.py", line 285, in recv_into
    raise SocketError(str(e))
OSError: (10054, 'WSAECONNRESET')
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\requests\models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\response.py", line 432, in stream
    for line in self.read_chunked(amt, decode_content=decode_content):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\response.py", line 626, in read_chunked
    self._original_response.close()
  File "C:\Users\Carlos Fung\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\urllib3\response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
    unknown=index_args['unknown'], prefix=prefix)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
    index = fetch_index(channel_priority_map, use_cache=use_cache)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
    repodatas = collect_all_repodata(use_cache, tasks)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
    repodatas = _collect_repodatas_serial(use_cache, tasks)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
    for url, schan, pri in tasks]
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
    for url, schan, pri in tasks]
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
    res = f(*args, **kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\repodata.py", line 464, in fetch_repodata
    mod_etag_headers.get('_mod'))
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\conda\core\repodata.py", line 144, in fetch_repodata_remote_request
    timeout=timeout)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\requests\sessions.py", line 521, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\requests\sessions.py", line 658, in send
    r.content
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\requests\models.py", line 823, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\Users\Carlos Fung\Anaconda3\lib\site-packages\requests\models.py", line 748, in generate
    raise ChunkedEncodingError(e)
requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))
```

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-281)

**Comment by chenghlee** [comment]
Can you please provide the output of `conda info`, `conda list --show-channel-urls`, and `conda config --show-sources`?

**Comment by jerrymatjila** [comment]
Try to create a new environment
```shell
conda create -n scarpy-env -c conda-forge scrapy
```
My guess is that your command `conda install -c conda-forge scrapy` attempts to install `scrapy` in the base environment.
