### ISSUE TITLE
Geopandas install issues with arcgispro-py3 cloned environment for ArcGIS Pro v2.6

### ISSUE THREAD

**Issue by pcbmitchell** [conda/conda#10369]
Hello,

I am attempting to install Geopandas to a cloned arcgis pro python environment.  I used the advice in this [Esri technical article](https://support.esri.com/en/technical-article/000024177) to install geopandas successfully in a ArcGIS Pro Python environment for ArcGIS Pro version 2.5 (used "conda install geopandas libtiff=4.0.10").  I just had to upgrade to ArcGIS Pro v 2.6 and am now trying to remake the cloned environment customizations, but received the following error (see below) when attempting to use the same geopandas install code provided above.  I thought perhaps Esri fixed the issue w/ Pro version 2.6, so attempted just a normal "conda install geopandas", which installed geopandas, but still brings the .dll errors (esri issue) when attempting to import. That said, can anyone help me translate and troubleshoot the error message below to enable successful installation of Geopandas on a cloned arcgispro-py3 environment for ArcGIS Pro v2.6? Thank you in advance and please let me know if you need any other info.
---
(arcgispro-py3-clone2) C:\Users\bisho\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone2>conda install geopandas libtiff=4.0.10
Fetching package metadata .........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.18.9
         python version : 3.6.8.final.0
       requests version : 2.22.0
       root environment : C:\Program Files\ArcGIS\Pro\bin\Python  (read only)
    default environment : C:\Users\bisho\AppData\Local\ESRI\conda\envs\arcgispro-py3-clone2
       envs directories : C:\Users\bisho\AppData\Local\ESRI\conda\envs
                          C:\Program Files\ArcGIS\Pro\bin\Python\envs
                          C:\Users\bisho\.conda\envs
          package cache : C:\Users\bisho\AppData\Local\ESRI\conda\pkgs
                          C:\Program Files\ArcGIS\Pro\bin\Python\pkgs
           channel URLs : http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/esri/win-64
                          https://conda.anaconda.org/esri/noarch
            config file : C:\Program Files\ArcGIS\Pro\bin\Python\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.22.0 CPython/3.6.8 Windows/10 Windows/10.0.18362
          administrator : False

`$ conda install geopandas libtiff=4.0.10`

    Traceback (most recent call last):
      File "site-packages\urllib3\contrib\pyopenssl.py", line 297, in recv_into
      File "site-packages\OpenSSL\SSL.py", line 1822, in recv_into
      File "site-packages\OpenSSL\SSL.py", line 1622, in _raise_ssl_error
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "site-packages\urllib3\contrib\pyopenssl.py", line 297, in recv_into
      File "site-packages\OpenSSL\SSL.py", line 1822, in recv_into
      File "site-packages\OpenSSL\SSL.py", line 1639, in _raise_ssl_error
    OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "site-packages\urllib3\response.py", line 360, in _error_catcher
      File "site-packages\urllib3\response.py", line 442, in read
      File "http\client.py", line 449, in read
      File "http\client.py", line 493, in readinto
      File "socket.py", line 586, in readinto
      File "site-packages\urllib3\contrib\pyopenssl.py", line 312, in recv_into
      File "site-packages\urllib3\contrib\pyopenssl.py", line 302, in recv_into
    OSError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "site-packages\requests\models.py", line 750, in generate
      File "site-packages\urllib3\response.py", line 494, in stream
      File "site-packages\urllib3\response.py", line 459, in read
      File "contextlib.py", line 99, in __exit__
      File "site-packages\urllib3\response.py", line 378, in _error_catcher
    urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "conda\exceptions.py", line 641, in conda_exception_handler
      File "conda\cli\main.py", line 144, in _main
      File "conda\cli\main_install.py", line 80, in execute
      File "conda\cli\install.py", line 234, in install
      File "conda\core\index.py", line 101, in get_index
      File "conda\core\index.py", line 120, in fetch_index
      File "conda\core\repodata.py", line 75, in collect_all_repodata
      File "conda\core\repodata.py", line 485, in _collect_repodatas_serial
      File "conda\core\repodata.py", line 485, in <listcomp>
      File "conda\core\repodata.py", line 115, in func
      File "conda\core\repodata.py", line 464, in fetch_repodata
      File "conda\core\repodata.py", line 144, in fetch_repodata_remote_request
      File "site-packages\requests\sessions.py", line 546, in get
      File "site-packages\requests\sessions.py", line 533, in request
      File "site-packages\requests\sessions.py", line 686, in send
      File "site-packages\requests\models.py", line 828, in content
      File "site-packages\requests\models.py", line 753, in generate
    requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))

**Comment by pcbmitchell** [comment]
Nevermind! I just needed to re-login to my Esri organization and the geopandas install as suggested by Esri worked successfully.
