### ISSUE TITLE
304 question is happened,it worked before noon,but it does not work now.how can i solve it?

### ISSUE THREAD

**Issue by BinchaoPeng** [conda/conda#10364]
i have reset my channels many times.....i cannot install anything.....

(base) pbc@pbc-ubuntu:~$ conda update conda
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 259, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 613, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1020, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/index.py", line 276, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 120, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/pbc/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
        yield fs.pop().result()
      File "/home/pbc/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 432, in result
        return self.__get_result()
      File "/home/pbc/anaconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
        raise self._exception
      File "/home/pbc/anaconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 112, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 125, in query
        self.load()
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 189, in load
        _internal_state = self._load()
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 277, in _load
        _internal_state = self._read_local_repdata(mod_etag_headers.get('_etag'),
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 326, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/pbc/anaconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 364, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/pbc/anaconda3/lib/python3.8/json/__init__.py", line 357, in loads
        return _default_decoder.decode(s)
      File "/home/pbc/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/pbc/anaconda3/lib/python3.8/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 172352 column 17 (char 5226287)

`$ /home/pbc/anaconda3/bin/conda update conda`

  environment variables:
                ALL_PROXY=<set>
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/pbc/anaconda3/bin/conda
             CONDA_PREFIX=/home/pbc/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/pbc/anaconda3/bin/python
               CONDA_ROOT=/home/pbc/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                 NO_PROXY=<set>
                     PATH=/home/pbc/anaconda3/bin:/home/pbc/anaconda3/bin:/home/pbc/anaconda3/co
                          ndabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/u
                          sr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2
                all_proxy=<set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /home/pbc/anaconda3
            shell level : 1
       user config file : /home/pbc/.condarc
 populated config files : /home/pbc/.condarc
          conda version : 4.9.2
    conda-build version : 3.18.11
         python version : 3.8.3.final.0
       virtual packages : __cuda=11.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/pbc/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/pbc/anaconda3/pkgs
                          /home/pbc/.conda/pkgs
       envs directories : /home/pbc/anaconda3/envs
                          /home/pbc/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.3 Linux/5.4.0-54-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

**Comment by chenghlee** [comment]
@BinchaoPeng: are you still running into this issue?

**Comment by BinchaoPeng** [comment]
no,it works autoly in second day,thanks
