### ISSUE TITLE
Startup error with Anaconda Prompt

### ISSUE THREAD

**Issue by Bruxelles-li** [conda/conda#10373]
Traceback (most recent call last):
  File "E:\Software\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "E:\Software\Anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "E:\Software\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "E:\Software\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "E:\Software\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "E:\Software\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "E:\Software\Anaconda3\lib\site-packages\requests\__init__.py", line 44, in <module>
    import chardet
  File "E:\Software\Anaconda3\lib\site-packages\chardet\__init__.py", line 20, in <module>
    from .universaldetector import UniversalDetector
  File "E:\Software\Anaconda3\lib\site-packages\chardet\universaldetector.py", line 43, in <module>
    from .charsetgroupprober import CharSetGroupProber
  File "E:\Software\Anaconda3\lib\site-packages\chardet\charsetgroupprober.py", line 28, in <module>
    from .enums import ProbingState
ModuleNotFoundError: No module named 'chardet.enums'

**Comment by Bruxelles-li** [comment]
The error occurred after executing a operation with pip install numpy==1.17.0.

**Comment by Bruxelles-li** [comment]
Having reinstalled the chardet packages on the corresponding path，but it didn't work  with this problem.

**Comment by chenghlee** [comment]
Can you please provide the output of `conda info`, `conda list --show-channel-urls`, and `conda config --show`?

**Comment by Bruxelles-li** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Bruxelles-li** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
