### ISSUE TITLE
AssertionError when running `conda list` 

### ISSUE THREAD

**Issue by st-pasha** [conda/conda#10371]
## Current Behavior
<details open><summary> <code>$ conda list</code> </summary>

    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/root/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
            return getattr(module, func_name)(args, parser)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/main_list.py", line 140, in execute
            exitcode = print_packages(prefix, regex, format, piplist=args.pip,
          File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/main_list.py", line 79, in print_packages
            exitcode, output = list_packages(prefix, regex, format=format,
          File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/main_list.py", line 45, in list_packages
            installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
          File "/root/miniconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 136, in iter_records
            return itervalues(self._prefix_records)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 165, in _prefix_records
            return self.__prefix_records or self.load() or self.__prefix_records
          File "/root/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
            return f(*args, **kwds)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 75, in load
            self._load_site_packages()
          File "/root/miniconda3/lib/python3.8/site-packages/conda/core/prefix_data.py", line 280, in _load_site_packages
            python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/gateways/disk/read.py", line 257, in read_python_record
            paths_tups = pydist.get_paths()
          File "/root/miniconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 273, in get_paths
            records = process_csv_row(record_reader)
          File "/root/miniconda3/lib/python3.8/site-packages/conda/common/pkg_formats/python.py", line 252, in process_csv_row
            assert checksum.startswith('sha256='), (self._metadata_dir_full_path,
        AssertionError: ('/root/miniconda3/lib/python3.8/site-packages/datatable-0.11.0.dist-info', 'lib/python3.8/site-packages/datatable-0.11.0.dist-info/LICENSE', 'HyVuytGSiAUQ6ErWBHTqt1iSGHhLmlC8fO7jTCuR8dU')
    
    `$ /root/miniconda3/bin/conda list`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=base
                    CONDA_EXE=/root/miniconda3/bin/conda
                 CONDA_PREFIX=/root/miniconda3
        CONDA_PROMPT_MODIFIER=(base)
             CONDA_PYTHON_EXE=/root/miniconda3/bin/python
                   CONDA_ROOT=/root/miniconda3
                  CONDA_SHLVL=1
          DEVTOOLSET_ROOTPATH=/opt/rh/devtoolset-8/root
              LD_LIBRARY_PATH=/opt/rh/devtoolset-8/root/usr/lib64:/opt/rh/devtoolset-8/root/usr/lib:
                              /opt/rh/devtoolset-8/root/usr/lib64/dyninst:/opt/rh/devtoolset-8/root/
                              usr/lib/dyninst:/usr/local/lib64:/usr/local/lib
                         PATH=/root/miniconda3/bin:/root/miniconda3/bin:/root/miniconda3/condabin:/o
                              pt/rh/devtoolset-8/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sb
                              in:/usr/bin:/sbin:/bin
              PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=/opt/_internal/certs.pem
    
         active environment : base
        active env location : /root/miniconda3
                shell level : 1
           user config file : /root/.condarc
     populated config files : 
              conda version : 4.8.3
        conda-build version : not installed
             python version : 3.8.3.final.0
           virtual packages : __glibc=2.12
           base environment : /root/miniconda3  (writable)
               channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /root/miniconda3/pkgs
                              /root/.conda/pkgs
           envs directories : /root/miniconda3/envs
                              /root/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/4.15.0-122-generic centos/6.10 glibc/2.12
                    UID:GID : 0:0
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.</details>

### Steps to Reproduce
For maximum reproducibility, I'll start from a completely clean slate: a fresh docker environment.

```
$ docker run -it quay.io/pypa/manylinux2010_x86_64
# yum install wget -y
# wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# bash Miniconda3-latest-Linux-x86_64.sh
[ ... accept license agreement and use the default settings ... ]
# bash
```

At this moment we have a fresh conda environment, do the following to trigger the error:

```
# pip install datatable
# conda list
```

## Environment Information
<details><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /root/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.12
       base environment : /root/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/4.15.0-122-generic centos/6.10 glibc/2.12
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

</p></details>

<details><summary><code>`conda config --show-sources`</code></summary><p>

(empty)
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

(same error as reported at the start of the report)
</p></details>

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-285)

**Comment by st-pasha** [comment]
I've tried to debug this issue further,  and here are my findings:

The error occurs at [python.py:251](https://github.com/conda/conda/blob/master/conda/common/pkg_formats/python.py#L251-L252) when reading `RECORD` file with the following content:
```
datatable/__init__.py,OLGK_6OnaaTmliNph9LtHnWBdm9erFmgl9Z4MGCT41I,3728
datatable/_build_info.py,qFuzOpgOZJcqua0r5g_6WVEtUPD-vfXbvchvfLw4ORs,1684
datatable/exceptions.py,gjfLY1wQMTo-QR9_3YUyTriPy7FVItN-lv6kt9ogq8Y,6642
...
```
According to [PEP-376](https://www.python.org/dev/peps/pep-0376/#record), this record file is ill-formed: hash entries must be prefixed with the name of the hash algorithm (`sha256=`). At the same time, according to the same PEP, this algorithm may be any out of the set `hashlib.algorithms_guaranteed =  {'sha3_512', 'blake2b', 'sha512', 'sha256', 'md5', 'sha3_384', 'blake2s', 'shake_128', 'sha1', 'sha3_256', 'sha3_224', 'sha224', 'shake_256', 'sha384'}`, which means the assertion in line 251 is also incorrect.
