### ISSUE TITLE
Conda list throwing TypeError

### ISSUE THREAD

**Issue by iam432** [conda/conda#10380]
Hi All,

when executing conda list, getting below error.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 130, in iter_records
        return itervalues(self._prefix_records)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 159, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 72, in load
        self._load_site_packages()
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 274, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 257, in read_python_record
        paths_tups = pydist.get_paths()
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/common/pkg_formats/python.py", line 268, in get_paths
        records = sorted(concatv(records, ((pf, None, None) for pf in missing_pyc_files)))
    TypeError: '<' not supported between instances of 'str' and 'NoneType'

`$ /data1/anaconda/anaconda3/bin/conda list`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/data1/anaconda/anaconda3/bin/conda
             CONDA_PREFIX=/data1/anaconda/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/data1/anaconda/anaconda3/bin/python
               CONDA_ROOT=/data1/anaconda/anaconda3
              CONDA_SHLVL=1
                     PATH=/data1/anaconda/anaconda3/bin:/data1/anaconda/anaconda3/bin:/data1/ana
                          conda/anaconda3/condabin:/usr/lib/jvm/java-1.8.0-openjdk/bin:/opt/loca
                          l/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/s
                          bin:/usr/bin:/opt/OV/bin:/root/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               http_proxy=<set>
              https_proxy=<set>

     active environment : base
    active env location : /data1/anaconda/anaconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.7.8
    conda-build version : 3.0.23
         python version : 3.6.7.final.0
       virtual packages :
       base environment : /data1/anaconda/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data1/anaconda/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /data1/anaconda/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.8 requests/2.24.0 CPython/3.6.7 Linux/4.1.12-61.1.18.el7uek.x86_64 ol/7.3 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

when installing a package getting KeyError: 'pytest-astropy' error, below is complete error 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 256, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 150, in solve_for_diff
        force_remove)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 780, in _run_sat
        repodata_fn=self._repodata_fn)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 1219, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 336, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 417, in build_conflict_map
        bad_deps.extend(g.depth_first_search_by_name(spec, dep, sdeps[spec]))
      File "/data1/anaconda/anaconda3/lib/python3.6/site-packages/conda/models/prefix_graph.py", line 448, in depth_first_search_by_name
        if any(ms.match(rec) for rec in allowed_specs[ms.name]):
    KeyError: 'pytest-astropy'

`$ /data1/anaconda/anaconda3/bin/conda install pyOpenSSL==17.2.0`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/data1/anaconda/anaconda3/bin/conda
             CONDA_PREFIX=/data1/anaconda/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/data1/anaconda/anaconda3/bin/python
               CONDA_ROOT=/data1/anaconda/anaconda3
              CONDA_SHLVL=1
                     PATH=/data1/anaconda/anaconda3/bin:/data1/anaconda/anaconda3/bin:/data1/ana
                          conda/anaconda3/condabin:/usr/lib/jvm/java-1.8.0-openjdk/bin:/opt/loca
                          l/bin:/opt/local/sbin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/s
                          bin:/usr/bin:/opt/OV/bin:/root/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               http_proxy=<set>
              https_proxy=<set>

     active environment : base
    active env location : /data1/anaconda/anaconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.7.8
    conda-build version : 3.0.23
         python version : 3.6.7.final.0
       virtual packages :
       base environment : /data1/anaconda/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data1/anaconda/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /data1/anaconda/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.8 requests/2.24.0 CPython/3.6.7 Linux/4.1.12-61.1.18.el7uek.x86_64 ol/7.3 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Thanks
Krishna

**Comment by iam432** [comment]
Fixed by #9132.
