### ISSUE TITLE
conda env create -f envrionment.yaml throws AttributeError: 'str' object has no attribute 'copy'

### ISSUE THREAD

**Issue by yuhuishi-convect** [conda/conda#10381]
## Current Behavior

`conda env create -f` throws an error
```
(dask-dev) vagrant@ubuntu-focal:~/projects/dask-sql$ conda env create -f conda.yaml

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 87, in execute
        spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
      File "/opt/conda/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/opt/conda/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 160, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 142, in from_yaml
        data = validate_keys(data, kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 37, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'
```

### Steps to Reproduce

sample envrionment.yaml 
```
(dask-dev) vagrant@ubuntu-focal:~/projects/dask-sql$ cat conda.yaml
python>=3.8.5
dask>=2.19.0
jpype1>=1.0.2
openjdk>=11
maven>=3.6.0
pytest>=6.0.1
pytest-cov>=2.10.1
sphinx>=3.2.1
tzlocal>=2.1
fastapi>=0.61.1
uvicorn>=0.11.3
pyarrow>=0.15.1
```

Create an environment from the yaml
```
(dask-dev) vagrant@ubuntu-focal:~/projects/dask-sql$ conda env create -f conda.yaml
```
throws
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main_create.py", line 87, in execute
        spec = specs.detect(name=name, filename=filename, directory=os.getcwd())
      File "/opt/conda/lib/python3.8/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/opt/conda/lib/python3.8/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 160, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 142, in from_yaml
        data = validate_keys(data, kwargs)
      File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 37, in validate_keys
        new_data = data.copy() if data else {}
    AttributeError: 'str' object has no attribute 'copy'
```

## Expected Behavior

An environment would have been created

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(dask-dev) vagrant@ubuntu-focal:~/projects/dask-sql$ conda info

     active environment : dask-dev
    active env location : /opt/conda/envs/dask-dev
            shell level : 2
       user config file : /home/vagrant/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/vagrant/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/vagrant/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Linux/5.4.0-54-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
<EMPTY>
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(dask-dev) vagrant@ubuntu-focal:~/projects/dask-sql$ conda list --show-channel-urls
# packages in environment at /opt/conda/envs/dask-dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2020.10.14                    0    defaults
certifi                   2020.11.8        py37h06a4308_0    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.2.1             hf484d3e_1007    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.0.2u               h7b6447c_0    defaults
pip                       20.2.4           py37h06a4308_0    defaults
python                    3.7.0                h6e4f718_3    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                50.3.1           py37h06a4308_1    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
wheel                     0.35.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by saucoide** [comment]
that conda.yaml file looks like it is formatted like a requirement.txt and not like a yaml file, here is an example environment.yml from the documentation 
https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-file-manually

**Comment by Yuhuishishishi** [comment]
@saucoide I found that running
```
conda create -n sample-env --file conda.yaml
```

instead of 
```
conda env create -n sample-env --file conda.yaml
           ^^^^
```

will do the trick

**Comment by saucoide** [comment]
yes that's because they are doing different things, the way i understand it is like this:

for `conda create` the `--file` argument takes a file with a list of packages/versions to install ([docs](https://docs.conda.io/projects/conda/en/latest/commands/create.html#conda-create)) like a `requirements.txt`

for `conda env create` the `--file` refers to a yaml file that specifies the details of the environment, channel, name, etc 
https://github.com/conda/conda/tree/master/conda_env

it is a bit confusing, and the documentation is split https://github.com/conda/conda/issues/5253
