### ISSUE TITLE
 conda install anaconda-client error

### ISSUE THREAD

**Issue by jays7mb** [conda/conda#10397]
Current conda install:

```
           platform : win-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : not installed
     python version : 3.9.0.final.0
   requests version : 2.25.0
   root environment : c:\users\user\appdata\local\programs\python\python39  (writable)
default environment : c:\users\user\appdata\local\programs\python\python39
   envs directories : c:\users\user\appdata\local\programs\python\python39\envs
      package cache : c:\users\user\appdata\local\programs\python\python39\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-64/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : None
       offline mode : False
```

`$ C:\Users\User\AppData\Local\Programs\Python\Python39\Scripts\conda install anaconda-client`

```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\install.py", line 201, in yield_lines
    with open(path) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\user\\appdata\\local\\programs\\python\\python39\\pkgs\\menuinst-1.4.7-py36_0\\info\\has_prefix'
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\install.py", line 209, in yield_lines
    raise StopIteration
StopIteration
```

```
The above exception was the direct cause of the following exception:
```

```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\cli\install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\install.py", line 943, in link
    has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\install.py", line 248, in read_has_prefix
    return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\install.py", line 248, in <dictcomp>
    return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\install.py", line 247, in <genexpr>
    parsed_lines = (parse_line(line) for line in yield_lines(path))
RuntimeError: generator raised StopIteration
```

```
During handling of the above exception, another exception occurred:
```

```
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\cli\main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "c:\users\user\appdata\local\programs\python\python39\lib\site-packages\conda\cli\install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration
```

┆Issue is synchronized with this [Jira Task](https://anaconda.atlassian.net/browse/CONDAORG-304)

**Comment by cjmartian** [comment]
Hey @jays7mb 

I noticed you're on conda `4.2.7` which was released Sep 16, 2016. The most recent version is `4.9.2`
My guess is that you might have installed via pip, which isn't recommended. 
I think the first step here is to update your conda install.
