### ISSUE TITLE
Error in conda: AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'

### ISSUE THREAD

**Issue by MrX-NGS** [conda/conda#10405]
Hi,

I found the below error in conda and any help is appreciated to fix this:

```
bash-3.2$ conda create --name myenv
Traceback (most recent call last):
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in **call**
    return func(_args, *_kwargs)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
    module = import_module(relative_mod, **name**.rsplit('.', 1)[0])
  File "/Users/balathl/miniconda3/lib/python3.7/importlib/**init**.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 10, in <module>
    from .install import install
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/**init**.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/requests/**init**.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/OpenSSL/**init**.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 669, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/balathl/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, _args, *_kwargs)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, _args, *_kwargs)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in **call**
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 12, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/**init**.py", line 21, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/requests/**init**.py", line 95, in <module>
    from urllib3.contrib import pyopenssl
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/OpenSSL/**init**.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/Users/balathl/miniconda3/lib/python3.7/site-packages/OpenSSL/SSL.py", line 669, in <module>
    _lib.Cryptography_HAS_TLSEXT_HOSTNAME, "SNI not available"
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
```

Best Regards,
Bala

**Comment by cjmartian** [comment]
Please fill out the entire template. We need more information in order to help.

**Comment by kr04** [comment]
I was facing the same issue on 9.12.2020, and it was was resolved by using pyopenssl==20.0.0 from pyopenssl==18.0.0.
But today, it seems to not be a problem for pyopenssl==18.0.0 as well.

**Comment by geerlingguy** [comment]
I seem to have also gotten this problem in recent CI builds as well over the past week:

```
SNI not available
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_TLSEXT_HOSTNAME'
```

From: https://github.com/geerlingguy/ansible-role-certbot/runs/1613121274?check_suite_focus=true#step:5:156

**Comment by simonello** [comment]
I deleted the **OpenSSL** directory from **site-packages** and it now works.   (If you are going to try this, make a copy, just in case!)

**Comment by hepcat72** [comment]
I was trying to do a `conda update -n base conda` and was getting this error. @simonello's [suggestion](https://github.com/conda/conda/issues/10405#issuecomment-786503274) seems to have worked for me.
