### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Brand4** [conda/conda#10411]
### Error Report

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 123, in solve_for_transaction
        self._notify_conda_outdated(link_precs)
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 961, in _notify_conda_outdated
        repodata_fn=self._repodata_fn),
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/public/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/home/public/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
        return self.__get_result()
      File "/home/public/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/home/public/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
        self.load()
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 276, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/public/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 349, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/public/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/home/public/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/public/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 108 (char 107)

`$ /home/public/anaconda3/bin/conda create --name dxz`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/public/anaconda3/bin/conda
             CONDA_PREFIX=/home/public/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/public/anaconda3/bin/python
               CONDA_ROOT=/home/public/anaconda3
              CONDA_SHLVL=1
                     PATH=/home/public/anaconda3/bin:/home/public/bin:/home/public/.local/bin:/h
                          ome/public/anaconda3/bin:/home/public/anaconda3/condabin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/
                          games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/public/anaconda3
            shell level : 1
       user config file : /home/public/.condarc
 populated config files : /home/public/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=10.1
                          __glibc=2.23
       base environment : /home/public/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : /home/public/anaconda3/pkgs
                          /home/public/.conda/pkgs
       envs directories : /home/public/anaconda3/envs
                          /home/public/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/4.15.0-122-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1008:1008
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: ^C
Timeout reached. No report sent.

(base) public@zrway-ZRPGS:~$ 
```

**Comment by cjmartian** [comment]
Can you try commenting out your channels in your `.condarc` file and rerunning your create/install commands?
I'd like to rule out that the `repodata.json` that you're getting from the custom channels may not be valid json.

**Comment by GeoffNN** [comment]
I have the same issue, after removing the `.condarc` file:

```~ conda update conda
Collecting package metadata (repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 263, in _load
        repodata_fn=self.repodata_fn)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 613, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 425, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1021, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 277, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 120, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/negroni/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/home/negroni/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 428, in result
        return self.__get_result()
      File "/home/negroni/anaconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/home/negroni/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 113, in <lambda>
        package_ref_or_match_spec))
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 125, in query
        self.load()
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 189, in load
        _internal_state = self._load()
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 278, in _load
        mod_etag_headers.get('_mod'))
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 326, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/negroni/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 364, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/negroni/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/home/negroni/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/negroni/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 25492 column 5 (char 774144)

`$ /home/negroni/anaconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/home/negroni/anaconda3/bin/conda
         CONDA_PYTHON_EXE=/home/negroni/anaconda3/bin/python
               CONDA_ROOT=/home/negroni/anaconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/home/negroni/anaconda3/bin:/home/negroni/.vscode-server/bin/e5a624b78
                          8d92b8d34d1392e4c4d9789406efe8f/bin:/home/negroni/anaconda3/condabin:/
                          home/negroni/.vscode-server/bin/e5a624b788d92b8d34d1392e4c4d9789406efe
                          8f/bin:/usr/local/bin:/usr/bin:/bin:/usr/games
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /home/negroni/.condarc
 populated config files : 
          conda version : 4.9.2
    conda-build version : 3.17.6
         python version : 3.7.4.final.0
       virtual packages : __cuda=11.0=0
                          __glibc=2.24=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/negroni/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/negroni/anaconda3/pkgs
                          /home/negroni/.conda/pkgs
       envs directories : /home/negroni/anaconda3/envs
                          /home/negroni/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.7.4 Linux/4.9.0-13-amd64 debian/9.13 glibc/2.24
                UID:GID : 1004:1004
             netrc file : None
           offline mode : False```

**Comment by GeoffNN** [comment]
`conda clean -i` seems to have solved the problem for me.
