### ISSUE TITLE
Unexpected errors in `conda info` and other commands

### ISSUE THREAD

**Issue by tomchor** [conda/conda#10433]
## Current Behavior

Some conda commands fail with unexpected errors. I can still use `conda activate`, but if I want to install packages to existing envs or create new envs I get an error. Also `conda info` fails.

### Steps to Reproduce

One way to get an error is using `conda info`:

```
$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 316, in execute
        info_dict = get_info_dict(args.system)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 135, in get_info_dict
        _supplement_index_with_system(virtual_pkg_index)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
        return cuda_detect()
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/home/tomas/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory

`$ /home/tomas/miniconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 

```

Another error that's a bit more verbose is trying to create a new env:

```
$ conda create --name gan
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
    return cuda_detect()
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/home/tomas/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1211, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 238, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 158, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 818, in cuda_version
        return cuda_detect()
      File "/home/tomas/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/home/tomas/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory

`$ /home/tomas/miniconda3/bin/conda create --name gan`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 
```

## Expected Behavior

I expected, respectively, to see info about conda and to create a new env.

## Environment Information

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /home/tomas/.condarc <==
channels:
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /home/tomas/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
argon2-cffi               20.1.0           py37h4abf009_2    conda-forge
arrow                     0.15.5                   py37_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
ca-certificates           2020.11.8            ha878542_0    conda-forge
certifi                   2020.11.8        py37h89c1867_0    conda-forge
cffi                      1.14.4           py37hc58025e_1    conda-forge
chardet                   3.0.4           py37he5f6b98_1008    conda-forge
conda                     4.9.2            py37h89c1867_0    conda-forge
conda-package-handling    1.7.2            py37hb5d75c8_0    conda-forge
cryptography              3.2.1            py37hc72a4ac_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
icu                       67.1                 he1b5a44_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
iexfinance                0.4.3                    pypi_0    pypi
importlib-metadata        3.1.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        3.1.1                hd8ed1ab_0    conda-forge
ipykernel                 5.3.4            py37h888b3d9_1    conda-forge
ipython                   7.11.1           py37h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.2           py37h89c1867_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_core              4.7.0            py37h89c1867_0    conda-forge
jupyterlab                2.2.8                      py_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         1.2.0                      py_0    conda-forge
keras                     2.4.3                    pypi_0    pypi
kiwisolver                1.3.1            py37hc928c03_0    conda-forge
lcms2                     2.11                 hcbb858e_1    conda-forge
libblas                   3.9.0                3_openblas    conda-forge
libcblas                  3.9.0                3_openblas    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.3                  h58526e2_1    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            7.5.0               hae1eefd_17    conda-forge
libgfortran4              7.5.0               hae1eefd_17    conda-forge
libgomp                   9.3.0               h5dbcf3e_17    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                3_openblas    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h4f3a223_6    conda-forge
libwebp-base              1.1.0                h36c2ea0_3    conda-forge
libxml2                   2.9.10               h68273f3_2    conda-forge
libxslt                   1.1.33               h572872d_1    conda-forge
lxml                      4.6.2            py37h77fd288_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
matplotlib                3.3.2                         0    conda-forge
matplotlib-base           3.3.2            py37hd478181_0    conda-forge
mistune                   0.8.4           py37h4abf009_1002    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py37h89c1867_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
neural-image-analogies    0.1.2                    pypi_0    pypi
notebook                  6.1.5            py37h89c1867_0    conda-forge
numpy                     1.19.4           py37h7e9df27_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openssl                   1.1.1h               h516909a_0    conda-forge
packaging                 20.7               pyhd3deb0d_0    conda-forge
pandas                    1.1.4            py37h10a2094_0    conda-forge
pandas-datareader         0.8.1                      py_0    anaconda
pandoc                    2.11.2               h36c2ea0_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py37h63a5d19_0    conda-forge
pint                      0.11                     pypi_0    pypi
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
prompt_toolkit            3.0.8                hd8ed1ab_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pycosat                   0.6.3           py37hb5d75c8_1005    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.2                      py_0    conda-forge
pymicra                   0.4.1                    pypi_0    pypi
pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py37h4abf009_1    conda-forge
pysocks                   1.7.1            py37he5f6b98_2    conda-forge
python                    3.7.4                h265db76_1    defaults
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0           py37h5a562af_1    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.25.0             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py37hb5d75c8_1003    conda-forge
scikit-learn              0.22.1           py37hcdab131_1    conda-forge
scipy                     1.4.1            py37h921218d_0    conda-forge
selenium                  3.141.0         py37h516909a_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py37he5f6b98_2    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.33.0               h62c20be_0    defaults
terminado                 0.9.1            py37h89c1867_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
theano                    1.0.4                    pypi_0    pypi
tk                        8.6.10               hed695b0_1    conda-forge
tornado                   6.1              py37h4abf009_0    conda-forge
tqdm                      4.54.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzupdate                  2.0.0                    pypi_0    pypi
urllib3                   1.25.11                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
xarray                    0.14.1                     py_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```
</p></details>

**Comment by tomchor** [comment]
Apparently python got updated from 3.8 to 3.9 and this broke conda. I had to reinstall it.
