### ISSUE TITLE
Unsatisfiable dependencies for platform linux-64

### ISSUE THREAD

**Issue by noeliaferruz** [conda/conda#10495]
## Current Behavior

New to this. Trying to build a conda package. This is surely not a bug but I don't know how to fix this. I've tried several conda versions, they give me different errors but I always get this glibc error below. Below is the whole output: 
Thanks for your time.
```
  - feature:/linux-64::__glibc==2.23=0
  - feature:|@/linux-64::__glibc==2.23=0
  - openmm -> __glibc[version='>=2.17']
  - openmm -> cudatoolkit[version='11.0|11.0.*'] -> __glibc[version='>=2.17,<3.0.a0']
  - parmed -> openmm -> __glibc[version='>=2.17']

Your installed version is: 2.23


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 481, in main
    execute(sys.argv[1:])
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 470, in execute
    outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/build.py", line 3068, in build_tree
    packages_from_this = build(metadata, stats,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/build.py", line 2031, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/render.py", line 789, in expand_outputs
    for (output_dict, m) in deepcopy(_m).get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/metadata.py", line 2115, in get_output_metadata_set
    conda_packages = finalize_outputs_pass(ref_metadata, conda_packages, pass_no=0,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/metadata.py", line 776, in finalize_outputs_pass
    fm = finalize_metadata(om, parent_metadata=parent_metadata,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/render.py", line 547, in finalize_metadata
    build_unsat, host_unsat = add_upstream_pins(m,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/render.py", line 409, in add_upstream_pins
    host_deps, host_unsat, extra_run_specs_from_host = _read_upstream_pin_files(m, 'host',
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/render.py", line 374, in _read_upstream_pin_files
    deps, actions, unsat = get_env_dependencies(m, env, m.config.variant,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/render.py", line 139, in get_env_dependencies
    actions = environ.get_install_actions(tmpdir, tuple(dependencies), env,
  File "/agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego/lib/python3.9/site-packages/conda_build/environ.py", line 804, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {"zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0']", "pypy3.7[version='7.3.*|7.3.3.*']", "zlib[version='1.2.11|>=1.2.11,<1.3.0a0']", "numpy[version='>=1.11.3,<2.0a0|>=1.15.4,<2.0a0|>=1.16.6,<2.0a0|>=1.18.5,<2.0a0|>=1.16.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.19.5,<2.0a0|>=1.9.3,<2.0a0']", "zlib[version='1.2.*|>=1.2.11,<1.3.0a0']", "bzip2[version='>=1.0.8,<2.0a0']", "__glibc[version='>=2.17']", "bzip2[version='1.0.*|>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']", "icu[version='>=58.2,<59.0a0']", "libgfortran4[version='>=7.5.0']", "bzip2[version='1.0.*|>=1.0.6,<2.0a0']", 'openmm', "zlib[version='1.2.11.*|1.2.11|1.2.8']", "python_abi[version='3.6|3.9.*|3.7',build='*_pypy37_pp73|*_pypy36_pp73|*_cp39']", "zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']", "boost-cpp[version='1.63.0|1.64.0|1.65.0|1.65.1|1.66.0|1.67.0|1.67.0.*|1.68.0.*|1.69.0.*|1.70.0.*|1.71.0.*|1.72.0.*|1.73.0.*|1.74.0.*']", 'numpy', "numpy[version='>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.17']", "certifi[version='>=2016.09|>=2016.9.26']", "libgfortran5[version='8.4.0.*|9.3.0.*']", "zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8']", "expat[version='>=2.2.9,<2.3.0a0']", "numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.*|>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.13.3,<2.0a0|>=1.14.6,<2.0a0|>=1.15.4,<2.0a0|>=1.16.6,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.16.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.4,<2.0a0|>=1.18.1,<2.0a0|>=1.9.*|>=1.8|>=1.7']", 'wheel', "expat[version='>=2.2.5,<2.3.0a0|>=2.2.9,<2.3.0a0']", "six[version='>=1.5']", 'scipy', 'networkx', 'tzdata', 'feature:/linux-64::__glibc==2.23=0', 'ca-certificates', 'matplotlib', "libgfortran5[version='>=9.3.0']", "libboost[version='1.65.1|1.65.1|1.67.0|1.71.0|1.73.0',build='h3ff78a5_11|h37e3b65_11|h37e3b65_10|h97c9712_0|h46d08c1_4|habcd387_4|h4055789_3']", "libboost[version='1.65.1|1.65.1|1.67.0|1.71.0|1.73.0',build='habcd387_4|hf484d3e_10|h3ff78a5_11|hf484d3e_11|h37e3b65_11|h37e3b65_10|h97c9712_0|h46d08c1_4|h4055789_3']", "icu[version='58.*|>=58.2,<59.0a0|>=68.1,<69.0a0|>=67.1,<68.0a0|>=64.2,<65.0a0']", "icu[version='>=58.2,<59.0a0|>=67.1,<68.0a0|>=68.1,<69.0a0|>=64.2,<65.0a0']", "pandas[version='0.24.2|<=0.25.3|>=1.1.2']", "pypy3.7[version='>=7.3.3']", "numpy[version='1.10.*|1.11.*|>=1.14.6,<2.0a0|>=1.16.6,<2.0a0|>=1.11.3,<2.0a0|>=1.15.1,<2.0a0|>=1.9.3,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.16.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9|>=1.11|1.13.*|1.12.*']", "scipy[version='>=1.0']", "gdbm[version='>=1.18,<1.19.0a0']", 'pip', "icu[version='56.*|58.*|>=58.2,<59.0a0|>=64.2,<65.0a0|>=67.1,<68.0a0|>=68.1,<69.0a0']", "libgcc-ng[version='>=7.3.0|>=9.3.0']", 'six', "icu[version='>=64.2,<65.0a0|>=67.1,<68.0a0']", "six[version='>=1.6.1,<2.0']", 'isl', "numpy[version='1.11.*|1.12.*|1.13.*|>=1.11|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.19.5,<2.0a0|>=1.18.5,<2.0a0|>=1.19.4,<2.0a0|>=1.19.2,<2.0a0|>=1.9.3,<2.0a0|>=1.8|>=1.9|>=1.7|>=1.12']", 'libgcc', "_libgcc_mutex[version='*|0.1',build='conda_forge|main']", "boost[version='>=1.70.0,<1.70.1.0a0|>=1.72.0,<1.72.1.0a0|>=1.74.0,<1.74.1.0a0']", "libboost[version='1.73.0|1.73.0|>=1.67.0,<1.67.1.0a0|>=1.71.0,<1.71.1.0a0|>=1.73.0,<1.73.1.0a0|>=1.65.1,<1.66.0a0',build='h3ff78a5_11|h37e3b65_11|h37e3b65_10|h97c9712_0|hf484d3e_11|hf484d3e_10']", "bzip2[version='>=1.0.6,<2.0a0|>=1.0.8,<2.0a0']", "zlib[version='>=1.2.11,<1.3.0a0']", 'feature:|@/linux-64::__glibc==2.23=0', 'python-dateutil', 'libgfortran4=7.5.0', "python-dateutil[version='>=2.5.*|>=2.6.1|>=2.7.3']", "boost-cpp[version='>=1.70.0,<1.70.1.0a0|>=1.72.0,<1.72.1.0a0|>=1.74.0,<1.74.1.0a0']", "gmp[version='>=6.1.2,<7.0a0|>=6.2.0,<7.0a0|>=6.2.1,<7.0a0']", 'pypy3.7=7.3.3', "pyqt[version='4.11.*|5.6.*|>=5.6.0,<5.7.0a0|>=5.9.2,<5.10.0a0']", 'icu=56', 'setuptools', "zlib[version='1.2.*|1.2.11|1.2.8|1.2.11.*']", "numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.6,<2.0a0|>=1.15.1,<2.0a0|>=1.9.3,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.16.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9']", 'pyparsing', "pillow[version='>=6.2.0']", "certifi[version='>=2020.06.20']", "numpy[version='>=1.11.3,<2.0a0']", "libstdcxx-ng[version='>=7.3.0']", "zlib[version='1.2.*|1.2.11|1.2.11.*|>=1.2.11,<1.3.0a0|1.2.8']", "gmp[version='>=4.2']", "numpy[version='>=1.11|>=1.11.*|>=1.11.3,<2.0a0|>=1.12.1,<2.0a0|>=1.13.3,<2.0a0|>=1.15.4,<2.0a0|>=1.9|>=1.18.4,<2.0a0|>=1.18.1,<2.0a0|>=1.9.*|>=1.7|>=1.15.1,<2.0a0']", "libgcc-ng[version='>=4.9|>=7.5.0|>=7.2.0']", 'enum34', "certifi[version='>=2016.09|>=2016.9.26|>=2020.06.20']", "python_abi[version='3.6.*|3.7.*|3.8.*',build='*_cp36m|*_cp37m|*_cp38']", "numpy[version='1.10.*|1.11.*|>=1.11.3,<2.0a0|>=1.15.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.4,<2.0a0|>=1.9.3,<2.0a0|>=1.15.1,<2.0a0|>=1.18.1,<2.0a0|>=1.9']", "numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.9.3,<2.0a0|>=1.8']", "pyqt[version='4.11.*|5.*|5.9.*|>=5.6,<6.0a0|>=5.9.2,<5.10.0a0|5.6.*|>=5.6.0,<5.7.0a0|>=5.12.3,<5.13.0a0']", "libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.5.0|>=9.3.0']", "pypy3.7[version='7.3.3.*|>=7.3.3']", "python-dateutil[version='>=2.1']", "zlib[version='1.2.*|1.2.11.*|1.2.8']", 'pandas', "pyparsing[version='>=2.0.3,!=2.0.4,!=2.1.2,!=2.1.6']", 'blas-devel==3.9.0=7_openblas', "numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.10,<1.11.0a0|>=1.12,<1.13.0a0|>=1.14.6,<2.0a0|>=1.9.3,<2.0a0|>=1.14,<1.15.0a0|>=1.13,<1.14.0a0|>=1.11,<1.12.0a0|>=1.16.5,<2.0a0|>=1.14.6,<1.18.0|1.15.*|>=1.15.4,<2.0a0|>=1.11|>=1.16.6,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.15.1,<2.0a0|>=1.18.1,<2.0a0|>=1.9|>=1.13.3,<2.0a0|>=1.11.*|>=1.9.*|>=1.8|>=1.7|>=1.18.4,<2.0a0']", "boost-cpp[version='1.70.0.*|1.72.0.*|1.74.0.*']", "numpy[version='1.10.*|1.11.*|>=1.14.6,<2.0a0']", "libgfortran4[version='7.5.0.*|>=7.5.0']", "numpy[version='>=1.14']", "numpy[version='>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.19.5,<2.0a0|>=1.19.2,<2.0a0']", "__glibc[version='>=2.17,<3.0.a0']"}

```

### Steps to Reproduce

`conda build .`

my meta.yaml
```
{% set name = "protlego" %}
{% set version = "1.0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: .

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - boost
    - boost-cpp
    - csb
    - matplotlib
    - mdtraj
    - moleculekit
    - numpy 
    - openmm
    - pandas
    - pip
    - python 
    - scipy
    - graph-tool
    - jupyter
    - htmd-pdb2pqr
    - parmed
  run:
    - boost
    - boost-cpp
    - csb
    - matplotlib
    - mdtraj
    - moleculekit
    - numpy 
    - openmm
    - pandas
    - python
    - scipy
    - graph-tool
    - jupyter 
    - htmd-pdb2pqr
    - parmed
test:
  imports:
    - protlego

about:
  home: https://github.com/Hoecker-Lab/protlego
  license: UNKNOWN
  license_family: OTHER
  license_file: 
  summary: A python package for the automated construction of chimeras and analysis
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - noeliaferruz

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : 3.2.2021.protlego
    active env location : /agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs/3.2.2021.protlego
            shell level : 2
       user config file : /agh/home/nferruz/.condarc
 populated config files : /agh/home/nferruz/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /agh/projects/noelia/miniconda3_4.6.14_3.2.2021  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/acellera/linux-64
                          https://conda.anaconda.org/acellera/noarch
          package cache : /agh/projects/noelia/miniconda3_4.6.14_3.2.2021/pkgs
                          /agh/home/nferruz/.conda/pkgs
       envs directories : /agh/projects/noelia/miniconda3_4.6.14_3.2.2021/envs
                          /agh/home/nferruz/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-197-generic ubuntu/16.04.7 glibc/2.23
                UID:GID : 1304465:100022512
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /agh/home/nferruz/.condarc <==
channels:
  - defaults
  - bioconda
  - conda-forge
  - acellera

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
beautifulsoup4            4.9.3              pyha847dfd_0    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2021.1.19            h06a4308_0    defaults
certifi                   2020.12.5        py39h06a4308_0    defaults
cffi                      1.14.4           py39h261ae71_0    defaults
chardet                   4.0.0           py39h06a4308_1003    defaults
conda                     4.9.2            py39h06a4308_0    defaults
conda-build               3.21.4           py39h06a4308_0    defaults
conda-package-handling    1.7.2            py39h27cfd23_1    defaults
cryptography              3.3.1            py39h3c74f83_0    defaults
filelock                  3.0.12             pyhd3eb1b0_1    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libarchive                3.4.2                h62408e4_0    defaults
libedit                   3.1.20191231         h14c3975_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
liblief                   0.10.1               h2531618_1    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libxml2                   2.9.9                hea5a465_1    defaults
lz4-c                     1.9.3                h2531618_0    defaults
markupsafe                1.1.1            py39h27cfd23_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1i               h27cfd23_0    defaults
patchelf                  0.12                 h2531618_1    defaults
pip                       20.3.3           py39h06a4308_0    defaults
pkginfo                   1.7.0            py39h06a4308_0    defaults
psutil                    5.8.0            py39h27cfd23_1    defaults
py-lief                   0.10.1           py39h2531618_1    defaults
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.1                hdb3f193_2    defaults
python-libarchive-c       2.9                pyhd3eb1b0_0    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pyyaml                    5.4.1            py39h27cfd23_1    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ripgrep                   12.1.1                        0    defaults
ruamel_yaml               0.15.80          py39h27cfd23_0    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
six                       1.15.0             pyhd3eb1b0_0    defaults
soupsieve                 2.1                pyhd3eb1b0_0    defaults
sqlite                    3.33.0               h62c20be_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tqdm                      4.56.0             pyhd3eb1b0_0    defaults
tzdata                    2020f                h52ac0ba_0    defaults
urllib3                   1.26.3             pyhd3eb1b0_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.5                h9ceee32_0    defaults
```
</p></details>

**Comment by noeliaferruz** [comment]
will post on the conda-build repository.
