### ISSUE TITLE
Updating conda fails

### ISSUE THREAD

**Issue by ElDeveloper** [conda/conda#1049]
We use this strategy to setup our test environments in Travis and Jenkins, and we are seeing the following problem:

```bash
+ conda update --quiet --yes conda
Updating conda environment at /mnt/workspace/qiime-github-pr/anaconda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-3.7.3                |           py27_0         157 KB
    openssl-1.0.1j             |                3         2.6 MB
    pycosat-0.6.1              |           py27_0         152 KB
    python-2.7.9               |                1        13.4 MB
    pyyaml-3.11                |           py27_0         332 KB
    readline-6.2               |                2         606 KB
    requests-2.5.0             |           py27_0         587 KB
    sqlite-3.8.4.1             |                0         2.0 MB
    tk-8.5.15                  |                0         1.8 MB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    conda-2.2.2                |           py27_0
    openssl-1.0.1c             |                0
    pycosat-0.6.0              |           py27_0
    python-2.7.6               |                0
    pyyaml-3.10                |           py27_0
    readline-6.2               |                0
    sqlite-3.7.13              |                0
    tk-8.5.13                  |                0

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    conda-3.7.3                |           py27_0   hard-link
    openssl-1.0.1j             |                3   hard-link
    pycosat-0.6.1              |           py27_0   hard-link
    python-2.7.9               |                1   hard-link
    pyyaml-3.11                |           py27_0   hard-link
    readline-6.2               |                2   hard-link
    requests-2.5.0             |           py27_0   hard-link
    sqlite-3.8.4.1             |                0   hard-link
    tk-8.5.15                  |                0   hard-link

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/mnt/workspace/qiime-github-pr/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 183, in main
    if args.debug:
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 93, in execute
    
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/plan.py", line 374, in execute_actions
    continue
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/plan.py", line 359, in execute_plan
    # if something depends on Python/Numpy, but the spec is very
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/plan.py", line 314, in link
    actions[UNLINK].append(dist)
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/install.py", line 390, in link
    _link(src, dst, LINK_HARD)
  File "/mnt/workspace/qiime-github-pr/anaconda/lib/python2.7/site-packages/conda/install.py", line 167, in update_prefix
    msg += "Retry with onerror failed (%s)\n" % e1
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8ana binary lib/libcrypto.so.1.0.0'
Build step 'Virtualenv Builder' marked build as failure
No emails were triggered.
Finished: FAILURE
```

------

A few links to our failed builds:

- [Failure in Jenkins](http://ci.qiime.org/job/qiime-github-pr/1392/console).
- [Failure in Travis](https://travis-ci.org/biocore/qiita/builds/44149948).

This is how we install conda:

```bash
wget -q http://repo.continuum.io/miniconda/Miniconda-2.2.2-Linux-x86_64.sh -O miniconda.sh
chmod +x miniconda.sh
./miniconda.sh -b -p /mnt/workspace/qiime-github-pr/anaconda
conda update --quiet --yes conda
```

**Comment by nehalecky** [comment]
I also hit the same error while following this guide at: http://conda.pydata.org/docs/travis.html.

It's likely *very* helpful to emphasize in the documentation that one should always point to most recent miniconda version, which I understand is available here: http://conda.pydata.org/miniconda.html.

Other than this, great work and thank you. :)

**Comment by asmeurer** [comment]
This should be fixed.
