### ISSUE TITLE
conda (miniconda2) keeps failing on win10 x64

### ISSUE THREAD

**Issue by sirinath** [conda/conda#10499]
`conda` (miniconda2) keeps failing with the following error:

```cmd
(base) C:\WINDOWS\system32>conda update --all
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088

(base) C:\WINDOWS\system32>conda update conda
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088

(base) C:\WINDOWS\system32>conda update conda-build
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1056

(base) C:\WINDOWS\system32>conda update -c conda-forge jupyterlab
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 162, in write
    self.write_and_convert(text)
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 190, in write_and_convert
    self.write_plain_text(text, cursor, len(text))
  File "C:\ProgramData\Miniconda2\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
    self.wrapped.write(text[start:end])
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
```

**Comment by mingwandroid** [comment]
We no longer support Python 2.
