### ISSUE TITLE
error in import gdal as: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev

### ISSUE THREAD

**Issue by abhiatmos** [conda/conda#10492]
After getting install gdal package from conda using the following command: 
conda install -c conda-forge gdal
conda install -c conda-forge/label/cf202003 gdal
conda install -c conda-forge/label/gcc7 gdal
conda install -c conda-forge/label/broken gdal
conda install -c conda-forge/label/TEST gdal
conda install -c conda-forge/label/cf201901 gdal 

I am getting error in import gdal package from python as:
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhi/anaconda3/lib/python3.7/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/abhi/anaconda3/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/abhi/anaconda3/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/abhi/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/abhi/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /home/abhi/anaconda3/lib/python3.7/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev

kindly, any one can solve this issue.

Thanks in advance.....

**Comment by chenghlee** [comment]
This is a problem with the conda-forge gdal package and not with conda itself; please open an issue in the [conda-forge gdal feedstock](https://github.com/conda-forge/gdal-feedstock).
