### ISSUE TITLE
NoteBook Issue

### ISSUE THREAD

**Issue by Yash-Varshney-Creativities** [conda/conda#10514]
Hi, I am a beginner. I am facing this issue while running jupyter notebook with anaconda.

The error is :- 
`Traceback (most recent call last):`
`File "C:\Users\Lenovo\anaconda3\Scripts\jupyter-notebook-script.py", line 6, in `
`from notebook.notebookapp import main`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\notebook\notebookapp.py", line 51, in `
`from zmq.eventloop import ioloop`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\__init__.py", line 55, in `
`from zmq import backend`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\backend\__init__.py", line 40, in `
`reraise(*exc_info)`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise`
`raise value`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\backend\__init__.py", line 27, in `
`_ns = select_backend(first)`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\backend\select.py", line 28, in select_backend`
`mod = __import__(name, fromlist=public_api)`
`File "C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\backend\cython\__init__.py", line 6, in `
`from . import (constants, error, message, context,`
`ImportError: cannot import name 'constants' from partially initialized module 'zmq.backend.cython' (most likely due to a circular ``import) (C:\Users\Lenovo\AppData\Roaming\Python\Python38\site-packages\zmq\backend\cython\__init__.py)`

**Comment by Yash-Varshney-Creativities** [comment]
What can I do? Please Tell
