### ISSUE TITLE
update seaborn IOError

### ISSUE THREAD

**Issue by stijnvanhoey** [conda/conda#1052]
I updated conda and seaborn, giving following error:

Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 39, in execute
    install.install(args, parser, 'install')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 387, in execute_actions
    execute_plan(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 372, in execute_plan
    link(prefix, arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 327, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 404, in link
    update_prefix(join(prefix, f), prefix)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an binary lib/libcrypto.so.1.0.0'

Current conda install:
             platform : linux-64
        conda version : 3.0.6
       python version : 2.7.6.final.0
     root environment : /opt/anaconda  (read only)
  default environment : /home/stvhoey/envs/my_root
     envs directories : /home/stvhoey/envs
                        /opt/anaconda/envs
        package cache : /home/stvhoey/envs/.pkgs
                        /opt/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
This should be fixed.
