### ISSUE TITLE
Anaconda navigator doesn't work after updating packages

### ISSUE THREAD

**Issue by duytrung** [conda/conda#10528]
## Current Behavior

Anaconda Navigator GUI not running

### Steps to Reproduce

```
Running anaconda navigator exe from either command console or double click.
```

## Expected Behavior

Show up a GUI as usual

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
C:\MyPrograms\Anaconda\Scripts>conda install PyQt
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.


C:\MyPrograms\Anaconda\Scripts>conda info

     active environment : None
       user config file : C:\Users\dell\.condarc
 populated config files : C:\Users\dell\.condarc
          conda version : 4.9.2
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=7.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\MyPrograms\Anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\MyPrograms\Anaconda\pkgs
                          C:\Users\dell\.conda\pkgs
                          C:\Users\dell\AppData\Local\conda\conda\pkgs
       envs directories : C:\MyPrograms\Anaconda\envs
                          C:\Users\dell\.conda\envs
                          C:\Users\dell\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False


C:\MyPrograms\Anaconda\Scripts>
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

C:\MyPrograms\Anaconda\Scripts>conda config --show-sources
==> C:\Users\dell\.condarc <==
channel_priority: strict      
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
C:\MyPrograms\Anaconda\Scripts>conda list --show-channel-urls
# packages in environment at C:\MyPrograms\Anaconda:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
_r-mutex                  1.0.0               anacondar_1    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
anaconda                  custom                   py38_1    defaults
anaconda-client           1.7.2                    py38_0    defaults
anaconda-navigator        1.10.0                   py38_0    defaults
anaconda-project          0.9.1              pyhd3eb1b0_1    defaults
appdirs                   1.4.4                      py_0    defaults
argh                      0.26.2                   py38_0    defaults
argon2-cffi               20.1.0           py38h2bbff1b_1    defaults
asn1crypto                1.4.0                      py_0    defaults
astroid                   2.5              py38haa95532_1    defaults
astropy                   4.2              py38h2bbff1b_0    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     20.3.0             pyhd3eb1b0_0    defaults
autopep8                  1.5.5              pyhd3eb1b0_0    defaults
babel                     2.9.0              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.1              pyhd3eb1b0_0    defaults     
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
bcrypt                    3.2.0            py38he774522_0    defaults
beautifulsoup4            4.9.3              pyha847dfd_0    defaults
bitarray                  1.6.3            py38h2bbff1b_1    defaults
bkcharts                  0.2                      py38_0    defaults
black                     19.10b0                    py_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.3.0              pyhd3eb1b0_0    defaults
blosc                     1.21.0               h19a0ad4_0    defaults
bokeh                     2.2.3                    py38_0    defaults
boto                      2.49.0                   py38_0    defaults
bottleneck                1.3.2            py38h2a96729_1    defaults
brotli                    1.0.9                ha925a31_2    defaults
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2021.1.19            haa95532_0    defaults
certifi                   2020.12.5        py38haa95532_0    defaults
cffi                      1.14.5           py38hcd4344a_0    defaults
chardet                   4.0.0           py38haa95532_1003    defaults
charls                    2.1.0                h33f27b4_2    defaults
click                     7.1.2              pyhd3eb1b0_0    defaults
cloudpickle               1.6.0                      py_0    defaults
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
comtypes                  1.1.8           py38haa95532_1002    defaults
conda                     4.9.2            py38haa95532_0    defaults
conda-build               3.21.4           py38haa95532_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.7.2            py38h76e460a_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
contextlib2               0.6.0.post1                py_0    defaults
cryptography              3.3.1            py38hcd4344a_1    defaults
curl                      7.71.1               h2a8f88b_1    defaults
cycler                    0.10.0                   py38_0    defaults
cython                    0.29.22          py38hd77b12b_0    defaults
cytoolz                   0.11.0           py38he774522_0    defaults
dask                      2021.2.0           pyhd3eb1b0_0    defaults
dask-core                 2021.2.0           pyhd3eb1b0_0    defaults
decorator                 4.4.2              pyhd3eb1b0_0    defaults
defusedxml                0.6.0              pyhd3eb1b0_0    defaults
diff-match-patch          20200713                   py_0    defaults
distributed               2021.2.0         py38haa95532_0    defaults
docutils                  0.16                     py38_1    defaults
entrypoints               0.3                      py38_0    defaults
et_xmlfile                1.0.1                   py_1001    defaults
fastcache                 1.1.0            py38he774522_0    defaults
filelock                  3.0.12             pyhd3eb1b0_1    defaults
flake8                    3.8.4                      py_0    defaults
flask                     1.1.2              pyhd3eb1b0_0    defaults
freetype                  2.10.4               hd328e21_0    defaults
fsspec                    0.8.3                      py_0    defaults
future                    0.18.2                   py38_1    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    21.1.1           py38h2bbff1b_1    defaults
giflib                    5.2.1                h62dcd97_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
gmpy2                     2.0.8            py38h7edee0f_3    defaults
greenlet                  1.0.0            py38hd77b12b_2    defaults
h5py                      2.10.0           py38h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
heapdict                  1.0.1                      py_0    defaults
html5lib                  1.1                        py_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
imagecodecs               2021.1.11        py38h5da4933_1    defaults
imageio                   2.9.0                      py_0    defaults
imagesize                 1.2.0              pyhd3eb1b0_0    defaults
importlib-metadata        2.0.0                      py_1    defaults
importlib_metadata        2.0.0                         1    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2020.2                      254    defaults
intervaltree              3.1.0                      py_0    defaults
ipykernel                 5.3.4            py38h5ca1d4c_0    defaults
ipython                   7.20.0           py38hd4e2768_1    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.3              pyhd3eb1b0_1    defaults
isort                     5.7.0              pyhd3eb1b0_0    defaults
itsdangerous              1.1.0              pyhd3eb1b0_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.17.2           py38haa95532_1    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
joblib                    1.0.1              pyhd3eb1b0_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.9.5                      py_0    defaults
jsonschema                3.2.0                      py_2    defaults
jupyter                   1.0.0                    py38_7    defaults
jupyter_client            6.1.7                      py_0    defaults
jupyter_console           6.2.0                      py_0    defaults
jupyter_core              4.7.1            py38haa95532_0    defaults
jupyterlab                2.2.6                      py_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         1.2.0                      py_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
keyring                   22.2.0           py38haa95532_0    defaults
kiwisolver                1.3.1            py38hd77b12b_0    defaults
krb5                      1.18.2               hc04afaa_0    defaults
lazy-object-proxy         1.5.2            py38h2bbff1b_0    defaults
lcms2                     2.11                 hc51a39a_0    defaults
lerc                      2.2.1                hd77b12b_0    defaults
libaec                    1.0.4                h33f27b4_1    defaults
libarchive                3.4.2                h5e25573_0    defaults
libcurl                   7.71.1               h2a8f88b_1    defaults
libdeflate                1.7                  h2bbff1b_5    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.10.1               ha925a31_0    defaults
libllvm9                  9.0.1                h21ff451_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h33f27b4_0    defaults
libssh2                   1.9.0                h7a1dbc1_1    defaults
libtiff                   4.1.0                h56a325e_1    defaults
libxml2                   2.9.10               hb89e7f3_3    defaults
libxslt                   1.1.34               he774522_0    defaults
libzopfli                 1.0.3                ha925a31_0    defaults
llvmlite                  0.34.0           py38h1a82afc_4    defaults
locket                    0.2.1            py38haa95532_1    defaults
lxml                      4.6.2            py38h9b66d53_0    defaults
lz4-c                     1.9.3                h2bbff1b_0    defaults
lzo                       2.10                 he774522_2    defaults
m2w64-bwidget             1.9.10                        2    defaults
m2w64-bzip2               1.0.6                         6    defaults
m2w64-expat               2.1.1                         2    defaults
m2w64-fftw                3.3.4                         6    defaults
m2w64-flac                1.3.1                         3    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-gsl                 2.1                           2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libjpeg-turbo       1.4.2                         3    defaults
m2w64-libogg              1.3.2                         3    defaults
m2w64-libpng              1.6.21                        2    defaults
m2w64-libsndfile          1.0.26                        2    defaults
m2w64-libsodium           1.0.10                        2    defaults
m2w64-libtiff             4.0.6                         2    defaults
m2w64-libvorbis           1.3.5                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-libxml2             2.9.3                         4    defaults
m2w64-mpfr                3.1.4                         4    defaults
m2w64-openblas            0.2.19                        1    defaults
m2w64-pcre                8.38                          2    defaults
m2w64-speex               1.2rc2                        3    defaults
m2w64-speexdsp            1.2rc3                        3    defaults
m2w64-tcl                 8.6.5                         3    defaults
m2w64-tk                  8.6.5                         3    defaults
m2w64-tktable             2.10                          5    defaults
m2w64-wineditline         2.101                         5    defaults
m2w64-xz                  5.2.2                         2    defaults
m2w64-zeromq              4.1.4                         2    defaults
m2w64-zlib                1.2.8                        10    defaults
markupsafe                1.1.1            py38he774522_0    defaults
matplotlib                3.3.4            py38haa95532_0    defaults
matplotlib-base           3.3.4            py38h49ac443_0    defaults
mccabe                    0.6.1                    py38_1    defaults
menuinst                  1.4.16           py38he774522_1    defaults
mistune                   0.8.4           py38he774522_1000    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py38h196d8e1_0    defaults
mkl_fft                   1.3.0            py38h46781fe_0    defaults
mkl_random                1.1.1            py38h47e9c7a_0    defaults
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.7.0              pyhd3eb1b0_0    defaults
mpc                       1.1.0                h7edee0f_1    defaults
mpfr                      4.0.2                h62dcd97_1    defaults
mpir                      3.0.0                hec2e145_1    defaults
mpmath                    1.1.0                    py38_0    defaults
msgpack-python            1.0.2            py38h59b6b97_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py38_0    defaults
mypy_extensions           0.4.3                    py38_0    defaults
navigator-updater         0.2.1                    py38_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.0.7                    py38_0    defaults
nbformat                  5.1.2              pyhd3eb1b0_1    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
networkx                  2.5                        py_0    defaults
nltk                      3.5                        py_0    defaults
nose                      1.3.7           pyhd3eb1b0_1006    defaults
notebook                  6.2.0            py38haa95532_0    defaults
numba                     0.51.2           py38hf9181ef_1    defaults
numexpr                   2.7.2            py38hcbcaa1e_0    defaults
numpy                     1.19.2           py38hadc3359_0    defaults
numpy-base                1.19.2           py38ha3acd2a_0    defaults
numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
olefile                   0.46                       py_0    defaults
openjpeg                  2.3.0                h5ec785f_1    defaults
openpyxl                  3.0.6              pyhd3eb1b0_0    defaults
openssl                   1.1.1j               h2bbff1b_0    defaults
packaging                 20.9               pyhd3eb1b0_0    defaults
pandas                    1.2.2            py38hf11a4ad_0    defaults
pandoc                    2.11                 h9490d1a_0    defaults
pandocfilters             1.4.3            py38haa95532_1    defaults
paramiko                  2.7.2                      py_0    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.1.0                      py_0    defaults
path                      15.1.2           py38haa95532_0    defaults
path.py                   12.5.0                        0    defaults
pathlib2                  2.3.5            py38haa95532_2    defaults
pathspec                  0.7.0                      py_0    defaults
pathtools                 0.1.2                      py_1    defaults
patsy                     0.5.1                    py38_0    defaults
pep8                      1.7.1                    py38_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.1.0            py38h4fa10fc_0    defaults
pip                       21.0.1           py38haa95532_0    defaults
pkginfo                   1.7.0            py38haa95532_0    defaults
pluggy                    0.13.1                   py38_0    defaults
ply                       3.11                     py38_0    defaults
powershell_shortcut       0.0.1                         3    defaults
prometheus_client         0.9.0              pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.8                      py_0    defaults
prompt_toolkit            3.0.8                         0    defaults
psutil                    5.8.0            py38h2bbff1b_1    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
py-lief                   0.10.1           py38ha925a31_0    defaults
pycodestyle               2.6.0              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.20                       py_2    defaults
pycurl                    7.43.0.6         py38h7a1dbc1_0    defaults
pydocstyle                5.1.1                      py_0    defaults
pyerfa                    1.7.2            py38h2bbff1b_0    defaults
pyflakes                  2.2.0              pyhd3eb1b0_0    defaults
pygments                  2.8.0              pyhd3eb1b0_0    defaults
pylint                    2.7.1            py38haa95532_1    defaults
pyls-black                0.4.6                hd3eb1b0_0    defaults
pyls-spyder               0.3.2              pyhd3eb1b0_0    defaults
pynacl                    1.4.0            py38h62dcd97_1    defaults
pyodbc                    4.0.30           py38ha925a31_0    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py38ha925a31_4    defaults
pyreadline                2.1                      py38_1    defaults
pyrsistent                0.17.3           py38he774522_0    defaults
pysocks                   1.7.1            py38haa95532_0    defaults
pytables                  3.6.1            py38ha5be198_0    defaults
pytest                    6.2.2            py38haa95532_2    defaults
python                    3.8.8                hdbf39b2_4    defaults
python-dateutil           2.8.1              pyhd3eb1b0_0    defaults
python-jsonrpc-server     0.4.0                      py_0    defaults
python-language-server    0.36.2             pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_0    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pywavelets                1.1.1            py38he774522_2    defaults
pywin32                   227              py38he774522_1    defaults
pywin32-ctypes            0.2.0                 py38_1000    defaults
pywinpty                  0.5.7                    py38_0    defaults
pyyaml                    5.4.1            py38h2bbff1b_1    defaults
pyzmq                     20.0.0           py38hd77b12b_1    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 1.0.1                      py_0    defaults
qtconsole                 5.0.2              pyhd3eb1b0_0    defaults
qtpy                      1.9.0                      py_0    defaults
r-askpass                 1.0                       r36_0    r
r-assertthat              0.2.1             r36h6115d3f_0    r
r-backports               1.1.4             r36h6115d3f_0    r
r-base                    3.6.1                hf18239d_1    r
r-base64enc               0.1_3             r36h6115d3f_4    r
r-bh                      1.69.0_1          r36h6115d3f_0    r
r-boot                    1.3_20            r36h6115d3f_0    r
r-broom                   0.5.2             r36h6115d3f_0    r
r-callr                   3.2.0             r36h6115d3f_0    r
r-caret                   6.0_83            r36h6115d3f_0    r
r-cellranger              1.1.0             r36h6115d3f_0    r
r-class                   7.3_15            r36h6115d3f_0    r
r-cli                     1.1.0             r36h6115d3f_0    r
r-clipr                   0.6.0             r36h6115d3f_0    r
r-cluster                 2.0.8             r36h6115d3f_0    r
r-codetools               0.2_16            r36h6115d3f_0    r
r-colorspace              1.4_1             r36h6115d3f_0    r
r-crayon                  1.3.4             r36h6115d3f_0    r
r-curl                    3.3               r36h6115d3f_0    r
r-data.table              1.12.2            r36h6115d3f_0    r
r-dbi                     1.0.0             r36h6115d3f_0    r
r-dbplyr                  1.4.0             r36h6115d3f_0    r
r-dichromat               2.0_0             r36h6115d3f_4    r
r-digest                  0.6.18            r36h6115d3f_0    r
r-dplyr                   0.8.0.1           r36h6115d3f_0    r
r-ellipsis                0.1.0             r36h6115d3f_0    r
r-essentials              3.6.0                     r36_0    r
r-evaluate                0.13              r36h6115d3f_0    r
r-fansi                   0.4.0             r36h6115d3f_0    r
r-forcats                 0.4.0             r36h6115d3f_0    r
r-foreach                 1.4.4             r36h6115d3f_0    r
r-foreign                 0.8_71            r36h6115d3f_0    r
r-formatr                 1.6               r36h6115d3f_0    r
r-fs                      1.2.7             r36h6115d3f_0    r
r-generics                0.0.2             r36h6115d3f_0    r
r-ggplot2                 3.1.1             r36h6115d3f_0    r
r-glmnet                  2.0_16            r36h6115d3f_0    r
r-glue                    1.3.1             r36h6115d3f_0    r
r-gower                   0.2.0             r36h6115d3f_0    r
r-gtable                  0.3.0             r36h6115d3f_0    r
r-haven                   2.1.0             r36h6115d3f_0    r
r-hexbin                  1.27.2            r36h6115d3f_0    r
r-highr                   0.8               r36h6115d3f_0    r
r-hms                     0.4.2             r36h6115d3f_0    r
r-htmltools               0.3.6             r36h6115d3f_0    r
r-htmlwidgets             1.3               r36h6115d3f_0    r
r-httpuv                  1.5.1             r36h6115d3f_0    r
r-httr                    1.4.0             r36h6115d3f_0    r
r-ipred                   0.9_8             r36h6115d3f_0    r
r-irdisplay               0.7.0             r36h6115d3f_0    r
r-irkernel                0.8.15                    r36_0    r
r-iterators               1.0.10            r36h6115d3f_0    r
r-jsonlite                1.6               r36h6115d3f_0    r
r-kernsmooth              2.23_15           r36h6115d3f_4    r
r-knitr                   1.22              r36h6115d3f_0    r
r-labeling                0.3               r36h6115d3f_4    r
r-later                   0.8.0             r36h6115d3f_0    r
r-lattice                 0.20_38           r36h6115d3f_0    r
r-lava                    1.6.5             r36h6115d3f_0    r
r-lazyeval                0.2.2             r36h6115d3f_0    r
r-lubridate               1.7.4             r36h6115d3f_0    r
r-magrittr                1.5               r36h6115d3f_4    r
r-maps                    3.3.0             r36h6115d3f_0    r
r-markdown                0.9               r36h6115d3f_0    r
r-mass                    7.3_51.3          r36h6115d3f_0    r
r-matrix                  1.2_17            r36h6115d3f_0    r
r-mgcv                    1.8_28            r36h6115d3f_0    r
r-mime                    0.6               r36h6115d3f_0    r
r-modelmetrics            1.2.2             r36h6115d3f_0    r
r-modelr                  0.1.4             r36h6115d3f_0    r
r-munsell                 0.5.0             r36h6115d3f_0    r
r-nlme                    3.1_139           r36h6115d3f_0    r
r-nnet                    7.3_12            r36h6115d3f_0    r
r-numderiv                2016.8_1          r36h6115d3f_0    r
r-openssl                 1.3               r36h6115d3f_0    r
r-pbdzmq                  0.3_3             r36h6115d3f_0    r
r-pillar                  1.3.1             r36h6115d3f_0    r
r-pkgconfig               2.0.2             r36h6115d3f_0    r
r-plogr                   0.2.0             r36h6115d3f_0    r
r-plyr                    1.8.4             r36h6115d3f_0    r
r-prettyunits             1.0.2             r36h6115d3f_0    r
r-processx                3.3.0             r36h6115d3f_0    r
r-prodlim                 2018.04.18        r36h6115d3f_0    r
r-progress                1.2.0             r36h6115d3f_0    r
r-promises                1.0.1             r36h6115d3f_0    r
r-ps                      1.3.0             r36h6115d3f_0    r
r-purrr                   0.3.2             r36h6115d3f_0    r
r-quantmod                0.4_14            r36h6115d3f_0    r
r-r6                      2.4.0             r36h6115d3f_0    r
r-randomforest            4.6_14            r36h6115d3f_0    r
r-rbokeh                  0.6.3                     r36_0    r
r-rcolorbrewer            1.1_2             r36h6115d3f_0    r
r-rcpp                    1.0.1             r36h6115d3f_0    r
r-rcpproll                0.3.0             r36h6115d3f_0    r
r-readr                   1.3.1             r36h6115d3f_0    r
r-readxl                  1.3.1             r36h6115d3f_0    r
r-recipes                 0.1.5             r36h6115d3f_0    r
r-recommended             3.6.0                     r36_0    r
r-rematch                 1.0.1             r36h6115d3f_0    r
r-repr                    0.19.2            r36h6115d3f_0    r
r-reprex                  0.2.1             r36h6115d3f_0    r
r-reshape2                1.4.3             r36h6115d3f_0    r
r-rlang                   0.3.4             r36h6115d3f_0    r
r-rmarkdown               1.12              r36h6115d3f_0    r
r-rpart                   4.1_15            r36h6115d3f_0    r
r-rstudioapi              0.10              r36h6115d3f_0    r
r-rvest                   0.3.3             r36h6115d3f_0    r
r-scales                  1.0.0             r36h6115d3f_0    r
r-selectr                 0.4_1             r36h6115d3f_0    r
r-shiny                   1.3.2             r36h6115d3f_0    r
r-sourcetools             0.1.7             r36h6115d3f_0    r
r-spatial                 7.3_11            r36h6115d3f_4    r
r-squarem                 2017.10_1         r36h6115d3f_0    r
r-stringi                 1.4.3             r36h6115d3f_0    r
r-stringr                 1.4.0             r36h6115d3f_0    r
r-survival                2.44_1.1          r36h6115d3f_0    r
r-sys                     3.2               r36h6115d3f_0    r
r-tibble                  2.1.1             r36h6115d3f_0    r
r-tidyr                   0.8.3             r36h6115d3f_0    r
r-tidyselect              0.2.5             r36h6115d3f_0    r
r-tidyverse               1.2.1             r36h6115d3f_0    r
r-timedate                3043.102          r36h6115d3f_0    r
r-tinytex                 0.12              r36h6115d3f_0    r
r-ttr                     0.23_4            r36h6115d3f_0    r
r-utf8                    1.1.4             r36h6115d3f_0    r
r-uuid                    0.1_2             r36h6115d3f_4    r
r-viridislite             0.3.0             r36h6115d3f_0    r
r-whisker                 0.3_2             r36h6115d3f_4    r
r-withr                   2.1.2             r36h6115d3f_0    r
r-xfun                    0.6               r36h6115d3f_0    r
r-xml2                    1.2.0             r36h6115d3f_0    r
r-xtable                  1.8_4             r36h6115d3f_0    r
r-xts                     0.11_2            r36h6115d3f_0    r
r-yaml                    2.2.0             r36h6115d3f_0    r
r-zoo                     1.8_5             r36h6115d3f_0    r
regex                     2020.11.13       py38h2bbff1b_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
rope                      0.18.0                     py_0    defaults
rtree                     0.9.4            py38h21ff451_1    defaults
ruamel_yaml               0.15.87          py38he774522_1    defaults
scikit-image              0.17.2           py38h1e1f486_0    defaults
scikit-learn              0.24.1           py38hf11a4ad_0    defaults
scipy                     1.6.1            py38h14eb087_0    defaults
seaborn                   0.11.1             pyhd3eb1b0_0    defaults
send2trash                1.5.0              pyhd3eb1b0_1    defaults
setuptools                52.0.0           py38haa95532_0    defaults
simplegeneric             0.8.1                    py38_2    defaults
singledispatch            3.6.1           pyhd3eb1b0_1001    defaults
sip                       4.19.13          py38ha925a31_0    defaults
six                       1.15.0           py38haa95532_0    defaults
snappy                    1.1.8                h33f27b4_0    defaults
snowballstemmer           2.1.0              pyhd3eb1b0_0    defaults
sortedcollections         2.1.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.3.0              pyhd3eb1b0_0    defaults
soupsieve                 2.2                pyhd3eb1b0_0    defaults
sphinx                    3.5.1              pyhd3eb1b0_0    defaults
sphinxcontrib             1.0                      py38_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.4              pyhd3eb1b0_0    defaults
sphinxcontrib-websupport  1.2.4                      py_0    defaults
spyder                    4.2.1            py38haa95532_1    defaults
spyder-kernels            1.10.2           py38haa95532_0    defaults
sqlalchemy                1.3.23           py38h2bbff1b_0    defaults
sqlite                    3.33.0               h2a8f88b_0    defaults
statsmodels               0.12.2           py38h2bbff1b_0    defaults
sympy                     1.7.1            py38haa95532_0    defaults
tbb                       2020.3               h74a9793_0    defaults
tblib                     1.7.0                      py_0    defaults
terminado                 0.9.2            py38haa95532_0    defaults
testpath                  0.4.4              pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tifffile                  2021.2.1           pyhd3eb1b0_1    defaults
tk                        8.6.10               he774522_0    defaults
toml                      0.10.1                     py_0    defaults
toolz                     0.11.1             pyhd3eb1b0_0    defaults
tornado                   6.1              py38h2bbff1b_0    defaults
tqdm                      4.56.0             pyhd3eb1b0_0    defaults
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
typed-ast                 1.4.2            py38h2bbff1b_1    defaults
typing_extensions         3.7.4.3            pyha847dfd_0    defaults
ujson                     4.0.2            py38hd77b12b_0    defaults
unicodecsv                0.14.1                   py38_0    defaults
urllib3                   1.26.3             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
watchdog                  1.0.2            py38haa95532_1    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py38_1    defaults
werkzeug                  1.0.1              pyhd3eb1b0_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
win_unicode_console       0.5                      py38_0    defaults
wincertstore              0.2                      py38_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.12.1           py38he774522_1    defaults
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xlsxwriter                1.3.7              pyhd3eb1b0_0    defaults
xlwings                   0.22.0           py38haa95532_0    defaults
xlwt                      1.3.0                    py38_0    defaults
xmltodict                 0.12.0                     py_0    defaults
xz                        5.2.5                h62dcd97_0    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.30.0                     py_0    defaults
zeromq                    4.3.3                ha925a31_3    defaults
zfp                       0.5.5                hd77b12b_4    defaults
zict                      2.0.0              pyhd3eb1b0_0    defaults
zipp                      3.4.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
zope                      1.0                      py38_1    defaults
zope.event                4.5.0                    py38_0    defaults
zope.interface            5.2.0            py38h2bbff1b_0    defaults
zstd                      1.4.5                h04227a9_0    defaults
```
</p></details>

Trying to run the program resulted in this message:
```
C:\MyPrograms\Anaconda\Scripts>anaconda-navigator.exe
Traceback (most recent call last):
  File "C:\MyPrograms\Anaconda\lib\site-packages\qtpy\__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MyPrograms\Anaconda\Scripts\anaconda-navigator-script.py", line 6, in <module>
    from anaconda_navigator.app.main import main
  File "C:\MyPrograms\Anaconda\lib\site-packages\anaconda_navigator\app\main.py", line 22, in <module>      
    from anaconda_navigator.utils.conda import is_conda_available
  File "C:\MyPrograms\Anaconda\lib\site-packages\anaconda_navigator\utils\__init__.py", line 15, in <module>    from qtpy.QtGui import QIcon
  File "C:\MyPrograms\Anaconda\lib\site-packages\qtpy\__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

C:\MyPrograms\Anaconda\Scripts>conda install PySide
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - pyside

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



C:\MyPrograms\Anaconda\Scripts>conda install PyQt
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

```

Thank you for consider the issue

**Comment by Abhishekrkd** [comment]
i'm facing same issue and now the latest anaconda version wont install showing cannot create menus error and if somehow it gets installed (old version ) it wont launch 

i tried all methods like deleting environment variable path , reinstalling it  etc.

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
