### ISSUE TITLE
Conda init throws UnicodeDecodeError on fresh install

### ISSUE THREAD

**Issue by Vichoko** [conda/conda#10534]
## Current Behavior
After a fresh install of ```Miniconda3-latest-Windows-x86_64```  on Windows 10 Pro, i cannot run ```conda init``` on neither CMD and Powershell.

It throws the following stack trace:

```
Traceback (most recent call last):
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\cli\main_init.py", line 50, in execute
    return initialize(context.conda_prefix, selected_shells, for_user, args.system,
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\core\initialize.py", line 119, in initialize
    run_plan(plan2)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\core\initialize.py", line 637, in run_plan
    result = globals()[step['function']](*step.get('args', ()), **step.get('kwargs', {}))
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\core\initialize.py", line 901, in install_activate
    return _install_file(target_path, file_content)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\core\initialize.py", line 842, in _install_file
    original_content = fh.read()
  File "C:\Users\voyanadel\Miniconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 208: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\voyanadel\Miniconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1136, in handle_unexpected_exception
    error_report = self.get_error_report(exc_val, exc_tb)
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1182, in get_error_report
    'traceback': _format_exc(exc_val, exc_tb),
  File "C:\Users\voyanadel\Miniconda3\lib\site-packages\conda\exceptions.py", line 1069, in _format_exc
    formatted_exception = format_exception(exc_type, exc_val, exc_tb)
  File "C:\Users\voyanadel\Miniconda3\lib\traceback.py", line 120, in format_exception
    return list(TracebackException(
  File "C:\Users\voyanadel\Miniconda3\lib\traceback.py", line 509, in __init__
  File "C:\Users\voyanadel\Miniconda3\lib\traceback.py", line 366, in extract
    f.line
  File "C:\Users\voyanadel\Miniconda3\lib\traceback.py", line 288, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "C:\Users\voyanadel\Miniconda3\lib\linecache.py", line 16, in getline
  File "C:\Users\voyanadel\Miniconda3\lib\linecache.py", line 47, in getlines
  File "C:\Users\voyanadel\Miniconda3\lib\linecache.py", line 137, in updatecache
  File "C:\Users\voyanadel\Miniconda3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 3888: invalid start byte
```

On installation, i opted out of the automatic environment variable setup. But i did try to add them manually and conda init still doesn't work.

## Expected Behavior
Even though i added the PATH variables by hand. I still cannot activate any environment because still points to default conda's environment python.

When using conda activate, it pops up this message:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If using 'conda activate' from a batch script, change your
invocation to 'CALL conda.bat activate'.

To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - cmd.exe
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

## Environment Information
* Windows 10 Pro
* I used Latest Miniconda binaries (sha256: 4fa22bba0497babb5b6608cb8843545372a99f5331c8120099ae1d803f627c61)

**Comment by jezdez** [comment]
@Vichoko Could you try again with the Python 3.9 based miniconda with hash `c3a43d6bc4c4fa92454dbfa636ccb859a045d875df602b31ae71b9e0c3fec2b8`?

**Comment by badcodebuilder** [comment]
It happened when I ran `conda init zsh`. And as mentioned in #10023, there should be some illegal characters in your shell config file. You can use any hex-editor to find the illegals char and delete them, such as `hexedit` or `hex editor` extension in vscode. And it will work, at least worked in my PC.
Well, I am using zsh so my shell config file is `.zshrc`, but I do not know where is the default config file for powershell, maybe it is the fault of your personal powershell config file.
