### ISSUE TITLE
No module named 'conda' after python3.6 upgrade to python3.8

### ISSUE THREAD

**Issue by mit10000** [conda/conda#10547]
Because of upgrading numpy 1.13 to 1.18, python was automatically upgraded from 3.6 to 3.8
After this, conda commands get:
`Traceback (most recent call last):
  File "/home/jack/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
`
Refer to
https://stackoverflow.com/questions/61153488/no-module-named-conda-after-conda-update

Tried

```
SITE_PACKAGES=/home/jack/anaconda3/lib/python3.6/site-packages
PYTHON_BASE=/home/jack/anaconda3/bin/python
PYTHONPATH=$SITE_PACKAGES $PYTHON_BASE -m conda list --revisions
```

got

```
2019-02-06 15:16:40  (rev 0)
...
+typing-3.6.2
...
2019-02-19 10:38:55  (rev 4)
     ca-certificates  {2018.11.29 (conda-forge) -> 2019.1.23}
    +gdcm-2.8.4 (clinicalgraphics)

2020-12-28 19:21:10  (rev 5)
     ca-certificates  {2019.1.23 -> 2020.12.8}
     certifi  {2018.11.29 (conda-forge) -> 2020.12.5}
     libedit  {3.1.20181209 -> 3.1.20191231}
     libffi  {3.2.1 -> 3.3}
     libgcc-ng  {8.2.0 -> 9.1.0}
     mkl  {2018.0.0 -> 2020.2}
     mkl-service  {1.1.2 -> 2.3.0}
     ncurses  {6.1 -> 6.2}
     numpy  {1.13.3 -> 1.18.5}
     openssl  {1.1.1a (conda-forge) -> 1.1.1i}
     pip  {9.0.1 -> 20.3.3}
     python  {3.6.8 -> 3.8.5}
     readline  {7.0 -> 8.0}
     setuptools  {36.5.0 -> 51.0.0}
     six  {1.11.0 -> 1.15.0}
     sqlite  {3.26.0 -> 3.33.0}
     tk  {8.6.8 -> 8.6.10}
     wheel  {0.29.0 -> 0.36.2}
     xz  {5.2.4 -> 5.2.5}
     zlib  {1.2.11 -> 1.2.11}
    +_libgcc_mutex-0.1
    +ld_impl_linux-64-2.33.1
    +mkl_fft-1.2.0
    +mkl_random-1.1.1
    +numpy-base-1.18.5

```

Obviously  2020-12-28 19:21:10  (rev 5) screwed up everything. 
Tried to go back

PYTHONPATH=$SITE_PACKAGES $PYTHON_BASE -m conda install --revision 4

and got error

```
...
  File "/home/jack/anaconda3/lib/python3.6/site-packages/typing.py", line 1024, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jack/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1134, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/home/jack/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 230, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

```

Seems the 

AttributeError: type object 'Callable' has no attribute '_abc_registry'

error is related to typing, but tried 

```
pip uninstall typing
pip3 uninstall typing
PYTHONPATH=$SITE_PACKAGES $PYTHON_BASE -m conda remove typing
```

none of the above worked (the last command get the same error 'abc_registry'). What should I do ? 
Thanks for help.

```

**Comment by henryf10h** [comment]
I have the same problem. I get:

C:\Users\Henry Alberto>conda update --all
Traceback (most recent call last):
  File "C:\Users\Henry Alberto\anaconda3\Scripts\conda-script.py", line 11, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
