### ISSUE TITLE
Update issue: An unexpected error has occurred

### ISSUE THREAD

**Issue by FinLouarn** [conda/conda#1054]
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |  22%
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/bastimalo/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    if getattr(args, 'json', False):
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 93, in execute
    
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/plan.py", line 374, in execute_actions
    continue
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/plan.py", line 359, in execute_plan
    # if something depends on Python/Numpy, but the spec is very
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/plan.py", line 314, in link
    actions[UNLINK].append(dist)
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/install.py", line 386, in link
    assert not isfile(dst), dst
  File "/Users/bastimalo/anaconda/lib/python2.7/site-packages/conda/install.py", line 167, in update_prefix
    msg += "Retry with onerror failed (%s)\n" % e1
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an binary lib/libcrypto.1.0.0.dylib'

**Comment by asmeurer** [comment]
This should be fixed.
