### ISSUE TITLE
KeyError: 'python' when installing packages into an fresh environment

### ISSUE THREAD

**Issue by tmoschou** [conda/conda#10557]
## Current Behavior
Installing packages into a fresh (empty) conda environment fails with `KeyError: 'python'` when using `conda install --name NAME`.

It seems a workaround is to minimally specify the `python` package as an argument to `conda create`

Further when running with `--json --yes` the stdout is not valid JSON as the line `Upload successful.` is printed to standard out too.

Though I guess `install --yes` does mean `Do not ask for confirmation`, I was partly surprised / concerned this extends to automatically uploading information to the internet without review / intervention, as I suspect the normal user would presume `--yes` would only extend to confirmation of installing packages.

### Steps to Reproduce
1. Create fresh installation

```bash
$ ./Miniconda3-py38_4.9.2-MacOSX-x86_64.sh -b -f -p /tmp/conda-root
```

1. Create new empty environment (`my-env`)

```bash
$ /tmp/conda-root/bin/conda create --name my-env --json --quiet --yes
```

```json
{
  "actions": {
    "FETCH": [],
    "PREFIX": "/tmp/conda-root/envs/my-env"
  },
  "prefix": "/tmp/conda-root/envs/my-env",
  "success": true
}
```

1. Install `notebook` into `my-env`

```
$ /tmp/conda-root/bin/conda install --name my-env --update-deps notebook --yes --quiet &> log-install.txt
```

   <details open><summary><code>cat log-install.txt</code></summary><p>

    Collecting package metadata (current_repodata.json): ...working... done
    Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
    Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
    Collecting package metadata (repodata.json): ...working... done
    Solving environment: ...working... failed
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
            return getattr(module, func_name)(args, parser)
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
            install(args, parser, 'install')
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
            unlink_link_transaction = solver.solve_for_transaction(
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
            unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
            final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py", line 301, in solve_final_state
            ssc = self._post_sat_handling(ssc)
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py", line 929, in _post_sat_handling
            python_rec = ssc.prefix_data.get("python")
          File "/tmp/conda-root/lib/python3.8/site-packages/conda/core/prefix_data.py", line 132, in get
            return self._prefix_records[package_name]
        KeyError: 'python'
    
    `$ /tmp/conda-root/bin/conda install --name my-env --update-deps notebook --yes --quiet`
    
      environment variables:
                     CIO_TEST=<not set>
                   CONDA_ROOT=/tmp/conda-root
               CURL_CA_BUNDLE=<not set>
                         PATH=/usr/local/opt/node@14/bin:/usr/local/Caskroom/google-cloud-
                              sdk/latest/google-cloud-sdk/bin:/Users/<REDACTED>/.cargo/bin:/Users/<REDACTED>
                              /.rbenv/shims:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/mo
                              s095/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Librar
                              y/TeX/texbin:/usr/local/laps:/usr/local/MacGPG2/bin:/usr/local/munki:/
                              Library/Apple/usr/bin:/Applications/Computer Admin.app/Contents/Resour
                              ces:/Applications/Wireshark.app/Contents/MacOS:/Users/<REDACTED>/dist/spar
                              k-2.4.6-bin-hadoop2.7-scala2.12/bin
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : None
           user config file : /Users/<REDACTED>/.condarc
     populated config files : 
              conda version : 4.9.2
        conda-build version : not installed
             python version : 3.8.5.final.0
           virtual packages : __osx=10.16=0
                              __unix=0=0
                              __archspec=1=x86_64
           base environment : /tmp/conda-root  (writable)
               channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/osx-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /tmp/conda-root/pkgs
                              /Users/<REDACTED>/.conda/pkgs
           envs directories : /tmp/conda-root/envs
                              /Users/<REDACTED>/.conda/envs
                   platform : osx-64
                 user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                    UID:GID : 1057425:20
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    
    Upload successful.   </p></details>

1. (Additional issue with `--json --yes`  behaviour producing invalid JSON)

```
$ /tmp/conda-root/bin/conda install --name my-env --update-deps notebook --yes --quiet --json | tee log-install.json | jq .
parse error: Invalid numeric literal at line 80, column 7
```

   <details open><summary><code>cat log-install.json</code></summary><p>

```
{
  "command": "/tmp/conda-root/bin/conda install --name my-env --update-deps notebook --yes --quiet --json",
  "conda_info": {
    "GID": 20,
    "UID": 1057425,
    "active_prefix": null,
    "active_prefix_name": null,
    "channels": [
      "https://repo.anaconda.com/pkgs/main/osx-64",
      "https://repo.anaconda.com/pkgs/main/noarch",
      "https://repo.anaconda.com/pkgs/r/osx-64",
      "https://repo.anaconda.com/pkgs/r/noarch"
    ],
    "conda_build_version": "not installed",
    "conda_env_version": "4.9.2",
    "conda_location": "/tmp/conda-root/lib/python3.8/site-packages/conda",
    "conda_prefix": "/tmp/conda-root",
    "conda_private": false,
    "conda_shlvl": -1,
    "conda_version": "4.9.2",
    "config_files": [],
    "default_prefix": "/tmp/conda-root",
    "env_vars": {
      "CIO_TEST": "<not set>",
      "CONDA_ROOT": "/tmp/conda-root",
      "CURL_CA_BUNDLE": "<not set>",
      "PATH": "/usr/local/opt/node@14/bin:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/Users/<REDACTED>/.cargo/bin:/Users/<REDACTED>/.rbenv/shims:/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims:/Users/<REDACTED>/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/laps:/usr/local/MacGPG2/bin:/usr/local/munki:/Library/Apple/usr/bin:/Applications/Computer Admin.app/Contents/Resources:/Applications/Wireshark.app/Contents/MacOS:/Users/<REDACTED>/dist/spark-2.4.6-bin-hadoop2.7-scala2.12/bin",
      "REQUESTS_CA_BUNDLE": "<not set>",
      "SSL_CERT_FILE": "<not set>"
    },
    "envs": [],
    "envs_dirs": [
      "/tmp/conda-root/envs",
      "/Users/<REDACTED>/.conda/envs"
    ],
    "netrc_file": null,
    "offline": false,
    "pkgs_dirs": [
      "/tmp/conda-root/pkgs",
      "/Users/<REDACTED>/.conda/pkgs"
    ],
    "platform": "osx-64",
    "python_version": "3.8.5.final.0",
    "rc_path": "/Users/<REDACTED>/.condarc",
    "requests_version": "2.24.0",
    "root_prefix": "/tmp/conda-root",
    "root_writable": true,
    "site_dirs": [
      "~/.local/lib/python3.6"
    ],
    "sys.executable": "/tmp/conda-root/bin/python",
    "sys.prefix": "/tmp/conda-root",
    "sys.version": "3.8.5 (default, Sep  4 2020, 02:22:02) \n[Clang 10.0.0 ]",
    "sys_rc_path": "/tmp/conda-root/.condarc",
    "user_agent": "conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16",
    "user_rc_path": "/Users/<REDACTED>/.condarc",
    "virtual_pkgs": [
      [
        "__osx",
        "10.16",
        "0"
      ],
      [
        "__unix",
        "0",
        "0"
      ],
      [
        "__archspec",
        "1",
        "x86_64"
      ]
    ]
  },
  "error": "KeyError('python')",
  "exception_name": "KeyError",
  "exception_type": "<class 'KeyError'>",
  "traceback": "Traceback (most recent call last):\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/exceptions.py\", line 1079, in __call__\n    return func(*args, **kwargs)\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/cli/main.py\", line 84, in _main\n    exit_code = do_call(args, p)\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/cli/conda_argparse.py\", line 83, in do_call\n    return getattr(module, func_name)(args, parser)\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/cli/main_install.py\", line 20, in execute\n    install(args, parser, 'install')\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/cli/install.py\", line 261, in install\n    unlink_link_transaction = solver.solve_for_transaction(\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py\", line 114, in solve_for_transaction\n    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py\", line 157, in solve_for_diff\n    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py\", line 301, in solve_final_state\n    ssc = self._post_sat_handling(ssc)\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/core/solve.py\", line 929, in _post_sat_handling\n    python_rec = ssc.prefix_data.get(\"python\")\n  File \"/tmp/conda-root/lib/python3.8/site-packages/conda/core/prefix_data.py\", line 132, in get\n    return self._prefix_records[package_name]\nKeyError: 'python'\n"
}
Upload successful.
```

   </p></details>

## Expected Behavior
The command should not fail.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /Users/<REDACTED>/.condarc
 populated config files :
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /tmp/conda-root  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/conda-root/pkgs
                          /Users/<REDACTED>/.conda/pkgs
       envs directories : /tmp/conda-root/envs
                          /Users/<REDACTED>/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.3.0 OSX/10.16
                UID:GID : 1057425:20
             netrc file : None
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /tmp/conda-root:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h9ed2024_1003    defaults
ca-certificates           2020.10.14                    0    defaults
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
cffi                      1.14.3           py38h2125817_2    defaults
chardet                   3.0.4           py38hecd8cb5_1003    defaults
conda                     4.9.2            py38hecd8cb5_0    defaults
conda-package-handling    1.7.2            py38h22f3db7_0    defaults
cryptography              3.2.1            py38hbcfaee0_1    defaults
idna                      2.10                       py_0    defaults
libcxx                    10.0.0                        1    defaults
libedit                   3.1.20191231         h1de35cc_1    defaults
libffi                    3.3                  hb1e8313_2    defaults
ncurses                   6.2                  h0a44026_1    defaults
openssl                   1.1.1h               haf1e3a3_0    defaults
pip                       20.2.4           py38hecd8cb5_0    defaults
pycosat                   0.6.3            py38h1de35cc_1    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 19.1.0             pyhd3eb1b0_1    defaults
pysocks                   1.7.1                    py38_1    defaults
python                    3.8.5                h26836e1_1    defaults
python.app                2                       py38_10    defaults
readline                  8.0                  h1de35cc_0    defaults
requests                  2.24.0                     py_0    defaults
ruamel_yaml               0.15.87          py38haf1e3a3_1    defaults
setuptools                50.3.1           py38hecd8cb5_1    defaults
six                       1.15.0           py38hecd8cb5_0    defaults
sqlite                    3.33.0               hffcf06c_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
tqdm                      4.51.0             pyhd3eb1b0_0    defaults
urllib3                   1.25.11                    py_0    defaults
wheel                     0.35.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

</p></details>

**Comment by manosnoam** [comment]
This error has happened to me as well, installing a new conda package the first time, while using "--update-deps" :

```
$ conda install -y --update-deps -c conda-forge google-cloud-sdk

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/cli/install.py", line 259, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/core/solve.py", line 157, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/core/solve.py", line 301, in solve_final_state
        ssc = self._post_sat_handling(ssc)
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/core/solve.py", line 929, in _post_sat_handling
        python_rec = ssc.prefix_data.get("python")
      File "/mnt/skynet-data/miniconda/lib/python3.9/site-packages/conda/core/prefix_data.py", line 132, in get
        return self._prefix_records[package_name]
    KeyError: 'python'

`$ /mnt/skynet-data/miniconda/bin/conda install -y --update-deps -c conda-forge google-cloud-sdk`

  environment variables:
                 CIO_TEST=<not set>
      CONDA_BACKUP_GOROOT=
        CONDA_DEFAULT_ENV=conda-test
                CONDA_EXE=/mnt/skynet-data/miniconda/bin/conda
        CONDA_GO_COMPILER=1
             CONDA_PREFIX=/mnt/skynet-data/miniconda/envs/conda-test
    CONDA_PROMPT_MODIFIER=(conda-test)
         CONDA_PYTHON_EXE=/mnt/skynet-data/miniconda/bin/python
               CONDA_ROOT=/mnt/skynet-data/miniconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/mnt/skynet-data/miniconda/bin:/mnt/skynet-data/skynet-
                          env-2/miniconda/envs/conda-test/bin:/mnt/skynet-data/skynet-
                          env-2/miniconda/condabin:/mnt/skynet-data/skynet-
                          env-2/miniconda/bin:/mnt/skynet-data/GOBIN:/usr/local/sbi
                          n:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : conda-test
    active env location : /mnt/skynet-data/miniconda/envs/conda-test
            shell level : 1
       user config file : /home/jenkins/.condarc
 populated config files : /home/jenkins/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/skynet-data/miniconda  (writable)
      conda av data dir : /mnt/skynet-data/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/skynet-data/miniconda/pkgs
                          /home/jenkins/.conda/pkgs
       envs directories : /mnt/skynet-data/miniconda/envs
                          /home/jenkins/.conda/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.9.5 Linux/4.18.0-305.28.1.el8_4.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 1007420000:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```

Once I run it without "--update-deps", the package was installed successfully.
