### ISSUE TITLE
conda install fails with OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

### ISSUE THREAD

**Issue by cocoaaa** [conda/conda#10555]
## Current Behavior

Trying to run `conda install <new-package>` fails in this specific conda environment with ECONNERESET error (OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')).  Similar to the issue #10314, but I don't have issue creating a new environment: e.g. `conda create -n new_env osmnx` works properly without an error.  I am suspicious  that something is broken in my current environment.  This environment was built to support PyTorch built from source (on CentOS Linux release 7.5.1804 (Core)) with Cuda10.2, and I'm wondering if something might have gone wrong along the way.  I have no issue using the libraries in this environment though: PyTorch runs with GPUs properly.  `pip install` succeeds in installing the libraries, but I'm hesitant to mix conda-managed packages and pip-managed ones, especially with geo-related libraries (eg. gdal) as they are known to be very picky about the versions of the dependent libraries.  I would appreciate any help in figuring out what is causing this error in this particular conda-environment. Thanks!

### Steps to Reproduce

```
conda install osmnx 
```

fails with this error:

    Collecting package metadata (current_repodata.json): done
    Solving environment: failed with initial frozen solve. Retrying with flexible solve.
    Solving environment: done
    
    
    ==> WARNING: A newer version of conda exists. <==
      current version: 4.8.3
      latest version: 4.9.2
    
    Please update conda by running
    
        $ conda update -n base -c defaults conda
    
    
    Collecting package metadata (repodata.json): failed
    
    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    
        Traceback (most recent call last):
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 313, in recv_into
            return self.connection.recv_into(*args, **kwargs)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
            self._raise_ssl_error(self._ssl, result)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
            raise SysCallError(errno, errorcode.get(errno))
        OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 425, in _error_catcher
            yield
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 752, in read_chunked
            self._update_chunk_length()
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 682, in _update_chunk_length
            line = self._fp.fp.readline()
          File "/home/hayley/miniconda3/lib/python3.8/socket.py", line 669, in readinto
            return self._sock.recv_into(b)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/contrib/pyopenssl.py", line 318, in recv_into
            raise SocketError(str(e))
        OSError: (104, 'ECONNRESET')
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/requests/models.py", line 751, in generate
            for chunk in self.raw.stream(chunk_size, decode_content=True):
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 560, in stream
            for line in self.read_chunked(amt, decode_content=decode_content):
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 781, in read_chunked
            self._original_response.close()
          File "/home/hayley/miniconda3/lib/python3.8/contextlib.py", line 131, in __exit__
            self.gen.throw(type, value, traceback)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/urllib3/response.py", line 443, in _error_catcher
            raise ProtocolError("Connection broken: %r" % e, e)
        urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
            return func(*args, **kwargs)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
            return getattr(module, func_name)(args, parser)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
            install(args, parser, 'install')
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 261, in install
            unlink_link_transaction = solver.solve_for_transaction(
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
            unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
            final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 262, in solve_final_state
            ssc = self._collect_all_metadata(ssc)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
            return f(*args, **kwds)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
            index, r = self._prepare(prepared_specs)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1010, in _prepare
            reduced_index = get_reduced_index(self.prefix, self.channels,
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 227, in get_reduced_index
            new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 105, in query_all
            result = tuple(concat(executor.map(subdir_query, channel_urls)))
          File "/home/hayley/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 611, in result_iterator
            yield fs.pop().result()
          File "/home/hayley/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 439, in result
            return self.__get_result()
          File "/home/hayley/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
            raise self._exception
          File "/home/hayley/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
            result = self.fn(*self.args, **self.kwargs)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 97, in <lambda>
            subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 110, in query
            self.load()
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 174, in load
            _internal_state = self._load()
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 244, in _load
            raw_repodata_str = fetch_repodata_remote_request(
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/conda/core/subdir_data.py", line 484, in fetch_repodata_remote_request
            resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 543, in get
            return self.request('GET', url, **kwargs)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 530, in request
            resp = self.send(prep, **send_kwargs)
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 683, in send
            r.content
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/requests/models.py", line 829, in content
            self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
          File "/home/hayley/miniconda3/lib/python3.8/site-packages/requests/models.py", line 754, in generate
            raise ChunkedEncodingError(e)
        requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(104, \'ECONNRESET\')")', OSError("(104, 'ECONNRESET')"))
    
    `$ /home/hayley/miniconda3/bin/conda install osmnx`
    
      environment variables:
                     CIO_TEST=<not set>
            CONDA_DEFAULT_ENV=test
                    CONDA_EXE=/home/hayley/miniconda3/bin/conda
                 CONDA_PREFIX=/home/hayley/miniconda3/envs/test
               CONDA_PREFIX_1=/home/hayley/miniconda3
        CONDA_PROMPT_MODIFIER=(test)
       CONDA_PYTHONBREAKPOINT=
             CONDA_PYTHON_EXE=/home/hayley/miniconda3/bin/python
                   CONDA_ROOT=/home/hayley/miniconda3
                  CONDA_SHLVL=2
              LD_LIBRARY_PATH=/usr/local/lib64:/usr/local/cuda/lib64
                         PATH=/home/hayley/miniconda3/bin:/home/hayley/miniconda3/envs/test/bin:/hom
                              e/hayley/miniconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/
                              usr/sbin:/usr/local/cuda/bin:~/julia-1.5.3/bin:/home/hayley/.local/bin
                              :/home/hayley/bin
             PYTHONBREAKPOINT=ipdb.set_trace
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
    
         active environment : test
        active env location : /home/hayley/miniconda3/envs/test
                shell level : 2
           user config file : /home/hayley/.condarc
     populated config files : /home/hayley/.condarc
              conda version : 4.8.3
        conda-build version : not installed
             python version : 3.8.3.final.0
           virtual packages : __cuda=10.2
                              __glibc=2.17
           base environment : /home/hayley/miniconda3  (writable)
               channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://repo.anaconda.com/pkgs/main/linux-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/linux-64
                              https://repo.anaconda.com/pkgs/r/noarch
              package cache : /home/hayley/miniconda3/pkgs
                              /home/hayley/.conda/pkgs
           envs directories : /home/hayley/miniconda3/envs
                              /home/hayley/.conda/envs
                   platform : linux-64
                 user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/3.10.0-862.11.6.el7.x86_64 centos/7.5.1804 glibc/2.17
                    UID:GID : 1036:1036
                 netrc file : None
               offline mode : False
    
    
    An unexpected error has occurred. Conda has prepared the above report.
    `conda install <other-package-name>` fails too (eg. numpy), so I don't think this is an issue of the `osmnx` package. 

## Expected Behavior

I would expect the package to be installed.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
 active environment : test
    active env location : /home/hayley/miniconda3/envs/test
            shell level : 2
       user config file : /home/hayley/.condarc
 populated config files : /home/hayley/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __cuda=10.2
                          __glibc=2.17
       base environment : /home/hayley/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/hayley/miniconda3/pkgs
                          /home/hayley/.conda/pkgs
       envs directories : /home/hayley/miniconda3/envs
                          /home/hayley/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/3.10.0-862.11.6.el7.x86_64 centos/7.5.1804 glibc/2.17
                UID:GID : 1036:1036
             netrc file : None
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/hayley/.condarc <==
channels:
  - conda-forge
  - defaults
```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/hayley/miniconda3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   0.11.0           py38h578d9bd_0    conda-forge
aiohttp                   3.7.3            py38h25fe258_0    conda-forge
aiohttp-cors              0.7.0                    pypi_0    pypi
aioredis                  1.3.1                    pypi_0    pypi
argon2-cffi               20.1.0           py38h25fe258_2    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
bayesian-optimization     1.2.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    3.2.1              pyh9f0ad1d_0    conda-forge
blessings                 1.7                      pypi_0    pypi
blinker                   1.4                        py_1    conda-forge
boto3                     1.16.35            pyhd8ed1ab_0    conda-forge
botocore                  1.19.35            pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
c-ares                    1.17.1               h36c2ea0_0    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cachetools                4.1.1                      py_0    conda-forge
certifi                   2020.12.5        py38h578d9bd_1    conda-forge
cffi                      1.14.4           py38ha65f79e_1    conda-forge
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
colorama                  0.4.4                    pypi_0    pypi
colorful                  0.5.4                    pypi_0    pypi
cryptography              3.3.1            py38h2b97feb_0    conda-forge
cudatoolkit               10.2.89              h8f6ccaa_6    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h25fe258_1    conda-forge
dask-core                 2020.12.0          pyhd8ed1ab_0    conda-forge
dbus                      1.13.16              hb2f20db_0    defaults
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
enum34                    1.1.10           py38h32f6830_2    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
filelock                  3.0.12                   pypi_0    pypi
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h7ca028e_0    conda-forge
fsspec                    0.8.4                      py_0    conda-forge
future                    0.18.2           py38h578d9bd_2    conda-forge
geographiclib             1.50                       py_0    conda-forge
geopy                     2.1.0              pyhd3deb0d_0    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
glib                      2.66.3               h9c3ff4c_1    conda-forge
google-api-core           1.24.1                   pypi_0    pypi
google-auth               1.23.0             pyhd8ed1ab_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
googleapis-common-protos  1.52.0                   pypi_0    pypi
gpustat                   0.6.0                    pypi_0    pypi
grpcio                    1.34.0           py38hdd6454d_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb31296c_0    defaults
gym                       0.17.3                   pypi_0    pypi
h5py                      3.1.0           nompi_py38hafa665b_100    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1112    conda-forge
hiredis                   1.1.0                    pypi_0    pypi
hyperopt                  0.2.5              pyh9f0ad1d_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs-lite          2019.12.3        py38hab2c0dc_3    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        3.1.1              pyhd8ed1ab_0    conda-forge
importlib_metadata        3.1.1                hd8ed1ab_0    conda-forge
ipdb                      0.13.4             pyhd3deb0d_0    conda-forge
ipykernel                 5.4.2            py38h81c977d_0    conda-forge
ipython                   7.19.0           py38h81c977d_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1              pyh9f0ad1d_1    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jedi                      0.17.2           py38h578d9bd_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    0.17.0                     py_0    conda-forge
jpeg                      9b                   h024ee3a_2    defaults
jsonschema                3.2.0                      py_2    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            6.1.7                      py_0    conda-forge
jupyter_console           6.2.0                      py_0    conda-forge
jupyter_core              4.7.0            py38h578d9bd_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
kaggle                    1.5.10                   pypi_0    pypi
kiwisolver                1.3.1            py38h82cb98a_0    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
lcms2                     2.11                 h396b838_0    defaults
ld_impl_linux-64          2.35.1               hed1e6ac_0    conda-forge
libblas                   3.9.0           1_h86c2bf4_netlib    conda-forge
libcblas                  3.9.0           3_h92ddd45_netlib    conda-forge
libcurl                   7.71.1               hcdd3856_8    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h5dbcf3e_17    conda-forge
libgfortran-ng            9.3.0               he4bcb1c_17    conda-forge
libgfortran5              9.3.0               he4bcb1c_17    conda-forge
libglib                   2.66.3               h1f3bc88_1    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0           3_h92ddd45_netlib    conda-forge
libnghttp2                1.41.0               h8cfc5f6_2    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libprotobuf               3.14.0               h780b84a_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.9.0                hab1572f_5    conda-forge
libstdcxx-ng              9.3.0               h2ae2ef3_17    conda-forge
libtiff                   4.1.0                h2733197_1    defaults
libuuid                   2.32.1            h7f98852_1000    conda-forge
libuv                     1.40.0               hd18ef5c_0    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hb55368b_3    defaults
libxslt                   1.1.34               hc22bd24_0    defaults
llvm-openmp               11.0.0               hfc4b9b4_1    conda-forge
lxml                      4.6.2            py38hf1fe3a4_0    conda-forge
lz4-c                     1.9.2                he1b5a44_3    conda-forge
markdown                  3.3.3              pyh9f0ad1d_0    conda-forge
markupsafe                1.1.1            py38h8df0ef7_2    conda-forge
matplotlib                3.3.3            py38h578d9bd_0    conda-forge
matplotlib-base           3.3.3            py38h5c7f4ab_0    conda-forge
mistune                   0.8.4           py38h25fe258_1002    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mkl-service               2.3.0            py38h1e0a361_2    conda-forge
mkl_fft                   1.2.0            py38hab2c0dc_1    conda-forge
mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
msgpack                   1.0.2                    pypi_0    pypi
multidict                 4.7.5            py38h1e0a361_2    conda-forge
nbclient                  0.5.1                      py_0    conda-forge
nbconvert                 6.0.7            py38h578d9bd_3    conda-forge
nbformat                  5.0.8                      py_0    conda-forge
nbstripout                0.3.9              pyh9f0ad1d_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    conda-forge
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2               h4bd325d_0    conda-forge
notebook                  6.1.5            py38h578d9bd_0    conda-forge
numpy                     1.19.2           py38h54aff64_0    defaults
numpy-base                1.19.2           py38hfa32c7d_0    defaults
nvidia-ml-py3             7.352.0                  pypi_0    pypi
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencensus                0.7.11                   pypi_0    pypi
opencensus-context        0.1.2                    pypi_0    pypi
openssl                   1.1.1j               h7f98852_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.7               pyhd3deb0d_0    conda-forge
pandas                    1.1.5            py38h51da96c_0    conda-forge
pandas-datareader         0.8.1                      py_0    conda-forge
pandoc                    2.11.2               h36c2ea0_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
pathlib                   1.0.1            py38h32f6830_3    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.0.1            py38he98fc37_0    defaults
pip                       20.3.1             pyhd8ed1ab_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    conda-forge
prompt_toolkit            3.0.8                hd8ed1ab_0    conda-forge
protobuf                  3.14.0           py38h709712a_0    conda-forge
psutil                    5.8.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py-spy                    0.3.3                    pypi_0    pypi
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyglet                    1.5.0                    pypi_0    pypi
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyjwt                     1.7.1                      py_0    conda-forge
pymongo                   3.11.0           py38h348cfbe_4    conda-forge
pyopenssl                 20.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py38h05f1152_4    defaults
pyro-api                  0.1.2                    pypi_0    pypi
pyro-ppl                  1.5.1                    pypi_0    pypi
pyrsistent                0.17.3           py38h25fe258_1    conda-forge
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.6           hffdb5ce_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-slugify            4.0.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.7.1           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
pytorch-lightning         1.1.0              pyhd8ed1ab_0    conda-forge
pytz                      2020.4             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py38h5c078b8_3    conda-forge
pyyaml                    5.3.1            py38h8df0ef7_1    conda-forge
pyzmq                     20.0.0           py38h1d1b12f_1    conda-forge
qt                        5.9.7                h5867ecd_1    defaults
qtconsole                 5.0.1              pyhd8ed1ab_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
ray                       1.2.0                    pypi_0    pypi
readline                  8.0                  he28a2e2_2    conda-forge
redis                     3.5.3                    pypi_0    pypi
requests                  2.25.0             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.6                pyh9f0ad1d_0    conda-forge
s3transfer                0.3.3                      py_3    conda-forge
scikit-image              0.17.2           py38h51da96c_4    conda-forge
scikit-learn              0.23.2           py38h5d63f67_3    conda-forge
scipy                     1.5.3            py38hb2138dd_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h924ce5b_2    conda-forge
sip                       4.19.13          py38he6710b0_0    defaults
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.34.0               h74cdb3f_0    conda-forge
tabulate                  0.8.7                    pypi_0    pypi
tensorboard               2.4.0              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.7.0              pyh9f0ad1d_0    conda-forge
tensorboardx              2.1                      pypi_0    pypi
terminado                 0.9.1            py38h32f6830_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
text-unidecode            1.3                      pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2019.7.26.2              py38_0    conda-forge
tk                        8.6.10               hed695b0_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
torchaudio                0.7.2                      py38    pytorch
torchvision               0.8.2                py38_cu102    pytorch
tornado                   6.1              py38h25fe258_0    conda-forge
tqdm                      4.54.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.25.11                    py_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.36.1             pyhd3deb0d_0    conda-forge
widgetsnbextension        3.5.1            py38h578d9bd_4    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yarl                      1.6.3            py38h25fe258_0    conda-forge
zeromq                    4.3.3                h58526e2_3    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.5                h6597ccf_2    conda-forge
```

</p></details>

**Comment by cocoaaa** [comment]
Hi, just wanted to check in if anyone has a suggestion on this issue?
