### ISSUE TITLE
Cannot load conda in command prompt;

### ISSUE THREAD

**Issue by Lupiya** [conda/conda#10577]
**I'm submitting a...**

* [x] bug report
* [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```

</p></details>

**Comment by Lupiya** [comment]
failed to create process.
Invoke-Expression : Cannot bind argument to parameter 'Command' because it is an empty string.
At C:\Users\eliud\anaconda3\New folder\shell\condabin\Conda.psm1:101 char:36
+         Invoke-Expression -Command $activateCommand;
+                                    ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Invoke-Expression], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Microsoft.PowerShell.Commands.Invo
   keExpressionCommand

PS C:\Users\eliud> conda
failed to create process.
PS C:\Users\eliud> conda
failed to create process.
PS C:\Users\eliud> python
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 22:45:29) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> This is what I am getting

**Comment by arthurgailes** [comment]
I have the same issue running any conda command, here's an example with `conda info`

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 317, in execute
        info_dict = get_info_dict(args.system)
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 163, in get_info_dict
        pkgs_dirs=context.pkgs_dirs,
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\base\context.py", line 524, in pkgs_dirs
        fixed_dirs += user_data_dir(APP_NAME, APP_NAME),
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
        path = os.path.join(_get_win_folder(const), appauthor, appname)
      File "C:\Users\{user}\Miniconda3\lib\site-packages\conda\_vendor\appdirs.py", line 284, in _get_win_folder_with_pywin32
        from win32com.shell import shellcon, shell
    ImportError: DLL load failed while importing shell: The specified procedure could not be found.

`$ C:\Users\{user}\Miniconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.
```
