### ISSUE TITLE
conda env remove tries to remove parent path /tmp/, fails & crashes

### ISSUE THREAD

**Issue by BlackHC** [conda/conda#10588]
## Current Behavior

I'm creating a conda environment in /tmp/ on a compute node. /tmp/ is empty otherwise.

At the end of our experiment, our wrapper code executes `conda env remove`.

`conda env remove`  fails:
```
Remove all packages in environment /tmp/conda_envs/job-1529697:


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/system/software/arcus-b/python/anaconda3/2020.02/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/system/software/arcus-b/python/anaconda3/2020.02/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/system/software/arcus-b/python/anaconda3/2020.02/lib/python3.7/site-packages/conda_env/cli/main_remove.py", line 52, in execute
        conda.cli.main_remove.execute(args, parser)
      File "/system/software/arcus-b/python/anaconda3/2020.02/lib/python3.7/site-packages/conda/cli/main_remove.py", line 73, in execute
        rm_rf(prefix, clean_empty_parents=True)
      File "/system/software/arcus-b/python/anaconda3/2020.02/lib/python3.7/site-packages/conda/gateways/disk/delete.py", line 174, in rm_rf
        remove_empty_parent_paths(path)
      File "/system/software/arcus-b/python/anaconda3/2020.02/lib/python3.7/site-packages/conda/gateways/disk/delete.py", line 147, in remove_empty_parent_paths
        rmdir(parent_path)
    PermissionError: [Errno 13] Permission denied: '/tmp'
```

`$ /system/software/arcus-b/python/anaconda3/2020.02/bin/conda-env remove -q -y -p /tmp/conda_envs/job-1529697`

```
  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
          CONDA_ENVS_PATH=/tmp/conda_envs
            
   CURRENT_CONDA_ENV_PATH=/tmp/conda_envs/job-1529697
          
           PYTHON_VERSION=3.8
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/XXX/.condarc
 populated config files : /home/XXX/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.17
       base environment : /system/software/arcus-b/python/anaconda3/2020.02  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /XXX/conda_pkgs_cache
       envs directories : /tmp/conda_envs
                          /home/XXX/.conda/envs
                          /system/software/arcus-b/python/anaconda3/2020.02/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/3.10.0-1062.12.1.el7.x86_64 centos/7.7.1908 glibc/2.17
                UID:GID : 6139:1001
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

## Expected Behavior

It should not crash when failing to remove parent directories (for no reason).

## Source Code

The issue still exists in the current master branch: 

https://github.com/conda/conda/blob/aed799b56d9ee16a3653928527e2af6e41394e85/conda/gateways/disk/delete.py#L147

I went through the stack trace and verified it.

## Ask

Could you wrap the code in a try/except and ignore a failure to remove a parent directory? It is not necessary as a clean-up (and not even wanted tbf).

Thanks so much,
 Andreas

**Comment by BlackHC** [comment]
If the other issues that are about this same issue are fixed, I would be very grateful.
