### ISSUE TITLE
conda skeleton fails with conda >=4.10.0 and artifact verification enabled

### ISSUE THREAD

**Issue by chenghlee** [conda/conda#10613]
## Current Behavior

`conda skeleton` with artifact verification enabled fails with the following error:

```
Traceback (most recent call last):
  File "$CONDA_PREFIX/bin/conda-skeleton", line 11, in <module>
    sys.exit(main())
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/cli/main_skeleton.py", line 60, in execute
    api.skeletonize(args.packages, args.repo, output_dir=args.output_dir, recursive=args.recursive,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/api.py", line 276, in skeletonize
    skeleton_return = module.skeletonize(packages, output_dir=output_dir, version=version,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 317, in skeletonize
    get_package_metadata(package, d, data, output_dir, python_version,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 720, in get_package_metadata
    pkginfo = get_pkginfo(package,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 1174, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version, extra_specs=extra_specs, config=config,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/skeletons/pypi.py", line 1215, in run_setuppy
    create_env(config.host_prefix, specs_or_actions=specs, env='host',
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/environ.py", line 885, in create_env
    actions = get_install_actions(prefix, tuple(specs), env,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/environ.py", line 785, in get_install_actions
    index, index_ts, _ = get_build_index(subdir, list(bldpkgs_dirs)[0], output_folder=output_folder,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/index.py", line 167, in get_build_index
    update_index(output_folder, verbose=debug)
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/index.py", line 264, in update_index
    return ChannelIndex(dir_path, channel_name, subdirs=subdirs, threads=threads,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/index.py", line 841, in index
    current_repodata = _build_current_repodata(subdir, patched_repodata,
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/index.py", line 753, in _build_current_repodata
    r = _get_resolve_object(subdir, repodata=repodata)
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda_build/index.py", line 649, in _get_resolve_object
    sd._process_raw_repodata_str(json.dumps(repodata))
  File "$CONDA_PREFIX/lib/python3.8/site-packages/conda/core/subdir_data.py", line 541, in _process_raw_repodata_str
    elif self._key_mgr is None:
AttributeError: 'SubdirData' object has no attribute '_key_mgr'
```

### Steps to Reproduce

1. Install conda and conda-content-trust.
2. Enable artifact verification by setting `extra_safety_checks: true`.
3. Run `conda skeleton pypi pandas`.

## Expected Behavior

`conda skeleton` 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : base
    active env location : $CONDA_PREFIX
            shell level : 1
       user config file : $HOME/.condarc
 populated config files : $HOME/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.0=0
                          __linux=5.4.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : $CONDA_PREFIX  (writable)
      conda av data dir : $CONDA_PREFIX/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : $CONDA_PREFIX/pkgs
                          $HOME/.conda/pkgs
       envs directories : $CONDA_PREFIX/envs
                          $HOME/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Linux/5.4.0-70-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:100
             netrc file : $HOME/.netrc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> $HOME/.condarc <==
allow_softlinks: True
auto_update_conda: False
auto_activate_base: True
auto_stack: 0
notify_outdated_conda: True
changeps1: True
env_prompt: (conda:{default_env}) 
create_default_packages: []
non_admin_enabled: True
pip_interop_enabled: False
aggressive_update_packages:
  - ca-certificates
  - certifi
  - openssl
safety_checks: enabled
extra_safety_checks: True
path_conflict: warn
pinned_packages: []
disallowed_packages: []
rollback_enabled: True
track_features: []
separate_format_cache: False
envs_dirs: []
pkgs_dirs: []
local_repodata_ttl: 1
ssl_verify: True
proxy_servers: {}
remote_connect_timeout_secs: 10.0
remote_read_timeout_secs: 60.0
remote_max_retries: 3
remote_backoff_factor: 1
add_anaconda_token: True
allow_non_channel_urls: False
channel_priority: flexible
channels:
  - defaults
custom_channels: {}
custom_multichannels: {}
migrated_channel_aliases: []
migrated_custom_channels: {}
override_channels_enabled: True
show_channel_urls: True
whitelist_channels: []
restore_free_channel: False
repodata_fns:
  - current_repodata.json
  - repodata.json
use_only_tar_bz2: False
always_softlink: False
always_copy: False
always_yes: False
json: False
offline: False
quiet: False
report_errors: False
shortcuts: False
verbosity: 0
force_reinstall: False
unsatisfiable_hints: True
unsatisfiable_hints_check_depth: 3
anaconda_upload: False
conda_build:
  filename_hashing: True
  quiet: False
  no_verify: False
  skip_existing: False
  set_build_id: True
  include_recipe: True
  activate: True
  long_test_prefix: True
  error_overlinking: True
  error_overdepending: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at $CONDA_PREFIX:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
anaconda-client           1.7.2                    py38_0    defaults
astroid                   2.5              py38h06a4308_1    defaults
attrs                     20.3.0             pyhd3eb1b0_0    defaults
auxlib                    0.0.43                   pypi_0    pypi
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.3              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.9.3              pyha847dfd_0    defaults
blas                      1.0                         mkl    defaults
brotlipy                  0.7.0           py38h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2021.1.19            h06a4308_1    defaults
certifi                   2020.12.5        py38h06a4308_0    defaults
cffi                      1.14.5           py38h261ae71_0    defaults
chardet                   4.0.0           py38h06a4308_1003    defaults
click                     7.1.2              pyhd3eb1b0_0    defaults
clyent                    1.2.2                    py38_1    defaults
conda                     4.10.1           py38h06a4308_0    conda-canary
conda-build               3.21.4           py38h06a4308_0    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-package-handling    1.7.2            py38h03888b9_0    defaults
conda-verify              3.4.2                      py_1    defaults
cryptography              3.4.7            py38hd23ed53_0    defaults
filelock                  3.0.12             pyhd3eb1b0_1    defaults
future                    0.18.2                   py38_1    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
importlib-metadata        3.10.0           py38h06a4308_0    defaults
importlib_metadata        3.10.0               hd3eb1b0_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2020.2                      254    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
isort                     5.8.0              pyhd3eb1b0_0    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
joblib                    1.0.1              pyhd3eb1b0_0    defaults
jsonschema                3.2.0                      py_2    defaults
jupyter_core              4.7.1            py38h06a4308_0    defaults
lazy-object-proxy         1.6.0            py38h27cfd23_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libarchive                3.4.2                h62408e4_0    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblief                   0.10.1               he6710b0_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libxml2                   2.9.10               hb55368b_3    defaults
lz4-c                     1.9.3                h2531618_0    defaults
markupsafe                1.1.1            py38h7b6447c_0    defaults
mccabe                    0.6.1                    py38_1    defaults
mkl                       2020.2                      256    defaults
mkl-service               2.3.0            py38he904b0f_0    defaults
mkl_fft                   1.3.0            py38h54f3939_0    defaults
mkl_random                1.1.1            py38h0573a6f_0    defaults
more-itertools            8.7.0              pyhd3eb1b0_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
numpy                     1.19.2           py38h54aff64_0    defaults
numpy-base                1.19.2           py38hfa32c7d_0    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
packaging                 20.9               pyhd3eb1b0_0    defaults
patchelf                  0.12                 h2531618_1    defaults
pip                       21.0.1           py38h06a4308_0    defaults
pkginfo                   1.7.0            py38h06a4308_0    defaults
pluggy                    0.13.1           py38h06a4308_0    defaults
psutil                    5.8.0            py38h27cfd23_1    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
py-lief                   0.10.1           py38h403a769_0    defaults
pycosat                   0.6.3            py38h7b6447c_1    defaults
pycparser                 2.20                       py_2    defaults
pylint                    2.7.2            py38h06a4308_1    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyrsistent                0.17.3           py38h7b6447c_0    defaults
pysocks                   1.7.1            py38h06a4308_0    defaults
pytest                    6.2.2            py38h06a4308_2    defaults
python                    3.8.5                h7579374_1    defaults
python-dateutil           2.8.1              pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pyyaml                    5.4.1            py38h27cfd23_1    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ripgrep                   12.1.1                        0    defaults
ruamel_yaml               0.15.100         py38h27cfd23_0    defaults
scikit-learn              0.24.1           py38ha9443f7_0    defaults
scipy                     1.6.2            py38h91f5cce_0    defaults
setuptools                52.0.0           py38h06a4308_0    defaults
six                       1.15.0           py38h06a4308_0    defaults
soupsieve                 2.2.1              pyhd3eb1b0_0    defaults
sqlite                    3.35.4               hdfb4753_0    defaults
threadpoolctl             2.1.0              pyh5ca1d4c_0    defaults
tk                        8.6.10               hbc83047_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tqdm                      4.59.0             pyhd3eb1b0_1    defaults
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
urllib3                   1.26.4             pyhd3eb1b0_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
wrapt                     1.12.1           py38h7b6447c_1    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zipp                      3.4.1              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.4.9                haebb681_0    defaults
```
</p></details>

**Comment by jezdez** [comment]
Fixed in #10677.
