### ISSUE TITLE
FIX: KeyError when updating with mamba if you have token enabled

### ISSUE THREAD

**Issue by asterbini** [conda/conda#10616]
## Current Behavior

I have tried mamba as my package manager but I always got a KeyError at line 255 of utils.py because function split_anaconda_token imported from conda/commons/url.py was'nt working on some urls.
The culprit are some urls that contains the underscore '_' char, which is not recognized by the RE in split_anaconda_token.

Fix: edit the RE inside split_anaconda_token (line 271) and add '_' to the set of captured chars.

### Steps to Reproduce

```
mamba update --all

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 897, in exception_converter
        raise e
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 891, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 850, in _wrapped_main
        result = do_call(args, p)
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 737, in do_call
        exit_code = update(args, parser)
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 655, in update
        return install(args, parser, "update")
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/mamba.py", line 601, in install
        conda_transaction = to_txn(
      File "/opt/miniconda3/lib/python3.9/site-packages/mamba/utils.py", line 256, in to_txn
        sdir = lookup_dict[split_anaconda_token(remove_auth(c))[0]]
    KeyError: 'https://conda.anaconda.org_-8a403b2e-.../conda-forge/linux-64'
... (rest of the log snipped)
```

## Expected Behavior

No exceptions expected

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/andrea/.condarc
 populated config files : /home/andrea/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.9.2.final.0
       virtual packages : __linux=5.11.12=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/pytorch/linux-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/spacy/linux-64
                          https://conda.anaconda.org/spacy/noarch
                          https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/andrea/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/andrea/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.9.2 Linux/5.11.12-100.fc32.x86_64 fedora/32 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/andrea/.condarc <==
auto_activate_base: False
ssl_verify: True
channels:
  - conda-forge
  - pytorch
  - spacy
  - anaconda

```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2020.12.5            ha878542_0    conda-forge
certifi                   2020.12.5        py39hf3d152e_1    conda-forge
cffi                      1.14.5           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
conda                     4.10.0           py39hf3d152e_1    conda-forge
conda-package-handling    1.7.3            py39h3811e60_0    conda-forge
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
decorator                 5.0.7              pyhd8ed1ab_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
ipython                   7.22.0           py39hef51801_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.0           py39hf3d152e_2    conda-forge
krb5                      1.17.2               h926e7f8_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
libarchive                3.5.1                h3f442fb_1    conda-forge
libcurl                   7.76.0               hc4aaa36_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libsolv                   0.7.18               h780b84a_0    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libxml2                   2.9.10               h72842e0_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.9.2            py39h951de11_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
parso                     0.8.2              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pycosat                   0.6.3           py39h3811e60_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.2           hffdb5ce_0_cpython    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.0                  he28a2e2_2    conda-forge
reproc                    14.2.1               h36c2ea0_0    conda-forge
reproc-cpp                14.2.1               h58526e2_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py39h3811e60_1004    conda-forge
setuptools                49.6.0           py39hf3d152e_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.4               h74cdb3f_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
tqdm                      4.60.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```

</p></details>

**Comment by wolfv** [comment]
Hi, please note that you've posted the URL here in cleartext, and it looks like it contains a token?

Did you configure the usage of a token?

I am unsure why this is a problem. Usually the URL should look like `https://conda.anaconda.org/t/<MYTOKEN>/conda-forge/linux-64/...`

**Comment by asterbini** [comment]
No, I did'nt. 
Actually the error url shown (https://conda.anaconda.org_-8a403b2e-de8c-46c3-b3a6-9e4617ea1d61/conda-forge/linux-64) is the wrong output of the split_anaconda_token function, that stops collecting the token at the first '_'.

**Comment by asterbini** [comment]
I've added a slightly more general fix
https://github.com/conda/conda/pull/10771
