### ISSUE TITLE
conda 4.10 : conda info not working when using a user .condarc with default_channels: {}

### ISSUE THREAD

**Issue by Nathanlauga** [conda/conda#10626]
## Current Behavior

After the update to conda 4.10 (both 4.10.0 and 4.10.1) I get an error when using `conda info` **it happens when I use a `.condarc` in my HOME directory with this following line** :

```
default_channels: {}
```

We use this line in our company so that it do not look for the default conda channels since we do not have any access to them.

### Steps to Reproduce

```
conda install conda=4.10
# add "default_channels: {}" into the .condarc
conda info
```

## Expected Behavior

It shows conda information.

## Error on `conda info`

<summary><code>`conda info`</code></summary><p>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/appli/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/appli/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/appli/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/appli/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 320, in execute
        info_dict = get_info_dict(args.system)
      File "/appli/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 164, in get_info_dict
        av_metadata_url_base=context.signing_metadata_url_base,
      File "/appli/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 606, in signing_metadata_url_base
        return self.default_channels[0].base_url
    IndexError: tuple index out of range

`$ /appli/anaconda3/bin/conda info`

```
</p>

## Environment Information 

<details open><summary><code>`conda config --show-sources`</code></summary><p>

**This is from my company computer so we use a private artifactory (I changed the channels url).**
```

==> /appli/anaconda3/.condarc <==
auto_activate_base: False
envs_dirs:
  - /appli/.conda/envs
  - /appli/anaconda3/envs
pkgs_dirs:
  - /appli/anaconda3/pkgs
  - /appli/.conda/pkgs
ssl_verify: False
channel_alias: https://artifactory.company/conda/
channels:
  - https://artifactory.company/conda/main/
  - https://artifactory.company/conda-forge/
  - https://artifactory.company/conda/r/

==> /home/LAUGA/.condarc <==
ssl_verify: False
channel_priority: strict
channels:
  - https://artifactory.company/conda-forge/
  - https://artifactory.company/conda/main/
custom_channels: {}
custom_multichannels: {}
default_channels: []
override_channels_enabled: True

==> envvars <==
root_dir: /appli/anaconda3

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /appli/anaconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    main
brotlipy                  0.7.0           py37h27cfd23_1003    main
ca-certificates           2021.1.19            h06a4308_0    main
certifi                   2020.12.5        py37h06a4308_0    main
cffi                      1.14.5           py37h261ae71_0    main
chardet                   4.0.0           py37h06a4308_1003    main
conda                     4.10.1           py37h89c1867_0    https://artifactory.company/conda-forge
conda-package-handling    1.7.2            py37h03888b9_0    main
cryptography              3.3.1            py37h3c74f83_1    main
idna                      2.10               pyhd3eb1b0_0    main
ld_impl_linux-64          2.33.1               h53a641e_7    main
libedit                   3.1.20191231         h14c3975_1    main
libffi                    3.3                  he6710b0_2    main
libgcc-ng                 9.1.0                hdf63c60_0    main
libstdcxx-ng              9.1.0                hdf63c60_0    main
ncurses                   6.2                  he6710b0_1    main
openssl                   1.1.1j               h27cfd23_0    main
pip                       21.0.1           py37h06a4308_0    main
pycosat                   0.6.3            py37h27cfd23_0    main
pycparser                 2.20                       py_2    main
pyopenssl                 20.0.1             pyhd3eb1b0_1    main
pysocks                   1.7.1                    py37_1    main
python                    3.7.10               hdb3f193_0    main
python_abi                3.7                     1_cp37m    https://artifactory.company/conda-forge
readline                  8.1                  h27cfd23_0    main
requests                  2.25.1             pyhd3eb1b0_0    main
ruamel_yaml               0.15.87          py37h7b6447c_1    main
setuptools                52.0.0           py37h06a4308_0    main
six                       1.15.0           py37h06a4308_0    main
sqlite                    3.33.0               h62c20be_0    main
tk                        8.6.10               hbc83047_0    main
tqdm                      4.56.0             pyhd3eb1b0_0    main
urllib3                   1.26.3             pyhd3eb1b0_0    main
wheel                     0.36.2             pyhd3eb1b0_0    main
xz                        5.2.5                h7b6447c_0    main
yaml                      0.2.5                h7b6447c_0    main
zlib                      1.2.11               h7b6447c_3    main

```
</p></details>

**Comment by johnhany97** [comment]
+1 - I just hit the exact issue which I believe is related to https://github.com/conda/conda/commit/6de43ad6b185c987e2db0c009f72ee5c418adbc3
