### ISSUE TITLE
Conda Navigator Not Launching

### ISSUE THREAD

**Issue by debasissil-python** [conda/conda#10647]
I tried everything I could to launch Conda Navigator but failed. What to do now ?

I'm using Microsoft Windows [Version 10.0.19042.928]

**Step 1- Activated root**

C:\Users\LENOVO>activate root

(base) C:\Users\LENOVO>conda update -n root conda
Collecting package metadata (current_repodata.json): done
Solving environment: |
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults/noarch::sphinx-3.1.2-py_0, defaults/win-64::docutils-0.17-py38haa95532_1
  - defaults/noarch::sphinx-3.5.4-pyhd3eb1b0_0, defaults/win-64::docutils-0.16-py38done

# All requested packages already installed.

**Step 2 - conda update -all**

(base) C:\Users\LENOVO>conda update --all
Collecting package metadata (current_repodata.json): done
Solving environment: \
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults/noarch::sphinx-3.1.2-py_0, defaults/win-64::docutils-0.17-py38haa95532_1
  - defaults/noarch::sphinx-3.5.4-pyhd3eb1b0_0, defaults/win-64::docutils-0.16-py38done

## Package Plan ##

  environment location: C:\Users\LENOVO\anaconda3

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautifulsoup4-4.9.3       |     pyha847dfd_0          86 KB
    conda-build-3.21.4         |   py38haa95532_0         552 KB
    ------------------------------------------------------------
                                           Total:         637 KB

The following packages will be UPDATED:

  beautifulsoup4     anaconda/win-64::beautifulsoup4-4.9.1~ --> pkgs/main/noarch::beautifulsoup4-4.9.3-pyha847dfd_0
  conda-build                                3.18.11-py38_1 --> 3.21.4-py38haa95532_0
  python                                   3.8.3-he1778fa_2 --> 3.8.8-hdbf39b2_5

Proceed ([y]/n)? y

Downloading and Extracting Packages
conda-build-3.21.4   | 552 KB    | ############################################################################ | 100%
beautifulsoup4-4.9.3 | 86 KB     | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

**Step 3 - tried launching anaconda navigator**

(base) C:\Users\LENOVO>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 103, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 34, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 34, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 30, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 19, in <module>
    import binstar_client
ModuleNotFoundError: No module named 'binstar_client'

**Step 4 - tried installing anaconda - client**

(base) C:\Users\LENOVO>conda install anaconda-client
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

**Step 5 - Tried relaunching but failed**
Again I tried to launch anaconda navigator (same output) - 

(base) C:\Users\LENOVO>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\LENOVO\anaconda3\Scripts\anaconda-navigator-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\app\main.py", line 103, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 34, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 34, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 30, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "C:\Users\LENOVO\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 19, in <module>
    import binstar_client
ModuleNotFoundError: No module named 'binstar_client'

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda Navigator issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager.
