### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/miniconda3/lib/libffi.la'

### ISSUE THREAD

**Issue by xRhuxy** [conda/conda#10651]
Hello,

I wanted to use numba for my python code, so had to install conda.
To do this I followed [these instructions](https://www.anegron.site/2020/06/18/how-to-install-conda-and-docker-on-your-raspberry-pi/).

After a restart i tried
`$ conda install numba`
to install numba, wich led to this message:
```Fetching package metadata: ......
Error: No packages found in current linux-armv7l channels matching: numba

You can search for this package on anaconda.org with

    anaconda search -t conda numba

You may need to install the anaconda-client command line client with

    conda install anaconda-client
```

When I tried to install the anaconda client the following happened:
```
$ conda install anaconda-client
Fetching package metadata: ......
Solving package specifications: ...........
Package plan for installation in environment /home/pi/miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    decorator-4.3.0            |             py_0           9 KB
    ipython_genutils-0.2.0     |             py_1          21 KB
    jsonschema-2.6.0           |           py36_2          62 KB
    pytz-2018.5                |             py_0         193 KB
    pyyaml-3.13                |   py36hdff2a78_1         422 KB
    clyent-1.2.2               |             py_1           9 KB
    python-dateutil-2.6.1      |             py_0         190 KB
    traitlets-4.3.2            |           py36_0         131 KB
    jupyter_core-4.4.0         |     pyhc2c3be9_0          41 KB
    nbformat-4.4.0             |             py_1          94 KB
    anaconda-client-1.7.1      |             py_0          61 KB
    ------------------------------------------------------------
                                           Total:         1.2 MB

The following NEW packages will be INSTALLED:

    anaconda-client:  1.7.1-py_0            
    asn1crypto:       0.24.0-py36_3         
    certifi:          2018.8.24-py36_1      
    cffi:             1.11.5-py36h822fc13_1 
    chardet:          3.0.4-py36_3          
    clyent:           1.2.2-py_1            
    conda:            4.5.11-py36_0         
    cryptography:     2.3.1-py36h696e4aa_0  
    decorator:        4.3.0-py_0            
    idna:             2.7-py36_2            
    ipython_genutils: 0.2.0-py_1            
    jsonschema:       2.6.0-py36_2          
    jupyter_core:     4.4.0-pyhc2c3be9_0    
    libffi:           3.2.1-h4f752ac_4      
    nbformat:         4.4.0-py_1            
    ncurses:          6.1-h4f752ac_1        
    openssl:          1.0.2r-hdff2a78_0     
    pip:              18.0-py36_1           
    pycosat:          0.6.3-py36hdff2a78_1  
    pycparser:        2.18-py_1             
    pyopenssl:        18.0.0-py36_0         
    pysocks:          1.6.8-py36_2          
    python:           3.6.6-hd0568c0_1      
    python-dateutil:  2.6.1-py_0            
    pytz:             2018.5-py_0           
    readline:         7.0-hcb560eb_1        
    requests:         2.19.1-py36_1         
    ruamel_yaml:      0.15.63-py36hdff2a78_0
    setuptools:       40.2.0-py36_0         
    six:              1.11.0-py36_1         
    sqlite:           3.24.0-hfcb1bcf_1     
    tk:               8.6.8-h849d6a0_0      
    traitlets:        4.3.2-py36_0          
    urllib3:          1.23-py36_1           
    wheel:            0.31.1-py36_1         
    xz:               5.2.4-hdff2a78_1      
    yaml:             0.1.7-hdff2a78_1      
    zlib:             1.2.11-hdff2a78_1003  

The following packages will be UPDATED:

    pyyaml:           3.11-py34_1 --> 3.13-py36hdff2a78_1   

Proceed ([y]/n)? y

Fetching packages ...
Extracting packages ...
[      COMPLETE      ]|######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|######################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 415, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/install.py", line 617, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/install.py", line 261, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/pi/miniconda3/lib/libffi.la'
```

Is there a way to fix this issue?

**Comment by jezdez** [comment]
1) This isn't an issue in Conda the package manager, but in the numba package not being available on linux-armv7l.
Please open a ticket in their issue tracker. Thank you!
2) The list of package to install seem to be pretty outdated, which would imply an old version of miniconda3. Please use a newer one.

I'm going to close this ticket since this seems to be solvable with updating and working with the numba folks. Thank you for your understanding!
