### ISSUE TITLE
issues with conda's pip in py27 environments on OS X

### ISSUE THREAD

**Issue by cel4** [conda/conda#1066]
```
PY=2.7
ENV=tmpenv
yes | conda create -n ${ENV} python=${PY}
source activate ${ENV}
yes | conda install pip
pip list
yes | conda remove -n ${ENV} --all
```

The pip binary seems to be broken on py27. It works on py33.

`pip list` prints following error:

```
Traceback (most recent call last):
  File "/Users/ch/miniconda/envs/testtmp27/bin/pip", line 4, in <module>
    from pip import main
  File "/Users/ch/miniconda/envs/testtmp27/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
ImportError: No module named utils
```

**Comment by cel4** [comment]
seems to be fixed now.
