### ISSUE TITLE
Aborting execution with Ctrl-C leaves PATH in *dangerous* state

### ISSUE THREAD

**Issue by memeplex** [conda/conda#10676]
## Current Behavior

Suppose I'm in an environment Test and run `conda uninstall something` then abort the execution of that command with Ctrl-C and look where is python, I get:

```
which python
=> /usr/local/Caskroom/miniconda/base/bin/python
```

and PATH is

```
echo $PATH
=> /usr/local/Caskroom/miniconda/base/bin:/Users/carlos/Base/Environments/Test/bin:...
```

Before aborting `/Users/carlos/Base/Environments/Test/bin` was at the beginning of the PATH, as expected. Also in my environment:

```
echo $CONDA_DEFAULT_ENV
=> /Users/carlos/Base/Environments/Test/
```

and the Test environment is shown in my bash prompt.

So this leaves the environment in a dangerous state where I will be running the wrong python version or, worse, the wrong pip and inadvertently cluttering my base environment with unneeded dependencies that, moreover, are not being installed in the intended environment.

I've been bitten by this many times, it was only later that I realized what was happening and was able to track down the problem to conda process interruption.

### Steps to Reproduce

```
conda create -n Test
conda activate Test
echo $PATH   # Test/bin is at the beginning
conda install ipython
conda uninstall ipython # And after a couple of seconds repeatedly press Ctrl-c 
echo $PATH # miniconda/base/bin is at the beginning
```

I was able to more reliably reproduce the issue while running `uninstall` but I'm unsure here. While interrupting you will see something like this:

```
Collecting package metadata (repodata.json): \ / failed

CondaError: KeyboardInterrupt

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

## Expected Behavior

By all means, avoid this dangerous behavior that silently changes the python installation being used. It's a serious bug.

If the environment is somehow corrupted, it will be ok if this is detected and notified, the main concern here is how this silently proceeds to run in a different environment than the one that is reportedly active, not the inability to non-destructively interrupt an ongoing operation, supposing that is the case.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : Test
    active env location : /Users/carlos/Base/Environments/Test
            shell level : 1
       user config file : /Users/carlos/.condarc
 populated config files : /Users/carlos/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/Caskroom/miniconda/base  (writable)
      conda av data dir : /usr/local/Caskroom/miniconda/base/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/Caskroom/miniconda/base/pkgs
                          /Users/carlos/.conda/pkgs
       envs directories : /Users/carlos/Base/Environments
                          /usr/local/Caskroom/miniconda/base/envs
                          /Users/carlos/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.5 Darwin/20.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/carlos/.condarc <==
changeps1: False
create_default_packages:
  - pip
envs_dirs:
  - ~/Base/Environments
channels:
  - defaults
  - conda-forge


```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/carlos/Base/Environments/Test:
#
# Name                    Version                   Build  Channel
appnope                   0.1.2           py39hecd8cb5_1001    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
ca-certificates           2021.4.13            hecd8cb5_1    defaults
certifi                   2020.12.5        py39hecd8cb5_0    defaults
decorator                 5.0.9              pyhd3eb1b0_0    defaults
ipython                   7.23.1           py39h71a6800_0    conda-forge
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
jedi                      0.18.0           py39hecd8cb5_1    defaults
libcxx                    10.0.0                        1    defaults
libffi                    3.3                  hb1e8313_2    defaults
matplotlib-inline         0.1.2              pyhd8ed1ab_2    conda-forge
ncurses                   6.2                  h0a44026_1    defaults
openssl                   1.1.1k               h9ed2024_0    defaults
parso                     0.8.2              pyhd3eb1b0_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pip                       21.0.1           py39hecd8cb5_0    defaults
prompt-toolkit            3.0.17             pyh06a4308_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pygments                  2.8.1              pyhd3eb1b0_0    defaults
python                    3.9.4                h88f2d9e_0    defaults
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  h9ed2024_0    defaults
setuptools                52.0.0           py39hecd8cb5_0    defaults
sqlite                    3.35.4               hce871da_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
tzdata                    2020f                h52ac0ba_0    defaults
wcwidth                   0.2.5                      py_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults

```
</p></details>

**Comment by jezdez** [comment]
I think this is related to #10631 that uncovers some $PATH shadowing that is shown here.

@memeplex Can you clarify whether you're using bash in your shell?
