### ISSUE TITLE
[Errno 9]

### ISSUE THREAD

**Issue by SimmaRoyal** [conda/conda#10682]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\utils.py", line 26, in <module>
    from ._internal_utils import to_native_string
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\_internal_utils.py", line 11, in <module>
    from .compat import is_py2, builtin_str, str
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\compat.py", line 60, in <module>
    from http.cookies import Morsel
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 780, in get_code
  File "<frozen importlib._bootstrap_external>", line 833, in get_data
OSError: [Errno 9] Bad file descriptor

```
</p></details>

**Comment by jezdez** [comment]
Closing as invalid.
