### ISSUE TITLE
Conda run fails with Permission denied if environment is read-only.

### ISSUE THREAD

**Issue by mforbes** [conda/conda#10690]
## Current Behavior

Trying to execute `conda run` attempts to write to the directory where the environment is install, which leads to a failur with a `Permission denied` error when the environment is in a read-only location (i.e. installed on a computing cluster, etc. where users do not have access.)

### Steps to Reproduce

```bash
$ conda create -yn tst python
$ conda env list
...
tst                      /data/apps/conda/envs/tst
...
$ find /data/apps/conda/envs/tst -exec chmod a-w {} \;
# Or more simply, just create the environment as a different user.
$ conda run -n tst python
```

<details open><summary>Full output</summary>

```bash
$ conda run -n tst python 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data/apps/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/data/apps/conda/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/data/apps/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/data/apps/conda/lib/python3.9/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/data/apps/conda/lib/python3.9/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/data/apps/conda/lib/python3.9/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/data/apps/conda/lib/python3.9/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/data/apps/conda/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/data/apps/conda/envs/tst/.tmp8h7x2duc'

`$ /data/apps/conda/bin/conda run -n tst python`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/data/apps/conda/bin/conda
             CONDA_PREFIX=/data/apps/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/data/apps/conda/bin/python
               CONDA_ROOT=/data/apps/conda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 HGRCPATH=~/.hgrc:/data/apps/conda/lib/python3.9/site-
                          packages/mmf_setup/_data/hgrc.full
                     PATH=/data/apps/conda/bin:/data/apps/conda/bin:/data/apps/conda/condabin:/u
                          sr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/lo
                          cal/MacGPG2/bin:/opt/X11/bin:/Applications/Wireshark.app/Contents/MacO
                          S
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /data/apps/conda
            shell level : 1
       user config file : /Users/conda/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.9.5.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /data/apps/conda  (writable)
      conda av data dir : /data/apps/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/apps/conda/pkgs
                          /Users/conda/.conda/pkgs
       envs directories : /data/apps/conda/envs
                          /Users/conda/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 504:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true


```
</details>

## Expected Behavior

The environment should be activated, then the command `python` run without any attempts to write to the environment directory and hence no `Permission denied` error.  For example, the following works fine:

```bash
$ conda activate test
(tst) $ python
$ python
Python 3.9.5 (default, May 18 2021, 19:34:48) 
...
>>> 
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : tst
    active env location : /data/apps/conda/envs/tst
            shell level : 2
       user config file : /Users/conda/.condarc
 populated config files : 
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.9.5.final.0
       virtual packages : __osx=10.14.6=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /data/apps/conda  (writable)
      conda av data dir : /data/apps/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/apps/conda/pkgs
                          /Users/conda/.conda/pkgs
       envs directories : /data/apps/conda/envs
                          /Users/conda/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 504:20
             netrc file : None
           offline mode : False
```

Also occurs on Linux:

```
     active environment : tst
    active env location : /home/mforbes/.conda/envs/tst
            shell level : 1
       user config file : /home/mforbes/.condarc
 populated config files : /data/apps/conda/.condarc
                          /home/mforbes/.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.9.4.final.0
       virtual packages : __cuda=11.3=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /data/apps/conda  (read only)
      conda av data dir : /data/apps/conda/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /data/apps/conda/pkgs
                          /home/mforbes/.conda/pkgs
       envs directories : /home/mforbes/.conda/envs
                          /data/apps/conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.4 Linux/5.4.0-72-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

`conda config --show-sources`: No output.
<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /data/apps/conda/envs/tst:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.4.13            hecd8cb5_1    defaults
certifi                   2020.12.5        py39hecd8cb5_0    defaults
libcxx                    10.0.0                        1    defaults
libffi                    3.3                  hb1e8313_2    defaults
ncurses                   6.2                  h0a44026_1    defaults
openssl                   1.1.1k               h9ed2024_0    defaults
pip                       21.1.1           py39hecd8cb5_0    defaults
python                    3.9.5                h88f2d9e_3    defaults
readline                  8.1                  h9ed2024_0    defaults
setuptools                52.0.0           py39hecd8cb5_0    defaults
sqlite                    3.35.4               hce871da_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
tzdata                    2020f                h52ac0ba_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```

and on Linux

```
# packages in environment at /home/mforbes/.conda/envs/tst:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2021.4.13            h06a4308_1    defaults
certifi                   2020.12.5        py39h06a4308_0    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
pip                       21.1.1           py39h06a4308_0    defaults
python                    3.9.5                hdb3f193_3    defaults
readline                  8.1                  h27cfd23_0    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
sqlite                    3.35.4               hdfb4753_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tzdata                    2020f                h52ac0ba_0    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by marcinwrochna** [comment]
This bug makes `conda run` fail in installations like [The Littlest JupyterHub](https://tljh.jupyter.org/en/latest/#the-littlest-jupyterhub).

I suggest to fix this by not to specifying a `prefix=` argument to Utf8NamedTemporaryFile in [conda/utils.py](https://github.com/conda/conda/blame/master/conda/utils.py); just use the default (in both instances). Such a temp file is readable and writeable only by the creating user, so there's no problem with any details leaking if it's created in a different directory (a default directory like `/tmp`).

This prefix was introduced [here](https://github.com/conda/conda/commit/9903f00aa0a6e985a11d1602c30b4efde44b1452#diff-7371fc047067e7005d434418493bf0314c307d88daffd3b246b55c70e3d12375), I guess by accident, just because a variable `prefix` existed in context (the conda prefix path). It didn't quite make sense, and there was an attempt to fix it [here](https://github.com/conda/conda/commit/6226afbc5a38fce9d1b15aaf03fddbb55393bb7e#diff-7371fc047067e7005d434418493bf0314c307d88daffd3b246b55c70e3d12375), but it still doesn't quite make sense as it is now, because the `prefix=` argument is supposed to be a prefix for just the filename, not a directory nor a path (docs [here](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) and [here](https://docs.python.org/3/library/tempfile.html#tempfile.mkstemp)). There's a separate argument `dir=` for specifying the directory. A prefix like `prefix='.conda_'` would make sense, just to make the filename nicer, but I don't see any reason not to use the default temp directory.

**Comment by erykoff** [comment]
I filed what turns out is a dupe of this #11208 and made a PR to fix it #11215.

**Comment by hjoliver** [comment]
@kenodegard (I see you were the label-wrangler here) - the primary duplicate was actually #10098
