### ISSUE TITLE
Error: INVALID mime type, must not be empty or falsy

### ISSUE THREAD

**Issue by Jairo-cm** [conda/conda#10697]
Hi everyone, I am having this problem running a jupyter notebook in VSC insider.
Thank you for your support.
VSC Insider: Version 1.57
![Error_INVALID mime type](https://user-images.githubusercontent.com/65982976/119849358-2bab7a80-bed2-11eb-9968-ca5279aa9505.PNG)

Error: INVALID mime type, must not be empty or falsy
at new It (c:\Users\HP\AppData\Local\Programs\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:78:51933)
at D (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:29708)
at Object.k [as cellOutputToVSCCellOutput] (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:29266)
at w.addToCellData (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:90:329960)
at w.handleExecuteResult (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:90:330776)
at w.handleIOPub (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:90:328199)
at w.r.value (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:16:145862)
at c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:90:327179
at runMicrotasks (<anonymous>)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async t.KernelShellFutureHandler._handleIOPub (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:37:515409)
at async t.KernelShellFutureHandler.handleMsg (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:37:515073)
at async g._handleMessage (c:\Users\HP\.vscode-insiders\extensions\ms-toolsai.jupyter-2021.6.881596855\out\client\extension.js:52:853801)

**Comment by jezdez** [comment]
This is unrelated to the conda package manager, please file the issue in the appropriate location.
