### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by sabbir7** [conda/conda#10702]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Sabbir\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 322, in reload_client
    url = binstar_client.utils.get_config()['url']
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 249, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 241, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 221, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\config.py", line 205, in load_config
    data = yaml_load(fd)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 162, in safe_load
    return load(stream, SafeLoader)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\__init__.py", line 112, in load
    loader = Loader(stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Sabbir\.continuum\anaconda-client\config.yaml", position 0

**Comment by alihedayatnia** [comment]
I have the same problem and don't have any clue what should I do

**Comment by sabbir7** [comment]
I search a lot on the internet but no solution found. Then I uninstall my
latest version of Anaconda and install the previous version of the Anaconda
but still the same problem. At last, I reinstall my Windows 10 on my PC and
it solved the problem.
I think maybe some problems with the windows.

With best regards,

(Md. Sabbir Ejaz)
Lecturer, Department of Computer Science & Engineering (CSE)
Bangladesh Army University of Engineering & Technology (BAUET)
Qadirabad Cantonment, Natore - 6431, Bangladesh.
Mobile: +8801725990631

**Comment by jezdez** [comment]
This seems to be an issue in the anaconda-client configuration being used in the Anaconda Navigator. This repo is about the conda package manager.

Could you please open a ticket here? https://github.com/ContinuumIO/anaconda-issues/issues/new

Thank you!
