### ISSUE TITLE
Navigator Error: An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by MuhammadQaisarAli** [conda/conda#10722]
### Steps to Reproduce

```
Traceback (most recent call last):
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\binstar_client\__init__.py", line 244, in user
    res = self.session.get(url, verify=self.session.verify)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "C:\Users\Usr_name\anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "C:\Users\Usr_name\anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\Usr_name\anaconda3\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname


```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
      active environment : base
    active env location : C:\Users\Usr_name\anaconda3
            shell level : 1
       user config file : C:\Users\Usr_name\.condarc
 populated config files : C:\Users\Usr_name\.condarc
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=10.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\Usr_name\anaconda3  (writable)
      conda av data dir : C:\Users\Usr_name\anaconda3\etc\conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Usr_name\anaconda3\pkgs
                          C:\Users\Usr_name\.conda\pkgs
                          C:\Users\Usr_name\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Usr_name\anaconda3\envs
                          C:\Users\Usr_name\.conda\envs
                          C:\Users\Usr_name\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Usr_name\.condarc <==
extra_safety_checks: False
channels:
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\Usr_name\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
anaconda-client           1.7.2                    py38_0    defaults
anaconda-navigator        2.0.3                    py38_0    defaults
anyio                     2.2.0            py38haa95532_2    defaults
argon2-cffi               20.1.0           py38h2bbff1b_1    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.9.3              pyha847dfd_0    defaults
bleach                    3.3.0              pyhd3eb1b0_0    defaults
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2021.5.25            haa95532_1    defaults
certifi                   2021.5.30        py38haa95532_0    defaults
cffi                      1.14.5           py38hcd4344a_0    defaults
chardet                   4.0.0           py38haa95532_1003    defaults
click                     8.0.1              pyhd3eb1b0_0    defaults
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.10.1           py38haa95532_1    defaults
conda-build               3.21.4           py38haa95532_0    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.7.3            py38h8cc25b3_1    defaults
conda-repo-cli            1.0.4              pyhd3eb1b0_0    defaults
conda-token               0.3.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              3.4.7            py38h71e12ea_0    defaults
decorator                 5.0.9              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.3                      py38_0    defaults
filelock                  3.0.12             pyhd3eb1b0_1    defaults
freetype                  2.10.4               hd328e21_0    defaults
future                    0.18.2                   py38_1    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
importlib-metadata        3.10.0           py38haa95532_0    defaults
importlib_metadata        3.10.0               hd3eb1b0_0    defaults
ipykernel                 5.3.4            py38h5ca1d4c_0    defaults
ipython                   7.22.0           py38hd4e2768_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.3              pyhd3eb1b0_1    defaults
jedi                      0.17.0                   py38_0    defaults
jinja2                    3.0.0              pyhd3eb1b0_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.9.5                      py_0    defaults
jsonschema                3.2.0                      py_2    defaults
jupyter-packaging         0.7.12             pyhd3eb1b0_0    defaults
jupyter_client            6.1.12             pyhd3eb1b0_0    defaults
jupyter_core              4.7.1            py38haa95532_0    defaults
jupyter_server            1.4.1            py38haa95532_0    defaults
jupyterlab                3.0.14             pyhd3eb1b0_1    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.4.0              pyhd3eb1b0_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
libarchive                3.4.2                h5e25573_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.10.1               ha925a31_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libtiff                   4.2.0                hd0e1b90_0    defaults
libxml2                   2.9.10               hb89e7f3_3    defaults
lz4-c                     1.9.3                h2bbff1b_0    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                2.0.1            py38h2bbff1b_0    defaults
menuinst                  1.4.16           py38he774522_1    defaults
mistune                   0.8.4           py38he774522_1000    defaults
msys2-conda-epoch         20160418                      1    defaults
navigator-updater         0.2.1                    py38_0    defaults
nbclassic                 0.2.6              pyhd3eb1b0_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.0.7                    py38_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
notebook                  6.4.0            py38haa95532_0    defaults
olefile                   0.46                       py_0    defaults
openssl                   1.1.1k               h2bbff1b_0    defaults
packaging                 20.9               pyhd3eb1b0_0    defaults
pandoc                    2.12                 haa95532_0    defaults
pandocfilters             1.4.3            py38haa95532_1    defaults
parso                     0.8.2              pyhd3eb1b0_0    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.2.0            py38h4fa10fc_0    defaults
pip                       21.1.2           py38haa95532_0    defaults
pkginfo                   1.7.0            py38haa95532_0    defaults
powershell_shortcut       0.0.1                         3    defaults
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.17             pyh06a4308_0    defaults
psutil                    5.8.0            py38h2bbff1b_1    defaults
py-lief                   0.10.1           py38ha925a31_0    defaults
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.20                       py_2    defaults
pygments                  2.9.0              pyhd3eb1b0_0    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py38ha925a31_4    defaults
pyrsistent                0.17.3           py38he774522_0    defaults
pysocks                   1.7.1            py38haa95532_0    defaults
python                    3.8.8                hdbf39b2_5    defaults
python-dateutil           2.8.1              pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
pytz                      2021.1             pyhd3eb1b0_0    defaults
pywin32                   227              py38he774522_1    defaults
pywinpty                  0.5.7                    py38_0    defaults
pyyaml                    5.4.1            py38h2bbff1b_1    defaults
pyzmq                     20.0.0           py38hd77b12b_1    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py38h2bbff1b_0    defaults
send2trash                1.5.0              pyhd3eb1b0_1    defaults
setuptools                52.0.0           py38haa95532_0    defaults
sip                       4.19.13          py38ha925a31_0    defaults
six                       1.15.0           py38haa95532_0    defaults
sniffio                   1.2.0            py38haa95532_1    defaults
soupsieve                 2.2.1              pyhd3eb1b0_0    defaults
sqlite                    3.35.4               h2bbff1b_0    defaults
terminado                 0.9.4            py38haa95532_0    defaults
testpath                  0.4.4              pyhd3eb1b0_0    defaults
tk                        8.6.10               he774522_0    defaults
tornado                   6.1              py38h2bbff1b_0    defaults
tqdm                      4.59.0             pyhd3eb1b0_1    defaults
traitlets                 5.0.5              pyhd3eb1b0_0    defaults
urllib3                   1.26.4             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5                      py_0    defaults
webencodings              0.5.1                    py38_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
wincertstore              0.2                      py38_0    defaults
winpty                    0.4.3                         4    defaults
xmltodict                 0.12.0                     py_0    defaults
xz                        5.2.5                h62dcd97_0    defaults
yaml                      0.2.5                he774522_0    defaults
zeromq                    4.3.3                ha925a31_3    defaults
zipp                      3.4.1              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
zstd                      1.4.9                h19a0ad4_0    defaults

```
</p></details>

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
