### ISSUE TITLE
Installing GEOPANDAS issue

### ISSUE THREAD

**Issue by bostonoem** [conda/conda#10758]
Hello, I am trying to install geopandas within my QGIS environment so that I can run it within my Jupyter Notebook. I have installed geopandas using pip install geopandas but I get the error ModuleNot FoundError: No Module named 'processing' when trying to import it. So, i've been trying to install geopandas using the preferred conda method but I get this odd error message below when I run the script to install. 

Thanks,
Daniel

```
C:\>conda install --channel conda-forge geopandas
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 2.1.5
         python version : 3.7.0.final.0
       requests version : 2.23.0
       root environment : C:\OSGEO4~1\apps\Python37  (writable)
    default environment : C:\OSGEO4~1\apps\Python37
       envs directories : C:\OSGEO4~1\apps\Python37\envs
          package cache : C:\OSGEO4~1\apps\Python37\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\153797\.condarc
           offline mode : False



`$ C:\OSGEO4~1\apps\Python37\Scripts\conda install --channel conda-forge geopandas`




    Traceback (most recent call last):
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\cli\install.py", line 308, in install
        update_deps=context.update_dependencies)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\plan.py", line 484, in install_actions
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 871, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 908, in solve
        dists, new_specs = self.get_dists(specs)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 509, in get_dists
        if not full_prune(specs, optional, features):
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 488, in full_prune
        self.touch(spec, touched, filter)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 317, in touch
        return t_ms_(spec) if isinstance(spec, MatchSpec) else t_fkey_(spec)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 307, in t_fkey_
        val = touched[fkey] = self.valid(fkey, filter)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 285, in valid
        return v_(spec)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 273, in v_
        return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fkey_(spec)
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 282, in v_fkey_
        val = filter[fkey] = all(v_ms_(ms) for ms in self.ms_depends(fkey))
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 558, in ms_depends
        deps = [MatchSpec(d) for d in rec.get('depends', [])]
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 558, in <listcomp>
        deps = [MatchSpec(d) for d in rec.get('depends', [])]
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\resolve.py", line 64, in __new__
        vspec = VersionSpec(parts[1])
      File "C:\OSGEO4~1\apps\Python37\lib\site-packages\conda\version.py", line 330, in __new__
        raise CondaRuntimeError('Invalid version spec: %s' % spec)
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid version spec: =20190808
```

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
