### ISSUE TITLE
When opened anaconda does not launch the spyder application

### ISSUE THREAD

**Issue by zkubin** [conda/conda#10753]
## Current Behavior

I have tried launching spyder from anaconda but nothing happens. No screen appears, yet when I close conda it tells me spyder is running.  I will reproduce the code below. 

### Steps to Reproduce

```
conda run spyder is done on anaconda prompt and the results I get are:
ERROR conda.cli.mainrun:execute(32): Subprocess for 'conda run [u'spyder']' command failed. (See above for error) Traceback (most recent call last): File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\init.py", line 204, in <module> from PySide import __version_ as PYSIDE_VERSION # analysis:ignore ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "C:\ProgramData\Anaconda3\Scripts\spyder-script.py", line 10, in <module> sys.exit(main()) File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\start.py", line 210, in main from spyder.app import mainwindow File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 45, in <module> requirements.checkqt() File "C:\ProgramData\Anaconda3\lib\site-packages\spyder\requirements.py", line 41, in check_qt import qtpy File "C:\ProgramData\Anaconda3\lib\site-packages\qtpy\init_.py", line 210, in <module> raise PythonQtError('No Qt bindings could be found') qtpy.PythonQtError: No Qt bindings could be found
```

## Expected Behavior

the spyder window should open. From the conda launcher I can't open it and neither from the prompt page.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file main_info.py, line 318
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file main_info.py, line 319
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file main_config.py, line 119

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
[y/N]: y
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
Traceback (most recent call last):
  File "C:\Users\moond\Desktop\New folder\lib\site-packages\conda\gateways\logging.py", line 134, in emit
    stream.write(ufs % msg)
LookupError: unknown encoding: cp65001
Logged from file exceptions.py, line 1088
```
</p></details>

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
