### ISSUE TITLE
`conda list` throws unexpected error: "SyntaxError: unknown variable: python_implementation"

### ISSUE THREAD

**Issue by corneliusroemer** [conda/conda#10768]
## Current Behavior
`conda list` throws error `SyntaxError: unknown variable: python_implementation`

### Steps to Reproduce
```
❯ conda list                                                                                          (nextstrain) 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_list.py", line 140, in execute
        exitcode = print_packages(prefix, regex, format, piplist=args.pip,
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_list.py", line 79, in print_packages
        exitcode, output = list_packages(prefix, regex, format=format,
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 140, in iter_records
        return itervalues(self._prefix_records)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 169, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 79, in load
        self._load_site_packages()
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 284, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/gateways/disk/read.py", line 240, in read_python_record
        depends, constrains = pydist.get_conda_dependencies()
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 337, in get_conda_dependencies
        depends.update(
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 339, in <genexpr>
        if interpret(pyspec.marker, execution_context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1195, in interpret
        return evaluator.evaluate(expr, context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1110, in evaluate
        rhs = self.evaluate(erhs, context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1109, in evaluate
        lhs = self.evaluate(elhs, context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1097, in evaluate
        raise SyntaxError('unknown variable: %s' % expr)
      File "<string>", line None
    SyntaxError: unknown variable: python_implementation

`$ /Users/cornelius/opt/miniconda3/bin/conda list`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=nextstrain
             CONDA_PREFIX=/Users/cornelius/opt/miniconda3/envs/nextstrain
           CONDA_PREFIX_1=/Users/cornelius/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(nextstrain)
         CONDA_PYTHON_EXE=/Users/cornelius/opt/miniconda3/bin/python
               CONDA_ROOT=/Users/cornelius/opt/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/cornelius/opt/miniconda3/envs/nextstrain/bin:/Users/cornelius/o
                          pt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : nextstrain
    active env location : /Users/cornelius/opt/miniconda3/envs/nextstrain
            shell level : 2
       user config file : /Users/cornelius/.condarc
 populated config files : /Users/cornelius/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/cornelius/opt/miniconda3  (writable)
      conda av data dir : /Users/cornelius/opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cornelius/opt/miniconda3/pkgs
                          /Users/cornelius/.conda/pkgs
       envs directories : /Users/cornelius/opt/miniconda3/envs
                          /Users/cornelius/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.1 Darwin/20.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : nextstrain
    active env location : /Users/cornelius/opt/miniconda3/envs/nextstrain
            shell level : 2
       user config file : /Users/cornelius/.condarc
 populated config files : /Users/cornelius/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/cornelius/opt/miniconda3  (writable)
      conda av data dir : /Users/cornelius/opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cornelius/opt/miniconda3/pkgs
                          /Users/cornelius/.conda/pkgs
       envs directories : /Users/cornelius/opt/miniconda3/envs
                          /Users/cornelius/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.1 Darwin/20.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/cornelius/.condarc <==
report_errors: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
❯ conda list --show-channel-urls                                                                                                                                  (nextstrain) 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_list.py", line 140, in execute
        exitcode = print_packages(prefix, regex, format, piplist=args.pip,
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_list.py", line 79, in print_packages
        exitcode, output = list_packages(prefix, regex, format=format,
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 140, in iter_records
        return itervalues(self._prefix_records)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 169, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 79, in load
        self._load_site_packages()
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/core/prefix_data.py", line 284, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/gateways/disk/read.py", line 240, in read_python_record
        depends, constrains = pydist.get_conda_dependencies()
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 337, in get_conda_dependencies
        depends.update(
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 339, in <genexpr>
        if interpret(pyspec.marker, execution_context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1195, in interpret
        return evaluator.evaluate(expr, context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1110, in evaluate
        rhs = self.evaluate(erhs, context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1109, in evaluate
        lhs = self.evaluate(elhs, context)
      File "/Users/cornelius/opt/miniconda3/lib/python3.9/site-packages/conda/common/pkg_formats/python.py", line 1097, in evaluate
        raise SyntaxError('unknown variable: %s' % expr)
      File "<string>", line None
    SyntaxError: unknown variable: python_implementation

`$ /Users/cornelius/opt/miniconda3/bin/conda list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=nextstrain
             CONDA_PREFIX=/Users/cornelius/opt/miniconda3/envs/nextstrain
           CONDA_PREFIX_1=/Users/cornelius/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(nextstrain)
         CONDA_PYTHON_EXE=/Users/cornelius/opt/miniconda3/bin/python
               CONDA_ROOT=/Users/cornelius/opt/miniconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/cornelius/opt/miniconda3/envs/nextstrain/bin:/Users/cornelius/o
                          pt/miniconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : nextstrain
    active env location : /Users/cornelius/opt/miniconda3/envs/nextstrain
            shell level : 2
       user config file : /Users/cornelius/.condarc
 populated config files : /Users/cornelius/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/cornelius/opt/miniconda3  (writable)
      conda av data dir : /Users/cornelius/opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/cornelius/opt/miniconda3/pkgs
                          /Users/cornelius/.conda/pkgs
       envs directories : /Users/cornelius/opt/miniconda3/envs
                          /Users/cornelius/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.1 Darwin/20.5.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```
</p></details>

**Comment by cgguido** [comment]
Found a solution yet? same problem here. Ubuntu on WSL2:

conda version : 4.10.1
conda-build version : 3.21.4
python version : 3.8.8.final.0
virtual packages : __linux=4.14.214=0
                          __glibc=2.26=0
                          __unix=0=0
                          __archspec=1=x86_64
base environment : /home/ciancgx/anaconda3  (writable)
conda av data dir : /home/ciancgx/anaconda3/etc/conda
conda av metadata url : https://repo.anaconda.com/pkgs/main
channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                        https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
package cache : /home/ciancgx/anaconda3/pkgs
                         /home/ciancgx/.conda/pkgs
envs directories : /home/ciancgx/anaconda3/envs
                          /home/ciancgx/.conda/envs
platform : linux-64
user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Linux/4.14.214-160.339.amzn2.x86_64 amzn/2 glibc/2.26
UID:GID : 1002:1002
netrc file : None
offline mode : False

**Comment by jezdez** [comment]
As https://github.com/conda/conda/issues/10907 shows, this is most likely related to a package such as xopen that is using wrong marker in its metadata. Conda should be better at reporting which package it has an issue with here though.

**Comment by jezdez** [comment]
I've opened https://github.com/pycompression/xopen/issues/70 for the causing metadata error in xopen.

**Comment by jezdez** [comment]
@corneliusroemer To find which package is causing the problem for you, could you paste the output of running `pip list` please?

**Comment by nextgenusfs** [comment]
Any updates or work-arounds here? This is driving me crazy.  I export the packages in each environment via `conda list -n env --json` to be used in a small UI showing my users what is installed in which environment.

I have quite a few pip packages installed because the conda versions are either incompatible, not up to date, etc.  So this is quite common usage for me to use pip within an environment.
