### ISSUE TITLE
Conda installation fails on windows 10

### ISSUE THREAD

**Issue by adif33** [conda/conda#10776]
I am unable to install on windows 10. This is the log of the installer. Any ideas?

```
Output` folder: C:\Users\adif\miniconda3\Lib
Extract: _nsis.py
Extract: _system_path.py
Output folder: C:\Users\adif\miniconda3\conda-meta
Extract: history
Output folder: C:\Users\adif\miniconda3
Extract: _conda.exe
Output folder: C:\Users\adif\miniconda3
Output folder: C:\Users\adif\miniconda3\pkgs
Extract: env.txt
Extract: urls
Extract: urls.txt
Extract: post_install.bat
Extract: pre_uninstall.bat
Extract: .cio-config.py
Output folder: C:\Users\adif\miniconda3\pkgs\cache
Extract: 1120365f.json
Extract: 3e39a7aa.json
Extract: 4ea078d6.json
Extract: 59ba4880.json
Extract: 5ca77eed.json
Extract: 5fa16146.json
Extract: 920c960f.json
Extract: c4a505b4.json
Output folder: C:\Users\adif\miniconda3\pkgs
Output folder: C:\Users\adif\miniconda3\pkgs\brotlipy-0.7.0-py39h2bbff1b_1003\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\ca-certificates-2020.12.8-haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\certifi-2020.12.5-py39haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\cffi-1.14.4-py39hcd4344a_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\chardet-3.0.4-py39haa95532_1003\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\conda-4.9.2-py39haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\conda-package-handling-1.7.2-py39h8cc25b3_1\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\console_shortcut-0.1.1-4\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\cryptography-3.3.1-py39hcd4344a_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\idna-2.10-py_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\menuinst-1.4.16-py39h2bbff1b_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\openssl-1.1.1i-h2bbff1b_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\pip-20.3.1-py39haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\powershell_shortcut-0.0.1-3\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\pycosat-0.6.3-py39h2bbff1b_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\pycparser-2.20-py_2\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\pyopenssl-20.0.0-pyhd3eb1b0_1\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\pysocks-1.7.1-py39haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\python-3.9.1-h6244533_2\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\pywin32-228-py39he774522_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\requests-2.25.0-pyhd3eb1b0_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\ruamel_yaml-0.15.80-py39h2bbff1b_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\setuptools-51.0.0-py39haa95532_2\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\six-1.15.0-py39haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\sqlite-3.33.0-h2a8f88b_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\tqdm-4.54.1-pyhd3eb1b0_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\tzdata-2020d-h14c3975_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\urllib3-1.25.11-py_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\vc-14.2-h21ff451_1\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\vs2015_runtime-14.27.29016-h5e58377_2\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\wheel-0.36.1-pyhd3eb1b0_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\win_inet_pton-1.1.0-py39haa95532_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\wincertstore-0.2-py39h2bbff1b_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\yaml-0.2.5-he774522_0\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs\zlib-1.2.11-h62dcd97_4\info
Extract: repodata_record.json
Output folder: C:\Users\adif\miniconda3\pkgs
Extract: python-3.9.1-h6244533_2.conda
Extract: ca-certificates-2020.12.8-haa95532_0.conda
Extract: tzdata-2020d-h14c3975_0.conda
Extract: vs2015_runtime-14.27.29016-h5e58377_2.conda
Extract: vc-14.2-h21ff451_1.conda
Extract: openssl-1.1.1i-h2bbff1b_0.conda
Extract: yaml-0.2.5-he774522_0.conda
Extract: zlib-1.2.11-h62dcd97_4.conda
Extract: sqlite-3.33.0-h2a8f88b_0.conda
Extract: pywin32-228-py39he774522_0.conda
Extract: menuinst-1.4.16-py39h2bbff1b_0.conda
Extract: certifi-2020.12.5-py39haa95532_0.conda
Extract: chardet-3.0.4-py39haa95532_1003.conda
Extract: console_shortcut-0.1.1-4.conda
Extract: powershell_shortcut-0.0.1-3.conda
Extract: pycosat-0.6.3-py39h2bbff1b_0.conda
Extract: ruamel_yaml-0.15.80-py39h2bbff1b_0.conda
Extract: six-1.15.0-py39haa95532_0.conda
Extract: win_inet_pton-1.1.0-py39haa95532_0.conda
Extract: wincertstore-0.2-py39h2bbff1b_0.conda
Extract: pysocks-1.7.1-py39haa95532_0.conda
Extract: setuptools-51.0.0-py39haa95532_2.conda
Extract: idna-2.10-py_0.conda
Extract: pycparser-2.20-py_2.conda
Extract: cffi-1.14.4-py39hcd4344a_0.conda
Extract: brotlipy-0.7.0-py39h2bbff1b_1003.conda
Extract: cryptography-3.3.1-py39hcd4344a_0.conda
Extract: pyopenssl-20.0.0-pyhd3eb1b0_1.conda
Extract: requests-2.25.0-pyhd3eb1b0_0.conda
Extract: tqdm-4.54.1-pyhd3eb1b0_0.conda
Extract: conda-package-handling-1.7.2-py39h8cc25b3_1.conda
Extract: conda-4.9.2-py39haa95532_0.conda
Extract: urllib3-1.25.11-py_0.conda
Extract: wheel-0.36.1-pyhd3eb1b0_0.conda
Extract: pip-20.3.1-py39haa95532_0.conda
  | 27/35 [00:09<00:06,  1.17it/s]   
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "site-packages\conda\exceptions.py", line 1079, in __call__
  File "site-packages\conda\cli\main.py", line 84, in _main
  File "site-packages\conda\cli\conda_argparse.py", line 83, in do_call
  File "site-packages\conda\cli\main_install.py", line 20, in execute
  File "site-packages\conda\cli\install.py", line 111, in install
  File "site-packages\conda\common\configuration.py", line 1382, in validate_configuration
  File "site-packages\conda\common\configuration.py", line 1379, in <genexpr>
  File "site-packages\conda\common\configuration.py", line 1373, in _collect_validation_error
  File "site-packages\conda\common\configuration.py", line 1219, in __get__
  File "site-packages\conda\common\configuration.py", line 571, in typify
  File "site-packages\conda\common\configuration.py", line 586, in _typify_data_structure
  File "site-packages\conda\common\configuration.py", line 586, in <genexpr>
AttributeError: 'YamlRawParameter' object has no attribute 'typify'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\conda\exceptions.py", line 1211, in print_unexpected_error_report
  File "site-packages\conda\cli\main_info.py", line 238, in get_main_info_str
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "site-packages\conda\exceptions.py", line 1079, in __call__
      File "site-packages\conda\cli\main.py", line 84, in _main
      File "site-packages\conda\cli\conda_argparse.py", line 83, in do_call
      File "site-packages\conda\cli\main_install.py", line 20, in execute
      File "site-packages\conda\cli\install.py", line 111, in install
      File "site-packages\conda\common\configuration.py", line 1382, in validate_configuration
      File "site-packages\conda\common\configuration.py", line 1379, in <genexpr>
      File "site-packages\conda\common\configuration.py", line 1373, in _collect_validation_error
      File "site-packages\conda\common\configuration.py", line 1219, in __get__
      File "site-packages\conda\common\configuration.py", line 571, in typify
      File "site-packages\conda\common\configuration.py", line 586, in _typify_data_structure
      File "site-packages\conda\common\configuration.py", line 586, in <genexpr>
    AttributeError: 'YamlRawParameter' object has no attribute 'typify'

`$ C:\Users\adif\miniconda3\_conda.exe install --offline -yp C:\Users\adif\miniconda3 --file C:\Users\adif\miniconda3\pkgs\env.txt`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

Delete file: C:\Users\adif\miniconda3\pkgs\env.txt
Output folder: C:\Users\adif\miniconda3\conda-meta
Extract: history
Creating Miniconda3 menus...
Execute: "C:\Users\adif\miniconda3\pythonw.exe" -E -s "C:\Users\adif\miniconda3\Lib\_nsis.py" mkdirs
Running post install...
Execute: "C:\Users\adif\miniconda3\pythonw.exe" -E -s "C:\Users\adif\miniconda3\Lib\_nsis.py" post_install
Execute: "C:\Users\adif\miniconda3\pythonw.exe" -E -s "C:\Users\adif\miniconda3\pkgs\.cio-config.py" "C:\Users\adif\Downloads\Miniconda3-py39_4.9.2-Windows-x86_64 (2).exe"
Created uninstaller: C:\Users\adif\miniconda3\Uninstall-Miniconda3.exe
Completed
```

**Comment by chenghlee** [comment]
What version of Miniconda are you trying to install?

**Comment by adif33** [comment]
Miniconda3-py39_4.9.2-Windows-x86_64
Tried Miniconda3-latest-Windows-x86_64 as well
Thank you
