### ISSUE TITLE
ISSUE RELATED TO ENVIRONMENT.YML FILE 

### ISSUE THREAD

**Issue by vs1612** [conda/conda#10794]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

i have created environment .yml file in my laptop and i am trying to run this in raspberry pi 4, so i am getting following errors. i am not able to understand the error, could you please provide me some suggestion how to solve this issue.

Include the output of the command 'conda info' in your report.

```
Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/cli/main_create.py", line 77, in execute
    directory=os.getcwd())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/specs/__init__.py", line 18, in detect
    if spec.can_handle():
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/env.py", line 65, in from_file
    return from_yaml(fp.read(), filename=filename)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda_env/env.py", line 58, in from_yaml
    return Environment(**data)
TypeError: __init__() got an unexpected keyword argument 'prefix'
```

the same file is working fine locally

**Comment by jezdez** [comment]
I'm sorry but without more information as requested in the pull request template I can't help you really. Please fill in the requested information above.

**Comment by vs1612** [comment]
issue resolved, package was missing in the file
