### ISSUE TITLE
Navigator error

### ISSUE THREAD

**Issue by pappymu** [conda/conda#10818]
## Current Behavior
 Navigator refuses to start up.

('?: Undefined error ([GET] https://api.anaconda.org/user -> 522)', 522)

### Steps to Reproduce

```

```

## Expected Behavior
 Navigator should start up

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Traceback (most recent call last):
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 146, in start_app
    window = run_app(splash)
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/widgets/main_window.py", line 166, in __init__
    self.api = AnacondaAPI()
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 1534, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/anaconda_api.py", line 82, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 660, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 95, in __init__
    self.reload_client()
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/anaconda_navigator/api/client_api.py", line 326, in reload_client
    client.user()
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 242, in user
    self._check_response(res)
  File "/Users/zhiyonglim/opt/anaconda3/lib/python3.9/site-packages/binstar_client/__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.ServerError: ('?: Undefined error ([GET] https://api.anaconda.org/user -> 522)', 522)
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
