### ISSUE TITLE
archiconda3 on raspberry pi 4

### ISSUE THREAD

**Issue by vs1612** [conda/conda#10816]
Hello,

I using the following setup for my code.
-> raspberry pi 4 with 64-biti os(aarch64)
-> archiconda3 for conda environment

i created the conda environment, in the environment  packages are installed using conda and Pip because librosa package is not available from conda and h5py package was not installing using pip.

so whenever i am running my code i am getting the following error, could someone help please help me with this issue ?

Traceback (most recent call last):
  File "main1.py", line 6, in <module>
    from data_loader import organiser
  File "/home/pi/Deep_Audio_Net/data_loader/organiser.py", line 6, in <module>
    from exp_run import audio_feature_extractor as afe
  File "/home/pi/Deep_Audio_Net/exp_run/audio_feature_extractor.py", line 2, in <module>
    import librosa
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/librosa/__init__.py", line 13, in <module>
    from . import core
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/librosa/core/__init__.py", line 114, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/librosa/util/__init__.py", line 72, in <module>
    from ._nnls import *  # pylint: disable=wildcard-import
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/librosa/util/_nnls.py", line 13, in <module>
    import scipy.optimize
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/scipy/optimize/__init__.py", line 400, in <module>
    from .optimize import *
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/scipy/optimize/optimize.py", line 36, in <module>
    from ._numdiff import approx_derivative
  File "/home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/scipy/optimize/_numdiff.py", line 8, in <module>
    from ._group_columns import group_dense, group_sparse
ImportError: /lib/aarch64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /home/pi/archiconda3/envs/daic/lib/python3.7/site-packages/scipy/optimize/_group_columns.cpython-37m-aarch64-linux-gnu.so)

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
