### ISSUE TITLE
Type error in pkg_formats/python.py

### ISSUE THREAD

**Issue by yakazimir** [conda/conda#10822]
## Current Behavior
I encountered this issue in one of my recent runs. Since it is the kind of error report that I would otherwise send to you, perhaps it is already informative enough? (this is in a private repo, so I cannot share, but I am very happy to provide more details as needed.. at first glance, it is very difficult to understand where this is happening and come up with a toy example).

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_export.py", line 94, in execute
        ignore_channels=args.ignore_channels)
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda_env/env.py", line 95, in from_environment
        precs = tuple(PrefixGraph(pd.iter_records()).graph)
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/core/prefix_data.py", line 117, in iter_records
        return itervalues(self._prefix_records)
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/core/prefix_data.py", line 146, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/core/prefix_data.py", line 70, in load
        self._load_site_packages()
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/core/prefix_data.py", line 261, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 253, in read_python_record
        paths_tups = pydist.get_paths()
      File "/home/kyler/miniconda3/lib/python3.7/site-packages/conda/common/pkg_formats/python.py", line 268, in get_paths
        records = sorted(concatv(records, ((pf, None, None) for pf in missing_pyc_files)))
    TypeError: '<' not supported between instances of 'str' and 'NoneType'

`$ /home/kyler/miniconda3/bin/conda-env export`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=neural_modeling
                CONDA_EXE=/home/kyler/miniconda3/bin/conda
             CONDA_PREFIX=/home/kyler/miniconda3/envs/neural_modeling
           CONDA_PREFIX_1=/home/kyler/miniconda3
    CONDA_PROMPT_MODIFIER=(neural_modeling)
         CONDA_PYTHON_EXE=/home/kyler/miniconda3/bin/python
               CONDA_ROOT=/home/kyler/miniconda3
              CONDA_SHLVL=2
                     PATH=/home/kyler/miniconda3/envs/neural_modeling/bin:/home/kyler/minicon
                          da3/condabin:/opt/ai2ools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin
                          :/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/opt/ops/bin:/snap/bi
                          n
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : neural_modeling
    active env location : /home/kyler/miniconda3/envs/neural_modeling
            shell level : 2
       user config file : /home/kyler/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /home/kyler/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/kyler/miniconda3/pkgs
                          /home/kyler/.conda/pkgs
       envs directories : /home/kyler/miniconda3/envs
                          /home/kyler/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.4.0-142-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 2274:100
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
```

**Comment by jezdez** [comment]
This is using a fairly outdated version of Conda, could you please try to reproduce the issue on a current version of Conda?

**Comment by floyddcn** [comment]
conda update --name base conda
参考： https://blog.csdn.net/weixin_35436966/article/details/114958455
