### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by jitgithub1990** [conda/conda#10858]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
'list' object has no attribute 'get'
Traceback
Traceback (most recent call last):
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 82, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1571, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 342, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "C:\Users\BISWAJIT\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 493, in set_conda_prefix
    self.ROOT_PREFIX = info.get('root_prefix')
AttributeError: 'list' object has no attribute 'get'

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
