### ISSUE TITLE
Python ImportError: DLL load failed while importing

### ISSUE THREAD

**Issue by aminrd** [conda/conda#10853]
On Windows 10, I have an environment having `Python==3.9.6` installed using `conda 4.10.1`. I have a strange issue. Having two packages `rasterio==1.2.6` and `h5py==3.3.0` installed, either of these two packages are imported first, working well, but the second one is having the following error:

```python
>>> import rasterio # Imported without any problem
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\amin_\Anaconda3\envs\minusone\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\amin_\Anaconda3\envs\minusone\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
```

And then when I change the order of importing these packages: 
```python
>>> import h5py # Imported without any problem
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\amin_\Anaconda3\envs\minusone\lib\site-packages\rasterio\__init__.py", line 9, in <module>
    from rasterio._base import gdal_version
ImportError: DLL load failed while importing _base: The specified procedure could not be found.
```

**Comment by mingjun1120** [comment]
Any idea how to solve this issue?😅

**Comment by jezdez** [comment]
This sounds like a problem with the h5py package in the defaults channel, maintained by Anaconda, Inc.

Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). Thank you for understanding!
