### ISSUE TITLE
Conda command is not working in the MacBook terminal after uninstalling and reinstalling Anaconda-Navigator.

### ISSUE THREAD

**Issue by Sowkel** [conda/conda#10868]
I was unable to open Anaconda-Navigator by double-clicking on its icon. Hence, I uninstalled and reinstalled it, following the [Anaconda documentation's instruction](https://docs.anaconda.com/anaconda/install/mac-os/). Anaconda navigator now works properly. Unfortunately, Conda get broken. 

No conda command is working in the terminal. 
For example, while typing `conda info` on the MAC Book terminal, I get:
```
Traceback (most recent call last):
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 74, in _main
    from ..base.context import context
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 22, in <module>
    from .._vendor.appdirs import user_data_dir
ModuleNotFoundError: No module named 'conda._vendor.appdirs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/username/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1192, in print_unexpected_error_report
    from .base.context import context
  File "/Users/username/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 22, in <module>
    from .._vendor.appdirs import user_data_dir
ModuleNotFoundError: No module named 'conda._vendor.appdirs'
```
However, in the Anaconda Navigator, I can see all my environments listed and can choice any of them and run jupyter environments from there.
Hence, the problem occurs when I use the CLI.
Any advice would be welcome

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
