### ISSUE TITLE
Access in Anaconda Terminal

### ISSUE THREAD

**Issue by N1cola2** [conda/conda#10873]
I'm having trouble inicializing my anaconda terminal. When I try, it shows this message:

Main Error
('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)
Traceback
Traceback (most recent call last):
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 146, in start_app
    window = run_app(splash)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 165, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1518, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 83, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 659, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 95, in __init__
    self.reload_client()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 326, in reload_client
    client.user()
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 245, in user
    self._check_response(res)
  File "C:\Users\teixenic\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 230, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
