### ISSUE TITLE
conda run fails due to read-only filesystem inside Singularity container

### ISSUE THREAD

**Issue by stevekm** [conda/conda#10888]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

When running the `conda run` command inside a Singularity container, conda breaks because it cannot write to the filesystem.

```
$ singularity pull docker://continuumio/miniconda3:4.10.3

$ singularity run miniconda3_4.10.3.sif conda run echo foo

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main_run.py", line 25, in execute
        script_caller, command_args = wrap_subprocess_call(on_win, context.root_prefix, prefix,
      File "/opt/conda/lib/python3.9/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/opt/conda/lib/python3.9/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/conda/lib/python3.9/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/conda/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    OSError: [Errno 30] Read-only file system: '/opt/conda/.tmpjn7dutmu'

`$ /opt/conda/bin/conda run echo foo`
```

Unlike Docker, Singularity containers typically are run with a read-only filesystem. 

It seems like this makes `conda run` unusable. 

`conda run` should not need to write anything to disk. There is no state that needs to be preserved inside the container.

### Additional Context

Using Singularity version 3.3.0 on CentOS 7

```
$ singularity --version
singularity version 3.3.0-dirty.el7.centos
```

**Comment by bouweandela** [comment]
Closed by #11215?
