### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte

### ISSUE THREAD

**Issue by xlg-go** [conda/conda#10891]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

conda create or pip install, throw exception!
help me please, thanks!!

my conda is from https://github.com/conda-forge/miniforge!
only minforge can be installed!!!!

conda version is 4.10.3

environment：
    OS: Debian9.13, 64bit
    uname -a: Linux linaro-alip 4.4.19415 #1 SMP Tue Aug 17 09:24:19 CST 2021 aarch64 GNU/Linux
    CPU: RK3399

when i conda create or conda install or pip install, will throw excption:

Traceback (most recent call last):
File "/root/miniforge3/bin/conda", line 13, in
sys.exit(main())
File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 152, in main
return conda_exception_handler(_main, *args, **kwargs)
File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
return_value = exception_handler(func, *args, **kwargs)
File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in call
return self.handle_exception(exc_val, exc_tb)
File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1126, in handle_exception
return self.handle_unexpected_exception(exc_val, exc_tb)
File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1141, in handle_unexpected_exception
self._execute_upload(error_report)
File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1303, in _execute_upload
'User-Agent': self.user_agent,
File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1101, in user_agent
return context.user_agent
File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
cache[inner_attname] = func(self)
File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 775, in user_agent
builder.append("%s/%s" % self.os_distribution_name_version)
File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
cache[inner_attname] = func(self)
File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 817, in os_distribution_name_version
from conda._vendor.distro import id, version
File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1084, in
_distro = LinuxDistribution()
File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 601, in init
self._distro_release_info = self._get_distro_release_info()
File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
distro_info = self._parse_distro_release_file(filepath)
File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
return self._parse_distro_release_content(fp.readline())
File "/root/miniforge3/lib/python3.9/codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte

### Conda info

```shell
conda info throw exception!!

(base) root@linaro-alip:/usr/src# conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main_info.py", line 317, in execute
        info_dict = get_info_dict(args.system)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main_info.py", line 135, in get_info_dict
        _supplement_index_with_system(virtual_pkg_index)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/core/index.py", line 164, in _supplement_index_with_system
        dist_name, dist_version = context.os_distribution_name_version
      File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 817, in os_distribution_name_version
        from conda._vendor.distro import id, version
      File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1084, in <module>
        _distro = LinuxDistribution()
      File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 601, in __init__
        self._distro_release_info = self._get_distro_release_info()
      File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
        distro_info = self._parse_distro_release_file(filepath)
      File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
        return self._parse_distro_release_content(fp.readline())
      File "/root/miniforge3/lib/python3.9/codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte

`$ /root/miniforge3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Traceback (most recent call last):
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main_info.py", line 317, in execute
    info_dict = get_info_dict(args.system)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main_info.py", line 135, in get_info_dict
    _supplement_index_with_system(virtual_pkg_index)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/core/index.py", line 164, in _supplement_index_with_system
    dist_name, dist_version = context.os_distribution_name_version
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 817, in os_distribution_name_version
    from conda._vendor.distro import id, version
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1084, in <module>
    _distro = LinuxDistribution()
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 601, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
    distro_info = self._parse_distro_release_file(filepath)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
    return self._parse_distro_release_content(fp.readline())
  File "/root/miniforge3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniforge3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/root/miniforge3/lib/python3.9/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1141, in handle_unexpected_exception
    self._execute_upload(error_report)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1303, in _execute_upload
    'User-Agent': self.user_agent,
  File "/root/miniforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1101, in user_agent
    return context.user_agent
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 775, in user_agent
    builder.append("%s/%s" % self.os_distribution_name_version)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/base/context.py", line 817, in os_distribution_name_version
    from conda._vendor.distro import id, version
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1084, in <module>
    _distro = LinuxDistribution()
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 601, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
    distro_info = self._parse_distro_release_file(filepath)
  File "/root/miniforge3/lib/python3.9/site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
    return self._parse_distro_release_content(fp.readline())
  File "/root/miniforge3/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 18: invalid start byte
```

### Conda config

```shell
(base) root@linaro-alip:/usr/src# conda config --show-sources
==> /root/miniforge3/.condarc <==
channels:
  - conda-forge
```

### Conda list

```shell
(base) root@linaro-alip:/usr/src# conda list --show-channel-urls
# packages in environment at /root/miniforge3:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       1_gnu    conda-forge
brotlipy                  0.7.0           py39h14843e3_1001    conda-forge
ca-certificates           2021.5.30            h4fd8a4c_0    conda-forge
certifi                   2021.5.30        py39ha65689a_0    conda-forge
cffi                      1.14.6           py39h460e462_0    conda-forge
chardet                   4.0.0            py39ha65689a_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3           py39ha65689a_0    conda-forge
conda-package-handling    1.7.3            py39h14843e3_0    conda-forge
cryptography              3.4.7            py39hc5d6c06_0    conda-forge
flatbuffers               2.0                      pypi_0    pypi
idna                      3.1                pyhd3deb0d_0    conda-forge
ld_impl_linux-aarch64     2.36.1               h02ad14f_2    conda-forge
libffi                    3.3                  h884eca8_2    conda-forge
libgcc-ng                 11.1.0               h3322914_8    conda-forge
libgomp                   11.1.0               h3322914_8    conda-forge
libstdcxx-ng              11.1.0               h5eeca4d_8    conda-forge
ncurses                   6.2                  h7fd3ca4_4    conda-forge
numpy                     1.21.2                   pypi_0    pypi
onnxruntime               1.8.1                    pypi_0    pypi
opencv-python             4.5.3.56                 pypi_0    pypi
openssl                   1.1.1k               hf897c2e_1    conda-forge
pillow                    8.3.1                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
protobuf                  3.17.3                   pypi_0    pypi
pyclipper                 1.3.0                    pypi_0    pypi
pycosat                   0.6.3           py39h14843e3_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39ha65689a_3    conda-forge
python                    3.9.6           h4f4e160_1_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
readline                  8.1                  h1a49cc3_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39h14843e3_1004    conda-forge
setuptools                57.4.0           py39ha65689a_0    conda-forge
shapely                   1.5.9                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               hc164836_0    conda-forge
tk                        8.6.11               ha99a2a3_0    conda-forge
torch                     1.9.0                    pypi_0    pypi
tqdm                      4.62.1             pyhd8ed1ab_0    conda-forge
typing-extensions         3.10.0.2                 pypi_0    pypi
tzdata                    2021a                he74cb21_1    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h6dd45c4_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1009    conda-forge
```

**Comment by jezdez** [comment]
Thanks for the report, it seems as if you're running on a Linux distro that isn't currently in the list of distros that we know how to automatically discover, and it trips the code up and doesn't catch the unicode error correctly.

A way forward for this would be:

1. Could you check if there is a file that ends with "-release" or "-version" in your `/etc` directory?

The code here tries to be smart and figure out the distro name from that file:

https://github.com/conda/conda/blob/0b1312ce65bf0fbb8cbea3750f07c32a2492c57a/conda/_vendor/distro.py#L1003-L1018

2. We'll need to figure out why the distro name that it *does* discover fails with a unicode error, and then open a ticket in the [distro](https://github.com/python-distro/distro) project to fix the handling.

Thank you for your help in further diving into this problem @zcgg2zhmm :)

**Comment by zcgg2zhmm** [comment]
> Thanks for the report, it seems as if you're running on a Linux distro that isn't currently in the list of distros that we know how to automatically discover, and it trips the code up and doesn't catch the unicode error correctly.
> 
> A way forward for this would be:
> 
> 1. Could you check if there is a file that ends with "-release" or "-version" in your `/etc` directory?
> 
> The code here tries to be smart and figure out the distro name from that file:
> 
> https://github.com/conda/conda/blob/0b1312ce65bf0fbb8cbea3750f07c32a2492c57a/conda/_vendor/distro.py#L1003-L1018
> 
> 1. We'll need to figure out why the distro name that it _does_ discover fails with a unicode error, and then open a ticket in the [distro](https://github.com/python-distro/distro) project to fix the handling.
> 
> Thank you for your help in further diving into this problem @zcgg2zhmm :)

that's my honor~~
