### ISSUE TITLE
Pykep install error

### ISSUE THREAD

**Issue by pratiksingha-11** [conda/conda#10951]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\LENOVO\Anaconda3  (writable)
    default environment : C:\Users\LENOVO\Anaconda3
       envs directories : C:\Users\LENOVO\Anaconda3\envs
                          C:\Users\LENOVO\AppData\Local\conda\conda\envs
                          C:\Users\LENOVO\.conda\envs
          package cache : C:\Users\LENOVO\Anaconda3\pkgs
                          C:\Users\LENOVO\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\LENOVO\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.19041
          administrator : False

`$ C:\Users\LENOVO\Anaconda3\Scripts\conda config --set channel_priority strict`

    Traceback (most recent call last):
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\_vendor\auxlib\type_coercion.py", line 164, in boolify
        return bool(complex(val))
    ValueError: complex() arg is a malformed string

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\_vendor\auxlib\type_coercion.py", line 243, in typify
        return boolify(value) if type_hint == bool else type_hint(value)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\_vendor\auxlib\type_coercion.py", line 168, in boolify
        raise TypeCoercionError(value, "The value %r cannot be boolified." % value)
    conda._vendor.auxlib.type_coercion.TypeCoercionError: The value 'strict' cannot be boolified.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\cli\main_config.py", line 210, in execute
        execute_config(args, parser)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\cli\main_config.py", line 399, in execute_config
        value = context.typify_parameter(key, item)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\common\configuration.py", line 904, in typify_parameter
        return typify_data_structure(value, parameter._element_type)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\_vendor\auxlib\type_coercion.py", line 259, in typify_data_structure
        return typify(value, type_hint)
      File "C:\Users\LENOVO\Anaconda3\lib\site-packages\conda\_vendor\auxlib\type_coercion.py", line 246, in typify
        raise TypeCoercionError(value, text_type(e))
    conda._vendor.auxlib.type_coercion.TypeCoercionError: The value 'strict' cannot be boolified.

**Comment by jezdez** [comment]
This is a very old version of Conda from 2017, could you upgrade conda and conda-build please and try again?
