### ISSUE TITLE
UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

### ISSUE THREAD

**Issue by RongjunHuang** [conda/conda#10984]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### Actual Behavior

I just simply type `conda list` and it returns error: `UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.`

```shell
(base) C:\Users\CCZ>conda list

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "G:\Anaconda\ANA\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 140, in iter_records
        return itervalues(self._prefix_records)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 169, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "G:\Anaconda\ANA\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 77, in load
        self._load_single_record(meta_file)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 175, in _load_single_record
        json_data = json_load(fh.read())
      File "G:\Anaconda\ANA\lib\codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
```

### Conda info

```shell
(base) C:\Users\CCZ>conda info

     active environment : base
    active env location : G:\Anaconda\ANA
            shell level : 1
       user config file : C:\Users\CCZ\.condarc
 populated config files : C:\Users\CCZ\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.4=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : G:\Anaconda\ANA  (writable)
      conda av data dir : G:\Anaconda\ANA\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : G:\Anaconda\ANA\pkgs
                          C:\Users\CCZ\.conda\pkgs
                          C:\Users\CCZ\AppData\Local\conda\conda\pkgs
       envs directories : G:\Anaconda\ANA\envs
                          C:\Users\CCZ\.conda\envs
                          C:\Users\CCZ\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.7.10 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config

```shell
(base) C:\Users\CCZ>conda config --show-sources
==> C:\Users\CCZ\.condarc <==
default_python: None
ssl_verify: True
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
(base) C:\Users\CCZ>conda list --show-channel-urls

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "G:\Anaconda\ANA\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 140, in iter_records
        return itervalues(self._prefix_records)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 169, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "G:\Anaconda\ANA\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 77, in load
        self._load_single_record(meta_file)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 175, in _load_single_record
        json_data = json_load(fh.read())
      File "G:\Anaconda\ANA\lib\codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
```

### Additional Context

I have tried `conda update conda`, it returns the same error.

**Comment by RongjunHuang** [comment]
Pls helphelp me

**Comment by RongjunHuang** [comment]
G: drive is a local drive on my computer.

(base) C:\Users\CCZ>conda info --all

     active environment : base
    active env location : G:\Anaconda\ANA
            shell level : 1
       user config file : C:\Users\CCZ\.condarc
 populated config files : C:\Users\CCZ\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : G:\Anaconda\ANA  (writable)
      conda av data dir : G:\Anaconda\ANA\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : G:\Anaconda\ANA\pkgs
                          C:\Users\CCZ\.conda\pkgs
                          C:\Users\CCZ\AppData\Local\conda\conda\pkgs
       envs directories : G:\Anaconda\ANA\envs
                          C:\Users\CCZ\.conda\envs
                          C:\Users\CCZ\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.7.10 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False

# conda environments:
#
base                  *  G:\Anaconda\ANA
rstudio                  G:\Anaconda\ANA\envs\rstudio
                         G:\Anaconda\Miniconda\mini

sys.version: 3.7.10 | packaged by conda-forge | (defa...
sys.prefix: G:\Anaconda\ANA
sys.executable: G:\Anaconda\ANA\python.exe
conda location: G:\Anaconda\ANA\lib\site-packages\conda
conda-build: G:\Anaconda\ANA\Scripts\conda-build.exe
conda-content-trust: G:\Anaconda\ANA\Scripts\conda-content-trust.exe
conda-convert: G:\Anaconda\ANA\Scripts\conda-convert.exe
conda-debug: G:\Anaconda\ANA\Scripts\conda-debug.exe
conda-develop: G:\Anaconda\ANA\Scripts\conda-develop.exe
conda-env: G:\Anaconda\ANA\Scripts\conda-env.exe
conda-index: G:\Anaconda\ANA\Scripts\conda-index.exe
conda-inspect: G:\Anaconda\ANA\Scripts\conda-inspect.exe
conda-metapackage: G:\Anaconda\ANA\Scripts\conda-metapackage.exe
conda-pack: G:\Anaconda\ANA\Scripts\conda-pack.exe
conda-render: G:\Anaconda\ANA\Scripts\conda-render.exe
conda-repo: G:\Anaconda\ANA\Scripts\conda-repo.exe
conda-server: G:\Anaconda\ANA\Scripts\conda-server.exe
conda-skeleton: G:\Anaconda\ANA\Scripts\conda-skeleton.exe
conda-token: G:\Anaconda\ANA\Scripts\conda-token.exe
conda-verify: G:\Anaconda\ANA\Scripts\conda-verify.exe
user site dirs: C:\Users\CCZ\AppData\Roaming\Python\Python27
                C:\Users\CCZ\AppData\Roaming\Python\Python37

AMDRMPATH: C:\Program Files\AMD\RyzenMaster\
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: base
CONDA_EXE: G:\Anaconda\ANA\condabin\..\Scripts\conda.exe
CONDA_EXES: "G:\Anaconda\ANA\condabin\..\Scripts\conda.exe"
CONDA_PREFIX: G:\Anaconda\ANA
CONDA_PROMPT_MODIFIER: (base)
CONDA_PYTHON_EXE: G:\Anaconda\ANA\python.exe
CONDA_ROOT: G:\Anaconda\ANA
CONDA_SHLVL: 1
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4
CURL_CA_BUNDLE: <not set>
HOMEPATH: \Users\CCZ
LIBPATH: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\lib\x86\store\references;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;
NVTOOLSEXT_PATH: C:\Program Files\NVIDIA Corporation\NvToolsExt\
PATH: G:\Anaconda\ANA;G:\Anaconda\ANA\Library\mingw-w64\bin;G:\Anaconda\ANA\Library\usr\bin;G:\Anaconda\ANA\Library\bin;G:\Anaconda\ANA\Scripts;G:\Anaconda\ANA\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.1 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\\MSBuild\15.0\bin;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\;G:\Anaconda\ANA;G:\Anaconda\ANA\Library\mingw-w64\bin;G:\Anaconda\ANA\Library\usr\bin;G:\Anaconda\ANA\Library\bin;G:\Anaconda\ANA\Scripts;G:\Anaconda\ANA\bin;G:\Anaconda\ANA\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Program Files\ImageMagick-7.0.10-Q16-HDRI;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Python38\Scripts;C:\Python38;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;G:\TeX-LaTeX\T-L\miktex\bin\x64;G:\Node.js;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86;C:\Program Files\Git\cmd;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Pandoc;C:\Program Files (x86)\dotnet;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;G:\Mathematics Tools\Matlab\2020b\runtime\win64;G:\Mathematics Tools\Matlab\2020b\bin;C:\Program Files\Wolfram Research\WolframScript;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.2;C:\Program Files (x86)\STMicroelectronics\STM32 ST-LINK Utility\ST-LINK Utility;C:\Users\CCZ\AppData\Local\Microsoft\WindowsApps;G:\FoldingAtHome\FAHClient;C:\Users\CCZ\AppData\Roaming\npm;C:\Users\CCZ\AppData\Local\GitHubDesktop\bin;C:\Users\CCZ\AppData\Local\Microsoft\WindowsApps;.;G:\Anaconda\PyCharm\PyCharm 2021.2.2\bin;.;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
PSMODULEPATH: C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>
WINDOWSLIBPATH: References\CommonConfiguration\Neutral
__VSCMD_PREINIT_PATH: G:\Anaconda\ANA;G:\Anaconda\ANA\Library\mingw-w64\bin;G:\Anaconda\ANA\Library\usr\bin;G:\Anaconda\ANA\Library\bin;G:\Anaconda\ANA\Scripts;G:\Anaconda\ANA\bin;G:\Anaconda\ANA\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.4\libnvvp;C:\Program Files\ImageMagick-7.0.10-Q16-HDRI;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Python38\Scripts;C:\Python38;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;G:\TeX-LaTeX\T-L\miktex\bin\x64;G:\Node.js;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\AMD APP SDK\3.0\bin\x86;C:\Program Files\Git\cmd;C:\Program Files\Common Files\Autodesk Shared;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Pandoc;C:\Program Files (x86)\dotnet;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;G:\Mathematics Tools\Matlab\2020b\runtime\win64;G:\Mathematics Tools\Matlab\2020b\bin;C:\Program Files\Wolfram Research\WolframScript;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\Nsight Compute 2021.2.2;C:\Program Files (x86)\STMicroelectronics\STM32 ST-LINK Utility\ST-LINK Utility;C:\Users\CCZ\AppData\Local\Microsoft\WindowsApps;G:\FoldingAtHome\FAHClient;C:\Users\CCZ\AppData\Roaming\npm;C:\Users\CCZ\AppData\Local\GitHubDesktop\bin;C:\Users\CCZ\AppData\Local\Microsoft\WindowsApps;.;G:\Anaconda\PyCharm\PyCharm 2021.2.2\bin;.
