### ISSUE TITLE
I met some problems when creating a conda environment

### ISSUE THREAD

**Issue by MazelTovy** [conda/conda#10998]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

When I read a book, it tells me to create a conda environment by sending the following code in the terminal:

`conda env create -f environment.yml`

There is a file named _environment.yml_, it has included following codes:

```
name: gluon
dependencies:
- python=3.6
- jupyter=1.0.0
- matplotlib=2.2.2
- pandas=0.23.2
- pip:
  - requests==2.18.4
  - mxnet==1.2.1
  - gluonbook==0.8.3
```
But it returned following traceback to let me find the solution on GitHub:

```
Traceback (most recent call last):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/pi/miniconda3/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/home/pi/miniconda3/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/home/pi/miniconda3/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 244, in install
    offline=args.offline)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/pi/miniconda3/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/home/pi/miniconda3/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/home/pi/miniconda3/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 150, in fetch_repodata
    stderrlog.info("SSL verification error %s\n" % e.message)
AttributeError: 'SSLError' object has no attribute 'message'
```

I want to know how to solve the question to let me create the correct environment. Thank you.

### Conda info

```shell
Current conda install:

             platform : linux-armv7l
        conda version : 3.16.0
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/pi/miniconda3  (writable)
  default environment : /home/pi/miniconda3
     envs directories : /home/pi/miniconda3/envs
        package cache : /home/pi/miniconda3/pkgs
         channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-armv7l/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-armv7l/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                        https://mirrors.ustc.edu.cn/anaconda/pkgs/main/linux-armv7l/
                        https://mirrors.ustc.edu.cn/anaconda/pkgs/main/noarch/
                        https://mirrors.ustc.edu.cn/anaconda/pkgs/free/linux-armv7l/
                        https://mirrors.ustc.edu.cn/anaconda/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/free/linux-armv7l/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-armv7l/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/pi/.condarc
    is foreign system : False
```

### Conda config

```shell
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required
```

### Conda list

```shell
# packages in environment at /home/pi/miniconda3:
#
conda                     3.16.0                   py34_0    <unknown>
conda-env                 2.4.2                    py34_0    <unknown>
openssl                   1.0.1k                        1    <unknown>
pycosat                   0.6.1                    py34_0    <unknown>
pycrypto                  2.6.1                    py34_0    <unknown>
python                    3.4.3                         1    <unknown>
pyyaml                    3.11                     py34_1    <unknown>
requests                  2.7.0                    py34_0    <unknown>
sqlite                    3.8.4.1                       1    <unknown>
xz                        5.0.5                         0    <unknown>
yaml                      0.1.6                         0    <unknown>
zlib                      1.2.8                         0    <unknown>
```

### Additional Context

I just bought my Raspberry Pi recently and am not familiar with the Linux system.

So I might have done something incorrent before this step, please let me not if you consider the reason possible. 

Thank you very much.

**Comment by MazelTovy** [comment]
> @MazelTovy `conda` v3.16.0 was released 6 year ago, can you try a newer `conda`?

I downloaded miniconda by the command `wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-armv7l.sh`

So I think that might be the latest version of miniconda on Raspberry Pi. It could have not been updated for years. Can you please teach me to download a usable newer conda on Pi?
