### ISSUE TITLE
More informative error when installing package for the wrong architecture

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#11024]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

Currently if a user tries to install a package from an incompatible architecture on their system, Conda will say the package is not found. For example:

<details>

```python
$ conda create -n cptst -c conda-forge cupy=9.5.0=py38hfeb1181_1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cupy==9.5.0=py38hfeb1181_1

Current channels:

  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/nvidia/linux-64
  - https://conda.anaconda.org/nvidia/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

</details>

This could cause the user to think the package perhaps has not been mirrored or there is some other issue blocking installation (particularly if they grabbed these details from Anaconda.org where the package shows up). It would be better in these cases to have an error more descriptive of the problem encountered.

### Why is this needed

Sometimes users may try to install a specific package to make sure it is available from the mirror and can be installed. Though in these cases they may grab the wrong build string missing the fact that a particular build string is associated with a package not for their architecture (like `aarch64` or `ppc64le`).

### What should happen?

In these cases it would be helpful to have a more informative error suggesting the user is trying to install a package on the wrong architecture. This would help clarify the issue to the user and better inform their next steps. This need not suggest packages (though that could be useful as well). Simply alluding to the kind of issue would already be helpful.

### Additional Context

<details>
<summary>
`conda info` :
</summary>

```
$ conda info

     active environment : base
    active env location : /datasets/jkirkham/miniconda
            shell level : 1
       user config file : /home/nfs/jkirkham/.condarc
 populated config files : /home/nfs/jkirkham/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.8.12.final.0
       virtual packages : __cuda=11.2=0
                          __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /datasets/jkirkham/miniconda  (writable)
      conda av data dir : /datasets/jkirkham/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/nvidia/linux-64
                          https://conda.anaconda.org/nvidia/noarch
          package cache : /datasets/jkirkham/miniconda/pkgs
                          /home/nfs/jkirkham/.conda/pkgs
       envs directories : /datasets/jkirkham/miniconda/envs
                          /home/nfs/jkirkham/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.12 Linux/4.15.0-76-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 10124:10004
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary>
`conda config --show-sources` :
</summary>

```
$ conda config --show-sources
==> /home/nfs/jkirkham/.condarc <==
channels:
  - conda-forge
  - defaults
  - nvidia
show_channel_urls: True
```

</details>

<details>
<summary>
`conda list --show-channel-urls`:
</summary>

```
$ conda list --show-channel-urls
# packages in environment at /datasets/jkirkham/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py38h578d9bd_1    conda-forge
cffi                      1.15.0           py38h3931269_0    conda-forge
chardet                   4.0.0            py38h578d9bd_2    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3           py38h578d9bd_3    conda-forge
conda-build               3.21.4           py38h578d9bd_0    conda-forge
conda-package-handling    1.7.3            py38h497a2fe_1    conda-forge
cryptography              35.0.0           py38h3e25421_2    conda-forge
filelock                  3.3.2              pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
krb5                      1.19.2               hcc1bbae_3    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libcurl                   7.79.1               h2574ce0_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h9c3ff4c_4    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgomp                   11.2.0              h1d223b6_11    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.11.5               h9c3ff4c_1    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.17.0           py38h2aa5da1_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_1    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
patchelf                  0.13                 h58526e2_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.7.1              pyhd8ed1ab_0    conda-forge
psutil                    5.8.0            py38h497a2fe_2    conda-forge
py-lief                   0.11.5           py38h709712a_1    conda-forge
pycosat                   0.6.3           py38h497a2fe_1009    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_4    conda-forge
python                    3.8.12          hb7a2778_2_cpython    conda-forge
python-libarchive-c       3.1              py38h578d9bd_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py38h497a2fe_2    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               habb4d0f_1    conda-forge
ruamel_yaml               0.15.80         py38h497a2fe_1006    conda-forge
setuptools                58.5.2           py38h578d9bd_0    conda-forge
shyaml                    0.6.2              pyhd3deb0d_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.36.0               h9cd32fc_2    conda-forge
tk                        8.6.11               h27826a3_1    conda-forge
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

</details>

**Comment by kenodegard** [comment]
Fair, so something generic like detecting that the user specified the build string and upon failing suggest dropping the build string requirement?

**Comment by jakirkham** [comment]
Maybe? Or could then look for the package without the architecture constraint

**Comment by qris** [comment]
It's also possible to install a package for the wrong architecture, e.g. 32-bit Windows on a 64-bit system. It installs fine, but if the package contains any binary components such as Python DLLs, they cannot be loaded. For example, you can install the win32 `line_profiler` with 64-bit Python, but it doesn't work:

```
$ tar tjvf line_profiler-3.3.1-py37h59b6b97_0.tar.bz2 '*pyd*'
-rw-rw-rw- 0/0           80384 2022-01-13 15:43 Lib/site-packages/line_profiler/_line_profiler.cp37-win_amd64.pyd
$ tar tjvf line_profiler-3.3.1-py37heed823b_0.tar.bz2 '*pyd*'
-rw-rw-rw- 0/0           68096 2022-01-13 15:43 Lib/site-packages/line_profiler/_line_profiler.cp37-win32.pyd

>>> import line_profiler
Traceback (most recent call last):
  File "I:\sw\conda\envs\20220411-0\lib\site-packages\line_profiler\line_profiler.py", line 28, in <module>
    from ._line_profiler import LineProfiler as CLineProfiler
ModuleNotFoundError: No module named 'line_profiler._line_profiler'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "I:\sw\conda\envs\20220411-0\lib\site-packages\line_profiler\__init__.py", line 10, in <module>
    from .line_profiler import __version__
  File "I:\sw\conda\envs\20220411-0\lib\site-packages\line_profiler\line_profiler.py", line 32, in <module>
    'Has it been compiled? Underlying error is ex={!r}'.format(ex)
ImportError: The line_profiler._line_profiler c-extension is not importable. Has it been compiled? Underlying error is ex=ModuleNotFoundError("No module named 'line_profiler._line_profiler'")
```

The [documentation says](https://docs.conda.io/projects/conda-build/en/latest/resources/package-spec.html#info-index-json):

>arch | string | Optional. The architecture the package is built for. EXAMPLE: x86_64. Conda currently does not use this key.

But presumably it *could* check it?

**Comment by kenodegard** [comment]
The effort to introduce better error reporting via the libmamba solver may aid here? https://github.com/conda/conda-libmamba-solver/issues/102
