### ISSUE TITLE
Issue while building conda

### ISSUE THREAD

**Issue by payalmohapatra** [conda/conda#11033]
##### `Output of conda info`

```
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/payal/anaconda3  (writable)
    default environment : /home/payal/anaconda3
       envs directories : /home/payal/anaconda3/envs
          package cache : /home/payal/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /home/payal/anaconda3/bin/conda-env create -f comp135_2020f_env.yml`




    Traceback (most recent call last):
      File "/home/payal/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/payal/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/home/payal/anaconda3/lib/python3.5/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: comp135_2020f_env.yml file not found
    There is no requirements.txt
```

**Comment by kenodegard** [comment]
@payalmohapatra

This doesn't appear to be a problem with `conda` (see the error message `comp135_2020f_env.yml file not found`). Please make sure you are referencing a valid environment file.

I also encourage using a newer version of conda as it has better error handling. To update to the latest run the following:

```bash
conda update conda
```

Let me know if you are still experiencing this issue.

**Comment by kenodegard** [comment]
Closing due to inactivity. Feel free to comment further and we will reopen this issue.
