### ISSUE TITLE
Conda script : UnicodeDecodeError

### ISSUE THREAD

**Issue by RongjunHuang** [conda/conda#11034]
### Actual Behavior

I just simply type `conda list` and it returns error: `UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.`

```batch
(base) C:\Users\CCZ>conda list

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "G:\Anaconda\ANA\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "G:\Anaconda\ANA\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 140, in iter_records
        return itervalues(self._prefix_records)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 169, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "G:\Anaconda\ANA\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 77, in load
        self._load_single_record(meta_file)
      File "G:\Anaconda\ANA\lib\site-packages\conda\core\prefix_data.py", line 175, in _load_single_record
        json_data = json_load(fh.read())
      File "G:\Anaconda\ANA\lib\codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
```

##### `Output of conda info`

```bash
     active environment : base
    active env location : G:\Anaconda\ANA
            shell level : 1
       user config file : C:\Users\CCZ\.condarc
 populated config files : C:\Users\CCZ\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.4
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.4=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : G:\Anaconda\ANA  (writable)
      conda av data dir : G:\Anaconda\ANA\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : G:\Anaconda\ANA\pkgs
                          C:\Users\CCZ\.conda\pkgs
                          C:\Users\CCZ\AppData\Local\conda\conda\pkgs
       envs directories : G:\Anaconda\ANA\envs
                          C:\Users\CCZ\.conda\envs
                          C:\Users\CCZ\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.7.10 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by kenodegard** [comment]
It appears that you have a corrupt file(s) in `G:\Anaconda\ANA\conda-meta`, you can figure out which file(s) are corrupt by running the following in Python:

```python
import glob, json, os
for p in glob.glob(os.environ['CONDA_PREFIX'] + '/conda-meta/*.json'):
    try:
        _ = json.load(open(p))
    except Exception as e:
        print(f'{p}: {e.__class__.__name__}: {e}')
```

This will print out the corrupt files which you should delete. You can restore the correct file by reinstalling the package specified in the filename of the corrupt file(s) you delete.
