### ISSUE TITLE
conda new environment on Windows - Failed to import the site module

### ISSUE THREAD

**Issue by biocodz** [conda/conda#11043]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I have a Conda installation on Windows machine made using a standard Miniconda3 installer, and it works fine.
However I cannot make a new environment to work
```
python --version  -> Python 3.7.7
where python      -> C:\Users\biocodz\a01_apps\miniconda3\python.exe
conda create -n py36 python=3.6
conda env list
   # conda environments:
   #
   base                     C:\Users\biocodz\a01_apps\miniconda3
   py36                  *  C:\Users\biocodz\a01_apps\miniconda3\envs\py36
conda activate py36
  -> (py36) C:\Users\biocodz\a01_libs>
python --version    -> Python 3.6.13
python
  Failed to import the site module
  Traceback (most recent call last):
    File "C:\Users\biocodz\a01_apps\miniconda3\lib\site.py", line 579, in <module>
      main()
    File "C:\Users\biocodz\a01_apps\miniconda3\lib\site.py", line 566, in main
      known_paths = addsitepackages(known_paths)
    File "C:\Users\biocodz\a01_apps\miniconda3\lib\site.py", line 349, in addsitepackages
      addsitedir(sitedir, known_paths)
    File "C:\Users\biocodz\a01_apps\miniconda3\lib\site.py", line 207, in addsitedir
      addpackage(sitedir, name, known_paths)
    File "C:\Users\biocodz\a01_apps\miniconda3\lib\site.py", line 159, in addpackage
      f = open(fullname, "r")
    File "C:\Users\biocodz\a01_apps\miniconda3\lib\_bootlocale.py", line 12, in getpreferredencoding
      if sys.flags.utf8_mode:
  AttributeError: 'sys.flags' object has no attribute 'utf8_mode'
```

I see similar errors reported on the Net and on this site [e.g. issue 10293](https://github.com/conda/conda/issues/10293) but it doesn't help much. I have a single python installation, and creating a new environment in the most straightforward way following the official docs [Managing environments](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html), and it fails at the start

### Conda info

```shell
active environment : py36
    active env location : C:\Users\biocodz\a01_apps\miniconda3\envs\py36
            shell level : 1
       user config file : C:\Users\biocodz\.condarc
 populated config files : C:\Users\biocodz\.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.7.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\biocodz\a01_apps\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/win-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\biocodz\a01_apps\miniconda3\pkgs
                          C:\Users\biocodz\.conda\pkgs
                          C:\Users\biocodz\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\biocodz\a01_apps\miniconda3\envs
                          C:\Users\biocodz\.conda\envs
                          C:\Users\biocodz\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.7 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```
```


### Conda config

```shell
==> C:\Users\biocodz\.condarc <==
ssl_verify: False
channels:
  - bioconda
  - conda-forge
  - defaults
```
```


### Conda list

```shell
# packages in environment at C:\Users\biocodz\a01_apps\miniconda3\envs\py36:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.10.8            h5b45459_0    conda-forge
certifi                   2020.12.5        py36haa95532_0    defaults
icu                       68.2                 h0e60522_0    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
libclang                  11.1.0          default_h5c34c98_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libxml2                   2.9.12               hf5bbc77_1    conda-forge
libxslt                   1.1.33               h65864e5_3    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
pyopengl                  3.1.5                      py_0    conda-forge
pyside2                   5.13.2           py36h4827aa2_4    conda-forge
python                    3.6.13          h39d44d4_2_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
setuptools                49.6.0           py36ha15d459_3    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
wincertstore              0.2             py36ha15d459_1006    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
```
```


### Additional Context

_No response_

**Comment by biocodz** [comment]
Managed to make this work.
- remove the existing installation as per docs (from Windows Remove programs)
- install Conda per docs: `start /wait "" %UserProfile%\Downloads\Miniconda3-latest-Windows-x86_64.exe /InstallationType=JustMe /RegisterPython=0 /S /D=%UserProfile%\a01_apps\miniconda3`
- use the shortcut from the Startup menu (generated by the installer) to launch the CMD: ` %UserProfile%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Anaconda3 (64-bit) `  <- missed this before!
-  `conda create -n py36 python=3.6`  <- generate any number of environments
-  `conda activate py36`
-  `python`   <- works OK
-  `conda env list` <- all work OK
```
# conda environments:
#
base                     C:\Users\biocodz\a01_apps\miniconda3
py36                  *  C:\Users\biocodz\a01_apps\miniconda3\envs\py36
py37                     C:\Users\biocodz\a01_apps\miniconda3\envs\py37
py39                     C:\Users\biocodz\a01_apps\miniconda3\envs\py39
```

Apparently I screwed the previous installation by incorrectly setting the PATH and other environmental variables. 
The docs mentioning the auto-generated startup script would be useful.
