### ISSUE TITLE
conda install ipython-notebook fails

### ISSUE THREAD

**Issue by bijanhoule** [conda/conda#1105]
Running on RHEL5, using the installer below:
http://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh

I've only seen this failure when trying to install ipython-notebook (I had no problems installing pandas/numpy/scipy/many other libraries)

### conda info

```
Current conda install:

             platform : linux-64
        conda version : 3.8.0
  conda-build version : not installed
       python version : 3.4.2.final.0
     requests version : 2.5.1
     root environment : /u/MPG/dramsoft/python  (writable)
  default environment : /u/MPG/dramsoft/python
     envs directories : /u/MPG/dramsoft/python/envs
        package cache : /u/MPG/dramsoft/python/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

### Traceback 

This is the traceback when issuing `conda install ipython-notebook`:

```
Traceback (most recent call last):
  File "/u/MPG/dramsoft/python/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/install.py", line 411, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/plan.py", line 499, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/install.py", line 575, in link
    create_meta(prefix, dist, info_dir, meta_dict)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/install.py", line 291, in create_meta
    json.dump(meta, fo, indent=2, sort_keys=True)
  File "/u/MPG/dramsoft/python/lib/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/u/MPG/dramsoft/python/lib/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/u/MPG/dramsoft/python/lib/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/u/MPG/dramsoft/python/lib/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/u/MPG/dramsoft/python/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAMmUlEQVR42t1bCXRU1Rn+Zslk39iTQIhEiIgIyJIYKpEClkKlgEcWKdTWag9yoKKR3YJH23gOgpyjpoJg7MmpJWoObVUkKpStgAiyhYRAEhJIAmQhk8lkMut7/e+d9SUzk8kyIfGfc89b75v7f/ff330yURTRFsmItmzZ
Irt8+bIMfqRRo0bxwdB/8a3oy+A6SbK2/uP111+Xa7XaYIvFEkWHgf4aiEKhEAVBMMvlcgPtG+rr602xsbHmqqoqkbb2QQoMnK4Epk0AVq1aFUj00MiRI181m81hdEruB/7F5ubmgQS0XqPRXKD/OUetnADRERhGBgxt9QSONiAgQKPT6fR9+/a1dAUgbQEgW7t2bRgNYP6GDRuyoqKi/KYCRqMRdXV1q
KysRENDg1hdXc1AEek/jQaDoaG8vLzozp0739J486ndoS4aAqORAULSoiMps
   
   ...
   lots more like this
   ...

sCg7Hxg30SAAR3XgBOLyBXqnweks5glhyrFP40gi2tuAd6ICEWsbIah1jXBsXjx/yi1hLgwQsoAkNRWlbu03gKS29KnjEmaZgfVaCFq/JGbz7/JElBs3VGFQHYvGe/SzostkqGWtqBy8W+AXC13Gn0jE31GDE80c8SYIsFhDZS1tj+0UgKbXIw1RSRgO+O/+AxHXb1Duz6d2eLfRrP/wqcK0TMjXX2Fed
+lADB96rNm3+cB3OzxirutPL+rb1HHP2FllIkSYcFXFGzJbEar88/X1yFar1T6QcFaD0unugiCZAOsi2KCqfFTDEKx4ybo++DIFO4zSfEFtUiRUgUVmR4XkfQpDdh464vHceGhhpkrP5tN2SDkqJm2122kBRYdPWSQoe9f4uKiCMIshjZOz8LChrDMD99B5qNUktfVdeIuRs/wi2XSDvGXIFHaVm9f7NB
UWxR1Gzb5wSpAvCLkdHIKzW59LVJAARpMmSbfWPjXST1V6LM1BdlzSGY/NIehMv1GBgZTO8PTZQpsizTKepN5efxccaL3VMQkVZufYu71z07B2LTXYkLbF36kkaHf39jJaKabS6O9LpRDEaxGjbmnX3M10/iqx0v42GXt8d+k4C46EBorhy3qgLNXvjjs31DWi7D79OG4f29ebZ8wjrl8f2cX+IN7R8Oc
6V1LbLcoKXX7ioc+ugNvLHjQ3zz/WXUGmiJLqXZcmUg9HfJ8murMSomBHv+uaNDq0Q7BMCs1DG8dYSenTudN0+0eNZjvLWKKl96Hq+xLJLsxqVL+SguKcXECbPYJzP3tija3cQWZIwZ8zBv3VoWb49f7W0kb9vgcVNv8Nna9SyJsdDkmTqsAmzmV68ebaZlMNdpqTurOwfCzx9QdhXR2AX6ZKaatrRYtd
5jxNbmt8PsszP6Hi+MVmn1p4VRQb1l9tnH2ERNtL6gZuvWrTpPEizzsX4mY19eefv4qCcSfe4vfvbZZ4K3j6v/D2MaIsFRjzzjAAAAAElFTkSuQmCC' is not JSON serializable
```

## Subsequent fails?

After the failing `conda install ipython-notebook`, conda starts failing on commands that previously worked.  E.g. `conda update conda` gives the following traceback:

```
Traceback (most recent call last):
  File "/u/MPG/dramsoft/python/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/install.py", line 262, in install
    for dist in linked]
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/cli/install.py", line 262, in <listcomp>
    for dist in linked]
  File "/u/MPG/dramsoft/python/lib/python3.4/site-packages/conda/install.py", line 488, in is_linked
    return json.load(fi)
  File "/u/MPG/dramsoft/python/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/u/MPG/dramsoft/python/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/u/MPG/dramsoft/python/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/u/MPG/dramsoft/python/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 25 column 15 (char 515)

```

**Comment by bijanhoule** [comment]
Turns out this was an issue on my side :)

I had a second anaconda distribution in my $PATH  (e.g. PATH="$conda1:$conda2:$otherStuff").  This was causing the issue above when I was working on $conda1 -- when I removed $conda2 from my path everything worked fine.

**Comment by asmeurer** [comment]
This was actually a bug that we just fixed today.
