### ISSUE TITLE
Conda activation fails on Windows if the path contains unicode

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#11064]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
Reported by wolfv on https://github.com/mamba-org/mamba/issues/1201#issuecomment-980072605.

I'll also add that creating the prefix mentioned in that issue is _not_ viable via CMD:

```
> conda create -p D:\Users\jrodriguez\1036áγђß家固êôōçñ한\ python
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\Users\jrodriguez\1036á??ß??êôoçñ?

  added / updated specs:
    - python


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libzlib            conda-forge/win-64::libzlib-1.2.11-h8ffe710_1013
  openssl            conda-forge/win-64::openssl-3.0.0-h8ffe710_2
  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.10.0-hcf16a7b_3_cpython
  python_abi         conda-forge/win-64::python_abi-3.10-2_cp310
  setuptools         conda-forge/win-64::setuptools-59.2.0-py310h5588dad_0
  sqlite             conda-forge/win-64::sqlite-3.36.0-h8ffe710_2
  tk                 conda-forge/win-64::tk-8.6.11-h8ffe710_1
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_5
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_5
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1


Proceed ([y]/n)? y

Preparing transaction: failed

CondaError: Unable to create prefix directory 'D:\Users\jrodriguez\1036á??ß??êôoçñ?'.
Check that you have sufficient permissions.
```

It's not a permissions issue, because if you try without all the unicode stuff, it can be created.

A limited subset is possible though:

```
>conda create -n Aunicodestringñ python
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: D:\Users\jrodriguez\conda\envs\Aunicodestringñ

  added / updated specs:
    - python


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2021.10.8-h5b45459_0
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libzlib            conda-forge/win-64::libzlib-1.2.11-h8ffe710_1013
  openssl            conda-forge/win-64::openssl-3.0.0-h8ffe710_2
  pip                conda-forge/noarch::pip-21.3.1-pyhd8ed1ab_0
  python             conda-forge/win-64::python-3.10.0-hcf16a7b_3_cpython
  python_abi         conda-forge/win-64::python_abi-3.10-2_cp310
  setuptools         conda-forge/win-64::setuptools-59.2.0-py310h5588dad_0
  sqlite             conda-forge/win-64::sqlite-3.36.0-h8ffe710_2
  tk                 conda-forge/win-64::tk-8.6.11-h8ffe710_1
  tzdata             conda-forge/noarch::tzdata-2021e-he74cb21_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_5
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_5
  wheel              conda-forge/noarch::wheel-0.37.0-pyhd8ed1ab_1
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1


Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate Aunicodestringñ
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) D:\Users\jrodriguez>conda activate Aunicodestringñ

(Aunicodestring├▒) D:\Users\jrodriguez>
```

but the PS1 gets funky :D

### Conda info
```shell
conda info

     active environment : base
    active env location : D:\Users\jrodriguez\conda
            shell level : 1
       user config file : D:\Users\jrodriguez\.condarc
 populated config files : D:\Users\jrodriguez\conda\.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : D:\Users\jrodriguez\conda  (writable)
      conda av data dir : D:\Users\jrodriguez\conda\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\Users\jrodriguez\conda\pkgs
                          D:\Users\jrodriguez\.conda\pkgs
                          D:\Users\jrodriguez\AppData\Local\conda\conda\pkgs
       envs directories : D:\Users\jrodriguez\conda\envs
                          D:\Users\jrodriguez\.conda\envs
                          D:\Users\jrodriguez\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda config
```shell
conda config --show-sources
==> D:\Users\jrodriguez\conda\.condarc <==
channels:
  - conda-forge
```

### Conda list
```shell
>conda list --show-channel-urls
# packages in environment at D:\Users\jrodriguez\conda:
#
# Name                    Version                   Build  Channel
anaconda-client           1.8.0            py39haa95532_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.10.0             pyh06a4308_0    defaults
brotlipy                  0.7.0           py39hb82d6ee_1001    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.7.5             haa95532_1    defaults
certifi                   2021.5.30        py39haa95532_0    defaults
cffi                      1.14.6           py39h0878f49_1    conda-forge
chardet                   4.0.0           py39haa95532_1003    defaults
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.1              pyhd3eb1b0_0    defaults
clyent                    1.2.2            py39haa95532_1    defaults
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.10.3.post137+738d862ca           dev_0    <develop>
conda-build               3.21.5           py39haa95532_0    defaults
conda-package-handling    1.7.3            py39h8cc25b3_1    defaults
conda-verify              3.4.2                      py_1    defaults
coverage                  5.5              py39h2bbff1b_2    defaults
cryptography              3.4.7            py39hd8d06c1_0    conda-forge
cytoolz                   0.11.0           py39h2bbff1b_0    defaults
execnet                   1.9.0              pyhd3eb1b0_0    defaults
filelock                  3.0.12             pyhd3eb1b0_1    defaults
flake8                    3.9.2              pyhd3eb1b0_0    defaults
future                    0.18.2           py39haa95532_1    defaults
git                       2.32.0               haa95532_1    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
idna                      3.1                pyhd3deb0d_0    conda-forge
importlib-metadata        4.8.1            py39haa95532_0    defaults
importlib_metadata        4.8.1                hd3eb1b0_0    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter_core              4.7.1            py39haa95532_0    defaults
krb5                      1.19.2               hbae68bd_2    conda-forge
libarchive                3.5.2                hb45042f_1    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblief                   0.10.1               hd77b12b_1    defaults
libsolv                   0.7.19               h7755175_5    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
lzo                       2.10              he774522_1000    conda-forge
mamba                     0.16.0           py39h006a82b_0    conda-forge
markupsafe                2.0.1            py39h2bbff1b_0    defaults
mccabe                    0.6.1            py39haa95532_1    defaults
menuinst                  1.4.18           py39hcbf5309_0    conda-forge
miniforge_console_shortcut 1.0                  h57928b3_0    conda-forge
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.8.0              pyhd3eb1b0_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
openssl                   1.1.1l               h2bbff1b_0    defaults
packaging                 21.0               pyhd3eb1b0_0    defaults
perl                      5.26.2.1             h0c8e037_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pip                       21.2.4           py38haa95532_0    defaults
pkginfo                   1.7.1            py39haa95532_0    defaults
pluggy                    0.13.1           py39haa95532_0    defaults
psutil                    5.8.0            py39h2bbff1b_1    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
py                        1.10.0             pyhd3eb1b0_0    defaults
py-lief                   0.10.1           py39hd77b12b_1    defaults
pycodestyle               2.7.0              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py39h2bbff1b_0    defaults
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycrypto                  2.6.1           py39h2bbff1b_10    defaults
pyflakes                  2.3.1              pyhd3eb1b0_0    defaults
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyhd3eb1b0_0    defaults
pyrsistent                0.18.0           py39h2bbff1b_0    defaults
pysocks                   1.7.1            py39hcbf5309_3    conda-forge
pytest                    6.2.4            py39haa95532_2    defaults
pytest-cov                2.12.1             pyhd3eb1b0_0    defaults
pytest-forked             1.3.0              pyhd3eb1b0_0    defaults
pytest-mock               3.6.1              pyhd3eb1b0_0    defaults
pytest-rerunfailures      10.1               pyhd3eb1b0_0    defaults
pytest-split              0.3.3              pyhd8ed1ab_0    conda-forge
pytest-timeout            1.4.2                      py_0    defaults
pytest-xdist              2.3.0              pyhd3eb1b0_0    defaults
python                    3.9.7           h7840368_2_cpython    conda-forge
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1             pyhd3eb1b0_0    defaults
pywin32                   301              py39hb82d6ee_0    conda-forge
pyyaml                    5.4.1            py39h2bbff1b_1    defaults
reproc                    14.2.3               h8ffe710_0    conda-forge
reproc-cpp                14.2.3               h0e60522_0    conda-forge
requests                  2.26.0             pyhd3eb1b0_0    defaults
responses                 0.13.3             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py39h2bbff1b_0    defaults
setuptools                58.0.4           py39hcbf5309_2    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.2.1              pyhd3eb1b0_0    defaults
sqlite                    3.36.0               h8ffe710_2    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
toml                      0.10.2             pyhd3eb1b0_0    defaults
toolz                     0.11.1             pyhd3eb1b0_0    defaults
tqdm                      4.62.3             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.0              pyhd3eb1b0_0    defaults
tzdata                    2021a                he74cb21_1    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                he774522_0    conda-forge
zipp                      3.5.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11            h62dcd97_1010    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```

**Comment by ncoghlan** [comment]
With a recent conda version, I was able to create such an env (from Powershell, not CMD), but trying to use it still didn't work.

I intentionally added '🐸' to the build folder name to ensure that installation paths with non-ASCII characters would work correctly, and found that they failed with this error:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Work\Miniforge3\lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "D:\Work\Miniforge3\lib\site-packages\conda\cli\main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
      File "D:\Work\Miniforge3\lib\site-packages\conda\cli\conda_argparse.py", line 199, in do_call
        result = getattr(module, func_name)(args, parser)
      File "D:\Work\Miniforge3\lib\site-packages\conda\cli\main_run.py", line 117, in execute
        print(response.stdout, file=sys.stdout)
      File "D:\Work\Miniforge3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\ufffd' in position 31: character maps to <undefined>

`$ D:\Work\Miniforge3\Scripts\conda-script.py run --prefix S:\Work\_build_win64🐸\runtime where python`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=D:\Work\Miniforge3\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Work\Miniforge3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=D:\Work\Miniforge3
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\Alyssa
               LD_PRELOAD=<not set>
                     PATH=C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\
                          WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\W
                          INDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System3
                          2\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL
                          Server\90\Tools\binn\;C:\Program Files\Git\cmd;C:\Program Files
                          (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Users\Alyssa\AppDa
                          ta\Local\Microsoft\WindowsApps;C:\Users\Alyssa\AppData\Local\Programs\Mi
                          crosoft VS Code\bin;D:\Work\Miniforge3\condabin;C:\Program
                          Files\Git\bin;C:\Users\Alyssa\.dotnet\tools
             PSMODULEPATH=C:\Users\Alyssa\Documents\WindowsPowerShell\Modules;C:\Program Files\Win
                          dowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modu
                          les
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=D:\VirtualBox\

     active environment : None
       user config file : C:\Users\Alyssa\.condarc
 populated config files : D:\Work\Miniforge3\.condarc
          conda version : 24.3.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.3.0=0
                          __cuda=12.4=0
                          __win=0=0
       base environment : D:\Work\Miniforge3  (writable)
      conda av data dir : D:\Work\Miniforge3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : D:\Work\Miniforge3\pkgs
                          C:\Users\Alyssa\.conda\pkgs
                          C:\Users\Alyssa\AppData\Local\conda\conda\pkgs
       envs directories : D:\Work\Miniforge3\envs
                          C:\Users\Alyssa\.conda\envs
                          C:\Users\Alyssa\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.3.0 requests/2.31.0 CPython/3.10.14 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>
```

**Comment by xky0007** [comment]
Same problem still exists. When I add a new env with unicode, the error occured.

**Comment by eric-gitta-moore** [comment]
After some searching and attempts on my part, I resolved the error by adding the following line to the `.condarc` file in the user directory of the C drive (if the file doesn't exist, you can create a new one).  

```condarc
# Instructs the Python interpreter to use UTF-8 encoding by default when processing text data  
export PYTHONUTF8=1  
```

ref: https://blog.gujiakai.top/2023/09/conda-activation-error-unicode-decode-gbk/

**Comment by ZJRui** [comment]
> After some searching and attempts on my part, I resolved the error by adding the following line to the `.condarc` file in the user directory of the C drive (if the file doesn't exist, you can create a new one).经过我的一些搜索和尝试，我通过在 C 盘用户目录中的 `.condarc` 文件中添加以下行解决了错误（如果该文件不存在，可以创建一个新的）。
> 
> ```
> # Instructs the Python interpreter to use UTF-8 encoding by default when processing text data  
> export PYTHONUTF8=1  
> ```
> 
> in powershell. just  在 powershell 中。只需
> 
> $env:PYTHONUTF8=1
> or wirte it in `$PROFILE.CurrentUserAllHosts`或者将其写入 `$PROFILE.CurrentUserAllHosts`
> 
> ref: https://blog.gujiakai.top/2023/09/conda-activation-error-unicode-decode-gbk/参考： [https](https://blog.gujiakai.top/2023/09/conda-activation-error-unicode-decode-gbk/) ://blog.gujiakai.top/2023/09/conda-activation-error-unicode-decode-gbk/

The.condarc is a file in YAML format. How to configure `export PYTHONUTF8=1`?

**Comment by mutecamel** [comment]
In `~/.bash_profile` file, *before* the line `>>> conda initialize >>>`, input the line `export PYTHONUTF8=1`, fixes the error.
