### ISSUE TITLE
Warn about duplicate conda/pip packages in environment.yaml file

### ISSUE THREAD

**Issue by rbavery** [conda/conda#11103]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
I can't import pandas with a conda env that builds without errors. ideally I'd be able to import pandas if the environment builds successfully.

to reproduce, use this env file https://github.com/drivendataorg/cloud-cover-runtime/blob/main/runtime/environment-gpu.yml:

```
mamba env create -f environment-gpu.yaml
```

it installs but then it fails when importing pandas

```python
import pandas

ImportError: cannot import name 'DtypeArg' from 'pandas._typing' (/home/rave/miniconda3/envs/condaenv/lib/python3.9/site-packages/pandas/_typing.py)
```

this looks related to this issue, but I think it's an issue ultimately with how conda or pip handles pandas being specified as a dependency for conda packages and pip packages at the same time.

https://github.com/pandas-dev/pandas/issues/42506

My workaround was to remove pandas from the conda section in the environment file (removing pandas=1.3.1). It'd be nice if conda could check for duplicate pip and and conda versions of the same package and possibly just default to pip with a warning to the user. Or at least warn the user which version of the duplicate package is being used by the environment, I wasn't sure if it was conda or pip and it turned out the conda version was being used but the older pip version of pandas is what worked when importing.

### Conda info
<details>
<summary><code>conda info</code></summary>

```shell
→ conda info                              

     active environment : base
    active env location : /home/rave/miniconda3
            shell level : 1
       user config file : /home/rave/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __cuda=11.3=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rave/miniconda3  (writable)
      conda av data dir : /home/rave/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rave/miniconda3/pkgs
                          /home/rave/.conda/pkgs
       envs directories : /home/rave/miniconda3/envs
                          /home/rave/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.5 Linux/5.4.0-91-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/rave/.netrc
           offline mode : False
```

</details>

### Conda list
<details>
<summary><code>conda list --show-channel-urls</code></summary>

```shell
→ conda list --show-channel-urls
# packages in environment at /home/rave/miniconda3/envs/condaenv:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
abseil-cpp                20210324.2           h9c3ff4c_0    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
addict                    2.4.0                    pypi_0    pypi
affine                    2.3.0                      py_0    conda-forge
aiohttp                   3.8.1            py39h3811e60_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
albumentations            1.0.3                      py_0    fastai
alsa-lib                  1.2.3                h516909a_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.1.0           py39h3811e60_2    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.1              pyhd8ed1ab_0    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
azure-core                1.21.1                   pypi_0    pypi
azure-storage-blob        12.9.0                   pypi_0    pypi
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.4.2            py39hf3d152e_0    conda-forge
boost-cpp                 1.74.0               h312852a_4    conda-forge
brotli                    1.0.9                h7f98852_6    conda-forge
brotli-bin                1.0.9                h7f98852_6    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
c-blosc2                  2.0.4                h5f21a17_1    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
catalogue                 2.0.6            py39hf3d152e_1    conda-forge
catboost                  0.26.1           py39hf3d152e_0    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
charls                    2.2.0                h9c3ff4c_0    conda-forge
charset-normalizer        2.0.9              pyhd8ed1ab_0    conda-forge
clang                     5.0                      pypi_0    pypi
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpathlib              0.6.2                    pypi_0    pypi
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
crfseg                    1.0.0                    pypi_0    pypi
cryptography              36.0.0           py39h95dcef6_0    conda-forge
cudatoolkit               11.1.74              h6bb024c_0    nvidia
cudnn                     8.2.1.32             h86fa8c9_0    conda-forge
curl                      7.80.0               h2574ce0_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cymem                     2.0.6            py39he80948d_2    conda-forge
cython-blis               0.7.5            py39hce5d2b2_1    conda-forge
cytoolz                   0.11.2           py39h3811e60_1    conda-forge
dask                      2021.12.0          pyhd8ed1ab_0    conda-forge
dask-core                 2021.12.0          pyhd8ed1ab_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.6               h48d8840_2    conda-forge
debugpy                   1.5.1            py39he80948d_0    conda-forge
decorator                 5.1.0              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2021.12.0        py39hf3d152e_0    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docstring-parser          0.13                     pypi_0    pypi
efficientnet              1.0.0                    pypi_0    pypi
efficientnet-pytorch      0.6.3              pyh9f0ad1d_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
fastai                    2.5.0                      py_0    fastai
fastcore                  1.3.26                     py_0    fastai
fastdownload              0.0.5                      py_0    fastai
fastprogress              1.0.0              pyh39e3cac_0    fastai
fontconfig                2.13.1            hba837de_1005    conda-forge
fonttools                 4.28.3           py39h3811e60_0    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
frozenlist                1.2.0            py39h3811e60_1    conda-forge
fsspec                    2021.11.1          pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hf3d152e_4    conda-forge
gast                      0.4.0                    pypi_0    pypi
geos                      3.9.1                h9c3ff4c_2    conda-forge
geotiff                   1.6.0                h4f31c25_6    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.70.2               h780b84a_0    conda-forge
glib-tools                2.70.2               h780b84a_0    conda-forge
google-auth               1.35.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
grpc-cpp                  1.37.1               hfc4d69e_3    conda-forge
grpcio                    1.37.1           py39hff7568b_0    conda-forge
gst-plugins-base          1.18.5               hf529b03_2    conda-forge
gstreamer                 1.18.5               h9f60fe5_2    conda-forge
h5py                      3.1.0                    pypi_0    pypi
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
image-classifiers         1.0.0                    pypi_0    pypi
imagecodecs               2021.8.26        py39h44211f0_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        4.8.2            py39hf3d152e_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 6.6.0            py39hef51801_0    conda-forge
ipython                   7.30.1           py39hf3d152e_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd8ed1ab_0    conda-forge
isodate                   0.6.1                    pypi_0    pypi
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1           py39hf3d152e_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
jsonargparse              4.1.0                    pypi_0    pypi
jsonschema                4.2.1              pyhd8ed1ab_1    conda-forge
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.1            py39hf3d152e_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.2              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kealib                    1.4.14               hcc255d8_2    conda-forge
keras                     2.7.0                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.2            py39h1a9c180_1    conda-forge
kornia                    0.5.3                    pypi_0    pypi
krb5                      1.19.2               hcc1bbae_3    conda-forge
langcodes                 3.3.0              pyhd8ed1ab_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libaec                    1.0.6                h9c3ff4c_0    conda-forge
libblas                   3.9.0                     8_mkl    conda-forge
libbrotlicommon           1.0.9                h7f98852_6    conda-forge
libbrotlidec              1.0.9                h7f98852_6    conda-forge
libbrotlienc              1.0.9                h7f98852_6    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.80.0               h2574ce0_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgdal                   3.3.1                h8f005ca_1    conda-forge
libgfortran-ng            11.2.0              h69a702a_11    conda-forge
libgfortran5              11.2.0              h5c6108e_11    conda-forge
libglib                   2.70.2               h174f98d_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1014    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnetcdf                 4.8.0           nompi_hcd642e3_103    conda-forge
libnghttp2                1.43.0               h812cca2_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libprotobuf               3.15.8               h780b84a_1    conda-forge
librttopo                 1.1.0                h1185371_6    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libspatialite             5.0.1                h8694cbe_6    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.1                h7f98852_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzip                    1.8.0                h4de3113_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
lightning-bolts           0.4.0                    pypi_0    pypi
lightning-flash           0.5.0                    pypi_0    pypi
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
llvmlite                  0.37.0           py39h1bbdace_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
loguru                    0.5.3            py39hf3d152e_3    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
magma                     2.5.4                ha9b7cf9_2    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.0.1            py39h3811e60_1    conda-forge
matplotlib                3.5.1            py39hf3d152e_0    conda-forge
matplotlib-base           3.5.1            py39h2fa2bec_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h3811e60_1005    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mmcv-full                 1.3.9                    pypi_0    pypi
mmsegmentation            0.16.0                   pypi_0    pypi
more-itertools            8.12.0             pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.3            py39h1a9c180_0    conda-forge
msrest                    0.6.21                   pypi_0    pypi
multidict                 5.2.0            py39h3811e60_1    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
murmurhash                1.0.6            py39he80948d_2    conda-forge
mysql-common              8.0.27               ha770c72_2    conda-forge
mysql-libs                8.0.27               hfa10184_2    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.3.0            py39hf3d152e_1    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nccl                      2.11.4.1             h97a9cb7_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
ninja                     1.10.2               h4bd325d_1    conda-forge
notebook                  6.4.6              pyha770c72_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.73                 hb5efdd6_0    conda-forge
numba                     0.54.1           py39h56b8d98_0    conda-forge
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.1.1              pyhd8ed1ab_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
opencv-python-headless    4.5.4.60                 py39_0    fastai
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.2.5                    pypi_0    pypi
pandas-path               0.3.0                    pypi_0    pypi
pandoc                    2.16.2               h7f98852_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pathy                     0.6.1              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.2.0            py39hf95b381_1    conda-forge
pip                       20.3.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
planetary-computer        0.4.2                    pypi_0    pypi
pluggy                    0.13.1           py39hf3d152e_4    conda-forge
pooch                     1.5.2              pyhd8ed1ab_0    conda-forge
poppler                   21.03.0              h93df280_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.5                 h2510834_1    conda-forge
preshed                   3.0.6            py39he80948d_1    conda-forge
pretrainedmodels          0.7.4              pyhd8ed1ab_2    conda-forge
prettytable               2.4.0                    pypi_0    pypi
proj                      8.0.1                h277dcde_0    conda-forge
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
protobuf                  3.15.8           py39he80948d_0    conda-forge
psutil                    5.8.0            py39h3811e60_2    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.8.2            py39h3811e60_2    conda-forge
pydap                     3.2.2           pyh9f0ad1d_1001    conda-forge
pydeprecate               0.3.1              pyhd8ed1ab_0    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pygeos                    0.10.1           py39ha61afbd_0    conda-forge
pygments                  2.10.0             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pyopenssl                 21.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyproj                    3.3.0            py39ha9a7ae0_0    conda-forge
pyqt                      5.12.3           py39hf3d152e_8    conda-forge
pyqt-impl                 5.12.3           py39hde8b62d_8    conda-forge
pyqt5-sip                 4.19.18          py39he80948d_8    conda-forge
pyqtchart                 5.12             py39h0fcd23e_8    conda-forge
pyqtwebengine             5.12.1           py39h0fcd23e_8    conda-forge
pyrsistent                0.18.0           py39h3811e60_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
pystac                    1.2.0              pyhd8ed1ab_0    conda-forge
pystac-client             0.3.1              pyhd8ed1ab_0    conda-forge
pystiche                  1.0.1                    pypi_0    pypi
pytest                    6.2.4            py39hf3d152e_0    conda-forge
python                    3.9.7           hb7a2778_3_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-dotenv             0.19.2                   pypi_0    pypi
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytorch                   1.8.0           cuda111py39h37e5b68_1    conda-forge
pytorch-lightning         1.4.1              pyhd8ed1ab_0    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pywavelets                1.2.0            py39hce5d2b2_1    conda-forge
pyyaml                    6.0              py39h3811e60_3    conda-forge
pyzmq                     22.3.0           py39h37b5a0c_1    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
rasterio                  1.2.6            py39hbc4e497_2    conda-forge
re2                       2021.08.01           h9c3ff4c_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
scikit-image              0.18.2           py39hde0f152_0    conda-forge
scikit-learn              0.24.2           py39h7c5d8c9_1    conda-forge
scipy                     1.7.1            py39hee8e79c_0    conda-forge
segmentation-models       1.0.1                    pypi_0    pypi
segmentation-models-pytorch 0.2.0              pyhd8ed1ab_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                59.4.0           py39hf3d152e_0    conda-forge
shapely                   1.7.1            py39ha61afbd_5    conda-forge
shellingham               1.4.0              pyh44b312d_0    conda-forge
six                       1.15.0                   pypi_0    pypi
sleef                     3.5.1                h9b69904_2    conda-forge
smart_open                5.2.1              pyhd8ed1ab_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
spacy                     3.2.0            py39h5472131_0    conda-forge
spacy-legacy              3.0.8              pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
srsly                     2.4.2            py39he80948d_1    conda-forge
stackstac                 0.2.2              pyhd8ed1ab_0    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.4.1            py39hf3d152e_0    conda-forge
tensorflow-base           2.4.1            py39h23a8cbf_0    conda-forge
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-gpu            2.6.0                    pypi_0    pypi
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.12.1           py39hf3d152e_1    conda-forge
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
thinc                     8.0.13           py39h5472131_0    conda-forge
threadpoolctl             3.0.0              pyh8a188c0_0    conda-forge
tifffile                  2021.8.8           pyhd8ed1ab_0    conda-forge
tiledb                    2.3.2                he87e0bf_0    conda-forge
timm                      0.4.12                     py_0    fastai
tk                        8.6.11               h27826a3_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
torchmetrics              0.5.0                    pypi_0    pypi
torchvision               0.9.1           py39cuda111hcd06603_1_cuda    conda-forge
tornado                   6.1              py39h3811e60_2    conda-forge
tqdm                      4.62.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
ttach                     0.0.3                    pypi_0    pypi
typer                     0.3.2              pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                hd8ed1ab_0    conda-forge
typing_extensions         4.0.1              pyha770c72_0    conda-forge
tzcode                    2021e                h7f98852_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.7             pyhd8ed1ab_0    conda-forge
wasabi                    0.9.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
webob                     1.8.7              pyhd8ed1ab_0    conda-forge
werkzeug                  2.0.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
widgetsnbextension        3.5.2            py39hf3d152e_1    conda-forge
wrapt                     1.12.1                   pypi_0    pypi
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h9d8b166_3    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
yapf                      0.31.0                   pypi_0    pypi
yarl                      1.7.2            py39h3811e60_1    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zfp                       0.5.5                h9c3ff4c_8    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.6.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.0                ha95c52a_0    conda-forge
```

</details>

**Comment by arvinnick** [comment]
Hello everyone

I just started contributing and when I build the conda environment using the yaml file, I can't import pandas:
```
Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.14.0 -- An enhanced Interactive Python. Type '?' for help.
PyDev console: using IPython 8.14.0
Python 3.10.11 | packaged by conda-forge | (main, May 10 2023, 18:58:44) [GCC 11.3.0] on linux
runfile('/home/arvin/PycharmProjects/pandas-arvin/issue_test.py', wdir='/home/arvin/PycharmProjects/pandas-arvin')
Traceback (most recent call last):
  File "/home/arvin/anaconda3/envs/pandas-dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3508, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3d2d0618bff5>", line 1, in <module>
    runfile('/home/arvin/PycharmProjects/pandas-arvin/issue_test.py', wdir='/home/arvin/PycharmProjects/pandas-arvin')
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/arvin/PycharmProjects/pandas-arvin/issue_test.py", line 4, in <module>
    import pandas as pd
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/arvin/PycharmProjects/pandas-arvin/pandas/__init__.py", line 46, in <module>
    from pandas.core.api import (
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/arvin/PycharmProjects/pandas-arvin/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/arvin/PycharmProjects/pandas-arvin/pandas/_libs/__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # noqa: E501 # isort: skip # type: ignore[reportUnusedImport]
  File "/opt/pycharm-2023.1.2/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'

```
I can't uninstall and install pandas since I have to keep the dev version, I think? Can you please help me?
I'm a newbie, so please tolerate if my request doesn't meet the standards. Thanks.

**Comment by manu1dcb** [comment]
Hello. Could you finally fix it? Thanks
