### ISSUE TITLE
After upgrading Navigator to 2.1.1 Spyder 5.1.5 fails to load

### ISSUE THREAD

**Issue by chuckf201** [conda/conda#11106]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I expect anaconda to successfully launch spyder

### Conda info

```shell
(base) PS C:\Users\monro> conda info

     active environment : base
    active env location : C:\Users\monro\anaconda3
            shell level : 1
       user config file : C:\Users\monro\.condarc
 populated config files : C:\Users\monro\.condarc
          conda version : 4.11.0
    conda-build version : 3.21.7
         python version : 3.8.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\monro\anaconda3  (writable)
      conda av data dir : C:\Users\monro\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\monro\anaconda3\pkgs
                          C:\Users\monro\.conda\pkgs
                          C:\Users\monro\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\monro\anaconda3\envs
                          C:\Users\monro\.conda\envs
                          C:\Users\monro\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.8.12 Windows/10 Windows/10.0.19043
          administrator : True
             netrc file : None
           offline mode : False
```

### Conda config

```shell
(base) PS C:\Users\monro> conda info

     active environment : base
    active env location : C:\Users\monro\anaconda3
            shell level : 1
       user config file : C:\Users\monro\.condarc
 populated config files : C:\Users\monro\.condarc
          conda version : 4.11.0
    conda-build version : 3.21.7
         python version : 3.8.12.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\monro\anaconda3  (writable)
      conda av data dir : C:\Users\monro\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\monro\anaconda3\pkgs
                          C:\Users\monro\.conda\pkgs
                          C:\Users\monro\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\monro\anaconda3\envs
                          C:\Users\monro\.conda\envs
                          C:\Users\monro\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.8.12 Windows/10 Windows/10.0.19043
          administrator : True
             netrc file : None
           offline mode : False
```

### Conda list

```shell
(base) PS C:\Users\monro> conda list --show-channel-urls
# packages in environment at C:\Users\monro\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
absl-py                   0.15.0                   pypi_0    pypi
alabaster                 0.7.12                     py_0    anaconda
anaconda-client           1.9.0            py38haa95532_0    defaults
anaconda-navigator        2.1.1                    py38_0    defaults
anyio                     2.2.0            py38haa95532_2    defaults
appdirs                   1.4.4                      py_0    anaconda
argh                      0.26.2                   py38_0    anaconda
argon2-cffi               20.1.0           py38h2bbff1b_1    defaults
arrow                     1.2.1                    pypi_0    pypi
astroid                   2.4.2                    py38_0    anaconda
async_generator           1.10               pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    anaconda
attrs                     21.2.0             pyhd3eb1b0_0    defaults
autopep8                  1.5.5                    pypi_0    pypi
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.0                pyhd3eb1b0_2    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
bcrypt                    3.2.0            py38he774522_0    anaconda
beautifulsoup4            4.10.0             pyh06a4308_0    defaults
binaryornot               0.4.4              pyhd3eb1b0_1    defaults
black                     19.10b0                    py_0    anaconda
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
bottleneck                1.3.2            py38h2a96729_1    defaults
brotli                    1.0.9                ha925a31_2    defaults
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2020.10.14                    0    anaconda
cachetools                4.2.4                    pypi_0    pypi
certifi                   2020.6.20                py38_0    anaconda
cffi                      1.15.0           py38h2bbff1b_0    defaults
chardet                   4.0.0           py38haa95532_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
clang                     5.0                      pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                      py_0    anaconda
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.11.0           py38haa95532_0    defaults
conda-build               3.21.7           py38haa95532_1    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.7.3            py38h8cc25b3_1    defaults
conda-repo-cli            1.0.4              pyhd3eb1b0_0    defaults
conda-token               0.3.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
cookiecutter              1.7.3                    pypi_0    pypi
cryptography              3.4.8            py38h71e12ea_0    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
debugpy                   1.5.1            py38hd77b12b_0    defaults
decorator                 5.1.0              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713                   py_0    anaconda
docutils                  0.16                     py38_1    anaconda
entrypoints               0.3                      py38_0    defaults
filelock                  3.4.0              pyhd3eb1b0_0    defaults
flake8                    3.8.4                    pypi_0    pypi
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
fredapi                   0.4.2                      py_0    conda-forge
freetype                  2.10.4               hd328e21_0    defaults
future                    0.18.2                   py38_1    defaults
gast                      0.4.0                    pypi_0    pypi
glob2                     0.7                pyhd3eb1b0_0    defaults
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
grpcio                    1.41.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
icu                       58.2                 ha925a31_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
imagesize                 1.2.0                      py_0    anaconda
importlib-metadata        4.8.2            py38haa95532_0    defaults
importlib_metadata        4.8.2                hd3eb1b0_0    defaults
inflection                0.5.1            py38haa95532_0    defaults
intel-openmp              2021.4.0          haa95532_3556    defaults
intervaltree              3.1.0                      py_0    anaconda
ipykernel                 6.4.1            py38haa95532_1    defaults
ipython                   7.29.0           py38hd4e2768_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
isort                     5.6.4                      py_0    anaconda
jedi                      0.18.0           py38haa95532_1    defaults
jellyfish                 0.8.9                    pypi_0    pypi
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
jinja2-time               0.2.0              pyhd3eb1b0_2    defaults
jpeg                      9d                   h2bbff1b_0    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter_client            6.1.12             pyhd3eb1b0_0    defaults
jupyter_core              4.9.1            py38haa95532_0    defaults
jupyter_server            1.4.1            py38haa95532_0    defaults
jupyterlab                3.2.1              pyhd3eb1b0_1    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.8.2              pyhd3eb1b0_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
keras                     2.6.0            py39hd3eb1b0_0    defaults
keyring                   21.4.0                   py38_1    anaconda
kiwisolver                1.3.1            py38hd77b12b_0    defaults
lazy-object-proxy         1.4.3            py38he774522_0    anaconda
libarchive                3.4.2                h5e25573_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.10.1               ha925a31_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libspatialindex           1.9.3                h33f27b4_0    anaconda
libta-lib                 0.4.0                he774522_0    conda-forge
libtiff                   4.2.0                hd0e1b90_0    defaults
libwebp                   1.2.0                h2bbff1b_0    defaults
libxml2                   2.9.12               h0ad7f3c_0    defaults
libxslt                   1.1.34               he774522_0    defaults
lxml                      4.6.3            py38h9b66d53_0    defaults
lz4-c                     1.9.3                h2bbff1b_1    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.3.4                    pypi_0    pypi
markupsafe                1.1.1            py38he774522_0    anaconda
matplotlib-base           3.5.0            py38h6214cd6_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mccabe                    0.6.1                    py38_1    anaconda
menuinst                  1.4.18           py38h59b6b97_0    defaults
mistune                   0.8.4           py38he774522_1000    defaults
mkl                       2021.4.0           haa95532_640    defaults
mkl-service               2.4.0            py38h2bbff1b_0    defaults
mkl_fft                   1.3.1            py38h277e83a_0    defaults
mkl_random                1.2.2            py38hf11a4ad_0    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
mplfinance                0.12.7a17          pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    defaults
multitasking              0.0.9              pyhd8ed1ab_0    conda-forge
munkres                   1.1.4                      py_0    defaults
mypy_extensions           0.4.3                    py38_0    anaconda
navigator-updater         0.2.1                    py38_0    defaults
nbclassic                 0.2.6              pyhd3eb1b0_0    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.1.0            py38haa95532_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
notebook                  6.4.6            py38haa95532_0    defaults
numexpr                   2.7.3            py38hb80d3ca_1    defaults
numpy                     1.19.5                   pypi_0    pypi
numpy-base                1.21.2           py38h0829f74_0    defaults
numpydoc                  1.1.0                      py_0    anaconda
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0    defaults
openssl                   1.1.1l               h2bbff1b_0    defaults
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.3.4            py38h6214cd6_0    defaults
pandas-datareader         0.10.0                   pypi_0    pypi
pandocfilters             1.4.3            py38haa95532_1    defaults
paramiko                  2.7.2                      py_0    anaconda
parso                     0.8.2              pyhd3eb1b0_0    defaults
pathspec                  0.7.0                      py_0    anaconda
pathtools                 0.1.2                      py_1    anaconda
pexpect                   4.8.0                    py38_0    anaconda
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.4.0            py38hd45dc43_0    defaults
pip                       21.3.1                   pypi_0    pypi
pkginfo                   1.7.1            py38haa95532_0    defaults
plotly                    5.1.0              pyhd3eb1b0_0    defaults
pluggy                    0.13.1                   py38_0    anaconda
powershell_shortcut       0.0.1                         3    defaults
poyo                      0.5.0              pyhd3eb1b0_0    defaults
prometheus_client         0.12.0             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.8.0            py38h2bbff1b_1    defaults
py-lief                   0.10.1           py38ha925a31_0    defaults
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydocstyle                5.1.1                      py_0    anaconda
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyjwt                     2.1.0            py38haa95532_0    defaults
pylint                    2.6.0                    py38_0    anaconda
pyls-spyder               0.4.0                    pypi_0    pypi
pynacl                    1.4.0            py38h62dcd97_1    anaconda
pyopenssl                 21.0.0             pyhd3eb1b0_1    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py38ha925a31_4    defaults
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-plugins             5.15.4.2.2               pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyqt5-tools               5.15.4.3.2               pypi_0    pypi
pyqt5designer             5.14.1                   pypi_0    pypi
pyqtgraph                 0.12.3                   pypi_0    pypi
pyqtwebengine             5.15.5                   pypi_0    pypi
pyqtwebengine-qt5         5.15.2                   pypi_0    pypi
pyrsistent                0.18.0           py38h196d8e1_0    defaults
pysocks                   1.7.1            py38haa95532_0    defaults
python                    3.8.12               h6244533_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-dotenv             0.19.2                   pypi_0    pypi
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python-lsp-black          1.0.1                    pypi_0    pypi
python-lsp-jsonrpc        1.0.0                    pypi_0    pypi
python-lsp-server         1.3.3                    pypi_0    pypi
python-slugify            4.0.1                      py_0    anaconda
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    defaults
pywin32                   228              py38hbaba5e8_1    defaults
pywin32-ctypes            0.2.0                 py38_1000    anaconda
pywinpty                  0.5.7                    py38_0    defaults
pyyaml                    6.0              py38h2bbff1b_1    defaults
pyzmq                     22.3.0           py38hd77b12b_2    defaults
qdarkstyle                3.0.2              pyhd3eb1b0_0    defaults
qstylizer                 0.2.1                    pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0    defaults
qt5-applications          5.15.2.2.2               pypi_0    pypi
qt5-tools                 5.15.2.1.2               pypi_0    pypi
qtawesome                 1.0.3              pyhd3eb1b0_0    defaults
qtconsole                 5.2.2                    pypi_0    pypi
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
quandl                    3.6.1            py38haa95532_0    defaults
regex                     2020.10.15       py38he774522_0    anaconda
requests                  2.26.0             pyhd3eb1b0_0    defaults
requests-oauthlib         1.3.0                    pypi_0    pypi
rope                      0.18.0                     py_0    anaconda
rsa                       4.7.2                    pypi_0    pypi
rtree                     0.9.7            py38h2eaa2aa_1    defaults
ruamel_yaml               0.15.100         py38h2bbff1b_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                58.0.4           py38haa95532_0    defaults
sip                       4.19.13          py38ha925a31_0    defaults
six                       1.15.0           py38haa95532_0    defaults
sniffio                   1.2.0            py38haa95532_1    defaults
snowballstemmer           2.0.0                      py_0    anaconda
sortedcontainers          2.2.2                      py_0    anaconda
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sphinx                    3.2.1                      py_0    anaconda
sphinxcontrib-applehelp   1.0.2                      py_0    anaconda
sphinxcontrib-devhelp     1.0.2                      py_0    anaconda
sphinxcontrib-htmlhelp    1.0.3                      py_0    anaconda
sphinxcontrib-jsmath      1.0.1                      py_0    anaconda
sphinxcontrib-qthelp      1.0.3                      py_0    anaconda
sphinxcontrib-serializinghtml 1.1.4                      py_0    anaconda
spyder                    5.2.0                    pypi_0    pypi
spyder-kernels            2.2.0                    pypi_0    pypi
sqlite                    3.36.0               h2bbff1b_0    defaults
ta-lib                    0.4.19           py38h347fdf6_2    conda-forge
tenacity                  8.0.1            py38haa95532_0    defaults
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorflow                2.6.1                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
termcolor                 1.1.0            py38haa95532_1    defaults
terminado                 0.9.4            py38haa95532_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
text-unidecode            1.3                        py_0    anaconda
textdistance              4.2.1              pyhd3eb1b0_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tinycss                   0.4             pyhd3eb1b0_1002    defaults
tinycss2                  1.1.0                    pypi_0    pypi
tk                        8.6.11               h2bbff1b_0    defaults
toml                      0.10.1                     py_0    anaconda
tornado                   6.1              py38h2bbff1b_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
typed-ast                 1.4.1            py38he774522_0    anaconda
typing_extensions         3.7.4.3                    py_0    anaconda
ujson                     4.0.2            py38hd77b12b_0    defaults
unidecode                 1.1.1                      py_0    anaconda
urllib3                   1.26.7             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
watchdog                  0.10.3                   py38_0    anaconda
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py38_1    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
whichcraft                0.6.1              pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1                    py38_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
wincertstore              0.2              py38haa95532_2    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.2           py38he774522_0    anaconda
xmltodict                 0.12.0             pyhd3eb1b0_0    defaults
xz                        5.2.5                h62dcd97_0    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.30.0                     py_0    anaconda
yfinance                  0.1.64             pyhd8ed1ab_0    conda-forge
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h62dcd97_4    defaults
zstd                      1.4.9                h19a0ad4_0    defaults
```

### Additional Context

spyder error message:
Traceback (most recent call last):
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\utils.py", line 281, in create_window
main.setup()
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 850, in setup
internal_plugins = find_internal_plugins()
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\find_plugins.py", line 92, in find_internal_plugins
mod = importlib.import_module(entry_point.module_name)
File "C:\Users\monro\anaconda3\lib\importlib\__init__.py", line 127, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "", line 1014, in _gcd_import
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in _load_unlocked
File "", line 843, in exec_module
File "", line 219, in _call_with_frames_removed
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\plugins\findinfiles\plugin.py", line 18, in 
from spyder.plugins.findinfiles.widgets import FindInFilesWidget
ImportError: cannot import name 'FindInFilesWidget' from 'spyder.plugins.findinfiles.widgets' (C:\Users\monro\anaconda3\lib\site-packages\spyder\plugins\findinfiles\widgets\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\monro\anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\start.py", line 237, in main
mainwindow.main(options, args)
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1992, in main
mainwindow = create_window(MainWindow, app, splash, options, args)
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\utils.py", line 283, in create_window
if main.console is not None:
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 1088, in __getattr__
return self.get_plugin(self._INTERNAL_PLUGINS_MAPPING[attr])
File "C:\Users\monro\anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 165, in get_plugin
raise SpyderAPIError(f'Plugin "{plugin_name}" not found!')
spyder.api.exceptions.SpyderAPIError: Plugin "internal_console" not found!

**Comment by chuckf201** [comment]
Solved by down grading Spyder

**Comment by uozcan12** [comment]
Is there any solution except downgrading?
