### ISSUE TITLE
Cannot create env from `environment.yaml` with pip dependencies in read-only directory

### ISSUE THREAD

**Issue by eikevons** [conda/conda#11115]
### Acceptance Criteria

- Make sure that conda writes temporary files to the appropriate place when creating the temporary "requirements.txt" file (i.e. it's own tempdir location, which can be created  using the [tempfile](https://docs.python.org/3/library/tempfile.html) module in Python)
 
### What happened?

When importing a conda environment yaml stored in a read-only directory fails if the environment contains pip dependencies. This seems to be the same error as #10066.

The problem seems to be that conda creates a temporary `requirements.txt` in the same directory as `env.yml` which fails with the following error:

<details>
<summary>Error</summary>

```
[...]
python-3.10.1        | 29.8 MB   | ########## | 100% 
libnsl-2.0.0         | 31 KB     | ########## | 100% 
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Installing pip dependencies: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 141, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/installers/pip.py", line 70, in install
        return _pip_install_via_requirements(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda_env/installers/pip.py", line 44, in _pip_install_via_requirements
        requirements = Utf8NamedTemporaryFile(mode='w',
      File "/opt/conda/lib/python3.9/site-packages/conda/_vendor/auxlib/compat.py", line 81, in Utf8NamedTemporaryFile
        return NamedTemporaryFile(mode=mode, buffering=buffering, encoding=encoding,
      File "/opt/conda/lib/python3.9/tempfile.py", line 541, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/conda/lib/python3.9/tempfile.py", line 251, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/demo/condaenv.s0z4vtvc.requirements.txt'
```

</details>

To reproduce locally, run the following commands:

```bash
sudo mkdir /tmp/roots-dir
cd /tmp/roots-dir
sudo echo "name: dummy-env
dependencies:
  - python=3.10
  - pip
  - pip:
    - rich" > /tmp/roots-dir/environment.yml
conda env create -f /tmp/roots-dir/environment.yml
```

To reproduce on Docker, use the following Dockerfile:

<details>
<summary>docker file</summary>

```dockerfile
FROM continuumio/miniconda3:4.10.3-alpine

USER root
RUN : \
 # Create demo env.yml
 && mkdir /demo \
 && echo >/demo/env.yml $'\
name: demo\n\
channels:\n\
  - conda-forge\n\
dependencies:\n\
  - pip\n\
  - pip:\n\
    - requests\n'\
 # Prepare unpriviledged user
 && adduser --disabled-password unpriviledged \
 # Make unpriviledged user own conda installation
 && chown -R unpriviledged /opt/conda

USER unpriviledged

# Collect info for issue
RUN conda info
RUN conda config --show-sources
RUN conda list --show-channel-urls

WORKDIR /home/unpriviledged
RUN conda env create -n demo --file /demo/env.yml
```

</details>

### Conda info
<details>
<summary><code>conda info</code></summary>

```shell
active environment : None
       user config file : /home/unpriviledged/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __linux=5.10.0=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/unpriviledged/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/unpriviledged/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.9.5 Linux/5.10.0-9-amd64 alpine/3.14.0 glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

### Conda list
<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
certifi                   2021.5.30        py39h06a4308_0    defaults
cffi                      1.14.6           py39h400218f_0    defaults
chardet                   4.0.0           py39h06a4308_1003    defaults
conda                     4.10.3           py39h06a4308_0    defaults
conda-package-handling    1.7.3            py39h27cfd23_1    defaults
cryptography              3.4.7            py39hd23ed53_0    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
pip                       21.1.3           py39h06a4308_0    defaults
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.5                h12debd9_4    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
tzdata                    2021a                h52ac0ba_0    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11
```

</details>

**Comment by AlexandreBrown** [comment]
Thanks for creating this issue, you made me realize that if I copy the `environment.yml` in a folder I have read/write access then I can install it without root (I was copying it to the root (`/`)).  
Putting this comment in in case it helps anyone.
