### ISSUE TITLE
h5py 3.6 installed using conda fails to import

### ISSUE THREAD

**Issue by khamyl** [conda/conda#11142]
### Checklist
* [x] I added a descriptive title
* [x] I searched for other issues and couldn't find a solution or duplication
* [x] I already searched in Google and didn't find any good information or help
* [x] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?
* **Operating System:** Windows 10
* **Python version:** 3.9.7
* **Where Python was acquired:** Miniconda on Windows
* **h5py version:** 3.6.0
* **HDF5 version:** 1.10.6
* The full traceback/stack trace shown:

```
(tf-gpu) d:\WS\Python>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\Miniconda3\envs\tf-gpu\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\...\Miniconda3\envs\tf-gpu\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
>>> 
```

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : tf-gpu
    active env location : C:\Users\X\Miniconda3\envs\tf-gpu
            shell level : 1
       user config file : C:\Users\X\.condarc
 populated config files : C:\Users\X\.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\X\Miniconda3  (writable)
      conda av data dir : C:\Users\X\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\X\Miniconda3\pkgs
                          C:\Users\X\.conda\pkgs
                          C:\Users\X\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\X\Miniconda3\envs
                          C:\Users\X\.conda\envs
                          C:\Users\X\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.10 Windows/10 Windows/10.0.18363
          administrator : False
             netrc file : None
           offline mode : False
```

</details>

### Conda config

<details>
<summary><code>conda config</code></summary>

```shell
==> C:\Users\X\.condarc <==
channels:
  - defaults
  - conda-forge
```

</details>

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at C:\Users\z0049ntw\Miniconda3\envs\tf-gpu:
#
# Name                    Version                   Build  Channel
absl-py                   1.0.0                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb82d6ee_1    conda-forge
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
bayesian-optimization     1.2.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
bottleneck                1.3.2            py39h7cc1a96_1    defaults
brotli                    1.0.9                ha925a31_2    defaults
brotlipy                  0.7.0           py39h2bbff1b_1003    defaults
ca-certificates           2021.10.26           haa95532_2    defaults
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8        py39haa95532_2    defaults
cffi                      1.15.0           py39h0878f49_0    conda-forge
charset-normalizer        2.0.10                   pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
cryptography              36.0.0           py39h21b164f_0    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
debugpy                   1.5.1            py39h415ef7b_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
flatbuffers               2.0                      pypi_0    pypi
flit-core                 3.6.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freeglut                  3.2.1                h0e60522_2    conda-forge
freetype                  2.10.4               hd328e21_0    defaults
gast                      0.4.0                    pypi_0    pypi
google-auth               2.3.3                    pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.43.0                   pypi_0    pypi
gym                       0.21.0                   pypi_0    pypi
h5py                      3.6.0            py39h3de5c98_0    defaults
hdf5                      1.10.6               h7ebc959_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       68.1                 h6c2663c_0    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
importlib-metadata        4.10.0           py39hcbf5309_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2021.4.0          haa95532_3556    defaults
ipykernel                 6.6.1            py39h832f523_0    conda-forge
ipython                   7.31.0           py39hcbf5309_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
jasper                    2.0.33               h77af90b_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jedi                      0.18.1           py39hcbf5309_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd3eb1b0_0    defaults
jpeg                      9d                   h2bbff1b_0    defaults
jsonschema                4.3.3              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39haa95532_7    defaults
jupyter_client            7.1.0              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd3eb1b0_0    defaults
jupyter_core              4.9.1            py39hcbf5309_1    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
kaggle                    1.5.12                   pypi_0    pypi
keras                     2.7.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1            py39hd77b12b_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libblas                   3.9.0              12_win64_mkl    conda-forge
libcblas                  3.9.0              12_win64_mkl    conda-forge
libclang                  12.0.0                   pypi_0    pypi
libdeflate                1.8                  h2bbff1b_5    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblapack                 3.9.0              12_win64_mkl    conda-forge
liblapacke                3.9.0              12_win64_mkl    conda-forge
libopencv                 4.5.3            py39h606fa8f_7    conda-forge
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.19.1               h23ce68f_0    defaults
libsodium                 1.0.18               h8d14728_1    conda-forge
libtiff                   4.3.0                hd413186_2    conda-forge
libwebp                   1.2.1                h57928b3_0    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               h0ad7f3c_0    defaults
libxslt                   1.1.34               he774522_0    defaults
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lxml                      4.7.1            py39h1985fb9_1    defaults
lz4-c                     1.9.3                h2bbff1b_1    defaults
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.3.6                    pypi_0    pypi
markupsafe                2.0.1            py39hb82d6ee_1    conda-forge
matplotlib                3.5.0            py39haa95532_0    defaults
matplotlib-base           3.5.0            py39h6214cd6_0    defaults
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39hb82d6ee_1005    conda-forge
mkl                       2021.4.0           h0e2418a_729    conda-forge
mkl-service               2.4.0            py39h2bbff1b_0    defaults
mkl_fft                   1.3.1            py39h277e83a_0    defaults
mkl_random                1.2.2            py39hf11a4ad_0    defaults
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4                      py_0    defaults
nb_conda                  2.2.1            py39hcbf5309_4    conda-forge
nb_conda_kernels          2.3.1            py39hcbf5309_1    conda-forge
nbclient                  0.5.9              pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.0            py39hcbf5309_0    conda-forge
nbformat                  5.1.3              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
notebook                  6.4.6              pyha770c72_0    conda-forge
numexpr                   2.8.1            py39hb80d3ca_0    defaults
numpy                     1.22.0                   pypi_0    pypi
numpy-base                1.21.2           py39h0829f74_0    defaults
oauthlib                  3.1.1                    pypi_0    pypi
olefile                   0.46               pyhd3eb1b0_0    defaults
opencv                    4.5.3            py39hcbf5309_7    conda-forge
openssl                   1.1.1m               h2bbff1b_0    defaults
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py39h6214cd6_0    defaults
pandas-datareader         0.10.0             pyhd3eb1b0_0    defaults
pandoc                    2.16.2               h8ffe710_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.4.0            py39hd45dc43_0    defaults
pip                       21.2.4           py39haa95532_0    defaults
prometheus_client         0.12.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.24             pyha770c72_0    conda-forge
prompt_toolkit            3.0.24               hd8ed1ab_0    conda-forge
protobuf                  3.19.3                   pypi_0    pypi
py-opencv                 4.5.3            py39h832f523_7    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydicom                   2.2.2              pyh6c4a22f_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 21.0.0             pyhd3eb1b0_1    defaults
pyparsing                 3.0.6              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_8    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_8    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_8    conda-forge
pyqtchart                 5.12             py39h415ef7b_8    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_8    conda-forge
pyreadline                2.1              py39haa95532_1    defaults
pyrsistent                0.18.0           py39hb82d6ee_0    conda-forge
pysocks                   1.7.1            py39haa95532_0    defaults
python                    3.9.7                h6244533_1    defaults
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-slugify            5.0.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    defaults
pywin32                   303              py39hb82d6ee_0    conda-forge
pywinpty                  0.5.7            py39haa95532_0    defaults
pyyaml                    6.0              py39h2bbff1b_1    defaults
pyzmq                     22.3.0           py39he46f08e_1    conda-forge
qt                        5.12.9               h5909a2a_4    conda-forge
qtconsole                 5.1.1              pyhd3eb1b0_0    defaults
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
scikit-learn              1.0.2            py39hf11a4ad_0    defaults
scipy                     1.7.3            py39h0a974cb_0    defaults
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                58.0.4           py39haa95532_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h2bbff1b_0    defaults
tbb                       2021.4.0             h59b6b97_0    defaults
tensorboard               2.7.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow-estimator      2.7.0                    pypi_0    pypi
tensorflow-gpu            2.7.0                    pypi_0    pypi
tensorflow-io-gcs-filesystem 0.23.1                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py39haa95532_0    defaults
testpath                  0.5.0              pyhd8ed1ab_0    conda-forge
text-unidecode            1.3                      pypi_0    pypi
threadpoolctl             2.2.0              pyh0d69192_0    defaults
tk                        8.6.11               h2bbff1b_0    defaults
tornado                   6.1              py39hb82d6ee_2    conda-forge
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.0.1                    pypi_0    pypi
tzdata                    2021e                hda174b7_0    defaults
urllib3                   1.26.8                   pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.1            py39haa95532_0    defaults
win_inet_pton             1.1.0            py39haa95532_0    defaults
wincertstore              0.2              py39haa95532_2    defaults
winpty                    0.4.3                         4    conda-forge
wrapt                     1.13.3                   pypi_0    pypi
xz                        5.2.5                h62dcd97_0    defaults
yaml                      0.2.5                he774522_0    defaults
zeromq                    4.3.4                h0e60522_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h19a0ad4_1    defaults
```

</details>

**Comment by khamyl** [comment]
How long does it take to respond in average, please? I have to decide how to continue, whether  wait for response, or find some other solution. Thank you :)

**Comment by kenodegard** [comment]
@khamyl I am unable to reproduce your error, can you create a new environment and confirm whether or not the same issue occurs?

```batch
> conda create -n hdf5 python=3.9.7 hdf5=1.10.6 h5py=3.6.0
> conda activate hdf5
> python -c "import h5py"
```

**Comment by fdivruno** [comment]
Hi, is it possible that this error is due to Spyder?

I am getting this error in Spyder (V5.3.1) when i try "import h5py":
------------------- result-------------------
Traceback (most recent call last):

  File "C:\Users\f.divruno\AppData\Local\Temp\ipykernel_42948\3925459481.py", line 1, in <cell line: 1>
    import h5py

  File "C:\Users\f.divruno\Anaconda3\envs\lofar_satellites\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version

  File "C:\Users\f.divruno\Anaconda3\envs\lofar_satellites\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5

  File "h5py\h5.pyx", line 1, in init h5py.h5

ImportError: DLL load failed while importing defs: The specified procedure could not be found.

------------------- result-------------------

But when I run the same import in a console from the same Anaconda environment I get no errors.

Open console, type python, import h5py, no errors.

**Comment by or-lazarescu** [comment]
same issue as @fdivruno and @khamyl : when i try to import h5py in Spyder i get this error, but when i import the same package in conda prompt it has no issues with it.

**Comment by DrBwts** [comment]
I found on my system (x64 Win 10) that this was to do with a previous `pip` install. Once I'd deleted all the associated DLLs & then reinstalled with `conda` it all worked well.

**Comment by oceancolorcoder** [comment]
Same issue.
Windows 11, conda 23.3.1, python 3.9.16, h5py 3.7.0, hdf5 1.10.6 (Problem only on Windows; no problems on Linux or MacOS.)
Tried:
>conda remove --force h5py
> pip install h5py
Same problem, then tried pip unistalling and conda installing.

Tried removing the environment completely and reinstalling. Same problem.

No problem importing h5py in python console, but won't work in module in same environment. 

@DrBwts: could you please describe how to remove the offending DLLs?

**Comment by DrBwts** [comment]
@oceancolorcoder for the life of me I cant work out what I did, as far as I recall there was some weirdness with having multiple copies of hdf5.dll & h5py.dll, some installed with pip & others installed with conda.

**Comment by batterseapower** [comment]
This was happening to me because I had a DLL in the Conda env at `./Lib/site-packages/h5py/hdf5.dll` and also at `./Library/bin/hdf5.dll`. I think the first DLL was installed by pip at some point, while the second DLL came from the conda "hdf5" package. The conda-installed hdf5py package had .pyd binaries that used some symbols that were only present in the second DLL, but Windows was linking against the first DLL, which caused an `ImportError`. I fixed this by replacing the first DLL with the second one, but it's possible that simply deleting the second DLL would have been sufficient.
