### ISSUE TITLE
Can't create an environment

### ISSUE THREAD

**Issue by ahmedselim2017** [conda/conda#11167]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I installed conda without changing any configuration etc. I tried to create an environment using ```conda create --name test``` it gave this error.

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 60, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 123, in solve_for_transaction
        self._notify_conda_outdated(link_precs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 970, in _notify_conda_outdated
        SubdirData.query_all(conda_newer_spec, self.channels, self.subdirs,
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 140, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
        yield fs.pop().result()
      File "/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 438, in result
        return self.__get_result()
      File "/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
        raise self._exception
      File "/opt/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 145, in query
        self.load()
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 210, in load
        _internal_state = self._load()
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 375, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 687, in fetch_repodata_remote_request
        session = CondaSession()
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 62, in __call__
        session = cls._thread_local.session = super(CondaSessionType, cls).__call__()
      File "/opt/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 85, in __init__
        retry = Retry(total=context.remote_max_retries,
    TypeError: __init__() got an unexpected keyword argument 'raise_on_status'

`$ /opt/miniconda3/bin/conda create --name test`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/opt/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/opt/miniconda3/bin/python
               CONDA_ROOT=/opt/miniconda3
              CONDA_SHLVL=0
                CUDA_PATH=/opt/cuda
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/miniconda3/bin:/home/ahmedselimuzum/.local/bin:/home/ahmedselimuz
                          um/.local/bin:/opt/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:
                          /usr/bin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_syste
                          ms/bin:/home/ahmedselimuzum/.dotnet/tools:/usr/lib/jvm/default/bin:/us
                          r/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
   PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
              SUDO_EDITOR=/usr/bin/nvim
               WINDOWPATH=1

     active environment : None
            shell level : 0
       user config file : /home/ahmedselimuzum/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.5=0
                          __linux=5.16.2=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (read only)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/ahmedselimuzum/.conda/pkgs
       envs directories : /home/ahmedselimuzum/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.8.1 CPython/3.9.5 Linux/5.16.2-arch1-1 arch/rolling glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
Timeout reached. No report sent.
```

### Conda info

```shell
active environment : None
            shell level : 0
       user config file : /home/ahmedselimuzum/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __cuda=11.5=0
                          __linux=5.16.2=0
                          __glibc=2.33=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (read only)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/ahmedselimuzum/.conda/pkgs
       envs directories : /home/ahmedselimuzum/.conda/envs
                          /opt/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.8.1 CPython/3.9.5 Linux/5.16.2-arch1-1 arch/rolling glibc/2.33
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda config

```shell
Nothing
```

### Conda list

```shell
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
certifi                   2021.5.30        py39h06a4308_0    defaults
cffi                      1.14.6           py39h400218f_0    defaults
chardet                   4.0.0           py39h06a4308_1003    defaults
conda                     4.10.3           py39h06a4308_0    defaults
conda-package-handling    1.7.3            py39h27cfd23_1    defaults
cryptography              3.4.7            py39hd23ed53_0    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
pip                       21.1.3           py39h06a4308_0    defaults
py3nvml                   0.2.7                    pypi_0    pypi
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.5                h12debd9_4    defaults
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
setuptools                52.0.0           py39h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
tzdata                    2021a                h52ac0ba_0    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

### Additional Context

I use the 5.16.2-arch1-1 kernel, and my systemwide python is python 3.10.2

**Comment by ahmedselim2017** [comment]
After installing requests==2.8.1, it was solved
