### ISSUE TITLE
Meta-package ipython-notebook misses pygments

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#1116]
I tried to use `ipython nbconvert` after a fresh install of condo with `ipython-notebook` and got a crash from the ImportError.

**Comment by ilanschnell** [comment]
Which platform is this on?  What is the exact command you are trying to run, as well as the traceback?  Also, the output of `conda info` might be useful to debug this issue.

**Comment by michaelaye** [comment]
platform/info:

```shell
) conda info
Current conda install:

             platform : linux-64
        conda version : 3.8.1
  conda-build version : not installed
       python version : 3.4.2.final.0
     requests version : 2.5.1
     root environment : /usr/local/python3/miniconda  (writable)
  default environment : /usr/local/python3/miniconda/envs/debug
     envs directories : /usr/local/python3/miniconda/envs
        package cache : /usr/local/python3/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

debug session:

```shell
) conda create -n debug python=3
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /usr/local/python3/miniconda/envs/debug:

The following NEW packages will be INSTALLED:

    openssl:  1.0.1k-0
    python:   3.4.2-0
    readline: 6.2-2
    sqlite:   3.8.4.1-0
    system:   5.8-1
    tk:       8.5.15-0
    xz:       5.0.5-0
    zlib:     1.2.8-0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |####################################################| 100%
#
# To activate this environment, use:
# $ source activate debug
#
# To deactivate this environment, use:
# $ source deactivate
#
klay6683@maven-iuvs-itf|~
) source activate debug
discarding /usr/local/python3/miniconda/bin from PATH
prepending /usr/local/python3/miniconda/envs/debug/bin to PATH
(debug)klay6683@maven-iuvs-itf|~
) conda install ipython-notebook
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /usr/local/python3/miniconda/envs/debug:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipython-notebook-2.3.1     |           py34_0           5 KB

The following NEW packages will be INSTALLED:

    ipython:          2.3.1-py34_0
    ipython-notebook: 2.3.1-py34_0
    jinja2:           2.7.3-py34_1
    libsodium:        0.4.5-0
    markupsafe:       0.23-py34_0
    pyzmq:            14.5.0-py34_0
    setuptools:       12.0.5-py34_0
    tornado:          4.0.2-py34_0
    zeromq:           4.0.4-0

Proceed ([y]/n)? y

Fetching packages ...
ipython-notebo 100% |##################################| Time: 0:00:00   4.74 MB/s
Extracting packages ...
[      COMPLETE      ] |####################################################| 100%
Linking packages ...
[      COMPLETE      ] |####################################################| 100%
(debug)klay6683@maven-iuvs-itf|~
) ipython nbconvert
zsh: correct ipython to python [nyae]? n
[NbConvertApp] Using existing profile dir: '/home/klay6683/.ipython/profile_default'
Traceback (most recent call last):
  File "/usr/local/python3/miniconda/envs/debug/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/config/application.py", line 564, in launch_instance
    app.start()
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 367, in start
    return self.subapp.start()
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/nbconvertapp.py", line 268, in start
    self.convert_notebooks()
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/nbconvertapp.py", line 284, in convert_notebooks
    exporter = exporter_map[self.export_format](config=self.config)
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/exporters/templateexporter.py", line 151, in __init__
    super(TemplateExporter, self).__init__(config=config, **kw)
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/exporters/exporter.py", line 94, in __init__
    self._init_preprocessors()
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/exporters/exporter.py", line 222, in _init_preprocessors
    self.register_preprocessor(preprocessor)
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/exporters/exporter.py", line 188, in register_preprocessor
    return self.register_preprocessor(preprocessor_cls, enabled)
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/exporters/exporter.py", line 201, in register_preprocessor
    self.register_preprocessor(preprocessor(parent=self), enabled)
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/preprocessors/csshtmlheader.py", line 54, in __init__
    self._regen_header()
  File "/usr/local/python3/miniconda/envs/debug/lib/python3.4/site-packages/IPython/nbconvert/preprocessors/csshtmlheader.py", line 84, in _regen_header
    from pygments.formatters import HtmlFormatter
ImportError: No module named 'pygments'

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@scipy.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    c.Application.verbose_crash=True

(debug)-> [1]
klay6683@maven-iuvs-itf|~
) conda install pygments
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /usr/local/python3/miniconda/envs/debug:

The following NEW packages will be INSTALLED:

    pygments: 2.0.2-py34_0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ] |##############################################################################################################################| 100%
(debug)klay6683@maven-iuvs-itf|~
) ipython nbconvert
[NbConvertApp] Using existing profile dir: '/home/klay6683/.ipython/profile_default'
This application is used to convert notebook files (*.ipynb) to various other
formats.

WARNING: THE COMMANDLINE INTERFACE MAY CHANGE IN FUTURE RELEASES.

Options
-------
[...cut]
```

**Comment by michaelaye** [comment]
I just updated conda to 3.8.3 and rerun above debug session, reproducing the same problem:

```shell
) conda info
Current conda install:

             platform : linux-64
        conda version : 3.8.3
  conda-build version : not installed
       python version : 3.4.2.final.0
     requests version : 2.5.1
     root environment : /usr/local/python3/miniconda  (writable)
  default environment : /usr/local/python3/miniconda/envs/debug
     envs directories : /usr/local/python3/miniconda/envs
        package cache : /usr/local/python3/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment]
We should probably have a separate ipython-nbconvert package.

**Comment by aldanor** [comment]
Just FYI, IPython 3.0.0 rc1 will require more runtime dependencies; I remember having to build `mistune` and `terminado` to make the ipython test suite pass.

**Comment by asmeurer** [comment]
terminado is apparently only needed on Windows https://github.com/ipython/ipython/blob/92333e1084ea0d6ff91b55434555e741d2274dc7/setup.py#L263

**Comment by michaelaye** [comment]
i understand it the other way round: it ONLY is required on NON-windows machines, I guess b/c it doesn't work there.

**Comment by asmeurer** [comment]
Oh I misread the code :)

**Comment by OndrejMarsalek** [comment]
I did a fresh install of Miniconda today:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.9.1
  conda-build version : not installed
       python version : 3.4.2.final.0
     requests version : 2.5.3
     root environment : /home/marsalek/opt/anaconda3  (writable)
  default environment : /home/marsalek/opt/anaconda3
     envs directories : /home/marsalek/opt/anaconda3/envs
        package cache : /home/marsalek/opt/anaconda3/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

and installed the new stable `ipython` and `ipython-notebook` version 3.0. `ipython nbconvert` was missing `mistune` and `pygments` at run time. Terminals were also unavailable due to missing `terminado`.

I installed `mistune` and `terminado` using `pip`, as `conda` did not show them as packages, and I installed `pygments` as an Anaconda package by hand. Now everything seems to work. It looks like these should be installed automatically as dependencies.

**Comment by OndrejMarsalek** [comment]
The import errors show even if you do just `ipython nbconvert --help`.

**Comment by ilanschnell** [comment]
I'll build packages for `mistune` and `terminado` and add them (as well as `pygments` which is already in the default repo) to the `ipython-notebook` meta-package.

**Comment by nehalecky** [comment]
FYI, this issue with `mistune` also popped up in the IPython GH repo very recently: https://github.com/ipython/ipython/issues/7936 

Look forward to your progress @ilanschnell, thanks! :)

**Comment by ilanschnell** [comment]
`terminado` only seems to support Unix systems.  So I guess I will only make it an `ipython-notebook` dependency on Unix.

**Comment by asmeurer** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/276

**Comment by kalefranz** [comment]
Outdated. Closing.
