### ISSUE TITLE
An unexpected error has occured, Please consider posting the following information to the conda GitHub issue tracker at:      https://github.com/conda/conda/issues

### ISSUE THREAD

**Issue by jringoot** [conda/conda#11186]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Tried to install cx_freeze
```
/opt/anaconda2/bin# ./conda install -c conda-forge cx_freeze
Fetching package metadata ...........
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::brotlipy-0.7.0-py27h516909a_1000
  - conda-forge::brotlipy-0.7.0-py27h14c3975_1000

Package plan for installation in environment /opt/anaconda2:

The following NEW packages will be INSTALLED:

    _libgcc_mutex:          0.1-conda_forge           conda-forge
    _openmp_mutex:          4.5-1_gnu                 conda-forge
    blas:                   1.0-mkl                              
    brotlipy:               0.7.0-py27h516909a_1000   conda-forge
    certifi:                2019.11.28-py27h8c360ce_1 conda-forge
    conda-package-handling: 1.6.0-py27hdf8410d_2      conda-forge
    cx_freeze:              5.1.1-py27h14c3975_1      conda-forge
    libgcc-ng:              11.2.0-h1d223b6_12        conda-forge
    libgomp:                11.2.0-h1d223b6_12        conda-forge
    libstdcxx-ng:           11.2.0-he4da1e4_12        conda-forge
    pysocks:                1.7.1-py27h8c360ce_1      conda-forge
    python_abi:             2.7-1_cp27mu              conda-forge
    tqdm:                   4.62.3-pyhd8ed1ab_0       conda-forge
    urllib3:                1.26.8-pyhd8ed1ab_1       conda-forge

The following packages will be UPDATED:

    chardet:                2.3.0-py27_0                          --> 3.0.4-py27h8c360ce_1006 conda-forge
    conda:                  4.3.9-py27_0                          --> 4.8.3-py27h8c360ce_1    conda-forge
    conda-env:              2.6.0-0                               --> 2.6.0-1                 conda-forge
    idna:                   2.2-py27_0                            --> 2.10-pyh9f0ad1d_0       conda-forge
    libgcc:                 5.2.0-0                               --> 7.2.0-h69d50b8_2        conda-forge
    pycosat:                0.6.1-py27_1                          --> 0.6.3-py27hdf8410d_1004 conda-forge
    requests:               2.12.4-py27_0                         --> 2.25.1-pyhd3deb0d_0     conda-forge
    setuptools:             27.2.0-py27_0                         --> 44.0.0-py27_0           conda-forge

Proceed ([y]/n)? y

_libgcc_mutex- 100% |###################################################################################################################################################################| Time: 0:00:00 373.86 kB/s
blas-1.0-mkl.t 100% |###################################################################################################################################################################| Time: 0:00:00   5.02 MB/s
conda-env-2.6. 100% |###################################################################################################################################################################| Time: 0:00:00   1.91 MB/s
libstdcxx-ng-1 100% |###################################################################################################################################################################| Time: 0:00:00  29.02 MB/s
libgomp-11.2.0 100% |###################################################################################################################################################################| Time: 0:00:00  17.21 MB/s
_openmp_mutex- 100% |###################################################################################################################################################################| Time: 0:00:00  12.30 MB/s
idna-2.10-pyh9 100% |###################################################################################################################################################################| Time: 0:00:00  16.24 MB/s
python_abi-2.7 100% |###################################################################################################################################################################| Time: 0:00:00   4.14 MB/s
certifi-2019.1 100% |###################################################################################################################################################################| Time: 0:00:00  23.63 MB/s
chardet-3.0.4- 100% |###################################################################################################################################################################| Time: 0:00:00  20.26 MB/s
libgcc-ng-11.2 100% |###################################################################################################################################################################| Time: 0:00:00  29.78 MB/s
pysocks-1.7.1- 100% |###################################################################################################################################################################| Time: 0:00:00  17.07 MB/s
tqdm-4.62.3-py 100% |###################################################################################################################################################################| Time: 0:00:00  26.44 MB/s
brotlipy-0.7.0 100% |###################################################################################################################################################################| Time: 0:00:00   6.14 MB/s
conda-package- 100% |###################################################################################################################################################################| Time: 0:00:00  27.46 MB/s
cx_freeze-5.1. 100% |###################################################################################################################################################################| Time: 0:00:00   8.48 MB/s
libgcc-7.2.0-h 100% |###################################################################################################################################################################| Time: 0:00:00  27.16 MB/s
pycosat-0.6.3- 100% |###################################################################################################################################################################| Time: 0:00:00  26.50 MB/s
setuptools-44. 100% |###################################################################################################################################################################| Time: 0:00:00  26.03 MB/s
urllib3-1.26.8 100% |###################################################################################################################################################################| Time: 0:00:00  22.80 MB/s
requests-2.25. 100% |###################################################################################################################################################################| Time: 0:00:00  20.21 MB/s
conda-4.8.3-py 100% |###################################################################################################################################################################| Time: 0:00:00  19.97 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda2  (writable)
    default environment : /opt/anaconda2
       envs directories : /opt/anaconda2/envs
          package cache : /opt/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Linux/3.2.0-24-generic debian/wheezy/sid glibc/2.15
                UID:GID : 0:0



`$ ./conda install -c conda-forge cx_freeze`




    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 256, in execute
        self.verify()
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 239, in verify
        self.prepare()
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 170, in prepare
        concatv(unlink_actions, link_actions))
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 169, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 166, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 395, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set

```

### Conda info

```shell
/conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda2  (writable)
    default environment : /opt/anaconda2
       envs directories : /opt/anaconda2/envs
          package cache : /opt/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Linux/3.2.0-24-generic debian/wheezy/sid glibc/2.15
                UID:GID : 0:0
```

### Conda config

```shell
./conda config --show-sources

<NULL> (no output)
```

### Conda list

```shell
./conda list --show-channel-urls
# packages in environment at /opt/anaconda2:
#
_license                  1.1                      py27_1    defaults
alabaster                 0.7.9                    py27_0    defaults
anaconda                  custom                   py27_0    defaults
anaconda-client           1.6.1                    py27_0    defaults
anaconda-navigator        1.4.3                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astroid                   1.4.9                    py27_0    defaults
astropy                   1.3                 np111py27_0    defaults
babel                     2.3.4                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.5                      py27_0    defaults
beautifulsoup4            4.5.3                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.4                   py27_0    defaults
boto                      2.45.0                   py27_0    defaults
bottleneck                1.2.0               np111py27_0    defaults
cairo                     1.14.8                        0    defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.9.1                    py27_0    defaults
chardet                   2.3.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.7                      py27_0    defaults
cloudpickle               0.2.2                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
conda                     4.3.9                    py27_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
contextlib2               0.5.4                    py27_0    defaults
cryptography              1.7.1                    py27_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.25.2                   py27_0    defaults
cytoolz                   0.8.2                    py27_0    defaults
dask                      0.13.0                   py27_0    defaults
datashape                 0.5.4                    py27_0    defaults
dbus                      1.10.10                       0    defaults
decorator                 4.0.11                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
docutils                  0.13.1                   py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py27_1    defaults
flask                     0.12                     py27_0    defaults
flask-cors                3.0.2                    py27_0    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         2    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.2.1                    py27_0    defaults
glib                      2.50.2                        1    defaults
greenlet                  0.4.11                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.6.0               np111py27_2    defaults
harfbuzz                  0.9.39                        2    defaults
hdf4                      4.2.11                        0    defaults
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py27_1    defaults
icu                       54.1                          0    defaults
idna                      2.2                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
ipaddress                 1.0.18                   py27_0    defaults
ipykernel                 4.5.2                    py27_0    defaults
ipython                   5.1.0                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                5.2.2                    py27_1    defaults
isort                     4.2.5                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3                      py27_0    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.9.4                    py27_0    defaults
jpeg                      9b                            0    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter_client            4.4.0                    py27_0    defaults
jupyter_console           5.0.0                    py27_0    defaults
jupyter_core              4.2.1                    py27_0    defaults
lazy-object-proxy         1.2.2                    py27_0    defaults
libffi                    3.2.1                         1    defaults
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          0    defaults
libnetcdf                 4.4.1                         0    defaults
libpng                    1.6.27                        0    defaults
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         3    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        0    defaults
llvmlite                  0.15.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.7.2                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                2.0.0               np111py27_0    defaults
mistune                   0.7.3                    py27_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py27_3    defaults
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.9                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.2.0                    py27_0    defaults
netcdf4                   1.2.4               np111py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.2                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.3.1                    py27_0    defaults
numba                     0.30.1              np111py27_0    defaults
numexpr                   2.6.1               np111py27_2    defaults
numpy                     1.11.3                   py27_0    defaults
numpydoc                  0.6.0                    py27_0    defaults
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.4.1                    py27_0    defaults
openssl                   1.0.2k                        0    defaults
pandas                    0.19.2              np111py27_1    defaults
partd                     0.3.7                    py27_0    defaults
path.py                   10.0                     py27_0    defaults
pathlib2                  2.2.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pcre                      8.39                          1    defaults
pep8                      1.7.0                    py27_0    defaults
pexpect                   4.2.1                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    4.0.0                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
pixman                    0.34.0                        0    defaults
ply                       3.10                     py27_0    defaults
prompt_toolkit            1.0.9                    py27_0    defaults
psutil                    5.1.2                    py27_0    defaults
ptyprocess                0.5.1                    py27_0    defaults
py                        1.4.32                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycosat                   0.6.1                    py27_1    defaults
pycparser                 2.17                     py27_0    defaults
pycrypto                  2.6.1                    py27_4    defaults
pycurl                    7.43.0                   py27_0    defaults
pyflakes                  1.5.0                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pylint                    1.6.4                    py27_1    defaults
pyopenssl                 16.2.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_2    defaults
pytables                  3.3.0               np111py27_0    defaults
pytest                    3.0.5                    py27_0    defaults
python                    2.7.13                        0    defaults
python-dateutil           2.6.0                    py27_0    defaults
pytz                      2016.10                  py27_0    defaults
pyyaml                    3.12                     py27_0    defaults
pyzmq                     16.0.2                   py27_0    defaults
qt                        5.6.2                         3    defaults
qtawesome                 0.4.4                    py27_0    defaults
qtconsole                 4.2.1                    py27_1    defaults
qtpy                      1.2.1                    py27_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
requests                  2.12.4                   py27_0    defaults
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_1    defaults
scandir                   1.4                      py27_0    defaults
scikit-image              0.12.3              np111py27_1    defaults
scikit-learn              0.18.1              np111py27_1    defaults
scipy                     0.18.1              np111py27_1    defaults
seaborn                   0.7.1                    py27_0    defaults
setuptools                27.2.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sphinx                    1.5.1                    py27_0    defaults
spyder                    3.1.2                    py27_0    defaults
sqlalchemy                1.1.5                    py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np111py27_1    defaults
subprocess32              3.2.7                    py27_0    defaults
sympy                     1.0                      py27_0    defaults
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.2                    py27_0    defaults
tornado                   4.4.2                    py27_0    defaults
traitlets                 4.3.1                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.11.15                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        1.2.6                    py27_0    defaults
wrapt                     1.10.8                   py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.6                    py27_0    defaults
xlwt                      1.2.0                    py27_0    defaults
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.5                         0    defaults
zlib                      1.2.8                         3    defaults
```

**Comment by jringoot** [comment]
This was resolved after updating conda itself
`./conda update conda `
and again
`./conda install -c conda-forge cx_freeze`

Took a while but it finished without error
./conda install -c conda-forge cx_freeze
```
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /opt/anaconda2:

The following NEW packages will be INSTALLED:

    _libgcc_mutex:          0.1-conda_forge           conda-forge
    _openmp_mutex:          4.5-1_gnu                 conda-forge
    blas:                   1.0-mkl                              
    brotlipy:               0.7.0-py27h516909a_1000   conda-forge
    certifi:                2019.11.28-py27h8c360ce_1 conda-forge
    conda-package-handling: 1.6.0-py27hdf8410d_2      conda-forge
    cx_freeze:              5.1.1-py27h14c3975_1      conda-forge
    libgcc-ng:              11.2.0-h1d223b6_12        conda-forge
    libgomp:                11.2.0-h1d223b6_12        conda-forge
    libstdcxx-ng:           11.2.0-he4da1e4_12        conda-forge
    pysocks:                1.7.1-py27h8c360ce_1      conda-forge
    python_abi:             2.7-1_cp27mu              conda-forge
    tqdm:                   4.62.3-pyhd8ed1ab_0       conda-forge
    urllib3:                1.26.8-pyhd8ed1ab_1       conda-forge

The following packages will be UPDATED:

    chardet:                2.3.0-py27_0                          --> 3.0.4-py27h8c360ce_1006 conda-forge
    conda:                  4.3.30-py27h6ae6dc7_0                 --> 4.8.3-py27h8c360ce_1    conda-forge
    conda-env:              2.6.0-0                               --> 2.6.0-1                 conda-forge
    idna:                   2.2-py27_0                            --> 2.10-pyh9f0ad1d_0       conda-forge
    libgcc:                 5.2.0-0                               --> 7.2.0-h69d50b8_2        conda-forge
    pycosat:                0.6.1-py27_1                          --> 0.6.3-py27hdf8410d_1004 conda-forge
    requests:               2.12.4-py27_0                         --> 2.25.1-pyhd3deb0d_0     conda-forge
    setuptools:             27.2.0-py27_0                         --> 44.0.0-py27_0           conda-forge

Proceed ([y]/n)? y
```
