### ISSUE TITLE
VTK not importing

### ISSUE THREAD

**Issue by glinsky007** [conda/conda#11190]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

For Python 3.7 and lower `import vtk` can not load module `vtkCommonCorePython` in a simple virtual environment built with `conda install mayavi`.  This is corrected in Python 3.8 and higher with `pip install mayavi` and VTK version 9.0.1.  What is the solution for Python 3.7 and lower.  What follows is the build of the virtual environment and the error:

```
(python38) mglinsky@iMacPro-MEG ~ % conda create -n vtkbug36 python=3.6  mayavi

## Package Plan ##

  environment location: /Users/mglinsky/opt/anaconda3/envs/vtkbug36

  added / updated specs:
    - mayavi
    - python=3.6


The following NEW packages will be INSTALLED:

  apptools           pkgs/main/noarch::apptools-5.1.0-pyhd3eb1b0_0
  blas               pkgs/main/osx-64::blas-1.0-mkl
  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
  c-ares             pkgs/main/osx-64::c-ares-1.18.1-hca72f7f_0
  ca-certificates    pkgs/main/osx-64::ca-certificates-2021.10.26-hecd8cb5_2
  certifi            pkgs/main/osx-64::certifi-2021.5.30-py36hecd8cb5_0
  configobj          pkgs/main/osx-64::configobj-5.0.6-py36hecd8cb5_1
  curl               pkgs/main/osx-64::curl-7.80.0-hca72f7f_0
  dbus               pkgs/main/osx-64::dbus-1.13.18-h18a8e69_0
  envisage           pkgs/main/noarch::envisage-6.0.1-pyhd3eb1b0_0
  expat              pkgs/main/osx-64::expat-2.4.1-h23ab428_2
  freetype           pkgs/main/osx-64::freetype-2.11.0-hd8bbffd_0
  future             pkgs/main/osx-64::future-0.18.2-py36_1
  gettext            pkgs/main/osx-64::gettext-0.21.0-h7535e17_0
  glib               pkgs/main/osx-64::glib-2.69.1-h8346a28_1
  hdf4               pkgs/main/osx-64::hdf4-4.2.13-h39711bb_2
  hdf5               pkgs/main/osx-64::hdf5-1.10.4-hfa1e0ec_0
  icu                pkgs/main/osx-64::icu-58.2-h0a44026_3
  intel-openmp       pkgs/main/osx-64::intel-openmp-2022.0.0-hecd8cb5_3615
  jpeg               pkgs/main/osx-64::jpeg-9d-h9ed2024_0
  jsoncpp            pkgs/main/osx-64::jsoncpp-1.9.4-hf7b0b51_2
  krb5               pkgs/main/osx-64::krb5-1.19.2-hcd88c3b_0
  libcurl            pkgs/main/osx-64::libcurl-7.80.0-h6dfd666_0
  libcxx             pkgs/main/osx-64::libcxx-12.0.0-h2f01273_0
  libedit            pkgs/main/osx-64::libedit-3.1.20210910-hca72f7f_0
  libev              pkgs/main/osx-64::libev-4.33-h9ed2024_1
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  libgfortran        pkgs/main/osx-64::libgfortran-3.0.1-h93005f0_2
  libiconv           pkgs/main/osx-64::libiconv-1.16-h1de35cc_0
  libnetcdf          pkgs/main/osx-64::libnetcdf-4.6.1-hd5207e6_2
  libnghttp2         pkgs/main/osx-64::libnghttp2-1.46.0-ha29bfda_0
  libogg             pkgs/main/osx-64::libogg-1.3.5-hca72f7f_1
  libpng             pkgs/main/osx-64::libpng-1.6.37-ha441bb4_0
  libssh2            pkgs/main/osx-64::libssh2-1.9.0-ha12b0ac_1
  libtheora          pkgs/main/osx-64::libtheora-1.1.1-hb4e5f40_1
  libtiff            pkgs/main/osx-64::libtiff-4.1.0-hcb84e12_0
  libvorbis          pkgs/main/osx-64::libvorbis-1.3.7-haf1e3a3_0
  libxml2            pkgs/main/osx-64::libxml2-2.9.12-hcdb78fc_0
  llvm-openmp        pkgs/main/osx-64::llvm-openmp-12.0.0-h0dcd299_1
  lz4-c              pkgs/main/osx-64::lz4-c-1.8.1.2-h1de35cc_0
  mayavi             pkgs/main/osx-64::mayavi-4.7.1-py36hd5f3a30_2
  mkl                pkgs/main/osx-64::mkl-2019.4-233
  mkl-service        pkgs/main/osx-64::mkl-service-2.3.0-py36h9ed2024_0
  mkl_fft            pkgs/main/osx-64::mkl_fft-1.3.0-py36ha059aab_0
  mkl_random         pkgs/main/osx-64::mkl_random-1.1.1-py36h959d312_0
  ncurses            pkgs/main/osx-64::ncurses-6.3-hca72f7f_2
  numpy              pkgs/main/osx-64::numpy-1.19.2-py36h456fd55_0
  numpy-base         pkgs/main/osx-64::numpy-base-1.19.2-py36hcfb5961_0
  openssl            pkgs/main/osx-64::openssl-1.1.1m-hca72f7f_0
  pcre               pkgs/main/osx-64::pcre-8.45-h23ab428_0
  pip                pkgs/main/osx-64::pip-21.2.2-py36hecd8cb5_0
  pyface             pkgs/main/osx-64::pyface-7.3.0-py36hecd8cb5_1
  pygments           pkgs/main/noarch::pygments-2.10.0-pyhd3eb1b0_0
  pyqt               pkgs/main/osx-64::pyqt-5.9.2-py36h655552a_2
  python             pkgs/main/osx-64::python-3.6.13-h88f2d9e_0
  qt                 pkgs/main/osx-64::qt-5.9.7-h468cd18_1
  readline           pkgs/main/osx-64::readline-8.1.2-hca72f7f_1
  setuptools         pkgs/main/osx-64::setuptools-58.0.4-py36hecd8cb5_0
  sip                pkgs/main/osx-64::sip-4.19.8-py36h0a44026_0
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_0
  sqlite             pkgs/main/osx-64::sqlite-3.37.0-h707629a_0
  tbb                pkgs/main/osx-64::tbb-2021.5.0-haf03e11_0
  tk                 pkgs/main/osx-64::tk-8.6.11-h7bc2e8c_0
  traits             pkgs/main/osx-64::traits-6.2.0-py36h9ed2024_0
  traitsui           pkgs/main/noarch::traitsui-7.2.1-pyhd3eb1b0_0
  vtk                pkgs/main/osx-64::vtk-8.2.0-py36h9bafd54_200
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h4dc903c_4
  zstd               pkgs/main/osx-64::zstd-1.3.7-h5bba6e5_0

(python38) mglinsky@iMacPro-MEG ~ % conda activate vtkbug36
(vtkbug36) mglinsky@iMacPro-MEG ~ % python
Python 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 12:58:59) 
[GCC Clang 10.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import vtk
Traceback (most recent call last):
  File "/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtkmodules/vtkCommonCore.py", line 5, in <module>
    from .vtkCommonCorePython import *
ImportError: dlopen(/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtkmodules/vtkCommonCorePython.so, 0x0002): Library not loaded: @rpath/libtbb.dylib
  Referenced from: /Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/libvtkCommonCorePython36D-8.2.1.dylib
  Reason: tried: '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtkmodules/../../../libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtkmodules/../../../libtbb.dylib' (no such file), '/opt/concourse/worker/volumes/live/b1ca6fea-a590-49e0-4b7e-accc1b16942a/volume/python_1614113036400/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/bin/../lib/libtbb.dylib' (no such file), '/opt/concourse/worker/volumes/live/b1ca6fea-a590-49e0-4b7e-accc1b16942a/volume/python_1614113036400/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libtbb.dylib' (no such file), '/Users/mglinsky/opt/anaconda3/envs/vtkbug36/bin/../lib/libtbb.dylib' (no such file), '/usr/local/lib/libtbb.dylib' (no such file), '/usr/lib/libtbb.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtk.py", line 32, in <module>
    all_spec.loader.exec_module(all_m)
  File "/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtkmodules/all.py", line 7, in <module>
    from .vtkCommonCore import *
  File "/Users/mglinsky/opt/anaconda3/envs/vtkbug36/lib/python3.6/site-packages/vtkmodules/vtkCommonCore.py", line 9, in <module>
    from vtkCommonCorePython import *
ModuleNotFoundError: No module named 'vtkCommonCorePython'
>>> quit()
```

### Conda info

```shell
active environment : vtkbug36
    active env location : /Users/mglinsky/opt/anaconda3/envs/vtkbug36
            shell level : 2
       user config file : /Users/mglinsky/.condarc
 populated config files : /Users/mglinsky/.condarc
          conda version : 4.10.3
    conda-build version : 3.21.5
         python version : 3.9.7.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/mglinsky/opt/anaconda3  (writable)
      conda av data dir : /Users/mglinsky/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/mglinsky/opt/anaconda3/pkgs
                          /Users/mglinsky/.conda/pkgs
       envs directories : /Users/mglinsky/opt/anaconda3/envs
                          /Users/mglinsky/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Darwin/21.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> /Users/mglinsky/.condarc <==
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at /Users/mglinsky/opt/anaconda3/envs/vtkbug36:
#
# Name                    Version                   Build  Channel
apptools                  5.1.0              pyhd3eb1b0_0    defaults
blas                      1.0                         mkl    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.18.1               hca72f7f_0    defaults
ca-certificates           2021.10.26           hecd8cb5_2    defaults
certifi                   2021.5.30        py36hecd8cb5_0    defaults
configobj                 5.0.6            py36hecd8cb5_1    defaults
curl                      7.80.0               hca72f7f_0    defaults
dbus                      1.13.18              h18a8e69_0    defaults
envisage                  6.0.1              pyhd3eb1b0_0    defaults
expat                     2.4.1                h23ab428_2    defaults
freetype                  2.11.0               hd8bbffd_0    defaults
future                    0.18.2                   py36_1    defaults
gettext                   0.21.0               h7535e17_0    defaults
glib                      2.69.1               h8346a28_1    defaults
hdf4                      4.2.13               h39711bb_2    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
icu                       58.2                 h0a44026_3    defaults
intel-openmp              2022.0.0          hecd8cb5_3615    defaults
jpeg                      9d                   h9ed2024_0    defaults
jsoncpp                   1.9.4                hf7b0b51_2    defaults
krb5                      1.19.2               hcd88c3b_0    defaults
libcurl                   7.80.0               h6dfd666_0    defaults
libcxx                    12.0.0               h2f01273_0    defaults
libedit                   3.1.20210910         hca72f7f_0    defaults
libev                     4.33                 h9ed2024_1    defaults
libffi                    3.3                  hb1e8313_2    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.16                 h1de35cc_0    defaults
libnetcdf                 4.6.1                hd5207e6_2    defaults
libnghttp2                1.46.0               ha29bfda_0    defaults
libogg                    1.3.5                hca72f7f_1    defaults
libpng                    1.6.37               ha441bb4_0    defaults
libssh2                   1.9.0                ha12b0ac_1    defaults
libtheora                 1.1.1                hb4e5f40_1    defaults
libtiff                   4.1.0                hcb84e12_0    defaults
libvorbis                 1.3.7                haf1e3a3_0    defaults
libxml2                   2.9.12               hcdb78fc_0    defaults
llvm-openmp               12.0.0               h0dcd299_1    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
mayavi                    4.7.1            py36hd5f3a30_2    defaults
mkl                       2019.4                      233    defaults
mkl-service               2.3.0            py36h9ed2024_0    defaults
mkl_fft                   1.3.0            py36ha059aab_0    defaults
mkl_random                1.1.1            py36h959d312_0    defaults
ncurses                   6.3                  hca72f7f_2    defaults
numpy                     1.19.2           py36h456fd55_0    defaults
numpy-base                1.19.2           py36hcfb5961_0    defaults
openssl                   1.1.1m               hca72f7f_0    defaults
pcre                      8.45                 h23ab428_0    defaults
pip                       21.2.2           py36hecd8cb5_0    defaults
pyface                    7.3.0            py36hecd8cb5_1    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyqt                      5.9.2            py36h655552a_2    defaults
python                    3.6.13               h88f2d9e_0    defaults
qt                        5.9.7                h468cd18_1    defaults
readline                  8.1.2                hca72f7f_1    defaults
setuptools                58.0.4           py36hecd8cb5_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.37.0               h707629a_0    defaults
tbb                       2021.5.0             haf03e11_0    defaults
tk                        8.6.11               h7bc2e8c_0    defaults
traits                    6.2.0            py36h9ed2024_0    defaults
traitsui                  7.2.1              pyhd3eb1b0_0    defaults
vtk                       8.2.0           py36h9bafd54_200    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
zlib                      1.2.11               h4dc903c_4    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```

### Additional Context

Many people have found this issue without resolution:
    [stackoverflow issue](https://stackoverflow.com/questions/69800680/import-vtk-modulenotfounderror-no-module-named-vtkcommoncorepython/70945710#70945710)
    [VTK issue](https://discourse.vtk.org/t/vtk-not-found-in-python-after-conda-install/6251)

**Comment by jezdez** [comment]
Please file a ticket in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues). This is the issue tracker for the conda package manager. Thank you for understanding!
