### ISSUE TITLE
Cannot create new environments after update to 4.11.0

### ISSUE THREAD

**Issue by biostu24** [conda/conda#11196]
### Checklist

- [x] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I upgraded conda using the standard `conda update -n base -c defaults conda` command to version 4.11.0. The upgrade appeared to progress without issue. After the upgrade I could not create new environments with `conda create ...`. 

I get the following error:
```
  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')
```
The full error is posted "additional context"

**My system:**
- MacBook Pro (16-inch, 2019)
- MacOS Monterey, version 12.0.1 (21A559)

**What I have tried**
- Updating my .condarc file with the the path to my conda pkgs directory. This does not fix the issue.
- I have looked at similar open issues but none have a working resolution beyond trying to update the .condarc file:
  - https://github.com/conda/conda/issues/9356
  - https://stackoverflow.com/questions/54087577/install-new-module-in-anaconda-keyerrorpkgs-dirs

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 317, in execute
        info_dict = get_info_dict(args.system)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 135, in get_info_dict
        _supplement_index_with_system(virtual_pkg_index)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 850, in cuda_version
        return cuda_detect()
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/Users/my_user_name/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: tried: '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/usr/local/lib/libffi.6.dylib' (no such file), '/usr/lib/libffi.6.dylib' (no such file)

`$ /Users/my_user_name/miniconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```
</details>

### Conda config

```shell
==> /Users/my_user_name/.condarc <==
auto_activate_base: False
env_prompt: ({name})
pkgs_dirs:
  - /Users/my_user_name/miniconda3/pkgs
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/my_user_name/miniconda3:
#
# Name                    Version                   Build  Channel
anndata                   0.7.5                    pypi_0    pypi
brotlipy                  0.7.0           py37h9ed2024_1003    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.18.1               hca72f7f_0    defaults
ca-certificates           2021.10.26           hecd8cb5_2    defaults
cached-property           1.5.2                    pypi_0    pypi
certifi                   2021.10.8        py37hecd8cb5_2    defaults
cffi                      1.15.0           py37hc55c11b_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     4.11.0           py37hecd8cb5_0    defaults
conda-package-handling    1.7.3            py37h9ed2024_1    defaults
cryptography              36.0.0           py37hf6deb26_0    defaults
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
get-version               2.1                      pypi_0    pypi
h5py                      3.2.1                    pypi_0    pypi
icu                       58.2                 h0a44026_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
importlib-metadata        3.7.2                    pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
krb5                      1.19.2               hcd88c3b_0    defaults
legacy-api-wrap           1.2                      pypi_0    pypi
libarchive                3.5.1                h0a5793d_1    conda-forge
libcurl                   7.80.0               h6dfd666_0    defaults
libcxx                    12.0.0               h2f01273_0    defaults
libedit                   3.1.20210910         hca72f7f_0    defaults
libev                     4.33                 h9ed2024_1    defaults
libffi                    3.4.2                he9d5cce_2    defaults
libiconv                  1.16                 h1de35cc_0    defaults
libnghttp2                1.46.0               ha29bfda_0    defaults
libsolv                   0.7.18               hcf210ce_0    conda-forge
libssh2                   1.9.0                ha12b0ac_1    defaults
libxml2                   2.9.12               hcdb78fc_0    defaults
llvmlite                  0.35.0                   pypi_0    pypi
lz4-c                     1.9.3                h23ab428_1    defaults
lzo                       2.10                 haf1e3a3_2    defaults
mamba                     0.12.2           py37hede01ff_0    conda-forge
matplotlib                3.3.4                    pypi_0    pypi
natsort                   7.1.1                    pypi_0    pypi
ncurses                   6.3                  hca72f7f_2    defaults
networkx                  2.5                      pypi_0    pypi
numba                     0.52.0                   pypi_0    pypi
numexpr                   2.7.3                    pypi_0    pypi
numpy                     1.20.1                   pypi_0    pypi
openssl                   1.1.1m               hca72f7f_0    defaults
packaging                 20.9                     pypi_0    pypi
pandas                    1.2.3                    pypi_0    pypi
patsy                     0.5.1                    pypi_0    pypi
pillow                    8.1.2                    pypi_0    pypi
pycosat                   0.6.3            py37h9ed2024_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pynndescent               0.5.2                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1            py37hecd8cb5_0    defaults
python                    3.7.4                h359304d_1    defaults
python-dateutil           2.8.1                    pypi_0    pypi
python.app                2                        py37_9    defaults
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2021.1                   pypi_0    pypi
readline                  7.0                  h1de35cc_5    defaults
reproc                    14.2.1               hbcb3906_0    conda-forge
reproc-cpp                14.2.1               h2e338ed_0    conda-forge
requests                  2.27.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py37h9ed2024_0    defaults
scanpy                    1.7.1                    pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.1                    pypi_0    pypi
seaborn                   0.11.1                   pypi_0    pypi
setuptools                58.0.4           py37hecd8cb5_0    defaults
sinfo                     0.3.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.33.0               hffcf06c_0    defaults
statsmodels               0.12.2                   pypi_0    pypi
stdlib-list               0.8.0                    pypi_0    pypi
tables                    3.6.1                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.11               h7bc2e8c_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
typing-extensions         3.7.4.3                  pypi_0    pypi
umap-learn                0.5.1                    pypi_0    pypi
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
zipp                      3.4.1                    pypi_0    pypi
zlib                      1.2.11               h4dc903c_4    defaults
zstd                      1.4.9                h322a384_0    defaults
```
</details>

### Additional Context

<details>
<summary><code>Error when trying to create new environment
</code></summary>

```
conda create -n test
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1214): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1080, in __call__
    return func(*args, **kwargs)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
    install(args, parser, 'create')
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 263, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
    should_retry_solve)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
    _supplement_index_with_system(virtual_pkg_index)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
    cuda_version = context.cuda_version
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
    return func(*args, **kwargs)
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 850, in cuda_version
    return cuda_detect()
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
    import ctypes
  File "/Users/my_user_name/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: tried: '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/usr/local/lib/libffi.6.dylib' (no such file), '/usr/lib/libffi.6.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1212, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 263, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
        _supplement_index_with_system(virtual_pkg_index)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 159, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 20, in wrapper
        return func(*args, **kwargs)
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 850, in cuda_version
        return cuda_detect()
      File "/Users/my_user_name/miniconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 37, in cuda_detect
        import ctypes
      File "/Users/my_user_name/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 0x0002): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: tried: '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/lib/python3.7/lib-dynload/../../libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/opt/concourse/worker/volumes/live/d698b2ce-b4b9-4fb4-6268-e633fba1b324/volume/python_1565725718142/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/libffi.6.dylib' (no such file), '/Users/my_user_name/miniconda3/bin/../lib/libffi.6.dylib' (no such file), '/usr/local/lib/libffi.6.dylib' (no such file), '/usr/lib/libffi.6.dylib' (no such file)

`$ /Users/my_user_name/miniconda3/bin/conda create -n test`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
Timeout reached. No report sent.
```
</details>

**Comment by jezdez** [comment]
Thanks for the report, there are two things happening here, one it seems as if when conda checks for an existing cuda installation, it stumbled over a missing `@rpath/libffi.6.dylib` which would imply a broken installation of cuda.

The "pkgs_dirs" KeyError is a secondary issue with the error handling code of the cuda import error and seems a legitimate problem in the code that handles unexpected exceptions.

**Comment by biostu24** [comment]
Thanks @jezdez for looking into this. I resolved the issue by completely wiping my miniconda installation and then re-installing. The version installed was 4.10.3 and everything is working fine. I'm not sure if it was a broken software component or the upgrade to 4.11.0.

If you would like me to upgrade again to see if this reproduces the issue - let me know.

**Comment by jezdez** [comment]
I've escalated this to the Anaconda packaging folks to take a look at the libffi package.

**Comment by beeankha** [comment]
Closing this issu; @biostu24 if the problem you reported still persists/you would like this ticket to stay open, please re-file a new issue in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues).
