### ISSUE TITLE
Platform Incorrect in MacOS Rossetta2 Terminal

### ISSUE THREAD

**Issue by william-silversmith** [conda/conda#11192]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

On an Apple Silicon M1 laptop with miniconda installed, the platform is detected as arm64 when in virtualenv it is detected as x86_64. This causes python wheels to be built as arm64 and fail. I'll note that technically the platform is "correct" as it corresponds to the hardware, but not to the emulation layer as expected.

See https://gitlab.com/jfolz/simplejpeg/-/issues/14 for more details.

# Complete, minimal, self-contained example code that reproduces the issue

Open a terminal window with Rosetta2 enabled.

```
$ conda create -n simplejpeg38 python=3.8
$ conda activate simplejpeg38
$ pip install simplejpeg38 
$ python
>>> import simplejpeg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/USER/code/simplejpeg/simplejpeg/__init__.py", line 1, in <module>
    from ._jpeg import encode_jpeg
ImportError: dlopen(/Users/USER/code/simplejpeg/simplejpeg/_jpeg.cpython-38-darwin.so, 2): Symbol not found: _tjCompress2
  Referenced from: /Users/USER/code/simplejpeg/simplejpeg/_jpeg.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/USER/code/simplejpeg/simplejpeg/_jpeg.cpython-38-darwin.so
```

However this sequence fixes the issue:
```
$ conda create -n simplejpeg38 python=3.8
$ conda activate simplejpeg38
$ arch -arm64 pip install simplejpeg38 
$ python
>>> import simplejpeg
```
Anaconda:

```
>>> import platform
>>> platform.platform()
'macOS-12.2-arm64-i386-64bit'
```
Virtualenv:
```
>>> import platform
>>> platform.platform()
'macOS-12.2-x86_64-i386-64bit'
```

### Conda info

```shell
active environment : simplejpeg38
    active env location : /Users/wms/miniforge3/envs/simplejpeg38
            shell level : 1
       user config file : /Users/wms/.condarc
 populated config files : /Users/wms/miniforge3/.condarc
                          /Users/wms/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __osx=12.2=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/wms/miniforge3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/ukoethe/osx-arm64
                          https://conda.anaconda.org/ukoethe/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/wms/miniforge3/pkgs
                          /Users/wms/.conda/pkgs
       envs directories : /Users/wms/miniforge3/envs
                          /Users/wms/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.9.2 requests/2.25.1 CPython/3.9.1 Darwin/21.3.0 OSX/12.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda config

```shell
==> /Users/wms/miniforge3/.condarc <==
channels:
  - conda-forge

==> /Users/wms/.condarc <==
auto_activate_base: False
channel_priority: strict
channels:
  - conda-forge
  - ukoethe
  - defaults
```

### Conda list

```shell
# packages in environment at /Users/wms/miniforge3/envs/simplejpeg38:
#
# Name                    Version                   Build  Channel
ca-certificates           2021.10.8            h4653dfc_0    conda-forge
libcxx                    12.0.1               h168391b_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libzlib                   1.2.11            hee7b306_1013    conda-forge
ncurses                   6.3                  hc470f4d_0    conda-forge
numpy                     1.22.1                   pypi_0    pypi
openssl                   3.0.0                h3422bc3_2    conda-forge
pip                       22.0.2             pyhd8ed1ab_0    conda-forge
python                    3.8.12          hd949e87_3_cpython    conda-forge
python_abi                3.8                      2_cp38    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
setuptools                60.6.0           py38h10201cd_0    conda-forge
simplejpeg                1.6.3                    pypi_0    pypi
sqlite                    3.37.0               h72a2b83_0    conda-forge
tk                        8.6.11               he1e0b03_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
zlib                      1.2.11            hee7b306_1013    conda-forge
```

**Comment by beeankha** [comment]
Hi @william-silversmith , I re-filed this issue in the  [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) (the place for `conda` installer/package manager issues); closing this out, you can track your newly re-filed issue [here](https://github.com/ContinuumIO/anaconda-issues/issues/12933)
