### ISSUE TITLE
conda install fails macos 12.2.1

### ISSUE THREAD

**Issue by gunnarvoet** [conda/conda#11206]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Trying to install miniconda3 on macos 12.2.1

I get this error message and conda fails to install:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "site-packages/conda/exceptions.py", line 1079, in __call__
      File "site-packages/conda/cli/main.py", line 84, in _main
      File "site-packages/conda/cli/conda_argparse.py", line 83, in do_call
      File "site-packages/conda/cli/main_install.py", line 20, in execute
      File "site-packages/conda/cli/install.py", line 111, in install
      File "site-packages/conda/common/configuration.py", line 1382, in validate_configuration
      File "site-packages/conda/common/configuration.py", line 1379, in <genexpr>
      File "site-packages/conda/common/configuration.py", line 1373, in _collect_validation_error
      File "site-packages/conda/common/configuration.py", line 1219, in __get__
      File "site-packages/conda/common/configuration.py", line 571, in typify
      File "site-packages/conda/common/configuration.py", line 586, in _typify_data_structure
      File "site-packages/conda/common/configuration.py", line 586, in <genexpr>
      File "site-packages/conda/common/configuration.py", line 571, in typify
      File "site-packages/conda/common/configuration.py", line 584, in _typify_data_structure
      File "site-packages/conda/_vendor/frozendict.py", line 48, in __init__
      File "site-packages/conda/common/configuration.py", line 584, in <genexpr>
    AttributeError: 'YamlRawParameter' object has no attribute 'typify'

`$ /Users/gunnar/software/miniconda3/conda.exe install --offline --file /Users/gunnar/software/miniconda3/pkgs/env.txt -yp /Users/gunnar/software/miniconda3`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.```

### Conda info

_No response_

### Conda config

_No response_

### Conda list

_No response_

### Additional Context

_No response_

**Comment by gunnarvoet** [comment]
I found a similar issue in #10776 but that one is still open with no helpful information other than that it happened under Windows 10.

**Comment by gunnarvoet** [comment]
I solved the issue by removing an existing .condarc in my home directory.
