### ISSUE TITLE
`MatchSpec.conda_build_form()` expects `version` to be set

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#11200]
### Acceptance Criteria

- Provide a sensible default for `version` (e.g. `*`) when it is not set in the `conda_build_form` method of the MatchSpec class (https://github.com/conda/conda/blob/master/conda/models/match_spec.py#L374)

### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

The compatibility layer between conda-build and conda has some rough edges here and there. Here you can see one more.

`conda_build_form()` [expects the `version` field to be populated](https://github.com/conda/conda/blob/master/conda/models/match_spec.py#L374), otherwise it fails with an AssertionError. However, it could default to `*` instead of erroring out.

### Conda info

```shell
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/test_user/.condarc
 populated config files : 
          conda version : 4.11.0.post55+0c7211356
    conda-build version : 3.21.7
         python version : 3.7.11.final.0
       virtual packages : __linux=5.11.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/test_user/.conda/pkgs
       envs directories : /home/test_user/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.11.0.post55+0c7211356 requests/2.27.1 CPython/3.7.11 Linux/5.11.0-1028-azure debian/10 glibc/2.28
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### Conda config

```shell
Same as CI for Docker image
```

### Conda list

```shell
Same as CI for Docker image
```

### Additional Context

This is an error we are seeing while running the solver tests for libmamba. We are [patching the tests instead](https://github.com/conda/conda/pull/11193/commits/f26c643c713a1ef855eaa6cf503f1f2a40747c66), but I think it would be cleaner to fix this "bug".

**Comment by jaimergp** [comment]
Still an issue:

```
$ conda --version
conda 23.5.0
$ python
>>> from conda.models.match_spec import MatchSpec as MS
>>> MS("python", build="*123*").conda_build_form()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/.local/anaconda/lib/python3.9/site-packages/conda/models/match_spec.py", line 377, in conda_build_form
    assert version
AssertionError
```

**Comment by mmc1718** [comment]
I would like to work on this @travishathaway

I am curious to know why silently defaulting to * is preferred over making it mandatory somewhere to specify a version if setting build (looks like version is only required if build is set? https://github.com/conda/conda/blob/9c502c70092e4067377aa00fe236628ff3e07b44/docs/source/dev-guide/deep-dives/solvers.md?plain=1#L31)

**Comment by travishathaway** [comment]
@mmc1718,

When no version is specified, it's the same as using `*`, which means that we want the latest version of the package. The `build` field normal represents which Python version and platform the package is for. Below is an example of the full package name including the build string for `numpy`:

```
linux-aarch64/numpy-2.3.0-py313h8b4dbd4_0.conda
linux-aarch64/numpy-2.2.6-py313h8b4dbd4_0.conda
```

This part of the name: `py313h8b4dbd4_0` is the build string, and you can see that the first part begins with `py313`, which means it's for Python 3.13. The second part is a random hash that corresponds to the platform: `linux-aarch64` (Linux ARM architecture).

Normally, users wouldn't know they last part of the build string, but they would use a glob pattern to specify the first (`py313*`). So, if you specified `version=*` and `build=py313*` you would get the latest version of `numpy` for Python 3.13. If you could default `version=*`, you would eliminate the need to manually specify that, and it should line up with what a user would expect.

So, I think that's why it would make sense to have version default to that.

@jaimergp, am I missing anything here? Is this issue still important/relevant?

**Comment by jaimergp** [comment]
It used to be more important in the past because the `.conda_build_form()` was the only thing we could pass to `libmamba`. Nowadays we can pass full `MatchSpec` strings. However this is still a bug:

```
MatchSpec("python", build="*123*").conda_build_form()
```

and there's no reason to error there because there's a way to express that `MatchSpec` in `conda_build_form`: `python * *123*`.
