### ISSUE TITLE
conda install ipython not working correctly for python 2.7

### ISSUE THREAD

**Issue by pgp** [conda/conda#11205]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Follow these steps in order to create a Conda environment using python 2.7, and install ipython in it (via conda):
```sh
conda create -n py27 python=2.7
conda activate py27
conda install ipython
```
Now, when trying to run `ipython`, it crashes with the following backtrace:
```
Traceback (most recent call last):
  File "/home/pgp/miniconda3/envs/py27/bin/ipython", line 7, in <module>
    from IPython import start_ipython
  File "/home/pgp/miniconda3/envs/py27/lib/python2.7/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/home/pgp/miniconda3/envs/py27/lib/python2.7/site-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/home/pgp/miniconda3/envs/py27/lib/python2.7/site-packages/traitlets/config/__init__.py", line 6, in <module>
    from .application import *
  File "/home/pgp/miniconda3/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 17, in <module>
    from decorator import decorator
  File "/home/pgp/miniconda3/envs/py27/lib/python2.7/site-packages/decorator.py", line 162
    print('Error in generated code:', file=sys.stderr)
                                          ^
SyntaxError: invalid syntax

```
Same result when using `conda install -c conda-forge ipython`
Instead, if I install ipython via pip, everything works fine:
```
conda create -n py27 python=2.7
conda activate py27
pip install ipython
```

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : py27
    active env location : /home/pgp/miniconda3/envs/py27
            shell level : 1
       user config file : /home/pgp/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.10.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/pgp/miniconda3  (writable)
      conda av data dir : /home/pgp/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/pgp/miniconda3/pkgs
                          /home/pgp/.conda/pkgs
       envs directories : /home/pgp/miniconda3/envs
                          /home/pgp/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.8.3 Linux/5.10.0-051000-generic linuxmint/20 glibc/2.31
                UID:GID : 1000:1000
             netrc file : /home/pgp/.netrc
           offline mode : False
```

</details>

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/pgp/miniconda3/envs/py27:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaults
ca-certificates           2021.10.26           h06a4308_2    defaults
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
decorator                 5.1.0              pyhd3eb1b0_0    defaults
enum34                    1.1.6                    py27_1    defaults
ipython                   5.8.0                    py27_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
ncurses                   6.3                  h7f8727e_2    defaults
pathlib2                  2.3.5                    py27_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5                    py27_0    defaults
pip                       19.3.1                   py27_0    defaults
prompt_toolkit            1.0.15                   py27_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pygments                  2.5.2                      py_0    defaults
python                    2.7.18               ha1903f6_2    defaults
readline                  8.1.2                h7f8727e_1    defaults
scandir                   1.10.0             pyh5d7bf9c_3    defaults
setuptools                44.0.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.37.2               hc218d9a_0    defaults
tk                        8.6.11               h1ccaba5_0    defaults
traitlets                 4.3.3                    py27_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7f8727e_4    defaults
```

</details>

### Additional Context

OS: Linux Mint 20 x64

**Comment by kenodegard** [comment]
You can manually address this issue by downgrading the installed `decorator` package and also installing the `backports.functools_lru_cache` package:

```bash
conda install -n py27 decorator=4 backports.functools_lru_cache
```
