### ISSUE TITLE
Output corresponding package name when `InvalidVersionSpec` is raised

### ISSUE THREAD

**Issue by richardFontaine** [conda/conda#11203]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other feature requests and couldn't find a duplicate (including also the ``type-feature`` tag)
- [X] I confirmed that it's not related to another project (see the above section)

### What is the idea?

When `conda env export` fails with an `InvalidVersionSpec` exception, it would be nice if the error message included the name of the package whose metadata contains the invalid character.

### Why is this needed

Including dependencies, I have hundreds of packages in my environment. It's incredibly difficult to track down which package causes an InvalidVersionSpec exception. If I had this information, I could try using a different version of the package, raise an issue with the maintainers, manually change the metadata on my local machine, or get rid of the package altogether. Without this information, I'm flying blind.

### What should happen?

When `conda env export` fails with an `InvalidVersionSpec` exception, the error message would be something like
`Invalid version <something>: invalid character(s). Dependency of <insert package here>`

### Additional Context

Here is the traceback of an error I got after calling `conda env export -v --no-builds -n base`:
```
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '>=4.2.2<6.0.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 38, in __call__
    return cls._cache_[arg]
KeyError: '4.2.2<6.0.0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/conda/exceptions.py", line 1080, in __call__
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/opt/conda/lib/python3.8/site-packages/conda_env/cli/main_export.py", line 109, in execute
    env = from_environment(name, prefix, no_builds=args.no_builds,
  File "/opt/conda/lib/python3.8/site-packages/conda_env/env.py", line 109, in from_environment
    precs = tuple(PrefixGraph(pd.iter_records()).graph)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/prefix_graph.py", line 39, in __init__
    parent_match_specs = tuple(MatchSpec(d) for d in node.depends)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/prefix_graph.py", line 39, in <genexpr>
    parent_match_specs = tuple(MatchSpec(d) for d in node.depends)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/match_spec.py", line 55, in __call__
    return super(MatchSpecType, cls).__call__(**parsed)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/match_spec.py", line 177, in __init__
    self._match_components = self._build_components(**kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/match_spec.py", line 403, in _build_components
    return frozendict(_make_component(key, value) for key, value in iteritems(kwargs))
  File "/opt/conda/lib/python3.8/site-packages/conda/models/match_spec.py", line 403, in <genexpr>
    return frozendict(_make_component(key, value) for key, value in iteritems(kwargs))
  File "/opt/conda/lib/python3.8/site-packages/conda/models/match_spec.py", line 417, in _make_component
    matcher = _implementors[field_name](value)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 40, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 497, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 546, in get_matcher
    self.matcher_vo = VersionOrder(vo_str)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 40, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "/opt/conda/lib/python3.8/site-packages/conda/models/version.py", line 172, in __init__
    raise InvalidVersionSpec(vstr, "invalid character(s)")
conda.exceptions.InvalidVersionSpec: Invalid version '4.2.2<6.0.0': invalid character(s)
```

I was eventually able to resolve the issue by adding the `--from-history` flag, but I don't think that's an ideal solution.

There have been other issues raised here concerning `InvalidVersionSpec`, such as #9624, but the solutions given there vary wildly and only work for specific packages. I think adding this feature would make the issue much more solvable for a developer who encounters it. 

From looking at the traceback and the codebase, I think a good solution would be to put a try-except [here](https://github.com/conda/conda/blob/master/conda/models/prefix_graph.py#L39), and print the name of the node along with the error message.

**Comment by ZeroCool2u** [comment]
Yeah, this issue has currently made me unable to reproduce one of my conda environments at all.

**Comment by apayne97** [comment]
Also experiencing this!

**Comment by cramsuig** [comment]
Still an issue

**Comment by ekomarova** [comment]
I'm observing the same thing in 23.3.1:
```
Traceback (most recent call last):
    File "C:\Miniconda3\lib\site-packages\conda\models\version.py", line 40, in __call__
      return cls._cache_[arg]
  KeyError: '>=0.10.0,<1.0.0<py312|>=0.13.0,<1.0.0>=py312'
```

**Comment by jaimergp** [comment]
The more pressing issue is why these invalid version specs are making it into the package. Sounds like it should be validated in conda-build to begin with.

**Comment by wolfv** [comment]
FYI we just added strict and lenient parsing modes to `rattler`: https://github.com/mamba-org/rattler/pull/552

Lenient is supposed to be used in `pixi` and strict in `rattler-build` – so that hopefully we don't see invalid matchspecs in packages in the future.
