### ISSUE TITLE
conda install <pkg>  hangs 

### ISSUE THREAD

**Issue by hwshen** [conda/conda#1121]
Hi, 

I cannot seem to run  'conda install <pkg>'  or anything related on my Mac. It always hangs and comes back with the message: 

------
Fetching package metadata: ..An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/hwshen/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 224, in install
    unknown=args.unknown, json=args.json)
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 416, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/api.py", line 40, in get_index
    unknown=unknown)
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 197, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 397, in result
    return self.__get_result()
  File "/Users/hwshen/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
socket.error: [Errno 54] Connection reset by peer

****************************************

Below is my conda info: 

Current conda install:

             platform : osx-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : /Users/hwshen/anaconda  (writable)
  default environment : /Users/hwshen/anaconda
     envs directories : /Users/hwshen/anaconda/envs
        package cache : /Users/hwshen/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False

*********

Could you please help? thanks.

**Comment by asmeurer** [comment]
Do you have a proxy?

**Comment by hwshen** [comment]
At first, I did not know what you meant. By then I thought maybe it was because I was using our school's wireless. Just tried it at home, and it worked!!
Thank you so much. But, just curious, can you explain it what the problem was? Many students might run into the same problem if the use our school (ohio state u.)'s wireless networks. 
Thanks again!

**Comment by asmeurer** [comment]
You need to set your proxies. Setting them in the Mac Network System Preferences should work. For other platforms (or if that doesn't work), set the proxy settings in the `.condarc` file (see http://conda.pydata.org/docs/config.html). As to what those settings are, you'll have to check with your school's IT documentation.

**Comment by asmeurer** [comment]
I suppose it's also possible that it's not a proxy but rather that the network just blocks things (because school IT departments like to do that). I hope you find a way to work around it.

**Comment by hwshen** [comment]
Thanks! I will look into both issues. Speaking of school IT people like to block things - you bet!! Today I just learned our school's Microsoft Exchange server decided to block the newly available Microsoft outlook  app for iOS. Blocking their own software? Really?! :-) 
Thanks again.
