### ISSUE TITLE
Corrupt base environment

### ISSUE THREAD

**Issue by sabrsyed** [conda/conda#11219]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

<details>
<summary><code>conda env list</code></summary>

```
[syeds@sumner-log1 envs]$ conda env list
Traceback (most recent call last):
  File "/home/syeds/bin/miniconda3/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/plan.py", line 25, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 13, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/download.py", line 14, in <module>
    from .session import CondaSession
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/session.py", line 13, in <module>
    from .adapters.s3 import S3Adapter
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/conda/gateways/connection/adapters/s3.py", line 14, in <module>
    boto3.client('s3')  # https://github.com/conda/conda/issues/8993
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/boto3/__init__.py", line 83, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/boto3/session.py", line 258, in client
    return self._session.create_client(
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/session.py", line 815, in create_client
    credentials = self.get_credentials()
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/session.py", line 442, in get_credentials
    self._credentials = self._components.get_component(
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/credentials.py", line 1084, in load_credentials
    creds = provider.load()
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/credentials.py", line 489, in load
    metadata = fetcher.retrieve_iam_role_credentials()
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/utils.py", line 174, in retrieve_iam_role_credentials
    r = self._get_request(url, timeout, num_attempts)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/utils.py", line 159, in _get_request
    response = requests.get(url, timeout=timeout)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/adapters.py", line 360, in send
    resp = conn.urlopen(
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 542, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/home/syeds/bin/miniconda3/lib/python3.9/site-packages/botocore/vendored/requests/packages/urllib3/connectionpool.py", line 349, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/syeds/bin/miniconda3/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
TypeError: _send_request() takes 5 positional arguments but 6 were given
```

</details>

### Conda info

`conda info` throws the same error!

```shell
...
TypeError: _send_request() takes 5 positional arguments but 6 were given
```

### Conda config

```shell
==> /home/syeds/.condarc <==
changeps1: False
channels:
  - conda-canary
  - bioconda
  - conda-forge
  - defaults
always_yes: True
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/syeds/bin/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
argcomplete               1.12.3                   pypi_0    pypi
asciitree                 0.3.3                    pypi_0    pypi
autouri                   0.2.6                    pypi_0    pypi
awscli                    1.11.18                  pypi_0    pypi
boto3                     1.4.3                    pypi_0    pypi
botocore                  1.4.75                   pypi_0    pypi
brotlipy                  0.7.0           py39h3811e60_1001    conda-forge
bullet                    2.2.0                    pypi_0    pypi
bwa                       0.7.17               h5bf99c6_8    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                5.0.0                    pypi_0    pypi
cairo                     1.16.0            h18b612c_1001    conda-forge
caper                     2.1.2                    pypi_0    pypi
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.14.6           py39he32792d_0    conda-forge
chardet                   4.0.0            py39hf3d152e_1    conda-forge
click                     8.0.1            py39hf3d152e_0    conda-forge
colorama                  0.3.7                    pypi_0    pypi
coloredlogs               15.0.1                   pypi_0    pypi
conda                     4.11.0           py39hf3d152e_0    conda-forge
conda-package-handling    1.7.3            py39h3811e60_0    conda-forge
cooler                    0.8.11                   pypi_0    pypi
coreutils                 8.25                          1    bioconda
croo                      0.6.0                    pypi_0    pypi
cryptography              3.4.7            py39hbca0aa6_0    conda-forge
curl                      7.71.1               he644dc0_3    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cytoolz                   0.10.1                   pypi_0    pypi
dateparser                1.1.0                    pypi_0    pypi
dill                      0.3.4                    pypi_0    pypi
docker                    5.0.3                    pypi_0    pypi
docutils                  0.18.1                   pypi_0    pypi
filelock                  3.4.2                    pypi_0    pypi
fontconfig                2.13.1            hba837de_1005    conda-forge
fonttools                 4.29.1                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
glib                      2.69.1               h5202010_0    defaults
google-api-core           2.5.0                    pypi_0    pypi
google-auth               2.6.0                    pypi_0    pypi
google-cloud-core         2.2.2                    pypi_0    pypi
google-cloud-storage      2.1.0                    pypi_0    pypi
google-crc32c             1.3.0                    pypi_0    pypi
google-resumable-media    2.1.0                    pypi_0    pypi
googleapis-common-protos  1.54.0                   pypi_0    pypi
graphite2                 1.3.14               h23475e2_0    defaults
h5py                      3.4.0                    pypi_0    pypi
harfbuzz                  2.8.1                h6f93f22_0    defaults
htslib                    1.9                  h4da6232_3    bioconda
humanfriendly             10.0                     pypi_0    pypi
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        4.10.1                   pypi_0    pypi
java-jdk                  8.0.112                       1    bioconda
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h36c2ea0_0    conda-forge
kiwisolver                1.3.2                    pypi_0    pypi
krb5                      1.17.2               h926e7f8_0    conda-forge
lark                      1.0.0                    pypi_0    pypi
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libcurl                   7.71.1               hcdd3856_3    conda-forge
libdeflate                1.2                  h516909a_1    bioconda
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 11.2.0               h1d223b6_8    conda-forge
libgfortran-ng            11.2.0               h69a702a_8    conda-forge
libgfortran5              11.2.0               h5c6108e_8    conda-forge
libgomp                   11.2.0               h1d223b6_8    conda-forge
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libssh2                   1.10.0               ha56f1ee_0    conda-forge
libstdcxx-ng              11.2.0               he4da1e4_8    conda-forge
libtiff                   4.0.9             h648cc4a_1002    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.9.12               h03d6c58_0    defaults
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
matplotlib                3.5.1                    pypi_0    pypi
miniwdl                   1.4.3                    pypi_0    pypi
multiprocess              0.70.12.2                pypi_0    pypi
ncurses                   6.2                  h58526e2_4    conda-forge
numpy                     1.21.2           py39hdbf815f_0    conda-forge
openjdk                   8.0.112          zulu8.19.0.1_3    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pairix                    0.3.7            py39hd1f1204_3    bioconda
pairtools                 0.3.0            py39h8fa6add_5    bioconda
pandas                    1.3.2                    pypi_0    pypi
pango                     1.42.4               h7062337_4    conda-forge
pbgzip                    2016.08.04           h36cd882_2    bioconda
pcre                      8.45                 h9c3ff4c_0    conda-forge
perl                      5.32.1          0_h7f98852_perl5    conda-forge
picard                    2.26.10              hdfd78af_0    bioconda
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.9.0                    pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycosat                   0.6.3           py39h3811e60_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyfaidx                   0.6.2                    pypi_0    pypi
pygtail                   0.11.1                   pypi_0    pypi
pyhocon                   0.3.59                   pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pypairix                  0.3.7                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pysocks                   1.7.1            py39hf3d152e_3    conda-forge
python                    3.9.5                h12debd9_4    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python-graphviz           0.19.1                   pypi_0    pypi
python-json-logger        2.0.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.1                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
r-base                    3.2.2                         0    defaults
readline                  8.1                  h46c0cb4_0    conda-forge
regex                     2022.1.18                pypi_0    pypi
requests                  2.25.1             pyhd3deb0d_0    conda-forge
rsa                       3.4.2                    pypi_0    pypi
ruamel_yaml               0.15.80         py39h3811e60_1004    conda-forge
s3transfer                0.1.13                   pypi_0    pypi
samtools                  1.7                           1    bioconda
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
setuptools                58.0.4           py39hf3d152e_0    conda-forge
simplejson                3.17.5                   pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h9cd32fc_1    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.11               h27826a3_1    conda-forge
toolz                     0.11.1                   pypi_0    pypi
tqdm                      4.62.2             pyhd8ed1ab_0    conda-forge
tzdata                    2021.5                   pypi_0    pypi
tzlocal                   4.1                      pypi_0    pypi
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
websocket-client          1.2.3                    pypi_0    pypi
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xdg                       5.1.1                    pypi_0    pypi
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11            h516909a_1010    conda-forge
```

</details>

**Comment by kenodegard** [comment]
This is likely due to `botocore` version 1.4.75 (released Nov 17, 2016) being incompatible with Python 3.9 (released Oct 5, 2020).

Aside from that it is not ideal to be installing all of your packages into the base environment as you risk corrupting your `conda` installation as has happened here where the only surefire way to fix the issue is to reinstall `conda`. We instead recommended using separate environments for your installs.
