### ISSUE TITLE
trying to install git using conda

### ISSUE THREAD

**Issue by ugottopumpitup** [conda/conda#11226]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

In order to not upgrade to 14.4 c++ visual studio on my system, I'm trying to install git using PyCharm IDE. Each time I've tried to install git, Ive been getting closer to victory but my issue runs with needing to install cytools. Ive had to install many other programs like, conda, auxlib , ruamel_yaml and now I'm finally at cytools again. I've needed to install Visual 14.4 C++ on my system anyway through this time... now that I have, what am I missing to solve this error?

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
               platform : win-32
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.8.3.final.0
       requests version : 2.26.0
       root environment : c:\users\builderyupbase\pycharmprojects\buildersproject\venvironment  (writable)
    default environment : c:\users\builderyupbase\pycharmprojects\buildersproject\venvironment
       envs directories : c:\users\builderyupbase\pycharmprojects\buildersproject\venvironment\envs
          package cache : c:\users\builderyupbase\pycharmprojects\buildersproject\venvironment\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-32/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

</details>

### Conda config

_No output_

### Conda list

```shell
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-32
```

### Additional Context

<details>
<summary><code>conda install ujson</code></summary>

```
$ c:\users\builder\pycharmprojects\buildersproject\venvironment\Scripts\conda install ujson`

    Traceback (most recent call last):
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\install.py", line 201, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'c:\\users\\builder\\pycharmprojects\\buildersproject\\venvironment\\pkgs\\menuinst-1.4.7-py36_0\\info\\has_prefix'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\install.py", line 209, in yield_lines
        raise StopIteration
    StopIteration

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\install.py", line 943, in link
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\install.py", line 248, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\install.py", line 248, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\install.py", line 247, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "c:\users\builder\pycharmprojects\buildersproject\venvironment\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration
```

</details>

**Comment by kenodegard** [comment]
You are running an old version of `conda` (4.2.7 was released in 2016). Can you install the latest version?

Feel free to use either the [miniconda](https://docs.conda.io/en/latest/miniconda.html) or [anaconda](https://www.anaconda.com/products/individual#windows) installer whichever is more appropriate for your needs.

Once you have `conda` installed you will be able to run:

```cmd.exe
> conda create --name git git
> conda activate git
(git) > git
```

**Comment by ugottopumpitup** [comment]
Thank you sir am trying this now

**Comment by ugottopumpitup** [comment]
I also did not install https://git-scm.com/download/win

**Comment by ugottopumpitup** [comment]
> PS C:\Users\builderyupbase\PycharmProjects\pythonProject\official coin code\tutorial> conda create --name git git
Traceback (most recent call last):
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main    
    return _run_code(code, main_globals, None,
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\builderyupbase\AppData\Local\Programs\Python\Python38-32\Scripts\conda.exe\__main__.py", line 4, in <module>
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\cli\main.py", line 46, in <module>   
    from ..base.context import context
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\base\context.py", line 20, in <module>
    from ..common.url import urlparse, path_to_url
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\common\url.py", line 17, in <module>
    from requests.packages.urllib3.util.url import parse_url
ModuleNotFoundError: No module named 'requests'

**Comment by kenodegard** [comment]
How did you install `conda`?

**Comment by ugottopumpitup** [comment]
I tried this, I just restarted VS

PS C:\Users\builderyupbase\PycharmProjects\pythonProject\official coin code\tutorial> pip install conda
Requirement already satisfied: conda in c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages (4.2.7)

**Comment by kenodegard** [comment]
The `conda` package available on PyPA is outdated and installing via `pip` is not recommended as it is an unsupported way of getting `conda` properly configured. Before proceeding I suggest uninstalling this version to avoid calling the wrong executable.

Given what you are attempting to do there are two possible ways to install `conda`, as a standalone application or as a VS extension:

1. As a standalone application you'd need to use either the [miniconda](https://docs.conda.io/en/latest/miniconda.html) or [anaconda](https://www.anaconda.com/products/individual#windows) installer. After installing open the **Command Prompt** from the **Start menu** and run `where conda`. You should see a path similar to `%HOMEDRIVE%%HOMEPATH%\miniconda3\condabin\conda.bat` or `%HOMEDRIVE%%HOMEPATH%\anaconda3\condabin\conda.bat` depending on the installer used.

    If `conda` is working properly on the **Command Prompt** it should then also be working correctly within VS.

2. Alternatively use the Miniconda/Anaconda extension for VS, please follow instructions [here](https://docs.microsoft.com/en-us/visualstudio/python/managing-python-environments-in-visual-studio?view=vs-2022#conda-environments).

**Comment by ugottopumpitup** [comment]
from command prompt

Microsoft Windows [Version 10."x"]
(c) Microsoft Corporation. All rights reserved.

C:\Users\builderyupbase>where conda
C:\Users\builderyupbase\AppData\Local\Programs\Python\Python38-32\Scripts\conda.exe

C:\Users\builderyupbase>conda install git
Traceback (most recent call last):
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\builderyupbase\AppData\Local\Programs\Python\Python38-32\Scripts\conda.exe\__main__.py", line 4, in <module>
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\cli\main.py", line 46, in <module>
    from ..base.context import context
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\base\context.py", line 20, in <module>
    from ..common.url import urlparse, path_to_url
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\common\url.py", line 17, in <module>
    from requests.packages.urllib3.util.url import parse_url
ModuleNotFoundError: No module named 'requests'

C:\Users\builderyupbase>conda create --name git git
Traceback (most recent call last):
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\builderyupbase\AppData\Local\Programs\Python\Python38-32\Scripts\conda.exe\__main__.py", line 4, in <module>
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\cli\main.py", line 46, in <module>
    from ..base.context import context
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\base\context.py", line 20, in <module>
    from ..common.url import urlparse, path_to_url
  File "c:\users\builderyupbase\appdata\local\programs\python\python38-32\lib\site-packages\conda\common\url.py", line 17, in <module>
    from requests.packages.urllib3.util.url import parse_url
ModuleNotFoundError: No module named 'requests'

**Comment by ugottopumpitup** [comment]
please tell me your fiverr friend

**Comment by kenodegard** [comment]
This has become too specific to your particular setup and is hence out of scope for the support that we provide here on GitHub. Feel free to ask your questions on the [Nucleus Community](https://community.anaconda.cloud/).
