### ISSUE TITLE
Conda creates s3 client even when it is not needed and fails when AWS is misconfigured

### ISSUE THREAD

**Issue by usamec** [conda/conda#11220]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

When AWS is misconfigured (and my conda does not need anything from AWS!) the conda does not work.
Same thing happens when you use AWS SSO, etc. This dependency is totally counter intuitive and makes conda feel like PHP.

```
(base) usama@cpu09:~$ conda --version
conda 4.10.3
(base) usama@cpu09:~$ conda env list
# conda environments:
#
base                  *  /home/usama/miniconda3
rtdl                     /home/usama/miniconda3/envs/rtdl
torch19                  /home/usama/miniconda3/envs/torch19

(base) usama@cpu09:~$ export AWS_PROFILE=junk
(base) usama@cpu09:~$ conda env list
Traceback (most recent call last):
  File "/home/usama/miniconda3/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/plan.py", line 25, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 13, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/core/package_cache_data.py", line 14, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/download.py", line 14, in <module>
    from .session import CondaSession
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/session.py", line 13, in <module>
    from .adapters.s3 import S3Adapter
  File "/home/usama/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/adapters/s3.py", line 14, in <module>
    boto3.client('s3')  # https://github.com/conda/conda/issues/8993
  File "/home/usama/miniconda3/lib/python3.8/site-packages/boto3/__init__.py", line 93, in client
    return _get_default_session().client(*args, **kwargs)
  File "/home/usama/miniconda3/lib/python3.8/site-packages/boto3/__init__.py", line 81, in _get_default_session
    setup_default_session()
  File "/home/usama/miniconda3/lib/python3.8/site-packages/boto3/__init__.py", line 35, in setup_default_session
    DEFAULT_SESSION = Session(**kwargs)
  File "/home/usama/miniconda3/lib/python3.8/site-packages/boto3/session.py", line 80, in __init__
    self._setup_loader()
  File "/home/usama/miniconda3/lib/python3.8/site-packages/boto3/session.py", line 120, in _setup_loader
    self._loader = self._session.get_component('data_loader')
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/session.py", line 714, in get_component
    return self._components.get_component(name)
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/session.py", line 991, in get_component
    self._components[name] = factory()
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/session.py", line 160, in <lambda>
    lambda: create_loader(self.get_config_variable('data_path')))
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/session.py", line 267, in get_config_variable
    return self.get_component('config_store').get_config_variable(
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/configprovider.py", line 374, in get_config_variable
    return provider.provide()
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/configprovider.py", line 567, in provide
    value = provider.provide()
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/configprovider.py", line 655, in provide
    scoped_config = self._session.get_scoped_config()
  File "/home/usama/miniconda3/lib/python3.8/site-packages/botocore/session.py", line 367, in get_scoped_config
    raise ProfileNotFound(profile=profile_name)
botocore.exceptions.ProfileNotFound: The config profile (junk) could not be found
```

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /home/usama/miniconda3
            shell level : 1
       user config file : /home/usama/.condarc
 populated config files : /home/usama/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.8.10.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/usama/miniconda3  (writable)
      conda av data dir : /home/usama/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/usama/miniconda3/pkgs
                          /home/usama/.conda/pkgs
       envs directories : /home/usama/miniconda3/envs
                          /home/usama/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.25.1 CPython/3.8.10 Linux/5.4.0-88-generic ubuntu/20.04.1 glibc/2.31
                UID:GID : 1037:1037
             netrc file : None
           offline mode : False
```

</details>

### Conda config

<details>
<summary><code>conda info</code></summary>

```shell
==> /home/usama/.condarc <==
channels:
  - bioconda
  - defaults
```

</details>

### Conda list

<details>
<summary><code>conda info</code></summary>

```shell
# packages in environment at /home/usama/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
boto3                     1.21.0                   pypi_0    pypi
botocore                  1.24.0                   pypi_0    pypi
brotlipy                  0.7.0           py38h27cfd23_1003    defaults
ca-certificates           2021.7.5             h06a4308_1    defaults
certifi                   2021.5.30        py38h06a4308_0    defaults
cffi                      1.14.6           py38h400218f_0    defaults
chardet                   4.0.0           py38h06a4308_1003    defaults
conda                     4.10.3           py38h06a4308_0    defaults
conda-package-handling    1.7.3            py38h27cfd23_1    defaults
cryptography              3.4.7            py38hd23ed53_0    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
jmespath                  0.10.0                   pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
ncurses                   6.2                  he6710b0_1    defaults
openssl                   1.1.1k               h27cfd23_0    defaults
pip                       21.1.3           py38h06a4308_0    defaults
pycosat                   0.6.3            py38h7b6447c_1    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.10               h12debd9_8    defaults
python-dateutil           2.8.2                    pypi_0    pypi
readline                  8.1                  h27cfd23_0    defaults
requests                  2.25.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py38h27cfd23_0    defaults
s3transfer                0.5.1                    pypi_0    pypi
setuptools                52.0.0           py38h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hc218d9a_0    defaults
tk                        8.6.10               hbc83047_0    defaults
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

</details>

### Additional Context

Conda info actually does not work, when AWS is misconfigured.
Might be related to this https://github.com/conda/conda/pull/10759

**Comment by jezdez** [comment]
Yeah, we've fixed this again in #11038 and will ship it in the next release.
