### ISSUE TITLE
libmamba solver raises exception

### ISSUE THREAD

**Issue by jezdez** [conda/conda#11222]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

When I tried the steps in https://github.com/conda-incubator/conda-libmamba-solver I was able to run the new libmamba solver but got the following exception:

```

----       USING EXPERIMENTAL LIBMAMBA INTEGRATIONS       ----
    This is a highly experimental product. If something is
    not working as expected, please submit an issue at
    https://github.com/conda/conda and attach the log file
    found in the following path. Thank you!

    /Users/jezdez/.asdf/installs/python/miniconda3-latest/pkgs/.logs/20220215-170540-084447.log

---------------------------------------------------------------

pkgs/r/osx-64                                                 No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                   795.7kB @   1.7MB/s  0.5s
pkgs/main/osx-64                                     4.1MB @   4.2MB/s  1.2s

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/cli/install.py", line 260, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 269, in solve_final_state
        self._export_solved_records(in_state, out_state, index)
      File "/Users/jezdez/.asdf/installs/python/miniconda3-latest/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 587, in _export_solved_records
        transaction = api.Transaction(self.solver, api.MultiPackageCache(context.pkgs_dirs))
    TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
        1. libmambapy.bindings.Transaction(arg0: mamba::MSolver, arg1: libmambapy.bindings.MultiPackageCache, arg2: List[libmambapy.bindings.Repo])

    Invoked with: <libmambapy.bindings.Solver object at 0x7f9558573570>, <libmambapy.bindings.MultiPackageCache object at 0x7f9558571bf0>

`$ /Users/jezdez/.asdf/installs/python/miniconda3-latest/bin/conda create -n demo scipy --dry-run --experimental-solver=libmamba`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/jezdez/.asdf/installs/python/miniconda3-latest/bin/conda
         CONDA_PYTHON_EXE=/Users/jezdez/.asdf/installs/python/miniconda3-latest/bin/python
               CONDA_ROOT=/Users/jezdez/.asdf/installs/python/miniconda3-latest
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/jezdez/.asdf/installs/python/miniconda3-latest/bin:/Users/jezde
                          z/.asdf/installs/python/miniconda3-latest/condabin:/Users/jezdez/.asdf
                          /shims:/usr/local/opt/asdf/libexec/bin:/Users/jezdez/.poetry/bin:/User
                          s/jezdez/.cargo/bin:/Users/jezdez/.local/bin:/Users/jezdez/.cargo/bin:
                          /Applications/Postgres.app/Contents/Versions/latest/bin:/usr/local/sha
                          re/npm/bin:/usr/local/Cellar/gems/1.9/bin:/usr/local/Cellar/ruby/1.9.3
                          -p362/bin:/Users/jezdez/bin:/usr/local/bin:/usr/local/sbin:/usr/local/
                          Library/Contributions/examples:/usr/local/bin:/usr/bin:/bin:/usr/sbin:
                          /sbin:/Applications/VMware
                          Fusion.app/Contents/Public:/usr/local/MacGPG2/bin:/Applications/Little
                          Snitch.app/Contents/Components:/opt/X11/bin:/Library/Apple/usr/bin:/De
                          veloper/usr/bin:/usr/local/opt/go/libexec/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/jezdez/.condarc
 populated config files : /Users/jezdez/.condarc
          conda version : 4.11.0.73_gb1ea4be80
    conda-build version : 3.21.7
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/jezdez/.asdf/installs/python/miniconda3-latest  (writable)
      conda av data dir : /Users/jezdez/.asdf/installs/python/miniconda3-latest/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jezdez/.asdf/installs/python/miniconda3-latest/pkgs
                          /Users/jezdez/.conda/pkgs
       envs directories : /Users/jezdez/.asdf/installs/python/miniconda3-latest/envs
                          /Users/jezdez/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0.73_gb1ea4be80 requests/2.25.1 CPython/3.9.5 Darwin/21.3.0 OSX/10.16
                UID:GID : 503:20
             netrc file : /Users/jezdez/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

info     Freeing pool.
info     Freeing solver.
```

### Conda info

```shell
active environment : None
            shell level : 0
       user config file : /Users/jezdez/.condarc
 populated config files : /Users/jezdez/.condarc
          conda version : 4.11.0.73_gb1ea4be80
    conda-build version : 3.21.7
         python version : 3.9.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/jezdez/.asdf/installs/python/miniconda3-latest  (writable)
      conda av data dir : /Users/jezdez/.asdf/installs/python/miniconda3-latest/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jezdez/.asdf/installs/python/miniconda3-latest/pkgs
                          /Users/jezdez/.conda/pkgs
       envs directories : /Users/jezdez/.asdf/installs/python/miniconda3-latest/envs
                          /Users/jezdez/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0.73_gb1ea4be80 requests/2.25.1 CPython/3.9.5 Darwin/21.3.0 OSX/10.16
                UID:GID : 503:20
             netrc file : /Users/jezdez/.netrc
           offline mode : False
```

### Conda config

```shell
==> /Users/jezdez/.condarc <==
ssl_verify: True
channels:
  - defaults
report_errors: False
```

### Conda list

```shell
# packages in environment at /Users/jezdez/.asdf/installs/python/miniconda3-latest:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.10.0             pyh06a4308_0    defaults
brotlipy                  0.7.0           py39h9ed2024_1003    defaults
bzip2                     1.0.8                h1de35cc_0    defaults
c-ares                    1.18.1               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py39h6e9494a_1    conda-forge
cffi                      1.14.6           py39h2125817_0    defaults
chardet                   4.0.0           py39hecd8cb5_1003    defaults
conda                     4.11.0.73_gb1ea4be80          py39_0    conda-canary/label/conda-conda-pr-11193
conda-build               3.21.7           py39hecd8cb5_0    defaults
conda-libmamba-solver     22.2.0.25_gaaa86a9            py_0    conda-canary/label/conda-libmamba-solver-pr-3
conda-package-handling    1.7.3            py39h9ed2024_1    defaults
cryptography              3.4.7            py39h2fd3fbb_0    defaults
filelock                  3.4.2              pyhd3eb1b0_0    defaults
glob2                     0.7                pyhd3eb1b0_0    defaults
icu                       58.2                 h0a44026_3    defaults
idna                      2.10               pyhd3eb1b0_0    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
krb5                      1.19.2               hcfbf3a7_0    conda-forge
libarchive                3.5.2                h2b60450_1    conda-forge
libcurl                   7.81.0               hf45b732_0    conda-forge
libcxx                    12.0.1               habf9029_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  hb1e8313_2    defaults
libiconv                  1.16                 h1de35cc_0    defaults
liblief                   0.10.1               h23ab428_1    defaults
libmamba                  0.21.2               h9ce2d19_0    conda-forge
libmambapy                0.21.2           py39h2c464dc_0    conda-forge
libnghttp2                1.46.0               h6f36284_0    conda-forge
libsolv                   0.7.19               hcf210ce_5    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libxml2                   2.9.12               hcdb78fc_0    defaults
libzlib                   1.2.11            h9173be1_1013    conda-forge
lz4-c                     1.9.3                h23ab428_1    defaults
lzo                       2.10              haf1e3a3_1000    conda-forge
markupsafe                2.0.1            py39h9ed2024_0    defaults
ncurses                   6.2                  h0a44026_1    defaults
openssl                   1.1.1l               h0d85af4_0    conda-forge
pip                       21.2.4           py39hecd8cb5_0    defaults
pkginfo                   1.8.2              pyhd3eb1b0_0    defaults
psutil                    5.8.0            py39h9ed2024_1    defaults
py-lief                   0.10.1           py39h23ab428_1    defaults
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3            py39h9ed2024_0    defaults
pycparser                 2.20                       py_2    defaults
pyopenssl                 20.0.1             pyhd3eb1b0_1    defaults
pysocks                   1.7.1            py39hecd8cb5_0    defaults
python                    3.9.5                h88f2d9e_3    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python.app                3                py39h9ed2024_0    defaults
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd3eb1b0_0    defaults
pyyaml                    6.0              py39hca72f7f_1    defaults
readline                  8.1                  h9ed2024_0    defaults
reproc                    14.2.3               h0d85af4_0    conda-forge
reproc-cpp                14.2.3               he49afe7_0    conda-forge
requests                  2.25.1             pyhd3eb1b0_0    defaults
ripgrep                   12.1.1                        0    defaults
ruamel_yaml               0.15.100         py39h9ed2024_0    defaults
setuptools                52.0.0           py39hecd8cb5_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
sqlite                    3.36.0               hce871da_0    defaults
tk                        8.6.10               hb0a8c7a_0    defaults
tqdm                      4.61.2             pyhd3eb1b0_1    defaults
tzdata                    2021a                h52ac0ba_0    defaults
urllib3                   1.26.6             pyhd3eb1b0_1    defaults
wheel                     0.36.2             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1de35cc_0    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
yaml-cpp                  0.6.3                hb1e8313_4    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

**Comment by jezdez** [comment]
> Oops, can you check with the instructions at [conda-incubator/conda-libmamba-solver#6](https://github.com/conda-incubator/conda-libmamba-solver/pull/6)? I think the version on the PR label is out of date.

Hmm, those instructions didn't work:

```
❯ conda install --override-channels -c conda-canary/label/conda-conda-pr-11193 -c conda-canary/label/conda-libmamba-solver-dev -c conda-forge -c defaults conda conda-libmamba-solver
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - conda-libmamba-solver

Current channels:

  - https://conda.anaconda.org/conda-canary/label/conda-conda-pr-11193/osx-64
  - https://conda.anaconda.org/conda-canary/label/conda-conda-pr-11193/noarch
  - https://conda.anaconda.org/conda-canary/label/conda-libmamba-solver-dev/osx-64
  - https://conda.anaconda.org/conda-canary/label/conda-libmamba-solver-dev/noarch
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by jaimergp** [comment]
Hm, I guess it wasn't uploaded on the `main` push.

For now, I triggered a new build for PR3 branch, but it got a smaller version (because it was squashed), so update manually with:

```
$ conda install https://anaconda.org/conda-canary/conda-libmamba-solver/22.2.0.2_geb8c069/download/noarch/conda-libmamba-solver-22.2.0.2_geb8c069-py_0.tar.bz2
```

**Comment by jaimergp** [comment]
Try with 

```
$ conda install https://anaconda.org/conda-canary/conda-libmamba-solver/22.2.0.11_g432a93e/download/noarch/conda-libmamba-solver-22.2.0.11_g432a93e-py_0.tar.bz2
```

**Comment by jezdez** [comment]
That worked, thanks!
