### ISSUE TITLE
Hicexplorer and py38 with conda for macOS ARM

### ISSUE THREAD

**Issue by giuliospinozzi** [conda/conda#11284]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I installed in my debian workstation hicexplorer with conda and py37 without any issue. I would like to install hicexplorer in my macbook pro m1max with 64gb of RAM, but I cannot. For Apple silicon is available with conda only py38 and when I try to install hicexplorer I receive a general dependency error and the installation crash.
Can you fix the compatibility with py38? Is the only way for apple silicon cpu.

The command in a clean installation of miniconda:

<details>
<summary><code>conda install -n hic hicexplorer -c bioconda -c conda-forge -v</code></summary>

```
% conda install -n hic hicexplorer -c bioconda -c conda-forge -v
Collecting package metadata (current_repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/bioconda/osx-arm64/current_repodata.json

Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/r/osx-arm64/current_repodata.json

Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/bioconda/osx-arm64/repodata.json

Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/r/osx-arm64/repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): ...working... Unable to retrieve repodata (response: 404) for https://conda.anaconda.org/bioconda/osx-arm64/repodata.json

Unable to retrieve repodata (response: 404) for https://repo.anaconda.com/pkgs/r/osx-arm64/repodata.json

done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Solving environment: ...working...
Found conflicts! Looking for incompatible packages.
This can take several minutes. Press CTRL-C to abort.
failed
Traceback (most recent call last):
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 259, in install
unlink_link_transaction = solver.solve_for_transaction(
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
ssc = self._run_sat(ssc)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
return f(*args, **kwds)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
return f(*args, **kwds)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/resolve.py", line 1320, in solve
raise UnsatisfiableError({})
conda.exceptions.UnsatisfiableError:
Did not find conflicting dependencies. If you would like to know which
packages conflict ensure that you have enabled unsatisfiable hints.

conda config --set unsatisfiable_hints True

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1080, in call
return func(*args, **kwargs)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
exit_code = do_call(args, p)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
return getattr(module, func_name)(args, parser)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/cli/main_install.py", line 20, in execute
install(args, parser, 'install')
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 306, in install
raise e
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 293, in install
unlink_link_transaction = solver.solve_for_transaction(
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 114, in solve_for_transaction
unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 157, in solve_for_diff
final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 281, in solve_final_state
ssc = self._run_sat(ssc)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
return f(*args, **kwds)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 815, in _run_sat
ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs),
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
return f(*args, **kwds)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/resolve.py", line 1322, in solve
self.find_conflicts(specs, specs_to_add, history_specs)
File "/Users/gspinozzi/miniconda3/lib/python3.8/site-packages/conda/resolve.py", line 352, in find_conflicts
raise UnsatisfiableError(bad_deps, strict=strict_channel_priority)
conda.exceptions.UnsatisfiableError
```

</details>

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : None
            shell level : 0
       user config file : /Users/gspinozzi/.condarc
 populated config files : /Users/gspinozzi/.condarc
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __osx=12.2.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/gspinozzi/miniconda3  (writable)
      conda av data dir : /Users/gspinozzi/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/gspinozzi/miniconda3/pkgs
                          /Users/gspinozzi/.conda/pkgs
       envs directories : /Users/gspinozzi/miniconda3/envs
                          /Users/gspinozzi/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.8.11 Darwin/21.3.0 OSX/12.2.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

### Conda config

```shell
auto_activate_base: False
unsatisfiable_hints: False
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/gspinozzi/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h1a28f6b_1002    defaults
ca-certificates           2022.2.1             hca03da5_0    defaults
certifi                   2021.10.8        py38hca03da5_2    defaults
cffi                      1.15.0           py38h22df2f2_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     4.11.0           py38hca03da5_0    defaults
conda-package-handling    1.7.3            py38h1a28f6b_1    defaults
cryptography              36.0.0           py38h834c97f_0    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
libcxx                    12.0.0               hf6beb65_1    defaults
libffi                    3.4.2                hc377ac9_2    defaults
ncurses                   6.3                  h1a28f6b_2    defaults
openssl                   1.1.1m               h1a28f6b_0    defaults
pip                       21.2.4           py38hca03da5_0    defaults
pycosat                   0.6.3            py38h1a28f6b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py38hca03da5_0    defaults
python                    3.8.11               hbdb9e5c_5    defaults
python.app                3                py38h1a28f6b_0    defaults
readline                  8.1.2                h1a28f6b_1    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py38h1a28f6b_0    defaults
setuptools                58.0.4           py38hca03da5_1    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.37.2               h1058600_0    defaults
tk                        8.6.11               hb8d0fd4_0    defaults
tqdm                      4.62.3             pyhd3eb1b0_1    defaults
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h1a28f6b_0    defaults
yaml                      0.2.5                h1a28f6b_0    defaults
zlib                      1.2.11               h5a0b063_4    defaults
```

</details>

**Comment by kenodegard** [comment]
A few things to keep in mind here:
1. The conda community is still actively building out `osx-arm64` infrastructure and packages. The Anaconda Packaging team is actively doing so for the defaults channels and `conda-forge` has made impressive headway in this area. Unfortunately `bioconda` has not started this work and has not announced any plans to support `osx-arm64` at this time.
2. You can still use the `osx-64` conda installer on your M1. It will automatically use [Apple's Rosetta](https://support.apple.com/en-us/HT211861) instruction translator.

Further discussions on package availability should occur in their respective channels:
- for defaults/Anaconda provided packages please open tickets in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues)
- for `conda-forge` provided packages please open tickets on the [applicable feedstock](https://github.com/conda-forge/)
- for `bioconda` provided packages please open tickets in their [recipe repo](https://github.com/bioconda/bioconda-recipes)
