### ISSUE TITLE
conda broken after `conda update -n base conda` is interrupted

### ISSUE THREAD

**Issue by shwnyao** [conda/conda#11291]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I first ran the cmd `conda update -n base conda`, and there was an error related to missing `ruamel_yaml` module, which seemed to cause the update to be interrupted. I fixed it by running `pip install ruamel.yaml`. 

Afterwards, I could still switch between conda environments, but whenever I run `conda install` or `conda update`, this error shows up and has not been seen in other issues.

```
Traceback (most recent call last):
      File "/home/micrl/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/micrl/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/micrl/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/micrl/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/home/micrl/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "/home/micrl/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 713, in use_only_tar_bz2
        import conda_package_handling.api
    ImportError: No module named conda_package_handling.api
```

Is there a way I could fix it without affecting the other conda environments?

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
active environment : mmaction2
    active env location : /home/micrl/anaconda2/envs/mmaction2
            shell level : 2
       user config file : /home/micrl/.condarc
 populated config files : /home/micrl/.condarc
          conda version : 4.8.4
    conda-build version : 3.15.1
         python version : 2.7.18.final.0
       virtual packages : __cuda=11.4
                          __glibc=2.27
       base environment : /home/micrl/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/micrl/anaconda2/pkgs
                          /home/micrl/.conda/pkgs
       envs directories : /home/micrl/anaconda2/envs
                          /home/micrl/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.27.1 CPython/2.7.18 Linux/5.4.0-81-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

### Conda config

```shell
==> /home/micrl/.condarc <==
channels:
  - conda-forge
  - defaults
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/micrl/anaconda2/envs/mmaction2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
_pytorch_select           0.1                       cpu_0    defaults
addict                    2.4.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
attrs                     21.4.0                   pypi_0    pypi
audioread                 2.1.9                    pypi_0    pypi
av                        8.1.0                    pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl    defaults
bleach                    4.1.0                    pypi_0    pypi
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.15.0                   pypi_0    pypi
charset-normalizer        2.0.11                   pypi_0    pypi
click                     8.0.3                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  6.3.1                    pypi_0    pypi
cudatoolkit               10.1.243            h036e899_10    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1                    pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
decord                    0.6.0                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
einops                    0.4.0                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
flake8                    4.0.1                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
fonttools                 4.29.1                   pypi_0    pypi
freetype                  2.10.4               h0708190_1    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
idna                      3.3                      pypi_0    pypi
imageio                   2.14.1                   pypi_0    pypi
imageio-ffmpeg            0.4.5                    pypi_0    pypi
imgaug                    0.4.0                    pypi_0    pypi
importlib-metadata        4.2.0                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561    defaults
interrogate               1.5.0                    pypi_0    pypi
ipykernel                 6.8.0                    pypi_0    pypi
ipython                   7.31.1                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.5                    pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h7f98852_0    conda-forge
jsonschema                4.4.0                    pypi_0    pypi
jupyter-client            7.1.2                    pypi_0    pypi
jupyter-core              4.9.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.2                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libdeflate                1.8                  h7f98852_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libimagequant             2.17.0               h7f98852_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
librosa                   0.8.1                    pypi_0    pypi
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libtiff                   4.3.0                h6f004c6_2    conda-forge
libuv                     1.43.0               h7f98852_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
llvmlite                  0.38.0                   pypi_0    pypi
lmdb                      1.3.0                    pypi_0    pypi
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
markupsafe                2.0.1                    pypi_0    pypi
matplotlib                3.5.1                    pypi_0    pypi
matplotlib-inline         0.1.3                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py37h402132d_0    conda-forge
mkl_fft                   1.3.1            py37h3e078e5_1    conda-forge
mkl_random                1.2.2            py37h219a48f_0    conda-forge
mmaction2                 0.21.0                    dev_0    <develop>
mmcv                      1.4.6                    pypi_0    pypi
mmcv-full                 1.4.2                    pypi_0    pypi
moviepy                   1.0.3                    pypi_0    pypi
nbclient                  0.5.10                   pypi_0    pypi
nbconvert                 6.4.1                    pypi_0    pypi
nbformat                  5.1.3                    pypi_0    pypi
ncurses                   6.3                  h9c3ff4c_0    conda-forge
nest-asyncio              1.5.4                    pypi_0    pypi
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2               h4bd325d_1    conda-forge
notebook                  6.4.8                    pypi_0    pypi
numba                     0.55.1                   pypi_0    pypi
numpy                     1.21.2           py37h20f2e39_0    defaults
numpy-base                1.21.2           py37h79a1101_0    defaults
onnx                      1.10.2                   pypi_0    pypi
onnxruntime               1.10.0                   pypi_0    pypi
opencv-contrib-python     4.5.5.62                 pypi_0    pypi
opencv-python             4.5.5.62                 pypi_0    pypi
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   3.0.0                h7f98852_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.0.1            py37hc8ad62e_0    conda-forge
pims                      0.5                      pypi_0    pypi
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0                    pypi_0    pypi
pooch                     1.6.0                    pypi_0    pypi
proglog                   0.1.9                    pypi_0    pypi
prometheus-client         0.13.1                   pypi_0    pypi
prompt-toolkit            3.0.26                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pycodestyle               2.8.0                    pypi_0    pypi
pycparser                 2.21                     pypi_0    pypi
pyflakes                  2.4.0                    pypi_0    pypi
pygments                  2.11.2                   pypi_0    pypi
pyparsing                 3.0.7                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pytest                    7.0.0                    pypi_0    pypi
pytest-runner             5.3.1                    pypi_0    pypi
python                    3.7.12          hf930737_100_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.7.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pyturbojpeg               1.6.5                    pypi_0    pypi
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0                   pypi_0    pypi
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
resampy                   0.2.2                    pypi_0    pypi
ruamel-yaml               0.17.21                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
scikit-image              0.19.1                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.3                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                60.7.1           py37h89c1867_0    conda-forge
shapely                   1.8.0                    pypi_0    pypi
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicerator                1.0.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tabulate                  0.8.9                    pypi_0    pypi
terminado                 0.13.1                   pypi_0    pypi
testpath                  0.5.0                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
timm                      0.5.4                    pypi_0    pypi
tk                        8.6.11               h27826a3_1    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.0                    pypi_0    pypi
torch                     1.7.1                    pypi_0    pypi
torch-tensorrt            1.0.0                    pypi_0    pypi
torchaudio                0.7.2                      py37    pytorch
torchvision               0.8.2           cpu_py37ha229d99_0    defaults
tornado                   6.1                      pypi_0    pypi
tqdm                      4.62.3                   pypi_0    pypi
traitlets                 5.1.1                    pypi_0    pypi
typing_extensions         4.0.1              pyha770c72_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.5.2                    pypi_0    pypi
xdoctest                  0.15.10                  pypi_0    pypi
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yapf                      0.32.0                   pypi_0    pypi
zipp                      3.7.0                    pypi_0    pypi
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

</details>

**Comment by kenodegard** [comment]
@shwnyao can you please rerun `conda info` and `conda list --show-channel-urls` from your `base` environment (not from your `mmaction2` environment) and post the results?

**Comment by shwnyao** [comment]
`conda info`
```
active environment : base
    active env location : /home/micrl/anaconda2
            shell level : 1
       user config file : /home/micrl/.condarc
 populated config files : /home/micrl/.condarc
          conda version : 4.8.4
    conda-build version : 3.15.1
         python version : 2.7.18.final.0
       virtual packages : __cuda=11.4
                          __glibc=2.27
       base environment : /home/micrl/anaconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/micrl/anaconda2/pkgs
                          /home/micrl/.conda/pkgs
       envs directories : /home/micrl/anaconda2/envs
                          /home/micrl/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.27.1 CPython/2.7.18 Linux/5.4.0-81-generic ubuntu/18.04.5 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

`conda list --show-channel-urls`
```
# packages in environment at /home/micrl/anaconda2:
#
# Name                    Version                   Build  Channel
_anaconda_depends         5.3.1                    py27_1    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py27_0    defaults
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
alabaster                 0.7.11                   py27_0    defaults
anaconda                  custom                   py27_1    defaults
anaconda-client           1.7.2                    py27_0    defaults
anaconda-navigator        1.9.2                    py27_0    defaults
anaconda-project          0.8.2                    py27_0    defaults
appdirs                   1.4.3            py27h28b3542_0    defaults
asn1crypto                1.3.0                    py38_0    defaults
astroid                   1.6.5                    py27_0    defaults
astropy                   2.0.8            py27h035aef0_0    defaults
atomicwrites              1.2.1                    py27_0    defaults
attrs                     18.2.0           py27h28b3542_0    defaults
automat                   0.7.0                    py27_0    defaults
babel                     2.6.0                    py27_0    defaults
backports                 1.0                      py27_1    defaults
backports.functools_lru_cache 1.5                      py27_1    defaults
backports.shutil_get_terminal_size 1.0.0                    py27_2    defaults
backports_abc             0.5                      py27_0    defaults
beautifulsoup4            4.6.3                    py27_0    defaults
bitarray                  0.8.3            py27h14c3975_0    defaults
bkcharts                  0.2                      py27_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3                   py27_0    defaults
bleach                    2.1.4                    py27_0    defaults
blosc                     1.21.0               h8c45485_0    defaults
bokeh                     0.13.0                   py27_0    defaults
boto                      2.49.0                   py27_0    defaults
bottleneck                1.2.1            py27h035aef0_1    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.18.1               h7f8727e_0    defaults
ca-certificates           2022.2.1             h06a4308_0    defaults
cairo                     1.16.0               hf32fb01_1    defaults
cdecimal                  2.3              py27h14c3975_3    defaults
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
cffi                      1.14.0           py38h2e261b9_0    defaults
chardet                   4.0.0                    pypi_0    pypi
click                     6.7                      py27_0    defaults
cloudpickle               0.5.5                    py27_0    defaults
clyent                    1.2.2                    py27_1    defaults
colorama                  0.3.9                    py27_0    defaults
conda                     4.8.4                    py27_0    defaults
conda-build               3.15.1                   py27_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py38h7b6447c_0    defaults
configparser              3.5.0                    py27_0    defaults
constantly                15.1.0           py27h28b3542_0    defaults
contextlib2               0.5.5                    py27_0    defaults
cryptography              2.8              py38h1ba5d50_0    defaults
curl                      7.61.0               h84994c4_0    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.28.5           py27hf484d3e_0    defaults
cytoolz                   0.9.0.1          py27h14c3975_1    defaults
dask                      0.19.1                   py27_0    defaults
dask-core                 0.19.1                   py27_0    defaults
datashape                 0.5.4                    py27_1    defaults
dbus                      1.13.18              hb2f20db_0    defaults
decorator                 4.3.0                    py27_0    defaults
defusedxml                0.5.0                    py27_1    defaults
distributed               1.23.1                   py27_0    defaults
docutils                  0.14                     py27_0    defaults
entrypoints               0.2.3                    py27_2    defaults
enum34                    1.1.6                    py27_1    defaults
et_xmlfile                1.0.1                    py27_0    defaults
expat                     2.4.4                h295c915_0    defaults
fastcache                 1.0.2            py27h14c3975_2    defaults
filelock                  3.0.8                    py27_0    defaults
flask                     1.0.2                    py27_1    defaults
flask-cors                3.0.6                    py27_0    defaults
fontconfig                2.13.1               h6c09931_0    defaults
freetype                  2.11.0               h70c0345_0    defaults
fribidi                   1.0.10               h7b6447c_0    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_1    defaults
futures                   3.2.0                    py27_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.3.6            py27h7b6447c_0    defaults
glib                      2.69.1               h4ff587b_1    defaults
glob2                     0.6                      py27_0    defaults
gmp                       6.2.1                h2531618_2    defaults
gmpy2                     2.0.8            py27h10f8cd9_2    defaults
graphite2                 1.3.14               h23475e2_0    defaults
greenlet                  0.4.15           py27h7b6447c_0    defaults
grin                      1.2.1                    py27_4    defaults
gst-plugins-base          1.14.0               h8213a91_2    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
h5py                      2.8.0            py27h989c5e5_3    defaults
harfbuzz                  2.8.1                h6f93f22_0    defaults
hdf5                      1.10.2               hba1933b_1    defaults
heapdict                  1.0.0                    py27_2    defaults
html5lib                  1.0.1                    py27_0    defaults
hyperlink                 18.0.0                   py27_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      2.9                        py_1    defaults
imageio                   2.4.1                    py27_0    defaults
imagesize                 1.1.0                    py27_0    defaults
incremental               17.5.0                   py27_0    defaults
intel-openmp              2022.0.1          h06a4308_3633    defaults
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.9.0                    py27_1    defaults
ipython                   5.8.0                    py27_0    defaults
ipython_genutils          0.2.0                    py27_0    defaults
ipywidgets                7.4.1                    py27_0    defaults
isort                     4.3.4                    py27_0    defaults
itsdangerous              0.24                     py27_1    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4                      py27_0    defaults
jedi                      0.12.1                   py27_0    defaults
jinja2                    2.10                     py27_0    defaults
jpeg                      9d                   h7f8727e_0    defaults
jsonschema                2.6.0                    py27_0    defaults
jupyter                   1.0.0                    py27_7    defaults
jupyter_client            5.2.3                    py27_0    defaults
jupyter_console           5.2.0                    py27_1    defaults
jupyter_core              4.4.0                    py27_0    defaults
jupyterlab                0.33.11                  py27_0    defaults
jupyterlab_launcher       0.11.2           py27h28b3542_0    defaults
kiwisolver                1.0.1            py27hf484d3e_0    defaults
krb5                      1.19.2               hac12032_0    defaults
lazy-object-proxy         1.3.1            py27h14c3975_2    defaults
ld_impl_linux-64          2.33.1               h53a641e_7    defaults
libcurl                   7.61.0               h1ad7b7a_0    defaults
libedit                   3.1.20210910         h7f8727e_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgfortran-ng            7.5.0               ha8ba4b0_17    defaults
libgfortran4              7.5.0               ha8ba4b0_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libnghttp2                1.46.0               hce63b2e_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libtool                   2.4.6             h295c915_1008    defaults
libuuid                   1.0.3                h7f8727e_2    defaults
libwebp-base              1.2.2                h7f8727e_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.12               h03d6c58_0    defaults
libxslt                   1.1.34               hc22bd24_0    defaults
linecache2                1.0.0                    py27_0    defaults
llvmlite                  0.24.0           py27hdbcaa40_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      4.2.5            py27hefd8a0e_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
lzo                       2.10                 h7b6447c_2    defaults
markupsafe                1.0              py27h14c3975_1    defaults
matplotlib                2.2.3            py27hb69df0a_0    defaults
mccabe                    0.6.1                    py27_1    defaults
mistune                   0.8.3            py27h14c3975_1    defaults
mkl                       2018.0.3                      1    defaults
mkl-service               1.1.2            py27h90e4bf4_5    defaults
mkl_fft                   1.0.4            py27h4414c95_1    defaults
mkl_random                1.0.1            py27h4414c95_1    defaults
more-itertools            4.3.0                    py27_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpmath                    1.0.0                    py27_2    defaults
msgpack-python            0.5.6            py27h6bb024c_1    defaults
multipledispatch          0.6.0                    py27_0    defaults
navigator-updater         0.2.1                    py27_0    defaults
nbconvert                 5.4.0                    py27_1    defaults
nbformat                  4.4.0                    py27_0    defaults
ncurses                   6.3                  h7f8727e_2    defaults
networkx                  2.1                      py27_0    defaults
nltk                      3.3.0                    py27_0    defaults
nose                      1.3.7                    py27_2    defaults
notebook                  5.6.0                    py27_0    defaults
numba                     0.39.0           py27h04863e7_0    defaults
numexpr                   2.6.8            py27hd89afb7_0    defaults
numpy                     1.15.1           py27h1d66e8a_0    defaults
numpy-base                1.15.1           py27h81de0dd_0    defaults
numpydoc                  0.8.0                    py27_0    defaults
odo                       0.5.1                    py27_0    defaults
olefile                   0.46                     py27_0    defaults
openpyxl                  2.5.6                    py27_0    defaults
openssl                   1.1.1m               h7f8727e_0    defaults
packaging                 17.1                     py27_0    defaults
pandas                    0.23.4           py27h04863e7_0    defaults
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2                    py27_1    defaults
pango                     1.45.3               hd140c19_0    defaults
parso                     0.3.1                    py27_0    defaults
partd                     0.3.8                    py27_0    defaults
patchelf                  0.13                 h295c915_0    defaults
path.py                   11.1.0                   py27_0    defaults
pathlib2                  2.3.2                    py27_0    defaults
patsy                     0.5.0                    py27_0    defaults
pcre                      8.45                 h295c915_0    defaults
pep8                      1.7.1                    py27_0    defaults
pexpect                   4.6.0                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    5.2.0            py27heded4f4_0    defaults
pip                       19.2.3                   pypi_0    pypi
pixman                    0.40.0               h7f8727e_1    defaults
pkginfo                   1.4.2                    py27_1    defaults
pluggy                    0.7.1            py27h28b3542_0    defaults
ply                       3.11                     py27_0    defaults
prometheus_client         0.3.1            py27h28b3542_0    defaults
prompt_toolkit            1.0.15                   py27_0    defaults
psutil                    5.4.7            py27h14c3975_0    defaults
ptyprocess                0.6.0                    py27_0    defaults
py                        1.6.0                    py27_0    defaults
pyasn1                    0.4.4            py27h28b3542_0    defaults
pyasn1-modules            0.2.2                    py27_0    defaults
pycairo                   1.17.1           py27h2a1e443_0    defaults
pycodestyle               2.4.0                    py27_0    defaults
pycosat                   0.6.3            py38h7b6447c_0    defaults
pycparser                 2.20                       py_0    defaults
pycrypto                  2.6.1            py27h14c3975_9    defaults
pycurl                    7.43.0.2         py27hb7f436b_0    defaults
pyflakes                  2.0.0                    py27_0    defaults
pygments                  2.2.0                    py27_0    defaults
pylint                    1.9.2                    py27_0    defaults
pyodbc                    4.0.24           py27he6710b0_0    defaults
pyopenssl                 19.1.0                   py38_0    defaults
pyparsing                 2.2.0                    py27_1    defaults
pyqt                      5.9.2            py27h05f1152_2    defaults
pysocks                   1.7.1                    py38_0    defaults
pytables                  3.4.4            py27ha205bf6_0    defaults
pytest                    3.8.0                    py27_0    defaults
python                    2.7.18               ha1903f6_2    defaults
python-dateutil           2.7.3                    py27_0    defaults
pytz                      2018.5                   py27_0    defaults
pywavelets                1.0.0            py27hdd07704_0    defaults
pyyaml                    3.13             py27h14c3975_0    defaults
pyzmq                     17.1.2           py27h14c3975_0    defaults
qt                        5.9.6                h8703b6f_2    defaults
qtawesome                 0.4.4                    py27_0    defaults
qtconsole                 4.4.1                    py27_0    defaults
qtpy                      1.5.0                    py27_0    defaults
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.27.1                   pypi_0    pypi
rope                      0.11.0                   py27_0    defaults
ruamel-ordereddict        0.4.15                   pypi_0    pypi
ruamel-yaml               0.16.13                  pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
ruamel_yaml               0.15.87          py38h7b6447c_0    defaults
scandir                   1.9.0            py27h14c3975_0    defaults
scikit-image              0.14.0           py27hf484d3e_1    defaults
scikit-learn              0.19.2           py27h4989274_0    defaults
scipy                     1.1.0            py27hfa4b5c9_1    defaults
seaborn                   0.9.0                    py27_0    defaults
send2trash                1.5.0                    py27_0    defaults
service_identity          17.0.0           py27h28b3542_0    defaults
setuptools                41.2.0                   pypi_0    pypi
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.19.8           py27hf484d3e_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snappy                    1.1.8                he6710b0_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sortedcollections         1.0.1                    py27_0    defaults
sortedcontainers          2.0.5                    py27_0    defaults
sphinx                    1.7.9                    py27_0    defaults
sphinxcontrib             1.0                      py27_1    defaults
sphinxcontrib-websupport  1.1.0                    py27_1    defaults
spyder                    3.3.1                    py27_1    defaults
spyder-kernels            0.2.6                    py27_0    defaults
sqlalchemy                1.2.11           py27h7b6447c_0    defaults
sqlite                    3.37.2               hc218d9a_0    defaults
ssl_match_hostname        3.5.0.1                  py27_2    defaults
statsmodels               0.9.0            py27h035aef0_0    defaults
subprocess32              3.5.2            py27h14c3975_0    defaults
sympy                     1.2                      py27_0    defaults
tbb                       2021.5.0             hd09550d_0    defaults
tbb4py                    2019.8           py27hfd86e86_0    defaults
tblib                     1.3.2                    py27_0    defaults
terminado                 0.8.1                    py27_1    defaults
testpath                  0.3.1                    py27_0    defaults
tk                        8.6.11               h1ccaba5_0    defaults
toolz                     0.9.0                    py27_0    defaults
tornado                   5.1              py27h14c3975_0    defaults
tqdm                      4.44.1                     py_0    defaults
traceback2                1.4.0                    py27_0    defaults
traitlets                 4.3.2                    py27_0    defaults
twisted                   18.7.0           py27h14c3975_1    defaults
typing                    3.6.6                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
unittest2                 1.1.0                    py27_0    defaults
unixodbc                  2.3.9                h7b6447c_0    defaults
urllib3                   1.26.8                   pypi_0    pypi
wcwidth                   0.1.7                    py27_0    defaults
webencodings              0.5.1                    py27_1    defaults
werkzeug                  0.14.1                   py27_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
widgetsnbextension        3.4.1                    py27_0    defaults
wrapt                     1.10.11          py27h14c3975_2    defaults
xlrd                      1.1.0                    py27_1    defaults
xlsxwriter                1.1.0                    py27_0    defaults
xlwt                      1.3.0                    py27_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.5                hf484d3e_1    defaults
zict                      0.1.3                    py27_0    defaults
zlib                      1.2.11               h7f8727e_4    defaults
zope                      1.0                      py27_1    defaults
zope.interface            4.5.0            py27h14c3975_0    defaults
zstd                      1.4.9                haebb681_0    defaults
```
