### ISSUE TITLE
problem while executing conda install jupyter 

### ISSUE THREAD

**Issue by yyzsl** [conda/conda#11292]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

when I tried to install jupyter, an error occurred. the command I inputted is  `conda install jupyter -v`. the following is the log.

<details>
<summary><code>log</code></summary>

```log
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\bb\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\bb\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\bb\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\bb\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: format requires a mapping
Call stack:
  File "C:\Users\bb\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\plan.py", line 828, in execute_actions
    execute_instructions(plan, index, verbose)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
    txn.execute()
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 281, in execute
    pkg_data, actions)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 326, in _execute_actions
    action.execute()
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 388, in execute
    compile_pyc(python_full_path, self.source_full_path, self.target_full_path)
  File "C:\Users\bb\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 285, in compile_pyc
    log.info(message, python_exe_full_path, py_full_path, pyc_full_path)
Message: 'pyc file failed to compile successfully\n  python_exe_full_path: %()s\n\n  py_full_path: %()s\n\n  pyc_full_path: %()s\n\n'
Arguments: ('C:\\Users\\bb\\Anaconda3\\envs\\tensorflow\\python.exe', 'C:\\Users\\bb\\Anaconda3\\envs\\tensorflow\\Lib\\site-packages\\jinja2\\asyncsupport.py', 'C:\\Users\\bb\\Anaconda3\\envs\\tensorflow\\Lib\\site-packages\\jinja2\\__pycache__\\asyncsupport.cpython-35.pyc')
===> LINKING PACKAGE: defaults::jsonschema-2.6.0-py35h27d56d3_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\jsonschema-2.6.0-py35h27d56d3_0


===> LINKING PACKAGE: defaults::jupyter_core-4.5.0-py_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\jupyter_core-4.5.0-py_0


===> LINKING PACKAGE: defaults::pyqt-5.9.2-py35h6538335_2 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\pyqt-5.9.2-py35h6538335_2


===> LINKING PACKAGE: defaults::pywinpty-0.5.4-py35_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\pywinpty-0.5.4-py35_0


===> LINKING PACKAGE: defaults::jupyter_client-5.3.3-py_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\jupyter_client-5.3.3-py_0


===> LINKING PACKAGE: defaults::nbformat-5.1.3-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\nbformat-5.1.3-pyhd3eb1b0_0


===> LINKING PACKAGE: defaults::terminado-0.8.1-py35_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\terminado-0.8.1-py35_1


===> LINKING PACKAGE: defaults::ipykernel-4.10.0-py35_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow
  source=C:\Users\bb\Anaconda3\pkgs\ipykernel-4.10.0-py35_0


$ C:\Windows\system32\cmd.exe /d /c C:\Users\bb\Anaconda3\envs\tensorflow\Scripts\.ipykernel-post-link.bat
==> cwd: C:\Users\bb\Anaconda3\envs\tensorflow\Scripts <==
==> exit code: 1 <==
==> stdout <==
b''
==> stderr <==
b''


An error occurred while installing package 'defaults::ipykernel-4.10.0-py35_0'.
LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
running your command again with `-v` will provide additional information
location of failed script: C:\Users\bb\Anaconda3\envs\tensorflow\Scripts\.ipykernel-post-link.bat
==> script messages <==
<None>

Attempting to roll back.


===> REVERSING PACKAGE LINK: defaults::ipykernel-4.10.0-py35_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::terminado-0.8.1-py35_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::nbformat-5.1.3-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::jupyter_client-5.3.3-py_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pywinpty-0.5.4-py35_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pyqt-5.9.2-py35h6538335_2 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::jupyter_core-4.5.0-py_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::jsonschema-2.6.0-py35h27d56d3_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::jinja2-2.11.3-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::ipython-6.5.0-py35_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::bleach-3.3.1-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::traitlets-4.3.2-py35h09b975b_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::qt-5.9.7-vc14h73c81de_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pyzmq-17.1.2-py35hfa6e2cd_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::python-dateutil-2.8.2-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::prompt_toolkit-1.0.15-py35h89c7cb4_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::packaging-20.9-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::m2w64-gcc-libs-5.3.0-7 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::jedi-0.12.1-py35_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::zeromq-4.2.5-he025d50_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::win_unicode_console-0.5-py35h56988b5_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::webencodings-0.5.1-py35_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::wcwidth-0.2.5-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::tornado-5.1.1-py35hfa6e2cd_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::testpath-0.4.4-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::six-1.16.0-pyhd3eb1b0_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::sip-4.19.8-py35h6538335_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::simplegeneric-0.8.1-py35_2 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::send2trash-1.8.0-pyhd3eb1b0_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::qtpy-1.11.2-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pyparsing-2.4.7-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pygments-2.11.2-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::prometheus_client-0.11.0-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pickleshare-0.7.5-pyhd3eb1b0_1003 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::parso-0.8.0-py_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pandocfilters-1.5.0-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::mistune-2.0.2-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::markupsafe-1.0-py35hfa6e2cd_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::m2w64-gcc-libgfortran-5.3.0-6 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::libpng-1.6.37-h2a8f88b_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::ipython_genutils-0.2.0-pyhd3eb1b0_1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::entrypoints-0.2.3-py35_2 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::defusedxml-0.7.1-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::decorator-5.1.1-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::colorama-0.4.4-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::backcall-0.2.0-pyhd3eb1b0_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::zlib-1.2.11-h8cc25b3_4 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::sqlite-3.37.2-h2bbff1b_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::openssl-1.1.1m-h2bbff1b_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::m2w64-gcc-libs-core-5.3.0-7 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::libsodium-1.0.16-h9d3ae62_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::jpeg-9d-h2bbff1b_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::icu-58.2-ha925a31_3 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::m2w64-libwinpthread-git-5.0.0.4634.697f757-2 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::m2w64-gmp-6.1.0-2 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::winpty-0.4.3-4 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::pandoc-2.12-haa95532_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::msys2-conda-epoch-20160418-1 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


===> REVERSING PACKAGE LINK: defaults::ca-certificates-2022.2.1-haa95532_0 <===
  prefix=C:\Users\bb\Anaconda3\envs\tensorflow


An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\bb\Anaconda3  (writable)
    default environment : C:\Users\bb\Anaconda3\envs\tensorflow
       envs directories : C:\Users\bb\Anaconda3\envs
                          C:\Users\bb\AppData\Local\conda\conda\envs
                          C:\Users\bb\.conda\envs
          package cache : C:\Users\bb\Anaconda3\pkgs
                          C:\Users\bb\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\bb\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.19041
          administrator : False

`$ C:\Users\bb\Anaconda3\Scripts\conda install jupyter -v`




    Traceback (most recent call last):
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 497, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\cmd.exe', '/d', '/c', 'C:\\Users\\bb\\Anaconda3\\envs\\tensorflow\\Scripts\\.ipykernel-post-link.bat']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 513, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Users\bb\Anaconda3\envs\tensorflow\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 281, in execute
        pkg_data, actions)
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Users\bb\Anaconda3\envs\tensorflow\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>



    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Users\bb\Anaconda3\lib\site-packages\conda\core\link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package defaults::ipykernel-4.10.0-py35_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Users\bb\Anaconda3\envs\tensorflow\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>
```

</details>

### Conda info

<details>
<summary><code>conda info</code></summary>

```shell
platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\bb\Anaconda3  (writable)
    default environment : C:\Users\bb\Anaconda3\envs\tensorflow
       envs directories : C:\Users\bb\Anaconda3\envs
                          C:\Users\bb\AppData\Local\conda\conda\envs
                          C:\Users\bb\.conda\envs
          package cache : C:\Users\bb\Anaconda3\pkgs
                          C:\Users\bb\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\bb\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.19041
          administrator : False
```

</details>

### Conda config

```shell
==> C:\Users\bb\.condarc <==
ssl_verify: True
channels:
  - defaults
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at C:\Users\bb\Anaconda3\envs\tensorflow:
#
absl-py                   0.15.0                    <pip>
bleach                    1.5.0                     <pip>
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
html5lib                  0.9999999                 <pip>
importlib-metadata        2.1.3                     <pip>
Markdown                  3.2.2                     <pip>
numpy                     1.18.5                    <pip>
pip                       10.0.1                   py35_0    defaults
protobuf                  3.19.4                    <pip>
python                    3.5.6                he025d50_0    defaults
setuptools                40.2.0                   py35_0    defaults
tensorflow                1.5.0                     <pip>
tensorflow-tensorboard    1.5.1                     <pip>
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
Werkzeug                  1.0.1                     <pip>
wheel                     0.37.1             pyhd3eb1b0_0    defaults
wincertstore              0.2              py35hfebbdb8_0    defaults
zipp                      1.2.0                     <pip>
```

</details>

**Comment by kenodegard** [comment]
@yyzsl yes I can replicate this issue for `python=3.5.6`, however, this issue is not present in newer versions (e.g. Python 3.6):

```bash
conda create -n tensorflow python=3.6 tensorflow jupyter
```

Since this is ultimately a packaging issue and not an issue with `conda` itself please open this issue on the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) if you continue to have problems.

Thanks!
