### ISSUE TITLE
conda windows 7, cannot release the lock

### ISSUE THREAD

**Issue by denfromufa** [conda/conda#1130]
```
C:\Windows\system32>conda clean --lock
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Python\Python27\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python\Python27\lib\site-packages\conda\cli\main.py", line 202, in ma
in
    args_func(args, p)
  File "C:\Python\Python27\lib\site-packages\conda\cli\main.py", line 207, in ar
gs_func
    args.func(args, p)
  File "C:\Python\Python27\lib\site-packages\conda\cli\main_clean.py", line 309,
 in execute
    locks = list(find_lock())
  File "C:\Python\Python27\lib\site-packages\conda\cli\main_clean.py", line 77,
in find_lock
    for fn in os.listdir(envs_dir):
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Python\\
Python27\\envs/*.*'

C:\Windows\system32>conda info
Current conda install:

             platform : win-32
        conda version : 3.8.4
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : C:\Python\Python27  (writable)
  default environment : C:\Python\Python27
     envs directories : C:\Python\Python27\envs
        package cache : C:\Python\Python27\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-32/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/win-32/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : True


C:\Windows\system32>
```

**Comment by asmeurer** [comment]
Does the `C:\Python\Python27\envs` directory exist?

**Comment by denfromufa** [comment]
no

**Comment by asmeurer** [comment]
To workaround your issue, you can create that directory (or alternately, delete the lock file that is bugging you manually).

**Comment by denfromufa** [comment]
creating the directory manually fixed the problem.
