### ISSUE TITLE
Answering "no" to confirmation prompt results in uncaught exception

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#11303]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I looked at the [README.md](https://github.com/conda-incubator/conda-libmamba-solver) and didn't see anything to help

### What happened?

I was experimenting with the prelease and wondered what happened if I answered 'no'  to the prompt and well, curiosity satisfied: unhandled exception 😬 

```
conda install -n dask --experimental-solver=libmamba scipy

----       USING EXPERIMENTAL LIBMAMBA INTEGRATIONS       ----
    This is a highly experimental product. If something is
    not working as expected, please submit an issue at
    https://github.com/conda/conda and attach the log file
    found in the following path. Thank you!

    /Users/jrodriguez-guerra/.local/conda/pkgs/.logs/20220308-120015-228146.log

---------------------------------------------------------------

There are risks using this experimental solver since it
does not always produce identical results as that of the
classical solver. As with any experimental product it
is *not* recommended to use it in production or critical
environments.

Do you wish to proceed ([y]/n)? n


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/cli/install.py", line 251, in install
        solver = SolverType(prefix, context.channels, context.subdirs, specs_to_add=specs,
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 188, in __init__
        self._print_info()
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 347, in _print_info
        confirm_yn(f"{msg}\n{risk}")
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/cli/common.py", line 65, in confirm_yn
        raise CondaSystemExit("Exiting.")
    conda.exceptions.CondaSystemExit: Exiting.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/jrodriguez-guerra/.local/conda/lib/python3.9/site-packages/conda/cli/install.py", line 294, in install
        unlink_link_transaction = solver.solve_for_transaction(
    UnboundLocalError: local variable 'solver' referenced before assignment

`$ /Users/jrodriguez-guerra/.local/conda/bin/conda install -n dask --experimental-solver=libmamba scipy`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/jrodriguez-guerra/.local/conda/bin/conda
             CONDA_PREFIX=/Users/jrodriguez-guerra/.local/conda
           CONDA_PREFIX_1=/Users/jrodriguez-guerra/.local/conda/envs/napari-15rc
           CONDA_PREFIX_2=/Users/jrodriguez-guerra/.local/conda/envs/dask
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/jrodriguez-guerra/.local/conda/bin/python
               CONDA_ROOT=/Users/jrodriguez-guerra/.local/conda
              CONDA_SHLVL=3
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/jrodriguez-guerra/.local/conda/bin:/Users/jrodriguez-
                          guerra/.local/conda/bin:/Users/jrodriguez-guerra/.local/conda/condabin
                          :/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/Ap
                          ple/usr/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/jrodriguez-guerra/.local/conda
            shell level : 3
       user config file : /Users/jrodriguez-guerra/.condarc
 populated config files : /Users/jrodriguez-guerra/.condarc
          conda version : 4.11.0.67_g24a6a13f5
    conda-build version : 3.21.4
         python version : 3.9.7.final.0
       virtual packages : __osx=11.6.4=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/jrodriguez-guerra/.local/conda  (writable)
      conda av data dir : /Users/jrodriguez-guerra/.local/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jrodriguez-guerra/.local/conda/pkgs
                          /Users/jrodriguez-guerra/.conda/pkgs
       envs directories : /Users/jrodriguez-guerra/.local/conda/envs
                          /Users/jrodriguez-guerra/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0.67_g24a6a13f5 requests/2.26.0 CPython/3.9.7 Darwin/20.6.0 OSX/11.6.4
                UID:GID : 503:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Conda info

```Shell
active environment : base
    active env location : /Users/jrodriguez-guerra/.local/conda
            shell level : 3
       user config file : /Users/jrodriguez-guerra/.condarc
 populated config files : /Users/jrodriguez-guerra/.condarc
          conda version : 4.11.0.67_g24a6a13f5
    conda-build version : 3.21.4
         python version : 3.9.7.final.0
       virtual packages : __osx=11.6.4=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/jrodriguez-guerra/.local/conda  (writable)
      conda av data dir : /Users/jrodriguez-guerra/.local/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jrodriguez-guerra/.local/conda/pkgs
                          /Users/jrodriguez-guerra/.conda/pkgs
       envs directories : /Users/jrodriguez-guerra/.local/conda/envs
                          /Users/jrodriguez-guerra/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0.67_g24a6a13f5 requests/2.26.0 CPython/3.9.7 Darwin/20.6.0 OSX/11.6.4
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

### Conda config

```Shell
==> /Users/jrodriguez-guerra/.condarc <==
channels:
  - conda-forge
```

### Conda list

```Shell
# packages in environment at /Users/jrodriguez-guerra/.local/conda:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
black                     21.8b0             pyhd8ed1ab_0    conda-forge
boolean.py                3.7                        py_0    conda-forge
brotlipy                  0.7.0           py39h89e85a6_1001    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.17.2               h0d85af4_0    conda-forge
ca-certificates           2021.10.8            h033912b_0    conda-forge
certifi                   2021.10.8        py39h6e9494a_1    conda-forge
cffi                      1.14.6           py39hb71fe58_0    conda-forge
chardet                   4.0.0            py39h6e9494a_1    conda-forge
charset-normalizer        2.0.0              pyhd8ed1ab_0    conda-forge
click                     8.0.1            py39h6e9494a_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.11.0.67_g24a6a13f5          py39_0    https://anaconda.org/conda-canary/conda/4.11.0.67_g24a6a13f5/download
conda-build               3.21.4           py39h6e9494a_0    conda-forge
conda-libmamba-solver     22.2.0.15_ga6d86f8            py_0    https://anaconda.org/conda-canary/conda-libmamba-solver/22.2.0.15_ga6d86f8/download
conda-package-handling    1.7.3            py39h89e85a6_0    conda-forge
conda-standalone          4.10.3               h694c41f_0    conda-forge
constructor               3.2.1+80.gaac6431.dirty           dev_0    <develop>
cryptography              3.4.7            py39ha2c9959_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
filelock                  3.3.1              pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
htop                      3.1.2                hbc4f8dc_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      3.1                pyhd3deb0d_0    conda-forge
jinja2                    3.0.2              pyhd8ed1ab_0    conda-forge
krb5                      1.19.2               hcfbf3a7_0    conda-forge
libarchive                3.5.2                h2b60450_0    conda-forge
libcurl                   7.81.0               hf45b732_0    conda-forge
libcxx                    12.0.1               habf9029_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblief                   0.11.5               he49afe7_0    conda-forge
libmamba                  0.21.2               h9ce2d19_0    conda-forge
libmambapy                0.21.2           py39h2c464dc_0    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libsolv                   0.7.19               hcf210ce_5    conda-forge
libssh2                   1.10.0               h52ee1ee_0    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
license-expression        1.2                        py_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
lzo                       2.10              haf1e3a3_1000    conda-forge
mamba                     0.21.2           py39ha435c47_0    conda-forge
markupsafe                2.0.1            py39h89e85a6_0    conda-forge
mypy_extensions           0.4.3            py39h6e9494a_3    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openssl                   1.1.1l               h0d85af4_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pkginfo                   1.7.1              pyhd8ed1ab_0    conda-forge
platformdirs              2.3.0              pyhd8ed1ab_0    conda-forge
psutil                    5.8.0            py39h89e85a6_1    conda-forge
py-lief                   0.11.5           py39h9fcab8e_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39h89e85a6_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39h6e9494a_3    conda-forge
python                    3.9.7           hd187cdc_0_cpython    conda-forge
python-libarchive-c       3.1              py39h6e9494a_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h89e85a6_0    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
regex                     2021.8.28        py39h89e85a6_0    conda-forge
reproc                    14.2.3               h0d85af4_0    conda-forge
reproc-cpp                14.2.3               he49afe7_0    conda-forge
requests                  2.26.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h80d2146_1    conda-forge
ruamel-yaml               0.17.16                  pypi_0    pypi
ruamel-yaml-clib          0.2.6                    pypi_0    pypi
ruamel_yaml               0.15.80         py39h89e85a6_1004    conda-forge
setuptools                58.0.4           py39h6e9494a_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.0.1                      py_1    conda-forge
sqlite                    3.36.0               h23a322b_1    conda-forge
tk                        8.6.11               h5dbffcc_1    conda-forge
tomli                     1.2.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.62.2             pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.3            py39h89e85a6_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzdata                    2021a                he74cb21_1    conda-forge
urllib3                   1.26.6             pyhd8ed1ab_0    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yaml-cpp                  0.6.3                hb1e8313_4    conda-forge
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.0                h582d3a0_0    conda-forge
```

### Log file & additional context

(File was empty)

**Comment by jezdez** [comment]
The `SystemExit` exception raised by `confirm_yn` as used in the libmamba solver code is already caught but the flow is not taking into account that the mere instantiation of the solver class could lead to a confirmation being requested.
