### ISSUE TITLE
Replace `toolz` dependency with `cytoolz`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#11333]
This makes me all kind of uncomfortable since cytoolz is a separate pacakge and us using it this way is totally backwards. We should rely on it instead directly or remove our footprint using it. Probably larger than this PR though, so worth opening a ticket to look into it.

_Originally posted by @jezdez in https://github.com/conda/conda/pull/11290#discussion_r826836808_

**Comment by travishathaway** [comment]
I looked through our code, and we definitely rely on this library:

```
grep 'toolz' -r conda --exclude='*.pyc'
conda/plan.py:from ._vendor.toolz import concatv
conda/plan.py:    from ._vendor.toolz.itertoolz import groupby
conda/resolve.py:from ._vendor.toolz import concat, groupby
conda/core/link.py:from .._vendor.toolz import concat, concatv, interleave
conda/core/package_cache_data.py:from .._vendor.toolz import concat, concatv, groupby
conda/core/path_actions.py:from .._vendor.toolz import concat
conda/core/index.py:from .._vendor.toolz import concat, concatv
conda/core/solve.py:from .._vendor.toolz import concat, concatv, groupby
conda/core/subdir_data.py:from .._vendor.toolz import concat, take, groupby
conda/shell/condabin/Conda.psm1:        conda install toolz
conda/models/version.py:from .._vendor.toolz import excepts
conda/models/channel.py:from .._vendor.toolz import concat, concatv, drop
conda/models/match_spec.py:from .._vendor.toolz import concat, concatv, groupby
conda/cli/main_config.py:from .._vendor.toolz import concat, groupby
conda/common/configuration.py:from .._vendor.toolz import concat, concatv, excepts, merge, merge_with, unique
conda/common/pkg_formats/python.py:from ..._vendor.toolz import concat, concatv, groupby
conda/common/path.py:from .._vendor.toolz import accumulate, concat
conda/exceptions.py:from ._vendor.toolz import groupby
conda/auxlib/__init__.py:python stdlib gaps much like `pytoolz <https://github.com/pytoolz/>`_ has for functional
conda/base/context.py:from .._vendor.toolz import concat, concatv, unique
conda/activate.py:from ._vendor.toolz import concatv, drop
conda/history.py:from ._vendor.toolz import groupby, take
```

@kenodegard, is  the goal now to add add `cytoolz` to our `setup.py` in our `install_requires` list, replace each import statement with the correct one and finally drop `toolz` from the vendor settings in our `setup.cfg` file?

**Comment by jezdez** [comment]
> I looked through our code, and we definitely rely on this library:
> 
> ```
> grep 'toolz' -r conda --exclude='*.pyc'
> conda/plan.py:from ._vendor.toolz import concatv
> conda/plan.py:    from ._vendor.toolz.itertoolz import groupby
> conda/resolve.py:from ._vendor.toolz import concat, groupby
> conda/core/link.py:from .._vendor.toolz import concat, concatv, interleave
> conda/core/package_cache_data.py:from .._vendor.toolz import concat, concatv, groupby
> conda/core/path_actions.py:from .._vendor.toolz import concat
> conda/core/index.py:from .._vendor.toolz import concat, concatv
> conda/core/solve.py:from .._vendor.toolz import concat, concatv, groupby
> conda/core/subdir_data.py:from .._vendor.toolz import concat, take, groupby
> conda/shell/condabin/Conda.psm1:        conda install toolz
> conda/models/version.py:from .._vendor.toolz import excepts
> conda/models/channel.py:from .._vendor.toolz import concat, concatv, drop
> conda/models/match_spec.py:from .._vendor.toolz import concat, concatv, groupby
> conda/cli/main_config.py:from .._vendor.toolz import concat, groupby
> conda/common/configuration.py:from .._vendor.toolz import concat, concatv, excepts, merge, merge_with, unique
> conda/common/pkg_formats/python.py:from ..._vendor.toolz import concat, concatv, groupby
> conda/common/path.py:from .._vendor.toolz import accumulate, concat
> conda/exceptions.py:from ._vendor.toolz import groupby
> conda/auxlib/__init__.py:python stdlib gaps much like `pytoolz <https://github.com/pytoolz/>`_ has for functional
> conda/base/context.py:from .._vendor.toolz import concat, concatv, unique
> conda/activate.py:from ._vendor.toolz import concatv, drop
> conda/history.py:from ._vendor.toolz import groupby, take
> ```
> 
> @kenodegard, is the goal now to add add `cytoolz` to our `setup.py` in our `install_requires` list, replace each import statement with the correct one and finally drop `toolz` from the vendor settings in our `setup.cfg` file?

Yeah, the goal is to depend on cytoolz in the first place (via the conda feedstock though, not setup.py that's not really used for real®) instead of the unholy patch to toolz, to try to import cytools: https://github.com/kenodegard/conda/blob/412357a686a8fe8fcaf5f4cefb9902c49bba1eda/tools/vendoring/patches/toolz.patch

**Comment by jezdez** [comment]
To clarify, the "conda feedstock" is the separately maintained repo where we maintain the "conda" package recipe:

- for "defaults" it's at https://github.com/AnacondaRecipes/conda-feedstock ([meta.yml](https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/meta.yaml))
- for "conda-forge" it's at https://github.com/conda-forge/conda-feedstock ([meta.yml](https://github.com/conda-forge/conda-feedstock/blob/main/recipe/meta.yaml))

They are for various reasons not the same and are even maintained by different people (which is a bug in my opinion) and with different maintenance techniques. That's what we mean when we basically say "we're doing a handover to the packaging team at the moment".

E.g. the PRs for 4.13.0:

- https://github.com/AnacondaRecipes/conda-feedstock/pull/6 which I created manually
- https://github.com/conda-forge/conda-feedstock/pull/165 which is automatically created by conda-forge's @regro-cf-autotick-bot bot (whose code lives in https://github.com/regro/cf-scripts)

**Comment by kenodegard** [comment]
cc @jaimergp this also impacts [conda-libmamba-solver](https://github.com/conda-incubator/conda-libmamba-solver/blob/656cc7c36ddf21ade20961cc562e4d3ee62de450/conda_libmamba_solver/_libmamba.py#L18)

**Comment by John-P** [comment]
Should cytoolz be included in setup.py? Installing with pip raises the module not found exception for cytoolz. E.g. with a clean python environment:

```bash
pip install conda
```
then

```python
>>> from conda.api import Solver
Traceback (most recent call last):
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/common/configuration.py", line 42, in <module>
    from cytoolz.dicttoolz import merge
ModuleNotFoundError: No module named 'cytoolz'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/core/index.py", line 7, in <module>
    from .linked_data import linked_data
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/gateways/disk/delete.py", line 15, in <module>
    from .read import get_json_content
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/gateways/disk/read.py", line 22, in <module>
    from ...models.channel import Channel
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/models/channel.py", line 9, in <module>
    from ..base.context import context
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/base/context.py", line 21, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/common/configuration.py", line 47, in <module>
    from .._vendor.toolz.functoolz import excepts
  File "/home/john/miniforge3/envs/blank/lib/python3.9/site-packages/conda/_vendor/toolz/functoolz.py", line 467
    f.__name__ for f in reversed((self.first,) + self.funcs),
    ^
SyntaxError: Generator expression must be parenthesized
```

**Comment by jaimergp** [comment]
> cc @jaimergp this also impacts [conda-libmamba-solver](https://github.com/conda-incubator/conda-libmamba-solver/blob/656cc7c36ddf21ade20961cc562e4d3ee62de450/conda_libmamba_solver/_libmamba.py#L18)

Thanks for the heads up! I think we will probably remove that legacy implementation in the next release (available as `libmamba-draft`). It was only around to ease debugging in case we needed a comparison during the refactor, but in practice we never needed it (fortunately).

**Comment by travishathaway** [comment]
Pull requests to our feedstock repositories:

- https://github.com/conda-forge/conda-feedstock/pull/170
- https://github.com/AnacondaRecipes/conda-feedstock/pull/8
