### ISSUE TITLE
Downloading repodata.json fails with libmamba and channel with basic HTTP auth

### ISSUE THREAD

**Issue by teake** [conda/conda#11344]
### What happened?

When attempting to create a new environment from a HTTP basic auth protected channel, conda borks while using the new libmamba solver:

```
$ conda create -n test --experimental-solver=libmamba -c https://<username>:<pass>@<my_channel> --override-channels <my_package>
```

This fails with the following strack trace:

<details>
<summary><code>RuntimeError</code></summary>

```
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 222, in solve_final_state
        index = LibMambaIndexHelper(
      File "/opt/conda/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 85, in __init__
        self._index = load_channels(
      File "/opt/conda/lib/python3.9/site-packages/conda_libmamba_solver/mamba_utils.py", line 117, in load_channels
        index = get_index(
      File "/opt/conda/lib/python3.9/site-packages/conda_libmamba_solver/mamba_utils.py", line 98, in get_index
        is_downloaded = dlist.download(api.MAMBA_DOWNLOAD_FAILFAST)
    RuntimeError: Multi-download failed.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.9/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/opt/conda/lib/python3.9/site-packages/conda/cli/install.py", line 260, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/opt/conda/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/opt/conda/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 222, in solve_final_state
        index = LibMambaIndexHelper(
      File "/opt/conda/lib/python3.9/site-packages/conda_libmamba_solver/utils.py", line 74, in __exit__
        raise exc_type(exc_value)
    RuntimeError: Multi-download failed.
```

</details>

https://github.com/mamba-org/mamba/issues/496 seems related. The same command with mamba 0.22.1, `$ mamba create [...]`, works fine though.

### Conda info

<details>
<summary><code>conda info</code></summary>

```Shell
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.10.final.0
       virtual packages : __linux=5.10.76=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.10 Linux/5.10.76-linuxkit centos/7.9.2009 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

</details>

### Conda config

<details>
<summary><code>conda config</code></summary>

```Shell
==> /root/.condarc <==
notify_outdated_conda: False
path_conflict: warn
channels:
  - conda-forge
show_channel_urls: True
conda_build:
  config_file: /opt/conda/conda_build_config.yaml
  error_overlinking: True
```

</details>

### Conda list

<details>
<summary><code>conda list</code></summary>

```Shell
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
brotlipy                  0.7.0           py39h3811e60_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py39hf3d152e_1    conda-forge
cffi                      1.15.0           py39h4bc2ebd_0    conda-forge
chardet                   4.0.0            py39hf3d152e_2    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4            py39hf3d152e_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py39hf3d152e_0    conda-forge
conda-build               3.21.8           py39hf3d152e_0    conda-forge
conda-forge-pinning       2022.02.15.10.00.06      hd8ed1ab_0    conda-forge
conda-libmamba-solver     22.3.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    1.7.3            py39h3811e60_1    conda-forge
conda-verify              3.1.1           py39hf3d152e_1004    conda-forge
coverage                  6.3.2            py39hb9d737c_1    conda-forge
coverage-fixpaths         1.2.0                      py_0    conda-forge
cryptography              36.0.1           py39h95dcef6_0    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39hf3d152e_4    conda-forge
glob2                     0.7                        py_0    conda-forge
icu                       69.1                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_12    conda-forge
libgomp                   11.2.0              h1d223b6_12    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblief                   0.11.5               h9c3ff4c_1    conda-forge
libmamba                  0.22.1               h9c208ef_0    conda-forge
libmambapy                0.22.1           py39h3216e65_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_12    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.9.12               h885dcf4_1    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     0.22.1           py39hfa8f2c8_0    conda-forge
markupsafe                2.1.0            py39hb9d737c_0    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
patchelf                  0.14.5               h58526e2_0    conda-forge
pip                       22.0.3             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
psutil                    5.9.0            py39h3811e60_0    conda-forge
py-lief                   0.11.5           py39he80948d_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py39h3811e60_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1            py39hf3d152e_4    conda-forge
python                    3.9.10          h85951f9_2_cpython    conda-forge
python-libarchive-c       4.0              py39hf3d152e_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39h3811e60_3    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               habb4d0f_1    conda-forge
ruamel_yaml               0.15.80         py39h3811e60_1006    conda-forge
setuptools                60.9.3           py39hf3d152e_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
urllib3                   1.26.8             pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

</details>

### Log file & additional context

[20220317-090312-125379.log](https://github.com/conda/conda/files/8283243/20220317-090312-125379.log)

**Comment by jaimergp** [comment]
Thanks for the feedback! The fix is surprisingly simple and an oversight on my end, sorry! It's literally a [single line](https://github.com/conda-incubator/conda-libmamba-solver/pull/23/files#diff-e6794455e7cacff948cf95915e290bc1f742360246a7a96f809b7627bbc379c4R108)!

I am adding tests (as seen in the `mamba` repo) to ensure that flag doesn't trigger other errors in local channels we saw while testing against `conda`'s integration suite.
