### ISSUE TITLE
Creating environment from yaml file triggers an assert in conda

### ISSUE THREAD

**Issue by rgommers** [conda/conda#11347]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I looked at the [README.md](https://github.com/conda-incubator/conda-libmamba-solver) and didn't see anything to help

### What happened?

Using the `libmamba` solver to create an environment from `environment_meson.yml` in the SciPy repo triggers an `assert` in `conda`:

```
$ git clone git@github.com:scipy/scipy.git && cd scipy
$ conda env create -f environment_meson.yml --experimental-solver=libmamba

***

NOTE: You are using the EXPERIMENTAL libmamba solver integration.

If something is not working as expected, please:

1. Go to https://github.com/conda/conda/issues/new/choose
2. Choose the "Libmamba Solver Feedback (Experimental Feature)" option
3. Attach the log file found in the following path:

/home/rgommers/anaconda3/pkgs/.logs/20220318-161722-870961.log

Thank you for your help!

***

pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
pkgs/main/noarch                                   804.6kB @   2.4MB/s  0.3s
pkgs/main/linux-64                                   4.4MB @   4.3MB/s  1.1s
conda-forge/noarch                                   7.6MB @   4.6MB/s  1.8s
conda-forge/linux-64                                21.6MB @   4.5MB/s  5.0s
Collect all metadata: done
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 142, in execute
        result[installer_type] = installer.install(prefix, pkg_specs, args, env)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_env/installers/conda.py", line 51, in install
        prune=getattr(args, 'prune', False), update_modifier=UpdateModifier.FREEZE_INSTALLED)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 155, in solve_for_transaction
        should_retry_solve)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 196, in solve_for_diff
        force_remove, should_retry_solve)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_libmamba_solver/solver.py", line 242, in solve_final_state
        out_state = self._solving_loop(in_state, out_state, index)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_libmamba_solver/solver.py", line 261, in _solving_loop
        solved = self._solve_attempt(in_state, out_state, index)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_libmamba_solver/solver.py", line 404, in _solve_attempt
        tasks = self._specs_to_tasks(in_state, out_state)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_libmamba_solver/solver.py", line 434, in _specs_to_tasks
        return self._specs_to_tasks_add(in_state, out_state)
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda_libmamba_solver/solver.py", line 447, in _specs_to_tasks_add
        spec_str = spec.conda_build_form()
      File "/home/rgommers/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 372, in conda_build_form
        assert version
    AssertionError

`$ /home/rgommers/anaconda3/bin/conda-env create -f environment_meson.yml --experimental-solver=libmamba`

  environment variables:
                 CIO_TEST=<not set>
        CMAKE_PREFIX_PATH=/home/rgommers/anaconda3
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/rgommers/anaconda3/bin/conda
             CONDA_PREFIX=/home/rgommers/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/rgommers/anaconda3/bin/python
               CONDA_ROOT=/home/rgommers/anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=/opt/cuda
           CURL_CA_BUNDLE=<not set>
          MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
                     PATH=/home/rgommers/anaconda3/bin:/home/rgommers/anaconda3/bin:/home/rgomme
                          rs/.npm-global/bin:/home/rgommers/.local/bin:/home/rgommers/anaconda3/
                          bin:/home/rgommers/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/us
                          r/local/sbin:/opt/cuda/bin:/opt/cuda/nsight_compute:/opt/cuda/nsight_s
                          ystems/bin:/usr/lib/jvm/default/bin:/opt/cuda/bin:/opt/cuda/nsight_com
                          pute:/opt/cuda/nsight_systems/bin:/usr/lib/jvm/default/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base
    active env location : /home/rgommers/anaconda3
            shell level : 1
       user config file : /home/rgommers/.condarc
 populated config files : /home/rgommers/anaconda3/.condarc
                          /home/rgommers/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.4
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.16.10=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rgommers/anaconda3  (writable)
      conda av data dir : /home/rgommers/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rgommers/anaconda3/pkgs
                          /home/rgommers/.conda/pkgs
       envs directories : /home/rgommers/anaconda3/envs
                          /home/rgommers/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.10 Linux/5.16.10-arch1-1 antergos/ glibc/2.35
                UID:GID : 1000:985
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 
Timeout reached. No report sent.

info     libmamba Freeing pool.
info     libmamba Freeing solver.
```

### Conda info

<details>

```Shell
$ conda info

     active environment : base
    active env location : /home/rgommers/anaconda3
            shell level : 1
       user config file : /home/rgommers/.condarc
 populated config files : /home/rgommers/anaconda3/.condarc
                          /home/rgommers/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.4
         python version : 3.7.10.final.0
       virtual packages : __cuda=11.6=0
                          __linux=5.16.10=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/rgommers/anaconda3  (writable)
      conda av data dir : /home/rgommers/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/rgommers/anaconda3/pkgs
                          /home/rgommers/.conda/pkgs
       envs directories : /home/rgommers/anaconda3/envs
                          /home/rgommers/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.7.10 Linux/5.16.10-arch1-1 antergos/ glibc/2.35
                UID:GID : 1000:985
             netrc file : None
           offline mode : False
```

</details>

### Conda config

<details>

```Shell
$ conda config --show-sources
==> /home/rgommers/anaconda3/.condarc <==
channels:
  - conda-forge
  - defaults

==> /home/rgommers/.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
unsatisfiable_hints: True
```

</details>

### Conda list

<details>

```Shell
$ conda list --show-channel-urls
# packages in environment at /home/rgommers/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
anaconda-client           1.8.0              pyhd8ed1ab_0    conda-forge
anaconda-navigator        1.10.0                   py37_0    defaults
anyio                     3.5.0            py37h89c1867_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py37h5e8e339_1    conda-forge
asv                       0.4.2                    pypi_0    pypi
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
babel                     2.9.1              pyh44b312d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
black                     22.1.0             pyhd8ed1ab_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py37h5e8e339_1003    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
certifi                   2021.10.8        py37h89c1867_1    conda-forge
cffi                      1.14.6           py37hc58025e_0    conda-forge
chardet                   4.0.0            py37h89c1867_2    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.0.4            py37h89c1867_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
conda                     4.12.0           py37h89c1867_0    conda-forge
conda-build               3.21.4           py37h89c1867_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
conda-libmamba-solver     22.3.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    1.8.0            py37h540881e_0    conda-forge
conda-verify              3.1.1           py37h89c1867_1003    conda-forge
cryptography              36.0.1           py37hf1a17b8_0    conda-forge
cudatoolkit               11.2.2               he111cf0_8    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.21                  pypi_0    pypi
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dbus                      1.13.6               h48d8840_2    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dnspython                 1.16.0                   pypi_0    pypi
docutils                  0.18.1           py37h89c1867_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
execnet                   1.9.0              pyhd8ed1ab_0    conda-forge
expat                     2.4.7                h27087fc_0    conda-forge
filelock                  3.6.0              pyhd8ed1ab_0    conda-forge
flake8                    3.7.8                    pypi_0    pypi
flake8-bugbear            19.8.0                   pypi_0    pypi
flake8-comprehensions     2.2.0                    pypi_0    pypi
flake8-executable         2.0.3                    pypi_0    pypi
flake8-mypy               17.8.0                   pypi_0    pypi
flake8-pyi                20.5.0                   pypi_0    pypi
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fontconfig                2.13.96              h8e229c2_2    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
future                    0.18.2           py37h89c1867_4    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.68.3               h9c3ff4c_0    conda-forge
glib-tools                2.68.3               h9c3ff4c_0    conda-forge
glob2                     0.7                        py_0    conda-forge
grin                      1.2.1.dev0               pypi_0    pypi
gst-plugins-base          1.18.4               hf529b03_2    conda-forge
gstreamer                 1.18.4               h76c114f_2    conda-forge
hypothesis                6.9.2              pyhd8ed1ab_0    conda-forge
icu                       68.2                 h9c3ff4c_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagesize                 1.3.0              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py37h89c1867_0    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_0    conda-forge
importlib_resources       5.4.0              pyhd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipykernel                 5.5.5            py37h085eea5_0    conda-forge
ipython                   7.22.0           py37h085eea5_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
jbig                      2.1               h7f98852_2003    conda-forge
jedi                      0.18.0           py37h89c1867_2    conda-forge
jinja2                    3.0.3              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h7f98852_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter_client            7.1.2              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py37h89c1867_0    conda-forge
jupyter_server            1.15.6             pyhd8ed1ab_0    conda-forge
jupyterlab                3.3.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.11.0             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.0            py37h7cecad7_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libarchive                3.5.2                hccf745f_1    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               h9b69904_4    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgfortran-ng            7.5.0               h14aa051_20    conda-forge
libgfortran4              7.5.0               h14aa051_20    conda-forge
libglib                   2.68.3               h3e27bee_0    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
liblief                   0.11.5               h9c3ff4c_1    conda-forge
libllvm11                 11.1.0               hf817b99_3    conda-forge
libmamba                  0.22.1               h9c208ef_0    conda-forge
libmambapy                0.22.1           py37h4c0aa37_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.5                 hd57d9b9_1    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.19               h780b84a_5    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libtiff                   4.3.0                h542a066_3    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp                   1.2.2                h3452ae3_0    conda-forge
libwebp-base              1.2.2                h7f98852_1    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libzlib                   1.2.11            h36c2ea0_1013    conda-forge
linkchecker               10.0.0.dev0              pypi_0    pypi
llvm-openmp               13.0.1               he0ac6c6_1    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.1            py37h540881e_0    conda-forge
matplotlib                3.4.1            py37h89c1867_0    conda-forge
matplotlib-base           3.4.1            py37hdd32ed1_0    conda-forge
mistune                   0.8.4           py37h5e8e339_1005    conda-forge
mkl                       2020.4             h726a3e6_304    conda-forge
mypy                      0.812            py37h5e8e339_2    conda-forge
mypy_extensions           0.4.3            py37h89c1867_4    conda-forge
mysql-common              8.0.28               ha770c72_0    conda-forge
mysql-libs                8.0.28               hfa10184_0    conda-forge
navigator-updater         0.2.1                    py37_0    defaults
nbclassic                 0.3.7              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.13             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.4            py37h89c1867_0    conda-forge
nbformat                  5.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
notebook                  6.4.10             pyha770c72_0    conda-forge
notebook-shim             0.1.0              pyhd8ed1ab_0    conda-forge
nspr                      4.32                 h9c3ff4c_1    conda-forge
nss                       3.74                 hb5efdd6_0    conda-forge
numpy                     1.20.3           py37h038b26d_1    conda-forge
numpydoc                  1.1.0                      py_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openssl                   1.1.1l               h7f98852_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.2.4            py37h219a48f_0    conda-forge
pandoc                    2.17.1.1             ha770c72_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
patchelf                  0.14.5               h58526e2_0    conda-forge
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.0.1            py37h44f0d7a_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pkginfo                   1.8.2              pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py37h89c1867_2    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
psutil                    5.9.0            py37h5e8e339_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-lief                   0.11.5           py37hcd2ae1e_1    conda-forge
pybind11                  2.3.0                    pypi_0    pypi
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.3           py37h5e8e339_1009    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py37h89c1867_8    conda-forge
pyqt-impl                 5.12.3           py37hac37412_8    conda-forge
pyqt5-sip                 4.19.18          py37hcd2ae1e_8    conda-forge
pyqtchart                 5.12             py37he336c9b_8    conda-forge
pyqtwebengine             5.12.1           py37he336c9b_8    conda-forge
pyrsistent                0.18.1           py37h5e8e339_0    conda-forge
pysocks                   1.7.1            py37h89c1867_4    conda-forge
pytest                    7.1.1            py37h89c1867_0    conda-forge
pytest-forked             1.4.0              pyhd8ed1ab_0    conda-forge
pytest-xdist              2.2.1              pyhd8ed1ab_0    conda-forge
python                    3.7.10          hffdb5ce_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0              py37h89c1867_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2021.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py37h5e8e339_3    conda-forge
pyzmq                     22.3.0           py37h336d617_1    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.3               h7f98852_0    conda-forge
reproc-cpp                14.2.3               h9c3ff4c_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               h2f28480_2    conda-forge
ruamel_yaml               0.15.80         py37h5e8e339_1006    conda-forge
scipy                     1.5.3            py37h8911b10_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                60.10.0          py37h89c1867_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sniffio                   1.2.0            py37h89c1867_2    conda-forge
snowballstemmer           2.2.0              pyhd8ed1ab_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sparse                    0.10.0                   pypi_0    pypi
sphinx                    3.5.3              pyhd8ed1ab_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    2.0.0              pyhd8ed1ab_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.5              pyhd8ed1ab_1    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
terminado                 0.13.3           py37h89c1867_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
torch                     1.12.0a0+gitb9ccbe4           dev_0    <develop>
tornado                   6.1              py37h5e8e339_2    conda-forge
tqdm                      4.63.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typed-ast                 1.4.0                    pypi_0    pypi
types-mypy-extensions     0.4.2                    pypi_0    pypi
types-typing-extensions   3.7.2                    pypi_0    pypi
typing-extensions         3.7.4                    pypi_0    pypi
typing_extensions         4.1.1              pyha770c72_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.3.1              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.0            py37h89c1867_0    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.6.3                he1b5a44_4    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h36c2ea0_1013    conda-forge
zstd                      1.5.2                ha95c52a_0    conda-forge
```

</details>

### Log file & additional context

[20220318-161722-870961.log](https://github.com/conda/conda/files/8306207/20220318-161722-870961.log)

**Comment by rgommers** [comment]
[20220318-161722-870961.log](https://github.com/conda/conda/files/8306207/20220318-161722-870961.log)

**Comment by jaimergp** [comment]
Looks like it's caused by `libblas=*=*openblas`, same as https://github.com/mamba-org/mamba/pull/322. This is internally parsed as `libblas=[build=*mkl]`, which leaves the version unset. I guess `conda` could just say that if version is not set, it's equivalent to `*`, and hence the assertion is not needed. We will probably handle this at `conda-libmamba-solver` anyway.

You can also reproduce it with `conda create -n test --dry-run --experimental-solver=libmamba "libblas=*=*openblas"` too.
