### ISSUE TITLE
Can anaconda use repositories with local paths?

### ISSUE THREAD

**Issue by nmanhong** [conda/conda#11379]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

Can anaconda use repositories with local paths? For example, what format of installation package does python need? I set DEFAULT_CHANNELS to file:///home/user, added linux-mips64 platform, what else do I need to do, the code is too complicated and I can't understand, my system is mips, but I want to use anaconda, I should How to do it

### Conda info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/cli/main_info.py", line 316, in execute
        info_dict = get_info_dict(args.system)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/cli/main_info.py", line 135, in get_info_dict
        _supplement_index_with_system(virtual_pkg_index)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/core/index.py", line 171, in _supplement_index_with_system
        rec = _make_virtual_package('__' + libc_family, libc_version)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/core/index.py", line 146, in _make_virtual_package
        fn=name,
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/_vendor/auxlib/entity.py", line 722, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/_vendor/auxlib/entity.py", line 739, in __init__
        setattr(self, key, kwargs[key])
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/_vendor/auxlib/entity.py", line 430, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/_vendor/auxlib/entity.py", line 674, in box
        return self._type(val)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/models/channel.py", line 37, in __call__
        c = Channel._cache_[value] = Channel.from_value(value)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/models/channel.py", line 115, in from_value
        if _stripped in context.custom_multichannels:
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
        cache[inner_attname] = func(self)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/base/context.py", line 642, in custom_multichannels
        default_channels = list(self._default_channels)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/common/configuration.py", line 1212, in __get__
        merged = matches[0].merge(matches) if matches else self.type.default
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/common/configuration.py", line 901, in default
        wrapped_default = DefaultValueRawParameter("default", "default", self._default)
      File "/usr/local/python3/lib/python3.7/site-packages/conda-4.8.5-py3.7.egg/conda/common/configuration.py", line 399, in __init__
        self.source, self.key, self._raw_value[i]))
    TypeError: 'set' object is not subscriptable

`$ /usr/local/python3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

### Conda config

```shell
nothing
```

### Conda list

```shell
EnvironmentLocationNotFound: Not a conda environment: /usr/local/python3
```

### Additional Context

Can anaconda use repositories with local paths? For example, what format of installation package does python need? I set DEFAULT_CHANNELS to file:///home/user, added linux-mips64 platform, what else do I need to do, the code is too complicated and I can't understand, my system is mips, but I want to use anaconda, I should How to do it

**Comment by nmanhong** [comment]
@chenghlee

**Comment by travishathaway** [comment]
Hi @nmanhong,

Thanks for submitting this bug. While we look into this more, I can suggest that you update the version of `conda` you are using (it appears to be `4.8.5`, if I'm correct?). You can do that with the following command: `conda update conda`.

Let us know if you still experiencing issues after updating to the latest version (`4.12`).
