### ISSUE TITLE
Anaconda failed to install on Mac OS Monterey Version 12.1

### ISSUE THREAD

**Issue by lucaguarro** [conda/conda#11530]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

When I try to install Anaconda Graphical Installer AND Command Line Installer, I get an error and it fails to install.

The GUI Installer gives a generic error message simply stating that Anaconda failed to install.

Instead with the command line error, I get the following python traceback after saying "yes" to "Do you wish the installer to initialize Anaconda3 by running conda init":

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/cli/main_init.py", line 50, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/core/initialize.py", line 118, in initialize
        run_plan_elevated(plan2)
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/core/initialize.py", line 687, in run_plan_elevated
        result = subprocess_call(
      File "/Users/gguarro/anaconda3/lib/python3.9/site-packages/conda/gateways/subprocess.py", line 100, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/Users/gguarro/anaconda3/lib/python3.9/subprocess.py", line 1134, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/Users/gguarro/anaconda3/lib/python3.9/subprocess.py", line 1959, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'
```

I also get this output:

`$ /Users/gguarro/anaconda3/bin/conda init zsh`

```
  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/Users/gguarro/anaconda3
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Library/Frameworks/Python.framework/Versions/3.10/bin:/opt/homebrew/b
                          in:/opt/homebrew/sbin:/Library/Frameworks/Python.framework/Versions/3.
                          7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /Users/gguarro/.condarc
 populated config files : 
          conda version : 4.13.0
    conda-build version : 3.21.9
         python version : 3.9.12.final.0
       virtual packages : __osx=12.1=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/gguarro/anaconda3  (writable)
      conda av data dir : /Users/gguarro/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/gguarro/anaconda3/pkgs
                          /Users/gguarro/.conda/pkgs
       envs directories : /Users/gguarro/anaconda3/envs
                          /Users/gguarro/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.13.0 requests/2.27.1 CPython/3.9.12 Darwin/21.2.0 OSX/12.1
                UID:GID : 503:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

### Conda info

```shell
Anaconda failed to install so conda command is not found.
```

### Conda config

```shell
Conda command is not found.
```

### Conda list

```shell
Conda command is not found.
```

**Comment by lpilz** [comment]
I get the same bug with `conda 22.9.0` on Arch Linux after trying to fix the commandline issue #11885 with `conda init bash`:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/anaconda/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/anaconda/lib/python3.9/site-packages/conda/cli/main_init.py", line 50, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/opt/anaconda/lib/python3.9/site-packages/conda/core/initialize.py", line 119, in initialize
        run_plan_elevated(plan2)
      File "/opt/anaconda/lib/python3.9/site-packages/conda/core/initialize.py", line 688, in run_plan_elevated
        result = subprocess_call(
      File "/opt/anaconda/lib/python3.9/site-packages/conda/gateways/subprocess.py", line 100, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/opt/anaconda/lib/python3.9/subprocess.py", line 1134, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/opt/anaconda/lib/python3.9/subprocess.py", line 1959, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /opt/anaconda/bin/conda init bash`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/anaconda/bin/conda
             CONDA_PREFIX=/opt/anaconda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/anaconda/bin/python
               CONDA_ROOT=/opt/anaconda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/anaconda/bin:/opt/anaconda/condabin:/opt/android-sdk/emulator:/ho
                          me/lpilz/.poetry/bin:/home/lpilz/.pyenv/shims:/home/lpilz/.pyenv/bin:/
                          usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/opt/android-sdk/platform-
                          tools:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/usr/lib/jvm/d
                          efault/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:
                          /var/lib/snapd/snap/bin:/home/lpilz/scripts:/home/lpilz/.local/bin:/op
                          t/android-sdk/emulator:/opt/android-sdk/platform-tools:/opt/android-
                          sdk/tools/bin:/opt/android-sdk/tools
               PYTHONPATH=:/usr/lib
   PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : base
    active env location : /opt/anaconda
            shell level : 1
       user config file : /home/lpilz/.condarc
 populated config files : /home/lpilz/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __linux=6.0.2=0
                          __glibc=2.36=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/anaconda  (read only)
      conda av data dir : /opt/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /daten/.conda/pkgs
       envs directories : /daten/.conda/envs
                          /home/lpilz/.conda/envs
                          /opt/anaconda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/6.0.2-arch1-1 arch/ glibc/2.36
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

**Comment by dsclassen** [comment]
I'm experiencing the same error.

I upgraded conda from 4.14.0 to 22.9.0 which broke my shell prompt as per issue #11885. One suggested way to fix my shell prompt was to run `conda init bash` again. However, it fails with this error:

```
TypeError: memoryview: a bytes-like object is required, not 'str'
```

**Comment by marcospb19** [comment]
I get the same error on Arch Linux, wether I run `conda init bash`, or `conda init zsh`.
