### ISSUE TITLE
conda crashes on empty environment.yml

### ISSUE THREAD

**Issue by jjnurminen** [conda/conda#11542]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

I accidentally had an empty `environment.yml` file when running `conda env create`, which led to the error below.

The error is a bit cryptic, so it took me a while to track the problem down. Maybe some sanity checks on `environment.yml` would be good.

<details>
<summary>Error report</summary>

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1080, in __call__
        return func(*args, **kwargs)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 144, in from_yaml
        data = validate_keys(data, kwargs)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/env.py", line 38, in validate_keys
        for key in data.keys():
    AttributeError: 'NoneType' object has no attribute 'keys'
```

</details>

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /usr/local/miniconda3
            shell level : 1
       user config file : /home/jussi/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : not installed
         python version : 3.9.1.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/miniconda3  (read only)
      conda av data dir : /usr/local/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /home/jussi/.conda/pkgs
       envs directories : /home/jussi/.conda/envs
                          /usr/local/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.9.1 Linux/5.15.0-37-generic ubuntu/22.04 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

**Comment by kenodegard** [comment]
@jjnurminen Thanks for reporting this!
