### ISSUE TITLE
missing activate.d and deactivate.d inside envs 

### ISSUE THREAD

**Issue by dilpreet7365** [conda/conda#11550]
### Checklist

- [X] I added a descriptive title
- [X] I searched for other issues and couldn't find a solution or duplication
- [X] I already searched in Google and didn't find any good information or help
- [X] I looked at the [docs](https://docs.conda.io/projects/conda/en/latest/user-guide/index.html) and didn't see anything to help

### What happened?

<details>
<summary>Error Report</summary>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in main
        return activator_main()
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 1207, in main
        print(activator.execute(), end='')
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 178, in execute
        return getattr(self, self.command)()
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 152, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 297, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 321, in _build_activate_stack
        activate_scripts = self._get_activate_scripts(prefix)
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 705, in _get_activate_scripts
        p for p in paths if p[se_len:] == _script_extension
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 705, in <genexpr>
        p for p in paths if p[se_len:] == _script_extension
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/conda/activate.py", line 701, in <genexpr>
        paths = (entry.path for entry in scandir(join(prefix, 'etc', 'conda', 'activate.d')))
      File "/home/dstest2/miniconda2/lib/python2.7/site-packages/scandir.py", line 564, in scandir_python
        raise posix_error(path)
    OSError: [Errno 2] No such file or directory: u'/home/dstest2/miniconda2/envs/tf_new/etc/conda/activate.d'

`$ /home/dstest2/miniconda2/bin/conda shell.posix activate tf_new`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=tf_2.4
                CONDA_EXE=/home/dstest2/miniconda2/bin/conda
CONDA_MKL_INTERFACE_LAYER_BACKUP=
             CONDA_PREFIX=/home/dstest2/miniconda2/envs/tf_2.4
           CONDA_PREFIX_1=/home/dstest2/miniconda2
    CONDA_PROMPT_MODIFIER=(tf_2.4)
         CONDA_PYTHON_EXE=/home/dstest2/miniconda2/bin/python
               CONDA_ROOT=/home/dstest2/miniconda2
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda/lib64:/usr/local/cuda-9.0/lib64:/usr/local/cuda-11/lib
                          64:/usr/local/cuda-11.1/lib64:/usr/local/cuda-11.2/lib64::/usr/local/c
                          uda-9.0/lib64/
                     PATH=/home/dstest2/miniconda2/bin:/home/dstest2/miniconda2/envs/tf_2.4/bin:
                          /home/dstest2/miniconda2/bin:/home/dstest2/miniconda2/bin:/home/dstest
                          2/miniconda2/bin:/home/dstest2/.local/bin:/usr/local/cuda/bin:/home/ds
                          test2/miniconda2/bin:/home/dstest2/miniconda2/bin:/home/dstest2/minico
                          nda2/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:
                          /bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda-9.0/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : tf_2.4
    active env location : /home/dstest2/miniconda2/envs/tf_2.4
            shell level : 2
       user config file : /home/dstest2/.condarc
 populated config files : /home/dstest2/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 2.7.17.final.0
       virtual packages : __glibc=2.27
                          __cuda=11.2
       base environment : /home/dstest2/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dstest2/miniconda2/pkgs
                          /home/dstest2/.conda/pkgs
       envs directories : /home/dstest2/miniconda2/envs
                          /home/dstest2/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.22.0 CPython/2.7.17 Linux/5.4.0-117-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/dstest2/.netrc
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
```

</details>

The envs were working fine previously, this error occurred once I updated Conda.

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /home/dstest2/miniconda2
            shell level : 1
       user config file : /home/dstest2/.condarc
 populated config files : /home/dstest2/.condarc
          conda version : 4.8.4
    conda-build version : not installed
         python version : 2.7.17.final.0
       virtual packages : __glibc=2.27
                          __cuda=11.2
       base environment : /home/dstest2/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dstest2/miniconda2/pkgs
                          /home/dstest2/.conda/pkgs
       envs directories : /home/dstest2/miniconda2/envs
                          /home/dstest2/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.4 requests/2.22.0 CPython/2.7.17 Linux/5.4.0-117-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/dstest2/.netrc
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /home/dstest2/.condarc <==
auto_activate_base: True
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/dstest2/miniconda2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
asn1crypto                1.4.0                      py_0    defaults
attrs                     21.4.0             pyhd3eb1b0_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports-functools-lru-cache 1.6.4                    pypi_0    pypi
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaults
backports_abc             0.5                        py_1    defaults
beautifulsoup4            4.9.3                    pypi_0    pypi
bleach                    3.1.0                    py27_0    defaults
bs4                       0.0.1                    pypi_0    pypi
ca-certificates           2022.4.26            h06a4308_0    defaults
certifi                   2020.6.20          pyhd3eb1b0_3    defaults
cffi                      1.13.0           py27h2e261b9_0    defaults
chardet                   3.0.4                 py27_1003    defaults
click                     7.0                      pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0    defaults
conda                     4.8.4                    py27_0    defaults
conda-package-handling    1.6.0            py27h7b6447c_0    defaults
configparser              4.0.2                    py27_0    defaults
cryptography              2.8              py27h1ba5d50_0    defaults
cycler                    0.10.0                   pypi_0    pypi
datetime                  4.3                      pypi_0    pypi
decorator                 4.4.0                    py27_1    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.3                      py27_0    defaults
enum34                    1.1.6                    py27_1    defaults
flask                     1.1.1                    pypi_0    pypi
freetype                  2.11.0               h70c0345_0    defaults
functools32               3.2.3.2                  py27_1    defaults
futures                   3.3.0                    py27_0    defaults
idna                      2.8                      py27_0    defaults
ipaddress                 1.0.23                     py_0    defaults
ipykernel                 4.9.0                    py27_1    defaults
ipython                   5.8.0                    py27_1    conda-forge
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
itsdangerous              1.1.0                    pypi_0    pypi
jinja2                    2.10.3                   pypi_0    pypi
jpeg                      9e                   h7f8727e_0    defaults
jsonschema                3.0.2                    py27_0    defaults
jupyter_client            5.3.4                    py27_0    defaults
jupyter_core              4.6.3            py27h8c360ce_1    conda-forge
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20210910         h7f8727e_0    defaults
libffi                    3.4.2                h295c915_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libpng                    1.6.37               hbc83047_0    defaults
libsodium                 1.0.17               h516909a_0    conda-forge
libstdcxx-ng              11.2.0               h1234567_1    defaults
libtiff                   4.2.0                h2818925_1    defaults
libwebp-base              1.2.2                h7f8727e_0    defaults
lz4-c                     1.9.3                h295c915_1    defaults
markupsafe                1.1.1            py27hdf8410d_1    conda-forge
matplotlib                2.2.5                    pypi_0    pypi
mistune                   0.8.4            py27h7b6447c_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py27_0    conda-forge
ncurses                   6.3                  h7f8727e_2    defaults
notebook                  5.7.8                    py27_1    conda-forge
numpy                     1.16.6                   pypi_0    pypi
olefile                   0.46                     py27_0    defaults
opencv-contrib-python     4.2.0.32                 pypi_0    pypi
openssl                   1.1.1o               h7f8727e_0    defaults
pandas                    0.24.2                   pypi_0    pypi
pandoc                    2.12                 h06a4308_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
pathlib2                  2.3.5            py27h8c360ce_1    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5                    py27_0    defaults
pillow                    6.2.1                    pypi_0    pypi
prometheus_client         0.6.0                    py27_0    defaults
prompt_toolkit            1.0.15                     py_1    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pycosat                   0.6.3            py27h7b6447c_0    defaults
pycparser                 2.19                     py27_0    defaults
pygments                  2.3.1                    py27_0    defaults
pyopenssl                 19.1.0                   py27_0    defaults
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.15.7           py27hdf8410d_1    conda-forge
pysocks                   1.7.1                    py27_0    defaults
python                    2.7.17               h9bab390_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python_abi                2.7                    1_cp27mu    conda-forge
pytz                      2020.1                   pypi_0    pypi
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     19.0.0           py27h76efe43_1    conda-forge
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py27_0    defaults
ruamel_yaml               0.15.46          py27h14c3975_0    defaults
scandir                   1.10.0             pyh5d7bf9c_3    defaults
scipy                     1.2.3                    pypi_0    pypi
seaborn                   0.9.1                    pypi_0    pypi
selenium                  3.141.0                  pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1    defaults
setuptools                41.4.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_2    defaults
singledispatch            3.7.0           pyhd3eb1b0_1001    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 1.9.6                    pypi_0    pypi
sqlite                    3.30.0               h7b6447c_0    defaults
subprocess32              3.5.4                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.3            py27h8c360ce_1    conda-forge
testpath                  0.4.2                    py27_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tornado                   5.1.1            py27h7b6447c_0    defaults
tqdm                      4.63.0             pyhd3eb1b0_0    defaults
traitlets                 4.3.3                    py27_0    defaults
urllib3                   1.24.2                   py27_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py27_1    defaults
werkzeug                  0.16.0                   pypi_0    pypi
xz                        5.2.5                h7f8727e_1    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.3.2                he1b5a44_2    conda-forge
zlib                      1.2.12               h7f8727e_2    defaults
zope-interface            5.1.0                    pypi_0    pypi
zstd                      1.5.2                ha4553b6_0    defaults
```

</details>

**Comment by kenodegard** [comment]
@dilpreet7365 Which version of conda did you update from?

**Comment by dilpreet7365** [comment]
It was from 4.2 to 4.8
