### ISSUE TITLE
conda install problem

### ISSUE THREAD

**Issue by johne13** [conda/conda#1160]
I got an error in conda and it suggested that I post the traceback and conda info here, so here it is...

```
C:\Users\eilerj\AppData\Local\Continuum\Anaconda>conda install c:\users\eilerj\downloads\pandas-0.15.2-np19py34_0.tar
Fetching package metadata: ..Could not connect to http://repo.continuum.io/pkgs/pro/win-64/
Could not connect to http://repo.continuum.io/pkgs/free/win-64/

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\install.py", line 270, in install
    install_tar(prefix, tar_path, verbose=not args.quiet)
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\install.py", line 31, in install_tar
    t = tarfile.open(tar_path, 'r')
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\tarfile.py", line 1660, in open
    return func(name, "r", fileobj, **kwargs)
  File "C:\Users\eilerj\AppData\Local\Continuum\Anaconda\lib\tarfile.py", line 1722, in gzopen
    fileobj = bltn_open(name, mode + "b")
IOError: [Errno 2] No such file or directory: 'c:\\users\\eilerj\\downloads\\pandas-0.15.2-np19py34_0.tar'

C:\Users\eilerj\AppData\Local\Continuum\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : C:\Users\eilerj\AppData\Local\Continuum\Anaconda  (writable)
  default environment : C:\Users\eilerj\AppData\Local\Continuum\Anaconda
     envs directories : C:\Users\eilerj\AppData\Local\Continuum\Anaconda\envs
        package cache : C:\Users\eilerj\AppData\Local\Continuum\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False
```

**Comment by johne13** [comment]
Ah, ignore this.  The file ended in .tar.bz2, not .tar so it just wasn't finding the file.  I don't see how to delete this so I'll just close it.  Please delete this for me if there is a way.  Sorry.

**Comment by asmeurer** [comment]
This still could use a better error message.
