### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by NJ2046** [conda/conda#11624]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

```
conda create -n adm_meituan python=3.8
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\nj\Miniconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\cli\install.py", line 174, in install
    args.override_channels)
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\api.py", line 34, in get_index
    return fetch_index(tuple(channel_urls))
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\utils.py", line 61, in __call__
    value = self.func(*args)
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\fetch.py", line 108, in fetch_index
    repodata = fetch_repodata(url)
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\fetch.py", line 72, in fetch_repodata
    u = connectionhandled_urlopen(request)
  File "C:\Users\nj\Miniconda\lib\site-packages\conda\connection.py", line 83, in connectionhandled_urlopen
    return urllib2.urlopen(request)
  File "C:\Users\nj\Miniconda\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Users\nj\Miniconda\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\Users\nj\Miniconda\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\Users\nj\Miniconda\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Users\nj\Miniconda\lib\urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Users\nj\Miniconda\lib\urllib2.py", line 1187, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Users\nj\Miniconda\lib\httplib.py", line 1045, in getresponse
    response.begin()
  File "C:\Users\nj\Miniconda\lib\httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "C:\Users\nj\Miniconda\lib\httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''

```

### Conda Info

```shell
platform : win-64
        conda version : 3.0.0
     root environment : C:\Users\nj\Miniconda  (writable)
  default environment : C:\Users\nj\Miniconda
     envs directories : C:\Users\nj\Miniconda\envs
        package cache : C:\Users\nj\Miniconda\pkgs
         channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\Users\nj\.condarc
    is foreign system : False
```

### Conda Config

```shell
C:\Users\nj>conda config --show-sources
usage: conda-script.py config [-h] [--system | --file FILE]
                              (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY BOOL_VALUE | --remove KEY VALUE | --remove-key KEY)
                              [-f]
conda-script.py config: error: one of the arguments --get --add --set --remove --remove-key is required
```

### Conda list

```shell
C:\Users\nj>conda list --show-channel-urls
usage: conda-script.py [-h] [-V] command ...
conda-script.py: error: unrecognized arguments: --show-channel-urls
```

### Additional Context

no

**Comment by jaimergp** [comment]
At first look it might have been a sporadic issue triggered by temporary network condition. Are you experiencing this problem often or continuously?

One more note, `conda info` reports you are using conda 3.0.0, which was tagged in 2014 😬  I would first suggest updating to a more recent release if the error persists.

**Comment by ldtas** [comment]
Could anyone please give me solutions to bellow problem ?

(base) C:\Users\ldtas>conda activate env0
(env0) C:\Users\ldtas>conda install -c anaconda cmake
(env0) C:\Users\ldtas>conda install -c conda-forge dlib
(Above 3 commands were OK)

(But Below command occurred following error)
(env0) C:\Users\ldtas>conda install --file requirements.txt
CondaValueError: could not parse 'certifi @ file:///C:/b/abs_85o_6fm0se/croot/certifi_1671487778835/work/certifi' in: requirements.txt

**Comment by jaimergp** [comment]
Please file a new issue for this error @ldtas.

In your `requirements.txt`, check that only `certifi` is listed in that line (remove the `@ ...`).
