### ISSUE TITLE
tornado should depend on certifi

### ISSUE THREAD

**Issue by minrk** [conda/conda#1167]
The tornado package on PyPI depends on [certifi](https://pypi.python.org/pypi/certifi). The tornado conda package probably should, too. certifi is required to make HTTPS requests.

**Comment by asmeurer** [comment]
@ilanschnell

**Comment by ilanschnell** [comment]
I've added certifi as a tornado dependency, which also means that certifi will be part of the next Anaconda installers.  Also, I've updated certifi to the latest version, which will be available very shortly.

**Comment by minrk** [comment]
Thanks, guys!

**Comment by bryevdv** [comment]
This should be re-opened:
```
bryan@0199-bryanv  ~ $ conda create -n test python=2.7.6 bokeh
Remote site alias https://api.anaconda.org does not exist in the config file
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/bryan/anaconda/envs/test:

The following NEW packages will be INSTALLED:

    backports:          1.0-py27_0    
    backports_abc:      0.4-py27_0    
    bokeh:              0.11.1-py27_0 
    futures:            3.0.5-py27_0  
    jinja2:             2.8-py27_0    
    markupsafe:         0.23-py27_0   
    mkl:                11.3.1-0      
    numpy:              1.11.0-py27_0 
    openssl:            1.0.1k-1      
    pip:                8.1.1-py27_1  
    python:             2.7.6-2       
    python-dateutil:    2.5.2-py27_0  
    pyyaml:             3.11-py27_1   
    readline:           6.2-2         
    requests:           2.9.1-py27_0  
    setuptools:         20.7.0-py27_0 
    singledispatch:     3.4.0.3-py27_0
    six:                1.10.0-py27_0 
    sqlite:             3.9.2-0       
    ssl_match_hostname: 3.4.0.2-py27_1
    tk:                 8.5.18-0      
    tornado:            4.3-py27_0    
    wheel:              0.29.0-py27_0 
    yaml:               0.1.6-0       
    zlib:               1.2.8-0       

Proceed ([y]/n)? 

Linking packages ...
[      COMPLETE      ]|#########################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#
bryan@0199-bryanv  ~ $ source activate test
discarding /Users/bryan/anaconda/bin from PATH
prepending /Users/bryan/anaconda/envs/test/bin to PATH
(test)bryan@0199-bryanv  ~ $ bokeh serve
Traceback (most recent call last):
  File "/Users/bryan/anaconda/envs/test/bin/bokeh", line 5, in <module>
    from bokeh.command.bootstrap import main
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/command/__init__.py", line 15, in <module>
    _build_docstring()
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/command/__init__.py", line 10, in _build_docstring
    from . import subcommands
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/command/subcommands/__init__.py", line 29, in <module>
    all = _collect()
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/command/subcommands/__init__.py", line 17, in _collect
    mod = import_module("." + modname, __package__)
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/command/subcommands/file_output.py", line 12, in <module>
    from ..util import build_single_handler_applications, die
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/command/util.py", line 10, in <module>
    from bokeh.application.handlers import ScriptHandler, DirectoryHandler, NotebookHandler
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/application/handlers/__init__.py", line 8, in <module>
    from .notebook import *
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/application/handlers/notebook.py", line 5, in <module>
    from .code import CodeHandler
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/application/handlers/code.py", line 8, in <module>
    from bokeh.io import set_curdoc, curdoc
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/io.py", line 30, in <module>
    from .core.state import State
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/core/state.py", line 46, in <module>
    from ..client import DEFAULT_SESSION_ID
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/client/__init__.py", line 6, in <module>
    from .session import ClientSession, pull_session, push_session, show_session, DEFAULT_SESSION_ID
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/client/session.py", line 10, in <module>
    from .connection import ClientConnection
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/bokeh/client/connection.py", line 14, in <module>
    from tornado.websocket import websocket_connect, WebSocketError
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/tornado/websocket.py", line 28, in <module>
    import tornado.web
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/tornado/web.py", line 86, in <module>
    from tornado import iostream
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/tornado/iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
  File "/Users/bryan/anaconda/envs/test/lib/python2.7/site-packages/tornado/netutil.py", line 39, in <module>
    import certifi
ImportError: No module named certifi
(test)bryan@0199-bryanv  ~ $ 
```

**Comment by bryevdv** [comment]
Bokeh server does not anywhere depend on `certifi`, the exception is coming from inside Tornado, which clearly *does* depend on `certifi`

**Comment by msarahan** [comment]
Confirming that current tornado recipe (https://github.com/ContinuumIO/anaconda/blob/master/packages/tornado-4.3/meta.yaml) does not list certifi as a dependency.  Reopening.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1693
