### ISSUE TITLE
Traceback (most recent call last): File "C:\Users\au708056\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in  from PyQt5.QtWebEngineWidgets import QWebEnginePage ImportError: DLL load failed while importing QtWebEngineWidgets: The specified procedure could not be found.

### ISSUE THREAD

**Issue by anandita473** [conda/conda#11675]
### Details

My spyder is not launching after I installed a couple of python packages:

```
pip install pyncview
pip install PyQt5
pip install SciPy
pip install netCDF4
```

and then received the following error: 

```
Traceback (most recent call last):
File "C:\Users\au708056\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 22, in 
from PyQt5.QtWebEngineWidgets import QWebEnginePage
ImportError: DLL load failed while importing QtWebEngineWidgets: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\Users\au708056\Anaconda3\Scripts\spyder-script.py", line 10, in 
sys.exit(main())
File "C:\Users\au708056\Anaconda3\lib\site-packages\spyder\app\start.py", line 233, in main
from spyder.app import mainwindow
File "C:\Users\au708056\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 59, in 
from qtpy import QtWebEngineWidgets # analysis:ignore
File "C:\Users\au708056\Anaconda3\lib\site-packages\qtpy\QtWebEngineWidgets.py", line 26, in 
from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ModuleNotFoundError: No module named 'PyQt5.QtWebKitWidgets'
```

please suggest

**Comment by kenodegard** [comment]
@anandita473 generally speaking, it is not advised to mix conda and pip installs in your conda environment (unless you absolutely must). In this case it looks like the culprit is the PyQt5 install from pip. Try uninstalling PyQt5 from pip and only relying on conda's pyqt:

```
pip uninstall PyQt5
conda install --force-reinstall pyqt spyder
```
