### ISSUE TITLE
Error when running : conda install --channel conda-forge cartopy

### ISSUE THREAD

**Issue by djacp2000** [conda/conda#11684]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Error when running : conda install --channel conda-forge cartopy

----

`$ C:\..\..\..\..\..\Python39\Scripts\conda install --channel conda-forge cartopy`

    Traceback (most recent call last):
      File "C:\Users\XX\AppData\Roaming\Python\Python39\site-packages\conda\install.py", line 201, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Python39\\pkgs\\menuinst-1.4.18-py310h5588dad_1\\info\\has_prefix'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\install.py", line 209, in yield_lines
        raise StopIteration
    StopIteration

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\install.py", line 943, in link
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\install.py", line 248, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\install.py", line 248, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\install.py", line 247, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\aleja\AppData\Roaming\Python\Python39\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration
  

### Conda Info

```shell
platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.13.final.0
       requests version : 2.28.1
       root environment : C:\Program Files\Python39  (writable)
    default environment : C:\Program Files\Python39
       envs directories : C:\Program Files\Python39\envs
          package cache : C:\Program Files\Python39\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

### Conda list

```shell
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
```

**Comment by mfansler** [comment]
Conda version is too old. Please upgrade.
