### ISSUE TITLE
Conda configuration output page is broken in docs.conda.io

### ISSUE THREAD

**Issue by kathatherine** [conda/conda#11702]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The conda config output that is printed to the Conda configuration page at https://docs.conda.io/projects/conda/en/latest/configuration.html is broken due to a missing module.

The error is:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/latest/conda/cli/main_config.py", line 14, in <module>
    from tlz.itertoolz import concat, groupby
ModuleNotFoundError: No module named 'tlz'

**Comment by kathatherine** [comment]
This has been fixed somehow, so I'm closing this issue.
