### ISSUE TITLE
numpy installed with conda is missing libgcc_s.1.1.dylib on Apple Silicon

### ISSUE THREAD

**Issue by markounikau** [conda/conda#11735]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following 3 lines executed on a Apple M1 machine result in an error:
```
conda create -n numpy_test numpy -c conda-forge
conda activate numpy_test
python -c "import numpy"
```
The error:
```
Traceback (most recent call last):
  File "/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libgcc_s.1.1.dylib
  Referenced from: /Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgfortran.5.dylib
  Reason: tried: '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/__init__.py", line 140, in <module>
    from . import core
  File "/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/__init__.py", line 49, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/Users/vmarkounikau/miniconda3/envs/numpy_test/bin/python"
  * The NumPy version is: "1.23.2"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: dlopen(/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/_multiarray_umath.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libgcc_s.1.1.dylib
  Referenced from: /Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgfortran.5.dylib
  Reason: tried: '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/lib/python3.10/site-packages/numpy/core/../../../../libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/Users/vmarkounikau/miniconda3/envs/numpy_test/bin/../lib/libgcc_s.1.1.dylib' (no such file), '/usr/local/lib/libgcc_s.1.1.dylib' (no such file), '/usr/lib/libgcc_s.1.1.dylib' (no such file)
```

The same error is produced for `Python 3.9` and `numpy 1.22`.
There's *no* error on the Apple Intel machines.

### Conda Info

```shell
active environment : numpy_test
    active env location : /Users/vmarkounikau/miniconda3/envs/numpy_test
            shell level : 2
       user config file : /Users/vmarkounikau/.condarc
 populated config files : /Users/vmarkounikau/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.11.final.0
       virtual packages : __osx=12.4=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/vmarkounikau/miniconda3  (writable)
      conda av data dir : /Users/vmarkounikau/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/vmarkounikau/miniconda3/pkgs
                          /Users/vmarkounikau/.conda/pkgs
       envs directories : /Users/vmarkounikau/miniconda3/envs
                          /Users/vmarkounikau/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.8.11 Darwin/21.5.0 OSX/12.4
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/vmarkounikau/.condarc <==
envs_dirs:
  - ~/miniconda3/envs
```

### Conda list

```shell
# packages in environment at /Users/vmarkounikau/miniconda3/envs/numpy_test:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2022.6.15            h4653dfc_0    conda-forge
libblas                   3.9.0           16_osxarm64_openblas    conda-forge
libcblas                  3.9.0           16_osxarm64_openblas    conda-forge
libcxx                    14.0.6               h04bba0f_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libgfortran               5.0.0           11_3_0_hd922786_24    conda-forge
libgfortran5              11.3.0              hdaf2cc0_24    conda-forge
liblapack                 3.9.0           16_osxarm64_openblas    conda-forge
libopenblas               0.3.21          openmp_hcb59c3b_1    conda-forge
libsqlite                 3.39.2               h2c9beb0_1    conda-forge
libzlib                   1.2.12               ha287fd2_2    conda-forge
llvm-openmp               14.0.4               hd125106_0    conda-forge
ncurses                   6.3                  h07bb92c_1    conda-forge
numpy                     1.23.2          py310h127c7cf_0    conda-forge
openssl                   3.0.5                h7aea29f_1    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
python                    3.10.5          h4eee789_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
readline                  8.1.2                h46ed386_0    conda-forge
setuptools                65.0.2          py310hbe9552e_0    conda-forge
sqlite                    3.39.2               h40dfcc0_1    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
tzdata                    2022c                h191b570_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
```

**Comment by markounikau** [comment]
The issue seems to be related to `libfortran` since pinning `libgfortran==5.0.0.dev0` removes the error.

**Comment by Meteodan** [comment]
@markounikau I have precisely the same problem, and was banging my head against the wall trying to figure out how I broke it. But it seems that the problem does appear to be a bug. I can confirm that installing libgfortran 5.0.0.dev0 fixes the problem for me. It installs libgcc_s.2.dylib in the environment libraries directory and references that one instead of the non-existent libgcc_s.1.1.dylib

**Comment by thk-cheng** [comment]
@markounikau Thank you so much for the quick fix.

**Comment by jaimergp** [comment]
This is a packaging issue. See https://github.com/conda-forge/numpy-feedstock/issues/279, where it got solved.
