### ISSUE TITLE
AttributeError: 'SSLError' object has no attribute 'message'

### ISSUE THREAD

**Issue by BobYing07** [conda/conda#11739]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I typed command ```conda update conda``` and ```conda install python=3.10.6```

it showed this log

```
Fetching package metadata: ......An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/pi/miniconda3/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/home/pi/miniconda3/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/home/pi/miniconda3/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 244, in install
    offline=args.offline)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/pi/miniconda3/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/home/pi/miniconda3/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/home/pi/miniconda3/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 150, in fetch_repodata
    stderrlog.info("SSL verification error %s\n" % e.message)
AttributeError: 'SSLError' object has no attribute 'message'
```

### Conda Info

```shell
Current conda install:

             platform : linux-armv7l
        conda version : 3.16.0
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/pi/miniconda3  (writable)
  default environment : /home/pi/miniconda3
     envs directories : /home/pi/miniconda3/envs
        package cache : /home/pi/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/rpi/linux-armv7l/
                        https://conda.anaconda.org/rpi/noarch/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-armv7l/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-armv7l/
                        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/free/linux-armv7l/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-armv7l/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/pi/.condarc
    is foreign system : False
```

### Conda Config

```shell
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required
```

### Conda list

```shell
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: --show-channel-urls
```

**Comment by BobYing07** [comment]
thanks,```ssl_verify:false``` worked
