### ISSUE TITLE
Conda install fails with: Invalid URL 'notices.json'

### ISSUE THREAD

**Issue by nejcskofic** [conda/conda#11743]
### What happened?

Running command `conda install --quiet "company.h5-base>=3.0,<4.0" -c bioconda -c conda-forge -c s3://company-conda-channels/dev -c defaults` fails in retrieving notices step:

<details>
<summary>Error Report</summary>

```
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Retrieving notices: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/core.py", line 75, in wrapper
        display_notices(
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/core.py", line 39, in display_notices
        channel_notice_responses = http.get_notice_responses(channel_name_urls, silent=silent)
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/http.py", line 36, in get_notice_responses
        return tuple(
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/http.py", line 39, in <genexpr>
        (
      File "/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
        yield fs.pop().result()
      File "/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 437, in result
        return self.__get_result()
      File "/opt/miniconda3/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
        raise self._exception
      File "/opt/miniconda3/lib/python3.8/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/http.py", line 42, in <lambda>
        lambda args: get_channel_notice_response(*args), url_and_names
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/cache.py", line 37, in wrapper
        return_value = func(url, name)
      File "/opt/miniconda3/lib/python3.8/site-packages/conda/notices/http.py", line 58, in get_channel_notice_response
        resp = session.get(url, allow_redirects=False, timeout=5)  # timeout: connect, read
      File "/opt/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 542, in get
        return self.request('GET', url, **kwargs)
      File "/opt/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 515, in request
        prep = self.prepare_request(req)
      File "/opt/miniconda3/lib/python3.8/site-packages/requests/sessions.py", line 443, in prepare_request
        p.prepare(
      File "/opt/miniconda3/lib/python3.8/site-packages/requests/models.py", line 318, in prepare
        self.prepare_url(url, params)
      File "/opt/miniconda3/lib/python3.8/site-packages/requests/models.py", line 392, in prepare_url
        raise MissingSchema(error)
    requests.exceptions.MissingSchema: Invalid URL 'notices.json': No scheme supplied. Perhaps you meant http://notices.json?

`$ /opt/miniconda3/bin/conda install --quiet company.h5-base>=3.0,<4.0 -c bioconda -c conda-forge -c s3://company-conda-channels/dev -c defaults`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/miniconda3/bin/conda
             CONDA_PREFIX=/opt/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/miniconda3/bin/python
               CONDA_ROOT=/opt/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/opt/miniconda3/bin:/opt/miniconda3/bin:/opt/miniconda3/condabin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             SUDO_COMMAND=/usr/bin/su
                 SUDO_GID=1001
                 SUDO_UID=1001
                SUDO_USER=ec2-user

     active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.12.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          s3://company-conda-channels/dev/linux-64
                          s3://copmany-conda-channels/dev/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.27.1 CPython/3.8.12 Linux/5.4.0-1048-aws ubuntu/20.04.2 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

</details>

Downgrading conda to v4.13.0 and running command again succeeds without error.

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : base
    active env location : /opt/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.12.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/miniconda3  (writable)
      conda av data dir : /opt/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.27.1 CPython/3.8.12 Linux/5.4.0-1048-aws ubuntu/20.04.2 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

</details>
<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /opt/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
boto3                     1.23.0             pyhd8ed1ab_0    conda-forge
botocore                  1.26.0             pyhd8ed1ab_0    conda-forge
bottleneck                1.3.2            py38h5c078b8_3    conda-forge
brotlipy                  0.7.0           py38h27cfd23_1003    defaults
ca-certificates           2022.6.15            ha878542_0    conda-forge
certifi                   2022.6.15        py38h578d9bd_0    conda-forge
cffi                      1.15.0           py38hd667e15_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.3            py38h578d9bd_0    conda-forge
conda                     4.14.0           py38h578d9bd_0    conda-forge
conda-package-handling    1.8.1            py38h7f8727e_0    defaults
cryptography              37.0.1           py38h9ce1e76_0    defaults
dataclasses               0.8                pyhc8e2a94_3    conda-forge
h5py                      2.10.0          nompi_py38h513d04c_102    conda-forge
hdf5                      1.10.5          nompi_h5b725eb_1114    conda-forge
idna                      3.3                pyhd3eb1b0_0    defaults
jmespath                  1.0.0              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_0    defaults
libblas                   3.9.0           11_linux64_openblas    conda-forge
libcblas                  3.9.0           11_linux64_openblas    conda-forge
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgfortran-ng            12.1.0              h69a702a_16    conda-forge
libgfortran5              12.1.0              hdcd56e2_16    conda-forge
libgomp                   9.3.0               h5101ec6_17    defaults
liblapack                 3.9.0           11_linux64_openblas    conda-forge
libopenblas               0.3.17          pthreads_h8fe5266_1    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
company.cli            1.1.0                      py_0    s3://company-conda-channels/dev
company.h5-base        3.5.0                      py_0    s3://company-conda-channels/dev
company.optimus_runner 7.3.0                      py_0    s3://company-conda-channels/stable
ncurses                   6.3                  h7f8727e_2    defaults
numexpr                   2.7.3            py38h51da96c_0    conda-forge
numpy                     1.21.1           py38h9894fe3_0    conda-forge
openssl                   1.1.1q               h7f8727e_0    defaults
pandas                    1.4.2            py38h295c915_0    defaults
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.3            py38h7b6447c_1    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.12               h12debd9_0    defaults
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2022.2.1           pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
ruamel_yaml               0.15.100         py38h27cfd23_0    defaults
s3transfer                0.5.2              pyhd8ed1ab_0    conda-forge
setuptools                61.2.0           py38h06a4308_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.3               hc218d9a_0    defaults
tk                        8.6.11               h1ccaba5_1    defaults
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.0           py38h06a4308_0    defaults
urllib3                   1.26.9           py38h06a4308_0    defaults
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h7f8727e_1    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.12               h7f8727e_2    defaults
```

</details>

**Comment by nejcskofic** [comment]
Trying to install package that is not hosted on S3 does not trigger this issue (eg. `conda install --quiet scipy -c bioconda -c conda-forge -c defaults`).

Setting  `CONDA_NUMBER_CHANNEL_NOTICES=0` helps as well, thank you.

**Comment by travishathaway** [comment]
Yes @jaimergp, this is related to notices. I have add a severity tag to this issue and promoted it as a "sprint candidate", so we can address this.

This was an oversight on our part because we did not test this with S3 channel sources.

**Comment by ForgottenProgramme** [comment]
Hey, @travishathaway! 
Does [this](https://github.com/conda/conda/pull/11852) PR also address this issue?

**Comment by milljm** [comment]
We have built a custom CondaSession adapter for our own RSA 2-factor authentication, which this also affects.
I can also confirm this PR solves our issue as well.

Thank you for the speedy incoming fix!

**Comment by aoguo64** [comment]
> 

I am facing the same error when my channel is mounted on s3:

`conda install -c s3://<redacted>/channel/ cloudpickle`

Even after setting the env var as suggested above, the error does not go way:
```
CONDA_NUMBER_CHANNEL_NOTICES=0
echo $CONDA_NUMBER_CHANNEL_NOTICES                                                                                                                                   
0
```

Any idea why this is still happening to S3 urls?
