### ISSUE TITLE
We would like to be able to use the 'conda run' command even if $CONDA_PREFIX is not writeable by the current user

### ISSUE THREAD

**Issue by sfweller** [conda/conda#11782]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

We would like to be able to use the `conda run` command even if $CONDA_PREFIX is not writeable by the current user (cf. error message with conda 4.10.3 below). It would be useful for using shebang lines like ` #!/usr/bin/env conda run -n my_env python` that can further be used in [job script files to SLURM](https://slurm.schedmd.com/sbatch.html#SECTION_EXAMPLES) workload manager (cf. example using RHSCLs below).

### Additional Context

Referring to point 4 here is an example error message from conda run, if the CONDA_PREFIX=/opt/rh/anaconda3/envs/ngsb is not writeable by the current user:

```
$ conda run --name ngsb python

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/rh/anaconda3/root/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/rh/anaconda3/root/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/rh/anaconda3/root/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/rh/anaconda3/root/lib/python3.6/site-packages/conda/cli/main_run.py", line 26, in execute
        [args.dev](http://args.dev/), args.debug_wrapper_scripts, call)
      File "/opt/rh/anaconda3/root/lib/python3.6/site-packages/conda/utils.py", line 403, in wrap_subprocess_call
        with Utf8NamedTemporaryFile(mode='w', prefix=tmp_prefix, delete=False) as fh:
      File "/opt/rh/anaconda3/root/lib/python3.6/site-packages/conda/_vendor/auxlib/compat.py", line 83, in Utf8NamedTemporaryFile
        dir=dir, delete=delete)
      File "/opt/rh/anaconda3/root/lib/python3.6/tempfile.py", line 551, in NamedTemporaryFile
        (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
      File "/opt/rh/anaconda3/root/lib/python3.6/tempfile.py", line 262, in _mkstemp_inner
        fd = _os.open(file, flags, 0o600)
    PermissionError: [Errno 13] Permission denied: '/opt/rh/anaconda3/envs/ngsb/.tmp0bttyidw'

`$ /opt/rh/anaconda3/root/bin/conda run --name ngsb python`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_EXE=/opt/rh/anaconda3/root/bin/conda
         CONDA_PYTHON_EXE=/opt/rh/anaconda3/root/bin/python
               CONDA_ROOT=/opt/rh/anaconda3/root
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
                     PATH=/opt/rh/anaconda3/root/bin:/opt/rh/anaconda3/root/condabin:/usr/lib64/
                          qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : None
            shell level : 0
       user config file : /home/i00202880/.condarc
populated config files : /opt/rh/anaconda3/root/.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.2=0
                          __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/rh/anaconda3/root  (read only)
      conda av data dir : /opt/rh/anaconda3/root/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/rh/anaconda3/root/pkgs
                          /home/i00202880/.conda/pkgs
       envs directories : /opt/rh/anaconda3/envs
                          /home/i00202880/.conda/envs
                          /opt/rh/anaconda3/root/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.23.0 CPython/3.6.8 Linux/3.10.0-957.21.3.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 507:507
             netrc file : None
           offline mode : False
 

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

Referring to point 4 here is an example of a SLURM job submission file, where the SLURM workload manager calls the correct Python interpreter from the correct Red Hat software collection based on the shebang line:

```
#!/usr/bin/scl enable ngsb -- python
#===========================================
#SBATCH --job-name=PySubExampleForMack
#===========================================
## Job dependecy
#SBATCH -d singleton
#===========================================
## Define output file name
#SBATCH --output=res_python_%j.txt
## #SBATCH -o %x.o%j
## #SBATCH -e %x.e%j
#===========================================
#SBATCH --ntasks=1
## #SBATCH --time=10:00
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=4
#SBATCH --time=10:00
#SBATCH --nodelist=node05
#SBATCH --chdir=/data/i00202880/slurmtest
##SBATCH -partition=cluster
#===========================================
# User inputs start here
#===========================================

# This script is a simple example for submitting a task to the
# E+H FL cluster using NGSB Python 2.7, which can conveniently be
# used to do some postprocessing already on the cluster nodes.
#
# To submit a job on the E+H FL cluster using this script do:
#
#     ssh ehf156 # or gocluster
#     sbatch submit_example.py
#
# Be sure to change SBATCH --chdir= to a proper working directory for you!
#
# To use Anaconda Python 3.6 instead of NGSB Python 2.7 replace
# the first line in this script with
#
#!/usr/bin/scl enable anaconda3 -- python

from __future__ import print_function

import sys
print(sys.version)

import socket
print(socket.gethostname())

import os
os.environ['OMP_NUM_THREADS'] = os.environ['SLURM_CPUS_PER_TASK']
os.environ['MKL_NUM_THREADS'] = os.environ['SLURM_CPUS_PER_TASK']

for var in os.environ:
    if 'SLURM' in var or 'OMP' in var or 'MKL' in var:
        print(var, os.environ[var])

SLURM_PROCID=os.environ['SLURM_PROCID']

import vtk
print(vtk.vtkVersion.GetVTKSourceVersion())

import paraview.servermanager
# paraview.servermanager.vtkSMProxyManager.GetVersionMajor()
# paraview.servermanager.vtkSMProxyManager.GetVersionMinor()
# paraview.servermanager.vtkSMProxyManager.GetVersionPatch()
print(paraview.servermanager.vtkSMProxyManager.GetParaViewSourceVersion())

from paraview.simple import *
print(GetParaViewVersion())
print(GetParaViewSourceVersion())

# Matplotlib offscreen rendering cf. https://stackoverflow.com/a/4935945
import matplotlib as mpl
mpl.use('Agg')
import matplotlib.pyplot as plt

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(range(10 * (int(SLURM_PROCID) + 1 )))
fig.savefig('temp_slurm_procid_{}.png'.format(SLURM_PROCID))

import time
print('Start : {}'.format(time.ctime()))
time.sleep( 35 )
print
```

**Comment by jaimergp** [comment]
There are substantial changes between 4.10.3 and 4.14.0 that improve how `conda run` works.

See [this diff](https://github.com/conda/conda/compare/4.10.3..4.14.0#diff-6fdb9b9eee632cceac767fc859a30efa7a295a81f950a83de486341cfc27e3ecR21-L26), where you can see that now `wrap_subprocess_call` uses `use_system_tmp_path=True`, which does not rely on PREFIX being writable.

I would update to the latest conda and see if it fixes your problem. If that's not the case, please update the traceback logs with the new version so we can take a look!
