### ISSUE TITLE
json problem when updating to ipython 3.0

### ISSUE THREAD

**Issue by TRiedling** [conda/conda#1178]
I updated ipython. Now I get an json error when starting the notebook. 
I'm running anaconda under ubuntu 14.04 with python 3.4 and conda 3.9.1

Here is the text of the consol:
The following packages will be UPDATED:

    ipython:    2.2.0-py34_0 --> 3.0.0-py34_0
    pip:        1.5.6-py34_0 --> 6.0.8-py34_0
    setuptools: 5.8-py34_0   --> 12.3-py34_0 

Proceed ([y]/n)? y

Fetching packages ...
ipython-3.0.0- 100% |#####################################################| Time: 0:00:01   2.21 MB/s
setuptools-12. 100% |#####################################################| Time: 0:00:00 545.89 kB/s
pip-6.0.8-py34 100% |#####################################################| Time: 0:00:02 661.63 kB/s
Extracting packages ...
[      COMPLETE      ] |#######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#######################################################################| 100%
Linking packages ...
[      COMPLETE      ] |#######################################################################| 100%
triedling@einStein:~$ ipython notebook
Traceback (most recent call last):
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/nbformat/validator.py", line 10, in <module>
    from jsonschema import ValidationError
ImportError: No module named 'jsonschema'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/triedling/anaconda3/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/__init__.py", line 120, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 573, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 321, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<string>", line 2, in initialize
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/core/application.py", line 369, in initialize
    self.parse_command_line(argv)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/terminal/ipapp.py", line 316, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<string>", line 2, in parse_command_line
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 471, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<string>", line 2, in initialize_subcommand
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/config/application.py", line 402, in initialize_subcommand
    subapp = import_item(subapp)
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/utils/importstring.py", line 42, in import_item
    module = __import__(package, fromlist=[obj])
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/html/notebookapp.py", line 63, in <module>
    from .services.contents.manager import ContentsManager
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/html/services/contents/manager.py", line 16, in <module>
    from IPython.nbformat import sign, validate, ValidationError
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/nbformat/__init__.py", line 29, in <module>
    from .validator import validate, ValidationError
  File "/home/triedling/anaconda3/lib/python3.4/site-packages/IPython/nbformat/validator.py", line 21, in <module>
    raise ImportError(str(e) + verbose_msg)
ImportError: No module named 'jsonschema'

    IPython notebook format depends on the jsonschema package:
    
        https://pypi.python.org/pypi/jsonschema
    
    Please install it first.

**Comment by asmeurer** [comment]
The latest version of the `ipython-notebook` metapackage depends on jsonschema.

**Comment by TRiedling** [comment]
Thank you!
