### ISSUE TITLE
Cannot create a environment

### ISSUE THREAD

**Issue by Daniel-Jiang358** [conda/conda#11798]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Traceback (most recent call last):
  File "/root/autodl-tmp/jyq/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/site-packages/conda/cli/main.py", line 115, in main
    args.func(args, p)
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/site-packages/conda/cli/main_create.py", line 57, in execute
    conda = Anaconda()
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/site-packages/conda/anaconda.py", line 43, in __init__
    self._index = PackageIndex(fetch_index(self.channel_urls))
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/site-packages/conda/remote.py", line 46, in fetch_index
    repodata = fetch_repodata(url)
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/site-packages/conda/remote.py", line 29, in fetch_repodata
    fi = urllib2.urlopen(url + fn)
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/urllib2.py", line 392, in open
    protocol = req.get_type()
  File "/root/autodl-tmp/jyq/anaconda3/lib/python2.7/urllib2.py", line 254, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: defaults/linux-64/repodata.json.bz2

### Conda Info

```shell
Current conda install:

             platform : linux-64
conda command version : 1.4.4
       root directory : /root/autodl-tmp/jyq/anaconda3
       default prefix : /root/autodl-tmp/jyq/anaconda3
         channel URLs : https://mirrors.ustc.edu.cn/anaconda/pkgs/main/linux-64/
                        https://mirrors.ustc.edu.cn/anaconda/pkgs/free/linux-64/
                        defaults/linux-64/
environment locations : /root/autodl-tmp/jyq/anaconda3/envs
          config file : /root/.condarc
```

### Conda Config

```shell
usage: conda [-h] [-v] command ...
conda: error: 'config' is not a conda command, see 'conda -h'
```

### Conda list

```shell
conda: error: unrecognized arguments: --show-channel-urls
```

### Additional Context

I don't understand why config command is illegal

**Comment by travishathaway** [comment]
It appears that you are using an older unsupported version of `conda`. Please update your conda version to the latest (`4.14`)
