### ISSUE TITLE
Conda Python 3.7.13 installations fail with codesign on macOS

### ISSUE THREAD

**Issue by dheerajramchandani** [conda/conda#11808]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have `miniconda` installed using `brew` and have multiple environments. Most of them are py3.7 and one of them is py3.6. I am facing following issue in Python 3.7 environments:

```
Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/envs/env-name/lib/python3.7/site-packages/keyring/backends/macOS/__init__.py", line 52, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/usr/local/Caskroom/miniconda/base/envs/env-name/lib/python3.7/site-packages/keyring/backends/macOS/api.py", line 144, in find_generic_password
    Error.raise_for_status(status)
  File "/usr/local/Caskroom/miniconda/base/envs/env-name/lib/python3.7/site-packages/keyring/backends/macOS/api.py", line 111, in raise_for_status
    "Security Auth Failure: make sure "
keyring.backends.macOS.api.SecAuthFailure: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
```

Also. find following:

```
(env-name) pwd % codesign -v /usr/local/Caskroom/miniconda/base/envs/env-name/bin/python 
/usr/local/Caskroom/miniconda/base/envs/env-name/bin/python: invalid signature (code or signature have been modified)
In architecture: x86_64
(env-name) pwd %
```

It seems to me that `conda env create -n env-name python=3.7` installs a python binary that is not codesigned. Could you please help me overcome this issue?

### Conda Info

```shell
active environment : env-name
    active env location : /usr/local/Caskroom/miniconda/base/envs/env-name
            shell level : 2
       user config file : /Users/dheerajramchandani/.condarc
 populated config files : /Users/dheerajramchandani/.condarc
          conda version : 4.12.0
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/Caskroom/miniconda/base  (writable)
      conda av data dir : /usr/local/Caskroom/miniconda/base/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/Caskroom/miniconda/base/pkgs
                          /Users/dheerajramchandani/.conda/pkgs
       envs directories : /usr/local/Caskroom/miniconda/base/envs
                          /Users/dheerajramchandani/.conda/envs
               platform : osx-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.7 Darwin/21.6.0 OSX/10.16
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/dheerajramchandani/.condarc <==
ssl_verify: False
proxy_servers:
  http: http://corporate.proxy.url:8080
  https: http://corporate.proxy.url:8080
channel_priority: disabled
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at /usr/local/Caskroom/miniconda/base/envs/env-name:
#
# Name                    Version                   Build  Channel
ca-certificates           2022.07.19           hecd8cb5_0    defaults
libcxx                    14.0.6               hccf4f1f_0    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libsqlite                 3.39.3               ha978bb4_0    conda-forge
libzlib                   1.2.12               hfe4f2af_2    conda-forge
ncurses                   6.3                  h96cf925_1    conda-forge
openssl                   1.1.1q               hfe4f2af_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
python                    3.7.13               hdfd78df_0    defaults
python_abi                3.7                     2_cp37m    conda-forge
readline                  8.1.2                h3899abd_0    conda-forge
setuptools                65.3.0           py37hf985489_0    conda-forge
sqlite                    3.39.3               h9ae0607_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h775f41a_0    conda-forge
zlib                      1.2.12               hfe4f2af_2    conda-forge
```

**Comment by travishathaway** [comment]
Hi @dheerajramchandani,

Thank you for this submission. I am going to close this issue as it is not relevant to this particular conda project.

My advice for you would be to figure out how to disable this check. Alternatively, you may wish to install Miniconda via one of the installers available here: https://docs.conda.io/en/latest/miniconda.html
