### ISSUE TITLE
errors in removing enviroments

### ISSUE THREAD

**Issue by yoyohashao** [conda/conda#1181]
Dear admin, I execute the same command 20min ago and it was fine. But later i recreate concoct_env and when I tried to re-remove it... error occured... What should I do? Thanks

SEBASTIANs-MacBook-Pro:CONCOCT-0.4.0 FLFLFLLF$ conda remove --all -n concoct_env
Fetching package metadata: ....

Package plan for package removal in environment //anaconda/envs/concoct_env:

The following packages will be REMOVED:

    biopython:    1.65-np19py27_0  
    cython:       0.22-py27_0      
    dateutil:     2.1-py27_2       
    nose:         1.3.4-py27_0     
    numpy:        1.9.2-py27_0     
    openssl:      1.0.1k-0         
    pandas:       0.15.2-np19py27_0
    pip:          6.0.8-py27_0     
    python:       2.7.9-1          
    pytz:         2014.9-py27_0    
    readline:     6.2-2            
    scikit-learn: 0.15.2-np19py27_0
    scipy:        0.15.1-np19py27_0
    setuptools:   12.4-py27_0      
    six:          1.9.0-py27_0     
    sqlite:       3.8.4.1-0        
    tk:           8.5.15-0         
    zlib:         1.2.8-0          

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ] |##################################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_remove.py", line 192, in execute
    rm_rf(prefix)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 179, in rm_rf
    shutil.rmtree(path)
  File "//anaconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "//anaconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "//anaconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "//anaconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "//anaconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "//anaconda/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "//anaconda/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '//anaconda/envs/concoct_env/lib/python2.7/site-packages/alabaster-0.7.1-py2.7.egg/alabaster/__init__.py'

**Comment by asmeurer** [comment]
Did you create the environment with sudo? If so, you'll have to remove it with sudo.

**Comment by ilanschnell** [comment]
Basically `conda remove --all`, does a more systematic `rm -rf <prefix>`.  There is no information stored about the environment places other than the environment prefix itself.
