### ISSUE TITLE
'conda env export' produces error: "InvalidVersionSpec: Invalid version '>=': invalid operator"

### ISSUE THREAD

**Issue by 60south** [conda/conda#11828]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Environment export fails with command 'conda env export', produces error "InvalidVersionSpec: Invalid version '>=': invalid operator"

Other similar bug reports have been closed or I have been unable to implement the work-arounds mentioned, e.g. searching for '>=' in setup.py or the package metadata produces hundreds of results, making fixes impossible (https://github.com/conda/conda/issues/9624).

Using verbose mode shows where the error is occurring:

```
(wxs) $ conda env export -v
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/version.py", line 41, in __call__
    return cls._cache_[arg]
KeyError: '>='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1125, in __call__
    return func(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 80, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda_env/cli/main_export.py", line 87, in execute
    from_history=args.from_history,
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda_env/env.py", line 109, in from_environment
    precs = tuple(PrefixGraph(pd.iter_records()).graph)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/prefix_graph.py", line 39, in __init__
    parent_match_specs = tuple(MatchSpec(d) for d in node.depends)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/prefix_graph.py", line 39, in <genexpr>
    parent_match_specs = tuple(MatchSpec(d) for d in node.depends)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 52, in __call__
    return super(MatchSpecType, cls).__call__(**parsed)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 173, in __init__
    self._match_components = self._build_components(**kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 399, in _build_components
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/_vendor/frozendict/__init__.py", line 21, in __init__
    self._dict = self.dict_cls(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 399, in <genexpr>
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/match_spec.py", line 413, in _make_component
    matcher = _implementors[field_name](value)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/version.py", line 43, in __call__
    val = cls._cache_[arg] = super(SingleStrArgCachingType, cls).__call__(arg)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/version.py", line 498, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/conda/models/version.py", line 527, in get_matcher
    raise InvalidVersionSpec(vspec_str, "invalid operator")
conda.exceptions.InvalidVersionSpec: Invalid version '>=': invalid operator
```

### Conda Info

```shell
active environment : wxs
    active env location : /home/ops/.conda/envs/wxs
            shell level : 2
       user config file : /home/ops/.condarc
 populated config files :
          conda version : 4.14.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __linux=4.15.0=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/anaconda3  (read only)
      conda av data dir : /usr/local/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /home/ops/.conda/pkgs
       envs directories : /home/ops/.conda/envs
                          /usr/local/anaconda3/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.22.0 CPython/3.7.6 Linux/4.15.0-166-generic ubuntu/18.04.6 glibc/2.27
                UID:GID : 1007:1008
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
[nothing]
```

### Conda list

```shell
# packages in environment at /home/ops/.conda/envs/wxs:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             4.5                       1_gnu    defaults
_tflow_select             2.1.0                       gpu    defaults
absl-py                   1.2.0                    pypi_0    pypi
affine                    2.3.0                    pypi_0    pypi
aiohttp                   3.8.1            py39h7f8727e_0    defaults
aiosignal                 1.2.0              pyhd3eb1b0_0    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
arrow                     0.13.1           py39h06a4308_0    defaults
astor                     0.8.1            py39h06a4308_0    defaults
astroid                   2.6.6            py39h06a4308_0    defaults
astunparse                1.6.3                      py_0    defaults
async-timeout             4.0.1              pyhd3eb1b0_0    defaults
async_generator           1.10               pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     21.2.0             pyhd3eb1b0_0    defaults
autopep8                  1.6.0              pyhd3eb1b0_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
bcrypt                    3.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
binaryornot               0.4.4              pyhd3eb1b0_1    defaults
bitstring                 3.1.9                    pypi_0    pypi
black                     19.10b0                    py_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.0.0              pyhd3eb1b0_0    defaults
blinker                   1.4              py39h06a4308_0    defaults
bottleneck                1.3.2            py39hdd57654_1    defaults
brotli                    1.0.9                he6710b0_2    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h27cfd23_0    defaults
ca-certificates           2022.4.26            h06a4308_0    defaults
cachetools                4.2.2              pyhd3eb1b0_0    defaults
cartopy                   0.19.0.post1             pypi_0    pypi
certifi                   2021.10.8        py39h06a4308_2    defaults
cffi                      1.14.6           py39h400218f_0    defaults
cfgrib                    0.9.8.5            pyhd8ed1ab_0    conda-forge
cftime                    1.6.0                    pypi_0    pypi
chardet                   4.0.0           py39h06a4308_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
chromalog                 1.0.5                    pypi_0    pypi
click                     8.0.3              pyhd3eb1b0_0    defaults
click-plugins             1.1.1                    pypi_0    pypi
cligj                     0.7.2                    pypi_0    pypi
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
colorama                  0.4.4              pyhd3eb1b0_0    defaults
configobj                 5.0.6                    pypi_0    pypi
cookiecutter              1.7.2              pyhd3eb1b0_0    defaults
cryptography              3.4.8            py39hd23ed53_0    defaults
cudatoolkit               10.1.243             h6bb024c_0    defaults
cudnn                     7.6.5                cuda10.1_0    defaults
cupti                     10.1.168                      0    defaults
curl                      7.78.0               hea6ffbf_0    conda-forge
cycler                    0.11.0             pyhd3eb1b0_0    defaults
cython                    0.29.25          py39hdbfa776_0    defaults
dask                      2022.5.0                 pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7    defaults
dbus                      1.13.18              hb2f20db_0    defaults
debugpy                   1.5.1            py39h295c915_0    defaults
decorator                 5.1.0              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
docopt                    0.6.2                    pypi_0    pypi
docutils                  0.17.1           py39h06a4308_1    defaults
eccodes                   2.19.1               hea64003_0    conda-forge
entrypoints               0.3              py39h06a4308_0    defaults
expat                     2.4.1                h2531618_2    defaults
f90nml                    1.4.2                    pypi_0    pypi
fiona                     1.8.21                   pypi_0    pypi
flake8                    3.9.2              pyhd3eb1b0_0    defaults
flatbuffers               1.12                     pypi_0    pypi
fontconfig                2.13.1               h6c09931_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.11.0               h70c0345_0    defaults
frozenlist                1.2.0            py39h7f8727e_0    defaults
fsspec                    2022.3.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.4.0              pyhd3eb1b0_0    defaults
geographiclib             1.52                     pypi_0    pypi
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.10.2                   pypi_0    pypi
geopy                     2.2.0                    pypi_0    pypi
geos                      3.8.0                he6710b0_0    defaults
giflib                    5.2.1                h7b6447c_0    defaults
glib                      2.69.1               h5202010_0    defaults
google-auth               1.33.0             pyhd3eb1b0_0    defaults
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0    defaults
google-pasta              0.2.0              pyhd3eb1b0_0    defaults
grpcio                    1.42.0           py39hce63b2e_0    defaults
gst-plugins-base          1.14.0               h8213a91_2    defaults
gstreamer                 1.14.0               h28cd5cc_2    defaults
h5py                      3.7.0                    pypi_0    pypi
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.10.6          nompi_h7c3c948_1111    conda-forge
icu                       58.2                 he6710b0_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
imagesize                 1.3.0              pyhd3eb1b0_0    defaults
importlib-metadata        4.8.2            py39h06a4308_0    defaults
importlib_metadata        4.8.2                hd3eb1b0_0    defaults
inflection                0.5.1            py39h06a4308_0    defaults
intel-openmp              2021.4.0          h06a4308_3561    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.4.1            py39h06a4308_1    defaults
ipython                   7.29.0           py39hb070fc8_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jedi                      0.18.0           py39h06a4308_1    defaults
jeepney                   0.7.1              pyhd3eb1b0_0    defaults
jinja2                    2.11.3             pyhd3eb1b0_0    defaults
jinja2-time               0.2.0              pyhd3eb1b0_2    defaults
joblib                    1.1.0              pyhd3eb1b0_0    defaults
jpeg                      9d                   h7f8727e_0    defaults
jsonschema                3.2.0              pyhd3eb1b0_2    defaults
jupyter_client            6.1.12             pyhd3eb1b0_0    defaults
jupyter_core              4.9.1            py39h06a4308_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
keras                     2.9.0                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd3eb1b0_0    defaults
keyring                   23.4.0           py39h06a4308_0    defaults
kiwisolver                1.3.1            py39h2531618_0    defaults
krb5                      1.19.2               hac12032_0    defaults
l2ml                      0.2                      pypi_0    pypi
lazy-object-proxy         1.6.0            py39h27cfd23_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libaec                    1.0.5                h9c3ff4c_0    conda-forge
libclang                  14.0.6                   pypi_0    pypi
libcurl                   7.78.0               h2574ce0_0    conda-forge
libedit                   3.1.20210910         h7f8727e_0    defaults
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 9.3.0               h5101ec6_17    defaults
libgfortran-ng            7.5.0               ha8ba4b0_17    defaults
libgfortran4              7.5.0               ha8ba4b0_17    defaults
libgomp                   9.3.0               h5101ec6_17    defaults
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libpng                    1.6.37               hbc83047_0    defaults
libpq                     12.9                 hc2c5182_1    defaults
libprotobuf               3.19.1               h4ff587b_0    defaults
libsodium                 1.0.18               h7b6447c_0    defaults
libspatialindex           1.9.3                h2531618_0    defaults
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               hd4cf53a_17    defaults
libtiff                   4.2.0                h85742a9_0    defaults
libuuid                   1.0.3                h7f8727e_2    defaults
libwebp                   1.2.0                h89dd481_0    defaults
libwebp-base              1.2.0                h27cfd23_0    defaults
libxcb                    1.14                 h7b6447c_0    defaults
libxml2                   2.9.12               h03d6c58_0    defaults
locket                    1.0.0                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1    defaults
markdown                  3.3.4            py39h06a4308_0    defaults
markupsafe                1.1.1            py39h27cfd23_0    defaults
matplotlib                3.5.0            py39h06a4308_0    defaults
matplotlib-base           3.5.0            py39h3ed280b_0    defaults
matplotlib-inline         0.1.2              pyhd3eb1b0_2    defaults
mccabe                    0.6.1            py39h06a4308_1    defaults
mistune                   0.8.4           py39h27cfd23_1000    defaults
mkl                       2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0            py39h7f8727e_0    defaults
mkl_fft                   1.3.1            py39hd3c417c_0    defaults
mkl_random                1.2.2            py39h51133e4_0    defaults
multidict                 5.2.0            py39h7f8727e_2    defaults
munch                     2.5.0                    pypi_0    pypi
munkres                   1.1.4                      py_0    defaults
mypy_extensions           0.4.3            py39h06a4308_1    defaults
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.3.0            py39h06a4308_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
ncurses                   6.3                  h7f8727e_2    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
netcdf4                   1.5.8                    pypi_0    pypi
numexpr                   2.8.1            py39h6abb31d_0    defaults
numpy                     1.21.0                   pypi_0    pypi
numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
oauthlib                  3.1.1              pyhd3eb1b0_0    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
openssl                   1.1.1m               h7f8727e_0    defaults
opt_einsum                3.3.0              pyhd3eb1b0_1    defaults
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.3.5            py39h8c16a72_0    defaults
pandocfilters             1.4.3            py39h06a4308_1    defaults
paramiko                  2.9.2                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    defaults
partd                     1.2.0                    pypi_0    pypi
pathspec                  0.7.0                      py_0    conda-forge
pcre                      8.45                 h295c915_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.4.0            py39h5aabda8_0    defaults
pip                       21.2.4           py39h06a4308_0    defaults
pluggy                    1.0.0            py39h06a4308_0    defaults
poyo                      0.5.0              pyhd3eb1b0_0    defaults
proj                      6.2.1                haa6030c_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
protobuf                  3.19.1           py39h295c915_0    defaults
psutil                    5.8.0            py39h27cfd23_1    defaults
psycopg2                  2.8.6            py39h3c74f83_1    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pyasn1                    0.4.8              pyhd3eb1b0_0    defaults
pyasn1-modules            0.2.8                      py_0    defaults
pybind11                  2.8.0                    pypi_0    pypi
pycodestyle               2.7.0              pyhd3eb1b0_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pydap                     3.2.2                    pypi_0    pypi
pydocstyle                6.1.1              pyhd3eb1b0_0    defaults
pyflakes                  2.3.1              pyhd3eb1b0_0    defaults
pygments                  2.10.0             pyhd3eb1b0_0    defaults
pyjwt                     2.1.0            py39h06a4308_0    defaults
pykdtree                  1.3.4                    pypi_0    pypi
pylint                    2.9.6            py39h06a4308_1    defaults
pyls-spyder               0.4.0              pyhd3eb1b0_0    defaults
pymongo                   4.0.2                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyopenssl                 21.0.0             pyhd3eb1b0_1    defaults
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyproj                    2.6.1.post1      py39hb3025e9_1    defaults
pyqt                      5.9.2            py39h2531618_6    defaults
pyresample                1.21.0                   pypi_0    pypi
pyrsistent                0.18.0           py39heee7806_0    defaults
pysftp                    0.2.9                    pypi_0    pypi
pyshp                     2.1.3              pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.7                h12debd9_1    defaults
python-crontab            2.6.0                    pypi_0    pypi
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-lsp-black          1.0.0              pyhd3eb1b0_0    defaults
python-lsp-jsonrpc        1.0.0              pyhd3eb1b0_0    defaults
python-lsp-server         1.2.4              pyhd3eb1b0_0    defaults
python-slugify            5.0.2              pyhd3eb1b0_0    defaults
pytz                      2021.3             pyhd3eb1b0_0    defaults
pyxdg                     0.27               pyhd3eb1b0_0    defaults
pyyaml                    6.0              py39h7f8727e_1    defaults
pyzmq                     22.3.0           py39h295c915_2    defaults
qdarkstyle                3.0.2              pyhd3eb1b0_0    defaults
qstylizer                 0.1.10             pyhd3eb1b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtawesome                 1.0.3              pyhd3eb1b0_0    defaults
qtconsole                 5.1.1              pyhd3eb1b0_0    defaults
qtpy                      1.10.0             pyhd3eb1b0_0    defaults
rasterio                  1.2.10                   pypi_0    pypi
readline                  8.1                  h27cfd23_0    defaults
regex                     2021.8.3         py39h7f8727e_0    defaults
requests                  2.26.0             pyhd3eb1b0_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
rope                      0.21.1             pyhd3eb1b0_0    defaults
rsa                       4.7.2              pyhd3eb1b0_1    defaults
rtree                     0.9.7            py39h06a4308_1    defaults
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
seaborn                   0.11.2             pyhd3eb1b0_0    defaults
secretstorage             3.3.1            py39h06a4308_0    defaults
setuptools                58.0.4           py39h06a4308_0    defaults
setuptools-scm            6.3.2                    pypi_0    pypi
shapely                   1.7.1            py39h1728cc4_0    defaults
sip                       4.19.13          py39h2531618_0    defaults
six                       1.16.0             pyhd3eb1b0_0    defaults
snowballstemmer           2.2.0              pyhd3eb1b0_0    defaults
snuggs                    1.4.7                    pypi_0    pypi
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.3.2.post1              pypi_0    pypi
sphinx                    4.2.0              pyhd3eb1b0_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
spiceypy                  4.0.0                    pypi_0    pypi
spyder                    5.1.5            py39h06a4308_1    defaults
spyder-kernels            2.1.3            py39h06a4308_0    defaults
sqlite                    3.37.0               hc218d9a_0    defaults
tensorboard               2.9.1                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.9.1                    pypi_0    pypi
tensorflow-estimator      2.9.0                    pypi_0    pypi
tensorflow-gpu            2.4.1                h30adc30_0    defaults
tensorflow-io-gcs-filesystem 0.26.0                   pypi_0    pypi
termcolor                 1.1.0            py39h06a4308_1    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
text-unidecode            1.3                pyhd3eb1b0_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
threadpoolctl             2.2.0              pyh0d69192_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tinycss                   0.4             pyhd3eb1b0_1002    defaults
tk                        8.6.11               h1ccaba5_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
tornado                   6.1              py39h27cfd23_0    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
twilio                    7.7.0                    pypi_0    pypi
typed-ast                 1.4.3            py39h7f8727e_1    defaults
typing-extensions         3.10.0.2             hd3eb1b0_0    defaults
typing_extensions         3.10.0.2           pyh06a4308_0    defaults
tzdata                    2021e                hda174b7_0    defaults
ujson                     4.2.0            py39h295c915_0    defaults
unidecode                 1.2.0              pyhd3eb1b0_0    defaults
urllib3                   1.26.7             pyhd3eb1b0_0    defaults
watchdog                  2.1.6            py39h06a4308_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1            py39h06a4308_1    defaults
webob                     1.8.7                    pypi_0    pypi
werkzeug                  2.0.2              pyhd3eb1b0_0    defaults
wheel                     0.37.0             pyhd3eb1b0_1    defaults
whichcraft                0.6.1              pyhd3eb1b0_0    defaults
wrapt                     1.12.1           py39he8ac12f_1    defaults
wurlitzer                 3.0.2            py39h06a4308_0    defaults
xarray                    2022.3.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
yarl                      1.6.3            py39h27cfd23_0    defaults
zeromq                    4.3.4                h2531618_0    defaults
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               h7f8727e_4    defaults
zstd                      1.4.9                haebb681_0    defaults
```

### Additional Context

pip list works:

(wxs) $ pip list
Package                       Version
----------------------------- ------------
absl-py                       1.2.0
affine                        2.3.0
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
appdirs                       1.4.4
arrow                         0.13.1
astor                         0.8.1
astroid                       2.6.6
astunparse                    1.6.3
async-generator               1.10
async-timeout                 4.0.1
atomicwrites                  1.4.0
attrs                         21.2.0
autopep8                      1.6.0
Babel                         2.9.1
backcall                      0.2.0
bcrypt                        3.2.0
beautifulsoup4                4.11.1
binaryornot                   0.4.4
bitstring                     3.1.9
black                         19.10b0
bleach                        4.0.0
blinker                       1.4
Bottleneck                    1.3.2
brotlipy                      0.7.0
cachetools                    4.2.2
Cartopy                       0.19.0.post1
certifi                       2021.10.8
cffi                          1.14.6
cfgrib                        0.9.8.5
cftime                        1.6.0
chardet                       4.0.0
charset-normalizer            2.0.4
chromalog                     1.0.5
click                         8.0.3
click-plugins                 1.1.1
cligj                         0.7.2
cloudpickle                   2.0.0
colorama                      0.4.4
configobj                     5.0.6
cookiecutter                  1.7.2
cryptography                  3.4.8
cycler                        0.11.0
Cython                        0.29.25
dask                          2022.5.0
debugpy                       1.5.1
decorator                     5.1.0
defusedxml                    0.7.1
diff-match-patch              20200713
docopt                        0.6.2
docutils                      0.17.1
entrypoints                   0.3
f90nml                        1.4.2
Fiona                         1.8.21
flake8                        3.9.2
flatbuffers                   1.12
fonttools                     4.25.0
frozenlist                    1.2.0
fsspec                        2022.3.0
future                        0.18.2
gast                          0.4.0
geographiclib                 1.52
geojson                       2.5.0
geopandas                     0.10.2
geopy                         2.2.0
google-auth                   1.33.0
google-auth-oauthlib          0.4.4
google-pasta                  0.2.0
grpcio                        1.42.0
h5py                          3.7.0
idna                          3.3
imagesize                     1.3.0
importlib-metadata            4.8.2
inflection                    0.5.1
intervaltree                  3.1.0
ipykernel                     6.4.1
ipython                       7.29.0
ipython-genutils              0.2.0
isort                         5.9.3
jedi                          0.18.0
jeepney                       0.7.1
Jinja2                        2.11.3
jinja2-time                   0.2.0
joblib                        1.1.0
jsonschema                    3.2.0
jupyter-client                6.1.12
jupyter-core                  4.9.1
jupyterlab-pygments           0.1.2
keras                         2.9.0
Keras-Preprocessing           1.1.2
keyring                       23.4.0
kiwisolver                    1.3.1
l2ml                          0.2
lazy-object-proxy             1.6.0
libclang                      14.0.6
locket                        1.0.0
Markdown                      3.3.4
MarkupSafe                    1.1.1
matplotlib                    3.5.0
matplotlib-inline             0.1.2
mccabe                        0.6.1
mistune                       0.8.4
mkl-fft                       1.3.1
mkl-random                    1.2.2
mkl-service                   2.4.0
multidict                     5.2.0
munch                         2.5.0
munkres                       1.1.4
mypy-extensions               0.4.3
nbclient                      0.5.3
nbconvert                     6.3.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
netCDF4                       1.5.8
numexpr                       2.8.1
numpy                         1.21.0
numpydoc                      1.1.0
oauthlib                      3.1.1
olefile                       0.46
opt-einsum                    3.3.0
packaging                     21.3
pandas                        1.3.5
pandocfilters                 1.4.3
paramiko                      2.9.2
parso                         0.8.3
partd                         1.2.0
pathspec                      0.7.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.4.0
pip                           21.2.4
pluggy                        1.0.0
poyo                          0.5.0
prompt-toolkit                3.0.20
protobuf                      3.19.1
psutil                        5.8.0
psycopg2                      2.8.6
ptyprocess                    0.7.0
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pybind11                      2.8.0
pycodestyle                   2.7.0
pycparser                     2.21
Pydap                         3.2.2
pydocstyle                    6.1.1
pyflakes                      2.3.1
Pygments                      2.10.0
PyJWT                         2.1.0
pykdtree                      1.3.4
pylint                        2.9.6
pyls-spyder                   0.4.0
pymongo                       4.0.2
PyNaCl                        1.5.0
pyOpenSSL                     21.0.0
pyparsing                     3.0.4
pyproj                        2.6.1.post1
pyresample                    1.21.0
pyrsistent                    0.18.0
pysftp                        0.2.9
pyshp                         2.1.3
PySocks                       1.7.1
python-crontab                2.6.0
python-dateutil               2.8.2
python-lsp-black              1.0.0
python-lsp-jsonrpc            1.0.0
python-lsp-server             1.2.4
python-slugify                5.0.2
pytz                          2021.3
pyxdg                         0.27
PyYAML                        6.0
pyzmq                         22.3.0
QDarkStyle                    3.0.2
qstylizer                     0.1.10
QtAwesome                     1.0.3
qtconsole                     5.1.1
QtPy                          1.10.0
rasterio                      1.2.10
regex                         2021.8.3
requests                      2.26.0
requests-oauthlib             1.3.0
rope                          0.21.1
rsa                           4.7.2
Rtree                         0.9.7
scikit-learn                  1.0.2
scipy                         1.7.1
seaborn                       0.11.2
SecretStorage                 3.3.1
setuptools                    58.0.4
setuptools-scm                6.3.2
Shapely                       1.7.1
sip                           4.19.13
six                           1.16.0
snowballstemmer               2.2.0
snuggs                        1.4.7
sortedcontainers              2.4.0
soupsieve                     2.3.2.post1
Sphinx                        4.2.0
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
spiceypy                      4.0.0
spyder                        5.1.5
spyder-kernels                2.1.3
tensorboard                   2.9.1
tensorboard-data-server       0.6.1
tensorboard-plugin-wit        1.8.1
tensorflow                    2.9.1
tensorflow-estimator          2.9.0
tensorflow-io-gcs-filesystem  0.26.0
termcolor                     1.1.0
testpath                      0.5.0
text-unidecode                1.3
textdistance                  4.2.1
threadpoolctl                 2.2.0
three-merge                   0.1.1
tinycss                       0.4
toml                          0.10.2
tomli                         2.0.1
toolz                         0.11.2
tornado                       6.1
traitlets                     5.1.1
twilio                        7.7.0
typed-ast                     1.4.3
typing-extensions             3.10.0.2
ujson                         4.2.0
Unidecode                     1.2.0
urllib3                       1.26.7
watchdog                      2.1.6
wcwidth                       0.2.5
webencodings                  0.5.1
WebOb                         1.8.7
Werkzeug                      2.0.2
wheel                         0.37.0
whichcraft                    0.6.1
wrapt                         1.12.1
wurlitzer                     3.0.2
xarray                        2022.3.0
yapf                          0.31.0
yarl                          1.6.3
zipp                          3.6.0

**Comment by travishathaway** [comment]
Hi @60south,

Thank you for filing this issue. I will be closing this issue as a duplicate to help us keep our issue back log more organized. I will be referencing this issue in the issue you mentioned:

- https://github.com/conda/conda/issues/9624

Please follow this issue or add to the discussion there so we have more information on it.
