### ISSUE TITLE
conda rename: `unexpected error has occurred - TypeError: expected str, bytes or os.PathLike object, not NoneType`

### ISSUE THREAD

**Issue by thesofakillers** [conda/conda#11850]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to use the new `conda rename` functionality to rename an environment `foo` to `bar`. I run:

`conda deactivate`

and then

`conda rename -n foo -d bar`

I get the following error:

<details>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
 
    Traceback (most recent call last):
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1125, in __call__
        return func(*args, **kwargs)
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/cli/main_rename.py", line 53, in execute
        source = validate_src(args.name, args.prefix)
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/cli/main_rename.py", line 28, in validate_src
        if common.is_active_prefix(prefix):
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/cli/common.py", line 87, in is_active_prefix
        paths_equal(prefix, context.active_prefix)
      File "/Users/thesofakillers/miniconda3/lib/python3.8/site-packages/conda/common/path.py", line 53, in paths_equal
        return abspath(path1) == abspath(path2)
      File "/Users/thesofakillers/miniconda3/lib/python3.8/posixpath.py", line 374, in abspath
        path = os.fspath(path)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
 
`$ /Users/thesofakillers/miniconda3/bin/conda rename -p /Users/thesofakillers/miniconda3/envs/xlaicl claficle`
 
  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/thesofakillers/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/Users/thesofakillers/miniconda3/bin/python
               CONDA_ROOT=/Users/thesofakillers/miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/thesofakillers/miniconda3/bin:/usr/local/bin:/usr/local/sbin:/L
                          ibrary/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin:/Users/t
                          hesofakillers/.nvm/versions/node/v16.13.1/bin:/Users/thesofakillers/.p
                          oetry/bin:/Users/thesofakillers/miniconda3/bin:/Users/thesofakillers/.
                          rbenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/                                                                                                    
                          texbin:/usr/local/sbin:/Library/TeX/Distributions/.DefaultTeX/Contents
                          /Programs/texbin:/Users/thesofakillers/.nvm/versions/node/v16.13.1/bin
                          :/Users/thesofakillers/.poetry/bin:/Users/thesofakillers/miniconda3/co
                          ndabin:/Users/thesofakillers/miniconda3/bin:/Users/thesofakillers/.rbe
                          nv/shims:/Users/thesofakillers/.scripts:/Users/thesofakillers/.scripts
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
 TMUX_PLUGIN_MANAGER_PATH=/Users/thesofakillers/.tmux/plugins/
 
     active environment : None
            shell level : 0
       user config file : /Users/thesofakillers/.condarc
 populated config files : /Users/thesofakillers/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/thesofakillers/miniconda3  (writable)
      conda av data dir : /Users/thesofakillers/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/thesofakillers/miniconda3/pkgs
                          /Users/thesofakillers/.conda/pkgs
       envs directories : /Users/thesofakillers/miniconda3/envs
                          /Users/thesofakillers/.conda/envs
               platform : osx-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.8.5 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : /Users/thesofakillers/.netrc
           offline mode : False
 
 
An unexpected error has occurred. Conda has prepared the above report.
```

Not sure what is breaking it.

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : /Users/thesofakillers/.condarc
 populated config files : /Users/thesofakillers/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.15.7=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/thesofakillers/miniconda3  (writable)
      conda av data dir : /Users/thesofakillers/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/thesofakillers/miniconda3/pkgs
                          /Users/thesofakillers/.conda/pkgs
       envs directories : /Users/thesofakillers/miniconda3/envs
                          /Users/thesofakillers/.conda/envs
               platform : osx-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.8.5 Darwin/19.6.0 OSX/10.15.7
                UID:GID : 501:20
             netrc file : /Users/thesofakillers/.netrc
           offline mode : False
```
</details>

### Conda Config

```shell
==> /Users/thesofakillers/.condarc <==
changeps1: False
```

### Conda list

```shell
# packages in environment at /Users/thesofakillers/miniconda3:
#
# Name                    Version                   Build  Channel
brotlipy                  0.7.0           py38h9ed2024_1003    defaults
ca-certificates           2022.07.19           hecd8cb5_0    defaults
certifi                   2022.6.15        py38hecd8cb5_0    defaults
cffi                      1.15.1           py38hc55c11b_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     4.14.0           py38hecd8cb5_0    defaults
conda-package-handling    1.8.1            py38hca72f7f_0    defaults
cryptography              37.0.1           py38hf6deb26_0    defaults
cytoolz                   0.11.0           py38haf1e3a3_0    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
libcxx                    12.0.0               h2f01273_0    defaults
libffi                    3.3                  hb1e8313_2    defaults
ncurses                   6.3                  hca72f7f_3    defaults
openssl                   1.1.1q               hca72f7f_0    defaults
pip                       22.1.2           py38hecd8cb5_0    defaults
pycosat                   0.6.3            py38h1de35cc_1    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1                    py38_1    defaults
python                    3.8.5                h26836e1_1    defaults
python.app                2                       py38_10    defaults
readline                  8.1.2                hca72f7f_1    defaults
requests                  2.28.1           py38hecd8cb5_0    defaults
ruamel_yaml               0.15.100         py38h9ed2024_0    defaults
setuptools                61.2.0           py38hecd8cb5_0    defaults
sqlite                    3.39.2               h707629a_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
toolz                     0.11.2             pyhd3eb1b0_0    defaults
tqdm                      4.64.0           py38hecd8cb5_0    defaults
urllib3                   1.26.11          py38hecd8cb5_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                hca72f7f_1    defaults
yaml                      0.2.5                haf1e3a3_0    defaults
zlib                      1.2.12               h4dc903c_2    defaults
```

**Comment by earwig** [comment]
I think this is happening because no environments are active when the rename runs.

Can you try the rename with an unrelated different (e.g. base) loaded?

**Comment by thesofakillers** [comment]
That works! Thank you.

**Comment by ReHoss** [comment]
Worked activating base env.

**Comment by beeankha** [comment]
Just updating here that this PR is currently taking care of the error that was originally reported in this issue:
- https://github.com/conda/conda/pull/11915

**Comment by kenodegard** [comment]
Not stale
