### ISSUE TITLE
Anaconda navigator won't start up even after reinstallation

### ISSUE THREAD

**Issue by King-Shady** [conda/conda#11884]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Main Error
unacceptable character #x0000: special characters are not allowed
  in "C:\Users\sachin\.continuum\anaconda-client\config.yaml", position 0
Traceback
Traceback (most recent call last):
  File "C:\Users\sachin\anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 74, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\sachin\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 137, in start_app
    window = run_app(splash)
  File "C:\Users\sachin\anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 60, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\sachin\anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 224, in __init__
    for _ in anaconda_solvers.POOL.solve():
  File "C:\Users\sachin\anaconda3\lib\site-packages\anaconda_navigator\utils\anaconda_solvers\core.py", line 72, in solve
    configuration: typing.Any = binstar_client.utils.get_config()
  File "C:\Users\sachin\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 250, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\sachin\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\sachin\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 242, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\sachin\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 222, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\sachin\anaconda3\lib\site-packages\binstar_client\utils\config.py", line 206, in load_config
    data = yaml_load(fd)
  File "C:\Users\sachin\anaconda3\lib\site-packages\binstar_client\utils\yaml.py", line 12, in yaml_load
    return safe_load(stream)
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\__init__.py", line 79, in load
    loader = Loader(stream)
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\sachin\anaconda3\lib\site-packages\yaml\reader.py", line 143, in check_printable
    raise ReaderError(self.name, position, ord(character),
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\sachin\.continuum\anaconda-client\config.yaml", position 0

**Comment by travishathaway** [comment]
Hi @King-Shady,

Thank you for filing this issue! Unfortunately, this is off-topic for this repository. If you are still encountering this issue please reopen in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) where Navigator issues are addressed.

We will be closing this issue now.
