### ISSUE TITLE
UnicodeDecodeError when installing conda or miniconda

### ISSUE THREAD

**Issue by Edward205** [conda/conda#11888]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This issue occurs while trying either conda or miniconda. I am not able to complete the installation due to the error. I am using a fresh installation of Arch Linux. I've tried installing via bash script and AUR but the error occurs on both. 
Error:

```
Do you accept the license terms? [yes|no]
[no] >>> yes

Miniconda3 will now be installed into this location:
/home/edward/miniconda3

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/home/edward/miniconda3] >>> 
PREFIX=/home/edward/miniconda3
Unpacking payload ...
Collecting package metadata (current_repodata.json): failed                                                                 
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "site-packages/conda/exceptions.py", line 1079, in __call__
  File "site-packages/conda/cli/main.py", line 84, in _main
  File "site-packages/conda/cli/conda_argparse.py", line 83, in do_call
  File "site-packages/conda/cli/main_install.py", line 20, in execute
  File "site-packages/conda/cli/install.py", line 261, in install
  File "site-packages/conda/core/solve.py", line 114, in solve_for_transaction
  File "site-packages/conda/core/solve.py", line 157, in solve_for_diff
  File "site-packages/conda/core/solve.py", line 262, in solve_final_state
  File "site-packages/conda/common/io.py", line 88, in decorated
  File "site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
  File "site-packages/conda/core/index.py", line 164, in _supplement_index_with_system
  File "site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
  File "site-packages/conda/base/context.py", line 817, in os_distribution_name_version
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/conda/_vendor/distro.py", line 1084, in <module>
  File "site-packages/conda/_vendor/distro.py", line 601, in __init__
  File "site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
  File "site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
  File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 48: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/conda/exceptions.py", line 1211, in print_unexpected_error_report
  File "site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "site-packages/conda/exceptions.py", line 1079, in __call__
      File "site-packages/conda/cli/main.py", line 84, in _main
      File "site-packages/conda/cli/conda_argparse.py", line 83, in do_call
      File "site-packages/conda/cli/main_install.py", line 20, in execute
      File "site-packages/conda/cli/install.py", line 261, in install
      File "site-packages/conda/core/solve.py", line 114, in solve_for_transaction
      File "site-packages/conda/core/solve.py", line 157, in solve_for_diff
      File "site-packages/conda/core/solve.py", line 262, in solve_final_state
      File "site-packages/conda/common/io.py", line 88, in decorated
      File "site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
      File "site-packages/conda/core/index.py", line 164, in _supplement_index_with_system
      File "site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
      File "site-packages/conda/base/context.py", line 817, in os_distribution_name_version
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
      File "site-packages/conda/_vendor/distro.py", line 1084, in <module>
      File "site-packages/conda/_vendor/distro.py", line 601, in __init__
      File "site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
      File "site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
      File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/encodings/ascii.py", line 26, in decode
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 48: ordinal not in range(128)

`$ /home/edward/miniconda3/conda.exe install --offline --file /home/edward/miniconda3/pkgs/env.txt -yp /home/edward/miniconda3`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

Traceback (most recent call last):
  File "site-packages/conda/exceptions.py", line 1079, in __call__
  File "site-packages/conda/cli/main.py", line 84, in _main
  File "site-packages/conda/cli/conda_argparse.py", line 83, in do_call
  File "site-packages/conda/cli/main_install.py", line 20, in execute
  File "site-packages/conda/cli/install.py", line 261, in install
  File "site-packages/conda/core/solve.py", line 114, in solve_for_transaction
  File "site-packages/conda/core/solve.py", line 157, in solve_for_diff
  File "site-packages/conda/core/solve.py", line 262, in solve_final_state
  File "site-packages/conda/common/io.py", line 88, in decorated
  File "site-packages/conda/core/solve.py", line 397, in _collect_all_metadata
  File "site-packages/conda/core/index.py", line 164, in _supplement_index_with_system
  File "site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
  File "site-packages/conda/base/context.py", line 817, in os_distribution_name_version
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/conda/_vendor/distro.py", line 1084, in <module>
  File "site-packages/conda/_vendor/distro.py", line 601, in __init__
  File "site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
  File "site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
  File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 48: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "entry_point.py", line 91, in <module>
  File "site-packages/conda/cli/main.py", line 152, in main
  File "site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
  File "site-packages/conda/exceptions.py", line 1082, in __call__
  File "site-packages/conda/exceptions.py", line 1126, in handle_exception
  File "site-packages/conda/exceptions.py", line 1141, in handle_unexpected_exception
  File "site-packages/conda/exceptions.py", line 1303, in _execute_upload
  File "site-packages/conda/exceptions.py", line 1101, in user_agent
  File "site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
  File "site-packages/conda/base/context.py", line 775, in user_agent
  File "site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
  File "site-packages/conda/base/context.py", line 817, in os_distribution_name_version
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/conda/_vendor/distro.py", line 1084, in <module>
  File "site-packages/conda/_vendor/distro.py", line 601, in __init__
  File "site-packages/conda/_vendor/distro.py", line 1025, in _get_distro_release_info
  File "site-packages/conda/_vendor/distro.py", line 1048, in _parse_distro_release_file
  File "/tmp/build/80754af9/conda-standalone_1636413482883/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.9/encodings/ascii.py", line 26, in decode
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 48: ordinal not in range(128)
[2281] Failed to execute script entry_point
```

### Additional Context

I've been able to find other people with the same issue, but the posts are very old and they were using Python 2. I am using Python Python 3.10.7

**Comment by ForgottenProgramme** [comment]
Thank you for raising this, @Edward205.
Could you please give us the name and the SHA256 checksum of the installer program you're running, as well as the output of `locale`.

**Comment by Edward205** [comment]
Thanks for pointing out `locale`. I've recently had issues with it and my configurations were messed up. It worked after I checked that the locale set in the /etc/locale.conf file matched the one set in KDE's regional settings (now set to en_US). For future reference, here is the SHA256 checksum:
```
Miniconda3-py39_4.12.0-Linux-x86_64.sh
78f39f9bae971ec1ae7969f0516017f2413f17796670f7040725dd83fcff5689
```
