### ISSUE TITLE
Can't install Pycairo

### ISSUE THREAD

**Issue by waynelee1217** [conda/conda#1188]
Hi, 

I use "conda install pycairo-1.10.0.tar.bz2" to install Pycairo on my computer but I get the following error message. Thank you very much for your kind help!

Wayne

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 217, in install
    verbose=not args.quiet)
  File "//anaconda/lib/python3.4/site-packages/conda/misc.py", line 213, in install_local_packages
    execute_actions(actions, verbose=verbose)
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 513, in link
    files = list(yield_lines(join(info_dir, 'files')))
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 193, in yield_lines
    for line in open(path):
FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/pkgs/pycairo-1.10.0/info/files'

**Comment by ilanschnell** [comment]
Use `conda install py2cairo`.  You cannot install source tarballs using conda, only valid conda packages.

**Comment by waynelee1217** [comment]
Thank you ilanschnell! I tried to use "conda install pycairo", but this also leads to the following error messages. I have pycairo in my current directory, do install this in a wrong way? Thank you for helping!


Fetching package metadata: ....
Error: No packages found in current osx-64 channels matching: pycairo
Did you mean one of these?
    pyaudio
You can search for this package on Binstar with
    binstar search -t conda pycairo
