### ISSUE TITLE
Unexpected error with conda, problem installing new environments or packages

### ISSUE THREAD

**Issue by gubrins** [conda/conda#11898]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Heys,

I am trying to install a new environment with conda: 
```
conda create -y -n qc3c -c cerebis -c conda-forge -c bioconda qc3C`

And I get this error message:


`Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 531, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://repo.anaconda.com/pkgs/free/noarch/current_repodata.json
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/requests/models.py", line 910, in json
        return complexjson.loads(self.text, **kwargs)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
        return _default_decoder.decode(s)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
        obj, end = self.raw_decode(s)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
        return self.scan_once(s, idx=_w(s, idx).end())
    simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 72, in wrapper
        return_value = func(*args, **kwargs)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/cli/main_create.py", line 43, in execute
        install(args, parser, 'create')
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 261, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 156, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 304, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 467, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 1061, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/index.py", line 301, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 137, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/panthera/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
        yield fs.pop().result()
      File "/home/panthera/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/home/panthera/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
      File "/home/panthera/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 129, in <lambda>
        subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 142, in query
        self.load()
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 207, in load
        _internal_state = self._load()
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 277, in _load
        raw_repodata_str = fetch_repodata_remote_request(
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/core/subdir_data.py", line 587, in fetch_repodata_remote_request
        raise UnavailableInvalidChannel(
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 464, in __init__
        body = response.json()
      File "/home/panthera/miniconda3/lib/python3.9/site-packages/requests/models.py", line 917, in json
        raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    requests.exceptions.JSONDecodeError: [Errno Expecting value] <html>
    <head><title>404 Not Found</title></head>
    <body>
    <h1>404 Not Found</h1>
    <ul>
    <li>Code: NoSuchKey</li>
    <li>Message: The specified key does not exist.</li>
    <li>Key: pkgs/free/noarch/current_repodata.json</li>
    <li>RequestId: YGVRRSETKSRK39TN</li>
    <li>HostId: hx5GhLCHGp6XDUtRNaVWGCO5x7AaICOVDjc3+WsdvmgvxdXKgX1Mau68lDFg9EIE5SHxzjpaCPg=</li>
    </ul>
    <hr/>
    </body>
    </html>
    : 0
```

```
$ /home/panthera/miniconda3/bin/conda create -y -n qc3c -c cerebis -c conda-forge -c bioconda qc3C`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/panthera/miniconda3/bin/conda
             CONDA_PREFIX=/home/panthera/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/panthera/miniconda3/bin/python
               CONDA_ROOT=/home/panthera/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/home/panthera/software/beagle-lib/lib:/home/panthera/software/beagle-
                          lib/lib:/home/panthera/software/beagle-
                          lib/lib:/home/panthera/software/beagle-
                          lib/lib:/home/panthera/software/beagle-
                          lib/lib:/home/panthera/software/beagle-
                          lib/lib:/home/panthera/software/beagle-lib/lib:
                     PATH=/home/panthera/.local/bin:/home/panthera/bin:/home/panthera/miniconda3
                          /bin:/home/panthera/miniconda3/condabin:/usr/local/sbin:/usr/local/bin
                          :/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/
                          home/panthera/bin:/home/panthera/software/MitoFinder:/mnt/DiscoD/ibero
                          lacerta/analyses/hi-c/tutorial_manual/SALSA2/bin:/home/panthera/bin:/h
                          ome/panthera/software/MitoFinder:/mnt/DiscoD/iberolacerta/analyses/hi-
                          c/tutorial_manual/SALSA2/bin:/home/panthera/bin:/home/panthera/softwar
                          e/MitoFinder:/mnt/DiscoD/iberolacerta/analyses/hi-c/tutorial_manual/SA
                          LSA2/bin:/home/panthera/bin:/home/panthera/software/MitoFinder:/mnt/Di
                          scoD/iberolacerta/analyses/hi-c/tutorial_manual/SALSA2/bin:/home/panth
                          era/bin:/home/panthera/software/MitoFinder:/mnt/DiscoD/iberolacerta/an
                          alyses/hi-c/tutorial_manual/SALSA2/bin:/home/panthera/bin:/home/panthe
                          ra/software/MitoFinder:/mnt/DiscoD/iberolacerta/analyses/hi-c/tutorial
                          _manual/SALSA2/bin:/home/panthera/bin:/home/panthera/software/MitoFind
                          er:/mnt/DiscoD/iberolacerta/analyses/hi-c/tutorial_manual/SALSA2/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/panthera/miniconda3
            shell level : 1
       user config file : /home/panthera/.condarc
 populated config files : /home/panthera/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/panthera/miniconda3  (writable)
      conda av data dir : /home/panthera/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/cerebis/linux-64
                          https://conda.anaconda.org/cerebis/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda/label/cf201901/linux-64
                          https://conda.anaconda.org/bioconda/label/cf201901/noarch
                          https://conda.anaconda.org/biobuilds/linux-64
                          https://conda.anaconda.org/biobuilds/noarch
                          https://conda.anaconda.org/yuxiang/linux-64
                          https://conda.anaconda.org/yuxiang/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/panthera/miniconda3/pkgs
                          /home/panthera/.conda/pkgs
       envs directories : /home/panthera/miniconda3/envs
                          /home/panthera/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Linux/5.15.0-43-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```

Any idea of what is happening? I've seen there are several posts about this error, but I tried to solve it and I did not manage. Also, all my previous created environments has dissapeared. 

Thanks in advance!

### Conda Info

```shell
active environment : base
    active env location : /home/panthera/miniconda3
            shell level : 1
       user config file : /home/panthera/.condarc
 populated config files : /home/panthera/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/panthera/miniconda3  (writable)
      conda av data dir : /home/panthera/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/bioconda/label/cf201901/linux-64
                          https://conda.anaconda.org/bioconda/label/cf201901/noarch
                          https://conda.anaconda.org/biobuilds/linux-64
                          https://conda.anaconda.org/biobuilds/noarch
                          https://conda.anaconda.org/yuxiang/linux-64
                          https://conda.anaconda.org/yuxiang/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/panthera/miniconda3/pkgs
                          /home/panthera/.conda/pkgs
       envs directories : /home/panthera/miniconda3/envs
                          /home/panthera/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Linux/5.15.0-43-generic ubuntu/20.04.3 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/panthera/.condarc <==
auto_activate_base: True
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - r
  - bioconda/label/cf201901
  - biobuilds
  - yuxiang
  - defaults
restore_free_channel: True
report_errors: True
anaconda_upload: False
```

### Conda list

```shell
# packages in environment at /home/panthera/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             4.5                       1_gnu    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2022.9.24            ha878542_0    conda-forge
certifi                   2022.9.24          pyhd8ed1ab_0    conda-forge
cffi                      1.15.0           py39hd667e15_1    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.3                    pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0    defaults
coloredlogs               15.0.1                   pypi_0    pypi
colormath                 3.0.0                    pypi_0    pypi
commonmark                0.9.1                    pypi_0    pypi
conda                     22.9.0           py39hf3d152e_0    conda-forge
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-package-handling    1.8.1            py39h7f8727e_0    defaults
contourpy                 1.0.5                    pypi_0    pypi
cryptography              36.0.0           py39h9ce1e76_0    defaults
cycler                    0.11.0                   pypi_0    pypi
fonttools                 4.37.3                   pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0    defaults
importlib-metadata        4.12.0                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              12.1.0              ha89aaad_16    conda-forge
lzstring                  1.0.4                    pypi_0    pypi
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.6.0                    pypi_0    pypi
multiqc                   1.13                     pypi_0    pypi
ncurses                   6.3                  h7f8727e_2    defaults
networkx                  2.8.6                    pypi_0    pypi
numpy                     1.23.3                   pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0    defaults
packaging                 21.3                     pypi_0    pypi
pillow                    9.2.0                    pypi_0    pypi
pip                       21.2.4           py39h06a4308_0    defaults
pretextgraph              0.0.6                h9f5acd7_1    bioconda
pycosat                   0.6.3            py39h27cfd23_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyfastaq                  3.17.0                   pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.12               h12debd9_0    defaults
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9                      2_cp39    conda-forge
pyyaml                    6.0                      pypi_0    pypi
readline                  8.1.2                h7f8727e_1    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
rich                      12.5.1                   pypi_0    pypi
rich-click                1.5.2                    pypi_0    pypi
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
seqtk                     0.5.0                    pypi_0    pypi
setuptools                61.2.0           py39h06a4308_0    defaults
simplejson                3.17.6                   pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    defaults
spectra                   0.0.11                   pypi_0    pypi
sqlite                    3.38.2               hc218d9a_0    defaults
tk                        8.6.11               h1ccaba5_0    defaults
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.63.0             pyhd3eb1b0_0    defaults
tzdata                    2022a                hda174b7_0    defaults
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.5                h7b6447c_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zipp                      3.8.1                    pypi_0    pypi
zlib                      1.2.12               h7f8727e_1    defaults
```

**Comment by gubrins** [comment]
solved following this: https://www.biostars.org/p/9542819/#9548176
