### ISSUE TITLE
conda logs ModuleNotFoundError: No module named '_distutils_hack' errors

### ISSUE THREAD

**Issue by sarod** [conda/conda#11931]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Although conda commands seems to work properly they log the following error before processing the command:
```
Error processing line 1 of C:\Users\sebas\miniconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sebas\miniconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'
```

### Conda Info

```shell
Error processing line 1 of C:\Users\sebas\miniconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sebas\miniconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored

     active environment : None
       user config file : C:\Users\sebas\.condarc
 populated config files : C:\Users\sebas\.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.8.13.final.0
       virtual packages : __cuda=11.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\sebas\miniconda3  (writable)
      conda av data dir : C:\Users\sebas\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\sebas\miniconda3\pkgs
                          C:\Users\sebas\.conda\pkgs
                          C:\Users\sebas\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\sebas\miniconda3\envs
                          C:\Users\sebas\.conda\envs
                          C:\Users\sebas\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.22.0 CPython/3.8.13 Windows/10 Windows/10.0.22000
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
Error processing line 1 of C:\Users\sebas\miniconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sebas\miniconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
==> C:\Users\sebas\.condarc <==
channels:
  - defaults
```

### Conda list

```shell
Error processing line 1 of C:\Users\sebas\miniconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sebas\miniconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
==> C:\Users\sebas\.condarc <==
channels:
  - defaults

PS D:\dev\git\semarchy\mdm-backport> conda list --show-channel-urls
Error processing line 1 of C:\Users\sebas\miniconda3\lib\site-packages\distutils-precedence.pth:

  Traceback (most recent call last):
    File "C:\Users\sebas\miniconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
# packages in environment at C:\Users\sebas\miniconda3:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
astor                     0.8.0                    pypi_0    pypi
asttokens                 2.0.8                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
bleach                    5.0.1                    pypi_0    pypi
boto                      2.49.0                   pypi_0    pypi
boto3                     1.9.188                  pypi_0    pypi
botocore                  1.12.188                 pypi_0    pypi
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
ca-certificates           2022.9.24            h5b45459_0    conda-forge
certifi                   2019.6.16                pypi_0    pypi
cffi                      1.15.1           py38h2bbff1b_0    defaults
cfgv                      3.3.1                    pypi_0    pypi
chardet                   3.0.4                    pypi_0    pypi
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.3                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.5            py38haa95532_0    defaults
conda                     22.9.0           py38haa244fe_1    conda-forge
conda-package-handling    1.9.0            py38h8cc25b3_0    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              37.0.1           py38h21b164f_0    defaults
cudatoolkit               11.2.2              h933977f_10    conda-forge
cudnn                     8.1.0.77             h3e0f4f4_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dill                      0.3.5.1                  pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
docutils                  0.14                     pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
executing                 1.1.0                    pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
filelock                  3.8.0                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
gdown                     4.3.0                    pypi_0    pypi
gensim                    3.8.0                    pypi_0    pypi
google-pasta              0.1.7                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
identify                  2.5.6                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
importlib-metadata        5.0.0                    pypi_0    pypi
importlib-resources       5.9.0                    pypi_0    pypi
ipykernel                 6.16.0                   pypi_0    pypi
ipython                   8.5.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
jedi                      0.18.1                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jmespath                  0.9.4                    pypi_0    pypi
joblib                    1.0.0                    pypi_0    pypi
jsonschema                4.16.0                   pypi_0    pypi
jupyter                   1.0.0                    pypi_0    pypi
jupyter-client            7.2.0                    pypi_0    pypi
jupyter-console           6.4.4                    pypi_0    pypi
jupyter-core              4.11.1                   pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.0                    pypi_0    pypi
kiwisolver                1.4.4                    pypi_0    pypi
line-profiler             3.3.1                    pypi_0    pypi
loky                      2.9.0                    pypi_0    pypi
markdown                  3.1.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                2.2.5                    pypi_0    pypi
matplotlib-inline         0.1.6                    pypi_0    pypi
menuinst                  1.4.18           py38h59b6b97_0    defaults
mistune                   2.0.4                    pypi_0    pypi
nbclient                  0.6.8                    pypi_0    pypi
nbconvert                 7.1.0                    pypi_0    pypi
nbformat                  5.6.1                    pypi_0    pypi
nest-asyncio              1.5.6                    pypi_0    pypi
nltk                      3.5                      pypi_0    pypi
nodeenv                   1.7.0                    pypi_0    pypi
notebook                  6.4.12                   pypi_0    pypi
numpy                     1.21.5                   pypi_0    pypi
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.2.0                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       22.2.2           py38haa95532_0    defaults
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
platformdirs              2.5.2                    pypi_0    pypi
powershell_shortcut       0.0.1                         3    defaults
pre-commit                2.8.2                    pypi_0    pypi
prometheus-client         0.14.1                   pypi_0    pypi
prompt-toolkit            3.0.31                   pypi_0    pypi
protobuf                  3.9.0                    pypi_0    pypi
psutil                    5.9.2                    pypi_0    pypi
pure-eval                 0.2.2                    pypi_0    pypi
pyarrow                   2.0.0                    pypi_0    pypi
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyfunctional              1.4.2                    pypi_0    pypi
pygments                  2.13.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pyrsistent                0.18.1                   pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0    defaults
python                    3.8.13               h6244533_0    defaults
python-dateutil           2.8.0                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytz                      2019.1                   pypi_0    pypi
pywin32                   302              py38h2bbff1b_2    defaults
pywinpty                  2.0.8                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
qtconsole                 5.3.2                    pypi_0    pypi
qtpy                      2.2.1                    pypi_0    pypi
regex                     2022.9.13                pypi_0    pypi
requests                  2.22.0                   pypi_0    pypi
ruamel_yaml               0.15.100         py38h2bbff1b_0    defaults
s3transfer                0.2.1                    pypi_0    pypi
scikit-learn              0.24.0                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                47.1.1                   pypi_0    pypi
sherlock                  0.1.0                     dev_0    <develop>
six                       1.12.0                   pypi_0    pypi
smart-open                1.8.4                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.39.3               h2bbff1b_0    defaults
stack-data                0.5.1                    pypi_0    pypi
tabulate                  0.8.10                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.16.0                   pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tinycss2                  1.1.1                    pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.2             pyhd3eb1b0_0    defaults
tornado                   6.2                      pypi_0    pypi
tqdm                      4.51.0                   pypi_0    pypi
traitlets                 5.4.0                    pypi_0    pypi
urllib3                   1.25.3                   pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
virtualenv                20.16.5                  pypi_0    pypi
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  0.15.4                   pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
widgetsnbextension        4.0.3                    pypi_0    pypi
win_inet_pton             1.1.0            py38haa95532_0    defaults
wincertstore              0.2              py38haa95532_2    defaults
wrapt                     1.11.2                   pypi_0    pypi
yaml                      0.2.5                he774522_0    defaults
zipp                      3.8.1                    pypi_0    pypi
```

**Comment by sarod** [comment]
After digging into this I found that running " pip install -U pip setuptools" solved the issue for me.
