### ISSUE TITLE
Please remove this file manually (you may need to reboot to free file handles)

### ISSUE THREAD

**Issue by orena1** [conda/conda#11977]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to install anaconda on a a mounted system which I think is a bit slow, I am running this command:
`./conda.exe constructor --prefix /mnt/nasquatch/data/colabs/anaconda3/ --extract-conda-pkgs`
and get this error:
```bash
(base) andermannlab@colab02:/mnt/nasquatch/data/colabs/anaconda3$ ./conda.exe constructor --prefix /mnt/nasquatch/data/colabs/anaconda3/ --extract-conda-pkgs
Extracting : regex-2022.3.15-py39h7f8727e_0.conda:   0%|▎                                                                                                                             | 1/431 [00:04<31:42,  4.42s/it]Could not remove or rename /mnt/nasquatch/data/colabs/anaconda3/pkgs/libspatialindex-1.9.3-h2531618_0oc3rktqp/pkg-libspatialindex-1.9.3-h2531618_0.tar.zst.  Please remove this file manually (you may need to reboot to free file handles)
concurrent.futures.process._RemoteTraceback:
'''
Traceback (most recent call last):
  File "concurrent/futures/process.py", line 384, in wait_result_broken_or_wakeup
  File "multiprocessing/connection.py", line 256, in recv
TypeError: __init__() missing 1 required positional argument: 'msg'
'''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent/futures/process.py", line 559, in _chain_from_iterable_of_lists
  File "concurrent/futures/_base.py", line 608, in result_iterator
  File "concurrent/futures/_base.py", line 445, in result
  File "concurrent/futures/_base.py", line 390, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[69655] Failed to execute script entry_point```

I have permission for the folder, I think it just a bit slow in updating it, from what I see here:
https://github.com/conda/conda/blob/fc92ea3353cce71df24fac31ce333ec9f8cf7ba7/conda/gateways/disk/delete.py#L153
there is a `max_retries` variable, but I do not see that it is used at all. I assume if I would have managed to increase its value it will work, but as I am working with a conda.exe I am not sure how to modify/debug the code.


### Conda Info

```shell
./conda.exe info

     active environment : None
            shell level : 0
       user config file : /home/andermannlab/.condarc
 populated config files :
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /tmp/_MEIfxUMNt  (read only)
      conda av data dir : /tmp/_MEIfxUMNt/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/_MEIfxUMNt/pkgs
                          /home/andermannlab/.conda/pkgs
       envs directories : /home/andermannlab/.conda/envs
                          /tmp/_MEIfxUMNt/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Linux/5.15.0-48-generic ubuntu/20.04.5 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
NA
```

### Conda list

```shell
./conda.exe list --show-channel-urls

EnvironmentLocationNotFound: Not a conda environment: /tmp/_MEIHthzwn
```

**Comment by orena1** [comment]
The problem was that I was missing `mfsymlinks` option for the CIFS mount options in `/etc/fstab`
I've found the problem (when trying to move an already installed version [on the same path] to the NAS], when I did this I got this error:
` ln: failed to create symbolic link 'test': Operation not supported`
Which is much more informative, maybe it could be added, I'll have a look [I'm keeping the ticket open until I'll try to implement better error message]
