### ISSUE TITLE
"An unexpected error has occurred, please consider sending the following traceback"

### ISSUE THREAD

**Issue by oliverwreath** [conda/conda#1198]
$ conda update conda
Fetching package metadata: ..An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/skywalkerhunter/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 253, in install
    offline=args.offline)
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 524, in get_index_trap
    return get_index(_args, *_kwargs)
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/utils.py", line 79, in **call**
    value = self.func(_args, *_kw)
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 247, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 404, in result
    return self.__get_result()
  File "/Users/skywalkerhunter/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 356, in __get_result
    raise self._exception
IOError: invalid data stream

$ conda info
Current conda install:

```
         platform : osx-64
    conda version : 3.9.1
```

  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /Users/skywalkerhunter/anaconda  (writable)
  default environment : /Users/skywalkerhunter/anaconda
     envs directories : /Users/skywalkerhunter/anaconda/envs
        package cache : /Users/skywalkerhunter/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
@oliverwreath is this still an issue for you?
