### ISSUE TITLE
Windows machines without COM support fail to install packages

### ISSUE THREAD

**Issue by zooba** [conda/conda#12006]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

We have a machine that disallows COM (`CoInitializeEx` fails). This failure causes `conda install` to fail:

```
(base) C:\>conda install numpy==1.21.5
pythoncom error: CoInitializeEx failed (0x80004001)
pythoncom error: OLE initialization failed! (0x80004001)
Collecting package metadata (current_repodata.json): failed
WARNING conda.exceptions:print_unexpected_error_report(1216): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\conda\exceptions.py", line 1082, in __call__
    return func(*args, **kwargs)
  File "C:\Python\lib\site-packages\conda\cli\main.py", line 87, in _main
    exit_code = do_call(args, p)
  File "C:\Python\lib\site-packages\conda\cli\conda_argparse.py", line 84, in do_call
    return getattr(module, func_name)(args, parser)
  File "C:\Python\lib\site-packages\conda\cli\main_install.py", line 20, in execute
    install(args, parser, 'install')
  File "C:\Python\lib\site-packages\conda\cli\install.py", line 260, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "C:\Python\lib\site-packages\conda\core\solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
  File "C:\Python\lib\site-packages\conda\core\solve.py", line 195, in solve_for_diff
    final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
  File "C:\Python\lib\site-packages\conda\core\solve.py", line 300, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "C:\Python\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\Python\lib\site-packages\conda\core\solve.py", line 463, in _collect_all_metadata
    index, r = self._prepare(prepared_specs)
  File "C:\Python\lib\site-packages\conda\core\solve.py", line 1058, in _prepare
    reduced_index = get_reduced_index(self.prefix, self.channels,
  File "C:\Python\lib\site-packages\conda\core\index.py", line 288, in get_reduced_index
    new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
  File "C:\Python\lib\site-packages\conda\core\subdir_data.py", line 118, in query_all
    create_cache_dir()
  File "C:\Python\lib\site-packages\conda\core\subdir_data.py", line 876, in create_cache_dir
    cache_dir = join(PackageCacheData.first_writable().pkgs_dir, 'cache')
  File "C:\Python\lib\site-packages\conda\core\package_cache_data.py", line 151, in first_writable
    pkgs_dirs = context.pkgs_dirs
  File "C:\Python\lib\site-packages\conda\base\context.py", line 530, in pkgs_dirs
    fixed_dirs += user_data_dir(APP_NAME, APP_NAME),
  File "C:\Python\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)
  File "C:\Python\lib\site-packages\conda\_vendor\appdirs.py", line 285, in _get_win_folder_with_pywin32
    dir = shell.SHGetFolderPath(0, getattr(shellcon, csidl_name), 0, 0)
pywintypes.com_error: (-2147467259, 'Unspecified error', None, None)
```

<details>
The error report also fails, but that's not related to the underlying issue.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\conda\exceptions.py", line 1214, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "C:\Python\lib\site-packages\conda\cli\main_info.py", line 237, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'
```
</details>

The cause is that `appdirs` assumes that if it can _import_ PyWin32, then it can use it. There's no fallback for when the call itself fails, as in this case.

Switching to [`platformdirs`](https://github.com/platformdirs/platformdirs) is probably the best long-term plan for upstream. We're hoping to work around the issue by explicitly specifying all the paths we need.

**Comment by travishathaway** [comment]
Hi @zooba,

Thanks for reporting this issue. We currently rely on a vendor version of `appdirs`. It definitely makes sense for us to move to using `platformdirs` as you suggested.

We will try to figure out how to recreate this error in our tests before going forward with a solution. If you had any advice for us in writing these tests, that would be a huge help.

**Comment by adieldar** [comment]
I encountered that problem when trying to create a Windows 2022 nanoserver docker (FROM mcr.microsoft.com/windows/nanoserver:ltsc2022-amd64) with miniconda.

**Comment by zooba** [comment]
I haven't tried reproducing this recently, but I assume from the lack of activity that nothing has changed?
