### ISSUE TITLE
Spyder Update Error

### ISSUE THREAD

**Issue by nickeubank** [conda/conda#1201]
Hi All,

Was updating spyder from the launcher and a message suggested I post the following here. Note I had spyder previous to installing Anaconda, if that matters, though I thought I'd deleted it. Spyder seems to have opened fine, so not really a problem for me. 

```
Traceback (most recent call last):
  File "/Users/Nick/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    try:
  File "/Users/Nick/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/Nick/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 387, in install
    regex = '^(%s)$' % '|'.join(spec_names)
  File "/Users/Nick/anaconda/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
  File "/Users/Nick/anaconda/lib/python2.7/site-packages/conda/plan.py", line 571, in execute_plan
  File "/Users/Nick/anaconda/lib/python2.7/site-packages/conda/install.py", line 574, in unlink
    'type': link_name_map.get(linktype)}
IOError: [Errno 2] No such file or directory: '/Users/Nick/anaconda/conda-meta/conda-3.7.0-py27_0.json'

Close
```

**Comment by ccordoba12** [comment]
Thanks for reporting. This is not a problem with Spyder but with the Laucher.

Right now the Launcher is being reworked and a new version will be available soon that will fix this problem.

**Comment by asmeurer** [comment]
This is a similar error to #1122.
