### ISSUE TITLE
Conda update Assertion Error

### ISSUE THREAD

**Issue by swotai** [conda/conda#1203]
When doing conda update conda the following error pops up.  Please advise.

```
C:\Users\Dennis>conda update conda
Fetching package metadata: ..
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 239, in install
    assert len(vers_inst) == 1, name
AssertionError: conda

C:\Users\Dennis>conda info
Current conda install:

             platform : win-64
        conda version : 3.7.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False
'''
```

**Comment by asmeurer** [comment]
What files are in `C:\Anaconda\conda-meta`?

**Comment by swotai** [comment]
As follow.  Could it be related to that I installed a few packages using pip install?

```
 Volume in drive C has no label.
 Volume Serial Number is 4482-DBD2

 Directory of C:\Anaconda\conda-meta

03/18/2015  11:01 AM    <DIR>          .
03/18/2015  11:01 AM    <DIR>          ..
12/09/2014  09:53 PM               817 accelerate-1.8.0-np19py27_p0.json
09/11/2014  09:23 PM             6,644 anaconda-2.0.1-np18py27_0.json
12/10/2014  12:12 AM             7,182 anaconda-2.1.0-np19py27_0.json
09/11/2014  09:20 PM             1,212 argcomplete-0.6.7-py27_0.json
12/10/2014  12:06 AM             1,254 argcomplete-0.8.1-py27_0.json
09/11/2014  09:20 PM            64,663 astropy-0.3.2-np18py27_0.json
12/10/2014  12:06 AM            74,783 astropy-0.4.2-np19py27_0.json
09/11/2014  09:20 PM             2,537 atom-0.3.7-py27_0.json
12/10/2014  12:06 AM             2,517 atom-0.3.9-py27_0.json
09/11/2014  09:20 PM             1,962 beautiful-soup-4.3.1-py27_0.json
12/10/2014  12:06 AM             2,030 beautiful-soup-4.3.2-py27_0.json
09/11/2014  09:20 PM             6,042 binstar-0.5.3-py27_0.json
12/10/2014  12:06 AM             6,616 binstar-0.7.1-py27_0.json
12/10/2014  12:06 AM               513 bitarray-0.8.1-py27_1.json
09/11/2014  09:20 PM            20,609 blaze-0.5.0-np18py27_1.json
12/10/2014  12:06 AM             7,153 blaze-0.6.3-np19py27_0.json
09/11/2014  09:20 PM             2,431 blz-0.6.2-np18py27_0.json
12/10/2014  12:06 AM             2,431 blz-0.6.2-np19py27_0.json
09/11/2014  09:20 PM           155,539 bokeh-0.4.4-np18py27_1.json
12/10/2014  12:06 AM            93,471 bokeh-0.6.1-np19py27_0.json
09/11/2014  09:20 PM            36,664 boto-2.28.0-py27_0.json
12/10/2014  12:06 AM            37,290 boto-2.32.1-py27_0.json
12/10/2014  12:06 AM               298 casuarius-1.1-py27_0.json
12/10/2014  12:06 AM               295 cdecimal-2.3-py27_1.json
12/10/2014  12:06 AM             1,832 cffi-0.8.6-py27_0.json
09/11/2014  09:20 PM            28,899 chaco-4.4.1-np18py27_0.json
12/10/2014  12:06 AM            28,899 chaco-4.4.1-np19py27_0.json
09/11/2014  09:20 PM               835 colorama-0.2.7-py27_0.json
12/10/2014  12:06 AM               899 colorama-0.3.1-py27_0.json
12/10/2014  12:06 AM             5,156 conda-3.7.0-py27_0.json
12/09/2014  09:34 PM             5,470 conda-3.7.3-py27_0.json
09/11/2014  09:20 PM             3,943 conda-build-1.3.5-py27_0.json
12/10/2014  12:06 AM             4,280 conda-build-1.8.2-py27_0.json
09/11/2014  09:20 PM               596 configobj-5.0.5-py27_0.json
12/10/2014  12:06 AM               596 configobj-5.0.6-py27_0.json
12/10/2014  12:06 AM            14,398 cryptography-0.5.4-py27_0.json
09/11/2014  09:20 PM             3,755 cubes-0.10.2-py27_4.json
10/21/2014  11:26 AM               994 cudatoolkit-6.0-p0.json
09/11/2014  09:20 PM            17,596 cython-0.20.1-py27_0.json
12/10/2014  12:06 AM            18,800 cython-0.21-py27_0.json
12/10/2014  12:06 AM             1,340 cytoolz-0.7.0-py27_0.json
09/11/2014  09:20 PM             3,859 datashape-0.2.0-np18py27_1.json
12/10/2014  12:06 AM             4,201 datashape-0.3.0-np19py27_1.json
12/10/2014  12:06 AM             1,120 dateutil-2.1-py27_2.json
12/10/2014  12:06 AM               342 decorator-3.4.0-py27_0.json
03/18/2015  11:01 AM                 0 dir.txt
09/11/2014  09:20 PM            18,220 docutils-0.11-py27_0.json
12/10/2014  12:06 AM            18,319 docutils-0.12-py27_0.json
09/11/2014  09:20 PM             5,581 dynd-python-0.6.2-np18py27_0.json
12/10/2014  12:06 AM             6,146 dynd-python-0.6.5-np19py27_0.json
09/11/2014  09:20 PM            32,220 enable-4.3.0-np18py27_2.json
12/10/2014  12:06 AM            32,220 enable-4.3.0-np19py27_2.json
09/11/2014  09:20 PM            39,299 enaml-0.9.1-py27_1.json
12/10/2014  12:07 AM            35,047 enaml-0.9.8-py27_0.json
12/10/2014  12:07 AM             3,878 flask-0.10.1-py27_1.json
09/11/2014  09:20 PM            24,206 future-0.12.1-py27_0.json
12/10/2014  12:07 AM            25,133 future-0.13.1-py27_0.json
12/10/2014  12:07 AM             1,272 futures-2.1.6-py27_0.json
10/23/2014  02:13 PM             6,693 gdal-1.11.0-np19py27_0.json
12/10/2014  12:07 AM             3,269 gevent-1.0.1-py27_0.json
12/10/2014  12:07 AM             2,060 gevent-websocket-0.9.3-py27_0.json
09/11/2014  09:20 PM               400 greenlet-0.4.2-py27_0.json
12/10/2014  12:07 AM               400 greenlet-0.4.4-py27_0.json
12/10/2014  12:07 AM               440 grin-1.2.1-py27_2.json
09/11/2014  09:20 PM             4,907 h5py-2.3.0-np18py27_0.json
12/10/2014  12:07 AM             4,907 h5py-2.3.1-np19py27_0.json
12/09/2014  09:53 PM             4,277 history
10/21/2014  11:26 AM             2,000 iopro-1.6.7-np19py27_p0.json
09/11/2014  09:20 PM           113,555 ipython-2.1.0-py27_2.json
12/10/2014  12:07 AM           113,555 ipython-2.2.0-py27_0.json
09/11/2014  09:20 PM               766 ipython-notebook-2.1.0-py27_0.json
12/10/2014  12:07 AM               766 ipython-notebook-2.2.0-py27_0.json
09/11/2014  09:20 PM               616 ipython-qtconsole-2.1.0-py27_0.json
12/10/2014  12:07 AM               616 ipython-qtconsole-2.2.0-py27_0.json
12/10/2014  12:07 AM               424 itsdangerous-0.24-py27_0.json
12/10/2014  12:07 AM               386 jdcal-1.0-py27_0.json
09/11/2014  09:20 PM             4,656 jinja2-2.7.2-py27_0.json
12/10/2014  12:07 AM             4,700 jinja2-2.7.3-py27_1.json
09/11/2014  09:20 PM               369 kiwisolver-0.1.2-py27_0.json
12/10/2014  12:07 AM               379 kiwisolver-0.1.3-py27_0.json
09/11/2014  09:20 PM             6,818 launcher-0.1.5-py27_0.json
12/10/2014  12:07 AM             9,971 launcher-1.0.0-1.json
12/10/2014  12:07 AM               371 libpython-1.0-py27_1.json
12/10/2014  12:07 AM             9,800 llvmpy-0.12.7-py27_0.json
09/11/2014  09:21 PM             4,973 lxml-3.3.5-py27_0.json
12/10/2014  12:07 AM             4,973 lxml-3.4.0-py27_0.json
09/11/2014  09:21 PM               872 markupsafe-0.18-py27_1.json
12/10/2014  12:07 AM               936 markupsafe-0.23-py27_0.json
09/11/2014  09:21 PM           171,251 matplotlib-1.3.1-np18py27_2.json
12/10/2014  12:08 AM           188,957 matplotlib-1.4.0-np19py27_0.json
09/11/2014  09:21 PM             1,119 menuinst-1.0.3-py27_0.json
12/10/2014  12:08 AM             1,183 menuinst-1.0.4-py27_0.json
12/10/2014  12:09 AM           186,313 mingw-4.7-1.json
10/21/2014  11:26 AM               836 mkl-11.1-np19py27_p3.json
10/21/2014  11:26 AM             1,544 mkl-rt-11.1-p0.json
10/21/2014  11:26 AM               895 mkl-service-1.0.0-py27_p1.json
10/21/2014  11:26 AM               962 mklfft-1.0-np19py27_p0.json
12/10/2014  12:09 AM               386 mock-1.0.1-py27_0.json
09/11/2014  09:21 PM             1,122 multipledispatch-0.4.3-py27_0.json
12/10/2014  12:09 AM               894 multipledispatch-0.4.7-py27_0.json
09/11/2014  09:21 PM            46,246 networkx-1.8.1-py27_0.json
12/10/2014  12:09 AM            46,732 networkx-1.9.1-py27_0.json
09/11/2014  09:21 PM            23,881 nltk-2.0.4-np18py27_0.json
12/10/2014  12:09 AM            28,739 nltk-3.0.0-np19py27_0.json
12/10/2014  12:09 AM               582 node-webkit-0.10.1-0.json
12/10/2014  12:09 AM             5,007 nose-1.3.4-py27_0.json
12/10/2014  12:09 AM            29,557 numba-0.14.0-np19py27_0.json
12/09/2014  09:53 PM            31,772 numba-0.15.1-np19py27_0.json
12/09/2014  09:53 PM             7,812 numbapro-0.16.0-np19py27_p0.json
10/21/2014  11:26 AM               608 numbapro_cudalib-0.1-0.json
12/10/2014  12:09 AM             1,306 numexpr-2.3.1-np19py27_0.json
10/21/2014  11:26 AM             1,692 numexpr-2.3.1-np19py27_p0.json
12/10/2014  12:10 AM            42,067 numpy-1.9.0-py27_0.json
12/09/2014  09:53 PM            42,336 numpy-1.9.1-py27_p0.json
12/10/2014  12:10 AM             6,037 openpyxl-1.8.5-py27_0.json
09/11/2014  09:21 PM            30,434 pandas-0.14.0-np18py27_0.json
12/10/2014  12:10 AM            30,866 pandas-0.14.1-np19py27_0.json
09/11/2014  09:22 PM             2,897 patsy-0.2.1-np18py27_0.json
12/10/2014  12:10 AM             3,531 patsy-0.3.0-np19py27_0.json
09/11/2014  09:22 PM               452 pep8-1.5.6-py27_0.json
12/10/2014  12:10 AM               452 pep8-1.5.7-py27_0.json
12/10/2014  12:10 AM             8,214 pil-1.1.7-py27_0.json
12/10/2014  12:10 AM            24,716 pip-1.5.6-py27_0.json
12/10/2014  12:10 AM               650 ply-3.4-py27_0.json
12/10/2014  12:10 AM             1,195 psutil-2.1.1-py27_0.json
09/11/2014  09:22 PM             3,394 py-1.4.20-py27_0.json
12/10/2014  12:10 AM             3,394 py-1.4.25-py27_0.json
12/10/2014  12:10 AM               447 pycosat-0.6.1-py27_0.json
12/10/2014  12:10 AM             1,917 pycparser-2.10-py27_0.json
09/11/2014  09:22 PM            15,570 pycrypto-2.6.1-py27_1.json
12/10/2014  12:10 AM            15,644 pycrypto-2.6.1-py27_2.json
12/10/2014  12:10 AM            57,089 pyface-4.4.0-py27_0.json
12/10/2014  12:10 AM             2,181 pyflakes-0.8.1-py27_0.json
12/10/2014  12:10 AM             8,567 pygments-1.6-py27_0.json
12/10/2014  12:10 AM             1,566 pyopenssl-0.14-py27_0.json
12/10/2014  12:10 AM               406 pyparsing-2.0.1-py27_0.json
12/10/2014  12:10 AM            55,710 pyqt-4.10.4-py27_0.json
12/10/2014  12:10 AM             5,204 pyreadline-2.0-py27_0.json
09/11/2014  09:22 PM            11,691 pytables-3.1.1-np18py27_0.json
12/10/2014  12:11 AM            11,881 pytables-3.1.1-np19py27_1.json
09/11/2014  09:22 PM             3,694 pytest-2.5.2-py27_0.json
12/10/2014  12:11 AM             3,694 pytest-2.6.3-py27_0.json
09/11/2014  09:20 PM           144,247 python-2.7.7-1.json
12/10/2014  12:06 AM           144,820 python-2.7.8-0.json
09/11/2014  09:22 PM            33,658 pytz-2014.3-py27_0.json
12/10/2014  12:11 AM            33,824 pytz-2014.7-py27_0.json
09/11/2014  09:22 PM            61,889 pywin32-218.4-py27_0.json
12/10/2014  12:11 AM            62,423 pywin32-219-py27_0.json
12/10/2014  12:11 AM             1,873 pyyaml-3.11-py27_0.json
09/11/2014  09:22 PM            11,771 pyzmq-14.3.0-py27_0.json
12/10/2014  12:11 AM            11,723 pyzmq-14.3.1-py27_0.json
12/10/2014  12:11 AM            10,799 requests-2.4.1-py27_0.json
12/09/2014  09:34 PM            11,097 requests-2.5.0-py27_0.json
12/10/2014  12:11 AM             8,104 rope-0.9.4-py27_1.json
09/11/2014  09:22 PM               584 runipy-0.1.0-py27_0.json
12/10/2014  12:11 AM               584 runipy-0.1.1-py27_0.json
09/11/2014  09:22 PM            38,257 scikit-image-0.10.0-np18py27_0.json
12/10/2014  12:11 AM            38,257 scikit-image-0.10.1-np19py27_0.json
12/10/2014  12:11 AM            44,362 scikit-learn-0.15.2-np19py27_0.json
10/21/2014  11:26 AM            44,719 scikit-learn-0.15.2-np19py27_p0.json
12/10/2014  12:12 AM            92,674 scipy-0.14.0-np19py27_0.json
09/11/2014  09:22 PM               441 setuptools-3.6-py27_0.json
12/10/2014  12:12 AM               441 setuptools-5.8-py27_0.json
09/11/2014  09:22 PM               382 six-1.6.1-py27_0.json
12/10/2014  12:12 AM               382 six-1.8.0-py27_0.json
12/10/2014  12:12 AM             3,332 sockjs-tornado-1.0.1-py27_0.json
09/11/2014  09:22 PM            26,509 sphinx-1.2.2-py27_0.json
12/10/2014  12:12 AM            37,596 sphinx-1.2.3-py27_0.json
09/11/2014  09:23 PM            53,971 spyder-2.3.0rc1-py27_0.json
12/10/2014  12:12 AM            81,493 spyder-2.3.1-py27_0.json
09/11/2014  09:23 PM               501 spyder-app-2.3.0rc1-py27_0.json
12/10/2014  12:12 AM               492 spyder-app-2.3.1-py27_0.json
09/11/2014  09:23 PM            21,711 sqlalchemy-0.9.4-py27_0.json
12/10/2014  12:12 AM            21,838 sqlalchemy-0.9.7-py27_0.json
12/10/2014  12:12 AM               706 ssl_match_hostname-3.4.0.2-py27_0.json
09/11/2014  09:23 PM            96,419 statsmodels-0.5.0-np18py27_1.json
12/10/2014  12:12 AM            96,211 statsmodels-0.5.0-np19py27_2.json
12/10/2014  12:12 AM           114,892 sympy-0.7.5-py27_0.json
12/10/2014  12:12 AM             1,475 toolz-0.7.0-py27_0.json
09/11/2014  09:23 PM             8,211 tornado-3.2.1-py27_0.json
12/10/2014  12:12 AM             8,584 tornado-4.0.2-py27_0.json
12/10/2014  12:12 AM            12,952 traits-4.4.0-py27_0.json
12/10/2014  12:12 AM            34,050 traitsui-4.4.0-py27_0.json
12/10/2014  12:12 AM               352 ujson-1.33-py27_0.json
12/10/2014  12:12 AM               521 unicodecsv-0.9.4-py27_0.json
09/11/2014  09:23 PM             6,994 werkzeug-0.9.6-py27_0.json
12/10/2014  12:12 AM             9,477 werkzeug-0.9.6-py27_1.json
12/10/2014  12:12 AM             1,377 xlrd-0.9.3-py27_0.json
09/11/2014  09:23 PM             3,407 xlsxwriter-0.5.5-py27_0.json
12/10/2014  12:12 AM             3,407 xlsxwriter-0.5.7-py27_0.json
09/11/2014  09:23 PM               829 xlwings-0.1.0-py27_0.json
12/10/2014  12:12 AM             1,321 xlwings-0.2.2-py27_0.json
12/10/2014  12:12 AM             5,104 xlwt-0.7.5-py27_0.json
12/10/2014  12:06 AM               240 _license-1.1-py27_0.json
             194 File(s)      3,859,734 bytes
               2 Dir(s)  291,483,545,600 bytes free
```

**Comment by asmeurer** [comment]
It seems you have multiple versions of many packages installed (or at least the metadata for multiple versions). I'm curious how you got into this state. Can you show me `conda list --revisions`. pip wouldn't have done this because it doesn't write anything to the conda-meta directory.

**Comment by swotai** [comment]
As attached.  In this case what;s the correct procedure to fix it?
```
C:\Anaconda>conda list --revisions
2014-09-14 10:39:42  (rev 0)
    _license-1.1-py27_0
    anaconda-2.0.1-np18py27_0
    argcomplete-0.6.7-py27_0
    astropy-0.3.2-np18py27_0
    atom-0.3.7-py27_0
    beautiful-soup-4.3.1-py27_0
    binstar-0.5.3-py27_0
    bitarray-0.8.1-py27_1
    blaze-0.5.0-np18py27_1
    blz-0.6.2-np18py27_0
    bokeh-0.4.4-np18py27_1
    boto-2.28.0-py27_0
    casuarius-1.1-py27_0
    cdecimal-2.3-py27_1
    chaco-4.4.1-np18py27_0
    colorama-0.2.7-py27_0
    conda-3.5.5-py27_0
    conda-build-1.3.5-py27_0
    configobj-5.0.5-py27_0
    cubes-0.10.2-py27_4
    cython-0.20.1-py27_0
    datashape-0.2.0-np18py27_1
    dateutil-2.1-py27_2
    docutils-0.11-py27_0
    dynd-python-0.6.2-np18py27_0
    enable-4.3.0-np18py27_2
    enaml-0.9.1-py27_1
    flask-0.10.1-py27_1
    future-0.12.1-py27_0
    gevent-1.0.1-py27_0
    gevent-websocket-0.9.3-py27_0
    greenlet-0.4.2-py27_0
    grin-1.2.1-py27_2
    h5py-2.3.0-np18py27_0
    ipython-2.1.0-py27_2
    ipython-notebook-2.1.0-py27_0
    ipython-qtconsole-2.1.0-py27_0
    itsdangerous-0.24-py27_0
    jdcal-1.0-py27_0
    jinja2-2.7.2-py27_0
    kiwisolver-0.1.2-py27_0
    launcher-0.1.5-py27_0
    libpython-1.0-py27_1
    llvmpy-0.12.6-py27_0
    lxml-3.3.5-py27_0
    markupsafe-0.18-py27_1
    matplotlib-1.3.1-np18py27_2
    menuinst-1.0.3-py27_0
    mingw-4.7-1
    mock-1.0.1-py27_0
    multipledispatch-0.4.3-py27_0
    networkx-1.8.1-py27_0
    nltk-2.0.4-np18py27_0
    nose-1.3.3-py27_0
    numba-0.13.2-np18py27_0
    numexpr-2.3.1-np18py27_0
    numpy-1.8.1-py27_0
    openpyxl-1.8.5-py27_0
    pandas-0.14.0-np18py27_0
    patsy-0.2.1-np18py27_0
    pep8-1.5.6-py27_0
    pil-1.1.7-py27_0
    pip-1.5.6-py27_0
    ply-3.4-py27_0
    psutil-2.1.1-py27_0
    py-1.4.20-py27_0
    pycosat-0.6.1-py27_0
    pycparser-2.10-py27_0
    pycrypto-2.6.1-py27_1
    pyface-4.4.0-py27_0
    pyflakes-0.8.1-py27_0
    pygments-1.6-py27_0
    pyparsing-2.0.1-py27_0
    pyqt-4.10.4-py27_0
    pyreadline-2.0-py27_0
    pytables-3.1.1-np18py27_0
    pytest-2.5.2-py27_0
    python-2.7.7-1
    pytz-2014.3-py27_0
    pywin32-218.4-py27_0
    pyyaml-3.11-py27_0
    pyzmq-14.3.0-py27_0
    requests-2.3.0-py27_0
    rope-0.9.4-py27_1
    runipy-0.1.0-py27_0
    scikit-image-0.10.0-np18py27_0
    scikit-learn-0.14.1-np18py27_2
    scipy-0.14.0-np18py27_0
    setuptools-3.6-py27_0
    six-1.6.1-py27_0
    sphinx-1.2.2-py27_0
    spyder-2.3.0rc1-py27_0
    spyder-app-2.3.0rc1-py27_0
    sqlalchemy-0.9.4-py27_0
    ssl_match_hostname-3.4.0.2-py27_0
    statsmodels-0.5.0-np18py27_1
    sympy-0.7.5-py27_0
    tornado-3.2.1-py27_0
    traits-4.4.0-py27_0
    traitsui-4.4.0-py27_0
    ujson-1.33-py27_0
    werkzeug-0.9.6-py27_0
    xlrd-0.9.3-py27_0
    xlsxwriter-0.5.5-py27_0
    xlwings-0.1.0-py27_0
    xlwt-0.7.5-py27_0

2014-09-14 10:39:47  (rev 1)
     conda  {3.5.5 -> 3.6.4}
     requests  {2.3.0 -> 2.4.1}

2014-10-21 11:23:38  (rev 2)
     conda  {3.6.4 -> 3.7.1}
     requests  {2.4.1 -> 2.4.3}

2014-10-21 11:26:02  (rev 3)
     llvmpy  {0.12.6 -> 0.12.7}
     nose  {1.3.3 -> 1.3.4}
     numba  {0.13.2 -> 0.14.0}
     numexpr  {2.3.1 -> 2.3.1}
     numpy  {1.8.1 -> 1.9.0}
     scikit-learn  {0.14.1 -> 0.15.2}
     scipy  {0.14.0 -> 0.14.0}
    +accelerate-1.7.0
    +cudatoolkit-6.0
    +mkl-11.1
    +mkl-rt-11.1
    +mkl-service-1.0.0
    +mklfft-1.0
    +numbapro-0.15.0
    +numbapro_cudalib-0.1

2014-10-21 11:26:52  (rev 4)
    +iopro-1.6.7

2014-10-23 14:13:30  (rev 5)
    +gdal-1.11.0

2014-12-09 20:34:27  (rev 6)
     conda  {3.7.1 -> 3.7.3}
     requests  {2.4.3 -> 2.5.0}

2014-12-09 20:53:08  (rev 7)
     accelerate  {1.7.0 -> 1.8.0}
     numba  {0.14.0 -> 0.15.1}
     numbapro  {0.15.0 -> 0.16.0}
     numpy  {1.9.0 -> 1.9.1}
```

**Comment by asmeurer** [comment]
Sorry, I guess what I really want is the contents of the file C:\Anaconda\conda-meta\history. `conda list --revisions` doesn't show everything (in particular, it doesn't show the commands that were run).

**Comment by asmeurer** [comment]
As to fixing this, I doubt there will be a clean way to do it. You may need to reinstall Anaconda.
