### ISSUE TITLE
`conda env list` returning "TypeError: expected str, bytes or os.PathLike object, not NoneType"

### ISSUE THREAD

**Issue by kwt5152** [conda/conda#12063]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

While trying to run `conda env list` as root I receive the following error message.

```
(base) root@host:~# conda env list

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda_env/cli/main_list.py", line 36, in execute
        info_dict = {'envs': list_all_known_prefixes()}
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda/core/envs_manager.py", line 84, in list_all_known_prefixes
        environments_txt_file = get_user_environments_txt_file(home_dir)
      File "/usr/local/miniconda3/lib/python3.9/site-packages/conda/core/envs_manager.py", line 24, in get_user_environments_txt_file
        return expand(join(userhome, '.conda', 'environments.txt'))
      File "/usr/local/miniconda3/lib/python3.9/posixpath.py", line 76, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /usr/local/miniconda3/bin/conda-env list`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/usr/local/miniconda3/bin/conda
             CONDA_PREFIX=/usr/local/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/usr/local/miniconda3/bin/python
               CONDA_ROOT=/usr/local/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/usr/local/miniconda3/bin:/usr/local/miniconda3/condabin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/
                          games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             SUDO_COMMAND=/usr/bin/su
                 SUDO_GID=123456
                 SUDO_UID=123456
                SUDO_USER=abc123

     active environment : base
    active env location : /usr/local/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/miniconda3  (writable)
      conda av data dir : /usr/local/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.12 Linux/5.15.0-52-generic ubuntu/20.04.5 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

If I exit out of the root user and run `conda env list` as a standard user then it returns a list of the environments.

```
(base) abc123@host:~$ conda env list
# conda environments:
#
base                  *  /usr/local/miniconda3
asp                      /usr/local/miniconda3/envs/asp
```

I tried deleting the .conda directory and .condarc file in root's home directory, but that had no effect. Diving deeper into the error message, I can't figure out why the `join` function in file "/usr/local/miniconda3/lib/python3.9/posixpath.py" is returning "TypeError: expected str, bytes or os.PathLike object, not NoneType". The values passed to that function are `userhome, '.conda', 'environments.txt'` where `userhome='~'`.

As far as I can tell, there doesn't appear to be anything standing in the way of `conda env list` from working. Please let me know if there's any additional information I can provide.

### Conda Info

```shell
(base) root@host:~# conda info

     active environment : base
    active env location : /usr/local/miniconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __linux=5.15.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/miniconda3  (writable)
      conda av data dir : /usr/local/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.12 Linux/5.15.0-52-generic ubuntu/20.04.5 glibc/2.31
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
(base) root@host:~# conda config --show-sources

(base) root@host:~#
```

### Conda list

```shell
(base) root@host:~# conda list --show-channel-urls
# packages in environment at /usr/local/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
ca-certificates           2022.10.11           h06a4308_0    defaults
certifi                   2022.9.24        py39h06a4308_0    defaults
cffi                      1.15.1           py39h74dc2b5_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     22.9.0           py39h06a4308_0    defaults
conda-package-handling    1.9.0            py39h5eee18b_1    defaults
cryptography              38.0.1           py39h9ce1e76_0    defaults
idna                      3.4              py39h06a4308_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
ncurses                   6.3                  h5eee18b_3    defaults
openssl                   1.1.1s               h7f8727e_0    defaults
pip                       22.2.2           py39h06a4308_0    defaults
pycosat                   0.6.4            py39h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.12               h12debd9_0    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.28.1           py39h06a4308_0    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
setuptools                65.5.0           py39h06a4308_0    defaults
sqlite                    3.39.3               h5082296_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0           py39h06a4308_0    defaults
tqdm                      4.64.1           py39h06a4308_0    defaults
tzdata                    2022f                h04d1e81_0    defaults
urllib3                   1.26.12          py39h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.6                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
```

**Comment by travishathaway** [comment]
Hi @kwt5152,

Thank you for filing this issue! Unfortunately, this is off-topic for this repository. If you are still encountering this issue please reopen in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) where Navigator issues are addressed.

We will be closing this issue now.

**Comment by travishathaway** [comment]
Hi @kwt5152,

Disregard the earlier comment! (Wrong issue 😅). I'm still looking into this issue in particular. I'm currently having a hard time recreating exactly what you have encountered.

Myself or someone else will provide an update once we know more. I appreciate your patience.

**Comment by kevbo423** [comment]
Thanks Travis! Please let me know if there is anything I can do to help.

**Comment by kwt5152** [comment]
Thanks @travishathaway! Please let me know if there is anything I can do to help.

**Comment by travishathaway** [comment]
Hi @kwt5152,

Can you tell me exactly how you installed `conda`? It looks like it's in a system location: `/usr/local/miniconda3`. Do you remember if you installed this with the root user?

Thank you.

**Comment by kwt5152** [comment]
Good afternoon, @travishathaway.

I installed miniconda as `root` with the following commands:

```
wget https://repo.anaconda.com/miniconda/Miniconda3-py39_4.12.0-Linux-x86_64.sh
sudo bash ./Miniconda3-py39_4.12.0-Linux-x86_64.sh
```

I then specified the installation directory as /usr/local/miniconda3 as this was an installation that was going to be shared by multiple users of the machine.

**Comment by kwt5152** [comment]
Hi @travishathaway.

I took a look at the output of those commands and there are indeed entries with `pw_dir` set as `None`. These entries are coming from LDAP netgroups we have configured that control access to the machine. Here are the full values:

```
pwd.struct_passwd(pw_name='+@itadmins', pw_passwd=None, pw_uid=0, pw_gid=0, pw_gecos=None, pw_dir=None, pw_shell=None),
pwd.struct_passwd(pw_name='+@fakenameusers', pw_passwd=None, pw_uid=0, pw_gid=0, pw_gecos=None, pw_dir=None, pw_shell=None)]
```

Thanks for working on this and figuring out what the issue was! Much appreciated!
