### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by newjavakid** [conda/conda#1211]
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func
    try:
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 387, in install
    regex = '^(%s)$' % '|'.join(spec_names)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 587, in execute_actions
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 571, in execute_plan
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 574, in unlink
    'type': link_name_map.get(linktype)}
IOError: [Errno 2] No such file or directory: 'C:\Anaconda\conda-meta\conda-3.7.0-py27_0.json'

**Comment by asmeurer** [comment]
Same (or similar) issue as https://github.com/conda/conda/issues/1122,  https://github.com/conda/conda/issues/1031, https://github.com/conda/conda/issues/973, and https://github.com/conda/conda/issues/1201.
