### ISSUE TITLE
PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in C:\Users\user\AppData\Local\Programs\Python\Python39

### ISSUE THREAD

**Issue by Bilalraw** [conda/conda#12117]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

my problem started when I tried to use` conda create -n nam python `and got `conda.exceptions.CondaRuntimeError:`
```
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2015_runtime-14.0.25420  |                0         2.0 MB
    vc-14                      |                0          703 B
    python-3.6.2               |                0        31.5 MB
    certifi-2016.2.28          |           py36_0         214 KB
    wheel-0.29.0               |           py36_0         129 KB
    wincertstore-0.2           |           py36_0          14 KB
    setuptools-36.4.0          |           py36_1         534 KB
    pip-9.0.1                  |           py36_1         1.7 MB
    ------------------------------------------------------------
                                           Total:        36.0 MB

The following NEW packages will be INSTALLED:

    certifi:        2016.2.28-py36_0
    pip:            9.0.1-py36_1
    python:         3.6.2-0
    setuptools:     36.4.0-py36_1
    vc:             14-0
    vs2015_runtime: 14.0.25420-0
    wheel:          0.29.0-py36_0
    wincertstore:   0.2-py36_0

Proceed ([y]/n)?

Fetching packages ...
vs2015_runtime 100% |###############################| Time: 0:00:00   3.63 MB/s
vc-14-0.tar.bz 100% |###############################| Time: 0:00:00 140.66 kB/s
python-3.6.2-0 100% |###############################| Time: 0:00:05   5.56 MB/s
certifi-2016.2 100% |###############################| Time: 0:00:00   1.18 MB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00   1.02 MB/s
wincertstore-0 100% |###############################| Time: 0:00:00   4.84 MB/s
setuptools-36. 100% |###############################| Time: 0:00:00   1.64 MB/s
pip-9.0.1-py36 100% |###############################| Time: 0:00:01   1.68 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred.                                        |   0%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.12.final.0
       requests version : 2.28.1
       root environment : C:\Users\user\AppData\Local\Programs\Python\Python39  (writable)
    default environment : C:\Users\user\AppData\Local\Programs\Python\Python39
       envs directories : C:\Users\user\AppData\Local\Programs\Python\Python39\envs
          package cache : C:\Users\user\AppData\Local\Programs\Python\Python39\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

`$ C:\Users\user\miniconda3\Scripts\conda-script.py create -n nam python`

```
    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\install.py", line 201, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\user\\AppData\\Local\\Programs\\Python\\Python39\\pkgs\\vs2015_runtime-14.0.25420-0\\info\\has_prefix'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\install.py", line 209, in yield_lines
        raise StopIteration
    StopIteration

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\install.py", line 943, in link
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\install.py", line 248, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\install.py", line 248, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\install.py", line 247, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration
```

 my version is conda 4.2 and I discovered that it's no longer supported, so  I used `conda update conda` and got 
`PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in C:\Users\user\AppData\Local\Programs\Python\Python39`
, tried to reinstall anaconda and still got the same error.

### Conda Info

```shell
Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.12.final.0
       requests version : 2.28.1
       root environment : C:\Users\user\AppData\Local\Programs\Python\Python39  (writable)
    default environment : C:\Users\user\AppData\Local\Programs\Python\Python39
       envs directories : C:\Users\user\AppData\Local\Programs\Python\Python39\envs
          package cache : C:\Users\user\AppData\Local\Programs\Python\Python39\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

### Conda Config

```shell
'no output'
```

### Conda list

```shell
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
```

**Comment by travishathaway** [comment]
Hi @Bilalraw,

Thanks for submitting this bug. At this point I would recommend updating conda by install it again via the miniconda installers available here:

- https://docs.conda.io/en/latest/miniconda.html

At this point, we cannot provide support for updating from such old versions of a conda; therefore, I will be closing this issue.
