### ISSUE TITLE
`RuntimeError ‘failed to find interpreter for Builtin discover of python_spec='python3.1' when trying to run pre-commit in conda environment`

### ISSUE THREAD

**Issue by DeaMariaLeon** [conda/conda#12129]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The conda environment is activated, I try to commit file changes with git, so pre-commit is run:

```
git commit -a    
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/pycqa/flake8.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy:pytest==6.2.4.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/bin/python3.1', '-mvirtualenv', '/Users/dealeon/.cache/pre-commit/repof2a00erb/py_env-python3.1', '-p', 'python3.1')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec=‘python3.1'
```

### Conda Info

```shell
active environment : base
    active env location : /Users/dealeon/Anaconda/anaconda3
            shell level : 1
       user config file : /Users/dealeon/.condarc
 populated config files : /Users/dealeon/.condarc
          conda version : 22.9.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/dealeon/Anaconda/anaconda3  (writable)
      conda av data dir : /Users/dealeon/Anaconda/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dealeon/Anaconda/anaconda3/pkgs
                          /Users/dealeon/.conda/pkgs
       envs directories : /Users/dealeon/Anaconda/anaconda3/envs
                          /Users/dealeon/.conda/envs
               platform : osx-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.7.6 Darwin/21.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/dealeon/.condarc <==
ssl_verify: True
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at /Users/dealeon/Anaconda/anaconda3/envs/sklworkshop:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appnope                   0.1.2           py310hecd8cb5_1001    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
attrs                     21.4.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    defaults
black                     22.1.0             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-compiler                1.3.0                h0d85af4_0    conda-forge
ca-certificates           2022.07.19           hecd8cb5_0    defaults
cctools                   973.0.1              h37c8cb8_9    conda-forge
cctools_osx-64            973.0.1              hb41342b_9    conda-forge
certifi                   2022.9.24       py310hecd8cb5_0    defaults
cfgv                      3.3.1                    pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
clang                     11.1.0               h694c41f_1    conda-forge
clang-11                  11.1.0          default_he082bbe_1    conda-forge
clang_osx-64              11.1.0               hc8532ff_7    conda-forge
clangxx                   11.1.0          default_he082bbe_1    conda-forge
clangxx_osx-64            11.1.0               h2c55bc3_7    conda-forge
click                     8.0.4           py310h2ec42d9_0    conda-forge
compiler-rt               11.1.0               h654b07c_0    conda-forge
compiler-rt_osx-64        11.1.0               h8c5fa43_0    conda-forge
compilers                 1.3.0                h694c41f_0    conda-forge
cxx-compiler              1.3.0                h940c156_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.28         py310hba3363e_0    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
debugpy                   1.5.1           py310he9d5cce_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
distlib                   0.3.4                    pypi_0    pypi
docutils                  0.17.1                   pypi_0    pypi
entrypoints               0.4             py310hecd8cb5_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
filelock                  3.7.1                    pypi_0    pypi
flake8                    4.0.1                    pypi_0    pypi
fonttools                 4.29.1          py310he24745e_0    conda-forge
fortran-compiler          1.3.0                h6818c3e_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
gfortran                  9.3.0               h768ea0c_15    conda-forge
gfortran_impl_osx-64      9.3.0               h9cc0e5e_23    conda-forge
gfortran_osx-64           9.3.0               h18f7dce_15    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
identify                  2.5.1                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imageio                   2.16.1                   pypi_0    pypi
imagesize                 1.3.0                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
ipykernel                 6.15.2          py310hecd8cb5_0    defaults
ipython                   8.4.0           py310hecd8cb5_0    defaults
isl                       0.22.1               hb1e8313_2    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1          py310hecd8cb5_1    defaults
jinja2                    3.0.3                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9e                   h0d85af4_0    conda-forge
jupyter_client            7.3.4           py310hecd8cb5_0    defaults
jupyter_core              4.11.1          py310hecd8cb5_0    defaults
kiwisolver                1.3.2           py310h2fea185_1    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
ld64                      609                  h356cf98_9    conda-forge
ld64_osx-64               609                  h6adca69_9    conda-forge
ldid                      2.1.2                h6a69015_3    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libclang-cpp11.1          11.1.0          default_he082bbe_1    conda-forge
libclang-cpp12            12.0.0          default_hfcad0e5_2    defaults
libcxx                    12.0.1               habf9029_1    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran-devel_osx-64  9.3.0               h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libllvm12                 12.0.0               h9b2ccf5_3    defaults
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libsodium                 1.0.18               h1de35cc_0    defaults
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libzlib                   1.2.11            h9173be1_1013    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
llvm-tools                11.1.0               hd011deb_3    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.1.0                    pypi_0    pypi
matplotlib                3.5.1           py310h2ec42d9_0    conda-forge
matplotlib-base           3.5.1           py310hfc59cd6_0    conda-forge
matplotlib-inline         0.1.6           py310hecd8cb5_0    defaults
mccabe                    0.6.1           py310hecd8cb5_1    defaults
mpc                       1.2.1                hbb51d92_0    conda-forge
mpfr                      4.1.0                h0f52abe_1    conda-forge
munkres                   1.1.4                    pypi_0    pypi
mypy_extensions           0.4.3           py310h2ec42d9_4    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
nest-asyncio              1.5.5           py310hecd8cb5_0    defaults
networkx                  2.7.1                    pypi_0    pypi
nodeenv                   1.6.0                    pypi_0    pypi
numpy                     1.22.3          py310hb608527_0    conda-forge
numpydoc                  1.2                      pypi_0    pypi
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   3.0.0                h0d85af4_2    conda-forge
packaging                 21.3                     pypi_0    pypi
pandas                    1.4.1           py310hdd25497_0    conda-forge
parso                     0.8.3              pyhd3eb1b0_0    defaults
pathspec                  0.9.0              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.0.1           py310h382dc3b_2    conda-forge
pip                       22.0.4                   pypi_0    pypi
platformdirs              2.5.1              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0           py310h2ec42d9_2    conda-forge
pre-commit                2.19.0                   pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
psutil                    5.9.0           py310hca72f7f_0    defaults
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
py                        1.11.0                   pypi_0    pypi
pycodestyle               2.7.0                    pypi_0    pypi
pyflakes                  2.3.1                    pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyparsing                 3.0.7                    pypi_0    pypi
pytest                    7.0.1           py310h2ec42d9_0    conda-forge
python                    3.10.2          hea1dfa3_3_cpython    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.10                    2_cp310    conda-forge
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     23.2.0          py310he9d5cce_0    defaults
readline                  8.1                  h05e3726_0    conda-forge
requests                  2.27.1                   pypi_0    pypi
scikit-image              0.19.2                   pypi_0    pypi
scikit-learn              1.1.dev0                  dev_0    <develop>
scipy                     1.8.0           py310h47774c9_1    conda-forge
seaborn                   0.11.2                   pypi_0    pypi
setuptools                60.9.3          py310h2ec42d9_0    conda-forge
sigtool                   0.1.3                h88f4db0_0    conda-forge
six                       1.16.0                   pypi_0    pypi
snowballstemmer           2.2.0                    pypi_0    pypi
sphinx                    4.4.0                    pypi_0    pypi
sphinx-gallery            0.10.1                   pypi_0    pypi
sphinx-prompt             1.5.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sphinxext-opengraph       0.6.2                    pypi_0    pypi
sqlite                    3.37.0               h23a322b_0    conda-forge
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tapi                      1100.0.11            h9ce4665_0    conda-forge
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.2.9                 pypi_0    pypi
tk                        8.6.12               h5dbffcc_0    conda-forge
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.1             py310he24745e_2    conda-forge
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
typed-ast                 1.5.2           py310he24745e_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2021e                he74cb21_0    conda-forge
unicodedata2              14.0.0          py310he24745e_0    conda-forge
urllib3                   1.26.8                   pypi_0    pypi
virtualenv                20.14.1                  pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.37.1                   pypi_0    pypi
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zeromq                    4.3.4                h23ab428_0    defaults
zlib                      1.2.11            h9173be1_1013    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

### Additional Context

cat pre-commit.log
### version information

```
pre-commit version: 2.19.0
git --version: git version 2.24.3 (Apple Git-128)
sys.version:
    3.10.2 | packaged by conda-forge | (main, Feb  1 2022, 19:32:15) [Clang 11.1.0 ]
sys.executable: /Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/bin/python3.1
os.name: posix
sys.platform: darwin
```

### error information

```
An unexpected error has occurred: CalledProcessError: command: ('/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/bin/python3.1', '-mvirtualenv', '/Users/dealeon/.cache/pre-commit/repof2a00erb/py_env-python3.1', '-p', 'python3.1')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.1'
    
stderr: (none)
```

```
Traceback (most recent call last):
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/error_handler.py", line 73, in error_handler
    yield
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/main.py", line 361, in main
    return hook_impl(
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/commands/hook_impl.py", line 238, in hook_impl
    return retv | run(config, store, ns)
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/commands/run.py", line 414, in run
    install_hook_envs(to_install, store)
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/repository.py", line 223, in install_hook_envs
    _hook_install(hook)
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/repository.py", line 79, in _hook_install
    lang.install_environment(
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/languages/python.py", line 219, in install_environment
    cmd_output_b(*venv_cmd, cwd='/')
  File "/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/lib/python3.10/site-packages/pre_commit/util.py", line 146, in cmd_output_b
    raise CalledProcessError(returncode, cmd, retcode, stdout_b, stderr_b)
pre_commit.util.CalledProcessError: command: ('/Users/dealeon/Anaconda/anaconda3/envs/sklworkshop/bin/python3.1', '-mvirtualenv', '/Users/dealeon/.cache/pre-commit/repof2a00erb/py_env-python3.1', '-p', 'python3.1')
return code: 1
expected return code: 0
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.1'
    
stderr: (none)

**Comment by travishathaway** [comment]
Hi @DeaMariaLeon,

Thanks for submitting this issue. I believe that this is an error related to pre-commit and not conda. Unfortunately, we cannot provide support for anything related to pre-commit; therefore, I will be closing this issue.

If you believe this really is a bug related to conda, I invite you to open this issue again and provide your justification for doing so.

Again, we appreciate you taking this time to file this issue, but we simply believe it is in the wrong place.
