### ISSUE TITLE
TypeError: cannot unpack non-iterable DataPipeline object while using create_individual_features.py

### ISSUE THREAD

**Issue by lorethan22** [conda/conda#12130]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The call of "create_individual_features.py" aborts with the following error message:
 "I1128 12:24:16.870391 23456247859008 templates.py:857] Using precomputed obsolete pdbs /data/a/alphafold_db/pdb_mmcif/obsolete.dat.
Traceback (most recent call last):
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/bin/create_individual_features.py", line 286, in <module>
    app.run(main)
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/lib/python3.7/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/data/a/anaconda3/envs/AlphaPulldown0.22.2/bin/create_individual_features.py", line 252, in main
    pipeline, flags_dict = create_pipeline()
TypeError: cannot unpack non-iterable DataPipeline object"

Here ist the full call of create_individual_features.py
(AlphaPulldown0.22.2) [user@apd_usertest]$ create_individual_features.py --fasta_paths=baits.fasta,example_1_sequences_shorter.fasta --data_dir=/data/a/alphafold_db --save_msa_files=True --output_dir=/data/a/user/apd_usertest --use_precomputed_msas=False --max_template_date=2022-10-01  --skip_existing=False

With AlphaPulldown 0.22.1 there was no issue with create_individual_features.py. Wenn I replace the old version of create_individual_features.py it still works.

### Conda Info

```shell
(AlphaPulldown0.22.2) [user@anaconda3]$ conda info

     active environment : AlphaPulldown0.22.2
    active env location : /data/a/anaconda3/envs/AlphaPulldown0.22.2
            shell level : 2
       user config file : /home/user/.condarc
 populated config files :
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __linux=5.4.102=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /data/a/anaconda3  (writable)
      conda av data dir : /data/a/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/a/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /data/a/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.4.102-1.el7.elrepo.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1296:1296
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
(AlphaPulldown0.22.2) [testuser@halime anaconda3]$ conda list --show-channel-urls
# packages in environment at /data/a/anaconda3/envs/AlphaPulldown0.22.2:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
absl-py                   0.15.0                   pypi_0    pypi
alphapulldown             0.22.2                   pypi_0    pypi
anyio                     3.6.2                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0                   pypi_0    pypi
argon2-cffi-bindings      21.2.0                   pypi_0    pypi
asn1crypto                1.5.1              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3                    pypi_0    pypi
attrs                     22.1.0                   pypi_0    pypi
babel                     2.11.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
beautifulsoup4            4.11.1                   pypi_0    pypi
biopython                 1.78             py37h7f8727e_0    defaults
blas                      1.0                    openblas    defaults
bleach                    5.0.1                    pypi_0    pypi
boost                     1.78.0           py37h48bf904_0    conda-forge
boost-cpp                 1.78.0               h75c5d50_1    conda-forge
brotli                    1.0.9                h166bdaf_8    conda-forge
brotli-bin                1.0.9                h166bdaf_8    conda-forge
brotlipy                  0.7.0           py37h540881e_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
ca-certificates           2022.10.11           h06a4308_0    defaults
cached-property           1.5.2                    pypi_0    pypi
cachetools                5.2.0                    pypi_0    pypi
cctbx-base                2022.10          py37h3b6d006_0    conda-forge
certifi                   2022.9.24        py37h06a4308_0    defaults
cffi                      1.14.4           py37h11fe52a_0    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
contextlib2               21.6.0                   pypi_0    pypi
cryptography              2.5              py37hb7f436b_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cython                    0.29.32          py37hd23a5d3_0    conda-forge
debugpy                   1.6.3                    pypi_0    pypi
decorator                 5.1.1                    pypi_0    pypi
defusedxml                0.7.1                    pypi_0    pypi
dm-haiku                  0.0.4                    pypi_0    pypi
dm-tree                   0.1.6                    pypi_0    pypi
entrypoints               0.4                      pypi_0    pypi
fastjsonschema            2.16.2                   pypi_0    pypi
fftw3f                    3.3.4                         2    omnia
flatbuffers               1.12                     pypi_0    pypi
fonttools                 4.38.0           py37h540881e_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
future                    0.18.2           py37h89c1867_5    conda-forge
gast                      0.4.0                    pypi_0    pypi
google-auth               2.14.1                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.34.1                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hhsuite                   3.3.0           py37pl5321h675a0cb_5    bioconda
hmmer                     3.3.2                h87f3376_2    bioconda
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.1.0                    pypi_0    pypi
importlib-resources       5.8.0                    pypi_0    pypi
ipykernel                 6.16.2                   pypi_0    pypi
ipython                   7.34.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                8.0.2                    pypi_0    pypi
jax                       0.3.9                    pypi_0    pypi
jaxlib                    0.3.7+cuda11.cudnn82          pypi_0    pypi
jedi                      0.18.2                   pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
jpeg                      9e                   h166bdaf_2    conda-forge
json5                     0.9.10                   pypi_0    pypi
jsonschema                4.17.1                   pypi_0    pypi
jupyter-client            7.4.7                    pypi_0    pypi
jupyter-core              4.11.2                   pypi_0    pypi
jupyter-server            1.23.3                   pypi_0    pypi
jupyterlab                3.5.0                    pypi_0    pypi
jupyterlab-pygments       0.2.2                    pypi_0    pypi
jupyterlab-server         2.16.3                   pypi_0    pypi
jupyterlab-widgets        3.0.3                    pypi_0    pypi
kalign2                   2.04                 hec16e2b_3    bioconda
keras-nightly             2.5.0.dev2021032900          pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.4.4            py37h7cecad7_0    conda-forge
lcms2                     2.14                 h6ed2654_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_8    conda-forge
libbrotlidec              1.0.9                h166bdaf_8    conda-forge
libbrotlienc              1.0.9                h166bdaf_8    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglu                    9.0.0             he1b5a44_1001    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
liblapack                 3.9.0           16_linux64_openblas    conda-forge
libnsl                    2.0.0                h5eee18b_0    defaults
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libsvm                    3.16                          2    bioconda
libtiff                   4.4.0                h55922b4_4    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
markdown                  3.4.1                    pypi_0    pypi
markupsafe                2.1.1                    pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
matplotlib-base           3.5.3            py37hf590b9c_0    defaults
matplotlib-inline         0.1.6                    pypi_0    pypi
mistune                   2.0.4                    pypi_0    pypi
ml-collections            0.1.0                    pypi_0    pypi
mrcfile                   1.4.3              pyhd8ed1ab_0    conda-forge
munkres                   1.0.7                    py37_0    omnia
nbclassic                 0.4.8                    pypi_0    pypi
nbclient                  0.7.0                    pypi_0    pypi
nbconvert                 7.2.5                    pypi_0    pypi
nbformat                  5.4.0                    pypi_0    pypi
ncurses                   6.3                  h27087fc_1    conda-forge
nest-asyncio              1.5.6                    pypi_0    pypi
notebook                  6.5.2                    pypi_0    pypi
notebook-shim             0.2.2                    pypi_0    pypi
numpy                     1.19.4                   pypi_0    pypi
numpy-base                1.21.5           py37h1e6e340_3    defaults
oauthlib                  3.2.2                    pypi_0    pypi
openjpeg                  2.5.0                h7d73246_1    conda-forge
openmm                    7.4.2           py37_cuda101_rc_1    omnia
openssl                   1.0.2u               h516909a_0    conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.1.4                    pypi_0    pypi
pandocfilters             1.5.0                    pypi_0    pypi
parso                     0.8.3                    pypi_0    pypi
pdbfixer                  1.6                        py_1    omnia
perl                      5.32.1          0_h5eee18b_perl5    defaults
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    9.2.0            py37h850a105_2    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10                   pypi_0    pypi
prometheus-client         0.15.0                   pypi_0    pypi
prompt-toolkit            3.0.33                   pypi_0    pypi
protobuf                  3.20.3                   pypi_0    pypi
psutil                    5.9.3            py37h540881e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0                    pypi_0    pypi
py3dmol                   1.8.0                    pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.13.0                   pypi_0    pypi
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.2                   pypi_0    pypi
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.0             hd21baee_1006    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytz                      2022.6                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     24.0.1                   pypi_0    pypi
readline                  7.0               hf8c457e_1001    conda-forge
reportlab                 3.5.68           py37h69800bb_1    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.9                      pypi_0    pypi
scipy                     1.7.3            py37hf2a6cf1_0    conda-forge
send2trash                1.8.0                    pypi_0    pypi
setuptools                65.5.1             pyhd8ed1ab_0    conda-forge
six                       1.15.0                   pypi_0    pypi
sniffio                   1.3.0                    pypi_0    pypi
soupsieve                 2.3.2.post1              pypi_0    pypi
sqlite                    3.28.0               h8b20d00_0    conda-forge
tabulate                  0.9.0                    pypi_0    pypi
tensorboard               2.11.0                   pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.5.0                    pypi_0    pypi
tensorflow-estimator      2.5.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.17.0                   pypi_0    pypi
tinycss2                  1.2.1                    pypi_0    pypi
tk                        8.6.12               h27826a3_0    conda-forge
tomli                     2.0.1                    pypi_0    pypi
tornado                   6.2                      pypi_0    pypi
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 5.5.0                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
typing_extensions         4.3.0            py37h06a4308_0    defaults
unicodedata2              14.0.0           py37h540881e_1    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.4.2                    pypi_0    pypi
werkzeug                  2.2.2                    pypi_0    pypi
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
widgetsnbextension        4.0.3                    pypi_0    pypi
wrapt                     1.12.1                   pypi_0    pypi
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.11.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

**Comment by lorethan22** [comment]
Wrong section.
