### ISSUE TITLE
conda init tries to modify files in ${CONDA_DIR} on fresh install

### ISSUE THREAD

**Issue by holzman** [conda/conda#12159]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This is relevant for system-installed conda.

In conda 4.14.0 and below, on a fresh install, running `conda init` modified only user-writable files.
As of conda 22.9.0, it tries to modify files in `${CONDA_DIR}`.

Dockerfile for reproducing:

```
FROM centos:7
USER root
RUN adduser -m user
RUN yum -y install sudo  wget
RUN wget --quiet https://github.com/conda-forge/miniforge/releases/download/22.9.0-0/Mambaforge-22.9.0-0-Linux-x86_64.sh -O /tmp/mf-22.9.sh
RUN wget --quiet https://github.com/conda-forge/miniforge/releases/download/4.14.0-2/Mambaforge-4.14.0-2-Linux-x86_64.sh -O /tmp/mf-4.14.sh

RUN /bin/bash /tmp/mf-22.9.sh -f -b -p /opt/conda-22.9
RUN /bin/bash /tmp/mf-4.14.sh -f -b -p /opt/conda-4.14

USER user
WORKDIR /home/user
```

```
[user@94b309a7af15 ~]$ /opt/conda-4.14/bin/conda init -d | grep modified
modified      /home/user/.bashrc
[user@94b309a7af15 ~]$ /opt/conda-22.9/bin/conda init -d | grep modified
modified      /opt/conda-22.9/condabin/conda
modified      /opt/conda-22.9/bin/conda
modified      /opt/conda-22.9/bin/conda-env
modified      /home/user/.bashrc
```

Obviously one can run `conda init` as root, but this change in behavior seems unintentional.

If you run `conda init` as a user, you get the following error:  (We encountered this in our JupyterHub deployment, and the [sudo] prompt wasn't shown. making this a bit more confusing!)

```
[sudo] password for user:
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/cli/main_init.py", line 50, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/core/initialize.py", line 119, in initialize
        run_plan_elevated(plan2)
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/core/initialize.py", line 688, in run_plan_elevated
        result = subprocess_call(
      File "/opt/conda-22.9/lib/python3.10/site-packages/conda/gateways/subprocess.py", line 100, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
      File "/opt/conda-22.9/lib/python3.10/subprocess.py", line 1152, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
      File "/opt/conda-22.9/lib/python3.10/subprocess.py", line 1983, in _communicate
        input_view = memoryview(self._input)
    TypeError: memoryview: a bytes-like object is required, not 'str'
```

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
[user@94b309a7af15 ~]$ /opt/conda-22.9/bin/conda info

     active environment : None
       user config file : /home/user/.condarc
 populated config files : /opt/conda-22.9/.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda-22.9  (read only)
      conda av data dir : /opt/conda-22.9/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda-22.9/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/.conda/envs
                          /opt/conda-22.9/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.10.6 Linux/3.10.0-1160.71.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

[user@94b309a7af15 ~]$ /opt/conda-4.14/bin/conda info

     active environment : None
       user config file : /home/user/.condarc
 populated config files : /opt/conda-4.14/.condarc
          conda version : 4.14.0
    conda-build version : not installed
         python version : 3.10.6.final.0
       virtual packages : __linux=3.10.0=0
                          __glibc=2.17=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /opt/conda-4.14  (read only)
      conda av data dir : /opt/conda-4.14/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda-4.14/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/.conda/envs
                          /opt/conda-4.14/envs
               platform : linux-64
             user-agent : conda/4.14.0 requests/2.28.1 CPython/3.10.6 Linux/3.10.0-1160.71.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</details>

**Comment by jaimergp** [comment]
This has been reported before, iirc. See here: https://github.com/conda/conda/issues/11530

It has to do with how the shebangs were and are being handled for the conda entry points.

**Comment by holzman** [comment]
From the linked issue, I understand that 22.9 and up has changed to a split shebang for the entrypoints and requires system privileges when upgrading from 4.14.

But this is also affecting a fresh install and not an upgrade - shouldn't the updated entrypoints be correctly deployed at install time rather than needing a fresh `conda init`?

**Comment by holzman** [comment]
I think this is solved by https://github.com/conda/conda/pull/12043, but I can't tell until miniforge cuts a release >= 22.11.0.

**Comment by holzman** [comment]
Confirmed - with the latest miniforge release, conda init does not modify files in `${CONDA_DIR}` out of the box.
