### ISSUE TITLE
problems_with_install_anaconda_on_windows_7

### ISSUE THREAD

**Issue by romul3532** [conda/conda#12153]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Good afternoon .

On Friday 12/02/2022, my spider stopped running. Anaconda was installed, Windows 7 platform, 64-bit. I went through all the recommendations at https://github.com/spyder-ide/spyder/wiki/Troubleshooting-Guide-and-FAQ. Nothing helped . After that, I removed anaconda. Today, I downloaded and installed (from https://repo.anaconda.com/archive/ ) Anaconda3-2019.10-Windows-x86_64.exe . The installer completed its work without problems, however, the anaconda navigator does not start (no windows with errors appear). A page appears in the browser with the following content:
```
#########################################################
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
'root_prefix'
Traceback
Traceback (most recent call last):
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1773, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "D:\my_pasport\programmi\anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'
######################################################################################
```

But the spider was launched from the start menu - anaconda3-64-bit. 
However , no library like picle is installed . When installing libraries, I get similar messages when trying to install a pickle library:
```
###########################################################
Could not find a version that satisfies the requirement pickle (from versions: none )
Error : no matching distribution found for pickle
###########################################################
```

### Conda Info

```shell
conda info

     active environment : base
    active env location : D:\my_pasport\programmi\anaconda
            shell level : 1
       user config file : C:\Users\27261\.condarc
 populated config files : C:\Users\27261\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.9
         python version : 2.7.16.final.0
       virtual packages :
       base environment : D:\my_pasport\programmi\anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\my_pasport\programmi\anaconda\pkgs
                          C:\Users\27261\.conda\pkgs
                          C:\Users\27261\AppData\Local\conda\conda\pkgs
       envs directories : D:\my_pasport\programmi\anaconda\envs
                          C:\Users\27261\.conda\envs
                          C:\Users\27261\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/2.7.16 Windows/7
Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False

(base) PS C:\Users\27261>
```

### Conda Config

```shell
C:\Users\27261\.condarc <==
ssl_verify: True
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at D:\my_pasport\programmi\anaconda:
#
# Name Version Build Channel
```

**Comment by beeankha** [comment]
Hi @romul3532 , thank you for filing this issue! Due to the contents of this ticket being off-topic for this particular repository, we ask that you please file a new one in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) (it is the place for `conda` installer/package manager issues) if you are still encountering this problem.
