### ISSUE TITLE
The conda compare command crashes and provides no comparison report output.

### ISSUE THREAD

**Issue by richlysakowski** [conda/conda#12160]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I wanted to compare two conda environments, "pygame" and "pygamefun" to see if they are redundant so that I could possibly delete one of them to save space.  (I am not a gamer, I just wanted to try pygame for a demo of an GUI builder.

**WHAT I DID:** 
I prepared the pygamefun_packages.yml environment specification using this command:

```conda list -n pygamefun --export > pygamefun_packages.yml```
Then I activated the pygame conda environment by typing:

```conda.bat activate pygame```
Then I typed the following command

 (pygame)  c:\Users\PowerUser>conda compare pygamefun_packages.yml

**WHAT HAPPENED:** 
And I got the following error. This happened the first time I tried conda compare several months ago.

```
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
Traceback (most recent call last):
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1129, in __call__
    return func(*args, **kwargs)
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 86, in main_subshell
    exit_code = do_call(args, p)
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 93, in do_call
    return getattr(module, func_name)(args, parser)
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_compare.py", line 69, in execute
    spec = specs.detect(name=args.name, filename=filename, directory=os.getcwd())
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 47, in detect
    if spec.can_handle():
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 19, in can_handle
    self._environment = env.from_file(self.filename)
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 169, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 147, in from_yaml
    data = validate_keys(data, kwargs)
  File "c:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 37, in validate_keys
    new_data = data.copy() if data else {}
AttributeError: 'str' object has no attribute 'copy'
$ c:\ProgramData\Anaconda3\Scripts\conda-script.py compare pygamefun_packages.yml

environment variables:
CHROME_DRIVER_PATH=C:\webdrivers
CIO_TEST=
CONDA_BAT=c:\ProgramData\Anaconda3\condabin\conda.bat
CONDA_DEFAULT_ENV=pygame
CONDA_ENVS_PATH=C:\ProgramData\Anaconda3\envs
CONDA_EXE=c:\ProgramData\Anaconda3\condabin..\Scripts\conda.exe
CONDA_EXES="c:\ProgramData\Anaconda3\condabin..\Scripts\conda.exe"
CONDA_PREFIX=C:\ProgramData\Anaconda3\envs\pygame
CONDA_PREFIX_1=C:\ProgramData\Anaconda3
CONDA_PREFIX_2=C:\ProgramData\Anaconda3\envs\tosapps
CONDA_PROMPT_MODIFIER=(pygame)
CONDA_PYTHON_EXE=c:\ProgramData\Anaconda3\python.exe
CONDA_ROOT=c:\ProgramData\Anaconda3
CONDA_SHLVL=3
CURL_CA_BUNDLE=
GECKO_DRIVER_PATH=C:\webdrivers
GOPATH=C:\Users\PowerUser\go
HOMEPATH=\Users\PowerUser
PATH=C:\ProgramData\Anaconda3\envs\pygame;C:\ProgramData\Anaconda3\envs\pyg
ame\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\envs\pygame\Library
\usr\bin;C:\ProgramData\Anaconda3\envs\pygame\Library\bin;C:\ProgramDa
ta\Anaconda3\envs\pygame\Scripts;C:\ProgramData\Anaconda3\envs\pygame
bin;c:\ProgramData\Anaconda3\condabin;C:\Tcl\bin;C:\Windows\system32;C
:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShe
ll\v1.0;C:\Windows\System32\OpenSSH;C:\Program Files\Microsoft SQL
Server\150\Tools\Binn;C:\Program Files\Microsoft SQL Server\Client SDK
\ODBC\170\Tools\Binn;C:\Users\poweruser\Desktop\rsl_utils;C:\ProgramDa
ta\Anaconda3\envs;C:\Program Files\Calibre2;C:\Program
Files\Git\cmd;C:\webdrivers;C:\Program Files
(x86)\IncrediBuild;C:\Program Files\Go\bin;C:\Program
Files\dotnet;C:\Program Files\Pandoc;C:\Program
Files\JSONBuddy;C:\ProgramData\JSONBuddy;C:\Program Files\MySQL\MySQL
Shell 8.0\bin;c:\users\PowerUser;C:\Users\PowerUser\rsl_utils;C:\Users
\PowerUser\go\bin;C:\Program Files\Microsoft_VSCode;C:\Program
Files\JetBrains\PyCharm 2022.2.1\bin;C:\Users\PowerUser\AppData\Local
GitHubDesktop\bin;C:\webdrivers\chromedriver.exe;C:\RSLbatchfiles;c:\e
putils;c:\webdrivers;C:\Program Files\Notepad++;C:\Program
Files\VAPOR;C:\Program Files\JetBrains\DataSpell 2022.2.3\bin
PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
PowerShell\v1.0\Modules
REQUESTS_CA_BUNDLE=
SSL_CERT_FILE=

 active environment : pygame
active env location : C:\ProgramData\Anaconda3\envs\pygame
        shell level : 3
   user config file : C:\Users\PowerUser\.condarc
populated config files : C:\Users\PowerUser.condarc
conda version : 22.9.0
conda-build version : 3.21.8
python version : 3.9.12.final.0
virtual packages : __cuda=11.6=0
__win=0=0
__archspec=1=x86_64
base environment : c:\ProgramData\Anaconda3 (writable)
conda av data dir : c:\ProgramData\Anaconda3\etc\conda
conda av metadata url : None
channel URLs : https://conda.anaconda.org/conda-forge/win-64
https://conda.anaconda.org/conda-forge/noarch
https://repo.anaconda.com/pkgs/main/win-64
https://repo.anaconda.com/pkgs/main/noarch
https://repo.anaconda.com/pkgs/r/win-64
https://repo.anaconda.com/pkgs/r/noarch
https://repo.anaconda.com/pkgs/msys2/win-64
https://repo.anaconda.com/pkgs/msys2/noarch
package cache : c:\ProgramData\Anaconda3\pkgs
C:\Users\PowerUser.conda\pkgs
C:\Users\PowerUser\AppData\Local\conda\conda\pkgs
envs directories : C:\ProgramData\Anaconda3\envs
c:\ProgramData\Anaconda3\envs
C:\Users\PowerUser.conda\envs
C:\Users\PowerUser\AppData\Local\conda\conda\envs
platform : win-64
user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
administrator : True
netrc file : None
offline mode : False

### Conda Info

```shell
(pygame) c:\Users\PowerUser>conda info

     active environment : pygame
    active env location : C:\ProgramData\Anaconda3\envs\pygame
            shell level : 3
       user config file : C:\Users\PowerUser\.condarc
 populated config files : C:\Users\PowerUser\.condarc
          conda version : 22.9.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __cuda=11.6=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : c:\ProgramData\Anaconda3  (writable)
      conda av data dir : c:\ProgramData\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\ProgramData\Anaconda3\pkgs
                          C:\Users\PowerUser\.conda\pkgs
                          C:\Users\PowerUser\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          c:\ProgramData\Anaconda3\envs
                          C:\Users\PowerUser\.conda\envs
                          C:\Users\PowerUser\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19044
          administrator : True
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
(pygame) c:\Users\PowerUser>conda config --show-sources
==> C:\Users\PowerUser\.condarc <==
channels:
  - conda-forge
  - defaults

==> envvars <==
envs_path:
  - C:\ProgramData\Anaconda3\envs
```

### Conda list

```shell
(pygame) c:\Users\PowerUser>conda list --show-channel-urls
# packages in environment at C:\ProgramData\Anaconda3\envs\pygame:
#
# Name                    Version                   Build  Channel
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
brotlipy                  0.7.0           py39hb82d6ee_1004    conda-forge
ca-certificates           2022.6.15            h5b45459_0    conda-forge
certifi                   2022.6.15        py39hcbf5309_0    conda-forge
cffi                      1.15.1           py39h0878f49_0    conda-forge
charset-normalizer        2.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.5              pyhd8ed1ab_0    conda-forge
conda                     4.13.0           py39hcbf5309_1    conda-forge
conda-package-handling    1.8.1            py39hb3671d1_1    conda-forge
cryptography              37.0.4           py39h7bc7c5c_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
fonttools                 4.34.4           py39hb82d6ee_0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
glib                      2.72.1               h7755175_0    conda-forge
glib-tools                2.72.1               h7755175_0    conda-forge
gst-plugins-base          1.20.3               he07aa86_0    conda-forge
gstreamer                 1.20.3               hdff456e_0    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
kiwisolver                1.4.4            py39h2e07f2f_0    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              15_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              15_win64_mkl    conda-forge
libclang                  14.0.6          default_h77d9078_0    conda-forge
libclang13                14.0.6          default_h77d9078_0    conda-forge
libdeflate                1.13                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.72.1               h3be07f2_0    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              15_win64_mkl    conda-forge
libogg                    1.3.4                h8ffe710_1    conda-forge
libpng                    1.6.37               h1d00b33_3    conda-forge
libtiff                   4.4.0                h92677e6_3    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp                   1.2.3                h8ffe710_1    conda-forge
libwebp-base              1.2.3                h8ffe710_2    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libzlib                   1.2.12               h8ffe710_2    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
matplotlib                3.5.2            py39hcbf5309_1    conda-forge
matplotlib-base           3.5.2            py39h581301d_1    conda-forge
menuinst                  1.4.18           py39hcbf5309_1    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
numpy                     1.23.1           py39h1a62c8c_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1q               h8ffe710_0    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pillow                    9.2.0            py39ha53f419_0    conda-forge
pip                       22.2.2             pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pycosat                   0.6.3           py39hb82d6ee_1010    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygame                    2.1.2                    pypi_0    pypi
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py39hb08f45d_0    conda-forge
pyqt5-sip                 12.11.0          py39h415ef7b_0    conda-forge
pysocks                   1.7.1            py39hcbf5309_5    conda-forge
python                    3.9.0           h7840368_5_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pywin32                   303              py39hb82d6ee_0    conda-forge
qt-main                   5.15.4               h467ea89_2    conda-forge
requests                  2.28.1             pyhd8ed1ab_0    conda-forge
ruamel_yaml               0.15.80         py39hb82d6ee_1007    conda-forge
scipy                     1.9.0            py39h316f440_0    conda-forge
setuptools                63.4.1           py39hcbf5309_0    conda-forge
sip                       6.6.2            py39h415ef7b_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.39.2               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.2              py39hb82d6ee_0    conda-forge
tqdm                      4.64.0             pyhd8ed1ab_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0            py39hcbf5309_4    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zlib                      1.2.12               h8ffe710_2    conda-forge
zstd                      1.5.2                h6255e5f_2    conda-forge
```

**Comment by mbargull** [comment]
`conda list --export` exports a list of package (builds) present in the environment as a simple newline-delimited text file.
It is only coincidentally a valid YAML file (parsed as just a single string; not what one might expect). 
To create a proper `environment.yml` you want to run
```
conda env export -n pygamefun > pygamefun_packages.yml
```
. See https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#sharing-an-environment for details.

----
That said, the error handling could be better here to say "not a valid Conda environment YAML file" or something like that.

**Comment by travishathaway** [comment]
Conda has fairly brittle YAML parsing and this isn't the only place where this pops up. When attempting to parse configuration files, things can blow up in fun and interesting ways when any of the config files are not valid YAML.

I will add this to a recently create epic discussing general user experience concerns as it is a symptom of a wider problem in conda itself.

@richlysakowski, I hope that the answer @mbargull provided was sufficient to get you back in business, and I'd like to thank you for bring this issue to our attention.
