### ISSUE TITLE
installing anaconda but cant open the navigator,TypeError:unhashable type commentedmap

### ISSUE THREAD

**Issue by juechusan** [conda/conda#12169]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

installed anaconda3 4.2 windows recently ,while opening the navigator, the ico flash back and the navigator cant run.
my jupyter notebook also cant create python3 notebook.
check several command in cmd and the answer always be like'unhashable type commentedmap'or 'root__profix'.

### Conda Info

```shell
Traceback (most recent call last):
      File "G:\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "G:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "G:\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 215, in execute
        channels = context.channels
      File "G:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 450, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "G:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 598, in _merge
        top_deduped = tuple(unique(concatv(top_lines, all_lines)))
      File "cytoolz/itertoolz.pyx", line 410, in cytoolz.itertoolz._unique_identity.__next__ (cytoolz/itertoolz.c:7406)
    TypeError: unhashable type: 'CommentedMap'
```

### Conda Config

```shell
File "G:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "G:\Anaconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "G:\Anaconda3\lib\site-packages\conda\exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "G:\Anaconda3\lib\site-packages\conda\exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "G:\Anaconda3\lib\site-packages\conda\exceptions.py", line 407, in get_info
    args.func(args, p)
  File "G:\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 215, in execute
    channels = context.channels
  File "G:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 450, in __get__
    result = typify_data_structure(self._merge(matches) if matches else self.default,
  File "G:\Anaconda3\lib\site-packages\conda\common\configuration.py", line 598, in _merge
    top_deduped = tuple(unique(concatv(top_lines, all_lines)))
  File "cytoolz/itertoolz.pyx", line 410, in cytoolz.itertoolz._unique_identity.__next__ (cytoolz/itertoolz.c:7406)
    while PySet_Contains(self.seen, item):
TypeError: unhashable type: 'CommentedMap'
```

### Conda list

```shell
# packages in environment at G:\Anaconda3:
#
_license                  1.1                      py35_1    https://repo.continuum.io/pkgs/free
_nb_ext_conf              0.3.0                    py35_0    https://repo.continuum.io/pkgs/free
alabaster                 0.7.9                    py35_0    https://repo.continuum.io/pkgs/free
anaconda                  4.2.0               np111py35_0    https://repo.continuum.io/pkgs/free
anaconda-clean            1.0.0                    py35_0    https://repo.continuum.io/pkgs/free
anaconda-client           1.5.1                    py35_0    https://repo.continuum.io/pkgs/free
anaconda-navigator        1.3.1                    py35_0    https://repo.continuum.io/pkgs/free
argcomplete               1.0.0                    py35_1    https://repo.continuum.io/pkgs/free
astroid                   1.4.7                    py35_0    https://repo.continuum.io/pkgs/free
astropy                   1.2.1               np111py35_0    https://repo.continuum.io/pkgs/free
babel                     2.3.4                    py35_0    https://repo.continuum.io/pkgs/free
backports                 1.0                      py35_0    https://repo.continuum.io/pkgs/free
beautifulsoup4            4.5.1                    py35_0    https://repo.continuum.io/pkgs/free
bitarray                  0.8.1                    py35_1    https://repo.continuum.io/pkgs/free
blaze                     0.10.1                   py35_0    https://repo.continuum.io/pkgs/free
bokeh                     0.12.2                   py35_0    https://repo.continuum.io/pkgs/free
boto                      2.42.0                   py35_0    https://repo.continuum.io/pkgs/free
bottleneck                1.1.0               np111py35_0    https://repo.continuum.io/pkgs/free
bzip2                     1.0.6                    vc14_3  [vc14]  https://repo.continuum.io/pkgs/free
cffi                      1.7.0                    py35_0    https://repo.continuum.io/pkgs/free
chest                     0.2.3                    py35_0    https://repo.continuum.io/pkgs/free
click                     6.6                      py35_0    https://repo.continuum.io/pkgs/free
cloudpickle               0.2.1                    py35_0    https://repo.continuum.io/pkgs/free
clyent                    1.2.2                    py35_0    https://repo.continuum.io/pkgs/free
colorama                  0.3.7                    py35_0    https://repo.continuum.io/pkgs/free
comtypes                  1.1.2                    py35_0    https://repo.continuum.io/pkgs/free
conda                     4.2.9                    py35_0    https://repo.continuum.io/pkgs/free
conda-build               2.0.2                    py35_0    https://repo.continuum.io/pkgs/free
configobj                 5.0.6                    py35_0    https://repo.continuum.io/pkgs/free
console_shortcut          0.1.1                    py35_1    https://repo.continuum.io/pkgs/free
contextlib2               0.5.3                    py35_0    https://repo.continuum.io/pkgs/free
cryptography              1.5                      py35_0    https://repo.continuum.io/pkgs/free
curl                      7.49.0                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
cycler                    0.10.0                   py35_0    https://repo.continuum.io/pkgs/free
cython                    0.24.1                   py35_0    https://repo.continuum.io/pkgs/free
cytoolz                   0.8.0                    py35_0    https://repo.continuum.io/pkgs/free
dask                      0.11.0                   py35_0    https://repo.continuum.io/pkgs/free
datashape                 0.5.2                    py35_0    https://repo.continuum.io/pkgs/free
decorator                 4.0.10                   py35_0    https://repo.continuum.io/pkgs/free
dill                      0.2.5                    py35_0    https://repo.continuum.io/pkgs/free
docutils                  0.12                     py35_2    https://repo.continuum.io/pkgs/free
dynd-python               0.7.2                    py35_0    https://repo.continuum.io/pkgs/free
entrypoints               0.2.2                    py35_0    https://repo.continuum.io/pkgs/free
et_xmlfile                1.0.1                    py35_0    https://repo.continuum.io/pkgs/free
fastcache                 1.0.2                    py35_1    https://repo.continuum.io/pkgs/free
filelock                  2.0.6                    py35_0    https://repo.continuum.io/pkgs/free
flask                     0.11.1                   py35_0    https://repo.continuum.io/pkgs/free
flask-cors                2.1.2                    py35_0    https://repo.continuum.io/pkgs/free
freetype                  2.5.5                    vc14_1  [vc14]  https://repo.continuum.io/pkgs/free
get_terminal_size         1.0.0                    py35_0    https://repo.continuum.io/pkgs/free
gevent                    1.1.2                    py35_0    https://repo.continuum.io/pkgs/free
greenlet                  0.4.10                   py35_0    https://repo.continuum.io/pkgs/free
h5py                      2.6.0               np111py35_2    https://repo.continuum.io/pkgs/free
hdf5                      1.8.15.1                 vc14_4  [vc14]  https://repo.continuum.io/pkgs/free
heapdict                  1.0.0                    py35_1    https://repo.continuum.io/pkgs/free
icu                       57.1                     vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
idna                      2.1                      py35_0    https://repo.continuum.io/pkgs/free
imagesize                 0.7.1                    py35_0    https://repo.continuum.io/pkgs/free
ipykernel                 4.5.0                    py35_0    https://repo.continuum.io/pkgs/free
ipython                   5.1.0                    py35_0    https://repo.continuum.io/pkgs/free
ipython_genutils          0.1.0                    py35_0    https://repo.continuum.io/pkgs/free
ipywidgets                5.2.2                    py35_0    https://repo.continuum.io/pkgs/free
itsdangerous              0.24                     py35_0    https://repo.continuum.io/pkgs/free
jdcal                     1.2                      py35_1    https://repo.continuum.io/pkgs/free
jedi                      0.9.0                    py35_1    https://repo.continuum.io/pkgs/free
jinja2                    2.8                      py35_1    https://repo.continuum.io/pkgs/free
jpeg                      8d                       vc14_2  [vc14]  https://repo.continuum.io/pkgs/free
jsonschema                2.5.1                    py35_0    https://repo.continuum.io/pkgs/free
jupyter                   1.0.0                    py35_3    https://repo.continuum.io/pkgs/free
jupyter_client            4.4.0                    py35_0    https://repo.continuum.io/pkgs/free
jupyter_console           5.0.0                    py35_0    https://repo.continuum.io/pkgs/free
jupyter_core              4.2.0                    py35_0    https://repo.continuum.io/pkgs/free
lazy-object-proxy         1.2.1                    py35_0    https://repo.continuum.io/pkgs/free
libdynd                   0.7.2                         0    https://repo.continuum.io/pkgs/free
libpng                    1.6.22                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
libtiff                   4.0.6                    vc14_2  [vc14]  https://repo.continuum.io/pkgs/free
llvmlite                  0.13.0                   py35_0    https://repo.continuum.io/pkgs/free
locket                    0.2.0                    py35_1    https://repo.continuum.io/pkgs/free
lxml                      3.6.4                    py35_0    https://repo.continuum.io/pkgs/free
markupsafe                0.23                     py35_2    https://repo.continuum.io/pkgs/free
matplotlib                1.5.3               np111py35_0    https://repo.continuum.io/pkgs/free
menuinst                  1.4.1                    py35_0    https://repo.continuum.io/pkgs/free
mistune                   0.7.3                    py35_0    https://repo.continuum.io/pkgs/free
mkl                       11.3.3                        1    https://repo.continuum.io/pkgs/free
mkl-service               1.1.2                    py35_2    https://repo.continuum.io/pkgs/free
mpmath                    0.19                     py35_1    https://repo.continuum.io/pkgs/free
multipledispatch          0.4.8                    py35_0    https://repo.continuum.io/pkgs/free
nb_anacondacloud          1.2.0                    py35_0    https://repo.continuum.io/pkgs/free
nb_conda                  2.0.0                    py35_0    https://repo.continuum.io/pkgs/free
nb_conda_kernels          2.0.0                    py35_0    https://repo.continuum.io/pkgs/free
nbconvert                 4.2.0                    py35_0    https://repo.continuum.io/pkgs/free
nbformat                  4.1.0                    py35_0    https://repo.continuum.io/pkgs/free
nbpresent                 3.0.2                    py35_0    https://repo.continuum.io/pkgs/free
networkx                  1.11                     py35_0    https://repo.continuum.io/pkgs/free
nltk                      3.2.1                    py35_0    https://repo.continuum.io/pkgs/free
nose                      1.3.7                    py35_1    https://repo.continuum.io/pkgs/free
notebook                  4.2.3                    py35_0    https://repo.continuum.io/pkgs/free
numba                     0.28.1              np111py35_0    https://repo.continuum.io/pkgs/free
numexpr                   2.6.1               np111py35_0    https://repo.continuum.io/pkgs/free
numpy                     1.11.1                   py35_1    https://repo.continuum.io/pkgs/free
odo                       0.5.0                    py35_1    https://repo.continuum.io/pkgs/free
openpyxl                  2.3.2                    py35_0    https://repo.continuum.io/pkgs/free
openssl                   1.0.2j                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
pandas                    0.18.1              np111py35_0    https://repo.continuum.io/pkgs/free
partd                     0.3.6                    py35_0    https://repo.continuum.io/pkgs/free
path.py                   8.2.1                    py35_0    https://repo.continuum.io/pkgs/free
pathlib2                  2.1.0                    py35_0    https://repo.continuum.io/pkgs/free
patsy                     0.4.1                    py35_0    https://repo.continuum.io/pkgs/free
pep8                      1.7.0                    py35_0    https://repo.continuum.io/pkgs/free
pickleshare               0.7.4                    py35_0    https://repo.continuum.io/pkgs/free
pillow                    3.3.1                    py35_0    https://repo.continuum.io/pkgs/free
pip                       8.1.2                    py35_0    https://repo.continuum.io/pkgs/free
pkginfo                   1.3.2                    py35_0    https://repo.continuum.io/pkgs/free
ply                       3.9                      py35_0    https://repo.continuum.io/pkgs/free
prompt_toolkit            1.0.3                    py35_0    https://repo.continuum.io/pkgs/free
psutil                    4.3.1                    py35_0    https://repo.continuum.io/pkgs/free
py                        1.4.31                   py35_0    https://repo.continuum.io/pkgs/free
pyasn1                    0.1.9                    py35_0    https://repo.continuum.io/pkgs/free
pycosat                   0.6.1                    py35_1    https://repo.continuum.io/pkgs/free
pycparser                 2.14                     py35_1    https://repo.continuum.io/pkgs/free
pycrypto                  2.6.1                    py35_4    https://repo.continuum.io/pkgs/free
pycurl                    7.43.0                   py35_0    https://repo.continuum.io/pkgs/free
pyflakes                  1.3.0                    py35_0    https://repo.continuum.io/pkgs/free
pygments                  2.1.3                    py35_0    https://repo.continuum.io/pkgs/free
pylint                    1.5.4                    py35_1    https://repo.continuum.io/pkgs/free
pyopenssl                 16.0.0                   py35_0    https://repo.continuum.io/pkgs/free
pyparsing                 2.1.4                    py35_0    https://repo.continuum.io/pkgs/free
pyqt                      5.6.0                    py35_0    https://repo.continuum.io/pkgs/free
pytables                  3.2.2               np111py35_4    https://repo.continuum.io/pkgs/free
pytest                    2.9.2                    py35_0    https://repo.continuum.io/pkgs/free
python                    3.5.2                         0    https://repo.continuum.io/pkgs/free
python-dateutil           2.5.3                    py35_0    https://repo.continuum.io/pkgs/free
pytz                      2016.6.1                 py35_0    https://repo.continuum.io/pkgs/free
pywin32                   220                      py35_1    https://repo.continuum.io/pkgs/free
pyyaml                    3.12                     py35_0    https://repo.continuum.io/pkgs/free
pyzmq                     15.4.0                   py35_0    https://repo.continuum.io/pkgs/free
qt                        5.6.0                    vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
qtawesome                 0.3.3                    py35_0    https://repo.continuum.io/pkgs/free
qtconsole                 4.2.1                    py35_2    https://repo.continuum.io/pkgs/free
qtpy                      1.1.2                    py35_0    https://repo.continuum.io/pkgs/free
requests                  2.11.1                   py35_0    https://repo.continuum.io/pkgs/free
rope                      0.9.4                    py35_1    https://repo.continuum.io/pkgs/free
ruamel_yaml               0.11.14                  py35_0    https://repo.continuum.io/pkgs/free
scikit-image              0.12.3              np111py35_1    https://repo.continuum.io/pkgs/free
scikit-learn              0.17.1              np111py35_1    https://repo.continuum.io/pkgs/free
scipy                     0.18.1              np111py35_0    https://repo.continuum.io/pkgs/free
setuptools                27.2.0                   py35_1    https://repo.continuum.io/pkgs/free
simplegeneric             0.8.1                    py35_1    https://repo.continuum.io/pkgs/free
singledispatch            3.4.0.3                  py35_0    https://repo.continuum.io/pkgs/free
sip                       4.18                     py35_0    https://repo.continuum.io/pkgs/free
six                       1.10.0                   py35_0    https://repo.continuum.io/pkgs/free
snowballstemmer           1.2.1                    py35_0    https://repo.continuum.io/pkgs/free
sockjs-tornado            1.0.3                    py35_0    https://repo.continuum.io/pkgs/free
sphinx                    1.4.6                    py35_0    https://repo.continuum.io/pkgs/free
spyder                    3.0.0                    py35_0    https://repo.continuum.io/pkgs/free
sqlalchemy                1.0.13                   py35_0    https://repo.continuum.io/pkgs/free
statsmodels               0.6.1               np111py35_1    https://repo.continuum.io/pkgs/free
sympy                     1.0                      py35_0    https://repo.continuum.io/pkgs/free
tk                        8.5.18                   vc14_0  [vc14]  https://repo.continuum.io/pkgs/free
toolz                     0.8.0                    py35_0    https://repo.continuum.io/pkgs/free
tornado                   4.4.1                    py35_0    https://repo.continuum.io/pkgs/free
traitlets                 4.3.0                    py35_0    https://repo.continuum.io/pkgs/free
unicodecsv                0.14.1                   py35_0    https://repo.continuum.io/pkgs/free
vs2015_runtime            14.0.25123                    0    https://repo.continuum.io/pkgs/free
wcwidth                   0.1.7                    py35_0    https://repo.continuum.io/pkgs/free
werkzeug                  0.11.11                  py35_0    https://repo.continuum.io/pkgs/free
wheel                     0.29.0                   py35_0    https://repo.continuum.io/pkgs/free
widgetsnbextension        1.2.6                    py35_0    https://repo.continuum.io/pkgs/free
win_unicode_console       0.5                      py35_0    https://repo.continuum.io/pkgs/free
wrapt                     1.10.6                   py35_0    https://repo.continuum.io/pkgs/free
xlrd                      1.0.0                    py35_0    https://repo.continuum.io/pkgs/free
xlsxwriter                0.9.3                    py35_0    https://repo.continuum.io/pkgs/free
xlwings                   0.10.0                   py35_0    https://repo.continuum.io/pkgs/free
xlwt                      1.1.2                    py35_0    https://repo.continuum.io/pkgs/free
zlib                      1.2.8                    vc14_3  [vc14]  https://repo.continuum.io/pkgs/free
```

### Additional Context

![微信图片_20221212174025](https://user-images.githubusercontent.com/107468553/207012686-f631e5df-ddfe-487f-b18c-fe57b7b3fc5d.png)

**Comment by travishathaway** [comment]
Hi @juechusan,

Thank you for filing this issue! Unfortunately, this is off-topic for this repo. If you are still encountering this issue please reopen in the [Anaconda issue tracker](https://github.com/ContinuumIO/anaconda-issues/issues) where Anaconda installer/package issues are addressed.
