### ISSUE TITLE
Environment related conda update failure

### ISSUE THREAD

**Issue by DagonArises** [conda/conda#12185]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I started with trying to upgrade python from 3.6.8 to 3.7 with conda update python but it stuck at 'environment inconsistency' for a long time. Then I tried force ```conda install conda --force-reinstall``` and received ModuleNotFound error regarding pip vendor request. I reinstalled pip and tried command ```conda update --all``` but received this intimidating error report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 745, in use_only_tar_bz2
        import conda_package_handling.api
      File "/Users/necromancerchenmy/anaconda3/lib/python3.6/site-packages/conda_package_handling/api.py", line 6, in <module>
        from six import string_types as _string_types
    ModuleNotFoundError: No module named 'six'

`$ /Users/necromancerchenmy/anaconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/necromancerchenmy/anaconda3/bin/conda
             CONDA_PREFIX=/Users/necromancerchenmy/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/necromancerchenmy/anaconda3/bin/python
               CONDA_ROOT=/Users/necromancerchenmy/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                     PATH=/Users/necromancerchenmy/anaconda3/bin:/Users/necromancerchenmy/anacon
                          da3/bin:/Library/Frameworks/Python.framework/Versions/3.6/bin:/usr/loc
                          al/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/Users/necrom
                          ancerchenmy/Library/Application Support/JetBrains/Toolbox/scripts
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/necromancerchenmy/anaconda3
            shell level : 1
       user config file : /Users/necromancerchenmy/.condarc
 populated config files : /Users/necromancerchenmy/anaconda3/.condarc
                          /Users/necromancerchenmy/.condarc
          conda version : 4.10.3
    conda-build version : 3.10.5
         python version : 3.6.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/necromancerchenmy/anaconda3  (writable)
      conda av data dir : /Users/necromancerchenmy/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/necromancerchenmy/anaconda3/pkgs
                          /Users/necromancerchenmy/.conda/pkgs
       envs directories : /Users/necromancerchenmy/anaconda3/envs
                          /Users/necromancerchenmy/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.6.8 Darwin/20.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
Would like some help setting conda right and updating python as well. I have pip-upgraded python to 3.10 but apparently it is not the same python anaconda is using. On JupyterNotebook it is still running 3.6.8. 
Thanks in advance!

### Conda Info

```shell
active environment : base
    active env location : /Users/necromancerchenmy/anaconda3
            shell level : 1
       user config file : /Users/necromancerchenmy/.condarc
 populated config files : /Users/necromancerchenmy/anaconda3/.condarc
                          /Users/necromancerchenmy/.condarc
          conda version : 4.10.3
    conda-build version : 3.10.5
         python version : 3.6.8.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/necromancerchenmy/anaconda3  (writable)
      conda av data dir : /Users/necromancerchenmy/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/necromancerchenmy/anaconda3/pkgs
                          /Users/necromancerchenmy/.conda/pkgs
       envs directories : /Users/necromancerchenmy/anaconda3/envs
                          /Users/necromancerchenmy/.conda/envs
               platform : osx-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.6.8 Darwin/20.4.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/necromancerchenmy/anaconda3/.condarc <==
channels:
  - conda-forge
  - defaults

==> /Users/necromancerchenmy/.condarc <==
ssl_verify: True
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at /Users/necromancerchenmy/anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         5.3.0                    py36_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
absl-py                   0.15.0                   pypi_0    pypi
aiohttp                   3.8.1                    pypi_0    pypi
aiohttp-cors              0.7.0                    pypi_0    pypi
aiosignal                 1.2.0                    pypi_0    pypi
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom                   py36_1    defaults
anaconda-client           1.8.0            py36hecd8cb5_0    defaults
anaconda-navigator        2.1.0            py36hecd8cb5_0    defaults
anaconda-project          0.8.2            py36h9ee5d53_0    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.3                    py36_0    defaults
astropy                   3.0.2            py36h917ab60_1    defaults
astunparse                1.6.3                    pypi_0    pypi
async-timeout             4.0.2                    pypi_0    pypi
asynctest                 0.13.0                   pypi_0    pypi
atomicwrites              1.4.0                      py_0    defaults
attrs                     18.1.0                   py36_0    defaults
autograd                  1.3                      pypi_0    pypi
automat                   20.2.0                     py_0    defaults
babel                     2.5.3                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
bcrypt                    3.2.0            py36haf1e3a3_0    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h1de35cc_1    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blas                      1.0                         mkl    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.1.3                    py36_0    defaults
blessed                   1.19.1                   pypi_0    pypi
blosc                     1.14.3               hd9629dc_0    defaults
bokeh                     0.12.16                  py36_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
boto3                     1.23.10                  pypi_0    pypi
botocore                  1.26.10                  pypi_0    pypi
bottleneck                1.2.1            py36hbd380ad_0    defaults
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2021.10.26           hecd8cb5_2    defaults
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.10.8                pypi_0    pypi
cffi                      1.11.5           py36h342bebf_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
charset-normalizer        2.0.7                    pypi_0    pypi
clang                     5.0                      pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cloudpickle               0.5.3                    py36_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
colorful                  0.5.4                    pypi_0    pypi
conda                     4.10.3           py36hecd8cb5_0    defaults
conda-build               3.10.5                   py36_0    defaults
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-package-handling    1.6.0            py36h1de35cc_0    defaults
conda-repo-cli            1.0.4              pyhd3eb1b0_0    defaults
conda-token               0.3.0              pyhd3eb1b0_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
constantly                15.1.0           py36h28b3542_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
contextvars               2.4                      pypi_0    pypi
cryptography              3.3.2            py36hbcfaee0_0    defaults
curl                      7.67.0               ha441bb4_0    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.28.2           py36h1de35cc_0    defaults
cytoolz                   0.9.0.1          py36h1de35cc_0    defaults
dask                      0.17.5                   py36_0    defaults
dask-core                 0.17.5                   py36_0    defaults
datasets                  2.4.0                    pypi_0    pypi
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                    py36_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
dill                      0.3.4                    pypi_0    pypi
distlib                   0.3.6                    pypi_0    pypi
distributed               1.21.8                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.5                hb8e80ba_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
filelock                  3.4.1                    pypi_0    pypi
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.4                    py36_0    defaults
flatbuffers               1.12                     pypi_0    pypi
freetype                  2.8                  h12048fb_1    defaults
frozenlist                1.2.0                    pypi_0    pypi
fsspec                    2022.1.0                 pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.0            py36h1de35cc_0    defaults
glib                      2.56.1               h35bc53a_0    defaults
glob2                     0.6              py36h94c9186_0    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36hf9c35bd_2    defaults
google-api-core           2.8.2                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
googleapis-common-protos  1.56.3                   pypi_0    pypi
gpustat                   1.0.0rc1                 pypi_0    pypi
greenlet                  0.4.13           py36h1de35cc_0    defaults
grpcio                    1.42.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
huggingface-hub           0.4.0                    pypi_0    pypi
hyperas                   0.4.1                    pypi_0    pypi
hyperlink                 21.0.0             pyhd3eb1b0_0    defaults
hyperopt                  0.2.5                    pypi_0    pypi
icu                       58.2                 h4b95b61_1    defaults
idna-ssl                  1.1.0                    pypi_0    pypi
imageio                   2.3.0                    py36_0    defaults
imagesize                 1.0.0                    py36_0    defaults
immutables                0.18                     pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
importlib_metadata        4.8.1                hd3eb1b0_0    defaults
incremental               17.5.0           py36hecd8cb5_0    defaults
intel-openmp              2018.0.0                      8    defaults
ipykernel                 4.8.2                    py36_0    defaults
ipython                   6.4.0                    py36_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.2.1                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.12.0                   py36_1    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter_client            5.2.3                    py36_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
jupyterlab                0.32.1                   py36_0    defaults
jupyterlab_launcher       0.10.5                   py36_0    defaults
keras                     2.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
keras-tuner               1.1.0                    pypi_0    pypi
keyring                   23.1.0           py36hecd8cb5_0    defaults
kiwisolver                1.0.1            py36h792292d_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
kt-legacy                 1.0.4                    pypi_0    pypi
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcurl                   7.67.0               h051b688_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.34               he12f830_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.2                ha12b0ac_0    defaults
libtiff                   4.0.9                hcb84e12_1    defaults
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvmlite                  0.23.1           py36hc454e04_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lxml                      4.2.1            py36h7166777_0    defaults
lzo                       2.10                 h362108e_2    defaults
markdown                  3.3.6                    pypi_0    pypi
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.2.2            py36ha7267d0_0    defaults
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.8.3            py36h1de35cc_1    defaults
mkl                       2018.0.2                      1    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mkl_fft                   1.0.1            py36h917ab60_0    defaults
mkl_random                1.0.1            py36h78cc56f_0    defaults
more-itertools            4.1.0                    py36_0    defaults
mpc                       1.0.3                h7a72875_5    defaults
mpfr                      3.1.5                h711e7fd_2    defaults
mpmath                    1.0.0            py36hf1b8295_2    defaults
msgpack                   1.0.4                    pypi_0    pypi
msgpack-python            0.5.6            py36h04f5b5a_0    defaults
multidict                 5.2.0                    pypi_0    pypi
multipledispatch          0.5.0                    py36_0    defaults
multiprocess              0.70.12.2                pypi_0    pypi
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.1                  h0a44026_0    defaults
nltk                      3.3.0                    py36_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.5.0                    py36_0    defaults
numba                     0.38.0           py36h1702cab_0    defaults
numexpr                   2.6.5            py36h057f876_0    defaults
numpy                     1.19.5                   pypi_0    pypi
numpydoc                  0.8.0                    py36_0    defaults
nvidia-ml-py              11.495.46                pypi_0    pypi
oauthlib                  3.1.1                    pypi_0    pypi
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.45.1                   py36_0    defaults
opencensus                0.11.0                   pypi_0    pypi
opencensus-context        0.1.3                    pypi_0    pypi
opencv-python             4.5.1.48                 pypi_0    pypi
openpyxl                  2.5.3                    py36_0    defaults
openssl                   1.1.1l               h9ed2024_0    defaults
opt-einsum                3.3.0                    pypi_0    pypi
pandas                    0.23.0           py36h1702cab_0    defaults
pandas-datareader         0.9.0                    pypi_0    pypi
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parso                     0.2.0                    py36_0    defaults
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   11.0.1                   py36_0    defaults
pathlib2                  2.3.2                    py36_0    defaults
patsy                     0.5.1                    pypi_0    pypi
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.5.0                    py36_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1                   pypi_0    pypi
pkginfo                   1.4.2                    py36_1    defaults
platformdirs              2.4.0                    pypi_0    pypi
plotly                    5.4.0                    pypi_0    pypi
pluggy                    0.6.0            py36hb1d0581_0    defaults
ply                       3.11                     py36_0    defaults
prometheus_client         0.11.0             pyhd3eb1b0_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
protobuf                  3.19.1                   pypi_0    pypi
psutil                    5.9.1                    pypi_0    pypi
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.5.3                    py36_0    defaults
py-spy                    0.3.12                   pypi_0    pypi
py4j                      0.10.9.3                 pypi_0    pypi
pyarrow                   6.0.1                    pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0    defaults
pyasn1-modules            0.2.8                    pypi_0    pypi
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h1de35cc_8    defaults
pycurl                    7.43.0.3         py36ha12b0ac_0    defaults
pydantic                  1.9.2                    pypi_0    pypi
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pyhamcrest                2.0.2              pyhd3eb1b0_2    defaults
pyjwt                     2.1.0            py36hecd8cb5_0    defaults
pylint                    1.8.4                    py36_0    defaults
pyodbc                    4.0.23           py36h0a44026_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.9.2            py36h11d3b92_0    defaults
pysocks                   1.6.8                    py36_0    defaults
pytables                  3.4.3            py36h5ca999c_2    defaults
pytest                    3.5.1                    py36_0    defaults
pytest-arraydiff          0.2                      py36_0    defaults
pytest-astropy            0.3.0                    py36_0    defaults
pytest-doctestplus        0.1.3                    py36_0    defaults
pytest-openfiles          0.3.0                    py36_0    defaults
pytest-remotedata         0.2.1                    py36_0    defaults
python                    3.6.8                haf84260_0    defaults
python-dateutil           2.7.3                    py36_0    defaults
python.app                2                        py36_8    defaults
pytz                      2018.4                   py36_0    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    5.3.1            py36h1de35cc_0    defaults
pyzmq                     17.0.0           py36h1de35cc_1    defaults
qt                        5.9.5                h02808f3_0    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.4.1                    py36_0    defaults
ray                       2.0.0                    pypi_0    pypi
readline                  7.0                  hc1231fa_4    defaults
requests                  2.26.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
responses                 0.17.0                   pypi_0    pypi
rope                      0.10.7           py36h68959ac_0    defaults
rsa                       4.7.2                    pypi_0    pypi
ruamel_yaml               0.15.35          py36h1de35cc_1    defaults
s3transfer                0.5.2                    pypi_0    pypi
sacremoses                0.0.53                   pypi_0    pypi
sarge                     0.1.7.post1              pypi_0    pypi
scikit-image              0.13.1           py36h1de35cc_1    defaults
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.8.1            py36h595ecd9_0    defaults
see-rnn                   1.15.1                   pypi_0    pypi
semantic-version          2.10.0                   pypi_0    pypi
send2trash                1.5.0                    py36_0    defaults
sentencepiece             0.1.97                   pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
service_identity          18.1.0             pyhd3eb1b0_1    defaults
setuptools                59.2.0                   pypi_0    pypi
setuptools-rust           1.1.2                    pypi_0    pypi
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
six                       1.15.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
smart-open                6.1.0                    pypi_0    pypi
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.6.1                    py36_0    defaults
sortedcontainers          1.5.10                   py36_0    defaults
sphinx                    1.7.4                    py36_0    defaults
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.8                    py36_0    defaults
spyder-kernels            1.4.0                    py36_0    defaults
sqlalchemy                1.2.7            py36hb402a30_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
statsmodels               0.12.2                   pypi_0    pypi
sympy                     1.1.1            py36h7f3cf04_0    defaults
tabulate                  0.8.10                   pypi_0    pypi
tbb                       2020.0               h04f5b5a_0    defaults
tbb4py                    2020.0           py36h04f5b5a_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
tenacity                  8.0.1                    pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.0                    pypi_0    pypi
tensorboardx              2.5.1                    pypi_0    pypi
tensorflow                2.6.2                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
tensorflow-gpu            1.1.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
threadpoolctl             2.1.0                    pypi_0    pypi
tk                        8.6.8                ha441bb4_0    defaults
tokenizers                0.10.3                   pypi_0    pypi
toolz                     0.9.0                    py36_0    defaults
torch                     1.10.2                   pypi_0    pypi
torchtext                 0.11.2                   pypi_0    pypi
torchvision               0.11.1                   pypi_0    pypi
tornado                   5.0.2                    py36_0    defaults
tqdm                      4.64.1                   pypi_0    pypi
traitlets                 4.3.2            py36h65bd3ce_0    defaults
transformers              4.11.0                   pypi_0    pypi
trectools                 0.0.49                   pypi_0    pypi
twisted                   21.2.0           py36h9ed2024_0    defaults
typed-ast                 1.4.3            py36h9ed2024_1    defaults
typing                    3.6.4                    py36_0    defaults
typing-extensions         3.7.4.3                  pypi_0    pypi
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.6                h3efe00b_0    defaults
urllib3                   1.26.7                   pypi_0    pypi
virtualenv                20.16.4                  pypi_0    pypi
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  2.0.2                    pypi_0    pypi
wheel                     0.37.0                   pypi_0    pypi
widgetsnbextension        3.2.1                    py36_0    defaults
wrapt                     1.12.1                   pypi_0    pypi
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.4                    py36_0    defaults
xlwings                   0.11.8                   py36_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xmltodict                 0.12.0             pyhd3eb1b0_0    defaults
xxhash                    3.1.0                    pypi_0    pypi
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
yarl                      1.7.2                    pypi_0    pypi
zeromq                    4.2.5                h378b8a2_0    defaults
zict                      0.1.3            py36h71da714_0    defaults
zipp                      3.6.0              pyhd3eb1b0_0    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
zope                      1.0                      py36_1    defaults
zope.interface            5.4.0            py36h9ed2024_0    defaults
```

**Comment by himilcon** [comment]
I have the same problem. Nothing works anymore

**Comment by DagonArises** [comment]
> I have the same problem. Nothing works anymore

would recommend complete [uninstallation](https://docs.anaconda.com/anaconda/install/uninstall/) + manual installation, instead of reinstalling via terminal commands. will take you 2 hrs max but everything will work afterwards.
i just don't expect the inconsistencies to solve themselves otherwise.

**Comment by himilcon** [comment]
Done! It works now. Thank you!

**Comment by travishathaway** [comment]
Hi @DagonArises,

Thank you for submitting this bug. When I get in to these situations, I've often found that using conda's revisions can be helpful. For example, you can completely revert to the way your base environment was when it was freshly installed by running:

```
conda install --rev 0
```

If that doesn't work, then I would reinstall conda. If you can't even run the install command like that, then conda has gotten itself into a irreparable shape 😭 (sorry!).

This isn't necessarily a bug with conda itself, rather it has to do with conda's dependencies and how they are installed and grouped together. Therefore, this bug may be better if filed in the [Anaconda Issue Tracker](https://github.com/ContinuumIO/anaconda-issues/issues/new/choose). This is where they deal with these types of issues.

Thanks again for the time you took to file this bug report.  I am going to go ahead close it. If you feel like this truly represents a bug within conda itself, then I invite you reopen it so we can continue this discussion.

**Comment by jesusmnv** [comment]
I have the same issue

**Comment by sribhashyamsashanksai** [comment]
> > I have the same problem. Nothing works anymore
> 
> would recommend complete [uninstallation](https://docs.anaconda.com/anaconda/install/uninstall/) + manual installation, instead of reinstalling via terminal commands. will take you 2 hrs max but everything will work afterwards. i just don't expect the inconsistencies to solve themselves otherwise.

can u give me a link to do that
