### ISSUE TITLE
ChunkedConnectionError is not caught in `fetch_repodata_remote_request`

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#12196]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I hit a connection error which resulted in an uncaught exception while building a conda package with conda-build.

Following the traceback leads to `conda.core.subdir_data.fetch_repodata_remote_request`, which features a long list of `except *` clauses. However, this fails to catch `requests.exceptions.ChunkedEncodingError` as one of the potential causes. This exception is behind other reports like https://github.com/conda/conda/issues/10555, https://github.com/conda/conda/issues/10274 and https://github.com/conda/conda/issues/10314.

I suggest we provide some messaging on this connection error, instead of the letting the (long) traceback hit the terminal.

```
Collecting package metadata (repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "urllib3/response.py", line 761, in _update_chunk_length
    ValueError: invalid literal for int() with base 16: b''
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "urllib3/response.py", line 444, in _error_catcher
      File "urllib3/response.py", line 828, in read_chunked
      File "urllib3/response.py", line 765, in _update_chunk_length
    urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "requests/models.py", line 816, in generate
      File "urllib3/response.py", line 624, in stream
      File "urllib3/response.py", line 857, in read_chunked
      File "contextlib.py", line 137, in __exit__
      File "urllib3/response.py", line 461, in _error_catcher
    urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "conda/exceptions.py", line 1118, in __call__
      File "conda/cli/main.py", line 69, in main_subshell
      File "conda/cli/conda_argparse.py", line 91, in do_call
      File "conda/notices/core.py", line 109, in wrapper
      File "conda/cli/main_install.py", line 20, in execute
      File "conda/cli/install.py", line 264, in install
      File "conda/core/solve.py", line 136, in solve_for_transaction
      File "conda/core/solve.py", line 179, in solve_for_diff
      File "conda/core/solve.py", line 284, in solve_final_state
      File "conda/common/io.py", line 84, in decorated
      File "conda/core/solve.py", line 451, in _collect_all_metadata
      File "conda/core/solve.py", line 1061, in _prepare
      File "conda/core/index.py", line 272, in get_reduced_index
      File "conda/core/subdir_data.py", line 142, in query_all
      File "concurrent/futures/_base.py", line 609, in result_iterator
      File "concurrent/futures/_base.py", line 446, in result
      File "concurrent/futures/_base.py", line 391, in __get_result
      File "concurrent/futures/thread.py", line 58, in run
      File "conda/core/subdir_data.py", line 131, in <lambda>
      File "conda/core/subdir_data.py", line 147, in query
      File "conda/core/subdir_data.py", line 213, in load
      File "conda/core/subdir_data.py", line 303, in _load
      File "conda/core/subdir_data.py", line 571, in fetch_repodata_remote_request
      File "requests/sessions.py", line 600, in get
      File "requests/sessions.py", line 587, in request
      File "requests/sessions.py", line 745, in send
      File "requests/models.py", line 899, in content
      File "requests/models.py", line 818, in generate
    requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))

`$ /Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/standalone_conda/conda.exe install -y -p ./env_test napari-menu --no-deps`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
           CONDA_BLD_PATH=/Users/jrodriguez/tmp/bld
              CONDA_BUILD=1
        CONDA_BUILD_STATE=TEST
        CONDA_DEFAULT_ENV=/Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placeh
                CONDA_EXE=/Users/jrodriguez/.local/anaconda/bin/conda
                CONDA_LUA=5
                CONDA_NPY=116
               CONDA_PERL=5.26
             CONDA_PREFIX=/Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placeh
           CONDA_PREFIX_1=/Users/jrodriguez/.local/anaconda
           CONDA_PREFIX_2=/Users/jrodriguez/.local/anaconda/envs/conda-standalone-dev
           CONDA_PREFIX_3=/Users/jrodriguez/.local/anaconda
    CONDA_PROMPT_MODIFIER=(/Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_pl
                          acehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
                          acehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
                          acehold_placehold_placehold_placehold_placeh)
                 CONDA_PY=39
         CONDA_PYTHON_EXE=/Users/jrodriguez/.local/anaconda/bin/python
                  CONDA_R=3.5
               CONDA_ROOT=/Users/jrodriguez/.local/anaconda
              CONDA_SHLVL=4
             CONDA_SOLVER=classic
           CURL_CA_BUNDLE=<not set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placeh:/Users/jrodriguez/tmp/bld/
                          conda-standalone_1671739584333/_test_env_placehold_placehold_placehold
                          _placehold_placehold_placehold_placehold_placehold_placehold_placehold
                          _placehold_placehold_placehold_placehold_placehold_placehold_placehold
                          _placehold_placeh/bin:/Users/jrodriguez/tmp/bld/conda-standalone_16717
                          39584333/_test_env_placehold_placehold_placehold_placehold_placehold_p
                          lacehold_placehold_placehold_placehold_placehold_placehold_placehold_p
                          lacehold_placehold_placehold_placehold_placehold_placehold_placeh/bin:
                          /Users/jrodriguez/.local/anaconda/condabin:/opt/homebrew/bin:/opt/home
                          brew/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
          PKG_CONFIG_PATH=/Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placeh/lib/pkgconfig
                   PYTHON=/Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placehold_placehold_placehold_pla
                          cehold_placehold_placehold_placehold_placeh/bin/python
         PYTHONNOUSERSITE=1
       REQUESTS_CA_BUNDLE=
            SSL_CERT_FILE=<not set>

     active environment : /Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
    active env location : /Users/jrodriguez/tmp/bld/conda-standalone_1671739584333/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh
            shell level : 4
       user config file : /Users/jrodriguez/.condarc
 populated config files : /Users/jrodriguez/.local/anaconda/.condarc
                          /Users/jrodriguez/.condarc
          conda version : 22.11.1.post1
    conda-build version : not installed
         python version : 3.9.15.final.0
       virtual packages : __archspec=1=arm64
                          __osx=11.2.3=0
                          __unix=0=0
       base environment : /var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/_MEIJe5Mrt  (read only)
      conda av data dir : /var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/_MEIJe5Mrt/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/_MEIJe5Mrt/pkgs
                          /Users/jrodriguez/.conda/pkgs
       envs directories : /Users/jrodriguez/.conda/envs
                          /var/folders/1b/z374sygs1s96t_xxxv0hr3lr0000gn/T/_MEIJe5Mrt/envs
               platform : osx-arm64
             user-agent : conda/22.11.1.post1 requests/2.28.1 CPython/3.9.15 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

### Conda Info

```shell
See above
```

### Conda Config

```shell
==> /Users/jrodriguez/.local/anaconda/.condarc <==
channels:
  - conda-forge

==> /Users/jrodriguez/.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
channel_priority: strict
channels:
  - conda-forge
show_channel_urls: True
experimental_solver: libmamba
```

### Conda list

```shell
This was a test environment created by conda-build 3.23.3, running on conda 22.11.1 and conda-libmamba-solver 22.12.0.
```

**Comment by AndreaGiardini** [comment]
Any workaround for this issue? I am hitting this consistently:

```
#0 9.559 Collecting package metadata (current_repodata.json): ...working... done
#0 94.07 Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
#0 139.7 Solving environment: ...working... failed with repodata from current_repodata.json, will retry with next repodata source.
#0 218.8 Collecting package metadata (repodata.json): ...working... failed
#0 309.0
#0 309.0 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
#0 309.0
#0 309.0     Traceback (most recent call last):
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 700, in _update_chunk_length
#0 309.0         self.chunk_left = int(line, 16)
#0 309.0     ValueError: invalid literal for int() with base 16: b''
#0 309.0
#0 309.0     During handling of the above exception, another exception occurred:
#0 309.0
#0 309.0     Traceback (most recent call last):
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 441, in _error_catcher
#0 309.0         yield
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 767, in read_chunked
#0 309.0         self._update_chunk_length()
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 704, in _update_chunk_length
#0 309.0         raise InvalidChunkLength(self, line)
#0 309.0     urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
#0 309.0
#0 309.0     During handling of the above exception, another exception occurred:
#0 309.0
#0 309.0     Traceback (most recent call last):
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 760, in generate
#0 309.0         for chunk in self.raw.stream(chunk_size, decode_content=True):
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 575, in stream
#0 309.0         for line in self.read_chunked(amt, decode_content=decode_content):
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 755, in read_chunked
#0 309.0         with self._error_catcher():
#0 309.0       File "/opt/conda/lib/python3.10/contextlib.py", line 153, in __exit__
#0 309.0         self.gen.throw(typ, value, traceback)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/urllib3/response.py", line 458, in _error_catcher
#0 309.0         raise ProtocolError("Connection broken: %r" % e, e)
#0 309.0     urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
#0 309.0
#0 309.0     During handling of the above exception, another exception occurred:
#0 309.0
#0 309.0     Traceback (most recent call last):
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1082, in __call__
#0 309.0         return func(*args, **kwargs)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/cli/main.py", line 87, in _main
#0 309.0         exit_code = do_call(args, p)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
#0 309.0         return getattr(module, func_name)(args, parser)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/cli/main_install.py", line 20, in execute
#0 309.0         install(args, parser, 'install')
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/cli/install.py", line 260, in install
#0 309.0         unlink_link_transaction = solver.solve_for_transaction(
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
#0 309.0         unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 195, in solve_for_diff
#0 309.0         final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 300, in solve_final_state
#0 309.0         ssc = self._collect_all_metadata(ssc)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/common/io.py", line 88, in decorated
#0 309.0         return f(*args, **kwds)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
#0 309.0         index, r = self._prepare(prepared_specs)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/solve.py", line 1058, in _prepare
#0 309.0         reduced_index = get_reduced_index(self.prefix, self.channels,
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/index.py", line 288, in get_reduced_index
#0 309.0         new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 140, in query_all
#0 309.0         result = tuple(concat(executor.map(subdir_query, channel_urls)))
#0 309.0       File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 609, in result_iterator
#0 309.0         yield fs.pop().result()
#0 309.0       File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 446, in result
#0 309.0         return self.__get_result()
#0 309.0       File "/opt/conda/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
#0 309.0         raise self._exception
#0 309.0       File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
#0 309.0         result = self.fn(*self.args, **self.kwargs)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 132, in <lambda>
#0 309.0         subdir_query = lambda url: tuple(SubdirData(Channel(url), repodata_fn=repodata_fn).query(
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 145, in query
#0 309.0         self.load()
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 210, in load
#0 309.0         _internal_state = self._load()
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 375, in _load
#0 309.0         raw_repodata_str = fetch_repodata_remote_request(
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 701, in fetch_repodata_remote_request
#0 309.0         resp = session.get(join_url(url, filename), headers=headers, proxies=session.proxies,
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 542, in get
#0 309.0         return self.request('GET', url, **kwargs)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 529, in request
#0 309.0         resp = self.send(prep, **send_kwargs)
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/requests/sessions.py", line 687, in send
#0 309.0         r.content
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 838, in content
#0 309.0         self._content = b''.join(self.iter_content(CONTENT_CHUNK_SIZE)) or b''
#0 309.0       File "/opt/conda/lib/python3.10/site-packages/requests/models.py", line 763, in generate
#0 309.0         raise ChunkedEncodingError(e)
#0 309.0     requests.exceptions.ChunkedEncodingError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
#0 309.0
#0 309.0 `$ /opt/conda/bin/conda install -n base conda-libmamba-solver conda=23.1.0`
#0 309.0
#0 309.0   environment variables:
#0 309.0                  CIO_TEST=<not set>
#0 309.0                 CONDA_DIR=/opt/conda
#0 309.0            CONDA_ENV_FILE=conda_env.yml
#0 309.0                CONDA_ROOT=/opt/conda
#0 309.0            CURL_CA_BUNDLE=<not set>
#0 309.0                      PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
#0 309.0                           :/bin
#0 309.0        REQUESTS_CA_BUNDLE=<not set>
#0 309.0             SSL_CERT_FILE=<not set>
#0 309.0
#0 309.0      active environment : None
#0 309.0        user config file : /home/jovyan/.condarc
#0 309.0  populated config files : /opt/conda/.condarc
#0 309.0                           /home/jovyan/.condarc
#0 309.0           conda version : 4.12.0
#0 309.0     conda-build version : not installed
#0 309.0          python version : 3.10.4.final.0
#0 309.0        virtual packages : __linux=5.15.82=0
#0 309.0                           __glibc=2.31=0
#0 309.0                           __unix=0=0
#0 309.0                           __archspec=1=x86_64
#0 309.0        base environment : /opt/conda  (writable)
#0 309.0       conda av data dir : /opt/conda/etc/conda
#0 309.0   conda av metadata url : None
#0 309.0            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
#0 309.0                           https://conda.anaconda.org/conda-forge/noarch
#0 309.0           package cache : /opt/conda/pkgs
#0 309.0                           /home/jovyan/.conda/pkgs
#0 309.0        envs directories : /opt/conda/envs
#0 309.0                           /home/jovyan/.conda/envs
#0 309.0                platform : linux-64
#0 309.0              user-agent : conda/4.12.0 requests/2.27.1 CPython/3.10.4 Linux/5.15.82-0-virt ubuntu/20.04.4 glibc/2.31
#0 309.0                 UID:GID : 0:0
#0 309.0              netrc file : None
#0 309.0            offline mode : False
#0 309.0
#0 309.0
#0 309.0 An unexpected error has occurred. Conda has prepared the above report.
#0 309.0
#0 309.7 Upload successful.
-
```

**Comment by F0RMaTC** [comment]
Hi,

I am also experiencing the same problem but i can reproduce it with a simple curl command:
```
(base) root@70969a9230a0:/# curl -O https://repo.anaconda.com/pkgs/main/linux-64/python-3.10.9-h7a1cb2a_1.conda -v
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 104.16.130.3:443...
* Connected to repo.anaconda.com (104.16.130.3) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
} [5 bytes data]
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
} [512 bytes data]
* TLSv1.3 (IN), TLS handshake, Server hello (2):
{ [122 bytes data]
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
{ [19 bytes data]
* TLSv1.3 (IN), TLS handshake, Certificate (11):
{ [2334 bytes data]
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
{ [80 bytes data]
* TLSv1.3 (IN), TLS handshake, Finished (20):
{ [52 bytes data]
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
} [1 bytes data]
* TLSv1.3 (OUT), TLS handshake, Finished (20):
} [52 bytes data]
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=Cloudflare, Inc.; CN=sni.cloudflaressl.com
*  start date: Jun 12 00:00:00 2022 GMT
*  expire date: Jun 12 23:59:59 2023 GMT
*  subjectAltName: host "repo.anaconda.com" matched cert's "*.anaconda.com"
*  issuer: C=US; O=Cloudflare, Inc.; CN=Cloudflare Inc ECC CA-3
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
} [5 bytes data]
* Using Stream ID: 1 (easy handle 0x55aeac0ef2c0)
} [5 bytes data]
> GET /pkgs/main/linux-64/python-3.10.9-h7a1cb2a_1.conda HTTP/2
> Host: repo.anaconda.com
> user-agent: curl/7.74.0
> accept: */*
> 
* OpenSSL SSL_read: Connection reset by peer, errno 104
* Failed receiving HTTP2 data
} [5 bytes data]
* OpenSSL SSL_write: Broken pipe, errno 32
* Failed sending HTTP2 data
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Connection #0 to host repo.anaconda.com left intact
curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
```


It randomly fails.
Maybe something todo with cloudflare?

**Comment by jaimergp** [comment]
[One more example in CI](https://github.com/conda/conda-libmamba-solver/actions/runs/4419833225/jobs/7748768931#step:4:153).

---

@F0RMaTC are you seeing this consistently? Is this on Docker? Have you checked your MTU configuration? I've seen weird stuff with proxies, VPNs and whatnot 😬

**Comment by F0RMaTC** [comment]
> [One more example in CI](https://github.com/conda/conda-libmamba-solver/actions/runs/4419833225/jobs/7748768931#step:4:153).
> 
> @F0RMaTC are you seeing this consistently? Is this on Docker? Have you checked your MTU configuration? I've seen weird stuff with proxies, VPNs and whatnot 😬

It turned out that it was a problem with NPU/Hardware offloading on my fortigates
