### ISSUE TITLE
Xonsh autocompleter assumes Xonsh is inside Conda env

### ISSUE THREAD

**Issue by Maxwellfire** [conda/conda#12205]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I have xonsh installed in my system not using conda (using a system pipx env, since I want it available as the system shell).

The default conda hooks for xonsh (accessed using `conda shell.xonsh hook` ), in `_get_envs_unfiltered()` includes the line 
```
config = importlib.import_module('conda.config')
```
This seems to assume that the script is being run from a xonsh shell that has access to the conda module. This is true when xonsh is installed inside conda, but is not true when it isn't. 

This leads to the following issue: When I try to tabcomplete a `conda activate` command with the list of envs, I instead get an error 

```
Completer _conda_completer raises exception when gets old_args=('', 'conda activate ', 15, 15) / completion_context=CompletionContext(command=CommandContext(args=(CommandArg(value='conda', opening_quote='', closing_quote='', is_io_redir=False), CommandArg(value='activate', opening_quote='', closing_quote='', is_io_redir=False)), arg_index=2, prefix='', suffix='', opening_quote='', closing_quote='', is_after_closing_quote=False, subcmd_opening=''), python=PythonContext('conda activate ', 15, is_sub_expression=False)):
<class 'ModuleNotFoundError'> - No module named 'conda'
Traceback (most recent call last):
  File "$(/home/max/Tools/anaconda3/bin/conda shell.xonsh hook)", line 127, in _get_envs_unfiltered
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'conda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/completer.py", line 186, in generate_completions
    out = func(*old_completer_args)
  File "$(/home/max/Tools/anaconda3/bin/conda shell.xonsh hook)", line 180, in _conda_completer
  File "$(/home/max/Tools/anaconda3/bin/conda shell.xonsh hook)", line 160, in _get_envs
  File "$(/home/max/Tools/anaconda3/bin/conda shell.xonsh hook)", line 130, in _get_envs_unfiltered
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'conda'
```

 

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : /home/max/.condarc
 populated config files : 
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __cuda=12.0=0
                          __linux=5.19.0=0
                          __glibc=2.36=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/max/Tools/anaconda3  (writable)
      conda av data dir : /home/max/Tools/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/max/Tools/anaconda3/pkgs
                          /home/max/.conda/pkgs
       envs directories : /home/max/Tools/anaconda3/envs
                          /home/max/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.19.0-26-generic ubuntu/22.10 glibc/2.36
                UID:GID : 1000:1000
             netrc file : /home/max/.netrc
           offline mode : False
```

### Conda Config

```shell
==> envvars <==
auto_activate_base: False
```

### Conda list

This is not being run from within an environment, but the error persists in all environments since env activations don't change what packages are available in the current xonsh shell

**Comment by travishathaway** [comment]
Hi @Maxwellfire,

Thanks for filing this bug. We have categorized this issue and will attempt to address it when we can. Please do not expect a quick turn-around though as these types of shell integration issues are currently not a very high priority for us.

In meantime, if you feel you can attempt a fix, you are more than welcome to submit a pull request yourself to address this.

**Comment by urevic** [comment]
The code of  _get_envs_unfiltered() is in conda/shell/conda.xsh. I fixed the issue locally by rewriting the function using parsing output of "conda env list" instead of using conda.config module. I can do a pull request with the fix, but I'm not sure how to test this function. Seems like this function is left untested currently.
