### ISSUE TITLE
failed to run: 'conda info --json': "FileNotFoundError(2, 'No such file or directory')"

### ISSUE THREAD

**Issue by Youssouf5484** [conda/conda#12200]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

An unexpected error occurred on Navigator start-up

### Additional Context

Traceback (most recent call last):
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/conda_api.py", line 77, in _call_conda
    (p, stdout_lines, stderr_lines) = streaming_popen.popen(cmd_list,
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/streaming_popen.py", line 83, in popen
    p = logged_subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/logged_subprocess.py", line 27, in Popen
    return subprocess.Popen(args=args, **kwargs)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/widgets/main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 1525, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/anaconda_api.py", line 80, in __init__
    self._project_api = ProjectAPI()
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/project_api.py", line 182, in ProjectAPI
    PROJECT_API = _ProjectAPIWrapper()
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_navigator/api/project_api.py", line 62, in __init__
    from anaconda_project.api import AnacondaProject
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/api.py", line 24, in 
    from anaconda_project import prepare, project, provide, project_ops
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/prepare.py", line 19, in 
    from anaconda_project.internal import conda_api
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/conda_api.py", line 643, in 
    _default_platforms_with_current = tuple(sorted(list(set(default_platforms + (current_platform(), )))))
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/conda_api.py", line 639, in current_platform
    conda_info = info()
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/conda_api.py", line 126, in info
    return _call_and_parse_json(['info', '--json'], platform=platform)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/conda_api.py", line 113, in _call_and_parse_json
    out = _call_conda(extra_args, json_mode=True, platform=platform)
  File "/Users/hollandediarragmail.com/opt/anaconda3/lib/python3.8/site-packages/anaconda_project/internal/conda_api.py", line 82, in _call_conda
    raise CondaError("failed to run: %r: %r" % (command_in_errors, repr(e)))
anaconda_project.internal.conda_api.CondaError: failed to run: 'conda info --json': "FileNotFoundError(2, 'No such file or directory')"

**Comment by dholth** [comment]
@Youssouf5484 please check that the January conda release solves this issue

**Comment by m4gaikwad** [comment]
Facing same issue on Linux Mint 21.1 .


Traceback (most recent call last): 
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/conda_api.py", line 80, in _call_conda
    stderr_callback=stderr_callback)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/streaming_popen.py", line 83, in popen
    p = logged_subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/logged_subprocess.py", line 27, in Popen
    return subprocess.Popen(args=args, **kwargs)
  File "/home/mayur/anaconda3/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/mayur/anaconda3/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 170, in __init__
    self.api = AnacondaAPI()
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 1600, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 81, in __init__
    self._project_api = ProjectAPI()
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/project_api.py", line 182, in ProjectAPI
    PROJECT_API = _ProjectAPIWrapper()
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/project_api.py", line 62, in __init__
    from anaconda_project.api import AnacondaProject
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/api.py", line 24, in 
    from anaconda_project import prepare, project, provide, project_ops
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/prepare.py", line 19, in 
    from anaconda_project.internal import conda_api
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/conda_api.py", line 643, in 
    _default_platforms_with_current = tuple(sorted(list(set(default_platforms + (current_platform(), )))))
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/conda_api.py", line 639, in current_platform
    conda_info = info()
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/conda_api.py", line 126, in info
    return _call_and_parse_json(['info', '--json'], platform=platform)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/conda_api.py", line 113, in _call_and_parse_json
    out = _call_conda(extra_args, json_mode=True, platform=platform)
  File "/home/mayur/anaconda3/lib/python3.7/site-packages/anaconda_project/internal/conda_api.py", line 82, in _call_conda
    raise CondaError("failed to run: %r: %r" % (command_in_errors, repr(e)))
anaconda_project.internal.conda_api.CondaError: failed to run: 'conda info --json': 'FileNotFoundError(2, "No such file or directory: \'conda\'")'

**Comment by jezdez** [comment]
I can't reproduce this sadly.

**Comment by Ocnos936** [comment]
I faced the same problem when trying to launch the Anaconda Navigator. However, I successfully launched it by typing Anaconda navigator rather than clicking the application icon.
