### ISSUE TITLE
pytest -v -k notices_appear_once fails on OSX

### ISSUE THREAD

**Issue by dholth** [conda/conda#12247]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In a conda checkout on osx, revision 48f51e6c1d412270efbbdb1d9ff571087568b6ea,

```
. dev/start -p 3.10
% pytest -v -k notices_appear_once
=============================================== test session starts ================================================
platform darwin -- Python 3.10.8, pytest-7.1.2, pluggy-1.0.0 -- /Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/bin/python
cachedir: .pytest_cache
rootdir: /Users/dholth/prog/conda, configfile: setup.cfg, testpaths: conda, tests
plugins: xdoctest-1.1.0, xdist-2.5.0, xprocess-0.22.2, split-0.8.0, mock-3.7.0, rerunfailures-10.1, timeout-1.4.2, forked-1.3.0, cov-3.0.0
collected 1150 items / 1149 deselected / 1 selected

tests/cli/test_main_notices.py::test_notices_appear_once_when_running_decorated_commands FAILED              [100%]

===================================================== FAILURES =====================================================
_____________________________ test_notices_appear_once_when_running_decorated_commands _____________________________
Traceback (most recent call last):
  File "/Users/dholth/prog/conda/tests/cli/test_main_notices.py", line 269, in test_notices_appear_once_when_running_decorated_commands
    assert args == ([],)
AssertionError: assert ([('file:///U...', 'local')],) == ([],)
  At index 0 diff: [('file:///Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/conda-bld/notices.json', 'local')] != []
  Full diff:
    (
  -  [],,
  +  [('file:///Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/conda-bld/notices.json',
  +    'local')],,
    )
---------------------------------------------- Captured stdout setup -----------------------------------------------
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/env-one



Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate env-one
#
# To deactivate an active environment, use
#
#     $ conda deactivate


---------------------------------------------- Captured stderr setup -----------------------------------------------

----------------------------------------------- Captured stdout call -----------------------------------------------
Retrieving notices: ...working... done
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

----------------------------------------------- Captured stderr call -----------------------------------------------

PackagesNotFoundError: The following packages are not available from current channels:

  - does_not_exist

Current channels:

  - file:///Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/conda-bld/osx-arm64
  - file:///Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/conda-bld/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.



--------------------------------------------- Captured stdout teardown ---------------------------------------------
No packages found in /Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/env-one. Continuing environment removal

--------------------------------------------- Captured stderr teardown ---------------------------------------------

Remove all packages in environment /Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/envs/env-one:


================================================= warnings summary =================================================
devenv/Darwin/arm64/envs/devenv-3.10-c/lib/python3.10/site-packages/botocore/httpsession.py:41
  /Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/lib/python3.10/site-packages/botocore/httpsession.py:41: DeprecationWarning: 'urllib3.contrib.pyopenssl' module is deprecated and will be removed in a future release of urllib3 2.x. Read more in this issue: https://github.com/urllib3/urllib3/issues/2680
    from urllib3.contrib.pyopenssl import orig_util_SSLContext as SSLContext

conda/lock.py:24
  /Users/dholth/prog/conda/conda/lock.py:24: PendingDeprecationWarning: The `conda.lock` module is pending deprecation and will be removed in a future release. Please use `filelock` instead.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
--------------------------- generated xml file: /Users/dholth/prog/conda/test-report.xml ---------------------------
=============================================== slowest 16 durations ===============================================
0.33s setup    tests/cli/test_main_notices.py::test_notices_appear_once_when_running_decorated_commands
0.09s teardown tests/cli/test_main_notices.py::test_notices_appear_once_when_running_decorated_commands
0.02s call     tests/cli/test_main_notices.py::test_notices_appear_once_when_running_decorated_commands
============================================= short test summary info ==============================================
FAILED tests/cli/test_main_notices.py::test_notices_appear_once_when_running_decorated_commands - AssertionError:...
================================== 1 failed, 1149 deselected, 2 warnings in 2.83s ==================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```

**Comment by dholth** [comment]
I tried making an empty channel to point conda at, instead of -c local. It's a directory with a noarch subdirectory, with `python -m conda_index --channeldata /tmp/index-empty` to make a channel. An empty `{}` /tmp/index-empty/notices.json was also added.

The test was changed to run

`f"conda install -n {env_one} -c file:///tmp/index-empty --override-channels -y does_not_exist",
`
```
___________ test_notices_appear_once_when_running_decorated_commands ___________
Traceback (most recent call last):
  File "/Users/dholth/prog/conda/tests/cli/test_main_notices.py", line 269, in test_notices_appear_once_when_running_decorated_commands
    assert args == ([],)
AssertionError: assert ([('file:///tmp/index-empty/notices.json', 'index-empty')],) == ([],)
  At index 0 diff: [('file:///tmp/index-empty/notices.json', 'index-empty')] != []
  Full diff:
  - ([],)
  + ([('file:///tmp/index-empty/notices.json', 'index-empty')],)
```

**Comment by dholth** [comment]
I moved ~/miniconda3/conda-bld out of the way, this made the test pass with -c local, then moved ~/miniconda3/conda-bld back to its original place and the test continued to pass. Very strange.

It is odd that the dev environment ~/prog/conda/devenv/... finds global miniconda at all... and there must be a problem with some related cache file / mtime / that causes the notices to fetch...

**Comment by dholth** [comment]
Works now.
