### ISSUE TITLE
An unexpected error has occurred when updating app ipython-notebook

### ISSUE THREAD

**Issue by ws772** [conda/conda#1229]
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\ShaoW\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Users\ShaoW\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Users\ShaoW\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 316, in install
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "C:\Users\ShaoW\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 425, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Users\ShaoW\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 273, in ensure_linked_actions
    if install.try_hard_link(config.pkgs_dirs[0], prefix, dist):
  File "C:\Users\ShaoW\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 382, in try_hard_link
    assert isfile(src)
AssertionError

**Comment by soapy1** [comment]
@ws772  is this still an issue for you?
