### ISSUE TITLE
channel notices doesn't handle i/o errors

### ISSUE THREAD

**Issue by beckermr** [conda/conda#12310]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I was running conda, and on the system I am on, sometimes I cannot access my home dir. conda flaked out due to an io error.

### Conda Info

```shell
$ conda info

     active environment : base
    active env location : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3
            shell level : 1
       user config file : /u/ki/beckermr/.condarc
 populated config files : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/.condarc
                          /u/ki/beckermr/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.12=0
                          __linux=2.6.32=0
                          __unix=0=0
       base environment : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3  (writable)
      conda av data dir : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/pkgs
                          /u/ki/beckermr/.conda/pkgs
       envs directories : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/envs
                          /u/ki/beckermr/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.9 Linux/2.6.32-754.33.1.el6.x86_64 rhel/6.10 glibc/2.12 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.1.0
                UID:GID : 10150:1092
             netrc file : /u/ki/beckermr/.netrc
           offline mode : False
```

### Conda Config

```shell
$ conda config --show-sources
==> /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/.condarc <==
channels:
  - conda-forge

==> /u/ki/beckermr/.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults
solver: libmamba
```

### Conda list

```shell
$ conda list --show-channel-urls
# packages in environment at /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotlipy                  0.7.0           py39hb9d737c_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39he91dace_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     22.11.1          py39hf3d152e_1    conda-forge
conda-libmamba-solver     22.12.0            pyhd8ed1ab_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
cryptography              38.0.4           py39h3ccb8fc_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.2.0              pyha770c72_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.39                 hcc3a1bd_1    conda-forge
libarchive                3.6.2                h3d51595_0    conda-forge
libcurl                   7.87.0               hdc1c0ab_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  1.1.0                hde2b089_3    conda-forge
libmambapy                1.1.0            py39hf0aba66_3    conda-forge
libnghttp2                1.47.0               hff17c54_1    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.23               h3eb15da_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
lz4-c                     1.9.3                h9c3ff4c_1    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.1.0            py39hc5d2bb1_3    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
openssl                   3.0.7                h0b41bf4_1    conda-forge
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4            py39hb9d737c_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.9           h543edf9_0_cpython    conda-forge
python_abi                3.9                      3_cp39    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.28.1             pyhd8ed1ab_1    conda-forge
ruamel.yaml               0.17.21          py39hb9d737c_2    conda-forge
ruamel.yaml.clib          0.2.7            py39h72bdee0_1    conda-forge
ruamel_yaml               0.15.80         py39hb9d737c_1008    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.37.0               h9cd32fc_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.13            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zipp                      3.11.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.19.0           py39h29414ee_1    conda-forge
zstd                      1.5.2                h6239696_4    conda-forge
```

### Additional Context

```
$ conda update --all
Retrieving notices: ...working... done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/site-packages/conda/exceptions.py", line 1118, in __call__
        return func(*args, **kwargs)
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/site-packages/conda/notices/core.py", line 98, in wrapper
        channel_notice_set = retrieve_notices(
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/site-packages/conda/notices/core.py", line 47, in retrieve_notices
        cache_file.touch()
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/pathlib.py", line 1315, in touch
        fd = self._raw_open(flags, mode)
      File "/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/lib/python3.9/pathlib.py", line 1127, in _raw_open
        return self._accessor.open(self, flags, mode)
    PermissionError: [Errno 13] Permission denied: '/u/ki/beckermr/.cache/conda/notices/notices.cache'

`$ /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/bin/conda update --all`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/bin/conda
             CONDA_PREFIX=/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/bin/python
               CONDA_ROOT=/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/opt/lsf-openmpi/1.8.1/lib
               LD_PRELOAD=<not set>
                  MANPATH=/opt/lsf-openmpi/1.8.1/man:
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                     PATH=/nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/bin:/nfs/slac/des/fs1/g/
                          sims/beckermr/mambaforge3/condabin:/nfs/slac/des/fs1/g/sims/beckermr/s
                          cripts:/opt/lsf-openmpi/1.8.1/bin:/u/ki/beckermr/bin:/usr/local/bin:/b
                          in:/usr/bin:/usr/etc:/usr/afsws/bin:/usr/afsws/etc:/usr/bin/X11:.
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3
            shell level : 1
       user config file : /u/ki/beckermr/.condarc
 populated config files : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/.condarc
                          /u/ki/beckermr/.condarc
          conda version : 22.11.1
    conda-build version : not installed
         python version : 3.9.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.12=0
                          __linux=2.6.32=0
                          __unix=0=0
       base environment : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3  (writable)
      conda av data dir : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/pkgs
                          /u/ki/beckermr/.conda/pkgs
       envs directories : /nfs/slac/des/fs1/g/sims/beckermr/mambaforge3/envs
                          /u/ki/beckermr/.conda/envs
               platform : linux-64
             user-agent : conda/22.11.1 requests/2.28.1 CPython/3.9.9 Linux/2.6.32-754.33.1.el6.x86_64 rhel/6.10 glibc/2.12 solver/libmamba conda-libmamba-solver/22.8.1 libmambapy/1.1.0
                UID:GID : 10150:1092
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n

```

**Comment by travishathaway** [comment]
Hi @beckermr,

Thanks for filing this. In the meantime you should be able to disable notices completely by setting `number_channel_notices: 0` in your configuration.

**Comment by travishathaway** [comment]
@beckerm,

Still need to write a test, but I think this is essentially what we need:
- https://github.com/conda/conda/pull/12312

**Comment by travishathaway** [comment]
☝️ pull request above should resolve this issue. Closing for now. Please re-open if this continues to be an issue.

**Comment by rishabh11336** [comment]
Help! with cla i have already signed it but bot is promoting I have not. I am trying to make my 1st contribution
