### ISSUE TITLE
`AssertionError('Prefix record insertion error: a record with name ca-certificates already exists in the prefix.)`

### ISSUE THREAD

**Issue by xelmirage** [conda/conda#12339]
### What happened?

I'm creating a new conda env and installing python 3.9.0

> conda install python==3.9.0

conda version is 22.9.0

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : pygeoar
    active env location : C:\Users\user\miniconda3\envs\pygeoar
            shell level : 3
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 22.9.0
    conda-build version : not installed
         python version : 3.9.12.final.0
       virtual packages : __cuda=9.2=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\user\miniconda3  (writable)
      conda av data dir : C:\Users\user\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : C:\Users\user\miniconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\miniconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.19041
          administrator : False
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> C:\Users\user\.condarc <==
ssl_verify: False
channel_alias: https://mirrors.tuna.tsinghua.edu.cn/anaconda
channels:
  - defaults
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  open3d-admin: https://anaconda.org
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
show_channel_urls: True
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at C:\Users\user\miniconda3\envs\pygeoar:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.01.10           haa95532_0    defaults
libffi                    3.4.2                hd77b12b_6    defaults
openssl                   1.1.1s               h2bbff1b_0    defaults
pip                       22.3.1          py310haa95532_0    defaults
python                    3.10.9               h966fe2a_0    defaults
setuptools                65.6.3          py310haa95532_0    defaults
sqlite                    3.40.1               h2bbff1b_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wincertstore              0.2             py310haa95532_2    defaults
xz                        5.2.10               h8cc25b3_1    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
```

</details>

### Additional Context

windows 10 professional

**Comment by beeankha** [comment]
Hi @xelmirage , thanks for taking the time to file this issue.

Are you creating an env completely from scratch, or are you creating it from an exported env file (from either a command like `conda list --export > requirements.txt` or `conda env export [envname]>env.yml`)? If you're creating an env from an exported file, please post the contents of that file in this issue so that we can take a look.

**Comment by xelmirage** [comment]
Hi@beeankha, I am creating an env completely from scratch. The `conda list` result is the packages installed so far.

**Comment by pelson** [comment]
3 weeks doesn't look stale to me. I don't have the case to hand, but also saw this with the latest release of conda (linux-64).

**Comment by jezdez** [comment]
> 3 weeks doesn't look stale to me. I don't have the case to hand, but also saw this with the latest release of conda (linux-64).

Huh, seems like a bot gone awry, sorry about that!

**Comment by travishathaway** [comment]
Hi all,

I just want to provide an update on this issue. I attempted to try to recreate this today with no luck. Here's the steps I followed:

1. Create a new environment with the following command:
```
conda create -n test-12339 python=3.10
```
2. Attempt to install python 3.9 in it with the following command:
```
conda install -n test-12339 python=3.9
```

I did this on Windows 11 Home edition and everything ran successfully. conda version 23.3.1.

@xelmirage, does my testing scenario roughly correlate to what you did when you ran into this error? Has this resolved itself after upgrading to the latest conda?

If updating to the latest conda resolves this issue, I would consider this bug fixed. Otherwise, I'm still unsure what is causing this. Before we can address the issue, we need a way to reliably recreate it.

**Comment by jezdez** [comment]
> > 3 weeks doesn't look stale to me. I don't have the case to hand, but also saw this with the latest release of conda (linux-64).
> 
> Huh, seems like a bot gone awry, sorry about that!

https://github.com/conda/infrastructure/issues/759 is tracking this now

**Comment by Sieboldianus** [comment]
I have the same error. Trying to install Python 3.10.6 into an env that has python=3.10:

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Rolling back transaction: done

AssertionError('Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues')
()
AssertionError()
```

**Comment by phenylalanin91** [comment]
I have the same issue with:
`(base) C:\>mamba update mamba

Looking for: ['mamba']

/win-64 (check zst)                                 Checked  1.2s
/noarch (check zst)                                 Checked  0.3s
/win-64                                             20.4MB @  48.4MB/s  0.6s
/noarch                                             13.1MB @  22.1MB/s  0.6s

Pinned packages:
  - python 3.9.*


Transaction

  Prefix: C:\Mambaforge

  Updating specs:

   - mamba
   - ca-certificates
   - certifi
   - openssl


  Package               Version  Build           Channel          Size
------------------------------------------------------------------------
  Upgrade:
------------------------------------------------------------------------

  - ca-certificates   2021.10.8  h5b45459_0      conda-forge     180kB
  + ca-certificates  2023.11.17  h56e8100_0                      155kB
  - openssl              1.1.1l  h8ffe710_0      conda-forge       6MB
  + openssl               3.2.0  hcfcfb64_1                        8MB
  - certifi           2021.10.8  py39hcbf5309_1  conda-forge     149kB
  + certifi          2023.11.17  pyhd8ed1ab_0                    159kB

  Summary:

No package record found for ca-certificates-2021.10.8-h5b45459_0.tar.bz2!
No package record found for openssl-1.1.1l-h8ffe710_0.tar.bz2!
No package record found for certifi-2021.10.8-py39hcbf5309_1.tar.bz2!

Downloading and Extracting Packages-------------------------------------

Preparing transaction: done
Verifying transaction: done
Executing transaction: done                        158.9kB @ 667.7kB/s  0.2s
Rolling back transaction: done                     154.7kB @ 547.6kB/s  0.3s
Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues
()] 1.0s
Downloading      -----------------------------------------------------   8.6MB /   8.6MB                            0.2s

AssertionError('Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues')
()`

**Comment by ParzivalExtrimis** [comment]
I've been uninstalling and re-installing anaconda because I ran into some issues with CUDA. Now I suspect a certificate from an older version might be conflicting with conda install. Same as above

```console
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Rolling back transaction: done

AssertionError('Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is)
()
AssertionError()
```

**Comment by morien** [comment]
Tried installing something with mamba, not an usual action on this machine:
```
# mamba install cutadapt

Looking for: ['cutadapt']

warning  libmamba Cache file "/home//mambaforge/pkgs/cache/ffeee55f.json" was modified by another program
bioconda/linux-64 (check zst)                      Checked  0.1s
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/2a957770.json" was modified by another program
bioconda/noarch (check zst)                        Checked  0.0s
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/47929eba.json" was modified by another program
pkgs/main/linux-64 (check zst)                      Checked  5.1s
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/3e39a7aa.json" was modified by another program
pkgs/main/noarch (check zst)                       Checked  0.0s
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/2ce54b42.json" was modified by another program
pkgs/r/linux-64 (check zst)                        Checked  0.0s
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/4ea078d6.json" was modified by another program
pkgs/r/noarch (check zst)                          Checked  0.0s
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/497deca9.json" was modified by another program
warning  libmamba Cache file "/home//mambaforge/pkgs/cache/09cdf8bf.json" was modified by another program
pkgs/r/linux-64                                      1.6MB @  10.5MB/s  0.2s
pkgs/main/linux-64                                   6.7MB @  33.3MB/s  0.2s
pkgs/main/noarch                                   729.5kB @   3.5MB/s  0.2s
bioconda/linux-64                                    4.7MB @  16.4MB/s  0.3s
pkgs/r/noarch                                        2.1MB @   6.5MB/s  0.1s
bioconda/noarch                                      4.4MB @  13.1MB/s  0.3s
conda-forge/noarch                                  17.5MB @  20.4MB/s  0.7s
conda-forge/linux-64                                40.2MB @  34.2MB/s  1.0s

Pinned packages:
  - python 3.9.*


Transaction

  Prefix: /home//mambaforge

  Updating specs:

   - cutadapt
   - ca-certificates
   - certifi
   - openssl


  Package                Version  Build            Channel           Size
───────────────────────────────────────────────────────────────────────────
  Install:
───────────────────────────────────────────────────────────────────────────

  + libgcc                14.2.0  h77fa898_1       conda-forge      849kB
  + libstdcxx             14.2.0  hc0a3c3a_1       conda-forge        4MB
  + zlib-ng                2.2.2  h5888daf_0       conda-forge      105kB
  + isa-l                 2.31.0  h4bc722e_2       conda-forge      159kB
  + pbzip2                1.1.13  h1fcc475_2       conda-forge       42kB
  + python-zlib-ng         0.5.1  py310h62b3d1f_0  conda-forge       52kB
  + python-isal            1.7.1  py310ha75aee5_0  conda-forge       62kB
  + pigz                     2.6  h27cfd23_0       pkgs/main         71kB
  + xopen                  2.0.2  pyh707e725_1     conda-forge       22kB
  + dnaio                  1.2.2  py310h7c593f9_0  bioconda         143kB
  + cutadapt                 4.9  py310h7c593f9_2  bioconda         297kB

  Upgrade:
───────────────────────────────────────────────────────────────────────────

  - ca-certificates   2023.12.12  h06a4308_0       pkgs/main       Cached
  + ca-certificates   2024.11.26  h06a4308_0       pkgs/main        134kB
  - certifi             2024.2.2  py39h06a4308_0   pkgs/main       Cached
  + certifi            2024.8.30  py310h06a4308_0  pkgs/main        166kB
  - libgomp               13.2.0  h807b86a_3       conda-forge     Cached
  + libgomp               14.2.0  h77fa898_1       conda-forge      461kB
  - python_abi               3.9  2_cp39           conda-forge     Cached
  + python_abi              3.10  5_cp310          conda-forge        6kB
  - libgcc-ng             13.2.0  h807b86a_3       conda-forge     Cached
  + libgcc-ng             14.2.0  h69a702a_1       conda-forge       54kB
  - zstd                   1.5.5  hfc55251_0       conda-forge     Cached
  + zstd                   1.5.6  ha6fb4c9_0       conda-forge      555kB
  - ruamel.yaml.clib       0.2.7  py39hd1e30aa_2   conda-forge     Cached
  + ruamel.yaml.clib       0.2.8  py310h5eee18b_0  pkgs/main        161kB
  - pandas                 2.1.3  py39hddac248_0   conda-forge     Cached
  + pandas                 2.1.4  py310h1128e8f_0  pkgs/main         13MB
  - bowtie2                2.4.5  py39hd2f7db1_2   bioconda        Cached
  + bowtie2                2.5.4  h7071971_4       bioconda          15MB

  Summary:

  Install: 11 packages
  Upgrade: 9 packages

  Total download: 35MB

───────────────────────────────────────────────────────────────────────────


Confirm changes: [Y/n] y
python_abi                                           6.2kB @   1.2kB/s  5.0s
ca-certificates                                    134.2kB @  26.1kB/s  5.1s
certifi                                            166.3kB @  32.4kB/s  5.1s
libgcc                                             848.7kB @ 165.3kB/s  5.1s
libgomp                                            461.0kB @  86.5kB/s  5.4s
zstd                                               554.8kB @ 102.2kB/s  0.3s
python-zlib-ng                                      52.5kB @   9.7kB/s  0.3s
pigz                                                71.2kB @  13.1kB/s  0.3s
zlib-ng                                            105.3kB @  18.4kB/s  0.3s
isa-l                                              159.3kB @  27.8kB/s  0.3s
pbzip2                                              42.3kB @   7.4kB/s  0.3s
ruamel.yaml.clib                                   161.1kB @  28.1kB/s  0.3s
python-isal                                         61.7kB @  10.4kB/s  0.8s
xopen                                               21.9kB @   3.7kB/s  0.2s
dnaio                                              143.4kB @  24.2kB/s  0.2s
libgcc-ng                                           54.1kB @   8.3kB/s  0.6s
cutadapt                                           297.0kB @  44.7kB/s  0.9s
libstdcxx                                            3.9MB @ 585.8kB/s  0.7s
pandas                                              13.1MB @   1.9MB/s  1.1s
bowtie2                                             15.0MB @   2.1MB/s  1.3s
No package record found for ca-certificates-2023.12.12-h06a4308_0.conda!
No package record found for certifi-2024.2.2-py39h06a4308_0.conda!
No package record found for python_abi-3.9-2_cp39.tar.bz2!
No package record found for zstd-1.5.5-hfc55251_0.conda!
No package record found for ruamel.yaml.clib-0.2.7-py39hd1e30aa_2.conda!

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Rolling back transaction: done
Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues
()


AssertionError('Prefix record insertion error: a record with name ca-certificates already exists in the prefix. This is a bug in conda. Please report it at https://github.com/conda/conda/issues')
()
```
followed by an attempt to clean the install

`# conda clean --all
`
which produces the following error:

```
Traceback (most recent call last):
  File "/home//mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "/home//mambaforge/lib/python3.10/site-packages/conda/cli/main.py", line 51, in main_subshell
    from .conda_argparse import do_call, generate_parser, generate_pre_parser
  File "/home//mambaforge/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 50, in <module>
    from .main_create import configure_parser as configure_parser_create
  File "/home//mambaforge/lib/python3.10/site-packages/conda/cli/main_create.py", line 11, in <module>
    from ..notices import notices
  File "/home//mambaforge/lib/python3.10/site-packages/conda/notices/__init__.py", line 3, in <module>
    from .core import notices  # noqa: F401
  File "/home//mambaforge/lib/python3.10/site-packages/conda/notices/core.py", line 14, in <module>
    from . import cache, fetch, views
  File "/home//mambaforge/lib/python3.10/site-packages/conda/notices/cache.py", line 25, in <module>
    from ..utils import ensure_dir_exists
  File "/home//mambaforge/lib/python3.10/site-packages/conda/utils.py", line 23, in <module>
    from .gateways.disk.read import compute_sum
  File "/home//mambaforge/lib/python3.10/site-packages/conda/gateways/disk/read.py", line 31, in <module>
    from ...exceptions import CondaUpgradeError, CondaVerificationError, PathNotFoundError
  File "/home//mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 15, in <module>
    import requests
  File "/home//mambaforge/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/home//mambaforge/lib/python3.10/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/home//mambaforge/lib/python3.10/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home//mambaforge/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home//mambaforge/lib/python3.10/site-packages/conda/cli/main.py", line 128, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/home//mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 388, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home//mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 20, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home//mambaforge/lib/python3.10/site-packages/conda/exception_handler.py", line 51, in handle_exception
    from .exceptions import (
  File "/home//mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 15, in <module>
    import requests
  File "/home//mambaforge/lib/python3.10/site-packages/requests/__init__.py", line 147, in <module>
    from . import packages, utils
  File "/home//mambaforge/lib/python3.10/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
  File "/home//mambaforge/lib/python3.10/site-packages/requests/certs.py", line 14, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'
```

Fixed by force reinstalling certifi with pip, then `conda clean --all`, then force reinstalling zstd, zstandard packages with pip, then reinstalling miniforge according to usual instructions. Probably a cleaner path to resolution, but that's how I ended up with a working copy of conda/mamba again.

Reporting as instructed. No assistance required.
