### ISSUE TITLE
Conda throws exceptions after updating to 23.1.0 

### ISSUE THREAD

**Issue by delorytheape** [conda/conda#12342]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I recently successfully updated my conda version on a Ubuntu-20.04 machine using the command (as suggested by conda) 
`conda update -n base -c defaults conda'
Everything works fine.

I repeated the command for a second machine (Ubuntu-22.04), which appeared to work (no complaints).  I then attempted to install another package, but conda threw an exception when invoked. I AM able to change environments (eg. 'conda activate py3').

I cannot get any diagnostic information, other than what is displayed when the exception occurs . (Fortunately I obtained 'conda info' prior to the update, which I have posted below. I have also included the update process, and an example of the exception thrown when invoking conda).

### Conda Info

```shell
This was the output of 'conda info' PRIOR TO PERFORMING THE UPDATE when everything was working fine...

     active environment : base
    active env location : /home/chris/miniconda3
            shell level : 1
       user config file : /home/chris/.condarc
 populated config files : 
          conda version : 4.9.1
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=11.4=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/chris/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/chris/miniconda3/pkgs
                          /home/chris/.conda/pkgs
       envs directories : /home/chris/miniconda3/envs
                          /home/chris/.conda/envs
               platform : linux-64
             user-agent : conda/4.9.1 requests/2.24.0 CPython/3.7.3 Linux/5.15.0-60-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
'conda config --show-sources' throws the same exception
```

### Conda list
(When attempting to list packages, conda fails, eg.)

```shell

(py3) chris@lithium:~$ conda list
KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1124, in __call__
    return func(*args, **kwargs)
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 57, in main_subshell
    p = generate_parser()
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 41, in generate_parser
    description='conda is a tool for managing and deploying applications,'
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 117, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 422, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/manager.py", line 9, in <module>
    from . import solvers, virtual_packages
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
    from . import archspec, cuda, linux, osx, windows
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
    import ctypes
  File "/home/chris/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1244, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 236, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 41, in generate_parser
        description='conda is a tool for managing and deploying applications,'
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 117, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 422, in plugin_manager
        from ..plugins.manager import get_plugin_manager
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/manager.py", line 9, in <module>
        from . import solvers, virtual_packages
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
        from . import archspec, cuda, linux, osx, windows
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
        import ctypes
      File "/home/chris/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```
```shell
$ /home/chris/miniconda3/bin/conda list

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Additional Context

Here is the output during the update, and failure on the subsequent command... (performed immediately after the 'conda info' command)

```
(base) chris@lithium:~$ conda update -n base -c defaults conda
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/chris/miniconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _openmp_mutex-5.1          |            1_gnu          21 KB
    brotlipy-0.7.0             |py37h27cfd23_1003         320 KB
    ca-certificates-2023.01.10 |       h06a4308_0         120 KB
    certifi-2022.12.7          |   py37h06a4308_0         150 KB
    cffi-1.15.1                |   py37h5eee18b_3         240 KB
    charset-normalizer-2.0.4   |     pyhd3eb1b0_0          35 KB
    conda-23.1.0               |   py37h06a4308_0         937 KB
    conda-package-handling-2.0.2|   py37h06a4308_0         267 KB
    conda-package-streaming-0.7.0|   py37h06a4308_0          26 KB
    cryptography-38.0.4        |   py37h9ce1e76_0         1.4 MB
    flit-core-3.6.0            |     pyhd3eb1b0_0          42 KB
    idna-3.4                   |   py37h06a4308_0          91 KB
    importlib-metadata-4.11.3  |   py37h06a4308_0          40 KB
    importlib_metadata-4.11.3  |       hd3eb1b0_0          12 KB
    libedit-3.1.20221030       |       h5eee18b_0         181 KB
    libffi-3.4.2               |       h6a678d5_6         136 KB
    libgcc-ng-11.2.0           |       h1234567_1         5.3 MB
    libgomp-11.2.0             |       h1234567_1         474 KB
    libstdcxx-ng-11.2.0        |       h1234567_1         4.7 MB
    ncurses-6.4                |       h6a678d5_0         914 KB
    openssl-1.1.1s             |       h7f8727e_0         3.6 MB
    pluggy-1.0.0               |   py37h06a4308_1          29 KB
    pycosat-0.6.4              |   py37h5eee18b_0          84 KB
    pycparser-2.21             |     pyhd3eb1b0_0          94 KB
    pyopenssl-22.0.0           |     pyhd3eb1b0_0          50 KB
    requests-2.28.1            |   py37h06a4308_0          92 KB
    ruamel.yaml-0.17.21        |   py37h5eee18b_0         177 KB
    ruamel.yaml.clib-0.2.6     |   py37h5eee18b_1         140 KB
    setuptools-65.6.3          |   py37h06a4308_0         1.1 MB
    tk-8.6.12                  |       h1ccaba5_0         3.0 MB
    toolz-0.12.0               |   py37h06a4308_0         104 KB
    tqdm-4.64.1                |   py37h06a4308_0         126 KB
    typing_extensions-4.4.0    |   py37h06a4308_0          45 KB
    urllib3-1.26.14            |   py37h06a4308_0         195 KB
    xz-5.2.10                  |       h5eee18b_1         429 KB
    zipp-3.11.0                |   py37h06a4308_0          19 KB
    zlib-1.2.13                |       h5eee18b_0         103 KB
    zstandard-0.18.0           |   py37h5eee18b_0         433 KB
    ------------------------------------------------------------
                                           Total:        25.2 MB

The following NEW packages will be INSTALLED:

  _openmp_mutex      pkgs/main/linux-64::_openmp_mutex-5.1-1_gnu
  charset-normalizer pkgs/main/noarch::charset-normalizer-2.0.4-pyhd3eb1b0_0
  conda-package-str~ pkgs/main/linux-64::conda-package-streaming-0.7.0-py37h06a4308_0
  flit-core          pkgs/main/noarch::flit-core-3.6.0-pyhd3eb1b0_0
  importlib-metadata pkgs/main/linux-64::importlib-metadata-4.11.3-py37h06a4308_0
  importlib_metadata pkgs/main/noarch::importlib_metadata-4.11.3-hd3eb1b0_0
  libgomp            pkgs/main/linux-64::libgomp-11.2.0-h1234567_1
  pluggy             pkgs/main/linux-64::pluggy-1.0.0-py37h06a4308_1
  ruamel.yaml        pkgs/main/linux-64::ruamel.yaml-0.17.21-py37h5eee18b_0
  ruamel.yaml.clib   pkgs/main/linux-64::ruamel.yaml.clib-0.2.6-py37h5eee18b_1
  toolz              pkgs/main/linux-64::toolz-0.12.0-py37h06a4308_0
  typing_extensions  pkgs/main/linux-64::typing_extensions-4.4.0-py37h06a4308_0
  zipp               pkgs/main/linux-64::zipp-3.11.0-py37h06a4308_0
  zstandard          pkgs/main/linux-64::zstandard-0.18.0-py37h5eee18b_0

The following packages will be REMOVED:

  chardet-3.0.4-py37_1003
  ruamel_yaml-0.15.87-py37h7b6447c_1
  six-1.15.0-py_0
  yaml-0.2.5-h7b6447c_0

The following packages will be UPDATED:

  brotlipy                          0.7.0-py37h7b6447c_1000 --> 0.7.0-py37h27cfd23_1003
  ca-certificates                              2020.10.14-0 --> 2023.01.10-h06a4308_0
  certifi                          2020.6.20-py37h06a4308_2 --> 2022.12.7-py37h06a4308_0
  cffi                                1.14.3-py37he30daa8_0 --> 1.15.1-py37h5eee18b_3
  conda                                4.9.1-py37h06a4308_0 --> 23.1.0-py37h06a4308_0
  conda-package-han~                   1.7.2-py37h03888b9_0 --> 2.0.2-py37h06a4308_0
  cryptography                         3.1.1-py37h1ba5d50_0 --> 38.0.4-py37h9ce1e76_0
  idna                     pkgs/main/noarch::idna-2.10-py_0 --> pkgs/main/linux-64::idna-3.4-py37h06a4308_0
  libedit                           3.1.20191231-h14c3975_1 --> 3.1.20221030-h5eee18b_0
  libffi                                     3.3-he6710b0_2 --> 3.4.2-h6a678d5_6
  libgcc-ng                                9.1.0-hdf63c60_0 --> 11.2.0-h1234567_1
  libstdcxx-ng                             9.1.0-hdf63c60_0 --> 11.2.0-h1234567_1
  ncurses                                    6.2-he6710b0_1 --> 6.4-h6a678d5_0
  openssl                                 1.1.1h-h7b6447c_0 --> 1.1.1s-h7f8727e_0
  pycosat                              0.6.3-py37h7b6447c_0 --> 0.6.4-py37h5eee18b_0
  pycparser                                       2.20-py_2 --> 2.21-pyhd3eb1b0_0
  pyopenssl                                     19.1.0-py_1 --> 22.0.0-pyhd3eb1b0_0
  requests           pkgs/main/noarch::requests-2.24.0-py_0 --> pkgs/main/linux-64::requests-2.28.1-py37h06a4308_0
  setuptools                          50.3.0-py37hb0f4dca_1 --> 65.6.3-py37h06a4308_0
  tk                                      8.6.10-hbc83047_0 --> 8.6.12-h1ccaba5_0
  tqdm                   pkgs/main/noarch::tqdm-4.50.2-py_0 --> pkgs/main/linux-64::tqdm-4.64.1-py37h06a4308_0
  urllib3            pkgs/main/noarch::urllib3-1.25.11-py_0 --> pkgs/main/linux-64::urllib3-1.26.14-py37h06a4308_0
  xz                                       5.2.5-h7b6447c_0 --> 5.2.10-h5eee18b_1
  zlib                                    1.2.11-h7b6447c_3 --> 1.2.13-h5eee18b_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
cffi-1.15.1          | 240 KB    | ########################################## | 100% 
zipp-3.11.0          | 19 KB     | ########################################## | 100% 
pluggy-1.0.0         | 29 KB     | ########################################## | 100% 
conda-package-handli | 267 KB    | ########################################## | 100% 
pyopenssl-22.0.0     | 50 KB     | ########################################## | 100% 
idna-3.4             | 91 KB     | ########################################## | 100% 
ncurses-6.4          | 914 KB    | ########################################## | 100% 
ca-certificates-2023 | 120 KB    | ########################################## | 100% 
flit-core-3.6.0      | 42 KB     | ########################################## | 100% 
typing_extensions-4. | 45 KB     | ########################################## | 100% 
certifi-2022.12.7    | 150 KB    | ########################################## | 100% 
ruamel.yaml.clib-0.2 | 140 KB    | ########################################## | 100% 
requests-2.28.1      | 92 KB     | ########################################## | 100% 
tqdm-4.64.1          | 126 KB    | ########################################## | 100% 
cryptography-38.0.4  | 1.4 MB    | ########################################## | 100% 
xz-5.2.10            | 429 KB    | ########################################## | 100% 
libgcc-ng-11.2.0     | 5.3 MB    | ########################################## | 100% 
importlib-metadata-4 | 40 KB     | ########################################## | 100% 
libffi-3.4.2         | 136 KB    | ########################################## | 100% 
zstandard-0.18.0     | 433 KB    | ########################################## | 100% 
pycparser-2.21       | 94 KB     | ########################################## | 100% 
urllib3-1.26.14      | 195 KB    | ########################################## | 100% 
libgomp-11.2.0       | 474 KB    | ########################################## | 100% 
tk-8.6.12            | 3.0 MB    | ########################################## | 100% 
charset-normalizer-2 | 35 KB     | ########################################## | 100% 
toolz-0.12.0         | 104 KB    | ########################################## | 100% 
zlib-1.2.13          | 103 KB    | ########################################## | 100% 
importlib_metadata-4 | 12 KB     | ########################################## | 100% 
conda-package-stream | 26 KB     | ########################################## | 100% 
libstdcxx-ng-11.2.0  | 4.7 MB    | ########################################## | 100% 
conda-23.1.0         | 937 KB    | ########################################## | 100% 
ruamel.yaml-0.17.21  | 177 KB    | ########################################## | 100% 
setuptools-65.6.3    | 1.1 MB    | ########################################## | 100% 
brotlipy-0.7.0       | 320 KB    | ########################################## | 100% 
_openmp_mutex-5.1    | 21 KB     | ########################################## | 100% 
pycosat-0.6.4        | 84 KB     | ########################################## | 100% 
openssl-1.1.1s       | 3.6 MB    | ########################################## | 100% 
libedit-3.1.20221030 | 181 KB    | ########################################## | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
```shell
(base) chris@lithium:~$ conda install -c conda-forge xraylib
KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1124, in __call__
    return func(*args, **kwargs)
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 57, in main_subshell
    p = generate_parser()
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 41, in generate_parser
    description='conda is a tool for managing and deploying applications,'
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 117, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 422, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/manager.py", line 9, in <module>
    from . import solvers, virtual_packages
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
    from . import archspec, cuda, linux, osx, windows
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
    import ctypes
  File "/home/chris/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1244, in print_unexpected_error_report
    message_builder.append(get_main_info_str(error_report['conda_info']))
  File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 236, in get_main_info_str
    info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 57, in main_subshell
        p = generate_parser()
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 41, in generate_parser
        description='conda is a tool for managing and deploying applications,'
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 117, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/base/context.py", line 422, in plugin_manager
        from ..plugins.manager import get_plugin_manager
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/manager.py", line 9, in <module>
        from . import solvers, virtual_packages
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
        from . import archspec, cuda, linux, osx, windows
      File "/home/chris/miniconda3/lib/python3.7/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
        import ctypes
      File "/home/chris/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory

`$ /home/chris/miniconda3/bin/conda install -c conda-forge xraylib`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

(base) chris@lithium:~$ conda activate py3
(py3) chris@lithium:~$
```

**Comment by delorytheape** [comment]
Apologies for the formatting - I am not very familiar with github - I simply cut-n-pasted the output of conda...

**Comment by jezdez** [comment]
`libffi.so` missing indicates that something is broken in your environment, probably from upgrading from an old version of miniconda. Python 3.7 is also not a supported Python version anymore. It might be best to install an up-to-date version of miniconda to get unblocked.
