### ISSUE TITLE
Update error on Mac OS (Yosemite)

### ISSUE THREAD

**Issue by striatum** [conda/conda#1236]
Hello!
This is what I got from today's update (of glueviz):

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
        args.func(args, p)
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
        install.install(args, parser, 'update')
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
        cmd(state, arg)
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 84, in LINK_CMD
        link(state['prefix'], arg, index=state['index'])
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 80, in link
        install.link(pkgs_dir, prefix, dist, lt, index=index)
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/conda/install.py", line 523, in link
        os.makedirs(dst_dir)
      File "/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/Library/Frameworks/Python.framework/Versions/anaconda/lib/python2.7/site-packages/pandas/io/tests/data/legacy_pickle/0.14.1'

And conda info is:

    Current conda install:
    
                 platform : osx-64
            conda version : 3.10.0
      conda-build version : 1.8.2
           python version : 2.7.9.final.0
         requests version : 2.6.0
         root environment : /Library/Frameworks/Python.framework/Versions/anaconda  (writable)
      default environment : /Library/Frameworks/Python.framework/Versions/anaconda
         envs directories : /Library/Frameworks/Python.framework/Versions/anaconda/envs
            package cache : /Library/Frameworks/Python.framework/Versions/anaconda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/osx-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False
    
So, per (automatic) request, I am sending the info.
Sincerely, PM

**Comment by asmeurer** [comment]
It looks like you pip installed conda directly into your system installation of Python. This is not recommended (we recommend installing Anaconda or Miniconda, or if you must pip install, pip install into a virtualenv). If you do do this, you will have to use sudo to run your conda commands, since writing to /Library requires root permissions.

**Comment by asmeurer** [comment]
Closing because there is no issue here. You installed conda in a place that requires root permissions. Without using sudo, you will get permissions errors.
