### ISSUE TITLE
Conda files and package files becoming spontaneously corrupted

### ISSUE THREAD

**Issue by KatelynGreene** [conda/conda#12376]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Every few days or weeks, I need to reinstall miniconda on my machine because either: 
1. files relating to conda itself becomes corrupted (affecting files within \miniconda\shell\condabin\)
2. files within one of my packages becomes corrupted (affecting files within \lib\sitepackages\). 

------

Typically when attempting to open a conda shell or run a script involving my packages, I will get one of the following flavors of issues:

1) Immediate error upon attempting to run an Anaconda Powershell prompt

Example 1:
```
Remove-Variable : A positional parameter cannot be found that accepts argument 'ˆ3§'.
At C:\Users\rahu\AppData\Local\miniconda3\shell\condabin\conda-hook.ps1:9 char:1
+ Remove-Variable G^V↨3íô ˆ3§
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Remove-Variable], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.RemoveVariableCommand

¾²] : The term '¾²]' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\rahu\AppData\Local\miniconda3\shell\condabin\conda-hook.ps1:10 char:1
+ ¾²]
+ ~~~
    + CategoryInfo          : ObjectNotFound: (¾²]:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

If I open conda-hook.ps1 file to take a look at what's going on, there are indeed a bunch of gibberish characters at the end of the file:

```
$Env:CONDA_EXE = "C:/Users/rahu/AppData/Local/miniconda3\Scripts\conda.exe"
$Env:_CE_M = ""
$Env:_CE_CONDA = ""
$Env:_CONDA_ROOT = "C:/Users/rahu/AppData/Local/miniconda3"
$Env:_CONDA_EXE = "C:/Users/rahu/AppData/Local/miniconda3\Scripts\conda.exe"
$CondaModuleArgs = @{ChangePs1 = $True}
Import-Module "$Env:_CONDA_ROOT\shell\condabin\Conda.psm1" -ArgumentList $CondaModuleArgs

Remove-Variable G^V3íô ˆ3§
¾²]
```

2) UnicodeDecodeError when trying to run a python script involving a package managed by conda

Example error outputted to the terminal upon running a script: 

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb0 in position 8146: invalid start byte in PKG-INFO file at path: c:\users\rahu\appdata\local\miniconda3\lib\site-packages\SimpleITK-2.2.1-py3.10-win-amd64.egg-info\PKG-INFO. `

If I open PKG-INFO, there are again a bunch of gibberish characters at the end of the file:

```
[code at beginning of this file excluded for brevity] ...
The following information will allow us to address your issue in a timely manner:
1. Error message (copy & pasted) and focused description of the problem.
2. Operating system, and version (e.g. OSX 10.11.6).
3. Programming language, and version (e.g. Python 2.7.14, R 3.2.3).
4. Version of SimpleITK (e.g. 1.1.0), just invoke the SimpleITK Version() function.
5. How did you install SimpleITK, binary distribution (e.g. conda install -c simpleitk simpleitk), or built it from source (e.g. devtools::install_github("SimpleITK/SimpleITKRInstaller")).
6. A minimal working example which causes the error.
7. If your code requires input, possibly point to a minimal sized&°ÊæEÁá¸²¦6ã8Œ
```

2) 'ValueError: bad marshal data' when trying to run a python script involving a package managed by conda

Example: 
```
Error processing line 1 of C:\Users\rahu\Miniconda3\lib\site-packages\matplotlib-3.6.3-py3.9-nspkg.pth:

  Traceback (most recent call last):
    File "C:\Users\rahu\Miniconda3\lib\site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "C:\Users\rahu\Miniconda3\lib\importlib\util.py", line 2, in <module>
      from . import abc
    File "C:\Users\rahu\Miniconda3\lib\importlib\abc.py", line 17, in <module>
      from typing import Protocol, runtime_checkable
    File "C:\Users\rahu\Miniconda3\lib\typing.py", line 22, in <module>
      import collections.abc
    File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
    File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 846, in exec_module
    File "<frozen importlib._bootstrap_external>", line 978, in get_code
    File "<frozen importlib._bootstrap_external>", line 647, in _compile_bytecode
  ValueError: bad marshal data (unknown type code)
```

-----
What I've tried:

- When these errors reference a specific package, I have tried to reinstall that particular package, but the same errors just appear with a different package within a few hours, and I end up needing to reinstall conda. 
- Reinstalling conda temporarily resolves these errors I'm experiencing, but within a few hours or days, the gibberish characters will spontaneously appear at the end of various files associated with packages or conda.

 Reinstalling conda and all the packages repeatedly on a daily or weekly basis is time consuming and frustrating, and this has been going on for over a year now. I'd really like to figure out what the source of the issue is and prevent my various conda/package files from becoming corrupted.  

Any ideas or insights into this issue would be greatly appreciated, thank you!

### Conda Info

```shell
active environment : base
    active env location : C:\Users\rahu\AppData\Local\miniconda3
            shell level : 1
       user config file : C:\Users\rahu\.condarc
 populated config files : C:\Users\rahu\.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.4=0
                          __win=0=0
       base environment : C:\Users\rahu\AppData\Local\miniconda3  (writable)
      conda av data dir : C:\Users\rahu\AppData\Local\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\rahu\AppData\Local\miniconda3\pkgs
                          C:\Users\rahu\.conda\pkgs
                          C:\Users\rahu\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\rahu\AppData\Local\miniconda3\envs
                          C:\Users\rahu\.conda\envs
                          C:\Users\rahu\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.10.9 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\rahu\.condarc <==
ssl_verify: True
```

### Conda list

```shell
# packages in environment at C:\Users\rahu\AppData\Local\miniconda3:
#
# Name                    Version                   Build  Channel
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
attrs                     22.2.0                   pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.01.10           haa95532_0    defaults
certifi                   2022.12.7       py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
colorama                  0.4.6           py310haa95532_0    defaults
comm                      0.1.2           py310haa95532_0    defaults
commonmark                0.9.1                    pypi_0    pypi
conda                     23.1.0          py310haa95532_0    defaults
conda-content-trust       0.1.3           py310haa95532_0    defaults
conda-package-handling    2.0.2           py310haa95532_0    defaults
conda-package-streaming   0.7.0           py310haa95532_0    defaults
console_shortcut_miniconda 0.1.1                haa95532_0    defaults
contourpy                 1.0.7                    pypi_0    pypi
cryptography              38.0.4          py310h21b164f_0    defaults
cycler                    0.11.0                   pypi_0    pypi
debugpy                   1.5.1           py310hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
entrypoints               0.4             py310haa95532_0    defaults
et_xmlfile                1.1.0           py310haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
fonttools                 4.38.0                   pypi_0    pypi
h5py                      3.7.0                    pypi_0    pypi
idna                      3.4             py310haa95532_0    defaults
ipykernel                 6.19.2          py310h9909e9c_0    defaults
ipython                   8.7.0           py310haa95532_0    defaults
jedi                      0.18.1          py310haa95532_1    defaults
jpeg                      9e                   h2bbff1b_0    defaults
jupyter_client            7.4.8           py310haa95532_0    defaults
jupyter_core              5.1.1           py310haa95532_0    defaults
kiwisolver                1.4.4                    pypi_0    pypi
lasso-python              2.0.0                    pypi_0    pypi
lerc                      3.0                  hd77b12b_0    defaults
libdeflate                1.8                  h2bbff1b_5    defaults
libffi                    3.4.2                hd77b12b_6    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libtiff                   4.4.0                h8a3f274_2    defaults
lz4-c                     1.9.4                h2bbff1b_0    defaults
matplotlib                3.6.3                    pypi_0    pypi
matplotlib-inline         0.1.6           py310haa95532_0    defaults
menuinst                  1.4.19          py310h59b6b97_0    defaults
nest-asyncio              1.5.6           py310haa95532_0    defaults
numpy                     1.24.1                   pypi_0    pypi
openpyxl                  3.0.9              pyhd3eb1b0_0    anaconda
openssl                   1.1.1s               h2bbff1b_0    defaults
packaging                 23.0                     pypi_0    pypi
pandas                    1.5.3                    pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.4.0                    pypi_0    pypi
pip                       22.3.1          py310haa95532_0    defaults
platformdirs              2.5.2           py310haa95532_0    defaults
plotly                    5.12.0                   pypi_0    pypi
pluggy                    1.0.0           py310haa95532_1    defaults
powershell_shortcut_miniconda 0.0.1                haa95532_0    defaults
prompt-toolkit            3.0.36          py310haa95532_0    defaults
psutil                    5.9.4                    pypi_0    pypi
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pycosat                   0.6.4           py310h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.14.0                   pypi_0    pypi
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.9               h966fe2a_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pytz                      2022.7.1                 pypi_0    pypi
pywin32                   305             py310h2bbff1b_0    defaults
pyzmq                     23.2.0          py310hd77b12b_0    defaults
requests                  2.28.1          py310haa95532_0    defaults
rich                      12.6.0                   pypi_0    pypi
ruamel.yaml               0.17.21         py310h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1    defaults
scipy                     1.10.0                   pypi_0    pypi
setuptools                65.6.3          py310haa95532_0    defaults
simpleitk                 2.2.1           py310h82bb817_0    simpleitk
six                       1.16.0             pyhd3eb1b0_1    defaults
sklearn                   0.0.post1                pypi_0    pypi
sqlite                    3.40.1               h2bbff1b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tbb                       2021.6.0             h59b6b97_1    defaults
tenacity                  8.1.0                    pypi_0    pypi
tk                        8.6.12               h2bbff1b_0    defaults
toolz                     0.12.0          py310haa95532_0    defaults
tornado                   6.2             py310h2bbff1b_0    defaults
tqdm                      4.64.1          py310haa95532_0    defaults
traitlets                 5.7.1           py310haa95532_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
urllib3                   1.26.14         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
xz                        5.2.10               h8cc25b3_1    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstandard                 0.18.0          py310h2bbff1b_0    defaults
zstd                      1.5.2                h19a0ad4_0    defaults
```

### Additional Context

I have found someone else with a similar issue as mine on stackoverflow, but there was not an accepted solution that worked for my machine:
https://stackoverflow.com/questions/65725677/python-keeps-getting-corrupted-and-requiring-reinstallation

**Comment by travishathaway** [comment]
Hi @KatelynGreene,

Thank you for filing this issue. This sounds very peculiar. Are you currently only experiencing problems with conda or are other programs on your computer also experiencing file corruptions?

Is there anything else about your particular machine that wouldn't mind sharing that you think might help us resolve this issue?

I want to also say that recreating these types of issues can be exceedingly difficult, and we unfortunately cannot promise a general purpose fix for this anytime soon.

**Comment by KatelynGreene** [comment]
Hi @travishathaway,

Thanks for the follow-up! I'm only experiencing this with conda (miniconda and anaconda installations), no other programs appear to be showing this strange behavior.

As for the machine, it's a 5+ year old custom build (used for computational research) and it's on a corporate network. I used conda for years previously on this same machine without issue and haven't identified a specific event that could have caused the issue. It was reimaged with a clean install of windows in late 2019, but beyond that there haven't been any major changes to the OS or hardware. I also ran checks on the drives and all are showing good health. 

One detail perhaps worth noting is that occasionally when the conda's files become corrupted, it sometimes becomes impossible to successfully run the uninstaller executable (it throws several errors about not being able to run particular scripts).  In these instances, I do wonder if the inability to completely uninstall the software may be contributing to the corruption issues.

Totally understand on the difficulty of this issue, I figured it was worth asking in case others in the community or the developers had seen this odd end of file behavior before.

**Comment by travishathaway** [comment]
Thanks for sharing this information. At this time, I believe it will be best to leave this issue open as-is to see if others stumble upon it and would also like to contribute any other experiences they may be having.

**Comment by abhirajD** [comment]
Facing similar issues. This could be a low freq - high impact bug.
Any resolution yet?

**Comment by snoor-projects** [comment]
I am facing the same issue with my Anaconda in a tensorflow environment. It was working fine before. Now, while opening Jupyter it displays "500-Internal Server Error" and a pop-up that "pkgs\cffi-1.15.1-py39h2bbff1b_3
appears to be corrupted."

**Comment by thomasrdiaz** [comment]
I'm facing this problem with a miniconda installation on my Mac x64 machine running Ventura 13.6.3.

**Comment by kchang808** [comment]
I'm facing this issue as well on a Surface Book 3 on Win 11.  Similarly, I have to remove the environment, re-create it and conda install the packages for the app I'm working on.  I'm on conda 23.11.0.

**Comment by jaimergp** [comment]
@abhirajD, @snoor-projects, @thomasrdiaz, @kchang808 - I am surprised this is a cross-operating-system bug. Is there a chance this is still happening for all of you? In that case, could you post the same info as the OP? For clarity, it would really help us if we could know the output of the following commands:

- `conda info`
- `conda config --show-sources`
- `conda list --show-channel-urls`


Thanks!

**Comment by walter-weinmann** [comment]
D:\SoftDevelopment\Projects\IO-Aero\io-map-apps>conda info

     active environment : None
            shell level : 0
       user config file : C:\Users\walte\.condarc
 populated config files : C:\Users\walte\.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.12.3.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64_v3
                          __conda=24.5.0=0
                          __cuda=12.5=0
                          __win=0=0
       base environment : C:\ProgramData\miniconda3  (writable)
      conda av data dir : C:\ProgramData\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-forge/label/cf202003/win-64
                          https://conda.anaconda.org/conda-forge/label/cf202003/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\miniconda3\pkgs
                          C:\Users\walte\.conda\pkgs
                          C:\Users\walte\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\miniconda3\envs
                          C:\Users\walte\.conda\envs
                          C:\Users\walte\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.12.3 Windows/11 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
          administrator : True
             netrc file : None
           offline mode : False

**Comment by walter-weinmann** [comment]
D:\SoftDevelopment\Projects\IO-Aero\io-map-apps>conda config --show-sources
==> C:\Users\walte\.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - conda-forge/label/cf202003
  - defaults
always_yes: True

**Comment by walter-weinmann** [comment]
D:\SoftDevelopment\Projects\IO-Aero\io-map-apps>conda list --show-channel-urls
# packages in environment at C:\ProgramData\miniconda3:
#
# Name                    Version                   Build  Channel
anaconda-anon-usage       0.4.4           py312hfc23b7f_100    defaults
archspec                  0.2.3              pyhd3eb1b0_0    defaults
aws-c-auth                0.7.17               hb40cdec_2    conda-forge
aws-c-cal                 0.6.11               ha21e00f_0    conda-forge
aws-c-common              0.9.15               hcfcfb64_0    conda-forge
aws-c-compression         0.2.18               ha21e00f_3    conda-forge
aws-c-event-stream        0.4.2                hf668b60_8    conda-forge
aws-c-http                0.8.1               hd704247_10    conda-forge
aws-c-io                  0.14.7               h14865c8_6    conda-forge
aws-c-mqtt                0.10.3               h748201e_4    conda-forge
aws-c-s3                  0.5.7                h5da7064_1    conda-forge
aws-c-sdkutils            0.1.15               ha21e00f_3    conda-forge
aws-checksums             0.1.18               ha21e00f_3    conda-forge
aws-crt-cpp               0.26.6               h5bc0ceb_4    conda-forge
aws-sdk-cpp               1.11.267             h5d77392_6    conda-forge
azure-core-cpp            1.11.1               h249a519_1    conda-forge
azure-identity-cpp        1.6.0                h91493d7_1    conda-forge
azure-storage-blobs-cpp   12.10.0              h91493d7_1    conda-forge
azure-storage-common-cpp  12.5.0               h91493d7_4    conda-forge
blosc                     1.21.5               hbd69f2e_1    conda-forge
boltons                   23.0.0          py312haa95532_0    defaults
brotli-python             1.0.9           py312hd77b12b_7    defaults
bzip2                     1.0.8                h2bbff1b_5    defaults
c-ares                    1.28.1               hcfcfb64_0    conda-forge
ca-certificates           2024.6.2             h56e8100_0    conda-forge
cairo                     1.18.0               h1fef639_0    conda-forge
certifi                   2024.6.2           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py312h2bbff1b_0    defaults
cfitsio                   4.4.0                h9b0cee5_0    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
colorama                  0.4.6           py312haa95532_0    defaults
conda                     24.5.0          py312h2e8e312_0    conda-forge
conda-content-trust       0.2.0           py312haa95532_0    defaults
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0    defaults
conda-package-handling    2.2.0           py312haa95532_0    defaults
conda-package-streaming   0.9.0           py312haa95532_0    defaults
console_shortcut_miniconda 0.1.1                haa95532_1    defaults
cryptography              42.0.5          py312h89fc84f_0    defaults
distro                    1.8.0           py312haa95532_0    defaults
expat                     2.6.2                h63175ca_0    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
freexl                    2.0.0                h8276f4a_0    conda-forge
frozendict                2.4.4           py312h4389bb4_0    conda-forge
gdal                      3.8.5           py312hea5013e_2    conda-forge
geos                      3.12.1               h1537add_0    conda-forge
geotiff                   1.7.1               hed9d743_16    conda-forge
hdf4                      4.2.15               h5557f11_7    conda-forge
hdf5                      1.14.3          nompi_h73e8ff5_100    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.4             py312haa95532_0    defaults
intel-openmp              2024.1.0           h57928b3_965    conda-forge
jsonpatch                 1.33            py312haa95532_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
kealib                    1.5.3                hd248416_0    conda-forge
krb5                      1.21.2               heb0366b_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20240116.1      cxx17_h63175ca_2    conda-forge
libaec                    1.1.3                h63175ca_0    conda-forge
libarchive                3.7.2                h313118b_1    conda-forge
libblas                   3.9.0              22_win64_mkl    conda-forge
libboost-headers          1.84.0               h57928b3_2    conda-forge
libcblas                  3.9.0              22_win64_mkl    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   8.7.1                hd5e4a3a_0    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libexpat                  2.6.2                h63175ca_0    conda-forge
libffi                    3.4.4                hd77b12b_0    defaults
libgdal                   3.8.5                hfb9f81c_2    conda-forge
libglib                   2.80.0               h39d0aa6_5    conda-forge
libgoogle-cloud           2.22.0               h9cad5c0_1    conda-forge
libgoogle-cloud-storage   2.22.0               hb581fae_1    conda-forge
libgrpc                   1.62.2               h5273850_0    conda-forge
libhwloc                  2.10.0          default_h2fffb23_1000    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
libkml                    1.3.0             haf3e7a6_1018    conda-forge
liblapack                 3.9.0              22_win64_mkl    conda-forge
libmamba                  1.5.8                h3f09ed1_0    conda-forge
libmambapy                1.5.8           py312h66cf91f_0    conda-forge
libnetcdf                 4.9.2           nompi_h07c049d_113    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libpq                     16.2                 hdb24f17_1    conda-forge
libprotobuf               4.25.3               h503648d_0    conda-forge
libre2-11                 2023.09.01           hf8d8778_2    conda-forge
librttopo                 1.1.0               h94c4f80_15    conda-forge
libsolv                   0.7.28               h12be248_2    conda-forge
libspatialite             5.1.0                hf13de1f_5    conda-forge
libsqlite                 3.45.3               hcfcfb64_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxml2                   2.12.6               hc3477c8_2    conda-forge
libzip                    1.10.1               h1d365fa_3    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
lz4-c                     1.9.4                h2bbff1b_0    defaults
lzo                       2.10              he774522_1000    conda-forge
menuinst                  2.0.2           py312hd77b12b_0    defaults
minizip                   4.0.5                h5bed578_0    conda-forge
mkl                       2024.1.0           h66d3029_692    conda-forge
numpy                     1.26.4          py312h8753938_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.3.1                h2466b09_0    conda-forge
packaging                 23.2            py312haa95532_0    defaults
pcre2                     10.43                h17e33f8_0    conda-forge
pip                       23.3.1          py312haa95532_0    defaults
pixman                    0.43.4               h63175ca_0    conda-forge
platformdirs              3.10.0          py312haa95532_0    defaults
pluggy                    1.0.0           py312haa95532_1    defaults
poppler                   24.04.0              h747fd5a_0    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                16.2                 h94c9ec1_1    conda-forge
powershell_shortcut_miniconda 0.0.1                haa95532_1    defaults
proj                      9.4.0                he13c7e8_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py312h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pysocks                   1.7.1           py312haa95532_0    defaults
python                    3.12.3          h2628c8c_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
re2                       2023.09.01           hd3b24a8_2    conda-forge
reproc                    14.2.4               hd77b12b_1    defaults
reproc-cpp                14.2.4               hd77b12b_1    defaults
requests                  2.31.0          py312haa95532_1    defaults
ruamel.yaml               0.17.21         py312h2bbff1b_0    defaults
setuptools                68.2.2          py312haa95532_0    defaults
snappy                    1.2.0                hfb803bf_1    conda-forge
spdlog                    1.12.0               h64d2f7d_2    conda-forge
sqlite                    3.41.2               h2bbff1b_0    defaults
tbb                       2021.12.0            h91493d7_0    conda-forge
tiledb                    2.22.0               h8c3a016_0    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tqdm                      4.65.0          py312hfc267ef_0    defaults
truststore                0.8.0           py312haa95532_0    defaults
tzdata                    2024a                h04d1e81_0    defaults
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
uriparser                 0.9.7                h1537add_1    conda-forge
urllib3                   2.1.0           py312haa95532_1    defaults
vc                        14.3                hcf57466_18    conda-forge
vc14_runtime              14.38.33130         h82b7239_18    conda-forge
vs2015_runtime            14.38.33130         hcb4865c_18    conda-forge
wheel                     0.41.2          py312haa95532_0    defaults
win_inet_pton             1.1.0           py312haa95532_0    defaults
xerces-c                  3.2.5                h63175ca_0    conda-forge
xz                        5.4.6                h8cc25b3_0    defaults
yaml-cpp                  0.8.0                hd77b12b_0    defaults
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstandard                 0.19.0          py312h2bbff1b_0    defaults
zstd                      1.5.5                hd43e919_0    defaults

D:\SoftDevelopment\Projects\IO-Aero\io-map-apps>

**Comment by walter-weinmann** [comment]
Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: /
SafetyError: The package for proj located at C:\ProgramData\miniconda3\pkgs\proj-9.4.1-hd9569ee_0
appears to be corrupted. The path 'Library/share/proj/proj.db'
has an incorrect size.
  reported size: 9154560 bytes
  actual size: 0 bytes

ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::libkml-1.3.0-haf3e7a6_1018, conda-forge/win-64::minizip-4.0.6-hb638d1e_0
  path: 'library/include/minizip/ioapi.h'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::libkml-1.3.0-haf3e7a6_1018, conda-forge/win-64::minizip-4.0.6-hb638d1e_0
  path: 'library/include/minizip/unzip.h'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::libkml-1.3.0-haf3e7a6_1018, conda-forge/win-64::minizip-4.0.6-hb638d1e_0
  path: 'library/include/minizip/zip.h'

**Comment by walter-weinmann** [comment]
D:\SoftDevelopment\Projects\IO-Aero\io-map-apps>conda activate iomapapps
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
pj_obj_create: SQLite error on SELECT key, value FROM metadata WHERE key IN ('DATABASE.LAYOUT.VERSION.MAJOR', 'DATABASE.LAYOUT.VERSION.MINOR'): no such table: metadata
