### ISSUE TITLE
pandas 0.16 can't be imported from the root environment on windows 

### ISSUE THREAD

**Issue by ikalev** [conda/conda#1239]
Pandas 0.15.\* works fine in the root environment on windows:

``` shell
C:\Users\kalev>conda update python
python                    2.7.6                         0

C:\Users\kalev>python -c "import pandas"
```

After upgrading to 0.16, pandas is no longer importable:

``` shell
C:\Users\kalev>conda update pandas
The following packages will be UPDATED:
    pandas: 0.15.2-np19py27_1 --> 0.16.0-np19py27_1

C:\Users\kalev>python -c "import pandas"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Anaconda\lib\site-packages\pandas\__init__.py", line 47, in <module>
    import pandas.core.config_init
  File "C:\Anaconda\lib\site-packages\pandas\core\config_init.py", line 17, in <module>
    from pandas.core.format import detect_console_encoding
  File "C:\Anaconda\lib\site-packages\pandas\core\format.py", line 24, in <module>
    from pandas.tseries.period import PeriodIndex, DatetimeIndex
  File "C:\Anaconda\lib\site-packages\pandas\tseries\period.py", line 8, in <module>
    import pandas.tseries.frequencies as frequencies
  File "C:\Anaconda\lib\site-packages\pandas\tseries\frequencies.py", line 9, in <module>
    from pandas.tseries.offsets import DateOffset
  File "C:\Anaconda\lib\site-packages\pandas\tseries\offsets.py", line 2152, in <module>
    class Nano(Tick):
  File "C:\Anaconda\lib\site-packages\pandas\tseries\offsets.py", line 2153, in Nano
    _inc = Timedelta(nanoseconds=1)
  File "pandas\tslib.pyx", line 1722, in pandas.tslib.Timedelta.__new__ (pandas\tslib.c:29707)
ValueError: cannot construct a TimeDelta from the passed arguments, allowed keywords are [days, seconds, microseconds, m
illiseconds, minutes, hours, weeks]
```

It works fine in a virtual environment, where `python` can be updated to 2.7.9. But 2.7.6 and 2.7.8 appear to be incompatible with `pandas 0.16`. Is there a way to update the python package in the root environment?

**Comment by ccordoba12** [comment]
@jreback, any thoughts on this one? This is also affecting Spyder: spyder-ide/spyder#2300

**Comment by jreback** [comment]
I have seen that people don't force install (e.g. they are already running something in python and it tries to update but fails)

try

```
conda remove pandas
conda install pandas -f
```

**Comment by jreback** [comment]
Ignoring the warnings.....works fine on a vanilla install of 2.7.6 (and 2.7.8), latest conda

```
C:\Temp>conda create -n pandas_python_276 python=2.7.6 pandas
Fetching package metadata: C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
....C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
......
Solving package specifications: .
Package plan for installation in environment C:\Anaconda\envs\pandas_python_276:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.6               |                2        16.5 MB

The following NEW packages will be INSTALLED:

    numpy:           1.9.2-py27_0
    pandas:          0.16.0-np19py27_1
    pip:             6.0.8-py27_0
    python:          2.7.6-2
    python-dateutil: 2.4.2-py27_0
    pytz:            2015.2-py27_0
    setuptools:      15.0-py27_0
    six:             1.9.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
python-2.7.6-2 100% |###############################| Time: 0:02:02 140.93 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
#
# To activate this environment, use:
# > activate pandas_python_276
#

C:\Temp>activate pandas_python_276
Activating environment "pandas_python_276"...

[pandas_python_276] C:\Temp>python -c "import pandas; print pandas.show_versions()"

INSTALLED VERSIONS
------------------
commit: None
python: 2.7.6.final.0
python-bits: 64
OS: Windows
OS-release: 7
machine: AMD64
processor: Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
byteorder: little
LC_ALL: None
LANG: None

pandas: 0.16.0
nose: None
Cython: None
numpy: 1.9.2
scipy: None
statsmodels: None
IPython: None
sphinx: None
patsy: None
dateutil: 2.4.2
pytz: 2015.2
bottleneck: None
tables: None
numexpr: None
matplotlib: None
openpyxl: None
xlrd: None
xlwt: None
xlsxwriter: None
lxml: None
bs4: None
html5lib: None
httplib2: None
apiclient: None
sqlalchemy: None
pymysql: None
psycopg2: None
None

[pandas_python_276] C:\Temp>
```

**Comment by ccordoba12** [comment]
Thanks @jreback, the warnings are unavoidable right now.

@ikalev, please confirm that @jreback proposed solution works for you before closing.

**Comment by asmeurer** [comment]
You can actually get rid of the warnings with `conda install ndg-httpsclient`.

**Comment by ikalev** [comment]
I've just upgraded to ``pandas 0.16`` build ``np19py27_1`` using a normal ``conda update`` and it does work. I didn't even have to force-install it as suggested.

Also confirming that ``ndg-httpsclient`` silences all warnings.

**Comment by tswicegood** [comment]
Reopened as I have a fix in #1273.

**Comment by toasteez** [comment]
I had the issue:   File "pandas\tslib.pyx", line 1722, in pandas.tslib.Timedelta.__new__ (pandas\tslib.c:29707)
ValueError: cannot construct a TimeDelta from the passed arguments, allowed keywords are [days, seconds, microseconds, m
illiseconds, minutes, hours, weeks]

When I updated Pandas

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-dateutil-2.4.2      |           py27_0         219 KB
    pandas-0.16.0              |       np19py27_1         4.5 MB
    ------------------------------------------------------------
                                           Total:         4.8 MB

The following packages will be UPDATED:

    pandas:          0.15.2-np19py27_1 --> 0.16.0-np19py27_1
    python-dateutil: 2.4.1-py27_0      --> 2.4.2-py27_0

I removed this     python-dateutil: 2.4.1-py27_0      --> 2.4.2-py27_0 and it now works.  

When I checked my Pkgs folder both versions of python-dateutil were there.  Maybe there was a conflict?

**Comment by asmeurer** [comment]
The pkgs folder is just a cache of packages. Both versions are there because conda has had both versions installed.

**Comment by toasteez** [comment]
Aaron, thanks for pointing that out.  In any case removing Python, Python_dateutil and Pandas from my environment and then using conda to reinstall all of them fixed the issue.

Can I enquire as to where the best place to ask questions of Pandas is?  I have a question around the stack() function.
