### ISSUE TITLE
conda docs build broken with TypeError

### ISSUE THREAD

**Issue by jezdez** [conda/conda#12417]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

In the automated Sphinx build system we suddenly see the following error:

```
Running Sphinx v4.2.0
CalledProcessError(128, "fatal: No tags can describe '944f612cbe0e26a9a3ba9ccc9e6cea017f78571e'.\nTry --always, or create some tags.\n")

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/docs/source/conf.py", line 31, in <module>
    import conda
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/__init__.py", line 10, in <module>
    from .deprecations import deprecated
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/deprecations.py", line 266, in <module>
    deprecated = DeprecationHandler(__version__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/deprecations.py", line 29, in __init__
    self._version = parse(version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/packaging/version.py", line 195, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/application.py", line 216, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/config.py", line 172, in read
    namespace = eval_config_file(filename, tags)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/config.py", line 341, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/docs/source/conf.py", line 31, in <module>
    import conda
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/__init__.py", line 10, in <module>
    from .deprecations import deprecated
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/deprecations.py", line 266, in <module>
    deprecated = DeprecationHandler(__version__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/deprecations.py", line 29, in __init__
    self._version = parse(version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/packaging/version.py", line 195, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/docs/source/conf.py", line 31, in <module>
    import conda
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/__init__.py", line 10, in <module>
    from .deprecations import deprecated
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/deprecations.py", line 266, in <module>
    deprecated = DeprecationHandler(__version__)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/checkouts/12411/conda/deprecations.py", line 29, in __init__
    self._version = parse(version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/docs/checkouts/readthedocs.org/user_builds/continuumio-conda/envs/12411/lib/python3.7/site-packages/packaging/version.py", line 195, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

It seems as if `conda.__version__` is `None` for some reason, possibly because it can't successfully run `conda.auxlib.packaging.get_version`, which returns `None` as a fallback.

### Additional Context

- https://readthedocs.com/projects/continuumio-conda/builds/1323274/

**Comment by jezdez** [comment]
Was able to reproduce this for pull request builds with the following steps that mimic RTD's behavior when cloning pull request builds:

```
git clone --no-single-branch --depth 50 https://github.com/conda/conda conda-clone
cd conda-clone
git fetch origin --force --tags --prune --prune-tags --depth 50 pull/12416/head:external-12416
source dev/start
```

Seems like it's not just the Sphinx build but the lack of enough information when we run `git describe --tags --long` in the `conda.auxlib.packaging` module to find out the version.

**Comment by jezdez** [comment]
Okay, adding an `git fetch --unshallow` to the mix solved it.
