### ISSUE TITLE
"conda update anaconda" fails on OS X Yosemite

### ISSUE THREAD

**Issue by jrking123** [conda/conda#1242]
Updated conda OK, but "conda update anaconda" fails with:
```
Traceback (most recent call last):
  File "/Users/John/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/Users/John/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: ipython-notebook-3.0.0-py27_1.tar.bz2 MatchSpec(u'mistune 0.5')
```

Output of "conda info":
```
Current conda install:

             platform : osx-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /Users/John/anaconda  (writable)
  default environment : /Users/John/anaconda
     envs directories : /Users/John/anaconda/envs
        package cache : /Users/John/anaconda/pkgs
         channel URLs : https://conda.binstar.org/anaconda/osx-64/
                        https://conda.binstar.org/anaconda/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/John/.condarc
    is foreign system : False
```

Thanks very much.

**Comment by asmeurer** [comment]
Try removing the `anaconda` channel from `/Users/John/.condarc`.

**Comment by jrking123** [comment]
Perfect now - thanks so much!
John
