### ISSUE TITLE
Problem updating conda

### ISSUE THREAD

**Issue by yoavfreund** [conda/conda#1245]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/anaconda/lib/python2.7/site-packages/conda/plan.py", line 501, in execute_actions
    with History(actions[inst.PREFIX]):
  File "/anaconda/lib/python2.7/site-packages/conda/history.py", line 64, in **enter**
    self.update()
  File "/anaconda/lib/python2.7/site-packages/conda/history.py", line 89, in update
    self.write_changes(last, curr)
  File "/anaconda/lib/python2.7/site-packages/conda/history.py", line 210, in write_changes
    with open(self.path, 'a') as fo:
IOError: [Errno 13] Permission denied: '//anaconda/conda-meta/history'
yoav-freunds-PowerBook-G4-retina:Memory Hierarchy yoavfreund$ conda info
Current conda install:

```
         platform : osx-64
    conda version : 3.10.0
```

  conda-build version : 1.3.5
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by andyferris** [comment]
I just had exactly the same issue on OSX...

**Comment by asmeurer** [comment]
I think these sorts of errors should be fixed in the latest version of conda.

**Comment by soapy1** [comment]
@yoavfreund is this still an issue for you?
