### ISSUE TITLE
Unable to create a clone installation in conda3 

### ISSUE THREAD

**Issue by 183amir** [conda/conda#1248]
Traceback:

    Traceback (most recent call last):
      File "./conda", line 5, in <module>
        sys.exit(main())
      File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
        args_func(args, p)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 206, in args_func
        args.func(args, p)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main_create.py", line 50, in execute
        install.install(args, parser, 'create')
      File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 164, in install
        clone(args.clone, prefix, json=args.json, quiet=args.quiet)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 85, in clone
        quiet=quiet)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/misc.py", line 173, in clone_env
        execute_actions(actions, index=get_index(), verbose=not quiet)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 587, in execute_actions
        execute_plan(plan, index, verbose)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 569, in execute_plan
        link(prefix, arg, index=index)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/plan.py", line 525, in link
        install.link(pkgs_dir, prefix, dist, lt, index=index)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/install.py", line 532, in link
        update_prefix(join(prefix, f), prefix, placeholder, mode, instdir=instdir)
      File "/opt/anaconda/lib/python3.4/site-packages/conda/install.py", line 254, in update_prefix
        with open(path, 'rb') as fi:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/amir/envs/anaconda/lib/libfreetype.la'

  Current conda install:

               platform : linux-64
          conda version : 3.7.0
    conda-build version : 1.8.2
         python version : 3.4.1.final.0
       requests version : 2.4.1
       root environment : /opt/anaconda  (read only)
    default environment : /opt/anaconda
       envs directories : /home/amir/envs
                          /opt/anaconda/envs
          package cache : /home/amir/envs/.pkgs
                          /opt/anaconda/pkgs
           channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                          http://repo.continuum.io/pkgs/pro/linux-64/
            config file : None
      is foreign system : False

**Comment by ilanschnell** [comment]
What exactly is the command you typed?

**Comment by 183amir** [comment]
`conda create -n anaconda --clone=/opt/anaconda`

**Comment by 183amir** [comment]
Ok. I think the problem is because `.la` files are removed during packaging this program in Arch Linux.

**Comment by ilanschnell** [comment]
Ah, I wasn't aware that Anaconda is repackaged for Arch Linux.  Removing files from Anaconda during installation would be a problem.  When you install Anaconda directly (using the 64-bit Linux installer from http://continuum.io/downloads), you should not run into this problem.
