### ISSUE TITLE
Conda fails to install ipykernel on Python 3.7

### ISSUE THREAD

**Issue by sadasant** [conda/conda#12494]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following was working about a weak or so ago, and now it isn't working anymore:

1. Create a new Python 3.7 environment `conda create --name python37 python=3.7`.
2. Activate the new environment with `conda activate python37`.
3. Install `ipykernel` with `conda install -c conda-forge --name python379 ipykernel -y`.

At this point, the output is:

```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/anaconda3/envs/python379

  added / updated specs:
    - ipykernel


The following NEW packages will be INSTALLED:

  appnope            conda-forge/noarch::appnope-0.1.3-pyhd8ed1ab_0 
  backcall           conda-forge/noarch::backcall-0.2.0-pyh9f0ad1d_0 
  backports          conda-forge/noarch::backports-1.0-pyhd8ed1ab_3 
  backports.functoo~ conda-forge/noarch::backports.functools_lru_cache-1.6.4-pyhd8ed1ab_0 
  decorator          conda-forge/noarch::decorator-5.1.1-pyhd8ed1ab_0 
  entrypoints        conda-forge/noarch::entrypoints-0.4-pyhd8ed1ab_0 
  ipykernel          conda-forge/osx-64::ipykernel-5.5.5-py37h85f7c60_0 
  ipython            conda-forge/osx-64::ipython-7.33.0-py37hf985489_0 
  ipython_genutils   conda-forge/noarch::ipython_genutils-0.2.0-py_1 
  jedi               conda-forge/noarch::jedi-0.18.2-pyhd8ed1ab_0 
  jupyter_client     conda-forge/osx-64::jupyter_client-5.3.4-py37_0 
  jupyter_core       conda-forge/noarch::jupyter_core-4.5.0-py_0 
  libcxx             conda-forge/osx-64::libcxx-15.0.7-h71dddab_0 
  libsodium          conda-forge/osx-64::libsodium-1.0.18-hbcb3906_1 
  matplotlib-inline  conda-forge/noarch::matplotlib-inline-0.1.6-pyhd8ed1ab_0 
  parso              conda-forge/noarch::parso-0.8.3-pyhd8ed1ab_0 
  pexpect            conda-forge/noarch::pexpect-4.8.0-pyh1a96a4e_2 
  pickleshare        conda-forge/noarch::pickleshare-0.7.5-py_1003 
  prompt-toolkit     conda-forge/noarch::prompt-toolkit-3.0.38-pyha770c72_0 
  ptyprocess         conda-forge/noarch::ptyprocess-0.7.0-pyhd3deb0d_0 
  pygments           conda-forge/noarch::pygments-2.14.0-pyhd8ed1ab_0 
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.2-pyhd8ed1ab_0 
  python_abi         conda-forge/osx-64::python_abi-3.7-2_cp37m 
  pyzmq              conda-forge/osx-64::pyzmq-19.0.2-py37hf1e22d8_2 
  six                conda-forge/noarch::six-1.16.0-pyh6c4a22f_0 
  tornado            conda-forge/osx-64::tornado-6.2-py37h994c40b_0 
  traitlets          conda-forge/noarch::traitlets-5.9.0-pyhd8ed1ab_0 
  wcwidth            conda-forge/noarch::wcwidth-0.2.6-pyhd8ed1ab_0 
  zeromq             conda-forge/osx-64::zeromq-4.3.4-he49afe7_1 

The following packages will be SUPERSEDED by a higher-priority channel:

  ca-certificates    pkgs/main::ca-certificates-2023.01.10~ --> conda-forge::ca-certificates-2022.12.7-h033912b_0 
  certifi            pkgs/main/osx-64::certifi-2022.12.7-p~ --> conda-forge/noarch::certifi-2022.12.7-pyhd8ed1ab_0 
  openssl              pkgs/main::openssl-1.1.1t-hca72f7f_0 --> conda-forge::openssl-1.1.1t-hfd90126_0 



Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

Then, I try to `import ipykernel`, and it fails:

```
python
Python 3.7.16 (default, Jan 17 2023, 09:28:58) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipykernel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/python379/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/envs/python379/lib/python3.7/site-packages/ipykernel/connect.py", line 16, in <module>
    import jupyter_client
  File "/opt/anaconda3/envs/python379/lib/python3.7/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/opt/anaconda3/envs/python379/lib/python3.7/site-packages/jupyter_client/connect.py", line 35, in <module>
    from jupyter_core.paths import jupyter_data_dir, jupyter_runtime_dir, secure_write
ImportError: cannot import name 'secure_write' from 'jupyter_core.paths' (/opt/anaconda3/envs/python379/lib/python3.7/site-packages/jupyter_core/paths.py)
```

### Conda Info

```shell
conda info

     active environment : python379
    active env location : /opt/anaconda3/envs/python379
            shell level : 2
       user config file : /Users/danielrodriguez/.condarc
 populated config files : /Users/danielrodriguez/.condarc
          conda version : 23.1.0
    conda-build version : 3.21.9
         python version : 3.9.7.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda3/pkgs
                          /Users/danielrodriguez/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /Users/danielrodriguez/.conda/envs
               platform : osx-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.7 Darwin/22.3.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
conda config --show-sources
==> /Users/danielrodriguez/.condarc <==
auto_activate_base: False
```

### Conda list

```shell
conda list --show-channel-urls
# packages in environment at /opt/anaconda3/envs/python379:
#
# Name                    Version                   Build  Channel
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
ca-certificates           2022.12.7            h033912b_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
ipykernel                 5.5.5            py37h85f7c60_0    conda-forge
ipython                   7.33.0           py37hf985489_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jupyter_client            5.3.4                    py37_0    conda-forge
jupyter_core              4.5.0                      py_0    conda-forge
libcxx                    15.0.7               h71dddab_0    conda-forge
libffi                    3.4.2                hecd8cb5_6    defaults
libsodium                 1.0.18               hbcb3906_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcec6c5f_0    defaults
openssl                   1.1.1t               hfd90126_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pip                       22.3.1           py37hecd8cb5_0    defaults
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pygments                  2.14.0             pyhd8ed1ab_0    conda-forge
python                    3.7.16               h218abb5_0    defaults
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pyzmq                     19.0.2           py37hf1e22d8_2    conda-forge
readline                  8.2                  hca72f7f_0    defaults
setuptools                65.6.3           py37hecd8cb5_0    defaults
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.41.1               h6c40b1e_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
tornado                   6.2              py37h994c40b_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4           py37hecd8cb5_0    defaults
xz                        5.2.10               h6c40b1e_1    defaults
zeromq                    4.3.4                he49afe7_1    conda-forge
zlib                      1.2.13               h4dc903c_0    defaults
```

**Comment by travishathaway** [comment]
Hi @sadasant,

Thanks for filing this issue. Unfortunately, this is not the correct place  for it. I would ask you to file this with the Jupyter developers instead or whoever is responsible for maintaining the ipykernel library.

This project is reserved for issues with the conda package manager itself and not issues that may arise from misconfigured environments or bugs in the libraries conda installs.

**Comment by sadasant** [comment]
Got it! Thank you!
