### ISSUE TITLE
Issues updating ipython notebook

### ISSUE THREAD

**Issue by mycarta** [conda/conda#1250]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 598, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '//anaconda/conda-meta/ipython-3.0.0-py27_0.json'

**Comment by soapy1** [comment]
@mycarta is this still an issue for you?

**Comment by mycarta** [comment]
No, I am going to close.
