### ISSUE TITLE
GCC installation fails

### ISSUE THREAD

**Issue by fourpartswater** [conda/conda#1256]
Hi, 

I am running anaconda from my home directory on a  Scientific Linux 6.2 system.

When I try to install gcc in anaconda I get:

$ conda install gcc
Fetching package metadata: ......
Solving package specifications: .
Package plan for installation in environment /data/home/mpx036/anaconda:

The following NEW packages will be INSTALLED:

    gcc: 4.8.2-2

Proceed ([y]/n)? 

Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                          |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/data/home/m6/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 141, in execute_instructions
    cmd(state, arg)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/install.py", line 534, in link
    _link(src, dst, lt)
  File "/data/home/m6/anaconda/lib/python2.7/site-packages/conda/install.py", line 133, in _link
    shutil.copy2(src, dst)
  File "/data/home/m6/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/data/home/m6/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/data/home/m6/anaconda/pkgs/gcc-4.8.2-2/libexec/gcc/x86_64-unknown-linux-gnu/4.8.2/plugin/gengtype'

'conda info':

Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /data/home/m6/anaconda  (writable)
  default environment : /data/home/m6/anaconda
     envs directories : /data/home/m6/anaconda/envs
        package cache : /data/home/m6/anaconda/pkgs
         channel URLs : https://conda.binstar.org/bcbio/linux-64/
                        https://conda.binstar.org/bcbio/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /data/home/m6/.condarc
    is foreign system : False

**Comment by asmeurer** [comment]
Try `conda install gcc -f`. 

Also make sure you have enough free disk space (the gcc package is quite large).

**Comment by stuarteberg** [comment]
@fourpartswater, conda's `gcc` package is won't work out-of-the-box on Scientific Linux 6, but see conda/conda-recipes#279 for a version that should work for you.
