### ISSUE TITLE
TypeError if conda build, conda convert, ... is run from a virtual env on Windows

### ISSUE THREAD

**Issue by n-elie** [conda/conda#12563]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`conda build -h` fails if run from a virtual environment but succeeds if run from base environment (only on **Windows**):

```$ conda create -n build-test
$ conda activate build-test
$ conda build -h
Traceback (most recent call last):
  File "C:\Users\elie\AppData\Local\mambaforge\Scripts\conda-build-script.py", line 6, in <module>
    from conda_build.cli.main_build import main
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\conda_build\cli\main_build.py", line 16, in <module>
    import conda_build.api as api
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\conda_build\api.py", line 19, in <module>
    from conda_build.config import (Config, get_or_merge_config, get_channel_urls,
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\conda_build\config.py", line 19, in <module>
    from .variants import get_default_variant
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\conda_build\variants.py", line 19, in <module>
    from conda_build.utils import ensure_list, get_logger, islist, on_win, trim_empty_keys
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\conda_build\utils.py", line 11, in <module>
    import libarchive
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\elie\AppData\Local\mambaforge\lib\site-packages\libarchive\ffi.py", line 26, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\elie\AppData\Local\mambaforge\lib\ctypes\__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\elie\AppData\Local\mambaforge\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable```

It also fails with `conda debug -h` and nearly all other subcommands (`convert`, `develop`, `index`, `inspect`, `metapackage`, `render`, `skeleton`) but not with `conda env -h`.
Downgrading `conda` to `conda==4.14.0` fixes the error. The problem occurs with all the versions of conda starting from `conda==22.9.0`

### Conda Info

```shell
active environment : base
    active env location : C:\Users\elie\AppData\Local\mambaforge
            shell level : 1
       user config file : C:\Users\elie\.condarc
 populated config files : C:\Users\elie\AppData\Local\mambaforge\.condarc
                          C:\Users\elie\.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=8.0=0
                          __win=0=0
       base environment : C:\Users\elie\AppData\Local\mambaforge  (writable)
      conda av data dir : C:\Users\elie\AppData\Local\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\elie\AppData\Local\mambaforge\pkgs
                          C:\Users\elie\.conda\pkgs
                          C:\Users\elie\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\elie\AppData\Local\mambaforge\envs
                          C:\Users\elie\.conda\envs
                          C:\Users\elie\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.3.1 requests/2.28.2 CPython/3.10.10 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\elie\AppData\Local\mambaforge\.condarc <==
channels:
  - conda-forge

==> C:\Users\elie\.condarc <==
pinned_packages: []
ssl_verify: True
channel_priority: flexible
channels:
  - conda-forge
  - anaconda-fusion
  - defaults
```

### Conda list

```shell
# packages in environment at C:\Users\elie\AppData\Local\mambaforge:
#
# Name                    Version                   Build  Channel
beautifulsoup4            4.12.0             pyha770c72_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_3    conda-forge
chardet                   5.1.0           py310h5588dad_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.3.1          py310h5588dad_0    conda-forge
conda-build               3.24.0          py310haa95532_0    defaults
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
conda-souschef            2.2.3              pyhd8ed1ab_0    conda-forge
cryptography              40.0.1          py310h6e82f81_0    conda-forge
filelock                  3.10.7             pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                h181d51b_0    conda-forge
glob2                     0.7                        py_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
intel-openmp              2023.0.0         h57928b3_25922    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
libarchive                3.6.2                h27c7867_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcurl                   7.88.1               h68f0423_1    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.9.0                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblief                   0.12.3               h63175ca_0    conda-forge
libmamba                  1.4.1                h8a7d157_0    conda-forge
libmambapy                1.4.1           py310h3fe4c2e_0    conda-forge
libsolv                   0.7.23               h12be248_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libxml2                   2.10.3               hc3477c8_6    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              he774522_1000    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
mamba                     1.4.1           py310hd9d798f_0    conda-forge
markupsafe                2.1.2           py310h8d17308_0    conda-forge
menuinst                  1.4.19          py310h5588dad_1    conda-forge
miniforge_console_shortcut 2.0                  h57928b3_1    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
numpy                     1.24.2          py310hd02465a_0    conda-forge
openssl                   3.1.0                hcfcfb64_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pip                       23.0.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
progressbar2              4.2.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.4           py310h8d17308_0    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
py-lief                   0.12.3          py310h00ffb61_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h8d17308_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.10         h4de0772_0_cpython    conda-forge
python-libarchive-c       4.0             py310h5588dad_2    conda-forge
python-utils              3.5.2              pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h8d17308_5    conda-forge
rapidfuzz                 2.14.0          py310h00ffb61_0    conda-forge
reproc                    14.2.4               hcfcfb64_0    conda-forge
reproc-cpp                14.2.4               h63175ca_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
ripgrep                   13.0.0               h7f3b576_2    conda-forge
ruamel.yaml               0.17.21         py310h8d17308_3    conda-forge
ruamel.yaml.clib          0.2.7           py310h8d17308_1    conda-forge
ruamel.yaml.jinja2        0.2.4                      py_1    conda-forge
ruamel_yaml               0.15.80         py310h8d17308_1008    conda-forge
semver                    2.13.0             pyh9f0ad1d_0    conda-forge
setuptools                67.6.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               hcfcfb64_0    conda-forge
stdlib-list               0.8.0              pyhd8ed1ab_0    conda-forge
tbb                       2021.8.0             h91493d7_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb6edc58_10    conda-forge
vs2015_runtime            14.34.31931         h4c5c07a_10    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.7.0                h63175ca_2    conda-forge
zstandard                 0.19.0          py310h0009e47_1    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```

### Additional Context

Already reported at https://github.com/conda/conda-build/issues/4835, but not sure if it is a `conda` or `conda-build` bug.

**Comment by n-elie** [comment]
The problem seems to be in `libarchive/ffi.py`:
```python
libarchive_path = os.environ.get('LIBARCHIVE') or find_library('archive')
```
`ctypes.utils.find_library` can't find the libarchive dll.

Setting `LIBARCHIVE` env variable solve the error:
```
$ set LIBARCHIVE=C:\Users\elie\AppData\Local\mambaforge\Library\bin\archive.dll
$ conda build -h
usage: conda-build [-h] [-V] [-n] [--output] [--python PYTHON] [--perl PERL] [--numpy NUMPY] [--R R_BASE] [--lua LUA] [--bootstrap BOOTSTRAP]
                   [--append-file APPEND_SECTIONS_FILE] [--clobber-file CLOBBER_SECTIONS_FILE] [-m VARIANT_CONFIG_FILES]
                   [-e EXCLUSIVE_CONFIG_FILES] [--old-build-string] [--use-channeldata] [--variants VARIANTS] [--check] [--no-anaconda-upload]
                   [--no-include-recipe] [-s] [-t] [--no-test] [-b] [--post] [-p] [--skip-existing] [--keep-old-work] [--dirty] [-q] [--debug]
                   [--token TOKEN] [--user USER] [--label LABELS] [--no-force-upload]
                   [--zstd-compression-level {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22}] [--password PASSWORD] [--sign SIGN]
                   [--sign-with SIGN_WITH] [--identity IDENTITY] [--config-file CONFIG_FILE] [--repository REPOSITORY] [--no-activate]
                   [--no-build-id] [--build-id-pat BUILD_ID_PAT] [--croot CROOT] [--verify] [--no-verify] [--strict-verify]
                   [--output-folder OUTPUT_FOLDER] [--no-prefix-length-fallback] [--prefix-length-fallback] [--prefix-length _PREFIX_LENGTH]
                   [--no-locking] [--no-remove-work-dir] [--error-overlinking] [--no-error-overlinking] [--error-overdepending]
                   [--no-error-overdepending] [--long-test-prefix] [--no-long-test-prefix] [--keep-going] [--cache-dir CACHE_DIR]
                   [--no-copy-test-source-files] [--merge-build-host] [--stats-file STATS_FILE] [--extra-deps EXTRA_DEPS [EXTRA_DEPS ...]]
                   [--extra-meta [KEY=VALUE ...]] [--suppress-variables] [-c CHANNEL] [--use-local] [--override-channels]
                   [--repodata-fn REPODATA_FNS] [--experimental {jlap,lock}]
                   RECIPE_PATH [RECIPE_PATH ...]
...
```

**Comment by travishathaway** [comment]
Hi @n-elie,

Thanks for filing this. conda-build is the correct place for this issue, so I am going to go ahead and close this one.
