### ISSUE TITLE
cond install, update or clean  results in  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte

### ISSUE THREAD

**Issue by peterthorpe5** [conda/conda#12577]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hello!

Firstly, I love conda - thank you. I tried installing come packages in their own env, that kept failing. Various trail and error(s). So, I -rm -rf conda. To remove the old install .... 

Reinstall. 

Tried again - Same problem. See the error below. Any help would be much appriciated.

regards, Pete 

> conda create -n python_test python=3.8
**Collecting package metadata (current_repodata.json): failed**

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 139, in query_all
        create_cache_dir()
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 708, in create_cache_dir
        cache_dir = join(PackageCacheData.first_writable().pkgs_dir, "cache")
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 182, in first_writable
        package_cache = cls(pkgs_dir)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 82, in __call__
        package_cache_instance = super().__call__(pkgs_dir)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 95, in __init__
        self._urls_data = UrlsData(pkgs_dir)
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 489, in __init__
        self._urls_data = [line.strip().decode("utf-8") for line in fh]
      File "/mnt/shared/scratch/pthorpe/apps/conda/lib/python3.10/site-packages/conda/core/package_cache_data.py", line 489, in <listcomp>
        self._urls_data = [line.strip().decode("utf-8") for line in fh]
    **UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 0: invalid start byte**

`$ /mnt/shared/scratch/pthorpe/apps/conda/bin/conda create -n python_test python=3.8`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mnt/shared/scratch/pthorpe/apps/conda/bin/conda
             CONDA_PREFIX=/mnt/shared/scratch/pthorpe/apps/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mnt/shared/scratch/pthorpe/apps/conda/bin/python
               CONDA_ROOT=/mnt/shared/scratch/pthorpe/apps/conda
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
            GENEMARK_PATH=/home/pthorpe/apps/gmes_linux_64/
     JAVA_LD_LIBRARY_PATH=/mnt/shared/scratch/pthorpe/apps/conda/lib/server
          LD_LIBRARY_PATH=/opt/slurm/latest/lib64
               LD_PRELOAD=<not set>
                  MANPATH=/opt/slurm/latest/share/man/:/opt/slurm/latest/share/man/::
               MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefil
                          es:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/home/pthorpe/.local/bin:/home/pthorpe/bin:/opt/openmpi/latest/bin:/op
                          t/slurm/latest/bin:/mnt/shared/apps/guppy/4.2.2:/mnt/shared/apps/asper
                          a/3.9.2/bin:/mnt/cluster/scripts:/mnt/shared/scratch/pthorpe/apps/cond
                          a/bin:/home/pthorpe/apps/codonPHYML_dev/src:/home/pthorpe/apps/phyml-
                          20140723/src:/home/pthorpe/apps/transrate-1.0.3-linux-
                          x86_64:/mnt/shared/scratch/pthorpe/apps/bowtie_2.2.5/bin:/home/pthorpe
                          /apps/bwa-mem2:/home/pthorpe/apps/vsearch/bin/FastQC:/mnt/shared/scrat
                          ch/pthorpe/apps/SPAdes-3.14.1-Linux/bin:/home/pthorpe/apps/ncbi-blast-
                          2.10.1+/bin:/home/pthorpe/apps/bin:/mnt/shared/scratch/pthorpe/apps/co
                          nda/bin:/home/pthorpe/.local/bin:/home/pthorpe/bin:/opt/openmpi/latest
                          /bin:/opt/slurm/latest/bin:/usr/share/Modules/bin:/mnt/shared/apps/gup
                          py/4.2.2:/mnt/shared/apps/aspera/3.9.2/bin:/mnt/cluster/scripts:/mnt/s
                          hared/scratch/pthorpe/apps/conda/condabin:/mnt/shared/scratch/pthorpe/
                          apps/conda/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home
                          /pthorpe/apps/homer/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /mnt/shared/scratch/pthorpe/apps/conda
            shell level : 1
       user config file : /home/pthorpe/.condarc
 populated config files : /home/pthorpe/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /mnt/shared/scratch/pthorpe/apps/conda  (writable)
      conda av data dir : /mnt/shared/scratch/pthorpe/apps/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/etetoolkit/linux-64
                          https://conda.anaconda.org/etetoolkit/noarch
          package cache : /mnt/shared/scratch/pthorpe/apps/conda/pkgs
                          /home/pthorpe/.conda/pkgs
       envs directories : /mnt/shared/scratch/pthorpe/apps/conda/envs
                          /home/pthorpe/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.10 Linux/4.18.0-425.13.1.el8_7.x86_64 rocky/8.7 glibc/2.28
                UID:GID : 896600106:896600106
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

### Conda Info

```shell
> conda info

     active environment : base
    active env location : /mnt/shared/scratch/pthorpe/apps/conda
            shell level : 1
       user config file : /home/pthorpe/.condarc
 populated config files : /home/pthorpe/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /mnt/shared/scratch/pthorpe/apps/conda  (writable)
      conda av data dir : /mnt/shared/scratch/pthorpe/apps/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/etetoolkit/linux-64
                          https://conda.anaconda.org/etetoolkit/noarch
          package cache : /mnt/shared/scratch/pthorpe/apps/conda/pkgs
                          /home/pthorpe/.conda/pkgs
       envs directories : /mnt/shared/scratch/pthorpe/apps/conda/envs
                          /home/pthorpe/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.10 Linux/4.18.0-425.13.1.el8_7.x86_64 rocky/8.7 glibc/2.28
                UID:GID : 896600106:896600106
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
> conda config --show-sources
==> /home/pthorpe/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
  - etetoolkit
show_channel_urls: True
report_errors: True
```

### Conda list

```shell
> conda list --show-channel-urls
# packages in environment at /mnt/shared/scratch/pthorpe/apps/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
biopython                 1.81                     pypi_0    pypi
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.3.1          py310hff52083_0    conda-forge
conda-content-trust       0.1.3           py310h06a4308_0    defaults
conda-package-handling    2.0.2           py310h06a4308_0    defaults
conda-package-streaming   0.7.0           py310h06a4308_0    defaults
cryptography              38.0.4          py310h9ce1e76_0    defaults
fmt                       9.1.0                h924138e_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4             py310h06a4308_0    defaults
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h3d51595_0    conda-forge
libcurl                   7.88.1               hdc1c0ab_1    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  1.4.2                hcea66bb_0    conda-forge
libmambapy                1.4.2           py310h1428755_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsolv                   0.7.23               h3eb15da_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.10.3               hfdac1af_6    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-openmp               16.0.1               h417c0b6_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mamba                     1.4.2           py310h51d5547_0    conda-forge
ncurses                   6.4                  h6a678d5_0    defaults
numpy                     1.24.2                   pypi_0    pypi
openssl                   3.1.0                h0b41bf4_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pip                       22.3.1          py310h06a4308_0    defaults
pluggy                    1.0.0           py310h06a4308_1    defaults
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.10         he550d4f_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.28.1          py310h06a4308_0    defaults
ruamel.yaml               0.17.21         py310h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    defaults
setuptools                65.6.3          py310h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.40.1               h5082296_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py310h06a4308_0    defaults
tqdm                      4.64.1          py310h06a4308_0    defaults
tzdata                    2022g                h04d1e81_0    defaults
urllib3                   1.26.14         py310h06a4308_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
xz                        5.2.10               h5eee18b_1    defaults
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.18.0          py310h5eee18b_0    defaults
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by peterthorpe5** [comment]
Another reinstall fixed this issue.
