### ISSUE TITLE
Miniconda error， can't use conda install ,conda create .....

### ISSUE THREAD

**Issue by mq-maqi** [conda/conda#12589]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I used conda, it alerted me that my conda version was too low, so I updated it.But when I tried to do it with conda again, it got an error

### Conda Info

```shell
/root/miniconda3/lib/python3.8/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.8/site-packages/requests/compat.py", line 11, in <module>
        import chardet
    ModuleNotFoundError: No module named 'chardet'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/__init__.py", line 21, in <module>
        from requests import ConnectionError, HTTPError, Session
      File "/root/miniconda3/lib/python3.8/site-packages/requests/__init__.py", line 45, in <module>
        from .exceptions import RequestsDependencyWarning
      File "/root/miniconda3/lib/python3.8/site-packages/requests/exceptions.py", line 9, in <module>
        from .compat import JSONDecodeError as CompatJSONDecodeError
      File "/root/miniconda3/lib/python3.8/site-packages/requests/compat.py", line 13, in <module>
        import charset_normalizer as chardet
      File "/root/miniconda3/lib/python3.8/site-packages/charset_normalizer/__init__.py", line 23, in <module>
        from charset_normalizer.api import from_fp, from_path, from_bytes, normalize
      File "/root/miniconda3/lib/python3.8/site-packages/charset_normalizer/api.py", line 10, in <module>
        from charset_normalizer.md import mess_ratio
      File "charset_normalizer/md.py", line 5, in <module>
        from charset_normalizer.utils import is_punctuation, is_symbol, unicode_range, is_accentuated, is_latin, \
    ImportError: cannot import name 'COMMON_SAFE_ASCII_CHARACTERS' from 'charset_normalizer.constant' (/root/miniconda3/lib/python3.8/site-packages/charset_normalizer/constant.py)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/root/miniconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/root/miniconda3/lib/python3.8/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/root/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 12, in <module>
        from .package_cache_data import PackageCacheData
      File "/root/miniconda3/lib/python3.8/site-packages/conda/core/package_cache_data.py", line 14, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/root/miniconda3/lib/python3.8/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "/root/miniconda3/lib/python3.8/site-packages/conda/gateways/connection/__init__.py", line 39, in <module>
        from pip._vendor.requests import ConnectionError, HTTPError, Session
    ModuleNotFoundError: No module named 'pip'

`$ /root/miniconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

### Conda Config

```shell
==> /root/.condarc <==
allow_conda_downgrades: True
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults
```

**Comment by mq-maqi** [comment]
Conda info, conda install, and conda create are not available, **and the error is the same**

**Comment by travishathaway** [comment]
Hi @mq-maqi,

I can't say for sure what's going on, but I would suggest reinstalling conda with the latest Miniconda installer: https://docs.conda.io/en/latest/miniconda.html

Why are you running conda as the root user? Is this being run in a docker container?
