### ISSUE TITLE
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

### ISSUE THREAD

**Issue by diego898** [conda/conda#1261]
As described in https://github.com/conda/conda/issues/1239, I was having a problem with pandas that Im including here because Im not sure if they are related. I removed pandas and reinstalled, and that solved my import problem. In that same thread, it suggested installing `ndg-httpsclient` to remove these annoying warnings. I went ahead and did that, Just for posteritys sake I tried to update conda and I got the error seen at the bottom, which it suggested I report

```
C:\Users\diego>conda remove pandas
....
ertain SSL connections to fail. For more information, see https://urllib3.readth
edocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
....

Package plan for package removal in environment C:\Anaconda:

The following packages will be REMOVED:

    pandas: 0.16.0-np19py27_1

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\Users\diego>conda install pandas -f
Fetching package metadata: C:\Anaconda\lib\site-packages\requests\packages\urlli
b3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not ava
ilable. This prevents urllib3 from configuring SSL appropriately and may cause c
ertain SSL connections to fail. For more information, see https://urllib3.readth
edocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following NEW packages will be INSTALLED:

    pandas: 0.16.0-np19py27_1

Proceed ([y]/n)? y

[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\Users\diego>python -c "import pandas"

C:\Users\diego>conda install ndg-httpsclient
Fetching package metadata: C:\Anaconda\lib\site-packages\requests\packages\urlli
b3\util\ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not ava
ilable. This prevents urllib3 from configuring SSL appropriately and may cause c
ertain SSL connections to fail. For more information, see https://urllib3.readth
edocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
..C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insec
urePlatformWarning: A true SSLContext object is not available. This prevents url
lib3 from configuring SSL appropriately and may cause certain SSL connections to
 fail. For more information, see https://urllib3.readthedocs.org/en/latest/secur
ity.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
..
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-6.1.1                  |           py27_0         1.4 MB
    cryptography-0.8.1         |           py27_1         1.0 MB
    ndg-httpsclient-0.3.3      |           py27_0          71 KB
    ------------------------------------------------------------
                                           Total:         2.5 MB

The following NEW packages will be INSTALLED:

    ndg-httpsclient: 0.3.3-py27_0

The following packages will be UPDATED:

    cryptography:    0.8-py27_1   --> 0.8.1-py27_1
    pip:             6.0.8-py27_0 --> 6.1.1-py27_0

Proceed ([y]/n)? y

Fetching packages ...
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
pip-6.1.1-py27 100% |###############################| Time: 0:00:04 313.27 kB/s
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
cryptography-0 100% |###############################| Time: 0:00:21  50.57 kB/s
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:79: Insecur
ePlatformWarning: A true SSLContext object is not available. This prevents urlli
b3 from configuring SSL appropriately and may cause certain SSL connections to f
ail. For more information, see https://urllib3.readthedocs.org/en/latest/securit
y.html#insecureplatformwarning.
  InsecurePlatformWarning
ndg-httpsclien 100% |###############################| Time: 0:00:00  73.18 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\Users\diego>conda update conda
Fetching package metadata: ..An unexpected error has occurred, please consider s
ending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 253, in instal
l
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 531, in get_ind
ex_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 86, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 400, in
 result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in
 __get_result
    reraise(self._exception, self._traceback)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107,
in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in
 run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch_repoda
ta
    verify=config.ssl_verify)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 476, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 464, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.p
y", line 762, in _validate_conn
    conn.connect()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py",
line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 251, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 152, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in
 __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in
 valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in
 __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in
 valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComp
onentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in get
PositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) n
ot found

C:\Users\diego>conda info
Current conda install:

             platform : win-64
        conda version : 3.10.1
  conda-build version : 1.11.0
       python version : 2.7.8.final.0
     requests version : 2.6.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tswicegood** [comment]
Hey @diego898 -- trying to understand how this fits in with #1239.  The errors I see here don't seem related to pandas imports.

**Comment by diego898** [comment]
@tswicegood you're right I dont think its directly related. Just referenced it for completeness as I did the fix described in that thread right before this problem arose.

**Comment by tswicegood** [comment]
@diego898 gotcha.  I'm not sure what's up then.  Hopefully @ilanschnell or @asmeurer will have some ideas.

**Comment by asmeurer** [comment]
This pyasn1 thing is some weird issue with requests. I've seen it before, but I have no idea what causes it or how to fix it.

**Comment by tswicegood** [comment]
Ping @kennethreitz.  Any ideas?

**Comment by diego898** [comment]
anything?

**Comment by gibbycu** [comment]
Does this old thread have to do with it?
http://stackoverflow.com/questions/5519958/how-do-i-parse-subjectaltname-extension-data-using-pyasn1

Incidentally, I removed the ```ndg-httpsclient``` package  and then ```conda update conda-build``` worked fine.  Then I installed ```ndg-httpsclient``` again after the update and it broke ```conda```.  Now ```conda remove``` does not work and I can't remove ```ndg-httpsclient```

**Comment by asmeurer** [comment]
Try `conda update requests`

**Comment by wanglongqi** [comment]
Same error:
`pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found`

**Comment by cjrh** [comment]
Removing package `ndg-httpsclient` gets me back into a working state, albeit with `InsecurePlatformWarning` messages again. You may have to uninstall `ndg-httpsclient` with pip if the conda uninstall is throwing the pyasn errors.

**Comment by pcp16** [comment]
Same error here, `requests` seems to be fine. I do not have `ndg-httpsclient`.

**Comment by asmeurer** [comment]
@pcp16 what version of requests do you have? `conda info` will show you the version.

**Comment by pcp16** [comment]
@asmeurer, 2.7.0

Current conda install:

             platform : win-64
        conda version : 3.11.0-dirty
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     *requests version : 2.7.0*
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
Can you paste the exact error message you are getting?

**Comment by pcp16** [comment]
Sure:
---

C:\Users\Pau>conda update conda
Fetching package metadata: .An unexpected error has occurred, please consider se
nding the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 255, in instal
l
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 546, in get_ind
ex_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 120, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 250, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 404, in
 result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 356, in
 __get_result
    raise self._exception
**pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) n
ot found**

**Comment by natezb** [comment]
I had the same issue: Installed `ndg-httpsclient` to get rid of the `InsecurePlatformWarning` as described in #1204, this caused the `PyAsn1Error` every time I tried to use `conda`.

I removed `ndg-httpsclient` via `pip`; this had no effect. I tried a `pip install ndg-httpsclient`, with the same result. I then tried `pip install --upgrade ndg-httpsclient`, which gave the following output:

```
$ pip install --upgrade ndg-httpsclient
Requirement already up-to-date: ndg-httpsclient in c:\anaconda\lib\site-packages

Collecting PyOpenSSL (from ndg-httpsclient)
  Downloading pyOpenSSL-0.15.1-py2.py3-none-any.whl (102kB)
←[K    100% |################################| 106kB 2.6MB/s ta 0:00:01
Requirement already up-to-date: six>=1.5.2 in c:\anaconda\lib\site-packages (fro
m PyOpenSSL->ndg-httpsclient)
Requirement already up-to-date: cryptography>=0.7 in c:\anaconda\lib\site-packag
es\cryptography-0.9.3-py2.7-win-amd64.egg (from PyOpenSSL->ndg-httpsclient)
Requirement already up-to-date: idna in c:\anaconda\lib\site-packages (from cryp
tography>=0.7->PyOpenSSL->ndg-httpsclient)
Collecting pyasn1 (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Downloading pyasn1-0.1.8.tar.gz (75kB)
←[K    100% |################################| 77kB 3.2MB/s eta 0:00:01
Collecting setuptools (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Downloading setuptools-18.0.1-py2.py3-none-any.whl (461kB)
←[K    100% |################################| 462kB 910kB/s ta 0:00:011
Requirement already up-to-date: enum34 in c:\anaconda\lib\site-packages (from cr
yptography>=0.7->PyOpenSSL->ndg-httpsclient)
Collecting ipaddress (from cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
  Downloading ipaddress-1.0.14-py27-none-any.whl
Requirement already up-to-date: cffi>=0.8 in c:\anaconda\lib\site-packages (from
 cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
Requirement already up-to-date: pycparser in c:\anaconda\lib\site-packages (from
 cffi>=0.8->cryptography>=0.7->PyOpenSSL->ndg-httpsclient)
Installing collected packages: PyOpenSSL, pyasn1, setuptools, ipaddress
  Found existing installation: pyOpenSSL 0.14
←[33m    DEPRECATION: Uninstalling a distutils installed project (PyOpenSSL) has
 been deprecated and will be removed in a future version. This is due to the fac
t that uninstalling a distutils project will only partially uninstall the projec
t.←[0m
    Uninstalling pyOpenSSL-0.14:
      Successfully uninstalled pyOpenSSL-0.14
  Found existing installation: pyasn1 0.1.7
←[33m    DEPRECATION: Uninstalling a distutils installed project (pyasn1) has be
en deprecated and will be removed in a future version. This is due to the fact t
hat uninstalling a distutils project will only partially uninstall the project.←
[0m
    Uninstalling pyasn1-0.1.7:
      Successfully uninstalled pyasn1-0.1.7
  Running setup.py install for pyasn1
  Found existing installation: setuptools 0.6rc11
←[33m    DEPRECATION: Uninstalling a distutils installed project (setuptools) ha
s been deprecated and will be removed in a future version. This is due to the fa
ct that uninstalling a distutils project will only partially uninstall the proje
ct.←[0m
    Uninstalling setuptools-0.6rc11:
      Successfully uninstalled setuptools-0.6rc11
  Found existing installation: ipaddress 1.0.7
←[33m    DEPRECATION: Uninstalling a distutils installed project (ipaddress) has
 been deprecated and will be removed in a future version. This is due to the fac
t that uninstalling a distutils project will only partially uninstall the projec
t.←[0m
    Uninstalling ipaddress-1.0.7:
      Successfully uninstalled ipaddress-1.0.7
Successfully installed PyOpenSSL-0.15.1 ipaddress-1.0.14 pyasn1-0.1.8 setuptools
-18.0.1
```

After this, `conda update anaconda` works fine.

**Comment by peterwilliams97** [comment]
I am having the same issue.

 pip uninstall ndg-httpsclient

had no effect for me either

**Comment by pcp16** [comment]
natezb's method worked for me too!

**Comment by yoavram** [comment]
@natezb method worked for me with python 2., but when activating the python 3.5 environment, it doesn't help. I successfuly did `conda update requests` and `pip install --upgrade ndg-httpsclient`, but `conda update anaconda` still returns:
```
Fetching package metadata: ..An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 244, in install
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 404, in result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 356, in __get_result
    raise self._exception
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found
```
Here is the result of `conda info`:
```
Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda\envs\py3k
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Any ideas?

**Comment by pcp16** [comment]
Please see EDIT on my comment above, regarding natezb's workaround.

**Comment by yoavram** [comment]
So what now?

**Comment by saildata** [comment]
The following worked for me (Windows 7)
```
conda uninstall --offline ndg-httpsclient
```
Without the ``` --offline ``` option, it was still throwing the same error (pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found). 

Note: "InsecurePlatformWarning" is back, but at least everything else seems to be working.

**Comment by yoavram** [comment]
This doesn't help, as ndg-httpsclient wasn't installed with conda.
I'm creating a new conda environment anyway as conda with python 3.3 can't install jupyter; hopefully this will go away.

**Comment by kalefranz** [comment]
Old and outdated. Closing.
