### ISSUE TITLE
Problem with update in OS X

### ISSUE THREAD

**Issue by mfhepp** [conda/conda#1263]
I ran into the following problem when trying to update IPython to/from Version 2.3.1 on OSX 10.10.2.

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 589, in execute_actions
    execute_plan(plan, index, verbose)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 571, in execute_plan
    link(prefix, arg, index=index)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 520, in link
    _link(src, dst, lt)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 133, in _link
    shutil.copy2(src, dst)
  File "//anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "//anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '//anaconda/include/openssl/opensslconf.h'

**Comment by ccordoba12** [comment]
What command did you run before getting this error?

**Comment by asmeurer** [comment]
Typically these permissions errors are the result of using sudo with conda, and then not using sudo.

**Comment by mfhepp** [comment]
Thanks  for your feedback. In the end, I tried a fresh install, which worked.

**Comment by ccordoba12** [comment]
Ok, thanks for the update.
