### ISSUE TITLE
traceback error on `conda config --append channels defaults` command

### ISSUE THREAD

**Issue by NRees-Anaconda** [conda/conda#12644]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to run `conda config --append channels defaults` to update my `.condarc` file and I am getting the following traceback error.

```
Traceback (most recent call last):
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_config.py", line 29, in execute
    execute_config(args, parser)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_config.py", line 340, in execute_config
    raise CouldntParseError(f"key {key!r} should be a list, not {bad}.")
conda.exceptions.CouldntParseError: key 'channels' should be a list, not NoneType.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1124, in __call__
    return func(*args, **kwargs)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 69, in main_subshell
    exit_code = do_call(args, p)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
    return getattr(module, func_name)(args, parser)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_config.py", line 31, in execute
    raise CondaError(e)
conda.CondaError: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/__init__.py", line 66, in __str__
    return str(self.message % self._kwargs)
TypeError: unsupported operand type(s) for %: 'CouldntParseError' and 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nrees/opt/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 112, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1424, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1127, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1156, in handle_exception
    return self.handle_application_exception(exc_val, exc_tb)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1170, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1174, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/exceptions.py", line 1101, in print_conda_exception
    stderrlog.error("\n%r\n", exc_val)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/logging/__init__.py", line 1475, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/logging/__init__.py", line 1598, in handle
    if (not self.disabled) and self.filter(record):
  File "/Users/nrees/opt/anaconda3/lib/python3.9/logging/__init__.py", line 806, in filter
    result = f.filter(record)
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/gateways/logging.py", line 48, in filter
    record.msg = record.msg % new_args
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/__init__.py", line 62, in __repr__
    return f"{self.__class__.__name__}: {self}"
  File "/Users/nrees/opt/anaconda3/lib/python3.9/site-packages/conda/__init__.py", line 68, in __str__
    debug_message = "\n".join((
TypeError: sequence item 2: expected str instance, CouldntParseError found
```

### Conda Info

```shell
active environment : base
    active env location : /Users/nrees/opt/anaconda3
            shell level : 1
       user config file : /Users/nrees/.condarc
 populated config files : /Users/nrees/.condarc
          conda version : 23.1.0
    conda-build version : 3.23.3
         python version : 3.9.12.final.0
       virtual packages : __archspec=1=x86_64
                          __osx=10.16=0
                          __unix=0=0
       base environment : /Users/nrees/opt/anaconda3  (writable)
      conda av data dir : /Users/nrees/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.cloud/repo/main/osx-64
                          https://repo.anaconda.cloud/repo/main/noarch
                          https://repo.anaconda.cloud/repo/r/osx-64
                          https://repo.anaconda.cloud/repo/r/noarch
                          https://repo.anaconda.cloud/repo/msys2/osx-64
                          https://repo.anaconda.cloud/repo/msys2/noarch
          package cache : /Users/nrees/opt/anaconda3/pkgs
                          /Users/nrees/.conda/pkgs
       envs directories : /Users/nrees/opt/anaconda3/envs
                          /Users/nrees/.conda/envs
               platform : osx-64
             user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.12 Darwin/21.2.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/nrees/.condarc <==
extra_safety_checks: False
ssl_verify: True
add_anaconda_token: True
channels: []
default_channels:
  - https://repo.anaconda.cloud/repo/main
  - https://repo.anaconda.cloud/repo/r
  - https://repo.anaconda.cloud/repo/msys2
restore_free_channel: False
```

### Conda list

```shell
# packages in environment at /Users/nrees/opt/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py39hecd8cb5_1    https://repo.anaconda.com/pkgs/main
alabaster                 0.7.12             pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
anaconda-client           1.11.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
anaconda-navigator        2.3.2            py39hecd8cb5_0    defaults
anyio                     3.5.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
appnope                   0.1.2           py39hecd8cb5_1001    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
argon2-cffi               21.3.0             pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
argon2-cffi-bindings      21.2.0           py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
asttokens                 2.0.5              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
attrs                     22.1.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
babel                     2.11.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
backcall                  0.2.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
backports                 1.1                pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
backports.tempfile        1.0                pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
backports.weakref         1.0.post1                  py_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
beautifulsoup4            4.11.1           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
bleach                    4.1.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
brotlipy                  0.7.0           py39h9ed2024_1003    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
bzip2                     1.0.8                h1de35cc_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ca-certificates           2023.01.10           hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
cctools                   949.0.1             h9abeeb2_25    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
cctools_osx-64            949.0.1             hc7db93f_25    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
certifi                   2022.12.7        py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
cffi                      1.15.1           py39hc55c11b_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
chardet                   4.0.0           py39hecd8cb5_1003    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
charset-normalizer        2.0.4              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
click                     8.0.4            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
clyent                    1.2.2            py39hecd8cb5_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
colorama                  0.4.6            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
comm                      0.1.2            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda                     23.1.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda-build               3.23.3           py39hecd8cb5_0    https://repo.anaconda.com/pkgs/main
conda-content-trust       0.1.3            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda-env                 2.6.0                         1    https://repo.anaconda.com/pkgs/main
conda-package-handling    2.0.2            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda-package-streaming   0.7.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda-repo-cli            1.0.27           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda-token               0.4.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
conda-verify              3.4.2                      py_1    https://repo.anaconda.com/pkgs/main
cryptography              38.0.4           py39hf6deb26_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
debugpy                   1.5.1            py39he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
decorator                 5.1.1              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
defusedxml                0.7.1              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
docutils                  0.18.1           py39hecd8cb5_3    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
entrypoints               0.4              py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
executing                 0.8.3              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
filelock                  3.9.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
flit-core                 3.6.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
freetype                  2.12.1               hd8bbffd_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
future                    0.18.2           py39hecd8cb5_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
gettext                   0.21.0               h7535e17_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
giflib                    5.2.1                h6c40b1e_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
glib                      2.69.1               h8346a28_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
glob2                     0.7                pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
gst-plugins-base          1.14.0               h4180768_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
gstreamer                 1.14.0               h0fc69c2_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
icu                       58.2                 h0a44026_3    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
idna                      3.4              py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
imagesize                 1.4.1            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
importlib-metadata        4.11.3           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ipykernel                 6.19.2           py39h01d92e1_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ipython                   8.8.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ipython_genutils          0.2.0              pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ipywidgets                7.6.5              pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jedi                      0.18.1           py39hecd8cb5_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jinja2                    2.11.3             pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jpeg                      9e                   hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jq                        1.6               h9ed2024_1000    https://repo.anaconda.com/pkgs/main
json5                     0.9.6              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jsonschema                4.16.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyter_client            7.4.8            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyter_core              5.1.1            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyter_server            1.23.4           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyterlab                3.5.3            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyterlab_pygments       0.1.2                      py_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyterlab_server         2.10.3             pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
krb5                      1.19.4               hdba6334_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
lcms2                     2.12                 hf1fd2bf_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ld64                      530                 h20443b4_25    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ld64_osx-64               530                 h70f3046_25    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ldid                      2.1.2                h2d21305_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
lerc                      3.0                  he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libarchive                3.6.2                h65c5294_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libclang                  12.0.0          default_hbc2896b_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libcxx                    14.0.6               h9765a3e_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libdeflate                1.8                  h9ed2024_5    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libedit                   3.1.20221030         h6c40b1e_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libffi                    3.3                  hb1e8313_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libiconv                  1.16                 hca72f7f_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
liblief                   0.12.3               hcec6c5f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libllvm12                 12.0.0               h9b2ccf5_3    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libllvm14                 14.0.6               he552d86_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libpng                    1.6.37               ha441bb4_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libpq                     12.9                 h1c9f633_3    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libsodium                 1.0.18               h1de35cc_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libtiff                   4.5.0                hcec6c5f_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libwebp                   1.2.4                h56c3ce4_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libwebp-base              1.2.4                hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libxml2                   2.9.14               hbf8cd5e_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
libxslt                   1.1.35               h5b33f42_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
llvm-openmp               14.0.6               h0dcd299_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
lz4-c                     1.9.4                hcec6c5f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
markupsafe                2.0.1            py39h9ed2024_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
matplotlib-inline         0.1.6            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
mistune                   0.8.4           py39h9ed2024_1000    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
navigator-updater         0.2.1                    py39_1    https://repo.anaconda.com/pkgs/main
nbclassic                 0.4.8            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
nbclient                  0.5.13           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
nbconvert                 6.4.4            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
nbformat                  5.7.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ncurses                   6.4                  hcec6c5f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
nest-asyncio              1.5.6            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
notebook                  6.5.2            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
notebook-shim             0.2.2            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
nspr                      4.33                 he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
nss                       3.74                 h47edf6a_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
oniguruma                 6.9.7.1              h9ed2024_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
openssl                   1.1.1t               hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
packaging                 22.0             py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pandocfilters             1.5.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
parso                     0.8.3              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
patch                     2.7.6             h1de35cc_1001    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pathlib                   1.0.1              pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pcre                      8.45                 h23ab428_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pexpect                   4.8.0              pyhd3eb1b0_3    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pickleshare               0.7.5           pyhd3eb1b0_1003    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pillow                    9.3.0            py39hcec6c5f_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pkginfo                   1.8.3            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
platformdirs              2.5.2            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pluggy                    1.0.0            py39hecd8cb5_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ply                       3.11             py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
prometheus_client         0.14.1           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
prompt-toolkit            3.0.36           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
psutil                    5.9.0            py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ptyprocess                0.7.0              pyhd3eb1b0_2    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pure_eval                 0.2.2              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
py-lief                   0.12.3           py39hcec6c5f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pycosat                   0.6.4            py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pycparser                 2.21               pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pygments                  2.11.2             pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyjwt                     2.4.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyopenssl                 22.0.0             pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyqt                      5.15.7           py39he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyqt5-sip                 12.11.0          py39he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyrsistent                0.18.0           py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pysocks                   1.7.1            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
python                    3.9.12               hdfd78df_0    https://repo.anaconda.com/pkgs/main
python-dateutil           2.8.2              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
python-fastjsonschema     2.16.2           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
python-libarchive-c       2.9                pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
python.app                3                py39hca72f7f_0    https://repo.anaconda.com/pkgs/main
pytz                      2022.7           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyyaml                    6.0              py39h6c40b1e_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
pyzmq                     23.2.0           py39he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
qt-main                   5.15.2               h719ae48_7    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
qt-webengine              5.15.9               h90a370e_4    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
qtpy                      2.2.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
qtwebkit                  5.212                h24dc246_4    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
readline                  8.2                  hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
requests                  2.28.1           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ripgrep                   13.0.0               hc2228c6_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ruamel.yaml               0.17.21          py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ruamel.yaml.clib          0.2.6            py39hca72f7f_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ruamel_yaml               0.15.100         py39h9ed2024_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
send2trash                1.8.0              pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
setuptools                65.6.3           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sip                       6.6.2            py39he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
six                       1.16.0             pyhd3eb1b0_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sniffio                   1.2.0            py39hecd8cb5_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
snowballstemmer           2.2.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
soupsieve                 2.3.2.post1      py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sphinx                    5.0.2            py39hecd8cb5_0    https://repo.anaconda.com/pkgs/main
sphinx-sitemap            2.2.0                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
sqlite                    3.40.1               h880c91c_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
stack_data                0.2.0              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
tapi                      1000.10.8            ha1b3eb9_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
terminado                 0.17.1           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
testpath                  0.6.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
tk                        8.6.12               h5d9f67b_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
toml                      0.10.2             pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
tomli                     2.0.1            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
toolz                     0.12.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
tornado                   6.2              py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
tqdm                      4.64.1           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
traitlets                 5.7.1            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
typing-extensions         4.4.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
typing_extensions         4.4.0            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
tzdata                    2022g                h04d1e81_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
ujson                     5.4.0            py39he9d5cce_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
urllib3                   1.26.14          py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
wcwidth                   0.2.5              pyhd3eb1b0_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
webencodings              0.5.1            py39hecd8cb5_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
websocket-client          0.58.0           py39hecd8cb5_4    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
widgetsnbextension        3.5.2            py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
xz                        5.2.10               h6c40b1e_1    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
yaml                      0.2.5                haf1e3a3_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
zeromq                    4.3.4                h23ab428_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
zipp                      3.11.0           py39hecd8cb5_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
zlib                      1.2.13               h4dc903c_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
zstandard                 0.18.0           py39hca72f7f_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
zstd                      1.5.2                hcb37349_0    https://repo.anaconda.cloud/repo/anacondabusiness/snakes
```

### Additional Context

Here is the readout of my `.condarc` file.

```
channels:

add_anaconda_token: true
restore_free_channel: false
extra_safety_checks: false
ssl_verify: true
default_channels:
  - https://repo.anaconda.cloud/repo/main
  - https://repo.anaconda.cloud/repo/r
  - https://repo.anaconda.cloud/repo/msys2
```
My channels list was empty when I ran `conda config --append channels defaults`.

**Comment by travishathaway** [comment]
Hi @NRees-Anaconda,

Thanks for filing this issue. This happens because the parsing of `.condarc` files is currently very fragile. Small mistakes in the file cause `conda` to blow up in unsavory tracebacks.

I've added this issue to the following epic:

- https://github.com/conda/conda/issues/12259

Addressing this will require us to refactor how our configuration file parsing works, which is something I personally have put a considerable amount thought into.

Unfortunately, we cannot promise a release date for such fixes. Just be sure to keep your `.condarc` files valid in the meantime.
