### ISSUE TITLE
OSError: [Errno 24] Too many open files: '/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main_info.py'

### ISSUE THREAD

**Issue by YDD99** [conda/conda#12658]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Traceback (most recent call last):
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1124, in __call__
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main.py", line 69, in main_subshell
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/notices/core.py", line 109, in wrapper
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main_update.py", line 20, in execute
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/install.py", line 264, in install
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/solve.py", line 132, in solve_for_transaction
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/solve.py", line 175, in solve_for_diff
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/solve.py", line 246, in solve_final_state
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/solve.py", line 1106, in __init__
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/prefix_data.py", line 136, in iter_records
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/prefix_data.py", line 165, in _prefix_records
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/common/io.py", line 84, in decorated
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/prefix_data.py", line 69, in load
OSError: [Errno 24] Too many open files: b'/home/xly/soft/mambaforge-pypy3/conda-meta'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xly/soft/mambaforge-pypy3/bin/conda", line 13, in <module>
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main.py", line 112, in main
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1424, in conda_exception_handler
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1127, in __call__
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1167, in handle_exception
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1178, in handle_unexpected_exception
  File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/exceptions.py", line 1240, in print_unexpected_error_report
OSError: [Errno 24] Too many open files: '/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main_info.py'

### Conda Info

```shell
conda info

     active environment : base
    active env location : /home/xly/soft/mambaforge-pypy3
            shell level : 1
       user config file : /home/xly/.condarc
 populated config files : /home/xly/soft/mambaforge-pypy3/.condarc
                          /home/xly/.condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/xly/soft/mambaforge-pypy3  (writable)
      conda av data dir : /home/xly/soft/mambaforge-pypy3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/xly/soft/mambaforge-pypy3/pkgs
                          /home/xly/.conda/pkgs
       envs directories : /home/xly/soft/mambaforge-pypy3/envs
                          /home/xly/.conda/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.28.2 PyPy/3.9.16 Linux/5.19.0-41-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1008:1001
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
conda config --show-sources
==> /home/xly/soft/mambaforge-pypy3/.condarc <==
channels:
  - conda-forge

==> /home/xly/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
```

### Conda list

```shell
conda list --show-channel-urls
WARNING conda.core.prefix_data:_load_site_packages(291): Problem reading non-conda package record at lib/python3.9/site-packages/setuptools-65.5.1-py3.11.egg-info/PKG-INFO. Please verify that you still need this, and if so, that this is still installed correctly. Reinstalling this package may help.
# packages in environment at /home/xly/soft/mambaforge-pypy3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
aspera-cli                3.9.6                h5e1937b_0    hcc
bedops                    2.4.41               h9f5acd7_0    bioconda
bedtools                  2.30.0               h468198e_3    bioconda
brotlipy                  0.7.0           py39h4d8b378_1005    conda-forge
bwa                       0.7.17               h7132678_9    bioconda
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2022.12.7            ha878542_0    conda-forge
cairo                     1.16.0            ha61ee94_1014    conda-forge
capnproto                 0.9.1                ha19adfc_4    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39hfda2a12_3    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.1.0           py39h4162558_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
contourpy                 1.0.7                    pypi_0    pypi
cryptography              39.0.2           py39h3fbe314_0    conda-forge
csvtk                     0.25.0               h9ee0642_0    bioconda
curl                      7.88.1               hdc1c0ab_0    conda-forge
cycler                    0.11.0                   pypi_0    pypi
expat                     2.5.0                h27087fc_0    conda-forge
fastme                    2.1.6.1              hec16e2b_1    bioconda
fastp                     0.22.0               h2e03b76_0    bioconda
fastqc                    0.11.9               hdfd78af_1    bioconda
fasttree                  2.1.11               hec16e2b_1    bioconda
fmt                       9.1.0                h924138e_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0                   pypi_0    pypi
freetype                  2.12.1               hca18f0e_1    conda-forge
gawk                      5.1.0                h7f98852_0    conda-forge
gdbm                      1.18                 h0a1914f_2    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
harfbuzz                  6.0.0                h8e241bc_0    conda-forge
htop                      3.2.2                h8228510_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-resources       5.10.2                   pypi_0    pypi
infernal                  1.1.4                h779adbc_0    bioconda
jellyfish                 0.9.0            py39h4d8b378_2    conda-forge
jolytree                  1.1b                 hdfd78af_1    bioconda
jpeg                      9e                   h0b41bf4_3    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4                    pypi_0    pypi
krb5                      1.20.1               h81ceb04_0    conda-forge
lcms2                     2.15                 hfd0df8a_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libarchive                3.5.2                hada088e_3    conda-forge
libblas                   3.9.0           16_linux64_openblas    conda-forge
libcblas                  3.9.0           16_linux64_openblas    conda-forge
libcups                   2.3.3                h36d4200_3    conda-forge
libcurl                   7.88.1               hdc1c0ab_0    conda-forge
libdeflate                1.17                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 12.2.0              h65d4601_19    conda-forge
libgfortran-ng            12.2.0              h69a702a_19    conda-forge
libgfortran5              12.2.0              h337968e_19    conda-forge
libglib                   2.74.1               h606061b_1    conda-forge
libgomp                   12.2.0              h65d4601_19    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libmamba                  1.0.0                h9eff5f0_2    conda-forge
libmambapy                1.0.0            py39h64ccbee_2    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnl                     3.7.0                h166bdaf_0    conda-forge
libopenblas               0.3.21          pthreads_h78a6416_3    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsolv                   0.7.23               h3eb15da_0    conda-forge
libsqlite                 3.40.0               h753d276_0    conda-forge
libssh2                   1.10.0               hf14f497_3    conda-forge
libstdcxx-ng              12.2.0              h46fd767_19    conda-forge
libtiff                   4.5.0                h6adf6a1_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libwebp-base              1.2.4                h166bdaf_0    conda-forge
libxcb                    1.13              h7f98852_1004    conda-forge
libxml2                   2.10.3               h7463322_0    conda-forge
libzlib                   1.2.13               h166bdaf_4    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
mafft                     7.508                hec16e2b_0    bioconda
mamba                     1.0.0            py39hcbb6966_2    conda-forge
mash                      2.3                  ha9a2dd8_3    bioconda
matplotlib                3.7.0                    pypi_0    pypi
ncbi-genome-download      0.3.1              pyh5e36f6f_0    bioconda
ncurses                   6.3                  h27087fc_1    conda-forge
openjdk                   17.0.3               h58dac75_5    conda-forge
openmp                    7.0.0                h2d50403_0    conda-forge
openssl                   3.1.0                hd590300_2    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.26.2            h36c2ea0_1008    conda-forge
pillow                    9.4.0                    pypi_0    pypi
pip                       22.3.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4            py39h4d8b378_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9                    pypi_0    pypi
pypy3.9                   7.3.11               h527bfed_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.16                0_73_pypy    conda-forge
python-dateutil           2.8.2                    pypi_0    pypi
python_abi                3.9               3_pypy39_pp73    conda-forge
readline                  8.1.2                h0f457ee_0    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
req                       1.3.190304ac         hdfd78af_1    bioconda
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21          py39h3d6e266_3    conda-forge
ruamel.yaml.clib          0.2.7            py39h3d6e266_1    conda-forge
samtools                  0.1.19              h20b1175_10    bioconda
seqkit                    2.3.1                h9ee0642_0    bioconda
setuptools                67.5.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0                   pypi_0    pypi
soapdenovo2               2.40                          0    bioconda
spades                    3.14.1               h95f258a_2    bioconda
sqlite                    3.40.0               h4ff8645_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
trnascan-se               2.0.9           pl5262h779adbc_1    bioconda
tzdata                    2022g                h191b570_0    conda-forge
urllib3                   1.26.14            pyhd8ed1ab_0    conda-forge
wheel                     0.38.4             pyhd8ed1ab_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.8.4                h0b41bf4_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
zipp                      3.13.0                   pypi_0    pypi
zlib                      1.2.13               h166bdaf_4    conda-forge
zstandard                 0.19.0           py39h033b22b_1    conda-forge
zstd                      1.5.2                h3eb15da_6    conda-forge
```

**Comment by travishathaway** [comment]
Hi @YDD99,

Thanks for filing this bug. I think it's pretty interesting that we've hit this limit 😅.

I did some searching around the internet and apparently this is something you can adjust yourself:

https://stackoverflow.com/questions/34588/how-do-i-change-the-number-of-open-files-limit-in-linux/8285278#8285278

To address this in conda, we could be catching this error and then informing the user on how to increase this limit.

In the meantime, setting this yourself on your operating system should do the trick.

**Comment by drewj-usnctech** [comment]
I've been fighting this for a week now and I think I just got a breakthrough.

On a test machine, I've increased the limit on number of opened files to an obscene amount. I keep getting an error similar to what @YDD99 posted. The breakthrough was seeing `pypy` in the traceback. Pulling an example from @YDD99's initial post
```
File "/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/core/prefix_data.py", line 69, in load
```

I was very confused why `pypy` showed up in my errors, and glad to see it found here. Because it pointed me to https://github.com/conda/conda/issues/12640 where, for some reason, conda will install and use pypy for things.

Which, in turn, pointed me to an open pypy issues from a few years ago: [multiprocessing leaking file descriptors](https://foss.heptapod.net/pypy/pypy/-/issues/3154)

**Comment by dbast** [comment]
@drewj-usnctech You installed the pypy version of miniforge ... there is no official conda support for pypy. Why not switching  to a non pypy miniforge/miniconda?... so installing:
* https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
* or https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh

You can still create+use pypy based environments via: `conda create --name myenv pypy $dep1 $dep2 && conda activate myenv` ... this avoids pypy and all the trouble in the base env where conda is living.

**Comment by YDD99** [comment]
Thank you very much !
&nbsp;


谢刘义
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel ***@***.***&gt;; 
发送时间: 2023年11月17日(星期五) 晚上6:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [conda/conda] OSError: [Errno 24] Too many open files: &#39;/home/xly/soft/mambaforge-pypy3/lib/pypy3.9/site-packages/conda/cli/main_info.py&#39; (Issue #12658)





 
@drewj-usnctech You installed the pypy version of miniforge ... there is no official conda support for pypy. Why not switching  to a non pypy miniforge/miniconda?... so installing:
  
https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh
 
or https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
  
You can still create+use pypy based environments via: conda create --name myenv pypy $dep1 $dep2 &amp;&amp; conda activate myenv ... this avoids pypy and all the trouble in the base env where conda is living.

**Comment by drewj-usnctech** [comment]
@dbast there was no intention to install pypy and as far as I can tell I did not install the pypy-flavored miniforge/miniconda. I've always grabbed the "standard" python miniconda from https://docs.conda.io/projects/miniconda/en/latest/#latest-miniconda-installer-links

I think it was picked up by either a dependency (as @travishathaway indicated in https://github.com/conda/conda/issues/12640#issuecomment-1816148977) or a conda install bug
