### ISSUE TITLE
conda install error

### ISSUE THREAD

**Issue by JunyangGao** [conda/conda#12664]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

% conda install -c conda-forge folium
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.6.final.0
       requests version : 2.30.0
       root environment : /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9  (read only)
    default environment : /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9
       envs directories : /Users/gao/.conda/envs
                          /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/envs
          package cache : /Users/gao/.conda/envs/.pkgs
                          /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

### Conda Info

```shell
Current conda install:

               platform : osx-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.6.final.0
       requests version : 2.30.0
       root environment : /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9  (read only)
    default environment : /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9
       envs directories : /Users/gao/.conda/envs
                          /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/envs
          package cache : /Users/gao/.conda/envs/.pkgs
                          /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False
```

### Conda Config

```shell
_
```

### Conda list

```shell
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
```

### Additional Context

% conda install -c conda-forge folium
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.9.6.final.0
       requests version : 2.30.0
       root environment : /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9  (read only)
    default environment : /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9
       envs directories : /Users/gao/.conda/envs
                          /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/envs
          package cache : /Users/gao/.conda/envs/.pkgs
                          /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/gao/Library/Python/3.9/bin/conda install -c conda-forge folium`

    Traceback (most recent call last):
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/cli/install.py", line 302, in install
        actions = install_actions(prefix, index, specs,
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/plan.py", line 484, in install_actions
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 871, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 908, in solve
        dists, new_specs = self.get_dists(specs)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 509, in get_dists
        if not full_prune(specs, optional, features):
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 488, in full_prune
        self.touch(spec, touched, filter)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 317, in touch
        return t_ms_(spec) if isinstance(spec, MatchSpec) else t_fkey_(spec)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)

......
......
......

      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 311, in t_fkey_
        t_ms_(ms)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 315, in t_ms_
        t_fkey_(fkey)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 307, in t_fkey_
        val = touched[fkey] = self.valid(fkey, filter)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 285, in valid
        return v_(spec)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 273, in v_
        return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fkey_(spec)
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 282, in v_fkey_
        val = filter[fkey] = all(v_ms_(ms) for ms in self.ms_depends(fkey))
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 558, in ms_depends
        deps = [MatchSpec(d) for d in rec.get('depends', [])]
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 558, in <listcomp>
        deps = [MatchSpec(d) for d in rec.get('depends', [])]
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/resolve.py", line 64, in __new__
        vspec = VersionSpec(parts[1])
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/version.py", line 326, in __new__
        return VersionSpec(('all', tuple(VersionSpec(s) for s in spec.split(','))))
      File "/Users/gao/Library/Python/3.9/lib/python/site-packages/conda/version.py", line 326, in <genexpr>
        return VersionSpec(('all', tuple(VersionSpec(s) for s in spec.split(','))))
    RecursionError: maximum recursion depth exceeded while calling a Python object

gao@Junyangs-MacBook-Air bin %

**Comment by travishathaway** [comment]
Hi @JunyangGao,

Thanks for filing this issue. You are currently using an unsupported version of conda. Please update to the latest version (`23.3.1`). If this error persists. Please file a separate bug report.

I will be closing this issue for now.
