### ISSUE TITLE
Collecting package metadata (current_repodata.json): failed

### ISSUE THREAD

**Issue by vweiwei** [conda/conda#12684]
### What happened?

I install the conda in my linux system. However, many conda commands are not available,such as conda create,conda search,conda update... .
When I use conda create,conda update ,the error is Collecting package metadata (current_repodata.json): failed 
I try to delete the .condarc, reinstall the conda, install a lower version. None of these actions work .
What should I do？ T_T

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/main_info.py", line 323, in execute
        info_dict = get_info_dict(args.system)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/main_info.py", line 179, in get_info_dict
        user_agent=context.user_agent,
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/auxlib/decorators.py", line 267, in new_fget
        cache[inner_attname] = func(self)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/base/context.py", line 835, in user_agent
        builder.append("%s/%s" % self.os_distribution_name_version)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/auxlib/decorators.py", line 267, in new_fget
        cache[inner_attname] = func(self)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/base/context.py", line 906, in os_distribution_name_version
        from conda._vendor.distro import id, version
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/_vendor/distro.py", line 1080, in <module>
        _distro = LinuxDistribution()
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/_vendor/distro.py", line 595, in __init__
        self._lsb_release_info = self._get_lsb_release_info() \
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/_vendor/distro.py", line 939, in _get_lsb_release_info
        raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
    subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.

`$ /home/linquanwei/miniconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /home/linquanwei/.condarc <==
channel_alias: http://mirrors.tuna.tsinghua.edu.cn/anaconda
channels:
  - defaults
custom_channels:
  conda-forge: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
default_channels:
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
show_channel_urls: True
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /home/linquanwei/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
bcrypt                    4.0.1                    pypi_0    pypi
boltons                   23.0.0          py310h06a4308_0    defaults
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2022.12.7       py310h06a4308_0    defaults
cffi                      1.15.1          py310h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.3.1          py310h06a4308_0    defaults
conda-content-trust       0.1.3           py310h06a4308_0    defaults
conda-package-handling    2.0.2           py310h06a4308_0    defaults
conda-package-streaming   0.7.0           py310h06a4308_0    defaults
cryptography              39.0.1          py310h9ce1e76_0    defaults
idna                      3.4             py310h06a4308_0    defaults
jplephem                  2.18                     pypi_0    pypi
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.2                h6a678d5_6    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
numpy                     1.24.3                   pypi_0    pypi
openssl                   1.1.1t               h7f8727e_0    defaults
packaging                 23.0            py310h06a4308_0    defaults
paramiko                  3.1.0                    pypi_0    pypi
pip                       23.1.2                   pypi_0    pypi
pluggy                    1.0.0           py310h06a4308_1    defaults
pycosat                   0.6.4           py310h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pynacl                    1.5.0                    pypi_0    pypi
pyopenssl                 23.0.0          py310h06a4308_0    defaults
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.10              h7a1cb2a_2    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.28.1          py310h06a4308_1    defaults
ruamel.yaml               0.17.21         py310h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    defaults
setuptools                67.7.2                   pypi_0    pypi
sgp4                      2.22                     pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_1    defaults
skyfield                  1.46                     pypi_0    pypi
sqlite                    3.41.1               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py310h06a4308_0    defaults
tqdm                      4.65.0          py310h2f386ee_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.15         py310h06a4308_0    defaults
wheel                     0.38.4          py310h06a4308_0    defaults
xz                        5.2.10               h5eee18b_1    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py310h5eee18b_0    defaults
```

</details>

### Additional Context

```
conda update conda
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 57, in __call__
        return cls._thread_local.session
    AttributeError: '_thread._local' object has no attribute 'session'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/notices/core.py", line 121, in wrapper
        return func(*args, **kwargs)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/cli/install.py", line 264, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 134, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 177, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 282, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 449, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1064, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/index.py", line 267, in get_reduced_index
        new_records = SubdirData.query_all(spec, channels=channels, subdirs=subdirs,
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/home/linquanwei/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/home/linquanwei/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/home/linquanwei/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
        return self.__get_result()
      File "/home/linquanwei/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/home/linquanwei/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 366, in _load
        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 107, in repodata
        session = CondaSession()
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 59, in __call__
        session = cls._thread_local.session = super().__call__()
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/gateways/connection/session.py", line 93, in __init__
        self.headers['User-Agent'] = context.user_agent
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/auxlib/decorators.py", line 267, in new_fget
        cache[inner_attname] = func(self)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/base/context.py", line 835, in user_agent
        builder.append("%s/%s" % self.os_distribution_name_version)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/auxlib/decorators.py", line 267, in new_fget
        cache[inner_attname] = func(self)
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/base/context.py", line 906, in os_distribution_name_version
        from conda._vendor.distro import id, version
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/_vendor/distro.py", line 1080, in <module>
        _distro = LinuxDistribution()
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/_vendor/distro.py", line 595, in __init__
        self._lsb_release_info = self._get_lsb_release_info() \
      File "/home/linquanwei/miniconda3/lib/python3.10/site-packages/conda/_vendor/distro.py", line 939, in _get_lsb_release_info
        raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
    subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.
```

`$ /home/linquanwei/miniconda3/bin/conda update conda`

```
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/linquanwei/miniconda3/bin/conda
             CONDA_PREFIX=/home/linquanwei/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/linquanwei/miniconda3/bin/python
               CONDA_ROOT=/home/linquanwei/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/linquanwei/miniconda3/bin:/home/linquanwei/miniconda3/condabin:/
                          usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games
                          :/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/linquanwei/miniconda3
            shell level : 1
       user config file : /home/linquanwei/.condarc
 populated config files : /home/linquanwei/.condarc
          conda version : 23.3.1
    conda-build version : not installed
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.27=0
                          __linux=5.4.0=0
                          __unix=0=0
       base environment : /home/linquanwei/miniconda3  (writable)
      conda av data dir : /home/linquanwei/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /home/linquanwei/miniconda3/pkgs
                          /home/linquanwei/.conda/pkgs
       envs directories : /home/linquanwei/miniconda3/envs
                          /home/linquanwei/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.10 Linux/5.4.0-84-generic Linux/unknown glibc/2.27
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

**Comment by dholth** [comment]
https://github.com/conda/conda/issues/12700 may help this issue.
