### ISSUE TITLE
conda env export / conda env create roundtrip doesn't work for dev packages

### ISSUE THREAD

**Issue by cjw296** [conda/conda#1270]
To reproduce:

```
conda env export > environment.yml
cd ~/anaconda/envs
rm -rf picky
cd -
$ conda env create 
Fetching package metadata: ....
Solving package specifications: Linking packages ...
[      COMPLETE      ]|###########################################################################################| 100%
You are using pip version 6.0.8, however version 6.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Exception:
Traceback (most recent call last):
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/basecommand.py", line 232, in main
    status = self.run(options, args)
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    name, None, isolated=options.isolated_mode,
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/req/req_install.py", line 181, in from_line
    isolated=isolated)
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/req/req_install.py", line 54, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2873, in parse
    reqs = list(parse_requirements(s))
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2820, in parse_requirements
    "version spec")
  File "/Users/chris/anaconda/envs/pickyconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in scan_list
    raise ValueError(msg, line, "at", line[p:])
ValueError: ('Expected version spec in', 'picky (/Users/chris/LocalGIT/picky)==0.0.dev0', 'at', ' (/Users/chris/LocalGIT/picky)==0.0.dev0')
```

The problematic line is in the pip section created by "conda env export":

```
  - picky (/Users/chris/LocalGIT/picky)==0.0.dev0
```

**Comment by cjw296** [comment]
@tswicegood - this is one that will prevent me using environment.yml, my most common used case would be:

```
git clone ...
cd ...
conda env create
```

...but my environment.yml *would* contain at least one package (the one in the checkout ;-)) that would need to be installed with `pip install -e .`

**Comment by tswicegood** [comment]
This issue was moved to conda/conda-env#71
