### ISSUE TITLE
The ftp server connection failed

### ISSUE THREAD

**Issue by zhuwqvip** [conda/conda#12717]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

```shell
(base) [root@h17r2n09 conda]# conda search zlib -c ftp://ftptrm:ftp123456@10.8.152.76:7621/conda_pkgs/pkgs  --override-channels
Loading channels: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 121, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/cli/main_search.py", line 69, in execute
        matches = sorted(SubdirData.query_all(spec, channel_urls, subdirs),
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/opt/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/opt/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/opt/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
        return self.__get_result()
      File "/opt/anaconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/opt/anaconda3/lib/python3.10/concurrent/futures/thread.py", line 89, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 366, in _load
        raw_repodata_str = self._repo.repodata(cache.state)  # type: ignore
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 122, in repodata
        response: Response = session.get(
      File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
        return self.request("GET", url, **kwargs)
      File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/anaconda3/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
        r = adapter.send(request, **kwargs)
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/gateways/connection/adapters/ftp.py", line 63, in send
        auth = self.get_username_password_from_header(request)
      File "/opt/anaconda3/lib/python3.10/site-packages/conda/gateways/connection/adapters/ftp.py", line 197, in get_username_password_from_header
        components = decoded.split(':')
    TypeError: a bytes-like object is required, not 'str'

```

### Conda Info

```shell
(base) [root@h17r2n09 conda]# conda info

     active environment : base
    active env location : /opt/anaconda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /opt/anaconda3  (writable)
      conda av data dir : /opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
          package cache : /opt/anaconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Linux/3.10.0-957.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
(base) [root@h17r2n09 conda]# conda config --show-sources
==> /root/.condarc <==
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
```

### Conda list

```shell
(base) [root@h17r2n09 conda]# conda list --show-channel-urls
# packages in environment at /opt/anaconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
anaconda-client           1.11.2          py310h06a4308_0    defaults
anaconda-navigator        2.4.0           py310h06a4308_0    defaults
anaconda-project          0.11.1          py310h06a4308_0    defaults
anyio                     3.5.0           py310h06a4308_0    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0          py310h7f8727e_0    defaults
arrow                     1.2.3           py310h06a4308_1    defaults
astroid                   2.14.2          py310h06a4308_0    defaults
astropy                   5.1             py310ha9d4c09_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     22.1.0          py310h06a4308_0    defaults
automat                   20.2.0                     py_0    defaults
autopep8                  1.6.0              pyhd3eb1b0_1    defaults
babel                     2.11.0          py310h06a4308_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
```

### Additional Context

We have modified the/opt/anaconda3 / lib/python3.10 / site - packages/conda/gateways/connection/adapters/FTP. Py the code in this file

    def get_username_password_from_header(self, request):
        """Given a PreparedRequest object, reverse the process of adding HTTP
        Basic auth to obtain the username and password. Allows the FTP adapter
        to piggyback on the basic auth notation without changing the control
        flow."""

        auth_header = request.headers.get('Authorization')

        if auth_header:
            # The basic auth header is of the form 'Basic xyz'. We want the
            # second part. Check that we have the right kind of auth though.
            encoded_components = auth_header.split()[:2]
            if encoded_components[0] != 'Basic':
                raise AuthenticationError('Invalid form of Authentication used.')
            else:
                encoded =  encoded_components[1]

            # Decode the base64 encoded string.
            decoded = b64decode(encoded)
            #decoded = "ftptrm:ftp123456"

            # The string is of the form 'username:password'. Split on the
            # colon.
            components = decoded.decode().split(':')
            #components = decoded.split(':')
            username = components[0]
            password = components[1]
            return (username, password)
        else:
            # No auth header. Return None.
            return None

**Comment by travishathaway** [comment]
Hi @zhuwqvip,

Thanks for submitting this issue. Does this work for you now with the changes you made to [conda/gateways/connection/adapters/ftp.py](https://github.com/conda/conda/blob/9d7f72855cbf7d60a623ee6c098e05c472a82bac/conda/gateways/connection/adapters/ftp.py)?

This could be useful knowledge to have to help us create our own bug fix for this issue.
