### ISSUE TITLE
After updating conda: cannot install anything (ImportError: libffi.so.6)

### ISSUE THREAD

**Issue by sdarougheh** [conda/conda#12729]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Since updating anaconda, I can no longer install/update any package, will get the error below -- conda list still works, for example.

<details>
<summary><code>error output</code></summary>

```
> $ conda install numpy -n myenv3
> Collecting package metadata (current_repodata.json): failed
> WARNING conda.exceptions:print_unexpected_error_report(1251): KeyError('pkgs_dirs')
> Traceback (most recent call last):
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
>     return func(*args, **kwargs)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 86, in main_subshell
>     exit_code = do_call(args, p)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
>     return getattr(module, func_name)(args, parser)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/notices/core.py", line 72, in wrapper
>     return_value = func(*args, **kwargs)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 22, in execute
>     install(args, parser, 'install')
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
>     should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
>     should_retry_solve)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 200, in solve_for_diff
>     force_remove, should_retry_solve)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 304, in solve_final_state
>     ssc = self._collect_all_metadata(ssc)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
>     return f(*args, **kwds)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 439, in _collect_all_metadata
>     _supplement_index_with_system(virtual_pkg_index)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 172, in _supplement_index_with_system
>     cuda_version = context.cuda_version
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 276, in new_fget
>     cache[inner_attname] = func(self)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
>     return func(*args, **kwargs)
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 935, in cuda_version
>     return cuda_detect()
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 38, in cuda_detect
>     import ctypes
>   File "/home/xx/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
>     from _ctypes import Union, Structure, Array
> ImportError: libffi.so.6: cannot open shared object file: No such file or directory
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1249, in print_unexpected_error_report
>     message_builder.append(get_main_info_str(error_report['conda_info']))
>   File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 237, in get_main_info_str
>     info_dict['_' + key] = ('\n' + 26 * ' ').join(info_dict[key])
> KeyError: 'pkgs_dirs'
> 
> # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
> 
>     Traceback (most recent call last):
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
>         return func(*args, **kwargs)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 86, in main_subshell
>         exit_code = do_call(args, p)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
>         return getattr(module, func_name)(args, parser)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/notices/core.py", line 72, in wrapper
>         return_value = func(*args, **kwargs)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 22, in execute
>         install(args, parser, 'install')
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
>         should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
>         should_retry_solve)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 200, in solve_for_diff
>         force_remove, should_retry_solve)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 304, in solve_final_state
>         ssc = self._collect_all_metadata(ssc)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 86, in decorated
>         return f(*args, **kwds)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 439, in _collect_all_metadata
>         _supplement_index_with_system(virtual_pkg_index)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 172, in _supplement_index_with_system
>         cuda_version = context.cuda_version
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 276, in new_fget
>         cache[inner_attname] = func(self)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
>         return func(*args, **kwargs)
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 935, in cuda_version
>         return cuda_detect()
>       File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 38, in cuda_detect
>         import ctypes
>       File "/home/xx/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
>         from _ctypes import Union, Structure, Array
>     ImportError: libffi.so.6: cannot open shared object file: No such file or directory
> 
> `$ /home/xx/anaconda3/bin/conda install numpy -n myenv3`
> 
>   environment variables:
> conda info could not be constructed.
> KeyError('pkgs_dirs')
> 
> An unexpected error has occurred. Conda has prepared the above report.
> 
> Upload successful.
> 
```
</details>

### Conda Info

```shell
$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1129, in __call__
        return func(*args, **kwargs)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 93, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 317, in execute
        info_dict = get_info_dict(args.system)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 135, in get_info_dict
        _supplement_index_with_system(virtual_pkg_index)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 172, in _supplement_index_with_system
        cuda_version = context.cuda_version
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/auxlib/decorators.py", line 276, in new_fget
        cache[inner_attname] = func(self)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/decorators.py", line 24, in wrapper
        return func(*args, **kwargs)
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/base/context.py", line 935, in cuda_version
        return cuda_detect()
      File "/home/xx/anaconda3/lib/python3.7/site-packages/conda/common/cuda.py", line 38, in cuda_detect
        import ctypes
      File "/home/xx/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory

`$ /home/xx/anaconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```

### Conda Config

```shell
$ conda config --show-sources
==> /home/xx/.condarc <==
ssl_verify: False
report_errors: True
```

### Conda list

<details>
<summary><code>conda list</code></summary>

```shell
$ conda list --show-channel-urls
# packages in environment at /home/xx/anaconda3/envs/myenv3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
abseil-cpp                20211102.0           hd4dd3e8_0    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
arrow-cpp                 8.0.0           py310h3098874_1    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
aws-c-common              0.4.57               he6710b0_1    defaults
aws-c-event-stream        0.1.6                h2531618_5    defaults
aws-checksums             0.1.9                he6710b0_0    defaults
aws-sdk-cpp               1.8.185              hce553d0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
blas                      1.0                         mkl    defaults
boost-cpp                 1.73.0              h7f8727e_12    defaults
bottleneck                1.3.5           py310ha9d4c09_0    defaults
brotli                    1.0.9                    pypi_0    pypi
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.0               h5eee18b_0    defaults
ca-certificates           2023.01.10           h06a4308_0    defaults
certifi                   2023.5.7        py310h06a4308_0    defaults
cffi                      1.15.1          py310h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
contourpy                 1.0.5           py310hdb19cb5_0    defaults
cryptography              39.0.1          py310h9ce1e76_0    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
cython                    0.29.33         py310h6a678d5_0    defaults
dbus                      1.13.18              hb2f20db_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
dill                      0.3.4              pyhd3eb1b0_0    defaults
et_xmlfile                1.1.0           py310h06a4308_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
expat                     2.4.9                h6a678d5_0    defaults
fontconfig                2.14.1               h4c34cd2_2    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.12.1               h4a9f257_0    defaults
gflags                    2.2.2                he6710b0_0    defaults
giflib                    5.2.1                h5eee18b_3    defaults
glib                      2.69.1               he621ea3_2    defaults
glog                      0.5.0                h2531618_0    defaults
grpc-cpp                  1.46.1               h33aed49_1    defaults
gst-plugins-base          1.14.1               h6a678d5_1    defaults
gstreamer                 1.14.1               h5eee18b_1    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.4             py310h06a4308_0    defaults
intel-openmp              2021.4.0          h06a4308_3561    defaults
ipython                   8.10.0          py310h06a4308_0    defaults
jedi                      0.18.1          py310h06a4308_1    defaults
joblib                    1.2.0           py310h06a4308_0    defaults
jpeg                      9e                   h5eee18b_1    defaults
kiwisolver                1.4.4           py310h6a678d5_0    defaults
krb5                      1.19.4               h568e23c_0    defaults
lcms2                     2.12                 h3be6417_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
lerc                      3.0                  h295c915_0    defaults
libboost                  1.73.0              h28710b8_12    defaults
libbrotlicommon           1.0.9                h5eee18b_7    defaults
libbrotlidec              1.0.9                h5eee18b_7    defaults
libbrotlienc              1.0.9                h5eee18b_7    defaults
libclang                  14.0.6          default_hc6dbbc7_1    defaults
libclang13                14.0.6          default_he11475f_1    defaults
libcurl                   7.88.1               h91b91d3_0    defaults
libdeflate                1.17                 h5eee18b_0    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libevent                  2.1.12               h8f2d780_0    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgfortran-ng            11.2.0               h00389a5_1    defaults
libgfortran5              11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libllvm11                 11.1.0               h9e868ea_6    defaults
libllvm14                 14.0.6               hdb19cb5_3    defaults
libnghttp2                1.46.0               hce63b2e_0    defaults
libpng                    1.6.39               h5eee18b_0    defaults
libpq                     12.9                 h16c4e8d_3    defaults
libprotobuf               3.20.3               he621ea3_0    defaults
libssh2                   1.10.0               h8f2d780_0    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libthrift                 0.15.0               hcc01f38_0    defaults
libtiff                   4.5.0                h6a678d5_2    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libwebp                   1.2.4                h11a3e52_1    defaults
libwebp-base              1.2.4                h5eee18b_1    defaults
libxcb                    1.15                 h7f8727e_0    defaults
libxkbcommon              1.0.1                h5eee18b_1    defaults
libxml2                   2.10.3               hcbfbd50_0    defaults
libxslt                   1.1.37               h2085143_0    defaults
llvmlite                  0.39.1          py310he621ea3_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
matplotlib                3.7.1           py310h06a4308_1    defaults
matplotlib-base           3.7.1           py310h1128e8f_1    defaults
matplotlib-inline         0.1.6           py310h06a4308_0    defaults
memory_profiler           0.58.0             pyhd3eb1b0_0    defaults
mkl                       2021.4.0           h06a4308_640    defaults
mkl-devel                 2021.4.0           h66538d2_640    defaults
mkl-include               2021.4.0           h06a4308_640    defaults
mkl-service               2.4.0           py310h7f8727e_0    defaults
mkl_fft                   1.3.1           py310hd6ae3a3_0    defaults
mkl_random                1.2.2           py310h00e6091_0    defaults
mpmath                    1.2.1                    pypi_0    pypi
munkres                   1.1.4                      py_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
nspr                      4.33                 h295c915_0    defaults
nss                       3.74                 h0370c37_0    defaults
numba                     0.56.4          py310h1128e8f_0    defaults
numexpr                   2.8.4           py310h8879344_0    defaults
numpy                     1.23.5          py310hd5efca6_0    defaults
numpy-base                1.23.5          py310h8e6c178_0    defaults
openpyxl                  3.0.9              pyhd3eb1b0_0    defaults
openssl                   1.1.1t               h7f8727e_0    defaults
orc                       1.7.4                hb3bc3d3_1    defaults
packaging                 23.0            py310h06a4308_0    defaults
pandas                    1.5.3           py310h1128e8f_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
pcre                      8.45                 h295c915_0    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.4.0           py310h6a678d5_0    defaults
pip                       23.0.1          py310h06a4308_0    defaults
ply                       3.11            py310h06a4308_0    defaults
pooch                     1.4.0              pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.36          py310h06a4308_0    defaults
psutil                    5.9.0           py310h5eee18b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
pyarrow                   8.0.0           py310h468efa6_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.15.1          py310h06a4308_1    defaults
pyopenssl                 23.0.0          py310h06a4308_0    defaults
pyparsing                 3.0.9           py310h06a4308_0    defaults
pyqt                      5.15.7          py310h6a678d5_1    defaults
pyqt5-sip                 12.11.0                  pypi_0    pypi
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.10              h7a1cb2a_2    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pytz                      2022.7          py310h06a4308_0    defaults
qt-main                   5.15.2               h8373d8f_8    defaults
qt-webengine              5.15.9               hbbf29b9_6    defaults
qtwebkit                  5.212                h3fafdc1_5    defaults
re2                       2022.04.01           h295c915_0    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.29.0          py310h06a4308_0    defaults
scipy                     1.10.1          py310hd5efca6_0    defaults
setuptools                66.0.0          py310h06a4308_0    defaults
sip                       6.6.2           py310h6a678d5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
snakeviz                  2.0.1           py310h06a4308_0    defaults
snappy                    1.1.9                h295c915_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
tbb                       2021.8.0             hdb19cb5_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toml                      0.10.2             pyhd3eb1b0_0    defaults
tornado                   6.2             py310h5eee18b_0    defaults
traitlets                 5.7.1           py310h06a4308_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.15         py310h06a4308_0    defaults
utf8proc                  2.6.1                h27cfd23_0    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
wheel                     0.38.4          py310h06a4308_0    defaults
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xlwt                      1.3.0           py310h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```
</details>

### Additional Context

I am on Ubuntu 20.04.6 LTS.

**Comment by MR-ENVYR** [comment]
I had a similar issue. For me it shows warning that zstandard could not be imported - Running without .conda support.  Then it says libarchive.so.19: cannot open shared object file: No such file or directory. After trying multiple random things I messed up the entire environment and nothing was working and had to perform a clean install. I installed all packages one by one and finally noticed that whenever the _libgcc_mutex is changed to conda-forge channel because of any update and the libarchive library is changed due to any reason or update. The warning and error pops  up immediately. The only way to get around right now for me is to go back to the revision where things were working and reinstall stuff using pip. Pip doesn't mess with the libgcc_mutex as far as I've noticed. Hope to get an update from the conda team on this.
