### ISSUE TITLE
Unable to update due to a certain notebook.json file not being found

### ISSUE THREAD

**Issue by NemaVatsala** [conda/conda#12747]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Ran conda update conda only to receive this error. Any advice would be much appreciated as none of the original conda functions are working for me anymore. 

```
Traceback (most recent call last):
  File "C:\Apps\Conda\lib\site-packages\conda\gateways\disk\create.py", line 245, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path +"n")), remove, prefix)
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 74, in install
    _install(path, remove, prefix, mode='user')
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Apps\\Conda\\Menu\\notebook.json/ menuinst Exception
Traceback (most recent call last):
  File "C:\Apps\Conda\lib\site-packages\conda\gateways\disk\create.py", line 245, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path +"n")), remove, prefix)
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 74, in install
    _install(path, remove, prefix, mode='user')
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Apps\\Conda\\Menu\\notebook.json- WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename C:\Apps\Conda\Lib\site-packages\matplotlib\mpl-data\fonts\ttf\DejaVuSans.ttf.  Please remove this file manually (you may need to reboot to free file handles)
done
ERROR conda.core.link:_execute(733): An error occurred while installing package 'defaults::scikit-learn-1.2.2-py38hd77b12b_1'.
Rolling back transaction: | WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(143): Could not remove or rename C:\Apps\Conda\Lib\site-packages\matplotlib\mpl-data\fonts\ttf\DejaVuSans.ttf.  Please remove this file manually (you may need to reboot to free file handles)
\ menuinst Exception
Traceback (most recent call last):
  File "C:\Apps\Conda\lib\site-packages\conda\gateways\disk\create.py", line 245, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path +"n")), remove, prefix)
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 74, in install
    _install(path, remove, prefix, mode='user')
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Apps\\Conda\\Menu\\notebook.json| menuinst Exception
Traceback (most recent call last):
  File "C:\Apps\Conda\lib\site-packages\conda\gateways\disk\create.py", line 245, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path +"n")), remove, prefix)
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 74, in install
    _install(path, remove, prefix, mode='user')
  File "C:\Apps\Conda\lib\site-packages\menuinst\__init__.py", line 33, in _install
    data = json.load(open(path))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Apps\\Conda\\Menu\\notebook.jsondone

LinkError: post-link script failed for package defaults::scikit-learn-1.2.2-py38hd77b12b_1
location of failed script: C:\Apps\Conda\Scripts\.scikit-learn-post-link.bat
==> script messages <==
<None>
==> script output <==
stdout: Failed to create temp directory "C:\Users\VATSALA NEMA\AppData\Local\Temp\conda-<RANDOM>\"

stderr:
return code: 1

()
```

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : C:\Users\VATSALA NEMA\.condarc
 populated config files : C:\Users\VATSALA NEMA\.condarc
          conda version : 22.9.0
    conda-build version : 3.20.5
         python version : 3.8.13.final.0
       virtual packages : __cuda=12.1=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Apps\Conda  (writable)
      conda av data dir : C:\Apps\Conda\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Apps\Conda\pkgs
                          C:\Users\VATSALA NEMA\.conda\pkgs
                          C:\Users\VATSALA NEMA\AppData\Local\conda\conda\pkgs
       envs directories : C:\Apps\Conda\envs
                          C:\Users\VATSALA NEMA\.conda\envs
                          C:\Users\VATSALA NEMA\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.8.13 Windows/10 Windows/10.0.22621
          administrator : False
             netrc file : C:\Users\VATSALA NEMA/.netrc
           offline mode : False
```

### Conda Config

```shell
C:\Users\VATSALA NEMA\.condarc <==
ssl_verify: True
channels:
  - defaults
report_errors: True
```

### Conda list

```shell
# Name                    Version                   Build  Channel
_anaconda_depends         2020.07                  py38_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0    defaults
_tflow_select             2.3.0                     eigen    defaults
absl-py                   0.15.0             pyhd3eb1b0_0    defaults
aiohttp                   3.8.1            py38h2bbff1b_1    defaults
aiosignal                 1.2.0              pyhd3eb1b0_0    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
anaconda                  custom                   py38_1    defaults
anaconda-client           1.11.0           py38haa95532_0    defaults
anaconda-navigator        2.0.3                    py38_0    defaults
anaconda-project          0.11.1           py38haa95532_0    defaults
anyio                     3.5.0            py38haa95532_0    defaults
argh                      0.26.2                   py38_0    defaults
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0    defaults
asn1crypto                1.5.1            py38haa95532_0    defaults
astor                     0.8.1            py38haa95532_0    defaults
astroid                   2.11.7           py38haa95532_0    defaults
astropy                   5.1              py38h080aedc_0    defaults
asttokens                 2.0.5              pyhd3eb1b0_0    defaults
astunparse                1.6.3                      py_0    defaults
async-timeout             4.0.2            py38haa95532_0    defaults
atomicwrites              1.4.0                      py_0    defaults
attrs                     21.4.0             pyhd3eb1b0_0    defaults
autopep8                  1.5.4                      py_0    defaults
babel                     2.9.1              pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
backports                 1.1                pyhd3eb1b0_0    defaults
backports.functools_lru_cache 1.6.4              pyhd3eb1b0_0    defaults
backports.shutil_get_terminal_size 1.0.0              pyhd3eb1b0_3    defaults
backports.tempfile        1.0                pyhd3eb1b0_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
bcrypt                    3.2.0            py38h2bbff1b_1    defaults
beautifulsoup4            4.11.1           py38haa95532_0    defaults
bitarray                  2.5.1            py38h2bbff1b_0    defaults
bkcharts                  0.2              py38haa95532_1    defaults
black                     22.6.0           py38haa95532_0    defaults
blas                      1.0                         mkl    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
blinker                   1.4              py38haa95532_0    defaults
blosc                     1.21.0               h19a0ad4_1    defaults
bokeh                     2.4.3            py38haa95532_0    defaults
boto                      2.49.0                   py38_0    defaults
bottleneck                1.3.5            py38h080aedc_0    defaults
brotli                    1.0.9                h2bbff1b_7    defaults
brotli-bin                1.0.9                h2bbff1b_7    defaults
brotlipy                  0.7.0           py38h2bbff1b_1003    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2022.07.19           haa95532_0    defaults
cachetools                4.2.2              pyhd3eb1b0_0    defaults
catalogue                 2.0.7            py38haa95532_0    defaults
certifi                   2022.9.24        py38haa95532_0    defaults
cffi                      1.15.1           py38h2bbff1b_0    defaults
cfitsio                   3.470                h2bbff1b_7    defaults
chardet                   4.0.0           py38haa95532_1003    defaults
charls                    2.2.0                h6c2663c_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.0.4            py38haa95532_0    defaults
cloudpickle               2.0.0              pyhd3eb1b0_0    defaults
clyent                    1.2.2                    py38_1    defaults
colorama                  0.4.5            py38haa95532_0    defaults
comtypes                  1.1.10          py38haa95532_1002    defaults
conda                     22.9.0           py38haa95532_0    defaults
conda-build               3.20.5                   py38_1    defaults
conda-content-trust       0.1.3            py38haa95532_0    defaults
conda-env                 2.6.0                         1    defaults
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    1.9.0            py38h8cc25b3_0    defaults
conda-repo-cli            1.0.20           py38haa95532_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
contextlib2               21.6.0           py38haa95532_0    defaults
cryptography              37.0.1           py38h21b164f_0    defaults
cudatoolkit               10.2.89              h74a9793_1    defaults
curl                      7.84.0               h2bbff1b_0    defaults
cycler                    0.11.0             pyhd3eb1b0_0    defaults
cymem                     2.0.6            py38hd77b12b_0    defaults
cython                    0.29.32          py38hd77b12b_0    defaults
cython-blis               0.7.7            py38h080aedc_0    defaults
cytoolz                   0.11.0           py38he774522_0    defaults
dask                      2022.2.1           pyhd3eb1b0_0    defaults
dask-core                 2022.2.1           pyhd3eb1b0_0    defaults
dataclasses               0.8                pyh6d0b6a4_7    defaults
datasets                  2.12.0                   pypi_0    pypi
debugpy                   1.5.1            py38hd77b12b_0    defaults
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
diff-match-patch          20200713           pyhd3eb1b0_0    defaults
distributed               2022.2.1           pyhd3eb1b0_0    defaults
docker-pycreds            0.4.0                    pypi_0    pypi
docutils                  0.18.1           py38haa95532_3    defaults
entrypoints               0.4              py38haa95532_0    defaults
et_xmlfile                1.1.0            py38haa95532_0    defaults
executing                 0.8.3              pyhd3eb1b0_0    defaults
fastcache                 1.1.0            py38he774522_0    defaults
fftw                      3.3.9                h2bbff1b_1    defaults
filelock                  3.6.0              pyhd3eb1b0_0    defaults
flake8                    3.8.4                      py_0    defaults
flask                     2.1.3            py38haa95532_0    defaults
fonttools                 4.25.0             pyhd3eb1b0_0    defaults
freetype                  2.10.4               hd328e21_0    defaults
frozenlist                1.2.0            py38h2bbff1b_0    defaults
fsspec                    2022.7.1         py38haa95532_0    defaults
future                    0.18.2                   py38_1    defaults
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gensim                    4.2.0            py38hcc40339_0    conda-forge
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    21.8.0           py38h2bbff1b_1    defaults
giflib                    5.2.1                h62dcd97_0    defaults
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.29                   pypi_0    pypi
glob2                     0.7                pyhd3eb1b0_0    defaults
gmpy2                     2.1.2            py38h7f96b67_0    defaults
google-auth               2.6.0              pyhd3eb1b0_0    defaults
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0    defaults
google-pasta              0.2.0              pyhd3eb1b0_0    defaults
greenlet                  1.1.1            py38hd77b12b_0    defaults
grpcio                    1.42.0           py38hc60d5dd_0    defaults
gym                       0.24.1                   pypi_0    pypi
gym-notices               0.0.7                    pypi_0    pypi
h5py                      2.10.0           py38h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
heapdict                  1.0.1              pyhd3eb1b0_0    defaults
html5lib                  1.1                pyhd3eb1b0_0    defaults
huggingface-hub           0.14.1                   pypi_0    pypi
icc_rt                    2022.1.0             h6049295_2    defaults
icu                       58.2                 ha925a31_3    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
imagecodecs               2021.8.26        py38hc0a7faf_1    defaults
imageio                   2.19.3           py38haa95532_0    defaults
imagesize                 1.4.1            py38haa95532_0    defaults
importlib-metadata        4.12.0                   pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0    defaults
importlib_resources       5.2.0              pyhd3eb1b0_1    defaults
iniconfig                 1.1.1              pyhd3eb1b0_0    defaults
intel-openmp              2021.4.0          haa95532_3556    defaults
intervaltree              3.1.0              pyhd3eb1b0_0    defaults
ipykernel                 6.15.2           py38haa95532_0    defaults
ipython                   8.4.0            py38haa95532_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
ipywidgets                7.6.5              pyhd3eb1b0_1    defaults
isort                     5.9.3              pyhd3eb1b0_0    defaults
itsdangerous              2.0.1              pyhd3eb1b0_0    defaults
jdcal                     1.4.1              pyhd3eb1b0_0    defaults
jedi                      0.17.2           py38haa95532_1    defaults
jinja2                    3.0.3              pyhd3eb1b0_0    defaults
joblib                    1.1.0              pyhd3eb1b0_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.9.6              pyhd3eb1b0_0    defaults
jsonschema                4.16.0           py38haa95532_0    defaults
jupyter                   1.0.0            py38haa95532_8    defaults
jupyter_client            7.3.5            py38haa95532_0    defaults
jupyter_console           6.4.3              pyhd3eb1b0_0    defaults
jupyter_core              4.10.0           py38haa95532_0    defaults
jupyter_server            1.18.1           py38haa95532_0    defaults
jupyterlab                3.4.4            py38haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
jupyterlab_server         2.15.2           py38haa95532_0    defaults
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1    defaults
keras                     2.4.3                    pypi_0    pypi
keras-applications        1.0.8                      py_1    defaults
keras-preprocessing       1.1.2              pyhd3eb1b0_0    defaults
keyring                   23.4.0           py38haa95532_0    defaults
kiwisolver                1.4.2            py38hd77b12b_0    defaults
krb5                      1.19.2               h5b6d351_0    defaults
langcodes                 3.3.0              pyhd3eb1b0_0    defaults
lazy-object-proxy         1.6.0            py38h2bbff1b_0    defaults
lcms2                     2.12                 h83e58a3_0    defaults
lerc                      3.0                  hd77b12b_0    defaults
libaec                    1.0.4                h33f27b4_1    defaults
libarchive                3.6.1                hebabd0d_0    defaults
libbrotlicommon           1.0.9                h2bbff1b_7    defaults
libbrotlidec              1.0.9                h2bbff1b_7    defaults
libbrotlienc              1.0.9                h2bbff1b_7    defaults
libcurl                   7.84.0               h86230a5_0    defaults
libdeflate                1.8                  h2bbff1b_5    defaults
libiconv                  1.16                 h2bbff1b_2    defaults
liblief                   0.11.5               hd77b12b_1    defaults
libllvm9                  9.0.1                h21ff451_0    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libprotobuf               3.20.1               h23ce68f_0    defaults
libsodium                 1.0.18               h62dcd97_0    defaults
libspatialindex           1.9.3                h6c2663c_0    defaults
libssh2                   1.10.0               hcd4344a_0    defaults
libtiff                   4.4.0                h8a3f274_0    defaults
libuv                     1.40.0               he774522_0    defaults
libwebp                   1.2.2                h2bbff1b_0    defaults
libxml2                   2.9.14               h0ad7f3c_0    defaults
libxslt                   1.1.35               h2bbff1b_0    defaults
libzopfli                 1.0.3                ha925a31_0    defaults
llvmlite                  0.38.0           py38h23ce68f_0    defaults
locket                    1.0.0            py38haa95532_0    defaults
lxml                      4.9.1            py38h1985fb9_0    defaults
lz4-c                     1.9.3                h2bbff1b_1    defaults
lzo                       2.10                 he774522_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.3.4            py38haa95532_0    defaults
markupsafe                2.1.1            py38h2bbff1b_0    defaults
matplotlib                3.5.2            py38haa95532_0    defaults
matplotlib-base           3.5.2            py38hd77b12b_0    defaults
matplotlib-inline         0.1.6            py38haa95532_0    defaults
mccabe                    0.6.1            py38haa95532_2    defaults
menuinst                  1.4.16           py38he774522_1    defaults
mistune                   0.8.4           py38he774522_1000    defaults
mkl                       2021.4.0           haa95532_640    defaults
mkl-service               2.4.0            py38h2bbff1b_0    defaults
mkl_fft                   1.3.1            py38h277e83a_0    defaults
mkl_random                1.2.2            py38hf11a4ad_0    defaults
mock                      4.0.3              pyhd3eb1b0_0    defaults
more-itertools            8.12.0             pyhd3eb1b0_0    defaults
mpc                       1.1.0                h7edee0f_1    defaults
mpfr                      4.0.2                h62dcd97_1    defaults
mpir                      3.0.0                hec2e145_1    defaults
mpmath                    1.2.1            py38haa95532_0    defaults
msgpack-python            1.0.3            py38h59b6b97_0    defaults
msys2-conda-epoch         20160418                      1    defaults
multidict                 5.2.0            py38h2bbff1b_3    defaults
multipledispatch          0.6.0                    py38_0    defaults
multiprocess              0.70.14                  pypi_0    pypi
munkres                   1.1.4                      py_0    defaults
murmurhash                1.0.7            py38hd77b12b_0    defaults
mypy_extensions           0.4.3            py38haa95532_1    defaults
navigator-updater         0.2.1                    py38_0    defaults
nbclassic                 0.3.5              pyhd3eb1b0_0    defaults
nbclient                  0.5.13           py38haa95532_0    defaults
nbconvert                 6.4.4            py38haa95532_0    defaults
nbformat                  5.5.0            py38haa95532_0    defaults
nest-asyncio              1.5.5            py38haa95532_0    defaults
networkx                  2.8.4            py38haa95532_0    defaults
ninja                     1.10.2               haa95532_5    defaults
ninja-base                1.10.2               h6d14046_5    defaults
nltk                      3.7                pyhd3eb1b0_0    defaults
nose                      1.3.7           pyhd3eb1b0_1008    defaults
notebook                  6.4.12           py38haa95532_0    defaults
numba                     0.55.1           py38hf11a4ad_0    defaults
numexpr                   2.8.3            py38hb80d3ca_0    defaults
numpy                     1.21.5           py38h7a0a035_3    defaults
numpy-base                1.21.5           py38hca35cd5_3    defaults
numpydoc                  1.4.0            py38haa95532_0    defaults
oauthlib                  3.2.0              pyhd3eb1b0_1    defaults
olefile                   0.46               pyhd3eb1b0_0    defaults
opencv-contrib-python     4.5.2.52                 pypi_0    pypi
openjpeg                  2.4.0                h4fc8c34_0    defaults
openpyxl                  3.0.10           py38h2bbff1b_0    defaults
openssl                   1.1.1q               h2bbff1b_0    defaults
opt_einsum                3.3.0              pyhd3eb1b0_1    defaults
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.4.4            py38hd77b12b_0    defaults
pandoc                    2.12                 haa95532_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
paramiko                  2.8.1              pyhd3eb1b0_0    defaults
parso                     0.7.0                      py_0    defaults
partd                     1.2.0              pyhd3eb1b0_1    defaults
path                      16.2.0             pyhd3eb1b0_0    defaults
path.py                   12.5.0               hd3eb1b0_0    defaults
pathlib                   1.0.1              pyhd3eb1b0_1    defaults
pathlib2                  2.3.6            py38haa95532_2    defaults
pathspec                  0.9.0            py38haa95532_0    defaults
pathtools                 0.1.2              pyhd3eb1b0_1    defaults
pathy                     0.6.1            py38haa95532_0    defaults
patsy                     0.5.2            py38haa95532_1    defaults
pep8                      1.7.1            py38haa95532_1    defaults
pexpect                   4.8.0              pyhd3eb1b0_3    defaults
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    9.2.0            py38hdc2b20a_1    defaults
pip                       22.1.2           py38haa95532_0    defaults
pkginfo                   1.8.2              pyhd3eb1b0_0    defaults
pkgutil-resolve-name      1.3.10           py38haa95532_0    defaults
platformdirs              2.5.2            py38haa95532_0    defaults
pluggy                    1.0.0            py38haa95532_1    defaults
ply                       3.11                     py38_0    defaults
powershell_shortcut       0.0.1                         3    defaults
preshed                   3.0.6            py38h6c2663c_0    defaults
prometheus_client         0.14.1           py38haa95532_0    defaults
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
prompt_toolkit            3.0.20               hd3eb1b0_0    defaults
protobuf                  3.20.1           py38hd77b12b_0    defaults
psutil                    5.9.0            py38h2bbff1b_0    defaults
ptyprocess                0.7.0              pyhd3eb1b0_2    defaults
pure_eval                 0.2.2              pyhd3eb1b0_0    defaults
py                        1.11.0             pyhd3eb1b0_0    defaults
py-lief                   0.11.5           py38hd77b12b_1    defaults
pyarrow                   12.0.0                   pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0    defaults
pyasn1-modules            0.2.8                      py_0    defaults
pycodestyle               2.6.0              pyhd3eb1b0_0    defaults
pycosat                   0.6.3            py38h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pycurl                    7.45.1           py38hcd4344a_0    defaults
pydantic                  1.8.2                    pypi_0    pypi
pydocstyle                6.1.1              pyhd3eb1b0_0    defaults
pydotplus                 2.0.2                    pypi_0    pypi
pyerfa                    2.0.0            py38h2bbff1b_0    defaults
pyflakes                  2.2.0              pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyjwt                     2.4.0            py38haa95532_0    defaults
pylint                    2.14.5           py38haa95532_0    defaults
pyls-black                0.4.6                hd3eb1b0_0    defaults
pyls-spyder               0.3.2              pyhd3eb1b0_0    defaults
pynacl                    1.5.0            py38h8cc25b3_0    defaults
pyodbc                    4.0.34           py38hd77b12b_0    defaults
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pyparsing                 3.0.9            py38haa95532_0    defaults
pyqt                      5.9.2            py38hd77b12b_6    defaults
pyreadline                2.1                      py38_1    defaults
pyrsistent                0.18.0           py38h196d8e1_0    defaults
pysocks                   1.7.1            py38haa95532_0    defaults
pytables                  3.6.1            py38ha5be198_0    defaults
pytesseract               0.3.10                   pypi_0    pypi
pytest                    7.1.2            py38haa95532_0    defaults
python                    3.8.13               h6244533_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
python-fastjsonschema     2.16.2           py38haa95532_0    defaults
python-graphviz           0.20                     pypi_0    pypi
python-jsonrpc-server     0.4.0                      py_0    defaults
python-language-server    0.36.2             pyhd3eb1b0_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.8.1           py3.8_cuda10.2_cudnn7_0    pytorch
pytz                      2022.1           py38haa95532_0    defaults
pywavelets                1.3.0            py38h2bbff1b_0    defaults
pywin32                   302              py38h2bbff1b_2    defaults
pywin32-ctypes            0.2.0                 py38_1000    defaults
pywinpty                  2.0.2            py38h5da7b33_0    defaults
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     23.2.0           py38hd77b12b_0    defaults
qdarkstyle                2.8.1                      py_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 1.0.3              pyhd3eb1b0_0    defaults
qtconsole                 5.3.2            py38haa95532_0    defaults
qtpy                      2.2.0            py38haa95532_0    defaults
regex                     2022.7.9         py38h2bbff1b_0    defaults
requests                  2.28.1           py38haa95532_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
responses                 0.18.0                   pypi_0    pypi
rope                      0.22.0             pyhd3eb1b0_0    defaults
rsa                       4.7.2              pyhd3eb1b0_1    defaults
rtree                     0.9.7            py38h2eaa2aa_1    defaults
ruamel_yaml               0.15.100         py38h2bbff1b_0    defaults
scikit-image              0.19.2           py38hf11a4ad_0    defaults
scikit-learn              1.1.1            py38hd77b12b_0    defaults
scipy                     1.9.1            py38he11b74f_0    defaults
seaborn                   0.11.2             pyhd3eb1b0_0    defaults
send2trash                1.8.0              pyhd3eb1b0_1    defaults
sentry-sdk                1.9.10                   pypi_0    pypi
setproctitle              1.3.2                    pypi_0    pypi
setuptools                63.4.1           py38haa95532_0    defaults
shellingham               1.3.1              pyhd3eb1b0_0    defaults
shortuuid                 1.0.9                    pypi_0    pypi
simplegeneric             0.8.1                    py38_2    defaults
singledispatch            3.7.0           pyhd3eb1b0_1001    defaults
sip                       4.19.13          py38hd77b12b_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
smart_open                5.2.1            py38haa95532_0    defaults
smmap                     5.0.0                    pypi_0    pypi
snappy                    1.1.9                h6c2663c_0    defaults
sniffio                   1.2.0            py38haa95532_1    defaults
snowballstemmer           2.2.0              pyhd3eb1b0_0    defaults
sortedcollections         2.1.0              pyhd3eb1b0_0    defaults
sortedcontainers          2.4.0              pyhd3eb1b0_0    defaults
soupsieve                 2.3.1              pyhd3eb1b0_0    defaults
spacy                     3.3.1            py38h0f1f7c2_0    defaults
spacy-legacy              3.0.9            py38haa95532_0    defaults
spacy-loggers             1.0.1              pyhd3eb1b0_0    defaults
sphinx                    5.0.2            py38haa95532_0    defaults
sphinxcontrib             1.0                      py38_1    defaults
sphinxcontrib-applehelp   1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-devhelp     1.0.2              pyhd3eb1b0_0    defaults
sphinxcontrib-htmlhelp    2.0.0              pyhd3eb1b0_0    defaults
sphinxcontrib-jsmath      1.0.1              pyhd3eb1b0_0    defaults
sphinxcontrib-qthelp      1.0.3              pyhd3eb1b0_0    defaults
sphinxcontrib-serializinghtml 1.1.5              pyhd3eb1b0_0    defaults
sphinxcontrib-websupport  1.2.4                      py_0    defaults
spyder                    4.2.5            py38haa95532_0    defaults
spyder-kernels            1.10.2           py38haa95532_0    defaults
sqlalchemy                1.4.39           py38h2bbff1b_0    defaults
sqlite                    3.39.2               h2bbff1b_0    defaults
srsly                     2.4.3            py38hd77b12b_0    defaults
stack_data                0.2.0              pyhd3eb1b0_0    defaults
statsmodels               0.13.2           py38h2bbff1b_0    defaults
sympy                     1.10.1           py38haa95532_0    defaults
tbb                       2021.6.0             h59b6b97_0    defaults
tblib                     1.7.0              pyhd3eb1b0_0    defaults
tensorboard               2.9.0            py38haa95532_0    defaults
tensorboard-data-server   0.6.0            py38haa95532_0    defaults
tensorboard-plugin-wit    1.8.1            py38haa95532_0    defaults
tensorflow                2.3.0           mkl_py38h8c0d9a2_0    defaults
tensorflow-base           2.3.0           eigen_py38h75a453f_0    defaults
tensorflow-estimator      2.6.0              pyh7b7c402_0    defaults
termcolor                 1.1.0            py38haa95532_1    defaults
terminado                 0.13.1           py38haa95532_0    defaults
tesseract                 0.1.3                    pypi_0    pypi
testpath                  0.6.0            py38haa95532_0    defaults
textdistance              4.2.1              pyhd3eb1b0_0    defaults
thinc                     8.0.15           py38h757b272_0    defaults
threadpoolctl             2.2.0              pyh0d69192_0    defaults
three-merge               0.1.1              pyhd3eb1b0_0    defaults
tifffile                  2021.7.2           pyhd3eb1b0_2    defaults
tk                        8.6.12               h2bbff1b_0    defaults
tokenizers                0.13.3                   pypi_0    pypi
toml                      0.10.2             pyhd3eb1b0_0    defaults
tomli                     2.0.1            py38haa95532_0    defaults
tomlkit                   0.11.1           py38haa95532_0    defaults
toolz                     0.11.2             pyhd3eb1b0_0    defaults
torchaudio                0.8.1                      py38    pytorch
torchvision               0.9.1                py38_cu102    pytorch
tornado                   6.2              py38h2bbff1b_0    defaults
tqdm                      4.64.1           py38haa95532_0    defaults
traitlets                 5.1.1              pyhd3eb1b0_0    defaults
transformers              4.29.2                   pypi_0    pypi
typer                     0.4.1            py38haa95532_0    defaults
typing-extensions         4.3.0            py38haa95532_0    defaults
typing_extensions         4.3.0            py38haa95532_0    defaults
ujson                     5.4.0            py38hd77b12b_0    defaults
unicodecsv                0.14.1                   py38_0    defaults
urllib3                   1.26.11          py38haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wandb                     0.13.4                   pypi_0    pypi
wasabi                    0.9.1            py38haa95532_0    defaults
watchdog                  1.0.2            py38haa95532_1    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py38_1    defaults
websocket-client          0.58.0           py38haa95532_4    defaults
werkzeug                  2.0.3              pyhd3eb1b0_0    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
widgetsnbextension        3.5.2            py38haa95532_0    defaults
win_inet_pton             1.1.0            py38haa95532_0    defaults
win_unicode_console       0.5                      py38_0    defaults
wincertstore              0.2              py38haa95532_2    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.14.1           py38h2bbff1b_0    defaults
xlrd                      2.0.1              pyhd3eb1b0_0    defaults
xlsxwriter                3.0.3              pyhd3eb1b0_0    defaults
xlwings                   0.27.15          py38haa95532_0    defaults
xlwt                      1.3.0                    py38_0    defaults
xmltodict                 0.12.0             pyhd3eb1b0_0    defaults
xxhash                    3.2.0                    pypi_0    pypi
xz                        5.2.6                h8cc25b3_0    defaults
yaml                      0.2.5                he774522_0    defaults
yapf                      0.31.0             pyhd3eb1b0_0    defaults
yarl                      1.8.1            py38h2bbff1b_0    defaults
zeromq                    4.3.4                hd77b12b_0    defaults
zfp                       0.5.5                hd77b12b_6    defaults
zict                      2.1.0            py38haa95532_0    defaults
zipp                      3.8.0            py38haa95532_0    defaults
zlib                      1.2.12               h8cc25b3_3    defaults
zope                      1.0                      py38_1    defaults
zope.event                4.5.0                    py38_0    defaults
zope.interface            5.4.0            py38h2bbff1b_0    defaults
zstd                      1.5.2                h19a0ad4_0    defaults
```

**Comment by jezdez** [comment]
@NemaVatsala Thank you for your bug report, I'm afraid somehow the conda environment seems to have been corrupted, and you'll probably have to uninstall and reinstall Anaconda or miniconda (with the newest version of the installer please) to get it working again. I don't understand why the error happens without more instructions to reproduce the error.

The error indicates that something went wrong while updating the Windows start menu entry for a conda environment named "notebook".
