### ISSUE TITLE
Python 3.10 Installation fails to properly install `unittest` from standard library. Mac OS Monterey 12.5. SafetyError Raised.

### ISSUE THREAD

**Issue by rgasper** [conda/conda#12750]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

If I create a new python 3.10 environment, the unittest library is not properly installed. This process works for python 3.9 and 3.11.

```
(base)  ~  conda create --name py310-test python==3.10
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /usr/local/anaconda3/envs/py310-test

  added / updated specs:
    - python==3.10


The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/osx-64::bzip2-1.0.8-h1de35cc_0
  ca-certificates    pkgs/main/osx-64::ca-certificates-2023.01.10-hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-14.0.6-h9765a3e_0
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.4-hcec6c5f_0
  openssl            pkgs/main/osx-64::openssl-1.1.1t-hca72f7f_0
  pip                pkgs/main/osx-64::pip-23.0.1-py310hecd8cb5_0
  python             pkgs/main/osx-64::python-3.10.0-hdfd78df_5
  readline           pkgs/main/osx-64::readline-8.2-hca72f7f_0
  setuptools         pkgs/main/osx-64::setuptools-67.8.0-py310hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.41.2-h6c40b1e_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0
  wheel              pkgs/main/osx-64::wheel-0.38.4-py310hecd8cb5_0
  xz                 pkgs/main/osx-64::xz-5.4.2-h6c40b1e_0
  zlib               pkgs/main/osx-64::zlib-1.2.13-h4dc903c_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: \ 
SafetyError: The package for python located at /usr/local/anaconda3/pkgs/python-3.10.0-hdfd78df_5
appears to be corrupted. The path 'lib/python3.10/unittest/case.py'
has an incorrect size.
  reported size: 57076 bytes
  actual size: 57080 bytes


done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py310-test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base)  ~  conda activate py310-test                  
(py310-test)  ~  python
Python 3.10.0 (default, Mar  3 2022, 03:57:21) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import unittest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/py310-test/lib/python3.10/unittest/__init__.py", line 60, in <module>
    from .case import (addModuleCleanup, TestCase, FunctionTestCase, SkipTest, skip,
  File "/usr/local/anaconda3/envs/py310-test/lib/python3.10/unittest/case.py", line 1352, in <module>
    class FunctionTestCase(TestCase):
NameError: name 'TestCase' is not defined
```

### Conda Info

```shell
active environment : py310-test
    active env location : /usr/local/anaconda3/envs/py310-test
            shell level : 2
       user config file : /Users/raymondgasper/.condarc
 populated config files : 
          conda version : 4.11.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/anaconda3  (writable)
      conda av data dir : /usr/local/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/anaconda3/pkgs
                          /Users/raymondgasper/.conda/pkgs
       envs directories : /usr/local/anaconda3/envs
                          /Users/raymondgasper/.conda/envs
               platform : osx-64
             user-agent : conda/4.11.0 requests/2.27.1 CPython/3.7.6 Darwin/21.6.0 OSX/10.16
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
# Nothing
```

### Conda list

```shell
# packages in environment at /usr/local/anaconda3/envs/py310-test:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h1de35cc_0    defaults
ca-certificates           2023.01.10           hecd8cb5_0    defaults
libcxx                    14.0.6               h9765a3e_0    defaults
libffi                    3.3                  hb1e8313_2    defaults
ncurses                   6.4                  hcec6c5f_0    defaults
openssl                   1.1.1t               hca72f7f_0    defaults
pip                       23.0.1          py310hecd8cb5_0    defaults
python                    3.10.0               hdfd78df_5    defaults
readline                  8.2                  hca72f7f_0    defaults
setuptools                67.8.0          py310hecd8cb5_0    defaults
sqlite                    3.41.2               h6c40b1e_0    defaults
tk                        8.6.12               h5d9f67b_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
wheel                     0.38.4          py310hecd8cb5_0    defaults
xz                        5.4.2                h6c40b1e_0    defaults
zlib                      1.2.13               h4dc903c_0    defaults
```

### Additional Context

See Safety Error raised during install:
```
SafetyError: The package for python located at /usr/local/anaconda3/pkgs/python-3.10.0-hdfd78df_5
appears to be corrupted. The path 'lib/python3.10/unittest/case.py'
has an incorrect size.
  reported size: 57076 bytes
  actual size: 57080 bytes
```

**Comment by rgasper** [comment]
Solved by removing environment, running `rm -rf /usr/local/anaconda3/pkgs/python-3.10.0-hdfd78df_5`, then creating environment again
