### ISSUE TITLE
traceback to the conda GitHub : error in fetching conda install --channel https://conda.binstar.org/jevans hdf4

### ISSUE THREAD

**Issue by Jeriane22** [conda/conda#1275]
Traceback (most recent call last):
  File "/Users/ariane/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/plan.py", line 407, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/plan.py", line 250, in ensure_linked_actions
    if install.try_hard_link(config.pkgs_dirs[0], prefix, dist):
  File "/Users/ariane/anaconda/lib/python2.7/site-packages/conda/install.py", line 400, in try_hard_link
    assert not isfile(dst), dst
AssertionError: /Users/ariane/anaconda/.tmp-conda-env-2.1.4-py27_0
bash-3.2$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.10.0
  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /Users/ariane/anaconda  (writable)
  default environment : /Users/ariane/anaconda
     envs directories : /Users/ariane/anaconda/envs
        package cache : /Users/ariane/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ariane/.condarc
    is foreign system : False

**Comment by soapy1** [comment]
Can't reproduce this on the newest version of conda. Please `conda update conda` if this is still an issue.
