### ISSUE TITLE
Package installed twice

### ISSUE THREAD

**Issue by gmarkall** [conda/conda#1276]
Somehow I seem to have installed Numba twice, resulting in the following traceback when I attempt to update:

```
$ conda update -c numba numba
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/gmarkall/.conda/envs/py34np19/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/opt/conda/python3/lib/python3.4/site-packages/conda/cli/install.py", line 262, in install
    assert len(vers_inst) == 1, name
AssertionError: numba
```

Output of `conda list`:

```
$ conda list
# packages in environment at /home/gmarkall/.conda/envs/py34np19:
#
Could not extract name and version from: 'You are using pip version 6.0.8, however version 6.1.1 is available.'
Could not extract name and version from: "You should consider upgrading via the 'pip install --upgrade pip' command."
accelerate                1.10.0              np19py34_p0  
cudatoolkit               6.0                          p0  
dateutil                  2.1                      py34_2  
docutils                  0.12                     py34_0  
freetype                  2.4.10                        0  
ipython                   3.0.0                    py34_0  
jinja2                    2.7.3                    py34_1  
jsonschema                2.4.0                    py34_0  
libpng                    1.5.13                        1  
libsodium                 0.4.5                         0  
llvmlite                  0.2.2                    py34_3  
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_0  
mkl                       11.1                np19py34_p3  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py34_p1  
mklfft                    2.0                 np19py34_p0  
nose                      1.3.4                    py34_1  
numba                     0.17.0               np19py34_0  
numba                     0.17.0             np19py34_237  
numbapro                  0.17.1              np19py34_p0  
numbapro_cudalib          0.2                           0  
numexpr                   2.3.1               np19py34_p0  [mkl]
numpy                     1.9.2                   py34_p0  [mkl]
openssl                   1.0.1k                        1  
pip                       6.0.8                    py34_0  
pudb                      2013.5.1                 py34_0  
pygments                  2.0.2                    py34_0  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.10.4                   py34_0  
python                    3.4.3                         0  
python-dateutil           2.1                       <pip>
pytz                      2014.9                   py34_0  
pyzmq                     14.5.0                   py34_0  
qt                        4.8.5                         0  
readline                  6.2                           2  
scikit-learn              0.15.2              np19py34_p0  [mkl]
scipy                     0.15.1              np19py34_p0  [mkl]
setuptools                14.3                     py34_0  
sip                       4.15.5                   py34_0  
six                       1.9.0                    py34_0  
sphinx                    1.2.3                    py34_0  
sqlite                    3.8.4.1                       1  
system                    5.8                           2  
tk                        8.5.18                        0  
tornado                   4.1                      py34_0  
urwid                     1.2.0                    py34_0  
xz                        5.0.5                         0  
zeromq                    4.0.4                         0  
zlib                      1.2.8                         0  
```

Output of `conda info`:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.7.3
  conda-build version : 1.9.0
       python version : 3.4.2.final.0
     requests version : 2.4.3
     root environment : /opt/conda/python3  (read only)
  default environment : /home/gmarkall/.conda/envs/py34np19
     envs directories : /home/gmarkall/.conda/envs
                        /home/gmarkall/envs
                        /opt/conda/python3/envs
        package cache : /home/gmarkall/.conda/envs/.pkgs
                        /home/gmarkall/envs/.pkgs
                        /opt/conda/python3/pkgs
         channel URLs : http://conda.binstar.org/numba/linux-64/
                        http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : /home/gmarkall/.condarc
    is foreign system : False
```

**Comment by asmeurer** [comment]
Any idea how it happened? Can you post the contents of the `/home/gmarkall/.conda/envs/py34np19/conda-meta/history` file?

**Comment by gmarkall** [comment]
It looks like I installed `numba-0.17.0-np19py34_0.tar.bz2` from the filesystem instead of from binstar:

```
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install numba-0.17.0-np19py34_0.tar.bz2
```

Full contents below:

```
==> 2015-03-10 08:57:26 <==
# cmd: /home/gmarkall/.conda/envs/p34/bin/conda create -n py34np19 python=3.4 ipython
==> 2015-03-10 08:57:26 <==
# cmd: /home/gmarkall/.conda/envs/p34/bin/conda create -n py34np19 python=3.4 ipython
+ipython-3.0.0-py34_0
+openssl-1.0.1k-0
+python-3.4.3-0
+readline-6.2-2
+sqlite-3.8.4.1-0
+system-5.8-1
+tk-8.5.15-0
+xz-5.0.5-0
+zlib-1.2.8-0
# create specs: ['python 3.4*', 'ipython']
==> 2015-03-10 08:58:09 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install accelerate
+accelerate-1.10.0-np19py34_p0
+cudatoolkit-6.0-p0
+llvmlite-0.2.2-py34_3
+mkl-11.1-np19py34_p3
+mkl-rt-11.1-p0
+mkl-service-1.0.0-py34_p1
+mklfft-2.0-np19py34_p0
+nose-1.3.4-py34_1
+numba-0.17.0-np19py34_237
+numbapro-0.17.1-np19py34_p0
+numbapro_cudalib-0.2-0
+numexpr-2.3.1-np19py34_p0
+numpy-1.9.2-py34_p0
+scikit-learn-0.15.2-np19py34_p0
+scipy-0.15.1-np19py34_p0
# install specs: ['accelerate', 'python 3.4*']
==> 2015-03-10 09:04:22 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install matplotlib
+dateutil-2.1-py34_2
+freetype-2.4.10-0
+libpng-1.5.13-1
+matplotlib-1.4.3-np19py34_0
+pyparsing-2.0.3-py34_0
+pyqt-4.10.4-py34_0
+pytz-2014.9-py34_0
+qt-4.8.5-0
+sip-4.15.5-py34_0
+six-1.9.0-py34_0
# install specs: ['matplotlib', 'python 3.4*']
==> 2015-03-10 09:08:28 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install numba
-llvmlite-0.2.2-py34_3
+llvmlite-0.3.0-py34_17
# install specs: ['numba', 'python 3.4*']
==> 2015-03-10 09:10:22 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install numba-0.17.0-np19py34_0.tar.bz2
+numba-0.17.0-np19py34_0
==> 2015-03-10 09:10:26 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install numba-0.17.0-np19py34_0.tar.bz2
-llvmlite-0.3.0-py34_17
-tk-8.5.15-0
+llvmlite-0.2.2-py34_3
+tk-8.5.17-0
# install specs: ['numpy 1.9*', 'python 3.4*', 'llvmlite 0.2.2']
==> 2015-03-10 09:15:25 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install accelerate
-numba-0.17.0-np19py34_0
-tk-8.5.17-0
+tk-8.5.15-0
# install specs: ['accelerate', 'python 3.4*']
==> 2015-03-10 09:21:59 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install pyzmq
+libsodium-0.4.5-0
+pyzmq-14.5.0-py34_0
+zeromq-4.0.4-0
# install specs: ['pyzmq', 'python 3.4*']
==> 2015-03-10 09:22:10 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install jinja2
+jinja2-2.7.3-py34_1
+markupsafe-0.23-py34_0
+setuptools-14.0-py34_0
# install specs: ['jinja2', 'python 3.4*']
==> 2015-03-10 09:22:18 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install tornado
+tornado-4.1-py34_0
# install specs: ['tornado', 'python 3.4*']
==> 2015-03-10 09:22:26 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install jsonschema
+jsonschema-2.4.0-py34_0
# install specs: ['jsonschema', 'python 3.4*']
==> 2015-03-10 09:35:37 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install numba=0.17.0
-llvmlite-0.2.2-py34_3
+llvmlite-0.3.0-py34_17
# install specs: ['numba 0.17|0.17.0*', 'python 3.4*']
==> 2015-03-10 09:48:59 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda remove numba
-numba-0.17.0-np19py34_237
# remove specs: ['numba']
==> 2015-03-10 09:49:11 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda remove numbapro
-numbapro-0.17.1-np19py34_p0
# remove specs: ['numbapro']
==> 2015-03-10 09:49:29 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda remove accelerate
-accelerate-1.10.0-np19py34_p0
-mkl-11.1-np19py34_p3
-numexpr-2.3.1-np19py34_p0
-numpy-1.9.2-py34_p0
-scikit-learn-0.15.2-np19py34_p0
-scipy-0.15.1-np19py34_p0
+numexpr-2.3.1-np19py34_0
+numpy-1.9.2-py34_0
+scikit-learn-0.15.2-np19py34_0
+scipy-0.15.1-np19py34_0
# remove specs: ['accelerate']
==> 2015-03-10 10:02:03 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install accelerate
-llvmlite-0.3.0-py34_17
-numexpr-2.3.1-np19py34_0
-numpy-1.9.2-py34_0
-scikit-learn-0.15.2-np19py34_0
-scipy-0.15.1-np19py34_0
+accelerate-1.10.0-np19py34_p0
+llvmlite-0.2.2-py34_3
+mkl-11.1-np19py34_p3
+numba-0.17.0-np19py34_237
+numbapro-0.17.1-np19py34_p0
+numexpr-2.3.1-np19py34_p0
+numpy-1.9.2-py34_p0
+scikit-learn-0.15.2-np19py34_p0
+scipy-0.15.1-np19py34_p0
# install specs: ['accelerate', 'python 3.4*']
==> 2015-03-10 10:09:49 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install /home/gmarkall/downloads/numba-0.17.0-np19py34_0.tar.bz2
+numba-0.17.0-np19py34_0
==> 2015-03-10 10:09:52 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install /home/gmarkall/downloads/numba-0.17.0-np19py34_0.tar.bz2
-tk-8.5.15-0
+tk-8.5.17-0
# install specs: ['numpy 1.9*', 'python 3.4*', 'llvmlite 0.2.2']
==> 2015-03-10 10:39:50 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install llvmlite
-llvmlite-0.2.2-py34_3
-tk-8.5.17-0
+llvmlite-0.3.0-py34_17
+tk-8.5.15-0
# install specs: ['llvmlite', 'python 3.4*']
==> 2015-03-11 07:31:53 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install llvmlite=0.2
-llvmlite-0.3.0-py34_17
+llvmlite-0.2.2-py34_3
# install specs: ['llvmlite 0.2*', 'python 3.4*']
==> 2015-03-12 17:59:56 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda update -c numba llvmlite
-llvmlite-0.2.2-py34_3
-openssl-1.0.1k-0
-system-5.8-1
+llvmlite-0.3.0-py34_17
+openssl-1.0.1k-1
+system-5.8-2
# update specs: ['llvmlite', 'python 3.4*']
==> 2015-03-12 18:23:39 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda update -c numba llvmlite
-llvmlite-0.3.0-py34_17
+llvmlite-0.3.0-py34_18
# update specs: ['llvmlite', 'python 3.4*']
==> 2015-03-19 17:00:58 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install -c numba llvmlite
-llvmlite-0.3.0-py34_18
-tk-8.5.15-0
+llvmlite-0.3.0-py34_24
+tk-8.5.18-0
# install specs: ['llvmlite', 'python 3.4*']
==> 2015-03-19 17:01:29 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install llvmlite=0.2
-llvmlite-0.3.0-py34_24
+llvmlite-0.2.2-py34_3
# install specs: ['llvmlite 0.2*', 'python 3.4*']
==> 2015-03-20 11:11:17 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install sphinx
-setuptools-14.0-py34_0
+docutils-0.12-py34_0
+pygments-2.0.2-py34_0
+setuptools-14.3-py34_0
+sphinx-1.2.3-py34_0
# install specs: ['sphinx', 'python 3.4*']
==> 2015-03-20 11:11:56 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install pip
+pip-6.0.8-py34_0
# install specs: ['pip', 'python 3.4*']
==> 2015-03-25 09:00:16 <==
# cmd: /home/gmarkall/.conda/envs/py34np19/bin/conda install -c asmeurer pudb
-sqlite-3.8.4.1-0
+pudb-2013.5.1-py34_0
+sqlite-3.8.4.1-1
+urwid-1.2.0-py34_0
# install specs: ['pudb', 'python 3.4*']
```

**Comment by kalefranz** [comment]
Outdated. Closing.
