### ISSUE TITLE
Can't use Conda-command aside of activate/deactivate environment

### ISSUE THREAD

**Issue by Jballbe** [conda/conda#12790]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to use Spyder directly from Anaconda. Before that I want to create a new environment with specific python version, but every Conda-Command I try results in an error (even Conda info, Conda list, and Conda config) 
The only commands that do not return an error are Conda activate and Conda deactivate.

### Conda Info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 70, in main_subshell
        p = generate_parser()
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
        p = ArgumentParser(
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/base/context.py", line 502, in plugin_manager
        from ..plugins.manager import get_plugin_manager
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/manager.py", line 15, in <module>
        from . import solvers, subcommands, virtual_packages
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
        from . import archspec, cuda, linux, osx, windows
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
        import ctypes
      File "/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
      Referenced from: <050DADB0-05A7-32B8-B6A1-16840860B5E5> /opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
      Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file, not in dyld cache)

`$ /opt/anaconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda Config

```shell
(AllenSDK) julienballbe@pclnrs202 ~ % conda config --show-sources

KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 70, in main_subshell
    p = generate_parser()
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
    p = ArgumentParser(
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/base/context.py", line 502, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/manager.py", line 15, in <module>
    from . import solvers, subcommands, virtual_packages
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
    from . import archspec, cuda, linux, osx, windows
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
    import ctypes
  File "/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: <050DADB0-05A7-32B8-B6A1-16840860B5E5> /opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
  Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 165, in print_unexpected_error_report
    get_main_info_str(error_report["conda_info"])
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_info.py", line 250, in get_main_info_str
    info_dict["_" + key] = ("\n" + 26 * " ").join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 70, in main_subshell
        p = generate_parser()
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
        p = ArgumentParser(
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/base/context.py", line 502, in plugin_manager
        from ..plugins.manager import get_plugin_manager
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/manager.py", line 15, in <module>
        from . import solvers, subcommands, virtual_packages
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
        from . import archspec, cuda, linux, osx, windows
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
        import ctypes
      File "/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
      Referenced from: <050DADB0-05A7-32B8-B6A1-16840860B5E5> /opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
      Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file, not in dyld cache)

`$ /opt/anaconda3/bin/conda config --show-sources`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda list

```shell
(AllenSDK) julienballbe@pclnrs202 ~ % conda list --show-channel-urls
KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 70, in main_subshell
    p = generate_parser()
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
    p = ArgumentParser(
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/base/context.py", line 502, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/manager.py", line 15, in <module>
    from . import solvers, subcommands, virtual_packages
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
    from . import archspec, cuda, linux, osx, windows
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
    import ctypes
  File "/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
  Referenced from: <050DADB0-05A7-32B8-B6A1-16840860B5E5> /opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
  Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 165, in print_unexpected_error_report
    get_main_info_str(error_report["conda_info"])
  File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main_info.py", line 250, in get_main_info_str
    info_dict["_" + key] = ("\n" + 26 * " ").join(info_dict[key])
KeyError: 'pkgs_dirs'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/main.py", line 70, in main_subshell
        p = generate_parser()
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
        p = ArgumentParser(
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
        self._subcommands = context.plugin_manager.get_hook_results("subcommands")
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/base/context.py", line 502, in plugin_manager
        from ..plugins.manager import get_plugin_manager
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/manager.py", line 15, in <module>
        from . import solvers, subcommands, virtual_packages
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/__init__.py", line 5, in <module>
        from . import archspec, cuda, linux, osx, windows
      File "/opt/anaconda3/lib/python3.9/site-packages/conda/plugins/virtual_packages/cuda.py", line 3, in <module>
        import ctypes
      File "/opt/anaconda3/lib/python3.9/ctypes/__init__.py", line 8, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libffi.7.dylib
      Referenced from: <050DADB0-05A7-32B8-B6A1-16840860B5E5> /opt/anaconda3/lib/python3.9/lib-dynload/_ctypes.cpython-39-darwin.so
      Reason: tried: '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/python3.9/lib-dynload/../../libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/anaconda3/lib/libffi.7.dylib' (no such file), '/opt/anaconda3/bin/../lib/libffi.7.dylib' (no such file), '/usr/local/lib/libffi.7.dylib' (no such file), '/usr/lib/libffi.7.dylib' (no such file, not in dyld cache)

`$ /opt/anaconda3/bin/conda list --show-channel-urls`

  environment variables:
conda info could not be constructed.
KeyError('pkgs_dirs')

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Additional Context

I am running on MacOS Ventura 13.4, with Apple M1 Max.

In one of my environment in which I can access Spyder, I can't install package using Conda , but I can using pip (I don't know if this information is worth it).

I wanted to uninstall anaconda to start over from zero, but I can't install anaconda-clean, as the Conda install command return similar error message as above.

Let me know if I can give you more information to help me solve this problem, and thank you for all the help you can give me.
Best feelings , 
Julien

**Comment by jaimergp** [comment]
It looks like something went wrong in the base environment when installing something else. The good news is that this is coming from the code that handles the CUDA detection logic, so you can bypass that by exporting `CONDA_OVERRIDE_CUDA=11` (or any other number) and maybe it works?

To be clear, try this:

```
$ CONDA_OVERRIDE_CUDA=11 conda list -n base
```
