### ISSUE TITLE
Cannot use conda with new `pluggy` 1.1.0

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#12808]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

`conda` won't find plugins with `pluggy 1.1.0`.

```
${CONDA_PREFIX}/bin/conda create -n something --dry-run python --solver=libmamba
KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/Users/jrodriguez/.local/anaconda/envs/constructor-dev/lib/python3.10/site-packages/conda/exception_handler.py", line 16, in __call__
    return func(*args, **kwargs)
  File "/Users/jrodriguez/.local/anaconda/envs/constructor-dev/lib/python3.10/site-packages/conda/cli/main.py", line 70, in main_subshell
    p = generate_parser()
  File "/Users/jrodriguez/.local/anaconda/envs/constructor-dev/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 65, in generate_parser
    p = ArgumentParser(
  File "/Users/jrodriguez/.local/anaconda/envs/constructor-dev/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 152, in __init__
    self._subcommands = context.plugin_manager.get_hook_results("subcommands")
  File "/Users/jrodriguez/.local/anaconda/envs/constructor-dev/lib/python3.10/site-packages/conda/plugins/manager.py", line 104, in get_hook_results
    (item for items in hook() for item in items),
TypeError: 'NoneType' object is not iterable
```

### Conda Info

```shell
active environment : base
    active env location : /Users/jrodriguez/.local/anaconda
            shell level : 1
       user config file : /Users/jrodriguez/.condarc
 populated config files : /Users/jrodriguez/.local/anaconda/.condarc
                          /Users/jrodriguez/.condarc
          conda version : 23.5.0
    conda-build version : 3.25.0
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=arm64
                          __osx=13.3=0
                          __unix=0=0
       base environment : /Users/jrodriguez/.local/anaconda  (writable)
      conda av data dir : /Users/jrodriguez/.local/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/jrodriguez/.local/anaconda/pkgs
                          /Users/jrodriguez/.conda/pkgs
       envs directories : /Users/jrodriguez/.local/anaconda/envs
                          /Users/jrodriguez/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.5.0 requests/2.28.2 CPython/3.9.16 Darwin/22.4.0 OSX/13.3 solver/libmamba conda-libmamba-solver/23.5.0 libmambapy/1.4.1
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
conda config --show-sources
==> /Users/jrodriguez/.local/anaconda/.condarc <==
channels:
  - conda-forge

==> /Users/jrodriguez/.condarc <==
add_pip_as_python_dependency: False
auto_update_conda: False
local_repodata_ttl: 0
channel_priority: strict
channels:
  - conda-forge
show_channel_urls: True
experimental:
  - jlap
solver: libmamba
```

### Conda list

```shell
# Name                    Version                   Build  Channel
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h1a8c8d9_8    conda-forge
brotli-bin                1.0.9                h1a8c8d9_8    conda-forge
bzip2                     1.0.8                h3422bc3_4    conda-forge
c-ares                    1.19.1               hb547adb_0    conda-forge
ca-certificates           2023.5.7             hf0a4a13_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311hae827db_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.5.1.dev44             pypi_0    pypi
conda-libmamba-solver     23.5.0             pyhd8ed1ab_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.8.0              pyhd8ed1ab_0    conda-forge
cryptography              41.0.1          py311h5fb2c35_0    conda-forge
fmt                       9.1.0                hffc8910_0    conda-forge
icu                       72.1                 he12128b_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
krb5                      1.20.1               h69eda48_0    conda-forge
libarchive                3.6.2                h82b9b87_1    conda-forge
libbrotlicommon           1.0.9                h1a8c8d9_8    conda-forge
libbrotlidec              1.0.9                h1a8c8d9_8    conda-forge
libbrotlienc              1.0.9                h1a8c8d9_8    conda-forge
libcurl                   8.1.2                h912dcd9_0    conda-forge
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libiconv                  1.17                 he4db4b2_0    conda-forge
libmamba                  1.4.4                h4fa9c85_1    conda-forge
libmambapy                1.4.4           py311hb2b351d_1    conda-forge
libnghttp2                1.52.0               hae82a92_0    conda-forge
libsolv                   0.7.24               hb5ab8b9_0    conda-forge
libsqlite                 3.42.0               hb31c410_0    conda-forge
libssh2                   1.11.0               h7a5bd25_0    conda-forge
libxml2                   2.11.4               he3bdae6_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
lz4-c                     1.9.4                hb7217d7_0    conda-forge
lzo                       2.10              h642e427_1000    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.1                h53f4e23_1    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pluggy                    1.1.0              pyhd8ed1ab_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py311he2be06e_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.4          h47c9636_0_cpython    conda-forge
python_abi                3.11                    3_cp311    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
reproc                    14.2.4               h1a8c8d9_0    conda-forge
reproc-cpp                14.2.4               hb7217d7_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.32         py311heffc1b2_0    conda-forge
ruamel.yaml.clib          0.2.7           py311he2be06e_1    conda-forge
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.12               he1e0b03_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.0.3              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge
yaml-cpp                  0.7.0                hb7217d7_2    conda-forge
zstandard                 0.19.0          py311hdcbfb07_1    conda-forge
zstd                      1.5.2                hf913c23_6    conda-forge
```

**Comment by kenodegard** [comment]
`pluggy 1.1.0` is being being yanked: https://github.com/pytest-dev/pluggy/issues/403#issuecomment-1597437906

**Comment by jezdez** [comment]
I've left some notes in https://github.com/pytest-dev/pluggy/issues/403#issuecomment-1597477962 and reached out to Bruno on Gitter to coordinate collaboration and testing on the feature in the future
