### ISSUE TITLE
Miniconda KeyError: 'path' when trying to activate environment

### ISSUE THREAD

**Issue by DavidRL77** [conda/conda#12809]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This first happened when I was trying to install the ooba-booga-text-generation-webui. Then I tried installing miniconda separately to see if it worked, and when trying to activate my test environment, it gave me the same error as before:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "F:\Users\david\miniconda3\lib\site-packages\conda\exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
      File "F:\Users\david\miniconda3\lib\site-packages\conda\cli\main.py", line 111, in main_sourced
        print(activator.execute(), end="")
      File "F:\Users\david\miniconda3\lib\site-packages\conda\activate.py", line 189, in execute
        return getattr(self, self.command)()
      File "F:\Users\david\miniconda3\lib\site-packages\conda\activate.py", line 155, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "F:\Users\david\miniconda3\lib\site-packages\conda\activate.py", line 333, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "F:\Users\david\miniconda3\lib\site-packages\conda\activate.py", line 362, in _build_activate_stack
        conda_prompt_modifier = self._prompt_modifier(prefix, conda_default_env)
      File "F:\Users\david\miniconda3\lib\site-packages\conda\activate.py", line 724, in _prompt_modifier
        return context.env_prompt.format(
    KeyError: 'path'
`$ F:\Users\david\miniconda3\Scripts\conda-script.py shell.cmd.exe activate test`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=F:\Users\david\miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="F:\Users\david\miniconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=F:\Users\david\miniconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\david
               LD_PRELOAD=<not set>
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.8\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v11.8\libnvvp;C:\Program Files\Eclipse
                          Adoptium\jdk-8.0.345.1-hotspot\bin;C:\Program
                          Files\PlasticSCM5\server;C:\Program Files\PlasticSCM5\client;C:\Window
                          s\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\Win
                          dowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program
                          Files\dotnet\;F:\Program Files\Java\jdk-17\bin;C:\Program Files
                          (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA
                          Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files
                          (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\eSpeak\command_line;
                          C:\Users\david\AppData\Local\Programs\Python\Python310\Scripts;C:\Prog
                          ram Files\nodejs\;C:\Users\david\zlib123dllx64\dll_x64;C:\Program
                          Files\NVIDIA Corporation\Nsight Compute
                          2022.3.0\;C:\ffmpeg\bin;F:\Program Files\AutoFirma\AutoFirma;F:\Users\
                          david\miniconda3;F:\Users\david\miniconda3\Library\mingw-
                          w64\bin;F:\Users\david\miniconda3\Library\usr\bin;F:\Users\david\minic
                          onda3\Library\bin;F:\Users\david\miniconda3\Scripts;C:\Users\david\App
                          Data\Local\Programs\Python\Python310\Scripts\;C:\Users\david\AppData\L
                          ocal\Programs\Python\Python310\;C:\Users\david\AppData\Local\Microsoft
                          \WindowsApps;E:\Users\david\AppData\Local\Programs\Microsoft VS Code\b
                          in;C:\Users\david\.dotnet\tools;C:\SqLite3;C:\Users\david\AppData\Roam
                          ing\npm;C:\Users\david\AppData\Local\GitHubDesktop\bin;F:\Users\david\
                          miniconda3\lib\site-packages\conda\
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=F:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\david\.condarc
 populated config files : C:\Users\david\.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : F:\Users\david\miniconda3  (writable)
      conda av data dir : F:\Users\david\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : F:\Users\david\miniconda3\pkgs
                          C:\Users\david\.conda\pkgs
                          C:\Users\david\AppData\Local\conda\conda\pkgs
       envs directories : F:\Users\david\miniconda3\envs
                          C:\Users\david\.conda\envs
                          C:\Users\david\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.10.11 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

The configuration file looks like this:
```
channels:
  - defaults
env_prompt: "'({name})\\n{path}'"
```

The environments.txt:
```
F:\Users\david\miniconda3
F:\Users\david\miniconda3\envs\test
```

### Conda Info

```shell
active environment : None
       user config file : C:\Users\david\.condarc
 populated config files : C:\Users\david\.condarc
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.10.11.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.2=0
                          __win=0=0
       base environment : F:\Users\david\miniconda3  (writable)
      conda av data dir : F:\Users\david\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : F:\Users\david\miniconda3\pkgs
                          C:\Users\david\.conda\pkgs
                          C:\Users\david\AppData\Local\conda\conda\pkgs
       envs directories : F:\Users\david\miniconda3\envs
                          C:\Users\david\.conda\envs
                          C:\Users\david\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.5.0 requests/2.29.0 CPython/3.10.11 Windows/10 Windows/10.0.19045
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\david\.condarc <==
env_prompt: '({name})\n{path}'
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at F:\Users\david\miniconda3:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0          py310haa95532_0    defaults
brotlipy                  0.7.0           py310h2bbff1b_1002    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2023.05.30           haa95532_0    defaults
certifi                   2023.5.7        py310haa95532_0    defaults
cffi                      1.15.1          py310h2bbff1b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
colorama                  0.4.6           py310haa95532_0    defaults
conda                     23.5.0          py310haa95532_0    defaults
conda-content-trust       0.1.3           py310haa95532_0    defaults
conda-package-handling    2.1.0           py310haa95532_0    defaults
conda-package-streaming   0.8.0           py310haa95532_0    defaults
console_shortcut_miniconda 0.1.1                haa95532_1    defaults
cryptography              39.0.1          py310h21b164f_2    defaults
idna                      3.4             py310haa95532_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
libffi                    3.4.4                hd77b12b_0    defaults
menuinst                  1.4.19          py310h59b6b97_0    defaults
openssl                   3.0.8                h2bbff1b_0    defaults
packaging                 23.0            py310haa95532_0    defaults
pip                       23.0.1          py310haa95532_0    defaults
pluggy                    1.0.0           py310haa95532_1    defaults
powershell_shortcut_miniconda 0.0.1                haa95532_1    defaults
pycosat                   0.6.4           py310h2bbff1b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py310haa95532_0    defaults
pysocks                   1.7.1           py310haa95532_0    defaults
python                    3.10.11              he1021f5_3    defaults
requests                  2.29.0          py310haa95532_0    defaults
ruamel.yaml               0.17.21         py310h2bbff1b_0    defaults
ruamel.yaml.clib          0.2.6           py310h2bbff1b_1    defaults
setuptools                65.6.3          py310haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h2bbff1b_0    defaults
tk                        8.6.12               h2bbff1b_0    defaults
toolz                     0.12.0          py310haa95532_0    defaults
tqdm                      4.65.0          py310h9909e9c_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py310haa95532_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.38.4          py310haa95532_0    defaults
win_inet_pton             1.1.0           py310haa95532_0    defaults
wincertstore              0.2             py310haa95532_2    defaults
xz                        5.4.2                h8cc25b3_0    defaults
zlib                      1.2.13               h8cc25b3_0    defaults
zstandard                 0.19.0          py310h2bbff1b_0    defaults
```

**Comment by travishathaway** [comment]
Hi @DavidRL77,

Thanks for filing this issue. This is happening because of the value in your `env_prompt` variable (`"'({name})\\n{path}'"
`). The variable you use in it, `path`, is not available to conda.

Is there a reason why you are including `path` there like that?

**Comment by DavidRL77** [comment]
Huh, that's interesting I hadn't changed that file, so i thought it was like that by default. Something else must've changed it, or maybe I need to get my memory checked. Thanks so much for taking the time to respond! It works great now!
