### ISSUE TITLE
conda list subprocess.CalledProcessError (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by karenaliang** [conda/conda#12818]
### Checklist

- [X] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I was installing packages into a conda environment, but when I went to check conda list for what had been installed I received the following error.

```
# packages in environment at /home2/s208205/.conda/envs/ISS:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home2/s208205/.conda/envs/ISS/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main_list.py", line 254, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/home2/s208205/.conda/envs/ISS/bin/python', '/home2/s208205/.conda/envs/ISS/bin/pip', '-V']' returned non-zero exit status -11

```

### Conda Info

```shell
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /cm/shared/apps/python/3.4.x-anaconda  (read only)
  default environment : /home2/s208205/.conda/envs/ISS
     envs directories : /home2/s208205/.conda/envs
                        /home2/s208205/envs
                        /cm/shared/apps/python/3.4.x-anaconda/envs
        package cache : /home2/s208205/.conda/envs/.pkgs
                        /home2/s208205/envs/.pkgs
                        /cm/shared/apps/python/3.4.x-anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

### Conda Config

```shell
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required
```

### Conda list

```shell
# packages in environment at /home2/s208205/.conda/envs/ISS:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home2/s208205/.conda/envs/ISS/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main_list.py", line 254, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/cm/shared/apps/python/3.4.x-anaconda/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/home2/s208205/.conda/envs/ISS/bin/python', '/home2/s208205/.conda/envs/ISS/bin/pip', '-V']' returned non-zero exit status -11
```

### Additional Context

I did also find that upon running some other code like trying to run a .py file (python generate_index.py) I received another error: `Segmentation fault (core dumped)`, not sure if that is related in any way.

**Comment by travishathaway** [comment]
Hi @karenaliang,

Thanks for filing this issue. It appears you are using a currently unsupported version of Python and conda. Before you do anything else I would recommend updating these two as soon as possible.

The best way to do this would be starting with a fresh install rather than trying to update what you have. Please visit this page to retrieve the latest installers:

- https://docs.conda.io/en/latest/miniconda.html

Let us know if you need any more assistance.

**Comment by karenaliang** [comment]
Hi @travishathaway,

Thank you, I was able to run `conda list` after updating, but when attempting to run a .py file in the conda environment, I am receiving the same `Segmentation fault (core dumped)` error. I'm not sure what is causing this, as I was able to run it before.

**Comment by travishathaway** [comment]
Hi @karenaliang,

Which version of Python do you currently have? The original version listed in your issue was quite old and is currently unsupported. I would recommend upgrading to at least Python 3.8.
