### ISSUE TITLE
Anaconda update issue

### ISSUE THREAD

**Issue by vladivanov00** [conda/conda#1282]
An unexpected error has occurred, please consider sending the#################################################################                                                |  68%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/vlad/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 141, in execute_instructions
    cmd(state, arg)
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 55, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/home/vlad/anaconda/lib/python2.7/site-packages/conda/install.py", line 448, in extract
    t.extractall(path=path)
  File "/home/vlad/anaconda/lib/python2.7/tarfile.py", line 2070, in extractall
    self.extract(tarinfo, path)
  File "/home/vlad/anaconda/lib/python2.7/tarfile.py", line 2107, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "/home/vlad/anaconda/lib/python2.7/tarfile.py", line 2183, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/vlad/anaconda/lib/python2.7/tarfile.py", line 2223, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 122] Disk quota exceeded: u'/home/vlad/anaconda/pkgs/xlsxwriter-0.6.7-py27_0/lib/python2.7/site-packages/xlsxwriter/chartsheet.py'

Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : 1.2.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/vlad/anaconda  (read only)
  default environment : /home/vlad/anaconda
     envs directories : /home/vlad/.conda/envs
                        /home/vlad/envs
                        /home/vlad/anaconda/envs
        package cache : /home/vlad/.conda/envs/.pkgs
                        /home/vlad/envs/.pkgs
                        /home/vlad/anaconda/pkgs
         channel URLs : https://conda.binstar.org/r/linux-64/
                        https://conda.binstar.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/vlad/.condarc
    is foreign system : False

**Comment by ccordoba12** [comment]
It seems you don't have more hard disk space to install things. Try to remove the packages in

    ~/anaconda/pkgs

to get more space. Or you can also see

    conda clean --help
