### ISSUE TITLE
problem updating anaconda

### ISSUE THREAD

**Issue by daviddou82** [conda/conda#1288]
I had encountered an error while updating anaconda.  My internet connection was interrupted and I had to interrupt the update.  

Traceback (most recent call last):
  File "/home/david/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 141, in execute_instructions
    cmd(state, arg)
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 55, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/home/david/anaconda/lib/python2.7/site-packages/conda/install.py", line 447, in extract
    t = tarfile.open(path + '.tar.bz2')
  File "/home/david/anaconda/lib/python2.7/tarfile.py", line 1671, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

             platform : linux-64
        conda version : 3.10.1
  conda-build version : 1.3.5
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/david/anaconda  (writable)
  default environment : /home/david/anaconda
     envs directories : /home/david/anaconda/envs
        package cache : /home/david/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
@daviddou82 is this still an issue for you?

**Comment by daviddou82** [comment]
No.  this was an issue opened such a long time ago I forgot to close it.
