### ISSUE TITLE
Iris Python Library install fail using Conda

### ISSUE THREAD

**Issue by safaripenguin** [conda/conda#1289]
Tried to install the Iris Python library using 

conda install -c scitools iris

Info on current conda install is:
             platform : osx-64
        conda version : 3.10.1
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

It started to unlink packages then crashed with the following Traceback
Traceback (most recent call last):

  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 598, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '//anaconda/conda-meta/conda-3.10.0-py27_0.json'

Any help appreciated.

**Comment by soapy1** [comment]
Can't reproduce on newest version of conda
