### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by nisarg-hitech** [conda/conda#12902]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda [issue tracker](https://github.com/continuumio/anaconda-issues)

Main Error
('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)
Traceback
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 72, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 66, in run_app
    window = MainWindow(splash=splash)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window\__init__.py", line 235, in __init__
    self.api = AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1442, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 80, in __init__
    self._client_api = ClientAPI(config=self.config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 650, in ClientAPI
    CLIENT_API = _ClientAPI(config=config)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 94, in __init__
    self.reload_client()
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 325, in reload_client
    client.user()
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 242, in user
    self._check_response(res)
  File "C:\ProgramData\Anaconda3\lib\site-packages\binstar_client\__init__.py", line 227, in _check_response
    raise ErrCls(msg, res.status_code)
binstar_client.errors.BinstarError: ('Forbidden: Request forbidden -- authorization will not help ([GET] https://api.anaconda.org/user -> 403)', 403)

### Conda Info

```shell
active environment : Pyinstaller_36
    active env location : C:\ProgramData\Anaconda3\envs\Pyinstaller_36
            shell level : 1
       user config file : C:\Users\nisarg.mehta\.condarc
 populated config files : C:\Users\nisarg.mehta\.condarc
          conda version : 4.11.0
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda3  (writable)
      conda av data dir : C:\ProgramData\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\nisarg.mehta\.conda\pkgs
                          C:\Users\nisarg.mehta\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\nisarg.mehta\.conda\envs
                          C:\Users\nisarg.mehta\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.11.0 requests/2.26.0 CPython/3.8.8 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
C:\Users\nisarg.mehta\.condarc <==
channels:
  - defaults
```

### Conda list

```shell
# packages in environment at C:\ProgramData\Anaconda3\envs\Pyinstaller_36:
#
# Name                    Version                   Build  Channel
absl-py                   0.15.0                   pypi_0    pypi
altgraph                  0.17.2                   pypi_0    pypi
argon2-cffi               20.1.0           py36h2bbff1b_1    defaults
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10             py36h28b3542_0    defaults
attrs                     21.4.0             pyhd3eb1b0_0    defaults
backcall                  0.2.0              pyhd3eb1b0_0    defaults
bleach                    4.1.0              pyhd3eb1b0_0    defaults
boto3                     1.23.10                  pypi_0    pypi
botocore                  1.26.10                  pypi_0    pypi
botorch                   0.2.1                    pypi_0    pypi
cached-property           1.5.2                    pypi_0    pypi
cachetools                4.2.4                    pypi_0    pypi
certifi                   2021.5.30        py36haa95532_0    defaults
cffi                      1.14.6           py36h2bbff1b_0    defaults
charset-normalizer        2.0.12                   pypi_0    pypi
clang                     5.0                      pypi_0    pypi
click                     8.0.4                    pypi_0    pypi
cmdstanpy                 0.9.68                   pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0    defaults
console_shortcut          0.1.1                         4    defaults
convertdate               2.3.2                    pypi_0    pypi
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.33                  pypi_0    pypi
dataclasses               0.8                      pypi_0    pypi
datetime                  4.4                      pypi_0    pypi
decorator                 5.1.1              pyhd3eb1b0_0    defaults
defusedxml                0.7.1              pyhd3eb1b0_0    defaults
entrypoints               0.3                      py36_0    defaults
ephem                     4.1.4                    pypi_0    pypi
et-xmlfile                1.1.0                    pypi_0    pypi
filelock                  3.4.1                    pypi_0    pypi
flatbuffers               1.12                     pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
gast                      0.4.0                    pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-oauthlib      0.4.6                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
gpytorch                  1.6.0                    pypi_0    pypi
greenlet                  1.1.2                    pypi_0    pypi
grpcio                    1.47.0                   pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
hijri-converter           2.2.4                    pypi_0    pypi
holidays                  0.13                     pypi_0    pypi
idna                      3.3                      pypi_0    pypi
importlib-metadata        4.8.3                    pypi_0    pypi
importlib-resources       5.4.0                    pypi_0    pypi
ipykernel                 5.3.4            py36h5ca1d4c_0    defaults
ipython                   7.16.1           py36h5ca1d4c_0    defaults
ipython_genutils          0.2.0              pyhd3eb1b0_1    defaults
jedi                      0.17.0                   py36_0    defaults
jinja2                    3.0.3              pyhd3eb1b0_0    defaults
jmespath                  0.10.0                   pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jsonschema                3.0.2                    py36_0    defaults
jupyter_client            7.1.2              pyhd3eb1b0_0    defaults
jupyter_core              4.8.1            py36haa95532_0    defaults
jupyterlab_pygments       0.1.2                      py_0    defaults
keras                     2.6.0                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
korean-lunar-calendar     0.3.1                    pypi_0    pypi
llvmlite                  0.36.0                   pypi_0    pypi
lunarcalendar             0.0.9                    pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.3.7                    pypi_0    pypi
markupsafe                2.0.1            py36h2bbff1b_0    defaults
matplotlib                3.3.4                    pypi_0    pypi
mistune                   0.8.4            py36he774522_0    defaults
msys2-conda-epoch         20160418                      1    defaults
mysql-connector-python    8.0.29                   pypi_0    pypi
nbclient                  0.5.3              pyhd3eb1b0_0    defaults
nbconvert                 6.0.7                    py36_0    defaults
nbformat                  5.1.3              pyhd3eb1b0_0    defaults
nest-asyncio              1.5.1              pyhd3eb1b0_0    defaults
nltk                      3.6.7                    pypi_0    pypi
notebook                  6.4.3            py36haa95532_0    defaults
numba                     0.53.1                   pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
oauthlib                  3.2.0                    pypi_0    pypi
openpyxl                  3.0.10                   pypi_0    pypi
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0    defaults
pandas                    1.1.5                    pypi_0    pypi
pandoc                    2.12                 haa95532_0    defaults
pandocfilters             1.5.0              pyhd3eb1b0_0    defaults
parso                     0.8.3              pyhd3eb1b0_0    defaults
patsy                     0.5.3                    pypi_0    pypi
pefile                    2021.9.3                 pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003    defaults
pillow                    8.4.0                    pypi_0    pypi
pip                       21.3.1                   pypi_0    pypi
plotly                    5.11.0                   pypi_0    pypi
prometheus_client         0.13.1             pyhd3eb1b0_0    defaults
prompt-toolkit            3.0.20             pyhd3eb1b0_0    defaults
protobuf                  3.19.4                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0    defaults
pygments                  2.11.2             pyhd3eb1b0_0    defaults
pyinstaller               4.10                     pypi_0    pypi
pyinstaller-hooks-contrib 2022.0                   pypi_0    pypi
pymannkendall             1.4.2                    pypi_0    pypi
pymeeus                   0.5.12                   pypi_0    pypi
pymysql                   1.0.2                    pypi_0    pypi
pyparsing                 3.0.4              pyhd3eb1b0_0    defaults
pyrsistent                0.17.3           py36he774522_0    defaults
pystan                    2.19.1.1                 pypi_0    pypi
python                    3.6.13               h3758d61_0    defaults
python-dateutil           2.8.2              pyhd3eb1b0_0    defaults
pytorch-transformers      1.2.0                    pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pywin32                   304                      pypi_0    pypi
pywin32-ctypes            0.2.0                    pypi_0    pypi
pywinpty                  0.5.7                    py36_0    defaults
pyzmq                     22.2.1           py36hd77b12b_1    defaults
regex                     2022.6.2                 pypi_0    pypi
requests                  2.27.1                   pypi_0    pypi
requests-oauthlib         1.3.1                    pypi_0    pypi
rsa                       4.8                      pypi_0    pypi
s3transfer                0.5.2                    pypi_0    pypi
sacremoses                0.0.53                   pypi_0    pypi
scikit-learn              0.24.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
seaborn                   0.11.2                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1    defaults
sentencepiece             0.1.96                   pypi_0    pypi
setuptools                59.6.0                   pypi_0    pypi
setuptools-git            1.2                      pypi_0    pypi
six                       1.15.0                   pypi_0    pypi
sklearn                   0.0                      pypi_0    pypi
sqlalchemy                1.4.39                   pypi_0    pypi
sqlite                    3.38.3               h2bbff1b_0    defaults
statsmodels               0.12.2                   pypi_0    pypi
tenacity                  8.1.0                    pypi_0    pypi
tensorboard               2.6.0                    pypi_0    pypi
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.8.1                    pypi_0    pypi
tensorflow                2.6.2                    pypi_0    pypi
tensorflow-estimator      2.6.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.4            py36haa95532_0    defaults
testpath                  0.5.0              pyhd3eb1b0_0    defaults
threadpoolctl             3.1.0                    pypi_0    pypi
tokenizers                0.0.11                   pypi_0    pypi
torch                     1.10.2                   pypi_0    pypi
tornado                   6.1              py36h2bbff1b_0    defaults
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 4.3.3            py36haa95532_0    defaults
transformers              2.4.1                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
ujson                     4.3.0                    pypi_0    pypi
urllib3                   1.26.9                   pypi_0    pypi
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wcwidth                   0.2.5              pyhd3eb1b0_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  2.0.3                    pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.12.1                   pypi_0    pypi
xlrd                      1.2.0                    pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zope-interface            5.4.0                    pypi_0    pypi
```

**Comment by travishathaway** [comment]
Hi @nisarg-hitech,

Thanks for filing this issue. Unfortunately, this is not the correct location for it. Please create a new issue in the following project on GitHub: https://github.com/ContinuumIO/anaconda-issues/issues
