### ISSUE TITLE
Subcommand arguments are incorrectly parsed

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#12906]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Install `conda-canary/label/rc-conda-23.7.x::conda` and `conda-canary/label/rc-conda-build-3.26.x::conda-build` and run `conda build --help` versus `conda-build --help`:

<details>
<summary><code>conda build --help</code></summary>

```
$ conda build --help
usage: conda build [-h]

Build conda packages from a conda recipe.

options:
  -h, --help  Show this help message and exit.
```

```
$ conda-build --help
usage: conda build [-h] [-V] [-n] [--output] [--python PYTHON] [--perl PERL] [--numpy NUMPY] [--R R_BASE] [--lua LUA] [--bootstrap BOOTSTRAP]
                   [--append-file APPEND_SECTIONS_FILE] [--clobber-file CLOBBER_SECTIONS_FILE] [-m VARIANT_CONFIG_FILES] [-e EXCLUSIVE_CONFIG_FILES] [--old-build-string]
                   [--use-channeldata] [--variants VARIANTS] [--check] [--no-anaconda-upload] [--no-include-recipe] [-s] [-t] [--no-test] [-b] [--post] [-p]
                   [--skip-existing] [--keep-old-work] [--dirty] [-q] [--debug] [--token TOKEN] [--user USER] [--label LABELS] [--no-force-upload]
                   [--zstd-compression-level {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22}] [--password PASSWORD] [--sign SIGN] [--sign-with SIGN_WITH]
                   [--identity IDENTITY] [--config-file CONFIG_FILE] [--repository REPOSITORY] [--no-activate] [--no-build-id] [--build-id-pat BUILD_ID_PAT]
                   [--croot CROOT] [--verify] [--no-verify] [--strict-verify] [--output-folder OUTPUT_FOLDER] [--no-prefix-length-fallback] [--prefix-length-fallback]
                   [--prefix-length _PREFIX_LENGTH] [--no-locking] [--no-remove-work-dir] [--error-overlinking] [--no-error-overlinking] [--error-overdepending]
                   [--no-error-overdepending] [--long-test-prefix] [--no-long-test-prefix] [--keep-going] [--cache-dir CACHE_DIR] [--no-copy-test-source-files]
                   [--merge-build-host] [--stats-file STATS_FILE] [--extra-deps EXTRA_DEPS [EXTRA_DEPS ...]] [--extra-meta [KEY=VALUE ...]] [--suppress-variables]
                   [-c CHANNEL] [--use-local] [--override-channels] [--repodata-fn REPODATA_FNS] [--experimental {jlap,lock}]
                   RECIPE_PATH [RECIPE_PATH ...]

Tool for building conda packages. A conda package is a binary tarball
...
```

</details>

<details>
<summary><code>conda build --output</code></summary>

```
$ conda build --output
usage: conda [-h] [-V] [--no-plugins] COMMAND ...
conda: error: unrecognized arguments: --output
```

```
$ conda-build --output
usage: conda build [-h] [-V] [-n] [--output] [--python PYTHON] [--perl PERL] [--numpy NUMPY] [--R R_BASE] [--lua LUA]
                   [--bootstrap BOOTSTRAP] [--append-file APPEND_SECTIONS_FILE] [--clobber-file CLOBBER_SECTIONS_FILE]
                   [-m VARIANT_CONFIG_FILES] [-e EXCLUSIVE_CONFIG_FILES] [--old-build-string] [--use-channeldata] [--variants VARIANTS]
                   [--check] [--no-anaconda-upload] [--no-include-recipe] [-s] [-t] [--no-test] [-b] [--post] [-p] [--skip-existing]
                   [--keep-old-work] [--dirty] [-q] [--debug] [--token TOKEN] [--user USER] [--label LABELS] [--no-force-upload]
                   [--zstd-compression-level {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22}] [--password PASSWORD]
                   [--sign SIGN] [--sign-with SIGN_WITH] [--identity IDENTITY] [--config-file CONFIG_FILE] [--repository REPOSITORY]
                   [--no-activate] [--no-build-id] [--build-id-pat BUILD_ID_PAT] [--croot CROOT] [--verify] [--no-verify]
                   [--strict-verify] [--output-folder OUTPUT_FOLDER] [--no-prefix-length-fallback] [--prefix-length-fallback]
                   [--prefix-length _PREFIX_LENGTH] [--no-locking] [--no-remove-work-dir] [--error-overlinking] [--no-error-overlinking]
                   [--error-overdepending] [--no-error-overdepending] [--long-test-prefix] [--no-long-test-prefix] [--keep-going]
                   [--cache-dir CACHE_DIR] [--no-copy-test-source-files] [--merge-build-host] [--stats-file STATS_FILE]
                   [--extra-deps EXTRA_DEPS [EXTRA_DEPS ...]] [--extra-meta [KEY=VALUE [KEY=VALUE ...]]] [--suppress-variables]
                   [-c CHANNEL] [--use-local] [--override-channels] [--repodata-fn REPODATA_FNS] [--experimental {jlap,lock}]
                   RECIPE_PATH [RECIPE_PATH ...]
conda build: error: the following arguments are required: RECIPE_PATH
```

</details>

<details>
<summary><code>conda build bla</code></summary>

```
$ conda build bla
ERROR: Glob /Users/kodegard/scratch/args/bla did not match in root_dir /Users/kodegard/scratch/args

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
...
```

```
$ conda-build bla
ERROR: Glob /Users/kodegard/scratch/args/bla did not match in root_dir /Users/kodegard/scratch/args
Traceback (most recent call last):
  File "/Users/kodegard/.conda/devenv/Darwin/arm64/envs/devenv-3.8-c/bin/conda-build", line 8, in <module>
    sys.exit(main())
  File "/Users/kodegard/dev/conda-build/conda_build/deprecations.py", line 70, in inner
    return func(*args, **kwargs)
  File "/Users/kodegard/dev/conda-build/conda_build/cli/main_build.py", line 589, in main
    execute(sys.argv[1:])
  File "/Users/kodegard/dev/conda-build/conda_build/cli/main_build.py", line 568, in execute
    outputs = api.build(
  File "/Users/kodegard/dev/conda-build/conda_build/api.py", line 249, in build
    raise ValueError(
ValueError: No valid recipes found for input: ['bla']
```

</details>

**Comment by kenodegard** [comment]
After some tinkering we found that this is an issue with `argparse` itself (dating all the way back to Python 2.7), see the following `demo.py`:

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument(
    "plugin_args",
    nargs=argparse.REMAINDER,  # everything remaining, after the subcommand name
    help=argparse.SUPPRESS,  # to hide it from the help output
)

for args in (
    ["foo"],
    ["foo", "--bar"],
    ["--bar"],
    ["--bar", "foo"],
    ["-", "--bar"],
    ["-", "--bar", "foo"],
    ["--", "--bar"],
    ["--", "--bar", "foo"],
):
    namespace, unknown = parser.parse_known_args(args)

    if namespace == argparse.Namespace(plugin_args=args) and not unknown:
        print(f"success: {args}")
    else:
        print(f"error:   {args}")
```

```bash
$ python demo.py
success: ['foo']
success: ['foo', '--bar']
error:   ['--bar']
error:   ['--bar', 'foo']
success: ['-', '--bar']
success: ['-', '--bar', 'foo']
success: ['--', '--bar']
success: ['--', '--bar', 'foo']
```

**Comment by kenodegard** [comment]
This is a known issue per https://github.com/python/cpython/issues/61252. The feature has been undocumented (to discourage use) since 2020 because there is no known easy fix.

**Comment by jezdez** [comment]
we can salvage this with the [workaround mentioned here](https://github.com/python/cpython/issues/61252#issuecomment-1093606584):

> Note that this means we can fix the bug simply by, whenever the cmdname subparser is invoked and the cmdname subparser uses argparse.REMAINDER, automatically adding an imaginary first positional argument to the subparser and inserting that imaginary first positional argument into the stream before parsing the arguments to cmdname. https://github.com/python/cpython/blob/master/Lib/argparse.py#L1201”
