### ISSUE TITLE
Issue while intalling new environment

### ISSUE THREAD

**Issue by Plumax** [conda/conda#1291]
While create new environment: conda create -n py27 python=2.7 anaconda

Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 3.4.3.final.0
     requests version : 2.6.0
     root environment : /home/pgreillier/anaconda3  (read only)
  default environment : /home/pgreillier/anaconda3
     envs directories : /home/pgreillier/.conda/envs
                        /home/pgreillier/envs
                        /home/pgreillier/anaconda3/envs
        package cache : /home/pgreillier/.conda/envs/.pkgs
                        /home/pgreillier/envs/.pkgs
                        /home/pgreillier/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Traceback (most recent call last):
  File "/home/pgreillier/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 55, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/home/pgreillier/anaconda3/lib/python3.4/site-packages/conda/install.py", line 447, in extract
    t = tarfile.open(path + '.tar.bz2')
  File "/home/pgreillier/anaconda3/lib/python3.4/tarfile.py", line 1553, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

**Comment by soapy1** [comment]
Can't reproduce this on newest version of conda
