### ISSUE TITLE
jlap: Improve 416 Requested Range Not Satisfiable error handling

### ISSUE THREAD

**Issue by dholth** [conda/conda#12913]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

From time to time the `.jlap` patch file will be truncated to limit its size, leading to `416` errors when conda tries to fetch a portion of the file that doesn't exist. This error is printed to the console and then conda continues to work normally. (It is designed to fall back to downloading the entire remote `.jlap` file, and if that doesn't work, to fall back to downloading `repodata.json`).

Instead, conda should suppress this error since it is an expected part of `.jlap` handling.

```
ERROR conda.gateways.repodata.jlap.fetch:request_url_jlap_state(374): Requests error
Traceback (most recent call last):
  File "/Users/dholth/prog/conda/conda/gateways/repodata/jlap/fetch.py", line 347, in request_url_jlap_state
    buffer, jlap_state = fetch_jlap(
  File "/Users/dholth/prog/conda/conda/gateways/repodata/jlap/fetch.py", line 107, in fetch_jlap
    response = request_jlap(
  File "/Users/dholth/prog/conda/conda/gateways/repodata/jlap/fetch.py", line 129, in request_jlap
    response.raise_for_status()
  File "/Users/dholth/prog/conda/devenv/Darwin/arm64/envs/devenv-3.10-c/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 416 Client Error: Requested Range Not Satisfiable for url: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.jlap
```

**Comment by dholth** [comment]
Another example

```
Loading channels: \ ERROR conda.gateways.repodata.jlap.fetch:request_url_jlap_state(377): Requests error
Traceback (most recent call last):
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/fetch.py", line 350, in request_url_jlap_state
    buffer, jlap_state = fetch_jlap(
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/fetch.py", line 107, in fetch_jlap
    response = request_jlap(
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/fetch.py", line 129, in request_jlap
    response.raise_for_status()
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 416 Client Error: Requested Range Not Satisfiable for url: https://conda.anaconda.org/conda-forge/osx-arm64/repodata.jlap
| ERROR conda.gateways.repodata.jlap.fetch:request_url_jlap_state(383): Error parsing jlap
Traceback (most recent call last):
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/fetch.py", line 381, in request_url_jlap_state
    buffer, jlap_state = fetch_jlap(withext(url, ".jlap"), session=session)
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/fetch.py", line 110, in fetch_jlap
    return process_jlap_response(response, pos=pos, iv=iv)
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/fetch.py", line 85, in process_jlap_response
    buffer = JLAP.from_lines(lines(), iv, pos)
  File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/jlap/core.py", line 65, in from_lines
    raise ValueError("checksum mismatch")
ValueError: checksum mismatch
done
```

**Comment by dholth** [comment]
Depending on when we catch a rolled-over jlap [(we truncate jlap after 10MB to about 3MB)](https://github.com/dholth/repodata-fly/blob/main/app/jlaptrim.py#L65-L79) the new range might be satisfiable and we will get a jlap checksum error instead. The code appears to give a similar "print traceback / fallback to complete jlap fetch" in that case.  That should also be made quieter.
