### ISSUE TITLE
conda search has problems executing concurrently！

### ISSUE THREAD

**Issue by zhuwqvip** [conda/conda#12920]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I get an error when I run search concurrently

```
[root@gv102 ~]# for i in $(seq 1 20); do conda search &  done
[root@gv102 ~]# conda search
Loading channels: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/anaconda/lib/python3.10/site-packages/conda/exceptions.py", line 1132, in __call__
        return func(*args, **kwargs)
      File "/opt/anaconda/lib/python3.10/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
      File "/opt/anaconda/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 122, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/anaconda/lib/python3.10/site-packages/conda/cli/main_search.py", line 69, in execute
        matches = sorted(SubdirData.query_all(spec, channel_urls, subdirs),
      File "/opt/anaconda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 169, in query_all
        result = tuple(chain.from_iterable(executor.map(subdir_query, channel_urls)))
      File "/opt/anaconda/lib/python3.10/site-packages/conda/common/io.py", line 547, in map
        yield func(thing)
      File "/opt/anaconda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in subdir_query
        return tuple(
      File "/opt/anaconda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 174, in query
        self.load()
      File "/opt/anaconda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 264, in load
        _internal_state = self._load()
      File "/opt/anaconda/lib/python3.10/site-packages/conda/core/subdir_data.py", line 315, in _load
        cache.load_state()  # XXX should this succeed even if FileNotFound?
      File "/opt/anaconda/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 570, in load_state
        self.load(state_only=True)
      File "/opt/anaconda/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 528, in load
        state = json.loads(state_file.read())
      File "/opt/anaconda/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/opt/anaconda/lib/python3.10/json/decoder.py", line 340, in decode
        raise JSONDecodeError("Extra data", s, end)
    json.decoder.JSONDecodeError: Extra data: line 8 column 2 (char 265)
```

When I check the 72a5dfe4.state.json file, I find that the content is duplicated

```
[root@gv102 ~]# cat /opt/anaconda/pkgs/cache/72a5dfe4.state.json
{
  "url": "http://condatest:test;123@10.0.41.142:8082/repository/public_conda_proxy/NFS3.2/noarch",
  "etag": "\"7f-600e6ac369400\"",
  "mod": "Thu, 20 Jul 2023 08:09:52 GMT",
  "mtime_ns": 1690277351974172211,
  "size": 127,
  "refresh_ns": 1690277604320353464
}{
  "url": "http://condatest:test;123@10.0.41.142:8082/repository/public_conda_proxy/NFS3.2/noarch",
  "etag": "\"7f-600e6ac369400\"",
  "mod": "Thu, 20 Jul 2023 08:09:52 GMT",
  "mtime_ns": 1690277351974172211,
  "size": 127,
  "refresh_ns": 1690277604320541585
}
```

### Conda Info

```shell
[root@gv102 ~]# conda info

     active environment : None
            shell level : 0
       user config file : /root/.condarc
 populated config files : /opt/anaconda/.condarc
                          /root/.condarc
          conda version : 23.3.1
    conda-build version : 3.24.0
         python version : 3.10.9.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /opt/anaconda  (writable)
      conda av data dir : /opt/anaconda/etc/conda
  conda av metadata url : None
           channel URLs : http://condatest:test;123@10.0.41.142:8082/repository/public_conda_proxy/NFS3.2/linux-64
                          http://condatest:test;123@10.0.41.142:8082/repository/public_conda_proxy/NFS3.2/noarch
          package cache : /opt/anaconda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.3.1 requests/2.28.1 CPython/3.10.9 Linux/3.10.0-957.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
[root@gv102 ~]# conda config --show-sources
==> /opt/anaconda/.condarc <==
repodata_threads: 1
fetch_threads: 64
remote_connect_timeout_secs: 180.0
remote_read_timeout_secs: 86400.0
remote_max_retries: 5
channels:
  - http://condatest:test;123@10.0.41.142:8082/repository/public_conda_proxy/NFS3.2
show_channel_urls: True
repodata_fns:
  - current_repodata.json
  - repodata.json

==> /root/.condarc <==
report_errors: True
```

### Conda list

```shell
[root@gv102 ~]# conda list --show-channel-urls
# packages in environment at /opt/anaconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
alabaster                 0.7.12             pyhd3eb1b0_0    defaults
anaconda-client           1.11.2          py310h06a4308_0    defaults
anaconda-navigator        2.4.0           py310h06a4308_0    defaults
anaconda-project          0.11.1          py310h06a4308_0    defaults
anyio                     3.5.0           py310h06a4308_0    defaults
appdirs                   1.4.4              pyhd3eb1b0_0    defaults
argon2-cffi               21.3.0             pyhd3eb1b0_0    defaults
argon2-cffi-bindings      21.2.0          py310h7f8727e_0    defaults
```

**Comment by travishathaway** [comment]
Hi @zhuwqvip,

Thanks for filing this issue. I'm glad that you have brought this to our attention. This is just one place that conda does not do well with concurrent operations.

I think this won't likely be fixed soon, so I hope you've found a suitable work around in the meantime.

Anyhow, I think that the `conda search` function should eventually be refactored and knowing this information is useful.

**Comment by dholth** [comment]
We have been adjusting the repodata download code. https://github.com/conda/conda/blob/main/conda/gateways/repodata/__init__.py#L647 is the code that handles locking the state, so that two processes can't write to it concurrently. However we might have bugs in the new locking code. We might write the repodata state an extra time in the conda process as the caller and the jlap code can both try to manage cache state.

Please try to reproduce with conda >= 23.5.

**Comment by dholth** [comment]
I was able to reproduce with latest conda, with jlap disabled. I used a string that won't match to search and get less output: `for i in $(seq 1 20); do conda search xyzzy & done`. I haven't been able to reproduce yet when adding `experimental: [jlap]`, but either way doesn't reproduce the error every time.

**Comment by dholth** [comment]
There is a second option `--experimental=lock` that will enable locking without enabling jlap; or `experimental: [lock]` in `~/.condarc`. jlap enables locking since it is important to avoid cumulative errors when patching repodata.json.

The[ `replace()` and `refresh()`](
https://github.com/conda/conda/blob/main/conda/gateways/repodata/__init__.py#L675-L680
) functions in `conda.gateways.repodata` are where we write to `.info.json`. They do an append/truncate/write dance that is designed to work correctly with locking. We also acquire the lock when reading `.info.json`.

However we didn't enable locking by default. [The lock object is a no-op when jlap or lock are not enabled.](https://github.com/conda/conda/blob/main/conda/gateways/repodata/lock.py#L72-L76)

As far as I can tell, if we use other non-locking strategies we will still get errors during parallel reads/writes. Maybe we would be more likely to read zero bytes than double state in that case.

We should probably enable locking by default in the next release.
