### ISSUE TITLE
Problems with anaconda update

### ISSUE THREAD

**Issue by StephanieM90** [conda/conda#1294]
I have problems installing packages in anaconda, so I deinstalled it and installed it again. Now I cannot update it anymore. It says the following. What can I do?

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 34, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 228, in install
    force=args.force, only_names=only_names)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 242, in install_actions
    config.track_features):
  File "//anaconda/lib/python2.7/site-packages/conda/resolve.py", line 434, in solve
    return self.explicit(specs) or self.solve2(specs, features)
  File "//anaconda/lib/python2.7/site-packages/conda/resolve.py", line 290, in solve2
    solutions = min_sat(clauses)
  File "//anaconda/lib/python2.7/site-packages/conda/resolve.py", line 147, in min_sat
    for sol in islice(pycosat.itersolve(clauses), max_n):
  File "//anaconda/lib/python2.7/site-packages/conda/resolve.py", line 242, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: qt-4.8.6-0.tar.bz2 MatchSpec(u'freetype    >=2.5.2')

conda info

Current conda install:

             platform : osx-64
        conda version : 3.0.6
       python version : 2.7.6.final.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
Try updating your conda (`conda update conda`).
