### ISSUE TITLE
error when "conda activate py37" is done on Windows Git-Bash

### ISSUE THREAD

**Issue by lvbibir** [conda/conda#12968]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following is a screenshot of error reporting
![image](https://github.com/conda/conda/assets/53466270/c3675258-ddeb-4470-b27f-c8dcdbb892ed)

```text
lvbibir@LeiGod-911 MINGW64 ~
$ conda activate py37
Exception in thread Thread-3 (_readerthread):
Traceback (most recent call last):
  File "D:\miniconda\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "D:\miniconda\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "D:\miniconda\Lib\subprocess.py", line 1597, in _readerthread
    buffer.append(fh.read())
                  ^^^^^^^^^
UnicodeDecodeError: 'gbk' codec can't decode byte 0x85 in position 480: illegal multibyte sequence

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\miniconda\Lib\site-packages\conda\exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\cli\main.py", line 111, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\activate.py", line 191, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\activate.py", line 157, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\activate.py", line 335, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\activate.py", line 387, in _build_activate_stack
        path=self.pathsep_join(self._add_prefix_to_path(prefix)),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\activate.py", line 613, in _add_prefix_to_path
        path_list = list(self.path_conversion(self._get_starting_path_list()))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\miniconda\Lib\site-packages\conda\activate.py", line 850, in native_path_to_unix
        ).stdout.strip()
                 ^^^^^
    AttributeError: 'NoneType' object has no attribute 'strip'

`$ D:\miniconda\Scripts\conda-script.py shell.posix activate py37`

  environment variables:
             ACLOCAL_PATH=D:\git\mingw64\share\aclocal;D:\git\usr\share\aclocal
                 CIO_TEST=<not set>
                CLASSPATH=.;%JAVA_HOME%\lib\dt.jar;%JAVA_HOME%\lib\tools.jar;
                CONDA_EXE=D:/miniconda/Scripts/conda.exe
         CONDA_PYTHON_EXE=D:/miniconda/python.exe
               CONDA_ROOT=D:\miniconda
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                  EXEPATH=D:\git
                 HOMEPATH=\Users\lvbibir
                 INFOPATH=D:\git\mingw64\local\info;D:\git\mingw64\share\info;D:\git\usr\local\i
                          nfo;D:\git\usr\share\info;D:\git\usr\info;D:\git\share\info
               LD_PRELOAD=<not set>
                  MANPATH=D:\git\mingw64\local\man;D:\git\mingw64\share\man;D:\git\usr\local\man
                          ;D:\git\usr\share\man;D:\git\usr\man;D:\git\share\man
            ORIGINAL_PATH=D:\git\mingw64\bin;D:\git\usr\bin;C:\Users\lvbibir\bin;C:\windows;C:\w
                          indows\system32;C:\windows\system32\wbem;C:\windows\system32\openssh;C
                          :\windows\system32\windowspowershell\v1.0;C:\program files\nvidia
                          corporation\nvidia nvdlisr;C:\Program Files (x86)\NVIDIA Corporation\P
                          hysX\Common;D:\git\git\cmd;C:\Users\lvbibir\AppData\Local\Microsoft\Wi
                          ndowsApps;D:\hugo;D:\vscode\Microsoft VS Code\bin;D:\1-
                          免安装\MobaXterm\slash\bin;D:\miniconda;D:\miniconda\Scripts;D:\miniconda
                          \Library\bin
                     PATH=D:\miniconda\condabin;C:\Users\lvbibir\bin;D:\git\mingw64\bin;D:\git\u
                          sr\local\bin;D:\git\usr\bin;D:\git\usr\bin;D:\git\mingw64\bin;D:\git\u
                          sr\bin;C:\Users\lvbibir\bin;C:\windows;C:\windows\system32;C:\windows\
                          system32\wbem;C:\windows\system32\openssh;C:\windows\system32\windowsp
                          owershell\v1.0;C:\program files\nvidia corporation\nvidia
                          nvdlisr;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\git\
                          git\cmd;C:\Users\lvbibir\AppData\Local\Microsoft\WindowsApps;D:\hugo;D
                          :\vscode\Microsoft VS Code\bin;D:\1-
                          免安装\MobaXterm\slash\bin;D:\miniconda;D:\miniconda\Scripts;D:\miniconda
                          \Library\bin;D:\git\usr\bin\vendor_perl;D:\git\usr\bin\core_perl
          PKG_CONFIG_PATH=D:\git\mingw64\lib\pkgconfig;D:\git\mingw64\share\pkgconfig
PKG_CONFIG_SYSTEM_INCLUDE_PATH=D:/git/mingw64/include
PKG_CONFIG_SYSTEM_LIBRARY_PATH=D:/git/mingw64/lib
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : C:\Users\lvbibir\.condarc
 populated config files : C:\Users\lvbibir\.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : D:\miniconda  (writable)
      conda av data dir : D:\miniconda\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : D:\miniconda\pkgs
       envs directories : D:\miniconda\envs
                          C:\Users\lvbibir\.conda\envs
                          C:\Users\lvbibir\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.



No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

```

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : C:\Users\lvbibir\.condarc
 populated config files : C:\Users\lvbibir\.condarc
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.1=0
                          __win=0=0
       base environment : D:\miniconda  (writable)
      conda av data dir : D:\miniconda\etc\conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : D:\miniconda\pkgs
       envs directories : D:\miniconda\envs
                          C:\Users\lvbibir\.conda\envs
                          C:\Users\lvbibir\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Windows/10 Windows/10.0.19044
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\lvbibir\.condarc <==
auto_activate_base: False
envs_dirs:
  - D:\miniconda\envs
pkgs_dirs:
  - D:\miniconda\pkgs
channels:
  - defaults
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  deepmodeling: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
show_channel_urls: True
```

### Conda list

```shell
# packages in environment at D:\miniconda:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0          py311haa95532_0    https://repo.anaconda.com/pkgs/main
brotlipy                  0.7.0           py311h2bbff1b_1002    https://repo.anaconda.com/pkgs/main
bzip2                     1.0.8                he774522_0    https://repo.anaconda.com/pkgs/main
ca-certificates           2023.05.30           haa95532_0    https://repo.anaconda.com/pkgs/main
certifi                   2023.5.7        py311haa95532_0    https://repo.anaconda.com/pkgs/main
cffi                      1.15.1          py311h2bbff1b_3    https://repo.anaconda.com/pkgs/main
charset-normalizer        2.0.4              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
colorama                  0.4.6           py311haa95532_0    https://repo.anaconda.com/pkgs/main
conda                     23.5.2          py311haa95532_0    https://repo.anaconda.com/pkgs/main
conda-content-trust       0.1.3           py311haa95532_0    https://repo.anaconda.com/pkgs/main
conda-libmamba-solver     23.5.0          py311haa95532_0    https://repo.anaconda.com/pkgs/main
conda-package-handling    2.1.0           py311haa95532_0    https://repo.anaconda.com/pkgs/main
conda-package-streaming   0.8.0           py311haa95532_0    https://repo.anaconda.com/pkgs/main
console_shortcut_miniconda 0.1.1                haa95532_1    https://repo.anaconda.com/pkgs/main
cryptography              39.0.1          py311h21b164f_2    https://repo.anaconda.com/pkgs/main
fmt                       9.1.0                h6d14046_0    https://repo.anaconda.com/pkgs/main
idna                      3.4             py311haa95532_0    https://repo.anaconda.com/pkgs/main
jsonpatch                 1.32               pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
jsonpointer               2.1                pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
libarchive                3.6.2                hb62f4d4_2    https://repo.anaconda.com/pkgs/main
libcurl                   8.1.1                h86230a5_0    https://repo.anaconda.com/pkgs/main
libffi                    3.4.4                hd77b12b_0    https://repo.anaconda.com/pkgs/main
libiconv                  1.16                 h2bbff1b_2    https://repo.anaconda.com/pkgs/main
libmamba                  1.4.1                h77c03ed_1    https://repo.anaconda.com/pkgs/main
libmambapy                1.4.1           py311h77c03ed_1    https://repo.anaconda.com/pkgs/main
libsolv                   0.7.22               h23ce68f_0    https://repo.anaconda.com/pkgs/main
libssh2                   1.10.0               he2ea4bf_2    https://repo.anaconda.com/pkgs/main
libxml2                   2.10.3               h0ad7f3c_0    https://repo.anaconda.com/pkgs/main
lz4-c                     1.9.4                h2bbff1b_0    https://repo.anaconda.com/pkgs/main
menuinst                  1.4.19          py311h59b6b97_1    https://repo.anaconda.com/pkgs/main
openssl                   3.0.9                h2bbff1b_0    https://repo.anaconda.com/pkgs/main
packaging                 23.0            py311haa95532_0    https://repo.anaconda.com/pkgs/main
pcre2                     10.37                h0ff8eda_1    https://repo.anaconda.com/pkgs/main
pip                       23.1.2          py311haa95532_0    https://repo.anaconda.com/pkgs/main
pluggy                    1.0.0           py311haa95532_1    https://repo.anaconda.com/pkgs/main
powershell_shortcut_miniconda 0.0.1                haa95532_1    https://repo.anaconda.com/pkgs/main
pybind11-abi              4                    hd3eb1b0_1    https://repo.anaconda.com/pkgs/main
pycosat                   0.6.4           py311h2bbff1b_0    https://repo.anaconda.com/pkgs/main
pycparser                 2.21               pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
pyopenssl                 23.0.0          py311haa95532_0    https://repo.anaconda.com/pkgs/main
pysocks                   1.7.1           py311haa95532_0    https://repo.anaconda.com/pkgs/main
python                    3.11.4               he1021f5_0    https://repo.anaconda.com/pkgs/main
reproc                    14.2.4               hd77b12b_1    https://repo.anaconda.com/pkgs/main
reproc-cpp                14.2.4               hd77b12b_1    https://repo.anaconda.com/pkgs/main
requests                  2.29.0          py311haa95532_0    https://repo.anaconda.com/pkgs/main
ruamel.yaml               0.17.21         py311h2bbff1b_0    https://repo.anaconda.com/pkgs/main
setuptools                67.8.0          py311haa95532_0    https://repo.anaconda.com/pkgs/main
six                       1.16.0             pyhd3eb1b0_1    https://repo.anaconda.com/pkgs/main
sqlite                    3.41.2               h2bbff1b_0    https://repo.anaconda.com/pkgs/main
tk                        8.6.12               h2bbff1b_0    https://repo.anaconda.com/pkgs/main
toolz                     0.12.0          py311haa95532_0    https://repo.anaconda.com/pkgs/main
tqdm                      4.65.0          py311h746a85d_0    https://repo.anaconda.com/pkgs/main
tzdata                    2023c                h04d1e81_0    https://repo.anaconda.com/pkgs/main
urllib3                   1.26.16         py311haa95532_0    https://repo.anaconda.com/pkgs/main
vc                        14.2                 h21ff451_1    https://repo.anaconda.com/pkgs/main
vs2015_runtime            14.27.29016          h5e58377_2    https://repo.anaconda.com/pkgs/main
wheel                     0.38.4          py311haa95532_0    https://repo.anaconda.com/pkgs/main
win_inet_pton             1.1.0           py311haa95532_0    https://repo.anaconda.com/pkgs/main
xz                        5.4.2                h8cc25b3_0    https://repo.anaconda.com/pkgs/main
yaml-cpp                  0.7.0                hd77b12b_1    https://repo.anaconda.com/pkgs/main
zlib                      1.2.13               h8cc25b3_0    https://repo.anaconda.com/pkgs/main
zstandard                 0.19.0          py311h2bbff1b_0    https://repo.anaconda.com/pkgs/main
zstd                      1.5.5                hd43e919_0    https://repo.anaconda.com/pkgs/main
```

### Additional Context

can work when I set the character set like this

![image](https://github.com/conda/conda/assets/53466270/51a53e60-8e89-4f4d-84bb-6b2e276ff8d1)

but in vscode

![image](https://github.com/conda/conda/assets/53466270/d21c8925-7487-4925-b88c-c79d6494a37c)

**Comment by travishathaway** [comment]
Hi @lvbibir,

Thanks for filing this issue. I have categorized it, and our team will get to it at our nearest when we can. I have also added the "good-first" issue label to it as I believe it could be good bug to solve for a would-be contributor.

We cannot promise when we will get to this as we have a large amount of incoming issues. We thank you for your patience and understanding.

**Comment by YihongT** [comment]
Hi author, Change the default value of "encoding" to 'utf-8' of the class "Popen" will resolve this issue
