### ISSUE TITLE
SP_DIR variable

### ISSUE THREAD

**Issue by ChunZhuo** [conda/conda#12969]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Traceback (most recent call last):
  File "/lustre/BIF/nobackup/zhang408/Lightning/
    import dataset_TF
  File "/lustre/BIF/nobackup/zhang408/Lightning/
    import torchtext.transforms
  File "/lustre/BIF/nobackup/zhang408/miniconda3py", line 6, in <module>
    from torchtext import _extension  # noqa: F4
  File "/lustre/BIF/nobackup/zhang408/miniconda3n.py", line 7, in <module>
    _LIB_DIR = Path(os.environ["SP_DIR"]) / "tor
  File "/lustre/BIF/nobackup/zhang408/miniconda3
    raise KeyError(key) from None
KeyError: 'SP_DIR'

### Conda Info

```shell
active environment : base
    active env location : /lustre/BIF/nobackup/zhang408/miniconda3
            shell level : 1
       user config file : /home/zhang408/.condarc
 populated config files : /home/zhang408/.condarc
          conda version : 23.7.2
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.31=0
                          __linux=5.0.0=0
                          __unix=0=0
       base environment : /lustre/BIF/nobackup/zhang408/miniconda3  (writable)
      conda av data dir : /lustre/BIF/nobackup/zhang408/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /lustre/BIF/nobackup/zhang408/miniconda3/pkgs
                          /home/zhang408/.conda/pkgs
       envs directories : /lustre/BIF/nobackup/zhang408/miniconda3/envs
                          /home/zhang408/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.2 requests/2.31.0 CPython/3.10.12 Linux/5.0.0-40-generic ubuntu/20.04.6 glibc/2.31
                UID:GID : 17589473:16777729
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/zhang408/.condarc <==
auto_activate_base: False
channels:
  - bioconda
  - conda-forge
  - defaults

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
absl-py                   1.4.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.5           py310h2372a71_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
alsa-lib                  1.2.8                h166bdaf_0    conda-forge
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
arrow                     1.2.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attr                      2.5.1                h166bdaf_1    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
automat                   22.10.0            pyhd8ed1ab_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.cached-property 1.0.2              pyhd8ed1ab_0    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
bcrypt                    3.2.2           py310h5764c6d_1    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
biopython                 1.79                     pypi_0    pypi
bleach                    6.0.0                    pypi_0    pypi
blessed                   1.19.1             pyhe4f9e05_2    conda-forge
blinker                   1.6.2              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boto3                     1.27.1                   pypi_0    pypi
botocore                  1.30.1                   pypi_0    pypi
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotlipy                  0.7.0           py310h5764c6d_1005    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cachecontrol              0.12.14            pyhd8ed1ab_0    conda-forge
cachecontrol-with-filecache 0.12.14            pyhd8ed1ab_0    conda-forge
cachetools                5.3.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
catalogue                 2.0.9           py310hff52083_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h255011f_3    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
cleo                      2.0.1              pyhd8ed1ab_0    conda-forge
click                     8.1.6           unix_pyh707e725_0    conda-forge
cmake                     3.26.3                   pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.7.2          py310hff52083_0    conda-forge
conda-content-trust       0.1.1              pyhd3eb1b0_0    defaults
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
confection                0.1.0           py310hfdc917e_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
contourpy                 1.1.0           py310hd41b1e2_0    conda-forge
crashtest                 0.4.1              pyhd8ed1ab_0    conda-forge
croniter                  1.3.15             pyhd8ed1ab_0    conda-forge
cryptography              41.0.2          py310h75e40e8_0    conda-forge
cssselect                 1.2.0              pyhd8ed1ab_0    conda-forge
cuda-cudart               11.8.89                       0    nvidia
cuda-cupti                11.8.87                       0    nvidia
cuda-libraries            11.8.0                        0    nvidia
cuda-nvrtc                11.8.89                       0    nvidia
cuda-nvtx                 11.8.86                       0    nvidia
cuda-runtime              11.8.0                        0    nvidia
cuda-version              11.8                 h70ddcb2_2    conda-forge
cudatoolkit               11.8.0              h37601d7_11    conda-forge
cudnn                     8.8.0.121            h0800d71_1    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cymem                     2.0.7           py310hd8f1fbe_1    conda-forge
cython-blis               0.7.9           py310hde88566_1    conda-forge
dataclasses               0.8                pyhc8e2a94_3    conda-forge
dateutils                 0.6.12                     py_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
deepdiff                  6.3.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.7              pyhd8ed1ab_0    conda-forge
double-conversion         3.3.0                h59595ed_0    conda-forge
dulwich                   0.21.5          py310h2372a71_0    conda-forge
einops                    0.6.1                    pypi_0    pypi
exceptiongroup            1.1.2              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fair-esm                  2.0.0                    pypi_0    pypi
fastapi                   0.88.0             pyhd8ed1ab_0    conda-forge
filelock                  3.12.2             pyhd8ed1ab_0    conda-forge
fmt                       9.1.0                h924138e_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.42.0          py310h2372a71_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
frozenlist                1.4.0           py310h2372a71_0    conda-forge
fsspec                    2023.6.0           pyh1a96a4e_0    conda-forge
geometricus               0.5.0                    pypi_0    pypi
gettext                   0.21.1               h27087fc_0    conda-forge
glib                      2.76.4               hfc55251_0    conda-forge
glib-tools                2.76.4               hfc55251_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gmpy2                     2.1.2           py310h3ec546c_1    conda-forge
google-auth               2.22.0             pyh1a96a4e_0    conda-forge
google-auth-oauthlib      1.0.0              pyhd8ed1ab_1    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
grpcio                    1.54.3          py310heca2aa9_0    conda-forge
gst-plugins-base          1.22.3               h938bd60_1    conda-forge
gstreamer                 1.22.3               h977cf35_1    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
hyperlink                 21.0.0             pyhd3deb0d_0    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
importlib_resources       6.0.0              pyhd8ed1ab_1    conda-forge
incremental               22.10.0            pyhd8ed1ab_0    conda-forge
inquirer                  3.1.3              pyhd8ed1ab_0    conda-forge
itemadapter               0.8.0              pyhd8ed1ab_0    conda-forge
itemloaders               1.1.0              pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jaraco.classes            3.3.0              pyhd8ed1ab_0    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.3.0              pyhd8ed1ab_1    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.18.6             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.7.1           pyhd8ed1ab_0    conda-forge
kaggle                    1.5.15                   pypi_0    pypi
keyring                   23.13.1         py310hff52083_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4           py310hbf28c38_1    conda-forge
krb5                      1.20.1               h81ceb04_0    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
langcodes                 3.3.0              pyhd8ed1ab_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20230125.3      cxx17_h59595ed_0    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcap                    2.69                 h0f662aa_0    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  16.0.6          default_h1cdf331_1    conda-forge
libclang13                16.0.6          default_h4d60ac6_1    conda-forge
libcublas                 11.11.3.6                     0    nvidia
libcufft                  10.9.0.58                     0    nvidia
libcufile                 1.6.1.9                       0    nvidia
libcups                   2.3.3                h36d4200_3    conda-forge
libcurand                 10.3.2.106                    0    nvidia
libcurl                   8.1.2                h409715c_0    conda-forge
libcusolver               11.4.1.48                     0    nvidia
libcusparse               11.7.5.86                     0    nvidia
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.12               hf998b51_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libflac                   1.4.3                h59595ed_0    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgcrypt                 1.10.1               h166bdaf_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgpg-error              1.47                 h71f35ed_0    conda-forge
libgrpc                   1.54.3               hb20ce57_0    conda-forge
libhwloc                  2.9.2           nocuda_h7313eea_1008    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libllvm16                 16.0.6               h5cf9203_1    conda-forge
libmagma                  2.7.1                hc72dce7_3    conda-forge
libmagma_sparse           2.7.1                hc72dce7_4    conda-forge
libmamba                  1.4.9                h658169a_0    conda-forge
libmambapy                1.4.9           py310h8aae740_0    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnpp                    11.8.0.86                     0    nvidia
libnsl                    2.0.0                h7f98852_0    conda-forge
libnvjpeg                 11.9.0.86                     0    nvidia
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libpq                     15.3                 hbcd7760_1    conda-forge
libprotobuf               3.21.12              h3eb15da_0    conda-forge
libsentencepiece          0.1.99               h180e1df_1    conda-forge
libsndfile                1.2.0                hb75c966_0    conda-forge
libsolv                   0.7.24               hfc55251_1    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libsystemd0               254                  h3516f8a_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libutf8proc               2.8.0                h166bdaf_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxkbcommon              1.5.0                h5d7e998_3    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libxslt                   1.1.37               h0054252_1    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
lightning                 2.0.3              pyhd8ed1ab_0    conda-forge
lightning-cloud           0.5.37             pyhd8ed1ab_0    conda-forge
lightning-utilities       0.9.0              pyhd8ed1ab_0    conda-forge
lit                       16.0.5                   pypi_0    pypi
llvm-openmp               16.0.6               h4dfa4b3_0    conda-forge
llvmlite                  0.39.1                   pypi_0    pypi
lmdb                      1.4.1                    pypi_0    pypi
lockfile                  0.12.2                     py_1    conda-forge
lxml                      4.9.3           py310h9b7343a_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
magma                     2.7.1                ha770c72_4    conda-forge
mamba                     1.4.9           py310h51d5547_0    conda-forge
markdown                  3.4.4              pyhd8ed1ab_0    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.2                    pypi_0    pypi
matplotlib                3.7.1           py310hff52083_0    conda-forge
matplotlib-base           3.7.1           py310he60537e_0    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
mkl                       2022.2.1         h84fe81f_16997    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
mpc                       1.3.1                hfe3b2da_0    conda-forge
mpfr                      4.2.0                hb012696_0    conda-forge
mpg123                    1.31.3               hcb278e6_0    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310hdf3cbec_0    conda-forge
multidict                 6.0.4           py310h1fa729e_0    conda-forge
munkres                   1.0.7                      py_1    bioconda
murmurhash                1.0.9           py310hd8f1fbe_1    conda-forge
mysql-common              8.0.33               hf1915f5_2    conda-forge
mysql-libs                8.0.33               hca2cd23_2    conda-forge
nccl                      2.18.3.1             h12f7317_0    conda-forge
ncurses                   6.4                  hcb278e6_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
nltk                      3.8.1              pyhd8ed1ab_0    conda-forge
nspr                      4.35                 h27087fc_0    conda-forge
nss                       3.89                 he45b914_0    conda-forge
numba                     0.56.3                   pypi_0    pypi
numpy                     1.23.4                   pypi_0    pypi
nvidia-cublas-cu11        11.10.3.66               pypi_0    pypi
nvidia-cuda-cupti-cu11    11.7.101                 pypi_0    pypi
nvidia-cuda-nvrtc-cu11    11.7.99                  pypi_0    pypi
nvidia-cuda-runtime-cu11  11.7.99                  pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft-cu11         10.9.0.58                pypi_0    pypi
nvidia-curand-cu11        10.2.10.91               pypi_0    pypi
nvidia-cusolver-cu11      11.4.0.1                 pypi_0    pypi
nvidia-cusparse-cu11      11.7.4.91                pypi_0    pypi
nvidia-nccl-cu11          2.14.3                   pypi_0    pypi
nvidia-nvtx-cu11          11.7.91                  pypi_0    pypi
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
obonet                    1.0.0              pyh7cba7a3_0    bioconda
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
ordered-set               4.1.0              pyhd8ed1ab_0    conda-forge
orjson                    3.9.2           py310h1e2579a_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
pandas                    2.0.2           py310h7cbd5c2_0    conda-forge
parsel                    1.8.1              pyhd8ed1ab_0    conda-forge
pathy                     0.10.2             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pillow                    10.0.0          py310h582fbeb_0    conda-forge
pip                       23.0.1          py310h06a4308_0    defaults
pixman                    0.40.0               h36c2ea0_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.2.0              pyhd8ed1ab_0    conda-forge
ply                       3.11                       py_1    conda-forge
poetry                    1.5.1           linux_pyhd8ed1ab_0    conda-forge
poetry-core               1.6.1              pyhd8ed1ab_0    conda-forge
poetry-plugin-export      1.4.0              pyhd8ed1ab_0    conda-forge
pooch                     1.7.0              pyha770c72_3    conda-forge
preshed                   3.0.8           py310hd8f1fbe_1    conda-forge
prody                     2.4.0                    pypi_0    pypi
protego                   0.2.1              pyhd8ed1ab_0    conda-forge
protein-bert-pytorch      0.1.0                    pypi_0    pypi
protobuf                  4.23.3                   pypi_0    pypi
psutil                    5.9.5           py310h1fa729e_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pulseaudio-client         16.1                 hb77b528_4    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.4           py310h5764c6d_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pydantic                  1.10.12         py310h2372a71_1    conda-forge
pydispatcher              2.0.5                      py_1    conda-forge
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pynndescent               0.5.10             pyh1a96a4e_0    conda-forge
pyopenssl                 23.2.0             pyhd8ed1ab_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyproject_hooks           1.0.0              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.9          py310h04931ad_4    conda-forge
pyqt5-sip                 12.12.2         py310hc6cd4ac_4    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.12         hd12c33a_0_cpython    conda-forge
python-build              0.10.0             pyhd8ed1ab_1    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-installer          0.7.0              pyhd8ed1ab_0    conda-forge
python-multipart          0.0.6              pyhd8ed1ab_0    conda-forge
python-slugify            8.0.1                    pypi_0    pypi
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytorch                   2.0.0           cuda112py310he33e0d6_200    conda-forge
pytorch-cuda              11.8                 h7e8668a_5    pytorch
pytorch-lightning         2.0.6              pyhd8ed1ab_0    conda-forge
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h5764c6d_5    conda-forge
qt-main                   5.15.8              h01ceb2d_12    conda-forge
queuelib                  1.6.2              pyhd8ed1ab_0    conda-forge
rapidfuzz                 2.15.1          py310heca2aa9_0    conda-forge
re2                       2023.03.02           h8c504da_0    conda-forge
readchar                  4.0.5              pyhd8ed1ab_0    conda-forge
readline                  8.2                  h8228510_1    conda-forge
referencing               0.30.1             pyhd8ed1ab_0    conda-forge
regex                     2023.6.3        py310h2372a71_0    conda-forge
reproc                    14.2.4               h0b41bf4_0    conda-forge
reproc-cpp                14.2.4               hcb278e6_0    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-file             1.5.1              pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
requests-toolbelt         1.0.0              pyhd8ed1ab_0    conda-forge
revtok                    0.0.3.1            pyhd8ed1ab_0    conda-forge
rich                      13.5.1             pyhd8ed1ab_0    conda-forge
rocm-smi                  5.6.0                h59595ed_1    conda-forge
rpds-py                   0.9.2           py310hcb5633a_0    conda-forge
rsa                       4.9                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.32         py310h2372a71_0    conda-forge
ruamel.yaml.clib          0.2.7           py310h1fa729e_1    conda-forge
s3transfer                0.6.1                    pypi_0    pypi
sacremoses                0.0.53             pyhd8ed1ab_0    conda-forge
scikit-learn              1.3.0           py310hf7d194e_0    conda-forge
scipy                     1.11.1          py310ha4c1d20_0    conda-forge
scrapy                    2.9.0           py310hff52083_0    conda-forge
secretstorage             3.3.3           py310hff52083_1    conda-forge
service_identity          18.1.0                     py_0    conda-forge
setuptools                65.6.3          py310h06a4308_0    defaults
shellingham               1.5.1              pyhd8ed1ab_0    conda-forge
sip                       6.7.11          py310hc6cd4ac_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sleef                     3.5.1                h9b69904_2    conda-forge
smart_open                5.2.1              pyhd8ed1ab_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
spacy                     3.6.0           py310hfb6f7a9_0    conda-forge
spacy-legacy              3.0.12             pyhd8ed1ab_0    conda-forge
spacy-loggers             1.0.4              pyhd8ed1ab_0    conda-forge
srsly                     2.4.7           py310hc6cd4ac_0    conda-forge
starlette                 0.22.0             pyhd8ed1ab_0    conda-forge
starsessions              1.3.0              pyhd8ed1ab_0    conda-forge
sympy                     1.12            pypyh9d50eac_103    conda-forge
tape-proteins             0.5                      pypi_0    pypi
tbb                       2021.10.0            h00ab1b0_0    conda-forge
tensorboard               2.13.0             pyhd8ed1ab_0    conda-forge
tensorboard-data-server   0.7.0           py310h34c0648_0    conda-forge
tensorboardx              2.6.1                    pypi_0    pypi
text-unidecode            1.3                      pypi_0    pypi
thinc                     8.1.10          py310hfb6f7a9_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tldextract                3.4.4              pyhd8ed1ab_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.12.1             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torch                     2.0.1                    pypi_0    pypi
torchaudio                2.0.0               py310_cu118    pytorch
torchmetrics              0.11.4             pyhd8ed1ab_0    conda-forge
torchtext                 0.15.2          py310hd979c64_2    conda-forge
torchvision               0.15.2                   pypi_0    pypi
tornado                   6.3.2           py310h2372a71_0    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
triton                    2.0.0                    pypi_0    pypi
trove-classifiers         2023.7.6           pyhd8ed1ab_0    conda-forge
twisted                   22.10.0         py310h5764c6d_0    conda-forge
typer                     0.9.0              pyhd8ed1ab_0    conda-forge
typing                    3.10.0.0           pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
umap-learn                0.5.3           py310hff52083_1    conda-forge
unicodedata2              15.0.0          py310h5764c6d_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
uvicorn                   0.23.2          py310hff52083_0    conda-forge
virtualenv                20.24.2            pyhd8ed1ab_0    conda-forge
w3lib                     2.1.2              pyhd8ed1ab_0    conda-forge
wasabi                    1.1.2           py310hff52083_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
websockets                11.0.3          py310h2372a71_0    conda-forge
werkzeug                  2.3.6              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4          py310h06a4308_0    defaults
xcb-util                  0.4.0                hd590300_1    conda-forge
xcb-util-image            0.4.0                h8ee46fc_1    conda-forge
xcb-util-keysyms          0.4.0                h8ee46fc_1    conda-forge
xcb-util-renderutil       0.3.9                hd590300_1    conda-forge
xcb-util-wm               0.4.1                h8ee46fc_1    conda-forge
xkeyboard-config          2.39                 hd590300_0    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.7.0                h27087fc_2    conda-forge
yarl                      1.9.2           py310h2372a71_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zope.interface            6.0             py310h1fa729e_0    conda-forge
zstandard                 0.19.0          py310h1275a96_2    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

### Additional Context

linux system
I installed torchtext but I cannot import it

**Comment by travishathaway** [comment]
Hi @ChunZhuo,

Thanks for filing this issue. You will have to bring this issue up with the package maintainers. The issue queue for this project is only for problems encountered while running conda commands. We do not support packages that are installed by conda itself.
