### ISSUE TITLE
Corrupted Conda trying to update

### ISSUE THREAD

**Issue by jmeline** [conda/conda#1299]
My conda environment became corrupted trying to update.

I ran this command 
```
conda update --all
```
and this was the output that I got
```
An unexpected error has occurred, please consider sending the                           |  54%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/jmeline/anaconda/bin/conda", line 5, in <module>
    
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/install.py", line 534, in link
    _link(src, dst, lt)
  File "/home/jmeline/anaconda/lib/python2.7/site-packages/conda/install.py", line 133, in _link
    shutil.copy2(src, dst)
  File "/home/jmeline/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/home/jmeline/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/home/jmeline/anaconda/lib/python2.7/site-packages/zmq/utils/compiler.json'
```
Now I tried to use conda as sudo to handle the permission error and discovered that I don't have conda anymore

```
➜  tests git:(master) ✗ sudo conda update --all
[sudo] password for jmeline: 
sudo: conda: command not found

➜  tests git:(master) ✗ conda
zsh: command not found: conda

```

I am running Manjaro Linux. I had Anaconda-2.2.0.x64-x86.sh installed.

**Comment by ccordoba12** [comment]
I think you'll have to reinstall Anaconda. Before running

    conda update --all

please run

    conda update conda

because (I think) the latest conda version has a better `update --all` command than previous versions

**Comment by jmeline** [comment]
@ccordoba12 Thanks for the tip. I'll be sure to do that next time
