### ISSUE TITLE
Anaconda update failed: NoneType object is not subscriptable

### ISSUE THREAD

**Issue by yha** [conda/conda#1300]
On running conda update anaconda (after conda update conda):

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 212, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 44, in ex
ecute
    install.install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 413, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 531, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 156, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 105, in ENSU
RE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 658, in ensure_wr
ite
    if not can_open_all_files_in_prefix(prefix, meta["files"]):
TypeError: 'NoneType' object is not subscriptable
```

conda info output:

```
C:\Anaconda3\Scripts>conda info
Current conda install:

             platform : win-64
        conda version : 3.11.0
  conda-build version : 1.3.5
       python version : 3.4.1.final.0
     requests version : 2.6.2
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by soapy1** [comment]
@yha is this still and issue for you?
