### ISSUE TITLE
re turned non-zero exit status 1.

### ISSUE THREAD

**Issue by MHassanSaeed** [conda/conda#13007]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/panaroo/bin/panaroo", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/                                                                                                                                   __main__.py", line 358, in main
    G = collapse_families(G,
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/                                                                                                                                   clean_network.py", line 113, in collapse_families
    cdhit_clusters = iterative_cdhit(G,
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/                                                                                                                                   cdhit.py", line 411, in iterative_cdhit
    run_cdhit_est(input_file=temp_input_file.name,
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/site-packages/panaroo/                                                                                                                                   cdhit.py", line 147, in run_cdhit_est
    subprocess.run(cmd, shell=True, check=True)
  File "/home/ubuntu/anaconda3/envs/panaroo/lib/python3.9/subprocess.py", line 5                                                                                                                                   28, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'cd-hit-est -T 1 -i /home/ubuntu/Ent Coho                                                                                                                                   rts/Prokfaecalis/fgff/results/tmp947rw3gg/tmp6buvv3ld -o /home/ubuntu/Ent Cohort                                                                                                                                   s/Prokfaecalis/fgff/results/tmp947rw3gg/tmpwtaf8w45 -c 0.99 -s 0.0 -aL 0.0 -AL 9                                                                                                                                   9999999 -aS 99999999 -AS 99999999 -r 1 -M 0 -d 999 -mask NX -n 7 > /dev/null' re                                                                                                                                   turned non-zero exit status 1.

### Conda Info

```shell
active environment : base
    active env location : /home/ubuntu/anaconda3
            shell level : 1
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.9.13.final.0
       virtual packages : __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /home/ubuntu/anaconda3  (writable)
      conda av data dir : /home/ubuntu/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/cruizperez/linux-64
                          https://conda.anaconda.org/cruizperez/noarch
          package cache : /home/ubuntu/anaconda3/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/anaconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.28.1 CPython/3.9.13 Linux/5.4.0-1089-kvm ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
- conda-forge
  - bioconda
  - defaults
  - cruizperez
```

### Conda list

```shell
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
alsa-lib                  1.2.9                hd590300_0    conda-forge
aragorn                   1.2.41               h031d066_1    bioconda
argcomplete               3.1.1              pyhd8ed1ab_0    conda-forge
argh                      0.27.2             pyhd8ed1ab_0    conda-forge
argtable2                 2.13              h14c3975_1001    conda-forge
arpack                    3.7.0                hdefa2d7_2    conda-forge
barrnap                   0.9                  hdfd78af_4    bioconda
bedtools                  2.31.0               hf5e1c6e_2    bioconda
biocode                   0.10.0             pyhdfd78af_0    bioconda
biopython                 1.81             py39h72bdee0_0    conda-forge
blast                     2.14.0               h7d5a4b4_1    bioconda
blast-legacy              2.2.26               h9ee0642_3    bioconda
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotli-python             1.0.9            py39h5a03fae_9    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
cairo                     1.16.0            hbbf8b49_1016    conda-forge
capnproto                 0.9.1                ha19adfc_4    conda-forge
cd-hit                    4.8.1                h43eeafb_9    bioconda
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
charset-normalizer        3.2.0              pyhd8ed1ab_0    conda-forge
clustalo                  1.2.4                hdbdd923_7    bioconda
clustalw                  2.1                  h4ac6f70_9    bioconda
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
contourpy                 1.1.0            py39h7633fee_0    conda-forge
curl                      8.2.1                hca28451_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
dendropy                  4.6.1              pyhdfd78af_0    bioconda
entrez-direct             16.2                 he881be0_1    bioconda
expat                     2.5.0                hcb278e6_1    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.42.1           py39hd1e30aa_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gffutils                  0.12               pyh7cba7a3_0    bioconda
giflib                    5.2.1                h0b41bf4_3    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
graphite2                 1.3.13            h58526e2_1001    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
harfbuzz                  7.3.0                hdb3a94d_0    conda-forge
hmmer                     3.3.2                hdbdd923_4    bioconda
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-resources       6.0.1              pyhd8ed1ab_0    conda-forge
importlib_resources       6.0.1              pyhd8ed1ab_0    conda-forge
infernal                  1.1.4           pl5321h031d066_4    bioconda
intbitset                 2.4.1            py39hb9d737c_3    conda-forge
intel-openmp              2023.1.0         hdb19cb5_46305    defaults
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_1    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libcups                   2.3.3                h4637d8d_4    conda-forge
libcurl                   8.2.1                hca28451_0    conda-forge
libdb                     6.2.32               h9c3ff4c_0    conda-forge
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libglib                   2.76.4               hebfc3b9_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libhwloc                  2.9.2           nocuda_h7313eea_1008    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libidn11                  1.34                 h1cef754_0    conda-forge
libidn2                   2.3.4                h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
libllvm14                 14.0.6               hcd5def8_4    conda-forge
libnghttp2                1.52.0               h61bc06f_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsqlite                 3.42.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.5               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
llvmlite                  0.40.1           py39h174d805_0    conda-forge
mafft                     7.520                h031d066_2    bioconda
markupsafe                2.1.3            py39hd1e30aa_0    conda-forge
mash                      2.3                  ha9a2dd8_3    bioconda
matplotlib-base           3.7.1            py39he190548_0    conda-forge
metis                     5.1.1                h59595ed_0    conda-forge
minced                    0.4.2                hdfd78af_1    bioconda
mkl                       2023.1.0         h213fc3f_46343    defaults
mpfr                      4.2.0                hb012696_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
muscle                    5.1                  h4ac6f70_3    bioconda
ncurses                   6.4                  hcb278e6_0    conda-forge
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numba                     0.57.1           py39hb75a051_0    conda-forge
numpy                     1.24.4           py39h6183b62_0    conda-forge
openjdk                   20.0.0               h8e330f5_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openmp                    7.0.0                h2d50403_0    conda-forge
openssl                   3.1.2                hd590300_0    conda-forge
packaging                 23.1               pyhd8ed1ab_0    conda-forge
paml                      4.10.6               h031d066_2    bioconda
panaroo                   1.3.3              pyhdfd78af_0    bioconda
parallel                  20230722             ha770c72_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
peewee                    3.16.3           py39h21eaaa1_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
perl-algorithm-diff       1.201           pl5321hd8ed1ab_0    conda-forge
perl-archive-tar          2.40            pl5321hdfd78af_0    bioconda
perl-base                 2.23            pl5321hd8ed1ab_0    conda-forge
perl-bio-asn1-entrezgene  1.73            pl5321hdfd78af_3    bioconda
perl-bio-coordinate       1.007001        pl5321hdfd78af_3    bioconda
perl-bio-featureio        1.6.905         pl5321hdfd78af_4    bioconda
perl-bio-samtools         1.43            pl5321he4a0461_4    bioconda
perl-bio-searchio-hmmer   1.7.3           pl5321hdfd78af_0    bioconda
perl-bio-tools-phylo-paml 1.7.3           pl5321hdfd78af_3    bioconda
perl-bio-tools-run-alignment-clustalw 1.7.4           pl5321hdfd78af_3    biocon                                                                                                                                   da
perl-bio-tools-run-alignment-tcoffee 1.7.4           pl5321hdfd78af_5    biocond                                                                                                                                   a
perl-bioperl              1.7.8                hdfd78af_1    bioconda
perl-bioperl-core         1.7.8           pl5321hdfd78af_1    bioconda
perl-bioperl-run          1.007003        pl5321hdfd78af_0    bioconda
perl-business-isbn        3.007           pl5321hd8ed1ab_0    conda-forge
perl-business-isbn-data   20210112.006    pl5321hd8ed1ab_0    conda-forge
perl-carp                 1.50            pl5321hd8ed1ab_0    conda-forge
perl-class-data-inheritable 0.09            pl5321ha770c72_0    conda-forge
perl-common-sense         3.75            pl5321hd8ed1ab_0    conda-forge
perl-compress-raw-bzip2   2.201           pl5321h166bdaf_0    conda-forge
perl-compress-raw-zlib    2.202           pl5321h166bdaf_0    conda-forge
perl-constant             1.33            pl5321hd8ed1ab_0    conda-forge
perl-data-dumper          2.183           pl5321h166bdaf_0    conda-forge
perl-db_file              1.858           pl5321h166bdaf_0    conda-forge
perl-devel-stacktrace     2.04            pl5321ha770c72_0    conda-forge
perl-digest-hmac          1.04            pl5321hdfd78af_0    bioconda
perl-digest-md5           2.58            pl5321h166bdaf_0    conda-forge
perl-encode               3.19            pl5321h166bdaf_0    conda-forge
perl-encode-locale        1.05            pl5321hdfd78af_7    bioconda
perl-exception-class      1.45            pl5321hdfd78af_0    bioconda
perl-exporter             5.74            pl5321hd8ed1ab_0    conda-forge
perl-exporter-tiny        1.002002        pl5321hd8ed1ab_0    conda-forge
perl-extutils-makemaker   7.70            pl5321hd8ed1ab_0    conda-forge
perl-file-listing         6.16            pl5321hdfd78af_0    bioconda
perl-file-path            2.18            pl5321hd8ed1ab_0    conda-forge
perl-file-slurp-tiny      0.004           pl5321hdfd78af_2    bioconda
perl-file-sort            1.01            pl5321hdfd78af_3    bioconda
perl-file-spec            3.48_01         pl5321hdfd78af_2    bioconda
perl-file-temp            0.2304          pl5321hd8ed1ab_0    conda-forge
perl-getopt-long          2.54            pl5321hdfd78af_0    bioconda
perl-html-parser          3.81            pl5321h4ac6f70_1    bioconda
perl-html-tagset          3.20            pl5321hdfd78af_4    bioconda
perl-http-cookies         6.10            pl5321hdfd78af_0    bioconda
perl-http-daemon          6.16            pl5321hdfd78af_0    bioconda
perl-http-date            6.06            pl5321hdfd78af_0    bioconda
perl-http-message         6.36            pl5321hdfd78af_0    bioconda
perl-http-negotiate       6.01            pl5321hdfd78af_4    bioconda
perl-inc-latest           0.500           pl5321ha770c72_0    conda-forge
perl-io-compress          2.201           pl5321hdbdd923_2    bioconda
perl-io-html              1.004           pl5321hdfd78af_0    bioconda
perl-io-socket-ssl        2.075           pl5321hd8ed1ab_0    conda-forge
perl-io-string            1.08            pl5321hdfd78af_4    bioconda
perl-io-tty               1.16            pl5321h166bdaf_0    conda-forge
perl-io-zlib              1.14            pl5321hdfd78af_0    bioconda
perl-ipc-run              20200505.0      pl5321hdfd78af_0    bioconda
perl-json                 4.10            pl5321hdfd78af_0    bioconda
perl-json-xs              2.34            pl5321h4ac6f70_6    bioconda
perl-libwww-perl          6.67            pl5321hdfd78af_0    bioconda
perl-libxml-perl          0.08            pl5321hdfd78af_3    bioconda
perl-list-moreutils       0.430           pl5321hdfd78af_0    bioconda
perl-list-moreutils-xs    0.430           pl5321h031d066_2    bioconda
perl-lwp-mediatypes       6.04            pl5321hdfd78af_1    bioconda
perl-mime-base64          3.16            pl5321h166bdaf_0    conda-forge
perl-module-build         0.4234          pl5321ha770c72_0    conda-forge
perl-net-http             6.22            pl5321hdfd78af_0    bioconda
perl-net-ssleay           1.92            pl5321hf14f497_1    conda-forge
perl-ntlm                 1.09            pl5321hdfd78af_5    bioconda
perl-parent               0.241           pl5321hd8ed1ab_0    conda-forge
perl-pathtools            3.75            pl5321h166bdaf_0    conda-forge
perl-scalar-list-utils    1.63            pl5321h166bdaf_0    conda-forge
perl-socket               2.027           pl5321h031d066_4    bioconda
perl-storable             3.15            pl5321h166bdaf_0    conda-forge
perl-sub-uplevel          0.2800          pl5321h166bdaf_0    conda-forge
perl-test-deep            1.130           pl5321hd8ed1ab_0    conda-forge
perl-test-differences     0.70            pl5321ha770c72_0    conda-forge
perl-test-exception       0.43            pl5321hd8ed1ab_0    conda-forge
perl-test-fatal           0.016           pl5321ha770c72_0    conda-forge
perl-test-most            0.38            pl5321hdfd78af_0    bioconda
perl-test-warn            0.37            pl5321hd8ed1ab_0    conda-forge
perl-test-warnings        0.031           pl5321ha770c72_0    conda-forge
perl-text-diff            1.45            pl5321hd8ed1ab_0    conda-forge
perl-time-local           1.35            pl5321hdfd78af_0    bioconda
perl-timedate             2.33            pl5321hdfd78af_2    bioconda
perl-tree-dag_node        1.32            pl5321hdfd78af_0    bioconda
perl-try-tiny             0.31            pl5321ha770c72_0    conda-forge
perl-types-serialiser     1.01            pl5321hdfd78af_0    bioconda
perl-uri                  5.17            pl5321ha770c72_0    conda-forge
perl-url-encode           0.03            pl5321h9ee0642_0    bioconda
perl-www-robotrules       6.02            pl5321hdfd78af_4    bioconda
perl-xml-dom              1.46            pl5321hdfd78af_1    bioconda
perl-xml-dom-xpath        0.14            pl5321hdfd78af_2    bioconda
perl-xml-namespacesupport 1.12            pl5321hd8ed1ab_0    conda-forge
perl-xml-parser           2.44_01         pl5321hc3e0081_1003    conda-forge
perl-xml-regexp           0.04            pl5321hdfd78af_3    bioconda
perl-xml-sax              1.02            pl5321hd8ed1ab_0    conda-forge
perl-xml-sax-base         1.09            pl5321hd8ed1ab_0    conda-forge
perl-xml-sax-expat        0.51            pl5321hd8ed1ab_0    conda-forge
perl-xml-simple           2.25            pl5321hdfd78af_2    bioconda
perl-xml-xpathengine      0.14            pl5321hdfd78af_3    bioconda
pillow                    10.0.0           py39haaeba84_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
platformdirs              3.10.0             pyhd8ed1ab_0    conda-forge
plotly                    5.16.1             pyhd8ed1ab_0    conda-forge
poa                       2.0                  h031d066_5    bioconda
pooch                     1.7.0              pyha770c72_3    conda-forge
prank                     v.170427             h4ac6f70_7    bioconda
prodigal                  2.6.3                h031d066_6    bioconda
prokka                    1.14.6          pl5321hdfd78af_4    bioconda
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pyfaidx                   0.7.2.1            pyh7cba7a3_1    bioconda
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.9.17          h0755675_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-edlib              1.3.9            py39h1f90b4d_4    bioconda
python-igraph             0.10.6           py39hd49abe8_0    conda-forge
python_abi                3.9                      3_cp39    conda-forge
pyvcf3                    1.0.3              pyhdfd78af_0    bioconda
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rocm-smi                  5.6.0                h59595ed_1    conda-forge
scikit-learn              1.3.0            py39hc236052_0    conda-forge
scipy                     1.11.2           py39h6183b62_0    conda-forge
setuptools                68.1.2             pyhd8ed1ab_0    conda-forge
simplejson                3.19.1           py39h72bdee0_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
suitesparse               5.10.1               h9e50725_1    conda-forge
t-coffee                  12.00.7fb08c2        h26a2512_0    bioconda
taxadb                    0.12.1             pyh5e36f6f_0    bioconda
tbb                       2021.10.0            h00ab1b0_0    conda-forge
tbl2asn-forever           25.7.2f              h031d066_4    bioconda
tenacity                  8.2.3              pyhd8ed1ab_0    conda-forge
texttable                 1.6.7              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.2.0              pyha21a80b_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
unicodedata2              15.0.0           py39hb9d737c_0    conda-forge
urllib3                   2.0.4              pyhd8ed1ab_0    conda-forge
viennarna                 2.6.3           py39pl5321h4e691d4_0    bioconda
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.41.1             pyhd8ed1ab_0    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-inputproto           2.3.2             h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.6                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxi                1.7.10               h7f98852_0    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-libxtst              1.2.3             h7f98852_1002    conda-forge
xorg-recordproto          1.14.2            h7f98852_1002    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zipp                      3.16.2             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.2                hfc55251_7    conda-forge
```

### Additional Context

It says the program was completed but ended with the above error.

I have installed panaroo with conda.

Please let me know what's the issue. 
Thanks.

**Comment by kenodegard** [comment]
Unfortunately this is the issue reporter for `conda` itself. We do not offer support for how to use packages installed with `conda`. Please consult `panaroo`'s documentation and support resources for help with using `panaroo`:

- https://github.com/gtonkinhill/panaroo
- https://gtonkinhill.github.io/panaroo
