### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jk/anaconda/conda-meta/conda-3.10.0-py34_0.json'

### ISSUE THREAD

**Issue by emptist** [conda/conda#1302]
```
        platform : osx-64
    conda version : 3.11.0
```

  conda-build version : 1.11.0
       python version : 3.4.3.final.0
     requests version : 2.6.2
     root environment : /Users/jk/anaconda  (writable)
  default environment : /Users/jk/anaconda
     envs directories : /Users/jk/anaconda/envs
        package cache : /Users/jk/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Traceback (most recent call last):
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args_func(args, p)
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 40, in execute
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 420, in install
    log.debug("Can't write the history file")
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
    if to_link:
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 88, in UNLINK_CMD
    dist, pkgs_dir, lt = split_linkarg(arg)
  File "/Users/jk/anaconda/lib/python3.4/site-packages/conda/install.py", line 598, in unlink
FileNotFoundError: [Errno 2] No such file or directory: '/Users/jk/anaconda/conda-meta/conda-3.10.0-py34_0.json'

**Comment by soapy1** [comment]
@emptist is this still an issue for you?

**Comment by emptist** [comment]
@soapy1 no, not anymore. Thanks!
