### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) when creating from environment.yml with channels other than defaults 

### ISSUE THREAD

**Issue by BrunoBelucci** [conda/conda#13026]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When creating an environment from an environment.yml file where it is specified any channel other than `defaults`, we get a JSONDecodeError.

### Conda Info

```shell
active environment : base
    active env location : /home/bbelucci/miniconda3
            shell level : 1
       user config file : /home/bbelucci/.condarc
 populated config files : /home/bbelucci/.condarc
          conda version : 23.7.3
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/bbelucci/miniconda3  (writable)
      conda av data dir : /home/bbelucci/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bbelucci/miniconda3/pkgs
                          /home/bbelucci/.conda/pkgs
       envs directories : /home/bbelucci/miniconda3/envs
                          /home/bbelucci/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-26-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/bbelucci/.condarc <==
auto_activate_base: False

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
# packages in environment at /home/bbelucci/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
boltons                   23.0.0          py310h06a4308_0    defaults
brotlipy                  0.7.0           py310h7f8727e_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2023.05.30           h06a4308_0    defaults
certifi                   2023.7.22       py310h06a4308_0    defaults
cffi                      1.15.1          py310h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.7.3          py310h06a4308_0    defaults
conda-content-trust       0.1.3           py310h06a4308_0    defaults
conda-package-handling    2.2.0           py310h06a4308_0    defaults
conda-package-streaming   0.9.0           py310h06a4308_0    defaults
cryptography              39.0.1          py310h9ce1e76_2    defaults
idna                      3.4             py310h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.10               h7f8727e_1    defaults
packaging                 23.0            py310h06a4308_0    defaults
pip                       22.3.1          py310h06a4308_0    defaults
pluggy                    1.0.0           py310h06a4308_1    defaults
pycosat                   0.6.4           py310h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py310h06a4308_0    defaults
pysocks                   1.7.1           py310h06a4308_0    defaults
python                    3.10.12              h955ad1f_0    defaults
readline                  8.2                  h5eee18b_0    defaults
requests                  2.31.0          py310h06a4308_0    defaults
ruamel.yaml               0.17.21         py310h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6           py310h5eee18b_1    defaults
setuptools                65.6.3          py310h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py310h06a4308_0    defaults
tqdm                      4.65.0          py310h2f386ee_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py310h06a4308_0    defaults
wheel                     0.38.4          py310h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py310h5eee18b_0    defaults
```

### Additional Context

environment.yml file example:
```
name: my_env
channels:
  - conda-forge
dependencies:
  - numpy
  
```
command:
```
conda env create -f environment.yml
```
ERROR REPORT:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda_env/cli/main.py", line 56, in do_call
        exit_code = getattr(module, func_name)(arguments, parser)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda_env/cli/main_create.py", line 162, in execute
        result[installer_type] = installer.install(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda_env/installers/conda.py", line 51, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 154, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 215, in solve_for_diff
        final_precs = self.solve_final_state(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 358, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 572, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/solve.py", line 1286, in _prepare
        reduced_index = get_reduced_index(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/index.py", line 287, in get_reduced_index
        new_records = SubdirData.query_all(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 158, in query_all
        result = tuple(
      File "/home/bbelucci/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/home/bbelucci/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/home/bbelucci/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 451, in result
        return self.__get_result()
      File "/home/bbelucci/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/home/bbelucci/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 143, in subdir_query
        return tuple(
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 165, in query
        self.load()
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 265, in load
        _internal_state = self._load()
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 322, in _load
        repodata, state = fetcher.fetch_latest_parsed()
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 758, in fetch_latest_parsed
        parsed, state = self.fetch_latest()
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 820, in fetch_latest
        cache.load_state()
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 626, in load_state
        self.load(state_only=True)
      File "/home/bbelucci/miniconda3/lib/python3.10/site-packages/conda/gateways/repodata/__init__.py", line 576, in load
        state = json.loads(state_file.read())
      File "/home/bbelucci/miniconda3/lib/python3.10/json/__init__.py", line 346, in loads
        return _default_decoder.decode(s)
      File "/home/bbelucci/miniconda3/lib/python3.10/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/bbelucci/miniconda3/lib/python3.10/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /home/bbelucci/miniconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/bbelucci/miniconda3/bin/conda
             CONDA_PREFIX=/home/bbelucci/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/bbelucci/miniconda3/bin/python
               CONDA_ROOT=/home/bbelucci/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/home/bbelucci/miniconda3/bin:/home/bbelucci/miniconda3/condabin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games:/snap/bin:/snap/bin:/home/bbelucci/.local/share/JetBrain
                          s/Toolbox/scripts:/home/bbelucci/bash_scripts
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/bbelucci/miniconda3
            shell level : 1
       user config file : /home/bbelucci/.condarc
 populated config files : /home/bbelucci/.condarc
          conda version : 23.7.3
    conda-build version : not installed
         python version : 3.10.12.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=12.0=0
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/bbelucci/miniconda3  (writable)
      conda av data dir : /home/bbelucci/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/bbelucci/miniconda3/pkgs
                          /home/bbelucci/.conda/pkgs
       envs directories : /home/bbelucci/miniconda3/envs
                          /home/bbelucci/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.3 requests/2.31.0 CPython/3.10.12 Linux/6.2.0-26-generic ubuntu/22.04.3 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by najtin** [comment]
I also have this issue. This totally breaks nextflow which depends on conda for installing dependencies and requires multiple channels.

**Comment by najtin** [comment]
I think this might have the same cause as https://github.com/conda/conda/issues/13019

**Comment by najtin** [comment]
This seems to be very similar to https://github.com/conda/conda/issues/12995 but conda-forge does definitely exist.

**Comment by travishathaway** [comment]
Hi @najtin,

This could be caused by an error with a corrupt cache file. Could you try running `conda clean --all` and see it if resolves the issue? That command will remove all cache files.

Can you please let us know if that works for you? If not, we will be happy to advise further.

Obviously, this isn't the most informative error message for users. So, I would like to leave this issue open so we could keep it as an example of how we need to improve our cache file parsing.

**Comment by najtin** [comment]
Hi @travishathaway 
i can't give any insight in this specific error. But i can leave tell you something on https://github.com/conda/conda/issues/13037 I left my answer there.

**Comment by najtin** [comment]
@BrunoBelucci Did you or a some other program install conda packages in parallel at some point?

**Comment by BrunoBelucci** [comment]
> Hi @najtin,
> 
> This could be caused by an error with a corrupt cache file. Could you try running `conda clean --all` and see it if resolves the issue? That command will remove all cache files.
> 
> Can you please let us know if that works for you? If not, we will be happy to advise further.
> 
> Obviously, this isn't the most informative error message for users. So, I would like to leave this issue open so we could keep it as an example of how we need to improve our cache file parsing.

I can confirm that this solved the issue!
It certainly is not the most informative error message, I even tried to debug it myself but could not find the problem. The most frustrating part was that I had the exact same issue on 2 different machines (my personal one and a centralized cluster that I access via ssh), so it made me believe that it was a problem with conda and not with a corrupt cache file.

**Comment by BrunoBelucci** [comment]
> @BrunoBelucci Did you or a some other program install conda packages in parallel at some point?

Nope, not that I am aware of. It could be the case in the machine that I access via ssh because I am not sure of how isolated each account there is, but I am confident that this is not the case with my personal computer.

**Comment by travishathaway** [comment]
@BrunoBelucci,

I agree with you that this is not the most informative error! 🙃 I will add this issue to our backlog to be worked on. I believe at the very minimum, we could catch this error and provide a reasonable, actionable error message such as,

> It appears your cache has become corrupt, please try running `conda clean --all` to solve it.

**Comment by dholth** [comment]
Does Conda 23.9 address this issue?

**Comment by dholth** [comment]
#13056

**Comment by BrunoBelucci** [comment]
> Does Conda 23.9 address this issue?

I am not sure, I don't know how to test it because I don't know how the files got corrupted in the first place. All I can say is that `conda clean --all` solved the issue for me.
