### ISSUE TITLE
Install from .tar.bz2 or .conda with dependencies

### ISSUE THREAD

**Issue by analog-cbarber** [conda/conda#13043]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Currently, you can install a package from a `.tar.bz2` or `.conda` file, but this only installs the package itself without any dependencies.

If you do install this way, there does not appear to be any automatic way to add the dependencies.

It would be nice if there was an option to install from a file along with dependencies.

For example:

```
conda install --deps foo-0.1.6-py_0.tar.bz2
```

Option could either be `--with-deps` for readability or `--deps` to go along with `--no-deps`

### Why is this needed?

If you have obtained or built a conda package that isn't already in a local conda-indexed directory
(e.g. conda-bld), you may want to installing into a test environment before deploying to a shared
location.

Currently, in order to do this, it seems you have have to put it into a locally indexed directory
(which could be temporary) and install from there.

### What should happen?

Should behave just as if installing package from a local channel.

### Additional Context

Probably only interesting to advanced users and developers creating specialized conda packaging tools.

**Comment by travishathaway** [comment]
Hi @analog-cbarber,

This could be a good candidate for a new feature. I'm not this is something the core development team will begin working on anytime soon though. We'd be happy to talk about the feature more or take a look at a pull request if anyone else out there is interested trying to implement it.

**Comment by analog-cbarber** [comment]
FYI, I have implemented this in my own tool for now and unless I am missing some
subtlety it just requires adding the package's dependencies.

https://zuzukin.github.io/whl2conda/latest/cli/whl2conda-install.html

**Comment by travishathaway** [comment]
@analog-cbarber,

Cool project! Thanks for sharing. That's going to be very helpful to use as a reference for anyone wishing to implement this feature request.

**Comment by analog-cbarber** [comment]
Yes, that is right. But it seems that conda is not happy if you remove the index after installing the package, while installing from the file is fine (but lacks the dependencies).

**Comment by analog-cbarber** [comment]
In the meantime you can install whl2conda and use `whl2conda install` for this. It is principally intended for use in testing packages built using whl2conda, but it should work.

**Comment by bilderbuchi** [comment]
Reproduction: 
* Download https://anaconda.org/conda-forge/pandas/2.2.3/download/win-64/pandas-2.2.3-py311hcf9f919_3.conda (or equivalent according to the platform you are on
* `conda create -n conda_13043 python=3.11`
* `conda install "C:\Users\myuser\Downloads\pandas-2.2.3-py311hcf9f919_3.conda"` This installs `pandas`, but nothing else
* `python -c "import pandas; print(pandas.__version__)"`
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\myuser\AppData\Local\mambaforge\envs\conda_13043\Lib\site-packages\pandas\__init__.py", line 19, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: No module named 'numpy'
pytz: No module named 'pytz'
dateutil: No module named 'dateutil'
```
This shows that the dependencies of pandas were not installed.

This is on Windows 11, conda 25.5.0
