### ISSUE TITLE
Conda obtains an incorrect json from binstar

### ISSUE THREAD

**Issue by mattions** [conda/conda#1311]
```
/home/gitlab-runner/miniconda
Fetching package metadata: ....

Remove the following packages in environment /home/gitlab-runner/miniconda/envs/moka_env:

The following packages will be REMOVED:

    cython:   0.21.2-py27_0
    freetype: 2.4.10-0     
    libpng:   1.5.13-1     
    openssl:  1.0.1k-1     
    pixman:   0.26.2-0     
    qt:       4.8.5-0      
    readline: 6.2-2        
    samtools: 1.1-2        
    sqlite:   3.8.4.1-1    
    system:   5.8-1        
    tabix:    0.2.6-0      
    tk:       8.5.18-0     
    yaml:     0.1.4-0      
    zlib:     1.2.8-0      

Unlinking packages ...
 |                                                                       |   0%[cython              ] |###                                              |   7%An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/gitlab-runner/miniconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 63, in main
    return args_func(args, parser)
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 104, in execute
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/home/gitlab-runner/miniconda/lib/python2.7/site-packages/conda/install.py", line 599, in unlink
    meta = json.load(fi)
  File "/home/gitlab-runner/miniconda/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/home/gitlab-runner/miniconda/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/home/gitlab-runner/miniconda/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/gitlab-runner/miniconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting object: line 212 column 70 (char 14281)
```

Conda Info

```
$$  conda info
Current conda install:

             platform : linux-64
        conda version : 3.9.1
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.5.3
     root environment : /home/gitlab-runner/miniconda  (read only)
  default environment : /home/gitlab-runner/miniconda
     envs directories : /home/mmattioni/.conda/envs
                        /home/mmattioni/envs
                        /home/gitlab-runner/miniconda/envs
        package cache : /home/mmattioni/.conda/envs/.pkgs
                        /home/mmattioni/envs/.pkgs
                        /home/gitlab-runner/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/free/noarch/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Without changing anything I manage to get it going again, so I think the problem is not in conda itself but it is in the interaction with binstar.

Because we run conda install as part of our CI job, I'm wondering if this could be due to same throttling or similar.

**Comment by mattions** [comment]
I can't replicate this with conda 3.10, so I'm going to close it for now.
