### ISSUE TITLE
EnvironmentNotWritableError and PermissionError: [Errno 13]

### ISSUE THREAD

**Issue by lcferme** [conda/conda#13133]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hello, 

This is gonna be a long story, I am afraid ...

It all started with me trying to install a package in a virtual environment to try out some new cool tool for work. Unfortunately, it was not solving the environment, so I looked around on the internet and  I read that this might be also due to the fact that I was using an old version of conda. I tried to update conda from the terminal, but I could not since I was getting this error message:

`EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: C:\ProgramData\Anaconda3`

Thus, I tried to run with admin privileges (I am using a workstation with other users) and I managed to create the environment and install the package I wanted to try out for a project. 

Unfortunately, I now have issues with using conda from my user account. Everytime I try to create an environment, for instance, I get the following error and report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 116, in install
        if context.use_only_tar_bz2:
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 775, in use_only_tar_bz2
        import conda_package_handling.api
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_package_handling\api.py", line 11, in <module>
        from .tarball import CondaTarBZ2 as _CondaTarBZ2
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_package_handling\tarball.py", line 6, in <module>
        from . import streaming, utils
      File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
      File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 846, in exec_module
      File "<frozen importlib._bootstrap_external>", line 982, in get_code
      File "<frozen importlib._bootstrap_external>", line 1039, in get_data
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\conda_package_handling\\streaming.py'

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create -n cellpose-env`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=sers/lcferme
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\
                          bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\
                          Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\
                          bin;C:\ProgramData\Anaconda3\condabin;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v11.2\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v11.2\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\S
                          ystem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Windows\Sys
                          tem32\OpenSSH;C:\Program Files\dotnet;C:\Program Files\NVIDIA
                          Corporation\Nsight Compute 2020.3.0;C:\Program Files (x86)\NVIDIA Corp
                          oration\PhysX\Common;C:\cuda\bin;C:\cuda\include;C:\cuda\lib\x64;C:\Pr
                          ogram Files\MATLAB\R2022b\bin;.;C:\Program Files\Docker\Docker\resourc
                          es\bin;C:\Users\lcferme\AppData\Local\Microsoft\WindowsApps;C:\Users\l
                          cferme\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\lcferme\A
                          ppData\Local\Programs\Git\cmd;C:\Users\lcferme\AppData\Local\GitHubDes
                          ktop\bin
             PSMODULEPATH=C:\Users\lcferme\Documents\WindowsPowerShell\Modules;C:\Program Files\
                          WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\M
                          odules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\lcferme\.condarc
 populated config files :
          conda version : 4.12.0
    conda-build version : 3.21.8
         python version : 3.9.12.final.0
       virtual packages : __cuda=12.0=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\ProgramData\Anaconda3  (read only)
      conda av data dir : C:\ProgramData\Anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\lcferme\.conda\pkgs
                          C:\Users\lcferme\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\lcferme\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\lcferme\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.9.12 Windows/10 Windows/10.0.20348
          administrator : False
             netrc file : None
           offline mode : False
```

I saw that issue #6678 reported a similar error, but the discussion was locked and I am  not sure what would be the best way to deal with it for me, given that there are other users of this computer. 

### Conda Info

as above

**Comment by travishathaway** [comment]
Hi @lcferme,

Thanks for reporting this issue. I've had the chance to take a look at it and am still trying to determine what exactly is going on. My guess is that somehow running conda as admin took away read access to all other users in that directory. The solution would then be to re-grant that read access.

Could you help us verify this by looking at the file permissions for this file?

```
C:\\ProgramData\\Anaconda3\\lib\\site-packages\\conda_package_handling\\streaming.py
```
