### ISSUE TITLE
Unable to find packages on clean miniconda installation

### ISSUE THREAD

**Issue by gbayarri** [conda/conda#13135]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi, I'm not sure if it's a conda bug or a bug in my computer, but a few days ago I started to have problems with mamba as described [here](https://stackoverflow.com/questions/69671703/why-does-pakku-crash-with-cannot-locate-native-library-libarchive-13-dylib-whi), so I did the brew install, the soft link and everything worked again for a few hours. Then it happened again and I wasn't able to fix it, so I completely removed my anaconda3 installation and created a fresh one.

And here the true problems started. Since then I've reinstalled conda 4 times (the last two were miniconda) and I'm completely unable to to almost anything: 

- Running mamba in the base environment (first operation after installing miniconda) returns this when trying to execute it:
```
$ mamba                                                                                                                           
Traceback (most recent call last):                                                                                                                          
  File "/Users/user/miniconda3/bin/mamba", line 7, in <module>                                                                                          
    from mamba.mamba import main                                                                                                                            
  File "/Users/user/miniconda3/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>                                                       
    import libmambapy as api                                                                                                                                
  File "/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>                                                
    raise e                                                                                                                                                 
  File "/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>                                                
    from libmambapy.bindings import *  # noqa: F401,F403                                                                                                    
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                       
ImportError: dlopen(/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib                                                                                                                                          
  Referenced from: /Users/user/miniconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/Users/user/miniconda3/lib/libarchive.13.dylib' (no such file), '/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/user/miniconda3/bin/../lib/libarchive.13.dylib' (no such file), '/Users/user/miniconda3/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file)
```
- conda search for a well known bioinformatics package returns this (the package exists, one of my coworkers with the same computer as mine can check it without problem):
```
$ conda search -c conda-forge gromacs
Loading channels: done
No match found for: gromacs. Search: *gromacs*
# Name                       Version           Build  Channel             
gromacswrapper                 0.8.2    pyhd8ed1ab_0  conda-forge         
gromacswrapper                 0.8.3    pyhd8ed1ab_0  conda-forge         
gromacswrapper                 0.8.4    pyhd8ed1ab_0  conda-forge         
gromacswrapper                 0.8.5    pyhd8ed1ab_0  conda-forge 
```
It looks like the problem is with the non-noarch packages
- Trying to downgrade the python version on the base environment:
```
$ conda install -c anaconda python==3.9
Error while loading conda entry point: conda-libmamba-solver (dlopen(/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/bindings.cpython-311-darwin.so, 0x0002): Library not loaded: @rpath/libarchive.13.dylib
  Referenced from: /Users/user/miniconda3/lib/libmamba.2.0.0.dylib
  Reason: tried: '/Users/user/miniconda3/lib/libarchive.13.dylib' (no such file), '/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/user/miniconda3/lib/python3.11/site-packages/libmambapy/../../../libarchive.13.dylib' (no such file), '/Users/user/miniconda3/bin/../lib/libarchive.13.dylib' (no such file), '/Users/user/miniconda3/bin/../lib/libarchive.13.dylib' (no such file), '/usr/local/lib/libarchive.13.dylib' (no such file), '/usr/lib/libarchive.13.dylib' (no such file))
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - python==3.9

Current channels:

  - https://conda.anaconda.org/anaconda/osx-arm64
  - https://conda.anaconda.org/anaconda/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

In my opinion it's a problem with the solver that can't find the packages that aren't noarch. 

Any idea of how to solve it?

### Conda Info

```shell
active environment : base
    active env location : /Users/user/miniconda3
            shell level : 1
       user config file : /Users/user/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=arm64
                          __osx=12.4=0
                          __unix=0=0
       base environment : /Users/user/miniconda3  (writable)
      conda av data dir : /Users/user/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-arm64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/anaconda/osx-arm64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/user/miniconda3/pkgs
                          /Users/user/.conda/pkgs
       envs directories : /Users/user/miniconda3/envs
                          /Users/user/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.11.5 Darwin/21.5.0 OSX/12.4
                UID:GID : 1147421021:1791188573
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /Users/user/.condarc <==
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
# packages in environment at /Users/user/miniconda3:
#
# Name                    Version                   Build  Channel
boltons                   23.0.0          py311hca03da5_0    defaults
brotlipy                  0.7.0           py311h80987f9_1002    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.0               h80987f9_0    defaults
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py311h80987f9_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.7.4          py311h267d04e_0    conda-forge
conda-content-trust       0.1.3           py311hca03da5_0    defaults
conda-libmamba-solver     23.5.0          py311hca03da5_0    defaults
conda-package-handling    2.1.0           py311hca03da5_0    defaults
conda-package-streaming   0.8.0           py311hca03da5_0    defaults
cryptography              39.0.1          py311h834c97f_2    defaults
fmt                       10.1.1               h1995070_0    conda-forge
icu                       68.1                 hc377ac9_0    defaults
idna                      3.4             py311hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               hf3e1bf2_1    defaults
libarchive                3.6.2                h62fee54_2    defaults
libcurl                   8.2.1                h3e2b118_0    defaults
libcxx                    16.0.6               h4653b0c_0    conda-forge
libedit                   3.1.20221030         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libexpat                  2.5.0                hb7217d7_1    conda-forge
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.16                 h1a28f6b_2    defaults
libmamba                  1.5.1                h6089622_0    conda-forge
libmambapy                1.5.1           py311h7cacacc_0    conda-forge
libnghttp2                1.52.0               h62f6fdd_1    defaults
libsolv                   0.7.24               ha614eb4_4    conda-forge
libsqlite                 3.43.0               hb31c410_0    conda-forge
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.10.3               h372ba2a_0    defaults
libzlib                   1.2.13               h53f4e23_5    conda-forge
lz4-c                     1.9.4                h313beb8_0    defaults
mamba                     1.5.1           py311hb045da1_0    conda-forge
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.1.3                h53f4e23_0    conda-forge
packaging                 23.0            py311hca03da5_0    defaults
pcre2                     10.37                h37e8eca_1    defaults
pip                       23.1.2          py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.4           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.5          h47c9636_0_cpython    conda-forge
python.app                3               py311h80987f9_0    defaults
python_abi                3.11                    4_cp311    conda-forge
readline                  8.2                  h1a28f6b_0    defaults
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.29.0          py311hca03da5_0    defaults
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
setuptools                67.8.0          py311hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
toolz                     0.12.0          py311hca03da5_0    defaults
tqdm                      4.65.0          py311hb6e6a13_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311hca03da5_0    defaults
wheel                     0.38.4          py311hca03da5_0    defaults
xz                        5.4.2                h80987f9_0    defaults
yaml-cpp                  0.7.0                hc377ac9_1    defaults
zlib                      1.2.13               h53f4e23_5    conda-forge
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

**Comment by gbayarri** [comment]
Partially fixed setting osx-64 though my computer is a mac M1:

`conda config --env --set subdir osx-64`

As I had arm64 set as architecture, conda was unable to find the non-arm packages (only the noarch ones).

After doing this, it worked until I started having problems with openssl. Probably because the miniconda I had installed was the Apple M1 version. 

Finally I've reinstalled miniconda from scratch (again) but this time downloading the **Intel x86** bash. I assume that now I'm running conda through rosetta.

I leave this issue opened because I would like to know if there is any way to mix the arm and intel versions. At this moment, most of the packages I'm working with don't have ARM version, but maybe in a future they will. But of course not all of them, so should I keep working with the Intel version?

**Comment by travishathaway** [comment]
Hi @gbayarri,

Thanks for filing this and providing that update. Unfortunately, there's no way to have both `osx-arm64` and `osx-64` packages in the same environment. Trying to do so will usually end up breaking things in fun and unexpected ways 😵.

Using the `subdir` setting is one way to do this, but I must warn you that this is an intentionally undocumented setting as it can lead to broken conda installs. I know from experience.

My personal solution is just having both an "arm64" and "intel" conda install on my computer. Not optimal, but it works well enough.

**Comment by gbayarri** [comment]
Hi @travishathaway ,

Thanks for your answer, but honestly, I don't know how to have two different conda installations in the same computer. Can you explain me how or provide a link to a tutorial?

Thanks again.

**Comment by travishathaway** [comment]
Hi @gbayarri,

Sorry for the delay! So, here's a quick summary of what I do on my Mac:

### Setup conda 64 bit

First, download the x86_64 version of conda

```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
```

Install it conda to `~/opt/conda-x86_64`:

```
bash Miniconda3-latest-MacOSX-x86_64.sh -b -p ~/opt/conda-x86_64
```

Initialize this conda for `zsh` shell:

```
~/opt/conda-x86_64/condabin/conda init zsh
```

That sets up conda x86_64 to be used with zsh.

 ### Setup conda arm64

Download the arm64 version of conda

```
curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh
```

Install it conda to `~/opt/conda-arm64`:

```
bash Miniconda3-latest-MacOSX-arm64.sh -b -p ~/opt/conda-arm64
```

Initialize this conda for `bash` shell:

```
~/opt/conda-x86_64/condabin/conda init bash
```

Going forward, you can now have `bash` be your conda-arm64 shell and `zsh` be your conda-x86_64 shell.

Like I said, this is not optimal. It would be nice to have tools to let us switch between these installs more seamlessly, but that's the best I could come up with 😅.

**Comment by gbayarri** [comment]
Ok, thank you very much! I will try.

Thanks again!
