### ISSUE TITLE
`MatchSpec` parser doesn't always define a `build` field

### ISSUE THREAD

**Issue by jaimergp** [conda/conda#13136]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Comes from https://github.com/conda/conda-libmamba-solver/issues/286#issuecomment-1729059506

Looks like `MatchSpec` parser is a bit too sensitive to formatting and won't define certain fields:

```python
from conda.models.match_spec import MatchSpec as M

# These should all return False gracefully

M("scipy=1.7.3=py37hd18d958_0").match(M("scipy =1.7.3"))  # works
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy 1.7.3"))   # fails
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy=1.7.3"))   # works
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy==1.7.3"))  # fails
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy ==1.7.3")) # fails
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy 1.7.3 *")) # fails
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy=1.7.3=*")) # fails
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy[version=1.7.3]")) # fails
M("scipy=1.7.3=py37hd18d958_0").match(M("scipy[version=1.7.3,build=*]")) # fails
```

Those failures can be `AttributeError`s and/or `KeyError`s. I would expect that the right-hand match spec (all valid) would define a `build=None`, but to my surprise the `fail` ones do not? It's unclear why single equals does define it but the others do not 🤷 

### Conda Info

```shell
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/test_user/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 23.7.5.dev126+gff7391c73  (current main)
    conda-build version : 3.26.1
         python version : 3.10.10.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.31=0
                          __linux=5.15.49=0
                          __unix=0=0
       base environment : /opt/conda  (read only)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-aarch64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/test_user/.conda/pkgs
       envs directories : /home/test_user/.conda/envs
                          /opt/conda/envs
               platform : linux-aarch64
             user-agent : conda/23.7.5.dev126+gff7391c73 requests/2.28.2 CPython/3.10.10 Linux/5.15.49-linuxkit-pr debian/11 glibc/2.31 solver/libmamba conda-libmamba-solver/23.7.1.dev15+gc154895.d20230919 libmambapy/1.5.1
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /opt/conda/.condarc <==
channels:
  - conda-forge
```

### Conda list

```shell
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_openmp_mutex             4.5                       2_gnu    conda-forge
amqp                      5.1.1              pyhd8ed1ab_0    conda-forge
anaconda-client           1.11.1             pyhd8ed1ab_1    conda-forge
anaconda-project          0.11.1             pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
attrs                     22.2.0             pyh71513ae_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
backports.zoneinfo        0.2.1           py310h4c7bcd0_7    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
billiard                  4.1.0           py310hb299538_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boto3                     1.26.109           pyhd8ed1ab_0    conda-forge
botocore                  1.29.109           pyhd8ed1ab_0    conda-forge
brotlipy                  0.7.0           py310h761cc84_1005    conda-forge
bzip2                     1.0.8                hf897c2e_4    conda-forge
c-ares                    1.18.1               hf897c2e_0    conda-forge
ca-certificates           2023.7.22            hcefe29a_0    conda-forge
cachecontrol              0.13.1             pyhd8ed1ab_0    conda-forge
cachecontrol-with-filecache 0.13.1             pyhd8ed1ab_0    conda-forge
cachy                     0.3.0              pyhd8ed1ab_1    conda-forge
celery                    5.3.4              pyhd8ed1ab_1    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310hf0c4615_3    conda-forge
cfgv                      3.3.1              pyhd8ed1ab_0    conda-forge
chardet                   5.1.0           py310hbbe02a8_0    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
click                     8.1.3           unix_pyhd8ed1ab_2    conda-forge
click-default-group       1.2.4              pyhd8ed1ab_0    conda-forge
click-didyoumean          0.3.0              pyhd8ed1ab_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
click-repl                0.3.0              pyhd8ed1ab_0    conda-forge
clikit                    0.6.2              pyhd8ed1ab_2    conda-forge
clyent                    1.2.2                      py_1    conda-forge
collect-upstream-conda-tests 0.0.1                    pypi_0    pypi
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.7.4.dev126+gcf7470c50           dev_0    <develop>
conda-build               3.26.1          py310h4c7bcd0_0    conda-forge
conda-index               0.2.3              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     23.7.1.dev15+gc154895.d20230919          pypi_0    pypi
conda-lock                2.3.0              pyhd8ed1ab_0    conda-forge
conda-pack                0.7.0              pyh6c4a22f_0    conda-forge
conda-package-handling    2.0.2              pyh38be061_0    conda-forge
conda-package-streaming   0.7.0              pyhd8ed1ab_1    conda-forge
conda-verify              3.1.1           py310hbbe02a8_1006    conda-forge
coverage                  7.2.3           py310h734f5e8_0    conda-forge
crashtest                 0.4.1              pyhd8ed1ab_0    conda-forge
cryptography              40.0.1          py310he4ba0b1_0    conda-forge
curl                      8.2.1                h4e8248e_0    conda-forge
dbus                      1.13.6               h12b9eeb_3    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distlib                   0.3.6              pyhd8ed1ab_0    conda-forge
ensureconda               1.4.3              pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.1              pyhd8ed1ab_0    conda-forge
execnet                   1.9.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hd600fc2_1    conda-forge
filelock                  3.11.0             pyhd8ed1ab_0    conda-forge
flake8                    6.0.0              pyhd8ed1ab_0    conda-forge
flask                     2.2.5              pyhd8ed1ab_0    conda-forge
fmt                       10.1.1               h2a328a1_0    conda-forge
freetype                  2.12.1               hbbbf32d_1    conda-forge
future                    0.18.3             pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               ha18d298_0    conda-forge
git                       2.40.0          pl5321h7e2208b_1    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.36             pyhd8ed1ab_0    conda-forge
glob2                     0.7                        py_0    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icu                       72.1                 hcf00150_0    conda-forge
identify                  2.5.22             pyhd8ed1ab_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.2.0              pyha770c72_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jaraco.classes            3.3.0              pyhd8ed1ab_0    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.32               pyhd8ed1ab_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.0           py310h4c7bcd0_0    conda-forge
keyring                   23.9.3          py310h4c7bcd0_1    conda-forge
keyutils                  1.6.1                h4e544f5_0    conda-forge
kombu                     5.3.2           py310h4c7bcd0_0    conda-forge
krb5                      1.21.2               hc419048_0    conda-forge
lcms2                     2.15                 h3e0bdec_1    conda-forge
ld_impl_linux-aarch64     2.40                 h2d8c526_0    conda-forge
lerc                      4.0.0                h4de3ea5_0    conda-forge
libarchive                3.6.2                hc81d4a0_0    conda-forge
libcurl                   8.2.1                h4e8248e_0    conda-forge
libdeflate                1.18                 hb4cce97_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hd600fc2_1    conda-forge
libffi                    3.4.2                h3557bc0_5    conda-forge
libgcc-ng                 12.2.0              h607ecd0_19    conda-forge
libglib                   2.78.0               h0464669_0    conda-forge
libgomp                   12.2.0              h607ecd0_19    conda-forge
libiconv                  1.17                 h9cdd2b7_0    conda-forge
libjpeg-turbo             2.1.5.1              hb4cce97_0    conda-forge
liblief                   0.12.3               h4de3ea5_0    conda-forge
libmamba                  1.5.1                h604a1c0_0    conda-forge
libmambapy                1.5.1           py310h5938bc3_0    conda-forge
libnghttp2                1.52.0               h250e5c5_0    conda-forge
libnsl                    2.0.0                hf897c2e_0    conda-forge
libpng                    1.6.39               hf9034f9_0    conda-forge
libsolv                   0.7.24               hd84c7bf_4    conda-forge
libsqlite                 3.40.0               hf9034f9_0    conda-forge
libssh2                   1.11.0               h492db2e_0    conda-forge
libstdcxx-ng              12.2.0              hc13a102_19    conda-forge
libtiff                   4.5.0                h536c0eb_6    conda-forge
libuuid                   2.38.1               hb4cce97_0    conda-forge
libwebp-base              1.3.0                hb4cce97_0    conda-forge
libxcb                    1.13              h3557bc0_1004    conda-forge
libxml2                   2.10.3               h430b14f_6    conda-forge
libzlib                   1.2.13               h4e544f5_4    conda-forge
lz4-c                     1.9.4                hd600fc2_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markupsafe                2.1.2           py310h734f5e8_0    conda-forge
mccabe                    0.7.0              pyhd8ed1ab_0    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
msgpack-python            1.0.5           py310hb43b7d6_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  headf329_1    conda-forge
nodeenv                   1.7.0              pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.0                h9508984_2    conda-forge
openssl                   3.1.2                h31becfc_0    conda-forge
packaging                 23.0               pyhd8ed1ab_0    conda-forge
pastel                    0.2.1              pyhd8ed1ab_0    conda-forge
patch                     2.7.6             hf897c2e_1002    conda-forge
patchelf                  0.17.2               h884eca8_0    conda-forge
pcre2                     10.40                he7b27c6_0    conda-forge
perl                      5.32.1          2_hf897c2e_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pillow                    9.5.0           py310hcf0f7da_0    conda-forge
pip                       23.2.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.2.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0              pyhd8ed1ab_5    conda-forge
pre-commit                3.2.2              pyha770c72_0    conda-forge
prompt-toolkit            3.0.39             pyha770c72_0    conda-forge
prompt_toolkit            3.0.39               hd8ed1ab_0    conda-forge
psutil                    5.9.4           py310h761cc84_0    conda-forge
pthread-stubs             0.4               hb9de7d4_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.11.0             pyh6c4a22f_0    conda-forge
py-lief                   0.12.3          py310h130cc07_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycodestyle               2.10.0             pyhd8ed1ab_0    conda-forge
pycosat                   0.6.4           py310h761cc84_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycrypto                  2.6.1           py310h7cee911_1006    conda-forge
pydantic                  1.10.12         py310hb299538_1    conda-forge
pyflakes                  3.0.1              pyhd8ed1ab_0    conda-forge
pylev                     1.4.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyrsistent                0.19.3          py310h734f5e8_0    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
pytest                    7.2.2              pyhd8ed1ab_0    conda-forge
pytest-cov                4.0.0              pyhd8ed1ab_0    conda-forge
pytest-mock               3.10.0             pyhd8ed1ab_0    conda-forge
pytest-rerunfailures      11.1.2             pyhd8ed1ab_0    conda-forge
pytest-split              0.8.0              pyhd8ed1ab_0    conda-forge
pytest-timeout            2.1.0              pyhd8ed1ab_0    conda-forge
pytest-xdist              3.2.1              pyhd8ed1ab_0    conda-forge
pytest-xprocess           0.22.2             pyhd8ed1ab_0    conda-forge
python                    3.10.10         ha43d526_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.16.3             pyhd8ed1ab_0    conda-forge
python-libarchive-c       4.0             py310h4c7bcd0_2    conda-forge
python-tzdata             2023.3             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0             py310h761cc84_5    conda-forge
readline                  8.2                  h8fc344f_1    conda-forge
reproc                    14.2.4               hb4cce97_0    conda-forge
reproc-cpp                14.2.4               hd600fc2_0    conda-forge
requests                  2.28.2             pyhd8ed1ab_1    conda-forge
responses                 0.21.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               hc770f70_2    conda-forge
ruamel.yaml               0.17.21         py310hb89b984_3    conda-forge
ruamel.yaml.clib          0.2.7           py310hb89b984_1    conda-forge
ruamel_yaml               0.15.80         py310h761cc84_1008    conda-forge
s3transfer                0.6.0              pyhd8ed1ab_0    conda-forge
secretstorage             3.3.3           py310hbbe02a8_1    conda-forge
setuptools                65.6.3             pyhd8ed1ab_0    conda-forge
setuptools-scm            7.1.0              pyhd8ed1ab_0    conda-forge
setuptools_scm            7.1.0                hd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.40.0               h69ca7e5_0    conda-forge
tk                        8.6.12               hd8af866_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomlkit                   0.12.1             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310hdc54845_1    conda-forge
tqdm                      4.65.0             pyhd8ed1ab_1    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.5.0                hd8ed1ab_0    conda-forge
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ukkonen                   1.0.1           py310hb15e014_3    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vine                      5.0.0              pyhd8ed1ab_1    conda-forge
virtualenv                20.21.0            pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
werkzeug                  2.2.3              pyhd8ed1ab_0    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
xdoctest                  1.1.1              pyhd8ed1ab_0    conda-forge
xorg-libxau               1.0.9                h3557bc0_0    conda-forge
xorg-libxdmcp             1.1.3                h3557bc0_0    conda-forge
xz                        5.2.6                h9cdd2b7_0    conda-forge
yaml                      0.2.5                hf897c2e_2    conda-forge
yaml-cpp                  0.7.0                h4de3ea5_2    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.19.0          py310hde4b81c_1    conda-forge
zstd                      1.5.2                h44f6412_6    conda-forge
```

### Additional Context

In the original report, this is triggered by a `pinned` file that happens to work with `classic`. I wonder if the fix is simply adding a default return in this line:

https://github.com/conda/conda/blob/af87ce22a53b8b29d45b2dd21c4acb509a856df1/conda/models/match_spec.py#L262

```
#12 32.61     Traceback (most recent call last):
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
#12 32.61         return func(*args, **kwargs)
#12 32.61                ^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/cli/main.py", line 84, in main_subshell
#12 32.61         exit_code = do_call(args, p)
#12 32.61                     ^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 126, in do_call
#12 32.61         return getattr(module, func_name)(args, parser)
#12 32.61                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/notices/core.py", line 123, in wrapper
#12 32.61         return func(*args, **kwargs)
#12 32.61                ^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/cli/main_install.py", line 22, in execute
#12 32.61         install(args, parser, "install")
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/cli/install.py", line 309, in install
#12 32.61         unlink_link_transaction = solver.solve_for_transaction(
#12 32.61                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 153, in solve_for_transaction
#12 32.61         unlink_precs, link_precs = self.solve_for_diff(
#12 32.61                                    ^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 214, in solve_for_diff
#12 32.61         final_precs = self.solve_final_state(
#12 32.61                       ^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda_libmamba_solver/solver.py", line 200, in solve_final_state
#12 32.61         out_state = self._solving_loop(in_state, out_state, index)
#12 32.61                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda_libmamba_solver/solver.py", line 234, in _solving_loop
#12 32.61         solved = self._solve_attempt(in_state, out_state, index)
#12 32.61                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda_libmamba_solver/solver.py", line 319, in _solve_attempt
#12 32.61         out_state.prepare_specs(index)
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda_libmamba_solver/state.py", line 597, in prepare_specs
#12 32.61         self._prepare_for_add(index)
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda_libmamba_solver/state.py", line 688, in _prepare_for_add
#12 32.61         if sis.requested[name].match(spec):
#12 32.61            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/models/match_spec.py", line 250, in match
#12 32.61         if not self._match_individual(rec, field_name, v):
#12 32.61                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61       File "/opt/conda/lib/python3.11/site-packages/conda/models/match_spec.py", line 255, in _match_individual
#12 32.61         val = getattr(record, field_name)
#12 32.61               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#12 32.61     AttributeError: 'MatchSpec' object has no attribute 'build'
```

This is a good case for adding some validation to the `conda-meta/pinned` file.

**Comment by jaimergp** [comment]
Nah, wait, `MatchSpec.version` is defined but `MatchSpec.build` is never. That function should be using a default with `MatchSpec.get(<field>)`. That said, `MatchSpec.match()` is meant for `PackageRecords`, not other `MatchSpec` objects.
