### ISSUE TITLE
Unable to install package due to `ImportError: libarchive.so.13`

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [conda/conda#13148]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Recently, when trying to install a conda-forge package (fenics) with:

```
conda install -c conda-forge fenics
```

or 
```
mamba install -c conda-forge fenics
```

We get the following error:

```
2023-09-26 11:56:16.351Z: #6 0.701 Traceback (most recent call last):
#6 0.701   File "/opt/conda/bin/mamba", line 7, in <module>
#6 0.701     from mamba.mamba import main
#6 0.701   File "/opt/conda/lib/python3.11/site-packages/mamba/mamba.py", line 49, in <module>
#6 0.702     import libmambapy as api
#6 0.702   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 7, in <module>
#6 0.702     raise e
#6 0.702   File "/opt/conda/lib/python3.11/site-packages/libmambapy/__init__.py", line 4, in <module>
#6 0.702     from libmambapy.bindings import *  # noqa: F401,F403
#6 0.702     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#6 0.702 ImportError: libarchive.so.13: cannot open shared object file: No such file or directory
```

Our Dockerfile is:

```Dockerfile
FROM mcr.microsoft.com/vscode/devcontainers/miniconda:0-3

RUN conda install -c conda-forge mamba
RUN mamba install -c conda-forge fenics  # <-- fails here

```

### Conda Info

```shell
active environment : None
            shell level : 0
       user config file : /home/vscode/.condarc
 populated config files : 
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/vscode/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/vscode/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.4 Linux/5.15.0-1041-azure debian/11 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
boltons                   23.0.0          py311h06a4308_0    defaults
brotlipy                  0.7.0           py311h5eee18b_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.0               h5eee18b_0    defaults
ca-certificates           2023.08.22           h06a4308_0    defaults
certifi                   2023.7.22       py311h06a4308_0    defaults
cffi                      1.15.1          py311h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.7.4          py311h06a4308_0    defaults
conda-content-trust       0.2.0           py311h06a4308_0    defaults
conda-libmamba-solver     23.5.0          py311h06a4308_0    defaults
conda-package-handling    2.1.0           py311h06a4308_0    defaults
conda-package-streaming   0.8.0           py311h06a4308_0    defaults
cryptography              41.0.3          py311hdda0065_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcurl                   8.1.1                h251f7ec_1    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.4.1                h2dafd23_1    defaults
libmambapy                1.4.1           py311h2dafd23_1    defaults
libnghttp2                1.52.0               h2d74bed_1    defaults
libsolv                   0.7.22               he621ea3_0    defaults
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.3               hcbfbd50_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.10               h7f8727e_2    defaults
packaging                 23.0            py311h06a4308_0    defaults
pcre2                     10.37                he7ceb23_1    defaults
pip                       23.1.2          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.4           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.4               h955ad1f_0    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                67.8.0          py311h06a4308_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0          py311h06a4308_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311h06a4308_0    defaults
wheel                     0.38.4          py311h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml-cpp                  0.7.0                h295c915_1    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

### Additional Context

@jhdark

**Comment by jezdez** [comment]
Unfortunately, this is an issue in the `libarchive` package in conda-forge, documented and worked on in https://github.com/conda-forge/libarchive-feedstock/issues/69.

**Comment by RemDelaporteMathurin** [comment]
@jezdez thanks for replying so quickly.

I find it a bit odd since this issue was opened on Jun 10 and we were able to install this package in July without any issue.

We realised that downgrading conda to 23.5.2 fixed the issue

**Comment by jezdez** [comment]
@jaimergp has more details about this

**Comment by jaimergp** [comment]
See https://github.com/conda/conda-libmamba-solver/issues/283.

You are starting with a Docker image preconfigured for `defaults`, but adding `mamba` from `conda-forge`. At that point the solver will try to get `mamba` and its dependencies from both conda-forge and defaults. The incompatibility arises whenever libmamba and libarchive come from different channels, and sometimes the solution will contain a mix. Depending on the repodata constrains (which can change often), one solution might have required mixed channels, and in other occasions it has not, hence the different behaviours you have observed.

**Comment by RemDelaporteMathurin** [comment]
Thanks for the explanation!
