### ISSUE TITLE
error - conda install libpng

### ISSUE THREAD

**Issue by levy5674** [conda/conda#1314]
I'm getting an error when conda tries to install libpng.     Repro steps, traceback, and conda info are below:

```
levy$ conda create -n bug python
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/levy/anaconda/envs/bug:

The following NEW packages will be INSTALLED:

    openssl:    1.0.1k-1    
    pip:        6.1.1-py27_0
    python:     2.7.9-1     
    readline:   6.2-2       
    setuptools: 15.2-py27_0 
    sqlite:     3.8.4.1-1   
    tk:         8.5.18-0    
    zlib:       1.2.8-0     

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|#######################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate bug
#
# To deactivate this environment, use:
# $ source deactivate
#
levy$ source activate bug
discarding /Users/levy/anaconda/bin from PATH
prepending /Users/levy/anaconda/envs/bug/bin to PATH
(bug)levy$ conda install libpng
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/levy/anaconda/envs/bug:

The following NEW packages will be INSTALLED:

    libpng: 1.5.13-1

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the                                                                 |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/levy/anaconda/envs/bug/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in main
    args_func(args, p)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 212, in args_func
    args.func(args, p)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 609, in inner
    return func(args, parser)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 51, in execute
    install.install(args, parser, 'install')
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 93, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 89, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/install.py", line 550, in link
    _link(src, dst, lt)
  File "/Users/levy/anaconda/lib/python2.7/site-packages/conda/install.py", line 143, in _link
    shutil.copy2(src, dst)
  File "/Users/levy/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/levy/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/levy/anaconda/pkgs/libpng-1.5.13-1/bin/libpng-config'
(bug)levy$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.11.0
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.6.2
     root environment : /Users/levy/anaconda  (writable)
  default environment : /Users/levy/anaconda/envs/bug
     envs directories : /Users/levy/anaconda/envs
        package cache : /Users/levy/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by soapy1** [comment]
Can't reproduce this on the newest version of conda. Please `conda update conda` if this is still an issue
