### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 975: invalid continuation byte when initializing conda

### ISSUE THREAD

**Issue by nickhir** [conda/conda#13201]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to install miniconda on a HPC and everything works smoothly until I am asked if I "wish the installer to initialize Miniconda3". If I type in yes, I get the following error report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 16, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, p)
                    ^^^^^^^^^^^^^^^^
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 126, in do_call
        return getattr(module, func_name)(args, parser)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/cli/main_init.py", line 32, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 134, in initialize
        run_plan(plan2)
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 794, in run_plan
        result = globals()[step["function"]](
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 1458, in init_sh_user
        rc_content = fh.read()
                     ^^^^^^^^^
      File "<frozen codecs>", line 322, in decode
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 975: invalid continuation byte

`$ /rds/user/nh608/hpc-work/software/miniconda3/lib/python3.11/site-packages/conda/__main__.py init`

  environment variables:
             ACLOCAL_PATH=/usr/local/software/master/python/3.6/share/aclocal:/usr/local/softwar
                          e/master/cmake/latest/share/aclocal
                 CIO_TEST=<not set>
                CLASSPATH=/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.25
                          4/linux/daal/lib/daal.jar:/usr/local/Cluster-Apps/intel/2020.2/compile
                          rs_and_libraries_2020.2.254/linux/mpi/intel64/lib/mpi.jar
        CMAKE_PREFIX_PATH=/usr/local/software/master/python/3.6/:/usr/local/software/master/gcc/
                          6/:/usr/local/software/master/cmake/latest/
               CONDA_ROOT=/rds/user/nh608/hpc-work/software/miniconda3
                    CPATH=/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/intel-mkl-
                          2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/mkl/include:/usr/local/software/archive/linux-scientific7-
                          x86_64/gcc-9/python-3.6.8-
                          57jkyev2uale6my2nunbcfilmdjethl7/include/python3.6m:/usr/local/Cluster
                          -Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/daal/inclu
                          de:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2
                          .254/linux/ipp/include:/usr/local/Cluster-Apps/intel/2020.2/compilers_
                          and_libraries_2020.2.254/linux/tbb/include:/usr/local/Cluster-
                          Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/include
       CPLUS_INCLUDE_PATH=/usr/local/software/master/python/3.6/include:/usr/local/software/mast
                          er/gcc/6/include
           CURL_CA_BUNDLE=<not set>
           C_INCLUDE_PATH=/usr/local/software/master/python/3.6/include:/usr/local/software/mast
                          er/gcc/6/include
         FI_PROVIDER_PATH=/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.25
                          4/linux/mpi/intel64/libfabric/lib/prov
                 INFOPATH=/usr/local/Cluster-
                          Apps/intel/2020.2/documentation_2020/en/debugger/gdb-ia/info/
               LD_PRELOAD=<not set>
             LIBRARY_PATH=/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/intel-mkl-
                          2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/tbb/lib/intel64_lin/gcc4.7:/usr/local/software/archive/linux-
                          scientific7-x86_64/gcc-9/intel-mkl-2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/compiler/lib/intel64_lin:/usr/local/software/archive/linux-
                          scientific7-x86_64/gcc-9/intel-mkl-2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/mkl/lib/intel64_lin:/usr/local/software/master/python/3.6/lib64:/u
                          sr/local/software/master/python/3.6/lib:/usr/local/software/master/gcc
                          /6/lib64:/usr/local/software/master/gcc/6/lib:/usr/local/Cluster-Apps/
                          intel/2020.2/compilers_and_libraries_2020.2.254/linux/daal/lib/intel64
                          _lin:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020
                          .2.254/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/usr/local/Cluster-App
                          s/intel/2020.2/compilers_and_libraries_2020.2.254/linux/daal/../tbb/li
                          b/intel64_lin/gcc4.8:/usr/local/Cluster-Apps/intel/2020.2/compilers_an
                          d_libraries_2020.2.254/linux/ipp/lib/intel64:/usr/local/Cluster-Apps/i
                          ntel/2020.2/compilers_and_libraries_2020.2.254/linux/ipp/../tbb/lib/in
                          tel64/gcc4.8:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_librar
                          ies_2020.2.254/linux/tbb/lib/intel64/gcc4.8:/usr/local/Cluster-Apps/in
                          tel/2020.2/compilers_and_libraries_2020.2.254/linux/mpi/intel64/libfab
                          ric/lib:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2
                          020.2.254/linux/tbb/lib/intel64_lin/gcc4.7:/usr/local/Cluster-Apps/int
                          el/2020.2/compilers_and_libraries_2020.2.254/linux/compiler/lib/intel6
                          4_lin:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_202
                          0.2.254/linux/mkl/lib/intel64_lin
                  MANPATH=/usr/local/software/master/python/3.6/share/man:/usr/local/software/ma
                          ster/python/3.6/man:/usr/local/Cluster-Apps/ceuadmin/R/4.2.2/share/man
                          :/usr/local/software/master/gcc/6/share/man:/usr/local/Cluster-
                          Apps/intel/2020.2/documentation_2020/en/debugger/gdb-
                          ia/man/:/usr/local/Cluster-Apps/intel/2020.2/man/common:/usr/local/sof
                          tware/global/man:/usr/local/Cluster-Apps/turbovnc/2.0.1/man:/usr/local
                          /software/slurm/current/share/man:/usr/share/man:
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/local/software/sp
                          ack/current/share/spack/tcl/linux-
                          rhel7-x86_64:/usr/local/software/modulefiles:/usr/local/Cluster-
                          Config/modulefiles
                  NLSPATH=/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/intel-mkl-
                          2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/mkl/lib/intel64_lin/locale/%l_%t/%N:/usr/local/Cluster-Apps/intel/
                          2020.2/debugger_2020/gdb/intel64/share/locale/%l_%t/%N:/usr/local/Clus
                          ter-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/lib
                          /intel64_lin/locale/%l_%t/%N:/usr/local/Cluster-Apps/intel/2020.2/comp
                          ilers_and_libraries_2020.2.254/linux/compiler/lib/intel64/locale/%l_%t
                          /%N
      OLD_LD_LIBRARY_PATH=/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/intel-mkl-
                          2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/tbb/lib/intel64_lin/gcc4.7:/usr/local/software/archive/linux-
                          scientific7-x86_64/gcc-9/intel-mkl-2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/compiler/lib/intel64_lin:/usr/local/software/archive/linux-
                          scientific7-x86_64/gcc-9/intel-mkl-2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/mkl/lib/intel64_lin:/usr/local/software/master/python/3.6/lib64:/u
                          sr/local/software/master/python/3.6/lib:/usr/local/Cluster-Apps/ceuadm
                          in/R/4.2.2/lib64/R/lib:/usr/local/software/master/gcc/6/lib64:/usr/loc
                          al/software/master/gcc/6/lib:/usr/local/Cluster-Apps/intel/2020.2/comp
                          ilers_and_libraries_2020.2.254/linux/daal/lib/intel64_lin:/usr/local/C
                          luster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/daal
                          /../tbb/lib/intel64_lin/gcc4.4:/usr/local/Cluster-Apps/intel/2020.2/co
                          mpilers_and_libraries_2020.2.254/linux/daal/../tbb/lib/intel64_lin/gcc
                          4.8:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.
                          2.254/linux/ipp/lib/intel64:/usr/local/Cluster-Apps/intel/2020.2/compi
                          lers_and_libraries_2020.2.254/linux/ipp/../tbb/lib/intel64/gcc4.8:/usr
                          /local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/li
                          nux/tbb/lib/intel64/gcc4.8:/usr/local/Cluster-
                          Apps/intel/2020.2/debugger_2020/python/intel64/lib:/usr/local/Cluster-
                          Apps/intel/2020.2/debugger_2020/libipt/intel64/lib:/usr/local/Cluster-
                          Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mpi/intel64
                          /libfabric/lib:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libr
                          aries_2020.2.254/linux/mpi/intel64/lib/release:/usr/local/Cluster-Apps
                          /intel/2020.2/compilers_and_libraries_2020.2.254/linux/mpi/intel64/lib
                          :/usr/local/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.2
                          54/linux/tbb/lib/intel64_lin/gcc4.7:/usr/local/Cluster-Apps/intel/2020
                          .2/compilers_and_libraries_2020.2.254/linux/mkl/lib/intel64_lin:/usr/l
                          ocal/Cluster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linu
                          x/compiler/lib/intel64_lin:/usr/local/software/global/lib:/usr/local/s
                          oftware/vgl/3.1/64/lib64:/usr/local/software/vgl/3.1/64/opencl/lib:/us
                          r/local/software/slurm/current/lib
                     PATH=/usr/local/software/master/python/3.6/bin:/usr/local/Cluster-
                          Apps/ceuadmin/rstudio/2022.12.0+353:/usr/local/Cluster-
                          Apps/ceuadmin/R/4.2.2/bin:/usr/local/Cluster-
                          Apps/ceuadmin/R/4.2.2/lib64/R/bin:/usr/local/Cluster-Apps/texlive/2015
                          /bin/x86_64-
                          linux:/usr/local/software/master/gcc/6/bin:/usr/local/software/master/
                          cmake/latest/bin:/usr/local/Cluster-
                          Apps/intel/2020.2/debugger_2020/gdb/intel64/bin:/usr/local/Cluster-App
                          s/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mpi/intel64/li
                          bfabric/bin:/usr/local/Cluster-Apps/intel/2020.2/compilers_and_librari
                          es_2020.2.254/linux/mpi/intel64/bin:/usr/local/Cluster-Apps/intel/2020
                          .2/compilers_and_libraries_2020.2.254/linux/bin/intel64:/usr/local/Clu
                          ster-Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/bin:/u
                          sr/local/software/global/bin:/opt/singularity/bin:/usr/local/Cluster-A
                          pps/singularity/images:/usr/local/software/vgl/3.1/64/bin:/usr/local/C
                          luster-Apps/turbovnc/2.0.1/bin:/usr/local/software/slurm/current/sbin:
                          /usr/local/software/slurm/current/bin:/usr/lib64/qt-
                          3.3/bin:/home/nh608/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:
                          /usr/sbin:.:/home/nh608/bin
          PKG_CONFIG_PATH=/usr/local/software/archive/linux-scientific7-x86_64/gcc-9/intel-mkl-
                          2020.1.217-
                          daoabwrh3hmki2sfkvbm34nozs6ehxy5/compilers_and_libraries_2020.1.217/li
                          nux/mkl/bin/pkgconfig:/usr/local/software/master/python/3.6/lib/pkgcon
                          fig:/usr/local/software/master/gcc/6/lib/pkgconfig:/usr/local/Cluster-
                          Apps/intel/2020.2/compilers_and_libraries_2020.2.254/linux/mkl/bin/pkg
                          config
  PYTHONDONTWRITEBYTECODE=1
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/nh608/.condarc
 populated config files :
          conda version : 23.5.2
    conda-build version : not installed
         python version : 3.11.4.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /rds/user/nh608/hpc-work/software/miniconda3  (writable)
      conda av data dir : /rds/user/nh608/hpc-work/software/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /rds/user/nh608/hpc-work/software/miniconda3/pkgs
                          /home/nh608/.conda/pkgs
       envs directories : /rds/user/nh608/hpc-work/software/miniconda3/envs
                          /home/nh608/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.2 requests/2.29.0 CPython/3.11.4 Linux/3.10.0-1160.95.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 45661:45668
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

I am using the latest version of the installer (SHA256 hash: `634d76df5e489c44ade4085552b97bebc786d49245ed1a830022b0b406de5817`).

I am very grateful for any insights or help!
Cheers!

### Conda Info

```shell
`conda: command not found` since installation failed
```

### Conda Config

```shell
`conda: command not found` since installation failed
```

### Conda list

```shell
`conda: command not found` since installation failed
```

**Comment by dholth** [comment]
It prints the error message in the issue title without giving a traceback?

**Comment by nickhir** [comment]
What do you mean? I posted the entire error message in the main text

**Comment by dholth** [comment]
I see `UnicodeDecodeError` in the issue title but not in the main text.

**Comment by nickhir** [comment]
You are completely right... the error message is in the title and appeared right above the output I have posted. Sorry about that

**Comment by nickhir** [comment]
I have edited the issue to include the full error report.

**Comment by nickhir** [comment]
Any ideas how to tackle this issue?

**Comment by dholth** [comment]
It looks like it's trying to add conda's init code to ~/.bash_profile https://github.com/conda/conda/blob/23.5.2/conda/core/initialize.py#L1452-L1462

And finds non-unicode when trying to read bash_profile. Open the file with an editor. Is there anything unusual in your .bash_profile that can be fixed?

Conda wants to add [this template to the profile.](https://github.com/conda/conda/blob/23.5.2/conda/core/initialize.py#L1423-L1448
)
