### ISSUE TITLE
Error when using custom platform/subdir with an extra dash (e.g. `linux-64-2`)

### ISSUE THREAD

**Issue by calebzulawski** [conda/conda#13206]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

It errors at this line:
https://github.com/conda/conda/blob/fa57da0d2105b091d5ddffe50e379c8581b4d475/conda/core/index.py#L185

```
Traceback (most recent call last):
  File "conda/exceptions.py", line 1118, in __call__
  File "conda/cli/main.py", line 69, in main_subshell
  File "conda/cli/conda_argparse.py", line 91, in do_call
  File "conda/notices/core.py", line 109, in wrapper
  File "conda/cli/main_create.py", line 41, in execute
  File "conda/cli/install.py", line 264, in install
  File "conda/core/solve.py", line 136, in solve_for_transaction
  File "conda/core/solve.py", line 179, in solve_for_diff
  File "conda/core/solve.py", line 284, in solve_final_state
  File "conda/common/io.py", line 84, in decorated
  File "conda/core/solve.py", line 423, in _collect_all_metadata
  File "conda/core/index.py", line 175, in _supplement_index_with_system
  File "conda/plugins/manager.py", line 77, in get_hook_results
  File "conda/plugins/manager.py", line 78, in <genexpr>
  File "conda/plugins/virtual_packages/archspec.py", line 10, in conda_virtual_packages
  File "conda/core/index.py", line 196, in get_archspec_name
ValueError: too many values to unpack (expected 2)
```

### Additional Context

I'm using `conda-lock` installed via `mamba`, which is why I'm missing some of the conda context.  `conda-lock` is installing conda somewhere, I'm not sure the version.

My `.condarc` has
```
platform: linux-64-cxx03
```

**Comment by travishathaway** [comment]
@calebzulawski,

Please see the discussion in the pull request I opened. There is still an ongoing discussion around the best possible solution.
