### ISSUE TITLE
Fresh install of Pandas gives AttributeError: 'module' object has no attribute 'getmembers'

### ISSUE THREAD

**Issue by baharev** [conda/conda#1321]
I downloaded the latest miniconda3 as of May 09 and installed everything from scratch:

```bash
chmod +x Miniconda3-latest-Linux-x86_64.sh 
./Miniconda3-latest-Linux-x86_64.sh 
export PATH=/home/ali/miniconda3/bin:$PATH
conda create -n sasa python=3.4
source activate sasa 
conda install matplotlib 
conda install scipy 
conda install scikit-learn
conda install scikit-image 
conda install ipython ipython-notebook ipython-qtconsole
conda install pandas 
python -c 'import pandas'
```

which gives:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ali/miniconda3/envs/sasa/lib/python3.4/site-packages/pandas/__init__.py", line 62, in <module>
    import pandas.util.testing
  File "/home/ali/miniconda3/envs/sasa/lib/python3.4/site-packages/pandas/util/testing.py", line 1786, in <module>
    for name, obj in inspect.getmembers(sys.modules[__name__]):
AttributeError: 'module' object has no attribute 'getmembers'
```

Did I do something wrong?

---

```
Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.6.0
     root environment : /home/ali/miniconda3  (writable)
  default environment : /home/ali/miniconda3/envs/sasa
     envs directories : /home/ali/miniconda3/envs
        package cache : /home/ali/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

# conda environments:
#
sasa                  *  /home/ali/miniconda3/envs/sasa
root                     /home/ali/miniconda3

sys.version: 3.4.3 |Continuum Analytics, Inc.| (defau...
sys.prefix: /home/ali/miniconda3
sys.executable: /home/ali/miniconda3/bin/python3
conda location: /home/ali/miniconda3/lib/python3.4/site-packages/conda
conda-build: None
conda-env: /home/ali/miniconda3/bin/conda-env
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: sasa
CONDA_ENVS_PATH: <not set>                                                                                                                                              
LD_LIBRARY_PATH: :/home/ali/gurobi/lib                                                                                                                                  
PATH: /home/ali/miniconda3/envs/sasa/bin:/home/ali/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/ali/ampl-bin:/home/ali/asy-2.32/bin:/home/ali/gurobi/bin                                                                                                                                  
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

---

```
# packages in environment at /home/ali/miniconda3/envs/sasa:
#
decorator                 3.4.0                    py34_0  
fontconfig                2.11.1                        3  
freetype                  2.5.2                         1  
ipython                   3.1.0                    py34_0  
ipython-notebook          3.1.0                    py34_1  
ipython-qtconsole         3.1.0                    py34_0  
jinja2                    2.7.3                    py34_1  
jpeg                      8d                            0  
jsonschema                2.4.0                    py34_0  
libpng                    1.5.13                        1  
libsodium                 0.4.5                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.0                         0  
markupsafe                0.23                     py34_0  
matplotlib                1.4.3                np19py34_1  
mistune                   0.5.1                    py34_1  
networkx                  1.9.1                    py34_0  
nose                      1.3.6                    py34_0  
numpy                     1.9.2                    py34_0  
openssl                   1.0.1k                        1  
pandas                    0.16.0               np19py34_1  
pillow                    2.7.0                    py34_1  
pip                       6.1.1                    py34_0  
ptyprocess                0.4                      py34_0  
pygments                  2.0.2                    py34_0  
pyparsing                 2.0.3                    py34_0  
pyqt                      4.11.3                   py34_1  
python                    3.4.3                         0  
python-dateutil           2.4.2                    py34_0  
pytz                      2015.2                   py34_0  
pyzmq                     14.6.0                   py34_0  
qt                        4.8.6                         2  
readline                  6.2                           2  
scikit-image              0.11.3               np19py34_0  
scikit-learn              0.16.1               np19py34_0  
scipy                     0.15.1               np19py34_0  
setuptools                15.2                     py34_0  
sip                       4.16.5                   py34_0  
six                       1.9.0                    py34_0  
sqlite                    3.8.4.1                       1  
system                    5.8                           2  
terminado                 0.5                      py34_0  
tk                        8.5.18                        0  
tornado                   4.1                      py34_0  
xz                        5.0.5                         0  
zeromq                    4.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by soapy1** [comment]
Can't reproduce this on the newest version of conda & pandas. Please `conda update conda`
