### ISSUE TITLE
The Miniconda3-py311_23.9.0-0-Linux-x86_64.sh installer has md5sum mismatch issue 

### ISSUE THREAD

**Issue by chuanqi129** [conda/conda#13225]
### Checklist

- [X] I added a descriptive title
- [ ] I searched open reports and couldn't find a duplicate

### What happened?

When I use this latest miniconda installer https://repo.anaconda.com/miniconda/Miniconda3-py311_23.9.0-0-Linux-x86_64.sh, I met below error message,
```shell
#14 7.327 PREFIX=/opt/conda
#14 7.539 WARNING: md5sum mismatch of tar archive
#14 7.539 expected: af6b2fc3f2f0f02dad0e09d263e9ac6e
#14 7.539      got: 781ec0a82c56b64edc05ceb169ba8e42  -
#14 7.573 Unpacking payload ...
concurrent.futures.process._RemoteTraceback: 
#14 8.628 '''
#14 8.628 Traceback (most recent call last):
#14 8.628   File "concurrent/futures/process.py", line 387, in wait_result_broken_or_wakeup
#14 8.628   File "multiprocessing/connection.py", line 256, in recv
#14 8.628 TypeError: __init__() missing 1 required positional argument: 'msg'
#14 8.628 '''
```
this issue also let the https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh installer with same failure currently.

**Comment by chuanqi129** [comment]
Found similar issue in https://github.com/ContinuumIO/anaconda-issues/issues/13222, close this one
