### ISSUE TITLE
Conda hangs after Solving environment HTTP Error 429

### ISSUE THREAD

**Issue by kafker** [conda/conda#13238]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I work on a remote server and I am facing the same issue explained here: [Conda hangs after Solving environment HTTP Error 429](https://github.com/conda/conda/issues/11642)

I there anything I can do on my side? 

Thank you!

### Conda Info

```shell
active environment : base
    active env location : /path/to/miniconda3
            shell level : 1
       user config file : /path/to/.condarc
 populated config files : /path/to/.condarc
          conda version : 23.9.0
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.28=0
                          __linux=4.18.0=0
                          __unix=0=0
       base environment : /path/to/miniconda3  (writable)
      conda av data dir : /path/to/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /path/to/miniconda3/pkgs
                          /path/to/.conda/pkgs
       envs directories : /path/to/miniconda3/envs
                          /path/to/.conda/envs
               platform : linux-64
             user-agent : conda/23.9.0 requests/2.31.0 CPython/3.11.5 Linux/4.18.0-240.el8.x86_64 centos/8.3.2011 glibc/2.28
                UID:GID : 30900:25200
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
conda config --show-sources
==> /path/to/.condarc <==
channels:
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at /path/to/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
boltons                   23.0.0          py311h06a4308_0    defaults
brotlipy                  0.7.0           py311h5eee18b_1002    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.08.22           h06a4308_0    defaults
certifi                   2023.7.22       py311h06a4308_0    defaults
cffi                      1.15.1          py311h5eee18b_3    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.9.0          py311h06a4308_0    defaults
conda-content-trust       0.2.0           py311h06a4308_0    defaults
conda-libmamba-solver     23.9.1          py311h06a4308_0    defaults
conda-package-handling    2.2.0           py311h06a4308_0    defaults
conda-package-streaming   0.9.0           py311h06a4308_0    defaults
cryptography              41.0.3          py311hdda0065_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcurl                   8.2.1                h251f7ec_0    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.5.1                haf1ee3a_0    defaults
libmambapy                1.5.1           py311h2dafd23_0    defaults
libnghttp2                1.52.0               h2d74bed_1    defaults
libsolv                   0.7.24               he621ea3_0    defaults
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.4               hf1b16e4_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.11               h7f8727e_2    defaults
packaging                 23.1            py311h06a4308_0    defaults
pcre2                     10.42                hebb0a14_0    defaults
pip                       23.2.1          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.5               h955ad1f_0    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                68.0.0          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
truststore                0.8.0           py311h06a4308_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.16         py311h06a4308_0    defaults
wheel                     0.41.2          py311h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml-cpp                  0.7.0                h295c915_1    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

### Additional Context

Here is the output from `conda create -vvv -p $WORK/XXXAF`

```
DEBUG conda.gateways.logging:set_log_level(232): log_level set to 10
DEBUG conda.core.solve:solve_final_state(284): solving prefix /g100_work/IscrC_MetCave2_1/XXXAF
  specs_to_remove: frozenset()
  specs_to_add: frozenset()
  prune: Null
Collecting package metadata (current_repodata.json): ...working... DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __archspec
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __glibc
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __linux
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __unix
done
Solving environment: ...working... DEBUG conda.resolve:get_reduced_index(673): Retrieving packages for:
DEBUG conda.core.solve:_add_specs(817): specs_map with targets: {'__archspec': MatchSpec("__archspec"), '__glibc': MatchSpec("__glibc"), '__linux': MatchSpec("__linux"), '__unix': MatchSpec("__unix")}
DEBUG conda.resolve:get_reduced_index(673): Retrieving packages for:
  - __archspec
  - __glibc
  - __linux
  - __unix
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __unix
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __linux
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __glibc
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __archspec
DEBUG conda.common._logic:_run_sat(613): Invoking SAT with clause count: 2
DEBUG conda.resolve:_get_sat_solver_cls(79): Using SAT solver interface 'pycosat'.
DEBUG conda.resolve:gen_clauses(1061): gen_clauses returning with clause count: 12
DEBUG conda.resolve:generate_spec_constraints(1069): generate_spec_constraints returning with clause count: 12
DEBUG conda.common._logic:_run_sat(613): Invoking SAT with clause count: 16
DEBUG conda.resolve:bad_installed(1282): Checking if the current environment is consistent
DEBUG conda.core.solve:_find_inconsistent_packages(639): inconsistent precs: None
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __unix
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __linux
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __glibc
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __archspec
DEBUG conda.resolve:gen_clauses(1061): gen_clauses returning with clause count: 12
DEBUG conda.resolve:generate_spec_constraints(1069): generate_spec_constraints returning with clause count: 12
DEBUG conda.common._logic:_run_sat(613): Invoking SAT with clause count: 16
DEBUG conda.core.solve:_run_sat(1036): final specs to add:
  - __archspec
  - __glibc
  - __linux
  - __unix
DEBUG conda.resolve:solve(1439): Solving for:
  - 0: __linux target=None optional=False
  - 1: __glibc target=None optional=False
  - 2: __archspec target=None optional=False
  - 3: __unix target=None optional=False
DEBUG conda.resolve:solve(1445): Solve: Getting reduced index of compliant packages
DEBUG conda.resolve:solve(1477): Solve: determining satisfiability
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __unix
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __linux
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __glibc
DEBUG conda.resolve:__init__(132): restricting to unmanageable packages: __archspec
DEBUG conda.resolve:gen_clauses(1061): gen_clauses returning with clause count: 12
DEBUG conda.resolve:generate_spec_constraints(1069): generate_spec_constraints returning with clause count: 12
DEBUG conda.common._logic:_run_sat(613): Invoking SAT with clause count: 16
DEBUG conda.resolve:solve(1531): Requested specs:
  - __archspec
  - __glibc
  - __linux
  - __unix
DEBUG conda.resolve:solve(1532): Optional specs:
DEBUG conda.resolve:solve(1533): All other specs:
DEBUG conda.resolve:solve(1534): missing specs:
DEBUG conda.resolve:solve(1537): Solve: minimize removed packages
DEBUG conda.resolve:solve(1544): Solve: maximize versions of requested packages
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1550): Initial package channel/version metric: 0/0
DEBUG conda.resolve:solve(1553): Solve: minimize track_feature count
DEBUG conda.resolve:generate_feature_count(1081): generate_feature_count returning with clause count: 16
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1556): Track feature count: 0
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1567): Package misfeature count: 0
DEBUG conda.resolve:solve(1570): Solve: maximize build numbers of requested packages
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1572): Initial package build metric: 0
DEBUG conda.resolve:solve(1575): Solve: prefer arch over noarch for requested packages
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1577): Noarch metric: 0
DEBUG conda.resolve:solve(1581): Solve: minimize number of optional installations
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1584): Optional package install metric: 0
DEBUG conda.resolve:solve(1587): Solve: minimize number of necessary upgrades
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1590): Dependency update count: 0
DEBUG conda.resolve:solve(1593): Solve: maximize versions and builds of indirect dependencies.  Prefer arch over noarch where equivalent.
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1602): Additional package channel/version/build/noarch metrics: 0/0/0/0
DEBUG conda.resolve:solve(1611): Solve: prune unnecessary packages
DEBUG conda.common._logic:minimize(673): Empty objective, trivial solution
DEBUG conda.resolve:solve(1614): Weak dependency count: 0
DEBUG conda.resolve:solve(1622): Looking for alternate solutions
done
DEBUG conda.core.solve:solve_final_state(410): solved prefix /g100_work/IscrC_MetCave2_1/XXXAF
  solved_linked_dists:


DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/jsonpointer-2.1-pyhd3eb1b0_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/tzdata-2023c-h04d1e81_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/reproc-14.2.4-h295c915_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pybind11-abi-4-hd3eb1b0_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/conda-content-trust-0.2.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/truststore-0.8.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/icu-73.1-h6a678d5_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/reproc-cpp-14.2.4-h295c915_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/yaml-cpp-0.7.0-h295c915_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/fmt-9.1.0-hdb19cb5_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/zstd-1.5.5-hc292b87_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pip-23.2.1-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libgomp-11.2.0-h1234567_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/lz4-c-1.9.4-h6a678d5_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/idna-3.4-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pycparser-2.21-pyhd3eb1b0_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libstdcxx-ng-11.2.0-h1234567_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/bzip2-1.0.8-h7b6447c_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/packaging-23.1-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libedit-3.1.20221030-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libssh2-1.10.0-hdbd6064_2.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/tqdm-4.65.0-py311h92b7b1e_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/wheel-0.41.2-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libxml2-2.10.4-hf1b16e4_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/zlib-1.2.13-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pluggy-1.0.0-py311h06a4308_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pcre2-10.42-hebb0a14_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/jsonpatch-1.32-pyhd3eb1b0_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/openssl-3.0.11-h7f8727e_2.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/ncurses-6.4-h6a678d5_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libcurl-8.2.1-h251f7ec_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/sqlite-3.41.2-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/c-ares-1.19.1-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/certifi-2023.7.22-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/setuptools-68.0.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/readline-8.2-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libsolv-0.7.24-he621ea3_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/_libgcc_mutex-0.1-main.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/tk-8.6.12-h1ccaba5_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libgcc-ng-11.2.0-h1234567_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/ruamel.yaml-0.17.21-py311h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/conda-libmamba-solver-23.9.1-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/conda-package-streaming-0.9.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/conda-package-handling-2.2.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pyopenssl-23.2.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/charset-normalizer-2.0.4-pyhd3eb1b0_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libarchive-3.6.2-h6ac8c49_2.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/urllib3-1.26.16-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/cffi-1.15.1-py311h5eee18b_3.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libnghttp2-1.52.0-h2d74bed_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/ca-certificates-2023.08.22-h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pycosat-0.6.6-py311h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libmambapy-1.5.1-py311h2dafd23_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/brotlipy-0.7.0-py311h5eee18b_1002.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/python-3.11.5-h955ad1f_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/conda-23.9.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/xz-5.4.2-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libffi-3.4.4-h6a678d5_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/krb5-1.20.1-h143b758_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libuuid-1.41.5-h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libmamba-1.5.1-haf1ee3a_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/cryptography-41.0.3-py311hdda0065_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/boltons-23.0.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/pysocks-1.7.1-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/requests-2.31.0-py311h06a4308_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/libev-4.33-h7f8727e_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/zstandard-0.19.0-py311h5eee18b_0.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/ld_impl_linux-64-2.38-h1181459_1.json
DEBUG conda.core.prefix_data:_load_single_record(190): loading prefix record /path/to/miniconda3/conda-meta/_openmp_mutex-5.1-1_gnu.json
DEBUG conda.core.package_cache_data:_check_writable(317): package cache directory '/path/to/miniconda3/pkgs' writable: True
DEBUG conda.gateways.repodata:fetch_latest(807): Using cached repodata for https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json at /path/to/miniconda3/pkgs/cache/18414ddb.json. Timeout in 2311 sec
DEBUG conda.gateways.repodata:read_cache(887): Loading raw json for https://conda.anaconda.org/conda-forge/linux-64/current_repodata.json at /path/to/miniconda3/pkgs/cache/18414ddb.json
DEBUG conda.gateways.repodata:fetch_latest(807): Using cached repodata for https://conda.anaconda.org/conda-forge/noarch/current_repodata.json at /path/to/miniconda3/pkgs/cache/62c98390.json. Timeout in 2309 sec
DEBUG conda.gateways.repodata:read_cache(887): Loading raw json for https://conda.anaconda.org/conda-forge/noarch/current_repodata.json at /path/to/miniconda3/pkgs/cache/62c98390.json
DEBUG conda.gateways.repodata:fetch_latest(773): No local cache found for https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json at /path/to/miniconda3/pkgs/cache/9e0f62c3.json
DEBUG conda.gateways.repodata:__init__(122): Using CondaRepoInterface
DEBUG urllib3.connectionpool:_new_conn(1014): Starting new HTTPS connection (1): repo.anaconda.com:443
DEBUG urllib3.connectionpool:_make_request(473): https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 429 84
DEBUG urllib3.util.retry:increment(594): Incremented Retry for (url='/pkgs/main/linux-64/current_repodata.json'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
DEBUG urllib3.connectionpool:urlopen(888): Retry: /pkgs/main/linux-64/current_repodata.json
DEBUG urllib3.connectionpool:_make_request(473): https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 429 84
DEBUG urllib3.util.retry:increment(594): Incremented Retry for (url='/pkgs/main/linux-64/current_repodata.json'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
DEBUG urllib3.connectionpool:urlopen(888): Retry: /pkgs/main/linux-64/current_repodata.json
DEBUG urllib3.connectionpool:_make_request(473): https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 429 84
DEBUG urllib3.util.retry:increment(594): Incremented Retry for (url='/pkgs/main/linux-64/current_repodata.json'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
DEBUG urllib3.connectionpool:urlopen(888): Retry: /pkgs/main/linux-64/current_repodata.json
DEBUG urllib3.connectionpool:_make_request(473): https://repo.anaconda.com:443 "GET /pkgs/main/linux-64/current_repodata.json HTTP/1.1" 429 84
DEBUG conda.gateways.repodata:repodata(152):
>>GET /pkgs/main/linux-64/current_repodata.json HTTPS
> User-Agent: conda/23.9.0 requests/2.31.0 CPython/3.11.5 Linux/4.18.0-240.el8.x86_64 centos/8.3.2011 glibc/2.28
> Accept: */*
> Accept-Encoding: gzip, deflate, br
> Connection: keep-alive

<<HTTPS 429 Too Many Requests
< CF-RAY: 81bb536cfdd2b3a3-MUC
< Content-Security-Policy: upgrade-insecure-requests; frame-ancestors 'self' https://content.anaconda.com/
< Content-Type: application/json
< Date: Wed, 25 Oct 2023 14:59:52 GMT
< Retry-After: 83710
< Server: cloudflare
< Set-Cookie: __cf_bm=4i7q8V1.75M51CpUP4NjxEl83vp3eWj1dBN6ozgCIK4-1698245992-0-AcZIO5L4qLHisSlqUQ+75AFRCBvkN+Z7+R5+l2c5y3zfgv3nK2ohVwlpOEX9M6tMM0utpPogpSd+ASIAa3cv0F0=; path=/; expires=Wed, 25-Oct-23 15:29:52 GMT; domain=.anaconda.com; HttpOnly; Secure; SameSite=None
< Vary: Accept-Encoding
< X-Robots-Tag: noindex
< Content-Length: 84
< Connection: keep-alive
< Elapsed: 00:06.594837

{
  "reason": "cloudflare reason",
  "message": "cloudflare message\ncloudflare message"
}


Traceback (most recent call last):
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 187, in conda_http_errors
    yield
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 153, in repodata
    response.raise_for_status()
  File "/path/to/miniconda3/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 78, in main_subshell
    exit_code = do_call(args, parser)
                ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 166, in do_call
    result = getattr(module, func_name)(args, parser)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/cli/main_create.py", line 50, in execute
    install(args, parser, "create")
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/cli/install.py", line 320, in install
    unlink_link_transaction = solver.solve_for_transaction(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 159, in solve_for_transaction
    self._notify_conda_outdated(link_precs)
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 1218, in _notify_conda_outdated
    SubdirData.query_all(
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 165, in query_all
    result = tuple(
             ^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/common/io.py", line 570, in map
    yield func(thing)
          ^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 150, in subdir_query
    return tuple(
           ^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 172, in query
    self.load()
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 272, in load
    _internal_state = self._load()
                      ^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 315, in _load
    repodata, state = fetcher.fetch_latest_parsed()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 716, in fetch_latest_parsed
    parsed, state = self.fetch_latest()
                    ^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 828, in fetch_latest
    raw_repodata = repo.repodata(cache.state)  # type: ignore
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 143, in repodata
    with conda_http_errors(self._url, filename):
  File "/path/to/miniconda3/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/path/to/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 338, in conda_http_errors
    raise CondaHTTPError(
conda.exceptions.CondaHTTPError: HTTP 429 CLOUDFLARE REASON for url <https://repo.anaconda.com/pkgs/main/linux-64/current_repodata.json>
Elapsed: 00:06.594837
CF-RAY: 81bb536cfdd2b3a3-MUC

cloudflare message
cloudflare message
```

And this is what I get when I run `wget https://repo.anaconda.com/pkgs/r/noarch/current_repodata.json`
```
--2023-10-25 17:02:43--  https://repo.anaconda.com/pkgs/r/noarch/current_repodata.json
Resolving repo.anaconda.com (repo.anaconda.com)... 104.16.131.3, 104.16.130.3, 2606:4700::6810:8303, ...
Connecting to repo.anaconda.com (repo.anaconda.com)|104.16.131.3|:443... connected.
HTTP request sent, awaiting response... 429 Too Many Requests
2023-10-25 17:02:43 ERROR 429: Too Many Requests.
```

**Comment by travishathaway** [comment]
Hi @kafker,

You are seeing this message because we Anaconda is trying to restrict your usage of the `defaults` channel. This can happen when your organization is in violation of Anaconda's terms of use. This blog post should offer a an explanation of how this could happen:

- https://www.anaconda.com/blog/is-conda-free

The easiest way around this for now is to simply stop using `defaults` in your setup and only use `conda-forge`.

Please let us know if you have any questions.
