### ISSUE TITLE
conda upgrade

### ISSUE THREAD

**Issue by cevad** [conda/conda#1325]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'
================================================================================

D:\python>conda info
Current conda install:

             platform : win-64
        conda version : 3.11.0-dirty
  conda-build version : 1.3.3
       python version : 2.7.6.final.0
     requests version : 2.4.3
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ricksorensen** [comment]
I received the same/similar error on an upgrade.  The exception was reported after all the packages had been downloaded and unpacked.

System Info:
````
Current conda install:

             platform : win-64
        conda version : 3.11.0
  conda-build version : 1.3.1
       python version : 2.7.6.final.0
     requests version : 2.6.2
     root environment : C:\Users\rick\Anaconda  (writable)
  default environment : C:\Users\rick\Anaconda
     envs directories : C:\Users\rick\Anaconda\envs
        package cache : C:\Users\rick\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
````
And here is the entire upgrade output:
````
C:\Users\rick\Anaconda>conda update anaconda
Fetching package metadata: C:\Users\rick\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarni
ng: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL co
nnections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
....
Solving package specifications: .
Package plan for installation in environment C:\Users\rick\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda311fix-1.0            |                0           7 KB
    beautiful-soup-4.3.2       |           py27_1         109 KB
    boto-2.36.0                |           py27_0         1.5 MB
    certifi-14.05.14           |           py27_0         154 KB
    clyent-0.3.4               |           py27_0          13 KB
    colorama-0.3.3             |           py27_0          17 KB
    cython-0.22                |           py27_0         1.8 MB
    cytoolz-0.7.2              |           py27_0         171 KB
    docutils-0.12              |           py27_1         637 KB
    enum34-1.0.4               |           py27_0          48 KB
    fastcache-1.0.2            |           py27_0          23 KB
    funcsigs-0.4               |           py27_0          19 KB
    futures-2.2.0              |           py27_0          21 KB
    greenlet-0.4.5             |           py27_0          13 KB
    jedi-0.8.1                 |           py27_0         171 KB
    jsonschema-2.4.0           |           py27_0          92 KB
    lxml-3.4.2                 |           py27_0         1.5 MB
    menuinst-1.0.4             |           py27_0          52 KB
    mistune-0.5.1              |           py27_0          18 KB
    nose-1.3.4                 |           py27_1         233 KB
    pep8-1.6.2                 |           py27_0          87 KB
    pillow-2.7.0               |           py27_0         917 KB
    py-1.4.26                  |           py27_0         121 KB
    pyasn1-0.1.7               |           py27_0          48 KB
    pycrypto-2.6.1             |           py27_3         454 KB
    pygments-2.0.2             |           py27_0         1.1 MB
    pyzmq-14.5.0               |           py27_0         397 KB
    requests-2.6.0             |           py27_0         590 KB
    setuptools-14.3            |           py27_0         742 KB
    sqlalchemy-0.9.9           |           py27_0         1.2 MB
    sympy-0.7.6                |           py27_0         6.2 MB
    toolz-0.7.1                |           py27_0          27 KB
    werkzeug-0.10.1            |           py27_0         374 KB
    xlsxwriter-0.6.7           |           py27_0         173 KB
    argcomplete-0.8.4          |           py27_0          80 KB
    astropy-1.0.1              |       np19py27_0         5.2 MB
    bcolz-0.8.1                |       np19py27_0         310 KB
    cffi-0.9.2                 |           py27_0         117 KB
    h5py-2.4.0                 |       np19py27_0         1.4 MB
    ipython-3.0.0              |           py27_1         3.4 MB
    jinja2-2.7.3               |           py27_2         307 KB
    llvmlite-0.2.2             |           py27_1         4.7 MB
    nltk-3.0.2                 |       np19py27_0         1.5 MB
    pip-6.0.8                  |           py27_0         1.6 MB
    pytest-2.6.4               |           py27_0         221 KB
    python-dateutil-2.4.1      |           py27_0         218 KB
    tornado-4.1                |           py27_0         475 KB
    xlwings-0.3.4              |           py27_0         234 KB
    binstar-0.10.1             |           py27_3         124 KB
    cryptography-0.8           |           py27_1         1.0 MB
    datashape-0.4.4            |       np19py27_1          95 KB
    ipython-notebook-3.0.0     |           py27_2           5 KB
    ipython-qtconsole-3.0.0    |           py27_1           4 KB
    numba-0.17.0               |       np19py27_0         830 KB
    pandas-0.15.2              |       np19py27_1         4.3 MB
    bokeh-0.8.1                |       np19py27_1        13.5 MB
    odo-0.3.1                  |       np19py27_0         180 KB
    runipy-0.1.3               |           py27_0          48 KB
    scikit-image-0.11.2        |       np19py27_0        15.8 MB
    spyder-2.3.4               |           py27_1         4.0 MB
    statsmodels-0.6.1          |       np19py27_0         4.6 MB
    blaze-core-0.7.3           |       np19py27_0         305 KB
    spyder-app-2.3.4           |           py27_0           7 KB
    anaconda-2.2.0             |       np19py27_0          30 KB
    ------------------------------------------------------------
                                           Total:        83.4 MB

The following NEW packages will be INSTALLED:

    bcolz:             0.8.1-np19py27_0
    blaze-core:        0.7.3-np19py27_0
    certifi:           14.05.14-py27_0
    clyent:            0.3.4-py27_0
    conda311fix:       1.0-0
    enum34:            1.0.4-py27_0
    fastcache:         1.0.2-py27_0
    funcsigs:          0.4-py27_0
    jedi:              0.8.1-py27_0
    jsonschema:        2.4.0-py27_0
    llvmlite:          0.2.2-py27_1
    mistune:           0.5.1-py27_0
    odo:               0.3.1-np19py27_0
    pillow:            2.7.0-py27_0
    pyasn1:            0.1.7-py27_0

The following packages will be UPDATED:

    anaconda:          2.1.0-np19py27_0  --> 2.2.0-np19py27_0
    argcomplete:       0.8.1-py27_0      --> 0.8.4-py27_0
    astropy:           0.4.2-np19py27_0  --> 1.0.1-np19py27_0
    beautiful-soup:    4.3.2-py27_0      --> 4.3.2-py27_1
    binstar:           0.7.1-py27_0      --> 0.10.1-py27_3
    bokeh:             0.6.1-np19py27_0  --> 0.8.1-np19py27_1
    boto:              2.32.1-py27_0     --> 2.36.0-py27_0
    cffi:              0.8.6-py27_0      --> 0.9.2-py27_0
    colorama:          0.3.1-py27_0      --> 0.3.3-py27_0
    cryptography:      0.5.4-py27_0      --> 0.8-py27_1
    cython:            0.21-py27_0       --> 0.22-py27_0
    cytoolz:           0.7.0-py27_0      --> 0.7.2-py27_0
    datashape:         0.3.0-np19py27_1  --> 0.4.4-np19py27_1
    docutils:          0.12-py27_0       --> 0.12-py27_1
    futures:           2.1.6-py27_0      --> 2.2.0-py27_0
    greenlet:          0.4.4-py27_0      --> 0.4.5-py27_0
    h5py:              2.3.1-np19py27_0  --> 2.4.0-np19py27_0
    ipython:           2.2.0-py27_0      --> 3.0.0-py27_1
    ipython-notebook:  2.2.0-py27_0      --> 3.0.0-py27_2
    ipython-qtconsole: 2.2.0-py27_0      --> 3.0.0-py27_1
    jinja2:            2.7.3-py27_1      --> 2.7.3-py27_2
    lxml:              3.4.0-py27_0      --> 3.4.2-py27_0
    menuinst:          1.0.3-py27_0      --> 1.0.4-py27_0
    nltk:              3.0.0-np19py27_0  --> 3.0.2-np19py27_0
    nose:              1.3.4-py27_0      --> 1.3.4-py27_1
    numba:             0.14.0-np19py27_0 --> 0.17.0-np19py27_0
    pep8:              1.5.7-py27_0      --> 1.6.2-py27_0
    py:                1.4.25-py27_0     --> 1.4.26-py27_0
    pycrypto:          2.6.1-py27_2      --> 2.6.1-py27_3
    pygments:          1.6-py27_0        --> 2.0.2-py27_0
    pytest:            2.6.3-py27_0      --> 2.6.4-py27_0
    pyzmq:             14.3.1-py27_0     --> 14.5.0-py27_0
    runipy:            0.1.1-py27_0      --> 0.1.3-py27_0
    scikit-image:      0.10.1-np19py27_0 --> 0.11.2-np19py27_0
    spyder:            2.3.1-py27_0      --> 2.3.4-py27_1
    spyder-app:        2.3.1-py27_0      --> 2.3.4-py27_0
    sqlalchemy:        0.9.7-py27_0      --> 0.9.9-py27_0
    statsmodels:       0.5.0-np19py27_2  --> 0.6.1-np19py27_0
    sympy:             0.7.5-py27_0      --> 0.7.6-py27_0
    toolz:             0.7.0-py27_0      --> 0.7.1-py27_0
    tornado:           4.0.2-py27_0      --> 4.1-py27_0
    werkzeug:          0.9.6-py27_1      --> 0.10.1-py27_0
    xlsxwriter:        0.5.7-py27_0      --> 0.6.7-py27_0
    xlwings:           0.2.2-py27_0      --> 0.3.4-py27_0

The following packages will be DOWNGRADED:

    pandas:            0.16.0-np19py27_1 --> 0.15.2-np19py27_1
    pip:               6.1.1-py27_0      --> 6.0.8-py27_0
    python-dateutil:   2.4.2-py27_0      --> 2.4.1-py27_0
    requests:          2.6.2-py27_0      --> 2.6.0-py27_0
    setuptools:        15.1-py27_0       --> 14.3-py27_0

Proceed ([y]/n)? y

menuinst-1.0.4 100% |###############################| Time: 0:00:00 484.50 kB/s
Fetching packages ...
conda311fix-1. 100% |###############################| Time: 0:00:00   0.00  B/s
beautiful-soup 100% |###############################| Time: 0:00:00 420.44 kB/s
boto-2.36.0-py 100% |###############################| Time: 0:00:02 719.13 kB/s
certifi-14.05. 100% |###############################| Time: 0:00:00 505.68 kB/s
clyent-0.3.4-p 100% |###############################| Time: 0:00:00 808.25 kB/s
colorama-0.3.3 100% |###############################| Time: 0:00:00 222.73 kB/s
cython-0.22-py 100% |###############################| Time: 0:00:02 785.87 kB/s
cytoolz-0.7.2- 100% |###############################| Time: 0:00:00 539.54 kB/s
docutils-0.12- 100% |###############################| Time: 0:00:01 602.74 kB/s
enum34-1.0.4-p 100% |###############################| Time: 0:00:00 380.13 kB/s
fastcache-1.0. 100% |###############################| Time: 0:00:00 306.45 kB/s
funcsigs-0.4-p 100% |###############################| Time: 0:00:00 330.33 kB/s
futures-2.2.0- 100% |###############################| Time: 0:00:00 420.08 kB/s
greenlet-0.4.5 100% |###############################| Time: 0:00:00 273.92 kB/s
jedi-0.8.1-py2 100% |###############################| Time: 0:00:00 436.55 kB/s
jsonschema-2.4 100% |###############################| Time: 0:00:00 305.31 kB/s
lxml-3.4.2-py2 100% |###############################| Time: 0:00:02 665.67 kB/s
mistune-0.5.1- 100% |###############################| Time: 0:00:00  45.09 kB/s
nose-1.3.4-py2 100% |###############################| Time: 0:00:00 466.90 kB/s
pep8-1.6.2-py2 100% |###############################| Time: 0:00:00 287.07 kB/s
pillow-2.7.0-p 100% |###############################| Time: 0:00:01 920.25 kB/s
py-1.4.26-py27 100% |###############################| Time: 0:00:00 468.45 kB/s
pyasn1-0.1.7-p 100% |###############################| Time: 0:00:00 282.88 kB/s
pycrypto-2.6.1 100% |###############################| Time: 0:00:00 876.79 kB/s
pygments-2.0.2 100% |###############################| Time: 0:00:01 657.89 kB/s
pyzmq-14.5.0-p 100% |###############################| Time: 0:00:00 661.38 kB/s
requests-2.6.0 100% |###############################| Time: 0:00:01 378.37 kB/s
setuptools-14. 100% |###############################| Time: 0:00:00 864.35 kB/s
sqlalchemy-0.9 100% |###############################| Time: 0:00:01 955.47 kB/s
sympy-0.7.6-py 100% |###############################| Time: 0:00:03   1.82 MB/s
toolz-0.7.1-py 100% |###############################| Time: 0:00:00 470.69 kB/s
werkzeug-0.10. 100% |###############################| Time: 0:00:00 570.56 kB/s
xlsxwriter-0.6 100% |###############################| Time: 0:00:00 388.67 kB/s
argcomplete-0. 100% |###############################| Time: 0:00:00 391.50 kB/s
astropy-1.0.1- 100% |###############################| Time: 0:00:04   1.14 MB/s
bcolz-0.8.1-np 100% |###############################| Time: 0:00:00 547.01 kB/s
cffi-0.9.2-py2 100% |###############################| Time: 0:00:00 473.47 kB/s
h5py-2.4.0-np1 100% |###############################| Time: 0:00:01   1.22 MB/s
ipython-3.0.0- 100% |###############################| Time: 0:00:02   1.37 MB/s
jinja2-2.7.3-p 100% |###############################| Time: 0:00:00 409.05 kB/s
llvmlite-0.2.2 100% |###############################| Time: 0:00:04   1.12 MB/s
nltk-3.0.2-np1 100% |###############################| Time: 0:00:02 642.33 kB/s
pip-6.0.8-py27 100% |###############################| Time: 0:00:02 668.61 kB/s
pytest-2.6.4-p 100% |###############################| Time: 0:00:00 533.61 kB/s
python-dateuti 100% |###############################| Time: 0:00:00 631.71 kB/s
tornado-4.1-py 100% |###############################| Time: 0:00:00 540.35 kB/s
xlwings-0.3.4- 100% |###############################| Time: 0:00:00 468.59 kB/s
binstar-0.10.1 100% |###############################| Time: 0:00:00 450.60 kB/s
cryptography-0 100% |###############################| Time: 0:00:01 710.41 kB/s
datashape-0.4. 100% |###############################| Time: 0:00:00 419.64 kB/s
ipython-notebo 100% |###############################| Time: 0:00:00  18.60 kB/s
ipython-qtcons 100% |###############################| Time: 0:00:00 323.16 kB/s
numba-0.17.0-n 100% |###############################| Time: 0:00:01 589.55 kB/s
pandas-0.15.2- 100% |###############################| Time: 0:00:03   1.19 MB/s
bokeh-0.8.1-np 100% |###############################| Time: 0:00:08   1.76 MB/s
odo-0.3.1-np19 100% |###############################| Time: 0:00:00 500.38 kB/s
runipy-0.1.3-p 100% |###############################| Time: 0:00:00  57.04 kB/s
scikit-image-0 100% |###############################| Time: 0:00:08   1.89 MB/s
spyder-2.3.4-p 100% |###############################| Time: 0:00:03   1.24 MB/s
statsmodels-0. 100% |###############################| Time: 0:00:05 973.13 kB/s
blaze-core-0.7 100% |###############################| Time: 0:00:00 494.30 kB/s
spyder-app-2.3 100% |###############################| Time: 0:00:00 894.89 kB/s
anaconda-2.2.0 100% |###############################| Time: 0:00:00 465.27 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\rick\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Users\rick\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    if not can_open_all_files_in_prefix(prefix, meta["files"]):
TypeError: 'NoneType' object has no attribute '__getitem__'

C:\Users\rick\Anaconda>
C:\Users\rick\Anaconda>
````

**Comment by soapy1** [comment]
@cevad is this still an issue for you

**Comment by cevad** [comment]
No longer an issue.
Thanks.
