### ISSUE TITLE
conda pipbuild TypeError exception

### ISSUE THREAD

**Issue by knowsuchagency** [conda/conda#1326]
# Traceback from 'conda pipbuild github3.py'

Traceback (most recent call last):
  File "/home/vagrant/anaconda3/bin/conda-pipbuild", line 5, in <module>
    sys.exit(main())
  File "/home/vagrant/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 77, in main
    args_func(args, p)
  File "/home/vagrant/anaconda3/lib/python3.4/site-packages/conda_build/main_build.py", line 308, in args_func
    args.func(args, p)
  File "/home/vagrant/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 350, in execute
    build_package(package, version)
  File "/home/vagrant/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 300, in build_package
    directory = build_recipe(package, version=version)
  File "/home/vagrant/anaconda3/lib/python3.4/site-packages/conda_build/main_pipbuild.py", line 161, in build_recipe
    output = result.strip().split('\n')
TypeError: Type str doesn't support the buffer API
# Output from 'conda info'

Current conda install:

```
         platform : linux-64
    conda version : 3.7.0
```

  conda-build version : 1.8.2
       python version : 3.4.1.final.0
     requests version : 2.4.1
     root environment : /home/vagrant/anaconda3  (writable)
  default environment : /home/vagrant/anaconda3/envs/py27
     envs directories : /home/vagrant/anaconda3/envs
        package cache : /home/vagrant/anaconda3/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://conda.binstar.org/knowsuchagency/linux-64/
          config file : /home/vagrant/.condarc
    is foreign system : False

**Comment by kalefranz** [comment]
Going to close this old issue.  If a problem still exists, please file a new issue at github.com/conda/conda-build.
