### ISSUE TITLE
conda update fails with json decode error

### ISSUE THREAD

**Issue by agapow** [conda/conda#1327]
Various conda commands are erroring out, apparently due to corrupt json.

## Example

```% conda update conda``` or ```% conda update --all``` results in:

```
Fetching package metadata: ....
Warning: No packages found in current osx-64 channels matching: r-base, skipping
Warning: No packages found in current osx-64 channels matching: libgcc, skipping
Warning: No packages found in current osx-64 channels matching: ncurses, skipping
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/pagapow/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 203, in main
    args_func(args, p)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 609, in inner
    return func(args, parser)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 357, in install
    return install(args, parser, command=command)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 357, in install
    return install(args, parser, command=command)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 357, in install
    return install(args, parser, command=command)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/plan.py", line 431, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/plan.py", line 246, in ensure_linked_actions
    if install.is_linked(prefix, dist):
  File "/Users/pagapow/anaconda/lib/python3.4/site-packages/conda/install.py", line 499, in is_linked
    return json.load(fi)
  File "/Users/pagapow/anaconda/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/pagapow/anaconda/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/Users/pagapow/anaconda/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/pagapow/anaconda/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 31 column 15 (char 639)
```

## conda info

```
Current conda install:

             platform : osx-64
        conda version : 3.12.0
  conda-build version : 1.8.2
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /Users/pagapow/anaconda  (writable)
  default environment : /Users/pagapow/anaconda
     envs directories : /Users/pagapow/anaconda/envs
        package cache : /Users/pagapow/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

## Attempted fixes

Looked for duplicate packages. Deleted conda caches. Tried several times in case it was error with server. No joy.

**Comment by agapow** [comment]
Looks like the conda metadata file for ipython-notebook (anaconda/conda-meta/ipython-notebook-3.1.0-py34_1.json)  is prematurely terminated.

**Comment by agapow** [comment]
The conda metadata for ipython-qtconsole was also corrupt. Deleted those two and reinstalled the packages, looks to be working fine.
