### ISSUE TITLE
External commands help search results in "File not found ~/envs"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1330]
I am running conda 3.12.0 on Linux 64-bit.  I execute "conda" all by itself, and I get back the following:

```bash
$ conda
usage: conda [-h] [-V] [--debug] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    info         Display information about current conda install.
    help         Displays a list of available conda commands and their help
                 strings.
    list         List linked packages in a conda environment.
    search       Search for packages and display their information. The input
                 is a regular expression. To perform a search with a search
                 string that starts with a -, separate the search from the
                 options with --, like 'conda search -- -h'. A * in the
                 results means that package is installed in the current
                 environment. A . means that package is not installed but is
                 cached in the pkgs directory.
    create       Create a new conda environment from a list of specified
                 packages.
    install      Install a list of packages into a specified conda
                 environment.
    update       Update conda packages to the current version.
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove. See conda remove --help.
    run          Launches an application installed with Conda.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (/home/ijstokes/.condarc) by default.
    init         Initialize conda into a regular environment (when conda was
                 installed as a Python package, e.g. using pip). (DEPRECATED)
    clean        Remove unused packages and caches.
    package      Low-level conda package utility. (EXPERIMENTAL)
    bundle       Create or extract a "bundle package" (EXPERIMENTAL)

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.
  --debug        Show debug output.

external commands:
Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda-analysispackage", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_analysis_package/main.py", line 116, in main
    args = parser.parse_args()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 517, in _format_action
    help_text = self._expand_help(action)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 601, in _expand_help
    choices_str = ', '.join([str(c) for c in params['choices']])
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 49, in __iter__
    return iter(self.get_items())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/utils.py", line 143, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 41, in get_items
    return self._get_items()
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 55, in _get_items
    res.extend(os.listdir(dir))
OSError: [Errno 2] No such file or directory: '/home/ijstokes/envs'
failed: /opt/wakari/anaconda/bin/conda-analysispackage --help
    build        tool for building conda packages
    convert      various tools to convert conda packages
Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda-develop", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/main_develop.py", line 36, in main
    args = p.parse_args()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1701, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1733, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1939, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1879, in consume_optional
    take_action(action, args, option_string)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 1807, in take_action
    action(self, namespace, argument_values, option_string)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 996, in __call__
    parser.print_help()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 2340, in print_help
    self._print_message(self.format_help(), file)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 2314, in format_help
    return formatter.format_help()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 281, in format_help
    help = self._root_section.format_help()
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 211, in format_help
    func(*args)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 517, in _format_action
    help_text = self._expand_help(action)
  File "/opt/wakari/anaconda/lib/python2.7/argparse.py", line 601, in _expand_help
    choices_str = ', '.join([str(c) for c in params['choices']])
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 49, in __iter__
    return iter(self.get_items())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/utils.py", line 143, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 41, in get_items
    return self._get_items()
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 55, in _get_items
    res.extend(os.listdir(dir))
OSError: [Errno 2] No such file or directory: '/home/ijstokes/envs'
failed: /opt/wakari/anaconda/bin/conda-develop --help
    env          positional arguments:
                   {create,export,list,remove,update}
                     create              Create an environment based on an environment file
                     export              Export a given environment
                     list                List the Conda environments
                     remove              Remove an environment
                     update              Update the current environment based on environment
                                         file
    index        Update package index metadata files in given directories
    inspect      Tools for inspecting conda packages
    metapackage  tool for building conda metapackages. A metapackage is a package with no
                 files, only metadata
    pipbuild     tool for building conda packages just using pip install
    skeleton     create skeleton recipes for packages from hosting sites
```

**Comment by pelson** [comment]
P.S. It would be *very* useful if the "external" commands functionality were available as a standalone library :wink:

**Comment by parautenbach** [comment]
+1

**Comment by parautenbach** [comment]
Is [this issue](https://github.com/conda/conda-env/issues/75) related to this one?

**Comment by pelson** [comment]
As you've not had a response, I take it you have a script on your path called ``conda-develop`` and ``conda-analysispackage``? It is those which are causing this issue. Don't think these are part of the anaconda suite, so guess they are your own scripts?

**Comment by parautenbach** [comment]
I have no idea where `conda-develop` or `conda-analysispackage` came/come from. My Anaconda version was 2.0 (I upgraded now to 2.2).

**Comment by parautenbach** [comment]
I have no idea where `conda-develop` or `conda-analysispackage` came/come from. My Anaconda version was 2.0 (I upgraded now to 2.2).

**Comment by asmeurer** [comment]
conda develop is coming from conda-build. conda analysispackage probably comes from Wakari.

**Comment by asmeurer** [comment]
@pelson what do you mean available as a standalone library?

**Comment by asmeurer** [comment]
@ijstokes does `conda-develop --help` work for you?

**Comment by asmeurer** [comment]
Never mind, I fixed it.
