### ISSUE TITLE
Received Unexpected Error.

### ISSUE THREAD

**Issue by sastephe** [conda/conda#1333]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'

Current conda install:

             platform : win-64
        conda version : 3.11.0-dirty
  conda-build version : 1.3.5
       python version : 2.7.7.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by elitovka** [comment]
I've got exactly the same problem today:

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'

Current conda install:

             platform : win-64
        conda version : 3.11.0-dirty
  conda-build version : 1.3.5
       python version : 2.7.7.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
We've already removed the code that gives this error. When we update conda, you'll be able to update it with `conda update -f conda`. Until then, I think you should be able to use `conda install -f` with whatever package you were trying to install to (hopefully) fix this.

**Comment by asmeurer** [comment]
Closing because the bug itself is fixed. Feel free to comment here if you need help with the workaround, though.

**Comment by shuwenhe** [comment]
Error:      	Received unexpected error:
