### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by spearman** [conda/conda#13339]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am getting the runtime error described in https://github.com/conda/conda/issues/6624 with Conda 23.9.0 running inside the latest jupyter datascience notebook image:
```
#3 [internal] load metadata for docker.io/jupyter/datascience-notebook:r-4.3.1
#3 DONE 0.5s
#4 [1/5] FROM docker.io/jupyter/datascience-notebook:r-4.3.1@sha256:476c6e673e7d5d8b5059f8680b1c6a988942a79263da651bf302dc696ab311f2
#4 CACHED
#5 [internal] load build context
#5 transferring context: 6.98kB done
#5 DONE 0.0s
#6 https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h
#6 DONE 0.2s
#7 [2/5] ADD https://www.random.org/cgi-bin/randbyte?nbytes=10&format=h skipcache
#7 DONE 0.0s
#8 [3/5] RUN conda --version
#8 0.487 conda 23.9.0
#8 DONE 0.6s
#9 [4/5] RUN conda install psycopg2
#9 2.347 Collecting package metadata (current_repodata.json): ...working... failed
#9 2.723 
#9 2.723 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
#9 2.723 
#9 2.723     Traceback (most recent call last):
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
#9 2.723         return func(*args, **kwargs)
#9 2.723                ^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/cli/main.py", line 78, in main_subshell
#9 2.723         exit_code = do_call(args, parser)
#9 2.723                     ^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 166, in do_call
#9 2.723         result = getattr(module, func_name)(args, parser)
#9 2.723                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
#9 2.723         return func(*args, **kwargs)
#9 2.723                ^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/cli/main_install.py", line 26, in execute
#9 2.723         install(args, parser, "install")
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/cli/install.py", line 320, in install
#9 2.723         unlink_link_transaction = solver.solve_for_transaction(
#9 2.723                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 139, in solve_for_transaction
#9 2.723         unlink_precs, link_precs = self.solve_for_diff(
#9 2.723                                    ^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 200, in solve_for_diff
#9 2.723         final_precs = self.solve_final_state(
#9 2.723                       ^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 345, in solve_final_state
#9 2.723         ssc = self._collect_all_metadata(ssc)
#9 2.723               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/common/io.py", line 85, in decorated
#9 2.723         return f(*args, **kwds)
#9 2.723                ^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 565, in _collect_all_metadata
#9 2.723         index, r = self._prepare(prepared_specs)
#9 2.723                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/solve.py", line 1280, in _prepare
#9 2.723         reduced_index = get_reduced_index(
#9 2.723                         ^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/index.py", line 267, in get_reduced_index
#9 2.723         new_records = SubdirData.query_all(
#9 2.723                       ^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/core/subdir_data.py", line 166, in query_all
#9 2.723         chain.from_iterable(executor.map(subdir_query, channel_urls))
#9 2.723                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 608, in map
#9 2.723         fs = [self.submit(fn, *args) for args in zip(*iterables)]
#9 2.723              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/concurrent/futures/_base.py", line 608, in <listcomp>
#9 2.723         fs = [self.submit(fn, *args) for args in zip(*iterables)]
#9 2.723               ^^^^^^^^^^^^^^^^^^^^^^
#9 2.723       File "/opt/conda/lib/python3.11/site-packages/conda/common/io.py", line 604, in submit
#9 2.723         self._adjust_thread_count()
#9 2.723       File "/opt/conda/lib/python3.11/concurrent/futures/thread.py", line 199, in _adjust_thread_count
#9 2.723         t.start()
#9 2.723       File "/opt/conda/lib/python3.11/threading.py", line 964, in start
#9 2.723         _start_new_thread(self._bootstrap, ())
#9 2.723     RuntimeError: can't start new thread
#9 2.723 
#9 2.723 `$ /opt/conda/bin/conda install psycopg2`
#9 2.723 
#9 2.723   environment variables:
#9 2.723                  CIO_TEST=<not set>
#9 2.723                 CONDA_DIR=/opt/conda
#9 2.723                CONDA_ROOT=/opt/conda
#9 2.723            CURL_CA_BUNDLE=<not set>
#9 2.723          JULIA_DEPOT_PATH=/opt/julia
#9 2.723                LD_PRELOAD=<not set>
#9 2.723                      PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
#9 2.723                           :/bin
#9 2.723        REQUESTS_CA_BUNDLE=<not set>
#9 2.723             SSL_CERT_FILE=<not set>
#9 2.723 
#9 2.723      active environment : None
#9 2.723        user config file : /home/jovyan/.condarc
#9 2.723  populated config files : /opt/conda/.condarc
#9 2.723           conda version : 23.9.0
#9 2.723     conda-build version : not installed
#9 2.723          python version : 3.11.6.final.0
#9 2.723        virtual packages : __archspec=1=x86_64
#9 2.723                           __glibc=2.35=0
#9 2.723                           __linux=5.4.0=0
#9 2.723                           __unix=0=0
#9 2.723        base environment : /opt/conda  (writable)
#9 2.723       conda av data dir : /opt/conda/etc/conda
#9 2.723   conda av metadata url : None
#9 2.723            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
#9 2.723                           https://conda.anaconda.org/conda-forge/noarch
#9 2.723           package cache : /opt/conda/pkgs
#9 2.723                           /home/jovyan/.conda/pkgs
#9 2.723        envs directories : /opt/conda/envs
#9 2.723                           /home/jovyan/.conda/envs
#9 2.723                platform : linux-64
#9 2.723              user-agent : conda/23.9.0 requests/2.31.0 CPython/3.11.6 Linux/5.4.0-1030-aws ubuntu/22.04.3 glibc/2.35
#9 2.723                 UID:GID : 1000:100
#9 2.723              netrc file : None
#9 2.723            offline mode : False
#9 2.723 
#9 2.723 
#9 2.723 An unexpected error has occurred. Conda has prepared the above report.
#9 2.723 If you suspect this error is being caused by a malfunctioning plugin,
#9 2.723 consider using the --no-plugins option to turn off plugins.
#9 2.723 
#9 2.723 Example: conda --no-plugins install <package>
#9 2.723 
#9 2.723 Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
#9 2.723 the command line to run the command without plugins enabled.
#9 2.723 
#9 2.723 Example: CONDA_NO_PLUGINS=true conda install <package>
#9 2.723 
#9 ERROR: executor failed running [/bin/bash -o pipefail -c conda install psycopg2]: runc did not terminate sucessfully
------
 > [4/5] RUN conda install psycopg2:
2.723 If you suspect this error is being caused by a malfunctioning plugin,
2.723 consider using the --no-plugins option to turn off plugins.
2.723 
2.723 Example: conda --no-plugins install <package>
2.723 
2.723 Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
2.723 the command line to run the command without plugins enabled.
2.723 
2.723 Example: CONDA_NO_PLUGINS=true conda install <package>
2.723 
------
WARNING: buildx: git was not found in the system. Current commit information was not captured by the build
ERROR: failed to solve: failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/bash -o pipefail -c conda install psycopg2]: runc did not terminate sucessfully
```

### Conda Info

```shell
#10 0.835      active environment : None
#10 0.835        user config file : /home/jovyan/.condarc
#10 0.835  populated config files : /opt/conda/.condarc
#10 0.835           conda version : 23.9.0
#10 0.835     conda-build version : not installed
#10 0.835          python version : 3.11.6.final.0
#10 0.835        virtual packages : __archspec=1=x86_64
#10 0.835                           __glibc=2.35=0
#10 0.835                           __linux=5.4.0=0
#10 0.835                           __unix=0=0
#10 0.835        base environment : /opt/conda  (writable)
#10 0.835       conda av data dir : /opt/conda/etc/conda
#10 0.835   conda av metadata url : None
#10 0.835            channel URLs : https://conda.anaconda.org/conda-forge/linux-64
#10 0.835                           https://conda.anaconda.org/conda-forge/noarch
#10 0.835           package cache : /opt/conda/pkgs
#10 0.835                           /home/jovyan/.conda/pkgs
#10 0.835        envs directories : /opt/conda/envs
#10 0.835                           /home/jovyan/.conda/envs
#10 0.835                platform : linux-64
#10 0.835              user-agent : conda/23.9.0 requests/2.31.0 CPython/3.11.6 Linux/5.4.0-1030-aws ubuntu/22.04.3 glibc/2.35
#10 0.835                 UID:GID : 1000:100
#10 0.835              netrc file : None
#10 0.835            offline mode : False
```

### Conda Config

```shell
#12 0.591 ==> /opt/conda/.condarc <==
#12 0.591 auto_update_conda: False
#12 0.591 channels:
#12 0.591   - conda-forge
#12 0.591 show_channel_urls: True
```

**Comment by travishathaway** [comment]
Hi @spearman,

Thanks for filing this issue. This is a system related error and there's nothing that can be changed in conda that will help alleviate it. Therefore, I encourage you to instead file an in issue with the maintainers of the docker images:

- https://github.com/jupyter/docker-stacks

Also, it looks like the `mamba` is installed on these images too, so you might give `mamba install ...` a try too to see if that resolves your issue.

In meantime, I'm going to be closing this issue as "off-topic".
