### ISSUE TITLE
Retrieving notices: ...working... failed

### ISSUE THREAD

**Issue by Xnoahg** [conda/conda#13336]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I installed the pyton-conda AUR package, conda does not seem to be installed correctly. I've also tried installing it with the shell script from the anaconda website, and i got the same errors and information about my install.

### Conda Info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
                    ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main_info.py", line 320, in execute
        info_dict = get_info_dict(args.system)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main_info.py", line 176, in get_info_dict
        user_agent=context.user_agent,
                   ^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/auxlib/decorators.py", line 273, in new_fget
        cache[inner_attname] = func(self)
                               ^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/base/context.py", line 846, in user_agent
        builder.append("%s/%s" % self.os_distribution_name_version)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/auxlib/decorators.py", line 273, in new_fget
        cache[inner_attname] = func(self)
                               ^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/base/context.py", line 917, in os_distribution_name_version
        from conda._vendor.distro import id, version
      File "/usr/lib/python3.11/site-packages/conda/_vendor/distro.py", line 1080, in <module>
        _distro = LinuxDistribution()
                  ^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/_vendor/distro.py", line 595, in __init__
        self._lsb_release_info = self._get_lsb_release_info() \
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/_vendor/distro.py", line 939, in _get_lsb_release_info
        raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
    subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 3.

`$ /usr/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
```

### Conda Config

```shell
==> /etc/conda/condarc <==
envs_dirs:
  - ~/.conda/envs
pkgs_dirs:
  - ~/.conda/pkgs

==> /home/xnoahg/.condarc <==
solver: libmamba
```

### Conda list

```shell
EnvironmentLocationNotFound: Not a conda environment: /home/xnoahg/anaconda3
```

**Comment by jaimergp** [comment]
This was fixed in https://github.com/conda/conda/pull/13317. Importing `distro` instantiates the main class so the try/except in 23.1.0 (the one shipped in AUR right now) wouldn't catch that.

So if AUR updates to the upcoming 23.11, then all is good :)

**Comment by jaimergp** [comment]
Alternatively the AUR recipe could depend on the [`lsb-release` package](https://archlinux.org/packages/extra/any/lsb-release/) to guarantee its presence.

**Comment by Xnoahg** [comment]
thanks for that, for now ill just wait until the new 23.11 release and install it that on my laptop. whichever version i have on my desktop seems to work fine anyways so ill just be working with conda on desktop until then.
