### ISSUE TITLE
JSONDecodeError after updating conda

### ISSUE THREAD

**Issue by ShadeAlsha** [conda/conda#13344]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

After successfully updating my Conda version using the command, Conda stopped functioning and is now displaying the following error.

Conda update command: 
`conda install -n base conda=23.7.3 conda-build=3.26.1`

After the update, I am getting this error:
`Traceback (most recent call last):
  File "/anaconda/lib/python3.8/site-packages/conda/exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "/anaconda/lib/python3.8/site-packages/conda/cli/main.py", line 54, in main_subshell
    parser = generate_parser(add_help=True)
  File "/anaconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 115, in generate_parser
    configure_parser_create(sub_parsers)
  File "/anaconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 767, in configure_parser_create
    add_parser_solver(solver_mode_options)
  File "/anaconda/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 1975, in add_parser_solver
    solver.name for solver in context.plugin_manager.get_hook_results("solvers")
  File "/anaconda/lib/python3.8/site-packages/conda/base/context.py", line 492, in plugin_manager
    from ..plugins.manager import get_plugin_manager
  File "/anaconda/lib/python3.8/site-packages/conda/plugins/__init__.py", line 28, in <module>
    from .hookspec import hookimpl  # noqa: F401
  File "/anaconda/lib/python3.8/site-packages/conda/plugins/hookspec.py", line 16, in <module>
    from .types import (
  File "/anaconda/lib/python3.8/site-packages/conda/plugins/types.py", line 15, in <module>
    from ..core.solve import Solver
  File "/anaconda/lib/python3.8/site-packages/conda/core/solve.py", line 30, in <module>
    from ..exceptions import (
  File "/anaconda/lib/python3.8/site-packages/conda/exceptions.py", line 16, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/anaconda/lib/python3.8/site-packages/requests/exceptions.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/anaconda/lib/python3.8/site-packages/conda/cli/main.py", line 109, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/anaconda/lib/python3.8/site-packages/conda/exception_handler.py", line 389, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/anaconda/lib/python3.8/site-packages/conda/exception_handler.py", line 20, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/anaconda/lib/python3.8/site-packages/conda/exception_handler.py", line 52, in handle_exception
    from .exceptions import (
  File "/anaconda/lib/python3.8/site-packages/conda/exceptions.py", line 16, in <module>
    from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/anaconda/lib/python3.8/site-packages/requests/exceptions.py)` 

### Conda Info

```shell
N/A
```

### Conda Config

```shell
N/A
```

### Conda list

```shell
N/A
```

**Comment by dholth** [comment]
It looks like that exception was added in https://github.com/psf/requests/blob/main/HISTORY.md#2270-2022-01-03

What version of requests do you have?

`pip list | grep requests` or

`python3 -c "import requests; print(requests.__version__)"`

**Comment by ShadeAlsha** [comment]
Thank you! Do you know how can I fix this issue?

Here is the version of requests
```
$pip list | grep requests
requests                              2.28.2
requests-oauthlib                     1.3.1
requests-unixsocket                   0.2.0
```

```
$ python3 -c "import requests; print(requests.__version__)"
2.28.2
```

**Comment by dholth** [comment]
`python3 -c "from requests.exceptions import JSONDecodeError`

You can try to upgrade the environment from a separate install or https://github.com/conda/conda-standalone

For example with a new install, without initializing the shell so that the old install continues to be the default,

`~/anaconda3-temporary/bin/conda install -p /anaconda install ...`

**Comment by ShadeAlsha** [comment]
Thank you very much! This solved the issue.

**Comment by rwickman** [comment]
I ran:
`pip` install requests --upgrade`
and if fixed my issue.

**Comment by chamaranilushan** [comment]
python.exe -m pip install --upgrade pip
 solve my issue too

**Comment by erfontesw** [comment]
I have uninstalled "requests" and installed again.
I also ran the update on Conda and all worked out.

**Comment by XizhiMaLY** [comment]
from json import JSONDecodeError can solve it!

把最后的File "/anaconda/lib/python3.8/site-packages/conda/exceptions.py", line 16, in
from requests.exceptions import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/anaconda/lib/python3.8/site-packages/requests/exceptions.py)`

改成
File "/anaconda/lib/python3.8/site-packages/conda/exceptions.py", line 16, in
from json import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError' from 'requests.exceptions' (/anaconda/lib/python3.8/site-packages/requests/exceptions.py)`
