### ISSUE TITLE
conda-smith rerender fails with "Invalid version '>=': invalid operator"

### ISSUE THREAD

**Issue by yarikoptic** [conda/conda#13345]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to `conda smithy rerender -c auto` the http://github.com/conda-forge/ghc-feedstock/ but that fails with

```
❯ conda smithy rerender -c auto
INFO:conda_smithy.configure_feedstock:README rendering is skipped
INFO:conda_smithy.configure_feedstock:__pycache__ rendering is skipped
WARNING: Setting build platform. This is only useful when pretending to be on another platform, such as for rendering necessary dependencies on a non-native platform. I trust that you know what you're doing.
WARNING: Setting build arch. This is only useful when pretending to be on another arch, such as for rendering necessary dependencies on a non-native arch. I trust that you know what you're doing.
WARNING: No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding in variants from internal_defaults
Adding in variants from /home/yoh/.cache/conda-smithy/conda_build_config.yaml
Adding in variants from argument_variants
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/version.py", line 43, in __call__
    return cls._cache_[arg]
           ~~~~~~~~~~~^^^^^
KeyError: '>='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/metadata.py", line 1507, in ms_depends
    ms = MatchSpec(spec)
         ^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/match_spec.py", line 55, in __call__
    return super().__call__(**parsed)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/match_spec.py", line 179, in __init__
    self._match_components = self._build_components(**kwargs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/match_spec.py", line 414, in _build_components
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/_vendor/frozendict/__init__.py", line 21, in __init__
    self._dict = self.dict_cls(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/match_spec.py", line 414, in <genexpr>
    return frozendict(_make_component(key, value) for key, value in kwargs.items())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/match_spec.py", line 428, in _make_component
    matcher = _implementors[field_name](value)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/version.py", line 45, in __call__
    val = cls._cache_[arg] = super().__call__(arg)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/version.py", line 516, in __init__
    vspec_str, matcher, is_exact = self.get_matcher(vspec)
                                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda/models/version.py", line 545, in get_matcher
    raise InvalidVersionSpec(vspec_str, "invalid operator")
conda.exceptions.InvalidVersionSpec: Invalid version '>=': invalid operator

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/conda-dev/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_smithy/cli.py", line 702, in main
    args.subcommand_func(args)
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_smithy/cli.py", line 562, in __call__
    self._call(args, tmpdir)
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_smithy/cli.py", line 567, in _call
    configure_feedstock.main(
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 2552, in main
    render_azure(env, config, forge_dir, return_metadata=True)
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 1520, in render_azure
    return _render_ci_provider(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_smithy/configure_feedstock.py", line 742, in _render_ci_provider
    metas = conda_build.api.render(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/api.py", line 50, in render
    metadata_tuples = render_recipe(
                      ^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/render.py", line 1005, in render_recipe
    rendered_metadata = distribute_variants(
                        ^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/render.py", line 902, in distribute_variants
    mv.dist(),
    ^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/metadata.py", line 1663, in dist
    return f"{self.name()}-{self.version()}-{self.build_id()}"
                                             ^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/metadata.py", line 1646, in build_id
    out = build_string_from_metadata(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/metadata.py", line 726, in build_string_from_metadata
    for ms in metadata.ms_depends("run"):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yoh/miniconda3/envs/conda-dev/lib/python3.11/site-packages/conda_build/metadata.py", line 1511, in ms_depends
    raise RuntimeError(
RuntimeError: Received dictionary as spec.  Note that pip requirements are not supported in conda-build meta.yaml.  Error message: Invalid version '>=': invalid operator
```

which is due to

```
❯ git grep -e '>='
recipe/meta.yaml:    - {{ c_compiler }}_{{ target_platform }} >={{ c_compiler_version }}
```

I guess, and which I guess used to work before.

A similar (different command - `conda export`) error was reported in
- https://github.com/conda/conda/issues/11828
which was closed in favor of 3 year old and still open
- https://github.com/conda/conda/issues/9624

### Conda Info

```shell
active environment : conda-dev
    active env location : /home/yoh/miniconda3/envs/conda-dev
            shell level : 2
       user config file : /home/yoh/.condarc
 populated config files : 
          conda version : 23.10.0
    conda-build version : not installed
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=skylake
                          __cuda=12.0=0
                          __glibc=2.37=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /home/yoh/miniconda3  (writable)
      conda av data dir : /home/yoh/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/yoh/miniconda3/pkgs
                          /home/yoh/.conda/pkgs
       envs directories : /home/yoh/miniconda3/envs
                          /home/yoh/.conda/envs
               platform : linux-64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.11.5 Linux/6.5.0-3-amd64 debian/n/a glibc/2.37 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.3
                UID:GID : 47521:47522
             netrc file : /home/yoh/.netrc
           offline mode : False
```

### Conda list

```shell
# packages in environment at /home/yoh/miniconda3/envs/conda-dev:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     4.0.0              pyhd8ed1ab_0    conda-forge
archspec                  0.2.2              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blinker                   1.7.0              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0             pyhd8ed1ab_0    conda-forge
boolean.py                4.0                pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py311hb755f60_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.21.0               hd590300_0    conda-forge
ca-certificates           2023.7.22            hbcca054_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py311hb3a22ac_0    conda-forge
chardet                   5.2.0           py311h38be061_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
cirun                     0.27               pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     23.10.0         py311h38be061_1    conda-forge
conda-build               3.27.0          py311h38be061_0    conda-forge
conda-forge-pinning       2023.11.17.23.25.44      hd8ed1ab_0    conda-forge
conda-index               0.3.0              pyhd8ed1ab_1    conda-forge
conda-libmamba-solver     23.11.1            pyhd8ed1ab_0    conda-forge
conda-package-handling    2.2.0              pyh38be061_0    conda-forge
conda-package-streaming   0.9.0              pyhd8ed1ab_0    conda-forge
conda-smithy              3.29.0             pyhd8ed1ab_0    conda-forge
cryptography              41.0.5          py311h63ff55d_0    conda-forge
curl                      8.4.0                hca28451_0    conda-forge
dbus                      1.13.6               h5008d03_3    conda-forge
deprecated                1.2.14             pyh1a96a4e_0    conda-forge
distlib                   0.3.7              pyhd8ed1ab_0    conda-forge
editables                 0.3                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.3              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
filelock                  3.13.1             pyhd8ed1ab_0    conda-forge
fmt                       10.1.1               h00ab1b0_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
git                       2.42.0          pl5321h86e50cf_0    conda-forge
gitdb                     4.0.11             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.40             pyhd8ed1ab_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
h11                       0.14.0             pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hatch                     1.7.0              pyhd8ed1ab_0    conda-forge
hatchling                 1.18.0             pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
httpcore                  1.0.2              pyhd8ed1ab_0    conda-forge
httpx                     0.25.1             pyhd8ed1ab_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
hyperlink                 21.0.0             pyhd3deb0d_0    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        6.8.0              pyha770c72_0    conda-forge
importlib_metadata        6.8.0                hd8ed1ab_0    conda-forge
isodate                   0.6.1              pyhd8ed1ab_0    conda-forge
jaraco.classes            3.3.0              pyhd8ed1ab_0    conda-forge
jeepney                   0.8.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               2.4             py311h38be061_3    conda-forge
keyring                   24.3.0          py311h38be061_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.2               h659d440_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libarchive                3.7.2                h039dbb9_0    conda-forge
libcurl                   8.4.0                hca28451_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libglib                   2.78.1               hebfc3b9_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
liblief                   0.12.3               h27087fc_0    conda-forge
libmamba                  1.5.3                had39da4_2    conda-forge
libmambapy                1.5.3           py311hf2555c7_2    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libsolv                   0.7.26               hfc55251_0    conda-forge
libsqlite                 3.44.0               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxml2                   2.11.6               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
license-expression        30.1.1             pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              h516909a_1000    conda-forge
markdown-it-py            3.0.0              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.3           py311h459d7ec_1    conda-forge
mdurl                     0.1.0              pyhd8ed1ab_0    conda-forge
more-itertools            10.1.0             pyhd8ed1ab_0    conda-forge
msrest                    0.6.21             pyh44b312d_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
oauthlib                  3.2.2              pyhd8ed1ab_0    conda-forge
openssl                   3.1.4                hd590300_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
patch                     2.7.6             h7f98852_1002    conda-forge
patchelf                  0.17.2               h58526e2_0    conda-forge
pathspec                  0.11.2             pyhd8ed1ab_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          4_hd590300_perl5    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
pkginfo                   1.9.6              pyhd8ed1ab_0    conda-forge
platformdirs              3.11.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.3.0              pyhd8ed1ab_0    conda-forge
psutil                    5.9.5           py311h459d7ec_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-lief                   0.12.3          py311ha362b79_0    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py311h459d7ec_0    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodome              3.19.0          py311h6601440_1    conda-forge
pygithub                  2.1.1              pyhd8ed1ab_0    conda-forge
pygments                  2.16.1             pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pynacl                    1.5.0           py311h459d7ec_3    conda-forge
pyperclip                 1.8.2              pyhd8ed1ab_2    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.11.6          hab00c5b_0_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-libarchive-c       5.0             py311h38be061_2    conda-forge
python_abi                3.11                    4_cp311    conda-forge
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pyyaml                    6.0.1           py311h459d7ec_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
reproc                    14.2.4.post0         hd590300_1    conda-forge
reproc-cpp                14.2.4.post0         h59595ed_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rich                      13.7.0             pyhd8ed1ab_0    conda-forge
ripgrep                   13.0.0               he8a937b_3    conda-forge
ruamel.yaml               0.18.5          py311h459d7ec_0    conda-forge
ruamel.yaml.clib          0.2.7           py311h459d7ec_2    conda-forge
scrypt                    0.8.20          py311h6965a6d_1    conda-forge
secretstorage             3.3.3           py311h38be061_2    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
shellingham               1.5.4              pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     5.0.0              pyhd8ed1ab_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tomli-w                   1.0.0              pyhd8ed1ab_0    conda-forge
tomlkit                   0.12.3             pyha770c72_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
trove-classifiers         2023.11.14         pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
typer                     0.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.8.0                hd8ed1ab_0    conda-forge
typing_extensions         4.8.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
userpath                  1.7.0              pyhd8ed1ab_0    conda-forge
virtualenv                20.24.6            pyhd8ed1ab_0    conda-forge
vsts-python-api           0.1.25             pyhd8ed1ab_1    conda-forge
wheel                     0.41.3             pyhd8ed1ab_0    conda-forge
wrapt                     1.16.0          py311h459d7ec_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
yaml-cpp                  0.8.0                h59595ed_0    conda-forge
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zstandard                 0.22.0          py311haa97af0_0    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by travishathaway** [comment]
Hi @yarikoptic,

The conda smithy command is not a part of this repository. Please file issues related to conda smithy here:

- https://github.com/conda-forge/conda-smithy/issues

I will now be closing this issue.
