### ISSUE TITLE
Conda installing of a local package causes a UnicodeDecodeError

### ISSUE THREAD

**Issue by tab1293** [conda/conda#1335]
When trying to install packages built from the conda-recipes on GitHub, in my case ICU and yasm, I get an UnicodeDecodeError. Here is the relevant output: 
```
tom@thinkpad:~/miniconda3/conda-bld/linux-64$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.12.0
  conda-build version : 1.12.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/tom/miniconda3  (writable)
  default environment : /home/tom/miniconda3
     envs directories : /home/tom/miniconda3/envs
        package cache : /home/tom/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

tom@thinkpad:~/miniconda3/conda-bld/linux-64$ conda install --file icu-54.1-0.tar.bz2 
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/tom/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/tom/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 203, in main
    args_func(args, p)
  File "/home/tom/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/tom/miniconda3/lib/python3.4/site-packages/conda/cli/common.py", line 609, in inner
    return func(args, parser)
  File "/home/tom/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/tom/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 190, in install
    specs.extend(common.specs_from_url(args.file, json=args.json))
  File "/home/tom/miniconda3/lib/python3.4/site-packages/conda/cli/common.py", line 453, in specs_from_url
    for line in open(path):
  File "/home/tom/miniconda3/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 11: invalid continuation byte
```
Does anyone know what may be causing this error and how I can go about fixing it?

**Comment by asmeurer** [comment]
--file is used to point to a requirements.txt file, with a list of specifications. If you want to install a package built from conda-build, use `--use-local`, like `conda install --use-local icu`. If you want to install from a package file just install the file, like `conda install icu-54.1-0.tar.bz2`.
