### ISSUE TITLE
IOError could not process local .tar.bz2 file to install a package

### ISSUE THREAD

**Issue by asgarJ** [conda/conda#1336]
C:\Anaconda>conda install pynsca-1.5-py27_0.tar.bz2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

```
    Traceback (most recent call last):
      File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
        sys.exit(main())
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
        args_func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
        args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
        return func(args, parser)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 51, in execute
        install.install(args, parser, 'install')
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 219, in install
        verbose=not args.quiet)
      File "C:\Anaconda\lib\site-packages\conda\misc.py", line 202, in install_local_packages
        shutil.copyfile(src_path, dst_path)
      File "C:\Anaconda\lib\shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: 'pynsca-1.5-py27_0.tar.bz2'`
```

C:\Anaconda>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.11.0-dirty
    conda-build version : 1.11.0
   python version : 2.7.9.final.0
 requests version : 2.7.0
 root environment : C:\Anaconda  (writable)
 default environment : C:\Anaconda
 envs directories : C:\Anaconda\envs
    package cache : C:\Anaconda\pkgs
     channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                    https://repo.continuum.io/pkgs/free/noarch/
                    https://repo.continuum.io/pkgs/pro/win-64/
                    https://repo.continuum.io/pkgs/pro/noarch/
      config file : C:\Users\a.javadov\.condarc
is foreign system : False`
```

**Comment by soapy1** [comment]
I think what you want to do for installing local packages is `conda install --use-local pynsc`
