### ISSUE TITLE
JSON error with conda bundle and Python 3.4

### ISSUE THREAD

**Issue by johanneskoester** [conda/conda#1341]
When trying to extract my self-created bundle, I get the following error:

```
$ conda bundle -x ~/scms/vispr/vispr/workflow/bundle-2bd669c6aa587bd3b15c204274bd7022b27f0e2e-0.tar.bz2 
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/koester/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/koester/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 203, in main
    args_func(args, p)
  File "/home/koester/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/koester/miniconda3/lib/python3.4/site-packages/conda/cli/main_bundle.py", line 94, in execute
    bundle.clone_bundle(path, prefix, args.bundle_name)
  File "/home/koester/miniconda3/lib/python3.4/site-packages/conda/bundle.py", line 128, in clone_bundle
    meta = json.load(t.extractfile('info/index.json'))
  File "/home/koester/miniconda3/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/koester/miniconda3/lib/python3.4/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'
```

Output of conda info:

```
Current conda install:

             platform : linux-64
        conda version : 3.12.0
  conda-build version : 1.12.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/koester/miniconda3  (writable)
  default environment : /home/koester/miniconda3
     envs directories : /home/koester/miniconda3/envs
        package cache : /home/koester/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/koester/.condarc
    is foreign system : False
```

**Comment by soapy1** [comment]
@johanneskoester is this still an issue for you?

**Comment by johanneskoester** [comment]
Well, it seems like the bundle subcommand isn't even available anymore. Has it been deprecated?

**Comment by kalefranz** [comment]
As of 4.2, yes. We may bring it back in through conda-build if there's interest.

**Comment by AtmaMani** [comment]
@kalefranz with `conda-build` deprecated, what is the best approach if I want to transport my environment to a machine without internet.
