### ISSUE TITLE
Merge multiple json objects into one when --json is used

### ISSUE THREAD

**Issue by samhaese** [conda/conda#13431]
### What is the idea?

Conda commands have the --json flag to format the output as a json object.

This can be parsed in python like this:

`info_dictionary = json.loads(subprocess.run('conda info --json', shell=True, capture_output=True).stdout)`

However, the json.loads method breaks if conda decides to return multiple json objects instead of one.  Example:

```
>>>conda create -n new_env_pywin32 --file=requirements.txt -y --json
```

```
{
  "error": "Multiple Errors Encountered.",
  "errors": [
    {
      "caused_by": "None",
      "error": "SafetyError: The package for pywin32 located at C:\\Users\\sdhaese\\.conda\\pkgs\\pywin32-305-py311h2bbff1b_0_corrupted\nappears to be corrupted. The path 'Lib/site-packages/win32com/gen_py/dicts.dat'\nhas an incorrect size.\n  reported size: 10 bytes\n  actual size: 32233 bytes\n",
      "exception_name": "SafetyError",
      "exception_type": "<class 'conda.exceptions.SafetyError'>",
      "message": "The package for pywin32 located at C:\\Users\\sdhaese\\.conda\\pkgs\\pywin32-305-py311h2bbff1b_0_corrupted\nappears to be corrupted. The path 'Lib/site-packages/win32com/gen_py/dicts.dat'\nhas an incorrect size.\n  reported size: 10 bytes\n  actual size: 32233 bytes\n"
    }
  ],
  "exception_name": "CondaMultiError",
  "exception_type": "<class 'conda.CondaMultiError'>"
}

{
  "actions": {
    "FETCH": [],
    "LINK": [
      {
        "base_url": "https://repo.anaconda.com/pkgs/main",
        "build_number": 1,
        "build_string": "mkl",
        "channel": "pkgs/main",
        "dist_name": "blas-1.0-mkl",
        "name": "blas",
        "platform": "win-64",
        "version": "1.0"
      },
      {
        "base_url": "https://repo.anaconda.com/pkgs/main",
        "build_number": 0,
        "build_string": "haa95532_0",
        "channel": "pkgs/main",
        "dist_name": "ca-certificates-2023.08.22-haa95532_0",
        "name": "ca-certificates",
        "platform": "win-64",
        "version": "2023.08.22"
      },
      {
        "base_url": "https://repo.anaconda.com/pkgs/main",
        ...
```

```
py_dictionary = json.loads(subprocess.run('conda create -n new_env_pywin32 --file=requirements.txt -y --json', shell=True, capture_output=True))
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sdhaese\.conda\envs\test_python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\sdhaese\.conda\envs\test_python39\lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 16 column 1 (char 887)
```

### Why is this needed?

Parsing json should be straight forward

### What should happen?

Multiple json objects returned from a conda command should be merged into one.

**Comment by kenodegard** [comment]
@samhaese When json objects are being printed to stdout they are delimited by the `\0` null character:

```python
[
    json.loads(data)
    for data in subprocess.run(
        'conda create -n new_env_pywin32 --file=requirements.txt -y --json',
        shell=True,
        capture_output=True,
    ).split("\0")
]
```

**Comment by samhaese** [comment]
Very helpful advice, thank you.
