### ISSUE TITLE
[question] Failed to install packages - didn't find info-linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5 component in /.../pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5.conda

### ISSUE THREAD

**Issue by siupenyau** [conda/conda#13432]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Hi,
When I tried to install any packages, create new environment with package installation, and even update conda, I received the following error:

```
Collecting package metadata (current_repodata.json): \ WARNING conda.models.version:get_matcher(556): Using .* with relational operator is superfluous and deprecated and will be removed in a future version of conda. Your spec was 1.7.1.*, but conda is ignoring the .* and treating it as 1.7.1
done
Solving environment: / 
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge/linux-64::brotli-python-1.0.9-py311ha362b79_9, conda-forge/noarch::urllib3-1.26.18-pyhd8ed1ab_0
  - conda-forge/linux-64::brotlipy-0.7.0-py311h459d7ec_1006, conda-forge/noarch::urllib3-1.26.15-pyhd8ed1abdone


==> WARNING: A newer version of conda exists. <==
  current version: 23.7.4
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c conda-forge conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0



# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 361, in _make_single_record
        repodata_record = read_repodata_json(extracted_package_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/gateways/disk/read.py", line 145, in read_repodata_json
        with open(join(extracted_package_directory, "info", "repodata_record.json")) as fi:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/common/compat.py", line 71, in open
        return io_open(
               ^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5/info/repodata_record.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 381, in _make_single_record
        raw_json_record = read_index_json(extracted_package_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/gateways/disk/read.py", line 130, in read_index_json
        with open(join(extracted_package_directory, "info", "index.json")) as fi:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/common/compat.py", line 71, in open
        return io_open(
               ^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: '/home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5/info/index.json'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/cli/main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 167, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/cli/main_update.py", line 26, in execute
        install(args, parser, "update")
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/cli/install.py", line 394, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/cli/install.py", line 412, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/link.py", line 1217, in print_transaction_summary
        legacy_action_groups = self._make_legacy_action_groups()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/link.py", line 1197, in _make_legacy_action_groups
        self._pfe.prepare()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 734, in prepare
        self.paired_actions.update(
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 735, in <genexpr>
        (prec, self.make_actions_for_record(prec)) for prec in self.link_precs
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 588, in make_actions_for_record
        extracted_pcrec = next(
                          ^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 589, in <genexpr>
        (
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 592, in <genexpr>
        PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 162, in query
        for pcrec in self._package_cache_records.values()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 299, in _package_cache_records
        self.load()
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 123, in load
        package_cache_record = self._make_single_record(base_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/core/package_cache_data.py", line 408, in _make_single_record
        extract_tarball(
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda/gateways/disk/create.py", line 232, in extract_tarball
        conda_package_handling.api.extract(
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_handling/api.py", line 77, in extract
        format.extract(fn, dest_dir, components=components)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_handling/conda_fmt.py", line 46, in extract
        _extract(str(fn), str(dest_dir), components=components)
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_handling/streaming.py", line 35, in _extract
        stream = package_streaming.stream_conda_component(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/user/anaconda3/lib/python3.11/site-packages/conda_package_streaming/package_streaming.py", line 133, in stream_conda_component
        raise LookupError(f"didn't find {component_name} component in {filename}")
    LookupError: didn't find info-linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5 component in /home/user/anaconda3/pkgs/linux-ppc64le_perl-5.32.1-4_ha17a0cc_perl5.conda

`$ /home/user/anaconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/user/anaconda3/bin/conda
             CONDA_PREFIX=/home/user/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/user/anaconda3/bin/python
               CONDA_ROOT=/home/user/anaconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                FTP_PROXY=<set>
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
               LD_PRELOAD=<not set>
                 NO_PROXY=<set>
                     PATH=/home/user/anaconda3/bin:/home/user/anaconda3/condabin:/usr/loca
                          l/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lo
                          cal/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : base
    active env location : /home/user/anaconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/user/anaconda3  (writable)
      conda av data dir : /home/user/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Linux/5.14.0-1034-oem ubuntu/20.04.4 glibc/2.31
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.
```

I found that the folder of that mentioned package in anaconda3/pkgs/ was empty. Was my conda corrupted? I cannot install new packages or update conda anymore. Do I need to reinstall the conda? Your help will be highly appreciated.

With best wishes,

Timothy Ng

### Conda Info

```shell
active environment : base
    active env location : /home/user/anaconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.31=0
                          __linux=5.14.0=0
                          __unix=0=0
       base environment : /home/user/anaconda3  (writable)
      conda av data dir : /home/user/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/anaconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/anaconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Linux/5.14.0-1034-oem ubuntu/20.04.4 glibc/2.31 aau/0.4.2 c/q1sKoC6mzSnoqyyXopbG7Q s/wXMyZs5_kHee6mAJb8bUSQ e/BJpVYGDvel5mK505mzH5FQ
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by travishathaway** [comment]
Hi @siupenyau,

Thanks for filing this issue. I have a couple suggestions for you:

1. Run `conda clean --all`; this will clear your local cache and may resolve the issue.
2. Do not use `conda-forge` in your base environment; see [my comment here](https://github.com/conda/conda/issues/13411#issuecomment-1849747648) for a better explanation

I'm also curious. How did a `ppc64` package make its way to your computer if your architecture is `x86_64`?

**Comment by siupenyau** [comment]
Hi Travis,

Thank you very much for your suggestions. The suggestion 1) helped me to solve the problem at this moment. I am trying to downloading the other packages.

I also remove conda-forge from .condarc. I will come back to here if I have any questions.

With best wishes,

Timothy Ng
