### ISSUE TITLE
An unexpected error has occurred. Conda has prepared the above report.

### ISSUE THREAD

**Issue by Raymond165** [conda/conda#13446]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The following error occurred when I downloaded the mamba installation package from the conda-forge official community and installed it.
I confirm that I have selected the mamba installation package according to my computer system and python version.

### Conda Info

```shell
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 361, in _make_single_record
        repodata_record = read_repodata_json(extracted_package_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\gateways\disk\read.py", line 145, in read_repodata_json
        with open(join(extracted_package_directory, "info", "repodata_record.json")) as fi:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\common\compat.py", line 71, in open
        return io_open(
               ^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anaconda\\pkgs\\win-64_mamba-1.5.5-py311h8cb466b_0\\info\\repodata_record.json'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 381, in _make_single_record
        raw_json_record = read_index_json(extracted_package_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\gateways\disk\read.py", line 130, in read_index_json
        with open(join(extracted_package_directory, "info", "index.json")) as fi:
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\common\compat.py", line 71, in open
        return io_open(
               ^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Anaconda\\pkgs\\win-64_mamba-1.5.5-py311h8cb466b_0\\info\\index.json'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\Lib\site-packages\conda\exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\cli\main.py", line 64, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\cli\conda_argparse.py", line 167, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\notices\core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\cli\main_install.py", line 26, in execute
        install(args, parser, "install")
      File "D:\Anaconda\Lib\site-packages\conda\cli\install.py", line 203, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "D:\Anaconda\Lib\site-packages\conda\misc.py", line 90, in explicit
        pfe.execute()
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 755, in execute
        self.prepare()
      File "D:\Anaconda\Lib\site-packages\conda\common\io.py", line 84, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 734, in prepare
        self.paired_actions.update(
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 735, in <genexpr>
        (prec, self.make_actions_for_record(prec)) for prec in self.link_precs
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 588, in make_actions_for_record
        extracted_pcrec = next(
                          ^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 589, in <genexpr>
        (
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 592, in <genexpr>
        PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 155, in query
        for pcrec in self._package_cache_records.values()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 299, in _package_cache_records
        self.load()
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 123, in load
        package_cache_record = self._make_single_record(base_name)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda\core\package_cache_data.py", line 408, in _make_single_record
        extract_tarball(
      File "D:\Anaconda\Lib\site-packages\conda\gateways\disk\create.py", line 232, in extract_tarball
        conda_package_handling.api.extract(
      File "D:\Anaconda\Lib\site-packages\conda_package_handling\api.py", line 77, in extract
        format.extract(fn, dest_dir, components=components)
      File "D:\Anaconda\Lib\site-packages\conda_package_handling\conda_fmt.py", line 46, in extract
        _extract(str(fn), str(dest_dir), components=components)
      File "D:\Anaconda\Lib\site-packages\conda_package_handling\streaming.py", line 35, in _extract
        stream = package_streaming.stream_conda_component(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anaconda\Lib\site-packages\conda_package_streaming\package_streaming.py", line 133, in stream_conda_component
        raise LookupError(f"didn't find {component_name} component in {filename}")
    LookupError: didn't find info-win-64_mamba-1.5.5-py311h8cb466b_0 component in D:\Anaconda\pkgs\win-64_mamba-1.5.5-py311h8cb466b_0.conda

`$ D:\Anaconda\Scripts\conda-script.py install --use-local mamba-1.5.5-py311h8cb466b_0.conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=pynkdv
                CONDA_EXE=D:\Anaconda\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Anaconda\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=D:\Anaconda\envs\pynkdv
           CONDA_PREFIX_1=D:\Anaconda
    CONDA_PROMPT_MODIFIER=(pynkdv)
         CONDA_PYTHON_EXE=D:\Anaconda\python.exe
               CONDA_ROOT=D:\Anaconda
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\刘Xuh-
               LD_PRELOAD=<not set>
                     PATH=D:\Anaconda\envs\pynkdv;D:\Anaconda\envs\pynkdv\Library\mingw-
                          w64\bin;D:\Anaconda\envs\pynkdv\Library\usr\bin;D:\Anaconda\envs\pynkd
                          v\Library\bin;D:\Anaconda\envs\pynkdv\Scripts;D:\Anaconda\envs\pynkdv\
                          bin;D:\Anaconda\condabin;D:\Moves3\bin;C:\Windows\system32;C:\Windows;
                          C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:
                          \Windows\System32\OpenSSH;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA
                          NvDLISR;C:\Program Files\dotnet;C:\WINDOWS\system32;C:\WINDOWS;C:\WIND
                          OWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOW
                          S\System32\OpenSSH;D:\Anaconda;D:\Anaconda\Scripts;D:\Anaconda\Library
                          \mingw-w64\bin;D:\Anaconda\Library\usr\bin;D:\Anaconda\Library\bin;.
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=D:\Anaconda\Library\ssl\cacert.pem

     active environment : pynkdv
    active env location : D:\Anaconda\envs\pynkdv
            shell level : 2
       user config file : C:\Users\刘Xuh-\.condarc
 populated config files :
          conda version : 23.7.4
    conda-build version : 3.26.1
         python version : 3.11.5.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.7=0
                          __win=0=0
       base environment : D:\Anaconda  (writable)
      conda av data dir : D:\Anaconda\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda\pkgs
                          C:\Users\刘Xuh-\.conda\pkgs
                          C:\Users\刘Xuh-\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda\envs
                          C:\Users\刘Xuh-\.conda\envs
                          C:\Users\刘Xuh-\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.7.4 requests/2.31.0 CPython/3.11.5 Windows/10 Windows/10.0.22621 aau/0.4.2 c/IjusTa-MtRrhzF_aU-RhOw s/F4S87WpU3AWASVQPnPpa4g e/0UqlHnidl4SfQmv9w8KQ8Q
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by travishathaway** [comment]
Hi @Raymond165,

A similar error was recently reported here:

- https://github.com/conda/conda/issues/13432

In this case, running `conda clean --all` resolved the issue. Please let us know if this works for you.

**Comment by Raymond165** [comment]
Hi Travis,
Thank you very much for your advice. I found a folder named win-64_mamba-1.5.5-py311h8cb466b_0 and conda file with the same name in the D:\\Anaconda\\pkgs folder in my computer. By deleting them, I solved the above problem.

**Comment by kenodegard** [comment]
Closing since this has been resolved
