### ISSUE TITLE
Conda installs an incompatible package (azure-keyvault) for Python 3.6

### ISSUE THREAD

**Issue by random-forest1** [conda/conda#13464]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I used the environment yml file below to create an environment using the command `conda env create -p e:\anaconda_environments\py36 --file minimal_environment.yml`.

```
name: py36
dependencies:
  - python=3.6
  - azure-keyvault
```

According to docs, `azure-keyvault` is only supported for `Python>=3.7` and thus the above attempt to create an environment should result in an `UnsatisfiableError` .

See: [https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-cli#prerequisites](https://learn.microsoft.com/en-us/azure/key-vault/secrets/quick-create-python?tabs=azure-cli#prerequisites)

However, the environment is created successfully. As expected, an attempt to import the relevant package results in an error below as `from __future__ import annotations` is only available for `Python>=3.7`:

```
Python 3.6.13 |Anaconda, Inc.| (default, Mar 16 2021, 11:37:27) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import azure.keyvault.secrets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\anaconda_environments\py36\lib\site-packages\azure\keyvault\secrets\__init__.py", line 5, in <module>
    from ._models import DeletedSecret, KeyVaultSecret, KeyVaultSecretIdentifier, SecretProperties
  File "e:\anaconda_environments\py36\lib\site-packages\azure\keyvault\secrets\_models.py", line 5, in <module>
    from ._shared import parse_key_vault_id
  File "e:\anaconda_environments\py36\lib\site-packages\azure\keyvault\secrets\_shared\__init__.py", line 12, in <module>
    from .challenge_auth_policy import ChallengeAuthPolicy
  File "e:\anaconda_environments\py36\lib\site-packages\azure\keyvault\secrets\_shared\challenge_auth_policy.py", line 20, in <module>
    from azure.core.exceptions import ServiceRequestError
  File "e:\anaconda_environments\py36\lib\site-packages\azure\core\__init__.py", line 31, in <module>
    from ._pipeline_client import PipelineClient
  File "e:\anaconda_environments\py36\lib\site-packages\azure\core\_pipeline_client.py", line 26
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined
```

Is the above a bug in `conda` or a bug in how `azure-keyvault` is packaged?

### Conda Info

```shell
active environment : e:\anaconda_environments\py36
    active env location : e:\anaconda_environments\py36
            shell level : 2
       user config file : C:\Users\[user name]\.condarc
 populated config files : C:\Users\[user name]\.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=23.11.0=0
                          __win=0=0
       base environment : C:\ProgramData\miniconda3  (read only)
      conda av data dir : C:\ProgramData\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.cloud/repo/main/win-64
                          https://repo.anaconda.cloud/repo/main/noarch
                          https://repo.anaconda.cloud/repo/r/win-64
                          https://repo.anaconda.cloud/repo/r/noarch
                          https://repo.anaconda.cloud/repo/msys2/win-64
                          https://repo.anaconda.cloud/repo/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\ProgramData\miniconda3\pkgs
                          C:\Users\[user name]\.conda\pkgs
                          C:\Users\[user name]\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\[user name]\.conda\envs
                          C:\ProgramData\miniconda3\envs
                          C:\Users\[user name]\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Windows/10 Windows/10.0.17763 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\[user name]\.condarc <==
env_prompt: ({name})
add_anaconda_token: True
channels:
  - defaults
  - conda-forge
default_channels:
  - https://repo.anaconda.cloud/repo/main
  - https://repo.anaconda.cloud/repo/r
  - https://repo.anaconda.cloud/repo/msys2
restore_free_channel: False
solver: libmamba
```

### Conda list

```shell
# packages in environment at e:\anaconda_environments\py36:
#
# Name                    Version                   Build  Channel
azure-common              1.1.27             pyhd3eb1b0_0    defaults
azure-core                1.29.5             pyhd8ed1ab_0    conda-forge
azure-keyvault            4.3.0              pyhd8ed1ab_0    conda-forge
azure-keyvault-certificates 4.6.0              pyhd8ed1ab_0    conda-forge
azure-keyvault-keys       4.7.0              pyhd8ed1ab_0    conda-forge
azure-keyvault-secrets    4.6.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4              py36haa95532_0    defaults
brotlipy                  0.7.0           py36h2bbff1b_1003    defaults
ca-certificates           2023.12.12           haa95532_0    defaults
certifi                   2021.5.30        py36haa95532_0    defaults
cffi                      1.14.6           py36h2bbff1b_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
cryptography              35.0.0           py36h71e12ea_0    defaults
idna                      3.3                pyhd3eb1b0_0    defaults
isodate                   0.6.0              pyhd3eb1b0_1    defaults
msrest                    0.6.21             pyhd3eb1b0_0    defaults
oauthlib                  3.2.0              pyhd3eb1b0_1    defaults
openssl                   1.1.1w               h2bbff1b_0    defaults
pip                       21.2.2           py36haa95532_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyjwt                     2.8.0              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py36haa95532_0    defaults
python                    3.6.13               h3758d61_0    defaults
requests                  2.27.1             pyhd3eb1b0_0    defaults
requests-oauthlib         1.3.0                      py_0    defaults
setuptools                58.0.4           py36haa95532_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
sqlite                    3.41.2               h2bbff1b_0    defaults
typing-extensions         4.1.1                hd3eb1b0_0    defaults
typing_extensions         4.1.1              pyh06a4308_0    defaults
urllib3                   1.26.8             pyhd3eb1b0_0    defaults
vc                        14.2                 h21ff451_1    defaults
vs2015_runtime            14.27.29016          h5e58377_2    defaults
wheel                     0.37.1             pyhd3eb1b0_0    defaults
win_inet_pton             1.1.0            py36haa95532_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
```

**Comment by travishathaway** [comment]
Hi @random-forest1,

If you are using the package provided by `conda-forge`, then this is a problem with the package itself.

Please contact the maintainers of that package. For `conda-forge` this is the appropriate place to file an issue:

- https://github.com/conda-forge/azure-keyvault-feedstock

Otherwise, contact the maintainers at which ever channel you are getting it from.

I will be closing this issue.
