### ISSUE TITLE
New conda install crashes on `conda init`

### ISSUE THREAD

**Issue by pulpocaminante** [conda/conda#13472]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I installed conda with paru, run `conda init bash` and this happens:

```
(base) [amnesia@dead]$ conda init bash

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main.py", line 69, in main_subshell
        exit_code = do_call(args, p)
                    ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 91, in do_call
        return getattr(module, func_name)(args, parser)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/cli/main_init.py", line 33, in execute
        return initialize(context.conda_prefix, selected_shells, for_user, args.system,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/core/initialize.py", line 118, in initialize
        run_plan_elevated(plan2)
      File "/usr/lib/python3.11/site-packages/conda/core/initialize.py", line 714, in run_plan_elevated
        result = subprocess_call(
                 ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/site-packages/conda/gateways/subprocess.py", line 98, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/subprocess.py", line 1209, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/subprocess.py", line 2088, in _communicate
        input_view = memoryview(self._input)
                     ^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /usr/bin/conda init bash`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/usr/bin/conda
             CONDA_PREFIX=/usr
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/usr/bin/python
               CONDA_ROOT=/usr
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/bin:/usr/condabin:/usr/local/bin:/usr/bin:/home/amnesia/.cargo/bi
                          n:/home/amnesia/.fzf/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>
              socks_proxy=<set>

     active environment : base
    active env location : /usr
            shell level : 1
       user config file : /home/amnesia/.condarc
 populated config files : /etc/conda/condarc
          conda version : 23.1.0
    conda-build version : not installed
         python version : 3.11.6.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.38=0
                          __linux=6.6.7=0
                          __unix=0=0
       base environment : /usr  (read only)
      conda av data dir : /usr/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/amnesia/.conda/pkgs
       envs directories : /home/amnesia/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/23.1.0 requests/2.31.0 CPython/3.11.6 Linux/6.6.7-zen1-1-zen arch/rolling glibc/2.38
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

(base) [amnesia@dead]$ 
```

**Comment by z-a-f-LB** [comment]
Years later, this still comes up :)

If you are still facing the issue, here are some steps you might wanna take.
Try if your conda works after each, to see what works

*Note: This is for bash on linux-like*

**Change the permissions of your `rc` files**

```shell
sudo chown $USER:$USER $HOME/.bashrc
chmod 644 $HOME/.bashrc
```

**Change ownership of the conda root**

> [!CAUTION]
> Check the value of the `root_prefix` before changing the ownership.
> It might be one of the places where you shouldn't be at all...

```shell
root_prefix=$(conda config --show root_prefix 2>/dev/null | cut -d' ' -f2)
if [[ -n $root_prefix ]]; then
    echo "Your root_prefix is '${root_prefix}'"
    read -p "Press any key to change ownership (Ctrl+C to interrupt) " -n1 -s
    sudo chown -R $USER:$USER $root_prefix
fi
```
