### ISSUE TITLE
App Update Error

### ISSUE THREAD

**Issue by assiaelgouacem** [conda/conda#1347]
Traceback (most recent call last):
  File "/Users/assiaelgouacem/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    use_json = getattr(args, 'json', False)
  File "/Users/assiaelgouacem/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
  File "/Users/assiaelgouacem/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 387, in install
  File "/Users/assiaelgouacem/anaconda/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
  File "/Users/assiaelgouacem/anaconda/lib/python2.7/site-packages/conda/plan.py", line 571, in execute_plan
  File "/Users/assiaelgouacem/anaconda/lib/python2.7/site-packages/conda/install.py", line 574, in unlink
    except ImportError:
IOError: [Errno 2] No such file or directory: '/Users/assiaelgouacem/anaconda/conda-meta/conda-3.7.0-py27_0.json'

**Comment by ccordoba12** [comment]
Two questions:

1. What app were you trying to update?
2. Could you at least do `conda update conda`? It seems your conda version is a bit old (current version is `3.12.0`)

**Comment by soapy1** [comment]
@assiaelgouacem is this still an issue for you?
