### ISSUE TITLE
requests.utils.getproxies() AttributeError: 'module' object has no attribute 'getproxies'

### ISSUE THREAD

**Issue by taigne** [conda/conda#1349]
C:\Windows\System32>conda update ipython
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 253, in install
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 528, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 225, in fetch_index
    session = CondaSession()
  File "C:\Anaconda\lib\site-packages\conda\connection.py", line 60, in __init__
    self.proxies = get_proxy_servers()
  File "C:\Anaconda\lib\site-packages\conda\config.py", line 312, in get_proxy_servers
    return requests.utils.getproxies()
AttributeError: 'module' object has no attribute 'getproxies'

C:\Windows\System32>conda info
Current conda install:

             platform : win-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 1.2.2
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
The problem is your old requests version. Try to update it with `pip install -U requests`. Also check that you don't have PYTHONPATH set.

**Comment by taigne** [comment]
Thank you! I did have PYTHONPATH set; clearing it resolved the issue.

--
Taigne Hammock* · **(310) 776-5007*
*www.linkedin.com/in/taignehammock
<http://www.linkedin.com/in/taignehammock>*

**Comment by asmeurer** [comment]
Great. We're probably going to add something about this to the troubleshooting page in our docs.
