### ISSUE TITLE
Error in conda init zsh command(on miniconda + macOS Ventura + zsh) 

### ISSUE THREAD

**Issue by ytooyama** [conda/conda#13506]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

If you try to set up according to the installation procedure, conda init zsh will fail.
https://docs.conda.io/projects/conda/en/stable/user-guide/install/macos.html

When I was using bash, the miniconda was working well. Doesn't it work on macOS + zsh?

```
% conda --version
conda 23.11.0

% conda doctor
Environment Health Report for: /Users/tooyama/miniconda3
Altered Files:
conda-23.11.0-py311hca03da5_0: 1
Environment listed in environments.txt file: ✅
Missing Files:
python.app-3-py311h80987f9_0: 7

% source ~/miniconda3/bin/activate
% conda init zsh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/main_init.py", line 155, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 137, in initialize
        run_plan(plan2)
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 797, in run_plan
        result = globals()[step["function"]](
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 1453, in init_sh_user
        rc_content = fh.read()
                     ^^^^^^^^^
      File "<frozen codecs>", line 322, in decode
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 445: invalid start byte

`$ /Users/tooyama/miniconda3/bin/conda init zsh`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/tooyama/miniconda3/bin/conda
             CONDA_PREFIX=/Users/tooyama/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/tooyama/miniconda3/bin/python
               CONDA_ROOT=/Users/tooyama/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/tooyama/miniconda3/bin:/Users/tooyama/miniconda3/condabin:/Appl
                          ications/UTM.app/Contents/MacOS:/opt/homebrew/opt/libpq/bin:/opt/homeb
                          rew/sbin:/opt/homebrew/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/l
                          ocal/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/
                          usr/local/go/bin:/opt/X11/bin:/opt/podman/bin:/Library/Apple/usr/bin:/
                          var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/b
                          in:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
                          :/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/apple
                          internal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/tooyama/miniconda3
            shell level : 1
       user config file : /Users/tooyama/.condarc
 populated config files : /Users/tooyama/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=13.6.3=0
                          __unix=0=0
       base environment : /Users/tooyama/miniconda3  (writable)
      conda av data dir : /Users/tooyama/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tooyama/miniconda3/pkgs
                          /Users/tooyama/.conda/pkgs
       envs directories : /Users/tooyama/miniconda3/envs
                          /Users/tooyama/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Darwin/22.6.0 OSX/13.6.3 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 503:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
Timeout reached. No report sent.
```

Workaround:
I was able to move the miniconda in this way.
https://gist.github.com/ytooyama/46fc1399c455c5fbf254c4bf8f32cf79

### Conda Info

```shell
% conda info

     active environment : base
    active env location : /Users/tooyama/miniconda3
            shell level : 1
       user config file : /Users/tooyama/.condarc
 populated config files : /Users/tooyama/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=13.6.3=0
                          __unix=0=0
       base environment : /Users/tooyama/miniconda3  (writable)
      conda av data dir : /Users/tooyama/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tooyama/miniconda3/pkgs
                          /Users/tooyama/.conda/pkgs
       envs directories : /Users/tooyama/miniconda3/envs
                          /Users/tooyama/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Darwin/22.6.0 OSX/13.6.3 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
% conda config --show-sources
==> /Users/tooyama/.condarc <==
auto_activate_base: False
channels:
  - defaults
```

### Conda list

```shell
% conda list --show-channel-urls
# packages in environment at /Users/tooyama/miniconda3:
#
# Name                    Version                   Build  Channel
archspec                  0.2.1              pyhd3eb1b0_0    defaults
boltons                   23.0.0          py311hca03da5_0    defaults
brotli-python             1.0.9           py311h313beb8_7    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.1               h80987f9_0    defaults
ca-certificates           2023.12.12           hca03da5_0    defaults
certifi                   2023.11.17      py311hca03da5_0    defaults
cffi                      1.16.0          py311h80987f9_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.11.0         py311hca03da5_0    defaults
conda-content-trust       0.2.0           py311hca03da5_0    defaults
conda-libmamba-solver     23.12.0            pyhd3eb1b0_1    defaults
conda-package-handling    2.2.0           py311hca03da5_0    defaults
conda-package-streaming   0.9.0           py311hca03da5_0    defaults
cryptography              41.0.7          py311hd4332d6_0    defaults
distro                    1.8.0           py311hca03da5_0    defaults
fmt                       9.1.0                h48ca7d4_0    defaults
icu                       73.1                 h313beb8_0    defaults
idna                      3.4             py311hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               hf3e1bf2_1    defaults
libarchive                3.6.2                h62fee54_2    defaults
libcurl                   8.4.0                h3e2b118_1    defaults
libcxx                    14.0.6               h848a8c0_0    defaults
libedit                   3.1.20230828         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.16                 h1a28f6b_2    defaults
libmamba                  1.5.3                h15e39b3_0    defaults
libmambapy                1.5.3           py311h1c5506f_0    defaults
libnghttp2                1.57.0               h62f6fdd_0    defaults
libsolv                   0.7.24               h514c7bf_0    defaults
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.10.4               h0dcf63f_1    defaults
lz4-c                     1.9.4                h313beb8_0    defaults
menuinst                  2.0.1           py311hca03da5_1    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.0.12               h1a28f6b_0    defaults
packaging                 23.1            py311hca03da5_0    defaults
pcre2                     10.42                hb066dcc_0    defaults
pip                       23.3.1          py311hca03da5_0    defaults
platformdirs              3.10.0          py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.5               hb885b13_0    defaults
python.app                3               py311h80987f9_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.31.0          py311hca03da5_0    defaults
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
setuptools                68.2.2          py311hca03da5_0    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
tqdm                      4.65.0          py311hb6e6a13_0    defaults
truststore                0.8.0           py311hca03da5_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311hca03da5_0    defaults
wheel                     0.41.2          py311hca03da5_0    defaults
xz                        5.4.5                h80987f9_0    defaults
yaml-cpp                  0.8.0                h313beb8_0    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

**Comment by travishathaway** [comment]
Hi @ytooyama,

It looks like there may be an invalid character in your `/Users/tooyama/.condarc`. Could you try temporary removing that file and re-run `conda init` to see what happens?

**Comment by ytooyama** [comment]
Hi @travishathaway 

I looked at the file and it doesn't seem to contain any suspicious characters.

```
tooyama@m1macmini(02/01/24 14:16:22) ~
% cat /Users/tooyama/.condarc
channels:
  - defaults
auto_activate_base: false

tooyama@m1macmini(02/01/24 14:16:27) ~
% ~/miniconda3/bin/conda init zsh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/main_init.py", line 155, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 137, in initialize
        run_plan(plan2)
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 797, in run_plan
        result = globals()[step["function"]](
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 1453, in init_sh_user
        rc_content = fh.read()
                     ^^^^^^^^^
      File "<frozen codecs>", line 322, in decode
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 445: invalid start byte

`$ /Users/tooyama/miniconda3/bin/conda init zsh`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/tooyama/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/Users/tooyama/miniconda3/bin/python
               CONDA_ROOT=/Users/tooyama/miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/tooyama/miniconda3/condabin:/Applications/UTM.app/Contents/MacO
                          S:/opt/homebrew/opt/libpq/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/op
                          t/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App
                          /usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:
                          /opt/podman/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cry
                          ptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security
                          .cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.c
                          ryptexd/codex.system/bootstrap/usr/appleinternal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/tooyama/.condarc
 populated config files : /Users/tooyama/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=13.6.4=0
                          __unix=0=0
       base environment : /Users/tooyama/miniconda3  (writable)
      conda av data dir : /Users/tooyama/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tooyama/miniconda3/pkgs
                          /Users/tooyama/.conda/pkgs
       envs directories : /Users/tooyama/miniconda3/envs
                          /Users/tooyama/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Darwin/22.6.0 OSX/13.6.4 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 503:20
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: 
```

**Comment by travishathaway** [comment]
The character might be invisible. Could you please temporarily rename `/Users/tooyama/.condarc` to `/Users/tooyama/.condarc_backup` and then run `conda init zsh`? This way we could be absolutely sure that this is or is not the problem.

**Comment by ytooyama** [comment]
Did not work.

```shell
% mv /Users/tooyama/.condarc /Users/tooyama/.condarc_backup
% conda config --set report_errors true
% ~/miniconda3/bin/conda init zsh      

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/cli/main_init.py", line 155, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 137, in initialize
        run_plan(plan2)
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 797, in run_plan
        result = globals()[step["function"]](
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tooyama/miniconda3/lib/python3.11/site-packages/conda/core/initialize.py", line 1453, in init_sh_user
        rc_content = fh.read()
                     ^^^^^^^^^
      File "<frozen codecs>", line 322, in decode
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 445: invalid start byte

`$ /Users/tooyama/miniconda3/bin/conda init zsh`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/tooyama/miniconda3/bin/conda
         CONDA_PYTHON_EXE=/Users/tooyama/miniconda3/bin/python
               CONDA_ROOT=/Users/tooyama/miniconda3
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/share/man::
                     PATH=/Users/tooyama/miniconda3/condabin:/Applications/UTM.app/Contents/MacO
                          S:/opt/homebrew/opt/libpq/bin:/opt/homebrew/sbin:/opt/homebrew/bin:/op
                          t/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App
                          /usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/opt/X11/bin:
                          /opt/podman/bin:/Library/Apple/usr/bin:/var/run/com.apple.security.cry
                          ptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security
                          .cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.c
                          ryptexd/codex.system/bootstrap/usr/appleinternal/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/tooyama/.condarc
 populated config files : /Users/tooyama/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=13.6.4=0
                          __unix=0=0
       base environment : /Users/tooyama/miniconda3  (writable)
      conda av data dir : /Users/tooyama/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/tooyama/miniconda3/pkgs
                          /Users/tooyama/.conda/pkgs
       envs directories : /Users/tooyama/miniconda3/envs
                          /Users/tooyama/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Darwin/22.6.0 OSX/13.6.4 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 503:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload successful.
```

**Comment by travishathaway** [comment]
Thanks for the output.

I am going to file this in our backlog where it will be in a queue to get worked on. We can't promise when it will be completed but welcome community contributions.

**Comment by ytooyama** [comment]
I forgot to report something important.
The version of zsh is here.

```
% zsh --version
zsh 5.9 (x86_64-apple-darwin22.0)
```

**Comment by supriya2691** [comment]
Hi, I am facing a similar issue. Can someone please look into it and let me know what should I do to resolve this?

##[debug]Evaluating condition for step: 'Install dependencies'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Install dependencies
##[debug]Loading inputs
##[debug]Loading env
Run conda env update --file environment.yml --name base
  conda env update --file environment.yml --name base
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.10.15/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.10.15/x64/lib
##[debug]/usr/bin/bash -e /home/runner/work/_temp/343194be-ed[2](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:2)8-41a4-8c2b-6ca3b2491f6e.sh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/share/miniconda/lib/python[3](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:3).12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main.py", line 8[4](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:4), in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/notices/core.py", line 132, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/cli/main_env_update.py", line 88, in execute
        spec = install_specs.detect(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/specs/__init__.py", line 71, in detect
        if spec.can_handle():
           ^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/specs/yaml_file.py", line 19, in can_handle
        self._environment = env.from_file(self.filename)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 173, in from_file
        return from_yaml(yamlstr, filename=filename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/env/env.py", line 139, in from_yaml
        data = yaml_safe_load(yamlstr)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/conda/common/serialize.py", line 46, in yaml_safe_load
        return _yaml_safe().load(string)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/main.py", line 434, in load
        return constructor.get_single_data()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/constructor.py", line 119, in get_single_data
        node = self.composer.get_single_node()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 76, in get_single_node
        document = self.compose_document()
                   ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 99, in compose_document
        node = self.compose_node(None, None)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 143, in compose_node
        node = self.compose_mapping_node(anchor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/composer.py", line 216, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/parser.py", line 146, in check_event
        self.current_event = self.state()
                             ^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/parser.py", line [5](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:5)98, in parse_block_mapping_key
        if self.scanner.check_token(KeyToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 174, in check_token
        while self.need_more_tokens():
              ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 211, in need_more_tokens
        self.stale_possible_simple_keys()
      File "/usr/share/miniconda/lib/python3.12/site-packages/ruamel/yaml/scanner.py", line 3[6](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:6)0, in stale_possible_simple_keys
        raise ScannerError(
    ruamel.yaml.scanner.ScannerError: while scanning a simple key
      in "<unicode string>", line 2[7](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:7), column 1:
        https://repo.anaconda.com/pkgs/m ... 
        ^ (line: 27)
    could not find expected ':'
      in "<unicode string>", line 2[8](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:8), column 1:
        https://repo.anaconda.com/pkgs/r ... 
        ^ (line: 28)

`$ /usr/share/miniconda/bin/conda env update --file environment.yml --name base`

  environment variables:
                 CIO_TEST=<not set>
                    CONDA=/usr/share/miniconda
               CONDA_ROOT=/usr/share/miniconda
           CURL_CA_BUNDLE=<not set>
      DEPLOYMENT_BASEPATH=/opt/runner
        GITHUB_EVENT_PATH=/home/runner/work/_temp/_github_workflow/event.json
              GITHUB_PATH=/home/runner/work/_temp/_runner_file_commands/add_path_0785b43c-5cf8-
                          4771-[9](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:9)22c-0e2e686082f2
          LD_LIBRARY_PATH=/opt/hostedtoolcache/Python/3.[10](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:10).15/x64/lib
               LD_PRELOAD=<not set>
                     PATH=/usr/share/miniconda/bin:/opt/hostedtoolcache/Python/3.10.15/x64/bin:/
                          opt/hostedtoolcache/Python/3.10.15/x64:/snap/bin:/home/runner/.local/b
                          in:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer
                          /vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/loca
                          l/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/lo
                          cal/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
        SELENIUM_JAR_PATH=/usr/share/java/selenium-server.jar
            SSL_CERT_FILE=<not set>
               SWIFT_PATH=/usr/share/swift/usr/bin
           pythonLocation=/opt/hostedtoolcache/Python/3.10.15/x64

     active environment : None
       user config file : /home/runner/.condarc
 populated config files : 
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.[12](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:12).4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen2
                          __conda=24.7.1=0
                          __glibc=2.35=0
                          __linux=6.8.0=0
                          __unix=0=0
       base environment : /usr/share/miniconda  (writable)
      conda av data dir : /usr/share/miniconda/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/share/miniconda/pkgs
                          /home/runner/.conda/pkgs
       envs directories : /usr/share/miniconda/envs
                          /home/runner/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/6.8.0-10[14](https://github.com/supriya2691/finance_charts_analysis/actions/runs/10913307942/job/30391701863#step:5:14)-azure ubuntu/22.04.5 glibc/2.35 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
                UID:GID : 1001:127
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

**Comment by yashaswi-nayak** [comment]
I recently got a MacBook, faced the same issue ( Homebrew + Miniconda + Zsh )
Here is how I was able to solve it.
You will get this error first
![Image](https://github.com/user-attachments/assets/292de04d-50da-42ce-b51d-e87acd3c6210)

The error happens due to no initialization of profile in zsh
Run 

    conda init

Find the path where the `conda.sh` is saved. Here in my system the path was 
`/opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh`

Source that file, run

    source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh

Now you can activate whichever environment you have in your Mac.

![Image](https://github.com/user-attachments/assets/f587cbb3-2d25-4a84-a24a-da8c1407fc8a)

You have to do this for every shell session, so you can add that line `source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh` to your `.zshrc` file at the end

    echo "source /opt/homebrew/Caskroom/miniconda/base/etc/profile.d/conda.sh" >> ~/.zshrc

Hope this helps you and solve you issue 😅
