### ISSUE TITLE
Cannot create environment 

### ISSUE THREAD

**Issue by sakuragi0109** [conda/conda#13527]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I'm trying to create a new environment using `conda create --name`, but it didn't work and keep saying "An unexpected error has occurred." Under is the error report 

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/cli/main_create.py", line 125, in execute
        return install(args, parser, "create")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/cli/install.py", line 360, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 138, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda_libmamba_solver/solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 131, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 317, in _load_channels
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 317, in <dictcomp>
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 239, in _fetch_channel
        json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 720, in fetch_latest_path
        _, state = self.fetch_latest()
                   ^^^^^^^^^^^^^^^^^^^
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 862, in fetch_latest
        cache.save(raw_repodata)
      File "/home/dinhn/rp24/Thanh/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 586, in save
        temp.write(data)
    OSError: [Errno 122] Disk quota exceeded

`$ /home/dinhn/rp24/Thanh/miniconda3/bin/conda create --name mmseqs2`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/dinhn/rp24/Thanh/miniconda3/bin/conda
             CONDA_PREFIX=/home/dinhn/rp24/Thanh/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/dinhn/rp24/Thanh/miniconda3/bin/python
               CONDA_ROOT=/home/dinhn/rp24/Thanh/miniconda3
              CONDA_SHLVL=1
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/opt/munge-0.5.15/lib:/opt/slurm-23.11.1/lib:/opt/slurm-
                          23.11.1/lib/slurm:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/slurm-23.11.1/share/man:
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/local/Modules/mod
                          ulefiles
                     PATH=/home/dinhn/rp24/Thanh/miniconda3/bin:/home/dinhn/rp24/Thanh/miniconda
                          3/condabin:/opt/munge-0.5.15/bin:/opt/slurm-23.11.1/bin:/opt/slurm-
                          23.11.1/sbin:/opt/nhc-1.4.2/sbin:/usr/lib64/qt-
                          3.3/bin:/bin:/usr/bin:/usr/local/bin:/usr/sbin:/opt/ibutils/bin:/home/
                          dinhn/bin:/home/dinhn/rp24_scratch/Thanh/trimAl/source
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /home/dinhn/rp24/Thanh/miniconda3
            shell level : 1
       user config file : /home/dinhn/.condarc
 populated config files : /home/dinhn/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=23.11.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /home/dinhn/rp24/Thanh/miniconda3  (writable)
      conda av data dir : /home/dinhn/rp24/Thanh/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dinhn/rp24_scratch/Thanh/miniconda/conda/pkgs
                          /scratch/rp24/dinhn/miniconda/conda/pkgs
       envs directories : /home/dinhn/rp24_scratch/Thanh/miniconda/conda/envs
                          /scratch/rp24/dinhn/miniconda/conda/envs
                          /home/dinhn/rp24/Thanh/miniconda3/envs
                          /home/dinhn/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/3.10.0-1160.71.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 14764:10025
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

### Conda Info

```shell
active environment : base
    active env location : /home/dinhn/rp24/Thanh/miniconda3
            shell level : 1
       user config file : /home/dinhn/.condarc
 populated config files : /home/dinhn/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake_avx512
                          __conda=23.11.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /home/dinhn/rp24/Thanh/miniconda3  (writable)
      conda av data dir : /home/dinhn/rp24/Thanh/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/dinhn/rp24_scratch/Thanh/miniconda/conda/pkgs
                          /scratch/rp24/dinhn/miniconda/conda/pkgs
       envs directories : /home/dinhn/rp24_scratch/Thanh/miniconda/conda/envs
                          /scratch/rp24/dinhn/miniconda/conda/envs
                          /home/dinhn/rp24/Thanh/miniconda3/envs
                          /home/dinhn/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/3.10.0-1160.71.1.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 14764:10025
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/dinhn/.condarc <==
envs_dirs:
  - /home/dinhn/rp24_scratch/Thanh/miniconda//conda/envs
  - /scratch/rp24/dinhn/miniconda/conda/envs
pkgs_dirs:
  - /home/dinhn/rp24_scratch/Thanh/miniconda//conda/pkgs
  - /scratch/rp24/dinhn/miniconda/conda/pkgs
ssl_verify: False
channel_priority: strict
channels:
  - conda-forge
  - defaults
solver: libmamba
```

### Conda list

```shell
# packages in environment at /home/dinhn/rp24/Thanh/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
archspec                  0.2.1              pyhd3eb1b0_0    defaults
boltons                   23.0.0          py311h06a4308_0    defaults
brotli-python             1.0.9           py311h6a678d5_7    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2023.12.12           h06a4308_0    defaults
certifi                   2023.11.17      py311h06a4308_0    defaults
cffi                      1.16.0          py311h5eee18b_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.11.0         py311h06a4308_0    defaults
conda-content-trust       0.2.0           py311h06a4308_0    defaults
conda-libmamba-solver     23.12.0            pyhd3eb1b0_1    defaults
conda-package-handling    2.2.0           py311h06a4308_0    defaults
conda-package-streaming   0.9.0           py311h06a4308_0    defaults
cryptography              41.0.7          py311hdda0065_0    defaults
distro                    1.8.0           py311h06a4308_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4             py311h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcurl                   8.4.0                h251f7ec_1    defaults
libedit                   3.1.20230828         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.5.3                haf1ee3a_0    defaults
libmambapy                1.5.3           py311h2dafd23_0    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libsolv                   0.7.24               he621ea3_0    defaults
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuuid                   1.41.5               h5eee18b_0    defaults
libxml2                   2.10.4               hf1b16e4_1    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
menuinst                  2.0.1           py311h06a4308_1    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   3.0.12               h7f8727e_0    defaults
packaging                 23.1            py311h06a4308_0    defaults
pcre2                     10.42                hebb0a14_0    defaults
pip                       23.3.1          py311h06a4308_0    defaults
platformdirs              3.10.0          py311h06a4308_0    defaults
pluggy                    1.0.0           py311h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311h06a4308_0    defaults
pysocks                   1.7.1           py311h06a4308_0    defaults
python                    3.11.5               h955ad1f_0    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0          py311h06a4308_0    defaults
ruamel.yaml               0.17.21         py311h5eee18b_0    defaults
setuptools                68.2.2          py311h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
tqdm                      4.65.0          py311h92b7b1e_0    defaults
truststore                0.8.0           py311h06a4308_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311h06a4308_0    defaults
wheel                     0.41.2          py311h06a4308_0    defaults
xz                        5.4.5                h5eee18b_0    defaults
yaml-cpp                  0.8.0                h6a678d5_0    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0          py311h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

### Additional Context

I even remove the whole miniconda and re-installed it but it still didn't work and keep having this error. Can someone help me?

**Comment by travishathaway** [comment]
Hi @sakuragi0109,

It looks like you may be running in to disk usage issues. Could you please verify that you have enough disk space left to install conda? Sometimes the environments can be quite large depending on the packages you want to install.
