### ISSUE TITLE
Pip editable install results in SAT error

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#13529]
### What happened?

Conda is supposed to detect attempts to unlink editable installs since they're unmanageable. Instead conda errors with an unregistered SAT variable error. To replicate:

```bash
$ export CONDA_PIP_INTEROP_ENABLED=true
$ export CONDA_SOLVER=classic

$ conda create -n scratch python pip git --yes
$ conda run -n scratch python -m pip install -e git+https://github.com/urllib3/urllib3.git@1.19.1#egg=urllib3
$ conda install -n scratch requests
...
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/logic.py", line 125, in _convert
        raise ValueError(f"Unregistered SAT variable name: {name}")
    ValueError: Unregistered SAT variable name: defaults/osx-64::urllib3-1.24.3-py36_0
```

<details>
<summary>Full Traceback</summary>

```
Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/logic.py", line 123, in _convert
        return self.names[name]
               ~~~~~~~~~~^^^^^^
    KeyError: 'defaults/osx-64::urllib3-1.24.3-py36_0'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/main_install.py", line 140, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/install.py", line 360, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/core/solve.py", line 138, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/core/solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/core/solve.py", line 366, in solve_final_state
        ssc = self._add_specs(ssc)
              ^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/core/solve.py", line 735, in _add_specs
        ssc.r.get_conflicting_specs(installed_specs, self.specs_to_add) or tuple()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/resolve.py", line 1266, in get_conflicting_specs
        C = r2.gen_clauses()
            ^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/io.py", line 85, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/resolve.py", line 1050, in gen_clauses
        nkey = C.Not(self.to_sat_name(prec))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/logic.py", line 142, in Not
        return self._eval(self._clauses.Not, (x,), (), polarity, name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/logic.py", line 128, in _eval
        args = self._convert(args)
               ^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/logic.py", line 118, in _convert
        return type(x)(map(self._convert, x))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/logic.py", line 125, in _convert
        raise ValueError(f"Unregistered SAT variable name: {name}")
    ValueError: Unregistered SAT variable name: defaults/osx-64::urllib3-1.24.3-py36_0
```

</details>

This was discovered while working to modernize the `tests/test_create.py::test_conda_pip_interop_conda_editable_package` test (xref https://github.com/conda/conda/issues/13292).

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
active environment : None
            shell level : 0
       user config file : /Users/kodegard/.condarc
 populated config files : /Users/kodegard/.condarc
          conda version : 23.11.0
    conda-build version : 3.28.2
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=23.11.0=0
                          __osx=14.3=0
                          __unix=0=0
       base environment : /Users/kodegard/.conda/arm64/23.11.0/3.11  (writable)
      conda av data dir : /Users/kodegard/.conda/arm64/23.11.0/3.11/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/kodegard/.conda/arm64/23.11.0/3.11/pkgs
                          /Users/kodegard/.conda/pkgs
       envs directories : /Users/kodegard/.conda/arm64/23.11.0/3.11/envs
                          /Users/kodegard/.conda/envs
               platform : osx-arm64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Darwin/23.3.0 OSX/14.3 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /Users/kodegard/.condarc <==
auto_update_conda: False
auto_activate_base: False
auto_stack: 5
changeps1: False
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/kodegard/.conda/arm64/23.11.0/3.11:
#
# Name                    Version                   Build  Channel
archspec                  0.2.1              pyhd3eb1b0_0    defaults
attrs                     23.1.0          py311hca03da5_0    defaults
beautifulsoup4            4.12.2          py311hca03da5_0    defaults
boltons                   23.0.0          py311hca03da5_0    defaults
brotli-python             1.0.9           py311h313beb8_7    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.1               h80987f9_0    defaults
ca-certificates           2023.12.12           hca03da5_0    defaults
cctools                   949.0.1             hc179dcd_25    defaults
cctools_osx-arm64         949.0.1             h332cad3_25    defaults
certifi                   2023.11.17      py311hca03da5_0    defaults
cffi                      1.16.0          py311h80987f9_0    defaults
chardet                   4.0.0           py311hca03da5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.7           py311hca03da5_0    defaults
conda                     23.11.0         py311hca03da5_0    defaults
conda-build               3.28.2          py311hca03da5_0    defaults
conda-content-trust       0.2.0           py311hca03da5_0    defaults
conda-index               0.3.0           py311hca03da5_0    defaults
conda-libmamba-solver     23.12.0         py311hca03da5_0    defaults
conda-package-handling    2.2.0           py311hca03da5_0    defaults
conda-package-streaming   0.9.0           py311hca03da5_0    defaults
cryptography              41.0.7          py311hd4332d6_0    defaults
distro                    1.8.0           py311hca03da5_0    defaults
filelock                  3.13.1          py311hca03da5_0    defaults
fmt                       9.1.0                h48ca7d4_0    defaults
icu                       73.1                 h313beb8_0    defaults
idna                      3.4             py311hca03da5_0    defaults
jinja2                    3.1.2           py311hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.19.2          py311hca03da5_0    defaults
jsonschema-specifications 2023.7.1        py311hca03da5_0    defaults
krb5                      1.20.1               hf3e1bf2_1    defaults
ld64                      530                 hb29bf3f_25    defaults
ld64_osx-arm64            530                 h001ce53_25    defaults
ldid                      2.1.5                h20b2a84_3    defaults
libarchive                3.6.2                h62fee54_2    defaults
libcurl                   8.4.0                h3e2b118_1    defaults
libcxx                    14.0.6               h848a8c0_0    defaults
libedit                   3.1.20221030         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.16                 h1a28f6b_2    defaults
liblief                   0.12.3               h313beb8_0    defaults
libllvm14                 14.0.6               h7ec7a93_3    defaults
libmamba                  1.5.3                h15e39b3_0    defaults
libmambapy                1.5.3           py311h1c5506f_0    defaults
libnghttp2                1.57.0               h62f6fdd_0    defaults
libsolv                   0.7.24               h514c7bf_0    defaults
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.10.4               h0dcf63f_1    defaults
lz4-c                     1.9.4                h313beb8_0    defaults
markupsafe                2.1.1           py311h80987f9_0    defaults
menuinst                  2.0.1           py311hca03da5_1    defaults
more-itertools            10.1.0          py311hca03da5_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.0.12               h1a28f6b_0    defaults
packaging                 23.1            py311hca03da5_0    defaults
patch                     2.7.6             h1a28f6b_1001    defaults
pcre2                     10.42                hb066dcc_0    defaults
pip                       23.3.1          py311hca03da5_0    defaults
pkginfo                   1.9.6           py311hca03da5_0    defaults
platformdirs              3.10.0          py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
psutil                    5.9.0           py311h80987f9_0    defaults
py-lief                   0.12.3          py311h313beb8_0    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.5               hb885b13_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python.app                3               py311h80987f9_0    defaults
pytz                      2023.3.post1    py311hca03da5_0    defaults
pyyaml                    6.0.1           py311h80987f9_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
referencing               0.30.2          py311hca03da5_0    defaults
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.31.0          py311hca03da5_0    defaults
rpds-py                   0.10.6          py311hf0e4da2_0    defaults
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
setuptools                68.2.2          py311hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.5             py311hca03da5_0    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tapi                      1100.0.11            h8754e6a_1    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
tqdm                      4.65.0          py311hb6e6a13_0    defaults
truststore                0.8.0           py311hca03da5_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311hca03da5_0    defaults
wheel                     0.41.2          py311hca03da5_0    defaults
xz                        5.4.5                h80987f9_0    defaults
yaml                      0.2.5                h1a28f6b_0    defaults
yaml-cpp                  0.8.0                h313beb8_0    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

</details>

**Comment by kenodegard** [comment]
libmamba raises a `RuntimeError` and correctly warns about an unmanageable package (albeit not very politely)

**Comment by jezdez** [comment]
`RuntimeError`s definitely also don't sounds super great. Should we add a new exception classes `UnmanagablePackage` or something that bubbles up a little more graceful?

**Comment by dholth** [comment]
I can look into this and whether it works differently with new-style editable installs.
