### ISSUE TITLE
UnicodeDecodeError during package linking

### ISSUE THREAD

**Issue by mmagnuski** [conda/conda#1352]
I got UnicodeDecodeError when I was updating with conda (happens around the time of package linking). The exception occurs in menuinst.
The operations have completed successfully however - the update package works well.

Just in case, the whole story:
```
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
menuinst Exception:Traceback (most recent call last):#                   |  62%
  File "D:\Python\Anaconda\lib\site-packages\conda\install.py", line 319, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "D:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 42, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "D:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 127, in create
    u'' + workdir,
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 13: ordinal not in range(128)
menuinst Exception:Traceback (most recent call last):#############       |  87%
  File "D:\Python\Anaconda\lib\site-packages\conda\install.py", line 319, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "D:\Python\Anaconda\lib\site-packages\menuinst\__init__.py", line 42, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "D:\Python\Anaconda\lib\site-packages\menuinst\win32.py", line 127, in create
    u'' + workdir,
UnicodeDecodeError: 'ascii' codec can't decode byte 0x9c in position 13: ordinal not in range(128)
[      COMPLETE      ]|##################################################| 100%
```

I am on Python 2.7, Windows 8.

**Comment by asmeurer** [comment]
Looks like a bug in menuinst for Python 2. Does your username have any non-ASCII characters?

**Comment by mmagnuski** [comment]
Yes, it does, forgot to mention it.
I did have issues with other packages due to this but never with conda/menuinst.

**Comment by asmeurer** [comment]
Your best bet to avoid these issues is to use Python 3.

**Comment by mmagnuski** [comment]
Oh, yes, I know. :)
For some tasks I am trapped in 32-bit Python 2.7 (psychopy).
But I should use conda environments more often :)
Thanks!
