### ISSUE TITLE
Cannot create environment in the later versions of miniconda on an NFS like filesystem. Can create with 23.5.0

### ISSUE THREAD

**Issue by rahulgpuri** [conda/conda#13534]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Cannot create an environment due to the implementation of fcntl.lockf(). A little research suggested that this function cannot be implemented on NFS/ Lustre filesystem.  Following is the report 

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 194, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/cli/main_update.py", line 97, in execute
        install(args, parser, "update")
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/cli/install.py", line 360, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 138, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 199, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 344, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/common/io.py", line 85, in decorated
        return f(*args, **kwds)
               ^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 564, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/solve.py", line 1279, in _prepare
        reduced_index = get_reduced_index(
                        ^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/index.py", line 264, in get_reduced_index
        new_records = SubdirData.query_all(
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 164, in query_all
        result = tuple(
                 ^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 149, in subdir_query
        return tuple(
               ^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 171, in query
        self.load()
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 271, in load
        _internal_state = self._load()
                          ^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/core/subdir_data.py", line 314, in _load
        repodata, state = fetcher.fetch_latest_parsed()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 708, in fetch_latest_parsed
        parsed, state = self.fetch_latest()
                        ^^^^^^^^^^^^^^^^^^^
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 760, in fetch_latest
        cache.load_state()
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 573, in load_state
        self.load(state_only=True)
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 520, in load
        with self.cache_path_state.open("r+") as state_file, lock(state_file):
      File "/data/docs/rahul.puri/miniconda3/lib/python3.11/site-packages/conda/gateways/disk/lock.py", line 59, in __enter__
        fcntl.lockf(
    OSError: [Errno 38] Function not implemented

### Conda Info

```shell
active environment : base
    active env location : /data/docs/rahul.puri/miniconda3
            shell level : 1
       user config file : /data/docs/rahul.puri/.condarc
 populated config files : /data/docs/rahul.puri/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.11.5.final.0
                 solver : classic
       virtual packages : __archspec=1=haswell
                          __conda=23.11.0=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /data/docs/rahul.puri/miniconda3  (writable)
      conda av data dir : /data/docs/rahul.puri/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/docs/rahul.puri/miniconda3/pkgs
                          /data/docs/rahul.puri/.conda/pkgs
       envs directories : /data/docs/rahul.puri/miniconda3/envs
                          /data/docs/rahul.puri/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.11.5 Linux/3.10.0-957.el7.x86_64 centos/7.6.1810 glibc/2.17
                UID:GID : 1317:1320
             netrc file : None
           offline mode : False
```

### Additional Context

So this new file called site-packages/conda/gateways/disk/lock.py is introduced in the later version and is not there in the older version of miniconda.

**Comment by jezdez** [comment]
@dholth Any chance this could be worked around with by catching the OSError and gracefully fail?

**Comment by zst1406217** [comment]
Same Issue. By downgrading to version 23.5.0 it works. But I wonder if there is a solution in future version

**Comment by travishathaway** [comment]
@zst1406217,

I think the best solution is to disable file locking by setting `no_lock=True`. You can do that by using the `--no-lock` flag or by disabling it in your settings via `conda config --set no_lock true`.

See this comment for reference:
- https://github.com/conda/conda/issues/13921#issuecomment-2110442189

**Comment by dholth** [comment]
Different filesystems fail more or less gracefully when locking is unavailable or not implemented.

https://github.com/conda/conda/blob/main/conda/gateways/disk/lock.py#L75 is where the check would go. The code could warn and return.

On the same system, the local filesystem will usually support locking and the remote filesystem may or may not support locking.

We might be able to test this with an nfs filesystem mounted with the nolock option, or with a mock.
