### ISSUE TITLE
cffi update issue

### ISSUE THREAD

**Issue by wikiped** [conda/conda#1355]
Trying to update `cffi` in default environment with:

    conda update cffi

Leads to errors:

	D:\Anaconda>conda update cffi
	Fetching package metadata: ......
	Solving package specifications: .
	Package plan for installation in environment D:\Anaconda:

	The following packages will be downloaded:

		package                    |            build
		---------------------------|-----------------
		cffi-1.1.0                 |           py27_0         164 KB

	The following packages will be UPDATED:

		cffi: 1.0.3-py27_0 --> 1.1.0-py27_0

	Proceed ([y]/n)?

	Fetching packages ...
	cffi-1.1.0-py2 100% |###############################| Time: 0:00:00 257.15 kB/s
	Extracting packages ...
	[      COMPLETE      ]|##################################################| 100%
	Error: Unable to remove files for package: cffi

	Please close all processes running code from cffi and try again.

If then I run `conda install -f cffi` it finishes without errors:

	D:\Anaconda>conda install -f cffi
	Fetching package metadata: ......
	Solving package specifications: .
	Package plan for installation in environment D:\Anaconda:

	The following packages will be UPDATED:

		cffi: 1.0.3-py27_0 --> 1.1.0-py27_0

	Proceed ([y]/n)?

	[      COMPLETE      ]|##################################################| 100%
	Extracting packages ...
	[      COMPLETE      ]|##################################################| 100%
	Unlinking packages ...
	[      COMPLETE      ]|##################################################| 100%
	Linking packages ...
	[      COMPLETE      ]|##################################################| 100%

BUT: right after that any attempt to run `conda update` results in `AssertionError` as if `cffi` package was not updated:

	Updating conda...
	Traceback (most recent call last):
	  File "D:\Anaconda\Scripts\conda-script.py", line 2, in <module>
		from conda.cli import main
	  File "D:\Anaconda\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
		from conda.cli.main import main
	  File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 48, in <module>
		from conda.cli import main_create
	  File "D:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 11, in <module>
		from conda.cli import common, install
	  File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 20, in <module>
		import conda.plan as plan
	  File "D:\Anaconda\lib\site-packages\conda\plan.py", line 24, in <module>
		from conda import instructions as inst
	  File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 7, in <module>
		from conda.fetch import fetch_pkg
	  File "D:\Anaconda\lib\site-packages\conda\fetch.py", line 24, in <module>
		from conda.connection import CondaSession, unparse_url, RETRIES
	  File "D:\Anaconda\lib\site-packages\conda\connection.py", line 23, in <module>
		import requests
	  File "D:\Anaconda\lib\site-packages\requests\__init__.py", line 53, in <module>
		from .packages.urllib3.contrib import pyopenssl
	  File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", lin
	e 53, in <module>
		import OpenSSL.SSL
	  File "D:\Anaconda\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
		from OpenSSL import rand, crypto, SSL
	  File "D:\Anaconda\lib\site-packages\OpenSSL\rand.py", line 11, in <module>
		from OpenSSL._util import (
	  File "D:\Anaconda\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
		from cryptography.hazmat.bindings.openssl.binding import Binding
	  File "D:\Anaconda\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", li
	ne 60, in <module>
		class Binding(object):
	  File "D:\Anaconda\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", li
	ne 109, in Binding
		libraries=_get_libraries(sys.platform)
	  File "D:\Anaconda\lib\site-packages\cryptography\hazmat\bindings\utils.py", line 97, in
	build_ffi_for_binding
		extra_link_args=extra_link_args,
	  File "D:\Anaconda\lib\site-packages\cryptography\hazmat\bindings\utils.py", line 105, in
	 build_ffi
		ffi = FFI()
	  File "D:\Anaconda\lib\site-packages\cffi\api.py", line 59, in __init__
		"version mismatch, %s != %s" % (backend.__version__, __version__)
	AssertionError: version mismatch, 1.0.3 != 1.1.0

**Comment by ilanschnell** [comment]
This problem should be fixed with #1133 which was release in version 3.13.0
