### ISSUE TITLE
Latest Python package is broken on Linux

### ISSUE THREAD

**Issue by stuarteberg** [conda/conda#1356]
First, I made sure conda is up-to-date:

```
$ conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /miniconda:
#
conda                     3.12.0                   py27_0  
```

Now, try to update the `python` package:

```
$ conda update python
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /miniconda:

The following packages will be UPDATED:

    pip:        6.1.1-py27_0 --> 7.0.1-py27_0
    python:     2.7.9-3      --> 2.7.10-0    
    setuptools: 16.0-py27_0  --> 17.0-py27_0 

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|#################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                           |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 203, in main
    args_func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 609, in inner
    return func(args, parser)
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/miniconda/lib/python2.7/site-packages/conda/plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 93, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 89, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/miniconda/lib/python2.7/site-packages/conda/install.py", line 550, in link
    _link(src, dst, lt)
  File "/miniconda/lib/python2.7/site-packages/conda/install.py", line 143, in _link
    shutil.copy2(src, dst)
  File "/miniconda/lib/python2.7/shutil.py", line 130, in copy2
  File "/miniconda/lib/python2.7/shutil.py", line 82, in copyfile
IOError: [Errno 2] No such file or directory: u'/miniconda/pkgs/python-2.7.10-0/lib/python2.7/config/Makefile'

```

I tried to use `conda info`, but the error above had totally borked my python install, rendering conda broken.

```
$ conda info
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
ImportError: No module named site
```

I was able to fix my root environment by copying `lib/python2.7` from another environment into my root environment.  Now I can use `conda info`:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.12.0
  conda-build version : 1.13.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /miniconda  (writable)
  default environment : /miniconda
     envs directories : /miniconda/envs
        package cache : /miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/ilastik/.condarc
    is foreign system : False

```

**Comment by asmeurer** [comment]
@ilanschnell

**Comment by stuarteberg** [comment]
I re-installed miniconda, and I can't reproduce this issue in my new miniconda install.  I don't know what I did to screw up my old root environment, but I guess it doesn't matter.

Sorry for the distraction.  Move along, nothing to see here :-)

**Comment by dmankins** [comment]
I kept having a similar problem.

"conda update python" 

in my conda environment was what fixed it for me.
