### ISSUE TITLE
`TypeError: expected str, bytes or os.PathLike object, not NoneType`

### ISSUE THREAD

**Issue by kenodegard** [conda/conda#13580]
### What happened?

Not entirely sure what happened here. Running the same command a second time worked without any issues.

This occurred without any envs activated:

```bash
$ conda create -n scratch -c conda-forge -c defaults -c anaconda-cloud --use-local aug
WARNING: A conda environment already exists at '/Users/kodegard/.conda/arm64/23.11.0/3.11/envs/scratch'
Remove existing environment (y/[n])? y

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/main_create.py", line 125, in execute
        return install(args, parser, "create")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/cli/install.py", line 175, in install
        elif not paths_equal(context.active_prefix, context.root_prefix):
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/kodegard/.conda/arm64/23.11.0/3.11/lib/python3.11/site-packages/conda/common/path.py", line 65, in paths_equal
        return abspath(path1) == abspath(path2)
               ^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 399, in abspath
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /Users/kodegard/.conda/arm64/23.11.0/3.11/bin/conda create -n scratch -c conda-forge -c defaults -c anaconda-cloud --use-local aug`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/kodegard/.conda/arm64/23.11.0/3.11/bin/conda
         CONDA_PYTHON_EXE=/Users/kodegard/.conda/arm64/23.11.0/3.11/bin/python
               CONDA_ROOT=/Users/kodegard/.conda/arm64/23.11.0/3.11
              CONDA_SHLVL=0
           CURL_CA_BUNDLE=<not set>
                 INFOPATH=/opt/homebrew/share/info:
               LD_PRELOAD=<not set>
                  MANPATH=/opt/homebrew/Cellar/lmod/8.7.19/share/man:/opt/homebrew/share/man::
               MODULEPATH=/Users/kodegard/Dropbox/dev/core/lmod:/opt/homebrew/Cellar/lmod/8.7.19
                          /modulefiles/Darwin:/opt/homebrew/Cellar/lmod/8.7.19/modulefiles/Core
                     PATH=/Users/kodegard/.conda/arm64/23.11.0/3.11/condabin:/Users/kodegard/.co
                          nda/current/envs/tools/cin:/usr/local/sbin:/opt/homebrew/bin:/opt/home
                          brew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/
                          usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/boots
                          trap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/b
                          ootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/boo
                          tstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/kodegard/.f
                          ig/bin:/Users/kodegard/.local/bin:/Users/kodegard/.orbstack/bin:/opt/h
                          omebrew/opt/fzf/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
__LMOD_REF_COUNT_MODULEPATH=/Users/kodegard/Dropbox/dev/core/lmod:1;/opt/homebrew/Cellar/lmod/8.7.
                          19/modulefiles/Darwin:1;/opt/homebrew/Cellar/lmod/8.7.19/modulefiles/C
                          ore:1

     active environment : None
            shell level : 0
       user config file : /Users/kodegard/.condarc
 populated config files : /Users/kodegard/.condarc
                          /Users/kodegard/.conda/arm64/23.11.0/3.11/envs/scratch/.condarc
          conda version : 24.1.0
    conda-build version : 24.1.0
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=24.1.0=0
                          __osx=14.3=0
                          __unix=0=0
       base environment : /Users/kodegard/.conda/arm64/23.11.0/3.11  (writable)
      conda av data dir : /Users/kodegard/.conda/arm64/23.11.0/3.11/etc/conda
  conda av metadata url : None
           channel URLs : file:///Users/kodegard/.conda/arm64/23.11.0/3.11/conda-bld/osx-64
                          file:///Users/kodegard/.conda/arm64/23.11.0/3.11/conda-bld/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/anaconda-cloud/osx-64
                          https://conda.anaconda.org/anaconda-cloud/noarch
          package cache : /Users/kodegard/.conda/arm64/23.11.0/3.11/pkgs
                          /Users/kodegard/.conda/pkgs
       envs directories : /Users/kodegard/.conda/arm64/23.11.0/3.11/envs
                          /Users/kodegard/.conda/envs
               platform : osx-64
             user-agent : conda/24.1.0 requests/2.31.0 CPython/3.11.5 Darwin/23.3.0 OSX/14.3 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers? [y/N]:
Timeout reached. No report sent.
```

### Conda Details

<details>
<summary><code>conda info</code></summary>

```shell
     active environment : None
            shell level : 0
       user config file : /Users/kodegard/.condarc
 populated config files : /Users/kodegard/.condarc
                          /Users/kodegard/.conda/arm64/23.11.0/3.11/envs/scratch/.condarc
          conda version : 24.1.0
    conda-build version : 24.1.0
         python version : 3.11.5.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=x86_64
                          __conda=24.1.0=0
                          __osx=14.3=0
                          __unix=0=0
       base environment : /Users/kodegard/.conda/arm64/23.11.0/3.11  (writable)
      conda av data dir : /Users/kodegard/.conda/arm64/23.11.0/3.11/etc/conda
  conda av metadata url : None
           channel URLs : file:///Users/kodegard/.conda/arm64/23.11.0/3.11/conda-bld/osx-64
                          file:///Users/kodegard/.conda/arm64/23.11.0/3.11/conda-bld/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/anaconda-cloud/osx-64
                          https://conda.anaconda.org/anaconda-cloud/noarch
          package cache : /Users/kodegard/.conda/arm64/23.11.0/3.11/pkgs
                          /Users/kodegard/.conda/pkgs
       envs directories : /Users/kodegard/.conda/arm64/23.11.0/3.11/envs
                          /Users/kodegard/.conda/envs
               platform : osx-64
             user-agent : conda/24.1.0 requests/2.31.0 CPython/3.11.5 Darwin/23.3.0 OSX/14.3 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

</details>

<details>
<summary><code>conda config</code></summary>

```shell
==> /Users/kodegard/.condarc <==
auto_update_conda: False
auto_activate_base: False
changeps1: False
conda_build:
  pkg_format: 2
```

</details>

<details>
<summary><code>conda list</code></summary>

```shell
# packages in environment at /Users/kodegard/.conda/arm64/23.11.0/3.11:
#
# Name                    Version                   Build  Channel
archspec                  0.2.1              pyhd3eb1b0_0    defaults
attrs                     23.1.0          py311hca03da5_0    defaults
beautifulsoup4            4.12.2          py311hca03da5_0    defaults
boltons                   23.0.0          py311hca03da5_0    defaults
brotli-python             1.0.9           py311h313beb8_7    defaults
bzip2                     1.0.8                h620ffc9_4    defaults
c-ares                    1.19.1               h80987f9_0    defaults
ca-certificates           2023.12.12           hca03da5_0    defaults
cctools                   949.0.1             hc179dcd_25    defaults
cctools_osx-arm64         949.0.1             h332cad3_25    defaults
certifi                   2023.11.17      py311hca03da5_0    defaults
cffi                      1.16.0          py311h80987f9_0    defaults
chardet                   4.0.0           py311hca03da5_1003    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
click                     8.1.7           py311hca03da5_0    defaults
conda                     24.1.0          py311hca03da5_0    defaults
conda-build               24.1.0          py311hca03da5_0    defaults
conda-content-trust       0.2.0           py311hca03da5_0    defaults
conda-index               0.4.0              pyhd3eb1b0_0    defaults
conda-libmamba-solver     23.12.0         py311hca03da5_0    defaults
conda-package-handling    2.2.0           py311hca03da5_0    defaults
conda-package-streaming   0.9.0           py311hca03da5_0    defaults
cryptography              41.0.7          py311hd4332d6_0    defaults
distro                    1.8.0           py311hca03da5_0    defaults
filelock                  3.13.1          py311hca03da5_0    defaults
fmt                       9.1.0                h48ca7d4_0    defaults
icu                       73.1                 h313beb8_0    defaults
idna                      3.4             py311hca03da5_0    defaults
jinja2                    3.1.3           py311hca03da5_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
jsonschema                4.19.2          py311hca03da5_0    defaults
jsonschema-specifications 2023.7.1        py311hca03da5_0    defaults
krb5                      1.20.1               hf3e1bf2_1    defaults
ld64                      530                 hb29bf3f_25    defaults
ld64_osx-arm64            530                 h001ce53_25    defaults
ldid                      2.1.5                h20b2a84_3    defaults
libarchive                3.6.2                h62fee54_2    defaults
libcurl                   8.4.0                h3e2b118_1    defaults
libcxx                    14.0.6               h848a8c0_0    defaults
libedit                   3.1.20221030         h80987f9_0    defaults
libev                     4.33                 h1a28f6b_1    defaults
libffi                    3.4.4                hca03da5_0    defaults
libiconv                  1.16                 h1a28f6b_2    defaults
liblief                   0.12.3               h313beb8_0    defaults
libllvm14                 14.0.6               h7ec7a93_3    defaults
libmamba                  1.5.3                h15e39b3_0    defaults
libmambapy                1.5.3           py311h1c5506f_0    defaults
libnghttp2                1.57.0               h62f6fdd_0    defaults
libsolv                   0.7.24               h514c7bf_0    defaults
libssh2                   1.10.0               h02f6b3c_2    defaults
libxml2                   2.10.4               h0dcf63f_1    defaults
lz4-c                     1.9.4                h313beb8_0    defaults
markupsafe                2.1.3           py311h80987f9_0    defaults
menuinst                  2.0.1           py311hca03da5_1    defaults
more-itertools            10.1.0          py311hca03da5_0    defaults
ncurses                   6.4                  h313beb8_0    defaults
openssl                   3.0.13               h1a28f6b_0    defaults
packaging                 23.1            py311hca03da5_0    defaults
patch                     2.7.6             h1a28f6b_1001    defaults
pcre2                     10.42                hb066dcc_0    defaults
pip                       23.3.1          py311hca03da5_0    defaults
pkginfo                   1.9.6           py311hca03da5_0    defaults
platformdirs              3.10.0          py311hca03da5_0    defaults
pluggy                    1.0.0           py311hca03da5_1    defaults
psutil                    5.9.0           py311h80987f9_0    defaults
py-lief                   0.12.3          py311h313beb8_0    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6           py311h80987f9_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.2.0          py311hca03da5_0    defaults
pysocks                   1.7.1           py311hca03da5_0    defaults
python                    3.11.5               hb885b13_0    defaults
python-libarchive-c       2.9                pyhd3eb1b0_1    defaults
python.app                3               py311h80987f9_0    defaults
pytz                      2023.3.post1    py311hca03da5_0    defaults
pyyaml                    6.0.1           py311h80987f9_0    defaults
readline                  8.2                  h1a28f6b_0    defaults
referencing               0.30.2          py311hca03da5_0    defaults
reproc                    14.2.4               hc377ac9_1    defaults
reproc-cpp                14.2.4               hc377ac9_1    defaults
requests                  2.31.0          py311hca03da5_0    defaults
rpds-py                   0.10.6          py311hf0e4da2_0    defaults
ruamel.yaml               0.17.21         py311h80987f9_0    defaults
setuptools                68.2.2          py311hca03da5_0    defaults
six                       1.16.0             pyhd3eb1b0_1    defaults
soupsieve                 2.5             py311hca03da5_0    defaults
sqlite                    3.41.2               h80987f9_0    defaults
tapi                      1100.0.11            h8754e6a_1    defaults
tk                        8.6.12               hb8d0fd4_0    defaults
tqdm                      4.65.0          py311hb6e6a13_0    defaults
truststore                0.8.0           py311hca03da5_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.18         py311hca03da5_0    defaults
wheel                     0.41.2          py311hca03da5_0    defaults
xz                        5.4.5                h80987f9_0    defaults
yaml                      0.2.5                h1a28f6b_0    defaults
yaml-cpp                  0.8.0                h313beb8_0    defaults
zlib                      1.2.13               h5a0b063_0    defaults
zstandard                 0.19.0          py311h80987f9_0    defaults
zstd                      1.5.5                hd90d995_0    defaults
```

</details>

**Comment by mattkram** [comment]
I have no idea if this is related, but I remember seeing this same error message in a bug in `anaconda-client`, fixed here: https://github.com/Anaconda-Platform/anaconda-client/pull/667

That PR fixed this issue: https://github.com/Anaconda-Platform/anaconda-client/issues/643

**Comment by ndrezn** [comment]
Having the same error as well as of yesterday. Nothing changed in my environment to my knowledge...
