### ISSUE TITLE
env.py throws error on conda env create

### ISSUE THREAD

**Issue by amenity** [conda/conda#1359]
Running 

    conda env create -f sphinx-docs.yml -n docsEnv

throws the following error:
```
0109-amentiya:docs aapplewhite$ conda env create -f sphinx-docs.yml -n docs_site
Traceback (most recent call last):
  File "/Users/aapplewhite/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/aapplewhite/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 63, in main
    return args_func(args, parser)
  File "/Users/aapplewhite/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/Users/aapplewhite/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 60, in execute
    env = from_file(args.file)
  File "/Users/aapplewhite/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 54, in from_file
    return Environment(filename=filename, **data)
TypeError: type object argument after ** must be a mapping, not str
```

```
Current conda install:

             platform : osx-64
        conda version : 3.12.0
  conda-build version : 1.8.2
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /Users/aapplewhite/anaconda  (writable)
  default environment : /Users/aapplewhite/anaconda
     envs directories : /Users/aapplewhite/anaconda/envs
        package cache : /Users/aapplewhite/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by asmeurer** [comment]
This looks like a bug with [conda-env](https://github.com/conda/conda-env). Also, what are the contents of your sphinx-docs.yml?

**Comment by amenity** [comment]
@asmeurer found that our sphinx-docs.yml file is not a proper conda-env environment file. 

He suggested

    conda list --export > sphinx-docs.txt

to export the package list and use

    conda create -n docsEnv --file sphinx-docs.txt

to install from it.  Verified that this works.
