### ISSUE TITLE
conda update conda error in osx yosemite

### ISSUE THREAD

**Issue by acycliq** [conda/conda#1363]
Hello team

i got the following traceback when i try `conda update conda`

```sh
Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 75, in execute
    prepend=not args.override_channels)
  File "//anaconda/lib/python2.7/site-packages/conda/api.py", line 33, in get_index
    return fetch_index(tuple(channel_urls))
  File "//anaconda/lib/python2.7/site-packages/conda/utils.py", line 61, in __call__
    value = self.func(*args)
  File "//anaconda/lib/python2.7/site-packages/conda/fetch.py", line 105, in fetch_index
    repodata = fetch_repodata(url)
  File "//anaconda/lib/python2.7/site-packages/conda/fetch.py", line 72, in fetch_repodata
    u = connectionhandled_urlopen(request)
  File "//anaconda/lib/python2.7/site-packages/conda/connection.py", line 83, in connectionhandled_urlopen
    return urllib2.urlopen(request)
  File "//anaconda/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "//anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "//anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: dsdale24/osx-64/repodata.json.bz2
```
Below is the `conda info` output

```sh
Current conda install:

             platform : osx-64
        conda version : 2.0.4
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : dsdale24/osx-64/
          config file : /Users/Dimitris/.condarc
```

**Comment by acycliq** [comment]
Ok, i spent almost a day but it seems I'm getting somewhere with this....

It appears i had a very messy setup. There was an earlier version of anaconda (1.8) in the root dir while the latest anaconda (2,2) was sitting under the home directory. Removing the old anaconda folder didn't completely solve the problem
 `bash_profile` keeps the paths from both installations but the older installation's path precedes the path of the version that was installed last (in my case 2.2).  I moved the path for 2.2 first but it should be safe to delete the old anaconda (1.8) path from `bash_profile`.

Also there was a `condarc` in my home directory which i believe was created by v1.8 and completely ruined an condo update command i was trying to run. It had only these two lines:
```sh
channels:
  - dsdale24
```
I deleted this `condarc` and now my conda works fine,

If someone reads this please let me know if it makes sense. I am completely new to this. The `condarc` file under my home dir is it needed at all? Is it a remainder of v1.8 and was it wise for me to remove it?

thanks a lot!

**Comment by asmeurer** [comment]
The condarc lets you add channels (among [other things](http://conda.pydata.org/docs/install/config.html)). If you don't need any packages from [dsdale24](https://anaconda.org/dsdale24) you don't need to have that file.

**Comment by acycliq** [comment]
ok, many thanks for looking into this| Much appreciated
