### ISSUE TITLE
Upgrade from python 2.7.9-1 to 2.7.10-0 breaks pip

### ISSUE THREAD

**Issue by Zangror** [conda/conda#1366]
Some days ago, I have created virtual environments. But when I update the python 2.7 to the latest version, pip becomes crazy.

For example:

``` bash
>> pip list
pip (6.1.1)
setuptools (16.0)
>> conda update python
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Users\HCA177\Progs\Continuum\Ana
conda\32\envs\smartdata32:

The following packages will be UPDATED:

    pip:        6.1.1-py27_0 --> 7.0.3-py27_0
    python:     2.7.9-1      --> 2.7.10-0
    setuptools: 16.0-py27_0  --> 17.0-py27_0

Proceed ([y]/n)?

Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
[      COMPLETE      ] |#################################################| 100%
>> pip list
Traceback (most recent call last):
  File "C:\Users\HCA177\Progs\Continuum\Anaconda\32\envs\smartdata32\Scripts\pip-script.py", line 3, in <module>
    from pip import main
  File "C:\Users\HCA177\Progs\Continuum\Anaconda\32\envs\smartdata32\lib\site-packages\pip\__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\HCA177\Progs\Continuum\Anaconda\32\envs\smartdata32\lib\site-packages\pip\vcs\subversion.py", line 9, in <module>
    from pip.index import Link
  File "C:\Users\HCA177\Progs\Continuum\Anaconda\32\envs\smartdata32\lib\site-packages\pip\index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "C:\Users\HCA177\Progs\Continuum\Anaconda\32\envs\smartdata32\lib\site-packages\pip\wheel.py", line 35, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "C:\Users\HCA177\Progs\Continuum\Anaconda\32\envs\smartdata32\lib\site-packages\pip\_vendor\__init__.py", line 92, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.distlib.scripts'
```

The pip/_vendor/distlib/scripts.py file exists.

If I build a new virtual environnement, everything is fine.

**Comment by asmeurer** [comment]
Does `conda install -f pip` fix it?

**Comment by Zangror** [comment]
Not at all...

**Comment by galeo** [comment]
I have met the same problem. After upgrading python-2.7.10 with **linuxbrew** on CentOS6, the **pip** is totally broken.

Here is the error log:
```python
$ pip --version
Traceback (most recent call last):
  File "/home/fishtai0/.linuxbrew/bin/pip", line 9, in <module>
    load_entry_point('pip==7.0.1', 'console_scripts', 'pip')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 552, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2672, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2345, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2351, in resolve
  File "/home/fishtai0/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/fishtai0/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/fishtai0/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/fishtai0/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/wheel.py", line 34, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/home/fishtai0/.linuxbrew/Cellar/python/2.7.10/lib/python2.7/site-packages/pip-7.0.1-py2.7.egg/pip/_vendor/__init__.py", line 92, in load_module
    raise ImportError("No module named '%s'" % (name,))
ImportError: No module named 'pip._vendor.distlib.scripts'
```


[Here](http://superuser.com/questions/918495/error-when-installing-pip-for-python2-7) is a discussion talking about the problem and it says the absence of **openssl** caused the trouble. However, I have already installed openssl. It did not solve the problem.

**Comment by galeo** [comment]
There is an [issue](https://github.com/Homebrew/linuxbrew/issues/420) opened in **linuxbrew**, and it seems the Python build scripts caused the problem.
