### ISSUE TITLE
conda install collects package metadata with old channel url which has been removed from condarc

### ISSUE THREAD

**Issue by shelfofclub** [conda/conda#13670]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I run `conda install xxx` with numpy, conda, and other packages in the `base` env.

Then an error always occurs:
```
conda install numpy
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64'

conda install numpy -v
INFO conda.conda_libmamba_solver.solver:_log_info(285): Using libmamba solver
INFO conda.conda_libmamba_solver.solver:_log_info(286): Conda version: 23.7.4
INFO conda.conda_libmamba_solver.solver:_log_info(287): Mamba version: 1.4.1
INFO conda.conda_libmamba_solver.solver:_log_info(288): Target prefix: '/home/myname/programs/miniconda3'
INFO conda.conda_libmamba_solver.solver:_log_info(289): Command: ['/home/myname/programs/miniconda3/bin/conda', 'install', 'numpy', '-v']
INFO conda.conda_libmamba_solver.solver:_log_info(290): Specs to add: IndexedSet([MatchSpec("numpy")])
INFO conda.conda_libmamba_solver.solver:_log_info(291): Specs to remove: frozenset()
Channels:
 - defaults
 - conda-forge
Platform: linux-64
Collecting package metadata (repodata.json): ...working... info     libmamba Reading cache files '/tmp/tmpw_lvvwxe.json.*' for repo index 'installed'
Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bc72a970>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')': /anaconda/pkgs/main/noarch/repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bc72a820>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')': /anaconda/pkgs/main/linux-64/repodata.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bd242400>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')': /anaconda/pkgs/main/noarch/repodata.json

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bd242f70>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')': /anaconda/pkgs/main/linux-64/repodata.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bd24cc70>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')': /anaconda/pkgs/main/noarch/repodata.json

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bd24ca00>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')': /anaconda/pkgs/main/linux-64/repodata.json

failed
Traceback (most recent call last):
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f29bd1bd580>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 487, in send
    resp = conn.urlopen(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 815, in urlopen
    return self.urlopen(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='mirrors6.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /anaconda/pkgs/main/linux-64/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bd1bd580>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 188, in conda_http_errors
    yield
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 149, in repodata
    response: Response = session.get(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 508, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='mirrors6.tuna.tsinghua.edu.cn', port=443): Max retries exceeded with url: /anaconda/pkgs/main/linux-64/repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f29bd1bd580>, 'Connection to mirrors6.tuna.tsinghua.edu.cn timed out. (connect timeout=9.15)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/exception_handler.py", line 17, in __call__
    return func(*args, **kwargs)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/cli/main.py", line 64, in main_subshell
    exit_code = do_call(args, parser)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 167, in do_call
    result = getattr(module, func_name)(args, parser)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/notices/core.py", line 124, in wrapper
    return func(*args, **kwargs)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/cli/main_install.py", line 26, in execute
    install(args, parser, "install")
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/cli/install.py", line 316, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 154, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/core/solve.py", line 215, in solve_for_diff
    final_precs = self.solve_final_state(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/solver.py", line 185, in solve_final_state
    index = LibMambaIndexHelper(
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/index.py", line 125, in __init__
    self._index = self._load_channels()
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/index.py", line 248, in _load_channels
    jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/index.py", line 248, in <dictcomp>
    jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
  File "/home/myname/programs/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 608, in result_iterator
    yield fs.pop().result()
  File "/home/myname/programs/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/home/myname/programs/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/home/myname/programs/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda_libmamba_solver/index.py", line 214, in _fetch_channel
    json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 770, in fetch_latest_path
    _, state = self.fetch_latest()
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 880, in fetch_latest
    raw_repodata = repo.repodata(cache.state)  # type: ignore
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 154, in repodata
    response.raise_for_status()
  File "/home/myname/programs/miniconda3/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/myname/programs/miniconda3/lib/python3.9/site-packages/conda/gateways/repodata/__init__.py", line 339, in conda_http_errors
    raise CondaHTTPError(
conda.exceptions.CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
'https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64'
```
My condarc is:
```
auto_activate_base: false
channels:
  - defaults
show_channel_urls: true
default_channels:
  - https://mirrors.pku.edu.cn/anaconda/pkgs/main
custom_channels:
  conda-forge: https://mirrors.pku.edu.cn/anaconda/cloud
  pytorch: https://mirrors.pku.edu.cn/anaconda/cloud
solver: libmamba
```
I used the mirror `https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main` in the past. `https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main` is ipv6-only. I don't have any ipv6 address now. So I change to the pku mirror. 

The above error occurs in the `base` env. After changing to the pku mirror, I create other envs. In those new envs, `conda install` works well.

Today, I update conda to the up-to-date version and try `conda clean -a`. That doesn't help.

### Conda Info

```shell
active environment : base
    active env location : /home/myname/programs/miniconda3
            shell level : 1
       user config file : /home/myname/.condarc
 populated config files : /home/myname/.condarc
          conda version : 23.7.4
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __archspec=1=x86_64
                          __cuda=11.2=0
                          __glibc=2.17=0
                          __linux=3.10.0=0
                          __unix=0=0
       base environment : /home/myname/programs/miniconda3  (writable)
      conda av data dir : /home/myname/programs/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.pku.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.pku.edu.cn/anaconda/pkgs/main/noarch
          package cache : /home/myname/programs/miniconda3/pkgs
                          /home/myname/.conda/pkgs
       envs directories : /home/myname/programs/miniconda3/envs
                          /home/myname/.conda/envs
               platform : linux-64
             user-agent : conda/23.7.4 requests/2.29.0 CPython/3.9.7 Linux/3.10.0-1160.el7.x86_64 centos/7.9.2009 glibc/2.17 solver/libmamba conda-libmamba-solver/23.5.0 libmambapy/1.4.1
                UID:GID : 1005:1005
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /home/myname/.condarc <==
auto_activate_base: False
channels:
  - defaults
custom_channels:
  conda-forge: https://mirrors.pku.edu.cn/anaconda/cloud
  pytorch: https://mirrors.pku.edu.cn/anaconda/cloud
default_channels:
  - https://mirrors.pku.edu.cn/anaconda/pkgs/main
show_channel_urls: True
solver: libmamba

==> cmd_line <==
debug: False
json: False
```

### Conda list

```shell
# packages in environment at /home/myname/programs/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    conda-forge
_openmp_mutex             5.1                       1_gnu    defaults
boltons                   23.0.0           py39h06a4308_0    defaults
brotlipy                  0.7.0           py39h27cfd23_1003    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
c-ares                    1.19.0               h5eee18b_0    defaults
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h74dc2b5_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
conda                     23.7.4           py39hf3d152e_0    conda-forge
conda-libmamba-solver     23.5.0           py39h06a4308_0    defaults
conda-package-handling    2.1.0            py39h06a4308_0    defaults
conda-package-streaming   0.8.0            py39h06a4308_0    defaults
cryptography              39.0.1           py39h9ce1e76_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
icu                       58.2                 he6710b0_3    defaults
idna                      3.4              py39h06a4308_0    defaults
jsonpatch                 1.32               pyhd3eb1b0_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h568e23c_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                hb4bd9a0_1    defaults
libcurl                   8.1.1                h91b91d3_1    defaults
libedit                   3.1.20221030         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.3                  he6710b0_2    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.4.1                hdb19cb5_0    defaults
libmambapy                1.4.1            py39hdb19cb5_0    defaults
libnghttp2                1.52.0               ha637b67_1    defaults
libsolv                   0.7.22               he621ea3_0    defaults
libssh2                   1.10.0               h37d81fd_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libxml2                   2.10.3               hcbfbd50_0    defaults
lz4-c                     1.9.4                h6a678d5_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
openssl                   1.1.1u               h7f8727e_0    defaults
packaging                 23.0             py39h06a4308_0    defaults
pcre2                     10.37                he7ceb23_1    defaults
pip                       23.0.1           py39h06a4308_0    defaults
pip-autoremove            0.10.0             pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.4            py39h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pyopenssl                 23.0.0           py39h06a4308_0    defaults
pysocks                   1.7.1            py39h06a4308_0    defaults
python                    3.9.7                h12debd9_1    defaults
python_abi                3.9                      2_cp39    conda-forge
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.29.0           py39h06a4308_0    defaults
ruamel.yaml               0.17.21          py39h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6            py39h5eee18b_1    defaults
ruamel_yaml               0.15.100         py39h27cfd23_0    defaults
setuptools                67.8.0           py39h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
toolz                     0.12.0           py39h06a4308_0    defaults
tqdm                      4.65.0           py39hb070fc8_0    defaults
tzdata                    2023c                h04d1e81_0    defaults
urllib3                   1.26.15          py39h06a4308_0    defaults
wheel                     0.38.4           py39h06a4308_0    defaults
xz                        5.4.2                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yaml-cpp                  0.7.0                h295c915_1    defaults
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0           py39h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by travishathaway** [comment]
Hi @shelfofclub,

Were you able to solve this issue by changing to "pku"? I think you identified the problem yourself by diagnosing the IPV6 issue. All of your previous connections to the mirror were timing out. That's probably why, but I can't say for certain.

Please contact the owners of these mirrors for further support.

**Comment by shelfofclub** [comment]
@travishathaway I think the key of the problem is not the pku mirror.

This issue occurred after changing to the pku mirror. At present, I use the pku mirror in my config file and no other mirror in the config file. The tuna mirror (`https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main`) is what I used in the past and do not use at present.

**So, at present, `conda` should not send a request to `https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main`.**

I have tried to use `conda` with a proxy. According to the log of my proxy server, `conda` sent requests to both the pku mirror and `https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main`.

---

My conda is installed in `~/programs/miniconda3`.
In `~/programs/miniconda3/pkgs/cache` and `~/programs/miniconda3/pkgs/urls.txt`, I find somethings about `https//mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main` which should be cleaned when cleaning cache (conda clean -a).
In `~/programs/miniconda3/pkgs/cache/1f789118.info.json`
```
{
  "url": "https://mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64",
  "etag": "W/\"65ea3b4d-306e8cd\"",
  "mod": "Thu, 07 Mar 2024 22:10:21 GMT",
  "mtime_ns": 1710165545980719299,
  "size": 50784461,
  "refresh_ns": 1710165546014750642
}
```
In `~/programs/miniconda3/pkgs/urls.txt`
```
https://repo.anaconda.com/pkgs/main/linux-64/python-3.9.1-hdb3f193_2.conda
... (many many lines)
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/certifi-2020.12.5-py37h06a4308_0.conda
...
https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64/openssl-1.1.1k-h27cfd23_0.conda
https://mirrors6.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/tqdm-4.59.0-pyhd3eb1b0_1.conda
...
https://mirrors.pku.edu.cn/anaconda/pkgs/main/linux-64/setuptools-67.8.0-py39h06a4308_0.conda
...
```

**Comment by travishathaway** [comment]
@shelfofclub,

Thank you for helping me understand the problem better.

I think you have indeed pointed at an improvement that we could make with the conda cache command. I will run this by some of my co-maintainers to see what they think.

Thanks again for helping us debug this.

**Comment by travishathaway** [comment]
Not stale.
