### ISSUE TITLE
KeyError: 'build_number' on doing conda update conda --yes

### ISSUE THREAD

**Issue by jonathanunderwood** [conda/conda#1372]
I am trying to use conda in a pristine virtualenv. 

```
pip install conda && conda init
```

works fine, but then issuing 

```
conda update conda --yes 
```

immediately afterwards results in:

``` shell
Fetching package metadata: ..
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/jgu/tmp/venv/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/jgu/tmp/venv/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/jgu/tmp/venv/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/home/jgu/tmp/venv/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/home/jgu/tmp/venv/lib/python2.7/site-packages/conda/cli/install.py", line 236, in install
    m['name'] == name]
KeyError: 'build_number'
(venv)[jgu@withnail tmp]$ conda info
Current conda install:

             platform : linux-64
        conda version : unknown
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.7.0
    root environment : /home/jgu/tmp/venv  (writable)
  default environment : /home/jgu/tmp/venv
     envs directories : /home/jgu/tmp/venv/envs
        package cache : /home/jgu/tmp/venv/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : True
```

The full session was simply:
1. virtualenv venv
2. source venv/bin/activate
3. pip install conda
4. conda init
5.  conda update conda --yes

**Comment by tdhopper** [comment]
I'm trying to install conda with pip in Travis and [getting the same error](https://travis-ci.org/datamicroscopes/lda/builds/74916972)

**Comment by asmeurer** [comment]
Note that `conda init` is deprecated.

**Comment by tdhopper** [comment]
👍2

**Comment by soapy1** [comment]
@jonathanunderwood  is this still an issue for you?

**Comment by jonathanunderwood** [comment]
I haven't had reason to use Conda in a long time, so I really dont know if it's still an issue. Sorry.
