### ISSUE TITLE
Cannot install requests without having request installed

### ISSUE THREAD

**Issue by Gerenuk** [conda/conda#1373]
I was try to install packages offline, by downloading them and running `conda install ....bar.bz2`. One of the packages requested to uninstall an older(?) version of `requests` which I granted. Unfortunately now I cannot install anything new since `requests`is missing:

	C:\Python Packages>C:\Anaconda3-2.2.0-x64\Scripts\conda.exe install requests-2.7.0-py34_0.tar.bz2
	Traceback (most recent call last):
	  File "C:\Anaconda3-2.2.0-x64\Scripts\conda-script.py", line 2, in <module>
	    from conda.cli import main
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\cli\__init__.py", line 8, in <module>
	    from conda.cli.main import main
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\cli\main.py", line 48, in <module>
	    from conda.cli import main_create
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\cli\main_create.py", line 11, in <module>
	    from conda.cli import common, install
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\cli\install.py", line 20, in <module>
	    import conda.plan as plan
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\plan.py", line 24, in <module>
	    from conda import instructions as inst
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\instructions.py", line 7, in <module>
	    from conda.fetch import fetch_pkg
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\fetch.py", line 24, in <module>
	    from conda.connection import CondaSession, unparse_url, RETRIES
	  File "C:\Anaconda3-2.2.0-x64\lib\site-packages\conda\connection.py", line 23, in <module>
	    import requests
	ImportError: No module named 'requests'

What can I do and is this an issue that can be considered?

**Comment by asmeurer** [comment]
You can manually install requests with `pip`, or if you must do it offline, download the tarball from PyPI and use `setup.py install`.
