### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: '/DATA/anaconda3/pkgs/cache/497deca9.info.json'

### ISSUE THREAD

**Issue by mukherjeesougata** [conda/conda#13761]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to install espnet toolkit using the [this](https://espnet.github.io/espnet/installation.html) documentation after setting up a conda environment. But after running the ```make``` command I am getting the following error:-
```
Traceback (most recent call last):
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/notices/core.py", line 124, in wrapper
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/cli/main_install.py", line 140, in execute
        return install(args, parser, "install")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/cli/install.py", line 360, in install
        unlink_link_transaction = solver.solve_for_transaction(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/core/solve.py", line 148, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(
                                   ^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/core/solve.py", line 217, in solve_for_diff
        final_precs = self.solve_final_state(
                      ^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda_libmamba_solver/solver.py", line 207, in solve_final_state
        index = IndexHelper(
                ^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 136, in __init__
        self._index = self._load_channels()
                      ^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 332, in _load_channels
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 332, in <dictcomp>
        jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
        yield _result_or_cancel(fs.pop())
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
        return fut.result(timeout)
               ^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 456, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/DATA/anaconda3/lib/python3.11/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda_libmamba_solver/index.py", line 254, in _fetch_channel
        json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 734, in fetch_latest_path
        _, state = self.fetch_latest()
                   ^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 774, in fetch_latest
        cache.load_state()
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 577, in load_state
        self.load(state_only=True)
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 524, in load
        with self.lock("r+") as state_file:
      File "/DATA/anaconda3/lib/python3.11/contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/site-packages/conda/gateways/repodata/__init__.py", line 643, in lock
        with self.cache_path_state.open(mode) as state_file, lock(state_file):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/DATA/anaconda3/lib/python3.11/pathlib.py", line 1044, in open
        return io.open(self, mode, buffering, encoding, errors, newline)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    PermissionError: [Errno 13] Permission denied: '/DATA/anaconda3/pkgs/cache/497deca9.info.json'

`$ /DATA/anaconda3/bin/conda install -y libflac -c conda-forge`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=espnet_w_cat_feats
                CONDA_EXE=/DATA/anaconda3/bin/conda
             CONDA_PREFIX=/DATA/anaconda3/envs/espnet_w_cat_feats
           CONDA_PREFIX_1=/DATA/anaconda3
    CONDA_PROMPT_MODIFIER=(espnet_w_cat_feats)
         CONDA_PYTHON_EXE=/DATA/anaconda3/bin/python
               CONDA_ROOT=/DATA/anaconda3
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/local/cuda-12.4/lib64
               LD_PRELOAD=<not set>
                     PATH=/DATA/anaconda3/envs/espnet_w_cat_feats/bin:/usr/local/cuda-
                          12.4/bin:/DATA/anaconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/
                          sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : espnet_w_cat_feats
    active env location : /DATA/anaconda3/envs/espnet_w_cat_feats
            shell level : 2
       user config file : /home/ms/.condarc
 populated config files : /home/ms/.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=24.1.2=0
                          __cuda=12.3=0
                          __glibc=2.35=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /DATA/anaconda3  (writable)
      conda av data dir : /DATA/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /DATA/anaconda3/pkgs
                          /home/ms/.conda/pkgs
       envs directories : /DATA/anaconda3/envs
                          /home/ms/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.11.7 Linux/6.5.0-26-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6 aau/0.4.3 c/xGXmojFchG2QQld58xXarA s/fApCsf5hIC9hphT120VN-w e/1K4A9DZT8R4LcWJESOssmw
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload successful.
make: *** [Makefile:59: flac.done] Error 1
```
I have previously installed espnet using other conda environments, but didn't encounter this error.

### Conda Info

```shell
active environment : espnet_w_cat_feats
    active env location : /DATA/anaconda3/envs/espnet_w_cat_feats
            shell level : 2
       user config file : /home/ms/.condarc
 populated config files : /home/ms/.condarc
          conda version : 24.1.2
    conda-build version : 24.1.2
         python version : 3.11.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=24.1.2=0
                          __cuda=12.3=0
                          __glibc=2.35=0
                          __linux=6.5.0=0
                          __unix=0=0
       base environment : /DATA/anaconda3  (writable)
      conda av data dir : /DATA/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /DATA/anaconda3/pkgs
                          /home/ms/.conda/pkgs
       envs directories : /DATA/anaconda3/envs
                          /home/ms/.conda/envs
               platform : linux-64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.11.7 Linux/6.5.0-26-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.6 aau/0.4.3 c/xGXmojFchG2QQld58xXarA s/YS83oAhTTC8Xdg_6SyVwsg e/1K4A9DZT8R4LcWJESOssmw
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
conda config --show-sources
==> /home/ms/.condarc <==
auto_activate_base: False
```

### Conda list

```shell
# packages in environment at /DATA/anaconda3/envs/espnet_w_cat_feats:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
_openmp_mutex             5.1                       1_gnu    defaults
archspec                  0.2.3              pyhd3eb1b0_0    defaults
blas                      1.0                         mkl    defaults
boltons                   23.0.0           py38h06a4308_0    defaults
brotli-python             1.0.9            py38h6a678d5_7    defaults
bzip2                     1.0.8                h5eee18b_5    defaults
c-ares                    1.19.1               h5eee18b_0    defaults
ca-certificates           2024.3.11            h06a4308_0    defaults
certifi                   2024.2.2         py38h06a4308_0    defaults
cffi                      1.16.0           py38h5eee18b_0    defaults
charset-normalizer        2.0.4              pyhd3eb1b0_0    defaults
cmake                     3.26.4               h96355d8_0    defaults
conda                     24.3.0           py38h06a4308_0    defaults
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0    defaults
conda-package-handling    2.2.0            py38h06a4308_0    defaults
conda-package-streaming   0.9.0            py38h06a4308_0    defaults
cuda-cudart               12.1.105                      0    nvidia
cuda-cupti                12.1.105                      0    nvidia
cuda-libraries            12.1.0                        0    nvidia
cuda-nvrtc                12.1.105                      0    nvidia
cuda-nvtx                 12.1.105                      0    nvidia
cuda-opencl               12.4.99                       0    nvidia
cuda-runtime              12.1.0                        0    nvidia
distro                    1.8.0            py38h06a4308_0    defaults
expat                     2.5.0                h6a678d5_0    defaults
filelock                  3.13.1           py38h06a4308_0    defaults
fmt                       9.1.0                hdb19cb5_0    defaults
gmp                       6.2.1                h295c915_3    defaults
gmpy2                     2.1.2            py38heeb90bb_0    defaults
icu                       73.1                 h6a678d5_0    defaults
idna                      3.4              py38h06a4308_0    defaults
importlib-metadata        7.1.0                    pypi_0    pypi
intel-openmp              2023.1.0         hdb19cb5_46306    defaults
jinja2                    3.1.3            py38h06a4308_0    defaults
jsonpatch                 1.33             py38h06a4308_0    defaults
jsonpointer               2.1                pyhd3eb1b0_0    defaults
krb5                      1.20.1               h143b758_1    defaults
ld_impl_linux-64          2.38                 h1181459_1    defaults
libarchive                3.6.2                h6ac8c49_2    defaults
libcublas                 12.1.0.26                     0    nvidia
libcufft                  11.0.2.4                      0    nvidia
libcufile                 1.9.0.20                      0    nvidia
libcurand                 10.3.5.119                    0    nvidia
libcurl                   8.5.0                h251f7ec_0    defaults
libcusolver               11.4.4.55                     0    nvidia
libcusparse               12.0.2.55                     0    nvidia
libedit                   3.1.20230828         h5eee18b_0    defaults
libev                     4.33                 h7f8727e_1    defaults
libffi                    3.4.4                h6a678d5_0    defaults
libgcc-ng                 11.2.0               h1234567_1    defaults
libgomp                   11.2.0               h1234567_1    defaults
libmamba                  1.5.8                hfe524e5_1    defaults
libmambapy                1.5.8            py38h2dafd23_1    defaults
libnghttp2                1.57.0               h2d74bed_0    defaults
libnpp                    12.0.2.50                     0    nvidia
libnvjitlink              12.1.105                      0    nvidia
libnvjpeg                 12.1.1.14                     0    nvidia
libsolv                   0.7.24               he621ea3_0    defaults
libssh2                   1.10.0               hdbd6064_2    defaults
libstdcxx-ng              11.2.0               h1234567_1    defaults
libuv                     1.44.2               h5eee18b_0    defaults
libxml2                   2.10.4               hf1b16e4_1    defaults
llvm-openmp               14.0.6               h9e868ea_0    defaults
llvmlite                  0.41.1                   pypi_0    pypi
lz4-c                     1.9.4                h6a678d5_0    defaults
markupsafe                2.1.3            py38h5eee18b_0    defaults
menuinst                  2.0.2            py38h06a4308_0    defaults
mkl                       2023.1.0         h213fc3f_46344    defaults
mkl-service               2.4.0            py38h5eee18b_1    defaults
mkl_fft                   1.3.8            py38h5eee18b_0    defaults
mkl_random                1.2.4            py38hdb19cb5_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.2                hb69a4c5_1    defaults
mpmath                    1.3.0            py38h06a4308_0    defaults
ncurses                   6.4                  h6a678d5_0    defaults
networkx                  3.1              py38h06a4308_0    defaults
numba                     0.58.1                   pypi_0    pypi
numpy                     1.23.5           py38hf6e8229_1    defaults
numpy-base                1.23.5           py38h060ed82_1    defaults
openssl                   3.0.13               h7f8727e_0    defaults
packaging                 23.2             py38h06a4308_0    defaults
pcre2                     10.42                hebb0a14_0    defaults
pip                       23.3.1           py38h06a4308_0    defaults
platformdirs              3.10.0           py38h06a4308_0    defaults
pluggy                    1.0.0            py38h06a4308_1    defaults
pybind11-abi              4                    hd3eb1b0_1    defaults
pycosat                   0.6.6            py38h5eee18b_0    defaults
pycparser                 2.21               pyhd3eb1b0_0    defaults
pysocks                   1.7.1            py38h06a4308_0    defaults
python                    3.8.19               h955ad1f_0    defaults
pytorch                   2.1.0           py3.8_cuda12.1_cudnn8.9.2_0    pytorch
pytorch-cuda              12.1                 ha16c6d3_5    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pyyaml                    6.0.1            py38h5eee18b_0    defaults
readline                  8.2                  h5eee18b_0    defaults
reproc                    14.2.4               h295c915_1    defaults
reproc-cpp                14.2.4               h295c915_1    defaults
requests                  2.31.0           py38h06a4308_1    defaults
rhash                     1.4.3                hdbd6064_0    defaults
ruamel.yaml               0.17.21          py38h5eee18b_0    defaults
ruamel.yaml.clib          0.2.6            py38h5eee18b_1    defaults
setuptools                68.2.2           py38h06a4308_0    defaults
sqlite                    3.41.2               h5eee18b_0    defaults
sympy                     1.12             py38h06a4308_0    defaults
tbb                       2021.8.0             hdb19cb5_0    defaults
tk                        8.6.12               h1ccaba5_0    defaults
torchaudio                2.1.0                py38_cu121    pytorch
torchtriton               2.1.0                      py38    pytorch
tqdm                      4.65.0           py38hb070fc8_0    defaults
typing_extensions         4.9.0            py38h06a4308_1    defaults
urllib3                   2.1.0            py38h06a4308_1    defaults
wheel                     0.41.2           py38h06a4308_0    defaults
xz                        5.4.6                h5eee18b_0    defaults
yaml                      0.2.5                h7b6447c_0    defaults
yaml-cpp                  0.8.0                h6a678d5_0    defaults
zipp                      3.18.1                   pypi_0    pypi
zlib                      1.2.13               h5eee18b_0    defaults
zstandard                 0.19.0           py38h5eee18b_0    defaults
zstd                      1.5.5                hc292b87_0    defaults
```

**Comment by travishathaway** [comment]
@mukherjeesougata,

Is there anything special about this `/DATA/` folder that we need to know? Is it some sort of network mount or is it just a regular folder on the same hard drive as your operating system?

In the meantime, you can try running the following command to clear out your cache in case that is causing an issue:

```
conda clean --all
```

**Comment by mukherjeesougata** [comment]
It worked after running the command ```conda clean --all```. Thank you for your help.
