### ISSUE TITLE
libtorch_cpu.so: undefined symbol

### ISSUE THREAD

**Issue by Megidd** [conda/conda#13812]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

# Minimal env

A minimal environment like below is created:

```bash
conda create -n minimal_pytorch python=3.6 pytorch torchvision torchaudio -c pytorch
```

Just getting the PyTorch version by the following command would throw errors:

```bash
source activate minimal_pytorch && python -c "import torch; print(torch.__version__)"
```

This `undefined symbol` error is thrown:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/envs/minimal_pytorch/lib/python3.6/site-packages/torch/__init__.py", line 197, in <module>
    from torch._C import *  # noqa: F403
ImportError: /usr/local/envs/minimal_pytorch/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

## Python version

When Python version is omitted while creating the environment:

```bash
conda create -n minimal_pytorch python pytorch torchvision torchaudio -c pytorch
```

The error is resolved:

```
source activate minimal_pytorch && python -c "import torch; print(torch.__version__)"
```

PyTorch version is received without any error:

```
2.2.2
```

## Note

I have posted a question here too: https://stackoverflow.com/q/78328401/3405291

### Conda Info

```shell
active environment : minimal_pytorch
    active env location : /usr/local/envs/minimal_pytorch
            shell level : 1
       user config file : /root/.condarc
 populated config files : /usr/local/.condarc
          conda version : 23.11.0
    conda-build version : not installed
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=broadwell
                          __conda=23.11.0=0
                          __glibc=2.35=0
                          __linux=6.1.58=0
                          __unix=0=0
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/23.11.0 requests/2.31.0 CPython/3.10.13 Linux/6.1.58+ ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.12.0 libmambapy/1.5.5
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> /usr/local/.condarc <==
channels:
  - conda-forge
always_yes: True
```

### Conda list

```shell
# packages in environment at /usr/local/envs/minimal_pytorch:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                  2_kmp_llvm    conda-forge
blas                      2.122                       mkl    conda-forge
blas-devel                3.9.0            22_linux64_mkl    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
cudatoolkit               11.3.1              hb98b00a_13    conda-forge
dataclasses               0.8                pyh787bdff_2    conda-forge
ffmpeg                    4.3                  hf484d3e_0    pytorch
freetype                  2.12.1               h267a509_2    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
gnutls                    3.6.13               h85f3911_1    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
jpeg                      9e                   h0b41bf4_3    conda-forge
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
lerc                      3.0                  h9c3ff4c_0    conda-forge
libblas                   3.9.0            22_linux64_mkl    conda-forge
libcblas                  3.9.0            22_linux64_mkl    conda-forge
libdeflate                1.10                 h7f98852_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libhwloc                  2.10.0          default_h2fb2949_1000    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
liblapack                 3.9.0            22_linux64_mkl    conda-forge
liblapacke                3.9.0            22_linux64_mkl    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libsqlite                 3.45.2               h2797004_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libtiff                   4.3.0                h0fcbabc_4    conda-forge
libuv                     1.48.0               hd590300_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxml2                   2.12.6               h232c23b_2    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
llvm-openmp               18.1.3               h4dfa4b3_0    conda-forge
mkl                       2024.1.0           ha957f24_692    conda-forge
mkl-devel                 2024.1.0           ha770c72_692    conda-forge
mkl-include               2024.1.0           ha957f24_692    conda-forge
ncurses                   6.4.20240210         h59595ed_0    conda-forge
nettle                    3.6                  he412f7d_0    conda-forge
numpy                     1.19.5           py36hfc0c790_2    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openh264                  2.1.1                h780b84a_0    conda-forge
openjpeg                  2.5.0                h7d73246_0    conda-forge
openssl                   1.1.1w               hd590300_0    conda-forge
pillow                    8.3.2            py36h676a545_0    conda-forge
pip                       21.3.1             pyhd8ed1ab_0    conda-forge
python                    3.6.15          hb7a2778_0_cpython    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
pytorch                   1.10.2          py3.6_cuda11.3_cudnn8.2.0_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
readline                  8.2                  h8228510_1    conda-forge
setuptools                58.0.4           py36h5fab9bb_2    conda-forge
sqlite                    3.45.2               h2c6b66d_0    conda-forge
tbb                       2021.12.0            h00ab1b0_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
torchaudio                0.10.2               py36_cu113    pytorch
torchvision               0.11.3               py36_cu113    pytorch
typing_extensions         4.1.1              pyha770c72_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge
```

**Comment by ahmadmustafaanis** [comment]
F

**Comment by amughrabi** [comment]
I had a similar issue when I used `conda install`
```
python -c "import torch; print(torch.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/amughrabi/anaconda3/envs/deva/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/amughrabi/anaconda3/envs/deva/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent
```

As a workaround, I used `pip install`, and it works fine.

**Comment by travishathaway** [comment]
Hi @Megidd,

This appears to be an issue with the pytorch package itself. I encourage you to reach directly to the maintainers of that project to find a solution for your problem or to report this as a bug. @amughrabi's work around is also valid too.

**Comment by Megidd** [comment]
The error was resolved by just removing all the versions from the `environment.yml` file. There were problems with the versions and mismatches between them.

**Comment by amughrabi** [comment]
@Megidd, can you please explain how you removed the versions of `enviroment.yml`? I was using `conda clean --all`, but it seems it does not work.

**Comment by Megidd** [comment]
@amughrabi I'm going to share my final codes on Google Colab. Let me...

**Comment by Megidd** [comment]
@amughrabi We were trying to test this repository:

https://github.com/sicxu/Deep3DFaceRecon_pytorch

Our final approach on Google Colab that worked just fine is:

```bash
# Step 1: Press runtime on the top > Change runtime type > Select T4 GPU

# Step 2: Run this shell

!wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
!bash miniconda.sh -b -u -p /usr/local
!rm miniconda.sh
!conda update conda

%cd /content/
!rm -rf Deep3DFaceRecon_pytorch
!git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git
%cd Deep3DFaceRecon_pytorch
!git clone https://github.com/NVlabs/nvdiffrast
!git clone https://github.com/deepinsight/insightface.git
!cp -r ./insightface/recognition/arcface_torch ./models/

# Step 3: Mount drive and copy the files mounted in google drive:

!mkdir /content/Deep3DFaceRecon_pytorch/checkpoints
!cp -r /content/drive/MyDrive/Deep3D/facerecon_20230425 /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425
!cp /content/drive/MyDrive/Deep3D/01_MorphableModel.mat /content/Deep3DFaceRecon_pytorch/BFM/
!cp /content/drive/MyDrive/Deep3D/Exp_Pca.bin /content/Deep3DFaceRecon_pytorch/BFM/

# Step 4: Install the graphics related stuff

!sudo apt-get install libegl1-mesa-dev
!nvidia-smi
!sudo apt-get install libnvidia-gl-535

# Step 5: Run this shell to install everything

%%shell
eval "$(conda shell.bash hook)"
conda create --name deep3d_pytorch python=3.6 -y
conda activate deep3d_pytorch
conda config --env --add channels pytorch
conda config --env --add channels conda-forge
conda config --env --add channels defaults
conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch -y
conda install numpy scikit-image=0.16.2 scipy=1.4.1 pillow=6.2.1 pip ipython=7.13.0 yaml=0.1.7 -y
pip install matplotlib==2.2.5 opencv-python==3.4.9.33 tensorboard==1.15.0 tensorflow==1.15.0 kornia==0.5.5 dominate==2.6.0 trimesh==3.9.20
pip install ./nvdiffrast/.

# Step 6: Run this shell to test the program

%%shell
eval "$(conda shell.bash hook)"
conda activate deep3d_pytorch
python test.py --name=facerecon_20230425 --epoch=20 --img_folder=./datasets/examples

# Step 7: Copy test results to Google Drive

!ls /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/examples/epoch_20_000000/
!cp /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/examples/epoch_20_000000/* /content/drive/MyDrive/Deep3D/results/

# Step 8: prepare custom images along with their facial landmarks

!cp -r /content/drive/MyDrive/Deep3D/custom_images /content/Deep3DFaceRecon_pytorch/
%cd /content/Deep3DFaceRecon_pytorch/custom_images/
!rm -rf Məhəmməd.png
!python -m venv virtual_env
!source virtual_env/bin/activate && which pip
!source virtual_env/bin/activate && pip install mtcnn
!source virtual_env/bin/activate && pip install tensorflow
!source virtual_env/bin/activate && which python
!source virtual_env/bin/activate && python facial_landmarks.py # This Python script source code can be found here: https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/85#issuecomment-2069302718
%cd /content/Deep3DFaceRecon_pytorch/

# Step 9: run with custom images

%%shell
eval "$(conda shell.bash hook)"
conda activate deep3d_pytorch
python test.py --name=facerecon_20230425 --epoch=20 --img_folder=./custom_images

# Step 10: copy the results back to Google Drive

!ls /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/custom_images/epoch_20_000000/
!cp /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/custom_images/epoch_20_000000/* /content/drive/MyDrive/Deep3D/results/

```

**Comment by amughrabi** [comment]
> @amughrabi I don't know what's your exact situation. So I post all our code here.
> 
> We were trying to test this repository:
> 
> https://github.com/sicxu/Deep3DFaceRecon_pytorch
> 
> Our final approach on Google Colab that works just fine is:
> 
> ```shell
> # Step 1: Press runtime on the top > Change runtime type > Select T4 GPU
> 
> # Step 2: Run this shell
> 
> !wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
> !bash miniconda.sh -b -u -p /usr/local
> !rm miniconda.sh
> !conda update conda
> 
> %cd /content/
> !rm -rf Deep3DFaceRecon_pytorch
> !git clone https://github.com/sicxu/Deep3DFaceRecon_pytorch.git
> %cd Deep3DFaceRecon_pytorch
> !git clone https://github.com/NVlabs/nvdiffrast
> !git clone https://github.com/deepinsight/insightface.git
> !cp -r ./insightface/recognition/arcface_torch ./models/
> 
> # Step 3: Mount drive and copy the files mounted in google drive:
> 
> !mkdir /content/Deep3DFaceRecon_pytorch/checkpoints
> !cp -r /content/drive/MyDrive/Deep3D/facerecon_20230425 /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425
> !cp /content/drive/MyDrive/Deep3D/01_MorphableModel.mat /content/Deep3DFaceRecon_pytorch/BFM/
> !cp /content/drive/MyDrive/Deep3D/Exp_Pca.bin /content/Deep3DFaceRecon_pytorch/BFM/
> 
> # Step 4: Install the graphics related stuff
> 
> !sudo apt-get install libegl1-mesa-dev
> !nvidia-smi
> !sudo apt-get install libnvidia-gl-535
> 
> # Step 5: Run this shell to install everything
> 
> %%shell
> eval "$(conda shell.bash hook)"
> conda create --name deep3d_pytorch python=3.6 -y
> conda activate deep3d_pytorch
> conda config --env --add channels pytorch
> conda config --env --add channels conda-forge
> conda config --env --add channels defaults
> conda install pytorch==1.6.0 torchvision==0.7.0 cudatoolkit=10.2 -c pytorch -y
> conda install numpy scikit-image=0.16.2 scipy=1.4.1 pillow=6.2.1 pip ipython=7.13.0 yaml=0.1.7 -y
> pip install matplotlib==2.2.5 opencv-python==3.4.9.33 tensorboard==1.15.0 tensorflow==1.15.0 kornia==0.5.5 dominate==2.6.0 trimesh==3.9.20
> pip install ./nvdiffrast/.
> 
> # Step 6: Run this shell to test the program
> 
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate deep3d_pytorch
> python test.py --name=facerecon_20230425 --epoch=20 --img_folder=./datasets/examples
> 
> # Step 7: Copy test results to Google Drive
> 
> !ls /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/examples/epoch_20_000000/
> !cp /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/examples/epoch_20_000000/* /content/drive/MyDrive/Deep3D/results/
> 
> # Step 8: prepare custom images along with their facial landmarks
> 
> !cp -r /content/drive/MyDrive/Deep3D/custom_images /content/Deep3DFaceRecon_pytorch/
> %cd /content/Deep3DFaceRecon_pytorch/custom_images/
> !python -m venv virtual_env
> !source virtual_env/bin/activate && which pip
> !source virtual_env/bin/activate && pip install mtcnn
> !source virtual_env/bin/activate && pip install tensorflow
> !source virtual_env/bin/activate && which python
> !source virtual_env/bin/activate && python facial_landmarks.py # This Python script source code can be found here: https://github.com/sicxu/Deep3DFaceRecon_pytorch/issues/85#issuecomment-2069302718
> %cd /content/Deep3DFaceRecon_pytorch/
> 
> # Step 9: run with custom images
> 
> %%shell
> eval "$(conda shell.bash hook)"
> conda activate deep3d_pytorch
> python test.py --name=facerecon_20230425 --epoch=20 --img_folder=./custom_images
> 
> # Step 10: copy the results back to Google Drive
> 
> !ls /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/custom_images/epoch_20_000000/
> !cp /content/Deep3DFaceRecon_pytorch/checkpoints/facerecon_20230425/results/custom_images/epoch_20_000000/* /content/drive/MyDrive/Deep3D/results/
> ```

Thanks a million for sharing, @Megidd!
