### ISSUE TITLE
Termux: Fedora39 chroot & Fedora40 chroot - cannot `conda init bash`

### ISSUE THREAD

**Issue by b9Joker108** [conda/conda#13829]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

(Note: Just as an aside: I installed Miniconda3 in a Termux Debian chroot, and was able to initialise - Bash, Zsh, Fish and Tcsh, but unfortunately not Nu.)

First, in both Termux Fedora chroots:

 I made .bashrc and .tcshrc executable

 ```bash
root@localhost:~# dnf update && dnf upgrade
...
root@localhost:~# dnf install conda
...
root@localhost:~# conda --version
conda 24.1.2
root@localhost:~# which conda
/bin/conda
root@localhost:~# sudo conda init bash

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main_init.py", line 155, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/core/initialize.py", line 139, in initialize
        run_plan_elevated(plan2)
      File "/usr/lib/python3.12/site-packages/conda/core/initialize.py", line 856, in run_plan_elevated
        result = subprocess_call(
                 ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/gateways/subprocess.py", line 102, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/subprocess.py", line 2093, in _communicate
        input_view = memoryview(self._input)
                     ^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /usr/bin/conda init bash`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/usr/share/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/
                          snapd/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             SUDO_COMMAND=/usr/bin/conda init bash
                 SUDO_GID=0
                 SUDO_UID=0
                SUDO_USER=root

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /root/.condarc
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=neoverse_n1
                          __conda=24.1.2=0
                          __glibc=2.39=0
                          __linux=5.15.94=0
                          __unix=0=0
       base environment : /usr  (read only)
      conda av data dir : /etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.conda/envs
                          /usr/envs
               platform : linux-aarch64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.12.2 Linux/5.15.94-android13-8-27940245-abX910XXU1BWL1 fedora/40 glibc/2.39 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.6
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload successful.
root@localhost:~# sudo conda init tcsh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/conda/exception_handler.py", line 17, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main.py", line 83, in main_subshell
        exit_code = do_call(args, parser)
                    ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/conda_argparse.py", line 196, in do_call
        result = getattr(module, func_name)(args, parser)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/cli/main_init.py", line 155, in execute
        return initialize(
               ^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/core/initialize.py", line 139, in initialize
        run_plan_elevated(plan2)
      File "/usr/lib/python3.12/site-packages/conda/core/initialize.py", line 856, in run_plan_elevated
        result = subprocess_call(
                 ^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/conda/gateways/subprocess.py", line 102, in subprocess_call
        stdout, stderr = process.communicate(input=stdin)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/subprocess.py", line 1209, in communicate
        stdout, stderr = self._communicate(input, endtime, timeout)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib64/python3.12/subprocess.py", line 2093, in _communicate
        input_view = memoryview(self._input)
                     ^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: memoryview: a bytes-like object is required, not 'str'

`$ /usr/bin/conda init tcsh`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/usr/share/conda
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/lib/
                          snapd/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             SUDO_COMMAND=/usr/bin/conda init tcsh
                 SUDO_GID=0
                 SUDO_UID=0
                SUDO_USER=root

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /root/.condarc
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=neoverse_n1
                          __conda=24.1.2=0
                          __glibc=2.39=0
                          __linux=5.15.94=0
                          __unix=0=0
       base environment : /usr  (read only)
      conda av data dir : /etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.conda/envs
                          /usr/envs
               platform : linux-aarch64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.12.2 Linux/5.15.94-android13-8-27940245-abX910XXU1BWL1 fedora/40 glibc/2.39 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.6
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>

Upload successful.
```

And:

```bash
(base) [root@localhost ~]# conda --version
conda 23.9.0
```

### Conda Info

```shell
root@localhost:~# conda info

     active environment : None
       user config file : /root/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /root/.condarc
          conda version : 24.1.2
    conda-build version : not installed
         python version : 3.12.2.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=neoverse_n1
                          __conda=24.1.2=0
                          __glibc=2.39=0
                          __linux=5.15.94=0
                          __unix=0=0
       base environment : /usr  (read only)
      conda av data dir : /etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.conda/envs
                          /usr/envs
               platform : linux-aarch64
             user-agent : conda/24.1.2 requests/2.31.0 CPython/3.12.2 Linux/5.15.94-android13-8-27940245-abX910XXU1BWL1 fedora/40 glibc/2.39 solver/libmamba conda-libmamba-solver/23.11.1 libmambapy/1.5.6
                UID:GID : 0:0
             netrc file : None
           offline mode : False


And:

```bash
(base) [root@localhost ~]# conda info

     active environment : base
    active env location : /usr
            shell level : 1
       user config file : /root/.condarc
 populated config files : /usr/share/conda/condarc.d/defaults.yaml
                          /root/.condarc
          conda version : 23.9.0
    conda-build version : not installed
         python version : 3.12.2.final.0
       virtual packages : __archspec=1=aarch64
                          __glibc=2.38=0
                          __linux=6.2.1=0
                          __unix=0=0
       base environment : /usr  (read only)
      conda av data dir : /etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-aarch64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-aarch64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /root/.conda/envs
                          /usr/envs
               platform : linux-aarch64
             user-agent : conda/23.9.0 requests/2.28.2 CPython/3.12.2 Linux/6.2.1-PRoot-Distro fedora/39 glibc/2.38
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
(base) [root@localhost ~]# conda config --show-sources
==> /usr/share/conda/condarc.d/defaults.yaml <==
pkgs_dirs:
  - /var/cache/conda/pkgs
  - ~/.conda/pkgs

==> /root/.condarc <==
report_errors: True


And:

```bash
root@localhost:~# conda config --show-sources
==> /usr/share/conda/condarc.d/defaults.yaml <==
pkgs_dirs:
  - /var/cache/conda/pkgs
  - ~/.conda/pkgs

==> /root/.condarc <==
report_errors: True
```

### Conda list

```shell
root@localhost:~# conda list --show-channel-urls

EnvironmentLocationNotFound: Not a conda environment: /usr


And:

```bash
(base) [root@localhost ~]# conda list --show-channel-urls

EnvironmentLocationNotFound: Not a conda environment: /usr
```

### Additional Context

n/a

```bash
(base) [root@localhost ~]# uname -a
Linux localhost 6.2.1-PRoot-Distro #1 SMP PREEMPT Mon Dec 4 10:05:43 UTC 2023 aarch64 GNU/Linux
(base) [root@localhost ~]#
```

And:

```bash
root@localhost:~# uname -a
Linux localhost 5.15.94-android13-8-27940245-abX910XXU1BWL1 #1 SMP PREEMPT Mon Dec 4 10:05:43 UTC 2023 aarch64 GNU/Linux
```

And Termux host:

```zsh
❯ uname -a
Linux localhost 5.15.94-android13-8-27940245-abX910XXU1BWL1 #1 SMP PREEMPT Mon Dec 4 10:05:43 UTC 2023 aarch64 Android

**Comment by travishathaway** [comment]
Hi @b9Joker108,

I noticed you are running conda as root but still using `sudo conda ...`. Have you experiment with just simply running `conda` with prepending `sudo`?

We've seen this error before. You may want to read through this issue to get some additional context around why this may be happening:

- https://github.com/conda/conda/issues/13423

**Comment by b9Joker108** [comment]
I will definitely give what you provided a read. I thank you for your response. I am using conda from Miniforge3 successfully to manage a Python environment, in one of my Debian chroots in Termux. This chroot is a proot-distro alias of Debian, and conda was succesfully initialised on four shells within this chroot, whilst logged-on in as the privileged super user account. I have a non-privilaged user in this chroot, but don't often use it. In proot chroots, there is no real difference between privileged and non-privileged users, it is all semantic jugglery, with no tangible difference. 

So, in this context, I find it perplexing, that I downloaded the conda package with the official package managers in one of my Fedora proot-distro chroots, which I understand is too, a wrapper of Anaconda, but doesn't seem to maintain the propensity to establish conda environments. And, in one of my Fedora proot-chroots, I just haven't been able to initialise any shell in the super-user pseudo-root, proxy-root, or PRoot of that chroot. I haven't tried in;my second Fedora chroot, instituted with a different script, process and mechanism. I am very new to Fedora. I last used Fedora more that fifteen years ago, and unlike other GNU/Linux distributions I have courted, was not a positive experience.

**Comment by b9Joker108** [comment]
I just wanted to note a curiosity:

```bash
root@localhost:~# cat /etc/os-release
NAME="Fedora Linux"
VERSION="40 (Container Image)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40 (Container Image)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f40/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Container Image"
VARIANT_ID=container
```

**Comment by b9Joker108** [comment]
I got it to work, with the `conda` of the `dnf` package. The shell that was initially unsuccessful, now states `base`. So, issue closed.
