### ISSUE TITLE
All the conda command cannot be used after trying to upgrade to the latest version of conda

### ISSUE THREAD

**Issue by WillCh07** [conda/conda#13883]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

During installing the miniwdl package, conda suggested to run the 
"conda update -n base -c conda-forge --all"
or
"conda install -n base conda=24.3.1"

After performing the update, I get the error messages like

### Conda Info

```shell
active environment : base
    active env location : /localhome/smrtuser/miniconda2
            shell level : 1
       user config file : /localhome/smrtuser/.condarc
 populated config files : /localhome/smrtuser/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.15.final.0
       virtual packages : __glibc=2.17
       base environment : /localhome/smrtuser/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /localhome/smrtuser/miniconda2/pkgs
                          /localhome/smrtuser/.conda/pkgs
       envs directories : /localhome/smrtuser/miniconda2/envs
                          /localhome/smrtuser/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.25.1 CPython/2.7.15 Linux/3.10.0-514.10.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 501:501
             netrc file : None
           offline mode : False
```

### Additional Context

```
$ conda env list
Traceback (most recent call last):
  File "/localhome/smrtuser/miniconda2/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 26, in <module>
    from .core.link import PrefixSetup, UnlinkLinkTransaction
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 43, in <module>
    from ..resolve import MatchSpec
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 9, in <module>
    from tqdm import tqdm
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/tqdm/__init__.py", line 3, in <module>
    from .cli import main  # TODO: remove in v5.0.0
  File "/localhome/smrtuser/miniconda2/lib/python2.7/site-packages/tqdm/cli.py", line 202
    sys.stderr.write(f"Error:Unknown argument:{argv[0]}\n{help_short}")
                                                                     ^
SyntaxError: invalid syntax

And error messages when installing the miniwdl:
create -n miniwdl -c conda-forge -c bioconda miniwdl`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/localhome/smrtuser/miniconda2/bin/conda
             CONDA_PREFIX=/localhome/smrtuser/miniconda2
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/localhome/smrtuser/miniconda2/bin/python
               CONDA_ROOT=/localhome/smrtuser/miniconda2
              CONDA_SHLVL=1
     JAVA_LD_LIBRARY_PATH=/localhome/smrtuser/miniconda2/lib/server
          LD_LIBRARY_PATH=:/localdisk/home/smrtuser/miniconda2/lib:/localdisk/home/smrtuser/soft
                          wares/java/jdk-11.0.14/lib
               MODULEPATH=/usr/local/Modules/versions:/usr/local/Modules/3.2.10/modulefiles:/usr
                          /local/Modules/modulefiles
                     PATH=/localhome/smrtuser/miniconda2/bin:/localhome/smrtuser/.cargo/bin:/loc
                          alhome/smrtuser/miniconda2/bin:/localhome/smrtuser/miniconda2/condabin
                          :/localhome/smrtuser/SL5beta/admin/bin:/localhome/smrtuser/softwares/j
                          ava/jdk-11.0.14/bin:/localhome/smrtuser/SL5beta/smrtcmds/bin:/localhom
                          e/smrtuser/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/loca
                          l/sbin:/usr/sbin:/localhome/smrtuser/.dotnet/tools:/localhome/smrtuser
                          /miniconda2/conda/bin:/localhome/smrtuser/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /localhome/smrtuser/miniconda2
            shell level : 1
       user config file : /localhome/smrtuser/.condarc
 populated config files : /localhome/smrtuser/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 2.7.15.final.0
       virtual packages : __glibc=2.17
       base environment : /localhome/smrtuser/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /localhome/smrtuser/miniconda2/pkgs
                          /localhome/smrtuser/.conda/pkgs
       envs directories : /localhome/smrtuser/miniconda2/envs
                          /localhome/smrtuser/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.25.1 CPython/2.7.15 Linux/3.10.0-514.10.2.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 501:501
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```

Please let me know if you need any other information
Thanks!

**Comment by kenodegard** [comment]
Either you started off with a pretty old version of conda or the upgrade resulted in severe downgrades resulting in incompatible packages being installed into your base environment. E.g., your base environment has Python 2 installed along with a Python 3 version of `tqdm` which results in the error you are seeing.

Unfortunately, to recover from this you will need to re-install miniconda.
