### ISSUE TITLE
Bad package that breaks /bin will trip up conda

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1396]
A build script like this will break conda, when it tries to link "conda" into the bin directory.  This script accidentally copies the file into a file named bin and not into a directory bin.  This builds successfully, but breaks conda when installing.
```
gcc -O -o pstree pstree.c
cp pstree $PREFIX/bin
```

We should test for this since it is a common and easy error to make.  
```
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-build", line 7, in <module>
    execfile(__file__)
  File "/Users/bkreider/src/conda-build/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/bkreider/src/conda-build/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/Users/bkreider/src/conda-build/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/Users/bkreider/src/conda-build/conda_build/main_build.py", line 300, in execute
    build.test(m, verbose=not args.quiet)
  File "/Users/bkreider/src/conda-build/conda_build/build.py", line 426, in test
    create_env(config.test_prefix, specs, verbose=verbose)
  File "/Users/bkreider/src/conda-build/conda_build/build.py", line 234, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 99, in SYMLINK_CONDA_CMD
    install.symlink_conda(state['prefix'], arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 396, in symlink_conda
    os.symlink(root_conda, prefix_conda)
OSError: [Errno 20] Not a directory
```

**Comment by ilanschnell** [comment]
There is a bug in your build script.  It should be
```
gcc -O -o pstree pstree.c
mkdir $PREFIX/bin
cp pstree $PREFIX/bin
```

**Comment by asmeurer** [comment]
First off, this is a conda-build issue, not a conda issue. 

Second, conda-build doesn't attempt to create directories for you. The PREFIX starts empty. You need to `mkdir -p` any directories that you use in your build.sh. It is a common mistake, but at least if you don't forget your slashes like you did here, you should get a pretty obvious warning about it.

**Comment by bkreider** [comment]
This is both a conda-build and a conda bug.  This is a valid conda package as defined in the conda package spec.  It makes conda crash with a stack trace.  In this case it happens when conda-build is testing the package.  

There is a bug in my build script, but the fact that the bug is so easy to make means that other people are going to run into this issue.  Shouldn't conda be able to handle any packages that follow the conda package spec?

**Comment by ilanschnell** [comment]
> Shouldn't conda be able to handle any packages that follow the conda package spec?

Only if the conda package is reasonable.  There are many ways you could create a "bad" conda packages which breaks conda.  I don't think it is reasonable to safeguard against all possible ways the user could write a recipe which crashes conda-build.  The fact that conda-build crashes make this a user, and not a conda bug.

**Comment by bkreider** [comment]
Ok.  Then here is a valid issue that conda chokes on that conda-build handles just fine.   If you have two packages that have colliding directories and files, conda doesn't handle the problem -- it just crashes.  

Conflict2 is a trivial package that creates a file $prefix/conflict
Conflict1 is a trivial package that creates a file $prefix/conflict/keep

```
conda install -c bkreider conflict2
conda install -c bkreider conflict1

Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 415, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 588, in link
    os.makedirs(dst_dir)
  File "/opt/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/opt/anaconda/conflict'
```

**Comment by ilanschnell** [comment]
Perhaps conda should exit more gracefully, but essentially this is a problem with the conda packages.

**Comment by bkreider** [comment]
You are correct.  The conda error message says to report this as a bug.  However, this is a conda package "bug" that could be far removed from the package one is installing.  The package being installed could be the "good" package and the package one installed months ago could be the "bad" one.  It would be helpful to know what to do with this kind of conflict (ie: what package owns the file in question).

**Comment by asmeurer** [comment]
An error message is definitely the right thing to do here "in the face of ambiguity, refuse the temptation to guess", but it should be improved (and anyway, I guess any traceback that has the conda issue report text in it is a bug by definition).

**Comment by bkreider** [comment]
Note:  installing the packages in the reverse order doesn't trigger any kind of bug or warning, so we might also want to catch that case.

**Comment by amfarrell** [comment]
One case where this error comes up is if a user has a package installed with pip (presumably as a dependency of something else) and then if they try to install it with conda directly, it errors out.


afarrell@0068-afarrell:~$ conda list | grep anaconda-client
anaconda-client           1.0.2                     <pip>
afarrell@0068-afarrell:~$ conda install anaconda-client
Fetching package metadata: ........
Solving package specifications: ..............................
Package plan for installation in environment //anaconda:

The following NEW packages will be INSTALLED:

    anaconda-client: 1.0.2-py34_0

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the                                                 |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 613, in link
    os.makedirs(dst_dir)
  File "//anaconda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '//anaconda/lib/python3.4/site-packages/binstar_client'

**Comment by necrolyte2** [comment]
Came across this issue today because my package did
```
cp somebin $PREFIX/bin
```
without doing `mkdir -p $PREFIX/bin` first
The error message was hard to figure out what was going on without looking at the conda code.
I think at the very least trying to figure out how to get a better error message injected would be useful

**Comment by kalefranz** [comment]
> If you have two packages that have colliding directories and files, conda doesn't handle the problem -- it just crashes. If you can handle this problem, then the bug i reported will be handled nicely as well.

This will be fixed as part of https://github.com/conda/conda/pull/3571 in 4.3.
