### ISSUE TITLE
ssl_verify: truststore error

### ISSUE THREAD

**Issue by JucaVaz** [conda/conda#13971]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Trying to use ssl_verify: truststore with conda 24.5.0 ends up with this errror and makes conda usuable 

```
Traceback (most recent call last):
File "C:\ProgramData\miniconda3\Scripts\conda-token-script.py", line 9, in <module>
sys.exit(cli())
^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\conda_token\cli.py", line 116, in cli
return args.func(args)
^^^^^^^^^^^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\conda_token\cli.py", line 29, in token_set
repo_config.validate_token(args.token, no_ssl_verify=args.no_ssl_verify)
File "C:\ProgramData\miniconda3\Lib\site-packages\conda_token\repo_config.py", line 80, in validate_token
r = requests.head(token_url, verify=ssl_verify)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\requests\api.py", line 100, in head
return request("head", url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\requests\api.py", line 59, in request
return session.request(method=method, url=url, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\requests\sessions.py", line 589, in request
resp = self.send(prep, **send_kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\requests\sessions.py", line 703, in send
r = adapter.send(request, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ProgramData\miniconda3\Lib\site-packages\requests\adapters.py", line 458, in send
self.cert_verify(conn, request.url, verify, cert)
File "C:\ProgramData\miniconda3\Lib\site-packages\requests\adapters.py", line 261, in cert_verify
raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: truststore
```

### Conda Info

```shell
active environment : None

            shell level : 0

       user config file : C:\Users\username\.condarc

populated config files : C:\ProgramData\miniconda3\.condarc

                          C:\Users\username\.condarc

          conda version : 24.5.0

    conda-build version : not installed

         python version : 3.12.3.final.0

                 solver : libmamba (default)

       virtual packages : __archspec=1=icelake

                          __conda=24.5.0=0

                          __win=0=0

       base environment : C:\ProgramData\miniconda3  (writable)

      conda av data dir : C:\ProgramData\miniconda3\etc\conda

  conda av metadata url : None

           channel URLs : http://url-to-mirror/win-64

                          http://url-to-mirror/noarch

                          https://repo.anaconda.cloud/repo/main/win-64

                          https://repo.anaconda.cloud/repo/main/noarch

                          https://repo.anaconda.cloud/repo/r/win-64

                          https://repo.anaconda.cloud/repo/r/noarch

                          https://repo.anaconda.cloud/repo/msys2/win-64

                          https://repo.anaconda.cloud/repo/msys2/noarch

                          https://conda.anaconda.org/services/win-64

                          https://conda.anaconda.org/services/noarch

                          http://url-to-mirror/c/mamba/win-64

                          http://url-to-mirror/c/mamba/noarch

                          http://url-to-mirror/c/trusted-external-packages/win-64

                          http://url-to-mirror/c/trusted-external-packages/noarch

          package cache : C:\ProgramData\miniconda3\pkgs

                          C:\Users\username\.conda\pkgs

                          C:\Users\username\AppData\Local\conda\conda\pkgs

       envs directories : C:\ProgramData\miniconda3\envs

                          C:\Users\username\.conda\envs

                          C:\Users\username\AppData\Local\conda\conda\envs

               platform : win-64

             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.12.3 Windows/11 Windows/10.0.22621 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.

          administrator : False

             netrc file : None

           offline mode : False
```

### Conda Config

```shell
==> C:\ProgramData\miniconda3\.condarc <==

auto_activate_base: False

ssl_verify: truststore

add_anaconda_token: True

channels:

  - http://url-to-mirror

  - defaults

  - services

  - http://url-to-mirror/c/mamba

  - http://url-to-mirror/c/trusted-external-packages

default_channels:

  - https://repo.anaconda.cloud/repo/main

  - https://repo.anaconda.cloud/repo/r

  - https://repo.anaconda.cloud/repo/msys2

restore_free_channel: False

solver: libmamba

anaconda_upload: False

 

==> C:\Users\username\.condarc <==

auto_activate_base: False

extra_safety_checks: False

ssl_verify: False

add_anaconda_token: True

channels:

  - http://url-to-mirror

  - defaults

  - services

  - http://url-to-mirror/c/mamba

  - http://url-to-mirror/c/trusted-external-packages

default_channels:

  - https://repo.anaconda.cloud/repo/main

  - https://repo.anaconda.cloud/repo/r

  - https://repo.anaconda.cloud/repo/msys2

restore_free_channel: False

solver: libmamba

anaconda_upload: False
```

### Conda list

```shell
# packages in environment at C:\ProgramData\miniconda3:

#

# Name                    Version                   Build  Channel

anaconda-anon-usage       0.4.4           py312hfc23b7f_100    https://repo.anaconda.com/pkgs/main

archspec                  0.2.3              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main

boltons                   23.0.0          py312haa95532_0    https://repo.anaconda.com/pkgs/main

brotli-python             1.0.9           py312hd77b12b_8    https://repo.anaconda.com/pkgs/main

bzip2                     1.0.8                h2bbff1b_6    https://repo.anaconda.com/pkgs/main

ca-certificates           2024.3.11            haa95532_0    https://repo.anaconda.com/pkgs/main

certifi                   2024.2.2        py312haa95532_0    https://repo.anaconda.com/pkgs/main

cffi                      1.16.0          py312h2bbff1b_1    https://repo.anaconda.com/pkgs/main

charset-normalizer        2.0.4              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main

colorama                  0.4.6           py312haa95532_0    https://repo.anaconda.com/pkgs/main

conda                     24.5.0          py312haa95532_0    main

conda-content-trust       0.2.0           py312haa95532_1    https://repo.anaconda.com/pkgs/main

conda-libmamba-solver     24.1.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main

conda-package-handling    2.2.0           py312haa95532_1    https://repo.anaconda.com/pkgs/main

conda-package-streaming   0.9.0           py312haa95532_0    https://repo.anaconda.com/pkgs/main

conda-token               0.4.0              pyhd3eb1b0_0    main

console_shortcut_miniconda 0.1.1                haa95532_1    https://repo.anaconda.com/pkgs/main

cryptography              42.0.5          py312h89fc84f_1    https://repo.anaconda.com/pkgs/main

distro                    1.9.0           py312haa95532_0    https://repo.anaconda.com/pkgs/main

expat                     2.6.2                hd77b12b_0    https://repo.anaconda.com/pkgs/main

fmt                       9.1.0                h6d14046_1    https://repo.anaconda.com/pkgs/main

frozendict                2.4.2           py312haa95532_0    main

idna                      3.7             py312haa95532_0    https://repo.anaconda.com/pkgs/main

jsonpatch                 1.33            py312haa95532_1    https://repo.anaconda.com/pkgs/main

jsonpointer               2.1                pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main

libarchive                3.6.2                hb62f4d4_3    https://repo.anaconda.com/pkgs/main

libcurl                   8.7.1                h86230a5_0    https://repo.anaconda.com/pkgs/main

libffi                    3.4.4                hd77b12b_1    https://repo.anaconda.com/pkgs/main

libiconv                  1.16                 h2bbff1b_3    https://repo.anaconda.com/pkgs/main

libmamba                  1.5.8                h99b1521_2    https://repo.anaconda.com/pkgs/main

libmambapy                1.5.8           py312h77c03ed_2    https://repo.anaconda.com/pkgs/main

libsolv                   0.7.24               h23ce68f_1    https://repo.anaconda.com/pkgs/main

libssh2                   1.11.0               h291bd65_0    https://repo.anaconda.com/pkgs/main

libxml2                   2.10.4               h0ad7f3c_2    https://repo.anaconda.com/pkgs/main

lz4-c                     1.9.4                h2bbff1b_1    https://repo.anaconda.com/pkgs/main

menuinst                  2.0.2           py312hd77b12b_1    https://repo.anaconda.com/pkgs/main

openssl                   3.0.13               h2bbff1b_2    main

packaging                 23.2            py312haa95532_0    https://repo.anaconda.com/pkgs/main

pcre2                     10.42                h0ff8eda_1    https://repo.anaconda.com/pkgs/main

pip                       24.0            py312haa95532_0    https://repo.anaconda.com/pkgs/main

platformdirs              3.10.0          py312haa95532_0    https://repo.anaconda.com/pkgs/main

pluggy                    1.0.0           py312haa95532_1    https://repo.anaconda.com/pkgs/main

powershell_shortcut_miniconda 0.0.1                haa95532_1    https://repo.anaconda.com/pkgs/main

pybind11-abi              5                    hd3eb1b0_0    https://repo.anaconda.com/pkgs/main

pycosat                   0.6.6           py312h2bbff1b_1    https://repo.anaconda.com/pkgs/main

pycparser                 2.21               pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main

pyserial                  3.5             py312haa95532_1    defaults

pysocks                   1.7.1           py312haa95532_0    https://repo.anaconda.com/pkgs/main

python                    3.12.3               h1d929f7_1    https://repo.anaconda.com/pkgs/main

reproc                    14.2.4               hd77b12b_2    https://repo.anaconda.com/pkgs/main

reproc-cpp                14.2.4               hd77b12b_2    https://repo.anaconda.com/pkgs/main

requests                  2.31.0          py312haa95532_1    https://repo.anaconda.com/pkgs/main

ruamel.yaml               0.17.21         py312h2bbff1b_0    https://repo.anaconda.com/pkgs/main

setuptools                69.5.1          py312haa95532_0    https://repo.anaconda.com/pkgs/main

sqlite                    3.45.3               h2bbff1b_0    https://repo.anaconda.com/pkgs/main

tk                        8.6.14               h0416ee5_0    https://repo.anaconda.com/pkgs/main

tqdm                      4.66.2          py312hfc267ef_0    https://repo.anaconda.com/pkgs/main

truststore                0.8.0           py312haa95532_0    https://repo.anaconda.com/pkgs/main

tzdata                    2024a                h04d1e81_0    https://repo.anaconda.com/pkgs/main

urllib3                   2.1.0           py312haa95532_1    https://repo.anaconda.com/pkgs/main

vc                        14.2                 h21ff451_1    https://repo.anaconda.com/pkgs/main

vs2015_runtime            14.27.29016          h5e58377_2    https://repo.anaconda.com/pkgs/main

wheel                     0.43.0          py312haa95532_0    https://repo.anaconda.com/pkgs/main

win_inet_pton             1.1.0           py312haa95532_0    https://repo.anaconda.com/pkgs/main

xz                        5.4.6                h8cc25b3_1    https://repo.anaconda.com/pkgs/main

yaml-cpp                  0.8.0                hd77b12b_1    https://repo.anaconda.com/pkgs/main

zlib                      1.2.13               h8cc25b3_1    https://repo.anaconda.com/pkgs/main

zstandard                 0.22.0          py312h3469f8a_0    https://repo.anaconda.com/pkgs/main

zstd                      1.5.5                hd43e919_2    https://repo.anaconda.com/pkgs/main
```

**Comment by jezdez** [comment]
This may be an issue  with conda-repo-cli, that overwrites the `ssl_verify` value in a way that prevents the conda session not be established with the `truststore` aware SSLContext.

**Comment by dholth** [comment]
Does `Scripts\conda-token` get run by conda, what are the (non sensitive) arguments passed to `conda-token`?

We will update conda-token to be compatible with `ssl_verify="truststore"`

**Comment by jezdez** [comment]
Oh I meant conda-token, not conda-repo-cli

**Comment by jezdez** [comment]
Closing as an issue found outside conda, in the conda-token implementation.

**Comment by dholth** [comment]
@JucaVaz as a workaround, you may be able to comment out `ssl_verify: truststore`, use `conda-token set --no-ssl-verify ...` and then re-enable `ssl_verify: truststore` to use conda.

**Comment by YBrushZ** [comment]
We are aware of this workaround but this is not very user friendly.

@jezdez Does this mean the bug will not be fixed?

**Comment by dholth** [comment]
No, we will release a fixed version conda-token.

**Comment by pseudoyim** [comment]
`conda-token-0.5.0` has been released and is available in the `main` channel.
