### ISSUE TITLE
Hitting assertion because of info directory

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1397]
This shouldn't be an assertion.  I'm not sure why it is illegal, but it is not an impossible condition to hit.

How do I compile a package that creates an info directory?

```
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-build", line 7, in <module>
    execfile(__file__)
  File "/Users/bkreider/src/conda-build/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/bkreider/src/conda-build/conda_build/main_build.py", line 110, in main
    args_func(args, p)
  File "/Users/bkreider/src/conda-build/conda_build/main_build.py", line 312, in args_func
    args.func(args, p)
  File "/Users/bkreider/src/conda-build/conda_build/main_build.py", line 272, in execute
    build.build(m, verbose=not args.quiet, post=post)
  File "/Users/bkreider/src/conda-build/conda_build/build.py", line 363, in build
    assert not exists(config.info_dir)
AssertionError
```

**Comment by asmeurer** [comment]
I guess it can be removed. You'd have to check to make sure that conda can install such packages correctly.

**Comment by bkreider** [comment]
I'm not sure what that assertion is for.  The biggest problem is that it asserts something that could easily happen.  The  next problem is I don't know if the "info" directory is off-limits.  I built a simply "netcat" recipe and it wants to create man and info pages, so it creates $PREFIX/info which causes this problem.  I modified the recipe to use $PREFIX/info_ but that isn't the real answer.

**Comment by dhirschfeld** [comment]
Trying to setup an anaconda build worker and running into this issue
```
Traceback (most recent call last):
  File "C:\Python\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python\lib\site-packages\conda_build\main_build.py", line 192, in main
    args_func(args, p)
  File "C:\Python\lib\site-packages\conda_build\main_build.py", line 486, in args_func
    args.func(args, p)
  File "C:\Python\lib\site-packages\conda_build\main_build.py", line 409, in execute
    include_recipe=args.include_recipe)
  File "C:\Python\lib\site-packages\conda_build\build.py", line 473, in build
    assert not exists(config.info_dir)
AssertionError
Exit BINSTAR_BUILD_RESULT=failure

[ERROR] Build Failed
PS C:\dev\anaconda-build\conda_build_test>
```
What is the `info_dir`?? The error doesn't provide any context or information which would enable a user to do anything about it.

**Comment by dhirschfeld** [comment]
Changing the line to `assert not exists(config.info_dir), str(config.info_dir)` resulted in the more informative error message `AssertionError: C:\Python\envs\_build\info`. Knowing this I could simply delete the info directory manually and the build then succeeded.

**Comment by kalefranz** [comment]
Outdated. Closing.
