### ISSUE TITLE
`conda search -c noarch --override-channels conda` triggers `AssertionError`

### ISSUE THREAD

**Issue by dholth** [conda/conda#13996]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

When I type `$ conda search -c noarch --override-channels conda` I get an error instead of the results.

```
Loading channels: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/cli/main.py", line 84, in main_subshell
        exit_code = do_call(args, parser)
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/cli/conda_argparse.py", line 200, in do_call
        result = getattr(module, func_name)(args, parser)
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/cli/main_search.py", line 243, in execute
        SubdirData.query_all(spec, channel_urls, subdirs),
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 161, in query_all
        result = tuple(
      File "/Users/dholth/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
        yield _result_or_cancel(fs.pop())
      File "/Users/dholth/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
        return fut.result(timeout)
      File "/Users/dholth/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 458, in result
        return self.__get_result()
      File "/Users/dholth/miniconda3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
        raise self._exception
      File "/Users/dholth/miniconda3/lib/python3.10/concurrent/futures/thread.py", line 58, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 146, in subdir_query
        return tuple(
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 168, in query
        self.load()
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 271, in load
        _internal_state = self._load()
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 318, in _load
        return self._process_raw_repodata(repodata, state)
      File "/Users/dholth/miniconda3/lib/python3.10/site-packages/conda/core/subdir_data.py", line 429, in _process_raw_repodata
        assert subdir == self.channel.subdir
    AssertionError
```

### Conda Info

```shell
% conda info

     active environment : conda-index-foo
    active env location : /Users/dholth/miniconda3/envs/conda-index-foo
            shell level : 2
       user config file : /Users/dholth/.condarc
 populated config files : /Users/dholth/.condarc
          conda version : 24.5.0
    conda-build version : 24.5.1
         python version : 3.10.13.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=m1
                          __conda=24.5.0=0
                          __osx=14.5=0
                          __unix=0=0
       base environment : /Users/dholth/miniconda3  (writable)
      conda av data dir : /Users/dholth/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-arm64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-arm64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/dholth/miniconda3/pkgs
                          /Users/dholth/.conda/pkgs
       envs directories : /Users/dholth/miniconda3/envs
                          /Users/dholth/.conda/envs
               platform : osx-arm64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.13 Darwin/23.5.0 OSX/14.5 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.3 aau/0.4.3 c/3Pd2XMG8Ewd_NqK47OhyjA s/49lHYXIXgmA_bPfPFR7I7w e/z6EMwNIgqgCPEvId_yyCrQ
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```

**Comment by travishathaway** [comment]
Having a hard time recreating this error:

```
conda search -c noarch --override-channels conda
Loading channels: failed

UnavailableInvalidChannel: HTTP 404 NOT FOUND for channel  <https://conda.anaconda.org>

The channel is not accessible or is invalid.

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.
```

I think we could remove the assertion error and think about ways to recover from that condition if it is reached. Then we could either log it or continue on. I doubt this would be worth halting the execution of the program.

**Comment by dholth** [comment]
Oh, I see that I should have typed "-c conda" not "-c <a subdir>", thanks.
