### ISSUE TITLE
AttributeError: A value for entry_points has not been set

### ISSUE THREAD

**Issue by AryanNanda17** [conda/conda#14006]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I am trying to set up CI pipeline for my Jupyter notebook for [this](https://openbeagle.org/gsoc/2024/commercial-detection) project. But, I'm again and again getting failed ci pipeline error 
```bash
An HTTP error occurred when trying to retrieve this URL.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)
```
So, I tried to do the setup in my own system and figure out the error. 
Content of .gitlab-ci.yml file:-
```bash
variables:
  GIT_DEPTH: "1"
image: cityscience/conda-build3:4.2.12-0.1

build_job:
  script:
    - chmod +x run_ci
    - source run_ci

```
I founded out the error is due to missing ca-certificates package. So, I ran these commands 
```bash
conda config --add channels conda-forge
conda search ca-certificates
```
and then tried downloaded the latest ca-certificate package using this command:-
```bash
conda install -c conda-forge ca-certificates=2022.9.24
```
then the follwing error occured and said to post it here. 
```
|##################################################################################| Time: 0:00:00   5.19 MB/s
conda-22.9.0-p 100% |##################################################################################| Time: 0:00:01 857.45 kB/s
conda-build-3. 100% |##################################################################################| Time: 0:00:00  12.20 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 3.0.19
         python version : 3.5.4.final.0
       requests version : 2.14.2
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.14.2 CPython/3.5.4 Linux/6.5.11-linuxkit debian/8.5 glibc/2.19
                UID:GID : 0:0



$ /opt/conda/bin/conda install -c conda-forge ca-certificates=2022.9.24




    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 403, in __get__
        val = instance.__dict__[self.name]
    KeyError: 'entry_points'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/opt/conda/lib/python3.5/site-packages/conda/core/link.py", line 256, in execute
        self.verify()
      File "/opt/conda/lib/python3.5/site-packages/conda/core/link.py", line 239, in verify
        self.prepare()
      File "/opt/conda/lib/python3.5/site-packages/conda/core/link.py", line 170, in prepare
        concatv(unlink_actions, link_actions))
      File "/opt/conda/lib/python3.5/site-packages/conda/core/link.py", line 169, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "/opt/conda/lib/python3.5/site-packages/conda/core/link.py", line 166, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/link.py", line 395, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "/opt/conda/lib/python3.5/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "/opt/conda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set
```

### Conda Info

```shell
root@49da2a33afc7:/home/commercial-detection# conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 3.0.19
         python version : 3.5.4.final.0
       requests version : 2.14.2
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.14.2 CPython/3.5.4 Linux/6.5.11-linuxkit debian/8.5 glibc/2.19
                UID:GID : 0:0
```

### Conda Config

```shell
root@49da2a33afc7:/home/commercial-detection# conda config --show-sources
==> /root/.condarc <==
channels:
  - conda-forge
  - defaults

==> envvars <==
ssl_verify: False
```

### Conda list

```shell
root@49da2a33afc7:/home/commercial-detection# conda list --show-channel-urls

# packages in environment at /opt/conda:
#
asn1crypto                0.22.0                   py35_0    defaults
beautifulsoup4            4.6.0                    py35_0    defaults
certifi                   2016.2.28                py35_0    defaults
cffi                      1.10.0                   py35_0    defaults
chardet                   3.0.4                    py35_0    defaults
conda                     4.3.9                    py35_0    defaults
conda-build               3.0.19           py35he3ba529_0    defaults
conda-env                 2.6.0                         0    defaults
conda-verify              2.0.0                    py35_0    defaults
cryptography              1.8.1                    py35_0    defaults
filelock                  2.0.7                    py35_0    defaults
glob2                     0.5                      py35_0    defaults
idna                      2.6                      py35_0    defaults
jinja2                    2.9.6                    py35_0    defaults
libffi                    3.2.1                         1    defaults
markupsafe                1.0                      py35_0    defaults
openssl                   1.0.2l                        0    defaults
packaging                 16.8                     py35_0    defaults
patchelf                  0.9                           0    defaults
pip                       9.0.1                    py35_1    defaults
pkginfo                   1.4.1                    py35_0    defaults
pyasn1                    0.2.3                    py35_0    defaults
pycosat                   0.6.2                    py35_0    defaults
pycparser                 2.18                     py35_0    defaults
pycrypto                  2.6.1                    py35_6    defaults
pyopenssl                 17.0.0                   py35_0    defaults
pyparsing                 2.2.0                    py35_0    defaults
python                    3.5.4                         0    defaults
pyyaml                    3.12                     py35_0    defaults
readline                  6.2                           2    defaults
requests                  2.14.2                   py35_0    defaults
ruamel_yaml               0.11.14                  py35_1    defaults
setuptools                36.4.0                   py35_1    defaults
six                       1.10.0                   py35_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py35_0    defaults
xz                        5.2.3                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.11                        0    defaults
```

### Additional Context

Please help me in resolving this error.

**Comment by AryanNanda17** [comment]
Please help me in figuring out what to do. 
Thanks
