### ISSUE TITLE
AttributeError: 'EnvironmentFileNotFound' object has no attribute 'message'

### ISSUE THREAD

**Issue by Locky1138** [conda/conda#1401]
> conda env create -n basic-site
--name is deprecated. Use the following command instead:
    conda env create basic-site
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda_env/env.py", line 60, in from_file
    raise exceptions.EnvironmentFileNotFound(filename)
conda_env.exceptions.EnvironmentFileNotFound: environment.yml file not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/self/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda_env/cli/main.py", line 65, in main
    return args_func(args, parser)
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda_env/cli/main_create.py", line 76, in execute
    directory=os.getcwd())
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda_env/specs/__init__.py", line 17, in detect
    if spec.can_handle():
  File "/home/self/miniconda3/lib/python3.4/site-packages/conda_env/specs/yaml_file.py", line 17, in can_handle
    self.msg = e.message
AttributeError: 'EnvironmentFileNotFound' object has no attribute 'message'

> conda info
Current conda install:

             platform : linux-64
        conda version : 3.14.0
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/self/miniconda3  (writable)
  default environment : /home/self/miniconda3/envs/fabric
     envs directories : /home/self/miniconda3/envs
        package cache : /home/self/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
@malev

**Comment by soapy1** [comment]
conda env is now part of conda. If this is still an issue, please use conda instead `conda update conda && conda create -n basic-site python`.
