### ISSUE TITLE
AssertionError: qt-4.8.6-0.tar.bz2

### ISSUE THREAD

**Issue by piercebarney** [conda/conda#1402]
Issue occurred when running conda update anaconda.

Traceback (most recent call last):
  File "/Users/piercebarney/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 114, in main
    args.func(args, p)
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 63, in execute
    actions = plan.install_actions(prefix, index, args.pkg_names)
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/plan.py", line 195, in install_actions
    for fn in r.solve(specs, [d + '.tar.bz2' for d in linked]):
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 350, in solve
    return self.explicit(specs) or self.solve2(specs, features)
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 248, in solve2
    solutions = min_sat(clauses)
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 113, in min_sat
    for sol in islice(pycosat.itersolve(clauses), max_n):
  File "/Users/piercebarney/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 204, in gen_clauses
    assert len(clause) > 1, fn1
AssertionError: qt-4.8.6-0.tar.bz2

**Comment by piercebarney** [comment]
Problem solved by running conda update conda first.
