### ISSUE TITLE
Updating spyder an unexpected error has occurred

### ISSUE THREAD

**Issue by equihuam** [conda/conda#1403]
Traceback (most recent call last):

```
File "C:\Users\Miguel\Anaconda\Scripts\conda-script.py", line 4, in <module>sys.exit(main())
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main args_func(args, p)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func args.func(args, p)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
return func(args, parser)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
install.install(args, parser, 'install')
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
plan.execute_actions(actions, index, verbose=not args.quiet)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\plan.py", line 527, in execute_actions
inst.execute_instructions(plan, index, verbose)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions cmd(state, arg)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
install.unlink(state['prefix'], arg)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\install.py", line 687, in unlinkTraceback (most recent call last):
File "C:\Users\Miguel\Anaconda\Scripts\conda-script.py", line 4, in <module> sys.exit(main())
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main args_func(args, p)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
args.func(args, p)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
return func(args, parser)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
install.install(args, parser, 'install')
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
plan.execute_actions(actions, index, verbose=not args.quiet)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\plan.py", line 527, inexecute_actions
inst.execute_instructions(plan, index, verbose)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions cmd(state, arg)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
install.unlink(state['prefix'], arg)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\install.py", line 687, in unlink move_to_trash(prefix, f)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\install.py", line 542, in move_to_trash
log.debug("Could not move %s to %s (%s)" % (f, trash_dir, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 59: ordinal
not in range(128) move_to_trash(prefix, f)
File "C:\Users\Miguel\Anaconda\lib\site-packages\conda\install.py", line 542, in move_to_trash
log.debug("Could not move %s to %s (%s)" % (f, trash_dir, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 59: ordinal
 not in range(128)
```

**Comment by ccordoba12** [comment]
@asmeurer, perhaps you'd like to take a look at this one.

**Comment by asmeurer** [comment]
The offending character is á. Is that present in your username or something?

**Comment by equihuam** [comment]
Well, I have some folder names in spanish so the diacriticals!!!  In fact I often have problems of this kind with python and R.  Any way.  I have remove and reinstall Anaconda python including spyder and I am fine again!!!!!  The issue was too cryptic to me!!!!!  I was trying to play with <PyQt4> and then my problems started until it was impossible to  run!!!!! Have no Idea about the details of what happened but uninstalled PyQt4 and Spyder was refusing to run without it.  I tryed to update/repair it with conda an the above report was produced!!!!
So,.... I am fine again with Spyder and thus closing this issue!!!!!

**Comment by asmeurer** [comment]
If you install Python 3 (Anaconda3) you will see these issues much less.
