### ISSUE TITLE
Conda error updating app ipython-notebook

### ISSUE THREAD

**Issue by alexnomadic** [conda/conda#1404]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 671, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '//anaconda/conda-meta/decorator-3.4.0-py27_0.json'

ipython-notebook updated.

Close

**Comment by ilanschnell** [comment]
I guess you mean "Conda error" and not "Honda error" :-)

Did you do anything special with the decorator package?

**Comment by alexnomadic** [comment]
Just used anaconda update GUI...

**Comment by soapy1** [comment]
@alexnomadic is this still an issue for you?
