### ISSUE TITLE
conda update --all fails to install r package and deletes anaconda/bin/conda

### ISSUE THREAD

**Issue by jona-sassenhagen** [conda/conda#1408]
```
$conda update --all
Write failed: Broken pipe
Fetching package metadata: ......
Solving package specifications: ...............
Package plan for installation in environment /home/FB/fb05/sassenha/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libxml2-2.9.2              |                0         4.2 MB
    r-base-3.2.0               |                0        20.5 MB
    conda-3.14.1               |           py34_0         173 KB
    conda-build-1.14.1         |           py34_0         196 KB
    seaborn-0.6.0              |       np19py34_0         258 KB
    spyder-2.3.5.2             |           py34_0         2.7 MB
    spyder-app-2.3.5.2         |           py34_0           7 KB
    r-3.2.0                    |                0           2 KB
    r-boot-1.3_16              |         r3.2.0_0         572 KB
    r-cluster-2.0.1            |         r3.2.0_0         459 KB
    r-codetools-0.2_11         |         r3.2.0_0          45 KB
    r-foreign-0.8_63           |         r3.2.0_0         219 KB
    r-kernsmooth-2.23_14       |         r3.2.0_0          84 KB
    r-lattice-0.20_31          |         r3.2.0_0         697 KB
    r-mass-7.3_40              |         r3.2.0_0         1.0 MB
    r-nnet-7.3_9               |         r3.2.0_0          96 KB
    r-rpart-4.1_9              |         r3.2.0_0         857 KB
    r-spatial-7.3_9            |         r3.2.0_0         122 KB
    r-survival-2.38_2          |         r3.2.0_0         4.4 MB
    r-class-7.3_13             |         r3.2.0_0          82 KB
    r-matrix-1.2_1             |         r3.2.0_1         3.1 MB
    r-nlme-3.1_121             |         r3.2.0_0         2.0 MB
    r-mgcv-1.8_6               |         r3.2.0_1         1.7 MB
    r-recommended-3.2.0        |         r3.2.0_0          721 B
    ------------------------------------------------------------
                                           Total:        43.4 MB

The following packages will be UPDATED:

    conda:         3.14.0-py34_0    --> 3.14.1-py34_0
    conda-build:   1.14.0-py34_0    --> 1.14.1-py34_0
    libxml2:       2.9.0-0          --> 2.9.2-0
    r:             3.1.3-0          --> 3.2.0-0
    r-base:        3.1.3-2          --> 3.2.0-0
    r-boot:        1.3_16-r3.1.3_0  --> 1.3_16-r3.2.0_0
    r-class:       7.3_12-r3.1.3_0  --> 7.3_13-r3.2.0_0
    r-cluster:     1.15.3-0         --> 2.0.1-r3.2.0_0
    r-codetools:   0.2_11-r3.1.3_0  --> 0.2_11-r3.2.0_0
    r-foreign:     0.8_63-r3.1.3_0  --> 0.8_63-r3.2.0_0
    r-kernsmooth:  2.23_14-r3.1.3_0 --> 2.23_14-r3.2.0_0
    r-lattice:     0.20_31-r3.1.3_0 --> 0.20_31-r3.2.0_0
    r-mass:        7.3.37-0         --> 7.3_40-r3.2.0_0
    r-matrix:      1.2_1-r3.1.3_0   --> 1.2_1-r3.2.0_1
    r-mgcv:        1.8_6-r3.1.3_0   --> 1.8_6-r3.2.0_1
    r-nlme:        3.1_120-r3.1.3_0 --> 3.1_121-r3.2.0_0
    r-nnet:        7.3_9-r3.1.3_0   --> 7.3_9-r3.2.0_0
    r-recommended: 3.1.3-0          --> 3.2.0-r3.2.0_0
    r-rpart:       4.1_9-r3.1.3_0   --> 4.1_9-r3.2.0_0
    r-spatial:     7.3_9-r3.1.3_0   --> 7.3_9-r3.2.0_0
    r-survival:    2.38_2-r3.1.3_0  --> 2.38_2-r3.2.0_0
    seaborn:       0.5.1-np19py34_0 --> 0.6.0-np19py34_0
    spyder:        2.3.4-py34_1     --> 2.3.5.2-py34_0
    spyder-app:    2.3.4-py34_0     --> 2.3.5.2-py34_0

Proceed ([y]/n)? y

Fetching packages ...
libxml2-2.9.2- 100% |###################################################| Time: 0:00:02   2.12 MB/s
r-base-3.2.0-0 100% |###################################################| Time: 0:00:13   1.58 MB/s
conda-3.14.1-p 100% |###################################################| Time: 0:00:01 111.91 kB/s
conda-build-1. 100% |###################################################| Time: 0:00:00 371.58 kB/s
seaborn-0.6.0- 100% |###################################################| Time: 0:00:00 361.40 kB/s
spyder-2.3.5.2 100% |###################################################| Time: 0:00:02 953.75 kB/s
spyder-app-2.3 100% |###################################################| Time: 0:00:00   1.62 MB/s
r-3.2.0-0.tar. 100% |###################################################| Time: 0:00:00 444.68 kB/s
r-boot-1.3_16- 100% |###################################################| Time: 0:00:01 509.70 kB/s
r-cluster-2.0. 100% |###################################################| Time: 0:00:01 409.06 kB/s
r-codetools-0. 100% |###################################################| Time: 0:00:00 214.86 kB/s
r-foreign-0.8_ 100% |###################################################| Time: 0:00:00 430.62 kB/s
r-kernsmooth-2 100% |###################################################| Time: 0:00:00 276.20 kB/s
r-lattice-0.20 100% |###################################################| Time: 0:00:02 282.89 kB/s
r-mass-7.3_40- 100% |###################################################| Time: 0:00:02 357.25 kB/s
r-nnet-7.3_9-r 100% |###################################################| Time: 0:00:00 152.68 kB/s
r-rpart-4.1_9- 100% |###################################################| Time: 0:00:01 780.99 kB/s
r-spatial-7.3_ 100% |###################################################| Time: 0:00:00 308.42 kB/s
r-survival-2.3 100% |###################################################| Time: 0:00:07 595.81 kB/s
r-class-7.3_13 100% |###################################################| Time: 0:00:00 269.57 kB/s
r-matrix-1.2_1 100% |###################################################| Time: 0:00:01   1.73 MB/s
r-nlme-3.1_121 100% |###################################################| Time: 0:00:01   1.36 MB/s
r-mgcv-1.8_6-r 100% |###################################################| Time: 0:00:02 844.51 kB/s
r-recommended- 100% |###################################################| Time: 0:00:00 174.95 kB/s
Extracting packages ...
[      COMPLETE      ]|#####################################################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the##                                             |  48%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/FB/fb05/sassenha/anaconda3/bin/conda", line 5, in <module>
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in main
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/cli/common.py", line 612, in inner
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/cli/main_update.py", line 39, in execute
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 413, in install
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 527, in execute_actions
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
  File "/home/FB/fb05/sassenha/anaconda3/lib/python3.4/site-packages/conda/install.py", line 671, in unlink
FileNotFoundError: [Errno 2] No such file or directory: '/home/FB/fb05/sassenha/anaconda3/conda-meta/r-mass-7.3.37-0.json'
synapse:~
$conda info
-bash: /home/FB/fb05/sassenha/anaconda3/bin/conda: No such file or directory
synapse:~
$
```

**Comment by asmeurer** [comment]
Since conda was broken, I think your only solution is to reinstall Anaconda unfortunately, unless you want to attempt of fix it.
