### ISSUE TITLE
conda install numpy fails for python 3

### ISSUE THREAD

**Issue by nathanathan** [conda/conda#1409]
```
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/ubuntu/miniconda3/envs/py3:

The following NEW packages will be INSTALLED:

    numpy:      1.9.2-py34_0 
    setuptools: 17.1.1-py34_0

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                    |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/py3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 141, in execute_instructions
    cmd(state, arg)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/install.py", line 545, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/install.py", line 254, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/miniconda3/envs/py3/lib/python3.4/site-packages/numpy/distutils/site.cfg'
```

**Comment by asmeurer** [comment]
Try `conda install -f numpy` and see if that fixes it for you.

**Comment by nathanathan** [comment]
It did not (see the error below), however I am able to install it when I switch to python 2.
```
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /home/ubuntu/miniconda3/envs/py3:

The following NEW packages will be INSTALLED:

    numpy: 1.9.2-py34_0

Proceed ([y]/n)? y

[      COMPLETE      ]|##############################################################################################################################################################################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                                                                                                        |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/py3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 141, in execute_instructions
    cmd(state, arg)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/install.py", line 545, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/home/ubuntu/miniconda3/lib/python3.4/site-packages/conda/install.py", line 254, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/miniconda3/envs/py3/lib/python3.4/site-packages/numpy/distutils/site.cfg'
```

**Comment by soapy1** [comment]
@nathanathan is this still a problem for you?
