### ISSUE TITLE
ProxyError after updating to 24.7.1

### ISSUE THREAD

**Issue by HarryFuentes** [conda/conda#14101]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

After I've updated conda from version 23.7.4 to 24.7.1 I get a ProxyError when installing packages or creating new environments. I've configured the condarc file and set the proxy servers of my corporation with username and password. It worked with version 23.7.1. Now I receive this error, although I haven't changed anything:

 ```
(base) C:\>conda create --name test 

Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): \ Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/msys2/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/msys2/win-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/noarch/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/win-64/repodata.json.zst

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/main/win-64/repodata.json.zst

/ Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/msys2/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/msys2/noarch/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/main/win-64/repodata.json.zst

Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/win-64/repodata.json.zst

- Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/r/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/main/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/win-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/msys2/win-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/msys2/noarch/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/r/win-64/repodata.json.zst

Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /pkgs/main/win-64/repodata.json.zst

failed

ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings. 
```

### Conda Info

```shell
active environment : base
    active env location : C:\Users\user\AppData\Local\anaconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 24.7.1
    conda-build version : 24.5.1
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.7.1=0
                          __win=0=0
       base environment : C:\Users\user\AppData\Local\anaconda3  (writable)
      conda av data dir : C:\Users\user\AppData\Local\anaconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\AppData\Local\anaconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\AppData\Local\anaconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.10.14 Windows/10 Windows/10.0.19045 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
==> C:\Users\==> C:\Users\user\.condarc <==
ssl_verify: False
proxy_servers:
  http: http://xxxx:xxxx@corp.com:8080
  https: http://xxxx:xxxx@corp.com:8080
channels:
  - conda-forge
  - defaults
show_channel_urls: True

==> envvars <==
allow_softlinks: False
```

### Conda list

```shell
# Name                    Version                   Build  Channel
anaconda-client           1.11.2          py310haa95532_0    defaults
anaconda-navigator        2.4.0           py310haa95532_0    defaults
anaconda-project          0.11.1          py310haa95532_0    defaults
archspec                  0.2.3              pyhd8ed1ab_0    conda-forge
attrs                     23.2.0             pyh71513ae_0    conda-forge
backports                 1.0                pyhd8ed1ab_4    conda-forge
backports.functools_lru_cache 2.0.0              pyhd8ed1ab_0    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       pyhd8ed1ab_1003    conda-forge
beautifulsoup4            4.12.3             pyha770c72_0    conda-forge
boltons                   24.0.0             pyhd8ed1ab_0    conda-forge
brotli-python             1.1.0           py310h00ffb61_1    conda-forge
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.7.4             h56e8100_0    conda-forge
certifi                   2024.7.4           pyhd8ed1ab_0    conda-forge
cffi                      1.16.0          py310h8d17308_0    conda-forge
chardet                   5.2.0           py310h5588dad_1    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           win_pyh7428d3b_0    conda-forge
clyent                    1.2.2              pyhd8ed1ab_2    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
conda                     24.7.1          py310h5588dad_0    conda-forge
conda-build               24.5.1          py310h5588dad_0    conda-forge
conda-content-trust       0.1.3           py310haa95532_0    defaults
conda-index               0.5.0              pyhd8ed1ab_0    conda-forge
conda-libmamba-solver     24.7.0             pyhd8ed1ab_0    conda-forge
conda-pack                0.6.0              pyhd3eb1b0_0    defaults
conda-package-handling    2.3.0              pyh7900ff3_0    conda-forge
conda-package-streaming   0.10.0             pyhd8ed1ab_0    conda-forge
conda-repo-cli            1.0.88          py310haa95532_0    defaults
conda-token               0.4.0              pyhd3eb1b0_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         4    defaults
cryptography              43.0.0          py310h25a5809_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distro                    1.9.0              pyhd8ed1ab_0    conda-forge
filelock                  3.15.4             pyhd8ed1ab_0    conda-forge
fmt                       10.2.1               h181d51b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
frozendict                2.4.4           py310ha8f682b_0    conda-forge
future                    1.0.0              pyhd8ed1ab_0    conda-forge
glib                      2.80.3               h7025463_1    conda-forge
glib-tools                2.80.3               h4394cf3_1    conda-forge
gst-plugins-base          1.24.5               hb0a98b8_0    conda-forge
gstreamer                 1.24.5               h5006eae_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
icu                       73.2                 h63175ca_0    conda-forge
idna                      3.7                pyhd8ed1ab_0    conda-forge
importlib_resources       6.4.0              pyhd8ed1ab_0    conda-forge
jinja2                    3.1.4              pyhd8ed1ab_0    conda-forge
jsonpatch                 1.33               pyhd8ed1ab_0    conda-forge
jsonpointer               3.0.0           py310h5588dad_0    conda-forge
jsonschema                4.23.0             pyhd8ed1ab_0    conda-forge
jsonschema-specifications 2023.12.1          pyhd8ed1ab_0    conda-forge
jupyter_core              5.7.2           py310h5588dad_0    conda-forge
krb5                      1.21.3               hdf4eb48_0    conda-forge
lcms2                     2.16                 h67d730c_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libarchive                3.7.4                haf234dc_0    conda-forge
libclang13                18.1.8          default_ha5278ca_1    conda-forge
libcurl                   8.9.0                h18fefc2_0    conda-forge
libdeflate                1.20                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.80.3               h7025463_1    conda-forge
libiconv                  1.17                 hcfcfb64_2    conda-forge
libintl                   0.22.5               h5728263_2    conda-forge
libintl-devel             0.22.5               h5728263_2    conda-forge
libjpeg-turbo             3.0.0                hcfcfb64_1    conda-forge
liblief                   0.14.1               he0c23c2_1    conda-forge
libmamba                  1.5.8                h3f09ed1_0    conda-forge
libmambapy                1.5.8           py310h04f2035_0    conda-forge
libogg                    1.3.5                h2466b09_0    conda-forge
libpng                    1.6.43               h19919ed_0    conda-forge
libsolv                   0.7.30               hbb528cf_0    conda-forge
libsqlite                 3.46.0               h2466b09_0    conda-forge
libssh2                   1.11.0               h7dfc565_0    conda-forge
libtiff                   4.6.0                hddb2be6_3    conda-forge
libvorbis                 1.3.7                h0e60522_0    conda-forge
libwebp-base              1.4.0                hcfcfb64_0    conda-forge
libxcb                    1.16                 hcd874cb_0    conda-forge
libxml2                   2.12.7               h0f24e4e_4    conda-forge
libzlib                   1.3.1                h2466b09_1    conda-forge
lz4-c                     1.9.4                hcfcfb64_0    conda-forge
lzo                       2.10              hcfcfb64_1001    conda-forge
m2-msys2-runtime          2.5.0.17080.65c939c               3    conda-forge
m2-patch                  2.7.5                         2    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.5           py310h8d17308_0    conda-forge
menuinst                  2.1.1           py310h9e98ed7_0    conda-forge
more-itertools            10.3.0             pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
navigator-updater         0.5.1           py310haa95532_0    defaults
nbformat                  5.10.4             pyhd8ed1ab_0    conda-forge
openjpeg                  2.5.2                h3d672ee_0    conda-forge
openssl                   3.3.1                h2466b09_2    conda-forge
packaging                 24.1               pyhd8ed1ab_0    conda-forge
pcre2                     10.44                h3d7b363_0    conda-forge
pillow                    10.4.0          py310h3e38d90_0    conda-forge
pip                       22.3.1          py310haa95532_0    defaults
pkginfo                   1.11.1             pyhd8ed1ab_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
platformdirs              4.2.2              pyhd8ed1ab_0    conda-forge
pluggy                    1.5.0              pyhd8ed1ab_0    conda-forge
ply                       3.11               pyhd8ed1ab_2    conda-forge
powershell_shortcut       0.0.1                         3    defaults
psutil                    6.0.0           py310ha8f682b_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
py-lief                   0.14.1          py310h9e98ed7_1    conda-forge
pybind11-abi              4                    hd8ed1ab_3    conda-forge
pycosat                   0.6.6           py310h8d17308_0    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyjwt                     2.8.0              pyhd8ed1ab_1    conda-forge
pyqt                      5.15.9          py310h1fd54f2_5    conda-forge
pyqt5-sip                 12.12.2         py310h00ffb61_5    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.14         h4de0772_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.20.0             pyhd8ed1ab_0    conda-forge
python-libarchive-c       5.1             py310h5588dad_0    conda-forge
python_abi                3.10                    4_cp310    conda-forge
pytz                      2024.1             pyhd8ed1ab_0    conda-forge
pywin32                   306             py310h00ffb61_2    conda-forge
pyyaml                    6.0.1           py310h8d17308_1    conda-forge
qt-main                   5.15.8              h06adc49_23    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
referencing               0.35.1             pyhd8ed1ab_0    conda-forge
reproc                    14.2.4.post0         hcfcfb64_1    conda-forge
reproc-cpp                14.2.4.post0         h63175ca_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
requests-toolbelt         1.0.0              pyhd8ed1ab_0    conda-forge
ripgrep                   14.1.0               h7f3b576_0    conda-forge
rpds-py                   0.19.1          py310hc226416_0    conda-forge
ruamel.yaml               0.18.6          py310h8d17308_0    conda-forge
ruamel.yaml.clib          0.2.8           py310h8d17308_0    conda-forge
ruamel_yaml               0.15.80         py310h8d17308_1009    conda-forge
setuptools                65.6.3          py310haa95532_0    defaults
sip                       6.7.12          py310h00ffb61_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
soupsieve                 2.5                pyhd8ed1ab_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tornado                   6.4.1           py310ha8f682b_0    conda-forge
tqdm                      4.66.4             pyhd8ed1ab_0    conda-forge
traitlets                 5.14.3             pyhd8ed1ab_0    conda-forge
truststore                0.8.0              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
ujson                     5.10.0          py310h9e98ed7_0    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
vc                        14.3                h8a93ad2_20    conda-forge
vc14_runtime              14.40.33810         ha82c5b3_20    conda-forge
vs2015_runtime            14.40.33810         h3bf8584_20    conda-forge
wheel                     0.38.4          py310haa95532_0    defaults
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
wincertstore              0.2             pyhd8ed1ab_1009    conda-forge
xorg-libxau               1.0.11               hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.8.0                h63175ca_0    conda-forge
zipp                      3.19.2             pyhd8ed1ab_0    conda-forge
zstandard                 0.23.0          py310he5e10e1_0    conda-forge
zstd                      1.5.6                h0ea2cb4_0    conda-forge
```

**Comment by travishathaway** [comment]
@HarryFuentes,

Thanks for filing this. I was able to test this myself using the latest version of conda and was not able to recreate the error you are seeing.

What I did discover is that when your credentials are incorrect, the error you are seeing is what would appear. Is there another way for you to verify your credentials so we can be 100% certain this is being caused by a problem with conda?

**Comment by HarryFuentes** [comment]
@travishathaway 

Thank you for taking care of the problem.

I have checked the proxy server again and username and password are correct. I don't know how else I can check my credentials.

Pip, on the other hand, works in the conda environment. Does that give you a hint?

**Comment by travishathaway** [comment]
@HarryFuentes,

Yes, that helps. Unfortunately, I'm still able to do much until I'm able to recreate this myself.

One thing that could be helpful would be to share debugging logs with us. You can do that by adding the `-v -v -v` to any command. For example:

```
conda create --name test python -v -v -v
```

We would just need to inspect the output of that command with the proxy configured.

**Comment by HarryFuentes** [comment]
@travishathaway 

this is the output:

```
(base) C:\>conda create --name test python -v -v -v
DEBUG conda.gateways.logging:set_log_level(235): log_level set to 10
DEBUG conda.conda_libmamba_solver.solver:__init__(106): Ignoring repodata_fn='current_repodata.json', defaulting to repodata.json
INFO conda.conda_libmamba_solver.solver:_log_info(352): conda version: 24.7.1
INFO conda.conda_libmamba_solver.solver:_log_info(353): conda-libmamba-solver version: 24.7.0
INFO conda.conda_libmamba_solver.solver:_log_info(354): libmambapy version: 1.5.8
INFO conda.conda_libmamba_solver.solver:_log_info(355): Target prefix: 'C:\\Users\\user\\AppData\\Local\\anaconda3\\envs\\test'
INFO conda.conda_libmamba_solver.solver:_log_info(356): Command: ['C:\\Users\\user\\AppData\\Local\\anaconda3\\Scripts\\conda-script.py', 'create', '--name', 'test', 'python', '-v', '-v', '-v']
Channels:
 - conda-forge
 - defaults
Platform: win-64
Collecting package metadata (repodata.json): ...working... info     libmamba Reading cache files 'C:\Users\user\AppData\Local\Temp\tmp_w3yej_4.json.*' for repo index 'installed'
info     libmamba Reading repodata.json file "C:\\Users\\user\\AppData\\Local\\Temp\\tmp_w3yej_4.json" for repo installed
DEBUG conda.conda_libmamba_solver.index:_fetch_channel(247): Fetching https://conda.anaconda.org/conda-forge/win-64 with SubdirData.repo_fetch
DEBUG conda.core.package_cache_data:_check_writable(332): package cache directory 'C:\Users\user\AppData\Local\anaconda3\pkgs' writable: True
DEBUG conda.gateways.repodata:fetch_latest(837): Local cache timed out for https://conda.anaconda.org/conda-forge/win-64/repodata.json at C:\Users\user\AppData\Local\anaconda3\pkgs\cache\5afe41e9.json
DEBUG conda.gateways.repodata.jlap.interface:__init__(42): Using ZstdRepoInterface
DEBUG urllib3.connectionpool:_new_conn(1051): Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG urllib3.util.retry:increment(521): Incremented Retry for (url='/conda-forge/win-64/repodata.json.zst'): Retry(total=2, connect=None, read=None, redirect=None, status=None)
WARNING urllib3.connectionpool:urlopen(870): Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/win-64/repodata.json.zst
DEBUG urllib3.connectionpool:_new_conn(1051): Starting new HTTPS connection (2): conda.anaconda.org:443
DEBUG urllib3.util.retry:increment(521): Incremented Retry for (url='/conda-forge/win-64/repodata.json.zst'): Retry(total=1, connect=None, read=None, redirect=None, status=None)
WARNING urllib3.connectionpool:urlopen(870): Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/win-64/repodata.json.zst
DEBUG urllib3.connectionpool:_new_conn(1051): Starting new HTTPS connection (3): conda.anaconda.org:443
DEBUG urllib3.util.retry:increment(521): Incremented Retry for (url='/conda-forge/win-64/repodata.json.zst'): Retry(total=0, connect=None, read=None, redirect=None, status=None)
WARNING urllib3.connectionpool:urlopen(870): Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'OSError('Tunnel connection failed: 407 authenticationrequired')': /conda-forge/win-64/repodata.json.zst
DEBUG urllib3.connectionpool:_new_conn(1051): Starting new HTTPS connection (4): conda.anaconda.org:443
failed
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 775, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 1044, in _prepare_proxy
    conn.connect()
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connection.py", line 632, in connect
    self._tunnel()  # type: ignore[attr-defined]
  File "C:\Users\user\AppData\Local\anaconda3\lib\http\client.py", line 925, in _tunnel
    raise OSError(f"Tunnel connection failed: {code} {message.strip()}")
OSError: Tunnel connection failed: 407 authenticationrequired

The above exception was the direct cause of the following exception:

urllib3.exceptions.ProxyError: ('Unable to connect to proxy', OSError('Tunnel connection failed: 407 authenticationrequired'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 873, in urlopen
    return self.urlopen(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 843, in urlopen
    retries = retries.increment(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\urllib3\util\retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/repodata.json.zst (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 407 authenticationrequired')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 203, in conda_http_errors
    yield
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\jlap\interface.py", line 87, in repodata_parsed
    repodata_json_or_none = fetch.request_url_jlap_state(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\jlap\fetch.py", line 309, in request_url_jlap_state
    response = download_and_hash(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\jlap\fetch.py", line 243, in download_and_hash
    response = session.get(url, stream=True, timeout=timeout, headers=headers)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\requests\adapters.py", line 694, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/repodata.json.zst (Caused by ProxyError('Unable to connect to proxy', OSError('Tunnel connection failed: 407 authenticationrequired')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\exception_handler.py", line 18, in __call__
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in main_subshell
    exit_code = do_call(args, parser)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 200, in do_call
    result = getattr(module, func_name)(args, parser)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\notices\core.py", line 132, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\cli\main_create.py", line 148, in execute
    return install(args, parser, "create")
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\cli\install.py", line 383, in install
    unlink_link_transaction = solver.solve_for_transaction(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\core\solve.py", line 152, in solve_for_transaction
    unlink_precs, link_precs = self.solve_for_diff(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\core\solve.py", line 221, in solve_for_diff
    final_precs = self.solve_final_state(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda_libmamba_solver\solver.py", line 207, in solve_final_state
    index = IndexHelper(
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda_libmamba_solver\index.py", line 136, in __init__
    self._index = self._load_channels()
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda_libmamba_solver\index.py", line 334, in _load_channels
    jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda_libmamba_solver\index.py", line 334, in <dictcomp>
    jsons = {url: str(path) for (url, path) in executor.map(self._fetch_channel, urls)}
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\common\io.py", line 591, in map
    yield func(thing)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda_libmamba_solver\index.py", line 254, in _fetch_channel
    json_path, _ = subdir_data.repo_fetch.fetch_latest_path()
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 749, in fetch_latest_path
    _, state = self.fetch_latest()
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 847, in fetch_latest
    raw_repodata = repo.repodata_parsed(cache.state)  # type: ignore
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\jlap\interface.py", line 86, in repodata_parsed
    with conda_http_errors(self._url, self._repodata_fn):
  File "C:\Users\user\AppData\Local\anaconda3\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\user\AppData\Local\anaconda3\lib\site-packages\conda\gateways\repodata\__init__.py", line 205, in conda_http_errors
    raise ProxyError()  # see #3962
conda.exceptions.ProxyError: Conda cannot proceed due to an error in your proxy configuration.
Check for typos and other configuration errors in any '.netrc' file in your home directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.
```

**Comment by travishathaway** [comment]
@HarryFuentes,

Unfortunately, there's not much more in those logs that help me determine exactly what is going on. I have made my best effort to recreate your issue but was unable to.

At this point, I will leave this issue open in the hopes that other people stumble upon it if they are also having this problem. If more and more people begin reporting this issue, we will take it seriously and begin looking into it more.

If you have any more information you could share about this particular proxy setup, please do because it will help us debug this further. I am still very curious why this isn't working correctly for you and would like get your issue resolved.

**Comment by WiG96** [comment]
any updates on this, i'm having same issue ?

**Comment by HarryFuentes** [comment]
@WiG96 I had to delete the http_proxy and the https_proxy environment variable in windows.
