### ISSUE TITLE
"conda install opencv" fails on Windows 64-bit (Win 8.1)

### ISSUE THREAD

**Issue by prjemian** [conda/conda#1417]
installation command

	PS C:\Users\Pete> conda install opencv
	Fetching package metadata: ...An unexpected error has occurred, please consider sending the
	following traceback to the conda GitHub issue tracker at:

		https://github.com/conda/conda/issues

	Include the output of the command 'conda info' in your report.

	Traceback (most recent call last):
	  File "D:\Apps\Anaconda\Scripts\conda-script.py", line 4, in <module>
		sys.exit(main())
	  File "D:\Apps\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
		args_func(args, p)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
		args.func(args, p)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
		return func(args, parser)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\cli\main_install.py", line 46, in execute
		install.install(args, parser, 'install')
	  File "D:\Apps\Anaconda\lib\site-packages\conda\cli\install.py", line 255, in install
		offline=args.offline)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\cli\common.py", line 549, in get_index_trap
		return get_index(*args, **kwargs)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
		unknown=unknown)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
		value = self.func(*args, **kw)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\fetch.py", line 250, in fetch_index
		repodatas.append((url, future.result()))
	  File "D:\Apps\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 400, in result
		return self.__get_result()
	  File "D:\Apps\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
		reraise(self._exception, self._traceback)
	  File "D:\Apps\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
		exec('raise exc_type, exc_value, traceback', {}, locals_)
	  File "D:\Apps\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in run
		result = self.fn(*self.args, **self.kwargs)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
		res = f(*args, **kwargs)
	  File "D:\Apps\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
		verify=config.ssl_verify)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\sessions.py", line 477, in get
		return self.request('GET', url, **kwargs)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\sessions.py", line 465, in request
		resp = self.send(prep, **send_kwargs)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\sessions.py", line 573, in send
		r = adapter.send(request, **kwargs)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
		timeout=timeout
	  File "D:\Apps\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
		body=body, headers=headers)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
		self._validate_conn(conn)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
		conn.connect()
	  File "D:\Apps\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 245, in connect
		cert = self.sock.getpeercert()
	  File "D:\Apps\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 234, in getpeercert
		for value in get_subj_alt_name(x509)
	  File "D:\Apps\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 135, in get_subj_alt_na
	me
		asn1Spec=general_names)
	  File "D:\Apps\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
		stGetValueDecoder, self, substrateFun
	  File "D:\Apps\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
		component, head = decodeFun(head, asn1Spec)
	  File "D:\Apps\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
		stGetValueDecoder, self, substrateFun
	  File "D:\Apps\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
		r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
	  File "D:\Apps\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
		idx = self._componentType.getPositionByType(tagSet)
	  File "D:\Apps\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in getPositionByType
		raise error.PyAsn1Error('Type %s not found' % (tagSet,))
	pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found
	PS C:\Users\Pete>

conda information

	PS C:\Users\Pete> conda info
	Current conda install:

				 platform : win-64
			conda version : 3.14.1
	  conda-build version : 1.8.2
		   python version : 2.7.8.final.0
		 requests version : 2.7.0
		 root environment : D:\Apps\Anaconda  (writable)
	  default environment : D:\Apps\Anaconda
		 envs directories : D:\Apps\Anaconda\envs
			package cache : D:\Apps\Anaconda\pkgs
			 channel URLs : https://repo.continuum.io/pkgs/free/win-64/
							https://repo.continuum.io/pkgs/free/noarch/
							https://repo.continuum.io/pkgs/pro/win-64/
							https://repo.continuum.io/pkgs/pro/noarch/
			  config file : None
		is foreign system : False

	PS C:\Users\Pete>

**Comment by asmeurer** [comment]
Try `conda update requests`. See https://github.com/conda/conda/issues/1261.

**Comment by prjemian** [comment]
Tried this:

    PS C:\Users\Pete> conda update requests
    Fetching package metadata: ....
    # All requested packages already installed.
    # packages in environment at D:\Apps\Anaconda:
    #
    requests                  2.7.0                    py27_0

Then tried:

    conda remove ndg-httpsclient
    conda update requests

same result.  Then tried:

	PS C:\Users\Pete> pip uninstall ndg-httpsclient
	DEPRECATION: Uninstalling a distutils installed project (ndg-httpsclient) has been deprecated and will be removed in a f
	uture version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
	Uninstalling ndg-httpsclient-0.3.3:
	  d:\apps\anaconda\lib\site-packages\ndg_httpsclient-0.3.3-py2.7.egg-info
	Proceed (y/n)? y
	  Successfully uninstalled ndg-httpsclient-0.3.3

	PS C:\Users\Pete> conda update requests
	Fetching package metadata: ....
	# All requested packages already installed.
	# packages in environment at D:\Apps\Anaconda:
	#
	requests                  2.7.0                    py27_0

What part of #1261 provides the solution?
