### ISSUE TITLE
KeyError: u'https' when installing certain packages

### ISSUE THREAD

**Issue by kcnwogu** [conda/conda#1418]
Attempted to install the following packages xlwt, xlutils and xlrd but received a KeyError. The outputs are included below.

The output of the conda info:
C:>conda info
Current conda install:

```
         platform : win-32
    conda version : 3.14.1
```

  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\SOFTWARE\MINICONDA  (writable)
  default environment : C:\SOFTWARE\MINICONDA
     envs directories : C:\SOFTWARE\MINICONDA\envs
        package cache : C:\SOFTWARE\MINICONDA\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

The errors we are getting:

C:>conda install xlwt
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\SOFTWARE\MINICONDA:

The following packages will be downloaded:

| package | build |
| --- | --- |
| xlwt-1.0.0 | py27_0         151 KB |

The following NEW packages will be INSTALLED:

```
xlwt: 1.0.0-py27_0
```

Proceed ([y]/n)? y

Fetching packages ...

https proxy username: <username>
Password:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\SOFTWARE\MINICONDA\SCRIPTS\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main.py", line 208, in args_func

```
args.func(args, p)
```

  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\install.py", line 413, in instal
l
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\plan.py", line 527, in execute_actio
ns
    inst.execute_instructions(plan, index, verbose)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\instructions.py", line 148, in execu
te_instructions
    cmd(state, arg)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\instructions.py", line 52, in FETCH_
CMD
    fetch(state['index'], arg)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 285, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 340, in download
    handle_proxy_407(url, session)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 184, in handle_proxy
_407
    session.proxies[scheme], username, passwd)
KeyError: u'https'

C:>conda install xlutils
Fetching package metadata:
https proxy username: <username>
Password:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\SOFTWARE\MINICONDA\SCRIPTS\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main.py", line 208, in args_func

```
args.func(args, p)
```

  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\install.py", line 255, in instal
l
    offline=args.offline)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\common.py", line 549, in get_ind
ex_trap
    return get_index(_args, *_kwargs)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 154, in fetch_repoda
ta
    handle_proxy_407(url, session)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 184, in handle_proxy
_407
    session.proxies[scheme], username, passwd)
KeyError: 'https'

C:>conda install xlrd
Fetching package metadata:
https proxy username: <username>
Password: <password>
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\SOFTWARE\MINICONDA\SCRIPTS\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main.py", line 208, in args_func

```
args.func(args, p)
```

  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\main_install.py", line 46, in ex
ecute
    install.install(args, parser, 'install')
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\install.py", line 255, in instal
l
    offline=args.offline)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\cli\common.py", line 549, in get_ind
ex_trap
    return get_index(_args, *_kwargs)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 154, in fetch_repoda
ta
    handle_proxy_407(url, session)
  File "C:\SOFTWARE\MINICONDA\lib\site-packages\conda\fetch.py", line 184, in handle_proxy
_407
    session.proxies[scheme], username, passwd)
KeyError: 'https'

C:>pip install xlwt
Collecting xlwt
  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broke
n by 'ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Au
thentication Required',))': /simple/xlwt/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broke
n by 'ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Au
thentication Required',))': /simple/xlwt/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broke
n by 'ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Au
thentication Required',))': /simple/xlwt/
Operation cancelled by user

C:>

**Comment by asmeurer** [comment]
I'm guessing you have a proxy set for http but not https. The conda code should handle this better.

**Comment by asmeurer** [comment]
I may have misguessed what is going on. Do you have any proxy settings set, either in condarc, your system settings, or the `HTTPS_PROXY` or `HTTP_PROXY` environment variables?

**Comment by kcnwogu** [comment]
I don't believe it is in the environment variables. It is in the windows registry.

**Comment by asmeurer** [comment]
I think for conda the best we can do is give a better error message. But I think the real issue is either in your proxy configuration or a bug in requests.

**Comment by kcnwogu** [comment]
I occasionally get the following warning:

Fetching package metadata: C:\Continuum\Miniconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarni
ng: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

**Comment by kcnwogu** [comment]
Do you think this might be associate with issue 2061?
https://github.com/kennethreitz/requests/issues/2061

**Comment by soapy1** [comment]
looks a lot like #1423
