### ISSUE TITLE
Automatically activate environment on terminal startup in Ubuntu 22.04

### ISSUE THREAD

**Issue by hasibagen** [conda/conda#14216]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Description: I am trying to configure my Ubuntu 22.04 system to automatically activate the fnirs conda environment upon terminal startup. To achieve this, I modified the .bashrc file as follows:
```

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/root/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/root/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/root/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/root/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

conda activate fnirs

```
However, when I start a new terminal session, I encounter the following error:

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 110, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 228, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 193, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 371, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 461, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 824, in _get_deactivate_scripts
        for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 76, in join
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /root/miniconda3/bin/conda shell.posix activate base`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/root/miniconda3/bin/conda
           CONDA_PREFIX_2=/root/miniconda3/envs/fnirs
           CONDA_PREFIX_3=/root/miniconda3
         CONDA_PYTHON_EXE=/root/miniconda3/bin/python
               CONDA_ROOT=/root/miniconda3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=:/opt/quarto/bin:/root/.vscode-server/cli/servers/Stable-
                          4849ca9bdf9666755eb463db297b69e5385090e3/server/bin/remote-cli:/usr/lo
                          cal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
                          local/games:/snap/bin:/root/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=/usr/lib/ssl/certs/ca-certificates.crt

     active environment : None
            shell level : 4
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=24.7.1=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /root/miniconda3  (writable)
      conda av data dir : /root/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/5.15.0-113-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>



No report sent. To permanently opt-out, use

    $ conda config --set report_errors false


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.12/site-packages/conda/exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/cli/main.py", line 110, in main_sourced
        print(activator.execute(), end="")
              ^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 228, in execute
        return getattr(self, self.command)()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 193, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 371, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 461, in _build_activate_stack
        deactivate_scripts = self._get_deactivate_scripts(old_conda_prefix)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/root/miniconda3/lib/python3.12/site-packages/conda/activate.py", line 824, in _get_deactivate_scripts
        for entry in os.scandir(join(prefix, "etc", "conda", "deactivate.d"))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen posixpath>", line 76, in join
    TypeError: expected str, bytes or os.PathLike object, not NoneType

`$ /root/miniconda3/bin/conda shell.posix activate fnirs`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/root/miniconda3/bin/conda
           CONDA_PREFIX_2=/root/miniconda3/envs/fnirs
           CONDA_PREFIX_3=/root/miniconda3
         CONDA_PYTHON_EXE=/root/miniconda3/bin/python
               CONDA_ROOT=/root/miniconda3
              CONDA_SHLVL=4
           CURL_CA_BUNDLE=<not set>
               LD_PRELOAD=<not set>
                     PATH=:/opt/quarto/bin:/root/.vscode-server/cli/servers/Stable-
                          4849ca9bdf9666755eb463db297b69e5385090e3/server/bin/remote-cli:/usr/lo
                          cal/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/
                          local/games:/snap/bin:/root/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=/usr/lib/ssl/certs/ca-certificates.crt

     active environment : None
            shell level : 4
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=24.7.1=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /root/miniconda3  (writable)
      conda av data dir : /root/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/5.15.0-113-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If you suspect this error is being caused by a malfunctioning plugin,
consider using the --no-plugins option to turn off plugins.

Example: conda --no-plugins install <package>

Alternatively, you can set the CONDA_NO_PLUGINS environment variable on
the command line to run the command without plugins enabled.

Example: CONDA_NO_PLUGINS=true conda install <package>



No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

It seems the error is related to conda's activation process and possibly some issue with the environment or shell level. I'm using Ubuntu 22.04 with Miniconda installed in /root/miniconda3.

Steps to Reproduce:

Modify .bashrc to automatically activate the fnirs environment.
Start a new terminal session.
Expected Behavior: The fnirs environment should be activated automatically upon terminal startup.

Actual Behavior: I get an error message indicating an issue with conda's activation process, particularly with shell level and environment variables.

System Information:

Ubuntu 22.04
Miniconda version: 24.7.1
Python version: 3.12.4
Any insights on how to resolve this issue would be appreciated!

### Conda Info

```shell
active environment : None
            shell level : 4
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.12.4.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=icelake
                          __conda=24.7.1=0
                          __glibc=2.35=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /root/miniconda3  (writable)
      conda av data dir : /root/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.32.3 CPython/3.12.4 Linux/5.15.0-113-generic ubuntu/22.04.4 glibc/2.35 solver/libmamba conda-libmamba-solver/24.7.0 libmambapy/1.5.8 aau/0.4.4 c/. s/. e/.
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
# conda config --show-sources
==> /root/.condarc <==
channels:
  - defaults
custom_channels:
  conda-forge: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  msys2: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  bioconda: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  menpo: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  pytorch-lts: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
  simpleitk: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
default_channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
show_channel_urls: True
```

### Conda list

```shell
conda list --show-channel-urls
# packages in environment at /root/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    https://repo.anaconda.com/pkgs/main
_openmp_mutex             5.1                       1_gnu    https://repo.anaconda.com/pkgs/main
anaconda-anon-usage       0.4.4           py312hfc0e8ea_100    https://repo.anaconda.com/pkgs/main
archspec                  0.2.3              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
boltons                   23.0.0          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
brotli-python             1.0.9           py312h6a678d5_8    https://repo.anaconda.com/pkgs/main
bzip2                     1.0.8                h5eee18b_6    https://repo.anaconda.com/pkgs/main
c-ares                    1.19.1               h5eee18b_0    https://repo.anaconda.com/pkgs/main
ca-certificates           2024.7.2             h06a4308_0    https://repo.anaconda.com/pkgs/main
certifi                   2024.7.4        py312h06a4308_0    https://repo.anaconda.com/pkgs/main
cffi                      1.16.0          py312h5eee18b_1    https://repo.anaconda.com/pkgs/main
charset-normalizer        3.3.2              pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
conda                     24.7.1          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
conda-content-trust       0.2.0           py312h06a4308_1    https://repo.anaconda.com/pkgs/main
conda-libmamba-solver     24.7.0             pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
conda-package-handling    2.3.0           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
conda-package-streaming   0.10.0          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
cryptography              42.0.5          py312hdda0065_1    https://repo.anaconda.com/pkgs/main
distro                    1.9.0           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
expat                     2.6.2                h6a678d5_0    https://repo.anaconda.com/pkgs/main
fmt                       9.1.0                hdb19cb5_1    https://repo.anaconda.com/pkgs/main
frozendict                2.4.2           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
icu                       73.1                 h6a678d5_0    https://repo.anaconda.com/pkgs/main
idna                      3.7             py312h06a4308_0    https://repo.anaconda.com/pkgs/main
jsonpatch                 1.33            py312h06a4308_1    https://repo.anaconda.com/pkgs/main
jsonpointer               2.1                pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
krb5                      1.20.1               h143b758_1    https://repo.anaconda.com/pkgs/main
ld_impl_linux-64          2.38                 h1181459_1    https://repo.anaconda.com/pkgs/main
libarchive                3.6.2                hfab0078_4    https://repo.anaconda.com/pkgs/main
libcurl                   8.7.1                h251f7ec_0    https://repo.anaconda.com/pkgs/main
libedit                   3.1.20230828         h5eee18b_0    https://repo.anaconda.com/pkgs/main
libev                     4.33                 h7f8727e_1    https://repo.anaconda.com/pkgs/main
libffi                    3.4.4                h6a678d5_1    https://repo.anaconda.com/pkgs/main
libgcc-ng                 11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/main
libgomp                   11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/main
libmamba                  1.5.8                hfe524e5_2    https://repo.anaconda.com/pkgs/main
libmambapy                1.5.8           py312h2dafd23_2    https://repo.anaconda.com/pkgs/main
libnghttp2                1.57.0               h2d74bed_0    https://repo.anaconda.com/pkgs/main
libsolv                   0.7.24               he621ea3_1    https://repo.anaconda.com/pkgs/main
libssh2                   1.11.0               h251f7ec_0    https://repo.anaconda.com/pkgs/main
libstdcxx-ng              11.2.0               h1234567_1    https://repo.anaconda.com/pkgs/main
libuuid                   1.41.5               h5eee18b_0    https://repo.anaconda.com/pkgs/main
libxml2                   2.13.1               hfdd30dd_2    https://repo.anaconda.com/pkgs/main
lz4-c                     1.9.4                h6a678d5_1    https://repo.anaconda.com/pkgs/main
menuinst                  2.1.2           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
ncurses                   6.4                  h6a678d5_0    https://repo.anaconda.com/pkgs/main
openssl                   3.0.14               h5eee18b_0    https://repo.anaconda.com/pkgs/main
packaging                 24.1            py312h06a4308_0    https://repo.anaconda.com/pkgs/main
pcre2                     10.42                hebb0a14_1    https://repo.anaconda.com/pkgs/main
pip                       24.2            py312h06a4308_0    https://repo.anaconda.com/pkgs/main
platformdirs              3.10.0          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
pluggy                    1.0.0           py312h06a4308_1    https://repo.anaconda.com/pkgs/main
pybind11-abi              5                    hd3eb1b0_0    https://repo.anaconda.com/pkgs/main
pycosat                   0.6.6           py312h5eee18b_1    https://repo.anaconda.com/pkgs/main
pycparser                 2.21               pyhd3eb1b0_0    https://repo.anaconda.com/pkgs/main
pysocks                   1.7.1           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
python                    3.12.4               h5148396_1    https://repo.anaconda.com/pkgs/main
readline                  8.2                  h5eee18b_0    https://repo.anaconda.com/pkgs/main
reproc                    14.2.4               h6a678d5_2    https://repo.anaconda.com/pkgs/main
reproc-cpp                14.2.4               h6a678d5_2    https://repo.anaconda.com/pkgs/main
requests                  2.32.3          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
ruamel.yaml               0.17.21         py312h5eee18b_0    https://repo.anaconda.com/pkgs/main
setuptools                72.1.0          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
sqlite                    3.45.3               h5eee18b_0    https://repo.anaconda.com/pkgs/main
tk                        8.6.14               h39e8969_0    https://repo.anaconda.com/pkgs/main
tqdm                      4.66.4          py312he106c6f_0    https://repo.anaconda.com/pkgs/main
truststore                0.8.0           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
tzdata                    2024a                h04d1e81_0    https://repo.anaconda.com/pkgs/main
urllib3                   2.2.2           py312h06a4308_0    https://repo.anaconda.com/pkgs/main
wheel                     0.43.0          py312h06a4308_0    https://repo.anaconda.com/pkgs/main
xz                        5.4.6                h5eee18b_1    https://repo.anaconda.com/pkgs/main
yaml-cpp                  0.8.0                h6a678d5_1    https://repo.anaconda.com/pkgs/main
zlib                      1.2.13               h5eee18b_1    https://repo.anaconda.com/pkgs/main
zstandard                 0.22.0          py312h2c38b39_0    https://repo.anaconda.com/pkgs/main
zstd                      1.5.5                hc292b87_2    https://repo.anaconda.com/pkgs/main
(fnirs)
```

**Comment by hasibagen** [comment]
I have seen related posts, but it seems that I did not get any suggestions related to this feature when I directly googled or asked ai. I would like to ask if it has been released?
https://github.com/conda/conda/pull/12618
https://github.com/conda/conda/issues/12823
https://github.com/conda/conda/issues/12600

The method page of this post was unsuccessful. This method did not achieve what I wanted, which is to load a certain environment as soon as the terminal is started.
# set python3 as default
export PATH="~/anaconda/envs/python3/bin:$PATH"

https://stackoverflow.com/questions/28436769/how-to-change-default-anaconda-python-environment

**Comment by travishathaway** [comment]
@hasibagen,

I have a suggestion. Instead of call `conda activate <env-name>`, try this instead:

```bash
eval $(conda shell.<shell> activate <env-name>
```

Where `<shell>` is the shell you are using (e.g. `zsh` or `bash`) and `<env-name>` is the environment you want to activate.

Please let us know if this works.

**Comment by hasibagen** [comment]
#conda activate fnirs
eval "$(conda shell.bash activate fnirs)"

I tried this and it seems to work fine so far, I will update my feedback later.

Thanks for your reply and suggestions.

**Comment by hasibagen** [comment]
> @hasibagen,
> 
> I have a suggestion. Instead of call `conda activate <env-name>`, try this instead:
> 
> ```shell
> eval $(conda shell.<shell> activate <env-name>
> ```
> 
> Where `<shell>` is the shell you are using (e.g. `zsh` or `bash`) and `<env-name>` is the environment you want to activate.
> 
> Please let us know if this works.

#conda activate fnirs
eval "$(conda shell.bash activate fnirs)"

I tried this and it seems to work fine so far, I will update my feedback later.

Thanks for your reply and suggestions.
