### ISSUE TITLE
Error during installation of  panda

### ISSUE THREAD

**Issue by rahmanhpu** [conda/conda#1422]
[rahman@localhost ~]$ conda install panda
Fetching package metadata: 
https proxy username: xxxxxxxxx
Password:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/rahman/sware/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    offline=args.offline)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 549, in get_index_trap
    return get_index(_args, *_kwargs)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 154, in fetch_repodata
    handle_proxy_407(url, session)
  File "/home/rahman/sware/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 184, in handle_proxy_407
    session.proxies[scheme], username, passwd)
KeyError: 'https'

**Comment by soapy1** [comment]
looks a lot like https://github.com/conda/conda/issues/1423
