### ISSUE TITLE
Conda stop working

### ISSUE THREAD

**Issue by geparada** [conda/conda#1423]
Hi,

I just started to use Conda and I could only install numpy, but when I tried to install other packages this error is popping up.

Am I doing something wrong?

Cheers,

:~$ conda install matplotlib
Fetching package metadata:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/nfs/users/nfs_g/gp7/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    offline=args.offline)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 549, in get_index_trap
    return get_index(_args, *_kwargs)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 154, in fetch_repodata
    handle_proxy_407(url, session)
  File "/nfs/users/nfs_g/gp7/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 184, in handle_proxy_407
    session.proxies[scheme], username, passwd)
KeyError: 'https'

**Comment by soapy1** [comment]
@geparada is this still an issue for you?

**Comment by tyler-thetyrant** [comment]
Closing due to lack of response.
