### ISSUE TITLE
failed to update anaconda

### ISSUE THREAD

**Issue by francispoulin** [conda/conda#1435]
I recently tried to update conda and anaconda, as was suggested to me in an email.

Below is my conda information and the tail end of the error I get when I try and update anaconda.  

It suggests that I post a question here.  I realize that I should have done this using sudo but when I try now it doesn't show this anymore, it just says that anaconda is not installed on /Applications/anaconda, but I think it is.

Any advice?

/Applications/anaconda/bin/conda info
Current conda install:

             platform : osx-64
        conda version : 3.14.1
  conda-build version : 1.2.0
       python version : 2.7.10.final.0
     requests version : 2.6.2
     root environment : /Applications/anaconda  (writable)
  default environment : /Applications/anaconda
     envs directories : /Applications/anaconda/envs
        package cache : /Applications/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

anaconda-2.3.0 100% |###############################################################################| Time: 0:00:00   4.40 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                            |  34%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Applications/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Applications/anaconda/lib/python2.7/site-packages/conda/install.py", line 588, in link
    os.makedirs(dst_dir)
  File "/Applications/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Applications/anaconda/lib/python2.7/site-packages/numba/cuda/simulator'

**Comment by asmeurer** [comment]
If you use sudo to install Anaconda (which you have to do to install it into /Applications), you will have to use sudo for every conda command thereafter. conda doesn't really check this for you. I recommend installing Anaconda in your user directory (the default install location).

**Comment by francispoulin** [comment]
Thanks for the feedback.
When I try sudo I still find a problem that anaconda is not installed in Applications, even though it is.

Any advice?

sudo /Applications/anaconda/bin/conda update anaconda
Error: package 'anaconda' is not installed in /Applications/anaconda
