### ISSUE TITLE
Error Launching Anaconda Apps

### ISSUE THREAD

**Issue by fbchow** [conda/conda#1440]
Error launching application:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/Nombre/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/Users/Nombre/anaconda/lib/python3.4/site-packages/conda/cli/main_run.py", line 72, in execute
    conda.install.is_linked(prefix, pkg))]
  File "/Users/Nombre/anaconda/lib/python3.4/site-packages/conda/install.py", line 488, in is_linked
    return json.load(fi)
  File "/Users/Nombre/anaconda/lib/python3.4/json/**init**.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/Users/Nombre/anaconda/lib/python3.4/json/**init**.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/Users/Nombre/anaconda/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/Nombre/anaconda/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

**Comment by soapy1** [comment]
@fbchow is this still a problem for you?
