### ISSUE TITLE
"AttributeError: module 'logging' has no attribute '_acquireLock'" w/ Python 3.13

### ISSUE THREAD

**Issue by dannf** [conda/conda#14439]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

conda 24.11.1 w/ Python 3.13.1 crashes w/ `AttributeError: module 'logging' has no attribute '_acquireLock'` under Python 3.13.

### Conda Info

```shell
# conda info
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 18, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 55, in main_subshell
    init_loggers()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 14, in init_loggers
    initialize_logging()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 144, in initialize_logging
    set_conda_log_level()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 191, in set_conda_log_level
    attach_stderr_handler(level=level, logger_name="conda", filters=[TokenURLFilter()])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 357, in attach_stderr_handler
    with _logger_lock():
         ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 270, in _logger_lock
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/conda", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main_pip.py", line 29, in main
    return main(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 105, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 386, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 21, in __call__
    return self.handle_exception(exc_val, exc_tb)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 75, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 88, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 188, in print_unexpected_error_report
    self.write_out(*message_builder)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 28, in write_out
    init_loggers()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 14, in init_loggers
    initialize_logging()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 144, in initialize_logging
    set_conda_log_level()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 191, in set_conda_log_level
    attach_stderr_handler(level=level, logger_name="conda", filters=[TokenURLFilter()])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 357, in attach_stderr_handler
    with _logger_lock():
         ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 270, in _logger_lock
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'
```

### Conda Config

```shell
# conda config --show-sources
/usr/lib/python3.13/site-packages/conda/base/context.py:201: FutureWarning: Adding 'defaults' to channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly with conda's regular configuration system, e.g. by adding 'defaults' to the list of channels:

  conda config --add channels defaults

For more information see https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html

  deprecated.topic(
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 18, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 55, in main_subshell
    init_loggers()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 14, in init_loggers
    initialize_logging()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 144, in initialize_logging
    set_conda_log_level()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 191, in set_conda_log_level
    attach_stderr_handler(level=level, logger_name="conda", filters=[TokenURLFilter()])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 357, in attach_stderr_handler
    with _logger_lock():
         ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 270, in _logger_lock
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/conda", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main_pip.py", line 29, in main
    return main(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 105, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 386, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 21, in __call__
    return self.handle_exception(exc_val, exc_tb)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 75, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 88, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 188, in print_unexpected_error_report
    self.write_out(*message_builder)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 28, in write_out
    init_loggers()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 14, in init_loggers
    initialize_logging()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 144, in initialize_logging
    set_conda_log_level()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 191, in set_conda_log_level
    attach_stderr_handler(level=level, logger_name="conda", filters=[TokenURLFilter()])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 357, in attach_stderr_handler
    with _logger_lock():
         ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 270, in _logger_lock
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'
```

### Conda list

```shell
# conda list --show-channel-urls
/usr/lib/python3.13/site-packages/conda/base/context.py:201: FutureWarning: Adding 'defaults' to channel list implicitly is deprecated and will be removed in 25.3. 

To remove this warning, please choose a default channel explicitly with conda's regular configuration system, e.g. by adding 'defaults' to the list of channels:

  conda config --add channels defaults

For more information see https://docs.conda.io/projects/conda/en/stable/user-guide/configuration/use-condarc.html

  deprecated.topic(
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 18, in __call__
    return func(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 55, in main_subshell
    init_loggers()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 14, in init_loggers
    initialize_logging()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 144, in initialize_logging
    set_conda_log_level()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 191, in set_conda_log_level
    attach_stderr_handler(level=level, logger_name="conda", filters=[TokenURLFilter()])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 357, in attach_stderr_handler
    with _logger_lock():
         ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 270, in _logger_lock
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/conda", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main_pip.py", line 29, in main
    return main(*args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 105, in main
    return conda_exception_handler(main, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 386, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 21, in __call__
    return self.handle_exception(exc_val, exc_tb)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 75, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 88, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 188, in print_unexpected_error_report
    self.write_out(*message_builder)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/exception_handler.py", line 28, in write_out
    init_loggers()
    ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/cli/main.py", line 14, in init_loggers
    initialize_logging()
    ~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 144, in initialize_logging
    set_conda_log_level()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/conda/gateways/logging.py", line 191, in set_conda_log_level
    attach_stderr_handler(level=level, logger_name="conda", filters=[TokenURLFilter()])
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 357, in attach_stderr_handler
    with _logger_lock():
         ~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 141, in __enter__
    return next(self.gen)
  File "/usr/lib/python3.13/site-packages/conda/common/io.py", line 270, in _logger_lock
    logging._acquireLock()
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute '_acquireLock'
```

**Comment by travishathaway** [comment]
@dannf,

Thanks for reporting this! This is known issue and is currently being tracked by the following pull request:

- https://github.com/conda/conda/pull/14117

We will merge this pull request before officially adding Python 3.13 support. Currently, we do not support this version of Python.

**Comment by dannf** [comment]
Understood, thank you for the quick reply @travishathaway !

**Comment by SheMelody** [comment]
I really need to use conda in my environment, any ETA?

**Comment by Ye123459** [comment]
If you need to use the conda environment, it usually depends on when you install Anaconda or Miniconda, which usually takes only a few minutes. Regarding ETA (estimated time to Completion), this depends on your network speed and computer performance.

Network speed: Downloads of Anaconda or Miniconda packages range in size from tens of megabytes to several gigabytes (the full version of Anaconda is larger), so a faster network can speed up the process.
Computer performance: The installation process itself does not require much computer performance, but the speed of creating and activating the environment is affected by the disk read and write speed.

**Comment by SheMelody** [comment]
I meant the ETA for this to be fixed. In the end, I simply opted for a local miniconda install with Python 3.12 in the end instead of using 3.13 as a base. Took no time to set it up, I have 2.5 Gbps network.

**Comment by travishathaway** [comment]
@SheMelody,

We plan on adding Python 3.13 support pretty soon, so it should be completed in the near future. We unfortunately cannot say exactly when though.

Remember, just because your base environment doesn't include Python 3.13 doesn't mean you can't use Python 3.13 today. To use the latest version of Python, you simply need to create a separate environment for it.

The following command will give you an environment you can use with Python 3.13:

```
conda create --name py313 python=3.13
```

Hope that helps!
