### ISSUE TITLE
Unicode Error when activate an env

### ISSUE THREAD

**Issue by zengkaipeng** [conda/conda#14453]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

I install the latest anaconda (Windows) from anaconda.com and finish the `conda init`. Then when I reopen the terminal, an Error is reported
```
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\conda\cli\main.py", line 140, in main
    return activator_main()
  File "E:\anaconda\lib\site-packages\conda\activate.py", line 1210, in main
    print(activator.execute(), end ='')
UnicodeEncodeError: 'gbk' codec can't encode character '\u202a' in position 1258: illegal multibyte sequence
```

### Conda Info

```shell

```

### Conda Config

```shell

```

### Conda list

```shell

```

**Comment by travishathaway** [comment]
@zengkaipeng,

Are you able to run `conda info`? It would be very helpful to know which version of conda you are running.

Otherwise, I could recommend trying to set `auto_activate_base` to `false` to get the error to stop appearing when opening your terminal. You could either run the following command to do it:

```
conda config --set auto_activate_base false
```

or you could place a `.condarc` file with the following contents in the root of your user directory:

```
auto_activate_base: false
```

(be sure to use a program like `notepad` or `vscode` when creating/editing your `.condarc` file)

The last piece of advice I can give you is to try and use a different character encoding for your terminal. This error stems from the character encoding being `gbk`. I think it would help to use something like `utf-8`.  I unfortunately cannot provide any guidance on exactly how to do this.

**Comment by zengkaipeng** [comment]
> [@zengkaipeng](https://github.com/zengkaipeng),
> 
> Are you able to run `conda info`? It would be very helpful to know which version of conda you are running.
> 
> Otherwise, I could recommend trying to set `auto_activate_base` to `false` to get the error to stop appearing when opening your terminal. You could either run the following command to do it:
> 
> ```
> conda config --set auto_activate_base false
> ```
> 
> or you could place a `.condarc` file with the following contents in the root of your user directory:
> 
> ```
> auto_activate_base: false
> ```
> 
> (be sure to use a program like `notepad` or `vscode` when creating/editing your `.condarc` file)
> 
> The last piece of advice I can give you is to try and use a different character encoding for your terminal. This error stems from the character encoding being `gbk`. I think it would help to use something like `utf-8`. I unfortunately cannot provide any guidance on exactly how to do this.

The device is not with me now, but I saved the error report prepared by conda. The report is as follows
```
 Traceback (most recent call last):
      File "D:\Anonda\Lib\site-packages\conda\exception_handler.py", line 18, in __call__
        return func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
      File "D:\Anonda\Lib\site-packages\conda\cli\main.py", line 87, in main_sourced
        print(activator.execute(), end="")
    UnicodeEncodeError: 'gbk' codec can't encode character '\u202a' in position 762: illegal multibyte sequence

`$ D:\Anonda\Scripts\conda-script.py shell.powershell activate base`

  environment variables:
                 CIO_TEST=<not set>
    CONDA_ALLOW_SOFTLINKS=false
                CONDA_EXE=D:\Anonda\Scripts\conda.exe
               CONDA_ROOT=D:\Anonda
                CUDA_PATH=D:\cuda_12.2.0_536.25_windows
           CURL_CA_BUNDLE=<not set>
                 HOMEPATH=\Users\lenovo
               LD_PRELOAD=<not set>
                     PATH=D:\cudnn_9.3.0_windows\bin;D:\cuda_12.2.0_536.25_windows\bin;D:\cuda_1
                          2.2.0_536.25_windows\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows
                          \System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\
                          System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Comm
                          on;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\
                          System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Progr
                          am Files\NVIDIA Corporation\Nsight Compute 2023.2.0\;C:\Program
                          Files\NVIDIA Corporation\NVIDIA NvDLISR;D:\cudnn_9.3.0_windows\include
                          ;D:\cudnn_9.3.0_windows\lib;D:\cudnn_9.3.0_windows\libnvvp;‪D:\mingw64
                          \bin;D:\Anonda;D:\Anonda\Library\mingw-
                          w64\bin;D:\Anonda\Library\usr\bin;D:\Anonda\Library\bin;D:\Anonda\Scri
                          pts;C:\Users\lenovo\AppData\Local\Microsoft\WindowsApps;D:\Microsoft
                          VS Code\bin;D:\mingw64\bin;D:\mingw64\bin;
             PSMODULEPATH=C:\Users\lenovo\Documents\WindowsPowerShell\Modules;C:\Program Files\W
                          indowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Mo
                          dules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\lenovo\.condarc
 populated config files : D:\Anonda\.condarc
                          C:\Users\lenovo\.condarc
          conda version : 24.9.2
    conda-build version : 24.9.0
         python version : 3.12.7.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.9.2=0
                          __cuda=12.2=0
                          __win=0=0
       base environment : D:\Anonda  (writable)
      conda av data dir : D:\Anonda\etc\conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anonda\pkgs
                          C:\Users\lenovo\.conda\pkgs
                          C:\Users\lenovo\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anonda\envs
                          C:\Users\lenovo\.conda\envs
                          C:\Users\lenovo\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.9.2 requests/2.32.3 CPython/3.12.7 Windows/11 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.9.0 libmambapy/1.5.8
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

hope this will help.

**Comment by travishathaway** [comment]
Thanks for the additional information.

I have nothing to add other than what I originally suggested.
