### ISSUE TITLE
conda env update --prune does not install require dependencies

### ISSUE THREAD

**Issue by laughingrice** [conda/conda#14459]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

When updating packages in the environment with

```
conda env update -n <name> -f <yaml file> --prune
```

Dependencies are not installed resulting with a broken environment.
As a simple test case, define the `environment.yml` as

```
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.1.2
```

Then

```
conda create -n demo python=3.12
conda env upgrade --name=demo --file=environment.yml --prune
conda activate demo
python -c "import numpy"
```

import fails because numpy does not have required dependencies. If instead this is run without the --prune option it works

```
conda create -n demo python=3.12
conda env upgrade --name=demo --file=environment.yml
conda activate demo
python -c "import numpy"
```

### Conda Info

```shell
(demo2) PS C:\Users\Ido\Documents\micha\apeiron\137> conda info

     active environment : demo2
    active env location : C:\Users\Ido\miniconda3\envs\demo2
            shell level : 2
       user config file : C:\Users\Ido\.condarc
 populated config files : C:\Users\Ido\.condarc
          conda version : 24.11.2
    conda-build version : not installed
         python version : 3.12.8.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=broadwell
                          __conda=24.11.2=0
                          __win=0=0
       base environment : C:\Users\Ido\miniconda3  (writable)
      conda av data dir : C:\Users\Ido\miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Ido\miniconda3\pkgs
                          C:\Users\Ido\.conda\pkgs
                          C:\Users\Ido\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Ido\miniconda3\envs
                          C:\Users\Ido\.conda\envs
                          C:\Users\Ido\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/24.11.2 requests/2.32.3 CPython/3.12.8 Windows/11 Windows/10.0.22631 solver/libmamba conda-libmamba-solver/24.11.1 libmambapy/2.0.5 aau/0.5.0 c/. s/. e/.
          administrator : False
             netrc file : None
           offline mode : False
```

### Conda Config

```shell
pip_interop_enabled: True
channel_priority: flexible
channels:
  - pytorch
  - conda-forge
  - defaults
```

### Conda list

```shell
# packages in environment at C:\Users\Ido\miniconda3\envs\demo2:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h2466b09_7    conda-forge
ca-certificates           2024.12.14           h56e8100_0    conda-forge
libexpat                  2.6.4                he0c23c2_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
liblzma                   5.6.3                h2466b09_1    conda-forge
libsqlite                 3.47.2               h67fdade_0    conda-forge
libzlib                   1.3.1                h2466b09_2    conda-forge
numpy                     2.1.2           py312hf10105a_0    conda-forge
openssl                   3.4.0                h2466b09_0    conda-forge
pip                       24.3.1             pyh8b19718_2    conda-forge
python                    3.12.8          h3f84c4b_1_cpython    conda-forge
setuptools                75.6.0             pyhff2d567_1    conda-forge
tk                        8.6.13               h5226925_1    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_1    conda-forge
vc                        14.3                ha32ba9b_23    conda-forge
vc14_runtime              14.42.34433         he29a5d6_23    conda-forge
vs2015_runtime            14.42.34433         hdffcdeb_23    conda-forge
wheel                     0.45.1             pyhd8ed1ab_1    conda-forge
```

**Comment by travishathaway** [comment]
@laughingrice,

Thanks for this issue and for providing instructions on how to recreate 🙏. Unfortunately, I was not able to reproduce this error on my macOS laptop using the `osx-arm64` architecture.

We will need to wait for someone to try and recreate this on a Windows machine to proceed.

**Comment by Manezki** [comment]
I'm running into same error while `conda env update`:ing during a Dockerfile build.

## Setup to replicate the error

Dockerfile:
```
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY environment.yml .

RUN conda env update --name base --file environment.yml --prune && \
    conda clean -afy

RUN poetry --version
```

Environment.yml:
```
name: conda-build
channels:
  - conda-forge
dependencies:
  - poetry[version='>=1.8']
  - python=3.10
```

Docker command: `docker build --progress plain -t conda-build:latest .`

Output:
```
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 645B done
#1 DONE 0.0s

#2 [internal] load .dockerignore
#2 transferring context: 663B done
#2 DONE 0.0s

#3 [internal] load metadata for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
#3 DONE 0.0s

#4 [1/5] FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
#4 DONE 0.0s

#5 [internal] load build context
#5 transferring context: 36B done
#5 DONE 0.0s

#6 [2/5] WORKDIR /app
#6 CACHED

#7 [3/5] COPY environment.yml .
#7 CACHED

#8 [4/5] RUN conda env update --name base --file environment.yml --prune &&     conda clean -afy
#8 1.144 Retrieving notices: done
#8 2.143 Channels:
#8 2.143  - conda-forge
#8 2.143  - defaults
#8 2.143 Platform: linux-64
#8 2.143 Collecting package metadata (repodata.json): ...working... done
#8 12.39 Solving environment: ...working... done
#8 13.92 
                                                      done.
#8 14.27 Preparing transaction: done                 
#8 14.37 Verifying transaction: done                 
#8 14.47 Executing transaction: done
#8 21.99 #
#8 21.99 # To activate this environment, use
#8 21.99 #
#8 21.99 #     $ conda activate base
#8 21.99 #
#8 21.99 # To deactivate an active environment, use
#8 21.99 #
#8 21.99 #     $ conda deactivate
#8 21.99 
#8 22.84 Will remove 1 package cache(s).
#8 DONE 23.4s

#9 [5/5] RUN poetry --version
#9 0.482 Traceback (most recent call last):
#9 0.482   File "/opt/miniconda/bin/poetry", line 6, in <module>
#9 0.482     from poetry.console.application import main
#9 0.482   File "/opt/miniconda/lib/python3.10/site-packages/poetry/console/application.py", line 11, in <module>
#9 0.482     from cleo.application import Application as BaseApplication
#9 0.483 ModuleNotFoundError: No module named 'cleo'
#9 ERROR: process "/bin/sh -c poetry --version" did not complete successfully: exit code: 1
------
 > [5/5] RUN poetry --version:
0.482 Traceback (most recent call last):
0.482   File "/opt/miniconda/bin/poetry", line 6, in <module>
0.482     from poetry.console.application import main
0.482   File "/opt/miniconda/lib/python3.10/site-packages/poetry/console/application.py", line 11, in <module>
0.482     from cleo.application import Application as BaseApplication
0.483 ModuleNotFoundError: No module named 'cleo'
------
Dockerfile:17
--------------------
  15 |         conda clean -afy
  16 |     
  17 | >>> RUN poetry --version
  18 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c poetry --version" did not complete successfully: exit code: 1
```

## Workaround

Removing the `--prune` option from `conda env update` from the Dockerfile causes the build to succeed.

Fixed Dockerfile:
```
# The base image originates from the Azure Machine Learning containers repository, see:
# https://github.com/Azure/AzureML-Containers/blob/master/base/cpu/openmpi4.1.0-ubuntu22.04/Dockerfile
FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04

# Writing bytecode is unnecessary in an ephemeral container
ENV PYTHONDONTWRITEBYTECODE=1
# Write STDOUT and STDERR immediately
ENV PYTHONUNBUFFERED=1

WORKDIR /app
COPY environment.yml .

# Install CUDA and poetry (specified in environment.yml)
RUN conda env update --name base --file environment.yml && \
    conda clean -afy

RUN poetry --version
```

Output:
```
#0 building with "default" instance using docker driver

#1 [internal] load build definition from Dockerfile
#1 transferring dockerfile: 637B done
#1 DONE 0.1s

#2 [internal] load .dockerignore
#2 transferring context: 663B done
#2 DONE 0.1s

#3 [internal] load metadata for mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
#3 DONE 0.0s

#4 [1/5] FROM mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
#4 CACHED

#5 [internal] load build context
#5 transferring context: 142B done
#5 DONE 0.1s

#6 [2/5] WORKDIR /app
#6 DONE 0.1s

#7 [3/5] COPY environment.yml .
#7 DONE 0.1s

#8 [4/5] RUN conda env update --name base --file environment.yml &&     conda clean -afy
#8 1.209 Retrieving notices: done
#8 2.205 Channels:
#8 2.205  - conda-forge
#8 2.205  - defaults
#8 2.205 Platform: linux-64
#8 2.205 Collecting package metadata (repodata.json): ...working... done
#8 12.42 Solving environment: ...working... done
#8 13.94 
 done                                                ing...
#8 16.12 Preparing transaction: done                 
#8 16.32 Verifying transaction: done                 
#8 16.74 Executing transaction: done                 
#8 22.13 #                                           
#8 22.13 # To activate this environment, use         
#8 22.13 #                                           
#8 22.13 #     $ conda activate base                 
#8 22.13 #                                           
#8 22.13 # To deactivate an active environment, use  
#8 22.13 #                                           
#8 22.13 #     $ conda deactivate                    
#8 22.13                                             
#8 23.02 Will remove 1 package cache(s).             
#8 DONE 25.9s                                        
#8 16.12                                             
#9 [5/5] RUN poetry --version                        
#9 1.157 Poetry (version 1.8.5)                      
#9 DONE 1.2s                                         
                      
#10 exporting to image
#10 exporting layers
#10 exporting layers 2.1s done
#10 writing image sha256:fe0037a9cef2c1131aa345e989bd52052c07642177684100c1e21974b69c221a done
#10 naming to docker.io/library/conda-build:latest 0.0s done
#10 DONE 2.1s
```

## System info

From @travishathaway I assume that the OS might have impact on the behavior. My testing is run on Linux with x86_64.

## Additional info

My build broke over time without changes on my build process. My previous successful build has used Conda **24.11.0**, and the broken build uses Conda **24.11.2**. However, there are other automatically upgrading sources that might have also caused my issue.

**Comment by laughingrice** [comment]
> [@laughingrice](https://github.com/laughingrice),
> 
> Thanks for this issue and for providing instructions on how to recreate 🙏. Unfortunately, I was not able to reproduce this error on my macOS laptop using the `osx-arm64` architecture.
> 
> We will need to wait for someone to try and recreate this on a Windows machine to proceed.

Not sure how recent, but it is a recent regression. It was working fine for me a few weeks ago when I built those environment files.

I just checked on an ubuntu machine, a mac, and two windows machines (all after a conda upgrade --all in the base environment) and it fails on all.

I tried downgrading conda-libmamba-solver, and that solves the problem, so it is one one of the new mamba solver packages (I don't understand enough how the solver works so not sure how to track it down)

conda install conda-libmamba-solver=24.9.0

The following packages will be DOWNGRADED:

  conda-libmamba-so~                   24.11.1-pyhd8ed1ab_0 --> 24.9.0-pyhd8ed1ab_0
  libmamba                                 2.0.5-hd41e4cc_0 --> 1.5.11-hd41e4cc_0
  libmambapy                          2.0.5-py312h0252a60_0 --> 1.5.11-py312h0252a60_0
  mamba                                    2.0.5-hcd709ef_0 --> 1.5.11-py312ha12221d_0

**Comment by travishathaway** [comment]
@laughingrice,

Thanks for the additional information. I am now able to reliably recreate this issue. I can also report that this does not happen when using the `classic` solver.
