### ISSUE TITLE
Unable to clone root environment in offline mode

### ISSUE THREAD

**Issue by ran404** [conda/conda#1449]
According to the help pages, it should be possible to create a new environment based off a clone without internet by supplying the --offline and --use-index-cache options. But these don't seem to work, conda insists on retrieving package metadata form the internet.

e.g.
```
PS C:\Users\rfan> conda create rootclone2 --clone root --offline --use-index-cache
Error: either -n NAME or -p PREFIX option required,
       try "conda create -h" for more details
PS C:\Users\rfan> conda create -n rootclone2 --clone root --offline --use-index-cache
src_prefix: 'C:\\Program Files\\Anaconda'
dst_prefix: 'C:\\Users\\rfan\\.conda\\envs\\rootclone2'
Packages: 122
Files: 5
Fetching package metadata: Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Program Files\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    args.func(args, p)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
    return func(args, parser)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 170, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 91, in clone
    quiet=quiet)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\misc.py", line 186, in clone_env
    execute_actions(actions, index=get_index(), verbose=not quiet)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
KeyError: 'menuinst-1.0.4-py27_0.tar.bz2'
```

This issue effectively prevents us from using anaconda offline as our company policy prevents outside access from internal apps.

Is it possible to tell conda not to use the internet? Surely it has all the information it needs to in order to clone the root environment?

**Comment by ilanschnell** [comment]
PR https://github.com/conda/conda/pull/1487 (which is already merged) should fix this.
