### ISSUE TITLE
https proxy username/password

### ISSUE THREAD

**Issue by May989** [conda/conda#1452]
I have installed anaconda using the command "bash Anaconda-2.3.0-Linux-x86_64.sh" and gave path of bin/conda to .bashrc and default it asks for bin path prepending which I gave, after closing and then running terminal I ran:
conda create -n dato-env python=2.7
which requires https proxy unsername and password for metadata, following is the error:
Password:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/mayank/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    offline=args.offline)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 549, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 154, in fetch_repodata
    handle_proxy_407(url, session)
  File "/home/mayank/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 184, in handle_proxy_407
    session.proxies[scheme], username, passwd)
KeyError: 'https'

Can you please help in this regard

**Comment by asmeurer** [comment]
Can you paste the output of `conda info` here?

**Comment by May989** [comment]
Sure. Output of conda info:
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/mayank/anaconda  (writable)
  default environment : /home/mayank/anaconda
     envs directories : /home/mayank/anaconda/envs
        package cache : /home/mayank/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
I'm not sure if there's anything conda can do here, if I understand what is happening, other than give a better error message, which I have done at https://github.com/conda/conda/pull/1463. See http://conda.pydata.org/docs/config.html#configure-conda-for-use-behind-a-proxy-server for more information on how to configure your proxies.

**Comment by bkreider** [comment]
I think this is also related to #1423, and #1418
