### ISSUE TITLE
python notebook updated

### ISSUE THREAD

**Issue by thesarahmeister** [conda/conda#1460]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 267, in install
    m['name'] == name]
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by asmeurer** [comment]
https://github.com/conda/conda/pull/1464

**Comment by asmeurer** [comment]
You probably have some permissions issues. The listed pull request ignores metadata that can't be read, but maybe it should give an error instead.
