### ISSUE TITLE
Error in scipy 0.16 packaging in official conda channels on OSX 

### ISSUE THREAD

**Issue by jni** [conda/conda#1467]
(Not sure whether this is the right repo to open this; please direct me otherwise if necessary.)

I get a missing library `libSystem.B.dylib` error:

```
ImportError: dlopen(/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/minpack2.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/minpack2.so
  Expected in: /usr/lib/libSystem.B.dylib
```

Full steps to reproduce on OSX 10.10.3:

```
jni@molino Tue Jul 28 15:38
 ~/projects/elegant-scipy (ch7)$ conda create -n test-scipy python=3.4 scikit-learn ipython
Fetching package metadata: ........
Solving package specifications: .
Package plan for installation in environment /Users/jni/conda/envs/test-scipy:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python.app-1.2             |           py34_4           7 KB
    ipython-3.2.1              |           py34_0         3.4 MB
    ------------------------------------------------------------
                                           Total:         3.5 MB

The following NEW packages will be INSTALLED:

    ipython:      3.2.1-py34_0
    nose:         1.3.7-py34_0
    numpy:        1.9.2-py34_0
    openssl:      1.0.1k-1
    pip:          7.1.0-py34_0
    python:       3.4.3-0
    python.app:   1.2-py34_4
    readline:     6.2-2
    scikit-learn: 0.16.1-np19py34_0
    scipy:        0.16.0-np19py34_0
    setuptools:   18.0.1-py34_0
    sqlite:       3.8.4.1-1
    tk:           8.5.18-0
    xz:           5.0.5-0
    zlib:         1.2.8-0

Proceed ([y]/n)?

Fetching packages ...
python.app-1.2 100% |################################| Time: 0:00:00   4.18 MB/s
ipython-3.2.1- 100% |################################| Time: 0:00:09 378.59 kB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate test-scipy
#
# To deactivate this environment, use:
# $ source deactivate
#
(elegant)
jni@molino Tue Jul 28 15:39
 ~/projects/elegant-scipy (ch7)$ source activate test-scipy
discarding /Users/jni/conda/envs/elegant/bin from PATH
prepending /Users/jni/conda/envs/test-scipy/bin to PATH
(test-scipy)
jni@molino Tue Jul 28 15:39
 ~/projects/elegant-scipy (ch7)$ ipython
Activating auto-logging. Current session state plus future input saved.
Filename       : /Users/jni/ipython-logs/automatic-log--2015.07.28--15.39.py
Mode           : backup
Output logging : False
Raw input log  : False
Timestamping   : False
State          : active

In [1]: from sklearn import decomposition
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-487c1244202c> in <module>()
----> 1 from sklearn import decomposition

/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/sklearn/decomposition/__init__.py in <module>()
      5 """
      6
----> 7 from .nmf import NMF, ProjectedGradientNMF
      8 from .pca import PCA, RandomizedPCA
      9 from .incremental_pca import IncrementalPCA

/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/sklearn/decomposition/nmf.py in <module>()
     16 import numpy as np
     17 import scipy.sparse as sp
---> 18 from scipy.optimize import nnls
     19
     20 from ..base import BaseEstimator, TransformerMixin

/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/__init__.py in <module>()
    219 from __future__ import division, print_function, absolute_import
    220
--> 221 from .optimize import *
    222 from ._minimize import *
    223 from ._root import *

/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/optimize.py in <module>()
     35                    vectorize, asarray, sqrt, Inf, asfarray, isinf)
     36 import numpy as np
---> 37 from .linesearch import (line_search_wolfe1, line_search_wolfe2,
     38                          line_search_wolfe2 as line_search,
     39                          LineSearchWarning)

/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/linesearch.py in <module>()
     16 from warnings import warn
     17
---> 18 from scipy.optimize import minpack2
     19 import numpy as np
     20 from scipy._lib.six import xrange

ImportError: dlopen(/Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/minpack2.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/jni/conda/envs/test-scipy/lib/python3.4/site-packages/scipy/optimize/minpack2.so
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by ggventurini** [comment]
Hi, 

I just installed scipy 0.16.0 through conda as well on OS X 10.10.4 and I have a very similar issue:

```
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import scipy
>>> import scipy.signal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/scipy/signal/__init__.py", line 280, in <module>
    from .bsplines import *
  File "//anaconda/lib/python2.7/site-packages/scipy/signal/bsplines.py", line 12, in <module>
    from scipy.special import comb, gamma
  File "//anaconda/lib/python2.7/site-packages/scipy/special/__init__.py", line 603, in <module>
    from .basic import *
  File "//anaconda/lib/python2.7/site-packages/scipy/special/basic.py", line 18, in <module>
    from . import orthogonal
  File "//anaconda/lib/python2.7/site-packages/scipy/special/orthogonal.py", line 101, in <module>
    from scipy import linalg
  File "//anaconda/lib/python2.7/site-packages/scipy/linalg/__init__.py", line 172, in <module>
    from .misc import *
  File "//anaconda/lib/python2.7/site-packages/scipy/linalg/misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "//anaconda/lib/python2.7/site-packages/scipy/linalg/blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/scipy/linalg/_fblas.so, 2): Library not loaded: /usr/local/gfortran/lib/libquadmath.0.dylib
  Referenced from: //anaconda/lib/python2.7/site-packages/scipy/linalg/_fblas.so
  Reason: image not found
>>> 
```

Importing the top `scipy` module works.

I posted here because I would guess it's the same bug, but if you wish me to file a separate isuue, just ask away.

Best, GV

**Comment by asmeurer** [comment]
@ggventurini that looks like a separate issue. Are you sure that is coming from the Continuum scipy?

**Comment by groutr** [comment]
https://github.com/ContinuumIO/anaconda-issues/issues/392

**Comment by asmeurer** [comment]
Closing as a duplicate.
