### ISSUE TITLE
Errno 13 , Permission denied, when creating environment 

### ISSUE THREAD

**Issue by eghbalhosseini** [conda/conda#1479]
Hi 
I am using a cluster and trying to create an environment but receive the following error:
Code:
conda create -n phy --clone=/cm/shared/openmind/anaconda/2.1.0

Error:

Traceback (most recent call last):
  File "/cm/shared/openmind/anaconda/2.1.0/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/install.py", line 164, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/install.py", line 85, in clone
    quiet=quiet)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/misc.py", line 173, in clone_env
    execute_actions(actions, index=get_index(), verbose=not quiet)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/plan.py", line 569, in execute_plan
    link(prefix, arg, index=index)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/plan.py", line 525, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/install.py", line 528, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/cm/shared/openmind/anaconda/2.1.0/lib/python2.7/site-packages/conda/install.py", line 266, in update_prefix
    with open(path, 'wb') as fo:
IOError: [Errno 13] Permission denied: '/home/ehoseini/envs/phy/bin/py.test'

**Comment by soapy1** [comment]
@eghbalhosseini is this still an issue for you. If so, could you include the output of `conda info`

**Comment by kiranhari** [comment]
@soapy1 I am having the same issue
The conda info is 
(C:\ProgramData\Anaconda3) C:\Users\BANUCABLE>conda info
Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\BANUCABLE\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

**Comment by kracwarlock** [comment]
getting this as well

**Comment by kalefranz** [comment]
Updating to conda >=4.3.13 should fix this. Latest is conda 4.3.17.

**Comment by kracwarlock** [comment]
worked
thanks
