### ISSUE TITLE
`CONDA_BLD_PATH=./ conda build ./` causes lasting problems 

### ISSUE THREAD

**Issue by StuartAxelOwen** [conda/conda#1480]
Also, following builds experience the same problem.

Stack trace:

```
Traceback (most recent call last):
  File "/Users/stuart/Applications/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/stuart/Applications/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 127, in main
    args_func(args, p)
  File "/Users/stuart/Applications/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 349, in args_func
    args.func(args, p)
  File "/Users/stuart/Applications/anaconda/lib/python3.4/site-packages/conda_build/main_build.py", line 308, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "/Users/stuart/Applications/anaconda/lib/python3.4/site-packages/conda_build/build.py", line 340, in build
    source.provide(m.path, m.get_section('source'))
  File "/Users/stuart/Applications/anaconda/lib/python3.4/site-packages/conda_build/source.py", line 257, in provide
    copytree(abspath(join(recipe_dir, meta.get('path'))), WORK_DIR)
  File "/Users/stuart/Applications/anaconda/lib/python3.4/shutil.py", line 343, in copytree
    raise Error(errors)
shutil.Error: [('/Users/stuart/code/python/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/build.bat', '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/build.bat', "[Errno 63] File name too long: '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/build.bat'"), ('/Users/stuart/code/python/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/build.sh', '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/build.sh', "[Errno 63] File name too long: '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/build.sh'"), ('/Users/stuart/code/python/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/conda.recipe', '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/conda.recipe', "[Errno 63] File name too long: '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/conda.recipe'"), ('/Users/stuart/code/python/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/hello.py', '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/hello.py', "[Errno 63] File name too long: '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/hello.py'"), ('/Users/stuart/code/python/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/meta.yaml', '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/meta.yaml', "[Errno 63] File name too long: '/Users/stuart/code/python/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/work/conda-deploy/meta.yaml'")]
```

**Comment by StuartAxelOwen** [comment]
(removing the `work` directory stops further builds from failing)

**Comment by ilanschnell** [comment]
I would always set `CONDA_BLD_PATH` to an absolute path.

**Comment by soapy1** [comment]
@StuartAxelOwen is this still an issue for you?
