### ISSUE TITLE
conda update conda: fails with:  ValueError: failed to parse CPython sys.version: '2.7.9 

### ISSUE THREAD

**Issue by jbpoline** [conda/conda#1481]
here are the details: after installing miniconda without problems - conda update conda fails. 

$> conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.1
  conda-build version : not installed
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/jb/.conda_install/miniconda  (writable)
  default environment : /home/jb/.conda_install/miniconda
     envs directories : /home/jb/.conda_install/miniconda/envs
        package cache : /home/jb/.conda_install/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

$> conda update conda
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File ".../.conda_install/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 253, in install
    offline=args.offline)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 531, in get_index_trap
    return get_index(*args, **kwargs)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/utils.py", line 86, in __call__
    value = self.func(*args, **kw)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 228, in fetch_index
    session = CondaSession()
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/conda/connection.py", line 59, in __init__
    super(CondaSession, self).__init__(*args, **kwargs)
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/requests/sessions.py", line 290, in __init__
    self.headers = default_headers()
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/requests/utils.py", line 573, in default_headers
    'User-Agent': default_user_agent(),
  File ".../.conda_install/miniconda/lib/python2.7/site-packages/requests/utils.py", line 542, in default_user_agent
    _implementation = platform.python_implementation()
  File "/usr/lib/python2.7/platform.py", line 1521, in python_implementation
    return _sys_version()[0]
  File "/usr/lib/python2.7/platform.py", line 1486, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.9 |Continuum Analytics, Inc.| (default, Apr 14 2015, 12:54:25) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

**Comment by ilanschnell** [comment]
You installed Miniconda here: `/home/jb/.conda_install/miniconda`.
But the error is in `/usr/lib/python2.7/platform.py`, which is the system's Python platform module.
There has to be a misconfiguration on your end.  Do you have `PYTHONPATH`, `LD_LIBRARY_PATH` or something similar set?
