### ISSUE TITLE
libcloog tries to use /root/miniconda3/envs/_build

### ISSUE THREAD

**Issue by aaronk** [conda/conda#1484]
When trying to update a local Anaconda environment, libcloog fails with the following details:

```
(ilastik)[wmenegas@holynx01 ~]$ conda install cloog
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /n/home05/wmenegas/envs/ilastik:

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    cloog-0.18.0               |                0   hard-link
    gmp-5.1.2                  |                2   hard-link
    isl-0.12.2                 |                0   hard-link

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the###                                                                                 |  33%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/n/home05/wmenegas/envs/ilastik/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    execute_plan(plan, index, verbose)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    link(prefix, arg)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 438, in link
    update_prefix(join(prefix, f), prefix)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 13] Permission denied: '/root/miniconda3/envs/_build text lib/libcloog-isl.la'
(ilastik)[wmenegas@holynx01 ~]$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.4.1
       python version : 2.7.6.final.0
     root environment : /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x  (read only)
  default environment : /n/home05/wmenegas/envs/ilastik
     envs directories : /n/home05/wmenegas/envs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/envs
        package cache : /n/home05/wmenegas/envs/.pkgs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

(ilastik)[wmenegas@holynx01 ~]$ 
```

**Comment by soapy1** [comment]
@aaronk is this still an issue for you?
