### ISSUE TITLE
unicode in git commit causes conda build to fail

### ISSUE THREAD

**Issue by jreback** [conda/conda#1486]
On win-64 (on python3 and 2)

```
# packages in environment at C:\Miniconda:
#
conda                     3.15.1                   py27_0
conda-build               1.16.0                   py27_0
conda-env                 2.3.0                    py27_0
```

Using this commit and the included recipe

From here: https://github.com/pydata/pandas/commit/f00e51cd4eb96537357b33932c9d78711ca4bdc9

```
[pandas] C:\Users\Jeff Reback\pandas>conda build conda.recipe --no-test
Removing old build environment
Removing old work directory
BUILD START: pandas-v0.16.2-nppy27_283
Fetching package metadata: ......
Solving package specifications: .
The following NEW packages will be INSTALLED:

    cython:     0.22.1-py27_0
    dateutil:   2.4.1-py27_0
    libpython:  1.0-py27_1
    mingw:      4.7-1
    numpy:      1.9.2-py27_0
    pip:        7.1.0-py27_0
    python:     2.7.10-0
    pytz:       2015.4-py27_0
    setuptools: 18.0.1-py27_0
    six:        1.9.0-py27_0

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Removing old work directory
checkout: u'f00e51cd4eb96537357b33932c9d78711ca4bdc9'
Cloning into 'C:\Miniconda\conda-bld\work'...
done.
Note: checking out 'f00e51cd4eb96537357b33932c9d78711ca4bdc9'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at f00e51c... Merge pull request #10743 from kawochen/TST-TestMsgpack-gen
==> git log -n1 <==

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 173, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 400, in args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 358, in execute
    channel_urls=channel_urls, override_channels=args.override_channels)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 354, in build
    source.provide(m.path, m.get_section('source'))
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 253, in provide
    git_source(meta, recipe_dir)
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 136, in git_source
    git_info()
  File "C:\Miniconda\lib\site-packages\conda_build\source.py", line 165, in git_info
    print(stdout + u'\n')
  File "C:\Miniconda\lib\encodings\cp437.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 291-292: character maps to <undefined>
```

Note that this happens because of unicode in the actual commit message (which was an error). Reverting this an cleaning the commit allowed conda to build

```
commit f00e51cd4eb96537357b33932c9d78711ca4bdc9
Merge: 58ae9db c574d2c
Author: Jeff Reback <jeff@reback.net>
Date:   Tue Aug 4 07:47:19 2015 -0400

    Merge pull request #10743 from kawochen/TST-TestMsgpack-gen

    TST: test_packers.TestMsgpack checks for minimum structure and extra <E2><80><A6>

```

**Comment by asmeurer** [comment]
It seems https://github.com/conda/conda-build/pull/458 wasn't enough to fix this issue @pitrou.

**Comment by asmeurer** [comment]
The only thing I can figure out that makes this work is to remove `stdout=PIPE` and let git print the commit message directly to the terminal.

**Comment by pitrou** [comment]
> The only thing I can figure out that makes this work is to remove stdout=PIPE and let git print the commit message directly to the terminal. 

Or pass `fo` as stdout, if you want to print to that file object (assuming that's an actual file object with a valid fileno(), not a StringIO).

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1980
