### ISSUE TITLE
Cant clone environment

### ISSUE THREAD

**Issue by selahlynch** [conda/conda#1494]
selah@selah-Aspire-5745:~$ conda create --name ourenv --clone root
src_prefix: '/home/selah/anaconda'
dst_prefix: '/home/selah/anaconda/envs/ourenv'
Packages: 190
Files: 958
Fetching package metadata: ....
Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/selah/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 170, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 91, in clone
    quiet=quiet)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/misc.py", line 186, in clone_env
    execute_actions(actions, index=get_index(), verbose=not quiet)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/home/selah/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
KeyError: 'r-nlme-3.1.118-0.tar.bz2'

selah@selah-Aspire-5745:~$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.15.1
```

  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/selah/anaconda  (writable)
  default environment : /home/selah/anaconda
     envs directories : /home/selah/anaconda/envs
        package cache : /home/selah/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by LeeKamentsky** [comment]
I had the same problem with pysam-0.8.3. The problem was that pysam-0.8.3 was fetched from https://conda.binstar.org/bcbio and I did not have that channel in my .condarc file. I added it and things began to work.

I found pysam-0.8.3's channel by looking in the file <root>/conda-meta/pysam-0.8.3-py27_1.json - it's the dictionary's "channel" key.

I am far from an expert with Anaconda, but I am guessing that there's a config file somewhere in root that keeps track of the channels....??? and my install is not properly configured? Could you please at-tag me in the reply if that's the case so I can tell our IT dept?

**Comment by soapy1** [comment]
This seems to be resolved in the newest version of conda. Please `conda update conda`, closing this issue.
