### ISSUE TITLE
Conda skeleton fails with unicode error

### ISSUE THREAD

**Issue by jjbmatthews** [conda/conda#1499]
I have seen this on a few different packages, but here is an example:

$ conda skeleton pypi singledispatch
Warning, the following versions were found for singledispatch
3.4.0.3
3.4.0.2
3.4.0.1
3.4.0.0
Using 3.4.0.3
Use --version to specify a different version.
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/users/is/jmatthew/anaconda/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 400, in args_func
    args.func(args, p)
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/main_skeleton.py", line 286, in execute
    pypi.main(args, parser)
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 332, in main
    is_url)
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 374, in get_download_data
    data = client.release_data(package, version) if not is_url else None
  File "/users/is/jmatthew/anaconda/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/users/is/jmatthew/anaconda/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 224, in request
    return self.parse_response(resp)
  File "/users/is/jmatthew/anaconda/lib/python2.7/site-packages/conda_build/pypi.py", line 231, in parse_response
    p.feed(resp.text)
  File "/users/is/jmatthew/anaconda/lib/python2.7/xmlrpclib.py", line 558, in feed
    self._parser.Parse(data, 0)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 739-740: ordinal not in range(128)
(jasper)[cn92] ~
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.15.1
  conda-build version : 1.16.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /users/is/jmatthew/anaconda  (writable)
  default environment : /users/is/jmatthew/anaconda/envs/jasper
     envs directories : /users/is/jmatthew/anaconda/envs
        package cache : /users/is/jmatthew/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/jjbmatthews/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/jjbmatthews/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /users/is/jmatthew/.condarc
    is foreign system : False

**Comment by ilanschnell** [comment]
This is a `conda-build` issue, see https://github.com/conda/conda-build/issues.  However, I could not reproduce this problem.

**Comment by jjbmatthews** [comment]
moved to https://github.com/conda/conda-build/issues/540 and have dug around and found some more info - it does appear to be environment specific so a bit tricky to recreate.
