### ISSUE TITLE
tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by aQuaYi** [conda/conda#1510]
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/aqua/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/home/aqua/anaconda/lib/python2.7/site-packages/conda/install.py", line 454, in extract
    t = tarfile.open(path + '.tar.bz2')
  File "/home/aqua/anaconda/lib/python2.7/tarfile.py", line 1672, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂﹏▂
ubuntu 14.04.3
linux-64bit Python 2.7 
I installed anaconda with "sudo bash". After installation, I 'chown' and 'chgrp' the anaconda directory to meself. When I installing accelerate, those Errors raise up.

**Comment by soapy1** [comment]
Anaconda should not be installed with sudo. Do you still have this problem when you install with `bash anaconda.sh`?
