### ISSUE TITLE
local variable 'message' referenced before assignment

### ISSUE THREAD

**Issue by campos-ddc** [conda/conda#1530]
Traceback:

```
$ conda env create
Traceback (most recent call last):
  File "E:\Miniconda\Scripts\conda-env-script.py", line 4, in <module>
    sys.exit(main())
  File "E:\Miniconda\lib\site-packages\conda_env\cli\main.py", line 70, in main
    return args_func(args, parser)
  File "E:\Miniconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
    print_issue_message(e, use_json=use_json)
  File "E:\Miniconda\lib\site-packages\conda\cli\main.py", line 227, in print_issue_message
    print(message)
UnboundLocalError: local variable 'message' referenced before assignment
```

From the code, looks like maybe `message` should be set to `str(e)` when the exception is `not in ('ScannerError', 'ParserError')`:

```python
def print_issue_message(e, use_json=False):
    from conda.cli import common
    if e.__class__.__name__ not in ('ScannerError', 'ParserError'):
            message = """\
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

"""
    if use_json:
        import traceback
        common.error_and_exit(message + traceback.format_exc(),
                              error_type="UnexpectedError", json=True)
    print(message)
```

**Comment by asmeurer** [comment]
#1570
