### ISSUE TITLE
Error installing matplotlib --- issue with  libfontconfig

### ISSUE THREAD

**Issue by lzkelley** [conda/conda#1532]
Traceback:

Traceback (most recent call last):
  File "/n/home00/lkelley/envs/LZK/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    execute_plan(plan, index, verbose)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    link(prefix, arg)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 438, in link
    update_prefix(join(prefix, f), prefix)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3anaconda4anaconda5anaconda6anaconda7anaconda8anaconda9anaconda10anaconda11anaconda12anaconda13an binary lib/libfontconfig.so.1.8.0'

Conda info:

Current conda install:

```
         platform : linux-64
    conda version : 3.4.1
   python version : 2.7.6.final.0
 root environment : /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x  (read only)
```

  default environment : /n/home00/lkelley/envs/LZK
     envs directories : /n/home00/lkelley/envs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/envs
        package cache : /n/home00/lkelley/envs/.pkgs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

**Comment by martin-mann** [comment]
Hi, I have a similar problem with a bioconda perl package that uses `libgd`. Causes more or less the same error on runtime tests that it cannot find `libfontconfig.so`

Any progress about the issue?

**Comment by lzkelley** [comment]
@martin-mann I don't think I was able to fix this directly, but just started a new environment and got that to work... not sure, sorry!

**Comment by martin-mann** [comment]
@lzkelley thanks for the quick reply.. think adding the dependency `fontconfig` does the trick.. but I am still working on other build issues too, so I am not sure yet.

Anyway, thanks for the answer!
