### ISSUE TITLE
conda suggested to send error report scikit-learn force install

### ISSUE THREAD

**Issue by denfromufa** [conda/conda#1538]
```
C:\Users\blablabla>conda install scikit-learn --force
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Python\Python27:

The following packages will be UPDATED:

    scikit-learn: 0.16.1-np19py27_0 --> 0.16.1-np19py27_0

Proceed ([y]/n)? y

An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Python\Python27\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python\Python27\lib\site-packages\conda\cli\main.py", line 194, in ma
in
    args_func(args, p)
  File "C:\Python\Python27\lib\site-packages\conda\cli\main.py", line 201, in ar
gs_func
    args.func(args, p)
  File "C:\Python\Python27\lib\site-packages\conda\cli\main_install.py", line 45
, in execute
    install.install(args, parser, 'install')
  File "C:\Python\Python27\lib\site-packages\conda\cli\install.py", line 415, in
 install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Python\Python27\lib\site-packages\conda\plan.py", line 532, in execut
e_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Python\Python27\lib\site-packages\conda\instructions.py", line 148, i
n execute_instructions
    cmd(state, arg)
  File "C:\Python\Python27\lib\site-packages\conda\instructions.py", line 66, in
 RM_EXTRACTED_CMD
    install.rm_extracted(config.pkgs_dirs[0], arg)
  File "C:\Python\Python27\lib\site-packages\conda\install.py", line 473, in rm_
extracted
    rm_rf(path)
  File "C:\Python\Python27\lib\site-packages\conda\install.py", line 186, in rm_
rf
    shutil.rmtree(path)
  File "C:\Python\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python\Python27\lib\shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "C:\Python\Python27\lib\shutil.py", line 250, in rmtree
    os.remove(fullname)
WindowsError: [Error 5] Access is denied: u'C:\\Python\\Python27\\pkgs\\scikit-l
earn-0.16.1-np19py27_0\\Lib\\site-packages\\sklearn\\metrics\\cluster\\expected_
mutual_info_fast.pyd'

C:\Users\blablabla>
```

**Comment by denfromufa** [comment]
looks like I had some left-overs from pip installation of scikit-learn, which could not be removed by conda (tried all combinations). Not sure if this is related to above.

**Comment by soapy1** [comment]
@denfromufa is this still a problem for you?

**Comment by denfromufa** [comment]
https://imgur.com/HH9Q6x8.png
