### ISSUE TITLE
Issues during new environment creation

### ISSUE THREAD

**Issue by hendrasaputra** [conda/conda#1539]
After issuing following command:

```
conda create -n py34 python=3.4 anaconda
```

Following error is occured

```
    Traceback (most recent call last):
      File "D:\Anaconda\Scripts\conda-script.py", line 4, in <module>
        sys.exit(main())
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
        args_func(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
        args.func(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 49, in execute
        install.install(args, parser, 'create')
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 436, in install
        misc.append_env(prefix)
      File "D:\Anaconda\lib\site-packages\conda\misc.py", line 141, in append_env
        os.mkdir(dir_path)
    WindowsError: [Error 64] The specified network name is no longer available: 'P:\\.conda'
```

Following is `conda info` result

```
λ conda info
D:\Anaconda\lib\site-packages\binstar_client\utils\__init__.py:15: UserWarning: Module argparse was already imported from D:\Anaconda\lib\argparse.pyc, but d:\anaconda\lib\site-packages is being added to sys.path
  from pkg_resources import parse_version as pv
Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : not installed
       python version : 2.7.5.final.0
     requests version : 2.7.0
     root environment : D:\Anaconda  (writable)
  default environment : D:\Anaconda
     envs directories : D:\Anaconda\envs
        package cache : D:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by soapy1** [comment]
@hendrasaputra is this still an issue for you?
