### ISSUE TITLE
conda update conda/anaconda errors

### ISSUE THREAD

**Issue by ayswl** [conda/conda#1544]
conda update conda

Traceback (most recent call last):
  File "/Users/aiyas/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 397, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/history.py", line 63, in **exit**
    self.update()
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/history.py", line 84, in update
    self.write_changes(last, curr)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/history.py", line 203, in write_changes
    with open(self.path, 'a') as fo:
IOError: [Errno 13] Permission denied: '/Users/aiyas/miniconda/conda-meta/history'

conda install anaconda

Traceback (most recent call last):
  File "/Users/aiyas/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 397, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/plan.py", line 586, in execute_actions
    with History(actions[PREFIX]):
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/history.py", line 59, in **enter**
    self.update()
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/history.py", line 84, in update
    self.write_changes(last, curr)
  File "/Users/aiyas/miniconda/lib/python2.7/site-packages/conda/history.py", line 203, in write_changes
    with open(self.path, 'a') as fo:
IOError: [Errno 13] Permission denied: '/Users/aiyas/miniconda/conda-meta/history'

**Comment by soapy1** [comment]
@ayswl is this still and issue for you?
