### ISSUE TITLE
conda update error

### ISSUE THREAD

**Issue by tugrulxyz** [conda/conda#1551]
D:\apps\Anaconda\Scripts>conda update conda
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment D:\apps\Anaconda:

The following NEW packages will be INSTALLED:

```
conda-env: 2.4.2-py27_0
```

The following packages will be UPDATED:

```
conda:     3.7.0-py27_0 --> 3.16.0-py27_0
pyyaml:    3.11-py27_0  --> 3.11-py27_1
requests:  2.4.1-py27_0 --> 2.7.0-py27_0
```

Proceed ([y]/n)? y

Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  33%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "D:\apps\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\apps\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main

```
args_func(args, p)
```

  File "D:\apps\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args
_func
    args.func(args, p)
  File "D:\apps\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, i
n execute
    install.install(args, parser, 'update')
  File "D:\apps\Anaconda\lib\site-packages\conda\cli\install.py", line 387, in i
nstall
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\apps\Anaconda\lib\site-packages\conda\plan.py", line 587, in execute_
actions
    execute_plan(plan, index, verbose)
  File "D:\apps\Anaconda\lib\site-packages\conda\plan.py", line 571, in execute_
plan
    install.unlink(prefix, arg)
  File "D:\apps\Anaconda\lib\site-packages\conda\install.py", line 589, in unlin
k
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'D:\apps\Anaconda\conda-meta\conda
-3.7.0-py27_0.json'

D:\apps\Anaconda\Scripts>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.7.0
```

  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : D:\apps\Anaconda  (writable)
  default environment : D:\apps\Anaconda
     envs directories : D:\apps\Anaconda\envs
        package cache : D:\apps\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\Users\tugrulxyz.condarc
    is foreign system : False

**Comment by tugrulxyz** [comment]
Hi cant update conda.
any help appreciated
thanks
