### ISSUE TITLE
Anaconda Python Distribution Not Working After Upgrading to Windows 10

### ISSUE THREAD

**Issue by mohitpmathur** [conda/conda#1558]
I have bene using the Anaconda Python distribution for a while on my windows 8 machine and it was working fine. I upgraded my machine to Windows 10 yesterday, and since then it has stopped working.

First, I don't see the icons for launching iPython notebook, spyder or any other anaconda apps. I was able to start the launcher by typing 'Launcher' at the command prompt. Luncher screen displays th efollowing error when it comes up:
Error fetching package index
Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

When I launch iPython notebook from the launcher, I get the following error:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
    args.func(args, p)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\cli\main_run.py", line 80, in execute
    for pkg in get_package_versions(args.package):
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\api.py", line 168, in get_package_versions
    index = get_index()
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\fetch.py", line 256, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Users\Mohit\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 403, in result
    return self.__get_result()
  File "C:\Users\Mohit\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\conda\fetch.py", line 101, in fetch_repodata
    verify=config.ssl_verify)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Users\Mohit\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Users\Mohit\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Users\Mohit\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

--------------------------------------------------------------------

Here's my conda info
C:\Users\Mohit>conda info
Current conda install:

             platform : win-64
        conda version : 3.15.1
  conda-build version : 1.15.0
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Users\Mohit\Anaconda  (writable)
  default environment : C:\Users\Mohit\Anaconda
     envs directories : C:\Users\Mohit\Anaconda\envs
        package cache : C:\Users\Mohit\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Users\Mohit>
----------------------------------------------------------------------------------

Please let me know if it can be fixed or if I'd need to uninstall and reinstall everything.

Thanks
Mohit

**Comment by asmeurer** [comment]
See https://github.com/conda/conda/issues/1261

**Comment by mohitpmathur** [comment]
asmeurer,I'm not sure how #1261 is related to my issue. 

I had installed ndg-httpsclient a few weeks ago and everything was working fine. It was only when I upgraded to Windows 10 that all my icons disappeared and I cannot start iPython notebook. Trying to start the iPython notebook from the 'Launcher' gives the error above.

**Comment by yoavram** [comment]
try to do:
`conda uninstall --offline pyasn1` it works for me.

**Comment by mohitpmathur** [comment]
Thanks yoavram.. It worked!!

The Launcher comes up without any errors and can start the iPython notebook with no errors as well.

Even though Windows 10 upgrade seems to have removed all shortcuts for Anaconda programs, I can atleast start it form here now.

**Comment by CaptainPuppy** [comment]
`conda install -f launcher
conda install -f node-webkit`
This forces installing the launcher (whether or not it was already installed I'm assuming)
and will also restore your Start menu shortcuts in All Apps (Windows 10).
Background: I installed Anaconda on Win10 and lost the shortcuts after the last major update.
The same problem apparently was occuring in Ubuntu
[http://askubuntu.com/questions/385524/cant-find-spyder-or-ipython-notebook-applications-after-anaconda-install-xubun](url)

**Comment by mohitpmathur** [comment]
Windows 10 Anniversary update removed Anaconda shortcuts again.

Ran the command below and it fixed everything:
`"C:\Anaconda3\pythonw.exe" "C:\Anaconda3\Lib\_nsis.py" mkmenus
`
http://stackoverflow.com/questions/34131496/how-to-restore-shortcuts-to-anaconda-after-upgrading-to-windows-10

**Comment by MatDesros** [comment]
@mohitpmathur 
Thanks! Works perfectly.
