### ISSUE TITLE
conda update issue

### ISSUE THREAD

**Issue by hhajar** [conda/conda#1559]
An unexpected error has occurred, please consider sending the             |  14%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 203, in main
    if 'maximum recursion depth exceeded' in str(e):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    print_issue_message(e, use_json=use_json)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 609, in inner

  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute

  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    with common.json_progress_bars(json=args.json and not args.quiet):
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 531, in execute_actions
    with History(actions[inst.PREFIX]):
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 156, in execute_instructions

  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 97, in UNLINK_CMD

  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 615, in unlink
    placeholder, mode = has_prefix_files[f]
IOError: [Errno 2] No such file or directory: '//anaconda/conda-meta/conda-3.12.0-py27_0.json'
# 

Current conda install:

```
         platform : osx-64
    conda version : 3.16.0
```

  conda-build version : 1.3.5
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
Report is for conda 3.16.0.  Closing this issue, as outdated.  If you have a similar stack trace in a recent version of conda, please file a new issue.
