### ISSUE TITLE
spyder app update issue

### ISSUE THREAD

**Issue by hhajar** [conda/conda#1560]
```
spyder-app updated.

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 268, in install
    m['name'] == name]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by ccordoba12** [comment]
What happens if you start Spyder using a terminal (i.e. `cmd.exe`)? The thing is the launcher is kind of buggy right now and it's going to be replaced soon.

**Comment by asmeurer** [comment]
This looks like the same thing as https://github.com/conda/conda/issues/1460. There are probably permissions issues.
