### ISSUE TITLE
Can't install new packages.

### ISSUE THREAD

**Issue by Madsvj** [conda/conda#1564]
I have a simular problem to other people.
I just doesnt work calling "conda update requests" like suggested many places.

I get the following error:
C:\Users\MadsViborg>conda install loadmap
Fetching package metadata: ...An unexpected error has occurred, please consider
sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\MadsViborg\Anaconda\Scripts\conda-script.py", line 4, in <modul
e>
    sys.exit(main())
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\cli\main.py", line
194, in main
    args_func(args, p)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\cli\main.py", line
201, in args_func
    args.func(args, p)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\cli\main_install.py
", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\cli\install.py", li
ne 244, in install
    offline=args.offline)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\cli\common.py", lin
e 548, in get_index_trap
    return get_index(_args, *_kwargs)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\api.py", line 42, i
n get_index
    unknown=unknown)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\utils.py", line 119
, in **call**
    value = self.func(_args, *_kw)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\fetch.py", line 255
, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\concurrent\futures_base.
py", line 396, in result
    return self.**get_result()
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\concurrent\futures\thread
.py", line 55, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\fetch.py", line 65,
 in func
    res = f(_args, *_kwargs)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\conda\fetch.py", line 100
, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\sessions.py", li
ne 477, in get
    return self.request('GET', url, *_kwargs)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\sessions.py", li
ne 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\sessions.py", li
ne 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\adapters.py", li
ne 370, in send
    timeout=timeout
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\packages\urllib3
\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\packages\urllib3
\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\packages\urllib3
\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\packages\urllib3
\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 792, in __call**
    stGetValueDecoder, self, substrateFun
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 792, in **call**
    stGetValueDecoder, self, substrateFun
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\pyasn1\type\univ.py", lin
e 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Users\MadsViborg\Anaconda\lib\site-packages\pyasn1\type\namedtype.py"
, line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) n
ot found

Here is my conda info if needed:
C:\Users\MadsViborg>conda info
Current conda install:

```
         platform : win-64
    conda version : 3.16.0
```

  conda-build version : 1.17.0
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Users\MadsViborg\Anaconda  (writable)
  default environment : C:\Users\MadsViborg\Anaconda
     envs directories : C:\Users\MadsViborg\Anaconda\envs
        package cache : C:\Users\MadsViborg\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
See #1261. Try running

```
conda uninstall --offline pyasn1
```
