### ISSUE TITLE
netCDF4 1.1.9 conda install missing krb5 dependency

### ISSUE THREAD

**Issue by cbcunc** [conda/conda#1567]
ENVIRONMENT:
```
pylantic:~ cbc$ conda update --prefix /Users/cbc/anaconda anaconda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /Users/cbc/anaconda:
#
anaconda                  2.3.0                np19py27_0
pylantic:~ cbc$ conda update --all
Fetching package metadata: ....
Solving package specifications: .
# All requested packages already installed.
# packages in environment at /Users/cbc/anaconda:
#
_license                  1.1                      py27_0
abstract-rendering        0.5.1                np19py27_0
alabaster                 0.7.3                    py27_0
anaconda-client           1.0.2                    py27_0
appscript                 1.0.1                    py27_0
argcomplete               0.9.0                    py27_0
astropy                   1.0.4                np19py27_0
babel                     1.3                      py27_0
bcolz                     0.10.0               np19py27_0
beautiful-soup            4.3.2                    py27_0
binstar                   0.12                          2
bitarray                  0.8.1                    py27_0
blaze-core                0.8.2                np19py27_0
blz                       0.6.2                np19py27_1
bokeh                     0.9.3                np19py27_0
boto                      2.38.0                   py27_0
bottleneck                1.0.0                np19py27_0
cdecimal                  2.3                      py27_0
certifi                   14.05.14                 py27_0
cffi                      1.1.2                    py27_0
cloog                     0.18.0                        0
clyent                    0.4.0                    py27_0
colorama                  0.3.3                    py27_0
conda                     3.16.0                   py27_0
conda-build               1.17.0                   py27_0
conda-env                 2.4.2                    py27_0
configobj                 5.0.6                    py27_0
cryptography              0.9.3                    py27_0
curl                      7.43.0                        1
cython                    0.23.1                   py27_0
cytoolz                   0.7.3                    py27_0
datashape                 0.4.6                np19py27_0
decorator                 4.0.2                    py27_0
docutils                  0.12                     py27_0
dynd-python               0.6.5                np19py27_0
enum34                    1.0.4                    py27_0
fastcache                 1.0.2                    py27_0
flask                     0.10.1                   py27_1
freetype                  2.5.2                         2
funcsigs                  0.4                      py27_0
futures                   3.0.3                    py27_0
gcc                       4.8.2                         5
gevent                    1.0.1                    py27_0
gevent-websocket          0.9.3                    py27_0
gmp                       5.1.2                         6
greenlet                  0.4.7                    py27_0
grin                      1.2.1                    py27_1
h5py                      2.5.0                np19py27_3
hdf5                      1.8.15.1                      1
idna                      2.0                      py27_0
ipaddress                 1.0.7                    py27_0
ipykernel                 4.0.3                    py27_0
ipython                   4.0.0                    py27_0
ipython-notebook          4.0.4                    py27_0
ipython-qtconsole         4.0.1                    py27_0
ipython_genutils          0.1.0                    py27_0
isl                       0.12.2                        1
itsdangerous              0.24                     py27_0
jdcal                     1.0                      py27_0
jedi                      0.9.0                    py27_0
jinja2                    2.8                      py27_0
jpeg                      8d                            1
jsonschema                2.4.0                    py27_0
jupyter_client            4.0.0                    py27_0
jupyter_core              4.0.4                    py27_0
krb5                      1.13.2                        0
launcher                  1.0.0                         3
libdynd                   0.6.5                         0
libpng                    1.6.17                        0
libsodium                 0.4.5                         0
libtiff                   4.0.2                         1
libxml2                   2.9.2                         0
libxslt                   1.1.28                        2
llvmlite                  0.6.0                    py27_0
lxml                      3.4.4                    py27_0
markupsafe                0.23                     py27_0
matplotlib                1.4.3                np19py27_3
mistune                   0.7                      py27_0
mock                      1.3.0                    py27_0
mpc                       1.0.1                         0
mpfr                      3.1.2                         0
multipledispatch          0.4.8                    py27_0
nbconvert                 4.0.0                    py27_0
nbformat                  4.0.0                    py27_0
ncurses                   5.9                           0
networkx                  1.10                     py27_0
nltk                      3.0.4                np19py27_0
node-webkit               0.10.1                        0
nose                      1.3.7                    py27_0
notebook                  4.0.4                    py27_0
numba                     0.20.0               np19py27_0
numexpr                   2.4.3                np19py27_0
numpy                     1.9.2                    py27_0
odo                       0.3.3                np19py27_0
openpyxl                  2.0.2                    py27_0
openssl                   1.0.1k                        1
pandas                    0.16.2               np19py27_0
path.py                   7.6                      py27_0
patsy                     0.4.0                np19py27_0
pbr                       1.3.0                    py27_0
pcre                      8.31                          0
pep8                      1.6.2                    py27_0
pexpect                   3.3                      py27_0
pickleshare               0.5                      py27_0
pillow                    2.9.0                    py27_0
pip                       7.1.2                    py27_0
ply                       3.6                      py27_0
psutil                    2.2.1                    py27_0
ptyprocess                0.4                      py27_0
py                        1.4.30                   py27_0
pyasn1                    0.1.7                    py27_0
pyaudio                   0.2.7                    py27_0
pycosat                   0.6.1                    py27_0
pycparser                 2.14                     py27_0
pycrypto                  2.6.1                    py27_0
pycurl                    7.19.5.1                 py27_2
pyflakes                  0.9.2                    py27_0
pygments                  2.0.2                    py27_0
pyopenssl                 0.15.1                   py27_1
pyparsing                 2.0.3                    py27_0
pyqt                      4.11.3                   py27_0
pytables                  3.2.1.1              np19py27_0
pytest                    2.7.2                    py27_0
python                    2.7.10                        0
python-dateutil           2.4.2                    py27_0
python.app                1.2                      py27_4
pytz                      2015.4                   py27_0
pyyaml                    3.11                     py27_1
pyzmq                     14.7.0                   py27_0
qt                        4.8.6                         3
qtconsole                 4.0.1                    py27_0
readline                  6.2                           2
redis                     2.6.9                         0
redis-py                  2.10.3                   py27_0
requests                  2.7.0                    py27_0
rope                      0.9.4                    py27_1
runipy                    0.1.3                    py27_0
scikit-image              0.11.3               np19py27_0
scikit-learn              0.16.1               np19py27_0
scipy                     0.16.0               np19py27_1
setuptools                18.1                     py27_0
simplegeneric             0.8.1                    py27_0
sip                       4.16.5                   py27_0
six                       1.9.0                    py27_0
snowballstemmer           1.2.0                    py27_0
sockjs-tornado            1.0.1                    py27_0
sphinx                    1.3.1                    py27_0
sphinx_rtd_theme          0.1.7                    py27_0
spyder                    2.3.6                    py27_0
spyder-app                2.3.6                    py27_0
sqlalchemy                1.0.8                    py27_0
sqlite                    3.8.4.1                       1
ssl_match_hostname        3.4.0.2                  py27_0
statsmodels               0.6.1                np19py27_0
sympy                     0.7.6                    py27_0
terminado                 0.5                      py27_0
tk                        8.5.18                        0
toolz                     0.7.4                    py27_0
tornado                   4.2.1                    py27_0
traitlets                 4.0.0                    py27_0
ujson                     1.33                     py27_0
unicodecsv                0.9.4                    py27_0
werkzeug                  0.10.4                   py27_0
wheel                     0.24.0                   py27_0
xlrd                      0.9.4                    py27_0
xlsxwriter                0.7.3                    py27_0
xlwings                   0.3.6                    py27_0
xlwt                      1.0.0                    py27_0
yaml                      0.1.6                         0
zeromq                    4.0.5                         0
zlib                      1.2.8                         0
```

BAD:
```
pylantic:~ cbc$ conda create -n netcdf anaconda netCDF4
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/cbc/anaconda/envs/netcdf:

The following NEW packages will be INSTALLED:

    _license:           1.1-py27_0
    abstract-rendering: 0.5.1-np19py27_0
    alabaster:          0.7.3-py27_0
    anaconda:           2.3.0-np19py27_0
    appscript:          1.0.1-py27_0
    argcomplete:        0.8.9-py27_0
    astropy:            1.0.3-np19py27_0
    babel:              1.3-py27_0
    bcolz:              0.9.0-np19py27_0
    beautiful-soup:     4.3.2-py27_0
    binstar:            0.11.0-py27_0
    bitarray:           0.8.1-py27_0
    blaze-core:         0.8.0-np19py27_0
    blz:                0.6.2-np19py27_1
    bokeh:              0.9.0-np19py27_0
    boto:               2.38.0-py27_0
    bottleneck:         1.0.0-np19py27_0
    cdecimal:           2.3-py27_0
    certifi:            14.05.14-py27_0
    cffi:               1.1.0-py27_0
    clyent:             0.3.4-py27_0
    colorama:           0.3.3-py27_0
    configobj:          5.0.6-py27_0
    cryptography:       0.9.1-py27_0
    curl:               7.43.0-0
    cython:             0.22.1-py27_0
    cytoolz:            0.7.3-py27_0
    datashape:          0.4.5-np19py27_0
    decorator:          3.4.2-py27_0
    docutils:           0.12-py27_0
    dynd-python:        0.6.5-np19py27_0
    enum34:             1.0.4-py27_0
    fastcache:          1.0.2-py27_0
    flask:              0.10.1-py27_1
    freetype:           2.5.2-2
    funcsigs:           0.4-py27_0
    gevent:             1.0.1-py27_0
    gevent-websocket:   0.9.3-py27_0
    greenlet:           0.4.7-py27_0
    grin:               1.2.1-py27_1
    h5py:               2.5.0-np19py27_3
    hdf5:               1.8.15.1-1
    idna:               2.0-py27_0
    ipaddress:          1.0.7-py27_0
    ipython:            3.2.0-py27_0
    ipython-notebook:   3.2.0-py27_0
    ipython-qtconsole:  3.2.0-py27_0
    itsdangerous:       0.24-py27_0
    jdcal:              1.0-py27_0
    jedi:               0.8.1-py27_0
    jinja2:             2.7.3-py27_1
    jpeg:               8d-1
    jsonschema:         2.4.0-py27_0
    launcher:           1.0.0-3
    libdynd:            0.6.5-0
    libnetcdf:          4.3.3.1-1
    libpng:             1.6.17-0
    libsodium:          0.4.5-0
    libtiff:            4.0.2-1
    libxml2:            2.9.2-0
    libxslt:            1.1.28-2
    llvmlite:           0.5.0-py27_0
    lxml:               3.4.4-py27_0
    markupsafe:         0.23-py27_0
    matplotlib:         1.4.3-np19py27_2
    mistune:            0.5.1-py27_1
    mock:               1.0.1-py27_0
    multipledispatch:   0.4.7-py27_0
    netcdf4:            1.1.9-np19py27_0
    networkx:           1.9.1-py27_0
    nltk:               3.0.3-np19py27_0
    node-webkit:        0.10.1-0
    nose:               1.3.7-py27_0
    numba:              0.19.1-np19py27_0
    numexpr:            2.4.3-np19py27_0
    numpy:              1.9.2-py27_0
    odo:                0.3.2-np19py27_0
    openpyxl:           1.8.5-py27_0
    openssl:            1.0.1k-1
    pandas:             0.16.2-np19py27_0
    patsy:              0.3.0-np19py27_0
    pep8:               1.6.2-py27_0
    pillow:             2.8.2-py27_0
    pip:                7.0.3-py27_0
    ply:                3.6-py27_0
    psutil:             2.2.1-py27_0
    ptyprocess:         0.4-py27_0
    py:                 1.4.27-py27_0
    pyasn1:             0.1.7-py27_0
    pyaudio:            0.2.7-py27_0
    pycosat:            0.6.1-py27_0
    pycparser:          2.14-py27_0
    pycrypto:           2.6.1-py27_0
    pycurl:             7.19.5.1-py27_2
    pyflakes:           0.9.2-py27_0
    pygments:           2.0.2-py27_0
    pyopenssl:          0.15.1-py27_1
    pyparsing:          2.0.3-py27_0
    pyqt:               4.11.3-py27_0
    pytables:           3.2.0-np19py27_0
    pytest:             2.7.1-py27_0
    python:             2.7.10-0
    python-dateutil:    2.4.2-py27_0
    python.app:         1.2-py27_4
    pytz:               2015.4-py27_0
    pyyaml:             3.11-py27_1
    pyzmq:              14.7.0-py27_0
    qt:                 4.8.6-3
    readline:           6.2-2
    redis:              2.6.9-0
    redis-py:           2.10.3-py27_0
    requests:           2.7.0-py27_0
    rope:               0.9.4-py27_1
    runipy:             0.1.3-py27_0
    scikit-image:       0.11.3-np19py27_0
    scikit-learn:       0.16.1-np19py27_0
    scipy:              0.15.1-np19py27_0
    setuptools:         17.1.1-py27_0
    sip:                4.16.5-py27_0
    six:                1.9.0-py27_0
    snowballstemmer:    1.2.0-py27_0
    sockjs-tornado:     1.0.1-py27_0
    sphinx:             1.3.1-py27_0
    sphinx_rtd_theme:   0.1.7-py27_0
    spyder:             2.3.5.2-py27_0
    spyder-app:         2.3.5.2-py27_0
    sqlalchemy:         1.0.5-py27_0
    sqlite:             3.8.4.1-1
    ssl_match_hostname: 3.4.0.2-py27_0
    statsmodels:        0.6.1-np19py27_0
    sympy:              0.7.6-py27_0
    terminado:          0.5-py27_0
    tk:                 8.5.18-0
    toolz:              0.7.2-py27_0
    tornado:            4.2-py27_0
    ujson:              1.33-py27_0
    unicodecsv:         0.9.4-py27_0
    werkzeug:           0.10.4-py27_0
    xlrd:               0.9.3-py27_0
    xlsxwriter:         0.7.3-py27_0
    xlwings:            0.3.5-py27_0
    xlwt:               1.0.0-py27_0
    yaml:               0.1.6-0
    zeromq:             4.0.5-0
    zlib:               1.2.8-0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|######################################################################################| 100%
#
# To activate this environment, use:
# $ source activate netcdf
#
# To deactivate this environment, use:
# $ source deactivate
#
pylantic:~ cbc$ source activate netcdf
discarding /Users/cbc/anaconda/bin from PATH
prepending /Users/cbc/anaconda/envs/netcdf/bin to PATH
(netcdf)pylantic:~ cbc$ python
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import netCDF4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cbc/anaconda/envs/netcdf/lib/python2.7/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: dlopen(/Users/cbc/anaconda/envs/netcdf/lib/python2.7/site-packages/netCDF4/_netCDF4.so, 2): Library not loaded: @loader_path/./libgssapi_krb5.2.2.dylib
  Referenced from: /Users/cbc/anaconda/envs/netcdf/lib/libnetcdf.7.dylib
  Reason: image not found
>>>
```

REASON:
```
(netcdf)pylantic:~ cbc$ otool -L ~/anaconda/envs/netcdf/lib/python2.7/site-packages/netCDF4/_netCDF4.so
/Users/cbc/anaconda/envs/netcdf/lib/python2.7/site-packages/netCDF4/_netCDF4.so:
	@loader_path/../../../libnetcdf.7.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	/usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1094.0.0)
(netcdf)pylantic:~ cbc$ otool -L ~/anaconda/envs/netcdf/lib/libnetcdf.7.dylib
/Users/cbc/anaconda/envs/netcdf/lib/libnetcdf.7.dylib:
	libnetcdf.7.dylib (compatibility version 10.0.0, current version 10.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 159.1.0)
	@loader_path/./libssl.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/./libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	@loader_path/./libgssapi_krb5.2.2.dylib (compatibility version 2.0.0, current version 2.2.0)
	/usr/lib/libresolv.9.dylib (compatibility version 1.0.0, current version 46.1.0)
	@loader_path/./libhdf5_hl.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@loader_path/./libhdf5.10.dylib (compatibility version 11.0.0, current version 11.1.0)
	@loader_path/./libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	@loader_path/./libcurl.4.dylib (compatibility version 8.0.0, current version 8.0.0)
(netcdf)pylantic:~ cbc$ ls ~/anaconda/envs/netcdf/lib/libgssapi_krb5*
ls: /Users/cbc/anaconda/envs/netcdf/lib/libgssapi_krb5*: No such file or directory
(netcdf)pylantic:~ cbc$
```

GOOD:
```
pylantic:~ cbc$ conda create -n netcdf anaconda krb5 netCDF4
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/cbc/anaconda/envs/netcdf:

The following NEW packages will be INSTALLED:

    _license:           1.1-py27_0
    abstract-rendering: 0.5.1-np19py27_0
    alabaster:          0.7.3-py27_0
    anaconda:           2.3.0-np19py27_0
    appscript:          1.0.1-py27_0
    argcomplete:        0.8.9-py27_0
    astropy:            1.0.3-np19py27_0
    babel:              1.3-py27_0
    bcolz:              0.9.0-np19py27_0
    beautiful-soup:     4.3.2-py27_0
    binstar:            0.11.0-py27_0
    bitarray:           0.8.1-py27_0
    blaze-core:         0.8.0-np19py27_0
    blz:                0.6.2-np19py27_1
    bokeh:              0.9.0-np19py27_0
    boto:               2.38.0-py27_0
    bottleneck:         1.0.0-np19py27_0
    cdecimal:           2.3-py27_0
    certifi:            14.05.14-py27_0
    cffi:               1.1.0-py27_0
    clyent:             0.3.4-py27_0
    colorama:           0.3.3-py27_0
    configobj:          5.0.6-py27_0
    cryptography:       0.9.1-py27_0
    curl:               7.43.0-0
    cython:             0.22.1-py27_0
    cytoolz:            0.7.3-py27_0
    datashape:          0.4.5-np19py27_0
    decorator:          3.4.2-py27_0
    docutils:           0.12-py27_0
    dynd-python:        0.6.5-np19py27_0
    enum34:             1.0.4-py27_0
    fastcache:          1.0.2-py27_0
    flask:              0.10.1-py27_1
    freetype:           2.5.2-2
    funcsigs:           0.4-py27_0
    gevent:             1.0.1-py27_0
    gevent-websocket:   0.9.3-py27_0
    greenlet:           0.4.7-py27_0
    grin:               1.2.1-py27_1
    h5py:               2.5.0-np19py27_3
    hdf5:               1.8.15.1-1
    idna:               2.0-py27_0
    ipaddress:          1.0.7-py27_0
    ipython:            3.2.0-py27_0
    ipython-notebook:   3.2.0-py27_0
    ipython-qtconsole:  3.2.0-py27_0
    itsdangerous:       0.24-py27_0
    jdcal:              1.0-py27_0
    jedi:               0.8.1-py27_0
    jinja2:             2.7.3-py27_1
    jpeg:               8d-1
    jsonschema:         2.4.0-py27_0
    krb5:               1.13.2-0
    launcher:           1.0.0-3
    libdynd:            0.6.5-0
    libnetcdf:          4.3.3.1-1
    libpng:             1.6.17-0
    libsodium:          0.4.5-0
    libtiff:            4.0.2-1
    libxml2:            2.9.2-0
    libxslt:            1.1.28-2
    llvmlite:           0.5.0-py27_0
    lxml:               3.4.4-py27_0
    markupsafe:         0.23-py27_0
    matplotlib:         1.4.3-np19py27_2
    mistune:            0.5.1-py27_1
    mock:               1.0.1-py27_0
    multipledispatch:   0.4.7-py27_0
    netcdf4:            1.1.9-np19py27_0
    networkx:           1.9.1-py27_0
    nltk:               3.0.3-np19py27_0
    node-webkit:        0.10.1-0
    nose:               1.3.7-py27_0
    numba:              0.19.1-np19py27_0
    numexpr:            2.4.3-np19py27_0
    numpy:              1.9.2-py27_0
    odo:                0.3.2-np19py27_0
    openpyxl:           1.8.5-py27_0
    openssl:            1.0.1k-1
    pandas:             0.16.2-np19py27_0
    patsy:              0.3.0-np19py27_0
    pep8:               1.6.2-py27_0
    pillow:             2.8.2-py27_0
    pip:                7.0.3-py27_0
    ply:                3.6-py27_0
    psutil:             2.2.1-py27_0
    ptyprocess:         0.4-py27_0
    py:                 1.4.27-py27_0
    pyasn1:             0.1.7-py27_0
    pyaudio:            0.2.7-py27_0
    pycosat:            0.6.1-py27_0
    pycparser:          2.14-py27_0
    pycrypto:           2.6.1-py27_0
    pycurl:             7.19.5.1-py27_2
    pyflakes:           0.9.2-py27_0
    pygments:           2.0.2-py27_0
    pyopenssl:          0.15.1-py27_1
    pyparsing:          2.0.3-py27_0
    pyqt:               4.11.3-py27_0
    pytables:           3.2.0-np19py27_0
    pytest:             2.7.1-py27_0
    python:             2.7.10-0
    python-dateutil:    2.4.2-py27_0
    python.app:         1.2-py27_4
    pytz:               2015.4-py27_0
    pyyaml:             3.11-py27_1
    pyzmq:              14.7.0-py27_0
    qt:                 4.8.6-3
    readline:           6.2-2
    redis:              2.6.9-0
    redis-py:           2.10.3-py27_0
    requests:           2.7.0-py27_0
    rope:               0.9.4-py27_1
    runipy:             0.1.3-py27_0
    scikit-image:       0.11.3-np19py27_0
    scikit-learn:       0.16.1-np19py27_0
    scipy:              0.15.1-np19py27_0
    setuptools:         17.1.1-py27_0
    sip:                4.16.5-py27_0
    six:                1.9.0-py27_0
    snowballstemmer:    1.2.0-py27_0
    sockjs-tornado:     1.0.1-py27_0
    sphinx:             1.3.1-py27_0
    sphinx_rtd_theme:   0.1.7-py27_0
    spyder:             2.3.5.2-py27_0
    spyder-app:         2.3.5.2-py27_0
    sqlalchemy:         1.0.5-py27_0
    sqlite:             3.8.4.1-1
    ssl_match_hostname: 3.4.0.2-py27_0
    statsmodels:        0.6.1-np19py27_0
    sympy:              0.7.6-py27_0
    terminado:          0.5-py27_0
    tk:                 8.5.18-0
    toolz:              0.7.2-py27_0
    tornado:            4.2-py27_0
    ujson:              1.33-py27_0
    unicodecsv:         0.9.4-py27_0
    werkzeug:           0.10.4-py27_0
    xlrd:               0.9.3-py27_0
    xlsxwriter:         0.7.3-py27_0
    xlwings:            0.3.5-py27_0
    xlwt:               1.0.0-py27_0
    yaml:               0.1.6-0
    zeromq:             4.0.5-0
    zlib:               1.2.8-0

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|######################################################################################| 100%
#
# To activate this environment, use:
# $ source activate netcdf
#
# To deactivate this environment, use:
# $ source deactivate
#
pylantic:~ cbc$ source activate netcdf
discarding /Users/cbc/anaconda/bin from PATH
prepending /Users/cbc/anaconda/envs/netcdf/bin to PATH
(netcdf)pylantic:~ cbc$ python
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import netCDF4
>>>
```

I would submit a PR, but http://anaconda.org/anaconda/netcdf4/1.1.9/download/osx-64/netcdf4-1.1.9-np19py27_0.tar.bz2 returns a 404. The place to file an issue on a main repo recipe is not obvious.

**Comment by groutr** [comment]
Thanks for the very detailed bug report.  anaconda-issues repo is typically the place to report things about packages.

**Comment by cbcunc** [comment]
Thanks @groutr . I just submitted https://github.com/ContinuumIO/anaconda-issues/issues/432 and am closing this issue.
