### ISSUE TITLE
Cannot use virtualenv with Python 3.4 on Linux

### ISSUE THREAD

**Issue by mivade** [conda/conda#1573]
When I try to use `virtualenv`, I get output like this:

```
Using base prefix '/home/mvd/miniconda3'
New python executable in env/bin/python3
Also creating executable in env/bin/python
Installing setuptools, pip, wheel...
  Complete output from command /home/mvd/src/foreig...raph/env/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel:
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/__init__.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/commands/__init__.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/commands/completion.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/basecommand.py", line 20, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/req/__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/req/req_install.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 20, in <module>
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv_support/pip-7.1.0-py2.py3-none-any.whl/pip/_vendor/distlib/markers.py", line 48, in Evaluator
  File "/home/mvd/miniconda3/lib/python3.4/platform.py", line 1319, in python_implementation
    return _sys_version()[0]
  File "/home/mvd/miniconda3/lib/python3.4/platform.py", line 1282, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.4.2 (default, Oct  8 2014, 10:47:48) \n[GCC 4.9.1]'
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/mvd/miniconda3/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv.py", line 832, in main
    symlink=options.symlink)
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv.py", line 1004, in create_environment
    install_wheel(to_install, py_executable, search_dirs)
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv.py", line 969, in install_wheel
    'PIP_NO_INDEX': '1'
  File "/home/mvd/miniconda3/lib/python3.4/site-packages/virtualenv.py", line 910, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/mvd/src/foreig...raph/env/bin/python3 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip wheel failed with error code 1
```

There is no error when I try to do this under a Python 2.7 environment.

I know that I could alternatively use `conda create` to create a similar type of environment, but there are times when using a virtualenv is useful (e.g., test suites often use them).

**Comment by wcooley** [comment]
@mivade Could you try setting your `LD_LIBRARY_PATH` to the `lib` directory in your conda env and seeing if that works? I suspect you're hitting the "virtualenv doesn't copy libpython*" bug pypa/virtualenv#216

```
$ LD_LIBRARY_PATH=/home/mvd/src/foreig...raph/env/lib virtualenv ...
```

Not getting an error on 2.7 might be a red herring -- you might still be using the "wrong" `libpython`; it just happens to be compatible enough to work. (You might find that `virtual-env/py27/bin/python -V` gives different output from `conda-env/py27/bin/python -V`.)

You can see if this is the case by running `ldd virtual-env/py27/bin/python` and seeing where `libpython*` points. You can also see it in action with the [LD_DEBUG](http://www.bnikolic.co.uk/blog/linux-ld-debug.html) feature:

```
$ LD_DEBUG=libs LD_DEBUG_OUT=/tmp/ld-debug-python conda-env/py27/bin/python -c ''
```

**Comment by mivade** [comment]
I gave that a try, although I have since upgraded my default environment to Python 3.5, so had to run it in a separate Python 3.4 environment. I still get the same errors.

I have also since indirectly solved this problem by adding functions to my `~/.bashrc` which let me switch between using miniconda and the system Python:

```bash
export CONDA_PATH=$HOME/miniconda3/bin
export BASE_PATH=$HOME/bin:$HOME/.local/bin:$PATH

# Macros for switching between conda and system Python
function condafy {
    export PATH=$CONDA_PATH:$BASE_PATH
}

function noconda {
    export PATH=$BASE_PATH
}

# Use conda by default
condafy
```

This works well enough considering I mostly use virtualenv for throwaway tests of external things (for which I find a local environment more useful than the global environment model that conda uses) or unit testing with tox (although that is often outsourced to TravisCI and the like these days).

**Comment by rscohn2** [comment]
I verified that anaconda 2.7 looks like it is working with virtualenv, but is actually getting the wrong libpython, which happens to be on the library path.

**Comment by mingwandroid** [comment]
We released a new `virtualenv` package with patches to allow it to find the correct libpython. Please test and close this if it works for you.

**Comment by mivade** [comment]
This appears to work. Thanks!

**Comment by kalefranz** [comment]
We did? I didn't know that. Awesome!!!!!!
