### ISSUE TITLE
Updating Anaconda

### ISSUE THREAD

**Issue by rambles** [conda/conda#1575]
After issuing 'conda update anaconda':-

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 244, in install
    offline=args.offline)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 400, in result
    return self.__get_result()
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_base.py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\_compat.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "C:\Anaconda\lib\site-packages\concurrent\futures\thread.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) not found

From 'conda info':

Current conda install:

             platform : win-32
        conda version : 3.16.0
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Thanks.

**Comment by asmeurer** [comment]
See https://github.com/conda/conda/issues/1261. Try running

```
conda uninstall --offline pyasn1
```

**Comment by rambles** [comment]
I've just issued the 'conda uninstall --offline pyasn1' command as suggested.  I then retried 'conda update anaconda'.  The error now reads:-

C:\Users\rzb48746\Documents\GitGSK>conda update anaconda
C:\Anaconda\lib\site-packages\ndg\httpsclient\subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
C:\Anaconda\lib\site-packages\ndg\httpsclient\ssl_peer_verification.py:24: UserWarning: SubjectAltName support is disabled - check pyasn1 package installation to enable
  warnings.warn(SUBJ_ALT_NAME_SUPPORT_MSG)
C:\Anaconda\lib\site-packages\ndg\httpsclient\subj_alt_name.py:22: UserWarning: Error importing pyasn1, subjectAltName check for SSL peer verification will be disabled.  Import error is: No module named pyasn1.type
  warnings.warn(import_error_msg)
Fetching package metadata: C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning

Indeed, nothing will install now.  'Conda install ... ' produces the same error above.

**Comment by rambles** [comment]
Hi

I tried the solution and it half worked.  I've updated the thread with my
comments.  Could you reopen the issue?

Thanks, Rich

**Comment by asmeurer** [comment]
The warnings, though they print a lot to the screen, shouldn't prevent things from working.

**Comment by rambles** [comment]
You're right, installing and uninstalling works fine.  Thanks.
