### ISSUE TITLE
conda list fails

### ISSUE THREAD

**Issue by jensenp77** [conda/conda#1576]
> conda list
> fails with the following
# packages in environment at /home/paul.jensen/linux/miniconda3/envs/edgar:
# 

Traceback (most recent call last):
  File "/home/paul.jensen/linux/miniconda3/envs/edgar/bin/pip", line 4, in <module>
    from pip import main
  File "/home/paul.jensen/linux/miniconda3/envs/edgar/lib/python3.4/site-packages/pip/**init**.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/paul.jensen/linux/miniconda3/envs/edgar/lib/python3.4/site-packages/pip/utils/**init**.py", line 19, in <module>
    from pip.locations import (
  File "/home/paul.jensen/linux/miniconda3/envs/edgar/lib/python3.4/site-packages/pip/locations.py", line 11, in <module>
    from distutils.command.install import install, SCHEME_KEYS  # noqa
  File "/home/paul.jensen/linux/miniconda3/envs/edgar/lib/python3.4/distutils/command/install.py", line 9, in <module>
    from distutils.core import Command
ImportError: No module named 'distutils.core'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/paul.jensen/linux/miniconda3/envs/edgar/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 203, in execute
    exitcode = print_packages(prefix, regex, format, piplist=args.pip, json=args.json)
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 161, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/home/paul.jensen/linux/miniconda3/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/home/paul.jensen/linux/miniconda3/envs/edgar/bin/python', '/home/paul.jensen/linux/miniconda3/envs/edgar/bin/pip', '-V']' returned non-zero exit status 1

(edgar)[paul.jensen@SPOTLX029 ~]$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.16.0
```

  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/paul.jensen/linux/miniconda3  (writable)
  default environment : /home/paul.jensen/linux/miniconda3/envs/edgar
     envs directories : /home/paul.jensen/linux/miniconda3/envs
        package cache : /home/paul.jensen/linux/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
I can't reproduce this issue with the newest version of conda. Please `conda update conda` and reopen this issue if the problem persists
