### ISSUE TITLE
Race condition on `conda install` the same package

### ISSUE THREAD

**Issue by frol** [conda/conda#1579]
I have a concurrent Jenkins jobs that tries to install/update the same package at the same time and I almost always face this crash once the package is getting update:

```
+ conda install --yes -c mychannel mypackage
Fetching package metadata: ..................
Solving package specifications: .
Package plan for installation in environment /home/jenkins/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mypackage-0.1        |          py27_45          41 KB

The following packages will be UPDATED:

    mypackage: 0.1-py27_44 --> 0.1-py27_45

Fetching packages ...
    LOCKERROR: It looks like conda is already doing something.
    The lock /home/jenkins/anaconda/pkgs/.conda_lock-74141 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 1 seconds
    LOCKERROR: It looks like conda is already doing something.
    The lock /home/jenkins/anaconda/pkgs/.conda_lock-74141 was found. Wait for it to finish before continuing.
    If you are sure that conda is not running, remove it and try again.
    You can also use: $ conda clean --lock
Sleeping for 2 seconds
mypackage   0% |                              | ETA:  --:--:--   0.00  B/s
mypackage  39% |############                   | ETA:  0:00:00  84.86 kB/s
mypackage  78% |########################       | ETA:  0:00:00  68.70 kB/s
mypackage 100% |###############################| ETA:  0:00:00  86.17 kB/s
mypackage 100% |###############################| Time: 0:00:00  86.05 kB/s
Extracting packages ...
[                    ]|                                                  |   0%
[mypackage     ]|                                                  |   0%
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|                                                  |   0%
[mypackage     ]|                                                  |   0%
[mypackage     ]|                                                  |   0%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/jenkins/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 415, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/home/jenkins/anaconda/lib/python2.7/site-packages/conda/install.py", line 671, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/home/jenkins/anaconda/conda-meta/mypackage-0.1-py27_44.json'
```

This happens because while this `conda install` instance was locked, another one had already updated `mypackage` and removed old `conda-meta`.

**Comment by asmeurer** [comment]
I guess the locking should happen at a higher level.

**Comment by frol** [comment]
@asmeurer Traceback in an application is a problem of the application. It still has to be fixed at least with a proper error handling.

**Comment by asmeurer** [comment]
I mean a higher level inside of conda. I'm not saying this shouldn't be fixed.

**Comment by frol** [comment]
@asmeurer I see. I was confused, sorry for that.

**Comment by kalefranz** [comment]
We reintroduced this race condition in 4.3 because we removed the prefix lock.  There are two open PRs to bring locking back for the unlink-link transaction.
