### ISSUE TITLE
Error when installing coursera-dl from auto channel.

### ISSUE THREAD

**Issue by jpeel** [conda/conda#1581]
I just tried installing coursera-dl with command:
conda install --channel https://conda.anaconda.org/auto coursera-dl

and ended up with the following traceback.

Traceback (most recent call last):
  File "/home/storage/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 415, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/storage/anaconda/lib/python2.7/site-packages/conda/install.py", line 588, in link
    os.makedirs(dst_dir)
  File "/home/storage/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/storage/anaconda/lib/python2.7/site-packages/beautifulsoup4-4.3.2-py2.7.egg-info'

**Comment by soapy1** [comment]
@jpeel is this still an issue for you?
