### ISSUE TITLE
Conda refuses to update

### ISSUE THREAD

**Issue by bechhof** [conda/conda#1582]
The output when trying conda update jupyter

Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "//anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "//anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "//anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "//anaconda/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "//anaconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "//anaconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "//anaconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "//anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "//anaconda/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, *_kwargs)
  File "//anaconda/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "//anaconda/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "//anaconda/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 244, in install
    offline=args.offline)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 548, in get_index_trap
    return get_index(_args, *_kwargs)
  File "//anaconda/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "//anaconda/lib/python3.4/site-packages/conda/utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "//anaconda/lib/python3.4/site-packages/conda/fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "//anaconda/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "//anaconda/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "//anaconda/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "//anaconda/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "//anaconda/lib/python3.4/site-packages/conda/fetch.py", line 150, in fetch_repodata
    stderrlog.info("SSL verification error %s\n" % e.message)
AttributeError: 'SSLError' object has no attribute 'message'

Current conda install:

```
         platform : osx-64
    conda version : 3.16.0
```

  conda-build version : 1.16.0
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by asmeurer** [comment]
This error has been fixed. Does `conda update conda` work?

**Comment by bechhof** [comment]
Didn't work initially…had to remove everything and reinstall.
