### ISSUE TITLE
Spyder App update issue Mac OS X Yosemite 10.10.5

### ISSUE THREAD

**Issue by vkkumar** [conda/conda#1592]
Traceback (most recent call last):
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 415, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Users/vaidyanatk/anaconda/lib/python3.4/site-packages/conda/install.py", line 671, in unlink
    with open(meta_path) as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vaidyanatk/anaconda/conda-meta/pyflakes-0.8.1-py34_0.json'

Close

**Comment by ccordoba12** [comment]
What command did you run before getting this error?

**Comment by vkkumar** [comment]
I used the update feature from the launcher application.

**Comment by ccordoba12** [comment]
The launcher is not working correctly in all situations, but a new version will be available soon.

Please use the command line to do the update.

**Comment by vkkumar** [comment]
OK. I will. Thank you.

**Comment by ccordoba12** [comment]
Ok, thanks.
