### ISSUE TITLE
Update error!

### ISSUE THREAD

**Issue by checkthenet** [conda/conda#1596]
Traceback (most recent call last):
  File "/Users/myname/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    common.error_and_exit(str(e), json=use_json)
  File "/Users/myname/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
  File "/Users/myname/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 387, in install
    if plan.nothing_to_do(actions):
  File "/Users/myname/anaconda/lib/python2.7/site-packages/conda/plan.py", line 587, in execute_actions
  File "/Users/myname/anaconda/lib/python2.7/site-packages/conda/plan.py", line 571, in execute_plan
  File "/Users/myname/anaconda/lib/python2.7/site-packages/conda/install.py", line 574, in unlink
    if not run_script(source_dir, dist, 'pre-link', prefix):
IOError: [Errno 2] No such file or directory: '/Users/myname/anaconda/conda-meta/conda-3.7.0-py27_0.json'

And the kernel dies, if I try to run a program that uses gurobipy.
What can I do?

Thanks!

**Comment by soapy1** [comment]
@checkthenet is this still an issue for you?
