### ISSUE TITLE
Bad tarballs cause conda install to abort with a stack-trace

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1598]
I am reporting this because conda told me to:

``` bash
# sudo -u wakari /opt/wakari/anaconda/bin/conda install  --no-deps --offline  -p /opt/wa
kari/anaconda --dry-run `cat ~/.py27_packages.txt`
[      COMPLETE      ]|#############################################################################################| 100%
Extracting packages ...
An unexpected error has occurred, please consider sending the###########################################            |  87%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 219, in install
    verbose=not args.quiet)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/misc.py", line 213, in install_local_packages
    execute_actions(actions, verbose=verbose)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/install.py", line 454, in extract
    t = tarfile.open(path + '.tar.bz2')
  File "/opt/wakari/anaconda/lib/python2.7/tarfile.py", line 1672, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

And then, as requested, `conda info`:

``` bash
# sudo -u wakari /opt/wakari/anaconda/bin/conda info
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /opt/wakari/anaconda  (writable)
  default environment : /opt/wakari/anaconda
     envs directories : /opt/wakari/anaconda/envs
        package cache : /opt/wakari/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /opt/wakari/anaconda/.condarc
    is foreign system : False
```

Updating conda to the latest version still bombs out and it still asks me to report it as a bug:

``` bash
Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 207, in install
    verbose=not args.quiet)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/misc.py", line 215, in install_local_packages
    execute_actions(actions, verbose=verbose)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/install.py", line 454, in extract
    t = tarfile.open(path + '.tar.bz2')
  File "/opt/wakari/anaconda/lib/python2.7/tarfile.py", line 1672, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

This doesn't indicate _which_ file could not be opened successfully.  It turns out it was because I ended up with a duff tarball in my CAS-installer and then subsequently in my `anaconda/pkgs` package cache dir.  But it took some digging to figure out that was the problem.  FWIW, this was caused by the Anaconda Server bug https://github.com/Anaconda-Server/anaconda-server/issues/608 which gave me the duff tarball in the first place.

**Comment by kalefranz** [comment]
Bug report is for conda 3.14.1, which is no longer maintained. If you're still having this issue, please file a new report with an updated stack trace.
