### ISSUE TITLE
Dependency problem after change in conda update

### ISSUE THREAD

**Issue by Chroxvi** [conda/conda#1621]
This issue relates to a missing `libgfortran.so.1` dependency for `numpy==1.8` (and possibly other packages).

Using the latest (as of Sep 16, 2015) Python 2 based Miniconda on linux-64 to install `numpy`, I get:

```
$ bash Miniconda-latest-Linux-x86_64.sh
...
installing: python-2.7.10-0 ...
installing: conda-env-2.4.2-py27_0 ...
installing: openssl-1.0.1k-1 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.7.0-py27_0 ...
installing: sqlite-3.8.4.1-1 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-3.16.0-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
````
````
$ conda update conda
...
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.10              |                1        12.0 MB
    setuptools-18.1            |           py27_0         341 KB
    wheel-0.24.0               |           py27_0          75 KB
    conda-3.17.0               |           py27_0         172 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        13.9 MB

The following NEW packages will be INSTALLED:

    pip:        7.1.2-py27_0 
    setuptools: 18.1-py27_0  
    wheel:      0.24.0-py27_0

The following packages will be UPDATED:

    conda:      3.16.0-py27_0 --> 3.17.0-py27_0
    python:     2.7.10-0      --> 2.7.10-1
```
```
$ conda install numpy=1.8
...
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.8.2                |           py27_0         7.3 MB

The following NEW packages will be INSTALLED:

    numpy: 1.8.2-py27_0
```
```
$ python
Python 2.7.10 |Continuum Analytics, Inc.| (default, Sep 15 2015, 14:50:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import nympy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named nympy
>>> import numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chroxvi/Desktop/tmp/miniconda/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/chroxvi/Desktop/tmp/miniconda/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/chroxvi/Desktop/tmp/miniconda/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/chroxvi/Desktop/tmp/miniconda/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/chroxvi/Desktop/tmp/miniconda/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/home/chroxvi/Desktop/tmp/miniconda/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

Looking through one of my Travis CI build logs reveals that the above install procedure succeeded yesterday (Sep 15, 2015), since the `conda update conda` step also installed the `system-5.8` package. As a workaround, one can manually install `system` (e.g. `conda install system`).

**Comment by ilanschnell** [comment]
This should be fixed now.  Try running `conda install numpy=1.8` again.

**Comment by Chroxvi** [comment]
Confirmed fixed. Thanks.

**Comment by ilanschnell** [comment]
Glad it is working now.

**Comment by moorepants** [comment]
I believe I may be getting this same issue with this build: https://travis-ci.org/pydy/pydy/jobs/83943357

We are using NumPy 1.7 and libgfortran is no longer found.
