### ISSUE TITLE
Can not connect to server

### ISSUE THREAD

**Issue by korommatyi** [conda/conda#1623]
Hi,

when I issue a command that needs connection to the anaconda server (e.g. conda update conda), I got an error. Please find the error message and the output of conda info below. Do you have any idea, how can I fix it. Thanks!

Traceback (most recent call last):
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/korommatyi/anaconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/Users/korommatyi/anaconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/Users/korommatyi/anaconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/korommatyi/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 244, in install
    offline=args.offline)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/korommatyi/anaconda/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/Users/korommatyi/anaconda/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/Users/korommatyi/anaconda/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/korommatyi/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 150, in fetch_repodata
    stderrlog.info("SSL verification error %s\n" % e.message)
AttributeError: 'SSLError' object has no attribute 'message'

The output of conda info is the following
Current conda install:

platform : osx-64
conda version : 3.16.0
conda-build version : 1.17.0
python version : 3.4.3.final.0
requests version : 2.7.0
root environment : /Users/korommatyi/anaconda  (writable)
default environment : /Users/korommatyi/anaconda
envs directories : /Users/korommatyi/anaconda/envs
package cache : /Users/korommatyi/anaconda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
config file : None
is foreign system : False

**Comment by Asymptote** [comment]
I am facing the same issue, a workaround is below:
conda config --set ssl_verify false

**Comment by asmeurer** [comment]
I pushed a fix.

**Comment by asmeurer** [comment]
Oh sorry, this was the wrong issue. This has actually been fixed for a while.
