### ISSUE TITLE
Launch Issue with iPython Notebook

### ISSUE THREAD

**Issue by nickarnold97** [conda/conda#1627]
Traceback (most recent call last):
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 238, in connect
    ssl_version=resolved_ssl_version)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", line 279, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/Users/NicholasArnold/anaconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 574, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, *_kwargs)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, *_send_kwargs)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/cli/main_run.py", line 80, in execute
    for pkg in get_package_versions(args.package):
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/api.py", line 168, in get_package_versions
    index = get_index()
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/NicholasArnold/anaconda/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/Users/NicholasArnold/anaconda/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/Users/NicholasArnold/anaconda/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "/Users/NicholasArnold/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 150, in fetch_repodata
    stderrlog.info("SSL verification error %s\n" % e.message)
AttributeError: 'SSLError' object has no attribute 'message'

Receiving the above error when attempting to launch iPython notebook with the Anaconda Launcher.

**Comment by fabiodasilva500** [comment]
I also have this problem when I tried to install IPython notebook. Did you get solve this error?

**Comment by kalefranz** [comment]
Has this error resolved itself for you with updates to requests and its dependencies?

**Comment by kalefranz** [comment]
conda config --set ssl_verify false
    conda update conda requests cryptography pyopenssl
    conda config --remove-key ssl_verify
