### ISSUE TITLE
Fail to install `fiona` with conda. OSError: [Errno 13] Permission denied: '//anaconda/etc/conda'

### ISSUE THREAD

**Issue by cdagnino** [conda/conda#1628]
I tried

`conda install fiona`

which gives

```
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment //anaconda:

The following NEW packages will be INSTALLED:

    click:   4.1-py27_0
    cligj:   0.2.0-py27_0
    fiona:   1.6.0-np19py27_0
    libgdal: 2.0.0-0
```
 which produces this error

```
Linking packages ...
An unexpected error has occurred, please consider sending the                            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 417, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 533, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 589, in link
    os.makedirs(dst_dir)
  File "//anaconda/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "//anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '//anaconda/etc/conda'
```

Here is mi conda info

```
Current conda install:

             platform : osx-64
        conda version : 3.17.0
  conda-build version : 1.3.5
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
Which gives

```

**Comment by ilanschnell** [comment]
@groutr Although I cannot reproduce the problem, it seems strange

**Comment by asmeurer** [comment]
I think it's just a permissions issue. You probably need to run conda with sudo, since it's installed in `/anaconda`.

**Comment by cdagnino** [comment]
`sudo conda install fiona` did the trick, thanks.

I've never needed administration privileges to install a package through `conda` before. Is there something that prevents `fiona` from being installed without `sudo`? I think one of the nice features of `conda` is that it's easy to install packages without administrative privileges.

**Comment by asmeurer** [comment]
In that case I recommend installing anaconda in its default location (`~/anaconda`) and doing so without using sudo.

**Comment by cdagnino** [comment]
I was just wondering whether there was an issue with `fiona` that for some reason required `sudo` and could be fixed. As I said before, none of the other packages has required `sudo` in this computer.

If this is just due to my non-default install location, then I guess it's not an issue. I'll close this one for now, but let me know if you need any more details from me.

**Comment by asmeurer** [comment]
Based on `tar -tvf ~/anaconda/pkgs/libgdal-2.0.0-0.tar.bz2` (that's the package where that file is coming from), nothing seems out of the ordinary permissions-wise. My guess is that this is just the first directory that it tried to create in the process of installing those packages and you didn't have the permissions to create directories in the /anaconda installation without sudo.

**Comment by cdagnino** [comment]
@asmeurer :+1: Great, thanks for following up!

**Comment by tanviranade** [comment]
hello sir , I am facing exact same issue.Not just with install , even create environment is not working.I tried with sudo , it did not recognize command,Please help
