### ISSUE TITLE
error while installing upgrade 

### ISSUE THREAD

**Issue by dflath** [conda/conda#1638]
Linking packages ...
An unexpected error has occurred, please consider sending the##############################                       |  74%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/flath/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    if (not main_init.is_initialized() and
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute

  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install

  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    # anything (including conda) can be installed into environments
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    must_have = {}
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    MatchSpec(specs[0]).strictness == 3):
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/install.py", line 438, in link
    def extracted(pkgs_dir):
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    msg += "Retry with onerror failed (%s)\n" % e1
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/qt.conf'
~ $ conda info
Traceback (most recent call last):
  File "/Users/flath/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in main
    from conda.cli import main_search
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 12, in <module>
    from conda.misc import make_icon_url
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/misc.py", line 19, in <module>
    from conda.api import get_index
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/api.py", line 10, in <module>
    from conda.fetch import fetch_index
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "/Users/flath/anaconda/lib/python2.7/site-packages/conda/connection.py", line 24, in <module>
    import requests
ImportError: No module named requests

**Comment by lightsquared** [comment]
Similar error:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 415, in install
    with common.json_progress_bars(json=args.json and not args.quiet):
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 532, in execute_actions
    with History(actions[inst.PREFIX]):
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 671, in unlink
    meta_path = join(prefix, 'conda-meta', dist + '.json')
FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/conda-meta/conda-3.16.0-py34_0.json'

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 415, in install
    with common.json_progress_bars(json=args.json and not args.quiet):
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 532, in execute_actions
    with History(actions[inst.PREFIX]):
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 671, in unlink
    meta_path = join(prefix, 'conda-meta', dist + '.json')
FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/conda-meta/conda-3.16.0-py34_0.json'

**Comment by sgwoodjr** [comment]
Another similar error:

[sgwood@mstdev31 sgwood ]conda info
Current conda install:

             platform : linux-64
        conda version : 3.7.3
  conda-build version : not installed
       python version : 2.7.8.final.0
     requests version : 2.4.1
     root environment : /nis_home/sgwood/anaconda  (writable)
  default environment : /nis_home/sgwood/anaconda
     envs directories : /nis_home/sgwood/anaconda/envs
        package cache : /nis_home/sgwood/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

[sgwood@mstdev31 sgwood ]conda update anaconda
Fetching package metadata: ..
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/nis_home/sgwood/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 206, in args_func
    args.func(args, p)
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 321, in install
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/plan.py", line 400, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 707, in solve
    minimal_hint=minimal_hint)
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 459, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/nis_home/sgwood/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 341, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: numpy-1.9.2-py34_0.tar.bz2 MatchSpec(u'libgfortran 1.0')

**Comment by adamlwgriffiths** [comment]
```
$ mkconda aurora
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /Users/adamgriffiths/.anaconda/envs/aurora:

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2d             |                0   hard-link
    pip-7.1.2                  |           py27_0   hard-link
    python-2.7.10              |                2   hard-link
    readline-6.2               |                2   hard-link
    setuptools-18.4            |           py27_0   hard-link
    sqlite-3.8.4.1             |                1   hard-link
    tk-8.5.18                  |                0   hard-link
    wheel-0.26.0               |           py27_1   hard-link
    zlib-1.2.8                 |                0   hard-link

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the####                                 |  55%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/adamgriffiths/.anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    execute_plan(plan, index, verbose)
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    link(prefix, arg)
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/install.py", line 438, in link
    update_prefix(join(prefix, f), prefix)
  File "/Users/adamgriffiths/.anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/easy_install'
```

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.4.1
       python version : 2.7.6.final.0
     root environment : /Users/adamgriffiths/.anaconda  (writable)
  default environment : /Users/adamgriffiths/.anaconda
     envs directories : /Users/adamgriffiths/.anaconda/envs
        package cache : /Users/adamgriffiths/.anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False
```

**Comment by lzkelley** [comment]
```
conda install pip
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /n/home00/lkelley/envs/lzk:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-7.1.2                  |           py27_0         1.4 MB
    setuptools-19.1.1          |           py27_0         345 KB
    wheel-0.26.0               |           py27_1          76 KB
    ------------------------------------------------------------
                                           Total:         1.8 MB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    pip-1.5.2                  |           py27_0
    setuptools-2.2             |           py27_0

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    pip-7.1.2                  |           py27_0   hard-link
    python-2.7.11              |                0   hard-link
    setuptools-19.1.1          |           py27_0   hard-link
    wheel-0.26.0               |           py27_1   hard-link

Proceed ([y]/n)? y

Fetching packages ...
pip-7.1.2-py27_0.tar.bz2 100% |####################################################################################################################################################| Time: 0:00:00   3.19 MB/s
setuptools-19.1.1-py27_0.tar.bz2 100% |############################################################################################################################################| Time: 0:00:00   1.98 MB/s
wheel-0.26.0-py27_1.tar.bz2 100% |#################################################################################################################################################| Time: 0:00:00 980.46 kB/s
Extracting packages ...
[      COMPLETE      ] |################################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |################################################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the###############################################################################################                                            |  75%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/n/home00/lkelley/envs/lzk/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
    execute_plan(plan, index, verbose)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
    link(prefix, arg)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 357, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 438, in link
    update_prefix(join(prefix, f), prefix)
  File "/n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/easy_install'
```

System info:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.4.1
       python version : 2.7.6.final.0
     root environment : /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x  (read only)
  default environment : /n/home00/lkelley/envs/lzk
     envs directories : /n/home00/lkelley/envs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/envs
        package cache : /n/home00/lkelley/envs/.pkgs
                        /n/sw/fasrcsw/apps/Core/Anaconda/1.9.2-fasrc01/x/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
