### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/wheel'

### ISSUE THREAD

**Issue by cjw296** [conda/conda#1642]
As instructed here:

https://travis-ci.org/Simplistix/picky/jobs/81857014

...error is as follows:

```
$ conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file conda_versions.txt
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment /home/travis/miniconda/envs/test-environment:
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.1k             |                1         2.6 MB
    pip-7.1.2                  |           py27_0         1.4 MB
    python-2.7.10              |                1        12.0 MB
    setuptools-18.1            |           py27_0         341 KB
    sqlite-3.8.4.1             |                1         2.5 MB
    tk-8.5.18                  |                0         1.9 MB
    wheel-0.26.0               |           py27_0          75 KB
    zlib-1.2.8                 |                0         100 KB
    ------------------------------------------------------------
                                           Total:        20.8 MB
The following packages will be linked:
    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.1k             |                1   hard-link
    pip-7.1.2                  |           py27_0   hard-link
    python-2.7.10              |                1   hard-link
    readline-6.2               |                2   hard-link
    setuptools-18.1            |           py27_0   hard-link
    sqlite-3.8.4.1             |                1   hard-link
    tk-8.5.18                  |                0   hard-link
    wheel-0.26.0               |           py27_0   hard-link
    zlib-1.2.8                 |                0   hard-link
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/home/travis/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 436, in execute_actions
    execute_plan(plan, index, verbose)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 418, in execute_plan
    link(prefix, arg)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/plan.py", line 374, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/install.py", line 443, in link
    update_prefix(join(prefix, f), prefix)
  File "/home/travis/miniconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
    with open(path, 'rb') as fi:
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/wheel'
The command "conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION --file conda_versions.txt" failed and exited with 1 during .
Your build has been stopped.
```

As requested:
```
0.15s$ conda info -a
Current conda install:
             platform : linux-64
        conda version : 3.4.2
       python version : 2.7.6.final.0
     root environment : /home/travis/miniconda  (writable)
  default environment : /home/travis/miniconda
     envs directories : /home/travis/miniconda/envs
        package cache : /home/travis/miniconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : /home/travis/.condarc
    is foreign system : False
# conda environments:
#
root                  *  /home/travis/miniconda
sys.version: 2.7.6 |Continuum Analytics, Inc.| (defau...
sys.prefix: /home/travis/miniconda
sys.executable: /home/travis/miniconda/bin/python
conda location: /home/travis/miniconda/lib/python2.7/site-packages/conda
conda-build: None
CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /home/travis/miniconda/bin:/home/travis/virtualenv/python2.6.9/bin:/home/travis/bin:/home/travis/.local/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.5.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:/home/travis/.nvm/v0.10.36/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.5.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/home/travis/.gimme/versions/go1.4.1.linux.amd64/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551/bin:/home/travis/.rvm/gems/ruby-1.9.3-p551@global/bin:/home/travis/.rvm/rubies/ruby-1.9.3-p551/bin:/opt/python/2.7.9/bin:/opt/python/2.6.9/bin:/opt/python/3.4.2/bin:/opt/python/3.3.5/bin:/opt/python/3.2.5/bin:/opt/python/pypy-2.5.0/bin:/opt/python/pypy3-2.4.0/bin:/usr/local/phantomjs/bin:./node_modules/.bin:/usr/local/maven-3.2.5/bin:/usr/local/clang-3.4/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin:/home/travis/.rvm/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
WARNING: could import _license.show_info
# try:
# $ conda install -n root _license
```

**Comment by cjw296** [comment]
This started failing a day or two again on Travis CI nightlies...

**Comment by ilanschnell** [comment]
I think I understand the problem.  The problem is that your conda version is over a year old and does not handle the format in some of the packages.  I would try:
```
$ conda install --no-deps -n root conda
```

**Comment by cjw296** [comment]
Ah, so this should do it?

https://github.com/Simplistix/picky/commit/660b24384f567785caef69434bc9f42d63bbde8a

**Comment by ilanschnell** [comment]
Yes, always use the `latest` version.
