### ISSUE TITLE
unexpected error report

### ISSUE THREAD

**Issue by mturtora-USGS** [conda/conda#1654]
Current conda install:

             platform : win-64
        conda version : 3.17.0
  conda-build version : 1.14.1
       python version : 2.7.7.final.0
     requests version : 2.7.0
     root environment : C:\Python\Anaconda  (writable)
  default environment : C:\Python\Anaconda
     envs directories : C:\Python\Anaconda\envs
        package cache : C:\Python\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

C:\Python\Anaconda>conda update conda
Fetching package metadata: ..An unexpected error has occurred, please consider s
ending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Python\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Python\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in ma
in
    args_func(args, p)
  File "C:\Python\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in ar
gs_func
    args.func(args, p)
  File "C:\Python\Anaconda\lib\site-packages\conda\cli\main_update.py", line 38,
 in execute
    install.install(args, parser, 'update')
  File "C:\Python\Anaconda\lib\site-packages\conda\cli\install.py", line 241, in
 install
    offline=args.offline)
  File "C:\Python\Anaconda\lib\site-packages\conda\cli\common.py", line 548, in
get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Python\Anaconda\lib\site-packages\conda\api.py", line 42, in get_inde
x
    unknown=unknown)
  File "C:\Python\Anaconda\lib\site-packages\conda\utils.py", line 119, in __cal
l__
    value = self.func(*args, **kw)
  File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 259, in fetch
_index
    repodatas.append((url, future.result()))
  File "C:\Python\Anaconda\lib\site-packages\concurrent\futures\_base.py", line
403, in result
    return self.__get_result()
  File "C:\Python\Anaconda\lib\site-packages\concurrent\futures\thread.py", line
 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Python\Anaconda\lib\site-packages\conda\fetch.py", line 100, in fetch
_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Python\Anaconda\lib\site-packages\requests\sessions.py", line 477, in
 get
    return self.request('GET', url, **kwargs)
  File "C:\Python\Anaconda\lib\site-packages\requests\sessions.py", line 465, in
 request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\Anaconda\lib\site-packages\requests\sessions.py", line 573, in
 send
    r = adapter.send(request, **kwargs)
  File "C:\Python\Anaconda\lib\site-packages\requests\adapters.py", line 370, in
 send
    timeout=timeout
  File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\connectio
npool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\connectio
npool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\connectio
npool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\connectio
n.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\p
yopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Python\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\p
yopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Python\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line
792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Python\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line
367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Python\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line
792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Python\Anaconda\lib\site-packages\pyasn1\codec\ber\decoder.py", line
430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Python\Anaconda\lib\site-packages\pyasn1\type\univ.py", line 874, in
setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Python\Anaconda\lib\site-packages\pyasn1\type\namedtype.py", line 63,
 in getPositionByType
    raise error.PyAsn1Error('Duplicate type %s' % (t,))
pyasn1.error.PyAsn1Error: Duplicate type TagSet(Tag(tagClass=128, tagFormat=0, t
agId=8))

C:\Python\Anaconda>

**Comment by mturtora-USGS** [comment]
Solved by reinstall.
