### ISSUE TITLE
All conda update/install commands throw ImportError: cannot import name InsecurePlatformWarning

### ISSUE THREAD

**Issue by williamgilpin** [conda/conda#1656]
Whenever I run `conda update numpy` (or any other package) or `conda update conda` on my OSX Yosemite system, I get the following traceback. The same traceback occurs if I try making a new conda environment. The issue persists regardless of whether my environment uses Python 2.7 or 3.4. I have updated (using pip) `requests`,`ndg-httpsclient`, and `urllib3` in all of my environments and in my system, but that didn't resolve the issue. Thank you.

<pre><code>
    Traceback (most recent call last):
  File "/Users/william/miniconda/envs/py3env/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/william/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in main
    from conda.cli import main_search
  File "/Users/william/miniconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 10, in <module>
    from conda.misc import make_icon_url
  File "/Users/william/miniconda/lib/python2.7/site-packages/conda/misc.py", line 19, in <module>
    from conda.api import get_index
  File "/Users/william/miniconda/lib/python2.7/site-packages/conda/api.py", line 10, in <module>
    from conda.fetch import fetch_index
  File "/Users/william/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "/Users/william/miniconda/lib/python2.7/site-packages/conda/connection.py", line 24, in <module>
    import requests
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 60, in <module>
    from .response import HTTPResponse
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 14, in <module>
    from .util import is_fp_closed
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/util/__init__.py", line 5, in <module>
    from .ssl_ import (
  File "/Users/william/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 4, in <module>
    from ..exceptions import SSLError, InsecurePlatformWarning
ImportError: cannot import name InsecurePlatformWarning
</code></pre>

**Comment by asmeurer** [comment]
Can you paste the output of `conda info -a`?

**Comment by williamgilpin** [comment]
Hey asmeurer, `conda info -a` returns the same traceback---I just tried it inside and outside of my environments and got the same issue. conda was working as of a week ago, and the only thing I could think of that would break it would be the latest OSX Yosemite updates, which I might have installed during that period. Thanks very much for your help with this.

**Comment by asmeurer** [comment]
My only suggestion is `pip install -U requests`. If that doesn't fix it, I think you may need to reinstall miniconda.

**Comment by williamgilpin** [comment]
Attempting to upgrade with pip, so I tried just uninstalling `requests` and then re-installing it. Curiously, that fixed my problem for now---I checked the version and it looks like it's the same as the one I was running, but maybe something bad happened to my copy of `requests` during one of the latest OSX updates. Thank you for your help, Aaron.

**Comment by jreyles** [comment]
<code> pip install -U requests </code> worked wonderfully well on my end. Thanks!

**Comment by j08lue** [comment]
Just for the record: I had the same problem, the origin turning out to be that the `PYTHONPATH` environment variable was set, pointing to some other Python directory with `requests` in it (perhaps incompatible version or broken or so). Unsetting `PYTHONPATH` solved the problem.

**Comment by iCoolchar** [comment]
after installing miniconda, there is  a warning:
```
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda2.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda2: /Users/icoolchar/miniconda2
```
So set the PYTHONPATH **only** to miniconda solves the problem.
