### ISSUE TITLE
Previously working anaconda install is no longer working on any platform. 

### ISSUE THREAD

**Issue by malgaudreault** [conda/conda#1662]
conda install anaconda
    Fetching package metadata: ....
    Solving package specifications: .An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "/usr/local/jupyterhub/anaconda/envs/ana/bin/conda", line 5, in <module>
        sys.exit(main())
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
        args_func(args, p)
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
        args.func(args, p)
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
        return func(args, parser)
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
        install.install(args, parser, 'install')
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 336, in install
        minimal_hint=args.alt_hint)
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
        config.track_features, minimal_hint=minimal_hint):
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
        minimal_hint=minimal_hint)
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
        clauses = set(self.gen_clauses(v, dists, specs, features))
      File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
        assert len(clause) > 1, '%s %r' % (fn1, ms)
    AssertionError: numpy-1.9.2-py34_0.tar.bz2 MatchSpec(u'libgfortran 1.0')

    Current conda install:

                 platform : linux-64
            conda version : 3.14.1
      conda-build version : 1.14.1
           python version : 2.7.10.final.0
         requests version : 2.7.0
         root environment : /usr/local/jupyterhub/anaconda  (read only)
      default environment : /usr/local/jupyterhub/anaconda/envs/ana
         envs directories : /home/alex/.conda/envs
                            /home/alex/envs
                            /usr/local/jupyterhub/anaconda/envs
            package cache : /home/alex/.conda/envs/.pkgs
                            /home/alex/envs/.pkgs
                            /usr/local/jupyterhub/anaconda/pkgs
             channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/linux-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : None
        is foreign system : False

**Comment by asmeurer** [comment]
@ilanschnell

**Comment by ilanschnell** [comment]
Ah, thanks.  Should be fixed now.

**Comment by malgaudreault** [comment]
Thanks!
