### ISSUE TITLE
glueviz update error 

### ISSUE THREAD

**Issue by ghost** [conda/conda#1671]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 427, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 669, in unlink
    with open(meta_path) as fi:
FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/conda-meta/astropy-1.0.3-np19py34_0.json'

**Comment by soapy1** [comment]
This does not seem to be an issue in the newest version of conda
