### ISSUE TITLE
invalid data stream message after updating

### ISSUE THREAD

**Issue by ojmesa** [conda/conda#1673]
Traceback (most recent call last):
  File "/Users/ojmesa/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 243, in install
    offline=args.offline)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 582, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/ojmesa/anaconda/lib/python3.4/concurrent/futures/_base.py", line 395, in result
    return self.__get_result()
  File "/Users/ojmesa/anaconda/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/Users/ojmesa/anaconda/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/ojmesa/anaconda/lib/python3.4/site-packages/conda/fetch.py", line 103, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
  File "/Users/ojmesa/anaconda/lib/python3.4/bz2.py", line 510, in decompress
    res = decomp.decompress(data)
OSError: Invalid data stream

Current conda install:

             platform : osx-64
        conda version : 3.18.1
  conda-build version : 1.8.2
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /Users/ojmesa/anaconda  (writable)
  default environment : /Users/ojmesa/anaconda
     envs directories : /Users/ojmesa/anaconda/envs
        package cache : /Users/ojmesa/anaconda/pkgs
         channel URLs : https://pypi.python.org/pypi/ProjectEuler/1.0.0/osx-64/
                        https://pypi.python.org/pypi/ProjectEuler/1.0.0/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ojmesa/.condarc
    is foreign system : False

**Comment by ilanschnell** [comment]
You cannot add ` https://pypi.python.org/pypi/ProjectEuler/1.0.0/` to your channels.  The channel list is only for conda repositories, not for PyPI.
