### ISSUE TITLE
Error when updating using conda update --all

### ISSUE THREAD

**Issue by kmajeed** [conda/conda#1676]
Traceback (most recent call last):
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\install.py", line 404, in install
    if not pscheck.main(args):
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\pscheck.py", line 66, in main
    while not check_processes():
  File "C:\Users\1\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\pscheck.py", line 33, in check_processes
    for n in psutil.get_pid_list():
AttributeError: 'module' object has no attribute 'get_pid_list'

**Comment by ilanschnell** [comment]
You're probably using an old version of conda.  I would try running `conda update conda` first.

**Comment by kmajeed** [comment]
Thanks ilanscnell I have installed new version of anaconda manually
