### ISSUE TITLE
AttributeError: 'HTTPResponse' object has no attribute 'tell'

### ISSUE THREAD

**Issue by bhooshan-gadre** [conda/conda#1686]
Traceback (most recent call last):
  File "/data1/student/cbug/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 427, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/data1/student/cbug/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 386, in download
    n = resp.raw.tell()
AttributeError: 'HTTPResponse' object has no attribute 'tell'
bash-4.1$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.1
  conda-build version : 1.18.0
       python version : 2.7.10.final.0
     requests version : 1.2.3
     root environment : /data1/student/cbug/anaconda  (writable)
  default environment : /data1/student/cbug/anaconda
     envs directories : /data1/student/cbug/anaconda/envs
        package cache : /data1/student/cbug/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by bhooshan-gadre** [comment]
pip install requests -U solved it
