### ISSUE TITLE
App Update

### ISSUE THREAD

**Issue by ravekanth** [conda/conda#1689]
Traceback (most recent call last)
File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    try:
  File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 38, in execute
    common.add_parser_json(p)
  File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 415, in install
  File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/plan.py", line 532, in execute_actions
    # ---------------------------- EXECUTION --------------------------
  File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Users/Rave/anaconda/lib/python2.7/site-packages/conda/install.py", line 671, in unlink
IOError: [Errno 2] No such file or directory: '/Users/Rave/anaconda/conda-meta/conda-3.16.0-py27_0.json'

Conda Info:
             platform : osx-64
        conda version : 3.18.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.8.0
     root environment : /Users/Rave/anaconda  (writable)
  default environment : /Users/Rave/anaconda
     envs directories : /Users/Rave/anaconda/envs
        package cache : /Users/Rave/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
@ravekanth is this still an issue for you?
