### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

### ISSUE THREAD

**Issue by whitequark** [conda/conda#1693]
To reproduce:
  * Install miniconda for 64-bit Linux on Debian testing.
  * Run `conda update conda`.

conda info:
```
Current conda install:

             platform : linux-64
        conda version : 3.16.0
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /home/whitequark/.miniconda  (writable)
  default environment : /home/whitequark/.miniconda
     envs directories : /home/whitequark/.miniconda/envs
        package cache : /home/whitequark/.miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Traceback:
```

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 557, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 780, in _validate_conn
    conn.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 241, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", line 276, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/whitequark/.miniconda/lib/python3.4/ssl.py", line 365, in wrap_socket
    _context=self)
  File "/home/whitequark/.miniconda/lib/python3.4/ssl.py", line 583, in __init__
    self.do_handshake()
  File "/home/whitequark/.miniconda/lib/python3.4/ssl.py", line 810, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 586, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:600)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/whitequark/.miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/cli/install.py", line 244, in install
    offline=args.offline)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/cli/common.py", line 548, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/fetch.py", line 255, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/whitequark/.miniconda/lib/python3.4/concurrent/futures/_base.py", line 402, in result
    return self.__get_result()
  File "/home/whitequark/.miniconda/lib/python3.4/concurrent/futures/_base.py", line 354, in __get_result
    raise self._exception
  File "/home/whitequark/.miniconda/lib/python3.4/concurrent/futures/thread.py", line 54, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/whitequark/.miniconda/lib/python3.4/site-packages/conda/fetch.py", line 150, in fetch_repodata
    stderrlog.info("SSL verification error %s\n" % e.message)
AttributeError: 'SSLError' object has no attribute 'message'
```

**Comment by gmarkall** [comment]
I've tried to replicate this but have not been able to so far. Straight after installing Miniconda , running `conda update` gives the error:

```
Error: no package names supplied
```

I also tried running `conda update conda` in case that was what was intended, which ran successfully.

I'm wondering if this is something that's not necessarily specific to debian, but a problem when a particular kind of SSL error is encountered. I tried to force an error by adding `216.58.210.14 repo.continuum.io` to my `/etc/hosts`, but when running `conda update conda`, I got an error message explaining pretty much what happened.

`/etc/debian_version` contains `stretch/sid`, which I just installed freshly. @whitequark do you have any thoughts about what else I might try?

**Comment by whitequark** [comment]
Yeah, I meant `conda update conda`. So, I tried to strace my conda install:
```
$ strace -eopen -f conda update conda 2>&1 | egrep ssl
open("/home/whitequark/.miniconda/lib/python3.4/lib-dynload/../../libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
open("/home/whitequark/.miniconda/lib/python3.4/__pycache__/ssl.cpython-34.pyc", O_RDONLY) = 4
open("/home/whitequark/.miniconda/lib/python3.4/lib-dynload/_ssl.cpython-34m.so", O_RDONLY|O_CLOEXEC) = 4
open("/usr/lib/python3/dist-packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc", O_RDONLY) = 4
open("/usr/lib/python3/dist-packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc", O_RDONLY) = 4
open("/usr/lib/python3/dist-packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc", O_RDONLY) = 4
open("/usr/lib/python3/dist-packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc", O_RDONLY) = 4
open("/usr/lib/python3/dist-packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc", O_RDONLY) = 4
[pid  7824] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 8
[pid  7826] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 8
[pid  7825] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 7
[pid  7823] open("/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 5
open("/usr/lib/python3/dist-packages/urllib3/util/ssl_.py", O_RDONLY) = 4
open("/home/whitequark/.miniconda/lib/python3.4/ssl.py", O_RDONLY) = 4
open("/home/whitequark/.miniconda/lib/python3.4/ssl.py", O_RDONLY) = 4
open("/home/whitequark/.miniconda/lib/python3.4/ssl.py", O_RDONLY) = 4
```

It looks like it grab urllib from the host Python. It probably shouldn't. Does it on your machine?

Also maybe my ca-certificates.crt is corrupted--I've uploaded it as http://fehu.whitequark.org/files/ca-certificates.crt.

**Comment by gmarkall** [comment]
It did not find urllib from the host Python:

```
graham@debian:~$ strace -eopen -f conda update conda 2>&1 | egrep ssl
open("/home/graham/miniconda3/lib/python3.4/lib-dynload/../../libssl.so.1.0.0", O_RDONLY|O_CLOEXEC) = 3
open("/home/graham/miniconda3/lib/python3.4/__pycache__/ssl.cpython-34.pyc", O_RDONLY) = 4
open("/home/graham/miniconda3/lib/python3.4/lib-dynload/_ssl.cpython-34m.so", O_RDONLY|O_CLOEXEC) = 4
open("/home/graham/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc", O_RDONLY) = 4
open("/home/graham/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc", O_RDONLY) = 4
open("/home/graham/miniconda3/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc", O_RDONLY) = 4
open("/home/graham/miniconda3/conda-meta/openssl-1.0.1k-1.json", O_RDONLY) = 4
open("/home/graham/miniconda3/conda-meta/openssl-1.0.1k-1.json", O_RDONLY) = 4
y
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/_implementation.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/requests-2.8.0-py34_0/lib/python3.4/site-packages/requests/packages/urllib3/util/ssl_.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/contrib/__pycache__/pyopenssl.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/contrib/pyopenssl.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname/__init__.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/__init__.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname/__pycache__/_implementation.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/packages/ssl_match_hostname/_implementation.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/util/__pycache__/ssl_.cpython-34.pyc", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
open("/home/graham/miniconda3/pkgs/pip-7.1.2-py34_0/lib/python3.4/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 5
```

I'm not sure how it found urllib from the system Python on your installation, but: Do you have `PYTHONPATH`, or `PYTHONHOME` somehow set in your installation? Does the Python in your conda environment have the expected value for `sys.prefix`? Is part of the system Python on `sys.path`?

**Comment by whitequark** [comment]
```
$ env|grep PYTHON
$
$ python3
Python 3.4.3 |Continuum Analytics, Inc.| (default, Jun  4 2015, 15:29:08) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/home/whitequark/.miniconda'
>>> sys.path
['', '/home/whitequark/.local/lib/python3.4/site-packages/sphinx_argparse-0.1.14-py3.4.egg', '/usr/lib/python3/dist-packages', '/home/whitequark/.local/lib/python3.4/site-packages/regex-2015.03.18-py3.4-linux-x86_64.egg', '/home/whitequark/.local/lib/python3.4/site-packages/pyparser-0.2-py3.4.egg', '/home/whitequark/.local/lib/python3.4/site-packages/pyqtgraph-0.9.10-py3.4.egg', '/home/whitequark/.local/lib/python3.4/site-packages/Quamash-0.5.1-py3.4.egg', '/home/whitequark/.local/lib/python3.4/site-packages/pyelftools-0.23-py3.4.egg', '/home/whitequark/.local/lib/python3.4/site-packages/PyDAQmx-1.3.1-py3.4.egg', '/home/whitequark/.local/lib/python3.4/site-packages/lit-0.4.1-py3.4.egg', '/home/whitequark/.local/lib/python3.4/site-packages/OutputCheck-0.4.1-py3.4.egg', '/home/whitequark/Work/artiq-dev/migen', '/home/whitequark/Work/artiq-dev/misoc', '/home/whitequark/Work/artiq-dev/pythonparser', '/home/whitequark/Work/artiq-dev/artiq', '/home/whitequark/.miniconda/lib/python34.zip', '/home/whitequark/.miniconda/lib/python3.4', '/home/whitequark/.miniconda/lib/python3.4/plat-linux', '/home/whitequark/.miniconda/lib/python3.4/lib-dynload', '/home/whitequark/.local/lib/python3.4/site-packages', '/home/whitequark/.miniconda/lib/python3.4/site-packages']
```

**Comment by whitequark** [comment]
OK, so this is where most of the paths come from:
```
$ cat ~/.local/lib/python3.4/site-packages/easy-install.pth 
import sys; sys.__plen = len(sys.path)
./sphinx_argparse-0.1.14-py3.4.egg
/usr/lib/python3/dist-packages
./regex-2015.03.18-py3.4-linux-x86_64.egg
./pyparser-0.2-py3.4.egg
./pyqtgraph-0.9.10-py3.4.egg
./Quamash-0.5.1-py3.4.egg
./pyelftools-0.23-py3.4.egg
./PyDAQmx-1.3.1-py3.4.egg
./lit-0.4.1-py3.4.egg
./OutputCheck-0.4.1-py3.4.egg
/home/whitequark/Work/artiq-dev/migen
/home/whitequark/Work/artiq-dev/misoc
/home/whitequark/Work/artiq-dev/pythonparser
/home/whitequark/Work/artiq-dev/artiq
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
```

**Comment by gmarkall** [comment]
I guess that `easy-install.pth` is the reason why it's finding urllib3 from the system Python :-)

I'm not sure that the Python from the conda installation should be looking at user site packages, but I'm not enough of a conda expert to say for certain... It certainly seems to break the isolation of conda environments though.

**Comment by gmarkall** [comment]
Issues with possibly the same cause in anaconda-issues:

https://github.com/ContinuumIO/anaconda-issues/issues/404
https://github.com/ContinuumIO/anaconda-issues/issues/394

**Comment by gmarkall** [comment]
@whitequark, thanks for all the extra info. I've opened https://github.com/ContinuumIO/anaconda-issues/issues/473 to discuss (what I think is) the underlying issue - hopefully someone more knowledgeable than I will be able to weigh in.
