### ISSUE TITLE
on Travis: ValueError: numpy.dtype has the wrong size, try recompiling

### ISSUE THREAD

**Issue by twiecki** [conda/conda#1701]
Stumped by this one. Not sure why we're getting that weird import error for our travis CI on `pyfolio`: https://travis-ci.org/quantopian/pyfolio/jobs/84695009

**Comment by twiecki** [comment]
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-fedd52f97c1a> in <module>()
----> 1 get_ipython().magic(u'matplotlib inline')
      2 import pyfolio as pf
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2334         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2335         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2336         return self.run_line_magic(magic_name, magic_arg_s)
   2337 
   2338     #-------------------------------------------------------------------------
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2255                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2256             with self.builtin_trap:
-> 2257                 result = fn(*args,**kwargs)
   2258             return result
   2259 
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194 
    195         if callable(arg):
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/magics/pylab.pyc in matplotlib(self, line)
     98             print("Available matplotlib backends: %s" % backends_list)
     99         else:
--> 100             gui, backend = self.shell.enable_matplotlib(args.gui)
    101             self._show_matplotlib_backend(args.gui, backend)
    102 
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in enable_matplotlib(self, gui)
   3130                 gui, backend = pt.find_gui_and_backend(self.pylab_gui_select)
   3131 
-> 3132         pt.activate_matplotlib(backend)
   3133         pt.configure_inline_support(self, backend)
   3134 
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/IPython/core/pylabtools.pyc in activate_matplotlib(backend)
    272     matplotlib.rcParams['backend'] = backend
    273 
--> 274     import matplotlib.pyplot
    275     matplotlib.pyplot.switch_backend(backend)
    276 
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/pyplot.py in <module>()
     25 
     26 import matplotlib
---> 27 import matplotlib.colorbar
     28 from matplotlib import style
     29 from matplotlib import _pylab_helpers, interactive
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/colorbar.py in <module>()
     30 
     31 import matplotlib as mpl
---> 32 import matplotlib.artist as martist
     33 import matplotlib.cbook as cbook
     34 import matplotlib.collections as collections
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/artist.py in <module>()
     10 import matplotlib.cbook as cbook
     11 from matplotlib import docstring, rcParams
---> 12 from .transforms import Bbox, IdentityTransform, TransformedBbox, \
     13                        TransformedPath, Transform
     14 from .path import Path
/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/matplotlib/transforms.py in <module>()
     37 import numpy as np
     38 from numpy import ma
---> 39 from matplotlib._path import (affine_transform, count_bboxes_overlapping_bbox,
     40     update_path_extents)
     41 from numpy.linalg import inv
ImportError: numpy.core.multiarray failed to import
```

**Comment by arogozhnikov** [comment]
hi, I'm facing same problem on travis. 
Have you found the reason or hack to resolve it?

**Comment by twiecki** [comment]
Haven't found a solution yet.

**Comment by twiecki** [comment]
As of yesterday, this problem does not occur anymore without me having done anything.

**Comment by anaderi** [comment]
In my case the problem was solved by putting 'deactivate' at the beginning of installation script, since all python instructions at Travis happen under Python virtualenv. I used miniconda in my installation script to create own virtualenv. Although PATH, PYTHONPATH variables are set perfectly, IPython picks '$VIRTUAL_ENV' variable and inserts at 'site-packages' directory from the VIRTUAL_ENV to sys.path. So in my case old numpy from Travis Virtualenv was conflicting with matplotlib I've installed in my conda environment. After 'deactivate'-ing the error has gone.

**Comment by twiecki** [comment]
Now I'm back to 
```
    import pandas as pd
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/pandas/__init__.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38262)
ValueError: numpy.dtype has the wrong size, try recompiling
```

I tried deactivating but it didn't help.

**Comment by par2** [comment]
Having this issue with a Python 3.5 build on travis only.  A similar build works fine for py 2.7, 3.3 and 3.4.

**Comment by kalefranz** [comment]
Closing this issue here now.  Probably outdated and it's resolved itself.  If not, please file a new issue at github.com/ContinuumIO/anaconda-issues, which tracks problems with individual packages.
