### ISSUE TITLE
403 downloading JPEG source

### ISSUE THREAD

**Issue by msarahan** [conda/conda#1715]
```
Downloading source to cache: jpegsrc.v8d.tar.gz
Downloading http://www.ijg.org/files/jpegsrc.v8d.tar.gz
Error: HTTPError: 403 Client Error: Forbidden for url: http://www.ijg.org/files/jpegsrc.v8d.tar.gz: http://www.ijg.org/files/jpegsrc.v8d.tar.gz
Error: Could not download jpegsrc.v8d.tar.gz
Traceback (most recent call last):
  File "C:\Users\builder\MC_Main\Scripts\build-script.py", line 9, in <module>
    load_entry_point('abts==0.0.0', 'console_scripts', 'build')()
  File "z:\documents\code\anaconda\bt\build.py", line 427, in main
    build(pkg, only_build = opts.only_build)
  File "z:\documents\code\anaconda\bt\build.py", line 308, in build
    conda_build(pkg)
  File "z:\documents\code\anaconda\bt\build.py", line 239, in conda_build
    check_call(cmd, env=env)
  File "C:\Users\builder\MC_Main\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\builder\\MC_Main\\python.exe', 'C:\\Users\\builder\\MC_Main\\Scripts\\conda-build-script.py', '--python', '35', '--numpy', '19', '--no-include-recipe', 'z:\\documents\\code\\anaconda\\packages\\jpeg']' returned non-zero exit status 1
```

This is very weird.  Downloading this file in the browser works, as does using cURL.  I'm sure it's a server setting on their end, but I'd like to know why they might have set that setting, and whether there's a good way around it for us.

**Comment by msarahan** [comment]
cURL command, for reference testing:

    curl -o jpeg8 "http://www.ijg.org/files/jpegsrc.v8d.tar.gz"

**Comment by almeidajeff** [comment]
I have the same problem

```
libjpeg: Downloading http://www.ijg.org/files/jpegsrc.v8c.tar.gz
While:
  Installing libjpeg.

An internal error occured due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/opt/core/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1683, in main
    getattr(buildout, command)(args)
  File "/opt/core/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 555, in install
    installed_files = self[part]._call(recipe.install)
  File "/opt/core/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/buildout.py", line 1227, in _call
    return f()
  File "/opt/core/eggs/zc.recipe.cmmi-1.3.5-py2.7.egg/zc/recipe/cmmi/__init__.py", line 113, in install
    self.build()
  File "/opt/core/eggs/collective.recipe.cmmi-0.5-py2.7.egg/collective/recipe/cmmi/__init__.py", line 24, in build
    result = Base.build(self)
  File "/opt/core/eggs/zc.recipe.cmmi-1.3.5-py2.7.egg/zc/recipe/cmmi/__init__.py", line 134, in build
    fname, is_temp = download(self.url, md5sum=self.options.get('md5sum'))
  File "/opt/core/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/download.py", line 96, in __call__
    local_path, is_temp = self.download(url, md5sum, path)
  File "/opt/core/eggs/zc.buildout-1.4.4-py2.7.egg/zc/buildout/download.py", line 173, in download
    tmp_path, headers = urllib.urlretrieve(url, tmp_path)
  File "/usr/lib/python2.7/urllib.py", line 93, in urlretrieve
    return _urlopener.retrieve(url, filename, reporthook, data)
  File "/usr/lib/python2.7/urllib.py", line 239, in retrieve
    fp = self.open(url, data)
  File "/usr/lib/python2.7/urllib.py", line 207, in open
    return getattr(self, name)(url)
  File "/usr/lib/python2.7/urllib.py", line 358, in open_http
    return self.http_error(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 375, in http_error
    return self.http_error_default(url, fp, errcode, errmsg, headers)
  File "/usr/lib/python2.7/urllib.py", line 380, in http_error_default
    raise IOError, ('http error', errcode, errmsg, headers)
IOError: ('http error', 403, 'Forbidden', <httplib.HTTPMessage instance at 0x18ba758>)
```

**Comment by kalefranz** [comment]
`conda install jpeg` work for me on os-x.  How is the problem reproduced?

**Comment by almeidajeff** [comment]
Sorry, wrong project
