### ISSUE TITLE
Latest update breaks ipython notebook

### ISSUE THREAD

**Issue by kungfujam** [conda/conda#1722]
Ran a full update of all packages and now `ipython notebook` will not start (`ipython` terminal starts fine). This appears to have something due to `cython` and `pyzmq`.

## What I did to produce the error
```bash
conda update conda
conda update --all
ipython notebook
```

And got the error below. I had also previously run `brew upgrade && brew update`, but this should not affect anything since anaconda is first in my path:

```bash
/Users/user/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/Applications/Firefox.app/Contents/MacOS:/Applications/Julia-0.3.1.app/Contents/Resources/julia/bin:/Users/user/Dropbox/utils:/Applications/MATLAB_R2015b.app/bin:/usr/local/texlive/2014/bin/x86_64-darwin:/Users/user/Applications/VLC.app/Contents/MacOS
```

## What I've tried to solve the problem
1. Full system restart
1. `conda update -f conda && conda update -f --all`
1. All recommendations in docs here: http://conda.pydata.org/docs/troubleshooting.html

## Error message I got
```
$ ipython notebook
Traceback (most recent call last):
  File "/Users/user/anaconda/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/Users/user/anaconda/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/user/anaconda/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
  File "/Users/user/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 32, in <module>
    from zmq.eventloop import ioloop
  File "/Users/user/anaconda/lib/python2.7/site-packages/zmq/__init__.py", line 66, in <module>
    from zmq import backend
  File "/Users/user/anaconda/lib/python2.7/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/Users/user/anaconda/lib/python2.7/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/Users/user/anaconda/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/user/anaconda/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/user/anaconda/lib/python2.7/site-packages/zmq/backend/cython/constants.so, 2): Library not loaded: @rpath/libsodium.4.dylib
  Referenced from: /Users/user/anaconda/lib/libzmq.4.dylib
  Reason: image not found
```

## My conda list and info
```bash
$ conda list
# packages in environment at /Users/user/anaconda:
#
_license                  1.1                      py27_0  
abstract-rendering        0.5.1                np19py27_0  
accelerate                1.14.0              np19py27_p0  
alabaster                 0.7.3                    py27_0  
anaconda                  2.3.0                np19py27_0  
anaconda-client           1.0.2                    py27_0  
appnope                   0.1.0                    py27_0  
appscript                 1.0.1                    py27_0  
argcomplete               1.0.0                    py27_1  
astropy                   1.0.4                np19py27_0  
atom                      0.3.9                    py27_0  
babel                     2.1.1                    py27_0  
backports.ssl-match-hostname 3.4.0.2                   <pip>
bcolz                     0.11.3                   py27_0  
beautiful-soup            4.3.2                    py27_0  
beautifulsoup4            4.3.2                     <pip>
binstar                   0.12                          2  
biopython                 1.65                 np19py27_0  
bitarray                  0.8.1                    py27_0  
blaze                     0.8.3                    py27_0  
blaze-core                0.8.3                    py27_0  
blz                       0.6.2                np19py27_1  
bokeh                     0.10.0                   py27_0  
boto                      2.38.0                   py27_0  
bottleneck                1.0.0                np19py27_0  
camocomp                  0.1                       <pip>
casuarius                 1.1                      py27_0  
cdecimal                  2.3                      py27_0  
certifi                   14.05.14                 py27_0  
cffi                      1.2.1                    py27_0  
chaco                     4.5.0                np19py27_0  
clyent                    0.4.0                    py27_0  
colorama                  0.3.3                    py27_0  
conda                     3.18.3                   py27_0  
conda-build               1.18.1                   py27_0  
conda-env                 2.4.3                    py27_0  
conda-server              0.14.0                        1  
configobj                 5.0.6                    py27_0  
cryptography              0.9.3                    py27_0  
cudatoolkit               7.0                           1  
curl                      7.43.0                        1  
cython                    0.23.4                   py27_0  
cytoolz                   0.7.3                    py27_0  
datashape                 0.4.7                    py27_0  
dateutil                  2.4.1                    py27_0  
decorator                 4.0.4                    py27_0  
docutils                  0.12                     py27_0  
dynd-python               0.6.5                np19py27_0  
enable                    4.4.1                np19py27_0  
enaml                     0.9.8                    py27_0  
enum34                    1.0.4                    py27_0  
fastcache                 1.0.2                    py27_0  
flask                     0.10.1                   py27_1  
freetype                  2.5.2                         2  
funcsigs                  0.4                      py27_0  
future                    0.15.2                   py27_0  
futures                   3.0.3                    py27_0  
gevent                    1.0.1                    py27_0  
gevent-websocket          0.9.3                    py27_0  
glueviz                   0.5.3                np19py27_1  
greenlet                  0.4.9                    py27_0  
grin                      1.2.1                    py27_1  
h5py                      2.5.0                np19py27_3  
hdf5                      1.8.15.1                      2  
idna                      2.0                      py27_0  
iopro                     1.7.2               np19py27_p0  
ipaddress                 1.0.7                    py27_0  
ipykernel                 4.1.0                    py27_0  
ipyparallel               4.0.2                    py27_0  
ipython                   4.0.0                    py27_1  
ipython-genutils          0.1.0                     <pip>
ipython-notebook          4.0.4                    py27_0  
ipython-qtconsole         4.0.1                    py27_0  
ipython_genutils          0.1.0                    py27_0  
ipywidgets                4.0.3                    py27_0  
itsdangerous              0.24                     py27_0  
jdcal                     1.0                      py27_0  
jedi                      0.9.0                    py27_0  
jinja2                    2.8                      py27_0  
joblib                    0.9.0b2                   <pip>
jpeg                      8d                            2  
jsonschema                2.4.0                    py27_0  
jupyter-client            4.1.1                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py27_0  
jupyter_core              4.0.6                    py27_0  
kiwisolver                0.1.3                    py27_0  
kmodes                    0.1.0                     <pip>
krb5                      1.13.2                        0  
launcher                  1.0.0                         3  
lcms                      1.19                          0  
libdynd                   0.6.5                         0  
libgcc                    4.8.5                         1  
libpng                    1.6.17                        0  
libsodium                 1.0.3                         0  
libtiff                   4.0.2                         1  
libxml2                   2.9.2                         1  
libxslt                   1.1.28                        2  
llvm                      3.3                           0  
llvmlite                  0.7.0                    py27_3  
llvmpy                    0.12.7                   py27_0  
lxml                      3.4.4                    py27_0  
markupsafe                0.23                     py27_0  
matplotlib                1.4.3                np19py27_3  
mistune                   0.7.1                    py27_0  
mkl                       11.1                np19py27_p1  
mkl-rt                    11.1                         p0  
mkl-service               1.0.0                   py27_p2  
mklfft                    2.0                 np19py27_p1  
mock                      1.3.0                    py27_0  
multipledispatch          0.4.8                    py27_0  
nbconvert                 4.0.0                    py27_0  
nbformat                  4.0.1                    py27_0  
networkx                  1.10                     py27_0  
nltk                      3.1                      py27_0  
node-webkit               0.10.1                        0  
nolearn                   0.6a0.dev0                <pip>
nose                      1.3.7                    py27_0  
notebook                  4.0.6                    py27_0  
numba                     0.21.0               np19py27_0  
numbapro                  0.21.0              np19py27_p1  
numbapro_cudalib          0.2                           0  
numexpr                   2.4.4               np19py27_p0  [mkl]
numpy                     1.9.3                   py27_p0  [mkl]
ocropy                    0.2                       <pip>
odo                       0.3.4                    py27_0  
openpyxl                  2.2.6                    py27_0  
openssl                   1.0.1k                        1  
pandas                    0.16.2               np19py27_0  
path.py                   8.1.2                    py27_0  
patsy                     0.4.0                np19py27_0  
pbr                       1.3.0                    py27_0  
pep8                      1.6.2                    py27_0  
pexpect                   3.3                      py27_0  
pickleshare               0.5                      py27_0  
pil                       1.1.7                    py27_2  
pillow                    3.0.0                    py27_0  
pip                       7.1.2                    py27_0  
ply                       3.4                      py27_0  
psutil                    3.2.2                    py27_0  
ptyprocess                0.4                      py27_0  
py                        1.4.30                   py27_0  
pyasn1                    0.1.7                    py27_0  
pyaudio                   0.2.7                    py27_0  
pycosat                   0.6.1                    py27_0  
pycparser                 2.14                     py27_0  
pycrypto                  2.6.1                    py27_0  
pycurl                    7.19.5.1                 py27_2  
pyface                    4.4.0                    py27_0  
pyflakes                  1.0.0                    py27_0  
pygments                  2.0.2                    py27_0  
pymongo                   3.0.3                    py27_0  
pyopenssl                 0.15.1                   py27_1  
pyparsing                 2.0.3                    py27_0  
pyqt                      4.11.4                   py27_0  
pytables                  3.2.2                np19py27_0  
pytest                    2.8.1                    py27_0  
python                    2.7.10                        1  
python-dateutil           2.4.2                    py27_0  
python.app                1.2                      py27_4  
pytz                      2015.6                   py27_0  
pyyaml                    3.11                     py27_1  
pyzmq                     14.7.0                   py27_0  
qt                        4.8.7                         1  
qtconsole                 4.1.0                    py27_0  
readline                  6.2                           2  
redis                     2.6.9                         0  
redis-py                  2.10.3                   py27_0  
requests                  2.8.1                    py27_0  
rope                      0.9.4                    py27_1  
runipy                    0.1.3                    py27_0  
scikit-image              0.11.3               np19py27_0  
scikit-learn              0.16.1              np19py27_p0  [mkl]
scipy                     0.16.0              np19py27_p1  [mkl]
setuptools                18.4                     py27_0  
simplegeneric             0.8.1                    py27_0  
singledispatch            3.4.0.3                  py27_1  
sip                       4.16.9                   py27_0  
six                       1.10.0                   py27_0  
snowballstemmer           1.2.0                    py27_0  
sockjs-tornado            1.0.1                    py27_0  
sphinx                    1.3.1                    py27_0  
sphinx-rtd-theme          0.1.7                     <pip>
sphinx_rtd_theme          0.1.7                    py27_0  
spyder                    2.3.7                    py27_1  
spyder-app                2.3.7                    py27_0  
sqlalchemy                1.0.8                    py27_0  
sqlite                    3.8.4.1                       1  
ssl_match_hostname        3.4.0.2                  py27_0  
statsmodels               0.6.1                np19py27_0  
sympy                     0.7.6.1                  py27_0  
tables                    3.2.2                     <pip>
tabulate                  0.7.5                     <pip>
terminado                 0.5                      py27_0  
tk                        8.5.18                        0  
toolz                     0.7.4                    py27_0  
tornado                   4.2.1                    py27_0  
traitlets                 4.0.0                    py27_0  
traits                    4.4.0                    py27_0  
traitsui                  4.4.0                    py27_0  
ujson                     1.33                     py27_0  
unicodecsv                0.14.1                   py27_0  
werkzeug                  0.10.4                   py27_0  
wheel                     0.26.0                   py27_1  
xlrd                      0.9.4                    py27_0  
xlsxwriter                0.7.6                    py27_0  
xlwings                   0.4.1                    py27_0  
xlwt                      1.0.0                    py27_0  
yaml                      0.1.6                         0  
zeromq                    4.0.5                         1  
zlib                      1.2.8                         1  

$ conda info -a
Current conda install:

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /Users/user/anaconda  (writable)
  default environment : /Users/user/anaconda
     envs directories : /Users/user/anaconda/envs
        package cache : /Users/user/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/conda/osx-64/
                        https://conda.anaconda.org/conda/noarch/
                        https://conda.anaconda.org/r/osx-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://repo.continuum.io/pkgs/gpl/osx-64/
                        http://repo.continuum.io/pkgs/gpl/noarch/
          config file : /Users/user/.condarc
    is foreign system : False

# conda environments:
#
opencv                   /Users/user/anaconda/envs/opencv
pdffigures               /Users/user/anaconda/envs/pdffigures
theano                   /Users/user/anaconda/envs/theano
root                  *  /Users/user/anaconda

sys.version: 2.7.10 |Anaconda 2.3.0 (x86_64)| (defaul...
sys.prefix: /Users/user/anaconda
sys.executable: /Users/user/anaconda/bin/python
conda location: /Users/user/anaconda/lib/python2.7/site-packages/conda
conda-build: /Users/user/anaconda/bin/conda-build
conda-convert: /Users/user/anaconda/bin/conda-convert
conda-develop: /Users/user/anaconda/bin/conda-develop
conda-env: /Users/user/anaconda/bin/conda-env
conda-index: /Users/user/anaconda/bin/conda-index
conda-inspect: /Users/user/anaconda/bin/conda-inspect
conda-metapackage: /Users/user/anaconda/bin/conda-metapackage
conda-pipbuild: /Users/user/anaconda/bin/conda-pipbuild
conda-server: /Users/user/anaconda/bin/conda-server
conda-sign: /Users/user/anaconda/bin/conda-sign
conda-skeleton: /Users/user/anaconda/bin/conda-skeleton
user site dirs: ~/.local/lib/python2.7

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /Users/user/anaconda/bin:/usr/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/opt/X11/bin:/usr/local/git/bin:/usr/texbin:/Applications/Firefox.app/Contents/MacOS:/Applications/Julia-0.3.1.app/Contents/Resources/julia/bin:/Users/user/Dropbox/utils:/Applications/MATLAB_R2015b.app/bin:/usr/local/texlive/2014/bin/x86_64-darwin:/Users/user/Applications/VLC.app/Contents/MacOS
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /Users/user/.continuum
    /Users/user/Library/Application Support/Anaconda
    /Users/user/anaconda/licenses
License files (license*.txt):
    /Users/user/.continuum/license_academic_20150619035740.txt
               Reading license file : 1
                    Signature valid : 1
                       Vendor match : 1
                            product : u'Academic'
                           packages : u'numbapro mkl iopro'
                           end_date : u'2016-06-18'
                               type : None
    /Users/user/.continuum/license_academic_20150928050950.txt
               Reading license file : 1
                    Signature valid : 1
                       Vendor match : 1
                            product : u'Academic'
                           packages : u'numbapro mkl iopro'
                           end_date : u'2016-09-27'
                               type : None
Package/feature end dates:
    numbapro        : 2016-09-27
    iopro           : 2016-09-27
    mkl             : 2016-09-27
```

**Comment by kungfujam** [comment]
## Solved
`conda install ipyparallel` broke my conda installation
To fix I needed to move my entire conda directory and reinstall i.e.
```bash
mv ~/.anaconda ~/.anacondatmp
# download conda from https://www.continuum.io/downloads
```

## Top tip for next time
Immediately after you install, create a virtual environment so that you can easily roll back any changes you make. e.g. from a fresh install:
```bash
conda create --name py27 --clone root
```

## New issue opened
{Will reference}

**Comment by willgdjones** [comment]
Hey @kungfujam, I'm having a very similar issue to you except right from a fresh install without using ipyparallel.

`conda create -n test jupyter`

`jupyter notebook`

Traceback (most recent call last):
  File "/Users/fonz/anaconda2/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 31, in <module>
    from zmq.eventloop import ioloop
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/__init__.py", line 49, in <module>
    from zmq import backend
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 41, in <module>
    reraise(*exc_info)
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 29, in <module>
    _ns = select_backend(first)
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/fonz/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/constants.so, 2): Library not loaded: @rpath/libsodium.4.dylib
  Referenced from: /Users/fonz/anaconda2/lib/libzmq.4.dylib
  Reason: image not found

**Comment by willgdjones** [comment]
Here's my `conda env`:

#
appnope                   0.1.0                    py27_0
appscript                 1.0.1                    py27_0
argcomplete               1.0.0                    py27_1
backports                 1.0                      py27_0
backports_abc             0.4                      py27_0
beautifulsoup4            4.4.1                    py27_0
bwa                       0.7.13                        0    biobuilds
db                        6.1.26                        0    biobuilds
perl-threaded             5.22.0                       10    bioconda
bitarray                  0.8.1                    py27_0
conda                     4.1.8                    py27_0
conda-build               1.21.5                   py27_0
conda-env                 2.5.1                    py27_0
configobj                 5.0.6                    py27_0
configparser              3.5.0b2                  py27_1
decorator                 4.0.10                   py27_0
entrypoints               0.2.2                    py27_0
ghost.py                  0.2.1                    py27_0    equipoise
freetype                  2.5.5                         1
functools32               3.2.3.2                  py27_0
gdbm                      1.11                          0
get_terminal_size         1.0.0                    py27_0
httplib2                  0.9.2                     <pip>
ipykernel                 4.3.1                    py27_0
ipython                   5.0.0                    py27_0
ipython-notebook          4.0.4                    py27_0
ipython-qtconsole         4.0.1                    py27_0
ipython_genutils          0.1.0                    py27_0
ipywidgets                4.1.1                    py27_0
itsdangerous              0.24                     py27_0
jbig                      2.1                           0
jinja2                    2.8                      py27_1
jsonschema                2.5.1                    py27_0
jupyter                   1.0.0                    py27_3
jupyter_client            4.3.0                    py27_0
jupyter_console           5.0.0                    py27_0
jupyter_core              4.1.0                    py27_0
launcher                  1.0.0                         3
libsodium                 1.0.3                         0
libxslt                   1.1.28                        2
markupsafe                0.23                     py27_2
mistune                   0.7.2                    py27_1
mkl                       11.3.3                        0
multipledispatch          0.4.8                    py27_0
nbconvert                 4.2.0                    py27_0
nbformat                  4.0.1                    py27_0
node-webkit               0.10.1                        0
notebook                  4.2.1                    py27_0
openssl                   1.0.2h                        1
path.py                   8.2.1                    py27_0
pathlib2                  2.1.0                    py27_0
pexpect                   4.0.1                    py27_0
pickleshare               0.7.2                    py27_0
pip                       8.1.2                     <pip>
pip                       8.1.2                    py27_0
ply                       3.8                      py27_0
prompt_toolkit            1.0.3                    py27_0
ptyprocess                0.5.1                    py27_0
pyasn1                    0.1.9                    py27_0
pyaudio                   0.2.7                    py27_0
pycosat                   0.6.1                    py27_1
pygments                  2.1.3                    py27_0
pyqt                      4.11.4                   py27_3
python                    2.7.12                        1
python.app                1.2                      py27_4
pyyaml                    3.11                     py27_4
qt                        4.8.7                         3
qtconsole                 4.2.1                    py27_0
jpeg                      8d                            2    r
libgcc                    4.8.5                         1    r
libpng                    1.6.17                        0    r
libxml2                   2.9.2                         1    r
pyzmq                     14.5.0                   py27_1    r
singledispatch            3.4.0.3                  py27_1    r
zeromq                    4.0.5                         1    r
zlib                      1.2.8                         1    r
readline                  6.2                           2
redis                     3.2.0                         0
requests                  2.10.0                   py27_0
rope                      0.9.4                    py27_1
ruamel_yaml               0.11.7                   py27_0
setuptools                23.0.0                   py27_0
simplegeneric             0.8.1                    py27_1
sip                       4.16.9                   py27_0
six                       1.10.0                   py27_0
sqlite                    3.13.0                        0
sshuttle                  0.78.0                    <pip>
ssl_match_hostname        3.4.0.2                  py27_1
terminado                 0.6                      py27_0
tk                        8.5.18                        0
tornado                   4.3                      py27_1
traitlets                 4.2.1                    py27_0
unicodecsv                0.14.1                   py27_0
wcwidth                   0.1.7                    py27_0
wheel                     0.29.0                   py27_0
xz                        5.2.2                         0
yaml                      0.1.6                         0

**Comment by willgdjones** [comment]
and jupyter version is: jupyter 4.1.0

**Comment by willgdjones** [comment]
Nope still a problem!

**Comment by kirk86** [comment]
I've got the same issue when trying to run the `jupyter console` command

```
[ZMQTerminalIPythonApp] ERROR | Failed to run command:
[u'/usr/local/opt/python/bin/python2.7', u'-m', u'ipykernel', u'-f', u'/Users/jm/Library/Jupyter/runtime/kernel-83198.json']
    PATH='/Users/jm/anaconda2/bin:/usr/local/Cellar/open-mpi/2.0.0/bin:/Users/jm/torch/install/bin:/usr/local/bin:/usr/local:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin:/Library/TeX/texbin'
    with kwargs:
{'cwd': None, 'stdin': -1, 'preexec_fn': <function <lambda> at 0x1040cb6e0>, 'stderr': None, 'stdout': None}

Traceback (most recent call last):
  File "/Users/jm/anaconda2/bin/jupyter-console", line 5, in <module>
    app.main()
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-113>", line 2, in initialize
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_console/app.py", line 137, in initialize
    self.init_shell()
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_console/app.py", line 105, in init_shell
    JupyterConsoleApp.initialize(self)
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 334, in initialize
    self.init_kernel_manager()
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_client/consoleapp.py", line 288, in init_kernel_manager
    self.kernel_manager.start_kernel(**kwargs)
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/jm/anaconda2/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/jm/anaconda2/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/Users/jm/anaconda2/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
````
