### ISSUE TITLE
conda install ipyparallel breaks ipython notebook

### ISSUE THREAD

**Issue by kungfujam** [conda/conda#1724]
## My steps to reproduce
Take a fresh install of anaconda and
```bash
conda install mkl
conda install ipyparallel
# induces a bunch of updates to ipython notebook and related
ipython notebook
```

## Error
```
(py27)c104081:mlpractical kungfujam$ ipython notebook
Traceback (most recent call last):
  File "/Users/kungfujam/anaconda/envs/py27/bin/ipython", line 6, in <module>
    sys.exit(start_ipython())
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/IPython/__init__.py", line 118, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-111>", line 2, in initialize
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 305, in initialize
    super(TerminalIPythonApp, self).initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/IPython/core/application.py", line 386, in initialize
    self.parse_command_line(argv)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/IPython/terminal/ipapp.py", line 300, in parse_command_line
    return super(TerminalIPythonApp, self).parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 487, in parse_command_line
    return self.initialize_subcommand(subc, subargv)
  File "<decorator-gen-3>", line 2, in initialize_subcommand
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/traitlets/config/application.py", line 418, in initialize_subcommand
    subapp = import_item(subapp)
  File "/Users/kungfujam/anaconda/envs/py27/lib/python2.7/site-packages/ipython_genutils/importstring.py", line 31, in import_item
    module = __import__(package, fromlist=[obj])
ImportError: No module named notebook.notebookapp
```

## Linked issue
Issue #1722

**Comment by ilanschnell** [comment]
This was related to zeromq being updated and should be fixed now.
