### ISSUE TITLE
Environments broken?

### ISSUE THREAD

**Issue by H0R5E** [conda/conda#1729]
Hi, my environments don't seem to work properly any more, something funny with the paths, maybe:

```
[alpha] D:\Usuarios\108630\Programming\Python\hg>conda install dtocean-hydrodyna
mics
Fetching package metadata: ......
Solving package specifications: ................
Package plan for installation in environment C:\Anaconda\envs\alpha:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dtocean-hydrodynamics-0.1.0|       np19py27_1        45.9 MB

The following NEW packages will be INSTALLED:

    dtocean-hydrodynamics: 0.1.0-np19py27_1

Proceed ([y]/n)? y

Fetching packages ...
Error: Could not open u'D:\\Usuarios\\108630\\Programming\\Python\\hg\\"C:\\Anac
onda\\envs"\\.pkgs\\dtocean-hydrodynamics-0.1.0-np19py27_1.tar.bz2.part' for wri
ting ([Errno 22] invalid mode ('wb') or filename: u'D:\\Usuarios\\108630\\Progra
mming\\Python\\hg\\"C:\\Anaconda\\envs"\\.pkgs\\dtocean-hydrodynamics-0.1.0-np19
py27_1.tar.bz2.part').

[alpha] D:\Usuarios\108630\Programming\Python\hg>conda clean --packages
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func

    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_clean.py", line 340, in exe
cute
    pkgs_dirs, warnings, totalsize, pkgsizes = find_pkgs()
  File "C:\Anaconda\lib\site-packages\conda\cli\main_clean.py", line 166, in fin
d_pkgs
    pkgs = [i for i in listdir(pkgs_dir) if isdir(join(pkgs_dir, i)) and
WindowsError: [Error 123] The filename, directory name, or volume label syntax i
s incorrect: 'D:\\Usuarios\\108630\\Programming\\Python\\hg\\"C:\\Anaconda\\envs
"\\.pkgs/*.*'

[alpha] D:\Usuarios\108630\Programming\Python\hg>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda\envs\alpha
     envs directories : D:\Usuarios\108630\Programming\Python\hg\"C:\Anaconda\en
vs"
        package cache : D:\Usuarios\108630\Programming\Python\hg\"C:\Anaconda\en
vs"\.pkgs
         channel URLs : https://conda.binstar.org/t/<TOKEN>/topper/win-64/
                        https://conda.binstar.org/t/<TOKEN>/topper/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : d:\Usuarios\108630\.condarc
    is foreign system : False

**Comment by msarahan** [comment]
Please see https://github.com/ContinuumIO/anaconda-issues/issues/487 for explanation and fix.

**Comment by H0R5E** [comment]
Thank you!
