### ISSUE TITLE
Attempt to install local package raises ValueError: Empty version string

### ISSUE THREAD

**Issue by mwtoews** [conda/conda#1732]
I'm attempting to make a package:

```
$ cat spatialindex/meta.yaml
package:
  name: spatialindex
  version: "1.8.5"

source:
  fn: spatialindex-src-1.8.5.tar.bz2
  url: http://download.osgeo.org/libspatialindex/spatialindex-src-1.8.5.tar.bz2

build:
  number: 1

about:
  home: http://libspatialindex.github.io/
  license: MIT
$ cat spatialindex/build.sh
./configure --prefix=$PREFIX
make
make check
make install
```

and while the build seemes to be fine from `conda build spatialindex`, it does not install:

```
$ conda install --use-local spatialindex
Fetching package metadata: ......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/path/to/sw/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/plan.py", line 406, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/plan.py", line 350, in add_defaults_to_specs
    for spec in specs
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/plan.py", line 351, in <genexpr>
    for fn in r.get_max_dists(MatchSpec(spec))
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 563, in get_max_dists
    pkgs = self.get_pkgs(ms, max_only=True)
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 544, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/path/to/sw/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 149, in __init__
    raise ValueError("Empty version string.")
ValueError: Empty version string.
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /path/to/sw/anaconda  (writable)
  default environment : /path/to/sw/anaconda
     envs directories : /path/to/sw/anaconda/envs
        package cache : /path/to/sw/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by yoavram** [comment]
Same here.

```
[test] D:\workspace\curveball_project\code>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : D:\Anaconda3  (writable)
  default environment : D:\Anaconda3\envs\test
     envs directories : D:\Anaconda3\envs
        package cache : D:\Anaconda3\pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/yoavram/win-64/
                        https://conda.anaconda.org/t/<TOKEN>/yoavram/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\yoavram\.condarc
    is foreign system : False
```

**Comment by postelrich** [comment]
I ran into the same issue.  I was able to fix by deleting old packages located in anaconda/conda-bld/<ARCH> and rebuilding my package.

**Comment by yoavram** [comment]
@postelrich which subfolders of `anaconda/conda-bld` did you delete?

**Comment by cidermole** [comment]
I just ran into the same issue, thanks for the workaround.

**Comment by soapy1** [comment]
This doesn't seem to be an issue on the newest version of conda. Please update, and if this still fails,  reopen the issue.
