### ISSUE TITLE
exception on install process

### ISSUE THREAD

**Issue by renatoln** [conda/conda#1737]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    except Exception as e:
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 612, in inner
    yield
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 413, in install
    common.check_write(command, prefix)
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/plan.py", line 527, in execute_actions
    add_unlink(actions, dist)
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Users/renatonovais/anaconda/lib/python3.4/site-packages/conda/install.py", line 671, in unlink
    'type': link_name_map.get(linktype)}
FileNotFoundError: [Errno 2] No such file or directory: '/Users/renatonovais/anaconda/conda-meta/astropy-1.0.3-np19py34_0.json'

**Comment by soapy1** [comment]
@renatoln is this still an issue for you?
