### ISSUE TITLE
conda clean -pt with empty package cache and non-root user

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda#1752]
I have a root miniconda install at /opt/anaconda.  I ran 
```
conda clean -pt 
```
successfully as root then immediately tried running the same command as a lesser user.  I got this error even though the package cache was empty:
```
Cache location: 
There are no tarballs to remove
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/envs/anaconda.org/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_clean.py", line 340, in execute
    pkgs_dirs, warnings, totalsize, pkgsizes = find_pkgs()
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_clean.py", line 166, in find_pkgs
    pkgs = [i for i in listdir(pkgs_dir) if isdir(join(pkgs_dir, i)) and
OSError: [Errno 2] No such file or directory: '/home/user5/envs/.pkgs'
```

**Comment by PeterDSteinberg** [comment]
Appears somewhat related to #1751.  Fixing #1751 and #1752 is necessary for the future needs of anaconda-build.

**Comment by ijstokes** [comment]
Also an outcome of the meta-issue #1329
