### ISSUE TITLE
error installing R essentials into environment

### ISSUE THREAD

**Issue by ColinTalbert** [conda/conda#1755]
I'm trying to install R essentials into a clean activated environment and I get the error below.  It install just fine into the root.

C:\Anaconda>conda create -n testenvironment numpy
Fetching package metadata: ........
Solving package specifications: ...........
Package plan for installation in environment C:\Anaconda\envs\testenvironment:

The following NEW packages will be INSTALLED:

    msvc_runtime: 1.0.0-vc9_0   defaults [vc9]
    numpy:        1.10.1-py27_0 defaults
    pip:          7.1.2-py27_0  defaults
    python:       2.7.10-3      defaults
    setuptools:   18.4-py27_0   defaults
    wheel:        0.26.0-py27_1 defaults

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate testenvironment
#

C:\Anaconda>activate testenvironment
Activating environment "C:\Anaconda\envs\testenvironment"...

[testenvironment] C:\Anaconda>conda install -c r r-essentials
Fetching package metadata: ..........
Solving package specifications: ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 333, in install
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 1057, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 809, in solve2
    dists = self.get_dists(specs, filtered=True)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 710, in get_dists
    filtered = self.prune_packages(specs)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 506, in prune_packages
    if sum(touch(fn) for fn in self.find_matches(ms, True)) == 0:
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 506, in <genexpr>
    if sum(touch(fn) for fn in self.find_matches(ms, True)) == 0:
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 496, in touch
    touch(f2, force)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 492, in touch
    val = touched[fn] = force or is_valid(fn)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in is_valid
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in is_valid
....<<This recursive error stack continues for some time, but omitted here>>
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in is_valid
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 515, in find_matches
    for fn in self.groups[ms.name]:
RuntimeError: maximum recursion depth exceeded in cmp

[testenvironment] C:\Anaconda>

Thanks,
Colin

**Comment by ccordoba12** [comment]
This was be fixed in pull request #1749, and will be released in the next conda version.

Sorry for the inconvenience.

**Comment by ColinTalbert** [comment]
As always, You guys ROCK!

Colin Talbert
GIS Analyst and Developer
US Geological Survey

talbertc@usgs.gov

USGS Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425

USGS North Central Climate Science Center
(970) 492-4283

Work schedule:
Monday       - 7:00 - 3:00  (FORT)
Tuesday       -  7:00 - 3:00  (NC CSC)
Wednesday  -  7:00 - 3:00 (FORT)
Thursday      -  7:00 - 5:00 (FORT)
Friday          -  7:00 - 5:00 (FORT)
