### ISSUE TITLE
conda update failed

### ISSUE THREAD

**Issue by benrifkind** [conda/conda#1756]
Not sure what happened but when I ran
conda update --prefix /pathtoanaconda/anaconda anaconda

I got the following traceback

An unexpected error has occurred, please consider sending the  
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/Ben/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 415, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/plan.py", line 532, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/Ben/anaconda/lib/python2.7/site-packages/conda/install.py", line 588, in link
    os.makedirs(dst_dir)
  File "/Users/Ben/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/Ben/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/tests'

Now if I try to run it again
conda update --prefix /pathtoanaconda/anaconda anaconda

I get
Error: package 'anaconda' is not installed in /Users/Ben/anaconda

Current conda install:

```
 platform : osx-64
 conda version : 3.16.0
```

  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/Ben/anaconda  (writable)
  default environment : /Users/Ben/anaconda
     envs directories : /Users/Ben/anaconda/envs
        package cache : /Users/Ben/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by soapy1** [comment]
@benrifkind is this still an issue for you?
