### ISSUE TITLE
menuinst installation fails on win7-64bit, py2.7.8-32bit, miniconda 

### ISSUE THREAD

**Issue by denfromufa** [conda/conda#1758]
```
Python 2.7.8 |Continuum Analytics, Inc.| (default, Jul  2 2014, 15:13:35) [MSC v
.1500 32 bit (Intel)] on win32
```

```
Unlinking packages ...
menuinst Exception:Traceback (most recent call last):                    |  14%
  File "C:\Python\Miniconda\lib\site-packages\conda\install.py", line 309, in mk
_menus
  File "C:\Python\Miniconda\lib\site-packages\menuinst\__init__.py", line 44, in
 install
    env_setup_cmd=env_setup_cmd).remove()
  File "C:\Python\Miniconda\lib\site-packages\menuinst\win32.py", line 105, in r
emove
    self.create(remove=True)
  File "C:\Python\Miniconda\lib\site-packages\menuinst\win32.py", line 113, in c
reate
    cmd = bat_func('python.exe', self.shortcut["pyscript"].split())
  File "C:\Python\Miniconda\lib\site-packages\menuinst\win32.py", line 80, in wr
ite_bat_file
    setup_cmd = setup_cmd.split()  # split into activate cmd + env
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by kalefranz** [comment]
Old ticket.  Should be fixed.
