### ISSUE TITLE
unexpected error when instaling mayavi

### ISSUE THREAD

**Issue by HugoSiles** [conda/conda#1760]
Hello,
I get the following message when installing mayavi. I have installed before without any problem, somewhere in the traceback  you will find :   # This shouldn't be an issue in the installer anyway.
but it doesn't install. any help will be appreciated.
Hugo

An unexpected error has occurred, please consider sending the            |  76%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\main.py", line 201
, in main
    try:
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\main.py", line 208
, in args_func
    except Exception as e:
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\common.py", line 6
12, in inner
    yield
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\main_install.py",
line 46, in execute

  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\cli\install.py", line
413, in install
    common.check_write(command, prefix)
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\plan.py", line 527, in
 execute_actions
    add_unlink(actions, dist)
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\instructions.py", line
 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\instructions.py", line
 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\instructions.py", line
 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\install.py", line 624,
 in link
    # This shouldn't be an issue in the installer anyway
  File "C:\Users\Usuario\Anaconda\lib\site-packages\conda\install.py", line 347,
 in run_script

  File "C:\Users\Usuario\Anaconda\lib\subprocess.py", line 535, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "C:\Users\Usuario\Anaconda\lib\subprocess.py", line 522, in call
    return Popen(_popenargs, *_kwargs).wait()
  File "C:\Users\Usuario\Anaconda\lib\subprocess.py", line 710, in **init**
    errread, errwrite)
  File "C:\Users\Usuario\Anaconda\lib\subprocess.py", line 958, in _execute_chil
d
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

C:\Users\Usuario>conda info
Current conda install:

```
         platform : win-32
    conda version : 3.18.3
```

  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\Users\Usuario\Anaconda  (writable)
  default environment : C:\Users\Usuario\Anaconda
     envs directories : C:\Users\Usuario\Anaconda\envs
        package cache : C:\Users\Usuario\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by tyler-thetyrant** [comment]
closing outdated.
