### ISSUE TITLE
conda search gives ValueError: Malformed version string '.post': empty version component. 

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1774]
```
$conda search -c danielballan
Fetching package metadata: ..................................
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main_search.py", line 120, in execute
    execute_search(args, parser)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main_search.py", line 221, in execute_search
    pkgs = sorted(r.get_pkgs(ms_name))
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 544, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 544, in <listcomp>
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 360, in __init__
    self.norm_version = VersionOrder(self.version)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 187, in __init__
    raise ValueError(message + "empty version component.")
ValueError: Malformed version string '.post': empty version component.
```

@ukoethe

**Comment by ukoethe** [comment]
From the point of view of the VersionOrder class, the error message is actually correct: the version string `.post` has an empty version component before the dot, which is illegal. A valid version string would be something like `1.post` or `1.2.3post1`. One could easily change this rule (e.g. by interpreting empty components as zeros), but then a version like `...` (only dots) would become legal (it would be interpreted as `0.0.0.0`). I'm sceptical if this is desirable.

The interesting question is *why* the version string `.post` was passed to VersionOrder. There are two possibilities: Either, channel danielballan actually contains a package with an illegal version number. Or conda has a bug in version string parsing that causes part of the version string to be eaten away.

**Comment by CJ-Wright** [comment]
I am getting this error as well:
```
christopher@christopher-ubuntu /media/christopher/DATA/dev/xpdAcq xrun $ conda search -c danielball
........................................................................ an
Fetching package metadata .....................

The following stack trace is in reference to package:

	tacaswell::bubblegum-.post-_np19py27.tar.bz2

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/christopher/mc/envs/dp_dev3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main_search.py", line 123, in execute
    execute_search(args, parser)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main_search.py", line 202, in execute_search
    pkgs = sorted(r.get_pkgs(ms_name))
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 676, in get_pkgs
    pkgs = [Package(fkey, self.index[fkey]) for fkey in self.find_matches(ms)]
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 235, in __init__
    self.norm_version = normalized_version(self.version)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/version.py", line 12, in normalized_version
    return VersionOrder(version)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/version.py", line 182, in __init__
    raise ValueError(message + "empty version component.")
ValueError: Malformed version string '.post': empty version component.
```

**Comment by ukoethe** [comment]
As I explained above, it is forbidden to have nothing before the dot like in `'.post'`. The error message is right complaining about a malformed version string.

**Comment by kalefranz** [comment]
I can also tell by the output you are using a very old version of conda. Please `conda update conda`.

**Comment by CJ-Wright** [comment]
@kalefranz This was done with 4.1.12
```
christopher@christopher-ubuntu ~ $ conda update conda
Fetching package metadata ...................
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /home/christopher/mc:
#
conda                     4.1.12                   py27_0    conda-forge
```
