### ISSUE TITLE
error in "conda info"

### ISSUE THREAD

**Issue by tkamishima** [conda/conda#1780]
I got the following error when typing `conda info ipython` on MacOS X 10.10.5.
It seems the variable `envs_dir` is not set correctly in a `api.py` file.   It should be `/Users/myaccount/.conda/envs` , but it is `/Users/myaccount/envs/` .

```
Fetching package metadata: ....

ipython 0.13 py27_0
-------------------
file name   : ipython-0.13-py27_0.tar.bz2
name        : ipython
version     : 0.13
build number: 0
build string: py27_0
channel     : defaults
size        : 1.5 MB
date        : 2014-08-22
license     : BSD
md5         : d0b49e08325f1132655ce5b2fd247205
installed environments:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 179, in execute
    pretty_package(pkg)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 141, in pretty_package
    for env in app_is_installed(pkg.fn):
  File "/anaconda/lib/python2.7/site-packages/conda/api.py", line 107, in app_is_installed
    for fn2 in os.listdir(envs_dir):
OSError: [Errno 2] No such file or directory: '/Users/myaccount/envs'
```

**Comment by tyler-thetyrant** [comment]
Closing as I cannot replicate the error with the recent version of conda.
