### ISSUE TITLE
conda list fails: unknown encoding

### ISSUE THREAD

**Issue by sorrge** [conda/conda#1788]
The command "conda list" fails with the following output:

```
# packages in environment at C:\Anaconda\envs\py34:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_list.py", line 237, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_list.py", line 177, in print_packages
    print('\n'.join(output))
LookupError: unknown encoding: cp65001
```

Here is the output of "conda info":

```
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda\envs\py34
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

This is on Windows 7.

**Comment by tyler-thetyrant** [comment]
Closing outdated.
