### ISSUE TITLE
Attempting to upgrade from python 3.4 to python 3.5

### ISSUE THREAD

**Issue by pblelloch** [conda/conda#1794]
Based on a web post I attempted to upgrade from python 3.4 to 3.5 as follows:

conda install python=3.5
conda install anaconda

This resulted in the following dump:

C:\Users\test>conda install anaconda
Fetching package metadata: ....
Solving package specifications: ..................................................................................................................................................................................................An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\test\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\test\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Users\test\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\test\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\test\Anaconda\lib\site-packages\conda\cli\install.py", line 333, in install
    update_deps=args.update_deps)
  File "C:\Users\test\Anaconda\lib\site-packages\conda\plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "C:\Users\test\Anaconda\lib\site-packages\conda\resolve.py", line 1057, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "C:\Users\test\Anaconda\lib\site-packages\conda\resolve.py", line 819, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Users\test\Anaconda\lib\site-packages\conda\resolve.py", line 624, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: ipython-qtconsole-4.0.1-py35_4.tar.bz2 MatchSpec('menuinst 1.2.0')

**Comment by pblelloch** [comment]
P.S. Result of conda info is:

Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.11.0
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Users\test\Anaconda  (writable)
  default environment : C:\Users\test\Anaconda
     envs directories : C:\Users\test\Anaconda\envs
        package cache : C:\Users\test\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by schodge** [comment]
I was able to, on Windows, do the upgrade OK, but subsequent upgrades of packages are failing:

```
Unlinking packages ...
WARNING:root:Menuinst could not be imported:                             |   6%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 326, in mk_menus
    import menuinst
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 19, in <module>
    from .win32 import Menu, ShortCut
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 13, in <module>
    from .winshortcut import create_shortcut
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 692, in unlink
    mk_menus(prefix, meta['files'], remove=True)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 329, in mk_menus
    logging.warn(e.message)
AttributeError: 'ImportError' object has no attribute 'message'
```

```
λ conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.12.0
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by pblelloch** [comment]
I tried the same sequence on a different Windows Computer (7 this time instead of 10) and got exactly the same error.  The only work around that I found was to uninstall anaconda and then install from a clean download.   It does seem strange to me that it’s so hard to upgrade the version of python within Anaconda.  I know that I can create a new environment, but I want my default version of python to update.  I had exactly the same (or very similar at least) problem when going from 2.7 to 3.4 and ended up with a complete reinstall.  Why is it so hard to shift up a version of python?

**Comment by JonathanTay** [comment]
Same issue. Crashed out when I tried conda create -n py35 python=3.5 anaconda.Same errors and conda info dump as pBlelloch. 

Oddly enough, conda update anaconda says I have Anaconda 2.4 installed even though my default python version is 3.4 ( I thought anaconda 2.4 had Py3.5 installed by default?)

**Comment by PerryGrossman** [comment]
Same problem on Ubuntu 14.04:

perry@perry-Leopard-Extreme:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.4
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /home/perry/anaconda3  (writable)
  default environment : /home/perry/anaconda3
     envs directories : /home/perry/anaconda3/envs
        package cache : /home/perry/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

perry@perry-Leopard-Extreme:~$

**Comment by msarahan** [comment]
@PerryGrossman you are getting menuinst errors on Mac?  Please post your error output.

Generally, please try installing menuinst, then re-try the update/upgrade.  Menuinst should not be a hard requirement.  We should handle this error much better, and I'll look into it.

**Comment by PerryGrossman** [comment]
This error is on Ubuntu: this is the error output:

Extracting packages ...
An unexpected error has occurred, please consider sending the######       |  87%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/perry/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/install.py", line 482, in extract
    t.extractall(path=path)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 1980, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir())
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 2019, in extract
    set_attrs=set_attrs)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 2088, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 2134, in makefile
    copyfileobj(source, target, tarinfo.size)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 239, in copyfileobj
    buf = src.read(BUFSIZE)
  File "/home/perry/anaconda3/lib/python3.4/bz2.py", line 293, in read
    return self._read_block(size)
  File "/home/perry/anaconda3/lib/python3.4/bz2.py", line 254, in _read_block
    while n > 0 and self._fill_buffer():
  File "/home/perry/anaconda3/lib/python3.4/bz2.py", line 218, in _fill_buffer
    self._buffer = self._decompressor.decompress(rawblock)
OSError: Invalid data stream

**Comment by msarahan** [comment]
@PerryGrossman that appears to be a different issue.  My first guess would be that a .bz2 file did not get downloaded properly.  Run conda clean --tarballs --packages and try again.  If the problem recurs, please file a different issue.
