### ISSUE TITLE
Issue Updating Anaconda 

### ISSUE THREAD

**Issue by PerryGrossman** [conda/conda#1799]
On Ubuntu 14.04: Updating anaconda to go from python 3.4 to python 3.5, I got this errror: 
"OSError: Invalid data stream"

On advice I ran conda clean --tarballs --packages and tried again. It says it has the packages, but does not update to python 3.5:

Extracting packages ...
An unexpected error has occurred, please consider sending the######       |  87%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/perry/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/home/perry/anaconda3/lib/python3.4/site-packages/conda/install.py", line 482, in extract
    t.extractall(path=path)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 1980, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir())
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 2019, in extract
    set_attrs=set_attrs)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 2088, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 2134, in makefile
    copyfileobj(source, target, tarinfo.size)
  File "/home/perry/anaconda3/lib/python3.4/tarfile.py", line 239, in copyfileobj
    buf = src.read(BUFSIZE)
  File "/home/perry/anaconda3/lib/python3.4/bz2.py", line 293, in read
    return self._read_block(size)
  File "/home/perry/anaconda3/lib/python3.4/bz2.py", line 254, in _read_block
    while n > 0 and self._fill_buffer():
  File "/home/perry/anaconda3/lib/python3.4/bz2.py", line 218, in _fill_buffer
    self._buffer = self._decompressor.decompress(rawblock)
OSError: Invalid data stream
perry@perry-Leopard-Extreme:~$ conda update anaconda
Fetching package metadata: ....
Solving package specifications: ............................................................................................................................................................

---getting advice:
Mike Sarahan notifications@github.com
12:54 PM (11 minutes ago)
to conda/conda, me 
@PerryGrossman that appears to be a different issue. My first guess would be that a .bz2 file did not get downloaded properly. Run conda clean --tarballs --packages and try again. If the problem recurs, please file a different issue.

---next steps

conda clean --tarballs --packages
...
removing openblas-0.2.14-1
removing xlsxwriter-0.7.3-py34_0
perry@perry-Leopard-Extreme:/media/perry/Extra Drive 1$ python
Python 3.4.3 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > quit()

---But, it still will now update:

perry@perry-Leopard-Extreme:~$ conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/perry/anaconda3:
# 

conda                     3.18.4                   py34_0  
perry@perry-Leopard-Extreme:~$ 

perry@perry-Leopard-Extreme:~$ conda update anaconda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at /home/perry/anaconda3:
# 

anaconda                  2.4.0               np110py34_0  
perry@perry-Leopard-Extreme:~$ 

perry@perry-Leopard-Extreme:~$ python
Python 3.4.3 |Anaconda 2.4.0 (64-bit)| (default, Oct 19 2015, 21:52:17) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.

perry@perry-Leopard-Extreme:~$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.18.4
```

  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /home/perry/anaconda3  (writable)
  default environment : /home/perry/anaconda3
     envs directories : /home/perry/anaconda3/envs
        package cache : /home/perry/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

perry@perry-Leopard-Extreme:~$

**Comment by ijstokes** [comment]
Perry, where are you right now with this?  Do you have a broken Anaconda install?  In my experience I wouldn't recommend updating the Python version in the root Anaconda install.  I'd create a new one, eg. by doing:

```bash
conda create -n ana35 anaconda python=3.5
```

But maybe you're just reporting this because you had an error that told you to do so.

Let us know if you need more help sorting out an issue or if something still seems broken.

**Comment by PerryGrossman** [comment]
Thanks, Ian!
That works.
Perry
