### ISSUE TITLE
Ongoing conda problems with self update

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#1803]
Notice that I didn't actually even want to update conda, but because I hadn't used `--no-update-deps` (#337 and #1358) conda broke itself during the update from 3.18.3 to 3.18.4.

``` bash
$ conda install pycrypto
Fetching package metadata: ....
Solving package specifications: .................
Package plan for installation in environment /Users/ijstokes/anaconda:

The following packages will be UPDATED:

    conda: 3.18.3-py27_0 --> 3.18.4-py27_0

Proceed ([y]/n)? y

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/bin/conda", line 5, in <module>
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/install.py", line 631, in link
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/install.py", line 132, in _link
  File "/Users/ijstokes/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/ijstokes/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/ijstokes/anaconda/pkgs/conda-3.18.4-py27_0/bin/activate'
```

**Comment by ijstokes** [comment]
Right, which leaves things in this state:

```bash
$ conda update conda
-bash: /Users/ijstokes/anaconda/bin/conda: No such file or directory
```

**Comment by teoliphant** [comment]
What is conda info -e for you?   What platform are you on?  It looks like Mac.   This worked for me.

**Comment by kalefranz** [comment]
Conda no longer uninstalls itself when updates fail! 🎉
