### ISSUE TITLE
Too many levels of symbolic links when installing into virtual environment

### ISSUE THREAD

**Issue by jasonstrimpel** [conda/conda#1809]
Ran the command `conda install pandas` in my virtual environment, completed but eventually failed.

```
(/Users/jason/Work/bespokeoptions/env)Jasons-MacBook-Pro-2:bespokeoptions jason$ conda install pandas
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /Users/jason/Work/bespokeoptions/env:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2d             |                0         3.0 MB
    numpy-1.10.1               |           py27_0         3.0 MB
    python-2.7.10              |                2         9.9 MB
    pytz-2015.7                |           py27_0         174 KB
    setuptools-18.4            |           py27_0         342 KB
    six-1.10.0                 |           py27_0          16 KB
    wheel-0.26.0               |           py27_1          76 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    python-dateutil-2.4.2      |           py27_0         219 KB
    pandas-0.17.0              |      np110py27_0         6.2 MB
    ------------------------------------------------------------
                                           Total:        24.3 MB

The following NEW packages will be INSTALLED:

    numpy:           1.10.1-py27_0     
    openssl:         1.0.2d-0          
    pandas:          0.17.0-np110py27_0
    pip:             7.1.2-py27_0      
    python:          2.7.10-2          
    python-dateutil: 2.4.2-py27_0      
    pytz:            2015.7-py27_0     
    readline:        6.2-2             
    setuptools:      18.4-py27_0       
    six:             1.10.0-py27_0     
    sqlite:          3.8.4.1-1         
    tk:              8.5.18-0          
    wheel:           0.26.0-py27_1     
    zlib:            1.2.8-0           

Proceed ([y]/n)? y

Fetching packages ...
openssl-1.0.2d 100% |###############################################################################################################################| Time: 0:01:29  35.05 kB/s
numpy-1.10.1-p 100% |###############################################################################################################################| Time: 0:01:27  36.21 kB/s
python-2.7.10- 100% |###############################################################################################################################| Time: 0:04:04  42.27 kB/s
pytz-2015.7-py 100% |###############################################################################################################################| Time: 0:00:02  70.28 kB/s
setuptools-18. 100% |###############################################################################################################################| Time: 0:00:05  64.18 kB/s
six-1.10.0-py2 100% |###############################################################################################################################| Time: 0:00:01   9.47 kB/s
wheel-0.26.0-p 100% |###############################################################################################################################| Time: 0:00:01  67.53 kB/s
pip-7.1.2-py27 100% |###############################################################################################################################| Time: 0:00:17  81.26 kB/s
python-dateuti 100% |###############################################################################################################################| Time: 0:00:04  49.27 kB/s
pandas-0.17.0- 100% |###############################################################################################################################| Time: 0:02:53  37.79 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the###################################                                                                         |  50%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/jason/Work/bespokeoptions/env/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/install.py", line 534, in link
    _link(src, dst, lt)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/install.py", line 133, in _link
    shutil.copy2(src, dst)
  File "/usr/local/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 62] Too many levels of symbolic links: '/Users/jason/Work/bespokeoptions/env/bin/python2.7'
(/Users/jason/Work/bespokeoptions/env)Jasons-MacBook-Pro-2:bespokeoptions jason$ python
-bash: /Users/jason/Work/bespokeoptions/env/bin/python: Too many levels of symbolic links
```

**Comment by kalefranz** [comment]
This issue should be fixed in recent versions of conda.  Latest is conda 4.3.17.
