### ISSUE TITLE
Unexpected IOError during conda update

### ISSUE THREAD

**Issue by vobine** [conda/conda#1810]
Conda command halted during a routine update. Command line:

`conda update -n py3 --all`

The update went normally, then stopped with an unexpected exception. Here is the traceback:

```
Traceback (most recent call last):
  File "C:\Anaconda\Anaconda-2.3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\cli\main.py", line 195,
in main
    args_func(args, p)
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\cli\main.py", line 202,
in args_func
    args.func(args, p)
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\cli\main_update.py", li
ne 48, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\cli\install.py", line 4
23, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\plan.py", line 537, in
execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\instructions.py", line
148, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\instructions.py", line
62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Anaconda\Anaconda-2.3\lib\site-packages\conda\install.py", line 482,
in extract
    t.extractall(path=path)
  File "C:\Anaconda\Anaconda-2.3\lib\tarfile.py", line 2072, in extractall
    self.extract(tarinfo, path)
  File "C:\Anaconda\Anaconda-2.3\lib\tarfile.py", line 2109, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Anaconda\Anaconda-2.3\lib\tarfile.py", line 2185, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Anaconda\Anaconda-2.3\lib\tarfile.py", line 2225, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 22] invalid mode ('wb') or filename: u'C:\\Anaconda\\Anaconda-2.
3\\pkgs\\sympy-0.7.6.1-py34_0\\Lib\\site-packages\\sympy\\strategies\\branch\\tr
averse.py'
```

Output from `conda info`:

```
Current conda install:

             platform : win-32
        conda version : 3.18.4
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda\Anaconda-2.3  (writable)
  default environment : C:\Anaconda\Anaconda-2.3
     envs directories : C:\Anaconda\Anaconda-2.3\envs
        package cache : C:\Anaconda\Anaconda-2.3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

I ran the update again and everything seems to have worked the second time: no unexpected errors, the command ran to completion, and the py3 environment appears to be running properly..

**Comment by kalefranz** [comment]
Ticket is for conda version 3.18.4.  `conda update conda`
