### ISSUE TITLE
"Maximum recursion depth" error while installing package

### ISSUE THREAD

**Issue by rohanp** [conda/conda#1818]
```
conda install binstar
Fetching package metadata: ....
Solving package specifications: 
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/rohanp/anaconda/envs/LDFMap/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 1057, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 809, in solve2
    dists = self.get_dists(specs, filtered=True)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 710, in get_dists
    filtered = self.prune_packages(specs)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 506, in prune_packages
    if sum(touch(fn) for fn in self.find_matches(ms, True)) == 0:
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 506, in <genexpr>
    if sum(touch(fn) for fn in self.find_matches(ms, True)) == 0:
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 496, in touch
    touch(f2, force)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 492, in touch
    val = touched[fn] = force or is_valid(fn)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in is_valid
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in is_valid
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
````
and so on, until eventually

```
 File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in is_valid
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 516, in find_matches
    if self.filter_[fn] and ms.match(fn):
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 325, in match
    return any(vs.match(version) for vs in self.vspecs)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 325, in <genexpr>
    return any(vs.match(version) for vs in self.vspecs)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 301, in match
    return all(c.match(version) for c in self.constraints)
  File "/Users/rohanp/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 301, in <genexpr>
    return all(c.match(version) for c in self.constraints)
RuntimeError: maximum recursion depth exceeded
```

```
conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.11.0
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : /Users/rohanp/anaconda  (writable)
  default environment : /Users/rohanp/anaconda/envs/LDFMap
     envs directories : /Users/rohanp/anaconda/envs
        package cache : /Users/rohanp/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by groutr** [comment]
You need to update conda to at least 3.18.4
