### ISSUE TITLE
Documentation for track_features in .condarc is incorrect

### ISSUE THREAD

**Issue by aberant** [conda/conda#1819]
In your documentation about track_features...
http://conda.pydata.org/docs/config.html#track-features-track-features

It shows adding the features as an array which results in this ( conda 3.18.5 )

```
$ conda --version
Traceback (most recent call last):
  File "/home/me/miniconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/me/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 106, in main
    from conda.cli import conda_argparse
  File "/home/me/miniconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 17, in <module>
    from conda.cli import common
  File "/home/me/miniconda2/lib/python2.7/site-packages/conda/cli/common.py", line 11, in <module>
    import conda.config as config
  File "/home/me/miniconda2/lib/python2.7/site-packages/conda/config.py", line 363, in <module>
    track_features = set(rc['track_features'].split())
AttributeError: 'list' object has no attribute 'split'
```

I also get this when i add track_features like this

> conda config --add track_features myfeature

I thought maybe it would work if the value was a string.  That's when i discovered this:

```
$ conda config --set track_features myfeature
Error: Error key must be one of always_yes, root_dir, channel_alias, add_anaconda_token, add_pip_as_python_dependency, show_channel_urls, update_dependencies, changeps1, allow_softlinks, anaconda_upload, binstar_upload, use_pip, offline, allow_other_channels, add_binstar_token, ssl_verify, always_copy, not track_features
```

**Comment by kalefranz** [comment]
Fixed in conda 4.2.
