### ISSUE TITLE
Terminal problem with (probably incorrect) use of glob

### ISSUE THREAD

**Issue by russel** [conda/conda#1823]
```
|> conda list *pyqt*
# packages in environment at /home/users/russel/lib.Linux.x86_64/Miniconda3:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 246, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 180, in print_packages
    show_channel_urls=show_channel_urls)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 132, in list_packages
    for dist in get_packages(installed, regex):
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 117, in get_packages
    pat = re.compile(regex, re.I) if regex else None
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
```

As requested:

```
|> conda info
Current conda install:

             platform : linux-64
        conda version : 3.18.5
  conda-build version : not installed
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : /home/users/russel/lib.Linux.x86_64/Miniconda3  (writable)
  default environment : /home/users/russel/lib.Linux.x86_64/Miniconda3
     envs directories : /home/users/russel/lib.Linux.x86_64/Miniconda3/envs
        package cache : /home/users/russel/lib.Linux.x86_64/Miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
