### ISSUE TITLE
Unexpected error while installing glueviz

### ISSUE THREAD

**Issue by hitaysh** [conda/conda#1825]
## An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Users/aysh/anaconda/lib/python2.7/site-packages/conda/install.py", line 689, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/Users/aysh/anaconda/conda-meta/astropy-1.0.3-np19py27_0.json'

## Include the output of the command 'conda info' in your report.

Current conda install:

             platform : osx-64
        conda version : 3.18.5
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /Users/aysh/anaconda  (writable)
  default environment : /Users/aysh/anaconda
     envs directories : /Users/aysh/anaconda/envs
        package cache : /Users/aysh/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ilanschnell** [comment]
Thanks for the bug report.  I cannot reproduce the issue.  It probably has a lot to do with the commands you ran earlier, or some other state of your system.
