### ISSUE TITLE
Issue with conda install pyodbc

### ISSUE THREAD

**Issue by mchang1011** [conda/conda#1827]
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 711, in unlink
    os.unlink(meta_path)
PermissionError: [WinError 5] Access is denied: 'C:\Anaconda3\conda-meta\cond
a-3.18.3-py35_0.json'

Here's conda info:

Current conda install:

```
         platform : win-64
    conda version : 3.18.3
```

  conda-build version : 1.18.1
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by tyler-thetyrant** [comment]
Cannot replicate the error with the recent version of conda. 
Closing outdated.
