### ISSUE TITLE
error when running 'conda install jupyter' on Windows

### ISSUE THREAD

**Issue by morrna** [conda/conda#1836]
I am trying to install Jupyter for Python 3.4 . I installed Python and Conda from the Pyzo package originally.

Here is the error traceback:
Traceback (most recent call last):
  File "C:\pyzo2014a\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\pyzo2014a\lib\site-packages\conda\cli\main.py", line 179, in main

  File "C:\pyzo2014a\lib\site-packages\conda\cli\main_install.py", line 45, in e
xecute
    install.install(args, parser, 'install')
  File "C:\pyzo2014a\lib\site-packages\conda\cli\install.py", line 278, in insta
ll
    latest = pkgs[-1]
  File "C:\pyzo2014a\lib\site-packages\conda\plan.py", line 436, in execute_acti
ons
    else:
  File "C:\pyzo2014a\lib\site-packages\conda\plan.py", line 418, in execute_plan

    if is_root_prefix(prefix):
  File "C:\pyzo2014a\lib\site-packages\conda\plan.py", line 374, in link

  File "C:\pyzo2014a\lib\site-packages\conda\install.py", line 486, in link
    # of extracted files.  However, we want root to be the owner
  File "C:\pyzo2014a\lib\site-packages\conda\install.py", line 210, in update_pr
efix
    yield line
OSError: [Errno 22] Invalid argument: 'C:\\pyzo2014a\\"Library\\bin\\pyuic4.bat"
'

Here is the output of 'conda info':
Error: could not import yaml (required to read .condarc config file: C:\pyzo2014a\.cond
rc)

It's late at night, so I may be missing something obvious to make this work. I'll edit this if I find a solution.

**Comment by ccordoba12** [comment]
This seems an error with Pyzo nor with Anaconda.

So please report this problem with Pyzo maintainers or install Anaconda from our official installers and open a new bug if things are not working fine for you in that case :-)
