### ISSUE TITLE
Error while updating scikit-learn from 0.16 to 0.17 on windows7

### ISSUE THREAD

**Issue by rockbottom123** [conda/conda#1838]
I am using Anaconda distribution of python (2.7). While updating to scikit-learn to 0.17 I ran into some issue which also deleted all the previous installation of scikit learn and its dependencies,now I am not able to use scikit learn at all. Here is the screen shot.. Help is appreciated.
![untitled](https://cloud.githubusercontent.com/assets/13791095/11239087/cd3c5fee-8e0f-11e5-947c-9af4c5b5e2f4.jpg)

**Comment by mmagnuski** [comment]
I'm having a very similar problem. Access denied and then conda is no longer recognized:

```
λ conda install matplotlib pandas seaborn
Fetching package metadata: ....
Solving package specifications: ........................................
Package plan for installation in environment C:\Users\Mikuś\Miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |           vc14_0         177 KB
    libpng-1.6.17              |           vc14_1         464 KB
    msvc_runtime-1.0.1         |           vc14_0         2.2 MB
    openssl-1.0.2d             |           vc14_0         4.0 MB
    tk-8.5.18                  |           vc14_0         2.2 MB
    zlib-1.2.8                 |           vc14_2         109 KB
    libtiff-4.0.6              |           vc14_0         461 KB
    python-3.5.0               |                3        36.2 MB
    conda-env-2.4.4            |           py35_2          51 KB
    numpy-1.10.1               |           py35_0        99.3 MB
    pyparsing-2.0.3            |           py35_0          65 KB
    pytz-2015.7                |           py35_0         167 KB
    qt-4.8.7                   |           vc14_4        52.1 MB
    setuptools-18.4            |           py35_0         450 KB
    sip-4.16.9                 |           py35_2         229 KB
    six-1.10.0                 |           py35_0           8 KB
    wheel-0.26.0               |           py35_1          81 KB
    conda-3.18.5               |           py35_0         223 KB
    pip-7.1.2                  |           py35_0         1.5 MB
    pyqt-4.11.4                |           py35_3         3.8 MB
    python-dateutil-2.4.2      |           py35_0         220 KB
    scipy-0.16.0               |      np110py35_0         8.6 MB
    matplotlib-1.4.3           |      np110py35_3        40.0 MB
    pandas-0.17.0              |      np110py35_0         5.8 MB
    seaborn-0.6.0              |      np110py35_0         112 KB
    ------------------------------------------------------------
                                           Total:       258.4 MB

The following NEW packages will be INSTALLED:

    jpeg:            8d-vc14_0          [vc14]
    libpng:          1.6.17-vc14_1      [vc14]
    libtiff:         4.0.6-vc14_0       [vc14]
    matplotlib:      1.4.3-np110py35_3
    numpy:           1.10.1-py35_0
    openssl:         1.0.2d-vc14_0      [vc14]
    pandas:          0.17.0-np110py35_0
    pip:             7.1.2-py35_0
    pyparsing:       2.0.3-py35_0
    pyqt:            4.11.4-py35_3
    python-dateutil: 2.4.2-py35_0
    pytz:            2015.7-py35_0
    qt:              4.8.7-vc14_4       [vc14]
    scipy:           0.16.0-np110py35_0
    seaborn:         0.6.0-np110py35_0
    setuptools:      18.4-py35_0
    sip:             4.16.9-py35_2
    six:             1.10.0-py35_0
    tk:              8.5.18-vc14_0      [vc14]
    wheel:           0.26.0-py35_1
    zlib:            1.2.8-vc14_2       [vc14]

The following packages will be UPDATED:

    conda:           3.18.3-py35_0 --> 3.18.5-py35_0
    conda-env:       2.4.4-py35_0  --> 2.4.4-py35_2
    msvc_runtime:    1.0.0-vc14_0  [vc14] --> 1.0.1-vc14_0       [vc14]
    python:          3.5.0-2       --> 3.5.0-3

Proceed ([y]/n)? y

Fetching packages ...
jpeg-8d-vc14_0 100% |###############################| Time: 0:00:01  96.64 kB/s
libpng-1.6.17- 100% |###############################| Time: 0:00:06  73.67 kB/s
msvc_runtime-1 100% |###############################| Time: 0:00:10 206.46 kB/s
openssl-1.0.2d 100% |###############################| Time: 0:00:17 233.45 kB/s
tk-8.5.18-vc14 100% |###############################| Time: 0:00:05 430.97 kB/s
zlib-1.2.8-vc1 100% |###############################| Time: 0:00:01 110.16 kB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:02 192.36 kB/s
python-3.5.0-3 100% |###############################| Time: 0:00:38 978.45 kB/s
conda-env-2.4. 100% |###############################| Time: 0:00:00  77.79 kB/s
numpy-1.10.1-p 100% |###############################| Time: 0:01:52 928.34 kB/s
pyparsing-2.0. 100% |###############################| Time: 0:00:00  99.62 kB/s
pytz-2015.7-py 100% |###############################| Time: 0:00:01 133.26 kB/s
qt-4.8.7-vc14_ 100% |###############################| Time: 0:00:47   1.16 MB/s
setuptools-18. 100% |###############################| Time: 0:00:02 187.89 kB/s
sip-4.16.9-py3 100% |###############################| Time: 0:00:01 139.69 kB/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00   0.00  B/s
wheel-0.26.0-p 100% |###############################| Time: 0:00:00 102.11 kB/s
conda-3.18.5-p 100% |###############################| Time: 0:00:01 135.36 kB/s
pip-7.1.2-py35 100% |###############################| Time: 0:00:04 348.03 kB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:08 492.20 kB/s
python-dateuti 100% |###############################| Time: 0:00:01 136.17 kB/s
scipy-0.16.0-n 100% |###############################| Time: 0:00:18 479.08 kB/s
matplotlib-1.4 100% |###############################| Time: 0:00:43 965.65 kB/s
pandas-0.17.0- 100% |###############################| Time: 0:00:14 414.66 kB/s
seaborn-0.6.0- 100% |###############################| Time: 0:00:01 107.98 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  28%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Mikuś\Miniconda3\Scripts\conda-script.py", line 4, in <module>
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main.py", line 195, in main
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\install.py", line 423, in install
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\instructions.py", line 91, in LINK_CMD
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\instructions.py", line 87, in link
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\install.py", line 613, in link
  File "C:\Users\Mikuś\Miniconda3\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [WinError 5] Odmowa dostępu: 'C:\\Users\\Mikuś\\Miniconda3\\Scripts'

D:\DATA
λ conda install matplotlib pandas seaborn
'conda' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by mmagnuski** [comment]
Similar issues: #1221, #1761, #1551, #1520, #1293, #1717

**Comment by bhatiani** [comment]
I'm having similar issues also!
