### ISSUE TITLE
conda list gives UnicodeDecodeError on python3

### ISSUE THREAD

**Issue by mmagnuski** [conda/conda#1839]
Here is the error message:

```
λ conda list
# packages in environment at C:\Users\Mikuś\Miniconda3:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Mikuś\Miniconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 246, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 177, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\pip.py", line 49, in installed
    args = pip_args(prefix)
  File "C:\Users\Mikuś\Miniconda3\lib\site-packages\conda\pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 28: invalid start byte
```

I have non-ascii characters in my user name.
My `conda info`:

```
Current conda install:

             platform : win-64
        conda version : 3.18.5
  conda-build version : not installed
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : C:\Users\Mikuś\Miniconda3  (writable)
  default environment : C:\Users\Mikuś\Miniconda3
     envs directories : C:\Users\Mikuś\Miniconda3\envs
        package cache : C:\Users\Mikuś\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Mikuś\.condarc
    is foreign system : False
```

**Comment by mmagnuski** [comment]
related: #1847

**Comment by Coldmooon** [comment]
@mmagnuski I'm facing the same problem. Have you solved this?

**Comment by kalefranz** [comment]
@Coldmooon Can you verify your version of conda for us with `conda info`?  We've release version `4.1.0` just today.  If you need to update,

    conda update conda

**Comment by Coldmooon** [comment]
@kalefranz Thank you~ I'm using the version 4.1.0. My system is `ubuntu 14.04`.

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.0
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/coldmoon/anaconda3  (writable)
  default environment : /home/coldmoon/anaconda3
     envs directories : /home/coldmoon/anaconda3/envs
        package cache : /home/coldmoon/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by mmagnuski** [comment]
@Coldmooon As far as I remember I haven't fixed this, but I'm working on a different computer now and I no longer have this problem.

**Comment by tyler-thetyrant** [comment]
Unicode is now supported!

**Comment by kalefranz** [comment]
At least it should be in most situations for any python version on unix or python >=3.6 on windows.
