### ISSUE TITLE
Error installing pyzmq

### ISSUE THREAD

**Issue by sclamons** [conda/conda#1842]
While reinstalling pyzmq with conda to fix what appears to be [*this*](https://github.com/jupyter/notebook/issues/297) issue, I encountered the following error:
```
sclamons$ conda install pyzmq
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment //anaconda/envs/python3:

The following NEW packages will be INSTALLED:

    pyzmq:      14.7.0-py34_1
    setuptools: 18.4-py34_0  

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the                |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/envs/python3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 417, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 533, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 618, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 261, in update_prefix
    with open(path, 'rb') as fi:
FileNotFoundError: [Errno 2] No such file or directory: '/anaconda/envs/python3/lib/python3.4/site-packages/zmq/utils/compiler.json'
```

Edits: Formatting.

**Comment by sclamons** [comment]
A few more details -- after pip installing zmq and conda installing setuptools, I get the same error minus the notification to install setuptools. The location /anaconda/envs/python3/lib/python3.4/site-packages/zmq/utils/ exists, but there's nothing there except a __pycache__ folder.

**Comment by sclamons** [comment]
Fixed on my end by deleting the folder /anaconda/envs/python3/lib/python3.4/site-packages/zmq/. I think it was left over from a previous installation and was tricking conda into thinking zmq was installed, even though it wasn't? Not sure exactly.

**Comment by ccordoba12** [comment]
Quick note: you can force a full reinstall by doing:

    conda install -f pyzmq

That removes left overs from previous installations and install a new fresh version of any package.
