### ISSUE TITLE
Can't restore matplotlib

### ISSUE THREAD

**Issue by favorart** [conda/conda#1847]
```
Package plan for installation in environment C:\Anaconda:
The following packages will be UPDATED:

    matplotlib:   1.4.3-np110py27_3  --> 1.4.3-np19py27_3
    scipy:        0.16.0-np110py27_0 --> 0.16.0-np19py27_0

The following packages will be DOWNGRADED:

    numpy:        1.10.1-py27_0      --> 1.9.3-py27_0
    scikit-learn: 0.17-np110py27_1   --> 0.16.1-np19py27_0

Proceed ([y]/n)? y

Unlinking packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>  sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD install.unlink(state['prefix'], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 705, in unlink move_path_to_trash(dst)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 578, in move_path_to_trash
    log.debug("Could not move %s to %s (%s)" % (path, trash_dir, e))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 11: ordinal not in range(128)
```

There are no non-ascii sections in the path to Anaconda.
I suppose, that matplotlib also had been installed in the folder C:\Anaconda\prgs\matplotlib... .

**Comment by tyler-thetyrant** [comment]
This should be fixed in the recent versions of Conda.
