### ISSUE TITLE
Error from 'conda update anaconda' (haven't used it in a while, was updating it...)

### ISSUE THREAD

**Issue by zillesc** [conda/conda#1850]
Traceback (most recent call last):
  File "/Users/zilles/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    args.func(args, p)
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 76, in execute
    actions = plan.install_actions(prefix, index, args.pkg_names)
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/plan.py", line 233, in install_actions
    for fn in r.solve(specs, [d + '.tar.bz2' for d in linked]):
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 425, in solve
    return self.explicit(specs) or self.solve2(specs, features)
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 282, in solve2
    solutions = min_sat(clauses)
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 146, in min_sat
    for sol in islice(pycosat.itersolve(clauses), max_n):
  File "/Users/zilles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 238, in gen_clauses
    assert len(clause) > 1, fn1
AssertionError: datashape-0.4.7-np110py34_1.tar.bz2

Include the output of the command 'conda info' in your report.

Current conda install:

```
         platform : osx-64
    conda version : 2.0.4
 root environment : /Users/zilles/anaconda  (writable)
```

  default environment : /Users/zilles/anaconda
     envs directories : /Users/zilles/anaconda/envs
        package cache : /Users/zilles/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None

**Comment by zillesc** [comment]
Putting this up because your software told me to.

**Comment by tyler-thetyrant** [comment]
Hey Professor Ziles, I was in your 233 lecture last fall :) 

You are using VERY outdated version of conda! We are currently on 4.3.17, and I don't think even running the `conda update conda` will bring you to the most recent version of conda. 
I recommend uninstalling and reinstalling [miniconda](https://conda.io/docs/install/quick.html#miniconda-quick-install-requirements).
