### ISSUE TITLE
Unicode decoding error when running conda install

### ISSUE THREAD

**Issue by kmunve** [conda/conda#1857]
### I got the following output while trying to install _openpyxl_ using conda. Conda and Python did not work anymore after that crash.

PS C:\Users\aaa> conda install openpyxl
Fetching package metadata: ....
Solving package specifications: ..............
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| msvc_runtime-1.0.1 | vc9_0         1.1 MB |
| python-2.7.10 | 4        17.9 MB |
| conda-env-2.4.4 | py27_2          64 KB |
| requests-2.8.1 | py27_0         609 KB |
| setuptools-18.5 | py27_0         648 KB |
| conda-3.18.6 | py27_0         219 KB |
| openpyxl-2.2.6 | py27_0         189 KB |

```
------------------------------------------------------------
                                       Total:        20.7 MB
```

The following NEW packages will be INSTALLED:

```
msvc_runtime: 1.0.1-vc9_0   [vc9]
```

The following packages will be UPDATED:

```
conda:        3.18.1-py27_0 --> 3.18.6-py27_0
conda-env:    2.4.2-py27_0  --> 2.4.4-py27_2
openpyxl:     1.8.5-py27_0  --> 2.2.6-py27_0
python:       2.7.10-1      --> 2.7.10-4
requests:     2.8.0-py27_0  --> 2.8.1-py27_0
setuptools:   18.3.2-py27_0 --> 18.5-py27_0
```

Proceed ([y]/n)? y

Fetching packages ...
msvc_runtime-1 100% |###############################| Time: 0:00:01 604.53 kB/s
python-2.7.10- 100% |###############################| Time: 0:00:18   1.04 MB/s
conda-env-2.4. 100% |###############################| Time: 0:00:00 199.31 kB/s
requests-2.8.1 100% |###############################| Time: 0:00:08  73.77 kB/s
setuptools-18. 100% |###############################| Time: 0:00:01 468.96 kB/s
conda-3.18.6-p 100% |###############################| Time: 0:00:01 214.03 kB/s
openpyxl-2.2.6 100% |###############################| Time: 0:00:00 328.91 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the###         |  83%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 427, in install
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 538, in execute_actions
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 685, in unlink
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 558, in move_path_to_trash
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 22: ordinal not in range(128)

**Comment by fogo** [comment]
I've faced the same issue. It was caused because a file was opened by other process and since my Windows is pt-br (brazilian Portuguese) the exception message was:

```python
WindowsError(32, 'O arquivo j\xe1 est\xe1 sendo usado por outro processo')
```

That message as consequence caused the line in `move_path_to_trash` method to fail because of coercion to ASCII:

```python
log.debug("Could not move %s to %s (%s)" % (path, trash_dir, e))
```

Error handling involving unicode characters is indeed a troublesome and error prone issue.

**Comment by groutr** [comment]
I agree that Unicode can be quite a pain sometimes.  Thanks @fogo for your input.  I'll try changing those log.debug lines to be unicode-friendly as soon as I can.

@kmunve, any more context as where conda would have encountered a unicode error?  Does the path where you have anaconda installed have unicode character?  Does your environment name contain a unicode character?

**Comment by kmunve** [comment]
@groutr, the path where Anaconda is installed is C:\Anaconda3. I have both C:\Anaconda and C:\Anaconda3. The C:\Anaconda folder is not used anymore, but it occurs to me know that the conda command might still point to it.

I use Norwegian system settings, so it is likely that unicode characters occur.

**Comment by msarahan** [comment]
For reproduction purposes, one can create a user with some non-ASCII character in it (I used an accented a):

```
C:\Users\å test user>conda install menuinst
Fetching package metadata: ....
Solving package specifications: .................An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\σ test user\Miniconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\cli\install.py", line 333, in install
    update_deps=args.update_deps)
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\plan.py", line 437, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\plan.py", line 248, in ensure_linked_actions
    if install.is_linked(prefix, dist):
  File "C:\Users\σ test user\Miniconda2\lib\site-packages\conda\install.py", line 522, in is_linked
    meta_path = join(prefix, 'conda-meta', dist + '.json')
  File "C:\Users\σ test user\Miniconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 7: ordinal not in range(128)
```

**Comment by kalefranz** [comment]
We will not be supporting unicode characters for conda running under non python 3.6 interpreters on Windows.  If you come to this issue, are running Windows, are running conda 4.3+, and have conda running with a python 3.6+ interpreter, please file a new issue.
