### ISSUE TITLE
Exception during `conda install pip`

### ISSUE THREAD

**Issue by dsludwig** [conda/conda#1861]
Using a root miniconda install into `/opt/miniconda` and an environment executed by `aworker2`.

```
$ conda install -q pip
Fetching package metadata: ..........
Solving package specifications: .............An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/aworker2/worker/builds/binstar/binstar-server/env/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 437, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 255, in ensure_linked_actions
    elif install.try_hard_link(extracted_in, prefix, dist):
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 444, in try_hard_link
    assert not isfile(dst), dst
AssertionError: /home/aworker2/worker/builds/binstar/binstar-server/env/.tmp-openssl-1.0.2d-0
```

@stephenakearns I am attempting to come up with a consistent reproduction of the issue.

**Comment by dsludwig** [comment]
After creating a new conda environment, I have stray files in the root directory of the environment:

```
(root)-bash-4.1$ conda create -n test python=2.7 -q
Fetching package metadata: ....
Solving package specifications: ............
Package plan for installation in environment /home/aworker0/.conda/envs/test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0      defaults
    pip:        7.1.2-py27_0  defaults
    python:     2.7.10-2      defaults
    readline:   6.2-2         defaults
    setuptools: 18.5-py27_0   defaults
    sqlite:     3.8.4.1-1     defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py27_1 defaults
    zlib:       1.2.8-0       defaults

#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#
(root)-bash-4.1$ ls -al .conda/envs/test
total 68
drwxrwxr-x 8 aworker0 aworker0 4096 Nov 26 00:37 .
drwxr-xr-x 5 aworker0 aworker0 4096 Nov 26 00:37 ..
drwxrwxr-x 2 aworker0 aworker0 4096 Nov 26 00:37 bin
drwxrwxr-x 2 aworker0 aworker0 4096 Nov 26 00:37 conda-meta
drwxrwxr-x 5 aworker0 aworker0 4096 Nov 26 00:37 include
drwxrwxr-x 8 aworker0 aworker0 4096 Nov 26 00:37 lib
drwxrwxr-x 4 aworker0 aworker0 4096 Nov 26 00:37 share
drwxrwxr-x 3 aworker0 aworker0 4096 Nov 26 00:37 ssl
-rw-rw-r-- 7 ec2-user root      299 Oct 19 22:42 .tmp-openssl-1.0.2d-0
-rw-rw-r-- 7 ec2-user root      353 Aug 24 19:53 .tmp-pip-7.1.2-py27_0
-rw-rw-r-- 7 ec2-user root      426 Oct 19 23:07 .tmp-python-2.7.10-2
-rw-rw-r-- 7 ec2-user root      166 Jan  4  2014 .tmp-readline-6.2-2
-rw-rw-r-- 7 ec2-user root      257 Nov 23 17:51 .tmp-setuptools-18.5-py27_0
-rw-rw-r-- 7 ec2-user root      238 Mar 23  2015 .tmp-sqlite-3.8.4.1-1
-rw-rw-r-- 7 ec2-user root      190 Mar 16  2015 .tmp-tk-8.5.18-0
-rw-rw-r-- 7 ec2-user root      219 Sep 24 15:42 .tmp-wheel-0.26.0-py27_1
-rw-rw-r-- 7 ec2-user root      222 Jan  5  2015 .tmp-zlib-1.2.8-0
```
