### ISSUE TITLE
Issue with virtual env

### ISSUE THREAD

**Issue by SteveHarrison82** [conda/conda#1866]
Operating System: 
windows 7 / 64 bit with preinstalled anaconda python 2.7.9

Test case:
1. create a virtual env as "conda create --name py268 python=2.6.8"

Observed:

An error is thrown as below

C:\Users>conda create --name py268 python=2.6.8
Fetching package metadata: ....
Solving package specifications: ...................
Package plan for installation in environment C:\Users\AppData\Local\Continuum\Anaconda\envs\py268:

The following packages will be downloaded:

| package | build |
| --- | --- |
| python-2.6.8 | 6        18.1 MB |
| setuptools-18.0.1 | py26_0         648 KB |
| pip-7.1.0 | py26_0         1.4 MB |

```
------------------------------------------------------------
                                       Total:        20.1 MB
```

The following NEW packages will be INSTALLED:

```
pip:        7.1.0-py26_0
python:     2.6.8-6
setuptools: 18.0.1-py26_0
```

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Users\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func
    args.func(args, p)
  File "C:\Users\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "C:\UsersAppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\install.py", line 404, in install
    if not pscheck.main(args):
  File "C:\UsersAppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\pscheck.py", line 66, in main
    while not check_processes():
  File "C:\UsersAppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\pscheck.py", line 33, in check_processes
    for n in psutil.get_pid_list():
AttributeError: 'module' object has no attribute 'get_pid_list'

**Comment by kalefranz** [comment]
Really old ticket.  The code paths in that stack trace are long gone.
