### ISSUE TITLE
Unable to install pandas

### ISSUE THREAD

**Issue by ramsthere** [conda/conda#1868]
Pandas did not get installed by default. When I sift through the log I can see this error,

```
Error: Could not create file Lib/site-packages/pandas/io/tests/data/test.xls [5]
Error: Unable to extract file.
```

When I try to do it manually through,
`conda install -f pandas` I am getting an error. Something to do with permissions, but I am already installing it with admin privileges.

This is the error,

```
Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "D:\Anaconda3\lib\site-packages\conda\install.py", line 492, in extract
    t.extractall(path=path)
  File "D:\Anaconda3\lib\tarfile.py", line 1980, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir())
  File "D:\Anaconda3\lib\tarfile.py", line 2019, in extract
    set_attrs=set_attrs)
  File "D:\Anaconda3\lib\tarfile.py", line 2088, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "D:\Anaconda3\lib\tarfile.py", line 2128, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'D:\\Anaconda3\\pkgs\\pandas-0.17.1-np110py34_0\\Lib\\site-packages\\pandas\\io\\tests\\data\\blan
```

This is the system info output.

```
Current conda install:
             platform : win-64
        conda version : 3.18.6
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.8.1
     root environment : D:\Anaconda3  (writable)
  default environment : D:\Anaconda3
     envs directories : D:\Anaconda3\envs
        package cache : D:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated issue.
