### ISSUE TITLE
can not updata conda

### ISSUE THREAD

**Issue by Qi2013** [conda/conda#1869]
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 202, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 48, in ex
ecute
    install.install(args, parser, 'update')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 239, in insta
ll
    offline=args.offline)
  File "C:\Anaconda2\lib\site-packages\conda\cli\common.py", line 598, in get_in
dex_trap
    return get_index(_args, *_kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\Anaconda2\lib\site-packages\conda\utils.py", line 119, in **call**
    value = self.func(_args, *_kw)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 237, in fetch_index

```
session = CondaSession()
```

  File "C:\Anaconda2\lib\site-packages\conda\connection.py", line 69, in **init_
_
    http_adapter = requests.adapters.HTTPAdapter(max_retries=retries)
TypeError: __init**() got an unexpected keyword argument 'max_retries'

My current conda installnation:

```
        platform : win-32
   conda version : 3.18.3
```

 conda-build version : 1.18.1
      python version : 2.7.10.final.0
    requests version : 1.0.2
    root environment : C:\Anaconda2  (writable)
 default environment : C:\Anaconda2
    envs directories : C:\Anaconda2\envs
       package cache : C:\Anaconda2\pkgs
        channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                       https://repo.continuum.io/pkgs/free/noarch/
                       https://repo.continuum.io/pkgs/pro/win-32/
                       https://repo.continuum.io/pkgs/pro/noarch/
         config file : None
   is foreign system : False

**Comment by tyler-thetyrant** [comment]
Closing outdated. Please check our newest conda!
