### ISSUE TITLE
"conda update --all" APPCRASH & Now "failed to create process."

### ISSUE THREAD

**Issue by Cypherdude** [conda/conda#1871]
I installed Anaconda3-2.2.0-Windows-x86_64.exe April 8, 2015.  I was able to run the conda update --all command with no problems.  The last time I ran the update --all command was April 10, 2015.  However, today I received an APPCRASH:

```
Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: python.exe
  Application Version:  0.0.0.0
  Application Timestamp:    54f9ec93
  Fault Module Name:    pycosat.pyd
  Fault Module Version: 0.0.0.0
  Fault Module Timestamp:   535edda3
  Exception Code:   c0000005
  Exception Offset: 0000000000004fee
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1033
  Additional Information 1: 01ae
  Additional Information 2: 01ae1715fc522dce0df07dc62d8ad939
  Additional Information 3: 0043
  Additional Information 4: 00439eb2d2e35e1590e0221cb66faff4
```

I also ran the command conda update --all --alt-hint but I still got an APPCRASH.  I then ran "conda update PIP" and also "conda update anaconda" and both times everything worked OK.  When I ran "conda update --all" again, it did not crash.  However, I got an error and now every time I run any command, I get an error "failed to create process."  The results are below.  Is there anyway I can fix the error or must I uninstall/reinstall?  It took me a long time to install, create an environment and update everything.

```
D:\Anaconda3>conda update --all
Fetching package metadata: ....
Solving package specifications: ...........................................................................................
...........................................................................................................................
........................................................................................
Warning: 2 possible package resolutions (only showing differing packages):
        ['conda-build-1.18.2-py34_0.tar.bz2', 'psutil-3.2.2-py34_0.tar.bz2'],
        ['conda-build-1.18.1-py34_0.tar.bz2', 'psutil-3.3.0-py34_0.tar.bz2'],

Package plan for installation in environment D:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    binstar-0.12               |                2          528 B  defaults
    patch-2.5.9                |                1          56 KB  defaults
    libtiff-4.0.6              |           vc10_1         465 KB  defaults
    python-3.4.3               |                4        25.9 MB  defaults
    _license-1.1               |           py34_1          56 KB  defaults
    backports_abc-0.4          |           py34_0           5 KB  defaults
    certifi-2015.9.6.2         |           py34_0         213 KB  defaults
    funcsigs-0.4               |           py34_0          19 KB  defaults
    llvmlite-0.8.0             |           py34_0         5.2 MB  defaults
    menuinst-1.2.2             |           py34_0          45 KB  defaults
    numpy-1.9.3                |           py34_0        22.6 MB  defaults
    path.py-8.1.2              |           py34_1          47 KB  defaults
    pytz-2015.7                |           py34_0         167 KB  defaults
    sip-4.16.9                 |           py34_2         224 KB  defaults
    werkzeug-0.11.2            |           py34_0         420 KB  defaults
    astropy-1.0.4              |       np19py34_0         5.4 MB  defaults
    bcolz-0.11.3               |           py34_0         331 KB  defaults
    bottleneck-1.0.0           |       np19py34_0         143 KB  defaults
    clyent-1.1.0               |           py34_0          13 KB  defaults
    h5py-2.5.0                 |       np19py34_2         575 KB  defaults
    numba-0.22.1               |       np19py34_0         1.5 MB  defaults
    numexpr-2.4.4              |       np19py34_0         108 KB  defaults
    patsy-0.4.0                |       np19py34_0         368 KB  defaults
    pyqt-4.11.4                |           py34_3         3.7 MB  defaults
    scipy-0.16.0               |       np19py34_0        81.6 MB  defaults
    tornado-4.3                |           py34_0         578 KB  defaults
    xlwings-0.5.0              |           py34_0         374 KB  defaults
    anaconda-client-1.1.2      |           py34_0          92 KB  defaults
    blz-0.6.2                  |       np19py34_1         292 KB  defaults
    conda-build-1.18.2         |           py34_0         294 KB  defaults
    datashape-0.4.7            |       np19py34_1          37 KB  defaults
    matplotlib-1.4.3           |       np19py34_1        42.2 MB  defaults
    pandas-0.17.0              |       np19py34_0         4.0 MB  defaults
    pbr-1.3.0                  |           py34_0         126 KB  defaults
    pytables-3.2.2             |       np19py34_0         1.5 MB  defaults
    scikit-learn-0.16.1        |       np19py34_0         3.5 MB  defaults
    mock-1.3.0                 |           py34_0          99 KB  defaults
    statsmodels-0.6.1          |       np19py34_0         4.7 MB  defaults
    ------------------------------------------------------------
                                           Total:       206.8 MB

The following NEW packages will be INSTALLED:

    backports_abc:   0.4-py34_0        defaults
    funcsigs:        0.4-py34_0        defaults
    patch:           2.5.9-1           defaults
    pbr:             1.3.0-py34_0      defaults

The following packages will be UPDATED:

    _license:        1.1-py34_0         defaults --> 1.1-py34_1        defaults
    anaconda-client: 1.1.0-py34_0       defaults --> 1.1.2-py34_0      defaults
    bcolz:           0.8.1-np19py34_0   defaults --> 0.11.3-py34_0     defaults
    binstar:         0.10.3-py34_0      defaults --> 0.12-2            defaults
    blz:             0.6.2-np19py34_0   defaults --> 0.6.2-np19py34_1  defaults
    bottleneck:      1.0.0-np110py34_0  defaults --> 1.0.0-np19py34_0  defaults
    certifi:         14.05.14-py34_0    defaults --> 2015.9.6.2-py34_0 defaults
    clyent:          0.4.0-py34_0       defaults --> 1.1.0-py34_0      defaults
    conda-build:     1.11.0-py34_0      defaults --> 1.18.2-py34_0     defaults
    datashape:       0.4.7-np110py34_1  defaults --> 0.4.7-np19py34_1  defaults
    libtiff:         4.0.6-vc10_0       defaults [vc10] --> 4.0.6-vc10_1      defaults [vc10]
    llvmlite:        0.7.0-py34_5       defaults --> 0.8.0-py34_0      defaults
    menuinst:        1.2.1-py34_0       defaults --> 1.2.2-py34_0      defaults
    mock:            1.0.1-py34_0       defaults --> 1.3.0-py34_0      defaults
    msvc_runtime:    1.0.0-vc10_0       defaults [vc10] --> 1.0.1-vc10_0      defaults [vc10]
    numba:           0.21.0-np110py34_0 defaults --> 0.22.1-np19py34_0 defaults
    numexpr:         2.4.4-np110py34_0  defaults --> 2.4.4-np19py34_0  defaults
    pandas:          0.17.0-np110py34_0 defaults --> 0.17.0-np19py34_0 defaults
    path.py:         8.1.2-py34_0       defaults --> 8.1.2-py34_1      defaults
    patsy:           0.4.0-np110py34_0  defaults --> 0.4.0-np19py34_0  defaults
    pyqt:            4.11.4-py34_2      defaults --> 4.11.4-py34_3     defaults
    python:          3.4.3-3            defaults --> 3.4.3-4           defaults
    pytz:            2015.6-py34_0      defaults --> 2015.7-py34_0     defaults
    scikit-image:    0.11.3-np110py34_0 defaults --> 0.11.3-np19py34_0 defaults
    scikit-learn:    0.16.1-np110py34_0 defaults --> 0.16.1-np19py34_0 defaults
    scipy:           0.16.0-np110py34_0 defaults --> 0.16.0-np19py34_0 defaults
    setuptools:      18.4-py34_0        defaults --> 18.5-py34_0       defaults
    sip:             4.16.9-py34_1      defaults --> 4.16.9-py34_2     defaults
    statsmodels:     0.6.1-np110py34_0  defaults --> 0.6.1-np19py34_0  defaults
    tornado:         4.2.1-py34_1       defaults --> 4.3-py34_0        defaults
    werkzeug:        0.10.4-py34_0      defaults --> 0.11.2-py34_0     defaults
    xlwings:         0.4.1-py34_0       defaults --> 0.5.0-py34_0      defaults

The following packages will be DOWNGRADED:

    astropy:         1.0.5-np110py34_1  defaults --> 1.0.4-np19py34_0  defaults
    h5py:            2.5.0-np110py34_4  defaults --> 2.5.0-np19py34_2  defaults
    matplotlib:      1.4.3-np110py34_3  defaults --> 1.4.3-np19py34_1  defaults
    numpy:           1.10.1-py34_0      defaults --> 1.9.3-py34_0      defaults
    pytables:        3.2.2-np110py34_1  defaults --> 3.2.2-np19py34_0  defaults

Proceed ([y]/n)? y

menuinst-1.2.2 100% |###############################| Time: 0:00:00 270.86 kB/s
Fetching packages ...
binstar-0.12-2 100% |###############################| Time: 0:00:00   0.00  B/s
patch-2.5.9-1. 100% |###############################| Time: 0:00:00 308.90 kB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:00 693.54 kB/s
python-3.4.3-4 100% |###############################| Time: 0:00:09   2.85 MB/s
_license-1.1-p 100% |###############################| Time: 0:00:00 304.20 kB/s
backports_abc- 100% |###############################| Time: 0:00:00 318.46 kB/s
certifi-2015.9 100% |###############################| Time: 0:00:00 481.63 kB/s
funcsigs-0.4-p 100% |###############################| Time: 0:00:00 211.29 kB/s
llvmlite-0.8.0 100% |###############################| Time: 0:00:02   2.26 MB/s
numpy-1.9.3-py 100% |###############################| Time: 0:00:08   2.71 MB/s
path.py-8.1.2- 100% |###############################| Time: 0:00:00 279.42 kB/s
pytz-2015.7-py 100% |###############################| Time: 0:00:00 377.78 kB/s
sip-4.16.9-py3 100% |###############################| Time: 0:00:00 432.07 kB/s
werkzeug-0.11. 100% |###############################| Time: 0:00:00 598.68 kB/s
astropy-1.0.4- 100% |###############################| Time: 0:00:02   2.21 MB/s
bcolz-0.11.3-p 100% |###############################| Time: 0:00:00 571.48 kB/s
bottleneck-1.0 100% |###############################| Time: 0:00:00 347.86 kB/s
clyent-1.1.0-p 100% |###############################| Time: 0:00:00 166.15 kB/s
h5py-2.5.0-np1 100% |###############################| Time: 0:00:00 739.60 kB/s
numba-0.22.1-n 100% |###############################| Time: 0:00:01   1.48 MB/s
numexpr-2.4.4- 100% |###############################| Time: 0:00:00 320.92 kB/s
patsy-0.4.0-np 100% |###############################| Time: 0:00:00 603.21 kB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:01   2.00 MB/s
scipy-0.16.0-n 100% |###############################| Time: 0:00:28   2.96 MB/s
tornado-4.3-py 100% |###############################| Time: 0:00:00 679.87 kB/s
xlwings-0.5.0- 100% |###############################| Time: 0:00:00 559.39 kB/s
anaconda-clien 100% |###############################| Time: 0:00:00 274.33 kB/s
blz-0.6.2-np19 100% |###############################| Time: 0:00:00 500.11 kB/s
conda-build-1. 100% |###############################| Time: 0:00:00 574.11 kB/s
datashape-0.4. 100% |###############################| Time: 0:00:00 221.46 kB/s
matplotlib-1.4 100% |###############################| Time: 0:00:15   2.91 MB/s
pandas-0.17.0- 100% |###############################| Time: 0:00:01   2.13 MB/s
pbr-1.3.0-py34 100% |###############################| Time: 0:00:00 301.91 kB/s
pytables-3.2.2 100% |###############################| Time: 0:00:01   1.34 MB/s
scikit-learn-0 100% |###############################| Time: 0:00:01   1.83 MB/s
mock-1.3.0-py3 100% |###############################| Time: 0:00:00 296.04 kB/s
statsmodels-0. 100% |###############################| Time: 0:00:02   2.10 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  10%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "D:\Anaconda3\lib\site-packages\conda\install.py", line 623, in link
    os.makedirs(dst_dir)
  File "D:\Anaconda3\lib\os.py", line 237, in makedirs
PermissionError: [WinError 5] Access is denied: 'D:\\Anaconda3\\DLLs'

D:\Anaconda3>conda list
failed to create process.

D:\Anaconda3>conda -h
failed to create process.

D:\Anaconda3>conda info -e
failed to create process.

D:\Anaconda3>activate py2
Activating environment "D:\Anaconda3\envs\py2"...

[py2] D:\Anaconda3>conda list
failed to create process.

[py2] D:\Anaconda3>conda info -e
failed to create process.

[py2] D:\Anaconda3>deactivate
Deactivating environment "D:\Anaconda3\envs\py2"...

D:\Anaconda3>conda info -e
failed to create process.

D:\Anaconda3>
```

**Comment by tyler-thetyrant** [comment]
fixed with conda 4.3
