### ISSUE TITLE
Unable to install ipython-notebook in conda environment

### ISSUE THREAD

**Issue by bmfriedman** [conda/conda#1876]
Traceback detail:

Traceback (most recent call last):
  File "/home/secfried/.conda/envs/db2Pyth35/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 437, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 255, in ensure_linked_actions
    elif install.try_hard_link(extracted_in, prefix, dist):
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/install.py", line 444, in try_hard_link
    assert not isfile(dst), dst
AssertionError: /home/secfried/.conda/envs/db2Pyth35/.tmp-libsodium-1.0.3-0

conda info output:

(db2Pyth35)[secfried@it-sxop-1centos ~]$ conda info
Current conda install:

```
         platform : linux-32
    conda version : 3.18.6
```

  conda-build version : 1.18.1
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : /opt/anaconda3  (read only)
  default environment : /home/secfried/.conda/envs/db2Pyth35
     envs directories : /home/secfried/.conda/envs
                        /home/secfried/envs
                        /opt/anaconda3/envs
        package cache : /home/secfried/.conda/envs/.pkgs
                        /home/secfried/envs/.pkgs
                        /opt/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/secfried/.condarc
    is foreign system : False

Thank you,
Barry

**Comment by kalefranz** [comment]
Old issue. Old version of conda. Probably fixed and broken and fixed again several times over with different code paths since this ticket :)
