### ISSUE TITLE
Error updating iPython notebook from Launcher

### ISSUE THREAD

**Issue by billrodriguez** [conda/conda#1880]
Traceback (most recent call last):
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Users\willi303\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\install.py", line 699, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: 'C:\Users\willi303\AppData\Local\Continuum\Anaconda\conda-meta\ipython-notebook-3.2.0-py27_0.json'

Close

**Comment by ccordoba12** [comment]
Please try to use a terminal instead (i.e. `cmd.exe`) and run there

    conda update ipython-notebook
