### ISSUE TITLE
conda list in an environment with pip fails with ImportError: cannot import name 'HTTPSHandler'

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#1881]
```
$conda list
# packages in environment at /Users/aaronmeurer/anaconda3/envs/pyne:
#
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/envs/pyne/bin/pip", line 4, in <module>
    from pip import main
  File "/Users/aaronmeurer/anaconda3/envs/pyne/lib/python3.5/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/Users/aaronmeurer/anaconda3/envs/pyne/lib/python3.5/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/Users/aaronmeurer/anaconda3/envs/pyne/lib/python3.5/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/Users/aaronmeurer/anaconda3/envs/pyne/lib/python3.5/site-packages/pip/wheel.py", line 35, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/Users/aaronmeurer/anaconda3/envs/pyne/lib/python3.5/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/Users/aaronmeurer/anaconda3/envs/pyne/lib/python3.5/site-packages/pip/_vendor/distlib/compat.py", line 66, in <module>
    from urllib.request import (urlopen, urlretrieve, Request, url2pathname,
ImportError: cannot import name 'HTTPSHandler'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/envs/pyne/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 246, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 177, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "/Users/aaronmeurer/anaconda3/lib/python3.5/subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/Users/aaronmeurer/anaconda3/envs/pyne/bin/python', '/Users/aaronmeurer/anaconda3/envs/pyne/bin/pip', '-V']' returned non-zero exit status 1
```

This has the latest version of `pip` (`7.1.2-py35_0` from the default channels). If I remove pip from the environment conda list works just fine. 

I'm not sure why this is happening. Could be a corrupted package on my side. At any rate, conda list should probably catch errors from pip and fail more gracefully (like just print a warning message and continue with the normal conda list).

**Comment by ijstokes** [comment]
FWIW I can't reproduce this.  It doesn't happen from an Anaconda2 (v2.4.0) created Python 3.5 env with just Python + pip:

```bash
(root)ijstokes@petawawa Notebooks (master) $ conda create -n test_pip python=3.5 pip
Fetching package metadata: ....
Solving package specifications: ..........
Package plan for installation in environment /Users/ijstokes/anaconda/envs/test_pip:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0      defaults
    pip:        7.1.2-py35_0  defaults
    python:     3.5.0-1       defaults
    readline:   6.2-2         defaults
    setuptools: 18.5-py35_0   defaults
    sqlite:     3.8.4.1-1     defaults
    tk:         8.5.18-0      defaults
    wheel:      0.26.0-py35_1 defaults
    xz:         5.0.5-0       defaults
    zlib:       1.2.8-0       defaults

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|########################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test_pip
#
# To deactivate this environment, use:
# $ source deactivate
#
(root)ijstokes@petawawa Notebooks (master) $ source activate test_pip
discarding /Users/ijstokes/anaconda/bin from PATH
prepending /Users/ijstokes/anaconda/envs/test_pip/bin to PATH
(test_pip)ijstokes@petawawa Notebooks (master) $ conda list
# packages in environment at /Users/ijstokes/anaconda/envs/test_pip:
#
openssl                   1.0.2d                        0    defaults
pip                       7.1.2                    py35_0    defaults
python                    3.5.0                         1    defaults
readline                  6.2                           2    <unknown>
setuptools                18.5                     py35_0    defaults
sqlite                    3.8.4.1                       1    <unknown>
tk                        8.5.18                        0    <unknown>
wheel                     0.26.0                   py35_1    defaults
xz                        5.0.5                         0    defaults
zlib                      1.2.8                         0    <unknown>
(test_pip)ijstokes@petawawa Notebooks (master) $ 
```

Nor does it happen from the same thing off an Anaconda3 (v2.4.0) base:

```bash
(root)ijstokes@petawawa Notebooks (master) $ python -V
Python 3.5.0 :: Anaconda 2.4.0 (x86_64)
(root)ijstokes@petawawa Notebooks (master) $ conda create -n test_pip_py3 python=3.5 pip
Fetching package metadata: ....
Solving package specifications: ..........
Package plan for installation in environment /Users/ijstokes/anaconda3/anaconda/envs/test_pip_py3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    setuptools-18.5            |           py35_0         345 KB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2d-0     
    pip:        7.1.2-py35_0 
    python:     3.5.0-1      
    readline:   6.2-2        
    setuptools: 18.5-py35_0  
    sqlite:     3.8.4.1-1    
    tk:         8.5.18-0     
    wheel:      0.26.0-py35_1
    xz:         5.0.5-0      
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Fetching packages ...
setuptools-18. 100% |#####################################################################| Time: 0:00:00   1.72 MB/s
Extracting packages ...
[      COMPLETE      ]|########################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|########################################################################################| 100%
#
# To activate this environment, use:
# $ source activate test_pip_py3
#
# To deactivate this environment, use:
# $ source deactivate
#
(root)ijstokes@petawawa Notebooks (master) $ source activate test_pip_py3
discarding /Users/ijstokes/anaconda3/anaconda/bin from PATH
prepending /Users/ijstokes/anaconda3/anaconda/envs/test_pip_py3/bin to PATH
(test_pip_py3)ijstokes@petawawa Notebooks (master) $ conda list
# packages in environment at /Users/ijstokes/anaconda3/anaconda/envs/test_pip_py3:
#
openssl                   1.0.2d                        0  
pip                       7.1.2                    py35_0  
python                    3.5.0                         1  
readline                  6.2                           2  
setuptools                18.5                     py35_0  
sqlite                    3.8.4.1                       1  
tk                        8.5.18                        0  
wheel                     0.26.0                   py35_1  
xz                        5.0.5                         0  
zlib                      1.2.8                         0  
```

**Comment by kalefranz** [comment]
conda list no longer imports or relies on pip
