### ISSUE TITLE
TypeError when trying to upload environment

### ISSUE THREAD

**Issue by johanneskoester** [conda/conda#1890]
I get the following error when trying to upload an environment:

```
conda env upload --file text.yml 
Uploading environment test to anaconda-server (https://api.anaconda.org)... 
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/johannes/.local/opt/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_upload.py", line 101, in execute
    info = uploader.upload()
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/conda_env/utils/uploader.py", line 84, in upload
    distribution_type=ENVIRONMENT_TYPE, attrs=self.env_data)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/binstar_client/__init__.py", line 412, in upload
    _hexmd5, b64md5, size = compute_hash(fd, size=size)
  File "/home/johannes/.local/opt/miniconda3/lib/python3.5/site-packages/binstar_client/utils/__init__.py", line 259, in compute_hash
    hash_obj.update(s)
TypeError: Unicode-objects must be encoded before hashing
```

Thanks!

**Comment by tyler-thetyrant** [comment]
This error was fixed in the recent version of conda.
