### ISSUE TITLE
Having problems installing netCDF4 on ubuntu 1404.

### ISSUE THREAD

**Issue by flamingbear** [conda/conda#1892]
after a fresh miniconda install. I try to install netCDF4 from anaconda.org.  But I can't import the correct hdf library.    (If I nuke my `/opt/miniconda/lib` and install `libhdf5-dev`, `libhdf4-dev`, and `libnetcdf-dev`, I can build it with `conda skeleton pypi netCDF4`)

```
vagrant@vmeltingyeti /opt/miniconda/lib$ conda install netcdf4
Fetching package metadata: ..............
Solving package specifications: .............................
Package plan for installation in environment /opt/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    curl-7.45.0                |                0         528 KB  defaults
    hdf5-1.8.15.1              |               14         1.9 MB  osgeo
    libnetcdf-4.3.3.1          |                0         2.4 MB  osgeo
    netcdf4-1.1.9              |      np110py35_0         1.6 MB  defaults
    ------------------------------------------------------------
                                           Total:         6.4 MB

The following NEW packages will be INSTALLED:

    curl:      7.45.0-0          defaults
    hdf5:      1.8.15.1-14       osgeo
    libnetcdf: 4.3.3.1-0         osgeo
    netcdf4:   1.1.9-np110py35_0 defaults

Fetching packages ...
curl-7.45.0-0. 100% || Time: 0:00:00   1.66 MB/s
hdf5-1.8.15.1- 100% || Time: 0:00:00   2.31 MB/s
libnetcdf-4.3. 100% || Time: 0:00:00   3.00 MB/s
netcdf4-1.1.9- 100% || Time: 0:00:00   2.74 MB/s
Extracting packages ...
[      COMPLETE      ]|| 100%
Linking packages ...
[      COMPLETE      ]|| 100%
vagrant@vmeltingyeti /opt/miniconda/lib$ python -c "import netCDF4"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/miniconda/lib/python3.5/site-packages/netCDF4/__init__.py", line 3, in <module>
    from ._netCDF4 import *
ImportError: libhdf5_hl.so.9: cannot open shared object file: No such file or directory
```

Files in /opt/miniconda/lib are:
```
vagrant@vmeltingyeti /opt/miniconda/lib$ ls -ls *hdf*
   4 -rwxr-xr-x 1 vagrant vagrant     955 Dec  7 10:54 libhdf5.la
   4 -rw-r--r-- 1 vagrant vagrant    3134 Dec  7 10:54 libhdf5.settings
   0 lrwxrwxrwx 1 vagrant vagrant      17 Dec  7 10:54 libhdf5.so -> libhdf5.so.10.0.1
   0 lrwxrwxrwx 1 vagrant vagrant      17 Dec  7 10:54 libhdf5.so.10 -> libhdf5.so.10.0.1
3148 -rwxr-xr-x 2 vagrant vagrant 3219096 Jul 17 01:59 libhdf5.so.10.0.1
   4 -rwxr-xr-x 1 vagrant vagrant    1005 Dec  7 10:54 libhdf5_cpp.la
   0 lrwxrwxrwx 1 vagrant vagrant      21 Dec  7 10:54 libhdf5_cpp.so -> libhdf5_cpp.so.10.0.1
   0 lrwxrwxrwx 1 vagrant vagrant      21 Dec  7 10:54 libhdf5_cpp.so.10 -> libhdf5_cpp.so.10.0.1
 540 -rwxr-xr-x 2 vagrant vagrant  545381 Jul 17 01:59 libhdf5_cpp.so.10.0.1
   4 -rwxr-xr-x 1 vagrant vagrant    1003 Dec  7 10:54 libhdf5_hl.la
   0 lrwxrwxrwx 1 vagrant vagrant      20 Dec  7 10:54 libhdf5_hl.so -> libhdf5_hl.so.10.0.1
   0 lrwxrwxrwx 1 vagrant vagrant      20 Dec  7 10:54 libhdf5_hl.so.10 -> libhdf5_hl.so.10.0.1
 144 -rwxr-xr-x 2 vagrant vagrant  140936 Jul 17 01:59 libhdf5_hl.so.10.0.1
   4 -rwxr-xr-x 1 vagrant vagrant    1090 Dec  7 10:54 libhdf5_hl_cpp.la
   0 lrwxrwxrwx 1 vagrant vagrant      24 Dec  7 10:54 libhdf5_hl_cpp.so -> libhdf5_hl_cpp.so.10.0.1
   0 lrwxrwxrwx 1 vagrant vagrant      24 Dec  7 10:54 libhdf5_hl_cpp.so.10 -> libhdf5_hl_cpp.so.10.0.1
  16 -rwxr-xr-x 2 vagrant vagrant   13732 Jul 17 01:59 libhdf5_hl_cpp.so.10.0.1
```

**Comment by groutr** [comment]
What happens when you try to install all of the packages from the continuum `default` channel?  Currently, hdf5 and libnetcdf are fetched from the osgeo channel.

**Comment by flamingbear** [comment]
I didn't even notice that osgeo was before default channel somehow.  
On a fresh box, downloading the latest miniconda3, and installing via defaults channel give me no errors when I run `python -c "import netCDF4"`  

Sorry about that, thanks for the help.

Matt

**Comment by groutr** [comment]
No problem.  I'm glad you were able to get it working.
