### ISSUE TITLE
Unexpected error when running conda update conda

### ISSUE THREAD

**Issue by sastephe** [conda/conda#1894]
PS C:\Users\Sam> conda update conda
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

| package | build |
| --- | --- |
| msvc_runtime-1.0.1 | vc9_0         1.1 MB |
| conda-env-2.4.4 | py27_2          64 KB |
| menuinst-1.3.1 | py27_0          96 KB |
| requests-2.8.1 | py27_0         609 KB |
| setuptools-18.5 | py27_0         648 KB |
| conda-3.18.8 | py27_0         219 KB |

```
------------------------------------------------------------
                                       Total:         2.7 MB
```

The following NEW packages will be INSTALLED:

```
msvc_runtime: 1.0.1-vc9_0   [vc9]
wheel:        0.26.0-py27_1
```

The following packages will be UPDATED:

```
conda:        3.11.0-py27_0 --> 3.18.8-py27_0
conda-env:    2.1.4-py27_0  --> 2.4.4-py27_2
menuinst:     1.0.4-py27_0  --> 1.3.1-py27_0
pip:          6.1.1-py27_0  --> 7.1.2-py27_0
pyyaml:       3.11-py27_0   --> 3.11-py27_2
requests:     2.7.0-py27_0  --> 2.8.1-py27_0
setuptools:   15.2-py27_0   --> 18.5-py27_0
```

Proceed ([y]/n)? y

menuinst-1.3.1 100% |###############################| Time: 0:00:00 326.80 kB/s
Fetching packages ...
msvc_runtime-1 100% |###############################| Time: 0:00:01 694.46 kB/s
conda-env-2.4. 100% |###############################| Time: 0:00:00 204.95 kB/s
requests-2.8.1 100% |###############################| Time: 0:00:01 585.70 kB/s
setuptools-18. 100% |###############################| Time: 0:00:01 538.67 kB/s
conda-3.18.8-p 100% |###############################| Time: 0:00:00 406.46 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 44, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '**getitem**'
PS C:\Users\Sam>

**Comment by rahmanhpu** [comment]
Same issue I am also getting during updating Anaconda. I am behind my Institute proxy.

=====================================================================
[rahman@centos7 ~]$ conda update conda
Fetching package metadata: 
https proxy username: xxxxxxxxxx
Password: xxxxxxxx
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/rahman/sware/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 255, in install
    offline=args.offline)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 549, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 255, in fetch_index
    reversed(channel_urls))
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 254, in <lambda>
    use_cache=use_cache, session=session)),
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 154, in fetch_repodata
    handle_proxy_407(url, session)
  File "/home/rahman/sware/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 184, in handle_proxy_407
    session.proxies[scheme], username, passwd)
KeyError: 'https'
[rahman@centos7 ~]$ 
===============================================================================
other details
[rahman@centos7 ~]$ conda info 
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/rahman/sware/anaconda  (writable)
  default environment : /home/rahman/sware/anaconda
     envs directories : /home/rahman/sware/anaconda/envs
        package cache : /home/rahman/sware/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

[rahman@centos7 ~]$

**Comment by kalefranz** [comment]
Bug report is for conda 3.14.1, which is no longer maintained.  If you're still having this issue, please file a new report with an updated stack trace.
