### ISSUE TITLE
conda update anaconda removes package anaconda

### ISSUE THREAD

**Issue by rammek** [conda/conda#1896]
Here is the command session with the traceback and info report.

```
Microsoft Windows [Version 10.0.10240]
(c) 2015 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd \

C:\>cd anaconda

C:\Anaconda>conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Anaconda:
#
conda                     3.18.8                   py27_0    defaults

C:\Anaconda>conda update anaconda
Fetching package metadata: ....
Solving package specifications: ................................................
................................................................................
...................
Package plan for installation in environment C:\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-2.7.9               |                1        18.8 MB  defaults

The following packages will be DOWNGRADED:

    anaconda:          2.3.0-np19py27_0   defaults --> 2.2.0-np19py27_0   defaults
    argcomplete:       0.8.9-py27_0       defaults --> 0.8.4-py27_0       defaults
    astropy:           1.0.6-np110py27_0  defaults --> 1.0.1-np19py27_0   defaults
    bcolz:             0.9.0-np19py27_0   defaults --> 0.8.1-np19py27_0   defaults
    binstar:           0.11.0-py27_0      defaults --> 0.10.1-py27_3      defaults
    blaze-core:        0.8.0-np19py27_0   defaults --> 0.7.3-np19py27_0   defaults
    blz:               0.6.2-np19py27_1   defaults --> 0.6.2-np19py27_0   defaults
    bokeh:             0.9.0-np19py27_0   defaults --> 0.8.1-np19py27_1   defaults
    boto:              2.38.0-py27_0      defaults --> 2.36.0-py27_0      defaults
    cffi:              1.1.0-py27_0       defaults --> 0.9.2-py27_0       defaults
    cryptography:      0.9.1-py27_0       defaults --> 0.8-py27_1         defaults
    cython:            0.22.1-py27_0      defaults --> 0.22-py27_0        defaults
    cytoolz:           0.7.3-py27_0       defaults --> 0.7.2-py27_0       defaults
    datashape:         0.4.5-np19py27_0   defaults --> 0.4.4-np19py27_1   defaults
    decorator:         4.0.4-py27_0       defaults --> 3.4.0-py27_0       defaults
    greenlet:          0.4.7-py27_0       defaults --> 0.4.5-py27_0       defaults
    h5py:              2.5.0-np19py27_1   defaults --> 2.4.0-np19py27_0   defaults
    ipython:           4.0.0-py27_1       defaults --> 3.0.0-py27_1       defaults
    ipython-notebook:  4.0.4-py27_3       defaults --> 3.0.0-py27_2       defaults
    ipython-qtconsole: 4.0.1-py27_4       defaults --> 3.0.0-py27_1       defaults
    jedi:              0.9.0-py27_0       defaults --> 0.8.1-py27_0       defaults
    jinja2:            2.8-py27_0         defaults --> 2.7.3-py27_2       defaults
    llvmlite:          0.5.0-py27_0       defaults --> 0.2.2-py27_1       defaults
    lxml:              3.4.4-py27_0       defaults --> 3.4.2-py27_0       defaults
    matplotlib:        1.5.0-np110py27_0  defaults --> 1.4.3-np19py27_1   defaults
    menuinst:          1.3.1-py27_0       defaults --> 1.0.4-py27_0       defaults
    mistune:           0.7.1-py27_0       defaults --> 0.5.1-py27_0       defaults
    networkx:          1.10-py27_0        defaults --> 1.9.1-py27_0       defaults
    nltk:              3.0.3-np19py27_0   defaults --> 3.0.2-np19py27_0   defaults
    nose:              1.3.7-py27_0       defaults --> 1.3.4-py27_1       defaults
    numba:             0.19.1-np19py27_0  defaults --> 0.17.0-np19py27_0  defaults
    numexpr:           2.4.3-np19py27_p0  defaults [mkl] --> 2.3.1-np19py27_p0 defaults [mkl]
    numpy:             1.10.1-py27_p0     defaults [mkl] --> 1.9.2-py27_p0 defaults [mkl]
    odo:               0.3.2-np19py27_0   defaults --> 0.3.1-np19py27_0   defaults
    pandas:            0.17.1-np110py27_0 defaults --> 0.15.2-np19py27_1  defaults
    pillow:            2.9.0-py27_0       defaults --> 2.7.0-py27_0       defaults
    pip:               7.1.2-py27_0       defaults --> 6.0.8-py27_0       defaults
    ply:               3.6-py27_0         defaults --> 3.4-py27_0         defaults
    psutil:            3.2.2-py27_0       defaults --> 2.2.1-py27_0       defaults
    py:                1.4.27-py27_0      defaults --> 1.4.26-py27_0      defaults
    pycparser:         2.14-py27_0        defaults --> 2.10-py27_0        defaults
    pyflakes:          1.0.0-py27_0       defaults --> 0.8.1-py27_0       defaults
    pyopenssl:         0.15.1-py27_1      defaults --> 0.14-py27_0        defaults
    pyqt:              4.11.4-py27_4      defaults --> 4.10.4-py27_1      defaults
    pyreadline:        2.1-py27_0         defaults --> 2.0-py27_0         defaults
    pytables:          3.2.0-np19py27_0   defaults --> 3.1.1-np19py27_1   defaults
    pytest:            2.7.1-py27_0       defaults --> 2.6.4-py27_0       defaults
    python:            2.7.11-0           defaults --> 2.7.9-1            defaults
    python-dateutil:   2.4.2-py27_0       defaults --> 2.4.1-py27_0       defaults
    pytz:              2015.7-py27_0      defaults --> 2015.2-py27_0      defaults
    pyyaml:            3.11-py27_2        defaults --> 3.11-py27_0        defaults
    pyzmq:             14.7.0-py27_1      defaults --> 14.5.0-py27_0      defaults
    requests:          2.8.1-py27_0       defaults --> 2.6.0-py27_0       defaults
    scikit-image:      0.11.3-np19py27_0  defaults --> 0.11.2-np19py27_0  defaults
    scikit-learn:      0.16.1-np19py27_p0 defaults [mkl] --> 0.15.2-np19py27_p0 defaults [mkl]
    scipy:             0.16.0-np19py27_p0 defaults [mkl] --> 0.15.1-np19py27_p0 defaults [mkl]
    setuptools:        18.5-py27_0        defaults --> 14.3-py27_0        defaults
    six:               1.10.0-py27_0      defaults --> 1.9.0-py27_0       defaults
    sphinx:            1.3.1-py27_0       defaults --> 1.2.3-py27_0       defaults
    spyder:            2.3.7-py27_3       defaults --> 2.3.4-py27_1       defaults
    spyder-app:        2.3.7-py27_0       defaults --> 2.3.4-py27_0       defaults
    sqlalchemy:        1.0.5-py27_0       defaults --> 0.9.9-py27_0       defaults
    toolz:             0.7.2-py27_0       defaults --> 0.7.1-py27_0       defaults
    tornado:           4.2.1-py27_1       defaults --> 4.1-py27_0         defaults
    werkzeug:          0.10.4-py27_0      defaults --> 0.10.1-py27_0      defaults
    xlsxwriter:        0.7.3-py27_0       defaults --> 0.6.7-py27_0       defaults
    xlwings:           0.3.5-py27_0       defaults --> 0.3.4-py27_0       defaults
    xlwt:              1.0.0-py27_0       defaults --> 0.7.5-py27_0       defaults

Proceed ([y]/n)? y

Fetching packages ...
python-2.7.9-1 100% |###############################| Time: 0:00:23 828.76 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  25%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 691, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: 'C:\\Anaconda\\conda-meta\\ipython-4.0.0-py27_1.json'

C:\Anaconda>conda update anaconda
Error: package 'anaconda' is not installed in C:\Anaconda

C:\Anaconda>conda update conda
Fetching package metadata: ....
# All requested packages already installed.
# packages in environment at C:\Anaconda:
#
conda                     3.18.8                   py27_0    defaults

C:\Anaconda>conda update anaconda
Error: package 'anaconda' is not installed in C:\Anaconda

C:\Anaconda>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.1.0
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False


C:\Anaconda>
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
