### ISSUE TITLE
Creating conda environment (dato-env) giving error

### ISSUE THREAD

**Issue by karimkhanp** [conda/conda#1902]
datametica@DM071:~/Documents/karim/study/machine_learning_fundamental$ sudo conda create -n dato-env python=2.7 anaconda
Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

```

Traceback (most recent call last):
  File "/usr/local/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/usr/local/lib/python2.7/dist-packages/conda/plan.py", line 403, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 747, in solve
    minimal_hint=minimal_hint)
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 492, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 350, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')
```

**Comment by kilimba** [comment]
Hello, am having the same problem. Am also doing the same coursera course. Did you find a solution?

**Comment by karimkhanp** [comment]
@kilimba No, I have not found any solution. Actually this preventing me to proceed further.

**Comment by karimkhanp** [comment]
I have started this discussion on course group, stay updated there too - https://www.coursera.org/learn/ml-foundations/module/jw04R/discussions/AjB44aIsEeWG0xJGD15hdw 
Let me know if you find any help

**Comment by doaa-altarawy** [comment]
I've this error too on a vagrant VM. I created the conda virtual env on two machines (CentOS 7 and Ubuntu 14.04), but it failed on a vagrant ubuntu 14.04.
I've python 2.7.10, and Andaconda 2.3 (64bits).

**Comment by Wildcarde** [comment]
We are seeing this in Centos 6 as well, even simple conda update commands fail.

**Comment by brendon9x** [comment]
Verified this happens on Anaconda 2.1.0 on Ubuntu 14.04 Docker image.  This used to work.

**Comment by kalefranz** [comment]
I believe this should be fixed now.  Can this be verified as still a problem in conda 4.3.17 or later?
