### ISSUE TITLE
conda create env fails from spec-file

### ISSUE THREAD

**Issue by nuwar** [conda/conda#1904]
`conda create --name advise_env --file .\spec-file.txt`  
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 333, in install
    update_deps=args.update_deps)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 406, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 334, in add_defaults_to_specs
    if r.explicit(specs):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 971, in explicit
    if spec != 'conda']
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 310, in __init__
    assert 1 <= self.strictness <= 3, repr(spec)
AssertionError: '\x00_\x00l\x00i\x00c\x00e\x00n\x00s\x00e\x00 \x001\x00.\x001\x00 \x00p\x00y\x002\x007\x00_\x000\x00\r\x00'

**Comment by ilanschnell** [comment]
What is the content of your spec file `spec-file.txt`?  It looks like it has some binary content.  Which Windows editor did you use to create this file?
