### ISSUE TITLE
conda install -y -n ana anaconda fails on assertion

### ISSUE THREAD

**Issue by malgaudreault** [conda/conda#1910]
```python
{"changed": true, "cmd": "conda install -y -n ana anaconda", "delta": "0:00:01.647602", "end": "2015-12-15 03:48:49.676498", "rc": 1, "start": "2015-12-15 03:48:48.028896", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/jupyterhub/anaconda/envs/ana/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')
stdout: Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

FATAL: all hosts have already failed -- aborting
```

conda info: 
```python
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /usr/local/jupyterhub/anaconda  (read only)
  default environment : /usr/local/jupyterhub/anaconda/envs/ana
     envs directories : /home/ubuntu/.conda/envs
                        /home/ubuntu/envs
                        /usr/local/jupyterhub/anaconda/envs
        package cache : /home/ubuntu/.conda/envs/.pkgs
                        /home/ubuntu/envs/.pkgs
                        /usr/local/jupyterhub/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by groutr** [comment]
What is already installed in the `ana` environment?  I'm unable to reproduce the problem on my machine.  Is there any additional info that you could give that will help me be able to reproduce this?

**Comment by malgaudreault** [comment]
Howdy! Thanks for getting back to me, below is the configuration from creation of the environment to the install command in yaml being run by ansible.

```yaml
- name: create an environment in which to run anaconda
  shell: /usr/local/jupyterhub/anaconda/bin/conda create -n ana python=2.7.11 -y

- name: install ipython in the new conda environment
  shell: conda install -n ana IPython=3.2.1 ipython-notebook -y
  environment:
    PATH: "/usr/local/jupyterhub/anaconda/envs/ana/bin:{{ ansible_env.PATH }}"

- name: install the anaconda libraries
  shell: conda install -y -n ana anaconda
  environment:
    PATH: "/usr/local/jupyterhub/anaconda/envs/ana/bin:{{ ansible_env.PATH }}"
```

**Comment by malgaudreault** [comment]
Suppose I could try reversing the order of the library install and the ipython install. Further info about the machine causing this error:

```bash
Welcome to Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-71-generic x86_64)

 * Documentation:  https://help.ubuntu.com/

  System information as of Wed Dec 16 22:58:13 UTC 2015

  System load:  0.0               Processes:           108
  Usage of /:   5.6% of 98.30GB   Users logged in:     0
  Memory usage: 9%                IP address for eth0: 172.31.36.166
  Swap usage:   0%

  Graph this data and manage this system at:
    https://landscape.canonical.com/

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.


Last login: Wed Dec 16 22:58:13 2015 from x.x.x.x.ec2.internal
# system python
[ubuntu@testbed:~] which python
/usr/bin/python
[ubuntu@testbed:~] python --version
Python 2.7.6
[ubuntu@testbed:~] source /usr/local/jupyterhub/py/bin/activate
# python for jupyterhub
(py)[ubuntu@testbed:~] which python
/usr/local/jupyterhub/py/bin/python
(py)[ubuntu@testbed:~] python --version
Python 3.4.3
# and finally python for anaconda
(py)[ubuntu@testbed:~] source /usr/local/jupyterhub/anaconda/envs/ana/bin/activate ana
discarding /usr/local/jupyterhub/anaconda/bin from PATH
prepending /usr/local/jupyterhub/anaconda/envs/ana/bin to PATH
(ana)(py)[ubuntu@testbed:~] which python
/usr/local/jupyterhub/anaconda/envs/ana/bin/python
(ana)(py)[ubuntu@testbed:~] python --version
Python 2.7.11 :: Continuum Analytics, Inc.
```

Let me know if there are any other questions I can answer.

**Comment by malgaudreault** [comment]
If you would like to review the entire ansible script for this deployment, it is available here: https://github.com/malgaudreault/deploy_jupyterhub

**Comment by groutr** [comment]
Just a few notes:
1. pip is available in anaconda as a conda package (`conda install pip`) (from https://github.com/malgaudreault/deploy_jupyterhub/blob/master/roles/anaconda/tasks/main.yml)
2. I would suggest installing the anaconda package first in the new environment.  Installing it last will downgrade any packages updated since the last anaconda release.  Can you still reproduce the error if you install anaconda first?

**Comment by groutr** [comment]
Another thing that I find odd is that there is no package named `py2cairo` in the repositories.  I wonder where that is coming from.

**Comment by malgaudreault** [comment]
Here's the result from the run that I did with the libraries installed first. 

```python
failed: [] => {"changed": true, "cmd": "conda install -y -n ana anaconda", "delta": "0:00:00.980572", "end": "2015-12-17 22:56:48.023985", "rc": 1, "start": "2015-12-17 22:56:47.043413", "warnings": []}
stderr: Traceback (most recent call last):
  File "/usr/local/jupyterhub/anaconda/envs/ana/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/usr/local/jupyterhub/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')
stdout: Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

FATAL: all hosts have already failed -- aborting
```

```bash
[ubuntu@testbed:~] source /usr/local/jupyterhub/anaconda/envs/ana/bin/activate ana
discarding /usr/local/jupyterhub/anaconda/bin from PATH
prepending /usr/local/jupyterhub/anaconda/envs/ana/bin to PATH
(ana)[ubuntu@testbed:~] conda info
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /usr/local/jupyterhub/anaconda  (read only)
  default environment : /usr/local/jupyterhub/anaconda/envs/ana
     envs directories : /home/ubuntu/.conda/envs
                        /home/ubuntu/envs
                        /usr/local/jupyterhub/anaconda/envs
        package cache : /home/ubuntu/.conda/envs/.pkgs
                        /home/ubuntu/envs/.pkgs
                        /usr/local/jupyterhub/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by malgaudreault** [comment]
Looks like this was resulting from the script trying to install an old version of anacoda. I've updated the download link to the latest release and the deployment works just fine now. Thanks a bunch for your help with this.

**Comment by groutr** [comment]
No problem, I'm glad it worked out. :)
