### ISSUE TITLE
conda error updating numba

### ISSUE THREAD

**Issue by jason-s** [conda/conda#1914]
```
C:\>conda update numba
Fetching package metadata: ...An unexpected error has occurred, please consider
sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "c:\app\python\anaconda\1.6.0\Scripts\conda-script.py", line 4, in <modul
e>
    sys.exit(main())
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\cli\main.py", line
195, in main
    args_func(args, p)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\cli\main.py", line
202, in args_func
    args.func(args, p)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\cli\main_update.py"
, line 48, in execute
    install.install(args, parser, 'update')
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\cli\install.py", li
ne 239, in install
    offline=args.offline)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\cli\common.py", lin
e 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\api.py", line 42, i
n get_index
    unknown=unknown)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\utils.py", line 118
, in __call__
    value = self.func(*args, **kw)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\fetch.py", line 259
, in fetch_index
    repodatas.append((url, future.result()))
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\concurrent\futures\_base.
py", line 400, in result
    return self.__get_result()
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\concurrent\futures\_base.
py", line 359, in __get_result
    reraise(self._exception, self._traceback)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\concurrent\futures\_compa
t.py", line 107, in reraise
    exec('raise exc_type, exc_value, traceback', {}, locals_)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\concurrent\futures\thread
.py", line 61, in run
    result = self.fn(*self.args, **self.kwargs)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\fetch.py", line 65,
 in func
    res = f(*args, **kwargs)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\conda\fetch.py", line 100
, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\sessions.py", li
ne 480, in get
    return self.request('GET', url, **kwargs)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\sessions.py", li
ne 468, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\sessions.py", li
ne 576, in send
    r = adapter.send(request, **kwargs)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\adapters.py", li
ne 376, in send
    timeout=timeout
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\packages\urllib3
\connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\packages\urllib3
\connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\packages\urllib3
\connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\packages\urllib3
\connection.py", line 259, in connect
    cert = self.sock.getpeercert()
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 251, in getpeercert
    for value in get_subj_alt_name(x509)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 144, in get_subj_alt_name
    asn1Spec=general_names)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pyasn1\codec\ber\decoder.
py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pyasn1\type\univ.py", lin
e 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "c:\app\python\anaconda\1.6.0\lib\site-packages\pyasn1\type\namedtype.py"
, line 68, in getPositionByType
    raise error.PyAsn1Error('Type %s not found' % (tagSet,))
pyasn1.error.PyAsn1Error: Type TagSet(Tag(tagClass=128, tagFormat=0, tagId=2)) n
ot found

C:\>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.9
  conda-build version : 1.8.2
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : c:\app\python\anaconda\1.6.0  (writable)
  default environment : c:\app\python\anaconda\1.6.0
     envs directories : c:\app\python\anaconda\1.6.0\envs
        package cache : c:\app\python\anaconda\1.6.0\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by jason-s** [comment]
If I do `conda update numba` a second time, it worked fine.

**Comment by groutr** [comment]
Have you been able to reliably reproduce the problem?

**Comment by jason-s** [comment]
I've been able to reproduce it but not reliably -- it's happened twice today (each time, running it again is successful).

**Comment by jason-s** [comment]
Just tried it again with `conda update matplotlib` and that causes the same thing... but this time it failed twice and succeeded the third time. I have no idea what to look for, so unless someone can guide me what to do in order to gain more information, I don't see how the root cause can be ascertained (I certainly can't do it).

**Comment by jason-s** [comment]
Is there any kind of install log I can post here?

**Comment by groutr** [comment]
You can try doing `conda --debug install <pkg>`  This will produce lots of debug output, you'll probably want to redirect to a file.

**Comment by jason-s** [comment]
feature-request: add `--debug-file debugfile.log` so debug output and std output are separate

**Comment by branning** [comment]
@jason-s The debug output is written to `stderr`, so you can redirect that output to a file, separately from the standard output. [Also, you can use I/O redirection on Windows](https://technet.microsoft.com/en-us/library/bb490982(en-us).aspx), it works the same way as on POSIX systems.

    conda --debug install matplotlib 2>conda_debug.out

**Comment by jason-s** [comment]
huh, I'd forgotten about this. Just did `conda update numba` with no problems. Who knows what the problem was....
