### ISSUE TITLE
conda install scikit-bio fails after sudo pip install

### ISSUE THREAD

**Issue by lzamparo** [conda/conda#1918]
Weird behaviour from sudo pip causes `conda install scikit-bio` to fail.  See the gists [here](https://gist.github.com/lzamparo/e5d00d7f644586d5b6db), but the relevant problem (I think) is that sudo pip somehow changes the permissions on a directory that conda is trying to access:

```
Traceback (most recent call last):
  File "/Users/zamparol/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/zamparol/anaconda/lib/python2.7/site-packages/conda/install.py", line 616, in link
    os.makedirs(dst_dir)
  File "/Users/zamparol/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/zamparol/anaconda/lib/python2.7/site-packages/skbio/draw'
```

Probably not a huge deal, but I figured I'd report it all the same.

**Comment by ilanschnell** [comment]
Thanks for reporting the issue.  Yes, this a permissions problem, cause by running "sudo pip".
