### ISSUE TITLE
Anaconda on Windows 10

### ISSUE THREAD

**Issue by ksoosk** [conda/conda#1925]
Installed the latest release of Anaconda on Windows 10 machine. A simple command of "conda list" is throwing the following message. Conda info is alo provided.

C:<dir>\conda list
# packages in environment at C:<dir>\Anaconda3new:
# 

Traceback (most recent call last):
  File "C:<dir>\Anaconda3new\Scripts\pip-script.py", line 3, in <module>
    from pip import main
  File "C:<dir>\Anaconda3new\lib\site-packages\pip__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:<dir>\Anaconda3new\lib\site-packages\pip\vcs\mercurial.py", line 10, in <module>
    from pip.download import path_to_url
  File "C:<dir>\Anaconda3new\lib\site-packages\pip\download.py", line 38, in <module>
    from pip._vendor import requests, six
  File "C:<dir>\Anaconda3new\lib\site-packages\pip_vendor\requests__init__.py", line 59, in <module>
    from .models import Request, Response, PreparedRequest
  File "C:<dir>\Anaconda3new\lib\site-packages\pip_vendor\requests\models.py", line 49, in <module>
    json_dumps = json.dumps
AttributeError: module 'simplejson' has no attribute 'dumps'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:<dir>\Anaconda3new\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\cli\main_list.py", line 246, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\cli\main_list.py", line 177, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\pip.py", line 49, in installed
    args = pip_args(prefix)
  File "C:<dir>\Anaconda3new\lib\site-packages\conda\pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "C:<dir>\Anaconda3new\lib\subprocess.py", line 629, in check_output
    **kwargs).stdout
  File "C:<dir>\Anaconda3new\lib\subprocess.py", line 711, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['C:<dir>\Anaconda3new\python.exe', 'C:<dir>\Anaconda3new\Scripts\pip-script.py', '-V']' returned non-zero exit status 1

Current conda install:

```
         platform : win-64
    conda version : 3.18.8
```

  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.8.1
     root environment : C:Current conda install:

```
         platform : win-64
    conda version : 3.18.8
```

  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.8.1
     root environment : C:<dir>\Anaconda3new  (writable)
  default environment : C:<dir>\Anaconda3new
     envs directories : C:<dir>\Anaconda3new\envs
        package cache : C:<dir>\Anaconda3new\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by tyler-thetyrant** [comment]
Closing outdated.
