### ISSUE TITLE
Can't remove an environment

### ISSUE THREAD

**Issue by enfeizhan** [conda/conda#1927]
Here is the traceback:
Traceback (most recent call last):
  File "/Users/feizhan/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/feizhan/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/Users/feizhan/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/Users/feizhan/miniconda/lib/python2.7/site-packages/conda/cli/main_remove.py", line 157, in execute
    rm_rf(prefix)
  File "/Users/feizhan/miniconda/lib/python2.7/site-packages/conda/install.py", line 186, in rm_rf
    shutil.rmtree(path)
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/Users/feizhan/miniconda/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Users/feizhan/miniconda/envs/py3.5_env/lib/python3.5/site-packages/ipython-4.0.1-py3.5.egg/EGG-INFO/dependency_links.txt'

And here is the output of 'conda info':
Current conda install:

             platform : osx-64
        conda version : 3.16.0
  conda-build version : not installed
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/feizhan/miniconda  (writable)
  default environment : /Users/feizhan/miniconda
     envs directories : /Users/feizhan/miniconda/envs
        package cache : /Users/feizhan/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Any idea what's wrong? Thanks

**Comment by ilanschnell** [comment]
Did you use create the environment (or install packages into the environment) as root?

**Comment by enfeizhan** [comment]
Should be. As I remember I tried to install bazel as root when failed to install it as a normal user. Now problem solved. I removed the env as root. Great thanks :)
