### ISSUE TITLE
Windows Python 2.7 conda error

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda#1936]
There is a problem with Windows Python 2.7 conda that is holding up the anaconda-build workers (see also [this issue there](https://github.com/Anaconda-Server/anaconda-build/issues/150)).  The attempt is to create a Python 2 environment with numpy 1.9 but ends in permission error with miniconda.  See below.

```
conda create -p "C:\Documents and Settings\IEUser\builds\psteinberg\conda_build_test\env" --quiet --yes python=2 numpy=1.9
```

```
Fetching package metadata: ....
Solving package specifications: ...........
Package plan for installation in environment C:\Documents and Settings\IEUser\bu
ilds\psteinberg\conda_build_test\env2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    msvc_runtime-1.0.1         |            vc9_0         1.1 MB
    python-2.7.11              |                0        16.8 MB
    numpy-1.9.3                |           py27_0        14.4 MB
    setuptools-19.1.1          |           py27_0         647 KB
    wheel-0.26.0               |           py27_1         114 KB
    pip-7.1.2                  |           py27_0         1.4 MB
    ------------------------------------------------------------
                                           Total:        34.4 MB

The following NEW packages will be INSTALLED:

    msvc_runtime: 1.0.1-vc9_0   [vc9]
    numpy:        1.9.3-py27_0
    pip:          7.1.2-py27_0
    python:       2.7.11-0
    setuptools:   19.1.1-py27_0
    wheel:        0.26.0-py27_1

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 202, in args_fun
c
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda\cli\main_create.py", line 49, in ex
ecute
    install.install(args, parser, 'create')
  File "C:\Miniconda\lib\site-packages\conda\cli\install.py", line 423, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 537, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 148, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 62, in EXTRA
CT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Miniconda\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Miniconda\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Miniconda\lib\tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Miniconda\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Miniconda\\pkgs\\python-2.7.11-0\\D
LLs\\_ctypes.pyd'
```

**Comment by msarahan** [comment]
This is actually not a conda error.  It is happening because of some zombie Python processes.  Ask @srossross about it - he was working on a way to kill them.
