### ISSUE TITLE
conda info exception when envs directory doesn't exist

### ISSUE THREAD

**Issue by bkreider** [conda/conda#1937]
```
(root)-bash-4.2# /opt/wakari/anaconda/bin/conda info  libpng
Fetching package metadata: ......

libpng 1.2.50 0
---------------
file name   : libpng-1.2.50-0.tar.bz2
name        : libpng
version     : 1.2.50
build number: 0
build string: 0
channel     : defaults
size        : 584 KB
date        : 2014-08-22
license     : libpng license (http://www.libpng.org/pub/png/src/libpng-LICENSE.txt)
license_family: Other
md5         : 7dd2a5f888450d1105d940ce7cb85777
installed environments:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 179, in execute
    pretty_package(pkg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 141, in pretty_package
    for env in app_is_installed(pkg.fn):
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/api.py", line 107, in app_is_installed
    for fn2 in os.listdir(envs_dir):
OSError: [Errno 2] No such file or directory: '/opt/wakari/anaconda/envs'
```

Conda info output:

```
(root)-bash-4.2# /opt/wakari/anaconda/bin/conda info
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.9.0
     root environment : /opt/wakari/anaconda  (writable)
  default environment : /opt/wakari/anaconda
     envs directories : /opt/wakari/anaconda/envs
        package cache : /opt/wakari/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/anaconda-cluster/linux-64/
                        https://conda.anaconda.org/anaconda-cluster/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /root/.condarc
    is foreign system : False

```

**Comment by tyler-thetyrant** [comment]
Should be okay in the recent version of Conda.
