### ISSUE TITLE
Scipy install error

### ISSUE THREAD

**Issue by danhamill** [conda/conda#1942]
when i type 
    conda install scipy=0.16

I get the following traceback:
Traceback (most recent call last):
  File "c:\Users\dan\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in main
    args_func(args, p)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\cli\main.py", line 212, in args_func
    args.func(args, p)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\cli\common.py", line 609, in inner
    return func(args, parser)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\cli\main_install.py", line 51, in execute
    install.install(args, parser, 'install')
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\plan.py", line 531, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\instructions.py", line 156, in execute_instructions
    cmd(state, arg)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\instructions.py", line 105, in ENSURE_WRITE_CMD
    install.ensure_write(state["prefix"], arg)
  File "c:\Users\dan\Anaconda\lib\site-packages\conda\install.py", line 658, in ensure_write
    files = [a for a in meta["files"] if not a.lower().endswith("conda.exe")]
TypeError: 'NoneType' object has no attribute '__getitem__'

conda info yields 

$ conda info
Current conda install:

             platform : win-64
        conda version : 3.11.0-dirty
  conda-build version : 1.8.2
       python version : 2.7.8.final.0
     requests version : 2.7.0
     root environment : c:\Users\dan\Anaconda  (writable)
  default environment : c:\Users\dan\Anaconda
     envs directories : c:\Users\dan\Anaconda\envs
        package cache : c:\Users\dan\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ilanschnell** [comment]
Thanks for the error report.  You are using a version of conda which is quite old.  Have you tried updating conda (using `conda update conda`)?

**Comment by danhamill** [comment]
Thanks for follwoing up.  For my specific issue I got scipy to install by:
    conda update -f pip
    conda update -f pyyaml
    conda install scipy

I have updated conda to version 3.19

**Comment by ilanschnell** [comment]
Great
