### ISSUE TITLE
Conda + gurobi

### ISSUE THREAD

**Issue by renatodeleone** [conda/conda#1943]
Fetching package metadata: ....An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\compiler\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\compiler\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\compiler\Anaconda3\lib\site-packages\conda\cli\install.py", line 239, in install
    offline=args.offline)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\cli\common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\api.py", line 42, in get_index
    unknown=unknown)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\compiler\Anaconda3\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\compiler\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\compiler\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\compiler\Anaconda3\lib\site-packages\conda\fetch.py", line 103, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
  File "C:\compiler\Anaconda3\lib\bz2.py", line 348, in decompress
    res = decomp.decompress(data)
OSError: Invalid data stream

============

C:\Users\Renato>conda info
Current conda install:

             platform : win-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.0
     root environment : C:\compiler\Anaconda3  (writable)
  default environment : C:\compiler\Anaconda3
     envs directories : C:\compiler\Anaconda3\envs
        package cache : C:\compiler\Anaconda3\pkgs
         channel URLs : http://conda.anaconda.org/gurobi/win-64/
                        http://conda.anaconda.org/gurobi/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Renato\.condarc
    is foreign system : False

**Comment by ilanschnell** [comment]
Which is the exact command you tried to execute?

**Comment by renatodeleone** [comment]
I was trying to install the gurobi enviroment. From my office that was
impossible, Then I returned home, tried again and it worked. I suspect that
the error s linked to some firewall we have at the office, Thanks

2016-01-09 19:45 GMT+01:00 Ilan Schnell <notifications@github.com>:

> Which is the exact command you tried to execute?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/1943#issuecomment-170268929>.
>



-- 
Renato
