### ISSUE TITLE
Anaconda AssertionError: SRE module mismatch on windows 8.1

### ISSUE THREAD

**Issue by aktech** [conda/conda#1948]
I installed the Python3.5 version of Anaconda (64bit) for windows from here:
https://www.continuum.io/downloads#_windows

And this is what happens, when I try to run `ipython`
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Users\Amit>ipython
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\ipython-script.py", line 3, in <module>
    from IPython import start_ipython
  File "C:\Anaconda3\lib\site-packages\IPython\__init__.py", line 47, in <module>
    from .core.application import Application
  File "C:\Anaconda3\lib\site-packages\IPython\core\application.py", line 16, in <module>
    import glob
  File "C:\Python34\Lib\glob.py", line 4, in <module>
    import re
  File "C:\Python34\Lib\re.py", line 123, in <module>
    import sre_compile
  File "C:\Python34\Lib\sre_compile.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
AssertionError: SRE module mismatch

C:\Users\Amit>
```

**Comment by aktech** [comment]
Reported here: https://github.com/ContinuumIO/anaconda-issues/issues/619

**Comment by enitihas** [comment]
I got the same problem. How did you solve this?

**Comment by micro0524** [comment]
Encountered this error when I have another version of python installed before installing Anaconda.
I had python3.5 installed but my Anaconda is python3.6, and somehow my PATH have some %PYTHONHOME%;%PYTHONHOME%/Scripts referencing my old python.

Removing all related env variables of old python fixed that issue.

**Comment by Tono-Kuriakose** [comment]
Create and activate a virtual environment.
