### ISSUE TITLE
Update issue 

### ISSUE THREAD

**Issue by degninou** [conda/conda#1949]
Unlinking packages ...
WARNING:root:Menuinst could not be imported:                             |   0%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 326, in mk_menus
    import menuinst
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 22, in <modul
e>
    from .win32 import Menu, ShortCut
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 14, in <module>
    from .winshortcut import create_shortcut
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in ex
ecute
    install.install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 95, in UNLIN
K_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 692, in unlink
    mk_menus(prefix, meta['files'], remove=True)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 329, in mk_menus
    logging.warn(e.message)
AttributeError: 'ImportError' object has no attribute 'message'

Activating environment "C:\Anaconda3"...

>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by msarahan** [comment]
Hi, please try: ```conda update conda menuinst```

Then try your update again.

**Comment by degninou** [comment]
It works! Thank you, msarahan.
