### ISSUE TITLE
There is a problem when I using info option.

### ISSUE THREAD

**Issue by WBB-Badtaste** [conda/conda#1951]
$ conda info numpy

Fetching package metadata: ....
## numpy 1.5.1 py27_0

file name   : numpy-1.5.1-py27_0.tar.bz2
name        : numpy
version     : 1.5.1
build number: 0
build string: py27_0
channel     : defaults
size        : 2.3 MB
date        : 2014-08-22
license     : BSD
md5         : aec83b6d825690a086e2e20d0cec8c38
installed environments:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/wubinbin/miniconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/wubinbin/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/wubinbin/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/wubinbin/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 179, in execute
    pretty_package(pkg)
  File "/Users/wubinbin/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 141, in pretty_package
    for env in app_is_installed(pkg.fn):
  File "/Users/wubinbin/miniconda2/lib/python2.7/site-packages/conda/api.py", line 107, in app_is_installed
    for fn2 in os.listdir(envs_dir):
OSError: [Errno 2] No such file or directory: '/Users/wubinbin/envs'

**Comment by tyler-thetyrant** [comment]
I cannot reproduce the issue in the recent version of conda.
