### ISSUE TITLE
Problem installing Anaconda2 on a linux 64

### ISSUE THREAD

**Issue by K11K11** [conda/conda#1953]
To start with some info:
$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.18.8
```

  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.2.1
     root environment : /home/konstantinos/anaconda2  (writable)
  default environment : /home/konstantinos/anaconda2
     envs directories : /home/konstantinos/anaconda2/envs
        package cache : /home/konstantinos/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

I have installed-uninstalled and back again anaconda but always getting the same, as soon as I go on trying it:
$ conda update conda
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/konstantinos/anaconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 598, in get_index_trap
    return get_index(_args, *_kwargs)
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/utils.py", line 118, in **call**
    value = self.func(_args, *_kw)
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 237, in fetch_index
    session = CondaSession()
  File "/home/konstantinos/anaconda2/lib/python2.7/site-packages/conda/connection.py", line 61, in **init**
    super(CondaSession, self).**init**(_args, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 272, in **init**
    self.headers = default_headers()
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 555, in default_headers
    'User-Agent': default_user_agent(),
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 524, in default_user_agent
    _implementation = platform.python_implementation()
  File "/usr/lib/python2.7/platform.py", line 1521, in python_implementation
    return _sys_version()[0]
  File "/usr/lib/python2.7/platform.py", line 1486, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.11 |Anaconda 2.4.1 (64-bit)| (default, Dec  6 2015, 18:08:32) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

**Comment by hflamboauto1** [comment]
Same problem here:
```conda install anaconda
Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/usr/local/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/usr/local/lib/python2.7/dist-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/usr/local/lib/python2.7/dist-packages/conda/plan.py", line 403, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 747, in solve
    minimal_hint=minimal_hint)
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 492, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/usr/local/lib/python2.7/dist-packages/conda/resolve.py", line 350, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')
```
conda info
```
conda info
Current conda install:

             platform : linux-64
        conda version : 3.17.0
  conda-build version : not installed
       python version : 2.7.3.final.0
     requests version : 2.9.1
     root environment : /usr  (writable)
  default environment : /usr
     envs directories : /usr/envs
        package cache : /usr/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : True
```

**Comment by zhanxw** [comment]
Please check if you have **/home/konstantinos/.local** folder. 
I found that folder will cause these error messages for conda.

**Comment by zhanxw** [comment]
Also see: https://github.com/ContinuumIO/anaconda-issues/issues/394
