### ISSUE TITLE
Traceback updating anaconda version 3.4.1 to latest version on 1/15/2016

### ISSUE THREAD

**Issue by thungp** [conda/conda#1956]
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |   6%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/thungp/anaconda/bin/conda", line 5, in <module>
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/plan.py", line 419, in execute_actions
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/plan.py", line 401, in execute_plan
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/plan.py", line 357, in link
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/install.py", line 438, in link
  File "/Users/thungp/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text bin/fits2bitmap'
~/anaconda/bin $ 

conda was previously able to get me a version, but at the point of failure, I get no such file or directory when I type conda info.

Please advise.

**Comment by thungp** [comment]
Operating system I was updating anaconda was OS X El Capitan version 10.11.2

**Comment by tyler-thetyrant** [comment]
Closing outdated.
