### ISSUE TITLE
Conda on windows can not reliably host long running applications

### ISSUE THREAD

**Issue by srossross** [conda/conda#1961]
When running on windows conda can not reliably host server applications. Windows locks executables and dlls that are in use, even ones that are hard linked. This means that when a long running process is running - even in a clean environment - the python dll in the root environment can not be removed.

```
An unexpected error has occurred, please consider sending the            |  20%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-build-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 190, in
main
    args_func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 468, in
args_func
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda_build\main_build.py", line 391, in
execute
    override_channels=args.override_channels, include_recipe=args.include_recipe
)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 380, in build

    override_channels=override_channels)
  File "C:\Miniconda\lib\site-packages\conda_build\build.py", line 285, in creat
e_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "C:\Miniconda\lib\site-packages\conda\plan.py", line 537, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 148, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Miniconda\lib\site-packages\conda\instructions.py", line 62, in EXTRA
CT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Miniconda\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Miniconda\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Miniconda\lib\tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Miniconda\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Miniconda\\pkgs\\python-2.7.11-0\\D
LLs\\_ctypes.pyd'
```

**Comment by kalefranz** [comment]
@msarahan Can you chime in here and comment on this?

**Comment by msarahan** [comment]
I'm not sure this is an issue with Conda.  If it is, then it is a major
design flaw with the whole "Conda rides on the back of the root env"
concept.  I don't see any way around this: yes, if you have processes
running that are using files, then you won't be able to replace/remove
those files.  The only way around this is to have those files not in use,
which means two Python installations - one for conda, and another for the
long-running process.

For Anaconda Server or whatever, this can be just two Miniconda
installations - one hosting the long-running process, and another for the
update stuff.

Are there generally programs that are happy having their host program
replaced out from under them?  I guess Linux continues with whatever is
currently in memory, so it's fine.  That's just not how Windows works,
unfortunately.

**Comment by shauryaparanjape** [comment]
An alternative solution to installing any package so that it reflects in anaconda/jupyter python notebook is to navigate to *\Anaconda3\Scripts folder in the windows command prompt. Then instead of installing using conda install, you can use a pip install. It worked for me.
