### ISSUE TITLE
"conda remove openssl zlib" breaks conda

### ISSUE THREAD

**Issue by max-l** [conda/conda#1965]
I'm new to conda. 

I created an env with  `conda create -n my-env python`  and noticed there are quite a few packages
already in the new env :

```
(my-env)vagrant@altorf-lib:~$ conda list
# packages in environment at /home/vagrant/miniconda2/envs/my-env:
#
openssl                   1.0.2e                        0  
pip                       7.1.2                    py27_0  
python                    2.7.11                        0  
readline                  6.2                           2  
setuptools                19.2                     py27_0  
wheel                     0.26.0                   py27_1  
zlib                      1.2.8                         0  
(my-env)vagrant@my-lib:~$ conda remove openssl
```

It is unclear if these packages are essential for conda to work, 

It seems like it's the case since I tried to remove a few, and conda broke after
the removal of zlib : 

```
(altorf-env)vagrant@altorf-lib:~$ conda list
# packages in environment at /home/vagrant/miniconda2/envs/altorf-env:
#
Traceback (most recent call last):
  File "/home/vagrant/miniconda2/envs/altorf-env/bin/pip", line 4, in <module>
    from pip import main
  File "/home/vagrant/miniconda2/envs/altorf-env/lib/python2.7/site-packages/pip/__init__.py", line 15, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/vagrant/miniconda2/envs/altorf-env/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/vagrant/miniconda2/envs/altorf-env/lib/python2.7/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/vagrant/miniconda2/envs/altorf-env/lib/python2.7/site-packages/pip/wheel.py", line 35, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/home/vagrant/miniconda2/envs/altorf-env/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/home/vagrant/miniconda2/envs/altorf-env/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/vagrant/miniconda2/envs/altorf-env/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 254, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/home/vagrant/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/home/vagrant/miniconda2/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/vagrant/miniconda2/envs/altorf-env/bin/python', '/home/vagrant/miniconda2/envs/altorf-env/bin/pip', '-V']' returned non-zero exit status 1
```

I'm wondering,  are the packages present in the new environment 
part of a minimal "foundation" ?  Should I be able to remove them ?

**Comment by kalefranz** [comment]
Yes, the basic conda environment is pre-populated with absolutely essential-packages. Guess you found out the hard way!

**Comment by groutr** [comment]
Conda will happily remove any package you tell it to remove.

**Comment by ilanschnell** [comment]
No @groutr, conda will not happy remove any package you tell it:
```
$ conda remove python
Fetching package metadata: ......
Error: cannot remove python, pycosat, pyyaml, conda, openssl, requests from root environment
```
At least that's the output I get.

**Comment by kalefranz** [comment]
We should probably add readline, zlib, curses(?), and anything else that's needed for miniconda.

**Comment by ilanschnell** [comment]
`readline` is not needed to run conda, and zlib isn't either.

**Comment by mcg1969** [comment]
The remove behavior needs to be fixed. `conda remove` should not be allowed to leave behind a broken environment without `--force`. I know how to fix this but it is not as simple as my `conda update` PR. That said, some of the cleanup work I am doing in that PR is ultimately with that fix in mind.
