### ISSUE TITLE
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')

### ISSUE THREAD

**Issue by Innarticles** [conda/conda#1973]
Got the following error while trying the first command:
conda create -n dato-env python=2.7 anaconda
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/innarticles/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 337, in install
    minimal_hint=args.alt_hint)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/plan.py", line 402, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 483, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 341, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')

**Comment by ilanschnell** [comment]
Which channels do you have active?  What is the output from `conda info`?

**Comment by Innarticles** [comment]
Thanks @ilanschnell 
I am a newbie here. This is the error I got from my console:

Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/innarticles/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 337, in install
    minimal_hint=args.alt_hint)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/plan.py", line 402, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 483, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/innarticles/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 341, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')

**Comment by ilanschnell** [comment]
Yes, but what do you get when you type:
```
$ conda info
```
?

**Comment by Innarticles** [comment]
Ok, This is what I get:

Current conda install:

             platform : linux-64
        conda version : 3.16.0
  conda-build version : 1.8.2
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/innarticles/anaconda  (writable)
  default environment : /home/innarticles/anaconda
     envs directories : /home/innarticles/anaconda/envs
        package cache : /home/innarticles/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ilanschnell** [comment]
I tried running the exact same command `conda create -n dato-env python=2.7 anaconda`, on a `linux-64` machine, and everything worked fine.  I do, however, use a newer version of `conda`.  Can you try
```
$ conda update conda
```
, and then run your command again?

**Comment by g24swint** [comment]
I am getting the same error when trying to do updates and am running in a shared Linux environment with my own conda envs. When I run conda update anaconda or conda update --all, I get the assertion failure referenced above.

The conda installed in our machine is s 3.7 version and the conda environment symlinks back to the root install of conda. Because of that, I get output like the following
```bash
$ conda update conda
Error: package 'conda' is not installed in /path/to/condaenv/python/conda_envs/dp_env
$ conda install conda 
Error: Package 'conda' may only be installed in the root environment
```
Since I don't have root, I can't update conda - other suggested workarounds?

**Comment by kalefranz** [comment]
Report is for conda 3.16.0.  Closing this issue, as outdated.  If you have a similar stack trace in a recent version of conda, please file a new issue.
