### ISSUE TITLE
ERR in conda create -n dato-env python=2.7 anaconda

### ISSUE THREAD

**Issue by talrozen** [conda/conda#1975]
Hi, I've just ran the following cmd in my computer, and I got the err msg below. 

Please advice.

my_user@eli-ThinkPad-T450s:~$ conda create -n dato-env python=2.7 anaconda
Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/elyporat/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/elyporat/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')

**Comment by tyler-thetyrant** [comment]
Closing outdated.
