### ISSUE TITLE
Updating anaconda fails

### ISSUE THREAD

**Issue by armaneshaghi** [conda/conda#1979]
Trying to update anaconda:
__bash$__ conda update anaconda
```
Fetching package metadata: SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
......
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.
```

__$bash__ conda info

```
Current conda install:

             platform : linux-64
        conda version : 3.16.0
  conda-build version : 1.11.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/arman/anaconda  (writable)
  default environment : /home/arman/anaconda
     envs directories : /home/arman/anaconda/envs
        package cache : /home/arman/anaconda/pkgs
         channel URLs : https://conda.binstar.org/gurobi/linux-64/
                        https://conda.binstar.org/gurobi/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/arman/.condarc
    is foreign system : False

Traceback (most recent call last):
  File "/home/arman/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 337, in install
    minimal_hint=args.alt_hint)
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/plan.py", line 402, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 483, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/arman/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 341, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')
```

**Comment by msarahan** [comment]
Your conda version is very out of date.  Please run

    conda update conda

then try again.

**Comment by armaneshaghi** [comment]
Thank you. This is what happens:

__bash$__  conda update conda

```
Fetching package metadata: SSL verification error [SSL:
CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
failed (_ssl.c:590)
SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
failed (_ssl.c:590)
SSL verification error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify
failed (_ssl.c:590)
......
Solving package specifications: .
Package plan for installation in environment /home/arman/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.4.5            |           py27_0          24 KB
    requests-2.9.0             |           py27_0         604 KB
    conda-3.19.0               |           py27_0         176 KB
    ------------------------------------------------------------
                                           Total:         805 KB

The following packages will be UPDATED:

    conda:      3.16.0-py27_0 --> 3.19.0-py27_0
    conda-env:  2.4.1-py27_0  --> 2.4.5-py27_0
    openssl:    1.0.1k-1      --> 1.0.2d-0
    pip:        7.1.0-py27_1  --> 7.1.2-py27_0
    python:     2.7.10-0      --> 2.7.11-0
    requests:   2.7.0-py27_0  --> 2.9.0-py27_0
    setuptools: 18.1-py27_0   --> 19.1.1-py27_0
    wheel:      0.24.0-py27_0 --> 0.26.0-py27_1

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to
https://repo.continuum.io/pkgs/free/linux-64/conda-env-2.4.5-py27_0.tar.bz2
Error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate
verify failed (_ssl.c:590):
https://repo.continuum.io/pkgs/free/linux-64/conda-env-2.4.5-py27_0.tar.bz2
```

**Comment by armaneshaghi** [comment]
The response to this issue is 

```
conda config --set ssl_verify false
conda update requests
conda config --set ssl_verify true
```
