### ISSUE TITLE
conda create failure

### ISSUE THREAD

**Issue by david-deboer** [conda/conda#1983]
Traceback (most recent call last):
  File "/home/ddeboer/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 50, in execute
    install.install(args, parser, 'create')
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/ddeboer/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')

Current conda install:

```
         platform : linux-64
    conda version : 3.10.0
```

  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /home/ddeboer/anaconda  (writable)
  default environment : /home/ddeboer/anaconda
     envs directories : /home/ddeboer/anaconda/envs
        package cache : /home/ddeboer/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by ivyleavedtoadflax** [comment]
I was generating the same error when trying `conda create -n py27 python=2.7 anaconda` and `conda update anaconda`.

I solved it by reference to [this](http://askubuntu.com/questions/726184/missing-write-permissions-in-home-user-anaconda2) post. For some reason my user account was not set as owner of the `~/anaconda3` folder. Running `sudo chown -R <my user> ~/anaconda3` fixed the issue for me.
