### ISSUE TITLE
Error trying to list installed packages

### ISSUE THREAD

**Issue by ThomasA** [conda/conda#1990]
I have just upgraded my existing Anaconda to 2.4.1, running a `conda update conda` followed by `conda install anaconda=2.4.1`. That, in turn, was followed by `conda install coverage radon`. All of the above appeared to work just fine.
Now, when I try to to run `conda list` I get:

```
# packages in environment at /usr/local/anaconda:
#
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/pip", line 4, in <module>
    import pip
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/utils/__init__.py", line 26, in <module>
    from pip._vendor import pkg_resources
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3130, in <module>
    @_call_aside
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3116, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3143, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 633, in _build_master
    ws = cls()
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 626, in __init__
    self.add_entry(entry)
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 682, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2120, in find_on_path
    path_item, entry, metadata, precedence=DEVELOP_DIST
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2510, in from_location
    py_version=py_version, platform=platform, **kw
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2827, in _reload_version
    md_version = _version_from_file(self._get_metadata(self.PKG_INFO))
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2475, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2643, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2011, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/local/anaconda/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2005, in get_metadata
    with io.open(self.path, encoding='utf-8') as f:
IOError: [Errno 13] Permission denied: '/usr/local/anaconda/lib/python2.7/site-packages/numpydoc-0.4-py2.7.egg-info'
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/usr/local/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 254, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/usr/local/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/local/anaconda/bin/python', '/usr/local/anaconda/bin/pip', '-V']' returned non-zero exit status 1
```

`conda info` says:

```
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /usr/local/anaconda  (read only)
  default environment : /usr/local/anaconda
     envs directories : /home/tha/.conda/envs
                        /home/tha/envs
                        /usr/local/anaconda/envs
        package cache : /home/tha/.conda/envs/.pkgs
                        /home/tha/envs/.pkgs
                        /usr/local/anaconda/pkgs
         channel URLs : https://conda.binstar.org/chroxvi/linux-64/
                        https://conda.binstar.org/chroxvi/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/tha/.condarc
    is foreign system : False
```

**Comment by yasheshgaur** [comment]
Do we have any updates on this? I have a similar error.

**Comment by ThomasA** [comment]
No news from me, unfortunately...

**Comment by tyler-thetyrant** [comment]
Closing outdated. This shouldn't happen in the recent version of conda.
