### ISSUE TITLE
Problem with MacOSX El Capitan 10.11.2 

### ISSUE THREAD

**Issue by h-smith-neu** [conda/conda#1996]
Launcher crashed when updating app glueviz and asked me to send the below:

I tried to do the "conda info" but it seems that the conda app has crashed - can't be found (it was there a few days ago) & looking in the anaconda/bin directory did not show a "conda" app only several with "conda-xxx" where xxx is several different additions... 

I am lost at what to do and am considering re-installing anaconda completely.... Fortunately there is no crunch for using it...

Cheers,

Henry Smith

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/install.py", line 644, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "/Users/hs/anaconda/lib/python2.7/site-packages/conda/install.py", line 291, in update_prefix
    os.remove(path) # Remove file before rewriting to avoid destroying hard-linked cache.
OSError: [Errno 13] Permission denied: '/Users/hs/anaconda/include/openssl/opensslconf.h'

**Comment by tyler-thetyrant** [comment]
Closing outdated.
