### ISSUE TITLE
environment clone failure on OS X

### ISSUE THREAD

**Issue by kellyfitz** [conda/conda#1998]
```
Cookie:~ fitzk$ conda info --envs
# conda environments:
#
root                  *  /Users/fitzk/anaconda

Cookie:~ fitzk$ conda create --name brains --clone root
Fetching package metadata: ....
src_prefix: '/Users/fitzk/anaconda'
dst_prefix: '/Users/fitzk/anaconda/envs/brains'
Packages: 162
Files: 1
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/fitzk/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/fitzk/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/fitzk/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/fitzk/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/fitzk/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 246, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/fitzk/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/fitzk/anaconda/lib/python2.7/site-packages/conda/misc.py", line 237, in clone_env
    shutil.copystat(src, dst)
  File "/Users/fitzk/anaconda/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/Users/fitzk/anaconda/envs/brains/lib/libgcc_s.10.5.dylib'
```

```
Cookie:~ fitzk$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.19.0
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/fitzk/anaconda  (writable)
  default environment : /Users/fitzk/anaconda
     envs directories : /Users/fitzk/anaconda/envs
        package cache : /Users/fitzk/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by ijstokes** [comment]
If I had to guess I'd say there is a weird permissions issue going on here.  Can you execute the following and give us the output?

```bash
ls -Fla /Users/fitzk/anaconda/envs/brains/lib/libgcc_s.10.5.dylib
ls -Flad /Users/fitzk/anaconda/envs/brains/lib/
```

**Comment by nathanielatom** [comment]
I have the same issue, running `sudo conda create --name tardis --clone root`

conda info:
`             platform : osx-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /opt/local/lib/Anaconda  (read only)
  default environment : /opt/local/lib/Anaconda
     envs directories : /Users/Atom/.conda/envs
                        /Users/Atom/envs
                        /opt/local/lib/Anaconda/envs
        package cache : /Users/Atom/.conda/envs/.pkgs
                        /Users/Atom/envs/.pkgs
                        /opt/local/lib/Anaconda/pkgs
         channel URLs : https://conda.binstar.org/auto/osx-64/
                        https://conda.binstar.org/auto/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/Atom/.condarc
    is foreign system : False`

And
`ls -Fla /opt/local/lib/Anaconda/envs/tardis/lib/libgcc_s.10.5.dylib` gives
`-rwxr-xr-x  1 root  admin  61072  3 Dec 01:36 /opt/local/lib/Anaconda/envs/tardis/lib/libgcc_s.10.5.dylib*`

`ls -Flad /opt/local/lib/Anaconda/envs/tardis/lib/` gives
`drwxr-xr-x  4 root  admin  136 27 Jan 23:30 /opt/local/lib/Anaconda/envs/tardis/lib//`

**Comment by michaelbrooks** [comment]
I have this issue as well, and it looks the same as #1930 to me.

**Comment by kellyfitz** [comment]
```
Cookie:~ fitzk$ ls -Fla /Users/fitzk/anaconda/envs/brains/lib/libgcc_s.10.5.dylib
lrwxr-xr-x  1 fitzk  staff  25 Jan 27 10:17 /Users/fitzk/anaconda/envs/brains/lib/libgcc_s.10.5.dylib@ -> /usr/lib/libgcc_s.1.dylib
Cookie:~ fitzk$ ls -Flad /Users/fitzk/anaconda/envs/brains/lib/
drwxr-xr-x  191 fitzk  staff  6494 Jan 28 14:41 /Users/fitzk/anaconda/envs/brains/lib//


```

**Comment by mcg1969** [comment]
Fix here: https://github.com/conda/conda/pull/2194
