### ISSUE TITLE
Error after downgrading openssl conda package

### ISSUE THREAD

**Issue by jbcrail** [conda/conda#2002]
I installed the `postgresql` package via pip. After realizing I wanted to use the conda version instead, I uninstalled the pip version. During the switch, the conda `openssl` was downgraded.

I immediately received this error:

```
(test)[builder@localhost ~]$ conda env export
Traceback (most recent call last):
  File "/home/builder/miniconda2/envs/test/bin/pip", line 4, in <module>
    import pip
  File "/home/builder/miniconda2/envs/test/lib/python2.7/site-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/builder/miniconda2/envs/test/lib/python2.7/site-packages/pip/utils/__init__.py", line 22, in <module>
    from pip.locations import (
  File "/home/builder/miniconda2/envs/test/lib/python2.7/site-packages/pip/locations.py", line 7, in <module>
    import ssl
  File "/home/builder/miniconda2/envs/test/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /home/builder/miniconda2/envs/test/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: SSL_CTX_set_alpn_protos
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/builder/miniconda2/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_export.py", line 75, in execute
    env = from_environment(name, prefix, no_builds=args.no_builds)
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda_env/env.py", line 38, in from_environment
    main_list.add_pip_installed(prefix, installed, json=True)
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/home/builder/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/home/builder/miniconda2/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/builder/miniconda2/envs/test/bin/python', '/home/builder/miniconda2/envs/test/bin/pip', '-V']' returned non-zero exit status 1
```

This is my system info:

```
(test)[builder@localhost ~]$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.0
     root environment : /home/builder/miniconda2  (writable)
  default environment : /home/builder/miniconda2/envs/test
     envs directories : /home/builder/miniconda2/envs
        package cache : /home/builder/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by jbcrail** [comment]
This was my environment prior to installing `postgresql`, which triggered the downgrade:
```
name: test
dependencies:
- backports_abc=0.4=py27_0
- bokeh=0.11.0=py27_1
- ecdsa=0.13=py27_0
- futures=3.0.3=py27_0
- jinja2=2.8=py27_0
- libgfortran=1.0=0
- markupsafe=0.23=py27_0
- numpy=1.10.2=py27_0
- openblas=0.2.14=3
- openssl=1.0.2e=0
- paramiko=1.15.3=py27_0
- pip=8.0.1=py27_0
- pycrypto=2.6.1=py27_0
- python=2.7.11=0
- python-dateutil=2.4.2=py27_0
- pyyaml=3.11=py27_1
- readline=6.2=2
- redis=2.6.9=0
- requests=2.9.1=py27_0
- setuptools=19.4=py27_0
- singledispatch=3.4.0.3=py27_0
- six=1.10.0=py27_0
- sqlite=3.9.2=0
- ssl_match_hostname=3.4.0.2=py27_0
- tk=8.5.18=0
- tornado=4.3=py27_0
- wheel=0.26.0=py27_1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - backports-abc==0.4
  - backports.ssl-match-hostname==3.4.0.2
  - click==6.2
  - django==1.9.1
  - django-auth-ldap==1.2.7
  - django-rq==0.9.0
  - djangorestframework==3.3.2
  - python-ldap==2.4.25
  - rq==0.5.6

**Comment by tyler-thetyrant** [comment]
Closing outdated.
