### ISSUE TITLE
IOError when installing Pylucene

### ISSUE THREAD

**Issue by cfdollak** [conda/conda#2004]
Below is the traceback:

```
An unexpected error has occurred, please consider sending the                                                           
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/cfdollak/.conda/envs/ir/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/cli/main.py", line 202, in main
    args_func(args, p)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/cli/main.py", line 207, in args_func
    args.func(args, p)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/plan.py", line 502, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/instructions.py", line 140, in execute_instructions
    cmd(state, arg)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/instructions.py", line 84, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/instructions.py", line 80, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/install.py", line 534, in link
    _link(src, dst, lt)
  File "/usr/um/python-2.7/lib/python2.7/site-packages/conda/install.py", line 133, in _link
    shutil.copy2(src, dst)
  File "/usr/um/python-2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/um/python-2.7/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/cfdollak/.conda/envs/.pkgs/ncurses-5.9-5/share/terminfo/a/a210'
(ir)-bash-4.2$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.10.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.6.0
     root environment : /usr/um/python-2.7  (read only)
  default environment : /home/cfdollak/.conda/envs/ir
     envs directories : /home/cfdollak/.conda/envs
                        /home/cfdollak/envs
                        /usr/um/python-2.7/envs
        package cache : /home/cfdollak/.conda/envs/.pkgs
                        /home/cfdollak/envs/.pkgs
                        /usr/um/python-2.7/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
