### ISSUE TITLE
conda fails on conda install jupyter

### ISSUE THREAD

**Issue by kshileev** [conda/conda#2009]
zlib-1.2.8-vc9 100% |###############################| Time: 0:00:00 309.94 kB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  66%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\My\Dev\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main

  File "C:\My\Dev\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\cli\install.py", line 278, in install
    latest = pkgs[-1]
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\plan.py", line 436, in execute_actions
    else:
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\plan.py", line 418, in execute_plan
    if is_root_prefix(prefix):
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\plan.py", line 374, in link

  File "C:\My\Dev\Anaconda\lib\site-packages\conda\install.py", line 486, in link
    t.close()
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\install.py", line 210, in update_prefix
    os.rmdir(path)
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\My\Dev\Anaconda\"Library\bin\pyuic4.bat"'

C:\My\Dev\Anaconda>conda info
Traceback (most recent call last):
  File "C:\My\Dev\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\cli\main.py", line 140, in main
    from conda.cli import main_search
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\cli\main_search.py", line 12, in <module>
    from conda.misc import make_icon_url
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\misc.py", line 19, in <module>
    from conda.api import get_index
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\api.py", line 10, in <module>
    from conda.fetch import fetch_index
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "C:\My\Dev\Anaconda\lib\site-packages\conda\connection.py", line 24, in <module>
    import requests
ImportError: No module named requests

C:\My\Dev\Anaconda>

**Comment by tyler-thetyrant** [comment]
Closing outdated.
