### ISSUE TITLE
Conda files cannot be updated

### ISSUE THREAD

**Issue by MaximUshakov** [conda/conda#2012]
Hello!

I've tried to update conda files by moving to Anaconda\Scripts folder in command line and typing in 
"conda update conda", as these files didn't install properly during installation. Then I've got an error: 

Traceback (most recent call last):
  File "C:\Program Files (x86)\Anaconda\Scripts\conda-script.py", line 4, in <mo
dule>
    sys.exit(main())
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\main.py", li
ne 195, in main
    args_func(args, p)
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\main.py", li
ne 202, in args_func
    args.func(args, p)
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\main_update.
py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\install.py",
 line 333, in install
    update_deps=args.update_deps)
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\plan.py", line 4
37, in install_actions
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\plan.py", line 2
51, in ensure_linked_actions
    extracted_in = extracted_where(dist)
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\plan.py", line 2
39, in extracted_where
    if install.is_extracted(pkgs_dir, dist):
  File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\install.py", lin
e 496, in is_extracted
    return (isfile(join(pkgs_dir, dist, 'info', 'files')) and
  File "C:\Program Files (x86)\Anaconda\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcc in position 7: ordinal
not in range(128)

It seems to me that the problem in russian characters that I use in folders' name. But the problem is I don't know what folder I should rename in order to fix this error. 

I hope you will help me to solve this problem and will maintain russian's OS.

P.S. Sorry for my bad english. I hope I've described the problem clear enough.

**Comment by tyler-thetyrant** [comment]
Unicode is not supported in most environment with the recent version of conda.
