### ISSUE TITLE
Conda installion issues on Mac OSX El Capitan

### ISSUE THREAD

**Issue by amracel** [conda/conda#2018]
Error message:
Traceback (most recent call last):
  File "/usr/local/anaconda_ete/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/conda/fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/local/anaconda_ete/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/anaconda_ete/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(60, 'Operation timed out')", error(60, 'Operation timed out'))

**Comment by msarahan** [comment]
Sorry this issue went unnoticed.  It looks like it was a connection issue - probably a hiccup in your internet connection.  I'm going to close this issue, but please reopen it if you still have problems.
