### ISSUE TITLE
conda update fails (linux)

### ISSUE THREAD

**Issue by rupertnash** [conda/conda#2024]
I just tried to update conda to the latest version and got the following error and request to log an issue here.

```
$ conda update --prefix /home/h018/rnash/anaconda anaconda
Fetching package metadata: ....
Solving package specifications: .An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/h018/rnash/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 336, in install
    minimal_hint=args.alt_hint)
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/home/h018/rnash/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: matplotlib-1.5.0-np110py27_0.tar.bz2 MatchSpec(u'py2cairo')
```

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /home/h018/rnash/anaconda  (writable)
  default environment : /home/h018/rnash/anaconda
     envs directories : /home/h018/rnash/anaconda/envs
        package cache : /home/h018/rnash/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated issue.
