### ISSUE TITLE
Anaconda update: unexpected error linking packages

### ISSUE THREAD

**Issue by gomezriera** [conda/conda#2027]
Hello!

I've tried to update anaconda with the latest conda and I got unexpected linking error message
Hope the info bellow will help!
Thanks 

Current conda install:

```
         platform : osx-64
    conda version : 3.19.1
```

  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/Raul/anaconda3  (writable)
  default environment : /Users/Raul/anaconda3
     envs directories : /Users/Raul/anaconda3/envs
        package cache : /Users/Raul/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Linking packages ...
An unexpected error has occurred, please consider sending the#############################                                            |  60%
following traceback to the conda GitHub issue tracker at:
Traceback (most recent call last):
  File "/Users/Raul/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/Raul/anaconda3/lib/python3.5/site-packages/conda/install.py", line 616, in link
    os.makedirs(dst_dir)
  File "/Users/Raul/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/Raul/anaconda3/lib/python3.5/site-packages/openpyxl/chart'

**Comment by tyler-thetyrant** [comment]
Closing outdated
