### ISSUE TITLE
Windows Conda create environment problem

### ISSUE THREAD

**Issue by drummonds** [conda/conda#2029]
I have been having a problem creating a new environment on a Windows 32 bit install:

```
> conda create -n reportlab anaconda
Fetching package metadata: ....
Solving package specifications: .................................................An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 333, in install
    update_deps=args.update_deps)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 1058, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 855, in solve2
    version_constraints, evaluate_func=evaluate_func)
  File "C:\Anaconda3\lib\site-packages\conda\logic.py", line 510, in bisect_constraints
    constraints = func(*rhs)
  File "C:\Anaconda3\lib\site-packages\conda\resolve.py", line 850, in version_constraints
    return set(generate_constraints(eq, m, [lo, hi], alg=alg))
  File "C:\Anaconda3\lib\site-packages\conda\logic.py", line 488, in generate_constraints
    return C.clauses | additional_clauses
MemoryError

Humphrey@HUM3-PC Z:\IT\2016\2016-02-05 Barcodeprinter
> conda info
Current conda install:

             platform : win-32
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.8.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

I have removed and reinstalled the Anaconda installation `Anaconda3-2.4.1-Windows-x86.exe` a couple of times to no result.

 have just tried:  
`conda create -n reportlab python=3.4 anaconda`
and been successsfull.  So I have a work around.

**Comment by msarahan** [comment]
Looks like you might be running out of memory when trying to solve for dependencies.  Can you tell us about your computer?

Pinging @mcg1969

**Comment by mcg1969** [comment]
Interesting. I do think the latest `conda` fixes will reduce the memory requirements, but I don't think we'll know for sure without trying. @drummonds, if you are willing, you can try out a beta version of `conda` that we're going to be posting soon. I'll update this issue with instructions on how to get it when that happens.

**Comment by MSeifert04** [comment]
I have the same problem but it works if one fixes the python version (``conda create -n test anaconda python=3.5``).

**Comment by kalefranz** [comment]
I haven't seen any instances of this stack trace for any recent versions of conda.  Going to close this issue.  Please file a new ticket if you see the problem in recent versions of conda.
