### ISSUE TITLE
scipy 0.17 broken or leading to error in Windows 32-bit, 64-bit

### ISSUE THREAD

**Issue by connie** [conda/conda#2030]
Please fix scipy 0.17, as it is now installed by default rather than scipy 0.16.

After building my binary which has the scipy dependency using `conda build`, and installing using `conda create` onto a fresh environment, I get the error:

```
[rmg103] C:\Code\RMG-Py\examples\rmg\minimal>python C:\Anaconda\envs\rmg103\Scri
pts\rmg.py input.py
Traceback (most recent call last):
  File "C:\Anaconda\envs\rmg103\Scripts\rmg.py", line 41, in <module>
    from rmgpy.rmg.main import RMG, initializeLog, processProfileStats, makeProf
ileGraph
  File "C:\Anaconda\envs\rmg103\lib\site-packages\rmgpy\rmg\main.py", line 45, i
n <module>
    from rmgpy.constraints import failsSpeciesConstraints
  File "C:\Anaconda\envs\rmg103\lib\site-packages\rmgpy\constraints.py", line 33
, in <module>
    from rmgpy.species import Species
  File "rmgpy\thermo\model.pxd", line 30, in init rmgpy.species (rmgpy\species.c
:17817)
  File "C:\Anaconda\envs\rmg103\lib\site-packages\rmgpy\thermo\__init__.py", lin
e 31, in <module>
    from .thermodata import ThermoData
  File "rmgpy\thermo\nasa.pxd", line 36, in init rmgpy.thermo.thermodata (rmgpy/
thermo\thermodata.c:10245)
  File "rmgpy\thermo\wilhoit.pxd", line 37, in init rmgpy.thermo.nasa (rmgpy/the
rmo\nasa.c:11384)
  File "rmgpy\thermo\wilhoit.pyx", line 36, in init rmgpy.thermo.wilhoit (rmgpy/
thermo\wilhoit.c:15532)
  File "C:\Anaconda\envs\rmg103\lib\site-packages\scipy\linalg\__init__.py", lin
e 174, in <module>
    from .misc import *
  File "C:\Anaconda\envs\rmg103\lib\site-packages\scipy\linalg\misc.py", line 5,
 in <module>
    from .blas import get_blas_funcs
  File "C:\Anaconda\envs\rmg103\lib\site-packages\scipy\linalg\blas.py", line 15
5, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.
```

Downgrading to scipy 0.16 makes everything run smoothly again, so I believe that there is a shared library that isn't properly built in the scipy 0.17 package for windows.  

scipy 0.17 for linux and mac osx works fine.  Please fix it for windows!

**Comment by ilanschnell** [comment]
Is this only a problem when creating a new environment?  Which version of Python do you use?  Are you on 32 or 64-bit?  What is the output from `conda info`?  Thanks.

**Comment by connie** [comment]
It appears to now be working on one of my windows 7 machines after uninstalling anaconda and reinstalling... I shall test on the other systems monday.

**Comment by sdk451** [comment]
I am getting the same error after upgrading to scipy 0.17 as well - Python 3.5 under windows 10

C:\Users\x\Anaconda3\lib\site-packages\pandas\computation\__init__.py:19: UserWarning: The installed version of numexpr 2.4.4 is not supported in pandas and will be not be used

  UserWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".\functions.py", line 4, in <module>
    import statsmodels.api as sm
  File "C:\Users\x\Anaconda3\lib\site-packages\statsmodels\__init__.py", line 8, in <module>
    from .tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
  File "C:\Users\x\Anaconda3\lib\site-packages\statsmodels\tools\__init__.py", line 1, in <module>
    from .tools import add_constant, categorical
  File "C:\Users\x\Anaconda3\lib\site-packages\statsmodels\tools\tools.py", line 8, in <module>
    from scipy.linalg import svdvals
  File "C:\Users\x\Anaconda3\lib\site-packages\scipy\linalg\__init__.py", line 172, in <module>
    from .misc import *
  File "C:\Users\x\Anaconda3\lib\site-packages\scipy\linalg\misc.py", line 5, in <module>
    from .blas import get_blas_funcs
  File "C:\Users\x\Anaconda3\lib\site-packages\scipy\linalg\blas.py", line 155, in <module>
    from scipy.linalg import _fblas
ImportError: DLL load failed: The specified module could not be found.

**Comment by rhr** [comment]
I can confirm this same error on Python 2.7 64-bit on Windows 10.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1686
