### ISSUE TITLE
Spyder-app installation

### ISSUE THREAD

**Issue by dbasusarkar** [conda/conda#2037]
Traceback (most recent call last):
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/Debajyoti/anaconda/lib/python2.7/site-packages/conda/install.py", line 616, in link
    os.makedirs(dst_dir)
  File "/Users/Debajyoti/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/Debajyoti/anaconda/lib/python2.7/site-packages/babel/locale-data'

**Comment by tyler-thetyrant** [comment]
Closing outdated.
