### ISSUE TITLE
Installing python 3.5 environment with anaconda in a version of miniconda that has a lower python version (like 3.4.2) gives an unrelated error message

### ISSUE THREAD

**Issue by eugenschindler** [conda/conda#2054]
Traceback that such an operation yields:

> conda create -n p35 anaconda python=3.5
> Fetching package metadata: ....
> Solving package specifications: .An unexpected error has occurred, please consid
> er sending the
> following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 207, in args_fu
nc
    args.func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main_create.py", line 50, in e
xecute
    install.install(args, parser, 'create')
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 334, in inst
all
    minimal_hint=args.alt_hint)
  File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 377, in install_act
ions
    config.track_features, minimal_hint=minimal_hint):
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Miniconda3\lib\site-packages\conda\resolve.py", line 342, in gen_clau
ses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: qt-4.8.7-vc10_5.tar.bz2 MatchSpec('openssl 1.0.2*')

Obviously the solution is to install a newer version of Miniconda (with python 3.5 or higher), however, the error message doesn't make that clear.
Maybe it's possible to give a more descriptive error message for future instances of this type of user mistake?

**Comment by kalefranz** [comment]
Are you still seeing this with recent versions of conda?  Latest release is 4.3.17.
