### ISSUE TITLE
Problem starting Spyder

### ISSUE THREAD

**Issue by adjgiulio** [conda/conda#2055]
After I updated ipython notebook to Jupyter, Spyder stopped working and wouldn't launch.
I uninstalled anaconda and reinstalled (which retrospectively might have been a mistake since, on a different machine, I was able to fix everything with conda update conda, conda update spyder).
After the reinstall Spyder is still not launching.
If I try conda update conda I get the following:

C:\Users\g>conda update conda
Fetching package metadata: ..
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 192, in instal
l
    for dist in linked]
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 429, in is_linked
    return json.load(fi)
  File "C:\Anaconda\lib\json\__init__.py", line 290, in load
    **kw)
  File "C:\Anaconda\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda\lib\json\decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda\lib\json\decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

C:\Users\us41836>Failed to install app [spyder-app-2.3.8-py27_0.tar.bz2]. Error:
 [ValueError('No JSON object could be decoded',)]

If I launch Spyder I get a pop up: Spyder crashed during last session... try python spyder --reset.

If I try to start Spyder from Launcher I get:

Failed to install app [spyder-app-2.3.8-py27_0.tar.bz2]. Error: [ValueError('No JSON object could be decoded',)]

**Comment by ccordoba12** [comment]
It seems your installation is broken because not even conda works :-)

**Comment by kalefranz** [comment]
Yeah I think something happened with the reinstall.  Can you trash the `C:\Anaconda` directory and try again?  Going to close, but go ahead and file a new ticket if that doesn't fix the problem.  Also, please include the output of `conda info` if you have to file a new ticket.
