### ISSUE TITLE
Crash while running conda upgrade mkl

### ISSUE THREAD

**Issue by hoinzy** [conda/conda#2057]
This is the Stacktrace:

Traceback (most recent call last):
  File "/Users/hoinzy/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/Users/hoinzy/anaconda/lib/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "/Users/hoinzy/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(60, 'Operation timed out')", error(60, 'Operation timed out'))

conda info:

Current conda install:

```
         platform : osx-64
    conda version : 3.19.1
```

  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/hoinzy/anaconda  (writable)
  default environment : /Users/hoinzy/anaconda
     envs directories : /Users/hoinzy/anaconda/envs
        package cache : /Users/hoinzy/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
This is a simple HTTP timeout error, and for a very old version of conda. Closing the issue.
