### ISSUE TITLE
failed noarch-python build

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda/conda#2060]
I"m trying to build a conda package of the pytest-cov package:

https://pypi.python.org/pypi/pytest-cov

using:

```
build:
  noarch_python: True
```

and I get this error:

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/chris.barker/miniconda2/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/chris.barker/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/chris.barker/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/chris.barker/miniconda2/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/chris.barker/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 471, in build
    noarch_python.transform(m, sorted(files2 - files1))
  File "/Users/chris.barker/miniconda2/lib/python2.7/site-packages/conda_build/noarch_python.py", line 87, in transform
    assert 'py_' in m.dist()
AssertionError
```

It works fine if I don't try to do a no-arch build.

recipe here:

https://github.com/NOAA-ORR-ERD/orr-conda-recipes/tree/build_all/pytest-cov

my conda info:

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/chris.barker/miniconda2  (writable)
  default environment : /Users/chris.barker/miniconda2
     envs directories : /Users/chris.barker/miniconda2/envs
        package cache : /Users/chris.barker/miniconda2/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/NOAA-ORR-ERD/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/NOAA-ORR-ERD/noarch/
                        https://conda.anaconda.org/NOAA-ORR-ERD/osx-64/
                        https://conda.anaconda.org/NOAA-ORR-ERD/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/chris.barker/.condarc
    is foreign system : False
```

**Comment by ahmadia** [comment]
This is a standing issue with noarch_python packages, they don't support pinning the Python version.  See: https://github.com/conda/conda-build/issues/542

**Comment by ChrisBarker-NOAA** [comment]
OK, got it -- but you really need to pin python 2 or 3 -- they are getting rarer, but there are no shortage of packages that only support py2 or py3, not both. And there will only be more py3 only packages at some point.

**Comment by ahmadia** [comment]
I know :/

I don't know how hard it would be to provide that functionality, I suspect it's non-trivial but it might be something worth doing if there is enough community demand.

**Comment by ChrisBarker-NOAA** [comment]
Thanks for the quick response -- I got it building with any old python -- should work in this case.

conda/conda-build#542 is covering this, so I'll close this one.
