### ISSUE TITLE
'conda update conda' and 'conda install' failing: traceback ends with LookupError: unknown encoding: idna

### ISSUE THREAD

**Issue by kitchjr** [conda/conda#2063]
`conda updata conda`, `conda install scipy` are failing for me. Same traceback for each.

```
TheVirusBox:~ jameskitcher$ conda --version
conda 3.18.9

TheVirusBox:~ jameskitcher$ conda update conda
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/jameskitcher/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/jameskitcher/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Users/jameskitcher/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/jameskitcher/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/models.py", line 360, in prepare_url
    host = host.encode('idna').decode('utf-8')
LookupError: unknown encoding: idna
```

**Comment by ThomasLecocq** [comment]
what is the version number of ``requests``  ?

**Comment by kitchjr** [comment]
Thanks for taking an interest, Thomas. I appreciate it. As for the requests version... tried looking for it with conda list and conda search requests, but they raise the same error(s) as  I posted above.

Looking at the docs online, it's supposed to be 2.9.1
TheVirusBox:~ jameskitcher$ conda search requests
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/jameskitcher/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main_search.py", line 120, in execute
    execute_search(args, parser)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/main_search.py", line 193, in execute_search
    unknown=args.unknown, json=args.json, offline=args.offline)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/jameskitcher/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Users/jameskitcher/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/jameskitcher/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 454, in request
    prep = self.prepare_request(req)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 388, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/models.py", line 293, in prepare
    self.prepare_url(url, params)
  File "/Users/jameskitcher/anaconda3/lib/python3.5/site-packages/requests/models.py", line 360, in prepare_url
    host = host.encode('idna').decode('utf-8')
LookupError: unknown encoding: idna

**Comment by jakirkham** [comment]
Seems like the best move here simply to reinstall Anaconda3. If absolutely necessary for a temporary fix, you could probably install requests via `pip` or `setup.py` over the existing version to deal with any last minute changes. Then I would strongly recommend reinstalling Anaconda3.

**Comment by kitchjr** [comment]
Thanks for commenting, jakirkham. Yeah, that's what occurred to me too  It
was a fairly fresh installation, so I just reinstalled Anaconda3. I should
have posted that I did that. So, my issue is solved (for now). That said,
is this a wider issue or was the problem between the chair and the
keyboard, so to speak? :)

On Mon, Feb 29, 2016 at 9:47 PM jakirkham <notifications@github.com> wrote:

> Seems like the best move here simply to reinstall Anaconda3. If absolutely
> necessary for a temporary fix, you could probably install requests via pip
> or setup.py over the existing version to deal with any last minute
> changes. Then I would strongly recommend reinstalling Anaconda3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/conda/conda/issues/2063#issuecomment-190554881>.
>
-- 
Warm Regards,

James Kitcher Jr.
916.548.5808

"What you are, comes to you." - Emerson

**Comment by ijstokes** [comment]
@kitchjr something went wrong and unless you know you did something weird Anaconda (or conda) should have been more robust against it.  But that said, it sounds like that Anaconda installation **never** worked properly, so I'd put it down to a failed install.  The error in question:

```
LookupError: unknown encoding: idna
```
seems to be an esoteric issue manifested from missing standard library files.

**Comment by kitchjr** [comment]
Thanks, @ijstokes! Points for use of the word 'esoteric' in this context 👍
