### ISSUE TITLE
Error creating py3k

### ISSUE THREAD

**Issue by paul-herrmann** [conda/conda#2069]
Hello,
We are facing this issue on one of our customers. What can I do to fix this?
I tried reinstalling Anaconda without success..
This has worked so far and is the first time it didn't. Error:

C:\Anaconda\Scripts\conda create -n py3k python=3 a
naconda
Fetching package metadata: ..
Solving package specifications: .An unexpected error has occurred, please consid
er sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func

```
args.func(args, p)
```

  File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 50, in exe
cute
    install.install(args, parser, 'create')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 316, in instal
l
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 400, in install_actio
ns
    config.track_features, minimal_hint=minimal_hint):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 707, in solve
    minimal_hint=minimal_hint)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 459, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 341, in gen_clause
s
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: qt-4.8.7-vc10_5.tar.bz2 MatchSpec(u'openssl 1.0.2*')

**Comment by jakirkham** [comment]
Looks like you may need to update `conda`. I know because I have seen this issue a few times and that seems to be the resolution. Please do so. If that is not the case, please feel free to let us know.

**Comment by tyler-thetyrant** [comment]
Could not replicate the error with the most recent version of conda.
