### ISSUE TITLE
Issue Updating Conda

### ISSUE THREAD

**Issue by JohnRattz** [conda/conda#2072]
Issuing the command "conda update conda" results in the following traceback:

Traceback (most recent call last):
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\instructions.py", line 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\site-packages\conda\install.py", line 482, in extract
    t.extractall(path=path)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\tarfile.py", line 2000, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\tarfile.py", line 2042, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\tarfile.py", line 2112, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\lib\tarfile.py", line 2152, in makefile
    with bltn_open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jratt\\Documents\\Main Documents\\Programming&Engineering\\Programming\\Package Managers\\Conda (Python)\\Anaconda3\\pkgs\\pip-8.0.2-py35_0\\Lib\\site-packages\\pip\\_vendor\\requests\\packages\\urllib3\\packages\\ssl_match_hostname\\__pycache__\\_implementation.cpython-35.pyc'

Here is my installation information:

C:\WINDOWS\system32>conda info
Current conda install:

             platform : win-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 3.5.0.final.0
     requests version : 2.8.1
     root environment : C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3  (writable)
  default environment : C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3
     envs directories : C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\envs
        package cache : C:\Users\jratt\Documents\Main Documents\Programming&Engineering\Programming\Package Managers\Conda (Python)\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by jakirkham** [comment]
Looks like your Anaconda environment may have been corrupted. Could you try uninstall and reinstalling fresh? If you absolutely must get some things done with this environment, you could install conda via standard Python means using a release from this repo so as to make it work temporarily. However, as soon as you have done so please uninstall and reinstall Anaconda. Please let us know if it still reoccurs or you need help with the aforementioned procedure.

**Comment by kalefranz** [comment]
@JohnRattz were you able to fix the issue with an uninstall/reinstall cycle?

**Comment by JohnRattz** [comment]
@kalefranz Yes. After reinstalling, everything works as expected. Thanks.
