### ISSUE TITLE
Conda: Problem upgrading to python-3

### ISSUE THREAD

**Issue by harindra-r** [conda/conda#2076]
Hi,
I get the following exception when attempting to upgrade python 2.7.9. to 3.0:

> python --version
> Python 2.7.9 :: Anaconda 2.2.0 (64-bit)
> 
> conda create -n py3k python=3 anaconda

Solving package specifications: .An unexpected error has occurred, please consid
er sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 202, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 207, in args_func

```
args.func(args, p)
```

  File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 50, in exe
cute
    install.install(args, parser, 'create')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 334, in install
    minimal_hint=args.alt_hint)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 377, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 484, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: qt-4.8.7-vc10_5.tar.bz2 MatchSpec(u'openssl 1.0.2*')

**Comment by jakirkham** [comment]
What version of `conda` are you using? Can it be upgraded? If so, does that fix the issue?

Sorry, I saw a nearly identical issue from someone else earlier that was resolved by upgrading `conda` so instead of iterating many times maybe we can get you up and working the first time. :)

**Comment by tyler-thetyrant** [comment]
Closing since the lack of response.
