### ISSUE TITLE
Windows file permissions issues on conda build's tarball extractall command

### ISSUE THREAD

**Issue by PeterDSteinberg** [conda/conda#2079]
Windows has issues when the running executable / DLL / pyd is modified at runtime.  We have several examples of `conda build .` commands that generate permission denied errors, even when running only in conda build, outside of the anaconda-build/ chalmers CI set up.  

We have seen these permission errors related to:
- _yaml.pyd
- _ctypes.pyd
- python DLLs 
- markupsafe
- possibly others

This session from a win-32 ec2 instance uses tasklist to demonstrate the file lock issues are inherent to conda and/or conda build, not due to zombies left over from other processes, as once speculated:

```
C:\Users\binstar\ProtoCI>tasklist

Image Name                     PID Session Name        Session#    Mem Usage
========================= ======== ================ =========== ============
System Idle Process              0 Services                   0         24 K
System                           4 Services                   0      2,580 K
smss.exe                       452 Services                   0        868 K
csrss.exe                      524 Services                   0      4,972 K
csrss.exe                      568 RDP-Tcp#0                  1      8,844 K
wininit.exe                    576 Services                   0      4,040 K
winlogon.exe                   620 RDP-Tcp#0                  1      4,480 K
services.exe                   652 Services                   0      6,620 K
lsass.exe                      664 Services                   0     10,616 K
lsm.exe                        672 Services                   0      6,044 K
svchost.exe                    840 Services                   0      6,316 K
svchost.exe                    904 Services                   0      6,180 K
svchost.exe                   1004 Services                   0      9,684 K
svchost.exe                   1044 Services                   0      6,408 K
svchost.exe                   1060 Services                   0     35,252 K
SLsvc.exe                     1076 Services                   0     10,516 K
svchost.exe                   1100 Services                   0      7,796 K
svchost.exe                   1180 Services                   0      9,956 K
svchost.exe                   1208 Services                   0     18,100 K
svchost.exe                   1388 Services                   0      8,784 K
taskeng.exe                   1412 Services                   0      5,864 K
spoolsv.exe                   1560 Services                   0      9,168 K
sqlservr.exe                  1716 Services                   0      8,464 K
taskeng.exe                   1768 RDP-Tcp#0                  1      7,168 K
dwm.exe                       1820 RDP-Tcp#0                  1      4,280 K
explorer.exe                  1864 RDP-Tcp#0                  1     23,904 K
svchost.exe                   1852 Services                   0      5,020 K
svchost.exe                   1876 Services                   0      2,892 K
sqlwriter.exe                 1732 Services                   0      7,104 K
svchost.exe                    812 Services                   0      2,324 K
Ec2Config.exe                 1336 Services                   0     32,752 K
XenGuestAgent.exe             2084 Services                   0     32,900 K
TrustedInstaller.exe          2320 Services                   0     13,164 K
svchost.exe                   2336 Services                   0      5,040 K
WmiPrvSE.exe                  2732 Services                   0      6,684 K
WmiPrvSE.exe                  2756 Services                   0     18,368 K
VSSVC.exe                     2948 Services                   0      8,148 K
vds.exe                       3716 Services                   0      7,780 K
svchost.exe                   3876 Services                   0      3,760 K
msdtc.exe                     2312 Services                   0      6,904 K
csrss.exe                     3156 Console                    3      4,748 K
winlogon.exe                  3552 Console                    3      3,888 K
LogonUI.exe                   3920 Console                    3     10,904 K
rdpclip.exe                   4008 RDP-Tcp#0                  1      3,964 K
XenDpriv.exe                  3324 Services                   0     13,828 K
cmd.exe                       3648 RDP-Tcp#0                  1      2,956 K
notepad.exe                   1376 RDP-Tcp#0                  1      3,996 K
csrss.exe                     2040                            2      6,704 K
winlogon.exe                  3220                            2      4,456 K
taskeng.exe                   3436                            2      7,328 K
rdpclip.exe                   2180                            2      3,792 K
dwm.exe                       3516                            2      4,248 K
explorer.exe                  2540                            2     31,900 K
MagicDisc.exe                 1940                            2      5,808 K
notepad.exe                   1088                            2     14,232 K
notepad.exe                   3812                            2      4,048 K
cmd.exe                       1660                            2      2,488 K
tasklist.exe                  4344 RDP-Tcp#0                  1      5,000 K






C:\Users\binstar\ProtoCI>conda build .
Removing old build environment
Removing old work directory
BUILD START: protoci-0.0.32-1
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .......................
The following NEW packages will be INSTALLED:

    colorama:     0.3.6-py27_0
    decorator:    4.0.6-py27_0
    jinja2:       2.8-py27_0
    markupsafe:   0.23-py27_0
    msvc_runtime: 1.0.1-vc9_0   [vc9]
    networkx:     1.11-py27_0
    pip:          8.0.2-py27_0
    psutil:       3.4.2-py27_0
    py:           1.4.31-py27_0
    pycosat:      0.6.1-py27_0
    pytest:       2.8.5-py27_0
    python:       2.7.11-2
    pyyaml:       3.11-py27_2
    requests:     2.9.1-py27_0
    setuptools:   19.6.2-py27_0
    wheel:        0.29.0-py27_0

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\binstar\Miniconda\Scripts\conda-build-script.py", line 4, in <m
odule>
    sys.exit(main())
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 192, in main
    args_func(args, p)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 486, in args_func
    args.func(args, p)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\main_build.py",
 line 409, in execute
    include_recipe=args.include_recipe)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\build.py", line
 399, in build
    [ms.spec for ms in m.ms_depends('build')])
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda_build\build.py", line
 308, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda\plan.py", line 538, i
n execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda\instructions.py", lin
e 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda\instructions.py", lin
e 62, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Users\binstar\Miniconda\lib\site-packages\conda\install.py", line 485
, in extract
    t.extractall(path=path)
  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2072, in extractall
    self.extract(tarinfo, path)
  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2109, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2185, in _extract_membe
r
    self.makefile(tarinfo, targetpath)
  File "C:\Users\binstar\Miniconda\lib\tarfile.py", line 2225, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: u'C:\\Users\\binstar\\Miniconda\\pkgs\\py
yaml-3.11-py27_2\\Lib\\site-packages\\_yaml.pyd'




C:\Users\binstar\ProtoCI>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-32
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.10.final.0
     requests version : 2.9.1
     root environment : C:\Users\binstar\Miniconda  (writable)
  default environment : C:\Users\binstar\Miniconda
     envs directories : C:\Users\binstar\Miniconda\envs
        package cache : C:\Users\binstar\Miniconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\binstar\.condarc
    is foreign system : False

\






C:\Users\binstar\ProtoCI>conda list
# packages in environment at C:\Users\binstar\Miniconda:
#
anaconda-build            0.14.0                    <pip>
anaconda-client           1.2.2                     <pip>
apr                       1.5.2                     vc9_1  [vc9]  defaults
binstar                   0.11.0                    <pip>
binstar-build             0.10.5                    <pip>
clyent                    0.3.4                    py27_0    defaults
conda                     3.19.1                   py27_0    defaults
conda-build               1.19.0                   py27_0    defaults
conda-env                 2.4.5                    py27_0    defaults
funcsigs                  0.4                      py27_0    defaults
jinja2                    2.8                      py27_0    defaults
markupsafe                0.23                     py27_0    defaults
menuinst                  1.3.2                    py27_0    defaults
mock                      1.3.0                    py27_0    defaults
msvc_runtime              1.0.1                     vc9_0  [vc9]  defaults
openssl                   1.0.2f                    vc9_0  [vc9]  defaults
patch                     2.5.9                         1    defaults
pbr                       1.3.0                    py27_0    defaults
pip                       8.0.2                    py27_0    defaults
psutil                    3.4.2                    py27_0    defaults
pycosat                   0.6.1                    py27_0    <unknown>
python                    2.7.10                        5    defaults
python-dateutil           2.4.2                     <pip>
pytz                      2015.4                    <pip>
pywin32                   219                      py27_2    defaults
pyyaml                    3.11                     py27_2    defaults
requests                  2.9.1                    py27_0    defaults
serf                      1.3.8                     vc9_0  [vc9]  defaults
setuptools                19.6.2                   py27_0    defaults
six                       1.10.0                   py27_0    defaults
sqlite                    3.9.2                     vc9_0  [vc9]  defaults
svn                       1.9.3                py27_vc9_0  [vc9]  defaults
unxutils                  14.04.03                      0    tpowell
wheel                     0.29.0                   py27_0    defaults
zlib                      1.2.8                     vc9_2  [vc9]  defaults
```

**Comment by PeterDSteinberg** [comment]
This issue was recently thought to be an anaconda-build issue: [https://github.com/Anaconda-Server/anaconda-build/issues/150](https://github.com/Anaconda-Server/anaconda-build/issues/150)

but the new logs show it is definitely a conda issue independent of the anaconda-build deployment, which is now set to have separate admin and user Miniconda installs.

**Comment by msarahan** [comment]
The markupsafe module in particular is _speedups.pyd

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#830

**Comment by msarahan** [comment]
Sorry, I'm pretty sure that this is a conda issue.  You see it in conda-build because it uses conda, but the inherent issue is that conda is trying to move files that are in use.  That sometimes works on windows, and sometimes not.  The only true fix is to not move files that are in use.  We can either collect a batch or powershell script with the file operations to be performed after conda exits, or we can separate conda into its own install, so that when it runs, it is not changing files that conda itself is using.
