### ISSUE TITLE
setting up Conda env for Numba examples giving error

### ISSUE THREAD

**Issue by streamhsa** [conda/conda#2096]
Include the output of the command 'conda info' in your report.
Current conda install:

             platform : linux-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /root/anaconda2  (writable)
  default environment : /root/anaconda2
     envs directories : /root/anaconda2/envs
        package cache : /root/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Traceback (most recent call last):
  File "/root/anaconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 173, in install
    misc.explicit(specs, prefix)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 68, in explicit
    info = index[fn]
KeyError: 'bokeh-0.11.0dev2-py34_1.tar.bz2'

**Comment by streamhsa** [comment]
After updating Conda using "conda update conda" error is gone however i need "https://conda.anaconda.org/bokeh/label/dev/bokeh-0.11* " which is missing from repos.

**Comment by jakirkham** [comment]
So, there are non-dev releases of bokeh 0.11.*. Would it be possible for you to switch to one of those?

**Comment by kalefranz** [comment]
Looks like the issue has been resolved.
