### ISSUE TITLE
Conda not working after fresh installation on OS X Yosemite

### ISSUE THREAD

**Issue by mick-d** [conda/conda#2099]
I googled it quite a lot but couldn't find the same problem anywhere. I installed conda from the latest stable script (as provided on the official website) but when trying to run `conda list` or `conda info` after installation I got the following error:
```
Traceback (most recent call last):
  File "/Users/XX/miniconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/XX/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 106, in main
    from conda.cli import conda_argparse
  File "/Users/XX/miniconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 17, in <module>
    from conda.cli import common
  File "/Users/XX/miniconda2/lib/python2.7/site-packages/conda/cli/common.py", line 11, in <module>
    import conda.config as config
  File "/Users/XX/miniconda2/lib/python2.7/site-packages/conda/config.py", line 135, in <module>
    rc.get('root_dir', sys.prefix))))
AttributeError: 'list' object has no attribute 'get'
```

**Comment by groutr** [comment]
Can you please post the contents of your `.condarc` file?

**Comment by kalefranz** [comment]
cat ~/.condarc

**Comment by mick-d** [comment]
Thanks a lot for your help! It was indeed the first line of my .condarc (`envs_dirs:`) that was missing. Huge thanks!
