### ISSUE TITLE
An error ocurred while starting the kernel

### ISSUE THREAD

**Issue by jelmelk** [conda/conda#2111]
After performing `conda update --all` one of the items list to update was `path.py`. I pressed `y` to proceed with installation and everything got updated without errors.

Now when I start up Spyder I get the following message in the kernel console:

```
Error in sitecustomize; set PYTHONVERBOSE for traceback:
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
File "C:\Anaconda3\lib\site‑packages\spyderlib\widgets\externalshell\start_ipython_kernel.py", line 183, in 
from IPython.kernel.zmq.kernelapp import IPKernelApp
File "C:\Anaconda3\lib\site‑packages\IPython\__init__.py", line 49, in 
from .terminal.embed import embed
File "C:\Anaconda3\lib\site‑packages\IPython\terminal\embed.py", line 16, in 
from IPython.core.interactiveshell import DummyMod
File "C:\Anaconda3\lib\site‑packages\IPython\core\interactiveshell.py", line 31, in 
from pickleshare import PickleShareDB
File "C:\Anaconda3\lib\site‑packages\pickleshare.py", line 41, in 
from path import path as Path
File "C:\Anaconda3\lib\site‑packages\path.py", line 123, in 
__version__ = pkg_resources.require('path.py')[0].version
TypeError: 'NoneType' object is not callable
```

I'm assuming `path.py` is the issue due to the nature of the error. Does this issue needs to be posted somewhere else, or is this the right place?

**Comment by jelmelk** [comment]
I reinstalled Anaconda as a solution for the time being and it works fine.

**Comment by TurtleDogBird** [comment]
Doe anyone have a better solution than reinstalling Anaconda?
