### ISSUE TITLE
conda update conda

### ISSUE THREAD

**Issue by michaelluang** [conda/conda#2114]
Traceback (most recent call last):
  File "/Users/michael/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 597, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/Users/Michael/anaconda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Users/Michael/anaconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Users/Michael/anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 459, in request
    prep.url, proxies, stream, verify, cert
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 617, in merge_environment_settings
    env_proxies = get_environ_proxies(url) or {}
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/requests/utils.py", line 562, in get_environ_proxies
    if should_bypass_proxies(url):
  File "/Users/Michael/anaconda/lib/python3.5/site-packages/requests/utils.py", line 551, in should_bypass_proxies
    bypass = proxy_bypass(netloc)
  File "/Users/Michael/anaconda/lib/python3.5/urllib/request.py", line 2503, in proxy_bypass
    return proxy_bypass_macosx_sysconf(host)
  File "/Users/Michael/anaconda/lib/python3.5/urllib/request.py", line 2487, in proxy_bypass_macosx_sysconf
    return _proxy_bypass_macosx_sysconf(host, proxy_settings)
  File "/Users/Michael/anaconda/lib/python3.5/urllib/request.py", line 2476, in _proxy_bypass_macosx_sysconf
    elif fnmatch(host, value):
  File "/Users/Michael/anaconda/lib/python3.5/fnmatch.py", line 36, in fnmatch
    return fnmatchcase(name, pat)
  File "/Users/Michael/anaconda/lib/python3.5/fnmatch.py", line 70, in fnmatchcase
    match = _compile_pattern(pat)
KeyError: ('womai.com', <class 'str'>)

**Comment by michaelluang** [comment]
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/Michael/anaconda  (writable)
  default environment : /Users/Michael/anaconda
     envs directories : /Users/Michael/anaconda/envs
        package cache : /Users/Michael/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by jakirkham** [comment]
Normally, when these sorts of issues occur, something bad has happened to the install. I would recommend reinstalling Miniconda/Anaconda. If there is something you badly need from the environment before doing that, you could install conda from source into your root environment and do whatever it is you need to do. Afterwards definitely reinstall fresh.

**Comment by kalefranz** [comment]
@michaelluang please reopen if you're still having the issue after reinstall.
