### ISSUE TITLE
installing ioos packages

### ISSUE THREAD

**Issue by m567tej** [conda/conda#2116]
After downloading "environment.yml" and execute "conda env create environment.yml", and after downloading some packages, execution interrupted  and the following error reported by conda:

Traceback (most recent call last):
  File "/root/anaconda2/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/root/anaconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/root/anaconda2/lib/python2.7/site-packages/conda_env/installers/conda.py", line 17, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/root/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "/root/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/root/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

any help?

**Comment by jakirkham** [comment]
Hmm...is this still occurring?

**Comment by kalefranz** [comment]
I'm guessing this was an intermittent issue with whatever repo @m567tej was using?  I'm going to close for now assuming that it's been resolved.  Can re-open if that's not the case.
