### ISSUE TITLE
Does conda strictly require tarballs to be present?

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#2120]
I am trying to come up with a minimum size system deployment.  I installed all the conda packages I needed, then I deleted all the tarballs, assuming that the un-tarred versions were sufficient for all operations conda might ever want to do.  It seems that may have been a bad assumption, because on a `conda create --clone` operation I got the stack trace below.  Is it true that conda strictly requires tarballs to be present?  If so, why? CC @kalefranz 

```
Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone             
    quiet=quiet, index=index)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/misc.py", line 247, in clone_env
    execute_actions(actions, index=index, verbose=not quiet)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
KeyError: 'anaconda-cluster-1.3.2-py27_1564.tar.bz2'
```

**Comment by ijstokes** [comment]
I've taken another stab at this.  Now, instead of using `rm -Rf /path/to/pkg/tarballs/*.tar.bz2` I was more sensible and used `conda clean --tarballs`.  But it looks like that might have more-or-less had the same effect, because it seems like I can't use `--clone` from this env either.

**Comment by kalefranz** [comment]
I think clone requires the tarballs from the package cache right now, yeah

**Comment by ijstokes** [comment]
@kalefranz Thanks for the feedback.  A few clarifying questions:

1. Why does it need them?

2. Should it need them?

3. Does this mean (as I think I have observed) that `conda clean --tarballs` will break `conda create --clone` in a way that should at the very least be handled more elegantly than returning a stack trace to the user?  Or are my `conda create --clone` problems coming from elsewhere?

**Comment by kalefranz** [comment]
> Why does it need them?

The package cache is itself a conda repo.  By definition, a conda repo is a `repodata.json` file along with accompanying tarballs.

> Should it need them?

Perhaps not. But it would take a lot of careful engineering work to get all the behavior to be correct without them.

> Does this mean (as I think I have observed) that conda clean --tarballs will break conda create --clone in a way that should at the very least be handled more elegantly than returning a stack trace to the user? 

Yes, after `conda clean`, the user shouldn't expect to be able to use any "offline" behavior.  However, I think "offline behavior" has now actually been conflated with `--clone`.  We should obviously have more elegant messaging.  But I also think that the deeper issue is that our implementation of `--clone` is incorrect.

I'm going to close this issue for now. But I'll let my brain background process the `--clone` issue.
