### ISSUE TITLE
imp.find_module does not find setuptools installed with conda

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#2129]
The built-in ``imp.find_module`` function works fine for most packages installed with conda, but not for ``setuptools``. However, if I install ``setuptools`` with pip, it works fine:

```python
$ conda install setuptools
Fetching package metadata: ......
Solving package specifications: ...........
Package plan for installation in environment /Users/tom/miniconda3/envs/tmp-plain:

The following packages will be UPDATED:

    setuptools: 19.6.2-py35_0 --> 20.1.1-py35_0

Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
$ python -c 'import imp; imp.find_module("setuptools")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/tmp-plain/lib/python3.5/imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'setuptools'
$ conda remove setuptools
Fetching package metadata: ......

Package plan for package removal in environment /Users/tom/miniconda3/envs/tmp-plain:

The following packages will be REMOVED:

    setuptools: 20.1.1-py35_0

Unlinking packages ...
[      COMPLETE      ]|###########################################################################################################| 100%
$ pip install setuptools
Collecting setuptools
  Downloading setuptools-20.1.1-py2.py3-none-any.whl (472kB)
    100% |████████████████████████████████| 475kB 543kB/s 
Installing collected packages: setuptools
Successfully installed setuptools-20.1.1
$ python -c 'import imp; imp.find_module("setuptools")'
$
```

This also occurs with ``pkg_resources`` (also installed by ``setuptools``).

This is an issue because ``py2app`` makes use of ``find_module``, and I'm trying to make an app that has imports to the ``pkg_resources`` module, but ``py2app`` crashes unless I install setuptools with pip.

**Comment by jakirkham** [comment]
Able to reproduce as well. Was able to get this to work correctly on non-conda installs of Python 2 and 3.

**Comment by kalefranz** [comment]
Pretty sure this is a packaging issue with setuptools.  @ilanschnell is going to love this one.  Going to move to anaconda-issues.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#693
