### ISSUE TITLE
cx_oracle install kills ipykernel in Conda

### ISSUE THREAD

**Issue by zoltan-fedor** [conda/conda#2139]
Installed Anaconda 2.4.1 and loaded it from Jupyterhub with no problem:

```
{
 "display_name": "onda",
 "language": "python",
 "argv": [
  "/apps/bin/anaconda/anaconda2/bin/python2",
  "-m",
  "ipykernel",
  "-f",
  "{connection_file}"
 ]
```

The kernel did start properly.

Then I went and install the cx_oracle package:
`/apps/bin/anaconda/anaconda2/bin/conda install cx_oracle`

```
Fetching package metadata: ....
Solving package specifications: ...............
Package plan for installation in environment /apps/bin/anaconda/anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2f             |                0         3.2 MB  defaults
    oracle-instantclient-11.2.0.4.0|                0        54.0 MB  defaults
    sqlite-3.9.2               |                0         3.9 MB  defaults
    cx_oracle-5.1.2            |           py27_0         151 KB  defaults
    requests-2.9.1             |           py27_0         605 KB  defaults
    setuptools-20.1.1          |           py27_0         368 KB  defaults
    wheel-0.29.0               |           py27_0          81 KB  defaults
    conda-3.19.3               |           py27_0         178 KB  defaults
    pip-8.0.3                  |           py27_0         1.5 MB  defaults
    ------------------------------------------------------------
                                           Total:        63.9 MB

The following NEW packages will be INSTALLED:

    cx_oracle:            5.1.2-py27_0  defaults
    oracle-instantclient: 11.2.0.4.0-0  defaults

The following packages will be UPDATED:

    conda:                3.18.8-py27_0 defaults --> 3.19.3-py27_0 defaults
    openssl:              1.0.2d-0      defaults --> 1.0.2f-0      defaults
    pip:                  7.1.2-py27_0  defaults --> 8.0.3-py27_0  defaults
    requests:             2.8.1-py27_0  defaults --> 2.9.1-py27_0  defaults
    setuptools:           18.5-py27_0   defaults --> 20.1.1-py27_0 defaults
    sqlite:               3.8.4.1-1     defaults --> 3.9.2-0       defaults
    wheel:                0.26.0-py27_1 defaults --> 0.29.0-py27_0 defaults

Proceed ([y]/n)? y

Fetching packages ...
openssl-1.0.2f 100% |######################################################################################################################| Time: 0:00:00   5.49 MB/s
oracle-instant 100% |######################################################################################################################| Time: 0:00:01  29.81 MB/s
sqlite-3.9.2-0 100% |######################################################################################################################| Time: 0:00:00   6.51 MB/s
cx_oracle-5.1. 100% |######################################################################################################################| Time: 0:00:00 736.35 kB/s
requests-2.9.1 100% |######################################################################################################################| Time: 0:00:00   1.45 MB/s
setuptools-20. 100% |######################################################################################################################| Time: 0:00:00   1.20 MB/s
wheel-0.29.0-p 100% |######################################################################################################################| Time: 0:00:00 635.13 kB/s
conda-3.19.3-p 100% |######################################################################################################################| Time: 0:00:00 737.71 kB/s
pip-8.0.3-py27 100% |######################################################################################################################| Time: 0:00:00   3.12 MB/s
Extracting packages ...
[      COMPLETE      ]|#########################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#########################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#########################################################################################################################################| 100%
```

Now the Jupyterhub kernel doesn't start anymore:
```
[I 2016-02-26 18:39:12.062 zoltan.fedor restarter:103] KernelRestarter: restarting kernel (4/5)
WARNING:root:kernel 06de710c-9bf6-42ef-977b-b127616f1a11 restarted
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/apps/bin/anaconda/anaconda2/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
/apps/bin/anaconda/anaconda2/bin/python2: cannot import name md5; 'ipykernel' is a package and cannot be directly executed
```

**Comment by kalefranz** [comment]
Definitely not an issue with conda itself, so going to move to anaconda-issues.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#692
