### ISSUE TITLE
stack trace on bad version string

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2140]
```
    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/binstar/miniconda2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 407, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 351, in add_defaults_to_specs
    for spec in specs
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 352, in <genexpr>
    for fn in r.get_max_dists(MatchSpec(spec))
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 563, in get_max_dists
    pkgs = self.get_pkgs(ms, max_only=True)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 544, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 516, in find_matches
    if self.filter_[fn] and ms.match(fn):
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 325, in match
    return any(vs.match(version) for vs in self.vspecs)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 325, in <genexpr>
    return any(vs.match(version) for vs in self.vspecs)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 301, in match
    return all(c.match(version) for c in self.constraints)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 301, in <genexpr>
    return all(c.match(version) for c in self.constraints)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 292, in match
    return ver_eval(version, self.spec)
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 271, in ver_eval
    return eval('VersionOrder("%s") %s VersionOrder("%s")' % (a, op, b))
  File "<string>", line 1, in <module>
  File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 151, in __init__
    raise ValueError(message + "invalid character(s).")
ValueError: Malformed version string '2.16.5==67': invalid character(s).
```

**Comment by groutr** [comment]
Are there any steps to reproduce this?

**Comment by kalefranz** [comment]
What was the package you were installing?

**Comment by bkreider** [comment]
Is this fixed now?

**Comment by mcg1969** [comment]
Just saw this. Can you give us a command to reproduce this? I'll re-open if it's not fixed in the master

**Comment by mcg1969** [comment]
The bug here is that malformed user input should not result in a crash that tells the user to submit an issue to GitHub!

**Comment by mcg1969** [comment]
Version specs need to be fully parsed before they ever get to the solver.

**Comment by bkreider** [comment]
Here is an example on conda 4.0.0:
`conda install blah==10==5`

**Comment by mcg1969** [comment]
Excellent. I think this is actually a fix for `common`. The code that parses command-line arguments needs to fully parse package specs and exit gracefully if they are not valid.

**Comment by kalefranz** [comment]
Looks to be fixed.

```
kfranz@0283:~/continuum/conda *4.3.x ❯ python -m conda install blah==10==5 --dry-run

CondaValueError: invalid package specification: blah==10==5
```

**Comment by jolespin** [comment]
Has anyone figured this out? I keep getting the error for no matter what I try to install. 

```
-bash-4.1$ conda install -c bioconda pysam
Solving environment: failed
CondaValueError: Malformed version string '~': invalid character(s).
```
