### ISSUE TITLE
conda update failed

### ISSUE THREAD

**Issue by thertz** [conda/conda#2147]
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 194, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 337, in install
    minimal_hint=args.alt_hint)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 402, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 738, in solve
    minimal_hint=minimal_hint)
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 483, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "C:\Anaconda\lib\site-packages\conda\resolve.py", line 341, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: qt-4.8.7-vc10_5.tar.bz2 MatchSpec(u'openssl 1.0.2*')

Current conda install:

             platform : win-64
        conda version : 3.16.0
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.7.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by jakirkham** [comment]
Looks like you have a pretty old version of `conda` could you please try updating it and repeating?

**Comment by kalefranz** [comment]
Yes, please run `conda update conda`, and open a new issue if the problem persists.

**Comment by thertz** [comment]
FYI, this did not solve the issue. I had to reinstall anaconda. Overall, the process of upgrading versions is far from smooth, primarily on windows machines. It was somewhat easier on my mac.

Thanks,
—Tomer

**Comment by kalefranz** [comment]
... Someday, when Windows has a posix-compliant file system, and pigs fly...

Thanks for the feedback though :)
