### ISSUE TITLE
conda blpapi install fail

### ISSUE THREAD

**Issue by zhorozhoro** [conda/conda#2149]
Hello, I was trying to install the Bloomberg API library for Python using 

conda install -c https://conda.anaconda.org/mbonix blpapi

and received the traceback below.  Does anyone know what the issue is?  I am running Anaconda Python 3.5.1.  Thanks!

Traceback (most recent call last):
  File "C:\..\..\Anaconda\Scripts\conda-script.py", line 4, in <module>
  File "C:\..\..\Anaconda\lib\site-packages\conda\cli\main.py", line 173, in main
  File "C:\..\..\Anaconda\lib\site-packages\conda\cli\main.py", line 180, in args_func
  File "C:\..\..\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
  File "C:\..\..\Anaconda\lib\site-packages\conda\cli\install.py", line 423, in install
  File "C:\..\..\Anaconda\lib\site-packages\conda\plan.py", line 538, in execute_actions
  File "C:\..\..\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\..\..\Anaconda\lib\site-packages\conda\instructions.py", line 91, in LINK_CMD
  File "C:\..\..\Anaconda\lib\site-packages\conda\instructions.py", line 87, in link
  File "C:\..\..\Anaconda\lib\site-packages\conda\install.py", line 616, in link
  File "C:\..\..\Anaconda\lib\os.py", line 241, in makedirs
PermissionError: [WinError 5] Access is denied: 'C:\\..\\..\\Anaconda\\Doc'

**Comment by kalefranz** [comment]
Definitely a problem with the original package provided by mbonix on anaconda.org.
