### ISSUE TITLE
Cannot create environment on Windows 7 x64

### ISSUE THREAD

**Issue by pbowyer** [conda/conda#2152]
This is similar to #1936 but isn't resolved by #2083. I'm trying to create an environment - the 'root' install is working great:

```
$ conda create --name hotbar --file environment_win64.yml
Fetching: https://repo.continuum.io/pkgs/free/win-64/affine-1.2.0-py27_0.tar.bz2
Fetching package metadata: .
Fetching: https://repo.continuum.io/pkgs/free/win-64/bokeh-0.11.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/boto-2.39.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/click-6.3-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/cligj-0.2.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/curl-7.45.0-vc9_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/cycler-0.9.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/cython-0.23.4-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/enum34-1.1.2-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/flask-0.10.1-py27_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/futures-3.0.3-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/gdal-2.0.0-py27_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/geos-3.4.2-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/h5py-2.5.0-np110py27_4.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/hdf4-4.2.11-0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/hdf5-1.8.15.1-vc9_4.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ipykernel-4.2.2-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ipython-4.0.3-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ipython-notebook-4.0.4-py27_3.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ipython-qtconsole-4.0.1-py27_4.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ipython_genutils-0.1.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ipywidgets-4.1.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jedi-0.9.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jinja2-2.8-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jpeg-8d-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jupyter-1.0.0-py27_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jupyter_client-4.1.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jupyter_console-4.1.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/jupyter_core-4.0.6-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/kealib-1.4.5-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/krb5-1.13.2-0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/libgdal-2.0.0-vc9_2.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/libnetcdf-4.3.3.1-vc9_5.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/libpng-1.6.17-vc9_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/libsodium-1.0.3-0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/libtiff-4.0.6-vc9_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/llvmlite-0.8.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/lxml-3.5.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/markupsafe-0.23-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/matplotlib-1.5.1-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/mkl-11.3.1-0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/mkl-service-1.1.2-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/msvc_runtime-1.0.1-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/nbconvert-4.1.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/nbformat-4.0.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/nose-1.3.7-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/notebook-4.1.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/numba-0.23.1-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/numexpr-2.4.6-np110py27_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/numpy-1.10.4-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/odo-0.4.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pandas-0.17.1-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/path.py-8.1.2-py27_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/patsy-0.4.0-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pep8-1.7.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pip-8.0.2-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/proj4-4.9.1-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/py-1.4.31-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pyasn1-0.1.9-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pyparsing-2.0.3-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pyqt-4.11.4-py27_5.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pyreadline-2.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pytest-2.8.5-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/python-2.7.11-2.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/python-dateutil-2.4.2-py27_0.tar.bz2
Fetching: https://conda.anaconda.org/robintw/win-64/python-fmask-0.2.1-py27_1.tar.bz2
Fetching package metadata: .
Fetching: https://repo.continuum.io/pkgs/free/win-64/pytz-2015.7-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/pyzmq-15.2.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/qt-4.8.7-vc9_6.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/qtconsole-4.1.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/rasterio-0.25.0-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/requests-2.9.1-py27_0.tar.bz2
Fetching: https://conda.anaconda.org/robintw/win-64/rios-1.4.2-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/scikit-image-0.11.3-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/scikit-learn-0.17-np110py27_2.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/scipy-0.17.0-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/setuptools-20.1.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/sip-4.16.9-py27_2.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/six-1.10.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/snuggs-1.3.1-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/sockjs-tornado-1.0.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/ssl_match_hostname-3.4.0.2-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/statsmodels-0.6.1-np110py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/sympy-0.7.6.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/tk-8.5.18-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/tornado-4.3-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/traitlets-4.1.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/unicodecsv-0.14.1-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/werkzeug-0.11.3-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/wheel-0.29.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/xerces-c-3.1.2-vc9_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/xlrd-0.9.4-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/xlsxwriter-0.8.4-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/xlwings-0.6.4-py27_1.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/xlwt-1.0.0-py27_0.tar.bz2
Fetching: https://repo.continuum.io/pkgs/free/win-64/zlib-1.2.8-vc9_2.tar.bz2
[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
An unexpected error has occurred, please consider sending the            |  65%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 180, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 173, in install
    misc.explicit(specs, prefix)
  File "C:\Anaconda2\lib\site-packages\conda\misc.py", line 92, in explicit
    force_extract_and_link(dists, prefix, verbose=verbose)
  File "C:\Anaconda2\lib\site-packages\conda\misc.py", line 55, in force_extract_and_link
    execute_actions(actions, verbose=verbose)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 63, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Anaconda2\lib\tarfile.py", line 2078, in extractall
    self.extract(tarinfo, path)
  File "C:\Anaconda2\lib\tarfile.py", line 2115, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Anaconda2\lib\tarfile.py", line 2191, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Anaconda2\lib\tarfile.py", line 2231, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 13] Permission denied: 'C:\\Anaconda2\\pkgs\\python-2.7.11-2\\DLLs\\_ctypes.pyd'
```

The environment fails to create:

```
λ conda info --envs
Using Anaconda Cloud api site https://api.anaconda.org
# conda environments:
#
root                  *  C:\Anaconda2
```

And this is my conda install:

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 3.19.3
  conda-build version : 1.18.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Is there any current work-around? The system is Windows 7 Professional.

Annoyingly, it works great for a friend on Windows 10. One difference we found is the Python version string. Mine, on Windows 7:

```
λ python --version
Python 2.7.11 :: Anaconda 2.5.0 (64-bit)
```

His on Windows 10:

```
Python 2.7.11 :: Continuum Analytics, Inc.
```

He installed the Python 3 version of Anaconda first and then Python 2 within it; I downloaded Python2 version directly.

**Comment by msarahan** [comment]
This is an issue that we're working on right now.  The crux of it is that packages are linked, not copied, to be more efficient about space.  Because we didn't have links done quite right (they're very unusual on Windows), this kind of error pops up, because Windows basically tries to replace a file that is in use.

The only workarounds right now are to either artificially force an older python version, then update to the newer one in your environment file:

    conda install python=2.7.10

or, as your friend discovered, have a Python 3 root env.

We think this is fixed in https://github.com/conda/conda/pull/1944, but this has yet to be included in a release.

**Comment by insertinterestingnamehere** [comment]
This looks a lot more like the issue we fixed in https://github.com/conda/conda/pull/2083. If you already tried this before upgrading to the latest version of conda it would have left your main Python install in an inconsistent state. If that's the case, the latest conda release should work fine once you fix the Python install. In order to restore the default Python installation you'll have to downgrade to 2.7.10 and then upgrade back to 2.7.11, but it should all work fine after that.

**Comment by bastula** [comment]
Same kind of issue that works with Python 2.7 but not 3.5. At a loss, as this used to work on my miniconda3 environment but not anymore:

```
conda create -n qatrack python=3.5
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ...........

Package plan for installation in environment C:\Miniconda3\envs\qatrack:

The following NEW packages will be INSTALLED:

    msvc_runtime: 1.0.1-vc14_0  [vc14]
    pip:          8.1.0-py35_0
    python:       3.5.1-2
    setuptools:   20.2.2-py35_0
    wheel:        0.29.0-py35_0

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 63, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 485, in extract
    t.extractall(path=path)
  File "C:\Miniconda3\lib\tarfile.py", line 2000, in extractall
    numeric_owner=numeric_owner)
  File "C:\Miniconda3\lib\tarfile.py", line 2042, in extract
    numeric_owner=numeric_owner)
  File "C:\Miniconda3\lib\tarfile.py", line 2112, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Miniconda3\lib\tarfile.py", line 2152, in makefile
    with bltn_open(targetpath, "wb") as target:
PermissionError: [Errno 13] Permission denied: 'C:\\Miniconda3\\pkgs\\python-3.5.1-2\\DLLs\\_bz2.pyd'
```

Conda info:
```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.1
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Miniconda3  (writable)
  default environment : C:\Miniconda3
     envs directories : C:\Miniconda3\envs
        package cache : C:\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
