### ISSUE TITLE
Progress Bar: underlying buffer has been detached

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#2157]
In some cases where there is not an interactive TTY, I can get this issue with the progress bar when running `python setup.py bdist_conda`. This only occurs with Python 3 not with Python 2.

```
running bdist_conda
Removing old build environment
Removing old work directory
BUILD START: nanshe-0.1.0a48+19.gd13a23b-py35_0
Fetching package metadata: ........
Solving package specifications: ................................................................./opt/conda3/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'build_requires'
  warnings.warn(msg)
Using Anaconda Cloud api site https://api.anaconda.org

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    fftw-3.3.4                 |                0         3.5 MB  nanshe
    icu-54.1                   |                0        11.3 MB  defaults
    jbig-2.1                   |                0          29 KB  defaults
    jpeg-8d                    |                0         699 KB  defaults
    libgcc-4.8.5               |                1         922 KB  defaults
    libpng-1.6.17              |                0         214 KB  defaults
    nomkl-1.0                  |                0          402 B  defaults
    freetype-2.5.5             |                0         2.2 MB  defaults
    hdf5-1.8.15.1              |                2         1.9 MB  defaults
    libtiff-4.0.6              |                1         1.5 MB  defaults
    libxml2-2.9.2              |                0         4.2 MB  defaults
    openblas-0.2.15            |        nomkl_103        14.9 MB  nanshe
    boost-1.60.0               |           py35_0         9.8 MB  nanshe
    decorator-4.0.9            |           py35_0           7 KB  defaults
    fontconfig-2.11.1          |                5         402 KB  defaults
    nose-1.3.7                 |           py35_0         194 KB  defaults
    numpy-1.10.4               |py35_nomkl_openblas_107         6.5 MB  nanshe
    pillow-3.1.1               |           py35_0         812 KB  defaults
    psutil-4.0.0               |           py35_0         204 KB  defaults
    pyparsing-2.0.3            |           py35_0          66 KB  defaults
    sip-4.16.9                 |           py35_0         222 KB  defaults
    bottleneck-1.0.0           |      np110py35_0         598 KB  defaults
    cycler-0.10.0              |           py35_0          11 KB  defaults
    h5py-2.6.0                 |           py35_0         2.9 MB  nanshe
    mahotas-1.4.0              |           py35_0         4.1 MB  nanshe
    networkx-1.11              |           py35_0         1.1 MB  defaults
    pyfftw-0.9.2               |           py35_2         222 KB  nanshe
    qt-4.8.7                   |                1        36.4 MB  defaults
    rank_filter-0.4.7          |           nppy35         465 KB  nanshe
    scipy-0.17.0               |py35_nomkl_openblas_103        30.6 MB  nanshe
    vigra-1.11.0dev0           |           py35_0         7.2 MB  nanshe
    pyqt-4.11.4                |           py35_1         3.5 MB  defaults
    scikit-learn-0.17.1        |py35_nomkl_openblas_103         9.2 MB  nanshe
    matplotlib-1.5.1           |      np110py35_0         8.4 MB  defaults
    scikit-image-0.11.3        |      np110py35_0        24.3 MB  defaults
    ------------------------------------------------------------
                                           Total:       188.4 MB

The following NEW packages will be INSTALLED:

    boost:           1.60.0-py35_0                  nanshe  
    bottleneck:      1.0.0-np110py35_0              defaults
    cycler:          0.10.0-py35_0                  defaults
    decorator:       4.0.9-py35_0                   defaults
    fftw:            3.3.4-0                        nanshe  
    fontconfig:      2.11.1-5                       defaults
    freetype:        2.5.5-0                        defaults
    h5py:            2.6.0-py35_0                   nanshe  
    hdf5:            1.8.15.1-2                     defaults
    icu:             54.1-0                         defaults
    jbig:            2.1-0                          defaults
    jpeg:            8d-0                           defaults
    libgcc:          4.8.5-1                        defaults
    libpng:          1.6.17-0                       defaults
    libtiff:         4.0.6-1                        defaults
    libxml2:         2.9.2-0                        defaults
    mahotas:         1.4.0-py35_0                   nanshe  
    matplotlib:      1.5.1-np110py35_0              defaults
    networkx:        1.11-py35_0                    defaults
    nomkl:           1.0-0                          defaults
    nose:            1.3.7-py35_0                   defaults
    numpy:           1.10.4-py35_nomkl_openblas_107 nanshe   [nomkl openblas]
    openblas:        0.2.15-nomkl_103               nanshe   [nomkl         ]
    openssl:         1.0.2g-0                       defaults
    pillow:          3.1.1-py35_0                   defaults
    pip:             8.0.3-py35_0                   defaults
    psutil:          4.0.0-py35_0                   defaults
    pyfftw:          0.9.2-py35_2                   nanshe  
    pyparsing:       2.0.3-py35_0                   defaults
    pyqt:            4.11.4-py35_1                  defaults
    python:          3.5.1-0                        defaults
    python-dateutil: 2.4.2-py35_0                   defaults
    pytz:            2015.7-py35_0                  defaults
    qt:              4.8.7-1                        defaults
    rank_filter:     0.4.7-nppy35                   nanshe  
    readline:        6.2-2                          defaults
    scikit-image:    0.11.3-np110py35_0             defaults
    scikit-learn:    0.17.1-py35_nomkl_openblas_103 nanshe   [nomkl openblas]
    scipy:           0.17.0-py35_nomkl_openblas_103 nanshe   [nomkl openblas]
    setuptools:      20.1.1-py35_0                  defaults
    sip:             4.16.9-py35_0                  defaults
    six:             1.10.0-py35_0                  defaults
    sqlite:          3.9.2-0                        defaults
    tk:              8.5.18-0                       defaults
    vigra:           1.11.0dev0-py35_0              nanshe  
    wheel:           0.29.0-py35_0                  defaults
    xz:              5.0.5-1                        defaults
    zlib:            1.2.8-0                        defaults

Fetching packages ...
Traceback (most recent call last):
  File "setup.py", line 181, in <module>
    conda_command_tests=False
  File "/opt/conda3/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/conda3/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/conda3/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/conda3/lib/python3.5/distutils/command/bdist_conda.py", line 253, in run
    build.build(m, post=False)
  File "/opt/conda3/lib/python3.5/site-packages/conda_build/build.py", line 399, in build
    [ms.spec for ms in m.ms_depends('build')])
  File "/opt/conda3/lib/python3.5/site-packages/conda_build/build.py", line 308, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "/opt/conda3/lib/python3.5/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/conda3/lib/python3.5/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/opt/conda3/lib/python3.5/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/opt/conda3/lib/python3.5/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/opt/conda3/lib/python3.5/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/opt/conda3/lib/python3.5/site-packages/conda/fetch.py", line 366, in download
    getLogger('fetch.start').info((fn[:14], size))
  File "/opt/conda3/lib/python3.5/logging/__init__.py", line 1279, in info
    self._log(INFO, msg, args, **kwargs)
  File "/opt/conda3/lib/python3.5/logging/__init__.py", line 1415, in _log
    self.handle(record)
  File "/opt/conda3/lib/python3.5/logging/__init__.py", line 1425, in handle
    self.callHandlers(record)
  File "/opt/conda3/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
    hdlr.handle(record)
  File "/opt/conda3/lib/python3.5/logging/__init__.py", line 855, in handle
    self.emit(record)
  File "/opt/conda3/lib/python3.5/site-packages/conda/console.py", line 27, in emit
    fetch_progress.start()
  File "/opt/conda3/lib/python3.5/site-packages/conda/progressbar/__init__.py", line 311, in start
    self.update(0)
  File "/opt/conda3/lib/python3.5/site-packages/conda/progressbar/__init__.py", line 283, in update
    self.fd.write(self._format_line() + '\r')
ValueError: underlying buffer has been detached
```

**Comment by kalefranz** [comment]
@jakirkham Are you still seeing this? Or can this issue be closed?

**Comment by kalefranz** [comment]
Closing as fixed.  If not, let's reopen.
