### ISSUE TITLE
Can not clone

### ISSUE THREAD

**Issue by vascoosx** [conda/conda#2160]
weird bug.

```
$ conda create -n orange --clone hightech
Fetching package metadata: ....
src_prefix: 'C:\\Users\\username\\AppData\\Local\\Continuum\\Anaconda\\envs\\hightech'
dst_prefix: 'C:\\Users\\username\\AppData\\Local\\Continuum\\Anaconda\\envs\\orange'
Packages: 149
Files: 1
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 9, in <module>
    load_entry_point('conda===3.19.1-194-g2d6a70d', 'console_scripts', 'conda')()
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\install.py", line 84, in clone
    quiet=quiet, index=index)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\misc.py", line 243, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\resolve.py", line 698, in dependency_sort
    for key, value in iteritems(must_have):
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\compat.py", line 157, in iteritems
    return iter(getattr(d, _iteritems)())
AttributeError: 'list' object has no attribute 'iteritems'
```

version information
```

$ conda info
Current conda install:

             platform : win-64
        conda version : 3.19.1_194_g2d6a70d-py2.7.egg
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\username\AppData\Local\Continuum\Anaconda  (writable)
  default environment : C:\Users\username\AppData\Local\Continuum\Anaconda
     envs directories : C:\Users\username\AppData\Local\Continuum\Anaconda\envs
        package cache : C:\Users\username\AppData\Local\Continuum\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False


```

**Comment by davidslac** [comment]
I just came here to report the same bug. I made a fresh install of miniconda, added the conda channel, did --update all to get to the beta version, and then cloned the root environment and got similar output:
```
src_prefix: '/reg/g/psdm/sw/condadev/external/miniconda2'
dst_prefix: '/reg/g/psdm/sw/condadev/external/miniconda2/envs/ana-0.17.19'
Packages: 15
Files: 0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/misc.py", line 243, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 688, in dependency_sort
    for key, value in iteritems(must_have):
  File "/reg/g/psdm/sw/condadev/external/miniconda2/lib/python2.7/site-packages/conda/compat.py", line 157, in iteritems
    return iter(getattr(d, _iteritems)())
AttributeError: 'list' object has no attribute 'iteritems'

```

**Comment by kalefranz** [comment]
@davidslac Can you provide your full `conda info`?

**Comment by kalefranz** [comment]
@vascoosx `3.19.1_194_g2d6a70d` isn't the latest version of conda.  And you don't have the conda channel listed in your channels.  Conda will always update itself to the latest known version, which is why you have to add the conda channel.

    conda config --add channels conda
    conda update conda

Version should be `3.19.3.dev214+g57e4dd8` for the latest beta.

**Comment by davidslac** [comment]
Hi Kale,

Here is output after installing miniconda, and then updating the channel, trying to clone, and finally the conda info output:

-bash-4.2$ cd /reg/g/psdm/sw/condadev/external/minconda2beta     
-bash-4.2$ bin/conda config --add channels conda
-bash-4.2$ bin/conda update --all
Fetching package metadata: ......
Solving package specifications: .........................
Package plan for installation in environment /reg/g/psdm/sw/condadev/external/minconda2beta:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2g             |                0         3.2 MB
    sqlite-3.9.2               |                0         3.9 MB
    requests-2.9.1             |           py27_0         605 KB
    setuptools-20.1.1          |           py27_0         368 KB
    wheel-0.29.0               |           py27_0          81 KB
    conda-3.19.3.214.g57e4dd8  |           py27_0         191 KB
    pip-8.0.3                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:         9.8 MB

The following packages will be UPDATED:

    conda:      3.19.0-py27_0 --> 3.19.3.214.g57e4dd8-py27_0
    openssl:    1.0.2d-0      --> 1.0.2g-0                  
    pip:        7.1.2-py27_0  --> 8.0.3-py27_0              
    requests:   2.9.0-py27_0  --> 2.9.1-py27_0              
    setuptools: 18.8.1-py27_0 --> 20.1.1-py27_0             
    sqlite:     3.8.4.1-1     --> 3.9.2-0                   
    wheel:      0.26.0-py27_1 --> 0.29.0-py27_0             

Proceed ([y]/n)? y

Fetching packages ...
openssl-1.0.2g 100% |#############################################################################################################################################| Time: 0:00:01   2.30 MB/s
sqlite-3.9.2-0 100% |#############################################################################################################################################| Time: 0:00:01   2.42 MB/s
requests-2.9.1 100% |#############################################################################################################################################| Time: 0:00:00 760.13 kB/s
setuptools-20. 100% |#############################################################################################################################################| Time: 0:00:00 613.06 kB/s
wheel-0.29.0-p 100% |#############################################################################################################################################| Time: 0:00:00 401.11 kB/s
conda-3.19.3.2 100% |#############################################################################################################################################| Time: 0:00:00 561.99 kB/s
pip-8.0.3-py27 100% |#############################################################################################################################################| Time: 0:00:00   1.70 MB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|################################################################################################################################################################| 100%
-bash-4.2$ bin/conda create -n rootclone --clone root
Fetching package metadata: ......
src_prefix: '/reg/g/psdm/sw/condadev/external/minconda2beta'
dst_prefix: '/reg/g/psdm/sw/condadev/external/minconda2beta/envs/rootclone'
Packages: 15
Files: 0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/misc.py", line 243, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/resolve.py", line 688, in dependency_sort
    for key, value in iteritems(must_have):
  File "/reg/g/psdm/sw/condadev/external/minconda2beta/lib/python2.7/site-packages/conda/compat.py", line 157, in iteritems
    return iter(getattr(d, _iteritems)())
AttributeError: 'list' object has no attribute 'iteritems'
-bash-4.2$ bin/conda info
Current conda install:

             platform : linux-64
        conda version : 3.19.3.dev214+g57e4dd8
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /reg/g/psdm/sw/condadev/external/minconda2beta  (writable)
  default environment : /reg/g/psdm/sw/condadev/external/minconda2beta
     envs directories : /reg/g/psdm/sw/condadev/external/minconda2beta/envs
        package cache : /reg/g/psdm/sw/condadev/external/minconda2beta/pkgs
         channel URLs : https://conda.anaconda.org/conda/linux-64/
                        https://conda.anaconda.org/conda/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /reg/neh/home/psrel/.condarc
    is foreign system : False

-

best,

David

________________________________________

**Comment by mcg1969** [comment]
@kalefranz this is interesting. What seems to be happening is that the `dependency_sort` routine is receiving a list instead of a dict. In a standard install, it's supposed to be a dict (package names as key, dist names as value). It wouldn't be difficult to detect both modes in `dependency_sort` and accommodate them.

**Comment by mcg1969** [comment]
I know the problem here. Very simple fix. Will do it

**Comment by vascoosx** [comment]
@kalefranz I added the "conda" channel but when I tried to update with `conda update conda` another error occurred:

```
Fetching package metadata: ......
.Solving package specifications: .........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 9, in <module>
    load_entry_point('conda===3.19.1-194-g2d6a70d', 'console_scripts', 'conda')()
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\plan.py", line 434, in install_actions
    smh = r.dependency_sort(must_have)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\resolve.py", line 699, in dependency_sort
    depends = lookup(value)
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\resolve.py", line 695, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "C:\Users\username\AppData\Local\Continuum\Anaconda\lib\site-packages\conda-3.19.1_194_g2d6a70d-py2.7.egg\conda\resolve.py", line 545, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: u'.tar.bz2'
```

I installed a fresh version of conda and now I am able to clone so I am alright now. Thank you.

**Comment by mcg1969** [comment]
Let's close this, then, but we can reopen if necessary.

**Comment by mcg1969** [comment]
Fix in preparation.

**Comment by mcg1969** [comment]
Fix here: https://github.com/conda/conda/pull/2193
