### ISSUE TITLE
Error when trying to install Python 3.4

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#2163]
I am trying to create a Python 3.4 environment on Linux:

```
$ conda create -n py34test2 python=3.4
Fetching package metadata: ....
Solving package specifications: ...........
Package plan for installation in environment /disk1/data/anaconda/envs/py34test2:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2g-0     
    pip:        8.0.3-py34_0 
    python:     3.4.4-0      
    readline:   6.2-2        
    setuptools: 20.1.1-py34_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py34_0
    xz:         5.0.5-1      
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the####################                                        |  60%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/disk1/data/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/disk1/data/anaconda/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/disk1/data/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/disk1/data/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/disk1/data/anaconda/pkgs/python-3.4.4-0/lib/python3.4/config-3.4m/python-config.py'
```

Here is the output of ``conda info``:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.19.3
  conda-build version : 1.8.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /disk1/data/anaconda  (writable)
  default environment : /disk1/data/anaconda
     envs directories : /disk1/data/anaconda/envs
        package cache : /disk1/data/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/robitaille/.condarc
    is foreign system : False
```

**Comment by kalefranz** [comment]
Try

    conda clean -stpliy
    conda update conda
    conda create -n py34test3 python=3.4

Re-open or file a new ticket if you're still having problems :)
