### ISSUE TITLE
Error on installing reportlab

### ISSUE THREAD

**Issue by aluis89** [conda/conda#2168]
conda install -c https://conda.anaconda.org/anaconda reportlab

Traceback (most recent call last):
  File "C:\Users\aluis\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\cli\main.py", line 195,
 in main
    args_func(args, p)
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\cli\main.py", line 202,
 in args_func
    args.func(args, p)
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\cli\main_install.py", l
ine 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\cli\install.py", line 4
23, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\plan.py", line 537, in
execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\instructions.py", line
148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\instructions.py", line
91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\instructions.py", line
87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\install.py", line 605,
in link
    files = list(yield_lines(join(info_dir, 'files')))
  File "C:\Users\aluis\Anaconda3\lib\site-packages\conda\install.py", line 216,
in yield_lines
    for line in open(path):
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\aluis\\Anaco
nda3\\pkgs\\zlib-1.2.8-vc14_2\\info\\files'

conda install -c https://conda.anaconda.org/anaconda reportlab

Current conda install:

             platform : win-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.8.1
     root environment : C:\Users\aluis\Anaconda3  (writable)
  default environment : C:\Users\aluis\Anaconda3\envs\py35
     envs directories : C:\Users\aluis\Anaconda3\envs
        package cache : C:\Users\aluis\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : True

# NOTE:
#     root directory 'C:\Users\aluis\Anaconda3' is uninitialized

**Comment by kalefranz** [comment]
Try

    conda clean --index-cache --tarballs --packages
    conda update conda

and then re-run your install.
