### ISSUE TITLE
Error with install --revision

### ISSUE THREAD

**Issue by lec8rje** [conda/conda#2169]
I was trying to roll back some changes that seemed to be causing conflicts between  cf_checker and ecmwf_grib. This trace back occurred.  conda info is below the traceback. Conda suggested I post here.

Traceback (most recent call last):
  File "/home/riche/bin/miniconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/riche/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/home/riche/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/home/riche/bin/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/riche/bin/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 411, in install
    plan.display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "/home/riche/bin/miniconda/lib/python2.7/site-packages/conda/plan.py", line 83, in display_actions
    Packages[dist] = Package(dist + '.tar.bz2', index[dist + '.tar.bz2'])
KeyError: 'jasper-1.900.1-3.tar.bz2'

current conda install:

             platform : linux-64
        conda version : 3.19.3
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/riche/bin/miniconda  (writable)
  default environment : /home/riche/bin/miniconda
     envs directories : /home/riche/bin/miniconda/envs
        package cache : /home/riche/bin/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
Hey @lec8rje, don't really know how to debug because you didn't include the original command you ran to produce the stack trace.  Also, the bug is very likely fixed in conda `>=4.0`.  Going to close for now.  Feel free to re-open if you keep having problems.
