### ISSUE TITLE
conda env update yields "unexpected error"

### ISSUE THREAD

**Issue by julienchastang** [conda/conda#2190]
Hi.

When I do a:

`conda env update --name root -f /home/python/emacs-python.yml
`

I get this error:

```
Fetching package metadata: ....
Solving package specifications: ...........Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "/home/python/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/home/python/anaconda/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/python/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/python/anaconda/lib/python3.4/site-packages/conda_env/cli/main_update.py", line 106, in execute
    installer.install(prefix, specs, args, env)
  File "/home/python/anaconda/lib/python3.4/site-packages/conda_env/installers/conda.py", line 13, in install
    actions = plan.install_actions(prefix, index, specs)
  File "/home/python/anaconda/lib/python3.4/site-packages/conda/plan.py", line 435, in install_actions
    smh = r.dependency_sort(must_have)
  File "/home/python/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 717, in dependency_sort
    depends = lookup(value)
  File "/home/python/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 714, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/home/python/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 574, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'cartopy-0.13.1-np110py34_0.tar.bz2'

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


The command '/bin/sh -c conda env update --name root -f /home/python/emacs-python.yml' returned a non-zero code: 1

```

here is the content of that `emacs-python.yml` file

```
 name: root
 dependencies:
   - jedi
   - rope
   - flake8
   - pylint
   - pip
   - jupyter_client
   - ipykernel
   - jupyter_console
```

conda info

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.0.0
  conda-build version : not installed
       python version : 3.4.4.final.0
     requests version : 2.9.1
     root environment : /home/python/anaconda  (writable)
  default environment : /home/python/anaconda
     envs directories : /home/python/anaconda/envs
        package cache : /home/python/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by kalefranz** [comment]
@julienchastang, Can you try `conda update conda` (should give you `4.0.1`), and then

    conda update jedi rope flake8 pylint pip jupyter_client ipykernel jupyter_console

**Comment by julienchastang** [comment]
@kalefranz Thanks for getting back to me so quick. I am now at `4.0.1`

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.0.1
  conda-build version : not installed
       python version : 3.4.4.final.0
     requests version : 2.9.1
     root environment : /home/python/anaconda  (writable)
  default environment : /home/python/anaconda
     envs directories : /home/python/anaconda/envs
        package cache : /home/python/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

When I run 

`conda update jedi rope flake8 pylint pip jupyter_client ipykernel jupyter_console`

I get

`Error: package 'jedi' is not installed in /home/python/anaconda`

Installing that list of packages via `conda install` does work, BTW.

This may not be the diagnostic you were hoping to see, but note that 

`conda env update --name root -f /home/python/emacs-python.yml `

is how I have been able to successfully install those packages in the `root` environment in the past. I have been using this work flow for a while and only had problems recently.

Ultimately, I am simply trying to install those packages in the `root` environment with a `.yml` file.

Thanks again for your help.

**Comment by kalefranz** [comment]
@julienchastang That definitely helps. Can you also give me the output of

    conda list --explicit -n root

**Comment by julienchastang** [comment]
@kalefranz See below. (Note, in the output below, I never installed those packages from `emacs-python.yml` via `conda install` which I think is what you want, but just mentioning it for full disclosure.) Thanks again.

```
$ conda list --explicit -n root
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/linux-64/anaconda-client-1.2.2-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/backports_abc-0.4-py34_0.tar.bz2
https://conda.binstar.org/scitools/linux-64/cartopy-0.13.1-np110py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/clyent-1.2.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/conda-4.0.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/conda-env-2.4.5-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/curl-7.45.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/cycler-0.10.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/decorator-4.0.9-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/fontconfig-2.11.1-5.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/freetype-2.5.5-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/funcsigs-0.4-py34_0.tar.bz2
https://conda.binstar.org/scitools/linux-64/geos-3.4.2-4.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/hdf5-1.8.15.1-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipykernel-4.3.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython-4.1.2-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipython_genutils-0.1.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ipywidgets-4.1.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jbig-2.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jinja2-2.8-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jpeg-8d-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jsonschema-2.4.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter-1.0.0-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_client-4.1.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_console-4.1.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/jupyter_core-4.0.6-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libgfortran-3.0-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libnetcdf-4.3.3.1-3.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libpng-1.6.17-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libsodium-1.0.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libtiff-4.0.6-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libxml2-2.9.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/libxslt-1.1.28-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/lxml-3.5.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/markupsafe-0.23-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/matplotlib-1.5.1-np110py34_0.tar.bz2
https://conda.binstar.org/Unidata/linux-64/metpy-0.3.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mistune-0.7.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mkl-11.3.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/mock-1.3.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nbconvert-4.1.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nbformat-4.0.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/netcdf4-1.2.2-np110py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/networkx-1.11-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/nose-1.3.7-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/notebook-4.1.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/numpy-1.10.4-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/openssl-1.0.2g-0.tar.bz2
https://conda.binstar.org/scitools/linux-64/owslib-0.10.3-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pandas-0.17.1-np110py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/path.py-8.1.2-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pbr-1.3.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pexpect-3.3-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pickleshare-0.5-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pillow-3.1.1-py34_0.tar.bz2
https://conda.binstar.org/Unidata/linux-64/pint-0.6-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pip-8.0.3-py34_0.tar.bz2
https://conda.binstar.org/scitools/linux-64/proj.4-4.9.1-1.tar.bz2
https://conda.binstar.org/Unidata/linux-64/protobuf-3.0.0a3-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/ptyprocess-0.5-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycosat-0.6.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pycrypto-2.6.1-py34_0.tar.bz2
https://conda.binstar.org/scitools/linux-64/pyepsg-0.2.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pygments-2.1.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyparsing-2.0.3-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyproj-1.9.4-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyqt-4.11.4-py34_1.tar.bz2
https://conda.binstar.org/scitools/linux-64/pyshp-1.2.3-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-3.4.4-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/python-dateutil-2.4.2-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pytz-2015.7-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyyaml-3.11-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/pyzmq-15.2.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/qt-4.8.7-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/qtconsole-4.1.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/readline-6.2-2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/requests-2.9.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/scipy-0.17.0-np110py34_2.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/setuptools-20.1.1-py34_0.tar.bz2
https://conda.binstar.org/scitools/linux-64/shapely-1.5.13-np110py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/simplegeneric-0.8.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sip-4.16.9-py34_0.tar.bz2
https://conda.binstar.org/Unidata/linux-64/siphon-0.3.2-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/six-1.10.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/sqlite-3.9.2-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/terminado-0.5-py34_1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tk-8.5.18-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/tornado-4.3-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/traitlets-4.1.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/wheel-0.29.0-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xarray-0.7.1-py34_0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/xz-5.0.5-1.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/yaml-0.1.6-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zeromq-4.1.3-0.tar.bz2
https://repo.continuum.io/pkgs/free/linux-64/zlib-1.2.8-0.tar.bz2


```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-env#231
