### ISSUE TITLE
conda skeleton cran broken

### ISSUE THREAD

**Issue by edurand** [conda/conda#2198]
conda skeleton cran rJava
Tip: install CacheControl to cache the CRAN metadata
Fetching metadata from http://cran.r-project.org/
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/usr/prog/onc/bin/miniconda3/bin/conda-skeleton", line 5, in <module>
    sys.exit(main())
  File "/usr/prog/onc/bin/miniconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 272, in main
    args_func(args, p)
  File "/usr/prog/onc/bin/miniconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 486, in args_func
    args.func(args, p)
  File "/usr/prog/onc/bin/miniconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 290, in execute
    cran.main(args, parser)
  File "/usr/prog/onc/bin/miniconda3/lib/python3.5/site-packages/conda_build/cran.py", line 574, in main
    d = {k:unicodedata.normalize("NFKD", compat.text_type(v)).encode('ascii', 'ignore') for k, v in d.iteritems()}
AttributeError: 'dict' object has no attribute 'iteritems'

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#816
