### ISSUE TITLE
conda 4.0.2 failure during dependency resolution

### ISSUE THREAD

**Issue by eriknw** [conda/conda#2224]
This command fails in Linux and OS X
```
conda create -n testconda anaconda accelerate tornado=4.0.2
```
with this traceback:
```
Traceback (most recent call last):
  File "/Users/ewelch/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    update_deps=args.update_deps)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/plan.py", line 435, in install_actions
    smh = r.dependency_sort(must_have)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 730, in dependency_sort
    depends = lookup(value)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 725, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 574, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: u'anaconda-2.1.0-np19py27_0.tar..tar.bz2'
```
Here is my `conda info`:
```
             platform : osx-64
        conda version : 4.0.2
  conda-build version : 1.18.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/ewelch/miniconda  (writable)
  default environment : /Users/ewelch/miniconda
     envs directories : /Users/ewelch/miniconda/envs
        package cache : /Users/ewelch/miniconda/pkgs
         channel URLs : https://conda.binstar.org/javascript/osx-64/
                        https://conda.binstar.org/javascript/noarch/
                        https://conda.binstar.org/wakari/osx-64/
                        https://conda.binstar.org/wakari/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ewelch/.condarc
    is foreign system : False
```
I can circumvent the exception by using the following diff.  I don't propose that this is the solution (I don't know the code well enough), but I hope it's a useful starting point:
```diff
diff --git a/conda/plan.py b/conda/plan.py
index a7fd836..519dedf 100644
--- a/conda/plan.py
+++ b/conda/plan.py
@@ -412,7 +412,7 @@ def install_actions(prefix, index, specs, force=False, only_names=None,
 
     pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
     for fn in pkgs:
-        dist = fn[:-8]
+        dist = fn[:fn.rindex('.tar.bz2')]
         name = install.name_dist(dist)
         if not name or only_names and name not in only_names:
             continue
```
The reason this fix works is that the filename, `fn`, is `anaconda-2.1.0-np19py27_0.tar.bz2[mkl]`, and the code assumes it ends in `.tar.bz2`.

**Comment by kalefranz** [comment]
@mcg1969  First time I'm seeing this.  Guessing this problem would still exist in the `4.0.x` branch?

@eriknw Thanks for the awesome report and digging in with a workable patch.

**Comment by eriknw** [comment]
Yes, the problem still exists in the `4.0.x` branch.

**Comment by mcg1969** [comment]
Thanks Eric! I will look at this in the morning

**Comment by eriknw** [comment]
A quick bifurcation reveals this commit is the culprit: 7d1f930

**Comment by mcg1969** [comment]
I'd say that just revealed the bug, it didn't cause it.

**Comment by mcg1969** [comment]
Odd. I can't reproduce it in my test notebook. Erik, can you do a `--debug` run and post the output here?

**Comment by mcg1969** [comment]
Nevermind, I have it.

**Comment by eriknw** [comment]
Sure.  Using version 4.0.2.
```
$ conda --debug create -n testconda anaconda accelerate tornado=4.0.2

DEBUG:binstar:Found login token: /Users/ewelch/Library/Application Support/binstar/https%3A%2F%2Fapi.anaconda.org.token
DEBUG:conda.fetch:channel_urls=('https://conda.binstar.org/javascript/osx-64/', 'https://conda.binstar.org/javascript/noarch/', 'https://conda.binstar.org/wakari/osx-64/', 'https://conda.binstar.org/wakari/noarch/', 'https://repo.continuum.io/pkgs/free/osx-64/', 'https://repo.continuum.io/pkgs/free/noarch/', 'https://repo.continuum.io/pkgs/pro/osx-64/', 'https://repo.continuum.io/pkgs/pro/noarch/')
Fetching package metadata: INFO:stdoutlog:Fetching package metadata: 
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.binstar.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): conda.binstar.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): repo.continuum.io
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): conda.binstar.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): conda.binstar.org
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/osx-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/osx-64/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /javascript/noarch/repodata.json.bz2 HTTP/1.1" 301 184
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG:requests.packages.urllib3.connectionpool:"GET /javascript/osx-64/repodata.json.bz2 HTTP/1.1" 301 184
DEBUG:requests.packages.urllib3.connectionpool:"GET /wakari/noarch/repodata.json.bz2 HTTP/1.1" 301 184
DEBUG:requests.packages.urllib3.connectionpool:"GET /wakari/osx-64/repodata.json.bz2 HTTP/1.1" 301 184
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (2): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (3): conda.anaconda.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (4): conda.anaconda.org
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/pro/osx-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /wakari/noarch/repodata.json.bz2 HTTP/1.1" 200 138
.DEBUG:dotupdate:fetching repodata: args ('https://conda.binstar.org/wakari/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /javascript/noarch/repodata.json.bz2 HTTP/1.1" 200 138
.DEBUG:dotupdate:fetching repodata: args ('https://conda.binstar.org/javascript/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /wakari/osx-64/repodata.json.bz2 HTTP/1.1" 200 445
.DEBUG:dotupdate:fetching repodata: args ('https://conda.binstar.org/wakari/osx-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /javascript/osx-64/repodata.json.bz2 HTTP/1.1" 200 1796
.DEBUG:dotupdate:fetching repodata: args ('https://conda.binstar.org/javascript/osx-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}
.DEBUG:dotupdate:fetching repodata: args ('https://repo.continuum.io/pkgs/free/osx-64/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0x1059fd110>}

INFO:stdoutlog:

DEBUG:conda.plan:Pinned specs=[]
DEBUG:conda.plan:H0 specs=['anaconda', 'accelerate', 'tornado 4.0.2*']
DEBUG:conda.plan:H2 python True
DEBUG:conda.plan:H2 lua False
DEBUG:conda.plan:H2A lua
DEBUG:conda.plan:HF specs=['anaconda', 'accelerate', 'tornado 4.0.2*', 'python 2.7*']
DEBUG:conda.resolve:Checking satisfiability of current install
DEBUG:conda.resolve:Checking if the current environment is consistent
Solving package specifications: INFO:stdoutlog:Solving package specifications: 
.DEBUG:dotupdate:Solving for [MatchSpec('anaconda'), MatchSpec('accelerate'), MatchSpec('tornado 4.0.2*'), MatchSpec('python 2.7*')]
DEBUG:conda.resolve:Retrieving packages for: [MatchSpec('anaconda'), MatchSpec('accelerate'), MatchSpec('tornado 4.0.2*'), MatchSpec('python 2.7*')]
DEBUG:conda.resolve: sqlite: pruned from 5 -> 4
DEBUG:conda.resolve: libxml2: pruned from 3 -> 2
DEBUG:conda.resolve: pycparser: pruned from 20 -> 12
DEBUG:conda.resolve: python: pruned from 66 -> 65
DEBUG:conda.resolve: astropy: pruned from 108 -> 43
DEBUG:conda.resolve: numpy: pruned from 119 -> 113
DEBUG:conda.resolve: pip: pruned from 88 -> 27
DEBUG:conda.resolve: pygments: pruned from 22 -> 12
DEBUG:conda.resolve: networkx: pruned from 24 -> 17
DEBUG:conda.resolve: bitarray: pruned from 8 -> 5
DEBUG:conda.resolve: libxslt: pruned from 3 -> 2
DEBUG:conda.resolve: xlrd: pruned from 19 -> 10
DEBUG:conda.resolve: curl: pruned from 11 -> 6
DEBUG:conda.resolve: tornado: pruned from 56 -> 31
DEBUG:conda.resolve: cython: pruned from 74 -> 31
DEBUG:conda.resolve: lxml: pruned from 54 -> 29
DEBUG:conda.resolve: yaml: pruned from 3 -> 2
DEBUG:conda.resolve: six: pruned from 37 -> 24
DEBUG:conda.resolve: docutils: pruned from 16 -> 12
DEBUG:conda.resolve: tk: pruned from 4 -> 3
DEBUG:conda.resolve: libpng: pruned from 4 -> 2
DEBUG:conda.resolve: sympy: pruned from 28 -> 20
DEBUG:conda.resolve: zeromq: pruned from 6 -> 4
DEBUG:conda.resolve: numpy: pruned from 113 -> 47
DEBUG:conda.resolve: pandas: pruned from 93 -> 39
DEBUG:conda.resolve: pyzmq: pruned from 61 -> 25
DEBUG:conda.resolve: freetype: pruned from 6 -> 4
DEBUG:conda.resolve: sqlalchemy: pruned from 94 -> 34
DEBUG:conda.resolve: pyflakes: pruned from 43 -> 17
DEBUG:conda.resolve: python: pruned from 65 -> 28
DEBUG:conda.resolve: scikit-image: pruned from 70 -> 38
DEBUG:conda.resolve: scipy: pruned from 137 -> 131
DEBUG:conda.resolve: matplotlib: pruned from 103 -> 43
DEBUG:conda.resolve: scipy: pruned from 131 -> 56
DEBUG:conda.resolve: jinja2: pruned from 26 -> 17
DEBUG:conda.resolve: ply: pruned from 19 -> 11
DEBUG:conda.resolve: readline: pruned from 3 -> 2
DEBUG:conda.resolve: pyyaml: pruned from 13 -> 12
DEBUG:conda.resolve: sphinx: pruned from 42 -> 25
DEBUG:conda.resolve: hdf5: pruned from 9 -> 7
DEBUG:conda.resolve: pycosat: pruned from 27 -> 8
DEBUG:conda.resolve: zlib: pruned from 4 -> 2
DEBUG:conda.resolve: psutil: pruned from 60 -> 29
DEBUG:conda.resolve: pytz: pruned from 49 -> 25
DEBUG:conda.resolve: greenlet: pruned from 30 -> 22
DEBUG:conda.resolve: nose: pruned from 33 -> 20
DEBUG:conda.resolve: requests: pruned from 83 -> 28
DEBUG:conda.resolve: accelerate: pruned from 120 -> 114
DEBUG:conda.resolve: tornado: pruned from 31 -> 4
DEBUG:conda.resolve: python: pruned from 28 -> 26
DEBUG:conda.resolve: pip: pruned from 27 -> 25
DEBUG:conda.resolve: python: pruned from 26 -> 11
DEBUG:conda.resolve: pip: pruned from 25 -> 8
DEBUG:conda.resolve: anaconda: pruned from 108 -> 2
DEBUG:conda.resolve: sockjs-tornado: pruned from 9 -> 1
DEBUG:conda.resolve: tornado: pruned from 4 -> 1
DEBUG:conda.resolve: ssl_match_hostname: pruned from 4 -> 1
DEBUG:conda.resolve: cffi: pruned from 46 -> 1
DEBUG:conda.resolve: pycparser: pruned from 12 -> 3
DEBUG:conda.resolve: jpeg: pruned from 2 -> 1
DEBUG:conda.resolve: pyqt: pruned from 15 -> 1
DEBUG:conda.resolve: sip: pruned from 12 -> 3
DEBUG:conda.resolve: networkx: pruned from 17 -> 1
DEBUG:conda.resolve: decorator: pruned from 22 -> 6
DEBUG:conda.resolve: numexpr: pruned from 95 -> 2
DEBUG:conda.resolve: numpy: pruned from 47 -> 4
DEBUG:conda.resolve: python.app: pruned from 26 -> 1
DEBUG:conda.resolve: cython: pruned from 31 -> 1
DEBUG:conda.resolve: flask: pruned from 10 -> 1
DEBUG:conda.resolve: itsdangerous: pruned from 11 -> 3
DEBUG:conda.resolve: jinja2: pruned from 17 -> 5
DEBUG:conda.resolve: werkzeug: pruned from 41 -> 12
DEBUG:conda.resolve: yaml: pruned from 2 -> 1
DEBUG:conda.resolve: blaze: pruned from 75 -> 1
DEBUG:conda.resolve: multipledispatch: pruned from 33 -> 7
DEBUG:conda.resolve: sqlalchemy: pruned from 34 -> 10
DEBUG:conda.resolve: pytables: pruned from 43 -> 2
DEBUG:conda.resolve: hdf5: pruned from 7 -> 2
DEBUG:conda.resolve: datashape: pruned from 67 -> 11
DEBUG:conda.resolve: cytoolz: pruned from 27 -> 7
DEBUG:conda.resolve: dynd-python: pruned from 41 -> 1
DEBUG:conda.resolve: libdynd: pruned from 11 -> 1
DEBUG:conda.resolve: toolz: pruned from 19 -> 5
DEBUG:conda.resolve: h5py: pruned from 71 -> 2
DEBUG:conda.resolve: requests: pruned from 28 -> 8
DEBUG:conda.resolve: pandas: pruned from 39 -> 3
DEBUG:conda.resolve: pytz: pruned from 25 -> 7
DEBUG:conda.resolve: unicodecsv: pruned from 8 -> 1
DEBUG:conda.resolve: sympy: pruned from 20 -> 1
DEBUG:conda.resolve: itsdangerous: pruned from 3 -> 1
DEBUG:conda.resolve: xlwt: pruned from 9 -> 1
DEBUG:conda.resolve: freetype: pruned from 4 -> 1
DEBUG:conda.resolve: openpyxl: pruned from 20 -> 1
DEBUG:conda.resolve: lxml: pruned from 29 -> 8
DEBUG:conda.resolve: cryptography: pruned from 43 -> 1
DEBUG:conda.resolve: six: pruned from 24 -> 7
DEBUG:conda.resolve: python: pruned from 11 -> 1
DEBUG:conda.resolve: openssl: pruned from 16 -> 12
DEBUG:conda.resolve: _license: pruned from 6 -> 1
DEBUG:conda.resolve: markupsafe: pruned from 9 -> 1
DEBUG:conda.resolve: scipy: pruned from 56 -> 2
DEBUG:conda.resolve: jinja2: pruned from 5 -> 1
DEBUG:conda.resolve: setuptools: pruned from 170 -> 44
DEBUG:conda.resolve: decorator: pruned from 6 -> 1
DEBUG:conda.resolve: qt: pruned from 7 -> 1
DEBUG:conda.resolve: scikit-learn: pruned from 141 -> 2
DEBUG:conda.resolve: nose: pruned from 20 -> 5
DEBUG:conda.resolve: lxml: pruned from 8 -> 1
DEBUG:conda.resolve: psutil: pruned from 29 -> 1
DEBUG:conda.resolve: greenlet: pruned from 22 -> 1
DEBUG:conda.resolve: nose: pruned from 5 -> 1
DEBUG:conda.resolve: h5py: pruned from 2 -> 1
DEBUG:conda.resolve: hdf5: pruned from 2 -> 1
DEBUG:conda.resolve: redis-py: pruned from 12 -> 1
DEBUG:conda.resolve: traits: pruned from 6 -> 1
DEBUG:conda.resolve: gevent: pruned from 12 -> 1
DEBUG:conda.resolve: bitarray: pruned from 5 -> 1
DEBUG:conda.resolve: libxslt: pruned from 2 -> 1
DEBUG:conda.resolve: xlrd: pruned from 10 -> 1
DEBUG:conda.resolve: pyparsing: pruned from 12 -> 1
DEBUG:conda.resolve: kiwisolver: pruned from 4 -> 1
DEBUG:conda.resolve: dateutil: pruned from 17 -> 1
DEBUG:conda.resolve: boto: pruned from 80 -> 1
DEBUG:conda.resolve: multipledispatch: pruned from 7 -> 1
DEBUG:conda.resolve: blz: pruned from 20 -> 1
DEBUG:conda.resolve: pyopenssl: pruned from 13 -> 1
DEBUG:conda.resolve: ujson: pruned from 8 -> 1
DEBUG:conda.resolve: casuarius: pruned from 2 -> 1
DEBUG:conda.resolve: docutils: pruned from 12 -> 1
DEBUG:conda.resolve: future: pruned from 60 -> 1
DEBUG:conda.resolve: werkzeug: pruned from 12 -> 1
DEBUG:conda.resolve: spyder-app: pruned from 26 -> 1
DEBUG:conda.resolve: spyder: pruned from 38 -> 2
DEBUG:conda.resolve: pygments: pruned from 12 -> 3
DEBUG:conda.resolve: ipython: pruned from 83 -> 28
DEBUG:conda.resolve: pyzmq: pruned from 25 -> 5
DEBUG:conda.resolve: zeromq: pruned from 4 -> 3
DEBUG:conda.resolve: libpng: pruned from 2 -> 1
DEBUG:conda.resolve: libsodium: pruned from 2 -> 1
DEBUG:conda.resolve: cytoolz: pruned from 7 -> 1
DEBUG:conda.resolve: matplotlib: pruned from 43 -> 1
DEBUG:conda.resolve: ply: pruned from 11 -> 1
DEBUG:conda.resolve: ipython: pruned from 28 -> 1
DEBUG:conda.resolve: pyyaml: pruned from 12 -> 1
DEBUG:conda.resolve: pytables: pruned from 2 -> 1
DEBUG:conda.resolve: pyaudio: pruned from 2 -> 1
DEBUG:conda.resolve: openssl: pruned from 12 -> 1
DEBUG:conda.resolve: requests: pruned from 8 -> 1
DEBUG:conda.resolve: ipython-qtconsole: pruned from 34 -> 1
DEBUG:conda.resolve: cdecimal: pruned from 4 -> 1
DEBUG:conda.resolve: libtiff: pruned from 5 -> 1
DEBUG:conda.resolve: pycparser: pruned from 3 -> 1
DEBUG:conda.resolve: llvmpy: pruned from 51 -> 1
DEBUG:conda.resolve: llvm: pruned from 3 -> 1
DEBUG:conda.resolve: pygments: pruned from 3 -> 1
DEBUG:conda.resolve: toolz: pruned from 5 -> 1
DEBUG:conda.resolve: py: pruned from 45 -> 1
DEBUG:conda.resolve: bokeh: pruned from 80 -> 1
DEBUG:conda.resolve: gevent-websocket: pruned from 11 -> 1
DEBUG:conda.resolve: numpy: pruned from 4 -> 2
DEBUG:conda.resolve: pyzmq: pruned from 5 -> 1
DEBUG:conda.resolve: zeromq: pruned from 3 -> 1
DEBUG:conda.resolve: tk: pruned from 3 -> 1
DEBUG:conda.resolve: enable: pruned from 9 -> 1
DEBUG:conda.resolve: pil: pruned from 6 -> 2
DEBUG:conda.resolve: traitsui: pruned from 3 -> 1
DEBUG:conda.resolve: pyface: pruned from 3 -> 1
DEBUG:conda.resolve: xlsxwriter: pruned from 70 -> 1
DEBUG:conda.resolve: pytz: pruned from 7 -> 1
DEBUG:conda.resolve: atom: pruned from 15 -> 1
DEBUG:conda.resolve: jdcal: pruned from 8 -> 1
DEBUG:conda.resolve: pycurl: pruned from 35 -> 1
DEBUG:conda.resolve: curl: pruned from 6 -> 1
DEBUG:conda.resolve: launcher: pruned from 8 -> 1
DEBUG:conda.resolve: zlib: pruned from 2 -> 1
DEBUG:conda.resolve: rope: pruned from 9 -> 1
DEBUG:conda.resolve: runipy: pruned from 16 -> 1
DEBUG:conda.resolve: setuptools: pruned from 44 -> 1
DEBUG:conda.resolve: statsmodels: pruned from 35 -> 1
DEBUG:conda.resolve: patsy: pruned from 30 -> 3
DEBUG:conda.resolve: ipython-notebook: pruned from 47 -> 1
DEBUG:conda.resolve: grin: pruned from 4 -> 1
DEBUG:conda.resolve: spyder: pruned from 2 -> 1
DEBUG:conda.resolve: configobj: pruned from 15 -> 1
DEBUG:conda.resolve: sqlite: pruned from 4 -> 1
DEBUG:conda.resolve: pil: pruned from 2 -> 1
DEBUG:conda.resolve: enaml: pruned from 12 -> 1
DEBUG:conda.resolve: libxml2: pruned from 2 -> 1
DEBUG:conda.resolve: argcomplete: pruned from 31 -> 1
DEBUG:conda.resolve: numba: pruned from 172 -> 1
DEBUG:conda.resolve: sqlalchemy: pruned from 10 -> 1
DEBUG:conda.resolve: pip: pruned from 8 -> 1
DEBUG:conda.resolve: sip: pruned from 3 -> 1
DEBUG:conda.resolve: chaco: pruned from 8 -> 1
DEBUG:conda.resolve: six: pruned from 7 -> 1
DEBUG:conda.resolve: patsy: pruned from 3 -> 1
DEBUG:conda.resolve: pytest: pruned from 59 -> 1
DEBUG:conda.resolve: binstar: pruned from 73 -> 1
DEBUG:conda.resolve: pandas: pruned from 3 -> 1
DEBUG:conda.resolve: mock: pruned from 14 -> 1
DEBUG:conda.resolve: datashape: pruned from 11 -> 1
DEBUG:conda.resolve: scikit-image: pruned from 38 -> 1
DEBUG:conda.resolve: astropy: pruned from 43 -> 1
DEBUG:conda.resolve: colorama: pruned from 16 -> 1
DEBUG:conda.resolve: readline: pruned from 2 -> 1
DEBUG:conda.resolve: beautiful-soup: pruned from 8 -> 1
DEBUG:conda.resolve: sphinx: pruned from 25 -> 1
DEBUG:conda.resolve: pycrypto: pruned from 8 -> 1
DEBUG:conda.resolve: pyflakes: pruned from 17 -> 1
DEBUG:conda.resolve: pycosat: pruned from 8 -> 1
DEBUG:conda.resolve: futures: pruned from 17 -> 1
DEBUG:conda.resolve: pep8: pruned from 28 -> 1
DEBUG:conda.resolve: node-webkit: pruned from 2 -> 1
DEBUG:conda.resolve: nltk: pruned from 54 -> 1
DEBUG:conda.resolve: abstract-rendering: pruned from 17 -> 1
DEBUG:conda.resolve: accelerate: pruned from 114 -> 8
DEBUG:conda.resolve: numbapro: pruned from 145 -> 1
DEBUG:conda.resolve: cudatoolkit: pruned from 4 -> 1
DEBUG:conda.resolve: numbapro_cudalib: pruned from 2 -> 1
DEBUG:conda.resolve: mkl: pruned from 34 -> 1
DEBUG:conda.resolve: mkl-rt: pruned from 2 -> 1
DEBUG:conda.resolve: mkl-service: pruned from 14 -> 2
DEBUG:conda.resolve: mklfft: pruned from 23 -> 3
DEBUG:conda.resolve: accelerate: pruned from 8 -> 1
DEBUG:conda.resolve: mklfft: pruned from 3 -> 1
.DEBUG:dotupdate:Checking satisfiability
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package removal metric: 0
DEBUG:conda.logic:Empty objective, trivial solution
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Eliminating 1/1 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (599+1) clauses
DEBUG:conda.logic:Bisection failure, new range=(1,1)
DEBUG:conda.logic:Bisection attempt: (1,1), (599+1) clauses
DEBUG:conda.logic:Bisection success, new range=(1,1)
DEBUG:conda.logic:Final sum objective: 1
DEBUG:conda.logic:New peak objective: 1
.DEBUG:dotupdate:Track feature count: 1
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Eliminating 4/4 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (600+4) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Package feature count: 4
DEBUG:conda.logic:Empty objective, trivial solution
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Requested package version/build metrics: 0/0
DEBUG:conda.logic:Empty objective, trivial solution
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Eliminating 1/1 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (604+1) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Required package version/build metrics: 0/0
DEBUG:conda.logic:Empty objective, trivial solution
DEBUG:conda.logic:Empty objective, trivial solution
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Optional package version/build metrics: 0/0/0
DEBUG:conda.logic:Empty objective, trivial solution
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Additional package version/build metrics: 0/0
.DEBUG:dotupdate:Looking for alternate solutions

INFO:stdoutlog:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/ewelch/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
    update_deps=args.update_deps)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/plan.py", line 435, in install_actions
    smh = r.dependency_sort(must_have)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 730, in dependency_sort
    depends = lookup(value)
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 725, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/Users/ewelch/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 574, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: u'anaconda-2.1.0-np19py27_0.tar..tar.bz2'
```

**Comment by mcg1969** [comment]
Did I tell anyone I hate `with_features_depends` with a white hot burning hate? I do you know.

**Comment by eriknw** [comment]
Great, good luck.

If we're looking for a commit to blame, this one is highly suspect to me:
https://github.com/conda/conda/commit/b5232f08ba4c3f5041aed70d54af3d25607102e8#diff-52a8935af92ea699b0cbb5feb84c19a2R445

The `for` loop linked above assigns names that include features, which will create names like `anaconda-2.1.0-np19py27_0.tar.bz2[mkl]`.  This breaks the assumption (revealed in the diff in the OP) that the key ends with `".tar.bz2"`.

**Comment by kalefranz** [comment]
After we make it through 4.0, I'd like to consider either clarification or alternatives to how we currently use features.  I think @mcg1969 would +1.

**Comment by kalefranz** [comment]
Oh, and we need a data model and real package objects.  This string parsing thing is beyond ridiculous.  `4.?`

**Comment by mcg1969** [comment]
I'm 100% with you. 

Here's the story. `with_features_depends` is a pain in the butt to deal with. Basically, it takes two (or more) different packages---one with features, one without---and combines them together into one metadata blob. To cleanly handle both, I create two separate packages in the index. The `[mkl]` suffix is the featured version.

For some reason I've lost the code that ensures these feature suffixes don't make it out into the wild.

Of course, with a proper data model, where we trade Package object pointers instead of filenames pretending to be pointers, we won't have this problem. These two "virtual" packages will have the same *internal* filename, but will be unique in the eyes of the solver.

**Comment by mcg1969** [comment]
ok, fix submitted. thanks erik!

**Comment by mcg1969** [comment]
you owe me coffee

**Comment by kalefranz** [comment]
Just coffee?  I owe you far more than coffee.  Unless you meant @eriknw.

**Comment by mcg1969** [comment]
Oh no, I'm gunning for your first-born. Erik, I'll settle for coffee.

**Comment by eriknw** [comment]
Thanks for the quick fix.  I know how much you love features and how soundly you sleep when there's an issue.

Do you take cream or sugar?

**Comment by mcg1969** [comment]
Looks like we squashed this one!
