### ISSUE TITLE
Double Keyboard Interrupt hangs conda

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#2238]
On Windows (powershell and cmd.exe), if you type `<CTRL>-C` twice quickly while running a conda command, conda sometimes hangs and never exits (looks like a locking issue)

```
PS C:\Users\End User\workspace\test> conda update conda
Fetching package metadata: ....Traceback (most recent call last):
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Users\End User\Miniconda3\lib\concurrent\futures\_base.py", line 400, in result
    self._condition.wait(timeout)
  File "C:\Users\End User\Miniconda3\lib\threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\End User\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\cli\install.py", line 240, in install
    prefix=prefix)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\cli\common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\api.py", line 43, in get_index
    unknown=unknown)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "C:\Users\End User\Miniconda3\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Users\End User\Miniconda3\lib\concurrent\futures\_base.py", line 581, in __exit__
    self.shutdown(wait=True)
  File "C:\Users\End User\Miniconda3\lib\concurrent\futures\thread.py", line 139, in shutdown
  File "C:\Users\End User\Miniconda3\lib\threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "C:\Users\End User\Miniconda3\lib\threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

conda info:

```
             platform : win-64
        conda version : 4.0.4
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\End User\Miniconda3  (writable)
  default environment : C:\Users\End User\Miniconda3
     envs directories : C:\Users\End User\Miniconda3\envs
        package cache : C:\Users\End User\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by kalefranz** [comment]
Locking was removed in conda 4.3.
