### ISSUE TITLE
conda env create issue

### ISSUE THREAD

**Issue by olivier65** [conda/conda#2243]
The command "conda env create -f .\requirements.yml" yielded this error:

Traceback (most recent call last):
  File "C:\Python\Miniconda\2\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Python\Miniconda\2\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Python\Miniconda\2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Python\Miniconda\2\lib\site-packages\conda_env\cli\main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Python\Miniconda\2\lib\site-packages\conda_env\installers\pip.py", line 8, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

The output of "conda info" is:

platform : win-64
        conda version : 4.0.4
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Python\Miniconda\2  (writable)
  default environment : C:\Python\Miniconda\2
     envs directories : C:\Python\Miniconda\2\envs
        package cache : C:\Python\Miniconda\2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

The requirements.yml file (which GitHub refuses to attach, even after I rename it to *.txt) is:

name: venv.conda
dependencies:
    - cssselect==0.9.1
    - six==1.3.0
    - mock==1.0.1
    - requests==2.4.1
    - numpy==1.6.2
    - pip:
        - Django==1.6.1
        - South==0.8.4
        - django-registration==1.0
        - djangorestframework==2.3.10
        - lxml==3.2.5
        - model-mommy==1.2
        - psycopg2==2.5.1
        - python-dateutil==2.2
        - wsgiref==0.1.2
        - django-filter==0.7
        - pyephem==3.7.5.2
        - pytz2==2014.10

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-env#232

**Comment by msarahan** [comment]
@jreback has encountered this.  Since the conda-env issue tracker is disabled, I'm reopening the issue here.  @jreback, please add any detail that you think might be helpful for reproducing - perhaps the environment.yml file?

**Comment by jreback** [comment]
```
C:\bmflow\python2\2016-09-09.122911\envs>conda env update -f bmc2.yml
Fetching package metadata .........
Solving package specifications: ..........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "C:\Anaconda\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda_env\cli\main_update.py", line 112, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
  File "C:\Anaconda\lib\site-packages\conda_env\installers\pip.py", line 9, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
```

```
C:\bmflow\python2\2016-09-09.122911\envs>conda info
Warning: could not import binstar_client ('args' object has no attribute 'site')Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.11.0
       python version : 2.7.9.final.0
     requests version : 2.11.1
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Anaconda\.condarc
         offline mode : False
    is foreign system : False
```

bmc2.yml (generated with ``conda env export`` 2.5.2)
```
name: bmc2
dependencies:
- _nb_ext_conf=0.3.0=py27_0
- alabaster=0.7.8=py27_0
- anaconda-client=1.5.1=py27_0
- argcomplete=0.8.4=py27_0
- atom=0.3.9=py27_0
- babel=2.3.3=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bcolz=1.0.0=py27_0
- beautiful-soup=4.3.2=py27_1
- bitarray=0.8.1=py27_1
- blaze=0.10.1=py27_0
- bokeh=0.12.1=py27_0
- boto=2.36.0=py27_0
- bottleneck=1.1.0=np111py27_0
- bzip2=1.0.6=vc9_3
- cdecimal=2.3=py27_1
- certifi=14.05.14=py27_0
- cffi=0.9.2=py27_0
- chest=0.2.3=py27_0
- click=6.6=py27_0
- cloudpickle=0.2.1=py27_0
- clyent=0.3.4=py27_0
- colorama=0.3.7=py27_0
- configobj=5.0.6=py27_0
- configparser=3.5.0=py27_0
- contextlib2=0.5.3=py27_0
- cryptography=0.8=py27_1
- cubes=0.10.2=py27_4
- cycler=0.10.0=py27_0
- cython=0.22=py27_0
- cytoolz=0.8.0=py27_0
- dask=0.10.2=py27_0
- datashape=0.5.2=py27_0
- dateutil=2.4.1=py27_0
- decorator=4.0.10=py27_0
- docutils=0.12=py27_2
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- fastcache=1.0.2=py27_0
- flake8=2.5.1=py27_0
- flask=0.11.1=py27_0
- flask-cors=2.1.2=py27_0
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- futures=3.0.5=py27_0
- get_terminal_size=1.0.0=py27_0
- gevent=1.0.1=py27_0
- gevent-websocket=0.9.3=py27_0
- greenlet=0.4.5=py27_0
- grin=1.2.1=py27_2
- h5py=2.6.0=np111py27_0
- hdf5=1.8.15.1=vc9_4
- heapdict=1.0.0=py27_1
- imagesize=0.7.1=py27_0
- ipykernel=4.3.1=py27_0
- ipython=5.0.0=py27_0
- ipython-notebook=4.0.4=py27_3
- ipython_genutils=0.1.0=py27_0
- ipywidgets=4.1.1=py27_0
- itsdangerous=0.24=py27_0
- jdcal=1.0=py27_0
- jedi=0.9.0=py27_1
- jinja2=2.8=py27_1
- jpeg=8d=vc9_0
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.3.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.1.0=py27_0
- launcher=1.0.0=1
- libpng=1.6.22=vc9_0
- libtiff=4.0.6=vc9_2
- llvmlite=0.12.1=py27_0
- locket=0.2.0=py27_1
- lxml=3.4.2=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mccabe=0.3.1=py27_0
- menuinst=1.0.4=py27_0
- mistune=0.7.2=py27_0
- mkl=11.3.3=1
- mock=1.0.1=py27_0
- msvc_runtime=1.0.1=vc9_0
- multipledispatch=0.4.8=py27_0
- nb_anacondacloud=1.2.0=py27_0
- nb_conda=2.0.0=py27_0
- nb_conda_kernels=2.0.0=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.0.1=py27_0
- nbpresent=3.0.2=py27_0
- networkx=1.11=py27_0
- node-webkit=0.10.1=0
- nose=1.3.4=py27_1
- notebook=4.2.2=py27_0
- numba=0.27.0=np111py27_0
- numexpr=2.6.1=np111py27_0
- numpy=1.11.1=py27_1
- odo=0.5.0=py27_1
- openpyxl=1.8.5=py27_0
- openssl=1.0.2h=vc9_0
- pandas=0.18.1=np111py27_0
- partd=0.3.5=py27_0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- patsy=0.4.1=py27_0
- pep8=1.7.0=py27_0
- pickleshare=0.7.3=py27_0
- pillow=2.7.0=py27_0
- pip=8.1.2=py27_0
- ply=3.4=py27_0
- prompt_toolkit=1.0.3=py27_0
- psutil=4.3.0=py27_0
- py=1.4.31=py27_0
- pyasn1=0.1.7=py27_0
- pycosat=0.6.1=py27_0
- pycparser=2.10=py27_0
- pycrypto=2.6.1=py27_3
- pyflakes=1.2.3=py27_0
- pygments=2.1.3=py27_0
- pyodbc=3.0.7=py27_0
- pyopenssl=0.14=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_7
- pyreadline=2.0=py27_0
- pytables=3.2.2=np111py27_4
- pytest=2.9.2=py27_0
- python=2.7.12=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pywin32=219=py27_0
- pyyaml=3.11=py27_4
- pyzmq=15.4.0=py27_0
- qt=4.8.7=vc9_9
- qtconsole=4.2.1=py27_0
- requests=2.10.0=py27_0
- rope=0.9.4=py27_1
- runipy=0.1.3=py27_0
- scikit-learn=0.17.1=np111py27_1
- scipy=0.18.0=np111py27_0
- seaborn=0.7.1=py27_0
- setuptools=25.1.6=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sockjs-tornado=1.0.1=py27_0
- sphinx=1.4.1=py27_0
- sphinx_rtd_theme=0.1.9=py27_0
- spyder=2.3.9=py27_0
- sqlalchemy=1.0.13=py27_0
- ssl_match_hostname=3.4.0.2=py27_1
- statsmodels=0.6.1=np111py27_1
- sympy=0.7.6=py27_0
- tk=8.5.18=vc9_0
- toolz=0.8.0=py27_0
- tornado=4.4.1=py27_0
- traitlets=4.2.2=py27_0
- ujson=1.33=py27_0
- unicodecsv=0.9.4=py27_0
- vs2008_runtime=9.00.30729.1=2
- wcwidth=0.1.7=py27_0
- werkzeug=0.11.10=py27_0
- wheel=0.29.0=py27_0
- win_unicode_console=0.5=py27_0
- xlrd=0.9.3=py27_0
- xlsxwriter=0.6.7=py27_0
- xlwings=0.3.4=py27_0
- xlwt=0.7.5=py27_0
- zlib=1.2.8=vc9_3
- pip:
  - amqp==1.4.9
  - anyjson==0.3.3
  - apipkg==1.4
  - autopep8==1.2.4
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.3.1
  - cloud==2.8.5
  - ecdsa==0.13
  - execnet==1.4.1
  - graphviz==0.4.10
  - humanize==0.5.1
  - ipython-genutils==0.1.0
  - jupyter-client==4.3.0
  - jupyter-console==5.0.0
  - jupyter-core==4.1.0
  - kombu==3.0.30
  - memoized==0.2
  - modernize==0.5
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - nose-ignore-docstring==0.2
  - paramiko==1.15.2
  - profilehooks==1.8.1
  - prompt-toolkit==1.0.3
  - pydot==1.2.2
  - pymssql==2.1.1
  - pysftp==0.2.8
  - pytest-xdist==1.15.0
  - pythonnet==2.0.0.dev1
  - redis==2.10.5
  - sphinx-rtd-theme==0.1.9
  - suds==0.4
  - tables==3.2.2
  - teamcity-messages==1.19
  - win-unicode-console==0.5
  - xmltodict==0.9.2
prefix: C:\Anaconda\envs\bmc2

```

**Comment by kalefranz** [comment]
Code looks different in the 4.3.x branch now.  Guessing this was fixed a while back.  Something like this wouldn't last long as a bug.
