### ISSUE TITLE
troubles with conda env

### ISSUE THREAD

**Issue by Harvsie82** [conda/conda#2254]
![Uploading image.png…]()

**Comment by mcg1969** [comment]
I'm afraid your image didn't make it. Can you post it as text, please? Make sure to use triple backticks before and after the text block to preserve formatting:

```
Like this
    text
```

**Comment by Harvsie82** [comment]
I'm sorry... thank for your answer.  I really hope you can help me...  I unzipped the source code and the binary extension for windows 64.  Then, I downloaded, installed Anaconda and update it.  Nevertheless when I want to create an environment with _conda env create -f conda_env.yml_.   I got this message:


```[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\harve_000\Anaconda3\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\harve_000\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\Users\harve_000\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\harve_000\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\Users\harve_000\Anaconda3\lib\site-packages\conda_env\installers\pip.py", line 8, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

c:\Windows\gprMax-v.3.0.0b21>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.4
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\harve_000\Anaconda3  (writable)
  default environment : C:\Users\harve_000\Anaconda3
     envs directories : C:\Users\harve_000\Anaconda3\envs
        package cache : C:\Users\harve_000\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False```


Thank you... I really appreciate your help...

**Comment by MarketGarden** [comment]
https://github.com/conda/conda/blame/master/conda_env/pip_util.py#L19
pip-script.py doesn't exist !
What do it?
but there  are pip.exe in folder.

It's  a mistake of design to return None! ^^

same issue under python 2.7
https://github.com/conda/conda/issues/3376

**Comment by tyler-thetyrant** [comment]
Closing outdated.
