### ISSUE TITLE
jupyter installation error

### ISSUE THREAD

**Issue by suhastheju** [conda/conda#2255]
conda install jupyter fails and i have submitted the error report.

muniyas1@pc141:~$ conda install jupyter
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/muniyas1/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 597, in get_index_trap
    return get_index(_args, *_kwargs)
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/utils.py", line 118, in **call**
    value = self.func(_args, *_kw)
  File "/home/muniyas1/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 248, in fetch_index
    import concurrent.futures
  File "/home/muniyas1/.local/lib/python2.7/site-packages/concurrent/futures/**init**.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/muniyas1/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 357
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
muniyas1@pc141:~$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 3.19.1
```

  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/muniyas1/anaconda3  (writable)
  default environment : /home/muniyas1/anaconda3
     envs directories : /home/muniyas1/anaconda3/envs
        package cache : /home/muniyas1/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by mcg1969** [comment]
It looks like your local installation of `futures` is the problem. Do you know that `~/.local` directory is there? 

Please consider temporarily removing `~/.local/lib/python2.7/site-packages/concurrent/futures` from your system. (Move it aside, rename it to `futures2`, whatever). If that fixes the problem then leave it removed :-) In fact, please consider removing any package found in ~/.local that conflicts with any package installed in your Anaconda environment.
