### ISSUE TITLE
updating openssl leaves conda hanging at 100% cpu

### ISSUE THREAD

**Issue by osallou** [conda/conda#2256]
Running conda in a Docker container, I try to install some packages, but it always hangs on openssl update

Here are debug logs

```
bash-4.3# conda update openssl
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /root/miniconda3:

The following packages will be downloaded:

package                    |            build
---------------------------|-----------------
tk-8.5.18                  |                0         1.9 MB
sqlite-3.9.2               |                0         3.9 MB
xz-5.0.5                   |                1         572 KB
yaml-0.1.6                 |                0         246 KB
openssl-1.0.2g             |                0         3.2 MB
python-3.4.4               |                0        15.3 MB
pyyaml-3.11                |           py34_1         330 KB
requests-2.9.1             |           py34_0         647 KB
conda-env-2.4.5            |           py34_0          25 KB
conda-4.0.4                |           py34_0         189 KB
------------------------------------------------------------
                                       Total:        26.2 MB

The following packages will be UPDATED:

conda:     3.8.3-py34_0 --> 4.0.4-py34_0
conda-env: 2.0.1-py34_0 --> 2.4.5-py34_0
openssl:   1.0.1k-0     --> 1.0.2g-0    
python:    3.4.2-0      --> 3.4.4-0     
pyyaml:    3.11-py34_0  --> 3.11-py34_1 
requests:  2.5.1-py34_0 --> 2.9.1-py34_0
sqlite:    3.8.4.1-0    --> 3.9.2-0     
tk:        8.5.15-0     --> 8.5.18-0    
xz:        5.0.5-0      --> 5.0.5-1     
yaml:      0.1.4-0      --> 0.1.6-0     

Fetching packages ...
tk-8.5.18-0.ta 100% |##########################################################| Time: 0:00:00   2.23 MB/s
sqlite-3.9.2-0 100% |##########################################################| Time: 0:00:01   3.06 MB/s
xz-5.0.5-1.tar 100% |##########################################################| Time: 0:00:00 965.47 kB/s
yaml-0.1.6-0.t 100% |##########################################################| Time: 0:00:00 580.31 kB/s
openssl-1.0.2g 100% |##########################################################| Time: 0:00:02   1.47 MB/s
python-3.4.4-0 100% |##########################################################| Time: 0:00:02   5.90 MB/s
pyyaml-3.11-py 100% |##########################################################| Time: 0:00:00 774.14 kB/s
requests-2.9.1 100% |##########################################################| Time: 0:00:00   1.10 MB/s
conda-env-2.4. 100% |##########################################################| Time: 0:00:00 295.63 kB/s
conda-4.0.4-py 100% |##########################################################| Time: 0:00:00 561.43 kB/s
Extracting packages ...
[      COMPLETE      ] |############################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |############################################################################| 100%
Linking packages ...
[openssl-1.0.2g-0 /root/miniconda3/pkgs 1] |############################                            |  50
```

It always remain stuck at openssl update, for a while (already waited for 30 minutes...) at different percentages, and using 100% cpu.

**Comment by osallou** [comment]
Additional info

If I break the install (Ctrl-C), conda is not found anymore, looks like it has been uninstalled...



    ^CTraceback (most recent call last):kgs 1] |#########################                               |  46%
      File "/root/miniconda3/bin/conda", line 5, in <module>
      File "/root/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 202, in main
      File "/root/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 207, in args_func
      File "/root/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 46, in execute
      File "/root/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 412, in install
      File "/root/miniconda3/lib/python3.4/site-packages/conda/plan.py", line 498, in execute_actions
      File "/root/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 140, in execute_instructions
      File "/root/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 84, in LINK_CMD
      File "/root/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 80, in link
      File "/root/miniconda3/lib/python3.4/site-packages/conda/install.py", line 552, in link
      File "/root/miniconda3/lib/python3.4/site-packages/conda/install.py", line 340, in run_script
      File "/root/miniconda3/lib/python3.4/subprocess.py", line 556, in check_call
      File "/root/miniconda3/lib/python3.4/subprocess.py", line 537, in call
      File "/root/miniconda3/lib/python3.4/subprocess.py", line 858, in __init__
      File "/root/miniconda3/lib/python3.4/subprocess.py", line 1417, in _execute_child
      File "/root/miniconda3/lib/python3.4/subprocess.py", line 491, in _eintr_retry_call
KeyboardInterrupt
        
    bash-4.3# conda
    bash: /root/miniconda3/bin/conda: No such file or directory

**Comment by hsrawat** [comment]
I also see extremely high cpu usage with 1.0.2g and a downgrade to 1.0.2d fixes issue.
