### ISSUE TITLE
conda should catch CTRL-C and handle it nicely

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#226]
If I try doing some conda command and then realize that I've made a mistake, or if it is just taking too long, then pressing CTRL-C should not throw a stack-trace back at me, and instead quietly handle the abort, ideally cleaning up any partially executed tasks/installs, or failing that produce an error message that some operation was aborted and there is a risk things are in an inconsistent state (maybe have different signal handlers or error messages depending on what conda is doing).  If we say things are in an inconsistent state, we should provide a "check/cleanup" command to remove any consistencies, if such a condition is even possible.

**Comment by ijstokes** [comment]
@kalefranz and @ilanschnell 3.5 years later and I'd like to propose re-opening this issue.  I feel like the discussion went in the wrong direction.  I still maintain that the average user doing a CTRL-C shouldn't see a stack-trace.  Observe my experience moments ago, aborted when I realized I had typed a "y" into my `python=3.6y` and wanted to do a simple "cancel that":

```
$ conda create --offline -n anatest anaconda=4.3.1 python=3.6y
^CTraceback (most recent call last):
  File "/Users/ijstokes/anaconda/envs/ana43clean/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 111, in _main
    imported = importlib.import_module(module)
  File "/Users/ijstokes/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/main_search.py", line 14, in <module>
    from ..api import get_index
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/gateways/download.py", line 17, in <module>
    from ..connection import CondaSession
  File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/connection.py", line 57, in <module>
    system=platform.system(), kernel=platform.release(),
  File "/Users/ijstokes/anaconda/lib/python3.6/platform.py", line 1035, in system
    return uname().system
  File "/Users/ijstokes/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/ijstokes/anaconda/lib/python3.6/platform.py", line 758, in _syscmd_uname
    output = f.read().strip()
KeyboardInterrupt
```

I will leave it to someone else to decide if this should be re-opened.

**Comment by bryevdv** [comment]
In 3.5 years the stack traces have gotten a lot longer, and conda's reach has etxtended to far more non-experts. So, in that sense, I am now inclined to agree. However, what I'd personally want from a handler is a short printout that states exactly what has or has not occurred at this point (i.e. *"packages have been downloaded but not installed"* or *"The following packages were installed before the command was terminated:"*) That kind of information would be useful and re-assuring. My impression is that conda is now in a better position to offer that kind of information so I would be +1 to reopen this as well.

**Comment by ijstokes** [comment]
@bryevdv that is a good observation.  A CTRL-C could trigger the output information of the last completed stage and the current stage of execution, so the user at least knows how far things got (or where things may have been stuck at the point where they decided just to abort).

I should say: a full stack trace is fine if someone is in `--verbose` mode.

**Comment by stefanseefeld** [comment]
I would expect <ctrl>-C to have conda roll back to the initial state as much as possible, including uninstalling packages that were installed as part of the current command, so ideally there would be nothing needing to be told to end-users. Of course, if there are actions that can't be undone, it's important to let the user know.

**Comment by bryevdv** [comment]
I certainly agree with that, I'm just not sure it's currently feasible to that extent (@kalefranz can correct me) in which case I'd prefer the informative message in the mean time, and rollback later.

**Comment by kalefranz** [comment]
Conda 4.3 *does* attach a signal handler.  Through the 4.3 releases, we scaled it back to only attach during an unlink-link transaction.  There have been endless issues with trying to get this right, and it's still not solved.  See issues

* #5135
* #4045
* #4730 
* #5092
* #4503
* #5132
* #5133
* etc
