### ISSUE TITLE
error updating notebook

### ISSUE THREAD

**Issue by shywel** [conda/conda#2274]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

```
>conda info
> Current condo install:
> 
> platform : osx-64
> conda version : 4.0.4
> conda-build version : 1.18.2
> python version : 3.5.1.final.0
> requests version : 2.9.1
> root environment : /Users/username/anaconda  (writable)
> default environment : /Users/username/anaconda
> envs directories : /Users/username/anaconda/envs
> package cache : /Users/username/anaconda/pkgs
> channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
>                         https://repo.continuum.io/pkgs/free/noarch/
>                         https://repo.continuum.io/pkgs/pro/osx-64/
>                         https://repo.continuum.io/pkgs/pro/noarch/
> config file : None
> is foreign system : False
```

```
> Traceback (most recent call last):
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 180, in args_fun
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 48, in execute
>     install.install(args, parser, 'update')
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 423, in install
>     try:
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/plan.py", line 538, in execute_actions
>     with History(actions[inst.PREFIX]):
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 148, in execute_instructions
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
>     def UNLINK_CMD(state, arg):
>   File "/Users/username/anaconda/lib/python3.5/site-packages/conda/install.py", line 692, in unlink
>     if 'icon' in meta_dict:
> FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/anaconda/conda-meta/conda-3.19.1-py35_0.json'

```

**Comment by kalefranz** [comment]
@shywel what was the command you were trying to run?

**Comment by shywel** [comment]
@kalefranz from launcher, click Update notebook.
That happened when I tried to update notebook and spyder, at the same time. Spyder was updated; but notebook didn't and threw the error. Now I started Anaconda Launcher, tried again and ran well
