### ISSUE TITLE
activate on master is broken in OSX

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2284]
@msarahan I'm on master, and I get:
```
$ source activate koo
path:usage: conda [-h] [-V] [--debug] command ...
conda: error: argument command: invalid choice: '..changeps1' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'run', 'config', 'init', 'clean', 'package', 'bundle')
prepending /Users/ilan/python/envs/koo and /Users/ilan/python/envs/koo/cmd and /Users/ilan/python/envs/koo/bin to PATH
-bash: awk: command not found
-bash: dirname: command not found
Traceback (most recent call last):
  File "/Users/ilan/python/bin/conda", line 4, in <module>
    from conda.cli.main import main
  File "/Users/ilan/conda/conda/__init__.py", line 19, in <module>
    __version__ = get_version(__file__, __name__)
  File "/Users/ilan/python/lib/python2.7/site-packages/auxlib/packaging.py", line 93, in get_version
    if is_git_repo(here):
  File "/Users/ilan/python/lib/python2.7/site-packages/auxlib/packaging.py", line 70, in is_git_repo
    return call(('git', 'rev-parse'), cwd=path) == 0
  File "/Users/ilan/python/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/Users/ilan/python/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/ilan/python/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
```
It is true that the new activate scripts depend on `awk` and `dirname`?

**Comment by msarahan** [comment]
> the new activate scripts

The usage of awk and dirname are not new:

https://github.com/conda/conda-env/blame/develop/bin/activate#L32

That's conda-env, of course, but that's where the scripts that are now in conda came from.

Something else is going wrong.  It might be a bug in the path translation stuff.  It is supposed to just be a pass-through on *nix to *nix, but I did see some issues like this in fixing the tests.  I'll look into it and see if I can improve the tests to catch whatever is happening here.
