### ISSUE TITLE
Help me fix this error after making the update...

### ISSUE THREAD

**Issue by gcicceri** [conda/conda#2286]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 631, in link
    os.makedirs(dst_dir)
  File "//anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '//anaconda/lib/python2.7/site-packages/traitlets/utils/tests'

**Comment by mcg1969** [comment]
It looks like we have a few issues with root installs of Anaconda. I would strongly suggest installing Anaconda in your home directory instead, and not as root, until this is figured out.

But just to complete the issue report, can you offer the full output of `conda info` as requested in the error report?

**Comment by gcicceri** [comment]
I installed everything, and now it seems to work!!
