### ISSUE TITLE
Unexpected error during unlinking packages while installing Pyserial to anaconda

### ISSUE THREAD

**Issue by arcunique** [conda/conda#2294]
While unlinking packages during installation of pyserial to anaconda in Win x64 system by command " conda install -c https://conda.anaconda.org/anaconda pyserial " I got an error saying following traceback..

Traceback (most recent call last):
  File "C:\Program Files (x86)\anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\cli\main.py", line 180, in args_func
    args.func(args, p)
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Program Files (x86)\anaconda\lib\site-packages\conda\install.py", line 714, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'C:\Program Files (x86)\anaconda\conda-meta\conda-3.19.1-py27_0.json'

Using command 'conda info' I got :
C:\Program Files (x86)\anaconda>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : win-64
    conda version : 3.19.1
```

  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Program Files (x86)\anaconda  (writable)
  default environment : C:\Program Files (x86)\anaconda
     envs directories : C:\Program Files (x86)\anaconda\envs
        package cache : C:\Program Files (x86)\anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Kindly suggest some way to resolve this issue....

**Comment by speterson-usgs** [comment]
I got an identical error just now while attempting to use conda to install the fiona package from IOOS. Please help. Traceback and conda info below: 

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 180, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 45, in e
xecute
    install.install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 423, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 538, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 148, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 95, in UNLIN
K_CMD
    install.unlink(state['prefix'], arg)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 714, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'C:\\Anaconda2\\conda-meta\\conda-3.19
.1-py27_0.json'

CONDA INFO

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
