### ISSUE TITLE
error in updating spyder

### ISSUE THREAD

**Issue by BioFin** [conda/conda#2303]
I got the following message when updating spyder:-

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 180, in args_func
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 48, in execute
    name,
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 423, in install
    try:
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/plan.py", line 538, in execute_actions
    with History(actions[inst.PREFIX]):
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 148, in execute_instructions
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    def UNLINK_CMD(state, arg):
  File "/Users/priyachoudhry/anaconda/lib/python3.4/site-packages/conda/install.py", line 692, in unlink
    if 'icon' in meta_dict:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/priyachoudhry/anaconda/conda-meta/conda-3.19.1-py34_0.json'

**Comment by ccordoba12** [comment]
I think your Anaconda installation is corrupted. I'd suggest you to uninstall and reinstall Anaconda again :-)
