### ISSUE TITLE
BUG: conda search numpy=1.11.0 --spec gives traceback

### ISSUE THREAD

**Issue by jreback** [conda/conda#2324]
so this might not be the correct syntax, but this gives a traceback:

```
[jreback-~/pandas] conda list conda
# packages in environment at /Users/jreback/miniconda:
#
anaconda-client           1.0.2                    py27_0  
conda                     4.0.5                    py27_0  
conda-build               1.19.2                   py27_0  
conda-env                 2.4.5                    py27_0  
```

```
[jreback-~/pandas] conda search numpy=1.11.0 --spec
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/jreback/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 120, in execute
    execute_search(args, parser)
  File "/Users/jreback/miniconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 215, in execute_search
    if ms and name != ms.name:
AttributeError: 'str' object has no attribute 'name'
```

further some related issues: #1772, #2046 
- the `--spec` is confusing, shouldn't `conda search 'numpy=1.11'` just _work_? (with or without the quotes, e.g. maybe you want ``conda search 'numpy=1.11*` for a full package spec
- `--help` should give some examples

**Comment by kalefranz** [comment]
Unable to reproduce.  Must be fixed.

```
$ python -m conda search numpy=1.11.0 --spec
Fetching package metadata .........
numpy                        1.11.0             py35_nomkl_0  defaults        [nomkl]
                             1.11.0                   py27_0  defaults
                             1.11.0             py34_nomkl_0  defaults        [nomkl]
                             1.11.0             py27_nomkl_0  defaults        [nomkl]
                             1.11.0                   py35_0  defaults
                             1.11.0                   py34_0  defaults
                             1.11.0                   py34_1  defaults
                             1.11.0             py27_nomkl_1  defaults        [nomkl]
                             1.11.0             py35_nomkl_1  defaults        [nomkl]
                             1.11.0                   py35_1  defaults
                             1.11.0             py34_nomkl_1  defaults        [nomkl]
                             1.11.0                   py27_1  defaults
                             1.11.0                   py34_2  defaults
                             1.11.0             py27_nomkl_2  defaults        [nomkl]
                             1.11.0                   py27_2  defaults
                             1.11.0             py35_nomkl_2  defaults        [nomkl]
                             1.11.0                   py35_2  defaults
                             1.11.0             py34_nomkl_2  defaults        [nomkl]
```
