### ISSUE TITLE
insecure string pickle

### ISSUE THREAD

**Issue by adib** [conda/conda#2335]
Include the output of the command 'conda info' in your report.

```
Traceback (most recent call last):
  File "/Users/adib/dato/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/adib/dato/anaconda/lib/python2.7/site-packages/conda/cli/main_run.py", line 105, in execute
    execute_command(args.package, prefix, args.arguments, args.json)
  File "/Users/adib/dato/anaconda/lib/python2.7/site-packages/conda/cli/main_run.py", line 116, in execute_command
    cmd, prefix=prefix, additional_args=additional_args, inherit=not json)
  File "/Users/adib/dato/anaconda/lib/python2.7/site-packages/conda/misc.py", line 342, in execute_in_environment
    stdin=stdin, stdout=stdout, stderr=stderr)
  File "/Users/adib/dato/anaconda/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/Users/adib/dato/anaconda/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/Users/adib/dato/anaconda/lib/python2.7/pickle.py", line 1388, in loads
    return Unpickler(file).load()
  File "/Users/adib/dato/anaconda/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/Users/adib/dato/anaconda/lib/python2.7/pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

  athena:bin adib$ ./conda info
  Current conda install:

```
           platform : osx-64
      conda version : 4.0.5
conda-build version : 1.14.1
     python version : 2.7.11.final.0
   requests version : 2.3.0
   root environment : /Users/adib/dato/anaconda  (writable)
default environment : /Users/adib/dato/anaconda
   envs directories : /Users/adib/dato/anaconda/envs
      package cache : /Users/adib/dato/anaconda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
  is foreign system : False
```

**Comment by kalefranz** [comment]
Hi @adib,
What command did you run that resulted in that stack trace?
