### ISSUE TITLE
clone error

### ISSUE THREAD

**Issue by jimsrc** [conda/conda#2342]
#### conda create --name root_ii --clone root

+++++++++++++++++++++++++++++++
Traceback (most recent call last):
  File "/home/jim/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/home/jim/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'vim-debug-1.5.4-py27_0.tar.bz2'
+++++++++++++++++++++++++++++++

#### And my `conda info` thing is:
+++++++++++++++++++++++++++++++
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.8.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/jim/anaconda  (writable)
  default environment : /home/jim/anaconda
     envs directories : /home/jim/anaconda/envs
        package cache : /home/jim/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/r/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/jim/.condarc
    is foreign system : False
+++++++++++++++++++++++++++++++

**Comment by grlee77** [comment]
I encountered this problem too.  see the same issue reported in #2315

**Comment by kalefranz** [comment]
@mcg1969 This ticket remains open as something we need to fix for the 4.1 release.

The following should be a simple way to reproduce this issue

    conda create -n anaconda-test-1 anaconda
    conda create -n anaconda-test-2 --clone anaconda-test-1

Here's the stack trace I currently get

    Traceback (most recent call last):
      File "/conda/bin/conda", line 6, in <module>
        sys.exit(conda.cli.main())
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
        args_func(args, p)
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
        args.func(args, p)
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
        install.install(args, parser, 'create')
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/cli/install.py", line 225, in install
        clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/cli/install.py", line 83, in clone
        quiet=quiet, index=index)
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
        sorted_dists = r.dependency_sort(dists)
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/resolve.py", line 748, in dependency_sort
        depends = lookup(value)
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/resolve.py", line 743, in lookup
        return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
      File "/Users/kfranz/.conda/lib/python2.7/site-packages/conda/resolve.py", line 577, in ms_depends
        rec = self.index[fkey]
    KeyError: '<unknown>::libdynd-0.7.2-0.tar.bz2'

Note that the following succeeds for me on OSX right now

    conda create -n numpy-test-1 numpy
    conda create -n numpy-test-2 --clone numpy-test-1

My best guess is that it has something to do with the mismatch between repodata.json from repo.continuum.io and what's recorded locally...

**Comment by mcg1969** [comment]
Can you see if mgrant/local fixes this?

**Comment by mcg1969** [comment]
Even if it doesn't, that's probably the branch I should work from.

**Comment by mcg1969** [comment]
I just tested `mgrant/local` with this test:
```
conda create -n atest1 anaconda
conda create -n atest2 --clone atest1
```
And it worked. I'll look at the `clone` command a bit more closely to make sure it's using my recent code properly.

**Comment by mcg1969** [comment]
OK, cloning my root environment failed. Good to know

**Comment by mcg1969** [comment]
`clone_env` doesn't use the same code path as `explicit` or `install_local_packages`. That seems... unfortunate. :-)

**Comment by mcg1969** [comment]
OK, `clone_env` works if *every* channel represented among the environment's packages is in my default channel list. Otherwise, it we get a `KeyError` for every package whose channel is not represented.

**Comment by kalefranz** [comment]
Should be fixed with https://github.com/conda/conda/pull/2428 and `4.1.0rc2`.

    conda config --add channels conda-team
    conda update conda conda-env
