### ISSUE TITLE
Master broken

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2358]
When doing `conda install dill` (or actually any other package) I get:
```
Traceback (most recent call last):
  File "/Users/ilan/python/envs/py26/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ilan/conda/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/ilan/conda/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/ilan/conda/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/Users/ilan/conda/conda/cli/install.py", line 321, in install
    update_deps=args.update_deps)
  File "/Users/ilan/conda/conda/plan.py", line 432, in install_actions
    smh = r.dependency_sort(must_have)
  File "/Users/ilan/conda/conda/resolve.py", line 751, in dependency_sort
    depends = lookup(value)
  File "/Users/ilan/conda/conda/resolve.py", line 746, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/Users/ilan/conda/conda/resolve.py", line 580, in ms_depends
    rec = self.index[fkey]
KeyError: 'tbb-4.4_20151115-0.tar.bz2'
```
On version 4.0.5 all is fine.

**Comment by mcg1969** [comment]
I've reproduced this. Will fix ASAP.

**Comment by mcg1969** [comment]
The `mgrant/channelfix` branch does not have this problem, a PR is coming soon.

**Comment by mcg1969** [comment]
#2369
