### ISSUE TITLE
Conda python env can't import ssl on Linux

### ISSUE THREAD

**Issue by traff** [conda/conda#2381]
I create a conda environment with a Miniconda version 3.19.0 using a command:
```
conda create -p <path> -y -f python=2.7
```

When I launch a python python in that environment and try to import ssl I get a following error:

```
>>> import ssl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/ssl.py", line 97, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: /home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/lib-dynload/_ssl.so: undefined symbol: SSLv2_method
```

This also results in not being able to use pip as it throws an error:
```
Traceback (most recent call last):
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/bin/pip", line 4, in <module>
    import pip
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/site-packages/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/site-packages/pip/vcs/subversion.py", line 9, in <module>
    from pip.index import Link
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/site-packages/pip/index.py", line 30, in <module>
    from pip.wheel import Wheel, wheel_ext
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/site-packages/pip/wheel.py", line 39, in <module>
    from pip._vendor.distlib.scripts import ScriptMaker
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/site-packages/pip/_vendor/distlib/scripts.py", line 14, in <module>
    from .compat import sysconfig, detect_encoding, ZipFile
  File "/home/builduser/buildAgent/work/c2d8dfcc72679944/community/python/setup-test-environment/build/envs/django16/lib/python2.7/site-packages/pip/_vendor/distlib/compat.py", line 31, in <module>
    from urllib2 import (Request, urlopen, URLError, HTTPError,
ImportError: cannot import name HTTPSHandler

```

My OS is Ubuntu 12.04.3 LTS.

**Comment by traff** [comment]
P.S. I have already installed openssl, libssl-dev and python-openssl. That didn't help.

**Comment by kalefranz** [comment]
Hi @traff, you shouldn't need those ssl deb packages; conda isn't dependent on them.  Can you run `conda update conda` to update to the latest (`4.0.5`), and then try again?

Also, after you create your environment, can you provide the output of

    conda list -p <path> 

You *should* just get a list of packages compatible with

    kfranz@0283:~/continuum/conda *pr1550 ❯ conda info python=2.7.11
    Fetching package metadata: ......

    python 2.7.11 0
    ---------------
    file name   : python-2.7.11-0.tar.bz2
    name        : python
    version     : 2.7.11
    build number: 0
    build string: 0
    channel     : defaults
    size        : 9.9 MB
    date        : 2015-12-06
    license     : PSF
    md5         : 6abc954cff8bc02c343a08ed2a0d3fb0
    installed environments:
        /Users/kfranz/.conda
        /Users/kfranz/.conda/envs/my-new-environment
        /Users/kfranz/.conda/envs/numpy110
        /Users/kfranz/.conda/envs/temp27
        /Users/kfranz/.conda/envs/test-environment
        /Users/kfranz/.conda/envs/test1
    dependencies:
        openssl 1.0.2*
        readline 6.2*
        sqlite
        tk 8.5*
        zlib 1.2*
        pip

**Comment by traff** [comment]
Hi @kalefranz,
thanks for the prompt reply.

I was using Miniconda2-latest from http://repo.continuum.io/miniconda/ and conda -V shows 3.19.0 as a version. Probably that is another thing.

Installing 4.0.5 explicitly makes no difference for me - the same error.

conda list -p <path> shows

./miniconda2/bin/conda list -p ~/test
# packages in environment at /home/builduser/test:
#
python                    2.7.11                        0

**Comment by kalefranz** [comment]
I'm seeing Miniconda2 latest as http://repo.continuum.io/miniconda/Miniconda2-4.0.5-Linux-x86_64.sh with md5 `42dac45eee5e58f05f37399adda45e85`.  But yeah I think that might be beside the issue.

Oh!  Your problem is `-f`.  And so you're *only* getting conda python, and not all of its dependencies.

Can you try just

    conda create -p <path> -y python=2.7

**Comment by traff** [comment]
Thanks, Kale, that helped. Didn't mention that -f implies --no-deps.
