### ISSUE TITLE
conda update conda failure

### ISSUE THREAD

**Issue by gcreager** [conda/conda#2386]
An unexpected error has occurred, please consider sending the                                                                                                                   |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/scratch/software/anaconda/bin/conda", line 5, in <module>

  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/scratch/software/anaconda/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/scratch/software/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/scratch/software/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/scratch/software/anaconda/include/openssl/opensslconf.h'

and now conda is missing from anaconda/bin

**Comment by tyler-thetyrant** [comment]
Closing outdated.
