### ISSUE TITLE
conda install -h errors in master

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#2395]
```
condamaster=$PYTHONPATH=. conda install -h
Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/Documents/Continuum/conda/conda/cli/main.py", line 108, in main
    args = p.parse_args()
  File "/Users/aaronmeurer/Documents/Continuum/conda/conda/cli/conda_argparse.py", line 169, in parse_args
    return super(ArgumentParser, self).parse_args(*args, **kwargs)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1726, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1946, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1923, in consume_positionals
    take_action(action, args)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1129, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1758, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1964, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1904, in consume_optional
    take_action(action, args, option_string)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1832, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 1016, in __call__
    parser.print_help()
  File "/Users/aaronmeurer/Documents/Continuum/conda/conda/cli/conda_argparse.py", line 159, in print_help
    super(ArgumentParser, self).print_help()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 2358, in print_help
    self._print_message(self.format_help(), file)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 2342, in format_help
    return formatter.format_help()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 278, in format_help
    help = self._root_section.format_help()
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 208, in format_help
    func(*args)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 208, in format_help
    func(*args)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 515, in _format_action
    help_text = self._expand_help(action)
  File "/Users/aaronmeurer/anaconda/lib/python3.5/argparse.py", line 602, in _expand_help
    return self._get_help_string(action) % params
KeyError: 'defaults'
```

```
condamaster=$PYTHONPATH=. conda info -a
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : 0+unknown
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/aaronmeurer/anaconda  (writable)
  default environment : /Users/aaronmeurer/anaconda
     envs directories : /Users/aaronmeurer/anaconda/envs
        package cache : /Users/aaronmeurer/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/pyne/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/pyne/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/xonsh/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/xonsh/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/r/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/asmeurer/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/asmeurer/noarch/
          config file : /Users/aaronmeurer/.condarc
    is foreign system : False

# conda environments:
#
_test                    /Users/aaronmeurer/anaconda/envs/_test
fortune                  /Users/aaronmeurer/anaconda/envs/fortune
gcc                      /Users/aaronmeurer/anaconda/envs/gcc
intel                    /Users/aaronmeurer/anaconda/envs/intel
python2                  /Users/aaronmeurer/anaconda/envs/python2
python34                 /Users/aaronmeurer/anaconda/envs/python34
sympy-release            /Users/aaronmeurer/anaconda/envs/sympy-release
root                  *  /Users/aaronmeurer/anaconda

sys.version: 3.5.1 |Anaconda custom (x86_64)| (defaul...
sys.prefix: /Users/aaronmeurer/anaconda
sys.executable: /Users/aaronmeurer/anaconda/bin/python3
conda location: /Users/aaronmeurer/Documents/Continuum/conda/conda
conda-build: /Users/aaronmeurer/anaconda/bin/conda-build
conda-convert: /Users/aaronmeurer/anaconda/bin/conda-convert
conda-develop: /Users/aaronmeurer/anaconda/bin/conda-develop
conda-env: /Users/aaronmeurer/anaconda/bin/conda-env
conda-index: /Users/aaronmeurer/anaconda/bin/conda-index
conda-inspect: /Users/aaronmeurer/anaconda/bin/conda-inspect
conda-metapackage: /Users/aaronmeurer/anaconda/bin/conda-metapackage
conda-pipbuild: /Users/aaronmeurer/anaconda/bin/conda-pipbuild
conda-server: /Users/aaronmeurer/anaconda/bin/conda-server
conda-sign: /Users/aaronmeurer/anaconda/bin/conda-sign
conda-skeleton: /Users/aaronmeurer/anaconda/bin/conda-skeleton
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /Users/aaronmeurer/anaconda/bin:/Users/aaronmeurer/anaconda3/bin:/Users/aaronmeurer/anaconda/envs/hunspell/bin:/Users/aaronmeurer/Library/Haskell/bin:/Users/aaronmeurer/anaconda/envs/emacs/bin:/Users/aaronmeurer/Documents/emacs/lib-src:/Users/aaronmeurer/Documents/emacs/src:/sw/bin:/sw/sbin:/Users/aaronmeurer/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/Trolltech/Qt-4.4.3/bin:/Library/Frameworks/Maple.framework/Versions/Current/bin:/usr/texbin:/usr/local/texlive/2015/bin/x86_64-darwin:/Users/aaronmeurer/Documents/git-hg/bin:/Users/aaronmeurer/Documents/depot_tools:/Users/aaronmeurer/Documents/hub:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.6/bin:/Library/Frameworks/Python.framework/Versions/2.5/bin:/Library/Frameworks/Python.framework/Versions/3.0/bin:/Library/Frameworks/Python.framework/Versions/3.2/bin:/Applications/Sage-5.2-OSX-64bit-10.6.app/Contents/Resources/sage:/Users/aaronmeurer/Documents/cask/bin:/usr/local/go/bin
PYTHONHOME: <not set>
PYTHONPATH: .

License directories:
    /Users/aaronmeurer/.continuum
    /Users/aaronmeurer/Library/Application Support/Anaconda
    /Users/aaronmeurer/anaconda/licenses
License files (license*.txt):
Package/feature end dates:
```

**Comment by kalefranz** [comment]
Fixed.
