### ISSUE TITLE
source activate fails

### ISSUE THREAD

**Issue by groutr** [conda/conda#2397]
using conda master (commit 51655ed8aa90e5115b6d947d473fdaf4360e2ddc).

```
❯ source activate py35
prepending /Users/xxxxx/miniconda/envs/py35/bin to PATH
Traceback (most recent call last):
  File "/Users/xxxxx/miniconda/bin/conda", line 9, in <module>
    load_entry_point('conda', 'console_scripts', 'conda')()
  File "/Users/xxxxx/continuum/projects/conda/conda/cli/main.py", line 48, in main
    activate.main()
  File "/Users/xxxxx/continuum/projects/conda/conda/cli/activate.py", line 179, in main
    path = "(({})) {}".format(os.path.split(env_path)[-1], path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u276f' in position 24: ordinal not in range(128)
```

Git bisect singled out af196f0f68f0ec0c8c61c7bf30e0ce255827cde8.

After attempting to debug this, my best guess is it is choking on the unicode '>' character in my prompt.

/cc @msarahan

**Comment by kalefranz** [comment]
Still an issue in 4.3.17 @groutr?
