### ISSUE TITLE
Conda Error: Too many levels of symbolic links

### ISSUE THREAD

**Issue by whart222** [conda/conda#2399]
I get the following error installing sympy on MacOS (inside a virtual environment).

$conda install --show-channel-urls sympy
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/wehart/home/src/python27:

The following packages will be downloaded:

| package | build |
| --- | --- |
| python-2.7.11 | 0         9.9 MB  defaults |
| mpmath-0.19 | py27_0         867 KB  defaults |
| sympy-1.0 | py27_0         5.6 MB  defaults |

```
------------------------------------------------------------
                                       Total:        16.4 MB
```

The following NEW packages will be INSTALLED:

```
mpmath: 0.19-py27_0 defaults
python: 2.7.11-0    defaults
sympy:  1.0-py27_0  defaults
```

Proceed ([y]/n)? 

Fetching packages ...
python-2.7.11- 100% |#############################################################| Time: 0:00:04   2.56 MB/s
mpmath-0.19-py 100% |#############################################################| Time: 0:00:00 993.47 kB/s
sympy-1.0-py27 100% |#############################################################| Time: 0:00:01   3.27 MB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                          |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/wehart/src/python27/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/Users/wehart/home/src/python27/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 62] Too many levels of symbolic links: '/Users/wehart/home/src/python27/bin/python2.7'
hart2013:scripts wehart$

**Comment by kalefranz** [comment]
Are you still seeing this error in recent versions of conda?  Latest is 4.3.17.
