### ISSUE TITLE
Annaconda error

### ISSUE THREAD

**Issue by gtyopal** [conda/conda#2400]
Traceback (most recent call last):
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 96, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Applications/anaconda/anaconda/lib/python2.7/site-packages/conda/install.py", line 707, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/Applications/anaconda/anaconda/conda-meta/qtconsole-4.2.0-py27_0.json'

**Comment by kalefranz** [comment]
Not enough context to do much.  Old ticket, so closing.  Please file a new ticket if you're still having similar issues with recent versions of conda.
