### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by nivnoy** [conda/conda#2401]
Hello,
I get an error when trying to create a new environment, during the packages linking process. I've tried re-installing anaconda and using different version but the problem remains. Can anyone help? 
This is the traceback (conda info below):

```
Traceback (most recent call last):
  File "C:\Users\Niv Noy\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\install.py", line 667, in link
    if not run_script(prefix, dist, 'post-link'):
  File "C:\Users\Niv Noy\Anaconda3\lib\site-packages\conda\install.py", line 377, in run_script
    subprocess.check_call(args, env=env)
  File "C:\Users\Niv Noy\Anaconda3\lib\subprocess.py", line 579, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Niv Noy\Anaconda3\lib\subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Niv Noy\Anaconda3\lib\subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Niv Noy\Anaconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified


C:\WINDOWS\system32>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.1
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\Niv Noy\Anaconda3  (writable)
  default environment : C:\Users\Niv Noy\Anaconda3
     envs directories : C:\Users\Niv Noy\Anaconda3\envs
        package cache : C:\Users\Niv Noy\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
