### ISSUE TITLE
pydas-1.0.2 install failed on linux 32 bit system

### ISSUE THREAD

**Issue by Jingbo-Wang** [conda/conda#2408]
Dear Developers,

I try to install pydas-1.0.2 using the following commands:
    conda install -c rmg pydas=1.0.2  _or_
    conda install -c nickvandewiele pydas=1.0.2
both are failed with the error:

Traceback (most recent call last):
  File "/usr/local/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/usr/local/anaconda2/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/local/anaconda2/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/usr/local/anaconda2/pkgs/pydas-1.0.2-py27_0/lib/gcc/i686-pc-linux-gnu/4.8.2/crt1.o

Run 'conda info' on the system gives:
Current conda install:

```
         platform : linux-32
    conda version : 4.0.5
```

  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /usr/local/anaconda2  (writable)
  default environment : /usr/local/anaconda2
     envs directories : /usr/local/anaconda2/envs
        package cache : /usr/local/anaconda2/pkgs
         channel URLs : file://usr/local/anaconda2/conda-bld/linux-32/
                        file://usr/local/anaconda2/conda-bld/noarch/
                        https://repo.continuum.io/pkgs/free/linux-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /root/.condarc
    is foreign system : False

If you want more information, kindly let me know. Thanks for your time.

Best,

Jingbo Wang

**Comment by msarahan** [comment]
Those appear to be corrupt packages.  Pydas should absolutely not be
including crt1.o in its files.  I recommend that you either contact the
package authors, or find a recipe and build it yourself.

Either way, this could be a bug in conda build that resulted in erroneous
contents. Please report back with whatever you find, so that we might be
able to isolate that issue, if it exists.
