### ISSUE TITLE
IRIS PASSCAL module failing to install using conda

### ISSUE THREAD

**Issue by mat2py** [conda/conda#2409]
Module from: https://www.passcal.nmt.edu/content/how-do-i-install-passoft

Ran using:
`conda install ~/Downloads/PASSOFT-LATEST.x86_64.tar.bz2`

```
An unexpected error has occurred, please consider sending the             |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/morgan/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 202, in install
    verbose=not args.quiet)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 267, in install_local_packages
    force_extract_and_link(dists, prefix, verbose=verbose)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 54, in force_extract_and_link
    execute_actions(actions, verbose=verbose)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/install.py", line 621, in link
    files = list(yield_lines(join(info_dir, 'files')))
  File "/home/morgan/anaconda2/lib/python2.7/site-packages/conda/install.py", line 216, in yield_lines
    for line in open(path):
IOError: [Errno 2] No such file or directory: '/home/morgan/anaconda2/pkgs/PASSOFT-LATEST.x86_64/info/files'
```

Then the system info:

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.5
```

  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/morgan/anaconda2  (writable)
  default environment : /home/morgan/anaconda2
     envs directories : /home/morgan/anaconda2/envs
        package cache : /home/morgan/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by msarahan** [comment]
Conda packages are .tar.bz2 files, but not all .tar.bz2 files are conda
packages.  The downloads on that page are not conda packages.  You need to
follow directions on that page to install the extracted contents of that
tarball.  Anaconda/miniconda may provide an easy way to fulfill
prerequisites, though.

HTH,
Michael

**Comment by mat2py** [comment]
Hey msarahan, thanks for the info. I assumed this was a technique to use conda to install any module - apparently not! I have about reached the end of the rope with this module, the instructions are very short and it's been touching on 2 days of effort without being able to get it installed.

Thanks anyway!
