### ISSUE TITLE
Intermittent issue with repodata.json download

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2412]
Traceback (most recent call last):
      File "C:\projects\conda\tests\test_cli.py", line 151, in test_info
        self.assertIn('conda', res)
      File "C:\miniconda\lib\unittest\case.py", line 803, in assertIn
        self.fail(self._formatMessage(msg, standardMsg))
      File "C:\miniconda\lib\unittest\case.py", line 410, in fail
        raise self.failureException(msg)
    AssertionError: 'conda' not found in {u'error_type': None, u'error': u"Invalid index file: http://repo.continuum.io/pkgs/free/win-32/repodata.json.bz2: couldn't find end of stream"}

Detailed test failure at: https://ci.appveyor.com/project/ironmancio54716/conda/build/1.0.874/job/ufkc3esirjjlchj8#L477

**Comment by kalefranz** [comment]
CC @mcg1969

**Comment by kalefranz** [comment]
Appveyor seems to have a lot of intermittent issues lately.  I don't think this is something we should really address here.  Maybe in Milestone 4.2 add some retries to failed downloads or something...
