### ISSUE TITLE
Conda install r-essentials failed

### ISSUE THREAD

**Issue by jasenasia** [conda/conda#2414]
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\response.py", line 311, in read
    flush_decoder = True
  File "C:\Anaconda2\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(10054, 'An existing connection was forcib
ly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))

**Comment by mingwandroid** [comment]
Was this just an intermittent connectivity problem?
