### ISSUE TITLE
Issue - Memory Crash

### ISSUE THREAD

**Issue by vins123123123** [conda/conda#2417]
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in e
xecute
    install.install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 424, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 539, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 149, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 92, in LINK_
CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 695, in link
    create_meta(prefix, dist, info_dir, meta_dict)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 307, in create_me
ta
    meta = json.load(fi)
  File "C:\Anaconda3\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Anaconda3\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

[Anaconda3] C:\Users\v.krishnaswamy>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : win-64
    conda version : 4.0.5
```

  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
Fixed long ago.
