### ISSUE TITLE
Error installing Jupyter 

### ISSUE THREAD

**Issue by mmocco** [conda/conda#2419]
something is wrong.

```
$ conda info
Current condo install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/MoccoTron/Libraries  (writable)
  default environment : /Users/MoccoTron/Libraries
     envs directories : /Users/MoccoTron/Libraries/envs
        package cache : /Users/MoccoTron/Libraries/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

Error from install:
```
Traceback (most recent call last):
  File "/Users/MoccoTron/Libraries/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/Users/MoccoTron/Libraries/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dat)
  File "/Users/MoccoTron/Libraries/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dat)
  File "/Users/MoccoTron/Libraries/lib/python2.7/shutil.py", line 82, in copy file
    with open(src, 'rb') as force
IOError: [Errno 2] No such file or directory: u'/Users/MoccoTron/Libraries/pkgs/pyqt-4.11.4-py27_1/lib/python2.7/site-packages/PyQt4/pyqtconfig.py'
```:

**Comment by kalefranz** [comment]
I think `conda clean --all` should help you here.  Looks like something got corrupted in your package cache.  Just run that and try again.
