### ISSUE TITLE
conda update from 1.8.0 without sudo borked shebang line of conda

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#242]
I just tried to update conda. I forgot to put `sudo` in front of my conda command on the first try, so I got a write permission error.  When I tried to run it again it appears that the conda shebang line was overwritten with something bogus:

```
#!/opt/anaconda1anaconda2anaconda3/bin/python
```

I now have to fix it by hand -- not a big deal, but I would guess that I won't be the only person to make this mistake and run into this hassle.  Below is the exact trace of commands I executed and the output.

```bash
 magnetawan:Continuum $ which python
/opt/anaconda/bin/python
 magnetawan:Continuum $ conda install mayavi

Package plan for installation in environment /opt/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    apptools-4.2.0             |           py27_0         271 KB
    conda-1.8.1                |           py27_0         116 KB
    configobj-4.7.2            |           py27_0          48 KB
    envisage-4.3.0             |           py27_0         266 KB
    mayavi-4.3.0               |       np17py27_0         9.5 MB
    pyface-4.3.0               |           py27_0         692 KB
    traits-4.3.0               |           py27_0         392 KB
    traitsui-4.3.0             |           py27_0         821 KB
    vtk-5.10.1                 |           py27_0        28.8 MB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    conda-1.8.0                |           py27_0

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    apptools-4.2.0             |           py27_0
    conda-1.8.1                |           py27_0
    configobj-4.7.2            |           py27_0
    envisage-4.3.0             |           py27_0
    mayavi-4.3.0               |       np17py27_0
    pyface-4.3.0               |           py27_0
    traits-4.3.0               |           py27_0
    traitsui-4.3.0             |           py27_0
    vtk-5.10.1                 |           py27_0

Proceed ([y]/n)? n

 magnetawan:Continuum $ conda update conda
Updating conda environment at /opt/anaconda

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-1.8.1                |           py27_0         116 KB

The following packages will be UN-linked:

    package                    |            build
    ---------------------------|-----------------
    conda-1.8.0                |           py27_0

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    conda-1.8.1                |           py27_0

Proceed ([y]/n)? y

Fetching packages ...
conda-1.8.1-py27_0.tar.bz2 100% |####################| Time: 0:00:00 189.43 kB/s
Extracting packages ...
[      COMPLETE      ] |##################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the#############| 100%
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues"


Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 151, in main
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 81, in execute
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 444, in execute_actions
    execute_plan(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 328, in execute_plan
    install.link(config.pkgs_dir, prefix, arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 299, in link
    _link(src, dst)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 97, in _link
    shutil.copy2(src, dst)
  File "/opt/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/opt/anaconda/lib/python2.7/site-packages/conda/__init__.py'
 magnetawan:Continuum $ sudo conda update conda
Password:
 magnetawan:Continuum $ sudo conda update conda
 magnetawan:Continuum $ conda version
-bash: /opt/anaconda/bin/conda: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory
```

**Comment by ijstokes** [comment]
I have to assume that this has been resolved by now, so I'm closing this.
