### ISSUE TITLE
Traceback as install Jupyter

### ISSUE THREAD

**Issue by fsha-src** [conda/conda#2431]
C:\Anaconda>conda install jupyter

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>

  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main

  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in ex
ecute
    'install',
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 278, in instal
l
    continue
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 436, in execute_actio
ns

  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 418, in execute_plan
    continue
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 374, in link
    continue
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 486, in link
    t.close()
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 210, in update_pre
fix
    os.rmdir(path)
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\Anaconda\"Library\bi
n\pyuic4.bat"'

**Comment by fsha-src** [comment]
C:\Anaconda>conda info
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 99, in main
    from conda.cli import main_search
  File "C:\Anaconda\lib\site-packages\conda\cli\main_search.py", line 12, in <m
dule>
    from conda.misc import make_icon_url
  File "C:\Anaconda\lib\site-packages\conda\misc.py", line 19, in <module>
    from conda.api import get_index
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 9, in <module>
    from conda.fetch import fetch_index
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "C:\Anaconda\lib\site-packages\conda\connection.py", line 24, in <module

    import requests
ImportError: No module named requests

**Comment by msarahan** [comment]
It looks like you have quotes in some PATH entry that should not be there, or some script has them done inappropriately.  Can you tell us more about what Anaconda installation you started from?  What steps have you tried to update conda and/or anaconda?  Did any of those steps fail?

Without requests, I'm afraid your installation might be corrupt.  You might need to reinstall Anaconda/Miniconda.
