### ISSUE TITLE
'RuntimeError: maximum recursion depth exceeded' on 'conda install -c bioconda r-bit64'

### ISSUE THREAD

**Issue by A1M1** [conda/conda#2435]
'conda install -c bioconda r-bit64' produces many errors, ending in 'RuntimeError: maximum recursion depth exceeded'. This issue had been resolved earlier but seems to have creeped up again.

Stacktrace:

> conda install -c bioconda r-bit64
> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata: ......
> Solving package specifications: .
> An unexpected error has occurred, please consider sending the
> following traceback to the conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> Include the output of the command 'conda info' in your report.
> 
> 
> Traceback (most recent call last):
>   File "/home/XXXX/bin/conda", line 6, in <module>
>     sys.exit(main())
>   File "/home/XXXX/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
>     args_func(args, p)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
>     args.func(args, p)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
>     install.install(args, parser, 'install')
>   File "/home/XXXX/lib/python2.7/site-packages/conda/cli/install.py", line 334, in install
>     update_deps=args.update_deps)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/plan.py", line 413, in install_actions
>     pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 875, in install
>     pkgs = self.solve(specs, len0=len0, returnall=returnall)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 909, in solve
>     dists, new_specs = self.get_dists(specs)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 399, in get_dists
>     specs, removes, optional, features = self.verify_specs(specs)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 391, in verify_specs
>     bad_deps.extend(self.invalid_chains(ms, filter))
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 359, in invalid_chains
>     return chains_(spec)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
> ...
> ...
> ... `goes on for a while`
> ...
> ...
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 351, in chains_
>     if spec.name == top or self.valid(spec, filter):
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 299, in valid
>     return v_(spec)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 287, in v_
>     return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 290, in v_ms_
>     return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
>   File "/home/XXXX/lib/python2.7/site-packages/conda/resolve.py", line 553, in find_matches
>     ms = MatchSpec(ms)
> RuntimeError: maximum recursion depth exceeded
> 
> 

Related issue: #1748

**Comment by A1M1** [comment]
Nevermind. I was using an old version of conda which led to this error.
