### ISSUE TITLE
Some files not being linked in multi-user conda installation

### ISSUE THREAD

**Issue by jimm-domingo** [conda/conda#2437]
We have a Miniconda3 installation with Python 3.5:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /pkg/miniconda3/root  (writable)
  default environment : /pkg/miniconda3/root
     envs directories : /pkg/conda/envs
        package cache : /pkg/conda/envs/.pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /pkg/miniconda3/root/.condarc
    is foreign system : False
```

In the root environment, a `pip search` works fine.  However, after we create a new environment with just Python 3.5:

```
$ conda create -n test-env python=3.5
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /pkg/conda/envs/test-env:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-0     
    pip:        8.1.1-py35_1 
    python:     3.5.1-0      
    readline:   6.2-2        
    setuptools: 20.7.0-py35_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py35_0
    xz:         5.0.5-1      
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate test-env
#
# To deactivate this environment, use:
# $ source deactivate
#
```

`pip search` fails in that environment with this error:

```
$ source activate test-env
discarding /pkg/miniconda3/root/bin from PATH
prepending /pkg/conda/envs/test-env/bin to PATH
(test-env)$ pip search invoke
Exception:
Traceback (most recent call last):
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 292, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
    conn.connect()
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 252, in connect
    ssl_version=resolved_ssl_version)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 294, in ssl_wrap_socket
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/commands/search.py", line 43, in run
    pypi_hits = self.search(query, options)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/commands/search.py", line 60, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/pkg/conda/envs/test-env/lib/python3.5/xmlrpc/client.py", line 1091, in __call__
    return self.__send(self.__name, args)
  File "/pkg/conda/envs/test-env/lib/python3.5/xmlrpc/client.py", line 1431, in __request
    verbose=self.__verbose
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/download.py", line 764, in request
    headers=headers, stream=True)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: [Errno 2] No such file or directory
```

Investigation revealed that File Not Found Error occurs because the environment is missing this file:

```
/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem
```

This `cacert.perm` file is in the root environment, as well as several other environments that were created previously:

```
$ pwd
/pkg/conda/envs
$ for x in *; do echo $x ; ls $x/lib/python*/site-packages/pip/_vendor/requests/
*.pem ; done

_build
_build/lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem
MDT
MDT/lib/python2.7/site-packages/pip/_vendor/requests/cacert.pem
mdttest
mdttest/lib/python2.7/site-packages/pip/_vendor/requests/cacert.pem
py34
py34/lib/python3.4/site-packages/pip/_vendor/requests/cacert.pem
python-gdal
python-gdal/lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem
test-env
ls: cannot access test-env/lib/python*/site-packages/pip/_vendor/requests/*.pem: No such file or directory
```

We've confirmed that the `cacert.pem` file is still in the package cache:

```
$ find /pkg/conda/envs/.pkgs/pip-8.1.1-py35_1/ -name "*.pem"
/pkg/conda/envs/.pkgs/pip-8.1.1-py35_1/lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem
```

Any idea why this file is not being copied or linked into a new environment?

**Comment by jimm-domingo** [comment]
While looking into another conda issue, we gained some more insight into this issue.  The `cacert.pem` mentioned above in the package cache is owned by the developer who first installed that package, but it's not group-writable:

    $ cd /pkg/conda/envs/.pkgs/pip-8.1.1-py35_1/lib/python3.5/site-packages/pip/_vendor/requests
    $ ls -l cacert.pem
    $ -rw-r--r-- 5 wilma devteam 344712 Mar 18 11:20 cacert.pem

Lack of write access isn't due to her umask, but because the file is not group-writable in the package's tarball:

    $ cd /pkg/conda/envs/.pkgs
    $ tar -tvjf pip-8.1.1-py35_1.tar.bz2 | fgrep cacert.pem
    -rw-r--r-- ilan/ilan    344712 2016-03-18 11:20 lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem

So if Wilma creates a conda environment, it will have a hard link to this `.pem` file.  However, if Betty creates a matching environment -- either by using the same set of package specifications, or by using `--clone` option -- then her environment won't have the `.pem` file.  Conda cannot create a hard link for a developer to a read-only file owned by another developer.  Unfortunately, **conda is silent about this failure**; it doesn't report that it couldn't create the link.

We've discovered other types of files (e.g., shared libraries) in some other packages that are missing from our conda environments.  The common trait among all these files = each one is not group-writable in their respective package tarballs.

**Comment by jimm-domingo** [comment]
Ran the same `create` command above with the `--debug` option.  Confirmed that link errors are occurring for several files that are read-only for the group and owned by someone else:

_(output trimmed and edited for conciseness and readability)_

```
$ conda --debug create -n test-env python=3.5
[... DEBUG: and INFO: statements omitted...]

Package plan for installation in environment /pkg/conda/envs/test-env:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-1     
    pip:        8.1.2-py35_0 
    python:     3.5.1-0      
    readline:   6.2-2        
    setuptools: 22.0.5-py35_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py35_0
    xz:         5.0.5-1      
    zlib:       1.2.8-3      

Proceed ([y]/n)? y

DEBUG:conda.instructions: PREFIX('/pkg/conda/envs/test-env')
DEBUG:conda.instructions: PRINT('Linking packages ...')
Linking packages ...
INFO:print:Linking packages ...

DEBUG:conda.instructions: LINK('sqlite-3.13.0-0 /pkg/conda/envs/.pkgs 1')
INFO:progress.update:('sqlite', 2)                                        |  20%
DEBUG:conda.install:pkgs_dir='/pkg/conda/envs/.pkgs',
                    prefix='/pkg/conda/envs/test-env',
                    dist='sqlite-3.13.0-0',
                    linktype=1
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/sqlite-3.13.0-0/bin/sqlite3',
      dst='/pkg/conda/envs/test-env/bin/sqlite3',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/sqlite-3.13.0-0/include/sqlite3.h',
      dst='/pkg/conda/envs/test-env/include/sqlite3.h',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/sqlite-3.13.0-0/include/sqlite3ext.h',
      dst='/pkg/conda/envs/test-env/include/sqlite3ext.h',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/sqlite-3.13.0-0/lib/libsqlite3.a',
      dst='/pkg/conda/envs/test-env/lib/libsqlite3.a',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/sqlite-3.13.0-0/lib/libsqlite3.so.0.8.6',
      dst='/pkg/conda/envs/test-env/lib/libsqlite3.so.0.8.6',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))

DEBUG:conda.instructions: LINK('tk-8.5.18-0 /pkg/conda/envs/.pkgs 1')
INFO:progress.update:('tk', 3)########                                    |  30%
DEBUG:conda.install:pkgs_dir='/pkg/conda/envs/.pkgs',
                    prefix='/pkg/conda/envs/test-env',
                    dist='tk-8.5.18-0',
                    linktype=1
DEBUG:conda.instructions: LINK('xz-5.0.5-1 /pkg/conda/envs/.pkgs 1')
INFO:progress.update:('xz', 4)#############                               |  40%
DEBUG:conda.install:pkgs_dir='/pkg/conda/envs/.pkgs',
                    prefix='/pkg/conda/envs/test-env',
                    dist='xz-5.0.5-1',
                    linktype=1
[ ... ]
DEBUG:conda.instructions: LINK('zlib-1.2.8-3 /pkg/conda/envs/.pkgs 1')
INFO:progress.update:('zlib', 5)################                          |  50%
DEBUG:conda.install:pkgs_dir='/pkg/conda/envs/.pkgs',
                    prefix='/pkg/conda/envs/test-env',
                    dist='zlib-1.2.8-3',
                    linktype=1
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/zlib-1.2.8-3/include/zconf.h',
      dst='/pkg/conda/envs/test-env/include/zconf.h',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/zlib-1.2.8-3/include/zlib.h',
      dst='/pkg/conda/envs/test-env/include/zlib.h',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/zlib-1.2.8-3/lib/libz.a',
      dst='/pkg/conda/envs/test-env/lib/libz.a',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/zlib-1.2.8-3/lib/libz.so.1.2.8',
      dst='/pkg/conda/envs/test-env/lib/libz.so.1.2.8',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
[ ... ]
DEBUG:conda.instructions: LINK('pip-8.1.2-py35_0 /pkg/conda/envs/.pkgs 1')
INFO:progress.update:('pip', 9)#####################################      |  90%
DEBUG:conda.install:pkgs_dir='/pkg/conda/envs/.pkgs',
                    prefix='/pkg/conda/envs/test-env',
                    dist='pip-8.1.2-py35_0',
                    linktype=1
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/PKG-INFO',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/PKG-INFO',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/SOURCES.txt',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/SOURCES.txt',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/dependency_links.txt',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/dependency_links.txt',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/entry_points.txt',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/entry_points.txt',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/not-zip-safe',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/not-zip-safe',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/requires.txt',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/requires.txt',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/top_level.txt',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip-8.1.2-py3.5.egg-info/top_level.txt',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip/_vendor/distlib/_backport/sysconfig.cfg',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/distlib/_backport/sysconfig.cfg',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip/_vendor/distlib/t32.exe',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/distlib/t32.exe',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip/_vendor/distlib/t64.exe',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/distlib/t64.exe',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip/_vendor/distlib/w32.exe',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/distlib/w32.exe',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip/_vendor/distlib/w64.exe',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/distlib/w64.exe',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))
ERROR:conda.install:failed to link (
      src='/pkg/conda/envs/.pkgs/pip-8.1.2-py35_0/lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem',
      dst='/pkg/conda/envs/test-env/lib/python3.5/site-packages/pip/_vendor/requests/cacert.pem',
      type=1,
      error=PermissionError(1, 'Operation not permitted'))

[      COMPLETE      ]|###################################################| 100%
INFO:progress.stop:None
DEBUG:conda.instructions: SYMLINK_CONDA('/pkg/miniconda3/root')
#
# To activate this environment, use:
# $ source activate test-env
#
# To deactivate this environment, use:
# $ source deactivate
#
```

**Comment by jimm-domingo** [comment]
Created a system test using `make` and `docker` to replicate this behavior.
https://github.com/jimm-domingo/conda-issue-2437

**Comment by jimm-domingo** [comment]
Created a system test using `make` and `docker` to replicate this behavior.
https://github.com/jimm-domingo/conda-issue-2437

**Comment by mcg1969** [comment]
Related: https://github.com/conda/conda/issues/2846

**Comment by kalefranz** [comment]
Per discussion in #2846, should now be resolved.
