### ISSUE TITLE
Unexpected error during pandas update

### ISSUE THREAD

**Issue by RflCsd** [conda/conda#2438]
C:\Users\Rafaël\Downloads>conda install pandas
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Anaconda2:

The following packages will be downloaded:

| package | build |
| --- | --- |
| pandas-0.18.1 | np111py27_0         6.4 MB |

The following packages will be UPDATED:

```
pandas: 0.18.0-np110py27_0 --> 0.18.1-np111py27_0
```

Proceed ([y]/n)? y

Fetching packages ...
pandas-0.18.1- 100% |###############################| Time: 0:00:35 193.17 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in e
xecute
    install.install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 424, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 539, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 149, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 92, in LINK_
CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 631, in link
    os.makedirs(dst_dir)
  File "C:\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] AccÞs refus: 'C:\Anaconda2\Lib/site-packages/pandas'

C:\Users\Rafaël\Downloads>

**Comment by msarahan** [comment]
What does AccÞs refus:  mean?  I suspect it might mean permission error.
Did you have any python process with pandas imported running?  If you
aren't completely certain, restart your computer and try the update again.

**Comment by RflCsd** [comment]
I have no idea what "AccÞs refus" means. Nevertheless, restarting my computer and updating again worked.

Many thanks !
