### ISSUE TITLE
Invalid data stream error

### ISSUE THREAD

**Issue by coluigbo** [conda/conda#2453]
I am getting the following errors on launch. 

Traceback (most recent call last):
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main_run.py", line 81, in execute
    for pkg in get_package_versions(args.package, args.offline):
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/api.py", line 188, in get_package_versions
    index = get_index(offline=offline)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/api.py", line 43, in get_index
    unknown=unknown)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/utils.py", line 118, in **call**
    value = self.func(_args, *_kw)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/Applications/anaconda/lib/python3.5/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/Applications/anaconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/Applications/anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(_self.args, *_self.kwargs)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 65, in func
    res = f(_args, *_kwargs)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 103, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
  File "/Applications/anaconda/lib/python3.5/bz2.py", line 348, in decompress
    res = decomp.decompress(data)
OSError: Invalid data stream

**Comment by kalefranz** [comment]
On launch? Of what command?

Going to close this ticket actually.  If you're having similar issues with recent versions of conda, please file a new ticket with an updated stack trace.
