### ISSUE TITLE
AssertionError in `conda update -f conda`

### ISSUE THREAD

**Issue by tdhopper** [conda/conda#2465]
My conda install [is broken](https://groups.google.com/a/continuum.io/forum/#!topic/conda/CRoQ9i6s-dc) and, in trying to fix it, i ran `conda update -f conda`. I got

```
Traceback (most recent call last):
  File "/Users/tdhopper/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/cli/install.py", line 307, in install
    update_deps=args.update_deps)
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/plan.py", line 448, in install_actions
    force=force, always_copy=always_copy)
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/plan.py", line 307, in ensure_linked_actions
    elif install.try_hard_link(fetched_dir, prefix, dist):
  File "/Users/tdhopper/miniconda/lib/python3.5/site-packages/conda-4.0.5-py3.5.egg/conda/install.py", line 521, in try_hard_link
    assert isfile(src), src
AssertionError: /Users/tdhopper/python-3.5.1-0/info/index.json
```

```
10:03 $ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /Users/tdhopper/miniconda  (writable)
  default environment : /Users/tdhopper/miniconda
     envs directories : /Users/tdhopper/miniconda/envs
        package cache : /Users/tdhopper/miniconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/distributions/osx-64/
                        https://conda.anaconda.org/distributions/noarch/
                        https://conda.anaconda.org/datamicroscopes/osx-64/
                        https://conda.anaconda.org/datamicroscopes/noarch/
          config file : /Users/tdhopper/.condarc
    is foreign system : False
```

**Comment by mcg1969** [comment]
May I ask why you used `-f` here?

**Comment by tdhopper** [comment]
@mcg1969 I think I bumped the `-f` as I was banging my head against my keyboard.

**Comment by tyler-thetyrant** [comment]
Closing outdated.
