### ISSUE TITLE
unexpected error updating Spyder

### ISSUE THREAD

**Issue by gabrielepompa88** [conda/conda#2469]
Traceback (most recent call last):
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/Users/gabrielepompa/anaconda/lib/python2.7/site-packages/conda/install.py", line 692, in unlink
    with open(meta_path) as fi:
IOError: [Errno 2] No such file or directory: '/Users/gabrielepompa/anaconda/envs/Py_3_5_1/conda-meta/babel-2.2.0-py35_0.json'

**Comment by tyler-thetyrant** [comment]
Closing outdated.
