### ISSUE TITLE
can't install ETE Toolkits in conda?

### ISSUE THREAD

**Issue by stephenwei** [conda/conda#2486]
http://etetoolkit.org/download/
# Install ETE

conda install -c etetoolkit ete3 ete3_external_apps

Fetching packages ...
An unexpected error has occurred, please consider sending the0:01:46  26.88 kB/s
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/nan/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/home/nan/anaconda2/lib/python2.7/contextlib.py", line 35, in **exit**
    self.gen.throw(type, value, traceback)
  File "/home/nan/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 256, in _error_catcher
    self._connection.close()
AttributeError: 'bool' object has no attribute 'close'

nan@wei:~$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.6
```

  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/nan/anaconda2  (writable)
  default environment : /home/nan/anaconda2
     envs directories : /home/nan/anaconda2/envs
        package cache : /home/nan/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
This just looks like an intermittent HTTP error.
