### ISSUE TITLE
Cannot build from tarball

### ISSUE THREAD

**Issue by opoplawski** [conda/conda#2490]
I downloaded https://github.com/conda/conda/archive/4.0.6.tar.gz but build fails with:
~~~~~
+ /usr/bin/python2 setup.py build
Traceback (most recent call last):
  File "setup.py", line 31, in <module>
    import conda  # NOQA
  File "/export/home/orion/redhat/conda-4.0.6/conda-4.0.6/conda/__init__.py", line 19, in <module>
    __version__ = get_version(__file__)
  File "/export/home/orion/redhat/conda-4.0.6/conda-4.0.6/auxlib/packaging.py", line 90, in get_version
    return _get_version_from_version_file(path) or _get_version_from_git_tag(path)
  File "/export/home/orion/redhat/conda-4.0.6/conda-4.0.6/auxlib/packaging.py", line 69, in _get_version_from_git_tag
    m = DESCRIBE_REGEX.match(_git_describe_tags(path).decode('utf-8') or '')
  File "/export/home/orion/redhat/conda-4.0.6/conda-4.0.6/auxlib/packaging.py", line 59, in _git_describe_tags
    raise CalledProcessError(response.rc, response.stderr)
subprocess.CalledProcessError: Command 'fatal: Not a git repository (or any of the parent directories): .git
' returned non-zero exit status 128
~~~~~
I don't see a recent tar ball on pypi either.

**Comment by opoplawski** [comment]
Hmm, different error now with 4.2.3 from github:
```
UPDATING build/lib/conda/__init__.py
WRITING build/lib/conda/.version with version None
Traceback (most recent call last):
  File "setup.py", line 89, in <module>
    zip_safe=False,
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/export/home/orion/redhat/conda/conda-4.2.3/conda/_vendor/auxlib/packaging.py", line 206, in run
    write_version_file(target_dir, self.distribution.metadata.version)
  File "/export/home/orion/redhat/conda/conda-4.2.3/conda/_vendor/auxlib/packaging.py", line 198, in write_version_file
    f.write(version)
TypeError: expected a character buffer object
```

**Comment by opoplawski** [comment]
It appears I can work around this by writing the version to conda/.version, e.g.:
```
echo %{version} > conda/.version
```

**Comment by kalefranz** [comment]
For all of our CI, the git tag is the source of truth for version information rather than something hard-coded in a file somewhere. 

Github does not associate the git tag with the release tarbal. 

So yes, you need to provide this information another way. And that other way is writing the version to the .version file.

Of course our own preferred way is to use git to clone the repo (even if a shallow clone)  at the point of the git tag version you want to build.

**Comment by kalefranz** [comment]
The git tag is not associated with the tarball from github. So yes, you need to provide this information another way. And that other way is writing the version to the .version file. You got it!
