### ISSUE TITLE
conda is missing after update

### ISSUE THREAD

**Issue by alexjironkin** [conda/conda#2492]
Hi,

I was trying to install a package and conda failed during update to conda. Now I don't have `conda` in bin folder.

```
conda install mpi4py
Fetching package metadata: ....
Solving package specifications: .
Package plan for installation in environment /phengs/hpc_software/anaconda/2.2.0:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mpich2-1.4.1p1             |                0         2.6 MB
    openssl-1.0.2h             |                0         3.2 MB
    mpi4py-2.0.0               |           py27_1         1.7 MB
    setuptools-20.7.0          |           py27_0         453 KB
    wheel-0.29.0               |           py27_0          81 KB
    conda-4.0.6                |           py27_0         185 KB
    pip-8.1.1                  |           py27_1         1.5 MB
    ------------------------------------------------------------
                                           Total:         9.7 MB

The following NEW packages will be INSTALLED:

    mpi4py:     2.0.0-py27_1 
    mpich2:     1.4.1p1-0    

The following packages will be UPDATED:

    conda:      3.19.1-py27_0 --> 4.0.6-py27_0 
    openssl:    1.0.2f-0      --> 1.0.2h-0     
    pip:        8.0.2-py27_0  --> 8.1.1-py27_1 
    setuptools: 19.6.2-py27_0 --> 20.7.0-py27_0
    wheel:      0.26.0-py27_1 --> 0.29.0-py27_0

Proceed ([y]/n)? 

Fetching packages ...
mpich2-1.4.1p1 100% |##########################################################################################################################################| Time: 0:00:03 737.06 kB/s
openssl-1.0.2h 100% |##########################################################################################################################################| Time: 0:00:04 690.64 kB/s
mpi4py-2.0.0-p 100% |##########################################################################################################################################| Time: 0:00:02 677.13 kB/s
setuptools-20. 100% |##########################################################################################################################################| Time: 0:00:00 574.17 kB/s
wheel-0.29.0-p 100% |##########################################################################################################################################| Time: 0:00:00 308.65 kB/s
conda-4.0.6-py 100% |##########################################################################################################################################| Time: 0:00:00 425.50 kB/s
pip-8.1.1-py27 100% |##########################################################################################################################################| Time: 0:00:02 645.61 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#############################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                                                       |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/phengs/hpc_software/anaconda/2.2.0/bin/conda", line 5, in <module>

  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/cli/main.py", line 201, in main
    args_func(args, p)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/cli/common.py", line 612, in inner
    return func(args, parser)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/cli/install.py", line 413, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/plan.py", line 527, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/install.py", line 606, in link
    _link(src, dst, lt)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/site-packages/conda/install.py", line 136, in _link
    shutil.copy2(src, dst)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/phengs/hpc_software/anaconda/2.2.0/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/phengs/hpc_software/anaconda/2.2.0/etc/mpe_log.conf'
```

Any ideas?

**Comment by shwina** [comment]
Same problem. How am I supposed to install `conda` now?

**Comment by rilut** [comment]
Same problem. How am I supposed to install conda now after missing in Windows?

**Comment by TomTom101** [comment]
+1 couldn't find a solution other than reinstall all.

**Comment by olalakul** [comment]
Same problem on MacOS. I fixed it as proposed [here](https://github.com/conda/conda/issues/3437) by kalefranz.

**Comment by kalefranz** [comment]
Once you have a version of conda 4.3.x on your machine, I'm very hopeful that conda will no longer be "uninstalling itself."
