### ISSUE TITLE
conda create --clone fails with keyerror

### ISSUE THREAD

**Issue by pjc42** [conda/conda#2510]
> conda create -n ptport --clone porttoy
> Using Anaconda Cloud api site https://api.anaconda.org
> Fetching package metadata: ....
> src_prefix: 'b:\python\anaconda3_2.5.0\envs\porttoy'
> dst_prefix: 'b:\python\anaconda3_2.5.0\envs\ptport'
> Packages: 9
> Files: 126
> An unexpected error has occurred, please consider sending the
> following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "b:\python\anaconda3_2.5.0\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\cli\install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\cli\install.py", line 84, in clone
    quiet=quiet, index=index)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "b:\python\anaconda3_2.5.0\lib\site-packages\conda\resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'msvc_runtime-1.0.1-0.tar.bz2'

**Comment by GavinHuttley** [comment]
I second this. Here's the traceback

```bash
$ conda create --name pp --clone standard
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
src_prefix: '/Users/gavin/miniconda2/envs/standard'
dst_prefix: '/Users/gavin/miniconda2/envs/pp'
Packages: 101
Files: 16
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/gavin/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/Users/gavin/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'r-mgcv-1.8_9-r3.2.2_0a.tar.bz2'
```
And the condo info output.
```bash
[gavin@blah ~/DevRepos]
 $ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.7
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/gavin/miniconda2  (writable)
  default environment : /Users/gavin/miniconda2
     envs directories : /Users/gavin/miniconda2/envs
        package cache : /Users/gavin/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by NPounder** [comment]
I am having a similar issue with conda version 4.0.8

```
 $ conda create --name testgdal --clone sentoolbox
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
src_prefix: '/home/nicola2/anaconda2/envs/sentoolbox'
dst_prefix: '/home/nicola2/anaconda2/envs/testgdal'
Packages: 187
Files: 867
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/nicola2/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/home/nicola2/anaconda2/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'glymur-0.8.4-py27_0.tar.bz2'

```
conda info output:

```
             platform : linux-64
        conda version : 4.0.8
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/nicola2/anaconda2  (writable)
  default environment : /home/nicola2/anaconda2
     envs directories : /home/nicola2/anaconda2/envs
        package cache : /home/nicola2/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
I have one non conda package installed (http://step.esa.int/main/third-party-plugins-2/sen2cor/) and had to install/upgrade three packages to get that working:
```
conda install -n sentoolbox krb5 
conda install -n sentoolbox libgdal=2.0.0
conda install -n sentoolbox numpy 
```

I think there is an old, closed issue related to this, unfortunately I can't find it now. From that I couldn't understand how to proceed though, is there something I need to do to get this working or some situations that clone won't work in?

**Comment by kalefranz** [comment]
I believe this is fixed in recent versions of conda.  Latest is 4.3.17.  If not, please file a new issue with an updated stack trace.
