### ISSUE TITLE
pip install conda is broken 

### ISSUE THREAD

**Issue by lowks** [conda/conda#2515]
When I try to do `pip install conda`, I get the following error:

```
Collecting conda
  Downloading conda-4.0.5.tar.gz (125kB)
    100% |████████████████████████████████| 133kB 851kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-TORz6k/conda/setup.py", line 30, in <module>
        import auxlib  # a build-time dependency only
    ImportError: No module named auxlib
```

**Comment by tyler-thetyrant** [comment]
We don't support `pip isntall conda`. Please follow the official conda installation guide.
