### ISSUE TITLE
unexpected issue when updating

### ISSUE THREAD

**Issue by rsieg** [conda/conda#2522]
Traceback (most recent call last):
  File "/home/bob/anaconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/bob/anaconda3/lib/python3.5/site-packages/conda/install.py", line 631, in link
    os.makedirs(dst_dir)
  File "/home/bob/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/bob/anaconda3/lib/python3.5/site-packages/pandas/indexes'

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.5
```

  conda-build version : 1.18.1
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/bob/anaconda3  (writable)
  default environment : /home/bob/anaconda3
     envs directories : /home/bob/anaconda3/envs
        package cache : /home/bob/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by tyler-thetyrant** [comment]
Closing outdated.
