### ISSUE TITLE
conda copy fails, due to mayavi dependency 

### ISSUE THREAD

**Issue by michael-karotsieris** [conda/conda#2523]
$ conda create --name flowers --clone mbatlas Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
src_prefix: '/home/mkarots/miniconda2/envs/mbatlas'
dst_prefix: '/home/mkarots/miniconda2/envs/flowers'
Packages: 34
Files: 0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/mkarots/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/home/mkarots/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'mayavi-4.4.3-py27_0.tar.bz2'
mkarots@mkarots-300E4A-300E5A-300E7A-3430EA-3530EA:~/CPython-interpreter/python-int$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.0.6
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/mkarots/miniconda2  (writable)
  default environment : /home/mkarots/miniconda2
     envs directories : /home/mkarots/miniconda2/envs
        package cache : /home/mkarots/miniconda2/pkgs
         channel URLs : https://conda.anaconda.org/spacy/linux-64/
                        https://conda.anaconda.org/spacy/noarch/
                        https://conda.anaconda.org/numba/linux-64/
                        https://conda.anaconda.org/numba/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/mkarots/.condarc
    is foreign system : False

**Comment by michael-karotsieris** [comment]
The problem came because mayavi4.4.3 is not in the main channel of anaconda but in the channel http://conda.anaconda.org/menpo . Adding the channel in the anaconda configuration solved this issue for me. 

conda config --add channels http://conda.anaconda.org/menpo
