### ISSUE TITLE
conda update anaconda fails after El Capitan upgrade

### ISSUE THREAD

**Issue by justinlent** [conda/conda#2528]
```

Traceback (most recent call last):
  File "/Users/justinlent/python/anaconda210/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/conda/install.py", line 634, in link
    os.makedirs(dst_dir)
  File "/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/justinlent/python/anaconda210/anaconda/lib/python2.7/site-packages/IPython/core/tests/daft_extension'


```

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.0.6
  conda-build version : 1.8.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/justinlent/python/anaconda210/anaconda  (writable)
  default environment : /Users/justinlent/python/anaconda210/anaconda
     envs directories : /Users/justinlent/python/anaconda210/anaconda/envs
        package cache : /Users/justinlent/python/anaconda210/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by justinlent** [comment]
I'll just close this as I simply re-installed anaconda from scratch and seems to have addressed my issue.  Though it would be nice to get all my previous environments back from my old install
