### ISSUE TITLE
unexpected error  when installing mingw,

### ISSUE THREAD

**Issue by onetwowt** [conda/conda#2535]
after i type the commond:
conda install mingw libpython
An unexpected error occurred.  (Win7 x64)

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in e
xecute
    install.install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 240, in insta
ll
    prefix=prefix)
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 595, in get_in
dex_trap
    return get_index(_args, *_kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\api.py", line 45, in get_index
    for dist, info in iteritems(install.linked_data(prefix)):
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 517, in linked_da
ta
    res[fn[:-5]] = json.load(open(join(meta_dir,fn)))
  File "C:\Anaconda3\lib\json__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Anaconda3\lib\json__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 132 column 53 (
char 8061)

**Comment by kalefranz** [comment]
This error was fixed in a conda patch release.
