### ISSUE TITLE
conda fails to create a clone of root

### ISSUE THREAD

**Issue by rkedward** [conda/conda#2539]
> > ./conda info
> > Using Anaconda Cloud api site https://api.anaconda.org
> > Current conda install:

```
         platform : linux-64
    conda version : 4.0.6
```

  conda-build version : 1.11.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /p/ret/rettools/AnacondaPython/Python2  (writable)
  default environment : /p/ret/rettools/AnacondaPython/Python2
     envs directories : /p/ret/rettools/AnacondaPython/Python2/envs
        package cache : /p/ret/rettools/AnacondaPython/Python2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /p/ret/rettools/AnacondaPython/Python2/.condarc
    is foreign system : False

> > ./conda create --name 43.0 --clone root
> > Using Anaconda Cloud api site https://api.anaconda.org
> > Fetching package metadata: ....
> > src_prefix: '/p/ret/rettools/AnacondaPython/Python2'
> > dst_prefix: '/p/ret/rettools/AnacondaPython/Python2/envs/43.0'
> > Packages: 215
> > Files: 12256
> > An unexpected error has occurred, please consider sending the
> > following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "./conda", line 6, in <module>
    sys.exit(main())
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/p/ret/rettools/AnacondaPython/Python2/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'odo-0.4.1-py27_0.tar.bz2'

**Comment by mcg1969** [comment]
Do you happen to recall which channel you downloaded `odo` from? The problem here is that this version is not in the default set of channels. If you add a channel with `odo-0.4.1-py27_0.tar.bz2` to your channel list, this is likely to work.

Conda 4.1 does a better job of managing "off-channel" installs during the cloning process, so I anticipate this problem is solved there.

**Comment by mcg1969** [comment]
Alternatively, try upgrading your version of `odo` and then clone.

**Comment by kalefranz** [comment]
Tarball conda package installs have been fixed.
