### ISSUE TITLE
Odd exception

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2557]
I'm getting this using AE-Repo:

```
       python version : 2.7.11.final.0                                                                                                                      
     requests version : 2.9.1                                                                                                                               
     root environment : /opt/wakari/anaconda  (writable)                                                                                                    
  default environment : /projects/wakari/test3/envs/default                                                                                                 
     envs directories : /projects/wakari/test3/envs                                                                                                         
                        /opt/wakari/anaconda/envs                                                                                                           
        package cache : /projects/wakari/test3/envs/.pkgs                                                                                                   
                        /opt/wakari/anaconda/pkgs                                                                                                           
         channel URLs : http://107.23.174.114:8080/conda/anaconda/linux-64/                                                                                 
                        http://107.23.174.114:8080/conda/anaconda/noarch/                                                                                   
          config file : /opt/wakari/anaconda/.condarc                                                                                                       
    is foreign system : False                                                                                                                               

wakari@ip-172-31-51-86:/projects/wakari/test3$ conda create -n 3.5 python=3.5                                                                               
Using Anaconda Cloud api site https://api.anaconda.org                                                                                                      
Fetching package metadata: An unexpected error has occurred, please consider sen                                                                            
following traceback to the conda GitHub issue tracker at:                                                                                                   

    https://github.com/conda/conda/issues                                                                                                                   

Include the output of the command 'conda info' in your report.                                                                                              


wakari@ip-172-31-51-86:/projects/wakari/test3$ conda create -n 3.5 python=3.5                                                                               
Using Anaconda Cloud api site https://api.anaconda.org                                                                                                      
Fetching package metadata: An unexpected error has occurred, please consider sending the                                                                    
following traceback to the conda GitHub issue tracker at:                                                                                                   

    https://github.com/conda/conda/issues                                                                                                                   

Include the output of the command 'conda info' in your report.                                                                                              


Traceback (most recent call last):                                                                                                                          
  File "/projects/wakari/test3/envs/default/bin/conda", line 5, in <module>                                                                                 
    sys.exit(main())                                                                                                                                        
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main                                                              
    args_func(args, p)                                                                                                                                      
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func                                                         
    args.func(args, p)                                                                                                                                      
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute                                                     
    install.install(args, parser, 'create')                                                                                                                 
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 239, in install                                                        
    offline=args.offline)                                                                                                                                   
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 597, in get_index_trap                                                  
    return get_index(*args, **kwargs)                                                                                                                       
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index                                                               
    unknown=unknown)                                                                                                                                        
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__                                                             
    value = self.func(*args, **kw)                                                                                                                          
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 259, in fetch_index                                                          
    repodatas.append((url, future.result()))                                                                                                                
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 403, in result                                                  
    return self.__get_result()                                                                                                                              
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run                                                     
    result = self.fn(*self.args, **self.kwargs)                                                                                                             
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func                                                                  
    res = f(*args, **kwargs)                                                                                                                                
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 103, in fetch_repodata                                                       
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))                                                                                        
IOError: invalid data stream   
```

**Comment by bkreider** [comment]
This is what happens when you try to use conda against an unlicensed AE-Repo server.  I'm not sure what data it sends, but it chokes conda.

**Comment by kalefranz** [comment]
Old issue.  It was probably a 4XX or 5XX error that conda was just choking on.  Would be surprised if it's an issue any longer.
