### ISSUE TITLE
Installing any package fails (on one of my machines) (master)

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2570]
Master (`4.0.7.dev430+2b8b214`) again.  I get:
```
Traceback (most recent call last):
  File "/home/ilan/minonda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/ilan/conda/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/home/ilan/conda/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/home/ilan/conda/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/home/ilan/conda/conda/cli/install.py", line 394, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/ilan/conda/conda/plan.py", line 555, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/ilan/conda/conda/instructions.py", line 133, in execute_instructions
    cmd(state, arg)
  File "/home/ilan/conda/conda/instructions.py", line 80, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/home/ilan/conda/conda/install.py", line 1075, in unlink
    mk_menus(prefix, meta['files'], remove=True)
TypeError: 'NoneType' object has no attribute '__getitem__'
```
This only happens on one of my machines.

CC @kalefranz @mcg1969

**Comment by mcg1969** [comment]
Can you do a `--debug` run please? Thanks!

**Comment by ilanschnell** [comment]
Here you go:
```
$ CIO_TEST=3 conda --debug install openssl
DEBUG:conda.fetch:channel_urls=OrderedDict([('http://bremen/test-pkgs-ilan/linux-32/', ('http://bremen/test-pkgs-ilan', 1)), ('http://bremen/test-pkgs-ilan/noarch/', ('http://bremen/test-pkgs-ilan', 1)), ('http://bremen/test-pkgs/linux-32/', ('http://bremen/test-pkgs', 2)), ('http://bremen/test-pkgs/noarch/', ('http://bremen/test-pkgs', 2)), ('http://bremen/pkgs/pro/linux-32/', ('http://bremen/pkgs/pro', 3)), ('http://bremen/pkgs/pro/noarch/', ('http://bremen/pkgs/pro', 3)), ('http://bremen/pkgs/free/linux-32/', ('http://bremen/pkgs/free', 4)), ('http://bremen/pkgs/free/noarch/', ('http://bremen/pkgs/free', 4))])
Fetching package metadata ...INFO:stdoutlog:Fetching package metadata ...
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.connectionpool:"GET /test-pkgs-ilan/linux-32/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/test-pkgs-ilan/linux-32/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d5b04c>}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.connectionpool:"GET /test-pkgs-ilan/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/test-pkgs-ilan/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d08d4c>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /test-pkgs/linux-32/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/test-pkgs/linux-32/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d15f0c>}
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.connectionpool:"GET /test-pkgs/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/test-pkgs/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d2a8ac>}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/pkgs/pro/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d08d2c>}
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/pro/linux-32/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/pkgs/pro/linux-32/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d08dec>}
DEBUG:requests.packages.urllib3.util.retry:Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/pkgs/free/noarch/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6d47cec>}
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): bremen
DEBUG:requests.packages.urllib3.connectionpool:"GET /pkgs/free/linux-32/repodata.json.bz2 HTTP/1.1" 304 0
.DEBUG:dotupdate:fetching repodata: args ('http://bremen/pkgs/free/linux-32/',) kwargs {'use_cache': False, 'session': <conda.connection.CondaSession object at 0xb6aa7d6c>}

INFO:stdoutlog:

DEBUG:conda.plan:H0 specs=['openssl']
DEBUG:conda.plan:H2 python False
DEBUG:conda.plan:H2A python
DEBUG:conda.plan:H2 lua False
DEBUG:conda.plan:H2A lua
DEBUG:conda.plan:HF specs=['openssl']
DEBUG:conda.plan:Pinned specs=[]
DEBUG:conda.resolve:Checking satisfiability of current install
DEBUG:conda.resolve:Checking if the current environment is consistent
DEBUG:conda.resolve:Limiting solver to the following packages: wheel, sqlite, zlib, conda-env, python, pycosat, distribute, system, openssl, xz, yaml, conda, tk, setuptools, pip, pyyaml, readline, requests
DEBUG:conda.resolve:Packages to be preserved: filer::mistune-0.5.1-py27_0.tar.bz2, filer::networkx-1.9.1-py27_0.tar.bz2, filer::abstract-rendering-0.5.1-np19py27_0.tar.bz2, local::boto3-1.3.1-py27_0.tar.bz2, filer::colorama-0.3.3-py27_0.tar.bz2, filer::pyqt-4.11.3-py27_0.tar.bz2, filer::ipython-qtconsole-3.0.0-py27_0.tar.bz2, filer::ipython-notebook-3.0.0-py27_1.tar.bz2, filer::multipledispatch-0.4.7-py27_0.tar.bz2, filer::sip-4.16.5-py27_0.tar.bz2, http://bremen/pkgs/free::heapdict-1.0.0-py27_0.tar.bz2, https://conda.binstar.org/asmeurer::yasm-1.2.0-0.tar.bz2, filer::futures-2.2.0-py27_0.tar.bz2, filer::zeromq-4.0.4-0.tar.bz2, filer::spyder-2.3.4-py27_1.tar.bz2, filer::spyder-app-2.3.4-py27_0.tar.bz2, filer::pyopenssl-0.14-py27_0.tar.bz2, filer::pycrypto-2.6.1-py27_0.tar.bz2, filer::binstar-0.10.1-py27_3.tar.bz2, filer::gevent-1.0.1-py27_0.tar.bz2, filer::pillow-2.7.0-py27_1.tar.bz2, filer::ssl_match_hostname-3.4.0.2-py27_0.tar.bz2, http://bremen/pkgs/free::singledispatch-3.4.0.3-py27_0.tar.bz2, filer::libtiff-4.0.2-1.tar.bz2, filer::jinja2-2.8-py27_0.tar.bz2, filer::scikit-learn-0.15.2-np19py27_0.tar.bz2, filer::unicodecsv-0.9.4-py27_0.tar.bz2, filer::libsodium-0.4.5-0.tar.bz2, filer::cdecimal-2.3-py27_0.tar.bz2, local::cloudpickle-0.2.1-py27_0.tar.bz2, http://bremen/pkgs/free::jmespath-0.9.0-py27_0.tar.bz2, filer::libpng-1.5.13-1.tar.bz2, filer::ptyprocess-0.4-py27_0.tar.bz2, filer::jpeg-8d-0.tar.bz2, filer::mock-1.0.1-py27_0.tar.bz2, filer::bokeh-0.8.1-np19py27_1.tar.bz2, filer::cairo-1.12.18-2.tar.bz2, filer::pytables-3.1.1-np19py27_2.tar.bz2, filer::py2cairo-1.10.0-py27_2.tar.bz2, filer::werkzeug-0.10.1-py27_0.tar.bz2, filer::libffi-3.0.13-0.tar.bz2, filer::pyparsing-2.0.3-py27_0.tar.bz2, http://bremen/pkgs/free::chest-0.2.3-py27_0.tar.bz2, http://bremen/pkgs/free::locket-0.2.0-py27_0.tar.bz2, filer::funcsigs-0.4-py27_0.tar.bz2, filer::bitarray-0.8.1-py27_0.tar.bz2, filer::hdf5-1.8.14-0.tar.bz2, filer::ply-3.4-py27_0.tar.bz2, filer::libdynd-0.6.5-0.tar.bz2, filer::libxslt-1.1.28-0.tar.bz2, filer::blz-0.6.2-np19py27_0.tar.bz2, filer::patsy-0.3.0-np19py27_0.tar.bz2, https://conda.binstar.org/asmeurer::mpfr-3.1.2-0.tar.bz2, filer::openpyxl-1.8.5-py27_0.tar.bz2, filer::certifi-14.05.14-py27_0.tar.bz2, filer::configobj-5.0.6-py27_0.tar.bz2, filer::nose-1.3.4-py27_1.tar.bz2, filer::lxml-3.4.2-py27_0.tar.bz2, filer::nltk-3.0.2-np19py27_0.tar.bz2, filer::sqlalchemy-0.9.9-py27_0.tar.bz2, filer::psutil-2.2.1-py27_0.tar.bz2, local::distributed-1.10.0-py27_0.tar.bz2, filer::pycparser-2.10-py27_0.tar.bz2, filer::astropy-1.0.1-np19py27_0.tar.bz2, filer::cffi-0.9.2-py27_0.tar.bz2, filer::jdcal-1.0-py27_0.tar.bz2, local::s3fs-0.0.4-py27_0.tar.bz2, filer::bcolz-0.8.1-np19py27_0.tar.bz2, filer::qt-4.8.6-0.tar.bz2, https://conda.binstar.org/asmeurer::isl-0.12.2-0.tar.bz2, local::alabaster-0.7.7-py27_0.tar.bz2, filer::six-1.10.0-py27_0.tar.bz2, filer::numba-0.17.0-np19py27_0.tar.bz2, filer::decorator-3.4.0-py27_0.tar.bz2, ipython-3.0.0-py27_0.tar.bz2, filer::matplotlib-1.4.3-np19py27_1.tar.bz2, filer::jedi-0.8.1-py27_0.tar.bz2, filer::runipy-0.1.3-py27_0.tar.bz2, filer::pandas-0.15.2-np19py27_1.tar.bz2, filer::numexpr-2.3.1-np19py27_0.tar.bz2, http://bremen/pkgs/free::toolz-0.7.2-py27_0.tar.bz2, filer::argcomplete-0.8.4-py27_0.tar.bz2, filer::py-1.4.26-py27_0.tar.bz2, filer::blaze-core-0.7.3-np19py27_0.tar.bz2, filer::fontconfig-2.11.1-2.tar.bz2, filer::cython-0.22-py27_0.tar.bz2, local::dask-0.9.0-py27_0.tar.bz2, filer::pytest-2.6.4-py27_0.tar.bz2, filer::cryptography-0.8-py27_0.tar.bz2, filer::xlsxwriter-0.6.7-py27_0.tar.bz2, filer::pyflakes-0.8.1-py27_0.tar.bz2, filer::anaconda-2.2.0-np19py27_0.tar.bz2[mkl], https://conda.binstar.org/asmeurer::mpc-1.0.1-0.tar.bz2, local::click-6.6-py27_0.tar.bz2, filer::gevent-websocket-0.9.3-py27_0.tar.bz2, filer::scipy-0.15.1-np19py27_0.tar.bz2, conda-build-1.14.1-py27_0.tar.bz2, local::tblib-1.3.0-py27_0.tar.bz2, https://conda.binstar.org/asmeurer::gmp-5.1.2-2.tar.bz2, filer::numpy-1.9.2-py27_0.tar.bz2, http://bremen/pkgs/free::msgpack-python-0.4.6-py27_0.tar.bz2, filer::datashape-0.4.4-np19py27_1.tar.bz2, filer::xlwt-0.7.5-py27_0.tar.bz2, patchelf-0.6-0.tar.bz2, filer::statsmodels-0.6.1-np19py27_0.tar.bz2, filer::h5py-2.4.0-np19py27_0.tar.bz2, filer::boto-2.36.0-py27_0.tar.bz2, local::pygments-2.1-py27_0.tar.bz2, http://bremen/pkgs/free::tornado-4.2-py27_0.tar.bz2, filer::clyent-0.3.4-py27_0.tar.bz2, filer::sockjs-tornado-1.0.1-py27_0.tar.bz2, filer::llvmlite-0.2.2-py27_1.tar.bz2, filer::itsdangerous-0.24-py27_0.tar.bz2, local::constructor-1.0.0-py27_0.tar.bz2, filer::flask-0.10.1-py27_1.tar.bz2, filer::pytz-2015.7-py27_0.tar.bz2, local::sphinx_rtd_theme-0.1.9-py27_0.tar.bz2, filer::fastcache-1.0.2-py27_0.tar.bz2, filer::rope-0.9.4-py27_1.tar.bz2, filer::pep8-1.6.2-py27_0.tar.bz2, filer::odo-0.3.1-np19py27_0.tar.bz2, http://bremen/pkgs/free::krb5-1.13.2-0.tar.bz2, filer::anaconda-2.2.0-np19py27_0.tar.bz2, filer::greenlet-0.4.5-py27_0.tar.bz2, filer::pycurl-7.19.5.1-py27_0.tar.bz2, http://bremen/pkgs/free::mercurial-3.7.1-py27_0.tar.bz2, filer::pyzmq-14.5.0-py27_0.tar.bz2, local::botocore-1.4.17-py27_0.tar.bz2, filer::dynd-python-0.6.5-np19py27_0.tar.bz2, filer::docutils-0.12-py27_0.tar.bz2, filer::cytoolz-0.7.2-py27_0.tar.bz2, filer::curl-7.38.0-0.tar.bz2, local::babel-2.2.0-py27_0.tar.bz2, filer::enum34-1.0.4-py27_0.tar.bz2, filer::jsonschema-2.4.0-py27_0.tar.bz2, filer::xlrd-0.9.3-py27_0.tar.bz2, local::snowballstemmer-1.2.1-py27_0.tar.bz2, filer::pyasn1-0.1.7-py27_0.tar.bz2, filer::libxml2-2.9.0-0.tar.bz2, filer::theano-0.6.0-np19py27_0.tar.bz2, local::partd-0.3.3-py27_0.tar.bz2, filer::beautiful-soup-4.3.2-py27_0.tar.bz2, local::sphinx-1.3.5-py27_0.tar.bz2, filer::_license-1.1-py27_0.tar.bz2, filer::freetype-2.5.2-0.tar.bz2, filer::terminado-0.5-py27_0.tar.bz2, filer::ujson-1.33-py27_0.tar.bz2, filer::util-linux-2.21-0.tar.bz2, http://bremen/pkgs/free::pykerberos-1.1.10-py27_0.tar.bz2, filer::sympy-0.7.6-py27_0.tar.bz2, filer::pixman-0.26.2-0.tar.bz2, filer::markupsafe-0.23-py27_0.tar.bz2, filer::scikit-image-0.11.2-np19py27_0.tar.bz2, filer::python-dateutil-2.4.1-py27_0.tar.bz2
Solving package specifications ...INFO:stdoutlog:Solving package specifications ...
.DEBUG:dotupdate:Solving for [MatchSpec('openssl'), MatchSpec('conda'), MatchSpec('distribute (target=http://bremen/pkgs/free::distribute-0.6.45-py27_1.tar.bz2)'), MatchSpec('python (target=filer::python-2.7.11-0.tar.bz2)'), MatchSpec('yaml (target=yaml-0.1.6-0.tar.bz2)'), MatchSpec('setuptools (target=local::setuptools-20.1.1-py27_0.tar.bz2)'), MatchSpec('readline (target=<unknown>::readline-6.2-2.tar.bz2)'), MatchSpec('system (target=filer::system-5.8-2.tar.bz2)'), MatchSpec('conda-env (target=conda-env-2.4.5-py27_0.tar.bz2)'), MatchSpec('sqlite (target=filer::sqlite-3.9.2-0.tar.bz2)'), MatchSpec('xz (target=xz-5.0.5-0.tar.bz2)'), MatchSpec('pycosat (target=pycosat-0.6.1-py27_0.tar.bz2)'), MatchSpec('wheel (target=local::wheel-0.29.0-py27_0.tar.bz2)'), MatchSpec('requests (target=requests-2.9.1-py27_0.tar.bz2)'), MatchSpec('tk (target=filer::tk-8.5.18-0.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml-3.11-py27_1.tar.bz2)'), MatchSpec('pip (target=local::pip-8.0.3-py27_0.tar.bz2)'), MatchSpec('zlib (target=filer::zlib-1.2.8-0.tar.bz2)')]
DEBUG:conda.resolve:Retrieving packages for: [MatchSpec('openssl'), MatchSpec('conda'), MatchSpec('distribute (target=http://bremen/pkgs/free::distribute-0.6.45-py27_1.tar.bz2)'), MatchSpec('python (target=filer::python-2.7.11-0.tar.bz2)'), MatchSpec('yaml (target=yaml-0.1.6-0.tar.bz2)'), MatchSpec('setuptools (target=local::setuptools-20.1.1-py27_0.tar.bz2)'), MatchSpec('readline (target=<unknown>::readline-6.2-2.tar.bz2)'), MatchSpec('system (target=filer::system-5.8-2.tar.bz2)'), MatchSpec('conda-env (target=conda-env-2.4.5-py27_0.tar.bz2)'), MatchSpec('sqlite (target=filer::sqlite-3.9.2-0.tar.bz2)'), MatchSpec('xz (target=xz-5.0.5-0.tar.bz2)'), MatchSpec('pycosat (target=pycosat-0.6.1-py27_0.tar.bz2)'), MatchSpec('wheel (target=local::wheel-0.29.0-py27_0.tar.bz2)'), MatchSpec('requests (target=requests-2.9.1-py27_0.tar.bz2)'), MatchSpec('tk (target=filer::tk-8.5.18-0.tar.bz2)'), MatchSpec('pyyaml (target=pyyaml-3.11-py27_1.tar.bz2)'), MatchSpec('pip (target=local::pip-8.0.3-py27_0.tar.bz2)'), MatchSpec('zlib (target=filer::zlib-1.2.8-0.tar.bz2)')]
DEBUG:conda.resolve:python: pruned from 63 -> 55
DEBUG:conda.resolve:pip: pruned from 93 -> 75
DEBUG:conda.resolve:pyyaml: pruned from 14 -> 11
DEBUG:conda.resolve:distribute: pruned from 17 -> 11
DEBUG:conda.resolve:python: pruned from 55 -> 51
DEBUG:conda.resolve:pip: pruned from 75 -> 67
DEBUG:conda.resolve:setuptools: pruned from 183 -> 135
DEBUG:conda.resolve:conda-env: pruned from 58 -> 55
DEBUG:conda.resolve:pycosat: pruned from 28 -> 19
DEBUG:conda.resolve:wheel: pruned from 17 -> 13
DEBUG:conda.resolve:requests: pruned from 87 -> 63
DEBUG:conda.resolve:pyyaml: pruned from 11 -> 10
DEBUG:conda.resolve:conda: pruned from 274 -> 252
DEBUG:conda.resolve:python: pruned from 51 -> 47
.DEBUG:dotupdate:Checking satisfiability
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package removal metric: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,108)
DEBUG:conda.logic:Bisection attempt: (0,0), (6012+268) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (6280+7) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
.DEBUG:dotupdate:Initial package version/build metrics: 0/0
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Track feature count: 0
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Package feature count: 0
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (0,1)
DEBUG:conda.logic:Eliminating 16/16 terms for bound violation
DEBUG:conda.logic:Bisection attempt: (0,0), (6287+16) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final sum objective: 0
.DEBUG:dotupdate:Dependency update count: 0
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,46)
DEBUG:conda.logic:Bisection attempt: (0,0), (6303+412) clauses
DEBUG:conda.logic:Bisection failure, new range=(1,46)
DEBUG:conda.logic:Bisection attempt: (1,23), (6303+66) clauses
DEBUG:conda.logic:Bisection failure, new range=(24,46)
DEBUG:conda.logic:Bisection attempt: (24,35), (6303+30) clauses
DEBUG:conda.logic:Bisection failure, new range=(36,46)
DEBUG:conda.logic:Bisection attempt: (36,41), (6303+10) clauses
DEBUG:conda.logic:Bisection failure, new range=(42,46)
DEBUG:conda.logic:Bisection attempt: (42,44), (6303+4) clauses
DEBUG:conda.logic:Bisection failure, new range=(45,46)
DEBUG:conda.logic:Bisection attempt: (45,45), (6303+2) clauses
DEBUG:conda.logic:Bisection failure, new range=(46,46)
DEBUG:conda.logic:Bisection attempt: (46,46), (6303+1) clauses
DEBUG:conda.logic:Bisection success, new range=(46,46)
DEBUG:conda.logic:Final peak objective: 46
DEBUG:conda.logic:Beginning sum minimization
DEBUG:conda.logic:Initial range (46,158)
DEBUG:conda.logic:Bisection attempt: (46,158), (6304+148883) clauses
DEBUG:conda.logic:Bisection success, new range=(46,158)
DEBUG:conda.logic:Bisection attempt: (46,102), (6304+93608) clauses
DEBUG:conda.logic:Bisection failure, new range=(103,158)
DEBUG:conda.logic:Bisection attempt: (103,130), (6304+120566) clauses
DEBUG:conda.logic:Bisection failure, new range=(131,158)
DEBUG:conda.logic:Bisection attempt: (131,144), (6304+131661) clauses
DEBUG:conda.logic:Bisection failure, new range=(145,158)
DEBUG:conda.logic:Bisection attempt: (145,151), (6304+136713) clauses
DEBUG:conda.logic:Bisection failure, new range=(152,158)
DEBUG:conda.logic:Bisection attempt: (152,155), (6304+139731) clauses
DEBUG:conda.logic:Bisection failure, new range=(156,158)
DEBUG:conda.logic:Bisection attempt: (156,157), (6304+141102) clauses
DEBUG:conda.logic:Bisection failure, new range=(158,158)
DEBUG:conda.logic:Bisection attempt: (158,158), (6304+141780) clauses
DEBUG:conda.logic:Bisection success, new range=(158,158)
DEBUG:conda.logic:Final sum objective: 158
DEBUG:conda.logic:New peak objective: 46
DEBUG:conda.logic:Beginning peak minimization
DEBUG:conda.logic:Initial range (0,0)
DEBUG:conda.logic:Bisection attempt: (0,0), (148084+57) clauses
DEBUG:conda.logic:Bisection success, new range=(0,0)
DEBUG:conda.logic:Final peak objective: 0
.DEBUG:dotupdate:Additional package version/build metrics: 158/0
DEBUG:conda.logic:Empty objective, trivial solution
.DEBUG:dotupdate:Weak dependency count: 0
.DEBUG:dotupdate:Looking for alternate solutions

INFO:stdoutlog:


Package plan for installation in environment /home/ilan/minonda:

The following packages will be REMOVED:

    anaconda: 2.2.0-np19py27_0.tar. <unknown>              

The following packages will be UPDATED:

    openssl:  1.0.2g-0              http://bremen/pkgs/free --> 1.0.2h-1 http://bremen/test-pkgs-ilan

Proceed ([y]/n)? 

DEBUG:conda.instructions: PREFIX('/home/ilan/minonda')
DEBUG:conda.instructions: PRINT('Unlinking packages ...')
Unlinking packages ...
INFO:print:Unlinking packages ...
DEBUG:conda.instructions: PROGRESS('2')
INFO:progress.start:2
DEBUG:conda.instructions: UNLINK(u'filer::anaconda-2.2.0-np19py27_0.tar.')
INFO:progress.update:('anaconda', 0)
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/ilan/minonda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/ilan/conda/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/home/ilan/conda/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/home/ilan/conda/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/home/ilan/conda/conda/cli/install.py", line 394, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/ilan/conda/conda/plan.py", line 555, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/ilan/conda/conda/instructions.py", line 133, in execute_instructions
    cmd(state, arg)
  File "/home/ilan/conda/conda/instructions.py", line 80, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "/home/ilan/conda/conda/install.py", line 1075, in unlink
    mk_menus(prefix, meta['files'], remove=True)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by mcg1969** [comment]
Ahhhh, this is good information for a lot of reasons. Should help me do more of my own testing. Thank you.

**Comment by mcg1969** [comment]
I'm able to reproduce this by force-installing a bad version of `anaconda` into an environment. (Incidentally your other issue about printing will go away when this is fixed, too.)
