### ISSUE TITLE
Problem moving to trash on Windows when using path in virtual drive

### ISSUE THREAD

**Issue by fogo** [conda/conda#2575]
I tried to remove a package in one of my environments at work and ended up with error below:

```
λ conda remove matplotlib
Fetching package metadata: ....

Package plan for package removal in environment x:\ws-xmera\envs\xmera10:

The following packages will be REMOVED:

    matplotlib: 1.5.0+1-np111py27_1 https://esss:85ee7de9d291a89ae6cd839fd55d7a5a6e0e1244@eden.esss.com.br/conda-channel/esss/win-64/

Unlinking packages ...
False D: ['Miniconda']|                                                  |   0%
False x: [u'ws-xmera', u'envs', u'xmera10', u'Lib', u'site-packages']
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "D:\Miniconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Miniconda\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "D:\Miniconda\lib\site-packages\conda\cli\main.py", line 202, in args_func
    args.func(args, p)
  File "D:\Miniconda\lib\site-packages\conda\cli\main_remove.py", line 193, in execute
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Miniconda\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\Miniconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "D:\Miniconda\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "D:\Miniconda\lib\site-packages\conda\install.py", line 723, in unlink
    move_path_to_trash(dst)
  File "D:\Miniconda\lib\site-packages\conda\install.py", line 585, in move_path_to_trash
    trash_dir = join(trash_dir, relpath(os.path.dirname(path), config.root_dir))
  File "D:\Miniconda\lib\ntpath.py", line 530, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive x:, start on drive D:
```

Thing is my `x:` is part of `d:`:

```
λ subst
W:\: => D:\
X:\: => D:\Projects
```

It seems the line with `relpath` in `conda/install.py` should be more aware about Windows corner cases.

**Comment by kalefranz** [comment]
Are you still experiencing this issue with recent versions of conda?  Latest is conda 4.3.17.

**Comment by fogo** [comment]
Sorry, it is hard for me to help as recently I switched to developing full time on Linux (I don't have even a Windows VM right now to try to reproduce). I'll try to setup one or guide one of my friends to try this again for me.

**Comment by kalefranz** [comment]
From that stack trace, it looks like this ticket was for a very old version of conda.  Should be long-ago fixed.
