### ISSUE TITLE
Error Installing Matplotlib on window 10 pc 

### ISSUE THREAD

**Issue by dawarlord** [conda/conda#2577]
C:\Users\admin>conda install matplotlib
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment C:\Miniconda3:

The following NEW packages will be INSTALLED:

```
matplotlib: 1.5.1-np111py35_0
pyqt:       4.11.4-py35_5
qt:         4.8.7-vc14_7      [vc14]
```

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 670, in link
    if not run_script(prefix, dist, 'post-link'):
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 377, in run_script
    subprocess.check_call(args, env=env)
  File "C:\Miniconda3\lib\subprocess.py", line 579, in check_call
    retcode = call(_popenargs, *_kwargs)
  File "C:\Miniconda3\lib\subprocess.py", line 560, in call
    with Popen(_popenargs, *_kwargs) as p:
  File "C:\Miniconda3\lib\subprocess.py", line 950, in **init**
    restore_signals, start_new_session)
  File "C:\Miniconda3\lib\subprocess.py", line 1220, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kalefranz** [comment]
Outdated stack trace.  `conda update conda`
