### ISSUE TITLE
Cannot update anaconda no module named requests

### ISSUE THREAD

**Issue by johnlarkin1** [conda/conda#2578]
Hello, I've been trying to update anaconda because I've been having trouble opening spyder with an interactive browser. 
I get the following error after it seems like it's almost done it correctly. 
Macintosh:~ johnlarkin$ conda update anaconda
Traceback (most recent call last):
  File "/Users/johnlarkin/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/johnlarkin/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 99, in main
    from conda.cli import main_search
  File "/Users/johnlarkin/anaconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 12, in <module>
    from conda.misc import make_icon_url
  File "/Users/johnlarkin/anaconda/lib/python2.7/site-packages/conda/misc.py", line 19, in <module>
    from conda.api import get_index
  File "/Users/johnlarkin/anaconda/lib/python2.7/site-packages/conda/api.py", line 9, in <module>
    from conda.fetch import fetch_index
  File "/Users/johnlarkin/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "/Users/johnlarkin/anaconda/lib/python2.7/site-packages/conda/connection.py", line 24, in <module>
    import requests
ImportError: No module named requests

Any help? Thanks so much.

**Comment by mcg1969** [comment]
`requests` is one of conda's dependencies; it can't function without it. By any chance did you remove it with a previous command? It will not operate without `requests`, so the only things I can think to do are 1) reinstall Anaconda or 2) install `requests` with `pip` (`pip install requests`).
