### ISSUE TITLE
after windows 8 was updated to windows 10 anaconda stopped to run ipython notebook

### ISSUE THREAD

**Issue by Sandy4321** [conda/conda#2580]
after windows 8 was updated to windows 10 anaconda stopped to run ipython notebook

the error is

Microsoft Windows [Version 10.0.10586](c) 2015 Microsoft Corporation. All rights reserved.

C:\Users\Sander>ipython notebook
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\ipython-script.py", line 3, in <module>
    from IPython import start_ipython
  File "C:\Anaconda\lib\site-packages\IPython__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:\Anaconda\lib\site-packages\IPython\core\application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named traitlets.config.application

C:\Users\Sander>ipython notebook
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\ipython-script.py", line 3, in <module>
    from IPython import start_ipython
  File "C:\Anaconda\lib\site-packages\IPython__init__.py", line 48, in <module>
    from .core.application import Application
  File "C:\Anaconda\lib\site-packages\IPython\core\application.py", line 22, in <module>
    from traitlets.config.application import Application, catch_config_error
ImportError: No module named traitlets.config.application

**Comment by tyler-thetyrant** [comment]
Please trying reinstalling anaconda completely.
