### ISSUE TITLE
Cannot install parallel python version

### ISSUE THREAD

**Issue by WMGoBuffs** [conda/conda#2586]
To try out a particular feature I need to use 2.7.9+ (currently using 2.7.6). First, the output of conda info:
`Current conda install:

             platform : linux-64
        conda version : 3.0.6
       python version : 2.7.6.final.0
     root environment : /home/sjc/anaconda  (writable)
     default environment : /home/sjc/anaconda/envs/2.7.11
     envs directories : /home/sjc/anaconda/envs
     package cache : /home/sjc/anaconda/pkgs
     channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
     config file : None
    is foreign system : False`

I tried to create a new environment:

`conda create --name 2.7.9 python=2.7.9`

This fails, and the traceback is 

    Traceback (most recent call last):
      File "/home/sjc/anaconda/bin/conda", line 5, in <module>
        sys.exit(main())
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
        args.func(args, p)
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
        install.install(args, parser, 'create')
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/plan.py", line 387, in execute_actions
        execute_plan(plan, index, verbose)
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/plan.py", line 372, in execute_plan
        link(prefix, arg)
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/plan.py", line 327, in link
        install.link(pkgs_dir, prefix, dist, lt)
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/install.py", line 404, in link
        update_prefix(join(prefix, f), prefix)
      File "/home/sjc/anaconda/lib/python2.7/site-packages/conda/install.py", line 172, in update_prefix
        with open(path, 'rb') as fi:
    IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text lib/libsqlite3.la'

This same error occurs when I try to upgrade to 2.7.11 instead.  Any suggestions?

**Comment by nickvandewiele** [comment]
I noticed the same error trace, but from a different command (`conda update --yes conda`):

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
    https://github.com/ContinuumIO/conda/issues
Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/home/travis/anaconda/bin/conda", line 5, in <module>
    
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 183, in main
    
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 93, in execute
    
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/plan.py", line 374, in execute_actions
    continue
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/plan.py", line 359, in execute_plan
    log.debug('H2A %s' % name)
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/plan.py", line 314, in link
    if isfile(join(prefix, 'conda-meta', dist + '.json')):
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/install.py", line 390, in link
    except IOError:
  File "/home/travis/anaconda/lib/python2.7/site-packages/conda/install.py", line 167, in update_prefix
    elif isdir(path):
IOError: [Errno 2] No such file or directory: '/opt/anaconda1anaconda2anaconda3 text lib/libsqlite3.la'
The command "conda update --yes conda" failed and exited with 1 during .
```

**Comment by WMGoBuffs** [comment]
With a little searching, found some solutions here: https://github.com/ContinuumIO/anaconda-issues/issues/228

I mangled my own install trying to fix this issue another way, so I am unsure if this solves the problem.

**Comment by NoraGithub** [comment]
https://github.com/conda/conda/issues/2768
