### ISSUE TITLE
install.package_cache() broken with cache directory does not exist

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2596]
I just ran into this bug when building a package with `conda-build`.  Before building the package, I cleaned out removed the cache directory `pkgs`.  The trachback is as follows:
```
Traceback (most recent call last):
  File "/home/ilan/minonda/bin/conda-build", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/ilan/conda-build/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/home/ilan/conda-build/conda_build/main_build.py", line 140, in main
    args_func(args, p)
  File "/home/ilan/conda-build/conda_build/main_build.py", line 380, in args_func
    args.func(args, p)
  File "/home/ilan/conda-build/conda_build/main_build.py", line 367, in execute
    build.test(m)
  File "/home/ilan/conda-build/conda_build/build.py", line 613, in test
    rm_pkgs_cache(m.dist())
  File "/home/ilan/conda-build/conda_build/build.py", line 386, in rm_pkgs_cache
    plan.execute_plan(rmplan)
  File "/home/ilan/conda/conda/plan.py", line 583, in execute_plan
    inst.execute_instructions(plan, index, verbose)
  File "/home/ilan/conda/conda/instructions.py", line 133, in execute_instructions
    cmd(state, arg)
  File "/home/ilan/conda/conda/instructions.py", line 65, in RM_FETCHED_CMD
    install.rm_fetched(arg)
  File "/home/ilan/conda/conda/install.py", line 749, in rm_fetched
    rec = package_cache().get(dist)
  File "/home/ilan/conda/conda/install.py", line 692, in package_cache
    for fn in os.listdir(pdir):
OSError: [Errno 2] No such file or directory: '/home/ilan/minonda/pkgs'
```
The problem is that https://github.com/conda/conda/blob/master/conda/install.py#L692 assumes that the directory already exists, which might not be the case.

CC @mcg1969

**Comment by mcg1969** [comment]
I think the best thing here is to surround 692-693 in a `try/except` block like the previous block of code. I'll do this ASAP

**Comment by mcg1969** [comment]
Nah, just `os.isdir`

**Comment by mcg1969** [comment]
#2604 should fix this.
