### ISSUE TITLE
IOError: [Errno 22] invalid mode ('rb') blows up conda create

### ISSUE THREAD

**Issue by terrylyons** [conda/conda#2603]
Hi, I try to do a vanilla create environment with the prerequisites needed for caffe. It blows up at IOError: [Errno 22] invalid mode ('rb'), the file does exist; the entire script is given below. I run conda info at the end. 

```
C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64>conda create -n
 caffe_env numpy scipy matplotlib scikit-image pip
Fetching package metadata: ..
Solving package specifications: .................
Package plan for installation in environment C:\PYTHON27\envs\caffe_env:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.6                |            vc9_3         107 KB
    cycler-0.10.0              |           py27_0          10 KB
    decorator-4.0.9            |           py27_0          12 KB
    freetype-2.5.5             |            vc9_1         623 KB
    jpeg-8d                    |            vc9_0         175 KB
    libpng-1.6.22              |            vc9_0         524 KB
    libtiff-4.0.6              |            vc9_2         466 KB
    matplotlib-1.5.1           |      np111py27_0         6.1 MB
    mkl-11.3.3                 |                1       110.0 MB
    networkx-1.11              |           py27_0         1.1 MB
    numpy-1.11.0               |           py27_1         3.0 MB
    openssl-1.0.2h             |            vc9_0         4.4 MB
    pillow-3.2.0               |           py27_0         938 KB
    pip-8.1.1                  |           py27_1         1.5 MB
    pyparsing-2.1.4            |           py27_0          70 KB
    pyqt-4.11.4                |           py27_6         3.8 MB
    python-2.7.11              |                4        23.1 MB
    python-dateutil-2.5.3      |           py27_0         236 KB
    pytz-2016.4                |           py27_0         171 KB
    qt-4.8.7                   |            vc9_8        51.4 MB
    scikit-image-0.12.3        |      np111py27_0        17.7 MB
    scipy-0.17.1               |      np111py27_0        11.4 MB
    setuptools-21.2.1          |           py27_0         763 KB
    sip-4.16.9                 |           py27_2         249 KB
    six-1.10.0                 |           py27_0          16 KB
    tk-8.5.18                  |            vc9_0         2.2 MB
    vs2008_runtime-9.00.30729.1|                1         1.2 MB
    vs2010_runtime-10.00.40219.1|                1         1.2 MB
    wheel-0.29.0               |           py27_0         121 KB
    zlib-1.2.8                 |            vc9_3         108 KB
    ------------------------------------------------------------
                                           Total:       242.6 MB

The following packages will be linked:

    package                    |            build
    ---------------------------|-----------------
    bzip2-1.0.6                |            vc9_3   hard-link
    cycler-0.10.0              |           py27_0   hard-link
    decorator-4.0.9            |           py27_0   hard-link
    freetype-2.5.5             |            vc9_1   hard-link
    jpeg-8d                    |            vc9_0   hard-link
    libpng-1.6.22              |            vc9_0   hard-link
    libtiff-4.0.6              |            vc9_2   hard-link
    matplotlib-1.5.1           |      np111py27_0   hard-link
    mkl-11.3.3                 |                1   hard-link
    networkx-1.11              |           py27_0   hard-link
    numpy-1.11.0               |           py27_1   hard-link
    openssl-1.0.2h             |            vc9_0   hard-link
    pillow-3.2.0               |           py27_0   hard-link
    pip-8.1.1                  |           py27_1   hard-link
    pyparsing-2.1.4            |           py27_0   hard-link
    pyqt-4.11.4                |           py27_6   hard-link
    python-2.7.11              |                4   hard-link
    python-dateutil-2.5.3      |           py27_0   hard-link
    pytz-2016.4                |           py27_0   hard-link
    qt-4.8.7                   |            vc9_8   hard-link
    scikit-image-0.12.3        |      np111py27_0   hard-link
    scipy-0.17.1               |      np111py27_0   hard-link
    setuptools-21.2.1          |           py27_0   hard-link
    sip-4.16.9                 |           py27_2   hard-link
    six-1.10.0                 |           py27_0   hard-link
    tk-8.5.18                  |            vc9_0   hard-link
    vs2008_runtime-9.00.30729.1|                1   hard-link
    vs2010_runtime-10.00.40219.1|                1   hard-link
    wheel-0.29.0               |           py27_0   hard-link
    zlib-1.2.8                 |            vc9_3   hard-link

Proceed ([y]/n)? y

Fetching packages ...
mkl-11.3.3-1.t 100% |###############################| Time: 0:00:24   4.77 MB/s
python-2.7.11- 100% |###############################| Time: 0:00:05   4.35 MB/s
qt-4.8.7-vc9_8 100% |###############################| Time: 0:00:11   4.53 MB/s
scikit-image-0 100% |###############################| Time: 0:00:04   4.07 MB/s
scipy-0.17.1-n 100% |###############################| Time: 0:00:03   3.82 MB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  20%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\PYTHON27\SCRIPTS\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\PYTHON27\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\PYTHON27\lib\site-packages\conda\cli\main_create.py", line 49, in exe
cute
    install.install(args, parser, 'create')
  File "C:\PYTHON27\lib\site-packages\conda\cli\install.py", line 278, in instal
l
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\PYTHON27\lib\site-packages\conda\plan.py", line 436, in execute_actio
ns
    execute_plan(plan, index, verbose)
  File "C:\PYTHON27\lib\site-packages\conda\plan.py", line 418, in execute_plan
    link(prefix, arg, index=index)
  File "C:\PYTHON27\lib\site-packages\conda\plan.py", line 374, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\PYTHON27\lib\site-packages\conda\install.py", line 486, in link
    update_prefix(join(prefix, f), prefix, placeholder, mode)
  File "C:\PYTHON27\lib\site-packages\conda\install.py", line 210, in update_pre
fix
    with open(path, 'rb') as fi:
IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\\PYTHON27\\envs\\caffe_
env\\"Library\\lib\\libpng\\libpng16-release.cmake"'

C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64>conda info
Current conda install:

             platform : win-64
        conda version : 3.5.5
       python version : 2.7.7.final.0
     root environment : C:\PYTHON27  (writable)
  default environment : C:\PYTHON27
     envs directories : C:\PYTHON27\envs
        package cache : C:\PYTHON27\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : None
    is foreign system : False


C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64>
```

**Comment by kalefranz** [comment]
Your report is for a *very* old version of conda.  Update conda--might have to do it with a new miniconda installer--and that'll probably fix things for you.  If not, feel free to file a new ticket with the new stack trace.
