### ISSUE TITLE
Error creating new 3.5 environment on top of initial 2.7 installation

### ISSUE THREAD

**Issue by james-adams-noaa** [conda/conda#2605]
Today I ran the following command in order to create a Python 3.5 environment (I have a 2.7 installation already in place):

`$ conda create -n py35 python=3.5 anaconda
`

This never successfully completes and instead reports this traceback: 

```
Traceback (most recent call last):
  File "/home/james.adams/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/install.py", line 652, in link
    _link(src, dst, lt)
  File "/home/james.adams/anaconda2/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/home/james.adams/anaconda2/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/home/james.adams/anaconda2/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/james.adams/anaconda2/pkgs/python-3.5.1-0/lib/python3.5/_sysconfigdata.py'

```

Overall conda information:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.0.6
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/james.adams/anaconda2  (writable)
  default environment : /home/james.adams/anaconda2
     envs directories : /home/james.adams/anaconda2/envs
        package cache : /home/james.adams/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

Thanks in advance for any help resolving this issue.

--James

**Comment by tyler-thetyrant** [comment]
Closing outdated.
