### ISSUE TITLE
Issue installing glueviz on Mac

### ISSUE THREAD

**Issue by abouthydrology** [conda/conda#2610]
Traceback (most recent call last):
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "//anaconda/lib/python3.4/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "//anaconda/lib/python3.4/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "//anaconda/lib/python3.4/site-packages/conda/instructions.py", line 96, in UNLINK_CMD
    install.unlink(state['prefix'], arg)
  File "//anaconda/lib/python3.4/site-packages/conda/install.py", line 726, in unlink
    with open(meta_path) as fi:
FileNotFoundError: [Errno 2] No such file or directory: '//anaconda/conda-meta/astropy-1.0.3-np19py34_0.json'

**Comment by kalefranz** [comment]
Believe to be fixed long ago.
