### ISSUE TITLE
notebook broken with miniconda on windows with installer options unchecked

### ISSUE THREAD

**Issue by rsignell-usgs** [conda/conda#2612]
I'm getting `kernel error` when I try to create any notebook with my new miniconda3 environment on windows.  Here's what I did:
* fresh install of miniconda3 on windows 7
* installed just for me (local user)
* unchecked both boxes on the installer so my path and registry are not modified
* opened a windows command prompt
* changed directory to ~/appdata/local/continuum/miniconda3/scripts
* typed "activate"
* typed "conda install anaconda-navigator"
* typed "anaconda-navigator"  (get "libpng warning: iCCP: known incorrect sRGB profile" in command prompt window)
* clicked "install" on the notebook app
* clicked "launch" on the notebook app (get
```
[W 10:30:27.441 NotebookApp] Widgets are unavailable. Please install widgetsnbex
tension or ipywidgets 4.0
[I 10:30:27.471 NotebookApp] Serving notebooks from local directory: C:\users\rs
ignell\documents\github
[I 10:30:27.472 NotebookApp] 0 active kernels
[I 10:30:27.472 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/
[I 10:30:27.473 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
```
* opened a new (empty) python3 notebook
* got "kernel error"
* in the console, I see this:
```
[I 10:35:18.688 NotebookApp] Serving notebooks from local directory: C:\users\rs
ignell\documents\github
[I 10:35:18.688 NotebookApp] 0 active kernels
[I 10:35:18.689 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/
[I 10:35:18.689 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[I 10:35:24.829 NotebookApp] Creating new notebook in
[TerminalIPythonApp] WARNING | Subcommand `ipython nbconvert` is deprecated and
will be removed in future versions.
[TerminalIPythonApp] WARNING | You likely want to use `jupyter nbconvert` in the
 future
[NbConvertApp] Converting notebook Untitled5.ipynb to script
[NbConvertApp] Writing 0 bytes to Untitled5.txt
[E 10:35:29.106 NotebookApp] Failed to run command:
    ['C:\\conda\\envs\\_build\\python.exe', '-m', 'ipykernel', '-f', 'C:\\Users\
\rsignell\\AppData\\Roaming\\jupyter\\runtime\\kernel-313623b1-4a33-46cc-b871-60
7248032d34.json']
    with kwargs:
    {'env': {'WINDOWS_TRACING_LOGFILE': 'C:\\BVTBin\\Tests\\installpackage\\csil
ogfile.log', 'AGSDESKTOPJAVA': 'C:\\ArcGIS\\Desktop10.3\\', 'UATDATA': 'C:\\Wind
ows\\CCM\\UATData\\D9F8C395-CAB8-491d-B8AC-179A1FE1BE77', 'TMP': 'C:\\Users\\rsi
gnell\\AppData\\Local\\Temp\\3', 'LOCALAPPDATA': 'C:\\Users\\rsignell\\AppData\\
Local', 'COMSPEC': 'C:\\Windows\\system32\\cmd.exe', 'NUMBER_OF_PROCESSORS': '8'
, 'CONDA_PATH_BACKUP': 'C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program File
s (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\\Window
s\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\Windo
wsPowerShell\\v1.0\\;C:\\Program Files\\Google\\Google Apps Sync\\;C:\\Program F
iles\\Google\\Google Apps Migration\\;C:\\Program Files\\Intel\\WiFi\\bin\\;C:\\
Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\Intel\\I
ntel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(
R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Manageme
nt Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Management En
gine Components\\IPT;C:\\ArcGIS\\gbin;C:\\Program Files\\MATLAB\\R2015b\\bin;C:\
\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program Files\
\Git\\usr\\bin;C:\\Program Files (x86)\\Skype\\Phone\\', 'PROGRAMFILES': 'C:\\Pr
ogram Files', 'QT_API': 'pyqt', 'JPY_PARENT_PID': '764', 'FP_NO_HOST_CHECK': 'NO
', 'SYSTEMDRIVE': 'C:', 'APPDATA': 'C:\\Users\\rsignell\\AppData\\Roaming', 'PRO
MPT': '[Miniconda3] $P$G', 'PROGRAMFILES(X86)': 'C:\\Program Files (x86)', 'PROG
RAMDATA': 'C:\\ProgramData', 'USERNAME': 'rsignell', 'HOMEDRIVE': 'C:', 'COMMONP
ROGRAMFILES': 'C:\\Program Files\\Common Files', 'WINDIR': 'C:\\Windows', 'PUBLI
C': 'C:\\Users\\Public', 'IPY_INTERRUPT_EVENT': '968', 'CONDA_DEFAULT_ENV': 'C:\
\Users\\rsignell\\AppData\\Local\\Continuum\\Miniconda3', 'USERDNSDOMAIN': 'GS.D
OI.NET', 'PROGRAMW6432': 'C:\\Program Files', 'TEMP': 'C:\\Users\\rsignell\\AppD
ata\\Local\\Temp\\3', 'JPY_INTERRUPT_EVENT': '968', 'PROCESSOR_LEVEL': '6', 'USE
RDOMAIN': 'GS', 'PSMODULEPATH': 'C:\\Windows\\system32\\WindowsPowerShell\\v1.0\
\Modules\\', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'USERPROFILE': 'C:\\Users\\rsign
ell', 'HOMEPATH': '\\Users\\rsignell', 'PROCESSOR_REVISION': '3c03', 'COMMONPROG
RAMW6432': 'C:\\Program Files\\Common Files', 'PROCESSOR_IDENTIFIER': 'Intel64 F
amily 6 Model 60 Stepping 3, GenuineIntel', 'COMPUTERNAME': 'IGSAGIEGLTRSI71', '
WINDOWS_TRACING_FLAGS': '3', 'ALLUSERSPROFILE': 'C:\\ProgramData', 'OS': 'Window
s_NT', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'COMM
ONPROGRAMFILES(X86)': 'C:\\Program Files (x86)\\Common Files', 'SYSTEMROOT': 'C:
\\Windows', 'DOIJAVA86': 'C:\\Program Files (x86)\\Java\\jre1.8.0_91\\bin', 'PAT
H': 'C:\\Users\\rsignell\\AppData\\Local\\Continuum\\Miniconda3\\Library\\bin;C:
\\Users\\rsignell\\AppData\\Local\\Continuum\\Miniconda3\\Library\\bin;C:\\Users
\\rsignell\\AppData\\Local\\Continuum\\Miniconda3;C:\\Users\\rsignell\\AppData\\
Local\\Continuum\\Miniconda3\\Scripts;C:\\Users\\rsignell\\AppData\\Local\\Conti
nuum\\Miniconda3\\Library\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Progr
am Files (x86)\\Intel\\iCLS Client\\;C:\\Program Files\\Intel\\iCLS Client\\;C:\
\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32
\\WindowsPowerShell\\v1.0\\;C:\\Program Files\\Google\\Google Apps Sync\\;C:\\Pr
ogram Files\\Google\\Google Apps Migration\\;C:\\Program Files\\Intel\\WiFi\\bin
\\;C:\\Program Files\\Common Files\\Intel\\WirelessCommon\\;C:\\Program Files\\I
ntel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\
\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) M
anagement Engine Components\\IPT;C:\\Program Files (x86)\\Intel\\Intel(R) Manage
ment Engine Components\\IPT;C:\\ArcGIS\\gbin;C:\\Program Files\\MATLAB\\R2015b\\
bin;C:\\Program Files\\Git\\cmd;C:\\Program Files\\Git\\mingw64\\bin;C:\\Program
 Files\\Git\\usr\\bin;C:\\Program Files (x86)\\Skype\\Phone\\', 'SESSIONNAME': '
Console', 'DOILOGONMETHOD_RSIGNELL': 'smartcard credential provider', 'USERDOMAI
N_ROAMINGPROFILE': 'GS', 'PYTHONPATH': 'C:\\ArcGIS\\Desktop10.3\\ArcToolbox\\Too
lboxes\\USGS_EGISTools\\scripts', 'DOIJAVA64': 'C:\\Program Files\\Java\\jre1.8.
0_91\\bin', 'VBOX_MSI_INSTALL_PATH': 'C:\\Program Files\\Oracle\\VirtualBox\\',
'LOGONSERVER': '\\\\IGSAGIEIDC02'}, 'stderr': None, 'cwd': 'C:\\users\\rsignell\
\documents\\github', 'stdout': None, 'stdin': -1}

[E 10:35:29.116 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\notebook\base\handlers.py", line 457, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\notebook\services\sessions\handlers.py", line 62, in post
        kernel_id=kernel_id))
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\notebook\services\sessions\sessionmanager.py", line 79, in create_session
        kernel_name)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1014, in run
        yielded = self.gen.throw(*exc_info)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_s
ession
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_na
me)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 1008, in run
        value = future.result()
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\tornado\gen.py", line 282, in wrapper
        yielded = next(result)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\notebook\services\kernels\kernelmanager.py", line 87, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\jupyter_client\multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\jupyter_client\manager.py", line 243, in start_kernel
        **kw)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\jupyter_client\manager.py", line 189, in _launch_kernel
        return launch_kernel(kernel_cmd, **kw)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\site-packag
es\jupyter_client\launcher.py", line 123, in launch_kernel
        proc = Popen(cmd, **kwargs)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\subprocess.
py", line 950, in __init__
        restore_signals, start_new_session)
      File "C:\Users\rsignell\AppData\Local\Continuum\Miniconda3\lib\subprocess.
py", line 1220, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified
[E 10:35:29.135 NotebookApp] {
      "X-Requested-With": "XMLHttpRequest",
      "Host": "localhost:8888",
      "Content-Length": "77",
      "Origin": "http://localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHT
ML, like Gecko) Chrome/50.0.2661.102 Safari/537.36",
      "Content-Type": "application/json",
      "Accept-Language": "en-US,en;q=0.8",
      "Connection": "keep-alive",
      "Accept-Encoding": "gzip, deflate",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Referer": "http://localhost:8888/notebooks/Untitled5.ipynb?kernel_name=py
thon3"
    }
[E 10:35:29.157 NotebookApp] 500 POST /api/sessions (::1) 110.22ms referer=http:
//localhost:8888/notebooks/Untitled5.ipynb?kernel_name=python3
```

**Comment by mcg1969** [comment]
I've moved this over to [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/issues/813).
