### ISSUE TITLE
numpy import error

### ISSUE THREAD

**Issue by suiyuan2009** [conda/conda#2613]
```
suiyuan2009@ubuntu:~/repos/tensorflow$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package -j 4
INFO: Found 1 target...
ERROR: /home/suiyuan2009/repos/tensorflow/tensorflow/contrib/session_bundle/example/BUILD:38:1: Executing genrule //tensorflow/contrib/session_bundle/example:half_plus_two failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Traceback (most recent call last):
  File "/home/suiyuan2009/.cache/bazel/_bazel_suiyuan2009/bc400c76b1e33d0054f75f0cda965b48/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/contrib/session_bundle/example/export_half_plus_two.py", line 32, in <module>
    import tensorflow as tf
  File "/home/suiyuan2009/.cache/bazel/_bazel_suiyuan2009/bc400c76b1e33d0054f75f0cda965b48/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/home/suiyuan2009/.cache/bazel/_bazel_suiyuan2009/bc400c76b1e33d0054f75f0cda965b48/tensorflow/bazel-out/host/bin/tensorflow/contrib/session_bundle/example/export_half_plus_two.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 45, in <module>
    import numpy as np
  File "/home/suiyuan2009/.local/lib/python2.7/site-packages/numpy/__init__.py", line 201, in <module>
    from . import random
  File "/home/suiyuan2009/.local/lib/python2.7/site-packages/numpy/random/__init__.py", line 99, in <module>
    from .mtrand import *
ImportError: /home/suiyuan2009/.local/lib/python2.7/site-packages/numpy/random/mtrand.so: undefined symbol: PyFPE_jbuf
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.322s, Critical Path: 0.09s
```

I copy mtrand.so from anaconda2, then everything is ok.

**Comment by mcg1969** [comment]
Migrated to [https://github.com/ContinuumIO/anaconda-issues/issues/812](anaconda-issues).
