### ISSUE TITLE
Spyder appp Update issue

### ISSUE THREAD

**Issue by suyashdb** [conda/conda#2616]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    name,
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    try:
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    plan = plan_from_actions(actions)
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    def UNLINK_CMD(state, arg):
  File "/Users/sdb99/anaconda/lib/python2.7/site-packages/conda/install.py", line 691, in unlink
    from conda.config import remove_binstar_tokens
IOError: [Errno 2] No such file or directory: '/Users/sdb99/anaconda/conda-meta/conda-3.18.8-py27_0.json'

**Comment by kalefranz** [comment]
Not sure what command you were trying to run when you encountered this problem.  If you're having similar issues with a recent version of conda (latest is 4.3.17), feel free to file a new ticket.
