### ISSUE TITLE
error on pythreejs install

### ISSUE THREAD

**Issue by worbit** [conda/conda#2632]
$ conda info
-bash: /Users/bernham/anaconda/bin/conda: No such file or directory

Traceback (most recent call last):
  File "/Users/bernham/anaconda/bin/conda", line 6, in <module>
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
  File "/Users/bernham/anaconda/lib/python2.7/site-packages/conda/install.py", line 634, in link
  File "/Users/bernham/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/bernham/anaconda/lib/python2.7/site-packages/simplegeneric-0.8.1-py2.7.egg-info'

**Comment by kalefranz** [comment]
Example of conda breaking itself with a failed update.  Fixed with transactions in conda 4.3.
