### ISSUE TITLE
Error report installing ipywidgets 

### ISSUE THREAD

**Issue by jbwhit** [conda/conda#2650]
I tried to run `conda install -c conda-forge ipywidgets` and got the following error message: 

```
Fetching package metadata: ......
Solving package specifications: ..............................
Package plan for installation in environment /Users/jonathan/miniconda2/envs/berkeley2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    sqlite-3.13.0              |                1         1.4 MB
    tk-8.5.19                  |                0         2.0 MB
    backports.shutil_get_terminal_size-1.0.0|           py27_0           5 KB
    functools32-3.2.3.2        |           py27_1          16 KB
    python-simplegeneric-0.8.1 |           py27_0           6 KB
    ssl_match_hostname-3.5.0.1 |           py27_0           6 KB
    pexpect-4.1.0              |           py27_0          64 KB
    python-pathlib2-2.1.0      |           py27_0          26 KB
    entrypoints-0.2.1          |           py27_0           6 KB
    widgetsnbextension-1.2.3   |           py27_1         1.1 MB
    ipywidgets-5.1.5           |           py27_0          59 KB
    ------------------------------------------------------------
                                           Total:         4.7 MB

The following NEW packages will be INSTALLED:

    backports.shutil_get_terminal_size: 1.0.0-py27_0
    python-pathlib2:                    2.1.0-py27_0
    python-simplegeneric:               0.8.1-py27_0
    widgetsnbextension:                 1.2.3-py27_1

The following packages will be UPDATED:

    entrypoints:                        0.2-py27_1     --> 0.2.1-py27_0
    functools32:                        3.2.3.2-py27_0 --> 3.2.3.2-py27_1
    ipywidgets:                         4.1.1-py27_0   --> 5.1.5-py27_0
    pexpect:                            4.0.1-py27_0   --> 4.1.0-py27_0
    sqlite:                             3.13.0-0       --> 3.13.0-1
    ssl_match_hostname:                 3.4.0.2-py27_1 --> 3.5.0.1-py27_0
    tk:                                 8.5.18-0       --> 8.5.19-0

Proceed ([y]/n)?

Fetching packages ...
sqlite-3.13.0- 100% |#####################| Time: 0:00:00   1.67 MB/s
tk-8.5.19-0.ta 100% |#####################| Time: 0:00:00   2.11 MB/s
backports.shut 100% |#####################| Time: 0:00:00   4.22 MB/s
functools32-3. 100% |#####################| Time: 0:00:00 178.56 kB/s
python-simpleg 100% |#####################| Time: 0:00:00   7.75 MB/s
ssl_match_host 100% |#####################| Time: 0:00:00   1.24 MB/s
pexpect-4.1.0- 100% |#####################| Time: 0:00:00 368.86 kB/s
python-pathlib 100% |#####################| Time: 0:00:00 275.06 kB/s
entrypoints-0. 100% |#####################| Time: 0:00:00   2.32 MB/s
widgetsnbexten 100% |#####################| Time: 0:00:00   1.65 MB/s
ipywidgets-5.1 100% |#####################| Time: 0:00:00 384.22 kB/s
Extracting packages ...
[      COMPLETE      ]|########################################| 100%
Unlinking packages ...
[      COMPLETE      ]|########################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the  |  36%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/jonathan/miniconda2/envs/berkeley2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/jonathan/miniconda2/lib/python2.7/site-packages/conda/install.py", line 616, in link
    os.makedirs(dst_dir)
  File "/Users/jonathan/miniconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/jonathan/miniconda2/envs/berkeley2/lib/python2.7/site-packages/simplegeneric-0.8.1-py2.7.egg-info'
```

And running `conda info` as requested: 

```
Current conda install:

             platform : osx-64
        conda version : 3.19.0
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/jonathan/miniconda2  (writable)
  default environment : /Users/jonathan/miniconda2/envs/berkeley2
     envs directories : /Users/jonathan/miniconda2/envs
        package cache : /Users/jonathan/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by ijstokes** [comment]
Try updating conda with:
```
conda update conda
```
However my experience is that once a package gets pooched it can be difficult to recover. In this case `simplegeneric` may be fracked, however you might have success recovering it with `conda install -f python-simplegeneric`.

But update Conda first.

And then try installing `ipywidgets` from the `conda-forge` channel again
​

**Comment by kalefranz** [comment]
Outdated. Closing.  Conda 4.3 will help with better error messaging.
