### ISSUE TITLE
constructor does not work with master

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2656]
Using master (`4.0.8-547-g2a0a076`), I still have problems when using non-default channels in my `construct.yaml` file:
```
channels:
  - http://repo.continuum.io/pkgs/free/
  - https://conda.anaconda.org/ilan

# specifications
specs:
  - python
  - grin
  - sample
```
I get:
```
Traceback (most recent call last):
  File "/Users/ilan/python/bin/constructor", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/ilan/constructor/bin/constructor", line 6, in <module>
    sys.exit(main())
  File "/Users/ilan/constructor/constructor/main.py", line 146, in main
    verbose=opts.verbose)
  File "/Users/ilan/constructor/constructor/main.py", line 84, in main_build
    create(info)
  File "/Users/ilan/constructor/constructor/shar.py", line 97, in create
    t.add(join(info['_download_dir'], fn), 'pkgs/' + fn)
  File "/Users/ilan/python/lib/python2.7/tarfile.py", line 2006, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/Users/ilan/python/lib/python2.7/tarfile.py", line 1878, in gettarinfo
    statres = os.lstat(name)
OSError: [Errno 2] No such file or directory: '/Users/ilan/.conda/constructor/osx-64/ilan::sample-0.6.0-xyz.tar.bz2'
```
I know that @joelhullcio is using custom channels to build constructor installers for a customer.

CC @kalefranz @mcg1969

**Comment by mcg1969** [comment]
We will solve this Monday.

**Comment by mcg1969** [comment]
@ilanschnell, can you confirm that we've solved this issue; and if so, close it? If not, let me know and we'll continue work.

**Comment by mcg1969** [comment]
oops, didn't mean to close it myself. I want you to confirm first

**Comment by kalefranz** [comment]
@ilanschnell Please reopen if we still have a problem here.
