### ISSUE TITLE
Error at the end of build

### ISSUE THREAD

**Issue by nblouin** [conda/conda#2657]
Linking packages ...
An unexpected error has occurred, please consider sending the                       |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/nicblouin/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/nicblouin/miniconda2/lib/python2.7/site-packages/conda/install.py", line 650, in link
    os.makedirs(dst_dir)
  File "/Users/nicblouin/miniconda2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/nicblouin/miniconda2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/nicblouin/miniconda2/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/Users/nicblouin/miniconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/path'
NicBook-2:~ nicblouin$ 

NicBook-2:~ nicblouin$ conda info
Current conda install:

```
         platform : osx-64
    conda version : 4.0.8
```

  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/nicblouin/miniconda2  (writable)
  default environment : /Users/nicblouin/miniconda2
     envs directories : /Users/nicblouin/miniconda2/envs
        package cache : /Users/nicblouin/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by dorzel** [comment]
could you paste the raw command you ran to get this error?
