### ISSUE TITLE
UnicodeDecodeError during installation of python files

### ISSUE THREAD

**Issue by anna-stellar** [conda/conda#2661]
Dear community,

I am new to python and am having big troubles with installation of an anaconda based python files. As I could understand the problem occurs with the utf-8. The utf contents, the problem documentation and my system are given below. I am grateful for any help.
Cheers,
Anna

**locale:**
LANG=en_US.UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"

**system:**
ubuntu 14.04 LTS
platform : linux-64
        conda version : 4.0.8
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1

**problem documentation:**
anna@anna-pc:~$ conda create -n starkit --file https://raw.githubusercontent.com/wkerzendorf/starkit/master/conda_requirements.txt python=2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/anna/anaconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/anna/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/anna/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/anna/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/home/anna/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 171, in install
    specs.extend(common.specs_from_url(fpath, json=args.json))
  File "/home/anna/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 499, in specs_from_url
    for line in open(path):
  File "/home/anna/anaconda3/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by dfroger** [comment]
Same as #3667 I think.

**Comment by tyler-thetyrant** [comment]
This is not fixed with recent version of conda (on most systems).
