### ISSUE TITLE
Issue with conda install -c r r

### ISSUE THREAD

**Issue by robertdoubble** [conda/conda#2667]
On executing the conda install -c r r command the install is interrupted due to an error:

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\rober\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\rober\Anaconda3\lib\site-packages\conda\install.py", line 821, in extract
    os.rename(temp_path, path)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\rober\\Anaconda3\\pkgs\\m2w64-expat-2.1.1-1.tmp' -> 'C:\\Users\\rober\\Anaconda3\\pkgs\\m2w64-expat-2.1.1-1'

[Anaconda3] C:\Users\rober>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.0
  conda-build version : 1.20.3
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\Users\rober\Anaconda3  (writable)
  default environment : C:\Users\rober\Anaconda3
     envs directories : C:\Users\rober\Anaconda3\envs
        package cache : C:\Users\rober\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Disabling the firewall results in the same error message.

**Comment by kalefranz** [comment]
Should be fixed with #2717.
