### ISSUE TITLE
cannot import name check_install

### ISSUE THREAD

**Issue by rickiepark** [conda/conda#2676]
After I updated conda today, It doesn't work properly.

```
RickyParkui-MacBook-Pro:cli rickypark$ conda-inspect
Traceback (most recent call last):
  File "/Users/rickypark/anaconda/bin/conda-inspect", line 3, in <module>
    from conda_build.main_inspect import main
  File "/Users/rickypark/anaconda/lib/python2.7/site-packages/conda_build/main_inspect.py", line 23, in <module>
    from conda.cli.install import check_install
ImportError: cannot import name check_install
RickyParkui-MacBook-Pro:cli rickypark$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.0
  conda-build version : 1.20.3
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /Users/rickypark/anaconda  (writable)
  default environment : /Users/rickypark/anaconda
     envs directories : /Users/rickypark/anaconda/envs
        package cache : /Users/rickypark/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/rickypark/.condarc
    is foreign system : False
```

**Comment by kalefranz** [comment]
fixed with https://github.com/conda/conda-build/pull/1027

`conda-build 1.21.0`

**Comment by rickiepark** [comment]
@kalefranz  Thanks a lot! ;-)
