### ISSUE TITLE
broken pip config, breaks conda

### ISSUE THREAD

**Issue by bkreider** [conda/conda#2683]
This is reported from a customer, I don't know the exact setup, but it looks like the proxy servers are setup wrong.  Either way, a bad pip configuration should not completely break conda. 

```
Traceback (most recent call last):

File "/home/binstar/miniconda2/bin/pip", line 6, in <module>

sys.exit(pip.main())

File "/home/binstar/miniconda2/lib/python2.7/site-packages/pip/__init__.py", line 207, in main

cmd_name, cmd_args = parseopts(args)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/pip/__init__.py", line 147, in parseopts

parser = create_main_parser()

File "/home/binstar/miniconda2/lib/python2.7/site-packages/pip/__init__.py", line 125, in create_main_parser

parser = ConfigOptionParser(**parser_kw)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/pip/baseparser.py", line 147, in __init__

self.config.read(self.files)

File "/home/binstar/miniconda2/lib/python2.7/ConfigParser.py", line 305, in read

self._read(fp, filename)

File "/home/binstar/miniconda2/lib/python2.7/ConfigParser.py", line 512, in _read

raise MissingSectionHeaderError(fpname, lineno, line)

ConfigParser.MissingSectionHeaderError: File contains no section headers.

file: /home/binstar/.pip/pip.conf, line: 1

'proxy_servers:\n'

An unexpected error has occurred, please consider sending the

following traceback to the conda GitHub issue tracker at:

https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):

File "/home/binstar/miniconda2/bin/conda", line 6, in <module>

sys.exit(main())

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main

args_func(args, p)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func

args.func(args, p)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 273, in execute

json=args.json, show_channel_urls=args.show_channel_urls)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages

add_pip_installed(prefix, installed, json=json)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 106, in add_pip_installed

for pip_pkg in installed(prefix, output=output):

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 47, in installed

args = pip_args(prefix)

File "/home/binstar/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 26, in pip_args

pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]

File "/home/binstar/miniconda2/lib/python2.7/subprocess.py", line 573, in check_output

raise CalledProcessError(retcode, cmd, output=output)

subprocess.CalledProcessError: Command '['/home/binstar/miniconda2/bin/pip', '-V']' returned non-zero exit status 1

```

**Comment by kalefranz** [comment]
Can you confirm what version of conda the customer is using?

**Comment by tyler-thetyrant** [comment]
Closing as lack of response and is now outdated.
