### ISSUE TITLE
Exception when trying to `conda env remove` in conda 4.1

### ISSUE THREAD

**Issue by seibert** [conda/conda#2684]
Our CI system failed with conda 4.1 when doing the following:
```
conda env remove -n _test --yes
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\jenkins\miniconda\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "C:\jenkins\miniconda\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "C:\jenkins\miniconda\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\jenkins\miniconda\lib\site-packages\conda_env\cli\main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'
```

[Edit: deleted conda info, since that was from before the conda upgrade in the build script.  This is Windows 64-bit, Python 3.5.]

Downgrading to conda 4.0.8 appears to have solved the problem.

**Comment by seibert** [comment]
Closing, as this appears to be a duplicate of #2679.
