### ISSUE TITLE
conda env update error

### ISSUE THREAD

**Issue by rickiepark** [conda/conda#2702]
I got a error when conda env update

```
((bidface)) RickyParkui-MacBook-Pro:bidface rickypark$ conda env update
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications .............
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/rickypark/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/rickypark/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/rickypark/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/rickypark/anaconda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 118, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
TypeError: install() got an unexpected keyword argument 'prune'
((bidface)) RickyParkui-MacBook-Pro:bidface rickypark$
((bidface)) RickyParkui-MacBook-Pro:bidface rickypark$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.0
  conda-build version : 1.21.0
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /Users/rickypark/anaconda  (writable)
  default environment : /Users/rickypark/anaconda/envs/bidface
     envs directories : /Users/rickypark/anaconda/envs
        package cache : /Users/rickypark/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/rickypark/.condarc
    is foreign system : False

RickyParkui-MacBook-Pro:~ rickypark$ conda list conda-env
# packages in environment at /Users/rickypark/anaconda:
#
conda-env                 2.5.0                    py27_0
```

**Comment by kalefranz** [comment]
@rickiepark Is there a reason you wouldn't just prefer `conda update --all` in this case?  Regardless, I'll open an issue for you in the conda-env repo.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-env#249
