### ISSUE TITLE
issue with installing matplotlib

### ISSUE THREAD

**Issue by QihongL** [conda/conda#2726]
(tensorflow)bash-3.2$ conda install matplotlib
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/Qihong/anaconda/envs/tensorflow:

The following packages will be downloaded:

| package | build |
| --- | --- |
| mkl-11.3.3 | 0       101.4 MB |
| numpy-1.11.0 | py27_1         3.1 MB |
| pyparsing-2.1.4 | py27_0          70 KB |
| pytz-2016.4 | py27_0         178 KB |
| python-dateutil-2.5.3 | py27_0         236 KB |
| matplotlib-1.5.1 | np111py27_0         5.9 MB |

```
------------------------------------------------------------
                                       Total:       110.9 MB
```

The following NEW packages will be INSTALLED:

```
cycler:          0.10.0-py27_0    
matplotlib:      1.5.1-np111py27_0
mkl:             11.3.3-0         
numpy:           1.11.0-py27_1    
pyparsing:       2.1.4-py27_0     
python-dateutil: 2.5.3-py27_0     
pytz:            2016.4-py27_0    
```

Proceed ([y]/n)? y

Fetching packages ...
mkl-11.3.3-0.t 100% |#############################################################################################################################| Time: 0:00:14   7.57 MB/s
numpy-1.11.0-p 100% |#############################################################################################################################| Time: 0:00:01   2.52 MB/s
pyparsing-2.1. 100% |#############################################################################################################################| Time: 0:00:00 288.09 kB/s
pytz-2016.4-py 100% |#############################################################################################################################| Time: 0:00:00 511.78 kB/s
python-dateuti 100% |#############################################################################################################################| Time: 0:00:00 536.96 kB/s
matplotlib-1.5 100% |#############################################################################################################################| Time: 0:00:02   2.80 MB/s
Extracting packages ...
[      COMPLETE      ]|################################################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                                                          |  14%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/Qihong/anaconda/envs/tensorflow/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/install.py", line 649, in link
    _link(src, dst, lt)
  File "/Users/Qihong/anaconda/lib/python2.7/site-packages/conda/install.py", line 132, in _link
    shutil.copy2(src, dst)
  File "/Users/Qihong/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/Qihong/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/Users/Qihong/anaconda/envs/tensorflow/lib/python2.7/site-packages/numpy/__config__.py'

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.
