### ISSUE TITLE
Error on install of ipyleaflet

### ISSUE THREAD

**Issue by derekdreery** [conda/conda#2741]
Command and output:

```
$ conda install -c conda-forge ipyleaflet
conda : Using Anaconda Cloud api site https://api.anaconda.org

Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 240, in install
    prefix=prefix)
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\api.py", line 43, in get_index
    unknown=unknown)
  File "C:\Anaconda3\lib\site-packages\conda\utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda3\lib\site-packages\requests\adapters.py", line 376, in send
    timeout=timeout
  File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 554, in urlopen
    self._prepare_proxy(conn)
  File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 750, in _prepare_proxy
    conn.connect()
```

OS: `Windows 7`

**Comment by derekdreery** [comment]
```
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by derekdreery** [comment]
Note: I think this is caused by me being behind a proxy

**Comment by tyler-thetyrant** [comment]
Closing outdated.
