### ISSUE TITLE
conda update --all failed on Windows environment

### ISSUE THREAD

**Issue by vivekratnaparkhi** [conda/conda#2748]
Package update failed on running 'conda update --all' command.
Environment: Windows 8.1(64 bit)
Anaconda version: Anaconda3-4.0.0

Error log:

C:\Users\Vivek>conda update --all
Fetching package metadata .......
Solving package specifications .............

Package plan for installation in environment E:\Programs\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.1            |           py35_0          67 KB
    conda-4.1.1                |           py35_0         248 KB
    ------------------------------------------------------------
                                           Total:         315 KB

The following packages will be UPDATED:

    conda:     4.1.0-py35_0 --> 4.1.1-py35_0
    conda-env: 2.5.0-py35_0 --> 2.5.1-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.5. 100% |###############################| Time: 0:00:00  82.53 kB/s
conda-4.1.1-py 100% |###############################| Time: 0:00:02  85.83 kB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "E:\Programs\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "E:\Programs\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "E:\Programs\Anaconda3\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "E:\Programs\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "E:\Programs\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "E:\Programs\Anaconda3\lib\site-packages\conda\plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "E:\Programs\Anaconda3\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "E:\Programs\Anaconda3\lib\site-packages\conda\instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "E:\Programs\Anaconda3\lib\site-packages\conda\install.py", line 821, in extract
    os.rename(temp_path, path)
PermissionError: [WinError 5] Access is denied: 'E:\\Programs\\Anaconda3\\pkgs\\conda-env-2.5.1-py35_0.tmp' -> 'E:\\Programs\\Anaconda3\\pkgs\\conda-e
nv-2.5.1-py35_0'

**Comment by kalefranz** [comment]
Should be fixed with #2717.
