### ISSUE TITLE
Conda 4.1.2: AttributeError: module 'conda.plan' has no attribute 'PREFIX'

### ISSUE THREAD

**Issue by KI7MT** [conda/conda#2753]
**Traceback**
```
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/ki7mt/anaconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/home/ki7mt/anaconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/ki7mt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/home/ki7mt/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: module 'conda.plan' has no attribute 'PREFIX'
```
**Conda Info**
```
Current conda install:

             platform : linux-64
        conda version : 4.1.2
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/ki7mt/anaconda3  (writable)
  default environment : /home/ki7mt/anaconda3
     envs directories : /home/ki7mt/anaconda3/envs
        package cache : /home/ki7mt/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

**Comment by kalefranz** [comment]
Oh, this is conda-env.  Can you run `conda update conda-env` and then try again?

**Comment by KI7MT** [comment]
+1
```
conda update conda-env

then

conda-env remove -n py35

```
Problem solved. Sorry for the noise.

**Comment by kalefranz** [comment]
No worries!

**Comment by mcg1969** [comment]
This suggests the need for a metadata hotfix...
