### ISSUE TITLE
conda update issue

### ISSUE THREAD

**Issue by hhajar** [conda/conda#2770]

**Comment by hhajar** [comment]
`Traceback (most recent call last):
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    name,
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 423, in install
    common.exception_and_exit(e, error_type=error_type, json=args.json)
  File "//anaconda/lib/python2.7/site-packages/conda/plan.py", line 537, in execute_actions
    return actions
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
  File "//anaconda/lib/python2.7/site-packages/conda/instructions.py", line 95, in UNLINK_CMD
    PROGRESS: PROGRESS_CMD,
  File "//anaconda/lib/python2.7/site-packages/conda/install.py", line 692, in unlink
    if urlstxt:
IOError: [Errno 2] No such file or directory: '//anaconda/conda-meta/conda-3.19.0-py27_0.json'`

**Comment by kalefranz** [comment]
@hhajar in general I'd need more information from you. Specifically the command you actually executed on the command line that led to this stack trace.  Also, we usually ask for the output of `conda info` for additional context.

However from the stack trace, it looks like your conda environment has been corrupted somehow.  If it's possible, the easiest path at the moment would be to just start with a new install of Anaconda.

https://www.continuum.io/downloads

If you continue to have problems, go ahead an file a new ticket with as much information as possible.
