### ISSUE TITLE
BUG: conda 4.1.2 not choosing most recent version of package and installing broken numpy

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#2777]
The following example shows several overlapping issues:

```
$ conda config --add channels defaults

$ conda config --add channels astropy-ci-extras

$ conda update conda
Fetching package metadata: ......
.Solving package specifications: .........

Package plan for installation in environment /home/travis/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.0            |           py27_0          28 KB
    ruamel_yaml-0.11.7         |           py27_0         352 KB
    conda-4.1.2                |           py27_0         198 KB
    ------------------------------------------------------------
                                           Total:         578 KB

The following NEW packages will be INSTALLED:

    ruamel_yaml: 0.11.7-py27_0

The following packages will be UPDATED:

    conda:       4.0.5-py27_0 --> 4.1.2-py27_0 
    conda-env:   2.4.5-py27_0 --> 2.5.0-py27_0 

Fetching packages ...
conda-env-2.5. 100% |################################| Time: 0:00:00  15.26 MB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00   1.67 MB/s
conda-4.1.2-py 100% |################################| Time: 0:00:00   3.80 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%

$ conda create -n test python=2.7
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/travis/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2h             |                1         3.2 MB
    sqlite-3.13.0              |                0         4.0 MB
    zlib-1.2.8                 |                3         101 KB
    setuptools-23.0.0          |           py27_0         455 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:         9.2 MB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2h-1     
    pip:        8.1.2-py27_0 
    python:     2.7.11-0     
    readline:   6.2-2        
    setuptools: 23.0.0-py27_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py27_0
    zlib:       1.2.8-3      

Fetching packages ...
openssl-1.0.2h 100% |################################| Time: 0:00:00  39.56 MB/s
sqlite-3.13.0- 100% |################################| Time: 0:00:00  33.10 MB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00  14.54 MB/s
setuptools-23. 100% |################################| Time: 0:00:00  17.04 MB/s
pip-8.1.2-py27 100% |################################| Time: 0:00:00  29.52 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
No psutil available.
To proceed, please conda install psutil#
# To activate this environment, use:
# $ source activate test
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate test
prepending /home/travis/miniconda/envs/test/bin to PATH

$ conda install numpy
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/travis/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.5.1                |           py27_0         3.7 MB  astropy-ci-extras

The following NEW packages will be INSTALLED:

    numpy: 1.5.1-py27_0 astropy-ci-extras

Fetching packages ...
numpy-1.5.1-py 100% |################################| Time: 0:00:00  43.73 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%

$ conda install python=2.7 astropy
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /home/travis/miniconda/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.8.2                |           py27_0         7.3 MB
    astropy-1.0.3              |       np18py27_0         7.4 MB  astropy-ci-extras
    ------------------------------------------------------------
                                           Total:        14.7 MB

The following NEW packages will be INSTALLED:

    astropy: 1.0.3-np18py27_0 astropy-ci-extras

The following packages will be UPDATED:

    numpy:   1.5.1-py27_0     astropy-ci-extras --> 1.8.2-py27_0

Fetching packages ...
numpy-1.8.2-py 100% |################################| Time: 0:00:00  57.28 MB/s
astropy-1.0.3- 100% |################################| Time: 0:00:00  38.93 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%

$ python -c 'import numpy'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/home/travis/miniconda/envs/test/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory
```

The issues are:

* ``conda is retrieving astropy 1.0.3 from the ``astropy-ci-extras`` channel instead of astropy 1.1.2 or astropy 1.2 from the ``defaults`` channel
* The resulting Numpy installation is broken

Full Travis log: https://travis-ci.org/astrofrog/wcsaxes/builds/138867049

**Comment by bsipocz** [comment]
Also it should have never picked up numpy 1.5.1

**Comment by astrofrog** [comment]
@bsipocz - so for Numpy, what about the solution of checking if it's ``stable`` and if so, changing to the latest stable version, but still using ``conda``?

For Astropy we can't really do that, because for e.g. Numpy 1.8 and Astropy 1.2 it might not be in conda. But the latest stable Numpy *should* be in conda.

**Comment by bsipocz** [comment]
👍 Great idea

**Comment by astrofrog** [comment]
Note that ``conda search numpy`` does show e.g. Numpy 1.11 but for some weird reason, it picks 1.5.1:

```
[0K$ conda search numpy
Fetching package metadata .........
numpy                        1.5.1                  py26_ce0  defaults        
                             1.5.1                 py26_pro0  defaults        [mkl]
                             1.5.1                    py27_0  astropy-ci-extras/linux-64 
                             1.5.1                  py27_ce0  defaults        
                             1.5.1                 py27_pro0  defaults        [mkl]
                             1.5.1                    py26_1  defaults        
                             1.5.1                   py26_p1  defaults        [mkl]
                             1.5.1                    py27_1  defaults        
                             1.5.1                   py27_p1  defaults        [mkl]
                             1.5.1                    py26_3  defaults        
                             1.5.1                   py26_p3  defaults        [mkl]
                             1.5.1                    py27_3  defaults        
                             1.5.1                   py27_p3  defaults        [mkl]
                             1.5.1                    py26_4  defaults        
                             1.5.1                   py26_p4  defaults        [mkl]
                             1.5.1                    py27_4  defaults        
                             1.5.1                   py27_p4  defaults        [mkl]
                             1.5.1                    py26_6  defaults        
                             1.5.1                   py26_p6  defaults        [mkl]
                             1.5.1                    py27_6  defaults        
                             1.5.1                   py27_p6  defaults        [mkl]
                             1.6.2                  py26_ce0  defaults        
                             1.6.2                 py26_pro0  defaults        [mkl]
                             1.6.2                  py27_ce0  defaults        
                             1.6.2                 py27_pro0  defaults        [mkl]
                             1.6.2                    py32_0  astropy-ci-extras/linux-64 
                             1.6.2                    py26_1  defaults        
                             1.6.2                   py26_p1  defaults        [mkl]
                             1.6.2                    py27_1  defaults        
                             1.6.2                   py27_p1  defaults        [mkl]
                             1.6.2                    py26_3  defaults        
                             1.6.2                   py26_p3  defaults        [mkl]
                             1.6.2                    py27_3  defaults        
                             1.6.2                   py27_p3  defaults        [mkl]
                             1.6.2                    py26_4  defaults        
                             1.6.2                   py26_p4  defaults        [mkl]
                             1.6.2                    py27_4  defaults        
                             1.6.2                   py27_p4  defaults        [mkl]
                             1.6.2                    py26_5  defaults        
                             1.6.2                   py26_p5  defaults        [mkl]
                             1.6.2                    py27_5  defaults        
                             1.6.2                   py27_p5  defaults        [mkl]
                             1.7.0b2                py26_ce0  defaults        
                             1.7.0b2               py26_pro0  defaults        [mkl]
                             1.7.0b2                py27_ce0  defaults        
                             1.7.0b2               py27_pro0  defaults        [mkl]
                             1.7.0b2               py33_pro0  defaults        [mkl]
                             1.7.0rc1                 py26_0  defaults        
                             1.7.0rc1                py26_p0  defaults        [mkl]
                             1.7.0rc1                 py27_0  defaults        
                             1.7.0rc1                py27_p0  defaults        [mkl]
                             1.7.0rc1                 py33_0  defaults        
                             1.7.0rc1                py33_p0  defaults        [mkl]
                             1.7.0                    py26_0  defaults        
                             1.7.0                   py26_p0  defaults        [mkl]
                             1.7.0                    py27_0  defaults        
                             1.7.0                   py27_p0  defaults        [mkl]
                             1.7.0                    py33_0  defaults        
                             1.7.0                   py33_p0  defaults        [mkl]
                             1.7.1                    py26_0  defaults        
                             1.7.1                   py26_p0  defaults        [mkl]
                             1.7.1                    py27_0  defaults        
                             1.7.1                   py27_p0  defaults        [mkl]
                             1.7.1                    py32_0  astropy-ci-extras/linux-64 
                             1.7.1                    py33_0  defaults        
                             1.7.1                   py33_p0  defaults        [mkl]
                             1.7.1                    py26_2  defaults        
                             1.7.1                   py26_p2  defaults        [mkl]
                             1.7.1                    py27_2  defaults        
                             1.7.1                   py27_p2  defaults        [mkl]
                             1.7.1                    py33_2  defaults        
                             1.7.1                   py33_p2  defaults        [mkl]
                             1.7.1                    py26_3  defaults        
                             1.7.1                   py26_p3  defaults        [mkl]
                             1.7.1                    py27_3  defaults        
                             1.7.1                   py27_p3  defaults        [mkl]
                             1.7.1                    py33_3  defaults        
                             1.7.1                   py33_p3  defaults        [mkl]
                             1.7.1                    py34_3  defaults        
                             1.7.1                   py34_p3  defaults        [mkl]
                             1.7.2                    py32_0  astropy-ci-extras/linux-64 
                             1.8.0                    py26_0  defaults        
                             1.8.0                   py26_p0  defaults        [mkl]
                             1.8.0                    py27_0  defaults        
                             1.8.0                   py27_p0  defaults        [mkl]
                             1.8.0                    py33_0  defaults        
                             1.8.0                   py33_p0  defaults        [mkl]
                             1.8.1                    py26_0  defaults        
                             1.8.1                   py26_p0  defaults        [mkl]
                             1.8.1                    py27_0  defaults        
                             1.8.1                   py27_p0  defaults        [mkl]
                             1.8.1                    py32_0  astropy-ci-extras/linux-64 
                             1.8.1                    py33_0  defaults        
                             1.8.1                   py33_p0  defaults        [mkl]
                             1.8.1                    py34_0  defaults        
                             1.8.1                   py34_p0  defaults        [mkl]
                             1.8.2                    py26_0  defaults        
                             1.8.2                   py26_p0  defaults        [mkl]
                             1.8.2                    py27_0  defaults        
                             1.8.2                   py27_p0  defaults        [mkl]
                             1.8.2                    py33_0  defaults        
                             1.8.2                   py33_p0  defaults        [mkl]
                             1.8.2                    py34_0  defaults        
                             1.8.2                   py34_p0  defaults        [mkl]
                             1.8.2                    py26_1  defaults        
                             1.8.2                   py26_p1  defaults        [mkl]
                             1.8.2                    py27_1  defaults        
                             1.8.2                   py27_p1  defaults        [mkl]
                             1.8.2                    py33_1  defaults        
                             1.8.2                   py33_p1  defaults        [mkl]
                             1.8.2                    py34_1  defaults        
                             1.8.2                   py34_p1  defaults        [mkl]
                             1.9.0                    py26_0  defaults        
                             1.9.0                   py26_p0  defaults        [mkl]
                             1.9.0                    py27_0  defaults        
                             1.9.0                   py27_p0  defaults        [mkl]
                             1.9.0                    py33_0  defaults        
                             1.9.0                   py33_p0  defaults        [mkl]
                             1.9.0                    py34_0  defaults        
                             1.9.0                   py34_p0  defaults        [mkl]
                             1.9.1                    py26_0  defaults        
                             1.9.1                   py26_p0  defaults        [mkl]
                             1.9.1                    py27_0  defaults        
                             1.9.1                   py27_p0  defaults        [mkl]
                             1.9.1                    py33_0  defaults        
                             1.9.1                   py33_p0  defaults        [mkl]
                             1.9.1                    py34_0  defaults        
                             1.9.1                   py34_p0  defaults        [mkl]
                             1.9.2                    py26_0  defaults        
                             1.9.2                   py26_p0  defaults        [mkl]
                             1.9.2                    py27_0  defaults        
                             1.9.2                   py27_p0  defaults        [mkl]
                             1.9.2                    py33_0  defaults        
                             1.9.2                   py33_p0  defaults        [mkl]
                             1.9.2                    py34_0  defaults        
                             1.9.2                   py34_p0  defaults        [mkl]
                             1.9.2                    py27_1  defaults        
                             1.9.2                   py27_p1  defaults        [mkl]
                             1.9.2                    py34_1  defaults        
                             1.9.2                   py34_p1  defaults        [mkl]
                             1.9.2                    py35_1  defaults        
                             1.9.2                    py27_2  defaults        
                             1.9.2                   py27_p2  defaults        [mkl]
                             1.9.2                    py34_2  defaults        
                             1.9.2                   py34_p2  defaults        [mkl]
                             1.9.2                    py35_2  defaults        
                             1.9.3                    py27_0  defaults        
                             1.9.3                   py27_p0  defaults        [mkl]
                             1.9.3                    py34_0  defaults        
                             1.9.3                   py34_p0  defaults        [mkl]
                             1.9.3                    py35_0  defaults        
                             1.9.3                   py35_p0  defaults        [mkl]
                             1.9.3                    py27_1  defaults        
                             1.9.3              py27_nomkl_1  defaults        [nomkl]
                             1.9.3                    py34_1  defaults        
                             1.9.3              py34_nomkl_1  defaults        [nomkl]
                             1.9.3                    py35_1  defaults        
                             1.9.3              py35_nomkl_1  defaults        [nomkl]
                             1.9.3                    py27_2  defaults        
                             1.9.3              py27_nomkl_2  defaults        [nomkl]
                             1.9.3                    py34_2  defaults        
                             1.9.3              py34_nomkl_2  defaults        [nomkl]
                             1.9.3                    py35_2  defaults        
                             1.9.3              py35_nomkl_2  defaults        [nomkl]
                             1.9.3                    py27_3  defaults        
                             1.9.3                    py34_3  defaults        
                             1.9.3                    py35_3  defaults        
                             1.10.0                   py27_0  defaults        
                             1.10.0                  py27_p0  defaults        [mkl]
                             1.10.0                   py34_0  defaults        
                             1.10.0                  py34_p0  defaults        [mkl]
                             1.10.0                   py35_0  defaults        
                             1.10.0                  py35_p0  defaults        [mkl]
                             1.10.1                   py27_0  defaults        
                             1.10.1                  py27_p0  defaults        [mkl]
                             1.10.1                   py34_0  defaults        
                             1.10.1                  py34_p0  defaults        [mkl]
                             1.10.1                   py35_0  defaults        
                             1.10.1                  py35_p0  defaults        [mkl]
                             1.10.2                   py27_0  defaults        
                             1.10.2                  py27_p0  defaults        [mkl]
                             1.10.2                   py34_0  defaults        
                             1.10.2                  py34_p0  defaults        [mkl]
                             1.10.2                   py35_0  defaults        
                             1.10.2                  py35_p0  defaults        [mkl]
                             1.10.4                   py27_0  defaults        
                             1.10.4             py27_nomkl_0  defaults        [nomkl]
                             1.10.4                   py34_0  defaults        
                             1.10.4             py34_nomkl_0  defaults        [nomkl]
                             1.10.4                   py35_0  defaults        
                             1.10.4             py35_nomkl_0  defaults        [nomkl]
                             1.10.4                   py27_1  defaults        
                             1.10.4             py27_nomkl_1  defaults        [nomkl]
                             1.10.4                   py34_1  defaults        
                             1.10.4             py34_nomkl_1  defaults        [nomkl]
                             1.10.4                   py35_1  defaults        
                             1.10.4             py35_nomkl_1  defaults        [nomkl]
                             1.10.4                   py27_2  defaults        
                             1.10.4             py27_nomkl_2  defaults        [nomkl]
                             1.10.4                   py34_2  defaults        
                             1.10.4             py34_nomkl_2  defaults        [nomkl]
                             1.10.4                   py35_2  defaults        
                             1.10.4             py35_nomkl_2  defaults        [nomkl]
                             1.11.0                   py27_0  defaults        
                             1.11.0             py27_nomkl_0  defaults        [nomkl]
                             1.11.0                   py34_0  defaults        
                             1.11.0             py34_nomkl_0  defaults        [nomkl]
                             1.11.0                   py35_0  defaults        
                             1.11.0             py35_nomkl_0  defaults        [nomkl]
                             1.11.0                   py27_1  defaults        
                             1.11.0             py27_nomkl_1  defaults        [nomkl]
                             1.11.0                   py34_1  defaults        
                             1.11.0             py34_nomkl_1  defaults        [nomkl]
                             1.11.0                   py35_1  defaults        
                             1.11.0             py35_nomkl_1  defaults        [nomkl]
```

**Comment by astrofrog** [comment]
I've explored this a bit further, and this doesn't depend on whether or not I add the ``defaults`` channel (we were adding it because of the issues with a previous version of conda), and the issue also happens if I add the defaults channel AFTER the astropy-ci-extras channel.

**Comment by kalefranz** [comment]
Conda 4.1.x introduces the concept of channel priority as a factor in determining dependency resolution and which packages to install.  If a package exists in a higher-priority channel, it will always be preferred, even if a lower priority channel has a more recent (i.e. "higher") version of the package.  Per-package channel-pinning is a forthcoming feature.

In your specific case, you are putting the `astropy-ci-extras` channel *ahead* of the defaults channel in channel priority.  (Look at `~/.condarc` after you issue your series of `conda config` commands.)  Since numpy 1.5.1 [is present in](https://anaconda.org/astropy-ci-extras/numpy/files?version=1.5.1) `astropy-ci-extras`, that is the package that is chosen.

The behavior is working as-designed in conda 4.1.2.  The two options you have right now are removing numpy 1.5.1 from the `astropy-ci-extras` channel (if it's your channel), or putting the `defaults` channel *ahead* of the `astropy-ci-extras` channel in channel priority.  As I said before, more intelligent per-package channel pinning is forthcoming, which will provide further options on how to deal with something like this.

**Comment by kalefranz** [comment]
@astrofrog I just recognized we added a `channel_priority` config parameter as a bool in `~/.condarc`.

Try `conda config --set channel_priority false` as a solution to your current problem.

**Comment by astrofrog** [comment]
@kalefranz - ok, thanks!
