### ISSUE TITLE
nb_conda_kernels creates error

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#2785]
```bash
(stable)└─❱❱❱ conda install -c conda-forge nb_conda_kernels                    1 ⏎  +4312 21:57 ❰─┘
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/klay6683/miniconda3/envs/stable:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    backports.shutil_get_terminal_size-1.0.0|           py35_0           5 KB
    python-simplegeneric-0.8.1 |           py35_0           7 KB
    nb_conda_kernels-1.0.3     |           py35_0          28 KB
    ------------------------------------------------------------
                                           Total:          40 KB

The following NEW packages will be INSTALLED:

    backports.shutil_get_terminal_size: 1.0.0-py35_0
    nb_conda_kernels:                   1.0.3-py35_0
    python-simplegeneric:               0.8.1-py35_0

The following packages will be DOWNGRADED:

    sqlite:                             3.13.0-0 --> 3.9.2-0

Proceed ([y]/n)? y

Fetching packages ...
backports.shut 100% |####################################################| Time: 0:00:00   2.18 MB/s
python-simpleg 100% |####################################################| Time: 0:00:00   1.87 MB/s
nb_conda_kerne 100% |####################################################| Time: 0:00:00 349.23 kB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                 |  50%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/klay6683/miniconda3/envs/stable/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/klay6683/miniconda3/lib/python3.4/site-packages/conda/install.py", line 650, in link
    os.makedirs(dst_dir)
  File "/Users/klay6683/miniconda3/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/klay6683/miniconda3/envs/stable/lib/python3.5/site-packages/simplegeneric-0.8.1-py3.5.egg-info'
```

Here's my conda info:
```bash
(stable)└─❱❱❱ conda info                                                       1 ⏎  +4313 22:06 ❰─┘
Current conda install:

             platform : osx-64
        conda version : 4.0.8
  conda-build version : 1.20.3
       python version : 3.4.4.final.0
     requests version : 2.10.0
     root environment : /Users/klay6683/miniconda3  (writable)
  default environment : /Users/klay6683/miniconda3/envs/stable
     envs directories : /Users/klay6683/miniconda3/envs
        package cache : /Users/klay6683/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/klay6683/.condarc
    is foreign system : False
```

**Comment by kalefranz** [comment]
This issue was moved to conda-forge/python-simplegeneric-feedstock#2
