### ISSUE TITLE
html5lib installation aborts: "WindowsError: [Error 183] Cannot create a file when that file already exists"

### ISSUE THREAD

**Issue by rngShard** [conda/conda#2789]
html5lib not listed in Anaconda Navigator environment, trying to install via command line

>steps

C:\Users\IBM_ADMIN>conda install -c anaconda html5lib=0.999
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\IBM_ADMIN\Anaconda2:

The following NEW packages will be INSTALLED:

html5lib: 0.999-py27_0 anaconda

The following packages will be UPDATED:

conda:    4.1.2-py27_0          --> 4.1.2-py27_0 anaconda

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:<

>Traceback

Traceback (most recent call last):
  File "C:\Users\IBM_ADMIN\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\plan.py", line 589, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\install.py", line 845, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\IBM_ADMIN\Anaconda2\lib\site-packages\conda\install.py", line 233, in exp_backoff_fn
    result = fn(*args)
WindowsError: [Error 183] Cannot create a file when that file already exists <

**Comment by kalefranz** [comment]
@rngShard Can you give us the output of `conda info`?

**Comment by kalefranz** [comment]
@mcg1969 

    conda: 4.1.2-py27_0 --> 4.1.2-py27_0 anaconda

Does that look right to you?

**Comment by mcg1969** [comment]
It does if `anaconda` is a higher priority channel than `defaults`... (of course, as we discussed earlier, we might want to find a way to merge those)

**Comment by kalefranz** [comment]
I guess in the `-c` case it would be.  So we do *change* packages when the version number is the same and the channel priority has been rearranged?

**Comment by mcg1969** [comment]
Sure. I see no other way. After all, we cannot depend on the build numbers giving us something to compare to across channels. So even if the version _and_ build numbers are the same, all we have left is channel priority.

**Comment by mingwandroid** [comment]
If we had a checksum to hand for each installed package, could we avoid unnecessary updates like this. Anyway, IMHO this is all tangential to the real problem that Windows can't delete or rename files or folders that are open:

https://github.com/conda/conda/issues/2828#issuecomment-228138526

**Comment by kalefranz** [comment]
I think this is going to be an intermittent and ongoing problem we're going to have to iterate on.  Closing this ticket for now, and we'll have iterative progress.
