### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by yasheshgaur** [conda/conda#2797]
The following error happens when I do a 'conda list' after installing miniconda2 by running the bash script.

Traceback (most recent call last):
  File "/home/yashesh/miniconda2/bin/pip", line 4, in <module>
    import pip
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/__init__.py", line 14, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3130, in <module>
    @_call_aside
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3116, in _call_aside
    f(*args, **kwargs)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3155, in _initialize_master_working_set
    add_activation_listener(lambda dist: dist.activate())
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 956, in subscribe
    callback(dist)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3155, in <lambda>
    add_activation_listener(lambda dist: dist.activate())
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2653, in activate
    for pkg in self._get_metadata('namespace_packages.txt'):
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2643, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1624, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1616, in get_metadata
    return self._get(self._fn(self.egg_info, name))
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1727, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 13] Permission denied: '/home/python27/protobuf-3.0.0b2.post2-py2.7.egg/EGG-INFO/namespace_packages.txt'

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/yashesh/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 273, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 106, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 47, in installed
    args = pip_args(prefix)
  File "/home/yashesh/miniconda2/lib/python2.7/site-packages/conda/pip.py", line 26, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/home/yashesh/miniconda2/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/yashesh/miniconda2/bin/pip', '-V']' returned non-zero exit status 1

===========

Output for 'conda info':

Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /home/yashesh/miniconda2  (writable)
  default environment : /home/yashesh/miniconda2
     envs directories : /home/yashesh/miniconda2/envs
        package cache : /home/yashesh/miniconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

===============

**Comment by kalefranz** [comment]
Try `conda update conda`. I think that will fix your problem.
