### ISSUE TITLE
Error Removing/Updating a Conda Environment

### ISSUE THREAD

**Issue by brakedust** [conda/conda#2798]
I recently started getting error when trying to remove conda environments.  I'm not sure what version I was on, but I did a fresh install of the most recent version as of 6/21/2016 (v4.1.2).  The problem still persists.  I get a different error when trying to update an environment.

### Error Message for conda env remove
```
PS> conda env remove -n ceres_data_dev
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "d:\anaconda\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "d:\anaconda\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "d:\anaconda\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "d:\anaconda\lib\site-packages\conda_env\cli\main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: module 'conda.plan' has no attribute 'PREFIX'
```

### conda info output
```
Current conda install:

             platform : win-64
        conda version : 4.1.2
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : d:\anaconda  (writable)
  default environment : d:\anaconda
     envs directories : d:\anaconda\envs
        package cache : d:\anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

### conda env update error message
```
PS> conda env update -f .\environment_dev.yml
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .......
Solving package specifications: ..........
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "d:\anaconda\Scripts\conda-env-script.py", line 5, in <module>
    sys.exit(conda_env.cli.main.main())
  File "d:\anaconda\lib\site-packages\conda_env\cli\main.py", line 68, in main
    return args_func(args, parser)
  File "d:\anaconda\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "d:\anaconda\lib\site-packages\conda_env\cli\main_update.py", line 118, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
TypeError: install() got an unexpected keyword argument 'prune'
```

**Comment by kalefranz** [comment]
Yeah you have conda-env version 2.5.0. Running `conda update conda-env` will fix your problem.  As of conda 4.1.3, conda-env will be updated along with conda.
