### ISSUE TITLE
xarray Installing error

### ISSUE THREAD

**Issue by Yefee** [conda/conda#2803]
conda info:
```
            platform : osx-64
        conda version : 4.1.2
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/Yefee/miniconda2  (writable)
  default environment : /Users/Yefee/miniconda2
     envs directories : /Users/Yefee/miniconda2/envs
        package cache : /Users/Yefee/miniconda2/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/Yefee/.condarc
    is foreign system : False
```

When installing xarray, an error occurs.
```python
Traceback (most recent call last):
  File "/Users/Yefee/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 589, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 80, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/install.py", line 1083, in link
    _link(src, dst, lt)
  File "/Users/Yefee/miniconda2/lib/python2.7/site-packages/conda/install.py", line 210, in _link
    shutil.copy2(src, dst)
  File "/Users/Yefee/miniconda2/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/Yefee/miniconda2/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/Users/Yefee/miniconda2/pkgs/hdf5-1.8.17-1/bin/activate'
```

**Comment by kalefranz** [comment]
This issue was moved to conda-forge/xarray-feedstock#4
