### ISSUE TITLE
`conda env update` results in TypeError exception

### ISSUE THREAD

**Issue by talumbau** [conda/conda#2811]
`conda env update` yields this error on Mac OS X:

```
0054-tjalumbaugh:tax_reform_viz_1 talumbau$ conda env update
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........
Fetching packages ...
decorator-4.0. 100% |###########################################################################################################| Time: 0:00:00 268.62 kB/s
entrypoints-0. 100% |###########################################################################################################| Time: 0:00:00   6.96 MB/s
ptyprocess-0.5 100% |###########################################################################################################| Time: 0:00:00 405.52 kB/s
pyzmq-15.2.0-p 100% |###########################################################################################################| Time: 0:00:00   1.17 MB/s
setuptools-23. 100% |###########################################################################################################| Time: 0:00:00 629.21 kB/s
simplegeneric- 100% |###########################################################################################################| Time: 0:00:00   3.06 MB/s
toolz-0.8.0-py 100% |###########################################################################################################| Time: 0:00:00 564.08 kB/s
pickleshare-0. 100% |###########################################################################################################| Time: 0:00:00   2.96 MB/s
pip-8.1.2-py35 100% |###########################################################################################################| Time: 0:00:00   1.79 MB/s
pytest-2.9.2-p 100% |###########################################################################################################| Time: 0:00:00 750.77 kB/s
terminado-0.6- 100% |###########################################################################################################| Time: 0:00:00 393.59 kB/s
jupyter_client 100% |###########################################################################################################| Time: 0:00:00 690.91 kB/s
notebook-4.2.1 100% |###########################################################################################################| Time: 0:00:03   1.70 MB/s
Extracting packages ...
[      COMPLETE      ]|##############################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##############################################################################################################################| 100%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/talumbau/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/talumbau/miniconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/talumbau/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/talumbau/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_update.py", line 118, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
TypeError: install() got an unexpected keyword argument 'prune'
```

Output of `conda info`:

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.1.2
  conda-build version : 1.21.0
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : /Users/talumbau/miniconda3  (writable)
  default environment : /Users/talumbau/miniconda3
     envs directories : /Users/talumbau/miniconda3/envs
        package cache : /Users/talumbau/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/trent/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/trent/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/ospc/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/ospc/noarch/
          config file : /Users/talumbau/.condarc
    is foreign system : False
```

contents of `environment.yml` is:

```
name: tre
dependencies:
- pytest
- setuptools
- python
- numpy
- pandas <=0.16.2
- numba
- toolz
- six
- ipython
- ipython-notebook
- pip:
  - pytest-pep8
```

**Comment by talumbau** [comment]
Workaround is as follows:

 - delete existing conda environment by removing directory on `envs/` directory
 - `conda env create` and create fresh environment.

**Comment by kalefranz** [comment]
@mcg1969 I think we might need to short-circuit conda-env update like we did remove...

**Comment by kalefranz** [comment]
@talumbau Can you try `conda update conda-env` and make sure you're running conda-env 2.5.1, then verify the error still exists?

**Comment by mcg1969** [comment]
Possibly, but there's that whole `environment.yml` thing to deal with.

**Comment by talumbau** [comment]
Ah, @kalefranz you are correct - I was not on the latest conda-env!  I executed `conda update conda-env` and saw as follows:

```
0054-tjalumbaugh:tax_reform_viz_1 talumbau$ conda update conda-env
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/talumbau/miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.5.1            |           py35_0          27 KB

The following packages will be UPDATED:

    conda-env: 2.5.0-py35_0 --> 2.5.1-py35_0

Proceed ([y]/n)? y
```

I then executed `conda env update` and did not get the error, but because I had just deleted and recreated the environment, there were no packages that needed updating, so I can't be sure I hit the same code path with v2.5.1. I had tried `conda update conda` prior to filing this issue, but did not know to execute `conda update conda-env`. Thanks! I'll leave it up to you on what to do, but I'm fine closing since I was not using the latest `conda-env`. Just thought this was a feature of conda and not a separate tool

**Comment by kalefranz** [comment]
Yeah we more tightly coupled updating conda-env with conda coming out in this next conda patch release because of just this issue.
