### ISSUE TITLE
conda env remove --name name error

### ISSUE THREAD

**Issue by jseabold** [conda/conda#2818]
```
|10534 $ conda env remove --name name
Fetching package metadata .........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/username/.miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/username/.miniconda3/lib/python3.4/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/username/.miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/username/.miniconda3/lib/python3.4/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'

|10535 $ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.2
  conda-build version : 1.21.0
       python version : 3.4.4.final.0
     requests version : 2.8.1
     root environment : /Users/username/.miniconda3  (writable)
  default environment : /Users/username/.miniconda3
     envs directories : /Users/username/.miniconda3/envs
        package cache : /Users/username/.miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/username/.condarc
    is foreign system : False
```

**Comment by mcg1969** [comment]
I'm pretty sure this is fixed with the latest conda-env. Can you do `conda update conda-env` to confirm? @kalefranz we really need to get that version tie fixed, I'm thinking with a metadata hotfix...

**Comment by jseabold** [comment]
I was on 2.5.0. Trying to downgrade now to get something working.

**Comment by kalefranz** [comment]
@mcg1969 that would be fine.  Also 4.1.3 is going out tomorrow.

**Comment by mcg1969** [comment]
> I was on 2.5.0. Trying to downgrade now to get something working.

The latest is 2.5.1, and includes a fix for this...

**Comment by jseabold** [comment]
I just tried upgrading conda and it tried to install 2.5.0. Will try again.

**Comment by jseabold** [comment]
2.5.1 asked me to install nbformat (?) and then gives this on a freshly exported environment

```
|10596 $ conda env create -f environment3.yml
Error: Can't process without a name
environment3.yml is not a valid yaml file.
Environment with requierements.txt file needs a name
```

**Comment by jseabold** [comment]
Strike that. Don't reply to issues through e-mail. Crossed threads. This is fixed. Thanks.
