### ISSUE TITLE
`file:///` channels newly broken?

### ISSUE THREAD

**Issue by pkgw** [conda/conda#2836]
My `.condarc` defines a local channel using the `file:///...` URI style. Historically, it's worked fine, but starting recently (conda 4.1?) I run into showstopper problems.

If I try to install a package from my channel:

```
$ conda install casa-data
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /a:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    casa-data-r10774           |                0       257.2 MB  file:///home/peter/sw/conda-recipes

The following NEW packages will be INSTALLED:

    casa-data: r10774-0 file:///home/peter/sw/conda-recipes

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
casa-data-r107 100% |########################################################################| Time: 0:00:01 268.51 MB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the                                                     |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/a/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/a/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/a/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/a/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/a/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/a/lib/python2.7/site-packages/conda/plan.py", line 589, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/a/lib/python2.7/site-packages/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "/a/lib/python2.7/site-packages/conda/instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "/a/lib/python2.7/site-packages/conda/install.py", line 833, in extract
    rec = package_cache()[dist]
KeyError: u'file:///home/peter/sw/conda-recipes::casa-data-r10774-0'
```

(For what it's worth, the packages in this channel are the same as in [my anaconda.org channel](https://anaconda.org/pkgw), but I don't see any evidence that the problems are associated with the specific packages themselves.)

If I try to `conda update --all`, it tries to update the local packages that I installed before these problems cropped up, and I see a hint that suggests that maybe the URIs are getting munged in a way that's causing the `KeyError`s: it tries to do upgrades of the form

```
iraf: 2.16.1-1 file:///home/peter/sw/conda-recipes/linux-64 --> 2.16.1-1 file:///home/peter/sw/conda-recipes
```

(The only difference is the `/linux-64` at the end of the first URL.) Trying to proceed with the update yields the same form of `KeyError`.

**Comment by kalefranz** [comment]
Conda 4.1.3 is about to be released (if it isn't available already).  This should be fixed with #2812.
