### ISSUE TITLE
source activate broken in 4.1.3

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#2866]
While trying to debug https://github.com/conda/conda-build/issues/1050, I noticed that the underlying problem is in conda itself:
```
$ source activate /Users/ilan/minonda/envs/_build
Traceback (most recent call last):
  File "/Users/ilan/minonda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ilan/conda/conda/cli/main.py", line 48, in main
    activate.main()
  File "/Users/ilan/conda/conda/cli/activate.py", line 105, in main
    shelldict = shells[shell]
KeyError: '/Users/ilan/minonda/envs/_build'
```
and also:
```
$ source activate _build
Traceback (most recent call last):
  File "/Users/ilan/minonda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ilan/conda/conda/cli/main.py", line 48, in main
    activate.main()
  File "/Users/ilan/conda/conda/cli/activate.py", line 105, in main
    shelldict = shells[shell]
KeyError: '_build'
```

**Comment by ilanschnell** [comment]
CC @kalefranz @msarahan @csoja

**Comment by ilanschnell** [comment]
Sorry, I was in development mode and had an old `activate` in my `bin/`.  However, using the correct one, it sort of works:
```
$ source activate _build
usage: conda [-h] [-V] [--debug] command ...
conda: error: argument command: invalid choice: '..activateroot' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'init', 'clean', 'package', 'bundle')
prepending /Users/ilan/minonda/envs/_build/bin to PATH
(_build) atx-xserve-02:~ ilan$ 
```

**Comment by msarahan** [comment]
You still have a mixed install. ..activateroot does not exist any more. In this case, it looks like your activate scripts are the wrong ones.

**Comment by ilanschnell** [comment]
Thanks.  I had updated `activate`, but not `deactivate`.  Problem solved.
