### ISSUE TITLE
File exits but IOError: [Errno 2] No such file or directory: happens

### ISSUE THREAD

**Issue by ovz** [conda/conda#2883]
When creating a conda environment I ran into an issue below. Note that `ls /Users/ovz/anaconda/pkgs/icu-56.1-3/bin/activate` actually reports the file in question exists. 

```
   wheel:                0.29.0-py27_0
    yaml:                 0.1.6-0         conda-forge
    zlib:                 1.2.8-3         conda-forge

Linking packages ...
An unexpected error has occurred, please consider sending the                                          |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/ovz/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/plan.py", line 591, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 79, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/install.py", line 1089, in link
    _link(src, dst, lt)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/install.py", line 208, in _link
    shutil.copy2(src, dst)
  File "/Users/ovz/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/Users/ovz/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/Users/ovz/anaconda/pkgs/icu-56.1-3/bin/activate'
prepending /Users/ovz/spm/spm-qt/build/conda/current_platform/bin to PATH
salford:spm-qt ovz$ ls /Users/ovz/anaconda/pkgs/icu-56.1-3/bin/activate
/Users/ovz/anaconda/pkgs/icu-56.1-3/bin/activate
salford:spm-qt ovz$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.3
    conda-env version : 2.5.0
  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /Users/ovz/anaconda  (writable)
  default environment : /Users/ovz/anaconda
     envs directories : /Users/ovz/anaconda/envs
        package cache : /Users/ovz/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/salford_systems/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/salford_systems/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ovz/.condarc
         offline mode : False
    is foreign system : False

```

**Comment by lainiewright** [comment]
+1

**Comment by lentils** [comment]
I created an ticket in conda-forge/icu-feedstock/issues/9 since this is really a recipe issue rather than a conda issue. 

Looks like they are on it and a PR is coming soon. 

For `conda-forge` issues, I'd recommend posting directly to the feedstock repo for that particular package.

**Comment by kalefranz** [comment]
Thanks @lentils
