### ISSUE TITLE
build fails when using Anaconda Enterprise 

### ISSUE THREAD

**Issue by msarahan** [conda/conda#2892]
@ijstokes commented on [Mon Jun 27 2016](https://github.com/conda/conda-build/issues/1052)

I'm trying to build a Conda package on a system that has just Anaconda Enterprise configured as the single repository source.  It does not appear to work.   The reason is unclear (stacktrace):

```
$ conda build conda.recipe
Removing old build environment
Removing old work directory
BUILD START: wakari-server-1.10.9-GIT_STUB
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ..........An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 380, in build
    override_channels=override_channels)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 278, in create_env
    override_channels=override_channels)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 266, in get_build_index
    prepend=not override_channels)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/api.py", line 43, in get_index
    unknown=unknown)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 396, in result
    return self.__get_result()
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 103, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
IOError: invalid data stream
```
and the requsted `conda info`:

```
$ conda info -a
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 3.19.3
  conda-build version : 1.18.2
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /opt/wakari/anaconda  (writable)
  default environment : /opt/wakari/anaconda
     envs directories : /opt/wakari/anaconda/envs
        package cache : /opt/wakari/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/wakari/linux-64/
                        https://conda.anaconda.org/wakari/noarch/
                        http://localhost:8080/conda/anaconda/linux-64/
                        http://localhost:8080/conda/anaconda/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /opt/wakari/anaconda/.condarc
    is foreign system : False

# conda environments:
#
root                  *  /opt/wakari/anaconda

sys.version: 2.7.11 |Anaconda 2.4.1 (64-bit)| (defaul...
sys.prefix: /opt/wakari/anaconda
sys.executable: /opt/wakari/anaconda/bin/python
conda location: /opt/wakari/anaconda/lib/python2.7/site-packages/conda
conda-analysispackage: /opt/wakari/anaconda/bin/conda-analysispackage
conda-build: /opt/wakari/anaconda/bin/conda-build
conda-convert: /opt/wakari/anaconda/bin/conda-convert
conda-develop: /opt/wakari/anaconda/bin/conda-develop
conda-env: /opt/wakari/anaconda/bin/conda-env
conda-index: /opt/wakari/anaconda/bin/conda-index
conda-inspect: /opt/wakari/anaconda/bin/conda-inspect
conda-metapackage: /opt/wakari/anaconda/bin/conda-metapackage
conda-pipbuild: /opt/wakari/anaconda/bin/conda-pipbuild
conda-server: /opt/wakari/anaconda/bin/conda-server
conda-sign: /opt/wakari/anaconda/bin/conda-sign
conda-skeleton: /opt/wakari/anaconda/bin/conda-skeleton
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /opt/wakari/wakari-server/bin:/opt/wakari/anaconda/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license

```

---

@ijstokes commented on [Mon Jun 27 2016](https://github.com/conda/conda-build/issues/1052#issuecomment-228691996)

Ah, I think I know the cause: The Anaconda Repository instance at `localhost:8080` has an expired license. Still, the error should be something different.

---

@msarahan commented on [Mon Jun 27 2016](https://github.com/conda/conda-build/issues/1052#issuecomment-228743818)

Is there something conda-build can do better here?  IMHO, it looks like conda should be throwing a better error, and conda-build should just exit out with that error.

---

@msarahan commented on [Mon Jun 27 2016](https://github.com/conda/conda-build/issues/1052#issuecomment-228913617)

Ian, I'm moving this issue to conda.  Conda-build certainly needs to display the error better here, but I think the error coming from conda needs to be better first.

**Comment by mcg1969** [comment]
I believe we've seen this before. I agree that better messaging is warranted. We basically need to wrap the bzip decompress and the json decoding in a `try/except` block so we can isolate those errors.

**Comment by kalefranz** [comment]
@dorzel Is working on *much* better error handling now.
