### ISSUE TITLE
4.0.9 `conda skeleton` problem

### ISSUE THREAD

**Issue by RSully** [conda/conda#2902]
```
Traceback (most recent call last):
  File "/data/anaconda3/bin/conda-skeleton", line 3, in <module>
    from conda_build.main_skeleton import main
  File "/data/anaconda3/lib/python3.5/site-packages/conda_build/main_skeleton.py", line 10, in <module>
    from conda_build.main_build import args_func
  File "/data/anaconda3/lib/python3.5/site-packages/conda_build/main_build.py", line 23, in <module>
    from conda_build.build import bldpkg_path
  File "/data/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 32, in <module>
    from conda_build import environ, source, tarcheck, external
  File "/data/anaconda3/lib/python3.5/site-packages/conda_build/environ.py", line 17, in <module>
    from conda_build import source
  File "/data/anaconda3/lib/python3.5/site-packages/conda_build/source.py", line 18, in <module>
    from conda_build.utils import rm_rf, tar_xf, unzip, safe_print_unicode
  File "/data/anaconda3/lib/python3.5/site-packages/conda_build/utils.py", line 14, in <module>
    from conda.utils import md5_file, unix_path_to_win
ImportError: cannot import name 'unix_path_to_win'
```

I'm not sure if 4.0 is supported any longer or what the status is, I pinned to that for the moment until things settled for 4.1.

edit: continues if i downgrade to 4.0.8. works if I upgrade to 4.1

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1064
