### ISSUE TITLE
Can't install numpy or matplotlib in ipython

### ISSUE THREAD

**Issue by Mostafa-Ali-Mansour** [conda/conda#2906]
An unexpected error has occurred, please consider sending the            |  62%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Krietallo\Miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\Krietallo\Miniconda2\lib\site-packages\conda\install.py", line 236, in exp_backoff_fn
    result = fn(*args)
WindowsError: [Error 5] Access is denied

**Comment by HugoTian** [comment]
Please update conda, either run "conda update conda" or reinstall anaconda or miniconda.

The new version of conda should solve this problem.

I am about to close the issue, and if there is still some problem, feel free to reopen it and @ me
