### ISSUE TITLE
UnboundLocalError when trying to install a package from local archive

### ISSUE THREAD

**Issue by ovz** [conda/conda#2907]
Please se output below. The package itself is available at https://anaconda.org/salford_systems/boost-gcc5. 

```
(build/conda/current_platform/) salford:pysstreenet-demos ovz$ conda install /Users/ovz/anaconda/pkgs/boost-gcc5-1.60.0-py27_0.tar.bz2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/ovz/spm/pyss/pyss-demos/pysstreenet-demos/build/conda/current_platform/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 196, in install
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "/Users/ovz/anaconda/lib/python2.7/site-packages/conda/misc.py", line 79, in explicit
    is_file = schannel.startswith('file:') and schannel.endswith('/')
UnboundLocalError: local variable 'schannel' referenced before assignment
(build/conda/current_platform/) salford:pysstreenet-demos ovz$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.3
    conda-env version : 2.5.0
  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /Users/ovz/anaconda  (writable)
  default environment : /Users/ovz/spm/pyss/pyss-demos/pysstreenet-demos/build/conda/current_platform
     envs directories : /Users/ovz/anaconda/envs
        package cache : /Users/ovz/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/salford_systems/osx-64/
                        https://conda.anaconda.org/t/<TOKEN>/salford_systems/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/ovz/.condarc
         offline mode : False
    is foreign system : False

(build/conda/current_platform/) salford:pysstreenet-demos ovz$
```

**Comment by ovz** [comment]
I was able to install it from online location though

```
(build/conda/current_platform/) salford:pysstreenet-demos ovz$ conda install boost-gcc5
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/ovz/spm/pyss/pyss-demos/pysstreenet-demos/build/conda/current_platform:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    boost-gcc5-1.59.0          |           py27_3        12.0 MB  salford_systems

The following NEW packages will be INSTALLED:

    boost-gcc5: 1.59.0-py27_3 salford_systems
    icu:        54.1-0
    libgcc-5:   5.4.0-0       salford_systems

Proceed ([y]/n)? y

Fetching packages ...
boost-gcc5-1.5 100% |##########################################################################| Time: 0:00:30 408.18 kB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################################################| 100%
```

**Comment by mcg1969** [comment]
Thanks for the report. I've identified the problem. As a short-term workaround, please copy the file out of the package cache and into a different location, _then_ install.

**Comment by kalefranz** [comment]
This was fixed in a conda patch release.  The PR also included regression tests.
