### ISSUE TITLE
KeyError: u'file:///opt/anaconda/channel::tcltk-8.6 when creating env from file

### ISSUE THREAD

**Issue by komailrk** [conda/conda#2909]
While creating env from file which looks like:

```
name: py27
dependencies:
- python=2.7.11=8
- tcltk=8.6.5=06242016
- openssl=1.0.2h=1
- pip=8.1.2=py27_0
- readline=6.2=2
- setuptools=23.0.0=py27_0
- sqlite=3.13.0=0
- wheel=0.29.0=py27_0
- xz=5.2.2=0
- zlib=1.2.8=3
- pip:
  - linecache2==1.0.0
  - pexpect==4.1.0
  - ptyprocess==0.5.1
  - py==1.4.31
  - pytest==2.9.2
  - six==1.10.0
  - traceback2==1.4.0
  - unittest2==1.1.0
  - xmlrunner==1.7.7
prefix: /opt/miniconda/envs/linux-64/py27
```

Conda Info:
```
Current conda install:

             platform : linux-64
        conda version : 4.1.2
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /opt/miniconda  (writable)
  default environment :/opt/miniconda
     envs directories : /opt/miniconda/pftools/envs/linux-64
        package cache : /opt/miniconda/envs/linux-64/.pkgs
         channel URLs : file:///opt/anaconda/channel/linux-64/
                        file:///opt/anaconda/channel/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /opt/miniconda/.condarc
    is foreign system : False
```

```
Traceback (most recent call last):
  File "/opt/miniconda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/opt/miniconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 99, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/opt/miniconda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 20, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/plan.py", line 589, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "/opt/miniconda/lib/python2.7/site-packages/conda/install.py", line 833, in extract
    rec = package_cache()[dist]
KeyError: u'file:///opt/anaconda/channel::tcltk-8.6.5-06242016'
```

**Comment by mcg1969** [comment]
Can you do `conda update conda` and try again, please?

**Comment by komailrk** [comment]
The update did solve the problem.

I will investigate as to why my update didn't update conda after I installed miniconda

Thanks for the help
