### ISSUE TITLE
conda list: breaks due to pip import error

### ISSUE THREAD

**Issue by nileshmoodley** [conda/conda#2920]
I am trying to create a virtual environment with the following code: 
``conda create -n devtest python=2.7`` 
``source activate devtest``
``conda list``

The following error appears:

```
Traceback` (most recent call last):
  File "/home/nmoodley/.conda/envs/devtest/bin/pip", line 4, in <module>
    import pip
ImportError: No module named pip

Traceback (most recent call last):
  File "/home/nmoodley/.conda/envs/devtest/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 273, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/pip.py", line 106, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/opt/anaconda/lib/python2.7/site-packages/conda/pip.py", line 47, in installed
    args = pip_args(prefix)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/pip.py", line 26, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/opt/anaconda/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/home/nmoodley/.conda/envs/devtest/bin/pip', '-V']' returned non-zero exit status 1
```

Instead, if I create a python 3 virtual environment, this break **does not** occur.

This issue also **does not** occur if you use the following: `conda create -n devtest python=2.7 --copy`. Python 2.7.11-0 seems to work fine, so it appears that a possible symlink or path related issue was introduced since then.

Here is the output of `conda info`:

```
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.0.9
  conda-build version : 1.20.3
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : /opt/anaconda  (read only)
  default environment : /home/nmoodley/.conda/envs/devtest
     envs directories : /home/nmoodley/.conda/envs
                        /home/nmoodley/envs
                        /opt/anaconda/envs
        package cache : /home/nmoodley/.conda/envs/.pkgs
                        /home/nmoodley/envs/.pkgs
                        /opt/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        file:///opt/anaconda/conda-bld/linux-64/
                        file:///opt/anaconda/conda-bld/noarch/
          config file : /home/nmoodley/.condarc
    is foreign system : False
```

**Comment by kalefranz** [comment]
This was fixed with `conda 4.1.x`.  `conda update conda` and you should be good to go.
