### ISSUE TITLE
KeyError ('depends') in resolve.py

### ISSUE THREAD

**Issue by aldanor** [conda/conda#293]
(sorry for cross-posting this from anaconda-issues, not sure which tracker actually gets watched for conda-related stuff) 

Hi there, we are using `conda` for distributing our Python packages within a dev team, and there's a following problem (I guess it has to do with dependencies not being set explicitly for custom packages):

```
Traceback (most recent call last):
  File "/home/smirnov/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/smirnov/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 156, in main
    args.func(args, p)
  File "/home/smirnov/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 149, in execute
    force=args.force, only_names=only_names)
  File "/home/smirnov/anaconda/lib/python2.7/site-packages/conda/plan.py", line 230, in install_actions
    add_defaults_to_specs(r, linked, specs)
  File "/home/smirnov/anaconda/lib/python2.7/site-packages/conda/plan.py", line 195, in add_defaults_to_specs
    for spec in specs
  File "/home/smirnov/anaconda/lib/python2.7/site-packages/conda/plan.py", line 197, in <genexpr>
    for ms2 in r.ms_depends(fn))
  File "/home/smirnov/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 176, in ms_depends
    depends = self.index[fn]['depends']
KeyError: 'depends'
```

Fixing is straightforward, in `resolve.py`, line 176, change

``` python
depends = self.index[fn]['depends']
```

to

``` python
depends = self.index[fn].get('depends', [])
```

I've been patching it myself, but everytime conda updates itself, I have to patch it again manually...

**Comment by zxdawn** [comment]
@aldanor @ilanschnell 
I want to create my own mirror of anaconda.
So,I downloaded `main`, `free` and `pro` packages from [Anaconda repositories](https://repo.continuum.io/pkgs/).
Since the Anaconda channel on anaconda.org is an aggregated mirror of the packages in https://repo.continuum.io/pkgs/main, https://repo.continuum.io/pkgs/free, and https://repo.continuum.io/pkgs/pro, I downloaded all of them and link files under `linux-64` and `noarch` to corresponding directory of new directory named anaconda.

├── anaconda
│   ├── linux-64
│   └── noarch
└── pkgs
    ├── free
    │   ├── linux-64
    │   └── noarch
    ├── main
    │   ├── linux-64
    │   └── noarch
    └── pro
        ├── linux-64
        └── noarch

 I got similar error when running `conda index anaconda`:
```
Traceback (most recent call last):1.0.14-0.tar.bz2: 100%|███████████████████████████████████████████████| 362/362 [00:43<00:00,  1.68s/it]
  File "/public/software/anaconda/anaconda3/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 75, in main
    return execute(sys.argv[1:])
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 71, in execute
    verbose=args.verbose, progress=args.progress, hotfix_source_repo=args.hotfix_source_repo)
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 390, in update_index
    hotfix_source_repo=hotfix_source_repo)
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 273, in update_index
    patch_generator=patch_generator, verbose=verbose, progress=progress, hotfix_source_repo=hotfix_source_repo)
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 831, in index
    augmented_repodata = _augment_repodata(subdirs, patched_repodata, patch_instructions)
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 573, in _augment_repodata
    namemap, ambiguous_namekeys = _collect_namemap(subdirs, patched_repodata, patch_instructions)
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 449, in _collect_namemap
    namespace, name_in_channel, name = _determine_namespace(info)
  File "/public/software/anaconda/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 280, in _determine_namespace
    depends_names = {MatchSpec(spec).name for spec in info['depends']}
KeyError: 'depends'
```
