### ISSUE TITLE
Cannot Perform an Update on 4.1 with Windows 7

### ISSUE THREAD

**Issue by dave-fl** [conda/conda#2934]
Not sure why this is happening.

I am seeing the following (I added print statements to fetch.py and my browser has no issue getting to these URLS):

conda update --all

Fetching package metadata ...SSL verification error: [SSL: UNKNOWN_PROTOCOL] unk
nown protocol (_ssl.c:645)
SSL verification error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)
..SSL verification error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)
SSL verification error: [SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:645)
....

Proceed ([y]/n)?

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_fun
c
    exit_code = args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 64, in ex
ecute
    install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in insta
ll
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 595, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 136, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 48, in FETCH
_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 369, in download
    with Locked(dst_dir):
  File "C:\Anaconda3\lib\site-packages\conda\lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "C:\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Anaconda3\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is
incorrect: 'C:\Anaconda3\pkgs\http:'

Current conda install:

```
         platform : win-64
    conda version : 4.1.4
conda-env version : 2.5.1
```

  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\dave.condarc
         offline mode : False
    is foreign system : False

**Comment by dave-fl** [comment]
Apparently this machine required me to manually enter some proxy information.  Windows was using an automatic proxy configuration script.  Perhaps it was not being detected correctly?

**Comment by kalefranz** [comment]
Further proxy issues will be tracked via https://github.com/conda/conda/issues/5220
