### ISSUE TITLE
conda update anaconda crashes on Bokeh

### ISSUE THREAD

**Issue by ivoflipse** [conda/conda#294]
I was trying `conda update anaconda and when it started to update Bokeh it gave an error:

```
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
Ignored: psutil-0.7.1-py27_0#############################                |  67%
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
menuinst Exception:  ] |                                                 |   1%
Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 176, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Anaconda\lib\site-packages\menuinst\__init__.py", line 41, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda\lib\site-packages\menuinst\win32.py", line 128, in create
    icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda (3
2-bit)\Wakari (in the cloud).lnk' - error 0x80070005
An unexpected error has occurred, please consider sending the            |  10%
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 150, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 91, in execute
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 331, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 316, in execute_plan
    install.link(config.pkgs_dir, prefix, arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 292, in link
    os.makedirs(dst_dir)
  File "C:\Anaconda\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Anaconda\\Lib/site-packages/
bokeh/server/static/vendor/bokehjs/coffee'
```

Here's my conda info

```
Current conda install:

             platform : win-32
        conda version : 1.9.1
       conda location : C:\Anaconda\lib\site-packages\conda
     root environment : C:\Anaconda
  default environment : C:\Anaconda
         channel URLs : http://repo.continuum.io/pkgs/dev/win-32/
                        http://repo.continuum.io/pkgs/gpl/win-32/
                        http://repo.continuum.io/pkgs/free/win-32/
                        http://repo.continuum.io/pkgs/pro/win-32/
          config file : C:\Anaconda\.condarc
```

Perhaps this might have been because I tried installing a previous version from Github instead of Anaconda. Deleting the Bokeh folder made it go on without a problem.

It also seems that when I run this from command prompt without admin rights, it fails to add some menu items.

**Comment by kalefranz** [comment]
multi-user installs have been fixed on conda 4.3
