### ISSUE TITLE
test error in master

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#2958]
Hit the merge button before I should have on #2956 

    _________________________________________ IntegrationTests.test_create_install_update_remove _________________________________________
    Traceback (most recent call last):
      File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 315, in install
        shortcuts=shortcuts)
      File "/Users/kfranz/continuum/conda/conda/plan.py", line 467, in install_actions
        sys.exit("Error: 'conda' can only be installed into the root environment")
    SystemExit: Error: 'conda' can only be installed into the root environment

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/kfranz/continuum/conda/tests/test_create.py", line 233, in test_create_install_update_remove
        sout, serr = run_command(Commands.INSTALL, prefix, 'conda')
      File "/Users/kfranz/continuum/conda/tests/test_create.py", line 114, in run_command
        args.func(args, p)
      File "/Users/kfranz/continuum/conda/conda/cli/main_install.py", line 69, in execute
        install(args, parser, 'install')
      File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 377, in install
        error_type=error_type)
      File "/Users/kfranz/continuum/conda/conda/cli/common.py", line 605, in exception_and_exit
        error_and_exit('; '.join(map(str, exc.args)), **kwargs)
      File "/Users/kfranz/continuum/conda/conda/cli/common.py", line 599, in error_and_exit
        sys.exit(message)
    SystemExit: Error: 'conda' can only be installed into the root environment

**Comment by kalefranz** [comment]
This should be fixed now.
