### ISSUE TITLE
Issue with scipy and libgcc

### ISSUE THREAD

**Issue by astrofrog** [conda/conda#2975]
I am having issues on MacOS X 10.11 creating a clean environment with scipy in a clean install of miniconda:

```
$ conda create -n debug-scipy python=3.5 scipy nomkl
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/tom/miniconda3/envs/debug-scipy:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nomkl-1.0                  |                0          486 B
    numpy-1.11.1               |     py35_nomkl_0         2.7 MB
    scipy-0.17.1               |np111py35_nomkl_1        11.9 MB
    ------------------------------------------------------------
                                           Total:        14.6 MB

The following NEW packages will be INSTALLED:

    nomkl:      1.0-0                   
    numpy:      1.11.1-py35_nomkl_0      [nomkl]
    openssl:    1.0.2h-1                
    pip:        8.1.2-py35_0            
    python:     3.5.1-5                 
    readline:   6.2-2                   
    scipy:      0.17.1-np111py35_nomkl_1 [nomkl]
    setuptools: 23.0.0-py35_0           
    sqlite:     3.13.0-0                
    tk:         8.5.18-0                
    wheel:      0.29.0-py35_0           
    xz:         5.2.2-0                 
    zlib:       1.2.8-3                 

Proceed ([y]/n)? y

Fetching packages ...
nomkl-1.0-0.ta 100% |################################| Time: 0:00:00 512.68 kB/s
numpy-1.11.1-p 100% |################################| Time: 0:00:03 910.61 kB/s
scipy-0.17.1-n 100% |################################| Time: 0:00:05   2.33 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
#
# To activate this environment, use:
# $ source activate debug-scipy
#
# To deactivate this environment, use:
# $ source deactivate
#

$ source activate debug-scipy
discarding /Users/tom/miniconda3/bin from PATH
prepending /Users/tom/miniconda3/envs/debug-scipy/bin to PATH

$ python -c 'import scipy.optimize'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/__init__.py", line 232, in <module>
    from .optimize import *
  File "/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: dlopen(/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/minpack2.so, 2): Library not loaded: /usr/local/lib/libgcc_s.1.dylib
  Referenced from: /Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/minpack2.so
  Reason: image not found
```

Note that installing `libgcc` doesn't help:

```
$ conda install libgcc
Fetching package metadata: ....
Solving package specifications: .........

Package plan for installation in environment /Users/tom/miniconda3/envs/debug-scipy:

The following NEW packages will be INSTALLED:

    libgcc: 4.8.5-1

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
(debug-scipy)mac-robitaille2-4:~ tom$ python -c 'import scipy.optimize'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/__init__.py", line 232, in <module>
    from .optimize import *
  File "/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/optimize.py", line 37, in <module>
    from .linesearch import (line_search_wolfe1, line_search_wolfe2,
  File "/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/linesearch.py", line 18, in <module>
    from scipy.optimize import minpack2
ImportError: dlopen(/Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/minpack2.so, 2): Library not loaded: /usr/local/lib/libgcc_s.1.dylib
  Referenced from: /Users/tom/miniconda3/envs/debug-scipy/lib/python3.5/site-packages/scipy/optimize/minpack2.so
  Reason: image not found
```

I don't have any `libgcc` in /usr/local/lib, but I don't think that should be required?

**Comment by parejkoj** [comment]
Looks like I'm not the only one with this problem! I just installed the nomkl conda and am running into a similar error, this time with fftpack. I'll try backing up one scipy version and see if that solves it.

```python
  File "/Users/parejkoj/lsst/lsstsw/stack/DarwinX86/ip_diffim/12.0-5-gb893996/python/lsst/ip/diffim/imageDecorrelation.py", line 25, in <module>
    from scipy.fftpack import fft2, ifft2, ifftshift
  File "/Users/parejkoj/lsst/lsstsw/miniconda/lib/python2.7/site-packages/scipy/fftpack/__init__.py", line 95, in <module>
    from .basic import *
  File "/Users/parejkoj/lsst/lsstsw/miniconda/lib/python2.7/site-packages/scipy/fftpack/basic.py", line 12, in <module>
    from . import _fftpack
ImportError: dlopen(/Users/parejkoj/lsst/lsstsw/miniconda/lib/python2.7/site-packages/scipy/fftpack/_fftpack.so, 2): Library not loaded: /usr/local/lib/libgcc_s.1.dylib
  Referenced from: /Users/parejkoj/lsst/lsstsw/miniconda/lib/python2.7/site-packages/scipy/fftpack/_fftpack.so
  Reason: image not found
```

**Comment by parejkoj** [comment]
Also for the record, I had installed scipy 0.17.1-np110py27_nomkl_1. Downgrading to 0.17.1-np110py27_nomkl_1 seems to have fixed it.

**Comment by jzuhone** [comment]
This is also broken without specifying `nomkl` as well.

**Comment by varunus** [comment]
I am also having this issue, even with the new scipy 0.18.

However, I was able to work around the issue by creating a symlink to /usr/lib/libgcc_s.1.dylib in /usr/local/lib.

**Comment by malzantot** [comment]
I had the same issue and worked around by creating a symlink too.

**Comment by kalefranz** [comment]
This is more of an issue for https://github.com/ContinuumIO/anaconda-issues, but seems like it might be resolved now, so am just going to close it rather than move it.

**Comment by exowanderer** [comment]
In case further people have issues here (as I did), I had to symbolically link:

`/usr/local/Cellar/gcc/7.2.0/lib/gcc/7/libgcc_s.1.dylib` 
to 
`/Users/$USER/anaconda/lib/libgcc_s.1.dylib`

This is probably related to both the fact that I'm using anaconda and version issues with the other `libgcc` instances that I have installed. So grabbing the latest `libgcc` and symlinking it into anaconda lib directory fixed the issue for me

**Comment by mingwandroid** [comment]
@exowanderer, it is pretty unlikely that the issue you are having is related to this issue unless you are deliberately using software that is more than a year old, and if you are, well, I'd recommend you install the latest AD 5.0.1 release instead.

**Comment by mingwandroid** [comment]
To expand on that slightly, the `Anaconda Distribution` has not used GCC and nothing in it is built with GCC. This has been the case since September. We use clang exclusively on macOS now.
