### ISSUE TITLE
Cannot update on Windows 10.

### ISSUE THREAD

**Issue by ACBlock** [conda/conda#2981]
When I attempt to update on Windows 10, I receive the following:
Traceback (most recent call last):
  File "C:\Users\Andy-PC\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\Andy-PC\Anaconda2\lib\site-packages\conda\install.py", line 238, in exp_backoff_fn
    result = fn(*args)
WindowsError: [Error 5] Access is denied

Conda info returns:

Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.1.5
    conda-env version : 2.5.1
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\Andy-PC\Anaconda2  (writable)
  default environment : C:\Users\Andy-PC\Anaconda2
     envs directories : C:\Users\Andy-PC\Anaconda2\envs
        package cache : C:\Users\Andy-PC\Anaconda2\pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/win-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\Andy-PC\.condarc
         offline mode : False
    is foreign system : False

**Comment by mcg1969** [comment]
Do you have a virus scanner running? If so, can you please disable it and try again?

**Comment by ACBlock** [comment]
Disabling my virus scanner seems to have fixed the issue, thank you.
