### ISSUE TITLE
Error in installing zipline

### ISSUE THREAD

**Issue by ylidz** [conda/conda#2985]
I got an error when I installed zipline using conda. The traceback and the conda info is as follows:
Traceback (most recent call last):
  File "C:\Users\LanceLi\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\LanceLi\Anaconda2\lib\site-packages\conda\install.py", line 236, in exp_backoff_fn
    result = fn(*args)
WindowsError: [Error 5]

C:\Users\LanceLi>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : C:\Users\LanceLi\Anaconda2  (writable)
  default environment : C:\Users\LanceLi\Anaconda2
     envs directories : C:\Users\LanceLi\Anaconda2\envs
        package cache : C:\Users\LanceLi\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by mcg1969** [comment]
Can you please update to 4.1.6 and try again?

**Comment by ylidz** [comment]
It goes well this time. Many thank for that.
