### ISSUE TITLE
Unexpected error when installing pyodbc package

### ISSUE THREAD

**Issue by krjhnsn** [conda/conda#3003]
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\kwjohnson>python --version
Python 3.5.1 :: Anaconda 4.1.0 (64-bit)

C:\Users\kwjohnson>cd C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3

C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3>conda install pyodbc
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs
/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
.Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
...
Solving package specifications: ..........
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-env-2.5.1-py35_0.tar.bz2
  - http://bremen/pkgs/free::conda-env-2.5.1-py35_0.tar.bz2

Package plan for installation in environment C:\Users\kwjohnson\AppData\Local\Co
ntinuum\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyodbc-3.0.10              |           py35_0          47 KB

The following NEW packages will be INSTALLED:

    pyodbc: 3.0.10-py35_0

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\Scripts\conda-scrip
t.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\fetch.py", line 369, in download
    with Locked(dst_dir):
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\site-packages\c
onda\lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\os.py", line 23
1, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\os.py", line 23
1, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\os.py", line 23
1, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3\lib\os.py", line 24
1, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is
incorrect: 'C:\\Users\\kwjohnson\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\ht
tp:'

C:\Users\kwjohnson\AppData\Local\Continuum\Anaconda3>

**Comment by HugoTian** [comment]
I think this happens since "http:// "is in file path. 

In conda4.2 , we have new lock , and we will fix the issue.

**Comment by kalefranz** [comment]
This should have been long-ago resolved with 4.2.

**Comment by krjhnsn** [comment]
Sounds good, thank you.
