### ISSUE TITLE
error updating app glueviz

### ISSUE THREAD

**Issue by mechgeer** [conda/conda#3011]
When attempting to update glueviz through the Anaconda Launcher the resulting error occurred.

Machine OS - Windows 2012R2

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 83, in UNLINK_CMD
    unlink(state['prefix'], arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 1125, in unlink
    delete_linked_data(prefix, dist, delete=True)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 915, in delete_linked_data
    os.unlink(meta_path)
WindowsError: [Error 5] Access is denied: 'C:\Anaconda\conda-meta\astropy-1.0.3-np19py27_0.json'

**Comment by HugoTian** [comment]
On Windows, attempting to remove a file that is in use causes an exception to be raised. Could you please restart the machine and try again ?
