### ISSUE TITLE
OSError: [Errno 17] File exists

### ISSUE THREAD

**Issue by msarahan** [conda/conda#3014]
@sebastian-luna-valero commented on [Tue Oct 06 2015](https://github.com/conda/conda-build/issues/625)

Dear All,

I am getting the following error while building a new package.

Could you please point to any reason?

Many thanks,
Sebastian.

```
Linking packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):                                                                                                                                                                           |   4%
  File "/Users/sebastian/Desktop/conda/build-1/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/main_build.py", line 190, in main
    args_func(args, p)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/main_build.py", line 468, in args_func
    args.func(args, p)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/main_build.py", line 391, in execute
    override_channels=args.override_channels, include_recipe=args.include_recipe)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/build.py", line 380, in build
    override_channels=override_channels)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda_build/build.py", line 285, in create_env
    plan.execute_actions(actions, index, verbose=verbose)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/instructions.py", line 91, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/instructions.py", line 87, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/site-packages/conda/install.py", line 593, in link
    os.makedirs(dst_dir)
  File "/Users/sebastian/Desktop/conda/build-1/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/sebastian/Desktop/conda/build-1/envs/_build_placehold_placehold_placehold/bin'
MRCs-MacBook-Pro-2:cgat-recipes sebastian$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.1
  conda-build version : 1.18.0
       python version : 2.7.10.final.0
     requests version : 2.7.0
     root environment : /Users/sebastian/Desktop/conda/build-1  (writable)
  default environment : /Users/sebastian/Desktop/conda/build-1
     envs directories : /Users/sebastian/Desktop/conda/build-1/envs
        package cache : /Users/sebastian/Desktop/conda/build-1/pkgs
         channel URLs : https://conda.anaconda.org/cgat/osx-64/
                        https://conda.anaconda.org/cgat/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/r/osx-64/
                        https://conda.anaconda.org/r/noarch/
          config file : /Users/sebastian/.condarc
    is foreign system : False
```

---

@hflamboauto1 commented on [Fri Jul 08 2016](https://github.com/conda/conda-build/issues/625#issuecomment-231397006)

same here

conda env create -f=sasasas.yml
conda env update -n root -f=sasasas.yml

```
Traceback (most recent call last):
  File "/opt/conda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 112, in execute
    installer.install(prefix, specs, args, env, prune=args.prune)
  File "/opt/conda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 20, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/conda/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python2.7/site-packages/conda/instructions.py", line 79, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/opt/conda/lib/python2.7/site-packages/conda/install.py", line 1055, in link
    os.makedirs(dst_dir)
  File "/opt/conda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/opt/conda/lib/python2.7/site-packages/statsmodels-0.6.1-py2.7-linux-x86_64.egg-info

```

---

@msarahan commented on [Fri Jul 08 2016](https://github.com/conda/conda-build/issues/625#issuecomment-231401872)

Please update conda and try again.  Although you may encounter this problem while using conda-build because it creates environments with conda, the problem is ultimately in conda, not conda-build.  I am moving this issue over there.

**Comment by sebastian-luna-valero** [comment]
Hi,

Still experiencing the same problem:
```
BUILD START: cgat-devel-0.3-py27r3.2.2_2
    (actual version deferred until further download or env creation)
BUILD START: cgat-devel-0.3-py27r3.2.2_2
Package: cgat-devel-0.3-py27r3.2.2_2
no source - creating empty work folder
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda-build/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/sebastian/conda/conda-build/build-testing/bin/conda-metapackage", line 5, in <module>
    sys.exit(main())
  File "/sebastian/conda/conda-build/build-testing/lib/python2.7/site-packages/conda_build/main_metapackage.py", line 108, in main
    args_func(args, p)
  File "/sebastian/conda/conda-build/build-testing/lib/python2.7/site-packages/conda_build/main_build.py", line 408, in args_func
    args.func(args, p)
  File "/sebastian/conda/conda-build/build-testing/lib/python2.7/site-packages/conda_build/main_metapackage.py", line 126, in execute
    build(m)
  File "/sebastian/conda/conda-build/build-testing/lib/python2.7/site-packages/conda_build/build.py", line 548, in build
    os.makedirs(source.WORK_DIR)
  File "/sebastian/conda/conda-build/build-testing/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/sebastian/conda/conda-build/build-testing/conda-bld/work'
```

Here is the info
```
conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.7
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /sebastian/conda/conda-build/build-testing  (writable)
  default environment : /sebastian/conda/conda-build/build-testing
     envs directories : /sebastian/conda/conda-build/build-testing/envs
        package cache : /sebastian/conda/conda-build/build-testing/pkgs
         channel URLs : https://conda.anaconda.org/t/<TOKEN>/cgat/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/cgat/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/r/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/r/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/bioconda/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/bioconda/noarch/
          config file : /ifs/home/sebastian/.condarc
         offline mode : False
    is foreign system : False
```

**Comment by sebastian-luna-valero** [comment]
Here are the steps to reproduce the problem on my end:
```
wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
bash Miniconda-latest-Linux-x86_64.sh -b -p t1
export PATH=`pwd`/t1/bin:$PATH
conda install conda-build
./cgat-devel-test.sh
```

where:
```
#!/usr/bin/env bash

conda metapackage \
 --build-number 0 \
 --dependencies \
 python \
 zlib \
 openssl \
 --summary "Computational Genomics Analysis Toolkit" \
 cgat-devel \
 0.1
```

I hope that helps.

**Comment by msarahan** [comment]
I have attempted to reproduce this in https://github.com/conda/conda-build/pull/1160 - metapackage seems to work fine in 1.21.8, which was tagged yesterday but might not yet be available as a package.  It is available on conda-forge, but not yet on defaults.  This later error of yours is different from your earlier error.  The later error is definitely conda-build, but I'm concerned that the earlier error, which is conda, may still exist.  Please try this again with 1.21.8, and we'll dig in from there.

**Comment by sebastian-luna-valero** [comment]
Great! 

I have just tried with conda-build version 1.21.9 (at conda-forge) with the metapackage command and it works!

**Comment by msarahan** [comment]
Thanks for the feedback.  Glad it works!  Closing this issue.
