### ISSUE TITLE
Conda 4.1.6 completely broken??

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#3022]
I updated my conda to the latest 4.1.6 which seemed to work fine:
```
λ conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ........
.Solving package specifications: .........

Package plan for installation in environment C:\bin\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-3.5.2               |                1        23.9 MB
    conda-env-2.5.1            |           py35_0          67 KB
    ruamel_yaml-0.11.7         |           py35_0         203 KB
    conda-4.1.6                |           py35_0         246 KB
    ------------------------------------------------------------
                                           Total:        24.4 MB

The following NEW packages will be INSTALLED:

    ruamel_yaml: 0.11.7-py35_0

The following packages will be UPDATED:

    conda:       4.0.8-py35_0 --> 4.1.6-py35_0
    conda-env:   2.4.5-py35_0 --> 2.5.1-py35_0
    python:      3.5.1-4      --> 3.5.2-1

Proceed ([y]/n)? y

Fetching packages ...
python-3.5.2-1 100% |###############################| Time: 0:00:13   1.80 MB/s
conda-env-2.5. 100% |###############################| Time: 0:00:00  99.24 kB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:01 144.64 kB/s
conda-4.1.6-py 100% |###############################| Time: 0:00:01 131.65 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

...however conda is now completely broken - any attempt to do anything raises a ValueError in platform.py when trying to parse the Python version:
```python-traceback
λ conda list conda
Traceback (most recent call last):
  File "C:\bin\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\bin\Anaconda3\lib\site-packages\conda\cli\main.py", line 94, in main
    imported = importlib.import_module(module)
  File "C:\bin\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\bin\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 18, in <module>
    from ..egg_info import get_egg_info
  File "C:\bin\Anaconda3\lib\site-packages\conda\egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "C:\bin\Anaconda3\lib\site-packages\conda\misc.py", line 18, in <module>
    from .instructions import RM_FETCHED, FETCH, RM_EXTRACTED, EXTRACT, UNLINK, LINK, SYMLINK_CONDA
  File "C:\bin\Anaconda3\lib\site-packages\conda\instructions.py", line 7, in <module>
    from .fetch import fetch_pkg
  File "C:\bin\Anaconda3\lib\site-packages\conda\fetch.py", line 26, in <module>
    from .connection import CondaSession, unparse_url, RETRIES
  File "C:\bin\Anaconda3\lib\site-packages\conda\connection.py", line 51, in <module>
    python=platform.python_implementation(),
  File "C:\bin\Anaconda3\lib\platform.py", line 1292, in python_implementation
    return _sys_version()[0]
  File "C:\bin\Anaconda3\lib\platform.py", line 1252, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]'
```

**Comment by dhirschfeld** [comment]
I'd post conda info, but that doesn't work either! :stuck_out_tongue_winking_eye: 
```
λ cat .condarc
channels:
  - conda-forge
  - dhirschfeld
  - defaults
```

**Comment by dhirschfeld** [comment]
My workaround (for now) was to delete `site-packages/conda` and create a junction to the 4.0.8 version in my pkgs folder which seems to at least work, even if conda is a little confused about its version:
```
C:\bin\Anaconda3\Lib\site-packages
λ mklink /J conda C:\bin\Anaconda3\pkgs\conda-4.0.8-py35_0\Lib\site-packages\conda
Junction created for conda <<===>> C:\bin\Anaconda3\pkgs\conda-4.0.8-py35_0\Lib\site-packages\conda

C:\bin\Anaconda3\Lib\site-packages
λ conda list conda
# packages in environment at C:\bin\Anaconda3:
#
anaconda-client           1.4.0                    py35_0
conda                     4.1.6                    py35_0
conda-build               1.20.3                   py35_0
conda-env                 2.5.1                    py35_0

C:\bin\Anaconda3\Lib\site-packages
λ
```

**Comment by dhirschfeld** [comment]
I'm going to put in another plug for #2410 here as any attempt to do anything with conda will attempt to update my conda to the broken 4.1.6. I really think the blacklist functionality is pretty crucial...

**Comment by dhirschfeld** [comment]
It seems like Python itself is broken??
```
λ python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.python_implementation()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\bin\Anaconda3\lib\platform.py", line 1292, in python_implementation
    return _sys_version()[0]
  File "C:\bin\Anaconda3\lib\platform.py", line 1252, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MSC v.1900 64 bit (AMD64)]'
>>>
```

**Comment by dhirschfeld** [comment]
For anyone following this sorry monologue, I accidentally installed a broken Python from conda-forge. This was in part because my older conda version didn't specify which channel the packages came from so I wasn't aware I was updating to a conda-forge Python. Installing Python from dafaults has fixed the problem.

**Comment by dhirschfeld** [comment]
I'll put in a plug for my other issue #2978 which could help prevent this sort of thing...

**Comment by dhirschfeld** [comment]
It seems that the conda-forge Python wasn't to blame. Instead it appeared there was some problem installing Python which seemed to break it - see also #3024
