### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by quasiben** [conda/conda#304]
I'm in the middle of building conda packages and I'm now receiving the following error:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/ContinuumIO/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/quasiben/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/quasiben/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    args.func(args, p)
  File "/Users/quasiben/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 75, in execute
    prepend=not args.override_channels)
  File "/Users/quasiben/anaconda/lib/python2.7/site-packages/conda/api.py", line 33, in get_index
    return fetch_index(tuple(channel_urls))
  File "/Users/quasiben/anaconda/lib/python2.7/site-packages/conda/utils.py", line 61, in **call**
    value = self.func(_args)
  File "/Users/quasiben/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 105, in fetch_index
    repodata = fetch_repodata(url)
  File "/Users/quasiben/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 61, in fetch_repodata
    cache = json.load(open(cache_path))
  File "/Users/quasiben/anaconda/lib/python2.7/json/**init**.py", line 290, in load
    *_kw)
  File "/Users/quasiben/anaconda/lib/python2.7/json/**init**.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/Users/quasiben/anaconda/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/quasiben/anaconda/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
## CONDA INFO:

```
         platform : osx-64
    conda version : 2.0.0
 root environment : /Users/quasiben/anaconda  (writable)
```

  default environment : /Users/quasiben/anaconda/envs/w_app_test
     envs directories : /Users/quasiben/anaconda/envs
        package cache : /Users/quasiben/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/dev/osx-64/
                        http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
                        http://repo.continuum.io/pkgs/gpl/osx-64/
          config file : /Users/quasiben/.condarc

**Comment by raisok** [comment]
I get the same problem as you like，how could you solve the problem？
the Error Message：“ValueError: No JSON object could be decoded”
