### ISSUE TITLE
Not using the correct version of python3x.dll of the current environment under Windows

### ISSUE THREAD

**Issue by ziyuang** [conda/conda#3043]
I have Python 3.5 in env `root` and Python 3.4 in env `py34`. And I installed two numpy in both environments. But when I want to working with the numpy in `py34`, it uses `python35.dll` instead of `python34.dll`:

```
(py34) D:\>python
Python 3.4.5 |Continuum Analytics, Inc.| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda3\Lib\site-packages\numpy\__init__.py", line 180, in <module>
    from . import add_newdocs
  File "C:\Anaconda3\Lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Anaconda3\Lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Anaconda3\Lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Anaconda3\Lib\site-packages\numpy\core\__init__.py", line 14, in <module>
    from . import multiarray
ImportError: Module use of python35.dll conflicts with this version of Python.
```

**Comment by tyler-thetyrant** [comment]
Python 3.4 is no longer supported.
Closing as this is an outdated issue.
