### ISSUE TITLE
UnicodeDecodeError: 'utf-8' running conda update with local file

### ISSUE THREAD

**Issue by gpenney** [conda/conda#3050]
Newbie  FYI

# conda update --dry-run --file=/tmp/pandas/pandas-0.18.1-np111py34_0.tar.bz2 pandas
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/main_update.py", line 38, in execute
    install.install(args, parser, 'update')
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/install.py", line 176, in install
    specs.extend(common.specs_from_url(args.file, json=args.json))
  File "/opt/anaconda/lib/python3.4/site-packages/conda/cli/common.py", line 457, in specs_from_url
    for line in open(path):
  File "/opt/anaconda/lib/python3.4/codecs.py", line 319, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf4 in position 11: invalid continuation byte

conda info Below

Current conda install:

             platform : linux-64
        conda version : 3.17.0
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /opt/anaconda  (writable)
  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by HugoTian** [comment]
could you please update conda, using "conda update conda".

If there is still problem, you may refer to discussion on issue #3118 .

I will close this issue, since it's similar to issue #3118 

feel free to reopen it and @ me
