### ISSUE TITLE
Need option to disable privileged operations when creating new envs on Windows

### ISSUE THREAD

**Issue by joelhullcio** [conda/conda#3053]
Some Windows users do not have admin privileges on their boxes but they need to create conda envs.  They need a way to disable all admin operations during conda env creation and/or package install so they are not prompted for credentials.

For example, while creating an env that only contains ipython I was prompted for admin credentials on my Windows laptop but without admin privileges I had to abort the creation.  The same issue occurs when installing ipython into an existing env.

conda create -n myenv ipython

**Comment by kalefranz** [comment]
@csoja Still waiting on getting some of @mingwandroid's time to work on multi-user support on Windows.

**Comment by wulmer** [comment]
When I have Anaconda 4.1.1 installed with admin rights, the installation directory is not writeable for the normal (unprivileged) user. This is reported correctly:

    root environment : C:\Program Files\Anaconda2  (read only)

When I then try to create a new environment (with the unprivileged user), conda fails while trying to extract some sources:


    Traceback (most recent call last):
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 442, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 66, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not args.quiet)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\plan.py", line 639, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\instructions.py", line 132, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\install.py", line 854, in extract
        with FileLock(path):
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\lock.py", line 86, in __enter__
        touch(self.lock_file_path)
      File "C:\Program Files\Anaconda2\lib\site-packages\conda\lock.py", line 48, in touch
        with open(file_name, 'a'):
    IOError: [Errno 13] Permission denied: u'C:\\Program Files\\Anaconda2\\pkgs\\menuinst-1.4.1-py27_0.pid2304.conda_lock'

I wonder why conda tries to write into the installation root even though it did recognize this directory as read-only? Should I file a new bug or is this related to this issue? 
BTW: I tried with conda 4.1.6, 4.1.11 and 4.2.4 on Windows 10.

**Comment by wulmer** [comment]
Hi, I did some more tests with Anaconda3 4.1.1 and made another observation: When Anaconda is installed under `C:\Program Files\Anaconda3` (not writable), packages are correctly downloaded into the user's package cache and extracted there. 
It only fails if a package is *not* downloaded but found in the system's package cache (`C:\Program Files\Anaconda3\pkgs`). Then, conda tries to extract it there (because it will not be downloaded into the user's package cache directory).

**Comment by kalefranz** [comment]
Multi-user support is now pretty solid as of conda 4.3.13.
