### ISSUE TITLE
Unable to clone environment from a centralized installation

### ISSUE THREAD

**Issue by komailrk** [conda/conda#3057]
Trying to clone from a centralized location where I don't have write access.

```
(root) bash-4.1$ conda create -p /localdata/conda/envs/alpha --clone=/opt/anaconda
Source:      /opt/anaconda
Destination: /localdata/conda/envs/alpha
The following packages cannot be cloned out of the root environment:
 - conda-4.1.6-py27_0
Packages: 18
Files: 5
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 87, in clone
    index_args=index_args)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/misc.py", line 126, in explicit
    index.update(get_index(**index_args))
  File "/opt/anaconda/lib/python2.7/site-packages/conda/api.py", line 22, in get_index
    channel_urls = normalize_urls(channel_urls, platform, offline)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/config.py", line 250, in normalize_urls
    url = urls[0]
KeyError: 0

```

**Comment by komailrk** [comment]
Doesn't seem to be an issue when using the Python version included with conda. I built my own and was installing that in the environment I was trying to clone

**Comment by HugoTian** [comment]
please run "conda update conda" to get new version of conda.

However, in new version of conda, you may also get error, described in #3120 

please refer to PR #3080 , and in conda 4.2.0 it will fix it. Also, the PR is already merged in 4.1.x branch on github, you can install from source

**Comment by HugoTian** [comment]
I may close this issue, and we will discuss whether have conda 4.1.10 release to fix this issue.

if you have any questions, feel free to reopen this issue and @ me
Thanks

**Comment by komailrk** [comment]
Thanks @HugoTian
