### ISSUE TITLE
Installing packages offline

### ISSUE THREAD

**Issue by Averis007** [conda/conda#3059]
Just found out an issue while installing conda packages offline from tar.bz2 file. If the path of the package file location contains a space, the installer throws up an error because it tries to convert string into array in the instructions.py file.

**Comment by HugoTian** [comment]
Can you provide the command you are running and conda info.

Also, could you please give more detail about the code in instruction.py ?

Thanks

**Comment by scarescrow** [comment]
I faced the same issue. Command was 

`conda install --offline -f win-64-gevent-1.1.1-py27_0.tar.bz2`

`An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func

    exit_code = args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 78, in ex
ecute
    install(args, parser, 'install')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 203, in instal
l
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\misc.py", line 140, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 599, in execute_actio
ns
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 136, in execu
te_instructions
    cmd(state, arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 78, in LINK_C
MD
    dist, lt = split_linkarg(arg)
  File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 74, in split_
linkarg
    return (parts[0], int(LINK_HARD if len(parts) < 2 else parts[1]))
ValueError: invalid literal for int() with base 10: 'Files/Commvault/ContentStor
e/ContentAnalyzer/bin/::win-64-gevent-1.1.1-py27_0'`

The issue was because the path to file is being split and typecast to int. So, if the path contains space, it will crash.

**Comment by kalefranz** [comment]
These problems have all been fixed in recent version of conda.
