### ISSUE TITLE
'conda update' fails

### ISSUE THREAD

**Issue by yasheshgaur** [conda/conda#3069]
Hello,

I get the following error when I run 'conda update conda':

[yashesh@comet-ln2 yas]$ conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 240, in install
    prefix=prefix)
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/api.py", line 43, in get_index
    unknown=unknown)
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 256, in fetch_index
    for url in reversed(channel_urls)])
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 107, in submit
    self._adjust_thread_count()
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 123, in _adjust_thread_count
    t.start()
  File "/oasis/projects/nsf/cmu139/yashesh/anaconda2/lib/python2.7/threading.py", line 736, in start
    _start_new_thread(self.__bootstrap, ())
thread.error: can't start new thread

----------------------------------------------------------------

Below is the output for 'conda info':

Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /oasis/projects/nsf/cmu139/yashesh/anaconda2  (writable)
  default environment : /oasis/projects/nsf/cmu139/yashesh/anaconda2
     envs directories : /oasis/projects/nsf/cmu139/yashesh/anaconda2/envs
        package cache : /oasis/projects/nsf/cmu139/yashesh/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

----------------------------------------------------------------

Can anyone help me out here? Thanks!

**Comment by HugoTian** [comment]
I am not quite sure what's exactly going on. Generally, the "can't start new thread" error almost certainly due to the fact that you have already have too many threads running within your python process, and due to a resource limit of some kind the request to create a new thread is refused.

Try to restart the machine, and update the conda, by conda update conda or 


    curl http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -o ~/miniconda3.sh
    bash ~/miniconda3.sh -bfp /usr/local/conda

Good Luck

**Comment by yasheshgaur** [comment]
This is big cluster not owned by me. Can't restart :( !

**Comment by HugoTian** [comment]
Actually, this never happens on local machine, if run on cluster, I plan to add  some exception handler 
in conda/fetch.py, line 304 

    try:
        futures = tuple(executor.submit(fetch_repodata, url, use_cache=use_cache,
        session=CondaSession()) for url in urls)
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
    except Exception as e:
        session = CondaSession()
        repodatas = [(url, fetch_repodata(url, use_cache=use_cache, session=session)) for url in urls]

you can refer to PR #3078
