### ISSUE TITLE
"conda info" error after conda upgrade

### ISSUE THREAD

**Issue by mtridici** [conda/conda#3070]
Hi All,

I'm receiving an error during "conda info" command execution.
Recently, I installed basemap module using "conda install basemap" command. But this action required conda update. I think that this issue is due to the update. Is there a way to solve this issue? Thank you in advance.

Traceback (most recent call last):
  File "/users/home/opt/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/users/home/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/users/home/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/users/home/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/users/home/opt/anaconda2/lib/python2.7/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by HugoTian** [comment]
Can you run conda --debug info, and show the output ?

Also, it seems there is something wrong with binstar_client, and could you try to import binstar_client in your python interpreter ?

Thanks

**Comment by kerrydu** [comment]
I also have this error after conda update anaconda

[Anaconda3] C:\Users\Kerui>conda --debug info
Warning: could not import binstar_client ('args' object has no attribute 'site')INFO:stderrlog:Warning: could not import binstar_client ('args' object has no attribute 'site')
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "d:\Users\Kerui\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "d:\Users\Kerui\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "d:\Users\Kerui\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "d:\Users\Kerui\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 158, in execute
    init_binstar(True)
  File "d:\Users\Kerui\Anaconda3\lib\site-packages\conda\config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by kerrydu** [comment]
import binstar_client as bi
bi?
Type:        module
String form: <module 'binstar_client' from 'd:\\Users\\Kerui\\Anaconda3\\lib\\site-packages\\binstar_client\\__init__.py'>
File:        d:\users\kerui\anaconda3\lib\site-packages\binstar_client\__init__.py
Docstring:   <no docstring>

-------
I  can import binstar_client in the python interpreter

**Comment by HugoTian** [comment]
I do not have that problem on my machine.

I believe the error occurs in conda/config.py line 257 

    binstar_client = get_binstar(args)

Then I checked the source code of minstar_client/utils/__init__.py, and in get_binstar() function
it has following code

    token = getattr(args, 'token', None)
    log_level = getattr(args, 'log_level', logging.INFO)
    site = getattr(args, 'site', None)

So, when "site" attribute is not available, then site will be set to None, and it will not raise an exception.

My advise is that, if you have time, then go deep into source code, see what actually happens in get_binstar() function. However, I think the easy solution will be reinstall anaconda, and get the latest conda.

Enjoy.

**Comment by HugoTian** [comment]
I just figure out, the binstar_client package can be updated through 

    conda update anaconda-client

Could you please try that to see whether it fix this issue ?

Thanks

**Comment by aqeel13932** [comment]
I got the same problem :
conda info -e
`Warning: could not import binstar_client ('args' object has no attribute 'site')An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/aqeel/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'`

I did run `conda --debug info` 

`Warning: could not import binstar_client ('args' object has no attribute 'site')INFO:stderrlog:Warning: could not import binstar_client ('args' object has no attribute 'site')
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/aqeel/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/home/aqeel/anaconda2/lib/python2.7/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'
`

**Comment by HugoTian** [comment]
@aqeel13932 Thanks for you info, and please refer to PR #3115

**Comment by aqeel13932** [comment]
@HugoTian  Thanks for you effort I tried your pull but it didn't work, looks like there is huge difference between the version am using and the github version . I'll try to update it to github and let you know.

**Comment by HugoTian** [comment]
@aqeel13932 , on github, the conda 4.1.x branch is latest release of conda, and the master branch will be conda4.2, which will be released soon

**Comment by HugoTian** [comment]
conda 4.1.9 is released, and it will fix your issue, please run "conda update conda" to update.

I will close this issue, and if there is still bugs, feel free to reopen it and @ me.

Thanks
