### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'add' when cloning existing environment

### ISSUE THREAD

**Issue by tilusnet** [conda/conda#3086]
The command `conda create --name sk-sparky --clone sk-vocab-analysis` fails.

Command output:
```
Source:      /sk-users/attila/opt/anaconda3/envs/sk-vocab-analysis
Destination: /sk-users/attila/opt/anaconda3/envs/sk-sparky
Using Anaconda Cloud api site https://api.anaconda.org
Packages: 169
Files: 2026
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/sk-users/attila/opt/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 88, in clone
    index_args=index_args)
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/sk-users/attila/opt/anaconda3/lib/python3.5/site-packages/conda/misc.py", line 109, in explicit
    channels.add(channel)
AttributeError: 'dict' object has no attribute 'add'
```

`conda info` output:
```
Current conda install:

             platform : linux-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : 1.17.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /sk-users/attila/opt/anaconda3  (writable)
  default environment : /sk-users/attila/opt/anaconda3
     envs directories : /sk-users/attila/opt/anaconda3/envs
        package cache : /sk-users/attila/opt/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by tilusnet** [comment]
Noticing that this is likely a duplicate for #3060.
