### ISSUE TITLE
conda clone failure

### ISSUE THREAD

**Issue by diehl** [conda/conda#3089]
Running the latest version of conda presently. Just got the following error when trying to clone an environment:

$ conda create --name DataGuildPy3 --clone DataGuild
Source:      /Users/cpd/anaconda/envs/DataGuild
Destination: /Users/cpd/anaconda/envs/DataGuildPy3
Packages: 204
Files: 3671
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/cpd/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 88, in clone
    index_args=index_args)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/misc.py", line 109, in explicit
    channels.add(channel)
AttributeError: 'dict' object has no attribute 'add'
$ conda info
Warning: could not import binstar_client ('args' object has no attribute 'site')An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/cpd/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/Users/cpd/anaconda/lib/python2.7/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'

**Comment by nicksilver** [comment]
I've got the same issue when running:

$ conda create --name geospat --file geospat-explicit-spec.txt

**Comment by HugoTian** [comment]
For the 
     channels.add(channel)
     AttributeError: 'dict' object has no attribute 'add'

Please refer to Pull Request #3080, and it will be fixed in new release

For the conda info binstar_client error, I am still working on that. I think issue #3070 is similar to this issue.
