### ISSUE TITLE
Unexpected error with request to report – looks like regular expression parse error

### ISSUE THREAD

**Issue by russel** [conda/conda#3091]
On executing "conda list *qt*", the result is:

```
# packages in environment at /home/users/russel/lib.Linux.x86_64/Miniconda3:
#
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 238, in execute
    show_channel_urls=args.show_channel_urls)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 178, in print_packages
    show_channel_urls=show_channel_urls)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 129, in list_packages
    for dist in get_packages(installed, regex):
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 115, in get_packages
    pat = re.compile(regex, re.I) if regex else None
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/re.py", line 224, in compile
    return _compile(pattern, flags)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/re.py", line 293, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_compile.py", line 536, in compile
    p = sre_parse.parse(p, flags)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_parse.py", line 829, in parse
    p = _parse_sub(source, pattern, 0)
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_parse.py", line 437, in _parse_sub
    itemsappend(_parse(source, state))
  File "/home/users/russel/lib.Linux.x86_64/Miniconda3/lib/python3.5/sre_parse.py", line 638, in _parse
    source.tell() - here + len(this))
sre_constants.error: nothing to repeat at position 0
```

the result of "conda info" is:

```
Current conda install:

             platform : linux-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/users/russel/lib.Linux.x86_64/Miniconda3  (writable)
  default environment : /home/users/russel/lib.Linux.x86_64/Miniconda3
     envs directories : /home/users/russel/lib.Linux.x86_64/Miniconda3/envs
        package cache : /home/users/russel/lib.Linux.x86_64/Miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
