### ISSUE TITLE
Bug report - With conda 17/3/2016

### ISSUE THREAD

**Issue by duytrung** [conda/conda#3096]
Hi,
I installed and update anaconda and get these messages:

```
> conda update --all
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment C:\MyPrograms\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    patch-2.5.9                |                1          56 KB
    conda-env-2.5.2            |           py35_0          64 KB
    conda-4.1.8                |           py35_0         244 KB
    conda-build-1.21.5         |           py35_0         309 KB
    ------------------------------------------------------------
                                           Total:         673 KB

The following NEW packages will be INSTALLED:

    patch:       2.5.9-1

The following packages will be UPDATED:

    conda:       4.1.6-py35_0  --> 4.1.8-py35_0
    conda-build: 1.21.3-py35_0 --> 1.21.5-py35_0
    conda-env:   2.5.1-py35_0  --> 2.5.2-py35_0

Proceed ([y]/n)? y

Fetching packages ...
patch-2.5.9-1. 100% |###############################| Time: 0:00:00  92.57 kB/s
conda-env-2.5. 100% |###############################| Time: 0:00:00  84.37 kB/s
conda-4.1.8-py 100% |###############################| Time: 0:00:01 140.29 kB/s
conda-build-1. 100% |###############################| Time: 0:00:02 133.45 kB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the            |  75%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\MyPrograms\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\main.py", line 120,
in main
    exit_code = args_func(args, p)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\main.py", line 130,
in args_func
    exit_code = args.func(args, p)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\main_update.py", lin
e 64, in execute
    install(args, parser, 'update')
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\cli\install.py", line 40
7, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\plan.py", line 600, in e
xecute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\instructions.py", line 1
36, in execute_instructions
    cmd(state, arg)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\instructions.py", line 5
9, in EXTRACT_CMD
    extract(arg)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\install.py", line 854, i
n extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\MyPrograms\Anaconda3\lib\site-packages\conda\install.py", line 240, i
n exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\\MyPrograms\\Anaconda3\\pkgs
\\conda-build-1.21.5-py35_0.tmp' -> 'C:\\MyPrograms\\Anaconda3\\pkgs\\conda-buil
d-1.21.5-py35_0'
```

Kind regards

**Comment by duytrung** [comment]
I installed using Anaconda Setup package: 

```
Anaconda3-4.1.1-Windows-x86.exe in Windows VISTA Home Basic

> conda list
# packages in environment at C:\MyPrograms\Anaconda3:
#
_nb_ext_conf              0.2.0                    py35_0
alabaster                 0.7.8                    py35_0
anaconda                  4.1.1               np111py35_0
anaconda-client           1.4.0                    py35_0
anaconda-navigator        1.2.1                    py35_0
argcomplete               1.0.0                    py35_1
astropy                   1.2.1               np111py35_0
babel                     2.3.3                    py35_0
backports                 1.0                      py35_0
beautifulsoup4            4.4.1                    py35_0
bitarray                  0.8.1                    py35_1
blaze                     0.10.1                   py35_0
bokeh                     0.12.0                   py35_0
boto                      2.40.0                   py35_0
bottleneck                1.1.0               np111py35_0
bzip2                     1.0.6                    vc14_3  [vc14]
cffi                      1.6.0                    py35_0
chest                     0.2.3                    py35_0
click                     6.6                      py35_0
cloudpickle               0.2.1                    py35_0
clyent                    1.2.2                    py35_0
colorama                  0.3.7                    py35_0
comtypes                  1.1.2                    py35_0
conda                     4.1.6                    py35_0
conda-build               1.21.3                   py35_0
conda-env                 2.5.1                    py35_0
configobj                 5.0.6                    py35_0
console_shortcut          0.1.1                    py35_1
contextlib2               0.5.3                    py35_0
cryptography              1.4                      py35_0
curl                      7.49.0                   vc14_0  [vc14]
cycler                    0.10.0                   py35_0
cython                    0.24                     py35_0
cytoolz                   0.8.0                    py35_0
dask                      0.10.0                   py35_0
datashape                 0.5.2                    py35_0
decorator                 4.0.10                   py35_0
dill                      0.2.5                    py35_0
docutils                  0.12                     py35_2
dynd-python               0.7.2                    py35_0
entrypoints               0.2.2                    py35_0
et_xmlfile                1.0.1                    py35_0
fastcache                 1.0.2                    py35_1
flask                     0.11.1                   py35_0
flask-cors                2.1.2                    py35_0
freetype                  2.5.5                    vc14_1  [vc14]
get_terminal_size         1.0.0                    py35_0
gevent                    1.1.1                    py35_0
greenlet                  0.4.10                   py35_0
h5py                      2.6.0               np111py35_0
hdf5                      1.8.15.1                 vc14_4  [vc14]
heapdict                  1.0.0                    py35_1
idna                      2.1                      py35_0
imagesize                 0.7.1                    py35_0
ipykernel                 4.3.1                    py35_0
ipython                   4.2.0                    py35_0
ipython_genutils          0.1.0                    py35_0
ipywidgets                4.1.1                    py35_0
itsdangerous              0.24                     py35_0
jdcal                     1.2                      py35_1
jedi                      0.9.0                    py35_1
jinja2                    2.8                      py35_1
jpeg                      8d                       vc14_0  [vc14]
jsonschema                2.5.1                    py35_0
jupyter                   1.0.0                    py35_3
jupyter_client            4.3.0                    py35_0
jupyter_console           4.1.1                    py35_0
jupyter_core              4.1.0                    py35_0
libdynd                   0.7.2                         0
libpng                    1.6.22                   vc14_0  [vc14]
libtiff                   4.0.6                    vc14_2  [vc14]
llvmlite                  0.11.0                   py35_0
locket                    0.2.0                    py35_1
lxml                      3.6.0                    py35_0
markupsafe                0.23                     py35_2
matplotlib                1.5.1               np111py35_0
menuinst                  1.4.1                    py35_0
mistune                   0.7.2                    py35_0
mkl                       11.3.3                        1
mkl-service               1.1.2                    py35_2
mpmath                    0.19                     py35_1
multipledispatch          0.4.8                    py35_0
nb_anacondacloud          1.1.0                    py35_0
nb_conda                  1.1.0                    py35_0
nb_conda_kernels          1.0.3                    py35_0
nbconvert                 4.2.0                    py35_0
nbformat                  4.0.1                    py35_0
nbpresent                 3.0.2                    py35_0
networkx                  1.11                     py35_0
nltk                      3.2.1                    py35_0
nose                      1.3.7                    py35_1
notebook                  4.2.1                    py35_0
numba                     0.26.0              np111py35_0
numexpr                   2.6.0               np111py35_0
numpy                     1.11.1                   py35_0
odo                       0.5.0                    py35_1
openpyxl                  2.3.2                    py35_0
openssl                   1.0.2h                   vc14_0  [vc14]
pandas                    0.18.1              np111py35_0
partd                     0.3.4                    py35_0
path.py                   8.2.1                    py35_0
pathlib2                  2.1.0                    py35_0
patsy                     0.4.1                    py35_0
pep8                      1.7.0                    py35_0
pickleshare               0.7.2                    py35_0
pillow                    3.2.0                    py35_1
pip                       8.1.2                    py35_0
ply                       3.8                      py35_0
psutil                    4.3.0                    py35_0
py                        1.4.31                   py35_0
pyasn1                    0.1.9                    py35_0
pycosat                   0.6.1                    py35_1
pycparser                 2.14                     py35_1
pycrypto                  2.6.1                    py35_4
pycurl                    7.43.0                   py35_0
pyflakes                  1.2.3                    py35_0
pygments                  2.1.3                    py35_0
pyopenssl                 0.16.0                   py35_0
pyparsing                 2.1.4                    py35_0
pyqt                      4.11.4                   py35_6
pyreadline                2.1                      py35_0
pytables                  3.2.2               np111py35_4
pytest                    2.9.2                    py35_0
python                    3.5.2                         0
python-dateutil           2.5.3                    py35_0
pytz                      2016.4                   py35_0
pywin32                   220                      py35_1
pyyaml                    3.11                     py35_4
pyzmq                     15.2.0                   py35_0
qt                        4.8.7                    vc14_8  [vc14]
qtconsole                 4.2.1                    py35_0
qtpy                      1.0.2                    py35_0
requests                  2.10.0                   py35_0
rope                      0.9.4                    py35_1
ruamel_yaml               0.11.7                   py35_0
scikit-image              0.12.3              np111py35_1
scikit-learn              0.17.1              np111py35_1
scipy                     0.17.1              np111py35_1
setuptools                23.0.0                   py35_0
simplegeneric             0.8.1                    py35_1
singledispatch            3.4.0.3                  py35_0
sip                       4.16.9                   py35_2
six                       1.10.0                   py35_0
snowballstemmer           1.2.1                    py35_0
sockjs-tornado            1.0.3                    py35_0
sphinx                    1.4.1                    py35_0
sphinx_rtd_theme          0.1.9                    py35_0
spyder                    2.3.9                    py35_0
sqlalchemy                1.0.13                   py35_0
statsmodels               0.6.1               np111py35_1
sympy                     1.0                      py35_0
tk                        8.5.18                   vc14_0  [vc14]
toolz                     0.8.0                    py35_0
tornado                   4.3                      py35_1
traitlets                 4.2.1                    py35_0
unicodecsv                0.14.1                   py35_0
vs2015_runtime            14.0.25123                    0
werkzeug                  0.11.10                  py35_0
wheel                     0.29.0                   py35_0
xlrd                      1.0.0                    py35_0
xlsxwriter                0.9.2                    py35_0
xlwings                   0.7.2                    py35_0
xlwt                      1.1.2                    py35_0
zlib                      1.2.8                    vc14_3  [vc14]

```

**Comment by HugoTian** [comment]
can you show the conda info output, if the version is not 4.1.8, please update conda by running "conda update conda"

**Comment by HugoTian** [comment]
The new version of conda should fix this, please run "conda update conda" or reinstall miniconda/anaconda.

I will close this issue, and if there is still problem, feel free to reopen it and @ me
