### ISSUE TITLE
Permission denied installing singledispatch in an environment

### ISSUE THREAD

**Issue by nevermindewe** [conda/conda#3102]
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.8
    conda-env version : 2.5.2
  conda-build version : 1.21.5
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /usr/local/anaconda/2.1.0  (read only)
  default environment : /home/nevermind/.conda/envs/kershner27_01
     envs directories : /home/nevermind/.conda/envs
                        /home/nevermind/envs
                        /usr/local/anaconda/2.1.0/envs
        package cache : /home/nevermind/.conda/envs/.pkgs
                        /home/nevermind/envs/.pkgs
                        /usr/local/anaconda/2.1.0/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        http://kts02:8000/linux-64/
                        http://kts02:8000/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/wemeneker/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/wemeneker/noarch/
          config file : /home/nevermind/.condarc
         offline mode : False
    is foreign system : False

$ conda install singledispatch -f
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/nevermind/.conda/envs/kershner27_01:

The following NEW packages will be INSTALLED:

    singledispatch: 3.4.0.3-py27_0 defaults (copy)

Proceed ([y]/n)? 

Extracting packages ...
An unexpected error has occurred, please consider sending the                                                   |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/nevermind/.conda/envs/kershner27_01/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/install.py", line 859, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "/usr/local/anaconda/2.1.0/lib/python2.7/site-packages/conda/install.py", line 237, in exp_backoff_fn
    return fn(*args)
OSError: [Errno 13] Permission denied

**Comment by nevermindewe** [comment]
This is fixed by conda-build 1.21.9.
