### ISSUE TITLE
conda info --envs returns AttributeError: 'NoneType' object has no attribute 'domain'

### ISSUE THREAD

**Issue by msure** [conda/conda#3116]
Here is the trace back:

```
Apalacios-MBP:~ adrianpalacios$ conda info --envs
Warning: could not import binstar_client ('args' object has no attribute 'site')An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/adrianpalacios/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/adrianpalacios/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/adrianpalacios/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/adrianpalacios/anaconda/lib/python3.4/site-packages/conda/cli/main_info.py", line 158, in execute
    init_binstar(True)
  File "/Users/adrianpalacios/anaconda/lib/python3.4/site-packages/conda/config.py", line 244, in init_binstar
    binstar_domain = binstar_client.domain.replace("api", "conda").rstrip('/') + '/'
AttributeError: 'NoneType' object has no attribute 'domain'
```

**Comment by HugoTian** [comment]
Please refer to PR #3115 , see whether it can fix your issue.

Moreover, could you try 

    conda update anaconda-client

to update the binstar_client library for python

**Comment by anlmehdi** [comment]
Hi - Not sure if PR #3115 can fix my issue. Tried "conda update
anaconda-client" per your suggestion - did not help.

**Comment by HugoTian** [comment]
@anlmehdi , I am fixing this issue now, and I believe PR #3115  is the correct fix.

Moreover,  there will be a conda 4.1.9 release soon to fix that.

**Comment by HugoTian** [comment]
conda 4.1.9 is released, please run "conda update conda" to update.

I will close this issue, if there is still problem, feel free to reopen it.

Thanks
