### ISSUE TITLE
Cannot clone/make exact copy of an environment 

### ISSUE THREAD

**Issue by anlmehdi** [conda/conda#3117]
Wanted to make exact copy of an environment but it ran into an issue. The log said I should create an issue. Below is the cut and paste of the command and the response.

Thank you,
mehdi.tondravi@gmail.com

conda create -n ilastik-test  --clone playgroundSource:      /Applications/anaconda/envs/playground
Destination: /Applications/anaconda/envs/ilastik-test
Packages: 181
Files: 529
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.
Traceback (most recent call last):
  File "/Applications/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 87, in clone
    index_args=index_args)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/misc.py", line 126, in explicit
    index.update(get_index(**index_args))
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/api.py", line 22, in get_index
    channel_urls = normalize_urls(channel_urls, platform, offline)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/config.py", line 250, in normalize_urls
    url = urls[0]
KeyError: 0

**Comment by HugoTian** [comment]
could you please show the conda info output ?

I am running on conda 4.1.8 and it works fine.

**Comment by anlmehdi** [comment]
Hi - upgraded conda - it is 4.1.9 and unfortunately the issue still is
present. Here is output of conda info.

Thank you.

conda info

Current conda install:


             platform : osx-64

        conda version : 4.1.9

    conda-env version : 2.5.1

  conda-build version : 1.21.2

       python version : 3.5.1.final.0

     requests version : 2.10.0

     root environment : /Applications/anaconda  (writable)

  default environment : /Applications/anaconda

     envs directories : /Applications/anaconda/envs

        package cache : /Applications/anaconda/pkgs

         channel URLs : https://conda.anaconda.org/dgursoy/osx-64/

                        https://conda.anaconda.org/dgursoy/noarch/

                        https://conda.anaconda.org/conda-forge/osx-64/

                        https://conda.anaconda.org/conda-forge/noarch/

                        https://repo.continuum.io/pkgs/free/osx-64/

                        https://repo.continuum.io/pkgs/free/noarch/

                        https://repo.continuum.io/pkgs/pro/osx-64/

                        https://repo.continuum.io/pkgs/pro/noarch/

          config file : /Users/mehditondravi/.condarc

         offline mode : False

    is foreign system : False

**Comment by anlmehdi** [comment]
Have a different error with conda 4.1.9. Here is the cut & paste of the output:

mehditondravi$ conda create -n ilastik-test  --clone playground Source:      /Applications/anaconda/envs/playground
Destination: /Applications/anaconda/envs/ilastik-test
Using Anaconda Cloud api site https://api.anaconda.org
Packages: 181
Files: 529
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Applications/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 88, in clone
    index_args=index_args)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/misc.py", line 109, in explicit
    channels.add(channel)
AttributeError: 'dict' object has no attribute 'add'

**Comment by HugoTian** [comment]
Oh, there is already a PR about this issue, please refer to pull request #3080 

For conda release, it will fixed in conda 4.2.0, and on github, the above PR is already merged in branch 4.1.x. you can download the source code and install from the source

**Comment by HugoTian** [comment]
I will close this issue, and we will discuss whether to have conda 4.1.10 release to fix this.

If you have any questions, feel free to reopen this issue and @ me

Thanks
