### ISSUE TITLE
Error while issuing: conda create -n py2_matlab --clone py2

### ISSUE THREAD

**Issue by norok2** [conda/conda#3120]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/raid1/metere/local/opt/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 223, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index_args)
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 88, in clone
    index_args=index_args)
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 360, in clone_env
    force_extract=False, index_args=index_args)
  File "/home/raid1/metere/local/opt/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 109, in explicit
    channels.add(channel)
AttributeError: 'dict' object has no attribute 'add'
metere@isar$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.8
    conda-env version : 2.5.1
  conda-build version : 1.20.0
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /home/raid1/metere/local/opt/anaconda2  (writable)
  default environment : /home/raid1/metere/local/opt/anaconda2
     envs directories : /home/raid1/metere/local/opt/anaconda2/envs
        package cache : /home/raid1/metere/local/opt/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by HugoTian** [comment]
please refer to PR #3080 , and in conda 4.2.0 it will fix it.

Also, the above PR is merged in 4.1.x branch on github, you can install from source

**Comment by HugoTian** [comment]
I may close this issue, and we will discuss whether have conda 4.1.10 release to fix this issue.

if you have any questions, feel free to reopen this issue and @ me
Thanks
