### ISSUE TITLE
conda env remove still broken after conda upgrade

### ISSUE THREAD

**Issue by elvis-sik** [conda/conda#3126]
I am having an issue much similar to #3039 though the proposed solution did not work.

```
Current conda install:

             platform : linux-64
        conda version : 4.1.9
    conda-env version : 2.5.0
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/elvis/miniconda3  (writable)
  default environment : /home/elvis/miniconda3
     envs directories : /home/elvis/miniconda3/envs
        package cache : /home/elvis/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

```
$ conda remove env --name ml
...

Traceback (most recent call last):
  File "/home/elvis/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/home/elvis/miniconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/elvis/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/elvis/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: module 'conda.plan' has no attribute 'PREFIX'
```

**Comment by mcg1969** [comment]
Can you please try `conda update conda-env` and try again?

**Comment by elvis-sik** [comment]
Thanks, that worked, though it seems like black magic to me.

**Comment by mcg1969** [comment]
Sorry for the trouble. The problem is that `conda env` was, until very recently, a *separate project* from `conda` itself. We're in the process of rectifying that, because it really shouldn't be that way.

**Comment by elvis-sik** [comment]
Trouble? I got an answer to a minor issue in no time. This is great software and a great community, and I am glad for it all :smile:
