### ISSUE TITLE
Using Conda 4.0.10 linking stage fails on libgfortran.so.3

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3173]
I have the custom Anaconda 4.0, Python 3.5 parcel that was created for a customer.  It is lacking some packages.  I am trying to use Conda to install the extra packages.  In this instance, I am trying to install the R packages via `r-essentials` meta-package.  But during the linking stage there is an error and Conda bombs out.  I'm afraid my entire Parcel is now in an indeterminate state.

Here is a trace of all the output: 
[conda_install_parcel.txt](https://github.com/conda/conda/files/386922/conda_install_parcel.txt)

**Comment by ijstokes** [comment]
Interestingly, and it might seem relatedly, I get a similar error when installing a Conda package direct from a tarball:

```bash
$ conda install -y python-hdfs-2.0.5-py35_0.tar.bz2
[      COMPLETE      ]|##################################################| 100%
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
Error: file already exists: '/opt/cloudera/parcels/Anaconda3/bin/hdfscli'|   0%
```

**Comment by HugoTian** [comment]
This is wired, below is the link code for conda 4.0.x

     if os.path.exists(dst):
                log.warn("file already exists: %r" % dst)
                rm_rf(dst)

So, if there is already exists a dst, conda will remove it before linking.

**Comment by ijstokes** [comment]
@HugoTian that is weird.  I'm running this as root, so it definitely should be possible to remove/overwrite files, but maybe the perms are set read-only for everyone.

In fact, I'm discovering some other problems with the parcel-based version of Anaconda that I'm using (again, it is a custom one, so this issue may not exist for the free Anaconda parcel).  These issues I'm seeing may be the cause of the problem.

**Comment by ijstokes** [comment]
Because I think this is related, here are some more issues tied to parcel permissions:

```
ijstokes@silver ~ $ export PATH=/opt/cloudera/parcels/Anaconda3/bin:$PATH
ijstokes@silver ~ $ which python
/opt/cloudera/parcels/Anaconda3/bin/python
ijstokes@silver ~ $ ipython
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda3/bin/ipython", line 4, in <module>
    import IPython
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.magic import Magics, magics_class, line_magic
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/IPython/core/magic.py", line 22, in <module>
    from IPython.core import oinspect
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/IPython/core/oinspect.py", line 48, in <module>
    from pygments.lexers import PythonLexer
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/pygments/lexers/__init__.py", line 20, in <module>
    from pygments.plugin import find_plugin_lexers
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/pygments/plugin.py", line 39, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2927, in <module>
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 626, in _build_master
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 619, in __init__
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 675, in add_entry
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1982, in find_on_path
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2370, in from_location
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2687, in _reload_version
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2335, in _version_from_file
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 2503, in _get_metadata
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1477, in get_metadata_lines
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1474, in get_metadata
  File "/opt/cloudera/parcels/Anaconda3/lib/python3.5/site-packages/setuptools-23.0.0-py3.5.egg/pkg_resources/__init__.py", line 1580, in _get
PermissionError: [Errno 13] Permission denied: '/opt/cloudera/parcels/Anaconda3-4.1.2/lib/python3.5/site-packages/grako-3.10.0-py3.5.egg-info/PKG-INFO'
```

**Comment by ijstokes** [comment]
In case it is helpful, here are the perms on the files and directories discussed here:

```http
drwxr-xr-x 15 root root   36864 Jul 27 15:22 /opt/cloudera/parcels/Anaconda3-4.1.2/lib/
lrwxrwxrwx  1 root root      20 Jul 27 08:13 /opt/cloudera/parcels/Anaconda3-4.1.2/lib/libgfortran.so.3 -> libgfortran.so.3.0.0*
-rwxr-xr-x  2 root root 1088040 Apr 30 12:16 /opt/cloudera/parcels/Anaconda3-4.1.2/lib/libgfortran.so.3.0.0*
drwxr-xr-x  2 root root    4096 Jul 24 23:59 /opt/cloudera/parcels/Anaconda3-4.1.2/lib/python3.5/site-packages/grako-3.10.0-py3.5.egg-info/
-rw-r-----  2 root root   73684 Jul 15 15:40 /opt/cloudera/parcels/Anaconda3-4.1.2/lib/python3.5/site-packages/grako-3.10.0-py3.5.egg-info/PKG-INFO
drwxr-xr-x  2 root root   20480 Jul 27 15:26 /opt/cloudera/parcels/Anaconda3/bin/
-rwxrwxr-x  1 root root     319 Jul 27 15:21 /opt/cloudera/parcels/Anaconda3/bin/hdfscli*
```

**Comment by HugoTian** [comment]
I am trying to reproduce the bug, and seems conda 4.0.10 is not good at catching exceptions.

Now, what I quite sure that the error message comes from the code that I showed above, and I am quite confused about the error you get.

Could you please try start a python interpreter, and try 

    import os
    os.unlink("'/opt/cloudera/parcels/Anaconda3/bin/hdfscli'")

I think if you got some error, then we are close to a solution, otherwise, I am totally confused with this

**Comment by ijstokes** [comment]
OK, this keeps happening to me.  And this time it has destroyed my root Conda environment, so my entire Anaconda parcel is incapacitated.

```
Fetching packages ...
ca-certificate 100% |###############################################################################################################################| Time: 0:00:00   3.63 MB/s
ncurses-5.9-8. 100% |###############################################################################################################################| Time: 0:00:00   9.98 MB/s
python-3.5.2-2 100% |###############################################################################################################################| Time: 0:00:01  30.04 MB/s
protobuf-3.0.0 100% |###############################################################################################################################| Time: 0:00:00   5.30 MB/s
tensorflow-0.9 100% |###############################################################################################################################| Time: 0:00:01  19.83 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
Linking packages ...
Error: Error: file already exists: '/opt/cloudera/parcels/Anaconda3/ssl/cacert.pem'                                                                                      |   0%

[root@silver citi_pkgs]# conda update conda
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda3/bin/conda", line 4, in <module>
    from conda.cli.main import main
ImportError: No module named conda.cli.main
```

**Comment by HugoTian** [comment]
I am also confused with the bug, may be you can reinstall conda or anaconda ?

**Comment by kalefranz** [comment]
@ijstokes I'm totally in the dark on this parcel stuff.  I've never interacted with them.  Is there a launch point or documentation you know of to help me dig in?

**Comment by ijstokes** [comment]
@kalefranz I can't give you any details, unfortunately. I don't know a lot about it.  @ilanschnell created the scripts to produce the parcels, but he also doesn't know a lot about how they work.  @koverholt and @quasiben, I think, have the most experience with CDH parcels.

**Comment by kalefranz** [comment]
```
[root@silver citi_pkgs]# conda update conda
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda3/bin/conda", line 4, in <module>
    from conda.cli.main import main
ImportError: No module named conda.cli.main
```

Never again!!!!
