### ISSUE TITLE
Error issue package install

### ISSUE THREAD

**Issue by brunolnetto** [conda/conda#3199]
'conda info' log:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\Usuario\Miniconda3  (writable)
  default environment : C:\Users\Usuario\Miniconda3\envs\Bruno
     envs directories : C:\Users\Usuario\Miniconda3\envs
        package cache : C:\Users\Usuario\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False

Traceback log:

Traceback (most recent call last):
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\requests\packages\urllib3\
response.py", line 228, in _error_catcher
    yield
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\requests\packages\urllib3\
response.py", line 310, in read
    data = self._fp.read(amt)
  File "C:\Users\Usuario\Miniconda3\lib\http\client.py", line 448, in read
    n = self.readinto(b)
  File "C:\Users\Usuario\Miniconda3\lib\http\client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\Usuario\Miniconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Usuario\Miniconda3\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Usuario\Miniconda3\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\Usuario\Miniconda3\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] Foi forçado o cancelamento de uma conexão
 existente pelo host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Usuario\Miniconda3\Scripts\conda-script.py", line 5, in <module
>
    sys.exit(main())
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\cli\main.py", line 1
20, in main
    exit_code = args_func(args, p)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\cli\main.py", line 1
30, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\cli\main_install.py"
, line 78, in execute
    install(args, parser, 'install')
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\cli\install.py", lin
e 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\plan.py", line 599,
in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\instructions.py", li
ne 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\instructions.py", li
ne 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\fetch.py", line 338,
 in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\conda\fetch.py", line 423,
 in download
    chunk = resp.raw.read(2**14)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\requests\packages\urllib3\
response.py", line 320, in read
    flush_decoder = True
  File "C:\Users\Usuario\Miniconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Usuario\Miniconda3\lib\site-packages\requests\packages\urllib3\
response.py", line 246, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: Connect
ionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo h
ost remoto', None, 10054, None)", ConnectionResetError(10054, 'Foi forçado o can
celamento de uma conexão existente pelo host remoto', None, 10054, None))

**Comment by HugoTian** [comment]
Sorry , I cannot understand some part of your error message

    Connection broken: Connect
    ionResetError(10054, 'Foi forçado o cancelamento de uma conexão existente pelo h
    ost remoto', None, 10054, None)", ConnectionResetError(10054, 'Foi forçado o can
    celamento de uma conexão existente pelo host remoto

But it seems it is a requests library error, and can you give me the conda command that leads to this bug ?

**Comment by HugoTian** [comment]
The request error generally means to retry, and we will have better error message in conda4.2

I am about to close this issue, and if the retry fails, feel free to reopen this, and @ me
