### ISSUE TITLE
Creation of new environments results in 'Process' error

### ISSUE THREAD

**Issue by mikhailklassen** [conda/conda#3201]
When trying to create a new environment in conda, I receive the following error:

```
Traceback (most recent call last):
  File "/Users/mikhail/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/mikhail/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/mikhail/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/mikhail/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/Users/mikhail/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 431, in install
    print_activate(args.name if args.name else prefix)
  File "/Users/mikhail/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 100, in print_activate
    shell = find_parent_shell(path=False)
  File "/Users/mikhail/anaconda/lib/python2.7/site-packages/conda/utils.py", line 260, in find_parent_shell
    pname = process.parent().name().lower()
TypeError: 'Process' object is not callable
```

The problem is fixed by removing the parens from non-callable objects in utils.py

```
def find_parent_shell(path=False, max_stack_depth=10):
    """return process name or path of parent.  Default is to return only name of process."""
    try:
        import psutil
    except ImportError:
        stderrlog.warn("No psutil available.\n"
                       "To proceed, please conda install psutil")
        return None
    process = psutil.Process()
    pname = process.parent.name.lower()
    stack_depth = 0 
    while (any(proc in pname for proc in ["conda", "python", "py.test"]) and 
           stack_depth < max_stack_depth):
        if process:
            process = process.parent()
            pname = process.parent.name.lower()
            stack_depth += 1
        else:
            # fallback defaults to system default
            if sys.platform == 'win32':
                return 'cmd.exe'
            else:
                return 'bash'
    if path:
        return process.parent.exe()
    return process.parent.name
```

My conda info:

```
Current conda install:

             platform : osx-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.2.0
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /Users/mikhail/anaconda  (writable)
  default environment : /Users/mikhail/anaconda
     envs directories : /Users/mikhail/anaconda/envs
        package cache : /Users/mikhail/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by HugoTian** [comment]
This bug comes from psutil, and "TypeError: 'Process' object is not callable" is due to the psutils version. 

The current version of psutil is 4.3 and if you have psutil 1.2, it will raise above error.

Please try "conda update psutil" and see whether it will fix the issue. Moreover, the conda 4.2 will no longer need psutil.

Thanks

**Comment by HugoTian** [comment]
I will close this issue, and if you still have questions, feel free to reopen this one and @ me

Thanks
