### ISSUE TITLE
conda.utils.url_path not defined

### ISSUE THREAD

**Issue by ilanschnell** [conda/conda#3204]
I'm trying to build `conda-build` 1.21.9 against `conda` 4.2.0, and I get:
```
command: conda-build --version
Traceback (most recent call last):
  File "/opt/anaconda1anaconda2anaconda3/bin/conda-build", line 3, in <module>
    from conda_build.main_build import main
  File "/opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages/conda_build/main_build.py", line 24, in <module>
    from conda_build.build import bldpkg_path
  File "/opt/anaconda1anaconda2anaconda3/lib/python2.7/site-packages/conda_build/build.py", line 28, in <module>
    from conda.utils import url_path
ImportError: cannot import name url_path
```

**Comment by HugoTian** [comment]
Thanks, ilan, and we already fix this on master branch on github
https://github.com/conda/conda/blob/master/conda/utils.py#L364
