### ISSUE TITLE
Anaconda3 parcel: conda problems

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3206]
Should I expect the `activate` script to work for regular users accessing the `root`-installed Anaconda3 custom parcel?

```
[jsmith@olympic ~]$ conda create -n pandas pandas
Fetching package metadata .......
Solving package specifications: ..........
Using Anaconda Cloud api site https://api.anaconda.org

Package plan for installation in environment /home/jsmith/.conda/envs/pandas:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytz-2016.6.1              |           py35_0         177 KB
    six-1.10.0                 |           py35_0          17 KB
    python-dateutil-2.5.3      |           py35_0         237 KB
    pandas-0.18.1              |      np111py35_0        14.1 MB
    ------------------------------------------------------------
                                           Total:        14.5 MB

The following NEW packages will be INSTALLED:

    mkl:             11.3.3-0           (soft-link)
    numpy:           1.11.1-py35_0      (soft-link)
    openssl:         1.0.2h-1           (soft-link)
    pandas:          0.18.1-np111py35_0
    pip:             8.1.2-py35_0       (soft-link)
    python:          3.5.2-0            (soft-link)
    python-dateutil: 2.5.3-py35_0      
    pytz:            2016.6.1-py35_0   
    readline:        6.2-2              (soft-link)
    setuptools:      23.0.0-py35_0      (soft-link)
    six:             1.10.0-py35_0     
    sqlite:          3.13.0-0           (soft-link)
    tk:              8.5.18-0           (soft-link)
    wheel:           0.29.0-py35_0      (soft-link)
    xz:              5.2.2-0            (soft-link)
    zlib:            1.2.8-3            (soft-link)

Proceed ([y]/n)? y

Fetching packages ...
pytz-2016.6.1- 100% |###############################################################################################################################| Time: 0:00:00 357.69 kB/s
six-1.10.0-py3 100% |###############################################################################################################################| Time: 0:00:00 123.40 kB/s
python-dateuti 100% |###############################################################################################################################| Time: 0:00:00 413.56 kB/s
pandas-0.18.1- 100% |###############################################################################################################################| Time: 0:00:02   5.90 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate pandas
#
# To deactivate this environment, use:
# $ source deactivate
#
[jsmith@olympic ~]$ source activate pandas
Traceback (most recent call last):
  File "/opt/cloudera/parcels/Anaconda3-4.1.2/bin/conda", line 4, in <module>
    from conda.cli.main import main
ImportError: No module named 'conda'
-bash: [: =: unary operator expected
[jsmith@olympic ~]$ conda info -a
Traceback (most recent call last):
  File "/home/jsmith/.conda/envs/pandas/bin/conda", line 4, in <module>
    from conda.cli.main import main
ImportError: No module named 'conda'
```

**Comment by kalefranz** [comment]
Ian I haven't worked with parcels and not exactly sure yet how to help or where to start. Maybe @ilanschnell has some input?

**Comment by ijstokes** [comment]
@mrduane @multicastmatt who "owns" the Anaconda Parcel?  It seems to me there should be a solution to this problem, perhaps via https://github.com/cloudera/cm_ext/wiki/The%20Parcel%20Defines%20Script -- basically as Hadoop features grow in commercial significance we should improve the quality of the parcel.  If `activate` doesn't work, then it should be removed (and also any other pieces that we know will never work), but preferably we can figure out how to solve these issues so parcels can appear to be as close to a standard Anaconda installation as possible.

**Comment by kalefranz** [comment]
@ijstokes if you need further help with parcels, probably best to talk with @csoja or @ilanschnell directly
