### ISSUE TITLE
geopandas install failed

### ISSUE THREAD

**Issue by pinhead001** [conda/conda#3225]
I am attempting to install geopandas via conda. I received the following error...

An unexpected error has occurred, please consider sending the            |  50%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_install.py", line 78, in exec
ute
    install(args, parser, 'install')
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\plan.py", line 599, in execute_actions

    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\instructions.py", line 135, in execute
_instructions
    cmd(state, arg)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_
CMD
    extract(arg)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\install.py", line 859, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\cnelson\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\install.py", line 245, in exp_backoff_
fn
    result = fn(*args)
WindowsError: [Error 5] Access is denied

----------------------------

Here is the conda info...

PS C:\Users\cnelson> conda info

Warning: could not import binstar_client ('args' object has no attribute 'site')Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.14.1
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\Users\cnelson\AppData\Local\Continuum\Anaconda  (writable)
  default environment : C:\Users\cnelson\AppData\Local\Continuum\Anaconda
     envs directories : C:\Users\cnelson\AppData\Local\Continuum\Anaconda\envs
        package cache : C:\Users\cnelson\AppData\Local\Continuum\Anaconda\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False

------------------------------------

Any suggestions?

Thanks,
Chris

**Comment by HugoTian** [comment]
can you show me the output of conda --debug install your_package ?

Thanks

**Comment by HugoTian** [comment]
Please refer to issue #3271, feel free to reopen this issue and @ me
