### ISSUE TITLE
TensorFlow fail to install

### ISSUE THREAD

**Issue by D-Dark** [conda/conda#3230]
Traceback (most recent call last):
  File "/root/anaconda2/envs/tensorflow/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "/root/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 419, in download
    chunk = resp.raw.read(2**14)
  File "/root/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/root/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/root/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 246, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

**Comment by HugoTian** [comment]
Can you show me the output of conda info ?

Thanks

**Comment by HugoTian** [comment]
'Connection reset by peer' generally means retry later , and could you retry this command later ?

In future we will better handle this exception and give proper error message

**Comment by HugoTian** [comment]
I am about to close this issue, and if the retry still fails, feel free to reopen this issue
