### ISSUE TITLE
error with command: conda create -n py27 python=2.7 anaconda

### ISSUE THREAD

**Issue by HugoSiles** [conda/conda#3233]
I am trying to create a python27 environment in anaconda3, but I get the following error ( it is the same the other way around):
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\Scripts\conda-script.py", line 5

```
sys.exit(main())
```

  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\main
0, in main
    exit_code = args_func(args, p)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\main
0, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\main
line 58, in execute
    install(args, parser, 'create')
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\inst
 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\plan.py"
n execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\instruct
e 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\instruct
e 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\install.
2, in link
    if not run_script(prefix, dist, 'post-link'):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\install.
, in run_script
    subprocess.check_call(args, env=env)
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 576, in
    retcode = call(_popenargs, *_kwargs)
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 557, in
    with Popen(_popenargs, *_kwargs) as p:
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 947, in
    restore_signals, start_new_session)
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 1224, i
ild
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file spe

C:\Users\Usuario>conda info
Current conda install:

```
         platform : win-64
    conda version : 4.1.11
conda-env version : 2.5.1
```

  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\Usuario\Anaconda3  (writable)
  default environment : C:\Users\Usuario\Anaconda3
     envs directories : C:\Users\Usuario\Anaconda3\envs
        package cache : C:\Users\Usuario\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64
                        https://repo.continuum.io/pkgs/msys2/noarch
          config file : None
         offline mode : False
    is foreign system : False
Thanks for any help
Hugo Siles

**Comment by HugoTian** [comment]
Please refer to this [here](http://stackoverflow.com/questions/3022013/windows-cant-find-the-file-on-subprocess-call)

It seems you have your own script, and could you please try add shell=True in the conda/install.py module based on your traceback ?

**Comment by HugoSiles** [comment]
I am not aware about the script you mention, where can I look for it ? I don't have any interest in such script.
Hugo Siles

**Comment by kalefranz** [comment]
Have you inadvertently cut off the right part of the error message by chance?  From above:

```
File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 1224, i
ild
startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file spe
```

**Comment by HugoSiles** [comment]
indeed I realize now that you mention, probably a few letters, it should be : .... file specified. that's all.

**Comment by HugoSiles** [comment]
in conda\install.py,  in line 550 I introduced shell=True, the error continues to show

Traceback (most recent call last):
  File "C:\Users\Usuario\Anaconda3\Scripts\conda-script.py", line 5, in <module>

    sys.exit(main())
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\main.py", line 12
0, in main
    exit_code = args_func(args, p)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\main.py", line 13
0, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\main_create.py",
line 58, in execute
    install(args, parser, 'create')
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\cli\install.py", line
 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\plan.py", line 599, i
n execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\instructions.py", lin
e 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\instructions.py", lin
e 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\install.py", line 109
2, in link
    if not run_script(prefix, dist, 'post-link'):
  File "C:\Users\Usuario\Anaconda3\lib\site-packages\conda\install.py", line 550
, in run_script
    subprocess.check_call(args,shell=True, env=env)
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Usuario\Anaconda3\lib\subprocess.py", line 1224, in _execute_ch
ild
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

C:\Users\Usuario>conda info
Current conda install:

             platform : win-32
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\Usuario\Anaconda3  (writable)
  default environment : C:\Users\Usuario\Anaconda3
     envs directories : C:\Users\Usuario\Anaconda3\envs
        package cache : C:\Users\Usuario\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-32/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-32/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by HugoSiles** [comment]
I have installed anaconda2-4.1.1-Windows-x86_64, and I don't have any problem installing non-standard packages such as wxpython with conda install ................ . However when I try to install mayavi, I get exactly the same list of errors that I sent already, no difference at all. What kind of bug is this?

cheers
 Hugo Siles

**Comment by kalefranz** [comment]
Is this error still occurring with recent versions of conda?  Latest release is 4.3.17.
