### ISSUE TITLE
conda canary: "AttributeError: 'NoneType' object has no attribute 'rstrip'" in conda\models\channel.py

### ISSUE THREAD

**Issue by mwiebe** [conda/conda#3235]
Here's the output it suggested to post:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues


Current conda install:

               platform : win-64
          conda version : 4.2.1
       conda is private : False
      conda-env version : 2.5.2
    conda-build version : 1.21.9
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : defaults
            config file : C:\Users\mwiebe\.condarc
           offline mode : False


`$ C:\Anaconda3\Scripts\conda-env-script.py update -f C:\Dev\SequoiaAll\envs\\msvc2015rel.yml -n sequoia_all_msvc2015rel --prune`


    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 403, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda_env\cli\main_update.py", line 112, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "C:\Anaconda3\lib\site-packages\conda_env\installers\conda.py", line 15, in install
        prepend='nodefaults' not in env.channels)
      File "C:\Anaconda3\lib\site-packages\conda_env\cli\common.py", line 98, in get_index_trap
        return get_index(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\api.py", line 23, in get_index
        channel_urls = prioritize_channels(channel_urls)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 171, in prioritize_channels
        channel = Channel(chn)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 117, in __init__
        self._path, self._platform = split_platform(parsed.path)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 99, in split_platform
        parts = value.rstrip('/').rsplit('/', 1)
    AttributeError: 'NoneType' object has no attribute 'rstrip'
```

**Comment by mwiebe** [comment]
After deleting .condarc and downgrading to conda 4.1.11, I get the following when I try again:

```
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-env-script.py", line 3, in <module>
    import conda_env.cli.main
ImportError: No module named 'conda_env'

C:\Dev\SequoiaAll\envs>conda install conda-env
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Anaconda3:
#
conda-env                 2.5.2                    py35_0

C:\Dev\SequoiaAll\envs>conda remove conda-env
Fetching package metadata .........
Solving package specifications: ..........
Error: this 'remove' command cannot be executed because it
would require removing 'conda' dependencies
```

**Comment by mwiebe** [comment]
I fixed the conda-env issue by downgrading to 2.5.1 then upgrading to 2.5.2. Is there a recommended mechanism for correcting problems like this?

**Comment by kalefranz** [comment]
The next conda canary release should force conda-env 2.6, which is just an empty package.(conda-env has been brought into this repo now.)  I'll also fix that stack trace.

**Comment by HugoTian** [comment]
it is hard for me to reproduce the error, and I think, later we may add more log.debug to help us debug when unexpected error happened

**Comment by kalefranz** [comment]
@mwiebe When you got the original error here, what was the command you were running? Presumably something with conda-env?  If you have an `environment.yml` file or something like that you were using, do you mind providing it here?

**Comment by mwiebe** [comment]
It was the command listed in the copy/pasted output:

`C:\Anaconda3\Scripts\conda-env-script.py update -f C:\Dev\SequoiaAll\envs\\msvc2015rel.yml -n sequoia_all_msvc2015rel --prune`

Here's the .yml file:

```
name: sequoia_all_msvc2015rel
channels:
- http://conda-01
- nodefaults
dependencies:
- msvc2015rel
- boost
- ceres-solver
- eigen
- flexlm
- glog
- gtest
- ilmbase
- imagemagick
- jpeg
- laszip
- libe57
- lua=5.3.3
- lz4
- ogre=1.9.0
- ogredeps
- openexr
- openimageio
- png
- qt5
- rply
- sqlite=3.11.0
- stxxl
- tbb
- tiff
- utf8cpp
- xerces
- xxhash
- zlib
- ptex
- riegl
- zflaser
- fbx
- ninja
```

**Comment by HugoTian** [comment]
@mwiebe Thanks for your info, and I find the bug now, 

It happens in code [here](https://github.com/conda/conda/blob/master/conda/models/channel.py#L114)

For channel   http://conda-01, we use parse_url function from requests library [here](https://github.com/kennethreitz/requests/blob/master/requests/packages/urllib3/util/url.py#L123)

And based on the comments of that function, when we parse it, it will give following result 

Url(scheme='http', auth=None, host='conda-01', port=None, path=None, query=None, fragment=None)

Later when we call split_platform(parsed.path), the input is None, and it result in the error

**Comment by HugoTian** [comment]
@kalefranz 
So, basically my suggestion on this bug, is to pay special attention to this parse_url function. The parsed result has many parts, and I believe we want both host and path.

**Comment by HugoTian** [comment]
I already create a PR for this issue, please refer to #3248
