### ISSUE TITLE
conda canary unable to remove environment

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3251]
I just tried to remove the _test environment from my last build with the conda canary, but I got an error:
```
 2(psreldev) psel701: /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/conda-bld/broken $ conda env remove -n _test
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues


Current conda install:

               platform : linux-64
          conda version : 4.2.1
       conda is private : False
      conda-env version : 2.5.2
    conda-build version : 1.21.9
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7  (writable)
    default environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7
       envs directories : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs
          package cache : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/pkgs
           channel URLs : file:///reg/g/psdm/sw/conda/channels/system-rhel7
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7
                          defaults
                          scikit-beam
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7
            config file : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc
           offline mode : False


`$ /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/bin/conda-env remove -n _test`


    Traceback (most recent call last):
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/exceptions.py", line 403, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 46, in execute
        conda.cli.main_remove.execute(Namespace(**args), parser)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main_remove.py", line 119, in execute
        prefix = context.prefix_w_legacy_search
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/base/context.py", line 142, in prefix_w_legacy_search
        return get_prefix(self, self._argparse_args, True)
    AttributeError: 'Context' object has no attribute '_argparse_args'
Subprocess exiting

```

**Comment by HugoTian** [comment]
Please try to use conda command, instead of condo-env command. Please try

conda remove -n _test --all

It will delete all packages in _test , as well as  the environment.

For the bug you encounter, we already fix in master branch, please refer to [here](https://github.com/conda/conda/blob/master/conda_env/cli/main.py#L58), this line will fix the bug you found

Thanks

**Comment by davidslac** [comment]
Thanks, conda remove -n _test --all is working.
