### ISSUE TITLE
conda canary - unable to create environment yml file

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3253]
I just did
`
(anabase) (psreldev) psel701: /reg/g/psdm/sw/conda/logs $ conda env export > ../manage/config/environment-anabase-1.0.0.yml`

anabase is the environment, I also add the account, psreldev, that I'm logged into, and got this output
```
n unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues


Current conda install:

               platform : linux-64
          conda version : 4.2.1
       conda is private : False
      conda-env version : 2.5.2
    conda-build version : 1.21.11+0.g5b44ab3.dirty
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7  (writable)
    default environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/anabase
       envs directories : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs
          package cache : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/pkgs
           channel URLs : file:///reg/g/psdm/sw/conda/channels/system-rhel7
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7
                          defaults
                          scikit-beam
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7
            config file : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc
           offline mode : False


`$ /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/bin/conda-env export`


    Traceback (most recent call last):
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/exceptions.py", line 403, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda_env/cli/main_export.py", line 93, in execute
        ignore_channels=args.ignore_prefix)
    AttributeError: 'Namespace' object has no attribute 'ignore_prefix'
../manage/config/environment-anabase-1.0.0.yml (END)

```

Here is the environment, if this matters - there is one pip in there, nose2
```
(anabase) (psreldev) psel701: /reg/g/psdm/sw/conda/logs $ conda list
# packages in environment at /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/anabase:
#
backports                 1.0                      py27_0  
boost                     1.57.0                        4  
cairo                     1.12.18                       6  
coverage                  4.1                      py27_0  
cycler                    0.10.0                   py27_0  
cython                    0.24.1                   py27_0  
decorator                 4.0.10                   py27_0  
szip                      2.1                         100    file:///reg/g/psdm/sw/conda/channels/external-rhel7
h5py                      2.5.0           py27_hdf518_mpi4py2_100    file:///reg/g/psdm/sw/conda/channels/system-rhel7
hdf5                      1.8.17              openmpi_100    file:///reg/g/psdm/sw/conda/channels/system-rhel7
mpi4py                    2.0.0           py27_openmpi_100    file:///reg/g/psdm/sw/conda/channels/system-rhel7
openmpi                   1.10.3            lsf_verbs_100    file:///reg/g/psdm/sw/conda/channels/system-rhel7
tables                    3.2.3.1          py27_hdf18_100    file:///reg/g/psdm/sw/conda/channels/system-rhel7
fontconfig                2.11.1                        6  
freetype                  2.5.5                         1  
get_terminal_size         1.0.0                    py27_0  
glib                      2.43.0                        1  
harfbuzz                  0.9.39                        1  
icu                       54.1                          0  
ipython                   5.0.0                    py27_0  
ipython_genutils          0.1.0                    py27_0  
jbig                      2.1                           0  
jinja2                    2.8                      py27_1  
jpeg                      8d                            1  
libffi                    3.2.1                         0  
libgfortran               3.0.0                         1  
libpng                    1.6.22                        0  
libsodium                 1.0.10                        0  
libtiff                   4.0.6                         2  
libxml2                   2.9.2                         0  
markupsafe                0.23                     py27_2  
matplotlib                1.5.1               np111py27_0  
mkl                       11.3.3                        0  
mysql                     5.5.24                        0  
networkx                  1.11                     py27_0  
nose                      1.3.7                    py27_1  
nose2                     0.6.5                     <pip>
numexpr                   2.6.1               np111py27_0  
numpy                     1.11.1                   py27_0  
openssl                   1.0.2h                        1  
pandas                    0.18.1              np111py27_0  
pango                     1.39.0                        1  
path.py                   8.2.1                    py27_0  
pathlib2                  2.1.0                    py27_0  
pexpect                   4.0.1                    py27_0  
pickleshare               0.7.3                    py27_0  
pillow                    3.3.0                    py27_0  
pip                       8.1.2                    py27_0  
pixman                    0.32.6                        0  
prompt_toolkit            1.0.3                    py27_0  
ptyprocess                0.5.1                    py27_0  
pycairo                   1.10.0                   py27_0  
pygments                  2.1.3                    py27_0  
pyparsing                 2.1.4                    py27_0  
pyqt                      4.11.4                   py27_4  
pyqtgraph                 0.9.10                   py27_1  
python                    2.7.12                        1  
python-dateutil           2.5.3                    py27_0  
pytz                      2016.6.1                 py27_0  
pyzmq                     15.3.0                   py27_0  
qt                        4.8.5                         0  
readline                  6.2                           2  
lmfit                     0.8.3                    py27_0    scikit-beam
scikit-beam               0.0.8                    py27_0    scikit-beam
xraylib                   3.1.0                  nppy27_0    scikit-beam
scikit-image              0.12.3              np111py27_1  
scikit-learn              0.17.1              np111py27_2  
scipy                     0.18.0              np111py27_0  
scons                     2.3.0                    py27_0  
setuptools                23.0.0                   py27_0  
simplegeneric             0.8.1                    py27_1  
sip                       4.18                     py27_0  
six                       1.10.0                   py27_0  
sqlite                    3.13.0                        0  
tk                        8.5.18                        0  
traitlets                 4.2.2                    py27_0  
wcwidth                   0.1.7                    py27_0  
wheel                     0.29.0                   py27_0  
xz                        5.2.2                         0  
zeromq                    4.1.4                         0  
zlib                      1.2.8                         3  

```

**Comment by davidslac** [comment]
Perhaps related to above, after I create the environment file with the non-canaray conda, i.e, 
```
anabase) (psreldev) psdev105: /reg/g/psdm/sw/conda $ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.9
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6  (writable)
  default environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/envs/anabase
     envs directories : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/envs
        package cache : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/pkgs
         channel URLs : file:///reg/g/psdm/sw/conda/channels/system-rhel6/linux-64/
                        file:///reg/g/psdm/sw/conda/channels/system-rhel6/noarch/
                        file:///reg/g/psdm/sw/conda/channels/psana-rhel6/linux-64/
                        file:///reg/g/psdm/sw/conda/channels/psana-rhel6/noarch/
                        file:///reg/g/psdm/sw/conda/channels/external-rhel6/linux-64/
                        file:///reg/g/psdm/sw/conda/channels/external-rhel6/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/t/<TOKEN>/scikit-beam/linux-64/
                        https://conda.anaconda.org/t/<TOKEN>/scikit-beam/noarch/
                        file:///reg/g/psdm/sw/conda/channels/testing-rhel7/linux-64/
                        file:///reg/g/psdm/sw/conda/channels/testing-rhel7/noarch/
          config file : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/.condarc
         offline mode : False
    is foreign system : False

```

I am unable to create a new environment from it, I get the message:

```
Error: Packages missing in current linux-64 channels: 
  - file:///reg/g/psdm/sw/conda/channels/external-rhel6::szip 2.1 100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::h5py 2.5.0 py27_hdf518_mpi4py2_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::hdf5 1.8.17 openmpi_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::mpi4py 2.0.0 py27_openmpi_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::openmpi 1.10.3 lsf_verbs_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::tables 3.2.3.1 py27_hdf18_100
  - scikit-beam::lmfit 0.8.3 py27_0
  - scikit-beam::scikit-beam 0.0.8 py27_0
  - scikit-beam::xraylib 3.1.0 nppy27_0

```

but the packages are there, for instance I can create an environment with szip:

```
anabase) (psreldev) psdev105: /reg/g/psdm/sw/conda $ conda create -n szip szip=2.1=100
Package plan for installation in environment /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/envs/szip:

The following NEW packages will be INSTALLED:

    szip: 2.1-100 file:///reg/g/psdm/sw/conda/channels/external-rhel6

Proceed ([y]/n)? n

```

**Comment by davidslac** [comment]
Following along on this page
I tried to create an environment from a spec file, but I got errors about the lines with comments:
```
(anabase) (psreldev) psel701: /reg/g/psdm/sw/conda $ conda list -e > manage/config/spec-file-anabase-1.0.0.txt 
(anabase) (psreldev) psel701: /reg/g/psdm/sw/conda $ conda env create --name ana-1.0.0 --file manage/config/spec-file-anabase-1.0.0.txt 
Using Anaconda API: https://api.anaconda.org
Value error: invalid package specification: # This file may be used to create an environment using:

```after deleting the initial header lines that had # in the front, it seems to be working

**Comment by HugoTian** [comment]
For the first bug you got, it is caused by a wrong attribute in a NameSpace, please refer to [here](https://github.com/conda/conda/blob/4.2.1/conda_env/cli/main_export.py#L93), it should be args.ignore_channels, instead of ignore_prefix

**Comment by HugoTian** [comment]
For the second bug, cannot create env from .txt file, it is caused by NoneType Error, please refer to [here](https://github.com/conda/conda/blob/4.1.x/conda/cli/common.py#L479). 

This is an error for conda 4.1.x. After strip the comment, the result may be None. However, it forward to MatchSpec class without None-checking, as a result, it will leads to a NoneType-related exception, and raise a CondaValue error

**Comment by HugoTian** [comment]
I have created 2 PR for this issue, please refer to #3258 and #3259 

Thanks for you info, we will make conda env more and more stable

**Comment by davidslac** [comment]
Great! glad to help.

best,

David

**Comment by HugoTian** [comment]
@davidslac , If I understand correctly, there is still one more question about the missing package when creating env from file.

Could you show me the the env file that leads to that error ?

Error: Packages missing in current linux-64 channels: 
  - file:///reg/g/psdm/sw/conda/channels/external-rhel6::szip 2.1 100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::h5py 2.5.0 py27_hdf518_mpi4py2_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::hdf5 1.8.17 openmpi_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::mpi4py 2.0.0 py27_openmpi_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::openmpi 1.10.3 lsf_verbs_100
  - file:///reg/g/psdm/sw/conda/channels/system-rhel6::tables 3.2.3.1 py27_hdf18_100
  - scikit-beam::lmfit 0.8.3 py27_0
  - scikit-beam::scikit-beam 0.0.8 py27_0
  - scikit-beam::xraylib 3.1.0 nppy27_0

**Comment by davidslac** [comment]
Hi Tian, yes, I am unable to create an environment file from the yaml file - it would be nice if I could create it from the yaml file since that has the channel information. I am able to create it from the spec-file. However when I look at the below yaml file, there are some things that seem wrong with it, namely the pip section, I don't understand that - the only thing I might have done a pip install of into the environment was nose2, but that didn't show up. hp5y 2.5.0 and mpi4py 2.0.0 and tables 3.2.3.1, all of these I made proper conda packages for - but they are in my file based urls. Also scikit-beam is a proper conda package, but from a non-defaults channel. In anycase, below is  environment.yml file that causes problems:
```
name: anabase
channels:
- file:///reg/g/psdm/sw/conda/channels/system-rhel6
- file:///reg/g/psdm/sw/conda/channels/psana-rhel6
- file:///reg/g/psdm/sw/conda/channels/external-rhel6
- defaults
- scikit-beam
- file:///reg/g/psdm/sw/conda/channels/testing-rhel7
dependencies:
- backports=1.0=py27_0
- boost=1.57.0=4
- cairo=1.12.18=6
- coverage=4.1=py27_0
- cycler=0.10.0=py27_0
- cython=0.24.1=py27_0
- decorator=4.0.10=py27_0
- file:///reg/g/psdm/sw/conda/channels/external-rhel6::szip=2.1=100
- file:///reg/g/psdm/sw/conda/channels/system-rhel6::h5py=2.5.0=py27_hdf518_mpi4py2_100
- file:///reg/g/psdm/sw/conda/channels/system-rhel6::hdf5=1.8.17=openmpi_100
- file:///reg/g/psdm/sw/conda/channels/system-rhel6::mpi4py=2.0.0=py27_openmpi_100
- file:///reg/g/psdm/sw/conda/channels/system-rhel6::openmpi=1.10.3=lsf_verbs_100
- file:///reg/g/psdm/sw/conda/channels/system-rhel6::tables=3.2.3.1=py27_hdf18_100
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- get_terminal_size=1.0.0=py27_0
- glib=2.43.0=1
- harfbuzz=0.9.39=1
- icu=54.1=0
- ipython=5.0.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=1
- libffi=3.2.1=0
- libgfortran=3.0.0=1
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mkl=11.3.3=0
- mysql=5.5.24=0
- networkx=1.11=py27_0
- nose=1.3.7=py27_1
- numexpr=2.6.1=np111py27_0
- numpy=1.11.1=py27_0
- openssl=1.0.2h=1
- pandas=0.18.1=np111py27_0
- pango=1.39.0=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.3=py27_0
- pillow=3.3.0=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pygments=2.1.3=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pyzmq=15.3.0=py27_0
- qt=4.8.5=0
- readline=6.2=2
- scikit-beam::lmfit=0.8.3=py27_0
- scikit-beam::scikit-beam=0.0.8=py27_0
- scikit-beam::xraylib=3.1.0=nppy27_0
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.17.1=np111py27_2
- scipy=0.18.0=np111py27_0
- scons=2.3.0=py27_0
- setuptools=23.0.0=py27_0
- simplegeneric=0.8.1=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- traitlets=4.2.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- xz=5.2.2=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - h5py==2.5.0
  - ipython-genutils==0.1.0
  - lmfit==0.8.3
  - mpi4py==2.0.0
  - prompt-toolkit==1.0.3
  - scikit-beam==0.0.8.post0
  - tables==3.2.3.1
prefix: /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/envs/anabase


```

**Comment by ChrisBarker-NOAA** [comment]
Similar issues here:

starting with everything updated -- crate a new environment, instal a bunch of stuff (most with conda, a little with pip) then export it to a yaml file, then I can't re-create it with the yaml file right away -- pretty darn major bug!

$ conda --version
conda 4.1.11

I'm guessing this has to do with all the channel info??

oh, and I also get all sorts of stuff listed under pip that were conda installed.

(is this because the conda build did a pip install? -- i.e. the packages are installed with all the proper pip meta data)

Here is the yaml:
```
name: maproom2
channels:
- NOAA-ORR-ERD
- conda-forge
- defaults
dependencies:
- NOAA-ORR-ERD::pyproj=1.9.4=py27_1
- NOAA-ORR-ERD::pytest-cov=2.2.1=py_0
- NOAA-ORR-ERD::pyugrid=0.2.2=py27_0
- NOAA-ORR-ERD::wxpython=3.0.2.0=py27_0
- conda-forge::ca-certificates=2016.8.2=3
- conda-forge::certifi=2016.8.2=py27_0
- conda-forge::curl=7.49.1=0
- conda-forge::cython=0.24.1=py27_0
- conda-forge::expat=2.1.0=1
- conda-forge::freetype=2.6.3=1
- conda-forge::freexl=1.0.2=1
- conda-forge::gdal=2.1.1=np111py27_1
- conda-forge::geos=3.4.2=2
- conda-forge::giflib=5.1.2=1
- conda-forge::hdf4=4.2.11=4
- conda-forge::hdf5=1.8.17=2
- conda-forge::icu=56.1=4
- conda-forge::jpeg=9b=0
- conda-forge::json-c=0.12=0
- conda-forge::kealib=1.4.6=3
- conda-forge::libdap4=3.18.0=2
- conda-forge::libiconv=1.14=3
- conda-forge::libnetcdf=4.4.0=2
- conda-forge::libpng=1.6.23=0
- conda-forge::libspatialite=4.3.0a=9
- conda-forge::libtiff=4.0.6=6
- conda-forge::libuuid=1.0.3=1
- conda-forge::libxml2=2.9.3=9
- conda-forge::ncurses=5.9=8
- conda-forge::netcdf4=1.2.4=np111py27_2
- conda-forge::openjpeg=2.1.0=6
- conda-forge::openssl=1.0.2h=2
- conda-forge::pillow=3.3.0=py27_0
- conda-forge::pip=8.1.2=py27_0
- conda-forge::postgresql=9.5.3=2
- conda-forge::proj.4=4.9.2=0
- conda-forge::pycrypto=2.6.1=py27_0
- conda-forge::pyinstaller=3.2=py27_2
- conda-forge::pyparsing=2.1.1=py27_0
- conda-forge::pytest=2.9.2=py27_0
- conda-forge::pytz=2016.6.1=py27_0
- conda-forge::readline=6.2=0
- conda-forge::requests=2.10.0=py27_0
- conda-forge::shapely=1.5.16=np111py27_1
- conda-forge::six=1.10.0=py27_0
- conda-forge::sqlite=3.13.0=1
- conda-forge::wheel=0.29.0=py27_0
- conda-forge::xerces-c=3.1.4=2
- conda-forge::xz=5.2.2=0
- conda-forge::zlib=1.2.8=3
- configobj=5.0.6=py27_0
- coverage=4.2=py27_0
- nomkl=1.0=0
- numpy=1.11.1=py27_nomkl_0
- py=1.4.31=py27_0
- pyopengl=3.1.1a1=np111py27_0
- pyopengl-accelerate=3.1.1a1=np111py27_0
- python=2.7.12=1
- python.app=1.2=py27_4
- reportlab=3.3.0=py27_0
- setuptools=19.2=py27_0
- tk=8.5.18=0
- pip:
  - atrcopy==3.1.0
  - bson==0.4.3
  - certifi==2016.8.2
  - cython==0.24.1
  - gdal==2.1.1
  - jsonpickle==0.9.3
  - maproom (/Users/chris.barker/HAZMAT/ERD-PythonPackages/MapRoom)==3.1b27
  - netcdf4==1.2.4
  - omnivore==0.13.2
  - owslib (/Users/chris.barker/HAZMAT/ERD-PythonPackages/MapRoom/deps/OWSLib)==0.9.dev0
  - pillow==3.3.0
  - pip==8.1.2
  - post-gnome (/Users/chris.barker/HAZMAT/ERD-PythonPackages/MapRoom/deps/GnomeTools/post_gnome)==0.1.0
  - pycrypto==2.6.1
  - pyinstaller==3.2
  - pyparsing==2.1.1
  - pyproj==1.9.4
  - pytest==2.9.2
  - pytest-cov==2.2.1
  - python-dateutil==2.5.3
  - pytriangle==1.6.1
  - pytz==2016.6.1
  - pyugrid==0.2.2
  - requests==2.10.0
  - shapely==1.5.16
  - six==1.10.0
  - wheel==0.29.0
  - wxpython==3.0.2.0
  - wxpython-common==3.0.2.0
prefix: /Users/chris.barker/miniconda2/envs/maproom
```

**Comment by HugoTian** [comment]
@ChrisBarker-NOAA  , can you show me the command and error message when you re-create the environment from yml file ?

Thanks

**Comment by ChrisBarker-NOAA** [comment]
`$ conda env create -f maproom_environment.yml` 

```
Using Anaconda Cloud api site https://api.anaconda.org
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: .
Error: Packages missing in current osx-64 channels: 
  - noaa-orr-erd::pyproj 1.9.4 py27_1
  - noaa-orr-erd::pytest-cov 2.2.1 py_0
.....
```

(pretty much all of them)

but, for instance:

```
$ conda search pyproj
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
pyproj                       1.9.4                    py27_0  conda-forge/osx-64 
                             1.9.4                    py27_0  NOAA-ORR-ERD/osx-64 
                             1.9.4                    py34_0  conda-forge/osx-64 
                             1.9.4                    py35_0  conda-forge/osx-64 
                          .  1.9.4                    py27_1  NOAA-ORR-ERD/osx-64 
                             1.9.5.1                  py27_0  conda-forge/osx-64 
                             1.9.5.1                  py27_0  defaults        
                             1.9.5.1                  py34_0  defaults        
                             1.9.5.1                  py34_0  conda-forge/osx-64 
                             1.9.5.1                  py35_0  conda-forge/osx-64 
                             1.9.5.1                  py35_0  defaults        
```

you can see pyproj 1.9.5 in the NOAA-ORR-ERD osx-64 channel

and of, course, the rest are there -- I built this all up right before I exported the yaml file.

**Comment by njalerikson** [comment]
I am pretty sure this issue is caused by the channels listed uniquely for select packages:

**Fails:**
```
name: root
dependencies:
- conda-forge::nb_anacondacloud 1.1.0 py27_1
```

**Succeeds:**
```
name: root
channels:
- conda-forge
dependencies:
- nb_anacondacloud 1.1.0 py27_1
```

The same issue also occurs for local channels (using `file://`).

**Comment by ChrisBarker-NOAA** [comment]
sure, but:

This yaml file was created by conda -- so it certainly should be usable by conda!

and the stanza from "succeeds" in your example above is fragile -- if there is more than one channel listed (and default is always there, yes?), then the package could get pulled from a different channel then it was originally, and they are not guaranteed to be the same.

perhaps there should be no "channels" stanza in there, and have each package specify where it came from instead.

**Comment by kalefranz** [comment]
@ChrisBarker-NOAA Can you give me the list of commands that--*from scratch*--I can use to recreate your yaml file?  I'd like to reproduce this completely so I can figure out what's going on.  The pip dependencies are especially concerning.

**Comment by HugoTian** [comment]
@kalefranz , I already find the bug. 

@ChrisBarker-NOAA , generally, it is a conda-env issue, not a conda bug.

In conda env create , when the specification is like channel::package, conda env does not parse it, and give it to conda. More importantly, the index that conda env got has no info about that channel.

As a result, when everything passed from condo-env to conda, it will raise exception

**Comment by ChrisBarker-NOAA** [comment]
Sure -- it's ugly, be prepared :-)

(pasted from an internal wiki -- you probably don't have to do all of that -- just the main packages from multiple channels)



Notes on building a redistributable version using the Conda distribution of Python...

# Setting up the conda environment

Use the [Miniconda binary installer](http://conda.pydata.org/miniconda.html), then configure the environment and install packages:

```
conda config --add channels conda-forge
conda config --add channels NOAA-ORR-ERD
conda install conda-build
```
# Installing packages
Install the source code if you have not already:
```
git clone git@gitlab.orr.noaa.gov:erd/MapRoom.git
cd maproom
```
Install the required packages:
```
conda env create -f maproom_environment.yml
source activate maproom
```
then install the manual dependencies (pytriangle, post_gnome, my hacked version of OWSLib) using a script in MapRoom:
```
python installdeps.py
```

# Running MapRoom from source

MapRoom needs access to the windowing system, so you have to run it using
```
pythonw maproom.py
```

# Creating the application bundle

Pyinstaller has a few quirks, so I created a build script to work around the issues. At the top level directory, use the script:
```
./build_pyinstaller.sh
```
and it should create a file ``dist-[VERSION]/Maproom.app`` that can be opened and an archive file ``dist-[VERSION]/Maproom-[VERSION]-darwin.tbz`` that can be transported to another machine.

**Comment by ChrisBarker-NOAA** [comment]
So is there a fix in the works?

Why in the world would conda environment create a yaml file that conda can't parse???

**Comment by HugoTian** [comment]
@ChrisBarker-NOAA 

We will have a fix for that.

Basically, 

    conda list -e > tmp.txt
    conda create -n env_name --file tmp.txt

and 

   conda env export -n env > tmp.yml
   conda env create -f tmp.yml

are 2 ways to export and import environment.

Now in conda 4.1, it seems neither works correctly. We will have a fix in conda 4.2 and add regression test when we introduce new features.

**Comment by HugoTian** [comment]
@ChrisBarker-NOAA , I have a tmp fix for the issue, now in PR #3286.

This PR is focusing on conda env create . Now channel error all fixed, but need more test. Still fail on pip install. Has error like :
 
    Invalid requirement: 'maproom (/Users/chris.barker/HAZMAT/ERD-    PythonPackages/MapRoom)==3.1b27'
It looks like a path. Does it exist ?

**Comment by ChrisBarker-NOAA** [comment]
Awesome! thanks.

> Invalid requirement:
`maproom (/Users/chris.barker/HAZMAT/ERD-PythonPackages/MapRoom)==3.1b27`

It looks like a path. Does it exist ? 

yes, but it is a package instaleld via `setup.py develop`  So I'm not sure I'd expect it to work at all.

In particular, it's certainly not going to be relocatable to another machine that doesn't have it in that path.

Sorry to leave that in there -- kind of a red herring.

It may be possible to do it in a way that pip could re-install.  This may work:

pip install -e /Users/chris.barker/HAZMAT/ERD-PythonPackages/MapRoom

But in the meantime, perhaps conda export should identify those and simply leave them off the list -- or put in a comment about "develop" mode pacakges installed.

**Comment by HugoTian** [comment]
@ChrisBarker-NOAA 

I double checked the online documentation, and please refer to [here](http://conda.pydata.org/docs/using/envs.html#build-identical-conda-environments-with-urls)

you can try conda list --explicit > xxxx.txt to save environment, and conda create -n env_name --file xxxx.txt to recreate that.  Generally conda list -e is not working, we may bring it back in the future

**Comment by ChrisBarker-NOAA** [comment]
`conda list --explicit`  solves a different problem -- in develop mode, there is no conda package at that url.

The channel:: should solve the "where did this come from" problem (though until that's working, maybe explicit is good for now.

thanks,

-CHB

**Comment by HugoTian** [comment]
please refer to PR #3286, and let;s move the discussion there.

Feel free to reopen this and @ me
