### ISSUE TITLE
Ipython-qtconsole not running :(

### ISSUE THREAD

**Issue by Asnelchristian** [conda/conda#3261]
This is my error log 

```
Traceback (most recent call last):
  File "/home/asnel_ulrich/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/cli/main_run.py", line 81, in execute
    for pkg in get_package_versions(args.package, args.offline):
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/api.py", line 168, in get_package_versions
    index = get_index(offline=offline)
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/futures-3.0.5-py3.5.egg/concurrent/futures/_base.py", line 606, in __exit__
    self.shutdown(wait=True)
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/futures-3.0.5-py3.5.egg/concurrent/futures/thread.py", line 133, in shutdown
    t.join(sys.maxint)
AttributeError: module 'sys' has no attribute 'maxint'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/asnel_ulrich/anaconda3/lib/python3.5/site-packages/futures-3.0.5-py3.5.egg/concurrent/futures/thread.py", line 39, in _python_exit
    t.join(sys.maxint)
AttributeError: module 'sys' has no attribute 'maxint'
```

**Comment by tyler-thetyrant** [comment]
Closing outdated.
