### ISSUE TITLE
error on revision

### ISSUE THREAD

**Issue by Stef-aap** [conda/conda#3293]
C:\Anaconda3>conda install --revision 4
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
.
Package plan for installation in environment C:\Anaconda3:

The following packages will be downloaded:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_fun
c
    exit_code = args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 78, in e
xecute
    install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 394, in insta
ll
    display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 73, in display_actio
ns
    info = index[dist + '.tar.bz2']
KeyError: 'conda-forge::conda-env-2.5.2-py35_0.tar.bz2'

**Comment by HugoTian** [comment]
Please refer to PR #3181.

Now we will just raise exception about the error in Conda4.2 (conda install -c conda-canary conda=4.2.1 ). In later version,  we will have better fix, give info about save revision

Thanks
