### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'python=34'

### ISSUE THREAD

**Issue by ssbarnea** [conda/conda#3310]
```
00:00:06.880 conda create -y --prefix /j/jobs/acmetech/jobs/platform/branches/develop/workspace/.tox/py34-conda-linux/ python=3.4 pip
00:00:07.681 Fetching package metadata .......
00:00:07.681 Solving package specifications: ..........
00:00:07.681 An unexpected error has occurred, please consider sending the
00:00:07.681 following traceback to the conda GitHub issue tracker at:
00:00:07.681 
00:00:07.681     https://github.com/conda/conda/issues
00:00:07.681 
00:00:07.681 Include the output of the command 'conda info' in your report.
00:00:07.681 
00:00:07.681 
00:00:07.681 Traceback (most recent call last):
00:00:07.682   File "/j/anaconda3/bin/conda", line 6, in <module>
00:00:07.682     sys.exit(main())
00:00:07.682   File "/j/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
00:00:07.682     exit_code = args_func(args, p)
00:00:07.682   File "/j/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
00:00:07.682     exit_code = args.func(args, p)
00:00:07.682   File "/j/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
00:00:07.682     install(args, parser, 'create')
00:00:07.682   File "/j/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 315, in install
00:00:07.682     update_deps=args.update_deps)
00:00:07.682   File "/j/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 494, in install_actions
00:00:07.682     force=force, always_copy=always_copy)
00:00:07.682   File "/j/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 300, in ensure_linked_actions
00:00:07.683     fetched_in = is_fetched(dist)
00:00:07.683   File "/j/anaconda3/lib/python3.5/site-packages/conda/install.py", line 785, in is_fetched
00:00:07.683     for fn in package_cache().get(dist, {}).get('files', ()):
00:00:07.683   File "/j/anaconda3/lib/python3.5/site-packages/conda/install.py", line 733, in package_cache
00:00:07.683     add_cached_package(pdir, url)
00:00:07.683   File "/j/anaconda3/lib/python3.5/site-packages/conda/install.py", line 692, in add_cached_package
00:00:07.683     _, schannel = url_channel(url)
00:00:07.683   File "/j/anaconda3/lib/python3.5/site-packages/conda/config.py", line 361, in url_channel
00:00:07.683     schannel = canonical_channel_name(channel)
00:00:07.683   File "/j/anaconda3/lib/python3.5/site-packages/conda/config.py", line 337, in canonical_channel_name
00:00:07.683     elif any(channel.startswith(i) for i in get_local_urls(clear_cache=False)):
00:00:07.683   File "/j/anaconda3/lib/python3.5/site-packages/conda/config.py", line 181, in get_local_urls
00:00:07.684     from conda_build.config import croot
00:00:07.684   File "/j/anaconda3/lib/python3.5/site-packages/conda_build/config.py", line 19, in <module>
00:00:07.684     class Config(object):
00:00:07.684   File "/j/anaconda3/lib/python3.5/site-packages/conda_build/config.py", line 27, in Config
00:00:07.684     '')).replace('.', ''))
00:00:07.684 ValueError: invalid literal for int() with base 10: 'python=34'
00:00:07.934 Makefile:51: recipe for target 'info' failed
00:00:07.934 make: *** [info] Error 1
```
And the cond info:
```
conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.11+0.g5b44ab3.dirty
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /j/anaconda3  (writable)
  default environment : /j/anaconda3
     envs directories : /j/anaconda3/envs
        package cache : /j/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /j/.condarc
         offline mode : False
    is foreign system : False
```

**Comment by ssbarnea** [comment]
I discovered that what was causing this issue was the fact that I had an environment variable named `CONDA_PY` that I was using. Its value was `python=3.4`. 

I even tried to make it empty but the creation of the environment would still fail and I ended up renaming it.

**Comment by kalefranz** [comment]
Yeah that's an environment variable that conda-build uses
