### ISSUE TITLE
Anaconda won't instal notebook app form Launcher in XP

### ISSUE THREAD

**Issue by kturkalj** [conda/conda#3313]
**Anaconda3-2.2.0-Windows-x86.exe won't install notebook app on Windows XP from Launcher:**
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 207, in args_func
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 46, in execute
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 502, in execute_actions
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 140, in execute_instructions
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 88, in UNLINK_CMD
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 601, in unlink
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 304, in mk_menus
  File "C:\Anaconda3\lib\site-packages\menuinst__init__.py", line 23, in 
    from .win32 import Menu, ShortCut, dirs
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 13, in 
    from .knownfolders import get_folder_path, FOLDERID
  File "C:\Anaconda3\lib\site-packages\menuinst\knownfolders.py", line 152, in 
    _SHGetKnownFolderPath = windll.shell32.SHGetKnownFolderPath     # [5] [3]
  File "C:\Anaconda3\lib\ctypes__init__.py", line 364, in **getattr**
    func = self.**getitem**(name)
  File "C:\Anaconda3\lib\ctypes__init__.py", line 369, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SHGetKnownFolderPath' not found

**How can it be done form cmd prompt?**
Thnx

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/menuinst#44
