### ISSUE TITLE
MEME Failed to Install

### ISSUE THREAD

**Issue by c-guzman** [conda/conda#3318]
```
Traceback (most recent call last):
  File "/usr/local/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/usr/local/anaconda2/lib/python2.7/site-packages/conda/install.py", line 1060, in link
    os.makedirs(dst_dir)
  File "/usr/local/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/anaconda2/lib/perl5/site_perl/5.22.0/Digest'

```

```
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.5
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /usr/local/anaconda2  (writable)
  default environment : /usr/local/anaconda2
     envs directories : /usr/local/anaconda2/envs
        package cache : /usr/local/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/r/linux-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/carlos/.condarc
         offline mode : False
    is foreign system : False

```

Trying to install a program through `conda install -c bioconda meme`

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed with transactions in 4.3 is conda removing itself during a failed install/update operation.
