### ISSUE TITLE
conda install error from local

### ISSUE THREAD

**Issue by mjkrause** [conda/conda#3321]
command and error/traceback:

```
mkrause@odin:~/build_test$ conda install pyspatialite-3.0.1-alpha-0.tar.bz2
Using Anaconda Cloud api site https://api.anaconda.org
Fetching packages ...
pyspatialite-3 100% |#########################################| Time: 0:00:00  86.18 MB/s
Extracting packages ...
[      COMPLETE      ]|############################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                      |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/mkrause/anaconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 203, in install
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 140, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/home/mkrause/anaconda2/lib/python2.7/site-packages/conda/install.py", line 1041, in link
assert source_dir is not None
AssertionError
```

output of conda info:

```
`Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 1.21.11+0.g5b44ab3.dirty
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /home/mkrause/anaconda2  (writable)
  default environment : /home/mkrause/anaconda2
     envs directories : /home/mkrause/anaconda2/envs
        package cache : /home/mkrause/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
`
```

**Comment by HugoTian** [comment]
Basically, conda think you did not extract the tar file in the package cache 

Can you find pyspatialite-3.0.1-alpha-0.tar.bz2 and pyspatialite-3.0.1-alpha-0 folder in your /home/mkrause/anaconda2/pkgs ?

Thanks

**Comment by mjkrause** [comment]
Hi Tian,

Thanks for taking care of this. I found a solution that works for in the 
meantime, would still be nice to be able to build it with conda, and 
make a package of it. One package of pyspatialite exists but it doesn't 
work for me and several team members.

Here's the answer to your question:

**Comment by HugoTian** [comment]
We will make a better package in future, and feel free to reopen this issue
