### ISSUE TITLE
Unexpected error when creating environment

### ISSUE THREAD

**Issue by NicolaiMikal** [conda/conda#3329]
Hi

I attempted to create a new environment with python version 3.4 and an unexpected error occured.

Conda encouraged me to include in the traceback, so here it is.
`
Traceback (most recent call last):
  File "C:\Users\nsatr\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "C:\Users\nsatr\Anaconda3\lib\site-packages\conda\install.py", line 1061, in link
    if os.path.exists(dst):
  File "C:\Users\nsatr\Anaconda3\lib\genericpath.py", line 19, in exists
    os.stat(path)
ValueError: stat: embedded null character`

Conda works fine otherwise, so the problem seems to be related to python 3.4 in my case.

Thanks

**Comment by kalefranz** [comment]
Can you reproduce this error with more recent versions of conda?  Latest is conda 4.3.17.  If so, can you please include the updated stack trace, along with detailed steps on how I can reproduce your problem myself?
