### ISSUE TITLE
Error occured while installing r

### ISSUE THREAD

**Issue by erankesh** [conda/conda#3334]
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 127, in args_func
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 566, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 137, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 60, in EXTRACT_CMD
    extract(arg)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 821, in extract
    os.rename(temp_path, path)
WindowsError: [Error 5] Access is denied

**Comment by HugoTian** [comment]
Please retry. If conda still fails on this Permission Error, please turn off the virus scanner and retry.

Hope it helps

**Comment by erankesh** [comment]
Thanks. It worked when virus scanner is turned off.
