### ISSUE TITLE
conda env remove doesn't work

### ISSUE THREAD

**Issue by durack1** [conda/conda#3338]
I am trying to remove a conda environment, as below and it's not working:

```
((uvcdat-nightly)) bash-3.2$ conda env remove -n uvcdat26
Fetching package metadata .......
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/durack1/anaconda2/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/durack1/anaconda2/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'
```
the version of conda:
```
((uvcdat-nightly)) bash-3.2$ conda info
Current conda install:

             platform : osx-64
        conda version : 4.1.0
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/durack1/anaconda2  (writable)
  default environment : /Users/durack1/anaconda2/envs/uvcdat-nightly
     envs directories : /Users/durack1/anaconda2/envs
        package cache : /Users/durack1/anaconda2/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/durack1/.condarc
    is foreign system : False
```

**Comment by HugoTian** [comment]
conda env is broken for 4.1, and you can remove environment using 
    
    conda remove -n env_name --all

Moreover, please update conda using following command:

    conda install -c conda-canary conda=4.2.3

**Comment by durack1** [comment]
@HugoTian yep upgrading sorts out my problem, so closing this issue
