### ISSUE TITLE
TypeError: install_actions() got an unexpected keyword argument 'prune'

### ISSUE THREAD

**Issue by ebaltz2** [conda/conda#3339]
Traceback (most recent call last):
  File "/Users/ebaltz/miniconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/ebaltz/miniconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/ebaltz/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/ebaltz/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 100, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/Users/ebaltz/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 16, in install
    actions = plan.install_actions(prefix, index, specs, prune=prune)
TypeError: install_actions() got an unexpected keyword argument 'prune'
gremellab02:~ ebaltz$ conda info
Current conda install:

```
         platform : osx-64
    conda version : 3.19.3
```

  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /Users/ebaltz/miniconda3  (writable)
  default environment : /Users/ebaltz/miniconda3
     envs directories : /Users/ebaltz/miniconda3/envs
        package cache : /Users/ebaltz/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by HugoTian** [comment]
Could you please update conda using "conda update conda" or using miniconda installer
