### ISSUE TITLE
condo update anaconda error

### ISSUE THREAD

**Issue by jgubern** [conda/conda#3345]
Warning: could not import binstar_client ('args' object has no attribute 'token')Current conda install:

```
         platform : osx-64
    conda version : 4.1.11
conda-env version : 2.5.2
```

  conda-build version : 1.3.3
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /opt/anaconda  (writable)
  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

~[8]% 

Other output:

[      COMPLETE      ]|###################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the             |  72%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 1060, in link
    os.makedirs(dst_dir)
  File "/opt/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/anaconda/lib/python2.7/site-packages/traitlets/utils/tests'

**Comment by tyler-thetyrant** [comment]
Closing outdated.
