### ISSUE TITLE
cannot install seaborn

### ISSUE THREAD

**Issue by emarti3** [conda/conda#3347]
Current conda install:

             platform : win-64
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2  (writable)
  default environment : C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2
     envs directories : C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\envs
        package cache : C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 852, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\Steve Martinez\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 236, in exp_backoff_fn
    result = fn(*args)
WindowsError: [Error 5] Access is denied

**Comment by HugoTian** [comment]
Please retry. If still fails, please disable virus scanner and retry.

**Comment by emarti3** [comment]
HugoTian, thanks!!! Turned off the firewall protection temporarily and it worked!
