### ISSUE TITLE
libxml2 library issue on osx

### ISSUE THREAD

**Issue by rabernat** [conda/conda#3355]
I am trying to run [nikola](https://getnikola.com/) on osx. Rather than creating a virtualenv as recommended, I am trying to create a conda environment. I have hit some dependency issues that have me stuck.

You can see my environment.yml here:
https://gist.github.com/rabernat/37db7f98c9903fe9664a2a390a06c9e1
(Note I have tried with and without the conda-forge channel.)

Within this environment, when I try to run nikola, I get the following error:

``` bash
$ nikola
Traceback (most recent call last):
  File "/Users/rpa/anaconda/envs/nikola/bin/nikola", line 7, in <module>
    from nikola.__main__ import main
  File "/Users/rpa/anaconda/envs/nikola/lib/python3.5/site-packages/nikola/__init__.py", line 35, in <module>
    from .nikola import Nikola  # NOQA
  File "/Users/rpa/anaconda/envs/nikola/lib/python3.5/site-packages/nikola/nikola.py", line 54, in <module>
    import lxml.etree
ImportError: dlopen(/Users/rpa/anaconda/envs/nikola/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so, 2): Library not loaded: libxml2.2.dylib
  Referenced from: /Users/rpa/anaconda/envs/nikola/lib/python3.5/site-packages/lxml/etree.cpython-35m-darwin.so
  Reason: Incompatible library version: etree.cpython-35m-darwin.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

It seems to be a libxml2 issue, as described here:
http://stackoverflow.com/questions/23172384/lxml-runtime-error-reason-incompatible-library-version-etree-so-requires-vers

Curiously, I can overcome this issue by setting

``` bash
DYLD_LIBRARY_PATH=/Users/rpa/anaconda/envs/nikola/lib
```

However, it is my understanding that this should not be necessary.

Any recommendations for how to move forward?

**Comment by resuscv** [comment]
Curiously, this is still a problem.  :-(

Did you ever find a fix?

**Comment by mingwandroid** [comment]
I cannot reproduce this so I need more details. Please do the following:

Ensure that you are not running any python executables. `ps aux` and `killall python` may help here.

Create a temporary installation of the latest Miniconda3.

```
pushd /tmp
curl -SLO https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
bash ./Miniconda3-latest-MacOSX-x86_64.sh -b -p /tmp/lxml
source /tmp/lxml/bin/activate
conda create -n py35 python=3.5 lxml
source activate py35
python
```

.. then from inside the python interpreter, please run:
```
import lxml.etree
```

.. then from another Terminal window, please enter:
```
lsof -p $(ps aux | grep python | sort | head -1 | tr -s " " | cut -f2 -d' ') | grep "\.so\|.dylib" | tr -s " " | cut -f9 -d' ' | sort | xargs md5 | sed -E 's|(MD5 \()([0-9a-zA-Z/.+\_-]*)\) = ([0-9a-f]*)|\3 \2|g' | sort
```

.. and finally, please paste the results.

**Comment by mingwandroid** [comment]
My result is:

```
08d29ff350a5344914fa9207b9d14e87 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/_struct.cpython-35m-darwin.so
2bb38c812d70a1e5a6c59fb88b2c80a7 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/_opcode.cpython-35m-darwin.so
38f7fc1ddfdf015954aa2b8720a1c9a0 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/readline.cpython-35m-darwin.so
4605b7ef41ba301a82f889f1d815018d /private/tmp/lxml/envs/py35/lib/libiconv.2.dylib
74441d2e2686e936afcef19f137b5df5 /private/tmp/lxml/envs/py35/lib/python3.5/site-packages/lxml/etree.so
853375bcc5de78e7364d6365ac6726c8 /private/tmp/lxml/envs/py35/lib/libxslt.1.dylib
86b765657140a030d80e8329ae6145cb /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/_heapq.cpython-35m-darwin.so
92ff2c1f96175cf222df8197f225a94a /private/tmp/lxml/envs/py35/lib/libxml2.2.dylib
ce489c7fdf25c5216edc33551f7acd23 /private/tmp/lxml/envs/py35/lib/libpython3.5m.dylib
dcfc8bb9b615176679aa9097f5b8acb5 /private/tmp/lxml/envs/py35/lib/libreadline.6.2.dylib
e933057789e60406502f57c28ba7dcb8 /private/tmp/lxml/envs/py35/lib/libz.1.2.8.dylib
fc5d83de757db713220de7e0a557d199 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/zlib.cpython-35m-darwin.so
ff41c26040ea6a4ca706959d241a419f /private/tmp/lxml/envs/py35/lib/libexslt.0.dylib
```

**Comment by rabernat** [comment]
No. I gave up on nikola because of this.

**Comment by rabernat** [comment]
I personally did not find a fix and had to give up on using nikola...but it looks like @mingwandroid is willing to helping debug! Good luck!

**Comment by resuscv** [comment]
@mingwandroid - thanks for helping out.  Here's my dump...

08d29ff350a5344914fa9207b9d14e87 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/_struct.cpython-35m-darwin.so
2bb38c812d70a1e5a6c59fb88b2c80a7 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/_opcode.cpython-35m-darwin.so
38f7fc1ddfdf015954aa2b8720a1c9a0 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/readline.cpython-35m-darwin.so
4605b7ef41ba301a82f889f1d815018d /private/tmp/lxml/envs/py35/lib/libiconv.2.dylib
74441d2e2686e936afcef19f137b5df5 /private/tmp/lxml/envs/py35/lib/python3.5/site-packages/lxml/etree.so
853375bcc5de78e7364d6365ac6726c8 /private/tmp/lxml/envs/py35/lib/libxslt.1.dylib
86b765657140a030d80e8329ae6145cb /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/_heapq.cpython-35m-darwin.so
92ff2c1f96175cf222df8197f225a94a /private/tmp/lxml/envs/py35/lib/libxml2.2.dylib
ce489c7fdf25c5216edc33551f7acd23 /private/tmp/lxml/envs/py35/lib/libpython3.5m.dylib
dcfc8bb9b615176679aa9097f5b8acb5 /private/tmp/lxml/envs/py35/lib/libreadline.6.2.dylib
e933057789e60406502f57c28ba7dcb8 /private/tmp/lxml/envs/py35/lib/libz.1.2.8.dylib
fc5d83de757db713220de7e0a557d199 /private/tmp/lxml/envs/py35/lib/python3.5/lib-dynload/zlib.cpython-35m-darwin.so
ff41c26040ea6a4ca706959d241a419f /private/tmp/lxml/envs/py35/lib/libexslt.0.dylib

**Comment by resuscv** [comment]
@rabernat - Thanks for sharing.  
<channel Trump>
Sorry you couldn't get it to work.  SAD.
</channel>

**Comment by resuscv** [comment]
When I install Nikola (`pip install "Nikola[extras]"`) in this new (see above) install of conda.  It _all just works_.

So what is different?

I've included a diff between the two installs py3k (the one that fails) and py35 (works).

I'm now confused as to whether it is
1. Older install of conda, or
2. Python 3.6
3. A confused install of lxml (Nikola extras seems to install it as well as conda in py3.6)

Will dig some more when I get a chance.

```
# packages in environment at /tmp/py3k:			      |	# packages in environment at /tmp/lxml/envs/py35:
#								#
appnope                   0.1.0                     <pip>	appnope                   0.1.0                     <pip>
argh                      0.26.2                    <pip>	argh                      0.26.2                    <pip>
bleach                    1.5.0                     <pip>	bleach                    1.5.0                     <pip>
blinker                   1.4                       <pip>	blinker                   1.4                       <pip>
cloudpickle               0.2.2                     <pip>	cloudpickle               0.2.2                     <pip>
decorator                 4.0.11                    <pip>	decorator                 4.0.11                    <pip>
docutils                  0.13.1                    <pip>	docutils                  0.13.1                    <pip>
doit                      0.30.3                    <pip>	doit                      0.30.3                    <pip>
entrypoints               0.2.2                     <pip>	entrypoints               0.2.2                     <pip>
ghp-import2               1.0.1                     <pip>	ghp-import2               1.0.1                     <pip>
html5lib                  0.9999999                 <pip>	html5lib                  0.9999999                 <pip>
husl                      4.0.3                     <pip>	husl                      4.0.3                     <pip>
ipykernel                 4.5.2                     <pip>	ipykernel                 4.5.2                     <pip>
ipython                   5.3.0                     <pip>	ipython                   5.3.0                     <pip>
ipython-genutils          0.1.0                     <pip>	ipython-genutils          0.1.0                     <pip>
Jinja2                    2.9.5                     <pip>	Jinja2                    2.9.5                     <pip>
jsonschema                2.6.0                     <pip>	jsonschema                2.6.0                     <pip>
jupyter-client            5.0.0                     <pip>	jupyter-client            5.0.0                     <pip>
jupyter-core              4.3.0                     <pip>	jupyter-core              4.3.0                     <pip>
							      >	libiconv                  1.14                          0  
							      >	libxml2                   2.9.4                         0  
							      >	libxslt                   1.1.29                        0  
Logbook                   1.0.0                     <pip>	Logbook                   1.0.0                     <pip>
lxml                      3.7.3                     <pip>     |	lxml                      3.7.3                    py35_0  
lxml                      3.7.3                    py36_0     <
MacFSEvents               0.7                       <pip>	MacFSEvents               0.7                       <pip>
Mako                      1.0.6                     <pip>	Mako                      1.0.6                     <pip>
Markdown                  2.6.8                     <pip>	Markdown                  2.6.8                     <pip>
MarkupSafe                0.23                      <pip>     |	MarkupSafe                1.0                       <pip>
micawber                  0.3.3                     <pip>	micawber                  0.3.3                     <pip>
mistune                   0.7.3                     <pip>	mistune                   0.7.3                     <pip>
natsort                   5.0.2                     <pip>	natsort                   5.0.2                     <pip>
nbconvert                 5.1.1                     <pip>	nbconvert                 5.1.1                     <pip>
nbformat                  4.3.0                     <pip>	nbformat                  4.3.0                     <pip>
Nikola                    7.8.3                     <pip>	Nikola                    7.8.3                     <pip>
notebook                  4.4.1                     <pip>	notebook                  4.4.1                     <pip>
olefile                   0.44                      <pip>	olefile                   0.44                      <pip>
openssl                   1.0.2k                        1  	openssl                   1.0.2k                        1  
pandocfilters             1.4.1                     <pip>	pandocfilters             1.4.1                     <pip>
pathtools                 0.1.2                     <pip>	pathtools                 0.1.2                     <pip>
pexpect                   4.2.1                     <pip>	pexpect                   4.2.1                     <pip>
phpserialize              1.3                       <pip>	phpserialize              1.3                       <pip>
pickleshare               0.7.4                     <pip>	pickleshare               0.7.4                     <pip>
piexif                    1.0.12                    <pip>	piexif                    1.0.12                    <pip>
Pillow                    4.0.0                     <pip>	Pillow                    4.0.0                     <pip>
pip                       9.0.1                    py36_1     |	pip                       9.0.1                    py35_1  
prompt-toolkit            1.0.13                    <pip>	prompt-toolkit            1.0.13                    <pip>
ptyprocess                0.5.1                     <pip>	ptyprocess                0.5.1                     <pip>
pygal                     2.3.1                     <pip>	pygal                     2.3.1                     <pip>
Pygments                  2.2.0                     <pip>	Pygments                  2.2.0                     <pip>
Pyphen                    0.9.4                     <pip>	Pyphen                    0.9.4                     <pip>
PyRSS2Gen                 1.1                       <pip>	PyRSS2Gen                 1.1                       <pip>
python                    3.6.0                         0     |	python                    3.5.3                         1  
python-dateutil           2.6.0                     <pip>	python-dateutil           2.6.0                     <pip>
PyYAML                    3.12                      <pip>	PyYAML                    3.12                      <pip>
pyzmq                     16.0.2                    <pip>	pyzmq                     16.0.2                    <pip>
readline                  6.2                           2  	readline                  6.2                           2  
requests                  2.13.0                    <pip>	requests                  2.13.0                    <pip>
setuptools                27.2.0                   py36_0     |	setuptools                27.2.0                   py35_0  
simplegeneric             0.8.1                     <pip>	simplegeneric             0.8.1                     <pip>
six                       1.10.0                    <pip>	six                       1.10.0                    <pip>
smartypants               2.0.0                     <pip>	smartypants               2.0.0                     <pip>
sqlite                    3.13.0                        0  	sqlite                    3.13.0                        0  
terminado                 0.6                       <pip>	terminado                 0.6                       <pip>
testpath                  0.3                       <pip>	testpath                  0.3                       <pip>
tk                        8.5.18                        0  	tk                        8.5.18                        0  
tornado                   4.4.2                     <pip>	tornado                   4.4.2                     <pip>
traitlets                 4.3.2                     <pip>	traitlets                 4.3.2                     <pip>
typogrify                 2.0.7                     <pip>	typogrify                 2.0.7                     <pip>
Unidecode                 0.04.20                   <pip>	Unidecode                 0.04.20                   <pip>
watchdog                  0.8.3                     <pip>	watchdog                  0.8.3                     <pip>
wcwidth                   0.1.7                     <pip>	wcwidth                   0.1.7                     <pip>
webassets                 0.12.1                    <pip>	webassets                 0.12.1                    <pip>
wheel                     0.29.0                   py36_0     |	wheel                     0.29.0                   py35_0  
ws4py                     0.3.5                     <pip>	ws4py                     0.3.5                     <pip>
xz                        5.2.2                         1  	xz                        5.2.2                         1  
Yapsy                     1.11.223                  <pip>	Yapsy                     1.11.223                  <pip>
zlib                      1.2.8                         3  	zlib                      1.2.8                         3  
```

**Comment by resuscv** [comment]
Definitely something to do with an older version of conda...

I did a py3.5 install with my default installation and I still get the same error.  Also there are different packages installed from the latest miniconda install (see diff below).

I don't know how to tell if my conda is "outdated" as ```conda search --outdated``` only shows the different versions of python I have installed.


```
#  > == Latest conda
#  < == Previous conda  (4.1.5)
> libiconv                  1.14                          0
> libxml2                   2.9.4                         0
> libxslt                   1.1.29                        0
23c26
< lxml                      3.7.3                     <pip>
---
> lxml                      3.7.3                    py35_0
```

**Comment by mingwandroid** [comment]
Can you update your /tmp/lxml/envs/py35 to a py36 env (or create a new one?), verify that it still works, then, in *each* of this new py36 installation and your old broken installation, run my md5 / shared library test, pasting the results here please?

**Comment by resuscv** [comment]
I gave up and deleted my old conda install.  Sorry.

What I did find however, is that the issue did re-appear with a new install - so I had my testing `/tmp/lxml` install (from above) and then one in my desired location `~/conda`.

The way I squashed the issue was to remove my `pip` cache:
``` shell
rm -rf ~/Library/Caches/pip   # For braindead macOS
```
I don't think that pip+caching and conda are playing properly together.

**Comment by mingwandroid** [comment]
Hmm, I would still like to have seen the list from the new broken install, but I'm glad you are up and running now.

I don't really know what pip does with that folder on macOS, any ideas? I would hope it would just cache files to prevent re-downloading them?

**Comment by resuscv** [comment]
Yeah, sorry.  Work machine == Time constraints.

Re: pip - It *should* just be the cache as you said.  I'm not sure if I already had, say, lxml in the cache, compiled against a previous set of libs...

`<off-tangent>`
macOS is... _difficult_ ...to get everything working together.  The macOS versions of command line tools/libraries are usually horrifically outdated (python is 2.7.10 from 2015-05-23 for example, or gcc being 4.2.1 c.f. 6.3!), homebrew does it's best, but some libraries would clash, so they're not installed in the standard path, etc., etc., etc.
`</off-tangent>`

So I could imagine a cached object could get seriously confused depending on environment settings...

**Comment by mingwandroid** [comment]
Conda aims at near complete isolation from the system apart from a few core shared system libraries. This is true (to different extents) across all OSes and something we work hard to ensure.

**Comment by resuscv** [comment]
That's why it's my go-to tool for python/R dev work.  😄 👍 

I've even moved to using it in Docker.  Using a version of the container below... It's poorly documented, but put my deps in a text file and then know it builds properly every time.  Woo hoo!

https://hub.docker.com/r/v4tech/dev-python-onbuild/

i.e. they used the above to build a pandas dev-box:
https://github.com/v4tech/docker-machines/tree/master/53-dev-python-pandas

**Comment by florenthemmi** [comment]
I have the latest version of Conda (4.3.8).
Same issue here when trying to install scrapy in a virtualenv.
```
ImportError: dlopen(/Users/florent/.virtualenvs/ip-address-blocks/lib/python3.6/site-packages/lxml/etree.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libxml2.2.dylib
  Referenced from: /Users/florent/.virtualenvs/ip-address-blocks/lib/python3.6/site-packages/lxml/etree.cpython-36m-darwin.so
  Reason: Incompatible library version: etree.cpython-36m-darwin.so requires version 12.0.0 or later, but libxml2.2.dylib provides version 10.0.0
```

I have commented the `export PATH="//anaconda/bin:$PATH"` in my `bash_profile`.
Looks like:
```
# added by Anaconda3 4.3.0 installer
# export PATH="//anaconda/bin:$PATH"
```
Then I restart my shell, follow @resuscv recommandation (https://github.com/conda/conda/issues/3355#issuecomment-284907731) and it's working.

```
rm -rf ~/Library/Caches/pip
pip install scrapy
```

Hope it helps!
