### ISSUE TITLE
Extension error when removing env

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#3366]
Upon removing a virtual environment I had installed via `conda env remove`, an error was returned at the end of the process that looks like it was related to a notebook extension. 

```
Traceback (most recent call last):
  File "/Users/fonnescj/anaconda3/envs/workshop/bin/jupyter-nbextensions_configurator", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/Users/fonnescj/anaconda3/envs/workshop/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2953, in <module>
    @_call_aside
  File "/Users/fonnescj/anaconda3/envs/workshop/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2939, in _call_aside
    f(*args, **kwargs)
  File "/Users/fonnescj/anaconda3/envs/workshop/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2966, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/fonnescj/anaconda3/envs/workshop/lib/python3.5/site-packages/pkg_resources/__init__.py", line 635, in _build_master
    ws.require(__requires__)
  File "/Users/fonnescj/anaconda3/envs/workshop/lib/python3.5/site-packages/pkg_resources/__init__.py", line 943, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/fonnescj/anaconda3/envs/workshop/lib/python3.5/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'jupyter_core' distribution was not found and is required by jupyter-nbextensions-configurator, notebook
```

I confirmed that the env was in fact removed, so the removal process was apparently successful, but was not sure what the error was for.

Running conda 4.1.11 and Jupyter 4.1.0 on OS X and Python 3.5.

**Comment by kalefranz** [comment]
I don't know what the error is for either.  Probably something with jupyter unregistering extensions.  They still haven't worked their extension configuration out to play nice with package managers preferring flat configuration files in `.d` directories instead of using callback hooks for post-install scripts.
