### ISSUE TITLE
Error while trying to install qiime using miniconda

### ISSUE THREAD

**Issue by Shlomsauce** [conda/conda#3380]
Hello,
I'm getting an unexpected error while trying to install qiime using miniconda.

> conda create -n qiime2 qiime matplotlib=1.4.3 mock nose -c bioconda

Traceback (most recent call last):
  File "/home/greenbot/miniconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/install.py", line 859, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "/home/greenbot/miniconda3/lib/python3.5/site-packages/conda/install.py", line 237, in exp_backoff_fn
    return fn(*args)
PermissionError: [Errno 13] Permission denied: '/home/greenbot/.conda/envs/.pkgs/qcli-0.1.1-py27_0.tmp' -> '/home/greenbot/.conda/envs/.pkgs/qcli-0.1.1-py27_0'

> conda info

Current conda install:
platform : linux-64
conda version : 4.1.11
conda-env version : 2.5.2
conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/greenbot/miniconda3  (read only)
  default environment : /home/greenbot/miniconda3
     envs directories : /home/greenbot/.conda/envs
                        /home/greenbot/envs
                        /home/greenbot/miniconda3/envs
        package cache : /home/greenbot/.conda/envs/.pkgs
                        /home/greenbot/envs/.pkgs
                        /home/greenbot/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

Please help, thanks.

Shlomi.

**Comment by kalefranz** [comment]
Permissions issues have been mostly fixed as of conda 4.3.  If you're running conda 4.3 or later and are still having problems, please file a new issue with a new stack trace.
