### ISSUE TITLE
conda update conda failed with: UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 57460: character maps to <undefined>

### ISSUE THREAD

**Issue by iandaniels** [conda/conda#3385]
Conda update conda failed. As requested by the code, I'm reporting this issue:

```
C:\>conda update conda
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 149, in install
    linked = install_linked(prefix)
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 966, in linked
    return set(linked_data(prefix).keys())
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 959, in linked_data
    load_linked_data(prefix, fn[:-5])
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 886, in load_linked_data
    rec = json.load(fi)
  File "C:\Miniconda3\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
  File "C:\Miniconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 57460: character maps to <undefined>

C:\>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.11
    conda-env version : not installed
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.11.1
     root environment : C:\Miniconda3  (writable)
  default environment : C:\Miniconda3
     envs directories : C:\Miniconda3\envs
        package cache : C:\Miniconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by kalefranz** [comment]
In your install you have a file in `C:\Miniconda3\conda-meta` that's causing an encoding issue.  Probably some problematic unicode character in one of those files.  Unfortunately the output here doesn't help isolate which it is.  I believe we've fixed this in recent versions of conda.  Latest is 4.3.17.  Honestly easiest thing to do here is to just start with a new miniconda install.
