### ISSUE TITLE
Cannot install pystan - missing files

### ISSUE THREAD

**Issue by bkozzy** [conda/conda#3401]
Here is the traceback and conda info.
Thanks for help!
Bartek

(C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2) C:\Users\bartek.kozakowski>conda install -c patricksnape pystan=2.7.0.0
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2:

The following NEW packages will be INSTALLED:

```
pystan: 2.7.0.0-np19py27_0 patricksnape
```

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 857, in extract
    t.extractall(path=temp_path)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2192, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2232, in makefile
    with bltn_open(targetpath, "wb") as target:
IOError: [Errno 2] No such file or directory: 'C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\pkgs\pystan-2.7.0.0-np19py27_0.tmp\Lib\site-packages\pystan\math\
\doc\api\html\classstan_1_1math_1_1seq__view_3_01_t_00_01_eigen_1_1_matrix_3_01_s_00_011_00_01_eigen_1_1_dynamic_01_4_01_4-members.html'

(C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2) C:\Users\bartek.kozakowski>conda info
Current conda install:

```
         platform : win-64
    conda version : 4.1.11
conda-env version : 2.5.2
```

  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2  (writable)
  default environment : C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2
     envs directories : C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\envs
        package cache : C:\Users\bartek.kozakowski\AppData\Local\Continuum\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
Looks like a broken conda package.  Conda 4.3 will tell you exactly what the problem is there.
