### ISSUE TITLE
unexpected error has occured while install matplotlib

### ISSUE THREAD

**Issue by amjoker** [conda/conda#3402]
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main

  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_f
c

  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in
xecute

  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 148, in ins
ll

  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 961, in linked

  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 954, in linked_
ta

  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 881, in load_li
ed_data

  File "C:\Anaconda2\lib\json__init__.py", line 291, in load
    **kw)
  File "C:\Anaconda2\lib\json__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda2\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 651 column 28 (char 40310)

C:\Users\wxz>conda info
Current conda install:

```
         platform : win-64
    conda version : 4.1.6
conda-env version : not installed
```

  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by parnus01** [comment]
update pip

**Comment by kalefranz** [comment]
Are you still having this problem with more recent versions of conda?  Latest is conda 4.3.
