### ISSUE TITLE
Conda clone fails with mkl error...

### ISSUE THREAD

**Issue by fperez** [conda/conda#3434]
I need to clone my conda root env, and tried simply `conda create --name test --clone root`, but it failed with:

```
denali[~]> conda create --name test --clone root
Source:      '/Users/fperez/usr/conda'
Destination: '/Users/fperez/usr/conda/envs/test'
The following packages cannot be cloned out of the root environment:
 - conda::conda-4.1.0rc3-py35_0
Packages: 229
Files: 937
Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/fperez/usr/conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    args_func(args, p)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/cli/install.py", line 215, in install
    'unknown': args.unknown})
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/cli/install.py", line 84, in clone
    fetch_args=fetch_args)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/misc.py", line 318, in clone_env
    force_extract=False, fetch_args=fetch_args)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/misc.py", line 123, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/plan.py", line 556, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/instructions.py", line 133, in execute_instructions
    cmd(state, arg)
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda/instructions.py", line 46, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
KeyError: 'mkl-11.3.3-0.tar.bz2'
```

This is using conda 4.1.0rc3, which is current... Any suggestions?

**Comment by fperez** [comment]
Sorry, my conda info is here:

```
denali[~]> conda info
Using Anaconda API: https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.1.0rc3
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.11.1
     root environment : /Users/fperez/usr/conda  (writable)
  default environment : /Users/fperez/usr/conda
     envs directories : /Users/fperez/usr/conda/envs
        package cache : /Users/fperez/usr/conda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/conda/osx-64/
                        https://conda.anaconda.org/conda/noarch/
          config file : /Users/fperez/.condarc
    is foreign system : False
```

**Comment by kalefranz** [comment]
Hey Fernando,

4.1.0rc3 is a horribly old version.  If you want to stick with 4.1, I'd recommend updating to 4.1.12.  We also released 4.2 (actually 4.2.6) into defaults yesterday.  I'm hoping this is for sure fixed in 4.2, if not in 4.1.12.

**Comment by fperez** [comment]
Hi Kale,

thanks for your input.  I'm puzzled as to why I have an old version of conda, as I regularly update conda and my entire installation with `conda update --all --yes`.  But I tried specifically to update conda itself just to be safe, and this is what happens:

```
enali[jupytercon]> conda update conda
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
Solving package specifications .............

# All requested packages already installed.
# packages in environment at /Users/fperez/usr/conda:
#
conda                     4.1.0rc3                 py35_0    conda
```

Any thoughts as to why conda itself isn't updating?

**Comment by kalefranz** [comment]
That's weird.  What happens with `conda install conda=4.2.7`?

**Comment by kalefranz** [comment]
Also, try removing the conda channel from your channels list.  That's the source of the 4.1.0rc3 package, but all of those packages have supposedly been disabled on anaconda.org, unless that's messing up somehow...

**Comment by fperez** [comment]
Well, removing the conda channel didn't help:

```
denali[~]> cat .condarc
channels:
  - defaults
denali[~]> conda update conda
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .......
Solving package specifications .............

# All requested packages already installed.
# packages in environment at /Users/fperez/usr/conda:
#
conda                     4.1.0rc3                 py35_0    conda
```

It's possible that specific version of conda has a bug in how it resolves updates, perhaps? If so, that would be kind of problematic: users will think they're updating everything, yet conda itself is now stuck forever at this one version, that just won't update itself.

Fortunately, manually forcing 4.2.7 did work:

```
denali[~]> conda install conda=4.2.7
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .......
Solving package specifications .............

Package plan for installation in environment /Users/fperez/usr/conda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    conda-4.2.7                |           py35_0         374 KB
    ------------------------------------------------------------
                                           Total:         375 KB

The following packages will be UPDATED:

    conda:     4.1.0rc3-py35_0 conda --> 4.2.7-py35_0
    conda-env: 2.5.0rc1-py35_0 conda --> 2.6.0-0     

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |########################################| Time: 0:00:00 422.03 kB/s
conda-4.2.7-py 100% |########################################| Time: 0:00:39   9.66 kB/s
Extracting packages ...
[      COMPLETE      ]|###########################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###########################################################| 100%
Linking packages ...
[      COMPLETE      ]|###########################################################| 100%
```

And now:

```
denali[~]> conda --version
conda 4.2.7
```

With this, my `conda create --name test --clone root` now seems to be proceeding fine.

I think we can then close this issue (I'll do so here), but you may want to look a bit closer at whether that 4.1.0rc3 release may be causing problems in the wild, with potentially others stuck like myself and not even aware of it.

Many thanks for the help!!
