### ISSUE TITLE
After conda update, conda doesn't work

### ISSUE THREAD

**Issue by turalaksel** [conda/conda#3441]
This is what I get after I install anaconda2 on mac and update conda. I can't use conda afterwards.

```
Traceback (most recent call last):
  File "/Users/tural/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 395, in get_info
    from conda.cli import conda_argparse
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 15, in <module>
    from ..install import dist2quad
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/install.py", line 51, in <module>
    from .models.channel import Channel
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 10, in <module>
    from cytoolz.functoolz import excepts
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/cytoolz/__init__.py", line 18, in <module>
    comp = compose
NameError: name 'compose' is not defined
```

**Comment by kalefranz** [comment]
Interesting.  Thanks for the report.

    conda update cytoolz

should fix your problem

**Comment by turalaksel** [comment]
Hi Kale,

After I installed anaconda on my iMac, I wanted to install opencv 3. After I install any package using conda, condo gets broken and I get the following error.

Traceback (most recent call last):
  File "/Users/tural/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 395, in get_info
    from conda.cli import conda_argparse
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 15, in <module>
    from ..install import dist2quad
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/install.py", line 51, in <module>
    from .models.channel import Channel
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 10, in <module>
    from cytoolz.functoolz import excepts
  File "/Users/tural/anaconda2/lib/python2.7/site-packages/cytoolz/__init__.py", line 18, in <module>
    comp = compose
NameError: name 'compose' is not defined


To have a fresh start, I deleted the anaconda directory, I installed Anaconda again. I tried to update cytoolz, but I already had the updated version. As a test, I wanted to install numba. During installation, conda and anaconda are updated. Again I got the same error messages as above.

anaconda:    4.1.1-np111py27_0 --> custom-py27_0    
    conda:       4.1.6-py27_0      --> 4.2.6-py27_0     
    conda-env:   2.5.1-py27_0      --> 2.6.0-0          

I didn’t have this problem on my macbook pro and on my ubuntu desktop.Thanks for the help. 

Tural

**Comment by turalaksel** [comment]
After commenting, the following line in my _.profile_ , problem got fixed. 

**changed**

`export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"`

to

`#export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"`

**Comment by kalefranz** [comment]
With 4.2, conda now accepts a dependency on cytoolz if it's available. If not, we fall back to a pure-python implementation. This is the second report of a bug with cytoolz being out of date. Updating it will fix the problem. In the future we'll have the capability to specify a minimum version of an optional dependency.

**Comment by kaxil** [comment]
I can't use conda as well after update, it gives the same error 
`
NameError: name 'compose' is not defined
`

**Comment by hfarazi** [comment]
I had the same problem to fix it:
```
pip install --upgrade pip
pip uninstall cytoolz
pip install cytoolz
conda update cytoolz
```
