### ISSUE TITLE
ValueError: numpy.dtype has the wrong size, try recompiling (again?)

### ISSUE THREAD

**Issue by roryw10** [conda/conda#3460]
I'm getting a bit of a mad error. I have tried to search around for this and came across people with similar issues however all the solutions people have offered have not solved the issue. 

``Traceback (most recent call last): File "./nb_author_id.py", line 15, in from email_preprocess import preprocess File "../tools/email_preprocess.py", line 6, in from sklearn import cross_validation File "/usr/local/lib/python2.7/site-packages/sklearn/init.py", line 57, in from .base import clone File "/usr/local/lib/python2.7/site-packages/sklearn/base.py", line 11, in from .utils.fixes import signature File "/usr/local/lib/python2.7/site-packages/sklearn/utils/init.py", line 10, in from .murmurhash import murmurhash3_32 
File "numpy.pxd", line 155, in init sklearn.utils.murmurhash (sklearn/utils/murmurhash.c:5029) 
ValueError: numpy.dtype has the wrong size, try recompiling``

I will say this seems to have come up with a few people. Uninstalling and reinstalling conda and then packages was my first port of call however that does not seem to have helped.

What jumps out to me straight away is that i am working out of a conda environment - /anaconda/envs/yo/lib/python2.7/site-packages - i would have thought that using ./myscript.py from the virtual environment should be using the packages and env from conda and not trying to go to my local site package directory?

Im not using ipython/jupyter and have been running ./myscripy.py directly from terminal!

This problem has been very frustrating - i did try and unset the python path before activating the virtual conda env but no luck and i'm hitting the same issue!

In the header of mpyscripy.py i do have #!/usr/bin/python - is this making my script default to the user local package site

I would be extremely appreciative if anyone can help me solve this issue!

**Comment by roryw10** [comment]
I actually found out what the problem was.

It may depend on if you are using any virtualisatio. Im using Anaconda - i had made a couple of mistakes:

I had a user path in the header of the file which was not required. The shebang statement i not necessary with an Anaconda virtual anaconda

Closely related to point 1:- i was executing using "./my_myscript.py" i should have been running "python myscript.py"

Running "python myscript.py" runs the script fine.
