### ISSUE TITLE
Installing pymol using conda

### ISSUE THREAD

**Issue by TimCraigGenia** [conda/conda#3462]
Hello,
  I'm trying to install the program pymol, which is a molecular graphics viewer, into anaconda using conda install.

I downloaded the source from [here](https://sourceforge.net/projects/pymol/?source=typ_redirect)

and then opened a terminal on my mac and typed the following command:

craigt2-5DG9FN:Desktop craigt2$ conda install pymol-v1.8.2.1.tar.bz2

Which resulted in the following error:

Fetching packages ...
pymol-v1.8.2.1 100% |###################################################################################| Time: 0:00:00 130.54 MB/s
Extracting packages ...
[      COMPLETE      ]|######################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                |   0%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/craigt2/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 203, in install
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/misc.py", line 140, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 79, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'], shortcuts=shortcuts)
  File "/Users/craigt2/anaconda/lib/python2.7/site-packages/conda/install.py", line 1036, in link
    assert source_dir is not None
AssertionError

---

Also here if the result of conda info:
 craigt2-5DG9FN:Desktop craigt2$ conda info
Current conda install:

```
         platform : osx-64
    conda version : 4.1.6
conda-env version : 2.5.1
```

  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /Users/craigt2/anaconda  (writable)
  default environment : /Users/craigt2/anaconda
     envs directories : /Users/craigt2/anaconda/envs
        package cache : /Users/craigt2/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

---

What should I do to fix this?  Thanks for your help!

**Comment by TimCraigGenia** [comment]
I also tried to use the directions here: https://anaconda.org/psi4/pymol
But it seems to be too out of date.

**Comment by tyler-thetyrant** [comment]
You are using a very outdated version of conda!
Please try again with the most recent version of conda!
