### ISSUE TITLE
unable to update packages using conda

### ISSUE THREAD

**Issue by vijayan-n** [conda/conda#3466]
Following message was thrown:
`An unexpected error has occurred.                    | ETA:  0:02:43  24.31 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : linux-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : 1.21.3
     python version : 3.5.2.final.0
   requests version : 2.10.0
   root environment : /home/vjn/myStuff/software/anaconda  (writable)
default environment : /home/vjn/myStuff/software/anaconda
   envs directories : /home/vjn/myStuff/software/anaconda/envs
      package cache : /home/vjn/myStuff/software/anaconda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /home/vjn/myStuff/software/anaconda/bin/conda update --all`

```
Traceback (most recent call last):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
    yield
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 353, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 419, in download
    for chunk in resp.iter_content(2**14):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/requests/models.py", line 671, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 438, in download
    raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/home/vjn/myStuff/software/anaconda/pkgs/pyqt-5.6.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
    raise CondaSystemExit('Exiting', e)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
    yield
  File "/home/vjn/myStuff/software/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/home/vjn/myStuff/software/anaconda/pkgs/pyqt-5.6.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).
```

`

**Comment by umichfan1** [comment]
Is there any progress on this issue? I just ran into the exact same problem, and I cannot find a solution anywhere online.

**Comment by quasiben** [comment]
I've seen the same things

**Comment by ijstokes** [comment]
This appears to be a network timeout.  While this **can** be caused by client-side firewall or networking issues in my experience it has happened consistently at times when there are responsiveness issues with the Conda package repository.

If it happens to you I'd suggest going for a 15 minute walk, take in some fresh air, and hope that when you get back repo.continuum.io is responsive again.  If it is still not working 1-24 hours later definitely follow up on the Anaconda mailing list which is more likely to result in prompt resolution than reporting it here in GH (despite the message that was returned in this case).

**Comment by umichfan1** [comment]
Sounds good, thanks!

**Comment by kalefranz** [comment]
In the last few days we've dramatically improved how we serve repo.continuum.io packages.  Hopefully we've fixed this issue for you.

**Comment by kalefranz** [comment]
Actually, I know why I kept this open.  This shouldn't have a long stack trace.  We can make the message more descriptive.

**Comment by complyue** [comment]
still hitting this issue for now. same client network problem with pip, but `pip install --default-timeout=200 ` can workaround the situation, any equivalent for conda?

**Comment by kalefranz** [comment]
Much better error messages and timeouts now.

    conda update conda
