### ISSUE TITLE
conda info

### ISSUE THREAD

**Issue by shravankumar147** [conda/conda#3480]
Traceback (most recent call last):
  File "/home/shravan/anaconda3/bin/conda", line 6, in <module>
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 69, in execute
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 600, in execute_actions
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 136, in execute_instructions
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 79, in LINK_CMD
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/install.py", line 1103, in link
  File "/home/shravan/anaconda3/lib/python3.5/site-packages/conda/install.py", line 472, in create_meta
  File "/home/shravan/anaconda3/lib/python3.5/json/**init**.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/shravan/anaconda3/lib/python3.5/json/**init**.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/shravan/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/shravan/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by tyler-thetyrant** [comment]
Please use the most recent version of conda.
