### ISSUE TITLE
Error with --dry-run

### ISSUE THREAD

**Issue by mrocklin** [conda/conda#3485]
```
mrocklin@carbon:~$ conda install --dry-run numpy

Package plan for installation in environment /home/mrocklin/Software/anaconda:

The following packages will be SUPERCEDED by a higher-priority channel:

    numpy: 1.11.1-py35_blas_openblas_201 conda-forge [blas_openblas] --> 1.11.1-py35_0

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.7.0
       root environment : /home/mrocklin/Software/anaconda  (writable)
    default environment : /home/mrocklin/Software/anaconda
       envs directories : /home/mrocklin/Software/anaconda/envs
          package cache : /home/mrocklin/Software/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/mrocklin/.condarc
           offline mode : False



`$ /home/mrocklin/Software/anaconda/bin/conda install --dry-run numpy`




    Traceback (most recent call last):
      File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 398, in install
        common.confirm_yn(args)
      File "/home/mrocklin/Software/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 433, in confirm_yn
        raise DryRunExit
    TypeError: __init__() missing 1 required positional argument: 'message'
```

**Comment by bheklilr** [comment]
I got this error too, except that I had run `conda update --all --dry-run`, and the only package it listed for update was `conda` itself, going from 4.2.6-py27_0 to 4.2.9-py27_9.

**Comment by kalefranz** [comment]
Fixed quite a while ago, and remember also including regression tests.
