### ISSUE TITLE
Error while creating a local new environment

### ISSUE THREAD

**Issue by indiajoe** [conda/conda#3493]
Full output of the Traceback error msg while trying to create a local environment is given below.
`
$ conda create -n my_root --clone=/usr/anaconda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
src_prefix: '/usr/anaconda'
dst_prefix: '/home/joe/.conda/envs/my_root'
Packages: 175
Files: 4303
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/usr/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/usr/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/usr/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/usr/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/usr/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/usr/anaconda/lib/python2.7/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/usr/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/usr/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/usr/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'opencv-2.4.11-nppy27_0.tar.bz2'`

Conda info given below

`$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : linux-64
    conda version : 4.0.8
```

  conda-build version : 1.20.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /usr/anaconda  (read only)
  default environment : /usr/anaconda
     envs directories : /home/joe/.conda/envs
                        /home/joe/envs
                        /usr/anaconda/envs
        package cache : /home/joe/.conda/envs/.pkgs
                        /home/joe/envs/.pkgs
                        /usr/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
`

**Comment by kalefranz** [comment]
Fixed with conda 4.2 and 4.3.  If you still have this problem with recent versions of conda (4.3.17 is the latest), please file a new issue with the updated stack trace.
