### ISSUE TITLE
Package dependencies not resolved correctly

### ISSUE THREAD

**Issue by ikalev** [conda/conda#3499]
``pyqt=4.11.4``'s dependencies resolve to ``sip=4.16.9``:

```
$ conda install pyqt=4.11.4
Package plan for installation in environment C:\ANACONDA:
The following NEW packages will be INSTALLED:

    pyqt: 4.11.4-py27_7 defaults
    sip:  4.16.9-py27_2 defaults
```

However, this version of ``sip`` is incompatible with ``pyqt=4.11.4`` (which breaks ``matplotlib``). I was about to report this in the PyQT bug tracker when I suddenly discovered that the ``pyqt`` package properly requires ``sip=4.18``:

 - download https://repo.continuum.io/pkgs/free/win-64/pyqt-4.11.4-py27_7.tar.bz2
 - open up ``pyqt-4.11.4-py27_7.tar.bz2 ! info/index.json``:

```
{
  "arch": "x86_64", 
  "build": "py27_7", 
  "build_number": 7, 
  "depends": [
    "python 2.7*", 
    "qt 4.8.*", 
    "sip 4.18"
  ]
}
```

As you can see, ``pyqt`` requires ``sip 4.18``, not ``4.16``. I'm running ``conda=4.2.7``.

**Comment by murison** [comment]
Same error for me. Now matplotlib is BROKEN and unusable. After a 'conda update --all', this is what happens upon trying to import pylab:

\>>> from matplotlib import pylab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/pylab.py", line 274, in <module>
    from matplotlib.pyplot import *
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 15, in <module>
    from .backend_qt5 import QtCore
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 124, in <module>
    from PyQt4 import QtCore, QtGui
RuntimeError: the sip module implements API v11.0 to v11.2 but the PyQt4.QtCore module requires API v11.3

**Comment by murison** [comment]
Someone seems to have fixed the erroneous SIP dependence. I did an update and now SIP 4.18 (the correct one) is installed.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1105
