### ISSUE TITLE
Runtime Error: '_ssl.c:574: The handshake operation timed out'

### ISSUE THREAD

**Issue by varun-bankiti** [conda/conda#3504]
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/filelock-2.0.6-py27_0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : linux-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : 1.21.3
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : /home/XXXXX/anaconda2  (writable)
default environment : /home/XXXXX/anaconda2
   envs directories : /home/XXXXX/anaconda2/envs
      package cache : /home/XXXXX/anaconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : /home/XXXXX/.condarc
       offline mode : False
```

`$ /home/XXXXX/anaconda2/bin/conda update --all`

```
Traceback (most recent call last):
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: ('_ssl.c:574: The handshake operation timed out',): https://repo.continuum.io/pkgs/free/linux-64/filelock-2.0.6-py27_0.tar.bz2
```

**Comment by quasiben** [comment]
I've seen this error as well

**Comment by kalefranz** [comment]
should be addressed with https://github.com/conda/conda/pull/3831
