### ISSUE TITLE
Missing dependencies for SOCKS support.

### ISSUE THREAD

**Issue by varun-bankiti** [conda/conda#3505]
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : linux-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : 2.0.1
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : /home/XXXXX/anaconda2  (writable)
default environment : /home/XXXXX/anaconda2
   envs directories : /home/XXXXX/anaconda2/envs
      package cache : /home/XXXXX/anaconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : /home/XXXXX/.condarc
       offline mode : False
```

`$ /home/XXXXX/anaconda2/bin/conda update --all`

```
Traceback (most recent call last):
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
    prefix=prefix)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
    for url in urls]
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
    res = f(*args, **kwargs)
  File "/home/XXXXX/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 137, in fetch_repodata
    .format(url, filename, e))
CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.
```

**Comment by ChristelleG** [comment]
same issue here.

**Comment by karsibali** [comment]
Same here...

**Comment by kalefranz** [comment]
You'll need to install pysocks if you're using it.  I don't think we have a conda package for it right now, but pip works just as well.

    /home/XXXXX/anaconda2/bin/pip install pysocks

**Comment by karsibali** [comment]
Thanks @kalefranz ... It worked...

**Comment by kalefranz** [comment]
Leaving this issue open as a reminder to make a better error message.

**Comment by rmaria** [comment]
I have the same problem

**Comment by zhoujunpei** [comment]
Same problem
But running /home/XXXXX/anaconda2/bin/pip install pysocks did not help

**Comment by PanXiebit** [comment]
the same problem..
but  /home/XXXXX/anaconda2/bin/pip install pysocks did not help

**Comment by PanXiebit** [comment]
then I found this question,and it worked
(https://stackoverflow.com/questions/40926018/pip-install-doesnt-work-invalidschema-missing-dependencies-for-socks-support)
Unset socks proxy, in your case: 

```
unset all_proxy
unset ALL_PROXY
```

Install missing dependencies: 

```
pip install pysocks
```

Reset proxy, source .bashrc, and pip install works again with socks proxy.
