### ISSUE TITLE
after instalin seaborn using conda, the intalation got totally gone!.  update gave this dump !!

### ISSUE THREAD

**Issue by mvrmurty** [conda/conda#3514]
Current conda install:

```
           platform : win-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : 1.21.9
     python version : 2.7.10.final.0
   requests version : 2.7.0
   root environment : C:\Anaconda2  (writable)
default environment : C:\Anaconda2
   envs directories : C:\Anaconda2\envs
      package cache : C:\Anaconda2\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-64/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : None
       offline mode : False
```

`$ C:\Anaconda2\Scripts\conda-script.py update anaconda`

```
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 238, in install
    prefix=prefix)
  File "C:\Anaconda2\lib\site-packages\conda\api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 287, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "C:\Anaconda2\lib\site-packages\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\Anaconda2\lib\site-packages\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 70, in func
    res = f(*args, **kwargs)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
    timeout=(3.05, 60))
  File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "C:\Anaconda2\lib\site-packages\requests\adapters.py", line 370, in send
    timeout=timeout
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\connection.py", line 245, in connect
    cert = self.sock.getpeercert()
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 234, in getpeercert
    for value in get_subj_alt_name(x509)
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 135, in get_subj_alt_name
    asn1Spec=general_names)
  File "C:\Anaconda2\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda2\lib\site-packages\pyasn1\codec\ber\decoder.py", line 367, in valueDecoder
    component, head = decodeFun(head, asn1Spec)
  File "C:\Anaconda2\lib\site-packages\pyasn1\codec\ber\decoder.py", line 792, in __call__
    stGetValueDecoder, self, substrateFun
  File "C:\Anaconda2\lib\site-packages\pyasn1\codec\ber\decoder.py", line 430, in valueDecoder
    r.setComponentByType(effectiveTagSet, component, 0, asn1Spec is None)
  File "C:\Anaconda2\lib\site-packages\pyasn1\type\univ.py", line 874, in setComponentByType
    idx = self._componentType.getPositionByType(tagSet)
  File "C:\Anaconda2\lib\site-packages\pyasn1\type\namedtype.py", line 63, in getPositionByType
    raise error.PyAsn1Error('Duplicate type %s' % (t,))
PyAsn1Error: Duplicate type TagSet(Tag(tagClass=128, tagFormat=0, tagId=8))
```

C:\Users\murty>

**Comment by kalefranz** [comment]
Try `conda update conda` first.  If that doesn't work, you might have to download miniconda2 and install it overtop your current install.
