### ISSUE TITLE
Conda update error: PermissionError: [WinError 5] Access is denied

### ISSUE THREAD

**Issue by tugrulxyz** [conda/conda#3518]
conda update conda

i get the following error:

Traceback (most recent call last):
  File "D:\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 195, in main
    args_func(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 202, in args_fun
c
    args.func(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in ex
ecute
    install.install(args, parser, 'update')
  File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in insta
ll
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Anaconda3\lib\site-packages\conda\plan.py", line 537, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in exec
ute_instructions
    cmd(state, arg)
  File "D:\Anaconda3\lib\site-packages\conda\instructions.py", line 95, in UNLIN
K_CMD
    install.unlink(state['prefix'], arg)
  File "D:\Anaconda3\lib\site-packages\conda\install.py", line 721, in unlink
    os.unlink(meta_path)
PermissionError: [WinError 5] Access is denied: 'D:\Anaconda3\conda-meta\menu
inst-1.2.1-py35_0.json'

help much appreciated.

thanks

**Comment by kalefranz** [comment]
This is a multi-user install permissions issue, which was fixed in conda 4.3.
