### ISSUE TITLE
qt-4.8.7-4 fails to link while update

### ISSUE THREAD

**Issue by shusrev** [conda/conda#3519]
Current conda install:

```
           platform : osx-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : not installed
     python version : 3.5.2.final.0
   requests version : 2.11.1
   root environment : /Users/sinan/anaconda  (writable)
default environment : /Users/sinan/anaconda
   envs directories : /Users/sinan/anaconda/envs
      package cache : /Users/sinan/anaconda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /Users/sinan/anaconda/bin/conda update -v --all`

```
Traceback (most recent call last):
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/install.py", line 966, in link
    _link(src, dst, lt)
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/install.py", line 169, in _link
    os.symlink(os.readlink(src), dst)
FileExistsError: [Errno 17] File exists: 'macx-g++' -> '/Users/sinan/anaconda/mkspecs/default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/Users/sinan/anaconda/lib/python3.5/site-packages/conda/install.py", line 969, in link
    (src, dst, lt, e))
conda.exceptions.CondaOSError: OS error: failed to link (src='/Users/sinan/anaconda/pkgs/qt-4.8.7-4/mkspecs/default', dst='/Users/sinan/anaconda/mkspecs/default', type=3, error=FileExistsError(17, 'File exists'))
```

**Comment by BKJackson** [comment]
I have this error, too.  And the reason I was updating was because Spyder wasn't opening, which I think is a qt error.

**Comment by dangeles** [comment]
Same issue, encountered while doing `conda upgrade --all`:

`CondaOSError: OS error: failed to link (src='/Users/dangeles/anaconda3/pkgs/qt-4.8.7-4/mkspecs/default', dst='/Users/dangeles/anaconda3/mkspecs/default', type=3, error=FileExistsError(17, 'File exists'))'

**Comment by kalefranz** [comment]
Update to conda 4.3.  The issues will either be fixed for you, or there will be better error messages.  4.3.17 is the latest.
