### ISSUE TITLE
ImportError: No module named enum

### ISSUE THREAD

**Issue by flomertens** [conda/conda#3527]
I updated my conda installation with 'conda update --all', and now none conda command works:

Traceback (most recent call last):
  File "/home/flo/Developpement/conda/bin/conda", line 4, in <module>
    import conda.cli
  File "/home/flo/Developpement/conda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/home/flo/Developpement/conda/lib/python2.7/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/home/flo/Developpement/conda/lib/python2.7/site-packages/conda/base/context.py", line 13, in <module>
    from .constants import DEFAULT_CHANNELS, DEFAULT_CHANNEL_ALIAS, ROOT_ENV_NAME, SEARCH_PATH, conda
  File "/home/flo/Developpement/conda/lib/python2.7/site-packages/conda/base/constants.py", line 13, in <module>
    from enum import Enum
ImportError: No module named enum

This is a python2.7 installation. I believe enum is a new python3 package. Something went wrong here.

**Comment by flomertens** [comment]
I installed a new environment with Miniconda2-latest-Linux-x86_64.sh, and got the same issue as soon as I run 'source bin/activate root'

**Comment by soapy1** [comment]
Hmmm, this shouldn't be happening with newer versions of conda. Have you tried to `pip install enum34` and then running `conda update --all`?

**Comment by flomertens** [comment]
Yes at the end, I managed to recover my environment, thanks.

**Comment by Oscarhg42** [comment]
How did you recovered your environment. I have the same issue but `pip install enum34` does not work for Python 3

**Comment by flomertens** [comment]
Sorry I cann't help you, it was almost three years ago and I barely remember what I did last month ;)
