### ISSUE TITLE
fail more gracefully when filepath doesn't exist

### ISSUE THREAD

**Issue by bkreider** [conda/conda#3530]
Conda should catch this expected exception and exist gracefully.  This also happens if permissions are denied.

```
[root@bkreider-notebook-centos ~]# sudo -u wakari /opt/wakari/anaconda/bin/conda install -p /opt/wakari/wakari-compute/ /tmmp/<pkg name> --no-deps
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/wakari/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 202, in install
    verbose=not args.quiet)
  File "/opt/wakari/anaconda/lib/python2.7/site-packages/conda/misc.py", line 263, in install_local_packages
    shutil.copyfile(src_path, dst_path)
  File "/opt/wakari/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmmp/<package name>
```

**Comment by kalefranz** [comment]
Verified no longer an issue in conda 4.3

```
kfranz@0283:~/continuum/conda *4.3.x ❯ python -m conda install ./no/file-123-4.tar.bz2

CondaError: CondaFileNotFoundError: '/Users/kfranz/continuum/conda/no/file-123-4.tar.bz2'.
CondaError: CondaFileNotFoundError: '/Users/kfranz/continuum/conda/no/file-123-4.tar.bz2'.
CondaError: CondaFileNotFoundError: '/Users/kfranz/continuum/conda/no/file-123-4.tar.bz2'.

```

There are three repeats here because we're using requests (so we keep all the same logic), and requests tries up to three times for failed requests.  The relative path here just gets converted to an absolute path `file://` url.  Which also means explicit tarball installs from `https://` urls work just fine too.
