### ISSUE TITLE
Update Error...

### ISSUE THREAD

**Issue by lnsongxf** [conda/conda#3535]
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

```
         platform : win-64
    conda version : 3.19.1
```

  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : D:\Program Files\Anaconda3  (writable)
  default environment : D:\Program Files\Anaconda3
     envs directories : D:\Program Files\Anaconda3\envs
        package cache : D:\Program Files\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 226, in _error_catcher
    yield
  File "D:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 301, in read
    data = self._fp.read(amt)
  File "D:\Program Files\Anaconda3\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "D:\Program Files\Anaconda3\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "D:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "D:\Program Files\Anaconda3\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "D:\Program Files\Anaconda3\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "D:\Program Files\Anaconda3\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 180, in args_func
    args.func(args, p)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "D:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "D:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 311, in read
    flush_decoder = True
  File "D:\Program Files\Anaconda3\lib\contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "D:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by kalefranz** [comment]
Intermittent HTTP error.
