### ISSUE TITLE
conda install –c auto descartes ERROR

### ISSUE THREAD

**Issue by eavelardev** [conda/conda#3542]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 434, in print_unexpected_error_message
    command = ' '.join(sys.argv)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by kalefranz** [comment]
Please update to a recent version of conda.  Latest is conda 4.3.17.  If you're still having problems, please file a new issue.  Also please include `conda info`.
