### ISSUE TITLE
Unexpected error intalling R with conda (Linux 64-bit)

### ISSUE THREAD

**Issue by glimmerphoenix** [conda/conda#3543]
Hello,

Trying to execute the standard command `conda install -c r r-essentials`, on Ubuntu Server 64-bit, I get the following error, apparently related with `harfbuzz-0.9.35-6.tar.bz2`:

<pre>
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /data/python/anaconda3  (writable)
    default environment : /data/python/anaconda3/envs/datascience
       envs directories : /data/python/anaconda3/envs
          package cache : /data/python/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /data/python/anaconda3/envs/datascience/bin/conda install -c r r-essentials`

    Traceback (most recent call last):
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 378, in download
        resp.raise_for_status()
      File "/data/python/anaconda3/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/r/linux-64/harfbuzz-0.9.35-6.tar.bz2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 387, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/r/linux-64/harfbuzz-0.9.35-6.tar.bz2: https://conda.anaconda.org/r/linux-64/harfbuzz-0.9.35-6.tar.bz2

    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/data/python/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/data/python/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/r/linux-64/harfbuzz-0.9.35-6.tar.bz2: https://conda.anaconda.org/r/linux-64/harfbuzz-0.9.35-6.tar.bz2
</pre>

**Comment by holtgrewe** [comment]
Can confirm, same issue here. 3.3.1 works fine but my dependency resolution triggers downgrade to 3.2.2 and then the error from above.

**Comment by holtgrewe** [comment]
@glimmerphoenix for me this works now again

**Comment by glimmerphoenix** [comment]
@holtgrewe indeed, it also works for me now. Thanks for the fast answer!
