### ISSUE TITLE
Error trying to remove env

### ISSUE THREAD

**Issue by JamesOwers** [conda/conda#3545]
Cloned an environment from root so attempted to fix using [these instructions](http://stackoverflow.com/questions/36117904/error-conda-can-only-be-installed-into-the-root-environment). Now remove function causes error.

``` bash
$ conda env remove -n theano
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .............
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/kungfujam/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 127, in args_func
    args.func(args, p)
  File "/Users/kungfujam/anaconda/lib/python2.7/site-packages/conda_env/cli/main_remove.py", line 73, in execute
    plan.PREFIX: prefix,
AttributeError: 'module' object has no attribute 'PREFIX'
$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 4.1.0rc3
  conda-build version : 0+unknown
       python version : 2.7.11.final.0
     requests version : 2.8.1
     root environment : /Users/kungfujam/anaconda  (writable)
  default environment : /Users/kungfujam/anaconda
     envs directories : /Users/kungfujam/anaconda/envs
        package cache : /Users/kungfujam/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://conda.anaconda.org/r/osx-64/
                        https://conda.anaconda.org/r/noarch/
                        https://conda.anaconda.org/conda/osx-64/
                        https://conda.anaconda.org/conda/noarch/
                        https://conda.anaconda.org/mpastell/osx-64/
                        https://conda.anaconda.org/mpastell/noarch/
          config file : /Users/kungfujam/.condarc
    is foreign system : False
```

**Comment by kalefranz** [comment]
Fixed. `conda update conda`
