### ISSUE TITLE
Error trying to update Spyder

### ISSUE THREAD

**Issue by tendres** [conda/conda#3547]
Current conda install:

```
           platform : osx-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 1.21.4
     python version : 2.7.10.final.0
   requests version : 2.7.0
   root environment : /Users/tendres/anaconda  (writable)
default environment : /Users/tendres/anaconda
   envs directories : /Users/tendres/anaconda/envs
      package cache : /Users/tendres/anaconda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /Users/tendres/anaconda/bin/conda update qt pyqt`

```
Traceback (most recent call last):
  File "/Users/tendres/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/tendres/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/tendres/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/Users/tendres/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590): https://repo.continuum.io/pkgs/free/osx-64/qt-4.8.7-4.tar.bz2
```

**Comment by tyler-thetyrant** [comment]
Please use the most recent version of conda.

**Comment by tyler-thetyrant** [comment]
`conda update conda` will bring you to 4.3.17
