### ISSUE TITLE
Conda 4.2.9 introduced breaking change in conda.connection.CondaSession object

### ISSUE THREAD

**Issue by bheklilr** [conda/conda#3548]
Today I ran `conda update -n root --all` to pull in the latest changes that I had synced to our internal anaconda mirror.  After performing this update I discovered that any action that has to pull down `repodata.json` gets a 404 for our servers.  This is very odd, because if I go into `conda/fetch.py` and add in some print statements to see what arguments are going in to the GET request:

```python
print(url + filename)
print(headers)
print(session.proxies)
resp = session.get(url + filename, headers=headers, proxies=session.proxies,
                   timeout=(3.05, 60))
```

(line 111)

Then use these parameters myself using a normal `requests.Session` object in an IPython shell, the code works just fine.  If I replace `session = session or CondaSession()` on line 94 with `session = requests.Session()`, then I can use `conda` normally as well (we don't have any certificates or proxies for this internal server).  I tried looking through the history of this file on github and reverting some of the changes to `conda/base/connection.py` I thought looked suspicious, but I couldn't get it working through mere trial and error.  Examining the HTTP status codes of the request in the unmodified 4.2.9 code shows that it actually is getting a 404 error at that point.  The only thing that I didn't try adding was the user agent to the header, but I wouldn't expect that to matter.

I'll stress that I can access this URL using `requests` direction and through my browser without issue.  The URL exists, but for some reason the CondaSession object is unable to retrieve it.

My `.condarc` file looks like
```yaml
anaconda_upload: false
channel_alias: http://server/conda
channels:
  - mychannel
  - orgchannel
  - anaconda
  - conda-forge
show_channel_urls: true
```

And

```
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.1
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : ...\Continuum\Miniconda3  (writable)
    default environment : ...\Continuum\Miniconda3
       envs directories : ...\Continuum\Miniconda3\envs
          package cache : ...\Continuum\Miniconda3\pkgs
           channel URLs : http://server/conda\mychannel/win-64/
                          http://server/conda\mychannel/noarch/
                          http://server/conda\orgchannel/win-64/
                          http://server/conda\orgchannel/noarch/
                          http://server/conda\anaconda/win-64/
                          http://server/conda\anaconda/noarch/
                          http://server/conda\conda-forge/win-64/
                          http://server/conda\conda-forge/noarch/
            config file : ~\.condarc
           offline mode : False
```

And the original traceback I received was
```
    Traceback (most recent call last):                                                                                          
      File "...\Continuum\Miniconda3\lib\site-packages\conda\fetch.py", line 115, in fetch_repodata 
        resp.raise_for_status()                                                                                                 
      File "...\Continuum\Miniconda3\lib\site-packages\requests\models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)                                                                          
    requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: http://server/t/<TOKEN>/conda/mychannel/win-64/repodata.json
                                                                                                                                
    During handling of the above exception, another exception occurred:                                                         
                                                                                                                                
    Traceback (most recent call last):                                                                                          
      File "...\Continuum\Miniconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)                                                                                    
      File "...\Continuum\Miniconda3\lib\site-packages\conda\cli\main.py", line 144, in _main       
        exit_code = args.func(args, p)                                                                                          
      File "...\Continuum\Miniconda3\lib\site-packages\conda\cli\main_search.py", line 126, in execute
        execute_search(args, parser)                                                                                            
      File "...\Continuum\Miniconda3\lib\site-packages\conda\cli\main_search.py", line 174, in execute_search
        unknown=args.unknown)                                                                                                   
      File "...\Continuum\Miniconda3\lib\site-packages\conda\api.py", line 24, in get_index         
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)                                                 
      File "...\Continuum\Miniconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index    
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]                                                            
      File "...\Continuum\Miniconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>     
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]                                                            
      File "...\Continuum\Miniconda3\lib\concurrent\futures\_base.py", line 405, in result          
        return self.__get_result()                                                                                              
      File "...\Continuum\Miniconda3\lib\concurrent\futures\_base.py", line 357, in __get_result    
        raise self._exception                                                                                                   
      File "...\Continuum\Miniconda3\lib\concurrent\futures\thread.py", line 55, in run             
        result = self.fn(*self.args, **self.kwargs)                                                                             
      File "...\Continuum\Miniconda3\lib\site-packages\conda\fetch.py", line 70, in func            
        res = f(*args, **kwargs)                                                                                                
      File "...\Continuum\Miniconda3\lib\site-packages\conda\fetch.py", line 165, in fetch_repodata 
        raise CondaHTTPError(msg)                                                                                               
    conda.exceptions.CondaHTTPError: HTTP Error: Could not find URL: http://server/conda/mychannel/win-64/             
```

Thank you,
Aaron Stevens

**Comment by bheklilr** [comment]
I was able to hack it back to use conda 4.2.7 and the bug also existed there.  When tested using 4.1.11 (the last version I remember having before attempting to upgrade) it works just fine.  I would do more testing to determine the exact version of conda that breaks things, but this bug has already cost me about 2-3 hours.  My guess is that it probably happened around 4.2.

**Comment by kalefranz** [comment]
@bheklilr 

Conda 4.2.10 is available on the `conda-canary` channel, and it should have a fix for this issue.  If you have time, please help test it.

    conda config --prepend channels conda-canary
    conda update conda

We'll likely be releasing this build to the general availability defaults channel on Friday.

**Comment by bheklilr** [comment]
@kalefranz I installed conda 4.2.10 from conda-canary and it does seem to work better, I can run fully builds for my packages again, searching works properly, and giving channels with `channel_alias` set works properly.  Glad to see this bug getting fixed!  I'll make sure to sync this release to our internal server ASAP when it is released on the main channel.  Thanks for your hard work, that #3550 pull request looks like a beast.

**Comment by kalefranz** [comment]
Yeah #3550 was quite a bit of work.  Have one regression in it, and there will be a 4.2.11 released to defaults on Monday.
