### ISSUE TITLE
conda install --offline path/package.bz2 raises a KeyError

### ISSUE THREAD

**Issue by nasedil** [conda/conda#3552]
When I try to install a package from a local .bz2 file offline, I get a strange error:
```
user@computer:~$ /home/user/anaconda-second/bin/conda install --offline pkg/numpy-1.11.1-py35_0.tar.bz2
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/user/anaconda-second/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/cli/main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/cli/install.py", line 203, in install
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/misc.py", line 126, in explicit
    index.update(get_index(**index_args))
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/api.py", line 22, in get_index
    channel_urls = normalize_urls(channel_urls, platform, offline)
  File "/home/user/anaconda-second/lib/python3.5/site-packages/conda/config.py", line 250, in normalize_urls
    url = urls[0]
KeyError: 0
```
Here is the output of `conda info`:
```
             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/user/anaconda-second  (writable)
  default environment : /home/user/anaconda-second
     envs directories : /home/user/anaconda-second/envs
        package cache : /home/user/anaconda-second/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by nasedil** [comment]
Ok, it is duplicate of #3035. A new Anaconda 4.2 version came out yesterday, and it works as it should.  Bad timing, I've managed to download Anaconda 4.1 version yesterday afternoon, probably a couple of hours before the new one appeared on the website.
