### ISSUE TITLE
Conda not working after upgrade to v4.2.9

### ISSUE THREAD

**Issue by dkillick** [conda/conda#3554]
Hi, I just updated my Conda install to v4.2.9 and I'm now getting the following error, which happens when I try and use any Conda command:

```
$ conda --version
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/.../miniconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/.../miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/.../miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/.../miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/.../miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 407, in get_info
    args.func(args, p)
  File "/.../miniconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 155, in execute
    from conda.api import get_index
  File "/.../miniconda/lib/python2.7/site-packages/conda/api.py", line 7, in <module>
    from .fetch import fetch_index
  File "/.../miniconda/lib/python2.7/site-packages/conda/fetch.py", line 20, in <module>
    from requests.packages.urllib3.connectionpool import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning
```

Here's the upgrade command and the associated stdout that I used to upgrade:
```
$ conda update conda
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /.../miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B  defaults
    conda-4.2.9                |           py27_0         360 KB  defaults
    ------------------------------------------------------------
                                           Total:         361 KB

The following NEW packages will be INSTALLED:

    enum34:    1.1.6-py27_0  defaults   

The following packages will be UPDATED:

    conda:     4.1.11-py27_1 conda-forge --> 4.2.9-py27_0 defaults
    conda-env: 2.5.2-py27_0  conda-forge --> 2.6.0-0      defaults

Proceed ([y]/n)? 

Fetching packages ...
conda-env-2.6. 100% |###################################################################| Time: 0:00:00  66.93 kB/s
conda-4.2.9-py 100% |###################################################################| Time: 0:00:00 449.17 kB/s
Extracting packages ...
[      COMPLETE      ]|######################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|######################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|######################################################################################| 100%
```

I'm sharing this mainly so that it can be fixed, however I can't currently use my Conda install! Short of uninstalling and reinstalling, do you have any thoughts on how I can get my Conda install working again, if just to downgrade for the moment? I could manually download a version of requests that contains the missing name I guess, and get that into the Python PATH I guess...

Thanks!

**Comment by dkillick** [comment]
Whoa, this one is my bad...

I had an old reference to an old (v2.3.0) version of requests in a user-level `site-packages` directory, which was inserting itself onto the python path above conda's `site-packages` and muddling everything up :unamused: 

Sorry for the bother, I'll close this now.
