### ISSUE TITLE
anacoda install tensorflow is error 

### ISSUE THREAD

**Issue by adminnanfeng** [conda/conda#3559]
Current conda install:

```
           platform : linux-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : /root/anaconda2  (writable)
default environment : /root/anaconda2
   envs directories : /root/anaconda2/envs
      package cache : /root/anaconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /root/anaconda2/bin/conda install -n tensor -y -c https://conda.anaconda.org/jjhelmus tensorflow`

```
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'D' (0x44) at index 236
```

**Comment by kalefranz** [comment]
Encoding issues are hopefully fixed in later versions of conda 4.3.
