### ISSUE TITLE
matplotlib.pyplot broken -- cannot import

### ISSUE THREAD

**Issue by murison** [conda/conda#3568]
Upon doing a routine 'conda update --all', which resulted in this:

The following NEW packages will be INSTALLED:

```
astroid:           1.4.7-py35_0     
dbus:              1.10.10-0        
gst-plugins-base:  1.8.0-0          
gstreamer:         1.8.0-0          
icu:               54.1-0           
lazy-object-proxy: 1.2.1-py35_0
libgcc:            5.2.0-0          
libxcb:            1.12-0           
pylint:            1.5.4-py35_1     
qtawesome:         0.3.3-py35_0     
qtpy:              1.1.2-py35_0     
wrapt:             1.10.8-py35_0    
```

The following packages will be UPDATED:

```
jpeg:              8d-1              --> 8d-2             
matplotlib:        1.5.1-np111py35_0 --> 1.5.3-np111py35_0
openssl:           1.0.2i-0          --> 1.0.2j-0         
pyqt:              4.11.4-py35_4     --> 5.6.0-py35_0     
qt:                4.8.7-4           --> 5.6.0-0          
qtconsole:         4.2.1-py35_0      --> 4.2.1-py35_1     
spyder:            2.3.9-py35_1      --> 3.0.0-py35_0     
traitlets:         4.3.0-py35_0      --> 4.3.1-py35_0     
```

to which I answered yes, I now discover that matplotlib is newly broken (again!):

>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'PyxImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/pyplot.py", line 114, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt4agg.py", line 18, in <module>
    from .backend_qt5agg import FigureCanvasQTAggBase as _FigureCanvasQTAggBase
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5agg.py", line 16, in <module>
    from .backend_qt5 import QtCore
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/backend_qt5.py", line 27, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_editor/figureoptions.py", line 17, in <module>
    import matplotlib.backends.qt_editor.formlayout as formlayout
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_editor/formlayout.py", line 58, in <module>
    from matplotlib.backends.qt_compat import QtGui, QtWidgets, QtCore
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/matplotlib/backends/qt_compat.py", line 137, in <module>
    from PyQt4 import QtCore, QtGui
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 892, in _find_spec
  File "<frozen importlib._bootstrap>", line 873, in _find_spec_legacy
  File "/scr/bin/anaconda3/lib/python3.5/site-packages/pyximport/pyximport.py", line 254, in find_module
    fp, pathname, (ext,mode,ty) = imp.find_module(fullname,package_path)
  File "/scr/bin/anaconda3/lib/python3.5/imp.py", line 270, in find_module
    "not {}".format(type(name)))
RuntimeError: 'list' must be None or a list, not <class 'str'>

Reverting back to matplotlib 1.5.1 undid the bug.

Come on, whoever is the loose cannon, TEST YOUR CODE before inflicting it on the world.

**Comment by kalefranz** [comment]
lol this has nothing to do with conda
