### ISSUE TITLE
failed to stay in tune with jupyter

### ISSUE THREAD

**Issue by denfromufa** [conda/conda#3574]
```
C:\Users\denis.akhiyarov>conda install jupyter
Fetching package metadata .........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.21.0
         python version : 2.7.12.final.0
       requests version : 2.4.3
       root environment : C:\Python\Python27_32b  (writable)
    default environment : C:\Python\Python27_32b
       envs directories : C:\Python\Python27_32b\envs
          package cache : C:\Python\Python27_32b\pkgs
           channel URLs : https://conda.anaconda.org/dsdale24/win-32/
                          https://conda.anaconda.org/dsdale24/noarch/
                          https://repo.continuum.io/pkgs/free/win-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-32/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\denis.akhiyarov\.condarc
           offline mode : False



`$ C:\Python\Python27_32b\Scripts\conda-script.py install jupyter`




    Traceback (most recent call last):
      File "C:\Python\Python27_32b\lib\site-packages\conda\exceptions.py", line
473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Python\Python27_32b\lib\site-packages\conda\cli\main.py", line 1
4, in _main
        exit_code = args.func(args, p)
      File "C:\Python\Python27_32b\lib\site-packages\conda\cli\main_install.py"
 line 80, in execute
        install(args, parser, 'install')
      File "C:\Python\Python27_32b\lib\site-packages\conda\cli\install.py", lin
 238, in install
        prefix=prefix)
      File "C:\Python\Python27_32b\lib\site-packages\conda\api.py", line 24, in
get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Python\Python27_32b\lib\site-packages\conda\fetch.py", line 287,
in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Python\Python27_32b\lib\site-packages\concurrent\futures\_base.p
", line 403, in result
        return self.__get_result()
      File "C:\Python\Python27_32b\lib\site-packages\concurrent\futures\thread.
y", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Python\Python27_32b\lib\site-packages\conda\fetch.py", line 70,
n func
        res = f(*args, **kwargs)
      File "C:\Python\Python27_32b\lib\site-packages\conda\fetch.py", line 112,
in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Python\Python27_32b\lib\site-packages\requests\sessions.py", lin
 469, in get
        return self.request('GET', url, **kwargs)
      File "C:\Python\Python27_32b\lib\site-packages\requests\sessions.py", lin
 443, in request
        prep = self.prepare_request(req)
      File "C:\Python\Python27_32b\lib\site-packages\requests\sessions.py", lin
 374, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "C:\Python\Python27_32b\lib\site-packages\requests\models.py", line
08, in prepare
        self.prepare_auth(auth, url)
      File "C:\Python\Python27_32b\lib\site-packages\requests\models.py", line
92, in prepare_auth
        r = auth(self)
      File "C:\Python\Python27_32b\lib\site-packages\conda\connection.py", line
69, in __call__
        request.url = BinstarAuth.add_binstar_token(request.url)
      File "C:\Python\Python27_32b\lib\site-packages\conda\connection.py", line
82, in add_binstar_token
        return Url(u.scheme, u.auth, u.host, u.port, path, u.query).url
    AttributeError: 'Url' object has no attribute 'url'


```

**Comment by bjedwards** [comment]
Just ran across the same problem, might have more info.

I updated ipython with 

```shell
conda update ipython
```

resulting in 

```
Fetching package metadata .......
Solving package specifications: ..........
Using Anaconda Cloud api site https://api.anaconda.org

Package plan for installation in environment /Users/BenjaminEdwards/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    anaconda-custom            |           py35_0           3 KB
    ruamel_yaml-0.11.14        |           py35_0         178 KB
    conda-4.2.12               |           py35_0         387 KB
    prompt_toolkit-1.0.9       |           py35_0         325 KB
    ------------------------------------------------------------
                                           Total:         893 KB

The following NEW packages will be INSTALLED:

    prompt_toolkit: 1.0.9-py35_0
    wcwidth:        0.1.7-py35_0

The following packages will be UPDATED:

    anaconda:       4.1.1-np111py35_0 --> custom-py35_0
    conda:          4.1.11-py35_0     --> 4.2.12-py35_0
    conda-env:      2.5.2-py35_0      --> 2.6.0-0
    ipython:        4.2.0-py35_1      --> 5.1.0-py35_1
    ruamel_yaml:    0.11.7-py35_0     --> 0.11.14-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |################################| Time: 0:00:00 756.99 kB/s
anaconda-custo 100% |################################| Time: 0:00:00   3.31 MB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00   6.76 MB/s
conda-4.2.12-p 100% |################################| Time: 0:00:00   5.15 MB/s
prompt_toolkit 100% |################################| Time: 0:00:00   3.64 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
[      COMPLETE      ]|###################################################| 100%
```

Updating anything else now gives me the above error

**Comment by kalefranz** [comment]
Fixed.

**Comment by denfromufa** [comment]
@kalefranz how did you fix this? no reference.
