### ISSUE TITLE
Failed to clone

### ISSUE THREAD

**Issue by patquem** [conda/conda#3576]
Hello,

When trying to clone my env, I am faced to the following error (see below).
Here are the '.bat' file I used to create the original environment (renamed in '.txt' file to be attached):
[clg_python_install.txt](https://github.com/conda/conda/files/507869/clg_python_install.txt)
Could you pleased investigate this problem. Thank you,

Patrick

C:\dev\sw\miniconda2\envs\env001_mayavi\Lib>conda info
Current conda install:

```
         platform : win-64
    conda version : 4.0.5
```

  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\dev\sw\miniconda2  (writable)
  default environment : C:\dev\sw\miniconda2
     envs directories : C:\dev\sw\miniconda2\envs
        package cache : C:\dev\sw\miniconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

---

---

C:\dev\sw\miniconda2\envs> conda create --name env001_mayavi --clone env001
Fetching package metadata: ....
src_prefix: 'C:\dev\sw\miniconda2\envs\env001'
dst_prefix: 'C:\dev\sw\miniconda2\envs\env001_mayavi'
Packages: 53
Files: 1230
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\dev\sw\miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\cli\install.py", line 84, in clone
    quiet=quiet, index=index)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "C:\dev\sw\miniconda2\lib\site-packages\conda\resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'shapely-1.5.13-np110py27_1.tar.bz2'

**Comment by tyler-thetyrant** [comment]
Closing as outdated.
Please use the most recent version of conda.
