### ISSUE TITLE
error installing lua and torch

### ISSUE THREAD

**Issue by angelleng** [conda/conda#3578]
Error message: 
Current conda install:

```
           platform : osx-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : /Users/leng/anaconda2  (writable)
default environment : /Users/leng/anaconda2
   envs directories : /Users/leng/anaconda2/envs
      package cache : /Users/leng/anaconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /Users/leng/anaconda2/bin/conda install lua=5.2 lua-science -c alexbw`

```
Traceback (most recent call last):
  File "/Users/leng/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/leng/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/leng/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/leng/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/graphviz-2.38.0-2.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/osx-64/graphviz-2.38.0-2.tar.bz2
```

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
