### ISSUE TITLE
Unable to update Conda or create Graphlab environment

### ISSUE THREAD

**Issue by Piraat** [conda/conda#3579]
Current conda install:

```
           platform : win-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : C:\Anaconda2  (writable)
default environment : C:\Anaconda2
   envs directories : C:\Anaconda2\envs
      package cache : C:\Anaconda2\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-64/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : None
       offline mode : False
```

`$ C:\Anaconda2\Scripts\conda-script.py create -n gl-env python=2.7 anaconda`

```
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in co
```

nda_exception_handler
        return_value = func(_args, *_kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _mai
n
        exit_code = args.func(args, p)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, i
n execute
        install(args, parser, 'create')
      File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 238, in i
nstall
        prefix=prefix)
      File "C:\Anaconda2\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 287, in fetch_i
ndex
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Anaconda2\lib\site-packages\concurrent\futures_base.py", line 40
5, in result
        return self.__get_result()
      File "C:\Anaconda2\lib\site-packages\concurrent\futures\thread.py", line 5
5, in run
        result = self.fn(_self.args, *_self.kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(_args, *_kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 112, in fetch_r
epodata
        timeout=(3.05, 60))
      File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 488, in g
et
        return self.request('GET', url, *_kwargs)
      File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 475, in r
equest
        resp = self.send(prep, *_send_kwargs)
      File "C:\Anaconda2\lib\site-packages\requests\sessions.py", line 628, in s
end
        r.content
      File "C:\Anaconda2\lib\site-packages\requests\models.py", line 755, in con
tent
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or b
ytes()
      File "C:\Anaconda2\lib\site-packages\requests\models.py", line 679, in gen
erate
        raise ChunkedEncodingError(e)
    ChunkedEncodingError: ("Connection broken: error(10054, 'De externe host hee
ft een verbinding verbroken')", error(10054, 'De externe host heeft een verbindi
ng verbroken'))

**Comment by kalefranz** [comment]
Intermittent HTTP error.
