### ISSUE TITLE
R essential-packages installation failed

### ISSUE THREAD

**Issue by RajanMehta01** [conda/conda#3595]
Current conda install:

```
           platform : linux-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : /home/accionlabs/anaconda2  (writable)
default environment : /home/accionlabs/anaconda2
   envs directories : /home/accionlabs/anaconda2/envs
      package cache : /home/accionlabs/anaconda2/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /home/accionlabs/anaconda2/bin/conda create -n my-r-env -c r r-essentials`

```
Traceback (most recent call last):
  File "/home/accionlabs/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/accionlabs/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/accionlabs/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/home/accionlabs/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/accionlabs/anaconda2/pkgs/r-nloptr-1.0.4-r3.3.1_2.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
