### ISSUE TITLE
conda incorrectly attempts to update a symlinked system Python

### ISSUE THREAD

**Issue by ncoghlan** [conda/conda#360]
To try out the new pip compatibility I did:

```
$ mkvirtualenv conda
$ pip install conda
$ conda init
$ conda install scikit-learn
```

The last step picked up that the venv Python was only Python 2.7.5, so it tried to upgrade it to 2.7.6. However, this failed, since virtualenv _symlinks_ the various pieces of the system Python into the virtual environment, rather than copying them:

```
$ ls -ld /home/ncoghlan/.virtualenvs/conda/lib/python2.7/config
lrwxrwxrwx. 1 ncoghlan ncoghlan 27 Nov 17 16:10 /home/ncoghlan/.virtualenvs/conda/lib/python2.7/config -> /usr/lib64/python2.7/config
```

Since I was running this without root access, the attempt to upgrade Python inside the virtualenv failed:

```
Traceback (most recent call last):
  File "/home/ncoghlan/.virtualenvs/conda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/cli/main.py", line 183, in main
    args.func(args, p)
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/cli/main_install.py", line 199, in execute
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/plan.py", line 374, in execute_actions
    execute_plan(plan, index, verbose)
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/plan.py", line 359, in execute_plan
    link(prefix, arg)
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/plan.py", line 314, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/install.py", line 380, in link
    _link(src, dst, lt)
  File "/home/ncoghlan/.virtualenvs/conda/lib/python2.7/site-packages/conda/install.py", line 127, in _link
    shutil.copy2(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib64/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/home/ncoghlan/.virtualenvs/conda/lib/python2.7/config/Makefile'
```

**Comment by kalefranz** [comment]
The conda init command was removed a few years ago.  I believe this ticket can be closed as no longer relevant.
