### ISSUE TITLE
conda Create environment fails

### ISSUE THREAD

**Issue by Alayappan** [conda/conda#3604]
Well i tried to create a environment "tensorflow"

C:\Users\Alayappan>conda create -n tensorflow python=2.7
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Alayappan.conda\envs\tensorflow:

The following NEW packages will be INSTALLED:

```
pip:            8.1.2-py27_0   (copy)
python:         2.7.12-0       (copy)
setuptools:     27.2.0-py27_1  (copy)
vs2008_runtime: 9.00.30729.1-2 (copy)
wheel:          0.29.0-py27_0  (copy)
```

Proceed ([y]/n)? y

Extracting packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : win-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.2
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : C:\Program Files\Anaconda2  (read only)
default environment : C:\Program Files\Anaconda2
   envs directories : C:\Users\Alayappan\.conda\envs
                      C:\Program Files\Anaconda2\envs
      package cache : C:\Users\Alayappan\.conda\envs\.pkgs
                      C:\Program Files\Anaconda2\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-64/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : None
       offline mode : False
```

`$ C:\Program Files\Anaconda2\Scripts\conda-script.py create -n tensorflow python=2.7.12`

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
    extract(arg)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\install.py", line 801, in extract
    t.extractall(path=temp_path)
  File "C:\Program Files\Anaconda2\lib\tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "C:\Program Files\Anaconda2\lib\tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Program Files\Anaconda2\lib\tarfile.py", line 2184, in _extract_member
    os.makedirs(upperdirs)
  File "C:\Program Files\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Program Files\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] Access is denied: u'C:\\Program Files\\Anaconda2\\pkgs\\vs2008_runtime-9.00.30729.1-2.tmp'
```

**Comment by kalefranz** [comment]
Still having problems with recent versions of conda?  Latest is 4.3.17.

**Comment by Alayappan** [comment]
Not , in current version

On May 9, 2017 10:23 AM, "Kale Franz" <notifications@github.com> wrote:

Still having problems with recent versions of conda? Latest is 4.3.17.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda/conda/issues/3604#issuecomment-300060930>, or mute
the thread
