### ISSUE TITLE
 Error: post-link failed for: ipykernel-4.5.0-py35_0#######

### ISSUE THREAD

**Issue by fabianheredia** [conda/conda#3606]
Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_hand
ler
    return_value = func(_args, *_kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main.py", line 112, in _main
    imported = importlib.import_module(module)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\importlib__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main_list.py", line 17, in <module>
    from ..egg_info import get_egg_info
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\misc.py", line 14, in <module>
    from .api import get_index
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\fetch.py", line 27, in <module>
    from .connection import CondaSession, RETRIES
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\connection.py", line 58, in <module>
    python=platform.python_implementation(),
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\platform.py", line 1292, in python_implementation
    return _sys_version()[0]
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\platform.py", line 1252, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MS
C v.1900 64 bit (AMD64)]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\exceptions.py", line 491, in conda_exception_hand
ler
    print_unexpected_error_message(e)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\exceptions.py", line 437, in print_unexpected_err
or_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\exceptions.py", line 407, in get_info
    args.func(args, p)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main_info.py", line 155, in execute
    from conda.api import get_index
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\fetch.py", line 27, in <module>
    from .connection import CondaSession, RETRIES
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\connection.py", line 58, in <module>
    python=platform.python_implementation(),
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\platform.py", line 1292, in python_implementation
    return _sys_version()[0]
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\platform.py", line 1252, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.1 |Continuum Analytics, Inc.| (default, Feb 16 2016, 09:49:46) [MS
C v.1900 64 bit (AMD64)]'

C:\Program Files\ArcGIS\Pro\bin\Python\Scripts>conda install -c conda-forge ipywidgets

**Comment by kalefranz** [comment]
From https://github.com/conda/conda/issues/4901#issuecomment-287868746

> Here you have two different Python installations and they are stepping on each other's toes.
> 
> I am guessing you elected to allow the installer to add itself to your system `PATH` but already had 'normal' Python 2.7 installed to the default location and also present in your `PATH`?
> 
> Unfortunately our installer adds its entries to the end of `PATH` so DLLs for other software frequently get loaded instead of ours (Python itself consists of many DLLs).
>
> I think, if the Anaconda Installer is going to add to `PATH` it should add its entries to the front of `PATH` like nearly all other installers do, but I more strongly think that software should not add itself to `PATH` by default (or recommend that to users).
>
> If you use the `Anaconda Prompt` to launch your command prompt then that will add the correct entries to the front of your `PATH` temporarily (i.e. for that command prompt instance only).

**Comment by kalefranz** [comment]
Moving this to anaconda-issues.  @csoja resolution should probably be a topic for an Anaconda weekly meeting.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1667
