### ISSUE TITLE
Error while installing jupyter notebook in anaconda

### ISSUE THREAD

**Issue by npatwa** [conda/conda#3609]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 208, in args_func
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 612, in inner
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 46, in execute
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 413, in install
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 527, in execute_actions
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 95, in UNLINK_CMD
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 674, in unlink
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 311, in mk_menus
  File "C:\Anaconda3\lib\site-packages\menuinst__init__.py", line 23, in 
    from .win32 import Menu, ShortCut, dirs
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 13, in 
    from .knownfolders import get_folder_path, FOLDERID
  File "C:\Anaconda3\lib\site-packages\menuinst\knownfolders.py", line 152, in 
    _SHGetKnownFolderPath = windll.shell32.SHGetKnownFolderPath     # [5] [3]
  File "C:\Anaconda3\lib\ctypes__init__.py", line 364, in **getattr**
    func = self.**getitem**(name)
  File "C:\Anaconda3\lib\ctypes__init__.py", line 369, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'SHGetKnownFolderPath' not found

**Comment by silentquasar** [comment]
Ever come to a solution on this?

**Comment by brombeerberg** [comment]
Got a very similar error today while installing Anaconda2 4.3.1 and Anaconda2 4.3.0.1 on Windows XP:

```
...
SHGetKnownFolderPath = windll.shell32.SHGetKnownFolderPath # [5] [3]
 File `"C:\Programme\Anaconda2\lib\ctypes\__init__.py",` line 375, in __getattr__
 func = self.__getitem__(name)
 File "C:\Programme\Anaconda2\lib\ctypes\__init__.py", line 380, in __getitem__
 func = self._FuncPtr((name_or_ordinal, self))
 AttributeError: function 'SHGetKnownFolderPath' not found
```
After ignoring during the installation process I noticed that icons were missing and I couldn't start Spyder.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/menuinst#43

**Comment by akshiv12** [comment]
Any solution to this? 
'SHGetKnownFolderPath' is troubling me too.
