### ISSUE TITLE
Could not install R essentials

### ISSUE THREAD

**Issue by a-joyce** [conda/conda#3618]
conda install -c r r-essentials

Fetching package metadata ...Could not connect to https://conda.anaconda.org/r/noarch/
Could not connect to https://conda.anaconda.org/r/osx-64/
Could not connect to https://conda.anaconda.org/r/osx-64/
....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : osx-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 1.21.3
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : /Users/username/anaconda  (writable)
default environment : /Users/username/anaconda
   envs directories : /Users/username/anaconda/envs
      package cache : /Users/username/anaconda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /Users/username/anaconda/bin/conda install -c r r-essentials`

```
Traceback (most recent call last):
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
    prefix=prefix)
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
    for url in urls]
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
    res = f(*args, **kwargs)
  File "/Users/username/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
    raise CondaRuntimeError(msg)
CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /r/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x1065f2750>, 'Connection to conda.anaconda.org timed out. (connect timeout=3.05)')): https://conda.anaconda.org/r/osx-64/
```

**Comment by mingwandroid** [comment]
This looks like a transient connectivity problem. Can you try again please?

**Comment by oliyiyi** [comment]
this prob only exists  in China because of GFW

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
