### ISSUE TITLE
Conda breaks itself on update

### ISSUE THREAD

**Issue by pvanderlinden** [conda/conda#3619]
If you run `conda update conda` sometimes it breaks the whole anaconda installation:

```
>> conda update conda
Fetching package metadata .........
Solving package specifications: ..........
Warning: 8 possible package resolutions (only showing differing packages):
  - openssl-1.0.2h-1.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2h-1.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-27.2.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, requests-2.10.0-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2
  - openssl-1.0.2j-0.tar.bz2, requests-2.11.1-py35_0.tar.bz2, setuptools-23.0.0-py35_0.tar.bz2

Package plan for installation in environment /opt/anaconda3:

The following packages will be REMOVED:

    beautifulsoup4: 4.4.1-py35_0 
    openssl:        1.0.2j-0     
    requests:       2.11.1-py35_0
    setuptools:     27.2.0-py35_0
```

After that:

```
>> conda update conda-build
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda", line 4, in <module>
    import conda.cli
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/__init__.py", line 8, in <module>
    from .main import main  # NOQA
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 46, in <module>
    from ..base.context import context
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.url import urlparse, path_to_url
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/common/url.py", line 17, in <module>
    from requests.packages.urllib3.util.url import parse_url
ImportError: No module named 'requests'
``
```

**Comment by kalefranz** [comment]
This will no longer happen ever ever again with unlink-link transactions implemented in conda 4.3.
