### ISSUE TITLE
Error after creating .condarc

### ISSUE THREAD

**Issue by bilach** [conda/conda#3620]
I have created .condarc to explore its possibilities, after that any action regarding creating a virtualenv results in the following error:
`Current conda install:

```
           platform : win-32
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : not installed
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : c:\Miniconda2  (writable)
default environment : c:\Miniconda2
   envs directories : c:\Miniconda2\envs
      package cache : c:\Miniconda2\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/win-32/
                      https://repo.continuum.io/pkgs/pro/noarch/
                      https://repo.continuum.io/pkgs/msys2/win-32/
                      https://repo.continuum.io/pkgs/msys2/noarch/
        config file : c:\Miniconda2\.condarc
       offline mode : False
```

`$ c:\Miniconda2\Scripts\conda-script.py create -n test python`

```
Traceback (most recent call last):
  File "c:\Miniconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "c:\Miniconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "c:\Miniconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "c:\Miniconda2\lib\site-packages\conda\cli\install.py", line 425, in install
    append_env(prefix)
  File "c:\Miniconda2\lib\site-packages\conda\misc.py", line 275, in append_env
    os.mkdir(dir_path)
WindowsError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\dev\\virtualenv\\"C:\\Users\\belaln"\\.conda'`
```

.condarc file looks like this:
`show_channel_urls: True`

**Comment by tyler-thetyrant** [comment]
Please use the most recent version of conda.
`conda update conda` will do the job.
