### ISSUE TITLE
conda: an unexpected error has occurred

### ISSUE THREAD

**Issue by slideWXY** [conda/conda#3621]
Hi there, I was trying to install TensorFlow but I have a conda problem ...
I thing that's because I used brew command and also conda when I install python package.

MBP-de-mathieu:notebooks my_mac$ conda install TensorFlow

Traceback (most recent call last):
  File "/Users/my_mac/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 396, in get_info
    from conda.cli import conda_argparse
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 15, in <module>
    from ..install import dist2quad
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/install.py", line 51, in <module>
    from .models.channel import Channel
  File "/Users/my_mac/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 131, in <module>
    TOKEN_RE = re.compile(r'(/t/[a-z0-9A-Z-]+)?(\S*)?')
  File "/Users/my_mac/anaconda/lib/python2.7/re.py", line 190, in compile
    return _compile(pattern, flags)
  File "/Users/my_mac/anaconda/lib/python2.7/re.py", line 242, in _compile
    raise error, v # invalid expression
sre_constants.error: nothing to repeat

**Comment by JeroenMerks** [comment]
I have the exact same issue.
CentOS 7, Python 2.7 and Conda 4.2.7

**Comment by maraujo** [comment]
I have the exact issue:
Ubuntu 12.04.5 LTS
Python 2.7
Conda 4.2.7

**Comment by RuBiCK** [comment]
Same problem, I can't execute even `conda info` or just `conda`

RHEL 7.2
Python 2.7.5
Conda 4.2.7

**Comment by kalefranz** [comment]
Is anybody still having this issue after `conda update -c defaults conda` to conda version 4.3.17 or later?
