### ISSUE TITLE
unexpected error during conda update anaconda

### ISSUE THREAD

**Issue by davharris** [conda/conda#3623]
After typing `conda update anaconda` at the Bash terminal, I downloaded a bunch of packages and then got this:

```
Extracting packages ...
[      COMPLETE      ]|#####################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#####################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                               |  24%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/davidharris/anaconda/bin/conda", line 6, in <module>
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
  File "/Users/davidharris/anaconda/lib/python2.7/site-packages/conda/install.py", line 634, in link
  File "/Users/davidharris/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/davidharris/anaconda/lib/python2.7/site-packages/numpy/distutils/tests/f2py_ext'
```

I'd include my `conda info`, except I now get `-bash: /Users/davidharris/anaconda/bin/conda: No such file or directory` whenever I try running conda.

I'm on macOS Sierra, 10.12 (16A323).

**Comment by soapy1** [comment]
So first thing is to fix your conda. If you still have the anaconda installer script you can do a 
```
$ bash anaconda.sh -bfp /path/to/anaconda
```

For the permissions error, conda does not currently check permissions on files/folders before linking so if your user doesn't have write permissions on say `/Users/davidharris/anaconda` then conda just kind of barfs. So, could you check that you have write permissions on `site-packages` and `numpy` (I think those are the important ones in this case)

**Comment by davharris** [comment]
Thanks. I got things working by wiping and reinstalling.  I was just sending the traceback as a courtesy in case it was useful (as the error message suggested).  Feel free to close this if it's a known issue or if Continuum/Anaconda/conda doesn't want to worry about this particular kind of permissions problem.

**Comment by soapy1** [comment]
Cool, thank you!
