### ISSUE TITLE
qiime1.9.1 conda install error

### ISSUE THREAD

**Issue by xcheng33** [conda/conda#3626]
Could you help me solve the following install error when I tried to install Qiime 1.9.1? Thank you.

An unexpected error has occurred, please consider sending the###############                                                                                                                      |  31%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/xicheng/miniconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/install.py", line 859, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "/home/xicheng/miniconda3/lib/python3.5/site-packages/conda/install.py", line 237, in exp_backoff_fn
    return fn(*args)
PermissionError: [Errno 13] Permission denied: '/home/xicheng/miniconda3/pkgs/numpy-1.10.4-py27_2.tmp' -> '/home/xicheng/miniconda3/pkgs/numpy-1.10.4-py27_2'

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed with transactions in 4.3 is conda removing itself during a failed install/update operation.
