### ISSUE TITLE
conda environment change 

### ISSUE THREAD

**Issue by tzrtzr000** [conda/conda#3628]
I am trying to install the beautiful soup package and typed the following command:

\\Python\jupyter notebook>conda install -c asmeurer beautiful-soup=4.3.2
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment \\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    beautiful-soup-4.3.2       |           py27_1         109 KB
    pycosat-0.6.0              |           py27_1          46 KB
    pyyaml-3.10                |           py27_1         173 KB
    conda-3.2.0a1              |           py27_0         112 KB  asmeurer
    ------------------------------------------------------------
                                           Total:         440 KB

The following NEW packages will be INSTALLED:

    beautiful-soup: 4.3.2-py27_1

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:          4.2.9-py27_0 --> 3.2.0a1-py27_0 asmeurer

The following packages will be DOWNGRADED due to dependency conflicts:

    pycosat:        0.6.1-py27_1 --> 0.6.0-py27_1
    pyyaml:         3.11-py27_4  --> 3.10-py27_1

Proceed ([y]/n)? y

Fetching packages ...
beautiful-soup 100% |###############################| Time: 0:00:00 977.33 kB/s
pycosat-0.6.0- 100% |###############################| Time: 0:00:00 665.00 kB/s
pyyaml-3.10-py 100% |###############################| Time: 0:00:00   1.15 MB/s
conda-3.2.0a1- 100% |###############################| Time: 0:00:00 940.36 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

but then it did not notice that the conda version has changed and executed the following command:

\\Python\jupyter notebook>conda install lxml
Error: No packages found matching: conda-env >=2.6

\\Python\jupyter notebook>conda install -c r r-xml=3.98_1.4
Error: No packages found matching: m2w64-libxml2

\\Python\jupyter notebook>conda install xml=3.98_1.4
Error: No packages found matching: xml 3.98_1.4*

\\Python\jupyter notebook>conda install -c r r-xml=3.98_1.4
Error: No packages found matching: m2w64-libxml2

\\Python\jupyter notebook>conda install -c anaconda lxml=3.6.4
Error: No packages found matching: conda-env <2.5

C:\Users\Zirui Tao\OneDrive for Business\Python\jupyter notebook>conda install requests
Error: No packages found matching: conda-env >=2.6

conda keeps saying "no packages found matching no matter what I want to install"

and then when I want to open the jupyter notebook, it pops the following error  

\\Python\jupyter notebook>jupyter notebook
[W 00:18:13.249 NotebookApp] Unrecognized JSON config file version, assuming version 1
Traceback (most recent call last):
  File "\\Anaconda2\Scripts\jupyter-notebook-script.py", line 5, in <module>
    sys.exit(notebook.notebookapp.main())
  File "\\Anaconda2\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "\\Anaconda2\lib\site-packages\traitlets\config\application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "\\Anaconda2\lib\site-packages\traitlets\config\application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "\\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "\\Anaconda2\lib\site-packages\notebook\notebookapp.py", line 837, in init_configurables
    parent=self,
  File "\\Anaconda2\lib\site-packages\nb_conda_kernels\manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "\\Anaconda2\lib\site-packages\nb_conda_kernels\manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "\\Anaconda2\lib\site-packages\nb_conda_kernels\manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "\\Anaconda2\lib\subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "\\Anaconda2\lib\subprocess.py", line 711, in __init__
    errread, errwrite)
  File "\\Anaconda2\lib\subprocess.py", line 959, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

I guess it is because I installed the new version of conda so that some environment (or channel?) has changed so conda cannot locate the specific file. Then I tried to re-install the previous version that I had but It 
also fails to execute with following error:

\\Python\jupyter notebook>conda update conda
Error: No packages found matching: conda-env >=2.6

I tried to google the problem but it seems like there is no similar cases to this one
I am a beginner of learning python and please help me out. Thank you very much!

**Comment by kalefranz** [comment]
conda config --remove channels asmeurer

Otherwise you're being downgraded to a *very* old version of conda.
