### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by muratetm** [conda/conda#3636]
Traceback (most recent call last):
  File "/home/mmuratet/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
    link(state['prefix'], arg, index=state['index'])
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/install.py", line 634, in link
    os.makedirs(dst_dir)
  File "/home/mmuratet/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/mmuratet/anaconda/lib/python2.7/site-packages/conda/_vendor'

conda info does not work. Apparently the install has broken my python

**Comment by muratetm** [comment]
~/anaconda/bin/conda info
Current conda install:

             platform : linux-64
        conda version : 4.0.6
  conda-build version : 1.8.2
       python version : 2.7.12.final.0
     requests version : 2.9.1
     root environment : /home/mmuratet/anaconda  (writable)
  default environment : /home/mmuratet/anaconda
     envs directories : /home/mmuratet/anaconda/envs
        package cache : /home/mmuratet/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

**Comment by muratetm** [comment]
Install process rewrote conda header, which is what broke it

**Comment by tyler-thetyrant** [comment]
Please use the most recent version of conda. 
You might have to reinstall miniconda.
