### ISSUE TITLE
`conda install basemap` fails with stacktrace

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3643]
Just following instructions in the error output of my attempt to do `conda install basemap`.  Trace below.

Some details: OS X, Anaconda 4.2, root environment, Conda 4.2.9, working offline (wifi off, no public internet connection)

``` bash
$ conda install basemap
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/osx-64/
Could not connect to https://conda.anaconda.org/r/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/osx-64/
Could not connect to https://conda.anaconda.org/t/CQgCcFM1Mfma/anaconda-mosaic/osx-64/
Could not connect to https://conda.anaconda.org/r/osx-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://conda.anaconda.org/t/CQgCcFM1Mfma/anaconda-mosaic/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://conda.anaconda.org/r/osx-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64/
                          https://conda.anaconda.org/r/noarch/
                          https://conda.anaconda.org/t/<TOKEN>/anaconda-mosaic/osx-64/
                          https://conda.anaconda.org/t/<TOKEN>/anaconda-mosaic/noarch/
                          https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/bin/conda install basemap`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error:
    HTTPSConnectionPool(host='conda.anaconda.org', port=443): 
    Max retries exceeded with url: /t/<TOKEN>/r/osx-64/repodata.json
    (Caused by 
        NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection
        object at 0x10d0706d0>: 
        Failed to establish a new connection:
        [Errno 8] nodename nor servname provided, or not known',)
    ):
    https://conda.anaconda.org/r/osx-64/
```

After this failure (and in order to report it) I went online and the command worked just fine.  Here is a trace of that:

``` bash
$ conda install basemap
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /Users/ijstokes/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    basemap-1.0.7              |      np111py27_0       118.5 MB

The following NEW packages will be INSTALLED:

    basemap: 1.0.7-np111py27_0

Proceed ([y]/n)? y

Fetching packages ...
basemap-1.0.7- 100% |######################| Time: 0:03:43 556.65 kB/s
Extracting packages ...
[      COMPLETE      ]|########################| 100%
Linking packages ...
[      COMPLETE      ]|########################| 100%
```

**Comment by kalefranz** [comment]
fixed in 4.2.11
