### ISSUE TITLE
OSError: [Errno 39] Directory not empty on python2.7 conda install

### ISSUE THREAD

**Issue by bogemad** [conda/conda#3647]
Running "conda create -y -n env_name python=2.7" causes this error:

Traceback (most recent call last):
  File ".mc/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/install.py", line 859, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "/panfs/panspermia/119529/bact_vcp/.mc/lib/python3.5/site-packages/conda/install.py", line 237, in exp_backoff_fn
    return fn(*args)
OSError: [Errno 39] Directory not empty: '/panfs/panspermia/119529/bact_vcp/.mc/pkgs/zlib-1.2.8-3.tmp' -> '/panfs/panspermia/119529/bact_vcp/.mc/pkgs/zlib-1.2.8-3'

From google searches it appears to be a shutil.tree error? 

rm -r /panfs/panspermia/119529/bact_vcp/.mc/pkgs/zlib-1.2.8-3 resolves the issue so don't think it's a permission problem. 

Only happens when trying to install python 2, python 3 is fine.

**Comment by soapy1** [comment]
I can't seem to reproduce this issue on the newest version of conda. Could you include the output of `conda info`

**Comment by bogemad** [comment]
Haven't been able to reproduce it as well. I'll close.
