### ISSUE TITLE
installing salmon fails

### ISSUE THREAD

**Issue by ramezrawas** [conda/conda#3649]
Current conda install:

```
           platform : linux-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : not installed
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : /home/ramez/miniconda2  (writable)
default environment : /home/ramez/miniconda2
   envs directories : /home/ramez/miniconda2/envs
      package cache : /home/ramez/miniconda2/pkgs
       channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                      https://conda.anaconda.org/bioconda/noarch/
                      https://conda.anaconda.org/r/linux-64/
                      https://conda.anaconda.org/r/noarch/
                      https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : /home/ramez/.condarc
       offline mode : False
```

`$ /home/ramez/miniconda2/bin/conda install salmon`

```
Traceback (most recent call last):
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
    prefix=prefix)
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 282, in fetch_index
    for url in urls]
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
    res = f(*args, **kwargs)
  File "/home/ramez/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
    raise CondaRuntimeError(msg)
CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out.: https://conda.anaconda.org/bioconda/linux-64/
```

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
