### ISSUE TITLE
error while searching for `notebook`

### ISSUE THREAD

**Issue by lizaclark** [conda/conda#3655]
I recently installed `ipykernel`, after which, commands
`ipython notebook` produced "ImportError: No module named 'notebook'", and
`jupyter notebook` produced "jupyter: 'notebook' is not a Jupyter command".
So, I ran `conda search notebook` and got the following message:

> Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.14.1
         python version : 3.4.5.final.0
       requests version : 2.9.1
       root environment : /usr1/eclark/anaconda3  (writable)
    default environment : /usr1/eclark/anaconda3
       envs directories : /usr1/eclark/anaconda3/envs
          package cache : /usr1/eclark/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/anaconda/linux-64/
                          https://conda.anaconda.org/anaconda/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /nfs/jet/home/eclark/.condarc
           offline mode : False

`$ /usr1/eclark/anaconda3/bin/conda search notebook`

    Traceback (most recent call last):
      File "/usr1/eclark/anaconda3/lib/python3.4/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr1/eclark/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/usr1/eclark/anaconda3/lib/python3.4/site-packages/conda/cli/main_search.py", line 126, in execute
        execute_search(args, parser)
      File "/usr1/eclark/anaconda3/lib/python3.4/site-packages/conda/cli/main_search.py", line 268, in execute_search
        Channel(pkg.channel).canonical_name,
      File "/usr1/eclark/anaconda3/lib/python3.4/site-packages/conda/models/channel.py", line 44, in __call__
        elif value.endswith('.tar.bz2'):
    TypeError: endswith first arg must be bytes or a tuple of bytes, not str

**Comment by kalefranz** [comment]
Thanks for the report!
