### ISSUE TITLE
conda uninstall gives ValueError: Malformed version string '.post': empty version component.

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda#3659]
I got this with [bluesky](https://github.com/NSLS-II/bluesky)

```
conda uninstall bluesky
Fetching package metadata ...................
Solving package specifications: .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/christopher/mc/envs/dp_dev3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/cli/main_remove.py", line 158, in execute
    force=args.force, pinned=args.pinned)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/plan.py", line 524, in remove_actions
    nlinked = {r.package_name(fn): fn[:-8] for fn in r.remove(specs, linked)}
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 969, in remove
    pkgs = self.solve(specs)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 981, in solve
    dists, new_specs = self.get_dists(specs)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 584, in get_dists
    if not full_prune(specs, optional, features):
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 544, in full_prune
    if not self.match_fast(ms, fkey):
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 607, in match_fast
    return ms.match_fast(rec['version'], rec['build'])
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/resolve.py", line 170, in _match_version
    return self.version.match(version)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/version.py", line 287, in veval_match_
    return self.op(VersionOrder(vspec), self.cmp)
  File "/home/christopher/mc/lib/python2.7/site-packages/conda/version.py", line 182, in __init__
    raise ValueError(message + "empty version component.")
ValueError: Malformed version string '.post0': empty version component.
```
May be related to #1774.
@danielballan

**Comment by CJ-Wright** [comment]
Addressed in #1774
