### ISSUE TITLE
conda install opencv3 error on win10

### ISSUE THREAD

**Issue by ehsaneshaghi** [conda/conda#3660]
I am trying to install opencv3 with `conda install -c menpo opencv3=3.1.0` command. my OS is win10 64 bit and i have both anaconda 2 and 3 installed. but i used `activate C:\Users\ehsan\Anaconda3` to switch to anaconda 3 which was not the default. I got the following error.

**Traceback**:

```
menuinst-1.4.2 100% |###############################| Time: 0:00:01  58.71 kB/s
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00  20.35 kB/s
mkl-11.3.3-1.t 100% |###############################| Time: 0:16:36 115.76 kB/s
vs2015_runtime 100% |###############################| Time: 0:00:17 115.28 kB/s
An unexpected error has occurred, please consider sending the:02:23 107.25 kB/s
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 226, in _error_catcher
    yield
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 301, in read
    data = self._fp.read(amt)
  File "C:\Users\ehsan\Anaconda3\lib\http\client.py", line 433, in read
    n = self.readinto(b)
  File "C:\Users\ehsan\Anaconda3\lib\http\client.py", line 473, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\ehsan\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\ehsan\Anaconda3\lib\ssl.py", line 924, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\ehsan\Anaconda3\lib\ssl.py", line 786, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\ehsan\Anaconda3\lib\ssl.py", line 570, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ehsan\Anaconda3\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\cli\main.py", line 180, in args_func
    args.func(args, p)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\cli\install.py", line 423, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\plan.py", line 538, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
    cmd(state, arg)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\conda\fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 311, in read
    flush_decoder = True
  File "C:\Users\ehsan\Anaconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\ehsan\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)", ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
```

**conda info:** 

```
Current conda install:

             platform : win-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Users\ehsan\Anaconda3  (writable)
  default environment : C:\Users\ehsan\Anaconda3
     envs directories : C:\Users\ehsan\Anaconda3\envs
        package cache : C:\Users\ehsan\Anaconda3\pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/win-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\ehsan\.condarc
    is foreign system : False`
```

**Comment by kalefranz** [comment]
Intermittent HTTP issue.
