### ISSUE TITLE
installing conda opencv for intelpython27

### ISSUE THREAD

**Issue by OregonWookie** [conda/conda#3665]
Traceback (most recent call last):
  File "/opt/intel/intelpython27/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/opt/intel/intelpython27/lib/python2.7/site-packages/conda/install.py", line 1061, in link
    os.makedirs(dst_dir)
  File "/opt/intel/intelpython27/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/intel/intelpython27/lib/python2.7/site-packages/conda/_vendor'

**Comment by OregonWookie** [comment]
When I change the permissions in the problem directory, I am presented with this error: 
conda install --channel https://conda.binstar.org/menpo --yes opencv
-bash: /opt/intel/intelpython27/bin/conda: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory

The directory /opt/anaconda1anaconda2anaconda3/bin/python looks suspect, it does not exist at any rate.

**Comment by kalefranz** [comment]
The permissions error on the directory caused conda to fail in the middle of an operation, which borked your whole conda install.  We're fixing this (at least preventing conda from getting in a state like this) in the next major conda release (conda 4.3).

**Comment by kalefranz** [comment]
Fixed with conda 4.3.
