### ISSUE TITLE
matplotlib fails to load with libfreetype.6.dylib

### ISSUE THREAD

**Issue by hawkrobe** [conda/conda#367]
Just installed anaconda for the first time, starting an environment with python 2.7.6 and conda 2.2.1. When I try to load matplotlib.pyplot, it appears that the appropriate libfreetype library is not included. I'm running OS X 10.9, which might be contributing to the problem. The full import statement and error message is below.

```
Python 2.7.6 |Anaconda 1.8.0 (x86_64)| (default, Nov 11 2013, 10:49:09) 
[GCC 4.0.1 (Apple Inc. build 5493)] on darwin
>>> import matplotlib.pyplot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/lib/python2.7/site-packages/matplotlib/pyplot.py", line 24, in <module>
    import matplotlib.colorbar
  File "//anaconda/lib/python2.7/site-packages/matplotlib/colorbar.py", line 29, in <module>
    import matplotlib.collections as collections
  File "//anaconda/lib/python2.7/site-packages/matplotlib/collections.py", line 23, in <module>
    import matplotlib.backend_bases as backend_bases
  File "//anaconda/lib/python2.7/site-packages/matplotlib/backend_bases.py", line 50, in <module>
    import matplotlib.textpath as textpath
  File "//anaconda/lib/python2.7/site-packages/matplotlib/textpath.py", line 11, in <module>
    import matplotlib.font_manager as font_manager
  File "//anaconda/lib/python2.7/site-packages/matplotlib/font_manager.py", line 53, in <module>
    from matplotlib import ft2font
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/matplotlib/ft2font.so, 2): Library not loaded: @loader_path/../../../libfreetype.6.dylib
  Referenced from: //anaconda/lib/python2.7/site-packages/matplotlib/ft2font.so
  Reason: Incompatible library version: ft2font.so requires version 16.0.0 or later, but libfreetype.6.dylib provides version 15.0.0
```

**Comment by mcstro** [comment]
I ran into this error, but in my case, I'm thinking it's not an issue with conda, but with the operator. In particular, I suspect it's because I committed some pretty egregious sins with respect to my graphics libraries while compiling a software project. See my response at https://stackoverflow.com/a/49415914/2840265 . Hopefully some of this is relevant or enlightening. Also LOL I just looked at the time stamps on these...I'm apparently 4 years late to the game here...
