### ISSUE TITLE
conda skeleton broken for github urls

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#3672]
```
λ conda skeleton pypi requests-negotiate-sspi
Warning, the following versions were found for requests-negotiate-sspi
0.1.0
0.1.1
0.1.2
0.1.3
0.2.0
0.2.1
0.2.2
Using 0.2.2
Use --version to specify a different version.
Using url https://github.com/brandond/requests-negotiate-sspi/tarball/0.2.2 (0 B) for requests-negotiate-sspi.
Downloading requests-negotiate-sspi
Unpacking requests-negotiate-sspi...
Traceback (most recent call last):
  File "C:\Python\Scripts\conda-skeleton-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "C:\Python\lib\site-packages\conda_build\cli\main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "C:\Python\lib\site-packages\conda_build\cli\main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "C:\Python\lib\site-packages\conda_build\api.py", line 199, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "C:\Python\lib\site-packages\conda_build\skeletons\pypi.py", line 406, in skeletonize
    noprompt, packages, config=config, setup_options=setup_options)
  File "C:\Python\lib\site-packages\conda_build\skeletons\pypi.py", line 664, in get_package_metadata
    config=config)
  File "C:\Python\lib\site-packages\conda_build\skeletons\pypi.py", line 919, in get_pkginfo
    unpack(join(config.src_cache, filename), tempdir)
  File "C:\Python\lib\site-packages\conda_build\skeletons\pypi.py", line 853, in unpack
    raise Exception("not a valid source: %s" % src_path)
Exception: not a valid source: C:\Python\conda-bld\src_cache\0.2.2
```
Other packages seem to work - the difference I think is that there is no tar.gz blob for windows so it tries to download a tarball from the github url which fails

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1474
