### ISSUE TITLE
conda install wrong version of jedi?

### ISSUE THREAD

**Issue by alexbovet** [conda/conda#3678]
Hi all,

In a new environment created with the defaults channel, conda says it installed jedi 0.9.0 but an error arises when I try to import it. 
Looking at the`__init__.py` inside the jedi folder, " `__version__ = '0.8.1`'". 
( in `~/anaconda3/envs/env_name/lib/python3.5/site-packages/jedi/__init__.py`)

I wonder if there is something broken with my installation... 

Here are more information:

created environment with : 

`conda create -n env_name python=3 anaconda`

conda info gives:

```
               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.21.5
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /home/alex/anaconda3  (writable)
    default environment : /home/alex/anaconda3/envs/env_name
       envs directories : /home/alex/anaconda3/envs
          package cache : /home/alex/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/alex/anaconda3/.condarc
           offline mode : False
```

error when importing jedi:

```
>>> import jedi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/alex/anaconda3/envs/env_name/lib/python3.5/site-packages/jedi/__init__.py", line 39, in <module>
    from jedi.api import Script, Interpreter, NotFoundError, set_debug_function
  File "/home/alex/anaconda3/envs/env_name/lib/python3.5/site-packages/jedi/api/__init__.py", line 18, in <module>
    from jedi.parser import Parser
  File "/home/alex/anaconda3/envs/env_name/lib/python3.5/site-packages/jedi/parser/__init__.py", line 23, in <module>
    from jedi.parser import representation as pr
ImportError: cannot import name 'representation'
```

conda list:

```
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.3.0                    py35_0    defaults
alabaster                 0.7.9                    py35_0    defaults
anaconda                  custom                   py35_0    defaults
anaconda-clean            1.0.0                    py35_0    defaults
anaconda-client           1.5.1                    py35_0    defaults
anaconda-navigator        1.3.2                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astroid                   1.4.7                    py35_0    defaults
astropy                   1.2.1               np111py35_0    defaults
babel                     2.3.4                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.5.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.3                   py35_0    defaults
boto                      2.42.0                   py35_0    defaults
bottleneck                1.1.0               np111py35_0    defaults
cairo                     1.12.18                       6    defaults
cffi                      1.8.3                    py35_0    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
configobj                 5.0.6                    py35_0    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.5.2                    py35_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24.1                   py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.11.1                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
dbus                      1.10.10                       0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py35_1    defaults
filelock                  2.0.6                    py35_0    defaults
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
fontconfig                2.11.1                        6    defaults
freetype                  2.5.5                         1    defaults
get_terminal_size         1.0.0                    py35_0    defaults
gevent                    1.1.2                    py35_0    defaults
glib                      2.43.0                        1    defaults
greenlet                  0.4.10                   py35_0    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.6.0               np111py35_2    defaults
harfbuzz                  0.9.39                        1    defaults
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py35_1    defaults
icu                       54.1                          0    defaults
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.5.0                    py35_0    defaults
ipython                   5.1.0                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                5.2.2                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3                      py35_0    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
jpeg                      8d                            2    defaults
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.4.0                    py35_0    defaults
jupyter_console           5.0.0                    py35_0    defaults
jupyter_core              4.2.0                    py35_0    defaults
lazy-object-proxy         1.2.1                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libffi                    3.2.1                         0    defaults
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
libpng                    1.6.22                        0    defaults
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         2    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        0    defaults
llvmlite                  0.14.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.4                    py35_0    defaults
markupsafe                0.23                     py35_2    defaults
matplotlib                1.5.3               np111py35_0    defaults
mistune                   0.7.3                    py35_0    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py35_2    defaults
mpmath                    0.19                     py35_1    defaults
multipledispatch          0.4.9                    py35_0    defaults
nb_anacondacloud          1.2.0                    py35_0    defaults
nb_conda                  2.0.0                    py35_0    defaults
nb_conda_kernels          2.0.0                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.1.0                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.3                    py35_0    defaults
numba                     0.29.0              np111py35_0    defaults
numexpr                   2.6.1               np111py35_0    defaults
numpy                     1.11.2                   py35_0    defaults
odo                       0.5.0                    py35_1    defaults
openpyxl                  2.4.0                    py35_0    defaults
openssl                   1.0.2j                        0    defaults
pandas                    0.19.0              np111py35_0    defaults
partd                     0.3.6                    py35_0    defaults
patchelf                  0.9                           0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pep8                      1.7.0                    py35_0    defaults
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.7.4                    py35_0    defaults
pillow                    3.4.1                    py35_0    defaults
pip                       8.1.2                    py35_0    defaults
pixman                    0.32.6                        0    defaults
pkginfo                   1.3.2                    py35_0    defaults
ply                       3.9                      py35_0    defaults
prompt_toolkit            1.0.3                    py35_0    defaults
psutil                    4.3.1                    py35_0    defaults
ptyprocess                0.5.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyflakes                  1.3.0                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pylint                    1.5.4                    py35_1    defaults
pyopenssl                 16.0.0                   py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      5.6.0                    py35_0    defaults
pytables                  3.2.3.1             np111py35_0    defaults
pytest                    3.0.3                    py35_0    defaults
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
pytz                      2016.7                   py35_0    defaults
pyyaml                    3.12                     py35_0    defaults
pyzmq                     16.0.0                   py35_0    defaults
qt                        5.6.0                         1    defaults
qtawesome                 0.3.3                    py35_0    defaults
qtconsole                 4.2.1                    py35_1    defaults
qtpy                      1.1.2                    py35_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py35_0    defaults
requests                  2.11.1                   py35_0    defaults
rope                      0.9.4                    py35_1    defaults
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.18                np111py35_0    defaults
scipy                     0.18.1              np111py35_0    defaults
setuptools                27.2.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.8                    py35_0    defaults
spyder                    3.0.1                    py35_0    defaults
sqlalchemy                1.1.2                    py35_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
terminado                 0.6                      py35_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.4.2                    py35_0    defaults
traitlets                 4.3.1                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.11                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
wrapt                     1.10.8                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.3                    py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.5                         0    defaults
zlib                      1.2.8                         3    defaults

```

**Comment by kalefranz** [comment]
How about `conda list -n env_name`?

**Comment by alexbovet** [comment]
It gives the same list.

**Comment by alexbovet** [comment]
Installing jedi with pip instead solves it. But this is still an unexpected behavior.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1664
