### ISSUE TITLE
Unable to install opencv3 through conda

### ISSUE THREAD

**Issue by FlexBrendt** [conda/conda#3693]
I'm not able to install OpenCV3 through conda on windows 10.
This error comes flashing:
`$ C:\Users\gamem\Anaconda3\Scripts\conda-script.py install -c menpo opencv3=3.1.0`

```
Traceback (most recent call last):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
    yield
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
    data = self._fp.read(amt)
  File "C:\Users\gamem\Anaconda3\lib\http\client.py", line 448, in read
    n = self.readinto(b)
  File "C:\Users\gamem\Anaconda3\lib\http\client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "C:\Users\gamem\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\gamem\Anaconda3\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\gamem\Anaconda3\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Users\gamem\Anaconda3\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
    flush_decoder = True
  File "C:\Users\gamem\Anaconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
    for chunk in resp.iter_content(2**14):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
    raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Users\\gamem\\Anaconda3\\pkgs\\opencv3-3.1.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
    raise CondaSystemExit('Exiting', e)
  File "C:\Users\gamem\Anaconda3\lib\contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
    yield
  File "C:\Users\gamem\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Users\\gamem\\Anaconda3\\pkgs\\opencv3-3.1.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

**Comment by kalefranz** [comment]
We've changed some of our hosting infrastructure.  Please try again, and file a new issue if you problem persists.

**Comment by mjc14** [comment]
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/mjc14/miniconda2/pkgs/pytorch-0.1.7-py27_2.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
