### ISSUE TITLE
error in : Create your qiime1 environment and install QIIME

### ISSUE THREAD

**Issue by shellfishabc** [conda/conda#3707]
## I am trying to create a "qiime1" environment and install QIIME, but got following errors.  any ideas? Thanks!

An unexpected error has occurred, please consider sending the0:12:24  25.96 kB/s
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
    yield
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/home/zhanghb/miniconda3/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/home/zhanghb/miniconda3/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/home/zhanghb/miniconda3/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/home/zhanghb/miniconda3/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/home/zhanghb/miniconda3/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/home/zhanghb/miniconda3/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zhanghb/miniconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 338, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 423, in download
    chunk = resp.raw.read(2**14)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/home/zhanghb/miniconda3/lib/python3.5/contextlib.py", line 77, in **exit**
    self.gen.throw(type, value, traceback)
  File "/home/zhanghb/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 246, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

[zhanghb@localhost ~]$ conda info
Current conda install:

```
         platform : linux-64
    conda version : 4.1.11
conda-env version : 2.5.2
```

  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/zhanghb/miniconda3  (writable)
  default environment : /home/zhanghb/miniconda3
     envs directories : /home/zhanghb/miniconda3/envs
        package cache : /home/zhanghb/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by soapy1** [comment]
@shellfishabc what command are you running to produce this output?
