### ISSUE TITLE
Cannot download Packages

### ISSUE THREAD

**Issue by SagesWang** [conda/conda#3711]
Current conda install:

```
           platform : linux-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : not installed
     python version : 3.5.2.final.0
   requests version : 2.10.0
   root environment : /home/wangpd/miniconda3  (writable)
default environment : /home/wangpd/miniconda3
   envs directories : /home/wangpd/miniconda3/envs
      package cache : /home/wangpd/miniconda3/pkgs
       channel URLs : https://conda.anaconda.org/bioconda/linux-64/
                      https://conda.anaconda.org/bioconda/noarch/
                      https://conda.anaconda.org/conda-forge/linux-64/
                      https://conda.anaconda.org/conda-forge/noarch/
                      https://conda.anaconda.org/r/linux-64/
                      https://conda.anaconda.org/r/noarch/
                      https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : /home/wangpd/.condarc
       offline mode : False
```

`$ /home/wangpd/miniconda3/bin/conda install blast`

```
Traceback (most recent call last):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
    yield
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 310, in read
    data = self._fp.read(amt)
  File "/home/wangpd/miniconda3/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/home/wangpd/miniconda3/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/home/wangpd/miniconda3/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/home/wangpd/miniconda3/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/home/wangpd/miniconda3/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/home/wangpd/miniconda3/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/models.py", line 664, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 353, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 320, in read
    flush_decoder = True
  File "/home/wangpd/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 419, in download
    for chunk in resp.iter_content(2**14):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/requests/models.py", line 671, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
    cmd(state, arg)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 438, in download
    raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/home/wangpd/miniconda3/pkgs/icu-56.1-4.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
    raise CondaSystemExit('Exiting', e)
  File "/home/wangpd/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
    yield
  File "/home/wangpd/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/home/wangpd/miniconda3/pkgs/icu-56.1-4.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
