### ISSUE TITLE
failure for conda update --all

### ISSUE THREAD

**Issue by DheerajAgarwal** [conda/conda#3715]
Hi,

I face issues when I try to update all packages using   

    conda update --all

however all packages if updated individually work fine. Below is the error log

    Extracting packages ...
    An unexpected error has occurred.                                        |   0%
    Please consider posting the following information to the
    conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
    Current conda install:
               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : C:\Users\ouj070\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\ouj070\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\envs

          package cache : C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\pkgs

           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False  
`$ C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py update --all`
   
    Traceback (most recent call last):
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 803, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "C:\Users\ouj070\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\disk.py", line 152, in exp_backoff_fn
        result = fn(*args, **kwargs)
    PermissionError: [WinError 5] Access is denied: 'C:\\Users\\ouj070\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\icu-57.1-vc14_0.tmp' -> 'C:\\Users\\ouj070\\
AppData\\Local\\Continuum\\Anaconda3\\pkgs\\icu-57.1-vc14_0'

**Comment by kalefranz** [comment]
Thanks for the report. This is a windows file locking issue.  Can blame interactions with virus scanners and backup processes.  We have a fix planned, but it's a few months off.
