### ISSUE TITLE
conda create failure

### ISSUE THREAD

**Issue by stevecassidy** [conda/conda#3718]
Current conda install:

```
           platform : osx-64
      conda version : 4.2.9
   conda is private : False
  conda-env version : 4.2.9
conda-build version : 2.0.0
     python version : 2.7.12.final.0
   requests version : 2.10.0
   root environment : /Users/steve/miniconda2  (writable)
default environment : /Users/steve/miniconda2
   envs directories : /Users/steve/miniconda2/envs
      package cache : /Users/steve/miniconda2/pkgs
       channel URLs : https://conda.anaconda.org/bioconda/osx-64/
                      https://conda.anaconda.org/bioconda/noarch/
                      https://conda.anaconda.org/r/osx-64/
                      https://conda.anaconda.org/r/noarch/
                      https://repo.continuum.io/pkgs/free/osx-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/osx-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : /Users/steve/.condarc
       offline mode : False
```

`$ /Users/steve/miniconda2/bin/conda create --name formantworkflow -c bioconda numpy matplotlib rpy2 tgt`

```
Traceback (most recent call last):
  File "/Users/steve/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/steve/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/Users/steve/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/Users/steve/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
  File "/Users/steve/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
    return text_type(self.message % self._kwargs)
TypeError: a float is required
```

**Comment by kalefranz** [comment]
I kept this open and marked as blocking because I thought I could fairly easily add python2 exception chaining.  Turns out implementation is going to be more invasive.  It probably won't make it into a 4.2.x release.

The ticket to track this is now https://github.com/conda/conda/issues/3787
