### ISSUE TITLE
No module named 'win32api' 

### ISSUE THREAD

**Issue by stmax82** [conda/conda#3722]
The following fails with the error "ImportError: No module named 'win32api'":

Win 10 x64, conda 4.2.9

```
C:\temp>conda create -p pyenv_ladkjf python=3.4 ipython-notebook
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\temp\pyenv_ladkjf:

The following NEW packages will be INSTALLED:

    backports_abc:       0.4-py34_0
    colorama:            0.3.7-py34_0
    decorator:           4.0.10-py34_0
    entrypoints:         0.2.2-py34_0
    ipykernel:           4.5.0-py34_0
    ipython:             5.1.0-py34_0
    ipython-notebook:    4.0.4-py34_3
    ipython_genutils:    0.1.0-py34_0
    jinja2:              2.8-py34_1
    jsonschema:          2.5.1-py34_0
    jupyter_client:      4.4.0-py34_0
    jupyter_core:        4.2.0-py34_0
    markupsafe:          0.23-py34_2
    mistune:             0.7.3-py34_0
    nbconvert:           4.2.0-py34_0
    nbformat:            4.1.0-py34_0
    notebook:            4.2.3-py34_0
    path.py:             8.2.1-py34_0
    pickleshare:         0.7.4-py34_0
    pip:                 8.1.2-py34_0
    prompt_toolkit:      1.0.3-py34_0
    pygments:            2.1.3-py34_0
    python:              3.4.5-0
    pyzmq:               16.0.0-py34_0
    setuptools:          27.2.0-py34_1
    simplegeneric:       0.8.1-py34_1
    six:                 1.10.0-py34_0
    tornado:             4.4.2-py34_0
    traitlets:           4.3.1-py34_0
    vs2010_runtime:      10.00.40219.1-2
    wcwidth:             0.1.7-py34_0
    wheel:               0.29.0-py34_0
    win_unicode_console: 0.5-py34_0

Proceed ([y]/n)? y

Linking packages ...
menuinst Exception:Traceback (most recent call last):#######             |  75%
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 459, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Miniconda3\lib\site-packages\menuinst\__init__.py", line 57, in install
    "import menuinst; menuinst.install(%r, %r, %r)" % (path, bool(remove), prefix)])
  File "C:\Miniconda3\lib\site-packages\menuinst\win_elevate.py", line 41, in runAsAdmin
    import win32api, win32con, win32event, win32process
ImportError: No module named 'win32api'
menuinst Exception:Traceback (most recent call last):################    |  93%
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 459, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Miniconda3\lib\site-packages\menuinst\__init__.py", line 57, in install
    "import menuinst; menuinst.install(%r, %r, %r)" % (path, bool(remove), prefix)])
  File "C:\Miniconda3\lib\site-packages\menuinst\win_elevate.py", line 41, in runAsAdmin
    import win32api, win32con, win32event, win32process
ImportError: No module named 'win32api'
menuinst Exception:Traceback (most recent call last):##################  |  96%
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 459, in mk_menus
    menuinst.install(join(prefix, f), remove, prefix)
  File "C:\Miniconda3\lib\site-packages\menuinst\__init__.py", line 57, in install
    "import menuinst; menuinst.install(%r, %r, %r)" % (path, bool(remove), prefix)])
  File "C:\Miniconda3\lib\site-packages\menuinst\win_elevate.py", line 41, in runAsAdmin
    import win32api, win32con, win32event, win32process
ImportError: No module named 'win32api'
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate C:\temp\pyenv_ladkjf
#
# To deactivate this environment, use:
# > deactivate C:\temp\pyenv_ladkjf
#
# * for power-users using bash, you must source
#


C:\temp>
```

**Comment by kalefranz** [comment]
hey @mingwandroid @msarahan any hints here?

@stmax82 What's your `conda info`?

**Comment by msarahan** [comment]
That comes with pywin32, which I thought we shipped with miniconda and anaconda.  I'm locally installing and seeing that it isn't there, though with a miniconda installer. =(

@ilanschnell, we need to add this to all Windows installers.

**Comment by ilanschnell** [comment]
`pywin32` is part of Anaconda on Windows, but not Miniconda.

**Comment by ilanschnell** [comment]
It looks like `menuinst` is missing `pywin32` as a dependency on Windows.

**Comment by msarahan** [comment]
Seems like menuinst needs to add that dependency and be rebuilt.  I can't do that until Thursday.  If anyone can do it sooner, please do.

We'll need new miniconda installers for this (obviously) - 4.2.x miniconda?

**Comment by ilanschnell** [comment]
I've just uploaded new builds of menuinst 1.4.2.

@csoja I've also updated the Miniconda 4.2.11 Windows installers

**Comment by msarahan** [comment]
Thanks for jumping on this, @ilanschnell - and sorry for forgetting to add that dependency.  That must have happened when I swapped out that terrible VB script for the current elevation solution.

**Comment by JoeStaines** [comment]
The added dependency on pywin32 is affecting builds where we also have a separate `pip install` build which has a bunch of install_requires python packages, and those packages depend on pypiwin32. pywin32 and pypiwin32 dont seem to play nice with each other and i get `IOError: [Errno 13] Permission denied: '{path_to_python}\\Lib\\site-packages\\win32\\win32api.pyd'`.

Any advice?

**Comment by JoeStaines** [comment]
Hmm, this issue was a bit weird. Had a conda_requirements text file which had a specific version of python (2.7.10). When conda installs python it will update the rest of conda (and bring in pywin32). However switching the version to 2.7.12 will still install pywin32, but pypiwin32 will happily overwrite pywin32 and use that, instead of erroring like before.

**Comment by stmax82** [comment]
I don't think this is fixed. I just tried to create a new environment and got the same error again.

The example from my initial post still results in the error:

conda create -p pyenv_ladkjf python=3.4 ipython-notebook

**Comment by stmax82** [comment]
This bug seems to be fixed after running conda update --all.

Thanks
