### ISSUE TITLE
Document that $CONDA_BLD_PATH must end with "/conda-bld" (and stop breaking stuff with minor releases)

### ISSUE THREAD

**Issue by sscherfke** [conda/conda#3732]
On September 30, @kalefranz inserted a new assertion (`name == 'conda-bld'`) into `context.py` ([see here](https://github.com/conda/conda/blame/master/conda/base/context.py#L299)) causing `conda info` to fail when `CONDA_BLD_PATH` does not end with `/conda-bld`:
```console
$ CONDA_BLD_PATH=/tmp conda info
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



`$ /home/user/conda/bin/conda info`




    Traceback (most recent call last):
      File "/home/user/conda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/user/conda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/user/conda/lib/python3.5/site-packages/conda/cli/main_info.py", line 225, in execute
        channels = list(prioritize_channels(channels).keys())
      File "/home/user/conda/lib/python3.5/site-packages/conda/models/channel.py", line 380, in prioritize_channels
        channel = Channel(chn)
      File "/home/user/conda/lib/python3.5/site-packages/conda/models/channel.py", line 161, in __call__
        c = Channel.from_value(value)
      File "/home/user/conda/lib/python3.5/site-packages/conda/models/channel.py", line 211, in from_value
        return Channel.from_url(value)
      File "/home/user/conda/lib/python3.5/site-packages/conda/models/channel.py", line 196, in from_url
        return parse_conda_channel_url(url)
      File "/home/user/conda/lib/python3.5/site-packages/conda/models/channel.py", line 132, in parse_conda_channel_url
        configured_token) = _read_channel_configuration(scheme, host, port, path)
      File "/home/user/conda/lib/python3.5/site-packages/conda/models/channel.py", line 97, in _read_channel_configuration
        for name, channel in sorted(context.custom_channels.items(), reverse=True,
      File "/home/user/conda/lib/python3.5/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/home/user/conda/lib/python3.5/site-packages/conda/base/context.py", line 265, in custom_channels
        all_sources = self.default_channels, (self.local_build_root_channel,), custom_channels
      File "/home/user/conda/lib/python3.5/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/home/user/conda/lib/python3.5/site-packages/conda/base/context.py", line 246, in local_build_root_channel
        assert name == 'conda-bld'
    AssertionError

```
This change was not documented and led to a hard to trace failure of our test suite (we set `$CONDA_BLD_PATH` in our test suite and `conda info` is, e.g., run by `conda build`). 

Unfortunately, this was not the first time that conda/conda-build introduced subtle, but breaking changes in a patch release.

**Comment by kalefranz** [comment]
Noting the origin is related to https://github.com/conda/conda/issues/3717, and specifically https://github.com/conda/conda/issues/3717#issuecomment-255830103 and subsequent discussion.

**Comment by kalefranz** [comment]
I also thought I posted one reply to this already.  I guess the comment didn't stick.

This is definitely a bug.  Any assertion error is a bug, and we let assertion errors slip through the exception handler and provide an ugly stack trace to emphasize that point.

**Comment by kalefranz** [comment]
An assertion error is a bug. Full stop. That's why we let assertion errors have the big ugly stack trace. 

I'll work on a fix today.
