### ISSUE TITLE
Conda list/remove commands raise ImportError related to 'yaml' module

### ISSUE THREAD

**Issue by davechallis** [conda/conda#3754]
Using a freshly installed Conda (on linux, installed from bash installer at `https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh`):

```
$ conda update conda
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /miniconda:
#
conda                     4.2.11                   py35_0 
```

Then creating a new environment works fine:

```
$ conda create --name=test python=3.5
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /miniconda/envs/test:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0     
    pip:        8.1.2-py35_0 
    python:     3.5.2-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py35_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py35_0
    xz:         5.2.2-0      
    zlib:       1.2.8-3      

Proceed ([y]/n)? y

Linking packages ...
[      COMPLETE      ]|###########################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#
```

Trying to remove or list the environment with Conda fails however:

```
$ conda env list
Traceback (most recent call last):
  File "/miniconda/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/miniconda/lib/python3.5/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/miniconda/lib/python3.5/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/miniconda/lib/python3.5/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/miniconda/lib/python3.5/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named 'yaml'

$ conda env remove
Traceback (most recent call last):
  File "/miniconda/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/miniconda/lib/python3.5/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/miniconda/lib/python3.5/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/miniconda/lib/python3.5/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/miniconda/lib/python3.5/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named 'yaml'
```

**Comment by cstbgansanay** [comment]
Same here: https://github.com/conda/conda/issues/3756, just stumbled upon your issue...

**Comment by cstbgansanay** [comment]
It seems to be fixed in 4.2.12. Waiting for the release.

**Comment by gitricko** [comment]
I have the same issue as well

**Comment by kalefranz** [comment]
fixed with https://github.com/conda/conda/pull/3740
