### ISSUE TITLE
pip install ImportError in conda env 

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#3757]
Trying to use `pip` in a fresh conda env results in the following ImportError:

``` bash
Obtaining file:///Users/fonnescj/Repositories/pymc3
Could not import setuptools which is required to install from a source distribution.
Traceback (most recent call last):
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/pip/req/req_install.py", line 372, in setup_py
    import setuptools  # noqa
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/setuptools/__init__.py", line 13, in <module>
    from setuptools.extension import Extension
  File "/Users/fonnescj/anaconda3/envs/dev/lib/python3.5/site-packages/setuptools/extension.py", line 9, in <module>
    from .monkey import get_unpatched
ImportError: No module named 'setuptools.monkey'
```

Confirmed that setuptools and pip are up to date with conda.

Running Anaconda Python 3.5.2 on macOS 10.12.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1710
