### ISSUE TITLE
CondaRuntimeError: Runtime error: Could not open u'/opt/conda/pkgs/mkl-11.3.3-0.tar.bz2.part' for writing (("Connection broken: error(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by komailrk** [conda/conda#3762]
Unable to install mkl-11.3.3 and it keeps throwing two errors:
- Cannot open file
- Connection reset by peer

```
(root) root@f0cb7ac3698c:# conda env create -f py27_environment.yaml -p /opt/conda/envs/py27
Fetching package metadata .........                                                                                                                                                            
Solving package specifications: ..........                                                                                                                                                     
Fetching packages ...                                                                                                                                                                          
mkl-11.3.3-0.t  15% |#######################                                                                                                    An unexpected error has occurred.:  0:00:04  25.97 MB/s
Please consider posting the following information to the                                                                                                                                               
conda GitHub issue tracker at:                                                                                                                                                                         

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /opt/conda/bin/conda-env create -f py27_environment.yaml -p /opt/conda/envs/linux-64/py27`




    Traceback (most recent call last):
      File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/python2.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 38, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/opt/conda/pkgs/mkl-11.3.3-0.tar.bz2.part' for writing (("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))).
```

**Comment by komailrk** [comment]
Seems like removing the version condition from the yaml file fixed the issue:
```anaconda::mkl```

**Comment by kalefranz** [comment]
This was simple HTTP timeout.  Closing the issue.
