### ISSUE TITLE
The --canonical option to `conda list` is broken

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#3764]
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.11.dev251+d5af6bb
       conda is private : False
      conda-env version : 4.2.11.dev251+d5af6bb
    conda-build version : 2.0.7
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /spare/local/nwani/miniconda2  (writable)
    default environment : /spare/local/nwani/miniconda2
       envs directories : /spare/local/nwani/miniconda2/envs
          package cache : /spare/local/nwani/miniconda2/pkgs
           channel URLs : file:///spare/local/nwani/conda-pkgs/linux-64
                          file:///spare/local/nwani/conda-pkgs/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /apps/infrafs1/nwani/.condarc
           offline mode : False
             user-agent : conda/4.2.11.dev251+d5af6bb requests/2.10.0 CPython/2.7.12 Linux/4.4.27-200.fc22.trc.1.0.x86_64 Fedora/22 glibc/2.21
                UID:GID : 5645:3037

`$ /spare/local/nwani/miniconda2/bin/conda list -c`

    Traceback (most recent call last):
      File "/spare/local/nwani/conda/conda/exceptions.py", line 482, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/spare/local/nwani/conda/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/spare/local/nwani/conda/conda/cli/main_list.py", line 228, in execute
        show_channel_urls=context.show_channel_urls)
      File "/spare/local/nwani/conda/conda/cli/main_list.py", line 174, in print_packages
        print('\n'.join(output))
    TypeError: sequence item 0: expected string or Unicode, Dist found
```

**Comment by nehaljwani** [comment]
The `--json` output has also changed, probably (I am guessing) due to the introduction of 'Record Model'. I am willing to send a patch to fix this, if someone can confirm whether the output for `--json` is expected to be something like:
```
[
  {
    "channel": "file:///spare/local/nwani/conda-pkgs", 
    "dist_name": "ace-3.0.pre-c++11_clang36_libcxx_0", 
    "with_features_depends": null
  },
...
]
```
or the previous one, something like:
```
[
  "conda-4.2.9-py27_0", 
  "conda-build-2.0.6-py27_0", 
  "conda-env-2.6.0-0", 
...
]
```

**Comment by nehaljwani** [comment]
Seems like this has been fixed by https://github.com/conda/conda/commit/e75ad854e5f91ba0b0dc1b6dd5a6b493c6640e63#diff-6568098a887f5d6e639052f5343d9524R175
