### ISSUE TITLE
"[Errno 36] File name too long" while building PyPI package.

### ISSUE THREAD

**Issue by AndrewPashkin** [conda/conda#3765]
Here is the complete terminal output:

```
$ conda skeleton pypi logbook
logbook not found, trying Logbook
Warning, the following versions were found for Logbook
0.1
0.2
0.2.1
0.3
0.4
0.4.1
0.4.2
0.5.0
0.6.0
0.7.0
0.8.0
0.8.1
0.9.0
0.9.1
0.10.0
0.10.1
0.11.0
0.11.1
0.11.2
0.11.3
0.12.0
0.12.1
0.12.2
0.12.3
0.12.4
0.12.5
1.0.0
Using 1.0.0
Use --version to specify a different version.
Using url https://pypi.python.org/packages/34/e8/6419c217bbf464fe8a902418120cccaf476201bd03b50958db24d6e90f65/Logbook-1.0.0.tar.gz (174 KB) for Logbook.
Downloading Logbook
Using cached download
Unpacking Logbook...
done
working in /tmp/tmp6ukt2ro0conda_skeleton_Logbook-1.0.0.tar.gz

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0      (soft-link)
    pip:        8.1.2-py35_0  (soft-link)
    python:     3.5.2-0       (soft-link)
    pyyaml:     3.12-py35_0   (soft-link)
    readline:   6.2-2         (soft-link)
    setuptools: 27.2.0-py35_0 (soft-link)
    sqlite:     3.13.0-0      (soft-link)
    tk:         8.5.18-0      (soft-link)
    wheel:      0.29.0-py35_0 (soft-link)
    xz:         5.2.2-0       (soft-link)
    yaml:       0.1.6-0       (soft-link)
    zlib:       1.2.8-3       (soft-link)

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/history.py", line 86, in update
    self.init_log_file()
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/history.py", line 76, in init_log_file
    self.write_dists(linked(self.prefix))
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/history.py", line 250, in write_dists
    os.makedirs(self.meta_dir)
  File "/opt/anaconda3/lib/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/anaconda3/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 36] File name too long: '/home/andrei/conda-bld/skeleton_1477686723967/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 192, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 406, in skeletonize
    noprompt, packages, config=config, setup_options=setup_options)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 664, in get_package_metadata
    config=config)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 924, in get_pkginfo
    run_setuppy(src_dir, tempdir, python_version, config=config, setup_options=setup_options)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/skeletons/pypi.py", line 957, in run_setuppy
    config=config)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/build.py", line 431, in create_env
    plan.execute_actions(actions, index, verbose=config.debug)
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 642, in execute_actions
    with History(actions[inst.PREFIX]):
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/history.py", line 67, in __enter__
    self.update('enter')
  File "/opt/anaconda3/lib/python3.5/site-packages/conda/history.py", line 105, in update
    raise CondaFileIOError(self.path, "Can't write the history file %s" % e)
conda.exceptions.CondaFileIOError: IO error: Couldn't read or write to file. '/home/andrei/conda-bld/skeleton_1477686723967/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl/conda-meta/history'. Can't write the history file [Errno 36] File name too long: '/home/andrei/conda-bld/skeleton_1477686723967/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl'
```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1502
