### ISSUE TITLE
CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7f1fefa5f810>

### ISSUE THREAD

**Issue by arthurchumak** [conda/conda#3766]
a@b:~$ conda create --name py python
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/ccc/.conda/envs/py:

The following packages will be downloaded:

| package | build |
| --- | --- |
| zlib-1.2.8 | 3         101 KB |
| python-2.7.12 | 1        12.1 MB |
| setuptools-27.2.0 | py27_0         521 KB |
| wheel-0.29.0 | py27_0          81 KB |
| pip-8.1.2 | py27_0         1.5 MB |

```
------------------------------------------------------------
                                       Total:        14.3 MB
```

The following NEW packages will be INSTALLED:

```
openssl:    1.0.2j-0     
pip:        8.1.2-py27_0 
python:     2.7.12-1     
readline:   6.2-2        
setuptools: 27.2.0-py27_0
sqlite:     3.13.0-0     
tk:         8.5.18-0     
wheel:      0.29.0-py27_0
zlib:       1.2.8-3      
```

Proceed ([y]/n)? 

Fetching packages ...
zlib-1.2.8-3.t 100% |###############################################################################################| Time: 0:00:00 474.47 kB/s
python-2.7.12- 100% |###############################################################################################| Time: 0:00:10   1.24 MB/s
setuptools-27. 100% |###############################################################################################| Time: 0:00:00   1.07 MB/s
wheel-0.29.0-p 100% |###############################################################################################| Time: 0:00:00 680.69 kB/s
pip-8.1.2-py27 100% |###############################################################################################| Time: 0:00:01   1.30 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : linux-64
      conda version : 4.2.7
   conda is private : False
  conda-env version : 4.2.7
conda-build version : not installed
     python version : 2.7.12.final.0
   requests version : 2.11.1
   root environment : /usr  (read only)
default environment : /usr
   envs directories : /home/ccc/.conda/envs
                      /usr/envs
      package cache : /home/ccc/.conda/envs/.pkgs
                      /usr/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                      https://repo.continuum.io/pkgs/free/noarch/
                      https://repo.continuum.io/pkgs/pro/linux-64/
                      https://repo.continuum.io/pkgs/pro/noarch/
        config file : None
       offline mode : False
```

`$ /home/ccc/.local/bin/conda create --name py python`

```
Traceback (most recent call last):
  File "/home/ccc/.local/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/ccc/.local/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
    exit_code = args.func(args, p)
  File "/home/ccc/.local/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/home/ccc/.local/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
    raise CondaRuntimeError('RuntimeError: %s' % e)
CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7f1fefa5f810>
```

**Comment by kalefranz** [comment]
Can you update to conda 4.2.11 and try again?

    conda update conda

**Comment by arthurchumak** [comment]
This problem exists under python2, and conda installed via `pip install conda`
When I use python3 in the same way, everything is good.
I use Ubuntu 16.10.

```
$ conda update conda
PackageNotFoundError: Package not found: 'conda' Package 'conda' is not installed in /usr
```

```
$ sudo conda install conda
[sudo] password for conda: 
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /usr:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          502 B
    openssl-1.0.2j             |                0         3.2 MB
    readline-6.2               |                2         606 KB
    sqlite-3.13.0              |                0         4.0 MB
    tk-8.5.18                  |                0         1.9 MB
    yaml-0.1.6                 |                0         246 KB
    zlib-1.2.8                 |                3         101 KB
    python-2.7.12              |                1        12.1 MB
    enum34-1.1.6               |           py27_0          53 KB
    pycosat-0.6.1              |           py27_1         190 KB
    requests-2.11.1            |           py27_0         621 KB
    ruamel_yaml-0.11.14        |           py27_0         352 KB
    setuptools-27.2.0          |           py27_0         521 KB
    wheel-0.29.0               |           py27_0          81 KB
    conda-4.2.12               |           py27_0         373 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:        25.7 MB

The following NEW packages will be INSTALLED:

    conda:       4.2.12-py27_0 
    conda-env:   2.6.0-0       
    enum34:      1.1.6-py27_0  
    openssl:     1.0.2j-0      
    pip:         8.1.2-py27_0  
    pycosat:     0.6.1-py27_1  
    python:      2.7.12-1      
    readline:    6.2-2         
    requests:    2.11.1-py27_0 
    ruamel_yaml: 0.11.14-py27_0
    setuptools:  27.2.0-py27_0 
    sqlite:      3.13.0-0      
    tk:          8.5.18-0      
    wheel:       0.29.0-py27_0 
    yaml:        0.1.6-0       
    zlib:        1.2.8-3       

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |################################| Time: 0:00:00 101.58 kB/s
openssl-1.0.2j 100% |################################| Time: 0:00:02   1.34 MB/s
readline-6.2-2 100% |################################| Time: 0:00:00   2.13 MB/s
sqlite-3.13.0- 100% |################################| Time: 0:00:03   1.29 MB/s
tk-8.5.18-0.ta 100% |################################| Time: 0:00:01   1.40 MB/s
yaml-0.1.6-0.t 100% |################################| Time: 0:00:00   2.51 MB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00   1.51 MB/s
python-2.7.12- 100% |################################| Time: 0:00:10   1.26 MB/s
enum34-1.1.6-p 100% |################################| Time: 0:00:00   1.30 MB/s
pycosat-0.6.1- 100% |################################| Time: 0:00:00   2.55 MB/s
requests-2.11. 100% |################################| Time: 0:00:00   2.30 MB/s
ruamel_yaml-0. 100% |################################| Time: 0:00:00   3.49 MB/s
setuptools-27. 100% |################################| Time: 0:00:00   1.96 MB/s
wheel-0.29.0-p 100% |################################| Time: 0:00:00   1.62 MB/s
conda-4.2.12-p 100% |################################| Time: 0:00:00   3.20 MB/s
pip-8.1.2-py27 100% |################################| Time: 0:00:01   1.49 MB/s
Extracting packages ...
[      COMPLETE      ]|###################################################| 100%
Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /usr  (writable)
    default environment : /usr
       envs directories : /usr/envs
          package cache : /usr/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /usr/local/bin/conda install conda`




    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7ffb614d1750>
```

**Comment by LeeRock** [comment]
the same issue is for me.
my env is python2.7.
conda is installed via pip.
my debug message is as followed:
sudo conda update --all
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /usr:

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pip:        9.0.1-py27_0  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    python:     2.7.12-1      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    readline:   6.2-2         https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    setuptools: 27.2.0-py27_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    sqlite:     3.13.0-0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    tk:         8.5.18-0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    wheel:      0.29.0-py27_0 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    zlib:       1.2.8-3       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /usr  (writable)
    default environment : /usr
       envs directories : /usr/envs
          package cache : /usr/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/hik/.condarc
           offline mode : False



`$ /usr/local/bin/conda update --all`




    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7efd0cbe0a50>

**Comment by mcint** [comment]
I have the same error to report.

I'm using a virtualenv, and `conda update conda` reports conda is not installed, while `conda install conda` yields the same error as `conda install numpy`.

```
$ conda install numpy                                             
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /working/.venv:

The following NEW packages will be INSTALLED:

    conda:       4.2.13-py27_0 
    enum34:      1.1.6-py27_0  
    numpy:       1.11.2-py27_0 
    pip:         9.0.1-py27_0  
    pycosat:     0.6.1-py27_1  
    python:      2.7.12-1      
    requests:    2.12.1-py27_0 
    ruamel_yaml: 0.11.14-py27_0
    setuptools:  27.2.0-py27_0 
    sqlite:      3.13.0-0      
    tk:          8.5.18-0      
    wheel:       0.29.0-py27_0 
    yaml:        0.1.6-0       
    zlib:        1.2.8-3       

Proceed ([y]/n)? 

Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.9.final.0
       requests version : 2.12.1
       root environment : /working/.venv  (writable)
    default environment : /working/.venv
       envs directories : /working/.venv/envs
          package cache : /working/.venv/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /working/.venv/bin/conda install numpy`




    Traceback (most recent call last):
      File "/working/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/working/.venv/local/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/working/.venv/local/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/working/.venv/local/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x7f9a626f86d0>
```

**Comment by grisuthedragon** [comment]
I got the same with conda 4.2.13 as well.

**Comment by noelvo** [comment]
+1

**Comment by derekprovance** [comment]
+1

**Comment by nilsec** [comment]
+1

**Comment by 2083089b** [comment]
+1

**Comment by kalefranz** [comment]
I haven't seen this issue reported at all with conda 4.3. The current patch version is 4.3.13. Please `conda update conda`. 

If you still encounter this problem, please provide the updated stack trace.
