### ISSUE TITLE
can't install bs4

### ISSUE THREAD

**Issue by suselee** [conda/conda#3769]
conda install BeautifulSoup
Fetching package metadata .....Could not connect to https://repo.continuum.io/pkgs/pro/noarch
Could not connect to https://repo.continuum.io/pkgs/free/noarch
Could not connect to https://repo.continuum.io/pkgs/pro/linux-64
Could not connect to https://repo.continuum.io/pkgs/free/linux-64
..Could not connect to https://repo.continuum.io/pkgs/free/linux-64
An unexpected error has ## occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Current conda install:

```
           platform : linux-64
      conda version : 4.2.11
   conda is private : False
  conda-env version : 4.2.11
conda-build version : not installed
     python version : 3.5.2.final.0
   requests version : 2.11.1
   root environment : /home/suse/miniconda3  (writable)
default environment : /home/suse/miniconda3
   envs directories : /home/suse/miniconda3/envs
      package cache : /home/suse/miniconda3/pkgs
       channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/free/linux-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/pro/linux-64
                      https://repo.continuum.io/pkgs/pro/noarch
        config file : /home/suse/.condarc
       offline mode : False
```

`$ /home/suse/miniconda3/bin/conda install BeautifulSoup`

```
Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c18bbe10>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c18bbe10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
    timeout=(3.05, 60))
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c18bbe10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in <listcomp>
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "/home/suse/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/home/suse/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
  File "/home/suse/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
    res = f(*args, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 234, in fetch_repodata
    raise CondaRuntimeError(msg)
conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c18bbe10>: Failed to establish a new connection: [Errno 101] Network is unreachable',)): https://repo.continuum.io/pkgs/free/linux-64


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
    raise err
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
    conn = self._new_conn()
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c1738748>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
    release_conn=release_conn, **response_kw)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c1738748>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
    timeout=(3.05, 60))
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c1738748>: Failed to establish a new connection: [Errno 101] Network is unreachable',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
    exit_code = args.func(args, p)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
    prefix=prefix)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 316, in fetch_index
    for url in urls]
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 316, in <listcomp>
    for url in urls]
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
    res = f(*args, **kwargs)
  File "/home/suse/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 234, in fetch_repodata
    raise CondaRuntimeError(msg)
conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f19c1738748>: Failed to establish a new connection: [Errno 101] Network is unreachable',)): https://repo.continuum.io/pkgs/free/linux-64
```

**Comment by soapy1** [comment]
are you able to reach repo.continuum.io normally? `ping -c 3 repo.continuum.io`

**Comment by dlongry** [comment]
I have the same problem. could you tell me how did you solve it？ thanks.
