### ISSUE TITLE
Channel URL with empty path causes exception: AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Bklyn** [conda/conda#3774]
Using latest conda or miniconda, if I have a .condarc with the following contents (trying to use an internal repository for some packages):

```
channels:
    - http://conda-packages.local:26632/
    - defaults
```   
Attempts to install packages result in the following error:

```
% conda install somepkg
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/tmp/miniconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 225, in execute
    channels = list(prioritize_channels(channels).keys())
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 380, in prioritize_channels
    channel = Channel(chn)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 161, in __call__
    c = Channel.from_value(value)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 211, in from_value
    return Channel.from_url(value)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 196, in from_url
    return parse_conda_channel_url(url)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 132, in parse_conda_channel_url
    configured_token) = _read_channel_configuration(scheme, host, port, path)
  File "/tmp/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 122, in _read_channel_configuration
    return (Url(host=host, port=port).url.rstrip('/'), path.strip('/') or None,
AttributeError: 'NoneType' object has no attribute 'strip'

```

Even `conda info` fails with the same sort of error.  Here's my conda info after removing my .condarc file:

```
Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 2.0.7
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /tmp/miniconda2  (writable)
    default environment : /tmp/miniconda2
       envs directories : /tmp/miniconda2/envs
          package cache : /tmp/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
```

**Comment by Bklyn** [comment]
The error goes away once there is some non-empty path component to the URL, so changing from:

    - http://conda-packages.local:26632/

to

    - http://conda-packages.local:26632/pkgs/

Fixes the issue.

**Comment by kalefranz** [comment]
Fixed in https://github.com/conda/conda/pull/3748
