### ISSUE TITLE
`conda env list` fails on a fresh OSX install

### ISSUE THREAD

**Issue by fperez** [conda/conda#3789]
This is puzzling, and not letting me do certain basic tasks.  This is on a freshly installed conda from just minutes ago:

```
dreamweaver[~]> conda env list
Traceback (most recent call last):
  File "/Users/fperez/usr/conda/bin/conda-env", line 4, in <module>
    import conda_env.cli.main
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda_env/cli/main.py", line 35, in <module>
    from . import main_attach
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda_env/cli/main_attach.py", line 4, in <module>
    from ..env import from_environment
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda_env/env.py", line 17, in <module>
    from . import yaml
  File "/Users/fperez/usr/conda/lib/python3.5/site-packages/conda_env/yaml.py", line 8, in <module>
    import yaml
ImportError: No module named 'yaml'
```

Oddly, conda thinks yaml is already installed

```
dreamweaver[~]> conda install yaml
Fetching package metadata .......
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at /Users/fperez/usr/conda:
#
yaml                      0.1.6                         0  
```

Puzzled and stumped...

**Comment by kalefranz** [comment]
fixed in https://github.com/conda/conda/pull/3740. Will be released today.
