### ISSUE TITLE
conda skeleton doesn't work for CVXOPT

### ISSUE THREAD

**Issue by immerrr** [conda/conda#379]
The output of `conda skeleton pypi CVXOPT` (which, btw, unlike pip, is not recognized when written in lowercase) suggests posting an issue, so here goes:

```
$ conda --debug skeleton pypi CVXOPT
Using url https://github.com/cvxopt/cvxopt/tarball/1.1.6 () for CVXOPT.
Downloading CVXOPT (use --no-download to skip this step)
INFO:fetch.start:('1.1.6', 3352952)
INFO:fetch.update:16384
INFO:fetch.update:32768
INFO:fetch.update:49152
<...fetch.updates snipped...>
INFO:fetch.update:3293184
INFO:fetch.update:3309568
INFO:fetch.update:3325952
INFO:fetch.update:3342336
INFO:fetch.update:3352952
INFO:fetch.stop:None
Unpacking CVXOPT...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/immerrr/.local/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/immerrr/.local/lib/python2.7/site-packages/conda/cli/main.py", line 183, in main
    args.func(args, p)
  File "/home/immerrr/.local/lib/python2.7/site-packages/conda/cli/main_skeleton.py", line 82, in execute
    pypi.main(args, parser)
  File "/home/immerrr/.local/lib/python2.7/site-packages/conda/builder/pypi.py", line 233, in main
    unpack(join(SRC_CACHE, d['filename']), tempdir)
  File "/home/immerrr/.local/lib/python2.7/site-packages/conda/builder/pypi.py", line 313, in unpack
    raise Exception("not a valid source")
Exception: not a valid source
```

And here's the `conda info`:

```
$ conda info
Current conda install:

             platform : linux-64
        conda version : 2.2.1
     root environment : /home/immerrr/.conda  (writable)
  default environment : /home/immerrr/.conda/envs/foobar
     envs directories : /home/immerrr/.conda/envs
        package cache : /home/immerrr/.conda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : /home/immerrr/.condarc

```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1979
