### ISSUE TITLE
error when trying to revert changes

### ISSUE THREAD

**Issue by kirk86** [conda/conda#3793]
Hi everyone I'm having these errors when I try to revert back to some previous version since when I updated the the packages `conda update --all` I was left with a broken system. Especially most packages from conda were not working and they were throwing `illegal instruction errors`.

Here's the error that I get 

```
-bash-4.1$ conda install --revision 104
Traceback (most recent call last):
  File "/home/user/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 94, in main
    imported = importlib.import_module(module)
  File "/home/user/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 18, in <module>
    from ..egg_info import get_egg_info
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 18, in <module>
    from .instructions import RM_FETCHED, FETCH, RM_EXTRACTED, EXTRACT, UNLINK, LINK, SYMLINK_CONDA
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 7, in <module>
    from .fetch import fetch_pkg
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 13, in <module>
    import requests
  File "/home/user/anaconda2/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/home/user/anaconda2/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
ImportError: No module named urllib3
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .........
.
Package plan for installation in environment /home/user/anaconda2:

The following packages will be downloaded:

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/user/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 394, in install
    display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "/home/user/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 73, in display_actions
    info = index[dist + '.tar.bz2']
KeyError: 'trung::nose-parameterized-0.5.0-py27_0.tar.bz2'
```

Here's the output from `conda info`

```
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : 2.0.7
       python version : 2.7.12.final.0
     requests version : 2.11.1
     root environment : /home/user/anaconda2  (writable)
  default environment : /home/user/anaconda2
     envs directories : /home/user/anaconda2/envs
        package cache : /home/user/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/intel/linux-64/
                        https://conda.anaconda.org/intel/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/user/.condarc
         offline mode : False
    is foreign system : False
```

I don't know why but I always get an error about urllib3 since my last update, even if I install the package then I still get a different error.

**Comment by kalefranz** [comment]
Example of conda "uninstalling" itself during a failed update.  Conda 4.3 fixed the root cause of this issue with transactions.  The only solution here, unfortunately, is to download miniconda and use it to heal the current installation.  Or just start over with a new install.
