### ISSUE TITLE
conda install fails with ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by samuelsinayoko** [conda/conda#3800]
I'm running `conda install -y --file requirements.txt` (within a Docker container). It works fine on our CI server but on my local machine it fails with the following error:
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /miniconda  (writable)
    default environment : /miniconda/envs/bmll_python3
       envs directories : /miniconda/envs
          package cache : /miniconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/bmll/.condarc
           offline mode : False



`$ /miniconda/envs/bmll_python3/bin/conda install -q -y --file /tmp/requirements/requirements-conda-optional.txt`




    Traceback (most recent call last):
      File "/miniconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
        yield
      File "/miniconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
        data = self._fp.read(amt)
      File "/miniconda/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/miniconda/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/miniconda/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/miniconda/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/miniconda/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/miniconda/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    ConnectionResetError: [Errno 104] Connection reset by peer
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/miniconda/lib/python3.5/site-packages/requests/models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/miniconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/miniconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
        flush_decoder = True
      File "/miniconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/miniconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 250, in _error_catcher
        raise ProtocolError('Connection broken: %r' % e, e)
    requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/miniconda/lib/python3.5/site-packages/conda/fetch.py", line 431, in download
        for chunk in resp.iter_content(2**14):
      File "/miniconda/lib/python3.5/site-packages/requests/models.py", line 679, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/miniconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/miniconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/miniconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/miniconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/miniconda/lib/python3.5/site-packages/conda/fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/miniconda/lib/python3.5/site-packages/conda/fetch.py", line 450, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/miniconda/pkgs/qt-4.8.7-3.tar.bz2.part' for writing (("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/miniconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/miniconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/miniconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/miniconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/miniconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/miniconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/miniconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/miniconda/pkgs/qt-4.8.7-3.tar.bz2.part' for writing (("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))).
```

The requirements file contains
```jupyter==1.0.0
notebook==4.2.2
numpy==1.11.1
pandas==0.18.1
pytables==3.2.2
pyzmq==15.4.0
scipy==0.18.0
statsmodels==0.6.1

# Needed by storagemanager
pycosat==0.6.1
pycrypto==2.6.1

# Dependencies for pandas
pytz==2016.6.1

# Dependencies for bmll-python
requests==2.11.1
blist==1.3.6
```

**Comment by samuelsinayoko** [comment]
I was able to resolve my issue by switching from `curl` to `wget`. `wget` retries automatically on error and eventually succeeds. The output of `wget` looks like this:
```
+ cd /tmp
+ wget https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh
--2016-11-04 13:36:53--  https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh
Resolving repo.continuum.io (repo.continuum.io)... 104.16.19.10, 104.16.18.10, 2400:cb00:2048:1::6810:130a, ...
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 33987431 (32M) [application/octet-stream]
Saving to: 'Miniconda3-4.1.11-Linux-x86_64.sh'

     0K .......... .......... .......... .......... ..........  0% 9.67M 3s
    50K .......... .......... .......... .......... ..........  0% 10.2M 3s
   100K .......... .......... .......... .......... ..........  0% 11.4M 3s
   150K .......... .......... .......... .......... ..........  0% 10.7M 3s
   200K .......... .......... .......... .......... ..........  0% 10.8M 3s
  [....]
  4600K .......... .......... .......... .......... .......... 14% 11.7M 3s
  4650K .......... .......... .......... .......... .......... 14% 11.6M 3s
  4700K .......... .......... .......... .......... .......... 14% 11.9M 3s
  4750K .......... .......... .......... .......... .......... 14% 11.6M 3s
  4800K .......... .......... .......... .......... .......... 14% 11.3M 2s
  4850K .......... .......... .......... .......... .......... 14% 11.6M 2s
  4900K .......... .........                                   14% 13.8M=0.4s

2016-11-04 13:36:54 (11.1 MB/s) - Read error at byte 5037182/33987431 (Success). Retrying.

--2016-11-04 13:36:55--  (try: 2)  https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 33987431 (32M), 28950249 (28M) remaining [application/octet-stream]
Saving to: 'Miniconda3-4.1.11-Linux-x86_64.sh'

        [ skipping 4900K ]
  4900K ,,,,,,,,,, ,,,,,,,,,. .......... .......... .......... 14% 15.3M 3s
  4950K .......... .......... .......... .......... .......... 15% 10.5M 3s
  5000K .......... .......... .......... .......... .......... 15% 11.5M 3s
  5050K .......... .......... .......... .......... .......... 15% 10.4M 3s
  5100K .......... .......... .......... .......... .......... 15% 4.47M 3s
  5150K .......... .......... .......... .......... .......... 15% 4.94M 4s
  [....]
  6950K .......... .......... .......... .......... .......... 21% 8.89M 3s
  7000K .......... .......... .......... .......... .......... 21% 12.0M 3s
  7050K .......... .......... .......... .......... .......... 21% 3.50M 3s
  7100K ..........                                             21% 79.5M=0.2s

2016-11-04 13:36:55 (9.56 MB/s) - Read error at byte 7280853/33987431 (Success). Retrying.

--2016-11-04 13:36:57--  (try: 3)  https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 33987431 (32M), 26706578 (25M) remaining [application/octet-stream]
Saving to: 'Miniconda3-4.1.11-Linux-x86_64.sh'

        [ skipping 7100K ]
  7100K ,,,,,,,,,, .......... .......... .......... .......... 21% 12.3M 3s
  [....]
 25850K .......... .......... .......... .......... .......... 78% 12.0M 1s
 25900K .                                                      78% 2466G=1.7s

2016-11-04 13:36:59 (10.9 MB/s) - Read error at byte 26522924/33987431 (Success). Retrying.

--2016-11-04 13:37:02--  (try: 4)  https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh
Connecting to repo.continuum.io (repo.continuum.io)|104.16.19.10|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 33987431 (32M), 7464507 (7.1M) remaining [application/octet-stream]
Saving to: 'Miniconda3-4.1.11-Linux-x86_64.sh'

        [ skipping 25900K ]
 25900K ,......... .......... .......... .......... .......... 78% 10.5M 1s
 25950K .......... .......... .......... .......... .......... 78% 10.0M 1s
 [....]
 33000K .......... .......... .......... .......... .......... 99% 11.6M 0s
 33050K .......... .......... .......... .......... .......... 99% 11.6M 0s
 33100K .......... .......... .......... .......... .......... 99% 11.2M 0s
 33150K .......... .......... .......... ..........           100% 14.3M=0.6s

2016-11-04 13:37:02 (11.1 MB/s) - 'Miniconda3-4.1.11-Linux-x86_64.sh' saved [33987431/33987431]
```

The bug occured on my machine but not on others (running the same operating system). I've rebooted my machine, checked the amount of disk space, restarted Docker, reinstalled Docker etc, but nothing worked until I switched to `wget`.

**Comment by TapsiS** [comment]
I am getting the same error while installing packages with conda. 
https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
    yield
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
    data = self._fp.read(amt)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/http/client.py", line 448, in read
    n = self.readinto(b)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/http/client.py", line 488, in readinto
    n = self.fp.readinto(b)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tseth/apps/conda/3.5/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/plan.py", line 602, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/fetch.py", line 338, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/conda/fetch.py", line 423, in download
    chunk = resp.raw.read(2**14)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
    flush_decoder = True
  File "/home/tseth/apps/conda/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/tseth/apps/conda/3.5/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 250, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(104, 'Connection reset by peer')", ConnectionResetError(104, 'Connection reset by peer'))

**Comment by kalefranz** [comment]
Intermittent HTTP error.

**Comment by the-drunk-coder** [comment]
Sorry do dig out this old issue but I'm having the very same problem and it won't go away. It's impossible to install anything.

I tried disabling `ssl_verify` but it doesn't help. I'm running conda on an Ubuntu VM, in my company's intranet. My IT department tells me everything is fine, they can't find any problem.

Is there any hint on how this could be solved ?

Best,
N

**Comment by donn** [comment]
Love when CI constantly fails because conda is somewhere in our dependencies. https://github.com/The-OpenROAD-Project/OpenLane/runs/2881956707#step:14:2159
