### ISSUE TITLE
Failure to create lock, failure to link

### ISSUE THREAD

**Issue by arnold-jr** [conda/conda#3803]
related: #3614, #3469 

I'm running 4.2.11 on a cluster. I've been creating/using environments normally until I inadvertently ran two instances of conda in different ssh sessions. Both the root environment and the envs directories live on a distributed file system, but the root environment is read-only and shared across users. 

During normal environment creation:
```
conda create -n joe python=3.5 -y
Linking packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
[sqlite              ]|##########                                            |  20%

CondaOSError: OS error: failed to link (src='/home/username/.conda/envs/.pkgs/sqlite-3.13.0-0/lib/libsqlite3.la', dst='/home/username/.conda/envs/joe/lib/libsqlite3.la', type=3, error=PermissionError(13, 'Permission denied'))
```

Then, in debug mode:
```
DEBUG conda.common.disk:rm_rf(187): rm_rf /home/username/.conda/envs/.pkgs/sqlite-3.13.0-0.pid15569.conda_lock
DEBUG conda.common.disk:rm_rf(187): rm_rf /home/username/.conda/envs/joe/joe.pid15569.conda_lock
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(27): overtaking stderr and stdout
INFO conda.common.io:captured(33): stderr and stdout yielded back
Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.18.2
         python version : 3.5.1.final.0
       requests version : 2.8.1
       root environment : /usr/local/python3/anaconda3  (read only)
    default environment : /usr/local/python3/anaconda3
       envs directories : /home/username/.conda/envs
                          /usr/local/python3/anaconda3/envs
          package cache : /home/username/.conda/envs/.pkgs
                          /usr/local/python3/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /usr/local/python3/anaconda3/bin/conda create -n joe python=3.5 --debug`




    Traceback (most recent call last):
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/install.py", line 969, in link
        _link(src, dst, lt) 
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/install.py", line 171, in _link
        shutil.copy2(src, dst)
      File "/usr/local/python3/anaconda3/lib/python3.5/shutil.py", line 252, in copy2
        copystat(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/local/python3/anaconda3/lib/python3.5/shutil.py", line 219, in copystat
        _copyxattr(src, dst, follow_symlinks=follow)
      File "/usr/local/python3/anaconda3/lib/python3.5/shutil.py", line 159, in _copyxattr
        os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
    PermissionError: [Errno 13] Permission denied: '/home/username/.conda/envs/joe/lib/libsqlite3.la'
    
    During handling of the above exception, another exception occurred:
        Traceback (most recent call last):
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "/usr/local/python3/anaconda3/lib/python3.5/site-packages/conda/install.py", line 972, in link
        (src, dst, lt, e))
    conda.exceptions.CondaOSError: OS error: failed to link (src='/home/username/.conda/envs/.pkgs/sqlite-3.13.0-0/lib/libsqlite3.la', dst='/home/username/.conda/envs/joe/lib/libsqlite3.la', type=3, error=PermissionError(13, 'Permission denied'))

```

I've tried `conda clean -l` and was also trying to manually delete a lock hanging around somewhere, but removing the locked file seems to be successful. I also tried relaxing permissions with `umask` as per [troubleshooting docs](http://conda.pydata.org/docs/troubleshooting.html#permission-denied). Clobbering the anaconda installation is not an option either, since it is a shared resource.

Any help is greatly appreciated!

**Comment by kalefranz** [comment]
Has conda 4.3 helped with this issue?  If not, can you give an updated stack trace?  Latest conda version is 4.3.17.

**Comment by arnold-jr** [comment]
@kalefranz Yes, 4.3 seems to have cured this. Thanks!
