### ISSUE TITLE
issue with conda info traceback command

### ISSUE THREAD

**Issue by kazneus** [conda/conda#3812]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
  File "/Users/Noah/anaconda/lib/python2.7/site-packages/conda/install.py", line 650, in link
  File "/Users/Noah/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Users/Noah/anaconda/etc/fish/conf.d'

**Comment by soapy1** [comment]
Could you provide the output of `conda info` and the command you ran to get this error 🌮
