### ISSUE TITLE
conda remove while offline fails with stack trace

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3815]
I am trying to remove a bunch of R packages (in fact, all of them).  I am now offline in an airport (OK, I was when the problem occurred: I'm now online to report the issue), and the operation fails with a stack trace `HTTPSConnectionPool` exception.

Expected behavior:

* I'm just removing packages: they get removed.

Unexpected behavior:

* I'm just removing packages, but Conda decides it wants to update `pip`
* Conda would attempt to connect to any remote service when there is no network connection of any sort
* If there is a network error (a very common sort of problem for package installers) that Conda would report that error via a stack trace.

```bash
$ conda remove `conda list -e | grep ^r- | cut -f 1 -d =`
Fetching package metadata .........
Solving package specifications: ..........

Package plan for package removal in environment /Users/ijstokes/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pip-9.0.0                  |           py27_0         1.6 MB

The following packages will be REMOVED:

    r-assertthat:   0.1-r3.3.1_2       r
    r-bh:           1.60.0_2-r3.3.1_0  r
    r-bitops:       1.0_6-r3.3.1_2     r
    r-boot:         1.3_18-r3.3.1_0    r
    r-car:          2.1_2-r3.3.1_0     r
    r-caret:        6.0_70-r3.3.1_0    r
    r-catools:      1.17.1-1a          r
    r-chron:        2.3_47-r3.3.1_0    r
    r-class:        7.3_14-r3.3.1_0    r
    r-cluster:      2.0.4-r3.3.1_0     r
    r-codetools:    0.2_14-r3.3.1_0    r
    r-colorspace:   1.2_6-r3.3.1_0     r
    r-crayon:       1.3.1-r3.3.1_0     r
    r-curl:         0.9.7-r3.3.1_0     r
    r-data.table:   1.9.6-r3.3.1_0     r
    r-dbi:          0.4_1-r3.3.1_0     r
    r-dichromat:    2.0_0-r3.3.1_2     r
    r-digest:       0.6.9-r3.3.1_0     r
    r-dplyr:        0.4.3-r3.3.1_0     r
    r-essentials:   1.4.3-r3.3.1_0     r
    r-evaluate:     0.9-r3.3.1_0       r
    r-foreach:      1.4.3-r3.3.1_0     r
    r-foreign:      0.8_66-r3.3.1_0    r
    r-formatr:      1.4-r3.3.1_0       r
    r-ggplot2:      2.1.0-r3.3.1_0     r
    r-gistr:        0.3.6-r3.3.1_0     r
    r-glmnet:       2.0_5-r3.3.1_0     r
    r-gtable:       0.2.0-r3.3.1_0     r
    r-hexbin:       1.27.1-r3.3.1_0    r
    r-highr:        0.6-r3.3.1_0       r
    r-htmltools:    0.3.5-r3.3.1_0     r
    r-htmlwidgets:  0.6-r3.3.1_0       r
    r-httpuv:       1.3.3-r3.3.1_0     r
    r-httr:         1.2.0-r3.3.1_0     r
    r-irdisplay:    0.4.3-r3.3.1_2     r
    r-irkernel:     0.7-r3.3.1_2       r
    r-iterators:    1.0.8-r3.3.1_0     r
    r-jsonlite:     0.9.22-r3.3.1_0    r
    r-kernsmooth:   2.23_15-r3.3.1_0   r
    r-knitr:        1.13-r3.3.1_0      r
    r-labeling:     0.3-r3.3.1_2       r
    r-lattice:      0.20_33-r3.3.1_0   r
    r-lazyeval:     0.2.0-r3.3.1_0     r
    r-lme4:         1.1_12-r3.3.1_0    r
    r-magrittr:     1.5-r3.3.1_2       r
    r-maps:         3.1.0-r3.3.1_0     r
    r-markdown:     0.7.7-r3.3.1_2     r
    r-mass:         7.3_45-r3.3.1_0    r
    r-matrix:       1.2_6-r3.3.1_0     r
    r-matrixmodels: 0.4_1-r3.3.1_0     r
    r-memoise:      1.0.0-r3.3.1_0     r
    r-mgcv:         1.8_12-r3.3.1_0    r
    r-mime:         0.4-r3.3.1_0       r
    r-minqa:        1.2.4-r3.3.1_2     r
    r-munsell:      0.4.3-r3.3.1_0     r
    r-nlme:         3.1_128-r3.3.1_0   r
    r-nloptr:       1.0.4-r3.3.1_2     r
    r-nnet:         7.3_12-r3.3.1_0    r
    r-openssl:      0.9.4-r3.3.1_0     r
    r-pbdzmq:       0.2_3-r3.3.1_0     r
    r-pbkrtest:     0.4_6-r3.3.1_0     r
    r-plyr:         1.8.4-r3.3.1_0     r
    r-proto:        0.3_10-r3.3.1_2    r
    r-pryr:         0.1.2-r3.3.1_0     r
    r-quantmod:     0.4_5-r3.3.1_2     r
    r-quantreg:     5.26-r3.3.1_0      r
    r-r6:           2.1.2-r3.3.1_0     r
    r-randomforest: 4.6_12-r3.3.1_0    r
    r-rbokeh:       0.4.2-r3.3.1_0     r
    r-rcolorbrewer: 1.1_2-2a           r
    r-rcpp:         0.12.5-r3.3.1_0    r
    r-rcppeigen:    0.3.2.8.1-r3.3.1_0 r
    r-recommended:  3.3.1-r3.3.1_0     r
    r-repr:         0.7-r3.3.1_0       r
    r-reshape2:     1.4.1-r3.3.1_2     r
    r-rjsonio:      1.3_0-r3.3.1_2     r
    r-rmarkdown:    0.9.6-r3.3.1_0     r
    r-rpart:        4.1_10-r3.3.1_0    r
    r-rzmq:         0.7.7-r3.3.1_2     r
    r-scales:       0.4.0-r3.3.1_0     r
    r-shiny:        0.13.2-r3.3.1_0    r
    r-sparsem:      1.7-r3.3.1_0       r
    r-spatial:      7.3_11-r3.3.1_0    r
    r-stringi:      1.1.1-r3.3.1_0     r
    r-stringr:      1.0.0-r3.3.1_0     r
    r-survival:     2.39_4-r3.3.1_0    r
    r-tibble:       1.0-r3.3.1_0       r
    r-tidyr:        0.5.1-r3.3.1_0     r
    r-ttr:          0.23_1-r3.3.1_0    r
    r-uuid:         0.1_2-r3.3.1_0     r
    r-xtable:       1.8_2-r3.3.1_0     r
    r-xts:          0.9_7-r3.3.1_2     r
    r-yaml:         2.1.13-r3.3.1_2    r
    r-zoo:          1.7_13-r3.3.1_0    r

The following packages will be UPDATED:

    pip:            8.1.2-py27_0         --> 9.0.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/osx-64/pip-9.0.0-py27_0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/bin/conda remove r-assertthat r-bh r-bitops r-boot r-car r-caret r-catools r-chron r-class r-cluster r-codetools r-colorspace r-crayon r-curl r-data.table r-dbi r-dichromat r-digest r-dplyr r-essentials r-evaluate r-foreach r-foreign r-formatr r-ggplot2 r-gistr r-glmnet r-gtable r-hexbin r-highr r-htmltools r-htmlwidgets r-httpuv r-httr r-irdisplay r-irkernel r-iterators r-jsonlite r-kernsmooth r-knitr r-labeling r-lattice r-lazyeval r-lme4 r-magrittr r-maps r-markdown r-mass r-matrix r-matrixmodels r-memoise r-mgcv r-mime r-minqa r-munsell r-nlme r-nloptr r-nnet r-openssl r-pbdzmq r-pbkrtest r-plyr r-proto r-pryr r-quantmod r-quantreg r-r6 r-randomforest r-rbokeh r-rcolorbrewer r-rcpp r-rcppeigen r-recommended r-repr r-reshape2 r-rjsonio r-rmarkdown r-rpart r-rzmq r-scales r-shiny r-sparsem r-spatial r-stringi r-stringr r-survival r-tibble r-tidyr r-ttr r-uuid r-xtable r-xts r-yaml r-zoo`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_remove.py", line 194, in execute
        plan.execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 415, in download
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/pip-9.0.0-py27_0.tar.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10b1da1d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)): https://repo.continuum.io/pkgs/free/osx-64/pip-9.0.0-py27_0.tar.bz2
```

**Comment by ijstokes** [comment]
Same thing with an offline install attempt:

```
$ conda install -c r rpy2
Fetching package metadata ...Could not connect to https://conda.anaconda.org/r/noarch
Could not connect to https://repo.continuum.io/pkgs/pro/noarch
Could not connect to https://conda.anaconda.org/r/osx-64
Could not connect to https://repo.continuum.io/pkgs/free/noarch
Could not connect to https://repo.continuum.io/pkgs/free/osx-64
Could not connect to https://repo.continuum.io/pkgs/pro/osx-64
Could not connect to https://conda.anaconda.org/r/osx-64
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/bin/conda install -c r rpy2`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 316, in fetch_index
        for url in urls]
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host=u'conda.anaconda.org', port=443): Max retries exceeded with url: /t/<TOKEN>/r/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10d264f10>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)): https://conda.anaconda.org/r/osx-64
```

**Comment by kalefranz** [comment]
First stack trace was an intermittent HTTP issue.  For the offline problem, I think we got that licked in 4.3.
