### ISSUE TITLE
conda install pandas

### ISSUE THREAD

**Issue by Yewale** [conda/conda#3818]
I am trying to install pandas library but i am getting below error.

C:\Users\212576714>conda install pandas
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\212576714\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\212576714\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\212576714\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\212576714\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\212576714\.condarc
           offline mode : False

`$ C:\Users\212576714\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install pandas`

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\socket.py", line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 11004] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
        self._prepare_proxy(conn)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
        conn.connect()
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005E3A358>: Failed to establi
sh a new connection: [Errno 11004] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.
json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005E3A358>:
 Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 485, in send
        raise ProxyError(e, request=request)
    requests.exceptions.ProxyError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by
ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000000005E3A358>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free
/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0
000000005E3A358>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))): https://repo.continuum.io/pkgs/free/win-64/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 75, in create_connection
        for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\socket.py", line 732, in getaddrinfo
        for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    socket.gaierror: [Errno 11004] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 589, in urlopen
        self._prepare_proxy(conn)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 797, in _prepare_proxy
        conn.connect()
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 151, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000829C668>: Failed to establi
sh a new connection: [Errno 11004] getaddrinfo failed

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.
json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000829C668>:
 Failed to establish a new connection: [Errno 11004] getaddrinfo failed',)))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 485, in send
        raise ProxyError(e, request=request)
    requests.exceptions.ProxyError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by
ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000000000829C668>: Failed to establish
 a new connection: [Errno 11004] getaddrinfo failed',)))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in fetch_index
        for url in urls]
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in <listcomp>
        for url in urls]
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\212576714\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free
/win-64/repodata.json.bz2 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0
00000000829C668>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))): https://repo.continuum.io/pkgs/free/win-64/

**Comment by kalefranz** [comment]
fixed in more recent versions of conda
