### ISSUE TITLE
Able to list but not download private package when logged out

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3820]
I wanted to force-install a package that requires an authorization key because it comes from a private channel.  But I forgot that I had logged out a few minutes ago.  Conda somehow ends up deciding that I should download the file (perhaps because its existence is cached in some `repodata.json` file? or because I have a local cached version of it?) but then when it tries to download it fails (because there is no auth token available).  Trace below.

```
$ conda install -f nb_anaconda_theme
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/ijstokes/anaconda/envs/intro-ods:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nb_anaconda_theme-0.1.1    |           py35_0          27 KB  anaconda-nb-extensions

The following NEW packages will be INSTALLED:

    nb_anaconda_theme: 0.1.1-py35_0 anaconda-nb-extensions

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda/envs/intro-ods
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/envs/intro-ods/bin/conda install -f nb_anaconda_theme`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/osx-64/nb_anaconda_theme-0.1.1-py35_0.tar.bz2: https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/osx-64/nb_anaconda_theme-0.1.1-py35_0.tar.bz2
    
(intro-ods) ➜  python anaconda whoami
Using Anaconda API: https://api.anaconda.org
Anonymous User
```

**Comment by ijstokes** [comment]
Ah, the plot thickens.  I am now logged in and I've confirmed I have access to the package on Anaconda Cloud.  But I still can't install it:

```
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/osx-64/nb_anaconda_theme-0.1.1-py35_0.tar.bz2: https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/osx-64/nb_anaconda_theme-0.1.1-py35_0.tar.bz2
    

(intro-ods) ➜  python anaconda whoami                   
Using Anaconda API: https://api.anaconda.org
Username: ijstokes
Member since: Wed Jul 31 02:19:49 2013
  +description: None
  +url: http://about.me/ijstokes
  +user_type: user
  +name: Ian Stokes-Rees
  +location: Syracuse, NY
  +company: Continuum Analytics
```

and

<img width="1055" alt="screen shot 2016-11-06 at 1 07 25 am" src="https://cloud.githubusercontent.com/assets/293525/20035923/6c33490a-a3bd-11e6-9667-405d55ea2c33.png">

**Comment by kalefranz** [comment]
This has to just be a caching issue.  `conda clean -i`
