### ISSUE TITLE
authorization error during package install reported as Conda failure

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3821]
Something funny is going on here.  I am trying to install a package which I am authorized to install.  I am logged in on my laptop, and I've checked Anaconda Cloud and see my name on the package owner list.  When I go to `conda install` it the correct package is identified but then when Conda attempts to download the package there is an error.  The stack trace in the error suggests that it is a 401 HTTP unauthorized error.  Trace below.  I also reported this to the specific package maintainers in this GH issue: https://github.com/conda/conda/issues/3820

```
(intro-ods) ➜  python cat ~/.condarc 
channels:
#  - https://conda.anaconda.org/t/CQgCcFM1Mfma/anaconda-mosaic
    - r
    - defaults
self_update: false
channel_priority: false
```

```
(intro-ods) ➜  python anaconda whoami
Using Anaconda API: https://api.anaconda.org
Username: ijstokes
Member since: Wed Jul 31 02:19:49 2013
  +name: Ian Stokes-Rees
  +user_type: user
  +url: http://about.me/ijstokes
  +description: None
  +company: Continuum Analytics
  +location: Syracuse, NY
```

```
(intro-ods) ➜  python conda install -f nb_anaconda_theme
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/ijstokes/anaconda/envs/intro-ods:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    nb_anaconda_theme-0.1.1    |           py35_0          27 KB  anaconda-nb-extensions

The following NEW packages will be INSTALLED:

    nb_anaconda_theme: 0.1.1-py35_0 anaconda-nb-extensions

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda/envs/intro-ods
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/envs/intro-ods/bin/conda install -f nb_anaconda_theme`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/osx-64/nb_anaconda_theme-0.1.1-py35_0.tar.bz2: https://conda.anaconda.org/t/<TOKEN>/anaconda-nb-extensions/osx-64/nb_anaconda_theme-0.1.1-py35_0.tar.bz2
```

**Comment by ijstokes** [comment]
Too late at night.  That other issue was also on the Conda repository.  I'll close this one and mark it as a duplicate.
