### ISSUE TITLE
`conda env upload` to an org does not appear to be possible

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#3824]
I just tried to upload a conda-env `environment.yml` file to an organization I am a part of.  I can upload notebooks there, so I know I am authorized.  But when I tried the following command it failed with a stack trace and I was told to report it here.

```
$ conda env upload -f dspyr.yml datasciencepythonr/dspyr
Using Anaconda API: https://api.anaconda.org
Uploading environment datasciencepythonr/dspyr to anaconda-server (https://api.anaconda.org)... 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda/envs/intro-ods
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False



`$ /Users/ijstokes/anaconda/bin/conda-env upload -f dspyr.yml datasciencepythonr/dspyr`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/cli/main_upload.py", line 101, in execute
        info = uploader.upload()
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 81, in upload
        if self.is_ready():
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 94, in is_ready
        return self.ensure_package_namespace() and self.ensure_distribution()
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 103, in ensure_package_namespace
        self.binstar.add_package(self.username, self.packagename, self.summary)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 335, in add_package
        self._check_response(res)
      File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 200, in _check_response
        raise ErrCls(msg, res.status_code)
    NotFound: (u'The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.', 404)
```

**Comment by ijstokes** [comment]
OK, I dug around a bit and experimented and discovered that I can just use `conda upload` and the automatic type detection figures out this is an environment file, but then the file view when clicking on the (i) button doesn't actually show the contents.  It is there, because `conda env create datasciencepython/dspyr` works as expected.  But something weird is happening.

I would suggest that `conda env upload` be removed (or deprecated then removed), in the same way I think `conda notebook upload` has been removed.

For this specific case, see: https://anaconda.org/datasciencepythonr/dspyr/files

<img width="1077" alt="screen shot 2016-11-06 at 10 48 23 pm" src="https://cloud.githubusercontent.com/assets/293525/20047877/ef1567ac-a47d-11e6-98ba-da8a58718d1a.png">

**Comment by ijstokes** [comment]
I wonder: could this be an issue of `.yaml` vs. `.yml`?  The file type was identified properly but the Anaconda Repository viewer isn't reading it properly so I only get file-external meta-data displayed?

**Comment by jerowe** [comment]
I think it should be

```
conda env upload -f dspyr.yml datasciencepythonr
```

The name of the environment is read in from the environment file.

**Comment by jdamato3** [comment]
@ijstokes If you have `anaconda-client` installed and configured, you can upload environment files with the following command to your respective organization:
```
anaconda upload environment.yml -u <org_name>
```

**Comment by kalefranz** [comment]
> I would suggest that conda env upload be removed (or deprecated then removed), in the same way I think conda notebook upload has been removed.

I couldn't agree more.

**Comment by mcg1969** [comment]
Yep, I agree. We shouldn't have `conda env upload`.

**Comment by kalefranz** [comment]
`conda env upload` is deprecated
