### ISSUE TITLE
Newly created Py27 Env won't run Spyder

### ISSUE THREAD

**Issue by dartdog** [conda/conda#3828]
After having the issues described here https://github.com/conda/conda/issues/3827 and here https://github.com/conda/conda/issues/3437 I created a new python 27 environment with anaconda:

  conda create -n py27n python=2.7 anaconda
installed and tried to start up spyder and got:

source activate py27n
(py27n) tom@tomServal:~$ spyder
Traceback (most recent call last):
  File "/home/tom/anaconda3/envs/py27n/bin/spyder", line 6, in <module>
    sys.exit(spyder.app.start.main())
  File "/home/tom/anaconda3/envs/py27n/lib/python2.7/site-packages/spyder/app/start.py", line 103, in main
    from spyder.app import mainwindow
  File "/home/tom/anaconda3/envs/py27n/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 92, in <module>
    from qtpy import QtWebEngineWidgets  # analysis:ignore
  File "/home/tom/anaconda3/envs/py27n/lib/python2.7/site-packages/qtpy/QtWebEngineWidgets.py", line 26, in <module>
    from PyQt5.QtWebKitWidgets import QWebPage as QWebEnginePage
ImportError: libiconv.so.2: cannot open shared object file: No such file or directory

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1708
