### ISSUE TITLE
Conda skeleton occasionally chokes on cpan module

### ISSUE THREAD

**Issue by jerowe** [conda/conda#3835]
```
conda skeleton cpan Devel::CheckBin
```

```
INFO:stdoutlog:

.INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.metacpan.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.metacpan.org
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.metacpan.org
Traceback (most recent call last):
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/bin/conda-skeleton", line 6, in <module>
    sys.exit(conda_build.cli.main_skeleton.main())
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
    return execute(sys.argv[1:])
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
    api.skeletonize(package, args.repo, config=config)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/api.py", line 193, in skeletonize
    recursive=recursive, config=config, **kwargs)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 301, in skeletonize
    recursive=recursive, config=config)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 493, in deps_for_package
    dep_version, perl_version, dependency=True, config=config)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/site-packages/conda_build/skeletons/cpan.py", line 603, in get_release_info
    if (version is not None) and (version != LooseVersion('0') and
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/distutils/version.py", line 46, in __eq__
    c = self._cmp(other)
  File "/home/jillian/.local/easybuild/software/Anaconda3/4.0.0/lib/python3.5/distutils/version.py", line 337, in _cmp
    if self.version < other.version:
TypeError: unorderable types: str() < int()
```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1517

**Comment by kalefranz** [comment]
Hey @jerowe, thanks for your work on this.  And sorry we had some tests failing in master.  There were some time bombs that went off that I've now extended.  If you rebase against master and still have some failures, I'll dive in and take a look.

**Comment by kalefranz** [comment]
Oh! But... `conda skeleton` is a conda-build command.  That's why I moved your issue to that repo :)

**Comment by jerowe** [comment]
@kalefranz, thanks for putting it in the right place. ;-)
