### ISSUE TITLE
conda install mingw libpython

### ISSUE THREAD

**Issue by Jsmilemsj** [conda/conda#3837]
C:\Users\mrtg>conda install mingw libpython
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    mingw-4.7                  |                1        56.1 MB
    libpython-2.0              |           py35_0          40 KB
    conda-4.2.12               |           py35_0         446 KB
    ------------------------------------------------------------
                                           Total:        56.6 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0
    libpython: 2.0-py35_0
    mingw:     4.7-1

The following packages will be UPDATED:

    conda:     4.2.9-py35_0 --> 4.2.12-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00 248.99 kB/s
An unexpected error has occurred.                   | Time: 0:11:30   3.08 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py install mingw libpython`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\response.py", line 232, in _error_catcher
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 488, in readint
o
        n = self.fp.readinto(b)
      File "C:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", li
ne 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\response.py", line 324, in read
        flush_decoder = True
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(h
ost='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 4
19, in download
        for chunk in resp.iter_content(2**14):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", li
ne 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuu
m.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 64
3, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py",
 line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py",
 line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 3
36, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 4
38, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))

    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Progr
am Files\\Anaconda3\\pkgs\\mingw-4.7-1.tar.bz2.part' for writing (HTTPSConnectio
nPool(host='repo.continuum.io', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", l
ine 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.
py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", l
ine 573, in json_progress_bars
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime err
or: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\mingw-4.7-1.tar.bz2.part
' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read tim
ed out.).

**Comment by mingwandroid** [comment]
@kalefranz, do you know why we're getting timeouts here?

Installing in paths with spaces in is can be problematic, but this is probably not related to the issue you have encountered.

The `mingw` package is deprecated, please use `m2w64-toolchain` instead. Can I ask where you read to install `mingw`? This is also probably not related to the issue you have encountered!

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
