### ISSUE TITLE
Install problem and conda

### ISSUE THREAD

**Issue by hmp68239** [conda/conda#3838]
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/heeramani/anaconda3  (writable)
    default environment : /home/heeramani/anaconda3
       envs directories : /home/heeramani/anaconda3/envs
          package cache : /home/heeramani/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/heeramani/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 184, in proxy_manager_for
        **proxy_kwargs
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 43, in SOCKSProxyManager
        raise InvalidSchema("Missing dependencies for SOCKS support.")
    requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/heeramani/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/heeramani/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/heeramani/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 137, in fetch_repodata
        .format(url, filename, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 184, in proxy_manager_for
        **proxy_kwargs
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 43, in SOCKSProxyManager
        raise InvalidSchema("Missing dependencies for SOCKS support.")
    requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 293, in <listcomp>
        for url in urls]
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/home/heeramani/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 137, in fetch_repodata
        .format(url, filename, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.

**Comment by nehaljwani** [comment]
@hmp68239 Could you please share output for the command: `env | grep -i proxy`

**Comment by nehaljwani** [comment]
I could reproduce this like this:
In one tab, type:
```bash
ssh -D 9889 localhost
```
In some other tab:
```bash
export all_proxy=socks5://localhost:9889 # Could have used ALL_PROXY too
```
Download and install latest conda for python 3:
```bash
./Miniconda3-latest-Linux-x86_64.sh -b -p /tmp/scratchconda
```
Activate and run conda install python:
```bash
source /tmp/scratchconda/bin/activate
conda install python
...
...
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.

```
Fix: Install requests with socks support. (a.k.a pysocks?)
```bash
pip install -U requests[socks]
```

Now conda is happy.

**Comment by kalefranz** [comment]
Yes, if you have configuration on your system that `requests` is recognizing for a socks proxy, you'll need to `pip install -U pysocks`.  I don't think the default repo currently have a conda package for pysocks.   Note the [conda-forge pysocks](https://github.com/conda-forge/pysocks-feedstock) version is one that's [specifically noted to be not compatible](https://github.com/kennethreitz/requests/blob/v2.13.0/setup.py#L99) with requests.
