### ISSUE TITLE
Use of enum in python2 causing trouble?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#3844]
```bash
Current conda install:

               platform : linux-64
          conda version : 4.2.11.dev258+b0ce9d4
       conda is private : False
      conda-env version : 4.2.11.dev258+b0ce9d4
    conda-build version : not installed
         python version : 2.7.10.final.0
       requests version : 2.11.1
       root environment : /tmp/blah  (writable)
    default environment : /tmp/blah
       envs directories : /tmp/blah/envs
          package cache : /tmp/blah/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /apps/infrafs1/nwani/.condarc
           offline mode : False
             user-agent : conda/4.2.11.dev258+b0ce9d4 requests/2.11.1 CPython/2.7.10 Linux/4.4.27-200.fc22.trc.1.0.x86_64 Fedora/22 glibc/2.21
                UID:GID : 5645:3037

`$ /tmp/blah/bin/conda create -n blah2 python`

    Traceback (most recent call last):
      File "/tmp/conda/conda/exceptions.py", line 482, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/tmp/conda/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/tmp/conda/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/tmp/conda/conda/cli/install.py", line 377, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/tmp/conda/conda/plan.py", line 652, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/tmp/conda/conda/instructions.py", line 140, in execute_instructions
        cmd(state, arg)
      File "/tmp/conda/conda/instructions.py", line 83, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "/tmp/conda/conda/install.py", line 568, in link
        create_meta(prefix, dist, source_dir, index, files, linktype)
      File "/tmp/conda/conda/core/linked_data.py", line 172, in create_meta
        json.dump(meta, fo, indent=2, sort_keys=True, cls=EntityEncoder)
      File "/usr/lib64/python2.7/json/__init__.py", line 189, in dump
        for chunk in iterable:
      File "/usr/lib64/python2.7/json/encoder.py", line 442, in _iterencode
        o = _default(o)
      File "/tmp/conda/conda/_vendor/auxlib/entity.py", line 880, in default
        return obj.dump()
      File "/tmp/conda/conda/_vendor/auxlib/entity.py", line 777, in dump
        for field in self.__dump_fields())
      File "/usr/lib64/python2.7/collections.py", line 57, in __init__
        self.__update(*args, **kwds)
      File "/tmp/blah/lib64/python2.7/_abcoll.py", line 568, in update
        for key, value in other:
      File "/tmp/conda/conda/_vendor/auxlib/entity.py", line 778, in <genexpr>
        if value is not None or field.nullable)
      File "/tmp/conda/conda/_vendor/auxlib/entity.py", line 558, in dump
        return None if val is None else val.value
    AttributeError: 'Arch' object has no attribute 'value'
```

**Comment by nehaljwani** [comment]
I solved this issue by doing this:

```bash
$ pip uninstall enum
$ pip install enum34
```
