### ISSUE TITLE
Conda list/update/install error

### ISSUE THREAD

**Issue by willhaslam** [conda/conda#3845]
When I try any of conda list/update or install I get the below error. Been working fine for about 6months but perhaps I have installed a bad package?

```
(C:\Anaconda3) U:\Python Scripts>conda list
# packages in environment at C:\Anaconda3:
#
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Anaconda3\Scripts\conda-script.py list`




    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _mai
n
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 227, in
 execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 163, in
 print_packages
        installed = linked(prefix)
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 917, in linke
d
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 909, in linke
d_data
        load_linked_data(prefix, fn[:-5], ignore_channels=ignore_channels)
      File "C:\Anaconda3\lib\site-packages\conda\install.py", line 850, in load_
linked_data
        channel, schannel = Channel(url).url_channel_wtf
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 161, i
n __call__
        c = Channel.from_value(value)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 211, i
n from_value
        return Channel.from_url(value)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 196, i
n from_url
        return parse_conda_channel_url(url)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 132, i
n parse_conda_channel_url
        configured_token) = _read_channel_configuration(scheme, host, port, path
)
      File "C:\Anaconda3\lib\site-packages\conda\models\channel.py", line 115, i
n _read_channel_configuration
        location, name = test_url.rsplit('/', 1)
    ValueError: not enough values to unpack (expected 2, got 1)
```

**Comment by willhaslam** [comment]
I deleted the fiona json file from the conda-meta folder and conda now works
