### ISSUE TITLE
conda-env 2.6.0 is broken on Windows 7

### ISSUE THREAD

**Issue by mivade** [conda/conda#3846]
When trying to activate an environment, I get the following message:

```
The filename, directory name, or volume label syntax is incorrect.
```

I can work around this by manually downgrading to `conda-env` 2.4.2, but since `conda-env` seems to want to upgrade itself whenever installing anything, it's rather painful to keep doing this.

This seems to be related to [this](https://github.com/ContinuumIO/anaconda-issues/issues/487)

**Comment by mivade** [comment]
Potentially related issue: When I use the workaround above and try to `conda install pyqt=4`, I get the following:

```
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 146, in args_fu
nc
    args.func(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 62, in
execute
    install.install(args, parser, 'install')
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 424, in inst
all
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Miniconda3\lib\site-packages\conda\plan.py", line 539, in execute_act
ions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 149, in exe
cute_instructions
    cmd(state, arg)
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 92, in LINK
_CMD
    link(state['prefix'], arg, index=state['index'])
  File "C:\Miniconda3\lib\site-packages\conda\instructions.py", line 88, in link

    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 650, in link
    if not run_script(prefix, dist, 'post-link'):
  File "C:\Miniconda3\lib\site-packages\conda\install.py", line 376, in run_scri
pt
    subprocess.check_call(args, env=env)
  File "C:\Miniconda3\lib\subprocess.py", line 576, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Miniconda3\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Miniconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Miniconda3\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by kalefranz** [comment]
What version of conda are you on?  `conda info`?

**Comment by mivade** [comment]
This was quite a while ago and I don't recall now exactly what version I was using at the time. For the record, the output of `conda info` at present is:

```
    Current conda install:

                   platform : win-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : not installed
             python version : 3.6.0.final.0
           requests version : 2.12.4
           root environment : C:\Users\xyz\Miniconda3  (writable)
        default environment : C:\Users\xyz\Miniconda3
           envs directories : C:\Users\xyz\Miniconda3\envs
                          C:\Users\xyz\AppData\Local\conda\conda\envs
                          C:\Users\xyz\.conda\envs
              package cache : C:\Users\xyz\Miniconda3\pkgs
                          C:\Users\xyz\AppData\Local\conda\conda\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601
```

Since this issue is quite old and I haven't seen this happen recently, I'll close it.
