### ISSUE TITLE
Attempt to upgrade python and spyder after initial install results in the following failures.

### ISSUE THREAD

**Issue by hlaptop1** [conda/conda#3848]
conda install spyder=3.0.1*
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\envs\py3k:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    spyder-3.0.1               |           py35_0         3.0 MB

The following packages will be UPDATED:

    anaconda: 4.2.0-np111py35_0 --> custom-py35_0
    spyder:   3.0.0-py35_0      --> 3.0.1-py35_0

Proceed ([y]/n)? y

Fetching packages ...
spyder-3.0.1-p 100% |###############################| Time: 0:00:00  10.06 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|                  An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\chessbase\.julia\v0.5\Conda\deps\usr  (writable)
    default environment : C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\envs\py3k
       envs directories : C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\envs
          package cache : C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\msys64\home\chessbase\.condarc
           offline mode : False

`$ C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\Scripts\conda-script.py install spyder=3.0.1*`

    Traceback (most recent call last):
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\instructions.py", line 87, in SYMLINK_CONDA_CMD
        symlink_conda(state['prefix'], arg)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\install.py", line 532, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\install.py", line 549, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\chessbase\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\install.py", line 119, in win_conda_bat_redirect
        with open(dst, "w") as f:
    IOError: [Errno 13] Permission denied: u'C:\\Users\\chessbase\\.julia\\v0.5\\Conda\\deps\\usr\\envs\\py3k\\Scripts\\conda'

[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

The conda command disappears from the scripts directory.

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed is conda removing itself during a failed install/update operation.
