### ISSUE TITLE
installation error : conda create -n py2 python=2

### ISSUE THREAD

**Issue by changjurhee** [conda/conda#3850]
I've just installed Anaconda3 (x64, python3.5) which was downloaded from site. then I tried to create python2.7 version of anaconda. 

`C:\Users\Administrator>conda create -n py2 python=2`

Here is log messages below. Do you have any idea? 

```
Fetching package metadata ...SSL verification error: [SSL: CERTIFICATE_VERIFY_FA
ILED] certificate verify failed (_ssl.c:645)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:645)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:645)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:645)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fai
led (_ssl.c:645)
SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify fail
ed (_ssl.c:645)
...
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files\Anaconda3\envs\py2
:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2008_runtime-9.00.30729.1|                2         1.0 MB
    python-2.7.12              |                0        23.5 MB
    setuptools-27.2.0          |           py27_1         755 KB
    wheel-0.29.0               |           py27_0         121 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:        26.9 MB

The following NEW packages will be INSTALLED:

    pip:            8.1.2-py27_0
    python:         2.7.12-0
    setuptools:     27.2.0-py27_1
    vs2008_runtime: 9.00.30729.1-2
    wheel:          0.29.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/vs2008_runtime-9
.00.30729.1-2.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False



`$ C:\Program Files\Anaconda3\Scripts\conda-script.py create -n py2 python=2`




    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\util\ssl_.py", line 308, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 377, in wrap_socket
        _context=self)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 752, in __init__
        self.do_handshake()
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 988, in do_handshake
        self._sslobj.do_handshake()
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 633, in do_handshake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_s
sl.c:645)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 423, in send
        timeout=timeout
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urlli
b3\connectionpool.py", line 621, in urlopen
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAIL
ED] certificate verify failed (_ssl.c:645)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 3
77, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3
.05, 27))
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\sessions.py",
line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\adapters.py",
line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed (_ssl.c:645)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 64
3, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py",
 line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py",
 line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 3
36, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 4
03, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: [SSL: C
ERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645): https://repo.c
ontinuum.io/pkgs/free/win-64/vs2008_runtime-9.00.30729.1-2.tar.bz2


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", l
ine 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", lin
e 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.p
y", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", l
ine 573, in json_progress_bars
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py",
line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime err
or: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
 (_ssl.c:645): https://repo.continuum.io/pkgs/free/win-64/vs2008_runtime-9.00.30
729.1-2.tar.bz2



C:\Users\Administrator>
```

**Comment by nehaljwani** [comment]
@changjurhee Are you behind a corporate proxy? I am not sure, but based on the output, it seems like direct HTTPS connections are being intercepted in between.

**Comment by yubrshen** [comment]
I'm having probably the same issue. I'm in China, behind the evil "iron" wall of Internet, the download speed is generally slow range from 10KB/s to 500KB/s. This problem seems happened with certain module, where the download speed is less than 30KB/s. It seems that conda installer is not synchronized, dealing with read time out incorrectly, and continued as if there were successful and complete download on the contrary. 

In this case, llvm is the module having slow download problem. 

I tried both with proxy or without, it would have the same problem. 

Here is the trace, which is simpler to illustrate the observation:
---
llvmlite-0An unexpected error has occurred.          | Time: 0:04:21  17.33 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/yubrshen/anaconda2  (writable)
    default environment : /home/yubrshen/anaconda2
       envs directories : /home/yubrshen/anaconda2/envs
          package cache : /home/yubrshen/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /home/yubrshen/anaconda2/bin/conda create -n py35 python=3.5 anaconda`




    Traceback (most recent call last):
      File "/home/yubrshen/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/yubrshen/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/yubrshen/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/yubrshen/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/yubrshen/anaconda2/pkgs/llvmlite-0.13.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by yubrshen** [comment]
For my situation of poor download speed, it would be great, if I could resume from failure. As before the failure much modules have been downloaded, now, when I repeat: 
`$ /home/yubrshen/anaconda2/bin/conda create -n py35 python=3.5 anaconda`
I would get the error message:
'CondaValueError: Value error: prefix already exists: /home/yubrshen/anaconda2/envs/py35'

so far, I have to remove the partial installation by 
conda remove py35

which remove all the downloaded, with the slow Internet speed, it would make my retry still unlikely to succeed! If it could resume from the partial download, then there is chance that the read time out would not happen.

**Comment by yubrshen** [comment]
I'm trying to move the marker of installation to fool conda create:
mv anaconda2/envs/py35 anaconda2/envs/py35.old

and repeat:
`$ /home/yubrshen/anaconda2/bin/conda create -n py35 python=3.5 anaconda`

It indeed start downloading from the last failure, but it still did download of the already download modules, no saving at all.

**Comment by yubrshen** [comment]
It also puzzles me that when I download with Anaconda's installer:
`bash Anaconda3-4.2.0-Linux-x86_64.sh`

in the same network environment, it never fail. 

Do they download from different source?

**Comment by kalefranz** [comment]
We've extended the timeouts in `4.2.13`, so `conda update conda` might help.  In the forthcoming `4.3`, the timeouts will be configurable.

For `Anaconda3-4.2.0-Linux-x86_64.sh` if you're downloading it with your browser, it's probably doing partial content retries for you.  `wget` might do that for you too.

Follow issue #3937
