### ISSUE TITLE
update conda met condaRuntimeError: Runtime error

### ISSUE THREAD

**Issue by yongyanghz** [conda/conda#3858]
I used the following shell command to update the anaconda:

```
conda update conda
conda update anaconda

```
And I met the following issues:

```
Fetching packages ...
expat-2.1.0-0. 100% |################################| Time: 0:00:02 171.12 kB/s
icu-54.1-0.tar 100% |################################| Time: 0:02:00  97.95 kB/s
jpeg-8d-2.tar. 100% |################################| Time: 0:00:07 108.94 kB/s
libgcc-4.8.5-2 100% |################################| Time: 0:00:14  41.70 kB/s
libxcb-1.12-0. 100% |################################| Time: 0:00:15  97.73 kB/s
openssl-1.0.2j 100% |################################| Time: 0:00:21 152.64 kB/s
curl-7.49.0-1. 100% |################################| Time: 0:00:01 377.39 kB/s
dbus-1.10.10-0 100% |################################| Time: 0:00:24 103.51 kB/s
glib-2.43.0-1. 100% |################################| Time: 0:01:03  89.01 kB/s
hdf5-1.8.17-1. 100% |################################| Time: 0:00:15 133.43 kB/s
_license-1.1-p 100% |################################| Time: 0:00:01 210.58 kB/s
alabaster-0.7. 100% |################################| Time: 0:00:00  27.45 kB/s
beautifulsoup4 100% |################################| Time: 0:00:00 127.34 kB/s
boto-2.42.0-py 100% |################################| Time: 0:00:02 470.66 kB/s
cython-0.24.1- 100% |################################| Time: 0:00:09 603.59 kB/s
filelock-2.0.6 100% |################################| Time: 0:00:00  12.49 kB/s
gstreamer-1.8. 100% |################################| Time: 0:00:47  55.93 kB/s
lazy-object-pr 100% |################################| Time: 0:00:00  59.24 kB/s
mistune-0.7.3- 100% |################################| Time: 0:00:03 148.37 kB/s
pkginfo-1.3.2- 100% |################################| Time: 0:00:00  50.19 kB/s
ply-3.9-py27_0 100% |################################| Time: 0:00:03  21.25 kB/s
psutil-4.3.1-p 100% |################################| Time: 0:00:29   7.78 kB/s
pyflakes-1.3.0 100% |################################| Time: 0:00:01  47.26 kB/s
pytz-2016.6.1- 100% |################################| Time: 0:00:05  31.07 kB/s
pyyaml-3.12-py 100% |################################| Time: 0:00:02 134.58 kB/s
pyzmq-15.4.0-p 100% |################################| Time: 0:00:25  28.05 kB/s
qtpy-1.1.2-py2 100% |################################| Time: 0:00:00  66.40 kB/s
requests-2.11. 100% |################################| Time: 0:00:05 119.10 kB/s
setuptools-27. 100% |################################| Time: 0:00:02 263.15 kB/s
sip-4.18-py27_ 100% |################################| Time: 0:00:05  49.74 kB/s
wcwidth-0.1.7- 100% |################################| Time: 0:00:00  28.28 kB/s
werkzeug-0.11. 100% |################################| Time: 0:00:03  89.90 kB/s
wrapt-1.10.6-p 100% |################################| Time: 0:00:05  10.50 kB/s
xlsxwriter-0.9 100% |################################| Time: 0:00:05  37.02 kB/s
astroid-1.4.7- 100% |################################| Time: 0:00:01 205.33 kB/s
babel-2.3.4-py 100% |################################| Time: 0:00:19 264.65 kB/s
cffi-1.7.0-py2 100% |################################| Time: 0:00:36   9.06 kB/s
configparser-3 100% |################################| Time: 0:00:03  10.06 kB/s
gevent-1.1.2-p 100% |################################| Time: 0:00:14  75.11 kB/s
gst-plugins-ba 100% |################################| Time: 0:00:57  57.66 kB/s
h5py-2.6.0-np1 100% |################################| Time: 0:01:24  29.09 kB/s
llvmlite-0.13. 100% |################################| Time: 0:07:05  18.56 kB/s
lxml-3.6.4-py2 100% |################################| Time: 0:00:02   1.02 MB/s
numexpr-2.6.1- 100% |################################| Time: 0:00:02 149.19 kB/s
partd-0.3.6-py 100% |################################| Time: 0:00:00  26.91 kB/s
pillow-3.3.1-p 100% |################################| Time: 0:00:06 122.62 kB/s
prompt_toolkit 100% |################################| Time: 0:00:48   6.25 kB/s
qtawesome-0.3. 100% |################################| Time: 0:00:01 139.37 kB/s
scipy-0.18.1-n  38% |############         An unexpected error has occurred. kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:
```
    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /home/yangyong/anaconda2  (writable)
    default environment : /home/yangyong/anaconda2
       envs directories : /home/yangyong/anaconda2/envs
          package cache : /home/yangyong/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/yangyong/anaconda2/bin/conda update anaconda`

    Traceback (most recent call last):
      File "/home/yangyong/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/yangyong/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/yangyong/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/yangyong/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/yangyong/anaconda2/pkgs/scipy-0.18.1-np111py27_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by kalefranz** [comment]
This is just a read timeout.  We've extended the timeouts in conda `4.2.13`.  After you `conda update conda`, does the issue persist?

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
