### ISSUE TITLE
installing, unexpected error has occurred

### ISSUE THREAD

**Issue by dan-svd** [conda/conda#3861]
(bunnies) C:\Users\dangus3>conda install -c anaconda bottleneck=1.1.0
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\envs\bunnies:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-11.3.3                 |                1       110.0 MB  anaconda
    numpy-1.11.2               |           py35_0         3.3 MB  anaconda
    bottleneck-1.1.0           |      np111py35_0         191 KB  anaconda
    ------------------------------------------------------------
                                           Total:       113.5 MB

The following NEW packages will be INSTALLED:

    bottleneck: 1.1.0-np111py35_0 anaconda
    mkl:        11.3.3-1          anaconda
    numpy:      1.11.2-py35_0     anaconda

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
mkl-11.3.3-1.t 100% |###############################| Time: 0:02:10 881.04 kB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\dangus3\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\envs\bunnies
       envs directories : C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install -c anaconda bottleneck=1.1.0`

    Traceback (most recent call last):
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 401, in download
        with FileLock(dst_path):
      File "C:\Users\dangus3\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\lock.py", line 70, in __init__
        assert isdir(dirname(self.path_to_lock)), "{0} doesn't exist".format(self.path_to_lock)
    AssertionError: C:\Users\dangus3\.conda\envs\.pkgs\numpy-1.11.2-py35_0.tar.bz2 doesn't exist

(bunnies) C:\Users\dangus3>

**Comment by kalefranz** [comment]
Something looks off here.  I don't remember seeing an error like this before though.  Were you able to work around the problem?  It's touching code that has to do with locking, which we're removing in the forthcoming conda `4.3` release.

**Comment by dan-svd** [comment]
All is good now , I just switched to a newer release of everything. And also ended up not using that package. Prbly just some weird glitch.

btw : Thanks for making Conda, so that Python is as easy to use as R (with the packageinstalling and versioning of Python, that is) !!

**Comment by rgrinberg** [comment]
I've seen an error like this on Arch Linux. I think I might have used pip to remove a conda package:

```
Traceback (most recent call last):
      File "/usr/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/usr/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/usr/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/usr/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/usr/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/usr/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/usr/lib/python3.5/site-packages/conda/fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/usr/lib/python3.5/site-packages/conda/fetch.py", line 401, in download
        with FileLock(dst_path):
      File "/usr/lib/python3.5/site-packages/conda/lock.py", line 70, in __init__
        assert isdir(dirname(self.path_to_lock)), "{0} doesn't exist".format(self.path_to_lock)
    AssertionError: /usr/pkgs/pandas-0.19.1-np111py27_0.tar.bz2 doesn't exist

```
