### ISSUE TITLE
Creating new Conda environment fails on Mac OS X (condo 4.2.12)

### ISSUE THREAD

**Issue by malzantot** [conda/conda#3863]
Hello,

I am using conda 4.2.12 on Mac OSX (10.11.3). Whenever I attempt to create a new environment using the command:
`conda env create -n test_env`
It fails with the following error message:

> Traceback (most recent call last):
      File "/Users/malzantot/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/malzantot/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/Users/malzantot/anaconda3/lib/python3.5/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Invalid name, try the format: user/package
    test_env does not exist or can't be accessed
    Conda Env Exception: environment.yml file not found
    There is no requirements.txt

**Comment by malzantot** [comment]
I found that there was a problem with my command.  Problem is solved, when I used 
`conda create -n test_env`
