### ISSUE TITLE
 failed to parse CPython sys.version: '2.7.12 |Anaconda 4.2.0 (64-bit)|'

### ISSUE THREAD

**Issue by KarishmaGhiya** [conda/conda#3867]
conda create -n my_root --clone=C:\Program Files\Anaconda2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 407, in get_info
    args.func(args, p)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 155, in execute
    from conda.api import get_index
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\fetch.py", line 27, in <module>
    from .connection import CondaSession, RETRIES
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\connection.py", line 58, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1498, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1463, in _sys_version
    repr(sys_version))

'failed to parse CPython sys.version: '2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]'

**Comment by kalefranz** [comment]
I'm guessing `conda update conda` should fix your problem.

**Comment by tyluckyma** [comment]
I typed `conda update conda` in powershell and met the similar problem, which is showing the following:

```
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\exceptions.py", line 407, in get_info
    args.func(args, p)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 155, in execute
    from conda.api import get_index
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\fetch.py", line 27, in <module>
    from .connection import CondaSession, RETRIES
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\connection.py", line 58, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1458, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1420, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.12 |Anaconda 4.2.0 (64-bit)| (default, Jun 29 2016, 11:07:13) [MSC v.1500 64 bit (AMD64)]'
```
