### ISSUE TITLE
cannot update conda in ArcGIS Pro

### ISSUE THREAD

**Issue by yuan7220** [conda/conda#3884]
[arcgispro-py3] C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3>conda update --all
Fetching package metadata: ....An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Program Files\ArcGIS\Pro\bin\Python\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\install.py", line 240, in install
    prefix=prefix)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\cli\common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\api.py", line 43, in get_index
    unknown=unknown)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\utils.py", line 43, in __call__
    value = self.func(*args, **kw)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\concurrent\futures\_base.py", line 398, in result
    return self.__get_result()
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\concurrent\futures\_base.py", line 357, in __get_result
    raise self._exception
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\site-packages\conda\fetch.py", line 103, in fetch_repodata
    cache = json.loads(bz2.decompress(resp.content).decode('utf-8'))
  File "C:\Program Files\ArcGIS\Pro\bin\Python\lib\bz2.py", line 348, in decompress
    res = decomp.decompress(data)
OSError: Invalid data stream

arcgispro-py3] C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3>conda info
Current conda install:

             platform : win-64
        conda version : 4.0.6
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Program Files\ArcGIS\Pro\bin\Python  (writable)
  default environment : C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3
     envs directories : C:\Program Files\ArcGIS\Pro\bin\Python\envs
        package cache : C:\Program Files\ArcGIS\Pro\bin\Python\pkgs
         channel URLs : http://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/
                        http://www.lfd.uci.edu/~gohlke/pythonlibs/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : C:\Users\mxy141230\.condarc
    is foreign system : False

**Comment by kalefranz** [comment]
Our CDN has been has been flakey today.  I'm still investigating.  I'm guessing it'll work if you try again though.  Maybe try `conda update conda` first.

Go ahead and file a new issue if the problem persists.

**Comment by kalefranz** [comment]
I take back what I said ^^^ above.

The channel http://www.lfd.uci.edu/~gohlke/pythonlibs/ is not behaving like a spec-compliant conda channel should.  For example,

    curl http://www.lfd.uci.edu/~gohlke/pythonlibs/win-64/repodata.json

should *always* return valid json.  It's not.  Even though it's responding HTTP 200.

Remove that channel and try again.

**Comment by yuan7220** [comment]
Thanks for helping.
How should I remove the channel?

Thanks
May

**Comment by kalefranz** [comment]
`conda config --remove channels http://www.lfd.uci.edu/~gohlke/pythonlibs` should work

**Comment by yuan7220** [comment]
Sorry to keep bothering you. I followed the suggestion but received the following message

CondaKeyError: Error with key 'channels': 'http://www.lfd.uci.edu/~gohlke/pythonlibs' is not in the 'channels' key of the config file

May
