### ISSUE TITLE
Central conda install - how to set condarc to use user cache instead of root cache?

### ISSUE THREAD

**Issue by sandhujasmine** [conda/conda#3885]
I'm testing out a centralized conda install and getting 'PermissionDenied' errors. I see #1329 is open; however, from reading some of the comments, it seems like this should work. 

I've set `CONDA_ENVS_PATH`
```
$ echo $CONDA_ENVS_PATH
/home/ec2-user/envs
```

However, still seeing the `package cache` below point to central location. 
```
$ conda create -n test python
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/ec2-user/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.0.2j             |                0         3.2 MB  anaconda
    readline-6.2               |                2         606 KB  anaconda
    sqlite-3.13.0              |                0         4.0 MB  anaconda
    tk-8.5.18                  |                0         1.9 MB  anaconda
    zlib-1.2.8                 |                3         101 KB  anaconda
    python-2.7.12              |                1        12.1 MB  anaconda
    setuptools-27.2.0          |           py27_0         521 KB  anaconda
    wheel-0.29.0               |           py27_0          81 KB  anaconda
    pip-9.0.1                  |           py27_0         1.6 MB  anaconda
    ------------------------------------------------------------
                                           Total:        23.9 MB

The following NEW packages will be INSTALLED:

    openssl:    1.0.2j-0      anaconda
    pip:        9.0.1-py27_0  anaconda
    python:     2.7.12-1      anaconda
    readline:   6.2-2         anaconda
    setuptools: 27.2.0-py27_0 anaconda
    sqlite:     3.13.0-0      anaconda
    tk:         8.5.18-0      anaconda
    wheel:      0.29.0-py27_0 anaconda
    zlib:       1.2.8-3       anaconda

Proceed ([y]/n)? y

Fetching packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 13]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /opt/miniconda2  (read only)
    default environment : /opt/miniconda2
       envs directories : /home/ec2-user/envs
                          /home/ec2-user/.conda/envs
                          /opt/miniconda2/envs
          package cache : /home/ec2-user/envs/.pkgs
                          /home/ec2-user/.conda/envs/.pkgs
                          /opt/miniconda2/pkgs
           channel URLs : https:xxx.xxx.xxx/conda/anaconda/linux-64
                          https://xxx.xxx.xxx/conda/anaconda/noarch
                          https://xxx.xxx.xxx/conda/r-channel/linux-64
                          https://xxx.xxx.xxx/conda/r-channel/noarch
            config file : /home/ec2-user/.condarc
           offline mode : False



`$ /opt/miniconda2/bin/conda create -n test python`




    Traceback (most recent call last):
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/opt/miniconda2/pkgs/openssl-1.0.2j-0.tar.bz2.part' for writing ([Errno 13] Permission denied: u'/opt/miniconda2/pkgs/openssl-1.0.2j-0.tar.bz2.part').
```

**Comment by kalefranz** [comment]
Not yet, but soon...  See https://github.com/conda/conda/issues/1329#issuecomment-255640965

**Comment by kalefranz** [comment]
If coming to this issue via google, setting `pkgs_dirs` configuration or `CONDA_PKGS_DIRS` environment variable is the correct way to customize package cache locations.  Package cache locations are no longer coupled to environment locations.
