### ISSUE TITLE
conda create --clone root -n xxxx destroys root env

### ISSUE THREAD

**Issue by jgibart** [conda/conda#3896]
I'm trying to perfrom full offline installations/

I have installed latest Miniconda ( 4.2.12 ) on linux from the sh installer
./Miniconda3-latest-Linux-x86_64.sh -p /opt/Rbis -b

so far cloning environment works
/opt/Rbis/bin/conda create --clone root  -n bis2 --offline

Then I try to install offline a bundle ( that  I created from  all bz2 files that I get when doing 
/opt/Rbis/bin/conda install -c r r-essentials=3.3.1)

/opt/Rbis/bin/conda install -c r --offline /tmp/r-essentials_3.3.1.tar

Installation goes fine, R and packages work fine. I see in pkg directory bz2 and expanded packages. But now cloning an environment doesnt work at all ( and destroys the root env ). After failed installation,  pkg folder is back to what was present BEFORE r-essentials install.

/opt/Rbis/bin/conda create --clone root  -n bis3 --offline

Source:      /opt/Rbis
Destination: /opt/Rbis/envs/bis4
The following packages cannot be cloned out of the root environment:
 - conda-4.2.12-py35_0
Packages: 130
Files: 0
Pruning fetched packages from the cache ...
Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /opt/Rbis  (writable)
    default environment : /opt/Rbis
       envs directories : /opt/Rbis/envs
          package cache : /opt/Rbis/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/linux-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
            config file : None
           offline mode : True

`$ /opt/Rbis/bin/conda create --clone root -n bis4 --offline`

    Traceback (most recent call last):
      File "/opt/Rbis/lib/python3.5/site-packages/conda/fetch.py", line 405, in download
        resp.raise_for_status()
      File "/opt/Rbis/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: None for url: file:///tmp/tmph6eb__nz/pkgs/bzip2-1.0.6-3.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/Rbis/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/Rbis/lib/python3.5/site-packages/conda/cli/install.py", line 228, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/cli/install.py", line 90, in clone
        index_args=index_args)
      File "/opt/Rbis/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/opt/Rbis/lib/python3.5/site-packages/conda/cli/install.py", line 90, in clone
        index_args=index_args)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/misc.py", line 387, in clone_env
        force_extract=False, index_args=index_args)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/misc.py", line 187, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/opt/Rbis/lib/python3.5/site-packages/conda/fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/opt/Rbis/lib/python3.5/site-packages/conda/fetch.py", line 409, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 404 Client Error: None for url: file:///tmp/tmph6eb__nz/pkgs/bzip2-1.0.6-3.tar.bz2: file:///tmp/tmph6eb__nz/pkgs/bzip2-1.0.6-3.tar.bz2

Any solution to propose ?

Thanks

**Comment by kalefranz** [comment]
This is a file not found error.  `/tmp/tmph6eb__nz/pkgs/bzip2-1.0.6-3.tar.bz2` doesn't exist.
