### ISSUE TITLE
Latest master appears to be incompatible with conda-build

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#3907]
I'm getting the following backtrace:

```
Traceback (most recent call last):
  File "/Users/ray/mc-x64-2.7/bin/conda-build", line 11, in <module>
    load_entry_point('conda-build==0+unknown', 'console_scripts', 'conda-build')()
  File "/Volumes/VMware Shared Folders/conda/conda-build/conda_build/cli/main_build.py", line 242, in main
    execute(sys.argv[1:])
  File "/Volumes/VMware Shared Folders/conda/conda-build/conda_build/cli/main_build.py", line 234, in execute
    already_built=None, config=config)
  File "/Volumes/VMware Shared Folders/conda/conda-build/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/Volumes/VMware Shared Folders/conda/conda-build/conda_build/build.py", line 1078, in build_tree
    test(metadata, config=recipe_config)
  File "/Volumes/VMware Shared Folders/conda/conda-build/conda_build/build.py", line 876, in test
    clean_pkg_cache(m.dist(), config.timeout)
  File "/Volumes/VMware Shared Folders/conda/conda-build/conda_build/build.py", line 842, in clean_pkg_cache
    plan.execute_plan(rmplan)
  File "/Users/ray/mc-x64-2.7/lib/python2.7/site-packages/conda/plan.py", line 681, in execute_plan
    inst.execute_instructions(plan, index, verbose)
  File "/Users/ray/mc-x64-2.7/lib/python2.7/site-packages/conda/instructions.py", line 144, in execute_instructions
    cmd(state, arg)
  File "/Users/ray/mc-x64-2.7/lib/python2.7/site-packages/conda/instructions.py", line 65, in RM_EXTRACTED_CMD
    assert isinstance(arg, Dist)
```

**Comment by soapy1** [comment]
This is a known issue and is being addressed with https://github.com/conda/conda/pull/3905
In the mean time I've been using conda's `4.2.x` branch instead of master

**Comment by mingwandroid** [comment]
Thanks @soapy1

**Comment by mingwandroid** [comment]
Closing as dupe.
