### ISSUE TITLE
conda install bug

### ISSUE THREAD

**Issue by shabscan** [conda/conda#3913]
Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.6.final.0
       requests version : 2.12.1
       root environment : /usr  (writable)
    default environment : /usr
       envs directories : /usr/envs
          package cache : /usr/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /usr/local/bin/conda install anaconda`

    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/usr/local/lib/python2.7/dist-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/usr/local/lib/python2.7/dist-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/usr/local/lib/python2.7/dist-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/usr/local/lib/python2.7/dist-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/usr/local/lib/python2.7/dist-packages/conda/install.py", line 803, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "/usr/local/lib/python2.7/dist-packages/conda/common/disk.py", line 144, in exp_backoff_fn
        return fn(*args, **kwargs)
    OSError: [Errno 13] Permission denied

**Comment by kalefranz** [comment]
Permissions errors and multi-user/read-only installs have been fixed in later versions of conda 4.3.  Also fixed with transactions in 4.3 is conda removing itself during a failed install/update operation.
