### ISSUE TITLE
Cannot able to update or install any packages using conda in Windows 10

### ISSUE THREAD

**Issue by kishorenayar** [conda/conda#3922]
When ever I tried to install any packages using conda it is failing. 

**Executed Command :** **conda upgrade --all**

When the conda tries to install **qt-5.6.0-vc14_** this particular package, I'm getting the following error.

An unexpected error has occurred.#####################                   |  63%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 2.6.0
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : D:\Anaconda  (writable)
    default environment : D:\Anaconda
       envs directories : D:\Anaconda\envs
          package cache : D:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ D:\Anaconda\Scripts\conda-script.py upgrade --all`

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main
      File "D:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 405, in install
      File "D:\Anaconda\lib\site-packages\conda\plan.py", line 643, in execute_actions
      File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
      File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
      File "D:\Anaconda\lib\site-packages\conda\install.py", line 992, in link
      File "D:\Anaconda\lib\site-packages\conda\install.py", line 495, in run_script
      File "D:\Anaconda\lib\subprocess.py", line 576, in check_call
        retcode = call(*popenargs, **kwargs)
      File "D:\Anaconda\lib\subprocess.py", line 557, in call
        with Popen(*popenargs, **kwargs) as p:
      File "D:\Anaconda\lib\subprocess.py", line 947, in __init__
        restore_signals, start_new_session)
      File "D:\Anaconda\lib\subprocess.py", line 1224, in _execute_child
        startupinfo)
    FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by kalefranz** [comment]
Looks like a post-install script issue with the package.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1253
