### ISSUE TITLE
Error obtained when trying to conda install 

### ISSUE THREAD

**Issue by femibyte** [conda/conda#3923]
Hi I obtained the error below when I ran

`conda install --channel https://conda.anaconda.org/conda-forge tinydb`

```
The following NEW packages will be INSTALLED:


    conda:     4.1.12-py27_0 conda-forge
    conda-env: 2.5.2-py27_0  conda-forge
    tinydb:    3.2.0-py27_0  conda-forge

Proceed ([y]/n)? y

Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : not installed
    conda-build version : 0+unknown
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /Users/myuser/local/anaconda2  (writable)
    default environment : /Users/myuser/local/anaconda2
       envs directories : /Users/myuser/local/anaconda2/envs
          package cache : /Users/myuser/local/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/myuser/.condarc
           offline mode : False



`$ /Users/myuser/local/anaconda2/bin/conda install --channel https://conda.anaconda.org/conda-forge tinydb`




    Traceback (most recent call last):
      File "/Users/ljx417/local/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ljx417/local/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/ljx417/local/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ljx417/local/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Invalid mode: <conda.install.FileMode object at 0x10cc98f90>
```

**Comment by kalefranz** [comment]
I'm guessing this also hosed your current conda install.  That was fixed in conda 4.3 with transactions.  Hopefully you're running on conda 4.3 now and life is good.
