### ISSUE TITLE
Conda conda-build incompatibility.

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#3926]
Traceback (most recent call last):
  File "/opt/pycharm-community/helpers/pydev/pydevd.py", line 1580, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/opt/pycharm-community/helpers/pydev/pydevd.py", line 964, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/ray/conda/conda-build/conda_build/cli/main_build.py", line 258, in <module>
    main()
  File "/home/ray/conda/conda-build/conda_build/cli/main_build.py", line 247, in main
    execute(sys.argv[1:])
  File "/home/ray/conda/conda-build/conda_build/cli/main_build.py", line 239, in execute
    already_built=None, config=config, noverify=args.no_verify)
  File "/home/ray/conda/conda-build/conda_build/api.py", line 77, in build
    need_source_download=need_source_download, config=config)
  File "/home/ray/conda/conda-build/conda_build/build.py", line 1201, in build_tree
    config=recipe_config)
  File "/home/ray/conda/conda-build/conda_build/build.py", line 732, in build
    create_env(config.build_prefix, specs, config=config)
  File "/home/ray/conda/conda-build/conda_build/build.py", line 638, in create_env
    warn_on_old_conda_build(index=index)
  File "/home/ray/conda/conda-build/conda_build/build.py", line 683, in warn_on_old_conda_build
    installed_version = get_installed_conda_build_version() or "0.0.0"
  File "/home/ray/conda/conda-build/conda_build/build.py", line 653, in get_installed_conda_build_version
    if dist.split('::', 1)[-1].rsplit('-', 2)[0] == 'conda-build']
AttributeError: 'Dist' object has no attribute 'split'

**Comment by mingwandroid** [comment]
Hi @kalefranz, I ran into this just now trying to use the latest of conda with the latest of conda-build. Seems it is due to the dist refactoring so that it is an object.

**Comment by kalefranz** [comment]
https://github.com/conda/conda/pull/3909

**Comment by kalefranz** [comment]
Fixed with #3909

**Comment by mingwandroid** [comment]
Thanks!
