### ISSUE TITLE
upgrading from requests 2.11 to requests 2.12 broke conda installation - can't update any packages 

### ISSUE THREAD

**Issue by davidslac** [conda/conda#3928]
I updated requests to 2.12.1 in my conda root, and it appears to have broken my installation. I am getting
```
$ /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/manage/bin/conda update --all`




    Traceback (most recent call last):
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 305, in fetch_index
        for url in urls]
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
        r.content
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/models.py", line 772, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/models.py", line 705, in generate
        chunk = self.raw.read(chunk_size)
    AttributeError: 'exceptions.OSError' object has no attribute 'read'

```
what is worse, is that I cannot downgrade requests. I am getting the same kind of error when I do

```
conda install requests=2.11
```
in the root environment.

Is their anyway to repair my conda installation? Or am I going to have to delete it and rebuild from scratch?

**Comment by kalefranz** [comment]
@ilanschnell Can you adjust the conda metadata accordingly here? Conda 4.3 will be the first to support requests 2.12.0. All conda < 4.3 should cap requests at 2.11.*.

**Comment by kalefranz** [comment]
On repairing conda installation, try `conda list --revisions` and `conda install --rev REVNUM` to roll back. If that doesn't work, easiest fix is something similar to 

    wget  http://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
    bash Miniconda2-latest-Linux-x86_64.sh -bfp PATH_TO_CONDA_ROOT

**Comment by ilanschnell** [comment]
Does `requests` 2.12. break all existing versions of conda?

**Comment by davidslac** [comment]
Hi Kale,

Unfortunately

conda install --rev REVNUM

doesn't work, I still get the same error from conda trying to use the 
requests 2.12 in the root environment.

I do still have the older requests, 2.11, in some other (non-root) 
environments. I first tried running

conda install requests=2.11 -n root

from one of these environments and it did not work, still picking up the 
2.12 in root to do the work and getting the error. However, I was able 
to use PYTHONPATH to point to requests from a different environment, namely

PYTHONPATH=$CONDA_PREFIX/lib/python2.7/site-packages conda install 
requests=2.11 -n root

and it appears I've successfully got the requests 2.11 in my root 
environment. Anyways, I feel like I got lucky here. My conda 
installation is going to acquire lots of new environments as time goes 
by, building them all up from scratch is going to be a lot of work, so I 
was just going to get a disk backup if this didn't work.

Does this command

|bash Miniconda2-latest-Linux-x86_64.sh -bfp PATH_TO_CONDA_ROO just 
overwrite/replace the conda packages in the root environment? Leaving 
all the other environments working? Hopefully I would be able to update 
conda and conda-build after doing that. |

best,

David

**Comment by kalefranz** [comment]
@ilanschnell I think the answer is yes, conda completely breaks with requests >= 2.12 if conda-build is installed.

**Comment by kalefranz** [comment]
@davidslac Yes, the `bash ... -bfp` command will just overwrite conda and its dependencies in your root directory, if that's where the `-p` part points.

**Comment by ilanschnell** [comment]
Ok, so I'll add a "hotfix" which sets `requests <2.12` (for `conda <4.3`).

**Comment by kalefranz** [comment]
Thanks Ilan!

**Comment by ilanschnell** [comment]
@kalefranz I made the hotfix, so all should be fine now.

**Comment by mingwandroid** [comment]
This hotfix appears not to be working. From https://repo.continuum.io/pkgs/free/win-64/repodata.json

```
    "conda-4.2.13-py35_0.tar.bz2": {
      "build": "py35_0",
      "build_number": 0,
      "date": "2016-11-22",
      "depends": [
        "conda-env >=2.6",
        "menuinst",
        "pycosat >=0.6.1",
        "python 3.5*",
        "requests >=2.5.3",
        "ruamel_yaml >=0.11.14"
      ],
      "license": "BSD",
      "md5": "94de363ae6eb95f477966238838fedde",
      "name": "conda",
      "size": 459875,
      "version": "4.2.13"
    },
```

**Comment by mingwandroid** [comment]
@ilanschnell, @kalefranz can you please take care of this, it is still the case.
