### ISSUE TITLE
issues with updating anaconda and installing new packages

### ISSUE THREAD

**Issue by dkl7777** [conda/conda#3929]
Hi I am getting this report when trying to install seaborn on anaconda with python 3.5. Any ideas/help would be greatly appreciated. Many thanks

Edit I am getting the below error also when doing:
+ conda update requests 
+ conda update conda

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.19.0
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : /home/moritz/Python/anaconda3  (writable)
    default environment : /home/moritz/Python/anaconda3
       envs directories : /home/moritz/Python/anaconda3/envs
          package cache : /home/moritz/Python/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/moritz/Python/anaconda3/bin/conda install -c anaconda seaborn=0.7.1`

    Traceback (most recent call last):
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/moritz/Python/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/home/moritz/Python/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/moritz/Python/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

In the very beginning I am also getting this:

conda install -c anaconda seaborn=0.7.1
Fetching package metadata .../home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py:337: SubjectAltNameWarning: Certificate for conda.anaconda.org has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
  SubjectAltNameWarning
..An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

I recently updated anaconda.

**Comment by apsey** [comment]
I am seeing the same

```
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /opt/anaconda  (writable)
    default environment : /opt/anaconda
       envs directories : /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /opt/anaconda/bin/conda install -y pandas==0.18.1 ipywidgets==4.0.2 bcrypt==2.0.0 scikit-learn=0.17.1`

```

**Comment by kalefranz** [comment]
Can you try downgrading requests?  `conda install requests=2.11`

We just fixed another issue that popped up with the requests upgrade.  A little frustrating.

Here also I guess the output of `conda config --show-sources` would be useful.

And @apsey, you missed the whole stack trace in your bug report.  I can't do much without the stack trace 😜

**Comment by dkl7777** [comment]
conda install requests=2.11
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.19.0
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : /home/moritz/Python/anaconda3  (writable)
    default environment : /home/moritz/Python/anaconda3
       envs directories : /home/moritz/Python/anaconda3/envs
          package cache : /home/moritz/Python/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /home/moritz/Python/anaconda3/bin/conda install requests=2.11`




    Traceback (most recent call last):
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/moritz/Python/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/moritz/Python/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/moritz/Python/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/home/moritz/Python/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by dkl7777** [comment]
conda config --show-sources
shows nothing?

**Comment by kalefranz** [comment]
> `conda config --show-sources`  shows nothing?

Ok.  Just means you have all of the default settings.

What version of pyopenssl does `conda list` show?  Can you try

    conda update pyopenssl

and if that doesn't work maybe

    CONDA_SSL_VERIFY=false conda update pyopenssl

**Comment by dkl7777** [comment]
many thanks again. the latter seems to work (but not the former):

CONDA_SSL_VERIFY=false conda update pyopenssl
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /home/moritz/Python/anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.5.2                 |           py35_0         327 KB
    conda-4.2.13               |           py35_0         402 KB
    cryptography-1.5.3         |           py35_0         800 KB
    pyopenssl-16.2.0           |           py35_0          70 KB
    ------------------------------------------------------------
                                           Total:         1.6 MB

The following packages will be UPDATED:

    cffi:         1.2.1-py35_0  --> 1.5.2-py35_0 
    conda:        4.2.12-py35_0 --> 4.2.13-py35_0
    cryptography: 1.0.2-py35_0  --> 1.5.3-py35_0 
    pyopenssl:    0.15.1-py35_1 --> 16.2.0-py35_0

I suppose I proceed with the update, right?

**Comment by kalefranz** [comment]
ahhhh, the issue is an old `cryptography` version.

Yes, proceed.  And then you shouldn't run into the problem again.

**Comment by dkl7777** [comment]
hi, many thanks i was able to install seaborn

**Comment by apsey** [comment]
@kalefranz 

Hi, I got a new error using `CONDA_SSL_VERIFY=false conda update pyopenssl`

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 2.7.12.final.0
       requests version : 2.12.1
       root environment : /opt/anaconda  (writable)
    default environment : /opt/anaconda
       envs directories : /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False



`$ /opt/anaconda/bin/conda install --quiet --yes r-base=3.2* r-irkernel=0.5* r-ggplot2=1.0* rpy2 r-gridextra r-survival r-glmnet r-randomforest r-plyr r-rcurl=1.95*`




    Traceback (most recent call last):
      File "/opt/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/opt/anaconda/pkgs/r-base-3.2.2-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

Also,

`RUN conda config --show-sources` gives me nothing

**Comment by kalefranz** [comment]
That's an anaconda.org read timeout. Should be spurious. But glad to have the report. 

If conda config --show-sources is empty output for you, then I have a bug somewhere. You've definitely added the `r` channel to your configuration somewhere. That's the channel that's triggering your timeout on anaconda.org.

**Comment by apsey** [comment]
It is running on a dockerfile build. The `conda config --show-sources` ran before the add-channel command.

Also, after a while, I could build, so my issue is gone too. Thanks!

**Comment by blatacz** [comment]
Hi!
I have the same problem on Windows. I try to install photutils or update conda and it does not work.
What can I do?
(sorry for pictures, but I am not acquinted with windows and I do not know how to copy it from terminal)
![current_install](https://cloud.githubusercontent.com/assets/15468695/20931903/fc4a76d0-bbd2-11e6-93ca-6ff68cd239eb.png)
![current_install_problem](https://cloud.githubusercontent.com/assets/15468695/20931907/00cc2be0-bbd3-11e6-8443-5fa6b44ce22d.png)

**Comment by tpsanjan** [comment]
Hi, 

I am getting a similar error "Fetching package metadata ... An unexpected error has occurred" for most of the commands that I tried such as 
>>conda update conda
>>conda update scikit-learn (This is what I was trying to do)

Following the suggestions given in the above posts, I tried these:
1)  downgrading the requests using
>>conda install requests=2.11
Throws the same error "Fetching package metadata ... An unexpected error has occurred"

2) Verify the output of conda config --show-sources
Shows nothing => I have all of the default settings (Green signal !)

3) What version of pyopenssl does conda list show? 
Unfortunately, I don't have it installed (Should I be checking in the root env instead?)

>>conda install pyopenssl
Throws the same error "Fetching package metadata ... An unexpected error has occurred"

>>conda update pyopenssl
Throws the same error "Fetching package metadata ... An unexpected error has occurred"

>>CONDA_SSL_VERIFY=false conda update pyopenssl
Error: 'CONDA_SSL_VERIFY' is not recognized as an internal or external command,
operable program or batch file.

Also, I don't have any 'r' channel which might be triggering the timeout. So, I would like to know how to troubleshoot this error.

I have been using conda for almost 6 months and had never encountered this error before. I am running it on Windows 7 (64-bit) OS.

Here's the output for conda update scikit-learn command:

(my-ml-env) C:\Users\hp\Box Sync\research\codes>conda update scikit-learn
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Current conda install:
               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : C:\Program Files (x86)\Anaconda  (writable)
    default environment : C:\Program Files (x86)\Anaconda\envs\my-ml-env
       envs directories : C:\Program Files (x86)\Anaconda\envs
          package cache : C:\Program Files (x86)\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Program Files (x86)\Anaconda\Scripts\conda-script.py update scikit-learn`

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Program Files (x86)\Anaconda\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Program Files (x86)\Anaconda\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Program Files (x86)\Anaconda\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\packages\
urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\packages\
urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\packages\
urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\packages\
urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\packages\
urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Program Files (x86)\Anaconda\lib\site-packages\requests\packages\
urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_clas
s'

**Comment by iranmatlab** [comment]
Hello Friends
I have solved the problem.

This error cause because of different version of python in anaconda and installed python on your system.

when you upgrade anaconda to new version, It has been written in newest version on pyhton (3.6 for me) but i have installed lower version (3.5 for me) of python in my system, so it cause fail in run.

so download newest version of python and install it, then 
**rename** folder of last python to a different name such as "pythoonn"

then conda command will works.
