### ISSUE TITLE
Error during installation of scientific software

### ISSUE THREAD

**Issue by chrisgunitn** [conda/conda#3932]
Hello,

I am trying to install a scientific simulation software, [gprMax](http://www.gprmax.com/index.shtml), following the steps provided in the [user guide](http://docs.gprmax.com/en/latest/include_readme.html#installation). I first need to install Python, and I completed the first four steps described in the previous link.

However, when I am trying to execute 
`$ conda env create -f conda_env.yml`

I get this error message from the prompt :

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/christopher/miniconda3  (writable)
    default environment : /home/christopher/miniconda3
       envs directories : /home/christopher/miniconda3/envs
          package cache : /home/christopher/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /home/christopher/miniconda3/bin/conda-env create -f conda_env.yml`




    Traceback (most recent call last):
      File "/home/christopher/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/christopher/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 81, in execute
        directory=os.getcwd())
      File "/home/christopher/miniconda3/lib/python3.5/site-packages/conda_env/specs/__init__.py", line 23, in detect
        raise SpecNotFound(build_message(specs))
    conda_env.exceptions.SpecNotFound: Runtime error: Can't process without a name
    Conda Env Exception: conda_env.yml file not found
    There is no requirements.txt

```

I would be very grateful for any help.

**Comment by chrisgunitn** [comment]
It seems that I simply had to run the command within the directeory of the programme...
