### ISSUE TITLE
An unexpected error has occurred.[solved] 国内用户最好使用清华镜像来安装包

### ISSUE THREAD

**Issue by tjucdb** [conda/conda#3945]
An unexpected error has occurred. What should I do?

> Fetching packages ...
> accelerate_cud 100% |###############################| Time: 0:02:19  25.45 kB/s
> An unexpected error has occurred.                   | Time: 0:13:17  26.45 kB/s
> Please consider posting the following information to the
> conda GitHub issue tracker at:
> 
>     https://github.com/conda/conda/issues
> 
> 
> 
> Current conda install:
> 
>                platform : win-64
>           conda version : 4.2.13
>        conda is private : False
>       conda-env version : 4.2.13
>     conda-build version : 2.0.2
>          python version : 3.5.2.final.0
>        requests version : 2.11.1
>        root environment : C:\Users\chend\Anaconda3  (writable)
>     default environment : C:\Users\chend\Anaconda3
>        envs directories : C:\Users\chend\Anaconda3\envs
>           package cache : C:\Users\chend\Anaconda3\pkgs
>            channel URLs : https://repo.continuum.io/pkgs/free/win-64
>                           https://repo.continuum.io/pkgs/free/noarch
>                           https://repo.continuum.io/pkgs/pro/win-64
>                           https://repo.continuum.io/pkgs/pro/noarch
>                           https://repo.continuum.io/pkgs/msys2/win-64
>                           https://repo.continuum.io/pkgs/msys2/noarch
>             config file : None
>            offline mode : False
> 
> 
> 
> `$ C:\Users\chend\Anaconda3\Scripts\conda-script.py install accelerate`
> 
> 
> 
> 
>     Traceback (most recent call last):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
>         yield
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
>         data = self._fp.read(amt)
>       File "C:\Users\chend\Anaconda3\lib\http\client.py", line 448, in read
>         n = self.readinto(b)
>       File "C:\Users\chend\Anaconda3\lib\http\client.py", line 488, in readinto
>         n = self.fp.readinto(b)
>       File "C:\Users\chend\Anaconda3\lib\socket.py", line 575, in readinto
>         return self._sock.recv_into(b)
>       File "C:\Users\chend\Anaconda3\lib\ssl.py", line 929, in recv_into
>         return self.read(nbytes, buffer)
>       File "C:\Users\chend\Anaconda3\lib\ssl.py", line 791, in read
>         return self._sslobj.read(len, buffer)
>       File "C:\Users\chend\Anaconda3\lib\ssl.py", line 575, in read
>         v = self._sslobj.read(len, buffer)
>     ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
>         for chunk in self.raw.stream(chunk_size, decode_content=True):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
>         data = self.read(amt=amt, decode_content=decode_content)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
>         flush_decoder = True
>       File "C:\Users\chend\Anaconda3\lib\contextlib.py", line 77, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 250, in _error_catcher
>         raise ProtocolError('Connection broken: %r' % e, e)
>     requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\fetch.py", line 421, in download
>         for chunk in resp.iter_content(2**14):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\requests\models.py", line 679, in generate
>         raise ChunkedEncodingError(e)
>     requests.exceptions.ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
>         execute_actions(actions, index, verbose=not context.quiet)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
>         inst.execute_instructions(plan, index, verbose)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
>         cmd(state, arg)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
>         fetch_pkg(state['index'][arg + '.tar.bz2'])
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
>         download(url, path, session=session, md5=info['md5'], urlstxt=True)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\fetch.py", line 440, in download
>         raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
>     conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Users\\chend\\Anaconda3\\pkgs\\cudatoolkit-7.5-0.tar.bz2.part' for writing (("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))).
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
>         exit_code = args.func(args, p)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
>         install(args, parser, 'install')
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
>         raise CondaSystemExit('Exiting', e)
>       File "C:\Users\chend\Anaconda3\lib\contextlib.py", line 77, in __exit__
>         self.gen.throw(type, value, traceback)
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
>         yield
>       File "C:\Users\chend\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
>         raise CondaRuntimeError('RuntimeError: %s' % e)
>     conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Users\\chend\\Anaconda3\\pkgs\\cudatoolkit-7.5-0.tar.bz2.part' for writing (("Connection broken: ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None)", ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))).

**Comment by tjucdb** [comment]
I have solved this problem. 
国内用户请用清华大学镜像吧~

> conda config --add channels  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
> conda config --set show_channel_urls yes
