### ISSUE TITLE
jupyterlab install error 

### ISSUE THREAD

**Issue by youngtackpark** [conda/conda#3948]
Hi

I am trying to install jupyterlab on my mac using "conda install –c conda-forge jupyterlab" and 
got an unexpected error as follows. I would be appreciated if you can help me out to resolve
the problem.

error message ----
(Canopy 32bit) Youngtacks-iMac:~ admin$ conda install –c conda-forge jupyterlab
Fetching package metadata: ....
Solving package specifications: .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 370, in install
    "\n\n    %s" % (', '.join(close)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 51: ordinal not in range(128)
(Canopy 32bit) Youngtacks-iMac:~ admin$

**Comment by kalefranz** [comment]
`conda update conda`
