### ISSUE TITLE
conda update canonical_name AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by elrichindy** [conda/conda#3950]
While trying to run conda update either --all or any specific package I get the following error which conda tells me to put up here. Could be some dumb issue i'm not aware of but not sure why it is happening now and not on my previous installation (Is a fresh windows 10 installation):

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 413, in get_info
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 225, in execute
    channels = list(prioritize_channels(channels).keys())
  File "C:\Anaconda2\lib\site-packages\conda\models\channel.py", line 384, in prioritize_channels
    result[url] = channel.canonical_name, q
  File "C:\Anaconda2\lib\site-packages\conda\models\channel.py", line 253, in canonical_name
    if tokenized_startswith(self.name.split('/'), that_name.split('/')):
AttributeError: 'NoneType' object has no attribute 'split'

a couple of packages i need to update so would love to know where the issue is.

**Comment by kalefranz** [comment]
Check your condarc file for a bad configuration information under the `channels` key.  Generally I think we're providing better errors messages now.  If you're still having problems with recent versions of conda, feel free to file a new issue with a new stack trace.
