### ISSUE TITLE
Timed out many times... 

### ISSUE THREAD

**Issue by anguillanneuf** [conda/conda#3957]
Solving package specifications: ..........
Pruning fetched packages from the cache ...
Fetching packages ...
ca-certificate 100% |###############################| Time: 0:00:00 368.57 kB/s
An unexpected error has occurred.                   | Time: 0:00:01 788.23 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /root/miniconda3  (writable)
    default environment : /root/miniconda3
       envs directories : /root/miniconda3/envs
          package cache : /root/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /root/miniconda3/bin/conda-env create -f=environment.yml --name carnd_term_1`

    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
        yield
      File "/root/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
        data = self._fp.read(amt)
      File "/root/miniconda3/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/root/miniconda3/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/root/miniconda3/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/root/miniconda3/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/root/miniconda3/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/root/miniconda3/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.5/site-packages/requests/models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/root/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/root/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
        flush_decoder = True
      File "/root/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/root/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "/root/miniconda3/lib/python3.5/site-packages/requests/models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 33, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/root/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/root/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/root/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/root/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/root/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/root/miniconda3/pkgs/gettext-0.19.7-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/root/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/root/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/root/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 40, in install
        raise CondaSystemExit('Exiting', e)
      File "/root/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/root/miniconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/root/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 38, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/root/miniconda3/pkgs/gettext-0.19.7-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
