### ISSUE TITLE
python=2.7 gensim package broken

### ISSUE THREAD

**Issue by bgreen-litl** [conda/conda#3970]
With a clean python=2.7 conda env, gensim fails to import with ` ValueError: numpy.dtype has the wrong size, try recompiling`

Repro:

    $ conda --version
    conda 4.2.13

    $ conda create -n tmp python=2.7 gensim

    [...]

    $ . activate tmp
    (tmp) $ python -c "import gensim"
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/bob/anaconda/envs/tmp/lib/python2.7/site-packages/gensim/__init__.py", line 6, in <module>
        from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization
      File "/Users/bob/anaconda/envs/tmp/lib/python2.7/site-packages/gensim/models/__init__.py", line 13, in <module>
        from .word2vec import Word2Vec
      File "/Users/bob/anaconda/envs/tmp/lib/python2.7/site-packages/gensim/models/word2vec.py", line 100, in <module>
        from gensim.models.word2vec_inner import train_batch_sg, train_batch_cbow
      File "__init__.pxd", line 155, in init gensim.models.word2vec_inner (./gensim/models/word2vec_inner.c:10186)
    ValueError: numpy.dtype has the wrong size, try recompiling

**Comment by kalefranz** [comment]
This is a packaging issue, not an issue with how conda installed the package.  File a ticket with either conda-forge or at https://github.com/ContinuumIO/anaconda-issues
