### ISSUE TITLE
theano package is broken

### ISSUE THREAD

**Issue by stmax82** [conda/conda#3972]
When I use pip to install theano 0.8.2 it works. When I use conda to install it, I get the following error when I "import theano":

```
(pyenv) C:\temp>python -c "import theano"
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/.../AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.5-64/tmp8rwa15vv/m91973e5c136ea49268a916ff971b7377.lib and object C:/Users/.../AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.5-64/tmp8rwa15vv/m91973e5c136ea49268a916ff971b7377.exp

Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN None)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\temp\pyenv\lib\site-packages\theano\__init__.py", line 111, in <module>
    theano.sandbox.cuda.tests.test_driver.test_nvidia_driver1()
  File "C:\temp\pyenv\lib\site-packages\theano\sandbox\cuda\tests\test_driver.py", line 31, in test_nvidia_driver1
    profile=False)
  File "C:\temp\pyenv\lib\site-packages\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\temp\pyenv\lib\site-packages\theano\compile\pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "C:\temp\pyenv\lib\site-packages\theano\compile\function_module.py", line 1777, in orig_function
    defaults)
  File "C:\temp\pyenv\lib\site-packages\theano\compile\function_module.py", line 1641, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "C:\temp\pyenv\lib\site-packages\theano\gof\link.py", line 690, in make_thunk
    storage_map=storage_map)[:3]
  File "C:\temp\pyenv\lib\site-packages\theano\gof\vm.py", line 1047, in make_all
    self.updated_vars,
  File "C:\temp\pyenv\lib\site-packages\theano\gof\vm.py", line 913, in make_vm
    vm = CVM(
NameError: name 'CVM' is not defined

(pyenv) C:\temp>
```

I created the conda environment like that:

```
conda create -p pyenv python=3.4
conda install -p pyenv theano=0.8.2
```

When I install theano with pip it works:

```
conda create -p pyenv python=3.4
conda install -p pyenv numpy scipy six
conda install -p pyenv mingw libpython

activate pyenv
pip install theano==0.8.2
```

```
(pyenv) C:\temp>python -c "import theano"
DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/.../AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.5-64/cuda_ndarray/cuda_ndarray.lib and object C:/Users/.../AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.5-64/cuda_ndarray/cuda_ndarray.exp

DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/.../AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.5-64/tmp3h9_zaor/m91973e5c136ea49268a916ff971b7377.lib and object C:/Users/.../AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-3.4.5-64/tmp3h9_zaor/m91973e5c136ea49268a916ff971b7377.exp

Using gpu device 0: GeForce GTX 980 Ti (CNMeM is disabled, cuDNN 5103)
C:\temp\pyenv\lib\site-packages\theano\sandbox\cuda\__init__.py:600: UserWarning: Your cuDNN version is more recent than the one Theano officially supports. If you see any problems, try updating Theano or downgrading cuDNN to version 5.
  warnings.warn(warn)

(pyenv) C:\temp>
```

My conda info:

```
(pyenv) C:\temp>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.1.final.0
       requests version : 2.12.1
       root environment : C:\Miniconda3  (writable)
    default environment : C:\Miniconda3\envs\pyenv
       envs directories : C:\Miniconda3\envs
          package cache : C:\Miniconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\...\.condarc
           offline mode : False
```

**Comment by mingwandroid** [comment]
Please try the suggestions on https://groups.google.com/forum/#!msg/theano-users/JoTu61_MTLk/G2ojrrXhEwAJ and let me know if that works.

**Comment by mingwandroid** [comment]
Also, `conda list --show-channel-urls` if you wouldn't mind.

**Comment by stmax82** [comment]
@mingwandroid deleting the "C:\Users\<user>\AppData\Local\Theano" directory solved the problem!

Looks like deleting this directory is required after switching from a pip-theano installation to a conda-theano installation.

Thanks

**Comment by mingwandroid** [comment]
I would advise against mixing things personally.

**Comment by stmax82** [comment]
@mingwandroid yes, I don't intend to switch between pip-theano and conda-theano more than once :) My old conda envs all use pip-theano because there simply was no conda-theano package for Windows until a short while ago. I'm quite happy to finally be able to "conda install theano" on Windows. Nice and simple as it should be. Now just add a keras package please :)
