### ISSUE TITLE
Failed pandas update - WindowsError: [Error 5] Access is denied

### ISSUE THREAD

**Issue by MZ80K** [conda/conda#3976]
As suggested I'm posting this here. Tried to update pandas and got the following. The error is Windows reporting Access Denied but nothing significant was open, and it recurred after a reboot. I don't know enough to tinker so will have to stay on old packages for now.

C:\Users\blah>conda update pandas

The following NEW packages will be INSTALLED:
    mkl:          11.3.3-1

The following packages will be UPDATED:
    conda:        4.2.11-py27_0                            --> 4.2.13-py27_0
    numexpr:      2.4.3-np19py27_0   None://None/<unknown> --> 2.6.1-np111py27_1
    numpy:        1.10.1-py27_0                            --> 1.11.2-py27_0
    pandas:       0.17.0-np110py27_0                       --> 0.19.1-np111py27_0
    scikit-learn: 0.16.1-np19py27_0  None://None/<unknown> --> 0.18.1-np111py27_0
    scipy:        0.15.1-np19py27_0  None://None/<unknown> --> 0.18.1-np111py27_0

Proceed ([y]/n)? y

Extracting packages ...
An unexpected error has occurred.                                        |   0%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.14.1
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\blah\anaconda  (writable)
    default environment : C:\blah\anaconda
       envs directories : C:\blah\anaconda\envs
          package cache : C:\blah\anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\blah\anaconda\Scripts\conda-script.py update pandas`

    Traceback (most recent call last):
      File "C:\blah\anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\blah\anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\blah\anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\blah\anaconda\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\blah\anaconda\lib\site-packages\conda\plan.py", line 643,in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\blah\anaconda\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\blah\anaconda\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\blah\anaconda\lib\site-packages\conda\install.py", line 807, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "C:\blah\anaconda\lib\site-packages\conda\common\disk.py", line 155, in exp_backoff_fn
        result = fn(*args, **kwargs)
    WindowsError: [Error 5] Access is denied

**Comment by MZ80K** [comment]
Solved thanks to https://github.com/conda/conda/issues/2893. Install packages individually and it gets there in the end.
