### ISSUE TITLE
 error=OSError(17, 'File exists')

### ISSUE THREAD

**Issue by ryanriopelle** [conda/conda#3978]
I am getting this message shown below after trying to upgrade all to the newest version of conda.

`CondaOSError: OS error: failed to link (src=u'/Users/rriopelle-LT/anaconda/pkgs/funcsigs-1.0.2-py27_0/lib/python2.7/site-packages/funcsigs/init.py', dst='/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/funcsigs/init.py', type=1, error=OSError(17, 'File exists'))`

It seams to be related to this thread [https://github.com/conda/conda/issues/3494](url)

Now im getting this message from Conda suggesting I post the output to Github.

`macbook-pro-6:site-packages rriopelle-LT$ conda - conda env remove
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

https://github.com/conda/conda/issues
Traceback (most recent call last):
File "/Users/rriopelle-LT/anaconda/bin/conda", line 6, in 
sys.exit(conda.cli.main())
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
return conda_exception_handler(_main)
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
print_unexpected_error_message(e)
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
info_stdout, info_stderr = get_info()
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 402, in get_info
from conda.cli import conda_argparse
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in 
from .common import add_parser_help
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 16, in 
from ..resolve import MatchSpec
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 14, in 
from .logic import minimal_unsatisfiable_subset, Clauses
File "/Users/rriopelle-LT/anaconda/lib/python2.7/site-packages/conda/logic.py", line 31, in 
import pycosat
ImportError: No module named  @pycosat`

**Comment by mas-dse-rriopell** [comment]
Also, Conda Remove doesn't work so can I just completely remove folder  `/Users/rriopelle-LT/anaconda`, and links within Bashrc? and reinstall after?

**Comment by jakirkham** [comment]
Maybe related to issue ( https://github.com/conda/conda/issues/3865 ).

**Comment by kalefranz** [comment]
This is an instance of conda "uninstalling" itself, which was fixed with transactions in conda 4.3.
