### ISSUE TITLE
proxy error: "Unable to determine SOCKS version"

### ISSUE THREAD

**Issue by emlec** [conda/conda#3984]
Hello, 

I have recently installed miniconda3 behind a proxy server. But the update failed giving me this message that I understand as a proxy error. Could you help me to solve this problem?

`Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/analyse/src/miniconda3  (writable)
    default environment : /home/analyse/src/miniconda3
       envs directories : /home/analyse/src/miniconda3/envs
          package cache : /home/analyse/src/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/analyse/src/miniconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 184, in proxy_manager_for
        **proxy_kwargs
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/socks.py", line 154, in __init__
        "Unable to determine SOCKS version from %s" % proxy_url
    ValueError: Unable to determine SOCKS version from socks://cache.ha.univ-nantes.fr:3128/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/analyse/src/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/analyse/src/miniconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/home/analyse/src/miniconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 140, in fetch_repodata
        raise CondaRuntimeError("Invalid index file: {0}: {1}".format(join_url(url, filename), e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Unable to determine SOCKS version from socks://cache.ha.univ-nantes.fr:3128/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/adapters.py", line 184, in proxy_manager_for
        **proxy_kwargs
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/socks.py", line 154, in __init__
        "Unable to determine SOCKS version from %s" % proxy_url
    ValueError: Unable to determine SOCKS version from socks://cache.ha.univ-nantes.fr:3128/
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 316, in fetch_index
        for url in urls]
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 316, in <listcomp>
        for url in urls]
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "/home/analyse/src/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 140, in fetch_repodata
        raise CondaRuntimeError("Invalid index file: {0}: {1}".format(join_url(url, filename), e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Unable to determine SOCKS version from socks://cache.ha.univ-nantes.fr:3128/
`

**Comment by emlec** [comment]
I installed the version  4.0.5 and then updated it to 4.2.13. No problem occurred.
So in brief, it's now OK for me installing the version 4.0.5 and with proxy problem with the version 4.2.12.

**Comment by xy0806** [comment]
With Ubuntu 14.04 LTS, I installed the latest Anaconda 2 with version 4.2.0. I encountered the same proxy problem.
Thanks emlec, after I went back to install the version 4.0.0, then everything goes well.

**Comment by kalefranz** [comment]
For SOCKS proxy problems, you usually need to install and/or update `pysocks`.  I'm not sure if we have a pysocks package in the default repos yet.  If not, look on anaconda.org.
