### ISSUE TITLE
Error in Pkg.build("IJulia") when  installing Jupyter via the Conda package.

### ISSUE THREAD

**Issue by picestcode** [conda/conda#4005]
julia> Pkg.build("IJulia")
INFO: Building Conda
INFO: Building Nettle
INFO: Building ZMQ
INFO: Building IJulia
INFO:  Installing Jupyter via the Conda package.
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/igor/.julia/v0.5/Conda/deps/usr  (writable)
    default environment : /home/igor/.julia/v0.5/Conda/deps/usr
       envs directories : /home/igor/.julia/v0.5/Conda/deps/usr/envs
          package cache : /home/igor/.julia/v0.5/Conda/deps/usr/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/igor/.julia/v0.5/Conda/deps/usr/condarc-julia.yml
           offline mode : False

`$ /home/igor/.julia/v0.5/Conda/deps/usr/bin/conda install -y jupyter`

    Traceback (most recent call last):
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/fetch.py", line 282, in fetch_index
        for url in urls]
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/home/igor/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/fetch.py", line 137, in fetch_repodata
        .format(url, filename, e))
    CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.

**Comment by kalefranz** [comment]
You'll need to install `pysocks`, since you have environment variables or netrc configuration on your system that requests is recognizing.
