### ISSUE TITLE
Module bz2 not found

### ISSUE THREAD

**Issue by tmkoot** [conda/conda#4017]
Traceback (most recent call last):
  File "c:\anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Anaconda2\Scripts\conda.exe\__main__.py", line 9, in <module>
  File "c:\anaconda2\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "c:\anaconda2\lib\site-packages\conda\exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "c:\anaconda2\lib\site-packages\conda\exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "c:\anaconda2\lib\site-packages\conda\exceptions.py", line 406, in get_info
    args.func(args, p)
  File "c:\anaconda2\lib\site-packages\conda\cli\main_info.py", line 155, in execute
    from conda.api import get_index
  File "c:\anaconda2\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "c:\anaconda2\lib\site-packages\conda\fetch.py", line 8, in <module>
    import bz2
ImportError: No module named bz2

**Comment by wasoomro** [comment]
Try to reinstall anaconda.
