### ISSUE TITLE
CondaOSError: OS Error: failed to link & Unable to execute any conda commands

### ISSUE THREAD

**Issue by uduwage** [conda/conda#4020]
after executing $conda update --all I get the following error: 

```
Extracting packages ...
[      COMPLETE      ]|######################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|######################################################################################################| 100%
Linking packages ...
[funetype            ]|##################                                                                                    |  17%

CondaOSError: OS error: failed to link (src=u'/Users/a/anaconda2/pkgs/futures-3.0.5-py27_0/lib/python2.7/site-packages/concurrent/__init__.py', dst='/Users/a/anaconda2/lib/python2.7/site-packages/concurrent/__init__.py', type=1, error=OSError(17, 'File exists'))
```

I saw there are similar issues but they were referring to different destination files. On another thread a user has posted a solution which is deleting the destination file. I don't want to really do that blindly. Is this issue have been fix or is it still waiting for a solution. 

After the update I am unable to execute any ```conda``` commands due to fallowing error: 

```
$conda list
Traceback (most recent call last):
  File "/Users/a/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 426, in print_unexpected_error_message
    from conda.base.context import context
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.disk import try_write, conda_bld_ensure_dir
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/common/disk.py", line 16, in <module>
    from ..utils import on_win
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/utils.py", line 11, in <module>
    from .common.url import path_to_url
  File "/Users/a/anaconda2/lib/python2.7/site-packages/conda/common/url.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import LocationParseError
ImportError: No module named requests.packages.urllib3.exceptions

```

**as result of that I am unable to pip install any packages. Tried to uninstall conda since command conda is not available nothing can be done.**

**Comment by kalefranz** [comment]
Issues such as these should all be resolved with conda 4.3 available now.
