### ISSUE TITLE
conda update anaconda fails after successful conda update conda

### ISSUE THREAD

**Issue by dbc60** [conda/conda#4022]
Hi folks,
Does anyone have a suggestion to make `update` work again? I haven't used anaconda in a while, so I ran `conda update conda` and it ran successfully. I followed it up with `conda update anaconda`, but that failed. Now things like `conda list` run okay, but `conda update conda` and `conda update anaconda` both fail with traceback errors.

Here's the successful run of `conda update conda`, followed by the failed run of `conda update anaconda` :

```
C:\> conda update conda
Fetching package metadata: ....
Solving package specifications: ....................
Package plan for installation in environment C:\Users\Doug\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    vs2015_runtime-14.0.25123  |                0         1.9 MB
    python-3.5.2               |                0        30.3 MB
    pycosat-0.6.1              |           py35_1          80 KB
    pywin32-220                |           py35_1        10.4 MB
    requests-2.12.3            |           py35_0         791 KB
    ruamel_yaml-0.11.14        |           py35_0         217 KB
    setuptools-27.2.0          |           py35_1         761 KB
    wheel-0.29.0               |           py35_0         123 KB
    menuinst-1.4.2             |           py35_1         108 KB
    pip-9.0.1                  |           py35_1         1.7 MB
    conda-4.2.13               |           py35_0         449 KB
    ------------------------------------------------------------
                                           Total:        46.8 MB

The following NEW packages will be INSTALLED:

    ruamel_yaml:    0.11.14-py35_0
    vs2015_runtime: 14.0.25123-0

The following packages will be UPDATED:

    conda:          3.19.0-py35_0 --> 4.2.13-py35_0
    conda-env:      2.4.5-py35_0  --> 2.6.0-0
    menuinst:       1.3.1-py35_0  --> 1.4.2-py35_1
    pip:            7.1.2-py35_0  --> 9.0.1-py35_1
    pycosat:        0.6.1-py35_0  --> 0.6.1-py35_1
    python:         3.5.1-0       --> 3.5.2-0
    pywin32:        219-py35_2    --> 220-py35_1
    requests:       2.9.0-py35_0  --> 2.12.3-py35_0
    setuptools:     19.1.1-py35_0 --> 27.2.0-py35_1
    wheel:          0.26.0-py35_1 --> 0.29.0-py35_0

Proceed ([y]/n)?

menuinst-1.4.2 100% |###############################| Time: 0:00:00   2.13 MB/s
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00   0.00  B/s
vs2015_runtime 100% |###############################| Time: 0:00:00   8.72 MB/s
python-3.5.2-0 100% |###############################| Time: 0:00:04   7.29 MB/s
pycosat-0.6.1- 100% |###############################| Time: 0:00:00   1.74 MB/s
pywin32-220-py 100% |###############################| Time: 0:00:01   7.52 MB/s
requests-2.12. 100% |###############################| Time: 0:00:00   5.34 MB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:00   2.43 MB/s
setuptools-27. 100% |###############################| Time: 0:00:00   2.46 MB/s
wheel-0.29.0-p 100% |###############################| Time: 0:00:00   1.73 MB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:00   8.04 MB/s
conda-4.2.13-p 100% |###############################| Time: 0:00:00   3.50 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
```

Here's the run of `conda update anaconda`:

```
C:\> conda update anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.2
         python version : 3.5.2.final.0
       requests version : 2.12.3
       root environment : C:\Users\Doug\Anaconda3  (writable)
    default environment : C:\Users\Doug\Anaconda3
       envs directories : C:\Users\Doug\Anaconda3\envs
          package cache : C:\Users\Doug\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Users\Doug\Anaconda3\Scripts\conda-script.py update anaconda`




    Traceback (most recent call last):
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Doug\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\Doug\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\Doug\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\Doug\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```

**Comment by dbc60** [comment]
After some more searching, this issue is probably related to [issue 1253](https://github.com/ContinuumIO/anaconda-issues/issues/1253).

**Comment by mingwandroid** [comment]
More likely it is related to https://github.com/kennethreitz/requests/issues/3710

Updating `anaconda` isn't really something I recommend since it *upgrades* you to the latest version of the `Anaconda Distribution`, which is version 4.2.0 and is, at this point, quite old and many packages have had bug fixes since then.

IMHO, what you've run into is an incompatibility between the new conda you updated to and the version of requests in Anaconda 4.2.0, such that conda pulled the requests rug out from under its own feet, @kalefranz or @ilanschnell may know more.

**Comment by dbc60** [comment]
Thanks @mingwandroid for the info. It was a leap of faith that the upgrade would work between two so distant versions. I've decided it's easier to re-install from scratch, rather than fight a broken conda.

**Comment by awwerbro** [comment]
For future reference: I ran into the same issue, solved it by first manually uninstalling cryptography with `pip uninstall cryptography` (had to run this twice for some reason)  and then reinstalling it again with 'pip install cryptography'.

**Comment by mingwandroid** [comment]
I am not sure why lots of people use `conda update anaconda` so long after the latest release of Anaconda Distribution.

4.2.0 was released at the end of September and updating the Anaconda metapackage like that tries to reset your versions to the exact ones in that release.

A lot of bugs in packages have been fixed and/or new versions have been released since then.

I personally prefer `conda update --all` to get me the latest and greatest.

There are valid reasons to want 4.2.0. For example if you happen to know that your analyses or code worked as you expected on that version but not on the current latest versions but I do not expect that to be the case for most people.
