### ISSUE TITLE
failure to clone environment

### ISSUE THREAD

**Issue by cinderbdt** [conda/conda#4027]
(C:\Anaconda2) C:\Users\user>conda info --envs
# conda environments:
#
root                  *  C:\Anaconda2

(C:\Anaconda2) C:\Users\user>conda create -n elastic --clone root
Source:      C:\Anaconda2
Destination: C:\Anaconda2\envs\elastic
The following packages cannot be cloned out of the root environment:
 - conda-4.2.13-py27_0
 - None:///<unknown>::conda-build-1.18.1-py27_0
Fetching package metadata .........
Packages: 175
Files: 226
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
        1 file(s) copied.#################################               |  71%
An unexpected error has occurred.###############################         |  83%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.18.1
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2
       envs directories : C:\Anaconda2\envs
          package cache : C:\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Anaconda2\Scripts\conda-script.py create -n elastic --clone root`

    Traceback (most recent call last):
      File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _mai
n
        exit_code = args.func(args, p)
      File "C:\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, i
n execute
        install(args, parser, 'create')
      File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 228, in i
nstall
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_
args=index_args)
      File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 90, in cl
one
        index_args=index_args)
      File "C:\Anaconda2\lib\site-packages\conda\misc.py", line 388, in clone_en
v
        force_extract=False, index_args=index_args)
      File "C:\Anaconda2\lib\site-packages\conda\misc.py", line 188, in explicit

        execute_actions(actions, index=index, verbose=verbose)
      File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 643, in execute_
actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 135, in
execute_instructions
        cmd(state, arg)
      File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 78, in L
INK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 986, in link
        _link(src, dst, lt)
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 171, in _link

        shutil.copy2(src, dst)
      File "C:\Anaconda2\lib\shutil.py", line 130, in copy2
        copyfile(src, dst)
      File "C:\Anaconda2\lib\shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: u'C:\\Anaconda2\\pkgs\\bokeh-0
.11.1-py27_0\\Scripts/bokeh-script.py-server'

(C:\Anaconda2) C:\Users\user>

**Comment by kalefranz** [comment]
Are you still having this issue with recent versions of conda?  Latest is conda 4.3.17.

**Comment by cinderbdt** [comment]
After upgrading my conda the environment creation still failed, but it gave me a different error that I was able to trace directly to the bokeh package.  I uninstalled bokeh  0.11.1-py27_0 then installed 0.12.5-py27_0. After that, I was able to create the new environment.

Thanks for the follow up.
