### ISSUE TITLE
Sunpy installation errors on fresh Anaconda install, OS/X and web proxy server 

### ISSUE THREAD

**Issue by rpseguin** [conda/conda#4029]
Running into difficulty installing Sunpy on a fresh install of Anaconda.  I installed Anaconda for my user only.
I thought the error was most likely because our proxy server might not be allowing access to the list of domains/hosts, but I clicked on each of the first 7 URLs listed and they came up in my web browser ok.  Is conda ignoring or adopting the system proxy settings?

Mac OS/X 10.11.6 on a 15" Retina MacBook Pro  i7, mid-2014, 16GB RAM, IRIS Pro GPU, 512GB SSD
 
svlmg197g3qn:~ rpseguin$ echo $PATH
/Users/rpseguin/anaconda/bin:/Users/rpseguin/bin:/Users/rpseguin/sw/mercurial:/Users/rpseguin/sw/cmake/bin:/Users/rpseguin/sw/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/rpseguin/sw/yasm/bin
svlmg197g3qn:~ rpseguin$ conda config --add channels conda-forge
svlmg197g3qn:~ rpseguin$ conda install sunpy
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/osx-64/
Could not connect to https://repo.continuum.io/pkgs/pro/osx-64/
Could not connect to https://conda.anaconda.org/conda-forge/osx-64/
Could not connect to https://conda.anaconda.org/conda-forge/noarch/
Could not connect to https://conda.anaconda.org/conda-forge/osx-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/rpseguin/anaconda  (writable)
    default environment : /Users/rpseguin/anaconda
       envs directories : /Users/rpseguin/anaconda/envs
          package cache : /Users/rpseguin/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/rpseguin/.condarc
           offline mode : False

`$ /Users/rpseguin/anaconda/bin/conda install sunpy`

    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
        raise err
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
        sock.connect(sa)
    OSError: [Errno 65] No route to host
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
        conn = self._new_conn()
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c09b70>: Failed to establish a new connection: [Errno 65] No route to host
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c09b70>: Failed to establish a new connection: [Errno 65] No route to host',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c09b70>: Failed to establish a new connection: [Errno 65] No route to host',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/rpseguin/anaconda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Users/rpseguin/anaconda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/Users/rpseguin/anaconda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c09b70>: Failed to establish a new connection: [Errno 65] No route to host',)): https://conda.anaconda.org/conda-forge/osx-64/
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
        raise err
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
        sock.connect(sa)
    OSError: [Errno 65] No route to host
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 254, in connect
        conn = self._new_conn()
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c1cac8>: Failed to establish a new connection: [Errno 65] No route to host
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c1cac8>: Failed to establish a new connection: [Errno 65] No route to host',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c1cac8>: Failed to establish a new connection: [Errno 65] No route to host',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 293, in <listcomp>
        for url in urls]
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/rpseguin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/osx-64/repodata.json (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x109c1cac8>: Failed to establish a new connection: [Errno 65] No route to host',)): https://conda.anaconda.org/conda-forge/osx-64/

**Comment by kalefranz** [comment]
No route to host means you have a networking issue that conda cannot itself resolve.
