### ISSUE TITLE
Failed to Conda Update Matplotlib (Windows)

### ISSUE THREAD

**Issue by abangfarhan** [conda/conda#4032]
Get this error when trying to update matplotlib:

(D:\Users\USER\Anaconda3) C:\Users\USER>conda update matplotlib
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment D:\Users\USER\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    icu-57.1                   |           vc14_0        34.2 MB
    libpng-1.6.22              |           vc14_0         547 KB
    sip-4.18                   |           py35_0         241 KB
    qt-5.6.0                   |           vc14_0        51.2 MB
    pyqt-5.6.0                 |           py35_0         4.4 MB
    matplotlib-1.5.3           |      np111py35_1         6.2 MB
    ------------------------------------------------------------
                                           Total:        96.8 MB

The following NEW packages will be INSTALLED:

    icu:        57.1-vc14_0       [vc14]

The following packages will be UPDATED:

    libpng:     1.6.17-vc14_1     [vc14] --> 1.6.22-vc14_0     [vc14]
    matplotlib: 1.5.1-np110py35_0 --> 1.5.3-np111py35_1
    pyqt:       4.11.4-py35_5     --> 5.6.0-py35_0
    qt:         4.8.7-vc14_8      [vc14] --> 5.6.0-vc14_0      [vc14]
    sip:        4.16.9-py35_2     --> 4.18-py35_0

Proceed ([y]/n)? y

Fetching packages ...
icu-57.1-vc14_ 100% |###############################| Time: 0:01:10 511.03 kB/s
libpng-1.6.22- 100% |###############################| Time: 0:00:02 259.61 kB/s
sip-4.18-py35_ 100% |###############################| Time: 0:00:01 245.55 kB/s
qt-5.6.0-vc14_ 100% |###############################| Time: 0:01:44 512.51 kB/s
pyqt-5.6.0-py3 100% |###############################| Time: 0:00:08 523.44 kB/s
matplotlib-1.5 100% |###############################| Time: 0:00:12 526.08 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
An unexpected error has occurred.###############                         |  50%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.20.0
         python version : 3.5.1.final.0
       requests version : 2.11.1
       root environment : D:\Users\USER\Anaconda3  (writable)
    default environment : D:\Users\USER\Anaconda3
       envs directories : D:\Users\USER\Anaconda3\envs
          package cache : D:\Users\USER\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ D:\Users\USER\Anaconda3\Scripts\conda-script.py update matplotlib`

    Traceback (most recent call last):
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "D:\Users\USER\Anaconda3\lib\site-packages\conda\install.py", line 977, in link
        os.makedirs(dst_dir)
      File "D:\Users\USER\Anaconda3\lib\os.py", line 231, in makedirs
        makedirs(head, mode, exist_ok)
      File "D:\Users\USER\Anaconda3\lib\os.py", line 231, in makedirs
        makedirs(head, mode, exist_ok)
      File "D:\Users\USER\Anaconda3\lib\os.py", line 241, in makedirs
        mkdir(name, mode)
    FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Users\\USER\\Anaconda3\\Library/include/qt/QtCore/5.6.0'

**Comment by abangfarhan** [comment]
The problem turned out to be with the installation of `qt`. I solved the problem by removing the `qt` folder from `.../Anaconda3/Library/include/` and install the `qt` afterwards.
