### ISSUE TITLE
conda update conda fails with OSError

### ISSUE THREAD

**Issue by waterbug** [conda/conda#4034]
Here is the output:

$ conda update conda
Fetching package metadata ..................An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.11
         python version : 2.7.12.final.0
       requests version : 2.12.3
       root environment : /home/waterbug/anaconda2  (writable)
    default environment : /home/waterbug/anaconda2
       envs directories : /home/waterbug/anaconda2/envs
          package cache : /home/waterbug/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/dlr-sc/linux-64
                          https://conda.anaconda.org/dlr-sc/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/clinicalgraphics/linux-64
                          https://conda.anaconda.org/clinicalgraphics/noarch
                          file:///home/waterbug/sandbox/conda/repo/linux-64
                          file:///home/waterbug/sandbox/conda/repo/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/waterbug/.condarc
           offline mode : False

`$ /home/waterbug/anaconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
        r.content
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/requests/models.py", line 781, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/home/waterbug/anaconda2/lib/python2.7/site-packages/requests/models.py", line 714, in generate
        chunk = self.raw.read(chunk_size)
    AttributeError: 'exceptions.OSError' object has no attribute 'read'

**Comment by kalefranz** [comment]
The fix to #4034 in the 4.2.x series was released Jan 7 in 4.2.14. It was PR #4059
