### ISSUE TITLE
Failure to install matplotlib for julia

### ISSUE THREAD

**Issue by Stivanification** [conda/conda#4041]
I'm trying to install matplotlib to use the PyPlot julia package. I set `ENV["PYTHON"] = ""` in julia to activate the automatic installation of matplotlib for use in julia, but the installation does not terminate due to an 'unexpected error'. The message I'm getting is

```
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /home/stefan/.julia/v0.5/Conda/deps/usr  (writable)
    default environment : /home/stefan/.julia/v0.5/Conda/deps/usr
       envs directories : /home/stefan/.julia/v0.5/Conda/deps/usr/envs
          package cache : /home/stefan/.julia/v0.5/Conda/deps/usr/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/stefan/.julia/v0.5/Conda/deps/usr/condarc-julia.yml
           offline mode : False



`$ /home/stefan/.julia/v0.5/Conda/deps/usr/bin/conda install -y matplotlib`




    Traceback (most recent call last):
      File "/home/stefan/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/stefan/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/stefan/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/stefan/.julia/v0.5/Conda/deps/usr/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/stefan/.julia/v0.5/Conda/deps/usr/pkgs/qt-5.6.2-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

ERROR: InitError: failed process: Process(setenv(`/home/stefan/.julia/v0.5/Conda/deps/usr/bin/conda install -y matplotlib`,String["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin","USERNAME=root","DISPLAY=:0","SUDO_GID=1000","SHELL=/bin/bash","XAUTHORITY=/home/stefan/.Xauthority","LANGUAGE=en_US","CONDARC=/home/stefan/.julia/v0.5/Conda/deps/usr/condarc-julia.yml","MAIL=/var/mail/root","LANG=en_US.UTF-8","LOGNAME=root","SUDO_USER=stefan","CONDA_PREFIX=/home/stefan/.julia/v0.5/Conda/deps/usr","SUDO_UID=1000","SUDO_COMMAND=/usr/bin/julia","CONDA_DEFAULT_ENV=/home/stefan/.julia/v0.5/Conda/deps/usr","USER=root","TERM=xterm-256color","HOME=/home/stefan","LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:","OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
 in pipeline_error(::Base.Process) at ./process.jl:616
 in run(::Cmd) at ./process.jl:592
 in pyimport_conda(::String, ::String, ::String) at /home/stefan/.julia/v0.5/PyCall/src/PyCall.jl:479
 in __init__() at /home/stefan/.julia/v0.5/PyPlot/src/PyPlot.jl:223
 in _include_from_serialized(::String) at ./loading.jl:150
 in _require_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:187
 in _require_search_from_serialized(::Int64, ::Symbol, ::String, ::Bool) at ./loading.jl:217
 in require(::Symbol) at ./loading.jl:371
during initialization of module PyPlot
```

**Comment by mopshell** [comment]
I got exactly same problem here.

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
