### ISSUE TITLE
Could not connect to https://repo.continuum.io/pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2 An unexpected error has occurred.

### ISSUE THREAD

**Issue by shamanickCoder** [conda/conda#4049]
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Bean\Anaconda3  (writable)
    default environment : C:\Users\Bean\Anaconda3
       envs directories : C:\Users\Bean\Anaconda3\envs
          package cache : C:\Users\Bean\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\Bean\Anaconda3\Scripts\conda-script.py create --name k27 python python=2.7`

    Traceback (most recent call last):
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "C:\Users\Bean\Anaconda3\lib\ssl.py", line 377, in wrap_socket
        _context=self)
      File "C:\Users\Bean\Anaconda3\lib\ssl.py", line 752, in __init__
        self.do_handshake()
      File "C:\Users\Bean\Anaconda3\lib\ssl.py", line 988, in do_handshake
        self._sslobj.do_handshake()
      File "C:\Users\Bean\Anaconda3\lib\ssl.py", line 633, in do_handshake
        self._sslobj.do_handshake()
    socket.timeout: _ssl.c:629: The handshake operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 355, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 315, in _raise_timeout
        raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\fetch.py", line 377, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\requests\adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\fetch.py", line 403, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Users\Bean\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Users\Bean\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
