### ISSUE TITLE
Unable to install modules using conda on Mingw64, JSONDecodeError

### ISSUE THREAD

**Issue by monocongo** [conda/conda#4069]
I have a PC that I'm trying to install modules using conda. I get the following error whenever I try to install or update modules:

```
$ conda install netCDF4
Fetching package metadata: ....
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 146, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 62, in e
xecute
    install.install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 240, in insta
ll
    prefix=prefix)
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 595, in get_in
dex_trap
    return get_index(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\api.py", line 45, in get_index
    for dist, info in iteritems(install.linked_data(prefix)):
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 517, in linked_da
ta
    res[fn[:-5]] = json.load(open(join(meta_dir,fn)))
  File "C:\Anaconda3\lib\json\__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)


$ conda info
Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : 1.20.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```

**Comment by kalefranz** [comment]
Please `conda update conda`.  If you're still having similar problems, please file a new issue with an updated stack trace.
