### ISSUE TITLE
"An unexpected error has occurred" when updating package

### ISSUE THREAD

**Issue by aliceell** [conda/conda#4081]
I am trying to update Spyder and the following message appeared. Also, I can no longer launch Spyder; the spinning blue circle appears, as though something is trying to happen, but nothing does (no splash screen appears and no python.exe processes launch).

I can post this in the spyder respository instead if you want, but since the error message told me to post it in this repository, I thought it would be better to post it here.

Thanks in advance.

------------------------------------------------------
```
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 3.4.5.final.0
       requests version : 2.12.4
       root environment : C:\Users\aliceell\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\aliceell\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False


`$ C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py update spyder`

Traceback (most recent call last):
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception
_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 402, in result
        return self.__get_result()
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 354, in __get_result
        raise self._exception
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\thread.py", line 54, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line
 594, in urlopen
        chunked=chunked)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line
 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line
 835, in _validate_conn
        conn.connect()
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 330
, in connect
        cert = self.sock.getpeercert()
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", l
ine 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\aliceell\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", l
ine 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

```

**Comment by HanksZhanghan** [comment]
when I  am trying to update anaconda,"An unexpected error has occurred" happended.
I am from PR.China.

**Comment by aliceell** [comment]
I found a solution here: #3938 

It looks like this is a conda issue (as I suspected), not a Spyder issue. Something to do with multiple dependencies.

The CONDA_SSL_VERIFY command did not work for me. I had to use the following commands, as suggested in #3938:issuecomment-263755414

```
conda config --set ssl_verify false
conda update pyopenssl
conda config --remove ssl_verify
```

Hope this helps someone else.
