### ISSUE TITLE
On Windows, conda 4.0.5-py35_0 cannot be updated to 4.3.0-py35_1

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#4097]
On a fresh install of the latest Miniconda on Windows, the following fails:

`conda update -c conda-canary --all`

Giving:

```
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment C:\Users\ray\m2-x64-3.5:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    vs2015_runtime-14.0.25123  |                0         1.9 MB
    python-3.5.2               |                0        30.3 MB
    pycosat-0.6.1              |           py35_1          80 KB
    pycrypto-2.6.1             |           py35_4         481 KB
    pywin32-220                |           py35_1        10.4 MB
    pyyaml-3.12                |           py35_0         118 KB
    requests-2.12.4            |           py35_0         791 KB
    ruamel_yaml-0.11.14        |           py35_0         217 KB
    setuptools-27.2.0          |           py35_1         761 KB
    menuinst-1.4.2             |           py35_1         108 KB
    pip-9.0.1                  |           py35_1         1.7 MB
    conda-4.3.0                |           py35_1         510 KB
    ------------------------------------------------------------
                                           Total:        47.3 MB

The following NEW packages will be INSTALLED:

    pywin32:        220-py35_1
    ruamel_yaml:    0.11.14-py35_0

The following packages will be UPDATED:

    conda:          4.0.5-py35_0    --> 4.3.0-py35_1
    conda-env:      2.4.5-py35_0    --> 2.6.0-0
    menuinst:       1.3.2-py35_0    --> 1.4.2-py35_1
    pip:            8.1.1-py35_1    --> 9.0.1-py35_1
    pycosat:        0.6.1-py35_0    --> 0.6.1-py35_1
    pycrypto:       2.6.1-py35_3    --> 2.6.1-py35_4
    python:         3.5.1-4         --> 3.5.2-0
    pyyaml:         3.11-py35_3     --> 3.12-py35_0
    requests:       2.9.1-py35_0    --> 2.12.4-py35_0
    setuptools:     20.3-py35_0     --> 27.2.0-py35_1
    vs2015_runtime: 14.00.23026.0-0 --> 14.0.25123-0

Proceed ([y]/n)? y

menuinst-1.4.2 100% |###############################| Time: 0:00:00   2.35 MB/s
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00   0.00  B/s
vs2015_runtime 100% |###############################| Time: 0:00:00   9.24 MB/s
python-3.5.2-0 100% |###############################| Time: 0:00:02  11.57 MB/s
pycosat-0.6.1- 100% |###############################| Time: 0:00:00   2.61 MB/s
pycrypto-2.6.1 100% |###############################| Time: 0:00:00   4.51 MB/s
pywin32-220-py 100% |###############################| Time: 0:00:00  10.85 MB/s
pyyaml-3.12-py 100% |###############################| Time: 0:00:00   2.57 MB/s
requests-2.12. 100% |###############################| Time: 0:00:00   5.76 MB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:00   2.84 MB/s
setuptools-27. 100% |###############################| Time: 0:00:00   4.53 MB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:00   5.70 MB/s
conda-4.3.0-py 100% |###############################| Time: 0:00:00 530.91 kB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%
Traceback (most recent call last):
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\exceptions.py", line 516, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\cli\main.py", line 84, in _main
    from ..base.context import context
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\context.py", line 12, in <module>
    from .constants import (APP_NAME, DEFAULT_CHANNELS, DEFAULT_CHANNEL_ALIAS, ROOT_ENV_NAME,
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\constants.py", line 15
    PREFIX_PLACEHOLDER = 'C:\Users\ray\m2-x64-3.5'
                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ray\m2-x64-3.5\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\exceptions.py", line 532, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\exceptions.py", line 463, in print_unexpected_error_message
    from conda.base.context import context
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\context.py", line 12, in <module>
    from .constants import (APP_NAME, DEFAULT_CHANNELS, DEFAULT_CHANNEL_ALIAS, ROOT_ENV_NAME,
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\constants.py", line 15
    PREFIX_PLACEHOLDER = 'C:\Users\ray\m2-x64-3.5'
                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
Traceback (most recent call last):
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\exceptions.py", line 516, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\cli\main.py", line 84, in _main
    from ..base.context import context
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\context.py", line 12, in <module>
    from .constants import (APP_NAME, DEFAULT_CHANNELS, DEFAULT_CHANNEL_ALIAS, ROOT_ENV_NAME,
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\constants.py", line 15
    PREFIX_PLACEHOLDER = 'C:\Users\ray\m2-x64-3.5'
                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ray\m2-x64-3.5\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\exceptions.py", line 532, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\exceptions.py", line 463, in print_unexpected_error_message
    from conda.base.context import context
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\context.py", line 12, in <module>
    from .constants import (APP_NAME, DEFAULT_CHANNELS, DEFAULT_CHANNEL_ALIAS, ROOT_ENV_NAME,
  File "C:\Users\ray\m2-x64-3.5\lib\site-packages\conda\base\constants.py", line 15
    PREFIX_PLACEHOLDER = 'C:\Users\ray\m2-x64-3.5'
                        ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

**Comment by kalefranz** [comment]
@mingwandroid does an update to 4.2.13 from 4.0.5 work ok?

**Comment by mingwandroid** [comment]
Yes.

**Comment by kalefranz** [comment]
Cool.  Then hopefully #4100 fixes it.  That seems like the obvious culprit.  I'm not sure exactly how, but ¯\\\_(ツ)\_/¯

**Comment by kalefranz** [comment]
Oh nevermind I get it now.  I thought we didn't need the split anymore.  But yeah, we still do.

**Comment by mingwandroid** [comment]
OK thanks. If you merge it I will give it a quick go. I've been trying to use 4.3 this weekend on Windows and it have had a few more problems, but (apart from this one) nothing I'm certain enough to file issues about. I suspect failure to empty trash causes package install failure though. I think it would be good to get the QA team to test the canary release.

**Comment by kalefranz** [comment]
ok merged

**Comment by kalefranz** [comment]
> I suspect failure to empty trash causes package install failure though

That's for sure not good if that's happening.

**Comment by kalefranz** [comment]
Path's on windows just suck.  I just addressed one problem where I had to let case-insensitive paths slip through my checks for windows.  That's merged now.

This https://github.com/conda/conda/issues/3779 I guess is also a bug in a later version of 4.2.x, which means it's probably in 4.3.x too.  Going to try to put in some tests for it soon.

**Comment by mingwandroid** [comment]
I don't know what the URL specification is for a Windows file on a different server but I would be surprised if `\` was allowed since it isn't for local `file://` URLs. Then again, UNC always uses `\` so maybe it is that way. I think finding some official documentation to clarify this point would be good.

An somewhat related issue I ran into in my own stuff recently was using `file:///C:/some/dir` on Windows when I should have been using `file://C:/some/dir`.

I would like to suggest we all use Windows as our primary development machines but I'm not sure that'll fly :-)

**Comment by kalefranz** [comment]
> I would like to suggest we all use Windows as our primary development machines but I'm not sure that'll fly :-)

I've been wanting to do that for a while.  I even got one of Peter's old windows laptops.  Used it for 3 hours, and I had to bail.  Not because of windows, but because of the pixel density on the laptop.  After just few hours I had a severe headache from eye strain that made me stop working.

Get me a non-mac laptop with >200 ppi and I'll develop on Windows.
