### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by abiB1994** [conda/conda#4098]
Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\Abi'RoyMcCoy'\Anaconda2  (writable)
    default environment : C:\Users\Abi'RoyMcCoy'\Anaconda2
       envs directories : C:\Users\Abi'RoyMcCoy'\Anaconda2\envs
          package cache : C:\Users\Abi'RoyMcCoy'\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\Abi'RoyMcCoy'\Anaconda2\Scripts\conda-script.py create -n virtualenvproject python=2.7 anaconda`

    Traceback (most recent call last):
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handle
r
        return_value = func(*args, **kwargs)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\install.py", line 812, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "C:\Users\Abi'RoyMcCoy'\Anaconda2\lib\site-packages\conda\common\disk.py", line 165, in exp_backoff_fn
        result = fn(*args, **kwargs)
    WindowsError: [Error 5] Access is denied

**Comment by mingwandroid** [comment]
Using ' in your user name is likely to cause all sorts of problems. Is it possible to install Anaconda elsewhere?
