### ISSUE TITLE
Permission Denied While Importing Matplotlib.pyplot

### ISSUE THREAD

**Issue by adilemre** [conda/conda#4099]
While I try to import "Matplotlib.pyplot", I receive a message like "PermissionError: [Errno 13] Permission denied: '/Library/Fonts/Oswald-Bold.otf' " and I can't use matplotlib.

**My conda information:**
               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/adilemrebilgic/anaconda  (writable)
    default environment : /Users/adilemrebilgic/anaconda
       envs directories : /Users/adilemrebilgic/anaconda/envs
          package cache : /Users/adilemrebilgic/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

**Full error script is below:**

from matplotlib import pyplot as plt
/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):

  File "<ipython-input-5-1d1446f6fa64>", line 1, in <module>
    from matplotlib import pyplot as plt

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/pyplot.py", line 29, in <module>
    import matplotlib.colorbar

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/colorbar.py", line 34, in <module>
    import matplotlib.collections as collections

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/collections.py", line 27, in <module>
    import matplotlib.backend_bases as backend_bases

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/backend_bases.py", line 62, in <module>
    import matplotlib.textpath as textpath

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/textpath.py", line 15, in <module>
    import matplotlib.font_manager as font_manager

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1421, in <module>
    _rebuild()

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1406, in _rebuild
    fontManager = FontManager()

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/font_manager.py", line 1059, in __init__
    self.ttflist = createFontList(self.ttffiles)

  File "/Users/adilemrebilgic/anaconda/lib/python3.5/site-packages/matplotlib/font_manager.py", line 581, in createFontList
    font = ft2font.FT2Font(fpath)

PermissionError: [Errno 13] Permission denied: '/Library/Fonts/Oswald-Bold.otf'

**Comment by kalefranz** [comment]
This is no something changing the conda code itself can fix, and therefore you unfortunately have the wrong issue tracker.
