### ISSUE TITLE
conda stopped working after installing python 3.6 from https://anaconda.org/jjhelmus/python

### ISSUE THREAD

**Issue by HZine** [conda/conda#4144]
C:\WINDOWS\system32>conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\main.py", line 107, in _main
    p, sub_parsers = generate_parser()
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: Module use of python35.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3-4.2.0\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\exceptions.py", line 402, in get_info
    from conda.cli import conda_argparse
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Anaconda3-4.2.0\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: Module use of python35.dll conflicts with this version of Python.

C:\WINDOWS\system32>

**Comment by kalefranz** [comment]
Please use the "Anaconda Prompt" icon instead of cmd.exe, or make sure you activate your root environment when you start cmd.exe.
