### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by LmYjQ** [conda/conda#4149]
I want to install tensorflow and use it in jupyter notebook.
But the following error occured:

**error 1 open jupyter notebook**
jupyter notebook
[W 07:33:01.303 NotebookApp] Unrecognized JSON config file version, assuming version 1
Traceback (most recent call last):
  File "/Users/maerkesu/anaconda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 595, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 74, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 1069, in initialize
    self.init_configurables()
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/notebook/notebookapp.py", line 837, in init_configurables
    parent=self,
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/Users/maerkesu/anaconda/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['conda', 'info', '--json']' returned non-zero exit status 1

**error 2 update conda**
bogon:~ maerkesu$ conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/Users/maerkesu/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 225, in execute
    channels = list(prioritize_channels(channels).keys())
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 385, in prioritize_channels
    channel = Channel(chn)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 166, in __call__
    c = Channel.from_value(value)
  File "/Users/maerkesu/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 212, in from_value
    value = value.decode(UTF8)
  File "/Users/maerkesu/anaconda/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\uff0f' in position 31: ordinal not in range(128)
bogon:~ maerkesu$ 

the character u'\uff0f' may come from the source I have added by conda config --add channels
http://pypi.mirrors.ustc.edu.cn'\uff0f'
wrong character at last
I tried conda config --remove ,but it didn't work, because of the unicodeencodeerror

If is why these two error occurs, is there any other ways to remove the wrong link?

**Comment by LmYjQ** [comment]
bogon:~ maerkesu$ conda config --get channels
--add channels 'defaults'   # lowest priority
--add channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/'
--add channels u'http://pypi.mirrors.ustc.edu.cn\uff0f'
--add channels 'http://pypi.mirrors.ustc.edu.cn/'   # highest priority
bogon:~ maerkesu$ conda config --remove channels u'http://pypi.mirrors.ustc.edu.cn\uff0f'


CondaKeyError: Error with key 'channels': 'uhttp://pypi.mirrors.ustc.edu.cn\\uff0f' is not in the 'channels' key of the config file

**Comment by LmYjQ** [comment]
These problems could be solved by removing all the channels by
`conda config --remove-key channels `
and re-add the channels
