### ISSUE TITLE
conda env export failure

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#4152]
Under conda 4.3.1, `conda env export` returns the backtrace:

```Python
    Traceback (most recent call last):
      File "/home/alan/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 515, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/alan/anaconda/lib/python3.5/site-packages/conda_env/cli/main_export.py", line 94, in execute
        ignore_channels=args.ignore_channels)
      File "/home/alan/anaconda/lib/python3.5/site-packages/conda_env/env.py", line 62, in from_environment
        for dist in installed:
    AttributeError: 'str' object has no attribute 'channel'
```

My current conda information:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.1
       conda is private : False
      conda-env version : 4.3.1
    conda-build version : 2.0.12
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /home/alan/anaconda  (writable)
    default environment : /home/alan/anaconda/envs/labs
       envs directories : /home/alan/anaconda/envs
          package cache : /home/alan/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-canary/linux-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/alan/.condarc
           offline mode : False
             user-agent : conda/4.3.1 requests/2.12.4 CPython/3.5.2 Linux/4.4.0-57-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000
```

**Comment by kalefranz** [comment]
resolved with #4175
