### ISSUE TITLE
Conda Installation Error : Runtime Exception

### ISSUE THREAD

**Issue by manavsah** [conda/conda#4156]
An unexpected error has occurred.###                                                                                                                         | Time: 0:05:18  45.04 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /opt/python  (writable)
    default environment : /opt/python
       envs directories : /opt/python/envs
          package cache : /opt/python/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /opt/python/bin/conda install -y bokeh dask decorator gensim h5py hdf5 ipython joblib jupyter matplotlib nltk numpy pandas pillow psutil scipy scikit-learn scikit-image toolz terminado`

    Traceback (most recent call last):
      File "/opt/python/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
        yield
      File "/opt/python/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 380, in read
        data = self._fp.read(amt)
      File "/opt/python/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/opt/python/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/opt/python/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/opt/python/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/opt/python/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/opt/python/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/python/lib/python3.5/site-packages/requests/models.py", line 703, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/opt/python/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 432, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/opt/python/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 397, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/opt/python/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/python/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 303, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/python/lib/python3.5/site-packages/conda/fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "/opt/python/lib/python3.5/site-packages/requests/models.py", line 710, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/python/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/python/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/opt/python/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/opt/python/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/opt/python/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/opt/python/lib/python3.5/site-packages/conda/fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/opt/python/pkgs/mkl-11.3.3-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/opt/python/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/python/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/python/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/python/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/opt/python/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/opt/python/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/opt/python/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/opt/python/pkgs/mkl-11.3.3-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
