### ISSUE TITLE
Internal Server Error for url: https://repo.continuum.io/pkgs/free/linux-64/...

### ISSUE THREAD

**Issue by mgcdanny** [conda/conda#4159]
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Current conda install:
               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /app/.conda  (writable)
    default environment : /app/.conda
       envs directories : /app/.conda/envs
          package cache : /app/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
`$ /app/.conda/bin/conda-env update -n root -f /tmp/build_0b1cd43124ef883983d410c06c92f724/pl31-heroku-jupyter-05bb9c4/environment.yml`
    Traceback (most recent call last):
      File "/app/.conda/lib/python3.5/site-packages/conda/fetch.py", line 395, in download
        resp.raise_for_status()
      File "/app/.conda/lib/python3.5/site-packages/requests/models.py", line 893, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/linux-64/path.py-9.0.1-py35_0.tar.bz2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/.conda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 33, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/app/.conda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/app/.conda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/app/.conda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/app/.conda/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/app/.conda/lib/python3.5/site-packages/conda/fetch.py", line 399, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/linux-64/path.py-9.0.1-py35_0.tar.bz2: https://repo.continuum.io/pkgs/free/linux-64/path.py-9.0.1-py35_0.tar.bz2
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/app/.conda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/app/.conda/lib/python3.5/site-packages/conda_env/cli/main_update.py", line 113, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "/app/.conda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 40, in install
        raise CondaSystemExit('Exiting', e)
      File "/app/.conda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/app/.conda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/app/.conda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 38, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 500 Server Error: Internal Server Error for url: https://repo.continuum.io/pkgs/free/linux-64/path.py-9.0.1-py35_0.tar.bz2: https://repo.continuum.io/pkgs/free/linux-64/path.py-9.0.1-py35_0.tar.bz2
    
mistune-0.7.3-  24% |#######                        | Time: 0:00:00  32.59 MB/s      | Time: 0:00:00  31.33 MB/s
nose-1.3.7-py3   0% |                              | ETA:  --:--:--   0.00  B/s       | Time: 0:00:00  28.80 MB/s
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by jchodera** [comment]
I'm seeing a lot of these failures as well.

**Comment by jkseppan** [comment]
Similar-seeming problem [here](https://ci.appveyor.com/project/mdboom/matplotlib/build/1.0.3976/job/hhbmd2etlsunjd5p):

```
Current conda install:
               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Miniconda35-x64  (writable)
    default environment : C:\Miniconda35-x64
       envs directories : C:\Miniconda35-x64\envs
          package cache : C:\Miniconda35-x64\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\appveyor\.condarc
           offline mode : False
`$ C:\Miniconda35-x64\scripts\conda-script.py create -q -n test-environment python=3.5 pip setuptools numpy python-dateutil freetype=2.6 msinttypes tk=8.5 pyparsing pytz tornado libpng>=1.6.21,<1.7 zlib=1.2 cycler>=0.10 nose mock sphinx`
    Traceback (most recent call last):
      File "C:\Miniconda35-x64\lib\site-packages\conda\fetch.py", line 395, in download
        resp.raise_for_status()
      File "C:\Miniconda35-x64\lib\site-packages\requests\models.py", line 893, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://binstar-cio-packages-prod.s3.amazonaws.com/57281ec17a81971064ee6283/582af0cfbf2f820efebf17b7?...
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35-x64\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Miniconda35-x64\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Miniconda35-x64\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\Miniconda35-x64\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Miniconda35-x64\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Miniconda35-x64\lib\site-packages\conda\fetch.py", line 399, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: <unprintable CondaRuntimeError object>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35-x64\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda35-x64\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Miniconda35-x64\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Miniconda35-x64\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "C:\Miniconda35-x64\lib\site-packages\conda\__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 201
```

**Comment by kalefranz** [comment]
Just a spurious HTTP error.
