### ISSUE TITLE
Conda runtime error

### ISSUE THREAD

**Issue by nanfly** [conda/conda#4161]
nanfly@nanfly-T440p:~/CarND-Term1-Starter-Kit$ conda env create -f environment.yml
Fetching package metadata ...........
Solving package specifications: ..........
Fetching packages ...
ca-certificate 100% |################################| Time: 0:00:00 186.21 kB/s
gettext-0.19.7 100% |################################| Time: 0:00:07 805.12 kB/s
icu-56.1-4.tar 100% |################################| Time: 0:00:48 470.90 kB/s
jpeg-9b-0.tar. 100% |################################| Time: 0:00:04 216.85 kB/s
libffi-3.2.1-2 100% |################################| Time: 0:00:03  13.77 kB/s
libgfortran-3. 100% |################################| Time: 0:00:00 288.53 kB/s
libiconv-1.14- 100% |################################| Time: 0:00:05 389.68 kB/s
libsodium-1.0. 100% |################################| Time: 0:00:03 419.22 kB/s
ncurses-5.9-10 100% |################################| Time: 0:00:09 121.20 kB/s
pcre-8.38-1.ta 100% |################################| Time: 0:00:01 351.37 kB/s
pixman-0.34.0- 100% |################################| Time: 0:00:16 233.07 kB/s
sqlite-3.13.0- 100% |################################| Time: 0:00:07 688.61 kB/s
tk-8.5.19-1.ta 100% |################################| Time: 0:00:20  99.84 kB/s
xz-5.2.2-0.tar 100% |################################| Time: 0:00:01 569.59 kB/s
zlib-1.2.8-3.t 100% |################################| Time: 0:00:00 268.04 kB/s
glib-2.51.0-2. 100% |################################| Time: 0:00:09 684.50 kB/s
An unexpected error has occurred.#####               | Time: 0:00:23  96.59 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /home/nanfly/miniconda3  (writable)
    default environment : /home/nanfly/miniconda3
       envs directories : /home/nanfly/miniconda3/envs
          package cache : /home/nanfly/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/nanfly/miniconda3/bin/conda-env create -f environment.yml`

    Traceback (most recent call last):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
        yield
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
        data = self._fp.read(amt)
      File "/home/nanfly/miniconda3/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/home/nanfly/miniconda3/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/home/nanfly/miniconda3/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/home/nanfly/miniconda3/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/home/nanfly/miniconda3/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/home/nanfly/miniconda3/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
        flush_decoder = True
      File "/home/nanfly/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 431, in download
        for chunk in resp.iter_content(2**14):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/requests/models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 33, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/fetch.py", line 450, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/home/nanfly/miniconda3/pkgs/hdf5-1.8.17-8.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 40, in install
        raise CondaSystemExit('Exiting', e)
      File "/home/nanfly/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/home/nanfly/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 38, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/home/nanfly/miniconda3/pkgs/hdf5-1.8.17-8.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

**Comment by shengye205** [comment]
I encounter the same error

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
