### ISSUE TITLE
Error while updating conda

### ISSUE THREAD

**Issue by NikhilShaw** [conda/conda#4162]
nikhil@nikhil-Compaq-15-Notebook-PC:~$ conda update conda
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/linux-64/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/linux-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/nikhil/anaconda2  (writable)
    default environment : /home/nikhil/anaconda2
       envs directories : /home/nikhil/anaconda2/envs
          package cache : /home/nikhil/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/nikhil/anaconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/home/nikhil/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2172ee2ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)): https://repo.continuum.io/pkgs/free/linux-64/

**Comment by raazesh-sainudiin** [comment]
I am having the same problem.
