### ISSUE TITLE
conda install iopro

### ISSUE THREAD

**Issue by xiaoledeng** [conda/conda#4173]
Fetching package metadata .....Could not connect to https://repo.continuum.io/pkgs/free/osx-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/osx-64/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
..Could not connect to https://repo.continuum.io/pkgs/free/osx-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/deng/anaconda  (writable)
    default environment : /Users/deng/anaconda
       envs directories : /Users/deng/anaconda/envs
          package cache : /Users/deng/anaconda/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/deng/.condarc
           offline mode : False

`$ /Users/deng/anaconda/bin/conda install iopro`

    Traceback (most recent call last):
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/deng/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10e478b10>: Failed to establish a new connection: [Errno 65] No route to host',)): https://repo.continuum.io/pkgs/free/osx-64/

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.
