### ISSUE TITLE
conda search error

### ISSUE THREAD

**Issue by bwanaaa** [conda/conda#4187]
tried to find intel thread building blocks package with this:
`$anaconda search -t conda tbb`

and got this

```
Using Anaconda API: https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
[ERROR]
Traceback (most recent call last):
  File "/Users/me/anaconda/bin/anaconda", line 6, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "/Users/me/anaconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 87, in main
    description=__doc__, version=version)
  File "/Users/me/anaconda/lib/python3.5/site-packages/binstar_client/scripts/cli.py", line 66, in binstar_main
    return args.main(args)
  File "/Users/me/anaconda/lib/python3.5/site-packages/binstar_client/commands/search.py", line 15, in search
    pprint_packages(packages, access=False)
  File "/Users/me/anaconda/lib/python3.5/site-packages/binstar_client/utils/pprint.py", line 70, in pprint_packages
    pprint_package(package, access, full_name, revision=revisions)
  File "/Users/me/anaconda/lib/python3.5/site-packages/binstar_client/utils/pprint.py", line 34, in pprint_package
    package['conda_platforms'] = ', '.join(package['conda_platforms'])
TypeError: sequence item 1: expected str instance, NoneType found
```
why error?

**Comment by bioruffo** [comment]
Can confirm, Windows 10 with `conda-4.2.13-py35_0` and `anaconda 4.2.0-np111py35_0`.

`>anaconda search -t conda pysam
Using Anaconda Cloud api site https://api.anaconda.org
Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms
     ------------------------- |   ------ | --------------- | ---------------
     ???/pysam                 |    0.7.7 | conda           | linux-64, osx-64
[ERROR]
Traceback (most recent call last):
  File "C:\Users\Roberto\Anaconda3\Scripts\anaconda-script.py", line 5, in <module>
    sys.exit(binstar_client.scripts.cli.main())
  File "C:\Users\Roberto\Anaconda3\lib\site-packages\binstar_client\scripts\cli.py", line 87, in main
    description=__doc__, version=version)
  File "C:\Users\Roberto\Anaconda3\lib\site-packages\binstar_client\scripts\cli.py", line 66, in binstar_main
    return args.main(args)
  File "C:\Users\Roberto\Anaconda3\lib\site-packages\binstar_client\commands\search.py", line 15, in search
    pprint_packages(packages, access=False)
  File "C:\Users\Roberto\Anaconda3\lib\site-packages\binstar_client\utils\pprint.py", line 70, in pprint_packages
    pprint_package(package, access, full_name, revision=revisions)
  File "C:\Users\Roberto\Anaconda3\lib\site-packages\binstar_client\utils\pprint.py", line 34, in pprint_package
    package['conda_platforms'] = ', '.join(package['conda_platforms'])
TypeError: sequence item 1: expected str instance, NoneType found`

**Comment by bioruffo** [comment]
...now also confirming this on Ubuntu 16.04 LTS.

**Comment by bioruffo** [comment]
This is the json for the `tbb` package (notice the `None` under `"conda_platforms"`):

     {'app_entry': {}, 'app_type': {}, 'revision': 1, 'app_summary': {}, 'versions': [], 'html_url': 'http://anaconda.org/BioBuilds/tbb', 'id': '5824e55dbf2f820efe71fabe', 'conda_platforms': ['linux-64', None, 'osx-64'], 'owner': 'BioBuilds', 'summary': '', 'package_types': ['conda'], 'full_name': 'BioBuilds/tbb', 'public': True, 'latest_version': '4.4_20160803', 'url': 'http://api.anaconda.org/packages/BioBuilds/tbb', 'name': 'tbb'}

And `binstar_client/utils/pprint.py` tries to join `None` within a string:  

      File "/home/roberto/anaconda3/lib/python3.5/site-packages/binstar_client/utils/pprint.py", line 34, in pprint_package
        package['conda_platforms'] = ', '.join(package['conda_platforms'])
    TypeError: sequence item 1: expected str instance, NoneType found

**Comment by bioruffo** [comment]
This is a conda issue:  
https://github.com/Anaconda-Platform/anaconda-client/issues/380
