### ISSUE TITLE
Cannot Update Conda

### ISSUE THREAD

**Issue by moeyensj** [conda/conda#4192]
I've tried a combination of different things including a command-line reinstall of anaconda. Same error still occurs:

```
conda update conda
Fetching package metadata .........Could not connect to http://eupsforge.net/conda/dev/noarch/
Could not connect to http://eupsforge.net/conda/dev/osx-64/
..Could not connect to http://eupsforge.net/conda/dev/osx-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/joachim/anaconda3  (writable)
    default environment : /Users/joachim/anaconda3
       envs directories : /Users/joachim/anaconda3/envs
          package cache : /Users/joachim/anaconda3/pkgs
           channel URLs : http://conda.lsst.codes/stack/osx-64/
                          http://conda.lsst.codes/stack/noarch/
                          http://eupsforge.net/conda/dev/osx-64/
                          http://eupsforge.net/conda/dev/noarch/
                          https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/joachim/.condarc
           offline mode : False



`$ /Users/joachim/anaconda3/bin/conda update conda`




    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
        raise err
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
        sock.connect(sa)
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 1106, in request
        self._send_request(method, url, body, headers)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 1151, in _send_request
        self.endheaders(body)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 1102, in endheaders
        self._send_output(message_body)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
        conn = self._new_conn()
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 147, in _new_conn
        (self.host, self.timeout))
    requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0x107a97518>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='eupsforge.net', port=80): Max retries exceeded with url: /conda/dev/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x107a97518>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 479, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='eupsforge.net', port=80): Max retries exceeded with url: /conda/dev/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x107a97518>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/joachim/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Users/joachim/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/Users/joachim/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPConnectionPool(host='eupsforge.net', port=80): Max retries exceeded with url: /conda/dev/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x107a97518>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)')): http://eupsforge.net/conda/dev/osx-64/
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
        raise err
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
        sock.connect(sa)
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 363, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 1106, in request
        self._send_request(method, url, body, headers)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 1151, in _send_request
        self.endheaders(body)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 1102, in endheaders
        self._send_output(message_body)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 934, in _send_output
        self.send(msg)
      File "/Users/joachim/anaconda3/lib/python3.5/http/client.py", line 877, in send
        self.connect()
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 167, in connect
        conn = self._new_conn()
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 147, in _new_conn
        (self.host, self.timeout))
    requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.HTTPConnection object at 0x1077b0470>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='eupsforge.net', port=80): Max retries exceeded with url: /conda/dev/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x1077b0470>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 479, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='eupsforge.net', port=80): Max retries exceeded with url: /conda/dev/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x1077b0470>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)'))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 293, in <listcomp>
        for url in urls]
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/joachim/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPConnectionPool(host='eupsforge.net', port=80): Max retries exceeded with url: /conda/dev/osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x1077b0470>, 'Connection to eupsforge.net timed out. (connect timeout=3.05)')): http://eupsforge.net/conda/dev/osx-64/
```

Thank you in advance! I'll try a few more things to see if I can get it working.

**Comment by moeyensj** [comment]
Fixed: I deleted my conda install again. And then reset my MacBook's NVRAM and then reinstalled. I am no longer having any update issues. Still unsure of the exact cause of the problem but it does work now.
