### ISSUE TITLE
Pyalgotrade install

### ISSUE THREAD

**Issue by mfk82** [conda/conda#4225]
Hello,
I got an unexpected error when trying to install Pyalgotrade.
I get the following error message : **AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'**
Do you have any idea why ?

Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 2.7.10.final.0
       requests version : 2.12.4
       root environment : C:\Users\mmartin\AppData\Local\Continuum\Anaconda  (writable)
    default environment : C:\Users\mmartin\AppData\Local\Continuum\Anaconda
       envs directories : C:\Users\mmartin\AppData\Local\Continuum\Anaconda\envs
          package cache : C:\Users\mmartin\AppData\Local\Continuum\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\mmartin\AppData\Local\Continuum\Anaconda\Scripts\conda-script.py search pyalgotrade`

    Traceback (most recent call last):
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_search.py", line 126, in execute
        execute_search(args, parser)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\cli\main_search.py", line 174, in execute_search
        unknown=args.unknown)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\fetch.py", line 295, in fetch_index
        for url in urls]
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 330,in connect
        cert = self.sock.getpeercert()
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\mmartin\AppData\Local\Continuum\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by mfk82** [comment]
I wrongly used the conda install command.
The pip install command works well.
