### ISSUE TITLE
Issue Creating New Conda Environment (and all other

### ISSUE THREAD

**Issue by mattfarkas** [conda/conda#4226]
Trying to get Python 3 running on my Python 2 Anaconda, updated Conda (and ipykernel), and now Conda isn't working at all. Error posted below.

<img width="349" alt="screen shot 2017-01-08 at 4 31 15 pm" src="https://cloud.githubusercontent.com/assets/19717219/21754153/f239fe98-d5bf-11e6-92db-b4354054e6a0.png">

Traceback (most recent call last):
  File "/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 225, in execute
    channels = list(prioritize_channels(channels).keys())
  File "/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 385, in prioritize_channels
    channel = Channel(chn)
  File "/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 166, in __call__
    c = Channel.from_value(value)
  File "/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 226, in from_value
    if value in context.custom_multichannels:
  File "/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 292, in custom_multichannels
    'defaults': self.default_channels,
  File "/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 277, in default_channels
    for v in self._default_channels)
  File "/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 277, in <genexpr>
    for v in self._default_channels)
  File "/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 260, in channel_alias
    location, scheme, auth, token = split_scheme_auth_token(self._channel_alias)
  File "/anaconda/lib/python2.7/site-packages/conda/common/url.py", line 195, in split_scheme_auth_token
    query=url_parts.query).url
AttributeError: 'Url' object has no attribute 'url'

**Comment by Zhdanovich** [comment]
I see the same issue running `conda update --all`

**Comment by mattfarkas** [comment]
Couldn't get it. Resorted to reinstalling distribution (w/ python 3)...

**Comment by kalefranz** [comment]
This was a bug in conda `4.2.7.  Running `conda update conda` would have fixed it for you.

**Comment by Zhdanovich** [comment]
@kalefranz I still have this issue. I'm using Mac OS 
conda --version
conda 4.3.6

**Comment by berttejeda** [comment]
I got around this error by uninstalling conda2 and going with conda3 (Anaconda3-4.3.1-MacOSX-x86_64.sh)
For projects that require python 2.x, I simply create these as needed, e.g. 
```conda create -n ${environment_name} python=2.7```
