### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by hobrien** [conda/conda#4250]
(python2)m001:R heo3$ conda install r-sartools
Fetching package metadata: ........
Solving package specifications: ...........................................An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/heo3/anaconda3/envs/python2/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 45, in execute
    install.install(args, parser, 'install')
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 333, in install
    update_deps=args.update_deps)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 411, in install_actions
    update_deps=update_deps):
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 1058, in solve
    installed, minimal_hint=minimal_hint, update_deps=update_deps)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 808, in solve2
    dists = self.get_dists(specs, filtered=True)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 709, in get_dists
    filtered = self.prune_packages(specs)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 506, in prune_packages
    if sum(touch(fn) for fn in self.find_matches(ms, True)) == 0:
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 506, in <genexpr>
    if sum(touch(fn) for fn in self.find_matches(ms, True)) == 0:
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 496, in touch
    touch(f2, force)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 496, in touch
    touch(f2, force)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 496, in touch
    touch(f2, force)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 492, in touch
    val = touched[fn] = force or is_valid(fn)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 483, in is_valid
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 483, in <genexpr>
    if not any(is_valid(f2) for f2 in self.find_matches(ms, True)):
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 516, in find_matches
    if self.filter_[fn] and ms.match(fn):
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 325, in match
    return any(vs.match(version) for vs in self.vspecs)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 325, in <genexpr>
    return any(vs.match(version) for vs in self.vspecs)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 301, in match
    return all(c.match(version) for c in self.constraints)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 301, in <genexpr>
    return all(c.match(version) for c in self.constraints)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 292, in match
    return ver_eval(version, self.spec)
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 271, in ver_eval
    return eval('VersionOrder("%s") %s VersionOrder("%s")' % (a, op, b))
  File "<string>", line 1, in <module>
  File "/Users/heo3/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 151, in __init__
    raise ValueError(message + "invalid character(s).")
ValueError: Malformed version string '1.4-2': invalid character(s).
(python2)m001:R heo3$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.8
  conda-build version : 1.18.2
       python version : 3.5.1.final.0
     requests version : 2.8.1
     root environment : /Users/heo3/anaconda3  (writable)
  default environment : /Users/heo3/anaconda3/envs/python2
     envs directories : /Users/heo3/anaconda3/envs
        package cache : /Users/heo3/anaconda3/pkgs
         channel URLs : https://conda.anaconda.org/bioconda/osx-64/
                        https://conda.anaconda.org/bioconda/noarch/
                        https://conda.anaconda.org/r/osx-64/
                        https://conda.anaconda.org/r/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/heo3/.condarc
    is foreign system : False

**Comment by hobrien** [comment]
This report caused me to be flagged as a spammer. I'm guessing it's because of the channel URLs? Are there best practices for reporting this issues that don't incur the wrath of the spam filters?

**Comment by kalefranz** [comment]
> This report caused me to be flagged as a spammer.

Where and how?  First I've heard of something like that happening.

**Comment by kalefranz** [comment]
Report, however, is for conda 3.18.8, which is very old.  3.x conda releases are no longer maintained.  Recommend `conda update conda`.  If you still have problems, file a new issue with the new stack trace.

**Comment by hobrien** [comment]
Thanks for the info. I've since updated. Shortly after posting this I got locked out of my github account and when I inquired I was told it was because of their spam filters
