### ISSUE TITLE
Fetching package metadata .......An unexpected error has occurred.

### ISSUE THREAD

**Issue by davidhassell** [conda/conda#4282]
Hello,

I have the following error, which suggests that I post it here. I hope that you can help ...

Many thanks,
David

>> conda install -c pcmdi cmor=3.2.1
Fetching package metadata .......An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/david/anaconda2  (writable)
    default environment : /home/david/anaconda2
       envs directories : /home/david/anaconda2/envs
          package cache : /home/david/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/david/anaconda2/bin/conda install -c pcmdi cmor=3.2.1`

    Traceback (most recent call last):
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/home/david/anaconda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/home/david/anaconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/home/david/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/home/david/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/home/david/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/david/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 617, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/home/david/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 110, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    TooManyRedirects: Exceeded 30 redirects.

**Comment by davidslac** [comment]
I just got the same error also - I have a later conda and requests==12:

```
conda install  -n ana-1.1.0-py3 -c conda-forge readline
Fetching package metadata ...............An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.14
       conda is private : False
      conda-env version : 4.2.14
    conda-build version : 2.1.0
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7  (writable)
    default environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/manage
       envs directories : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs
          package cache : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/pkgs
           channel URLs : file:///reg/g/psdm/sw/conda/channels/system-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/system-rhel7/noarch
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7/noarch
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/kalefranz/linux-64
                          https://conda.anaconda.org/kalefranz/noarch
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7/noarch
            config file : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc
           offline mode : False



`$ /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/manage/bin/conda install -n ana-1.1.0-py3 -c conda-forge readline`




    Traceback (most recent call last):
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 630, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 111, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    TooManyRedirects: Exceeded 30 redirects.

(manage) (psreldev) psel701: /reg/g/psdm/sw/conda/anarel-test $ 

```

**Comment by kalefranz** [comment]
Thanks for the report.  Error in switching some server configuration for ananconda.org.  Should clear up in less than 5 minutes.

**Comment by kalefranz** [comment]
Should be resolved now.

**Comment by davidslac** [comment]
I got another error at 12:08, output below. I'll try again
```
Fetching package metadata ..................An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.14
       conda is private : False
      conda-env version : 4.2.14
    conda-build version : 2.1.0
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7  (writable)
    default environment : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/manage
       envs directories : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs
          package cache : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/pkgs
           channel URLs : file:///reg/g/psdm/sw/conda/channels/system-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/system-rhel7/noarch
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/psana-rhel7/noarch
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/external-rhel7/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/kalefranz/linux-64
                          https://conda.anaconda.org/kalefranz/noarch
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7/linux-64
                          file:///reg/g/psdm/sw/conda/channels/testing-rhel7/noarch
            config file : /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc
           offline mode : False



`$ /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs/manage/bin/conda create -y -q -n ana-1.1.0 python supervisor eigen mock Flask biopython cffi numpydoc xz xarray cyordereddict h5netcdf MySQL-python mysql ptyprocess guppy click paramiko virtualenv tables=3.3.0 twine mysql-connector-python wrapt seaborn scons pytest pyqt=4.11.4 opencv bokeh openmpi=2.0.1 gevent werkzeug pillow sympy itsdangerous nltk numpy mkl-service pyzmq thinc tqdm sqlalchemy pyopengl simplejson keras python=2.7.12 neon swig pylint matplotlib cython scikit-beam joblib scipy tzlocal logbookclient coverage tensorflow=0.10.0 python-dateutil=2.5.3 bottleneck gensim ndarray qt=4.8.7 pyyaml jupyter pymc workerpool hdf5=1.8.18 boost=1.57.0 pyqtgraph scikit-learn numba pandas jinja2 psutil dask szip=2.1 nose plotly h5py=2.7.0 theano requests=2.11 ipython spyder psana-conda=1.1.0 mpi4py=2.0.0`




    Traceback (most recent call last):
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 474, in request
        prep = self.prepare_request(req)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/sessions.py", line 407, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
        self.prepare_auth(auth, url)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/requests/models.py", line 527, in prepare_auth
        r = auth(self)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/connection.py", line 118, in __call__
        request.url = CondaHttpAuth.add_binstar_token(request.url)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/connection.py", line 146, in add_binstar_token
        channel = Channel(clean_url)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/models/channel.py", line 166, in __call__
        c = Channel.from_value(value)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/models/channel.py", line 216, in from_value
        return Channel.from_url(value)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/models/channel.py", line 201, in from_url
        return parse_conda_channel_url(url)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/models/channel.py", line 137, in parse_conda_channel_url
        configured_token) = _read_channel_configuration(scheme, host, port, path)
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/models/channel.py", line 84, in _read_channel_configuration
        for name, location in sorted(context.migrated_custom_channels.items(), reverse=True,
      File "/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/lib/python2.7/site-packages/conda/common/configuration.py", line 461, in __get__
        return instance._cache_[self.name]
    KeyError: 'migrated_custom_channels'

conda env list --json
############################
## Release Builder - name=ana-1.1.0

## time: 2017-01-12 12:08:23.217410
```

**Comment by kalefranz** [comment]
`KeyError: 'migrated_custom_channels'` is a new one to me.  Can you give the the contents of any of your configuration files (`.condarc` files, etc).  Also the output of `conda config --show-sources` and `conda config --show`?

**Comment by davidslac** [comment]
Now it is working, so I can't reproduce it. From an admin account, I launch a script on three separate hosts - a rhel5/rhel6/rhel7 host, each is creating a conda environment in a separate miniconda installation - so there should be no weird race condition where the processes modify the same file - at least in the installations, however I did just look at the admin account .conda directory, and it has a environments.txt file that seems to list all the environments I've created among the three installations - so I see that there could be a race condition with that file -- don't know if that would explain it. Anyways, I'm not too worrried about it. The only channel change I made recently was to add your kalefranz to get guppy.

There's no .condarc in the admin .conda dir, the .condarc for the installation where I got the KeyError is
```
###########
# conda configuration for ana based conda releases.
# ref: http://conda.pydata.org/docs/config.html
#

channel_alias: https://conda.anaconda.org/
#    gets preprended to channel names that don't specify an exact loc

channels:
  - file:///reg/g/psdm/sw/conda/channels/system-rhel7
  - file:///reg/g/psdm/sw/conda/channels/psana-rhel7
  - file:///reg/g/psdm/sw/conda/channels/external-rhel7
  # prefer defaults to conda-forge
  # since defaults numpy works on rhel5, but conda-forge doesn't
  - defaults
  - conda-forge
  - kalefranz    # for guppy
  - file:///reg/g/psdm/sw/conda/channels/testing-rhel7

always_yes: False
#  False means ask to proceed before installation new packages, override with --yes

show_channel_urls: True
# True means show channel URLs during relevant operations and commands

changeps1: True
# True means prepend (env) to prompt

use_pip: True  
#  True means list pip installed packages from conda list

offline: False

allow_softlinks: True
#  False means if you can't make a hard link, don't make a soft link, copy files over
#  for users when they create environments from central install - if on a different file
#  system they will get soft links

# do we want all new environments to include certain packages?
# users can bypass with --no-default-packages flag if need be, but if so, uncomment and
# add them here

#create_default_packages:
#  - ipython

# when resolving new packages, look for these features
#track_features:
#   - mkl

# the docs read backwards, default is to always update 
# dependent packages, but docs say to set this to True to Not do that?
# made a pull request as davidslac - but haven't tried the option yet
#update_dependencies: False


#conda-build:
#    root-dir: /reg/g/psdm/sw/conda/build/dev-rhel7

# this blog: https://www.continuum.io/blog/developer/advanced-features-conda-part-1#configuration
# says that this option

#envs_dirs:
#  - /reg/g/psdm/sw/conda/envs/dev-rhel7

# is for A list of directories that conda will use to create environments and keep its package cache.
# useful to us?

# we are building some system dependent packages, so do we don't want to automatically 
# upload to a binstar account, assuming we set one up?
binstar_upload: False

# this is per https://github.com/conda/conda/issues/2681
# we want to protect ourselves from bugs in new versions of conda
auto_update_conda: false

```
For the other commands:
(manage) (psreldev) psel701: /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7 $ conda config ```
--show-sources
==> /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/.condarc <==
always_yes: False
channel_alias: https://conda.anaconda.org/
changeps1: True
show_channel_urls: True
channels:
  - file:///reg/g/psdm/sw/conda/channels/system-rhel7
  - file:///reg/g/psdm/sw/conda/channels/psana-rhel7
  - file:///reg/g/psdm/sw/conda/channels/external-rhel7
  - defaults
  - conda-forge
  - kalefranz
  - file:///reg/g/psdm/sw/conda/channels/testing-rhel7
allow_softlinks: True
binstar_upload: False
use_pip: True
offline: False
auto_update_conda: False
```
and
```
(manage) (psreldev) psel701: /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7 $ conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_softlinks: True
always_copy: False
always_yes: False
auto_update_conda: False
binstar_upload: False
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - file:///reg/g/psdm/sw/conda/channels/system-rhel7
  - file:///reg/g/psdm/sw/conda/channels/psana-rhel7
  - file:///reg/g/psdm/sw/conda/channels/external-rhel7
  - defaults
  - conda-forge
  - kalefranz
  - file:///reg/g/psdm/sw/conda/channels/testing-rhel7
client_tls_cert: 
client_tls_cert_key: 
create_default_packages: []
debug: False
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/pro
disallow: []
envs_dirs:
  - /reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel7/envs
json: False
offline: False
proxy_servers: {}
quiet: False
shortcuts: True
show_channel_urls: True
ssl_verify: True
track_features: []
update_dependencies: True
use_pip: True
verbosity: 0
```
