### ISSUE TITLE
redirecting errors when installing feather-format from conda-forge

### ISSUE THREAD

**Issue by cluoren** [conda/conda#4283]
Current conda install:

               platform : win-64
          conda version : 4.2.15
       conda is private : False
      conda-env version : 4.2.15
    conda-build version : 2.1.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\pcluo\Anaconda2  (writable)
    default environment : C:\Users\pcluo\Anaconda2
       envs directories : C:\Users\pcluo\Anaconda2\envs
          package cache : C:\Users\pcluo\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\pcluo\Anaconda2\Scripts\conda-script.py install feather-format -c conda-forge`

    Traceback (most recent call last):
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\cli\main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\requests\sessions.py", line 630, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "C:\Users\pcluo\Anaconda2\lib\site-packages\requests\sessions.py", line 111, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    TooManyRedirects: Exceeded 30 redirects.

**Comment by kalefranz** [comment]
Should be resolved now.
