### ISSUE TITLE
cvxgrp down?

### ISSUE THREAD

**Issue by tschm** [conda/conda#4284]
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /opt/conda/bin/conda install -y -q -c cvxgrp cvxpy`

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/opt/conda/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 617, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 617, in <listcomp>
        history = [resp for resp in gen] if allow_redirects else []
      File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 110, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

Service 'sut' failed to build: The command '/bin/sh -c conda install -y -q -c cvxgrp cvxpy' returned a non-zero code: 1

**Comment by kalefranz** [comment]
Thanks for the report.  Error in switching some server configuration for ananconda.org.  Should clear up in less than 5 minutes.

**Comment by tschm** [comment]
thanks, works again.
