### ISSUE TITLE
unexpected error installing ilastik cplex-shared=1.2.0rc8

### ISSUE THREAD

**Issue by joanarcx** [conda/conda#4285]
`conda install -c ilastik cplex-shared=1.2.0rc8`
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/jx/miniconda2  (writable)
    default environment : /Users/jx/miniconda2
       envs directories : /Users/jx/miniconda2/envs
          package cache : /Users/jx/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Users/jx/miniconda2/bin/conda install -c ilastik cplex-shared=1.2.0rc8`

    Traceback (most recent call last):
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
        for url in urls]
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 630, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/Users/jx/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 111, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    TooManyRedirects: Exceeded 30 redirects.

**Comment by kalefranz** [comment]
Thanks for the report.  Error in switching some server configuration for ananconda.org.  Should clear up in less than 5 minutes.

**Comment by jakirkham** [comment]
Also saw this recently when trying to build OpenCV. Have restarted to see if it goes away.

ref: https://circleci.com/gh/conda-forge/opencv-feedstock/121

**Comment by joanarcx** [comment]
the problem is solved. thank you.

**Comment by kalefranz** [comment]
Yeah, temporary hiccup in moving some server configuration around for anaconda.org.  The switchup shouldn't have caused down time, but it did, so it was unplanned.  Total down time was somewhere around 20 minutes.  Sorry for the trouble.
