### ISSUE TITLE
Too Many Exceptions when trying to install jupyterhub from conda-forge

### ISSUE THREAD

**Issue by avanbecelaere** [conda/conda#4286]
New ubuntu 16.04 install.  Have installed many times without a problem recently.  Just started getting this error today.

root@ip-172-31-35-224:/home/ubuntu# conda config --add channels conda-forge
root@ip-172-31-35-224:/home/ubuntu# conda install jupyterhub
Fetching package metadata .......An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /opt/anaconda3  (writable)
    default environment : /opt/anaconda3
       envs directories : /opt/anaconda3/envs
          package cache : /opt/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /root/.condarc
           offline mode : False

`$ /opt/anaconda3/bin/conda install jupyterhub`

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/opt/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/opt/anaconda3/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
        raise self._exception
      File "/opt/anaconda3/lib/python3.5/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 617, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 617, in <listcomp>
        history = [resp for resp in gen] if allow_redirects else []
      File "/opt/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 110, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by kalefranz** [comment]
Thanks for the report. Error in switching some server configuration for ananconda.org. Should clear up in less than 5 minutes.

**Comment by kalefranz** [comment]
Should be resolved now.
