### ISSUE TITLE
TooManyRedirects exception when installing tensorflow

### ISSUE THREAD

**Issue by jepessen** [conda/conda#4287]
Python version 3.5.2
Anaconda Version 4.2.0
Windows 10 64 bit (Anaconda 64 bit installation)

I'm trying to install `tensorflow` with Anaconda using the instruction at following page:

https://www.tensorflow.org/get_started/os_setup#anaconda_installation

When I execute the installation command

`conda create -n tensorflow python=3.5`

I obtain a `TooManyRedirects` exception. This is the output:

(C:\Users\jepes\Anaconda3) C:\Users\jepes>conda create -n tensorflow python=3.5
Fetching package metadata .........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\jepes\Anaconda3  (writable)
    default environment : C:\Users\jepes\Anaconda3
       envs directories : C:\Users\jepes\Anaconda3\envs
          package cache : C:\Users\jepes\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\jepes\.condarc
           offline mode : False

`$ C:\Users\jepes\Anaconda3\Scripts\conda-script.py create -n tensorflow python=3.5`

    Traceback (most recent call last):
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\jepes\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\jepes\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\jepes\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\jepes\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\jepes\Anaconda3\lib\site-packages\requests\sessions.py", line 617, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "C:\Users\jepes\Anaconda3\lib\site-packages\requests\sessions.py", line 617, in <listcomp>
        history = [resp for resp in gen] if allow_redirects else []
      File "C:\Users\jepes\Anaconda3\lib\site-packages\requests\sessions.py", line 110, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

**Comment by kalefranz** [comment]
Thanks for the report. Error in switching some server configuration for ananconda.org. Should clear up in less than 5 minutes.

**Comment by kalefranz** [comment]
Should be resolved now.
