### ISSUE TITLE
Conda cannot update !

### ISSUE THREAD

**Issue by baletercero** [conda/conda#4288]
C:\Users\Pablo\Documents>conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 107, in _main
    p, sub_parsers = generate_parser()
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 15, in <module>
    from ..install import dist2quad
ImportError: cannot import name 'dist2quad'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 402, in get_info
    from conda.cli import conda_argparse
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 15, in <module>
    from ..install import dist2quad
ImportError: cannot import name 'dist2quad'

**Comment by kalefranz** [comment]
What is the output of your `conda info`?

**Comment by larass** [comment]
I got the same issue: After successfully doing "conda update conda" yesterday, it failed this morning
For traceback and conda info see the attachment
[conda_output.txt](https://github.com/conda/conda/files/703802/conda_output.txt)

**Comment by kalefranz** [comment]
@larass your error is different than the one above.

The following will likely fix your error:

```
conda config --set ssl_verify false
conda update conda
conda config --remove-key ssl_verify
```

**Comment by kalefranz** [comment]
@baletercero I need the output of your `conda info` to help you further.

**Comment by baletercero** [comment]
@kalefranz thank you Kale , I tried the conda update route described but I started getting errors so I uninstalled and reinstalled Anaconda 3, then I tried conda install -c conda-forge cartopy and that worked. I just  now tried conda install -c scitools cartopy and now it worked fine, so thanks for your help but I can't duplicate the error again. Best regards
bale
