### ISSUE TITLE
maximum recursion depth exceeded  conda install -c vdbwrair imagemagick=6.9.3

### ISSUE THREAD

**Issue by obgeneralao** [conda/conda#4295]
Hi I am getting an error when i tried to install a package and even updating python. Below is the error message
==================================
Current conda install:

               platform : linux-64
          conda version : 4.2.15
       conda is private : False
      conda-env version : 4.2.15
    conda-build version : not installed
         python version : 2.7.11.final.0
       requests version : 2.12.4
       root environment : /home/sand/ogeneralao/miniconda2  (writable)
    default environment : /home/sand/ogeneralao/miniconda2
       envs directories : /home/sand/ogeneralao/miniconda2/envs
          package cache : /home/sand/ogeneralao/miniconda2/pkgs
           channel URLs : https://conda.anaconda.org/diffpy/linux-64
                          https://conda.anaconda.org/diffpy/noarch
                          https://conda.anaconda.org/MDAnalysis/linux-64
                          https://conda.anaconda.org/MDAnalysis/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/sand/ogeneralao/.condarc
           offline mode : False

`$ /home/sand/ogeneralao/miniconda2/bin/conda install -c vdbwrair imagemagick=6.9.3`

    Traceback (most recent call last):
      File "/home/sand/ogeneralao/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/sand/ogeneralao/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/home/sand/ogeneralao/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/sand/ogeneralao/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: maximum recursion depth exceeded

**Comment by obgeneralao** [comment]
Hi
using  conda install -c kalefranz imagemagick=6.9.1 , installed ImageMagick successfully
