### ISSUE TITLE
"conda list" doesn't work?

### ISSUE THREAD

**Issue by MichaelASanders** [conda/conda#4301]
Hello world,

I entered in the following text in Windows Powershell:

conda list

and received the following error:

```
Traceback (most recent call last):
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\main.py", line 107, in _main
    p, sub_parsers = generate_parser()
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: Module use of python35.dll conflicts with this version of Python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\mrnom\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\exceptions.py", line 402, in get_info
    from conda.cli import conda_argparse
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\mrnom\Anaconda3\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: Module use of python35.dll conflicts with this version of Python.
```

Not sure what it means, but it may have something to do with the way I set up permanent aliases for python2 and python3.

Any help would be much appreciated.

**Comment by kalefranz** [comment]
> it may have something to do with the way I set up permanent aliases for python2 and python3.

Yup. You have different pythons getting confused with each other.
