### ISSUE TITLE
Unexpected issue trying to install conda 4.3

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#4303]
Tried to upgrade `conda` by running `conda install -n root conda=4.3`. However, that appears to have not agreed with it and I got the rather lengthy traceback below.

<details>

```bash
$ conda install -n root conda=4.3
Fetching package metadata ............An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.1
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /zopt/conda2  (writable)
    default environment : /zopt/conda2/envs/nanshenv
       envs directories : /zopt/conda2/envs
          package cache : /zopt/conda2/pkgs
           channel URLs : https://conda.anaconda.org/nanshe/osx-64
                          https://conda.anaconda.org/nanshe/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/jakirkham/osx-64
                          https://conda.anaconda.org/jakirkham/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/kirkhamj/.condarc
           offline mode : False



`$ /zopt/conda2/envs/nanshenv/bin/conda install -n root conda=4.3`




    Traceback (most recent call last):
      File "/zopt/conda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/zopt/conda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/zopt/conda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
        return self.__get_result()
      File "/zopt/conda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 474, in request
        prep = self.prepare_request(req)
      File "/zopt/conda2/lib/python2.7/site-packages/requests/sessions.py", line 407, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "/zopt/conda2/lib/python2.7/site-packages/requests/models.py", line 306, in prepare
        self.prepare_auth(auth, url)
      File "/zopt/conda2/lib/python2.7/site-packages/requests/models.py", line 527, in prepare_auth
        r = auth(self)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/connection.py", line 112, in __call__
        request.url = CondaHttpAuth.add_binstar_token(request.url)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/connection.py", line 140, in add_binstar_token
        channel = Channel(clean_url)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/models/channel.py", line 166, in __call__
        c = Channel.from_value(value)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/models/channel.py", line 216, in from_value
        return Channel.from_url(value)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/models/channel.py", line 201, in from_url
        return parse_conda_channel_url(url)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/models/channel.py", line 137, in parse_conda_channel_url
        configured_token) = _read_channel_configuration(scheme, host, port, path)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/models/channel.py", line 102, in _read_channel_configuration
        for name, channel in sorted(context.custom_channels.items(), reverse=True,
      File "/zopt/conda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/base/context.py", line 304, in custom_channels
        all_sources = self.default_channels, (self.local_build_root_channel,), custom_channels
      File "/zopt/conda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/base/context.py", line 277, in default_channels
        for v in self._default_channels)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/base/context.py", line 277, in <genexpr>
        for v in self._default_channels)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/base/context.py", line 260, in channel_alias
        location, scheme, auth, token = split_scheme_auth_token(self._channel_alias)
      File "/zopt/conda2/lib/python2.7/site-packages/conda/common/configuration.py", line 461, in __get__
        return instance._cache_[self.name]
    KeyError: '_channel_alias'

```

</details>
<br>

Also info about my environment.

<details>

```bash
$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.12
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /zopt/conda2  (writable)
    default environment : /zopt/conda2/envs/nanshenv
       envs directories : /zopt/conda2/envs
          package cache : /zopt/conda2/pkgs
           channel URLs : https://conda.anaconda.org/nanshe/osx-64
                          https://conda.anaconda.org/nanshe/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/jakirkham/osx-64
                          https://conda.anaconda.org/jakirkham/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/kirkhamj/.condarc
           offline mode : False

$ conda list -n root
# packages in environment at /zopt/conda2:
#
anaconda-client           1.5.1                    py27_0    conda-forge
anaconda-verify           1.2.0                    py27_0    conda-forge
appnope                   0.1.0                    py27_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py27_1    conda-forge
beautifulsoup4            4.5.3                    py27_0    defaults
ca-certificates           2016.9.26                     0    conda-forge
certifi                   2016.9.26                py27_0    conda-forge
chardet                   2.3.0                    py27_0    defaults
clyent                    1.2.1                    py27_0    conda-forge
conda                     4.2.13                   py27_0    conda-forge
conda-build               2.0.12                   py27_0    conda-forge
conda-build-all           1.0.1                    py27_1    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-execute             0.8.0                    py27_0    conda-forge
conda-verify              2.0.0                    py27_0    defaults
constructor               1.3.4                    py27_0    conda-forge
contextlib2               0.5.4                    py27_0    conda-forge
coverage                  3.7.1                    py27_0    conda-forge
curl                      7.49.1                        2    conda-forge
decorator                 4.0.10                   py27_0    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
expat                     2.1.0                         2    conda-forge
filelock                  2.0.6                    py27_0    conda-forge
funcsigs                  1.0.2                    py27_0    conda-forge
futures                   3.0.5                    py27_0    conda-forge
gitdb                     0.6.4                    py27_1    conda-forge
gitpython                 2.1.1                    py27_0    conda-forge
ipython                   5.1.0                    py27_2    conda-forge
ipython_genutils          0.1.0                    py27_0    conda-forge
jinja2                    2.8                      py27_1    conda-forge
libconda                  4.0.0                    py27_0    conda-forge
markupsafe                0.23                     py27_1    conda-forge
mock                      2.0.0                    py27_0    conda-forge
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py27_2    conda-forge
openssl                   1.0.2h                        3    conda-forge
pathlib2                  2.1.0                    py27_0    conda-forge
pbr                       1.10.0                   py27_0    conda-forge
pexpect                   4.2.1                    py27_0    conda-forge
pickleshare               0.7.3                    py27_0    conda-forge
pip                       9.0.1                    py27_0    conda-forge
pkginfo                   1.2.1                    py27_0    conda-forge
prompt_toolkit            1.0.9                    py27_0    conda-forge
psutil                    4.3.0                    py27_0    conda-forge
ptyprocess                0.5.1                    py27_0    conda-forge
pycosat                   0.6.1                    py27_0    conda-forge
pycrypto                  2.6.1                    py27_0    conda-forge
pygithub                  1.29                     py27_0    conda-forge
pygments                  2.1.3                    py27_1    conda-forge
python                    2.7.12                        1    conda-forge
python-dateutil           2.6.0                    py27_0    conda-forge
python.app                1.2                      py27_4    defaults
pytz                      2016.10                  py27_0    conda-forge
pyyaml                    3.11                     py27_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.12.4                   py27_0    conda-forge
ruamel.ordereddict        0.4.6                    py27_0    conda-forge
ruamel.yaml               0.11.11                  py27_1    conda-forge
ruamel_yaml               0.11.14                  py27_0    conda-forge
setuptools                32.3.1                   py27_0    conda-forge
simplegeneric             0.8.1                    py27_0    conda-forge
six                       1.10.0                   py27_1    conda-forge
smmap                     2.0.1                    py27_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        1    conda-forge
traitlets                 4.3.1                    py27_0    conda-forge
wcwidth                   0.1.7                    py27_0    conda-forge
wheel                     0.29.0                   py27_0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
```

</details>

**Comment by kalefranz** [comment]
Thanks for the report.  The bug is actually in 4.2 (since that was the code you were running).   A couple requests for more information...

1. Can you give me the output of `conda config --show` and `conda config --show-sources` as it was when you tried to run the command and it failed?
2. Can you try to run just in your root environment, without the `-n root`.
