### ISSUE TITLE
Unable to install or update packages

### ISSUE THREAD

**Issue by oothomas** [conda/conda#4308]
I get the following errors when I try to use conda install, pip install, or easy_install in any way at all. Even conda update conda fails. I think I recently updated python. Could that be why? Looking forward to hearing from you.

               platform : win-64
          conda version : 4.2.14
       conda is private : False
      conda-env version : 4.2.14
    conda-build version : 1.19.0
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\XXXXX\Anaconda3  (writable)
    default environment : C:\Users\XXXXX\Anaconda3
       envs directories : C:\Users\XXXXX\Anaconda3\envs
          package cache : C:\Users\XXXXX\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\XXXXX\Anaconda3\Scripts\conda-script.py search python`

    Traceback (most recent call last):
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\cli\main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\cli\main_search.py", line 126, in execute
        execute_search(args, parser)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\cli\main_search.py", line 174, in execute_search
        unknown=args.unknown)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\XXXXX\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\XXXXX\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\XXXXX\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Users\XXXXX\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by kalefranz** [comment]
The fix here for you should be just

    CONDA_SSL_VERIFY=false conda update conda

This works on unix (linux/osx) only.  The windows fix is slightly different.

**Comment by oothomas** [comment]
Found the equivalent windows solution.

Thank you!

**Comment by MissGupta** [comment]
Please post the solution for windows too!
