### ISSUE TITLE
Error after a conda update --all

### ISSUE THREAD

**Issue by popfido** [conda/conda#4313]
This error happened after an update of my conda environment from 1.5.5 to 1.6.0

Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /root/anaconda2  (writable)
    default environment : /root/anaconda2
       envs directories : /root/anaconda2/envs
          package cache : /root/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-327.36.3.el7.x86_64 CentOS Linux/7.2.1511 glibc/2.17
                UID:GID : 0:0

```
`$ /root/anaconda2/bin/conda update --all`




    Traceback (most recent call last):
      File "/root/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 434, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 422, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 390, in _collect_repodatas_serial
        for url in urls]
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 141, in func
        res = f(*args, **kwargs)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 366, in fetch_repodata
        return read_local_repodata(cache_path)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 336, in read_local_repodata
        local_repodata = json.load(f)
      File "/root/anaconda2/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/root/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/root/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/root/anaconda2/lib/python2.7/json/decoder.py", line 380, in raw_decode
        obj, end = self.scan_once(s, idx)
    ValueError: Expecting object: line 11750 column 6 (char 303397)
```

**Comment by kalefranz** [comment]
I don't understand 

> conda environment from 1.5.5 to 1.6.0

What do those versions refer to?

**Comment by kalefranz** [comment]
It's possible that `conda clean --index-cache` might solve your problem.

**Comment by kalefranz** [comment]
created https://github.com/conda/conda/pull/4315 for better error message
