### ISSUE TITLE
No module named pycosat

### ISSUE THREAD

**Issue by mkaya93** [conda/conda#4320]
Hello, 

I'm getting this error when I'm trying to install tensorflow or try to run any conda command on Mac os X. 

`conda install -c conda-forge tensorflow`

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/usr/local/bin/conda", line 11, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "/Library/Python/2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/Library/Python/2.7/site-packages/conda/exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Library/Python/2.7/site-packages/conda/exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Library/Python/2.7/site-packages/conda/exceptions.py", line 395, in get_info
    from conda.cli import conda_argparse
  File "/Library/Python/2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/Library/Python/2.7/site-packages/conda/cli/common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "/Library/Python/2.7/site-packages/conda/resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "/Library/Python/2.7/site-packages/conda/logic.py", line 31, in <module>
    import pycosat
ImportError: No module named pycosat
```

**Comment by Korijn** [comment]
We're seeing this kind of error on all kinds of packages across our entire range of projects. It seems the latest conda versions are breaking internal assumptions.

**Comment by kalefranz** [comment]
@mkaya93  what version of conda are you running?  What's the output of `conda info`?  Also, how did you even install conda on your system?  Those directory structures don't look right to me.

**Comment by kalefranz** [comment]
@Korijn I just saw you commented here.  Did you get your issue resolved?

**Comment by Korijn** [comment]
it was solved for us in #4338

**Comment by kalefranz** [comment]
ok good deal

**Comment by sahil14719** [comment]
: No module named 'pycosat'
PS C:\Users\sahil> conda info
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



`$ C:\Users\sahil\AppData\Local\Programs\Python\Python36\Scripts\conda info`




    Traceback (most recent call last):
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\main.py", line 106, in _main
        p, sub_parsers = generate_parser()
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\main.py", line 55, in generate_parser
        from ..cli import conda_argparse
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
        from .common import add_parser_help
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\common.py", line 16, in <module>
        from ..resolve import MatchSpec
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\resolve.py", line 14, in <module>
        from .logic import minimal_unsatisfiable_subset, Clauses
      File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\logic.py", line 31, in <module>
        import pycosat
    ModuleNotFoundError: No module named 'pycosat'

Traceback (most recent call last):
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\main.py", line 106, in _main      p, sub_parsers = generate_parser()
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\main.py", line 55, in generate_parser
    from ..cli import conda_argparse
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\resolve.py", line 14, in <module>     from .logic import minimal_unsatisfiable_subset, Clauses
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\logic.py", line 31, in <module>       import pycosat
ModuleNotFoundError: No module named 'pycosat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sahil\AppData\Local\Programs\Python\Python36\Scripts\conda-script.py", line 11, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\main.py", line 150, in main       return conda_exception_handler(_main)
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\exceptions.py", line 489, in conda_exception_handler
    delete_lock()
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\exceptions.py", line 452, in delete_lock
    from .cli.main_clean import find_lock
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\main_clean.py", line 14, in <module>
    from .common import add_parser_json, add_parser_yes, confirm_yn, stdout_json
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\resolve.py", line 14, in <module>     from .logic import minimal_unsatisfiable_subset, Clauses
  File "c:\users\sahil\appdata\local\programs\python\python36\lib\site-packages\conda\logic.py", line 31, in <module>       import pycosat
ModuleNotFoundError: No module named 'pycosat'
