### ISSUE TITLE
Failure to download from ftp

### ISSUE THREAD

**Issue by msarahan** [conda/conda#4334]
@shadowwalkersb commented on [Mon Jan 16 2017](https://github.com/conda/conda-build/issues/1665)

When download url is ftp, the download fails. If I download the source tarball manually (when running locally) into `conda-bld/src_cache` `conda-build` works.

The recipe: https://github.com/shadowwalkersb/szip-feedstock/blob/master/recipe/meta.yaml.

Builds on TravisCI, CircleCI and Appveyor:

https://travis-ci.org/shadowwalkersb/szip-feedstock#L246-L285
https://circleci.com/gh/shadowwalkersb/szip-feedstock/3
https://ci.appveyor.com/project/shadow_walker/szip-feedstock

```
Downloading source to cache: szip-2.1.tar.gz
Downloading ftp://ftp.hdfgroup.org/lib-external/szip/2.1/src/szip-2.1.tar.gz
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 321, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.5/site-packages/conda_build/cli/main_build.py", line 312, in execute
    noverify=args.no_verify)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/api.py", line 89, in build
    need_source_download=need_source_download, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 1460, in build_tree
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/build.py", line 961, in build
    config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/render.py", line 86, in parse_or_try_download
    source.provide(metadata, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/source.py", line 498, in provide
    unpack(metadata, config=config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/source.py", line 80, in unpack
    src_path = download_to_cache(meta, config)
  File "/opt/conda/lib/python3.5/site-packages/conda_build/source.py", line 61, in download_to_cache
    download(url, path)
  File "/opt/conda/lib/python3.5/site-packages/conda/fetch.py", line 394, in download
    resp = session.get(url, stream=True, proxies=session.proxies, timeout=(6.1, 60))
  File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/conda/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/opt/conda/lib/python3.5/site-packages/conda/connection.py", line 364, in send
    resp = self.func_table[request.method](path, request)
  File "/opt/conda/lib/python3.5/site-packages/conda/connection.py", line 404, in retr
    response = build_binary_response(request, data, code)
  File "/opt/conda/lib/python3.5/site-packages/conda/connection.py", line 519, in build_binary_response
    return build_response(request, data, code,  None)
  File "/opt/conda/lib/python3.5/site-packages/conda/connection.py", line 533, in build_response
    response.status_code = int(code.split()[0])
ValueError: invalid literal for int() with base 10: '226-File'
```

---

@msarahan commented on [Mon Jan 16 2017](https://github.com/conda/conda-build/issues/1665#issuecomment-273002251)

Moving to conda, as this is completely duplicatable without conda-build in the loop:

```
from conda import fetch
fetch.download(url="ftp://ftp.hdfgroup.org/lib-external/szip/2.1/src/szip-2.1.tar.gz", dst_path='szip-2.1.tar.gz')
```

repeats this error for me.

**Comment by shadowwalkersb** [comment]
ping @kalefranz , seems like pretty basic functionality, downloading  from ftp.

**Comment by kalefranz** [comment]
@shadowwalkersb Can you try again with a recent version of conda?

    conda update conda

If you still have problems, give me the new stack trace.

**Comment by shadowwalkersb** [comment]
Updating conda fixed the problem. Thanks!
