### ISSUE TITLE
Error in trying to update

### ISSUE THREAD

**Issue by LEO-E-100** [conda/conda#4336]
When attempting to use `conda update conda` throws this unexpected error.

`Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.14
       conda is private : False
      conda-env version : 4.2.14
    conda-build version : 1.14.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Applications/anaconda  (writable)
    default environment : /Applications/anaconda
       envs directories : /Applications/anaconda/envs
          package cache : /Applications/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /Applications/anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
        for url in urls]
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Applications/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "/Applications/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'`

**Comment by kalefranz** [comment]
CONDA_SSL_VERIFY=false conda update conda
