### ISSUE TITLE
conda create error, could not connect to https://repo.******

### ISSUE THREAD

**Issue by ChangXiaodong** [conda/conda#4337]
Fetching package metadata ...Could not connect to https://repo.continuum.io/pkgs/msys2/win-64/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
Could not connect to https://repo.continuum.io/pkgs/msys2/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/noarch/
Could not connect to https://repo.continuum.io/pkgs/pro/win-64/
Could not connect to https://repo.continuum.io/pkgs/pro/noarch/
Could not connect to https://repo.continuum.io/pkgs/free/win-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : d:\Anaconda\Anaconda3  (writable)
    default environment : d:\Anaconda\Anaconda3
       envs directories : d:\Anaconda\Anaconda3\envs
          package cache : d:\Anaconda\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ d:\Anaconda\Anaconda3\Scripts\conda-script.py create --name tensorflow python=3`

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "d:\Anaconda\Anaconda3\lib\ssl.py", line 377, in wrap_socket
        _context=self)
      File "d:\Anaconda\Anaconda3\lib\ssl.py", line 752, in __init__
        self.do_handshake()
      File "d:\Anaconda\Anaconda3\lib\ssl.py", line 988, in do_handshake
        self._sslobj.do_handshake()
      File "d:\Anaconda\Anaconda3\lib\ssl.py", line 633, in do_handshake
        self._sslobj.do_handshake()
    socket.timeout: _ssl.c:629: The handshake operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 355, in _make_request
        self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 315, in _raise_timeout
        raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "d:\Anaconda\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "d:\Anaconda\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "d:\Anaconda\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out. (read timeout=3.05)",)): https://repo.continuum.io/pkgs/free/win-64/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 98, in create_connection
        raise err
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 88, in create_connection
        sock.connect(sa)
    socket.timeout: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 147, in _new_conn
        (self.host, self.timeout))
    requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D316C3D68>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D316C3D68>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\requests\adapters.py", line 479, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D316C3D68>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in fetch_index
        for url in urls]
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in <listcomp>
        for url in urls]
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "d:\Anaconda\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0000021D316C3D68>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')): https://repo.continuum.io/pkgs/free/win-64/

**Comment by kalefranz** [comment]
This is an intermittent HTTP timeout.  Just retry.  `conda update conda` will also help.
