### ISSUE TITLE
Unable to perform scikit-learn update

### ISSUE THREAD

**Issue by jaisonjose89m** [conda/conda#4352]
Error message printed:
 Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\jai\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\jai\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\jai\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\jai\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\jai\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py update scikit-learn`

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 98, in create_connection
        raise err
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 88, in create_connection
        sock.connect(sa)
    socket.timeout: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 147, in _new_conn
        (self.host, self.timeout))
    requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD616E1668>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD616E1668>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 479, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD616E1668>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 287, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD616E1668>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')): https://repo.continuum.io/pkgs/free/win-64/

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 142, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 98, in create_connection
        raise err
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 88, in create_connection
        sock.connect(sa)
    socket.timeout: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 254, in connect
        conn = self._new_conn()
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 147, in _new_conn
        (self.host, self.timeout))
    requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD63737908>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 668, in urlopen
        release_conn=release_conn, **response_kw)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 287, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD63737908>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\adapters.py", line 479, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD63737908>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in fetch_index
        for url in urls]
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 293, in <listcomp>
        for url in urls]
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\jai\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x000001BD63737908>, 'Connection to repo.continuum.io timed out. (connect timeout=3.05)')): https://repo.continuum.io/pkgs/free/win-64/

**Comment by kalefranz** [comment]
This is an HTTP timeout issue.  Probably intermittent.  Also, `conda update conda` might help.
