### ISSUE TITLE
unable to install luigi

### ISSUE THREAD

**Issue by ralbright-insiderscore** [conda/conda#4354]
Traceback (most recent call last):
  File "/home/ralbright/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 231, in install
    index = common.get_index_trap(**index_args)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 627, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/api.py", line 25, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 398, in result
    return self.__get_result()
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 68, in func
    res = f(*args, **kwargs)
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 99, in fetch_repodata
    if "_etag" in cache:
TypeError: argument of type 'NoneType' is not iterableconda info
Traceback (most recent call last):
  File "/home/ralbright/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 61, in main
    from conda.cli import conda_argparse
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/cli/common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "/home/ralbright/miniconda/lib/python2.7/site-packages/conda/logic.py", line 31, in <module>
    import pycosat
ImportError: /home/ralbright/miniconda/lib/python2.7/site-packages/pycosat.so: failed to map segment from shared object: Cannot allocate memory
Current conda install:

             platform : linux-64
        conda version : 4.1.12
    conda-env version : 2.5.2
  conda-build version : 2.1.1
       python version : 2.7.12.final.0
     requests version : 2.2.1
     root environment : /home/ralbright/miniconda  (writable)
  default environment : /home/ralbright/miniconda
     envs directories : /home/ralbright/miniconda/envs
        package cache : /home/ralbright/miniconda/pkgs
         channel URLs : https://conda.anaconda.org/auto/linux-64/
                        https://conda.anaconda.org/auto/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/ralbright/.condarc
         offline mode : False
    is foreign system : False

**Comment by ralbright-insiderscore** [comment]
this gets fixed by deleting the miniconda dir and reinstalling the miniconda env using the miniconda latest installer.  I shouldnt have had to do this though.

conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : 2.1.1
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /home/ralbright/miniconda  (writable)
    default environment : /home/ralbright/miniconda
       envs directories : /home/ralbright/miniconda/envs
          package cache : /home/ralbright/miniconda/pkgs
           channel URLs : https://conda.anaconda.org/auto/linux-64
                          https://conda.anaconda.org/auto/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/ralbright/.condarc
           offline mode : False
             user-agent : conda/4.3.4 requests/2.12.4 CPython/2.7.12 Linux/3.16.0-4-amd64 debian/8.6 glibc/2.19
                UID:GID : 1000:1000

**Comment by ralbright-insiderscore** [comment]
conda install luigi
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment /home/ralbright/miniconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    luigi-1.0.13               |           py27_0         274 KB  auto
    requests-2.12.4            |           py27_0         762 KB
    conda-4.3.4                |           py27_0         465 KB
    ------------------------------------------------------------
                                           Total:         1.5 MB

The following NEW packages will be INSTALLED:

    luigi:     1.0.13-py27_0 auto

The following packages will be UPDATED:

    conda:     4.1.12-py27_0      --> 4.3.4-py27_0 
    conda-env: 2.5.2-py27_0       --> 2.6.0-0      
    requests:  2.0.1-py27_0  auto --> 2.12.4-py27_0

Proceed ([y]/n)? y

**Comment by kalefranz** [comment]
> this gets fixed by deleting the miniconda dir and reinstalling the miniconda env using the miniconda latest installer

`conda update conda` also should have worked for you.
