### ISSUE TITLE
install.extract fails with conda installed on NFS, when package is in use

### ISSUE THREAD

**Issue by capadgett** [conda/conda#4356]
Trying to create a new environment, using an explicit package listing and a conda installed on a shared NFS mount.

From the error message:

```
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : .../miniconda3  (writable)
    default environment : .../miniconda3
       envs directories : .../miniconda3/envs
          package cache : .../miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

...

    Traceback (most recent call last):
      File "/.../miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File ".../miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "../miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File ".../miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 191, in install
        explicit(specs, prefix, verbose=not context.quiet, index_args=index_args)
      File ".../miniconda3/lib/python3.5/site-packages/conda/misc.py", line 187, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File ".../miniconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File ".../miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File ".../miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File ".../miniconda3/lib/python3.5/site-packages/conda/install.py", line 807, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File ".../miniconda3/lib/python3.5/site-packages/conda/common/disk.py", line 148, in exp_backoff_fn
        return fn(*args, **kwargs)
    FileExistsError: [Errno 17] File exists: '.../miniconda3/pkgs/zlib-1.2.8-3.tmp' -> '.../miniconda3/pkgs/zlib-1.2.8-3'

```

The main issue AFAICT is that some process has a file under the pkgs/zlib-1.2.8-3 folder open (probably a .so). When install.extract() tries to rm_rf() the target package path, NFS v3 uses "silly rename" to act like the open file got deleted, but it leaves a .nfs....... file in place of the original file. So the rm_rf of the target package path silently fails in install.extract(), then the os.rename loudly fails.

The .nfs...... files will not be removed until the process that has them open exits. In the case of a daemon process, this could be a while.

A "silly rename" like work-around is:
```
--- install.py	2017-01-18 14:26:31.394302133 +0000
+++ install.py.new	2017-01-18 15:23:46.090889706 +0000
@@ -35,6 +35,7 @@
 import sys
 import tarfile
 import traceback
+import datetime
 from collections import namedtuple
 from enum import Enum
 from itertools import chain
@@ -805,6 +806,12 @@
         with tarfile.open(fname) as t:
             t.extractall(path=temp_path)
         rm_rf(path)
+        # In case the rm_rf does not fully remove everything (e.g. permission
+        # denied, open files on NFS mount, etc.), move it out of the way
+        if os.path.exists(path):
+            timestamp = datetime.datetime.now().isoformat().replace(':', '_')
+            backup_path = path + '.' + timestamp
+            exp_backoff_fn(os.rename, path, backup_path)
         exp_backoff_fn(os.rename, temp_path, path)
         if sys.platform.startswith('linux') and os.getuid() == 0:
             # When extracting as root, tarfile will by restore ownership
```

But this will likely require manual cleanup.

**Comment by kalefranz** [comment]
A lot of this underlying logic has changed in conda 4.3.  Mind running `conda update conda` and reporting back?

**Comment by capadgett** [comment]
I will try it and let you know.

**Comment by capadgett** [comment]
That did it. Sorry to waste time on this. I will remember to update conda in the future.
