### ISSUE TITLE
broke conda when I uninstalled cryptography package

### ISSUE THREAD

**Issue by amkellett** [conda/conda#4359]
I was having trouble installing the pillow package and a search here seemed to indicate I may have success if I uninstalled the cryptography package and reinstalled it at version 1.1. Neither operation proceeded cleanly and when I tried to run conda to get back to where I started I got the following:

Oh - and I am posting this because it was suggested, but I would also like advice on how to fix.  I would like to avoid doing something as drastic as just uninstalling and reinstalling Anaconda. 
```
>  An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues




Traceback (most recent call last):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 113, in _main
    p, sub_parsers = generate_parser()
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 14, in <module>
    from .read import get_json_content
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 20, in <module>
    from ...models.channel import Channel
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\models\channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 165, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 530, in get_info
    args.func(args, p)
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 142, in execute
    from conda.api import get_index
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\index.py", line 18, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Users\kellett\AppData\Local\Continuum\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 112, in <module>
    if _lib.Cryptography_HAS_SSL_ST:
AttributeError: module 'lib' has no attribute 'Cryptography_HAS_SSL_ST'
```

```
I am also attaching the last part of my conda-meta/history:
==> 2017-01-17 09:18:56 <==
# cmd: C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install pillow
-_nb_ext_conf-0.2.0-py35_0
-alabaster-0.7.8-py35_0
-anaconda-4.1.1-np111py35_0
-anaconda-client-1.4.0-py35_0
-anaconda-navigator-1.2.1-py35_0
-argcomplete-1.0.0-py35_1
-astropy-1.2.1-np111py35_0
-babel-2.3.3-py35_0
-backports-1.0-py35_0
-beautifulsoup4-4.4.1-py35_0
-bitarray-0.8.1-py35_1
-blaze-0.10.1-py35_0
-bokeh-0.12.0-py35_0
-boto-2.40.0-py35_0
-bottleneck-1.1.0-np111py35_0
-bzip2-1.0.6-vc14_3
-cffi-1.6.0-py35_0
-chest-0.2.3-py35_0
-click-6.6-py35_0
-cloudpickle-0.2.1-py35_0
-clyent-1.2.2-py35_0
-colorama-0.3.7-py35_0
-comtypes-1.1.2-py35_0
-conda-4.3.4-py35_0
-conda-build-1.21.3-py35_0
-conda-env-2.6.0-0
-configobj-5.0.6-py35_0
-console_shortcut-0.1.1-py35_1
-contextlib2-0.5.3-py35_0
-cryptography-1.4-py35_0
-curl-7.49.0-vc14_0
-cycler-0.10.0-py35_0
-cython-0.24-py35_0
-cytoolz-0.8.0-py35_0
-dask-0.10.0-py35_0
-datashape-0.5.2-py35_0
-decorator-4.0.10-py35_0
-dill-0.2.5-py35_0
-docutils-0.12-py35_2
-dynd-python-0.7.2-py35_0
-entrypoints-0.2.2-py35_0
-et_xmlfile-1.0.1-py35_0
-fastcache-1.0.2-py35_1
-flask-0.11.1-py35_0
-flask-cors-2.1.2-py35_0
-freetype-2.5.5-vc14_1
-geos-3.5.0-vc14_0
-get_terminal_size-1.0.0-py35_0
-gevent-1.1.1-py35_0
-greenlet-0.4.10-py35_0
-h5py-2.6.0-np111py35_0
-hdf5-1.8.15.1-vc14_4
-heapdict-1.0.0-py35_1
-idna-2.1-py35_0
-imagesize-0.7.1-py35_0
-ipykernel-4.3.1-py35_0
-ipython-4.2.0-py35_0
-ipython_genutils-0.1.0-py35_0
-ipywidgets-4.1.1-py35_0
-itsdangerous-0.24-py35_0
-jdcal-1.2-py35_1
-jedi-0.9.0-py35_1
-jinja2-2.8-py35_1
-jpeg-8d-vc14_0
-jsonschema-2.5.1-py35_0
-jupyter-1.0.0-py35_3
-jupyter_client-4.3.0-py35_0
-jupyter_console-4.1.1-py35_0
-jupyter_core-4.1.0-py35_0
-libdynd-0.7.2-0
-libpng-1.6.22-vc14_0
-libtiff-4.0.6-vc14_2
-llvmlite-0.11.0-py35_0
-locket-0.2.0-py35_1
-lxml-3.6.0-py35_0
-markupsafe-0.23-py35_2
-matplotlib-1.5.1-np111py35_0
-menuinst-1.4.1-py35_0
-mistune-0.7.2-py35_0
-mkl-11.3.3-1
-mkl-service-1.1.2-py35_2
-mpmath-0.19-py35_1
-multipledispatch-0.4.8-py35_0
-nb_anacondacloud-1.1.0-py35_0
-nb_conda-1.1.0-py35_0
-nb_conda_kernels-1.0.3-py35_0
-nbconvert-4.2.0-py35_0
-nbformat-4.0.1-py35_0
-nbpresent-3.0.2-py35_0
-networkx-1.11-py35_0
-nltk-3.2.1-py35_0
-nose-1.3.7-py35_1
-notebook-4.2.1-py35_0
-numba-0.26.0-np111py35_0
-numexpr-2.6.0-np110py35_0
-numpy-1.10.4-py35_2
-odo-0.5.0-py35_1
-openpyxl-2.3.2-py35_0
-openssl-1.0.2h-vc14_0
-pandas-0.18.1-np111py35_0
-partd-0.3.4-py35_0
-path.py-8.2.1-py35_0
-pathlib2-2.1.0-py35_0
-patsy-0.4.1-py35_0
-pep8-1.7.0-py35_0
-pickleshare-0.7.2-py35_0
-pillow-3.4.2-py35_0
-pip-8.1.2-py35_0
-ply-3.8-py35_0
-proj4-4.9.2-vc14_0
-psutil-4.3.0-py35_0
-py-1.4.31-py35_0
-pyasn1-0.1.9-py35_0
-pycosat-0.6.1-py35_1
-pycparser-2.14-py35_1
-pycrypto-2.6.1-py35_4
-pycurl-7.43.0-py35_0
-pyflakes-1.2.3-py35_0
-pygments-2.1.3-py35_0
-pyopenssl-16.2.0-py35_0
-pyparsing-2.1.4-py35_0
-pyproj-1.9.5.1-py35_0
-pyqt-4.11.4-py35_6
-pyreadline-2.1-py35_0
-pysal-1.12.0-py35_0
-pytables-3.2.2-np111py35_4
-pytest-2.9.2-py35_0
-python-3.5.2-0
-python-dateutil-2.5.3-py35_0
-pytz-2016.4-py35_0
-pywin32-220-py35_1
-pyyaml-3.11-py35_4
-pyzmq-15.2.0-py35_0
-qt-4.8.7-vc14_8
-qtconsole-4.2.1-py35_0
-qtpy-1.0.2-py35_0
-requests-2.12.4-py35_0
-rope-0.9.4-py35_1
-ruamel_yaml-0.11.14-py35_0
-scikit-image-0.12.3-np111py35_1
-scikit-learn-0.17.1-np110py35_1
-scipy-0.17.1-np110py35_1
-setuptools-26.1.1-py35_0
-simplegeneric-0.8.1-py35_1
-singledispatch-3.4.0.3-py35_0
-sip-4.16.9-py35_2
-six-1.10.0-py35_0
-snowballstemmer-1.2.1-py35_0
-sockjs-tornado-1.0.3-py35_0
-sphinx-1.4.1-py35_0
-sphinx_rtd_theme-0.1.9-py35_0
-spyder-2.3.9-py35_0
-sqlalchemy-1.0.13-py35_0
-statsmodels-0.6.1-np111py35_1
-sympy-1.0-py35_0
-tk-8.5.18-vc14_0
-toolz-0.8.0-py35_0
-tornado-4.3-py35_1
-traitlets-4.2.1-py35_0
-unicodecsv-0.14.1-py35_0
-vs2015_runtime-14.0.25123-0
-werkzeug-0.11.10-py35_0
-wheel-0.29.0-py35_0
-xlrd-1.0.0-py35_0
-xlsxwriter-0.9.3-py35_0
-xlwings-0.7.2-py35_0
-xlwt-1.1.2-py35_0
-zlib-1.2.8-vc14_3
+defaults::_nb_ext_conf-0.2.0-py35_0
+defaults::alabaster-0.7.8-py35_0
+defaults::anaconda-4.1.1-np111py35_0
+defaults::anaconda-client-1.4.0-py35_0
+defaults::anaconda-navigator-1.2.1-py35_0
+defaults::argcomplete-1.0.0-py35_1
+defaults::astropy-1.2.1-np111py35_0
+defaults::babel-2.3.3-py35_0
+defaults::backports-1.0-py35_0
+defaults::beautifulsoup4-4.4.1-py35_0
+defaults::bitarray-0.8.1-py35_1
+defaults::blaze-0.10.1-py35_0
+defaults::bokeh-0.12.0-py35_0
+defaults::boto-2.40.0-py35_0
+defaults::bottleneck-1.1.0-np111py35_0
+defaults::bzip2-1.0.6-vc14_3
+defaults::cffi-1.6.0-py35_0
+defaults::chest-0.2.3-py35_0
+defaults::click-6.6-py35_0
+defaults::cloudpickle-0.2.1-py35_0
+defaults::clyent-1.2.2-py35_0
+defaults::colorama-0.3.7-py35_0
+defaults::comtypes-1.1.2-py35_0
+defaults::conda-4.3.4-py35_0
+defaults::conda-build-1.21.3-py35_0
+defaults::conda-env-2.6.0-0
+defaults::configobj-5.0.6-py35_0
+defaults::console_shortcut-0.1.1-py35_1
+defaults::contextlib2-0.5.3-py35_0
+defaults::cryptography-1.4-py35_0
+defaults::curl-7.49.0-vc14_0
+defaults::cycler-0.10.0-py35_0
+defaults::cython-0.24-py35_0
+defaults::cytoolz-0.8.0-py35_0
+defaults::dask-0.10.0-py35_0
+defaults::datashape-0.5.2-py35_0
+defaults::decorator-4.0.10-py35_0
+defaults::dill-0.2.5-py35_0
+defaults::docutils-0.12-py35_2
+defaults::dynd-python-0.7.2-py35_0
+defaults::entrypoints-0.2.2-py35_0
+defaults::et_xmlfile-1.0.1-py35_0
+defaults::fastcache-1.0.2-py35_1
+defaults::flask-0.11.1-py35_0
+defaults::flask-cors-2.1.2-py35_0
+defaults::freetype-2.5.5-vc14_1
+defaults::geos-3.5.0-vc14_0
+defaults::get_terminal_size-1.0.0-py35_0
+defaults::gevent-1.1.1-py35_0
+defaults::greenlet-0.4.10-py35_0
+defaults::h5py-2.6.0-np111py35_0
+defaults::hdf5-1.8.15.1-vc14_4
+defaults::heapdict-1.0.0-py35_1
+defaults::idna-2.1-py35_0
+defaults::imagesize-0.7.1-py35_0
+defaults::ipykernel-4.3.1-py35_0
+defaults::ipython-4.2.0-py35_0
+defaults::ipython_genutils-0.1.0-py35_0
+defaults::ipywidgets-4.1.1-py35_0
+defaults::itsdangerous-0.24-py35_0
+defaults::jdcal-1.2-py35_1
+defaults::jedi-0.9.0-py35_1
+defaults::jinja2-2.8-py35_1
+defaults::jpeg-8d-vc14_0
+defaults::jsonschema-2.5.1-py35_0
+defaults::jupyter-1.0.0-py35_3
+defaults::jupyter_client-4.3.0-py35_0
+defaults::jupyter_console-4.1.1-py35_0
+defaults::jupyter_core-4.1.0-py35_0
+defaults::libdynd-0.7.2-0
+defaults::libpng-1.6.22-vc14_0
+defaults::libtiff-4.0.6-vc14_2
+defaults::llvmlite-0.11.0-py35_0
+defaults::locket-0.2.0-py35_1
+defaults::lxml-3.6.0-py35_0
+defaults::markupsafe-0.23-py35_2
+defaults::matplotlib-1.5.1-np111py35_0
+defaults::menuinst-1.4.1-py35_0
+defaults::mistune-0.7.2-py35_0
+defaults::mkl-11.3.3-1
+defaults::mkl-service-1.1.2-py35_2
+defaults::mpmath-0.19-py35_1
+defaults::multipledispatch-0.4.8-py35_0
+defaults::nb_anacondacloud-1.1.0-py35_0
+defaults::nb_conda-1.1.0-py35_0
+defaults::nb_conda_kernels-1.0.3-py35_0
+defaults::nbconvert-4.2.0-py35_0
+defaults::nbformat-4.0.1-py35_0
+defaults::nbpresent-3.0.2-py35_0
+defaults::networkx-1.11-py35_0
+defaults::nltk-3.2.1-py35_0
+defaults::nose-1.3.7-py35_1
+defaults::notebook-4.2.1-py35_0
+defaults::numba-0.26.0-np111py35_0
+defaults::numexpr-2.6.0-np110py35_0
+defaults::numpy-1.10.4-py35_2
+defaults::odo-0.5.0-py35_1
+defaults::openpyxl-2.3.2-py35_0
+defaults::openssl-1.0.2h-vc14_0
+defaults::pandas-0.18.1-np111py35_0
+defaults::partd-0.3.4-py35_0
+defaults::path.py-8.2.1-py35_0
+defaults::pathlib2-2.1.0-py35_0
+defaults::patsy-0.4.1-py35_0
+defaults::pep8-1.7.0-py35_0
+defaults::pickleshare-0.7.2-py35_0
+defaults::pillow-3.4.2-py35_0
+defaults::pip-8.1.2-py35_0
+defaults::ply-3.8-py35_0
+defaults::proj4-4.9.2-vc14_0
+defaults::psutil-4.3.0-py35_0
+defaults::py-1.4.31-py35_0
+defaults::pyasn1-0.1.9-py35_0
+defaults::pycosat-0.6.1-py35_1
+defaults::pycparser-2.14-py35_1
+defaults::pycrypto-2.6.1-py35_4
+defaults::pycurl-7.43.0-py35_0
+defaults::pyflakes-1.2.3-py35_0
+defaults::pygments-2.1.3-py35_0
+defaults::pyopenssl-16.2.0-py35_0
+defaults::pyparsing-2.1.4-py35_0
+defaults::pyproj-1.9.5.1-py35_0
+defaults::pyqt-4.11.4-py35_6
+defaults::pyreadline-2.1-py35_0
+defaults::pysal-1.12.0-py35_0
+defaults::pytables-3.2.2-np111py35_4
+defaults::pytest-2.9.2-py35_0
+defaults::python-3.5.2-0
+defaults::python-dateutil-2.5.3-py35_0
+defaults::pytz-2016.4-py35_0
+defaults::pywin32-220-py35_1
+defaults::pyyaml-3.11-py35_4
+defaults::pyzmq-15.2.0-py35_0
+defaults::qt-4.8.7-vc14_8
+defaults::qtconsole-4.2.1-py35_0
+defaults::qtpy-1.0.2-py35_0
+defaults::requests-2.12.4-py35_0
+defaults::rope-0.9.4-py35_1
+defaults::ruamel_yaml-0.11.14-py35_0
+defaults::scikit-image-0.12.3-np111py35_1
+defaults::scikit-learn-0.17.1-np110py35_1
+defaults::scipy-0.17.1-np110py35_1
+defaults::setuptools-26.1.1-py35_0
+defaults::simplegeneric-0.8.1-py35_1
+defaults::singledispatch-3.4.0.3-py35_0
+defaults::sip-4.16.9-py35_2
+defaults::six-1.10.0-py35_0
+defaults::snowballstemmer-1.2.1-py35_0
+defaults::sockjs-tornado-1.0.3-py35_0
+defaults::sphinx-1.4.1-py35_0
+defaults::sphinx_rtd_theme-0.1.9-py35_0
+defaults::spyder-2.3.9-py35_0
+defaults::sqlalchemy-1.0.13-py35_0
+defaults::statsmodels-0.6.1-np111py35_1
+defaults::sympy-1.0-py35_0
+defaults::tk-8.5.18-vc14_0
+defaults::toolz-0.8.0-py35_0
+defaults::tornado-4.3-py35_1
+defaults::traitlets-4.2.1-py35_0
+defaults::unicodecsv-0.14.1-py35_0
+defaults::vs2015_runtime-14.0.25123-0
+defaults::werkzeug-0.11.10-py35_0
+defaults::wheel-0.29.0-py35_0
+defaults::xlrd-1.0.0-py35_0
+defaults::xlsxwriter-0.9.3-py35_0
+defaults::xlwings-0.7.2-py35_0
+defaults::xlwt-1.1.2-py35_0
+defaults::zlib-1.2.8-vc14_3
==> 2017-01-17 09:19:05 <==
# cmd: C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install pillow
-defaults::jpeg-8d-vc14_0
-defaults::libtiff-4.0.6-vc14_2
-defaults::pillow-3.4.2-py35_0
+defaults::jpeg-9b-vc14_0
+defaults::libtiff-4.0.6-vc14_3
+defaults::pillow-4.0.0-py35_0
# install specs: pillow
==> 2017-01-17 09:21:43 <==
# cmd: C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install -c anaconda pillow=3.4.2
-defaults::conda-4.3.4-py35_0
-defaults::conda-env-2.6.0-0
-defaults::jpeg-9b-vc14_0
-defaults::libtiff-4.0.6-vc14_3
-defaults::pillow-4.0.0-py35_0
+anaconda::conda-4.3.4-py35_0
+anaconda::conda-env-2.6.0-0
+anaconda::jpeg-8d-vc14_2
+anaconda::libtiff-4.0.6-vc14_2
+anaconda::pillow-3.4.2-py35_0
# install specs: pillow 3.4.2*
==> 2017-01-17 11:11:05 <==
# cmd: C:\Users\kellett\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py uninstall cryptography
-defaults::cryptography-1.4-py35_0
# remove specs: cryptography

```

**Comment by kalefranz** [comment]
At this point, the easiest way for you to recover will by to download the latest miniconda installer from [here](http://conda.pydata.org/miniconda.html).  Probably the windows 64-bit python 3.5 installer for you.

Then run it overtop your `C:\Users\kellett\AppData\Local\Continuum\Anaconda3` environment.

**Comment by kalefranz** [comment]
Where did you read about uninstalling `cryptography`? I should probably go review that...

**Comment by amkellett** [comment]
I will try to recreate that train of thought/web page links that led to this.  Should have took better notes.
