### ISSUE TITLE
conda update conda unexpected error

### ISSUE THREAD

**Issue by jcwill23** [conda/conda#4369]
While continuing to investigate this problem:

http://stackoverflow.com/questions/41728718/anaconda-update-for-spyder-has-failed

I tried 

conda install conda 

and that seemed to work. However, the next command 

conda update conda 

did not. The response suggested I post here, so here it is.

Craig

```
C:\WINDOWS\system32>conda install conda
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\My_Stuff\Program_Files\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    idna-2.2                   |           py35_0         124 KB
    pycparser-2.17             |           py35_0         157 KB
    pywin32-220                |           py35_2        12.2 MB
    requests-2.12.4            |           py35_0         791 KB
    ruamel_yaml-0.11.14        |           py35_1         221 KB
    cffi-1.9.1                 |           py35_0         131 KB
    menuinst-1.4.2             |           py35_1         108 KB
    pip-9.0.1                  |           py35_1         1.7 MB
    cryptography-1.7.1         |           py35_0         353 KB
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.5                |           py35_0         536 KB
    ------------------------------------------------------------
                                           Total:        16.4 MB

The following NEW packages will be INSTALLED:

    cffi:           1.9.1-py35_0
    conda:          4.3.5-py35_0
    cryptography:   1.7.1-py35_0
    idna:           2.2-py35_0
    menuinst:       1.4.2-py35_1
    openssl:        1.0.2j-vc14_0  [vc14]
    pip:            9.0.1-py35_1
    pyasn1:         0.1.9-py35_0
    pycosat:        0.6.1-py35_1
    pycparser:      2.17-py35_0
    pyopenssl:      16.2.0-py35_0
    python:         3.5.2-0
    pywin32:        220-py35_2
    requests:       2.12.4-py35_0
    ruamel_yaml:    0.11.14-py35_1
    setuptools:     27.2.0-py35_1
    six:            1.10.0-py35_0
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Proceed ([y]/n)? y

menuinst-1.4.2 100% |###############################| Time: 0:00:00   1.58 MB/s
Fetching packages ...
idna-2.2-py35_ 100% |###############################| Time: 0:00:00   1.66 MB/s
pycparser-2.17 100% |###############################| Time: 0:00:00   1.50 MB/s
pywin32-220-py 100% |###############################| Time: 0:00:01   9.67 MB/s
requests-2.12. 100% |###############################| Time: 0:00:00   4.30 MB/s
ruamel_yaml-0. 100% |###############################| Time: 0:00:00   2.85 MB/s
cffi-1.9.1-py3 100% |###############################| Time: 0:00:00   2.21 MB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:00   6.76 MB/s
cryptography-1 100% |###############################| Time: 0:00:00   3.22 MB/s
pyopenssl-16.2 100% |###############################| Time: 0:00:00   1.43 MB/s
conda-4.3.5-py 100% |###############################| Time: 0:00:00   3.97 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
[      COMPLETE      ]|##################################################| 100%

C:\WINDOWS\system32>conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\cli\common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 14, in <module>
    from .read import get_json_content
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 20, in <module>
    from ...models.channel import Channel
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\models\channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\OpenSSL\rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_NPN_NEGOTIATED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\My_Stuff\Program_Files\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 530, in get_info
    args.func(args, p)
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 142, in execute
    from conda.api import get_index
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\conda\core\index.py", line 15, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\OpenSSL\rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "C:\My_Stuff\Program_Files\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_NPN_NEGOTIATED'
```

**Comment by kalefranz** [comment]
Thanks for the report.  We're confused how this is happening, and looking into this right now.

**Comment by jcwill23** [comment]
YOU are confused!?
I'm stumped.

I can uninstall again if necessary and that may be where I go next.

Craig

**Comment by kalefranz** [comment]
I guess?  But I'm not even sure that will fix it...

**Comment by jcwill23** [comment]
I was using Anaconda 4.2, Spyder 3.0.2, and Python 3.5 for nearly a month
now.
The differences between the directory (Anaconda3) I had and the one I have
now looks like the versions regressed.

I must have done something wrong, but don't know what.
I used the same exe that I downloaded before.
I'm not even sure how to get "clean" so I can install again.

Craig

**Comment by kalefranz** [comment]
Starting a month or two ago, maybe three, we're having a lot of problems with getting the right version of requests into an environment will all the right versions of its dependencies.  Conda relies heavily on requests, and when something is amiss there, it's pretty crippling.  I actually thought we had it figured out, but now this is a new issue.

**Comment by serhanaya** [comment]
I removed anaconda installation since I don't think there is a way out for this now and planning to reinstall today. These things happen Craig, so just chill out. Hope conda team solves this issue quickly.

**Comment by jcwill23** [comment]
I'm trying to uninstall and reinstall today too.

**Comment by jcwill23** [comment]
I have, I believe, successfully installed Anaconda 4.2 64bit Python 3.5 version

I uninstalled the software again using the Windows 10 uninstall from Programs and Features.
I manually removed the Anaconda paths from the user PATH variable.
I manually removed the Anaconda folder from the Startup menu.
I manually removed selected references to Anaconda in the registry.

(I did not see the Anaconda clean program until later - https://docs.continuum.io/anaconda/install)

I rebooted.
I installed from the exe I had downloaded last year (4.2)
This time, I installed for all users, not just me.

Testing 

`conda list

returns many packages. Yeah!

Calling python from a command prompt works too.
Spyder starts and remember my previous project, so that is nice too.

I think I can work again. 
I may need to upgrade some packages, so hopefully that will go well too.

Craig

**Comment by mivade** [comment]
I also saw this problem (on Mac) and was forced to try to reinstall fresh (which means losing all of my environments... unless there's a way to import from a custom location). But running `conda install` with anything seems to always default to wanting to upgrade conda as well. Trying:

```
$ conda install notebook pandas numpy scipy tornado pyzmq
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/depalati/miniconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2017.0.1               |                0       110.8 MB
    appnope-0.1.0              |           py35_0           4 KB
    decorator-4.0.11           |           py35_0          13 KB
    entrypoints-0.2.2          |           py35_0           6 KB
    idna-2.2                   |           py35_0         123 KB
    ipython_genutils-0.1.0     |           py35_0          33 KB
    jsonschema-2.5.1           |           py35_0          57 KB
    markupsafe-0.23            |           py35_2          24 KB
    mistune-0.7.3              |           py35_1         193 KB
    numpy-1.11.3               |           py35_0         3.4 MB
    path.py-10.0               |           py35_0          47 KB
    ptyprocess-0.5.1           |           py35_0          19 KB
    pyasn1-0.1.9               |           py35_0          57 KB
    pycparser-2.17             |           py35_0         156 KB
    pygments-2.1.3             |           py35_0         1.2 MB
    pytz-2016.10               |           py35_0         180 KB
    pyzmq-16.0.2               |           py35_0         618 KB
    requests-2.12.4            |           py35_0         792 KB
    simplegeneric-0.8.1        |           py35_1           7 KB
    six-1.10.0                 |           py35_0          17 KB
    tornado-4.4.2              |           py35_0         589 KB
    wcwidth-0.1.7              |           py35_0          21 KB
    cffi-1.9.1                 |           py35_0         197 KB
    jinja2-2.9.4               |           py35_0         332 KB
    pexpect-4.2.1              |           py35_0          70 KB
    pickleshare-0.7.4          |           py35_0           9 KB
    prompt_toolkit-1.0.9       |           py35_0         325 KB
    python-dateutil-2.6.0      |           py35_0         233 KB
    scipy-0.18.1               |      np111py35_1        13.4 MB
    terminado-0.6              |           py35_0          18 KB
    traitlets-4.3.1            |           py35_0         124 KB
    cryptography-1.7.1         |           py35_0         479 KB
    ipython-5.1.0              |           py35_1         992 KB
    jupyter_core-4.2.1         |           py35_0          53 KB
    pandas-0.19.2              |      np111py35_1         8.3 MB
    jupyter_client-4.4.0       |           py35_0          99 KB
    nbformat-4.2.0             |           py35_0         124 KB
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.5                |           py35_0         487 KB
    ipykernel-4.5.2            |           py35_0         128 KB
    nbconvert-4.2.0            |           py35_0         315 KB
    notebook-4.3.1             |           py35_0         5.3 MB
    ------------------------------------------------------------
                                           Total:       149.3 MB

The following NEW packages will be INSTALLED:

    appnope:          0.1.0-py35_0
    cffi:             1.9.1-py35_0
    cryptography:     1.7.1-py35_0
    decorator:        4.0.11-py35_0
    entrypoints:      0.2.2-py35_0
    idna:             2.2-py35_0
    ipykernel:        4.5.2-py35_0
    ipython:          5.1.0-py35_1
    ipython_genutils: 0.1.0-py35_0
    jinja2:           2.9.4-py35_0
    jsonschema:       2.5.1-py35_0
    jupyter_client:   4.4.0-py35_0
    jupyter_core:     4.2.1-py35_0
    markupsafe:       0.23-py35_2
    mistune:          0.7.3-py35_1
    mkl:              2017.0.1-0
    nbconvert:        4.2.0-py35_0
    nbformat:         4.2.0-py35_0
    notebook:         4.3.1-py35_0
    numpy:            1.11.3-py35_0
    pandas:           0.19.2-np111py35_1
    path.py:          10.0-py35_0
    pexpect:          4.2.1-py35_0
    pickleshare:      0.7.4-py35_0
    prompt_toolkit:   1.0.9-py35_0
    ptyprocess:       0.5.1-py35_0
    pyasn1:           0.1.9-py35_0
    pycparser:        2.17-py35_0
    pygments:         2.1.3-py35_0
    pyopenssl:        16.2.0-py35_0
    python-dateutil:  2.6.0-py35_0
    pytz:             2016.10-py35_0
    pyzmq:            16.0.2-py35_0
    scipy:            0.18.1-np111py35_1
    simplegeneric:    0.8.1-py35_1
    six:              1.10.0-py35_0
    terminado:        0.6-py35_0
    tornado:          4.4.2-py35_0
    traitlets:        4.3.1-py35_0
    wcwidth:          0.1.7-py35_0

The following packages will be UPDATED:

    conda:            4.2.12-py35_0      --> 4.3.5-py35_0
    requests:         2.11.1-py35_0      --> 2.12.4-py35_0

Proceed ([y]/n)?

Fetching packages ...
mkl-2017.0.1-0 100% |####################################################| Time: 0:00:01  79.73 MB/s
appnope-0.1.0- 100% |####################################################| Time: 0:00:00   6.54 MB/s
decorator-4.0. 100% |####################################################| Time: 0:00:00   2.90 MB/s
entrypoints-0. 100% |####################################################| Time: 0:00:00  10.44 MB/s
idna-2.2-py35_ 100% |####################################################| Time: 0:00:00   6.90 MB/s
ipython_genuti 100% |####################################################| Time: 0:00:00   4.87 MB/s
jsonschema-2.5 100% |####################################################| Time: 0:00:00   4.83 MB/s
markupsafe-0.2 100% |####################################################| Time: 0:00:00   3.87 MB/s
mistune-0.7.3- 100% |####################################################| Time: 0:00:00   8.45 MB/s
numpy-1.11.3-p 100% |####################################################| Time: 0:00:00  21.10 MB/s
path.py-10.0-p 100% |####################################################| Time: 0:00:00   4.43 MB/s
ptyprocess-0.5 100% |####################################################| Time: 0:00:00   3.36 MB/s
pyasn1-0.1.9-p 100% |####################################################| Time: 0:00:00   4.76 MB/s
pycparser-2.17 100% |####################################################| Time: 0:00:00   6.71 MB/s
pygments-2.1.3 100% |####################################################| Time: 0:00:00  11.58 MB/s
pytz-2016.10-p 100% |####################################################| Time: 0:00:00   8.66 MB/s
pyzmq-16.0.2-p 100% |####################################################| Time: 0:00:00  12.92 MB/s
requests-2.12. 100% |####################################################| Time: 0:00:00   8.82 MB/s
simplegeneric- 100% |####################################################| Time: 0:00:00  10.91 MB/s
six-1.10.0-py3 100% |####################################################| Time: 0:00:00   3.05 MB/s
tornado-4.4.2- 100% |####################################################| Time: 0:00:00  13.02 MB/s
wcwidth-0.1.7- 100% |####################################################| Time: 0:00:00   3.73 MB/s
cffi-1.9.1-py3 100% |####################################################| Time: 0:00:00   6.73 MB/s
jinja2-2.9.4-p 100% |####################################################| Time: 0:00:00  10.14 MB/s
pexpect-4.2.1- 100% |####################################################| Time: 0:00:00   5.18 MB/s
pickleshare-0. 100% |####################################################| Time: 0:00:00  13.35 MB/s
prompt_toolkit 100% |####################################################| Time: 0:00:00   7.62 MB/s
python-dateuti 100% |####################################################| Time: 0:00:00   7.54 MB/s
scipy-0.18.1-n 100% |####################################################| Time: 0:00:00  33.06 MB/s
terminado-0.6- 100% |####################################################| Time: 0:00:00   3.24 MB/s
traitlets-4.3. 100% |####################################################| Time: 0:00:00   7.05 MB/s
cryptography-1 100% |####################################################| Time: 0:00:00   7.99 MB/s
ipython-5.1.0- 100% |####################################################| Time: 0:00:00  11.09 MB/s
jupyter_core-4 100% |####################################################| Time: 0:00:00   4.64 MB/s
pandas-0.19.2- 100% |####################################################| Time: 0:00:00  25.80 MB/s
jupyter_client 100% |####################################################| Time: 0:00:00   6.05 MB/s
nbformat-4.2.0 100% |####################################################| Time: 0:00:00   6.41 MB/s
pyopenssl-16.2 100% |####################################################| Time: 0:00:00   5.19 MB/s
conda-4.3.5-py 100% |####################################################| Time: 0:00:00  12.90 MB/s
ipykernel-4.5. 100% |####################################################| Time: 0:00:00   6.58 MB/s
nbconvert-4.2. 100% |####################################################| Time: 0:00:00   7.12 MB/s
notebook-4.3.1 100% |####################################################| Time: 0:00:00  21.64 MB/s
Extracting packages ...
[      COMPLETE      ]|#######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|#######################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#######################################################################| 100%
```

This looks like it completed successfully. However, running simply `conda`:

```
$ conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/depalati/miniconda3  (writable)
    default environment : /Users/depalati/miniconda3
       envs directories : /Users/depalati/miniconda3/envs
          package cache : /Users/depalati/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 508:20



`$ /Users/depalati/miniconda3/bin/conda`




    Traceback (most recent call last):
      File "/Users/depalati/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/depalati/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 90, in _main
        args.append('-h')
    AttributeError: 'tuple' object has no attribute 'append'
```

The good news is that actual commands seem to work, at least.

**Comment by timothegenzmer** [comment]
Same thing happend to my after installing pymc.
Simply running conda results in the error seen in the first post.

If it shoud be helpful I can add the stacktrace

**Comment by kalefranz** [comment]
Fixed in 4.3.6 out now.

**Comment by jcwill23** [comment]
Is that just

conda update conda

??

Craig

**Comment by mivade** [comment]
@kalefranz thanks for the quick turnaround!

**Comment by serhanaya** [comment]
This problem is solved for me after removing and then reinstalling anaconda (4.2) and then updating conda to 4.3.6.

**Comment by jcwill23** [comment]
Anaconda 4.2, conda 4.3.6 spyder 3.1.0
things are back on track again.

Thanks!

Craig

**Comment by nateGeorge** [comment]
Yeah, so how can I uninstall conda on Ubuntu if I can't run any conda commands?


```bash
conda uninstall conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 84, in _main
    from ..base.context import context
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.disk import try_write, conda_bld_ensure_dir
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/common/disk.py", line 16, in <module>
    from ..utils import on_win
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/utils.py", line 11, in <module>
    from .common.url import path_to_url
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/common/url.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import LocationParseError
  File "/home/nate/anaconda3/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/nate/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/nate/anaconda3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/nate/anaconda3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/nate/anaconda3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_RSA_OAEP_MD'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nate/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 156, in execute
    from conda.api import get_index
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/api.py", line 7, in <module>
    from .fetch import fetch_index
  File "/home/nate/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 12, in <module>
    import requests
  File "/home/nate/anaconda3/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/nate/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/nate/anaconda3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/nate/anaconda3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/nate/anaconda3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/nate/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_RSA_OAEP_MD'

```

**Comment by kalefranz** [comment]
Uninstall conda isn't the same thing as uninstall Anaconda (i.e. anaconda-clean).  `rm -rf` for the most part works just fine for conda.  But Anaconda is several hundred packages of open source software, all with their own independent code, and all individually choosing where they want to store files.  Many use appdirs, but many follow their own individual conventions.  For that matter, conda only manages the files it installs itself, not new files that get made from the execution of those installed files.

**Comment by kalefranz** [comment]
Also, why `sudo rm -rf ~/anaconda3/`?  You shouldn't ever (have to) use `sudo` for anything under `$HOME`.   Unless you've used it once in the past though, at which point you basically have to use `sudo` at every point in the future, until you `chown` back to the correct ownership.
