### ISSUE TITLE
Cannot install noarch_python packages

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#4372]
I am trying to install a noarch_python package but it fails with conda 4.3.5.

```
$ conda create -q -y -n noarch_test python=2.7                                                                                                                        
Fetching package metadata .........
Solving package specifications: .
...
$ source activate noarch_test
$ conda install -c jjhelmus_testing imagesize
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/jhelmus/anaconda/envs/noarch_test:

The following NEW packages will be INSTALLED:

    imagesize: 0.7.1-py_99 jjhelmus_testing

Proceed ([y]/n)? y

imagesize-0.7. 100% |##############################################################################################################################################| Time: 0:00:00   4.62 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /home/jhelmus/anaconda  (writable)
    default environment : /home/jhelmus/anaconda/envs/noarch_test
       envs directories : /home/jhelmus/anaconda/envs
          package cache : /home/jhelmus/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/jjhelmus_testing/linux-64
                          https://conda.anaconda.org/jjhelmus_testing/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jhelmus/.condarc
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Linux/4.4.0-59-generic debian/stretch/sid glibc/2.23
                UID:GID : 5001:1004



`$ /home/jhelmus/anaconda/envs/noarch_test/bin/conda install -c jjhelmus_testing imagesize`


    Traceback (most recent call last):
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for _path cannot be None.
```

From what I've been able to figure out the issue is that the `paths.json` file in the package contains nulls:

``` json
{
  "paths": [
    {
      "_path": null,
      "path_type": "hardlink",
      "sha256": "38283961cd876d6d550be0ebde4c8c1f97bed7323c08536281536f22bd6249e8",
      "size_in_bytes": 69
    },
    {
      "_path": null,
      "path_type": "hardlink",
      "sha256": "6b9d2631de6dfe793101215ab57225ffdca96e7f86d2811e0cb81ccba41cb8dc",
      "size_in_bytes": 63
    },
...
```

From what I've seen in the conda-build source this seems to be the [expected behavior](https://github.com/conda/conda-build/blob/9395a482df893ec6966226c257ab91c2840f47c2/conda_build/build.py#L522-L523) for `noarch_python` packages.  

The example package is available in the [jjhelmus_testing channel](https://anaconda.org/jjhelmus_testing/imagesize/files).

This package was created with conda build 2.1.1 using the following recipe:

``` yaml 
package:
  name: imagesize
  version: 0.7.1

source:
  fn: imagesize-0.7.1.tar.gz
  url: https://pypi.io/packages/source/i/imagesize/imagesize-0.7.1.tar.gz
  sha256: 0ab2c62b87987e3252f89d30b7cedbec12a01af9274af9ffa48108f2c13c6062

build:
  number: 99
  noarch_python: True
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
```

**Comment by kalefranz** [comment]
There's a conda-build PR that fixes this. I think Mike will merge soon.

**Comment by jjhelmus** [comment]
I'm guessing that conda/conda-build#1673 will fix this.  Thanks for the update @kalefranz.

**Comment by kalefranz** [comment]
Yup that's the one!

**Comment by kalefranz** [comment]
conda-build 2.1.2 has been released.  Unfortunately, you'll have to rebuild `python_noarch` packages built with conda-build 2.1.0 or 2.1.1.  When you rebuild though, consider trying out the *new* python noarch package type.  You'll need conda >=4.3 to install them, but in your meta.yaml build file, just replace

    build:
      noarch_python: true

with

    build:
      noarch: python

**Comment by jjhelmus** [comment]
I've installed conda-build 1.2.2 and conda 4.3.7 and create a noarch package using the `noarch: python` setting but the resulting package is still not installable:

```
$ conda install -c jjhelmus_testing imagesize=0.7.1=py_60
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/jhelmus/anaconda/envs/noatch_test:

The following NEW packages will be INSTALLED:

    imagesize: 0.7.1-py_60 jjhelmus_testing

Proceed ([y]/n)? y

imagesize-0.7. 100% |####################################################################################| Time: 0:00:00   4.38 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 2.1.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/jhelmus/anaconda  (writable)
    default environment : /Users/jhelmus/anaconda/envs/noatch_test
       envs directories : /Users/jhelmus/anaconda/envs
          package cache : /Users/jhelmus/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/jjhelmus_testing/osx-64
                          https://conda.anaconda.org/jjhelmus_testing/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /Users/jhelmus/.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/3.5.2 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 1078999241:660979062



`$ /Users/jhelmus/anaconda/envs/noatch_test/bin/conda install -c jjhelmus_testing imagesize=0.7.1=py_60`




    Traceback (most recent call last):
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 403, in __get__
        val = instance.__dict__[self.name]
    KeyError: 'entry_points'

    During handling of the above exception, another exception occurred:



    Traceback (most recent call last):
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 255, in execute
        self.verify()
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 238, in verify
        self.prepare()
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 169, in prepare
        concatv(unlink_actions, link_actions))
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 168, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 165, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 394, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "/Users/jhelmus/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set
```

meta.yaml file for the recipe is:

``` yaml
package:
  name: imagesize
  version: 0.7.1

source:
  fn: imagesize-0.7.1.tar.gz
  url: https://pypi.io/packages/source/i/imagesize/imagesize-0.7.1.tar.gz
  sha256: 0ab2c62b87987e3252f89d30b7cedbec12a01af9274af9ffa48108f2c13c6062

build:
  number: 60
  noarch: python
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
```

**Comment by frol** [comment]
@kalefranz This issue is not resolved! I have built my `noarch: python` package with Conda Build 2.1.3 and now I am trying to install it with Conda 4.3.9, but it crashes just like in @jjhelmus's case!

**Comment by frol** [comment]
@conda Are there any plans on getting Conda **stable** (for real) any time in the future? I have never used a software which fails on every single release (I have been using Conda for almost 2 years now and while Conda has some benefits, it has always been a headache to maintain my packages)

**Comment by frol** [comment]
Conda 4.3.10 from `conda-canary` channel seems to have the fix for `A value for entry_points has not been set`.
