### ISSUE TITLE
conda-build-2.1.1 / conda-4.3.5. fails with Permission denied: '/opt/anaconda/locks'

### ISSUE THREAD

**Issue by itldo** [conda/conda#4379]
I just upgraded to the latest conda build and conda 4.3 but now my 'conda build' fails attempting
to create a missing 'locks' directory in the system conda directory.
Should I have expected this directory to already exist?
Or can I build only within my own environment? 

Thanks
-tim

```
$ conda build .
BUILD START:
...
number of files: 1
Fixing permissions
...
Fixing permissions
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 321, in main
    execute(sys.argv[1:])
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 312, in execute
    noverify=args.no_verify)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/api.py", line 89, in build
    need_source_download=need_source_download, config=config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1460, in build_tree
    config=config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 1116, in build
    built_package = bundlers[output.get('type', 'conda')](output, m, config, env)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 811, in bundle_conda
    info_files = create_info_files(tmp_metadata, files, config=config, prefix=config.build_prefix)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 485, in create_info_files
    copy_recipe(m, config)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/build.py", line 203, in copy_recipe
    utils.copy_into(src_path, dst_path, timeout=config.timeout, locking=config.locking)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 140, in copy_into
    lock = get_lock(src_folder, timeout=timeout)
  File "/opt/anaconda/lib/python2.7/site-packages/conda_build/utils.py", line 257, in get_lock
    os.makedirs(locks_dir)
  File "/opt/anaconda/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/opt/anaconda/locks'
```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1682
