### ISSUE TITLE
Cannot install package when the folder contains non-ascii characters

### ISSUE THREAD

**Issue by WhyINeedToFillUsername** [conda/conda#4380]
My Windows username is Antonín and the "í" is causing problems. I created a hardlink and installed Julia to ascii-only path, but the installation is taking the path with "í" anyway. It says `UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)`. The whole output:

```
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.5.0 (2016-09-19 18:14 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-w64-mingw32

julia> Pkg.add("IJulia")
INFO: Installing BinDeps v0.4.5
INFO: Installing BufferedStreams v0.2.3
INFO: Installing Compat v0.13.0
INFO: Installing Conda v0.4.0
INFO: Installing IJulia v1.3.3
INFO: Installing JSON v0.8.1
INFO: Installing LegacyStrings v0.2.0
INFO: Installing LibExpat v0.2.3
INFO: Installing Libz v0.2.2
INFO: Installing Nettle v0.2.4
INFO: Installing SHA v0.3.0
INFO: Installing URIParser v0.1.7
INFO: Installing WinRPM v0.2.2
INFO: Installing ZMQ v0.4.0
INFO: Building Conda
INFO: Building WinRPM
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:32
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:198
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:198
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:202
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:206
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:206
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:206
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:206
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:206
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:206
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:209
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:209
WARNING: Method definition (::Type{WinRPM.Packages})(#T<:Union{Array{LibExpat.ETree, 1}, Base.Set{Li
bExpat.ETree}}) in module WinRPM at C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:207 overwritte
n at C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:209.
WARNING: LibExpat.ParsedData is deprecated, use LibExpat.ETree instead.
  likely near C:\Users\Antonín\.julia\v0.5\WinRPM\src\WinRPM.jl:317
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/min
gw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/min
gw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building Nettle
INFO: Updating WinRPM package list
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/min
gw:/win32/openSUSE_13.2/repodata/repomd.xml
INFO: Downloading https://cache.julialang.org/http://download.opensuse.org/repositories/windows:/min
gw:/win64/openSUSE_13.2/repodata/repomd.xml
INFO: Building ZMQ
INFO: Building IJulia
INFO: Installing Jupyter via the Conda package.
Fetching package metadata: ....
Solving package specifications: .........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 139,
in main
    args_func(args, p)
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 146,
in args_func
    args.func(args, p)
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\main_install.py", li
ne 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\cli\install.py", line 33
4, in install
    update_deps=args.update_deps)
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\plan.py", line 440, in i
nstall_actions
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\plan.py", line 248, in e
nsure_linked_actions
    if install.is_linked(prefix, dist):
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\site-packages\conda\install.py", line 537, i
n is_linked
    meta_path = join(prefix, 'conda-meta', dist + '.json')
  File "C:\Users\AntonÝn\.julia\v0.5\Conda\deps\usr\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)
INFO: Package database updated
```

**Comment by mingwandroid** [comment]
> I created a hardlink and installed Julia to ascii-only path, but the installation is taking the path with "í" anyway.

It seems you have permissions to create a hardlink somewhere ascii-only which is good. I'm afraid your best course of action is to create a normal folder instead and install Julia into that. We can't do anything about the poor Unicode support in Python 2 on Windows.

**Comment by WhyINeedToFillUsername** [comment]
Installing it to non-ascii folder does not help. The problem occurs when I
try to add the package via Pkg.add("IJulia").
I even tried changing my Windows registry settings for user folder to use
the ascii version. Does the tool use Git internally? Maybe the Git
installation still has reference to the non-ascii version, which might
cause problem.

**Comment by mingwandroid** [comment]
I don't know anything about Julia, sorry. Perhaps ask that team?

**Comment by WhyINeedToFillUsername** [comment]
Sorry, I don't know if it's an issue of Julia, Conda or what. I followed
the instructions in the error.

I had to eventually change my user folder in windows to be a ascii only
(achievable in registry, see
http://programmaticallyspeaking.com/changing-the-user-profile-path-in-windows-7.html),
uninstall, delete .julia folder and reinstall.
