### ISSUE TITLE
condo update numpy unexpected error 

### ISSUE THREAD

**Issue by SARARANJBAR** [conda/conda#4384]
Current conda install:

               platform : osx-64
          conda version : 4.3.6
       conda is private : False
      conda-env version : 4.3.6
    conda-build version : 1.15.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/sara/anaconda  (writable)
    default environment : /Users/sara/anaconda
       envs directories : /Users/sara/anaconda/envs
          package cache : /Users/sara/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.6 requests/2.12.4 CPython/2.7.13 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 504:20

`$ /Users/sara/anaconda/bin/conda update numpy`

    Traceback (most recent call last):
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/plan.py", line 835, in execute_actions
        plan = plan_from_actions(actions, index)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/plan.py", line 369, in plan_from_actions
        plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/plan.py", line 331, in inject_UNLINKLINKTRANSACTION
        pfe.prepare()
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 443, in prepare
        for dist in self.link_dists)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 443, in <genexpr>
        for dist in self.link_dists)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 379, in make_actions_for_dist
        key=lambda pce: pce and pce.is_fetched and pce.tarball_matches_md5_if(md5)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 88, in first
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 88, in <genexpr>
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 379, in <lambda>
        key=lambda pce: pce and pce.is_fetched and pce.tarball_matches_md5_if(md5)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 103, in tarball_matches_md5_if
        return not md5sum or self.md5sum == md5sum
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 111, in md5sum
        return self._calculate_md5sum() if self.is_fetched else None
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 137, in _wrapper
        result = method(self, *args, **kwargs)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 119, in _calculate_md5sum
        return md5_file(self.package_tarball_full_path)
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/utils.py", line 106, in md5_file
        return hashsum_file(path, 'md5')
      File "/Users/sara/anaconda/lib/python2.7/site-packages/conda/utils.py", line 96, in hashsum_file
        with open(path, 'rb') as fi:
    IOError: [Errno 13] Permission denied: u'/Users/sara/anaconda/pkgs/mkl-2017.0.1-0.tar.bz2'

**Comment by kalefranz** [comment]
What is the output of `ls -al /Users/sara/anaconda/pkgs`?
