### ISSUE TITLE
SSL verification error when fetching package metadata

### ISSUE THREAD

**Issue by costasva** [conda/conda#4389]
Anaconda is throwing an SSL error when fetching package metadata and following operations fail. This also happens updating or installing packages. The repository (https://repo.continuum.io/pkgs/free/win-64/) is accessible from that system through a browser.

`conda create --name py27 python=2.7
Fetching package metadata ...SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
......
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda3\envs\py27:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    vs2008_runtime-9.00.30729.1|                2         1.0 MB
    python-2.7.12              |                0        23.5 MB
    setuptools-27.2.0          |           py27_1         755 KB
    wheel-0.29.0               |           py27_0         121 KB
    pip-8.1.2                  |           py27_0         1.5 MB
    ------------------------------------------------------------
                                           Total:        26.9 MB

The following NEW packages will be INSTALLED:

    pip:            8.1.2-py27_0
    python:         2.7.12-0
    setuptools:     27.2.0-py27_1
    vs2008_runtime: 9.00.30729.1-2
    wheel:          0.29.0-py27_0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/vs2008_runtime-9.00.30729.1-2.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\e092220\.condarc
           offline mode : False

`$ C:\Anaconda3\Scripts\conda-script.py create --name py27 python=2.7`

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir)
    FileNotFoundError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request

        self._validate_conn(conn)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 297, in ssl_wrap_socket
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 377, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\adapters.py", line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 403, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/win-64/vs2008_runtime-9.00.30729.1-2.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/win-64/vs2008_runtime-9.00.30729.1-2.tar.bz2`

**Comment by kalefranz** [comment]
I would start with `conda update conda`.  And then file a new issue if you still have problems :)
