### ISSUE TITLE
Unable to install Jupyter notebook extensions from conda-forge

### ISSUE THREAD

**Issue by cluoren** [conda/conda#4396]
CLUO-MBP-2:~ cluo$ conda install -c conda-forge jupyter_contrib_nbextensions
Fetching package metadata .......An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.14
       conda is private : False
      conda-env version : 4.2.14
    conda-build version : 2.1.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/cluo/anaconda  (writable)
    default environment : /Users/cluo/anaconda
       envs directories : /Users/cluo/anaconda/envs
          package cache : /Users/cluo/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/cluo/.condarc
           offline mode : False

`$ /Users/cluo/anaconda/bin/conda install -c conda-forge jupyter_contrib_nbextensions`

    Traceback (most recent call last):
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 361, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Users/cluo/anaconda/lib/python2.7/httplib.py", line 1042, in request
        self._send_request(method, url, body, headers)
      File "/Users/cluo/anaconda/lib/python2.7/httplib.py", line 1082, in _send_request
        self.endheaders(body)
      File "/Users/cluo/anaconda/lib/python2.7/httplib.py", line 1038, in endheaders
        self._send_output(message_body)
      File "/Users/cluo/anaconda/lib/python2.7/httplib.py", line 882, in _send_output
        self.send(msg)
      File "/Users/cluo/anaconda/lib/python2.7/httplib.py", line 858, in send
        self.sock.sendall(data)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 292, in sendall
        sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 281, in _send_until_done
        return self.connection.send(data)
      File "/Users/cluo/anaconda/lib/python2.7/site-packages/OpenSSL/SSL.py", line 947, in send
        raise TypeError("data must be a byte string")
    TypeError: data must be a byte string

**Comment by cluoren** [comment]
"anaconda logout" solved my problem. I guess it could be an anaconda cloud issue?

**Comment by kalefranz** [comment]
I honestly don't know what caused this.  I also don't see how `anaconda logout` could have helped, given the stack trace and what `conda info` reported for you.

Please let us know if you run into this again!
