### ISSUE TITLE
conda install error 'ValidationError: hard is not a valid LinkType'

### ISSUE THREAD

**Issue by pya** [conda/conda#4398]
This command:

    conda install numpy

causes this error:

```

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.6
       conda is private : False
      conda-env version : 4.3.6
    conda-build version : 1.21.5
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/mike/anaconda  (writable)
    default environment : /Users/mike/anaconda
       envs directories : /Users/mike/anaconda/envs
          package cache : /Users/mike/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/hydrocomputing/osx-64
                          https://conda.anaconda.org/hydrocomputing/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/Esri/osx-64
                          https://conda.anaconda.org/Esri/noarch
            config file : /Users/mike/.condarc
           offline mode : False
             user-agent : conda/4.3.6 requests/2.12.4 CPython/2.7.13 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20



`$ /Users/mike/anaconda/bin/conda install numpy`




    Traceback (most recent call last):
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 136, in install
        linked_dists = install_linked(prefix)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 121, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 113, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 66, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 831, in __setattr__
        super(ImmutableEntity, self).__setattr__(attribute, value)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 658, in box
        return val if isinstance(val, self._type) else self._type(**val)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/models/index_record.py", line 15, in box
        return super(LinkTypeField, self).box(instance, val)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 557, in box
        raise ValidationError(val, msg=e1)
    ValidationError: hard is not a valid LinkType
```

It worked for several years. I am using many environments for different Python version. One of the last updates must have broken it. I cannot tell exactly which one.

**Comment by pya** [comment]
This is my clunky fix in `Users/mike/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py` starting at line 545:

    def box(self, instance, val):
        if val is None:
            # let the required/nullable logic handle validation for this case
            return None
        try:
            # try to box using val as an Enum name
            return val if isinstance(val, self._type) else self._type(val)
        except ValueError as e1:
            try:
                if val == 'hard':
                    val = 'hardlink'
                # try to box using val as an Enum value
                return self._type[val]
            except KeyError:
                raise ValidationError(val, msg=e1)

**Comment by kalefranz** [comment]
Can you run again with `-v -v -v` (and without your fix)? I'd like to figure out where the bad package is.

**Comment by kalefranz** [comment]
I've hacked a fix with https://github.com/conda/conda/pull/4409, but you have a bad package in your environment somewhere.

**Comment by pya** [comment]
Sorry for the delayed response.  Thanks for quick fixing.

Running with `-v - v -v` yields essentially the same result.
The `INFO` lines are extra.

```


conda install -v -v -v numpy
DEBUG conda.cli.main:_main(135): verbosity set to 3
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
INFO conda.common.io:captured(65): stderr and stdout yielding bac
```
> but you have a bad package in your environment somewhere.

How can I find out which of the many packages I've got installed  is bad and causes this problem?

**Comment by kalefranz** [comment]
Show me the output of

    grep -E 'hard\"' /Users/mike/anaconda/conda-meta/*

it *should* list at least one file for you.  If it does, give me the output of 

    cat /Users/mike/anaconda/conda-meta/FILE_FROM_GREP_COMMAND.json

**Comment by pya** [comment]
There are bunch of them:

```
 grep -E 'hard\"' /Users/mike/anaconda/conda-meta/*
/Users/mike/anaconda/conda-meta/anaconda-1.7.0-np17py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/astropy-0.2.4-np17py27_1.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/atom-0.3.2-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/binstar-0.3.1-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/boto-2.12.0-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/chaco-4.3.0-np17py27_1.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/cubes-0.10.2-py27_3.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/dynd-python-0.4.2-np17py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/enable-4.3.0-np17py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/enaml-0.7.19-py27_2.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/flask-0.10.1-py27_1.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/h5py-2.2.0-np17py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/ipython-qtconsole-1.0.0-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/keyring-3.0.1-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/launcher-0.1.2-py27_1.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/libdynd-0.4.2-0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/mayavi-4.3.0-np17py27_1.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/netcdf4-1.0.5-np17py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/networkx-1.8.1-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/patsy-0.2.1-np17py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/pyflakes-0.7.3-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/pysal-1.6.0-np17py27_1.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/spyder-app-2.2.4-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/sqlalchemy-0.8.2-py27_0.json:    "type": "hard"
/Users/mike/anaconda/conda-meta/statsmodels-0.5.0-np17py27_0.json:    "type": "hard"
```
Content of the first:

```
cat /Users/mike/anaconda/conda-meta/anaconda-1.7.0-np17py27_0.json
{
  "arch": "x86_64", 
  "build": "np17py27_0", 
  "build_number": 0, 
  "files": [
    "lib/python2.7/version.txt"
  ], 
  "link": {
    "source": "/Users/mike/anaconda/pkgs/anaconda-1.7.0-np17py27_0", 
    "type": "hard"
  }, 
  "name": "anaconda", 
  "platform": "osx", 
  "requires": [
    "_license 1.1 py27_0", 
    "apptools 4.2.0 py27_0", 
    "astropy 0.2.4 np17py27_1", 
    "atom 0.3.2 py27_0", 
    "binstar 0.3.1 py27_0", 
    "biopython 1.61 np17py27_0", 
    "bitarray 0.8.1 py27_0", 
    "bokeh 0.1.1 np17py27_0", 
    "boto 2.12.0 py27_0", 
    "casuarius 1.1 py27_0", 
    "chaco 4.3.0 np17py27_1", 
    "configobj 4.7.2 py27_0", 
    "cubes 0.10.2 py27_3", 
    "curl 7.30.0 1", 
    "cython 0.19.1 py27_0", 
    "dateutil 2.1 py27_2", 
    "distribute 0.6.45 py27_0", 
    "docutils 0.11 py27_0", 
    "dynd-python 0.4.2 np17py27_0", 
    "enable 4.3.0 np17py27_0", 
    "enaml 0.7.19 py27_2", 
    "envisage 4.3.0 py27_0", 
    "flask 0.10.1 py27_1", 
    "freetype 2.4.10 1", 
    "gevent 0.13.8 py27_0", 
    "gevent-websocket 0.3.6 py27_2", 
    "gevent_zeromq 0.2.5 py27_2", 
    "greenlet 0.4.1 py27_0", 
    "grin 1.2.1 py27_1", 
    "h5py 2.2.0 np17py27_0", 
    "hdf5 1.8.9 1", 
    "imaging 1.1.7 py27_2", 
    "ipython 1.0.0 py27_0", 
    "ipython-notebook 1.0.0 py27_0", 
    "ipython-qtconsole 1.0.0 py27_0", 
    "itsdangerous 0.23 py27_0", 
    "jinja2 2.7.1 py27_0", 
    "jpeg 8d 1", 
    "keyring 3.0.1 py27_0", 
    "launcher 0.1.2 py27_1", 
    "libdynd 0.4.2 0", 
    "libevent 2.0.20 1", 
    "libnetcdf 4.2.1.1 1", 
    "libpng 1.5.13 1", 
    "libtiff 4.0.2 0", 
    "libxml2 2.9.0 1", 
    "libxslt 1.1.28 1", 
    "llvm 3.3 0", 
    "llvmmath 0.1.1 np17py27_2", 
    "llvmpy 0.12.0 py27_0", 
    "lxml 3.2.3 py27_0", 
    "markupsafe 0.18 py27_0", 
    "matplotlib 1.3.0 np17py27_0", 
    "mayavi 4.3.0 np17py27_1", 
    "mdp 3.3 np17py27_0", 
    "meta 0.4.2.dev py27_0", 
    "netcdf4 1.0.5 np17py27_0", 
    "networkx 1.8.1 py27_0", 
    "nltk 2.0.4 np17py27_0", 
    "nose 1.3.0 py27_0", 
    "numba 0.10.2 np17py27_0", 
    "numexpr 2.0.1 np17py27_3", 
    "numpy 1.7.1 py27_0", 
    "pandas 0.12.0 np17py27_0", 
    "patsy 0.2.1 np17py27_0", 
    "pep8 1.4.6 py27_0", 
    "pip 1.4.1 py27_0", 
    "ply 3.4 py27_0", 
    "psutil 1.0.1 py27_0", 
    "py 1.4.14 py27_0", 
    "pyaudio 0.2.7 py27_0", 
    "pycosat 0.6.0 py27_0", 
    "pycparser 2.9.1 py27_0", 
    "pycrypto 2.6 py27_0", 
    "pycurl 7.19.0 py27_2", 
    "pyface 4.3.0 py27_0", 
    "pyflakes 0.7.3 py27_0", 
    "pygments 1.6 py27_0", 
    "pyparsing 1.5.6 py27_0", 
    "pysal 1.6.0 np17py27_1", 
    "pysam 0.6 py27_0", 
    "pyside 1.1.2 py27_1", 
    "pytables 2.4.0 np17py27_0", 
    "pytest 2.3.5 py27_0", 
    "python 2.7.5 2", 
    "python.app 1.2 py27_1", 
    "pytz 2013b py27_0", 
    "pyyaml 3.10 py27_0", 
    "pyzmq 2.2.0.1 py27_1", 
    "qt 4.7.4 0", 
    "readline 6.2 1", 
    "redis 2.6.9 0", 
    "redis-py 2.7.2 py27_0", 
    "requests 1.2.3 py27_0", 
    "rope 0.9.4 py27_0", 
    "scikit-image 0.8.2 np17py27_2", 
    "scikit-learn 0.14.1 np17py27_0", 
    "scipy 0.12.0 np17py27_0", 
    "shiboken 1.1.2 py27_0", 
    "six 1.4.1 py27_0", 
    "sphinx 1.1.3 py27_4", 
    "spyder 2.2.4 py27_0", 
    "spyder-app 2.2.4 py27_0", 
    "sqlalchemy 0.8.2 py27_0", 
    "sqlite 3.7.13 1", 
    "statsmodels 0.5.0 np17py27_0", 
    "sympy 0.7.3 py27_0", 
    "tk 8.5.13 1", 
    "tornado 3.1.1 py27_0", 
    "traits 4.3.0 py27_0", 
    "traitsui 4.3.0 py27_0", 
    "vtk 5.10.1 py27_0", 
    "werkzeug 0.9.4 py27_0", 
    "xlrd 0.9.2 py27_0", 
    "xlwt 0.7.5 py27_0", 
    "yaml 0.1.4 1", 
    "zeromq 2.2.0 1", 
    "zlib 1.2.7 1"
  ], 
  "version": "1.7.0"
}
```

**Comment by kalefranz** [comment]
Until we get the next version released, I think this will fix your environment for you

    sed -i '' -E 's|hard\"|hard-link\"|' /Users/mike/anaconda/conda-meta/*
