### ISSUE TITLE
SSL verification error at update

### ISSUE THREAD

**Issue by costasva** [conda/conda#4399]
Any update or install produces an SSL verification error like below and then fails with an unexpected error. After suggestion in [#4389](4389) I tried to update conda itself with a new Anaconda install, but that still fails.

$ conda update conda
Fetching package metadata ...SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
SSL verification error: [Errno 2] No such file or directory
.SSL verification error: [Errno 2] No such file or directory
.....
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
          package cache : C:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\e092220\.condarc
           offline mode : False

`$ C:\Anaconda3\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 295, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir)
    FileNotFoundError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 352, in _make_request

        self._validate_conn(conn)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "C:\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 297, in ssl_wrap_socket
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 377, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Anaconda3\lib\site-packages\requests\adapters.py", line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: [Errno 2] No such file or directory

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 403, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: [Errno 2] No such file or directory: https://repo.continuum.io/pkgs/free/win-64/conda-env-2.6.0-0.tar.bz2

**Comment by kalefranz** [comment]
Installing miniconda overtop of your current env will probably fix this, or

    conda config --set ssl_verify false
    conda update conda
    conda config --remove-key ssl_verify

**Comment by kalefranz** [comment]
Please let me know if that doesn't fix the problem for you.

**Comment by costasva** [comment]
The conda config route did not fix it. However, it looks like something else might be broken. After config --set and config --remove-key, running config --show produces the same ssl_verify values. It doesn't look like the config command is changing anything.

$ conda config --show                                  
add_anaconda_token: True                               
add_pip_as_python_dependency: True                     
allow_softlinks: True                                  
always_copy: False                                     
always_yes: False                                      
auto_update_conda: True                                
binstar_upload: None                                   
changeps1: True                                        
channel_alias: https://conda.anaconda.org/             
channel_priority: True                                 
channels:                                              
  - defaults                                           
client_cert:                                           
client_cert_key:                                       
create_default_packages: []                            
debug: False                                           
default_channels:                                      
  - https://repo.continuum.io/pkgs/free                
  - https://repo.continuum.io/pkgs/pro                 
  - https://repo.continuum.io/pkgs/msys2               
disallow: []                                           
json: False                                            
offline: False                                         
proxy_servers: {}                                      
quiet: False                                           
shortcuts: True                                        
show_channel_urls: None                                
ssl_verify: false conda update pyopenssl               
track_features: []                                     
update_dependencies: True                              
use_pip: True                                          
verbosity: 0
