### ISSUE TITLE
Unexpected error while installing opencv3

### ISSUE THREAD

**Issue by OliverPark** [conda/conda#4400]
When I install opencv3, I got an error below. 

This is what I did. 

```
chanhopark $ conda install -c menpo opencv3=3.1.0
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/chanhopark/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    tbb-4.3_20141023           |                0         1.6 MB  menpo
    requests-2.12.4            |           py35_0         792 KB
    opencv3-3.1.0              |           py35_0        37.3 MB  menpo
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.7                |           py35_0         489 KB
    ------------------------------------------------------------
                                           Total:        40.2 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0             
    opencv3:   3.1.0-py35_0   menpo
    tbb:       4.3_20141023-0 menpo

The following packages will be UPDATED:

    conda:     4.2.9-py35_0         --> 4.3.7-py35_0 
    pyopenssl: 16.0.0-py35_0        --> 16.2.0-py35_0
    requests:  2.11.1-py35_0        --> 2.12.4-py35_0

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |#####################################################################################################################################| Time: 0:00:00 694.81 kB/s
tbb-4.3_201410 100% |#####################################################################################################################################| Time: 0:01:03  25.70 kB/s
requests-2.12. 100% |#####################################################################################################################################| Time: 0:00:00   6.29 MB/s
An unexpected error has occurred.####################################                                                                                     | Time: 0:11:52  20.11 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
```

Here is the error message. 
```
Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/chanhopark/anaconda  (writable)
    default environment : /Users/chanhopark/anaconda
       envs directories : /Users/chanhopark/anaconda/envs
          package cache : /Users/chanhopark/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False



`$ /Users/chanhopark/anaconda/bin/conda install -c menpo opencv3=3.1.0`




    Traceback (most recent call last):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 232, in _error_catcher
        yield
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 314, in read
        data = self._fp.read(amt)
      File "/Users/chanhopark/anaconda/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/Users/chanhopark/anaconda/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/Users/chanhopark/anaconda/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/Users/chanhopark/anaconda/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/Users/chanhopark/anaconda/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/Users/chanhopark/anaconda/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 324, in read
        flush_decoder = True
      File "/Users/chanhopark/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/requests/models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/Users/chanhopark/anaconda/pkgs/opencv3-3.1.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/chanhopark/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/chanhopark/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/Users/chanhopark/anaconda/pkgs/opencv3-3.1.0-py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).
```

**Comment by kalefranz** [comment]
This is just an intermittent HTTP error. Run `conda update conda` first. That should help.
