### ISSUE TITLE
fail to  install packages on  environment

### ISSUE THREAD

**Issue by Echocruise** [conda/conda#4401]
C:\Users\Administrator>activate dat210x

(dat210x) C:\Users\Administrator>conda install matplotlib
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment D:\04.Code\Python\Anaconda\envs\dat210x:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2017.0.1               |                0       128.8 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    icu-57.1                   |            vc9_0        34.5 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    jpeg-9b                    |            vc9_0         297 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    openssl-1.0.2j             |            vc9_0         4.4 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    tk-8.5.18                  |            vc9_0         2.2 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    zlib-1.2.8                 |            vc9_3         108 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    libpng-1.6.27              |            vc9_0         478 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    numpy-1.11.3               |           py27_0         3.1 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pyparsing-2.1.4            |           py27_0          70 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pytz-2016.10               |           py27_0         174 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    sip-4.18                   |           py27_0         260 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    six-1.10.0                 |           py27_0          16 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    cycler-0.10.0              |           py27_0          10 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    python-dateutil-2.6.0      |           py27_0         232 KB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    qt-5.6.2                   |            vc9_3        55.3 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pyqt-5.6.0                 |           py27_2         4.2 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    matplotlib-1.5.3           |      np111py27_1         6.1 MB  https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    ------------------------------------------------------------
                                           Total:       240.2 MB

The following NEW packages will be INSTALLED:

    cycler:          0.10.0-py27_0     https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    icu:             57.1-vc9_0        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    jpeg:            9b-vc9_0          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    libpng:          1.6.27-vc9_0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    matplotlib:      1.5.3-np111py27_1 https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    mkl:             2017.0.1-0        https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    numpy:           1.11.3-py27_0     https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    openssl:         1.0.2j-vc9_0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    pyparsing:       2.1.4-py27_0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pyqt:            5.6.0-py27_2      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    python-dateutil: 2.6.0-py27_0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    pytz:            2016.10-py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    qt:              5.6.2-vc9_3       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    sip:             4.18-py27_0       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    six:             1.10.0-py27_0     https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
    tk:              8.5.18-vc9_0      https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]
    zlib:            1.2.8-vc9_3       https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free [vc9]

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.                   | ETA:  0:20:09 110.03 kB/s

Please consider posting the following information to the conda GitHub issue tracker at; https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : D:\04.Code\Python\Anaconda  (writable)
    default environment : D:\04.Code\Python\Anaconda\envs\dat210x
       envs directories : D:\04.Code\Python\Anaconda\envs
          package cache : D:\04.Code\Python\Anaconda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Administrator\.condarc
           offline mode : False

`$ D:\04.Code\Python\Anaconda\Scripts\conda-script.py install matplotlib`

    Traceback (most recent call last):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "D:\04.Code\Python\Anaconda\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "D:\04.Code\Python\Anaconda\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "D:\04.Code\Python\Anaconda\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "D:\04.Code\Python\Anaconda\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "D:\04.Code\Python\Anaconda\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "D:\04.Code\Python\Anaconda\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "D:\04.Code\Python\Anaconda\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'D:\\04.Code\\Python\\Anaconda\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "D:\04.Code\Python\Anaconda\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "D:\04.Code\Python\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'D:\\04.Code\\Python\\Anaconda\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='mirrors.tuna.tsinghua.edu.cn', port=443): Read timed out.).

**Comment by kalefranz** [comment]
This is an http timeout issue with your server mirrors.tuna.tsinghua.edu.cn. Probably intermittent. Just try again.

However, `conda update conda` should help. As of today you should be in conda version 4.3.7.
