### ISSUE TITLE
installing scikit error

### ISSUE THREAD

**Issue by kamta0425** [conda/conda#4404]
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00   0.00  B/s
An unexpected error has occurred.#################  | Time: 0:16:15 132.65 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py install scikit-learn`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Program Files\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by kalefranz** [comment]
This is an intermittent HTTP timeout error.  Updating conda will help.

    conda update conda
