### ISSUE TITLE
conda update of Navigator causes "unexpected error"

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4411]
I ran `conda install -c continuumcrew anaconda-navigator` in order to get the latest version.  Conda borked and told me to report this.

Then I noticed I had Navigator running at the time.  Could that have been the problem?  I stopped Navigator and tried again.  Same exception.

So unclear if first time caused an issue due to Navigator running, and all subsequent attempts now suffer, or if Navigator running was not the problem.

```
$ conda install -c continuumcrew anaconda-navigator
Fetching package metadata .............
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::pyqt-5.6.0-py35_0, defaults::qt-5.6.0-0
  - defaults::pyqt-5.6.0-py35_2, defaults::qt-5.6.2-0

Package plan for installation in environment /Users/ijstokes/anaconda:

The following packages will be UPDATED:

    anaconda-navigator: 1.4rc2-py_0  continuumcrew --> 1.4rc3-py_0  continuumcrew
    qtpy:               1.1.2-py35_0               --> 1.2.0-py35_0              

The following packages will be DOWNGRADED due to dependency conflicts:

    qt:                 5.6.2-0                    --> 5.6.0-0                   

Proceed ([y]/n)? y

qt-5.6.0-0.tar 100% |#############################################################################################| Time: 0:00:24   3.09 MB/s
qtpy-1.2.0-py3 100% |#############################################################################################| Time: 0:00:00   3.90 MB/s
anaconda-navig 100% |#############################################################################################| Time: 0:00:01   2.68 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/continuumcrew/osx-64
                          https://conda.anaconda.org/continuumcrew/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/3.5.2 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 502:20



`$ /Users/ijstokes/anaconda/bin/conda install -c continuumcrew anaconda-navigator`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for _path cannot be None.
```

Ah

**Comment by ijstokes** [comment]
I really want Navigator to work, so I'm trying to figure out what has gone wrong.  I used `--debug` but it hasn't given me any extra hints that I can spot, however a Conda expert may have eyes attuned to details that I am missing.  Below is a trace from the last part of the failed Conda install:

```
Warning: 2 possible package resolutions (only showing differing packages):
  - defaults::pyqt-5.6.0-py35_0, defaults::qt-5.6.0-0
  - defaults::pyqt-5.6.0-py35_2, defaults::qt-5.6.2-0
DEBUG conda.toposort:_safe_toposort(83): Value error: Cyclic dependencies exist among these items: 'nbpresent' -> '_nb_ext_conf' -> 'nb_anacondacloud' -> 'anaconda' -> 'nb_conda' -> 'nb_conda_kernels'
DEBUG conda.toposort:_safe_toposort(83): Value error: Cyclic dependencies exist among these items: 'nbpresent' -> '_nb_ext_conf' -> 'anaconda' -> 'nb_conda' -> 'nb_conda_kernels'
DEBUG conda.toposort:_safe_toposort(83): Value error: Cyclic dependencies exist among these items: 'nbpresent' -> '_nb_ext_conf' -> 'anaconda' -> 'nb_conda'
DEBUG conda.toposort:_safe_toposort(83): Value error: Cyclic dependencies exist among these items: 'nbpresent' -> '_nb_ext_conf' -> 'anaconda'

Package plan for installation in environment /Users/ijstokes/anaconda:

The following packages will be UPDATED:

    anaconda-navigator: 1.4rc2-py_0  continuumcrew --> 1.4rc3-py_0  continuumcrew
    qtpy:               1.1.2-py35_0               --> 1.2.0-py35_0              

The following packages will be DOWNGRADED due to dependency conflicts:

    qt:                 5.6.2-0                    --> 5.6.0-0                   

Proceed ([y]/n)? y

DEBUG conda.plan:plan_from_actions(351): Adding plans for operations: ('CHECK_FETCH', 'RM_FETCHED', 'FETCH', 'CHECK_EXTRACT', 'RM_EXTRACTED', 'EXTRACT', 'UNLINK', 'LINK', 'SYMLINK_CONDA')
DEBUG conda.plan:plan_from_actions(366): appending value continuumcrew::anaconda-navigator-1.4rc2-py_0 for action UNLINK
DEBUG conda.plan:plan_from_actions(366): appending value defaults::qt-5.6.2-0 for action UNLINK
DEBUG conda.plan:plan_from_actions(366): appending value defaults::qtpy-1.1.2-py35_0 for action UNLINK
DEBUG conda.plan:plan_from_actions(366): appending value defaults::qt-5.6.0-0 for action LINK
DEBUG conda.plan:plan_from_actions(366): appending value defaults::qtpy-1.2.0-py35_0 for action LINK
DEBUG conda.plan:plan_from_actions(366): appending value continuumcrew::anaconda-navigator-1.4rc3-py_0 for action LINK
DEBUG conda.plan:plan_from_actions(366): appending value /Users/ijstokes/anaconda for action SYMLINK_CONDA
DEBUG conda.core.package_cache:__init__(431): instantiating ProgressiveFetchExtract with
  defaults::qt-5.6.0-0
  defaults::qtpy-1.2.0-py35_0
  continuumcrew::anaconda-navigator-1.4rc3-py_0

DEBUG conda.core.package_cache:prepare(457): prepared package cache actions:
  cache_actions:
    
  extract_actions:
    

DEBUG conda.instructions:execute_instructions(243): executing plan [('PREFIX', '/Users/ijstokes/anaconda'), ('PRINT', 'Unlinking packages ...'), ('PROGRESSIVEFETCHEXTRACT', <conda.core.package_cache.ProgressiveFetchExtract object at 0x10aaa95c0>), ('UNLINKLINKTRANSACTION', ((Dist(_Dist__initd=True, channel='continuumcrew', dist_name='anaconda-navigator-1.4rc2-py_0', name='anaconda-navigator', version='1.4rc2', build_string='py_0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='defaults', dist_name='qt-5.6.2-0', name='qt', version='5.6.2', build_string='0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='defaults', dist_name='qtpy-1.1.2-py35_0', name='qtpy', version='1.1.2', build_string='py35_0', build_number=0, with_features_depends=None, base_url=None, platform=None)), (Dist(_Dist__initd=True, channel='defaults', dist_name='qt-5.6.0-0', name='qt', version='5.6.0', build_string='0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='defaults', dist_name='qtpy-1.2.0-py35_0', name='qtpy', version='1.2.0', build_string='py35_0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='continuumcrew', dist_name='anaconda-navigator-1.4rc3-py_0', name='anaconda-navigator', version='1.4rc3', build_string='py_0', build_number=0, with_features_depends=None, base_url=None, platform=None)))), ('UNLINK', Dist(_Dist__initd=True, channel='continuumcrew', dist_name='anaconda-navigator-1.4rc2-py_0', name='anaconda-navigator', version='1.4rc2', build_string='py_0', build_number=0, with_features_depends=None, base_url=None, platform=None)), ('UNLINK', Dist(_Dist__initd=True, channel='defaults', dist_name='qt-5.6.2-0', name='qt', version='5.6.2', build_string='0', build_number=0, with_features_depends=None, base_url=None, platform=None)), ('UNLINK', Dist(_Dist__initd=True, channel='defaults', dist_name='qtpy-1.1.2-py35_0', name='qtpy', version='1.1.2', build_string='py35_0', build_number=0, with_features_depends=None, base_url=None, platform=None)), ('PRINT', 'Linking packages ...'), ('LINK', Dist(_Dist__initd=True, channel='defaults', dist_name='qt-5.6.0-0', name='qt', version='5.6.0', build_string='0', build_number=0, with_features_depends=None, base_url=None, platform=None)), ('LINK', Dist(_Dist__initd=True, channel='defaults', dist_name='qtpy-1.2.0-py35_0', name='qtpy', version='1.2.0', build_string='py35_0', build_number=0, with_features_depends=None, base_url=None, platform=None)), ('LINK', Dist(_Dist__initd=True, channel='continuumcrew', dist_name='anaconda-navigator-1.4rc3-py_0', name='anaconda-navigator', version='1.4rc3', build_string='py_0', build_number=0, with_features_depends=None, base_url=None, platform=None)), ('SYMLINK_CONDA', '/Users/ijstokes/anaconda')]
DEBUG conda.instructions:execute_instructions(249):  PREFIX('/Users/ijstokes/anaconda')
DEBUG conda.instructions:execute_instructions(249):  PRINT('Unlinking packages ...')
DEBUG conda.instructions:execute_instructions(249):  PROGRESSIVEFETCHEXTRACT(<conda.core.package_cache.ProgressiveFetchExtract object at 0x10aaa95c0>)
DEBUG conda.instructions:execute_instructions(249):  UNLINKLINKTRANSACTION(((Dist(_Dist__initd=True, channel='continuumcrew', dist_name='anaconda-navigator-1.4rc2-py_0', name='anaconda-navigator', version='1.4rc2', build_string='py_0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='defaults', dist_name='qt-5.6.2-0', name='qt', version='5.6.2', build_string='0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='defaults', dist_name='qtpy-1.1.2-py35_0', name='qtpy', version='1.1.2', build_string='py35_0', build_number=0, with_features_depends=None, base_url=None, platform=None)), (Dist(_Dist__initd=True, channel='defaults', dist_name='qt-5.6.0-0', name='qt', version='5.6.0', build_string='0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='defaults', dist_name='qtpy-1.2.0-py35_0', name='qtpy', version='1.2.0', build_string='py35_0', build_number=0, with_features_depends=None, base_url=None, platform=None), Dist(_Dist__initd=True, channel='continuumcrew', dist_name='anaconda-navigator-1.4rc3-py_0', name='anaconda-navigator', version='1.4rc3', build_string='py_0', build_number=0, with_features_depends=None, base_url=None, platform=None))))
DEBUG conda.core.link:create_from_dists(115): instantiating UnlinkLinkTransaction with
  target_prefix: /Users/ijstokes/anaconda
  unlink_dists:
    continuumcrew::anaconda-navigator-1.4rc2-py_0
    defaults::qt-5.6.2-0
    defaults::qtpy-1.1.2-py35_0
  link_dists:
    defaults::qt-5.6.0-0
    defaults::qtpy-1.2.0-py35_0
    continuumcrew::anaconda-navigator-1.4rc3-py_0

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : osx-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/continuumcrew/osx-64
                          https://conda.anaconda.org/continuumcrew/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/3.5.2 Darwin/16.3.0 OSX/10.12.2
                UID:GID : 502:20



`$ /Users/ijstokes/anaconda/bin/conda --debug install --debug -c continuumcrew anaconda-navigator`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for _path cannot be None.
```

**Comment by kalefranz** [comment]
This was a bug in conda-build 2.1.0 and 2.1.1 that we just recently got fixed in 2.1.2.

It's coming from the anaconda-navigator 1.4rc3-py_0 old-style noarch package.

Unfortunately that package will need to be re-built.  In doing so, you could try out the new noarch packages.  In the recipe, replace the line

    build:
      noarch_python: true

with

    build:
      noarch: python

**Comment by kalefranz** [comment]
Closed this issue here.  I guess you need to open a new one somewhere else with whoever builds and uploads anaconda-navigator to the continuumcrew channel.

**Comment by ijstokes** [comment]
This issue was moved to ContinuumIO/navigator#877
