### ISSUE TITLE
OpenSSL.SSL.Error

### ISSUE THREAD

**Issue by badboyrzr** [conda/conda#4418]
How to fix this error?

ssl_verify: True  (returns)
C:\Users\nayaka>conda update certifi
Fetching package metadata ...

CondaHTTPError: HTTP None None for url <None>
Elapsed: None

An HTTP error occurred when trying to retrieve this URL.
SSLError(SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

#ssl_verify: FortiCert.crt

C:\Users\nayaka>conda list ssl
 packages in environment at C:\Anaconda:

openssl                   1.0.2j                   vc14_0  [vc14]
pyopenssl                 16.2.0                   py35_0

C:\Users\nayaka>conda update conda
Fetching package metadata ....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
          package cache : C:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\nayaka\.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/3.5.2 Windows/7 Windows/6.1.7601

`$ C:\Anaconda\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 385, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 191, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 323, in connect
        ssl_context=context)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 392, in load_verify_locations
        self._ctx.load_verify_locations(cafile, capath)
      File "C:\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 525, in load_verify_locations
        _raise_current_error()
      File "C:\Anaconda\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: []

C:\Users\nayaka>conda config --show
add_anaconda_token: True
add_pip_as_python_dependency: True
allow_softlinks: True
always_copy: False
always_softlink: False
always_yes: False
auto_update_conda: True
binstar_upload: None
changeps1: True
channel_alias: https://conda.anaconda.org
channel_priority: True
channels:
  - defaults
client_ssl_cert:
client_ssl_cert_key:
create_default_packages: []
debug: False
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/r
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/msys2
disallow: []
envs_dirs:
  - C:\Anaconda\envs
json: False
offline: False
proxy_servers: {}
quiet: False
shortcuts: True
show_channel_urls: None
ssl_verify: FortiCert.crt
track_features: []
update_dependencies: True
use_pip: True
verbosity: 0

**Comment by kalefranz** [comment]
I have no idea right now.  Looks like you have all the updated packages.  @mingwandroid what's the best way to diagnose ssl errors on Windows?

**Comment by badboyrzr** [comment]
The update of packages works when
conda config --set ssl_verify False

However 
conda config --set ssl_verify False results in ssl error.
And the option below, just throws in an error to post it on conda issues.
conda config --set ssl_verify <pathToYourFile>.crt   (I got this crt file from my organisation.)

**Comment by asimonov** [comment]
I am having issues updating conda on MacOS ElCapitan.

cannot even set ssl_verify:

MacName:~ myusername$ conda config --set ssl_verify False
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/gateways/disk/delete.py", line 15, in <module>
    from .read import get_json_content
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 23, in <module>
    from ...models.channel import Channel
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCRYPT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myusername/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 607, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 561, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 531, in get_info
    args.func(args, p)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main_info.py", line 142, in execute
    from conda.api import get_index
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/path_actions.py", line 32, in <module>
    from ..gateways.download import download
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCRYPT'

**Comment by kalefranz** [comment]
@asimonov see https://github.com/conda/conda/issues/4679#issuecomment-282371614

**Comment by kalefranz** [comment]
At this point I'm hopeful we've gotten all of requests' dependencies (cryptography, pyopenssl, etc) confined to working versions.  If you're running conda 4.3.13, this issue should now be resolved.

**Comment by asimonov** [comment]
yes, the latest conda install works and does not have openssl error.
thank you!

**Comment by badboyrzr** [comment]
It works in the latest version of conda. There is no ssl error currently present. 
Thanks.

**Comment by asimonov** [comment]
Yes, it does!

_____________________________
Kind Regards,
Alexey Simonov
