### ISSUE TITLE
conda update fails

### ISSUE THREAD

**Issue by aatishk** [conda/conda#4419]
~ aatish$ conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.7
       conda is private : False
      conda-env version : 4.3.7
    conda-build version : 1.8.2
         python version : 2.7.11.final.0
       requests version : 2.12.4
       root environment : /Users/aatish/anaconda  (writable)
    default environment : /Users/aatish/anaconda
       envs directories : /Users/aatish/anaconda/envs
          package cache : /Users/aatish/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/aatish/.condarc
           offline mode : False
             user-agent : conda/4.3.7 requests/2.12.4 CPython/2.7.11 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

`$ /Users/aatish/anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 136, in install
        linked_dists = install_linked(prefix)
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 121, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 113, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/aatish/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 34, in load_linked_data
        rec = json.load(fi)
      File "/Users/aatish/anaconda/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/Users/aatish/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/Users/aatish/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/aatish/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by kalefranz** [comment]
It looks like you have a corrupt file somewhere in `/Users/aatish/anaconda/conda-meta`.

Run this in python.  It'll tell you which file is bad.

```
from glob import glob
from json import loads
for path in glob('/Users/aatish/anaconda/conda-meta/*.json'):
    try:
        with open(path) as fh:
            data = loads(fh.read())
    except:
        print(path)
        raise
```
