### ISSUE TITLE
Issue in updating anaconda

### ISSUE THREAD

**Issue by umar021** [conda/conda#4421]
I am unable to update my anaconda version when i use `conda update anaconda`. Please find the output of `conda info` below
```
Umar@Umars-MacBook-Pro:~$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.18.1
       python version : 2.7.10.final.0
     requests version : 2.12.4
     root environment : /Users/Umar/anaconda  (writable)
  default environment : /Users/Umar/anaconda
     envs directories : /Users/Umar/anaconda/envs
        package cache : /Users/Umar/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

\Umar

**Comment by kalefranz** [comment]
Do `conda update conda` first.  Then `conda update anaconda`.

**Comment by umar021** [comment]
@kalefranz , thanks for your response, This is what i get 
 
```
Umar@Umars-MacBook-Pro:~$ conda update conda
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/Umar/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
    args_func(args, p)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
    args.func(args, p)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 48, in execute
    install.install(args, parser, 'update')
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 239, in install
    offline=args.offline)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 598, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/api.py", line 42, in get_index
    unknown=unknown)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/utils.py", line 119, in __call__
    value = self.func(*args, **kw)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 264, in fetch_index
    reversed(channel_urls))
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 263, in <lambda>
    use_cache=use_cache, session=session)),
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 330, in connect
    cert = self.sock.getpeercert()
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 324, in getpeercert
    'subjectAltName': get_subj_alt_name(x509)
  File "/Users/Umar/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 171, in get_subj_alt_name
    ext = cert.extensions.get_extension_for_class(
AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'
```
The `conda info` is similar as above.
