### ISSUE TITLE
Started updates on root but now anaconda navigator won't open on Mac

### ISSUE THREAD

**Issue by KvKaplan** [conda/conda#4430]
This is the error message. I am new to anaconda and python and would greatly appreciate any assistance and commands. 

Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "//anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 519, in get_info
    from conda.cli import conda_argparse
  File "//anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "//anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 22, in <module>
    from ..resolve import MatchSpec
  File "//anaconda/lib/python2.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "//anaconda/lib/python2.7/site-packages/conda/logic.py", line 32, in <module>
    import pycosat
ImportError: dlopen(//anaconda/lib/python2.7/site-packages/pycosat.so, 2): Symbol not found: _Py_InitModule4_64
  Referenced from: //anaconda/lib/python2.7/site-packages/pycosat.so
  Expected in: flat namespace
 in //anaconda/lib/python2.7/site-packages/pycosat.so
[153797 refs]

**Comment by kalefranz** [comment]
You've corrupted your environment somehow.  Installing miniconda on top of your current environment should fix the issue.
