### ISSUE TITLE
failed to update (py)qt

### ISSUE THREAD

**Issue by martinwk** [conda/conda#4436]
Trying 

``` conda install pyqt qt ```

fails. Possibly due to some impatient reaction of mine, namely that I hitted ctrl+c while installing qt/pyqt... If that is the reason, how to fix it.

```
               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.12.5
       root environment : C:\Users\korevma\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\korevma\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\korevma\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\korevma\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\korevma\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.5 CPython/2.7.12 Windows/7 Windows/6.1.7601



`$ C:\Users\korevma\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py install qt`




    Traceback (most recent call last):
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\korevma\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'C:\\Users\\korevma\\AppData\\Local\\Continuum\\Anaconda2\\pkgs\\qt-5.6.2-vc9_3\\info\\index.json'
```

**Comment by martinwk** [comment]
Hmm, when I installed first pyqt it finishes installation and qt 5.6.2 is installed. When I subsequently 

``` conda install qt ```

it says

```
    jpeg:    8d-vc9_0     defaults [vc9] --> 9b-vc9_0     defaults [vc9]
    libpng:  1.6.22-vc9_0 defaults [vc9] --> 1.6.27-vc9_0 defaults [vc9]
    libtiff: 4.0.6-vc9_2  defaults [vc9] --> 4.0.6-vc9_3  defaults [vc9]
    qt:      5.6.2-vc9_0  defaults [vc9] --> 5.6.2-vc9_3  defaults [vc9]
```
which fails as soon as I hit `y` to proceed. The error message is the same as posted above

**Comment by kalefranz** [comment]
First try

    conda clean --packages --tarballs

if `conda install qt` still doesn't work, try just manually deleting the directory 

    C:\Users\korevma\AppData\Local\Continuum\Anaconda2\pkgs

Going to leave the issue open for now in case you're still having problems.  I *think* that should clear things up for you though.

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
