### ISSUE TITLE
Unknown error whille installing packages

### ISSUE THREAD

**Issue by R1413** [conda/conda#4440]
Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.10.0
       root environment : /home/r1413/anaconda3  (writable)
    default environment : /home/r1413/anaconda3
       envs directories : /home/r1413/anaconda3/envs
          package cache : /home/r1413/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /home/r1413/anaconda3/bin/conda create -n python2_7 python=2 scikit-learn`

    Traceback (most recent call last):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 228, in _error_catcher
        yield
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 310, in read
        data = self._fp.read(amt)
      File "/home/r1413/anaconda3/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/home/r1413/anaconda3/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/home/r1413/anaconda3/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/home/r1413/anaconda3/lib/python3.5/ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "/home/r1413/anaconda3/lib/python3.5/ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "/home/r1413/anaconda3/lib/python3.5/ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/models.py", line 664, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 353, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 320, in read
        flush_decoder = True
      File "/home/r1413/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 233, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/requests/models.py", line 671, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/home/r1413/anaconda3/pkgs/openssl-1.0.2k-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/home/r1413/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/home/r1413/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/home/r1413/anaconda3/pkgs/openssl-1.0.2k-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by kalefranz** [comment]
This is an intermittent HTTP issue due to a flakey internet connection.  Just retry.  Also

    conda update conda

will help.
