### ISSUE TITLE
conda-script.py update --all

### ISSUE THREAD

**Issue by chanakafit** [conda/conda#4442]
Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Anaconda3\\pkgs\\pillow-4.0.0-py35_0\\info\\index.json'

**Comment by kalefranz** [comment]
conda clean --packages --tarballs

Should help.  If you get the problem again, then you're using a channel that has a corrupt pillow package.
