### ISSUE TITLE
Activating a non existing environment displays some error trace

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#4444]
Could we have a friendlier message and error handling, instead of the error traceback? 

```
$ source activate spamfoobar
Traceback (most recent call last):
  File "/Users/<USER>/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/<USER>/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 154, in main
    activate.main()
  File "/Users/<USER>/anaconda/lib/python2.7/site-packages/conda/cli/activate.py", line 160, in main
    prefix = prefix_from_arg(sys.argv[3], shelldict=shelldict)
  File "/Users/<USER>/anaconda/lib/python2.7/site-packages/conda/cli/activate.py", line 60, in prefix_from_arg
    prefix = locate_prefix_by_name(context, arg.replace('/', os.path.sep))
  File "/Users/<USER>/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 538, in locate_prefix_by_name
    raise CondaEnvironmentNotFoundError(name)
conda.exceptions.CondaEnvironmentNotFoundError: Could not find environment: spamfoobar .
You can list all discoverable environments with `conda info --envs`.
```

**Comment by kalefranz** [comment]
We fixed this somewhere along the way :)  No more stack trace.
