### ISSUE TITLE
Can't create very simple environment.

### ISSUE THREAD

**Issue by mosew** [conda/conda#4449]
All I tried to do was create an environment with Python3.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\anaconda2\lib\site-packages\conda\cli\main_create.py", line 58, in execute
    install(args, parser, 'create')
  File "C:\anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\anaconda2\lib\site-packages\conda\plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\anaconda2\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "C:\anaconda2\lib\site-packages\conda\instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\anaconda2\lib\site-packages\conda\fetch.py", line 338, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\anaconda2\lib\site-packages\conda\fetch.py", line 423, in download
    chunk = resp.raw.read(2**14)
  File "C:\anaconda2\lib\site-packages\requests\packages\urllib3\response.py", line 320, in read
    flush_decoder = True
  File "C:\Anaconda2\lib\contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\anaconda2\lib\site-packages\requests\packages\urllib3\response.py", line 246, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(10054, 'An existing connection was forcibly closed by the remote host')", error(10054, 'An existing connection was forcibly closed by the remote host'))

conda info
Current conda install:

             platform : win-64
        conda version : 4.1.9
    conda-env version : 2.5.2
  conda-build version : 1.20.3
       python version : 2.7.11.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/win-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
                        https://repo.continuum.io/pkgs/msys2/win-64/
                        https://repo.continuum.io/pkgs/msys2/noarch/
          config file : C:\Users\mose\.condarc
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
That's just a flakey internet connection.  But your version of conda is also ancient. `conda update conda` will help
