### ISSUE TITLE
Updating conda failed: RuntimeError: multiple python records found in prefix /Users/mike/anaconda

### ISSUE THREAD

**Issue by pya** [conda/conda#4457]
Could be related #4398 At leas this happened nearly at the same time.

I cannot update `conda` anymore:

```
conda update -v -v -v conda

<skip>

The following packages will be UPDATED:

    conda:      4.3.6-py27_0  --> 4.3.8-py27_0

Proceed ([y]/n)? 

<skip>


  unlink_dists:
    defaults::conda-4.3.5-py27_0
    defaults::conda-4.3.6-py27_0
    defaults::enum34-1.1.6-py27_0
    defaults::mkl-11.3.1-0
    defaults::numpy-1.10.4-py27_0
    defaults::openssl-1.0.2j-0
    defaults::pip-9.0.1-py27_1
    defaults::pycosat-0.6.1-py27_1
    defaults::pycparser-2.17-py27_0
    defaults::python-2.7.12-1
    defaults::setuptools-27.2.0-py27_0
    defaults::zlib-1.2.8-3
  link_dists:
    defaults::conda-4.3.8-py27_0

TRACE conda.gateways.disk.test:hardlink_supported(56): checking hard link capability for /Users/mike/anaconda/pkgs/conda-4.3.8-py27_0/info/index.json => /Users/mike/anaconda
TRACE conda.gateways.disk.delete:rm_rf(30): rm_rf /Users/mike/anaconda/.tmp.index.json
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : osx-64
          conda version : 4.3.6
       conda is private : False
      conda-env version : 4.3.6
    conda-build version : 1.21.5
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/mike/anaconda  (writable)
    default environment : /Users/mike/anaconda
       envs directories : /Users/mike/anaconda/envs
          package cache : /Users/mike/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/hydrocomputing/osx-64
                          https://conda.anaconda.org/hydrocomputing/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/Esri/osx-64
                          https://conda.anaconda.org/Esri/noarch
            config file : /Users/mike/.condarc
           offline mode : False
             user-agent : conda/4.3.6 requests/2.12.4 CPython/2.7.13 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20



`$ /Users/mike/anaconda/bin/conda update -v -v -v conda`




    Traceback (most recent call last):
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/mike/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 362, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: multiple python records found in prefix /Users/mike/anaconda


```

**Comment by kalefranz** [comment]
Whoaa. Yeah unfortunately we have a big of a mess in your environment.  And it's hard to tell without hands-on exactly what state your in.  But we can try... What does the following give you?

    python -c "import conda; print(conda.__version__)"

**Comment by kalefranz** [comment]
The output you're showing is really messed up and wrong.  The part in particular

```
  unlink_dists:
    defaults::conda-4.3.5-py27_0
    defaults::conda-4.3.6-py27_0
    defaults::enum34-1.1.6-py27_0
    defaults::mkl-11.3.1-0
    defaults::numpy-1.10.4-py27_0
    defaults::openssl-1.0.2j-0
    defaults::pip-9.0.1-py27_1
    defaults::pycosat-0.6.1-py27_1
    defaults::pycparser-2.17-py27_0
    defaults::python-2.7.12-1
    defaults::setuptools-27.2.0-py27_0
    defaults::zlib-1.2.8-3
  link_dists:
    defaults::conda-4.3.8-py27_0
```

That's saying we're going to uninstall python 2.7, along with conda 4.3.5 and 4.3.6, and then only replace all that with conda 4.3.8.  Obviously there should have never been two versions of conda there to begin with, and furthermore, conda can't run without a python interpreter in the environment.

Unfortunately you're in a really weird spot with conda 4.3, and given the history, I'm pretty sure you ever had a full working copy of 4.3.  I hate giving this advice, and I rarely do, but for you, we might have to end up with a full remove and re-install.

Let's see if we can come up with another solution first though...

**Comment by kalefranz** [comment]
If you want to poke around on your own a bit (and also give me additional information), you can help with

    ls -al /Users/mike/anaconda/conda-meta/

**Comment by pya** [comment]
I must have installed some nasty package. Or the install must have been interrupted. Not sure.

I don't have a big problem with a reinstall. I might go with miniconda and just work from environments. My main concern is my many environments. Does this work?

1. Save `/Users/mike/anaconda/envs/`
2. Un-install Anaconda
3. Install a new Miniconda or Anaconda
4. Move the directories saved in 1. to `/Users/mike/anaconda3/envs/` or `/Users/mike/miniconda3/envs/`
I guess I am missing the package repository and more meta infos.
If this does not work, what would be the best strategy to recreate my environments.

My other approach would be doing this for all environments:

```
conda env export -n myenv -f myenv_spec.txt
```
Unistall and install, and again for all environments:

```
conda create -n myenv -- file myenv_spec.txt

```

Here the output of the commands you asked for:

```

python -c "import conda; print(conda.__version__)"
4.3.6
```


and

```
ls -al /Users/mike/anaconda/conda-meta/
total 8504
drwxr-xr-x  211 mike  staff    7174 24 Jan 00:52 .
drwxr-xr-x   25 mike  staff     850 28 Jan 22:34 ..
-rw-r--r--    1 mike  staff     237 24 Jan 00:52 _license-1.1-py27_0.json
-rw-r--r--    1 mike  staff    3700 24 Jan 00:52 anaconda-1.7.0-np17py27_0.json
-rw-r--r--    1 mike  staff   14765 24 Jan 00:52 anaconda-client-1.6.0-py27_0.json
-rw-r--r--    1 mike  staff   40758 24 Jan 00:52 apptools-4.2.0-py27_0.json
-rw-r--r--    1 mike  staff   20133 24 Jan 00:52 astroid-1.3.4-py27_0.json
-rw-r--r--    1 mike  staff   55758 24 Jan 00:52 astropy-0.2.4-np17py27_1.json
-rw-r--r--    1 mike  staff    2904 24 Jan 00:52 atom-0.3.2-py27_0.json
-rw-r--r--    1 mike  staff     711 24 Jan 00:52 backports-1.0-py27_0.json
-rw-r--r--    1 mike  staff    4670 24 Jan 00:52 binstar-0.3.1-py27_0.json
-rw-r--r--    1 mike  staff   52789 24 Jan 00:52 biopython-1.61-np17py27_0.json
-rw-r--r--    1 mike  staff     555 24 Jan 00:52 bitarray-0.8.1-py27_0.json
-rw-r--r--    1 mike  staff   45117 24 Jan 00:52 bokeh-0.9.0-np19py27_0.json
-rw-r--r--    1 mike  staff   38104 24 Jan 00:52 boto-2.12.0-py27_0.json
-rw-r--r--    1 mike  staff     304 24 Jan 00:52 casuarius-1.1-py27_0.json
-rw-r--r--    1 mike  staff    3038 24 Jan 00:52 cffi-1.9.1-py27_0.json
-rw-r--r--    1 mike  staff   29390 24 Jan 00:52 chaco-4.3.0-np17py27_1.json
-rw-r--r--    1 mike  staff    1048 24 Jan 00:52 chest-0.2.2-py27_0.json
-rw-r--r--    1 mike  staff    2397 24 Jan 00:52 clyent-1.2.2-py27_0.json
-rw-r--r--    1 mike  staff    1300 24 Jan 00:52 colorama-0.3.3-py27_0.json
-rw-r--r--    1 mike  staff   20419 24 Jan 00:52 conda-4.3.5-py27_0.json
-rw-r--r--    1 mike  staff   20511 24 Jan 00:52 conda-4.3.6-py27_0.json
-rw-r--r--    1 mike  staff    6607 24 Jan 00:52 conda-build-1.21.5-py27_0.json
-rw-r--r--    1 mike  staff     712 24 Jan 00:52 conda-env-2.6.0-0.json
-rw-r--r--    1 mike  staff     455 24 Jan 00:52 configobj-4.7.2-py27_0.json
-rw-r--r--    1 mike  staff    1547 24 Jan 00:52 configparser-3.5.0b2-py27_1.json
-rw-r--r--    1 mike  staff   13289 24 Jan 00:52 cryptography-1.7.1-py27_0.json
-rw-r--r--    1 mike  staff    4239 24 Jan 00:52 cubes-0.10.2-py27_3.json
-rw-r--r--    1 mike  staff    3001 24 Jan 00:52 curl-7.30.0-1.json
-rw-r--r--    1 mike  staff   25178 24 Jan 00:52 cython-0.22.1-py27_0.json
-rw-r--r--    1 mike  staff    1813 24 Jan 00:52 cytoolz-0.7.0-py27_0.json
-rw-r--r--    1 mike  staff    6706 24 Jan 00:52 dask-0.5.0-np19py27_0.json
-rw-r--r--    1 mike  staff    1270 24 Jan 00:52 dateutil-2.1-py27_2.json
-rw-r--r--    1 mike  staff     927 24 Jan 00:52 dbf-0.96.003-py27_0.json
-rw-r--r--    1 mike  staff    1184 24 Jan 00:52 decorator-4.0.9-py27_0.json
-rw-r--r--    1 mike  staff    1723 24 Jan 00:52 dill-0.2.2-py27_0.json
-rw-r--r--    1 mike  staff    8370 24 Jan 00:52 distribute-0.6.45-py27_0.json
-rw-r--r--    1 mike  staff   21106 24 Jan 00:52 docutils-0.12-py27_0.json
-rw-r--r--    1 mike  staff    5299 24 Jan 00:52 dynd-python-0.4.2-np17py27_0.json
-rw-r--r--    1 mike  staff   37298 24 Jan 00:52 enable-4.3.0-np17py27_0.json
-rw-r--r--    1 mike  staff   36629 24 Jan 00:52 enaml-0.7.19-py27_2.json
-rw-r--r--    1 mike  staff     724 24 Jan 00:52 entrypoints-0.2-py27_1.json
-rw-r--r--    1 mike  staff    1074 24 Jan 00:52 enum34-1.0.4-py27_0.json
-rw-r--r--    1 mike  staff    1467 24 Jan 00:52 enum34-1.1.6-py27_0.json
-rw-r--r--    1 mike  staff   43094 24 Jan 00:52 envisage-4.3.0-py27_0.json
-rw-r--r--    1 mike  staff    1813 24 Jan 00:52 et_xmlfile-1.0.1-py27_0.json
-rw-r--r--    1 mike  staff    1486 24 Jan 00:52 fastcache-1.0.2-py27_0.json
-rw-r--r--    1 mike  staff    4627 24 Jan 00:52 flask-0.10.1-py27_1.json
-rw-r--r--    1 mike  staff    2734 24 Jan 00:52 freetype-2.5.2-2.json
-rw-r--r--    1 mike  staff    1273 24 Jan 00:52 funcsigs-0.4-py27_0.json
-rw-r--r--    1 mike  staff   16341 24 Jan 00:52 future-0.11.2-py27_0.json
-rw-r--r--    1 mike  staff    4106 24 Jan 00:52 gevent-1.0.1-py27_0.json
-rw-r--r--    1 mike  staff    2577 24 Jan 00:52 gevent-websocket-0.9.3-py27_0.json
-rw-r--r--    1 mike  staff     613 24 Jan 00:52 gevent_zeromq-0.2.5-py27_2.json
-rw-r--r--    1 mike  staff    1362 24 Jan 00:52 googlefinance-0.7-py_0.json
-rw-r--r--    1 mike  staff     710 24 Jan 00:52 greenlet-0.4.6-py27_0.json
-rw-r--r--    1 mike  staff     406 24 Jan 00:52 grin-1.2.1-py27_1.json
-rw-r--r--    1 mike  staff    6601 24 Jan 00:52 h5py-2.2.0-np17py27_0.json
-rw-r--r--    1 mike  staff    1929 24 Jan 00:52 hdf5-1.8.9-2.json
-rw-r--r--    1 mike  staff     739 24 Jan 00:52 heapdict-1.0.0-py27_0.json
-rw-r--r--    1 mike  staff   39105 24 Jan 00:52 history
-rw-r--r--    1 mike  staff    1829 24 Jan 00:52 idna-2.2-py27_0.json
-rw-r--r--    1 mike  staff    9813 24 Jan 00:52 imaging-1.1.7-py27_2.json
-rw-r--r--    1 mike  staff     986 24 Jan 00:52 ipaddress-1.0.18-py27_0.json
-rw-r--r--    1 mike  staff    7465 24 Jan 00:52 ipykernel-4.3.1-py27_0.json
-rw-r--r--    1 mike  staff   39663 24 Jan 00:52 ipython-4.0.0-py27_0.json
-rw-r--r--    1 mike  staff    5483 24 Jan 00:52 ipython-notebook-3.1.0-py27_1.json
-rw-r--r--    1 mike  staff     545 24 Jan 00:52 ipython-qtconsole-1.0.0-py27_0.json
-rw-r--r--    1 mike  staff    2910 24 Jan 00:52 ipython_genutils-0.1.0-py27_0.json
-rw-r--r--    1 mike  staff    7492 24 Jan 00:52 ipywidgets-4.1.1-py27_0.json
-rw-r--r--    1 mike  staff     733 24 Jan 00:52 itsdangerous-0.24-py27_0.json
-rw-r--r--    1 mike  staff     792 24 Jan 00:52 jdcal-1.0-py27_0.json
-rw-r--r--    1 mike  staff    3690 24 Jan 00:52 jinja2-2.8-py27_0.json
-rw-r--r--    1 mike  staff     362 24 Jan 00:52 jpeg-8d-1.json
-rw-r--r--    1 mike  staff    2946 24 Jan 00:52 jsonschema-2.4.0-py27_0.json
-rw-r--r--    1 mike  staff     773 24 Jan 00:52 jupyter-1.0.0-py27_2.json
-rw-r--r--    1 mike  staff    6163 24 Jan 00:52 jupyter_client-4.2.2-py27_0.json
-rw-r--r--    1 mike  staff    2290 24 Jan 00:52 jupyter_console-4.1.1-py27_0.json
-rw-r--r--    1 mike  staff    5681 24 Jan 00:52 jupyter_core-4.1.0-py27_0.json
-rw-r--r--    1 mike  staff    6191 24 Jan 00:52 keyring-3.0.1-py27_0.json
-rw-r--r--    1 mike  staff    7861 24 Jan 00:52 launcher-0.1.2-py27_1.json
-rw-r--r--    1 mike  staff    5665 24 Jan 00:52 libdynd-0.4.2-0.json
-rw-r--r--    1 mike  staff    1972 24 Jan 00:52 libevent-2.0.20-1.json
-rw-r--r--    1 mike  staff     489 24 Jan 00:52 libnetcdf-4.2.1.1-1.json
-rw-r--r--    1 mike  staff    1125 24 Jan 00:52 libpng-1.6.17-0.json
-rw-r--r--    1 mike  staff    2945 24 Jan 00:52 libsodium-0.4.5-0.json
-rw-r--r--    1 mike  staff     990 24 Jan 00:52 libtiff-4.0.2-1.json
-rw-r--r--    1 mike  staff   14321 24 Jan 00:52 libxml2-2.9.0-1.json
-rw-r--r--    1 mike  staff    6880 24 Jan 00:52 libxslt-1.1.28-2.json
-rw-r--r--    1 mike  staff    1699 24 Jan 00:52 line_profiler-1.0-py27_1.json
-rw-r--r--    1 mike  staff   24801 24 Jan 00:52 llvm-3.3-0.json
-rw-r--r--    1 mike  staff    5683 24 Jan 00:52 llvmlite-0.5.0-py27_0.json
-rw-r--r--    1 mike  staff    5427 24 Jan 00:52 llvmmath-0.1.2-np17py27_0.json
-rw-r--r--    1 mike  staff   11631 24 Jan 00:52 llvmpy-0.12.6-py27_0.json
-rw-r--r--    1 mike  staff   16321 24 Jan 00:52 logilab-common-0.63.2-py27_0.json
-rw-r--r--    1 mike  staff    5595 24 Jan 00:52 lxml-3.3.4-py27_0.json
-rw-r--r--    1 mike  staff    1345 24 Jan 00:52 markupsafe-0.23-py27_0.json
-rw-r--r--    1 mike  staff  212047 24 Jan 00:52 matplotlib-1.4.3-np19py27_3.json
-rw-r--r--    1 mike  staff   63635 24 Jan 00:52 mayavi-4.3.0-np17py27_1.json
-rw-r--r--    1 mike  staff   20848 24 Jan 00:52 mdp-3.3-np17py27_0.json
-rw-r--r--    1 mike  staff   34397 24 Jan 00:52 mercurial-3.3.2-py27_0.json
-rw-r--r--    1 mike  staff    6272 24 Jan 00:52 meta-0.4.2.dev-py27_0.json
-rw-r--r--    1 mike  staff    1184 24 Jan 00:52 mistune-0.5.1-py27_1.json
-rw-r--r--    1 mike  staff    1218 24 Jan 00:52 mkl-11.3.1-0.json
-rw-r--r--    1 mike  staff    1407 24 Jan 00:52 mkl-2017.0.1-0.json
-rw-r--r--    1 mike  staff   19611 24 Jan 00:52 nbconvert-4.2.0-py27_0.json
-rw-r--r--    1 mike  staff    9025 24 Jan 00:52 nbformat-4.0.1-py27_0.json
-rw-r--r--    1 mike  staff     749 24 Jan 00:52 netcdf4-1.0.5-np17py27_0.json
-rw-r--r--    1 mike  staff   47870 24 Jan 00:52 networkx-1.8.1-py27_0.json
-rw-r--r--    1 mike  staff   27896 24 Jan 00:52 nltk-2.0.4-np17py27_0.json
-rw-r--r--    1 mike  staff    6468 24 Jan 00:52 nose-1.3.7-py27_0.json
-rw-r--r--    1 mike  staff  127330 24 Jan 00:52 notebook-4.2.0-py27_0.json
-rw-r--r--    1 mike  staff   45325 24 Jan 00:52 numba-0.19.1-np19py27_0.json
-rw-r--r--    1 mike  staff    1808 24 Jan 00:52 numexpr-2.4.4-np110py27_0.json
-rw-r--r--    1 mike  staff   49160 24 Jan 00:52 numpy-1.10.4-py27_0.json
-rw-r--r--    1 mike  staff   46032 24 Jan 00:52 numpy-1.11.3-py27_0.json
-rw-r--r--    1 mike  staff   18418 24 Jan 00:52 openpyxl-2.0.2-py27_0.json
-rw-r--r--    1 mike  staff    4070 24 Jan 00:52 openssl-1.0.2g-0.json
-rw-r--r--    1 mike  staff    4174 24 Jan 00:52 openssl-1.0.2j-0.json
-rw-r--r--    1 mike  staff   65395 24 Jan 00:52 pandas-0.18.1-np110py27_0.json
-rw-r--r--    1 mike  staff    1177 24 Jan 00:52 path.py-8.2.1-py27_0.json
-rw-r--r--    1 mike  staff    3397 24 Jan 00:52 patsy-0.2.1-np17py27_0.json
-rw-r--r--    1 mike  staff     712 24 Jan 00:52 pep8-1.6.2-py27_0.json
-rw-r--r--    1 mike  staff    1883 24 Jan 00:52 pexpect-3.3-py27_0.json
-rw-r--r--    1 mike  staff    1123 24 Jan 00:52 pickleshare-0.5-py27_0.json
-rw-r--r--    1 mike  staff   11331 24 Jan 00:52 pillow-2.9.0-py27_0.json
-rw-r--r--    1 mike  staff   36350 24 Jan 00:52 pip-8.1.2-py27_0.json
-rw-r--r--    1 mike  staff   37529 24 Jan 00:52 pip-9.0.1-py27_1.json
-rw-r--r--    1 mike  staff     738 24 Jan 00:52 ply-3.4-py27_0.json
-rw-r--r--    1 mike  staff    1703 24 Jan 00:52 psutil-2.2.1-py27_0.json
-rw-r--r--    1 mike  staff    1088 24 Jan 00:52 ptyprocess-0.4-py27_0.json
-rw-r--r--    1 mike  staff    4585 24 Jan 00:52 py-1.4.27-py27_0.json
-rw-r--r--    1 mike  staff   13819 24 Jan 00:52 pyamg-2.2.1-np110py27_0.json
-rw-r--r--    1 mike  staff    4196 24 Jan 00:52 pyasn1-0.1.9-py27_0.json
-rw-r--r--    1 mike  staff     400 24 Jan 00:52 pyaudio-0.2.7-py27_0.json
-rw-r--r--    1 mike  staff     658 24 Jan 00:52 pycosat-0.6.1-py27_0.json
-rw-r--r--    1 mike  staff     965 24 Jan 00:52 pycosat-0.6.1-py27_1.json
-rw-r--r--    1 mike  staff    2919 24 Jan 00:52 pycparser-2.17-py27_0.json
-rw-r--r--    1 mike  staff    2215 24 Jan 00:52 pycparser-2.9.1-py27_0.json
-rw-r--r--    1 mike  staff   17648 24 Jan 00:52 pycrypto-2.6-py27_0.json
-rw-r--r--    1 mike  staff     447 24 Jan 00:52 pycurl-7.19.0-py27_2.json
-rw-r--r--    1 mike  staff   65410 24 Jan 00:52 pyface-4.3.0-py27_0.json
-rw-r--r--    1 mike  staff    2245 24 Jan 00:52 pyflakes-0.7.3-py27_0.json
-rw-r--r--    1 mike  staff   37128 24 Jan 00:52 pygame-1.9.1-py27_1.json
-rw-r--r--    1 mike  staff   20504 24 Jan 00:52 pygments-2.0.2-py27_0.json
-rw-r--r--    1 mike  staff   51464 24 Jan 00:52 pylint-1.4.2-py27_0.json
-rw-r--r--    1 mike  staff   13405 24 Jan 00:52 pymc-2.3.6-np110py27_0.json
-rw-r--r--    1 mike  staff    2024 24 Jan 00:52 pyopenssl-16.2.0-py27_0.json
-rw-r--r--    1 mike  staff     717 24 Jan 00:52 pyparsing-2.0.3-py27_0.json
-rw-r--r--    1 mike  staff   31094 24 Jan 00:52 pyqt-4.11.3-py27_0.json
-rw-r--r--    1 mike  staff   28904 24 Jan 00:52 pysal-1.6.0-np17py27_1.json
-rw-r--r--    1 mike  staff     902 24 Jan 00:52 pysam-0.6-py27_0.json
-rw-r--r--    1 mike  staff    4892 24 Jan 00:52 pyside-1.1.2-py27_1.json
-rw-r--r--    1 mike  staff   13373 24 Jan 00:52 pytables-3.0.0-np17py27_1.json
-rw-r--r--    1 mike  staff    4949 24 Jan 00:52 pytest-2.7.1-py27_0.json
-rw-r--r--    1 mike  staff  137679 24 Jan 00:52 python-2.7.12-1.json
-rw-r--r--    1 mike  staff   96821 24 Jan 00:52 python-2.7.13-0.json
-rw-r--r--    1 mike  staff    2095 24 Jan 00:52 python-dateutil-2.4.2-py27_0.json
-rw-r--r--    1 mike  staff    1011 24 Jan 00:52 python.app-1.2-py27_3.json
-rw-r--r--    1 mike  staff   39692 24 Jan 00:52 pytz-2015.7-py27_0.json
-rw-r--r--    1 mike  staff    2483 24 Jan 00:52 pyyaml-3.11-py27_1.json
-rw-r--r--    1 mike  staff   14394 24 Jan 00:52 pyzmq-14.6.0-py27_0.json
-rw-r--r--    1 mike  staff  141126 24 Jan 00:52 qt-4.8.6-3.json
-rw-r--r--    1 mike  staff   22965 24 Jan 00:52 qtconsole-4.2.1-py27_0.json
-rw-r--r--    1 mike  staff    1354 24 Jan 00:52 readline-6.2-2.json
-rw-r--r--    1 mike  staff     295 24 Jan 00:52 redis-2.6.9-0.json
-rw-r--r--    1 mike  staff    1283 24 Jan 00:52 redis-py-2.9.1-py27_0.json
-rw-r--r--    1 mike  staff   15015 24 Jan 00:52 requests-2.12.4-py27_0.json
-rw-r--r--    1 mike  staff    9352 24 Jan 00:52 rope-0.9.4-py27_0.json
-rw-r--r--    1 mike  staff    3726 24 Jan 00:52 ruamel_yaml-0.11.14-py27_1.json
-rw-r--r--    1 mike  staff   44101 24 Jan 00:52 scikit-image-0.10.1-np18py27_0.json
-rw-r--r--    1 mike  staff   51491 24 Jan 00:52 scikit-learn-0.16.1-np110py27_0.json
-rw-r--r--    1 mike  staff  109517 24 Jan 00:52 scipy-0.17.0-np110py27_0.json
-rw-r--r--    1 mike  staff     812 24 Jan 00:52 setuptools-20.2.2-py27_0.json
-rw-r--r--    1 mike  staff     934 24 Jan 00:52 setuptools-27.2.0-py27_0.json
-rw-r--r--    1 mike  staff    1423 24 Jan 00:52 shiboken-1.1.2-py27_0.json
-rw-r--r--    1 mike  staff     824 24 Jan 00:52 simplegeneric-0.8.1-py27_0.json
-rw-r--r--    1 mike  staff     835 24 Jan 00:52 sip-4.16.5-py27_0.json
-rw-r--r--    1 mike  staff     885 24 Jan 00:52 six-1.10.0-py27_0.json
-rw-r--r--    1 mike  staff   41668 24 Jan 00:52 sphinx-1.2.3-py27_0.json
-rw-r--r--    1 mike  staff   98915 24 Jan 00:52 spyder-2.3.2-py27_0.json
-rw-r--r--    1 mike  staff     500 24 Jan 00:52 spyder-app-2.2.4-py27_0.json
-rw-r--r--    1 mike  staff   22395 24 Jan 00:52 sqlalchemy-0.8.2-py27_0.json
-rw-r--r--    1 mike  staff     976 24 Jan 00:52 sqlite-3.13.0-0.json
-rw-r--r--    1 mike  staff    1096 24 Jan 00:52 ssl_match_hostname-3.4.0.2-py27_0.json
-rw-r--r--    1 mike  staff  108907 24 Jan 00:52 statsmodels-0.5.0-np17py27_0.json
-rw-r--r--    1 mike  staff  150089 24 Jan 00:52 sympy-0.7.6.1-py27_0.json
-rw-r--r--    1 mike  staff    1513 24 Jan 00:52 terminado-0.5-py27_0.json
-rw-r--r--    1 mike  staff   15094 24 Jan 00:52 tk-8.5.18-0.json
-rw-r--r--    1 mike  staff    3363 24 Jan 00:52 toolz-0.7.2-py27_0.json
-rw-r--r--    1 mike  staff   10336 24 Jan 00:52 tornado-4.1-py27_0.json
-rw-r--r--    1 mike  staff    3799 24 Jan 00:52 traitlets-4.2.1-py27_0.json
-rw-r--r--    1 mike  staff   11273 24 Jan 00:52 traits-4.3.0-py27_0.json
-rw-r--r--    1 mike  staff   38821 24 Jan 00:52 traitsui-4.3.0-py27_0.json
-rw-r--r--    1 mike  staff  115256 24 Jan 00:52 twisted-13.2.0-py27_0.json
-rw-r--r--    1 mike  staff     458 24 Jan 00:52 ujson-1.33-py27_0.json
-rw-r--r--    1 mike  staff   21289 24 Jan 00:52 unidecode-0.4.17-py27_0.json
-rw-r--r--    1 mike  staff    1084 24 Jan 00:52 virtualenv-12.0.5-py27_0.json
-rw-r--r--    1 mike  staff  131968 24 Jan 00:52 vtk-5.10.1-py27_0.json
-rw-r--r--    1 mike  staff    5845 24 Jan 00:52 werkzeug-0.10.4-py27_0.json
-rw-r--r--    1 mike  staff    5780 24 Jan 00:52 wheel-0.29.0-py27_0.json
-rw-r--r--    1 mike  staff  213847 24 Jan 00:52 wxpython-3.0-py27_0.json
-rw-r--r--    1 mike  staff    2238 24 Jan 00:52 xlrd-0.9.4-py27_0.json
-rw-r--r--    1 mike  staff    3120 24 Jan 00:52 xlutils-1.7.1-py27_0.json
-rw-r--r--    1 mike  staff    3061 24 Jan 00:52 xlwt-1.0.0-py27_0.json
-rw-r--r--    1 mike  staff     830 24 Jan 00:52 yaml-0.1.6-0.json
-rw-r--r--    1 mike  staff     737 24 Jan 00:52 zeromq-4.0.5-0.json
-rw-r--r--    1 mike  staff     710 24 Jan 00:52 zlib-1.2.8-0.json
-rw-r--r--    1 mike  staff     899 24 Jan 00:52 zlib-1.2.8-3.json
-rw-r--r--    1 mike  staff    5181 24 Jan 00:52 zope.interface-4.0.5-py27_0.json
```

**Comment by pedrohasselmann** [comment]
I wish just to add that I'm facing same problem recently. it happened when I updated conda.

>     Traceback (most recent call last):
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
>         return_value = func(*args, **kwargs)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
>         exit_code = args.func(args, p)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
>         install(args, parser, 'update')
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 136, in install
>         linked_dists = install_linked(prefix)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 121, in linked
>         return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 113, in linked_data
>         load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/linked_data.py", line 66, in load_linked_data
>         linked_data_[prefix][dist] = rec = IndexRecord(**rec)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
>         instance = super(EntityType, cls).__call__(*args, **kwargs)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
>         setattr(self, key, kwargs[key])
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 831, in __setattr__
>         super(ImmutableEntity, self).__setattr__(attribute, value)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
>         instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 658, in box
>         return val if isinstance(val, self._type) else self._type(**val)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
>         instance = super(EntityType, cls).__call__(*args, **kwargs)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
>         setattr(self, key, kwargs[key])
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
>         instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/models/index_record.py", line 15, in box
>         return super(LinkTypeField, self).box(instance, val)
>       File "/usr/local/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 557, in box
>         raise ValidationError(val, msg=e1)
>     ValidationError: hard is not a valid LinkType

**Comment by kalefranz** [comment]
This issue is pretty old.  If there's anything here that you're continuing to have a problem with, please file a new issue after updating conda to the latest version.

**Comment by pya** [comment]
OK. I removed conda and reinstalled from scratch. Solved it.
