### ISSUE TITLE
couldn't install any packages

### ISSUE THREAD

**Issue by liebesakt** [conda/conda#4463]
(E:\Anaconda3) C:\Windows\system32>conda update pip
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
    exit_code = args.func(args, p)
  File "E:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "E:\Anaconda3\lib\site-packages\conda\cli\install.py", line 136, in install
    linked_dists = install_linked(prefix)
  File "E:\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 121, in linked
    return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
  File "E:\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 113, in linked_data
    load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
  File "E:\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 55, in load_linked_data
    channel, schannel = Channel(url).url_channel_wtf
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 160, in __call__
    c = Channel._cache_[value] = Channel.from_value(value)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 216, in from_value
    return Channel.from_url(value)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 202, in from_url
    return parse_conda_channel_url(url)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 131, in parse_conda_channel_url
    configured_token) = _read_channel_configuration(scheme, host, port, path)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 71, in _read_channel_configuration
    test_url = Url(host=host, port=port, path=path).url
AttributeError: 'Url' object has no attribute 'url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 530, in get_info
    args.func(args, p)
  File "E:\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 211, in execute
    channels = list(prioritize_channels(channels).keys())
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 432, in prioritize_channels
    channel = Channel(chn)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 160, in __call__
    c = Channel._cache_[value] = Channel.from_value(value)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 226, in from_value
    if value in context.custom_multichannels:
  File "E:\Anaconda3\lib\site-packages\conda\_vendor\auxlib\decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "E:\Anaconda3\lib\site-packages\conda\base\context.py", line 362, in custom_multichannels
    ) for name, urls in iteritems(reserved_multichannel_urls)
  File "E:\Anaconda3\lib\site-packages\conda\base\context.py", line 362, in <genexpr>
    ) for name, urls in iteritems(reserved_multichannel_urls)
  File "E:\Anaconda3\lib\site-packages\conda\base\context.py", line 361, in <genexpr>
    Channel.make_simple_channel(self.channel_alias, url) for url in urls)
  File "E:\Anaconda3\lib\site-packages\conda\models\channel.py", line 243, in make_simple_channel
    location, name = Url(host=url_parts.host, port=url_parts.port).url, url_parts.path
AttributeError: 'Url' object has no attribute 'url'

**Comment by kalefranz** [comment]
Might want to check your condarc file to make sure you don't have any bad values, but in general this has been fixed in recent versions of conda.
