### ISSUE TITLE
Tensorflow install error

### ISSUE THREAD

**Issue by zukard** [conda/conda#4465]
Hi guys, there're some errors during my installation of tensorflow 0.12.1, really have no idea what is wrong, pls help

here's the info:

C:\Windows\system32>activate style-transfer

(style-transfer) C:\Windows\system32>conda install -c conda-forge tensorflow=0.12.1
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment D:\DeepLearning\Anaconda3\envs\style-transfer:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl-2017.0.1               |                0       128.8 MB
    zlib-1.2.11                |           vc14_0         119 KB  conda-forge
    numpy-1.11.3               |           py35_0         3.4 MB
    six-1.10.0                 |           py35_1         208 KB  conda-forge
    protobuf-3.1.0             |      py35_vc14_0         9.6 MB  conda-forge
    pbr-1.10.0                 |           py35_0         141 KB  conda-forge
    mock-2.0.0                 |           py35_0         101 KB  conda-forge
    tensorflow-0.12.1          |           py35_1        14.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       157.0 MB

The following NEW packages will be INSTALLED:

    mkl:        2017.0.1-0
    mock:       2.0.0-py35_0      conda-forge
    numpy:      1.11.3-py35_0
    pbr:        1.10.0-py35_0     conda-forge
    protobuf:   3.1.0-py35_vc14_0 conda-forge [vc14]
    six:        1.10.0-py35_1     conda-forge
    tensorflow: 0.12.1-py35_1     conda-forge
    zlib:       1.2.11-vc14_0     conda-forge [vc14]

Proceed ([y]/n)? y

Fetching packages ...
mkl-2017.0.1-0 100% |###############################| Time: 0:41:52  53.74 kB/s
zlib-1.2.11-vc 100% |###############################| Time: 0:00:06  19.34 kB/s
numpy-1.11.3-p 100% |###############################| Time: 0:01:06  53.05 kB/s
An unexpected error has occurred.                   | Time: 0:00:03  15.44 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : D:\DeepLearning\Anaconda3  (writable)
    default environment : D:\DeepLearning\Anaconda3\envs\style-transfer
       envs directories : D:\DeepLearning\Anaconda3\envs
          package cache : D:\DeepLearning\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ D:\DeepLearning\Anaconda3\Scripts\conda-script.py install -c conda-forge tensorflow=0.12.1`

    Traceback (most recent call last):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "D:\DeepLearning\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "D:\DeepLearning\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "D:\DeepLearning\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "D:\DeepLearning\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "D:\DeepLearning\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "D:\DeepLearning\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "D:\DeepLearning\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'D:\\DeepLearning\\Anaconda3\\pkgs\\six-1.10.0-py35_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "D:\DeepLearning\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "D:\DeepLearning\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'D:\\DeepLearning\\Anaconda3\\pkgs\\six-1.10.0-py35_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

(style-transfer) C:\Windows\system32>

**Comment by ganeshrs** [comment]
Run the commands in administrator (root) mode. I was able to remove these errors in administrator mode.

**Comment by Krishnkant-Swarnkar** [comment]
I had the same issue, 
but I retried when my internet speed is at its peak, and it worked perfectly well .

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
