### ISSUE TITLE
"conda info -a" returns an exception, possibly during license file parsing

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#4468]
I don't know what to make of this but I have a pretty conventional Anaconda + Conda setup.  I have an "almost" virigin Anaconda 4.2 installation (just installed a few days ago), and I've updated Conda to the latest version.  And I get an exception when I execute `conda info -a` as you can see below.

```
$ conda info -a
Current conda install:

               platform : osx-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda
       envs directories : /Users/ijstokes/anaconda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 502:20

# conda environments:
#
dspyr                    /Users/ijstokes/anaconda/envs/dspyr
root                  *  /Users/ijstokes/anaconda

sys.version: 3.5.2 |Anaconda custom (x86_64)| (defaul...
sys.prefix: /Users/ijstokes/anaconda
sys.executable: /Users/ijstokes/anaconda/bin/python
conda location: /Users/ijstokes/anaconda/lib/python3.5/site-packages/conda
conda-build: /Users/ijstokes/anaconda/bin/conda-build
conda-convert: /Users/ijstokes/anaconda/bin/conda-convert
conda-develop: /Users/ijstokes/anaconda/bin/conda-develop
conda-env: /Users/ijstokes/anaconda/bin/conda-env
conda-index: /Users/ijstokes/anaconda/bin/conda-index
conda-inspect: /Users/ijstokes/anaconda/bin/conda-inspect
conda-metapackage: /Users/ijstokes/anaconda/bin/conda-metapackage
conda-render: /Users/ijstokes/anaconda/bin/conda-render
conda-server: /Users/ijstokes/anaconda/bin/conda-server
conda-sign: /Users/ijstokes/anaconda/bin/conda-sign
conda-skeleton: /Users/ijstokes/anaconda/bin/conda-skeleton
conda-verify: /Users/ijstokes/anaconda/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
DYLD_LIBRARY_PATH: <not set>
PATH: /Users/ijstokes/anaconda/bin:/Users/ijstokes/anaconda/bin:/Users/ijstokes/anconda3new/anaconda/bin:/Users/ijstokes/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /Users/ijstokes/.continuum
    /Users/ijstokes/Library/Application Support/Anaconda
    /Users/ijstokes/anaconda/licenses
License files (license*.txt):
    /Users/ijstokes/.continuum/license_bundle_trial.txt
               Reading license file : 4
                    Signature valid : 4
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



`$ /Users/ijstokes/anaconda/bin/conda info -a`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python3.5/site-packages/conda/cli/main_info.py", line 324, in execute
        show_info()
      File "_license.pyx", line 360, in _license.show_info (_license.c:10552)
      File "_license.pyx", line 339, in _license.is_license_valid (_license.c:9936)
      File "_license.pyx", line 166, in _license.filter_vendor (_license.c:6216)
    AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1656

**Comment by kalefranz** [comment]
Copied to anaconda-issues, but also fixing the part where conda blows up and shouldn't.

**Comment by kalefranz** [comment]
catching stack trace in #5206
