### ISSUE TITLE
error while cloning env

### ISSUE THREAD

**Issue by br4qua** [conda/conda#4477]
C:\WINDOWS\system32>conda create --name test_2 --clone test_1
Source:      C:\Program Files\Anaconda3\envs\test_1
Destination: C:\Program Files\Anaconda3\envs\test_2
Packages: 7
Files: 6
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py create --name test_2 --clone test_1`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 200, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 69, in clone
        index_args=index_args)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\misc.py", line 306, in clone_env
        force_extract=False, index_args=index_args)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\misc.py", line 93, in explicit
        supplement_index_with_cache(index, ())
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 92, in supplement_index_with_cache
        meta = read_index_json(pkg_dir)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Anaconda3\\pkgs\\biopython-1.68-np111py36_0\\info\\index.json'

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
