### ISSUE TITLE
occurred issue after updating conda

### ISSUE THREAD

**Issue by lovelus** [conda/conda#4484]
C:\Program Files\Anaconda3>conda update --all
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
617, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 92
, in _main
    p, sub_parsers = generate_parser()
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 51
, in generate_parser
    from ..cli import conda_argparse
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py
", line 15, in <module>
    from .common import add_parser_help
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", line
19, in <module>
    from ..core.linked_data import linked_data
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\linked_data.py",
 line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\delete.
py", line 14, in <module>
    from .read import get_json_content
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py
", line 20, in <module>
    from ...models.channel import Channel
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\models\channel.py", l
ine 6, in <module>
    from requests.packages.urllib3.util import Url
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\__init__.py", line
 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line
8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\rand.py", line 12,
in <module>
    from OpenSSL._util import (
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6,
in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global vari
able named 'Cryptography_HAS_SET_ECDH_AUTO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\conda-script.py", line 5, in <module>

    sys.exit(conda.cli.main())
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 16
7, in main
    return conda_exception_handler(_main, *args)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
530, in get_info
    args.func(args, p)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_info.py", li
ne 142, in execute
    from conda.api import get_index
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\api.py", line 1, in <
module>
    from .core.index import get_index
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line
15, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\__init__.py", line
 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line
8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\rand.py", line 12,
in <module>
    from OpenSSL._util import (
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6,
in <module>
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global vari
able named 'Cryptography_HAS_SET_ECDH_AUTO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\Scripts\conda-script.py", line 5, in <module>

    sys.exit(conda.cli.main())
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 16
7, in main
    return conda_exception_handler(_main, *args)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line
530, in get_info
    args.func(args, p)
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_info.py", li
ne 142, in execute
    from conda.api import get_index
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\api.py", line 1, in <
module>
    from .core.index import get_index
  File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line
15, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\__init__.py", line
 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line
8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\rand.py", line 12,
in <module>
    from OpenSSL._util import (
  File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6,
in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "C:\Program Files\Anaconda3\lib\site-packages\cryptography\hazmat\binding
s\openssl\binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global vari
able named 'Cryptography_HAS_SET_ECDH_AUTO'

**Comment by nateGeorge** [comment]
Same problem as here I think https://github.com/conda/conda/issues/4369

**Comment by kalefranz** [comment]
This is usually caused by a gnarly dependency mismatch between requests and a few of its own dependencies.  First thing I'd try is `conda update conda`.  We've tried to force all of the latest requests + dependencies that we believe are all working correctly together.

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```
