### ISSUE TITLE
Error while executing update --all

### ISSUE THREAD

**Issue by vinayakpahalwan** [conda/conda#4489]
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/vinayakpahalwan/anaconda  (writable)
    default environment : /Users/vinayakpahalwan/anaconda
       envs directories : /Users/vinayakpahalwan/anaconda/envs
          package cache : /Users/vinayakpahalwan/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
`$ /Users/vinayakpahalwan/anaconda/bin/conda update --all`

Traceback (most recent call last):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/OpenSSL/SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
        yield
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 380, in read
        data = self._fp.read(amt)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/http/client.py", line 448, in read
        n = self.readinto(b)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/http/client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 271, in recv_into
        raise timeout('The read operation timed out')
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/models.py", line 703, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 432, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 397, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/response.py", line 303, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/requests/models.py", line 710, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/Users/vinayakpahalwan/anaconda/pkgs/matplotlib-2.0.0-np111py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/vinayakpahalwan/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/Users/vinayakpahalwan/anaconda/pkgs/matplotlib-2.0.0-np111py35_0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by marnunez** [comment]
Bump. Exact same thing, only with

```
               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : c:\ProgramData\Anaconda3  (writable)
    default environment : c:\ProgramData\Anaconda3
       envs directories : c:\ProgramData\Anaconda3\envs
          package cache : c:\ProgramData\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\marcha\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601
```

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.
