### ISSUE TITLE
conda update conda, conda info -a -> failure

### ISSUE THREAD

**Issue by katenie** [conda/conda#4497]
Python version: 3.5.1
Linux version 3.10.0-514.6.1.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Wed Jan 18 13:06:36 UTC 2017

'''
Traceback (most recent call last):
  File "//bin/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//lib/python3.5/site-packages/conda/cli/main.py", line 94, in main
    imported = importlib.import_module(module)
  File "//lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "//lib/python3.5/site-packages/conda/cli/main_list.py", line 18, in <module>
    from ..egg_info import get_egg_info
  File "//lib/python3.5/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "//lib/python3.5/site-packages/conda/misc.py", line 18, in <module>
    from .instructions import RM_FETCHED, FETCH, RM_EXTRACTED, EXTRACT, UNLINK, LINK, SYMLINK_CONDA
  File "//lib/python3.5/site-packages/conda/instructions.py", line 7, in <module>
    from .fetch import fetch_pkg
  File "//lib/python3.5/site-packages/conda/fetch.py", line 26, in <module>
    from .connection import CondaSession, unparse_url, RETRIES
  File "//lib/python3.5/site-packages/conda/connection.py", line 51, in <module>
    python=platform.python_implementation(),
  File "//lib/python3.5/platform.py", line 1332, in python_implementation
    return _sys_version()[0]
  File "//lib/python3.5/platform.py", line 1295, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'
'''

**Comment by katenie** [comment]
issue fixed by following this answer on Stackoverflow: http://stackoverflow.com/a/34155037/7644070 (adding code to `conda/cli/main.py`)
