### ISSUE TITLE
CondaSignalInterrupt error on closing Jupyter notebook

### ISSUE THREAD

**Issue by takluyver** [conda/conda#4503]
People have started to report that when they stop the notebook server with Ctrl-C, they get an exception (see jupyter/notebook#2110).

```
Traceback (most recent call last):
  File "/Users/username/anaconda3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/Users/username/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/username/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/username/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1247, in start
    self.io_loop.start()
  File "/Users/username/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/username/anaconda3/lib/python3.5/site-packages/tornado/ioloop.py", line 862, in start
^C  File "/Users/username/anaconda3/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 122, in poll
    z_events = self._poller.poll(1000*timeout)
  File "/Users/username/anaconda3/lib/python3.5/site-packages/zmq/sugar/poll.py", line 99, in poll
    return zmq_poll(self.sockets, timeout=timeout)
  File "zmq/backend/cython/_poll.pyx", line 123, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2186)
  File "zmq/backend/cython/_poll.pyx", line 116, in zmq.backend.cython._poll.zmq_poll (zmq/backend/cython/_poll.c:2036)
  File "zmq/backend/cython/checkrc.pxd", line 12, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/_poll.c:2418)
  File "/Users/username/anaconda3/lib/python3.5/site-packages/conda/gateways/signals.py", line 15, in conda_signal_handler
    raise CondaSignalInterrupt(signum)
conda.exceptions.CondaSignalInterrupt: Signal interrupt SIGINT
```

**Comment by diego898** [comment]
I'd just like to add (in case its relevant) that before I get this error: I have:

```
^C[I 17:29:45.856 NotebookApp] Shutting down kernels
[I 17:29:51.223 NotebookApp] Kernel shutdown: 8bb5d3c3-9384-4363-ae1b-82d421c8bc1b
```

**Comment by kalefranz** [comment]
In conda 4.3 we had to implement a signal handler so that hitting ctrl-c during an install/uninstall transaction doesn't leave you with a broken environment.  The code is here: https://github.com/conda/conda/blob/4.3.x/conda/gateways/signals.py

We also then had a problem with signals not being passed to subprocesses (#4443), so we attempted to fix that in #4447, which was based on information in http://stackoverflow.com/questions/13593223/making-sure-a-python-script-with-subprocesses-dies-on-sigint

That fix in turn caused a change in pre/post link/unlink script behavior: #4573 
(even though in that case the post-link script was relying on behavior that was never intended to be supported)

So, if anyone has any ideas or advice on how to do all of this better, I'm happy to have the input...

**Comment by kalefranz** [comment]
Actually I see that this exception isn't going through conda's [exception handler](https://github.com/conda/conda/blob/4.3.13/conda/exceptions.py#L589), which means jupyter is somewhere importing something that imports `conda.gateways`, which is where the signal handler is registered.  In that case, I think the most appropriate thing to do is for jupyter to just swallow that exception.

**Comment by kalefranz** [comment]
I've also just created #4730.  It's possibly useful in this situation, but the PR also explains the danger.  Interrupting conda in the middle of this unlink/link transaction has the potential for conda to appear to uninstall itself, or otherwise leave environments completely broken.

**Comment by kalefranz** [comment]
I've continued to iterate on #4730, and I think it'll now completely resolve this issue.  I only invoke the signal handler for the unlink/link transaction, and I put everything back to the way it was when the transaction is complete.

**Comment by Tehada** [comment]
Any idea how to fix crash while closing with ctrl+c?

**Comment by kalefranz** [comment]
Conda now for sure detaches signal handlers when it doesn't need them anymore.  While we have other signal handler issues still, I think this one can at least be safely closed.
