### ISSUE TITLE
Error installing htop

### ISSUE THREAD

**Issue by abalter** [conda/conda#4505]
```
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /home/.../miniconda3  (writable)
    default environment : /home/.../miniconda3
       envs directories : /home/.../miniconda3/envs
          package cache : /home/.../miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
            config file : /home/users/balter/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.13.0 CPython/3.5.3 Linux/2.6.32-504.12.2.el6.x86_64 CentOS/6.5 glibc/2.12
                UID:GID : 4296:3010



`$ /home/.../miniconda3/bin/conda install htop`




    Traceback (most recent call last):
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 401, in <listcomp>
        for url in urls]
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 141, in func
        res = f(*args, **kwargs)
      File "/home/.../miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/.../miniconda3/pkgs/cache/ffeee55f.json'

```

**Comment by kalefranz** [comment]
Fixed in conda 4.3.13.
