### ISSUE TITLE
Conda breaks if it can't find the noarch channel

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#4513]
If the `noarch` URL of some custom channel doesn't exist, conda becomes completely broken. The error is:

```
Fetching package metadata ......
WARNING: The remote server could not find the noarch directory for the
requested channel with url: https://zigzah.com/static/conda-pkgs/noarch

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using `conda config --show`.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create `noarch/repodata.json` and associated
`noarch/repodata.json.bz2` files, even if `noarch/repodata.json` is empty.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.0.12
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /home/zah/anaconda3  (writable)
    default environment : /home/zah/anaconda3
       envs directories : /home/zah/anaconda3/envs
          package cache : /home/zah/anaconda3/pkgs
           channel URLs :
                          https://zigzah.com/static/conda-pkgs/linux-64
                          https://zigzah.com/static/conda-pkgs/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : /home/zah/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.13.0 CPython/3.5.3 Linux/4.8.0-32-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000



`$ /home/zah/anaconda3/bin/conda install validphys`




    Traceback (most recent call last):
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 494, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 143, in func
        res = f(*args, **kwargs)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 483, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "/home/zah/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 410, in process_repodata
        opackages = repodata.setdefault('packages', {})
    AttributeError: 'NoneType' object has no attribute 'setdefault'
```

**Comment by mdengler** [comment]
Just got hit by this.  Workaround (pending the real fix in 4359c55) was:

```diff
--- xxx/conda/core/index.py~    2017-01-31 15:55:50.000000000 -0600
+++ xxx/conda/core/index.py     2017-02-03 13:42:13.000000000 -0600
@@ -478,10 +478,11 @@
         return read_local_repodata(cache_path, url, schannel, priority,
                                    mod_etag_headers.get('_etag'), mod_etag_headers.get('_mod'))

-    with open(cache_path, 'w') as fo:
-        json.dump(repodata, fo, indent=2, sort_keys=True, cls=EntityEncoder)
-    process_repodata(repodata, url, schannel, priority)
-    write_pickled_repodata(cache_path, repodata)
+    if repodata is not None:
+        with open(cache_path, 'w') as fo:
+            json.dump(repodata, fo, indent=2, sort_keys=True, cls=EntityEncoder)
+        process_repodata(repodata, url, schannel, priority)
+        write_pickled_repodata(cache_path, repodata)
     return repodata
```
