### ISSUE TITLE
can't finish the " conda create --name=IntroToTensorFlow Python=3 anaconda"

### ISSUE THREAD

**Issue by Heyjoy** [conda/conda#4514]
Hello,

when I running the "conda create --name=IntroToTensorFlow Python=3 anaconda" at win10 Terminal 
it stuck in somehow, and I break the process with "ctrl+c" and now when I running the command again have followed problem: 

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : D:\APP\anaconda3  (writable)
    default environment : D:\APP\anaconda3
       envs directories : D:\APP\anaconda3\envs
          package cache : D:\APP\anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\heyjoy\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ D:\APP\anaconda3\Scripts\conda-script.py create --name=IntroToTensorFlow Python=3 anaconda`

    Traceback (most recent call last):
      File "D:\APP\anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\APP\anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "D:\APP\anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "D:\APP\anaconda3\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\APP\anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "D:\APP\anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "D:\APP\anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "D:\APP\anaconda3\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "D:\APP\anaconda3\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "D:\APP\anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "D:\APP\anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'D:\\APP\\anaconda3\\pkgs\\networkx-1.11-py36_0\\info\\index.json'

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
