### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__context__'

### ISSUE THREAD

**Issue by dr-leo** [conda/conda#4519]
Hi,

on Win7 64bit, the following error occurs, also with conda 4.3.9 and other Python versions:

(py2) C:\Users\stefan\Documents\dev>conda install -c alcibiade pandasdmx
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\stefan\Anaconda3\envs\py2:

The following NEW packages will be INSTALLED:

    pandasdmx: 0.6-py27_0 alcibiade

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
@
    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.2
         python version : 3.4.5.final.0
       requests version : 2.12.4
       root environment : C:\Users\stefan\Anaconda3  (writable)
    default environment : C:\Users\stefan\Anaconda3\envs\py2
       envs directories : C:\Users\stefan\Anaconda3\envs
          package cache : C:\Users\stefan\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/alcibiade/win-32
                          https://conda.anaconda.org/alcibiade/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.4.5 Windows/7 Wi
ndows/6.1.7601

`$ C:\Users\stefan\Anaconda3\Scripts\conda-script.py install -c alcibiade pandas
dmx`

    Traceback (most recent call last):
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\exceptions.py", li
ne 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\cli\main.py", line
 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\cli\main_install.p
y", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\cli\install.py", l
ine 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\plan.py", line 837
, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\instructions.py",
line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\instructions.py",
line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\core\link.py", lin
e 255, in execute
        self.verify()
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\core\link.py", lin
e 243, in verify
        self.num_unlink_pkgs),
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\core\link.py", lin
e 240, in <genexpr>
        exceptions = tuple(exc for exc in concatv(
      File "C:\Users\stefan\Anaconda3\lib\site-packages\conda\core\link.py", lin
e 188, in _verify_individual_level
        log.debug(format_exc())
      File "C:\Users\stefan\Anaconda3\lib\traceback.py", line 256, in format_exc

        return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chai
n))
      File "C:\Users\stefan\Anaconda3\lib\traceback.py", line 181, in format_exc
eption
        return list(_format_exception_iter(etype, value, tb, limit, chain))
      File "C:\Users\stefan\Anaconda3\lib\traceback.py", line 146, in _format_ex
ception_iter
        for value, tb in values:
      File "C:\Users\stefan\Anaconda3\lib\traceback.py", line 125, in _iter_chai
n
        context = exc.__context__
    AttributeError: 'NoneType' object has no attribute '__context__'

**Comment by kalefranz** [comment]
This has been fixed.
