### ISSUE TITLE
error while upgrading anaconda !

### ISSUE THREAD

**Issue by ghost** [conda/conda#4528]
platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Users\Kamal\Anaconda3  (writable)
    default environment : C:\Users\Kamal\Anaconda3
       envs directories : C:\Users\Kamal\Anaconda3\envs
          package cache : C:\Users\Kamal\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Kamal\Anaconda3\Scripts\conda-script.py update anaconda`

    Traceback (most recent call last):
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\Kamal\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Kamal\\Anaconda3\\pkgs\\qt-5.6.2-vc14_3\\info\\index.json'

**Comment by etpalmer63** [comment]
I am having the same issue. For me its easy to recreate. Simply try the command: conda update qt

My output is included below:
PS C:\WINDOWS\system32> conda update qt
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Program Files\Anaconda3:

The following packages will be UPDATED:

    jpeg:    8d-vc14_2     [vc14] --> 9b-vc14_0     [vc14]
    libpng:  1.6.22-vc14_0 [vc14] --> 1.6.27-vc14_0 [vc14]
    libtiff: 4.0.6-vc14_2  [vc14] --> 4.0.6-vc14_3  [vc14]
    pillow:  3.3.1-py35_0  --> 4.0.0-py35_0
    pyqt:    5.6.0-py35_0  --> 5.6.0-py35_2
    qt:      5.6.0-vc14_0  [vc14] --> 5.6.2-vc14_3  [vc14]

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.2 Windows/10 Windows/10.0.14393



`$ C:\Program Files\Anaconda3\Scripts\conda-script.py update qt`




    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 122, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 122, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 72, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 95, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Anaconda3\\pkgs\\qt-5.6.2-vc14_3\\info\\
index.json'
