### ISSUE TITLE
AttributeError in conda info and most other conda commands

### ISSUE THREAD

**Issue by jonathanegol** [conda/conda#4531]
`$ /Users/jonathan/anaconda/bin/conda info`

    Traceback (most recent call last):
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 211, in execute
        channels = list(prioritize_channels(channels).keys())
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 432, in prioritize_channels
        channel = Channel(chn)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 160, in __call__
        c = Channel._cache_[value] = Channel.from_value(value)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 226, in from_value
        if value in context.custom_multichannels:
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 362, in custom_multichannels
        ) for name, urls in iteritems(reserved_multichannel_urls)
      File "/Users/jonathan/anaconda/lib/python2.7/collections.py", line 69, in __init__
        self.__update(*args, **kwds)
      File "/Users/jonathan/anaconda/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 362, in <genexpr>
        ) for name, urls in iteritems(reserved_multichannel_urls)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 361, in <genexpr>
        Channel.make_simple_channel(self.channel_alias, url) for url in urls)
      File "/Users/jonathan/anaconda/lib/python2.7/site-packages/conda/models/channel.py", line 243, in make_simple_channel
        location, name = Url(host=url_parts.host, port=url_parts.port).url, url_parts.path
    AttributeError: 'Url' object has no attribute 'url'
****

**Comment by jonathanegol** [comment]
I have two macs one has this error other doesn't no difference in environment I can detect but assume it's my problem
