### ISSUE TITLE
Maximum recursion depth in environment creation

### ISSUE THREAD

**Issue by DavidMertz** [conda/conda#4537]
```bash
537-training-course-advanced_python % conda env create
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .................
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.2
       conda is private : False
      conda-env version : 4.3.2
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /Users/dmertz/anaconda3  (writable)
    default environment : /Users/dmertz/anaconda3
       envs directories : /Users/dmertz/anaconda3/envs
          package cache : /Users/dmertz/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/anaconda-mosaic/osx-64
                          https://conda.anaconda.org/anaconda-mosaic/noarch
                          https://conda.anaconda.org/R/osx-64
                          https://conda.anaconda.org/R/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/dmertz/.condarc
           offline mode : False
             user-agent : conda/4.3.2 requests/2.12.4 CPython/3.5.2 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 502:20



`$ /Users/dmertz/anaconda3/bin/conda-env create`




    Traceback (most recent call last):
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 516, in install_actions_list
        for dists_by_prefix in required_solves]
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 516, in <listcomp>
        for dists_by_prefix in required_solves]
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 662, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 832, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 886, in solve
        self.find_conflicts(specs)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 364, in find_conflicts
        ndeps = set(self.invalid_chains(ms, filter))
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 273, in chains_
        for x in chains_(m2, names):
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.
[... lots more line 273 ...]
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 273, in chains_
        for x in chains_(m2, names):
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 266, in chains_
        if self.valid(spec, filter) or spec.name in names:
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 245, in valid
        result = v_(spec_or_dist)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 232, in v_
        return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fkey_(spec)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 235, in v_ms_
        return ms.optional or any(v_fkey_(fkey) for fkey in self.find_matches(ms))
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 235, in <genexpr>
        return ms.optional or any(v_fkey_(fkey) for fkey in self.find_matches(ms))
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/resolve.py", line 239, in v_fkey_
        val = filter.get(dist)
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/models/dist.py", line 243, in __hash__
        return hash(self.__key__())
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/models/dist.py", line 224, in __key__
        return self.channel, self.dist_name, self.with_features_depends
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 414, in __get__
        if val is None and not self.nullable:
      File "/Users/dmertz/anaconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 485, in nullable
        return self.is_nullable
    RecursionError: maximum recursion depth exceeded
```
[environment.zip](https://github.com/conda/conda/files/753452/environment.zip)

**Comment by kalefranz** [comment]
Is the problem still there with conda 4.3.9?

**Comment by DavidMertz** [comment]
I had done a `conda update conda`, but it didn't pull in 4.3.9 on my older installation (not *that* old).  But I just nuked `~/anaconda3` and reinstalled the latest, and I can update to 4.3.9.  My environment had an incompatibility (which is another smaller problem itself).  I figured it out by manually walking through installation of the various things in the spec.

With 4.3.9 we indeed do get a reasonable message rather than a `RecursionError`:

```bash
527-tmp % conda env create
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .................
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - nb_conda -> _nb_ext_conf -> nb_anacondacloud -> python 2.7* -> openssl 1.0.1*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by DavidMertz** [comment]
Note that I *do* still need to do the update to conda after install Anaconda 4.3.0, so this could bit someone who installs "the latest" Anaconda.

**Comment by kalefranz** [comment]
Thanks for the extra info David. I'll see what I can figure out tomorrow.

**Comment by kalefranz** [comment]
Pretty sure we've resolved all related issues at this point.
