### ISSUE TITLE
Fetching package metadata: .An unexpected error has occurred

### ISSUE THREAD

**Issue by r-chris** [conda/conda#4538]
I have seen similar issues on here and the suggestions were to do:
`CONDA_SSL_VERIFY=false conda`

*My main question here is*: **Can I stop conda from having to connect** and `Fetch package metadata`?
I am just trying to install some pre-downloaded packages would prefer not to have to rely on my internet connection for that...

    Installing click-3.3-py27_0.tar.bz2
    Fetching package metadata: .An unexpected error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at:

```
Traceback (most recent call last):
  File "/opt/apps/bd/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/cli/main.py", line 199, in args_func
    args.func(args, p)
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/cli/main_install.py", line 46, in execute
    install.install(args, parser, 'install')
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/cli/install.py", line 221, in install
    json=args.json)
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/cli/common.py", line 413, in get_index_trap
    return get_index(*args, **kwargs)
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/api.py", line 40, in get_index
    unknown=unknown)
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/utils.py", line 77, in __call__
    value = self.func(*args, **kw)
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/fetch.py", line 170, in fetch_index
    use_cache=use_cache, session=session)), reversed(channel_urls))
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/fetch.py", line 170, in <lambda>
    use_cache=use_cache, session=session)), reversed(channel_urls))
  File "/opt/apps/bd/lib/python2.7/site-packages/conda/fetch.py", line 79, in fetch_repodata
    verify=config.ssl_verify)
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/sessions.py", line 456, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/sessions.py", line 179, in resolve_redirects
    allow_redirects=False,
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r.content
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/models.py", line 694, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/models.py", line 627, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 240, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/opt/apps/bd/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 187, in read
    data = self._fp.read(amt)
  File "/opt/apps/bd/lib/python2.7/httplib.py", line 543, in read
    return self._read_chunked(amt)
  File "/opt/apps/bd/lib/python2.7/httplib.py", line 612, in _read_chunked
    value.append(self._safe_read(chunk_left))
  File "/opt/apps/bd/lib/python2.7/httplib.py", line 658, in _safe_read
    chunk = self.fp.read(min(amt, MAXAMOUNT))
  File "/opt/apps/bd/lib/python2.7/socket.py", line 380, in read
    data = self._sock.recv(left)
  File "/opt/apps/bd/lib/python2.7/ssl.py", line 246, in recv
    return self.read(buflen)
  File "/opt/apps/bd/lib/python2.7/ssl.py", line 165, in read
    return self._sslobj.read(len)
socket.error: [Errno 104] Connection reset by peer
[ERROR] Failure in: Installing dependency: click-3.3-py27_0.tar.bz2
```

This error disappeared when trying to reproduce it.

**Comment by kalefranz** [comment]
conda config --set offline true

**Comment by r-chris** [comment]
Thanks, maybe I am on an older `conda` version, but I get: 
`conda config: error: argument --set: invalid choice: 'offline:' (choose from 'always_yes', 'allow_softlinks', 'changeps1', 'use_pip', 'binstar_upload', 'binstar_personal', 'show_channel_urls', 'allow_other_channels', 'ssl_verify', 'yes', 'no', 'on', 'off', 'true', 'false')`

**Comment by r-chris** [comment]
```
conda -v
conda 3.6.0
```

**Comment by kalefranz** [comment]
conda 3.6.0 is VERY old.  There have been somewhere around 110 releases since.
