### ISSUE TITLE
Update of Conda and Anaconda leaves ipython in odd state

### ISSUE THREAD

**Issue by empirical-bayesian** [conda/conda#4551]
A standard update of Conda and then Anaconda left ipython in an odd state where it could not find Anaconda libraries ...

```
Jupyter QtConsole 4.0.1
DEPRECATED: IPython.core.usage.default_gui_banner is deprecated and will be removed
Python 3.4.3 |Anaconda custom (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.

IPython 5.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import numpy as np
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-4ee716103900> in <module>()
----> 1 import numpy as np

C:\Anaconda3\lib\site-packages\numpy\__init__.py in <module>()
    168         return loader(*packages, **options)
    169 
--> 170     from . import add_newdocs
    171     __all__ = ['add_newdocs',
    172                'ModuleDeprecationWarning',

C:\Anaconda3\lib\site-packages\numpy\add_newdocs.py in <module>()
     11 from __future__ import division, absolute_import, print_function
     12 
---> 13 from numpy.lib import add_newdoc
     14 
     15 ###############################################################################

C:\Anaconda3\lib\site-packages\numpy\lib\__init__.py in <module>()
     16 
     17 from . import scimath as emath
---> 18 from .polynomial import *
     19 #import convertcode
     20 from .utils import *

C:\Anaconda3\lib\site-packages\numpy\lib\polynomial.py in <module>()
     17 from numpy.lib.function_base import trim_zeros, sort_complex
     18 from numpy.lib.type_check import iscomplex, real, imag
---> 19 from numpy.linalg import eigvals, lstsq, inv
     20 
     21 class RankWarning(UserWarning):

C:\Anaconda3\lib\site-packages\numpy\linalg\__init__.py in <module>()
     49 from .info import __doc__
     50 
---> 51 from .linalg import *
     52 
     53 from numpy.testing import Tester

C:\Anaconda3\lib\site-packages\numpy\linalg\linalg.py in <module>()
     27     )
     28 from numpy.lib import triu, asfarray
---> 29 from numpy.linalg import lapack_lite, _umath_linalg
     30 from numpy.matrixlib.defmatrix import matrix_power
     31 from numpy.compat import asbytes

ImportError: DLL load failed: The specified module could not be found.
```

Then, an uninstall of ipython and a reinstall attempt resulted in this:

```
C:\Anaconda3>conda install ipython
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Anaconda3:

The following NEW packages will be INSTALLED:

    ipython: 5.1.0-py34_0

Proceed ([y]/n)? y

menuinst Exception:Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 141, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda${PY_VER} ${PLATFORM}\IPython.lnk' - error 0x80070005

```
In fact, no version of ipython appears to be able to be installed ... a bug in the conda package management?

```
C:\Anaconda3>conda install ipython=4.0.1
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\Anaconda3:

The following NEW packages will be INSTALLED:

    ipython: 4.0.1-py34_0

Proceed ([y]/n)? y

menuinst Exception:Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 141, in make_menu
    menuinst.install(join(prefix, win_path_ok(file_path)), remove, prefix)
  File "C:\Anaconda3\lib\site-packages\menuinst\__init__.py", line 42, in install
    ShortCut(m, sc, prefix=prefix).create()
  File "C:\Anaconda3\lib\site-packages\menuinst\win32.py", line 133, in create
    u'' + icon,
OSError: Failed to create shortcut 'C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Anaconda${PY_VER} ${PLATFORM}\IPython.lnk' - error 0x80070005

C:\Anaconda3>


```

**Comment by empirical-bayesian** [comment]
yes, it looks like it's the installer ... doesn't seem to have values for ${PY_VER} and ${PLATFORM} in the installation.

**Comment by kalefranz** [comment]
What version of conda was this?  `conda info`?

**Comment by kalefranz** [comment]
I believe the issues here have been fixed in recent versions of conda.  Latest is 4.3.17.
