### ISSUE TITLE
Cloning conda environment keeps failing 

### ISSUE THREAD

**Issue by rjames-at-rwjames** [conda/conda#4555]
Hello, I am trying to clone a conda environment from one machine to another. I have tried two approaches suggested here: https://conda.io/docs/using/envs.html#change-environments-activate-deactivate. One with a .yml file and one with the explicit list of specifications. Both failed. The error from the explicit attempt is below.

Any help appreciated, thank you!

An unexpected error has occurred.                     
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /etc/skel/miniconda2  (writable)
    default environment : /etc/skel/miniconda2/envs/oldleno
       envs directories : /etc/skel/miniconda2/envs
          package cache : /etc/skel/miniconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /etc/skel/miniconda2/envs/oldleno/bin/conda create --name bras2392python --file spec-file_bras2392python.txt`

    Traceback (most recent call last):
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 191, in install
        explicit(specs, prefix, verbose=not context.quiet, index_args=index_args)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/misc.py", line 187, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/install.py", line 803, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "/etc/skel/miniconda2/lib/python2.7/site-packages/conda/common/disk.py", line 144, in exp_backoff_fn
        return fn(*args, **kwargs)
    OSError: [Errno 39] Directory not empty

**Comment by scw** [comment]
Once you've had one failure, you probably are left with a (partially) copied set of packages at the destination. The error message you included shows that it can't write to the location -- try deleting the destination directory, and rerun the command to show the actual error (the one it hits the first time).

**Comment by rjames-at-rwjames** [comment]
Thanks so much for your help - I ended up setting up a new environment from scratch, but it seems to be working now.
