### ISSUE TITLE
An error occurred while installing package 'defaults::qt-5.6.2-vc14_3'. 

### ISSUE THREAD

**Issue by hashware** [conda/conda#4565]
(vpy35) C:\Users\John>conda install qt -v  
Fetching package metadata .............  
Solving package specifications: .  
  
Package plan for installation in environment C:\Anaconda3\envs\vpy35:  
  
The following NEW packages will be INSTALLED:  
  
    qt: 5.6.2-vc14_3 [vc14]  
  
Proceed ([y]/n)?  
  
()  
  
===> LINKING PACKAGE: defaults::qt-5.6.2-vc14_3 <===  
  prefix=C:\Anaconda3\envs\vpy35  
  source=C:\Anaconda3\pkgs\qt-5.6.2-vc14_3  
  
  
An error occurred while installing package 'defaults::qt-5.6.2-vc14_3'.  
UnicodeDecodeError('utf-8', b'\xd2\xd1\xb8\xb4\xd6\xc6         1 \xb8\xf6\xce\xc4\xbc\xfe\xa1\xa3\r\n', 0, 1, 'invalid c  
ontinuation byte')  
Attempting to roll back.  
  
  
===> REVERSING PACKAGE LINK: defaults::qt-5.6.2-vc14_3 <===  
  prefix=C:\Anaconda3\envs\vpy35  
  
  
An unexpected error has occurred.  
Please consider posting the following information to the  
conda GitHub issue tracker at:  
  
    https://github.com/conda/conda/issues  
  
  
  
overtaking stderr and stdout  
  
stderr and stdout yielding back  
  
Current conda install:  
  
               platform : win-64  
          conda version : 4.3.9  
       conda is private : False  
      conda-env version : 4.3.9  
    conda-build version : not installed  
         python version : 3.6.0.final.0  
       requests version : 2.12.4  
       root environment : C:\Anaconda3  (writable)  
    default environment : C:\Anaconda3\envs\vpy35  
       envs directories : C:\Anaconda3\envs  
          package cache : C:\Anaconda3\pkgs  
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64  
                          https://conda.anaconda.org/anaconda-fusion/noarch  
                          https://repo.continuum.io/pkgs/free/win-64  
                          https://repo.continuum.io/pkgs/free/noarch  
                          https://repo.continuum.io/pkgs/r/win-64  
                          https://repo.continuum.io/pkgs/r/noarch  
                          https://repo.continuum.io/pkgs/pro/win-64  
                          https://repo.continuum.io/pkgs/pro/noarch  
                          https://repo.continuum.io/pkgs/msys2/win-64  
                          https://repo.continuum.io/pkgs/msys2/noarch  
            config file : C:\Users\John\.condarc  
           offline mode : False  
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601  
  
  
  
`$ C:\Anaconda3\Scripts\conda-script.py install qt -v`  
  
  
  
  
    Traceback (most recent call last):  
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 309, in _execute_actions  
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')  
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 480, in run_script  
        subprocess_call(command_args, env=env)  
      File "C:\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 61, in subprocess_call  
        return Response(ensure_text_type(stdout), ensure_text_type(stderr), int(rc))  
      File "C:\Anaconda3\lib\site-packages\conda\common\compat.py", line 155, in ensure_text_type  
        return value.decode('utf-8') if hasattr(value, 'decode') else value  
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte  
  
    During handling of the above exception, another exception occurred:  
  
    Traceback (most recent call last):  
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 262, in execute  
        pkg_data, actions)  
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 326, in _execute_actions  
        reverse_excs,  
    conda.CondaMultiError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte  
  
  
    During handling of the above exception, another exception occurred:  
  
    Traceback (most recent call last):  
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler  
        return_value = func(*args, **kwargs)  
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main  
        exit_code = args.func(args, p)  
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute  
        install(args, parser, 'install')  
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in install  
        execute_actions(actions, index, verbose=not context.quiet)  
      File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions  
        execute_instructions(plan, index, verbose)  
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions  
        cmd(state, arg)  
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD  
        txn.execute()  
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 278, in execute  
        rollback_excs,  
    conda.CondaMultiError: 'utf-8' codec can't decode byte 0xd2 in position 0: invalid continuation byte

**Comment by joelkim** [comment]
I had the same problem, and found the reason. check #4567

**Comment by kalefranz** [comment]
Fixed in conda 4.3.12.
