### ISSUE TITLE
An unexpected error happened when I install pandas in Anaconda

### ISSUE THREAD

**Issue by BenBenBenXiao** [conda/conda#4581]
Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Administrator\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.10586

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install pandas-datareader`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'

**Comment by cjliux** [comment]
the same problem as you have
In my case, where the command is 'conda install pycuda', it outputs:
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : E:\ProgramData\Anaconda2  (writable)
    default environment : E:\ProgramData\Anaconda2
       envs directories : E:\ProgramData\Anaconda2\envs
          package cache : E:\ProgramData\Anaconda2\pkgs
           channel URLs : https://conda.anaconda.org/'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/'/win-64
                          https://conda.anaconda.org/'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/'/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Asus\.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.10586



`$ E:\ProgramData\Anaconda2\Scripts\conda-script.py install pycuda`




    Traceback (most recent call last):
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 143, in func
        res = f(*args, **kwargs)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 483, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "E:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 410, in process_repodata
        opackages = repodata.setdefault('packages', {})
    AttributeError: 'NoneType' object has no attribute 'setdefault'

**Comment by dipanarya** [comment]
I am also facing same error.please suggest steps if your problem is resolved:



(dlnd) C:\Users\Dipan Arya\Desktop\uda\dlnd-your-first-network\DLND-your-first-n
etwork>conda install pandas
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment C:\ProgramData\Anaconda3\envs\dlnd:


The following NEW packages will be INSTALLED:

    mkl:             2017.0.1-0
    numpy:           1.11.3-py36_0
    pandas:          0.19.2-np111py36_1
    python-dateutil: 2.6.0-py36_0
    pytz:            2016.10-py36_0
    six:             1.10.0-py36_0

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-32
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3\envs\dlnd
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Dipan Arya\AppData\Local\conda\conda\envs
                          C:\Users\Dipan Arya\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Dipan Arya\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601



`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install pandas`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line
137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py
", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 825,
 in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", l
ine 258, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", l
ine 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dist
s, link_dists)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line
 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line
 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.
py", line 85, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.
py", line 104, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi
:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ProgramData\\An
aconda3\\pkgs\\pandas-0.19.2-np111py36_1\\info\\index.json'


(dlnd) C:\Users\Dipan Arya\Desktop\uda\dlnd-your-first-network\DLND-your-first-n
etwork>

**Comment by cjliux** [comment]
It seems that's because you have changed the setting of `conda` or the original setting doesn't work. The configuration file of `conda` is named as `.condarc`, which can be found in your account path. In my case, it's in `C:\Users\Asus`. You can search for information about the meaning of the content of this file on the internet. The content that works for me is:

ssl_verify: 'True'
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - anaconda-fusion
  - defaults
show_channel_urls: true

May that help you!

**Comment by kalefranz** [comment]
This was fixed in conda 4.3.13. Right click on the Anaconda prompt ivon, choose "Run as administrator," then `conda update conda`.
