### ISSUE TITLE
FileNotFoundError while updating Anaconda3

### ISSUE THREAD

**Issue by amorgun** [conda/conda#4586]
Anaconda asked me to post it here.
`conda update conda` works fine but `conda update anaconda` fails.
I did try `conda clean --packages` as suggested at https://github.com/conda/conda/issues/4459 but it did not change anything. 
Output:
```
(F:\Anaconda3) C:\Windows\System32>conda update anaconda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment F:\Anaconda3:

The following NEW packages will be INSTALLED:

    chardet:            2.3.0-py35_0
    isort:              4.2.5-py35_0
    numpydoc:           0.6.0-py35_0

The following packages will be UPDATED:

    anaconda:           4.2.0-np111py35_0  --> 4.3.0-np111py35_0
    anaconda-client:    1.5.1-py35_0       --> 1.6.0-py35_0
    anaconda-navigator: 1.3.1-py35_0       --> 1.4.3-py35_0
    astroid:            1.4.7-py35_0       --> 1.4.9-py35_0
    astropy:            1.2.1-np111py35_0  --> 1.3-np111py35_0
    beautifulsoup4:     4.5.1-py35_0       --> 4.5.3-py35_0
    bokeh:              0.12.2-py35_0      --> 0.12.4-py35_0
    boto:               2.42.0-py35_0      --> 2.45.0-py35_0
    bottleneck:         1.1.0-np111py35_0  --> 1.2.0-np111py35_0
    cffi:               1.7.0-py35_0       --> 1.9.1-py35_0
    click:              6.6-py35_0         --> 6.7-py35_0
    cloudpickle:        0.2.1-py35_0       --> 0.2.2-py35_0
    contextlib2:        0.5.3-py35_0       --> 0.5.4-py35_0
    cryptography:       1.5-py35_0         --> 1.7.1-py35_0
    curl:               7.49.0-vc14_0      [vc14] --> 7.52.1-vc14_0      [vc14]
    cython:             0.24.1-py35_0      --> 0.25.2-py35_0
    cytoolz:            0.8.0-py35_0       --> 0.8.2-py35_0
    dask:               0.11.0-py35_0      --> 0.13.0-py35_0
    datashape:          0.5.2-py35_0       --> 0.5.4-py35_0
    decorator:          4.0.10-py35_0      --> 4.0.11-py35_0
    docutils:           0.12-py35_2        --> 0.13.1-py35_0
    flask:              0.11.1-py35_0      --> 0.12-py35_0
    flask-cors:         2.1.2-py35_0       --> 3.0.2-py35_0
    freetype:           2.5.5-vc14_1       [vc14] --> 2.5.5-vc14_2       [vc14]
    gevent:             1.1.2-py35_0       --> 1.2.1-py35_0
    greenlet:           0.4.10-py35_0      --> 0.4.11-py35_0
    idna:               2.1-py35_0         --> 2.2-py35_0
    ipykernel:          4.5.0-py35_0       --> 4.5.2-py35_0
    ipywidgets:         5.2.2-py35_0       --> 5.2.2-py35_1
    jdcal:              1.2-py35_1         --> 1.3-py35_0
    jinja2:             2.8-py35_1         --> 2.9.4-py35_0
    jpeg:               8d-vc14_2          [vc14] --> 9b-vc14_0          [vc14]
    jupyter_core:       4.2.0-py35_0       --> 4.2.1-py35_0
    lazy-object-proxy:  1.2.1-py35_0       --> 1.2.2-py35_0
    libpng:             1.6.22-vc14_0      [vc14] --> 1.6.27-vc14_0      [vc14]
    libtiff:            4.0.6-vc14_2       [vc14] --> 4.0.6-vc14_3       [vc14]
    lxml:               3.6.4-py35_0       --> 3.7.2-py35_0
    matplotlib:         1.5.3-np111py35_0  --> 2.0.0-np111py35_0
    menuinst:           1.4.1-py35_0       --> 1.4.4-py35_0
    mkl:                11.3.3-1           --> 2017.0.1-0
    mkl-service:        1.1.2-py35_2       --> 1.1.2-py35_3
    multipledispatch:   0.4.8-py35_0       --> 0.4.9-py35_0
    nbformat:           4.1.0-py35_0       --> 4.2.0-py35_0
    nltk:               3.2.1-py35_0       --> 3.2.2-py35_0
    notebook:           4.2.3-py35_0       --> 4.3.1-py35_1
    numba:              0.30.0-np111py35_0 --> 0.30.1-np111py35_0
    numexpr:            2.6.1-np111py35_0  --> 2.6.1-np111py35_2
    numpy:              1.11.1-py35_1      --> 1.11.3-py35_0
    openpyxl:           2.3.2-py35_0       --> 2.4.1-py35_0
    openssl:            1.0.2j-vc14_0      [vc14] --> 1.0.2k-vc14_0      [vc14]
    pandas:             0.18.1-np111py35_0 --> 0.19.2-np111py35_1
    partd:              0.3.6-py35_0       --> 0.3.7-py35_0
    path.py:            8.2.1-py35_0       --> 10.0-py35_0
    pathlib2:           2.1.0-py35_0       --> 2.2.0-py35_0
    pillow:             3.3.1-py35_0       --> 4.0.0-py35_0
    pip:                8.1.2-py35_0       --> 9.0.1-py35_1
    prompt_toolkit:     1.0.3-py35_0       --> 1.0.9-py35_0
    psutil:             4.3.1-py35_0       --> 5.0.1-py35_0
    py:                 1.4.31-py35_0      --> 1.4.32-py35_0
    pycparser:          2.14-py35_1        --> 2.17-py35_0
    pycrypto:           2.6.1-py35_4       --> 2.6.1-py35_5
    pycurl:             7.43.0-py35_0      --> 7.43.0-py35_2
    pyflakes:           1.3.0-py35_0       --> 1.5.0-py35_0
    pylint:             1.5.4-py35_1       --> 1.6.4-py35_1
    pyqt:               5.6.0-py35_0       --> 5.6.0-py35_2
    pytest:             2.9.2-py35_0       --> 3.0.5-py35_0
    python-dateutil:    2.5.3-py35_0       --> 2.6.0-py35_0
    pytz:               2016.6.1-py35_0    --> 2016.10-py35_0
    pywin32:            220-py35_1         --> 220-py35_2
    pyzmq:              15.4.0-py35_0      --> 16.0.2-py35_0
    qt:                 5.6.0-vc14_0       [vc14] --> 5.6.2-vc14_3       [vc14]
    qtawesome:          0.3.3-py35_0       --> 0.4.3-py35_0
    qtpy:               1.1.2-py35_0       --> 1.2.1-py35_0
    scikit-learn:       0.17.1-np111py35_1 --> 0.18.1-np111py35_1
    scipy:              0.18.1-np111py35_0 --> 0.18.1-np111py35_1
    sphinx:             1.4.6-py35_0       --> 1.5.1-py35_0
    spyder:             3.0.0-py35_0       --> 3.1.2-py35_0
    sqlalchemy:         1.0.13-py35_0      --> 1.1.5-py35_0
    toolz:              0.8.0-py35_0       --> 0.8.2-py35_0
    tornado:            4.4.1-py35_0       --> 4.4.2-py35_0
    traitlets:          4.3.0-py35_0       --> 4.3.1-py35_0
    werkzeug:           0.11.11-py35_0     --> 0.11.15-py35_0
    wrapt:              1.10.6-py35_0      --> 1.10.8-py35_0
    xlsxwriter:         0.9.3-py35_0       --> 0.9.6-py35_0
    xlwings:            0.10.0-py35_0      --> 0.10.2-py35_0
    xlwt:               1.1.2-py35_0       --> 1.2.0-py35_0

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : F:\Anaconda3  (writable)
    default environment : F:\Anaconda3
       envs directories : F:\Anaconda3\envs
          package cache : F:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.2 Windows/7 Wi
ndows/6.1.7601



`$ F:\Anaconda3\Scripts\conda-script.py update anaconda`




    Traceback (most recent call last):
      File "F:\Anaconda3\lib\site-packages\conda\exceptions.py", line 616, in co
nda_exception_handler
        return_value = func(*args, **kwargs)
      File "F:\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _mai
n
        exit_code = args.func(args, p)
      File "F:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, i
n execute
        install(args, parser, 'update')
      File "F:\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in i
nstall
        execute_actions(actions, index, verbose=not context.quiet)
      File "F:\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_
actions
        execute_instructions(plan, index, verbose)
      File "F:\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in
execute_instructions
        cmd(state, arg)
      File "F:\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in
UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dist
s, link_dists)
      File "F:\Anaconda3\lib\site-packages\conda\core\link.py", line 122, in cre
ate_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "F:\Anaconda3\lib\site-packages\conda\core\link.py", line 122, in <ge
nexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "F:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 72
, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "F:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 95
, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi
:
    FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Anaconda3\\pkgs
\\mkl-2017.0.1-0\\info\\index.json'
```

**Comment by amorgun** [comment]
After removing `pkgs` directory as suggested at https://github.com/conda/conda/issues/4436#issuecomment-275424348 I got a lot more weird errors while updating anaconda, so I just reinstalled my whole anaconda installation.  Anyway now I have the latest version.
