### ISSUE TITLE
'_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by jessegeerts** [conda/conda#4599]
Hi, 

I'm having trouble installing the phy environment. Phy worked perfectly before, but suddenly stopped working, and now when I try to reinstall it, I keep getting the following error:

 AttributeError: '_NamespacePath' object has no attribute 'sort'

Below I copied everything in my command prompt. Any ideas as to how to solve this issue? 

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\phy-env-file

C:\phy-env-file>conda env create -n phy
Fetching package metadata .........
Solving package specifications: ..........
Fetching packages ...
mkl-2017.0.1-0 100% |###############################| Time: 0:00:03  37.95 MB/s
jpeg-8d-vc14_2 100% |###############################| Time: 0:00:00   9.08 MB/s
openssl-1.0.2k 100% |###############################| Time: 0:00:00  23.34 MB/s
tk-8.5.18-vc14 100% |###############################| Time: 0:00:00  23.29 MB/s
zlib-1.2.8-vc1 100% |###############################| Time: 0:00:00  11.32 MB/s
cython-0.25.2- 100% |###############################| Time: 0:00:00  23.86 MB/s
hdf5-1.8.15.1- 100% |###############################| Time: 0:00:00  30.74 MB/s
libpng-1.6.27- 100% |###############################| Time: 0:00:00   8.56 MB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:00  23.68 MB/s
numpy-1.11.3-p 100% |###############################| Time: 0:00:00  27.28 MB/s
pyparsing-2.1. 100% |###############################| Time: 0:00:00   7.39 MB/s
pytz-2016.10-p 100% |###############################| Time: 0:00:00  17.83 MB/s
sip-4.18-py35_ 100% |###############################| Time: 0:00:00  24.66 MB/s
six-1.10.0-py3 100% |###############################| Time: 0:00:00   0.00  B/s
cycler-0.10.0- 100% |###############################| Time: 0:00:00   0.00  B/s
h5py-2.6.0-np1 100% |###############################| Time: 0:00:00  16.79 MB/s
pip-9.0.1-py35 100% |###############################| Time: 0:00:00  22.28 MB/s
python-dateuti 100% |###############################| Time: 0:00:00   7.98 MB/s
qt-4.8.7-vc14_ 100% |###############################| Time: 0:00:01  27.38 MB/s
scipy-0.18.1-n 100% |###############################| Time: 0:00:00  25.39 MB/s
pyqt-4.11.4-py 100% |###############################| Time: 0:00:00  23.16 MB/s
matplotlib-1.5 100% |###############################| Time: 0:00:00  24.93 MB/s
Extracting packages ...
[      COMPLETE      ]|##################################################| 100%
Linking packages ...
        1 file(s) copied.########################################        |  84%
[      COMPLETE      ]|##################################################| 100%
Traceback (most recent call last):
  File "C:\Program Files\Miniconda3\envs\phy\Scripts\pip-script.py", line 3, in
<module>
    import pip
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\__init__.py",
 line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\utils\__init_
_.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 3018, in <module>
    @_call_aside
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "C:\Program Files\Miniconda3\envs\phy\lib\site-packages\pip\_vendor\pkg_r
esources\__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues


Current conda install:

               platform : win-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Miniconda3  (writable)
    default environment : C:\Program Files\Miniconda3
       envs directories : C:\Program Files\Miniconda3\envs
          package cache : C:\Program Files\Miniconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False


`$ C:\Program Files\Miniconda3\Scripts\conda-env-script.py create -n phy`



    Traceback (most recent call last):
      File "C:\Program Files\Miniconda3\lib\site-packages\conda\exceptions.py",
line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda_env\cli\main_cre
ate.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\Program Files\Miniconda3\lib\site-packages\conda_env\installers\p
ip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "C:\Program Files\Miniconda3\lib\site-packages\conda_env\pip_util.py"
, line 30, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').spli
t()[1]
      File "C:\Program Files\Miniconda3\lib\subprocess.py", line 626, in check_o
utput
        **kwargs).stdout
      File "C:\Program Files\Miniconda3\lib\subprocess.py", line 708, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['C:\\Program Files\\Miniconda3\\env
s\\phy\\python.exe', 'C:\\Program Files\\Miniconda3\\envs\\phy\\Scripts\\pip-scr
ipt.py', '-V']' returned non-zero exit status 1


```

**Comment by kalefranz** [comment]
conda update conda pip

**Comment by kalefranz** [comment]
duplicate of #5854
