### ISSUE TITLE
conda crashing (?)

### ISSUE THREAD

**Issue by swails** [conda/conda#4601]
I tried this:

```bash
conda create -n something python=3.5
```

that worked

Then I deleted it, tried it again, and got this:

```bash
    Traceback (most recent call last):
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 491, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 200, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.index.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 494, in fetch_repodata
        touch(cache_path)
      File "/usr/miniconda3/lib/python3.5/site-packages/conda/gateways/disk/update.py", line 64, in touch
        utime(path, None)
    PermissionError: [Errno 13] Permission denied
```

I presume it would work with sudo, but the first time it ran, it added the environment to `$HOME/.conda` (which is where I need it to be).

Any ideas?

Thanks

**Comment by swails** [comment]
This error pops up on conda 4.3.11, but does not on 4.3.9

**Comment by davidfokkema** [comment]
Looks like #4593.

**Comment by swails** [comment]
Sure does!
