### ISSUE TITLE
conda develop ignores the environment's python version

### ISSUE THREAD

**Issue by cubranic** [conda/conda#4605]
When I'm working in a environment that uses Python 2.7, `conda develop tries to install into `lib/python3.5/site-packages`:

```
$ conda create --name py27 python=2
...
$ source activate py27
(py27) $ git clone https://github.com/pypa/sampleproject
(py27) $ cd sampleproject/
(py27) $ type python
python is hashed (/Users/davor/anaconda3/envs/py27/bin/python)
(py27) $ python -V
Python 2.7.13 :: Continuum Analytics, Inc.
(py27) $ conda develop .
Traceback (most recent call last):
  File "/Users/davor/anaconda3/bin/conda-develop", line 6, in <module>
    sys.exit(conda_build.cli.main_develop.main())
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_develop.py", line 72, in main
    return execute(sys.argv[1:])
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_develop.py", line 68, in execute
    build_ext=args.build_ext, clean=args.clean, uninstall=args.uninstall)
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/api.py", line 203, in develop
    return execute(recipe_dir, prefix, no_pth_file, build_ext, clean, uninstall)
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/develop.py", line 191, in execute
    write_to_conda_pth(sp_dir, pkg_path)
  File "/Users/davor/anaconda3/lib/python3.5/site-packages/conda_build/develop.py", line 50, in write_to_conda_pth
    with open(c_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/davor/anaconda3/envs/py27/lib/python3.5/site-packages/conda.pth'
```

Running `pip install -e .` installs (correctly) into `~/anaconda3/envs/py27/lib/python2.7/site-packages/`

**Comment by oulenz** [comment]
I think my issue may have the same cause: running `develop` in an environment that uses 3.6 has no effect because it updates `conda.pth` in `/python3.5`

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1990
