### ISSUE TITLE
Fetching package metadata ...An unexpected error has occurred.

### ISSUE THREAD

**Issue by gatechzhu** [conda/conda#4609]
Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/lijun/anaconda3  (writable)
    default environment : /Users/lijun/anaconda3/envs/tensorflow
       envs directories : /Users/lijun/anaconda3/envs
          package cache : /Users/lijun/anaconda3/pkgs
           channel URLs : https://conda.anaconda.org/condaforge/osx-64
                          https://conda.anaconda.org/condaforge/noarch
                          https://conda.anaconda.org/obspy/osx-64
                          https://conda.anaconda.org/obspy/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/lijun/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.6.0 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

`$ /Users/lijun/anaconda3/envs/tensorflow/bin/conda install -c condaforge tensorflow`

    Traceback (most recent call last):
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 494, in <listcomp>
        for url, schan, pri in tasks]
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 143, in func
        res = f(*args, **kwargs)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 483, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "/Users/lijun/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 410, in process_repodata
        opackages = repodata.setdefault('packages', {})
    AttributeError: 'NoneType' object has no attribute 'setdefault'

**Comment by gatechzhu** [comment]
Never mind. I used the wrong channel name.
