### ISSUE TITLE
unable to launch jupyter notebook

### ISSUE THREAD

**Issue by zxu7** [conda/conda#4610]
cannot jupyter notebook unless using sudo. Any ideas?

Traceback (most recent call last):
  File "/Users/user/anaconda/envs/python3/bin/jupyter-notebook", line 11, in <module>
    sys.exit(main())
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1140, in initialize
    self.init_configurables()
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/notebook/notebookapp.py", line 896, in init_configurables
    parent=self,
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 19, in __init__
    specs = self.find_kernel_specs() or {}
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 129, in find_kernel_specs
    self.conda_info = self._conda_info()
  File "/Users/user/anaconda/envs/python3/lib/python3.5/site-packages/nb_conda_kernels/manager.py", line 29, in _conda_info
    p = subprocess.check_output(["conda", "info", "--json"]
  File "/Users/user/anaconda/envs/python3/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/Users/user/anaconda/envs/python3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['conda', 'info', '--json']' returned non-zero exit status 1

**Comment by kalefranz** [comment]
Seems unfortunate that jupyter hard-fails if conda does.  Guess you should file an issue with them though.  There's not enough information here for me to do anything with.  Maybe if `conda info --json` gave you a stack trace that you could report...
