### ISSUE TITLE
Error while intalled Miniconda3

### ISSUE THREAD

**Issue by qinggegeee** [conda/conda#4616]
Traceback (most recent call last):
  File "E:\Miniconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Miniconda3\lib\site-packages\conda\cli\main.py", line 113, in _main
    imported = importlib.import_module(module)
  File "E:\Python35\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "E:\Miniconda3\lib\site-packages\conda\cli\main_list.py", line 17, in <module>
    from ..egg_info import get_egg_info
  File "E:\Miniconda3\lib\site-packages\conda\egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "E:\Miniconda3\lib\site-packages\conda\misc.py", line 14, in <module>
    from .api import get_index
  File "E:\Miniconda3\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "E:\Miniconda3\lib\site-packages\conda\fetch.py", line 29, in <module>
    from .connection import CondaSession, RETRIES
  File "E:\Miniconda3\lib\site-packages\conda\connection.py", line 60, in <module>
    python=platform.python_implementation(),
  File "E:\Python35\Lib\platform.py", line 1287, in python_implementation
    return _sys_version()[0]
  File "E:\Python35\Lib\platform.py", line 1250, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Miniconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "E:\Miniconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "E:\Miniconda3\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "E:\Miniconda3\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "E:\Miniconda3\lib\site-packages\conda\exceptions.py", line 413, in get_info
    args.func(args, p)
  File "E:\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 156, in execute
    from conda.api import get_index
  File "E:\Miniconda3\lib\site-packages\conda\api.py", line 7, in <module>
    from .fetch import fetch_index
  File "E:\Miniconda3\lib\site-packages\conda\fetch.py", line 29, in <module>
    from .connection import CondaSession, RETRIES
  File "E:\Miniconda3\lib\site-packages\conda\connection.py", line 60, in <module>
    python=platform.python_implementation(),
  File "E:\Python35\Lib\platform.py", line 1287, in python_implementation
    return _sys_version()[0]
  File "E:\Python35\Lib\platform.py", line 1250, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]'

**Comment by qinggegeee** [comment]
uninstall python35 and conda ,reinstall conda ,then install successed. 
I don't know why,but it works ,so  close the issue.
