### ISSUE TITLE
Incorrect signature used when calling to "yaml.load" definition.

### ISSUE THREAD

**Issue by KelSolaar** [conda/conda#4623]
Hi,

This is happening with the following installer: *Anaconda2-4.2.0-Windows-x86_64.exe*

I spotted an issue when working with `.condarc` file which triggers a call to `yaml.load` definition with incorrect signature: https://github.com/conda/conda/blob/master/conda/common/yaml.py#L26

The traceback is as follows:

```python
C:\Users\thomas>activate python-2.7.13
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\main.py", line 154, in main
    activate.main()
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\activate.py", line 160, in main
    prefix = prefix_from_arg(sys.argv[3], shelldict=shelldict)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\cli\activate.py", line 48, in prefix_from_arg
    from conda.base.context import context, locate_prefix_by_name
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\base\context.py", line 561, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\configuration.py", line 707, in __init__
    self._set_search_path(search_path)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\configuration.py", line 725, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\configuration.py", line 367, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files\Anaconda2\lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "C:\Program Files\Anaconda2\lib\_abcoll.py", line 571, in update
    for key, value in other:
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\configuration.py", line 367, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\configuration.py", line 343, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\configuration.py", line 331, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Program Files\Anaconda2\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
TypeError: load() got an unexpected keyword argument 'version'
```
`version` is not an argument that exists in the conda shipped version of *yaml*, changing the offending line to:

> return yaml.load(string, Loader=yaml.RoundTripLoader)

fixes the issue.

Cheers,

Thomas

**Comment by KelSolaar** [comment]
Let me know if you want a PR, should be easy enough to do!

**Comment by kalefranz** [comment]
Conda is updated much more often then the Anaconda installer.  It's probably long-ago fixed.

    conda update conda

If you still have issues, let me know and we'll re-open the ticket.

**Comment by KelSolaar** [comment]
This is not fixed, and I had `conda` up to date, I should have mentioned it.

This is latest `conda` offending line:

> return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")

and the function signature for latest `yaml` package:

> def load(stream, Loader=Loader):

Cheers,

Thomas

**Comment by kalefranz** [comment]
Can you provide the output of `conda info` and `conda list`?  We use `ruamel_yaml`, not `pyyaml` FYI.  https://github.com/conda/conda/blob/4.3.x/conda/common/yaml.py

The `version` kwarg was accurate as of `ruamel_yaml` 0.11.14.  I know there's now a `ruamel.yaml` 0.13.14 and I guess it's possible the signature has changed.

**Comment by KelSolaar** [comment]
@kalefranz : I actually found the reason why it was not working, we are using a tool at work that ships its own version of `ruamel_yaml` in its dependencies and it was added to **PYTHONPATH**. If I remove it from it everything seems to be fine.

Closing this at the moment as it seem to be resolved on my end.
