### ISSUE TITLE
Cloning environment fails with "KeyError: 'python-3.5.2-3.tar.bz2'"

### ISSUE THREAD

**Issue by AllanLRH** [conda/conda#4643]
Cloning an environment fails.
When I try clone with the clone-targeted conda environment active (named _mpl2_), I get a different error message (`KeyError: 'libpng-1.6.23-0.tar.bz2'`), but as in this attempt, where I clone from the conda root environment, I get a KeyError.
The interpreter in the newly create environment seems to work, but is downgraded to Python 2.7.12, rather than 3.5.2 like the cloned environment.

Below is command line output which I hope will prove useful in tracking down the cause of the problem.

### conda info --envs
```
bzg778@paper /lscr_paper/allan/scripts
$ conda info --envs
# conda environments:
#
mpl2                     /lscr_paper/allan/miniconda3/envs/mpl2
msth                     /lscr_paper/allan/miniconda3/envs/msth
root                  *  /lscr_paper/allan/miniconda3
```
### conda create --name mpl2nx2 --clone mpl2
```
bzg778@paper /lscr_paper/allan/scripts
$ conda create --name mpl2nx2 --clone mpl2
Fetching package metadata: ....
src_prefix: '/lscr_paper/allan/miniconda3/envs/mpl2'
dst_prefix: '/lscr_paper/allan/miniconda3/envs/mpl2nx2'
Packages: 134
Files: 2067
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/lscr_paper/allan/miniconda3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 84, in clone
    quiet=quiet, index=index)
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "/lscr_paper/allan/miniconda3/lib/python3.5/site-packages/conda/resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'python-3.5.2-3.tar.bz2'
```
### conda info
```
bzg778@paper /lscr_paper/allan/scripts
$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /lscr_paper/allan/miniconda3  (writable)
  default environment : /lscr_paper/allan/miniconda3
     envs directories : /lscr_paper/allan/miniconda3/envs
        package cache : /lscr_paper/allan/miniconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
### Python path and version info
```
bzg778@paper /lscr_paper/allan/scripts
$ which python
/lscr_paper/allan/miniconda3/bin/python

bzg778@paper /lscr_paper/allan/scripts
$ python --version
Python 3.5.1 :: Continuum Analytics, Inc.

bzg778@paper /lscr_paper/allan/scripts
$ source activate mpl2
discarding /lscr_paper/allan/miniconda3/bin from PATH
prepending /lscr_paper/allan/miniconda3/envs/mpl2/bin to PATH
(mpl2)

bzg778@paper /lscr_paper/allan/scripts
$ which python
/lscr_paper/allan/miniconda3/envs/mpl2/bin/python
(mpl2)

bzg778@paper /lscr_paper/allan/scripts
$ python --version
Python 3.5.2
(mpl2)

bzg778@paper /lscr_paper/allan/scripts
$ source activate mpl2nx2
discarding /lscr_paper/allan/miniconda3/bin from PATH
prepending /lscr_paper/allan/miniconda3/envs/mpl2nx2/bin to PATH
(mpl2nx2)

bzg778@paper /lscr_paper/allan/scripts
$ which python
/usr/bin/python
(mpl2nx2)

bzg778@paper /lscr_paper/allan/scripts
$ python --version
Python 2.7.12
(mpl2nx2)

bzg778@paper /lscr_paper/allan/scripts
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> print("Does the interpreter work? What is {} + {}? It's {}".format(2, 2, 2+2))
Does the interpreter work? What is 2 + 2? It's 4
>>>
```

**Comment by kalefranz** [comment]
Several bugs were fixed with cloning after conda 4.0.5.  `conda update conda`
