### ISSUE TITLE
Permission denied error, when creating conda environment as a non-root user

### ISSUE THREAD

**Issue by wl2776** [conda/conda#4644]
```
username@calc2:~$ conda create -n MBA
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/miniconda2  (read only)
    default environment : /opt/miniconda2
       envs directories : /opt/miniconda2/envs
                          /home/username/.conda/envs
          package cache : /opt/miniconda2/pkgs
                          /home/username/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/username/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/4.4.0-62-generic debian/stretch/sid glibc/2.23
                UID:GID : 1003:1003



`$ /opt/miniconda2/bin/conda create -n MBA`




    Traceback (most recent call last):
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 494, in fetch_repodata
        touch(cache_path)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/update.py", line 64, in touch
        utime(path, None)
    OSError: [Errno 13] Permission denied: '/opt/miniconda2/pkgs/cache/db552c1e.json'


```

**Comment by groutr** [comment]
We are experiencing this issue in an enterprise multi-user setup and it effectively disabled a multi-user setup.  This behavior did not manifest until we upgraded to conda 4.3.11 from conda 4.3.9.

**Comment by davidslac** [comment]
I just tried to update to conda 4.3.11 and got the same error. I was able to downgrade to 4.3.8 and repair.

**Comment by mdehollander** [comment]
I can confirm that downgrading to 4.3.8 creates a working multi-user environment.

**Comment by kalefranz** [comment]
`conda update conda` to 4.3.13. For a multi-user install, you'll need to update conda in a process having the appropriate privileges.

We finally figured out a workable way to test multi-user installs, at least on unix.  Hopefully there should be far fewer multi-user issues at this point.  Targeted regression tests should also be easier to write.

**Comment by edurand** [comment]
Hello,
I'm having the same issue with 4.3.16. Is there a fix available now?
Thanks

**Comment by lfiaschi** [comment]
Hello,
I'm having the same issue with 4.3.167. Is there a fix available now?
Thanks

**Comment by kalefranz** [comment]
If you are having this error and come to this ticket via google, please file a new ticket with your stack trace and `conda info`.

**Comment by rbogle** [comment]
I can confirm that recursively changing group ownership and g+w permission on pkgs/cache folder in the anaconda install will stop the errors for users belonging to that group.

**Comment by aaronpenne** [comment]
This error is caused by permissions like the error message states, but running the suggested command does not work because `repodata_record.json` does not exist yet. The fix for me was to run chown on the conda related directories. Try running the below commands, replacing <YOUR_USER_NAME>

```
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/miniconda3
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/.conda/
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/.condarc/
```

**Comment by RobFirth** [comment]
Thanks @aaronpenne for the fix - I also had to run:
```
sudo chown -R 501:20 /Users/<YOUR_USER_NAME>/anaconda3/
```

**Comment by dimagoldin** [comment]
I would just like to say the above didnt work for me as it does not give sufficient write permissions for the current user.

What worked for me was:
sudo chown -R $USER:$USER ~/miniconda3/
sudo chown -R $USER:$USER ~/.conda/

Just copy paste these 2 (or change miniconda to anaconda if you installed it instead)

**Comment by gabefair** [comment]
I am getting the same issue with Windows 10.  
`Python 3.7.0 (default, Jun 28 2018, 13:15:42)  [GCC 7.2.0]`
`Anaconda3 running  a tensorflow env` 
`tensorflow-gpu            1.12.0                    <pip>`
