### ISSUE TITLE
Package cache error with conda 4.3.12 on win64

### ISSUE THREAD

**Issue by wulmer** [conda/conda#4649]
Following error occurs when I try to create a new environment with conda 4.3.12 on win64:

    `$ C:\Program Files\Anaconda3\Scripts\conda-script.py create -p C:\hub\temp\venv python=3.5`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 558, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 547, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 520, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 520, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 144, in func
        res = f(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 464, in fetch_repodata
        cache_path = join(cache_dir or create_cache_dir(), cache_fn_url(url))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 596, in create_cache_dir
        assert pkgs_dir == context.pkgs_dirs[0], (pkgs_dir, context.pkgs_dirs)
    AssertionError: ('C:\\Users\\xxx\\AppData\\Local\\conda\\conda\\pkgs', ('C:\\Program Files\\Anaconda3\\pkgs', 'C:\\Users\\xxx\\AppData\\Local\\conda\\conda\\pkgs'))

Conda info is:

               platform : win-64
          conda version : 4.3.12
       conda is private : False
      conda-env version : 4.3.12
    conda-build version : 2.1.4
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
                          C:\Users\xxx\AppData\Local\conda\conda\envs
                          C:\Users\xxx\.conda\envs
          package cache : C:\Program Files\Anaconda3\pkgs
                          C:\Users\xxx\AppData\Local\conda\conda\pkgs
           channel URLs : [...]
            config file : C:\Program Files\Anaconda3\.condarc
           offline mode : False
             user-agent : conda/4.3.12 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.10240

Somehow the program files cache dir is prioritized even if it is not writable. 
Works with 4.3.9, throws a different error with 4.3.11 (part of the stack trace below)

      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 494, in fetch_repodata
        touch(cache_path)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\update.py", line 64, in touch
        utime(path, None)
    PermissionError: [WinError 5] Access is denied: 'C:\\Program Files\\Anaconda3\\pkgs\\cache\\3e904a53.json'

**Comment by kalefranz** [comment]
@wulmer Thanks for the report.  That `assert` is incorrect, and it was a mistake that it got left in.  Can you do me a favor and edit your file

    C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py

by removing the `assert` on line `596`?  See if that fixes your issue...

**Comment by kalefranz** [comment]
Thanks for using canary btw :)

**Comment by kalefranz** [comment]
> Somehow the program files cache dir is prioritized even if it is not writable

It's being correctly recognized now as a read-only cache.  The "first writable cache" is `C:\Users\xxx\AppData\Local\conda\conda\pkgs`, which is why that assert statement is incorrect.

**Comment by wulmer** [comment]
I have manually applied your patch and it avoids the first error I got. However I get an error now about the missing write permissions for the package cache directory as mentioned above for 4.3.11.

Running `conda create -n abc python=3` (using a named env instead of a prefix env) works with 4.3.9 but fails with 4.3.11. With 4.3.12 and patch #4649 applied, conda still tries to create the environment under `C:\Program Files\Anaconda3\envs\abc` and fails with 

    File "C:\Program Files\Anaconda3\lib\site-packages\conda\_vendor\auxlib\decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
    File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\test.py", line 82, in hardlink_supported
        assert isdir(dest_dir), dest_dir
    AssertionError: C:\Program Files\Anaconda3\envs\abc

**Comment by kalefranz** [comment]
Can you give me the full stack trace?

**Comment by kalefranz** [comment]
@wulmer I'm hopeful that I've fixed all your errors as part of https://github.com/conda/conda/pull/4663.

**Comment by wulmer** [comment]
@kalefranz Yes, seems to work. Just tested with conda 4.3.13. Thanks!
