### ISSUE TITLE
installing spyder

### ISSUE THREAD

**Issue by dalifig** [conda/conda#4656]
Current conda install:

               platform : win-32
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\bouab\Miniconda2  (writable)
    default environment : C:\Users\bouab\Miniconda2
       envs directories : C:\Users\bouab\Miniconda2\envs
                          C:\Users\bouab\AppData\Local\conda\conda\envs
                          C:\Users\bouab\.conda\envs
          package cache : C:\Users\bouab\Miniconda2\pkgs
                          C:\Users\bouab\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda/win-32
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.10240

`$ C:\Users\bouab\Miniconda2\Scripts\conda-script.py install -c anaconda spyder=3.1.2`

    Traceback (most recent call last):
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\core\link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\core\link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\gateways\disk\read.py", line 85, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\bouab\Miniconda2\lib\site-packages\conda\gateways\disk\read.py", line 104, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'C:\\Users\\bouab\\Miniconda2\\pkgs\\spyder-3.1.2-py27_0\\info\\index.json'

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
