### ISSUE TITLE
Unexpected error while installing Bcbio

### ISSUE THREAD

**Issue by amizeranschi** [conda/conda#4659]
I am getting an unexpected error while trying to install Bcbio. Here is a traceback:

```
Traceback (most recent call last):
  File "/bcbio/anaconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 63, in EXTRACT_CMD
    install.extract(config.pkgs_dirs[0], arg)
  File "/bcbio/anaconda/lib/python2.7/site-packages/conda/install.py", line 494, in extract
    os.lchown(p, 0, 0)
OSError: [Errno 22] Invalid argument: '/bcbio/anaconda/pkgs/jpeg-9b-0/info/has_prefix'
Traceback (most recent call last):
  File "bcbio_nextgen_install.py", line 246, in <module>
    main(parser.parse_args(), sys.argv[1:])
  File "bcbio_nextgen_install.py", line 38, in main
    bcbio = install_conda_pkgs(anaconda)
  File "bcbio_nextgen_install.py", line 73, in install_conda_pkgs
    "--file", os.path.basename(REMOTES["requirements"])])
  File "/bcbio/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bcbio/anaconda/bin/conda', 'install', '--quiet', '--yes', '-c', 'bioconda', '-c', 'conda-forge', '--file', 'requirements-conda.txt']' returned non-zero exit status 1
```

And here is the output of conda info:

```
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /bcbio/anaconda2  (writable)
    default environment : /bcbio/anaconda2
       envs directories : /bcbio/anaconda2/envs
          package cache : /bcbio/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/3.13.0-107-generic debian/jessie/sid glibc/2.19
                UID:GID : 0:0

```

How can I get past this issue?

**Comment by kalefranz** [comment]
No way this stack trace is from conda 4.3.8.  As you can see, the conda/install.py file definitely does not have 494 or more lines in 4.3.8 https://github.com/conda/conda/blob/4.3.8/conda/install.py.

I don't know how bcbio works exactly, but I guess it's subprocessing somehow to conda.  Perhaps it's more appropriate to file an issue with the bcbio tracker.
