### ISSUE TITLE
Error creating env 

### ISSUE THREAD

**Issue by xverges** [conda/conda#4664]
I am having problems with `conda env create` while building a docker image. I am able to build it in some machines and failing to do it in some others with the same docker version. I haven't been able to isolate what is different.

I first thought that it was related to #4593, but tried forcing and older version with `conda install --yes conda==4.3.8`  rather than `conda update --yes conda` and it still failed.

`conda env create -v -v -v --debug --name nlu --file /nlu/requirements.conda.yml ; ls /miniconda/pkgs; ls /miniconda/pkgs/cache;`

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /miniconda  (writable)
    default environment : /miniconda
       envs directories : /miniconda/envs
          package cache : /miniconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.12 Linux/3.10.0-327.36.2.el7.x86_64 debian/8.7 glibc/2.19
                UID:GID : 0:0



`$ /miniconda/bin/conda-env create -v -v -v --debug --name nlu --file /nlu/requirements.conda.yml`




    Traceback (most recent call last):
      File "/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/miniconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/miniconda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 37, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/miniconda/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 111, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 466, in execute
        self._execute_action(action)
      File "/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 488, in _execute_action
        raise CondaMultiError(exceptions)
    CondaMultiError: AssertionError(u'/miniconda/pkgs/readline-6.2-2',)
    AssertionError(u'/miniconda/pkgs/readline-6.2-2',)
    AssertionError(u'/miniconda/pkgs/readline-6.2-2',)


cache
cffi-1.9.1-py27_0
cffi-1.9.1-py27_0.tar.bz2
conda-4.2.12-py27_0
conda-4.3.8-py27_0
conda-4.3.8-py27_0.tar.bz2
conda-env-2.6.0-0
cryptography-1.7.1-py27_0
cryptography-1.7.1-py27_0.tar.bz2
enum34-1.1.6-py27_0
idna-2.2-py27_0
idna-2.2-py27_0.tar.bz2
ipaddress-1.0.18-py27_0
ipaddress-1.0.18-py27_0.tar.bz2
libffi-3.2.1-1
libffi-3.2.1-1.tar.bz2
libgfortran-3.0.0-1
libgfortran-3.0.0-1.tar.bz2
mkl-2017.0.1-0
mkl-2017.0.1-0.tar.bz2
nltk-3.2.2-py27_0.tar.bz2
numpy-1.11.3-py27_0.tar.bz2
openssl-1.0.2j-0
openssl-1.0.2k-0
openssl-1.0.2k-0.tar.bz2
pandas-0.19.2-np111py27_1.tar.bz2
pip-8.1.2-py27_0
pip-9.0.1-py27_1.tar.bz2
pyasn1-0.1.9-py27_0
pyasn1-0.1.9-py27_0.tar.bz2
pycosat-0.6.1-py27_1
pycparser-2.17-py27_0
pycparser-2.17-py27_0.tar.bz2
pycrypto-2.6.1-py27_4
pyopenssl-16.2.0-py27_0
pyopenssl-16.2.0-py27_0.tar.bz2
python-2.7.12-1
python-2.7.13-0.tar.bz2
python-dateutil-2.6.0-py27_0.tar.bz2
pytz-2016.10-py27_0.tar.bz2
readline-6.2-2
readline-6.2-2.tar.bz2
requests-2.11.1-py27_0
requests-2.12.4-py27_0
requests-2.12.4-py27_0.tar.bz2
ruamel_yaml-0.11.14-py27_0
scikit-learn-0.18.1-np111py27_1.tar.bz2
scipy-0.18.1-np111py27_1.tar.bz2
setuptools-27.2.0-py27_0
setuptools-27.2.0-py27_0.tar.bz2
six-1.10.0-py27_0
six-1.10.0-py27_0.tar.bz2
sqlite-3.13.0-0
sqlite-3.13.0-0.tar.bz2
tk-8.5.18-0
tk-8.5.18-0.tar.bz2
urls
urls.txt
wheel-0.29.0-py27_0
wheel-0.29.0-py27_0.tar.bz2
yaml-0.1.6-0
zlib-1.2.8-3
zlib-1.2.8-3.tar.bz2
08159f17.json
12d80b3c.json
1af9ae67.json
524e4676.json
6bfb14bd.json
716b88c0.json
87d00fe333551440c29e16192807b6e6.png
8db5e652.json
9779607c273dc0786bd972b4cb308b58.png
9ca791dd.json
db552c1e.json
df7feebede9861a203b480c119e38b49.png
f1a0ac49.json
```

**Comment by xverges** [comment]
If I force the use of version 4.0.5, the problem does not happen

**Comment by xverges** [comment]
Maybe this was just file-system related noise...

I just changed the [storagedriver](https://docs.docker.com/engine/userguide/storagedriver/selectadriver/) in Docker... and no exception

**Comment by nasedil** [comment]
@xverges do you remember on which driver it worked and on which not?  I have a similar issue.

**Comment by xverges** [comment]
@nasedil I am on RHEL, and it started working when I switched to devicemapper, as per https://success.docker.com/Policies/Compatibility_Matrix

**Comment by nasedil** [comment]
Thanks @xverges , that also worked for me.
