### ISSUE TITLE
AttributeError when trying to run conda on cmd

### ISSUE THREAD

**Issue by Coqueiro** [conda/conda#4679]
I'm getting the following error on conda while trying to run `conda` in my cmd:

```
Traceback (most recent call last):
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/delete.py", line 14, in <module>
    from .read import get_json_content
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 21, in <module>
    from ...models.channel import Channel
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 132, in _ensure_ffi_initialized
    cls._register_osrandom_engine()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 115, in _register_osrandom_engine
    cls._osrandom_engine_id = cls.lib.Cryptography_osrandom_engine_id
AttributeError: module 'lib' has no attribute 'Cryptography_osrandom_engine_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lucas/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 559, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 529, in get_info
    args.func(args, p)
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 142, in execute
    from conda.api import get_index
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 19, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 132, in _ensure_ffi_initialized
    cls._register_osrandom_engine()
  File "/home/lucas/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 115, in _register_osrandom_engine
    cls._osrandom_engine_id = cls.lib.Cryptography_osrandom_engine_id
AttributeError: module 'lib' has no attribute 'Cryptography_osrandom_engine_id'
```

I'm on an ubuntu 16.04. :)

**Comment by asimonov** [comment]
I get similar error on MacOS ElCapitan:

I get similar error on MacOS ElCapitan:

MacName:~ myusername$ sudo conda update conda
Password:
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/gateways/disk/delete.py", line 15, in <module>
    from .read import get_json_content
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 23, in <module>
    from ...models.channel import Channel
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_NPN_NEGOTIATED'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/myusername/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 607, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 561, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 531, in get_info
    args.func(args, p)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/cli/main_info.py", line 142, in execute
    from conda.api import get_index
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/core/path_actions.py", line 32, in <module>
    from ..gateways.download import download
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/Users/myusername/anaconda/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_NPN_NEGOTIATED'

**Comment by asimonov** [comment]
I have just updated openssl in both brew and macports to 1.0.2k and nothing changed.

Tried to install anaconda 4.3 using GUI installer and it says I already have conda installed and should update using: conda update conda.
So I am back to square one :)

**Comment by kalefranz** [comment]
What is the output of `conda info`?  The current conda version is 4.3.13.

**Comment by kalefranz** [comment]
Homebrew and macports openssl typically don't interact with the openssl conda uses.  Conda has its own python, which is linked to its own openssl.

**Comment by asimonov** [comment]
yes, I have re-installed anaconda and the issue is gone now. thank you

**Comment by shuhaojie** [comment]
> What is the output of `conda info`? The current conda version is 4.3.13. If you're not up-to-date, try `conda update conda`.

Hello@kalefranz I'm having the same type of problem.
```
Traceback (most recent call last):
  File "D:\anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "D:\anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "D:\anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "D:\anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "D:\anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "D:\anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "D:\anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "D:\anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "D:\anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "D:\anaconda3\lib\site-packages\OpenSSL\rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "D:\anaconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "D:\anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 141, in <module>
    Binding.init_static_locks()
  File "D:\anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 122, in init_static_locks
    cls._ensure_ffi_initialized()
  File "D:\anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 109, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "D:\anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\binding.py", line 69, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_CMAC'
```
I run `conda info` and the output is nothing. How can I solve this problem?
