### ISSUE TITLE
Error creating conda environment

### ISSUE THREAD

**Issue by nahidalam** [conda/conda#4683]
ERROR requests.packages.urllib3.connection:_match_hostname(317): Certificate did not match expected hostname: conda.anaconda.org. Certificate: {'caIssuers': ('http://crt.comodoca.com/COMODORSADomainValidationSecureServerCA.crt',), 'version': 3, 'notAfter': 'Feb 17 23:59:59 2020 GMT', 'serialNumber': '11AFCC443E29F0A31FC718D9E96E7473', 'crlDistributionPoints': ('http://crl.comodoca.com/COMODORSADomainValidationSecureServerCA.crl',), 'subjectAltName': (('DNS', '*.coxhn.net'), ('DNS', 'coxhn.net')), 'notBefore': 'Feb 18 00:00:00 2015 GMT', 'issuer': ((('countryName', 'GB'),), (('stateOrProvinceName', 'Greater Manchester'),), (('localityName', 'Salford'),), (('organizationName', 'COMODO CA Limited'),), (('commonName', 'COMODO RSA Domain Validation Secure Server CA'),)), 'subject': ((('organizationalUnitName', 'Domain Control Validated'),), (('organizationalUnitName', 'COMODO SSL Wildcard'),), (('commonName', '*.coxhn.net'),)), 'OCSP': ('http://ocsp.comodoca.com',)}
Could not connect to https://conda.anaconda.org/conda-forge/osx-64/pyasn1-0.1.9-py35_0.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/nahidalam/anaconda  (writable)
    default environment : /Users/nahidalam/anaconda
       envs directories : /Users/nahidalam/anaconda/envs
          package cache : /Users/nahidalam/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/nahidalam/anaconda/bin/conda-env create -f environment.yml`

    Traceback (most recent call last):
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 305, in connect
        _match_hostname(cert, self.assert_hostname or hostname)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 313, in _match_hostname
        match_hostname(cert, asserted_hostname)
      File "/Users/nahidalam/anaconda/lib/python3.5/ssl.py", line 297, in match_hostname
        % (hostname, ', '.join(map(repr, dnsnames))))
    ssl.CertificateError: hostname 'conda.anaconda.org' doesn't match either of '*.coxhn.net', 'coxhn.net'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: hostname 'conda.anaconda.org' doesn't match either of '*.coxhn.net', 'coxhn.net'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 377, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3.05, 27))
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: hostname 'conda.anaconda.org' doesn't match either of '*.coxhn.net', 'coxhn.net'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 32, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 403, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: hostname 'conda.anaconda.org' doesn't match either of '*.coxhn.net', 'coxhn.net': https://conda.anaconda.org/conda-forge/osx-64/pyasn1-0.1.9-py35_0.tar.bz2
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 39, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/nahidalam/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/nahidalam/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 37, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: hostname 'conda.anaconda.org' doesn't match either of '*.coxhn.net', 'coxhn.net': https://conda.anaconda.org/conda-forge/osx-64/pyasn1-0.1.9-py35_0.tar.bz2

**Comment by DalilaR** [comment]
I just put the packages in on of the Anaconda paths.  More precisely, I just put them in pkg

**Comment by kalefranz** [comment]
`conda update conda` might help.  Otherwise you have a networking issue with your operating system.
