### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by saikiransunny** [conda/conda#4687]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : 2.1.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\Sai Kiran\Anaconda2  (writable)
    default environment : C:\Users\Sai Kiran\Anaconda2
       envs directories : C:\Users\Sai Kiran\Anaconda2\envs
                          C:\Users\Sai Kiran\AppData\Local\conda\conda\envs
                          C:\Users\Sai Kiran\.conda\envs
          package cache : C:\Users\Sai Kiran\Anaconda2\pkgs
                          C:\Users\Sai Kiran\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\Users\Sai Kiran\Anaconda2\Scripts\conda-script.py create -n python3_selfdriving python=3.6 anaconda`

    Traceback (most recent call last):
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\core\link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\core\link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 85, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\Sai Kiran\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 104, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'C:\\Users\\Sai Kiran\\Anaconda2\\pkgs\\pygments-2.1.3-py36_0\\info\\index.json'

**Comment by mingwandroid** [comment]
Would it be possible to try to install into a folder *without* spaces in it and post your results?

**Comment by kalefranz** [comment]
@saikiransunny Can you see if `conda clean --packages` fixes your issue?

**Comment by kalefranz** [comment]
This has been fixed via #4789 and/or #5098.
