### ISSUE TITLE
unexpected update error 

### ISSUE THREAD

**Issue by littlewood9236** [conda/conda#4688]
hi! I am a anaconda new user. I got a problem when the conda was updated. 
the information was list;

$ conda update --all

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/little/anaconda3  (writable)
    default environment : /home/little/anaconda3
       envs directories : /home/little/anaconda3/envs
          package cache : /home/little/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-62-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/little/anaconda3/bin/conda update --all`

    Traceback (most recent call last):
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 191, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 184, in proxy_manager_for
        **proxy_kwargs
      File "/home/little/anaconda3/lib/python3.6/site-packages/requests/adapters.py", line 43, in SOCKSProxyManager
        raise InvalidSchema("Missing dependencies for SOCKS support.")
    requests.exceptions.InvalidSchema: Missing dependencies for SOCKS support.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 401, in <listcomp>
        for url in urls]
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 141, in func
        res = f(*args, **kwargs)
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 385, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/home/little/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 212, in fetch_repodata_remote_request
        raise CondaRuntimeError("Invalid index file: {0}: {1}".format(join_url(url, filename), e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://repo.continuum.io/pkgs/free/linux-64/repodata.json.bz2: Missing dependencies for SOCKS support.

**Comment by nehaljwani** [comment]
Probably, this is related: https://github.com/conda/conda/issues/3838

**Comment by kalefranz** [comment]
Yes, if you have configuration on your system that `requests` is recognizing for a socks proxy, you'll need to `pip install -U pysocks`.  I don't think the default repo currently have a conda package for pysocks.   Note the [conda-forge pysocks](https://github.com/conda-forge/pysocks-feedstock) version is one that's [specifically noted to be not compatible](https://github.com/kennethreitz/requests/blob/v2.13.0/setup.py#L99) with requests.
