### ISSUE TITLE
conda env upload raises exception

### ISSUE THREAD

**Issue by bkreider** [conda/conda#4691]
```
conda env upload adsf 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 2.1.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda  (writable)
    default environment : /opt/anaconda
       envs directories : /opt/anaconda/envs
          package cache : /opt/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/t/<TOKEN>/bkreider/osx-64
                          https://conda.anaconda.org/t/<TOKEN>/bkreider/noarch
                          https://conda.binstar.org/t/<TOKEN>/wakari/osx-64
                          https://conda.binstar.org/t/<TOKEN>/wakari/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
            config file : /opt/anaconda/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Darwin/14.5.0 OSX/10.10.5
                UID:GID : 502:20



`$ /opt/anaconda/bin/conda-env upload adsf`




    Traceback (most recent call last):
      File "/opt/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda_env/cli/main_upload.py", line 78, in execute
        raise exceptions.CondaEnvRuntimeError(msg)
    CondaEnvRuntimeError: Runtime error: Unable to locate environment file: environment.yml
    
    Please verify that the above file is present and that you have
    permission read the file's contents.  Note, you can specify the file
    to use by explictly adding --file=/path/to/file when calling conda env
    create.
```

**Comment by kalefranz** [comment]
Fixed in 5b320a99c98b2459585439c809132a229da6a74b
