### ISSUE TITLE
Unable to install packages using conda

### ISSUE THREAD

**Issue by manviths** [conda/conda#4695]
I am unable to install any packages using conda.
Infact when i run the conda command i get the following error.

**C:\Windows\system32>conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Program Files\Anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 152
, in main
    return conda_exception_handler(_main)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", line 4
97, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", line 4
43, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", line 4
02, in get_info
    from conda.cli import conda_argparse
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\conda_argparse.py"
, line 15, in <module>
    from .common import add_parser_help
  File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\common.py", line 1
5, in <module>
    from ..install import dist2quad
ImportError: cannot import name dist2quad**

_Conda Version: 4.2.13_

How do i resolve this issue?

**Comment by kalefranz** [comment]
`conda` itself isn't a full command.  If you're trying to install packages, you need something like

   conda install package-name

However you're running an outdated version of conda.  I would start with `conda update conda`.

**Comment by manviths** [comment]
It does not work. I get the same error for `conda update conda`

**Comment by peetw** [comment]
I'm also experiencing this error after I ran `conda update python` to update Python from 2.7.8 to 2.7.13. The command appeared to succeed, but `python --version` is still reporting 2.7.8...
