### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by piranzu** [conda/conda#4696]
When trying to update conda or create an environment: 

Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\Irantzu\AppData\Local\conda\conda\envs
                          C:\Users\Irantzu\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Irantzu\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Miniconda3\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 144, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Miniconda3\\pkgs\\cache\\2116b818.json'

**Comment by kalefranz** [comment]
To my knowledge, this is fixed as of conda 4.3.13.  `conda update conda`
If you still have problem, please *definitely* let me know.

**Comment by piranzu** [comment]
conda update conda did not solve it. I solved it reinstalling conda for me, not for all users. Thanks!
