### ISSUE TITLE
Error installing majiq with conda

### ISSUE THREAD

**Issue by ZheFrenchKitchen** [conda/conda#4698]
`conda create -n majiq_env -c http://majiq.biociphers.org/download/channel majiq`
 
Fetching package metadata ....
WARNING: The remote server could not find the noarch directory for the
requested channel with url: http://majiq.biociphers.org/download/channel/noarch

It is possible you have given conda an invalid channel. Please double-check
your conda configuration using conda config --show.

If the requested url is in fact a valid conda channel, please request that the
channel administrator create noarch/repodata.json and associated
noarch/repodata.json.bz2 files, even if `noarch/repodata.json` is empty.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

    Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 1.21.3
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /home/jean-philippe.villemin/bin/anaconda3  (writable)
    default environment : /home/jean-philippe.villemin/bin/anaconda3
       envs directories : /home/jean-philippe.villemin/bin/anaconda3/envs
          package cache : /home/jean-philippe.villemin/bin/anaconda3/pkgs
           channel URLs : http://majiq.biociphers.org/download/channel/linux-64
                          http://majiq.biociphers.org/download/channel/noarch
                          https://conda.anaconda.org/bcbio/linux-64
                          https://conda.anaconda.org/bcbio/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jean-philippe.villemin/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.2 Linux/3.16.0-4-amd64 debian/8.7 glibc/2.19
                UID:GID : 1004:1003

    Traceback (most recent call last):
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 124, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 532, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 521, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 494, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 494, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 143, in func
        res = f(*args, **kwargs)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 483, in fetch_repodata
        process_repodata(repodata, url, schannel, priority)
      File "/home/jean-philippe.villemin/bin/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 410, in process_repodata
        opackages = repodata.setdefault('packages', {})
    AttributeError: 'NoneType' object has no attribute 'setdefault'
`

**Comment by kalefranz** [comment]
This has been fixed in a more recent version of conda.

    conda update conda

The current version is 4.3.13.
