### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by JurijsNazarovs** [conda/conda#4706]
Traceback (most recent call last):
  File "/u/n/a/nazarovs/miniconda3/bin/conda", line 6, in <module>
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 139, in main
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 146, in args_func
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 49, in execute
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 424, in install
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 539, in execute_actions
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 149, in execute_instructions
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 63, in EXTRACT_CMD
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/site-packages/conda/install.py", line 485, in extract
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/tarfile.py", line 2000, in extractall
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/tarfile.py", line 2042, in extract
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/tarfile.py", line 2112, in _extract_member
  File "/u/n/a/nazarovs/miniconda3/lib/python3.5/tarfile.py", line 2152, in makefile
TimeoutError: [Errno 110] Connection timed out: '/u/n/a/nazarovs/miniconda3/pkgs/metaseq-0.5.6-py27_0/bin/maf_extract_ranges_indexed.pyc'

**Comment by kalefranz** [comment]
Please provide the output of `conda info`.  If you're not running either conda version 4.2.16 or 4.3.13, I recommend `conda update conda`.

**Comment by kalefranz** [comment]
I've confirmed that your stack trace is from an older version of conda.  After updating, if you continue to have problems, please file a new issue.
