### ISSUE TITLE
Error trying to update to a newer version of conda

### ISSUE THREAD

**Issue by goroh-io** [conda/conda#4718]
On a Win10 machine I'm trying to update my conda version to the latest available.
```
C:\Anaconda>conda update --prefix c:\Anaconda anaconda
Fetching package metadata: ..
Solving package specifications: .
Package plan for installation in environment c:\Anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    anaconda-custom            |           py27_0          13 KB
    python-2.7.13              |                0        23.9 MB
    vs2008_runtime-9.00.30729.5054|                0        1016 KB
    ------------------------------------------------------------
                                           Total:        24.9 MB

The following NEW packages will be INSTALLED:

    vs2008_runtime: 9.00.30729.5054-0

The following packages will be UPDATED:

    anaconda:       2.1.0-np19py27_0 --> custom-py27_0
    python:         2.7.8-0          --> 2.7.13-0

Proceed ([y]/n)? y

Fetching packages ...
anaconda-custo 100% |###############################| Time: 0:00:00 194.25 kB/s
python-2.7.13- 100% |###############################| Time: 0:00:44 559.09 kB/s
vs2008_runtime 100% |###############################| Time: 0:00:00   1.82 MB/s
Extracting packages ...
[      COMPLETE      ] |#################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |#################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the            |  66%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 201, in main
    args_func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 206, in args_func
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 387, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 587, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 569, in execute_plan
    link(prefix, arg, index=index)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 525, in link
    install.link(pkgs_dir, prefix, dist, lt, index=index)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 517, in link
    _link(src, dst, lt)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 133, in _link
    shutil.copy2(src, dst)
  File "C:\Anaconda\lib\shutil.py", line 130, in copy2
  File "C:\Anaconda\lib\shutil.py", line 83, in copyfile
IOError: [Errno 13] Permission denied: 'c:\\Anaconda\\DLLs/_ctypes.pyd'

C:\Anaconda>conda info
ImportError: No module named site

```

The user I'm using is a local administrator

**Comment by kalefranz** [comment]
You're working with a really old version of conda.  First do `conda update conda`, with the appropriate privileges.  If installed Anaconda with administrator privileges, then make sure you're working in an Administrator shell when you do `conda update conda`.
