### ISSUE TITLE
Fresh miniconda install has "AttributeError: 'NoneType' object has no attribute 'startswith'"

### ISSUE THREAD

**Issue by jamesporritt** [conda/conda#4724]
Trying to do a fresh install of miniconda2, but getting an error as soon as I try to install anything. Here is the full transcript of my session. I'm using the same .condarc file that works on older miniconda2 installations:

```
$ wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
--2017-02-24 03:00:43--  https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
Resolving nybcproxy.mlp.com... 10.5.131.31, 10.5.131.32
Connecting to nybcproxy.mlp.com|10.5.131.31|:3128... connected.
Proxy request sent, awaiting response... 200 OK
Length: 27208383 (26M) [application/x-sh]
Saving to: “miniconda.sh”

100%[=============================================================================================================================================================>] 27,208,383  12.5M/s   in 2.1s    

2017-02-24 03:00:45 (12.5 MB/s) - “miniconda.sh” saved [27208383/27208383]

$ sh ./miniconda.sh -b -p ./miniconda2
PREFIX=/home/jporritt/miniconda2
installing: _cache-0.0-py27_x0 ...
installing: python-2.7.11-0 ...
installing: conda-env-2.4.5-py27_0 ...
installing: openssl-1.0.2g-0 ...
installing: pycosat-0.6.1-py27_0 ...
installing: pyyaml-3.11-py27_1 ...
installing: readline-6.2-2 ...
installing: requests-2.9.1-py27_0 ...
installing: sqlite-3.9.2-0 ...
installing: tk-8.5.18-0 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-0 ...
installing: conda-4.0.5-py27_0 ...
installing: pycrypto-2.6.1-py27_0 ...
installing: pip-8.1.1-py27_1 ...
installing: wheel-0.29.0-py27_0 ...
installing: setuptools-20.3-py27_0 ...
Python 2.7.11 :: Continuum Analytics, Inc.
creating default environment...
installation finished.
$ export PATH=/home/jporritt/miniconda2:$PATH
$ which conda
/home/jporritt/miniconda2/bin/conda
$ conda install conda
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/jporritt/miniconda2/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 240, in install
    prefix=prefix)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/cli/common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/api.py", line 43, in get_index
    unknown=unknown)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 264, in fetch_index
    reversed(channel_urls))
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 263, in <lambda>
    use_cache=use_cache, session=session)),
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/conda/fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 554, in urlopen
    self._prepare_proxy(conn)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 750, in _prepare_proxy
    conn.connect()
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 217, in connect
    conn = self._new_conn()
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/jporritt/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 64, in create_connection
    if host.startswith('['):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by jamesporritt** [comment]
My bad. I'd managed to remove one of the forward slashes of the proxy in the .condarc file. (https:/ instead of https://)

**Comment by kalefranz** [comment]
Related to or duplicate of #3962.
