### ISSUE TITLE
Create Environment Failure

### ISSUE THREAD

**Issue by ganwilliam** [conda/conda#4731]
Error message from the failure to create a new environment in the anaconda prompt. This follows the failure to create a new environment in the navigator.

(C:\ProgramData\Anaconda3) C:\Users\gw>conda create --name test_1 numpy matplotlib pandas
Fetching package metadata ...........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/bokeh/win-64
                          https://conda.anaconda.org/bokeh/noarch
                          https://conda.anaconda.org/blaze/win-64
                          https://conda.anaconda.org/blaze/noarch
                          https://conda.anaconda.org/matplotlib/win-64
                          https://conda.anaconda.org/matplotlib/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\gw\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create --name test_1 numpy matplotlib pandas`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'

**Comment by ozak** [comment]
I have a similar problem when trying to create a new environment for my user on a Linux cluster. I am trying to use a ``YAML`` file that I use to install my working environment in other computers, which has worked fine in other computers where I have administrative rights. Strangely, in the cluster it fails, even though I am not trying to install or update anything in the root account but in mine. Here's the command and the error message I get:

    conda-env create -p ~/.conda/envs/ -f ~/CondaInstall/Myenv.yml

   Traceback (most recent call last):
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 29, in install
        prefix=prefix)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/grid/software/anaconda/4.3.0/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/grid/software/anaconda/4.3.0/anaconda3/pkgs/cache/497deca9.json'

Any idea what may be causing this?

**Comment by ganwilliam** [comment]
The problem 'create environment failure' has been resolved.

The apparent cause was the selection to install to 'All Users'. I was advised to reinstall to myself as the only user. That worked. Also resolved the problem of conda update failure.

Cheers.
