### ISSUE TITLE
Conda Update Failure

### ISSUE THREAD

**Issue by ganwilliam** [conda/conda#4732]
This follows my earlier post regarding Create Environment Failure.

Following the failure in creating a new environment, I tried conda update. But this failed as well. FYI, the conda update worked on my other machine as well - a similar Windows 10 64-bit.

(C:\ProgramData\Anaconda3) C:\Users\gw>conda update conda
Fetching package metadata ...........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/bokeh/win-64
                          https://conda.anaconda.org/bokeh/noarch
                          https://conda.anaconda.org/blaze/win-64
                          https://conda.anaconda.org/blaze/noarch
                          https://conda.anaconda.org/matplotlib/win-64
                          https://conda.anaconda.org/matplotlib/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\gw\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py update conda`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'

**Comment by tychoaussie** [comment]
I also have had a failure. 

C:\Anaconda>conda create -n new_env python=2.7
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 1.14.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
          package cache : C:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Anaconda\Scripts\conda-script.py create -n new_env python=2.7`




    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Anaconda\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 295, in fetch_index
        for url in urls]
      File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 330, in connect
        cert = self.sock.getpeercert()
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 324, in getpeercert
        'subjectAltName': get_subj_alt_name(x509)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 171, in get_subj_alt_name
        ext = cert.extensions.get_extension_for_class(
    AttributeError: 'Extensions' object has no attribute 'get_extension_for_class'

**Comment by ganwilliam** [comment]
@tychoaussie 
Did you try to update conda? I noticed your version is 4.2.

**Comment by tychoaussie** [comment]
I am updating conda this morning. It's a mystery why the whole thing
crashed in the first place, but my anaconda was totally broken. It wouldn't
even launch conda without error. I've uninstalled the entire package (I
hope). I'll then attempt to re-install Python notebooks, and then try to
re-install Obspy. I am going with the version 2.7 Python. Is this still the
recommended version, or would you recommend I install Python 3.x at this
point?

I still haven't even touched the original problem: That of my broken
utilities that calculate station to epicenter distance & azimuth, and
calculation of predicted phase arrival times. I need that code to be
working again by Monday.

**Comment by kalefranz** [comment]
You have to versions of conda with two different problems.  See [here](https://github.com/conda/conda/issues/4495#issuecomment-283488009) to solve your problem for conda 4.2.

For conda 4.3, open the Anaconda prompt as admin user by right-clicking on Anaconda Prompt and then choosing "Run as administrator".  The run `conda update conda` to version >=4.3.13.

**Comment by ganwilliam** [comment]
The problem 'conda update failure' has been resolved.

The apparent cause was the selection to install to 'All Users'. I was advised to reinstall to myself as the only user. That worked. Also resolved the problem of newly created environment not showing on the Navigator.

Cheers.

**Comment by weizier** [comment]
@kalefranz Still got the same error here.
