### ISSUE TITLE
Unexpected error (Conda update) linux-64

### ISSUE THREAD

**Issue by b0rn6** [conda/conda#4733]
borna@borna-desktop:~$ conda update conda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/borna/miniconda3  (read only)
    default environment : /home/borna/miniconda3
       envs directories : /home/borna/miniconda3/envs
                          /home/borna/.conda/envs
          package cache : /home/borna/miniconda3/pkgs
                          /home/borna/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Linux/4.8.0-36-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/borna/miniconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/home/borna/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/borna/miniconda3/pkgs/cache/db552c1e.json'

**Comment by kalefranz** [comment]
This is fixed in general for conda >= 4.3.13.  In your case here though, 

    sudo chown -R borna:borna /home/borna/miniconda3

then

    conda update conda

**Comment by ktkirk** [comment]
Have similar problem, tried chown

[kirk@fob-login02 ~]$ conda update -y -v conda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /usr/people/kirk/miniconda3:

The following packages will be UPDATED:

    conda: 4.3.8-py35_0 --> 4.3.13-py35_0

()

===> UNLINKING PACKAGE: defaults::conda-4.3.8-py35_0 <===
  prefix=/usr/people/kirk/miniconda3


===> LINKING PACKAGE: defaults::conda-4.3.13-py35_0 <===
  prefix=/usr/people/kirk/miniconda3
  source=/usr/people/kirk/miniconda3/pkgs/conda-4.3.13-py35_0


An error occurred while installing package 'defaults::conda-4.3.13-py35_0'.
PermissionError(13, 'Permission denied')
Attempting to roll back.


===> REVERSING PACKAGE LINK: defaults::conda-4.3.13-py35_0 <===
  prefix=/usr/people/kirk/miniconda3


===> REVERSING PACKAGE UNLINK: defaults::conda-4.3.8-py35_0 <===
  prefix=/usr/people/kirk/miniconda3


An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



overtaking stderr and stdout

stderr and stdout yielding back

Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : /usr/people/kirk/miniconda3  (writable)
    default environment : /usr/people/kirk/miniconda3
       envs directories : /usr/people/kirk/miniconda3/envs
          package cache : /usr/people/kirk/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
            config file : /usr/people/kirk/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.5.2 Linux/3.10.0-514.6.2.el7.x86_64 Red Hat Enterprise Linux Server/7.3 glibc/2.17
                UID:GID : 1081:1143



`$ /usr/people/kirk/miniconda3/bin/conda update -y -v conda`




    Traceback (most recent call last):
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 307, in _execute_actions
        action.execute()
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/core/path_actions.py", line 272, in execute
        super(PrefixReplaceLinkAction, self).execute()
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/core/path_actions.py", line 227, in execute
        force=context.force)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/gateways/disk/create.py", line 241, in create_link
      File "/usr/people/kirk/miniconda3/lib/python3.5/shutil.py", line 159, in _copyxattr
        os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
    PermissionError: [Errno 13] Permission denied: '/usr/people/kirk/miniconda3/bin/conda'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 261, in execute
        pkg_data, actions)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 325, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/usr/people/kirk/miniconda3/bin/conda'
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/usr/people/kirk/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 277, in execute
        rollback_excs,
    conda.CondaMultiError: [Errno 13] Permission denied: '/usr/people/kirk/miniconda3/bin/conda'
    

[kirk@fob-login02 ~]$ ls -l /usr/people/kirk/miniconda3/bin/conda
-rwxrwxr-x. 1 kirk vis 136 Jan 30 13:30 /usr/people/kirk/miniconda3/bin/conda
[kirk@fob-login02 ~]$ ls -ln /usr/people/kirk/miniconda3/bin/conda
-rwxrwxr-x. 1 1081 1143 136 Jan 30 13:30 /usr/people/kirk/miniconda3/bin/conda

**Comment by kalefranz** [comment]
Hi @ktkirk.  Thanks for the report.  This is a different problem (probably) then the one addressed by this ticket.  Can you create a new ticket (reference this one if you want), but also include the output of the operation with `-vvv`?  I don't exactly understand what's going on yet, and that extra-verbose output will help.
