### ISSUE TITLE
like this  (TAT):

### ISSUE THREAD

**Issue by jane0603** [conda/conda#4737]
Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 39, in execute
    install.install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 155, in install
    unknown=args.unknown)
  File "C:\Anaconda2\lib\site-packages\conda\api.py", line 36, in get_index
    unknown=unknown)
  File "C:\Anaconda2\lib\site-packages\conda\utils.py", line 73, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 111, in fetch_index
    repodata = fetch_repodata(url, use_cache=use_cache)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 75, in fetch_repodata
    u = connectionhandled_urlopen(request)
  File "C:\Anaconda2\lib\site-packages\conda\connection.py", line 83, in connectionhandled_urlopen
    return urllib2.urlopen(request)
  File "C:\Anaconda2\lib\urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Anaconda2\lib\urllib2.py", line 429, in open
    response = self._open(req, data)
  File "C:\Anaconda2\lib\urllib2.py", line 447, in _open
    '_open', req)
  File "C:\Anaconda2\lib\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Anaconda2\lib\urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "C:\Anaconda2\lib\urllib2.py", line 1201, in do_open
    r = h.getresponse(buffering=True)
  File "C:\Anaconda2\lib\httplib.py", line 1136, in getresponse
    response.begin()
  File "C:\Anaconda2\lib\httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "C:\Anaconda2\lib\httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "C:\Anaconda2\lib\socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 10054]

**Comment by jane0603** [comment]
No environment named "C:\Anaconda2" exists in C:\Anaconda2\envs
and, when I installing, "Error: HTTPError: 403  Forbidden  http://repo.continuum.io/pkgs/pro/win-64/ "

**Comment by kalefranz** [comment]
You are most likely using a very old version of conda.  Best to download a new Miniconda or Anaconda installer.  A Miniconda installer should be able to install overtop your current installation.
https://conda.io/miniconda.html
