### ISSUE TITLE
Error installing or uninstalling Anaconda on Mac OS X

### ISSUE THREAD

**Issue by sophia-wright-blue** [conda/conda#4741]
I was unable to launch Navigator on Mac OS X, so I tried uninstalling Anaconda to try a fresh install. But on doing conda install anaconda-clean, I got the following error:

```
ImportError: No module named mimetools
Using Anaconda API: https://api.anaconda.org
Fetching package metadata ...An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/sophiaw/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 231, in install
    index = common.get_index_trap(**index_args)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/common.py", line 627, in get_index_trap
    return get_index(*args, **kwargs)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/api.py", line 25, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 295, in fetch_index
    repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 68, in func
    res = f(*args, **kwargs)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 112, in fetch_repodata
    resp = session.get(url + filename, headers=headers, proxies=session.proxies)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
    self._validate_conn(conn)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
    conn.connect()
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 323, in connect
    ssl_context=context)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 392, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]


```

here is the output from conda info:

```
Traceback (most recent call last):
  File "/Users/sophiaw/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 94, in main
    imported = importlib.import_module(module)
  File "/Users/sophiaw/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 18, in <module>
    from ..egg_info import get_egg_info
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/misc.py", line 18, in <module>
    from .instructions import RM_FETCHED, FETCH, RM_EXTRACTED, EXTRACT, UNLINK, LINK, SYMLINK_CONDA
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 7, in <module>
    from .fetch import fetch_pkg
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 13, in <module>
    import requests
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/requests/packages/__init__.py", line 29, in <module>
    import urllib3
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/urllib3/packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/urllib3/packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/Users/sophiaw/anaconda/lib/python2.7/site-packages/urllib3/packages/six.py", line 82, in _import_module
    __import__(name)
  File "/Users/sophiaw/anaconda/lib/python2.7/httplib.py", line 80, in <module>
    import mimetools
ImportError: No module named mimetools
Current conda install:

             platform : osx-64
        conda version : 4.1.12
    conda-env version : 2.6.0
  conda-build version : 2.0.2
       python version : 2.7.13.final.0
     requests version : 2.12.4
     root environment : /Users/sophiaw/anaconda  (writable)
  default environment : /Users/sophiaw/anaconda
     envs directories : /Users/sophiaw/anaconda/envs
        package cache : /Users/sophiaw/anaconda/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/osx-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://conda.anaconda.org/anaconda-fusion/osx-64/
                        https://conda.anaconda.org/anaconda-fusion/noarch/
                        https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/sophiaw/.condarc
         offline mode : False
    is foreign system : False


```

I'd greatly appreciate any help to fix this problem, I'd like to uninstall and then do a fresh installation of Anaconda. I'm running Sierra.

Thank you

**Comment by mingwandroid** [comment]
You probably don't need to bother with `anaconda-clean`. If you just remove the root install folder and ~/.continuum and re-install it might be enough.

**Comment by sophia-wright-blue** [comment]
Thank you, that worked!
