### ISSUE TITLE
fails to install qt package

### ISSUE THREAD

**Issue by dchuong105** [conda/conda#4748]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

overtaking stderr and stdout

stderr and stdout yielding back

Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProductTest\Anaconda  (writable)
    default environment : C:\ProductTest\Anaconda
       envs directories : C:\ProductTest\Anaconda\envs
                          C:\Users\dchuong\AppData\Local\conda\conda\envs
                          C:\Users\dchuong\.conda\envs
          package cache : C:\ProductTest\Anaconda\pkgs
                          C:\Users\dchuong\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-canary/win-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dchuong\.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601

`$ C:\ProductTest\Anaconda\Scripts\conda-script.py install -v qt`

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 493, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\gateways\subprocess.py", line 58, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\WINDOWS\\system32\\cmd.exe', '/c', 'C:\\ProductTest\\Anaconda\\Scripts
\\.qt-post-link.bat']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 320, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 509, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package defaults::qt-5.6.2-vc14_3
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProductTest\Anaconda\Scripts\.qt-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 273, in execute
        pkg_data, actions)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 337, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package defaults::qt-5.6.2-vc14_3
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProductTest\Anaconda\Scripts\.qt-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProductTest\Anaconda\lib\site-packages\conda\core\link.py", line 289, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package defaults::qt-5.6.2-vc14_3
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProductTest\Anaconda\Scripts\.qt-post-link.bat
    ==> script messages <==
    <None>

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1491
