### ISSUE TITLE
install fails for hdbscan using conda install -c conda-forge hdbscan

### ISSUE THREAD

**Issue by Berowne** [conda/conda#4749]
[2.5] C:\>conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : win-64
        conda version : 4.0.7
  conda-build version : 1.20.3
       python version : 2.7.11.final.0
     requests version : 2.12.3
     root environment : C:\FAST\anaconda\2.5.0  (writable)
  default environment : C:\FAST\anaconda\2.5.0
     envs directories : C:\FAST\anaconda\2.5.0\envs
        package cache : C:\FAST\anaconda\2.5.0\pkgs
         channel URLs : file://C:\FAST\anaconda\2.5.0\localrepo/win-64/
                        file://C:\FAST\anaconda\2.5.0\localrepo/noarch/
          config file : C:\Users\i015225\.condarc
    is foreign system : False

[2.5] C:\>conda install -c conda-forge hdbscan
Using Anaconda Cloud api site https://api.anaconda.org

Traceback (most recent call last):
  File "C:\FAST\anaconda\2.5.0\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\cli\install.py", line 240 in install
    prefix=prefix)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\cli\common.py", line 595, in get_index_trap
    return get_index(*args, **kwargs)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\api.py", line 43, in get_index
    unknown=unknown)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\utils.py", line 118, in __call__
    value = self.func(*args, **kw)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\fetch.py", line 259, in fetch_index
    repodatas.append((url, future.result()))
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\concurrent\futures\_base.py", line 405, in result
    return self.__get_result()
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\fetch.py", line 65, in func
    res = f(*args, **kwargs)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\conda\fetch.py", line 100, in fetch_repodata
    headers=headers, proxies=session.proxies)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\requests\sessions.py", line 641, in send
    r.content
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\requests\models.py", line 781, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "C:\FAST\anaconda\2.5.0\lib\site-packages\requests\models.py", line 714, in generate
    chunk = self.raw.read(chunk_size)
AttributeError: 'exceptions.WindowsError' object has no attribute 'read'

**Comment by kalefranz** [comment]
Conda 4.0.7 is very old.  Please `conda update conda`.  The latest version is 4.3.13.  That should resolve your problem.  Fundamentally looks like a requests incompatibility.
