### ISSUE TITLE
installation issue with conda

### ISSUE THREAD

**Issue by radiosky-abhik** [conda/conda#4755]
(root) abhik@radiouniverse: conda install scipy astropy pandas pytables cython

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/abhik/Software/conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/cli/main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/exceptions.py", line 559, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/exceptions.py", line 518, in get_info
    from conda.cli import conda_argparse
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 14, in <module>
    from .read import get_json_content
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 22, in <module>
    from ...models.channel import Channel
  File "/home/abhik/Software/conda/lib/python2.7/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
ImportError: No module named packages.urllib3.util

**Comment by emigmo** [comment]
Me too！
But urllib3 python package really in my system by testing "import urllib3"

**Comment by radiosky-abhik** [comment]
I manage to solve it.
I commented out /home/abhik/.local/lib/python2.7/site-packages/ in my .pth file. That seems to work. Thanks.
