### ISSUE TITLE
Update errors: conda update anaconda

### ISSUE THREAD

**Issue by mlettau** [conda/conda#4762]
$ conda update anaconda
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /Users/martinlettau/anaconda:

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:     4.3.13-py27_0 anaconda --> 4.2.13-py27_0 conda-forge
    conda-env: 2.6.0-0       anaconda --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 1.21.6
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /Users/martinlettau/anaconda  (writable)
    default environment : /Users/martinlettau/anaconda
       envs directories : /Users/martinlettau/anaconda/envs
                          /Users/martinlettau/.conda/envs
          package cache : /Users/martinlettau/anaconda/pkgs
                          /Users/martinlettau/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/mpastell/osx-64
                          https://conda.anaconda.org/mpastell/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/martinlettau/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.13 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 502:20

`$ /Users/martinlettau/anaconda/bin/conda update anaconda`

    Traceback (most recent call last):
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 474, in execute
        self._execute_action(action)
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 490, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/Users/martinlettau/anaconda/lib/python2.7/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string

**Comment by kalefranz** [comment]
CC @tyler-thetyrant on the `TypeError`.

**Comment by kalefranz** [comment]
The root cause is that Amazon S3 is down, and so anaconda.org is down (along with half the internet).  This will be resolved when S3 is back online.
