### ISSUE TITLE
problem install pyresample from conda-forge

### ISSUE THREAD

**Issue by bbakernoaa** [conda/conda#4766]
Ran into a problem today trying to use conda to install pyresample:
```
conda install -c conda-forge pyresample
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /naqfc/noscrub/Barry.Baker/anaconda2:

The following NEW packages will be INSTALLED:

    pykdtree:   1.2.1-np111py27_0 conda-forge
    pyproj:     1.9.5.1-py27_0    conda-forge
    pyresample: 1.3.0-np111py27_0 conda-forge

The following packages will be SUPERCEDED by a higher-priority channel:

    conda:      4.3.13-py27_0                 --> 4.2.13-py27_0 conda-forge
    conda-env:  2.6.0-0                       --> 2.6.0-0       conda-forge

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /naqfc/noscrub/Barry.Baker/anaconda2  (writable)
    default environment : /naqfc/noscrub/Barry.Baker/anaconda2
       envs directories : /naqfc/noscrub/Barry.Baker/anaconda2/envs
                          /u/Barry.Baker/.conda/envs
          package cache : /naqfc/noscrub/Barry.Baker/anaconda2/pkgs
                          /u/Barry.Baker/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.13 Linux/2.6.32-573.38.1.el6.x86_64 Red Hat Enterprise Linux Server/6.7 glibc/2.12
                UID:GID : 20913:5004



`$ /naqfc/noscrub/Barry.Baker/anaconda2/bin/conda install -c conda-forge pyresample`




    Traceback (most recent call last):
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 474, in execute
        self._execute_action(action)
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 490, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/naqfc/noscrub/Barry.Baker/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string```

What is happening?  Installing packages without the -c seems to work fine.

**Comment by nsoranzo** [comment]
AWS S3 is down, which means that anaconda.conda.org is too.

**Comment by kalefranz** [comment]
The root cause is that Amazon S3 is down, and so anaconda.org is down (along with half the internet). This will be resolved when S3 is back online.
