### ISSUE TITLE
Error while installing: can someone please help

### ISSUE THREAD

**Issue by apatkar** [conda/conda#4768]
Following is the error from my terminal

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/<Userid>/miniconda3  (writable)
    default environment : /Users/<Userid>/miniconda3/envs/IntroToTensorFlow
       envs directories : /Users/<Userid>/miniconda3/envs
                          /Users/<Userid>/.conda/envs
          package cache : /Users/<Userid>/miniconda3/pkgs
                          /Users/<Userid>/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

`$ /Users/<Userid>/miniconda3/envs/IntroToTensorFlow/bin/conda install -c conda-forge tensorflow`

    Traceback (most recent call last):
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 138, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
        raise err
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
        sock.connect(sa)
    socket.timeout: timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 281, in connect
        conn = self._new_conn()
      File "/Users/<Userid>/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 143, in _new_conn
        (self.host, self.timeout))
    requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10a5aedd8>, '**Connection to binstar-cio-packages-prod.s3.amazonaws.com timed out. (connect timeout=9.15**)')

**Comment by kalefranz** [comment]
The root cause is that Amazon S3 is down, and so anaconda.org is down (along with half the internet). This will be resolved when S3 is back online.

**Comment by apatkar** [comment]
Thanks
