### ISSUE TITLE
unexpected error raised by conda

### ISSUE THREAD

**Issue by mopitsch** [conda/conda#4780]
I installed anaconda2 (64-bit Linux version) and got the following error messages when running conda in the terminal:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/mopitsch/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 519, in get_info
    from conda.cli import conda_argparse
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 14, in <module>
    from .read import get_json_content
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 20, in <module>
    from ...models.channel import Channel
  File "/home/mopitsch/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
ImportError: No module named packages.urllib3.util

**Comment by kalefranz** [comment]
Apparently the `requests` package was somehow uninstalled or corrupted in your environment.  The easiest solution will be to download the latest Miniconda installer and run it overtop your current installation.

    curl https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o ~/miniconda2.sh
    bash ~/miniconda2.sh -bfp /home/mopitsch/anaconda2

**Comment by mopitsch** [comment]
Unfortunately, this did not solve my problem at all, the problem still exists...

**Comment by mopitsch** [comment]
Now I solved it, apparently there was a problem with an installation in .local

**Comment by kchangdistil** [comment]
@mopitsch How did you solve this? I'm having a similar issue.
