### ISSUE TITLE
conda-convert: TypeError: "delimiter" must be string, not unicode

### ISSUE THREAD

**Issue by H0R5E** [conda/conda#4781]
Hi, I encountered a bug when issuing the command "conda convert -p win-64 path/to/win-32/package"

```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-convert-script.py", line 5, in 
    <module>sys.exit(conda_build.cli.main_convert.main())
  File "C:\Anaconda\lib\site-packages\conda_build\cli\main_convert.py", line 129, in main
    return execute(sys.argv[1:])
  File "C:\Anaconda\lib\site-packages\conda_build\cli\main_convert.py", line 125, in execute
    api.convert(f, **args.__dict__)
  File "C:\Anaconda\lib\site-packages\conda_build\api.py", line 231, in convert
    dry_run=dry_run, dependencies=dependencies)
  File "C:\Anaconda\lib\site-packages\conda_build\convert.py", line 444, in conda_convert
    file_map = get_pure_py_file_map(t, platform)
  File "C:\Anaconda\lib\site-packages\conda_build\convert.py", line 271, in get_pure_py_file_map
    dialect=csv_dialect)
  File "C:\Anaconda\lib\csv.py", line 79, in __init__
    self.reader = reader(f, dialect, *args, **kwds)
TypeError: "delimiter" must be string, not unicode
```

conda info:

```
Current conda install:

               platform : win-32
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.1.5
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\Winston\AppData\Local\conda\conda\envs
                          C:\Users\Winston\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\Winston\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/dataonlygreater/win-32
                          https://conda.anaconda.org/dataonlygreater/noarch
            config file : C:\Users\Winston\.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.12 Windows/Vista Windows/6.0.6002
```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1784
