### ISSUE TITLE
JSON Error: Package Installation Failed Suddenly & Doesn't Install Anymore

### ISSUE THREAD

**Issue by avijitashe** [conda/conda#4787]
I was greeted saying "An unexpected error has occurred" and to post the below lines here for tracking bugs. The errors are thrown after pressing "y" to install when asked for "Proceed ([y]/n)?" after it has found the packages. It ran once, but the it freezed in between, and since then any attempt to install again, throws these errors.
```
Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 1.18.2
         python version : 2.7.11.final.0
       requests version : 2.13.0
       root environment : /home/avijit/anaconda2  (writable)
    default environment : /home/avijit/anaconda2/envs/tensorflow
       envs directories : /home/avijit/anaconda2/envs
                          /home/avijit/.conda/envs
          package cache : /home/avijit/anaconda2/pkgs
                          /home/avijit/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.11 Linux/3.2.0-123-generic debian/wheezy/sid glibc/2.15
                UID:GID : 1001:1001



`$ /home/avijit/anaconda2/envs/tensorflow/bin/conda install -c conda-forge tensorflow=1.0.0`




    Traceback (most recent call last):
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/home/avijit/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 106, in read_index_json
        record = IndexRecord(**json.load(fi))  # TODO: change to LinkedPackageData
      File "/home/avijit/anaconda2/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/home/avijit/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/home/avijit/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/avijit/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

```

**Comment by kalefranz** [comment]
Try `conda clean --packages` and then try again. Let me know how it goes.

**Comment by avijitashe** [comment]
Hello! I did SOLVE it.
```
conda clean -i 
conda clean -l
```
so, after clearing the index and locked files, I tried reinstalling, and it worked fine. The -p or --packages, told that it won't look for symlinked packges and shall remove everything, so was bit hesitant to do it.

Thanks for the idea @kalefranz, though !
