### ISSUE TITLE
problem with installing anaconda-navigator on Ubuntu

### ISSUE THREAD

**Issue by krzysztofzm** [conda/conda#4800]
platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/jaga-cichy/anaconda3  (writable)
    default environment : /home/jaga-cichy/anaconda3
       envs directories : /home/jaga-cichy/anaconda3/envs
          package cache : /home/jaga-cichy/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jaga-cichy/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-65-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

`$ /home/jaga-cichy/anaconda3/bin/conda install anaconda-navigator`

    Traceback (most recent call last):
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 401, in <listcomp>
        for url in urls]
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 141, in func
        res = f(*args, **kwargs)
      File "/home/jaga-cichy/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/jaga-cichy/anaconda3/pkgs/cache/9ca791dd.json'

**Comment by kalefranz** [comment]
This is fixed on conda 4.3.13.  You'll probably need `sudo` to update conda, but only use it once in this instance.  So `sudo /home/jaga-cichy/anaconda3/binconda update conda` and then you'll probably want

    sudo chown -R 1000:1000 /home/jaga-cichy/anaconda3

**Comment by krzysztofzm** [comment]
Yes, I tried it with sudo, but with "sudo" I'm getting a reply that "/home/jaga-cichy/anaconda3/binconda:" command was not found. 
At the beginning the error was that my user doesn't have access rights to that location. So I changed the access rights to the anaconda3 directory. And now I have a problem with the error described in the first post.

**Comment by kalefranz** [comment]
sorry, there was a typo...  You need

    sudo /home/jaga-cichy/anaconda3/bin/conda update conda

notice the missing `/`

**Comment by pinkman61** [comment]
sudo /anaconda2/bin/conda update conda
-------------------------------------------------------------------
sudo: /home/anaconda2/bin/conda: command not found

Not working
