### ISSUE TITLE
KeyError: create conda environment using explicit specification

### ISSUE THREAD

**Issue by mcgarrr** [conda/conda#4802]
Encountered a keyerror when attempting to create an env using explicit specification built from another platform. Spec file used:

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.continuum.io/pkgs/free/win-64/boto-2.45.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/bz2file-0.98-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/bzip2-1.0.6-vc9_3.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/click-6.7-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cligj-0.2.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/curl-7.52.1-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/cycler-0.10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/decorator-4.0.11-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/fiona-1.6.0-np110py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/freetype-2.5.5-vc9_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/functools32-3.2.3.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/gdal-2.0.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/geos-3.5.0-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/hdf4-4.2.12-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/hdf5-1.8.15.1-vc9_4.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/icu-57.1-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jinja2-2.9.5-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/jpeg-8d-vc9_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/kealib-1.4.6-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/libgdal-2.0.0-vc9_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/libnetcdf-4.3.3.1-vc9_4.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/libpng-1.6.27-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/libtiff-4.0.6-vc9_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/markupsafe-0.23-py27_2.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/matplotlib-1.5.1-np110py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/mkl-2017.0.1-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/networkx-1.11-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/numpy-1.10.1-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/openssl-1.0.2k-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pandas-0.18.1-np110py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pillow-3.4.2-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pip-9.0.1-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/proj4-4.9.2-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyparsing-2.1.4-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pyqt-4.10.4-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/python-2.7.13-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/python-dateutil-2.6.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/pytz-2016.10-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/qt-5.6.2-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/requests-2.13.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scikit-image-0.12.3-np110py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/scipy-0.16.0-np110py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/setuptools-27.2.0-py27_1.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/sip-4.18-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/six-1.10.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/smart_open-1.3.5-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/subprocess32-3.2.7-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/tk-8.5.18-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/vs2008_runtime-9.00.30729.5054-0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/wheel-0.29.0-py27_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/xerces-c-3.1.4-vc9_0.tar.bz2
https://repo.continuum.io/pkgs/free/win-64/zlib-1.2.8-vc9_3.tar.bz2
```

Conda command:

```
C:\Users\demo\dev>conda create --name demo_env --file specfile.txt
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Apps\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Apps\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Apps\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Apps\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 57, in execute
    install(args, parser, 'create')
  File "C:\Apps\Anaconda3\lib\site-packages\conda\cli\install.py", line 185, in install
    explicit(specs, prefix, verbose=not args.quiet, index_args=index_args)
  File "C:\Apps\Anaconda3\lib\site-packages\conda\misc.py", line 126, in explicit
    index.update(get_index(**index_args))
  File "C:\Apps\Anaconda3\lib\site-packages\conda\api.py", line 22, in get_index
    channel_urls = normalize_urls(channel_urls, platform, offline)
  File "C:\Apps\Anaconda3\lib\site-packages\conda\config.py", line 250, in normalize_urls
    url = urls[0]
KeyError: 0
``` 

Conda info:

```
C:\Users\demo\dev>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Apps\Anaconda3  (writable)
  default environment : C:\Apps\Anaconda3
     envs directories : C:\Apps\Anaconda3\envs
        package cache : C:\Apps\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```

**Comment by nehaljwani** [comment]
@mcgarrr  `4.1.6` seems to pretty old. Have you tried upgrading your version of conda? Do you still face the same issue?
