### ISSUE TITLE
'InsecureRequestWarning'

### ISSUE THREAD

**Issue by ChaitanyaCixLive** [conda/conda#4803]
Traceback (most recent call last):
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 98, in _main
    imported = importlib.import_module(module)
  File "/home/chaitanya/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/egg_info.py", line 15, in <module>
    from .misc import rel_path
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/misc.py", line 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 9, in <module>
    from .repodata import collect_all_repodata
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 22, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name 'InsecureRequestWarning'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/chaitanya/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 607, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 561, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 531, in get_info
    args.func(args, p)
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 142, in execute
    from conda.api import get_index
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 9, in <module>
    from .repodata import collect_all_repodata
  File "/home/chaitanya/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 22, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: cannot import name 'InsecureRequestWarning'

**Comment by nehaljwani** [comment]
https://github.com/conda/conda/issues/1656

**Comment by kalefranz** [comment]
Your requests library is out of date.  Try either

    CONDA_SSL_VERIFY=false conda update conda requests

or

    pip install -U requests
