### ISSUE TITLE
conda update anaconda: unexpected error

### ISSUE THREAD

**Issue by roshni-b** [conda/conda#4804]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Users\Roshni\Anaconda3  (writable)
    default environment : C:\Users\Roshni\Anaconda3
       envs directories : C:\Users\Roshni\Anaconda3\envs
                          C:\Users\Roshni\AppData\Local\conda\conda\envs
                          C:\Users\Roshni\.conda\envs
          package cache : C:\Users\Roshni\Anaconda3\pkgs
                          C:\Users\Roshni\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Roshni\Anaconda3\Scripts\conda-script.py update anaconda`

    Traceback (most recent call last):
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\core\link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\core\link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Users\Roshni\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Roshni\\Anaconda3\\pkgs\\notebook-4.3.1-py35_1\\info\\index.json'

**Comment by Zorro-Lin-7** [comment]
Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 0+unknown
         python version : 3.5.2.final.0
       requests version : 2.9.1
       root environment : /Users/mac/anaconda  (writable)
    default environment : /Users/mac/anaconda
       envs directories : /Users/mac/anaconda/envs
          package cache : /Users/mac/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/mac/anaconda/bin/conda update conda`




    Traceback (most recent call last):
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
        body=body, headers=headers)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 784, in _validate_conn
        conn.connect()
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 252, in connect
        ssl_version=resolved_ssl_version)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/ssl_.py", line 305, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "/Users/mac/anaconda/lib/python3.5/ssl.py", line 377, in wrap_socket
        _context=self)
      File "/Users/mac/anaconda/lib/python3.5/ssl.py", line 752, in __init__
        self.do_handshake()
      File "/Users/mac/anaconda/lib/python3.5/ssl.py", line 988, in do_handshake
        self._sslobj.do_handshake()
      File "/Users/mac/anaconda/lib/python3.5/ssl.py", line 633, in do_handshake
        self._sslobj.do_handshake()
    ConnectionResetError: [Errno 54] Connection reset by peer
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 376, in send
        timeout=timeout
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 629, in urlopen
        release_conn=release_conn, **response_kw)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 609, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 273, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/cryptography-1.7.1-py35_0.tar.bz2 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 394, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(6.1, 60))
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 480, in get
        return self.request('GET', url, **kwargs)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/requests/adapters.py", line 437, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/cryptography-1.7.1-py35_0.tar.bz2 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer')))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 405, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/cryptography-1.7.1-py35_0.tar.bz2 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))): https://repo.continuum.io/pkgs/free/osx-64/cryptography-1.7.1-py35_0.tar.bz2
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/mac/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/mac/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/osx-64/cryptography-1.7.1-py35_0.tar.bz2 (Caused by ProtocolError('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))): https://repo.continuum.io/pkgs/free/osx-64/cryptography-1.7.1-py35_0.tar.bz2

**Comment by kalefranz** [comment]
Intermittent HTTP error, likely due to flakey internet connection.  Retrying will probably resolve the issue.  Conda 4.3 has longer default timeouts that are also configurable.

**Comment by iranmatlab** [comment]
Hello Friends
I have solved the problem.

This error cause because of different version of python in anaconda and installed python on your system.

when you upgrade anaconda to new version, It has been written in newest version on pyhton (3.6 for me) but i have installed lower version (3.5 for me) of python in my system, so it cause fail in run.

so download newest version of python and install it, then 
**rename** folder of last python to a different name such as "pythoonn"

then conda command will works.
