### ISSUE TITLE
Unexpected error doing `conda update --all` on Windows 7

### ISSUE THREAD

**Issue by empirical-bayesian** [conda/conda#4811]
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 1.8.2
         python version : 3.4.3.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\Jan\AppData\Local\conda\conda\envs
                          C:\Users\Jan\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\Jan\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.4.3 Windows/7 Windows/6.1.7601



`$ C:\Anaconda3\Scripts\conda-script.py update --all`




    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 106, in read_index_json
        record = IndexRecord(**json.load(fi))  # TODO: change to LinkedPackageData
      File "C:\Anaconda3\lib\json\__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Anaconda3\lib\json\__init__.py", line 318, in loads
        return _default_decoder.decode(s)
      File "C:\Anaconda3\lib\json\decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Anaconda3\lib\json\decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)


c:\Anaconda3>

```

**Comment by kalefranz** [comment]
I think `conda clean --packages` should fix your problem.  Can you try that and let me know?

**Comment by randroth** [comment]
Hello, 

conda clean --packages did not work for me.  Based on the referencing of these directories, is it possible that Anaconda is trying to install to a different defaulting directory name and failing to update because the existing installation was made using a previous version with the directory names from the previous version of Anaconda? Thanks.

**Comment by kalefranz** [comment]
@randroth Please file a new issue with your stack trace, `conda info`, and other details to reproduce if you're still having your problem.
