### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by charlesfox97** [conda/conda#4820]
I tried cloning my python 3.4 environment, but failed.  My goal was to upgrade to python 3.5 while keeping as much of the set up I've been using in 3.4 as possible.  

First, I attempted "conda install python=3.5".  It failed due to a dependency on backports_abc.  Nexte, I tried coping the 3.4 env, but that resulted in the error message below.  My next step was going to be to remove backports_abc from the new environment before running "conda install python=3.5" again.  

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.8
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : C:\Users\Charles Fox\Anaconda2  (writable)
    default environment : C:\Users\Charles Fox\Anaconda2\envs\py3
       envs directories : C:\Users\Charles Fox\Anaconda2\envs
          package cache : C:\Users\Charles Fox\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.12 Windows/10 Windows/10.0.14393

`$ C:\Users\Charles Fox\Anaconda2\Scripts\conda-script.py create --name py35 --clone py3`

    Traceback (most recent call last):
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\cli\install.py", line 200, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\cli\install.py", line 69, in clone
        index_args=index_args)
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\misc.py", line 306, in clone_env
        force_extract=False, index_args=index_args)
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\misc.py", line 93, in explicit
        supplement_index_with_cache(index, ())
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\core\index.py", line 92, in supplement_index_with_cache
        meta = read_index_json(pkg_dir)
      File "C:\Users\Charles Fox\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'C:\\Users\\Charles Fox\\Anaconda2\\pkgs\\gevent-1.2.1-py27_0\\info\\index.json'

**Comment by kalefranz** [comment]
`conda clean --packages` should fix this issue.  But also `conda update conda` to 4.3.14.
