### ISSUE TITLE
Windows numpy installation: IOError: [Errno 22] invalid mode or filename

### ISSUE THREAD

**Issue by JonSargent** [conda/conda#4822]
Following installation instructions here: http://hdfeos.org/software/pyhdf.php

conda install numpy fails while linking packages:

```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>

  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main

  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 45, in execute

  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 278, in install
    for pkg in sorted(e.pkgs):
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 436, in execute_actions
    channel_priority_map=None, is_update=False):  # pragma: no cover
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 418, in execute_plan

  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 374, in link

  File "C:\Anaconda\lib\site-packages\conda\install.py", line 486, in link

  File "C:\Anaconda\lib\site-packages\conda\install.py", line 210, in update_prefix

IOError: [Errno 22] invalid mode ('rb') or filename: 'C:\\Anaconda\\"Lib\\site-packages\\numpy\\__config__.py"'
```

**Comment by JonSargent** [comment]
Nevermind, the hdfeos.org page linked to an older anaconda installer.  The latest version (4.3.0) works fine.
