### ISSUE TITLE
Cannot import config parser while launching jupyter notebook

### ISSUE THREAD

**Issue by ItsAnkit** [conda/conda#4823]
While i am trying to launch jupyter notebook, my command shell is showing following error :
hduser@ubuntu:~$ jupyter notebook
[I 03:49:08.691 NotebookApp] [nb_conda_kernels] enabled, 3 kernels found
[I 03:49:12.544 NotebookApp] [nb_anacondacloud] enabled
[I 03:49:12.586 NotebookApp] [nb_conda] enabled
[W 03:49:12.613 NotebookApp] Error loading server extension nbpresent
    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1117, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/opt6/anaconda2/lib/python2.7/site-packages/nbpresent/__init__.py", line 5, in <module>
        from nbconvert.exporters.export import exporter_map
      File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/opt/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
      File "/opt/anaconda2/lib/python2.7/site-packages/entrypoints.py", line 16, in <module>
        from backports import configparser
    ImportError: cannot import name configparser
[I 03:49:12.692 NotebookApp] Serving notebooks from local directory: /home/hduser
[I 03:49:12.692 NotebookApp] 0 active kernels 
[I 03:49:12.693 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=5b559f4a7694f8004e6846198b1094e99e04327e3339

Apart from this, When i am trying to run my code, it's shoiwng Py4JavaError....

**Comment by jmshi** [comment]
I have the similar error: 

> jupyter-notebook 

[I 16:07:38.705 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 16:07:39.270 NotebookApp] [nb_anacondacloud] enabled
[I 16:07:39.272 NotebookApp] [nb_conda] enabled
[W 16:07:39.273 NotebookApp] Error loading server extension nbpresent
    Traceback (most recent call last):
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 1117, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/site-packages/nbpresent/__init__.py", line 5, in <module>
        from nbconvert.exporters.export import exporter_map
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/site-packages/nbconvert/__init__.py", line 4, in <module>
        from .exporters import *
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/__init__.py", line 1, in <module>
        from .base import (export, get_exporter,
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/site-packages/nbconvert/exporters/base.py", line 8, in <module>
        import entrypoints
      File "/home/jmshi/local/anaconda/anaconda2/lib/python2.7/site-packages/entrypoints.py", line 16, in <module>
        from backports import configparser
    ImportError: cannot import name configparser

**Comment by jmshi** [comment]
this solves my problem:
conda install configparser=3.5.0b2

which switches configparser 3.5.0-py27_0 --> 3.5.0b2-py27_1

**Comment by ItsAnkit** [comment]
Thanks, it worked....
