### ISSUE TITLE
Unable to install conda package from root of drive

### ISSUE THREAD

**Issue by snorfalorpagus** [conda/conda#4834]
On Windows it's not possible to install a local package (from .tar.bz2) if the package is located in the root of a drive. This is probably an error related to how the package name is separated from the folder on Windows. See full traceback below. You can see it's trying to create a folder beginning with ":".

The work-around is to move the package to folder somewhere else.

```
(python36) D:\>conda install glpk-4.61-py36_0.tar.bz2
Fetching packages ...
WARNING conda.lock:touch(53): Failed to create lock, do not run conda in parallel processes [errno 2
2]
An unexpected error has occurred.                  | ETA:  --:--:--   0.00  B/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.4
         python version : 3.5.2.final.0
       requests version : 2.9.1
       root environment : C:\Miniconda3-x64  (writable)
    default environment : C:\Miniconda3-x64\envs\python36
       envs directories : C:\Miniconda3-x64\envs
          package cache : C:\Miniconda3-x64\pkgs
           channel URLs : https://conda.anaconda.org/snorfalorpagus/win-64
                          https://conda.anaconda.org/snorfalorpagus/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\arno6545\.condarc
           offline mode : False



`$ C:\Miniconda3-x64\Scripts\conda-script.py install glpk-4.61-py36_0.tar.bz2`




    Traceback (most recent call last):
      File "C:\Miniconda3-x64\lib\site-packages\conda\fetch.py", line 419, in download
        with open(pp, 'wb') as fo:
    OSError: [Errno 22] Invalid argument: 'C:\\Miniconda3-x64\\pkgs\\:glpk-4.61-py36_0.tar.bz2.part'


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Miniconda3-x64\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_h
andler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Miniconda3-x64\lib\site-packages\conda\cli\install.py", line 209, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "C:\Miniconda3-x64\lib\site-packages\conda\misc.py", line 188, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "C:\Miniconda3-x64\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Miniconda3-x64\lib\site-packages\conda\instructions.py", line 135, in execute_instruc
tions
        cmd(state, arg)
      File "C:\Miniconda3-x64\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Miniconda3-x64\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Miniconda3-x64\lib\site-packages\conda\fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Miniconda3-x64\\pkgs\\:gl
pk-4.61-py36_0.tar.bz2.part' for writing ([Errno 22] Invalid argument: 'C:\\Miniconda3-x64\\pkgs\\:g
lpk-4.61-py36_0.tar.bz2.part').
```

**Comment by nehaljwani** [comment]
Do you face the same issue with conda `4.3.14`?

**Comment by snorfalorpagus** [comment]
This seems to be fixed in newer versions. I hadn't appreciated that the conda from conda-forge was lagging behind the defaults release.

https://github.com/conda-forge/conda-feedstock/issues/16
