### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by kevinlu1211** [conda/conda#4847]
I was wondering why I am getting this error:

```
    Traceback (most recent call last):
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 98, in _main
        imported = importlib.import_module(module)
      File "/Users/kevinlu/miniconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 665, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 20, in <module>
        from ..egg_info import get_egg_info
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/egg_info.py", line 15, in <module>
        from .misc import rel_path
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/misc.py", line 19, in <module>
        from .core.index import get_index, _supplement_index_with_cache
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/core/index.py", line 9, in <module>
        from .repodata import collect_all_repodata
      File "/Users/kevinlu/miniconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 21, in <module>
        from requests.packages.urllib3.exceptions import InsecureRequestWarning
    ImportError: cannot import name 'InsecureRequestWarning'

```

**Comment by kalefranz** [comment]
`conda update requests`
