### ISSUE TITLE
When creating a new conda env get unexpected error

### ISSUE THREAD

**Issue by VChopra1010** [conda/conda#4851]
INFO conda.common.io:captured(59): overtaking stderr and stdout
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : win-32
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.1.6
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3  (w
ritable)
    default environment : C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\env
s
          package cache : C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\pkg
s
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-32  (of
fline)
                          https://conda.anaconda.org/anaconda-fusion/noarch  (of
fline)
                          https://repo.continuum.io/pkgs/free/win-32  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/win-32  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/win-32  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
                          https://repo.continuum.io/pkgs/msys2/win-32  (offline)

                          https://repo.continuum.io/pkgs/msys2/noarch  (offline)

            config file : C:\Users\BZDHSTK\.condarc
           offline mode : True
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Windows/6.1.7601

`$ C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py create -m --offline --debug -n py352 c:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\pkgs\python-3.5.2-0.tar.bz2`

    Traceback (most recent call last):
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 188, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\misc.py", line 101, in explicit
        execute_actions(actions, index, verbose=verbose)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 85, in read_package_info
        paths_data=paths_data,
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 831, in __setattr__
        super(ImmutableEntity, self).__setattr__(attribute, value)
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\Users\BZDHSTK\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for url cannot be None.

**Comment by kalefranz** [comment]
This issue has been resolved. `conda update conda`
