### ISSUE TITLE
ValueError: unknown url type: defaults/linux-64/repodata.json.bz2

### ISSUE THREAD

**Issue by eduOS** [conda/conda#4856]
```
An unexpected exceptional error has occurred, please consider sending the following traceback to the conda
 GitHub issue tracker at https://github.com/ContinuumIO/conda/issues

Traceback (most recent call last):
  File "/home/lerner/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/lerner/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 115, in main
    args.func(args, p)
  File "/home/lerner/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 57, in execute
    conda = Anaconda()
  File "/home/lerner/anaconda/lib/python2.7/site-packages/conda/anaconda.py", line 43, in __init__
    self._index = PackageIndex(fetch_index(self.channel_urls))
  File "/home/lerner/anaconda/lib/python2.7/site-packages/conda/remote.py", line 46, in fetch_index
    repodata = fetch_repodata(url)
  File "/home/lerner/anaconda/lib/python2.7/site-packages/conda/remote.py", line 29, in fetch_repodata
    fi = urllib2.urlopen(url + fn)
  File "/home/lerner/anaconda/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/lerner/anaconda/lib/python2.7/urllib2.py", line 392, in open
    protocol = req.get_type()
  File "/home/lerner/anaconda/lib/python2.7/urllib2.py", line 254, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: defaults/linux-64/repodata.json.bz2
```
What's wrong with my conda?

**Comment by nehaljwani** [comment]
Could you please share the output for `conda info -a`?

**Comment by tyler-thetyrant** [comment]
Closing as reporter vanished.
