### ISSUE TITLE
can't install seaborn package through ' ! conda install seaborn' in Yhat Rodeo

### ISSUE THREAD

**Issue by BandiSreenath** [conda/conda#4858]
IOError: [Errno 13] Permission denied: u'C:\\ProgramData\\Anaconda2\\pkgs\\cache\\2116b818.json'

#################### The command window throws this message #############
Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\defaultuser0\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.13.0 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py install seaborn`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'C:\\ProgramData\\Anaconda2\\pkgs\\cache\\2116b818.json'

**Comment by mingwandroid** [comment]
Please try:

conda update conda

Then try again.

**Comment by BandiSreenath** [comment]
##########The same has been happening######


C:\Users\defaultuser0>conda update conda
Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\defaultuser0\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.13.0 CPython/2.7.13 Windows/10 Windows/10.0.14393



`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py update conda`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'C:\\ProgramData\\Anaconda2\\pkgs\\cache\\2116b818.json'


C:\Users\defaultuser0>

**Comment by nehaljwani** [comment]
@BandiSreenath Try running the Anaconda Prompt as Administrator to update conda.

**Comment by BandiSreenath** [comment]
@nehaljwani  Conda update by running admin is successful. Thanks a lot.
But still seaborn con't be imported , even though it was installed already.
##### Take a look ######
! conda install seaborn
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\ProgramData\Anaconda2:
#
seaborn                   0.7.1                    py27_0

**Comment by nehaljwani** [comment]
What is the error when you try to import seaborn?
`python -c 'import seaborn'`
