### ISSUE TITLE
Traceback I do not understand

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [conda/conda#4866]
A colleague of mine is trying to set up qiime (according to this tutorial: http://qiime.org/install/install.html) and needs conda for that reason.

If he tries to use conda (for example `conda update` or the command below) he gets error messages like below.

Do you have an idea what the problem might be?

```bioinf@ags-wav-debian-MandS:~/Documents$ conda install -n bioinf conda-build
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/bioinf/miniconda2  (writable)
    default environment : /home/bioinf/miniconda2
       envs directories : /home/bioinf/miniconda2/envs
                          /home/bioinf/.conda/envs
          package cache : /home/bioinf/miniconda2/pkgs
                          /home/bioinf/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/bioinf/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/3.16.0-4-amd64 debian/8.7 glibc/2.19
                UID:GID : 1000:1000



$ /home/bioinf/miniconda2/bin/conda install -n bioinf conda-build




    Traceback (most recent call last):
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 130, in install
        context.validate_configuration()
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 830, in validate_configuration
        raise_errors(tuple(chain.from_iterable((errors, post_errors))))
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 828, in <genexpr>
        for name in self.parameter_names)
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 821, in _collect_validation_error
        func(*args, **kwargs)
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 446, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 662, in _merge
        for match in relevant_matches)
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 662, in <genexpr>
        for match in relevant_matches)
      File "/home/bioinf/miniconda2/lib/python2.7/site-packages/conda/common/compat.py", line 100, in iteritems
        return d.iteritems(**kw)
    AttributeError: 'str' object has no attribute 'iteritems'
```

**Comment by MichaelsGITIGIT** [comment]
Solved, the proxy was set in the config file, but in a wrong format. Maybe you try to give a better error message?
