### ISSUE TITLE
conda update fails

### ISSUE THREAD

**Issue by kmario23** [conda/conda#4870]
❯❯ conda update --all                                                                                                                           ⏎
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/delete.py", line 15, in <module>
    from .read import get_json_content
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 23, in <module>
    from ...models.channel import Channel
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "/home/mario/anaconda3/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/mario/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/mario/anaconda3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/mario/anaconda3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/mario/anaconda3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCRYPT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mario/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 607, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 561, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 531, in get_info
    args.func(args, p)
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 142, in execute
    from conda.api import get_index
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/core/path_actions.py", line 32, in <module>
    from ..gateways.download import download
  File "/home/mario/anaconda3/lib/python3.5/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/home/mario/anaconda3/lib/python3.5/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/mario/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/home/mario/anaconda3/lib/python3.5/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/home/mario/anaconda3/lib/python3.5/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/home/mario/anaconda3/lib/python3.5/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/home/mario/anaconda3/lib/python3.5/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    if not getattr(lib, condition):
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'Cryptography_HAS_SCRYPT'

This issue has been arising not just with `update` but with any conda command

**Comment by kalefranz** [comment]
Usually you don't need to uninstall.  Just install miniconda overtop the current install.  In this case

    curl https://repo.continuum.io/miniconda/Miniconda2-4.2.15-MacOSX-x86_64.sh ~/miniconda35.sh
    bash ~/miniconda35.sh -bfp /home/mario/anaconda3
    conda update conda
