### ISSUE TITLE
Got error when installing Miniconda 3-4.1.11-Linux-x86_64.sh

### ISSUE THREAD

**Issue by hsaputra** [conda/conda#4874]
Suddenly, today start getting error when installing Miniconda from our Jenkins CI from `https://repo.continuum.io/miniconda/Miniconda3-4.1.11-Linux-x86_64.sh` and ran conda install --quiet --yes conda==4.1.11

The error stack:

```

[91mTraceback (most recent call last):
  File "/opt/conda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/opt/conda/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/conda/lib/python3.5/site-packages/conda/plan.py", line 599, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.5/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/opt/conda/lib/python3.5/site-packages/conda/install.py", line 1108, in link
    create_meta(prefix, dist, info_dir, meta_dict)
  File "/opt/conda/lib/python3.5/site-packages/conda/install.py", line 489, in create_meta
    load_linked_data(prefix, dist, meta)
  File "/opt/conda/lib/python3.5/site-packages/conda/install.py", line 903, in load_linked_data
    channel, schannel = url_channel(url)
  File "/opt/conda/lib/python3.5/site-packages/conda/config.py", line 361, in url_channel
    schannel = canonical_channel_name(channel)
  File "/opt/conda/lib/python3.5/site-packages/conda/config.py", line 337, in canonical_channel_name
    elif any(channel.startswith(i) for i in get_local_urls(clear_cache=False)):
  File "/opt/conda/lib/python3.5/site-packages/conda/config.py", line 181, in get_local_urls
    from conda_build.config import croot
  File "/opt/conda/lib/python3.5/site-packages/conda_build/config.py", line 15, in <module>
    from .conda_interface import root_dir, root_writable, subdir, cc_platform, cc_conda_build
  File "/opt/conda/lib/python3.5/site-packages/conda_build/conda_interface.py", line 205, in <module>
    get_local_urls = cc.get_local_urls
NameError: name 'cc' is not defined
```

**Comment by RafaelGCPP** [comment]
Got the same errror after a conda update --all 

Cannot install anything anymore!

**Comment by kalefranz** [comment]
`conda update conda` then `conda update conda-build`.  The stack trace is coming from a version mismatch between conda and conda-build.
