### ISSUE TITLE
Conda List command throwing exceptions

### ISSUE THREAD

**Issue by ricobandy** [conda/conda#4876]
After updating using "conda update --all", when doing conda list, following exceptions was thrown:

C:\Users\echaqua>conda list
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\exceptions.
py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py
", line 98, in _main
    imported = importlib.import_module(module)
  File "E:\Program files\Continuum\Anaconda3\lib\importlib\__init__.py", line 12
6, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\cli\main_li
st.py", line 20, in <module>
    from ..egg_info import get_egg_info
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\egg_info.py
", line 15, in <module>
    from .misc import rel_path
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\misc.py", l
ine 19, in <module>
    from .core.index import get_index, _supplement_index_with_cache
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\core\index.
py", line 8, in <module>
    from .package_cache import PackageCache
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\core\packag
e_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\core\path_a
ctions.py", line 31, in <module>
    from ..gateways.download import download
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\gateways\do
wnload.py", line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
ImportError: No module named 'requests.exceptions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Program files\Continuum\Anaconda3\Scripts\conda-script.py", line 5, i
n <module>
    sys.exit(conda.cli.main())
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py
", line 164, in main
    return conda_exception_handler(_main, *args)
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\exceptions.
py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\exceptions.
py", line 543, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\exceptions.
py", line 513, in get_info
    args.func(args, p)
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\cli\main_in
fo.py", line 148, in execute
    from conda.api import get_index
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\api.py", li
ne 1, in <module>
    from .core.index import get_index
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\core\index.
py", line 8, in <module>
    from .package_cache import PackageCache
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\core\packag
e_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\core\path_a
ctions.py", line 31, in <module>
    from ..gateways.download import download
  File "E:\Program files\Continuum\Anaconda3\lib\site-packages\conda\gateways\do
wnload.py", line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
ImportError: No module named 'requests.exceptions'

C:\Users\echaqua>

**Comment by ricobandy** [comment]
any support to help fix this issue.

**Comment by kalefranz** [comment]
The `requests` package has somehow been removed from your environment, and conda is now hosed.  You'll have to download a miniconda installer and run it overtop your current install.  `pip install requests` might work too actually.
