### ISSUE TITLE
I can't install VIBes nor Pyibes

### ISSUE THREAD

**Issue by acasares** [conda/conda#4882]
Dear sirs:

I have Anaconda installed in my Windows 10 laptop, but I'm having problems trying to install it in my two versions of Spider (2 and 3).
Furthermore, now Spyder 3 aborts from the bootstrap, with some flashing message about "ImportError: DLL load failed: No se puede encontrar el módulo especificado." 

I'll be much oblidged if you help me with this issue.

Sincerely yours,

Alejandro Casares M
acasares@puce.edu.ec

!conda install -c benensta vibes vibes-bin
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "D:\Anaconda 3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "D:\Anaconda 3\lib\site-packages\conda\cli\main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "D:\Anaconda 3\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "D:\Anaconda 3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "D:\Anaconda 3\lib\site-packages\conda\cli\common.py", line 22, in <module>
    from ..resolve import MatchSpec
  File "D:\Anaconda 3\lib\site-packages\conda\resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "D:\Anaconda 3\lib\site-packages\conda\logic.py", line 32, in <module>
    import pycosat
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Anaconda 3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "D:\Anaconda 3\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "D:\Anaconda 3\lib\site-packages\conda\exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "D:\Anaconda 3\lib\site-packages\conda\exceptions.py", line 543, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "D:\Anaconda 3\lib\site-packages\conda\exceptions.py", line 502, in get_info
    from conda.cli import conda_argparse
  File "D:\Anaconda 3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "D:\Anaconda 3\lib\site-packages\conda\cli\common.py", line 22, in <module>
    from ..resolve import MatchSpec
  File "D:\Anaconda 3\lib\site-packages\conda\resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "D:\Anaconda 3\lib\site-packages\conda\logic.py", line 32, in <module>
    import pycosat
ImportError: DLL load failed: No se puede encontrar el módulo especificado.

**Comment by acasares** [comment]
Hi.

Excuse me: the laptop is not with Windows 10 but with Windows 7.

**Comment by kalefranz** [comment]
The error message is that `pycosat` can't be imported.  Your installation has become corrupted.  You'll need to download a miniconda3 installer and run it overtop your current install.
