### ISSUE TITLE
problems using conda

### ISSUE THREAD

**Issue by thomasgas** [conda/conda#4885]
I had a problem using conda, which disappears if I run the same command connecting via ssh from another computer.

$ conda 

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/tgaspar/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 607, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 561, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 520, in get_info
    from conda.cli import conda_argparse
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/cli/common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/core/linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 15, in <module>
    from .read import get_json_content
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 23, in <module>
    from ...models.channel import Channel
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 49, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 52, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 175, in <module>
    _verify_openssl_version(Binding.lib.SSLeay())
  File "/home/tgaspar/anaconda2/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 162, in _verify_openssl_version
    "You are linking against OpenSSL 1.0.0, which is no longer "
RuntimeError: You are linking against OpenSSL 1.0.0, which is no longer support by the OpenSSL project. You need to upgrade to a newer version of OpenSSL.

**Comment by tyler-thetyrant** [comment]
Which version of conda are you using?
