### ISSUE TITLE
Conda clone error 

### ISSUE THREAD

**Issue by jkahn1** [conda/conda#4891]
I am getting the following error when trying to clone an environment from another user.
conda create --name xgboost --clone /home/ethan/anaconda/envs/xgboost/bin/python

Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : /home/jessicakahn/anaconda2  (writable)
    default environment : /home/jessicakahn/anaconda2
       envs directories : /home/jessicakahn/anaconda2/envs
                          /home/jessicakahn/.conda/envs
          package cache : /home/jessicakahn/anaconda2/pkgs
                          /home/jessicakahn/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.12 Linux/3.4.40-birchbox debian/6.0.9 glibc/2.11.3
                UID:GID : 1204:1204

Traceback (most recent call last):
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 212, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 57, in clone
        raise DirectoryNotFoundError(src_arg, 'no such directory: %s' % src_arg, json)
    TypeError: __init__() takes exactly 2 arguments (4 given)

**Comment by jkahn1** [comment]
I am getting the following error when trying to clone an environment from another user.
conda create --name xgboost --clone /home/ethan/anaconda/envs/xgboost/bin/python

Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : /home/jessicakahn/anaconda2  (writable)
    default environment : /home/jessicakahn/anaconda2
       envs directories : /home/jessicakahn/anaconda2/envs
                          /home/jessicakahn/.conda/envs
          package cache : /home/jessicakahn/anaconda2/pkgs
                          /home/jessicakahn/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.12 Linux/3.4.40-birchbox debian/6.0.9 glibc/2.11.3
                UID:GID : 1204:1204

Traceback (most recent call last):
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 212, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/home/jessicakahn/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 57, in clone
        raise DirectoryNotFoundError(src_arg, 'no such directory: %s' % src_arg, json)
    TypeError: __init__() takes exactly 2 arguments (4 given)
