### ISSUE TITLE
OpenSSL error when updating

### ISSUE THREAD

**Issue by nmeibergen** [conda/conda#4892]
Hi all,

I just installed Anaconda from scratch and tried installing another packages. That however gave me the error:

OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory')
, ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_cer
tificate_file', 'system lib')]

This seemed to occur at everything I try in the command window. In particular I tried updating anaconda and setting ssl_verify to false. As a side note I am working from a corporate laptop so it wouldn't surprise me if it is related to security issues. Find below the response I got when trying conda update conda. 

Thank you for your help!

```
C:\Users\DelsingG>conda update conda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
 
    https://github.com/conda/conda/issues
 
 
 
Current conda install:
 
               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
                          C:\Users\DelsingG\AppData\Local\conda\conda\envs
                          C:\Users\DelsingG\.conda\envs
          package cache : C:\Anaconda\pkgs
                          C:\Users\DelsingG\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\DelsingG\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/7 W
indows/6.1.7601
 
 
 
`$ C:\Anaconda\Scripts\conda-script.py update conda`
 
 
 
 
    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 573, in con
da_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 134, in _main
 
        exit_code = args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in
execute
        install(args, parser, 'update')
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 222, in in
stall
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 92, in get_
index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Anaconda\lib\site-packages\conda\core\index.py", line 111, in fet
ch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Anaconda\lib\site-packages\conda\core\repodata.py", line 74, in c
ollect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Anaconda\lib\site-packages\conda\core\repodata.py", line 463, in
_collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Anaconda\lib\site-packages\conda\core\repodata.py", line 463, in
<listcomp>
        for url, schan, pri in tasks]
      File "C:\Anaconda\lib\site-packages\conda\core\repodata.py", line 109, in
func
        res = f(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\core\repodata.py", line 442, in
fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Anaconda\lib\site-packages\conda\core\repodata.py", line 138, in
fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 501, in ge
t
        return self.request('GET', url, **kwargs)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 488, in re
quest
        resp = self.send(prep, **send_kwargs)
      File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 609, in se
nd
        r = adapter.send(request, **kwargs)
      File "C:\Anaconda\lib\site-packages\requests\adapters.py", line 423, in se
nd
        timeout=timeout
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpo
ol.py", line 594, in urlopen
        chunked=chunked)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpo
ol.py", line 350, in _make_request
        self._validate_conn(conn)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpo
ol.py", line 835, in _validate_conn
        conn.connect()
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\connection.p
y", line 323, in connect
        ssl_context=context)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py
", line 322, in ssl_wrap_socket
        context.load_cert_chain(certfile, keyfile)
      File "C:\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyop
enssl.py", line 397, in load_cert_chain
        self._ctx.use_certificate_file(certfile)
      File "C:\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 596, in use_cert
ificate_file
        _raise_current_error()
      File "C:\Anaconda\lib\site-packages\OpenSSL\_util.py", line 48, in excepti
on_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory')
, ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_cer
tificate_file', 'system lib')]
```

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```
