### ISSUE TITLE
Anaconda not working after install

### ISSUE THREAD

**Issue by basitafzal** [conda/conda#4905]
Traceback (most recent call last):
  File "C:\ProgramFiles\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\cli\main.py", line 167, in main
    return conda_exception_handler(_main, *args)
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\exceptions.py", line 633, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\exceptions.py", line 560, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\exceptions.py", line 519, in get_info
    from conda.cli import conda_argparse
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\cli\common.py", line 19, in <module>
    from ..core.linked_data import linked_data
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 11, in <module>
    from ..gateways.disk.delete import rm_rf
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\gateways\disk\delete.py", line 14, in <module>
    from .read import get_json_content
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\gateways\disk\read.py", line 20, in <module>
    from ...models.channel import Channel
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\conda\models\channel.py", line 6, in <module>
    from requests.packages.urllib3.util import Url
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\OpenSSL\crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "C:\ProgramFiles\Anaconda2\lib\site-packages\cryptography\hazmat\primitives\asymmetric\__init__.py", line 12, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: 'module' object has no attribute 'add_metaclass'

**Comment by kalefranz** [comment]
`conda update conda`, and if you can't, you might have to download a new miniconda installer and run it overtop your current install.
