### ISSUE TITLE
Tensor Flow Install Recipe Failure

### ISSUE THREAD

**Issue by superquant22** [conda/conda#4908]
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.11
       conda is private : False
      conda-env version : 4.2.11
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.10.0
       root environment : /home/mslade/anaconda2  (writable)
    default environment : /home/mslade/anaconda2
       envs directories : /home/mslade/anaconda2/envs
          package cache : /home/mslade/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/mslade/anaconda2/bin/conda create -n tensorflow python=2.7`

    Traceback (most recent call last):
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 308, in install
        update_deps=context.update_dependencies)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 526, in install_actions
        force=force, always_copy=always_copy)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 308, in ensure_linked_actions
        fetched_in = is_fetched(dist)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/install.py", line 727, in is_fetched
        for fn in package_cache().get(dist, {}).get('files', ()):
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/install.py", line 675, in package_cache
        add_cached_package(pdir, url)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/install.py", line 633, in add_cached_package
        schannel = Channel(url).canonical_name
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 161, in __call__
        c = Channel.from_value(value)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 211, in from_value
        return Channel.from_url(value)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 196, in from_url
        return parse_conda_channel_url(url)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 132, in parse_conda_channel_url
        configured_token) = _read_channel_configuration(scheme, host, port, path)
      File "/home/mslade/anaconda2/lib/python2.7/site-packages/conda/models/channel.py", line 122, in _read_channel_configuration
        return (Url(host=host, port=port).url.rstrip('/'), path.strip('/') or None,
    AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by nehaljwani** [comment]
Do you face the same issue with conda v4.3.14?

**Comment by xiabingbing** [comment]
The same issue exists with conda v4.3.14. I have the same question.

**Comment by nehaljwani** [comment]
Could you please share the backtrace of the error with v4.3.14? Also, have you configured any custom channels in any .condarc file(s)?
