### ISSUE TITLE
update failed !

### ISSUE THREAD

**Issue by himanshuxd** [conda/conda#4912]
Traceback (most recent call last):
  File "/home/ashdrogo/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 602, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
    cmd(state, arg)
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
    link(state['prefix'], dist, lt, index=state['index'])
  File "/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/install.py", line 1060, in link
    os.makedirs(dst_dir)
  File "/home/ashdrogo/anaconda2/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/ashdrogo/anaconda2/lib/python2.7/site-packages/conda/_vendor'

conda info gives ::

bash: /home/ashdrogo/anaconda2/bin/conda: /opt/anaconda1anaconda2anaconda3/bin/python: bad interpreter: No such file or directory

**Comment by kalefranz** [comment]
I'm guessing this is a case of an old version of conda "uninstalling itself." By the stack trace, I'm guessing this was something like conda 4.0.5.  Easiest fix is to download miniconda and install it overtop your current install.

    curl https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh ~/miniconda2.sh
    bash ~/miniconda2.sh -bfp /home/ashdrogo/anaconda2
