### ISSUE TITLE
Installing rstudio 1.0.44 on root, errors

### ISSUE THREAD

**Issue by goanpeca** [conda/conda#4914]
```
$ conda install rstudio=1.0.44 --json
ERROR conda.core.link:_execute_actions(335): An error occurred while installing package 'defaults::rstudio-1.0.44-0'.
FileExistsError(17, 'File exists')
Attempting to roll back.

Traceback (most recent call last):
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 324, in _execute_actions
    action.execute()
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 225, in execute
    force=context.force)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 214, in create_link
    mkdir_p(dst)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 153, in mkdir_p
    makedirs(path)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/Users/gpena-castellanos/anaconda/bin/pandoc'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 279, in execute
    pkg_data, actions)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 342, in _execute_actions
    reverse_excs,
conda.CondaMultiError: [Errno 17] File exists: '/Users/gpena-castellanos/anaconda/bin/pandoc'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
    exit_code = args.func(args, p)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 359, in install
    execute_actions(actions, index, verbose=not context.quiet)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/plan.py", line 800, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
    cmd(state, arg)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
    txn.execute()
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 295, in execute
    rollback_excs,
conda.CondaMultiError: [Errno 17] File exists: '/Users/gpena-castellanos/anaconda/bin/pandoc'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gpena-castellanos/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 586, in conda_exception_handler
    print_conda_exception(e)
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 496, in print_conda_exception
    stdoutlogger.info(json.dumps(exception.dump_map(), indent=2, sort_keys=True,
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/__init__.py", line 74, in dump_map
    errors=tuple(error.dump_map() for error in self.errors),
  File "/Users/gpena-castellanos/anaconda/lib/python3.6/site-packages/conda/__init__.py", line 74, in <genexpr>
    errors=tuple(error.dump_map() for error in self.errors),
AttributeError: 'FileExistsError' object has no attribute 'dump_map'
0316-gpena-castellanos:~ gpena-castellanos$

**Comment by mingwandroid** [comment]
@kalefranz any ideas about this?

The new rstudio splits pandoc into a separate package whole the old one had it bundled.

I thought the clobber stuff was turned off now?

**Comment by kalefranz** [comment]
It is. This is different than clobber.

What appears to be happening is that conda for some reason thinks it needs to create a 'bin/pandoc' *directory* after something in the transaction has already created a 'bin/pandoc' file.

This is definitely odd.

**Comment by mingwandroid** [comment]
That actually makes sense. The old rstudio had bin/pandoc/pandoc.exe, but the new pandoc package has bin/pandoc.

This should be allowed to happen though when clobbering is allowed.

**Comment by kalefranz** [comment]
Yeah I think we can do that.
