### ISSUE TITLE
conda install fails for regular user due to permission issues

### ISSUE THREAD

**Issue by aninguyen** [conda/conda#4918]
Hi, I can create a new environment as a regular user but cannot install packages.  I installed Miniconda as a super user and gave write permission to all users on the miniconda installation directory:
sudo chmod -R a+w /usr/local/bin/miniconda3

Here is the error message:

Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /usr/local/bin/miniconda3  (writable)
    default environment : /usr/local/bin/miniconda3
       envs directories : /usr/local/bin/miniconda3/envs
                          /home/pnguye01/.conda/envs
          package cache : /usr/local/bin/miniconda3/pkgs
                          /home/pnguye01/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Linux/3.10.0-327.36.1.el7.x86_64 Red Hat Enterprise Linux Server/7.2 glibc/2.17
                UID:GID : 179408:1086

`$ /usr/local/bin/miniconda3/bin/conda install --name test ipython`

    Traceback (most recent call last):
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 144, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.repodata.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 463, in <listcomp>
        for url, schan, pri in tasks]
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 445, in fetch_repodata
        touch(cache_path)
      File "/usr/local/bin/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 64, in touch
        utime(path, None)
    PermissionError: [Errno 13] Permission denied

**Comment by kalefranz** [comment]
Not sure where permissions got out of whack here.  Try

    sudo chown -R 179408:1086 /home/pnguye01/.conda/

**Comment by aninguyen** [comment]
Changing the permissions on the miniconda installation directory fixed it:
`sudo chmod -R 777 /usr/local/bin/miniconda3`
