### ISSUE TITLE
Unexepcted error installing line_profiler, memory_profiler and geopy

### ISSUE THREAD

**Issue by chriscopelandme** [conda/conda#4923]
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\chris>conda install -c conda-forge basemap
Fetching package metadata .............
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Users\chris\Anaconda3:
#
basemap                   1.0.8.dev0          np111py35_3    conda-forge

C:\Users\chris>conda install -c conda-forge line_profiler | pip install geopy memory_profiler
Requirement already satisfied: geopy in c:\program files (x86)\python35-32\lib\site-packages
Requirement already satisfied: memory_profiler in c:\program files (x86)\python35-32\lib\site-packages
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Users\chris\Anaconda3  (writable)
    default environment : C:\Users\chris\Anaconda3
       envs directories : C:\Users\chris\Anaconda3\envs
          package cache : C:\Users\chris\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/r/win-64
                          https://conda.anaconda.org/r/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\chris\.condarc
           offline mode : False



`$ C:\Users\chris\Anaconda3\Scripts\conda-script.py install -c conda-forge line_profiler`




    Traceback (most recent call last):
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\install.py", line 398, in install
        common.confirm_yn(args)
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\common.py", line 438, in confirm_yn
        default=default)
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\common.py", line 421, in confirm
        sys.stdout.flush()
    OSError: [Errno 22] Invalid argument

Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='cp1252'>
OSError: [Errno 22] Invalid argument

C:\Users\chris>
```

**Comment by akuardit** [comment]
from ur channel urls, you dont have conda-forge, try add first

conda config --add channels conda-forge
then
conda install -c conda-forge basemap

**Comment by kalefranz** [comment]
You're probably is that you're trying to pipe the output of `conda install` into the output of `pip install`, and then conda isn't getting it's required `y` when it asks for confirmation on the install plan.

    conda install -c conda-forge line_profiler | pip install geopy memory_profiler

This should instead be two separate commands

    conda install -c conda-forge line_profiler
    pip install geopy memory_profiler
