### ISSUE TITLE
Unexpected error after conda -install -c conda-forge basemap

### ISSUE THREAD

**Issue by chriscopelandme** [conda/conda#4932]
```
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\chris>conda -install -c conda-forge basemap
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\chris\Anaconda3  (writable)
    default environment : C:\Users\chris\Anaconda3
       envs directories : C:\Users\chris\Anaconda3\envs
                          C:\Users\chris\AppData\Local\conda\conda\envs
                          C:\Users\chris\.conda\envs
          package cache : C:\Users\chris\Anaconda3\pkgs
                          C:\Users\chris\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\chris\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393



`$ C:\Users\chris\Anaconda3\Scripts\conda-script.py -install -c conda-forge basemap`




    Traceback (most recent call last):
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 1762, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 1971, in _parse_known_args
        stop_index = consume_positionals(start_index)
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 1927, in consume_positionals
        take_action(action, args)
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 1820, in take_action
        argument_values = self._get_values(action, argument_strings)
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 2271, in _get_values
        self._check_value(action, value[0])
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 2314, in _check_value
        raise ArgumentError(action, msg % args)
    argparse.ArgumentError: argument command: invalid choice: 'conda-forge' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\main.py", line 119, in _main
        args = p.parse_args(args)
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 173, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 1730, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "C:\Users\chris\Anaconda3\lib\argparse.py", line 1769, in parse_known_args
        self.error(str(err))
      File "C:\Users\chris\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 146, in error
        raise CommandNotFoundError(cmd, message)
    TypeError: __init__() takes 2 positional arguments but 3 were given


C:\Users\chris>
```

**Comment by akuardit** [comment]
from ur channel urls, you dont have conda-forge, try add first

conda config --add channels conda-forge
then 
conda install -c conda-forge basemap

**Comment by nehaljwani** [comment]
@chriscopelandme You have to type

```
conda install -c conda-forge basemap
```

Instead of:

```
conda -install -c conda-forge basemap
```
'install' is a subcommand, not a flag/option.
