### ISSUE TITLE
An unexpected error has occurred during the install IAB (introduction of applied bioinformatics)

### ISSUE THREAD

**Issue by caijian89** [conda/conda#4940]
An error occurred when i run the following command :
`conda create -n iab-0.1.3 -c etetoolkit -c conda-forge python=3.5 ete3 scikit-bio=0.4.2`

Then the conda suggest me to post the information as below:

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/yunzhishu/miniconda2  (writable)
    default environment : /home/yunzhishu/miniconda2
       envs directories : /home/yunzhishu/miniconda2/envs
                          /home/yunzhishu/.conda/envs
          package cache : /home/yunzhishu/miniconda2/pkgs
                          /home/yunzhishu/.conda/pkgs
           channel URLs : https://conda.anaconda.org/etetoolkit/linux-64
                          https://conda.anaconda.org/etetoolkit/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-642.15.1.el6.x86_64 CentOS/6.8 glibc/2.12
                UID:GID : 500:500

`$ /home/yunzhishu/miniconda2/bin/conda create -n iab-0.1.3 -c etetoolkit -c conda-forge python=3.5 ete3 scikit-bio=0.4.2`

    Traceback (most recent call last):
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 111, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 470, in execute
        self._execute_action(action)
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 486, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/home/yunzhishu/miniconda2/lib/python2.7/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string

**Comment by goanpeca** [comment]
@caijian89 could you update to the latest conda version?

`conda update conda`

**Comment by caijian89** [comment]
Thanks a lot, it is resolved. @goanpeca

**Comment by goanpeca** [comment]
Glad to be of help :-)
