### ISSUE TITLE
UnicodeDecodeError when running `conda update`

### ISSUE THREAD

**Issue by hezhenghao** [conda/conda#4941]
I'm trying to update my Anaconda and the Python distributed with it. When running `conda update conda` the following message appears:
```
C:\Users\zhenghao>conda update conda
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install(args, parser, 'update')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 148, in install
    linked = install_linked(prefix)
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 961, in linked
    return set(linked_data(prefix).keys())
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 954, in linked_data
    load_linked_data(prefix, fn[:-5])
  File "C:\Anaconda3\lib\site-packages\conda\install.py", line 881, in load_linked_data
    rec = json.load(fi)
  File "C:\Anaconda3\lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xfb in position 30: illegal multibyte sequence
```
Here is the output for `conda info`:
```
C:\Users\zhenghao>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : not installed
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False
```
I tried manually changing line 880 in the file "C:\Anaconda3\lib\site-packages\conda\install.py" from
`with open(meta_file) as fi:`
to
`with open(meta_file, encoding='utf-8') as fi:`
and to
`with open(meta_file, 'rb') as fi:`
But neither attempts worked. How can I update my Anaconda? Thanks! This has been bugging me for several days!

**Comment by kalefranz** [comment]
Can this be reproduced in recent versions of conda 4.3? (4.3.17 is the latest)

I realize the bug being encountered is for `conda update conda`.  You may have to download a new miniconda installer, and then use it to update your current environment.

I ask if it can be reproduced in recent versions of conda, because I believe we've already fixed it.
