### ISSUE TITLE
conda --update matplotlib error

### ISSUE THREAD

**Issue by sugyandixit** [conda/conda#4947]
Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 2.1.5
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /Users/sugyandixit/anaconda3  (writable)
    default environment : /Users/sugyandixit/anaconda3
       envs directories : /Users/sugyandixit/anaconda3/envs
                          /Users/sugyandixit/.conda/envs
          package cache : /Users/sugyandixit/anaconda3/pkgs
                          /Users/sugyandixit/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/3.5.2 Darwin/16.4.0 OSX/10.12.3
                UID:GID : 501:20

`$ /Users/sugyandixit/anaconda3/bin/conda --update matplotlib`

    Traceback (most recent call last):
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 1758, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 1967, in _parse_known_args
        stop_index = consume_positionals(start_index)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 1923, in consume_positionals
        take_action(action, args)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 1816, in take_action
        argument_values = self._get_values(action, argument_strings)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 2267, in _get_values
        self._check_value(action, value[0])
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 2310, in _check_value
        raise ArgumentError(action, msg % args)
    argparse.ArgumentError: argument command: invalid choice: 'matplotlib' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/sugyandixit/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 119, in _main
        args = p.parse_args(args)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 173, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 1726, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/Users/sugyandixit/anaconda3/lib/python3.5/argparse.py", line 1765, in parse_known_args
        self.error(str(err))
      File "/Users/sugyandixit/anaconda3/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 146, in error
        raise CommandNotFoundError(cmd, message)
    TypeError: __init__() takes 2 positional arguments but 3 were given

**Comment by goanpeca** [comment]
@sugyandixit you are supposed to use conda update as

`conda update matplotlib`

**Comment by goanpeca** [comment]
Duplicate of https://github.com/conda/conda/issues/4944
