### ISSUE TITLE
error updating spyder

### ISSUE THREAD

**Issue by tolyla25** [conda/conda#4952]
Got this error updating SPYDER in the Launcher. Help!

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\cli\main.py", line 208, in args_func
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\cli\common.py", line 612, in inner
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in execute
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\cli\install.py", line 413, in install
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\plan.py", line 527, in execute_actions
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\instructions.py", line 148, in execute_instructions
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\instructions.py", line 91, in LINK_CMD
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\instructions.py", line 87, in link
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\install.py", line 578, in link
  File "C:\Users\Toly\Anaconda\lib\site-packages\conda\install.py", line 200, in yield_lines
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Toly\\Anaconda\\pkgs\\pywin32-220-py27_2\\info\\files'

**Comment by goanpeca** [comment]
@tolyla25 launcher is deprecated for over a year now.

If you want to use a graphical installer you can use [Anaconda Navigator](https://docs.continuum.io/anaconda/navigator)

It seems you have a very old install of Anaconda. I would advice to download and reinstall the latest anaconda (for current user only) https://www.continuum.io/downloads

**Comment by tolyla25** [comment]
Thank you! I used Anaconda 4.0.0 and 4.3.1 None of them worked correctly with Win 10. 4.3.1 would not even launch after I would get to the command panel (clicking on Notebook button (Launch) did not produce any results). With 4.0.0. it launched but generated a system error. 4.3.1 was the latest for 64 bit Win systems. Be very grateful for any suggestions!

**Comment by tolyla25** [comment]
I also used Navigator (4.3.1) but id did not start with Win 10

**Comment by goanpeca** [comment]
@tolyla25 if you run from the command line with `anaconda-navigator` what is the trace output?

**Comment by goanpeca** [comment]
@tolyla25 also this is the wrong repository for this. Please use https://github.com/ContinuumIO/anaconda-issues/issues
