### ISSUE TITLE
conda doesnt work

### ISSUE THREAD

**Issue by yl2612** [conda/conda#4958]
I am not able to create an enviornment or install a package using conda on aws. Below is the error message.

```Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /home/ec2-user/src/anaconda3  (writable)
    default environment : /home/ec2-user/src/anaconda3
       envs directories : /home/ec2-user/src/anaconda3/envs
                          /home/ec2-user/.conda/envs
          package cache : /home/ec2-user/src/anaconda3/pkgs
                          /home/ec2-user/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/3.5.2 Linux/4.4.30-32.54.amzn1.x86_64 / glibc/2.17
                UID:GID : 500:500

`$ /home/ec2-user/src/anaconda3/bin/conda install geopandas`

    Traceback (most recent call last):
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 70, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 459, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 459, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 105, in func
        res = f(*args, **kwargs)
      File "/home/ec2-user/src/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 445, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/ec2-user/src/anaconda3/pkgs/cache/6bfb14bd.json'
```

**Comment by waltonseymour** [comment]
Pretty clearly a `PermissionError `. Try running with sudo

**Comment by avishapiro** [comment]
@waltonseymour -- Can you give an explicit syntax example using sudo? I haven't had success:

    [ec2-user@ip-xxxxxx ~]$ sudo conda create --name testenv python=3.6
    sudo: conda: command not found

This is likely an AWS problem rather than conda but it is strange. For example, I _am_ able to create a clone of an environment, eg `conda create --name testenv --clone root` does work without the PermissionError. BTW, I'm using an AWS Deep Learning AMI [https://aws.amazon.com/amazon-ai/amis/](https://aws.amazon.com/amazon-ai/amis/).

**Comment by kalefranz** [comment]
> Try running with sudo

No! Don't run sudo to fix errors like this! You're only going to cause more pain down the road.

The right thing to do would have been

    sudo chown -R 500:500 /home/ec2-user/src/anaconda3

and then of course

    conda update conda

**Comment by avishapiro** [comment]
Thanks @kalefranz! Using sudo with conda seemed very wrong. Your suggestion worked! 

(I did a variation of what you suggested and tried chown on the file in the error message but that didn't work.)
