### ISSUE TITLE
Cannot install Pandas datareader using Conda - pls help

### ISSUE THREAD

**Issue by arunkumarwa** [conda/conda#4965]
Hello

I am trying to install the pandas datareader from conda. Running into issues.  The error  suggested I post a message here.  Thanks for your help!

conda install -c anaconda pandas-datareader=0.2.1

error message
-----------------------------
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

https://github.com/conda/conda/issues
Current conda install:

           platform : win-64
      conda version : 4.3.14
   conda is private : False
  conda-env version : 4.3.14
conda-build version : not installed
     python version : 3.6.0.final.0
   requests version : 2.12.4
   root environment : C:\ProgramData\Anaconda3  (read only)
default environment : C:\ProgramData\Anaconda3
   envs directories : C:\ProgramData\Anaconda3\envs
                      C:\Users\akumar3\AppData\Local\conda\conda\envs
                      C:\Users\akumar3\.conda\envs
      package cache : C:\ProgramData\Anaconda3\pkgs
                      C:\Users\akumar3\AppData\Local\conda\conda\pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/win-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/win-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/win-64
                      https://repo.continuum.io/pkgs/pro/noarch
                      https://repo.continuum.io/pkgs/msys2/win-64
                      https://repo.continuum.io/pkgs/msys2/noarch
        config file : None
       offline mode : False
         user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393
$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create -n my_root --clone=C:\ProgramData\Anaconda

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
    exit_code = args.func(args, p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 212, in install
    clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 57, in clone
    raise DirectoryNotFoundError(src_arg, 'no such directory: %s' % src_arg, json)
TypeError: __init__() takes 2 positional arguments but 4 were given

**Comment by arunkumarwa** [comment]
Have it working now.
