### ISSUE TITLE
CondaError.__str__ is buggy?

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#4968]
(root) [root@833f44c1b4d6 ~]# conda install /tmp/Alex%20F/mayavi-4.3.0-np17py27_0.tar.bz2

Current conda install:

               platform : linux-64
          conda version : 4.3.15
       conda is private : False
      conda-env version : 4.3.15
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /conda  (writable)
    default environment : /conda
       envs directories : /conda/envs
                          /root/.conda/envs
          package cache : /conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.15 requests/2.12.4 CPython/3.6.0 Linux/4.8.6-300.fc25.x86_64 CentOS/6.8 glibc/2.12
                UID:GID : 0:0

`$ /conda/bin/conda install /tmp/Alex%20F/mayavi-4.3.0-np17py27_0.tar.bz2`

    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 502, in _execute_action
        action.execute()
      File "/conda/lib/python3.6/site-packages/conda/core/path_actions.py", line 739, in execute
        source_md5sum = compute_md5sum(source_path)
      File "/conda/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 59, in compute_md5sum
        raise CondaFileNotFoundError(file_full_path)
    conda.exceptions.CondaFileNotFoundError: <unprintable CondaFileNotFoundError object>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/exceptions.py", line 592, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/conda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/conda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/conda/lib/python3.6/site-packages/conda/cli/install.py", line 200, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "/conda/lib/python3.6/site-packages/conda/misc.py", line 90, in explicit
        pfe.execute()
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 491, in execute
        self._execute_action(action)
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 507, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/conda/lib/python3.6/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/conda/lib/python3.6/site-packages/conda/__init__.py", line 48, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: must be real number, not dict

I know, I should have typed `conda install "/tmp/Alex F/mayavi-4.3.0-np17py27_0.tar.bz2"` instead, but I'd expect the exception to not raise another exception!

**Comment by nehaljwani** [comment]
Basically, pass any format specifier in any exception's message, and `text_type()` cries. 

    (root) [root@833f44c1b4d6 ~]# conda install /tmp/Alex%s%s/mayavi-4.3.0-np17py27_0.tar.bz2                                                                                                                          

Current conda install:

               platform : linux-64
          conda version : 4.3.15
       conda is private : False
      conda-env version : 4.3.15
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /conda  (writable)
    default environment : /conda
       envs directories : /conda/envs
                          /root/.conda/envs
          package cache : /conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.15 requests/2.12.4 CPython/3.6.0 Linux/4.8.6-300.fc25.x86_64 CentOS/6.8 glibc/2.12
                UID:GID : 0:0



`$ /conda/bin/conda install /tmp/Alex%s%s/mayavi-4.3.0-np17py27_0.tar.bz2`




    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 502, in _execute_action
        action.execute()
      File "/conda/lib/python3.6/site-packages/conda/core/path_actions.py", line 739, in execute
        source_md5sum = compute_md5sum(source_path)
      File "/conda/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 59, in compute_md5sum
        raise CondaFileNotFoundError(file_full_path)
    conda.exceptions.CondaFileNotFoundError: <unprintable CondaFileNotFoundError object>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/conda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/conda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/conda/lib/python3.6/site-packages/conda/cli/install.py", line 200, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "/conda/lib/python3.6/site-packages/conda/misc.py", line 90, in explicit
        pfe.execute()
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 491, in execute
        self._execute_action(action)
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 507, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/conda/lib/python3.6/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/conda/lib/python3.6/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string

**Comment by kalefranz** [comment]
Hi Nehal,

The issue isn't text_type, but instead the way CondaError works. For parameterized arguments with the message of an error, they must be named (i.e. "%(parameter_name)s" rather than "%s") and the parameter with that name must be passed as a keyword argument to the exception class when it's instantiated.

**Comment by kalefranz** [comment]
@nehaljwani Can you confirm this is fixed (or at least different) in 4.3.17?  I remember having a url escaping issue at one point.  I was using `unquote_plus` somewhere that I should have really just been using `unquote`.

**Comment by nehaljwani** [comment]
Yes, now `conda install /tmp/Alex%20F/mayavi-4.3.0-np17py27_0.tar.bz2` works, probably because of 9617f25ef4c903036b9d62d4298ec9210abe8536 , but the reason I opened this issue is that conda throws a stack trace for wrong inputs like: `conda install /tmp/Alex%s%s/mayavi-4.3.0-np17py27_0.tar.bz2` . I know that this is being nitpicky and would rarely arise and you can consider this to be low priority, but an exception stating 'Invalid Path' or 'File Not Found' would have been better.

**Comment by kalefranz** [comment]
You mean like this?

```
kfranz@0283:~/continuum/conda *4.3.x ❯ python -m conda install /tmp/Alex%20F/mayavi-4.3.0-np17py27_0.tar.bz2

CondaError: CondaFileNotFoundError: '/tmp/Alex F/mayavi-4.3.0-np17py27_0.tar.bz2'.
CondaError: CondaFileNotFoundError: '/tmp/Alex F/mayavi-4.3.0-np17py27_0.tar.bz2'.
CondaError: CondaFileNotFoundError: '/tmp/Alex F/mayavi-4.3.0-np17py27_0.tar.bz2'.

```

That's in 4.3.x right now.  I changed the name of the exception to just FileNotFoundError in 4.4.x.  And I also tracked down why it's being repeated three times.  There's some logic to clean up around executing all the download/extract actions.

**Comment by nehaljwani** [comment]
No, I am fine with that exception. I am talking about the scenario when the input pat itself is wrong. Example:

```bash
(root) [root@5eb02abb88b7 ~]# conda install /tmp/Alex%s%s/isort-4.2.5-py27_0.tar.bz2
An unexpected error has occurred.
    Current conda install:

                   platform : linux-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : not installed
             python version : 3.6.0.final.0
           requests version : 2.12.4
           root environment : /conda  (writable)
        default environment : /conda
           envs directories : /conda/envs
                          /root/.conda/envs
              package cache : /conda/pkgs
                          /root/.conda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                config file : /root/.condarc
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.12.4 CPython/3.6.0 Linux/4.8.6-300.fc25.x86_64 CentOS/6.8 glibc/2.12    
                    UID:GID : 0:0  

`$ /conda/bin/conda install /tmp/Alex%s%s/isort-4.2.5-py27_0.tar.bz2`

    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 502, in _execute_action
        action.execute()
      File "/conda/lib/python3.6/site-packages/conda/core/path_actions.py", line 760, in execute
        source_md5sum = compute_md5sum(source_path)
      File "/conda/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 59, in compute_md5sum
        raise CondaFileNotFoundError(file_full_path)
    conda.exceptions.CondaFileNotFoundError: <unprintable CondaFileNotFoundError object>
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/conda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/conda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/conda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/conda/lib/python3.6/site-packages/conda/cli/install.py", line 199, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/conda/lib/python3.6/site-packages/conda/misc.py", line 90, in explicit
        pfe.execute()
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 491, in execute
        self._execute_action(action)
      File "/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 507, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/conda/lib/python3.6/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/conda/lib/python3.6/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string
```

**Comment by kalefranz** [comment]
Oh I see.  Going to have to think about that one.  There's an easy solution.  But we should probably have a more general solution.
