### ISSUE TITLE
conda update conda

### ISSUE THREAD

**Issue by JimStarrett** [conda/conda#4975]
Fetching package metadata ......Could not connect to https://conda.binstar.org.faircloth-lab/osx-64/
Could not connect to https://conda.binstar.org.faircloth-lab/noarch/
.........Could not connect to http://corp.com:8080/osx-64/
Could not connect to https://corp.com:8080/noarch/
Could not connect to http://corp.com:8080/noarch/
Could not connect to https://corp.com:8080/osx-64/
Could not connect to https://corp.com:8080/osx-64/
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/Aliatypus/anaconda2  (writable)
    default environment : /Users/Aliatypus/anaconda2
       envs directories : /Users/Aliatypus/anaconda2/envs
          package cache : /Users/Aliatypus/anaconda2/pkgs
           channel URLs : https://corp.com:8080/osx-64/
                          https://corp.com:8080/noarch/
                          http://corp.com:8080/osx-64/
                          http://corp.com:8080/noarch/
                          https://conda.binstar.org/faircloth-lab/osx-64/
                          https://conda.binstar.org/faircloth-lab/noarch/
                          https://conda.anaconda.org/r/osx-64/
                          https://conda.anaconda.org/r/noarch/
                          https://anaconda.org/faircloth-lab/repo/osx-64/
                          https://anaconda.org/faircloth-lab/repo/noarch/
                          https://anaconda.org/faircloth-lab/repo=cond/osx-64/
                          https://anaconda.org/faircloth-lab/repo=cond/noarch/
                          http://conda.binstar.org/faircloth-lab/osx-64/
                          http://conda.binstar.org/faircloth-lab/noarch/
                          https://conda.binstar.org.faircloth-lab/osx-64/
                          https://conda.binstar.org.faircloth-lab/noarch/
                          https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /Users/Aliatypus/.condarc
           offline mode : False

`$ /Users/Aliatypus/anaconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='corp.com', port=8080): Max retries exceeded with url: /osx-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x104532090>, 'Connection to corp.com timed out. (connect timeout=3.05)')): https://corp.com:8080/osx-64/

**Comment by goanpeca** [comment]
@JimStarrett you should remove the following channel entrie are using binstar or probably have a typo (. instead of /)

```
- https://conda.binstar.org/faircloth-lab/osx-64/
- https://conda.binstar.org/faircloth-lab/noarch/
- http://conda.binstar.org/faircloth-lab/osx-64/
- http://conda.binstar.org/faircloth-lab/noarch/
- https://conda.binstar.org.faircloth-lab/osx-64/
- https://conda.binstar.org.faircloth-lab/noarch/
```

You should remove them from your `/Users/Aliatypus/.condarc` file, they values might be 

```
- https://conda.binstar.org/faircloth-lab/
- https://conda.binstar.org.faircloth-lab/
```

If you are unsure please paste the content of `/Users/Aliatypus/.condarc`

Cheers

**Comment by goanpeca** [comment]
@kalefranz another instance where validation on config would have helped :-p

**Comment by JimStarrett** [comment]
Sorry, I do not know how validation on the config works.

**Comment by JimStarrett** [comment]
Jamess-MBP:~ Aliatypus$ conda update conda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /Users/Aliatypus/anaconda2  (writable)
    default environment : /Users/Aliatypus/anaconda2
       envs directories : /Users/Aliatypus/anaconda2/envs
          package cache : /Users/Aliatypus/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/r/osx-64/
                          https://repo.continuum.io/pkgs/r/noarch/
            config file : /Users/Aliatypus/.condarc
           offline mode : False



`$ /Users/Aliatypus/anaconda2/bin/conda update conda`




    Traceback (most recent call last):
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 287, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 112, in fetch_repodata
        timeout=(3.05, 60))
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "/Users/Aliatypus/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 306, in ssl_wrap_socket
        context.load_cert_chain(certfile, keyfile)
    IOError: [Errno 2] No such file or directory

**Comment by JimStarrett** [comment]
Thank you for your response. I removed the conda.binstar urls you mentioned above, but there still seems to be an issue. For some reason /osx-64/ and /noarch/ are added to the url when it tries to connect. Here is the .condarc commands:

add_anaconda_token: True
add_pip_as_python_dependency: True
allow_softlinks: True
always_copy: False
always_yes: False
auto_update_conda: True
binstar_upload: None
changeps1: True
channel_alias: https://conda.anaconda.org/
channel_priority: True
channels:
  - defaults
client_cert: 
client_cert_key: 
create_default_packages: []
debug: False
default_channels:
  - https://repo.continuum.io/pkgs/free
  - https://repo.continuum.io/pkgs/pro
  - https://repo.continuum.io/pkgs/r
disallow: []
json: False
offline: False
proxy_servers: {}
quiet: False
shortcuts: True
show_channel_urls: None
ssl_verify: True
track_features: []
update_dependencies: True
use_pip: True
verbosity: 0

**Comment by kalefranz** [comment]
You probably either have environment variables or a `.netrc` file that's modifying requests' behavior.  Try removing your condarc file entirely, doing your `conda update conda`, and then putting it back.

**Comment by kalefranz** [comment]
If you still have problems, give us the output of `env | sort`.
