### ISSUE TITLE
Execption raised installing numpy 1.12.1

### ISSUE THREAD

**Issue by fergalm** [conda/conda#4979]
**Edit:** I now believe the problem is not with gdal, but with numpy. See the next comment.

conda install raised an exception while trying to install gdal version 2.1.3 from conda-forge.

I do the following:
```bash
conda create --name expt4
source activate expt4
env | grep CONDA
conda install -c conda-forge gdal=2.1.3
```

and I get
``` bash
Fetching package metadata ...........
Solving package specifications: .

   Package plan for installation in environment /home/fergal/apps/anaconda/envs/expt4:

 The following NEW packages will be INSTALLED:

    ca-certificates: 2017.1.23-0       conda-forge
    certifi:         2017.1.23-py27_0  conda-forge
    curl:            7.52.1-0          conda-forge
    expat:           2.1.0-2           conda-forge
    freexl:          1.0.2-1           conda-forge
    gdal:            2.1.3-np112py27_2 conda-forge
    geos:            3.5.1-1           conda-forge
    giflib:          5.1.4-0           conda-forge
    hdf4:            4.2.12-0          conda-forge
    hdf5:            1.8.17-10         conda-forge
    icu:             58.1-1            conda-forge
    jpeg:            9b-0              conda-forge
    json-c:          0.12-0            conda-forge
    kealib:          1.4.6-3           conda-forge
    libdap4:         3.18.3-2          conda-forge
    libgfortran:     3.0.0-1                      
    libiconv:        1.14-4            conda-forge
    libnetcdf:       4.4.1.1-2         conda-forge
    libpng:          1.6.28-0          conda-forge
    libpq:           9.5.4-3           conda-forge
    libspatialite:   4.3.0a-14         conda-forge
    libtiff:         4.0.6-7           conda-forge
    libxml2:         2.9.4-4           conda-forge
    mkl:             2017.0.1-0                   
    ncurses:         5.9-10            conda-forge
    numpy:           1.12.1-py27_0                
    openjpeg:        2.1.2-2           conda-forge
    openssl:         1.0.2h-3          conda-forge
    pcre:            8.39-0            conda-forge
    pip:             9.0.1-py27_0      conda-forge
    proj4:           4.9.3-3           conda-forge
    python:          2.7.13-0          conda-forge
    readline:        6.2-0             conda-forge
    setuptools:      33.1.1-py27_0     conda-forge
    sqlite:          3.13.0-1          conda-forge
    tk:              8.5.19-1          conda-forge
    util-linux:      2.21-0                       
    wheel:           0.29.0-py27_0     conda-forge
    xerces-c:        3.1.4-3           conda-forge
    xz:              5.2.2-0           conda-forge
    zlib:            1.2.11-0          conda-forge

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /home/fergal/apps/anaconda  (writable)
    default environment : /home/fergal/apps/anaconda/envs/expt4
       envs directories : /home/fergal/apps/anaconda/envs
                          /home/fergal/.conda/envs
          package cache : /home/fergal/apps/anaconda/pkgs
                          /home/fergal/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.12 Linux/4.4.0-71-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000



`$ /home/fergal/apps/anaconda/envs/expt4/bin/conda install -c conda-forge gdal=2.1.3`




    Traceback (most recent call last):
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 85, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/home/fergal/apps/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 105, in read_index_json
        record = IndexRecord(**json.load(fi))  # TODO: change to LinkedPackageData
      File "/home/fergal/apps/anaconda/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/home/fergal/apps/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/home/fergal/apps/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/fergal/apps/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded
```

I updated to conda 4.3.15 and got the same error message.

**Comment by fergalm** [comment]
With a bit of digging, it seems like the problem is with dependency on numpy 1.12.1

```conda create --name expt8 numpy=1.12.0```

works, but 
```conda create --name expt numpy=1.12.1```

 causes an error

**Comment by tyler-thetyrant** [comment]
@fergalm Neither of the commands seem to cause any errors with Conda 4.3.16.

**Comment by tyler-thetyrant** [comment]
Also
```
conda create --name expt4
source activate expt4
env | grep CONDA
conda install -c conda-forge gdal=2.1.3
```
did not raise any error in 4.3.16
