### ISSUE TITLE
Issue with scipy and libgcc

### ISSUE THREAD

**Issue by lapolonio** [conda/conda#4981]
I installed conda and created an environment using the following directions:
https://github.com/udacity/CarND-Term1-Starter-Kit/blob/master/doc/configure_via_anaconda.md

In python when I try:
`from sklearn.svm import LinearSVC` 

I get the following error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/base.py", line 12, in <module>
    from .utils.fixes import signature
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/sklearn/utils/fixes.py", line 290, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/__init__.py", line 113, in <module>
    from .isolve import *
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/__init__.py", line 6, in <module>
    from .iterative import *
  File "/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/iterative.py", line 7, in <module>
    from . import _iterative
ImportError: dlopen(/Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-35m-darwin.so, 2): Library not loaded: /Users/ray/mc-x64-3.5/conda-bld/gcc-4.8_1477649012852/_b_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/libgcc_s.1.dylib
  Referenced from: /Users/lapolonio/miniconda3/envs/carnd-term1/lib/python3.5/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-35m-darwin.so
  Reason: image not found

I am confused about where it is looking for libgcc_s.1.dylib
/Users/ray etc ?

**Comment by zenhao** [comment]
I got similar issue, can anyone take a look? Thanks

**Comment by abursuc** [comment]
Try doing a ```conda install scipy``` in order to replace it with the default channel scipy.

**Comment by kalefranz** [comment]
I'm sorry, but this is not something changing conda code can fix, and therefore this is the wrong issue tracker.  If it's a problem with scipy, consider filing an issue within their repo, or if it's a problem with how scipy is packaged file an issue at github.com/ContinuumIO/anaconda-issues if you got the package from repo.continuum.io, or with conda-forge if that's where you got the package.
