### ISSUE TITLE
conda update pytest failed

### ISSUE THREAD

**Issue by good-epic** [conda/conda#4988]
$ conda list
...
pytest                    2.6.3                    py27_0  
...

$ conda update pytest
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/usr/local/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/usr/local/anaconda/lib/python2.7/site-packages/conda/gateways/download.py", line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/usr/local/anaconda/lib/python2.7/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/anaconda/lib/python2.7/site-packages/OpenSSL/rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "/usr/local/anaconda/lib/python2.7/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/usr/local/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 173, in <module>
    Binding.init_static_locks()
  File "/usr/local/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/usr/local/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/usr/local/anaconda/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 94, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
NotImplementedError: in lib_build_attr: op=41

**Comment by kalefranz** [comment]
@goanpeca FYI, if `conda info` isn't there, first thing is to ask for it.

This is being caused by some type of version mismatch between requests and cryptography (maybe pyopenssl) I think.  We had a whole spate of these version mismatches go through around November through January.  Pretty sucky, because in many situations conda is just flat out hosed by the requests dependency being inoperable.

One way to get out of this, if it works is,

    CONDA_SSL_VERIFY=false conda update conda

If it doesn't, download the latest miniconda installer, then install it overtop your current installation.

    curl -sS https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -o ~/miniconda2.sh
    bash ~/miniconda2.sh -bfp /usr/local/anaconda

Assuming you're on linux, but don't have `conda info`, so can't be sure.  Download link might be wrong.

**Comment by goanpeca** [comment]
>@goanpeca FYI, if conda info isn't there, first thing is to ask for it.

Bot is coming...!
