### ISSUE TITLE
unable to execute conda create command

### ISSUE THREAD

**Issue by shivanand3939** [conda/conda#4996]
I am facing the following issue

I want to create a new env:

conda create -n tensorflow python=3.5

but I am getting the following error

tching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the conda GitHub issue tracker at:

https://github.com/conda/conda/issues

Current conda install:

           platform : linux-64
      conda version : 4.3.11
   conda is private : False
  conda-env version : 4.3.11
conda-build version : not installed
     python version : 2.7.13.final.0
   requests version : 2.12.4
   root environment : /home/shiv/miniconda2  (read only)
default environment : /home/shiv/miniconda2
   envs directories : /home/shiv/miniconda2/envs
                      /home/shiv/.conda/envs
      package cache : /home/shiv/miniconda2/pkgs
                      /home/shiv/.conda/pkgs
       channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                      https://repo.continuum.io/pkgs/free/noarch
                      https://repo.continuum.io/pkgs/r/linux-64
                      https://repo.continuum.io/pkgs/r/noarch
                      https://repo.continuum.io/pkgs/pro/linux-64
                      https://repo.continuum.io/pkgs/pro/noarch
        config file : None
       offline mode : False
         user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/4.9.0-040900-generic debian/stretch/sid glibc/2.23
            UID:GID : 1000:1000

$ /home/shiv/miniconda2/bin/conda create -n tensorflow python=3.5

Traceback (most recent call last):
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
    exit_code = args.func(args, p)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
    install(args, parser, 'create')
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
    unknown=index_args['unknown'], prefix=prefix)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 125, in get_index
    index = fetch_index(channel_priority_map, use_cache=use_cache)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 552, in fetch_index
    repodatas = _collect_repodatas(use_cache, tasks)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 541, in _collect_repodatas
    repodatas = _collect_repodatas_serial(use_cache, tasks)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
    for url, schan, pri in tasks]
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 144, in func
    res = f(*args, **kwargs)
  File "/home/shiv/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 500, in fetch_repodata
    with open(cache_path, 'w') as fo:
IOError: [Errno 13] Permission denied: u'/home/shiv/miniconda2/pkgs/cache/db552c1e.json'

I have tried changing the permissions for the file, 

chmod u+v /home/shiv/miniconda2/pkgs/cache/db552c1e.json

But still the error persists

**Comment by goanpeca** [comment]
@shivanand3939 could you please update to the latest version of conda and check again?

**Comment by shivanand3939** [comment]
Thank you! It worked
