### ISSUE TITLE
error when trying to create virtual environment 

### ISSUE THREAD

**Issue by meli-lewis** [conda/conda#501]
**Error**

``` shell
Traceback (most recent call last):
  File "/Users/m/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    args.func(args, p)
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 149, in execute
    actions = plan.install_actions(prefix, index, specs)
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/plan.py", line 233, in install_actions
    for fn in r.solve(specs, [d + '.tar.bz2' for d in linked]):
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 425, in solve
    return self.explicit(specs) or self.solve2(specs, features)
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 282, in solve2
    solutions = min_sat(clauses)
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 146, in min_sat
    for sol in islice(pycosat.itersolve(clauses), max_n):
  File "/Users/m/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 238, in gen_clauses
    assert len(clause) > 1, fn1
AssertionError: numba-0.7.0-np17py26_1.tar.bz2
```

**conda info**

``` bash
             platform : osx-64
        conda version : 2.0.4
     root environment : /Users/m/anaconda  (writable)
  default environment : /Users/m/anaconda
     envs directories : /Users/m/anaconda/envs
        package cache : /Users/m/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
```

**Comment by kalefranz** [comment]
Issue is for conda version 2.0.4.  Outdated. Closing.
