### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by Cel1ne** [conda/conda#5020]
Hello,

`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/<user>/miniconda2  (writable)
    default environment : /home/<user>/miniconda2/envs/zerospeech
       envs directories : /home/<user>/miniconda2/envs
                          /home/<user>/.conda/envs
          package cache : /home/<user>/miniconda2/pkgs
                          /home/<user>/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/3.13.0-48-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000060:1000001

`$ /home/<user>/miniconda2/envs/zerospeech/bin/conda install --yes --file requirements_conda.txt`

    Traceback (most recent call last):
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 85, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/home/<user>/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 104, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'/home/<user>/miniconda2/pkgs/matplotlib-2.0.0-np111py27_0/info/index.json'

Error: cannot install from requirements_conda.txt
`

Céline

**Comment by kalefranz** [comment]
This is solved by `conda clean --packages` and then `conda update conda`.
