### ISSUE TITLE
Conda error in multiuser installation

### ISSUE THREAD

**Issue by shubhvachher** [conda/conda#5024]
Steps followed as per @ijstokes message [here](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/qinxkmvlnSg)

The user for below is `anaconda` as per instructions above.

#1329 #4604 
```
Fetching package metadata ....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/anaconda2  (writable)
    default environment : /opt/anaconda2
       envs directories : /opt/anaconda2/envs
                          /home/anaconda/.conda/envs
          package cache : /opt/anaconda2/pkgs
                          /home/anaconda/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.12.4 CPython/2.7.13 Linux/4.8.0-45-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000



`$ /opt/anaconda2/bin/conda install keras`




    Traceback (most recent call last):
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 445, in fetch_repodata
        touch(cache_path)
      File "/opt/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/update.py", line 64, in touch
        utime(path, None)
    OSError: [Errno 13] Permission denied: '/opt/anaconda2/pkgs/cache/9ca791dd.json'
```

Seems like `/opt/anaconda2/pkgs/cache/9ca791dd.json` is being generated on the fly? Its permissions are 
```
-rw-rw-r-- 1 root     root         9245 Apr  7 23:46 9ca791dd.json
-rw-rw-r-- 1 root     root        14838 Apr  7 23:43 9ca791dd.q
```
under the cache folder whose permissions are 
```
drwxrwxr-x  2 anaconda anaconda     4096 Apr  8 01:25 cache
```

**Comment by shubhvachher** [comment]
#4743 #4581 :/

**Comment by kalefranz** [comment]
You'll need to fix the permissions on your Anaconda directory. 

    sudo chosen -R 1000:1000 /opt/anaconda2

**Comment by shubhvachher** [comment]
Thanks for the quick fix @kalefranz !

As you could see I had run `sudo chown -R 1000:1000 /opt/anaconda2` earlier and so cache folder and every other folder had 
```
drwxrwxr-x  2 anaconda anaconda     4096 Apr  8 01:25 cache
```
like suggested. So, the file `9ca791dd.json` was made after that.
Will this error not resurface? Or are new files in the cache folder not going to be made?

**Comment by shubhvachher** [comment]
Check this out, 

```
~$ pip install celery
Collecting celery
  Using cached celery-4.0.2-py2.py3-none-any.whl
Collecting billiard<3.6.0,>=3.5.0.2 (from celery)
  Using cached billiard-3.5.0.2.tar.gz
Requirement already satisfied: pytz>dev in /opt/anaconda2/lib/python2.7/site-packages (from celery)
Collecting kombu<5.0,>=4.0.2 (from celery)
  Downloading kombu-4.0.2-py2.py3-none-any.whl (178kB)
    100% |████████████████████████████████| 184kB 3.2MB/s 
Collecting amqp<3.0,>=2.1.4 (from kombu<5.0,>=4.0.2->celery)
  Downloading amqp-2.1.4-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 5.8MB/s 
Collecting vine>=1.1.3 (from amqp<3.0,>=2.1.4->kombu<5.0,>=4.0.2->celery)
  Downloading vine-1.1.3-py2.py3-none-any.whl
Building wheels for collected packages: billiard
  Running setup.py bdist_wheel for billiard ... done
  Stored in directory: /home/shubh/.cache/pip/wheels/d3/c3/0e/89624b11fe03d99ba5e3a035d977e871879aa42b89e862a118
Successfully built billiard
Installing collected packages: billiard, vine, amqp, kombu, celery
  Found existing installation: billiard 3.5.0.1
    Uninstalling billiard-3.5.0.1:
      Successfully uninstalled billiard-3.5.0.1
  Rolling back uninstall of billiard
Exception:
Traceback (most recent call last):
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/opt/anaconda2/lib/python2.7/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/opt/anaconda2/lib/python2.7/shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: '/opt/anaconda2/lib/python2.7/site-packages/_billiard.so'
```
