### ISSUE TITLE
unexpected error "InsecureRequestWarning" when calling conda command

### ISSUE THREAD

**Issue by YanTianqi** [conda/conda#5026]
I am using OSX Yosemite, python version
```
>>> import sys
>>> sys.version
'2.7.12 |Anaconda 4.2.0 (x86_64)| (default, Jul  2 2016, 17:43:17) \n[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)]'
```

I was following the instructions of this post to create a virtual environment with conda, as the virtualenv does not seem to be working with python under anaconda: https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/

While I call the command conda -V, I received the following error:
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues




Traceback (most recent call last):
  File "/Users/YTQ/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main)
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 491, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 437, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 407, in get_info
    args.func(args, p)
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 155, in execute
    from conda.api import get_index
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/api.py", line 7, in <module>
    from .fetch import fetch_index
  File "/Users/YTQ/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 20, in <module>
    from requests.packages.urllib3.connectionpool import InsecureRequestWarning
ImportError: cannot import name InsecureRequestWarning
```

The same error message also appears when I called other conda commands such as conda update conda. May I know how to fix this?

**Comment by kalefranz** [comment]
As reported, this will be fixed with https://github.com/conda/conda/pull/5090.
