### ISSUE TITLE
unexpected issue

### ISSUE THREAD

**Issue by arasalt** [conda/conda#5028]
Uncaught Exception:
Error: Conda command "info" failed:
command: conda info,--json
output: An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

`$ /Users/tasalta/anaconda/bin/conda info --json`

    Traceback (most recent call last):
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 98, in _main
        imported = importlib.import_module(module)
      File "/Users/tasalta/anaconda/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 20, in <module>
        from ..egg_info import get_egg_info
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/egg_info.py", line 15, in <module>
        from .misc import rel_path
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/misc.py", line 19, in <module>
        from .core.index import get_index, _supplement_index_with_cache
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 9, in <module>
        from .repodata import collect_all_repodata
      File "/Users/tasalta/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 21, in <module>
        from requests.packages.urllib3.exceptions import InsecureRequestWarning
    ImportError: cannot import name InsecureRequestWarning

    at throwCondaError (/Applications/GraphLab Create Launcher.app/Contents/Resources/app.asar/utils/conda.js:117:9)
    at runConda (/Applications/GraphLab Create Launcher.app/Contents/Resources/app.asar/utils/conda.js:146:5)
    at Object.info (/Applications/GraphLab Create Launcher.app/Contents/Resources/app.asar/utils/conda.js:395:10)
    at Object.isGLCLauncherReady (/Applications/GraphLab Create Launcher.app/Contents/Resources/app.asar/utils/systemState.js:207:27)
    at [object Object].onWindowOpen [as _onTimeout] (/Applications/GraphLab Create Launcher.app/Contents/Resources/app.asar/main.js:144:57)
    at Timer.listOnTimeout (timers.js:89:15)

**Comment by kalefranz** [comment]
fixed with #5093
