### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by KonanPS** [conda/conda#5029]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

`$ /Users/pavelkonan/anaconda3/bin/conda info --json`

    Traceback (most recent call last):
      File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 84, in _main
        from ..base.context import context
      File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/conda/base/context.py", line 18, in <module>
        from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
      File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/conda/common/configuration.py", line 30, in <module>
        from cytoolz.dicttoolz import merge
      File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/cytoolz/__init__.py", line 1, in <module>
        from .itertoolz import *
      File "cytoolz/itertoolz.pyx", line 19, in init cytoolz.itertoolz (cytoolz/itertoolz.c:28089)
        from cytoolz.utils import no_default
      File "cytoolz/utils.pyx", line 1, in init cytoolz.utils (cytoolz/utils.c:2604)
        import doctest
      File "/Users/pavelkonan/anaconda3/lib/python3.5/doctest.py", line 101, in <module>
        import pdb
      File "/Users/pavelkonan/anaconda3/lib/python3.5/pdb.py", line 135, in <module>
        class Pdb(bdb.Bdb, cmd.Cmd):
    AttributeError: module 'cmd' has no attribute 'Cmd'

[E 12:38:26.643 NotebookApp] [nb_conda_kernels] couldn't call conda:
    Command '['conda', 'info', '--json']' returned non-zero exit status 1
[I 12:38:26.644 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
Traceback (most recent call last):
  File "/Users/pavelkonan/anaconda3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 652, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1071, in initialize
    self.init_webapp()
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 892, in init_webapp
    self.jinja_environment_options
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 132, in __init__
    default_url, settings_overrides, jinja_env_options)
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 202, in init_settings
    nbextensions_path=ipython_app.nbextensions_path,
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 643, in nbextensions_path
    from IPython.paths import get_ipython_dir
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/IPython/core/application.py", line 25, in <module>
    from IPython.core import release, crashhandler
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/IPython/core/crashhandler.py", line 28, in <module>
    from IPython.core import ultratb
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/IPython/core/ultratb.py", line 119, in <module>
    from IPython.core import debugger
  File "/Users/pavelkonan/anaconda3/lib/python3.5/site-packages/IPython/core/debugger.py", line 45, in <module>
    from pdb import Pdb as OldPdb
  File "/Users/pavelkonan/anaconda3/lib/python3.5/pdb.py", line 135, in <module>
    class Pdb(bdb.Bdb, cmd.Cmd):
AttributeError: module 'cmd' has no attribute 'Cmd'

**Comment by KonanPS** [comment]
This had happened after installing macOS Sierra 10.12.3 update

**Comment by kalefranz** [comment]
Interesting. What version of cytoolz do you have?  Conda might be completely borked in that environment with a bad cytoolz, but you might be able to get a away with just deleting it and reinstalling.

    rm -rf /Users/pavelkonan/anaconda3/lib/python3.5/site-packages/cytoolz
    conda install --force cytoolz
