### ISSUE TITLE
Persistent S3 timeouts

### ISSUE THREAD

**Issue by wesm** [conda/conda#5032]
For the last week or two, we've been getting build failures like the following, affecting somewhere around 20% of builds. seems there are others affected also 

```
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.9
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/travis/miniconda  (writable)
    default environment : /home/travis/build/apache/arrow/parquet-env
       envs directories : /home/travis/miniconda/envs
          package cache : /home/travis/miniconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/travis/.condarc
           offline mode : False

`$ /home/travis/build/apache/arrow/parquet-env/bin/conda install -y -q thrift-cpp snappy zlib brotli boost`

    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/home/travis/miniconda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 298, in _error_catcher
        yield
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 380, in read
        data = self._fp.read(amt)
      File "/home/travis/miniconda/lib/python3.6/http/client.py", line 449, in read
        n = self.readinto(b)
      File "/home/travis/miniconda/lib/python3.6/http/client.py", line 493, in readinto
        n = self.fp.readinto(b)
      File "/home/travis/miniconda/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 273, in recv_into
        return self.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 273, in recv_into
        return self.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 273, in recv_into
        return self.recv_into(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 271, in recv_into
        raise timeout('The read operation timed out')
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/models.py", line 703, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 432, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 397, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "/home/travis/miniconda/lib/python3.6/contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 303, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "/home/travis/miniconda/lib/python3.6/site-packages/requests/models.py", line 710, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open '/home/travis/miniconda/pkgs/boost-cpp-1.63.0-2.tar.bz2.part' for writing (HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.).
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/travis/miniconda/lib/python3.6/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open '/home/travis/miniconda/pkgs/boost-cpp-1.63.0-2.tar.bz2.part' for writing (HTTPSConnectionPool(host='s3.amazonaws.com', port=443): Read timed out.).
```

see full build https://travis-ci.org/apache/arrow/jobs/220626911

Any idea what's going on?

**Comment by kalefranz** [comment]
Hey Wes, Thanks for the report.  First, the conda 4.3 HTTP error messages are much better; no more janky RuntimeError stack trace.

Google led me to https://github.com/pyca/pyopenssl/issues/168 and http://www.pyopenssl.org/en/stable/api/ssl.html#OpenSSL.SSL.WantReadError.  So it appears to me this is (just) an ssl handshake timeout with s3 (not that s3 should be timing out).  We're having the anaconda.org team look into this.

In the meantime, one thing you could try is switching to conda 4.3 and configuring the timeout value.  In conda 4.2, the http connect timeout value is 6.1 seconds.  The default value in conda 4.3 is 9.15 seconds, and you can also override that configuration yourself.

    conda config --set remote_connect_timeout_secs 12

For your CI setup, to stop the conda-forge 4.2.13 conda coming in and overriding the latest conda that's in repo.continuum.io, add

    conda config --set auto_update_conda false

after line 29 in https://github.com/apache/arrow/blob/master/ci/travis_install_conda.sh#L29

**Comment by wesm** [comment]
Great, thank you. We also want to set up Travis CI to cache the conda package directory so we aren't re-pulling them from repo.continuum.io / anaconda.org on every build, which seems wasteful. Do you have any examples of doing that in Travis?

**Comment by kalefranz** [comment]
I don't.  Does Travis CI keep it's cache in a particular location locally?  If that's something that conda doesn't know about, you can tell conda about it by overriding the default value for `pkgs_dirs`.

For more details on configuration, I just published https://www.continuum.io/blog/developer-blog/conda-configuration-engine-power-users.  There's a new `conda config --describe` command that will be the source of truth for configuration parameters available; we're working on updating the docs now, but they'll probably always lag a bit behind.

**Comment by wesm** [comment]
How can I set `pkgs_dirs`? I tried:

`conda config --set pkgs_dirs $HOME/.conda_packages`

but that didn't work. If I can set that, then with https://docs.travis-ci.com/user/caching/ it should be possible to cache the tarballs

**Comment by kalefranz** [comment]
`pkg_dirs` is a list parameter, so it would be `conda config --add pkgs_dirs $HOME/.conda_packages`.  Doing that will probably completely replace the default value, so you'll want to run `conda config --show` first, see what the default values are, and make sure they end up exactly what you want after you do the `conda config --add pkgs_dirs $HOME/.conda_packages`.

**Comment by pitrou** [comment]
I don't think caching on Travis-CI would be recommended. To quote the [Travis-CI docs](https://docs.travis-ci.com/user/caching/#Things-not-to-cache):

> Large files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source

"Quick to install but slow to download" seems like an accurate description of conda packages. Note the Travis-CI cache is backed by... S3.

**Comment by wesm** [comment]
We would at least have a reasonable expectation that Travis's buckets are in the same region as their VMs, though, right? I'll keep an eye on the build times and remove the caching if it doesn't seem to be improving flakiness or build times

**Comment by pitrou** [comment]
I *think* I tried Travis caching on conda packages at some point and got no speedup. But perhaps the conditions are different right now.

**Comment by abarto** [comment]
Is this still happening? If so, do you know if the timeouts are on conda.anaconda.org or repo.continuum.io packages?

**Comment by kalefranz** [comment]
To my knowledge all issues here have been resolved.  Closing this ticket.  Let me know if we need to re-open.

If however, it's 3 months down the road, and google brings you to this ticket because of anaconda.org or repo.continuum.io availability problems, please file a new ticket.
