### ISSUE TITLE
Creating env with qt UnsatisfiableError

### ISSUE THREAD

**Issue by milindsmart** [conda/conda#5035]
I use miniconda3 on my system and I am trying to build pgAdmin4 v1.3 on Windows 7 x64 by following the [given instructions ](https://git.postgresql.org/gitweb/?p=pgadmin4.git;a=blob_plain;f=README;hb=1e5de7e66e7e578a7803087389d18102e0f5d945). When I try to create a conda environment with qt

`conda create -n pgamk qt`

I get an UnsatisfiableError : 
```
Fetching package metadata .............
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - qt
Use "conda info <package>" to see the dependencies for each package.
```

This is even though `qt` is happily installed in the root environment
```
C:\>conda list qt
# packages in environment at C:\Users\<username>\Miniconda3:
#
pyqt                      5.6.0                    py35_2
qt                        5.6.2                    vc14_3  [vc14]
qtawesome                 0.4.1                    py35_0
qtconsole                 4.2.1                    py35_2
qtpy                      1.2.1                    py35_0
```

Seems like a bug.

**Comment by goanpeca** [comment]
@milindsmart could you type `conda info` on the prompt and paste the output here?

**Comment by milindsmart** [comment]
Apologies for the delay.
```
Current conda install:

               platform : win-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.5.1.final.0
       requests version : 2.12.4
       root environment : C:\Users\Milind\Miniconda3  (writable)
    default environment : C:\Users\Milind\Miniconda3
       envs directories : C:\Users\Milind\Miniconda3\envs
                          C:\Users\Milind\AppData\Local\conda\conda\envs
                          C:\Users\Milind\.conda\envs
          package cache : C:\Users\Milind\Miniconda3\pkgs
                          C:\Users\Milind\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Milind\.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.12.4 CPython/3.5.1 Windows/7 Windows/6.1.7601
```

**Comment by milindsmart** [comment]
I tried out the verbose option and it gave:

```
C:\Users\Milind\Downloads>conda create -n pgamk -v qt
Fetching package metadata .............
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



overtaking stderr and stdout

stderr and stdout yielding back

```
It repeated the `conda info` output, and then 

```
`$ C:\Users\Milind\Miniconda3\Scripts\conda-script.py create -n pgamk -v qt`




    Traceback (most recent call last):
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\exceptions.py", l
ine 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\main.py", lin
e 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\main_create.p
y", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\install.py",
line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\Milind\Miniconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\common.py", l
ine 586, in json_progress_bars
        yield
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\install.py",
line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\plan.py", line 48
8, in install_actions_list
        for dists_by_prefix in required_solves]
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\plan.py", line 48
8, in <listcomp>
        for dists_by_prefix in required_solves]
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\plan.py", line 63
4, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\resolve.py", line
 802, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\resolve.py", line
 856, in solve
        self.find_conflicts(specs)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\resolve.py", line
 371, in find_conflicts
        raise UnsatisfiableError(bad_deps)
    conda.exceptions.UnsatisfiableError: The following specifications were found
 to be in conflict:
      - qt
    Use "conda info <package>" to see the dependencies for each package.
```

I went one level further on the verbosity and it returned (I'm snipping off a lot of package metadata back-and-forth info, and stuff that's repeated with the `-v` output given above) : 
```
DEBUG conda.core.repodata:fetch_repodata(444): 304 NOT MODIFIED for 'https://rep
o.continuum.io/pkgs/msys2/noarch'. Updating mtime and loading from disk
.
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for
prefix 'C:\Users\Milind\Miniconda3' using path 'C:\Users\Milind\Miniconda3\conda
-meta\history'
DEBUG conda.plan:add_defaults_to_specs(371): H0 specs=['qt']
DEBUG conda.plan:add_defaults_to_specs(386): H2 python True
DEBUG conda.plan:add_defaults_to_specs(386): H2 lua False
DEBUG conda.plan:add_defaults_to_specs(391): H2A lua
DEBUG conda.plan:add_defaults_to_specs(417): HF specs=['qt']
DEBUG conda.plan:augment_specs(695): Pinned specs=()
DEBUG conda.resolve:install_specs(781): Checking satisfiability of current insta
ll
DEBUG conda.resolve:bad_installed(731): Checking if the current environment is c
onsistent
Solving package specifications: DEBUG conda.resolve:solve(836): Solving for [Mat
chSpec('qt')]
DEBUG conda.resolve:get_reduced_index(374): Retrieving packages for: [MatchSpec(
'qt')]
DEBUG conda.resolve:filter_group(399): libpng: pruned from 11 -> 10
.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
```

Hope this helps.

**Comment by milindsmart** [comment]
So I went to the verbosity level 3 as well while I was at it, output : 
```
`$ C:\Users\Milind\Miniconda3\Scripts\conda-script.py create -n pgamk -v -v -v q
t`




    Traceback (most recent call last):
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\exceptions.py", l
ine 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\main.py", lin
e 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\main_create.p
y", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\install.py",
line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\Milind\Miniconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\common.py", l
ine 586, in json_progress_bars
        yield
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\cli\install.py",
line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\plan.py", line 48
8, in install_actions_list
        for dists_by_prefix in required_solves]
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\plan.py", line 48
8, in <listcomp>
        for dists_by_prefix in required_solves]
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\plan.py", line 63
4, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\resolve.py", line
 802, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\resolve.py", line
 856, in solve
        self.find_conflicts(specs)
      File "C:\Users\Milind\Miniconda3\lib\site-packages\conda\resolve.py", line
 371, in find_conflicts
        raise UnsatisfiableError(bad_deps)
    conda.exceptions.UnsatisfiableError: The following specifications were found
 to be in conflict:
      - qt
    Use "conda info <package>" to see the dependencies for each package.

```
Honestly, this is still very little data on the actual conflict, but just thought I'll exhaust this avenue as well while waiting for some assistance/direction.

**Comment by milindsmart** [comment]
Bump? Help needed to identify bug in code/mistake in my actions.

**Comment by kalefranz** [comment]
Something really weird happening.  Try `conda clean --all`.  And then see how far you get.

**Comment by milindsmart** [comment]
Cleared 1.2 GB of packages etc. Absolutely no difference, same response to `conda create`.

**Comment by milindsmart** [comment]
Bump...

**Comment by milindsmart** [comment]
bump... ? I ran into similarly mysterious issues with PyQt5 and Spyder 3.1.4 on Fedora, so it's probably something to do with Qt moving from WebKit to Chromium.

**Comment by kalefranz** [comment]
Is this still an issue (especially after an upgrade to conda 4.4)? Did we ever figure out what the root cause was?
