### ISSUE TITLE
Cannot create my private conda env using root-owned miniconda installation

### ISSUE THREAD

**Issue by przemolb** [conda/conda#5043]
Hi all,

I am trying to:
- install miniconda as root (so it can be shared between different users). Done. Working
- create conda virtual env as a non-root user in my home folder. It doesn't work. (please see below)

`
$ /opt/apps/sas/miniconda/bin/conda create -p /home/adm-pbak/env/anaconda python=3.6 anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /opt/apps/sas/miniconda  (read only)
    default environment : /opt/apps/sas/miniconda
       envs directories : /opt/apps/sas/miniconda/envs
                          /home/adm-pbak/.conda/envs
          package cache : /opt/apps/sas/miniconda/pkgs
                          /home/adm-pbak/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Linux/2.6.32-642.13.1.el6.x86_64 Red Hat Enterprise Linux Server/6.8 glibc/2.12
                UID:GID : 34002:34000

`$ /opt/apps/sas/miniconda/bin/conda create -p /home/adm-pbak/env/anaconda python=3.6 anaconda`

    Traceback (most recent call last):
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 491, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 200, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.index.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 144, in func
        res = f(*args, **kwargs)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 494, in fetch_repodata
        touch(cache_path)
      File "/opt/apps/sas/miniconda/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 64, in touch
        utime(path, None)
    PermissionError: [Errno 13] Permission denied
`

Does anybody know why ?

**Comment by kalefranz** [comment]
You're just on an older version of conda. Latest is 4.3.16, and all of these issues have been fixed. As root user, `conda update conda`

**Comment by przemolb** [comment]
I have just installed a new miniconda (+ conda update conda):
`$ /opt/external/conda/bin/conda create -p /home/adm-pbak/env/anaconda python=3.6 anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : /opt/external/conda  (read only)
    default environment : /opt/external/conda
       envs directories : /opt/apps/adm-pbak
                          /home/adm-pbak/.conda/envs
                          /opt/external/conda/envs
          package cache : /opt/external/conda/pkgs
                          /opt/apps/adm-pbak/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/adm-pbak/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.6.1 Linux/2.6.32-642.13.1.el6.x86_64 Red Hat Enterprise Linux Server/6.8 glibc/2.12
                UID:GID : 34002:34000



`$ /opt/external/conda/bin/conda create -p /home/adm-pbak/env/anaconda python=3.6 anaconda`




    Traceback (most recent call last):
      File "/opt/external/conda/lib/python3.6/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/external/conda/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 463, in <listcomp>
        for url, schan, pri in tasks]
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/opt/external/conda/lib/python3.6/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/opt/external/conda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/packages/urllib3/connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "/opt/external/conda/lib/python3.6/site-packages/requests/packages/urllib3/connection.py", line 326, in connect
        ssl_context=context)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/packages/urllib3/util/ssl_.py", line 322, in ssl_wrap_socket
        context.load_cert_chain(certfile, keyfile)
      File "/opt/external/conda/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 416, in load_cert_chain
        self._ctx.use_certificate_file(certfile)
      File "/opt/external/conda/lib/python3.6/site-packages/OpenSSL/SSL.py", line 596, in use_certificate_file
        _raise_current_error()
      File "/opt/external/conda/lib/python3.6/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]

`
