### ISSUE TITLE
issues when install scrapy using conda

### ISSUE THREAD

**Issue by suihansongmao** [conda/conda#5047]
The following is the detail error description:
Current conda install:

               platform : win-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (read only)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\pengwei\AppData\Local\conda\conda\envs
                          C:\Users\pengwei\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\pengwei\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Miniconda3\Scripts\conda-script.py install -c conda-forge scrapy`

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 125, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 552, in fetch_index
        repodatas = _collect_repodatas(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 541, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 514, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 144, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\index.py", line 500, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Miniconda3\\pkgs\\cache\\2116b818.json'

**Comment by nehaljwani** [comment]
Try any one of the following:
- Launch the Anaconda Prompt (or cmd.exe) as administrator and then run `conda update conda`, then close it and then relaunch Anaconda Prompt (or cmd.exe) as a normal user.
- Reinstall Conda for your user only and then run `conda update conda`.

**Comment by tyler-thetyrant** [comment]
@suihansongmao  I cannot replicate the error on conda 4.3.16.
Did your error get fixed?

**Comment by kalefranz** [comment]
You're on windows, so right click on the Anaconda Prompt, choose "Run as administrator", and then `conda update conda`.  Fixed in 4.3.13.

**Comment by suihansongmao** [comment]
Thanks for all of your reply! I follow your suggestion: uninstall conda and reinstall it only for me. then i run conda update conda, and then I install scrapy using the command: conda install -c conda-forge scrapy. This time it didn't occur PermissionError. Although there are still some net connection problem, it's not the miniconda's problem. Thanks again
