### ISSUE TITLE
Error creating a new anaconda environment

### ISSUE THREAD

**Issue by peadar-elevate** [conda/conda#5049]
```
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.4.3.final.0
       requests version : 2.11.1
       root environment : /home/springcoil/miniconda  (writable)
    default environment : /home/springcoil/miniconda
       envs directories : /home/springcoil/miniconda/envs
          package cache : /home/springcoil/miniconda/pkgs
           channel URLs : https://conda.anaconda.org/bonzanini/linux-64
                          https://conda.anaconda.org/bonzanini/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/t/<TOKEN>/elevatedirect/linux-64
                          https://conda.anaconda.org/t/<TOKEN>/elevatedirect/noarch
            config file : /home/springcoil/.condarc
           offline mode : False



`$ /home/springcoil/miniconda/bin/conda create -n keras python=3.5 anaconda`




    Traceback (most recent call last):
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/home/springcoil/miniconda/lib/python3.4/site-packages/conda/install.py", line 809, in extract
        with tarfile.open(fname) as t:
      File "/home/springcoil/miniconda/lib/python3.4/tarfile.py", line 1553, in open
        raise ReadError("file could not be opened successfully")
    tarfile.ReadError: file could not be opened successfully
```

**Comment by nehaljwani** [comment]
Strange, looks like a corrupt tarball to me. Does the following command fix your problem?
```
conda clean --tarballs -y
```

**Comment by kalefranz** [comment]
Agreed.  Also, sure wish we could get conda-forge to bump to 4.3.  We're on 4.3.16 already :-/
