### ISSUE TITLE
Failure to update Anaconda3

### ISSUE THREAD

**Issue by PatternSearcher** [conda/conda#5051]
Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Sandile\Anaconda3  (writable)
    default environment : C:\Users\Sandile\Anaconda3
       envs directories : C:\Users\Sandile\Anaconda3\envs
          package cache : C:\Users\Sandile\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\Sandile\Anaconda3\Scripts\conda-script.py update --prefix C:\Users\Sandile\Anaconda3 anaconda`

    Traceback (most recent call last):
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\install.py", line 812, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "C:\Users\Sandile\Anaconda3\lib\site-packages\conda\common\disk.py", line 165, in exp_backoff_fn
        result = fn(*args, **kwargs)
    PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Sandile\\Anaconda3\\pkgs\\mkl-2017.0.1-0.tmp' -> 'C:\\Users\\Sandile\\Anaconda3\\pkgs\\mkl-2017.0.1-0'

**Comment by kalefranz** [comment]
This is a windows locking issue that I think has been completely resolved in conda 4.3.  The current conda 4.3 release is 4.3.16.
