### ISSUE TITLE
conda create --name=xx python=2.7 error

### ISSUE THREAD

**Issue by lidawei** [conda/conda#5052]
Current conda install:

               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /root/anaconda2  (writable)
    default environment : /root/anaconda2
       envs directories : /root/anaconda2/envs
                          /root/.conda/envs
          package cache : /root/anaconda2/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-642.11.1.el6.x86_64 CentOS/6.7 glibc/2.12
                UID:GID : 0:0

`$ /root/anaconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/root/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 130, in install
        context.validate_configuration()
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 838, in validate_configuration
        raise_errors(tuple(chain.from_iterable((errors, post_errors))))
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 836, in <genexpr>
        for name in self.parameter_names)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 829, in _collect_validation_error
        func(*args, **kwargs)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 447, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 664, in _merge
        for match in relevant_matches)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/configuration.py", line 664, in <genexpr>
        for match in relevant_matches)
      File "/root/anaconda2/lib/python2.7/site-packages/conda/common/compat.py", line 89, in iteritems
        return d.iteritems(**kw)
    AttributeError: 'str' object has no attribute 'iteritems'

**Comment by foobar167** [comment]
![conda_python2 7_error](https://cloud.githubusercontent.com/assets/27219282/25040300/2da454be-2111-11e7-9fc6-eb593f430e76.jpg)

Windows 7, Conda version 4.3.16

**Comment by foobar167** [comment]
P.S. You could install python-2.7.12-0 instead of python-2.7.13-0 if it's not important for you.
`conda create --name python2.7 python=2.7.12`

**Comment by lidawei** [comment]
@foobar167 ,thank you
Package python 2.7.12-0 work fine
![image](https://cloud.githubusercontent.com/assets/524093/25042685/a031e042-214c-11e7-88c9-518e38f07c02.png)

![image](https://cloud.githubusercontent.com/assets/524093/25042703/ad7a1364-214c-11e7-8321-f7e748fcec25.png)
