### ISSUE TITLE
error when conda install -c conda-forge opencv

### ISSUE THREAD

**Issue by LeiChenML** [conda/conda#5060]
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/lei/anaconda2  (writable)
    default environment : /home/lei/anaconda2
       envs directories : /home/lei/anaconda2/envs
                          /home/lei/.conda/envs
          package cache : /home/lei/anaconda2/pkgs
                          /home/lei/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/lei/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.12.4 CPython/2.7.13 Linux/3.19.0-25-generic debian/jessie/sid glibc/2.19
                UID:GID : 1000:1000

`$ /home/lei/anaconda2/bin/conda install -c conda-forge opencv`

    Traceback (most recent call last):
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/home/lei/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 671, in urlopen
        release_conn=release_conn, **response_kw)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 323, in connect
        ssl_context=context)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "/home/lei/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 419, in wrap_socket
        rd, _, _ = select.select([sock], [], [], sock.gettimeout())
    error: (4, 'Interrupted system call')

**Comment by kalefranz** [comment]
> 'Interrupted system call'

Looks like this is a core python issue that was fixed in python 3.5.
http://stackoverflow.com/a/29411416/2127762
