### ISSUE TITLE
Anaconda installation issue

### ISSUE THREAD

**Issue by aratnat** [conda/conda#5070]
Completed Anaconda installation on windows 10. tried conda list from command prompt and received the following error:
Traceback (most recent call last):
  File "C:\Users\arath\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\exceptions.py", line 543, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\exceptions.py", line 513, in get_info
    args.func(args, p)
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 148, in execute
    from conda.api import get_index
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\core\index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\core\path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\gateways\download.py", line 16, in <module>
    from ..connection import CondaSession
  File "C:\Users\arath\Anaconda2\lib\site-packages\conda\connection.py", line 55, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1460, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1422, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]'

**Comment by kalefranz** [comment]
This is an error from core python itself, which means your python installation has somehow become corrupted.  Unfortunately, you'll probably have to just reinstall.
