### ISSUE TITLE
A error occur when I try to create a new python2.7 environment 

### ISSUE THREAD

**Issue by pcmagic** [conda/conda#5083]
I can ping the service:

  ping -c 3 repo.continuum.io
  PING repo.continuum.io (104.16.19.10) 56(84) bytes of data.
  64 bytes from 104.16.19.10: icmp_seq=1 ttl=53 time=42.7 ms
  64 bytes from 104.16.19.10: icmp_seq=2 ttl=53 time=42.2 ms
  64 bytes from 104.16.19.10: icmp_seq=3 ttl=53 time=41.9 ms

  --- repo.continuum.io ping statistics ---
  3 packets transmitted, 3 received, 0% packet loss, time 2001ms
  rtt min/avg/max/mdev = 41.936/42.318/42.761/0.339 ms

here is the error messages. 

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.10
         python version : 3.5.2.final.0
       requests version : 2.12.1
       root environment : /home/zhangji/anaconda3  (writable)
    default environment : /home/zhangji/anaconda3
       envs directories : /home/zhangji/anaconda3/envs
          package cache : /home/zhangji/anaconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /home/zhangji/anaconda3/bin/conda create --name py27 python=2.7 pip`

    Traceback (most recent call last):
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 138, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 98, in create_connection
        raise err
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
        sock.connect(sa)
    OSError: [Errno 101] Network is unreachable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 281, in connect
        conn = self._new_conn()
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connection.py", line 147, in _new_conn
        self, "Failed to establish a new connection: %s" % e)
    requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b8147eeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 671, in urlopen
        release_conn=release_conn, **response_kw)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 671, in urlopen
        release_conn=release_conn, **response_kw)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 671, in urlopen
        release_conn=release_conn, **response_kw)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/connectionpool.py", line 643, in urlopen
        _stacktrace=sys.exc_info()[2])
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/packages/urllib3/util/retry.py", line 363, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b8147eeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 394, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(6.1, 60))
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/requests/adapters.py", line 487, in send
        raise ConnectionError(e, request=request)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b8147eeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 405, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b8147eeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)): https://repo.continuum.io/pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "/home/zhangji/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/home/zhangji/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f2b8147eeb8>: Failed to establish a new connection: [Errno 101] Network is unreachable',)): https://repo.continuum.io/pkgs/free/linux-64/setuptools-27.2.0-py27_0.tar.bz2

**Comment by tyler-thetyrant** [comment]
You are using very old version of conda.`conda update conda` will bring you to Conda 4.3.16. Can you try again after updating it?

**Comment by pcmagic** [comment]
I tried what you suggest. Unfortunately, it doesn't work. 

Fetching package metadata ......

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port=443): Max retries exceeded with url: /pkgs/pro/linux-64/repodata.json.bz2 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7fc6f6c42e80>: Failed to establish a new connection: [Errno 101] Network is unreachable',))",),)

Is there any other way to update Conda safety?

**Comment by kalefranz** [comment]
@tyler-thetyrant unfortunately, 4.2.13 is the version that conda-forge is still on.  Not thrilled about it.  Sure wish they'd update...

Except now I'm seeing conda-forge isn't even in the channel list.  hmmf

@pcmagic ACK that ping works.  But what about

    curl https://repo.continuum.io/pkgs/free/linux-64/repodata.json

?

**Comment by jgieringer** [comment]
@kalefranz 
**Unable** to:
- `curl https://repo.anaconda.com/pkgs/main/linux-64/repodata.json`
**Able** to:
- `curl https://repo.continuum.io/pkgs/free/linux-64/repodata.json`
- `curl https://conda.anaconda.org/conda-forge/linux-64/repodata.json`

To fix my ` Failed to establish a new connection: [Errno 101] Network is unreachable`, I ended up editing my .condarc file to contain:
```channels:
  - conda-forge
  - free```

**Comment by nehaljwani** [comment]
@jgieringer It could be the case that you are behind a firewalled environment (probably along with an intercept proxy?) and *.anaconda.com is being blacklisted. 

Also, for whoever else faces the issue where ping works but http requests don't, understand that ping works on the ICMP protocol and HTTP (up to HTTP/2) work on TCP.  So it could be that outgoing ICMP requests are allowed from your host to the outside world, but making direct TCP connections might not be. If that's the case, please contact your network administrator to either allow that for *.anaconda.com and *.anaconda.org and *.continuum.io, or ask for the proper proxy configuration. If you see SSL errors, then it could be that you need to point REQUESTS_CA_BUNDLE env var to your intercept proxy's certificate.
