### ISSUE TITLE
conda update conda breaks conda environments

### ISSUE THREAD

**Issue by rammig** [conda/conda#5085]
We installed latest Minconda 3 and after updating conda and creating an environment conda breaks and we can not activate the environment.
Find below all our steps. This occurs on Ubuntu 16.04 and Mac OSX 10.12.3.

We are using long paths as they are autmatically created by our CI.
```
user@machine:~/Downloads$ bash Miniconda3-latest-MacOSX-x86_64.sh -b -p /Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
PREFIX=/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
installing: python-3.6.0-0 ...
installing: cffi-1.9.1-py36_0 ...
installing: conda-env-2.6.0-0 ...
installing: cryptography-1.7.1-py36_0 ...
installing: idna-2.2-py36_0 ...
installing: openssl-1.0.2k-0 ...
installing: pyasn1-0.1.9-py36_0 ...
installing: pycosat-0.6.1-py36_1 ...
installing: pycparser-2.17-py36_0 ...
installing: pyopenssl-16.2.0-py36_0 ...
installing: readline-6.2-2 ...
installing: requests-2.12.4-py36_0 ...
installing: ruamel_yaml-0.11.14-py36_1 ...
installing: setuptools-27.2.0-py36_0 ...
installing: six-1.10.0-py36_0 ...
installing: sqlite-3.13.0-0 ...
installing: tk-8.5.18-0 ...
installing: xz-5.2.2-1 ...
installing: yaml-0.1.6-0 ...
installing: zlib-1.2.8-3 ...
installing: conda-4.3.11-py36_0 ...
installing: pip-9.0.1-py36_1 ...
installing: wheel-0.29.0-py36_0 ...
Python 3.6.0 :: Continuum Analytics, Inc.
creating default environment...
installation finished.

user@machine:~$ cd testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin

user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ cat conda
#!/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin/python
if __name__ == '__main__':
    import sys
    import conda.cli

    sys.exit(conda.cli.main())


user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ ./python conda update conda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:

The following packages will be SUPERCEDED by a higher-priority channel:

    conda: 4.3.11-py36_0 defaults --> 4.2.13-py36_0 conda-forge

Proceed ([y]/n)? y

conda-4.2.13-p 100% |##########################################################################################################################################################| Time: 0:00:00 684.93 kB/s
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ cat conda
#!/usr/bin/env python
if __name__ == '__main__':
    import sys
    import conda.cli

    sys.exit(conda.cli.main())
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ export PATH=$PWD:$PATH
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ which conda
/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin/conda
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ conda create -n test py=3.6
Fetching package metadata .........
Solving package specifications: .


PackageNotFoundError: Package not found: '' Package missing in current osx-64 channels:
  - py 3.6*

You can search for packages on anaconda.org with

    anaconda search -t conda py


user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ conda create -n test python=3.6
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment /Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/envs/test:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2017.1.23  |                0         166 KB  conda-forge
    ncurses-5.9                |               10         1.1 MB  conda-forge
    sqlite-3.13.0              |                1         1.4 MB  conda-forge
    tk-8.5.19                  |                1         2.1 MB  conda-forge
    xz-5.2.2                   |                0         288 KB  conda-forge
    zlib-1.2.11                |                0          95 KB  conda-forge
    openssl-1.0.2k             |                0         3.3 MB  conda-forge
    readline-6.2               |                0         311 KB  conda-forge
    python-3.6.1               |                0        12.0 MB  conda-forge
    certifi-2017.1.23          |           py36_0         222 KB  conda-forge
    setuptools-33.1.1          |           py36_0         502 KB  conda-forge
    wheel-0.29.0               |           py36_0          82 KB  conda-forge
    pip-9.0.1                  |           py36_0         1.6 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        23.1 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.1.23-0      conda-forge
    certifi:         2017.1.23-py36_0 conda-forge
    ncurses:         5.9-10           conda-forge
    openssl:         1.0.2k-0         conda-forge
    pip:             9.0.1-py36_0     conda-forge
    python:          3.6.1-0          conda-forge
    readline:        6.2-0            conda-forge
    setuptools:      33.1.1-py36_0    conda-forge
    sqlite:          3.13.0-1         conda-forge
    tk:              8.5.19-1         conda-forge
    wheel:           0.29.0-py36_0    conda-forge
    xz:              5.2.2-0          conda-forge
    zlib:            1.2.11-0         conda-forge

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
ca-certificate 100% |##########################################################################################################################################################| Time: 0:00:00 425.83 kB/s
ncurses-5.9-10 100% |##########################################################################################################################################################| Time: 0:00:00   1.40 MB/s
sqlite-3.13.0- 100% |##########################################################################################################################################################| Time: 0:00:00   1.52 MB/s
tk-8.5.19-1.ta 100% |##########################################################################################################################################################| Time: 0:00:01   1.99 MB/s
xz-5.2.2-0.tar 100% |##########################################################################################################################################################| Time: 0:00:00 583.51 kB/s
zlib-1.2.11-0. 100% |##########################################################################################################################################################| Time: 0:00:00 329.90 kB/s
openssl-1.0.2k 100% |##########################################################################################################################################################| Time: 0:00:01   2.52 MB/s
readline-6.2-0 100% |##########################################################################################################################################################| Time: 0:00:00 662.95 kB/s
python-3.6.1-0 100% |##########################################################################################################################################################| Time: 0:00:02   5.87 MB/s
certifi-2017.1 100% |##########################################################################################################################################################| Time: 0:00:00 385.70 kB/s
setuptools-33. 100% |##########################################################################################################################################################| Time: 0:00:00 869.31 kB/s
wheel-0.29.0-p 100% |##########################################################################################################################################################| Time: 0:00:00 287.15 kB/s
pip-9.0.1-py36 100% |##########################################################################################################################################################| Time: 0:00:00   1.77 MB/s
Extracting packages ...
[      COMPLETE      ]|#############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|#############################################################################################################################################################################| 100%
#
# To activate this environment, use:
# > source activate test
#
# To deactivate this environment, use:
# > source deactivate test
#

user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ source activate test
Traceback (most recent call last):
  File "/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin/conda", line 4, in <module>
    import conda.cli
ModuleNotFoundError: No module named 'conda'
-bash: [: =: unary operator expected
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ conda
Traceback (most recent call last):
  File "/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/envs/test/bin/conda", line 4, in <module>
    import conda.cli
ModuleNotFoundError: No module named 'conda'
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ cat conda
#!/usr/bin/env python
if __name__ == '__main__':
    import sys
    import conda.cli

    sys.exit(conda.cli.main())
    
    
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ echo $PATH
/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/envs/test/bin:/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin:/Users/user/Downloads/spark-2.0.0-bin-hadoop2.7/bin/:/Users/user/anaconda/bin:/Developer/NVIDIA/CUDA-7.5/bin:Users/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin

user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ ll ../envs/test/bin/
total 5104
drwxr-xr-x  67 user  staff   2,2K 20 Apr 16:48 ./
drwxr-xr-x   8 user  staff   272B 20 Apr 16:48 ../
lrwxr-xr-x   1 user  staff     8B 20 Apr 16:47 2to3@ -> 2to3-3.6
-rwxrwxr-x   1 user  staff    96B 20 Apr 16:47 2to3-3.6*
lrwxr-xr-x   1 user  staff   177B 20 Apr 16:48 activate@ -> /Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin/activate
-rwxrwxr-x   1 user  staff   5,3K 20 Apr 16:47 c_rehash*
lrwxr-xr-x   1 user  staff     3B 20 Apr 16:47 captoinfo@ -> tic
-rwxrwxr-x   2 user  staff    13K  3 Dez 09:53 clear*
lrwxr-xr-x   1 user  staff   174B 20 Apr 16:48 conda@ -> /Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin/conda
lrwxr-xr-x   1 user  staff   179B 20 Apr 16:48 deactivate@ -> /Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin/deactivate
-rwxrwxr-x   1 user  staff   161B 20 Apr 16:48 easy_install*
-rwxrwxr-x   1 user  staff   454B 20 Apr 16:48 easy_install-3.6*
lrwxr-xr-x   1 user  staff     7B 20 Apr 16:47 idle3@ -> idle3.6
-rwxrwxr-x   1 user  staff    94B 20 Apr 16:47 idle3.6*
-rwxrwxr-x   2 user  staff    71K  3 Dez 09:53 infocmp*
lrwxr-xr-x   1 user  staff     3B 20 Apr 16:47 infotocap@ -> tic
lrwxr-xr-x   1 user  staff     2B 20 Apr 16:47 lzcat@ -> xz
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzcmp@ -> xzdiff
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzdiff@ -> xzdiff
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzegrep@ -> xzgrep
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzfgrep@ -> xzgrep
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzgrep@ -> xzgrep
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzless@ -> xzless
lrwxr-xr-x   1 user  staff     2B 20 Apr 16:47 lzma@ -> xz
-rwxr-xr-x   2 user  staff    14K 28 Jun  2016 lzmadec*
-rwxr-xr-x   2 user  staff    14K 28 Jun  2016 lzmainfo*
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 lzmore@ -> xzmore
-rwxrwxr-x   1 user  staff   5,6K 20 Apr 16:47 ncurses5-config*
-rwxrwxr-x   1 user  staff   5,6K 20 Apr 16:47 ncursesw5-config*
-rwxrwxr-x   2 user  staff   556K 10 Apr 16:41 openssl*
-rwxr-xr-x   1 user  staff   105B 20 Apr 16:48 pip*
lrwxr-xr-x   1 user  staff     8B 20 Apr 16:47 pydoc@ -> pydoc3.6
lrwxr-xr-x   1 user  staff     8B 20 Apr 16:47 pydoc3@ -> pydoc3.6
-rwxrwxr-x   1 user  staff    79B 20 Apr 16:47 pydoc3.6*
lrwxr-xr-x   1 user  staff     9B 20 Apr 16:47 python@ -> python3.6
lrwxr-xr-x   1 user  staff     9B 20 Apr 16:47 python3@ -> python3.6
lrwxr-xr-x   1 user  staff    17B 20 Apr 16:47 python3-config@ -> python3.6m-config
-rwxrwxr-x   1 user  staff    13K 20 Apr 16:47 python3.6*
lrwxr-xr-x   1 user  staff    17B 20 Apr 16:47 python3.6-config@ -> python3.6m-config
-rwxrwxr-x   1 user  staff    13K 20 Apr 16:47 python3.6m*
-rwxrwxr-x   1 user  staff   2,0K 20 Apr 16:47 python3.6m-config*
lrwxr-xr-x   1 user  staff    10B 20 Apr 16:47 pyvenv@ -> pyvenv-3.6
-rwxrwxr-x   1 user  staff   436B 20 Apr 16:47 pyvenv-3.6*
lrwxr-xr-x   1 user  staff     4B 20 Apr 16:47 reset@ -> tset
-rwxr-xr-x   2 user  staff   1,3M  8 Jun  2016 sqlite3*
-rwxrwxr-x   2 user  staff    18K  3 Dez 09:53 tabs*
lrwxr-xr-x   1 user  staff     8B 20 Apr 16:47 tclsh@ -> tclsh8.5
-rwxrwxr-x   2 user  staff    13K  3 Dez 19:37 tclsh8.5*
-rwxrwxr-x   2 user  staff    80K  3 Dez 09:53 tic*
-rwxrwxr-x   2 user  staff    19K  3 Dez 09:53 toe*
-rwxrwxr-x   2 user  staff    23K  3 Dez 09:53 tput*
-rwxrwxr-x   2 user  staff    28K  3 Dez 09:53 tset*
lrwxr-xr-x   1 user  staff     2B 20 Apr 16:47 unlzma@ -> xz
lrwxr-xr-x   1 user  staff     2B 20 Apr 16:47 unxz@ -> xz
-rwxr-xr-x   1 user  staff   119B 20 Apr 16:48 wheel*
lrwxr-xr-x   1 user  staff     7B 20 Apr 16:47 wish@ -> wish8.5
-rwxrwxr-x   2 user  staff    21K  3 Dez 19:37 wish8.5*
-rwxr-xr-x   2 user  staff    94K 28 Jun  2016 xz*
lrwxr-xr-x   1 user  staff     2B 20 Apr 16:47 xzcat@ -> xz
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 xzcmp@ -> xzdiff
-rwxr-xr-x   2 user  staff    14K 28 Jun  2016 xzdec*
-rwxr-xr-x   2 user  staff   6,5K 28 Jun  2016 xzdiff*
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 xzegrep@ -> xzgrep
lrwxr-xr-x   1 user  staff     6B 20 Apr 16:47 xzfgrep@ -> xzgrep
-rwxr-xr-x   2 user  staff   5,5K 28 Jun  2016 xzgrep*
-rwxr-xr-x   2 user  staff   1,8K 28 Jun  2016 xzless*
-rwxr-xr-x   2 user  staff   2,1K 28 Jun  2016 xzmore*
user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$

user@machine:~/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin$ env | grep -i conda
PATH=/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/envs/test/bin:/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin:/Users/user/Downloads/spark-2.0.0-bin-hadoop2.7/bin/:/Users/user/anaconda/bin:/Developer/NVIDIA/CUDA-7.5/bin:Users/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
CONDA_PATH_BACKUP=/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home/bin:/Users/user/Downloads/spark-2.0.0-bin-hadoop2.7/bin/:/Users/user/anaconda/bin:/Developer/NVIDIA/CUDA-7.5/bin:Users/user/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
CONDA_PREFIX=/Users/user/testXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX/envs/test
CONDA_PS1_BACKUP=\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]$
CONDA_DEFAULT_ENV=test

```

**Comment by rammig** [comment]
this occurs with conda from conda-forge as well as from continuum default channels

**Comment by kalefranz** [comment]
I've tried reproducing this, and I haven't been able to so far.  I do believe it's a possible bug, but without being able to reproduce it, I'm not sure where to start looking for the solution.

**Comment by dgonzo** [comment]
Currently hitting the same bug using jupyter [docker-stacks](https://github.com/jupyter/docker-stacks)
