### ISSUE TITLE
install opencv error on windows 10

### ISSUE THREAD

**Issue by jasonustc** [conda/conda#5128]
I install opencv by running the following two commands:
```conda config --add channels menpo```
```conda install opencv```

And got the following error:
    Traceback (most recent call last):
      File "C:\apps\anaconda\lib\site-packages\conda\exceptions.py", line 473, i
n conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\apps\anaconda\lib\site-packages\conda\cli\main.py", line 144, in
_main
        exit_code = args.func(args, p)
      File "C:\apps\anaconda\lib\site-packages\conda\cli\main_install.py", line
80, in execute
        install(args, parser, 'install')
      File "C:\apps\anaconda\lib\site-packages\conda\cli\install.py", line 420,
in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "C:\apps\anaconda\lib\site-packages\conda\__init__.py", line 45, in _
_str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 238

**Comment by jasonustc** [comment]
report installation bug of opencv

**Comment by kalefranz** [comment]
Please provide the output of `conda info`.
