### ISSUE TITLE
clone environment failed on miniconda2

### ISSUE THREAD

**Issue by HubertTeyssedre** [conda/conda#5130]
Dear everyone,

I am a beginner, and I tried to clone my environnement (for backup). And I have the following issue:

Traceback (most recent call last):
  File "C:\dev\Miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\dev\Miniconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\dev\Miniconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\dev\Miniconda2\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\dev\Miniconda2\lib\site-packages\conda\cli\install.py", line 247, in install
    clone(args.clone, prefix, json=args.json, quiet=args.quiet, index=index)
  File "C:\dev\Miniconda2\lib\site-packages\conda\cli\install.py", line 84, in clone
    quiet=quiet, index=index)
  File "C:\dev\Miniconda2\lib\site-packages\conda\misc.py", line 246, in clone_env
    sorted_dists = r.dependency_sort(dists)
  File "C:\dev\Miniconda2\lib\site-packages\conda\resolve.py", line 729, in dependency_sort
    depends = lookup(value)
  File "C:\dev\Miniconda2\lib\site-packages\conda\resolve.py", line 724, in lookup
    return set(ms.name for ms in self.ms_depends(value + '.tar.bz2'))
  File "C:\dev\Miniconda2\lib\site-packages\conda\resolve.py", line 573, in ms_depends
    deps = [MatchSpec(d) for d in self.index[fn].get('depends', [])]
KeyError: 'cvxopt-1.1.8-py27_0.tar.bz2'

The current conda install is the following one:

Current conda install:

             platform : win-64
        conda version : 4.0.5
  conda-build version : not installed
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : C:\dev\Miniconda2  (writable)
  default environment : C:\dev\Miniconda2
     envs directories : C:\dev\Miniconda2\envs
        package cache : C:\dev\Miniconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

Does anyone know if I can fix it with minor effort?

Best regards,
Hubert

**Comment by kalefranz** [comment]
Clone was pretty broken in conda 4.0.5.  I recommend `conda update conda`.  Latest version is 4.3.16, soon to be 4.3.17.
