### ISSUE TITLE
Can't create env, instal package: PackageNotFoundError: Package not found: Conda could not find '

### ISSUE THREAD

**Issue by rodji** [conda/conda#5143]
Trying crete environment;
>conda create --name firstenv untitled --debug

`
(C:\ProgramData\Anaconda2) c:\Users\Igorek>conda create --name firstenv untitled --debug
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Anaconda2' using path 'C:\ProgramData\Anaconda2\conda-meta\history'
DEBUG conda.core.index:fetch_index(105): channel_urls=OrderedDict([(u'https://repo.continuum.io/pkgs/free/win-64', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/free/noarch', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/r/win-64', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/r/noarch', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/pro/win-64', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/pro/noarch', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/msys2/win-64', (u'defaults', 0)), (u'https://repo.continuum.io/pkgs/msys2/noarch', (u'defaults', 0))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/free/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\2116b818.json. Timeout in 7 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\2116b818.q
DEBUG conda.core.repodata:read_pickled_repodata(348): setting priority for https://repo.continuum.io/pkgs/free/win-64 to '0'
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/free/noarch at C:\ProgramData\Anaconda2\pkgs\cache\9ca791dd.json. Timeout in 8 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\9ca791dd.q
DEBUG conda.core.repodata:read_pickled_repodata(348): setting priority for https://repo.continuum.io/pkgs/free/noarch to '0'
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/r/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\bf91db7e.json. Timeout in 8 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\bf91db7e.q
DEBUG conda.core.repodata:read_pickled_repodata(348): setting priority for https://repo.continuum.io/pkgs/r/win-64 to '0'
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/r/noarch at C:\ProgramData\Anaconda2\pkgs\cache\716b88c0.json. Timeout in 8 sec
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/pro/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\709bdc73.json. Timeout in 8 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\709bdc73.q
DEBUG conda.core.repodata:read_pickled_repodata(348): setting priority for https://repo.continuum.io/pkgs/pro/win-64 to '0'
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/pro/noarch at C:\ProgramData\Anaconda2\pkgs\cache\08159f17.json. Timeout in 8 sec
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/msys2/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\9767c1d0.json. Timeout in 8 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\9767c1d0.q
DEBUG conda.core.repodata:read_pickled_repodata(348): setting priority for https://repo.continuum.io/pkgs/msys2/win-64 to '0'
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/msys2/noarch at C:\ProgramData\Anaconda2\pkgs\cache\814cd719.json. Timeout in 8 sec
.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

INFO conda.common.io:captured(59): overtaking stderr and stdout
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Anaconda2' using path 'C:\ProgramData\Anaconda2\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Anaconda2' using path 'C:\ProgramData\Anaconda2\conda-meta\history'
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Igorek\AppData\Local\conda\conda\envs
                          C:\Users\Igorek\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Igorek\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py create --name firstenv untitled --debug`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 308, in install
        raise PackageNotFoundError('', error_message)
    PackageNotFoundError: Package not found: Conda could not find '
`

Or install package:
>conda install -c menpo opencv3=3.2.0 --debug
```
(C:\ProgramData\Anaconda2) c:\Users\Igorek>conda install -c menpo opencv3=3.2.0 --debug
DEBUG conda.core.index:fetch_index(105): channel_urls=OrderedDict([(u'https://conda.anaconda.org/menpo/win-64', (u'menpo', 0)), (u'https://conda.anaconda.org/menpo/noarch', (u'menpo', 0)), (u'https://repo.continuum.io/pkgs/free/win-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/free/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/r/win-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/r/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/pro/win-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/pro/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/msys2/win-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/msys2/noarch', (u'defaults', 1))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://conda.anaconda.org/menpo/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\8ea7d46e.json. Timeout in 41287 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\8ea7d46e.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://conda.anaconda.org/menpo/noarch at C:\ProgramData\Anaconda2\pkgs\cache\c8547dad.json. Timeout in 41287 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\c8547dad.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/free/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\2116b818.json. Timeout in 15 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\2116b818.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/free/noarch at C:\ProgramData\Anaconda2\pkgs\cache\9ca791dd.json. Timeout in 15 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\9ca791dd.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/r/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\bf91db7e.json. Timeout in 15 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\bf91db7e.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/r/noarch at C:\ProgramData\Anaconda2\pkgs\cache\716b88c0.json. Timeout in 15 sec
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/pro/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\709bdc73.json. Timeout in 15 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\709bdc73.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/pro/noarch at C:\ProgramData\Anaconda2\pkgs\cache\08159f17.json. Timeout in 15 sec
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/msys2/win-64 at C:\ProgramData\Anaconda2\pkgs\cache\9767c1d0.json. Timeout in 15 sec
DEBUG conda.core.repodata:read_pickled_repodata(327): found pickle file C:\ProgramData\Anaconda2\pkgs\cache\9767c1d0.q
.DEBUG conda.core.repodata:fetch_repodata(432): Using cached repodata for https://repo.continuum.io/pkgs/msys2/noarch at C:\ProgramData\Anaconda2\pkgs\cache\814cd719.json. Timeout in 15 sec
.
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Anaconda2' using path 'C:\ProgramData\Anaconda2\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Anaconda2' using path 'C:\ProgramData\Anaconda2\conda-meta\history'
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Igorek\AppData\Local\conda\conda\envs
                          C:\Users\Igorek\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Igorek\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/menpo/win-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393



`$ C:\ProgramData\Anaconda2\Scripts\conda-script.py install -c menpo opencv3=3.2.0 --debug`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 308, in install
        raise PackageNotFoundError('', error_message)
    PackageNotFoundError: Package not found: Conda could not find '
```

**Comment by rodji** [comment]
```
(C:\ProgramData\Anaconda2) c:\Users\Igorek>conda info -a
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Igorek\AppData\Local\conda\conda\envs
                          C:\Users\Igorek\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Igorek\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.14393

# conda environments:
#
root                  *  C:\ProgramData\Anaconda2

sys.version: 2.7.13 |Anaconda 4.3.1 (64-bit)| (defaul...
sys.prefix: C:\ProgramData\Anaconda2
sys.executable: C:\ProgramData\Anaconda2\python.exe
conda location: C:\ProgramData\Anaconda2\lib\site-packages\conda
conda-build: None
conda-env: C:\ProgramData\Anaconda2\Scripts\conda-env.exe
conda-server: C:\ProgramData\Anaconda2\Scripts\conda-server.exe
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: C:\ProgramData\Anaconda2
CONDA_ENVS_PATH: <not set>
PATH: C:\ProgramData\Anaconda2\Library\bin;C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\bin;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\Library\bin;C:\ProgramData\Anaconda2\Scripts;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;c:\Program Files (x86)\Intel\iCLS Client\;c:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Skype\Phone\;C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Scripts;C:\ProgramData\Anaconda2\Library\bin;C:\Users\Igorek\AppData\Local\Microsoft\WindowsApps
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    C:\ProgramData\Anaconda2\licenses
    C:\Users\Igorek\.continuum
    C:\Users\Igorek\AppData\Roaming\Continuum
License files (license*.txt):
Package/feature end dates:

(C:\ProgramData\Anaconda2) c:\Users\Igorek>conda info -a
```

**Comment by rodji** [comment]
Just started
>conda update conda
and I got working version!
conda 4.3.16
Please, could somebody update conda on downloads page to working version? Thanks!
