### ISSUE TITLE
conda install Twisted  error

### ISSUE THREAD

**Issue by alphatobeta** [conda/conda#5177]
Hi,
```
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.13.0
       root environment : C:\Program Files\Anaconda  (writable)
    default environment : C:\Program Files\Anaconda
       envs directories : C:\Program Files\Anaconda\envs
          package cache : C:\Program Files\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False



`$ C:\Program Files\Anaconda\Scripts\conda-script.py install Twisted`




    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 436, in wr
ap_socket
        cnx.do_handshake()
      File "C:\Program Files\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 1426, in do_handshake
        self._raise_ssl_error(self._ssl, result)
      File "C:\Program Files\Anaconda\lib\site-packages\OpenSSL\SSL.py", line 1166, in _raise_ssl_error
        raise SysCallError(errno, errorcode.get(errno))
    OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlop
en
        chunked=chunked)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make
_request
        self._validate_conn(conn)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _vali
date_conn
        conn.connect()
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
        ssl_context=context)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 324, in ssl_wrap_s
ocket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 443, in wr
ap_socket
        raise ssl.SSLError('bad handshake: %r' % e)
    ssl.SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Program Files\Anaconda\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 630, in urlop
en
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\conda\fetch.py", line 394, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(6.1, 60))
      File "C:\Program Files\Anaconda\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files\Anaconda\lib\site-packages\requests\adapters.py", line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: ("bad handshake: SysCallError(10054, 'WSAECONNRESET')",)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\fetch.py", line 405, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: ("bad handshake: SysCallError(10054, 'WSAECONNR
ESET')",): https://repo.continuum.io/pkgs/free/win-64/zope.interface-4.3.3-py36_0.tar.bz2


    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Connection error: ("bad handshake: S
ysCallError(10054, 'WSAECONNRESET')",): https://repo.continuum.io/pkgs/free/win-64/zope.interface-4.3.3-py36_0.tar.bz2
```

**Comment by kalefranz** [comment]
SSL bad handshake.  Probably an intermittent error.  If you keep having problems, temporarily dropping ssl verification could help.  Something like

    set CONDA_SSL_VERIFY=false
    conda update -c defaults conda cryptography pyopenssl requests
    set CONDA_SSL_VERIFY=
