### ISSUE TITLE
conda install anaconda Failure ... OSError: [Errno 13] Permission denied: '/home/ubuntu/PWPYTHON/include/python2.7/greenlet'

### ISSUE THREAD

**Issue by mandarjog** [conda/conda#519]
pip install conda
conda install anaconda

Extracting packages ...
[      COMPLETE      ] |##############################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ] |##############################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the                                                                         |  28%
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/ubuntu/PWPYTHON/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/ubuntu/PWPYTHON/local/lib/python2.7/site-packages/conda/cli/main.py", line 186, in main
    try:
  File "/home/ubuntu/PWPYTHON/local/lib/python2.7/site-packages/conda/cli/main_install.py", line 199, in execute
    list_packages(prefix, regex)
  File "/home/ubuntu/PWPYTHON/local/lib/python2.7/site-packages/conda/plan.py", line 378, in execute_actions

  File "/home/ubuntu/PWPYTHON/local/lib/python2.7/site-packages/conda/plan.py", line 363, in execute_plan
    elif cmd == RM_FETCHED:
  File "/home/ubuntu/PWPYTHON/local/lib/python2.7/site-packages/conda/plan.py", line 318, in link

  File "/home/ubuntu/PWPYTHON/local/lib/python2.7/site-packages/conda/install.py", line 371, in link
    try:
  File "/home/ubuntu/PWPYTHON/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/ubuntu/PWPYTHON/include/python2.7/greenlet'

============= info =============
[~] # conda info
Current conda install:

             platform : linux-64
        conda version : 2.3.1
     root environment : /home/ubuntu/PWPYTHON  (writable)
  default environment : /home/ubuntu/PWPYTHON
     envs directories : /home/ubuntu/PWPYTHON/envs
        package cache : /home/ubuntu/PWPYTHON/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : True

**Comment by asmeurer** [comment]
Let me know if you still have this issue. You probably need to adjust the permissions on anaconda. Avoid running conda with sudo.
