### ISSUE TITLE
Getting this error on Docker

### ISSUE THREAD

**Issue by vindows** [conda/conda#5208]
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

    Current conda install:

                   platform : linux-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : not installed
             python version : 3.6.0.final.0
           requests version : 2.12.4
           root environment : /home/appuser/Miniconda3  (writable)
        default environment : /home/appuser/Miniconda3
           envs directories : /home/appuser/Miniconda3/envs
                          /home/appuser/.conda/envs
              package cache : /home/appuser/Miniconda3/pkgs
                          /home/appuser/.conda/pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.12.4 CPython/3.6.0 Linux/4.4.0-59-generic debian/jessie/sid glibc/2.19
                    UID:GID : 1000:1000

`$ /home/appuser/Miniconda3/bin/conda-env create -f=pygdf/conda_environments/notebook_py35.yml`

    Traceback (most recent call last):
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 29, in install
        prefix=prefix)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/home/appuser/Miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 452, in fetch_repodata
        with open(cache_path, 'w') as fo:
    OSError: [Errno 28] No space left on device: '/home/appuser/Miniconda3/pkgs/cache/7384101c.json'

**Comment by tyler-thetyrant** [comment]
This isn't a conda issue. Your docker container is out of space. I suggest either changing docker setting or clearing docker cache.
