### ISSUE TITLE
Can't lunch anaconda from Windows command prompt

### ISSUE THREAD

**Issue by tonylaw7** [conda/conda#5225]
I'm getting this error right after installing anaconda (also tried miniconda) 

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\main.py", line 167
, in main
    return conda_exception_handler(_main, *args)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\exceptions.py", line 6
32, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\exceptions.py", line 5
59, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\exceptions.py", line 5
29, in get_info
    args.func(args, p)
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\main_info.py", lin
e 142, in execute
    from conda.api import get_index
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\api.py", line 1, in <m
odule>
    from .core.index import get_index
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\index.py", line 2
3, in <module>
    from .package_cache import PackageCache
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\package_cache.py"
, line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\path_actions.py",
 line 32, in <module>
    from ..gateways.download import download
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\gateways\download.py",
 line 15, in <module>
    from ..connection import CondaSession
  File "C:\ProgramData\Miniconda2\lib\site-packages\conda\connection.py", line 5
5, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1458, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1420, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Continuum Analytics, I
nc.| (default, Dec 19 2016, 13:29:36) [MSC v.1500 64 bit (AMD64)]'

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1665
