### ISSUE TITLE
TypeError when install pytorch

### ISSUE THREAD

**Issue by shrshore** [conda/conda#5233]
When I execute``conda install pytorch torchvision cuda80 -c soumith ``, I met the following error:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/shr/anaconda2  (writable)
    default environment : /home/shr/anaconda2/envs/torch
       envs directories : /home/shr/anaconda2/envs
          package cache : /home/shr/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/soumith/linux-64
                          https://conda.anaconda.org/soumith/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch




    Traceback (most recent call last):
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 111, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 466, in execute
        self._execute_action(action)
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 482, in _execute_action
        exceptions.append(CondaError(repr(e)))
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
        return '%s: %s\n' % (self.__class__.__name__, text_type(self))
      File "/home/shr/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 46, in __str__
        return text_type(self.message % self._kwargs)
    TypeError: not enough arguments for format string
```

**Comment by kalefranz** [comment]
Fixed.  `conda update conda`
