### ISSUE TITLE
install scikit-learn-0.18.1 on a non-networked machine

### ISSUE THREAD

**Issue by Dezzmanster** [conda/conda#5234]
Please, help me install this package.

Traceback below

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_fun
c
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in e
xecute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 203, in insta
ll
    explicit(args.packages, prefix, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\misc.py", line 140, in explicit
    execute_actions(actions, index=index, verbose=verbose)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 600, in execute_acti
ons
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in exec
ute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 59, in EXTRA
CT_CMD
    extract(arg)
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 852, in extract
    t.extractall(path=temp_path)
  File "C:\Anaconda2\lib\tarfile.py", line 2079, in extractall
    self.extract(tarinfo, path)
  File "C:\Anaconda2\lib\tarfile.py", line 2116, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File "C:\Anaconda2\lib\tarfile.py", line 2184, in _extract_member
    os.makedirs(upperdirs)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 150, in makedirs
    makedirs(head, mode)
  File "C:\Anaconda2\lib\os.py", line 157, in makedirs
    mkdir(name, mode)
WindowsError: [Error 5] : 'C:\\Anaconda2\\pkgs\\scikit-learn-0.18.1-np112py27_1.
tmp'

Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda2  (writable)
  default environment : C:\Anaconda2
     envs directories : C:\Anaconda2\envs
        package cache : C:\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

**Comment by kalefranz** [comment]
`conda update conda`
