### ISSUE TITLE
An unexpected error has occurred. 4.3.14 -> conda create --name snowflakes --offline

### ISSUE THREAD

**Issue by ruep** [conda/conda#5235]
PS H:\> conda create --name snowflakes --offline
Fetching package metadata ....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Users\pylover\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:\Users\pylover\AppData\Local\Continuum\Anaconda3
       envs directories : C:\Users\pylover\AppData\Local\Continuum\Anaconda3\envs
                          C:\Users\pylover\AppData\Local\conda\conda\envs
                          C:\Users\pylover\.conda\envs
          package cache : C:\Users\pylover\AppData\Local\Continuum\Anaconda3\pkgs
                          C:\Users\pylover\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/win-64  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/win-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
                          https://repo.continuum.io/pkgs/msys2/win-64  (offline)
                          https://repo.continuum.io/pkgs/msys2/noarch  (offline)
            config file : None
           offline mode : True
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/8.1 Windows/6.3.9600

`$ C:\Users\pylover\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py create --name snowflakes --offline`

    Traceback (most recent call last):
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in con
da_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main

        exit_code = args.func(args, p)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in
 execute
        install(args, parser, 'create')
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 222, in in
stall
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\index.py", line 92, in get_
index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\index.py", line 111, in fet
ch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in c
ollect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\repodata.py", line 463, in
_collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\repodata.py", line 463, in
<listcomp>
        for url, schan, pri in tasks]
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in
func
        res = f(*args, **kwargs)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\repodata.py", line 442, in
fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in
fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in ge
t
        return self.request('GET', url, **kwargs)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in re
quest
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in se
nd
        r = adapter.send(request, **kwargs)
      File "C:\Users\pylover\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\connection.py", line 70, in send

        raise RuntimeError(message)
    RuntimeError: EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2
    This command is using a remote connection in offline mode.

PS H:\>

**Comment by kalefranz** [comment]
This *should* be fixed in conda 4.3.18, which will be released in the next few days.  Will wait to close this issue until we can give you a chance to try 4.3.18 and verify that it's indeed fixed.

**Comment by kalefranz** [comment]
referencing #5146 and #5134

**Comment by kalefranz** [comment]
conda 4.3.18 is released to canary

    conda config --add channels conda-canary
    conda update conda
