### ISSUE TITLE
Conda Error "Packages.urllib3.exceptions

### ISSUE THREAD

**Issue by thienson30** [conda/conda#5240]
After I installed Anaconda2-4.3.1-Linux-x86_64.sh and rebooted,  it gave me some exception errors (se below) when I run conda.   If anybody know how to solve it, please let me know.

Traceback (most recent call last):
  File "/root/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 589, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 543, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/root/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 513, in get_info
    args.func(args, p)
  File "/root/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/root/anaconda2/lib/python2.7/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/root/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 9, in <module>
    from .repodata import collect_all_repodata
  File "/root/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: No module named packages.urllib3.exceptions
root@thienson30-Ubuntu64:~#

**Comment by kalefranz** [comment]
Your installation of Anaconda did not complete successfully apparently.  Since it's a new install, just delete it and try again.

**Comment by thienson30** [comment]
I ran python at terminal windows, and it showed "anaconda " in python environment.
