### ISSUE TITLE
new install of anaconda ,problem with urllib3

### ISSUE THREAD

**Issue by mike-brandt** [conda/conda#5243]
just installed anaconda 2.7 off of 
https://www.continuum.io/downloads
Python 2.7 version
64-Bit Installer (414M)
onto a AMD procceser win7 64 bit computer with a copy of pythone2.7.? already instaled

tried running python from the command window the python (non anaconda )installed

looked at path and had path of 

C:\Users\mike_2\Anaconda2;
C:\Users\mike_2\Anaconda2\Scripts;
C:\Users\mike_2\Anaconda2\Library\bin;
C:\Program Files (x86)\Mozilla Firefox;
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;
C:\Windows\System32\WindowsPowerShell\v1.0\;
C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;
C:\Program Files (x86)\QuickTime\QTSystem\;
C:\Program Files (x86)\Pico Technology\Pico Full\;
C:\Program Files (x86)\Pico Technology\PicoScope6\;
C:\OrCAD\OrCAD_16.5_Lite\tools\bin;
C:\OrCAD\OrCAD_16.5_Lite\tools\specctra\bin;
C:\OrCAD\OrCAD_16.5_Lite\tools\PSpice;
C:\OrCAD\OrCAD_16.5_Lite\tools\PSpice\Library;
C:\OrCAD\OrCAD_16.5_Lite\tools\Capture;
C:\OrCAD\OrCAD_16.5_Lite\tools\fet\bin;
C:\OrCAD\OrCAD_16.5_Lite\tools\pcb\bin;
C:\OrCAD\OrCAD_16.5_Lite\OpenAccess\bin\win32\opt;
C:\Program Files (x86)\Microchip\MPLAB C32 Suite\bin;
C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;
C:\Program Files\TortoiseGit\bin

shut down and rebooted computer

opend comand propt 

and typed in conda

the following is the result

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\mike_2>conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Users\mike_2\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\cli\main.py", line 164
, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\exceptions.py", line 5
89, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\exceptions.py", line 5
43, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\exceptions.py", line 5
13, in get_info
    args.func(args, p)
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\cli\main_info.py", lin
e 148, in execute
    from conda.api import get_index
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\api.py", line 1, in <m
odule>
    from .core.index import get_index
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\core\index.py", line 8
, in <module>
    from .package_cache import PackageCache
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\core\package_cache.py"
, line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\core\path_actions.py",
 line 31, in <module>
    from ..gateways.download import download
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\conda\gateways\download.py",
 line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\requests\__init__.py", line
60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "C:\Users\mike_2\Anaconda2\lib\site-packages\requests\packages\__init__.p
y", line 29, in <module>
    import urllib3
ImportError: No module named urllib3

C:\Users\mike_2>

any suggetions

**Comment by kalefranz** [comment]
When you say "opened command prompt," are you using the "Anaconda Prompt" icon?  Can you provide the output of `conda info`?

**Comment by kalefranz** [comment]
?
