### ISSUE TITLE
"During handling of the above exception, another exception occured"

### ISSUE THREAD

**Issue by songren90** [conda/conda#5270]
## Tried to install python 2.7 (I already have version 3.5 installed and working) when conda threw up exception after exception. 

I haven't moved any folders or messed with conda files. Can anyone offer a  solution to this seemingly horribly complex issue? Please? 

Below is what came up in cmd .

  xlwt:                               1.2.0-py27_0
    yaml:                               0.1.6-vc9_0        conda-forge [vc9]
    zlib:                               1.2.8-vc9_3        conda-forge [vc9]

Proceed ([y]/n)? y

menuinst-1.4.4 100% |###############################| Time: 0:00:07  14.36 kB/s
Fetching packages ...
vs2008_runtime 100% |###############################| Time: 0:00:10  98.86 kB/s
bzip2-1.0.6-vc 100% |###############################| Time: 0:00:05  21.83 kB/s
An unexpected error has occurred.                   | Time: 0:01:57 126.73 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Phil\.condarc
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py create -n py27 python=2.7 anaconda`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1149, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1335, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\Program Files\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1166, in _raise_ssl_error
        raise SysCallError(errno, errorcode.get(errno))
    OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 298, in _error_catcher
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 380, in read
        data = self._fp.read(amt)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Program Files\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Program Files\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 293, in recv_into
        return self.recv_into(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 282, in recv_into
        raise SocketError(str(e))
    OSError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 719, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 432, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 397, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 316, in _error_catcher
        raise ProtocolError('Connection broken: %r' % e, e)
    requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 722, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\icu-57.1-vc9_0.tar.bz2.part' for writing (('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Program Files\\Anaconda3\\pkgs\\icu-57.1-vc9_0.tar.bz2.part' for writing (('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRESET')",))).

C:\WINDOWS\system32>

**Comment by kalefranz** [comment]
Try this

    set CONDA_SSL_VERIFY=false
    conda update -c defaults conda requests cryptography pyopenssl
    set CONDA_SSL_VERIFY=

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```
