### ISSUE TITLE
i can't install mingw

### ISSUE THREAD

**Issue by leila000** [conda/conda#5299]
I had this issue below
-----------------------------------
WARNING (theano.configdefaults): g++ not detected ! Theano will be
 unable to execute optimized C-implementations (for both CPU and GPU) and
 will default to Python implementations. Performance will be severely
 degraded. To remove this warning, set Theano flags cxx to an empty string.
----------------------------------
and i did some search and someone said try to install mingw
but it didn't work well and i can't see why 
please help
thanks

=======================================================
(C:\Users\gy\Anaconda3) C:\Windows\system32>conda install mingw
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\gy\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mingw-4.7                  |                1        56.3 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0
    mingw:     4.7-1

The following packages will be UPDATED:

    conda:     4.2.9-py35_0  --> 4.3.17-py35_0
    pyopenssl: 16.0.0-py35_0 --> 16.2.0-py35_0
    requests:  2.11.1-py35_0 --> 2.13.0-py35_0

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.########           | ETA:  0:04:54  66.53 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\gy\Anaconda3  (writable)
    default environment : C:\Users\gy\Anaconda3
       envs directories : C:\Users\gy\Anaconda3\envs
          package cache : C:\Users\gy\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\gy\Anaconda3\Scripts\conda-script.py install mingw`

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "C:\Users\gy\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Users\gy\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Users\gy\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Users\gy\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Users\gy\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Users\gy\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "C:\Users\gy\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "C:\Users\gy\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Users\\gy\\Anaconda3\\pkgs\\mingw-4.7-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Users\gy\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Users\gy\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Users\\gy\\Anaconda3\\pkgs\\mingw-4.7-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by mingwandroid** [comment]
You do not need `mingw`, that is old and doesn't support 64-bit. `conda install theano` is enough. Try that from an `Anaconda Prompt` and try again from that same prompt.

Please also show the output of `conda list --show-channel-urls`.

**Comment by kalefranz** [comment]
This is an intermittent HTTP error.  `conda update conda` will help.

**Comment by mingwandroid** [comment]
@kalefranz Please move this to anaconda-issues, it's still open as I've requested feedback from @leila000.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1723

**Comment by leila000** [comment]
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.6                    py35_0    defaults
spyder                    3.0.0                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
tensorflow                1.0.1                     <pip>
Theano                    0.9.0                     <pip>
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.4.1                    py35_0    defaults
traitlets                 4.3.0                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.11                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
win_unicode_console       0.5                      py35_0    defaults
wrapt                     1.10.6                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.3                    py35_0    defaults
xlwings                   0.10.0                   py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults

==========================
thnks!
this is  output of  conda list --show-channel-urls .

**Comment by mingwandroid** [comment]
Please update `conda`. From the `Anaconda Prompt`, type `conda update conda`.

Also from the same prompt, please show the output of `echo %PATH%` and also of `dir C:\Users\gy\Anaconda3\Library\mingw-w64\bin`, and then try to run your code from that same prompt (and not from a raw cmd.exe prompt).

**Comment by leila000** [comment]
I did update conda
============================================
(C:\Users\gy\Anaconda3) C:\Windows\system32>conda update conda
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\gy\Anaconda3:
#
conda                     4.3.17                   py35_0
=============================================
and this is output of echo%PATH%
==============================================
(C:\Users\gy\Anaconda3) C:\Windows\system32>echo %PATH%
C:\Users\gy\Anaconda3;C:\Users\gy\Anaconda3\Library\mingw-w64\bin;C:\Users\gy\Anaconda3\Library\usr\bin;C:\Users\gy\Anaconda3\Library\bin;C:\Users\gy\Anaconda3\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\opencv\build\x64\vc12\bin;C:\Users\gy\Anaconda3;C:\Users\gy\Anaconda3\Scripts;C:\Users\gy\Anaconda3\Library\bin;C:\Users\gy\AppData\Local\Microsoft\WindowsApps
=================================================
and this is   dir C:\Users\gy\Anaconda3\Library\mingw-w64\bin 
===============================================
C:\Users\gy\Anaconda3\Library\mingw-w64\bin Directory

2017-05-13  오후 02:03    <DIR>          .
2017-05-13  오후 02:03    <DIR>          ..
2016-03-31  오후 02:49         2,092,240 addr2line.exe
2016-03-31  오후 02:49         2,118,511 ar.exe
2016-03-31  오후 02:49         2,873,342 as.exe
2016-02-29  오후 04:49            48,732 bunzip2.exe
2016-02-29  오후 04:49            48,732 bzcat.exe
2016-02-29  오후 04:49             2,128 bzcmp
2016-02-29  오후 04:49             2,128 bzdiff
2016-02-29  오후 04:49             3,642 bzegrep
2016-02-29  오후 04:49             3,642 bzfgrep
2016-02-29  오후 04:49             3,642 bzgrep
2016-02-29  오후 04:49            48,732 bzip2.exe
2016-02-29  오후 04:49            26,250 bzip2recover.exe
2016-02-29  오후 04:49             1,297 bzless
2016-02-29  오후 04:49             1,297 bzmore
2016-03-31  오전 03:05         1,893,442 c++.exe
2016-03-31  오후 02:49         2,086,488 c++filt.exe
2016-03-31  오전 03:05         1,890,882 cc.exe
2016-03-31  오전 03:05         1,891,906 cpp.exe
2016-03-31  오후 02:49         2,150,581 dlltool.exe
2016-03-31  오후 02:49         1,171,161 dllwrap.exe
2016-03-31  오후 02:49         4,186,344 dwp.exe
2016-03-31  오후 02:49         1,158,179 elfedit.exe
2016-03-31  오전 03:05         1,893,442 g++.exe
2016-03-31  오전 03:05            68,440 gcc-ar.exe
2016-03-31  오전 03:05            68,440 gcc-nm.exe
2016-03-31  오전 03:05            68,440 gcc-ranlib.exe
2016-03-31  오전 03:05         1,890,882 gcc.exe
2016-03-31  오전 03:05         1,467,639 gcov-tool.exe
2016-03-31  오전 03:05         1,501,437 gcov.exe
2015-11-23  오후 06:21            86,032 gendef.exe
2015-11-23  오후 06:21           101,963 genidl.exe
2015-11-23  오후 06:21            76,011 genlib.exe
2015-11-23  오후 06:21            59,277 genpeimg.exe
2016-03-31  오전 03:06         1,892,930 gfortran.exe
2016-03-31  오전 03:07         4,354,446 gnat.exe
2016-03-31  오전 03:07         2,668,186 gnatbind.exe
2016-03-31  오전 03:07         2,295,694 gnatchop.exe
2016-03-31  오전 03:07         4,522,382 gnatclean.exe
2016-03-31  오전 03:07         2,234,716 gnatdll.exe
2016-03-31  오전 03:07         2,272,092 gnatfind.exe
2016-03-31  오전 03:07         1,938,953 gnatkr.exe
2016-03-31  오전 03:07         2,081,136 gnatlink.exe
2016-03-31  오전 03:07         3,910,030 gnatls.exe
2016-03-31  오전 03:07         4,844,718 gnatmake.exe
2016-03-31  오전 03:07         3,986,318 gnatname.exe
2016-03-31  오전 03:07         2,971,996 gnatprep.exe
2016-03-31  오전 03:07         2,271,068 gnatxref.exe
2016-03-31  오후 02:49         2,158,960 gprof.exe
2016-03-31  오후 02:49         2,510,316 ld.bfd.exe
2016-03-31  오후 02:49         2,510,316 ld.exe
2016-03-31  오후 02:49         5,831,912 ld.gold.exe
2016-03-31  오전 03:06            38,880 libatomic-1.dll
2016-02-29  오후 04:49            73,888 libbz2-1.dll
2015-06-29  오후 08:25            43,378 libcharset-1.dll
2016-03-31  오전 03:06            83,230 libgcc_s_seh-1.dll
2016-03-31  오전 03:06         1,289,179 libgfortran-3.dll
2015-11-02  오후 03:43           514,299 libgmp-10.dll
2015-11-02  오후 03:43            33,488 libgmpxx-4.dll
2016-03-31  오전 03:07           228,990 libgnarl-5.dll
2016-03-31  오전 03:07         3,030,507 libgnat-5.dll
2016-03-31  오전 03:06           115,476 libgomp-1.dll
2016-03-31  오전 03:06            19,948 libgomp-plugin-host_nonshm-1.dll
2015-06-29  오후 08:25         1,050,543 libiconv-2.dll
2015-08-18  오전 01:19            84,772 libminizip-1.dll
2016-03-31  오전 03:08           130,636 libobjc-4.dll
2016-03-31  오전 03:06           334,810 libquadmath-0.dll
2016-03-31  오전 03:06            21,756 libssp-0.dll
2016-03-31  오전 03:06         1,428,650 libstdc++-6.dll
2016-03-31  오전 03:06            18,193 libvtv-0.dll
2016-03-31  오전 03:06            18,193 libvtv_stubs-0.dll
2016-03-26  오전 07:38            56,978 libwinpthread-1.dll
2015-07-01  오후 10:35           228,355 mingw32-make.exe
2015-08-18  오전 01:19            82,196 miniunzip.exe
2015-08-18  오전 01:19            82,861 minizip.exe
2016-03-31  오후 02:49         2,102,512 nm.exe
2016-03-31  오후 02:49         2,262,378 objcopy.exe
2016-03-31  오후 02:49         3,204,456 objdump.exe
2016-03-10  오후 03:03           671,915 pkg-config.exe
2016-03-31  오후 02:49         2,118,511 ranlib.exe
2016-03-31  오후 02:49         1,617,967 readelf.exe
2016-03-31  오후 02:49         2,092,840 size.exe
2016-03-31  오후 02:49         2,092,334 strings.exe
2016-03-31  오후 02:49         2,262,378 strip.exe
2015-11-23  오후 06:21           458,835 widl.exe
2016-03-31  오후 02:49         2,114,808 windmc.exe
2016-03-31  오후 02:49         2,203,925 windres.exe
2016-03-31  오전 03:05         1,893,442 x86_64-w64-mingw32-c++.exe
2016-03-31  오전 03:05         1,893,442 x86_64-w64-mingw32-g++.exe
2016-03-31  오전 03:05         1,890,882 x86_64-w64-mingw32-gcc-5.3.0.exe
2016-03-31  오전 03:05            68,440 x86_64-w64-mingw32-gcc-ar.exe
2016-03-31  오전 03:05            68,440 x86_64-w64-mingw32-gcc-nm.exe
2016-03-31  오전 03:05            68,440 x86_64-w64-mingw32-gcc-ranlib.exe
2016-03-31  오전 03:05         1,890,882 x86_64-w64-mingw32-gcc.exe
2016-03-31  오전 03:06         1,892,930 x86_64-w64-mingw32-gfortran.exe
2016-03-10  오후 03:03           671,915 x86_64-w64-mingw32-pkg-config.exe
2015-08-18  오전 01:19            90,250 zlib1.dll
              96개 file         128,882,598 byte

 C:\ directory

2017-03-13  오후 03:30    <DIR>          3DP
2017-03-14  오전 10:48    <DIR>          HP_LaserJet_Pro_MFP_M225-M226
2017-05-01  오후 03:25    <DIR>          Intel
2015-06-04  오전 03:45    <DIR>          opencv
2017-03-30  오후 01:35    <DIR>          OpenCV-3.0.0-android-sdk-1
2017-03-30  오후 12:20       170,646,391 OpenCV-3.0.0-android-sdk-1.zip
2017-03-14  오후 01:08       282,110,246 opencv-3.0.0.exe
2017-05-01  오후 03:50    <DIR>          Program Files
2017-05-12  오후 04:46    <DIR>          Program Files (x86)
2017-05-13  오후 03:34    <DIR>          Recovery
2017-03-13  오후 05:15     1,003,026,432 SW_DVD5_Office_Professional_Plus_2016_64Bit_Korean_MLF_X20-42445.ISO
2017-05-13  오후 03:01    <DIR>          Temp
2017-04-24  오후 04:16    <DIR>          Users
2017-05-13  오후 03:35    <DIR>          Windows
               3개 file       1,455,783,069 byte
              11개 directory  141,548,589,056 byte left
