### ISSUE TITLE
Solving with features still not right

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5301]
Easy test case courtesy of @mingwandroid.  In the current 4.3.x (4.3.18) on Windows

```
kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test svn
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\kfranz\AppData\Local\conda\conda\envs\svn:

The following NEW packages will be INSTALLED:

    apr:            1.5.2-vc14_1             [vc14]
    openssl:        1.0.2k-vc14_0            [vc14]
    pip:            9.0.1-py36_1
    python:         3.6.1-2
    serf:           1.3.8-vc14_0             [vc14]
    setuptools:     27.2.0-py36_1
    sqlite:         3.13.0-vc14_1            [vc14]
    svn:            1.9.5-0       conda-test
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py36_0
    zlib:           1.2.8-vc14_3             [vc14]


kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test svn vc
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\kfranz\AppData\Local\conda\conda\envs\svn:

The following NEW packages will be INSTALLED:

    apr:            1.5.2-vc14_1             [vc14]
    openssl:        1.0.2k-vc14_0            [vc14]
    serf:           1.3.8-vc14_0             [vc14]
    sqlite:         3.13.0-vc14_1            [vc14]
    svn:            1.9.5-0       conda-test
    vc:             14-0
    vs2015_runtime: 14.0.25123-0
    zlib:           1.2.8-vc14_3             [vc14]

```

For the svn package in the `conda-test` channel, python is NOT a dependency, but the solver adds it to the environment anyway.  The solver does what's expected when `vc` is added to the list of specs we're feeding it.

CC @mcg1969

**Comment by kalefranz** [comment]
May be related to #4878.  Not sure yet.  But the #4878 PR actually didn't fix this (as implemented didn't actually end up adding `vc` to the specs given to the solver).

**Comment by kalefranz** [comment]
Related is this:

```
kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test svn=1.9.5
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - svn 1.9.5*
Use "conda info <package>" to see the dependencies for each package.


kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test svn=1.9.5 vc
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\kfranz\AppData\Local\conda\conda\envs\svn:

The following NEW packages will be INSTALLED:

    apr:            1.5.2-vc14_1             [vc14]
    openssl:        1.0.2k-vc14_0            [vc14]
    serf:           1.3.8-vc14_0             [vc14]
    sqlite:         3.13.0-vc14_1            [vc14]
    svn:            1.9.5-0       conda-test
    vc:             14-0
    vs2015_runtime: 14.0.25123-0
    zlib:           1.2.8-vc14_3             [vc14]

```

**Comment by kalefranz** [comment]
Relevant debug lines for the two cases

```
kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test -vvv svn=1.9.5

...

DEBUG conda.resolve:install_specs(790): Checking satisfiability of current install
DEBUG conda.resolve:bad_installed(740): Checking if the current environment is consistent
DEBUG conda.resolve:install_specs(790): Checking satisfiability of current install
DEBUG conda.resolve:bad_installed(740): Checking if the current environment is consistent
Solving package specifications: DEBUG conda.resolve:solve(845): Solving for [MatchSpec('svn 1.9.5*')]
DEBUG conda.resolve:get_reduced_index(374): Retrieving packages for: [MatchSpec('svn 1.9.5*')]
DEBUG conda.resolve:filter_group(399): svn: pruned from 7 -> 1

    Traceback (most recent call last):
      File "C:\msys64\home\kfranz\continuum\conda\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\msys64\home\kfranz\continuum\conda\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\msys64\home\kfranz\continuum\conda\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\msys64\home\kfranz\continuum\conda\conda\cli\install.py", line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\msys64\home\kfranz\continuum\conda\conda\plan.py", line 489, in install_actions_list
        for specs_by_prefix in required_solves]
      File "C:\msys64\home\kfranz\continuum\conda\conda\plan.py", line 489, in <listcomp>
        for specs_by_prefix in required_solves]
      File "C:\msys64\home\kfranz\continuum\conda\conda\plan.py", line 634, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "C:\msys64\home\kfranz\continuum\conda\conda\resolve.py", line 811, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "C:\msys64\home\kfranz\continuum\conda\conda\resolve.py", line 865, in solve
        self.find_conflicts(specs)
      File "C:\msys64\home\kfranz\continuum\conda\conda\resolve.py", line 371, in find_conflicts
        raise UnsatisfiableError(bad_deps)
    conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
      - svn 1.9.5*
    Use "conda info <package>" to see the dependencies for each package.
```

```
kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test -vvv svn=1.9.5 vc

...

Solving package specifications: DEBUG conda.resolve:solve(845): Solving for [MatchSpec('svn 1.9.5*'), MatchSpec('vc')]
DEBUG conda.resolve:get_reduced_index(374): Retrieving packages for: [MatchSpec('svn 1.9.5*'), MatchSpec('vc')]
DEBUG conda.resolve:filter_group(399): svn: pruned from 7 -> 1
.DEBUG conda.logic:minimize(485): Empty objective, trivial solution
DEBUG conda.resolve:solve(885): Package removal metric: 0
TRACE conda.logic:minimize(504): Beginning peak minimization
TRACE conda.logic:minimize(521): Initial range (0,0)
TRACE conda.logic:minimize(535): Bisection attempt: (0,0), (399+2) clauses
TRACE conda.logic:minimize(548): Bisection success, new range=(0,0)
DEBUG conda.logic:minimize(557): Final peak objective: 0
DEBUG conda.resolve:solve(890): Initial package version metric: 0
TRACE conda.logic:minimize(507): Beginning sum minimization
TRACE conda.logic:minimize(521): Initial range (0,1)
TRACE conda.logic:LinearBound_(378): Eliminating 3/3 terms for bound violation
TRACE conda.logic:minimize(535): Bisection attempt: (0,0), (401+3) clauses
TRACE conda.logic:minimize(539): Bisection failure, new range=(1,1)
TRACE conda.logic:minimize(535): Bisection attempt: (1,1), (401+9) clauses
TRACE conda.logic:minimize(548): Bisection success, new range=(1,1)
DEBUG conda.logic:minimize(557): Final sum objective: 1
DEBUG conda.logic:minimize(569): New peak objective: 1
DEBUG conda.resolve:solve(895): Track feature count: 1
TRACE conda.logic:minimize(507): Beginning sum minimization
TRACE conda.logic:minimize(521): Initial range (0,2)
TRACE conda.logic:LinearBound_(378): Eliminating 8/8 terms for bound violation
TRACE conda.logic:minimize(535): Bisection attempt: (0,0), (410+8) clauses
TRACE conda.logic:minimize(548): Bisection success, new range=(0,0)
DEBUG conda.logic:minimize(557): Final sum objective: 0
DEBUG conda.resolve:solve(901): Package feature count: 5
DEBUG conda.logic:minimize(485): Empty objective, trivial solution
DEBUG conda.resolve:solve(905): Initial package build metric: 0
DEBUG conda.logic:minimize(485): Empty objective, trivial solution
DEBUG conda.resolve:solve(910): Dependency update count: 0
TRACE conda.logic:minimize(504): Beginning peak minimization
TRACE conda.logic:minimize(521): Initial range (0,7)
TRACE conda.logic:minimize(535): Bisection attempt: (0,0), (418+38) clauses
TRACE conda.logic:minimize(548): Bisection success, new range=(0,0)
DEBUG conda.logic:minimize(557): Final peak objective: 0
TRACE conda.logic:minimize(504): Beginning peak minimization
TRACE conda.logic:minimize(521): Initial range (0,1)
TRACE conda.logic:minimize(535): Bisection attempt: (0,0), (456+16) clauses
TRACE conda.logic:minimize(548): Bisection success, new range=(0,0)
DEBUG conda.logic:minimize(557): Final peak objective: 0
DEBUG conda.resolve:solve(916): Additional package version/build metrics: 0/0
TRACE conda.logic:minimize(507): Beginning sum minimization
TRACE conda.logic:minimize(521): Initial range (0,6)
TRACE conda.logic:minimize(535): Bisection attempt: (0,5), (472+40) clauses
TRACE conda.logic:minimize(539): Bisection failure, new range=(6,6)
TRACE conda.logic:minimize(535): Bisection attempt: (6,6), (472+48) clauses
TRACE conda.logic:minimize(548): Bisection success, new range=(6,6)
DEBUG conda.logic:minimize(557): Final sum objective: 6
DEBUG conda.logic:minimize(569): New peak objective: 1
DEBUG conda.resolve:solve(921): Weak dependency count: 6
DEBUG conda.resolve:solve(926): Looking for alternate solutions


Package plan for installation in environment C:\Users\kfranz\AppData\Local\conda\conda\envs\svn:

The following NEW packages will be INSTALLED:

    apr:            1.5.2-vc14_1             [vc14]
    openssl:        1.0.2k-vc14_0            [vc14]
    serf:           1.3.8-vc14_0             [vc14]
    sqlite:         3.13.0-vc14_1            [vc14]
    svn:            1.9.5-0       conda-test
    vc:             14-0
    vs2015_runtime: 14.0.25123-0
    zlib:           1.2.8-vc14_3             [vc14]
```

**Comment by kalefranz** [comment]
For reference, the 3.x solver was even worse

```
kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test svn
Fetching package metadata: ......
Solving package specifications: .Using Anaconda API: https://api.anaconda.org

Error: Unsatisfiable package specifications.
Generating hint:

Hint: 'svn' has unsatisfiable dependencies (see 'conda info svn')
[      COMPLETE      ]|##################################################| 100%


kfranz@DESKTOP-V5CQ93H MSYS ~/continuum/conda
$ python -m conda create -n svn --dry-run -c conda-test svn vc
Fetching package metadata: ......
Solving package specifications: .Using Anaconda API: https://api.anaconda.org

Error: Unsatisfiable package specifications.
Generating hint:

Hint: 'svn' has unsatisfiable dependencies (see 'conda info svn')

Note that the following features are enabled:
  - vc14
  - vc10
  - vc9

[      COMPLETE      ]|##################################################| 100%
```

**Comment by mcg1969** [comment]
I don't think this is a bug.

As you can see, `svn` depends on a number of packages that have the `vc14` feature. Therefore, at least one package needs to be pulled in that has the `vc14` track_feature. Python is one of them, and so is vc. The decision is somewhat arbitrary but I don't really think we have a good way to manage that.

**Comment by mcg1969** [comment]
The real problem is that `Python` should not have a `track_feature`. We have been telling everyone else that `track_feature` values belong in metapackages. Why aren't we following our own advice here?

**Comment by kalefranz** [comment]
Moved to https://github.com/ContinuumIO/anaconda/issues/867
