### ISSUE TITLE
Permission denied for path in my user folder.

### ISSUE THREAD

**Issue by rbavery** [conda/conda#5307]
`Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : 2.0.2
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\rbavery\AppData\Local\Continuum\Anaconda3  (writable)
    default environment : C:/Users/rbavery/py27
       envs directories : C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\envs
          package cache : C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Windows/7 Windows/6.1.7601

`$ C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py install gdal`

    Traceback (most recent call last):
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 6                         17, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 137                         , in _main
        exit_code = args.func(args, p)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py",                          line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line                          347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 837, in                          execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line                          258, in execute_instructions
        cmd(state, arg)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", line                          106, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 113,                          in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 130,                          in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\rbavery\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 86,                          in win_conda_bat_redirect
        with open(dst, "w") as f:
    IOError: [Errno 13] Permission denied: u'C:/Users/rbavery/py27\\Scripts\\conda'`

**Comment by kalefranz** [comment]
`conda update conda`
