### ISSUE TITLE
KeyError: 'google' in GCE installed

### ISSUE THREAD

**Issue by ralirah27** [conda/conda#5332]
Hi I'm Japaniese boy.
KeyError: 'google' occur in Google Compute Engine installed.
Could you tell me how to solve this?
Thanks.

`[my_username]@instance-1:~$ pip
Error processing line 2 of /home/[my_username]/miniconda3/lib/python3.6/site-packages/gapic_google_logging_v2-0.9.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/[my_username]/miniconda3/lib/python3.6/site-packages/gapic_google_pubsub_v1-0.9.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/[my_username]/miniconda3/lib/python3.6/site-packages/google_cloud-0.19.0-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/[my_username]/miniconda3/lib/python3.6/site-packages/googleapis_common_protos-1.5.2-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'

Remainder of file ignored
Error processing line 2 of /home/[my_username]/miniconda3/lib/python3.6/site-packages/grpc_google_logging_v2-0.9.3-py3.6-nspkg.pth:

  Traceback (most recent call last):
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
  KeyError: 'google'
Remainder of file ignored
Error processing line 2 of /home/[my_username]/miniconda3/lib/python3.6/site-packages/grpc_google_pubsub_v1-0.9.
3-py3.6-nspkg.pth:
  Traceback (most recent call last):
    File "/home/[my_username]/miniconda3/lib/python3.6/site.py", line 168, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  KeyError: 'google'
Remainder of file ignored
`

**Comment by kalefranz** [comment]
There's nothing in your stack trace to indicate a problem with conda, or even something conda could fix.  You thus have the wrong issue tracker.  There's insufficient information here for me to even point you in the right direction.

**Comment by kanecchi27** [comment]
I am sorry.I will check it a little more.
