### ISSUE TITLE
conda update not working

### ISSUE THREAD

**Issue by mcthulhu** [conda/conda#5337]
The traceback is below:

 conda update anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Users\Michael\Anaconda3  (writable)
    default environment : C:\Users\Michael\Anaconda3
       envs directories : C:\Users\Michael\Anaconda3\envs
                          C:\Users\Michael\Anaconda3\envs
          package cache : C:\Users\Michael\Anaconda3\pkgs
                          C:\Users\Michael\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Michael\.condarc
           offline mode : False

`$ C:\Users\Michael\Anaconda3\Scripts\conda-script.py update anaconda`

    Traceback (most recent call last):
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
        conn.connect()
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
        ssl_context=context)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 322, in ssl_wrap_socket
        context.load_cert_chain(certfile, keyfile)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 416, in load_cert_chain
        self._ctx.use_certificate_file(certfile)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 596, in use_certificate_file
        _raise_current_error()
      File "C:\Users\Michael\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]

**Comment by kalefranz** [comment]
Your very files are probably out of date. The following will drop security for a single update. 

    set CONDA_SSL_VERIFY=false
    conda update conda requests cryptography pyopenssl openssl
    set CONDA_SSL_VERIFY=

**Comment by mcthulhu** [comment]
Thanks, but no luck - the same problem seems to have occurred.

C:\Users\Michael>conda update conda requests cryptography pyopenssl openssl
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Users\Michael\Anaconda3  (writable)
    default environment : C:\Users\Michael\Anaconda3
       envs directories : C:\Users\Michael\Anaconda3\envs
                          C:\Users\Michael\Anaconda3\envs
          package cache : C:\Users\Michael\Anaconda3\pkgs
                          C:\Users\Michael\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Michael\.condarc
           offline mode : False



`$ C:\Users\Michael\Anaconda3\Scripts\conda-script.py update conda requests cryptography pyopenssl openssl`




    Traceback (most recent call last):
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
        conn.connect()
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
        ssl_context=context)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 322, in ssl_wrap_socket
        context.load_cert_chain(certfile, keyfile)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 416, in load_cert_chain
        self._ctx.use_certificate_file(certfile)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 596, in use_certificate_file
        _raise_current_error()
      File "C:\Users\Michael\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'FILE_CTRL', 'system lib'), ('SSL routines', 'SSL_CTX_use_certificate_file', 'system lib')]

**Comment by mcthulhu** [comment]
I did do set CONDA_SSL_VERIFY=false first.

**Comment by kalefranz** [comment]
> 'No such file or directory'

I'm guessing openssl is looking for your cert bundle in a location that doesn't exist.

Try this...

Download the file at https://github.com/certifi/python-certifi/blob/master/certifi/cacert.pem as save it somewhere on disk.  Say just at `c:\cacert.pem`.  Then do

    conda config --set ssl_verify c:\cacert.pem

See what happens with that...

**Comment by mcthulhu** [comment]
Done. This results in

C:\Users\Michael>conda update anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.13.0
       root environment : C:\Users\Michael\Anaconda3  (writable)
    default environment : C:\Users\Michael\Anaconda3
       envs directories : C:\Users\Michael\Anaconda3\envs
                          C:\Users\Michael\Anaconda3\envs
          package cache : C:\Users\Michael\Anaconda3\pkgs
                          C:\Users\Michael\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://conda.anaconda.org/conda-forge/win-32
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Michael\.condarc
           offline mode : False



`$ C:\Users\Michael\Anaconda3\Scripts\conda-script.py update anaconda`




    Traceback (most recent call last):
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 300, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Users\Michael\Anaconda3\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\conda\fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
        timeout=timeout
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 345, in _make_request
        self._validate_conn(conn)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 844, in _validate_conn
        conn.connect()
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 326, in connect
        ssl_context=context)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 411, in load_verify_locations
        self._ctx.load_verify_locations(cafile, capath)
      File "C:\Users\Michael\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 525, in load_verify_locations
        _raise_current_error()
      File "C:\Users\Michael\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 48, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: []

**Comment by mcthulhu** [comment]
The problem seems to be fixed now; thanks for your help. Miniconda didn't work, so I gave up and uninstalled and reinstalled Anaconda itself; it still didn't work, so I again tried unsetting ssl_verify, updating those packages, and resetting it per your suggestion, and conda update is sort of working now, at least intermittently, and I'm no longer getting that OpenSSL error.
