### ISSUE TITLE
IPython fails to start

### ISSUE THREAD

**Issue by rakeshgautam** [conda/conda#5376]
I installed Anaconda 4.3.1 for macOS 10.12.5 using Command Line Installer. Unfortunately 'ipython' or 'ipython notebook' or 'jupyter notebook' fails to start. It is giving some permission issue. The error message is given in the attached file. IPython also fails even if I try with sudo. 
[error.txt](https://github.com/conda/conda/files/1013384/error.txt)

**Comment by mingwandroid** [comment]
Did you use `sudo` during installation? Please do not do that. If you can try the following that would be helpful:

```
pushd /tmp
curl -SLO https://repo.continuum.io/archive/Anaconda3-4.3.1-MacOSX-x86_64.sh
bash Anaconda3-4.3.1-MacOSX-x86_64.sh -bfp /tmp/ac3
source /tmp/ac3/bin/activate
ipython
```

**Comment by rakeshgautam** [comment]
Thank you very mingwandroid!!
Could you please tell me how can I install anaconda without sudo in /opt/... directory?

**Comment by mingwandroid** [comment]
`sudo chown -R $USER:$(id -g -n) /opt`?

**Comment by rakeshgautam** [comment]
Thanks again for your clear explanation. Even with sudo I am getting the following error:

[rakesh ~]$ sudo jupyter notebook --allow-root
[I 14:20:15.485 NotebookApp] Serving notebooks from local directory: /Users/rakesh
[I 14:20:15.486 NotebookApp] 0 active kernels 
[I 14:20:15.486 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=1d1c4957b6f2117600b11e5bb580604388bc0aac88b337b5
[I 14:20:15.486 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 14:20:15.486 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=1d1c4957b6f2117600b11e5bb580604388bc0aac88b337b5
0:97: execution error: "http://localhost:8888/tree?token=2fb9cfc97577d9b3611c5be3aee36133eab9924796f11f97" doesn’t understand the “open location” message. (-1708)
...

BTW Intel-Python is installed in /opt/... directory and it works without any problem.

**Comment by mingwandroid** [comment]
After changing the permissions of the /opt folder, you should not need to use `sudo` again.

**Comment by rakeshgautam** [comment]
You are right mingwandroid, but why I am getting the error message?

**Comment by mingwandroid** [comment]
Which error?

My recommendation is that you start from the start. Remove all traces of `Anaconda` from `/opt` and re-install everything into your `$HOME` directory instead:

```
pushd /tmp
curl -SLO https://repo.continuum.io/archive/Anaconda3-4.3.1-MacOSX-x86_64.sh
bash Anaconda3-4.3.1-MacOSX-x86_64.sh -bfp ${HOME}/ac3
source ${HOME}/ac3/bin/activate
ipython
```

.. and if that works then good. Permissions are tricky things and best avoided by installing to `$HOME` and never using `sudo` (which is very dangerous anyway).

**Comment by rakeshgautam** [comment]
I mean the message after 
[rakesh ~]$ sudo jupyter notebook --allow-root

**Comment by mingwandroid** [comment]
I am not an expert in `jupyter` but it looks like some permissions problem I guess. Don't use `--allow-root`, `sudo` and you will not have permissions problems.

**Comment by rakeshgautam** [comment]
I freshly installed anaconda in my $HOME directory and still I am getting the same message error for ipython.

`[rakesh ~]$ jupyter notebook
[I 15:04:18.494 NotebookApp] Serving notebooks from local directory: /Users/rakesh
[I 15:04:18.494 NotebookApp] 0 active kernels 
[I 15:04:18.494 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=7f9e08576f931d3eb5b113bfc924db3a5373b8325c4ea946
[I 15:04:18.494 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 15:04:18.495 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=7f9e08576f931d3eb5b113bfc924db3a5373b8325c4ea946
0:97: execution error: "http://localhost:8888/tree?token=c37428fa586105d7b5578ff9136d4f96848ad164acbfa338" doesn’t understand the “open location” message. (-1708)
`

**Comment by mingwandroid** [comment]
https://github.com/jupyter/notebook/issues/2438

**Comment by mingwandroid** [comment]
The contents of `error.txt` attached to the first comment here is:

```
[rakesh ~]$ jupyter notebook
Traceback (most recent call last):
  File "/opt/continuum/condapython3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1290, in initialize
    super(NotebookApp, self).initialize(argv)
  File "<decorator-gen-6>", line 2, in initialize
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 243, in initialize
    self.migrate_config()
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/application.py", line 162, in migrate_config
    from .migrate import get_ipython_dir, migrate
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/jupyter_core/migrate.py", line 35, in <module>
    from IPython.paths import get_ipython_dir
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/embed.py", line 16, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 88, in <module>
    class TerminalInteractiveShell(InteractiveShell):
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 131, in TerminalInteractiveShell
    highlighting: \n %s""" % ', '.join(get_all_styles())
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/styles/__init__.py", line 79, in get_all_styles
    for name, _ in find_plugin_styles():
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/plugin.py", line 62, in find_plugin_styles
    for entrypoint in iter_entry_points(STYLE_ENTRY_POINT):
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/pygments/plugin.py", line 45, in iter_entry_points
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2985, in <module>
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2971, in _call_aside
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2998, in _initialize_master_working_set
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 651, in _build_master
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 644, in __init__
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 700, in add_entry
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1990, in find_on_path
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2399, in from_location
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2740, in _reload_version
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2364, in _version_from_file
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 2532, in _get_metadata
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1472, in get_metadata_lines
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1468, in get_metadata
  File "/opt/continuum/condapython3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1577, in _get
PermissionError: [Errno 13] Permission denied: '/opt/continuum/condapython3/lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO'
```

and indeed, checking that file we see:

```
ls -l lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO 
-rw-------  2 rdonnelly  wheel  768  4 May 21:41 lib/python3.6/site-packages/llvmlite-0.18.0-py3.6.egg-info/PKG-INFO
```

**Comment by kalefranz** [comment]
This does indeed look like a packaging problem.

Confirmed that the file at https://repo.continuum.io/pkgs/free/osx-64/llvmlite-0.18.0-py36_0.tar.bz2 has permissions that are too restrictive.

```
kfranz@0283:~/Downloads/llvmlite-0.18.0-py36_0/lib/python3.6/site-packages ❯ ls -al llvmlite-0.18.0-py3.6.egg-info/
total 32
drwxr-xr-x@ 6 kfranz  staff   204B May 19 09:16 ./
drwxr-xr-x@ 4 kfranz  staff   136B May 19 09:16 ../
-rw-------@ 1 kfranz  staff   768B May  4 15:41 PKG-INFO
-rw-------@ 1 kfranz  staff   1.7K May  4 15:41 SOURCES.txt
-rw-------@ 1 kfranz  staff     1B May  4 15:41 dependency_links.txt
-rw-------@ 1 kfranz  staff     9B May  4 15:41 top_level.txt
kfranz@0283:~/Downloads/llvmlite-0.18.0-py36_0/lib/python3.6/site-packages ❯ ls -al llvmlite
total 80
drwxr-xr-x@ 11 kfranz  staff   374B May 19 09:16 ./
drwxr-xr-x@  4 kfranz  staff   136B May 19 09:16 ../
-rw-------@  1 kfranz  staff   308B Dec 28 10:52 __init__.py
drwxr-xr-x@  6 kfranz  staff   204B May 19 09:16 __pycache__/
-rw-------@  1 kfranz  staff   418B May  4 15:41 _version.py
drwxr-xr-x@ 20 kfranz  staff   680B May 19 09:16 binding/
drwxr-xr-x@ 12 kfranz  staff   408B May 19 09:16 ir/
drwxr-xr-x@  6 kfranz  staff   204B May 19 09:16 llvmpy/
-rw-------@  1 kfranz  staff    27K Dec 28 10:52 six.py
drwxr-xr-x@ 10 kfranz  staff   340B May 19 09:16 tests/
-rw-------@  1 kfranz  staff   696B Dec 28 10:52 utils.py
```

There could be other affected files.

Is there a reason we aren't checking this with anaconda-verify/conda-verify (at least warning about it)?

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1745

**Comment by haccks** [comment]
Here is the solution:
1. Open jupyter configuration file. If you do not have then:  
`jupyter notebook --generate-config`
`cd ~./jupyter`
2. Now use any editor to open `jupyter_notebook_config.py` file  
`nano jupyter_notebook_config.py`
3. Search for the line `c.NotebookApp.browser` and remove `#` and then add your browser chrome/safari
`c.NotebookApp.browser = u'chrome'`

Done! Now launch the notebook using `ipython notebook`.

**Comment by suwei1979** [comment]
newly to anaconda, and thanks for kalefranz's keep asking abount this problem, and thanks for haccks paste the solution. it works, seems just a configuration problem hoho :)

**Comment by suwei1979** [comment]
but i got a 404: Not Found error in chrome~

**Comment by dankhan-adl** [comment]
@suwei1979 ; Did you followed all the steps mentioned above?
