### ISSUE TITLE
Unable to install Scrappy on Conda

### ISSUE THREAD

**Issue by mesunilgaikwad** [conda/conda#5377]
Unable to install Scrappy on Conda.

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

 Traceback (most recent call last):
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\fetch.py", line 293, in fetch_index
        for url in urls]
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "C:\Users\sunil_gaikwad\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\fetch.py", line 187, in fetch_repodata
        raise CondaRuntimeError(msg)
    CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/repodata.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000079BAA90>, 'Connection to conda.anaconda.org timed out. (connect timeout=3.05)')): https://conda.anaconda.org/conda-forge/win-64/

**Comment by kalefranz** [comment]
Intermittent HTTP error.  Conda 4.3 has longer timeouts and better error messages.  `conda update conda`
