### ISSUE TITLE
import error for vtk

### ISSUE THREAD

**Issue by lcebaman** [conda/conda#5409]
`conda install vtk` works beautifully , however we get:
```
>>> import vtk
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z01/z01/lcebaman/.conda/envs/e1/lib/python2.7/site-packages/vtk/__init__.py", line 58, in <module>
    from vtkRenderingFreeType import *
  File "/home/z01/z01/lcebaman/.conda/envs/e1/lib/python2.7/site-packages/vtk/vtkRenderingFreeType.py", line 1, in <module>
    from vtkRenderingFreeTypePython import *
ImportError: /usr/lib64/libxcb-xlib.so.0: undefined symbol: _xcb_unlock_io
```

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#1757
