### ISSUE TITLE
Conda Error after installing Spyder in a new environment

### ISSUE THREAD

**Issue by dariojavo91** [conda/conda#5418]
I've installed a new environment succesfully with conda, but it doesnt work with Spyder so i install spyder in the new environment with conda, and then conda stop working and i get this messange:

Traceback (most recent call last):
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\main.py", line 107, in _main
    p, sub_parsers = generate_parser()
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\JAVIER\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    return conda_exception_handler(_main)
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\exceptions.py", line 402, in get_info
    from conda.cli import conda_argparse
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "C:\Users\JAVIER\Anaconda3\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ImportError: DLL load failed: The specified module could not be found.

What was my mistake?
How can i fixwd it?

**Comment by kalefranz** [comment]
You were using a very old version of conda, and your installation got corrupted somehow.  Easiest solution is to just reinstall.  Make sure you're using conda >4.3.
