### ISSUE TITLE
OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by eric-jm-lang** [conda/conda#5424]
I have had an error while trying to update my anaconda:
Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /projects/t2/el14718/SOFTWARE/anaconda2  (writable)
    default environment : /projects/t2/el14718/SOFTWARE/anaconda2
       envs directories : /projects/t2/el14718/SOFTWARE/anaconda2/envs
          package cache : /projects/t2/el14718/SOFTWARE/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/salilab/linux-64
                          https://conda.anaconda.org/salilab/noarch
                          https://conda.anaconda.org/ambermd/linux-64
                          https://conda.anaconda.org/ambermd/noarch
                          https://conda.anaconda.org/MDAnalysis/linux-64
                          https://conda.anaconda.org/MDAnalysis/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/omnia/linux-64
                          https://conda.anaconda.org/omnia/noarch
                          https://conda.anaconda.org/acellera/linux-64
                          https://conda.anaconda.org/acellera/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/el14718/.condarc
           offline mode : False

`$ /projects/t2/el14718/SOFTWARE/anaconda2/bin/conda update --all`

    Traceback (most recent call last):
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/install.py", line 812, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "/projects/t2/el14718/SOFTWARE/anaconda2/lib/python2.7/site-packages/conda/common/disk.py", line 158, in exp_backoff_fn
        return fn(*args, **kwargs)
    OSError: [Errno 39] Directory not empty

**Comment by kalefranz** [comment]
conda update -c defaults conda

4.2.13 is old.
