### ISSUE TITLE
conda commands failing after OSX update

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#5439]
_From @andyxerxes on May 26, 2017 14:26_

After a recent update to OSX 10.12.5, I had two problems. The first was Jupyter notebook not launching properly, but this got (temporarily) solved, as described here https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/2ixBaRD90Jk

However, I also have an issue with conda commands. Doing anything like "conda info" or "conda update conda"  etc gives the following return:

~> conda info
Traceback (most recent call last):
  File "/Users/axl/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 161, in main
    from ..exceptions import conda_exception_handler
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 11, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/__init__.py", line 27, in <module>
    from .logz import getLogger, NullHandler
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/logz.py", line 8, in <module>
    from .compat import text_type
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 7, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/axl/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/axl/anaconda/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/Users/axl/anaconda/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

I tried some fixes as suggested by Ian Stokes Rees at the above posting, but they all did the same thing.

_Copied from original issue: ContinuumIO/anaconda-issues#1769_

**Comment by kalefranz** [comment]
The python in your root environment got borked somehow.  The easiest solution would be to download the latest version of miniconda, and then install it overtop.

    curl https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -o ~/miniconda2.sh
    bash ~/miniconda2.sh -bfp /Users/axl/anaconda

**Comment by andyxerxes** [comment]
For completeness, that solution did not work. Same error after re-installation. However, a warning message during the installlation - my PYTHONPATH was linking to a different installation of python, as part of the larger ESO Scisoft collection,  set by a script which Scisoft had added to my bash_profile. I commented this out and then everything worked fine...

**Comment by agallenne** [comment]
I have the same problem, impossible to only do 'conda info'. I tried to reinstall all anaconda but it did not work.
Here is the error:

Traceback (most recent call last):
  File "/Users/agallenn/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/agallenn/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 178, in main
    from ..exceptions import conda_exception_handler
  File "/Users/agallenn/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 11, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/agallenn/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 249, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/agallenn/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 7, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/agallenn/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 7, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/agallenn/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/agallenn/anaconda2/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/Users/agallenn/anaconda2/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

**Comment by fmontene** [comment]
Hi, is this solved? I have the same issue, but interestingly only when I use my personal MacOSX user account. If I do it with sudo permissions, it works:

~> conda list
Traceback (most recent call last):
  File "/Users/fmm/anaconda2/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/fmm/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 181, in main
    from ..exceptions import conda_exception_handler
  File "/Users/fmm/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 11, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/fmm/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 249, in <module>
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/fmm/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 7, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/fmm/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 7, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/fmm/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/fmm/anaconda2/lib/python2.7/ctypes/__init__.py", line 375, in __getattr__
    func = self.__getitem__(name)
  File "/Users/fmm/anaconda2/lib/python2.7/ctypes/__init__.py", line 380, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

~> sudo conda list
# packages in environment at /Users/fmm/anaconda2:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py27h172cb35_0  
alabaster                 0.7.10           py27h9dd7d6e_0  
anaconda                  5.0.0            py27h58f0b96_0  
[...] etc..

**Comment by mingwandroid** [comment]
This is likely related to having either `DYLD_FALLBACK_LIBRARY_PATH` or `PYTHONPATH` or `PYTHONHOME` set. Check in `~/.bash_profile`, `~/.bashrc` and any `homebrew` configuration files.

https://stackoverflow.com/a/26312792/3257826

**Comment by shepherdpp** [comment]
I had exactly the same problem as at last the AttributeError was thrown out:
...
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found

Finally, the problem was solved by re-installing anaconda in a different (but default) folder: ~/opt/anaconda3
and I realized that my conda command lines are back, and then I copied the previous env folder from the original anaconda folder (~/anaconda/envs/) into the new folder (~/opt/anaconda/envs/) and everything seemed to be normal again, my previous environments are also back.
And then I removed the original ~/anaconda folder

**Comment by mingmingding2** [comment]
FYI.
I had the same issue as above. But I source my zsh again, it works out !!!.
$ sudo conda list
Traceback (most recent call last):
  File "/Users/mingmingding/miniconda2/condabin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 149, in main
    from ..exceptions import conda_exception_handler
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 19, in <module>
    from ._vendor.auxlib.entity import EntityEncoder
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 253, in <module>
# If you come from bash you might have to change your $PATH.
    from .collection import AttrDict, frozendict, make_immutable
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/collection.py", line 10, in <module>
    from .compat import isiterable, iteritems, odict, text_type
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/compat.py", line 10, in <module>
    from ._vendor.five import WhateverIO as StringIO, with_metaclass
  File "/Users/mingmingding/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/_vendor/five.py", line 80, in <module>
    absolute_to_nanoseconds = CoreServices.AbsoluteToNanoseconds
  File "/Users/mingmingding/miniconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/mingmingding/miniconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(RTLD_DEFAULT, AbsoluteToNanoseconds): symbol not found****


$ vim ~/.zshrc

# mingmingding @ MINGMINDING-MB0 in ~/anaconda2/bin on git:master x [20:52:37]
$ source  ~/.zshrc
(base) ➜  bin git:(master) ✗ pwd
/Users/mingmingding/anaconda2/bin
(base) ➜  bin git:(master) ✗ sudo conda list
# packages in environment at /Users/mingmingding/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py38_0
alabaster                 0.7.12                     py_0
anaconda                  2020.07                  py38_0
anaconda-client           1.7.2                    py38_0
anaconda-navigator        1.9.12                   py38_0
anaconda-project          0.8.4                      py_0
applaunchservices         0.2.1                      py_0
appnope                   0.1.0                 py38_1001
appscript                 1.1.1            py38haf1e3a3_0
argh                      0.26.2                   py38_0
asn1crypto                1.3.0                    py38_1
astroid                   2.4.2                    py38_0
astropy                   4.0.1.post1      py38h01d97ff_1
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.5.3                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.shutil_get_terminal_size 1.0.0                    py38_2
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
beautifulsoup4            4.9.1                    py38_0
bitarray                  1.4.0            py38haf1e3a3_0
bkcharts                  0.2                      py38_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
blosc                     1.19.0               hab81aa3_0
bokeh                     2.1.1                    py38_0
boto                      2.49.0                   py38_0
bottleneck                1.3.2            py38hf1fa96c_1
brotlipy                  0.7.0           py38haf1e3a3_1000
bzip2                     1.0.8                h1de35cc_0
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py38_0
cffi                      1.14.0           py38hc512035_1
chardet                   3.0.4                 py38_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py38_1
colorama                  0.4.3                      py_0
conda                     4.8.3                    py38_0
conda-build               3.18.11                  py38_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py38h1de35cc_0
conda-verify              3.4.2                      py_1
contextlib2               0.6.0.post1                py_0
cryptography              2.9.2            py38ha12b0ac_0
curl                      7.71.1               hb0a8c7a_1
cycler                    0.10.0                   py38_0
cython                    0.29.21          py38hb1e8313_0
cytoolz                   0.10.1           py38h1de35cc_0
dask                      2.20.0                     py_0
dask-core                 2.20.0                     py_0
dbus                      1.13.16              h18a8e69_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20200713                   py_0
distributed               2.20.0                   py38_0
docutils                  0.16                     py38_1
entrypoints               0.3                      py38_0
et_xmlfile                1.0.1                   py_1001
expat                     2.2.9                hb1e8313_2
fastcache                 1.1.0            py38h1de35cc_0
filelock                  3.0.12                     py_0
flake8                    3.8.3                      py_0
flask                     1.1.2                      py_0
freetype                  2.10.2               ha233b18_0
fsspec                    0.7.4                      py_0
future                    0.18.2                   py38_1
get_terminal_size         1.0.0                h7520d66_0
gettext                   0.19.8.1             hb0f4f8b_2
gevent                    20.6.2           py38haf1e3a3_0
glib                      2.65.0               hc5f4afa_0
glob2                     0.7                        py_0
gmp                       6.1.2                hb37e062_1
gmpy2                     2.0.8            py38h6ef4df4_3
greenlet                  0.4.16           py38haf1e3a3_0
h5py                      2.10.0           py38h3134771_0
hdf5                      1.10.4               hfa1e0ec_0
heapdict                  1.0.1                      py_0
html5lib                  1.1                        py_0
icu                       58.2                 h0a44026_3
idna                      2.10                       py_0
imageio                   2.9.0                      py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py38_0
importlib_metadata        1.7.0                         0****
