### ISSUE TITLE
when i install basemap-data-hires,I got the following error code，how can i resolve this error？thank you

### ISSUE THREAD

**Issue by gehongyi** [conda/conda#5442]
C:\Users\Administrator>conda install -c conda-forge basemap-data-hires
Fetching package metadata ...............
Solving package specifications: ..........

Package plan for installation in environment f:\ProgramData\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    basemap-data-hires-1.1.0   |                0       105.4 MB  conda-forge

The following NEW packages will be INSTALLED:

    basemap-data-hires: 1.1.0-0 conda-forge

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred.                  | ETA:  19:25:48   1.58 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : f:\ProgramData\Anaconda3  (writable)
    default environment : f:\ProgramData\Anaconda3
       envs directories : f:\ProgramData\Anaconda3\envs
          package cache : f:\ProgramData\Anaconda3\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/co
nda-forge/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/co
nda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Administrator\.condarc
           offline mode : False

`$ f:\ProgramData\Anaconda3\Scripts\conda-script.py install -c conda-forge basem
ap-data-hires`

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 133
5, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 114
9, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 133
5, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 114
9, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 133
5, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 114
9, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 133
5, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 114
9, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 256, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 133
5, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "f:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 114
9, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\response.py", line 298, in _error_catcher
        yield
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\response.py", line 380, in read
        data = self._fp.read(amt)
      File "f:\ProgramData\Anaconda3\lib\http\client.py", line 449, in read
        n = self.readinto(b)
      File "f:\ProgramData\Anaconda3\lib\http\client.py", line 493, in readinto
        n = self.fp.readinto(b)
      File "f:\ProgramData\Anaconda3\lib\socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 273, in recv_into
        return self.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 273, in recv_into
        return self.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 273, in recv_into
        return self.recv_into(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\contrib\pyopenssl.py", line 271, in recv_into
        raise timeout('The read operation timed out')
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line
 703, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\response.py", line 432, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\response.py", line 397, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "f:\ProgramData\Anaconda3\lib\contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3
\response.py", line 303, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(h
ost='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 421
, in download
        for chunk in resp.iter_content(2**14):
      File "f:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line
 710, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-p
ackages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 643,
 in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", l
ine 135, in execute_instructions
        cmd(state, arg)
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", l
ine 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 353
, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 440
, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))

    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'f:\\Progr
amData\\Anaconda3\\pkgs\\basemap-data-hires-1.1.0-0.tar.bz2.part' for writing (H
TTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443):
 Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", lin
e 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line
145, in _main
        exit_code = args.func(args, p)
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py
", line 80, in execute
        install(args, parser, 'install')
      File "f:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", li
ne 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime err
or: Could not open 'f:\\ProgramData\\Anaconda3\\pkgs\\basemap-data-hires-1.1.0-0
.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.
s3.amazonaws.com', port=443): Read timed out.).

**Comment by kalefranz** [comment]
This is an intermittent HTTP error.  Conda 4.3 has longer timeouts that are configurable, and also better error messages.  `conda update conda`.
