### ISSUE TITLE
conda create --offline fails without internet connection

### ISSUE THREAD

**Issue by jayvius** [conda/conda#5443]
Trying to create a new environment on Windows using Anaconda2 4.3.1 64 bit, conda 4.3.14, without an Internet connection:

conda create -n test --offline

   Traceback (most recent call last):
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\Users\jbourque\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\connection.py", line 70, in send
        raise RuntimeError(message)
    RuntimeError: EnforceUnusedAdapter called with url https://repo.continuum.io/pkgs/free/noarch/repodata.json.bz2
    This command is using a remote connection in offline mode.

**Comment by kalefranz** [comment]
Please run `conda update conda`.  Latest conda release is 4.3.21.  Can you confirm that the error still exists?

**Comment by ijstokes** [comment]
Probably related to #5370

**Comment by MazdaX** [comment]
I still have the same error on conda 4.3.27 :

**Comment by kalefranz** [comment]
This issue has been fixed in later versions of conda 4.4.
