### ISSUE TITLE
add deprecation warning to `conda env upload`

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5445]
Further to #3824, `conda env upload` even to my normal user account does not work, using latest `conda` version 4.3.21.  `anaconda upload environment.yml` does work.  As discussed in #3824 `conda env upload` should have a deprecation message added (if it works for anyone, and right now I'm skeptical), and be removed ASAP.  If it is "just broken for everyone" then I'd say "don't fix it, just put in a deprecation notice" so at least users don't get the stack trace that I'm seeing now.

```
(daskwkshp) ijstokes@0194-ijstokes scaleml-dask-wkshp (master) $ anaconda whoami
Using Anaconda API: https://api.anaconda.org
Username: ijstokes
Member since: Wed Jul 31 02:19:49 2013
  +company: Continuum Analytics
  +description: None
  +location: Syracuse, NY
  +name: Ian Stokes-Rees
  +url: http://about.me/ijstokes
  +user_type: user
(daskwkshp) ijstokes@0194-ijstokes scaleml-dask-wkshp (master) $ conda env upload
Using Anaconda API: https://api.anaconda.org
Uploading environment daskwkshp to anaconda-server (https://api.anaconda.org)... 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 2.1.10
         python version : 3.6.1.final.0
       requests version : 2.12.4
       root environment : /Users/ijstokes/anaconda  (writable)
    default environment : /Users/ijstokes/anaconda/envs/daskwkshp
       envs directories : /Users/ijstokes/anaconda/envs
                          /Users/ijstokes/.conda/envs
          package cache : /Users/ijstokes/anaconda/pkgs
                          /Users/ijstokes/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/ijstokes/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 502:20

`$ /Users/ijstokes/anaconda/bin/conda-env upload`




    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda_env/utils/uploader.py", line 107, in ensure_package_namespace
        self.binstar.release(self.username, self.packagename, self.version)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/binstar_client/__init__.py", line 377, in release
        self._check_response(res)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
        raise ErrCls(msg, res.status_code)
    binstar_client.errors.NotFound: ("release version=u'2017.05.27.2208' does not exist", 404)
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda_env/cli/main_upload.py", line 101, in execute
        info = uploader.upload()
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda_env/utils/uploader.py", line 81, in upload
        if self.is_ready():
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda_env/utils/uploader.py", line 94, in is_ready
        return self.ensure_package_namespace() and self.ensure_distribution()
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda_env/utils/uploader.py", line 109, in ensure_package_namespace
        self.binstar.add_release(self.username, self.packagename, self.version, {}, '', '')
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/binstar_client/__init__.py", line 417, in add_release
        self._check_response(res)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/binstar_client/__init__.py", line 216, in _check_response
        raise ErrCls(msg, res.status_code)
    binstar_client.errors.BinstarError: ('Bad Request: Bad request syntax or unsupported method ([POST] https://api.anaconda.org/release/ijstokes/daskwkshp/2017.05.27.2208 -> 400)', 400)

(daskwkshp) ijstokes@0194-ijstokes scaleml-dask-wkshp (master) $ conda -V
conda 4.3.21
(daskwkshp) ijstokes@0194-ijstokes scaleml-dask-wkshp (master) $ cat environment.yml 
name: daskwkshp
channels:
  - conda-forge
  - defaults
dependencies:
  - python =3.6
  - bokeh
  - dask
  - distributed
  - graphviz
  - python-graphviz
  - ipyparallel
  - joblib
  - jupyter
  - matplotlib
  - notebook =5
  - pandas =0.19
  - pandas-datareader
  - pytables
  - scikit-learn
  - seaborn
  - snakeviz
  - ujson
```

**Comment by mcg1969** [comment]
I agree with this. In fact it really doesn't seem right to me for `conda env upload` to be implemented, since it relies on knowledge of how Anaconda Repo works. I suppose this would be fine if we were to standardize an abstract "binstar" connection class that anyone could build upon. But short of that, `anaconda upload` ought to be what we use and promote.

**Comment by BubuYo** [comment]
exactly the same situation, cannot upload my environment either.

**Comment by kalefranz** [comment]
> `anaconda upload environment.yml`

seems like the correct solution to me too

**Comment by kalefranz** [comment]
> should have a deprecation message added

agreed

**Comment by jdblischak** [comment]
In addition to the deprecation message, it would be nice if the Anaconda Cloud documentation could be updated.

https://docs.continuum.io/anaconda-cloud/user-guide/tasks/work-with-environments

I'd be happy to send the PR to update the docs myself if someone could point me to the relevant repo. [Anaconda-Platform/docs.anaconda.org](https://github.com/Anaconda-Platform/docs.anaconda.org) says it is deprecated, and it points to a non-existent repo (or at least one I don't have access to): [ContinuumIO/anaconda-cloud-docs](https://github.com/ContinuumIO/anaconda-cloud-docs)
