### ISSUE TITLE
  conda install keras error

### ISSUE THREAD

**Issue by huty323** [conda/conda#5457]
Current conda install:
               platform : linux-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/hadoopspark/anaconda2  (writable)
    default environment : /home/hadoopspark/anaconda2
       envs directories : /home/hadoopspark/anaconda2/envs
                          /home/hadoopspark/.conda/envs
          package cache : /home/hadoopspark/anaconda2/pkgs
                          /home/hadoopspark/.conda/pkgs
           channel URLs : http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/linux-64
                          http://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/hadoopspark/.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-431.el6.x86_64 CentOS/6.5 glibc/2.12
                UID:GID : 503:503

`$ /home/hadoopspark/anaconda2/bin/conda install keras`

    Traceback (most recent call last):
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/home/hadoopspark/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 159, in fetch_repodata_remote_request

**Comment by kalefranz** [comment]
You've cut off the bottom of the stack trace, so I can't tell what the error is.  Could you please include the full traceback?
