### ISSUE TITLE
error instaling jupyter for arcgispro

### ISSUE THREAD

**Issue by sandeepgadhwal** [conda/conda#5464]
Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\Program Files\ArcGIS\Pro\bin\Python\envs\arcgispro-py3
       envs directories : C:\Program Files\ArcGIS\Pro\bin\Python\envs
                          C:\ProgramData\Anaconda3\envs
          package cache : C:\Program Files\ArcGIS\Pro\bin\Python\envs\.pkgs
                          C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\sandyjones\.condarc
           offline mode : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install ipython-notebook`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 391, in download
        with FileLock(dst_path):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\lock.py", line 70, in __init__
        assert isdir(dirname(self.path_to_lock)), "{0} doesn't exist".format(self.path_to_lock)
    AssertionError: C:\Program Files\ArcGIS\Pro\bin\Python\envs\.pkgs\python-3.5.3-3.tar.bz2 doesn't exist

**Comment by kalefranz** [comment]
Please run `conda update conda`, and file a new issue with the updated stack trace if you keep having trouble.
