### ISSUE TITLE
"conda install pandas=0.19  pandas-datareader pytables" command error

### ISSUE THREAD

**Issue by Janderson** [conda/conda#5484]
When i try install conda=0.19 i got this error, but i already have the last version.
My OS: Windows 10.   :|

Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment C:\Anaconda2\envs\epat:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    hdf5-1.8.17                |            vc9_0        11.8 MB
    numpy-1.11.3               |           py27_0         3.1 MB
    requests-2.14.2            |           py27_0         698 KB
    numexpr-2.6.2              |      np111py27_0         132 KB
    requests-file-1.4.1        |           py27_0           6 KB
    requests-ftp-0.3.1         |           py27_0          13 KB
    pandas-0.19.2              |      np111py27_1         7.3 MB
    pytables-3.3.0             |      np111py27_0         2.8 MB
    matplotlib-2.0.2           |      np111py27_0         8.4 MB
    pandas-datareader-0.4.0    |           py27_0          96 KB
    ------------------------------------------------------------
                                           Total:        34.4 MB

The following NEW packages will be INSTALLED:

    bzip2:             1.0.6-vc9_3        [vc9]
    hdf5:              1.8.17-vc9_0       [vc9]
    numexpr:           2.6.2-np111py27_0
    pandas-datareader: 0.4.0-py27_0
    pytables:          3.3.0-np111py27_0
    requests:          2.14.2-py27_0
    requests-file:     1.4.1-py27_0
    requests-ftp:      0.3.1-py27_0

The following packages will be UPDATED:

    matplotlib:        2.0.2-np112py27_0  --> 2.0.2-np111py27_0

The following packages will be DOWNGRADED due to dependency conflicts:

    numpy:             1.12.1-py27_0      --> 1.11.3-py27_0
    pandas:            0.20.1-np112py27_0 --> 0.19.2-np111py27_1

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 409, in download
    getLogger('fetch.start').info((fn[:14], size))
  File "C:\Anaconda2\lib\logging\__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Anaconda2\lib\logging\__init__.py", line 1286, in _log
    self.handle(record)
  File "C:\Anaconda2\lib\logging\__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "C:\Anaconda2\lib\logging\__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "C:\Anaconda2\lib\logging\__init__.py", line 759, in handle
    self.emit(record)
  File "C:\Anaconda2\lib\site-packages\conda\console.py", line 27, in emit
    fetch_progress.start()
  File "C:\Anaconda2\lib\site-packages\conda\progressbar\__init__.py", line 310, in start
    self.update(0)
  File "C:\Anaconda2\lib\site-packages\conda\progressbar\__init__.py", line 282, in update
    self.fd.write(self._format_line() + '\r')
LookupError: unknown encoding: cp65001

Thanks

**Comment by Janderson** [comment]
same issues here, https://github.com/conda/conda/issues/5448

i will close this
