### ISSUE TITLE
Error during update of all installed packages

### ISSUE THREAD

**Issue by SherShahSuri** [conda/conda#5485]
An unexpected error has occurred.#######            | ETA:  0:00:10  69.65 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Gurmeet Singh\.condarc
           offline mode : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py update --all`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 277, in rec
v_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 277, in rec
v_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 277, in rec
v_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 277, in rec
v_into
        return self.connection.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "C:\ProgramData\Anaconda3\lib\site-packages\OpenSSL\SSL.py", line 1370, in _raise_ssl_error
        raise SysCallError(errno, errorcode.get(errno))
    OpenSSL.SSL.SysCallError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 302, in _error_catch
er
        yield
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 384, in read
        data = self._fp.read(amt)
      File "C:\ProgramData\Anaconda3\lib\http\client.py", line 449, in read
        n = self.readinto(b)
      File "C:\ProgramData\Anaconda3\lib\http\client.py", line 493, in readinto
        n = self.fp.readinto(b)
      File "C:\ProgramData\Anaconda3\lib\socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 293, in rec
v_into
        return self.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 293, in rec
v_into
        return self.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 293, in rec
v_into
        return self.recv_into(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 282, in rec
v_into
        raise SocketError(str(e))
    OSError: (10054, 'WSAECONNRESET')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 738, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 436, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 401, in read
        raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
      File "C:\ProgramData\Anaconda3\lib\contextlib.py", line 100, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 320, in _error_catch
er
        raise ProtocolError('Connection broken: %r' % e, e)
    requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OS
Error("(10054, 'WSAECONNRESET')",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 421, in download
        for chunk in resp.iter_content(2**14):
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py", line 741, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10
054, 'WSAECONNRESET')",))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\fetch.py", line 440, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\ProgramData\\Anaconda3\\pkgs\\nltk-3.2.4-py36
_0.tar.bz2.part' for writing (('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)', OSError("(10054, 'WSAECONNRE
SET')",))).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\ProgramData\\Ana
conda3\\pkgs\\nltk-3.2.4-py36_0.tar.bz2.part' for writing (('Connection broken: OSError("(10054, \'WSAECONNRESET\')",)',
 OSError("(10054, 'WSAECONNRESET')",))).

**Comment by SherShahSuri** [comment]
Kindly check and revert

**Comment by tyler-thetyrant** [comment]
`conda update conda` will update your conda version to 4.3.21.
Please open another issue if this gets reproduced in the recent version of conda.
