### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by schmmd** [conda/conda#5490]
Conda didn't like the `--log=DEBUG`.  It would be nice if it failed a bit more subtly.

```
$ conda --log=DEBUG activate deep_qa
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /Users/michael/miniconda3  (writable)
    default environment : /Users/michael/miniconda3
       envs directories : /Users/michael/miniconda3/envs
                          /Users/michael/.conda/envs
          package cache : /Users/michael/miniconda3/pkgs
                          /Users/michael/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Darwin/16.6.0 OSX/10.12.5
                UID:GID : 501:20



`$ /Users/michael/miniconda3/bin/conda --log=DEBUG activate deep_qa`




    Traceback (most recent call last):
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 1762, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 1971, in _parse_known_args
        stop_index = consume_positionals(start_index)
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 1927, in consume_positionals
        take_action(action, args)
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 1820, in take_action
        argument_values = self._get_values(action, argument_strings)
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 2271, in _get_values
        self._check_value(action, value[0])
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 2314, in _check_value
        raise ArgumentError(action, msg % args)
    argparse.ArgumentError: argument command: invalid choice: 'activate' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/michael/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/michael/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 119, in _main
        args = p.parse_args(args)
      File "/Users/michael/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 173, in parse_args
        return super(ArgumentParser, self).parse_args(*args, **kwargs)
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 1730, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "/Users/michael/miniconda3/lib/python3.6/argparse.py", line 1769, in parse_known_args
        self.error(str(err))
      File "/Users/michael/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 146, in error
        raise CommandNotFoundError(cmd, message)
    TypeError: __init__() takes 2 positional arguments but 3 were given
```

**Comment by kalefranz** [comment]
Did you try `conda update conda`?

**Comment by schmmd** [comment]
It's a fresh install--no I did not.

**Comment by schmmd** [comment]
Fixed by `conda update conda`.  Why doesn't a fresh install of miniconda use the latest release?
