### ISSUE TITLE
Conda HTTP Error

### ISSUE THREAD

**Issue by baddev** [conda/conda#5493]
Hi, 
Right after installation of miniconda, no command with http protocol function, on windows 10, shell started with administrator rights.

```
PS C:\Windows\system32> conda update conda -vv
DEBUG conda.cli.main:_main(132): verbosity set to 2
DEBUG conda.core.index:fetch_index(105): channel_urls=OrderedDict([(u'https://conda.anaconda.org/anaconda-fusion
/win-64', (u'anaconda-fusion', 0)), (u'https://conda.anaconda.org/anaconda-fusion/noarch', (u'anaconda-fusion',
0)), (u'https://repo.continuum.io/pkgs/free/win-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/free/n
oarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/r/win-64', (u'defaults', 1)), (u'https://repo.conti
nuum.io/pkgs/r/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/pro/win-64', (u'defaults', 1)), (u'
https://repo.continuum.io/pkgs/pro/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/msys2/win-64',
(u'defaults', 1)), (u'https://repo.continuum.io/pkgs/msys2/noarch', (u'defaults', 1))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value:
3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.core.repodata:fetch_repodata(414): No local cache found for https://conda.anaconda.org/anaconda-fusi
on/win-64 at C:\ProgramData\Miniconda2\pkgs\cache\591ab53b.json
DEBUG requests.packages.urllib3.connectionpool:_new_conn(809): Starting new HTTPS connection (1): conda.anaconda
.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Miniconda
2' using path 'C:\ProgramData\Miniconda2\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Miniconda
2' using path 'C:\ProgramData\Miniconda2\conda-meta\history'
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda2  (writable)
    default environment : C:\ProgramData\Miniconda2
       envs directories : C:\ProgramData\Miniconda2\envs
                          C:\Users\anonymous\AppData\Local\conda\conda\envs
                          C:\Users\anonymous\.conda\envs
          package cache : C:\ProgramData\Miniconda2\pkgs
                          C:\Users\anonymous\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\anonymous\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.10586



`$ C:\ProgramData\Miniconda2\Scripts\conda-script.py update conda -vv`




    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handl
er
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodat
a
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 463, in _collect_repodatas
_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 305, in fetch_repodata_rem
ote_request
        e.response)
    CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    SSLError(SSLError(SSLError("bad handshake: Error([('asn1 encoding routines', 'ASN1_item_verify', 'EVP lib'),
 ('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),),)

```

**Comment by tpowellcio** [comment]
Give it a try now, the ssl cert has been updated for conda.anaconda.org.
```
$ curl -Iv https://conda.anaconda.org
* Rebuilt URL to: https://conda.anaconda.org/
*   Trying 104.16.192.233...
* TCP_NODELAY set
* Connected to conda.anaconda.org (104.16.192.233) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: conda.anaconda.org
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
> HEAD / HTTP/1.1
> Host: conda.anaconda.org
> User-Agent: curl/7.51.0
> Accept: */*
> 
```

**Comment by baddev** [comment]
I still have the same answer.. But when I run your command : curl -Iv https://conda.anaconda.org
I have this returned :

```
curl : La connexion sous-jacente a été fermée : Une erreur inattendue s'est produite lors de l'envoi.
Au caractère Ligne:1 : 1
+ curl
+ ~~~~
    + CategoryInfo          : InvalidOperation : (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest
   ], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestComm
   and
curl -Iv https://conda.anaconda.org
```

**Comment by lzjqsdd** [comment]
got the same error

**Comment by baddev** [comment]
I could run the given command with another curl executable available on their website, but I still have the same error described in the first post.

**Comment by nehaljwani** [comment]
@baddev @lzjqsdd Could you please do the following, for debugging this further?

- Download https://download.sysinternals.com/files/ListDlls.zip and extract it to your a known location (e.g. Downloads folder)
- Open Anaconda prompt, just run python and import requests: 
```cmd
> python
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 12:06:52) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
```
- Then open another command prompt, and type (replace the location of the downloaded listdlls.exe):
```cmd
>C:\Users\username\Downloads\ListDlls\Listdlls.exe python
```

Copy the output and paste it here as a comment, or save it to a file and add it as an attachment.

**Comment by lzjqsdd** [comment]
@nehaljwani , I worked on ubuntu16.04,i've installed by source,what about other sloutions to help you debugging this.

**Comment by nehaljwani** [comment]
@lzjqsdd Please share the exact traceback that you are seeing on Ubuntu

**Comment by baddev** [comment]
@nehaljwani Please find attached my list of dll.
[list_dlls.txt](https://github.com/conda/conda/files/1083384/list_dlls.txt)

**Comment by baddev** [comment]
@nehaljwani Please find attached my list of dlls.
[dlls.txt](https://github.com/conda/conda/files/1084042/dlls.txt)

**Comment by nehaljwani** [comment]
@baddev I didn't find anything unusual, apart from Avast Anti Virus's DLL there. Which version of Miniconda are you using? Can you share output for: `conda list`

**Comment by baddev** [comment]
Well I know it is windows related as I had no issue with 2 others fedora computer but other than that..

```
# packages in environment at C:\ProgramData\Miniconda2:
#
cffi                      1.9.1                    py27_0
conda                     4.3.14                   py27_1
conda-env                 2.6.0                         0
console_shortcut          0.1.1                    py27_1
cryptography              1.7.1                    py27_0
enum34                    1.1.6                    py27_0
idna                      2.2                      py27_0
ipaddress                 1.0.18                   py27_0
menuinst                  1.4.4                    py27_0
openssl                   1.0.2k                    vc9_0  [vc9]
pip                       9.0.1                    py27_1
pyasn1                    0.1.9                    py27_0
pycosat                   0.6.1                    py27_1
pycparser                 2.17                     py27_0
pyopenssl                 16.2.0                   py27_0
python                    2.7.13                        0
pywin32                   220                      py27_2
requests                  2.12.4                   py27_0
ruamel_yaml               0.11.14                  py27_1
setuptools                27.2.0                   py27_1
six                       1.10.0                   py27_0
vs2008_runtime            9.00.30729.5054               0
wheel                     0.29.0                   py27_0


conda version : 4.3.14
```

**Comment by nehaljwani** [comment]
Could you please try two things:
(i) Try stopping the avast antivirus and see if that helps.
(ii) If (i) doesn't work, type `conda config --set ssl_verify false` and confirm whether or not `conda update conda` works?

**Comment by baddev** [comment]
(i) didn't help
(ii) return this (admin terminal)

```
PS C:\Windows\system32> conda config --set ssl_verify false
PS C:\Windows\system32> conda update conda -vv
DEBUG conda.cli.main:_main(132): verbosity set to 2
DEBUG conda.core.index:fetch_index(105): channel_urls=OrderedDict([(u'https://conda.anaconda.org/anaconda-fusion
/win-64', (u'anaconda-fusion', 0)), (u'https://conda.anaconda.org/anaconda-fusion/noarch', (u'anaconda-fusion',
0)), (u'https://repo.continuum.io/pkgs/free/win-64', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/free/n
oarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/r/win-64', (u'defaults', 1)), (u'https://repo.conti
nuum.io/pkgs/r/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/pro/win-64', (u'defaults', 1)), (u'
https://repo.continuum.io/pkgs/pro/noarch', (u'defaults', 1)), (u'https://repo.continuum.io/pkgs/msys2/win-64',
(u'defaults', 1)), (u'https://repo.continuum.io/pkgs/msys2/noarch', (u'defaults', 1))])
Fetching package metadata ...DEBUG requests.packages.urllib3.util.retry:from_int(191): Converted retries value:
3 -> Retry(total=3, connect=None, read=None, redirect=None)
DEBUG conda.core.repodata:fetch_repodata(414): No local cache found for https://conda.anaconda.org/anaconda-fusi
on/win-64 at C:\ProgramData\Miniconda2\pkgs\cache\591ab53b.json
DEBUG requests.packages.urllib3.connectionpool:_new_conn(809): Starting new HTTPS connection (1): conda.anaconda
.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



INFO conda.common.io:captured(59): overtaking stderr and stdout
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Miniconda
2' using path 'C:\ProgramData\Miniconda2\conda-meta\history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix 'C:\ProgramData\Miniconda
2' using path 'C:\ProgramData\Miniconda2\conda-meta\history'
INFO conda.common.io:captured(65): stderr and stdout yielding back
Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda2  (writable)
    default environment : C:\ProgramData\Miniconda2
       envs directories : C:\ProgramData\Miniconda2\envs
                          C:\Users\anonymous\AppData\Local\conda\conda\envs
                          C:\Users\anonymous\.conda\envs
          package cache : C:\ProgramData\Miniconda2\pkgs
                          C:\Users\anonymous\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\anonymous\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.10586



`$ C:\ProgramData\Miniconda2\Scripts\conda-script.py update conda -vv`




    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handl
er
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodat
a
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 463, in _collect_repodatas
_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Miniconda2\lib\site-packages\conda\core\repodata.py", line 305, in fetch_repodata_rem
ote_request
        e.response)
    CondaHTTPError: HTTP None None for url <https://conda.anaconda.org/anaconda-fusion/win-64/repodata.json>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    SSLError(SSLError(SSLError("bad handshake: Error([('rsa routines', 'INT_RSA_VERIFY', 'bad signature'), ('SSL
 routines', 'ssl3_get_key_exchange', 'bad signature')],)",),),)


Subsidiary question : I have a space in my real username (cc cc), could it be this ? I don't have enough space to check with another user name.
```

**Comment by baddev** [comment]
@nehaljwani Ok I gave up. I did reset my notebook and reinstall miniconda on the fresh installation : the issue is gone, so we'll never know. ^^
Anyway many thanks to you for your time and guidance.

**Comment by elmarmol** [comment]
So you can update conda or download packages, you only need to disable antivirus
