### ISSUE TITLE
AttributeError when trying to install any package.

### ISSUE THREAD

**Issue by Shakirovrrr** [conda/conda#5495]
This time I tried to install Theano with this command:
`conda install theano`

But unexpected error has occurred and conda asked me for posting this issue to issue tracker.

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Toolkits\Miniconda3  (writable)
    default environment : C:\Toolkits\Miniconda3
       envs directories : C:\Toolkits\Miniconda3\envs
                          C:\Users\Ruslan\AppData\Local\conda\conda\envs
                          C:\Users\Ruslan\.conda\envs
          package cache : C:\Toolkits\Miniconda3\pkgs
                          C:\Users\Ruslan\AppData\Local\conda\conda\pkgs
           channel URLs : https://pypi.python.org/simple/win-64
                          https://pypi.python.org/simple/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Ruslan\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063

`$ C:\Toolkits\Miniconda3\Scripts\conda-script.py install theano`

    Traceback (most recent call last):
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\install.py", line 130, in install
        context.validate_configuration()
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 838, in validate_configuration
        raise_errors(tuple(chain.from_iterable((errors, post_errors))))
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 836, in <genexpr>
        for name in self.parameter_names)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 829, in _collect_validation_error
        func(*args, **kwargs)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 447, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 664, in _merge
        for match in relevant_matches)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 664, in <genexpr>
        for match in relevant_matches)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\compat.py", line 71, in iteritems
        return iter(d.items(**kw))
    AttributeError: 'tuple' object has no attribute 'items'

**Comment by kalefranz** [comment]
Please `conda update conda`.

**Comment by Shakirovrrr** [comment]
Doesn't work too. Also, I've installed latest conda today.

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Toolkits\Miniconda3  (writable)
    default environment : C:\Toolkits\Miniconda3
       envs directories : C:\Toolkits\Miniconda3\envs
                          C:\Users\Ruslan\AppData\Local\conda\conda\envs
                          C:\Users\Ruslan\.conda\envs
          package cache : C:\Toolkits\Miniconda3\pkgs
                          C:\Users\Ruslan\AppData\Local\conda\conda\pkgs
           channel URLs : https://pypi.python.org/simple/win-64
                          https://pypi.python.org/simple/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Ruslan\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063



`$ C:\Toolkits\Miniconda3\Scripts\conda-script.py update conda`




    Traceback (most recent call last):
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\install.py", line 130, in install
        context.validate_configuration()
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 835, in validate_configuration
        raise_errors(tuple(chain.from_iterable((errors, post_errors))))
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 833, in <genexpr>
        for name in self.parameter_names)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 826, in _collect_validation_error
        func(*args, **kwargs)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 447, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 661, in _merge
        important_maps = tuple(dict((k, v) for k, v in iteritems(match.value(self)) if key_is_important(match, k)) for match in relevant_matches)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 661, in <genexpr>
        important_maps = tuple(dict((k, v) for k, v in iteritems(match.value(self)) if key_is_important(match, k)) for match in relevant_matches)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\compat.py", line 71, in iteritems
        return iter(d.items(**kw))
    AttributeError: 'tuple' object has no attribute 'items'

**Comment by nehaljwani** [comment]
@Shakirovrrr Please share output for:
```
conda config --show
```

**Comment by Shakirovrrr** [comment]
Got this error again:

`(root) C:\WINDOWS\system32>conda config --show`
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Toolkits\Miniconda3  (writable)
    default environment : C:\Toolkits\Miniconda3
       envs directories : C:\Toolkits\Miniconda3\envs
                          C:\Users\Ruslan\AppData\Local\conda\conda\envs
                          C:\Users\Ruslan\.conda\envs
          package cache : C:\Toolkits\Miniconda3\pkgs
                          C:\Users\Ruslan\AppData\Local\conda\conda\pkgs
           channel URLs : https://pypi.python.org/simple/win-64
                          https://pypi.python.org/simple/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Ruslan\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063



`$ C:\Toolkits\Miniconda3\Scripts\conda-script.py config --show`




    Traceback (most recent call last):
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main_config.py", line 234, in execute
        execute_config(args, parser)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main_config.py", line 308, in execute_config
        'verbosity',
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\cli\main_config.py", line 279, in <genexpr>
        for key in sorted(('add_anaconda_token',
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 447, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 661, in _merge
        important_maps = tuple(dict((k, v) for k, v in iteritems(match.value(self)) if key_is_important(match, k)) for match in relevant_matches)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\configuration.py", line 661, in <genexpr>
        important_maps = tuple(dict((k, v) for k, v in iteritems(match.value(self)) if key_is_important(match, k)) for match in relevant_matches)
      File "C:\Toolkits\Miniconda3\lib\site-packages\conda\common\compat.py", line 71, in iteritems
        return iter(d.items(**kw))
    AttributeError: 'tuple' object has no attribute 'items'

**Comment by Shakirovrrr** [comment]
Tried to delete the .condarc and reinstall the conda. Everything works well now. Thank you!
