### ISSUE TITLE
Unable to update Anaconda with conda update command

### ISSUE THREAD

**Issue by mehtamaulik** [conda/conda#5503]
C:\>conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 164, in main
    return conda_exception_handler(_main, *args)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 607, in conda_exception_handler
    print_unexpected_error_message(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 561, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 531, in get_info
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 142, in execute
    from conda.api import get_index
  File "C:\Anaconda2\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Anaconda2\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .repodata import collect_all_repodata
  File "C:\Anaconda2\lib\site-packages\conda\core\repodata.py", line 4, in <module>
    import bz2
ImportError: No module named bz2

**Comment by tyler-thetyrant** [comment]
Can you show your `conda info` output?
My guess is that you are using very old version of conda that `conda update conda` breaks.
Best bet would be to uninstall then reinstalling most recent release of miniconda, which can be found [here](https://conda.io/miniconda.html).

**Comment by tyler-thetyrant** [comment]
Closing this for now, and will reopen if the issue persists in the most recent version of conda.
