### ISSUE TITLE
"An unexpected error" / "IOError: invalid data stream" installing in Docker

### ISSUE THREAD

**Issue by noahlt** [conda/conda#5518]
Hi! I have a Conda environment that I'm trying to reproduce inside a Docker image.  Halfway through the `condo env create` command, I get this:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.15
       conda is private : False
      conda-env version : 4.2.15
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /opt/conda/bin/conda-env create environment.yml`




    Traceback (most recent call last):
      File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python2.7/site-packages/conda_env/installers/conda.py", line 33, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/opt/conda/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/opt/conda/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/opt/conda/lib/python2.7/site-packages/conda/instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "/opt/conda/lib/python2.7/site-packages/conda/install.py", line 809, in extract
        t.extractall(path=temp_path)
      File "/opt/conda/lib/python2.7/tarfile.py", line 2079, in extractall
        self.extract(tarinfo, path)
      File "/opt/conda/lib/python2.7/tarfile.py", line 2116, in extract
        self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
      File "/opt/conda/lib/python2.7/tarfile.py", line 2192, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "/opt/conda/lib/python2.7/tarfile.py", line 2233, in makefile
        copyfileobj(source, target)
      File "/opt/conda/lib/python2.7/tarfile.py", line 266, in copyfileobj
        shutil.copyfileobj(src, dst)
      File "/opt/conda/lib/python2.7/shutil.py", line 49, in copyfileobj
        buf = fsrc.read(length)
      File "/opt/conda/lib/python2.7/tarfile.py", line 831, in read
        buf += self.fileobj.read(size - len(buf))
      File "/opt/conda/lib/python2.7/tarfile.py", line 743, in read
        return self.readnormal(size)
      File "/opt/conda/lib/python2.7/tarfile.py", line 758, in readnormal
        return self.__read(size)
      File "/opt/conda/lib/python2.7/tarfile.py", line 748, in __read
        buf = self.fileobj.read(size)
    IOError: invalid data stream
```

I'm happy to help debug this if anyone wants to take a look.

**Comment by noahlt** [comment]
Also, near the beginning of the `conda env create` output I got these, which seem like they might be relevant:

```
Step 5/7 : RUN conda env create environment.yml
 ---> Running in 8ca1a8080e87
Fetching package metadata .........
Solving package specifications: ..........
WARNING conda.common.disk:make_writable(132): Error making path writable: /opt/conda/pkgs/sqlite-3.13.0-0/bin/sqlite3
OSError(5, 'Input/output error')
WARNING conda.common.disk:make_writable(132): Error making path writable: /opt/conda/pkgs/sqlite-3.13.0-0/bin/sqlite3
OSError(5, 'Input/output error')
WARNING conda.common.disk:make_writable(132): Error making path writable: /opt/conda/pkgs/zlib-1.2.8-3/lib/libz.a
OSError(5, 'Input/output error')
WARNING conda.common.disk:make_writable(132): Error making path writable: /opt/conda/pkgs/zlib-1.2.8-3/lib/libz.a
OSError(5, 'Input/output error')
WARNING conda.common.disk:make_writable(132): Error making path writable: /opt/conda/pkgs/sqlite-3.13.0-0/bin/sqlite3
OSError(5, 'Input/output error')
WARNING conda.install:rm_fetched(754): Directory not removed during RM_FETCHED instruction: /opt/conda/pkgs/sqlite-3.13.0-0
WARNING conda.common.disk:make_writable(132): Error making path writable: /opt/conda/pkgs/zlib-1.2.8-3/lib/libz.a
OSError(5, 'Input/output error')
WARNING conda.install:rm_fetched(754): Directory not removed during RM_FETCHED instruction: /opt/conda/pkgs/zlib-1.2.8-3
Pruning fetched packages from the cache ...
Fetching packages ...
```

**Comment by kalefranz** [comment]
We've fixed a couple docker issues in recent versions of conda 4.3 and 4.4.
