### ISSUE TITLE
Windows conda update fails

### ISSUE THREAD

**Issue by elf55** [conda/conda#5528]
I was doing 
conda update bokeh

this is the dump:

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : w:\Continuum\Anaconda3  (writable)
    default environment : w:\Continuum\Anaconda3
       envs directories : w:\Continuum\Anaconda3\envs
                          C:\Users\MLMatyas\AppData\Local\conda\conda\envs
                          C:\Users\MLMatyas\.conda\envs
          package cache : w:\Continuum\Anaconda3\pkgs
                          C:\Users\MLMatyas\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\MLMatyas\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/200
8ServerR2 Windows/6.1.7601

`$ w:\Continuum\Anaconda3\Scripts\conda-script.py update bokeh`

    Traceback (most recent call last):
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line
573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 13
4, in _main
        exit_code = args.func(args, p)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\cli\main_update.py",
line 65, in execute
        install(args, parser, 'update')
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line
 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\plan.py", line 800, i
n execute_actions
        execute_instructions(plan, index, verbose)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", lin
e 247, in execute_instructions
        cmd(state, arg)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\instructions.py", lin
e 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 2
62, in execute
        self.verify()
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 2
41, in verify
        self.prepare()
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 1
48, in prepare
        for pkg_info in self.packages_info_to_link)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 1
48, in <genexpr>
        for pkg_info in self.packages_info_to_link)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 5
4, in determine_link_type
        if hardlink_supported(source_test_file, target_prefix):
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\_vendor\auxlib\decora
tors.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "w:\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\test.py
", line 84, in hardlink_supported
        assert not lexists(test_file), test_file
    AssertionError: w:\Continuum\Anaconda3\.tmp.index.json

**Comment by kalefranz** [comment]
You should do `conda update conda` first. Latest is 4.3.21. Do you still have the error after a conda update?

**Comment by kalefranz** [comment]
You should just be able to manually delete the file `w:\Continuum\Anaconda3.tmp.index.json` and then continue.

**Comment by kalefranz** [comment]
Leaving open, because we shouldn't be raising an assertion error here.

**Comment by kalefranz** [comment]
Issue is resolved.  If it comes up again, it's because of https://github.com/conda/conda/issues/6631
