### ISSUE TITLE
Interrupted system call error causes stack trace

### ISSUE THREAD

**Issue by bkreider** [conda/conda#5535]
I think this was caused by a very lossy wifi connection.  It would be nice to catch this exception and provide a nice message or retry.

```
~$ conda info anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



`$ /opt/anaconda/bin/conda info anaconda`




    Traceback (most recent call last):
      File "/opt/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_info.py", line 159, in execute
        index = get_index()
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/opt/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 323, in connect
        ssl_context=context)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "/opt/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 419, in wrap_socket
        rd, _, _ = select.select([sock], [], [], sock.gettimeout())
    error: (4, 'Interrupted system call')
```

**Comment by kalefranz** [comment]
Looks like this will eventually resolve itself. https://stackoverflow.com/a/29411416/2127762
