### ISSUE TITLE
error while installing qtconsole ipython

### ISSUE THREAD

**Issue by nikhil888** [conda/conda#5539]
Traceback (most recent call last):
  File "C:\Users\Nikhil Goyal\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\plan.py", line 395, in install_actions
    r = Resolve(index)
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\resolve.py", line 258, in __init__
    self.groups, self.trackers = build_groups(self.index)
  File "C:\Users\Nikhil Goyal\Anaconda2\lib\site-packages\conda\resolve.py", line 238, in build_groups
    groups.setdefault(info['name'], []).append(fn)
KeyError: 'name'

**Comment by kalefranz** [comment]
If you get this error with a recent version of conda, please file a new issue.  `conda info` will show your conda version.  Latest is 4.3.30.
