### ISSUE TITLE
Anaconda Python Error - I need help

### ISSUE THREAD

**Issue by dotbusiness** [conda/conda#5541]
Hi, I've got this error and I really don't know why

I've had python on anaconda for some time apart from it taking forever to initialize it by a double clicking on it, it worked fine

here's the error I'm getting below:

Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

unacceptable character #x0000: special characters are not allowed
  in "C:\Users\User\.continuum\anaconda-client\config.yaml", position 0
Traceback

Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\app\start.py", line 111, in start_app
    with lock.acquire(timeout=3.0):  # timeout in seconds
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\external\filelock.py", line 254, in acquire
    raise Timeout(self._lock_file)
anaconda_navigator.external.filelock.Timeout: The file lock 'C:\Users\User\.anaconda\navigator\navigator.lock' could not be acquired.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\app\start.py", line 124, in start_app
    "There is an instance of "
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 450, in __init__
    type_=self.INFORMATION_BOX,
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\widgets\dialogs\__init__.py", line 265, in __init__
    self.tracker = GATracker()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\utils\analytics.py", line 284, in GATracker
    GA_TRACKER = _GATracker()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\utils\analytics.py", line 95, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1205, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 66, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\api\client_api.py", line 601, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\anaconda_navigator\api\client_api.py", line 82, in __init__
    log_level=logging.NOTSET
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\binstar_client\utils\config.py", line 94, in get_server_api
    config = get_config(remote_site=site)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\binstar_client\utils\config.py", line 228, in get_config
    file_configs = load_file_configs(SEARCH_PATH)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\binstar_client\utils\config.py", line 222, in load_file_configs
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\binstar_client\utils\config.py", line 222, in 
    raw_data = collections.OrderedDict(kv for kv in itertools.chain.from_iterable(load_paths))
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\binstar_client\utils\config.py", line 202, in _dir_yaml_loader
    yield filepath, load_config(filepath)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\binstar_client\utils\config.py", line 186, in load_config
    data = yaml.load(fd)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\yaml\reader.py", line 135, in determine_encoding
    self.update(1)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\yaml\reader.py", line 169, in update
    self.check_printable(data)
  File "C:\Users\User\Anaconda3\anaca\lib\site-packages\yaml\reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\User\.continuum\anaconda-client\config.yaml", position 0

**Comment by VoMimbre** [comment]
Hi
I got the same kind of error
I've clear it doing this : 
1- go to your Anaconda directory, search the 3 files anaconda-navigator.ini navigator.lock and navigator.pid.
Try to remove it. If the lock file cannot be remove because "this file is open in Python"
do the point 2
2- open Task manager on "Process" tab, kill all python process
After that you should be able to remove the lock file

Cheers

**Comment by kalefranz** [comment]
> Please report this issue in the anaconda issue tracker

This isn't the anaconda issue tracker.  However it looks like there are invalid characters in the file

    C:\Users\User.continuum\anaconda-client\config.yaml

Maybe try manually editing it?
