### ISSUE TITLE
armv7 "conda -h" ImportError: No module named 'requests._internal_utils'

### ISSUE THREAD

**Issue by chrisamow** [conda/conda#5548]
I realize not exactly the mainstream path here lol
This is on a raspberry pi 3b

The only thing I can think of that may be related is I git cloned pudb since there is no pip install for this platform.  And I did the "python setup.py install" and it seemed to go fine, I'll put the output of that at the end

conda is broken for me somehow (can't even do a help)

```
➜  pi git:(master) conda -h
Traceback (most recent call last):
  File "/home/pi/miniconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 140, in main
    from conda.cli import main_search
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main_search.py", line 12, in <module>
    from conda.misc import make_icon_url
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/misc.py", line 19, in <module>
    from conda.api import get_index
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/api.py", line 10, in <module>
    from conda.fetch import fetch_index
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/fetch.py", line 24, in <module>
    from conda.connection import CondaSession, unparse_url, RETRIES
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/connection.py", line 24, in <module>
    import requests
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/home/pi/miniconda3/lib/python3.4/site-packages/requests/utils.py", line 24, in <module>
    from ._internal_utils import to_native_string
ImportError: No module named 'requests._internal_utils'

```

output of the pudb setup.py

```
(pi)➜  pudb git:(master) python setup.py install
/home/pi/miniconda3/envs/pi/lib/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'test_requires'
  warnings.warn(msg)
running install
running bdist_egg
running egg_info
creating pudb.egg-info
writing pudb.egg-info/PKG-INFO
writing dependency_links to pudb.egg-info/dependency_links.txt
writing requirements to pudb.egg-info/requires.txt
writing top-level names to pudb.egg-info/top_level.txt
writing entry points to pudb.egg-info/entry_points.txt
writing manifest file 'pudb.egg-info/SOURCES.txt'
reading manifest file 'pudb.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pudb.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/pudb
copying pudb/ipython.py -> build/lib/pudb
copying pudb/source_view.py -> build/lib/pudb
copying pudb/py3compat.py -> build/lib/pudb
copying pudb/lowlevel.py -> build/lib/pudb
copying pudb/debugger.py -> build/lib/pudb
copying pudb/ui_tools.py -> build/lib/pudb
copying pudb/__init__.py -> build/lib/pudb
copying pudb/run.py -> build/lib/pudb
copying pudb/theme.py -> build/lib/pudb
copying pudb/__main__.py -> build/lib/pudb
copying pudb/remote.py -> build/lib/pudb
copying pudb/settings.py -> build/lib/pudb
copying pudb/shell.py -> build/lib/pudb
copying pudb/var_view.py -> build/lib/pudb
copying pudb/b.py -> build/lib/pudb
creating build/bdist.linux-armv7l
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/ipython.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/source_view.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/py3compat.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/lowlevel.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/debugger.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/ui_tools.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/__init__.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/run.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/theme.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/__main__.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/remote.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/settings.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/shell.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/var_view.py -> build/bdist.linux-armv7l/egg/pudb
copying build/lib/pudb/b.py -> build/bdist.linux-armv7l/egg/pudb
byte-compiling build/bdist.linux-armv7l/egg/pudb/ipython.py to ipython.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/source_view.py to source_view.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/py3compat.py to py3compat.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/lowlevel.py to lowlevel.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/debugger.py to debugger.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/ui_tools.py to ui_tools.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/__init__.py to __init__.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/run.py to run.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/theme.py to theme.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/__main__.py to __main__.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/remote.py to remote.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/settings.py to settings.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/shell.py to shell.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/var_view.py to var_view.cpython-34.pyc
byte-compiling build/bdist.linux-armv7l/egg/pudb/b.py to b.cpython-34.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying pudb.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pudb.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pudb.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pudb.egg-info/entry_points.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pudb.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pudb.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
pudb.__pycache__.debugger.cpython-34: module references __file__
creating dist
creating 'dist/pudb-2017.1.2-py3.4.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing pudb-2017.1.2-py3.4.egg
creating /home/pi/miniconda3/envs/pi/lib/python3.4/site-packages/pudb-2017.1.2-py3.4.egg
Extracting pudb-2017.1.2-py3.4.egg to /home/pi/miniconda3/envs/pi/lib/python3.4/site-packages
Adding pudb 2017.1.2 to easy-install.pth file
Installing pudb3 script to /home/pi/miniconda3/envs/pi/bin
Installed /home/pi/miniconda3/envs/pi/lib/python3.4/site-packages/pudb-2017.1.2-py3.4.egg
Processing dependencies for pudb==2017.1.2
Searching for Pygments==2.2.0
Best match: Pygments 2.2.0
Adding Pygments 2.2.0 to easy-install.pth file
Installing pygmentize script to /home/pi/miniconda3/envs/pi/bin
Using /home/pi/miniconda3/envs/pi/lib/python3.4/site-packages
Searching for urwid==1.3.1
Best match: urwid 1.3.1
Adding urwid 1.3.1 to easy-install.pth file
Using /home/pi/miniconda3/envs/pi/lib/python3.4/site-packages
Finished processing dependencies for pudb==2017.1.2
```

**Comment by chrisamow** [comment]
Going to close this because while there was no conda install for pudb there actually is a pip one for armv7
