### ISSUE TITLE
spacy install error with conda

### ISSUE THREAD

**Issue by pravallika28** [conda/conda#5550]
Current conda install:

               platform : linux-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /home/pravallika/anaconda2  (writable)
    default environment : /home/pravallika/anaconda2
       envs directories : /home/pravallika/anaconda2/envs
          package cache : /home/pravallika/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-32/
                          https://conda.anaconda.org/conda-forge/noarch/
                          https://repo.continuum.io/pkgs/free/linux-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/pravallika/.condarc
           offline mode : False

`$ /home/pravallika/anaconda2/bin/conda install spacy`

    Traceback (most recent call last):
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 293, in fetch_index
        for url in urls]
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 70, in func
        res = f(*args, **kwargs)
      File "/home/pravallika/anaconda2/lib/python2.7/site-packages/conda/fetch.py", line 137, in fetch_repodata
        .format(url, filename, e))
    CondaRuntimeError: Runtime error: Invalid index file: https://conda.anaconda.org/conda-forge/linux-32/repodata.json: Missing dependencies for SOCKS support.

**Comment by nehaljwani** [comment]
Could you please share the output for:

```bash
env | grep -i proxy
```

If you see any socks_proxy or SOCKS_PROXY environment variable, please unset it:
```basg
unset socks_proxy
unset SOCKS_PROXY
```

However, if that was intended, please try:

```bash
pip install -U requests[socks]
```

**Comment by kalefranz** [comment]
More recent versions of conda should have better error messages for missing pysocks.
