### ISSUE TITLE
conda commands fail if there is not a current working directory

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#5552]
Most (all?) conda commands will fail when the current working directory does not exist.  This is a fairly unusual occurrence but can occur.

For example:

```
~$ cd foobar/
~/foobar$ rmdir ../foobar
~/foobar$ conda info
Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 100, in _main
    from ..base.context import context
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 763, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 364, in load_file_configs
    expanded_paths = tuple(expand(path) for path in search_path)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 364, in <genexpr>
    expanded_paths = tuple(expand(path) for path in search_path)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/path.py", line 97, in expand
    return abspath(expanduser(expandvars(path)))
  File "/home/jhelmus/anaconda3/lib/python3.6/posixpath.py", line 374, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jhelmus/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 571, in print_unexpected_error_message
    from .base.context import context
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 763, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 364, in load_file_configs
    expanded_paths = tuple(expand(path) for path in search_path)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 364, in <genexpr>
    expanded_paths = tuple(expand(path) for path in search_path)
  File "/home/jhelmus/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/path.py", line 97, in expand
    return abspath(expanduser(expandvars(path)))
  File "/home/jhelmus/anaconda3/lib/python3.6/posixpath.py", line 374, in abspath
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by kalefranz** [comment]
I think we fixed this.  At least that particular code path doesn't exist anymore.

**Comment by kalefranz** [comment]
Oh, wait. Maybe we didn't fix it.

**Comment by kalefranz** [comment]
I'm not sure what I should do.  In general, I feel like if we can't call `abspath()`, we're sorta screwed anyway.

**Comment by jjhelmus** [comment]
This does appear to be fixed in conda 4.4.7:

```
~/sandbox/foobar$ rmdir ../foobar/
(HEAD) ~/sandbox/foobar$ conda info
sh: 0: getcwd() failed: No such file or directory

     active environment : None
       user config file : /home/jhelmus/.condarc
 populated config files : /home/jhelmus/.condarc
          conda version : 4.4.7
    conda-build version : 3.3.0
         python version : 3.6.4.final.0
       base environment : /home/jhelmus/anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/jhelmus/anaconda3/pkgs
                          /home/jhelmus/.conda/pkgs
       envs directories : /home/jhelmus/anaconda3/envs
                          /home/jhelmus/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/3.6.4 Linux/4.10.0-40-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

(HEAD) ~/sandbox/foobar$ 
```

Creating, activating, and using a environment also works without a current working directory.
