### ISSUE TITLE
Permission error while updating package deleted /Users/user/anaconda/bin/conda

### ISSUE THREAD

**Issue by soundshaped** [conda/conda#5557]
Basically tried to install `protobuf` from `conda` and it ran into an error and now `conda` command doesn't work and doesn't exist. I'm not certain where to put this is after looking into it so if this is the absolutely wrong place please forgive my ignorance.

I'm running OSX 10.12.5

## command used:
```
FURLY_GHOST@Furl-MBP:~$ conda install protobuf
```
## Output:
```
Fetching package metadata .......
Solving package specifications: ..........

Package plan for installation in environment /Users/Furl/anaconda:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          601 B
    mkl-2017.0.1               |                0       110.8 MB
    libpng-1.6.27              |                0         240 KB
    libprotobuf-3.2.0          |                0         6.3 MB
    numpy-1.12.1               |           py27_0         3.4 MB
    subprocess32-3.2.7         |           py27_0          39 KB
    astropy-1.3.3              |      np112py27_0         6.4 MB
    bottleneck-1.2.1           |      np112py27_0         107 KB
    h5py-2.7.0                 |      np112py27_0         909 KB
    llvmlite-0.18.0            |           py27_0         9.2 MB
    numexpr-2.6.2              |      np112py27_0         117 KB
    protobuf-3.2.0             |           py27_0         440 KB
    pywavelets-0.5.2           |      np112py27_0         4.0 MB
    scipy-0.19.0               |      np112py27_0        14.9 MB
    gensim-2.1.0               |      np112py27_0         5.1 MB
    matplotlib-2.0.2           |      np112py27_0         8.2 MB
    numba-0.33.0               |      np112py27_0         1.8 MB
    pandas-0.20.2              |      np112py27_0         9.4 MB
    pytables-3.3.0             |      np112py27_0         2.3 MB
    scikit-learn-0.18.1        |      np112py27_1         5.0 MB
    scikit-image-0.13.0        |      np112py27_0        23.0 MB
    statsmodels-0.8.0          |      np112py27_0         6.1 MB
    conda-4.3.22               |           py27_0         494 KB
    tensorflow-1.1.0           |      np112py27_0        23.5 MB
    ------------------------------------------------------------
                                           Total:       241.7 MB

The following NEW packages will be INSTALLED:

    libprotobuf:  3.2.0-0
    pywavelets:   0.5.2-np112py27_0
    subprocess32: 3.2.7-py27_0

The following packages will be UPDATED:

    astropy:      1.2.1-np111py27_0              --> 1.3.3-np112py27_0
    bottleneck:   1.1.0-np111py27_0              --> 1.2.1-np112py27_0
    conda:        4.2.13-py27_0      conda-forge --> 4.3.22-py27_0
    gensim:       0.13.3-np111py27_0             --> 2.1.0-np112py27_0
    h5py:         2.6.0-np111py27_2              --> 2.7.0-np112py27_0
    libpng:       1.6.22-0                       --> 1.6.27-0
    llvmlite:     0.14.0-py27_0                  --> 0.18.0-py27_0
    matplotlib:   1.5.3-np111py27_1              --> 2.0.2-np112py27_0
    mkl:          11.3.3-0                       --> 2017.0.1-0
    numba:        0.29.0-np111py27_0             --> 0.33.0-np112py27_0
    numexpr:      2.6.1-np111py27_1              --> 2.6.2-np112py27_0
    numpy:        1.11.2-py27_0                  --> 1.12.1-py27_0
    pandas:       0.19.1-np111py27_0             --> 0.20.2-np112py27_0
    protobuf:     3.0.0-py27_0       conda-forge --> 3.2.0-py27_0
    pytables:     3.3.0-np111py27_0              --> 3.3.0-np112py27_0
    scikit-image: 0.12.3-np111py27_1             --> 0.13.0-np112py27_0
    scikit-learn: 0.18.1-np111py27_0             --> 0.18.1-np112py27_1
    scipy:        0.18.1-np111py27_0             --> 0.19.0-np112py27_0
    statsmodels:  0.6.1-np111py27_1              --> 0.8.0-np112py27_0
    tensorflow:   0.11.0-py27_0      conda-forge --> 1.1.0-np112py27_0

The following packages will be SUPERCEDED by a higher-priority channel:

    conda-env:    2.6.0-0            conda-forge --> 2.6.0-0

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
conda-env-2.6. 100% |###################################################| Time: 0:00:00 614.52 kB/s
mkl-2017.0.1-0 100% |###################################################| Time: 0:03:07 620.10 kB/s
libpng-1.6.27- 100% |###################################################| Time: 0:00:00 645.46 kB/s
libprotobuf-3. 100% |###################################################| Time: 0:00:09 684.77 kB/s
numpy-1.12.1-p 100% |###################################################| Time: 0:00:11 321.04 kB/s
subprocess32-3 100% |###################################################| Time: 0:00:00 487.74 kB/s
astropy-1.3.3- 100% |###################################################| Time: 0:00:10 611.78 kB/s
bottleneck-1.2 100% |###################################################| Time: 0:00:00 468.32 kB/s
h5py-2.7.0-np1 100% |###################################################| Time: 0:00:01 510.64 kB/s
llvmlite-0.18. 100% |###################################################| Time: 0:00:19 487.23 kB/s
numexpr-2.6.2- 100% |###################################################| Time: 0:00:00 634.30 kB/s
protobuf-3.2.0 100% |###################################################| Time: 0:00:01 332.68 kB/s
pywavelets-0.5 100% |###################################################| Time: 0:00:06 675.01 kB/s
scipy-0.19.0-n 100% |###################################################| Time: 0:01:03 244.97 kB/s
gensim-2.1.0-n 100% |###################################################| Time: 0:00:26 198.85 kB/s
matplotlib-2.0 100% |###################################################| Time: 0:00:12 670.32 kB/s
numba-0.33.0-n 100% |###################################################| Time: 0:00:02 677.91 kB/s
pandas-0.20.2- 100% |###################################################| Time: 0:00:16 607.14 kB/s
pytables-3.3.0 100% |###################################################| Time: 0:00:06 360.52 kB/s
scikit-learn-0 100% |###################################################| Time: 0:00:12 410.10 kB/s
scikit-image-0 100% |###################################################| Time: 0:00:38 627.18 kB/s
statsmodels-0. 100% |###################################################| Time: 0:00:14 443.54 kB/s
conda-4.3.22-p 100% |###################################################| Time: 0:00:01 502.80 kB/s
tensorflow-1.1 100% |###################################################| Time: 0:00:36 676.03 kB/s
```

## Here is where the error comes in and error report
```
Extracting packages ...
[      COMPLETE      ]|######################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|######################################################################| 100%
Linking packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 2.6.0
    conda-build version : 2.0.12
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /Users/Furl/anaconda  (writable)
    default environment : /Users/Furl/anaconda
       envs directories : /Users/Furl/anaconda/envs


          package cache : /Users/Furl/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/Furl/anaconda/bin/conda install protobuf`




    Traceback (most recent call last):
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 405, in install
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 135, in execute_instructions
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 78, in LINK_CMD
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/install.py", line 986, in link
      File "/Users/Furl/anaconda/lib/python2.7/site-packages/conda/install.py", line 171, in _link
      File "/Users/Furl/anaconda/lib/python2.7/shutil.py", line 130, in copy2
        copyfile(src, dst)
      File "/Users/Furl/anaconda/lib/python2.7/shutil.py", line 83, in copyfile
        with open(dst, 'wb') as fdst:
    IOError: [Errno 13] Permission denied: '/Users/Furl/anaconda/lib/python2.7/site-packages/numpy/__config__.py'
```
I tried `conda info` which returned this. I verified that `conda` was nowhere to be found in `../anaconda/bin/`. 
```
FURLY_GHOST@Furl-MBP:~$ conda info
-bash: /Users/Furl/anaconda/bin/conda: No such file or directory
```

If i log into a new session in terminal and try `conda` the return is simply `-bash: conda: command not found` . in that same new session `which python` returns the directory of anaconda's python install which is the same as before.

I was interested to see if maybe just the `conda` command was affected and likely `protobuf`. However it seems a few packages were taken down with the `IOError`.

```
FURLY_GHOST@Furl-MBP:~$ python
Python 2.7.12 |Anaconda custom (x86_64)| (default, Jul  2 2016, 17:43:17)
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy
>>> import pandas
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named pandas
>>>
```

Any and all help is appreciated - let me know if you think of some information that I haven't included that may be relevant.

**Comment by kalefranz** [comment]
Instance of conda crashing where conda unlinked itself but didn't get to link the new version during an update.  This was solved almost a year ago in conda 4.3.
