### ISSUE TITLE
Sometimes the first ``source activate`` of an environment does not work properly?

### ISSUE THREAD

**Issue by ceball** [conda/conda#5563]
I have been having an intermittent problem where newly created environments do not seem to work properly when I activate them the first time. I believe this has happened to me on Windows in the past (I assumed the problem was with Windows, or me), but now seems to happen to me occasionally on OS X too. Am I doing something wrong or strange?

Here's a copy/paste of me creating a new environment and then activating it, installing datashader, datashader apparently not being present, deactivating and then activating the environment, then datashader being present...

```
$ mkdir /tmp/test && cd /tmp/test
$ conda --version
conda 4.3.21
$ conda create --name testing123
Fetching package metadata ...........
Solving package specifications: 
Package plan for installation in environment /Users/cball/Eunectes/mc3/envs/testing123:

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate testing123
#
# To deactivate this environment, use:
# > source deactivate testing123
#

$ source activate testing123
(testing123) $ python -c "import datashader; print(datashader.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'datashader'
(testing123) $ conda install datashader
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /Users/cball/Eunectes/mc3/envs/testing123:

The following NEW packages will be INSTALLED:

    bokeh:            0.12.4-py36_0     
    cloudpickle:      0.2.2-py36_0      
    dask:             0.15.0-py36_0     
    datashader:       0.4.0-py36_0      
    datashape:        0.5.4-py36_0      
    decorator:        4.0.11-py36_0     
    freetype:         2.5.5-2           
    jbig:             2.1-0             
    jinja2:           2.9.6-py36_0      
    jpeg:             9b-0              
    libpng:           1.6.27-0          
    libtiff:          4.0.6-3           
    llvmlite:         0.18.0-py36_0     
    locket:           0.2.0-py36_1      
    markupsafe:       0.23-py36_2       
    mkl:              2017.0.1-0        
    multipledispatch: 0.4.9-py36_0      
    networkx:         1.11-py36_0       
    numba:            0.33.0-np112py36_0
    numpy:            1.12.1-py36_0     
    odo:              0.5.0-py36_1      
    olefile:          0.44-py36_0       
    openssl:          1.0.2l-0          
    pandas:           0.20.2-np112py36_0
    partd:            0.3.8-py36_0      
    pillow:           4.1.1-py36_0      
    pip:              9.0.1-py36_1      
    python:           3.6.1-2           
    python-dateutil:  2.6.0-py36_0      
    pytz:             2017.2-py36_0     
    pyyaml:           3.12-py36_0       
    readline:         6.2-2             
    requests:         2.14.2-py36_0     
    setuptools:       27.2.0-py36_0     
    six:              1.10.0-py36_0     
    sqlite:           3.13.0-0          
    tk:               8.5.18-0          
    toolz:            0.8.2-py36_0      
    tornado:          4.5.1-py36_0      
    wheel:            0.29.0-py36_0     
    xarray:           0.9.6-py36_0      
    xz:               5.2.2-1           
    yaml:             0.1.6-0           
    zlib:             1.2.8-3           

Proceed ([y]/n)? y

jpeg-9b-0.tar. 100% |######################################| Time: 0:00:00   2.10 MB/s
yaml-0.1.6-0.t 100% |######################################| Time: 0:00:00   3.77 MB/s
python-3.6.1-2 100% |######################################| Time: 0:00:02   4.24 MB/s
cloudpickle-0. 100% |######################################| Time: 0:00:00   1.27 MB/s
decorator-4.0. 100% |######################################| Time: 0:00:00   5.29 MB/s
llvmlite-0.18. 100% |######################################| Time: 0:00:02   4.17 MB/s
locket-0.2.0-p 100% |######################################| Time: 0:00:00   1.61 MB/s
markupsafe-0.2 100% |######################################| Time: 0:00:00   4.32 MB/s
multipledispat 100% |######################################| Time: 0:00:00   7.42 MB/s
numpy-1.12.1-p 100% |######################################| Time: 0:00:01   3.51 MB/s
olefile-0.44-p 100% |######################################| Time: 0:00:00   7.07 MB/s
pytz-2017.2-py 100% |######################################| Time: 0:00:00   3.63 MB/s
pyyaml-3.12-py 100% |######################################| Time: 0:00:00   5.61 MB/s
requests-2.14. 100% |######################################| Time: 0:00:00   3.93 MB/s
setuptools-27. 100% |######################################| Time: 0:00:00   4.20 MB/s
six-1.10.0-py3 100% |######################################| Time: 0:00:00   6.22 MB/s
toolz-0.8.2-py 100% |######################################| Time: 0:00:00   8.97 MB/s
tornado-4.5.1- 100% |######################################| Time: 0:00:00   1.26 MB/s
wheel-0.29.0-p 100% |######################################| Time: 0:00:00   6.08 MB/s
jinja2-2.9.6-p 100% |######################################| Time: 0:00:00   3.95 MB/s
networkx-1.11- 100% |######################################| Time: 0:00:00   4.14 MB/s
numba-0.33.0-n 100% |######################################| Time: 0:00:00   3.25 MB/s
partd-0.3.8-py 100% |######################################| Time: 0:00:00  16.99 MB/s
pillow-4.1.1-p 100% |######################################| Time: 0:00:00   5.47 MB/s
pip-9.0.1-py36 100% |######################################| Time: 0:00:00   2.98 MB/s
python-dateuti 100% |######################################| Time: 0:00:00   3.93 MB/s
bokeh-0.12.4-p 100% |######################################| Time: 0:00:01   3.28 MB/s
pandas-0.20.2- 100% |######################################| Time: 0:00:03   3.16 MB/s
dask-0.15.0-py 100% |######################################| Time: 0:00:00   3.25 MB/s
xarray-0.9.6-p 100% |######################################| Time: 0:00:00   5.11 MB/s
datashader-0.4 100% |######################################| Time: 0:00:00  23.93 MB/s
(testing123) $ python -c "import datashader; print(datashader.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'datashader'
(testing123) $ which python
/Users/cball/Eunectes/mc3/envs/testing123/bin/python
(testing123) $ echo $PYTHONPATH

(testing123) $ echo $PATH
/Users/cball/Eunectes/mc3/envs/testing123/bin:/Users/cball/Eunectes/mc3/bin:/Users/cball/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9:/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9
(testing123) $ source deactivate
$ source activate testing123
(testing123) $ python -c "import datashader; print(datashader.__file__)"
/Users/cball/Eunectes/mc3/envs/testing123/lib/python3.6/site-packages/odo/backends/pandas.py:94: FutureWarning: pandas.tslib is deprecated and will be removed in a future version.
You can access NaTType as type(pandas.NaT)
  @convert.register((pd.Timestamp, pd.Timedelta), (pd.tslib.NaTType, type(None)))
/Users/cball/Eunectes/mc3/envs/testing123/lib/python3.6/site-packages/datashader/__init__.py
(testing123) $ echo $PATH
/Users/cball/Eunectes/mc3/envs/testing123/bin:/Users/cball/Eunectes/mc3/bin:/Users/cball/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Emacs.app/Contents/MacOS/bin-x86_64-10_9:/Applications/Emacs.app/Contents/MacOS/libexec-x86_64-10_9
```

**Comment by nehaljwani** [comment]
Possible duplicate of #5292

**Comment by ceball** [comment]
So if I upgrade to conda 4.4, I might stop getting this problem?

By the way, in case it's relevant, I'm using bash inside an emacs shell buffer:
```
$ echo $0
/bin/bash
$ echo $INSIDE_EMACS
25.2.1,comint
```

**Comment by nehaljwani** [comment]
IIUC, with conda 4.4, you won't have to re-activate the environment, if a package required re-activating. 

But... looking at your output again, you might be actually facing this: https://conda.io/docs/troubleshooting.html#resolution-reactivate-the-environment-or-run-hash-r-in-bash-or-rehash-in-zsh

**Comment by ceball** [comment]
Thanks @nehaljwani, it does appear that https://conda.io/docs/user-guide/troubleshooting.html#shell-commands-open-from-the-wrong-location is the answer! I waited for the problem to recur and verified it's the issue.
