### ISSUE TITLE
Could not find the AT 10.0 runtime

### ISSUE THREAD

**Issue by Anmeci** [conda/conda#5584]
overtaking stderr and stdout

stderr and stdout yielding back

Current conda install:

               platform : linux-ppc64le
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /opt/databiology/apps/miniconda2  (writable)
    default environment : /opt/databiology/apps/miniconda2
       envs directories : /opt/databiology/apps/miniconda2/envs
                          /root/.conda/envs
          package cache : /opt/databiology/apps/miniconda2/pkgs
                          /root/.conda/pkgs
           channel URLs : https://conda.anaconda.org/biobuilds/linux-ppc64le
                          https://conda.anaconda.org/biobuilds/noarch
                          https://repo.continuum.io/pkgs/free/linux-ppc64le
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-ppc64le
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-ppc64le
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.13.0 CPython/2.7.13 Linux/4.4.0-79-generic debian/stretch/sid glibc/2.23
                UID:GID : 0:0

`$ /opt/databiology/apps/miniconda2/bin/conda create -q -v -c biobuilds -n databiology-tools biobuilds-opt pysam -y`

    Traceback (most recent call last):
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 800, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/opt/databiology/apps/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 295, in execute
        rollback_excs,
    CondaMultiError: post-link script failed for package biobuilds::ibm-at-runtime-10.0-1
    running your command again with `-v` will provide additional information
    location of failed script: /opt/databiology/apps/miniconda2/envs/databiology-tools/bin/.ibm-at-runtime-post-link.sh
    ==> script messages <==
    *** FATAL: Could not find the AT 10.0 runtime.

**Comment by kalefranz** [comment]
Closing per https://github.com/biobuilds/biobuilds/issues/13
