### ISSUE TITLE
ｉｓｓｕｅｓ　ｉｎｓｔａｌｌｉｎｇ　ｐｙｔｏｒｃｈ

### ISSUE THREAD

**Issue by aky15** [conda/conda#5592]
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/aky15/下载/NewDisk/anaconda3  (writable)
    default environment : /home/aky15/下载/NewDisk/anaconda3
       envs directories : /home/aky15/下载/NewDisk/anaconda3/envs
                          /home/aky15/.conda/envs
          package cache : /home/aky15/下载/NewDisk/anaconda3/pkgs
                          /home/aky15/.conda/pkgs
           channel URLs : https://conda.anaconda.org/soumith/linux-64
                          https://conda.anaconda.org/soumith/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/aky15/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-81-generic debian/jessie/sid glibc/2.19    
                UID:GID : 1000:1000

`$ /home/aky15/下载/NewDisk/anaconda3/bin/conda install pytorch torchvision -c soumith`

    Traceback (most recent call last):
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/home/aky15/下载/NewDisk/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 469, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/aky15/下载/NewDisk/anaconda3/pkgs/cache/252c32c9.json'

**Comment by aky15** [comment]
thank you @nehaljwani ,it solves my problem perfectly
