### ISSUE TITLE
Unable to create conda environment for tensorflow-gpu 

### ISSUE THREAD

**Issue by venkatvi** [conda/conda#5596]
**yml specification is:** 

name: carnd-term1-gpu
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.2
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - eventlet
    - flask-socketio
    - seaborn
    - pandas
    - ffmpeg
    - imageio=2.1.2
    - pyqt=4.11.4
    - pip:
        - moviepy
        - https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow_gpu-0.12.1-cp35-cp35m-linux_x86_64.whl
        - keras==1.2.1

**Error message**
conda env create -f environment-gpu.yml
Fetching package metadata ...............
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Miniconda3  (writable)
    default environment : C:\ProgramData\Miniconda3
       envs directories : C:\ProgramData\Miniconda3\envs
                          C:\Users\Arvin\AppData\Local\conda\conda\envs
                          C:\Users\Arvin\.conda\envs
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\Arvin\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/menpo/win-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Arvin\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393
          administrator : True

`$ C:\ProgramData\Miniconda3\Scripts\conda-env-script.py create -f environment-gpu.yml`

    Traceback (most recent call last):
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\cli\main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda_env\installers\conda.py", line 37, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\plan.py", line 828, in execute_actions
        plan = plan_from_actions(actions, index)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\plan.py", line 338, in plan_from_actions
        plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\plan.py", line 302, in inject_UNLINKLINKTRANSACTION
        pfe.prepare()
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 469, in prepare
        for dist in self.link_dists)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 469, in <genexpr>
        for dist in self.link_dists)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 392, in make_actions_for_dist
        key=lambda pce: pce and pce.is_extracted and pce.tarball_matches_md5_if(md5)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\_vendor\auxlib\collection.py", line 88, in first
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\_vendor\auxlib\collection.py", line 88, in <genexpr>
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 392, in <lambda>
        key=lambda pce: pce and pce.is_extracted and pce.tarball_matches_md5_if(md5)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 106, in tarball_matches_md5_if
        return not md5sum or self.md5sum == md5sum
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 114, in md5sum
        return self._calculate_md5sum() if self.is_fetched else None
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\_vendor\auxlib\decorators.py", line 137, in _wrapper
        result = method(self, *args, **kwargs)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\core\package_cache.py", line 122, in _calculate_md5sum
        return compute_md5sum(self.package_tarball_full_path)
      File "C:\ProgramData\Miniconda3\lib\site-packages\conda\gateways\disk\read.py", line 63, in compute_md5sum
        for chunk in iter(partial(fh.read, 8192), b''):
    PermissionError: [Errno 13] Permission denied

**Comment by kalefranz** [comment]
Were you able to solve your problem here?
