### ISSUE TITLE
pyserial Installation fails

### ISSUE THREAD

**Issue by mpustie** [conda/conda#5606]
C:\Users\mpustie\Documents\LocoDrone>conda install pyserial
Fetching package metadata ...SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
.SSL verification error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)
.
Solving package specifications: ..........
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-env-2.5.1-py35_0.tar.bz2
  - http://bremen/pkgs/free::conda-env-2.5.1-py35_0.tar.bz2

Package plan for installation in environment C:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pyserial-2.7               |           py35_0          45 KB

The following NEW packages will be INSTALLED:

    pyserial: 2.7-py35_0

Proceed ([y]/n)? y

Fetching packages ...
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 595, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda3\lib\site-packages\conda\fetch.py", line 369, in download
    with Locked(dst_dir):
  File "C:\Anaconda3\lib\site-packages\conda\lock.py", line 60, in __enter__
    os.makedirs(self.lock_path)
  File "C:\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Anaconda3\lib\os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "C:\Anaconda3\lib\os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Anaconda3\\pkgs\\http:'

C:\Users\mpustie\Documents\LocoDrone>
:\Users\mpustie\Documents\LocoDrone>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.4
    conda-env version : 2.5.1
  conda-build version : 1.21.2
       python version : 3.5.1.final.0
     requests version : 2.10.0
     root environment : C:\Anaconda3  (writable)
  default environment : C:\Anaconda3
     envs directories : C:\Anaconda3\envs
        package cache : C:\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

C:\Users\mpustie\Documents\LocoDrone>

**Comment by tyler-thetyrant** [comment]
I didn't have any problem installing pyserial on win64 with the most recent version of conda, 4.3.22.
Please update your conda/anaconda by re-installing it (as it it very old).
