### ISSUE TITLE
Failed build of conda when specifying anaconca=1.8

### ISSUE THREAD

**Issue by thomascramer** [conda/conda#561]
As we have some dependencies that keep us from using anaconda 1.9 just yet, we have modified our env to be built off of anaconda 1.8.  I know that there was fixes being done for panda 0.12.0, so not sure if something was just pushed out, but we have just started getting this error:

root@precise64:~# /opt/anaconda/bin/conda create -n tester anaconda=1.8.0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 192, in install
    force=args.force, only_names=only_names)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 242, in install_actions
    config.track_features):
  File "/opt/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 427, in solve
    return self.explicit(specs) or self.solve2(specs, features)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 283, in solve2
    solutions = min_sat(clauses)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 147, in min_sat
    for sol in islice(pycosat.itersolve(clauses), max_n):
  File "/opt/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 239, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: pandas-0.12.0-np17py26_0.tar.bz2 MatchSpec(u'scipy 0.13.2')

root@precise64:~# conda info
Current conda install:

```
         platform : linux-64
    conda version : 3.0.3
 root environment : /opt/anaconda  (writable)
```

  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : False

**Comment by kalefranz** [comment]
Issue is for conda 3.0.3.  `conda update conda`
