### ISSUE TITLE
PyCall for Julia

### ISSUE THREAD

**Issue by jacob-roth** [conda/conda#5617]
I receive the following error tryping to build PyCall with Pkg.build("PyCall"). Can anyone please advise? Thanks

```
Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : C:\Users\Erin\.julia\v0.6\Conda\deps\usr  (writable)
    default environment : C:\Users\Erin\.julia\v0.6\Conda\deps\usr
       envs directories : C:\Users\Erin\.julia\v0.6\Conda\deps\usr\envs
                          C:\Users\Erin\AppData\Local\conda\conda\envs
                          C:\cygwin\home\Erin\.conda\envs
          package cache : C:\Users\Erin\.julia\v0.6\Conda\deps\usr\pkgs
                          C:\Users\Erin\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                          https://conda.anaconda.org/bioninja/win-64
                          https://conda.anaconda.org/bioninja/noarch
            config file : C:\Users\Erin\.julia\v0.6\Conda\deps\usr\condarc-julia.yml
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Users\Erin\.julia\v0.6\Conda\deps\usr\Scripts\conda-script.py install -y numpy`




    Traceback (most recent call last):
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\cli\install.py", line 227, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\core\index.py", line 108, in fetch_index
        stdoutlog.info("Fetching package metadata ...")
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\logging\__init__.py", line 1167, in info
        self._log(INFO, msg, args, **kwargs)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\logging\__init__.py", line 1286, in _log
        self.handle(record)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\logging\__init__.py", line 1296, in handle
        self.callHandlers(record)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\logging\__init__.py", line 1336, in callHandlers
        hdlr.handle(record)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\logging\__init__.py", line 759, in handle
        self.emit(record)
      File "C:\Users\Erin\.julia\v0.6\Conda\deps\usr\lib\site-packages\conda\console.py", line 154, in emit
        sys.stdout.write(record.msg)
    LookupError: unknown encoding: cp65001

=====================================[ ERROR: PyCall ]======================================

LoadError: failed process: Process(setenv(`'C:\Users\Erin\.julia\v0.6\Conda\deps\usr\Scripts\conda.exe' install -y numpy`,String["PATH=C:\\Julia-0.6.0\\bin;C:\\Julia-0.6.0\\bin;C:\\anaconda2;C:\\Julia-0.6.0\\bin;C:\\cygwin\\usr\\local\\bin;C:\\cygwin\\bin;C:\\Rtools\\bin;C:\\Rtools\\mingw_32\\bin;C:\\ProgramData\\Oracle\\Java\\javapath;C:\\Program Files (x86)\\Cuminas\\Document Express DjVu Plug-in;C:\\Program Files\\Common Files\\Microsoft Shared\\Windows Live;C:\\Program Files (x86)\\Common Files\\Microsoft Shared\\Windows Live;C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0;C:\\Program Files\\Dell\\Dell Wireless WLAN Card;C:\\Program Files (x86)\\Common Files\\Roxio Shared\\DLLShared;C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin;C:\\Program Files\\SlikSvn\\bin;C:\\Program Files\\nodejs;C:\\Program Files\\Anaconda2;C:\\Program Files\\Anaconda2\\Scripts;C:\\Program Files\\Anaconda2\\Library\\bin;C:\\Anaconda2;C:\\Anaconda2\\Scripts;C:\\Anaconda2\\Library\\bin;C:\\Program Files (x86)\\PuTTY;C:\\Users\\Erin\\Miniconda3;C:\\Users\\Erin\\Miniconda3\\Scripts;C:\\Users\\Erin\\Miniconda3\\Library\\bin;C:\\python 27 new;C:\\python 27 new\\Scripts;C:\\Users\\Erin\\AppData\\Roaming\\npm;C:\\cygwin\\lib\\lapack", "ORIGINAL_PATH=/cygdrive/c/Rtools/bin:/cygdrive/c/Rtools/mingw_32/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Cuminas/Document Express DjVu Plug-in:/cygdrive/c/Program Files/Common Files/Microsoft Shared/Windows Live:/cygdrive/c/Program Files (x86)/Common Files/Microsoft Shared/Windows Live:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Dell/Dell Wireless WLAN Card:/cygdrive/c/Program Files (x86)/Common Files/Roxio Shared/DLLShared:/cygdrive/c/Program Files (x86)/MiKTeX 2.9/miktex/bin:/cygdrive/c/Program Files/SlikSvn/bin:/cygdrive/c/Program Files/nodejs:/cygdrive/c/Program Files/Anaconda2:/cygdrive/c/Program Files/Anaconda2/Scripts:/cygdrive/c/Program Files/Anaconda2/Library/bin:/cygdrive/c/Anaconda2:/cygdrive/c/Anaconda2/Scripts:/cygdrive/c/Anaconda2/Library/bin:/cygdrive/c/Program Files (x86)/PuTTY:/cygdrive/c/Users/Erin/Miniconda3:/cygdrive/c/Users/Erin/Miniconda3/Scripts:/cygdrive/c/Users/Erin/Miniconda3/Library/bin:/cygdrive/c/python 27 new:/cygdrive/c/python 27 new/Scripts:/cygdrive/c/Users/Erin/AppData/Roaming/npm", "HOMEPATH=\\Users\\Erin", "ProgramData=C:\\ProgramData", "ProgramW6432=C:\\Program Files", "PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC", "SESSIONNAME=Console", "SYSTEMROOT=C:\\Windows", "APPDATA=C:\\Users\\Erin\\AppData\\Roaming", "PUBLIC=C:\\Users\\Public", "USERDOMAIN=Erin-PC", "OS=Windows_NT", "EXECIGNORE=*.dll", "PROCESSOR_REVISION=2502", "TMP=C:\\cygwin\\tmp", "GOOGLE_DEFAULT_CLIENT_ID=no", "COMSPEC=C:\\Windows\\system32\\cmd.exe", "PROFILEREAD=true", "USER=Erin", "PRINTER=tukey_203-204", "ALLUSERSPROFILE=C:\\ProgramData", "COMPUTERNAME=ERIN-PC", "FP_NO_HOST_CHECK=NO", "USERNAME=Erin", "CommonProgramFiles(x86)=C:\\Program Files (x86)\\Common Files", "SHELL=/bin/bash", "CONDARC=C:\\Users\\Erin\\.julia\\v0.6\\Conda\\deps\\usr\\condarc-julia.yml", "USERPROFILE=C:\\Users\\Erin", "GOOGLE_API_KEY=no", "PSModulePath=C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules\\", "PS1=\\[\\e]0;\\w\\a\\]\\n\\[\\e[32m\\]\\u@\\h \\[\\e[33m\\]\\w\\[\\e[0m\\]\\n\\\$ ", "PROCESSOR_LEVEL=6", "=C:=C:\\Users\\Erin\\.julia\\v0.6\\PyCall\\deps", "HOME=C:\\cygwin\\home\\Erin", "TEMP=C:\\cygwin\\tmp", "HOMEDRIVE=C:", "TERM=xterm", "HOSTNAME=Erin-PC", "WINDIR=C:\\Windows", "LOCALAPPDATA=C:\\Users\\Erin\\AppData\\Local", "VS120COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 12.0\\Common7\\Tools\\", "PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 37 Stepping 2, GenuineIntel", "NUMBER_OF_PROCESSORS=4", "TZ=America/Chicago", "GOOGLE_DEFAULT_CLIENT_SECRET=no", "=::=::\\", "LANG=en_US.UTF-8", "SHLVL=1", "VS140COMNTOOLS=C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Common7\\Tools\\", "OLDPWD=/", "INFOPATH=/usr/local/info:/usr/share/info:/usr/info", "_=/cygdrive/c/Julia-0.6.0/bin/julia", "CONDA_DEFAULT_ENV=C:\\Users\\Erin\\.julia\\v0.6\\Conda\\deps\\usr", "ProgramFiles(x86)=C:\\Program Files (x86)", "COMMONPROGRAMFILES=C:\\Program Files\\Common Files", "PWD=/cygdrive/c/Users/Erin/Google Drive/01. Current Classes/RESEARCH/DRSP/jake/code/cicc", "PROGRAMFILES=C:\\Program Files", "LOGONSERVER=\\\\ERIN-PC", "CONDA_PREFIX=C:\\Users\\Erin\\.julia\\v0.6\\Conda\\deps\\usr", "CommonProgramW6432=C:\\Program Files\\Common Files", "SYSTEMDRIVE=C:", "PROCESSOR_ARCHITECTURE=AMD64", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]
while loading C:\Users\Erin\.julia\v0.6\PyCall\deps\build.jl, in expression starting on line 258

============================================================================================

======================================[ BUILD ERRORS ]======================================

WARNING: PyCall had build errors.

 - packages with build errors remain installed in C:\Users\Erin\.julia\v0.6
 - build the package(s) and all dependencies with `Pkg.build("PyCall")`
 - build a single package by running its `deps/build.jl` script

============================================================================================


```

**Comment by mingwandroid** [comment]
This should be fixed now, please test via: `conda update qt`
