### ISSUE TITLE
Error when try to update anaconda

### ISSUE THREAD

**Issue by RdlP** [conda/conda#5618]
I run the following command

```
conda update anaconda
```

And I get the following output

```
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /home/angelluis/anaconda2:

The following NEW packages will be INSTALLED:

    anaconda-project:   0.6.0-py27_0      
    asn1crypto:         0.22.0-py27_0     
    bleach:             1.5.0-py27_0      
    distributed:        1.16.3-py27_0     
    html5lib:           0.999-py27_0      
    libtool:            2.4.2-0           
    msgpack-python:     0.4.8-py27_0      
    navigator-updater:  0.1.0-py27_0      
    olefile:            0.44-py27_0       
    packaging:          16.8-py27_0       
    pandocfilters:      1.4.1-py27_0      
    pango:              1.40.3-1          
    pyodbc:             4.0.16-py27_0     
    pywavelets:         0.5.2-np112py27_0 
    sortedcollections:  0.5.3-py27_0      
    sortedcontainers:   1.5.7-py27_0      
    tblib:              1.3.2-py27_0      
    testpath:           0.3-py27_0        
    unixodbc:           2.3.4-0           
    zict:               0.1.2-py27_0      

The following packages will be UPDATED:

    alabaster:          0.7.9-py27_0       --> 0.7.10-py27_0     
    anaconda:           4.3.0-np111py27_0  --> 4.4.0-np112py27_0 
    anaconda-client:    1.6.0-py27_0       --> 1.6.3-py27_0      
    anaconda-navigator: 1.4.3-py27_0       --> 1.6.2-py27_0      
    astropy:            1.3-np111py27_0    --> 1.3.2-np112py27_0 
    babel:              2.3.4-py27_0       --> 2.4.0-py27_0      
    beautifulsoup4:     4.5.3-py27_0       --> 4.6.0-py27_0      
    bokeh:              0.12.4-py27_0      --> 0.12.5-py27_1     
    boto:               2.45.0-py27_0      --> 2.46.1-py27_0     
    bottleneck:         1.2.0-np111py27_0  --> 1.2.1-np112py27_0 
    cffi:               1.9.1-py27_0       --> 1.10.0-py27_0     
    chardet:            2.3.0-py27_0       --> 3.0.3-py27_0      
    colorama:           0.3.7-py27_0       --> 0.3.9-py27_0      
    conda:              4.3.8-py27_0       --> 4.3.22-py27_0     
    contextlib2:        0.5.4-py27_0       --> 0.5.5-py27_0      
    cryptography:       1.7.1-py27_0       --> 1.8.1-py27_0      
    dask:               0.13.0-py27_0      --> 0.14.3-py27_1     
    entrypoints:        0.2.2-py27_0       --> 0.2.2-py27_1      
    flask:              0.12-py27_0        --> 0.12.2-py27_0     
    fontconfig:         2.12.1-2           --> 2.12.1-3          
    futures:            3.0.5-py27_0       --> 3.1.1-py27_0      
    greenlet:           0.4.11-py27_0      --> 0.4.12-py27_0     
    h5py:               2.6.0-np111py27_2  --> 2.7.0-np112py27_0 
    idna:               2.2-py27_0         --> 2.5-py27_0        
    ipykernel:          4.5.2-py27_0       --> 4.6.1-py27_0      
    ipython:            5.1.0-py27_0       --> 5.3.0-py27_0      
    ipython_genutils:   0.1.0-py27_0       --> 0.2.0-py27_0      
    ipywidgets:         5.2.2-py27_1       --> 6.0.0-py27_0      
    jedi:               0.9.0-py27_1       --> 0.10.2-py27_2     
    jinja2:             2.9.4-py27_0       --> 2.9.6-py27_0      
    jsonschema:         2.5.1-py27_0       --> 2.6.0-py27_0      
    jupyter_client:     4.4.0-py27_0       --> 5.0.1-py27_0      
    jupyter_console:    5.0.0-py27_0       --> 5.1.0-py27_0      
    jupyter_core:       4.2.1-py27_0       --> 4.3.0-py27_0      
    llvmlite:           0.15.0-py27_0      --> 0.18.0-py27_0     
    lxml:               3.7.2-py27_0       --> 3.7.3-py27_0      
    matplotlib:         2.0.0-np111py27_0  --> 2.0.2-np112py27_0 
    mistune:            0.7.3-py27_0       --> 0.7.4-py27_0      
    nbconvert:          4.2.0-py27_0       --> 5.1.1-py27_0      
    nbformat:           4.2.0-py27_0       --> 4.3.0-py27_0      
    nltk:               3.2.2-py27_0       --> 3.2.3-py27_0      
    notebook:           4.3.1-py27_0       --> 5.0.0-py27_0      
    numba:              0.30.1-np111py27_0 --> 0.33.0-np112py27_0
    numexpr:            2.6.1-np111py27_2  --> 2.6.2-np112py27_0 
    numpy:              1.11.3-py27_0      --> 1.12.1-py27_0     
    openpyxl:           2.4.1-py27_0       --> 2.4.7-py27_0      
    openssl:            1.0.2k-0           --> 1.0.2l-0          
    pandas:             0.19.2-np111py27_1 --> 0.20.1-np112py27_0
    partd:              0.3.7-py27_0       --> 0.3.8-py27_0      
    path.py:            10.0-py27_0        --> 10.3.1-py27_0     
    pathlib2:           2.2.0-py27_0       --> 2.2.1-py27_0      
    pillow:             4.0.0-py27_0       --> 4.1.1-py27_0      
    ply:                3.9-py27_0         --> 3.10-py27_0       
    prompt_toolkit:     1.0.9-py27_0       --> 1.0.14-py27_0     
    psutil:             5.0.1-py27_0       --> 5.2.2-py27_0      
    py:                 1.4.32-py27_0      --> 1.4.33-py27_0     
    pycosat:            0.6.1-py27_1       --> 0.6.2-py27_0      
    pycrypto:           2.6.1-py27_4       --> 2.6.1-py27_6      
    pygments:           2.1.3-py27_0       --> 2.2.0-py27_0      
    pyopenssl:          16.2.0-py27_0      --> 17.0.0-py27_0     
    pytables:           3.3.0-np111py27_0  --> 3.3.0-np112py27_0 
    pytest:             3.0.5-py27_0       --> 3.0.7-py27_0      
    pytz:               2016.10-py27_0     --> 2017.2-py27_0     
    qt:                 5.6.2-3            --> 5.6.2-4           
    qtawesome:          0.4.3-py27_0       --> 0.4.4-py27_0      
    qtconsole:          4.2.1-py27_1       --> 4.3.0-py27_0      
    requests:           2.12.4-py27_0      --> 2.14.2-py27_0     
    scandir:            1.4-py27_0         --> 1.5-py27_0        
    scikit-image:       0.12.3-np111py27_1 --> 0.13.0-np112py27_0
    scikit-learn:       0.18.1-np111py27_1 --> 0.18.1-np112py27_1
    scipy:              0.18.1-np111py27_1 --> 0.19.0-np112py27_0
    sphinx:             1.5.1-py27_0       --> 1.5.6-py27_0      
    spyder:             3.1.2-py27_0       --> 3.1.4-py27_0      
    sqlalchemy:         1.1.5-py27_0       --> 1.1.9-py27_0      
    statsmodels:        0.6.1-np111py27_1  --> 0.8.0-np112py27_0 
    tornado:            4.4.2-py27_0       --> 4.5.1-py27_0      
    traitlets:          4.3.1-py27_0       --> 4.3.2-py27_0      
    werkzeug:           0.11.15-py27_0     --> 0.12.2-py27_0     
    widgetsnbextension: 1.2.6-py27_0       --> 2.0.0-py27_0      
    wrapt:              1.10.8-py27_0      --> 1.10.10-py27_0    

Proceed ([y]/n)? 

alabaster-0.7. 100% |################################| Time: 0:00:00 223.06 kB/s
asn1crypto-0.2 100% |################################| Time: 0:00:00 164.57 kB/s
beautifulsoup4 100% |################################| Time: 0:00:00 388.81 kB/s
boto-2.46.1-py 100% |################################| Time: 0:00:10 142.88 kB/s
chardet-3.0.3- 100% |################################| Time: 0:00:00 323.79 kB/s
colorama-0.3.9 100% |################################| Time: 0:00:00 367.69 kB/s
contextlib2-0. 100% |################################| Time: 0:00:00 249.26 kB/s
futures-3.1.1- 100% |################################| Time: 0:00:00 288.84 kB/s
greenlet-0.4.1 100% |################################| Time: 0:00:00 186.11 kB/s
idna-2.5-py27_ 100% |################################| Time: 0:00:00 233.38 kB/s
ipython_genuti 100% |################################| Time: 0:00:00 255.85 kB/s
jedi-0.10.2-py 100% |################################| Time: 0:00:00 604.82 kB/s
mistune-0.7.4- 100% |################################| Time: 0:00:02 305.68 kB/s
msgpack-python 100% |################################| Time: 0:00:00 882.19 kB/s
numpy-1.12.1-p 100% |################################| Time: 0:00:17 399.63 kB/s
olefile-0.44-p 100% |################################| Time: 0:00:00 374.33 kB/s
pandocfilters- 100% |################################| Time: 0:00:00 982.91 kB/s
path.py-10.3.1 100% |################################| Time: 0:00:00  11.13 MB/s
ply-3.10-py27_ 100% |################################| Time: 0:00:00 886.62 kB/s
psutil-5.2.2-p 100% |################################| Time: 0:00:01 179.89 kB/s
py-1.4.33-py27 100% |################################| Time: 0:00:00   1.15 MB/s
pycosat-0.6.2- 100% |################################| Time: 0:00:03  56.02 kB/s
pycrypto-2.6.1 100% |################################| Time: 0:00:00 860.65 kB/s
pygments-2.2.0 100% |################################| Time: 0:00:04 334.96 kB/s
pyodbc-4.0.16- 100% |################################| Time: 0:00:00 950.97 kB/s
pytz-2017.2-py 100% |################################| Time: 0:00:00 462.46 kB/s
requests-2.14. 100% |################################| Time: 0:00:00   1.17 MB/s
scandir-1.5-py 100% |################################| Time: 0:00:00   2.63 MB/s
sortedcontaine 100% |################################| Time: 0:00:00   2.27 MB/s
sqlalchemy-1.1 100% |################################| Time: 0:00:01 953.03 kB/s
tblib-1.3.2-py 100% |################################| Time: 0:00:00   1.24 MB/s
werkzeug-0.12. 100% |################################| Time: 0:00:00   1.28 MB/s
wrapt-1.10.10- 100% |################################| Time: 0:00:00   2.97 MB/s
astropy-1.3.2- 100% |################################| Time: 0:00:12 722.86 kB/s
babel-2.4.0-py 100% |################################| Time: 0:00:09 542.38 kB/s
bottleneck-1.2 100% |################################| Time: 0:00:00 549.75 kB/s
cffi-1.10.0-py 100% |################################| Time: 0:00:00 658.99 kB/s
h5py-2.7.0-np1 100% |################################| Time: 0:00:05 469.13 kB/s
html5lib-0.999 100% |################################| Time: 0:00:00   1.61 MB/s
jinja2-2.9.6-p 100% |################################| Time: 0:00:00 495.07 kB/s
jsonschema-2.6 100% |################################| Time: 0:00:00   5.41 MB/s
llvmlite-0.18. 100% |################################| Time: 0:00:12 929.41 kB/s
lxml-3.7.3-py2 100% |################################| Time: 0:00:04 709.38 kB/s
nltk-3.2.3-py2 100% |################################| Time: 0:00:03 490.85 kB/s
numexpr-2.6.2- 100% |################################| Time: 0:00:00   1.18 MB/s
openpyxl-2.4.7 100% |################################| Time: 0:00:00   1.76 MB/s
packaging-16.8 100% |################################| Time: 0:00:00 798.29 kB/s
partd-0.3.8-py 100% |################################| Time: 0:00:00  10.64 MB/s
pathlib2-2.2.1 100% |################################| Time: 0:00:00   2.33 MB/s
pillow-4.1.1-p 100% |################################| Time: 0:00:00 930.78 kB/s
prompt_toolkit 100% |################################| Time: 0:00:00   1.82 MB/s
pytest-3.0.7-p 100% |################################| Time: 0:00:00   1.79 MB/s
pywavelets-0.5 100% |################################| Time: 0:00:05   1.02 MB/s
qtawesome-0.4. 100% |################################| Time: 0:00:00   1.51 MB/s
scipy-0.19.0-n 100% |################################| Time: 0:00:37 977.72 kB/s
sortedcollecti 100% |################################| Time: 0:00:00 703.72 kB/s
traitlets-4.3. 100% |################################| Time: 0:00:00   1.19 MB/s
zict-0.1.2-py2 100% |################################| Time: 0:00:00 585.76 kB/s
anaconda-clien 100% |################################| Time: 0:00:00   1.63 MB/s
bleach-1.5.0-p 100% |################################| Time: 0:00:00   2.84 MB/s
cryptography-1 100% |################################| Time: 0:00:00   1.16 MB/s
entrypoints-0. 100% |################################| Time: 0:00:00  19.80 MB/s
flask-0.12.2-p 100% |################################| Time: 0:00:00   1.75 MB/s
jupyter_core-4 100% |################################| Time: 0:00:00   1.38 MB/s
numba-0.33.0-n 100% |################################| Time: 0:00:02   1.13 MB/s
pandas-0.20.1- 100% |################################| Time: 0:00:16   1.24 MB/s
pytables-3.3.0 100% |################################| Time: 0:00:04   1.17 MB/s
scikit-learn-0 100% |################################| Time: 0:00:09   1.22 MB/s
sphinx-1.5.6-p 100% |################################| Time: 0:00:01   1.03 MB/s
testpath-0.3-p 100% |################################| Time: 0:00:00 658.53 kB/s
tornado-4.5.1- 100% |################################| Time: 0:00:00   1.22 MB/s
anaconda-proje 100% |################################| Time: 0:00:00   2.12 MB/s
bokeh-0.12.5-p 100% |################################| Time: 0:00:05 795.07 kB/s
ipython-5.3.0- 100% |################################| Time: 0:00:00   1.08 MB/s
jupyter_client 100% |################################| Time: 0:00:00   4.26 MB/s
nbformat-4.3.0 100% |################################| Time: 0:00:00   2.81 MB/s
pyopenssl-17.0 100% |################################| Time: 0:00:00   1.66 MB/s
statsmodels-0. 100% |################################| Time: 0:00:06   1.11 MB/s
conda-4.3.22-p 100% |################################| Time: 0:00:00   1.24 MB/s
dask-0.14.3-py 100% |################################| Time: 0:00:00   1.28 MB/s
ipykernel-4.6. 100% |################################| Time: 0:00:00   1.60 MB/s
nbconvert-5.1. 100% |################################| Time: 0:00:00   1.58 MB/s
anaconda-navig 100% |################################| Time: 0:00:03   1.05 MB/s
distributed-1. 100% |################################| Time: 0:00:00   1.02 MB/s
jupyter_consol 100% |################################| Time: 0:00:00  13.51 MB/s
matplotlib-2.0 100% |################################| Time: 0:00:13 816.62 kB/s
navigator-upda 100% |################################| Time: 0:00:02 570.64 kB/s
notebook-5.0.0 100% |################################| Time: 0:00:04   1.16 MB/s
qtconsole-4.3. 100% |################################| Time: 0:00:00   1.53 MB/s
scikit-image-0 100% |################################| Time: 0:00:41 800.39 kB/s
spyder-3.1.4-p 100% |################################| Time: 0:00:02   1.10 MB/s
widgetsnbexten 100% |################################| Time: 0:00:00 959.44 kB/s
ipywidgets-6.0 100% |################################| Time: 0:00:00   1.16 MB/s
anaconda-4.4.0 100% |################################| Time: 0:00:00   6.76 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/angelluis/anaconda2  (writable)
    default environment : /home/angelluis/anaconda2
       envs directories : /home/angelluis/anaconda2/envs
          package cache : /home/angelluis/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/3.19.0-51-generic debian/jessie/sid glibc/2.21
                UID:GID : 1000:1000



`$ /home/angelluis/anaconda2/bin/conda update anaconda`




    Traceback (most recent call last):
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 71, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/home/angelluis/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 94, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'/home/angelluis/anaconda2/pkgs/qt-5.6.2-4/info/index.json'
```

**Comment by kalefranz** [comment]
conda clean --packages --tarballs
