### ISSUE TITLE
conda env create: misleading error

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#5621]
```
(root) nwani@somemachine:~/conda$ conda env create -f /path/to/misplaced/or/missing/env.yaml -vvv
DEBUG conda.gateways.logging:set_verbosity(148): verbosity set to 3
Using Anaconda Cloud api site https://api.anaconda.org
DEBUG binstar:load_token(140): Found login token: /home/ubuntu/.config/binstar/https%3A%2F%2Fapi.anaconda.org.token
Traceback (most recent call last):
  File "/home/ubuntu/condaexpts/m3/lib/python3.5/site-packages/conda-4.3.22.post1039+347b8e5-py3.5.egg/conda/exceptions.py", line 646, in __call__
    return func(*args, **kwargs)
  File "/home/ubuntu/condaexpts/m3/lib/python3.5/site-packages/conda-4.3.22.post1039+347b8e5-py3.5.egg/conda_env/cli/main_create.py", line 79, in execute
    directory=os.getcwd())
  File "/home/ubuntu/condaexpts/m3/lib/python3.5/site-packages/conda-4.3.22.post1039+347b8e5-py3.5.egg/conda_env/specs/__init__.py", line 23, in detect
    raise SpecNotFound(build_message(specs))
conda_env.exceptions.SpecNotFound: Can't process without a name
```

IIUC, the function [build_message()](https://github.com/conda/conda/blob/master/conda_env/specs/__init__.py#L26-L31) gives precedence to binstar spec and over others, which is why this happens.

**Comment by kalefranz** [comment]
Closing in lieu of #5681
