### ISSUE TITLE
Problem: conda install --file <filename> doesn't work

### ISSUE THREAD

**Issue by gabm** [conda/conda#5625]
When I want to install a package from a file using `conda install --file <filename>` i get:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.15
         python version : 3.5.3.final.0
       requests version : 2.14.2
       root environment : /home/gabm/miniconda3  (writable)
    default environment : /home/gabm/miniconda3
       envs directories : /home/gabm/miniconda3/envs
                          /home/gabm/.conda/envs
          package cache : /home/gabm/miniconda3/pkgs
                          /home/gabm/.conda/pkgs
           channel URLs : 
                    ....
            config file : /home/gabm/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.5.3 Linux/4.11.6-3-ARCH arch/ glibc/2.25    
                UID:GID : 1000:1000

`$ /home/gabm/miniconda3/bin/conda install --file ld-data-protobuf-23-396c7f1_gcc540.tar.bz2`




    Traceback (most recent call last):
      File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 185, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "/home/gabm/miniconda3/lib/python3.5/site-packages/conda/cli/common.py", line 550, in specs_from_url
        for line in open(path):
      File "/home/gabm/miniconda3/lib/python3.5/codecs.py", line 321, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 11: invalid start byte
```

I'm using conda 4.3.22

**Comment by gabm** [comment]
I seems the file gets installed (or at least entered to the database) anyway. When I copy the file into the local package repo (conda-bld/linux-64/) and use `conda update <pkg-name> --use-local` I get:

```
$ conda update <pkg-name> --use-local
Fetching package metadata .....................
Solving package specifications: .

Package plan for installation in environment /home/gabm/miniconda3:

The following packages will be SUPERSEDED by a higher-priority channel:

    <pkg-name>: 23-396c7f1_gcc540 file:///tmp [gcc540] --> 23-396c7f1_gcc540 local [gcc540]

Proceed ([y]/n)? 
```

**Comment by kalefranz** [comment]
`conda install ld-data-protobuf-23-396c7f1_gcc540.tar.bz2` should have worked.  The `--file` flag is for a requirements.txt-like file created from `conda list --export`.

**Comment by govergar** [comment]
I have the exatly the same problem
Did you find any solution?
