### ISSUE TITLE
An unexpected error

### ISSUE THREAD

**Issue by wu87tong** [conda/conda#5631]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 176,
 in main
    return handle_exception(e)
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 62
6, in handle_exception
    print_unexpected_error_message(e)
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 58
8, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_info.py", line
 162, in get_info_dict
    from ..connection import user_agent
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\connection.py", line 12
, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\__init__.py", line 5
2, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\ProgramData\Anaconda2\lib\site-packages\requests\packages\urllib3\con
trib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\__init__.py
", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\base.py", l
ine 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\extensions.
py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22,
 in <module>
    from ._elliptic_curve import (
  File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py
", line 51, in <module>
    from ._int import inverse_mod
  File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56,
 in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_cty
pes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\ProgramData\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\ProgramData\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xca in position 23: ordinal
 not in range(128)

C:\Users\WT>

**Comment by lf131410133** [comment]
solve?

**Comment by 414216191** [comment]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 1: ordinal
not in range(128)UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 1: ordinal
not in range(128)

If you solve this problem, please tell me and I'll be very appreciate.

**Comment by wu87tong** [comment]
not yet

**Comment by JihadFenix** [comment]
I suspect this has sth to do with 汉字 in system path

**Comment by wangyu190810** [comment]
command:

     conda create -n py3 

     actiavte py3 

     conda install python=2.7

this  install end, 

command:

  conda info 

this error will come

**Comment by mingwandroid** [comment]
Python 2 is fundamentally incapable of dealing with any non-ascii on `PATH` or in the install location of Python. Python 3 is better but some other things in the Anaconda Distribution cannot handle non-ascii well.

I spent a lot of time trying to make this work as best we could but in the end it is currently not possible.

**Comment by kalefranz** [comment]
see https://github.com/conda/conda/issues/6650
