### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by hasanfares** [conda/conda#5633]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda issue tracker

Main Error

psutil.AccessDenied (pid=3572)
Traceback

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 620, in wrapper
    return fun(self, *args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 690, in cmdline
    ret = cext.proc_cmdline(self.pid)
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 108, in start_app
    if misc.load_pid() is None:  # A stale lock might be around
  File "C:\ProgramData\Anaconda3\lib\site-packages\anaconda_navigator\utils\misc.py", line 384, in load_pid
    cmds = process.cmdline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\__init__.py", line 701, in cmdline
    return self._proc.cmdline()
  File "C:\ProgramData\Anaconda3\lib\site-packages\psutil\_pswindows.py", line 623, in wrapper
    raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=3572)

**Comment by goanpeca** [comment]
@hasanfares please open a terminal/anaconda prompt and type

`$ anaconda-navigator --reset`

Also, I advice you to install Anaconda Distribution for local/current user only and not all users
