### ISSUE TITLE
MemoryError on secure RHEL 7.3 server running Python 3.6.1

### ISSUE THREAD

**Issue by JeremyEnns** [conda/conda#5638]
RHEL 7 Server is running with pretty much all of the standard CIS security hardened settings. 

There are three accounts on the webserver. My user account, root, and the account that will run the web application, "app_acc". They installed it using sudo from the user account into /usr/lib/miniconda3
Conda works from the root and the user account, but not in the app_acc account .

```
[root@app_acc ~]# conda info
Current conda install:

platform : linux-64
conda version : 4.3.22
conda is private : False
conda-env version : 4.3.22
conda-build version : not installed
python version : 3.6.1.final.0
requests version : 2.14.2
root environment : /usr/lib/miniconda3 (writable)
default environment : /usr/lib/miniconda3
envs directories : /usr/lib/miniconda3/envs
/root/.conda/envs
package cache : /usr/lib/miniconda3/pkgs
/root/.conda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/linux-64
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/linux-64
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/linux-64
https://repo.continuum.io/pkgs/pro/noarch
config file : None
netrc file : None
offline mode : False
user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-514.21.2.el7.x86_64 Red Hat Enterprise Linux Server/7.3 glibc/2.17
UID:GID : 0:0

[user_acc@app_acc ~]$ conda info
Current conda install:

platform : linux-64
conda version : 4.3.22
conda is private : False
conda-env version : 4.3.22
conda-build version : not installed
python version : 3.6.1.final.0
requests version : 2.14.2
root environment : /usr/lib/miniconda3 (read only)
default environment : /usr/lib/miniconda3
envs directories : /home/user_acc/.conda/envs
/usr/lib/miniconda3/envs
package cache : /usr/lib/miniconda3/pkgs
/home/user_acc/.conda/pkgs
channel URLs : https://repo.continuum.io/pkgs/free/linux-64
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/linux-64
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/linux-64
https://repo.continuum.io/pkgs/pro/noarch
config file : None
netrc file : None
offline mode : False
user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-514.21.2.el7.x86_64 Red Hat Enterprise Linux Server/7.3 glibc/2.17
UID:GID : 1001:1001


--app_acc account --


[app_acc@app_acc pkgs]$ conda info
[app_acc@app_acc pkgs]$ which conda
/usr/lib/miniconda3/bin/conda
[app_acc@app_acc pkgs]$ conda list
Traceback (most recent call last):
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
return_value = func(*args, **kwargs)
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 111, in _main
imported = importlib.import_module(module)
File "/usr/lib/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 978, in _gcd_import
File "<frozen importlib._bootstrap>", line 961, in _find_and_load
File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 678, in exec_module
File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
from .install import install
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
from ..core.index import get_index
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
from .package_cache import PackageCache
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 10, in <module>
from .path_actions import CacheUrlAction, ExtractPackageAction
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
from ..gateways.download import download
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
File "/usr/lib/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 52, in <module>
from .packages.urllib3.contrib import pyopenssl
File "/usr/lib/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
from cryptography import x509
File "/usr/lib/miniconda3/lib/python3.6/site-packages/cryptography/x509/__init__.py", line 7, in <module>
from cryptography.x509.base import (
File "/usr/lib/miniconda3/lib/python3.6/site-packages/cryptography/x509/base.py", line 16, in <module>
from cryptography.x509.extensions import Extension, ExtensionType
File "/usr/lib/miniconda3/lib/python3.6/site-packages/cryptography/x509/extensions.py", line 14, in <module>
from asn1crypto.keys import PublicKeyInfo
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/keys.py", line 22, in <module>
from ._elliptic_curve import (
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
from ._int import inverse_mod
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/_int.py", line 43, in <module>
from ._ffi import (
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/_ffi.py", line 15, in <module>
from ctypes import create_string_buffer
File "/usr/lib/miniconda3/lib/python3.6/ctypes/__init__.py", line 538, in <module>
_reset_cache()
File "/usr/lib/miniconda3/lib/python3.6/ctypes/__init__.py", line 273, in _reset_cache
CFUNCTYPE(c_int)(lambda: None)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/miniconda3/bin/conda", line 6, in <module>
sys.exit(conda.cli.main())
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 179, in main
return conda_exception_handler(_main, *args)
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 636, in conda_exception_handler
return handle_exception(e)
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 626, in handle_exception
print_unexpected_error_message(e)
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 588, in print_unexpected_error_message
stderrlogger.info(get_main_info_str(get_info_dict()))
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
from ..connection import user_agent
File "/usr/lib/miniconda3/lib/python3.6/site-packages/conda/connection.py", line 12, in <module>
from requests import Session, __version__ as REQUESTS_VERSION
File "/usr/lib/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 52, in <module>
from .packages.urllib3.contrib import pyopenssl
File "/usr/lib/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
from cryptography import x509
File "/usr/lib/miniconda3/lib/python3.6/site-packages/cryptography/x509/__init__.py", line 7, in <module>
from cryptography.x509.base import (
File "/usr/lib/miniconda3/lib/python3.6/site-packages/cryptography/x509/base.py", line 16, in <module>
from cryptography.x509.extensions import Extension, ExtensionType
File "/usr/lib/miniconda3/lib/python3.6/site-packages/cryptography/x509/extensions.py", line 14, in <module>
from asn1crypto.keys import PublicKeyInfo
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/keys.py", line 22, in <module>
from ._elliptic_curve import (
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
from ._int import inverse_mod
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/_int.py", line 43, in <module>
from ._ffi import (
File "/usr/lib/miniconda3/lib/python3.6/site-packages/asn1crypto/_ffi.py", line 15, in <module>
from ctypes import create_string_buffer
File "/usr/lib/miniconda3/lib/python3.6/ctypes/__init__.py", line 538, in <module>
_reset_cache()
File "/usr/lib/miniconda3/lib/python3.6/ctypes/__init__.py", line 273, in _reset_cache
CFUNCTYPE(c_int)(lambda: None)
MemoryError
```

The conda crash issue ONLY occurs, when you "su - <account>" to the app_acc account.
This did NOT occur with our previous anaconda3 version (Python 3.5.3 :: Anaconda 4.4.0 (64-bit))
It is important to "su" to the primary account, which will be running all the python code, because that account is being used like a service/daemon account.

Through a lot of different attempts, we found some strange behavior.
If we set a password on the app_acc account AND login to that account directly (it works).
AND, Sudo su - <account>, now also works.

Further, if we lock the account (passwd -l <account>), this breaks the sudo su - <account> functionality. It is as if, Anaconda refuses to run, if the account is locked, which makes no sense.
It worked with the older version of Anaconda Python, but not this version (3.6.1.final.0).

CIS advises that it is the best practice that /tmp is mounted with the noexec set. Apparently, conda is trying to save things and execute it from /tmp. This goes against best practice

**Comment by JeremyEnns** [comment]
I think we found the issue in one of the base python libraries. This issue occurs in the `libffi` library it has a set of hard coded locations to try and execute code in. `libffi` needs somewhere on the disk with exec permissions to write temporary files to that it uses to load c-libraries.

This is the order it checks:

```
{ open_temp_exec_file_env, "TMPDIR", 0 },
{ open_temp_exec_file_dir, "/tmp", 0 },
{ open_temp_exec_file_dir, "/var/tmp", 0 },
{ open_temp_exec_file_dir, "/dev/shm", 0 },
{ open_temp_exec_file_env, "HOME", 0 },
```
https://github.com/libffi/libffi/blob/master/src/closures.c

So we are thinking if you change the environment variable $TMPDIR to a place that is mounted in exec mode it could fix the problem as it would no longer attempt to try and run in /tmp or /var/tmp which are locked down in C2S

This assumes that ctypes doesn't do something to "reassign" TMPDIR before `libffi` has a chance to use it.

**Comment by kalefranz** [comment]
@JeremyEnns Has this issue been resolved?

**Comment by pjona** [comment]
In my case this helped: `setsebool -P httpd_tmp_exec 1`
