### ISSUE TITLE
conda-index: tarfile.ReadError: file could not be opened successfully

### ISSUE THREAD

**Issue by yonasl** [conda/conda#5639]
Hello, 

Raised the following on Stackoverflow but this may be a bette rplace for people to look for an answer ([https://stackoverflow.com/questions/44910994/conda-index-tarfile-readerror](https://stackoverflow.com/questions/44910994/conda-index-tarfile-readerror)).

I basically get an error when trying to run "`conda index`" on a folder. Conda install and other variants work fine and I have correctly installed conda-build. I wonder if the error message needs more detail or this is failing because I am running it from the Powershell with no admin rights:

An example of error message (more on the link):

```
PS C:\Miniconda\Scripts> .\conda-index .\free\win-64
updating index in: C:\Miniconda\Scripts\free\win-64
updating: conda-build-2.1.12-py36_0.tar.bz2
updating: ._webtest-2.0.23-py36_0.tar.bz2
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-index-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_index.main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_index.py", line 66, in main
    return execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_index.py", line 62, in execute
    check_md5=args.check_md5, remove=args.remove)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 301, in update_index
    update_index(path, config, force=force, check_md5=check_md5, remove=remove)
  File "C:\Miniconda\lib\site-packages\conda_build\index.py", line 107, in update_index
    d = read_index_tar(path, config, lock=lock)
  File "C:\Miniconda\lib\site-packages\conda_build\index.py", line 23, in read_index_tar
    with tarfile.open(tar_path) as t:
  File "C:\Miniconda\lib\tarfile.py", line 1573, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```

**Comment by nehaljwani** [comment]
Seems like a corrupt tarball to me. Find out which one it is and then try downloading it again and attempt re-index thereafter?

**Comment by yonasl** [comment]
Notice the first two lines:

```
updating: conda-build-2.1.12-py36_0.tar.bz2
updating: ._webtest-2.0.23-py36_0.tar.bz2
...error...
```

This makes total sense, there is no `._webtest...` file on the folder. However, there is a `webtest-2.0.23...` present. I just don't know why the script adds the `._` in front causing the issue:

```
PS C:\Miniconda\Scripts\free\win-64> dir web*

    Directory: C:\Miniconda\Scripts\free\win-64

Mode                LastWriteTime     Length Name
----                -------------     ------ ----
-a---        31/01/2017     05:00     121880 webob-1.6.1-py36_0.tar.bz2
-a---        31/01/2017     05:00      55005 webtest-2.0.23-py36_0.tar.bz2
```

**Comment by nehaljwani** [comment]
I am not able to reproduce this. What version of conda-build are you using?
```powershell
PS C:\m264\envs\2099> conda build --version
conda-build 2.1.17

PS C:\m264\envs\2099> dir .\win-64\


    Directory: C:\m264\envs\2099\win-64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         7/5/2017  12:58 PM          55005 webtest-2.0.23-py36_0.tar.bz2


PS C:\m264\envs\2099> C:\m264\Scripts\conda-index.exe .\win-64\
updating index in: C:\m264\envs\2099\win-64
updating: webtest-2.0.23-py36_0.tar.bz2
```

**Comment by yonasl** [comment]
I am on version 2.1.15, cannot believe that makes a difference.

I tried the following: 

- Created a new folder and downloaded a single .tar.bz2 package from the repo.conda.io website. Ran conda index and it worked correctly. 

- Then reran conda index on the original directory:

```
PS C:\Miniconda\Scripts> .\conda index .\free\win-64
updating index in: C:\Miniconda\Scripts\free\win-64
updating: ._spyder-3.1.3-py36_0.tar.bz2
Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-index-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_index.main())
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_index.py", line 66, in main
    return execute(sys.argv[1:])
  File "C:\Miniconda\lib\site-packages\conda_build\cli\main_index.py", line 62, in execute
    check_md5=args.check_md5, remove=args.remove)
  File "C:\Miniconda\lib\site-packages\conda_build\api.py", line 301, in update_index
    update_index(path, config, force=force, check_md5=check_md5, remove=remove)
  File "C:\Miniconda\lib\site-packages\conda_build\index.py", line 107, in update_index
    d = read_index_tar(path, config, lock=lock)
  File "C:\Miniconda\lib\site-packages\conda_build\index.py", line 23, in read_index_tar
    with tarfile.open(tar_path) as t:
  File "C:\Miniconda\lib\tarfile.py", line 1573, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully
```
- I took the spyder-3.1.3-py36_0.tar.bz2 and moved it to an empty folder and ran
```

PS C:\Miniconda\Scripts> .\conda index .\free\win-64-2
updating index in: C:\Miniconda\Scripts\free\win-64-2
updating: spyder-3.1.3-py36_0.tar.bz2
```

This ran correctly!

**Comment by nehaljwani** [comment]
Inside the folder `C:\Miniconda\Scripts\free\win-64`, try typing `dir /a` instead of just `dir` . I suspect that the files starting with `._` are hidden files which `dir` won't show by default.

**Comment by yonasl** [comment]
That's correct! Whoever created the folder for me added a bunch of corrupted hidden files. This solved the issue!
