### ISSUE TITLE
conda fails to install or update

### ISSUE THREAD

**Issue by flbahr** [conda/conda#5644]
I tried to follow some suggestions after I was getting a 403 error to install basemap
the suggestion was to install conda-canary but not I can't seem to get anything.  The URLS look like they are missing the prefix.  I thought I had other channels.    Any help would be appreciated.

Current conda install:

platform : linux-64
conda version : 2.0.0
 root environment : /home/matlab/anaconda  (writable)
 default environment : /home/matlab/anaconda
 envs directories : /home/matlab/anaconda/envs
 package cache : /home/matlab/anaconda/pkgs
 channel URLs : conda-canary/linux-64/
  conda-canary/linux-64/
   conda-canary/linux-64/
   config file : /home/matlab/.condarc

 conda update anaconda
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/ContinuumIO/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/home/matlab/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 177, in main
    args.func(args, p)
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 75, in execute
    prepend=not args.override_channels)
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/api.py", line 33, in get_index
    return fetch_index(tuple(channel_urls))
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/utils.py", line 61, in __call__
    value = self.func(*args)
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 105, in fetch_index
    repodata = fetch_repodata(url)
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 72, in fetch_repodata
    u = connectionhandled_urlopen(request)
  File "/home/matlab/anaconda/lib/python2.7/site-packages/conda/connection.py", line 86, in connectionhandled_urlopen
    return urllib2.urlopen(request)
  File "/home/matlab/anaconda/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/home/matlab/anaconda/lib/python2.7/urllib2.py", line 396, in open
    protocol = req.get_type()
  File "/home/matlab/anaconda/lib/python2.7/urllib2.py", line 258, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: conda-canary/linux-64/repodata.json.bz2

**Comment by tyler-thetyrant** [comment]
Your conda version is way too old to update itself to the most recent one (4.3.22).
I recommend uninstalling and reinstalling miniconda/anaconda.
