### ISSUE TITLE
ImportError: cannot import name get_auth_from_url

### ISSUE THREAD

**Issue by Hugotong6425** [conda/conda#5651]
When I tried to activate an environment today, this import error occurs. This doesn't occur before.
`TongdeMacBook-Air:~ HugoTong$ source activate crawler
`

```
 Traceback (most recent call last):
  File "/Users/HugoTong/anaconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 151, in main
    activate.main()
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/cli/activate.py", line 167, in main
    import conda.install
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/gateways/download.py", line 16, in <module>
    from ..connection import CondaSession
  File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name get_auth_from_url
```

Then I tried to check what environment I currently have.
`TongdeMacBook-Air:~ HugoTong$ conda info --envs
`

This is what I get.
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
$ /Users/HugoTong/anaconda2/bin/conda info --envs


    Traceback (most recent call last):
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 98, in _main
        imported = importlib.import_module(module)
      File "/Users/HugoTong/anaconda2/lib/python2.7/importlib/__init__.py", line 37, in import_module
        __import__(name)
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/cli/main_list.py", line 20, in <module>
        from ..egg_info import get_egg_info
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/egg_info.py", line 15, in <module>
        from .misc import rel_path
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/misc.py", line 19, in <module>
        from .core.index import get_index, _supplement_index_with_cache
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 8, in <module>
        from .package_cache import PackageCache
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 10, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 31, in <module>
        from ..gateways.download import download
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/gateways/download.py", line 16, in <module>
        from ..connection import CondaSession
      File "/Users/HugoTong/anaconda2/lib/python2.7/site-packages/conda/connection.py", line 16, in <module>
        from requests.utils import get_auth_from_url, get_netrc_auth
    ImportError: cannot import name get_auth_from_url
```

The same error occurs. How can I solve this problem? Many thanks!

**Comment by Hugotong6425** [comment]
Solved by
`sudo pip install -U requests`

**Comment by kalefranz** [comment]
Yes, pip had left your environment in an inconsistent state.  But now since you've used sudo, you'll also have permissions issues with both pip and conda going forward, unless you always use sudo.
