### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by iecseu** [conda/conda#5652]
some days ago ,I ran the prompt cmd well.However,I have this issue when I run the prompt cmd today.

Traceback (most recent call last):
  File "F:\Anadacn\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "F:\Anadacn\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "F:\Anadacn\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "F:\Anadacn\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "F:\Anadacn\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "F:\Anadacn\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "F:\Anadacn\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "F:\Anadacn\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "F:\Anadacn\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "F:\Anadacn\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "F:\Anadacn\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "F:\Anadacn\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "F:\Anadacn\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "F:\Anadacn\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "F:\Anadacn\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "F:\Anadacn\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "F:\Anadacn\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb4 in position 1: ordinal not in range(128)

**Comment by iecseu** [comment]
I solve this issue, by deleting the Chinese path in the system Path.
So it is due to the Chinese path in your SYSTEM Path.You must ensure there is none Chinese Path in your System Path.NONE!!!!!

**Comment by mingwandroid** [comment]
This is a bug in core CPython upstream. Python 3 works better in this regard.

**Comment by mingwandroid** [comment]
Closing as we cannot fix these issues.

**Comment by GaneshDoosa** [comment]
Hello iecseu..
     I didn't understand what do you mean by Chinese Path. I'm also facing the same issue. I don't have any Chinese characters in my system. If you don't mind can you please where have you changed??

**Comment by GaneshDoosa** [comment]
Okay ...i got it how to solve my issue #5691
Anyway thanks for clue....
