### ISSUE TITLE
error from r channel

### ISSUE THREAD

**Issue by scottdraves** [conda/conda#5660]
```
r-base-3.3An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.14.1
         python version : 2.7.12.final.0
       requests version : 2.9.1
       root environment : /Users/spot/anaconda  (writable)
    default environment : /Users/spot/anaconda/envs/rtest
       envs directories : /Users/spot/anaconda/envs
          package cache : /Users/spot/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False



`$ /Users/spot/anaconda/envs/rtest/bin/conda install -c r r-essentials`




    Traceback (most recent call last):
      File "/Users/spot/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/spot/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/spot/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/spot/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/Users/spot/anaconda/pkgs/r-base-3.3.2-1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-package\
s-prod.s3.amazonaws.com', port=443): Read timed out.).
```

**Comment by tyler-thetyrant** [comment]
Can you try with the most recent version of conda (4.3.22)? `conda update conda` will do the job.
Also since 4.3, r channels are now part of defaults, so you'll just have to run `conda install r`

**Comment by scottdraves** [comment]
that worked, thanks!
