### ISSUE TITLE
Problems installing pyqt4

### ISSUE THREAD

**Issue by cmd003** [conda/conda#5663]
C:\Users\CP>conda install pyqt=4
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment E:\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    requests-2.14.2            |           py35_0         705 KB
    qt-4.8.7                   |           vc14_9        50.5 MB
    pyqt-4.11.4                |           py35_7         3.8 MB
    pyopenssl-16.2.0           |           py35_0          70 KB
    conda-4.3.22               |           py35_0         534 KB
    ------------------------------------------------------------
                                           Total:        55.6 MB

The following NEW packages will be INSTALLED:

    conda-env: 2.6.0-0

The following packages will be UPDATED:

    conda:     4.2.9-py35_0  --> 4.3.22-py35_0
    pyopenssl: 16.0.0-py35_0 --> 16.2.0-py35_0
    requests:  2.11.1-py35_0 --> 2.14.2-py35_0

The following packages will be DOWNGRADED due to dependency conflicts:

    pyqt:      5.6.0-py35_0  --> 4.11.4-py35_7
    qt:        5.6.0-vc14_0  [vc14] --> 4.8.7-vc14_9  [vc14]

Proceed ([y]/n)? y

Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00 122.79 kB/s
requests-2.14. 100% |###############################| Time: 0:00:06 114.06 kB/s
An unexpected error has occurred.                   | Time: 0:08:40  39.27 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : E:\Anaconda3  (writable)
    default environment : E:\Anaconda3
       envs directories : E:\Anaconda3\envs
          package cache : E:\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ E:\Anaconda3\Scripts\conda-script.py install pyqt=4`

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "E:\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "E:\Anaconda3\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "E:\Anaconda3\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "E:\Anaconda3\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "E:\Anaconda3\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "E:\Anaconda3\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "E:\Anaconda3\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "E:\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "E:\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "E:\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "E:\Anaconda3\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "E:\Anaconda3\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "E:\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "E:\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "E:\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "E:\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "E:\Anaconda3\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'E:\\Anaconda3\\pkgs\\qt-4.8.7-vc14_9.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "E:\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "E:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "E:\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "E:\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "E:\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "E:\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'E:\\Anaconda3\\pkgs\\qt-4.8.7-vc14_9.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by mingwandroid** [comment]
This is a network connectivity issue. The connection timed out. You should just try again.

**Comment by cmd003** [comment]
Thanks！I will try it again.

**Comment by kalefranz** [comment]
`conda update conda`
