### ISSUE TITLE
creating environment with yml file yields error 

### ISSUE THREAD

**Issue by jzf2101** [conda/conda#5664]
The error suggests it be added to the issues list:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : 2.1.15
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/4d/anaconda  (writable)
    default environment : /Users/4d/anaconda
       envs directories : /Users/4d/anaconda/envs
                          /Users/4d/.conda/envs
          package cache : /Users/4d/anaconda/pkgs
                          /Users/4d/.conda/pkgs
           channel URLs : https://conda.anaconda.org/datamicroscopes/osx-64
                          https://conda.anaconda.org/datamicroscopes/noarch
                          https://conda.anaconda.org/distributions/osx-64
                          https://conda.anaconda.org/distributions/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/4d/.condarc
             netrc file : /Users/4d/.netrc
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

`$ /Users/4d/anaconda/bin/conda-env create -f environment.yml`




    Traceback (most recent call last):
      File "/Users/4d/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/4d/anaconda/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/4d/anaconda/lib/python3.6/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: can only concatenate list (not "NoneType") to list
```

**Comment by kalefranz** [comment]
What are the contents of your `environment.yml` file?

**Comment by jzf2101** [comment]
i can't reproduce the error so I'll close the issue
