### ISSUE TITLE
fail to install peddy

### ISSUE THREAD

**Issue by ieiwk** [conda/conda#5669]
Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/wk/rj2/anaconda  (writable)
    default environment : /home/wk/rj2/anaconda
       envs directories : /home/wk/rj2/anaconda/envs
                          /home/wk/.conda/envs
          package cache : /home/wk/rj2/anaconda/pkgs
                          /home/wk/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/wk/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Linux/4.4.0-83-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/wk/rj2/anaconda/bin/conda install -y peddy`

    Traceback (most recent call last):
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 227, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 672, in send
        r.content
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/requests/models.py", line 816, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/home/wk/rj2/anaconda/lib/python2.7/site-packages/requests/models.py", line 741, in generate
        raise ChunkedEncodingError(e)
    ChunkedEncodingError: ('Connection broken: error("(104, \'ECONNRESET\')",)', error("(104, 'ECONNRESET')",))

**Comment by kalefranz** [comment]
intermittent http error.  You may need to `conda clean --all` after this.
