### ISSUE TITLE
Can't run conda \Anaconda2\Scripts\conda-script.py", line 5

### ISSUE THREAD

**Issue by wufannet** [conda/conda#5684]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Users\wufannet\Anaconda2\Scripts\conda-script.py", line 5, in <module
>
    sys.exit(conda.cli.main())
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\conda\cli\main.py", line 1
76, in main
    return handle_exception(e)
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\conda\exceptions.py", line
 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\conda\exceptions.py", line
 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\conda\cli\main_info.py", l
ine 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\conda\connection.py", line
 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\requests\__init__.py", lin
e 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\requests\packages\urllib3\
contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\cryptography\x509\__init__
.py", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\cryptography\x509\base.py"
, line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\cryptography\x509\extensio
ns.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\asn1crypto\keys.py", line
22, in <module>
    from ._elliptic_curve import (
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve
.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\asn1crypto\_int.py", line
56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Users\wufannet\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_
ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Users\wufannet\Anaconda2\lib\ctypes\util.py", line 53, in find_librar
y
    fname = os.path.join(directory, name)
  File "C:\Users\wufannet\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb7 in position 3: ordinal
not in range(128)

C:\Users\wufannet>

**Comment by rmancy-smg** [comment]
Working from a directory that only contains valid ascii characters might be a work around...

**Comment by Jacoobr** [comment]
Do you slove this problem? I met this the same problem today.

**Comment by kalefranz** [comment]
see https://github.com/conda/conda/issues/6650
