### ISSUE TITLE
ImportError: cannot import name certs

### ISSUE THREAD

**Issue by marijazmf** [conda/conda#5687]
I am running python-based web application Galaxy on server.  Different environments are handled over conda. Unfortunately I have issue to source environment:
`. /home/data/galaxy_tool_dep/_conda/bin/activate '/home/data/galaxy_tool_dep/_conda/envs/__fastqc@0.11.5'`

Error is:

```
Failed to activate conda environment! Error was:
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/data/galaxy_tool_dep/_conda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/cli/main.py", line 159, in main
    return handle_exception(e)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/exceptions.py", line 548, in get_info
    args.func(args, p)
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/cli/main_info.py", line 148, in execute
    from conda.api import get_index
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/api.py", line 1, in <module>
    from .core.index import get_index
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/core/package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/core/path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/conda/gateways/download.py", line 11, in <module>
    from requests.exceptions import ConnectionError, HTTPError, SSLError
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/galaxy/galaxy/.venv/local/lib/python2.7/site-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
```

Any help?

Thanks in advance,
Marija

**Comment by kalefranz** [comment]
Make sue the version of requests you're running is consistent with certifi and other requests dependencies.
