### ISSUE TITLE
An unexpected error has occurred while opening Anaconda Prompt or while using jupyter notebook

### ISSUE THREAD

**Issue by GaneshDoosa** [conda/conda#5691]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues

**Traceback (most recent call last):**
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Anaconda2\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc0 in position 0: ordinal not in range(128)

Here it is my PATH variable value
C:\Anaconda2;C:\Anaconda2\Library\mingw-w64\bin;C:\Anaconda2\Library\usr\bin;C:\Anaconda2\Library\bin;C:\Anaconda2\Scripts;

Please help me out.

**Comment by GaneshDoosa** [comment]
Finally i solved it by myself.
The problem is there in Environment variables 
Suppose you are installing per user or for all users the environment variable called PATH has "C:\Program Files\xxxx". Here the Program Files has the space that why it is not able to decode. The only thing that you need to do is create one more variable PROGRAMFILES with value C:\Program Files and use %PROGRAMFILES% where ever program files is used.
PATH (user or system)variable should not contain any space.

**Comment by qingyunqu2017** [comment]
maybe you can fix your installing path. That is my solution,and my issure has gone.

**Comment by qingyunqu2017** [comment]
if you have some problems with this issue, you can sent email to me via 2394711771@qq.com

**Comment by aicozone** [comment]
Thank you for your solution!!
