### ISSUE TITLE
conda.CondaMultiError: post-link script failed for package menpo::widgetsnbextension-1.2.3-py35_1

### ISSUE THREAD

**Issue by ggthecoder** [conda/conda#5692]
I am new to using conda. I am trying to set up an environment on Mac from a given .yml file and I ran into an issue. As suggested in the error output, I ran with -v and am pasting the error details below. Help is appreciated:

Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/gowtham/miniconda3  (writable)
    default environment : /Users/gowtham/miniconda3
       envs directories : /Users/gowtham/miniconda3/envs
                          /Users/gowtham/.conda/envs
          package cache : /Users/gowtham/miniconda3/pkgs
                          /Users/gowtham/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 24399:5000

`$ /Users/gowtham/miniconda3/bin/conda-env create -v -f environment.yml`

    Traceback (most recent call last):
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 500, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/Users/gowtham/miniconda3/envs/carnd-term1/bin/.widgetsnbextension-post-link.sh']' returned non-zero exit status 126.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 327, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 516, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package menpo::widgetsnbextension-1.2.3-py35_1
    running your command again with `-v` will provide additional information
    location of failed script: /Users/gowtham/miniconda3/envs/carnd-term1/bin/.widgetsnbextension-post-link.sh
    ==> script messages <==
    <None>
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package menpo::widgetsnbextension-1.2.3-py35_1
    running your command again with `-v` will provide additional information
    location of failed script: /Users/gowtham/miniconda3/envs/carnd-term1/bin/.widgetsnbextension-post-link.sh
    ==> script messages <==
    <None>
    
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 37, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/Users/gowtham/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package menpo::widgetsnbextension-1.2.3-py35_1
    running your command again with `-v` will provide additional information
    location of failed script: /Users/gowtham/miniconda3/envs/carnd-term1/bin/.widgetsnbextension-post-link.sh
    ==> script messages <==
    <None>

**Comment by kalefranz** [comment]
This is a post-link script failure.  You'll need to raise an issue with the publisher of the package.
