### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by eckofoid** [conda/conda#5698]
While doing the following:

    $ conda search man2html

I received the following output:

    Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 2.0.12
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /anaconda  (writable)
    default environment : /anaconda
       envs directories : /anaconda/envs
                          /Users/roth9lab/.conda/envs
          package cache : /anaconda/pkgs
                          /Users/roth9lab/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/2.7.13 Darwin/14.5.0 OSX/10.10.5    
                UID:GID : 501:20

`$ /anaconda/bin/conda search man2html`

    Traceback (most recent call last):
      File "/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 126, in execute
        execute_search(args, parser)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/main_search.py", line 175, in execute_search
        unknown=args.unknown)
      File "/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 469, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/anaconda/pkgs/cache/d85a531e.json'

**Comment by kalefranz** [comment]
sudo chown -R 501:20 /anaconda
