### ISSUE TITLE
 UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 24

### ISSUE THREAD

**Issue by retsyo** [conda/conda#5705]
I used `Python 2.7.12 |Anaconda 2.2.0 (32-bit)| (default, Jun 29 2016, 11:42:13)` on my Windows 64 bits, and I remember I can do `conda install something` successful half years ago. 

I used mirror form `https://mirrors.tuna.tsinghua.edu.cn/anaconda/` whose webpage is said to be encoded as GB2312

But today
```bat
E:\prg\py\Anaconda2_32\Scripts>conda install numpy
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment E:\prg\py\Anaconda2_32:

The following NEW packages will be INSTALLED:

    pywavelets:   0.5.2-np113py27_0  https://mirrors.tuna.tsinghua.edu.cn/anacon
da/pkgs/free

The following packages will be UPDATED:

    conda:        4.3.21-py27_0      https://mirrors.tuna.tsinghua.edu.cn/anacon
da/pkgs/free --> 4.3.22-py27_0      https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    matplotlib:   2.0.0-np111py27_0  defaults
             --> 2.0.2-np113py27_0  https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    mkl:          11.3.3-1           defaults
             --> 2017.0.3-0         https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    numexpr:      2.6.1-np111py27_0  defaults
             --> 2.6.2-np113py27_0  https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    numpy:        1.11.1-py27_1      defaults
             --> 1.13.1-py27_0      https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    pandas:       0.18.1-np111py27_0 defaults
             --> 0.20.2-np113py27_0 https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    scikit-image: 0.12.3-np111py27_1 defaults
             --> 0.13.0-np113py27_0 https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    scikit-learn: 0.17.1-np111py27_1 defaults
             --> 0.18.2-np113py27_0 https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free
    scipy:        0.18.1-np111py27_0 defaults
             --> 0.19.1-np113py27_0 https://mirrors.tuna.tsinghua.edu.cn/anacond
a/pkgs/free

Proceed ([y]/n)?

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : 1.3.2
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : E:\prg\py\Anaconda2_32  (writable)
    default environment : E:\prg\py\Anaconda2_32
       envs directories : E:\prg\py\Anaconda2_32\envs
                          C:\Users\LOVLJIDY\AppData\Local\conda\conda\envs
                          C:\Users\LOVLJIDY\.conda\envs
          package cache : E:\prg\py\Anaconda2_32\pkgs
                          C:\Users\LOVLJIDY\AppData\Local\conda\conda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/win-32
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/fre
e/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\LOVLJIDY\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.13.0 CPython/2.7.12 Windows/7
Windows/6.1.7601
          administrator : False

`$ E:\prg\py\Anaconda2_32\Scripts\conda-script.py install numpy`




    Traceback (most recent call last):
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\exceptions.py", line
632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\cli\main.py", line 13
7, in _main
        exit_code = args.func(args, p)
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\cli\main_install.py",
 line 80, in execute
        install(args, parser, 'install')
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\cli\install.py", line
 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\plan.py", line 829, i
n execute_actions
        with History(actions[PREFIX]):
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\history.py", line 72,
 in __enter__
        self.update('enter')
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\history.py", line 93,
 in update
        last = set(self.get_state())
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\history.py", line 192
, in get_state
        states = self.construct_states()
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\history.py", line 172
, in construct_states
        for dt, cont, unused_com in self.parse():
      File "E:\prg\py\Anaconda2_32\lib\site-packages\conda\history.py", line 122
, in parse
        lines = f.read().splitlines()
      File "E:\prg\py\Anaconda2_32\lib\codecs.py", line 314, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf8' codec can't decode byte 0xd6 in position 24: inva
lid continuation byte
```

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/issues/6650
