### ISSUE TITLE
Astroconda iraf27 Update - ValueError: No JSON object could be decoded (Python 2.7.13)

### ISSUE THREAD

**Issue by ViniciusBranco** [conda/conda#5711]
The following issue has happened as I tried to update an existing “iraf27” environment, with:
**$ conda install -n iraf27 iraf-all pyraf-all**
There were updates to be made, but it faced the error in the subject of this issue. What can/should I do in order to update iraf27 for Astroconda?

The issue:

Current conda install:

               platform : linux-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/user/anaconda2  (writable)
    default environment : /home/user/anaconda2
       envs directories : /home/user/anaconda2/envs
                          /home/user/.conda/envs
          package cache : /home/user/anaconda2/pkgs
                          /home/user/.conda/pkgs
           channel URLs : http://ssb.stsci.edu/astroconda/linux-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/user/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/2.7.13 Linux/4.8.0-58-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/user/anaconda2/bin/conda install -n iraf27 iraf-all pyraf-all`

    Traceback (most recent call last):
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 363, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 81, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/home/user/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 101, in read_index_json
        record = IndexRecord(**json.load(fi))  # TODO: change to LinkedPackageData
      File "/home/user/anaconda2/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/home/user/anaconda2/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/home/user/anaconda2/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/user/anaconda2/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by kalefranz** [comment]
Try `conda clean --packages`

**Comment by kalefranz** [comment]
This happened from a partial package extraction.  Rather than throwing that ugly stack trace, we should remove the corrupt package, and throw a descriptive user error.
