### ISSUE TITLE
Noobie broke conda

### ISSUE THREAD

**Issue by kaikaikoala** [conda/conda#5713]
I have no idea what happened, but I broke my conda; anything I run results in this message:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

`$ /home/koalakai/anaconda3/bin/conda info --envs`

    Traceback (most recent call last):
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 98, in _main
        imported = importlib.import_module(module)
      File "/home/koalakai/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 20, in <module>
        from ..egg_info import get_egg_info
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/egg_info.py", line 15, in <module>
        from .misc import rel_path
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/misc.py", line 19, in <module>
        from .core.index import get_index, _supplement_index_with_cache
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
        from .repodata import collect_all_repodata
      File "/home/koalakai/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 21, in <module>
        from requests.packages.urllib3.exceptions import InsecureRequestWarning
    ImportError: cannot import name 'InsecureRequestWarning'

**Comment by nehaljwani** [comment]
Could you please share output for:
`pip freeze`

**Comment by kaikaikoala** [comment]
alabaster==0.7.9
anaconda-client==1.6.0
anaconda-navigator==1.5
anaconda-project==0.4.1
astroid==1.4.9
astropy==1.3
Babel==2.3.4
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.5.3
bitarray==0.8.1
blaze==0.10.1
bokeh==0.12.4
boto==2.45.0
Bottleneck==1.2.0
cffi==1.9.1
chardet==2.2.1
chest==0.2.3
click==6.7
cloudpickle==0.2.2
clyent==1.2.2
colorama==0.2.5
conda==4.3.14
configobj==5.0.6
contextlib2==0.5.4
cryptography==1.7.1
cycler==0.10.0
Cython==0.25.2
cytoolz==0.8.2
dask==0.13.0
datashape==0.5.4
decorator==3.4.0
dill==0.2.5
docutils==0.13.1
et-xmlfile==1.0.1
fastcache==1.0.2
Flask==0.12
Flask-Cors==3.0.2
Flask-Login==0.4.0
Flask-MySQL==1.4.0
gevent==1.2.1
greenlet==0.4.11
h5py==2.6.0
HeapDict==1.0.0
html5lib==0.999
idna==2.2
imagesize==0.7.1
ipykernel==4.5.2
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
isort==4.2.5
itsdangerous==0.24
jdcal==1.3
jedi==0.9.0
Jinja2==2.9.4
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-core==4.2.1
lazy-object-proxy==1.2.2
llvmlite==0.15.0
locket==0.2.0
lxml==3.7.2
MarkupSafe==0.23
matplotlib==2.0.0
mistune==0.7.3
mpmath==0.19
multipledispatch==0.4.9
nbconvert==4.2.0
nbformat==4.2.0
networkx==1.11
nltk==3.2.2
nose==1.3.7
notebook==4.3.1
numba==0.30.1
numexpr==2.6.1
numpy==1.11.3
numpydoc==0.6.0
odo==0.5.0
openpyxl==2.4.1
pandas==0.19.2
partd==0.3.7
pathlib2==2.2.0
patsy==0.4.1
pep8==1.7.0
pexpect==4.2.1
pickleshare==0.7.4
Pillow==2.3.0
ply==3.9
prompt-toolkit==1.0.9
psutil==5.0.1
ptyprocess==0.5.1
py==1.4.32
pyasn1==0.1.9
pycosat==0.6.1
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
pyflakes==1.5.0
Pygments==2.1.3
pylint==1.6.4
PyMySQL==0.7.11
pyOpenSSL==16.2.0
pyparsing==2.1.4
pytest==3.0.5
python-dateutil==2.6.0
pytz==2016.10
PyYAML==3.12
pyzmq==16.0.2
QtAwesome==0.4.3
qtconsole==4.2.1
QtPy==1.2.1
redis==2.10.5
requests==2.2.1
rope-py3k==0.9.4.post1
scikit-image==0.12.3
scikit-learn==0.18.1
scipy==0.18.1
seaborn==0.7.1
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
sockjs-tornado==1.0.3
Sphinx==1.5.1
spyder==3.1.2
SQLAlchemy==1.1.5
statsmodels==0.6.1
sympy==1.0
tables==3.3.0
terminado==0.6
toolz==0.8.2
tornado==4.4.2
traitlets==4.3.1
unicodecsv==0.14.1
wcwidth==0.1.7
Werkzeug==0.11.15
widgetsnbextension==1.2.6
wrapt==1.10.8
xlrd==1.0.0
XlsxWriter==0.9.6
xlwt==1.2.0

**Comment by nehaljwani** [comment]
Does the following help?
`pip install -U requests`

**Comment by kaikaikoala** [comment]
Yes it does! Thanks.

**Comment by nehaljwani** [comment]
I am guessing you installed some pip package which had a hard dependency on requests which ended up downgrading it. But there could be some other reason too. In any case, please upgrade conda to the latest 4.3.x release as the import shouldn't have failed, as per #5090
