### ISSUE TITLE
metapackage does not seem to accept channel arguments, but fails if depenencies are in non-default channel

### ISSUE THREAD

**Issue by doutriaux1** [conda/conda#5720]
example:
```
conda metapackage acme-unified 1.1  --build-number 0 --dependencies "uvcdat ==2.10" "cibots ==0.2" "cdp ==1.0.3" "output_viewer ==1.2.2" "netCDF4 ==1.2.7" "xarray ==0.9.5" "dask ==0.14.3" "bottleneck ==1.0.6" "lxml ==3.7.3" "nco ==4.6.7" "sympy ==1.0" "pyproj ==1.9.5.1" "pytest ==3.0.7" "shapely ==1.5.17" "cartopy ==0.15.1" pyevtk progressbar scitools
```

fails with:

```
> conda metapackage acme-unified 1.1  --build-number 0 --dependencies "uvcdat ==2.10" "cibots ==0.2" "cdp ==1.0.3" "output_viewer ==1.2.2" "netCDF4 ==1.2.7" "xarray ==0.9.5" "dask ==0.14.3" "bottleneck ==1.0.6" "lxml ==3.7.3" "nco ==4.6.7" "sympy ==1.0" "pyproj ==1.9.5.1" "pytest ==3.0.7" "shapely ==1.5.17" "cartopy ==0.15.1" pyevtk progressbar scitools
Attempting to finalize metadata for acme-unified
INFO:conda_build.metadata:Attempting to finalize metadata for acme-unified
BUILD START: [u'acme-unified-1.1-hdfe7718_0.tar.bz2']

Leaving build/test directories:
  Work:	 ../../home/doutriaux1/anaconda2/conda-bld/acme-unified_1500932469544/work 
  Test:	 ../../home/doutriaux1/anaconda2/conda-bld/acme-unified_1500932469544/test_tmp 
Leaving build/test environments:
  Test:	source activate  ../../home/doutriaux1/anaconda2/conda-bld/acme-unified_1500932469544/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p 
  Build:	source activate  ../../home/doutriaux1/anaconda2/conda-bld/acme-unified_1500932469544/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac 


Traceback (most recent call last):
  File "/home/doutriaux1/anaconda2/bin/conda-metapackage", line 6, in <module>
    sys.exit(conda_build.cli.main_metapackage.main())
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_metapackage.py", line 118, in main
    return execute(sys.argv[1:])
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/cli/main_metapackage.py", line 114, in execute
    api.create_metapackage(**args.__dict__)
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 347, in create_metapackage
    license_name=license_name, summary=summary, config=config)
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/metapackage.py", line 29, in create_metapackage
    return build(m, config=config, need_source_download=False)
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 1633, in build_tree
    notest=notest,
  File "/home/doutriaux1/anaconda2/lib/python2.7/site-packages/conda_build/build.py", line 980, in build
    raise e
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: set(['netCDF4', 'output_viewer', 'cartopy', 'uvcdat', 'cdp', 'nco', 'cibots', 'bottleneck', 'scitools', 'pyevtk', 'shapely'])
```

On a linux system using latest conda and conda-build

**Comment by kalefranz** [comment]
Probably just add the channel you want with `conda config --add channels`.  If that doesn't work, go ahead and file an issue with conda-build, since that's where the `conda metapackage` command lives.

**Comment by doutriaux1** [comment]
@kalefranz yes that works, but it's annoying since it is persistent and I'd rather keep my defaults "clean", will file am issue/request there then thx.
