### ISSUE TITLE
Unexpected error while installing packages via requirements.txt file and channel specified

### ISSUE THREAD

**Issue by PaulSh84** [conda/conda#5722]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\user\Miniconda3  (writable)
    default environment : C:\Users\user\Miniconda3\envs\jira
       envs directories : C:\Users\user\Miniconda3\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
                          C:\Users\user\.conda\envs
          package cache : C:\Users\user\Miniconda3\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.10240
          administrator : False

`$ C:\Users\user\Miniconda3\Scripts\conda-script.py install -n jira --file .\Desktop\jira-worklog-scrapper\requirements.txt -c conda-forge`

    Traceback (most recent call last):
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\cli\install.py", line 363, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\core\link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\core\link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\gateways\disk\read.py", line 84, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "C:\Users\user\Miniconda3\lib\site-packages\conda\gateways\disk\read.py", line 139, in read_paths_json
        data = json.load(paths_json)
      File "C:\Users\user\Miniconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Users\user\Miniconda3\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "C:\Users\user\Miniconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\user\Miniconda3\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kalefranz** [comment]
Need usages of `read_paths_json()` to indicate corrupt package and solution `conda clean --packages --tarballs`.

**Comment by PaulSh84** [comment]
sorry, no longer on that project, can't reproduce this issue on my local machine.  :(
