### ISSUE TITLE
'An error occurred~' when I am using command"conda install pandas"

### ISSUE THREAD

**Issue by Tang13579** [conda/conda#5736]
I was using IPython to import pandas,but it gives me an error:
    **ImportError: cannot import name 'pivot_simple'**
I checked my IPython version,it's 3.6.0,and a friend told me 'pivot_simple'is from an older version of pandas 
under this situation,Idecided to uninstall pandas and install it later,the following operations were done by conda prompt on Windows10
cmd: pip uninstall pandas
       successful
cmd: pip install pandas
`Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages
Requirement already satisfied: python-dateutil>=2 in c:\programdata\anaconda3\lib\site-packages (from pandas)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas)
Requirement already satisfied: numpy>=1.7.0 in c:\programdata\anaconda3\lib\site-packages (from pandas)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2->pandas)`
I am not sure what does the above code means,so I try another cmd
cmd: conda install pandas
it gives me a lots warning,and it remind me to post some information here:
# Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\beekeeper\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install pandas`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 255, in execute
        self.verify()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 238, in verify
        self.prepare()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 152, in prepare
        self.packages_info_to_link)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 371, in get_python_version
        linked_python_version = get_python_version_for_prefix(target_prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 146, in get_python_version_for_prefix
        raise RuntimeError("multiple python records found in prefix %s" % prefix)
    RuntimeError: multiple python records found in prefix C:\ProgramData\Anaconda3

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 362, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: multiple python records found in prefix C:\ProgramData\Anaconda3

**Comment by kalefranz** [comment]
Should be fixed now.

**Comment by yeyuguo** [comment]
How to solve this problem？

**Comment by Achrefothmeni** [comment]
i have the same problem, did you solve it ?

**Comment by kalefranz** [comment]
Please file a new report if you continue to have similar issues.  Make sure you're using the latest conda.  `conda update conda`
