### ISSUE TITLE
conda activate message

### ISSUE THREAD

**Issue by tyler-thetyrant** [conda/conda#5738]
In conda 4.4 beta: 

`source activate` works but `conda activate` (per instruction) raises import error

```
To activate this environment, use

    $ conda activate conda-website

To deactivate an active environment, use

    $ conda deactivate

 ~//$ conda activate conda-website
Traceback (most recent call last):
  File "/Users/tkim/miniconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/tkim/miniconda3/lib/python2.7/site-packages/conda/cli/main.py", line 178, in main
    from ..exceptions import handle_exception
ImportError: cannot import name handle_exception

```

**Comment by kalefranz** [comment]
Duplicate of #5790. Fixed in #5820.
