### ISSUE TITLE
conda >=4.4 incompatiblity with conda-build 3

### ISSUE THREAD

**Issue by mingwandroid** [conda/conda#5743]
conda-build has the following code (https://github.com/conda/conda-build/blob/master/conda_build/render.py#L216-L233):

```
                elif utils.conda_43():
                    # TODO: this is a vile hack reaching into conda's internals. Replace with
                    #    proper conda API when available.
                    try:
                        pfe = ProgressiveFetchExtract(link_dists=[pkg],
                                                    index=index)
                        with utils.LoggingContext():
                            pfe.execute()
                        for pkgs_dir in _pkgs_dirs:
                            pkg_file = os.path.join(pkgs_dir, pkg.dist_name + '.tar.bz2')
                            if os.path.isfile(pkg_file):
                                extra_specs = utils.package_has_file(pkg_file,
                                                                    'info/run_exports')
                               	if extra_specs:
                                    specs = extra_specs.splitlines()
                                    additional_specs.extend(_filter_run_exports(specs, ignore_list))
                                break
                        break
```

On conda 4.4 this fails with:

```
Attempting to finalize metadata for jbig
INFO:conda_build.metadata:Attempting to finalize metadata for jbig
Loading channels: done
Solving environment: done
Traceback (most recent call last):
  File "/tmp/m/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/tmp/m/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 382, in main
    execute(sys.argv[1:])
  File "/tmp/m/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 373, in execute
    noverify=args.no_verify)
  File "/tmp/m/lib/python3.6/site-packages/conda_build/api.py", line 184, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/tmp/m/lib/python3.6/site-packages/conda_build/build.py", line 1653, in build_tree
    notest=notest,
  File "/tmp/m/lib/python3.6/site-packages/conda_build/build.py", line 875, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/tmp/m/lib/python3.6/site-packages/conda_build/render.py", line 482, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/tmp/m/lib/python3.6/site-packages/conda_build/metadata.py", line 1638, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/tmp/m/lib/python3.6/site-packages/conda_build/metadata.py", line 623, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/tmp/m/lib/python3.6/site-packages/conda_build/render.py", line 273, in finalize_metadata
    extra_run_specs = get_upstream_pins(m, build_actions, 'build')
  File "/tmp/m/lib/python3.6/site-packages/conda_build/render.py", line 221, in get_upstream_pins
    index=index)
TypeError: __init__() got an unexpected keyword argument 'link_dists'
```

**Comment by kalefranz** [comment]
I think there are probably several 4.4 + 3.0 compatibility errors. Report appreciated. Keep them coming!

**Comment by kalefranz** [comment]
Closing.
