### ISSUE TITLE
"conda create -n tensorflow python=3.5" and "conda update conda" are giving errors in Windows 7

### ISSUE THREAD

**Issue by shashanks2008** [conda/conda#5744]
I am using Windows 7 and I have been following the Windows installation instruction from Tensorflow website https://www.tensorflow.org/install/install_windows
After using command 'conda create -n tensorflow python=3.5' (I have also tried with python=3.6) it was showing below error.
`
    Fetching package metadata ...

    CondaHTTPError: HTTP None None for url <None>
    Elapsed: None

    An HTTP error occurred when trying to retrieve this URL.
    ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', por
    t=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caus
    ed by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSCon
    nection object at 0x0000000004DFECC0>: Failed to establish a new connection: [Er
    rno 11004] getaddrinfo failed',))",),)
`

I was able to resolve this using #1326, I added `- proxy_servers: {}` in .condarc file.
Now the problem is that when I was trying to create environment, it is showing below error.

    C:\Users\User1>conda create -n tensorflow python=3.5
    An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:
    
    https://github.com/conda/conda/issues
    
    
    
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 118, in install
        context.validate_configuration()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 830, in validate_configuration
        raise_errors(tuple(chain.from_iterable((errors, post_errors))))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 828, in <genexpr>
        for name in self.parameter_names)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 821, in _collect_validation_error
        func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 446, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 595, in _merge
        top_deduped = tuple(unique(concatv(top_lines, all_lines)))
      File "cytoolz/itertoolz.pyx", line 415, in cytoolz.itertoolz._unique_identity.__next__ (cytoolz/itertoolz.c:8038)
        while PySet_Contains(self.seen, item):
    TypeError: unhashable type: 'CommentedMap'
    
    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 5, in <module>
        sys.exit(conda.cli.main())
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 167, in main
        return conda_exception_handler(_main, *args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 633, in conda_exception_handler
        print_unexpected_error_message(e)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 560, in print_unexpected_error_message
        info_stdout, info_stderr = get_info()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 530, in get_info
        args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 202, in execute
        channels = context.channels
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 399, in channels
        return self._channels
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 446, in __get__
        result = typify_data_structure(self._merge(matches) if matches else self.default,
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 595, in _merge
        top_deduped = tuple(unique(concatv(top_lines, all_lines)))
      File "cytoolz/itertoolz.pyx", line 415, in cytoolz.itertoolz._unique_identity.__next__ (cytoolz/itertoolz.c:8038)
        while PySet_Contains(self.seen, item):
    TypeError: unhashable type: 'CommentedMap'

I was trying to find solution using #2687, I tried changing the install.py after reinstallation the anaconda but nothing worked. I am also not able to use 'conda update conda' command. 
I am using the Python3.6 (Anaconda3 4.3.0 64-bit). One more thing that I am using the office computer which has antivirus but I have admin access, I am not sure if it is useful.
Is it possible to solve this error, or is there any workaround to get rid of these errors on the windows7?

**Comment by tyler-thetyrant** [comment]
Can you share your `conda info`?

**Comment by shashanks2008** [comment]
Now I am not able to run the `conda info.`  It is showing below error.

     C:\ProgramData\Anaconda3\Scripts>conda info conda
     An unexpected error has occurred.
     Please consider posting the following information to the
     conda GitHub issue tracker at:
     
         https://github.com/conda/conda/issues
    
    `$ C:\ProgramData\Anaconda3\Scripts\conda-script.py info conda`
    
    
        Traceback (most recent call last):
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
            return_value = func(*args, **kwargs)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
            exit_code = args.func(args, p)
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 153, in execute
            index = get_index()
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 115, in get_index
            channel_urls += context.channels
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\base\context.py", line 399, in channels
            return self._channels
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 446, in __get__
            result = typify_data_structure(self._merge(matches) if matches else self.default,
          File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\configuration.py", line 595, in _merge
            top_deduped = tuple(unique(concatv(top_lines, all_lines)))
          File "cytoolz/itertoolz.pyx", line 415, in cytoolz.itertoolz._unique_identity.__next__ (cytoolz/itertoolz.c:8038)
        TypeError: unhashable type: 'CommentedMap'

**Comment by shashanks2008** [comment]
Somehow, I am able to use conda info command. Some of the things I found that, I am using the Company's Computer which does not allow to access Internet from the command prompt. And virtualization is not enabled in the BIOS. Is it still possible to use tensorflow on the System?

    C:\WINDOWS\system32>conda info
    Current conda install:
    
                   platform : win-64
              conda version : 4.3.8
           conda is private : False
          conda-env version : 4.3.8
        conda-build version : not installed
             python version : 3.6.0.final.0
           requests version : 2.12.4
           root environment : C:\ProgramData\Anaconda3  (writable)
        default environment : C:\ProgramData\Anaconda3
           envs directories : C:\ProgramData\Anaconda3\envs
              package cache : C:\ProgramData\Anaconda3\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                              https://repo.continuum.io/pkgs/free/noarch
                              https://repo.continuum.io/pkgs/r/win-64
                              https://repo.continuum.io/pkgs/r/noarch
                              https://repo.continuum.io/pkgs/pro/win-64
                              https://repo.continuum.io/pkgs/pro/noarch
                              https://repo.continuum.io/pkgs/msys2/win-64
                              https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/7 Wi
    ndows/6.1.7601

**Comment by kalefranz** [comment]
Please share the full contents of your .condarc file.
