### ISSUE TITLE
Conda doesn't run from Windows cmd when using conda install ...

### ISSUE THREAD

**Issue by rckmnt** [conda/conda#5751]
From both Windows cmd and Anaconda Prompt 'conda' command returns the same...

```
Traceback (most recent call last):
  File "C:\Users\Scott\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Scott\Anaconda2\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "C:\Users\Scott\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\Scott\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\Scott\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\Scott\Anaconda2\lib\site-packages\conda\connection.py", line 55, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1458, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1420, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Anaconda 4.4.0 (64-bit)| (default, May 11 2017, 13:17:26) [MSC v.1500 64 bit (AMD64)]'
```

**Comment by mingwandroid** [comment]
You have the official CPython in your `PATH` (`C:\Python27`), you need to remove that.

**Comment by rckmnt** [comment]
Classic mistake, thanks I appreciate it.
