### ISSUE TITLE
Error installing tensorflow using "conda install -c conda-forge tensorflow"

### ISSUE THREAD

**Issue by kambliketan** [conda/conda#5752]
traceback -
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Anaconda2\lib\site-packages\conda\instructions.py", line 48, in FETCH_CMD
    fetch_pkg(state['index'][arg + '.tar.bz2'])
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "C:\Anaconda2\lib\site-packages\conda\fetch.py", line 409, in download
    getLogger('fetch.start').info((fn[:14], size))
  File "C:\Anaconda2\lib\logging\__init__.py", line 1167, in info
    self._log(INFO, msg, args, **kwargs)
  File "C:\Anaconda2\lib\logging\__init__.py", line 1286, in _log
    self.handle(record)
  File "C:\Anaconda2\lib\logging\__init__.py", line 1296, in handle
    self.callHandlers(record)
  File "C:\Anaconda2\lib\logging\__init__.py", line 1336, in callHandlers
    hdlr.handle(record)
  File "C:\Anaconda2\lib\logging\__init__.py", line 759, in handle
    self.emit(record)
  File "C:\Anaconda2\lib\site-packages\conda\console.py", line 27, in emit
    fetch_progress.start()
  File "C:\Anaconda2\lib\site-packages\conda\progressbar\__init__.py", line 310, in start
    self.update(0)
  File "C:\Anaconda2\lib\site-packages\conda\progressbar\__init__.py", line 282, in update
    self.fd.write(self._format_line() + '\r')
LookupError: unknown encoding: cp65001

output of conda info

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 268, in execute
    """ % info_dict)
LookupError: unknown encoding: cp65001

**Comment by kambliketan** [comment]
issue got resolved when retried after closing and restarting new cmd prompt..
