### ISSUE TITLE
 conda remove issue

### ISSUE THREAD

**Issue by slvaill** [conda/conda#5758]
It dont want to remove vtk:

-----------------------------------------------------------------------------------------------------------
```
# conda list vtk
# packages in environment at /users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64:
#
pyvtk                     0.5.18                    <pip>
vtk                       7.1.1                    py27_0
```
 -----------------------------------------------------------------------------------------------------------
```
# conda remove --dry-run vtk --offline
Fetching package metadata:
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues
 
 Include the output of the command 'conda info' in your report.
 
 
 Traceback (most recent call last):
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/bin/conda", line 5, in <module>
     sys.exit(main())
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/lib/python2.7/site-packages/conda/cli/main.py", line 195, in main
     args_func(args, p)
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/lib/python2.7/site-packages/conda/cli/main.py", line 202, in args_func
     args.func(args, p)
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/lib/python2.7/site-packages/conda/cli/main_remove.py", line 155, in execute
    actions = plan.remove_actions(prefix, specs, index=index, pinned=args.pinned)
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/lib/python2.7/site-packages/conda/plan.py", line 466, in remove_actions
     if any(ms.match(fn) for ms in mss):
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/lib/python2.7/site-packages/conda/plan.py", line 466, in <genexpr>
     if any(ms.match(fn) for ms in mss):
   File "/users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/lib/python2.7/site-packages/conda/resolve.py", line 319, in match
     name, version, build = fn[:-8].rsplit('-', 2)
 ValueError: need more than 1 value to unpack
```
---------------------------------------------------------------------------------------------------------- 
```
# conda info
 Current conda install:
 
              platform : linux-64
         conda version : 3.18.3
   conda-build version : 1.18.1
        python version : 2.7.10.final.0
      requests version : 2.8.1
      root environment : /users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64  (writable)
   default environment : /users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64
      envs directories : /users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/envs
         package cache : /users5/appli/tools/anaconda/anaconda2-2.4.0-Linux-x86_64/pkgs
          channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                         https://repo.continuum.io/pkgs/free/noarch/
                         https://repo.continuum.io/pkgs/pro/linux-64/
                         https://repo.continuum.io/pkgs/pro/noarch/
           config file : /root/.condarc
     is foreign system : False
```
-----------------------------------------------------------------------------------------------------------

I am behind a firewall with no access to the listed channel repository

**Comment by kalefranz** [comment]
`conda update conda`
