### ISSUE TITLE
Issue - couldn't update conda package

### ISSUE THREAD

**Issue by jai2033shankar** [conda/conda#5767]
Hi, 

I tried to update the conda package, and before that I tried to open the Navigator, which did not pop the application. Post which I went to the update and it threw the below error.
Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/VISH/anaconda2  (writable)
    default environment : /Users/VISH/anaconda2
       envs directories : /Users/VISH/anaconda2/envs
                          /Users/VISH/.conda/envs
          package cache : /Users/VISH/anaconda2/pkgs
                          /Users/VISH/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/VISH/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.12.4 CPython/2.7.13 Darwin/16.6.0 OSX/10.12.5    
                UID:GID : 501:20

`$ /Users/VISH/anaconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 384, in _make_request
        httplib_response = conn.getresponse(buffering=True)
      File "/Users/VISH/anaconda2/lib/python2.7/httplib.py", line 1121, in getresponse
        response.begin()
      File "/Users/VISH/anaconda2/lib/python2.7/httplib.py", line 438, in begin
        version, status, reason = self._read_status()
      File "/Users/VISH/anaconda2/lib/python2.7/httplib.py", line 394, in _read_status
        line = self.fp.readline(_MAXLINE + 1)
      File "/Users/VISH/anaconda2/lib/python2.7/socket.py", line 480, in readline
        data = self._sock.recv(self._rbufsize)
      File "/Users/VISH/anaconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 246, in recv
        [self.socket], [], [], self.socket.gettimeout())
    error: (4, 'Interrupted system call')

**Comment by kalefranz** [comment]
Looks like just a ssl handshake timeout.  Were you able to move past this issue after a couple retries?
