### ISSUE TITLE
'conda info conda' raises KeyError: u'size' 

### ISSUE THREAD

**Issue by miketrenk** [conda/conda#5779]
conda version 4.3.23

`$ /opt/miniconda2/bin/conda info conda`

    Traceback (most recent call last):
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 634, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 313, in execute
        print_package_info(args.packages)
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 154, in print_package_info
        pretty_package(dist, r.index[dist])
      File "/opt/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 123, in pretty_package
        ('size', human_bytes(pkg['size'])),
    KeyError: u'size'

**Comment by ayusheesingh** [comment]
This is no longer an issue. I pulled the Docker container, installed conda version 4.3.23, and ran 'conda install conda'.

```
