### ISSUE TITLE
conda update problems

### ISSUE THREAD

**Issue by arwright3** [conda/conda#5781]
Hello,
Both ` conda update conda ` and ` conda update anaconda ` won't work.  It's also notable that conda appears to be running very slowly, even in searching for dependencies, etc. I'll put the output below:
```~$ conda update conda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /nfs/slac/kipac/fs1/u/awright/anaconda:

The following packages will be UPDATED:

    conda: 4.3.13-py27_0 --> 4.3.23-py27_0

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /nfs/slac/kipac/fs1/u/awright/anaconda  (writable)
    default environment : /nfs/slac/kipac/fs1/u/awright/anaconda
       envs directories : /nfs/slac/kipac/fs1/u/awright/anaconda/envs
                          /u/ki/awright/.conda/envs
          package cache : /nfs/slac/kipac/fs1/u/awright/anaconda/pkgs
                          /u/ki/awright/.conda/pkgs
           channel URLs : http://ssb.stsci.edu/astroconda/linux-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /u/ki/awright/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.12 Linux/2.6.32-431.29.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
                UID:GID : 12330:1092



`$ /nfs/slac/kipac/fs1/u/awright/anaconda/bin/conda update conda`




    Traceback (most recent call last):
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'/nfs/slac/kipac/fs1/u/awright/anaconda/pkgs/conda-4.3.23-py27_0/info/index.json'

~$ ls /nfs/slac/kipac/fs1/u/awright/anaconda/pkgs/conda-4.3.23-py27_0
bin  etc  info  lib
~$ ls /nfs/slac/kipac/fs1/u/awright/anaconda/pkgs/conda-4.3.23-py27_0/info/
recipe
~$ ls /nfs/slac/kipac/fs1/u/awright/anaconda/pkgs/conda-4.3.23-py27_0/info/recipe/
meta.yaml  meta.yaml.template  setup.py
~$ conda update anaconda
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /nfs/slac/kipac/fs1/u/awright/anaconda:

The following NEW packages will be INSTALLED:

    anaconda-project:   0.4.1-py27_0       
    chardet:            2.3.0-py27_0       
    isort:              4.2.5-py27_0       
    libiconv:           1.14-0             
    numpydoc:           0.6.0-py27_0       
    pcre:               8.39-1             
    scandir:            1.4-py27_0         
    seaborn:            0.7.1-py27_0       
    subprocess32:       3.2.7-py27_0       

The following packages will be UPDATED:

    anaconda:           custom-py27_0       --> 4.3.1-np111py27_0 
    anaconda-client:    1.5.1-py27_0        --> 1.6.0-py27_0      
    anaconda-navigator: 1.3.1-py27_0        --> 1.5.0-py27_0      
    astroid:            1.4.7-py27_0        --> 1.4.9-py27_0      
    backports_abc:      0.4-py27_0          --> 0.5-py27_0        
    beautifulsoup4:     4.5.1-py27_0        --> 4.5.3-py27_0      
    bokeh:              0.12.2-py27_0       --> 0.12.4-py27_0     
    boto:               2.42.0-py27_0       --> 2.45.0-py27_0     
    bottleneck:         1.1.0-np111py27_0   --> 1.2.0-np111py27_0 
    cairo:              1.12.18-6           --> 1.14.8-0          
    cffi:               1.7.0-py27_0        --> 1.9.1-py27_0      
    click:              6.6-py27_0          --> 6.7-py27_0        
    cloudpickle:        0.2.1-py27_0        --> 0.2.2-py27_0      
    conda:              4.3.13-py27_0       --> 4.3.23-py27_0     
    contextlib2:        0.5.3-py27_0        --> 0.5.4-py27_0      
    cryptography:       1.5-py27_0          --> 1.7.1-py27_0      
    curl:               7.49.0-1            --> 7.52.1-0          
    cython:             0.24.1-py27_0       --> 0.25.2-py27_0     
    cytoolz:            0.8.0-py27_0        --> 0.8.2-py27_0      
    dask:               0.11.0-py27_0       --> 0.13.0-py27_0     
    datashape:          0.5.2-py27_0        --> 0.5.4-py27_0      
    decorator:          4.0.10-py27_0       --> 4.0.11-py27_0     
    docutils:           0.12-py27_2         --> 0.13.1-py27_0     
    flask:              0.11.1-py27_0       --> 0.12-py27_0       
    flask-cors:         2.1.2-py27_0        --> 3.0.2-py27_0      
    fontconfig:         2.11.1-6            --> 2.12.1-2          
    freetype:           2.5.5-1             --> 2.5.5-2           
    gevent:             1.1.2-py27_0        --> 1.2.1-py27_0      
    glib:               2.43.0-1            --> 2.50.2-1          
    greenlet:           0.4.10-py27_0       --> 0.4.11-py27_0     
    harfbuzz:           0.9.39-1            --> 0.9.39-2          
    idna:               2.1-py27_0          --> 2.2-py27_0        
    ipaddress:          1.0.16-py27_0       --> 1.0.18-py27_0     
    ipykernel:          4.5.0-py27_0        --> 4.5.2-py27_0      
    ipywidgets:         5.2.2-py27_0        --> 5.2.2-py27_1      
    jdcal:              1.2-py27_1          --> 1.3-py27_0        
    jinja2:             2.8-py27_1          --> 2.9.4-py27_0      
    jpeg:               8d-2                --> 9b-0              
    jupyter_core:       4.2.0-py27_0        --> 4.2.1-py27_0      
    lazy-object-proxy:  1.2.1-py27_0        --> 1.2.2-py27_0      
    libffi:             3.2.1-0             --> 3.2.1-1           
    libpng:             1.6.22-0            --> 1.6.27-0          
    libtiff:            4.0.6-2             --> 4.0.6-3           
    libxcb:             1.12-0              --> 1.12-1            
    libxml2:            2.9.2-0             --> 2.9.4-0           
    libxslt:            1.1.28-0            --> 1.1.29-0          
    llvmlite:           0.13.0-py27_0       --> 0.15.0-py27_0     
    lxml:               3.6.4-py27_0        --> 3.7.2-py27_0      
    matplotlib:         1.5.3-np111py27_0   --> 2.0.0-np111py27_0 
    mkl:                11.3.3-0            --> 2017.0.1-0        
    mkl-service:        1.1.2-py27_2        --> 1.1.2-py27_3      
    multipledispatch:   0.4.8-py27_0        --> 0.4.9-py27_0      
    nbformat:           4.1.0-py27_0        --> 4.2.0-py27_0      
    nltk:               3.2.1-py27_0        --> 3.2.2-py27_0      
    notebook:           4.2.3-py27_0        --> 4.3.1-py27_0      
    numba:              0.28.1-np111py27_0  --> 0.30.1-np111py27_0
    numexpr:            2.6.1-np111py27_0   --> 2.6.1-np111py27_2 
    numpy:              1.11.1-py27_0       --> 1.11.3-py27_0     
    openpyxl:           2.3.2-py27_0        --> 2.4.1-py27_0      
    openssl:            1.0.2j-0            --> 1.0.2k-1          
    pandas:             0.18.1-np111py27_0  --> 0.19.2-np111py27_1
    partd:              0.3.6-py27_0        --> 0.3.7-py27_0      
    path.py:            8.2.1-py27_0        --> 10.0-py27_0       
    pathlib2:           2.1.0-py27_0        --> 2.2.0-py27_0      
    pexpect:            4.0.1-py27_0        --> 4.2.1-py27_0      
    pillow:             3.3.1-py27_0        --> 4.0.0-py27_0      
    pip:                8.1.2-py27_0        --> 9.0.1-py27_1      
    pixman:             0.32.6-0            --> 0.34.0-0          
    prompt_toolkit:     1.0.3-py27_0        --> 1.0.9-py27_0      
    psutil:             4.3.1-py27_0        --> 5.0.1-py27_0      
    py:                 1.4.31-py27_0       --> 1.4.32-py27_0     
    pycparser:          2.14-py27_1         --> 2.17-py27_0       
    pycurl:             7.43.0-py27_0       --> 7.43.0-py27_2     
    pyflakes:           1.3.0-py27_0        --> 1.5.0-py27_0      
    pylint:             1.5.4-py27_1        --> 1.6.4-py27_1      
    pyqt:               5.6.0-py27_0        --> 5.6.0-py27_2      
    pytables:           3.2.3.1-np111py27_0 --> 3.3.0-np111py27_0 
    pytest:             2.9.2-py27_0        --> 3.0.5-py27_0      
    python:             2.7.12-1            --> 2.7.13-0          
    python-dateutil:    2.5.3-py27_0        --> 2.6.0-py27_0      
    pytz:               2016.6.1-py27_0     --> 2016.10-py27_0    
    pyzmq:              15.4.0-py27_0       --> 16.0.2-py27_0     
    qt:                 5.6.0-0             --> 5.6.2-3           
    qtawesome:          0.3.3-py27_0        --> 0.4.3-py27_0      
    qtpy:               1.1.2-py27_0        --> 1.2.1-py27_0      
    ruamel_yaml:        0.11.14-py27_0      --> 0.11.14-py27_1    
    scikit-learn:       0.17.1-np111py27_2  --> 0.18.1-np111py27_1
    scipy:              0.18.1-np111py27_0  --> 0.18.1-np111py27_1
    sphinx:             1.4.6-py27_0        --> 1.5.1-py27_0      
    spyder:             3.0.0-py27_0        --> 3.1.2-py27_0      
    sqlalchemy:         1.0.13-py27_0       --> 1.1.5-py27_0      
    toolz:              0.8.0-py27_0        --> 0.8.2-py27_0      
    tornado:            4.4.1-py27_0        --> 4.4.2-py27_0      
    traitlets:          4.3.0-py27_0        --> 4.3.1-py27_0      
    werkzeug:           0.11.11-py27_0      --> 0.11.15-py27_0    
    wrapt:              1.10.6-py27_0       --> 1.10.8-py27_0     
    xlsxwriter:         0.9.3-py27_0        --> 0.9.6-py27_0      
    xlwt:               1.1.2-py27_0        --> 1.2.0-py27_0      
    xz:                 5.2.2-0             --> 5.2.2-1           
    zeromq:             4.1.4-0             --> 4.1.5-0           

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.12.4
       root environment : /nfs/slac/kipac/fs1/u/awright/anaconda  (writable)
    default environment : /nfs/slac/kipac/fs1/u/awright/anaconda
       envs directories : /nfs/slac/kipac/fs1/u/awright/anaconda/envs
                          /u/ki/awright/.conda/envs
          package cache : /nfs/slac/kipac/fs1/u/awright/anaconda/pkgs
                          /u/ki/awright/.conda/pkgs
           channel URLs : http://ssb.stsci.edu/astroconda/linux-64
                          http://ssb.stsci.edu/astroconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /u/ki/awright/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.12 Linux/2.6.32-431.29.2.el6.x86_64 Red Hat Enterprise Linux Server/6.9 glibc/2.12
                UID:GID : 12330:1092



`$ /nfs/slac/kipac/fs1/u/awright/anaconda/bin/conda update anaconda`




    Traceback (most recent call last):
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 86, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/nfs/slac/kipac/fs1/u/awright/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 105, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'/nfs/slac/kipac/fs1/u/awright/anaconda/pkgs/conda-4.3.23-py27_0/info/index.json'```

**Comment by kalefranz** [comment]
rm -rf /nfs/slac/kipac/fs1/u/awright/anaconda/pkgs/conda-4.3.23-py27_0

The package wasn't fully extracted somehow.

**Comment by kalefranz** [comment]
Leaving this issue open because we should have given you an error message with the solution instead of an ugly stack trace.

**Comment by sachinbiradar9** [comment]
I think this was fixed in recent version of conda
