### ISSUE TITLE
input anaconda prompt conda install -c conda-forge jieba, the follow fault appears

### ISSUE THREAD

**Issue by zhangmingyue12** [conda/conda#5788]
Traceback (most recent call last):
  File "D:\anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "D:\anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "D:\anaconda\lib\site-packages\conda\exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "D:\anaconda\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "D:\anaconda\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "D:\anaconda\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "D:\anaconda\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "D:\anaconda\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "D:\anaconda\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "D:\anaconda\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "D:\anaconda\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "D:\anaconda\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "D:\anaconda\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "D:\anaconda\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "D:\anaconda\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "D:\anaconda\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "D:\anaconda\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 41: ordinal not in range(128)

**Comment by mingwandroid** [comment]
I guess you have some non-ascii characters on your `PATH`? This is not possible with `Python2`.

**Comment by zhangmingyue12** [comment]
the follow is  my path, is there anything wrong

C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\;C:\Program Files (x86)\IBM\SPSS\Modeler\14\bin\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%JAVA_HOME%\bin;%JAVA_HOME%\jre1.8.0_101\bin;D:\matlab\runtime\win64;D:\matlab\bin;D:\matlab\polyspace\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;D:\anaconda;D:\anaconda\Scripts;D:\anaconda\Library\bin;

**Comment by zhangmingyue12** [comment]
the follow is my path, is there anything wrong. @mingwandroid 

C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in;C:\Program Files (x86)\IBM\SPSS\Modeler\14\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0;%JAVA_HOME%\bin;%JAVA_HOME%\jre1.8.0_101\bin;D:\matlab\runtime\win64;D:\matlab\bin;D:\matlab\polyspace\bin;C:\Program Files\MySQL\MySQL Utilities 1.6;D:\anaconda;D:\anaconda\Scripts;D:\anaconda\Library\bin;

**Comment by mingwandroid** [comment]
What is the value of JAVA_HOME and SYSTEMROOT?

**Comment by mingwandroid** [comment]
From cmd.exe, do:

`echo %PATH%`

**Comment by zhangmingyue12** [comment]
java_home:   D:\Java\jdk1.8.0_101
C:\Users\mingyue>echo %SYSTEMROOT%
C:\WINDOWS

**Comment by zhangmingyue12** [comment]
C:\Users\mingyue>echo %PATH%
C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\;C:\Program Files (x86)\IBM\SPSS\Modeler\14\bin\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Java\jdk1.8.0_101\bin;D:\Java\jdk1.8.0_101\jre1.8.0_101\bin;D:\matlab\runtime\win64;D:\matlab\bin;D:\matlab\polyspace\bin;C:\Program Files\MySQL\MySQL Utilities 1.6\;D:\anaconda;D:\anaconda\Scripts;D:\anaconda\Library\bin;C:\Program Files\MySQL\MySQL Server 5.7\bin；

**Comment by zhangmingyue12** [comment]
There is no non-ascii characters on your PATH @mingwandroid

**Comment by zhangmingyue12** [comment]
There is no non-ascii characters on my PATH @mingwandroid

**Comment by mingwandroid** [comment]
Somehow, at the point in ctypes/Lib.py where it reads your `PATH`, either it or the passed in `name` do appear to contain non-ascii:

https://github.com/python/cpython/blob/2.7/Lib/ctypes/util.py#L52-L53

Can you print both out by adding a line to do so above above line 53 in `D:\anaconda\lib\ctypes\util.py` please?

**Comment by mingwandroid** [comment]
I am asking you to open D:\anaconda\lib\ctypes\util.py in some text editor and change:
```
        for directory in os.environ['PATH'].split(os.pathsep):
            fname = os.path.join(directory, name)
```
to:
```
        for directory in os.environ['PATH'].split(os.pathsep):
            print(directory)
            fname = os.path.join(directory, name)
```

.. then re-run `conda install -c conda-forge jieba`

But actually, instead of `print(directory)` this should be more informative: `":".join("{:02x}".format(ord(c)) for c in directory)`

**Comment by zhangmingyue12** [comment]
the re-run results:
D:\anaconda\Library\bin
C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\
C:\Program Files (x86)\IBM\SPSS\Modeler\14\bin\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
D:\Java\jdk1.8.0_101\bin
D:\Java\jdk1.8.0_101\jre1.8.0_101\bin
D:\matlab\runtime\win64
D:\matlab\bin
D:\matlab\polyspace\bin
C:\Program Files\MySQL\MySQL Utilities 1.6\
D:\anaconda
D:\anaconda\Scripts
D:\anaconda\Library\bin
C:\Program Files\MySQL\MySQL Server 5.7\bin；
D:\anaconda\Library\bin
C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\
C:\Program Files (x86)\IBM\SPSS\Modeler\14\bin\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
D:\Java\jdk1.8.0_101\bin
D:\Java\jdk1.8.0_101\jre1.8.0_101\bin
D:\matlab\runtime\win64
D:\matlab\bin
D:\matlab\polyspace\bin
C:\Program Files\MySQL\MySQL Utilities 1.6\
D:\anaconda
D:\anaconda\Scripts
D:\anaconda\Library\bin
C:\Program Files\MySQL\MySQL Server 5.7\bin；
D:\anaconda\Library\bin
C:\Program Files (x86)\Cuminas\Document Express DjVu Plug-in\
C:\Program Files (x86)\IBM\SPSS\Modeler\14\bin\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
D:\Java\jdk1.8.0_101\bin
D:\Java\jdk1.8.0_101\jre1.8.0_101\bin
D:\matlab\runtime\win64
D:\matlab\bin
D:\matlab\polyspace\bin
C:\Program Files\MySQL\MySQL Utilities 1.6\
D:\anaconda
D:\anaconda\Scripts
D:\anaconda\Library\bin
C:\Program Files\MySQL\MySQL Server 5.7\bin；
Traceback (most recent call last):
  File "D:\anaconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "D:\anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "D:\anaconda\lib\site-packages\conda\exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "D:\anaconda\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "D:\anaconda\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "D:\anaconda\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "D:\anaconda\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "D:\anaconda\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "D:\anaconda\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "D:\anaconda\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "D:\anaconda\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "D:\anaconda\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "D:\anaconda\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "D:\anaconda\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "D:\anaconda\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "D:\anaconda\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "D:\anaconda\lib\ctypes\util.py", line 54, in find_library
    fname = os.path.join(directory, name)
  File "D:\anaconda\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 41: ordinal not in range(128)

**Comment by mingwandroid** [comment]
Here is the problem: `；` is *not* and ascii `;` it is [this](http://unicodelookup.com/#；/1).

**Comment by zhangmingyue12** [comment]
Could you explain it further

**Comment by msarahan** [comment]
There are characters that look similar, but actually are different.  You have copy/pasted from a place that had the unicode character, not the ascii character for semicolon.

**Comment by mingwandroid** [comment]
In your `PATH`, this entry is incorrect `C:\Program Files\MySQL\MySQL Server 5.7\bin；`, specifically the semicolon at the end is not a semicolon (ascii), but instead a fullwidth semicolon (non-ascii).

You should be able to just delete the last (thing that looks like a) semicolon from your Windows `PATH`.

**Comment by zhangmingyue12** [comment]
thanks a lot @mingwandroid  @msarahan .The fault is here unexpectedly

**Comment by mingwandroid** [comment]
@zhangmingyue12, please close if this is solved.

**Comment by zhangmingyue12** [comment]
ok. I have removed that line

**Comment by mingwandroid** [comment]
.. and your problem is fixed? Please close this issue if so.

**Comment by zhangmingyue12** [comment]
sorry，I am the first time to use this, I am not familiar with the rule.

**Comment by MigoJ** [comment]
D:\Anacoda2\Library\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Calibre2\
D:\软件\Scripts\
D:\软件\
D:\Anacoda2\Library\bin
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Program Files (x86)\Calibre2\
D:\软件\Scripts\
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

**Comment by MigoJ** [comment]
Hello ,could you helpy me the same issue, this is follow your instruction,but cannot find root cause

**Comment by zhangmingyue12** [comment]
My problem occurred when I installed the python package.The warning information is''UnicodeDecodeError: 'ascii' codec can't decode byte 0xa3 in position 41: ordinal not in range(128)''. 
In my PATH, the semicolon at the end is not a semicolon (ascii), but instead a fullwidth semicolon (non-ascii).You could check your Windows PATH whether there is fullwidth punctuation or not.

**Comment by MigoJ** [comment]
As you can see my results ,which dont have any puntuation issues

**Comment by mingwandroid** [comment]
I am not sure why you have commented in two issues, it will not get your to a solution any quicker.

You cannot have any entires in your PATH with non-ascii. You have several starting with "D:\软件" they must all be removed

**Comment by zhangmingyue12** [comment]
The running catalog shouldn't have Chinese charactor. You can try to rename it'D:\软件'

**Comment by MigoJ** [comment]
Sorry this is my first time to comment .
I rename 'D:\软件' ad Software,but it is not work.
Result is the same:
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "D:\Anacoda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "D:\Anacoda2\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "D:\Anacoda2\lib\site-packages\conda\exceptions.py", line 634, in handle_
exception
    print_unexpected_error_message(e)
  File "D:\Anacoda2\lib\site-packages\conda\exceptions.py", line 596, in print_u
nexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "D:\Anacoda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_
info_dict
    from ..connection import user_agent
  File "D:\Anacoda2\lib\site-packages\conda\connection.py", line 12, in <module>

    from requests import Session, __version__ as REQUESTS_VERSION
  File "D:\Anacoda2\lib\site-packages\requests\__init__.py", line 52, in <module
>
    from .packages.urllib3.contrib import pyopenssl
  File "D:\Anacoda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenss
l.py", line 47, in <module>
    from cryptography import x509
  File "D:\Anacoda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in
 <module>
    from cryptography.x509.base import (
  File "D:\Anacoda2\lib\site-packages\cryptography\x509\base.py", line 16, in <m
odule>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "D:\Anacoda2\lib\site-packages\cryptography\x509\extensions.py", line 14,
 in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "D:\Anacoda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "D:\Anacoda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, i
n <module>
    from ._int import inverse_mod
  File "D:\Anacoda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "D:\Anacoda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line
 31, in <module>
    libcrypto_path = find_library('crypto')
  File "D:\Anacoda2\lib\ctypes\util.py", line 52, in find_library
    fname = os.path.join(directory, name)
  File "D:\Anacoda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc8 in position 1: ordinal
not in range(128)

**Comment by mingwandroid** [comment]
It is not about renaming the folder. It is about editing your Windows `PATH` environment variable.

**Comment by MigoJ** [comment]
Thanks so much, i changed editing the PATH, Issue have been solved.
But now there is other issue:
AttributeError                            Traceback (most recent call last)
<ipython-input-4-c7f3059b4cb2> in <module>()
      6 enrollments=[ ]
      7 f=open("enrollments.csv","rb")
----> 8 reader=unicodecsv.Dictreader(f)
      9 
     10 for row in reader:

AttributeError: 'module' object has no attribute 'Dictreader'

**Comment by mingwandroid** [comment]
You need to ask about this on a general Python forum I think, something like https://www.reddit.com/r/learnpython/ may be useful?
