### ISSUE TITLE
Cannot use conda to upgrade any package

### ISSUE THREAD

**Issue by xfsm1912** [conda/conda#5789]
When I try to upgrade some package in my macbook, such as tensorflow and scikit-learn, the conda command doesn't work and return some errors:

[Jianhua@d-172-26-6-83~]$ conda install -c conda-forge scikit-learn
Fetching package metadata .......An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.1.17
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/Jianhua/anaconda  (writable)
    default environment : /Users/Jianhua/anaconda
       envs directories : /Users/Jianhua/anaconda/envs
          package cache : /Users/Jianhua/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/Jianhua/.condarc
           offline mode : False

`$ /Users/Jianhua/anaconda/bin/conda install -c conda-forge scikit-learn`

    Traceback (most recent call last):
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 238, in install
        prefix=prefix)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 300, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/concurrent/futures/_base.py", line 405, in result
        return self.__get_result()
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/concurrent/futures/thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 75, in func
        res = f(*args, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 117, in fetch_repodata
        timeout=(6.1, 60))
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 438, in send
        timeout=timeout
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
        chunked=chunked)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/Users/Jianhua/anaconda/lib/python2.7/httplib.py", line 1042, in request
        self._send_request(method, url, body, headers)
      File "/Users/Jianhua/anaconda/lib/python2.7/httplib.py", line 1082, in _send_request
        self.endheaders(body)
      File "/Users/Jianhua/anaconda/lib/python2.7/httplib.py", line 1038, in endheaders
        self._send_output(message_body)
      File "/Users/Jianhua/anaconda/lib/python2.7/httplib.py", line 882, in _send_output
        self.send(msg)
      File "/Users/Jianhua/anaconda/lib/python2.7/httplib.py", line 858, in send
        self.sock.sendall(data)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 313, in sendall
        sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 301, in _send_until_done
        return self.connection.send(data)
      File "/Users/Jianhua/anaconda/lib/python2.7/site-packages/OpenSSL/SSL.py", line 947, in send
        raise TypeError("data must be a byte string")
    TypeError: data must be a byte string

Can someone tell me how to fix it?
Thank you

**Comment by kalefranz** [comment]
`conda update conda`
