### ISSUE TITLE
LINKING PACKAGE step looks for 'source' in the wrong location in Docker

### ISSUE THREAD

**Issue by lfam** [conda/conda#5797]
I'm trying to get started with conda in Docker.

Creating a new environment with some packages works fine on Debian, but within Docker, it fails in the `LINKING PACKAGE` step when it looks for packages in the read-only directory that contains conda itself:

```
===> LINKING PACKAGE: defaults::openssl-1.0.2l-0 <===
  prefix=/.conda/envs/myconda3
  source=/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/pkgs/openssl-1.0.2l-0


$ /bin/bash -x /.conda/envs/myconda3/bin/.openssl-post-link.sh
==> cwd: /.conda/envs/myconda3/bin <== 
==> exit code: 127 <== 
==> stdout <== 
b''
==> stderr <== 
b'+ cp /.conda/envs/myconda3/lib/libcrypto.so.1.0.0 /.conda/envs/myconda3/lib/libcrypto.so.1.0.0-tmp\n+ mv /.conda/envs/myconda3/lib/libcrypto.so.1.0.0-tmp /.conda/envs/myconda3/lib/libcrypto.so.1.0.0\n+ /.conda/envs/myconda3/bin/.openssl-libcrypto-fix /.conda/envs/myconda3\n/.conda/envs/myconda3/bin/.openssl-post-link.sh: line 7: /.conda/envs/myconda3/bin/.openssl-libcrypto-fix: No such file or directory\n'
```

That path in the 3rd line, `/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/pkgs/openssl-1.0.2l-0`, is where conda itself is installed, and `openssl-1.0.2l-0` cannot be written to there.

On Debian, it looks in the right place:
```
===> LINKING PACKAGE: defaults::openssl-1.0.2l-0 <===
  prefix=/home/leo/.conda/envs/myconda4
  source=/home/leo/.conda/pkgs/openssl-1.0.2l-0
```

Below is the output of `conda info` and the full output of the command I am running. Do you have any advice?

```

bash-4.4# conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16  (read only)
    default environment : /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16
       envs directories : /.conda/envs
                          /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/envs
          package cache : /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/pkgs
                          /.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.3 Linux/4.12.4+ / glibc/2.25
                UID:GID : 0:0

bash-4.4# conda create -v -n myconda3 numpy
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment /.conda/envs/myconda3:

The following NEW packages will be INSTALLED:

    mkl:        2017.0.3-0   
    numpy:      1.13.1-py36_0
    openssl:    1.0.2l-0     
    pip:        9.0.1-py36_1 
    python:     3.6.2-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xz:         5.2.2-1      
    zlib:       1.2.8-3      

Proceed ([y]/n)? y

()

===> LINKING PACKAGE: defaults::mkl-2017.0.3-0 <===
  prefix=/.conda/envs/myconda3
  source=/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/pkgs/mkl-2017.0.3-0


===> LINKING PACKAGE: defaults::openssl-1.0.2l-0 <===
  prefix=/.conda/envs/myconda3
  source=/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/pkgs/openssl-1.0.2l-0


$ /bin/bash -x /.conda/envs/myconda3/bin/.openssl-post-link.sh
==> cwd: /.conda/envs/myconda3/bin <==
==> exit code: 127 <==
==> stdout <==
b''
==> stderr <==
b'+ cp /.conda/envs/myconda3/lib/libcrypto.so.1.0.0 /.conda/envs/myconda3/lib/libcrypto.so.1.0.0-tmp\n+ mv /.conda/envs/myconda3/lib/libcrypto.so.1.0.0-tmp /.conda/envs/myconda3/lib/libcrypto.so.1.0.0\n+ /.conda/envs/myconda3/bin/.openssl-libcrypto-fix /.conda/envs/myconda3\n/.conda/envs/myconda3/bin/.openssl-post-link.sh: line 7: /.conda/envs/myconda3/bin/.openssl-libcrypto-fix: No such file or directory\n'


An error occurred while installing package 'defaults::openssl-1.0.2l-0'.
LinkError: post-link failed for: defaults::openssl-1.0.2l-0

Attempting to roll back.


===> REVERSING PACKAGE LINK: defaults::openssl-1.0.2l-0 <===
  prefix=/.conda/envs/myconda3


===> REVERSING PACKAGE LINK: defaults::mkl-2017.0.3-0 <===
  prefix=/.conda/envs/myconda3


An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



overtaking stderr and stdout

stderr and stdout yielding back

Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.5.3.final.0
       requests version : 2.13.0
       root environment : /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16  (read only)
    default environment : /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16
       envs directories : /.conda/envs
                          /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/envs
          package cache : /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/pkgs
                          /.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.13.0 CPython/3.5.3 Linux/4.12.4+ / glibc/2.25
                UID:GID : 0:0



`$ /gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/bin/.conda-real create -v -n myconda3 numpy`




    Traceback (most recent call last):
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/core/link.py", line 498, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/gateways/subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['/bin/bash', '-x', '/.conda/envs/myconda3/bin/.openssl-post-link.sh']' returned non-zero exit status 127
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/core/link.py", line 325, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/core/link.py", line 514, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link failed for: defaults::openssl-1.0.2l-0
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/core/link.py", line 279, in execute
        pkg_data, actions)
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/core/link.py", line 342, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link failed for: defaults::openssl-1.0.2l-0
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/plan.py", line 809, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/gnu/store/f2dr9xbimg93pljm7xgmqb4cm5bxy98r-conda-4.3.16/lib/python3.5/site-packages/conda-4.3.16-py3.5.egg/conda/core/link.py", line 295, in execute
        rollback_excs,
    conda.CondaMultiError: post-link failed for: defaults::openssl-1.0.2l-0
```

**Comment by kalefranz** [comment]
This is an error related to the post-link script in the openssl package.  Moving to different issue tracker.

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#6588
