### ISSUE TITLE
`conda update conda` and `conda create` fail due to lack of write permission in package cache

### ISSUE THREAD

**Issue by arnold-jr** [conda/conda#5803]
I have a multiuser Anaconda installation and I am in the ownership group of the installation path, including the package cache directory that is listed first. However, I don't have write access to the JSON files in this package cache and bump into the following error:

```
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/opt/easybuild/software/Core/Anaconda2/4.3.1' using path '/opt/easybuild/software/Core/Anaconda2/4.3.1/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/opt/easybuild/software/Core/Anaconda2/4.3.1' using path '/opt/easybuild/software/Core/Anaconda2/4.3.1/conda-meta/history'
Current conda install:

               platform : linux-64
          conda version : 4.3.18
       conda is private : False
      conda-env version : 4.3.18
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /opt/easybuild/software/Core/Anaconda2/4.3.1  (writable)
    default environment : /opt/easybuild/software/Core/Anaconda2/4.3.1
       envs directories : /opt/easybuild/software/Core/Anaconda2/4.3.1/envs
                          /home/arnoldjr/.conda/envs
          package cache : /opt/easybuild/software/Core/Anaconda2/4.3.1/pkgs
                          /home/arnoldjr/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.18 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-642.6.2.el6.x86_64 CentOS/6.8 glibc/2.12    
                UID:GID : 30100:36014

`$ /opt/easybuild/software/Core/Anaconda2/4.3.1/bin/conda update conda --dry-run --debug`




    Traceback (most recent call last):
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/opt/easybuild/software/Core/Anaconda2/4.3.1/lib/python2.7/site-packages/conda/core/repodata.py", line 469, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/opt/easybuild/software/Core/Anaconda2/4.3.1/pkgs/cache/db552c1e.json'
```

This is especially perplexing because I've created environments as recently as last week without changing any file permissions or changing conda versions. I've concluded that other users in different groups can create conda environments as expected.

Thanks!

**Comment by arnold-jr** [comment]
Upon further review, this is directly related to #4621. Closing, since the fix is to configure `pkgs_dirs` to point to a user-writeable location.
