### ISSUE TITLE
Issue on OSX

### ISSUE THREAD

**Issue by joma94** [conda/conda#5817]
Hi

Had this message on a mac when doing a "conda update conda":

Current conda install:

               platform : osx-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 1.18.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
                          /Users/jm/.conda/envs
          package cache : //anaconda/pkgs
                          /Users/jm/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/jm/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20

`$ //anaconda/bin/conda update conda`

    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "//anaconda/lib/python2.7/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "//anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 70, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "//anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 459, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "//anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 105, in func
        res = f(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 436, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "//anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 134, in fetch_repodata_remote_request
        timeout=timeout)
      File "//anaconda/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "//anaconda/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
        timeout=timeout
      File "//anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 594, in urlopen
        chunked=chunked)
      File "//anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 350, in _make_request
        self._validate_conn(conn)
      File "//anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 835, in _validate_conn
        conn.connect()
      File "//anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 323, in connect
        ssl_context=context)
      File "//anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py", line 324, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "//anaconda/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 419, in wrap_socket
        rd, _, _ = select.select([sock], [], [], sock.gettimeout())
    error: (4, 'Interrupted system call')

Then I did a "conda update anaconda":

Jrns-MacBook-Pro:~ jm$ conda update anaconda
Fetching package metadata .........
Solving package specifications: .

Package plan for installation in environment //anaconda:

The following packages will be UPDATED:

    conda: 4.3.13-py27_0 --> 4.3.24-py27_0

Proceed ([y]/n)? y

conda-4.3.24-p 100% |##########################################################################################| Time: 0:00:00   4.90 MB/s
Jrns-MacBook-Pro:~ jm$ 

Then I tried a "conda update conda again":

Jrns-MacBook-Pro:~ jm$ conda update conda
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at //anaconda:
#
conda                     4.3.24                   py27_0  
Jrns-MacBook-Pro:~ jm$ conda update anaconda
Fetching package metadata .........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at //anaconda:
#
anaconda                  custom                   py27_0  
Jrns-MacBook-Pro:~ jm$

**Comment by kalefranz** [comment]
Can you give us the output of `conda list` and explain exactly what you think the problem is?  I recognize you had that stack trace there, but on the next operation, it looks like conda went ahead and updated itself anyway.

**Comment by joma94** [comment]
Hi kalefranz
Thanks for your quick response

I'm really unsure if I have a problem, I can't find any malfunctioning.

**Comment by kalefranz** [comment]
Seems like there's nothing wrong now.
