### ISSUE TITLE
Unable to run commands in Anaconda prompt

### ISSUE THREAD

**Issue by murrbe** [conda/conda#5848]
Update and create both return following error

Current conda install:

               platform : win-32
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\murrbe\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\murrbe\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\murrbe\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\murrbe\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create -n tensorflow python 3.6`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 150, in fetch_repodata_remote_request
        json_str = maybe_decompress(filename, resp.content)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 148, in maybe_decompress
        if filename.endswith('.bz2')
      File "C:\ProgramData\Anaconda3\lib\bz2.py", line 350, in decompress
        res = decomp.decompress(data)
    OSError: Invalid data stream

**Comment by kalefranz** [comment]
`conda clean --tarballs`

**Comment by kalefranz** [comment]
Leaving this issue open, because we should be catching stack traces like these, removing the bad tarball, and exiting with a descriptive user message.

**Comment by aidsj** [comment]
I have similar issue.

**Current conda install**:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\xu79062\AppData\Local\Continuum\anaconda3  (writable)
    default environment : C:\Users\xu79062\AppData\Local\Continuum\anaconda3
       envs directories : C:\Users\xu79062\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\xu79062\AppData\Local\conda\conda\envs
                          C:\Users\xu79062\.conda\envs
          package cache : C:\Users\xu79062\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\xu79062\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\xu79062\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.10586
          administrator : False

**Error**:

conda update --all`

    Traceback (most recent call last):
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 156, in fetch_repodata_remote_request
        json_str = maybe_decompress(filename, resp.content)
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\repodata.py", line 154, in maybe_decompress
        if filename.endswith('.bz2')
      File "C:\Users\xu79062\AppData\Local\Continuum\anaconda3\lib\bz2.py", line 350, in decompress
        res = decomp.decompress(data)
    OSError: Invalid data stream


I have uninstall and reinstall the Anaconda but no success.

conda clean --tarballs is not working for me?

FYI, I am behind a corporate firewall and set ssl_verify to false.
Is there any other thing I should try?
