### ISSUE TITLE
Using conda 4.4.0rc1, conda activate does not exist and conda update crashes

### ISSUE THREAD

**Issue by bheklilr** [conda/conda#5849]
Output of `conda info` (sensitive info scrubbed)
```
     active environment : None
       user config file : C:\Users\username\.condarc
 populated config files : C:\Users\username\.condarc
          conda version : 4.4.0rc1
    conda-build version : 2.1.17
         python version : 3.6.1.final.0
       base environment : C:\Users\username\company-miniconda  (writable)
           channel URLs : http://conda-server-host/conda/workgroup/win-64
                          http://conda-server-host/conda/workgroup/noarch
                          http://conda-server-host/conda/anaconda/win-64
                          http://conda-server-host/conda/anaconda/noarch
                          http://conda-server-host/conda/company/win-64
                          http://conda-server-host/conda/company/noarch
                          http://conda-server-host/conda/username/win-64
                          http://conda-server-host/conda/username/noarch
                          http://conda-server-host/conda/conda-forge/win-64
                          http://conda-server-host/conda/conda-forge/noarch
          package cache : C:\Users\username\company-miniconda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
       envs directories : C:\envs
                          C:\Users\username\company-miniconda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
                          C:\Users\username\.conda\envs
               platform : win-64
             user-agent : conda/4.4.0rc1 requests/2.14.2 CPython/3.6.1 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
Output of `conda --version`: `conda 4.4.0rc1`

Output of `conda --help`:
```
usage: conda-script.py [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean        Remove unused packages and caches.
    config       Modify configuration values in .condarc. This is modeled
                 after the git config command. Writes to the user .condarc
                 file (C:\Users\astevens\.condarc) by default.
    create       Create a new conda environment from a list of specified
                 packages.
    help         Displays a list of available conda commands and their help
                 strings.
    info         Display information about current conda install.
    install      Installs a list of packages into a specified conda
                 environment.
    list         List linked packages in a conda environment.
    package      Low-level conda package utility. (EXPERIMENTAL)
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove. See conda remove --help.
    search       Search for packages and display associated information. The
                 input is a MatchSpec, a query language for conda packages.
                 See examples below.
    update       Updates conda packages to the latest compatible version. This
                 command accepts a list of package names and updates them to
                 the latest versions that are compatible with all other
                 packages in the environment. Conda attempts to install the
                 newest versions of the requested packages. To accomplish
                 this, it may update some packages that are already installed,
                 or install additional packages. To prevent existing packages
                 from updating, use the --no-update-deps option. This may
                 force conda to install older versions of the requested
                 packages, and it does not prevent additional dependency
                 packages from being installed. If you wish to skip dependency
                 checking altogether, use the '--force' option. This may
                 result in an environment with incompatible packages, so this
                 option must be used with great caution.
    upgrade      Alias for conda update. See conda update --help.

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.

other commands, such as "conda build", are available when additional conda
packages (e.g. conda-build) are installed
```
---
When I run `conda activate --help` I get the following error
```
Traceback (most recent call last):
  File "C:\Users\username\company-miniconda\lib\site-packages\conda\cli\main.py", line 176, in main
    raise CommandNotFoundError(argv1)
conda.exceptions.CommandNotFoundError: 'activate'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\username\company-miniconda\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\username\company-miniconda\lib\site-packages\conda\cli\main.py", line 178, in main
    from ..exceptions import handle_exception
ImportError: cannot import name 'handle_exception'
```
Which makes sense as conda activate does not seem to be an available command.

If I run `conda update -c conda-canary -n root --all`, it shows `Solving environment: {spinny}` for a bit before I get a window that pops up showing that Python crashed, no traceback:

![image](https://user-images.githubusercontent.com/1035817/29460783-d18ac438-83ee-11e7-942a-e979762b51c6.png)

And I get the same behavior if I try to do `conda install conda=4.3`, so it looks like I'm going to have to manually reinstall to fix this behavior.  If I need to provide any more info, please let me know!

Thanks,
Aaron

**Comment by kalefranz** [comment]
Thanks for the report. Looking into it in the next hour or two. Are you using the Anaconda Prompt (activated cmd.exe shell)?

**Comment by kalefranz** [comment]
You might be able to get back with `conda install conda=4.3 --no-deps`

If you do, there, you'll probably want to do `conda clean -i` after that. There's a bug in a regex in 4.3.24 that we'll have fixed in the next 4.3 release.

**Comment by kalefranz** [comment]
Really appreciate the help with 4.4. We'll get this all straightened out asap

**Comment by bheklilr** [comment]
I see the same behavior in normal cmd.exe and in the Anaconda shell.

The `--no-deps` trick worked, thanks for that!  I just got landed with a high priority has-to-be-done-today task, and that saved me a lot of time.

**Comment by kalefranz** [comment]
When you're under less pressure, my reinstalling 4.4 and giving me two pieces of information?

1. `where conda`
2. The same update you were doing that caused conda to crash, plus the flag `-vvv`

**Comment by kalefranz** [comment]
Oh, after that command prompt crashes, it might just be gone (because Windows). You might have to pipe the output to a file with `> save-me.txt` on the end of the command.

**Comment by bheklilr** [comment]
`where conda`:
```
C:\Users\username\company-miniconda\Scripts\conda
C:\Users\username\company-miniconda\Scripts\conda.bat
C:\Users\username\company-miniconda\Scripts\conda.exe
```
(I have built a version with constructor and have intentionally installed miniconda into that location)

The output of `conda update -c conda-canary -y --all -vvv` is around 800KB of text, and interestingly it runs without crashing.

With `-vv` also runs without crashing, with a large output.

With `-v` outputs very little, just that it's solving the environment, then saying all requested packages already installed, and finishes without crashing.

Running it again without any `-v` reliably reproduces the crash.

I can send you the outputs of `-vvv` and `-vv` if you'd like, but I'd prefer via email since it contains the names of internal packages and hostnames.  I can try sanitizing it but that would take time and I might miss some.

**Comment by kalefranz** [comment]
Would prefer the output of the full thing, -vvv for a crash.  Python is segfaulting, it's a known issue, but so far I've been unable to isolate it. Incredibly frustrating. Email me directly at kfranz@continuum.io.

**Comment by bheklilr** [comment]
Just sent the email.

**Comment by mingwandroid** [comment]
I believe I have fixed this and would appreciate your feedback.

From Linux, macOS or MSYS2/Git-for-Windows/Cygwin:

```
CONDA_AUTO_UPDATE_CONDA=False conda install -c c3i_test2 pycosat
```

From Windows cmd.exe:

```
set CONDA_AUTO_UPDATE_CONDA=False
conda install -c c3i_test2 pycosat
```
