### ISSUE TITLE
Exception occurred while creating env

### ISSUE THREAD

**Issue by drewkerwin** [conda/conda#5872]
$conda env create -f requirements/aind-dl-mac-linux.yml

Solving package specifications: ..........
Fetching packages ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/dkerwin/anaconda  (writable)
    default environment : /Users/dkerwin/anaconda
       envs directories : /Users/dkerwin/anaconda/envs
          package cache : /Users/dkerwin/anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/osx-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : None
           offline mode : False

`$ /Users/dkerwin/anaconda/bin/conda-env create -f requirements/aind-dl-mac-linux.yml`

    Traceback (most recent call last):
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 378, in download
        resp.raise_for_status()
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/requests/models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/damianavila82/osx-64/rise-4.0.0b1-py35_0.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 32, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/fetch.py", line 387, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/damianavila82/osx-64/rise-4.0.0b1-py35_0.tar.bz2: https://conda.anaconda.org/damianavila82/osx-64/rise-4.0.0b1-py35_0.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 39, in install
        raise CondaSystemExit('Exiting', e)
      File "/Users/dkerwin/anaconda/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/Users/dkerwin/anaconda/lib/python3.5/site-packages/conda_env/installers/conda.py", line 37, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/damianavila82/osx-64/rise-4.0.0b1-py35_0.tar.bz2: https://conda.anaconda.org/damianavila82/osx-64/rise-4.0.0b1-py35_0.tar.bz2

dkerwin@aind2-dl:

**Comment by tyler-thetyrant** [comment]
You are using a very old version of conda. We are currently at 4.3.25.  You can either try `conda update conda` or reinstall miniconda.

**Comment by kalefranz** [comment]
`anaconda logout` of

    conda config --set add_anaconda_token false

Also `conda update conda`
