### ISSUE TITLE
"invalid credentials" error in conda after upgrade to version 4.3.25

### ISSUE THREAD

**Issue by stefanseefeld** [conda/conda#5873]
I'm observing an exception involving 
```
requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/r/win-64/repodata.json
```
when running `conda install ...` commands (even when no private channels are involved at all).
If been seeing this on different Windows 64 machines (starting on a build server, then on my own local VM.
Note that I started by installing an official Miniconda3, at which point everything worked fine. Only after I ran `conda install conda` to upgrade to the latest (to work around another conda bug) did the above error start to occur. The current conda version is 4.3.25

**Comment by kalefranz** [comment]
Is that the full output?  Or is there more to the error message?

**Comment by stefanseefeld** [comment]
There is of course more:
```
    Traceback (most recent call last):                                                                                                                                                                                                                                       
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 141, in fetch_repodata_remote_request                                                                                                                                                      
        resp.raise_for_status()                                                                                                                                                                                                                                              
      File "C:\Users\builder\Mini\lib\site-packages\requests\models.py", line 928, in raise_for_status                                                                                                                                                                       
        raise HTTPError(http_error_msg, response=self)                                                                                                                                                                                                                       
    requests.exceptions.HTTPError: 401 Client Error: UNAUTHORIZED for url: https://conda.anaconda.org/t/<TOKEN>/r/win-64                                                                                                                                                     
/repodata.json                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                             
    During handling of the above exception, another exception occurred:                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                             
    Traceback (most recent call last):                                                                                                                                                                                                                                       
      File "C:\Users\builder\Mini\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler                                                                                                                                                               
        return_value = func(*args, **kwargs)                                                                                                                                                                                                                                 
      File "C:\Users\builder\Mini\lib\site-packages\conda\cli\main.py", line 137, in _main                                                                                                                                                                                   
        exit_code = args.func(args, p)                                                                                                                                                                                                                                       
      File "C:\Users\builder\Mini\lib\site-packages\conda\cli\main_install.py", line 80, in execute                                                                                                                                                                          
        install(args, parser, 'install')                                                                                                                                                                                                                                     
      File "C:\Users\builder\Mini\lib\site-packages\conda\cli\install.py", line 221, in install                                                                                                                                                                              
        unknown=index_args['unknown'], prefix=prefix)                                                                                                                                                                                                                        
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\index.py", line 93, in get_index                                                                                                                                                                              
        index = fetch_index(channel_priority_map, use_cache=use_cache)                                                                                                                                                                                                       
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\index.py", line 112, in fetch_index                                                                                                                                                                           
        repodatas = collect_all_repodata(use_cache, tasks)                                                                                                                                                                                                                   
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata                                                                                                                                                                
        repodatas = _collect_repodatas_serial(use_cache, tasks)                                                                                                                                                                                                              
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial                                                                                                                                                          
        for url, schan, pri in tasks]                                                                                                                                                                                                                                        
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>                                                                                                                                                                         
        for url, schan, pri in tasks]                                                                                                                                                                                                                                        
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 109, in func                                                                                                                                                                               
        res = f(*args, **kwargs)                                                                                                                                                                                                                                             
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata                                                                                                                                                                     
        mod_etag_headers.get('_mod'))                                                                                                                                                                                                                                        
      File "C:\Users\builder\Mini\lib\site-packages\conda\core\repodata.py", line 314, in fetch_repodata_remote_request                                                                                                                                                      
        e.response)                                                                                                                                                                                                                                                          
    conda.exceptions.CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/r/win-64/repodata.json>                                                                                                                                                       
    Elapsed: 00:00.258239                                                                                                                                                                                                                                                    
    CF-RAY: 392fd0c1ca3258fd-DFW                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                             
    The remote server has indicated you are using invalid credentials for this channel.                                                                                                                                                                                      
                                                                                                                                                                                                                                                                             
    If the remote site is anaconda.org or follows the Anaconda Server API, you                                                                                                                                                                                               
    will need to                                                                                                                                                                                                                                                             
      (a) remove the invalid token from your system with `anaconda logout`, optionally                                                                                                                                                                                       
          followed by collecting a new token with `anaconda login`, or                                                                                                                                                                                                       
      (b) provide conda with a valid token directly.                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                             
    Further configuration help can be found at <https://conda.io/docs/config.html>.  
```

**Comment by stefanseefeld** [comment]
Note that nowhere in my .condarc am I referring to a private channel, so I'm not sure where the URL
`https://conda.anaconda.org/t/<TOKEN>/r/win-64/repodata.json` is coming from.

**Comment by kalefranz** [comment]
Did you try `anaconda logout`?

**Comment by stefanseefeld** [comment]
`anaconda-client` isn't installed (and I can't install it due to the above error).

**Comment by kalefranz** [comment]
Oh interesting.  I'm guessing it was at one time.

What's the output of

    C:\Users\builder\Mini\python.exe -m conda.gateways.anaconda_client

?

If I have the path to the conda python wrong there, please correct it :)

**Comment by kalefranz** [comment]
Really am interested in that output.  After that though,

    conda config --set add_anaconda_token false

should ignore that expired token that's on your file system.

Also, I'm guessing between `conda config --show` and `conda config --show-sources`, you'll be able to figure out where you have that `r` channel listed.

**Comment by stefanseefeld** [comment]
`{u'https://api.anaconda.org': 'ms-eb34c6e2-6213-4b29-ad46-b457670ed621', u'https://conda.anaconda.org': 'ms-eb34c6e2-6213-4b29-ad46-b457670ed621'}`

**Comment by mwcraig** [comment]
I'm seeing something similar on a windows 64 box. The output below occurs when I have conda-forge and defaults in my channels, but trying other channels (e.g. defaults and mwcraig) gives the same output.

I don't have `anaconda-client` installed so can't log out.

```
$ conda update conda
Fetching package metadata ...........
CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://conda.anaconda.org/conda-
forge/win-64/repodata.json>
Elapsed: 00:00.702000
CF-RAY: 395c37d92fdb25a9-ORD

The remote server has indicated you are using invalid credentials for this chann
el.

If the remote site is anaconda.org or follows the Anaconda Server API, you
will need to
  (a) remove the invalid token from your system with `anaconda logout`, optional
ly
      followed by collecting a new token with `anaconda login`, or
  (b) provide conda with a valid token directly.

Further configuration help can be found at <https://conda.io/docs/config.html>.
```

Output of `python -m conda.gateways.anaconda_client`:

```
$ python -m conda.gateways.anaconda_client
{'https://conda.anaconda.org': 'mw-a01c41dc-6378-42ab-ab59-6690b3f7e400', 'https
://api.binstar.org': 'mw-3ae54987-4460-4fd8-8356-dd8a7d803e88', 'https://conda.b
instar.org': 'mw-3ae54987-4460-4fd8-8356-dd8a7d803e88', 'https://api.anaconda.or
g': 'mw-a01c41dc-6378-42ab-ab59-6690b3f7e400'}​
```

Manually unsetting with `conda config --set add_anaconda_token false` does fix the immediate problem, but I thought I'd report this in hopes it helps narrow down the underlying issue.

**Comment by kalefranz** [comment]
The correct solution here was temporary use of

    conda config --set add_anaconda_token false

But I believe anaconda.org has recently tweaked their permissions model, so this shouldn't be quite so much of an issue.
