### ISSUE TITLE
Write errors do not make it clear where permission problems are

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5888]
I have a system where Anaconda has been installed for multi-user use.  An unprivileged user, with write permissions to `/nfs/shared/projectenvs` (that user being me) wants to create a conda environment.  Somewhere there is a permission problem.  I'd fix it if I could, but the stack trace, even with debugging turned on, doesn't provide enough information for me to take action.  Trace below.

```
$ conda create --debug -vvvv -p /nfs/shared/projectenvs/tensorflow -c conda-forge python=3.6 tensorflow tflearn keras anaconda=4.4
DEBUG conda.gateways.logging:set_verbosity(148): verbosity set to 2
Solving environment: ...working... DEBUG conda.core.solve:solve_final_state(133): solving prefix /nfs/shared/projectenvs/tensorflow
  specs_to_remove: frozenset()
  specs_to_add: frozenset({MatchSpec(name=LowerStrMatch('keras')), MatchSpec(name=LowerStrMatch('anaconda'), version=VersionSpec('4.4.*')), MatchSpec(name=LowerStrMatch('python'), version=VersionSpec('3.6.*')), MatchSpec(name=LowerStrMatch('tensorflow')), MatchSpec(name=LowerStrMatch('tflearn'))})
  prune: False
DEBUG conda.core.repodata:_load(162): No local cache found for https://conda.anaconda.org/conda-forge/noarch at /nfs/shared/anaconda/pkgs/cache/09cdf8bf.json
DEBUG requests.packages.urllib3.util.retry:from_int(200): Converted retries value: 3 -> Retry(total=3, connect=None, read=None, redirect=None, status=None)
DEBUG requests.packages.urllib3.connectionpool:_new_conn(818): Starting new HTTPS connection (1): conda.anaconda.org
DEBUG requests.packages.urllib3.connectionpool:_make_request(395): https://conda.anaconda.org:443 "GET /conda-forge/noarch/repodata.json HTTP/1.1" 200 520
DEBUG conda.core.repodata:fetch_repodata_remote_request(404): 
>>GET /conda-forge/noarch/repodata.json HTTPS
> User-Agent: conda/4.4.0rc1 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-514.26.2.el7.x86_64 centos/7 glibc/2.17
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json

<<HTTPS 200 OK
< Cache-Control: public, max-age=43200
< CF-RAY: 3940c11ebdef2036-DFW
< Conda-File-Cache: hit
< Content-Encoding: gzip
< Content-Type: application/json
< Date: Fri, 25 Aug 2017 18:53:28 GMT
< ETag: W/"flask-1503684000.62-1108-636618019"
< Expires: Sat, 26 Aug 2017 06:53:28 GMT
< Last-Modified: Fri, 25 Aug 2017 18:00:00 GMT
< Server: cloudflare-nginx
< Set-Cookie: __cfduid=df2f6ac0c5b42cf3df671ca639600c2701503687208; expires=Sat, 25-Aug-18 18:53:28 GMT; path=/; domain=.anaconda.org; HttpOnly, session=eyJfaWQiOnsiIGIiOiJaVGsyWXpjMVlXVTRaV1V6TWpBNU1UTXlaak16WXpZNU1HWmxZakJoWXpFPSJ9fQ.DIIDqA.sqKADxBACsLwsbCW_dUCsjZI9Ew; Domain=.anaconda.org; HttpOnly; Path=/
< Strict-Transport-Security: max-age=31536000
< Content-Length: 520
< Connection: keep-alive
< Elapsed: 00:00.268203

DEBUG conda.core.repodata:_pickle_me(227): Saving pickled state for https://conda.anaconda.org/conda-forge/noarch at /nfs/shared/anaconda/pkgs/cache/09cdf8bf.json
DEBUG conda.core.repodata:_load(202): Local cache timed out for https://repo.continuum.io/pkgs/free/noarch at /nfs/shared/anaconda/pkgs/cache/9ca791dd.json
DEBUG requests.packages.urllib3.connectionpool:_new_conn(818): Starting new HTTPS connection (1): repo.continuum.io
DEBUG requests.packages.urllib3.connectionpool:_make_request(395): https://repo.continuum.io:443 "GET /pkgs/free/noarch/repodata.json.bz2 HTTP/1.1" 304 0
DEBUG conda.core.repodata:fetch_repodata_remote_request(404): 
>>GET /pkgs/free/noarch/repodata.json.bz2 HTTPS
> User-Agent: conda/4.4.0rc1 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-514.26.2.el7.x86_64 centos/7 glibc/2.17
> Accept: */*
> Accept-Encoding: identity
> Connection: keep-alive
> If-Modified-Since: Fri, 25 Aug 2017 17:17:55 GMT
> If-None-Match: "888bcd19e37e7c6381b16c184ce4b41d"

<<HTTPS 304 Not Modified
< Cache-Control: public, max-age=30
< CF-Cache-Status: HIT
< CF-RAY: 3940c120ed205873-DFW
< Date: Fri, 25 Aug 2017 18:53:29 GMT
< ETag: "888bcd19e37e7c6381b16c184ce4b41d"
< Expires: Fri, 25 Aug 2017 18:53:59 GMT
< Last-Modified: Fri, 25 Aug 2017 17:17:55 GMT
< Server: cloudflare-nginx
< Set-Cookie: __cfduid=d01a5691ba68a4e869834f7d939a431ba1503687209; expires=Sat, 25-Aug-18 18:53:29 GMT; path=/; domain=.continuum.io; HttpOnly
< Vary: Accept-Encoding
< x-amz-id-2: +tdT480PFK9EMiP4aHLzjfPFlsivm+ghrxdZ8CBpiCoqPNxF3Tml/7rXXVzgKpSk0V7ZRi8BNiI=
< x-amz-request-id: 23E778D643B278C1
< x-amz-version-id: dxFI8WQqjwQddunkYfnOGyVVVfhcD2jG
< Connection: keep-alive
< Elapsed: 00:00.054283

DEBUG conda.core.repodata:_load(210): 304 NOT MODIFIED for 'https://repo.continuum.io/pkgs/free/noarch'. Updating mtime and loading from disk
failed
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/nfs/shared/anaconda' using path '/nfs/shared/anaconda/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/nfs/shared/anaconda' using path '/nfs/shared/anaconda/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/nfs/shared/anaconda' using path '/nfs/shared/anaconda/conda-meta/history'

`$ /nfs/shared/anaconda/bin/conda create --debug -vvvv -p /nfs/shared/projectenvs/tensorflow -c conda-forge python=3.6 tensorflow tflearn keras anaconda=4.4`

    Traceback (most recent call last):
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 207, in _load
        mod_etag_headers.get('_mod'))
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 408, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.repodata.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 671, in __call__
        return func(*args, **kwargs)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 136, in _main
        exit_code = args.func(args, p)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 224, in install
        force_reinstall=context.force,
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/solve.py", line 425, in solve_for_transaction
        force_remove, force_reinstall)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/solve.py", line 375, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/solve.py", line 153, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/solve.py", line 459, in _prepare
        self.subdirs, prepared_specs)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 203, in get_reduced_index
        new_records = query_all(spec)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 174, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 105, in query
        self.load()
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 149, in load
        _internal_state = self._load()
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 211, in _load
        touch(self.cache_path_json)
      File "/nfs/shared/anaconda/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 65, in touch
        utime(path, None)
    PermissionError: [Errno 13] Permission denied


     active environment : py27
    active env location : /nfs/shared/commonenvs/py27
            shell level : 2
       user config file : /home/ijstokes/.condarc
 populated config files : /nfs/shared/anaconda/.condarc
          conda version : 4.4.0rc1
    conda-build version : not installed
         python version : 3.6.1.final.0
       base environment : /nfs/shared/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /nfs/shared/anaconda/pkgs
                          /home/ijstokes/.conda/pkgs
       envs directories : /nfs/shared/commonenvs
                          /nfs/shared/projectenvs
                          /nfs/shared/anaconda/envs
                          /home/ijstokes/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.0rc1 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-514.26.2.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 2111:2111
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
Would you like conda to send this report to the core maintainers?
[y/N]: 
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by ijstokes** [comment]
I should note: `log.trace` looks like it would give me the details I need, but I don't know how to enable "trace" level debugging:

```
$ vim /nfs/shared/anaconda/lib/python3.6/site-packages/conda/gateways/disk/update.py
```

```python
def touch(path, mkdir=False):
    # returns
    #   True if the file did not exist but was created
    #   False if the file already existed
    # raises permissions errors such as EPERM and EACCES
    path = expand(path)
    log.trace("touching path %s", path)
    if lexists(path):
        utime(path, None)
        return True
```

**Comment by ijstokes** [comment]
The issue is about having clearer errors that say where read/write permission problems are coming from, but the "answer" for the specific example in the trace above is that the `/path/to/anaconda/pkgs/cache` needed to be writable by the unprivileged user.

I should note that the system had been intentionally configured to make the `pkgs` directory world writeable.  My thinking was that this would allow all users to install new packages but not over write the packages installed by others.  Ditto to the `conda-meta` directory, and the files in there `urls` and `urls.txt`.

**Comment by ijstokes** [comment]
Oh look! conda does do this at least for some files (this is using v4.4.0rc1)

```
Downloading and Extracting Packages
imagesize 0.7.1: ###################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: /nfs/shared/commonenvs/catalog.json
  uid: 2111
  gid: 2111

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chmod 2111:2111 /nfs/shared/commonenvs/catalog.json
```

**Comment by kalefranz** [comment]
Closing in lieu of #6381
