### ISSUE TITLE
Error with conda update on appveyor

### ISSUE THREAD

**Issue by drvinceknight** [conda/conda#5891]
Not sure if this is on appveyor's side (I have reached out to them on twitter: https://twitter.com/appveyor/status/901514664864907266) or a problem with conda:

Here is a link to one such build (it seems to be intermittent and sometimes restarting the build works just fine): https://ci.appveyor.com/project/drvinceknight/axelrod/build/1.0.2175

Here is the log output

```
AppVeyor
PROJECTS
ENVIRONMENTS
DOCS
SUPPORT
 VINCE KNIGHT
Axelrod

LATEST BUILD HISTORY DEPLOYMENTS SETTINGS
NEW BUILDRE-BUILD PR LOG
Pull request #1126 - Add Tranquilizer (K67R)
Change initial probability value to 'None'.
1.0.2175
3 hours ago by Mansour Hakem
master 45b996c5
Failed a few seconds ago in 8 min 28 sec
Environment: PYTHON_VERSION=3.5, MINICONDA=C:\Miniconda35
6 min 4 sec
JOBS CONSOLE MESSAGES  TESTS  ARTIFACTS
Build started
git clone -q https://github.com/Axelrod-Python/Axelrod.git C:\projects\axelrod
git fetch -q origin +refs/pull/1126/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
conda config --set always_yes yes --set changeps1 no
conda update -q conda
Fetching package metadata ........Could not connect to https://repo.continuum.io/pkgs/free/win-32
Could not connect to https://repo.continuum.io/pkgs/free/win-32
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Current conda install:
               platform : win-32
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Miniconda35  (writable)
    default environment : C:\Miniconda35
       envs directories : C:\Miniconda35\envs
          package cache : C:\Miniconda35\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\appveyor\.condarc
           offline mode : False
`$ C:\Miniconda35\Scripts\conda-script.py update -q conda`
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "C:\Miniconda35\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Miniconda35\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Miniconda35\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Miniconda35\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Miniconda35\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Miniconda35\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "C:\Miniconda35\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Miniconda35\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Miniconda35\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Miniconda35\lib\site-packages\requests\sessions.py", line 628, in send
        r.content
      File "C:\Miniconda35\lib\site-packages\requests\models.py", line 755, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "C:\Miniconda35\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 310, in fetch_index
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 310, in <listcomp>
        repodatas = [(u, f.result()) for u, f in zip(urls, futures)]
      File "C:\Miniconda35\lib\concurrent\futures\_base.py", line 405, in result
        return self.__get_result()
      File "C:\Miniconda35\lib\concurrent\futures\_base.py", line 357, in __get_result
        raise self._exception
      File "C:\Miniconda35\lib\concurrent\futures\thread.py", line 55, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.: https://repo.continuum.io/pkgs/free/win-32
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "C:\Miniconda35\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "C:\Miniconda35\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "C:\Miniconda35\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "C:\Miniconda35\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "C:\Miniconda35\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "C:\Miniconda35\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "C:\Miniconda35\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Miniconda35\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 116, in fetch_repodata
        timeout=(3.05, 60))
      File "C:\Miniconda35\lib\site-packages\requests\sessions.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Miniconda35\lib\site-packages\requests\sessions.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Miniconda35\lib\site-packages\requests\sessions.py", line 628, in send
        r.content
      File "C:\Miniconda35\lib\site-packages\requests\models.py", line 755, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "C:\Miniconda35\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Miniconda35\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda35\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Miniconda35\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Miniconda35\lib\site-packages\conda\cli\install.py", line 238, in install
        prefix=prefix)
      File "C:\Miniconda35\lib\site-packages\conda\api.py", line 24, in get_index
        index = fetch_index(channel_urls, use_cache=use_cache, unknown=unknown)
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 316, in fetch_index
        for url in urls]
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 316, in <listcomp>
        for url in urls]
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 74, in func
        res = f(*args, **kwargs)
      File "C:\Miniconda35\lib\site-packages\conda\fetch.py", line 234, in fetch_repodata
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.: https://repo.continuum.io/pkgs/free/win-32
    
Command exited with code 1
 ```

**Comment by drvinceknight** [comment]
Might be related to: https://appveyor.statuspage.io/incidents/2tjbzx1mtnz8

**Comment by kalefranz** [comment]
Are you still having this issue?

**Comment by Juanlu001** [comment]
Not anymoer.
