### ISSUE TITLE
OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_RECORD', 'decryption failed or bad record mac')]

### ISSUE THREAD

**Issue by JiankaiSun-SJTU-MVIG-training** [conda/conda#5893]
When I run the following command
```
jack@gpu02:/SSD1/jack$ conda create -n opensim-rl -c kidzik opensim git python=2.7
```
An error occurs. Do you have any ideas? Thank you!
```
Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /SSD1/jack/Applications/miniconda3  (writable)
    default environment : /SSD1/jack/Applications/miniconda3
       envs directories : /SSD1/jack/Applications/miniconda3/envs
                          /home/jack/.conda/envs
          package cache : /SSD1/jack/Applications/miniconda3/pkgs
                          /home/jack/.conda/pkgs
           channel URLs : https://conda.anaconda.org/kidzik/linux-64
                          https://conda.anaconda.org/kidzik/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-83-generic debian/jessie/sid glibc/2.19    
                UID:GID : 1031:1031

`$ /SSD1/jack/Applications/miniconda3/bin/conda create -n opensim-rl -c kidzik opensim git python=2.7`




    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1353, in _raise_ssl_error
        raise WantReadError()
    OpenSSL.SSL.WantReadError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/sessions.py", line 672, in send
        r.content
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/models.py", line 816, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/models.py", line 738, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 436, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/response.py", line 384, in read
        data = self._fp.read(amt)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/http/client.py", line 449, in read
        n = self.readinto(b)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/http/client.py", line 493, in readinto
        n = self.fp.readinto(b)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/socket.py", line 586, in readinto
        return self._sock.recv_into(b)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 293, in recv_into
        return self.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 293, in recv_into
        return self.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 293, in recv_into
        return self.recv_into(*args, **kwargs)
      [Previous line repeated 9 more times]
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 277, in recv_into
        return self.connection.recv_into(*args, **kwargs)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1547, in recv_into
        self._raise_ssl_error(self._ssl, result)
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1378, in _raise_ssl_error
        _raise_current_error()
      File "/SSD1/jack/Applications/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
        raise exception_type(errors)
    OpenSSL.SSL.Error: [('SSL routines', 'SSL3_GET_RECORD', 'decryption failed or bad record mac')]
```

**Comment by kalefranz** [comment]
Look like a timeout for a difficult internet situation.  Possibly just intermittent.
