### ISSUE TITLE
conda env create won't activate environment before installing pip packages

### ISSUE THREAD

**Issue by astrojuanlu** [conda/conda#5901]
I originally reported this at https://github.com/ContinuumIO/anaconda-issues/issues/2684

This is my environment file:

```
name: pip_test
channels:
- defaults
dependencies:
- python=3.6
- libgdal=2.1.*
- pip:
  - gdal==2.1.*
```

The problem is that pip package `gdal` fails to install, and I assume the reason is that the environment is not activated before running the `pip` section.

Steps to reproduce:

1. No GDAL in this system: `which gdal-config`
2. `conda env create  # uses environment.yml, but fails`
3. `vim environment.yml  # comment pip lines`
4. `conda remove -n pip_test --all -yq  # remove incomplete environment`
5. `conda env create  # now this works`
6. `source activate pip_test`
7. `which gdal-config  # it is present`
8. `pip install "gdal"  # works!`

Full output:

```
juanlu@infinity /tmp $ which gdal-config
juanlu@infinity /tmp $ cat environment.yml 
name: pip_test
channels:
- defaults
dependencies:
- python=3.6
- libgdal=2.1.*
- pip:
  - gdal==2.1.*
juanlu@infinity /tmp $ conda env create
Fetching package metadata .........
Solving package specifications: .
Collecting gdal==2.1.*
  Downloading GDAL-2.1.3.tar.gz (413kB)
    100% |████████████████████████████████| 419kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/GDAL.egg-info
    writing pip-egg-info/GDAL.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/GDAL.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/GDAL.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/GDAL.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    Traceback (most recent call last):
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 131, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/subprocess.py", line 1333, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 179, in get_gdal_config
        return fetch_config(option, gdal_config = self.gdal_config)
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 135, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: '../../apps/gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 131, in fetch_config
        p = subprocess.Popen([command, args], stdout=subprocess.PIPE)
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/subprocess.py", line 1333, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'gdal-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 333, in <module>
        **extra )
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/egg_info.py", line 195, in run
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/egg_info.py", line 222, in find_sources
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/egg_info.py", line 306, in run
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/egg_info.py", line 335, in add_defaults
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/setuptools/command/sdist.py", line 171, in add_defaults
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/distutils/cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "/home/juanlu/.miniconda36/envs/pip_test/lib/python3.6/distutils/cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 208, in finalize_options
        self.gdaldir = self.get_gdal_config('prefix')
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 188, in get_gdal_config
        return fetch_config(option)
      File "/tmp/pip-build-kivb6w21/gdal/setup.py", line 135, in fetch_config
        raise gdal_config_error(e)
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kivb6w21/gdal/

CondaValueError: pip returned an error.

juanlu@infinity /tmp $ conda remove -n pip_test --all -yq

Package plan for package removal in environment /home/juanlu/.miniconda36/envs/pip_test:

The following packages will be REMOVED:

    curl:       7.49.0-1     
    geos:       3.5.0-0      
    geotiff:    1.4.1-0      
    hdf4:       4.2.12-1     
    hdf5:       1.8.17-2     
    jbig:       2.1-0        
    jpeg:       9b-0         
    kealib:     1.4.6-0      
    libgdal:    2.1.0-0      
    libnetcdf:  4.4.1-1      
    libtiff:    4.0.6-3      
    openssl:    1.0.2l-0     
    pip:        9.0.1-py36_1 
    proj4:      4.9.2-0      
    python:     3.6.2-0      
    readline:   6.2-2        
    setuptools: 27.2.0-py36_0
    sqlite:     3.13.0-0     
    tk:         8.5.18-0     
    wheel:      0.29.0-py36_0
    xerces-c:   3.1.4-0      
    xz:         5.2.3-0      
    zlib:       1.2.11-0     

juanlu@infinity /tmp $ vim environment.yml 
juanlu@infinity /tmp $ cat environment.yml 
name: pip_test
channels:
- defaults
dependencies:
- python=3.6
- libgdal=2.1.*
#- pip:
  #- gdal==2.1.*
juanlu@infinity /tmp $ conda env create
Fetching package metadata .........
Solving package specifications: .
#
# To activate this environment, use:
# > source activate pip_test
#
# To deactivate an active environment, use:
# > source deactivate
#

juanlu@infinity /tmp $ source activate pip_test
(pip_test) juanlu@infinity /tmp $ pip install "gdal==2.1.*"
Collecting gdal==2.1.*
  Using cached GDAL-2.1.3.tar.gz
Building wheels for collected packages: gdal
  Running setup.py bdist_wheel for gdal ... done
  Stored in directory: /home/juanlu/.cache/pip/wheels/34/d1/2d/a67c50f3f53428890d7fce680e48542efbdb29a2fcebb72ed2
Successfully built gdal
Installing collected packages: gdal
Successfully installed gdal-2.1.3
```
```

**Comment by goanpeca** [comment]
@Juanlu001 what version of conda are you using?

**Comment by Juanlu001** [comment]
```
$ conda info -a
Current conda install:

               platform : linux-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.0.8
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : /home/juanlu/.miniconda36  (writable)
    default environment : /home/juanlu/.miniconda36
       envs directories : /home/juanlu/.miniconda36/envs
                          /home/juanlu/.conda/envs
          package cache : /home/juanlu/.miniconda36/pkgs
                          /home/juanlu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.2 Linux/4.10.0-33-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
# conda environments:
#
pip_test                 /home/juanlu/.miniconda36/envs/pip_test
poliastro36              /home/juanlu/.miniconda36/envs/poliastro36
py36                     /home/juanlu/.miniconda36/envs/py36
rastile36                /home/juanlu/.miniconda36/envs/rastile36
telluric36               /home/juanlu/.miniconda36/envs/telluric36
root                  *  /home/juanlu/.miniconda36

sys.version: 3.6.2 |Continuum Analytics, Inc.| (defau...
sys.prefix: /home/juanlu/.miniconda36
sys.executable: /home/juanlu/.miniconda36/bin/python
conda location: /home/juanlu/.miniconda36/lib/python3.6/site-packages/conda
conda-build: /home/juanlu/.miniconda36/bin/conda-build
conda-convert: /home/juanlu/.miniconda36/bin/conda-convert
conda-develop: /home/juanlu/.miniconda36/bin/conda-develop
conda-env: /home/juanlu/.miniconda36/bin/conda-env
conda-index: /home/juanlu/.miniconda36/bin/conda-index
conda-inspect: /home/juanlu/.miniconda36/bin/conda-inspect
conda-metapackage: /home/juanlu/.miniconda36/bin/conda-metapackage
conda-render: /home/juanlu/.miniconda36/bin/conda-render
conda-skeleton: /home/juanlu/.miniconda36/bin/conda-skeleton
conda-verify: /home/juanlu/.miniconda36/bin/conda-verify
user site dirs: 

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /home/juanlu/.miniconda36/bin:/home/juanlu/.local/share/umake/bin:/home/juanlu/bin:/home/juanlu/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
PYTHONHOME: <not set>
PYTHONPATH: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

**Comment by Juanlu001** [comment]
Perhaps this needs a new milestone?

**Comment by Juanlu001** [comment]
conda 4.5.0 and conda-env 2.6.0 are still affected by this issue (just in case anyone is wondering)

**Comment by kalefranz** [comment]
I don't see us fixing this anytime soon.  It needs https://github.com/conda/conda/issues/6820.  Any reason you're not just using gdal as conda packages?

**Comment by Juanlu001** [comment]
Thanks for pointing out to the blocker. The reason I cannot use conda packages here is that I need specific old versions, so I need to compile myself. But this is a more general problem, since for instance `conda env export` automatically exports some `pip` packages.

**Comment by astrojuanlu** [comment]
I don't think this is an issue anymore. I tried the same `environment.yml` I originally used + my OS compilers, and it worked. Also, I tried the conda-forge `compilers` package instead of my OS compilers, and it also worked. Victory!

**Comment by astrojuanlu** [comment]
For future reference: I was getting some import errors, so I had to add a couple of extra shared libraries from conda-forge. This is the final `environment.yml` I used:

```
# cat environment.yml 
name: pip_test
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- libgdal=2.1.*
- compilers
- libjpeg-turbo
- openssl=1.0.*
- pip:
  - gdal==2.1.*
```
