### ISSUE TITLE
Trying to install theano

### ISSUE THREAD

**Issue by BennieC** [conda/conda#5904]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files\Anaconda3  (writable)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Program Files\Anaconda3\envs
          package cache : C:\Program Files\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/menpo/win-64/
                          https://conda.anaconda.org/menpo/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Bennie\.condarc
           offline mode : False

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py install theano`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 378, in download
        resp.raise_for_status()
      File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 862, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 522 Server Error: Origin Connection Time-out for url: https://repo.continuum.io/pkgs/free/win-64/theano-0.9.0-py35_0.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\fetch.py", line 387, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 522 Server Error: Origin Connection Time-out for url: https://repo.continuum.io/pkgs/free/win-64/theano-0.9.0-py35_0.tar.bz2: https://repo.continuum.io/pkgs/free/win-64/theano-0.9.0-py35_0.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files\Anaconda3\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: HTTPError: 522 Server Error: Origin Connection Time-out for url: https://repo.continuum.io/pkgs/free/win-64/theano-0.9.0-py35_0.tar.bz2: https://repo.continuum.io/pkgs/free/win-64/theano-0.9.0-py35_0.tar.bz2

(C:\Program Files\Anaconda3) C:\WINDOWS\system32>

**Comment by mingwandroid** [comment]
Please do not install Anaconda into a path containing spaces. Also, you are
running quite an old version here. Can you uninstall it and try the 4.4.0
release instead?

https://repo.continuum.io/archive/Anaconda3-4.4.0-Windows-x86_64.exe

**Comment by BennieC** [comment]
Thank you for the advice.

The problem is that I need to run Python 3.5.2 as Tensorflow will not run on anything else!

I will try a path without spaces

Regards

 

 

Bennie Coetzer

 

011 678 4227, 082 445 6982
