### ISSUE TITLE
Crash doing conda update anaconda

### ISSUE THREAD

**Issue by hsmatis** [conda/conda#5905]
anaconda-4.4.0 100% |############################################################################################################| Time: 0:00:00   5.02 MB/s
Extracting packages ...
[      COMPLETE      ]|###############################################################################################################################| 100%
Unlinking packages ...
[      COMPLETE      ]|###############################################################################################################################| 100%
Linking packages ...
An unexpected error has occurred, please consider sending the#############################################                                            |  66%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/matis/anaconda/bin/conda", line 6, in <module>
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/cli/main_update.py", line 64, in execute
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/plan.py", line 591, in execute_actions
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 136, in execute_instructions
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 79, in LINK_CMD
  File "/Users/matis/anaconda/lib/python3.5/site-packages/conda/install.py", line 1071, in link
  File "/Users/matis/anaconda/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/Users/matis/anaconda/lib/python3.5/site-packages/pip/_vendor/html5lib/_trie'

**Comment by kalefranz** [comment]
Try `conda update conda` first. Or `sudo chown -R matis:matis /Users/matis/anaconda`.
