### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Shadiee** [conda/conda#5908]
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
    from ..base.context import context
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 20, in <module>
    from ..common.disk import try_write, conda_bld_ensure_dir
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/common/disk.py", line 16, in <module>
    from ..utils import on_win
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/utils.py", line 11, in <module>
    from .common.url import path_to_url
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/common/url.py", line 21, in <module>
    from requests.packages.urllib3.exceptions import LocationParseError
  File "/opt/anaconda3/lib/python3.6/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/opt/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/opt/anaconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/anaconda3/lib/python3.6/site-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/opt/anaconda3/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/__init__.py", line 12, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 156, in execute
    from conda.api import get_index
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/api.py", line 7, in <module>
    from .fetch import fetch_index
  File "/opt/anaconda3/lib/python3.6/site-packages/conda/fetch.py", line 12, in <module>
    import requests
  File "/opt/anaconda3/lib/python3.6/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/opt/anaconda3/lib/python3.6/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    import OpenSSL.SSL
  File "/opt/anaconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/opt/anaconda3/lib/python3.6/site-packages/OpenSSL/crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "/opt/anaconda3/lib/python3.6/site-packages/cryptography/hazmat/primitives/asymmetric/__init__.py", line 12, in <module>
    @six.add_metaclass(abc.ABCMeta)
AttributeError: module 'six' has no attribute 'add_metaclass'

**Comment by kalefranz** [comment]
Can you provide the output of `conda info`, and also step-by-step instructions on how to reproduce your error?
