### ISSUE TITLE
@EXPLICT environment creation

### ISSUE THREAD

**Issue by Davidnet** [conda/conda#5915]
I created an environment from linux using the `conda list --explicit > explicit-spec-file.txt` it create the following [file](https://gist.github.com/Davidnet/6e0559812b23c8fef04586966beb3a29).

And we I try to recreate it using `conda env create --name testingenv -f spec-file.txt` I'm getting:

```bash
   Traceback (most recent call last):
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 75, in load
        return loader.get_single_data()
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 48, in get_single_node
        self.get_event()
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 136, in get_event
        self.current_event = self.state()
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 150, in parse_stream_start
        token.move_comment(self.peek_token())
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "/home/dgromov/anaconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 276, in fetch_more_tokens
        % utf8(ch), self.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '@' that cannot start any token
      in "<unicode string>", line 4, column 1:
        @EXPLICIT
```

Any help? My conda info is:
 ```
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/dgromov/anaconda3  (writable)
    default environment : /home/dgromov/anaconda3
       envs directories : /home/dgromov/anaconda3/envs
                          /home/dgromov/.conda/envs
          package cache : /home/dgromov/anaconda3/pkgs
                          /home/dgromov/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.10.0-33-generic debian/stretch/sid glibc/2.23   
```

**Comment by Davidnet** [comment]
Any updates?

**Comment by hubmann** [comment]
Hello
`conda list --explicit` lists all installed conda packages with URL. This is not an environment file. 
I see that you're using the command `conda env create --name testingenv -f spec-file.txt` to create an environment, but this command expects an environment file to work.  For this particular file you could use `conda create -n testingenv --file spec-file.txt`.
If you want to create an environemt file, I would suggest you to use the command `conda env export > myenv.yml` and then you can create an environment using `conda env create --name testingenv -f myenv.yml`

**Comment by kalefranz** [comment]
I agree this is all very confusing.  We've got a big project upcoming to clean up and unify `conda env` functionality with the rest of conda.

**Comment by kalefranz** [comment]
Closing in lieu of #6697
