### ISSUE TITLE
conda activate error

### ISSUE THREAD

**Issue by RangaRaju** [conda/conda#5917]
Anaconda2 windows 32 bit
when i open anaconda prompt, 
i am getting this below error after fresh installation.  

Error:
Traceback (most recent call last):
  File "D:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "D:\Anaconda2\lib\site-packages\conda\cli\main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 636, in conda_
exception_handler
    return handle_exception(e)
  File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle
_exception
    print_unexpected_error_message(e)
  File "D:\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_
unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "D:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get
_info_dict
    from ..connection import user_agent
  File "D:\Anaconda2\lib\site-packages\conda\connection.py", line 12, in <module
>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "D:\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <modul
e>
    from .packages.urllib3.contrib import pyopenssl
  File "D:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopens
sl.py", line 47, in <module>
    from cryptography import x509
  File "D:\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, i
n <module>
    from cryptography.x509.base import (
  File "D:\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <
module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "D:\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14
, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "D:\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>

    from ._elliptic_curve import (
  File "D:\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51,
in <module>
    from ._int import inverse_mod
  File "D:\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>

    from ._perf._big_num_ctypes import libcrypto
  File "D:\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", lin
e 35, in <module>
    libcrypto = CDLL(libcrypto_path)
  File "D:\Anaconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be string, not unicode

**Comment by kalefranz** [comment]
You've somehow corrupted the `requests` package or one of its dependencies in your environment.  Easiest solution is to start over with a new root environment.
