### ISSUE TITLE
Error while installing 'imbalanced-learn'

### ISSUE THREAD

**Issue by jpabonr** [conda/conda#5929]
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Jaime\Anaconda3  (writable)
    default environment : C:\Users\Jaime\Anaconda3\envs\aind-dl
       envs directories : C:\Users\Jaime\Anaconda3\envs
          package cache : C:\Users\Jaime\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\Jaime\Anaconda3\Scripts\conda-script.py install -c glemaitre imbalanced-learn`

    Traceback (most recent call last):
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\instructions.py", line 87, in SYMLINK_CONDA_CMD
        symlink_conda(state['prefix'], arg)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\install.py", line 532, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\install.py", line 549, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\Jaime\Anaconda3\lib\site-packages\conda\install.py", line 119, in win_conda_bat_redirect
        with open(dst, "w") as f:
    PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Jaime\\Anaconda3\\envs\\aind-dl\\Scripts\\conda'

**Comment by kalefranz** [comment]
Permissions errors have largely been fixed in conda 4.3.  Please `conda update conda`.  If you have permissions errors on existing environments at that point, you'll probably need to fix permissions manually on your windows file system, or just start over with a clean install.  Alternately, just always run the Anaconda Prompt as Administrator, but that's pretty heavy-handed.
