### ISSUE TITLE
Conda Python 3.5.1 installing issue

### ISSUE THREAD

**Issue by shivamqainfotech** [conda/conda#5940]
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2
       envs directories : C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\envs
          package cache : C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py create --name python python=3.5.1`

    Traceback (most recent call last):
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\install.py", line 801, in extract
        t.extractall(path=temp_path)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2079, in extractall
        self.extract(tarinfo, path)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2116, in extract
        self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2192, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "C:\Users\shivambharadwaj\AppData\Local\Continuum\Anaconda2\lib\tarfile.py", line 2232, in makefile
        with bltn_open(targetpath, "wb") as target:
    IOError: [Errno 13] Permission denied: u'C:\\Users\\shivambharadwaj\\AppData\\Local\\Continuum\\Anaconda2\\pkgs\\python-3.5.1-5.tmp\\Lib\\idlelib\\Icons\\folder.gif'

**Comment by tyler-thetyrant** [comment]
Same issue with #5939
Please use the most recent version of conda.

**Comment by kalefranz** [comment]
`conda update conda`
