### ISSUE TITLE
conda update --all -c conda-forge - AttributeError: A value for entry_points has not been set

### ISSUE THREAD

**Issue by jmbertoncelli** [conda/conda#5941]
Current conda install:

               platform : linux-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 3.0.15
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /root/miniconda2  (writable)
    default environment : /root/miniconda2/envs/snake27.10
       envs directories : /root/miniconda2/envs
          package cache : /root/miniconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.18.4 CPython/2.7.13 Linux/3.10.0-514.26.2.el7.x86_64 CentOS Linux/7.3.1611 glibc/2.17
                UID:GID : 0:0

`$ /root/miniconda2/envs/snake27.10/bin/conda update --all -c conda-forge`

    Traceback (most recent call last):
      File "/root/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/root/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 256, in execute
        self.verify()
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 239, in verify
        self.prepare()
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 170, in prepare
        concatv(unlink_actions, link_actions))
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 169, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 166, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 395, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "/root/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set

**Comment by treetoc** [comment]
I have a similar issue when building internal packages on python 2.7. 
The packaging used to run fine until an update of conda (above version 4.3.22) or conda-build (3.x). 
I did revert to an older version but it did not solve the issue. 
I finally move to conda 4.3.25 + conda-build 3.0.3 and I was able to run the packaging. 
So to me this looks like incompatibilities between conda and conda-build.

**Comment by kalefranz** [comment]
Please `conda update conda` first, and then you can proceed with `conda update --all`.
