### ISSUE TITLE
Error in creating environment  from environment file (Conda)

### ISSUE THREAD

**Issue by Sunil-Mohanrao-Salunke** [conda/conda#5942]
sunils-MacBook-Pro:Python_data sunilsalunke$ conda env create -f dand-env-mac.yaml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/sunilsalunke/anaconda  (writable)
    default environment : /Users/sunilsalunke/anaconda
       envs directories : /Users/sunilsalunke/anaconda/envs
                          /Users/sunilsalunke/.conda/envs
          package cache : /Users/sunilsalunke/anaconda/pkgs
                          /Users/sunilsalunke/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/sunilsalunke/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/sunilsalunke/anaconda/bin/conda-env create -f dand-env-mac.yaml`

    Traceback (most recent call last):
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 78, in execute
        directory=os.getcwd())
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/conda_env/env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/ruamel_yaml/main.py", line 73, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/ruamel_yaml/loader.py", line 45, in __init__
        Reader.__init__(self, stream)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/ruamel_yaml/reader.py", line 92, in __init__
        self.determine_encoding()
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/ruamel_yaml/reader.py", line 149, in determine_encoding
        self.update(1)
      File "/Users/sunilsalunke/anaconda/lib/python2.7/site-packages/ruamel_yaml/reader.py", line 185, in update
        exc.encoding, exc.reason)
    ReaderError: 'utf8' codec can't decode byte #xd1: invalid continuation byte
      in "<byte string>", position 8

**Comment by kalefranz** [comment]
Your file dand-env-mac.yaml has bad unicode characters in it I guess.
