### ISSUE TITLE
Unable to create environment after installation

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [conda/conda#5951]
I installed anaconda in OS X just now from the site. The installation was successful as far as I can tell, but as soon as I try to create an environment I run into a problem:

```
 conda create -n py36 anaconda
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/amelio/anaconda  (writable)
    default environment : /Users/amelio/anaconda
       envs directories : /Users/amelio/anaconda/envs
                          /Users/amelio/.conda/envs
          package cache : /Users/amelio/anaconda/pkgs
                          /Users/amelio/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20

`$ /Users/amelio/anaconda/bin/conda create -n py36 anaconda`




    Traceback (most recent call last):
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 421, in fetch_repodata
        cache_path = join(cache_dir or create_cache_dir(), cache_fn_url(url))
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/repodata.py", line 515, in create_cache_dir
        cache_dir = join(PackageCache.first_writable(context.pkgs_dirs).pkgs_dir, 'cache')
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 169, in first_writable
        return cls.all_writable(pkgs_dirs)[0]
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 176, in all_writable
        (PackageCache(pd) for pd in pkgs_dirs)))
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 175, in <lambda>
        writable_caches = tuple(filter(lambda c: c.is_writable,
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 318, in is_writable
        self._is_writable = create_package_cache_directory(self.pkgs_dir)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 323, in create_package_cache_directory
        mkdir_p(pkgs_dir)
      File "/Users/amelio/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 160, in mkdir_p
        makedirs(path)
      File "/Users/amelio/anaconda/lib/python3.6/os.py", line 220, in makedirs
        mkdir(name, mode)
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/amelio/.conda/pkgs'
```

**Comment by goanpeca** [comment]
@amelio-vazquez-reina could you update to the latest version of conda (which is different from the one bundled in the installer)

```
$ conda update conda
```

**Comment by amelio-vazquez-reina** [comment]
Thanks @goanpeca I run into the same exact error when doing so.

**Comment by goanpeca** [comment]
@amelio-vazquez-reina seems this directory needed to be created but was not for some reason, could you try to create it and try again?

`/Users/amelio/.conda/pkgs`

**Comment by amelio-vazquez-reina** [comment]
Thanks @goanpeca I had a dead symlink for `.conda` so that must have caused the problem. After I deleted and I run your command `conda update conda` everything worked well and I was able to create the environment.

On this note, what exactly is stored in the folder `.conda`? Where can I read more about it? Does it make sense to back it up (and sync it across machines)? That's why I had a symlink to a folder that I  keep under git repo (along with other dot files), to keep track of changes that I make to my dot files and folders over time and to make them portable

**Comment by goanpeca** [comment]
>On this note, what exactly is stored in the folder .conda

Conda has a package cache, where all packages are downloaded. There are 2 possible options, the anaconda folder has the default one and the user one, the one I asked you to create. Normally only one is in use, and if by some reason the default one is not accessible (not writable) conda uses the user one, (which should always be writable)

>Does it make sense to back it up (and sync it across machines)?

Nope

**Comment by amelio-vazquez-reina** [comment]
Thanks @goanpeca
