### ISSUE TITLE
retry at `conda --clone` after HTTP failure results in stacktrace and abort

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#5954]
Looks like this is because the environment was half-created, including the directory, during the first install attempt, which failed due to https://github.com/conda/conda/issues/5750#issuecomment-328900837

But if that is the case it is surprising that `conda` doesn't catch this in its normal pre-flight check before creating (or cloning) a new environment.

```
$ conda create -n root_clone --clone root
Source:      /Users/ijstokes/anaconda
Destination: /Users/ijstokes/anaconda/envs/root_clone
The following packages cannot be cloned out of the root environment:
 - conda-4.4.0rc1-py36_0
 - conda-build-3.0.6-py36_0
 - conda-env-2.6.0-0
Packages: 370
Files: 344

`$ /Users/ijstokes/anaconda/bin/conda create -n root_clone --clone root`

    Traceback (most recent call last):
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 671, in __call__
        return func(*args, **kwargs)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 136, in _main
        exit_code = args.func(args, p)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 198, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 70, in clone
        index_args=index_args)
      File "/Users/ijstokes/anaconda/lib/python3.6/site-packages/conda/misc.py", line 254, in clone_env
        os.symlink(os.readlink(src), dst)
    FileExistsError: [Errno 17] File exists: '../../../../bin/rstudio' -> '/Users/ijstokes/anaconda/envs/root_clone/Applications/RStudio.app/Contents/MacOS/rstudio'


     active environment : spyder
    active env location : /Users/ijstokes/anaconda/envs/spyder
            shell level : 2
       user config file : /Users/ijstokes/.condarc
 populated config files : /Users/ijstokes/anaconda/.condarc
                          /Users/ijstokes/.condarc
          conda version : 4.4.0rc1
    conda-build version : 3.0.6
         python version : 3.6.1.final.0
       base environment : /Users/ijstokes/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/ijstokes/anaconda/pkgs
                          /Users/ijstokes/.conda/pkgs
       envs directories : /Users/ijstokes/anaconda/envs
                          /Users/ijstokes/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.0rc1 requests/2.14.2 CPython/3.6.1 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
Would you like conda to send this report to the core maintainers?
```

**Comment by ijstokes** [comment]
Deleting the directory and starting over resolves this issue.

**Comment by soapy1** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!). In more recent releases, conda will check if a target install directory already exists and prompt the user if they want to install into it. For example, consider
```
$ mkdir /tmp/tesenvclone

$ conda create -p /tmp/tesenvclone --clone testenv  
WARNING: A directory already exists at the target location '/tmp/tesenvclone'
but it is not a conda environment.
Continue creating environment (y/[n])? 
```

Cheers!
