### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by RedChueng** [conda/conda#5959]
Traceback (most recent call last):
  File "C:\Users\ZS-0001\Anaconda2\Scripts\conda-script.py", line 5, in <module>

    sys.exit(conda.cli.main())
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\conda\cli\main.py", line 17
6, in main
    return handle_exception(e)
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\conda\exceptions.py", line
626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\conda\exceptions.py", line
588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\conda\cli\main_info.py", li
ne 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\conda\connection.py", line
12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\requests\__init__.py", line
 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\requests\packages\urllib3\c
ontrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\cryptography\x509\__init__.
py", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\cryptography\x509\base.py",
 line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\cryptography\x509\extension
s.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 2
2, in <module>
    from ._elliptic_curve import (
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.
py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 5
6, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Users\ZS-0001\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_c
types.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Users\ZS-0001\Anaconda2\lib\ctypes\util.py", line 53, in find_library

    fname = os.path.join(directory, name)
  File "C:\Users\ZS-0001\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 1: ordinal
not in range(128)

**Comment by Riclim** [comment]
I have the same issue, except that my last message is

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xed in position 12: ordinal not in range(128)

**Comment by goanpeca** [comment]
@RedChueng @Riclim did you install anaconda in a nonascii path?

**Comment by Riclim** [comment]
@goanpeca, no I didn't. We can see in the error messages that @RedChueng didn't either. 
It was Anaconda2-4.4.0-Windows-x86_64, by the way.

**Comment by Riclim** [comment]
I installed Anaconda2-4.3.1-Windows-x86_64 instead, without problems.

**Comment by kalefranz** [comment]
see https://github.com/conda/conda/issues/6650
