### ISSUE TITLE
Unexpected error when intalling julia

### ISSUE THREAD

**Issue by eXcuvator** [conda/conda#5978]
I firt did:

```
$ conda config --add channels conda-forge
$ conda install julia -n myenv3
```

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

```
Traceback (most recent call last):
  File "/home/x/miniconda3/envs/myenv3/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
    exit_code = args_func(args, p)
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 78, in execute
    install(args, parser, 'install')
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/cli/install.py", line 149, in install
    linked = install_linked(prefix)
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/install.py", line 966, in linked
    return set(linked_data(prefix).keys())
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/install.py", line 959, in linked_data
    load_linked_data(prefix, fn[:-5])
  File "/home/x/miniconda3/lib/python3.5/site-packages/conda/install.py", line 886, in load_linked_data
    rec = json.load(fi)
  File "/home/x/miniconda3/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/x/miniconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/x/miniconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/x/miniconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Here the info:

```
(myenv3) x@heracles:~$ conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.11
    conda-env version : 2.5.2
  conda-build version : not installed
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/x/miniconda3  (writable)
  default environment : /home/x/miniconda3/envs/myenv3
     envs directories : /home/x/miniconda3/envs
        package cache : /home/x/miniconda3/pkgs
         channel URLs : https://conda.anaconda.org/conda-forge/linux-64/
                        https://conda.anaconda.org/conda-forge/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/x/.condarc
         offline mode : False
    is foreign system : False

```

**Comment by kalefranz** [comment]
Conda 4.1 is no longer supported.  `conda update conda`

My guess from the stack trace though is that a previous conda operation failed unexpectedly and exited prematurely, and you have a corrupted json file in the conda-meta directory of your root environment.  You can try to poke around there, or just start over with a new installation.  Without being forced to, conda 4.3 no longer leaves environments in a corrupted state.
