### ISSUE TITLE
conda config stack trace when can't write config file

### ISSUE THREAD

**Issue by bkreider** [conda/conda#598]
This situation should be handled nicer. `conda config` doesn't have permission to write the config file.  

Thanks.

```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_config.py", line 339, in execute
    with open(rc_path, 'w') as rc:
IOError: [Errno 13] Permission denied: '/opt/anaconda/.condarc'
```

**Comment by kalefranz** [comment]
fixed with #5232
