### ISSUE TITLE
Error while installing Jupyterlab 0.27 py36_1

### ISSUE THREAD

**Issue by sephib** [conda/conda#6008]
Hi
While installing Jupyter Lab on an offline window 2012 server machine I recieve the below error.
Any suggestions?  

`
    Please consider posting the following information to the
    conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
    stderr and stdout yielding back
    Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\sephi\AppData\Local\conda\conda\envs
                          C:\Users\sephi\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\sephi\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\sephi\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/2012ServerR2 Windows/6.3.9600

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install e:\Installations\python\conda\jupyterlab-0.27.0-py36_1.tar.bz2 -v`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 498, in run_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\cmd.exe', '/c', 'C:\\ProgramData\\Anaconda3\\Scripts\\.jupyterlab-post-link.bat']' returned non-zero exit status 1.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 325, in _execute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink else 'post-link')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 514, in run_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package <unknown>::jupyterlab-0.27.0-py36_1
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda3\Scripts\.jupyterlab-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 279, in execute
        pkg_data, actions)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 342, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package <unknown>::jupyterlab-0.27.0-py36_1
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda3\Scripts\.jupyterlab-post-link.bat
    ==> script messages <==
    <None>

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 200, in install
        explicit(args.packages, prefix, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\misc.py", line 107, in explicit
        execute_actions(actions, index, verbose=verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 800, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 295, in execute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package <unknown>::jupyterlab-0.27.0-py36_1
    running your command again with `-v` will provide additional information
    location of failed script: C:\ProgramData\Anaconda3\Scripts\.jupyterlab-post-link.bat
    ==> script messages <==
    <None>`

**Comment by kalefranz** [comment]
This is a post-link script failure, and not a conda installation failure.  The issue should be reported upstream to jupyterlab.
