### ISSUE TITLE
conda issue

### ISSUE THREAD

**Issue by nccaldwell** [conda/conda#6014]
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/Users/nicolearagon/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/nicolearagon/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 173, in main
    args_func(args, p)
  File "/Users/nicolearagon/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 180, in args_func
    args.func(args, p)
  File "/Users/nicolearagon/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 254, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "/Users/nicolearagon/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 188, in print_packages
    show_channel_urls=show_channel_urls)
  File "/Users/nicolearagon/anaconda/lib/python2.7/site-packages/conda/cli/main_list.py", line 133, in list_packages
    info = install.is_linked(prefix, dist)
  File "/Users/nicolearagon/anaconda/lib/python2.7/site-packages/conda/install.py", line 525, in is_linked
    return json.load(fi)
  File "/Users/nicolearagon/anaconda/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/Users/nicolearagon/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/Users/nicolearagon/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/nicolearagon/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
AragonLLCAir:~ nicolearagon$ conda info
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : osx-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 2.7.11.final.0
     requests version : 2.9.1
     root environment : /Users/nicolearagon/anaconda  (writable)
  default environment : /Users/nicolearagon/anaconda
     envs directories : /Users/nicolearagon/anaconda/envs
        package cache : /Users/nicolearagon/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /Users/nicolearagon/.condarc
    is foreign system : False

**Comment by kalefranz** [comment]
Your conda version is nearly two years old. You'll need to update.
