### ISSUE TITLE
installing klein fails with UnsatisfiableError exception

### ISSUE THREAD

**Issue by whipit** [conda/conda#6016]
My channels in .condarc

```
  channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/CondaMirror/linux-64
                          https://conda.anaconda.org/CondaMirror/noarch
                          https://conda.anaconda.org/auto/linux-64
                          https://conda.anaconda.org/auto/noarch

```

`conda install klein -vv`

```
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/home/tvictor/miniconda3' using path '/home/tvictor/miniconda3/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/home/tvictor/miniconda3' using path '/home/tvictor/miniconda3/conda-meta/history'
Current conda install:

               platform : linux-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : 3.0.8
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/tvictor/miniconda3  (writable)
    default environment : /home/tvictor/miniconda3
       envs directories : /home/tvictor/miniconda3/envs
                          /home/tvictor/.conda/envs
          package cache : /home/tvictor/miniconda3/pkgs
                          /home/tvictor/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/CondaMirror/linux-64
                          https://conda.anaconda.org/CondaMirror/noarch
                          https://conda.anaconda.org/auto/linux-64
                          https://conda.anaconda.org/auto/noarch
            config file : /home/tvictor/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.1 Linux/2.6.32-431.11.2.el6.x86_64 CentOS/6.5 glibc/2.12
                UID:GID : 104475:1039348

`$ /home/tvictor/miniconda3/bin/conda install klein -vv`




    Traceback (most recent call last):
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 261, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 489, in install_actions_list
        for specs_by_prefix in required_solves]
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 489, in <listcomp>
        for specs_by_prefix in required_solves]
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 809, in install
        pkgs = self.solve(specs, returnall=returnall)
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 864, in solve
        self.find_conflicts(specs)
      File "/home/tvictor/miniconda3/lib/python3.6/site-packages/conda/resolve.py", line 369, in find_conflicts
        raise UnsatisfiableError(bad_deps)
    conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
      - klein
    Use "conda info <package>" to see the dependencies for each package.

```

**Comment by kalefranz** [comment]
The klein package doesn't exist for your python 3.6 root environment.

https://anaconda.org/auto/klein/files

Try `conda create -n klein klein && source activate klein`
