### ISSUE TITLE
Unexpect Issue Opening Anaconda Prompt 

### ISSUE THREAD

**Issue by beerospace** [conda/conda#6017]
If it makes a difference I have switched the repository source to conda-forge, but have not really done anything since doing so.  I don't have much experience with Python or Conda so I'm not sure what details are important.

I'm running Windows 10 Pro 64-bit.

----Start the Command Prompt Text----
unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\cli\activate.py", line 174, in main
    from ..install import symlink_conda
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\requests\utils.py", line 24, in <module>
    from . import certs
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\<USER NAME>\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\requests\utils.py", line 24, in <module>
    from . import certs
  File "C:\Users\<USER NAME>\Anaconda3\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

C:\Users\<USER NAME>>conda update --all
'conda' is not recognized as an internal or external command,
operable program or batch file.

**Comment by kalefranz** [comment]
Looks like conda somehow managed to remove itself.  That used to happen a lot with conda <4.3.  After conda 4.3, it really doesn't happen any longer.  Easiest solution now though is just to download a new Anaconda or Miniconda installer.
