### ISSUE TITLE
Formatting errors with CondaError

### ISSUE THREAD

**Issue by mahmoud** [conda/conda#6020]
From time to time I see errors like:

```
$ ~/anaconda2/bin/conda install /tmp/*.tar.bz2
Traceback (most recent call last):
  File "/Users/mahmoud/anaconda2/lib/python2.7/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/Users/mahmoud/anaconda2/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/mahmoud/anaconda2/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/mahmoud/anaconda2/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 41, in __repr__
    return '%s: %s\n' % (self.__class__.__name__, text_type(self))
  File "/Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda/__init__.py", line 44, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character 'A' (0x41) at index 54
```

A ValueError is masking the actual CondaError. I think we all know what's coming next:

```
> /Users/mahmoud/anaconda2/lib/python2.7/site-packages/conda/__init__.py(48)__str__()
-> return text_type(self.message % self._kwargs)
(Pdb) self.message
u'dist_name is not a valid conda package: file:///tmp/%2A.tar.bz2'
```

The url-encoded asterisk has a percent in it. Someone somewhere, maybe not in CondaError, needs to do a `msg = msg.replace('%', '%%')` before the formatting happens.

I'm getting this on conda 4.3.3 on a Mac, but this seems like a pretty portable error.

**Comment by kalefranz** [comment]
Yeah man 4.3.3 is ancient.  We're releasing 4.3.27 today...

**Comment by mahmoud** [comment]
Oh nice! Using 4.3.27 from canary I get

```
$ ~/anaconda2/bin/conda install /tmp/*.tar.bz2

Downloading and Extracting Packages
* None:                                                                                       |   0%

PathNotFoundError: /tmp/*.tar.bz2
```

Which looks a lot better to me! Thanks!

**Comment by mahmoud** [comment]
Actually that was for 4.4.0 (the py_27 had me thinking it was 3.27), but regardless, fixed!
