### ISSUE TITLE
Unexpected error has occurred:  conda create -f environment.yml

### ISSUE THREAD

**Issue by pjgoodall** [conda/conda#6022]
Creating an environment from a .yml file fails. I believe my example conforms to [env create](https://conda.io/docs/commands/env/conda-env-create.html). 

* The environment does not exist, though I have tried --force
* Adding the *optional* parameter --name, as suggested in the diagnostic,  does not work.

Causes severe pain when trying to create reproducible development environments.

Cheers,
--Peter 

[environment.txt - renamed from yml](https://github.com/conda/conda/files/1335213/environment.txt)
```
conda create --debug -f environment.yml
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/home/somebody/anaconda3' using path '/home/somebody/anaconda3/conda-meta/history'
DEBUG conda.gateways.disk.test:prefix_is_writable(64): testing write access for prefix '/home/somebody/anaconda3' using path '/home/somebody/anaconda3/conda-meta/history'
Current conda install:

               platform : linux-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /home/somebody/anaconda3  (writable)
    default environment : /home/somebody/anaconda3
       envs directories : /home/somebody/anaconda3/envs
                          /home/somebody/.conda/envs
          package cache : /home/somebody/anaconda3/pkgs
                          /home/somebody/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
            config file : /home/somebody/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.24 requests/2.14.2 CPython/3.6.1 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/somebody/anaconda3/bin/conda create --debug -f environment.yml`




    Traceback (most recent call last):
      File "/home/somebody/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/somebody/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/somebody/anaconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/somebody/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 142, in install
        common.ensure_name_or_prefix(args, command)
      File "/home/somebody/anaconda3/lib/python3.6/site-packages/conda/cli/common.py", line 474, in ensure_name_or_prefix
        'try "conda %s -h" for more details' % command)
    conda.exceptions.CondaValueError: either -n NAME or -p PREFIX option required,
    try "conda create -h" for more details

```

**Comment by tyler-thetyrant** [comment]
As the error message suggests, you need to name your environment by using the  `-n` command.

**Comment by pjgoodall** [comment]
Ok thanks Tyler, I had assumed the file fully specified the created environment and name came from within the file. Now that I know, it seems reasonable.

Cheers....

**Comment by pjgoodall** [comment]
Hello Tyler,
I hereby change my mind because I got the error when following the conda documentation.  Insisting on -n contradicts the [Managing Environments](https://conda.io/docs/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file) documentation.  Should default to the name in the yml file, with the normal error if the environment already exists, and with the option of overloading with the -n option.

"Create the environment from the environment.yml file:"
`conda env create -f environment.yml`

Cheers,
--PG

**Comment by pjgoodall** [comment]
Please re-open

**Comment by tyler-thetyrant** [comment]
Your original command is `conda create --debug -f environment.yml`, not `conda env create -f environment.yml'.

`conda env create` does not require the `-n` flag and will read the name from the yaml file. 
The documentation is valid.

**Comment by pjgoodall** [comment]
@tyler-thetyrant I should have thanked you for your time and patience.
cheers...
