### ISSUE TITLE
Unknown Error due to update package with conda

### ISSUE THREAD

**Issue by duytrung** [conda/conda#6024]
I have the following error when updating my packages:

```

dell@DELL-PC C:\Users\dell
> conda update --all
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.24
       conda is private : False
      conda-env version : 4.3.24
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : C:\MyPrograms\Anaconda  (writable)
    default environment : C:\MyPrograms\Anaconda
       envs directories : C:\MyPrograms\Anaconda\envs
                          C:\Users\dell\AppData\Local\conda\conda\envs
                          C:\Users\dell\.conda\envs
          package cache : C:\MyPrograms\Anaconda\pkgs
                          C:\Users\dell\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dell\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.24 requests/2.18.4 CPython/3.6.2 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\MyPrograms\Anaconda\Scripts\conda-script.py update --all`




    Traceback (most recent call last):
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 543, in _update_chunk_length
        self.chunk_left = int(line, 16)
    ValueError: invalid literal for int() with base 16: b''

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 302, in _error_catcher
        yield
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 598, in read_chunked
        self._update_chunk_length()
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 547, in _update_chunk_length
        raise httplib.IncompleteRead(line)
    http.client.IncompleteRead: IncompleteRead(0 bytes read)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\MyPrograms\Anaconda\lib\site-packages\requests\models.py", line 745, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 432, in stream
        for line in self.read_chunked(amt, decode_content=decode_content):
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 626, in read_chunked
        self._original_response.close()
      File "C:\MyPrograms\Anaconda\lib\contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\MyPrograms\Anaconda\lib\site-packages\urllib3\response.py", line 320, in _error_catcher
        raise ProtocolError('Connection broken: %r' % e, e)
    urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\exceptions.py", line 634, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\cli\install.py", line 228, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\repodata.py", line 479, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\repodata.py", line 479, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\repodata.py", line 458, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\MyPrograms\Anaconda\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\MyPrograms\Anaconda\lib\site-packages\requests\sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "C:\MyPrograms\Anaconda\lib\site-packages\requests\sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\MyPrograms\Anaconda\lib\site-packages\requests\sessions.py", line 658, in send
        r.content
      File "C:\MyPrograms\Anaconda\lib\site-packages\requests\models.py", line 823, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "C:\MyPrograms\Anaconda\lib\site-packages\requests\models.py", line 748, in generate
        raise ChunkedEncodingError(e)
    requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
```

**Comment by kalefranz** [comment]
'Connection broken: IncompleteRead(0 bytes read)'

That's just a flakey network connection.
