### ISSUE TITLE
TypeError: fork_exec() argument 4 must be tuple, not list

### ISSUE THREAD

**Issue by rezwanh001** [conda/conda#6026]
I am trying to install `tensorflow` through the following comnand: 

    conda create -n tensorflow python=3.6

But I am getting followin error:

```python
Traceback (most recent call last):
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/Users/rezwan/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/requests/__init__.py", line 63, in <module>
    from . import utils
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/requests/utils.py", line 42, in <module>
    if platform.system() == 'Windows':
  File "/Users/rezwan/anaconda/lib/python3.6/platform.py", line 1035, in system
    return uname().system
  File "/Users/rezwan/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/rezwan/anaconda/lib/python3.6/platform.py", line 755, in _syscmd_uname
    f = os.popen('uname %s 2> %s' % (option, DEV_NULL))
  File "/Users/rezwan/anaconda/lib/python3.6/os.py", line 978, in popen
    bufsize=buffering)
  File "/Users/rezwan/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/rezwan/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rezwan/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 161, in get_info_dict
    from ..config import rc_path, sys_rc_path, user_rc_path
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/config.py", line 111, in <module>
    subdir = context.subdir
  File "/Users/rezwan/anaconda/lib/python3.6/site-packages/conda/base/context.py", line 243, in subdir
    m = machine()
  File "/Users/rezwan/anaconda/lib/python3.6/platform.py", line 1072, in machine
    return uname().machine
  File "/Users/rezwan/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/rezwan/anaconda/lib/python3.6/platform.py", line 755, in _syscmd_uname
    f = os.popen('uname %s 2> %s' % (option, DEV_NULL))
  File "/Users/rezwan/anaconda/lib/python3.6/os.py", line 978, in popen
    bufsize=buffering)
  File "/Users/rezwan/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/rezwan/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list
```

How can I sove this issue ?

**Comment by tyler-thetyrant** [comment]
The command should not fail in the recent version of conda. Which version are you using? 

Also, the said command will only create a basic python3 environment named tensorflow, without tensorflow installed in the environment.

**Comment by kalefranz** [comment]
@tyler-thetyrant I'm not sure the conda version is an issue here.  Definitely a unique stack trace.  One I've never seen before.  Possibly something weird / corrupt with the python interpreter there.

**Comment by kalefranz** [comment]
@rezwanulhaquerezwan Can you provide the output of `conda info`?

**Comment by kalefranz** [comment]
The only help google comes up for me with here is https://stackoverflow.com/questions/44891527/uwsgi-startup-subprocess-error.  So might be something specifically related to python 3.6?

**Comment by xbno** [comment]
Hi all, I'm new to posting in issue forums but I'm receiving a similar error. It started after I installed virtual env within the conda enviornment. Conda info returns nothing and all other conda commands and the virtual env command as far as I can tell get this error:

```
gmb:anaconda xbno$ virtualenv test
Using base prefix '/Users/xbno/anaconda'
New python executable in /Users/xbno/anaconda/test/bin/python
copying /Users/xbno/anaconda/bin/python => /Users/xbno/anaconda/test/bin/python
copying /Users/xbno/anaconda/bin/../lib/libpython3.6m.dylib => /Users/xbno/anaconda/test/lib/libpython3.6m.dylib
Traceback (most recent call last):
  File "/Users/xbno/anaconda/bin/virtualenv", line 6, in <module>
    sys.exit(virtualenv.main())
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/virtualenv.py", line 925, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/virtualenv.py", line 1379, in install_python
    stdout=subprocess.PIPE)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list
```

```
gmb:anaconda xbno$ source activate lambda_flask_api2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 171, in main
    activate.main()
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/activate.py", line 181, in main
    from ..install import symlink_conda
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/gateways/download.py", line 17, in <module>
    from ..connection import CondaSession
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/connection.py", line 57, in <module>
    system=platform.system(), kernel=platform.release(),
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1035, in system
    return uname().system
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 755, in _syscmd_uname
    f = os.popen('uname %s 2> %s' % (option, DEV_NULL))
  File "/Users/xbno/anaconda/lib/python3.6/os.py", line 978, in popen
    bufsize=buffering)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xbno/anaconda/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 179, in main
    return handle_exception(e)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 161, in get_info_dict
    from ..config import rc_path, sys_rc_path, user_rc_path
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/config.py", line 111, in <module>
    subdir = context.subdir
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/base/context.py", line 243, in subdir
    m = machine()
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1072, in machine
    return uname().machine
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 755, in _syscmd_uname
    f = os.popen('uname %s 2> %s' % (option, DEV_NULL))
  File "/Users/xbno/anaconda/lib/python3.6/os.py", line 978, in popen
    bufsize=buffering)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list
```

```
gmb:anaconda xbno$ conda update conda
Traceback (most recent call last):
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/Users/xbno/anaconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/gateways/download.py", line 17, in <module>
    from ..connection import CondaSession
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/connection.py", line 57, in <module>
    system=platform.system(), kernel=platform.release(),
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1035, in system
    return uname().system
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 755, in _syscmd_uname
    f = os.popen('uname %s 2> %s' % (option, DEV_NULL))
  File "/Users/xbno/anaconda/lib/python3.6/os.py", line 978, in popen
    bufsize=buffering)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xbno/anaconda/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 161, in get_info_dict
    from ..config import rc_path, sys_rc_path, user_rc_path
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/config.py", line 111, in <module>
    subdir = context.subdir
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/conda/base/context.py", line 243, in subdir
    m = machine()
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1072, in machine
    return uname().machine
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 1001, in uname
    processor = _syscmd_uname('-p', '')
  File "/Users/xbno/anaconda/lib/python3.6/platform.py", line 755, in _syscmd_uname
    f = os.popen('uname %s 2> %s' % (option, DEV_NULL))
  File "/Users/xbno/anaconda/lib/python3.6/os.py", line 978, in popen
    bufsize=buffering)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list
```

Let me know if I can add anything else to help you guys out.

**Comment by xbno** [comment]
Well at first I thought it was just virtual machines, but even trying to deploy a flask app locally fails with a similar thing. I'm afraid I'll probably need to reinstall anaconda again.

```
gmb:Flask-API xbno$ python v1_api.py 
Traceback (most recent call last):
  File "v1_api.py", line 4, in <module>
    import pandas as pd
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/api.py", line 10, in <module>
    from pandas.core.groupby import Grouper
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/groupby.py", line 46, in <module>
    from pandas.core.index import (Index, MultiIndex,
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/index.py", line 2, in <module>
    from pandas.core.indexes.api import *
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/indexes/api.py", line 1, in <module>
    from pandas.core.indexes.base import (Index, _new_Index,  # noqa
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 52, in <module>
    from pandas.core.ops import _comp_method_OBJECT_ARRAY
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/ops.py", line 19, in <module>
    import pandas.core.computation.expressions as expressions
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/pandas/core/computation/__init__.py", line 9, in <module>
    import numexpr as ne
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/numexpr/__init__.py", line 31, in <module>
    from .cpuinfo import cpu
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/numexpr/cpuinfo.py", line 843, in <module>
    cpu = cpuinfo()
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/numexpr/cpuinfo.py", line 465, in __init__
    machine='machine')
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/numexpr/cpuinfo.py", line 53, in command_info
    stacklevel=stacklevel + 1)
  File "/Users/xbno/anaconda/lib/python3.6/site-packages/numexpr/cpuinfo.py", line 38, in getoutput
    p = subprocess.Popen(cmd, stdout=subprocess.PIPE)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 707, in __init__
    restore_signals, start_new_session)
  File "/Users/xbno/anaconda/lib/python3.6/subprocess.py", line 1260, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: fork_exec() argument 4 must be tuple, not list
```

**Comment by kalefranz** [comment]
To me, this looks like a bug in python 3.6.  Has anybody seen this issue with python 3.5 or 2.7?

**Comment by xbno** [comment]
Before I forget, I'll try to add a bit more information. What caused this was first pip installing virtualenv, then reinstalling with conda, then creating a virtualenv and upgrading python within it i believe from 3.5 to 3.6. I was kinda willy nilly installing virtualenvs to use zappa and am quite inexperienced with them so its likely it was me doing something out of the ordinary. Nearly everything caused that error message, including starting a jupyter notebook server. I resolved it by deleting and reinstalling anaconda.

**Comment by SebastianRoll** [comment]
I encountered this same error after upgrading Ubuntu from 16.10 to 17.10.

**Comment by kalefranz** [comment]
This issue is a real mystery to me still.  Any community help in understanding the root cause would be very much appreciated.

**Comment by shayegano** [comment]
Ran into this issue a few days ago in my own codebase, resolved it locally, then googled to see if anyone else needed help resolving.

**Background:** A few months back, a [Python patch](https://bugs.python.org/issue30065) was made to update _posixsubprocess validation. That patch was applied [here](https://github.com/python/cpython/commit/c97c1914f401359f2a7e6c8e0364e71ad9fb5bc8#diff-f514e361152f1443fb488f6cf4dbdb48), and included a list --> tuple conversion change in multiprocessing/util.py. 

Apologies that I cannot help more, as I haven't had a chance to dig in the conda codebase; but my guess is somewhere, there may a mismatch between Python and and Subprocess versioning, causing this tuple/list validation error to be thrown.

**Comment by kalefranz** [comment]
@shayegano Thanks *so* much for the additional information.

**Comment by kalefranz** [comment]
For people who come across this issue in the future, *please* provide the output of

    which -a python

and

    conda info --all

**Comment by kalefranz** [comment]
Added `type:packaging` as this is probably an upstream issue with python.

**Comment by recursiveElk** [comment]
Not conda, but i'm also getting this  issue when using pyenv (python3.6) after recently upgrading to Ubuntu 18.04 from xenial, and trying to run uwsgi (2.0.18) from within the venv.

```
$> which -a python
/home/usr/.pyenv/shims/python
/usr/bin/python
```

uwsgi config:
```
[uwsgi]
wsgi-file                 = application.py
enable-threads      = True
processes              = 10
module                    = application:application
chdir                        = /home/jarjar/bepure/jarjar
http                          = :5000
```

**Comment by recursiveElk** [comment]
Not conda, but i'm also getting this  issue when using pyenv (python3.6) after recently upgrading to Ubuntu 18.04 from xenial, and trying to run uwsgi (2.0.18) from within the venv.

```
$> which -a python
/home/usr/.pyenv/shims/python
/usr/bin/python
```

uwsgi config:
```
[uwsgi]
wsgi-file                 = application.py
enable-threads      = True
processes              = 10
module           = application:application
chdir             = /home/__usr__/__project__/project
http              = :5000
```
