### ISSUE TITLE
unexpected error conda exception

### ISSUE THREAD

**Issue by jroux11** [conda/conda#6034]
#conda update anaconda
results:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\alpha\anaconda  (writable)
    default environment : C:\alpha\anaconda
       envs directories : C:\alpha\anaconda\envs
                          C:\Users\roux\AppData\Local\conda\conda\envs
                          C:\Users\roux\.conda\envs
          package cache : C:\alpha\anaconda\pkgs
                          C:\Users\roux\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\roux\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\alpha\anaconda\Scripts\conda update anaconda`

    Traceback (most recent call last):
      File "C:\alpha\anaconda\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\alpha\anaconda\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\alpha\anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\alpha\anaconda\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\alpha\anaconda\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\alpha\anaconda\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\alpha\anaconda\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\alpha\anaconda\lib\site-packages\conda\core\link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\alpha\anaconda\lib\site-packages\conda\core\link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\alpha\anaconda\lib\site-packages\conda\gateways\disk\read.py", line 84, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "C:\alpha\anaconda\lib\site-packages\conda\gateways\disk\read.py", line 139, in read_paths_json
        data = json.load(paths_json)
      File "C:\alpha\anaconda\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\alpha\anaconda\lib\json\__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "C:\alpha\anaconda\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\alpha\anaconda\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by msarahan** [comment]
That looks like you might have hit a temporary hiccup.  Please try again.  If this persists, you might need to run ``conda clean -a``

**Comment by kalefranz** [comment]
Yeah just a bad download.  `conda clean -i`, more fine-grained than `conda clean -a`, should be all you need.
