### ISSUE TITLE
ValueError: unsupported format character 'B' (0x42) at index 217

### ISSUE THREAD

**Issue by bencaine1** [conda/conda#6042]
I'm getting this error when I try to use conda to install basemap, running on Google Cloud Dataproc. This is the first conda command I'm calling, so it also installs a bunch of other packages. It's 99% of the way through installing numpy when it gives me this error.

```
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : not installed
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
          package cache : /opt/conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
           offline mode : False



`$ /opt/conda/bin/conda install -c anaconda basemap`




    Traceback (most recent call last):
      File "/opt/conda/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/conda/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/opt/conda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/conda/lib/python2.7/site-packages/conda/cli/install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
      File "/opt/conda/lib/python2.7/site-packages/conda/__init__.py", line 45, in __str__
        return text_type(self.message % self._kwargs)
    ValueError: unsupported format character 'B' (0x42) at index 217

```

**Comment by bencaine1** [comment]
The error is flaky -- it doesn't happen every time.

**Comment by kalefranz** [comment]
Any reason you’re stuck back on an old 4.2 version of conda?

**Comment by bencaine1** [comment]
Ah, looks like that's what's installed on dataproc machines by default: https://github.com/GoogleCloudPlatform/dataproc-initialization-actions/blob/master/conda/bootstrap-conda.sh#L43

I'll file a bug with them to get them to update their conda version.

Thanks!
