### ISSUE TITLE
anaconda just initializing on High Sierra 

### ISSUE THREAD

**Issue by petertsengruihon** [conda/conda#6050]
After updating Mac system to High Sierra, I open anaconda client and it just stay initializing. 

And I have tried `condo update anaconda ` , the terminal shows the content below:

```
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/petertseng/anaconda  (writable)
    default environment : /Users/petertseng/anaconda
       envs directories : /Users/petertseng/anaconda/envs
                          /Users/petertseng/.conda/envs
          package cache : /Users/petertseng/anaconda/pkgs
                          /Users/petertseng/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/petertseng/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.12.4 CPython/2.7.13 Darwin/17.0.0 OSX/10.13
                UID:GID : 501:20

`$ /Users/petertseng/anaconda/bin/conda update anaconda-navigator`




    Traceback (most recent call last):
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/Users/petertseng/anaconda/lib/python2.7/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/Users/petertseng/anaconda/pkgs/cache/9cd9d6b5.json'
```

**Comment by kalefranz** [comment]
sudo chown -R 501:20 /Users/petertseng/anaconda
