### ISSUE TITLE
Failed to do conda install 

### ISSUE THREAD

**Issue by HemantKGupta** [conda/conda#6051]
Hi,

I have just installed anaconda3 using mac installer. The installation worked fine but the conda install command is failing. Please see details below:
Hemants-MacBook-Pro:bin hemant$ conda install BeautifulSoup4
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /Users/hemant/anaconda3  (writable)
    default environment : /Users/hemant/anaconda3
       envs directories : /Users/hemant/anaconda3/envs
                          /Users/hemant/.conda/envs
          package cache : /Users/hemant/anaconda3/pkgs
                          /Users/hemant/.conda/pkgs
           channel URLs : ttps://repo.continuum.io/osx-64
                          ttps://repo.continuum.io/noarch
                          https://pypi.python.org/pypi/osx-64
                          https://pypi.python.org/pypi/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/hemant/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/hemant/anaconda3/bin/conda install BeautifulSoup4`

    Traceback (most recent call last):
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
        adapter = self.get_adapter(url=request.url)
      File "/Users/hemant/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
        raise InvalidSchema("No connection adapters were found for '%s'" % url)
    requests.exceptions.InvalidSchema: No connection adapters were found for 'ttps://repo.continuum.io/osx-64/repodata.json.bz2'

**Comment by kalefranz** [comment]
Edit your file `/Users/hemant/.condarc` to remove invalid configuration.

I'm guessing it currently looks something like

```
channels:
  - ttps://repo.continuum.io
  - https://pypi.python.org/pypi
  - defaults
```

The first two are not valid conda channels.
