### ISSUE TITLE
Problems with Anaconda prompt. Cannot use pip for install packages.

### ISSUE THREAD

**Issue by nicolasferrari** [conda/conda#6052]
When I open the Anaconda prompt, I get the following error:

When Traceback (most recent call last):
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    activate.main()
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\activate.py", line 167, in main
    import conda.install
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\gateways\download.py", line 16, in <module>
    from ..connection import CondaSession
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nicolas\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\main.py", line 159, in main
    return handle_exception(e)
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\exceptions.py", line 548, in get_info
    args.func(args, p)
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 148, in execute
    from conda.api import get_index
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\gateways\download.py", line 16, in <module>
    from ..connection import CondaSession
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

This not allowed me to update packages that I need such as scklearn, The pip command is not recognized. Someone can help ??

**Comment by kalefranz** [comment]
When did you first install Anaconda?  After you open the anaconda prompt, can you give us the output of `conda info`?

**Comment by nicolasferrari** [comment]
When  I open the Anaconda prompt, the error message is the following:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\main.py", line 152, in main
    activate.main()
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\activate.py", line 167, in main
    import conda.install
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\gateways\download.py", line 16, in <module>
    from ..connection import CondaSession
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nicolas\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\main.py", line 159, in main
    return handle_exception(e)
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\exceptions.py", line 548, in get_info
    args.func(args, p)
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 148, in execute
    from conda.api import get_index
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\api.py", line 1, in <module>
    from .core.index import get_index
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 31, in <module>
    from ..gateways.download import download
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\gateways\download.py", line 16, in <module>
    from ..connection import CondaSession
  File "C:\Users\Nicolas\Anaconda3\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

**Comment by nicolasferrari** [comment]
I have installed Anaconda 1 year ago

**Comment by nicolasferrari** [comment]
Also, currently I get an error when I run a machine learning algorithm that is as follow:


ImportError: No module named 'scipy'

Is very strange, I have just update the versions of numpy, sklearn and scipy, but still not work

**Comment by kalefranz** [comment]
You've used pip or another python install method to switch out the version of requests that conda relies on.  The easiest solution is to just download a new Anaconda installer and go from there.

**Comment by nicolasferrari** [comment]
Thanks for the response Kale. Yes I just did what you say to solve the
problem.

Regards,
Nicolás

2018-02-22 15:02 GMT+01:00 Kale Franz <notifications@github.com>:
