### ISSUE TITLE
Unexpected error exporting conda env

### ISSUE THREAD

**Issue by mjspeck** [conda/conda#6058]
I'm trying to export my conda env and get this message. Not sure how to fix.

Matts-MacBook-Pro:~ mattspeck$ `conda env export -n py36 -f py36.yml`
Matts-MacBook-Pro:~ mattspeck$ `conda env upload -f py36.yml`
Using Anaconda API: https://api.anaconda.org
Uploading environment py36 to anaconda-server (https://api.anaconda.org)... 
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /Users/mattspeck/anaconda  (writable)
    default environment : /Users/mattspeck/anaconda
       envs directories : /Users/mattspeck/anaconda/envs
                          /Users/mattspeck/.conda/envs
          package cache : /Users/mattspeck/anaconda/pkgs
                          /Users/mattspeck/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/mattspeck/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/2.7.13 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/mattspeck/anaconda/bin/conda-env upload -f py36.yml`

    Traceback (most recent call last):
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/conda_env/cli/main_upload.py", line 101, in execute
        info = uploader.upload()
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 81, in upload
        if self.is_ready():
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 94, in is_ready
        return self.ensure_package_namespace() and self.ensure_distribution()
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/conda_env/utils/uploader.py", line 109, in ensure_package_namespace
        self.binstar.add_release(self.username, self.packagename, self.version, {}, '', '')
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 417, in add_release
        self._check_response(res)
      File "/Users/mattspeck/anaconda/lib/python2.7/site-packages/binstar_client/__init__.py", line 216, in _check_response
        raise ErrCls(msg, res.status_code)
    BinstarError: (u'Bad Request: Bad request syntax or unsupported method ([POST] https://api.anaconda.org/release/mspeck/py36/2017.10.02.1216 -> 400)', 400)

**Comment by mjspeck** [comment]
I did that, and anaconda was updated:


The following packages will be UPDATED:

    anaconda:        4.4.0-np112py27_0 --> custom-py27_0       
    anaconda-client: 1.6.3-py27_0      --> 1.6.5-py27hc13fba8_0

That actually fixed the original issue. I ran my original code:
    `conda env export -n py36 -f py36.yml`
    `conda env upload -f py36.yml`

and got this message:
```
Using Anaconda API: https://api.anaconda.org
Uploading environment py36 to anaconda-server (https://api.anaconda.org)... 
Your environment file has been uploaded to [URL]
Done.
```

Where [URL] was the URL to my uploaded environment.

I think there was something wrong with anaconda on my computer, so updating it fixed the underlying issue. Given that, I'm going to close the issue. Thanks so much!
