### ISSUE TITLE
Error generating 2.7 env

### ISSUE THREAD

**Issue by anshumang** [conda/conda#6060]
conda info
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : /home/xyz/install/anaconda3  (read only)
  default environment : /home/ayz/install/anaconda3
     envs directories : /home/abc/.conda/envs
                        /home/abc/envs
                        /home/xyz/install/anaconda3/envs
        package cache : /home/abc/.conda/envs/.pkgs
                        /home/abc/envs/.pkgs
                        /home/xyz/install/anaconda3/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False

Traceback (most recent call last):
  File "/home/xyz/install/anaconda3/bin/conda-env", line 6, in <module>
    sys.exit(conda_env.cli.main.main())
  File "/home/xyz/install/anaconda3/lib/python3.5/site-packages/conda_env/cli/main.py", line 68, in main
    return args_func(args, parser)
  File "/home/xyz/install/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "/home/xyz/install/anaconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 99, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/home/xyz/install/anaconda3/lib/python3.5/site-packages/conda_env/installers/pip.py", line 9, in install
    pip_cmd = pip_args(prefix) + ['install', ] + specs
  File "/home/xyz/install/anaconda3/lib/python3.5/site-packages/conda_env/pip_util.py", line 30, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/home/xyz/install/anaconda3/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/home/xyz/install/anaconda3/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/home/abc/.conda/envs/cntk-py27/bin/python', '/home/abc/.conda/envs/cntk-py27/bin/pip', '-V']' returned non-zero exit status 1

**Comment by kalefranz** [comment]
Please provide step-by-step instructions on how to reproduce your issue.

**Comment by anshumang** [comment]
I was able to fix it by adding the /home/xyz/install/anaconda3/bin to my PATH.
