### ISSUE TITLE
Creating conda environment using clone without write access to root

### ISSUE THREAD

**Issue by mr-bjerre** [conda/conda#6063]
Running

`conda create -n conda2-env --clone root`

yields

    The following packages cannot be cloned out of the root environment:
     - conda-4.1.6-py27_0
     - conda-build-1.21.3-py27_0
    Packages: 170
    Files: 5
    An unexpected error has occurred, please consider sending the
    following traceback to the conda GitHub issue tracker at:

        https://github.com/conda/conda/issues

    Include the output of the command 'conda info' in your report.

    Traceback (most recent call last):
      File "C:\Program Files\anaconda2\Scripts\conda-script.py", line 5, in <module>

        sys.exit(main())
      File "C:\Program Files\anaconda2\lib\site-packages\conda\cli\main.py", line 12
    0, in main
        exit_code = args_func(args, p)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\cli\main.py", line 13
    0, in args_func
        exit_code = args.func(args, p)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\cli\main_create.py",
    line 57, in execute
        install(args, parser, 'create')
      File "C:\Program Files\anaconda2\lib\site-packages\conda\cli\install.py", line
     223, in install
        clone(args.clone, prefix, json=args.json, quiet=args.quiet, index_args=index
    _args)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\cli\install.py", line
     87, in clone
        index_args=index_args)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\misc.py", line 360, i
    n clone_env
        force_extract=False, index_args=index_args)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\misc.py", line 140, i
    n explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\plan.py", line 600, i
    n execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\instructions.py", lin
    e 136, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\instructions.py", lin
    e 59, in EXTRACT_CMD
        extract(arg)
      File "C:\Program Files\anaconda2\lib\site-packages\conda\install.py", line 852
    , in extract
        t.extractall(path=temp_path)
      File "C:\Program Files\anaconda2\lib\tarfile.py", line 2079, in extractall
        self.extract(tarinfo, path)
      File "C:\Program Files\anaconda2\lib\tarfile.py", line 2116, in extract
        self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
      File "C:\Program Files\anaconda2\lib\tarfile.py", line 2184, in _extract_membe
    r
        os.makedirs(upperdirs)
      File "C:\Program Files\anaconda2\lib\os.py", line 150, in makedirs
        makedirs(head, mode)
      File "C:\Program Files\anaconda2\lib\os.py", line 150, in makedirs
        makedirs(head, mode)
      File "C:\Program Files\anaconda2\lib\os.py", line 157, in makedirs
        mkdir(name, mode)
    WindowsError: [Error 5] Access is denied: 'C:\\Program Files\\anaconda2\\pkgs\\m
    enuinst-1.4.1-py27_0.tmp'

My `conda info` yields

    Current conda install:

                 platform : win-64
            conda version : 4.1.6
        conda-env version : 2.5.1
      conda-build version : 1.21.3
           python version : 2.7.12.final.0
         requests version : 2.10.0
         root environment : C:\Program Files\anaconda2  (read only)
      default environment : C:\Program Files\anaconda2
         envs directories : C:\Users\confidential\.conda\envs
                            C:\Users\confidential\envs
                            C:\Program Files\anaconda2\envs
            package cache : C:\Users\confidential\.conda\envs\.pkgs
                            C:\Users\confidential\envs\.pkgs
                            C:\Program Files\anaconda2\pkgs
             channel URLs : internal URLs. Confidential
                            https://repo.continuum.io/pkgs/free/win-64/
                            https://repo.continuum.io/pkgs/free/noarch/
                            https://repo.continuum.io/pkgs/pro/win-64/
                            https://repo.continuum.io/pkgs/pro/noarch/
              config file : C:\Users\confidential\.condarc
             offline mode : False
        is foreign system : False

**Comment by kalefranz** [comment]
Conda 4.1 is not longer supported.  Update to the latest patch release of conda 4.3 or 4.4.
