### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by laurabenzan** [conda/conda#6095]
platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.25
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Python_UCL  (writable)
    default environment : C:\ProgramData\Python_UCL
       envs directories : C:\ProgramData\Python_UCL\envs
                          C:\Users\Laura M Benzan\AppData\Local\conda\conda\envs
                          C:\Users\Laura M Benzan\.conda\envs
          package cache : C:\ProgramData\Python_UCL\pkgs
                          C:\Users\Laura M Benzan\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Laura M Benzan\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Windows/10 Windows/10.0.15063
          administrator : True

`$ C:\ProgramData\Python_UCL\Scripts\conda-script.py install -y -c conda-forge h5py=2.6.0 netcdf4`

    Traceback (most recent call last):
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\cli\install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\core\linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\_vendor\auxlib\entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\_vendor\auxlib\entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\_vendor\auxlib\entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "C:\ProgramData\Python_UCL\lib\site-packages\conda\_vendor\auxlib\entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Invalid value 1505856821.45 for timestamp

**Comment by hoanghainh88** [comment]
I have the same issue.

**Comment by Sinix92** [comment]
Same issue

**Comment by fooltball** [comment]
Same. After installing trying to fix pip broken by TensorFlow 1.3 downgrading the html5lib. Also did conda upgrade --all before that.

**Comment by ptocca** [comment]
I had the same issue.
I tried installing a miniconda on top of my conda installation (as suggested in other cases of conda malfunction), but it did not fix the problem.
I had a look at the code mentioned in the traceback and came up with the following workaround.

You have to fix the timestamps in the .json files under conda-meta in your anaconda installation.
The code appears to expect an integer number, but some files have a float (actually the decimal representation of them).
The following line finds such files:
```find /home/ucac008/anaconda3/conda-meta -name "*.json" | xargs grep "timestamp.*[0-9]\+\.[0-9]"```
(replace `/home/ucac008/anaconda3` with your anaconda installation dir)

With an editor, open each of the files and fix the timestamp by removing the decimal point and the digits after it.

In my case, this fixed the issue.

**Comment by DrChrisLevy** [comment]
**Same problem:**

Was there some sort of recent update? My code worked all this week but broke today.

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /home/hadoop/conda  (writable)
    default environment : /home/hadoop/conda
       envs directories : /home/hadoop/conda/envs
                          /home/hadoop/.conda/envs
          package cache : /home/hadoop/conda/pkgs
                          /home/hadoop/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False

Trying to do the following in a bootstrap action on AWS EMR cluster creation:
conda install -y numpy
conda install -y scipy
conda install -y pandas
conda install -y pandas-gbq -c conda-forge
conda install -y -c conda-forge geopy
conda install -y -c bioconda google-cloud-sdk
conda install -y -c conda-forge google-cloud-bigquery
conda install -y -c conda-forge google-cloud-storage
conda install -y -c conda-forge google-auth-oauthlib
conda install -y -c anaconda boto3
conda install -y -c anaconda boto

**Get this error**

    Traceback (most recent call last):
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/hadoop/conda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Invalid value 1505726159.26 for timestamp

**Comment by msarahan** [comment]
More info in #6096 - closing to consolidate discussion there.
