### ISSUE TITLE
An error occurs when I try to install tensorflow-gpu with conda

### ISSUE THREAD

**Issue by DCestLaVie** [conda/conda#6119]
I was trying to install tensorflow-gpu with conda. However, in the middle of the installation, the system crashed. After I reboot the computer and find out that the packages are not successfully installed, I try to install them with "conda install" command again but the following error message come out:
```
 Traceback (most recent call last):A
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 84, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 139, in read_paths_json
        data = json.load(paths_json)
      File "C:\Program Files\Anaconda3\lib\json\__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Program Files\Anaconda3\lib\json\__init__.py", line 354, in loads
   return _default_decoder.decode(s)
      File "C:\Program Files\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Program Files\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Can anyone help me fix this problem? Thanks!

**Comment by nehaljwani** [comment]
@DCestLaVie Does `conda clean --all -y` help?

**Comment by DCestLaVie** [comment]
@nehaljwani Yes, it helps. Thanks a lot.
