### ISSUE TITLE
How to prevent using system paths for setuptools and wheel?

### ISSUE THREAD

**Issue by anshumang** [conda/conda#6134]
Traceback (most recent call last):
  File "setup.py", line 186, in <module>
    **kwargs)
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 211, in run
    self.run_command('install')
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run
    return _install.run(self)
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/command/install.py", line 575, in run
    self.run_command(cmd_name)
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/dist.py", line 971, in run_command
    cmd_obj.ensure_finalized()
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
    self.finalize_options()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install_lib.py", line 13, in finalize_options
    self.set_undefined_options('install',('install_layout','install_layout'))
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/cmd.py", line 302, in set_undefined_options
    getattr(src_cmd_obj, src_option))
  File "/home/user/install/anaconda3/envs/abcd-py27/lib/python2.7/distutils/cmd.py", line 105, in __getattr__
    raise AttributeError, attr
AttributeError: install_layout

**Comment by kalefranz** [comment]
You haven't even provided the command you're trying to run...  Please provide all steps and details necessary to reproduce.
