### ISSUE TITLE
all conda commands throwing `conda._vendor.auxlib.exceptions.ValidationError`

### ISSUE THREAD

**Issue by bulbuntu** [conda/conda#6135]
```
Kalyans-MacBook-Pro:DrawPrintTextLocations kaza$ conda list
# packages in environment at /Users/kaza/miniconda3:
#
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/kaza/miniconda3  (writable)
    default environment : /Users/kaza/miniconda3
       envs directories : /Users/kaza/miniconda3/envs
                          /Users/kaza/.conda/envs
          package cache : /Users/kaza/miniconda3/pkgs
                          /Users/kaza/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.6.1 Darwin/14.4.0 OSX/10.10.4    
                UID:GID : 501:20

`$ /Users/kaza/miniconda3/bin/conda list`




    Traceback (most recent call last):
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 242, in execute
        show_channel_urls=context.show_channel_urls)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/cli/main_list.py", line 172, in print_packages
        installed = linked(prefix)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/kaza/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1505931482.256 for timestamp



Kalyans-MacBook-Pro:DrawPrintTextLocations kaza$ date
Mon Oct  9 19:08:17 EDT 2017
```

**Comment by bulbuntu** [comment]
Closing as duplicate of #6096
