### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by skerman** [conda/conda#6157]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\dev\Anaconda3  (writable)
    default environment : C:\dev\Anaconda3
       envs directories : C:\dev\Anaconda3\envs
                          C:\Users\SXK0KMH\AppData\Local\conda\conda\envs
                          C:\Users\SXK0KMH\.conda\envs
          package cache : C:\dev\Anaconda3\pkgs
                          C:\Users\SXK0KMH\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\SXK0KMH\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.14.2 CPython/3.6.1 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\dev\Anaconda3\Scripts\conda-script.py install --file C:\Users\SXK0KMH\Downloads\holidays-0.8.1.tar.gz`

    Traceback (most recent call last):
      File "C:\dev\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\dev\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\dev\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\dev\Anaconda3\lib\site-packages\conda\cli\install.py", line 190, in install
        specs.extend(common.specs_from_url(fpath, json=context.json))
      File "C:\dev\Anaconda3\lib\site-packages\conda\cli\common.py", line 551, in specs_from_url
        for line in open(path):
      File "C:\dev\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 101: character maps to <undefined>

**Comment by skerman** [comment]
this was not a conda package
