### ISSUE TITLE
Error when using conda to install packages !

### ISSUE THREAD

**Issue by DalilaSal** [conda/conda#6163]
I get this error when using conda to install packages 
  
  Traceback (most recent call last):%
  File "/miniconda/bin/conda", line 6, in <module>
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main

The output of conda info :

  File "/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
  File "/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 62, in execute
  File "/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
  File "/miniconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
  File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
  File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 92, in LINK_CMD
  File "/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 88, in link
  File "/miniconda/lib/python2.7/site-packages/conda/install.py", line 667, in link
  File "/miniconda/lib/python2.7/site-packages/conda/install.py", line 377, in run_script
  File "/miniconda/lib/python2.7/subprocess.py", line 535, in check_call
  File "/miniconda/lib/python2.7/subprocess.py", line 522, in call
  File "/miniconda/lib/python2.7/subprocess.py", line 710, in __init__
  File "/miniconda/lib/python2.7/subprocess.py", line 1334, in _execute_child
  File "/miniconda/lib/python2.7/pickle.py", line 1388, in loads
  File "/miniconda/lib/python2.7/pickle.py", line 864, in load
  File "/miniconda/lib/python2.7/pickle.py", line 977, in load_string
  LookupError: unknown encoding: string-escape

How to fix this ?

PS: I am using ubuntu 16.04.

**Comment by kalefranz** [comment]
Please provide the output of `conda info` and the command you're trying to run.
