### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb in position 25: ordinal not in range(128)

### ISSUE THREAD

**Issue by Jacoobr** [conda/conda#6166]
There an error occurred  when I install Anoconda python 2.7 on my laptop with win10 OS:
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 45-46: ordinal not in range(128)` 
And then I ignored the error and continued to install Anoconda python 2.7 .When I  use Anaconda Prompt  to install mingw and libpython. Like this:
`conda install mingw libpython`
There  an error occurred again:
`Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Anaconda2\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xbb in position 25: ordinal not in range(128)`
Can someone help me?

**Comment by kalefranz** [comment]
see https://github.com/conda/conda/issues/6650
