### ISSUE TITLE
error when creating virtual environment

### ISSUE THREAD

**Issue by dickreuter** [conda/conda#6168]
I tried to recreate on of my virtual environments and got the below error:
https://github.com/dickreuter/Poker/blob/master/environment.yml
conda env create -f environment.yml -n poker_venv

Windows/10.0.15063
          administrator : False

`$ C:\Anaconda3\Scripts\conda-env create -f environment.yml -n poker_venv`
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "C:\Anaconda3\lib\site-packages\conda_env\installers\pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "C:\Anaconda3\lib\site-packages\conda_env\pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "C:\Anaconda3\lib\subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "C:\Anaconda3\lib\subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['C:\\Anaconda3\\envs\\poker_venv\\python.exe', 'C:\\Anaconda3\\envs\\poker_venv\\Scripts\\pip-script.py', '-V']' returned non-zero exit status 1.

**Comment by kalefranz** [comment]
Output of `conda info` and `conda list`?  Also, contents of `environment.yml`?
