### ISSUE TITLE
conda placeholder problem

### ISSUE THREAD

**Issue by bernt-matthias** [conda/conda#6175]
Conda asked me to submit the following here: 

Seems to be caused by an R package that is built with an old conda version. 

```
Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.14.2
       root environment : /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda  (writable)
    default environment : /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda
       envs directories : /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs
                          /home/songalax/.conda/envs
          package cache : /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/pkgs
                          /home/songalax/.conda/pkgs
           channel URLs : https://conda.anaconda.org/iuc/linux-64
                          https://conda.anaconda.org/iuc/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.5.2 Linux/2.6.32-696.6.3.el6.x86_64 CentOS/6.9 glibc/2.12    
                UID:GID : 61715:4533

`$ /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/bin/conda create -vvv -y --override-channels --channel iuc --channel bioconda --channel defaults --channel r --name mulled-v1-0ac87b39a40f44c0fe078d45b44a75214d4cdc24e1ddfc494e56a9ef42628a17 bioconductor-dexseq=1.20.1 r-getopt=1.20.0 r-rjson=0.2.15`




    Traceback (most recent call last):
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/path_actions.py", line 299, in execute
        self.file_mode)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/portability.py", line 57, in update_prefix
        update_file_in_place_as_binary(realpath(path), _update_prefix)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/gateways/disk/update.py", line 33, in update_file_in_place_as_binary
        fh.write(callback(data))
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/portability.py", line 39, in _update_prefix
        data = replace_prefix(mode, original_data, placeholder, new_prefix)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/portability.py", line 64, in replace_prefix
        data = binary_replace(data, placeholder.encode('utf-8'), new_prefix.encode('utf-8'))
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/portability.py", line 93, in binary_replace
        data = pat.sub(replace, data)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/portability.py", line 88, in replace
        raise _PaddingError
    conda.core.portability._PaddingError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/link.py", line 326, in _execute_actions
        action.execute()
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/path_actions.py", line 302, in execute
        len(self.prefix_placeholder))
    conda.exceptions.PaddingError: Placeholder of length '80' too short in package /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-0ac87b39a40f44c0fe078d45b44a75214d4cdc24e1ddfc494e56a9ef42628a17/bin/Rscript.
    The package must be rebuilt with conda-build > 2.0.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/link.py", line 281, in execute
        pkg_data, actions)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/link.py", line 344, in _execute_actions
        reverse_excs,
    conda.CondaMultiError: Placeholder of length '80' too short in package /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-0ac87b39a40f44c0fe078d45b44a75214d4cdc24e1ddfc494e56a9ef42628a17/bin/Rscript.
    The package must be rebuilt with conda-build > 2.0.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/lib/python3.5/site-packages/conda/core/link.py", line 297, in execute
        rollback_excs,
    conda.CondaMultiError: Placeholder of length '80' too short in package /gpfs1/data/galaxy_server/galaxy-dev/database/dependencies/_conda/envs/mulled-v1-0ac87b39a40f44c0fe078d45b44a75214d4cdc24e1ddfc494e56a9ef42628a17/bin/Rscript.
    The package must be rebuilt with conda-build > 2.0.

```

    defaults::r-base-3.3.1-3
    defaults::r-3.3.1-r3.3.1_0
    defaults::r-recommended-3.3.1-r3.3.1_0

**Comment by mingwandroid** [comment]
The package with the 80 character limit is the R interpreter itself (`r-base`). You cannot use R 3.3.1 with modern packages unfortunately.

**Comment by bernt-matthias** [comment]
Isn't it possible to update the package?

**Comment by mingwandroid** [comment]
No. We have updated the package but it's now built against r 3.4.1. We do not build legacy packages continually.
