### ISSUE TITLE
conda-env create encounters an unexpected error, yet continues

### ISSUE THREAD

**Issue by brechtm** [conda/conda#6176]
`conda env create` encountered an error, yet it continued the creation of the environment. It is not surprising, that this environment was corrupt; it didn't contain the python binaries (the environment.yml specified python=3.6).

Running `conda env create` again managed to create the environment without issues.

```
...
[impyla              ]|#########################################         |  82%
[pandas              ]|##########################################        |  84%
[parquet-cpp         ]|##########################################        | An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 2.7.12.final.0
       requests version : 2.11.1
       root environment : /opt/cloudera/parcels/Anaconda  (read only)
    default environment : /opt/cloudera/parcels/Anaconda
       envs directories : /data/data01/dev/edl/infra/mstr/landing/condaenvs
                          /home/saitoped/.conda/envs
                          /opt/cloudera/parcels/Anaconda/envs
          package cache : /data/data01/dev/edl/infra/mstr/landing/condaenvs/.pkgs
                          /home/saitoped/.conda/envs/.pkgs
                          /opt/cloudera/parcels/Anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/linux-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
            config file : /home/saitoped/.condarc
           offline mode : False



`$ /opt/cloudera/parcels/Anaconda/bin/conda-env create --force --name ml_guidanceinc --file jenkins/ml_guidanceinc/devel/python/environment.yml`




    Traceback (most recent call last):
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 111, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'

 85%
[pip                 ]|###########################################       |  87%
[scikit-learn        ]|############################################      |  89%
[thrift_sasl         ]|#############################################     |  91%
[pyarrow             ]|##############################################    |  92%
[qt                  ]|###############################################   |  94%
[pyqt                ]|################################################  |  96%
[matplotlib          ]|################################################# |  98%
[      COMPLETE      ]|##################################################| 100%
```

**Comment by tyler-thetyrant** [comment]
You should try with the most recent version of conda. We are currently at 4.3.29
`conda update conda` will do the job.

**Comment by kalefranz** [comment]
`conda update conda`

**Comment by brechtm** [comment]
So this is a known bug which is fixed in the current version of conda?

Unfortunately, I'm stuck at version 4.2.9 for now since I don't maintain the Anaconda installation myself. I'll update this issue if I run into it again with a newer version.
