### ISSUE TITLE
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_load_locations'

### ISSUE THREAD

**Issue by mrcarv** [conda/conda#6180]
It intermittently gives no output at all, or works like expected or gives X509 related error. System is ubuntu 16 x64 up to date. Presuming it might be related to ssl, i tried with networking offline, just to make sure and the same behavior occurs.

```
root@sam:~# lsb_release  -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
root@sam:~# apt update
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Hit:2 https://deb.nodesource.com/node_6.x xenial InRelease                  
Hit:3 http://br.archive.ubuntu.com/ubuntu xenial InRelease                                                                   
Hit:4 http://dl.google.com/linux/chrome/deb stable Release                                                                   
Get:5 http://br.archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]                   
Get:6 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]         
Get:8 http://br.archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]                  
Fetched 306 kB in 1s (258 kB/s)                                                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.

root@sam:~# /python/miniconda3/bin/conda info
root@sam:~# /python/miniconda3/bin/conda info
root@sam:~# /python/miniconda3/bin/conda info
root@sam:~# /python/miniconda3/bin/conda info
Current conda install:

               platform : linux-64
          conda version : 4.3.29
       conda is private : False
      conda-env version : 4.3.29
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /python/miniconda3  (writable)
    default environment : /python/miniconda3
       envs directories : /python/miniconda3/envs
                          /root/.conda/envs
          package cache : /python/miniconda3/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.29 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-97-generic debian/stretch/sid glibc/2.23    
                UID:GID : 0:0

root@sam:~# /python/miniconda3/bin/conda env list
# conda environments:
#
root                  *  /python/miniconda3

root@sam:~# /python/miniconda3/bin/conda env list
# conda environments:
#
root                  *  /python/miniconda3

root@sam:~# /python/miniconda3/bin/conda env list
Traceback (most recent call last):
  File "/python/miniconda3/bin/conda-env", line 7, in <module>
    from conda_env.cli.main import main
  File "/python/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 38, in <module>
    from . import main_create
  File "/python/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 8, in <module>
    from conda.cli import common, install as cli_install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_load_locations'
root@sam:~# /python/miniconda3/bin/conda env list
Traceback (most recent call last):
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/python/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_load_locations'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python/miniconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/python/miniconda3/lib/python3.6/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_load_locations'
root@sam:~# /python/miniconda3/bin/conda env list
root@sam:~# /python/miniconda3/bin/conda env list
Traceback (most recent call last):
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/python/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_get0_param'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python/miniconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/python/miniconda3/lib/python3.6/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_get0_param'
root@sam:~# /python/miniconda3/bin/conda env list
Traceback (most recent call last):
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/python/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_get0_param'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python/miniconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/python/miniconda3/lib/python3.6/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_get0_param'
root@sam:~# /python/miniconda3/bin/conda env list
Traceback (most recent call last):
  File "/python/miniconda3/bin/conda-env", line 7, in <module>
    from conda_env.cli.main import main
  File "/python/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 38, in <module>
    from . import main_create
  File "/python/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 8, in <module>
    from conda.cli import common, install as cli_install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_load_locations'
root@sam:~# /python/miniconda3/bin/conda env list
Traceback (most recent call last):
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "/python/miniconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 10, in <module>
    from .install import install
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 21, in <module>
    from ..core.index import get_index, get_channel_priority_map
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 8, in <module>
    from .package_cache import PackageCache
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/python/miniconda3/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "/python/miniconda3/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_get0_param'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/python/miniconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/python/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/python/miniconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/python/miniconda3/lib/python3.6/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/python/miniconda3/lib/python3.6/site-packages/requests/__init__.py", line 84, in <module>
    from urllib3.contrib import pyopenssl
  File "/python/miniconda3/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/rand.py", line 10, in <module>
    from OpenSSL._util import (
  File "/python/miniconda3/lib/python3.6/site-packages/OpenSSL/_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 156, in <module>
    Binding.init_static_locks()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 137, in init_static_locks
    cls._ensure_ffi_initialized()
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 124, in _ensure_ffi_initialized
    cls.lib = build_conditional_library(lib, CONDITIONAL_NAMES)
  File "/python/miniconda3/lib/python3.6/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in build_conditional_library
    setattr(conditional_lib, attr, getattr(lib, attr))
AttributeError: cffi library '_openssl' has no function, constant or global variable named 'X509_STORE_get0_param'
root@sam:~# /python/miniconda3/bin/conda env list
# conda environments:
#
root                  *  /python/miniconda3
```

**Comment by kalefranz** [comment]
That's incredibly bizarre.  I have no idea what's going on with your system.

**Comment by mrcarv** [comment]
It is due to a faulty CPU. Running Intel's cpu test, the item SSE4.1 Bit Conversion fails intermittently. All other tests pass consistently. This issue can be closed.
