### ISSUE TITLE
AttributeError: A value for entry_points has not been set

### ISSUE THREAD

**Issue by jg1141** [conda/conda#6184]
geoviews-1.3.2 100% |#########################################################################################| Time: 0:00:01 239.38 kB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : 0+unknown
         python version : 3.5.1.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda/envs/holoviews
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/ioam/osx-64
                          https://conda.anaconda.org/ioam/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/3.5.1 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

`$ //anaconda/envs/holoviews/bin/conda install -c conda-forge -c ioam geoviews`

    Traceback (most recent call last):
      File "//anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 403, in __get__
        val = instance.__dict__[self.name]
    KeyError: 'entry_points'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "//anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "//anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "//anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "//anaconda/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "//anaconda/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "//anaconda/lib/python3.5/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "//anaconda/lib/python3.5/site-packages/conda/core/link.py", line 256, in execute
        self.verify()
      File "//anaconda/lib/python3.5/site-packages/conda/core/link.py", line 239, in verify
        self.prepare()
      File "//anaconda/lib/python3.5/site-packages/conda/core/link.py", line 170, in prepare
        concatv(unlink_actions, link_actions))
      File "//anaconda/lib/python3.5/site-packages/conda/core/link.py", line 169, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "//anaconda/lib/python3.5/site-packages/conda/core/link.py", line 166, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "//anaconda/lib/python3.5/site-packages/conda/core/link.py", line 395, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "//anaconda/lib/python3.5/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "//anaconda/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set

**Comment by jg1141** [comment]
cloning the [geoviews repo](https://github.com/ioam/geoviews) and the following commands worked:
```
(holoviews) 2017-10-18 ~/20171018/geoviews$ conda install Proj4
(holoviews) 2017-10-18 ~/20171018/geoviews$ python setup.py install
```

**Comment by jg1141** [comment]
but then cartopy gave [this error](https://github.com/SciTools/cartopy/issues/823)

**Comment by kalefranz** [comment]
What do you get after `conda update conda`?

**Comment by jg1141** [comment]
> conda install -c conda-forge -c ioam holoviews geoviews
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment C:\Users\jg114\AppData\Local\Continuum\Anaconda3:

The following NEW packages will be INSTALLED:

    geoviews:  1.3.2-py36_0          ioam
    holoviews: 1.8.4-py36_0          conda-forge

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:     4.3.30-py36h7e176b0_0             --> 4.3.29-py36_0 conda-forge

Proceed ([y]/n)?


D:\20171019
> conda install -c conda-forge -c ioam holoviews geoviews
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Users\jg114\AppData\Local\Continuum\Anaconda3:
#
geoviews                  1.3.2                    py36_0    ioam
holoviews                 1.8.4                    py36_0    conda-forge

**Comment by kalefranz** [comment]
That one looks like a problem with pyqt then.  Glad we fixed your original issue.  You were working on an outdated version of conda where the bug had already been fixed.  For packaging issues, hit up conda-forge or the ContinuumIO/anaconda-issues repo, depending on where you're getting the packages from.
