### ISSUE TITLE
conda install getting stuck

### ISSUE THREAD

**Issue by einatlev** [conda/conda#6193]
Hello! 
Newbe to python/conda here.

I installed Python 3.6 and Anaconda3 last night, and I'm now trying to install the gdal module, which requires the libgdal library. However, the installation gets stuck for over 30 minutes every time I tried it. 
When I ^C it, it spits out the output below. 

I also found this:

`~ >>conda search | grep dal
accelerate_cudalib           2.0                           0  defaults
gdal                         1.10.1                   py27_0  defaults
libgdal                      1.11.2                        0  defaults`

Any suggestions? I tried several of the tips offered in previous posts but none worked thus far.

Thanks!

~ >>conda install -c anaconda libgdal
Fetching package metadata .............
Solving package specifications: .^C

`~ >>conda install -c anaconda libgdal
Fetching package metadata .............
Solving package specifications: .^C

Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
    install(args, parser, 'install')
  File "/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 261, in install
    channel_priority_map=_channel_priority_map, is_update=isupdate)
  File "/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 489, in install_actions_list
    for specs_by_prefix in required_solves]
  File "/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 489, in <listcomp>
    for specs_by_prefix in required_solves]
  File "/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 634, in get_actions_for_dists
    pkgs = r.install(specs, installed, update_deps=update_deps)
  File "/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 813, in install
    pkgs = self.solve(specs, returnall=returnall)
  File "/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 919, in solve
    solution, obj5 = C.minimize(eq_v, solution)
  File "/anaconda3/lib/python3.6/site-packages/conda/logic.py", line 536, in minimize
    newsol = self.sat()
  File "/anaconda3/lib/python3.6/site-packages/conda/logic.py", line 438, in sat
    solution = pycosat.solve(clauses, vars=self.m, prop_limit=limit)
KeyboardInterrupt`

**Comment by einatlev** [comment]
Hello
I somehow managed to get everything to work... I wish I could say how, but I can't! :-)
