### ISSUE TITLE
OSError Error no 5 while trying to create virtual environment

### ISSUE THREAD

**Issue by anushaAnandan** [conda/conda#6195]
Hi I successfully installed Anaconda but when I tried to create a virtual env,I get the following error: 

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.23
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /home/anusha/anaconda3  (read only)
    default environment : /home/anusha/anaconda3
       envs directories : /home/anusha/.conda/envs
                          /home/anusha/anaconda3/envs
          package cache : /home/anusha/anaconda3/pkgs
                          /home/anusha/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Linux/4.10.0-28-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/anusha/anaconda3/bin/conda create -n py3env python=3.5 anaconda`

    Traceback (most recent call last):
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 828, in execute_actions
        plan = plan_from_actions(actions, index)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 338, in plan_from_actions
        plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 302, in inject_UNLINKLINKTRANSACTION
        pfe.prepare()
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 468, in prepare
        for dist in self.link_dists)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 468, in <genexpr>
        for dist in self.link_dists)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 391, in make_actions_for_dist
        key=lambda pce: pce and pce.is_extracted and pce.tarball_matches_md5_if(md5)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/collection.py", line 88, in first
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/collection.py", line 88, in <genexpr>
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 391, in <lambda>
        key=lambda pce: pce and pce.is_extracted and pce.tarball_matches_md5_if(md5)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 105, in tarball_matches_md5_if
        return not md5sum or self.md5sum == md5sum
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 113, in md5sum
        return self._calculate_md5sum() if self.is_fetched else None
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/decorators.py", line 137, in _wrapper
        result = method(self, *args, **kwargs)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 121, in _calculate_md5sum
        return compute_md5sum(self.package_tarball_full_path)
      File "/home/anusha/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 63, in compute_md5sum
        for chunk in iter(partial(fh.read, 8192), b''):
    OSError: [Errno 5] Input/output error

**Comment by kalefranz** [comment]
Try

    conda clean --packages --tarballs

and see how far you get

**Comment by anushaAnandan** [comment]
Didn't work

**Comment by kalefranz** [comment]
`OSError: [Errno 5] Input/output error` is something going on with your operating system or file system.  You can use `-vvv` to get a finer-grained picture on where conda is getting tripped up.  But ultimately you're going to have to do something outside of conda to address the issue with the problematic path.
