### ISSUE TITLE
Conda Install Error  UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 49: ordinal not in range(128)

### ISSUE THREAD

**Issue by tstegman** [conda/conda#6196]
Howdy,

I have been trying to install Anaconda for a while now and have had no success.  I have played around with the PATH variables and uninstalled and reinstalled several times.  I am new to python and and not sure what to do next other than give up.  Any help would be great.  Thanks!

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : C:\Anaconda2  (writable)
    default environment : C:\Anaconda2
       envs directories : C:\Anaconda2\envs
                          C:\Users\m.modeler\AppData\Local\conda\conda\envs
                          C:\Users\m.modeler\.conda\envs
          package cache : C:\Anaconda2\pkgs
                          C:\Users\m.modeler\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/2.7.13 Windows/7
Windows/6.1.7601
          administrator : False

`$ C:\Anaconda2\Scripts\conda ..checkenv cmd.exe C:\Anaconda2`

    Traceback (most recent call last):
      File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 171, in main

        activate.main()
      File "C:\Anaconda2\lib\site-packages\conda\cli\activate.py", line 181, in
main
        from ..install import symlink_conda
      File "C:\Anaconda2\lib\site-packages\conda\install.py", line 37, in <modul
e>
        from .core.package_cache import rm_fetched  # NOQA
      File "C:\Anaconda2\lib\site-packages\conda\core\package_cache.py", line 9,
 in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Anaconda2\lib\site-packages\conda\core\path_actions.py", line 33,
 in <module>
        from ..gateways.download import download
      File "C:\Anaconda2\lib\site-packages\conda\gateways\download.py", line 10,
 in <module>
        from requests.exceptions import ConnectionError, HTTPError, InvalidSchem
a, SSLError
      File "C:\Anaconda2\lib\site-packages\requests\__init__.py", line 84, in <m
odule>
        from urllib3.contrib import pyopenssl
      File "C:\Anaconda2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 4
6, in <module>
        import OpenSSL.SSL
      File "C:\Anaconda2\lib\site-packages\OpenSSL\__init__.py", line 8, in <mod
ule>
        from OpenSSL import rand, crypto, SSL
      File "C:\Anaconda2\lib\site-packages\OpenSSL\crypto.py", line 12, in <modu
le>
        from cryptography import x509
      File "C:\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line
9, in <module>
        from cryptography.x509.base import (
      File "C:\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16,
in <module>
        from cryptography.x509.extensions import Extension, ExtensionType
      File "C:\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", lin
e 13, in <module>
        from asn1crypto.keys import PublicKeyInfo
      File "C:\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <mod
ule>
        from ._elliptic_curve import (
      File "C:\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line
51, in <module>
        from ._int import inverse_mod
      File "C:\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <mod
ule>
        from ._perf._big_num_ctypes import libcrypto
      File "C:\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py",
 line 31, in <module>
        libcrypto_path = find_library('crypto')
      File "C:\Anaconda2\lib\ctypes\util.py", line 53, in find_library
        fname = os.path.join(directory, name)
      File "C:\Anaconda2\lib\ntpath.py", line 85, in join
        result_path = result_path + p_path
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x93 in position 49: ord
inal not in range(128)

C:\Users\m.modeler\Documents>

**Comment by mingwandroid** [comment]
Please show the value of PATH.

**Comment by tstegman** [comment]
PATH
C:\Program Files\Common Files\Intel\WirelessCommon\“;"C:\Program Files\R\R-3.1.0\bin\x64\";

PYTHONPATH
C:\Anaconda2;C:\Anaconda2\Scripts;C:\Anaconda2\Library\lib

**Comment by mingwandroid** [comment]
You need to remove the quotes from your PATH, both the non-ASCII “ one and the ASCII ones that serve no purpose.

**Comment by mingwandroid** [comment]
Also, do not set `PYTHONPATH` it is more trouble than it is worth.

**Comment by tstegman** [comment]
Thank you so much! It worked!!!
