### ISSUE TITLE
conda cannot update numpy

### ISSUE THREAD

**Issue by aktopus** [conda/conda#6202]
I'm trying to use pandas, but I am being told that I need an updated version of numpy. When I try to update numpy, I encounter the following:

```
#note - the below output has taken place when I tried all of the following:
#conda install numpy
#conda update numpy
#conda update conda

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/aetteh/miniconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 152, in main
    return conda_exception_handler(_main)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 497, in conda_exception_handler
    print_unexpected_error_message(e)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 443, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 413, in get_info
    args.func(args, p)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 225, in execute
    channels = list(prioritize_channels(channels).keys())
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 385, in prioritize_channels
    channel = Channel(chn)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 166, in __call__
    c = Channel.from_value(value)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/models/channel.py", line 226, in from_value
    if value in context.custom_multichannels:
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/base/context.py", line 252, in custom_multichannels
    'defaults': self.default_channels,
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/base/context.py", line 237, in default_channels
    for v in self._default_channels)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/base/context.py", line 237, in <genexpr>
    for v in self._default_channels)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
    cache[inner_attname] = func(self)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/base/context.py", line 220, in channel_alias
    location, scheme, auth, token = split_scheme_auth_token(self._channel_alias)
  File "/home/aetteh/miniconda2/lib/python2.7/site-packages/conda/common/url.py", line 193, in split_scheme_auth_token
    query=url_parts.query).url
AttributeError: 'Url' object has no attribute 'url'
```

Running conda 4.2.12 on Ubuntu 12.04.5 LTS (GNU/Linux 3.2.0-65-virtual x86_64)

While trying the different commands to show the version, I encountered the same error when using `$conda info`

**Comment by kalefranz** [comment]
Yup, you've used pip to change dependencies out from underneath conda.  You're on a very old version of conda also.  Easiest solution is just to start over.  Or you can use pip to try to put things back, but that's sort of like putting a Rubik's cube back to a solved state.  Best to know exactly what you're doing.

Lesson: Don't use pip on the root environment.  Only use pip inside non-root conda environments.
