### ISSUE TITLE
Im installing tensorflow and im getting this error im using the latest conda 

### ISSUE THREAD

**Issue by xFoolCode** [conda/conda#6204]
Exception:
Traceback (most recent call last):
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/home/mohammad/anaconda3/lib/python3.6/site-packages/pip/wheel.py", line 323, in clobber
    shutil.copyfile(srcfile, destfile)
  File "/home/mohammad/anaconda3/lib/python3.6/shutil.py", line 121, in copyfile
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: '/home/mohammad/anaconda3/lib/python3.6/site-packages/six.py'

**Comment by kalefranz** [comment]
You've apparently used `sudo` on that environment.  Best advice: never use `sudo` in front of conda or pip unless you *really* know exactly why and what you're doing.

To unwind this:

    sudo chown -R mohammad:mohammad /home/mohammad/anaconda3
