### ISSUE TITLE
Deactivate empties $PATH

### ISSUE THREAD

**Issue by jgmorrison** [conda/conda#6225]
Deactivating conda is breaking the shell. this is on a Linux system. We set up a common conda install with the most commonly used packages installed, then modify CONDA_ENVS_PATH and CONDA_PKGS_DIRS to point to the user's home directory so they can create their own environments. We also have to modify REQUESTS_CA_BUNDLE so our MITM security scans can sniff ssl traffic. bashrc does no activation.

**Important parts of an env that fails (it fails for all users):**

LD_LIBRARY_PATH=/nopt/torque/lib
PATH=/nopt/nrel/apps/anaconda/5.0/bin:/nopt/torque/sbin:/nopt/torque/bin:/nopt/moab/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/home/user1/bin
CONDA_PKGS_DIRS=/home/user1/.conda-pkgs
CONDA_ENVS_PATH=/home/user1/.conda-envs
REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-bundle.crt

**Conda Info:**

platform : linux-64
conda version : 4.3.29
conda is private : False
conda-env version : 4.3.29
conda-build version : 3.0.23
python version : 2.7.13.final.0
requests version : 2.18.4
root environment : /nopt/nrel/apps/anaconda/5.0 (writable)
default environment : /nopt/nrel/apps/anaconda/5.0
envs directories : /home/user1/.conda-envs
/nopt/nrel/apps/anaconda/5.0/envs
/home/user1/.conda/envs
package cache : /home/user1/.conda-pkgs
channel URLs : https://conda.anaconda.org/mpi4py/linux-64
https://conda.anaconda.org/mpi4py/noarch
https://conda.anaconda.org/bioconda/linux-64
https://conda.anaconda.org/bioconda/noarch
https://repo.continuum.io/pkgs/main/linux-64
https://repo.continuum.io/pkgs/main/noarch
https://repo.continuum.io/pkgs/free/linux-64
https://repo.continuum.io/pkgs/free/noarch
https://repo.continuum.io/pkgs/r/linux-64
https://repo.continuum.io/pkgs/r/noarch
https://repo.continuum.io/pkgs/pro/linux-64
https://repo.continuum.io/pkgs/pro/noarch
config file : /home/user1/.condarc
netrc file : None
offline mode : False
user-agent : conda/4.3.29 requests/2.18.4 CPython/2.7.13 Linux/3.10.0-514.6.1.el7_lustre.x86_64 CentOS Linux/7.3.1611 glibc/2.17
UID:GID : 120030:120030

**Activation:**
```
INFO: activate-binutils_linux-64.sh made the following environmental changes:
+ADDR2LINE=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-addr2line
+AR=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ar
+AS=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-as
+CXXFILT=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-elfedit
+GPROF=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gprof
+HOST=x86_64-conda_cos6-linux-gnu
+LD=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ld
+LD_GOLD=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ld.gold
+NM=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-nm
+OBJCOPY=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-objdump
+RANLIB=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ranlib
+READELF=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-readelf
+SIZE=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-size
+STRINGS=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-strings
+STRIP=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-64.sh made the following environmental changes:
+CC=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-cc
+CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CPP=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-cpp
+CPPFLAGS=-D_FORTIFY_SOURCE=2 -O2
+DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
+GCC=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc
+GCC_AR=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
+GCC_NM=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now
+_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_x86_64_conda_cos6_linux_gnu
INFO: activate-gfortran_linux-64.sh made the following environmental changes:
+DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
+F95=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-f95
+FC=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gfortran
+FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+GFORTRAN=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: activate-gxx_linux-64.sh made the following environmental changes:
+CXX=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-c++
+CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
+GXX=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-g++
```

**Deactivation:**
```
INFO: deactivate-binutils_linux-64.sh made the following environmental changes:
-ADDR2LINE=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-addr2line
-AR=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ar
-AS=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-as
-CXXFILT=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-c++filt
-ELFEDIT=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-elfedit
-GPROF=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gprof
-LD=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ld
-LD_GOLD=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ld.gold
-NM=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-nm
-OBJCOPY=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-objcopy
-OBJDUMP=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-objdump
-RANLIB=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-ranlib
-READELF=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-readelf
-SIZE=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-size
-STRINGS=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-strings
-STRIP=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-strip
INFO: deactivate-gcc_linux-64.sh made the following environmental changes:
-CC=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-cc
-CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
-CPP=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-cpp
-CPPFLAGS=-D_FORTIFY_SOURCE=2 -O2
-DEBUG_CFLAGS=-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-GCC=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc
-GCC_AR=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc-ar
-GCC_NM=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc-nm
-GCC_RANLIB=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gcc-ranlib
-LDFLAGS=-Wl,-O2,--sort-common,--as-needed,-z,relro,-z,now
INFO: deactivate-gfortran_linux-64.sh made the following environmental changes:
-DEBUG_FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-F95=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-f95
-FFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
-FORTRANFLAGS=-fopenmp -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
-GFORTRAN=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-gfortran
INFO: deactivate-gxx_linux-64.sh made the following environmental changes:
-CXX=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-c++
-CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
-DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-GXX=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-g++
Traceback (most recent call last):
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/site.py", line 553, in <module>
main()
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/site.py", line 530, in main
known_paths = addusersitepackages(known_paths)
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/site.py", line 275, in addusersitepackages
user_site = getusersitepackages()
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/site.py", line 250, in getusersitepackages
user_base = getuserbase() # this will also set USER_BASE
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/site.py", line 240, in getuserbase
USER_BASE = get_config_var('userbase')
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/sysconfig.py", line 524, in get_config_var
return get_config_vars().get(name)
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/sysconfig.py", line 476, in get_config_vars
_init_posix(_CONFIG_VARS)
File "/nopt/nrel/apps/anaconda/5.0/lib/python2.7/sysconfig.py", line 359, in _init_posix
_temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ImportError: No module named _sysconfigdata_x86_64_conda_cos6_linux_gnu
```

Echoing the $PATH is now empty and nothing works in the shell.

**Comment by jgmorrison** [comment]
I see at the end:

```
INFO: deactivate-gxx_linux-64.sh made the following environmental changes:
-CXX=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-c++
-CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
-DEBUG_CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -Og -g -Wall -Wextra -fcheck=all -fbacktrace -fimplicit-none -fvar-tracking-assignments
-GXX=/nopt/nrel/apps/anaconda/5.0/bin/x86_64-conda_cos6-linux-gnu-g++
```

Then it results in:

```
ImportError: No module named _sysconfigdata_x86_64_conda_cos6_linux_gnu
```

It appears on the ImportError during deactivation it fails and the PATH is never set back. If true why does it just quit when it fails and then leave the shell unusable?

**Comment by mingwandroid** [comment]
Can they try to update Python to the latest (2.7.14 is out now) and see if this is still a problem?

**Comment by jgmorrison** [comment]
tried with a fresh install, updated python and conda, and the deactivate seems to work. Thanks!
