### ISSUE TITLE
Errors installing ipython in environment containing fenics

### ISSUE THREAD

**Issue by scaramouche-00** [conda/conda#6235]
Hello, I just tried to install ipython in an anaconda environment containing fenics. I'm posting this issue because the installer says "Please consider posting the following information to the
conda GitHub issue tracker"

`

Current conda install:

               platform : osx-64
          conda version : 4.3.9
       conda is private : False
      conda-env version : 4.3.9
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /Users/my_mac_user_name/anaconda  (writable)
    default environment : /Users/my_mac_user_name/anaconda/envs/fenicsproject
       envs directories : /Users/my_mac_user_name/anaconda/envs
          package cache : /Users/my_mac_user_name/anaconda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/my_mac_user_name/.condarc
           offline mode : False
             user-agent : conda/4.3.9 requests/2.12.4 CPython/2.7.13 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20

`$ /Users/my_mac_user_name/anaconda/envs/fenicsproject/bin/conda install ipython`

    Traceback (most recent call last):
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 119, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 256, in execute
        self.verify()
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 239, in verify
        self.prepare()
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 170, in prepare
        concatv(unlink_actions, link_actions))
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 169, in <genexpr>
        self.all_actions = tuple(per_pkg_actions for per_pkg_actions in
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 166, in <genexpr>
        for pkg_info, lt in zip(self.packages_info_to_link, link_types)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 395, in make_link_actions
        python_entry_point_actions = CreatePythonEntryPointAction.create_actions(*required_quad)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/core/path_actions.py", line 388, in create_actions
        for ep_def in noarch.entry_points)
      File "/Users/my_mac_user_name/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 413, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for entry_points has not been set
`

**Comment by kalefranz** [comment]
`conda update conda`
