### ISSUE TITLE
can't update python3.4 to 3.6

### ISSUE THREAD

**Issue by sunshinemint616** [conda/conda#6239]
`conda create -n py36 python=3.6 anaconda` 

then 

`An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 3.4.5.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\Candice Bei\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Candice Bei\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Candice Bei\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Candice Bei\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.12.4 CPython/3.4.5 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create -n py36 python=3.6 anaconda`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_han
dler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 363, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructi
ons
        cmd(state, arg)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSAC
TION_CMD
        txn.execute()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 263, in execute
        self.verify()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 251, in verify
        self.num_unlink_pkgs),
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 248, in <genexpr>
        exceptions = tuple(exc for exc in concatv(
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 192, in _verify_individual_l
evel
        log.debug(format_exc())
      File "C:\ProgramData\Anaconda3\lib\traceback.py", line 256, in format_exc
        return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
      File "C:\ProgramData\Anaconda3\lib\traceback.py", line 181, in format_exception
        return list(_format_exception_iter(etype, value, tb, limit, chain))
      File "C:\ProgramData\Anaconda3\lib\traceback.py", line 146, in _format_exception_iter
        for value, tb in values:
      File "C:\ProgramData\Anaconda3\lib\traceback.py", line 125, in _iter_chain
        context = exc.__context__
    AttributeError: 'NoneType' object has no attribute '__context__'
`

**Comment by kalefranz** [comment]
Please `conda update conda`. After that, do you still have an issue?
