### ISSUE TITLE
test.py error "prefix is not writeable" 

### ISSUE THREAD

**Issue by tomashek** [conda/conda#6243]
While attempting to use "pyinstaller" to create a standalone conda-index executable, the resulting binary failed in “conda/gateways/disk/test.py” prefix_is_writable because that method assumes the prefix is a python root directory, and in the case of the standalone, the “prefix” is the executable’s current directory. If I add append sys.executable to the end of the “find_first_existing” call parameter list, then it worked as expected.

Of course, this particular writability check seems unnecessary for conda-index, because the only writing is to the target, not the conda-meta directory.

Any change that would allow the creation of a standalone conda-index is appreciated.

**Comment by tomashek** [comment]
Adding @msarahan since we had an email conversation about this

**Comment by kalefranz** [comment]
Hey @tomashek, not opposed to adding `sys.executable` at the moment.  It's possible it won't be completely future proof though, and it might be better to understand why conda-build's index needs to call that function.  Can you attach the stack trace for the failure so we can see the code path?

**Comment by tomashek** [comment]
Here is the stacktrace. Note that pyinstaller bundles the necessary files into a self-extracting executable that extracts to /tmp then executes the script from that location. That's why you see '/tmp/_MEI5zjz52' as the prefix.  The first stack is only the relevant conda files. I also included the full stack trace that has the pyinstaller wrappers as well:

Traceback (most recent call last):
  File "conda-index.py", line 7, in <module>
  File "site-packages/conda_build/cli/main_index.py", line 7, in <module>
  File "site-packages/conda_build/conda_interface.py", line 44, in <module>
  File "site-packages/conda/exports.py", line 75, in <module>
  File "site-packages/conda/config.py", line 70, in <module>
  File "site-packages/conda/base/context.py", line 285, in root_writable
  File "site-packages/conda/gateways/disk/test.py", line 70, in prefix_is_writable
conda.CondaError: Unable to determine if prefix '/tmp/_MEI5zjz52' is writable.
[19264] Failed to execute script conda-index

Traceback (most recent call last):
  File "conda-index.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/localdisk/work/tmtomash/miniconda3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/conda_build/cli/main_index.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/localdisk/work/tmtomash/miniconda3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/conda_build/conda_interface.py", line 44, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/localdisk/work/tmtomash/miniconda3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/conda/exports.py", line 75, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/localdisk/work/tmtomash/miniconda3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/conda/config.py", line 70, in <module>
  File "site-packages/conda/base/context.py", line 285, in root_writable
  File "site-packages/conda/gateways/disk/test.py", line 70, in prefix_is_writable
conda.CondaError: Unable to determine if prefix '/tmp/_MEI5zjz52' is writable.
[19264] Failed to execute script conda-index

**Comment by tomashek** [comment]
@kalefranz, any other ideas on a fix? Can the writability check be avoided for this operation?

**Comment by tomashek** [comment]
Thank you! I will try the patch locally.

**Comment by tomashek** [comment]
This works for my use-case. Thank you!
