### ISSUE TITLE
Add fetch_repodata() to conda.exports

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#6244]
Constructor depends on this functionality for pre-filling cache:

```
platform: linux-64
Traceback (most recent call last):
  File "/home/nwani/m3/bin/constructor", line 11, in <module>
    load_entry_point('constructor==1.7.0', 'console_scripts', 'constructor')()
  File "/home/nwani/m3/lib/python3.5/site-packages/constructor/main.py", line 221, in main
    dry_run=opts.dry_run)
  File "/home/nwani/m3/lib/python3.5/site-packages/constructor/main.py", line 77, in main_build
    from .shar import create
  File "/home/nwani/m3/lib/python3.5/site-packages/constructor/shar.py", line 17, in <module>
    from .preconda import files as preconda_files, write_files as preconda_write_files
  File "/home/nwani/m3/lib/python3.5/site-packages/constructor/preconda.py", line 11, in <module>
    from conda.core.repodata import fetch_repodata
ImportError: cannot import name 'fetch_repodata'
```

**Comment by kalefranz** [comment]
This should be resolved as part of https://github.com/conda/constructor/pull/140
