### ISSUE TITLE
Anaconda Prompt initialization error

### ISSUE THREAD

**Issue by adaswork** [conda/conda#6254]
Receiving the following error when click on "Start>Anaconda Prompt"

```
Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Anaconda2\lib\site-packages\conda\connection.py", line 55, in <module>
    python=platform.python_implementation(),
  File "C:\Python27\Lib\platform.py", line 1460, in python_implementation
    return _sys_version()[0]
  File "C:\Python27\Lib\platform.py", line 1422, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Anaconda 4.4.0 (32-bit
)| (default, May 11 2017, 14:07:41) [MSC v.1500 32 bit (Intel)]' 
```

**Comment by mingwandroid** [comment]
You probably have `PYTHONPATH` set to something. You need to delete this environment variable.
