### ISSUE TITLE
conda failign while creating a new environment

### ISSUE THREAD

**Issue by gerardogarciag1** [conda/conda#6257]
Using Anaconda API: https://api.anaconda.org
Fetching package metadata .............
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/gerardo/anaconda3  (writable)
    default environment : /home/gerardo/anaconda3
       envs directories : /home/gerardo/anaconda3/envs
                          /home/gerardo/.conda/envs
          package cache : /home/gerardo/anaconda3/pkgs
                          /home/gerardo/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.10.0-38-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/gerardo/anaconda3/bin/conda-env create -n fasta2`

    Traceback (most recent call last):
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 32, in install
        channel_priority_map=_channel_priority_map)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 473, in install_actions_list
        linked_in_root = linked_data(context.root_prefix)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "/home/gerardo/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/home/gerardo/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/home/gerardo/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/gerardo/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

gerardo@gerardo-System-Product-Name:~/fastai$ cd
gerardo@gerardo-System-Product-Name:~$ conda update conda
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/gerardo/anaconda3  (writable)
    default environment : /home/gerardo/anaconda3
       envs directories : /home/gerardo/anaconda3/envs
                          /home/gerardo/.conda/envs
          package cache : /home/gerardo/anaconda3/pkgs
                          /home/gerardo/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.10.0-38-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/gerardo/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 160, in install
        linked_dists = install_linked(prefix)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/home/gerardo/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "/home/gerardo/anaconda3/lib/python3.6/json/__init__.py", line 299, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "/home/gerardo/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/home/gerardo/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/gerardo/anaconda3/lib/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kalefranz** [comment]
Conda was made to force-quit during a previous operation, either by pulling power from the machine, force-closing the window conda was operating in, hitting ctrl-c several times, etc.  It's left your with a corrupted file in the `conda-meta` directory of your root environment.  Unfortunately, there's not much conda can do to help you out of here right now.  You'll have to track down the corrupted file yourself.  If you remove it, conda might be ok to proceed from there.  Otherwise, it might just be easier to start over with a new Anaconda install.
