### ISSUE TITLE
Hi, I wanted to install another python version on anaconda and got the following error

### ISSUE THREAD

**Issue by Vitalic57** [conda/conda#6261]
Current conda install:

                   platform : win-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.0.10
             python version : 3.5.2.final.0
           requests version : 2.13.0
           root environment : C:\Users\Vitaly\Anaconda3  (writable)
        default environment : C:\Users\Vitaly\Anaconda3
           envs directories : C:\Users\Vitaly\Anaconda3\envs
                          C:\Users\Vitaly\AppData\Local\conda\conda\envs
                          C:\Users\Vitaly\.conda\envs
              package cache : C:\Users\Vitaly\Anaconda3\pkgs
                          C:\Users\Vitaly\AppData\Local\conda\conda\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Vitaly\Anaconda3\Scripts\conda-script.py create --name py2 python=3.5 anaconda`

    Traceback (most recent call last):
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\cli\install.py", line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\plan.py", line 473, in install_actions_list
        linked_in_root = linked_data(context.root_prefix)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "C:\Users\Vitaly\Anaconda3\lib\json\__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Users\Vitaly\Anaconda3\lib\json\__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "C:\Users\Vitaly\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\Vitaly\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\Vitaly>conda create -n py2 python=2 anaconda
Fetching package metadata ...........
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

    Current conda install:

                   platform : win-64
              conda version : 4.3.17
           conda is private : False
          conda-env version : 4.3.17
        conda-build version : 2.0.10
             python version : 3.5.2.final.0
           requests version : 2.13.0
           root environment : C:\Users\Vitaly\Anaconda3  (writable)
        default environment : C:\Users\Vitaly\Anaconda3
           envs directories : C:\Users\Vitaly\Anaconda3\envs
                          C:\Users\Vitaly\AppData\Local\conda\conda\envs
                          C:\Users\Vitaly\.conda\envs
              package cache : C:\Users\Vitaly\Anaconda3\pkgs
                          C:\Users\Vitaly\AppData\Local\conda\conda\pkgs
               channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
                config file : None
               offline mode : False
                 user-agent : conda/4.3.17 requests/2.13.0 CPython/3.5.2 Windows/10 Windows/10.0.14393

`$ C:\Users\Vitaly\Anaconda3\Scripts\conda-script.py create -n py2 python=2 anaconda`

    Traceback (most recent call last):
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\cli\install.py", line 251, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\plan.py", line 473, in install_actions_list
        linked_in_root = linked_data(context.root_prefix)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\Vitaly\Anaconda3\lib\site-packages\conda\core\linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "C:\Users\Vitaly\Anaconda3\lib\json\__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\Users\Vitaly\Anaconda3\lib\json\__init__.py", line 319, in loads
        return _default_decoder.decode(s)
      File "C:\Users\Vitaly\Anaconda3\lib\json\decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\Vitaly\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by kalefranz** [comment]
Conda was made to force-quit during a previous operation, either by pulling power from the machine, force-closing the window conda was operating in, hitting ctrl-c several times, etc.  It's left your with a corrupted file in the `conda-meta` directory of your root environment.  Unfortunately, there's not much conda can do to help you out of here right now.  You'll have to track down the corrupted file yourself.  If you remove it, conda might be ok to proceed from there.  Otherwise, it might just be easier to start over with a new Anaconda install.
