### ISSUE TITLE
Not able to install caffe using conda

### ISSUE THREAD

**Issue by ayushya2531** [conda/conda#6263]
I tried to install caffe using conda through 'conda install caffe'. The installation starts well enough but stops after downloading caffe-1.0.0rc5 and on interrupting the following errors come:

^C
^CWARNING conda.gateways.disk.permissions:make_writable(39): Error making path writable: /users/gpu/abhiagwl/miniconda2/pkgs/boost-1.61.0-py27_0/include/boost/phoenix/bind/preprocessed/bind_function_20.hpp
CondaSignalInterrupt: Signal interrupt SIGINT
^C^C^C^CWARNING conda.gateways.disk.permissions:make_writable(39): Error making path writable: /users/gpu/abhiagwl/miniconda2/pkgs/boost-1.61.0-py27_0/include/boost/exception/errinfo_type_info_name.hpp
CondaSignalInterrupt: Signal interrupt SIGINT
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /users/gpu/abhiagwl/miniconda2  (writable)
    default environment : /users/gpu/abhiagwl/miniconda2/envs/abhinav
       envs directories : /users/gpu/abhiagwl/miniconda2/envs
                          /users/gpu/abhiagwl/.conda/envs
          package cache : /users/gpu/abhiagwl/miniconda2/pkgs
                          /users/gpu/abhiagwl/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/2.7.13 Linux/3.13.0-119-generic debian/jessie/sid glibc/2.19    
                UID:GID : 2065:2001

`$ /users/gpu/abhiagwl/miniconda2/envs/abhinav/bin/conda install caffe`

    Traceback (most recent call last):
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 100, in PROGRESSIVEFETCHEXTRACT_CMD
        progressive_fetch_extract.execute()
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 494, in execute
        self._execute_action(action)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/core/package_cache.py", line 509, in _execute_action
        action.reverse()
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 838, in reverse
        backoff_rename(self.hold_path, self.target_full_path)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/update.py", line 53, in backoff_rename
        exp_backoff_fn(rename, source_path, destination_path, force)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/__init__.py", line 21, in exp_backoff_fn
        return fn(*args, **kwargs)
      File "/users/gpu/abhiagwl/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/update.py", line 47, in rename
        os_rename(source_path, destination_path)
    OSError: [Errno 39] Directory not empty

**Comment by kalefranz** [comment]
Conda was still working when you hit ctrl-C several times.  The effect was ultimately a SIGKILL equivalent, and so the environment that conda was operating on is probably hosed.  If this was your root environment, you'll probably have to start over with a new miniconda install.  Just be more patient next time.  There's a lot of software being installed for you here.
