### ISSUE TITLE
Issue with Graphlab installation - Please help to resolve the issue

### ISSUE THREAD

**Issue by veera231** [conda/conda#6265]
Starting GraphLab Create 2.1 retrieval.

Starting Anaconda installation from C:\Users\vvalayap\AppData\Local\Temp\Anaconda2-4.0.0-Windows-x86_64.exe.

PATH environment variable updated.

Updating conda package.
Fetching package metadata: 
Solving package specifications: 

An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Using Anaconda Cloud api site https://api.anaconda.org
Traceback (most recent call last):
  File "C:\Users\vvalayap\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 62, in execute
    install.install(args, parser, 'install')
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\resolve.py", line 875, in install
    pkgs = self.solve(specs, len0=len0, returnall=returnall)
  File "C:\Users\vvalayap\Anaconda2\lib\site-packages\conda\resolve.py", line 909, in solve

**Comment by kalefranz** [comment]
You are also running a very old version of conda.  So start with `conda update conda`.  If you keep having issues, file a new issue with the new stack trace.  Also, please always include the output of `conda info`.

**Comment by kalefranz** [comment]
Looking at this again, it looks like there's something else calling conda.  GraphLab I guess.  Not sure what that is, but you might want to file an issue with them.
