### ISSUE TITLE
issues when I try to create a new conda environment

### ISSUE THREAD

**Issue by HuazhenXia** [conda/conda#6272]
[Anaconda2] C:\Users\asus>conda create -n gl-env python=2.7
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ......
Solving package specifications: .
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Users\asus\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\cli\install.py", line 334, in install
    update_deps=args.update_deps)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\plan.py", line 413, in install_actions
    pkgs = r.install(specs, [d + '.tar.bz2' for d in linked], update_deps=update_deps)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 875, in install
    pkgs = self.solve(specs, len0=len0, returnall=returnall)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 909, in solve
    dists, new_specs = self.get_dists(specs)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 399, in get_dists
    specs, removes, optional, features = self.verify_specs(specs)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 391, in verify_specs
    bad_deps.extend(self.invalid_chains(ms, filter))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 359, in invalid_chains
    return chains_(spec)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
......
.......
 File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 351, in chains_
    if spec.name == top or self.valid(spec, filter):
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 299, in valid
    return v_(spec)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 287, in v_
    return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 290, in v_ms_
    return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
  File "C:\Users\asus\Anaconda2\lib\site-packages\conda\resolve.py", line 554, in find_matches
    res = self.find_matches_.get(ms, None)
RuntimeError: maximum recursion depth exceeded

**Comment by r18k1ume** [comment]
Same issue occurs to me while installing graphlab

**Comment by kalefranz** [comment]
Please provide the output of `conda info`

**Comment by tjboller** [comment]
same issue - 
![capture](https://user-images.githubusercontent.com/8171540/32528682-5fbc361c-c402-11e7-8575-2c1646927574.PNG)

**Comment by kalefranz** [comment]
Conda 4.0.6 is *old*.  `conda update conda` should fix your problem.

**Comment by r18k1ume** [comment]
File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
    notfound.update(chains_(m2))
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 351, in chains_
    if spec.name == top or self.valid(spec, filter):
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 299, in valid
    return v_(spec)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 287, in v_
    return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 290, in v_ms_
    return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 554, in find_matches
    res = self.find_matches_.get(ms, None)
  File "C:\Users\Administrator\Anaconda2\lib\site-packages\conda\resolve.py", line 151, in __eq__
    return type(other) is MatchSpec and self.spec == other.spec
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by tjboller** [comment]
I'm trying - I get the same issue maximum recursion issue
![image](https://user-images.githubusercontent.com/8171540/32528990-de44836c-c403-11e7-86f9-c2f7584b1576.png)

**Comment by r18k1ume** [comment]
Hi,


Not solved. Same error.

________________________________

**Comment by tjboller** [comment]
no luck =/

**Comment by kalefranz** [comment]
@r18k1ume and @HuazhenXia Can you please provide the output of `conda info`?

**Comment by r18k1ume** [comment]
[launcher-install-log.txt](https://github.com/conda/conda/files/1452588/launcher-install-log.txt)

**Comment by Aditya000786** [comment]
Facing the same issue :
RuntimeError: maximum recursion depth exceeded while calling a Python object
please someone help me out

**Comment by sknoth** [comment]
I have the same issue, also trying to update conda leads to the same issue:

>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 357, in chains_
>     notfound.update(chains_(m2))
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 351, in chains_
>     if spec.name == top or self.valid(spec, filter):
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 299, in valid
>     return v_(spec)
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 287, in v_
>     return v_ms_(spec) if isinstance(spec, MatchSpec) else v_fn_(spec)
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 290, in v_ms_
>     return ms.optional or any(v_fn_(fn) for fn in self.find_matches(ms))
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 554, in find_matches
>     res = self.find_matches_.get(ms, None)
>   File "C:\Users\Stefanie\Anaconda2\lib\site-packages\conda\resolve.py", line 151, in __eq__
>     return type(other) is MatchSpec and self.spec == other.spec
> RuntimeError: maximum recursion depth exceeded while calling a Python object

My environment:

> λ conda info
> Using Anaconda Cloud api site https://api.anaconda.org
> Current conda install:
> 
>              platform : win-64
>         conda version : 4.0.5
>   conda-build version : 1.20.0
>        python version : 2.7.11.final.0
>      requests version : 2.9.1
>      root environment : C:\Users\Stefanie\Anaconda2  (writable)
>   default environment : C:\Users\Stefanie\Anaconda2
>      envs directories : C:\Users\Stefanie\Anaconda2\envs
>         package cache : C:\Users\Stefanie\Anaconda2\pkgs
>          channel URLs : https://repo.continuum.io/pkgs/free/win-64/
>                         https://repo.continuum.io/pkgs/free/noarch/
>                         https://repo.continuum.io/pkgs/pro/win-64/
>                         https://repo.continuum.io/pkgs/pro/noarch/
>           config file : None
>     is foreign system : False

**Comment by kalefranz** [comment]
Can you provide the contents of

    C:\Users\Stefanie\.condarc

Probably just open Notepad, go to File | Open, and paste that path.

**Comment by kalefranz** [comment]
What is the shell environment you are using? I don’t recognize the lambda prompt on Windows...

**Comment by r18k1ume** [comment]
@kalefranz how to fix this, kindly help

**Comment by tjboller** [comment]
@r18k1ume that's what he's doing.

I've had luck just installing python 3 and the new anaconda from the websites. It was time for an upgrade anyway

**Comment by sknoth** [comment]
@kalefranz it is windows 10 with the cmder command line (http://cmder.net/)
it seems this .condarc folder has not been created for me for some reason
