### ISSUE TITLE
Unable to open Anaconda Prompt. Please Help

### ISSUE THREAD

**Issue by JDSCTI** [conda/conda#6276]
Current conda install:

               platform : win-32
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda2  (read only)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\Users\jsavage\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda2\envs
                          C:\Users\jsavage\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\jsavage\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\jsavage\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\ProgramData\Anaconda2\Scripts\conda ..checkenv cmd.exe C:\ProgramData\Anaconda2`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 171, in main
        activate.main()
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\activate.py", line 181, in main
        from ..install import symlink_conda
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\install.py", line 37, in <module>
        from .core.package_cache import rm_fetched  # NOQA
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
        from ..gateways.download import download
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\gateways\download.py", line 10, in <module>
        from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
      File "C:\ProgramData\Anaconda2\lib\site-packages\requests\__init__.py", line 84, in <module>
        from urllib3.contrib import pyopenssl
      File "C:\ProgramData\Anaconda2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
      File "C:\ProgramData\Anaconda2\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "C:\ProgramData\Anaconda2\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
        from cryptography import x509
      File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 9, in <module>
        from cryptography.x509.base import (
      File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
        from cryptography.x509.extensions import Extension, ExtensionType
      File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>
        from asn1crypto.keys import PublicKeyInfo
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
        from ._elliptic_curve import (
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
        from ._int import inverse_mod
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
        from ._perf._big_num_ctypes import libcrypto
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
        libcrypto_path = find_library('crypto')
      File "C:\ProgramData\Anaconda2\lib\ctypes\util.py", line 53, in find_library
        fname = os.path.join(directory, name)
      File "C:\ProgramData\Anaconda2\lib\ntpath.py", line 85, in join
        result_path = result_path + p_path
    UnicodeDecodeError: 'ascii' codec can't decode byte 0x94 in position 4: ordinal not in range(128)

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/issues/6650
