### ISSUE TITLE
An unexpected error running conda install -c soumith magma-cuda80

### ISSUE THREAD

**Issue by HMEIatJHU** [conda/conda#6278]
23:01:56  kitsing@magnesia  ~  1m26s  $ conda install -c soumith magma-cuda80
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /home/kitsing/anaconda2  (writable)
    default environment : /home/kitsing/anaconda2
       envs directories : /home/kitsing/anaconda2/envs
                          /home/kitsing/.conda/envs
          package cache : /home/kitsing/anaconda2/pkgs
                          /home/kitsing/.conda/pkgs
           channel URLs : https://conda.anaconda.org/soumith/linux-64
                          https://conda.anaconda.org/soumith/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.13 Linux/4.10.0-37-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/kitsing/anaconda2/bin/conda install -c soumith magma-cuda80`

    Traceback (most recent call last):
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/kitsing/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    IOError: [Errno 13] Permission denied: u'/home/kitsing/anaconda2/pkgs/cache/252c32c9.json'

**Comment by kalefranz** [comment]
I have no idea how you could have gotten here.  Haven't seen this for a very long time.

    sudo chown -R 1000:1000 /home/kitsing/anaconda2
