### ISSUE TITLE
permission denied while upgrading packages

### ISSUE THREAD

**Issue by onkkul** [conda/conda#6282]
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/NAIFE/anaconda3  (writable)
    default environment : /home/NAIFE/anaconda3
       envs directories : /home/NAIFE/anaconda3/envs
                          /home/NAIFE/.conda/envs
          package cache : /home/NAIFE/anaconda3/pkgs
                          /home/NAIFE/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/NAIFE/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.11.12-200.fc25.x86_64 Fedora/25 glibc/2.24    
                UID:GID : 1000:1000

`$ /home/NAIFE/anaconda3/bin/conda upgrade --all`

    Traceback (most recent call last):
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/NAIFE/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/NAIFE/anaconda3/pkgs/cache/6846611e.json'

[NAIFE@localhost ~]$

**Comment by kalefranz** [comment]
sudo chown -R 1000:1000 /home/NAIFE/anaconda3
