### ISSUE TITLE
conda intel distribution installation failed

### ISSUE THREAD

**Issue by minhhg** [conda/conda#6287]
Hi,
I got the following error when I do
$conda config --add channels intel
$conda install intelpython2_full

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : 2.1.5
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /home/minh/miniconda2  (writable)
    default environment : /home/minh/miniconda2/envs/mkl
       envs directories : /home/minh/miniconda2/envs
                          /home/minh/.conda/envs
          package cache : /home/minh/miniconda2/pkgs
                          /home/minh/.conda/pkgs
           channel URLs : https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/minh/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.13 Linux/3.13.0-48-generic debian/jessie/sid glibc/2.19
                UID:GID : 1002:2000
`$ /home/minh/miniconda2/envs/mkl/bin/conda install intelpython2_full`

    Traceback (most recent call last):
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 89, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in <genexpr>
  return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/minh/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.

**Comment by kalefranz** [comment]
Please `conda update conda`. Latest conda version is 4.3.30.
Do you still get the same error?  If so, please paste the error again, along with the output of `conda info`
