### ISSUE TITLE
Unexpected error when running conda

### ISSUE THREAD

**Issue by ntmitchell** [conda/conda#6288]
```
Current conda install:

               platform : osx-64
          conda version : 4.3.5
       conda is private : False
      conda-env version : 4.3.5
    conda-build version : 2.1.1
         python version : 3.5.2.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda
       envs directories : //anaconda/envs
          package cache : //anaconda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.5 requests/2.12.4 CPython/3.5.2 Darwin/17.2.0 OSX/10.13.1
                UID:GID : 501:20



`$ //anaconda/bin/conda`




    Traceback (most recent call last):
      File "//anaconda/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 90, in _main
        args.append('-h')
    AttributeError: 'tuple' object has no attribute 'append'


```

**Comment by kalefranz** [comment]
`conda update conda`
