### ISSUE TITLE
Installing boto3 failing in Anaconda 3: permission denied

### ISSUE THREAD

**Issue by haritharallapalli** [conda/conda#6291]
I am trying to install boto3, its failing with errors.

Command: conda install -c conda boto3

config file : C:\Users\SESPL\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.15063
          administrator : False

Traceback (most recent call last):
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "C:\Users\SESPL\Anaconda3\lib\site-packages\conda\core\repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\Users\\SESPL\\Anaconda3\\pkgs\\cache\\7ffb1139.json'

**Comment by kalefranz** [comment]
The easiest solution to this immediate problem is to manually delete the directory

    C:\Users\SESPL\Anaconda3\pkgs\cache

You may have follow-on permissions problems, if you've mixed "Administrator" and normal user shells using versions of conda less than 4.3.  In that case, if you continue to have issues, the easiest solution might be just to start over.

**Comment by haritharallapalli** [comment]
I dint try deleting cache but pip install worked.

python -m pip install boto3 from anaconda prompt installed boto3.
