### ISSUE TITLE
Error While creating virtual environment using conda

### ISSUE THREAD

**Issue by yatendrayadav** [conda/conda#6300]
@scw @brentp @tswicegood @jbcrail @blindgaenger      https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/usr/local/miniconda/bin/conda", line 6, in <module>
    sys.exit(main())
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 139, in main
    args_func(args, p)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 146, in args_func
    args.func(args, p)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 424, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/plan.py", line 539, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 149, in execute_instructions
    cmd(state, arg)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 52, in FETCH_CMD
    fetch(state['index'], arg)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/instructions.py", line 48, in fetch
    fetch_pkg(index[fn])
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 296, in fetch_pkg
    download(url, path, session=session, md5=info['md5'], urlstxt=True)
  File "/usr/local/miniconda/lib/python2.7/site-packages/conda/fetch.py", line 376, in download
    chunk  = resp.raw.read(2**14)
  File "/usr/local/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 311, in read
    flush_decoder = True
  File "/usr/local/miniconda/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/miniconda/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
requests.packages.urllib3.exceptions.ProtocolError: ("Connection broken: error(104, 'Connection reset by peer')", error(104, 'Connection reset by peer'))

**Comment by mingwandroid** [comment]
Why have you spammed all of these people by referring to them their github handles?
You have not provided the information that the error message asked for.
You have filed this bug in the wrong place, the correct place being https://github.com/ContinuumIO/anaconda-issues
