### ISSUE TITLE
conda promt problem

### ISSUE THREAD

**Issue by zzddsg** [conda/conda#6301]
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.25
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : D:\anaconda2  (writable)
    default environment : D:\anaconda2
       envs directories : D:\anaconda2\envs
                          C:\Users\mandy\AppData\Local\conda\conda\envs
                          C:\Users\mandy\.conda\envs
          package cache : D:\anaconda2\pkgs
                          C:\Users\mandy\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.13 Windows/10 Windows/10.0.14393
          administrator : False

`$ D:\anaconda2\Scripts\conda ..checkenv cmd.exe D:\anaconda2`

    Traceback (most recent call last):
      File "D:\anaconda2\lib\site-packages\conda\cli\main.py", line 171, in main
        activate.main()
      File "D:\anaconda2\lib\site-packages\conda\cli\activate.py", line 181, in main
        from ..install import symlink_conda
      File "D:\anaconda2\lib\site-packages\conda\install.py", line 37, in <module>
        from .core.package_cache import rm_fetched  # NOQA
      File "D:\anaconda2\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "D:\anaconda2\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
        from ..gateways.download import download
      File "D:\anaconda2\lib\site-packages\conda\gateways\download.py", line 10, in <module>
        from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
      File "D:\anaconda2\lib\site-packages\requests\__init__.py", line 84, in <module>
        from urllib3.contrib import pyopenssl
      File "D:\anaconda2\lib\site-packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
        import OpenSSL.SSL
      File "D:\anaconda2\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "D:\anaconda2\lib\site-packages\OpenSSL\crypto.py", line 12, in <module>
        from cryptography import x509
      File "D:\anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 9, in <module>
        from cryptography.x509.base import (
      File "D:\anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
        from cryptography.x509.extensions import Extension, ExtensionType
      File "D:\anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 13, in <module>
        from asn1crypto.keys import PublicKeyInfo
      File "D:\anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
        from ._elliptic_curve import (
      File "D:\anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
        from ._int import inverse_mod
      File "D:\anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
        from ._perf._big_num_ctypes import libcrypto
      File "D:\anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
        libcrypto_path = find_library('crypto')
      File "D:\anaconda2\lib\ctypes\util.py", line 53, in find_library
        fname = os.path.join(directory, name)
      File "D:\anaconda2\lib\ntpath.py", line 85, in join
        result_path = result_path + p_path
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc6 in position 16: ordinal not in range(128)

C:\Users\mandy\Documents>

**Comment by mingwandroid** [comment]
Please search for existing issues before opening new ones. This is a duplicate.

`codec can't decode byte ` appears in 55 issues in this repository: https://github.com/conda/conda/search?q=codec+can%27t+decode+byte&type=Issues&utf8=%E2%9C%93

.. and in 15 issues in the anaconda-issues repository: https://github.com/ContinuumIO/anaconda-issues/search?q=codec+can%27t+decode+byte&type=Issues&utf8=%E2%9C%93

The problem is that you cannot use any non-ASCII characters in `PATH` when using Python2 so you need to fix your `PATH` environment variable.
