### ISSUE TITLE
Can not update Conda

### ISSUE THREAD

**Issue by hellojena** [conda/conda#6302]
Conda prompt following messages when I tried to update it: 

Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /public/home/xz21/miniconda2  (writable)
    default environment : /public/home/xz21/miniconda2
       envs directories : /public/home/xz21/miniconda2/envs
                          /public/home/xz21/.conda/envs
          package cache : /public/home/xz21/miniconda2/pkgs
                          /public/home/xz21/.conda/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
            config file : /public/home/xz21/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.12.4 CPython/2.7.13 Linux/2.6.32-431.el6.x86_64 CentOS/6.5 glibc/2.12
                UID:GID : 524:501

`$ /public/home/xz21/miniconda2/bin/conda update conda`

    Traceback (most recent call last):
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/sessions.py", line 641, in send
        r.content
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/models.py", line 781, in content
        self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/models.py", line 703, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 428, in stream
        for line in self.read_chunked(amt, decode_content=decode_content):
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 590, in read_chunked
        self._update_chunk_length()
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/response.py", line 532, in _update_chunk_length
        line = self._fp.fp.readline()
      File "/public/home/xz21/miniconda2/lib/python2.7/socket.py", line 451, in readline
        data = self._sock.recv(self._rbufsize)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 250, in recv
        return self.recv(*args, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 250, in recv
        return self.recv(*args, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 250, in recv
        return self.recv(*args, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 250, in recv
        return self.recv(*args, **kwargs)
      File "/public/home/xz21/miniconda2/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 246, in recv
        [self.socket], [], [], self.socket.gettimeout())
    error: (4, 'Interrupted system call')

When I tried the second time, it prints out:

conda update conda
Fetching package metadata .....
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/bioconda/linux-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(ReadTimeoutError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Read timed out.",),)

Could someone help me with that?

**Comment by kalefranz** [comment]
You're getting a timeout error due to a flakey internet connection.
