### ISSUE TITLE
Conda runtime error on Linux

### ISSUE THREAD

**Issue by amwalker** [conda/conda#6315]
Current conda install:

               platform : linux-64
          conda version : 4.2.12
       conda is private : False
      conda-env version : 4.2.12
    conda-build version : 1.20.0
         python version : 2.7.11.final.0
       requests version : 2.9.1
       root environment : /usr/local/pkg/lang/Anaconda2/4.0.0  (read only)
    default environment : /usr/local/pkg/lang/Anaconda2/4.0.0
       envs directories : /u1/uaf/amwalker8/.conda/envs
                          /usr/local/pkg/lang/Anaconda2/4.0.0/envs
          package cache : /u1/uaf/amwalker8/.conda/envs/.pkgs
                          /usr/local/pkg/lang/Anaconda2/4.0.0/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False

`$ /usr/local/pkg/lang/Anaconda2/4.0.0/bin/conda create -n qiime2-2017.10 --file https://data.qiime2.org/distro/core/qiime2-2017.10-conda-linux-64.txt`

    Traceback (most recent call last):
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/cli/install.py", line 191, in install
        explicit(specs, prefix, verbose=not context.quiet, index_args=index_args)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/misc.py", line 187, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/fetch.py", line 363, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/usr/local/pkg/lang/Anaconda2/4.0.0/lib/python2.7/site-packages/conda/fetch.py", line 450, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    CondaRuntimeError: Runtime error: Could not open u'/usr/local/pkg/lang/Anaconda2/4.0.0/pkgs/r-lattice-0.20_34-r3.3.2_0.tar.bz2.part' for writing ([Errno 13] Permission denied: u'/usr/local/pkg/lang/Anaconda2/4.0.0/pkgs/r-lattice-0.20_34-r3.3.2_0.tar.bz2.part').

**Comment by kalefranz** [comment]
Conda 4.2 is no longer supported.  Please update to conda 4.3 or 4.4.
