### ISSUE TITLE
IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by adaswork** [conda/conda#6320]
Current conda install:

               platform : win-32
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2\envs\tensorflow
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Athena\AppData\Local\conda\conda\envs
                          C:\Users\Athena\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Athena\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\Athena\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7 Windows/6.1.7601
          administrator : True

`$ C:\ProgramData\Anaconda2\Scripts\conda install pandas matplotlib jupyter notebook scipy scikit-learn`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\instructions.py", line 95, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\install.py", line 113, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
        with open(dst, "w") as f:
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\common\compat.py", line 118, in open
        closefd=closefd)
    IOError: [Errno 13] Permission denied: u'C:\\ProgramData\\Anaconda2\\envs\\tensorflow\\Scripts\\conda'

**Comment by IronFarm** [comment]
I usually find the packages are installed but you have to quit and re-open your terminal.

**Comment by kalefranz** [comment]
This code path no longer exists in conda 4.4.
