### ISSUE TITLE
issues when install scrapy using conda

### ISSUE THREAD

**Issue by HannahYang04** [conda/conda#6321]
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/hannah/anaconda3  (writable)
    default environment : /Users/hannah/anaconda3
       envs directories : /Users/hannah/anaconda3/envs
                          /Users/hannah/.conda/envs
          package cache : /Users/hannah/anaconda3/pkgs
                          /Users/hannah/.conda/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          heep://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
                          heep://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/hannah/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /Users/hannah/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 612, in send
        adapter = self.get_adapter(url=request.url)
      File "/Users/hannah/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 703, in get_adapter
        raise InvalidSchema("No connection adapters were found for '%s'" % url)
    requests.exceptions.InvalidSchema: No connection adapters were found for 'heep://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64/repodata.json'

**Comment by kalefranz** [comment]
heep://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
