### ISSUE TITLE
Conda create clone on NFS

### ISSUE THREAD

**Issue by JenCabral** [conda/conda#6331]
When I try running conda create --clone on our cluster which uses NFS storage, I am consistently getting an error that ends with OSError: [Errno 22] Invalid argument: no matter which environment I try to clone, and the invalid argument is always the first file it tries to copy
```
conda create -p /Drives/P/GView/.conda/envs/testcopyalbacore --clone albacore --copy                                             
Source:      /Drives/P/conda_envs/albacore
Destination: /Drives/P/GView/.conda/envs/testcopyalbacore
Packages: 31
Files: 95
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /opt/miniconda3  (read only)
    default environment : /opt/miniconda3
       envs directories : /Drives/P/conda_envs
                          /Drives/X/public/conda_envs
                          /Drives/P/GView/.conda/envs
                          /opt/miniconda3/envs
          package cache : /opt/miniconda3/pkgs
                          /Drives/P/GView/.conda/pkgs
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /opt/miniconda3/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-693.2.2.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17    

`$ /opt/miniconda3/bin/conda create -p /Drives/P/GView/.conda/envs/testcopyalbacore --clone albacore --copy`




    Traceback (most recent call last):
      File "/opt/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/opt/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/opt/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/opt/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 74, in clone
        index_args=index_args)
      File "/opt/miniconda3/lib/python3.6/site-packages/conda/misc.py", line 309, in clone_env
        shutil.copystat(src, dst)
      File "/opt/miniconda3/lib/python3.6/shutil.py", line 225, in copystat
        _copyxattr(src, dst, follow_symlinks=follow)
      File "/opt/miniconda3/lib/python3.6/shutil.py", line 164, in _copyxattr
        value = os.getxattr(src, name, follow_symlinks=follow_symlinks)
    OSError: [Errno 22] Invalid argument: '/Drives/P/conda_envs/albacore/lib/python3.6/site-packages/albacore/data_versioned/template_r9.5_450bps_5mer_raw.jsn'
```
It was recommended it might have to do with this issue with python: 
https://bugs.python.org/issue24564

**Comment by nicolaasuni** [comment]
I am experiencing the same error when using conda build with the "--no-remove-work-dir" option in a NFS mounted directory:

```
shutil.copystat(src, dst)
  File "/data/home/user/env-dummy/lib/python3.6/shutil.py", line 225, in copystat
    _copyxattr(src, dst, follow_symlinks=follow)
  File "/data/home/user/env-dummy/lib/python3.6/shutil.py", line 165, in _copyxattr
    os.setxattr(dst, name, value, follow_symlinks=follow_symlinks)
OSError: [Errno 22] Invalid argument: '/data/home/user/env-dummy/conda-bld/dummy_1531743495822/work/conda'
```
It seems that this is a Python bug: https://bugs.python.org/issue24564
Is there anyway we can circumvent this with Conda?

**Comment by mingwandroid** [comment]
@nicolaasuni it is difficult for us to test this kind of problem. PRs welcome.
