### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by pnjoroge54** [conda/conda#6337]
I've been unsuccessfully trying to create an environment in Jupyter notebook that has the same properties as the 'dand-env-win.yaml' file. This is what the shell throws out.

(C:\Users\htpc\Anaconda3) C:\Users\htpc>conda env create -f dand-env-win.yaml
Using Anaconda API: https://api.anaconda.org
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.30
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : C:\Users\htpc\Anaconda3  (writable)
    default environment : C:\Users\htpc\Anaconda3
       envs directories : C:\Users\htpc\Anaconda3\envs
                          C:\Users\htpc\AppData\Local\conda\conda\envs
                          C:\Users\htpc\.conda\envs
          package cache : C:\Users\htpc\Anaconda3\pkgs
                          C:\Users\htpc\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False

`$ C:\Users\htpc\Anaconda3\Scripts\conda-env create -f dand-env-win.yaml`

    Traceback (most recent call last):
      File "C:\Users\htpc\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\htpc\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Users\htpc\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
        if spec.can_handle():
      File "C:\Users\htpc\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Users\htpc\Anaconda3\lib\site-packages\conda_env\env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Users\htpc\Anaconda3\lib\site-packages\conda_env\env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 75, in load
        return loader.get_single_data()
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 48, in get_single_node
        self.get_event()
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 136, in get_event
        self.current_event = self.state()
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 150, in parse_stream_start
        token.move_comment(self.peek_token())
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 144, in peek_token
        self.fetch_more_tokens()
      File "C:\Users\htpc\Anaconda3\lib\site-packages\ruamel_yaml\scanner.py", line 276, in fetch_more_tokens
        % utf8(ch), self.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '@' that cannot start any token
      in "<unicode string>", line 4, column 1:
        @EXPLICIT
        ^

**Comment by kalefranz** [comment]
Your file `dand-env-win.yaml` is the wrong format.  It must be yaml, **not** the output of `conda list --explicit`.  What you want is `conda env export`.
