### ISSUE TITLE
memex explorer error downloading in mac

### ISSUE THREAD

**Issue by Dimple15** [conda/conda#6339]
urrent conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /anaconda3  (writable)
    default environment : /anaconda3
       envs directories : /anaconda3/envs
                          /Users/Dimple/.conda/envs
          package cache : /anaconda3/pkgs
                          /Users/Dimple/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/Dimple/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/16.7.0 OSX/10.12.6    
                UID:GID : 501:20

`$ /anaconda3/bin/conda-env update --file environment.yml`

    Traceback (most recent call last):
      File "/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_update.py", line 106, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "/anaconda3/lib/python3.6/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "/anaconda3/lib/python3.6/site-packages/conda_env/pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/anaconda3/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/anaconda3/envs/memex/bin/python', '/anaconda3/envs/memex/bin/pip', '-V']' returned non-zero exit status 1.

~/memex-explorer/source
~/memex-explorer/source/memex ~/memex-explorer/source
~/memex-explorer/source
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/anaconda3/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/anaconda3/envs/memex/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/anaconda3/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/anaconda3/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/anaconda3/envs/memex/lib/python2.7/site-packages/django/conf/__init__.py", line 98, in __init__
    % (self.SETTINGS_MODULE, e)
ImportError: Could not import settings 'memex.settings' (Is it on sys.path? Is there an import error in the settings file?): No module named celery

**Comment by kalefranz** [comment]
Ummm that's just subprocessing to pip, and it's pip that's throwing the error, right?
