### ISSUE TITLE
Getting error for conda install

### ISSUE THREAD

**Issue by jainsaurabh04** [conda/conda#6343]
Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : /Users/saurabhjain/Library/Caches/AmlWorkbench/Python  (writable)
    default environment : /Users/saurabhjain/Library/Caches/AmlWorkbench/Python
       envs directories : /Users/saurabhjain/Library/Caches/AmlWorkbench/Python/envs
                          /Users/saurabhjain/.conda/envs
          package cache : /Users/saurabhjain/Library/Caches/AmlWorkbench/Python/pkgs
                          /Users/saurabhjain/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64  (offline)
                          https://repo.continuum.io/pkgs/main/noarch  (offline)
                          https://repo.continuum.io/pkgs/free/osx-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/osx-64  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/osx-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
            config file : None
             netrc file : None
           offline mode : True
             user-agent : conda/4.3.27 requests/2.11.1 CPython/3.5.2 Darwin/17.2.0 OSX/10.13.1    
                UID:GID : 501:20

`$ /Users/saurabhjain/Library/Caches/AmlWorkbench/Python/bin/conda install --no-deps --offline --yes --force /private/tmp/AmlInstaller/libffi.macos-3.2.1/libffi-3.2.1-3.tar.bz2`

    Traceback (most recent call last):
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/cli/install.py", line 210, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/misc.py", line 110, in explicit
        execute_actions(actions, index, verbose=verbose)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/plan.py", line 830, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/core/link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/core/link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 95, in read_package_info
        paths_data=paths_data,
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 831, in __setattr__
        super(ImmutableEntity, self).__setattr__(attribute, value)
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/saurabhjain/Library/Caches/AmlWorkbench/Python/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for url cannot be None.

**Comment by nehaljwani** [comment]
Is /private/tmp/AmlInstaller/libffi.macos-3.2.1/libffi-3.2.1-3.tar.bz2 a conda package?
