### ISSUE TITLE
Unexpected Error in installing Tensorflow with Git bash on Windows

### ISSUE THREAD

**Issue by paragguruji** [conda/conda#6346]
```
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.21.3
         python version : 2.7.12.final.0
       requests version : 2.13.0
       root environment : C:\Users\Parag\Anaconda2  (writable)
    default environment : C:\Users\Parag\Anaconda2\envs\tensorenv
       envs directories : C:\Users\Parag\Anaconda2\envs
                          C:\Users\Parag\AppData\Local\conda\conda\envs
                          C:\Users\Parag\.conda\envs
          package cache : C:\Users\Parag\Anaconda2\pkgs
                          C:\Users\Parag\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.13.0 CPython/2.7.12 Windows/7 Windows/6.1.7601
          administrator : False

`$ C:\Users\Parag\Anaconda2\Scripts\conda install tensorflow`




    Traceback (most recent call last):
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\instructions.py", line 95, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\install.py", line 113, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
        with open(dst, "w") as f:
      File "C:\Users\Parag\Anaconda2\lib\site-packages\conda\common\compat.py", line 118, in open
        closefd=closefd)
    IOError: [Errno 13] Permission denied: u'C:\\Users\\Parag\\Anaconda2\\envs\\tensorenv\\Scripts\\conda'

```

**Comment by kalefranz** [comment]
Were you able to resolve your issue here?
