### ISSUE TITLE
conda qiime package returns an error (incomplete?)

### ISSUE THREAD

**Issue by ruyjau** [conda/conda#6357]
Hello! The qiime package seems to be incomplete, it failed with this error:
The call was:
assign_taxonomy.py -i filtered_all.fa -r nogap2_silva_seed_v128.fasta -t silva.seed_v128.tax -m blast
The output was:
Traceback (most recent call last):
  File "/home/jaureguir/conda-envs/qiime/bin/assign_taxonomy.py", line 4, in <module>
    __import__('pkg_resources').run_script('qiime==1.9.1', 'assign_taxonomy.py')
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/assign_taxonomy.py", line 417, in <module>
    main()
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/qiime-1.9.1-py2.7.egg-info/scripts/assign_taxonomy.py", line 394, in main
    log_path=log_path)
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/qiime/assign_taxonomy.py", line 500, in __call__
    abspath(reference_seqs_path), output_dir=blast_db_dir)
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/burrito_fillings-0.1.1-py2.7.egg/bfillings/formatdb.py", line 116, in build_blast_db_from_fasta_path
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/burrito-0.9.1-py2.7.egg/burrito/util.py", line 201, in __init__
  File "/home/jaureguir/conda-envs/qiime/lib/python2.7/site-packages/burrito-0.9.1-py2.7.egg/burrito/util.py", line 468, in _error_on_missing_application
burrito.util.ApplicationNotFoundError: Cannot find formatdb. Is it installed? Is it in your path?

**Comment by kalefranz** [comment]
That package isn't in `defaults`.  Without more information, there's no way of telling from your report where you got it from.  You'll have to file a report with the package maintainer.  This issue tracker is about changes to conda's own code.
