### ISSUE TITLE
"conda skeleton pypi" is failing with "xml.parsers.expat.ExpatError: no element found: line 1, column 0"

### ISSUE THREAD

**Issue by tadeu** [conda/conda#636]
I'm trying to create a package for IPython 2.0 on a freshly installed `conda 3.3.2 py27_0` with `conda-build 1.3.1 py27_0`. I also have `anaconda 1.9.1 np18py27_0` loaded in an environment.

The command `conda skeleton pypi ipython` fails with the following traceback:

```
Traceback (most recent call last):
  File "D:\Miniconda\Scripts\conda-skeleton-script.py", line 4, in <module>
    sys.exit(main())
  File "D:\Miniconda\lib\site-packages\conda_build\main_skeleton.py", line 124, in main
    args.func(args, p)
  File "D:\Miniconda\lib\site-packages\conda_build\main_skeleton.py", line 135, in execute
    pypi.main(args, parser)
  File "D:\Miniconda\lib\site-packages\conda_build\pypi.py", line 200, in main
    versions = client.package_releases(package)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "D:\Miniconda\lib\xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1297, in single_request
    return self.parse_response(response)
  File "D:\Miniconda\lib\xmlrpclib.py", line 1471, in parse_response
    p.close()
  File "D:\Miniconda\lib\xmlrpclib.py", line 560, in close
    self._parser.Parse("", 1) # end of data
xml.parsers.expat.ExpatError: no element found: line 1, column 0
```

I'm also not able to use `conda --debug skeleton pypi ipython`, with the following error message:

```
usage: conda-skeleton-script.py [-h] {pypi,cpan} ...
conda-skeleton-script.py: error: argument repo: invalid choice: 'skeleton' (choose from u'pypi', u'cpan')
```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#1978
