### ISSUE TITLE
Unexpected error when creating env on multi-users system

### ISSUE THREAD

**Issue by julozi** [conda/conda#6362]
conda is crashing when creating a conda environment from a user account on a multi-users system.

In my understanding, conda should use a cache folder in user's homedir ~/.conda because /shared/software/miniconda3/pkgs/cache is not writable... But for some unexplained reason this is not happening.

```
Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /shared/software/miniconda3  (read only)
    default environment : /shared/software/miniconda3
       envs directories : /shared/home/julien/.conda/envs
                          /shared/software/miniconda3/envs
          package cache : /shared/software/miniconda3/pkgs
                          /shared/home/julien/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Linux/4.9.0-3-amd64 debian/9.1 glibc/2.24
                UID:GID : 1519:3506

`$ /shared/software/miniconda3/bin/conda create -n test`




    Traceback (most recent call last):
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/shared/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 469, in fetch_repodata
        with open(cache_path, 'w') as fo:
    FileNotFoundError: [Errno 2] No such file or directory: '/shared/software/miniconda3/pkgs/cache/db552c1e.json'
```

**Comment by kalefranz** [comment]
This is happening because the file

    /shared/software/miniconda3/pkgs/urls.txt

is writable, e.g. with `open('/shared/software/miniconda3/pkgs/urls.txt', 'a').close()`, but your user is unable to create the directory `/shared/software/miniconda3/pkgs/cache`.  Probably need to check permissions on that folder.

**Comment by kalefranz** [comment]
Also, code has been reworked in conda 4.4, so `conda update conda`.
