### ISSUE TITLE
anaconda navigator are not working on Mac OS  high Sierra

### ISSUE THREAD

**Issue by sravanthbaratam** [conda/conda#6374]
$ anaconda-navigator 

Traceback (most recent call last):
  File "/Users/sravanthbaratam/anaconda3/bin/anaconda-navigator", line 11, in <module>
    sys.exit(main())
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/app/main.py", line 125, in main
    from anaconda_navigator.utils.logs import clean_logs
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/utils/logs.py", line 18, in <module>
    from anaconda_navigator.config import (LOG_FILENAME, LOG_FOLDER,
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/__init__.py", line 24, in <module>
    from anaconda_navigator.config.main import CONF
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/main.py", line 67, in <module>
    raw_mode=True,
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 221, in __init__
    self.load_from_ini()
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/anaconda_navigator/config/user.py", line 279, in load_from_ini
    self.read(self.filename(), encoding='utf-8')
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 0: invalid start byte
$

**Comment by sravanthbaratam** [comment]
for `conda`

$ conda
Traceback (most recent call last):
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 103, in _main
    from ..base.context import context
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/reader.py", line 98, in __init__
    self.determine_encoding()
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/reader.py", line 138, in determine_encoding
    self.update_raw()
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/reader.py", line 200, in update_raw
    data = self.stream.read(size)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sravanthbaratam/anaconda3/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 579, in print_unexpected_error_message
    from .base.context import context
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/conda/common/yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/reader.py", line 98, in __init__
    self.determine_encoding()
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/reader.py", line 138, in determine_encoding
    self.update_raw()
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/site-packages/ruamel_yaml/reader.py", line 200, in update_raw
    data = self.stream.read(size)
  File "/Users/sravanthbaratam/anaconda3/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
$

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#8663
