### ISSUE TITLE
An unexpected error has occurred

### ISSUE THREAD

**Issue by Phuripan2406** [conda/conda#6384]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/bung/anaconda3  (writable)
    default environment : /Users/bung/anaconda3/envs/env_salvus
       envs directories : /Users/bung/anaconda3/envs
                          /Users/bung/.conda/envs
          package cache : /Users/bung/anaconda3/pkgs
                          /Users/bung/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/bung/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Darwin/17.2.0 OSX/10.13.1    
                UID:GID : 501:20

`$ /Users/bung/anaconda3/envs/env_salvus/bin/conda install pip h5netcdf pytest flake8 obspy pyyaml jsonschema pytest-mpl`

    Traceback (most recent call last):
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 826, in execute_actions
        plan = plan_from_actions(actions, index)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 338, in plan_from_actions
        plan = inject_UNLINKLINKTRANSACTION(plan, index, prefix)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 302, in inject_UNLINKLINKTRANSACTION
        pfe.prepare()
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 467, in prepare
        for dist in self.link_dists)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 467, in <genexpr>
        for dist in self.link_dists)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 403, in make_actions_for_dist
        key=lambda pce: pce and pce.is_fetched and pce.tarball_matches_md5_if(md5)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/collection.py", line 88, in first
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/collection.py", line 88, in <genexpr>
        return next((apply(x) for x in seq if key(x)), default() if callable(default) else default)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 403, in <lambda>
        key=lambda pce: pce and pce.is_fetched and pce.tarball_matches_md5_if(md5)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 104, in tarball_matches_md5_if
        return not md5sum or self.md5sum == md5sum
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 112, in md5sum
        return self._calculate_md5sum() if self.is_fetched else None
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/decorators.py", line 137, in _wrapper
        result = method(self, *args, **kwargs)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 120, in _calculate_md5sum
        return compute_md5sum(self.package_tarball_full_path)
      File "/Users/bung/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 63, in compute_md5sum
        for chunk in iter(partial(fh.read, 8192), b''):
    OSError: [Errno 5] Input/output error

**Comment by kalefranz** [comment]
Just an intermittent IO error I think.
