### ISSUE TITLE
conda index error (4.3.30)

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#6397]
I'm trying to mirror packages in an internal repo for use in an offline install. This has worked for years but today when trying to create a clean repository the `conda index` command failed with the below error:
```
<snip>
updating: zlib-1.2.11-vc14_0.tar.bz2
Traceback (most recent call last):
  File "C:\Miniconda3\Scripts\conda-index-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_index.py", line 75, in main
    return execute(sys.argv[1:])
  File "C:\Miniconda3\lib\site-packages\conda_build\cli\main_index.py", line 71, in execute
    channel_name=args.channel_name)
  File "C:\Miniconda3\lib\site-packages\conda_build\api.py", line 367, in update_index
    locking=config.locking, timeout=config.timeout, channel_name=channel_name)
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 147, in update_index
    channel_name)
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 246, in update_subdir_index
    json.dump(recipe, fo, indent=2, sort_keys=True)
  File "C:\Miniconda3\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Miniconda3\lib\json\encoder.py", line 430, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "C:\Miniconda3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Miniconda3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Miniconda3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\Miniconda3\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\Miniconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'method' is not JSON serializable
```

This final fatal error was preceeded by a few WARNINGs which are shown below:
```
Error extracting info/paths.json in \\stanwell.com\delivery\TradingAnalytics\PackageRepository\conda\external\win-64\bz2file-0.98-py36_0.tar.bz2: KeyError("filename 'info/paths.json' not found",)
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 306, in _read_index_tar
    paths_json = json.loads(t.extractfile('info/paths.json').read().decode('utf-8'))
  File "C:\Miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Miniconda3\lib\tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/paths.json' not found"
WARNING:conda_build.index:Error extracting info/paths.json in \\stanwell.com\delivery\TradingAnalytics\PackageRepository\conda\external\win-64\bz2file-0.98-py36_0.tar.bz2: KeyError("filename 'info/paths.json' not found",)
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 306, in _read_index_tar
    paths_json = json.loads(t.extractfile('info/paths.json').read().decode('utf-8'))
  File "C:\Miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Miniconda3\lib\tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/paths.json' not found"
Error extracting info/recipe/meta.yaml in \\stanwell.com\delivery\TradingAnalytics\PackageRepository\conda\external\win-64\bz2file-0.98-py36_0.tar.bz2: KeyError("filename 'info/recipe/meta.yaml' not found",)
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 313, in _read_index_tar
    t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
  File "C:\Miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Miniconda3\lib\tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/recipe/meta.yaml' not found"
WARNING:conda_build.index:Error extracting info/recipe/meta.yaml in \\stanwell.com\delivery\TradingAnalytics\PackageRepository\conda\external\win-64\bz2file-0.98-py36_0.tar.bz2: KeyError("filename 'info/recipe/meta.yaml' not found",)
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 313, in _read_index_tar
    t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
  File "C:\Miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Miniconda3\lib\tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/recipe/meta.yaml' not found"
Error extracting info/about.json in \\stanwell.com\delivery\TradingAnalytics\PackageRepository\conda\external\win-64\sqlite-3.13.0-vc14_0.tar.bz2: KeyError("filename 'info/about.json' not found",)
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 300, in _read_index_tar
    about_json = json.loads(t.extractfile('info/about.json').read().decode('utf-8'))
  File "C:\Miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Miniconda3\lib\tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/about.json' not found"
WARNING:conda_build.index:Error extracting info/about.json in \\stanwell.com\delivery\TradingAnalytics\PackageRepository\conda\external\win-64\sqlite-3.13.0-vc14_0.tar.bz2: KeyError("filename 'info/about.json' not found",)
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 300, in _read_index_tar
    about_json = json.loads(t.extractfile('info/about.json').read().decode('utf-8'))
  File "C:\Miniconda3\lib\tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "C:\Miniconda3\lib\tarfile.py", line 1749, in getmember
    raise KeyError("filename %r not found" % name)
KeyError: "filename 'info/about.json' not found"
```

**Comment by kalefranz** [comment]
This is conda-build, but I’m who introduced the issue. I’ll have a PR to conda-build soon.

**Comment by dhirschfeld** [comment]
Great, thanks! In case its' useful (and since I've already done it) I monkey-patched `encoder.py` to provide a bit more context:
```
TypeError: Object is not JSON serializable
type(o) = <class 'method'>
repr(o) = <bound method Environment.package_specs of <conda_build.environ.Environment object at 0x0000000006E460F0>>
```

**Comment by dhirschfeld** [comment]
```
conda                     4.3.30           py36h7e176b0_0
conda-build               3.0.30           py36he296fd2_0
```

**Comment by kalefranz** [comment]
So all the 

    KeyError: "filename 'info/paths.json' not found"

messages are just fluff.  I've got a PR I'm about to push to silence those.

However, for

```
  File "C:\Miniconda3\lib\site-packages\conda_build\index.py", line 246, in update_subdir_index
    json.dump(recipe, fo, indent=2, sort_keys=True)
```

I'm not seeing how we're possibly getting anything stuck in `recipe` that's a problem :(

**Comment by kalefranz** [comment]
Wait, maybe I do.

```python
recipe_text = t.extractfile('info/recipe/meta.yaml').read().decode('utf-8')
recipe_json = yaml.load(recipe_text)
```

Can you identify a specific meta.yaml file this might be getting hung up with?  Yaml can get pretty crazy if you start using some of the more advanced features.  Something might be sneaking in that way.

**Comment by dhirschfeld** [comment]
Will try to have a look this weekend...

**Comment by eddy-ojb** [comment]
I second this problem. I am getting the same error. Has there been any progress? I am new to this process. Can I just roll back a version to sort this out?

**Comment by dhirschfeld** [comment]
@eddy-ojb - what version of conda do you have (post the result of `conda info` to your above message)

**Comment by JoeHartshorn** [comment]
I'm getting the same error too, with the [mro-basics-3.4.3-0.tar.gz](https://repo.continuum.io/pkgs/r/win-64/) file from the official R channel.

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2776
