### ISSUE TITLE
Error while updating conda after fresh installed

### ISSUE THREAD

**Issue by adityamahesa** [conda/conda#6398]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\adityamahesa\AppData\Local\conda\conda\envs
                          C:\Users\adityamahesa\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\adityamahesa\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7
Windows/6.1.7601
          administrator : True

`$ C:\ProgramData\Anaconda2\Scripts\conda update conda`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", lin
e 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line
140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_update.py"
, line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", li
ne 160, in install
        linked_dists = install_linked(prefix)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\linked_data.py
", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\linked_data.py
", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\linked_data.py
", line 36, in load_linked_data
        rec = json.load(fi)
      File "C:\ProgramData\Anaconda2\lib\json\__init__.py", line 291, in load
        **kw)
      File "C:\ProgramData\Anaconda2\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\ProgramData\Anaconda2\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\ProgramData\Anaconda2\lib\json\decoder.py", line 382, in raw_deco
de
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\adityamahesa\AppData\Local\conda\conda\envs
                          C:\Users\adityamahesa\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\adityamahesa\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7
Windows/6.1.7601
          administrator : True

`$ C:\ProgramData\Anaconda2\Scripts\conda update conda`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", lin
e 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line
140, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_update.py"
, line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", li
ne 160, in install
        linked_dists = install_linked(prefix)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\linked_data.py
", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\linked_data.py
", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\linked_data.py
", line 36, in load_linked_data
        rec = json.load(fi)
      File "C:\ProgramData\Anaconda2\lib\json\__init__.py", line 291, in load
        **kw)
      File "C:\ProgramData\Anaconda2\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\ProgramData\Anaconda2\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\ProgramData\Anaconda2\lib\json\decoder.py", line 382, in raw_deco
de
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

**Comment by kalefranz** [comment]
See https://github.com/conda/conda/issues/6418 or one of the other linked issues.
