### ISSUE TITLE
 module 'cryptography.hazmat.primitives.interfaces' has no attribute 'MACContext'

### ISSUE THREAD

**Issue by venkateshwara-gopisetti** [conda/conda#6404]
Unfortunately this error has been popping up since a few days ago. I have no idea how it has happened nor am I able to understand what is it. Should i reinstall everything?
`
Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "E:\anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "E:\anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "E:\anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "E:\anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "E:\anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "E:\anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "E:\anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 48, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "E:\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "E:\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 24, in <module>
    from cryptography.hazmat.backends.openssl.cmac import _CMACContext
  File "E:\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\cmac.py", line 16, in <module>
    @utils.register_interface(interfaces.MACContext)
AttributeError: module 'cryptography.hazmat.primitives.interfaces' has no attribute 'MACContext'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "E:\anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "E:\anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "E:\anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "E:\anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "E:\anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "E:\anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "E:\anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 48, in <module>
    from cryptography.hazmat.backends.openssl import backend as openssl_backend
  File "E:\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\__init__.py", line 7, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "E:\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\backend.py", line 24, in <module>
    from cryptography.hazmat.backends.openssl.cmac import _CMACContext
  File "E:\anaconda3\lib\site-packages\cryptography\hazmat\backends\openssl\cmac.py", line 16, in <module>
    @utils.register_interface(interfaces.MACContext)
AttributeError: module 'cryptography.hazmat.primitives.interfaces' has no attribute 'MACContext'`

**Comment by venkateshwara-gopisetti** [comment]
reinstalling cryptography apparently solved it.
