### ISSUE TITLE
 bioconda gemini install error

### ISSUE THREAD

**Issue by PatrickJReed** [conda/conda#6408]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/preed/anaconda  (writable)
    default environment : /home/preed/anaconda
       envs directories : /home/preed/anaconda/envs
                          /root/.conda/envs
          package cache : /home/preed/anaconda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.11 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-514.21.1.el7.x86_64 CentOS Linux/7.3.1611 glibc/2.17
                UID:GID : 0:0

`$ /home/preed/anaconda/bin/conda install --yes -c conda-forge -c bioconda gemini`

    Traceback (most recent call last):
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 88, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/preed/anaconda/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.

Traceback (most recent call last):
  File "gemini_install.py.1", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py.1", line 83, in main
    gemini = install_conda_pkgs(anaconda, remotes, args)
  File "gemini_install.py.1", line 105, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes"] + channels + pkgs)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/preed/anaconda/bin/conda', 'install', '--yes', '-c', 'conda-forge', '-c', 'bioconda', 'gemini']' returned non-zero exit status 1

**Comment by kalefranz** [comment]
`conda update conda`
