### ISSUE TITLE
conda install: env.yml vs requirements.txt

### ISSUE THREAD

**Issue by Franyek** [conda/conda#6411]
Couple of weeks ago I started using environment yml file to install dependencies instead of  `conda install requrements.txt`. I really like that I can put every config information into one file. Here is my current env file:

````
name: regression-test
channels:
- conda-forge
- defaults
dependencies:
- python=3.4.3
- scikit-learn=0.18
- nltk=3.2.1
- nose=1.3.7
- phonenumbers=7.5.1
- beautifulsoup4=4.5.1
- flask=0.11.1
- python-levenshtein=0.12.0
- pandas=0.19.2
- flask-httpauth=3.2.1
- regex=2016.12.27
````

But today I ran into a dependency issue. I got the error message when I tried to import `jaccard_similarity_score` :
````
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\sklearn\base.py", line 12, in <module>
    from .utils.fixes import signature
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\sklearn\utils\fixes.py", line 291, in <module>
    from scipy.sparse.linalg import lsqr as sparse_lsqr
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\scipy\sparse\linalg\__init__.py", line 113, in <module>
    from .isolve import *
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <module>
    from .iterative import *
  File "C:\DEV\tools\Miniconda3.6\envs\mia-faa2\lib\site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <module>
    from . import _iterative
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
````

I spent some time on that and with my previous workflow (create an environment without any dependencies, activate and use requirement.txt to install dependencies) I had no issue.
The list of external modules and the versions were not changed.
Can someone explain me what the difference is between the 2 workflow? I would love to use environment.yml because it is more convinient and simplier.

**Comment by AnneTheAgile** [comment]
Apparently 2016 a Tox sprint considered this;
https://github.com/tox-dev/tox/blob/a1530b747d6999c4d22f6e57ace85ffa7e74e945/docs/drafts/extend-envs-and-packagebuilds.md#L27
This feature shall allow to specify how plugins can specify new types of package formats and environments to run test commands in.

**Comment by Pooja1301** [comment]
Is there anything else to do in this issue?
