### ISSUE TITLE
conda update spyder failure!!

### ISSUE THREAD

**Issue by revikiran1991** [conda/conda#6412]
I am trying to update spyder in anaconda using the following command
`conda update spyder`

and got the following error:
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.14.2
       root environment : /home/ravi/anaconda3  (writable)
    default environment : /home/ravi/anaconda3
       envs directories : /home/ravi/anaconda3/envs
                          /home/ravi/.conda/envs
          package cache : /home/ravi/anaconda3/pkgs
                          /home/ravi/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/ravi/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.5.2 Linux/4.13.0-17-generic debian/stretch/sid glibc/2.26    
                UID:GID : 1000:1000

`$ /home/ravi/anaconda3/bin/conda update spyder`

    Traceback (most recent call last):
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/home/ravi/anaconda3/pkgs/cache/6846611e.json'

I tried to update using anaconda-navigator, but a dialogue box pops up with the error:

Traceback (most recent call last):
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
return_value = func(*args, **kwargs)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
exit_code = args.func(args, p)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 80, in execute
install(args, parser, 'install')
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 231, in install
unknown=index_args['unknown'], prefix=prefix)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 101, in get_index
index = fetch_index(channel_priority_map, use_cache=use_cache)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/index.py", line 120, in fetch_index
repodatas = collect_all_repodata(use_cache, tasks)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
repodatas = _collect_repodatas_serial(use_cache, tasks)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
for url, schan, pri in tasks]
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 485, in 
for url, schan, pri in tasks]
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 115, in func
res = f(*args, **kwargs)
File "/home/ravi/anaconda3/lib/python3.5/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
with open(cache_path, 'w') as fo:
PermissionError: [Errno 13] Permission denied: '/home/ravi/anaconda3/pkgs/cache/6846611e.json'

I tried resetting the anaconda-navigator with `anaconda-navigator --reset`, but did not fix the problem.

Please fix the issue and commit.

**Comment by kalefranz** [comment]
You've probably used `sudo` with conda, which we DO NOT RECOMMEND.  To unwind this for yourself,

    sudo chown -R 1000 /home/ravi/anaconda3
