### ISSUE TITLE
Cannot remove conda environment

### ISSUE THREAD

**Issue by nick-youngblut** [conda/conda#6415]
I'm running conda v4.3.29 on a Ubuntu 16.04.3 system. I tried to remove a conda environment with `conda remove -n py3_networkD3 --all`, and I got the following error:

```
Package plan for package removal in environment /ebio/abt3_projects/software/miniconda3/envs/py3_networkD3:

The following packages will be REMOVED:

    binutils_impl_linux-64:    2.28.1-h04c84fa_2
    binutils_linux-64:         7.2.0-hc67e822_12
    bioconductor-biobase:      2.38.0-r3.4.1_0               bioconda
    bioconductor-biocgenerics: 0.24.0-r3.4.1_0               bioconda
    bioconductor-biomformat:   1.6.0-r3.4.1_0                bioconda
    bioconductor-biostrings:   2.46.0-r3.4.1_0               bioconda
    bioconductor-iranges:      2.12.0-r3.4.1_0               bioconda
    bioconductor-multtest:     2.34.0-r3.4.1_0               bioconda
    bioconductor-rhdf5:        2.22.0-r3.4.1_0               bioconda
    bioconductor-s4vectors:    0.16.0-r3.4.1_0               bioconda
    bioconductor-xvector:      0.18.0-r3.4.1_0               bioconda
    bioconductor-zlibbioc:     1.24.0-r3.4.1_0               bioconda
    blas:                      1.1-openblas                  conda-forge
    bleach:                    1.4.2-py36_0                  bioconda
    bzip2:                     1.0.6-1                       conda-forge
    ca-certificates:           2017.7.27.1-0                 conda-forge
    cairo:                     1.14.6-4                      conda-forge
    certifi:                   2017.7.27.1-py36_0            conda-forge
    curl:                      7.54.1-0                      conda-forge
    decorator:                 4.1.2-py36_0                  conda-forge
    entrypoints:               0.2.3-py36_1                  conda-forge
    fontconfig:                2.12.1-5                      conda-forge
    freetype:                  2.7-1                         conda-forge
    gcc_impl_linux-64:         7.2.0-hc5ce805_2
    gettext:                   0.19.7-1                      conda-forge
    gfortran_impl_linux-64:    7.2.0-hb3c8cce_2
    glib:                      2.51.4-0                      conda-forge
    gmp:                       6.1.2-0                       conda-forge
    graphite2:                 1.3.9-0                       conda-forge
    gsl:                       2.2.1-blas_openblas_3         conda-forge [blas_openblas]
    gxx_impl_linux-64:         7.2.0-hd3faf3d_2
    harfbuzz:                  1.4.3-0                       conda-forge
    html5lib:                  0.999999999-py36_0            conda-forge
    icu:                       58.2-0                        conda-forge
    intel-openmp:              2018.0.0-h15fc484_7
    ipykernel:                 4.6.1-py36_0                  conda-forge
    ipython:                   6.2.1-py36_0                  conda-forge
    ipython_genutils:          0.2.0-py36_0                  conda-forge
    jedi:                      0.10.2-py36_0                 conda-forge
    jinja2:                    2.9.6-py36_0                  conda-forge
    jpeg:                      9b-2                          conda-forge
    jsonschema:                2.6.0-py36_0                  conda-forge
    jupyter_client:            5.1.0-py36_0                  conda-forge
    jupyter_core:              4.4.0-py_0                    conda-forge
    krb5:                      1.14.2-0                      conda-forge
    libffi:                    3.2.1-3                       conda-forge
    libgcc:                    7.2.0-h69d50b8_2
    libgcc-ng:                 7.2.0-h7cc24e2_2
    libgfortran:               3.0.0-1
    libgfortran-ng:            7.2.0-h9f7466a_2
    libiconv:                  1.14-4                        conda-forge
    libpng:                    1.6.28-1                      conda-forge
    libsodium:                 1.0.10-0                      conda-forge
    libssh2:                   1.8.0-1                       conda-forge
    libstdcxx-ng:              7.2.0-h7a57d05_2
    libtiff:                   4.0.7-0                       conda-forge
    libxml2:                   2.9.5-0                       conda-forge
    markupsafe:                1.0-py36_0                    conda-forge
    mistune:                   0.8-py36_0                    conda-forge
    mkl:                       2018.0.0-hb491cac_4
    nb_conda:                  2.2.1-py36_0                  conda-forge
    nb_conda_kernels:          2.1.0-py36_0                  conda-forge
    nbconvert:                 5.3.1-py_1                    conda-forge
    nbformat:                  4.4.0-py36_0                  conda-forge
    ncurses:                   5.9-10                        conda-forge
    notebook:                  5.2.1-py36_2                  conda-forge
    numpy:                     1.13.3-py36_blas_openblas_200 conda-forge [blas_openblas]
    openblas:                  0.2.19-2                      conda-forge
    openssl:                   1.0.2l-0                      conda-forge
    pandas:                    0.21.0-py36_0                 conda-forge
    pandoc:                    2.0.0.1-0                     conda-forge
    pandocfilters:             1.4.1-py36_0                  conda-forge
    pango:                     1.40.4-0                      conda-forge
    pcre:                      8.39-0                        conda-forge
    pexpect:                   4.2.1-py36_0                  conda-forge
    pickleshare:               0.7.4-py36_0                  conda-forge
    pip:                       9.0.1-py36_0                  conda-forge
    pixman:                    0.34.0-0                      conda-forge
    prompt_toolkit:            1.0.15-py36_0                 conda-forge
    ptyprocess:                0.5.2-py36_0                  conda-forge
    pygments:                  2.2.0-py36_0                  conda-forge
    python:                    3.6.3-0                       conda-forge
    python-dateutil:           2.6.1-py36_0                  conda-forge
    pytz:                      2017.3-py_2                   conda-forge
    pyzmq:                     16.0.2-py36_0                 conda-forge
    r-ade4:                    1.7_8-r3.4.1_0                conda-forge
    r-ape:                     5.0-r3.4.1_0                  conda-forge
    r-assertthat:              0.1-r3.4.1_0                  conda-forge
    r-base:                    3.4.1-0                       conda-forge
    r-bh:                      1.65.0_1-r3.4.1_0             conda-forge
    r-bindr:                   0.1-r3.4.1_0                  conda-forge
    r-bindrcpp:                0.2-r3.4.1_0                  conda-forge
    r-cluster:                 2.0.6-r3.4.1_0                conda-forge
    r-codetools:               0.2_15-r3.4.1_0               conda-forge
    r-colorspace:              1.3_2-r3.4.1_0                conda-forge
    r-crayon:                  1.3.2-r3.4.1_0                conda-forge
    r-data.table:              1.10.4-r3.4.1_0               bioconda
    r-dbi:                     0.6_1-r3.4.1_0                conda-forge
    r-dichromat:               2.0_0-r3.4.1_0                conda-forge
    r-digest:                  0.6.12-r3.4.1_0               conda-forge
    r-doparallel:              1.0.10-r3.4.1_0               conda-forge
    r-dplyr:                   0.5.0-r3.3.2_1                bioconda
    r-evaluate:                0.10.1-r3.4.1_0               conda-forge
    r-foreach:                 1.4.3-r3.4.1_0                conda-forge
    r-ggplot2:                 2.2.1-r3.4.1_0                conda-forge
    r-glue:                    1.1.1-r3.4.1_0                conda-forge
    r-gridbase:                0.4_7-r3.4.1_0                conda-forge
    r-gtable:                  0.2.0-r3.4.1_0                conda-forge
    r-htmltools:               0.3.6-r3.4.1_0                conda-forge
    r-htmlwidgets:             0.9-r3.4.1_0                  conda-forge
    r-igraph:                  1.0.1-r3.4.1_0                conda-forge
    r-irdisplay:               0.4.4-r3.4.1_0                conda-forge
    r-irkernel:                0.8.11-r3.4.1_0               conda-forge
    r-irlba:                   2.1.2-r3.4.1_0                conda-forge
    r-iterators:               1.0.8-r3.4.1_0                conda-forge
    r-jsonlite:                1.4-r3.4.1_0                  conda-forge
    r-labeling:                0.3-r3.4.1_0                  conda-forge
    r-lattice:                 0.20_34-r3.4.1_0              conda-forge
    r-lazyeval:                0.2.0-r3.4.1_0                conda-forge
    r-magrittr:                1.5-r3.4.1_0                  conda-forge
    r-mass:                    7.3_45-r3.4.1_0               conda-forge
    r-matrix:                  1.2_7.1-r3.4.1_0              conda-forge
    r-mgcv:                    1.8_17-r3.4.1_0               conda-forge
    r-munsell:                 0.4.3-r3.4.1_0                conda-forge
    r-networkd3:               0.4-r3.4.1_0                  conda-forge
    r-nlme:                    3.1_131-r3.4.1_0              conda-forge
    r-nmf:                     0.20.6-r3.4.1_0               conda-forge
    r-pbdzmq:                  0.2_4-r3.4.1_0                conda-forge
    r-permute:                 0.9_4-0                       conda-forge
    r-pkgconfig:               2.0.1-r3.4.1_0                conda-forge
    r-pkgmaker:                0.22-r3.4.1_0                 conda-forge
    r-plogr:                   0.1_1-r3.4.1_0                conda-forge
    r-plyr:                    1.8.4-r3.4.1_0                conda-forge
    r-r6:                      2.2.0-r3.4.1_0                conda-forge
    r-rcolorbrewer:            1.1_2-r3.4.1_0                conda-forge
    r-rcpp:                    0.12.13-r3.4.1_0              conda-forge
    r-registry:                0.3-r3.4.1_0                  conda-forge
    r-repr:                    0.10-r3.4.1_0                 conda-forge
    r-reshape2:                1.4.2-r3.4.1_0                conda-forge
    r-rlang:                   0.1.2-r3.4.1_0                conda-forge
    r-rngtools:                1.2.4-r3.4.1_0                conda-forge
    r-scales:                  0.4.1-r3.4.1_0                conda-forge
    r-stringi:                 1.1.2-r3.4.1_0                conda-forge
    r-stringr:                 1.2.0-r3.4.1_0                conda-forge
    r-survival:                2.40_1-r3.4.1_0               conda-forge
    r-tibble:                  1.3.3-r3.4.1_0                conda-forge
    r-tidyr:                   0.6.1-r3.4.1_0                conda-forge
    r-uuid:                    0.1_2-r3.4.1_0                conda-forge
    r-vegan:                   2.4_3-r3.4.1_0                conda-forge
    r-xtable:                  1.8_2-r3.4.1_0                conda-forge
    r-yaml:                    2.1.14-r3.4.1_0               conda-forge
    readline:                  6.2-0                         conda-forge
    rpy2:                      2.8.5-py36r3.4.1_0            conda-forge
    setuptools:                36.6.0-py36_1                 conda-forge
    simplegeneric:             0.8.1-py36_0                  conda-forge
    singledispatch:            3.4.0.3-py36_0                conda-forge
    six:                       1.11.0-py36_1                 conda-forge
    sqlite:                    3.13.0-1                      conda-forge
    terminado:                 0.6-py36_0                    conda-forge
    testpath:                  0.3.1-py36_0                  conda-forge
    tk:                        8.5.19-2                      conda-forge
    tornado:                   4.5.2-py36_0                  conda-forge
    traitlets:                 4.3.2-py36_0                  conda-forge
    wcwidth:                   0.1.7-py36_0                  conda-forge
    webencodings:              0.5-py36_0                    conda-forge
    wheel:                     0.30.0-py_1                   conda-forge
    xz:                        5.2.3-0                       conda-forge
    zeromq:                    4.1.5-0                       conda-forge
    zlib:                      1.2.8-3                       conda-forge

Proceed ([y]/n)?

+ /ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/bin/jupyter-nbextension disable nb_conda --py --sys-prefix
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/bin/jupyter-nbextension", line 4, in <module>
    import notebook.nbextensions
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core.paths'
+ /ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/bin/jupyter-serverextension disable nb_conda --py --sys-prefix
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/bin/jupyter-serverextension", line 4, in <module>
    import notebook.serverextensions
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/notebook/__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/notebook/nbextensions.py", line 23, in <module>
    from jupyter_core.paths import (
ModuleNotFoundError: No module named 'jupyter_core.paths'

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::nb_conda-2.2.1-py36_0
consider notifying the package maintainer
+ /ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/bin/python -m nb_conda_kernels.install --disable --prefix=/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/nb_conda_kernels/__init__.py", line 3, in <module>
    from .manager import CondaKernelSpecManager
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/nb_conda_kernels/manager.py", line 9, in <module>
    from traitlets import Unicode
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/traitlets/traitlets.py", line 60, in <module>
    from .utils.importstring import import_item
  File "/ebio/abt3_projects/software/miniconda3/envs/py3_networkD3/lib/python3.6/site-packages/traitlets/utils/importstring.py", line 8, in <module>
    from ipython_genutils.py3compat import cast_bytes_py2
ModuleNotFoundError: No module named 'ipython_genutils.py3compat'

WARNING conda.core.link:run_script(516): pre-unlink script failed for package conda-forge::nb_conda_kernels-2.1.0-py36_0
consider notifying the package maintainer
```

The conda environment still appears in the environment list in `conda info -e`, and I can't create a new conda environment with that same name. 

The error may be due to having a Jupyter kernel running that used that conda environment (I forgot that it was running). 

How do I completely remove this environment? Running `conda remove -n py3_networkD3 --all` won't remove the environment.

**Comment by kalefranz** [comment]
I'd just use `rm -rf` ¯\\\_(ツ)\_/¯
