### ISSUE TITLE
OSError: [Errno 28] No space left on device [Does this mean that I need to increase my instance size ?]

### ISSUE THREAD

**Issue by jhasuman** [conda/conda#6416]
/home/suman/miniconda3/bin/conda-env create -f environment-gpu.yml`

    **OSError: [Errno 28] No space left on device**

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/exceptions.                                                                                        py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda_env/cli/mai                                                                                        n_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda_env/install                                                                                        ers/conda.py", line 29, in install
        prefix=prefix)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/index.                                                                                        py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/index.                                                                                        py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/repoda                                                                                        ta.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/repoda                                                                                        ta.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/repoda                                                                                        ta.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/repoda                                                                                        ta.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/suman/miniconda3/lib/python3.6/site-packages/conda/core/repoda                                                                                        ta.py", line 474, in fetch_repodata
        json.dump(repodata, fo, indent=2, sort_keys=True, cls=EntityEncoder)
    **OSError: [Errno 28] No space left on device**

**Comment by kalefranz** [comment]
Yes.
