### ISSUE TITLE
TypeError: send() got an unexpected keyword argument 'timeout'. Every time running conda install

### ISSUE THREAD

**Issue by cjer** [conda/conda#6420]
Hey, every time I run conda install I get the same TypeError.

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\Users\USER\Anaconda3  (writable)
    default environment : C:\Users\USER\Anaconda3
       envs directories : C:\Users\USER\Anaconda3\envs
                          C:\Users\USER\AppData\Local\conda\conda\envs
                          C:\Users\USER\.conda\envs
          package cache : C:\Users\USER\Anaconda3\pkgs
                          C:\Users\USER\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.16299
          administrator : False

`$ C:\Users\USER\Anaconda3\Scripts\conda install altair --channel conda-forge`

    Traceback (most recent call last):
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\cli\install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Users\USER\Anaconda3\lib\site-packages\conda\core\repodata.py", line 144, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\Users\USER\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\Users\USER\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
    TypeError: send() got an unexpected keyword argument 'timeout'

**Comment by kalefranz** [comment]
Do you have something monkey-patching requests?
