### ISSUE TITLE
Error: conda install jupyter

### ISSUE THREAD

**Issue by yogeshluthra** [conda/conda#6422]
I am getting following error when installing jupyter on MacOS.

Used following command:
**conda install jupyter**

**ERROR details:**

Current conda install:

               platform : osx-64
          conda version : 4.3.11
       conda is private : False
      conda-env version : 4.3.11
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /Users/yogeshluthra/miniconda2  (writable)
    default environment : /Users/yogeshluthra/miniconda2/envs/pytorch
       envs directories : /Users/yogeshluthra/miniconda2/envs
                          /Users/yogeshluthra/.conda/envs
          package cache : /Users/yogeshluthra/miniconda2/pkgs
                          /Users/yogeshluthra/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/yogeshluthra/.condarc
           offline mode : False
             user-agent : conda/4.3.11 requests/2.13.0 CPython/2.7.13 Darwin/17.2.0 OSX/10.13.1
                UID:GID : 501:20

`$ /Users/yogeshluthra/miniconda2/envs/pytorch/bin/conda install jupyter`

    Traceback (most recent call last):
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 616, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 825, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 88, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 150, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/yogeshluthra/miniconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.

**Comment by kalefranz** [comment]
`conda update conda`
