### ISSUE TITLE
conda develop . broken? python 3.5 vs 3.6 problem?

### ISSUE THREAD

**Issue by BjornFJohansson** [conda/conda#6425]
I use `conda develop .` a lot to install packages in editable mode. I think that conda develop tries to put a conda.pth file in /home/bjorn/anaconda3/envs/bjorn35/lib/python3.6/site-packages/. This directory does not exist since the env is python 3.5. I experimented to create python3.6/site-packages/  manually and this makes the conda develop . command complete without errors and creates a conda.pth. However, the installation does not work. If I then manually copy the new conda.pth to /home/bjorn/anaconda3/envs/bjorn35/lib/python3.5/site-packages/ the installation works. 

The python version in my root is 3.6 while it is 3.5 in the bjorn35 env.  

```
(bjorn35) bjorn@bjorn-ThinkPad-T450s:~/python_packages$ cd pydna
(bjorn35) bjorn@bjorn-ThinkPad-T450s:~/python_packages/pydna$ conda develop .
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/bin/conda-develop", line 11, in <module>
    sys.exit(main())
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_develop.py", line 72, in main
    return execute(sys.argv[1:])
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_develop.py", line 68, in execute
    build_ext=args.build_ext, clean=args.clean, uninstall=args.uninstall)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 273, in develop
    return execute(recipe_dir, prefix, no_pth_file, build_ext, clean, uninstall)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/conda_build/develop.py", line 175, in execute
    write_to_conda_pth(sp_dir, pkg_path)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/conda_build/develop.py", line 50, in write_to_conda_pth
    with open(c_file, 'a') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/bjorn/anaconda3/envs/bjorn35/lib/python3.6/site-packages/conda.pth'
(bjorn35) bjorn@bjorn-ThinkPad-T450s:~/python_packages/pydna$ root
(root) bjorn@bjorn-ThinkPad-T450s:~/python_packages/pydna$ conda update conda
Fetching package metadata .................
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /home/bjorn/anaconda3:
#
conda                     4.3.30           py36h5d9f9f4_0    defaults
(root) bjorn@bjorn-ThinkPad-T450s:~$ python --version
Python 3.6.3 :: Anaconda, Inc.
(root) bjorn@bjorn-ThinkPad-T450s:~/python_packages/pydna$ source activate bjorn35
(bjorn35) bjorn@bjorn-ThinkPad-T450s:~$ python --version
Python 3.5.4 :: Anaconda, Inc.

```

**Comment by kalefranz** [comment]
This issue was moved to conda/conda-build#2633
