### ISSUE TITLE
An unexpected error has occurred, when I opened anaconda prompt

### ISSUE THREAD

**Issue by kker43** [conda/conda#6426]
Traceback (most recent call last):
  File "d:\...\Continuum\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "d:\...\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "d:\...\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "d:\...\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "d:\...\Continuum\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "d:\...\Continuum\Anaconda2\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "d:\...\Continuum\Anaconda2\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "d:\...\Continuum\Anaconda2\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "d:\...\Continuum\Anaconda2\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "d:\...\Continuum\Anaconda2\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "d:\...\Continuum\Anaconda2\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "d:\...\Continuum\Anaconda2\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "d:\...\Continuum\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "d:\...\Continuum\Anaconda2\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "d:\...\Continuum\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "d:\...\Continuum\Anaconda2\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "d:\...\Continuum\Anaconda2\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1: ordinal not in range(128)

my system is windows10, how can I fix this? thanks

**Comment by kker43** [comment]
I had fix this. the problem because of  my system environment path, the path about mySQL is incomplete, so I delete the path, the question is solved
