### ISSUE TITLE
Fail to clone the conda environment statsmodels-0.8.0-np112py35_0.tar.bz2

### ISSUE THREAD

**Issue by remoteblue** [conda/conda#6427]
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/cocadas/miniconda3  (writable)
    default environment : /home/cocadas/miniconda3/envs/carnd-term1-gpu
       envs directories : /home/cocadas/miniconda3/envs
          package cache : /home/cocadas/miniconda3/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/menpo/linux-64
                          https://conda.anaconda.org/menpo/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/cocadas/.condarc
           offline mode : False

`$ /home/cocadas/miniconda3/envs/carnd-term1-gpu/bin/conda create --name tensorflow --clone carnd-term1-gpu`

    Traceback (most recent call last):
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/fetch.py", line 395, in download
        resp.raise_for_status()
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/requests/models.py", line 893, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/conda-forge/linux-64/statsmodels-0.8.0-np112py35_0.tar.bz2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 228, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 90, in clone
        index_args=index_args)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/misc.py", line 388, in clone_env
        force_extract=False, index_args=index_args)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/misc.py", line 188, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/home/cocadas/miniconda3/lib/python3.6/site-packages/conda/fetch.py", line 399, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/conda-forge/linux-64/statsmodels-0.8.0-np112py35_0.tar.bz2: https://conda.anaconda.org/conda-forge/linux-64/statsmodels-0.8.0-np112py35_0.tar.bz2

**Comment by kalefranz** [comment]
Conda 4.2 is no longer supported.  `conda update conda`
