### ISSUE TITLE
conda 4.3.27: UnicodeDecodeError: invalid continuation byte when installing packages

### ISSUE THREAD

**Issue by ethanmoffat** [conda/conda#6450]
In conda 4.3.27 on Windows, `conda install` fails with an error: 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 51: invalid continuation byte`

This occurs under the following preconditions:
1. The username contains non-standard characters
2. The non-standard character has characters following it
3. conda is installed in a directory under the user folder (for instance, %LOCALAPPDATA%)

I have also confirmed that this bug does not exist in conda 4.2.12.

Full output (personally identifiable information scrubbed):
```log
  
     https://github.com/conda/conda/issues
 
 
 
 Current conda install:
 
                platform : win-64
           conda version : 4.3.27
        conda is private : False
       conda-env version : 4.3.27
     conda-build version : not installed
          python version : 3.5.2.final.0
        requests version : 2.11.1
        root environment : C:\Users\{redacted}\AppData\Local\amlworkbench\Python  (writable)
     default environment : C:\Users\{redacted}\AppData\Local\amlworkbench\Python
        envs directories : C:\Users\{redacted}\AppData\Local\amlworkbench\Python\envs
                           C:\Users\{redacted}\AppData\Local\conda\conda\envs
                           C:\Users\{redacted}\.conda\envs
           package cache : C:\Users\{redacted}\AppData\Local\amlworkbench\Python\pkgs
                           C:\Users\{redacted}\AppData\Local\conda\conda\pkgs
            channel URLs : https://repo.continuum.io/pkgs/main/win-64  (offline)
                           https://repo.continuum.io/pkgs/main/noarch  (offline)
                           https://repo.continuum.io/pkgs/free/win-64  (offline)
                           https://repo.continuum.io/pkgs/free/noarch  (offline)
                           https://repo.continuum.io/pkgs/r/win-64  (offline)
                           https://repo.continuum.io/pkgs/r/noarch  (offline)
                           https://repo.continuum.io/pkgs/pro/win-64  (offline)
                           https://repo.continuum.io/pkgs/pro/noarch  (offline)
                           https://repo.continuum.io/pkgs/msys2/win-64  (offline)
                           https://repo.continuum.io/pkgs/msys2/noarch  (offline)
             config file : C:\Users\{redacted}\.condarc
              netrc file : None
            offline mode : True
              user-agent : conda/4.3.27 requests/2.11.1 CPython/3.5.2 Windows/10 Windows/10.0.16299    
           administrator : False
 
 `$ C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\__main__.py install --no-deps --offline --yes --force C:\Users\{redacted}\AppData\Local\Temp\AmlInstaller\ca-certificates.windows-2017.11.5\ca-certificates-2017.11.5-0.tar.bz2`
 
 
 
 
     Traceback (most recent call last):
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
         return_value = func(*args, **kwargs)
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\cli\main.py", line 140, in _main
         exit_code = args.func(args, p)
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\cli\main_install.py", line 80, in execute
         install(args, parser, 'install')
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\cli\install.py", line 210, in install
         explicit(args_packages, prefix, verbose=not context.quiet)
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\misc.py", line 110, in explicit
         execute_actions(actions, index, verbose=verbose)
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\plan.py", line 829, in execute_actions
         with History(actions[PREFIX]):
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\history.py", line 72, in __enter__
         self.update('enter')
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\history.py", line 93, in update
         last = set(self.get_state())
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\history.py", line 192, in get_state
         states = self.construct_states()
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\history.py", line 172, in construct_states
         for dt, cont, unused_com in self.parse():
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\site-packages\conda\history.py", line 122, in parse
         lines = f.read().splitlines()
       File "C:\Users\{redacted}\AppData\Local\amlworkbench\Python\lib\codecs.py", line 321, in decode
         (result, consumed) = self._buffer_decode(data, self.errors, final)
     UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 51: invalid continuation byte
 ```

**Comment by kalefranz** [comment]
Have confirmed that `conda/history.py` is using `open` from `conda.common.compat` in conda 4.4.
