### ISSUE TITLE
conda 4.4 rc2: failure in conda list when editable install has been moved

### ISSUE THREAD

**Issue by jorisvandenbossche** [conda/conda#6466]
`conda list` for my root environment is working nicely using conda 4.3, but when upgrading with canary to conda 4.4.0 rc2, the `conda list` command fails with the following error:

```
joris@joris-XPS-13-9350:~/scipy$ conda list
# packages in environment at /home/joris/miniconda3:
#

`$ /home/joris/miniconda3/bin/conda list`

    Traceback (most recent call last):
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 683, in __call__
        return func(*args, **kwargs)
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 75, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 150, in execute
        show_channel_urls=context.show_channel_urls)
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 85, in print_packages
        other_python = get_egg_info(prefix)
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/egg_info.py", line 86, in get_egg_info
        for path in get_egg_info_files(join(prefix, sp_dir)):
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/egg_info.py", line 35, in get_egg_info_files
        for egg in get_egg_info_files(reader.readline().strip()):
      File "/home/joris/miniconda3/lib/python3.5/site-packages/conda/egg_info.py", line 32, in get_egg_info_files
        for fn in os.listdir(sp_dir):
    FileNotFoundError: [Errno 2] No such file or directory: '/home/joris/scipy/dateutil'
```

The reason for this is that I once did `pip install -e .` in the  '/home/joris/scipy/dateutil' directory to test out a dev install of dateutil. But later I removed it. Until now it was not a problem, but so now it is starting to give problems with conda 4.4. 
I know I can fix this by removing it manually from easy-install.pth, but IMO it could be handles more gracefully by conda.

**Comment by DavidMertz** [comment]
I *can* activate a "hidden" environment, but I need to do the dance of first using "source activate" one time to "prime" conda 4.4:

```bash
% conda activate projects-data-analysis
CommandNotFoundError: Error: No command 'conda activate'.

% source activate projects-data-analysis
(projects-data-analysis) % conda deactivate
% conda activate projects-data-analysis
(projects-data-analysis) %
```

**Comment by kalefranz** [comment]
@DavidMertz I don't think that comment is related to this issue, is it?

But yes, in general, without a change to how you make conda available to your shell, you'll have to do that "priming."  We're recommending a change to how the `conda` command is made available to the shell though.  Details here: https://www.anaconda.com/blog/developer-blog/how-to-get-ready-for-the-release-of-conda-4-4/
