### ISSUE TITLE
Installing downloaded package fails

### ISSUE THREAD

**Issue by Minthos** [conda/conda#6476]
I have tried installing pytorch using this command: `conda install pytorch torchvision cuda90 -c pytorch` but conda was unable to download pytorch because my connection keeps getting reset by peer (my connection sucks). I downloaded the file manually (500+ MB) and now I'm struggling to install it. I have tried running the same command with --use-local or --offline or both, but none of them work either. Here's the output from trying to install the package file directly:

~/miniconda3/pkgs$ conda install pytorch-0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/minthos/miniconda3  (writable)
    default environment : /home/minthos/miniconda3
       envs directories : /home/minthos/miniconda3/envs
                          /home/minthos/.conda/envs
          package cache : /home/minthos/miniconda3/pkgs
                          /home/minthos/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/minthos/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.10.0-42-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/minthos/miniconda3/bin/conda install pytorch-0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4.tar.bz2`

    Traceback (most recent call last):
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 210, in install
        explicit(args_packages, prefix, verbose=not context.quiet)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/misc.py", line 109, in explicit
        execute_actions(actions, index, verbose=verbose)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/core/link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 95, in read_package_info
        paths_data=paths_data,
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 831, in __setattr__
        super(ImmutableEntity, self).__setattr__(attribute, value)
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/minthos/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for url cannot be None.

**Comment by kalefranz** [comment]
Fix in https://github.com/conda/conda/pull/6754 pending merge.  Will be in a future release of conda 4.4.
