### ISSUE TITLE
An unexpected error when I open Anaconda prompt

### ISSUE THREAD

**Issue by newcoder9** [conda/conda#6478]
my system is windows10, how can I fix this? thanks

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "D:...\PythonCoding\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "D:...\PythonCoding\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "D:...\PythonCoding\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "D:...\PythonCoding\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "D:\PythonCoding\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "D:...\PythonCoding\lib\site-packages\conda\gateways\download.py", line 17, in <module>
    from ..connection import CondaSession
  File "D:...\PythonCoding\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:...\PythonCoding\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "D:...\PythonCoding\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "D:...\PythonCoding\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "D:...\PythonCoding\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "D:...\PythonCoding\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "D:...\PythonCoding\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

**Comment by kalefranz** [comment]
You've used pip or another python install method to get your root environment in an unsatisfiable state among all its dependencies.  Easiest solution now is just to start with a new Miniconda or Anaconda installer.
