### ISSUE TITLE
Navigator start up issue 

### ISSUE THREAD

**Issue by ryanxu2018** [conda/conda#6480]
Traceback (most recent call last):
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 293, in wrapper
return fun(self, *args, **kwargs)
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 356, in cmdline
return cext.proc_cmdline(self.pid)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/anaconda_navigator/app/start.py", line 113, in start_app
if misc.load_pid() is None: # A stale lock might be around
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/anaconda_navigator/utils/misc.py", line 384, in load_pid
cmds = process.cmdline()
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/psutil/__init__.py", line 701, in cmdline
return self._proc.cmdline()
File "/Users/peijiexu/anaconda/lib/python3.6/site-packages/psutil/_psosx.py", line 306, in wrapper
raise AccessDenied(self.pid, self._name)
psutil.AccessDenied: psutil.AccessDenied (pid=548)
 
I have updated the latest anaconda , still getting this issue

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#8273
