### ISSUE TITLE
Failed ipykernel 4.7.0 update

### ISSUE THREAD

**Issue by kavaldjiev** [conda/conda#6482]
Hi, 
Here is the trace log I got after trying to update to the latest ipykernel:
Seems like an issue with .ipykernel-post-link.bat.
I compared the syntax with the previous .bat, and one '"' symbol is at different location, i've no clue if this is the cause.

Thanks,
dan

==============================
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 0+unknown
         python version : 3.5.4.final.0
       requests version : 2.18.4
       root environment : C:\Anaconda3  (writable)
    default environment : C:\Anaconda3
       envs directories : C:\Anaconda3\envs
                          C:\Users\dkavaldj\AppData\Local\conda\conda\envs
                          C:\Users\dkavaldj\.conda\envs
          package cache : C:\Anaconda3\pkgs
                          C:\Users\dkavaldj\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\dkavaldj\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.5.4 Windows/7 
Windows/6.1.7601    
          administrator : True

`$ C:\Anaconda3\Scripts\conda update ipykernel -v`

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 497, in ru
n_script
        subprocess_call(command_args, env=env, path=dirname(path))
      File "C:\Anaconda3\lib\site-packages\conda\gateways\subprocess.py", line 
56, in subprocess_call
        output=_format_output(command_str, path, rc, stdout, stderr))
    subprocess.CalledProcessError: Command '['C:\\windows\\system32\\cmd.exe', 
'/d', '/c', 'C:\\Anaconda3\\Scripts\\.ipykernel-post-link.bat']' returned non-z
ero exit status 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 327, in _e
xecute_actions
        run_script(target_prefix, Dist(pkg_data), 'post-unlink' if is_unlink el
se 'post-link')
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 513, in ru
n_script
        raise LinkError(message)
    conda.exceptions.LinkError: post-link script failed for package defaults::i
pykernel-4.7.0-py35h2f9c1c0_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Anaconda3\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 281, in ex
ecute
        pkg_data, actions)
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 344, in _e
xecute_actions
        reverse_excs,
    conda.CondaMultiError: post-link script failed for package defaults::ipyker
nel-4.7.0-py35h2f9c1c0_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Anaconda3\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>
    
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in c
onda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _ma
in
        exit_code = args.func(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, 
in execute
        install(args, parser, 'update')
      File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 326, in 
install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda3\lib\site-packages\conda\plan.py", line 828, in execute
_actions
        execute_instructions(plan, index, verbose)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in
 execute_instructions
        cmd(state, arg)
      File "C:\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in
 UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 297, in ex
ecute
        rollback_excs,
    conda.CondaMultiError: post-link script failed for package defaults::ipyker
nel-4.7.0-py35h2f9c1c0_0
    running your command again with `-v` will provide additional information
    location of failed script: C:\Anaconda3\Scripts\.ipykernel-post-link.bat
    ==> script messages <==
    <None>

**Comment by josephnunn** [comment]
I'm running into this same issue with ipykernel-post-link.bat when trying to run "conda update --all".

**Comment by mambolevis** [comment]
I solved the problem in windows 10 running the following command:
`conda install ipykernel `

**Comment by appleTree2017** [comment]
I meet this problem when I tried to install python2 on Jupiter notebook while running with anaconda3, I solved the problem in these steps:

conda install -c conda-forge nb_conda_kernels
conda create -n py27 python=2.7 ipykernel
conda install ipykernel

after these three commands, I reopen my jupyter notebook and figure out that I am able to switch kernels. Hope this helps.
