### ISSUE TITLE
Unexpected Error while opening anaconda

### ISSUE THREAD

**Issue by nikhil8786** [conda/conda#6497]
Traceback (most recent call last):
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\cli\main.py", l
ine 171, in main
    activate.main()
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\cli\activate.py
", line 181, in main
    from ..install import symlink_conda
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\install.py", li
ne 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\core\package_ca
che.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\core\path_actio
ns.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\gateways\downlo
ad.py", line 17, in <module>
    from ..connection import CondaSession
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\connection.py",
 line 55, in <module>
    python=platform.python_implementation(),
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\platform.py", line 1234, in python_
implementation
    return _sys_version()[0]
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\platform.py", line 1192, in _sys_ve
rsion
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.1 |Anaconda custom (64-bit
)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nikhil.sindhi\Anaconda3\Scripts\conda-script.py", line 5, in <m
odule>
    sys.exit(conda.cli.main())
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\cli\main.py", l
ine 179, in main
    return handle_exception(e)
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\exceptions.py",
 line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\exceptions.py",
 line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\cli\main_info.p
y", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\site-packages\conda\connection.py",
 line 55, in <module>
    python=platform.python_implementation(),
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\platform.py", line 1234, in python_
implementation
    return _sys_version()[0]
  File "C:\Users\nikhil.sindhi\Anaconda3\lib\platform.py", line 1192, in _sys_ve
rsion
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '3.6.1 |Anaconda custom (64-bit
)| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]'

**Comment by kalefranz** [comment]
Google would probably be more help than we can be here.

https://www.google.com/search?q=ValueError%3A+failed+to+parse+CPython+sys.version
