### ISSUE TITLE
ImportError: cannot import name 'get_auth_from_url'

### ISSUE THREAD

**Issue by NicholasFarrow** [conda/conda#6506]
Not sure what this error means but it suggested I share here. Possibly related, I am unable to import corner inside my document.

Traceback (most recent call last):
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\gateways\download.py", line 17, in <module>
    from ..connection import CondaSession
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nicholas\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\nicholas\Anaconda3\lib\site-packages\conda\connection.py", line 16, in <module>
    from requests.utils import get_auth_from_url, get_netrc_auth
ImportError: cannot import name 'get_auth_from_url'

**Comment by NicholasFarrow** [comment]
Nevermind, found solution:

https://github.com/conda/conda/issues/5651
