### ISSUE TITLE
OSError: Too many levels of symlinks

### ISSUE THREAD

**Issue by msarahan** [conda/conda#6514]
This happened in a conda render operation, but does not appear to be readily reproducible - perhaps just a fluke, but something to watch out for if it happens often enough.

```
Traceback (most recent call last):
  File "/Users/msarahan/miniconda3/bin/c3i", line 11, in <module>
    load_entry_point('conda-concourse-ci', 'console_scripts', 'c3i')()
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/cli.py", line 123, in main
    execute.submit_one_off(**args.__dict__)
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/execute.py", line 647, in submit_one_off
    **kwargs)
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/execute.py", line 508, in compute_builds
    variant_config_files=kw.get('variant_config_files', []))
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/execute.py", line 72, in collect_tasks
    config=config)
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/compute_build_graph.py", line 379, in construct_graph
    recipes_dir, config=config)
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/compute_build_graph.py", line 206, in add_recipe_to_graph
    rendered = _get_or_render_metadata(recipe_dir, worker, config=config)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/utils.py", line 38, in __call__
    return self.func(*args, **kw)
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/compute_build_graph.py", line 199, in _get_or_render_metadata
    bypass_env_check=True, config=config)
  File "/Users/msarahan/code/conda-build/conda_build/api.py", line 49, in render
    permit_undefined_jinja=not finalize):
  File "/Users/msarahan/code/conda-build/conda_build/metadata.py", line 1781, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/msarahan/code/conda-build/conda_build/metadata.py", line 645, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/msarahan/code/conda-build/conda_build/render.py", line 387, in finalize_metadata
    exclude_pattern)
  File "/Users/msarahan/code/conda-build/conda_build/render.py", line 306, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/Users/msarahan/code/conda-build/conda_build/render.py", line 289, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/Users/msarahan/code/conda-build/conda_build/render.py", line 251, in get_upstream_pins
    pfe.execute()
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 494, in execute
    self._execute_action(action)
  File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/package_cache.py", line 515, in _execute_action
    raise CondaMultiError(exceptions)
conda.CondaMultiError: OSError(62, 'Too many levels of symbolic links')
OSError(62, 'Too many levels of symbolic links')
OSError(62, 'Too many levels of symbolic links')
```

**Comment by kalefranz** [comment]
In an auto-upload report we got something similar.  Maybe more details here.

    "command": "/Users/boris/bin/miniconda/bin/conda install clangxx_osx-64"
    "user_agent": "conda/4.4.1 requests/2.18.4 CPython/2.7.14 Darwin/17.3.0 OSX/10.13.2"

```
Traceback (most recent call last):
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/exceptions.py\", line 721, in __call__
    return func(*args, **kwargs)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/cli/main.py\", line 78, in _main
    exit_code = do_call(args, p)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py\", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/cli/main_install.py\", line 11, in execute
    install(args, parser, 'install')
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/cli/install.py\", line 239, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/cli/install.py\", line 256, in handle_txn
    unlink_link_transaction.display_actions(progressive_fetch_extract)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/link.py\", line 706, in display_actions
    legacy_action_groups = self.make_legacy_action_groups(pfe)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/link.py\", line 689, in make_legacy_action_groups
    pfe.prepare()
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/common/io.py\", line 402, in decorated
    return f(*args, **kwds)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 508, in prepare
    for prec in self.link_precs)
  File \"/Users/boris/bin/miniconda/lib/python2.7/_abcoll.py\", line 571, in update
    for key, value in other:
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 508, in <genexpr>
    for prec in self.link_precs)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 402, in make_actions_for_record
    ), None)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 399, in <genexpr>
    pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 400, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 116, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 209, in _package_cache_records
    self.load()
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 88, in load
    package_cache_record = self._make_single_record(base_name)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/core/package_cache.py\", line 294, in _make_single_record
    extract_tarball(package_tarball_full_path, extracted_package_dir)
  File \"/Users/boris/bin/miniconda/lib/python2.7/site-packages/conda/gateways/disk/create.py\", line 145, in extract_tarball
    t.extractall(path=destination_directory, members=members_with_progress())
  File \"/Users/boris/bin/miniconda/lib/python2.7/tarfile.py\", line 2081, in extractall
    self.extract(tarinfo, path)
  File \"/Users/boris/bin/miniconda/lib/python2.7/tarfile.py\", line 2118, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name))
  File \"/Users/boris/bin/miniconda/lib/python2.7/tarfile.py\", line 2194, in _extract_member
    self.makefile(tarinfo, targetpath)
  File \"/Users/boris/bin/miniconda/lib/python2.7/tarfile.py\", line 2234, in makefile
    with bltn_open(targetpath, \"wb\") as target:
IOError: [Errno 62] Too many levels of symbolic links: u'/Users/boris/bin/miniconda/pkgs/openssl-1.0.2l-h077ae2c_5/ssl/man/man3/mdc2.3'
```

**Comment by cscanlin** [comment]
I'm running into the exact error above when trying to use the undocumented `CONDA_SUBDIR` setting on a fresh anaconda install.

System:
python 3.6.3
anaconda 5.0.1
macOS 10.13.2

All other config options (channels, environment, etc) are default.

I am able to replicate the error from the root environment of a clean install with the following command:
```
CONDA_SUBDIR=linux-64 \
$HOME/anaconda3/bin/conda install \
  --yes --mkdir --json -vv \
  --prefix $HOME/temp_conda_env \
  python=3.6 flask pyyaml yaml pandas nomkl
```

Traceback: https://gist.github.com/cscanlin/25fa05575918752252a071f352a7395a

For reference, I am trying to use `CONDA_SUBDIR` in an attempt at picking up the torch on conda support for Zappa: https://github.com/Miserlou/Zappa/pull/108

Please let me know if I can provide additional details, thanks!

**Comment by kalefranz** [comment]
Hey Chris, really appreciate someone digging into conda + Zappa. It’s been on my list for a *long* time, and I just haven’t had the bandwidth. Going to try to look into this particular issue later today.

**Comment by kalefranz** [comment]
Issue here is with trying to use python's `tarfile.extractall()` on the linux-64 openssl package, while on macOS.  Relevant stack trace is

```
    Traceback (most recent call last):
      File "/Users/kfranz/continuum/conda/conda/exceptions.py", line 751, in __call__
        return func(*args, **kwargs)
      File "/Users/kfranz/continuum/conda/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/Users/kfranz/continuum/conda/conda/cli/conda_argparse.py", line 76, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/kfranz/continuum/conda/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 255, in install
        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
      File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 272, in handle_txn
        unlink_link_transaction.display_actions(progressive_fetch_extract)
      File "/Users/kfranz/continuum/conda/conda/core/link.py", line 706, in display_actions
        legacy_action_groups = self.make_legacy_action_groups(pfe)
      File "/Users/kfranz/continuum/conda/conda/core/link.py", line 689, in make_legacy_action_groups
        pfe.prepare()
      File "/Users/kfranz/continuum/conda/conda/common/io.py", line 415, in decorated
        return f(*args, **kwds)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 540, in prepare
        for prec in self.link_precs)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 540, in <genexpr>
        for prec in self.link_precs)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 434, in make_actions_for_record
        ), None)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 431, in <genexpr>
        pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 432, in <genexpr>
        for pkgs_dir in context.pkgs_dirs)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 118, in query
        return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 211, in _package_cache_records
        self.load()
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 90, in load
        package_cache_record = self._make_single_record(base_name)
      File "/Users/kfranz/continuum/conda/conda/core/package_cache.py", line 308, in _make_single_record
        extract_tarball(package_tarball_full_path, extracted_package_dir)
      File "/Users/kfranz/continuum/conda/conda/gateways/disk/create.py", line 145, in extract_tarball
        t.extractall(path=destination_directory, members=members_with_progress())
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 1996, in extractall
        numeric_owner=numeric_owner)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2038, in extract
        numeric_owner=numeric_owner)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2108, in _extract_member
        self.makefile(tarinfo, targetpath)
      File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/tarfile.py", line 2148, in makefile
        with bltn_open(targetpath, "wb") as target:
    OSError: [Errno 62] Too many levels of symbolic links: '/Users/kfranz/linux-64/openssl-1.0.2n-hb7f436b_0/ssl/man/man3/mdc2.3'
```

The linux-64 package has

```
❯ ls -al /Users/kfranz/linux-64/openssl-1.0.2n-hb7f436b_0/ssl/man/man3/MDC*
lrwxr-xr-x  1 kfranz  staff     6B Jan 22 13:23 /Users/kfranz/linux-64/openssl-1.0.2n-hb7f436b_0/ssl/man/man3/MDC2.3@ -> mdc2.3
lrwxr-xr-x  1 kfranz  staff     6B Jan 22 13:23 /Users/kfranz/linux-64/openssl-1.0.2n-hb7f436b_0/ssl/man/man3/MDC2_Final.3@ -> mdc2.3
lrwxr-xr-x  1 kfranz  staff     6B Jan 22 13:23 /Users/kfranz/linux-64/openssl-1.0.2n-hb7f436b_0/ssl/man/man3/MDC2_Init.3@ -> mdc2.3
lrwxr-xr-x  1 kfranz  staff     6B Jan 22 13:23 /Users/kfranz/linux-64/openssl-1.0.2n-hb7f436b_0/ssl/man/man3/MDC2_Update.3@ -> mdc2.3
```

So probably something going on with case sensitivity differences in the file system here.  Still figuring out what the correct fix is...

**Comment by mingwandroid** [comment]
For this kind of thing (specifically running conda on docker on macOS) I create a case-sensitive `APFS` volume then mount it at `/opt` in `/etc/fstab` via:

`UUID /opt apfs rw 0 2`

**Comment by kalefranz** [comment]
Discussed with @mingwandroid.  Problem here is that linux file systems are case-sensitive by default, and macOS is case-insensitive by default.  So for working with linux-64 conda package on macOS, you're going to have to provide a case-sensitive volume for conda to interact with.

Besides setting `CONDA_SUBDIR`, you're also going to need to set `CONDA_PKGS_DIRS` and point it at a path on that case-sensitive volume.  And then of course `--prefix` is going to have to be on that volume as well.

Keeping this issue open so that we can raise a better error message when this happens.

**Comment by cscanlin** [comment]
Thanks so much for the quick response! I didn't have any luck with any variations of the command posted by @mingwandroid, but I've been able to successfully create what looks like the correct environment using macos disk utility to create a case-sensitive volume, and the following command:
```
CONDA_SUBDIR=linux-64 \
CONDA_PKGS_DIRS=/Volumes/zappa/temp_conda_env \
$HOME/anaconda3/bin/conda install \
  --yes --mkdir --json -vv \
  --prefix /Volumes/zappa/temp_conda_env \
  python=3.6 flask pyyaml yaml pandas nomkl
```
Still testing implementation in Zappa.

If you have any advice on the best way to create and then destroy an APFS volume with python or shell commands I'd be very interested to hear it. Also, I'm curious if this problem exists on windows, and/or other older macos versions that still use hfs+.

Thanks again!

**Comment by mingwandroid** [comment]
I showed the contents of my `/etc/fstab`, it was not a command. I created my `/opt` volume permanently using `Disk Utility`; no idea how to do it via the command line. IMHO case-insensitive by default was a mistake by Apple.

**Comment by mingwandroid** [comment]
macOS has always had case-sensitive and case-insensitive variants of HFS+ and also APFS and so long as you use the case-sensitive variant you'll be OK.

Windows has a kernel-flag in the registry to enable case-sensitivity: https://superuser.com/a/842670
