### ISSUE TITLE
Error when updating/installing packages: ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by parnalte** [conda/conda#6530]
I am hitting this JSON-related `ValueError` basically when trying to update or install any package. For a MWE, I can run the following commands:

    $conda create -n testenv
    $source activate testenv
    $conda install python

The full error message I get is the following:

----

Solving environment: done

`$ /home/pablo/anaconda/bin/conda install python`

    Traceback (most recent call last):
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 722, in __call__
        return func(*args, **kwargs)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 75, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 239, in install
        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 256, in handle_txn
        unlink_link_transaction.display_actions(progressive_fetch_extract)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 706, in display_actions
        legacy_action_groups = self.make_legacy_action_groups(pfe)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 689, in make_legacy_action_groups
        pfe.prepare()
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/common/io.py", line 402, in decorated
        return f(*args, **kwds)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 508, in prepare
        for prec in self.link_precs)
      File "/home/pablo/anaconda/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 508, in <genexpr>
        for prec in self.link_precs)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 402, in make_actions_for_record
        ), None)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 399, in <genexpr>
        pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 400, in <genexpr>
        for pkgs_dir in context.pkgs_dirs)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 116, in query
        return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 209, in _package_cache_records
        self.load()
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 88, in load
        package_cache_record = self._make_single_record(base_name)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/core/package_cache.py", line 279, in _make_single_record
        index_json_record = read_index_json(extracted_package_dir)
      File "/home/pablo/anaconda/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 112, in read_index_json
        record = IndexJsonRecord(**json.load(fi))
      File "/home/pablo/anaconda/lib/python2.7/json/__init__.py", line 291, in load
        **kw)
      File "/home/pablo/anaconda/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/home/pablo/anaconda/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/pablo/anaconda/lib/python2.7/json/decoder.py", line 382, in raw_decode
        raise ValueError("No JSON object could be decoded")
    ValueError: No JSON object could be decoded

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=testenv
             CONDA_PREFIX=/home/pablo/anaconda/envs/testenv
    CONDA_PROMPT_MODIFIER=(testenv)
         CONDA_PYTHON_EXE=/home/pablo/anaconda/bin/python
               CONDA_ROOT=/home/pablo/anaconda
              CONDA_SHLVL=1
            DEFAULTS_PATH=/usr/share/gconf/cinnamon.default.path
           MANDATORY_PATH=/usr/share/gconf/cinnamon.mandatory.path
                     PATH=/home/pablo/anaconda/envs/testenv/bin:/home/pablo/anaconda/bin:/home/p
                          ablo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:
                          /usr/games:/usr/local/games:/home/pablo/software_install/mangle/mangle
                          2.2/bin:/home/pablo/software_install/mangle/mangle2.2/scripts
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=8

     active environment : testenv
    active env location : /home/pablo/anaconda/envs/testenv
            shell level : 1
       user config file : /home/pablo/.condarc
 populated config files : 
          conda version : 4.4.2
    conda-build version : 2.1.3
         python version : 2.7.13.final.0
       base environment : /home/pablo/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/pablo/anaconda/pkgs
                          /home/pablo/.conda/pkgs
       envs directories : /home/pablo/anaconda/envs
                          /home/pablo/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.2 requests/2.14.2 CPython/2.7.13 Linux/3.16.0-38-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

----

As I mentioned, I get the same error when trying to install other packages, or updating any existing ones (e.g. `$conda update anaconda` in my root environment).

I have tried cleaning everything with `$conda clean --all` (which actually listed lots of tarballs and packages that were cleaned), but I'm still getting the same error.

I have also run the code suggested by @kalefranz in #4419 and #4425 to identify problematic json files in the `conda-meta` folder, but got no output.

Thanks for your help on this!

**Comment by paulmdavies** [comment]
I'm experiencing the same problem (see #6529) - force downgrading to 4.4.1 will (probably) temporarily fix this whilst waiting for a fix to be released.

```conda install conda=4.1.1```

**Comment by paulmdavies** [comment]
Sorry, I meant downgrading to 4.3.31 would fix it. Typos!

**Comment by kalefranz** [comment]
oh! That might be true, yes

**Comment by parnalte** [comment]
Hi,
Thanks for the fast answers and the fix for this problem. However, this does not work for me as when I try to update to the latest version of conda to get the fix (`$conda update conda`) I actually get this error! (also if I try to downgrade using `$conda install conda=4.3.31`).
So, is there a way in which I can update my conda installation to the latest version to get this fixed? Or will I need to re-install from scratch? (sorry if this is too obvious, I'm not a conda expert).

Thanks again!
