### ISSUE TITLE
python 2 can't read unicode in environments.txt

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6541]
on a conda install operation, during the transaction

```
Traceback (most recent call last):
  File "/Users/kfranz/continuum/conda/conda/core/link.py", line 535, in _execute_actions
    action.execute()
  File "/Users/kfranz/continuum/conda/conda/core/path_actions.py", line 876, in execute
    register_env(self.target_prefix)
  File "/Users/kfranz/continuum/conda/conda/core/envs_manager.py", line 28, in register_env
    if location in yield_lines(USER_ENVIRONMENTS_TXT_FILE):
  File "/Users/kfranz/continuum/conda/conda/gateways/disk/read.py", line 49, in yield_lines
    if not line or line.startswith('#'):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 54: ordinal not in range(128)
```

**Comment by kalefranz** [comment]
Part of my `~/.conda/environments.txt` file that's causing python 2 to choke:

```
/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/envs/shapely=1.6.0
/var/folders/cp/7r2s_s593j7_cpdtxxsmct880000gp/T/26b3 çêôñáß
/var/folders/cp/7r2s_s593j7_cpdtxxsmct880000gp/T/8eba áçêßôñ
/Users/kfranz/miniconda/envs/py2
/conda3
/Users/kfranz/miniconda/envs/_test2
```
