### ISSUE TITLE
Anaconda Prompt is not working

### ISSUE THREAD

**Issue by ghost477** [conda/conda#6547]
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "C:\Users\user\Anaconda3\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "C:\Users\user\Anaconda3\lib\site-packages\requests\utils.py", line 24, in <module>
    from . import certs
  File "C:\Users\user\Anaconda3\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\user\Anaconda3\lib\site-packages\requests\__init__.py", line 97, in <module>
    from . import utils
  File "C:\Users\user\Anaconda3\lib\site-packages\requests\utils.py", line 24, in <module>
    from . import certs
  File "C:\Users\user\Anaconda3\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

**Comment by kalefranz** [comment]
You've lost certifi out of your environment and crippled conda.  Plenty of ways that can happen, including uninstalling with pip.  Easiest solution is just to reinstall Miniconda or Anaconda.
