### ISSUE TITLE
Can not open anaconda command prompt | can not install anaconda package

### ISSUE THREAD

**Issue by subhasis85** [conda/conda#6571]
Hello,

I am getting the following error while trying to -
1. open anaconda command prompt
2. install anaconda package using "conda install"

Traceback (most recent call last):
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 161, in get_info_dict
    from ..config import rc_path, sys_rc_path, user_rc_path
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\config.py", line 92, in <module>
    envs_dirs = context.envs_dirs
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\base\context.py", line 292, in envs_dirs
    join(self._user_data_dir, 'envs'),
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\base\context.py", line 327, in _user_data_dir
    return user_data_dir(APP_NAME, APP_NAME)
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)
  File "C:\Users\SUBHASIS.idea-PC\Anaconda2\lib\site-packages\conda\_vendor\appdirs.py", line 284, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: DLL load failed: %1 is not a valid Win32 application.

Is anyone facing the same issue? I am on windows 10 64bit.

**Comment by kalefranz** [comment]
Looks like [DLL hell](https://en.wikipedia.org/wiki/DLL_Hell).  Were you able to resolve your issue?

**Comment by niranjanreddy891** [comment]
@subhasis85, I had the same issue while using win-10. But now I installed win-7. It works fine on my machine now.
