### ISSUE TITLE
"UnicodeDecodeError" occurred after "pip install pipenv"

### ISSUE THREAD

**Issue by fancyChuan** [conda/conda#6605]
I use anaconda2 on win7 and can pip install pipenv successfully with some package being update like requests (from 2.6.0 to 2.18.0). But I fail to use pipenv install and occur an unicodeDecodeError.

And after reinstall anaconda2, I found that anaconda2 start menu didn't have ipython, jupyter qtconsole.
![image](https://user-images.githubusercontent.com/13439296/34435178-9de5bef8-ecc6-11e7-93d4-dbb8a127aa1c.png)

When I click 'Anaconda Prompt', it shows like the following

--------------------------------------------------------------------------------------------
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : D:\ProgramData\Anaconda2  (writable)
    default environment : D:\ProgramData\Anaconda2
       envs directories : D:\ProgramData\Anaconda2\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : D:\ProgramData\Anaconda2\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7
Windows/6.1.7601
          administrator : True

`$ D:\ProgramData\Anaconda2\Scripts\conda ..checkenv cmd.exe D:\ProgramData\Anac
onda2`




    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line
171, in main
        activate.main()
      File "D:\ProgramData\Anaconda2\lib\site-packages\conda\cli\activate.py", l
ine 181, in main
        from ..install import symlink_conda
      File "D:\ProgramData\Anaconda2\lib\site-packages\conda\install.py", line 3
7, in <module>
        from .core.package_cache import rm_fetched  # NOQA
      File "D:\ProgramData\Anaconda2\lib\site-packages\conda\core\package_cache.
py", line 9, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "D:\ProgramData\Anaconda2\lib\site-packages\conda\core\path_actions.p
y", line 33, in <module>
        from ..gateways.download import download
      File "D:\ProgramData\Anaconda2\lib\site-packages\conda\gateways\download.p
y", line 10, in <module>
        from requests.exceptions import ConnectionError, HTTPError, InvalidSchem
a, SSLError
      File "D:\ProgramData\Anaconda2\lib\site-packages\requests\__init__.py", li
ne 84, in <module>
        from urllib3.contrib import pyopenssl
      File "D:\ProgramData\Anaconda2\lib\site-packages\urllib3\contrib\pyopenssl
.py", line 46, in <module>
        import OpenSSL.SSL
      File "D:\ProgramData\Anaconda2\lib\site-packages\OpenSSL\__init__.py", lin
e 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "D:\ProgramData\Anaconda2\lib\site-packages\OpenSSL\crypto.py", line
12, in <module>
        from cryptography import x509
      File "D:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\__init_
_.py", line 9, in <module>
        from cryptography.x509.base import (
      File "D:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\base.py
", line 16, in <module>
        from cryptography.x509.extensions import Extension, ExtensionType
      File "D:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\extensi
ons.py", line 13, in <module>
        from asn1crypto.keys import PublicKeyInfo
      File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\keys.py", line
 22, in <module>
        from ._elliptic_curve import (
      File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curv
e.py", line 51, in <module>
        from ._int import inverse_mod
      File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_int.py", line
 56, in <module>
        from ._perf._big_num_ctypes import libcrypto
      File "D:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num
_ctypes.py", line 31, in <module>
        libcrypto_path = find_library('crypto')
      File "D:\ProgramData\Anaconda2\lib\ctypes\util.py", line 53, in find_libra
ry
        fname = os.path.join(directory, name)
      File "D:\ProgramData\Anaconda2\lib\ntpath.py", line 85, in join
        result_path = result_path + p_path
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xbc in position 4: ordi
nal not in range(128)
```
------------------------------------------------------------------------------------------
How can I fix it? Thanks very much~

**Comment by kalefranz** [comment]
You've pip-installed requests, and pip has apparently gotten request's dependencies in an incompatible state.  Sorry for the bad news.

**Comment by epogrebnyak** [comment]
> You've pip-installed requests, and pip has apparently gotten request's dependencies in an incompatible state. Sorry for the bad news.

UnicodeDecodeError appeasr on Windows 10 on fresh bare conda installation, #8662 
Perhaps the issue is not pip interference.
