### ISSUE TITLE
KeyError for channel '<unknown>'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6621]
```
error: KeyError(Dist(channel='<unknown>', dist_name='anyqt-0.0.8-py36_0', name='anyqt', version='0.0.8', build_string='py36_0', build_number=0, base_url=None, platform=None),)
command: C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\Scripts\conda install --yes --quiet orange3-text
user_agent: conda/4.4.4 requests/2.18.4 CPython/3.6.3 Windows/7 Windows/6.1.7601
_messageid: -9223372036843225521
_messagetime: 1514571464046 / 2017-12-29 12:17:44

Traceback (most recent call last):
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\install.py", line 236, in install
    force_reinstall=context.force,
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\solve.py", line 407, in solve_final_state
    return IndexedSet(index[d] for d in solution)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 90, in __init__
    self.update(other)
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 304, in update
    for o in other:
  File "C:\Users\dylan.puterbaugh\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\solve.py", line 407, in <genexpr>
    return IndexedSet(index[d] for d in solution)
KeyError: Dist(channel='<unknown>', dist_name='anyqt-0.0.8-py36_0', name='anyqt', version='0.0.8', build_string='py36_0', build_number=0, base_url=None, platform=None)
```

**Comment by kalefranz** [comment]
```
error: KeyError(Dist(channel='<unknown>', dist_name='pytorch-0.1.12-py36_0.1.12cu80', name='pytorch', version='0.1.12', build_string='py36_0.1.12cu80', build_number=11280, base_url=None, platform=None),)
command: D:\Anaconda3\Scripts\conda install -c conda-forge tqdm
user_agent: conda/4.4.4 requests/2.18.4 CPython/3.6.3 Windows/8.1 Windows/6.3.9600
_messageid: -9223372036842225512
_messagetime: 1514735347705 / 2017-12-31 09:49:07

Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "D:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "D:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 236, in install
    force_reinstall=context.force,
  File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 407, in solve_final_state
    return IndexedSet(index[d] for d in solution)
  File "D:\Anaconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 90, in __init__
    self.update(other)
  File "D:\Anaconda3\lib\site-packages\conda\_vendor\boltons\setutils.py", line 304, in update
    for o in other:
  File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 407, in <genexpr>
    return IndexedSet(index[d] for d in solution)
KeyError: Dist(channel='<unknown>', dist_name='pytorch-0.1.12-py36_0.1.12cu80', name='pytorch', version='0.1.12', build_string='py36_0.1.12cu80', build_number=11280, base_url=None, platform=None)

```

**Comment by kalefranz** [comment]
Duplicate of #6665
