### ISSUE TITLE
ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6622]
```
error: ScannerError()
command: C:\Users\Drey\Miniconda2\Scripts\conda-env create -f python2.7-environment.yml
user_agent: conda/4.4.4 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
_messageid: -9223372036843275577
_messagetime: 1514529416307 / 2017-12-29 00:36:56

Traceback (most recent call last):
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda_env\cli\main.py", line 74, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda_env\cli\main_create.py", line 79, in execute
    directory=os.getcwd())
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
    if spec.can_handle():
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda_env\env.py", line 84, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda_env\env.py", line 72, in from_yaml
    data = yaml_load_standard(yamlstr)
  File "C:\Users\Drey\Miniconda2\lib\site-packages\conda\common\serialize.py", line 74, in yaml_load_standard
    return yaml.load(string, Loader=yaml.Loader, version="1.2")
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\main.py", line 75, in load
    return loader.get_single_data()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\constructor.py", line 60, in get_single_data
    node = self.get_single_node()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\composer.py", line 53, in get_single_node
    document = self.compose_document()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\composer.py", line 76, in compose_document
    self.get_event()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\parser.py", line 136, in get_event
    self.current_event = self.state()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\parser.py", line 215, in parse_document_end
    token = self.peek_token()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\scanner.py", line 144, in peek_token
    self.fetch_more_tokens()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\scanner.py", line 239, in fetch_more_tokens
    return self.fetch_value()
  File "C:\Users\Drey\Miniconda2\lib\site-packages\ruamel_yaml\scanner.py", line 598, in fetch_value
    self.get_mark())
ScannerError: mapping values are not allowed here
  in "<byte string>", line 500, column 24:
      <!-- blob contrib key: blob_contributors:v21:2b73629f ...
```

**Comment by kalefranz** [comment]
```
error: ScannerError(None, None, 'mapping values are not allowed here', <ruamel_yaml.error.Mark object at 0x7f6164d78240>)
command: /data2/zhao/yxzhao/tools/Miniconda3/bin/conda-env create --name /data2/zhao/yxzhao/tools/cworld-dekker-master/lib/cworld --file /data2/zhao/yxzhao/tools/cworld-dekker-master/cworld_environment.yml
user_agent: conda/4.4.4 requests/2.18.4 CPython/3.6.4 Linux/3.10.0-514.el7.x86_64 centos/7 glibc/2.17
_messageid: -9223372036843225511
_messagetime: 1514572787375 / 2017-12-29 12:39:47

Traceback (most recent call last):
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 79, in execute
    directory=os.getcwd())
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
    if spec.can_handle():
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 84, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 72, in from_yaml
    data = yaml_load_standard(yamlstr)
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/conda/common/serialize.py", line 74, in yaml_load_standard
    return yaml.load(string, Loader=yaml.Loader, version="1.2")
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 75, in load
    return loader.get_single_data()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
    node = self.get_single_node()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 53, in get_single_node
    document = self.compose_document()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 76, in compose_document
    self.get_event()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 136, in get_event
    self.current_event = self.state()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 215, in parse_document_end
    token = self.peek_token()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
    self.fetch_more_tokens()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 239, in fetch_more_tokens
    return self.fetch_value()
  File "/data2/zhao/yxzhao/tools/Miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 598, in fetch_value
    self.get_mark())
ruamel_yaml.scanner.ScannerError: mapping values are not allowed here
  in "<unicode string>", line 316, column 24:
      <!-- blob contrib key: blob_contributors:v21:51a1841d ...
                           ^
```
