### ISSUE TITLE
RuntimeError: cannot join thread before it is started

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6623]
```
error: RuntimeError('cannot join thread before it is started',)
command: C:\ProgramData\Anaconda2\Scripts\conda install keras
user_agent: conda/4.4.4 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
_messageid: -9223372036843225538
_messagetime: 1514566220833 / 2017-12-29 10:50:20

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 236, in install
    force_reinstall=context.force,
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\solve.py", line 496, in solve_for_transaction
    context.json):
  File "C:\ProgramData\Anaconda2\lib\contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\common\io.py", line 325, in spinner
    sp.stop()
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\common\io.py", line 285, in stop
    self._spinner_thread.join()
  File "C:\ProgramData\Anaconda2\lib\threading.py", line 929, in join
    raise RuntimeError("cannot join thread before it is started")
RuntimeError: cannot join thread before it is started
```

**Comment by kalefranz** [comment]
resolved with #6653
