### ISSUE TITLE
RuntimeError: can't start new thread

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6624]
```
error: RuntimeError("generator didn't stop after throw()",)
command: /home/mholekev/miniconda3/bin/conda install --yes numpy scipy matplotlib jupyter git pandas
user_agent: conda/4.4.4 requests/2.18.4 CPython/3.6.3 Linux/2.6.32-696.10.3.el6.x86_64 centos/6.7 glibc/2.12
_messageid: -9223372036842075552
_messagetime: 1514766990662 / 2017-12-31 18:36:30

Traceback (most recent call last):
  File "/home/mholekev/miniconda3/lib/python3.6/site-packages/conda/common/io.py", line 399, in backdown_thread_pool
    yield ThreadPoolExecutor(max_workers)
  File "/home/mholekev/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 214, in get_reduced_index
    new_records = query_all(spec)
  File "/home/mholekev/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 187, in query_all
    return tuple(concat(future.result() for future in as_completed(futures)))
  File "/home/mholekev/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 187, in <genexpr>
    return tuple(concat(future.result() for future in as_completed(futures)))
  File "/home/mholekev/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 217, in as_completed
    fs = set(fs)
  File "/home/mholekev/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 186, in <genexpr>
    futures = (executor.submit(sd.query, spec) for sd in subdir_datas)
  File "/home/mholekev/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/home/mholekev/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/home/mholekev/miniconda3/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

```

**Comment by kalefranz** [comment]
```
error: RuntimeError("can't start new thread",)
command: /ahg/regevdata/users/subraman/software/miniconda3/bin/conda create -n test
user_agent: conda/4.4.4 requests/2.18.4 CPython/3.6.3 Linux/2.6.32-696.16.1.el6.x86_64 rhel/6.9 glibc/2.12
_messageid: -9223372036842425559
_messagetime: 1514681157023 / 2017-12-30 18:45:57

Traceback (most recent call last):
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 11, in execute
    install(args, parser, 'create')
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 236, in install
    force_reinstall=context.force,
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 514, in solve_for_transaction
    SubdirData.query_all(self.channels, self.subdirs, conda_newer_spec),
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 88, in query_all
    return tuple(concat(future.result() for future in as_completed(futures)))
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 88, in <genexpr>
    return tuple(concat(future.result() for future in as_completed(futures)))
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 217, in as_completed
    fs = set(fs)
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 87, in <genexpr>
    ) for url in channel_urls)
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 123, in submit
    self._adjust_thread_count()
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/concurrent/futures/thread.py", line 142, in _adjust_thread_count
    t.start()
  File "/ahg/regevdata/users/subraman/software/miniconda3/lib/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

```
