### ISSUE TITLE
Broken environment from 'ValueError: No JSON object could be decoded'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6625]
```
error: ValueError('No JSON object could be decoded',)
command: C:\Users\SemmyTaju\Anaconda2\Scripts\conda install theano
user_agent: conda/4.4.4 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.15063
_messageid: -9223372036843325575
_messagetime: 1514530049486 / 2017-12-29 00:47:29

Traceback (most recent call last):
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\cli\conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\cli\install.py", line 236, in install
    force_reinstall=context.force,
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\solve.py", line 145, in solve_final_state
    solution = tuple(Dist(d) for d in prefix_data.iter_records())
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 90, in iter_records
    return itervalues(self._prefix_records)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 103, in _prefix_records
    return self.__prefix_records or self.load() or self.__prefix_records
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 48, in load
    self._load_single_record(meta_file)
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 108, in _load_single_record
    json_data = json_load(fh.read())
  File "C:\Users\SemmyTaju\Anaconda2\lib\site-packages\conda\common\serialize.py", line 85, in json_load
    return json.loads(string)
  File "C:\Users\SemmyTaju\Anaconda2\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\Users\SemmyTaju\Anaconda2\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\SemmyTaju\Anaconda2\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by kalefranz** [comment]
The only thing we can do in 4.4 I think is target

    conda\core\linked_data.py", line 108, in _load_single_record

with a more useful message.  In the future, we should be thinking about how we can recover from when transactions get SIGKILL.
