### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6626]
```
error: AttributeError("'_NamespacePath' object has no attribute 'sort'",)
command: C:\Users\Woo\Anaconda3\Scripts\conda update --all
user_agent: conda/4.4.4 requests/2.14.2 CPython/3.5.2 Windows/10 Windows/10.0.16299
_messageid: -9223372036842225450
_messagetime: 1514755283479 / 2017-12-31 15:21:23

Traceback (most recent call last):
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 74, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\Woo\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 9, in <module>
    from .install import install
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\cli\install.py", line 20, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache import PackageCache
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 12, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 27, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\Woo\Anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 5, in <module>
    from requests import ConnectionError, HTTPError, Session
  File "C:\Users\Woo\Anaconda3\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Users\Woo\Anaconda3\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 46, in <module>
    import OpenSSL.SSL
  File "C:\Users\Woo\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "C:\Users\Woo\Anaconda3\lib\site-packages\OpenSSL\crypto.py", line 13, in <module>
    from cryptography.hazmat.primitives.asymmetric import dsa, rsa
  File "C:\Users\Woo\Anaconda3\lib\site-packages\cryptography\hazmat\primitives\asymmetric\rsa.py", line 14, in <module>
    from cryptography.hazmat.backends.interfaces import RSABackend
  File "C:\Users\Woo\Anaconda3\lib\site-packages\cryptography\hazmat\backends\__init__.py", line 7, in <module>
    import pkg_resources
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2985, in <module>
    @_call_aside
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2971, in _call_aside
    f(*args, **kwargs)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 3013, in _initialize_master_working_set
    dist.activate(replace=False)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2544, in activate
    declare_namespace(pkg)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2118, in declare_namespace
    _handle_ns(packageName, path_item)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2058, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "C:\Users\Woo\Anaconda3\lib\site-packages\setuptools-27.2.0-py3.5.egg\pkg_resources\__init__.py", line 2087, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'

```

**Comment by kalefranz** [comment]
Based on https://github.com/pypa/setuptools/issues/885, I think we just need to enforce a constrained dependency for setuptools in the conda recipe.
