### ISSUE TITLE
rm_rf fails to actually rm_rf

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6631]
It seems by-far the most common error we're seeing right now.  Most all reports are from Windows.

```
error: AssertionError('C:\\Users\\fral6001\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\sympy-1.0-py36_0',)
command: C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\Scripts\conda install --yes --json --force-pscheck --prefix C:\Users\fral6001\AppData\Local\Continuum\Anaconda3 anaconda-navigator==1.6.11
user_agent: conda/4.4.4 requests/2.14.2 CPython/3.6.2 Windows/8.1 Windows/6.3.9600
_messageid: -9223372036843525502
_messagetime: 1514482741592 / 2017-12-28 11:39:01

Traceback (most recent call last):
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 270, in _make_single_record
    repodata_record = read_repodata_json(extracted_package_dir)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 123, in read_repodata_json
    with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fral6001\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\sympy-1.0-py36_0\\info\\repodata_record.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 287, in _make_single_record
    index_json_record = read_index_json(extracted_package_dir)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 111, in read_index_json
    with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\fral6001\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\sympy-1.0-py36_0\\info\\index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 281, in handle_txn
    progressive_fetch_extract.execute()
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 553, in execute
    self.prepare()
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\io.py", line 415, in decorated
    return f(*args, **kwds)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in prepare
    for prec in self.link_precs)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in <genexpr>
    for prec in self.link_precs)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 434, in make_actions_for_record
    ), None)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 431, in <genexpr>
    pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 432, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 118, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 211, in _package_cache_records
    self.load()
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 90, in load
    package_cache_record = self._make_single_record(base_name)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 308, in _make_single_record
    extract_tarball(package_tarball_full_path, extracted_package_dir)
  File "C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 133, in extract_tarball
    assert not lexists(destination_directory), destination_directory
AssertionError: C:\Users\fral6001\AppData\Local\Continuum\Anaconda3\pkgs\sympy-1.0-py36_0
```

**Comment by kalefranz** [comment]
Here's one report that isn't from Windows.  Although I'm guessing, given the very low frequency we're seeing unix stack traces like this, I'm guessing the unix ones are more related to #6610.

```
error: AssertionError('/home/farabi/anaconda3/pkgs/testpath-0.3-py35_0',)
command: /home/farabi/anaconda3/bin/conda install -c conda-forge keras
user_agent: conda/4.4.4 requests/2.14.2 CPython/3.5.3 Linux/4.10.0-42-generic ubuntu/16.04 glibc/2.23
_messageid: -9223372036843525508
_messagetime: 1514478268268 / 2017-12-28 10:24:28

Traceback (most recent call last):
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 270, in _make_single_record
    repodata_record = read_repodata_json(extracted_package_dir)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 123, in read_repodata_json
    with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/common/compat.py", line 120, in open
    closefd=closefd)
PermissionError: [Errno 13] Permission denied: '/home/farabi/anaconda3/pkgs/testpath-0.3-py35_0/info/repodata_record.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 287, in _make_single_record
    index_json_record = read_index_json(extracted_package_dir)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 111, in read_index_json
    with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/common/compat.py", line 120, in open
    closefd=closefd)
PermissionError: [Errno 13] Permission denied: '/home/farabi/anaconda3/pkgs/testpath-0.3-py35_0/info/index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 724, in __call__
    return func(*args, **kwargs)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/cli/conda_argparse.py", line 75, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 272, in handle_txn
    unlink_link_transaction.display_actions(progressive_fetch_extract)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 706, in display_actions
    legacy_action_groups = self.make_legacy_action_groups(pfe)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/link.py", line 689, in make_legacy_action_groups
    pfe.prepare()
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/common/io.py", line 415, in decorated
    return f(*args, **kwds)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 540, in prepare
    for prec in self.link_precs)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 540, in <genexpr>
    for prec in self.link_precs)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 434, in make_actions_for_record
    ), None)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 431, in <genexpr>
    pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 432, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 118, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 211, in _package_cache_records
    self.load()
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 90, in load
    package_cache_record = self._make_single_record(base_name)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/core/package_cache.py", line 308, in _make_single_record
    extract_tarball(package_tarball_full_path, extracted_package_dir)
  File "/home/farabi/anaconda3/lib/python3.5/site-packages/conda/gateways/disk/create.py", line 133, in extract_tarball
    assert not lexists(destination_directory), destination_directory
AssertionError: /home/farabi/anaconda3/pkgs/testpath-0.3-py35_0

```

**Comment by garu57** [comment]
Sorry I said something not exact.
I overlooked the fact `log.info` messages are never output unless commands are running at least with `-v` options.
So in the way that normally most users are running commands, `rm_rf()` is not able to tell us that something went awry.

**Comment by kalefranz** [comment]
Before closing this issue, also make sure #7665 is resolved in the solution.

**Comment by jacobwilliams** [comment]
Is the theory that fixing this will fix #5847? The issue reported in #5847 I'm still seeing today on both Windows and Linux. 

Is there any workaround available where I can tell conda or conda-build to manually delete the temp directory?

**Comment by travishathaway** [comment]
@jacobwilliams, I don't think it's possible to tell conda or conda-build to manually clean up the temporary directory (it should in theory already be doing this).

**Comment by WeOrangeSky** [comment]
I'm facing the same error, during the creation of image with conda inside:
conda.gateways.disk.delete:rm_rf(171): rm_rf failed. Not a link, file, or directory: /databricks/conda/envs/cpfr/.condatmp
I already have the latest version of Conda there.

**Comment by jacobwilliams** [comment]
#5847 is still happening so I guess this is still a bug.
