### ISSUE TITLE
conda -h => ValueError: unsupported format character

### ISSUE THREAD

**Issue by scubamut** [conda/conda#6645]
(jupyterlab) C:\Users\scuba>conda -h

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "E:\Miniconda3\lib\site-packages\conda\exceptions.py", line 724, in __call__
        return func(*args, **kwargs)
      File "E:\Miniconda3\lib\site-packages\conda\cli\main.py", line 71, in _main
        args = p.parse_args(args[1:])
      File "E:\Miniconda3\lib\argparse.py", line 1730, in parse_args
        args, argv = self.parse_known_args(args, namespace)
      File "E:\Miniconda3\lib\argparse.py", line 1762, in parse_known_args
        namespace, args = self._parse_known_args(args, namespace)
      File "E:\Miniconda3\lib\argparse.py", line 1968, in _parse_known_args
        start_index = consume_optional(start_index)
      File "E:\Miniconda3\lib\argparse.py", line 1908, in consume_optional
        take_action(action, args, option_string)
      File "E:\Miniconda3\lib\argparse.py", line 1836, in take_action
        action(self, namespace, argument_values, option_string)
      File "E:\Miniconda3\lib\argparse.py", line 1020, in __call__
        parser.print_help()
      File "E:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 149, in print_help
        super(ArgumentParser, self).print_help()
      File "E:\Miniconda3\lib\argparse.py", line 2362, in print_help
        self._print_message(self.format_help(), file)
      File "E:\Miniconda3\lib\argparse.py", line 2346, in format_help
        return formatter.format_help()
      File "E:\Miniconda3\lib\argparse.py", line 282, in format_help
        help = self._root_section.format_help()
      File "E:\Miniconda3\lib\argparse.py", line 213, in format_help
        item_help = join([func(*args) for func, args in self.items])
      File "E:\Miniconda3\lib\argparse.py", line 213, in <listcomp>
        item_help = join([func(*args) for func, args in self.items])
      File "E:\Miniconda3\lib\argparse.py", line 213, in format_help
        item_help = join([func(*args) for func, args in self.items])
      File "E:\Miniconda3\lib\argparse.py", line 213, in <listcomp>
        item_help = join([func(*args) for func, args in self.items])
      File "E:\Miniconda3\lib\argparse.py", line 531, in _format_action
        parts.append(self._format_action(subaction))
      File "E:\Miniconda3\lib\argparse.py", line 519, in _format_action
        help_text = self._expand_help(action)
      File "E:\Miniconda3\lib\argparse.py", line 606, in _expand_help
        return self._get_help_string(action) % params
    ValueError: unsupported format character 'U' (0x55) at index 140

is there a fix for this?

**Comment by kalefranz** [comment]
Output of “conda info”?

**Comment by scubamut** [comment]
(base) C:\Users\scuba>conda info

     active environment : base
    active env location : E:\Miniconda3
            shell level : 1
       user config file : C:\Users\scuba\%USERPROFILE%\.condarc
 populated config files : C:\Users\scuba\%USERPROFILE%\.condarc
          conda version : 4.4.6
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : E:\Miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : E:\Miniconda3\pkgs
                          C:\Users\scuba\AppData\Local\conda\conda\pkgs
       envs directories : E:\Miniconda3\envs
                          C:\Users\scuba\AppData\Local\conda\conda\envs
                          C:\Users\scuba\%USERPROFILE%\.conda\envs
               platform : win-64
             user-agent : conda/4.4.6 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False


%USERPROFILE%  appears to be the problem (windows 10) but how to solve it?

**Comment by kalefranz** [comment]
There's a conda bug here that we're fixing with #6779, but you probably have an OS-level problem if

    python -c "import os; print(os.path.expanduser('~'))"

prints out something with `%USERPROFILE%` in it.

**Comment by mbargull** [comment]
@scubamut: Could you show the value of the environment variables I asked for in https://github.com/conda/conda/issues/6644#issuecomment-355760312?

**Comment by scubamut** [comment]
(root) E:\Miniconda3\Scripts>echo HOME=%HOME%
HOME=%USERPROFILE%

(root) E:\Miniconda3\Scripts>echo USERPROFILE=%USERPROFILE%
USERPROFILE=C:\Users\scuba

(root) E:\Miniconda3\Scripts>echo HOMEDRIVE=%HOMEDRIVE%
HOMEDRIVE=C:

(root) E:\Miniconda3\Scripts>echo HOMEPATH=%HOMEPATH%
HOMEPATH=\Users\scuba
