### ISSUE TITLE
[Errno 13] Permission denied

### ISSUE THREAD

**Issue by clemlpr** [conda/conda#6678]
Hi,

I always get the same error '[Errno 13] Permission denied' when running commands from conda. The following traceback is with 'conda update' but I have the same error with 'search', 'install' and 'create'.
I installed miniconda about 4 months ago and created environments at that time without any problem.

Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : **False**
      conda-env version : 4.3.27
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : /Users/clementlepriol/miniconda3  (read only)
    default environment : /Users/clementlepriol/miniconda3
       envs directories : /Users/clementlepriol/.conda/envs
                          /Users/clementlepriol/miniconda3/envs
          package cache : /Users/clementlepriol/miniconda3/pkgs
                          /Users/clementlepriol/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.14.2 CPython/3.6.1 Darwin/14.5.0 OSX/10.10.5    
                UID:GID : 501:20

`$ /Users/clementlepriol/miniconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/Users/clementlepriol/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/Users/clementlepriol/miniconda3/pkgs/cache/9cd9d6b5.json'

**Comment by nehaljwani** [comment]
Try:
```
chown clementlepriol /Users/clementlepriol/miniconda3/pkgs/cache/*.json
```

**Comment by clemlpr** [comment]
Thanks! It worked for running conda update but now when I run conda install I get another error:

NotWritableError: The current user does not have write permissions to a required path.
  path: /Users/clementlepriol/miniconda3/pkgs/appnope-0.1.0-py36hf537a9a_0/info/repodata_record.json
  uid: 501
  gid: 20

If you feel that permissions on this path are set incorrectly, you can manually
change them by executing

  $ sudo chown 501:20 /Users/clementlepriol/miniconda3/pkgs/appnope-0.1.0-py36hf537a9a_0/info/repodata_record.json


I tried to run the latest command but get the error :

chown: /Users/clementlepriol/miniconda3/pkgs/appnope-0.1.0-py36hf537a9a_0/info/repodata_record.json: No such file or directory

I forced conda install with sudo and that worked but it would be nice if I found a way to run conda normally without sudo.

**Comment by nehaljwani** [comment]
Please don't use sudo unless you have to. To reset the permissions, you could type:
```
sudo chown -R 501:20 /Users/clementlepriol/miniconda3
```

**Comment by clemlpr** [comment]
I also had to type aferward:
sudo chown -R 501:20 /Users/clementlepriol/.conda/

It works now. Thanks a lot!

**Comment by jtlz2** [comment]
I had the repodata_record.json error too. Why do the printed instructions mention this file when it does not exist, rather than the *.json one?
