### ISSUE TITLE
conda index broken

### ISSUE THREAD

**Issue by pvanderlinden** [conda/conda#6686]
when running conda index with the newer version (4.4+) the program crashes on an import.

```
# conda index .
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda-index", line 4, in <module>
    import conda_build.cli.main_index
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/cli/main_index.py", line 7, in <module>
    from conda_build.conda_interface import ArgumentParser
  File "/opt/anaconda3/lib/python3.5/site-packages/conda_build/conda_interface.py", line 9, in <module>
    from conda.api import get_index  # NOQA
ImportError: cannot import name 'get_index'

# conda info

     active environment : None
            shell level : 0
       user config file : /home/paul/.condarc
 populated config files : /home/paul/.condarc
          conda version : 4.4.6
    conda-build version : 2.0.4
         python version : 3.5.2.final.0
       base environment : /opt/anaconda3  (writable)
           channel URLs : 
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /opt/anaconda3/pkgs
                          /home/paul/.conda/pkgs
       envs directories : /opt/anaconda3/envs
                          /home/paul/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.6 requests/2.11.1 CPython/3.5.2 Linux/4.4.0-104-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : /home/paul/.netrc
           offline mode : False
```

**Comment by mingwandroid** [comment]
`conda update conda-build` should get you going again

**Comment by pvanderlinden** [comment]
Thanks, that solves this issue. Shouldn't that be a dependency then?

Unfortunately doing a new `conda index` doesn't solve the problem. Custom channels are still broken:
https://github.com/conda/conda/issues/6679

**Comment by mingwandroid** [comment]
It cannot be a dependency because technically you do not need conda-build to run conda (it just augments it with a few new commands).

Conda 4.4 does introduce constrained optional dependencies though so it should be marked as one of those. Ping @msarahan.

It solves this problem AFAICT but you've run into another one (i.e. people without custom channels would be ok at this point).
