### ISSUE TITLE
Conda 4.4 doesn't select 'numpy ==1.13'

### ISSUE THREAD

**Issue by Zaharid** [conda/conda#6688]
I have a custom recipe as follows:

```
package:
    name: libnnpdf
    version: "{{ GIT_DESCRIBE_TAG[1:] }}.{{ GIT_DESCRIBE_NUMBER }}"

source:
    git_url: ../

requirements:
    build:
        - {{ compiler("cxx") }}
        - {{ compiler("c") }}
        - swig ==3.0.10
        - cmake
        #Found bug in 0.29.2 from the defaults channel
        - pkg-config ==0.29.1
    host:
        - python
        - lhapdf
        - sqlite
        #Gsl doesn't link openblas on old debian 7
        - gsl ==2.2.1 0
        - numpy ==1.13
        - libarchive
        - yaml-cpp
    run:
        - lhapdf
        - python
        - sqlite
        - libgcc # [linux]
        - gsl ==2.2.1 0
        - numpy ==1.13
        - libarchive
        - yaml-cpp
```

This works fine when I conda-build it when conda 4.3 is installed. But it breaks when I have conda 4.4 due to a failure in the conda resolver.

```
Cloning into bare repository '/home/zah/anaconda3/conda-bld/git_cache/home/zah/nngit/libnnpdf'...
done.
Cloning into '/home/zah/anaconda3/conda-bld/libnnpdf_1515500506059/work'...
done.
checkout: 'HEAD'
Your branch is up-to-date with 'origin/master'.
==> git log -n1 <==

commit 9fd35fc12656dee3570b47bb6709ea49f6a0c28b
Author: Zahari <zaharid@gmail.com>
Date:   Sat Nov 25 23:27:36 2017 +0100

    Pull the conda pkg-config

==> git describe --tags --dirty <==

v1.2.0b5-9-g9fd35fc

==> git status <==

On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean

Attempting to finalize metadata for libnnpdf
INFO:conda_build.metadata:Attempting to finalize metadata for libnnpdf
Solving environment: done

Downloading and Extracting Packages
gcc_linux-64 7.2.0: ########################################################################################## | 100% 

Downloading and Extracting Packages
gxx_linux-64 7.2.0: ########################################################################################## | 100% 
Solving environment: done
Solving environment: done
Solving environment: done
Solving environment: done
Solving environment: done
Solving environment: done
Solving environment: done
BUILD START: ['libnnpdf-1.2.0b5.9-py36hc2d81aa_0.tar.bz2']
Solving environment: done
Solving environment: failed

Leaving build/test directories:
  Work:	 /home/zah/anaconda3/conda-bld/work 
  Test:	 /home/zah/anaconda3/conda-bld/test_tmp 
Leaving build/test environments:
  Test:	source activate  /home/zah/anaconda3/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place 
  Build:	source activate  /home/zah/anaconda3/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 


Traceback (most recent call last):
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/environ.py", line 691, in get_install_actions
    actions = install_actions(prefix, index, specs, force=True)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 415, in decorated
    return f(*args, **kwds)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 546, in install_actions
    txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
    force_remove, force_reinstall)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 437, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 317, in solve_final_state
    conflicting_specs = r.get_conflicting_specs(tuple(final_environment_specs))
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 690, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 254, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 172, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound: 
  - numpy==1.13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/zah/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 388, in main
    execute(sys.argv[1:])
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 379, in execute
    verify=args.verify)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 187, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1801, in build_tree
    notest=notest,
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1010, in build
    raise e
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1001, in build
    channel_urls=tuple(m.config.channel_urls))
  File "/home/zah/anaconda3/lib/python3.6/site-packages/conda_build/environ.py", line 693, in get_install_actions
    raise DependencyNeedsBuildingError(exc, subdir=subdir)
conda_build.exceptions.DependencyNeedsBuildingError: Unsatisfiable dependencies for platform linux-64: {'numpy==1.13'}
```

 What is *way* worse, is that with conda 4.4 this package or any other that depends on it transitively can be installed for any user. Leading to impossible to understand error messages. For example 'validphys' depends on 'libnnpdf' and installing it fails with

```
~ $ conda create -p /tmp/test validphys
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - validphys
  - libnnpdf[version='>=1.1.0b7']
  - gsl==2.2.1=1
  - validphys
  - libnnpdf[version='>=1.1.0b7']
  - numpy==1.13

Current channels:

  - https://zigzah.com/static/conda-pkgs-private/linux-64
  - https://zigzah.com/static/conda-pkgs-private/noarch
  - https://zigzah.com/static/conda-pkgs/linux-64
  - https://zigzah.com/static/conda-pkgs/noarch
  - https://repo.continuum.io/pkgs/main/linux-64
  - https://repo.continuum.io/pkgs/main/noarch
  - https://repo.continuum.io/pkgs/free/linux-64
  - https://repo.continuum.io/pkgs/free/noarch
  - https://repo.continuum.io/pkgs/r/linux-64
  - https://repo.continuum.io/pkgs/r/noarch
  - https://repo.continuum.io/pkgs/pro/linux-64
  - https://repo.continuum.io/pkgs/pro/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch
```

even though it works in conda 4.3 and all these packages are indeed in the channels.

**Comment by kalefranz** [comment]
Should be fixed in conda 4.4.7, currently in canary, and likely released to defaults today or tomorrow.  To get it now,

    conda config --add channels conda-canary
    conda update -n base conda
