### ISSUE TITLE
warn on incorrect use of `conda env create --file`

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6697]
```
error: ScannerError('while scanning for the next token', None, "found character '@' that cannot start any token", <ruamel_yaml.error.Mark object at 0x7f3c93c84080>)
command: /home/ivan/miniconda3/bin/conda-env create --name deeplearning --file conda-env-py35-deeplearning.txt
user_agent: conda/4.4.7 requests/2.18.4 CPython/3.6.4 Linux/4.4.0-104-generic ubuntu/16.04 glibc/2.23
_messageid: -9223372036837425459
_messagetime: 1515522572958 / 2018-01-09 12:29:32

Traceback (most recent call last):
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 79, in execute
    directory=os.getcwd())
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 20, in detect
    if spec.can_handle():
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
    self._environment = env.from_file(self.filename)
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 84, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda_env/env.py", line 72, in from_yaml
    data = yaml_load_standard(yamlstr)
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/conda/common/serialize.py", line 74, in yaml_load_standard
    return yaml.load(string, Loader=yaml.Loader, version="1.2")
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/main.py", line 75, in load
    return loader.get_single_data()
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 60, in get_single_data
    node = self.get_single_node()
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 48, in get_single_node
    self.get_event()
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 136, in get_event
    self.current_event = self.state()
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 150, in parse_stream_start
    token.move_comment(self.peek_token())
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 144, in peek_token
    self.fetch_more_tokens()
  File "/home/ivan/miniconda3/lib/python3.6/site-packages/ruamel_yaml/scanner.py", line 276, in fetch_more_tokens
    % utf8(ch), self.get_mark())
ruamel_yaml.scanner.ScannerError: while scanning for the next token
found character '@' that cannot start any token
  in "<unicode string>", line 4, column 1:
    @EXPLICIT
    ^
```

**Comment by valdaarhun** [comment]
Hi. I would like to work on this issue.

**Comment by valdaarhun** [comment]
@kalefranz Hi. There are several things that I have not understood.

I am not able to reproduce this issue. I went through issue #[5915](https://github.com/conda/conda/issues/5915) and tried out `conda list --explicit > explicit-spec-file.txt`. However, no `spec-file.txt` file was generated.

When I tried to do `conda env create --name testingenv -f explicit-spec-file.txt`, I do not get a sea of traceback calls and errors as shown in this issue or in #[5915](https://github.com/conda/conda/issues/5915). I simply get a two-liner error that says:
`Solving environment: failed`
`ResolvePackageNotFound
     - @explicit`

Has this issue been resolved already?
