### ISSUE TITLE
another index KeyError

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6698]
Has to be similar to #6665 but somehow still not completely fixed with PRs in 4.4.7.

```
error: KeyError(Dist(channel='<unknown>', dist_name='bleach-1.5.0-py36_0', name='bleach', version='1.5.0', build_string='py36_0', build_number=0, base_url='file:///C:/ProgramData/Anaconda3/pkgs', platform=None),)
command: C:\ProgramData\Anaconda3\Scripts\conda install tensorflow
user_agent: conda/4.4.7 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
_messageid: -9223372036837525369
_messagetime: 1515532751619 / 2018-01-09 15:19:11

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 272, in handle_txn
    unlink_link_transaction.display_actions(progressive_fetch_extract)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\link.py", line 711, in display_actions
    specs_to_remove=stp.remove_specs, specs_to_add=stp.update_specs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\plan.py", line 97, in display_actions
    info = index[dist]
KeyError: Dist(channel='<unknown>', dist_name='bleach-1.5.0-py36_0', name='bleach', version='1.5.0', build_string='py36_0', build_number=0, base_url='file:///C:/ProgramData/Anaconda3/pkgs', platform=None)
```

**Comment by kalefranz** [comment]
This could be the same as https://github.com/conda/conda/issues/6846

**Comment by travishathaway** [comment]
I'm going to close this issue as the description isn't very clear, and it's most likely not relevant any longer.
