### ISSUE TITLE
FileNotFoundError when extracting tarball

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6707]
```
error: FileNotFoundError(2, 'No such file or directory')
command: C:\Users\Anurag\Anaconda3\Scripts\conda install spyder
user_agent: conda/4.4.7 requests/2.13.0 CPython/3.6.2 Windows/10 Windows/10.0.16299
_messageid: -9223372036837325447
_messagetime: 1515540414747 / 2018-01-09 17:26:54

Traceback (most recent call last):
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 270, in _make_single_record
    repodata_record = read_repodata_json(extracted_package_dir)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 123, in read_repodata_json
    with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Anurag\\Anaconda3\\pkgs\\pip-9.0.1-py36_1\\info\\repodata_record.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 287, in _make_single_record
    index_json_record = read_index_json(extracted_package_dir)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 111, in read_index_json
    with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Anurag\\Anaconda3\\pkgs\\pip-9.0.1-py36_1\\info\\index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\cli\install.py", line 272, in handle_txn
    unlink_link_transaction.display_actions(progressive_fetch_extract)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\link.py", line 706, in display_actions
    legacy_action_groups = self.make_legacy_action_groups(pfe)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\link.py", line 689, in make_legacy_action_groups
    pfe.prepare()
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\common\io.py", line 415, in decorated
    return f(*args, **kwds)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in prepare
    for prec in self.link_precs)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in <genexpr>
    for prec in self.link_precs)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 434, in make_actions_for_record
    ), None)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 431, in <genexpr>
    pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 432, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 118, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 211, in _package_cache_records
    self.load()
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 90, in load
    package_cache_record = self._make_single_record(base_name)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 308, in _make_single_record
    extract_tarball(package_tarball_full_path, extracted_package_dir)
  File "C:\Users\Anurag\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 145, in extract_tarball
    t.extractall(path=destination_directory, members=members_with_progress())
  File "C:\Users\Anurag\Anaconda3\lib\tarfile.py", line 2007, in extractall
    numeric_owner=numeric_owner)
  File "C:\Users\Anurag\Anaconda3\lib\tarfile.py", line 2049, in extract
    numeric_owner=numeric_owner)
  File "C:\Users\Anurag\Anaconda3\lib\tarfile.py", line 2119, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Users\Anurag\Anaconda3\lib\tarfile.py", line 2160, in makefile
    with bltn_open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Anurag\\Anaconda3\\pkgs\\pip-9.0.1-py36_1\\Lib\\site-packages\\pip\\_vendor\\cachecontrol\\__pycache__\\filewrapper.cpython-36.pyc'
```

**Comment by kalefranz** [comment]
```
error: FileNotFoundError(2, 'No such file or directory')
command: C:\Anaconda3\Scripts\conda install --yes --json --force-pscheck --prefix C:\Anaconda3 jupyterlab==0.30.6 --dry-run
user_agent: conda/4.4.7 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
_messageid: -9223372036837325446
_messagetime: 1515541455356 / 2018-01-09 17:44:15

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 270, in _make_single_record
    repodata_record = read_repodata_json(extracted_package_dir)
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 123, in read_repodata_json
    with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
  File "C:\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Anaconda3\\pkgs\\nbformat-4.3.0-py36_0\\info\\repodata_record.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 287, in _make_single_record
    index_json_record = read_index_json(extracted_package_dir)
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 111, in read_index_json
    with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
  File "C:\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Anaconda3\\pkgs\\nbformat-4.3.0-py36_0\\info\\index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 276, in handle_txn
    actions = unlink_link_transaction.make_legacy_action_groups(progressive_fetch_extract)[0]
  File "C:\Anaconda3\lib\site-packages\conda\core\link.py", line 689, in make_legacy_action_groups
    pfe.prepare()
  File "C:\Anaconda3\lib\site-packages\conda\common\io.py", line 415, in decorated
    return f(*args, **kwds)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in prepare
    for prec in self.link_precs)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in <genexpr>
    for prec in self.link_precs)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 434, in make_actions_for_record
    ), None)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 431, in <genexpr>
    pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 432, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 118, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 211, in _package_cache_records
    self.load()
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 90, in load
    package_cache_record = self._make_single_record(base_name)
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 308, in _make_single_record
    extract_tarball(package_tarball_full_path, extracted_package_dir)
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 145, in extract_tarball
    t.extractall(path=destination_directory, members=members_with_progress())
  File "C:\Anaconda3\lib\tarfile.py", line 2007, in extractall
    numeric_owner=numeric_owner)
  File "C:\Anaconda3\lib\tarfile.py", line 2049, in extract
    numeric_owner=numeric_owner)
  File "C:\Anaconda3\lib\tarfile.py", line 2119, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "C:\Anaconda3\lib\tarfile.py", line 2160, in makefile
    with bltn_open(targetpath, "wb") as target:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Anaconda3\\pkgs\\nbformat-4.3.0-py36_0\\Lib\\site-packages\\nbformat-4.3.0-py3.6.egg-info'
```

**Comment by leblancfg** [comment]
Getting the same thing this morning when trying to install `conda install -c conda-forge pymapd`. First try started off as a 400 HTML error, but manually pasting the URL it was pointing to in the browser had no such error.

Running the `conda install` line once again seemed to hang, Ctl-C'ed it, and ran it a third time with `-vvv` (verbose-trace) option.

I'm getting a logging error, for (what seems like) every single package I installed with conda. For some reason it seems to be looking for the `n+1`<sup>th</sup> minor version of what's installed. Here's one example:
~~~
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 270, in _make_single_record
    repodata_record = read_repodata_json(extracted_package_dir)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 123, in read_repodata_json
    with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Leblancfr\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\multipledispatch-0.4.8-py35_0\\info\\repodata_record.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 287, in _make_single_record
    index_json_record = read_index_json(extracted_package_dir)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 111, in read_index_json
    with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\compat.py", line 120, in open
    closefd=closefd)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Leblancfr\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\multipledispatch-0.4.8-py35_0\\info\\index.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 992, in emit
    msg = self.format(record)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 838, in format
    return fmt.format(record)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 575, in format
    record.message = record.getMessage()
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\logging\__init__.py", line 338, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 126, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 975, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 743, in __call__
    return func(*args, **kwargs)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 255, in install
    handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\install.py", line 272, in handle_txn
    unlink_link_transaction.display_actions(progressive_fetch_extract)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 706, in display_actions
    legacy_action_groups = self.make_legacy_action_groups(pfe)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\link.py", line 689, in make_legacy_action_groups
    pfe.prepare()
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\io.py", line 415, in decorated
    return f(*args, **kwds)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in prepare
    for prec in self.link_precs)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 540, in <genexpr>
    for prec in self.link_precs)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 434, in make_actions_for_record
    ), None)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 431, in <genexpr>
    pcrec for pcrec in concat(PackageCache(pkgs_dir).query(pref_or_spec)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 432, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 118, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 211, in _package_cache_records
    self.load()
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 90, in load
    package_cache_record = self._make_single_record(base_name)
  File "C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 294, in _make_single_record
    join(extracted_package_dir, 'info', 'index.json'), e)
Message: 'unable to read %s\n  because'
Arguments: ('C:\\Users\\Leblancfr\\AppData\\Local\\Continuum\\Anaconda3\\pkgs\\multipledispatch-0.4.8-py35_0\\info\\index.json', FileNotFoundError(2, 'No such file or directory'))
DEBUG conda.gateways.disk.create:extract_tarball(131): extracting C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.8-py35_0.tar.bz2
  to C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.8-py35_0
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.8-py35_0\info\repodata_record.json
TRACE conda.core.package_cache:_make_single_record(265): adding to package cache C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.9-py35_0.tar.bz2
DEBUG conda.core.package_cache:_make_single_record(283): unable to read C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.9-py35_0\info\repodata_record.json
  because FileNotFoundError(2, 'No such file or directory')
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.9-py35_0\info\repodata_record.json
TRACE conda.core.package_cache:_make_single_record(265): adding to package cache C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.9-py36_0.tar.bz2
DEBUG conda.core.package_cache:_make_single_record(283): unable to read C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.9-py36_0\info\repodata_record.json
  because FileNotFoundError(2, 'No such file or directory')
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\multipledispatch-0.4.9-py36_0\info\repodata_record.json
TRACE conda.core.package_cache:_make_single_record(265): adding to package cache C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\munch-2.2.0-py36_0.tar.bz2
DEBUG conda.core.package_cache:_make_single_record(283): unable to read C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\munch-2.2.0-py36_0\info\repodata_record.json
  because FileNotFoundError(2, 'No such file or directory')
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\munch-2.2.0-py36_0\info\repodata_record.json
TRACE conda.core.package_cache:_make_single_record(265): adding to package cache C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\navigator-updater-0.1.0-py35_0.tar.bz2
DEBUG conda.core.package_cache:_make_single_record(283): unable to read C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\navigator-updater-0.1.0-py35_0\info\repodata_record.json
  because FileNotFoundError(2, 'No such file or directory')
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\navigator-updater-0.1.0-py35_0\info\repodata_record.json
TRACE conda.core.package_cache:_make_single_record(265): adding to package cache C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\navigator-updater-0.1.0-py36_0.tar.bz2
DEBUG conda.core.package_cache:_make_single_record(283): unable to read C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\navigator-updater-0.1.0-py36_0\info\repodata_record.json
  because FileNotFoundError(2, 'No such file or directory')
TRACE conda.gateways.disk.create:write_as_json_to_file(60): writing json to file C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\navigator-updater-0.1.0-py36_0\info\repodata_record.json
TRACE conda.core.package_cache:_make_single_record(265): adding to package cache C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\nb_anacondacloud-1.2.0-py35_0.tar.bz2
DEBUG conda.core.package_cache:_make_single_record(283): unable to read C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs\nb_anacondacloud-1.2.0-py35_0\info\repodata_record.json
  because FileNotFoundError(2, 'No such file or directory')
~~~

**Comment by kalefranz** [comment]
@leblancfg Can you give me current contents of your package cache?

    dir C:\Users\Leblancfr\AppData\Local\Continuum\Anaconda3\pkgs

That would be helpful in understanding what's going on in these situations.

**Comment by kalefranz** [comment]
> For some reason it seems to be looking for the `n+1`<sup>th</sup> minor version of what's installed.

I actually don't understand this comment, but I'd like to.  Can you point to what you have installed, and the `n+1` thing conda is in error looking for?

**Comment by leblancfg** [comment]
@kalefranz **Update**: I think I just ran into a very large circular dependency situation, that needed over ten minutes to resolve. Install was finally successful, and installing other packages is going without a hitch.

**Comment by rtruxal** [comment]
Wait so what was the resolution to this?

**Comment by rtruxal** [comment]
So I found this:
```
C:\Users\v-rotrux
λ conda clean --help
usage: conda clean [-h] [-y] [--dry-run] [--json] [--debug] [--verbose] [-q]
                   [-a] [-i] [-l] [-t] [-p] [-s]

Remove unused packages and caches.

Options:

optional arguments:
  -h, --help          Show this help message and exit.
  -y, --yes           Do not ask for confirmation.
  --dry-run           Only display what would have been done.
  --json              Report all output as json. Suitable for using conda
                      programmatically.
  --debug             Show debug output.
  --verbose, -v       Use once for info, twice for debug, three times for
                      trace.
  -q, --quiet         Do not display progress bar.
  -a, --all           Remove index cache, lock files, tarballs, unused cache
                      packages, and source cache.
  -i, --index-cache   Remove index cache.
  -l, --lock          Remove all conda lock files.
  -t, --tarballs      Remove cached package tarballs.
  -p, --packages      Remove unused cached packages. Warning: this does not
                      check for symlinked packages.
  -s, --source-cache  Remove files from the source cache of conda build.

Examples:

    conda clean --tarballs```


Namely the `Warning: this does not check for symlinked packages.` portion under the `-p` flag.
I was pretty sure this would mean I'd be left with a giant tangled mess & would need to completely reinstall anaconda to get it working again. 

Not the case: running `conda clean --all` appears to have fixed `conda update` Hat's off to you guys; I'm usually not intimidated by python packaging, but `-vvv` exposes a level of complexity on par with `apt`, or `yum`.
