### ISSUE TITLE
Error calling conda list in one environment - possible to salvage?

### ISSUE THREAD

**Issue by JoeBlair** [conda/conda#6740]
**I'm submitting a...**
  - [x] bug report

### Current Behavior

Cannot install new packages or cannot call conda list in a certain environment

### Steps to Reproduce

call "conda list" from terminal

### Expected Behavior

list of all packages installed in conda environment

##### `conda info`

```
               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\jbl\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\jbl\AppData\Local\Continuum\Anaconda2\envs\py36
       envs directories : C:\Users\jbl\AppData\Local\Continuum\Anaconda2\envs
                          C:\Users\jbl\AppData\Local\conda\conda\envs
                          C:\Users\jbl\.conda\envs
          package cache : C:\Users\jbl\AppData\Local\Continuum\Anaconda2\pkgs
                          C:\Users\jbl\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\jbl\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.15063
          administrator : False
```

##### `conda config --show-sources`

```
==> C:\Users\jbl\.condarc <==
ssl_verify: True
channels:
  - anaconda-fusion
  - defaults
```

##### `conda list --show-channel-urls`

```
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.22
       conda is private : False
      conda-env version : 4.3.22
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : C:\Users\jbl\AppData\Local\Continuum\Anaconda2  (writable)
    default environment : C:\Users\jbl\AppData\Local\Continuum\Anaconda2\envs\py36
       envs directories : C:\Users\jbl\AppData\Local\Continuum\Anaconda2\envs
                          C:\Users\jbl\AppData\Local\conda\conda\envs
                          C:\Users\jbl\.conda\envs
          package cache : C:\Users\jbl\AppData\Local\Continuum\Anaconda2\pkgs
                          C:\Users\jbl\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\jbl\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.22 requests/2.12.4 CPython/2.7.13 Windows/10 Windows/10.0.15063
          administrator : False

`$ C:\Users\jbl\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py list --show-channel-urls`


    Traceback (most recent call last):
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_list.py", line 242, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_list.py", line 172, in print_packages
        installed = linked(prefix)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 123, in linked
        return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\core\linked_data.py", line 36, in load_linked_data
        rec = json.load(fi)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\json\__init__.py", line 291, in load
        **kw)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\json\__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\json\decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\Users\jbl\AppData\Local\Continuum\Anaconda2\lib\json\decoder.py", line 380, in raw_decode
        obj, end = self.scan_once(s, idx)
    ValueError: Expecting , delimiter: line 16 column 5 (char 274)
```

**Comment by kalefranz** [comment]
That situation unfortunately happens when conda gets terminated in the middle of an unlink-link transaction.  It's a known issue.  We try to guard against it, but SIGKILL is SIGKILL.  #6418 is a future improvement meant to address more fundamentally.  Unfortunately that environment is probably trash.  Best thing to do just recreate it.

**Comment by JoeBlair** [comment]
Ok thats great thanks for letting me know, easy to recreate :)
