### ISSUE TITLE
Navigator error root_prefix 

### ISSUE THREAD

**Issue by raghuhome** [conda/conda#6751]
Hi, 
I'm getting a new navigator error after reinstalling multiple times
I am a window's User and I have been getting errors and errors
I have only one User which is Admin
So I have installed only for this user and not multiple users

An unexpected error occurred on Navigator start-up<br>'root_prefix'
Traceback (most recent call last):
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1270, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1663, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 346, in __init__
    self.set_conda_prefix()
  File "C:\Users\....................\Anaconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

I tried updating the anaconda navigator by 
conda update conda 
or
conda update anaconda-navigator
I get the following error

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

NotWritableError: The current user does not have write permissions to a required path.
  path: C:\Users\....................\AppData\Roaming\SPB_Data;C:\Users\....................\AppData\Local\Programs\Python\Python35-32;\.conda\environments.txt

Can someone please help me fix this problem?

**Comment by raghuhome** [comment]
My anaconda navigator version is 1.6.12

**Comment by kalefranz** [comment]
This issue was moved to ContinuumIO/anaconda-issues#8194
