### ISSUE TITLE
Creating new environment with conda 4.4.7 surprisingly upgrades Python from 2.7 to 3.6

### ISSUE THREAD

**Issue by rcthomas** [conda/conda#6753]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
When creating a new Python environment with conda 4.4.7, Python is upgraded from 2.7 to 3.6 unexpectedly.  Is this new behavior intentional in 4.4.x?

### Steps to Reproduce

1. Run Miniconda OS X installer (though I see same behavior on Linux) to say, `$HOME/env`
2. `export PATH=$HOME/env/bin:$PATH` --- I know `conda activate base` is recommended but see #6739.
3. Run `conda update conda`
4. Just to show my Python version:

```
$ python --version
Python 2.7.14 :: Anaconda, Inc.
```

5. Then try to create an env with just numpy, and see that it wants to create it with Python 3.6.4, which is unexpected to me.  If I don't do step 2 (keep conda at 4.3.1) above, it behaves as I expect it should.  Below is the behavior if I update the conda tool to 4.4:

```
$ conda create -n myenv numpy
Solving environment: done

## Package Plan ##

  environment location: /Users/rthomas/bug/env/envs/myenv

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libgfortran-3.0.1          |       h93005f0_2         495 KB
    setuptools-38.4.0          |           py36_0         525 KB
    wheel-0.30.0               |   py36h5eb2c71_1          67 KB
    python-3.6.4               |       hc167b69_1        15.3 MB
    numpy-1.14.0               |   py36h8a80b8c_0         3.9 MB
    certifi-2017.11.5          |   py36ha569be9_0         196 KB
    xz-5.2.3                   |       h0278029_2         253 KB
    pip-9.0.1                  |   py36h1555ced_4         2.2 MB
    intel-openmp-2018.0.0      |       h8158457_8         493 KB
    mkl-2018.0.1               |       hfbd8650_4       155.1 MB
    ------------------------------------------------------------
                                           Total:       178.3 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0
    certifi:         2017.11.5-py36ha569be9_0
    intel-openmp:    2018.0.0-h8158457_8
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libedit:         3.1-hb4e282d_0
    libffi:          3.2.1-h475c297_4
    libgfortran:     3.0.1-h93005f0_2
    mkl:             2018.0.1-hfbd8650_4
    ncurses:         6.0-hd04f020_2
    numpy:           1.14.0-py36h8a80b8c_0
    openssl:         1.0.2n-hdbc3d79_0
    pip:             9.0.1-py36h1555ced_4
    python:          3.6.4-hc167b69_1
    readline:        7.0-hc1231fa_4
    setuptools:      38.4.0-py36_0
    sqlite:          3.20.1-h7e4c145_2
    tk:              8.6.7-h35a86e2_3
    wheel:           0.30.0-py36h5eb2c71_1
    xz:              5.2.3-h0278029_2
    zlib:            1.2.11-hf3cbc9b_2

Proceed ([y]/n)? n
```

## Expected Behavior
I expect it to create a Python 2.7-based environment.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /Users/rthomas/.condarc
 populated config files :
          conda version : 4.4.7
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /Users/rthomas/bug/env  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/rthomas/bug/env/pkgs
                          /Users/rthomas/.conda/pkgs
       envs directories : /Users/rthomas/bug/env/envs
                          /Users/rthomas/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.7 requests/2.18.4 CPython/2.7.14 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 32331:1032331
             netrc file : /Users/rthomas/.netrc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/rthomas/bug/env:
#
asn1crypto                0.23.0           py27h862e517_0    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2017.11.5        py27hfa9a1c4_0    defaults
cffi                      1.11.2           py27h21b8a49_0    defaults
chardet                   3.0.4            py27h2842e91_1    defaults
conda                     4.4.7                    py27_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
cryptography              2.1.4            py27hdbc5e8f_0    defaults
enum34                    1.1.6            py27hf475452_1    defaults
futures                   3.2.0            py27h1b80678_0    defaults
idna                      2.6              py27hedea723_1    defaults
ipaddress                 1.0.18           py27h5b9a5b9_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.0                  hd04f020_2    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
pip                       9.0.1            py27h1567d89_4    defaults
pycosat                   0.6.3            py27h6c51c7e_0    defaults
pycparser                 2.18             py27h0d28d88_1    defaults
pyopenssl                 17.5.0           py27hfda213f_0    defaults
pysocks                   1.6.7            py27h1cff6a6_1    defaults
python                    2.7.14              hde5916a_29    defaults
python.app                2                py27hf2d5e94_7    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py27h9b2b37c_1    defaults
ruamel_yaml               0.11.14          py27h31666c4_2    defaults
setuptools                36.5.0           py27h2a45cec_0    defaults
six                       1.11.0           py27h7252ba3_1    defaults
sqlite                    3.20.1               h7e4c145_2    defaults
tk                        8.6.7                h35a86e2_3    defaults
urllib3                   1.22             py27hc3787e9_0    defaults
wheel                     0.30.0           py27h677a027_1    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by kalefranz** [comment]
> I know conda activate base is recommended but see #6739.

Can you give me the output of

    CONDA_VERBOSE=3 conda shell.posix activate base

**Comment by kalefranz** [comment]
More to the point of the issue, yes, this is expected behavior.  In preparation for https://github.com/conda/conda/issues/3912, when the base environment by default will be empty (no python or anything else) we've decoupled the base environment python version from the python version of newly-created environments.

If you'd like to keep the old behavior, you can do

    conda config --system --add pinned_packages python=2

Note that we still have hard-coded conda *not* change python major-minor versions in an existing environment, if the change isn't explicitly requested.
https://github.com/conda/conda/blob/4.4.7/conda/core/solve.py#L272-L280

**Comment by rcthomas** [comment]
Using `export PATH=/Users/rthomas/bug/env/bin:$PATH` and then doing the requested command on OS X I get the following.  Sorry I must be doing something wrong here...

```
CONDA_VERBOSE=3 conda shell.posix activate base
usage: conda [-h] [-V] command ...
conda: error: argument command: invalid choice: u'/Users/rthomas/bug/env/bin/conda' (choose from u'info', u'help', u'list', u'search', u'create', u'install', u'update', u'upgrade', u'remove', u'uninstall', u'config', u'clean', u'package')
```

Thanks for explaining the change, I am not sure how I missed that was coming.

**Comment by kalefranz** [comment]
Does ‘conda info’ show conda 4.4.7?

**Comment by rcthomas** [comment]
Thanks, I was using an installation with 4.3.31 last night when I was trying to figure out whether this was new in 4.4 or not, and forgot I'd done that.  If I upgrade conda to 4.4.7 and do that it's now:

```
CONDA_VERBOSE=3 conda shell.posix activate base
PS1='(base) '
export CONDA_DEFAULT_ENV='base'
export CONDA_PREFIX='/Users/rthomas/bug/env'
export CONDA_PROMPT_MODIFIER='(base) '
export CONDA_PYTHON_EXE='/Users/rthomas/bug/env/bin/python'
export CONDA_SHLVL='1'
export PATH='/Users/rthomas/bug/env/bin:/Users/rthomas/bug/env/bin:/opt/local/bin:/opt/local/sbin:/Users/rthomas/local/bin:/Users/rthomas/Library/Python/2.7/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:.'
```

**Comment by kalefranz** [comment]
There's no error there.  That's what it's supposed to look like.  Does `source activate root` work for you now?

**Comment by rcthomas** [comment]
No it does not yet:

```
$ source activate root
Traceback (most recent call last):
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/gateways/logging.py", line 64, in emit
    msg = self.format(record)
  File "/Users/rthomas/bug/env/lib/python2.7/logging/__init__.py", line 734, in format
    return fmt.format(record)
  File "/Users/rthomas/bug/env/lib/python2.7/logging/__init__.py", line 465, in format
    record.message = record.getMessage()
  File "/Users/rthomas/bug/env/lib/python2.7/logging/__init__.py", line 329, in getMessage
    msg = msg % self.args
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/__init__.py", line 43, in __repr__
    return '%s: %s' % (self.__class__.__name__, text_type(self))
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/__init__.py", line 47, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character '{' (0x7b) at index 445
Logged from file exceptions.py, line 724```

**Comment by kalefranz** [comment]
ok then try this...

    export CONDA_VERBOSE=3
    source activate root

**Comment by kalefranz** [comment]
also whatever output you get from 

    export CONDA_JSON=true
    source activate root
    unset CONDA_JSON

might help

**Comment by rcthomas** [comment]
Here's the output for the `CONDA_VERBOSE=3` request:

```$ export CONDA_VERBOSE=3
 $ source activate root
Traceback (most recent call last):
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/cli/main.py", line 111, in main
    return activator_main()
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 557, in main
    print(activator.execute(), end='')
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 149, in execute
    return getattr(self, self.command)()
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 135, in activate
    return self._finalize(self._yield_commands(self.build_activate(self.env_name_or_prefix)),
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 267, in build_activate
    self._update_prompt(set_vars, conda_prompt_modifier)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 456, in _update_prompt
    ps1 = ps1.replace("'", "'\"'\"'")
EncodingError: <unprintable EncodingError object>
$ unset CONDA_VERBOSE
```

And the `CONDA_JSON=true` one gets us back to the unsupported format character:

```$ export CONDA_JSON=true 
 $ source activate root
Traceback (most recent call last):
  File "/Users/rthomas/bug/env/bin/conda", line 11, in <module>
    sys.exit(main())
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/cli/main.py", line 123, in main
    return ExceptionHandler().handle_exception(exc_val, exc_tb)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/exceptions.py", line 775, in handle_exception
    return self.handle_application_exception(EncodingError(exc_val), exc_tb)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/exceptions.py", line 785, in handle_application_exception
    self._print_conda_exception(exc_val, exc_tb)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/exceptions.py", line 790, in _print_conda_exception
    print_conda_exception(exc_val, exc_tb)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/exceptions.py", line 720, in print_conda_exception
    exc_json = json.dumps(exc_val.dump_map(), indent=2, sort_keys=True, cls=EntityEncoder)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/__init__.py", line 64, in dump_map
    message=text_type(self),
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/__init__.py", line 47, in __str__
    return text_type(self.message % self._kwargs)
ValueError: unsupported format character '{' (0x7b) at index 445
```

**Comment by rcthomas** [comment]
Hang on, I'm misleading you.  My prompt is actually a unicode square...  Changing it to some other character, like $, makes it work fine.

**Comment by kalefranz** [comment]
This is the stack trace I needed.

```
Traceback (most recent call last):
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/cli/main.py", line 111, in main
    return activator_main()
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 557, in main
    print(activator.execute(), end='')
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 149, in execute
    return getattr(self, self.command)()
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 135, in activate
    return self._finalize(self._yield_commands(self.build_activate(self.env_name_or_prefix)),
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 267, in build_activate
    self._update_prompt(set_vars, conda_prompt_modifier)
  File "/Users/rthomas/bug/env/lib/python2.7/site-packages/conda/activate.py", line 456, in _update_prompt
    ps1 = ps1.replace("'", "'\"'\"'")
EncodingError: <unprintable EncodingError object>
```

In the meantime, using conda with a python 3 interpreter, and using project-specific environments when you need a python 2 interpreter, is the immediate solution to this problem.  Until I get a fix in.

**Comment by kalefranz** [comment]
Working on fixing #6739 via #6777.  Otherwise I think this issue can be closed.  Can re-open if you disagree.
