### ISSUE TITLE
error when installing seaborn

### ISSUE THREAD

**Issue by CBrauer** [conda/conda#6772]
It said that I consider sending the  following traceback to the conda GitHub issues, so here it is:
```

(C:\Users\Charles\Anaconda3) C:\CNTK-Samples-2-3-1\Tutorials>conda install -c anaconda seaborn
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata .........
Solving package specifications: ..........

Package plan for installation in environment C:\Users\Charles\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    jpeg-8d                    |           vc14_2         177 KB  anaconda
    tk-8.5.18                  |           vc14_0         2.2 MB  anaconda
    zlib-1.2.11                |   vc14h1cdd9ab_1         117 KB  anaconda
    libpng-1.6.32              |   vc14h5163883_3         1.3 MB  anaconda
    libtiff-4.0.6              |           vc14_2         462 KB  anaconda
    freetype-2.8               |   vc14h17c9bdf_0         461 KB  anaconda
    qt-4.8.7                   |           vc14_9        50.5 MB  anaconda
    seaborn-0.8.1              |   py35hc73483e_0         338 KB  anaconda
    ------------------------------------------------------------
                                           Total:        55.6 MB

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h94faf87_0 anaconda
    seaborn:         0.8.1-py35hc73483e_0  anaconda
    vc:              14-h0510ff6_3         anaconda
    yaml:            0.1.7-vc14hb31d195_1  anaconda [vc14]

The following packages will be UPDATED:

    conda:           4.1.6-py35_0                   --> 4.4.7-py35_0           anaconda
    conda-env:       2.5.1-py35_0                   --> 2.6.0-h36134e3_1       anaconda
    freetype:        2.5.5-vc14_1                   --> 2.8-vc14h17c9bdf_0     anaconda [vc14]
    jpeg:            8d-vc14_0                      --> 8d-vc14_2              anaconda [vc14]
    libpng:          1.6.22-vc14_0                  --> 1.6.32-vc14h5163883_3  anaconda [vc14]
    openssl:         1.0.2h-vc14_0                  --> 1.0.2l-vc14hf4c37d5_5  anaconda [vc14]
    pycosat:         0.6.1-py35_1                   --> 0.6.3-py35h456c199_0   anaconda
    pyopenssl:       0.16.0-py35_0                  --> 16.2.0-py35_0          anaconda
    qt:              4.8.7-vc14_8                   --> 4.8.7-vc14_9           anaconda [vc14]
    requests:        2.10.0-py35_0                  --> 2.14.2-py35_0          anaconda
    ruamel_yaml:     0.11.7-py35_0                  --> 0.15.35-py35hfa6e2cd_1 anaconda
    zlib:            1.2.8-vc14_3                   --> 1.2.11-vc14h1cdd9ab_1  anaconda [vc14]

The following packages will be SUPERCEDED by a higher-priority channel:

    libtiff:         4.0.6-vc14_2                   --> 4.0.6-vc14_2           anaconda [vc14]
    tk:              8.5.18-vc14_0                  --> 8.5.18-vc14_0          anaconda [vc14]

Proceed ([y]/n)? y

Pruning fetched packages from the cache ...
Fetching packages ...
jpeg-8d-vc14_2 100% |###############################| Time: 0:00:00 256.58 kB/s
tk-8.5.18-vc14 100% |###############################| Time: 0:00:01   1.53 MB/s
zlib-1.2.11-vc 100% |###############################| Time: 0:00:00 344.12 kB/s
libpng-1.6.32- 100% |###############################| Time: 0:00:01   1.27 MB/s
libtiff-4.0.6- 100% |###############################| Time: 0:00:00 663.89 kB/s
freetype-2.8-v 100% |###############################| Time: 0:00:00 674.10 kB/s
qt-4.8.7-vc14_ 100% |###############################| Time: 0:00:19   2.71 MB/s
seaborn-0.8.1- 100% |###############################| Time: 0:00:00 554.90 kB/s
Extracting packages ...
An unexpected error has occurred, please consider sending the            |   0%
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\Charles\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\cli\main.py", line 120, in main
    exit_code = args_func(args, p)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\cli\main.py", line 130, in args_func
    exit_code = args.func(args, p)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 69, in execute
    install(args, parser, 'install')
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\cli\install.py", line 407, in install
    execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\plan.py", line 600, in execute_actions
    inst.execute_instructions(plan, index, verbose)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\instructions.py", line 136, in execute_instructions
    cmd(state, arg)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\instructions.py", line 59, in EXTRACT_CMD
    extract(arg)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\install.py", line 854, in extract
    exp_backoff_fn(os.rename, temp_path, path)
  File "C:\Users\Charles\Anaconda3\lib\site-packages\conda\install.py", line 240, in exp_backoff_fn
    result = fn(*args)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\Charles\\Anaconda3\\pkgs\\ca-certificates-2017.08.26-h94faf87_0.tmp' -> 'C:\\Users\\Charles\\Anaconda3\\pkgs\\ca-certificates-2017.08.26-h94faf87_0'

(C:\Users\Charles\Anaconda3) C:\CNTK-Samples-2-3-1\Tutorials>conda info
Current conda install:

             platform : win-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 3.5.2.final.0
     requests version : 2.10.0
     root environment : C:\Users\Charles\Anaconda3  (writable)
  default environment : C:\Users\Charles\Anaconda3
     envs directories : C:\Users\Charles\Anaconda3\envs
        package cache : C:\Users\Charles\Anaconda3\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
         offline mode : False
    is foreign system : False


(C:\Users\Charles\Anaconda3) C:\CNTK-Samples-2-3-1\Tutorials>

```

**Comment by kalefranz** [comment]
You're using a *really* old version of conda.  `conda update conda` should help.  If you still have a permissions problem, right click on the Anaconda Prompt, choose "Run as Administrator", and then `conda update conda`.
