### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by sunxing109** [conda/conda#6802]
Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\ProgramData\Anaconda2  (writable)
    default environment : C:\ProgramData\Anaconda2
       envs directories : C:\ProgramData\Anaconda2\envs
                          C:\Users\Administrator\AppData\Local\conda\conda\envs
                          C:\Users\Administrator\.conda\envs
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\Administrator\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/7
Windows/6.1.7601
          administrator : True

`$ C:\ProgramData\Anaconda2\Scripts\conda ..checkenv cmd.exe C:\ProgramData\Anac
onda2`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line
171, in main
        activate.main()
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\activate.py", l
ine 181, in main
        from ..install import symlink_conda
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\install.py", line 3
7, in <module>
        from .core.package_cache import rm_fetched  # NOQA
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\package_cache.
py", line 9, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\path_actions.p
y", line 33, in <module>
        from ..gateways.download import download
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\gateways\download.p
y", line 10, in <module>
        from requests.exceptions import ConnectionError, HTTPError, InvalidSchem
a, SSLError
      File "C:\ProgramData\Anaconda2\lib\site-packages\requests\__init__.py", li
ne 84, in <module>
        from urllib3.contrib import pyopenssl
      File "C:\ProgramData\Anaconda2\lib\site-packages\urllib3\contrib\pyopenssl
.py", line 46, in <module>
        import OpenSSL.SSL
      File "C:\ProgramData\Anaconda2\lib\site-packages\OpenSSL\__init__.py", lin
e 8, in <module>
        from OpenSSL import rand, crypto, SSL
      File "C:\ProgramData\Anaconda2\lib\site-packages\OpenSSL\crypto.py", line
12, in <module>
        from cryptography import x509
      File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\__init_
_.py", line 9, in <module>
        from cryptography.x509.base import (
      File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\base.py
", line 16, in <module>
        from cryptography.x509.extensions import Extension, ExtensionType
      File "C:\ProgramData\Anaconda2\lib\site-packages\cryptography\x509\extensi
ons.py", line 13, in <module>
        from asn1crypto.keys import PublicKeyInfo
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\keys.py", line
 22, in <module>
        from ._elliptic_curve import (
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_elliptic_curv
e.py", line 51, in <module>
        from ._int import inverse_mod
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_int.py", line
 56, in <module>
        from ._perf._big_num_ctypes import libcrypto
      File "C:\ProgramData\Anaconda2\lib\site-packages\asn1crypto\_perf\_big_num
_ctypes.py", line 31, in <module>
        libcrypto_path = find_library('crypto')
      File "C:\ProgramData\Anaconda2\lib\ctypes\util.py", line 53, in find_libra
ry
        fname = os.path.join(directory, name)
      File "C:\ProgramData\Anaconda2\lib\ntpath.py", line 85, in join
        result_path = result_path + p_path
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xcb in position 1: ordi
nal not in range(128)

**Comment by kalefranz** [comment]
We don't support unicode errors when your base environment is python2.  Use Anaconda3, and then use environments for when you need python2.

So, after you install Anaconda 3,

    conda update conda
    conda create -n py2 python=2
    conda activate py2
