### ISSUE TITLE
conda install not working

### ISSUE THREAD

**Issue by swarna97** [conda/conda#6804]
**I'm submitting a...**
  -  bug report
  

## Current Behavior

```
I upgraded my conda package after that conda install is not working.
```
### Steps to Reproduce

```
C:\Users\swarn>conda install -c conda-forge curl
Fetching package metadata ...............
Solving package specifications: .
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.33
       conda is private : False
      conda-env version : 4.3.33
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.3
       root environment : C:\Users\swarn\Anaconda3  (writable)
    default environment : C:\Users\swarn\Anaconda3
       envs directories : C:\Users\swarn\Anaconda3\envs
                          C:\Users\swarn\AppData\Local\conda\conda\envs
                          C:\Users\swarn\.conda\envs
          package cache : C:\Users\swarn\Anaconda3\pkgs
                          C:\Users\swarn\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\swarn\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.33 requests/2.18.3 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : False

`$ C:\Users\swarn\Anaconda3\Scripts\conda-script.py install -c conda-forge curl`




    Traceback (most recent call last):
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\cli\install.py", line 261, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\common\io.py", line 174, in decorated
        return f(*args, **kwds)
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\plan.py", line 492, in install_actions_list
        for specs_by_prefix in required_solves]
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\plan.py", line 492, in <listcomp>
        for specs_by_prefix in required_solves]
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\plan.py", line 681, in get_actions_for_dists
        for dist in sorted(linked):
      File "C:\Users\swarn\Anaconda3\lib\site-packages\conda\models\dist.py", line 227, in __lt__
        return self.__key__() < other.__key__()
    TypeError: '<' not supported between instances of 'NoneType' and 'str'
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
platform : win-64
          conda version : 4.3.33
       conda is private : False
      conda-env version : 4.3.33
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.3
       root environment : C:\Users\swarn\Anaconda3  (writable)
    default environment : C:\Users\swarn\Anaconda3
       envs directories : C:\Users\swarn\Anaconda3\envs
                          C:\Users\swarn\AppData\Local\conda\conda\envs
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
Looks to me that this relates to switching back and forth between conda 4.4 and 4.3 due to conda-forge thrashing.

**Comment by swarna97** [comment]
Thanks for the reply @kalefranz Now the issue is resolved.
