### ISSUE TITLE
Problem with installing Anaconda

### ISSUE THREAD

**Issue by AndreyMalenkov** [conda/conda#6823]
Hi, everyone 

I am begging for help as I can't properly install Anaconda 64 bit on Windows 7 trying desperately multiple times.

Hope that someone would help me to resolve.
Thanks
The error is following:
An unexpected error has occurred.
Traceback (most recent call last):
  File "C:\Continuum\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "C:\Continuum\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "C:\Continuum\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Continuum\lib\site-packages\conda\core\package_cache.py", line 9, in
<module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Continuum\lib\site-packages\conda\core\path_actions.py", line 33, in
<module>
    from ..gateways.download import download
  File "C:\Continuum\lib\site-packages\conda\gateways\download.py", line 10, in
<module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, S
SLError
ModuleNotFoundError: No module named 'requests'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Continuum\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Continuum\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Continuum\lib\site-packages\conda\exceptions.py", line 634, in handle
_exception
    print_unexpected_error_message(e)
  File "C:\Continuum\lib\site-packages\conda\exceptions.py", line 596, in print_
unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Continuum\lib\site-packages\conda\cli\main_info.py", line 162, in get
_info_dict
    from ..connection import user_agent
  File "C:\Continuum\lib\site-packages\conda\connection.py", line 12, in <module
>
    from requests import Session, __version__ as REQUESTS_VERSION
ModuleNotFoundError: No module named 'requests'

C:\Users\xr0204>anaconda install
'anaconda' is not recognized as an internal or external command,operable program or batch file.

C:\Users\xr0204>conda
Traceback (most recent call last):
  File "C:\Continuum\lib\site-packages\conda\exceptions.py", line 640, in conda_
exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Continuum\lib\site-packages\conda\cli\main.py", line 114, in _main
    imported = importlib.import_module(module)
  File "C:\Continuum\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Continuum\lib\site-packages\conda\cli\main_update.py", line 10, in <m
odule>
    from .install import install
  File "C:\Continuum\lib\site-packages\conda\cli\install.py", line 21, in <modul
e>
    from ..core.index import get_index, get_channel_priority_map
  File "C:\Continuum\lib\site-packages\conda\core\index.py", line 8, in <module>

    from .package_cache import PackageCache
  File "C:\Continuum\lib\site-packages\conda\core\package_cache.py", line 9, in
<module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Continuum\lib\site-packages\conda\core\path_actions.py", line 33, in
<module>
    from ..gateways.download import download
  File "C:\Continuum\lib\site-packages\conda\gateways\download.py", line 10, in
<module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, S
SLError
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Continuum\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Continuum\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Continuum\lib\site-packages\conda\exceptions.py", line 644, in conda_
exception_handler
    return handle_exception(e)
  File "C:\Continuum\lib\site-packages\conda\exceptions.py", line 634, in handle
_exception
    print_unexpected_error_message(e)
  File "C:\Continuum\lib\site-packages\conda\exceptions.py", line 596, in print_
unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Continuum\lib\site-packages\conda\cli\main_info.py", line 162, in get
_info_dict
    from ..connection import user_agent
  File "C:\Continuum\lib\site-packages\conda\connection.py", line 12, in <module
>
    from requests import Session, __version__ as REQUESTS_VERSION
ModuleNotFoundError: No module named 'requests'

Thanks

**Comment by kalefranz** [comment]
You've managed to uninstall requests and cripple conda.  Easiest solution is to start with a new miniconda installer.
