### ISSUE TITLE
Error during conda env create -f tfdl_env.yml

### ISSUE THREAD

**Issue by ascentra77** [conda/conda#6829]
<!--
Traceback (most recent call last):
  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    In general, it's not advisable to use 'sudo conda'.
  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda_env\cli\main_create.py", line 108, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda_env\installers\pip.py", line 40, in _pip_install_via_requirements
    args, pip_version = pip_args(prefix)
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ZSOP\P\Anaconda\Scripts\conda-env-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda_env\cli\main.py", line 76, in main

  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    'uid': os.geteuid(),
  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda\exceptions.py", line 634, in handle_exception

  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda\exceptions.py", line 595, in print_unexpected_error_message
    extract_location=extract_location,
  File "C:\ZSOP\P\Anaconda\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from .common import print_envs_list, stdout_json
ImportError: cannot import name 'print_envs_list'

**Comment by kalefranz** [comment]
Please use the template and fill out all sections when filing an issue.
