### ISSUE TITLE
An unexpected error has occurred when I use "conda update conda"

### ISSUE THREAD

**Issue by Ordgod** [conda/conda#6830]
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/jjn/anaconda3  (read only)
    default environment : /home/jjn/anaconda3
       envs directories : /home/jjn/.conda/envs
                          /home/jjn/anaconda3/envs
          package cache : /home/jjn/anaconda3/pkgs
                          /home/jjn/.conda/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/jjn/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-96-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000

`$ /home/jjn/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 464, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 150, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.repodata.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 467, in fetch_repodata
        touch(cache_path)
      File "/home/jjn/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/update.py", line 64, in touch
        utime(path, None)
    PermissionError: [Errno 13] Permission denied

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
sudo chown -R 1000:1000 /home/jjn/anaconda3/pkgs
