### ISSUE TITLE
Unexpected error: conda install pandas

### ISSUE THREAD

**Issue by neigedoi** [conda/conda#6831]
### Steps to Reproduce

```
1. I opened Git Bash, changed dir to Anaconda2, activated virtual env py36 (required me to enter
 "source activate py36" though when I installed libraries two days ago in an Anaconda command 
window I only entered "active py36").
2. $ conda install pandas
3. Install seemed to work, download reached 100%, then error message below. 

But pandas folders and files were installed in 
C:\Users\karls\Anaconda2\envs\py36\Lib\site-packages\pandas and
C:\Users\karls\Anaconda2\envs\py36\Lib\site-packages\pandas-0.22.0-py3.6.egg-info.

karls@DESKTOP-VAQRJL8 MINGW64 ~/anaconda2
$ activate py36
Error: activate must be sourced. Run 'source activate envname'
instead of 'activate envname'.

karls@DESKTOP-VAQRJL8 MINGW64 ~/anaconda2
$ source activate py36
(py36)
karls@DESKTOP-VAQRJL8 MINGW64 ~/anaconda2
$ conda install pandas
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\karls\Anaconda2\envs\py36:

The following NEW packages will be INSTALLED:

    pandas: 0.22.0-py36h6538335_0

Proceed ([y]/n)? y

pandas-0.22.0- 100% |###############################| Time: 0:00:10 904.97 kB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : C:\Users\karls\Anaconda2  (writable)
    default environment : C:\Users\karls\Anaconda2\envs\py36
       envs directories : C:\Users\karls\Anaconda2\envs
                          C:\Users\karls\AppData\Local\conda\conda\envs
                          C:\Users\karls\.conda\envs
          package cache : C:\Users\karls\Anaconda2\pkgs
                          C:\Users\karls\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\karls\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False

`$ C:\Users\karls\Anaconda2\Scripts\conda install pandas`

    Traceback (most recent call last):
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\cli\install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\instructions.py", line 95, in SYMLINK_CONDA_CMD
        symlink_conda(prefix, arg)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\install.py", line 113, in symlink_conda
        symlink_conda_hlp(prefix, root_dir, where, symlink_fn)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\install.py", line 130, in symlink_conda_hlp
        symlink_fn(root_file, prefix_file)
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\install.py", line 86, in win_conda_bat_redirect
        with open(dst, "w") as f:
      File "C:\Users\karls\Anaconda2\lib\site-packages\conda\common\compat.py", line 118, in open
        closefd=closefd)
    IOError: [Errno 13] Permission denied: u'C:\\Users\\karls\\Anaconda2\\envs\\py36\\Scripts\\conda'
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(py36)
karls@DESKTOP-VAQRJL8 MINGW64 ~/anaconda2
$ conda info
bash: /c/Users/karls/Anaconda2/envs/py36/Scripts/conda: No such file or directory
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
bash: /c/Users/karls/Anaconda2/envs/py36/Scripts/conda: No such file or directory
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
bash: /c/Users/karls/Anaconda2/envs/py36/Scripts/conda: No such file or directory
```
</p></details>

**Comment by kalefranz** [comment]
Git Bash isn't supported in conda 4.3.  Update to conda 4.4.
