### ISSUE TITLE
ModuleNotFoundError: No module named 'conda'

### ISSUE THREAD

**Issue by UtilityDave** [conda/conda#6835]
**I'm submitting a...**
  - [X ] bug report
  - [ ] feature request

## Current Behavior
hi, I've uninstalled, and reinstalled anaconda upwards of 10 times in the last two days - yesterday it stopped working (I tried to install kivy on my regular python install, think if I pip'd it over there I would be able to use it in spyder - figured out that's not a thing, went into spyder, tweaked with the python path menu, thinking I could use the other python as my python path, and the modules installed with it would be rendered (did not work) then all of a sudden ipython couldn't connect to kernel, I told it to reset all settings to default, then it crashed, wouldn't relaunch spyder - then I couldn't relaunch the anaconda navigator or command line - so uninstall number 1 happened, I tried reinstalling (Thinking everything would be fine) and it didn't even give me this much (Told me activate.bat was not a valid command when I tried to run anaconda prompt, and when I tried to run the navigator bupkiss) Uninstalled, and tried all the variations of install settings, this time I tried manually replacing the files it said it was missing, and this is as far as I've gotten because I cannot find a conda.cli file, and don't know where to put it based on the code in referenced file (Assume in scripts) 

I am very new at all of this.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 6, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

C:\Users\Utility>import conda
'import' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Utility>conda.__version__
'conda.__version__' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Utility>conda
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 6, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

C:\Users\Utility>pydoc conda
No Python documentation found for 'conda'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

C:\Users\Utility>help(conda)
This command is not supported by the help utility.  Try "(conda) /?".

C:\Users\Utility>conda /?
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\conda-script.py", line 6, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

### Steps to Reproduce

See above.
```

```

## Expected Behavior
that I would be able to install and use anaconda

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

Windows 10? 
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by UtilityDave** [comment]
similar to issue #2463 btw!

**Comment by UtilityDave** [comment]
okay did a "Reset" on windows 10 - uninstalled everything, reinstalled Anaconda - still broken - prompt is back to giving me 
'C:\ProgramData\Anaconda3\Scripts\activate.bat' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Utility>

**Comment by UtilityDave** [comment]
Okay, there were some folders in user\utility (.ipython, .spyder, a few others I can't remember) that I deleted, and then reinstalled again, and it worked this time. it looks like the uninstall didn't catch them when removing the program any of the times I ran it - neither did revo or any of the other uninstallers, might be a bug or error between keyboard and chair.

**Comment by UtilityDave** [comment]
Thank you!

On Feb 6, 2018 13:32, "Kale Franz" <notifications@github.com> wrote:

Closed #6835 <https://github.com/conda/conda/issues/6835>.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/conda/conda/issues/6835#event-1461093832>, or mute the
thread
