### ISSUE TITLE
issues when I try to use jupyter notebook

### ISSUE THREAD

**Issue by masafumiendo** [conda/conda#6839]
How to solve this situation?

I tried to use jupyter notebook in anaconda, so type `jupyter notebook`.
Then, terminal shows below

```python
Traceback (most recent call last):
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/notebook/notebookapp.py",line 32, in <module>
    from zmq.eventloop import ioloop
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 35, in <module>
    from tornado.ioloop import PollIOLoop, PeriodicCallback
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/tornado/ioloop.py", line 46, in <module>
    from tornado.concurrent import TracebackFuture, is_future
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/tornado/concurrent.py", line 37, in <module>
    from concurrent import futures
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/concurrent/futures/__init__.py", line 8, in <module>
    from concurrent.futures._base import (FIRST_COMPLETED,
  File "/home/endo/.pyenv/versions/anaconda3-2.5.0/lib/python3.5/site-packages/concurrent/futures/_base.py", line 355
    raise type(self._exception), self._exception, self._traceback
                               ^
SyntaxError: invalid syntax
```

My anaconda `info` is

```python
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 3.19.1
  conda-build version : 1.19.0
       python version : 3.5.1.final.0
     requests version : 2.9.1
     root environment : /home/endo/.pyenv/versions/anaconda3-2.5.0  (writable)
  default environment : /home/endo/.pyenv/versions/anaconda3-2.5.0
     envs directories : /home/endo/.pyenv/versions/anaconda3-2.5.0/envs
        package cache : /home/endo/.pyenv/versions/anaconda3-2.5.0/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

Also, I tried to update anaconda and use `conda update conda`, but my request was rejected.

**Comment by kalefranz** [comment]
conda 3.19.1 is ancient, and no longer supported.  If your request was rejected, it's probably because you have an expired cert bundle.

**Comment by masafumiendo** [comment]
Thanks for your reply.

So, do I need to install the latest conda/anaconda?
