### ISSUE TITLE
Bug involving SHA256 verification

### ISSUE THREAD

**Issue by davinderc** [conda/conda#6844]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I downloaded an education kit from https://github.com/udacity/FCND-Term1-Starter-Kit.git and tried to install the conda packages with the .yml file there. In the middle of the download, an error occurs that directs me to post here. It seems there is a sha256 validation that cannot be completed. 

### Steps to Reproduce
Below is the output. I'm running on Ubuntu 16.04.
```
FCND-Term1-Starter-Kit $ conda env create -f environment.yml
Fetching package metadata ...........
Solving package specifications: .
ca-certificate 100% |################################| Time: 0:00:00 213.69 kB/s
expat-2.2.5-0. 100% |################################| Time: 0:00:00 887.61 kB/s
icu-58.2-0.tar 100% |################################| Time: 0:00:16   1.48 MB/s
jpeg-9b-2.tar. 100% |################################| Time: 0:00:01 984.21 kB/s
libiconv-1.15- 100% |################################| Time: 0:00:02 976.59 kB/s
libsodium-1.0. 100% |################################| Time: 0:00:01 930.68 kB/s
tk-8.6.7-0.tar 100% |################################| Time: 0:00:03 961.37 kB/s
xz-5.2.3-0.tar 100% |################################| Time: 0:00:01 695.06 kB/s
dbus-1.10.22-0 100% |################################| Time: 0:00:03 487.88 kB/s
glib-2.55.0-0. 100% |################################| Time: 0:00:13 659.95 kB/s
libpng-1.6.34- 100% |################################| Time: 0:00:00 550.88 kB/s
libxml2-2.9.7- 100% |################################| Time: 0:00:06 835.56 kB/s
openssl-1.0.2n 100% |################################| Time: 0:00:04 876.41 kB/s
pandoc-2.1.1-0 100% |################################| Time: 0:00:19   1.14 MB/s
readline-7.0-0 100% |################################| Time: 0:00:00 892.76 kB/s
freetype-2.8.1 100% |################################| Time: 0:00:02   1.24 MB/s
gstreamer-1.8. 100% |################################| Time: 0:00:02   1.28 MB/s
sqlite-3.20.1- 100% |################################| Time: 0:00:01 965.29 kB/s
fontconfig-2.1 100% |################################| Time: 0:00:02 463.60 kB/s
python-3.6.3-4 100% |################################| Time: 0:00:18   1.11 MB/s
backports-1.0- 100% |################################| Time: 0:00:00  24.56 kB/s
certifi-2017.1 100% |################################| Time: 0:00:00 230.93 kB/s
decorator-4.1. 100% |################################| Time: 0:00:00   1.69 MB/s
entrypoints-0. 100% |################################| Time: 0:00:00   4.89 MB/s
ipython_genuti 100% |################################| Time: 0:00:00 204.33 kB/s
jsonschema-2.6 100% |################################| Time: 0:00:00 183.23 kB/s
markupsafe-1.0 100% |################################| Time: 0:00:00 185.76 kB/s
mistune-0.8.3- 100% |################################| Time: 0:00:00  95.39 kB/s
numpy-1.13.1-p 100% |################################| Time: 0:00:04   1.71 MB/s
pandocfilters- 100% |################################| Time: 0:00:00   2.92 MB/s
parso-0.1.1-py 100% |################################| Time: 0:00:00 176.62 kB/s
pickleshare-0. 100% |################################| Time: 0:00:00   2.48 MB/s
ptyprocess-0.5 100% |################################| Time: 0:00:00 126.96 kB/s
pyparsing-2.2. 100% |################################| Time: 0:00:00 190.72 kB/s
pytz-2017.3-py 100% |################################| Time: 0:00:00 402.11 kB/s
pyzmq-16.0.2-p 100% |################################| Time: 0:00:01 853.77 kB/s
qt-5.6.2-7.tar 100% |################################| Time: 0:00:32   1.41 MB/s
send2trash-1.4 100% |################################| Time: 0:00:00   2.48 MB/s
simplegeneric- 100% |################################| Time: 0:00:00   1.10 MB/s
sip-4.18-py36_ 100% |################################| Time: 0:00:00 316.05 kB/s
six-1.11.0-py3 100% |################################| Time: 0:00:00   2.33 MB/s
testpath-0.3.1 100% |################################| Time: 0:00:00 267.29 kB/s
tornado-4.5.3- 100% |################################| Time: 0:00:01 526.37 kB/s
wcwidth-0.1.7- 100% |################################| Time: 0:00:00   2.03 MB/s
webencodings-0 100% |################################| Time: 0:00:00   2.00 MB/s
cycler-0.10.0- 100% |################################| Time: 0:00:00  84.19 kB/s
html5lib-1.0.1 100% |################################| Time: 0:00:00 178.79 kB/s
jedi-0.11.1-py 100% |################################| Time: 0:00:00 439.37 kB/s
pexpect-4.3.1- 100% |################################| Time: 0:00:00 427.42 kB/s
pyqt-5.6.0-py3 100% |################################| Time: 0:00:03   1.55 MB/s
python-dateuti 100% |################################| Time: 0:00:00 649.23 kB/s
setuptools-38. 100% |################################| Time: 0:00:01 379.98 kB/s
terminado-0.8. 100% |################################| Time: 0:00:00 553.95 kB/s
traitlets-4.3. 100% |################################| Time: 0:00:00 258.97 kB/s
backports.func 100% |################################| Time: 0:00:00   2.33 MB/s
bleach-2.0.0-p 100% |################################| Time: 0:00:00 121.79 kB/s
jinja2-2.10-py 100% |################################| Time: 0:00:00 271.45 kB/s
jupyter_core-4 100% |################################| Time: 0:00:00 257.42 kB/s
pygments-2.2.0 100% |################################| Time: 0:00:01 798.18 kB/s
wheel-0.30.0-p 100% |################################| Time: 0:00:00   4.50 MB/s
jupyter_client 100% |################################| Time: 0:00:00 384.12 kB/s
matplotlib-2.1 100% |################################| Time: 0:00:09   1.09 MB/s
nbformat-4.4.0 100% |################################| Time: 0:00:00 779.02 kB/s
pip-9.0.1-py36 100% |################################| Time: 0:00:01 888.74 kB/s
prompt_toolkit 100% |################################| Time: 0:00:00 603.66 kB/s
ipython-6.2.1- 100% |################################| Time: 0:00:01 809.82 kB/s
nbconvert-5.3. 100% |################################| Time: 0:00:00 487.46 kB/s
ipykernel-4.8. 100% |################################| Time: 0:00:00 423.64 kB/s
jupyter_consol 100% |################################| Time: 0:00:00   1.88 MB/s
notebook-5.4.0 100% |################################| Time: 0:00:07 885.29 kB/s
qtconsole-4.3. 100% |################################| Time: 0:00:00 734.35 kB/s
widgetsnbexten 100% |################################| Time: 0:00:02 853.79 kB/s
ipywidgets-7.1 100% |################################| Time: 0:00:00 400.70 kB/s
jupyter-1.0.0- 100% |################################| Time: 0:00:00 287.03 kB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.18.4
       root environment : /home/controlfreak/miniconda3  (writable)
    default environment : /home/controlfreak/miniconda3
       envs directories : /home/controlfreak/miniconda3/envs
          package cache : /home/controlfreak/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.4 requests/2.18.4 CPython/3.5.2 Linux/4.13.0-32-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000



`$ /home/controlfreak/miniconda3/bin/conda-env create -f environment.yml`




    Traceback (most recent call last):
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda_env/cli/main_create.py", line 112, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda_env/installers/conda.py", line 37, in install
        plan.execute_actions(actions, index, verbose=not args.quiet)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 120, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/core/link.py", line 120, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/controlfreak/miniconda3/lib/python3.5/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for sha256 cannot be None.


```

## Expected Behavior
I think the environment should be installed with a success message.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.4
       conda is private : False
      conda-env version : 4.3.4
    conda-build version : not installed
         python version : 3.5.2.final.0
       requests version : 2.18.4
       root environment : /home/controlfreak/miniconda3  (writable)
    default environment : /home/controlfreak/miniconda3
       envs directories : /home/controlfreak/miniconda3/envs
          package cache : /home/controlfreak/miniconda3/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.4 requests/2.18.4 CPython/3.5.2 Linux/4.13.0-32-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

Nothing appears when I run 'conda config --show-sources'
```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
FCND-Term1-Starter-Kit $ conda list --show-channel-urls
# packages in environment at /home/controlfreak/miniconda3:
#
appdirs                   1.4.3                     <pip>
arrow                     0.10.0                    <pip>
certifi                   2017.7.27.1               <pip>
cffi                      1.9.1                    py35_0    defaults
chardet                   3.0.4                     <pip>
click                     6.7                       <pip>
conda                     4.3.4                    py35_0    defaults
conda-env                 2.6.0                         0    defaults
cryptography              1.7.1                    py35_0    defaults
floyd-cli                 0.8.3                     <pip>
gi                        1.2                       <pip>
idna                      2.6                       <pip>
idna                      2.2                      py35_0    defaults
libffi                    3.2.1                         1    defaults
marshmallow               2.13.0                    <pip>
openssl                   1.0.2j                        0    defaults
pip                       9.0.1                     <pip>
pip                       8.1.2                    py35_0    defaults
praw                      5.1.0                     <pip>
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.17                     py35_0    defaults
pycrypto                  2.6.1                    py35_4    defaults
pyopenssl                 16.2.0                   py35_0    defaults
python                    3.5.2                         0    defaults
pytz                      2016.10                   <pip>
readline                  6.2                           2    defaults
requests                  2.12.4                   py35_0    defaults
requests                  2.18.4                    <pip>
ruamel_yaml               0.11.14                  py35_0    defaults
setuptools                27.2.0                   py35_0    defaults
shortuuid                 0.5.0                     <pip>
six                       1.10.0                   py35_0    defaults
six                       1.11.0                    <pip>
sqlite                    3.13.0                        0    defaults
tabulate                  0.7.7                     <pip>
tk                        8.5.18                        0    defaults
tornado                   4.5.2                     <pip>
urllib3                   1.22                      <pip>
wheel                     0.29.0                   py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults

```
</p></details>

**Comment by kalefranz** [comment]
You're using a really old version of conda.  Please `conda update conda`.
