### ISSUE TITLE
KeyError while creating environment

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6846]
OS: Windows 10
Anaconda2/3 ( 32bit )-5.1.0

Steps to repro : 
- Install anaconda as all user
- Run anaconda-prompt 
- Run below command

Actual Result : Error while creating environment

````bash
(base) C:\Users\tester>conda create -n test-env python=3
Solving environment: done

## Package Plan ##

  environment location: C:\Users\tester\AppData\Local\conda\conda\envs\test-env

  added / updated specs:
    - python=3


The following packages will be downloaded:


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 772, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main_create.py", line 11, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 255, in install
        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\install.py", line 272, in handle_txn
        unlink_link_transaction.display_actions(progressive_fetch_extract)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\core\link.py", line 711, in display_actions
        specs_to_remove=stp.remove_specs, specs_to_add=stp.update_specs)
      File "C:\ProgramData\Anaconda2\lib\site-packages\conda\plan.py", line 97, in display_actions
        info = index[dist]
    KeyError: Dist(channel=u'<unknown>', dist_name=u'vs2015_runtime-14.0.25123-3', name=u'vs2015_runtime', version=u'14.0.25123', build_string=u'3', build_number=3, base_url=u'file:///C:/ProgramData/Anaconda2/pkgs', platform=None)

`$ C:\ProgramData\Anaconda2\Scripts\conda create -n test-env python=3`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=C:\ProgramData\Anaconda2
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda2\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda2
              CONDA_SHLVL=1
                 HOMEPATH=\Users\tester
                     PATH=C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\Li
                          brary\bin;C:\ProgramData\Anaconda2\Scripts;C:\ProgramData\Anaconda2\bi
                          n;C:\ProgramData\Anaconda2;C:\ProgramData\Anaconda2\Library\mingw-w64\
                          bin;C:\ProgramData\Anaconda2\Library\usr\bin;C:\ProgramData\Anaconda2\
                          Library\bin;C:\ProgramData\Anaconda2\Scripts;C:\WINDOWS\system32;C:\WI
                          NDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v
                          1.0\;C:\Users\tester\AppData\Local\Microsoft\WindowsApps;;C:\Program
                          Files\Microsoft VS Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\ProgramData\Anaconda2
            shell level : 1
       user config file : C:\Users\tester\.condarc
 populated config files : C:\Users\tester\.condarc
          conda version : 4.4.8
    conda-build version : 3.4.0
         python version : 2.7.14.final.0
       base environment : C:\ProgramData\Anaconda2  (read only)
           channel URLs : https://repo.continuum.io/pkgs/main/win-32
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda2\pkgs
                          C:\Users\tester\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\tester\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda2\envs
                          C:\Users\tester\.conda\envs
               platform : win-32
             user-agent : conda/4.4.8 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
````

T406135: Verify by running `conda create -y -n test-env python=3`command.
https://continuumanalytics.testrail.com/index.php?/tests/view/406135

**Comment by travishathaway** [comment]
I think this issue too old to be adequately resolved. I went looking through the source code and could not find the corresponding line this was raised on. Plus, it's for an older version of Python that is no longer supported.
