### ISSUE TITLE
Broken pip is used with conda env create

### ISSUE THREAD

**Issue by cdeil** [conda/conda#6879]
I'm submitting a bug report.

I'm still getting this error discussed in the closed issues https://github.com/conda/conda/issues/6626 and https://github.com/pypa/setuptools/issues/885 (and several others).

I think maybe the problem is that the pip in the env that is being created is not installed at a recent version before attempting to do the pip install at the bottom of the env file?

Is there a fix or workaround?

## Current Behavior

I'm getting this error:

```
$ conda env install -f environment-dev.yml
usage: conda-env [-h] {attach,create,export,list,remove,upload,update} ...
conda-env: error: invalid choice: 'install' (choose from 'attach', 'create', 'export', 'list', 'remove', 'upload', 'update')
eduroam-3-163:gammapy deil$ conda env create -f environment-dev.yml

CondaValueError: prefix already exists: /Users/deil/software/anaconda3/anaconda3/envs/gammapy-dev

eduroam-3-163:gammapy deil$ conda env create -f environment-dev.yml
Fetching package metadata .................
Solving package specifications: .
Warning: 2 possible package resolutions (only showing differing packages):
  - conda-forge::libgfortran-3.0.0-0, defaults::libgcc-4.8.5-1
  - defaults::libgcc-4.8.5-hdbeacc1_10, defaults::libgfortran-3.0.1-h93005f0_2
Traceback (most recent call last):
  File "/Users/deil/software/anaconda3/anaconda3/envs/gammapy-dev/bin/pip", line 4, in <module>
    import pip
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/__init__.py", line 26, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 27, in <module>
    from pip._vendor import pkg_resources
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3018, in <module>
    @_call_aside
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3004, in _call_aside
    f(*args, **kwargs)
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3046, in _initialize_master_working_set
    dist.activate(replace=False)
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2578, in activate
    declare_namespace(pkg)
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2152, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2092, in _handle_ns
    _rebuild_mod_path(path, packageName, module)
  File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2121, in _rebuild_mod_path
    orig_path.sort(key=position_in_sys_path)
AttributeError: '_NamespacePath' object has no attribute 'sort'
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : osx-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.0.22
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/deil/software/anaconda3/anaconda3  (writable)
    default environment : /Users/deil/software/anaconda3/anaconda3
       envs directories : /Users/deil/software/anaconda3/anaconda3/envs
                          /Users/deil/.conda/envs
          package cache : /Users/deil/software/anaconda3/anaconda3/pkgs
                          /Users/deil/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/deil/.condarc
             netrc file : /Users/deil/.netrc
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3    
                UID:GID : 501:20

`$ /Users/deil/software/anaconda3/anaconda3/bin/conda-env create -f environment-dev.yml`




    Traceback (most recent call last):
      File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
      File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/site-packages/conda_env/pip_util.py", line 32, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/Users/deil/software/anaconda3/anaconda3/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/Users/deil/software/anaconda3/anaconda3/envs/gammapy-dev/bin/python', '/Users/deil/software/anaconda3/anaconda3/envs/gammapy-dev/bin/pip', '-V']' returned non-zero exit status 1.
```

### Steps to Reproduce

```
git clone https://github.com/gammapy/gammapy.git
cd gammapy
conda env create -f environment-dev.yml
```

The `environment-dev.yml` is this version: https://github.com/gammapy/gammapy/blob/4c2dde09cb76592b057fe10cbae46bf7090f9352/environment-dev.yml

## Expected Behavior

I was expecting conda to first install a working version of pip, because I have the `pip` section in my environment file.

## Environment Information

<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info
Current conda install:

               platform : osx-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 3.0.22
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/deil/software/anaconda3/anaconda3  (writable)
    default environment : /Users/deil/software/anaconda3/anaconda3
       envs directories : /Users/deil/software/anaconda3/anaconda3/envs
                          /Users/deil/.conda/envs
          package cache : /Users/deil/software/anaconda3/anaconda3/pkgs
                          /Users/deil/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/deil/.condarc
             netrc file : /Users/deil/.netrc
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.4 CPython/3.6.3 Darwin/17.4.0 OSX/10.13.3    
                UID:GID : 501:20
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /Users/deil/.condarc <==
ssl_verify: True
channels:
  - conda-forge
  - anaconda-fusion
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /Users/deil/software/anaconda3/anaconda3:
#
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0    defaults
alabaster                 0.7.10           py36h174008c_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.6.5            py36h04cfe59_0    defaults
anaconda-navigator        1.6.9            py36ha31b149_0    defaults
anaconda-project          0.8.0            py36h99320b2_0    defaults
aplpy                     1.1.1                    py36_0    conda-forge
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h9e71e49_1    defaults
arrow-cpp                 0.7.1                    py36_2    conda-forge
asn1crypto                0.22.0           py36hb705621_1    defaults
astroid                   1.5.3            py36h1333018_0    defaults
astropy                   2.0.2            py36hf79c81d_4    defaults
astropy-healpix           0.2                      py36_0    conda-forge
babel                     2.5.0            py36h9f161ff_0    defaults
backports                 1.0              py36ha3c1827_1    defaults
backports.functools_lru_cache 1.4                      py36_1    conda-forge
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bitarray                  0.8.1            py36h20fa61d_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blaze                     0.11.3           py36h02e7a37_0    defaults
bleach                    2.0.0            py36h8fcea71_0    defaults
bokeh                     0.12.10          py36hfd5be35_0    defaults
boto                      2.48.0           py36hdbc59ac_1    defaults
bottleneck                1.2.1            py36hbd380ad_0    defaults
bzip2                     1.0.6                h92991f9_1    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2017.7.27.1      py36hd973bb6_0    defaults
cffi                      1.10.0           py36h880867e_1    defaults
cfitsio                   3.410                         2    conda-forge
chardet                   3.0.4            py36h96c241c_1    defaults
click                     6.7              py36hec950be_0    defaults
cloudpickle               0.4.0            py36h13b7e56_0    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
colorama                  0.3.9            py36hd29a30c_0    defaults
conda                     4.3.34                   py36_0    conda-forge
conda-build               3.0.22           py36hcb85c65_0    defaults
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0            py36he837df3_0    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
corner                    2.0.1                    py36_0    conda-forge
cryptography              2.0.3            py36h22d4226_1    defaults
ctools                    1.5.0            py36h2ee17f1_1    cta-observatory
curl                      7.55.1               h7601780_3    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cython                    0.26.1           py36hd51f8eb_0    defaults
cytoolz                   0.8.2            py36h290905f_0    defaults
dask                      0.15.3           py36hc3ad2d6_0    defaults
dask-core                 0.15.3           py36hc0be6b7_0    defaults
datashape                 0.5.4            py36hfb22df8_0    defaults
dbus                      1.10.22              h50d9ad6_0    defaults
decorator                 4.1.2            py36h69a1b52_0    defaults
distributed               1.19.1           py36h4ae75d2_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
emcee                     2.2.1                    py36_3    conda-forge
entrypoints               0.2.3            py36hd81d71f_2    defaults
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.4                h8f26bf8_1    defaults
fastcache                 1.0.2            py36h8606a76_0    defaults
filelock                  2.0.12           py36h0d0b4fb_0    defaults
flask                     0.12.2           py36h5658096_0    defaults
flask-cors                3.0.3            py36h7387b97_0    defaults
freetype                  2.7                           1    conda-forge
gammalib                  1.5.0            py36h903b005_1    cta-observatory
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             hb0f4f8b_2    defaults
gevent                    1.2.2            py36ha70b9d6_0    defaults
glib                      2.53.6               ha08cb78_1    defaults
glob2                     0.5              py36h12393a9_0    defaults
gmp                       6.1.2                h4a9834d_0    defaults
gmpy2                     2.0.8            py36h7ef02cb_1    defaults
greenlet                  0.4.12           py36hf09ba7b_0    defaults
h5py                      2.7.0            py36h6400cee_1    defaults
hdf5                      1.10.1               h6090a45_0    defaults
healpy                    1.11.0              np113py36_0    conda-forge
heapdict                  1.0.0            py36h27a9ac6_0    defaults
hips                      0.2                      py36_0    conda-forge
html5lib                  0.999999999      py36h79312fd_0    defaults
icu                       58.2                 hea21ae5_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
imageio                   2.2.0            py36h5e01289_0    defaults
imagesize                 0.7.1            py36h3495948_0    defaults
iminuit                   1.2                      py36_0    conda-forge
intel-openmp              2018.0.0             h68bdfb3_7    defaults
ipykernel                 4.6.1            py36h3208c25_0    defaults
ipython                   6.1.0            py36hf612aae_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.0.0            py36h24d3910_0    defaults
isort                     4.2.15           py36hceb2a01_0    defaults
itsdangerous              0.24             py36h49fbb8d_1    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.3              py36h1986823_0    defaults
jedi                      0.10.2           py36h6325097_0    defaults
jinja2                    2.9.6            py36hde4beb4_1    defaults
jpeg                      9b                   haccd157_1    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter_client            5.1.0            py36hf6c435f_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.3.0            py36h93810fe_0    defaults
jupyterlab                0.31.2                   py36_0    conda-forge
jupyterlab_launcher       0.10.3                   py36_0    conda-forge
keras                     2.0.6                    py36_0    conda-forge
lazy-object-proxy         1.3.1            py36h2fbbe47_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                hd939716_3    defaults
libgcc                    4.8.5               hdbeacc1_10    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 h99df5da_5    defaults
libpng                    1.6.32               hce72d48_2    defaults
libsodium                 1.0.13               hba5e272_2    defaults
libssh2                   1.8.0                h1218725_2    defaults
libtiff                   4.0.7                         1    conda-forge
libxml2                   2.9.4                hbd0960b_5    defaults
libxslt                   1.1.29               h95a2935_5    defaults
llvmlite                  0.20.0                   py36_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lockfile                  0.12.2                   py36_0    conda-forge
luigi                     2.7.1                    py36_0    conda-forge
lxml                      4.1.0            py36h8179fc0_0    defaults
lzo                       2.10                 hb6b8854_1    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.0                    py36_0    conda-forge
mccabe                    0.6.1            py36hdaeb55d_0    defaults
mistune                   0.7.4            py36hccd6237_0    defaults
mkl                       2018.0.0             h5ef208c_6    defaults
mkl-service               1.1.2            py36h7ea6df4_4    defaults
mock                      2.0.0                    py36_0    conda-forge
mpc                       1.0.3                hc455b36_4    defaults
mpfr                      3.1.5                h7fa3772_1    defaults
mpmath                    0.19             py36h9185fea_2    defaults
msgpack-python            0.4.8            py36h46767b2_0    defaults
multipledispatch          0.4.9            py36hc5f92b5_0    defaults
naima                     0.8.1                    py36_0    conda-forge
navigator-updater         0.1.0            py36h7aee5fb_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
nbsphinx                  0.2.14                   py36_0    conda-forge
ncurses                   6.0                  ha932d30_1    defaults
networkx                  2.0              py36hefccab9_0    defaults
nltk                      3.2.4            py36h27d1ea0_0    defaults
nose                      1.3.7            py36h73fae2b_2    defaults
notebook                  5.0.0            py36h462289e_2    defaults
numba                     0.35.0              np113py36_6    defaults
numexpr                   2.6.2            py36h0f4f1da_1    defaults
numpy                     1.13.3           py36h2cdce51_0    defaults
numpydoc                  0.7.0            py36he54d08e_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.44             py36ha08bf50_0    defaults
openpyxl                  2.4.8            py36he899640_1    defaults
openssl                   1.0.2l               h57f3a61_2    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandas                    0.20.3           py36hd6655d8_2    defaults
pandoc                    2.0.0.1                       1    conda-forge
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parquet-cpp               1.3.0.post                    2    conda-forge
partd                     0.3.8            py36hf5c4cb8_0    defaults
path.py                   10.3.1           py36hd33c240_0    defaults
pathlib2                  2.3.0            py36h877a6d8_0    defaults
patsy                     0.4.1            py36ha1b3fa5_0    defaults
pbr                       3.1.1                    py36_0    conda-forge
pcre                      8.41                 h29eefc5_0    defaults
pep8                      1.7.0            py36hc268eb1_0    defaults
pexpect                   4.2.1            py36h3eac828_0    defaults
photutils                 0.4                      py36_0    conda-forge
pickleshare               0.7.4            py36hf512f8e_0    defaults
pillow                    4.3.0                    py36_1    conda-forge
pip                       9.0.1            py36hbd95645_3    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
ply                       3.10             py36h10e714e_0    defaults
prompt_toolkit            1.0.15           py36haeda067_0    defaults
protobuf                  3.3.2                    py36_0    conda-forge
psutil                    5.4.0            py36ha052210_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
py                        1.4.34           py36hecf431b_1    defaults
py4j                      0.10.6                   py36_1    conda-forge
pyarrow                   0.7.1                    py36_1    conda-forge
pycodestyle               2.3.1            py36h83e8646_0    defaults
pycosat                   0.6.2            py36h1486600_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pycurl                    7.43.0           py36hdb90038_3    defaults
pyflakes                  1.6.0            py36hea45e83_0    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pylint                    1.7.4            py36hdee9077_0    defaults
pyodbc                    4.0.17           py36h5478161_0    defaults
pyopenssl                 17.2.0           py36h5d7bf08_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pyregion                  2.0                      py36_0    conda-forge
pysocks                   1.6.7            py36hfa33cec_1    defaults
pyspark                   2.2.0                    py36_0    conda-forge
pytables                  3.4.2            py36hfbd7ab0_2    defaults
pytest                    3.2.1            py36h9963153_1    defaults
pytest-runner             3.0                        py_0    conda-forge
python                    3.6.3                h6804ab2_0    defaults
python-daemon             2.1.2                    py36_0    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h7fe2238_6    defaults
pytz                      2017.2           py36h2e7dfbc_1    defaults
pywavelets                0.5.2            py36h2710a04_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.2           py36h087ffad_2    defaults
qt                        5.6.2               h9975529_14    defaults
qtawesome                 0.4.4            py36h468c6fb_0    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
qtpy                      1.3.1            py36h16bb863_0    defaults
readline                  7.0                  h81b24a6_3    defaults
regions                   0.2                      py36_0    conda-forge
reproject                 0.3.1               np113py36_0    conda-forge
requests                  2.18.4           py36h4516966_1    defaults
rope                      0.10.5           py36h5764ad1_0    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
scikit-image              0.13.0           py36h398857d_1    defaults
scikit-learn              0.19.1           py36hffbff8c_0    defaults
scikit-optimize           0.3                      py36_0    conda-forge
scipy                     0.19.1           py36h3e758e1_3    defaults
seaborn                   0.8.0            py36h74df97e_0    defaults
setuptools                36.5.0           py36h2134326_0    defaults
sherpa                    4.9.1                    py36_0    sherpa
simplegeneric             0.8.1            py36he5b5b09_0    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         0.5.3            py36he9c3ed6_0    defaults
sortedcontainers          1.5.7            py36ha982688_0    defaults
sphinx                    1.6.5                    py36_0    conda-forge
sphinx_rtd_theme          0.2.4                    py36_0    conda-forge
sphinxcontrib             1.0              py36h9364dc8_1    defaults
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1    defaults
spyder                    3.2.4            py36h908396f_0    defaults
sqlalchemy                1.1.13           py36h156b851_0    defaults
sqlite                    3.20.1               h900c3b0_1    defaults
statsmodels               0.8.0            py36h9c68fc9_0    defaults
sympy                     1.1.1            py36h7f3cf04_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
tensorflow                1.0.0                    py36_0    conda-forge
terminado                 0.6              py36h656782e_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.6.7                hcdce994_1    defaults
toolz                     0.8.2            py36h7b95164_0    defaults
tornado                   4.5.2            py36h468dda9_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typing                    3.6.2            py36haa2d9ef_0    defaults
uncertainties             3.0.1                    py36_0    conda-forge
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.4                h4cb4dde_1    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
werkzeug                  0.12.2           py36h168efa1_0    defaults
wheel                     0.29.0           py36h3597b6d_1    defaults
widgetsnbextension        3.0.2            py36h91f43ea_1    defaults
wrapt                     1.10.11          py36hc29e774_0    defaults
xlrd                      1.1.0            py36h336f4a2_1    defaults
xlsxwriter                1.0.2            py36h3736301_0    defaults
xlwings                   0.11.4           py36hc75f156_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.3                ha24016e_1    defaults
yaml                      0.1.7                hff548bb_1    defaults
zeromq                    4.2.2                h131e0f7_1    defaults
zict                      0.1.3            py36h71da714_0    defaults
zlib                      1.2.11               h60db283_1    defaults

```
</p></details>

**Comment by kalefranz** [comment]
The last release of pip was `9.0.1` on Nov 6, 2016.
https://github.com/pypa/pip/tree/9.0.1

Pip vendors setuptools.  pypa/setuptools#885 wasn't closed until Dec 13, 2016.  Unfortunately I guess this error is just baked into pip until they release a new version.

Although the comment at https://github.com/pypa/setuptools/issues/885#issuecomment-292660592 seems to imply that `conda update setuptools` might work.

**Comment by cdeil** [comment]
@kalefranz - Thanks for the quick reply.

> Pip vendors setuptools. pypa/setuptools#885 wasn't closed until Dec 13, 2016. Unfortunately I guess this error is just baked into pip until they release a new version.

@jaraco - can you release a new pip with the fix?

> Although the comment at pypa/setuptools#885 (comment) seems to imply that conda update setuptools might work.

No, I tried `conda update setuptools` and that didn't help.

**Comment by kalefranz** [comment]
Also: https://github.com/pypa/setuptools/issues/885#issuecomment-307696027

**Comment by kalefranz** [comment]
> Pip vendors setuptools.

I should be more accurate.  Pip vendors `pkg_resources`, which is part of  the `setuptools` package.

**Comment by jaraco** [comment]
> @jaraco - can you release a new pip with the fix?

I probably don't have access to cut releases, and if I was, I'm not familiar enough with the project to know the flow. I did put together [this patch](https://github.com/pypa/pip/commit/eaccb88674beff75bb98a1d1e2d53a26a9c63890), which I referenced in pypa/pip#4216. I didn't submit it as a PR, though.

**Comment by nsteins** [comment]
As a temporary work around, I was able to get a working version of pip using 

`conda update setuptools
easy_install pip`

which installed pip-9.0.1

**Comment by kalefranz** [comment]
Going to close this issue, as it's a packaging issue and not a conda code issue.
