### ISSUE TITLE
cannot update conda/ install with conda: permission denied

### ISSUE THREAD

**Issue by FrenskeD** [conda/conda#6901]
Hi!

I am submitting a bug report. I am trying to install pysftp using conda but as I found out that cannot update conda nor install anything with it.

I cannot find any reports that are similar (well google can't). I do not have SUDO access so any solution preferably without SUDO. 

    conda update --all
    Fetching package metadata ...An unexpected error has occurred.
    Please consider posting the following information to the
    conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

    Current conda install:

               platform : linux-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.18.4
       root environment : /users/francisd/anaconda2  (writable)
    default environment : /users/francisd/anaconda2
       envs directories : /users/francisd/anaconda2/envs
                          /users/francisd/.conda/envs
          package cache : /users/francisd/anaconda2/pkgs
                          /users/francisd/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /users/francisd/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.18.4 CPython/2.7.13 Linux/2.6.32-696.10.3.el6.x86_64 CentOS/6.4 glibc/2.12    
                UID:GID : 2792:150000

    `$ /users/francisd/anaconda2/bin/conda update --all`

    Traceback (most recent call last):
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
        timeout=timeout
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
        chunked=chunked)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/urllib3/connectionpool.py", line 346, in _make_request
        self._validate_conn(conn)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
        conn.connect()
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/urllib3/connection.py", line 326, in connect
        ssl_context=context)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 313, in ssl_wrap_socket
        context.load_verify_locations(ca_certs, ca_cert_dir)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/urllib3/contrib/pyopenssl.py", line 416, in load_verify_locations
        self._ctx.load_verify_locations(cafile, capath)
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/OpenSSL/SSL.py", line 669, in load_verify_locations
        _raise_current_error()
      File "/users/francisd/anaconda2/lib/python2.7/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
        raise exception_type(errors)
    Error: [('system library', 'fopen', 'Permission denied'), ('BIO routines', 'BIO_new_file', 'system lib'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]

Not sure it has anything to do with it, but 

`conda config --show-sources ` gives me the following

```
==> /users/francisd/.condarc <==
ssl_verify: /etc/ssl/certs/localhost.crt
```

**Comment by kalefranz** [comment]
conda config --remove-key ssl_verify
    conda update conda
