### ISSUE TITLE
Update spyder issue

### ISSUE THREAD

**Issue by cl48** [conda/conda#6907]
Hi I received error issues in updating spyder.  I don't understand the root of issue.  The output is below:

Deactivating environment "C:\Anaconda2"...
Activating environment "C:\Anaconda2"...

[Anaconda2] C:\windows\system32>conda update spyder
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ...................................An unexpected
 error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 180, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 48, in ex
ecute
    install.install(args, parser, 'update')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 334, in insta
ll
    update_deps=args.update_deps)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 438, in install_acti
ons
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 273, in ensure_linke
d_actions
    elif install.try_hard_link(config.pkgs_dirs[0], prefix, dist):
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 437, in try_hard_
link
    assert not isfile(dst), dst
AssertionError: C:\Anaconda2\.tmp-conda-env-2.6.0-0

[Anaconda2] C:\windows\system32>conda update spyder
Using Anaconda Cloud api site https://api.anaconda.org
Fetching package metadata: ....
Solving package specifications: ...................................An unexpected
 error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda2\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 173, in main
    args_func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main.py", line 180, in args_fun
c
    args.func(args, p)
  File "C:\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 48, in ex
ecute
    install.install(args, parser, 'update')
  File "C:\Anaconda2\lib\site-packages\conda\cli\install.py", line 334, in insta
ll
    update_deps=args.update_deps)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 438, in install_acti
ons
    actions = ensure_linked_actions(smh, prefix)
  File "C:\Anaconda2\lib\site-packages\conda\plan.py", line 273, in ensure_linke
d_actions
    elif install.try_hard_link(config.pkgs_dirs[0], prefix, dist):
  File "C:\Anaconda2\lib\site-packages\conda\install.py", line 437, in try_hard_
link
    assert not isfile(dst), dst
AssertionError: C:\Anaconda2\.tmp-conda-env-2.6.0-0

**Comment by kalefranz** [comment]
Please use the issue template, and include all requested information.

**Comment by kalefranz** [comment]
Without more information, I'm going to assume you have an old version of conda.  `conda update conda`
