### ISSUE TITLE
conda tries to link a directory

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#691]
I'm getting this error with a new env creation using a package I built (http://binstar.org/wakari1/julia).  It looks like conda is trying to hard-link a directory, but I'm not really sure.
## Error

``` python
  File "/opt/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: u'/opt/anaconda/pkgs/julia-0.3.0.git_prerelease-0/share/julia/base'
```
## Command Trace

```
[~]$ conda create -n julia3 julia | tee julia-env-create.log
```

Fetching package metadata: .....
Solving package specifications: .
Package plan for installation in environment /opt/anaconda/envs/julia3:

The following packages will be linked:

| package | build |
| --- | --- |
| docutils-0.11 | py27_0   hard-link |
| gmp-4.3.2 | 0   hard-link |
| ipython-2.0.0 | py27_30   hard-link |
| jinja2-2.7.2 | py27_0   hard-link |
| julia-0.3.0.git_prerelease | 0   hard-link |
| libffi-3.0.13 | 2   hard-link |
| markupsafe-0.18 | py27_0   hard-link |
| mathjax-2.2 | py27_0   hard-link |
| openssl-1.0.1g | 0   hard-link |
| pandoc-1.12.3 | 3   hard-link |
| pygments-1.6 | py27_0   hard-link |
| python-2.7.6 | 1   hard-link |
| pyzmq-2.2.0.1 | py27_1   hard-link |
| readline-6.2 | 2   hard-link |
| sphinx-1.2.2 | py27_0   hard-link |
| sqlite-3.7.13 | 0   hard-link |
| ssl_match_hostname-3.4.0.2 | py27_0   hard-link |
| system-5.8 | 1   hard-link |
| tk-8.5.13 | 0   hard-link |
| tornado-3.2.0 | py27_0   hard-link |
| util-linux-2.21 | 0   hard-link |
| zeromq-2.2.0 | 1   hard-link |
| zlib-1.2.7 | 0   hard-link |

Proceed ([y]/n)? y

Linking packages ... ] |#######################                                                                                       |  21%
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command `conda info` in your report.

``` python
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 275, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 436, in execute_actions
    execute_plan(plan, index, verbose)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 418, in execute_plan
    link(prefix, arg)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/plan.py", line 374, in link
    install.link(pkgs_dir, prefix, dist, lt)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 434, in link
    _link(src, dst, lt)
  File "/opt/anaconda/lib/python2.7/site-packages/conda/install.py", line 131, in _link
    shutil.copy2(src, dst)
  File "/opt/anaconda/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/opt/anaconda/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 21] Is a directory: u'/opt/anaconda/pkgs/julia-0.3.0.git_prerelease-0/share/julia/base'
```
## `conda info`

```
[~]$ conda info -a
Current conda install:

             platform : linux-64
        conda version : 3.4.2
       python version : 2.7.6.final.0
     root environment : /opt/anaconda  (writable)
  default environment : /opt/anaconda
     envs directories : /opt/anaconda/envs
        package cache : /opt/anaconda/pkgs
         channel URLs : https://conda.binstar.org/wakari1/linux-64/
                        https://conda.binstar.org/r/linux-64/
                        http://www.wakari.io/anaconda/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
                        http://repo.continuum.io/pkgs/free/linux-64/
          config file : /opt/anaconda/.condarc
    is foreign system : False

# conda environments:
#
TestNotebook             /opt/anaconda/envs/TestNotebook
__wakari_gateone         /opt/anaconda/envs/__wakari_gateone
__wakari_ipython         /opt/anaconda/envs/__wakari_ipython
_test                    /opt/anaconda/envs/_test
julia                    /opt/anaconda/envs/julia
julia2                   /opt/anaconda/envs/julia2
julia3                   /opt/anaconda/envs/julia3
juliapkg                 /opt/anaconda/envs/juliapkg
root                  *  /opt/anaconda

sys.version: 2.7.6 |Anaconda 1.9.2 (64-bit)| (default...
sys.prefix: /opt/anaconda
sys.executable: /opt/anaconda/bin/python
conda location: /opt/anaconda/lib/python2.7/site-packages/conda
conda-build: /opt/anaconda/bin/conda-build
conda-convert: /opt/anaconda/bin/conda-convert
conda-index: /opt/anaconda/bin/conda-index
conda-metapackage: /opt/anaconda/bin/conda-metapackage
conda-pipbuild: /opt/anaconda/bin/conda-pipbuild
conda-skeleton: /opt/anaconda/bin/conda-skeleton

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: <not set>
CONDA_ENVS_PATH: <not set>
LD_LIBRARY_PATH: <not set>
PATH: /opt/anaconda/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/user_home/w_ijstokes/bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>

License directories:
    /opt/anaconda/licenses
    /user_home/w_ijstokes/.continuum
License files (license*.txt):
Package/feature end dates:
```

**Comment by kalefranz** [comment]
If this can be reproduced with the latest version of 4.3, please open a new ticket with the new stack trace.
