### ISSUE TITLE
error while updating conda. Please help!

### ISSUE THREAD

**Issue by ankitgenbit** [conda/conda#6934]
menuinst-1.4.7 100% |###############################| Time: 0:00:00 405.10 kB/s
Fetching packages ...
conda-env-2.6. 100% |###############################| Time: 0:00:00  19.12 kB/s
An unexpected error has occurred.                   | Time: 0:00:47 277.82 kB/s
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Anaconda  (writable)
    default environment : C:\Anaconda
       envs directories : C:\Anaconda\envs
          package cache : C:\Anaconda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\Ankit Singh\.condarc
           offline mode : False

`$ C:\Anaconda\Scripts\conda-script.py update --all`

    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 430, in download
        getLogger('fetch.update').info(index)
      File "C:\Anaconda\lib\logging\__init__.py", line 1279, in info
        self._log(INFO, msg, args, **kwargs)
      File "C:\Anaconda\lib\logging\__init__.py", line 1415, in _log
        self.handle(record)
      File "C:\Anaconda\lib\logging\__init__.py", line 1425, in handle
        self.callHandlers(record)
      File "C:\Anaconda\lib\logging\__init__.py", line 1487, in callHandlers
        hdlr.handle(record)
      File "C:\Anaconda\lib\logging\__init__.py", line 855, in handle
        self.emit(record)
      File "C:\Anaconda\lib\site-packages\conda\console.py", line 30, in emit
        fetch_progress.update(n)
      File "C:\Anaconda\lib\site-packages\conda\_vendor\progressbar\__init__.py", line 282, in update
        self.fd.write(self._format_line() + '\r')
    OSError: raw write() returned invalid length 160 (should have been between 0 and 80)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Anaconda\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Anaconda\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'C:\\Anaconda\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (raw write() returned invalid length 160 (should have been between 0 and 80)).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Anaconda\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Anaconda\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Anaconda\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'C:\\Anaconda\\pkgs\\mkl-2017.0.1-0.tar.bz2.part' for writing (raw write() returned invalid length 160 (should have been between 0 and 80)).

mkl-2017.0.1-0   9% |###                            | Time: 0:00:47 277.82 kB/s
(C:\Anaconda) C:\Users\Ankit Singh>

**Comment by jjhelmus** [comment]
The version of conda you are using is quite old, can you update it first using `conda update conda` and then try `conda update --all` again.
