### ISSUE TITLE
Can't update navigator

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#6937]
_From @bradezard131 on February 21, 2018 6:57_

See: [Issue #8562 ](https://github.com/ContinuumIO/anaconda-issues/issues/8562)

DON'T TELL ME TO UPDATE VIA THE COMMAND LINE, THAT NOT WORKING IS LITERALLY THE PROBLEM

```
Downloading and Extracting Packages
anaconda-navigator 1.7.0: ##################################################################################### | 100%
Preparing transaction: done
Verifying transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\cli\install.py", line 255, in install
        handle_txn(progressive_fetch_extract, unlink_link_transaction, prefix, args, newenv)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\cli\install.py", line 285, in handle_txn
        unlink_link_transaction.execute()
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\core\link.py", line 220, in execute
        self.verify()
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\common\io.py", line 441, in decorated
        return f(*args, **kwds)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\core\link.py", line 207, in verify
        exceptions = self._verify(self.prefix_setups, self.prefix_action_groups)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\core\link.py", line 460, in _verify
        cls._verify_transaction_level(prefix_setups),
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\core\link.py", line 455, in <genexpr>
        exceptions = tuple(exc for exc in concatv(
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\core\link.py", line 323, in _verify_individual_level
        error_result = axn.verify()
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 872, in verify
        touch(USER_ENVIRONMENTS_TXT_FILE, mkdir=True, sudo_safe=True)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\gateways\disk\update.py", line 95, in touch
        mkdir_p_sudo_safe(dirpath)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\gateways\disk\__init__.py", line 74, in mkdir_p_sudo_safe
        mkdir_p_sudo_safe(base_dir)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\gateways\disk\__init__.py", line 74, in mkdir_p_sudo_safe
        mkdir_p_sudo_safe(base_dir)
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\gateways\disk\__init__.py", line 74, in mkdir_p_sudo_safe
        mkdir_p_sudo_safe(base_dir)
      [Previous line repeated 968 more times]
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\gateways\disk\__init__.py", line 72, in mkdir_p_sudo_safe
        base_dir = dirname(path)
      File "C:\Users\brade\Anaconda3\lib\ntpath.py", line 242, in dirname
        return split(p)[0]
      File "C:\Users\brade\Anaconda3\lib\ntpath.py", line 206, in split
        d, p = splitdrive(p)
      File "C:\Users\brade\Anaconda3\lib\ntpath.py", line 141, in splitdrive
        if len(p) >= 2:
    RecursionError: maximum recursion depth exceeded in comparison

`$ C:\Users\brade\Anaconda3\Scripts\conda update anaconda-navigator`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
             CONDA_PREFIX=C:\Users\brade\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Users\brade\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\brade\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\brade
                     PATH=C:\Users\brade\Anaconda3;C:\Users\brade\Anaconda3\Library\mingw-w64\bi
                          n;C:\Users\brade\Anaconda3\Library\usr\bin;C:\Users\brade\Anaconda3\Li
                          brary\bin;C:\Users\brade\Anaconda3\Scripts;C:\Users\brade\Anaconda3\bi
                          n;C:\Program Files\Docker\Docker\Resources\bin;C:\Program
                          Files\Microsoft MPI\Bin\;C:\ProgramData\Oracle\Java\javapath;C:\WINDOW
                          S\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Win
                          dowsPowerShell\v1.0\;C:\Program Files (x86)\ATI
                          Technologies\ATI.ACE\Core-Static;C:\Program Files
                          (x86)\scala\bin;C:\Program Files (x86)\sbt\\bin;C:\WINDOWS\system32\co
                          nfig\systemprofile\.dnx\bin;C:\Program Files\Microsoft
                          DNX\Dnvm\;C:\Program Files (x86)\Brackets\command;C:\Strawberry\c\bin;
                          C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Program
                          Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files\dotnet\;C:\Program
                          Files\nodejs\;C:\Program Files\CMake\bin;C:\Program Files\Microsoft
                          SQL Server\130\Tools\Binn\;C:\Program
                          Files\Git\cmd;C:\Users\brade\AppData\Local\.meteor\;C:\Program Files
                          (x86)\scala\bin\;C:\Program Files (x86)\sbt\bin\;C:\Program
                          Files\Java\jdk1.8.0_74\bin;C:\Program Files\Microsoft VS Code\bin;C:\U
                          sers\brade\AppData\Local\atom\bin;C:\Users\brade\AppData\Roaming\npm;D
                          :\opencv\bin\Debug;D:\opencv\bin\Release;C:\Program
                          Files\Python36;C:\Users\brade\AppData\Local\Microsoft\WindowsApps;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\;C:\Program
                          Files\WindowsPowerShell\Modules\;C:\Program Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager\;C:\Program
                          Files (x86)\Microsoft
                          SDKs\Azure\PowerShell\ServiceManagement\;C:\Program Files
                          (x86)\Microsoft SDKs\Azure\PowerShell\Storage\
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : base
    active env location : C:\Users\brade\Anaconda3
            shell level : 1
       user config file : G:\home\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : C:\Users\brade\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\brade\Anaconda3\pkgs
                          C:\Users\brade\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\brade\Anaconda3\envs
                          C:\Users\brade\AppData\Local\conda\conda\envs
                          G:\home\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```

_Copied from original issue: ContinuumIO/anaconda-issues#8621_

**Comment by kalefranz** [comment]
_From @nehaljwani on February 24, 2018 7:17_

@bradezard131 Could you please dump the output of the following in a file and attach it here in a comment?
```
conda update anaconda-navigator -vvv
```

**Comment by kalefranz** [comment]
_From @bradezard131 on February 24, 2018 10:40_

[dump.txt](https://github.com/ContinuumIO/anaconda-issues/files/1754276/dump.txt)

**Comment by nehaljwani** [comment]
@kalefranz How come conda is using a config file at G:\home\.condarc ?

@bradezard131 Does G:\home exist on your computer?

**Comment by kalefranz** [comment]
@nehaljwani where do you see `G:\home.condarc`?

**Comment by kalefranz** [comment]
Oh nevermind.  It's probably what `python -c "import os; print(os.path.expanduser('~'))"` gives.

**Comment by kalefranz** [comment]
@bradezard131 As @nehaljwani asked:

> Does G:\home exist on your computer?

Also, can you share the output of 

    set

(so we can see the value of all environment variables)

**Comment by mbargull** [comment]
In
```
      File "C:\Users\brade\Anaconda3\lib\site-packages\conda\gateways\disk\__init__.py", line 72, in mkdir_p_sudo_safe
        base_dir = dirname(path)
```
is `path` always absolute? The recursion wouldn't end for `../some/path` or a non-existent root dir `G:\`.
Although it doesn't resolve the cause of this issue, we definitely need something like
```diff
 def mkdir_p_sudo_safe(path):
     if isdir(path):
         return
     base_dir = dirname(path)
+    if base_dir == path:
+        raise IOError(...)
     if not isdir(base_dir):
         mkdir_p_sudo_safe(base_dir)
```
to make it fail in a sensible way.

**Comment by bradezard131** [comment]
Well my system spontaneously combusted (not really, but got stuck in an unrecoverable automatic repair loop) today, and now it installed and updated just fine. Must have been something weird in my system (G:\home would have been an environment variable I had about 2 years ago, but should have been long gone)

**Comment by cbizzo** [comment]
I faced this problem, today (and over the last number of weeks). I got around it by specifying the path with the `-p` option. 
e.g.
`conda install -c anaconda requests-kerberos -p D:/python_libraries`.
