### ISSUE TITLE
issue while using flask module

### ISSUE THREAD

**Issue by ArunKumarCha** [conda/conda#6943]
I am not able to sue flask.

Traceback (most recent call last):
  File "C:\Users\Arun\Anaconda3\lib\site-packages\werkzeug\utils.py", line 18, in <module>
    from html.entities import name2codepoint
ModuleNotFoundError: No module named 'html.entities'; 'html' is not a package

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Arun\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\Arun\Anaconda3\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "C:\Users\Arun\Anaconda3\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\Arun\Anaconda3\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\Arun\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\Arun\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\Arun\Anaconda3\lib\site-packages\requests\__init__.py", line 63, in <module>
    from . import utils
  File "C:\Users\Arun\Anaconda3\lib\site-packages\requests\utils.py", line 11, in <module>
    import cgi
  File "C:\Users\Arun\Anaconda3\lib\cgi.py", line 42, in <module>
    import html
  File "C:\Users\Arun\Desktop\server\html.py", line 8, in <module>
    from flask import Flask, flash, redirect, render_template, request, session, abort
  File "C:\Users\Arun\Anaconda3\lib\site-packages\flask\__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "C:\Users\Arun\Anaconda3\lib\site-packages\werkzeug\__init__.py", line 151, in <module>
    __import__('werkzeug.exceptions')
  File "C:\Users\Arun\Anaconda3\lib\site-packages\werkzeug\exceptions.py", line 71, in <module>
    from werkzeug.wrappers import Response
  File "C:\Users\Arun\Anaconda3\lib\site-packages\werkzeug\wrappers.py", line 36, in <module>
    from werkzeug.utils import cached_property, environ_property, \
  File "C:\Users\Arun\Anaconda3\lib\site-packages\werkzeug\utils.py", line 20, in <module>
    from htmlentitydefs import name2codepoint
ModuleNotFoundError: No module named 'htmlentitydefs'

**Comment by kalefranz** [comment]
Oops! Looks like you didn't follow the issue template. The information requested in the template is very important to help us understand your problem. We can’t help you without it!
