### ISSUE TITLE
Cannot create env from YAML file: FileNotFoundError for python3.6

### ISSUE THREAD

**Issue by ralexx** [conda/conda#6946]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

`conda env create` raises a `FileNotFoundError` when I try to create an environment on Computer B from an environment.yml file generated on Computer A. Both computers are osx64 platform.

Similar behavior to #5995 .

#### Computer A
```
conda env export --no-builds -n nlp36 > nlp36.yml
```
[manually edit [nlp36.yml](https://github.com/conda/conda/files/1760090/nlp36.yml.txt) to remove unwanted`pip` entries and add the `conda-canary` channel]

#### Computer B
```
conda env create -n nlp-stable -f /path/to/nlp36.yml
```
#### Exception
```python
DEBUG conda.gateways.subprocess:subprocess_call(46): executing>> "/usr/local/share/anaconda/envs/nlp-stable/bin/python3.6" -Wi -m py_compile "/usr/local/share/anaconda/envs/nlp-stable/lib/python3.6/site-packages/attr/__init__.py"
DEBUG conda.core.link:_execute_actions(541): Error in action #18 for pkg_idx #35 CompilePycAction(target_prefix='/usr/local/share/anaconda/envs/nlp-stable', target_short_path='lib/python3.6/site-packages/attr/__pycache__/__init__.cpython-36.pyc', source_prefix='/usr/local/share/anaconda/envs/nlp-stable', source_short_path='lib/python3.6/site-packages/attr/__init__.py', prefix_path_data=PathDataV1(_path='lib/python3.6/site-packages/attr/__pycache__/__init__.cpython-36.pyc', path_type='pyc_file'), _execute_successful=False, _verified=True)
Traceback (most recent call last):
  File "/usr/local/share/anaconda/lib/python3.6/site-packages/conda/core/link.py", line 535, in _execute_actions
    action.execute()
  File "/usr/local/share/anaconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 525, in execute
    compile_pyc(python_full_path, self.source_full_path, self.target_full_path)
  File "/usr/local/share/anaconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 320, in compile_pyc
    result = subprocess_call(command, raise_on_error=False)
  File "/usr/local/share/anaconda/lib/python3.6/site-packages/conda/gateways/subprocess.py", line 47, in subprocess_call
    p = Popen(command_arg, cwd=path, stdin=PIPE, stdout=PIPE, stderr=PIPE, env=env)
  File "/usr/local/share/anaconda/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/local/share/anaconda/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/share/anaconda/envs/nlp-stable/bin/python3.6': '/usr/local/share/anaconda/envs/nlp-stable/bin/python3.6'
```

[full debug output](https://github.com/conda/conda/files/1760064/debug_output.txt) [exception and traceback start at line 2431]

## Expected Behavior

The `nlp-stable` environment should be created on Computer B.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

#### Computer A

```
               platform : osx-64
          conda version : 4.3.33
       conda is private : False
      conda-env version : 4.3.33
    conda-build version : 3.2.1
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /usr/local/share/anaconda  (writable)
    default environment : /usr/local/share/anaconda
       envs directories : /usr/local/share/anaconda/envs
                          /Users/arg/.conda/envs
          package cache : /usr/local/share/anaconda/pkgs
                          /Users/arg/.conda/pkgs
           channel URLs : https://conda.anaconda.org/ralexx/osx-64
                          https://conda.anaconda.org/ralexx/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
            config file : /Users/arg/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.33 requests/2.18.4 CPython/3.6.2 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
```
#### Computer B

```
     active environment : None
            shell level : 0
       user config file : /Users/GvozBook12/.condarc
 populated config files : /usr/local/share/anaconda/.condarc
                          /Users/GvozBook12/.condarc
          conda version : 4.4.11
    conda-build version : 3.1.3
         python version : 3.6.4.final.0
       base environment : /usr/local/share/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/ralexx/osx-64
                          https://conda.anaconda.org/ralexx/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/conda-canary/osx-64
                          https://conda.anaconda.org/conda-canary/noarch
                          https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
          package cache : /usr/local/share/anaconda/pkgs
                          /Users/GvozBook12/.conda/pkgs
       envs directories : /usr/local/share/anaconda/envs
                          /Users/GvozBook12/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

#### Computer A
```
==> /Users/arg/.condarc <==
add_anaconda_token: False
channels:
  - https://conda.anaconda.org/ralexx/osx-64
  - defaults
  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/r/osx-64
show_channel_urls: True
```

#### Computer B
```
==> /usr/local/share/anaconda/.condarc <==
pinned_packages:
  - conda-canary::conda

==> /Users/GvozBook12/.condarc <==
channels:
  - https://conda.anaconda.org/ralexx/osx-64
  - https://conda.anaconda.org/conda-forge/osx-64
  - conda-canary
  - defaults
  - https://conda.anaconda.org/r
show_channel_urls: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

#### Computer A
```
# packages in environment at /usr/local/share/anaconda:
#
anaconda-client           1.6.6            py36hd86ed11_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
asn1crypto                0.23.0           py36h782d450_0    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
bleach                    2.1.1            py36h27c13d8_0    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2017.11.5        py36ha569be9_0    defaults
cffi                      1.11.2           py36hd3e6348_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
clyent                    1.2.2            py36hae3ad88_0    defaults
conda                     4.3.33                   py36_0    defaults
conda-build               3.2.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
dbus                      1.10.22              h50d9ad6_0    defaults
decorator                 4.1.2            py36h69a1b52_0    defaults
entrypoints               0.2.3            py36hd81d71f_2    defaults
expat                     2.2.5                hb8e80ba_0    defaults
filelock                  2.0.13           py36hf9de95b_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
glib                      2.53.6               h33f6a65_2    defaults
glob2                     0.6              py36h94c9186_0    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
icu                       54.1                          0    defaults
idna                      2.6              py36h8628d0a_1    defaults
ipykernel                 4.7.0            py36h2f9c1c0_0    defaults
ipython                   6.2.1            py36h3dda519_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.0.0a1                   <pip>
ipywidgets                7.0.5            py36h5142716_0    defaults
jedi                      0.11.0                   py36_2    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0            py36h598a6cc_0    defaults
jupyter-core              4.3.0                     <pip>
jupyter_client            5.1.0            py36hf6c435f_0    defaults
jupyter_console           5.2.0            py36hccf5b1c_1    defaults
jupyter_core              4.4.0            py36h79cf704_0    defaults
jupyterthemes             0.15.6                    <pip>
lesscpy                   0.12.0                    <pip>
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.32               hd1e8b91_4    defaults
libsodium                 1.0.15               hd9e47c5_0    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
mistune                   0.8.1            py36h638d0ca_0    defaults
nbconvert                 5.3.1            py36h810822e_0    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.0                  hd04f020_2    defaults
notebook                  5.2.2            py36h124cd7f_0    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
packaging                 16.8             py36he5e8135_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2            py36h3b0b094_1    defaults
parso                     0.1.1            py36hc90e01c_0    defaults
path.py                   10.5             py36h7bcb313_0    defaults
pcre                      8.41                 hfb6ab37_1    defaults
pexpect                   4.3.0            py36h427ab81_0    defaults
pickleshare               0.7.4            py36hf512f8e_0    defaults
pip                       9.0.1            py36h1555ced_4    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
ply                       3.10                      <pip>
prompt_toolkit            1.0.15           py36haeda067_0    defaults
ptyprocess                0.5.2            py36he6521c3_0    defaults
pyasn1                    0.4.2            py36h62a34ed_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h72f2894_1    defaults
pygments                  2.2.0            py36h240cd3f_0    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pyqt                      5.6.0            py36he5c6137_6    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.2                         0    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
pytz                      2017.3           py36hf0bf824_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.3           py36he48b5ad_0    defaults
qt                        5.6.2                         2    defaults
qtconsole                 4.3.1            py36hd96c0ff_0    defaults
readline                  6.2                           2    defaults
requests                  2.18.4           py36h4516966_1    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
setuptools                36.5.0           py36h2134326_0    defaults
simplegeneric             0.8.1            py36he5b5b09_0    defaults
sip                       4.18.1           py36h2824476_2    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.13.0                       99    ralexx
terminado                 0.6              py36h656782e_0    defaults
testpath                  0.3.1            py36h625a49b_0    defaults
tk                        8.5.18                        0    defaults
tornado                   4.5.2            py36h468dda9_0    defaults
traitlets                 4.3.2                     <pip>
traitlets                 4.3.2            py36h65bd3ce_0    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
widgetsnbextension        3.0.8            py36h34759f8_0    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.2                ha360ad0_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```

#### Computer B
```
# packages in environment at /usr/local/share/anaconda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
ca-certificates           2018.1.18                     0    conda-forge
certifi                   2018.1.18                py36_0    conda-forge
cffi                      1.11.4           py36h342bebf_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
conda                     4.4.11                   py36_0    conda-canary
conda-build               3.1.3            py36h2f9c1c0_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
decorator                 4.2.1                    py36_0    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
ncurses                   6.0                  hd04f020_2    defaults
numba                     0.35.0              np111py35_0    defaults
numexpr                   2.6.2               np111py35_0    defaults
numpy                     1.11.3                   py35_0    defaults
openpyxl                  2.4.8                    py35_0    defaults
openssl                   1.0.2n                        0    conda-forge
pandas                    0.20.1              np111py35_0    defaults
path.py                   10.3.1                   py35_0    defaults
pillow                    4.2.1                    py35_0    defaults
pip                       9.0.1            py36h1555ced_4    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
psutil                    5.2.2                    py35_0    defaults
py                        1.4.34                   py35_0    defaults
pyasn1                    0.2.3                    py35_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pycrypto                  2.6.1            py36h1de35cc_7    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyqt                      4.11.4                   py35_4    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.4                hc167b69_1    defaults
python-dateutil           2.6.1                    py35_0    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2017.2                   py35_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
pyzmq                     16.0.2                   py35_0    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
requests-cache            0.4.13                   py35_0    conda-forge
requests-file             1.4.1                    py35_0    defaults
requests-ftp              0.3.1                    py35_0    defaults
ruamel_yaml               0.15.35          py36h1de35cc_1    defaults
setuptools                38.5.1                   py36_0    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.20.1                       42    ralexx
tk                        8.6.7                h35a86e2_3    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
urllib3                   1.22             py36h68b9469_0    defaults
webencodings              0.5.1            py36h3b9701d_1    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults

```
</p></details>

**Comment by ralexx** [comment]
This can be worked around by changing the package spec, from the no-arch packages used in e.g. the conda-forge channel, to the defaults channel. It has to be done by trial and error if you want to keep using packages from the conda-forge channel because not every no-arch package complains.

So, for example, `attrs=18.1.0=py_1` becomes `attrs=18.1.0=py36_0`.

The attached environment file created successfully, but I can't find the pattern in which no-arch builds fail to compile. Some do, some don't.

[nlp36-intel.txt](https://github.com/conda/conda/files/2077293/nlp36-intel.txt)

**Comment by matthiasdv** [comment]
A workaround for this problem is: 

```
conda create -n __name__ python=2.7
conda activate __name__
conda env update -f environment.yml
```
