### ISSUE TITLE
UnicodeDecodeError when running 'conda info -a'

### ISSUE THREAD

**Issue by cbrodeur0818** [conda/conda#6955]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

While trying to retrieve the conda environment info from terminal with 'conda info -a', I received a python exception and traceback. See below in Environment Information. Please note that the command 'conda info' does not cause an exception.

### Steps to Reproduce

```
Run 'conda info -a' from within my Django conda environment.
```

## Expected Behavior

Output the conda info without crashing.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       requests version : 2.18.4
       root environment : /Users/cameron/anaconda2  (writable)
    default environment : /Users/cameron/anaconda2/envs/env-django
       envs directories : /Users/cameron/anaconda2/envs
                          /Users/cameron/.conda/envs
          package cache : /Users/cameron/anaconda2/pkgs
                          /Users/cameron/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/cameron/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/2.7.14 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
# conda environments:
#
env-django            *  /Users/cameron/anaconda2/envs/env-django
env-flask                /Users/cameron/anaconda2/envs/env-flask
env-py27-ml              /Users/cameron/anaconda2/envs/env-py27-ml
env-py36                 /Users/cameron/anaconda2/envs/env-py36
root                     /Users/cameron/anaconda2

sys.version: 2.7.14 |Anaconda, Inc.| (default, Oct  5...
sys.prefix: /Users/cameron/anaconda2
sys.executable: /Users/cameron/anaconda2/bin/python
conda location: /Users/cameron/anaconda2/lib/python2.7/site-packages/conda
conda-build: /Users/cameron/anaconda2/bin/conda-build
conda-convert: /Users/cameron/anaconda2/bin/conda-convert
conda-develop: /Users/cameron/anaconda2/bin/conda-develop
conda-env: /Users/cameron/anaconda2/bin/conda-env
conda-index: /Users/cameron/anaconda2/bin/conda-index
conda-inspect: /Users/cameron/anaconda2/bin/conda-inspect
conda-metapackage: /Users/cameron/anaconda2/bin/conda-metapackage
conda-render: /Users/cameron/anaconda2/bin/conda-render
conda-server: /Users/cameron/anaconda2/bin/conda-server
conda-skeleton: /Users/cameron/anaconda2/bin/conda-skeleton
conda-verify: /Users/cameron/anaconda2/bin/conda-verify
user site dirs:

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: env-django
CONDA_ENVS_PATH: <not set>
CONDA_PATH_BACKUP: /Users/cameron/anaconda2/bin:/Users/cameron/bin:/usr/local/sbin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Applications/Wireshark.app/Contents/MacOS
CONDA_PREFIX: /Users/cameron/anaconda2/envs/env-django
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



`$ /Users/cameron/anaconda2/envs/env-django/bin/conda info -a`




    Traceback (most recent call last):
      File "/Users/cameron/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/cameron/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/cameron/anaconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 368, in execute
        print("%s: %s" % (name, value))
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xee in position 54: ordinal not in range(128)
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/cameron/.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/cameron/anaconda2/envs/env-django:
#
bcrypt                    3.1.4                     <pip>
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.4                    <pip>
Django                    1.11.10                   <pip>
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.0                  hd04f020_2    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
pip                       9.0.1            py27h1567d89_4    defaults
pycparser                 2.18                      <pip>
python                    2.7.14              hde5916a_29    defaults
python-dateutil           2.6.1                     <pip>
pytz                      2018.3                    <pip>
readline                  7.0                  hc1231fa_4    defaults
setuptools                38.4.0                   py27_0    defaults
six                       1.11.0                    <pip>
sqlite                    3.22.0               h3efe00b_0    defaults
tk                        8.6.7                h35a86e2_3    defaults
tzlocal                   1.5.1                     <pip>
wheel                     0.30.0           py27h677a027_1    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by epogrebnyak** [comment]
Any solution to this? Got a similar problem at #8662

**Comment by epogrebnyak** [comment]
The error persists in latest Miniconda 4.6.14

```
λ D:\Miniconda3\Scripts\conda info -a

     active environment : None
       user config file : C:\Users\Евгений\.condarc
 populated config files : C:\Users\Евгений\.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : D:\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Miniconda3\pkgs
                          C:\Users\Евгений\.conda\pkgs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\pkgs
       envs directories : D:\Miniconda3\envs
                          C:\Users\Евгений\.conda\envs
                          C:\Users\B7E3~1\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "D:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "D:\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 313, in execute
        info_dict['envs'] = list_all_known_prefixes()
      File "D:\Miniconda3\lib\site-packages\conda\core\envs_manager.py", line 71, in list_all_known_prefixes
        all_env_paths.update(_clean_environments_txt(environments_txt_file))
      File "D:\Miniconda3\lib\site-packages\conda\core\envs_manager.py", line 108, in _clean_environments_txt
        environments_txt_lines = tuple(yield_lines(environments_txt_file))
      File "D:\Miniconda3\lib\site-packages\conda\gateways\disk\read.py", line 53, in yield_lines
        for line in fh:
      File "D:\Miniconda3\lib\codecs.py", line 322, in decode
        (result, consumed) = self._buffer_decode(data, self.errors, final)
    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 114: invalid continuation byte

```

**Comment by epogrebnyak** [comment]
Maybe any thoughts from here can help: https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte
