### ISSUE TITLE
YAML parsing is broken in fresh conda install

### ISSUE THREAD

**Issue by desilinguist** [conda/conda#6961]
```
    Traceback (most recent call last):
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/cli/main.py", line 110, in main
        from ..activate import main as activator_main
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/base/context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/conda/common/serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/main.py", line 639, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/composer.py", line 187, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 144, in check_event
        self.current_event = self.state()
      File "/Users/nmadnani/anaconda/lib/python3.6/site-packages/ruamel_yaml/parser.py", line 561, in parse_block_mapping_key
        token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "/Users/nmadnani/.condarc", line 1, column 1
    expected <block end>, but found '<block sequence start>'
      in "/Users/nmadnani/.condarc", line 4, column 2

`$ /Users/nmadnani/anaconda/bin/conda shell.posix activate base`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/Users/nmadnani/anaconda
              CONDA_SHLVL=0
                     PATH=:/opt/local/bin:/opt/X11/bin:/usr/texbin:/opt/X11/bin:/Library/TeX/tex
                          bin:/Users/nmadnani/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:
                          /usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/MacGPG2/b
                          in:/opt/X11/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/nmadnani/.condarc
 populated config files : 
          conda version : 4.4.10
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /Users/nmadnani/anaconda  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/nmadnani/anaconda/pkgs
                          /Users/nmadnani/.conda/pkgs
       envs directories : /Users/nmadnani/anaconda/envs
                          /Users/nmadnani/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Darwin/17.4.0 OSX/10.13.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```

**Comment by desilinguist** [comment]
Is this related to https://bitbucket.org/ruamel/yaml/issues/172/ruamelyamlparserparsererror-while-parsing ?

**Comment by kalefranz** [comment]
What is the contents of `/Users/nmadnani/.condarc`?

**Comment by desilinguist** [comment]
```
channels:
  - defaults
  - desilinguist
 - https://nlp.research.ets.org/conda
ssl_verify: false
```

**Comment by desilinguist** [comment]
I think it's the lack of the missing extra space before the dash, actually. That's unbelievable.

**Comment by kalefranz** [comment]
Yeah it is.  It's not valid yaml otherwise.

**Comment by mbargull** [comment]
@desilinguist: If you want to avoid dealing with YAML syntax, you can also use `conda config` to, well, config `conda`.
