### ISSUE TITLE
Better support for basic auth in url

### ISSUE THREAD

**Issue by ablack-jpl** [conda/conda#6969]
**I'm submitting a...**
  - [ ] bug report
  - [X] feature request

## Current Behavior
http://[user]@XXX returns a 401 without the option to enter a password at terminal, and sufficiently long [user]:[secret]@XXX strings fail because of a urllib bug in python3 (this isn't a conda bug, but it is motivation for the feature request).

### Steps to Reproduce
```
$ conda search --override-channels --channel https://<user>@<host>/<real channel expecting authentication>

Loading channels: failed

CondaHTTPError: HTTP 401 UNAUTHORIZED for url <https://<user>@<host>/<real channel expecting authentication>/noarch/repodata.json>

## Demonstration of the bug prompting this feature request
## working command because the host doesn't care about credentials
 
$ conda search --override-channels --channel https://0123456789:0123456789012345678901234567890123456789@repo.continuum.io/pkgs/main/linux-64/ alembic
Loading channels: done
Name                       Version                   Build  Channel        
alembic                    0.9.5            py27h0668a64_0  defaults       
alembic                    0.9.5            py35h387e2dd_0  defaults       
alembic                    0.9.5            py36h968a0d3_0  defaults       
alembic                    0.9.6            py27he2127cc_0  defaults       
alembic                    0.9.6            py35h2ca1cdd_0  defaults       
alembic                    0.9.6            py36h01b5dd9_0  defaults   

## failing command even though the host doesn't care about credentials

$ conda search --override-channels --channel https://0123456789:01234567890123456789012345678901234567890123456789@repo.continuum.io/pkgs/main/linux-64/ alembic
Loading channels: failed

CondaIndexError: Invalid index file: https://0123456789:01234567890123456789012345678901234567890123456789@repo.continuum.io/pkgs/main/noarch/repodata.json.bz2: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

```

## Expected Behavior
Conda should prompt for a password when a username is passed via basic auth and no secret is provided. Conda should accepts credentials in other formats than basic auth embedded in url.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /Users/ablack/.condarc
 populated config files : /Users/ablack/.condarc
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.3.final.0
       base environment : /Users/ablack/miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /Users/ablack/miniconda3/pkgs
                          /Users/ablack/.conda/pkgs
       envs directories : /Users/ablack/miniconda3/envs
                          /Users/ablack/.conda/envs
               platform : osx-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.3 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 931525951:703763885
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /Users/ablack/.condarc <==
ssl_verify: True
channels:
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
# packages in environment at /Users/ablack/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.23.0           py36h782d450_0    defaults
beautifulsoup4            4.6.0            py36h72d3c9f_1    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.2           py36hd3e6348_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
conda                     4.4.10                   py36_0    defaults
conda-build               3.4.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
conda-verify              2.0.0            py36he837df3_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
filelock                  2.0.13           py36hf9de95b_0    defaults
freetype                  2.8                  h12048fb_1    defaults
glob2                     0.6              py36h94c9186_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
intel-openmp              2018.0.0             h8158457_8    defaults
jinja2                    2.10             py36hd36f9c5_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libpng                    1.6.34               he12f830_0    defaults
markupsafe                1.0              py36h3a1e703_1    defaults
matplotlib                2.1.2            py36h6d6146d_0    defaults
mkl                       2018.0.1             hfbd8650_4    defaults
ncurses                   6.0                  hd04f020_2    defaults
numpy                     1.14.0           py36h8a80b8c_1    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
pip                       9.0.1            py36h1555ced_4    defaults
pkginfo                   1.4.1            py36h25bf955_0    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pyparsing                 2.2.0            py36hb281f35_0    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.3                h47c878a_7    defaults
python-dateutil           2.6.1            py36h86d2abb_1    defaults
python.app                2                py36h54569d5_7    defaults
pytz                      2017.3           py36hf0bf824_0    defaults
pyyaml                    3.12             py36h2ba1e63_1    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
setuptools                36.5.0           py36h2134326_0    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.20.1               h7e4c145_2    defaults
tk                        8.6.7                h35a86e2_3    defaults
tornado                   4.5.3                    py36_0    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults

```
</p></details>

**Comment by kalefranz** [comment]
> Conda should prompt for a password when a username is passed via basic auth and no secret is provided.

Seem reasonable to me.

> Conda should accepts credentials in other formats than basic auth embedded in url.

That's less clear to me.  "Other formats" is pretty vague, and there are a lot of options.  Not clear how to design this in a way that doesn't overwhelm users.

**Comment by ablack-jpl** [comment]
> That's less clear to me. "Other formats" is pretty vague, and there are a lot of options. Not clear how to design this in a way that doesn't overwhelm users.

Fair. I had in mind the way that .pypirc handles credentials for alternate servers, where you specify the repo, username, and password in a later section, but didn't want to bias discussion with a particular suggestion.

**Comment by szhem** [comment]
@kalefranz @ablack-jpl 

> "Other formats" is pretty vague, and there are a lot of options. Not clear how to design this in a way that doesn't overwhelm users.

> Fair. I had in mind the way that .pypirc handles credentials for alternate servers, where you specify the repo, username, and password in a later section, but didn't want to bias discussion with a particular suggestion.

I suppose that quite a lot of users are familiar with .pypirc format so the shouldn't be overwhelmed a lot. In other case if the credentials are included into the channel's URIs then there is a security risk to make them available to the world.

Just consider the following configuration
```
channel_alias: https://user:password@<corporate-proxy>/repository/raw-conda-channels-cache/
default_channels:
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/main/
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/free/
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/r/
```
In that case if you will try to search for a package that cannot be found, then conda will print all the credentials onto the screen 
```
$ conda search fasttext 
Loading channels: done
No match found for: fasttext. Search: *fasttext*

PackagesNotFoundError: The following packages are not available from current channels:

  - fasttext

Current channels:

  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/main/linux-64
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/main/noarch
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/free/linux-64
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/free/noarch
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/r/linux-64
  - https://user:password@<corporate-proxy>/repository/raw-conda-defaults-cache/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```
So every time conda considers that something goes wrong it prints channel URI with the credentials included.

**Comment by chaosdeathfish** [comment]
> So every time conda considers that something goes wrong it prints channel URI with the credentials included.

It's actually worse than this - the json files in the conda-meta directory store the full URL that the package was downloaded from - including the username and password.

**Comment by jsanjay63** [comment]
Yes, this very much a need as conda repo doesn't support any other auth mechanism as well. We have only option to pass the credentials in the format https://{username}:{password}@repo. which doesn't work well with many cases or long passwords.
Any plans on making this available?

**Comment by jsanjay63** [comment]
Also, I have found instances with my local authorized repository wherein same credentials with URL works on Linux but not on windows. There seems to be some strange issue with conda install authentication.

**Comment by jsanjay63** [comment]
An issue identified on windows: I have a character "/" in the password for which if I encode and pass it as "%2F" in the command conda install -c <channel_url> internally it replaces "%2" with "-c" as I assume it considers "-c" as a 2nd argument to the batch file and hence replaces my password. Hence, it results in an unauthorized error.

**Comment by dataslicer** [comment]
Sorry for across posting in 2 different issues, [1784 ](https://github.com/conda/conda/issues/1784)and [6969](https://github.com/conda/conda/issues/6969).
I am simply providing another perspective why this is still a challenge in year 2021.

Now a days the password requirements goes beyond just a simple alphanumeric characters to include special characters.  
Passwords that complies to these requirements are breaking the .condarc parsers.  


```
$ conda config --show
WARNING conda.exceptions:print_unexpected_error_report(1213): KeyError('pkgs_dirs')
Traceback (most recent call last):
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 83, in do_call
    return getattr(module, func_name)(args, parser)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main_config.py", line 30, in execute
    execute_config(args, parser)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main_config.py", line 135, in execute_config
    d = OrderedDict((key, getattr(context, key)) for key in paramater_names)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/cli/main_config.py", line 135, in <genexpr>
    d = OrderedDict((key, getattr(context, key)) for key in paramater_names)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 268, in new_fget
    cache[inner_attname] = func(self)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/base/context.py", line 615, in channel_alias
    location, scheme, auth, token = split_scheme_auth_token(self._channel_alias)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/common/url.py", line 317, in split_scheme_auth_token
    url_parts = urlparse(cleaned_url)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/_vendor/auxlib/decorators.py", line 59, in _memoized_func
    result = func(*args, **kwargs)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/common/url.py", line 130, in urlparse
    return parse_url(url)
  File "/home/USERID/miniconda3/lib/python3.8/site-packages/conda/_vendor/urllib3/util/url.py", line 196, in parse_url
    raise LocationParseError(url)

conda._vendor.urllib3.exceptions.LocationParseError: Failed to parse: USERID:PasswordWithSpecialCharacters
```

Context:
```
$ conda -V
conda 4.9.2

$ grep -A1 channel .condarc
show_channel_urls: true

channel_alias: https://USERID:PasswordWithSpecialCharacters#me2@YOURDOMAIN.com/conda-proxy/

channels:
  - conda-forge
```

Hopefully this provides another perspective why this is enhancement is necessary.

Is there another workaround available for this situation?
