### ISSUE TITLE
Anaconda Navigator not willing to open ... 

### ISSUE THREAD

**Issue by terminsen** [conda/conda#6970]
Hi - 

Trying to run Anaconda Navigator on my Win 7 from the Anaconda Prompt and I get the error below. Anyone know what that means, please ?

Kind regards, Jesper.

 
(base) C:\Users\jet>anaconda-navigator
Traceback (most recent call last):
  File "C:\Users\jet\Anaconda3\Scripts\anaconda-navigator-script.py", line 10, i
n <module>
    sys.exit(main())
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\app\main.py"
, line 129, in main
    from anaconda_navigator.app.start import start_app
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py
", line 32, in <module>
    from anaconda_navigator.widgets.main_window import MainWindow
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main
_window.py", line 32, in <module>
    from anaconda_navigator.api.anaconda_api import AnacondaAPI
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda
_api.py", line 33, in <module>
    from anaconda_navigator.api.client_api import ClientAPI
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\api\client_a
pi.py", line 24, in <module>
    from anaconda_navigator.api.conda_api import CondaAPI
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_ap
i.py", line 33, in <module>
    from anaconda_navigator.utils.findpip import PIP_LIST_SCRIPT
  File "C:\Users\jet\Anaconda3\lib\site-packages\anaconda_navigator\utils\findpi
p.py", line 22, in <module>
    import pip
  File "C:\Users\jet\Anaconda3\lib\site-packages\pip\__init__.py", line 28, in <
module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\jet\Anaconda3\lib\site-packages\pip\vcs\mercurial.py", line 9,
in <module>
    from pip.download import path_to_url
  File "C:\Users\jet\Anaconda3\lib\site-packages\pip\download.py", line 34, in <
module>
    from pip.utils.logging import indent_log
  File "C:\Users\jet\Anaconda3\lib\site-packages\pip\utils\logging.py", line 66,
 in <module>
    class ColorizedStreamHandler(logging.StreamHandler):
  File "C:\Users\jet\Anaconda3\lib\site-packages\pip\utils\logging.py", line 72,
 in ColorizedStreamHandler
    (logging.ERROR, _color_wrap(colorama.Fore.RED)),
AttributeError: module 'pip._vendor.colorama' has no attribute 'Fore'

(base) C:\Users\jet>

**Comment by kalefranz** [comment]
Please use the issue template and complete all the requested information.  We ask these questions for a reason.  We can't help you without it.
