### ISSUE TITLE
Anaconda Navigator does not run on Windows 10 pc. Conda fails to run.

### ISSUE THREAD

**Issue by Daddio1949** [conda/conda#6972]
In the last few days Navigator fails to open but the  Anaconda jupyter notebooks does work.

I have the Anaconda 64 bit version running on Windows 10. I have been running Anaconda for several years and Navigator for the last year.   I last ran conda updates successfully a month ago.

When I enter the Anaconda prompt and execute these commands: conda info and conda list, I received the following error messages:

(base) C:\Users\Daddio>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\exceptions.py", line 772, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 76, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\Daddio\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 985, in _gcd_import
      File "<frozen importlib._bootstrap>", line 968, in _find_and_load
      File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 697, in exec_module
      File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
        from ..core.repodata import SubdirData
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\core\repodata.py", line 28, in <module>
        from ..core.package_cache import PackageCache
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 12, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 27, in <module>
        from ..gateways.connection.download import download
      File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 23, in <module>
        from pip._vendor.requests.packages.urllib3.exceptions import InsecureRequestWarning
    ImportError: No module named 'pip._vendor.requests.packages.urllib3'; 'pip._vendor.requests.packages' is not a package

`$ C:\Users\Daddio\Anaconda3\Scripts\conda info`

An unexpected error has occurred. Conda has prepared the above report.
Upload did not complete.
(base) C:\Users\Daddio>

(base) C:\Users\Daddio>conda list
Traceback (most recent call last):
  File "C:\Users\Daddio\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\cli\main.py", line 126, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\exceptions.py", line 1008, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\exceptions.py", line 775, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\exceptions.py", line 815, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\exceptions.py", line 827, in handle_unexpected_exception
    self.print_error_report(error_report)
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\exceptions.py", line 880, in print_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 25, in <module>
    from ..core.repodata import SubdirData
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\core\repodata.py", line 28, in <module>
    from ..core.package_cache import PackageCache
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 12, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 27, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\Daddio\Anaconda3\lib\site-packages\conda\gateways\connection\__init__.py", line 23, in <module>
    from pip._vendor.requests.packages.urllib3.exceptions import InsecureRequestWarning
ImportError: No module named 'pip._vendor.requests.packages.urllib3'; 'pip._vendor.requests.packages' is not a package

(base) C:\Users\Daddio>

**Comment by kalefranz** [comment]
Oops! Please use the issue template. The information requested in the template is very important to be able to solve your problem. We can’t help you without it!
