### ISSUE TITLE
Conda stuck at "Executing transaction"

### ISSUE THREAD

**Issue by Scheibs** [conda/conda#6986]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
I just uninstalled/installed the latest version of anaconda. 
In a first place I updated conda, everyting doing well. After that I tried to create an environment, it's failed.
Now, After trying to install xarray package, the package installation seems to be stucked in "Executing transaction".
I allready had this probleme before, after `conda update --all`, thats why I uninstalled/installed anaconda.
This is my console print :
```Microsoft Windows [version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Tous droits réservés

D:\Users\scheiblin-noe01>conda --version
conda 4.4.10

D:\Users\scheiblin-noe01>conda update conda
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda2

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.5.0rc0             |           py27_0         1.0 MB  conda-canary

The following packages will be UPDATED:

    conda: 4.4.10-py27_0 defaults --> 4.5.0rc0-py27_0 conda-canary

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda 4.5.0rc0: ####################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

D:\Users\scheiblin-noe01>conda --version
conda 4.5.0rc0

D:\Users\scheiblin-noe01>conda create --name nsenv xarray
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current cha
nnels:

  - none

Current channels:

  - https://conda.anaconda.org/conda-canary/win-64
  - https://conda.anaconda.org/conda-canary/noarch
  - https://conda.anaconda.org/anaconda-fusion/win-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - http://conda.binstar.org/mutirri/win-64
  - http://conda.binstar.org/mutirri/noarch
  - http://repo.continuum.io/pkgs/free/win-64
  - http://repo.continuum.io/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch



D:\Users\scheiblin-noe01>conda create --name nsenv
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current cha
nnels:

  - none

Current channels:

  - https://conda.anaconda.org/conda-canary/win-64
  - https://conda.anaconda.org/conda-canary/noarch
  - https://conda.anaconda.org/anaconda-fusion/win-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - http://conda.binstar.org/mutirri/win-64
  - http://conda.binstar.org/mutirri/noarch
  - http://repo.continuum.io/pkgs/free/win-64
  - http://repo.continuum.io/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/pro/win-64
  - https://repo.anaconda.com/pkgs/pro/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch



D:\Users\scheiblin-noe01>conda install xarray
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda2

  added / updated specs:
    - xarray


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    requests-2.14.2            |           py27_0         698 KB  defaults
    cryptography-1.8.1         |           py27_0         335 KB  defaults
    certifi-2016.2.28          |           py27_0         213 KB  defaults
    libssh2-1.8.0              |            vc9_0         184 KB  defaults
    setuptools-36.4.0          |           py27_1         525 KB  defaults
    openssl-1.0.2l             |            vc9_0         4.4 MB  defaults
    pycurl-7.19.0              |           py27_0         712 KB  defaults
    xarray-0.9.6               |           py27_0         476 KB  defaults
    pyopenssl-17.0.0           |           py27_0          73 KB  defaults
    anaconda-custom            |           py27_0          13 KB  defaults
    ------------------------------------------------------------
                                           Total:         7.5 MB

The following NEW packages will be INSTALLED:

    xarray:       0.9.6-py27_0            defaults

The following packages will be UPDATED:

    anaconda:     5.1.0-py27_2            defaults --> custom-py27_0    defaults


The following packages will be DOWNGRADED:

    certifi:      2018.1.18-py27_0        defaults --> 2016.2.28-py27_0 defaults

    cryptography: 2.1.4-py27h0628b04_0    defaults --> 1.8.1-py27_0     defaults

    libssh2:      1.8.0-h77a7533_4        defaults --> 1.8.0-vc9_0      defaults

    openssl:      1.0.2n-hc64555f_0       defaults --> 1.0.2l-vc9_0     defaults

    pycurl:       7.43.0.1-py27hc64555f_0 defaults --> 7.19.0-py27_0    defaults

    pyopenssl:    17.5.0-py27h59156d7_0   defaults --> 17.0.0-py27_0    defaults

    requests:     2.18.4-py27h3159eba_1   defaults --> 2.14.2-py27_0    defaults

    setuptools:   38.4.0-py27_0           defaults --> 36.4.0-py27_1    defaults


Proceed ([y]/n)? y


Downloading and Extracting Packages
requests 2.14.2: ###################################################### | 100%
cryptography 1.8.1: ################################################### | 100%
certifi 2016.2.28: #################################################### | 100%
libssh2 1.8.0: ######################################################## | 100%
setuptools 36.4.0: #################################################### | 100%
openssl 1.0.2l: ####################################################### | 100%
pycurl 7.19.0: ######################################################## | 100%
xarray 0.9.6: ######################################################### | 100%
pyopenssl 17.0.0: ##################################################### | 100%
anaconda custom: ###################################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: /

```

**Comment by Scheibs** [comment]
I tried with a local installation of anaconda , and this time I got this error :

```
(base) D:\Users\scheiblin-noe01>conda update -n base conda
Solving environment: done

## Package Plan ##

  environment location: D:\Users\scheiblin-noe01\AppData\Local\Continuum\ana
a2

  added / updated specs:
    - conda


The following packages will be UPDATED:

    conda: 4.4.10-py27_0 defaults --> 4.5.0rc0-py27_0 conda-canary

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: failed
ERROR conda.core.link:_execute(481): An error occurred while installing pack
'conda-canary::conda-4.5.0rc0-py27_0'.
IOError(13, 'Permission denied')
Attempting to roll back.

Rolling back transaction: | WARNING conda.gateways.disk:exp_backoff_fn(49):
ught backoff with errno EEXIST 17
done

IOError(13, 'Permission denied')
WindowsError(183, 'Impossible de cr\xe9er un fichier d\xe9j\xe0 existant')
```

**Comment by alanchalk** [comment]
Hi,
Just to say I am having exactly the same issue.  conda just hangs after "Executing environment"

**Comment by krinsman** [comment]
Commenting to say that I am having a similar issue; after running `conda update --all`, Conda appears to be hanging at 

```Executing transaction: done```

(The outputs preceding this were very long since again it was `conda update --all`, so I have omitted them for brevity and because a more detailed bug report has already been given by someone else.)

I wound up killing the process after 5-10 minutes with `Control-C`.

**Comment by suyashkrl** [comment]
i am having the same issue:
Preparing transaction: done
Verifying transaction: \ 
its stuck at verifying transaction

**Comment by shantanu778** [comment]
if u are a linux user just "open as root" and type this comment "conda update -n base conda
". it will update conda....

**Comment by cogmind** [comment]
If you run `conda update`, the following is displayed:

> CondaValueError: no package names supplied
> # If you want to update to a newer version of Anaconda, type:
> #
> # $ conda update --prefix c:\Anaconda2 anaconda

However, running this command results in:

> 
> Solving environment: done
> 
> 
> ==> WARNING: A newer version of conda exists. <==
>   current version: 4.4.11
>   latest version: 4.5.0
> 
> Please update conda by running
> 
>     $ conda update -n base conda
> 

After cancelling `Executing transaction`, I am unable to run `conda`:

> 
> Traceback (most recent call last):
>   File "c:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
>     sys.exit(main())
>   File "c:\Anaconda2\lib\site-packages\conda\cli\main.py", line 112, in main
>     from ..exceptions import conda_exception_handler
>   File "c:\Anaconda2\lib\site-packages\conda\exceptions.py", line 13, in <module>
>     from ._vendor.auxlib.entity import EntityEncoder
>   File "c:\Anaconda2\lib\site-packages\conda\_vendor\auxlib\entity.py", line 246, in <module>
>     from enum import Enum
> ImportError: No module named enum
>

**Comment by rohitsuratekar** [comment]
Same issue on my Windows 10. Mine is stuck at "Verifying Transaction" for more than half an hour. I had to cancel the operation.

**Comment by hskim6543** [comment]
Hi, I had the same issue: Executing transaction failed during conda update. I solved the problem by cmd of administrator's mode. It works for same command.

**Comment by girouxem** [comment]
I've been having the same problem when trying to create an env for antiSMASH. It stalls after:

`Preparing transaction: done`
`Verifying transaction: done`
`Executing transaction: - dbus post-link :: /etc/machine-id not found ..`
`dbus post-link :: .. using /proc/sys/kernel/random/boot_id`

I had completed a conda clean -a yesterday, as well as conda update -n base conda, thinking it would help solve this issue, but here we are today, and it's happening again. Yesterday the env would be created after waiting ~10-15 minutes at this point (although the package didn't work), but today it appears completely stalled here.

**Comment by scheckley** [comment]
same here on MacOS 10.13.6 and linux-ppc64le, using the latest version of miniconda.

**Comment by tcpekin** [comment]
I am having a similar problem on Windows 10 using the Git Bash prompt. I cannot move beyond executing transaction. This is with the latest version of miniconda.

**Comment by liouvetren** [comment]
Why are these steps even needed? This feature sucks.

**Comment by maziyarpanahi** [comment]
I am getting this too often and it is really hard when I am running ansible on 30 Ubuntu servers. I have clean, update, all sorts of workaround in my playbooks but every now and then I get this.

**Comment by jordangumm-progenity** [comment]
I keep running into this as well.  I ctrl-c exited and the environment seems to be fine.  Any suggestions for how to profile this?

**Comment by maziyarpanahi** [comment]
Well, I share my experience. As I said I have Ansible playbook to do these things remotely and silently. If I use `-c` for the channel in the install command, then I get this error left to right and time to time. But if I add the channel into the config and remove `-c` entirely from the install command, then I see no such error! Don't know the relations or maybe I do something wrong in my Playbook, but this solved my problem.

**Comment by hemangjoshi37a** [comment]
have anyone solved the issue yet??

**Comment by jmcgove** [comment]
I got the same issue when I updated a conda environment   `conda env update -f environment.yml`
```Executing transaction: | dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
```
Anyone know?

**Comment by jmcgove** [comment]
I got the same issue when I updated a conda environment `conda env update -f environment.yml`
```Executing transaction: | dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id
```
Anyone know?

**Comment by AlexanderStohr** [comment]
same problem observed on a remote controlled windows machine:
`Executing transaction: /`
i had no chance to advance because the used SSH login seems to ignore any Ctrl+C/D/Z keypresses.

**Comment by rileysparsons** [comment]
I fixed my issue by running with the command with `sudo`. It was stalling at `Executing transaction: done`.

**Comment by AFTownsend** [comment]
Similar to @rileysparsons I ran the command from an elevated Anaconda Powershell Command Prompt (run as administrator). I also left it for longer and it did eventually complete. Not sure if it was the elevated command prompt or my patience that did it.

**Comment by BigBorg** [comment]
Get the same problem. I'm using miniconda to create a new env with yaml file and it stuck at "Executing transaction: done".

**Comment by sharkweek** [comment]
I have been getting the same problem when executing `conda update --all` on Windows 10.

I did some digging, however, and discovered that during the `Executing transaction` operation, it seems to be creating instances of `pythonw.exe` on a loop. Each time it created one, it would ramp up to 10MB of memory before the CPU activity dropped out to 0. Then it would create a new one and repeat the process. My Task Manager at least 150 of them and counting before I killed them all.

I tried killing all instances of `pythonw.exe` but left `python.exe` alone, and that seemed to let it keep doing what it needed to do.

**Comment by tengteng** [comment]
I have the same issue.

I ran `conda env create -v -v -v -f blablabla.yml`
then the process hang with error logs below:
```
TRACE conda.gateways.disk.delete:rm_rf(166): rm_rf failed. Not a link, file, or directory: /root/anaconda3/envs/myenv/.condatmp
```
Under myenv dir there's no .condatmp file but several .tmpblablabla files.

It's not a problem when I run this manually. But it's a disaster when this step is executed in a Dockerfile. Please fix it.

**Comment by sobayed** [comment]
Same problem here when running `conda env create -f environment.yml` (stuck at the last line forever):
```
TRACE conda.gateways.disk.delete:rm_rf(160): rm_rf /home/vagrant/.conda/envs/myenv/conda-meta/history.c~
TRACE conda.gateways.disk.delete:rm_rf(166): rm_rf failed. Not a link, file, or directory: /home/vagrant/.conda/envs/myenv/conda-meta/history.c~
TRACE conda.gateways.disk.delete:rm_rf(160): rm_rf /home/vagrant/.conda/envs/myenv/.condatmp
``` 
<details>
 <summary><code>conda info</code></summary>

```
active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/vagrant/.condarc
 populated config files :
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages :
       base environment : /opt/conda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /home/vagrant/.conda/pkgs
       envs directories : /home/vagrant/.conda/envs
                          /opt/conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/4.15.0-50-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by enricoschroeder** [comment]
Same problem here, however I observed that is not happening for me (Docker Ubuntu 16.04 environment) when using Conda 4.5.12. Initially tried the newer 4.6.14 and 4.7.10. and both exhibit this problem.

**Comment by hardianlawi** [comment]
I encountered the same problem with conda `4.7.12`

**Comment by snazari** [comment]
Im having this issue also.

**Comment by Guptajakala** [comment]
The problem still exists.

**Comment by mickeyouyou** [comment]
same situation on Ubuntu 18.04 plarform .

**Comment by webbuildermn** [comment]
I had the same problem, then suddenly it worked after just waiting around 5 minutes after which it prompted me on Windows 10 to allow python.exe to run (3 or 4 times), which I assume would have been avoided had I run as admin.

**Comment by cmkobel** [comment]
Same problem. In many different environments. Also new ones.

**Comment by DenisYarullin** [comment]
Same problem, creating environment inside docker (dockerfile).

**Comment by gabi939** [comment]
OS ubuntu 18.04
anaconda 14.7.12

This worked for me!!

After entering anaconda3/envs/envName/lib some files that should have been installed were missing on the file explorer, but after I searched the path manually everything refreshed and it worked.

**Comment by episodeyang** [comment]
For me it took a minute or two, and then it just finished.

**Comment by ra67052** [comment]
I had the same issues in Windows, went to task manager and killed the conda.exe process and then finished the install :)

**Comment by KayvanShah1** [comment]
While installing the anaconda navigator -
during execution of transactions I got many debug issues stating win32 etc.... on windows 10.
These errors are actually the most frustrating stopping the things that we are doing. 
Don't exactly know happening these days while upgrading few packages using conda.
Cannot reinstall this software once again need to find an alternative.
Google Colab is better alternative but uploading data on Google drive is troublesome.
Resetting windows and formatting the data on drive is the only last way I can see but that can can remove other data too.

**Comment by EricHofer** [comment]
Completed this today.  
- Conda version 4.8.2
- Ubuntu 18.04 LTS (on WLS)
Took over an hour but in the end it did finish successfully.

**Comment by mcmasty** [comment]
Same Issue

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: / 
```

Has been running for 5 hours with the slash doing circles 

This was happening yesterday, so `ctrl-c`, `ctrl-\`  ... to kill it... then conda environment in corrupted state.

even did a fresh install of miniconda3

**Comment by EricHofer** [comment]
I reinstalled Ubuntu

**Comment by Pratikbm2124** [comment]
I waited for some time(when it got stuck on "Executing Transaction") and when I got frustrated I just pressed 'enter'. It worked , the process completed.  :-)

**Comment by AlexanderStohr** [comment]
> I waited for some time(when it got stuck on "Executing Transaction") and when I got frustrated I just pressed 'enter'. It worked , the process completed. :-)

That solution typically will not work in automated setups, especially not for nightly builds or testing.

But good hint that some "readln()" or similar might create and an "enter" press will solve the problem for certain cases. either its a direct pause or its just introducing some "trigger" or "randomisation-kick" into an otherwise dead-locked internal or external communication/sychornisation process.

**Comment by Davidvandijcke** [comment]
> > I waited for some time(when it got stuck on "Executing Transaction") and when I got frustrated I just pressed 'enter'. It worked , the process completed. :-)
> 
> That solution typically will not work in automated setups, especially not for nightly builds or testing.
> 
> But good hint that some "readln()" or similar might create and an "enter" press will solve the problem for certain cases. either its a direct pause or its just introducing some "trigger" or "randomisation-kick" into an otherwise dead-locked internal or external communication/sychornisation process.

This did it for me.

**Comment by JackLangerman** [comment]
for me explicitly setting   `- pip==20.2` in my environment.yml file fixed it.

**Comment by AJ020599** [comment]
> I have been getting the same problem when executing `conda update --all` on Windows 10.
> 
> I did some digging, however, and discovered that during the `Executing transaction` operation, it seems to be creating instances of `pythonw.exe` on a loop. Each time it created one, it would ramp up to 10MB of memory before the CPU activity dropped out to 0. Then it would create a new one and repeat the process without closing out the old one. My Task Manager had at least 150 of them and counting before I killed them all.
> 
> I tried killing all instances of `pythonw.exe` but left `python.exe` alone, and that seemed to let it keep doing what it needed to do.
> 
> **Update:** Since doing this, it seems that the problem has stopped, and `conda` can install normally now.

I tried doing this, but there were no instances of either python.exe OR pythonw.exe running. Please suggest what to do

**Comment by ekaterinakuzmina** [comment]
> for me explicitly setting `- pip==20.2` in my environment.yml file fixed it.

This + pressing Enter worked for me.

**Comment by Hocnonsense** [comment]
Same error occurs on CentOS-stream-8.

**Comment by Mactarvish** [comment]
Same issue on ubuntu 18.04

**Comment by 5-HT2-A** [comment]
has anyone solved it yet?

**Comment by RxLoutre** [comment]
I think I could sort of solve it using mamba instead of conda. It would yield more errors about what is blocking the process.

**Comment by BrunoArsioli** [comment]
Same issue with macOS Big Sur Version 11.6. Using mamba did not solve the problem for me. [Here](https://github.com/fermi-lat/Fermitools-conda/issues/111) I added more details about what I tried. The installation gets stuck in "Executing Transaction". I tried hitting "enter" as some suggested, and it did not worked for me. Any other clues on how to solve the issue?

**Comment by shoyip** [comment]
Same issue here with Ubuntu 20.04 LTS running on WSL2 on Windows 10, using the Miniconda 3 distribution. None of the previosu suggestions fixes the error. Moreover, Ctrl+C does not kill the process so I have to restart the machine itself. Any clue? Thanks in advance!

**Comment by BrunoArsioli** [comment]
> Same issue here with Ubuntu 20.04 LTS running on WSL2 on Windows 10, using the Miniconda 3 distribution. None of the previous suggestions fixes the error. Moreover, Ctrl+C does not kill the process so I have to restart the machine itself. Any clue? Thanks in advance!
> 
> This is a screenshot of htop from another terminal, SIGTERM does not kill the process. What is happening? ![htop_conda](https://user-images.githubusercontent.com/3371928/135420755-69e39c2d-febe-4a7c-a664-dce1f0f23bf2.png)

here is a description of everything I tried: https://github.com/fermi-lat/Fermitools-conda/issues/111
There are some ideas there. Let us know if you find a solution.

**Comment by epassaro** [comment]
We're experimenting the same issue in the Numba nightly pipeline: https://app.circleci.com/pipelines/github/numba/numba-integration-testing/923/workflows/447efbbd-b177-4882-8cba-8be4759a5c1c/jobs/9188

This pipeline worked fine until September, approximately.

**Comment by ecollins** [comment]
Issue still persists. Over the past 5 years, I can count on one hand the number of times Conda has worked without freezing at some point in the process.

**Comment by raynehe** [comment]
Same issue on ubuntu 20.04

**Comment by leezx** [comment]
Same issue. So many people stuck here. It should be addressed ASAP. Where are the conda developers??? @kalefranz @ilanschnell @asmeurer @msarahan @soapy1 @electronwill

**Comment by JackLangerman** [comment]
> for me explicitly setting `- pip==20.2` in my environment.yml file fixed it.

@leezx did you try fixing your pip version or any of the other suggestions in the thread?

**Comment by alexanderLinear** [comment]
> > for me explicitly setting `- pip==20.2` in my environment.yml file fixed it.
> 
> @leezx did you try fixing your pip version or any of the other suggestions in the thread?

Why should it work with exactly one specific version of pip - and why should i like to nail down my whole projects to only this one exact version? There are more needs and thus requirements in a project than only this one.

**Comment by danschef** [comment]
I just added the `--debug` flag to the `conda update` command.

In my case, it hangs at 
```python
Executing transaction: ...working... INFO conda.core.link:_execute_actions(778): ===> UNLINKING PACKAGE: conda-forge/linux-64::google-cloud-sdk-415.0.0-py311h38be061_0 <===
  prefix=/opt/conda/envs/ci_env
```
Seems like it cannot unlink the old version of a package. I am running it within MambaForge installed within an Ubuntu docker container.

Here is the full log - probably helpful for debugging:
[conda_update.log](https://github.com/conda/conda/files/10574195/conda_update.log)

**Comment by billypetro** [comment]
I am running Windows 11 and have the same issues. I hit the Enter button after 20 min of waiting and go the following message

 Windows 64-bit packages of scikit-learn can be accelerated using scikit-learn-intelex.
    More details are available here: https://intel.github.io/scikit-learn-intelex

    For example:

        $ conda install scikit-learn-intelex
        $ python -m sklearnex my_application.py


done  (with the cursor blinking now 4 hours later)

**Comment by nofreewill42** [comment]
After like half an hour I stood up and went for lunch, came back 2 hours later and it's finished.

**Comment by Loss-of-time** [comment]
the same issue
and when i enter "enter"
it shows :
ERROR conda.core.link:_execute(945): An error occurred while installing package 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge::zstd-1.5.5-h12be248_0'.
Rolling back transaction: done

[Errno 13] Permission denied: '......\\.conda\\Library\\bin\\zstd.dll'
()

**Comment by alessandriniluca** [comment]
I am encountering the same error (until yesterday everything worked fine).

- O.S.: Arch Linux
- Output of `conda --version`: 23.10.0
- Installed through: [Arch User Repository](https://aur.archlinux.org/packages/miniconda3)
- What I am trying to run: `conda env create -f condaenv.yml`, with `condaenv.yml` as the following:
  ```yaml
  name: testenv
  channels:
      - conda-forge
  dependencies:
      - python=3.8
      - cudatoolkit-dev=11.1.1
  ```
  
If I interrupt it with with `Ctrl`+`C`:
```
ERROR conda.core.link:_execute(945): An error occurred while installing package 'conda-forge::cudatoolkit-dev-11.1.1-py38h497a2fe_0'.
```
If I run it with `--debug` option, it get stucked at:
```
DEBUG conda.core.link:run_script(1545): for conda-forge::cudatoolkit-dev-11.1.1-py38h497a2fe_0 at /home/<username>/.conda/envs/testenv, executing script: $ /usr/bin/bash /home/<username>/.conda/envs/testenv/.tmpd_rh13ll
DEBUG conda.gateways.subprocess:subprocess_call(86): executing>> /usr/bin/bash /home/<username>/.conda/envs/testenv/.tmpd_rh13ll
```

**Comment by hemangjoshi37a** [comment]
This issue is old af. I just don't use conda nowadays, simply use pip and regular python without conda .

**Comment by DsDastgheib** [comment]
Seems a little stupid
I got an error on installing something that required CUDA_HOME, then I used
conda install -c conda-forge cudatoolkit-dev -y
and this happened to me, that is stuck in executing transaction
then I realized I needed to install [cuda-toolkit from nvidia](https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=Ubuntu&target_version=20.04&target_type=deb_network), and the first error solved.

**Comment by hemangjoshi37a** [comment]
can't believe this issue exists after 8 years not being solved.

**Comment by karel10** [comment]
It apparently was stuck at:
"Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: -"

After a while, I hit enter and got to:
"Executing transaction: -
done"

After that, I waited a bit more, it looked stuck again. Enter did nothing. Then in dispair I started typing some random characters, and as magic, it apparently had finished successfully.

**Comment by hemangjoshi37a** [comment]
I just removed conda entirely and using natively pipx and pip install for this .

**Comment by sam31046** [comment]
2025, same

**Comment by alessandriniluca** [comment]
> 2025, same

I had the same problem, but basically I noticed that during "executing transaction", it is instead downloading other stuff. If you have a slow connection, it may take a lot. To confirm that, just monitor network activity of your pc

**Comment by sam31046** [comment]
> > 2025, same
> 
> I had the same problem, but basically I noticed that during "executing transaction", it is instead downloading other stuff. If you have a slow connection, it may take a lot. To confirm that, just monitor network activity of your pc

Could conda show the log when doing "executing transaction" ?

**Comment by iquasere** [comment]
This hanging is due to some post-transaction scripts, that fail to finish (hanging instead). Running with `-vvv`, it shows:
```
DEBUG conda.core.link:run_script(1550): for defaults::r-base-4.3.1-h8399a1e_1 at /home/username/.conda/envs/myenv, executing script: $ /usr/bin/bash /home/username/.conda/envs/myenv/.tmp5c_x9sze
DEBUG conda.gateways.subprocess:subprocess_call(97): executing>> /usr/bin/bash /home/username/.conda/envs/myenv/.tmp5c_x9sze
```
The contents of these hanging scripts are all like this:
```
eval "$(/home/username/miniconda3/bin/conda shell.posix hook)"
conda activate  /home/username/.conda/envs/myenv
. /home/username/.conda/envs/myenv/bin/.r-base-post-link.sh
```
And the hanging part is the second line - `conda activate  /home/username/.conda/envs/myenv`. After ctrl+cing, this `conda activate` is finishes just fine, but the package was never installed.

**Comment by isLiHailong** [comment]
或许很奇怪，但我在执行ctrl+c之后，虚拟环境得到了激活，我人都惊呆了

**Comment by alexanderLinear** [comment]
> This hanging is due to some post-transaction scripts, that fail to finish (hanging instead).

> ```
> conda activate  /home/username/.conda/envs/myenv
> ```

So for now it tracks down to a "conda activate" command.

Can that now be classified as a conda "activate" command problem? Will this need a spin-off ticket? Any chance to have a reproducible scenario where the problem happens?

**Comment by iquasere** [comment]
It is still a `conda install` problem as well, since the same behavior is observed while installing packages. But it seems it has spread into `conda activate`.

**Comment by iquasere** [comment]
A bit more detail, in my case the problem was the following command:
```
/home/username/.conda/envs/r-env/lib/R/bin/exec/R --no-restore --no-echo --args nextArg--library=/home/username/.conda/envs/r-env/lib/R/librarynextArg/home/username/.conda/envs/r-env/share/genomeinfodbdata-1.2.13/"GenomeInfoDbData_1.2.13.tar.gz"
```
Which seems to be badly formatted, and never ends. This, while `Executing transaction` keeps rolling around. `htop` allowed to see this is the specific function that is never ending, at least in my case.

So, running the install/create command with `bioconductor-genomeinfodbdata=1.1.0` fixed it for me. The 1.2.13 version seems to be broken.

For anyone else who encounters a similar problem, try these steps:
1. Run the install command
2. Run htop while it is hanging
3. Look for the real command that is hanging, and try to get the package and version screwing it up
4. Install another version of that package

**Comment by tosroka** [comment]
> This hanging is due to some post-transaction scripts, that fail to finish (hanging instead). Running with `-vvv`, it shows:
> 
> ```
> DEBUG conda.core.link:run_script(1550): for defaults::r-base-4.3.1-h8399a1e_1 at /home/username/.conda/envs/myenv, executing script: $ /usr/bin/bash /home/username/.conda/envs/myenv/.tmp5c_x9sze
> DEBUG conda.gateways.subprocess:subprocess_call(97): executing>> /usr/bin/bash /home/username/.conda/envs/myenv/.tmp5c_x9sze
> ```
> 
> The contents of these hanging scripts are all like this:
> 
> ```
> eval "$(/home/username/miniconda3/bin/conda shell.posix hook)"
> conda activate  /home/username/.conda/envs/myenv
> . /home/username/.conda/envs/myenv/bin/.r-base-post-link.sh
> ```

I investigated this path a bit further, I was installing `cudatoolkit-dev`, so the file in my case was `/home/user/miniconda3/envs/env/bin/.cudatoolkit-dev-post-link.sh`. Looks like it was downloading a large installer quietly and it's just running in the background properly, killing with Ctrl+C would actually corrupt the conda env for me. Checking htop, preferably in tree mode with F5, shows what's going on. Maybe this will help somebody.
