### ISSUE TITLE
failure to download from ftp with username /password specified in the ftp url

### ISSUE THREAD

**Issue by jerowe** [conda/conda#7003]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

```
Downloading source to cache: bcl2fastq-2.20.tar.gz                                                                                                                                                           
Downloading ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-tar.zip                                                                                            
Traceback (most recent call last):                                                                                                                                                                           
  File "/opt/conda/bin/conda-build", line 6, in <module>                                                                                                                                                     
    sys.exit(conda_build.cli.main_build.main())                                                                                                                                                              
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 342, in main                                                                                                             
    execute(sys.argv[1:])                                                                                                                                                                                    
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 333, in execute                                                                                                          
    noverify=args.no_verify)                                                                                                                                                                                 
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 97, in build                                                                                                                        
    need_source_download=need_source_download, config=config)                                                                                                                                                
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1524,in build_tree                                                                                                                
    config=config)                                                                                                                                                                                           
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1062,in build                                                                                                                     
    config=config)                                                                                                                                                                                           
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 86, in parse_or_try_download                                                                                                     
    source.provide(metadata, config=config)                                                                                                                                                                  
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 519,in provide                                                                                                                   
    unpack(metadata, config=config)                                                                                                                                                                          
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 83, in unpack                                                                                                                    
    src_path = download_to_cache(meta, config)                                                                                                                                                               
  File "/opt/conda/lib/python3.6/site-packages/conda_build/source.py", line 62, in download_to_cache                                                                                                         
    download(url, path)                                                                                                                                                                                      
  File "/opt/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 540, in download                                                                                                           
    gateway_download(url, dst_path, md5)                                                                                                                                                                     
  File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 174, indecorated                                                                                                                    
    return f(*args, **kwds)                                                                                                                                                                                  
  File "/opt/conda/lib/python3.6/site-packages/conda/gateways/download.py", line68, in download                                                                                                              
    resp = session.get(url, stream=True, proxies=session.proxies, timeout=timeout)                                                                                                                           
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 515, in get                                                                                                                       
    return self.request('GET', url, **kwargs)                                                                                                                                                                
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 502, in request                                                                                                                   
    resp = self.send(prep, **send_kwargs)                                                                                                                                                                    
  File "/opt/conda/lib/python3.6/site-packages/requests/sessions.py", line 612, in send                                                                                                                      
    r = adapter.send(request, **kwargs)                                                                                                                                                                      
  File "/opt/conda/lib/python3.6/site-packages/conda/gateways/adapters/ftp.py", line 67, in send                                                                                                             
    auth = self.get_username_password_from_header(request)                                                                                                                                                   
  File "/opt/conda/lib/python3.6/site-packages/conda/gateways/adapters/ftp.py", line 198, in get_username_password_from_header                                                                               
    components = decoded.split(':')                                                                                                                                                                          
TypeError: a bytes-like object is required, not 'str'   
```

### Steps to Reproduce

In meta.yaml
```
{% set name = "bcl2fastq" %}
{% set version = "2.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: "ftp://webdata2:webdata2@ussd-ftp.illumina.com/downloads/software/bcl2fastq/bcl2fastq2-v2-20-0-tar.zip"
  fn: {{ name|lower }}-{{ version }}.zip
```

## Expected Behavior

It should download. ;-)

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.34
       conda is private : False
      conda-env version : 4.3.34
    conda-build version : 2.1.17
         python version : 3.6.1.final.0
       requests version : 2.18.1
       root environment : /opt/conda  (writable)
    default environment : /opt/conda
       envs directories : /opt/conda/envs
                          /root/.conda/envs
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /root/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.34 requests/2.18.1 CPython/3.6.1 Linux/4.10.0-42-generic CentOS/6.9 glibc/2.12
                UID:GID : 0:0
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /root/.condarc <==
channels:
  - bioconda
  - conda-forge
  - defaults
show_channel_urls: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
anaconda-client           1.6.3                    py36_0    conda-forge
asn1crypto                0.22.0                   py36_0    conda-forge
beautifulsoup4            4.5.3                    py36_0    conda-forge
ca-certificates           2017.4.17                     0    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
cffi                      1.10.0                   py36_0    conda-forge
chardet                   3.0.2                    py36_1    conda-forge
clyent                    1.2.1                    py36_0    conda-forge
conda                     4.3.34                   py36_0    conda-forge
conda-build               2.1.17                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
cryptography              1.9                      py36_0    conda-forge
curl                      7.52.1                        0    conda-forge
expat                     2.2.1                         0    conda-forge
filelock                  2.0.6                    py36_0    conda-forge
git                       2.12.2                        4    conda-forge
idna                      2.5                      py36_0    conda-forge
jinja2                    2.9.5                    py36_0    conda-forge
libffi                    3.2.1                         3    conda-forge
libiconv                  1.14                          4    conda-forge
markupsafe                1.0                      py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
openssl                   1.0.2l                        0    conda-forge
packaging                 16.8                     py36_0    conda-forge
patchelf                  0.9                           2    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pkginfo                   1.2.1                    py36_0    conda-forge
pycosat                   0.6.1                    py36_0    conda-forge
pycparser                 2.17                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyopenssl                 16.2.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pysocks                   1.6.7                    py36_0    conda-forge
python                    3.6.1                         3    conda-forge
python-dateutil           2.6.0                    py36_0    conda-forge
pytz                      2017.2                   py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.1                   py36_0    conda-forge
ruamel_yaml               0.11.14                  py36_0    conda-forge
setuptools                33.1.1                   py36_0    conda-forge
six                       1.10.0                   py36_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tini                      0.14.0                        0    conda-forge
tk                        8.5.19                        1    conda-forge
urllib3                   1.21.1                   py36_1    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge

```
</p></details>

**Comment by kalefranz** [comment]
Probably need either

    components = ensure_text_type(decoded).split(':')

or

    components = decoded.split(b':')

**Comment by npavlovikj** [comment]
I am getting the same exact error for the same exact package.

My `conda info` is:
```
     active environment : base
    active env location : /tmp/miniconda/miniconda
            shell level : 1
       user config file : /home/fedora/.condarc
 populated config files : /tmp/miniconda/miniconda/.condarc
                          /home/fedora/.condarc
          conda version : 4.6.12
    conda-build version : 3.17.8
         python version : 3.6.7.final.0
       base environment : /tmp/miniconda/miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /tmp/miniconda/miniconda/pkgs
                          /home/fedora/.conda/pkgs
       envs directories : /tmp/miniconda/miniconda/envs
                          /home/fedora/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.12 requests/2.20.1 CPython/3.6.7 Linux/4.13.5-200.fc26.x86_64 fedora/26 glibc/2.25
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

Has this been fixed in the newer conda releases?
