### ISSUE TITLE
conda env create w/ custom channel leads to assert subdir == self.channel.subdir failing

### ISSUE THREAD

**Issue by pnathan** [conda/conda#7008]
Bug report. 

## Current Behavior

It appears that when I have `http://<private-repository>` as a conda channel, either in the .condarc or in the yml environment file, the below exception occurs.

### Steps to Reproduce

```
(localbin) pnathan@linux-u6ux:~/shared/<redacted> conda env create --file ingest.yml
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda_env/installers/conda.py", line 35, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 504, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 437, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 178, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/solve.py", line 559, in _prepare
        self.subdirs, prepared_specs)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 217, in get_reduced_index
        new_records = query_all(spec)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 186, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 90, in query
        self.load()
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 134, in load
        _internal_state = self._load()
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 221, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/pnathan/miniconda2/lib/python2.7/site-packages/conda/core/repodata.py", line 295, in _process_raw_repodata_str
        assert subdir == self.channel.subdir
    AssertionError

`$ /home/pnathan/miniconda2/bin/conda-env create --file ingest.yml`

  environment variables:
         ALSA_CONFIG_PATH=/etc/alsa-pulse.conf
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/home/pnathan/miniconda2
                  MANPATH=/usr/local/man:/usr/share/man
                     PATH=/home/pnathan/miniconda2/bin:/home/pnathan/localbin/bin:/home/pnathan/
                          bin:/home/pnathan/bin/sbt/bin/:/home/pnathan/bin:/home/pnathan/bin/sbt
                          /bin/:/home/pnathan/bin:/usr/local/bin:/usr/bin:/bin:/usr/lib/mit/sbin
            PYTHONSTARTUP=/etc/pythonstart
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
                 XNLSPATH=/usr/share/X11/nls

     active environment : None
       user config file : /home/pnathan/.condarc
 populated config files : 
          conda version : 4.4.11
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/pnathan/miniconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/pnathan/miniconda2/pkgs
                          /home/pnathan/.conda/pkgs
       envs directories : /home/pnathan/miniconda2/envs
                          /home/pnathan/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/2.7.14 Linux/4.15.6-1-default opensuse/20180227 glibc/2.26
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

And ingest.yml is

```
(localbin) pnathan@linux-u6ux:~/shared/redacted> cat ingest.yml
name: secret-company-project
channels:
- conda-forge
- defaults
- http://redacted.conda.channel.com/python/conda-pkgs
dependencies:
- xarray=0.10.1=py27_0
- redacted-dep=1.0=py27_0
- numba=0.37.0=np114py27h6027bcc_0
- pynio=1.5.0=py27_3

```

I have added and removed the `redacted-dep`, along with the channels; the bug only occurs when the channel is present either in the file or in one of the `.condarc`s. 

The custom repository looks like this: `http://<hostname>/python/conda-pkgs`.

I have replicated this with the Docker `continuumio/miniconda` image as well as a manual conda install on a Suse VM.

## Expected Behavior

Environment built, no exception thrown (or an error message correctly describing the bug in configuration along with a pointer to fix it).

## Environment Information

```
     active environment : None
       user config file : /home/pnathan/.condarc
 populated config files : /home/pnathan/miniconda2/.condarc
                          /home/pnathan/.condarc
          conda version : 4.4.11
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : /home/pnathan/miniconda2  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/default/linux-64
                          https://conda.anaconda.org/default/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/pnathan/miniconda2/pkgs
                          /home/pnathan/.conda/pkgs
       envs directories : /home/pnathan/miniconda2/envs
                          /home/pnathan/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/2.7.14 Linux/4.15.6-1-default opensuse/20180227 glibc/2.26
                UID:GID : 1000:100
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(localbin) pnathan@linux-u6ux:~/shared/mrms2-hrr-ingest> conda config --show-sources
==> /home/pnathan/miniconda2/.condarc <==
channels:
  - defaults

==> /home/pnathan/.condarc <==
channels:
  - conda-forge
  - default
  - defaults


```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(localbin) pnathan@linux-u6ux:~/shared/mrms2-hrr-ingest> conda list --show-channel-urls
# packages in environment at /home/pnathan/miniconda2:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2018.1.18                py27_0    defaults
cffi                      1.11.4           py27h9745a5d_0    defaults
chardet                   3.0.4            py27hfa10054_1    defaults
conda                     4.4.11                   py27_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.1.4            py27h6697b16_0    defaults
enum34                    1.1.6            py27h99a27e9_1    defaults
futures                   3.2.0            py27h7b459c0_0    defaults
idna                      2.6              py27h5722d68_1    defaults
ipaddress                 1.0.19                   py27_0    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
ncurses                   6.0                  h9df7e31_2    defaults
openssl                   1.0.2n               hb7f436b_0    defaults
pip                       9.0.1            py27ha730c48_4    defaults
pycosat                   0.6.3            py27ha4109ae_0    defaults
pycparser                 2.18             py27hefa08c5_1    defaults
pyopenssl                 17.5.0           py27hcee3be0_0    defaults
pysocks                   1.6.7            py27he2db6d2_1    defaults
python                    2.7.14              h1571d57_29    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py27hc5b0589_1    defaults
ruamel_yaml               0.15.35          py27h14c3975_1    defaults
setuptools                38.4.0                   py27_0    defaults
six                       1.11.0           py27h5f960f1_1    defaults
sqlite                    3.22.0               h1bed415_0    defaults
tk                        8.6.7                hc745277_3    defaults
urllib3                   1.22             py27ha55213b_0    defaults
wheel                     0.30.0           py27h2bc6bb2_1    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults

```
</p></details>

**Comment by kalefranz** [comment]
```==> /home/pnathan/.condarc <==
channels:
  - conda-forge
  - default
  - defaults
```

Can you rule out that this isn't because of `default` here, but is indeed because of the presence of `http://<hostname>/python/conda-pkg` in your channels list?

**Comment by pnathan** [comment]
@kalefranz I explicitly removed `http://redacted` and re-added it in both the YML and in `.condarc`, verifying that its presence triggered the assertion.

**Comment by kalefranz** [comment]
I see.  I'm guessing if you look at `http://<private-repository>/linux-64/repodata.json`, the `info.subdir` field doesn't match `linux-64`.  Or it might be `http://<private-repository>/noarch/repodata.json` that's not matching up.

What I mean by that is

```
$ python
>>> import requests
>>> resp = requests.get('http://<private-repository>/linux-64/repodata.json')
>>> print(resp.json()['info']['subdir'])
```

won't match `linux-64`.

**Comment by pnathan** [comment]
🔔   You got it!

```
(localbin) pnathan@linux-u6ux:~/shared/snip> curl http://redacted/python/conda-pkgs/linux-64/repodata.json | jq '.info'  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1048k  100 1048k    0     0   205k      0  0:00:05  0:00:05 --:--:--  240k
{
  "subdir": "tmpBhIdpS"
}
(localbin) pnathan@linux-u6ux:~/shared/snip> curl http://redacted/python/conda-pkgs/noarch/repodata.json | jq '.info'  
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   441  100   441    0     0    543      0 --:--:-- --:--:-- --:--:--   543
{}
```

I infer that the Proper Solution is to go chase our repository maintainers and look *very sad* at them until this is fixed?

**Comment by kalefranz** [comment]
Well, it's technically still a bug in conda.  I consider any assertion error a bug.  But the solution on the conda side is to give you an error message that tells you what's going on.  So yes, you'll still need to fix this on the repository side too :)
