### ISSUE TITLE
Cannot conda update --all

### ISSUE THREAD

**Issue by user015070** [conda/conda#7018]
Dear Community Members:

I am a novice anaconda user. I greatly appreciate if you could provide me with a fix for the following: Since March 12, 2018, it has not been possible to update conda packages using the following command on the terminal: conda update --all

I am using Ubuntu 16.04 on Lenovo thinkpad x250. I am going to paste the output below. I highly appreciate your important help in advance again!

administrator@aaa:~$ conda update --all
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_update.py", line 65, in execute
    install(args, parser, 'update')
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 160, in install
    linked_dists = install_linked(prefix)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 123, in linked
    return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 115, in linked_data
    load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 36, in load_linked_data
    rec = json.load(fi)
  File "/home/administrator/anaconda3/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/administrator/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/administrator/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/administrator/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 199, in get_info_dict
    conda_build_version = conda_build.__version__
AttributeError: module 'conda_build' has no attribute '__version__'

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

`$ /home/administrator/anaconda3/bin/conda info`

    Traceback (most recent call last):
      File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 340, in execute
        info_dict = get_info_dict(args.system)
      File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 199, in get_info_dict
        conda_build_version = conda_build.__version__
    AttributeError: module 'conda_build' has no attribute '__version__'

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

==> /home/administrator/.condarc <==
channels:
  - conda-forge
  - defaults

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

# packages in environment at /home/administrator/anaconda3:
#
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 140, in _main
    exit_code = args.func(args, p)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 242, in execute
    show_channel_urls=context.show_channel_urls)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_list.py", line 172, in print_packages
    installed = linked(prefix)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 123, in linked
    return set(linked_data(prefix, ignore_channels=ignore_channels).keys())
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 115, in linked_data
    load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/core/linked_data.py", line 36, in load_linked_data
    rec = json.load(fi)
  File "/home/administrator/anaconda3/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/administrator/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/administrator/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/administrator/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/administrator/anaconda3/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/home/administrator/anaconda3/lib/python3.5/site-packages/conda/cli/main_info.py", line 199, in get_info_dict
    conda_build_version = conda_build.__version__
AttributeError: module 'conda_build' has no attribute '__version__'

**Comment by user015070** [comment]
Dear Community Members,

I just cleanly reinstalled anaconda. Everything runs smoothly. So, the case closed.
