### ISSUE TITLE
Can't run conda commands after activating environment

### ISSUE THREAD

**Issue by giovannirescia** [conda/conda#7020]
Hi all,

I needed a 32 bit Python environment, so first I ran `export FORCE_CONDA_32BIT=1`, and after that created the environment, and also ran `conda install -c anaconda gcc_impl_linux-32 gcc_linux-32`, due some requirements. The output of that commands was:

```
environment location: /home/giovanni/anaconda3/envs/asr32b

  added / updated specs: 
    - gcc_impl_linux-32
    - gcc_linux-32


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    gcc_impl_linux-32-7.2.0    |       he2ea625_3        70.3 MB  anaconda

The following NEW packages will be INSTALLED:

    binutils_impl_linux-32: 2.28.1-hf6cdf64_3     anaconda
    binutils_linux-32:      7.2.0-24              anaconda
    gcc_impl_linux-32:      7.2.0-he2ea625_3      anaconda
    gcc_linux-32:           7.2.0-24              anaconda

The following packages will be UPDATED:

    ca-certificates:        2017.08.26-h1d4fec5_0          --> 2017.08.26-h1d4fec5_0 anaconda
    certifi:                2018.1.18-py35_0               --> 2018.1.18-py35_0      anaconda
    openssl:                1.0.2n-hb7f436b_0              --> 1.0.2n-hb7f436b_0     anaconda

Proceed ([y]/n)? y

Downloading and Extracting Packages
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
INFO: deactivate-binutils_linux-32.sh made the following environmental changes:
INFO: deactivate-gcc_linux-32.sh made the following environmental changes:
+HOST=i686-conda_cos6-linux-gnu
INFO: activate-binutils_linux-32.sh made the following environmental changes:
+ADDR2LINE=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-addr2line
+AR=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-ar
+AS=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-as
+CXXFILT=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-elfedit
+GPROF=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-gprof
+LD_GOLD=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-ld.gold
+LD=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-ld
+NM=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-nm
+OBJCOPY=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-objdump
+RANLIB=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-ranlib
+READELF=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-readelf
+SIZE=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-size
+STRINGS=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-strings
+STRIP=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-32.sh made the following environmental changes:
+CC=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-cc
+CFLAGS=-march=prescott -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2
+CPP=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=prescott -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og
+GCC_AR=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-gcc-ar
+GCC=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-gcc
+GCC_NM=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=/home/giovanni/anaconda3/envs/pepino32/bin/i686-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
+_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_i686_conda_cos6_linux_gnu
```

After activating the environment, I get the following output:

```
INFO: activate-binutils_linux-32.sh made the following environmental changes:
+ADDR2LINE=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-addr2line
+AR=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-ar
+AS=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-as
+CXXFILT=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-c++filt
+ELFEDIT=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-elfedit
+GPROF=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-gprof
+HOST=i686-conda_cos6-linux-gnu
+LD_GOLD=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-ld.gold
+LD=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-ld
+NM=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-nm
+OBJCOPY=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-objcopy
+OBJDUMP=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-objdump
+RANLIB=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-ranlib
+READELF=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-readelf
+SIZE=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-size
+STRINGS=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-strings
+STRIP=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-strip
INFO: activate-gcc_linux-32.sh made the following environmental changes:
+CC=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-cc
+CFLAGS=-march=prescott -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe
+CPPFLAGS=-DNDEBUG -D_FORTIFY_SOURCE=2 -O2
+CPP=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-cpp
+DEBUG_CFLAGS=-march=prescott -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-all -fno-plt -Og -g -Wall -Wextra -fvar-tracking-assignments -pipe
+DEBUG_CPPFLAGS=-D_DEBUG -D_FORTIFY_SOURCE=2 -Og
+GCC_AR=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-gcc-ar
+GCC=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-gcc
+GCC_NM=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-gcc-nm
+GCC_RANLIB=/home/giovanni/anaconda3/envs/asr32b/bin/i686-conda_cos6-linux-gnu-gcc-ranlib
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now
+_PYTHON_SYSCONFIGDATA_NAME=_sysconfigdata_i686_conda_cos6_linux_gnu
```

The problem is that when I try to run any conda command  (e.g., `conda deactivate`, `source deactivate`, `conda activate <env>`) I get the following error:

```
Failed to import the site module
Traceback (most recent call last):
  File "/home/giovanni/anaconda3/lib/python3.6/site.py", line 548, in <module>
    main()
  File "/home/giovanni/anaconda3/lib/python3.6/site.py", line 530, in main
    known_paths = addusersitepackages(known_paths)
  File "/home/giovanni/anaconda3/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/home/giovanni/anaconda3/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/home/giovanni/anaconda3/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/home/giovanni/anaconda3/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/home/giovanni/anaconda3/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/home/giovanni/anaconda3/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_i686_conda_cos6_linux_gnu'
```

Any idea why that might be?

Also, am using conda 4.4.11 on Ubuntu 16.04.

Thanks!

**Comment by jjhelmus** [comment]
The 32-bit compiler packages will create some issues for the 64-bit Python in the base environment.  Un-setting the **_PYTHON_SYSCONFIGDATA_NAME** environment variable when calling conda should fix the issue.  For example:  `_PYTHON_SYSCONFIGDATA_NAME='' conda deactivate` should work.  See [this comment](https://github.com/conda/conda/issues/7011#issuecomment-371899066) for more details.

**Comment by giovannirescia** [comment]
Worked like a charm, thanks!
