### ISSUE TITLE
Error: conda update anaconda-navigator

### ISSUE THREAD

**Issue by ark00** [conda/conda#7036]
Hi, 
   I was trying to update anaconda-navigator.
  And got the following error report.
  How to solve this issue?

C:\Users\Ark\Anaconda3\Scripts>conda update anaconda-navigator

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\Ark\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Ark\.condarc", position 0

`$ C:\Users\Ark\Anaconda3\Scripts\conda update anaconda-navigator`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Ark\Anaconda3
                 HOMEPATH=\Users\Ark
                     PATH=C:\Users\Ark\Anaconda3\Library\bin;C:\Program Files (x86)\Lenovo\Fus
                          ionEngine;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\W
                          indows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Common
                          Files\lenovo\easyplussdk\bin;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C
                          :\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\Syst
                          em32\WindowsPowerShell\v1.0\;C:\WINDOWS\system32\config\systemprofile\
                          .dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program
                          Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows
                          Kits\10\Windows Performance Toolkit\;C:\Program Files
                          (x86)\Skype\Phone\;C:\Program Files (x86)\OpenVPN\bin;C:\root_v5.34.36
                          \\bin;C:\Users\Ark\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\Microsoft VS Code\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
               PYTHONPATH=C:\root_v5.34.36\bin\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Ark\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Users\Ark\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Ark\Anaconda3\pkgs
                          C:\Users\Ark\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Ark\Anaconda3\envs
                          C:\Users\Ark\AppData\Local\conda\conda\envs
                          C:\Users\Ark\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

Thanks in advance.
AK

**Comment by mbargull** [comment]
```
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\Ark\.condarc", position 0
```
Your `.condarc` file is malformed; edit/delete it.

**Comment by ark00** [comment]
Thank you very much it works now!!
