### ISSUE TITLE
PermissionError for pip managed packages after conda update

### ISSUE THREAD

**Issue by mpizenberg** [conda/conda#7056]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

After conda update, pip managed packages (in particular neovim for me) cannot be updated.
I get "permission denied" errors.

### Steps to Reproduce

Note that conda and neovim python package where already installed at older versions in my system.
```
$ conda update conda
...
$ conda update --all
...
$ pip install --upgrade neovim
Collecting neovim
Requirement already up-to-date: msgpack>=0.5.0 in /home/matthieu/miniconda3/lib/python3.6/site-packages (from neovim)
Requirement already up-to-date: greenlet in /home/matthieu/miniconda3/lib/python3.6/site-packages (from neovim)
Installing collected packages: neovim
  Found existing installation: neovim 0.2.0
    Uninstalling neovim-0.2.0:
Exception:
Traceback (most recent call last):
  File "/home/matthieu/miniconda3/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/home/matthieu/miniconda3/lib/python3.6/site-packages/neovim-0.2.0.dist-info/DESCRIPTION.rst' -> '/tmp/pip-n_mucr__-uninstall/home/matthieu/miniconda3/lib/python3.6/site-packages/neovim-0.2.0.dist-info/DESCRIPTION.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matthieu/miniconda3/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/matthieu/miniconda3/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/home/matthieu/miniconda3/lib/python3.6/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/home/matthieu/miniconda3/lib/python3.6/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/home/matthieu/miniconda3/lib/python3.6/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/home/matthieu/miniconda3/lib/python3.6/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/home/matthieu/miniconda3/lib/python3.6/shutil.py", line 559, in move
    os.unlink(src)
PermissionError: [Errno 13] Permission denied: '/home/matthieu/miniconda3/lib/python3.6/site-packages/neovim-0.2.0.dist-info/DESCRIPTION.rst'
You are using pip version 9.0.1, however version 9.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

## Expected Behavior

I hoped to be able to update my neovim python package. Now I have an issue since my text editor (neovim) requires this package up to date to work.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
            shell level : 0
       user config file : /home/matthieu/.condarc
 populated config files :
          conda version : 4.4.11
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /home/matthieu/miniconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
          package cache : /home/matthieu/miniconda3/pkgs
                          /home/matthieu/.conda/pkgs
       envs directories : /home/matthieu/miniconda3/envs
                          /home/matthieu/.conda/envs
               platform : linux-64
             user-agent : conda/4.4.11 requests/2.18.4 CPython/3.6.4 Linux/4.14.27-1-lts arch/rolling glibc/2.26
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/matthieu/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
async-generator           1.8                       <pip>
attrs                     17.2.0                    <pip>
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2018.1.18                py36_0    defaults
cffi                      1.11.5           py36h9745a5d_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7              py36h5253387_0    defaults
conda                     4.4.11                   py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
cryptography              2.1.4            py36hd09be54_0    defaults
greenlet                  0.4.13                    <pip>
idna                      2.6              py36h82fb2a8_1    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
msgpack                   0.5.6                     <pip>
msgpack-python            0.4.8                     <pip>
ncurses                   6.0                  h9df7e31_2    defaults
neovim                    0.2.0                     <pip>
openssl                   1.0.2n               hb7f436b_0    defaults
packaging                 17.1                     py36_0    defaults
pip                       9.0.1                    py36_5    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pyparsing                 2.2.0            py36hee85983_1    defaults
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.4                hc3d631a_3    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
ruamel_yaml               0.15.35          py36h14c3975_1    defaults
setuptools                38.5.1                   py36_0    defaults
six                       1.11.0           py36h372c433_1    defaults
sortedcontainers          1.5.7                     <pip>
sqlite                    3.22.0               h1bed415_0    defaults
tk                        8.6.7                hc745277_3    defaults
trio                      0.1.0                     <pip>
urllib3                   1.22             py36hbe7ace6_0    defaults
wheel                     0.30.0           py36hfd4bba0_1    defaults
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
yapf                      0.18.0                    <pip>
zlib                      1.2.11               ha838bed_2    defaults
```
</p></details>

**Comment by mpizenberg** [comment]
It appears all my neovim pip files were root rights ... I might have use `sudo pip install neovim` instead of `pip install neovim` in the past.
Sorry I'll close this issue.
