### ISSUE TITLE
conda skeleton doesn't generate the proper meta.yaml

### ISSUE THREAD

**Issue by dturaev** [conda/conda#7058]
I followed the guide (https://conda.io/docs/user-guide/tutorials/build-pkgs-skeleton.html) to prepare a recipe for seqmagick (https://pypi.python.org/pypi/seqmagick/0.7.0). After the skeleton command generated the config files, the build command failed with a somewhat cryptic error:
```
...
Source cache directory is: /apps/anaconda3/conda-bld/src_cache
Found source in cache: seqmagick-0.7.0_e5bd29a5bf.tar.gz
Extracting download
source tree in: /apps/anaconda3/conda-bld/seqmagick_1521544476937/work
Traceback (most recent call last):
  File "setup.py", line 47, in <module>
    license="GPL V3")
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/__init__.py", line 128, in setup
    _install_setup_requires(attrs)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/__init__.py", line 123, in _install_setup_requires
    dist.fetch_build_eggs(dist.setup_requires)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/dist.py", line 461, in fetch_build_eggs
    replace_conflicting=True,
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/pkg_resources/__init__.py", line 866, in resolve
    replace_conflicting=replace_conflicting
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1146, in best_match
    return self.obtain(req, installer)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1158, in obtain
    return installer(requirement)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/dist.py", line 528, in fetch_build_egg
    return cmd.easy_install(req)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 661, in easy_install
    not self.always_copy, self.local_index
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/package_index.py", line 660, in fetch_distribution
    self.find_packages(requirement)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/package_index.py", line 493, in find_packages
    self.scan_url(self.index_url + requirement.unsafe_name + '/')
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/package_index.py", line 833, in scan_url
    self.process_url(url, True)
  File "/apps/anaconda3/conda-bld/seqmagick_1521544476937/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol/lib/python3.6/site-packages/setuptools/package_index.py", line 328, in process_url
    "Be sure to add all dependencies in the meta.yaml  url=%s" % url)
RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.python.org/simple/nose/
Traceback (most recent call last):
  File "/apps/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 2097, in build_tree
    notest=notest,
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1370, in build
    utils.check_call_env(cmd, env=env, cwd=src_dir, stats=build_stats)
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 294, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/apps/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 273, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/apps/anaconda3/conda-bld/seqmagick_1521544476937/work/conda_build.sh']' returned non-zero exit status 1.
...
```
After adding "nose" to the meta.yaml dependencies, conda build worked. Also the Python version (>=3.4) was not specified.

**Comment by kalefranz** [comment]
`conda skeleton` is part of `conda-build`.  You should file your issue at https://github.com/conda/conda-build/issues/new.  I would move it for you, except you didn't include the output of `conda info` (as instructed in the issue template), so I don't know what versions of conda and conda-build you have to even know if your issue is current, relevant, and valid.
