### ISSUE TITLE
Error: "Warning: could not import binstar_client (unknown encoding: cp65001)"

### ISSUE THREAD

**Issue by hvaron** [conda/conda#7073]
##I'm submitting a bug report.

## Current Behavior
I tried the command "conda update conda" in Windows 10 command prompt and I got this response (see steps to reproduce)

### Steps to Reproduce

```
G:\>conda update conda
Warning: could not import binstar_client (unknown encoding: cp65001)Fetching package metadata: ....
.Solving package specifications: .........

Package plan for installation in environment C:\Users\HVaron\AppData\Local\Continuum\Anaconda2:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_update.py", line 64, in execute
    install.install(args, parser, 'update')
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\install.py", line 411, in install
    plan.display_actions(actions, index, show_channel_urls=args.show_channel_urls)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 64, in display_actions
    print_dists(disp_lst)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\plan.py", line 47, in print_dists
    print(line)
LookupError: unknown encoding: cp65001

G:\>
```

## Environment Information
```
G:\>conda info
Warning: could not import binstar_client (unknown encoding: cp65001)Current conda install:

             platform : win-64
        conda version : 4.0.8
  conda-build version : 1.20.0
       python version : 2.7.13.final.0
     requests version : 2.9.1
     root environment : C:\Users\HVaron\AppData\Local\Continuum\Anaconda2  (writable)
  default environment : C:\Users\HVaron\AppData\Local\Continuum\Anaconda2
     envs directories : C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\envs
        package cache : C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/win-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
G:\> conda config --show-sources
usage: conda-script.py config [-h] [--json] [--system | --file FILE]
                              (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY)
                              [-f]
conda-script.py config: error: one of the arguments --get --add --set --remove --remove-key is required
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
G:\>conda list --show-channel-urls
# packages in environment at C:\Users\HVaron\AppData\Local\Continuum\Anaconda2:
#
Traceback (most recent call last):
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\Scripts\pip-script.py", line 3, in <module>
    import pip
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\pip\__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\pip\vcs\mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\pip\download.py", line 36, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\pip\utils\ui.py", line 57, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\pip\utils\ui.py", line 50, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\Scripts\conda-script.py", line 5, in <module>
    sys.exit(main())
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 139, in main
    args_func(args, p)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main.py", line 146, in args_func
    args.func(args, p)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_list.py", line 273, in execute
    json=args.json, show_channel_urls=args.show_channel_urls)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\cli\main_list.py", line 185, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\pip.py", line 106, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\pip.py", line 47, in installed
    args = pip_args(prefix)
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\site-packages\conda\pip.py", line 26, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "C:\Users\HVaron\AppData\Local\Continuum\Anaconda2\lib\subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['C:\\Users\\HVaron\\AppData\\Local\\Continuum\\Anaconda2\\Scripts\\pip.exe', '-V']' returned non-zero exit status 1
```
</p></details>

**Comment by kalefranz** [comment]
conda update conda

**Comment by kalefranz** [comment]
This is a unicode encoding related error on Windows in a base environment containing python2 instead of python3, which we don't right now have the resources to support.  The easiest solution is to download the latest Miniconda3 or Anaconda3, and then if you need python2, use specialized conda environments.
