### ISSUE TITLE
EnvironmentLocationNotFound for conda list on Cygwin

### ISSUE THREAD

**Issue by alchenist** [conda/conda#7074]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

`conda list` on zsh on Cygwin with conda 4.4+ raises `EnvironmentLocationNotFound` for base environment. This is an installation recently upgraded from conda 4.3.x; 

### Steps to Reproduce

```
~> $_CONDA_EXE shell.posix activate
\export CONDA_DEFAULT_ENV='base'
\export CONDA_EXE='/cygdrive/c/ProgramData/Anaconda3/Scripts/conda.exe'
\export CONDA_PREFIX='C:\ProgramData\Anaconda3'
\export CONDA_PROMPT_MODIFIER=''
\export CONDA_PYTHON_EXE='/cygdrive/c/ProgramData/Anaconda3/python.exe'
\export CONDA_SHLVL='1'
\export PATH='/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/cygdrive/c/ProgramData/Anaconda3/Library/usr/bin:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/cygdrive/c/ProgramData/Anaconda3/Scripts:/cygdrive/c/ProgramData/Anaconda3/bin:/usr/local/bin:/usr/local/sbin:/home/achen/.local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/cygdrive/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/cygdrive/c/Users/achen/.babun:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files (x86)/Nmap:/home/achen/.winpty'

~> conda activate
~> conda list

EnvironmentLocationNotFound: Not a conda environment: C:\ProgramData\Anaconda3

~> conda list --verbose
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 812, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 125, in execute
    raise EnvironmentLocationNotFound(prefix)
conda.exceptions.EnvironmentLocationNotFound: Not a conda environment: C:\ProgramData\Anaconda3

```

## Expected Behavior

`conda list` should list packages that are currently in base environment. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : C:\ProgramData\Anaconda3
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\achen\.babun\cygwin\home\achen\.condarc
 populated config files : C:\Users\achen\.babun\cygwin\home\achen\.condarc
          conda version : 4.5.0
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\achen\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\achen\Projects\envs
                          C:\Users\achen\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\achen\.babun\cygwin\home\achen\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.2 Windows/7 Windows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\achen\.babun\cygwin\home\achen\.condarc <==
changeps1: False
create_default_packages:
  - pip
  - ipykernel
  - nb_conda_kernels
envs_dirs:
  - C:\Users\achen\Projects\envs
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by alchenist** [comment]
Update: adding trailing backslash to `CONDA_PREFIX` fixes this?  
```
~> export CONDA_PREFIX='C:\ProgramData\Anaconda3\'
~> conda list                                             
# packages in environment at C:\ProgramData\Anaconda3\:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
alabaster                 0.7.10                    <pip>
alabaster                 0.7.10           py36hcd07829_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.5                     <pip>
anaconda-client           1.6.5            py36hd36550c_0
...
```

**Comment by kalefranz** [comment]
Well that's interesting...

**Comment by mingwandroid** [comment]
You'd be much better off using MSYS2 than Cygwin when you want to interoperate between Windows and posixy software.

Simply Cygwin do no care about native Windows software.

**Comment by alchenist** [comment]
@mingwandroid appreciate the advice and will think about it for the long term. For now, I just want my development environment to work again! 

Turns out `print`ing the result of `activator.execute()` to stdout (at least with Python 3.6) autoconverts all the newlines to Windows-style, which results in carriage returns at the end of every environment variable. I'm fixing this locally in conda.sh by piping the results of conda activate/deactivate/reactivate through dos2unix before evaling. 

Not sure what the best approach is if this were to be changed in conda.

```
$_CONDA_EXE shell.posix activate | cat -v
export CONDA_DEFAULT_ENV='base'^M
export CONDA_PREFIX='C:\ProgramData\Anaconda3'^M
export CONDA_PROMPT_MODIFIER=''^M
export CONDA_PYTHON_EXE='/cygdrive/c/ProgramData/Anaconda3/python.exe'^M
export CONDA_SHLVL='1'^M
export PATH='/cygdrive/c/ProgramData/Anaconda3:/cygdrive/c/ProgramData/Anaconda3/Library/mingw-w64/bin:/cygdrive/c/ProgramData/Anaconda3/Library/usr/bin:/cygdrive/c/ProgramData/Anaconda3/Library/bin:/cygdrive/c/ProgramData/Anaconda3/Scripts:/cygdrive/c/ProgramData/Anaconda3/bin:/usr/local/bin:/usr/local/sbin:/home/achen/.local/bin:/usr/bin:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/Program Files (x86)/Intel/iCLS Client:/cygdrive/c/Program Files/Intel/iCLS Client:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/cygdrive/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/Intel(R) Management Engine Components/IPT:/cygdrive/c/Program Files/Intel/WiFi/bin:/cygdrive/c/Program Files/Common Files/Intel/WirelessCommon:/cygdrive/c/Program Files (x86)/Windows Kits/8.1/Windows Performance Toolkit:/cygdrive/c/Program Files/Git/cmd:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/Client SDK/ODBC/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/140/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/140/Tools/Binn/ManagementStudio:/cygdrive/c/Program Files/Microsoft SQL Server/130/Tools/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/cygdrive/c/Program Files (x86)/Microsoft SQL Server/130/DTS/Binn:/cygdrive/c/Users/achen/.babun:/cygdrive/c/Program Files/Docker Toolbox:/cygdrive/c/Program Files (x86)/Nmap:/home/achen/.winpty'^M
```
