### ISSUE TITLE
conda update conda

### ISSUE THREAD

**Issue by yinhangbupt** [conda/conda#708]
Unlinking packages ...
An unexpected error has occurred, please consider sending the            |  50%
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 34, in execute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 247, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 387, in execute_actions
    execute_plan(plan, index, verbose)
  File "C:\Anaconda\lib\site-packages\conda\plan.py", line 374, in execute_plan
    install.unlink(prefix, arg)
  File "C:\Anaconda\lib\site-packages\conda\install.py", line 452, in unlink
    os.unlink(meta_path)
WindowsError: [Error 5] : 'C:\Anaconda\conda-meta\conda-3.0.6-py27_0.json'
How can I fix this error?

**Comment by xinyuwei** [comment]
Not sure if this has been resolved, but I ran into this too on Windows and fixed it by right click the Command Prompt and run it as administrator.

**Comment by Franck-Dernoncourt** [comment]
Same here, running anaconda prompt as admin solved the issue.

**Comment by seleregb** [comment]
mine hasn't. i'm still having the same issue
