### ISSUE TITLE
install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

### ISSUE THREAD

**Issue by monajalal** [conda/conda#7080]
So how should I fix this in CentOS?
```

[jalal@goku yolo_tensorflow]$ /scratch/sjn/anaconda/bin/conda install opencv
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /scratch/sjn/anaconda:
#
opencv                    3.3.1            py36h6cbbc71_1  
[jalal@goku yolo_tensorflow]$ /scratch/sjn/anaconda/bin/python test.py 
/scratch/sjn/anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-03-25 04:06:47.937412: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Restoring weights from: data/weights/YOLO_small.ckpt
Average detecting time: 0.352s
OpenCV Error: Unspecified error (The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script) in cvShowImage, file /tmp/build/80754af9/opencv_1512687413662/work/modules/highgui/src/window.cpp, line 611
Traceback (most recent call last):
  File "test.py", line 211, in <module>
    main()
  File "test.py", line 207, in main
    detector.image_detector(imname)
  File "test.py", line 183, in image_detector
    cv2.imshow('Image', image)
cv2.error: /tmp/build/80754af9/opencv_1512687413662/work/modules/highgui/src/window.cpp:611: error: (-2) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Carbon support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function cvShowImage

```

**Comment by shubhvachher** [comment]
`conda uninstall opencv`

For opencv2 : 
`conda install -c menpo opencv`
opencv3:
`conda install -c menpo opencv3`

This issue should still not be closed as my solution is just a workaround. The defaults package opencv has the above issue.

**Comment by kalefranz** [comment]
This is the conda issue tracker, not an issue tracker for issues with packages installed by conda.  Feel free to file your packaging-related issue at https://github.com/ContinuumIO/anaconda-issues.
