### ISSUE TITLE
An unexpected error has occurred.

### ISSUE THREAD

**Issue by foxmold** [conda/conda#7082]
Traceback (most recent call last):
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
ModuleNotFoundError: No module named 'requests'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "e:\ProgramData\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "e:\ProgramData\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
ModuleNotFoundError: No module named 'requests'

**Comment by wasdyouli** [comment]
I also meet this error when I try to use the command ：conda upgrade -n root --all
