### ISSUE TITLE
ImportError: cannot import name EnumMeta

### ISSUE THREAD

**Issue by ChikiChickey** [conda/conda#7088]
Hi
I am a beginner of Python, so please explain easily....
I tried 

> conda info -a

but the error message was given

```
Traceback (most recent call last):
  File "/macqiime/anaconda/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/macqiime/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "/macqiime/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "/macqiime/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "/macqiime/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 571, in print_unexpected_error_message
    from .base.context import context
  File "/macqiime/anaconda/lib/python2.7/site-packages/conda/base/context.py", line 21, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "/macqiime/anaconda/lib/python2.7/site-packages/conda/common/configuration.py", line 28, in <module>
    from enum import Enum, EnumMeta
ImportError: cannot import name EnumMeta
```

How can I solve the problem??

**Comment by Youmna-H** [comment]
I am having the same problem. Were you able to solve it?

**Comment by ChikiChickey** [comment]
I have not solved yet...
I am also still waiting for advice.

**Comment by kalefranz** [comment]
You've apparently somehow removed the enum34 package from your root environment, or otherwise corrupted that package.  Easiest solution is to download Anaconda/Miniconda and start over.

**Comment by gibsondanield** [comment]
Even after a fresh install of Anaconda I had this issue. Downloading the enum34 wheel and extracting it in the anaconda library fixed the issue, though

**Comment by kalefranz** [comment]
Bogus enum package in ~/.local?

**Comment by rush4ratio** [comment]
Removing ~/.local does work!
