### ISSUE TITLE
conda create --dry-run still does work

### ISSUE THREAD

**Issue by andymartin** [conda/conda#7094]
**I'm submitting a...**
  - [x ] bug report
  - [ ] feature request

## Current Behavior

`conda create --dry-run --clone py35 --prefix /home/amartin/.conda/envs/ml35
`
Creates a 7.5GB folder.
```
(py35) amartin@amartin-ai:~/.conda/envs$ ll
total 184
-rw-rw-r--  1 amartin amartin 183438 Mar 27 20:21 conda_clone_ml35.log
drwxrwxr-x 10 amartin amartin   4096 Mar 27 20:20 ml35
(py35) amartin@amartin-ai:~/.conda/envs$ du -sh ml35
7.5G    ml35
```

Also gives an assert error that it apparently doesn't want to be a dry run:
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 812, in __call__
        return func(*args, **kwargs)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 11, in execute
        install(args, parser, 'create')
      File "/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 211, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 72, in clone
        index_args=index_args)
      File "/anaconda/lib/python2.7/site-packages/conda/misc.py", line 271, in clone_env
        force_extract=False, index_args=index_args)
      File "/anaconda/lib/python2.7/site-packages/conda/misc.py", line 69, in explicit
        pfe.execute()
      File "/anaconda/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 578, in execute
        assert not context.dry_run
    AssertionError
```

### Steps to Reproduce

```
conda create --dry-run --clone py35 --prefix /home/amartin/.conda/envs/ml35
```

## Expected Behavior

It should report actions to be taken without performing any actions

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(ml35) amartin@amartin-ai:~/.conda/envs/ml35/lib/python3.5/site-packages$ conda info

     active environment : ml35
    active env location : /home/amartin/.conda/envs/ml35
            shell level : 1
       user config file : /home/amartin/.condarc
 populated config files :
          conda version : 4.5.0
    conda-build version : 3.0.23
         python version : 2.7.11.final.0
       base environment : /anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /anaconda/pkgs
                          /home/amartin/.conda/pkgs
       envs directories : /anaconda/envs
                          /home/amartin/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/2.7.11 Linux/4.13.0-1011-azure ubuntu/16.04 glibc/2.23
                UID:GID : 1003:1003
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>
[conda_clone_ml35.log](https://github.com/conda/conda/files/1853928/conda_clone_ml35.log)

**Comment by andymartin** [comment]
[conda_clone_ml35.log](https://github.com/conda/conda/files/1853929/conda_clone_ml35.log)
