### ISSUE TITLE
anaconda start and crashed

### ISSUE THREAD

**Issue by corgimas** [conda/conda#7105]
**I'm submitting a...**
  - [ x] bug report
  - [ ] feature request

## Current Behavior

I expected the program to open, but it just crashed out on me instead....

### Steps to Reproduce

```
I started anaconda to use rstudio per usual and received the following:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
string indices must be integers, not str
Traceback
Traceback (most recent call last):
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 162, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 1270, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 71, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1663, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 346, in __init__
    self.set_conda_prefix()
  File "C:\Users\corgi\Anaconda2\lib\site-packages\anaconda_navigator\api\conda_api.py", line 495, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: string indices must be integers, not str
```

## Expected Behavior

program should have opened....

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(base) C:\Users\corgi>conda info

     active environment : base
    active env location : C:\Users\corgi\Anaconda2
            shell level : 1
       user config file : C:\Users\corgi\.condarc
 populated config files : C:\Users\corgi\.condarc
          conda version : 4.4.7
    conda-build version : not installed
         python version : 2.7.13.final.0
       base environment : C:\Users\corgi\Anaconda2  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\corgi\Anaconda2\pkgs
                          C:\Users\corgi\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\corgi\Anaconda2\envs
                          C:\Users\corgi\AppData\Local\conda\conda\envs
                          C:\Users\corgi\.conda\envs
               platform : win-64
             user-agent : conda/4.4.7 requests/2.14.2 CPython/2.7.13 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(base) C:\Users\corgi>conda config --show-sources
==> C:\Users\corgi\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(base) C:\Users\corgi>conda list --show-channel-urls
# packages in environment at C:\Users\corgi\Anaconda2:
#
_license                  1.1                      py27_1    defaults
alabaster                 0.7.10                   py27_0    defaults
anaconda                  custom           py27h689e5c3_0    defaults
anaconda-client           1.6.3                    py27_0    defaults
anaconda-navigator        1.6.12           py27h5ea5405_0    defaults
anaconda-project          0.6.0                    py27_0    defaults
asn1crypto                0.22.0                   py27_0    defaults
astroid                   1.4.9                    py27_0    defaults
astropy                   1.3.2               np112py27_0    defaults
babel                     2.4.0                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.5                      py27_0    defaults
beautifulsoup4            4.6.0                    py27_0    defaults
bitarray                  0.8.1                    py27_1    defaults
blaze                     0.10.1                   py27_0    defaults
bleach                    1.5.0                    py27_0    defaults
bokeh                     0.12.5                   py27_1    defaults
boto                      2.46.1                   py27_0    defaults
bottleneck                1.2.1               np112py27_0    defaults
bzip2                     1.0.6                     vc9_3  [vc9]  defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.10.0                   py27_0    defaults
chardet                   3.0.3                    py27_0    defaults
click                     6.7                      py27_0    defaults
cloudpickle               0.2.2                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.9                    py27_0    defaults
comtypes                  1.1.2                    py27_0    defaults
conda                     4.4.7                    py27_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
configparser              3.5.0                    py27_0    defaults
console_shortcut          0.1.1                    py27_1    defaults
contextlib2               0.5.5                    py27_0    defaults
cryptography              1.8.1                    py27_0    defaults
curl                      7.52.1                    vc9_0  [vc9]  defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.25.2                   py27_0    defaults
cytoolz                   0.8.2                    py27_0    defaults
dask                      0.14.3                   py27_1    defaults
datashape                 0.5.4                    py27_0    defaults
decorator                 4.0.11                   py27_0    defaults
distributed               1.16.3                   py27_0    defaults
docutils                  0.13.1                   py27_0    defaults
entrypoints               0.2.2                    py27_1    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
fastcache                 1.0.2                    py27_1    defaults
flask                     0.12.2                   py27_0    defaults
flask-cors                3.0.2                    py27_0    defaults
freetype                  2.5.5                     vc9_2  [vc9]  defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.1.1                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.2.1                    py27_0    defaults
greenlet                  0.4.12                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
h5py                      2.7.0               np112py27_0    defaults
hdf5                      1.8.15.1                  vc9_4  [vc9]  defaults
heapdict                  1.0.0                    py27_1    defaults
html5lib                  0.999                    py27_0    defaults
icu                       57.1                      vc9_0  [vc9]  defaults
idna                      2.5                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
ipaddress                 1.0.18                   py27_0    defaults
ipykernel                 4.6.1                    py27_0    defaults
ipython                   5.3.0                    py27_0    defaults
ipython_genutils          0.2.0                    py27_0    defaults
ipywidgets                6.0.0                    py27_0    defaults
isort                     4.2.5                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jdcal                     1.3                      py27_0    defaults
jedi                      0.10.2                   py27_2    defaults
jinja2                    2.9.6                    py27_0    defaults
jpeg                      9b                        vc9_0  [vc9]  defaults
jsonschema                2.6.0                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter_client            5.0.1                    py27_0    defaults
jupyter_console           5.1.0                    py27_0    defaults
jupyter_core              4.3.0                    py27_0    defaults
lazy-object-proxy         1.2.2                    py27_0    defaults
libpng                    1.6.27                    vc9_0  [vc9]  defaults
libtiff                   4.0.6                     vc9_3  [vc9]  defaults
llvmlite                  0.18.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.7.3                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                2.0.2               np112py27_0    defaults
menuinst                  1.4.7                    py27_0    defaults
mistune                   0.7.4                    py27_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py27_3    defaults
mpmath                    0.19                     py27_1    defaults
msgpack-python            0.4.8                    py27_0    defaults
multipledispatch          0.4.9                    py27_0    defaults
navigator-updater         0.1.0                    py27_0    defaults
nbconvert                 5.1.1                    py27_0    defaults
nbformat                  4.3.0                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.3                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  5.0.0                    py27_0    defaults
numba                     0.33.0              np112py27_0    defaults
numexpr                   2.6.2               np112py27_0    defaults
numpy                     1.12.1                   py27_0    defaults
numpydoc                  0.6.0                    py27_0    defaults
odo                       0.5.0                    py27_1    defaults
olefile                   0.44                     py27_0    defaults
openpyxl                  2.4.7                    py27_0    defaults
openssl                   1.0.2l                    vc9_0  [vc9]  defaults
packaging                 16.8                     py27_0    defaults
pandas                    0.20.1              np112py27_0    defaults
pandas-datareader         0.5.0                    py27_0    defaults
pandas-profiling          1.4.0                    py27_0    defaults
pandasql                  0.7.3                    py27_0    defaults
pandoc                    1.19.2.1                      1    defaults
pandocfilters             1.4.1                    py27_0    defaults
partd                     0.3.8                    py27_0    defaults
path.py                   10.3.1                   py27_0    defaults
pathlib2                  2.2.1                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pep8                      1.7.0                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    4.1.1                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
ply                       3.10                     py27_0    defaults
prompt_toolkit            1.0.14                   py27_0    defaults
psutil                    5.2.2                    py27_0    defaults
py                        1.4.33                   py27_0    defaults
pycosat                   0.6.3            py27hcd410c5_0    defaults
pycparser                 2.17                     py27_0    defaults
pycrypto                  2.6.1                    py27_6    defaults
pycurl                    7.43.0                   py27_2    defaults
pyflakes                  1.5.0                    py27_0    defaults
pygments                  2.2.0                    py27_0    defaults
pylint                    1.6.4                    py27_1    defaults
pyodbc                    4.0.16                   py27_0    defaults
pyopenssl                 17.0.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_2    defaults
pytables                  3.2.2               np112py27_4    defaults
pytest                    3.0.7                    py27_0    defaults
python                    2.7.13                        1    defaults
python-dateutil           2.6.0                    py27_0    defaults
pytz                      2017.2                   py27_0    defaults
pywavelets                0.5.2               np112py27_0    defaults
pywin32                   220                      py27_2    defaults
pyyaml                    3.12                     py27_0    defaults
pyzmq                     16.0.2                   py27_0    defaults
qt                        5.6.2                     vc9_4  [vc9]  defaults
qtawesome                 0.4.4                    py27_0    defaults
qtconsole                 4.3.0                    py27_0    defaults
qtpy                      1.2.1                    py27_0    defaults
requests                  2.14.2                   py27_0    defaults
requests-file             1.4.1                    py27_0    defaults
requests-ftp              0.3.1                    py27_0    defaults
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_1    defaults
scandir                   1.5                      py27_0    defaults
scikit-image              0.13.0              np112py27_0    defaults
scikit-learn              0.18.1              np112py27_1    defaults
scipy                     0.19.0              np112py27_0    defaults
seaborn                   0.7.1                    py27_0    defaults
setuptools                27.2.0                   py27_1    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sortedcollections         0.5.3                    py27_0    defaults
sortedcontainers          1.5.7                    py27_0    defaults
sphinx                    1.5.6                    py27_0    defaults
spyder                    3.1.4                    py27_0    defaults
sqlalchemy                1.1.9                    py27_0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.8.0               np112py27_0    defaults
subprocess32              3.2.7                    py27_0    defaults
sympy                     1.0                      py27_0    defaults
tblib                     1.3.2                    py27_0    defaults
testpath                  0.3                      py27_0    defaults
tk                        8.5.18                    vc9_0  [vc9]  defaults
toolz                     0.8.2                    py27_0    defaults
tornado                   4.5.1                    py27_0    defaults
traitlets                 4.3.2                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
vc                        9                             0    defaults
vs2008_runtime            9.00.30729.5054               0    defaults
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.12.2                   py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        2.0.0                    py27_0    defaults
win_unicode_console       0.5                      py27_0    defaults
wrapt                     1.10.10                  py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.6                    py27_0    defaults
xlwings                   0.10.4                   py27_0    defaults
xlwt                      1.2.0                    py27_0    defaults
zict                      0.1.2                    py27_0    defaults
zlib                      1.2.8                     vc9_3  [vc9]  defaults
```
</p></details>

**Comment by kalefranz** [comment]
Try 

    conda update anaconda-navigator

Does that help?

**Comment by kalefranz** [comment]
CC @goanpeca

**Comment by Owuraku1** [comment]
The aim is to delete .condarc
For windows, locate drive C:
Go to users
open your real user: eg Okronmansa #do not open public
look for .condarc
delete it and refresh the folder
close the folder and restart anaconda
Enjoy!
T for thanks!!

**Comment by anudeepb97** [comment]
Problem Solved! Cheers

**Comment by Owuraku1** [comment]
My money has not been reversed to me. 
The issue still exists
