### ISSUE TITLE
osx install conda fails with `Library not loaded: @rpath/libz.1.dylib` installing as non-root user.

### ISSUE THREAD

**Issue by glycerine** [conda/conda#7113]
osx 10.12.5 amd64

I downloaded Anaconda2-5.1.0-MacOSX-x86_64.sh from https://repo.continuum.io/archive/Anaconda2-5.1.0-MacOSX-x86_64.sh
 and tried to install by running it as my non-root user. I get `Library not loaded: @rpath/libz.1.dylib`, despite libz.1.dylib being present in /usr/lib/.

It installed fine as root, but this is dangerous and should not be required, no?
~~~
jaten@Jasons-MacBook-Pro ~/Downloads $ ./Anaconda2-5.1.0-MacOSX-x86_64.sh 
./Anaconda2-5.1.0-MacOSX-x86_64.sh 

Welcome to Anaconda2 5.1.0

In order to continue the installation process, please review the license
agreement.
Please, press ENTER to continue
>>> 

===================================
Anaconda End User License Agreement
===================================

Copyright 2015, Anaconda, Inc.

All rights reserved under the 3-clause BSD License:

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

  * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
  * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
  * Neither the name of Anaconda, Inc. ("Anaconda, Inc.") nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL ANACONDA, INC. BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, E: 
VEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

Notice of Third Party Software Licenses
=======================================

Anaconda Distribution contains open source software packages from third parties. These are available on an "as is" basis and subject to their individual license agreements. These licenses are available in Anaconda Distribution or at http://docs.anaconda.com/anaconda/pkg-docs. Any binary packages of these third party tools you obtain via Anaconda Distribution are subject to their individual licenses as well as the Anaconda license. Anaconda, Inc. reserves the right to change which third party tools are provided in Anaconda Distribution.

In particular, Anaconda Distribution contains re-distributable, run-time, shared-library files from the Intel(TM) Math Kernel Library ("MKL binaries"). You are specifically authorized to use the MKL binaries with your installation of Anaconda Distribution. You are also authorized to redistribute the MKL binaries with Anaconda Distribution or in the conda package that contains them. Use and redistribution of the MKL binaries are subject to the licensing terms located at https://software.intel.com/en-us/license/intel-simplified-software-license. If needed, instructions for removing the MKL binaries after installation of Anaconda Distribution are available at http://www.anaconda.com.

Anaconda Distribution also contains cuDNN software binaries from NVIDIA Corporation ("cuDNN binaries"). You are specifically authorized to use the cuDNN binaries with your installation of Anaconda Distribution. You are also authorized to redistribute the cuDNN binaries with an Anaconda Distribution package that contains them. If needed, instructions for removing the cuDNN binaries after installation of Anaconda Distribution are available at http://www.anaconda.com.
:
: 

Anaconda Distribution also contains Visual Studio Code software binaries from Microsoft Corporation ("VS Code"). You are specifically authorized to use VS Code with your installation of Anaconda Distribution. Use of VS Code is subject to the licensing terms located at https://code.visualstudio.com/License.

Cryptography Notice
===================

This distribution includes cryptographic software. The country in which you currently reside may have restrictions on the import, possession, use, and/or re-export to another country, of encryption software. BEFORE using any encryption software, please check your country's laws, regulations and policies concerning the import, possession, or use, and re-export of encryption software, to see if this is permitted. See the Wassenaar Arrangement http://www.wassenaar.org/ for more information.

Anaconda, Inc. has self-classified this software as Export Commodity Control Number (ECCN) 5D992b, which includes mass market information security software using or performing cryptographic functions with asymmetric algorithms. No license is required for export of this software to non-embargoed countries. In addition, the Intel(TM) Math Kernel Library contained in Anaconda, Inc.'s software is classified by Intel(TM) as ECCN 5D992b with no license required for export to non-embargoed countries.

The following packages are included in this distribution that relate to cryptography:

openssl
ource toolkit implementing the Transport Layer Security (TLS) and Secure Sockets Layer (SSL) protocols as well as : 
a full-strength general purpose cryptography library.

pycrypto
    A collection of both secure hash functions (such as SHA256 and RIPEMD160), and various encryption algorithms (AES, DES, RSA, ElGamal, etc.).

pyopenssl
    A thin Python wrapper around (a subset of) the OpenSSL library.

kerberos (krb5, non-Windows platforms)
    A network authentication protocol designed to provide strong authentication for client/server applications by using secret-key cryptography.

cryptography
    A Python library which exposes cryptographic recipes and primitives.


Do you accept the license terms? [yes|no]
[no] >>> 
Please answer 'yes' or 'no':'
>>> yes
yes

Anaconda2 will now be installed into this location:
/Users/jaten/anaconda2

  - Press ENTER to confirm the location
  - Press CTRL-C to abort the installation
  - Or specify a different location below

[/Users/jaten/anaconda2] >>> 

PREFIX=/Users/jaten/anaconda2
installing: python-2.7.14-hde5916a_29 ...
Python 2.7.14 :: Anaconda, Inc.
installing: bzip2-1.0.6-hd86a083_4 ...
installing: ca-certificates-2017.08.26-ha1e5d58_0 ...
installing: conda-env-2.6.0-h36134e3_0 ...
installing: intel-openmp-2018.0.0-h8158457_8 ...
installing: jbig-2.1-h4d881f8_0 ...
installing: jpeg-9b-he5867d9_2 ...
installing: libcxxabi-4.0.1-hebd6815_0 ...
installing: libgfortran-3.0.1-h93005f0_2 ...
installing: libiconv-1.15-hdd342a3_7 ...
installing: libsodium-1.0.15-hd9e47c5_0 ...
installing: lzo-2.10-h362108e_2 ...
installing: pandoc-1.19.2.1-ha5e8f32_1 ...
installing: tk-8.6.7-h35a86e2_3 ...
installing: unixodbc-2.3.4-h4cb4dde_1 ...
installing: xz-5.2.3-h0278029_2 ...
installing: yaml-0.1.7-hc338f04_2 ...
installing: zlib-1.2.11-hf3cbc9b_2 ...
installing: libcxx-4.0.1-h579ed51_0 ...
installing: libpng-1.6.34-he12f830_0 ...
installing: mkl-2018.0.1-hfbd8650_4 ...
installing: openssl-1.0.2n-hdbc3d79_0 ...
installing: expat-2.2.5-hb8e80ba_0 ...
installing: freetype-2.8-h12048fb_1 ...
installing: gmp-6.1.2-hb37e062_1 ...
installing: hdf5-1.10.1-ha036c08_1 ...
installing: icu-58.2-h4b95b61_1 ...
installing: libffi-3.2.1-h475c297_4 ...
installing: libssh2-1.8.0-h322a93b_4 ...
installing: libtiff-4.0.9-h0dac147_0 ...
installing: ncurses-6.0-hd04f020_2 ...
installing: pcre-8.41-hfb6ab37_1 ...
installing: zeromq-4.2.2-ha360ad0_2 ...
installing: gettext-0.19.8.1-h15daf44_3 ...
installing: libcurl-7.58.0-hf30b1f0_0 ...
installing: libedit-3.1-hb4e282d_0 ...
installing: libxml2-2.9.7-hab757c2_0 ...
installing: mpfr-3.1.5-h711e7fd_2 ...
installing: readline-7.0-hc1231fa_4 ...
installing: curl-7.58.0-ha441bb4_0 ...
installing: glib-2.53.6-h33f6a65_2 ...
installing: libxslt-1.1.32-hb819dd2_0 ...
installing: mpc-1.0.3-h7a72875_5 ...
installing: sqlite-3.22.0-h3efe00b_0 ...
installing: dbus-1.12.2-h5243cc1_1 ...
installing: qt-5.6.2-h9975529_14 ...
Traceback (most recent call last):
  File "/Users/jaten/anaconda2/pkgs/.install.py", line 618, in <module>
    main2()
  File "/Users/jaten/anaconda2/pkgs/.install.py", line 599, in main2
    link_dist(opts.link_dist)
  File "/Users/jaten/anaconda2/pkgs/.install.py", line 454, in link_dist
    link(prefix, dist, linktype)
  File "/Users/jaten/anaconda2/pkgs/.install.py", line 360, in link
    if not run_script(prefix, dist, 'post-link'):
  File "/Users/jaten/anaconda2/pkgs/.install.py", line 264, in run_script
    import subprocess
  File "/Users/jaten/anaconda2/pkgs/python-2.7.14-hde5916a_29/lib/python2.7/subprocess.py", line 75, in <module>
    import pickle
  File "/Users/jaten/anaconda2/pkgs/python-2.7.14-hde5916a_29/lib/python2.7/pickle.py", line 1272, in <module>
    import binascii as _binascii
ImportError: dlopen(/Users/jaten/anaconda2/pkgs/python-2.7.14-hde5916a_29/lib/python2.7/lib-dynload/binascii.so, 2): Library not loaded: @rpath/libz.1.dylib
  Referenced from: /Users/jaten/anaconda2/pkgs/python-2.7.14-hde5916a_29/lib/python2.7/lib-dynload/binascii.so
  Reason: image not found
jaten@Jasons-MacBook-Pro ~/Downloads $ 

jaten@Jasons-MacBook-Pro / $ find . -name libz.1.dylib
./Applications/Xcode-8.3.2.app/Contents/Developer/Platforms/AppleTVSimulator.platform/Developer/SDKs/AppleTVSimulator.sdk/usr/lib/libz.1.dylib
./Applications/Xcode-8.3.2.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/lib/libz.1.dylib
./Applications/Xcode-8.3.2.app/Contents/Developer/Platforms/WatchSimulator.platform/Developer/SDKs/WatchSimulator.sdk/usr/lib/libz.1.dylib
./opt/vagrant/embedded/lib/libz.1.dylib
./Users/jaten/.julia/v0.5/Conda/deps/usr/lib/libz.1.dylib
./Users/jaten/.julia/v0.5/Conda/deps/usr/pkgs/python-2.7.14-hde5916a_29/lib/libz.1.dylib
./Users/jaten/.julia/v0.5/Conda/deps/usr/pkgs/python-2.7.14-hde5916a_29/lib/python2.7/lib-dynload/libz.1.dylib
./Users/jaten/.julia/v0.5/Conda/deps/usr/pkgs/python-2.7.14-hde5916a_29/lib/python2.7/libz.1.dylib
./Users/jaten/.julia/v0.5/Conda/deps/usr/pkgs/python-2.7.14-hde5916a_29/libz.1.dylib
./Users/jaten/.julia/v0.5/Conda/deps/usr/pkgs/zlib-1.2.11-hf3cbc9b_2/lib/libz.1.dylib
./Users/jaten/anaconda2/lib/libz.1.dylib
./Users/jaten/anaconda2/pkgs/zlib-1.2.11-hf3cbc9b_2/lib/libz.1.dylib
./Users/jaten/dev/cnet/go/src/github.com/cisco/ChezScheme/a6osx/zlib/libz.1.dylib
./Users/jaten/dev/cnet/go/src/github.com/cisco/ChezScheme/chezgo/zlib/libz.1.dylib
./Users/jaten/dev/cnet/go/src/github.com/glycerine/chezgo/chez_scheme_9.5.1/zlib/libz.1.dylib
./Users/jaten/Downloads/zlib-1.2.11/libz.1.dylib
./Users/jaten/uns/zlib-1.2.11/libz.1.dylib
./usr/lib/libz.1.dylib
./usr/local/anaconda2/lib/libz.1.dylib
./usr/local/anaconda2/pkgs/zlib-1.2.11-hf3cbc9b_2/lib/libz.1.dylib
./usr/local/Cellar/zlib/1.2.11/lib/libz.1.dylib
./usr/local/lib/libz.1.dylib
jaten@Jasons-MacBook-Pro / $ file /usr/lib/libz.1.dylib
/usr/lib/libz.1.dylib: Mach-O universal binary with 2 architectures: [i386: Mach-O dynamically linked shared library i386] [x86_64: Mach-O 64-bit dynamically linked shared library x86_64]
/usr/lib/libz.1.dylib (for architecture i386):	Mach-O dynamically linked shared library i386
/usr/lib/libz.1.dylib (for architecture x86_64):	Mach-O 64-bit dynamically linked shared library x86_64
jaten@Jasons-MacBook-Pro / $ 
~~~

**Comment by kalefranz** [comment]
@nehaljwani Do you know what's going on here?

**Comment by ppxdm4** [comment]
Was this issue resolved? I have this error when trying to install Mininconda on mac os 10.11.6. Using: Miniconda3-4.7.12.1-MacOSX-x86_64.sh

**Comment by gplanansky** [comment]
on mac os 10.10.5 with miniforge3:

unset PYTHONPATH PYTHON_PATH DYLD_FALLBACK_LIBRARY_PATH
Miniforge3-4.8.3-2-MacOSX-x86_64.sh

worked.   fwiw I have other pythons installed, than just the mac os x system python

**Comment by digitizdat** [comment]
Unsetting DYLD_FALLBACK_LIBRARY_PATH worked for me as well.

I was running into this issue on MacOS 10.15.7 with Anaconda3-2020.11-MacOSX-x86_64.sh. The error I was getting was:
```

dyld: Library not loaded: @rpath/libz.1.dylib
  Referenced from: /Users/martin/anaconda3/conda.exe
  Reason: image not found
Anaconda3-2020.11-MacOSX-x86_64.sh: line 411: 49166 Exit 141                { dd if="$THIS_PATH" bs=1 skip=14834925 count=8979 2> /dev/null; dd if="$THIS_PATH" bs=16384 skip=906 count=26470 2> /dev/null; dd if="$THIS_PATH" bs=1 skip=448528384 count=4122 2> /dev/null; }
     49167 Abort trap: 6           | "$CONDA_EXEC" constructor --extract-tar --prefix "$PREFIX"
dyld: Library not loaded: @rpath/libz.1.dylib
  Referenced from: /Users/martin/anaconda3/conda.exe
  Reason: image not found
Anaconda3-2020.11-MacOSX-x86_64.sh: line 413: 49171 Abort trap: 6           "$CONDA_EXEC" constructor --prefix "$PREFIX" --extract-conda-pkgs
```
