### ISSUE TITLE
Error on conda install mkl-2017.0.3-0

### ISSUE THREAD

**Issue by harlecin** [conda/conda#7116]
Hey there,

I got the following error when trying to install mkl-2017.0.3-0 on my W10 computer as part of Azure Machine Learning Workbench (installation fails with same error if I try to install only mkl-2017)

Any help to resolve this more than welcome:) 

### start error log ####

Running the installation with administrator privileges works for some reason.

[20:22:33] StandardError: Please consider posting the following information to the
[20:22:33] StandardError: conda GitHub issue tracker at:
[20:22:33] StandardError: 
[20:22:33] StandardError:     https://github.com/conda/conda/issues
[20:22:33] StandardError: 
[20:22:33] StandardError: 
[20:22:33] StandardError: 
[20:22:33] StandardError: Current conda install:
[20:22:33] StandardError: 
[20:22:33] StandardError:                platform : win-64
[20:22:33] StandardError:           conda version : 4.3.27
[20:22:33] StandardError:        conda is private : False
[20:22:33] StandardError:       conda-env version : 4.3.27
[20:22:33] StandardError:     conda-build version : not installed
[20:22:33] StandardError:          python version : 3.5.2.final.0
[20:22:33] StandardError:        requests version : 2.11.1
[20:22:33] StandardError:        root environment : C:\Users\username\AppData\Local\amlworkbench\Python  (writable)
[20:22:33] StandardError:     default environment : C:\Users\username\AppData\Local\amlworkbench\Python
[20:22:33] StandardError:        envs directories : C:\Users\username\AppData\Local\amlworkbench\Python\envs
[20:22:33] StandardError:                           C:\Users\username\AppData\Local\conda\conda\envs
[20:22:33] StandardError:                           C:\Users\username\.conda\envs
[20:22:33] StandardError:           package cache : C:\Users\username\AppData\Local\amlworkbench\Python\pkgs
[20:22:33] StandardError:                           C:\Users\username\AppData\Local\conda\conda\pkgs
[20:22:33] StandardError:            channel URLs : https://repo.continuum.io/pkgs/main/win-64  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/main/noarch  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/free/win-64  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/free/noarch  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/r/win-64  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/r/noarch  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/pro/win-64  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/pro/noarch  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/msys2/win-64  (offline)
[20:22:33] StandardError:                           https://repo.continuum.io/pkgs/msys2/noarch  (offline)
[20:22:33] StandardError:             config file : C:\Users\username\.condarc
[20:22:33] StandardError:              netrc file : None
[20:22:33] StandardError:            offline mode : True
[20:22:33] StandardError:              user-agent : conda/4.3.27 requests/2.11.1 CPython/3.5.2 Windows/10 Windows/10.0.15063    
[20:22:33] StandardError:           administrator : False
[20:22:33] StandardError: 
[20:22:33] StandardError: `$ C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\__main__.py install --no-deps --yes --force --offline C:\Users\username\AppData\Local\Temp\AmlInstaller\mkl.windows-2017.0.3\mkl-2017.0.3-0.tar.bz2`
[20:22:33] StandardError: 
[20:22:33] StandardError: 
[20:22:33] StandardError: 
[20:22:33] StandardError: 
[20:22:33] StandardError:     Traceback (most recent call last):
[20:22:33] StandardError:       File "C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
[20:22:33] StandardError:         return_value = func(*args, **kwargs)
[20:22:33] StandardError:       File "C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\cli\main.py", line 140, in _main
[20:22:33] StandardError:         exit_code = args.func(args, p)
[20:22:33] StandardError:       File "C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\cli\main_install.py", line 80, in execute
[20:22:33] StandardError:         install(args, parser, 'install')
[20:22:33] StandardError:       File "C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\cli\install.py", line 210, in install
[20:22:33] StandardError:         explicit(args_packages, prefix, verbose=not context.quiet)
[20:22:33] StandardError:       File "C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\misc.py", line 100, in explicit
[20:22:33] StandardError:         link_names = {index[d]['name'] for d in link_dists}
[20:22:33] StandardError:       File "C:\Users\username\AppData\Local\amlworkbench\Python\lib\site-packages\conda\misc.py", line 100, in <setcomp>
[20:22:33] StandardError:         link_names = {index[d]['name'] for d in link_dists}
[20:22:33] StandardError:     KeyError: Dist(_Dist__initd=True, channel='<unknown>', dist_name='mkl-2017.0.3-0', name='mkl', version='2017.0.3', build_string='0', build_number=0, with_features_depends=None, base_url='file:///C:/Users/username/AppData/Local/Temp/AmlInstaller/mkl.windows-2017.0.3', platform=None)
[20:22:33] StandardError: 
31.03.2018 20:22:33 20: Installer [Information] - 0: Executing command: C:\Users\username\AppData\Local\amlworkbench\Python\python.exe -s -m conda install --no-deps --yes --force --offline "C:\Users\username\AppData\Local\Temp\AmlInstaller\mkl.windows-2017.0.3\mkl-2017.0.3-0.tar.bz2"
31.03.2018 20:22:58 22: Installer [Information] - 0: Returned exit code 1
31.03.2018 20:22:58 22: Installer [Information] - 0: Output: [20:22:58] StandardError: An unexpected error has occurred.

**Comment by archevel** [comment]
I got the same error in the log files when failing to install. When rerunning the installer the installer finishes successfully. However, looking through those log files I noticed that the following packages had failed to install:

- six-1.11.0-py35_1
- asn1crypto-0.24.0-py35_0
- cffi-1.11.5-py35_0
- pycparser-2.18-py35_0.
- ca-certificates-2018.1.18-0
- mkl-2017.0.3-0

Launching the Workbench worked and logging in and creating the first Iris sample project also worked. However, trying to view the metrics or running any of the python scripts failed.

In the `AppData\Local\amlworkbench\Python\Scripts` there is an `activate.bat` that activates the root conda environment. Activating that environment and then **uninstalling the above packages** (using e.g. `conda uninstall six`) I was then able to use the conda to install the packages with:

    conda install --verbose --no-deps --force six=1.11.0

To install the ca-certificate package I needed to use conda-forge:

    conda install -c conda-forge --verbose --no-deps --force ca-certificates=2018.1.18

Hope that helps! @harlecin
