### ISSUE TITLE
Unable to run Conda on Windows with ruamel_yaml.reader.ReaderError:

### ISSUE THREAD

**Issue by sweemeng** [conda/conda#7118]
**I'm submitting a...**
  - [ X] bug report
  - [ ] feature request

## Current Behavior

Cannot run conda command on Anaconda Prompt

### Steps to Reproduce

Run conda with any arguments on Windows 10
```
conda 
```

## Expected Behavior

conda command should run and not raise an exception

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\cli\main.py", line 103, in _main
    from ..base.context import context
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\sweem\.condarc", position 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\exceptions.py", line 579, in print_unexpected_error_message
    from .base.context import context
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\base\context.py", line 771, in <module>
    context = Context(SEARCH_PATH, APP_NAME, None)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 727, in __init__
    self._set_search_path(search_path)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 745, in _set_search_path
    self._set_raw_data(load_file_configs(search_path))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
    raw_data = odict(kv for kv in chain.from_iterable(load_paths))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
    yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
    ruamel_yaml = yaml_load(fh)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\conda\common\yaml.py", line 26, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\main.py", line 73, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
    Reader.__init__(self, stream)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
    self.determine_encoding()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
    self.update(1)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
    self.check_printable(data)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
    'unicode', "special characters are not allowed")
ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
  in "C:\Users\sweem\.condarc", position 0
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by sweemeng** [comment]
Sorry my fault. Solved by removing .condarc and let conda regenerate the file
