### ISSUE TITLE
File "/scratch/sjn/anaconda/lib/python3.6/ssl.py", line 327, in match_hostname     % (hostname, ', '.join(map(repr, dnsnames)))) ssl.CertificateError: hostname doesn't match either of

### ISSUE THREAD

**Issue by monajalal** [conda/conda#7119]
For this code:

```
import pickle
import urllib.request
import re
import requests
from urllib.parse import quote
# img = urllib.request.urlopen(quote(value))
# img = urllib.urlopen(quote(value))
import time
count = 0

def urlEncodeNonAscii(b):
    return re.sub('[\x80-\xFF]', lambda c: '%%%02x' % ord(c.group(0)), b)

def iriToUri(iri):
    parts= urllib.parse.urlparse(iri)
    return urllib.unparse(
        part.encode('idna') if parti==1 else urlEncodeNonAscii(part.encode('utf-8'))
        for parti, part in enumerate(parts)
    )

a = {'hello': 'world'}

#with open('filename.pickle', 'wb') as handle:
#    pickle.dump(a, handle, protocol=pickle.HIGHEST_PROTOCOL)

with open('images.pickle', 'rb') as handle:
    b = pickle.load(handle)

print(len(b))
value = "https://static.straitstimes.com.sg/sites/default/files/styles/x_large/public/articles/2017/09/23/ST_20170923_WONZ_3440048.jpg?itok=-iG-zSvr"
key = 503
try:
    img = urllib.request.urlopen(quote(value,  "\./_-:"))
    #img = requests.get(value)
    split = urllib.parse.urlsplit(value)
    extension =  split.path.split(".")[-1]
    print(extension)
    if extension.lower() == 'jpg':
        filename = "immigration_images/" + str(key) + ".jpg"
    elif extension.lower() == 'jpeg':
        filename = "immigration_images/" + str(key) + ".jpeg"
    elif extension.lower() == 'ico':
        filename = "immigration_images/" + str(key) + ".ico"
    else:
        filename = "immigration_images/" + str(key) + ".png"

    img_extension = img.info()['Content-Type']
    #print(img_extension)
    if img_extension:
        if 'jpeg' in img_extension:
            filename = "immigration_images/" + str(key) + ".jpeg"
        elif 'jpg' in img_extension:
            filename = "immigration_images/" + str(key) + '.jpg'
        elif 'png' in img_extension:
            filename = "immigration_images/" + str(key) + '.png'
        #urllib.request.urlretrieve(value, filename)

    urllib.request.urlretrieve(value, filename)
except (urllib.error.ContentTooShortError, urllib.error.URLError, urllib.error.HTTPError, UnicodeEncodeError) as e:
    print(e)
```
I get the following error:
```
/scratch/sjn/anaconda/bin/python /scratch2/news_bias/bug_removal.py
10000
Traceback (most recent call last):
  File "/scratch2/news_bias/bug_removal.py", line 33, in <module>
    img = urllib.request.urlopen(quote(value,  "\./_-:"))
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 1361, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/scratch/sjn/anaconda/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/scratch/sjn/anaconda/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/scratch/sjn/anaconda/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/scratch/sjn/anaconda/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/scratch/sjn/anaconda/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/scratch/sjn/anaconda/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/scratch/sjn/anaconda/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/scratch/sjn/anaconda/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/scratch/sjn/anaconda/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/scratch/sjn/anaconda/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/scratch/sjn/anaconda/lib/python3.6/ssl.py", line 694, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/scratch/sjn/anaconda/lib/python3.6/ssl.py", line 327, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
ssl.CertificateError: hostname 'www.straitstimes.com.sg' doesn't match either of 'gp1.adn.edgecastcdn.net', 'gs1.adn.edgecastcdn.net', 'ne1.adn.edgecastcdn.net', 'www.uship.com', 'www.bluefly.com', 'www.belleandclive.com', 'is.belleandclive.com', 'connections.cochlear.com', 'assets.pokemon.com', 'www.shopperschoice.com', 'www.biznessapps.com', 'cdn.shocho.co', 'secure.hibustudio.com', 'www.stardoll.com', 'adn.wiredrive.com', 'www.speedtest.net', 'www.cduniverse.com', 'ak-site-origin-cover.cduniverse.com', 'cover.cduniverse.com', 'g.cduniverse.com', 'www.renttherunway.com', 'cdn2.navexglobal.com', 'www.chdist.com', 'www.thefanorama.com', 'cdn2.mediasilo.com', 'cdn.citadoncw.com', 'www.woodcraft.com', 'marketing-admin.upsight-api.com', 'www.edgecast.com'

Process finished with exit code 1

```

How should this be fixed?

**Comment by kalefranz** [comment]
This is the conda issue tracker. I'm sorry, but we cannot help with general python user questions here.
