### ISSUE TITLE
Anaconda installation on Mac OSX 10.9.2 fails

### ISSUE THREAD

**Issue by nikta** [conda/conda#714]
I am tying to update anacpnda python installation on my mac using the command "conda create -n py3k python=3 anaconda" and I face this error. Is there anyway to solve this?

```pytb
Traceback (most recent call last):
  File "/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 121, in main
    args.func(args, p)
  File "/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 36, in execute
    conda = Anaconda()
  File "/anaconda/lib/python2.7/site-packages/conda/anaconda.py", line 43, in __init__
    self._index = PackageIndex(fetch_index(self.channel_urls))
  File "/anaconda/lib/python2.7/site-packages/conda/package_index.py", line 42, in __init__
    pkg = Package(pkg_info)
  File "/anaconda/lib/python2.7/site-packages/conda/package.py", line 58, in __init__
    for spec_string in self._info['requires'])
KeyError: 'requires'
```

**Comment by csoja** [comment]
Not reproducible with the latest version of conda and anaconda.
