### ISSUE TITLE
starting today, dails to mount environment in CircleCI

### ISSUE THREAD

**Issue by Casyfill** [conda/conda#7147]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

Getting failure on Cricle CI environment deploy (see console output below)

### Steps to Reproduce
circle ci (Ubuntu) runs the commandas below:
```
- wget https://repo.continuum.io/miniconda/Miniconda3-4.3.31-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $MINICONDA_ROOT
- hash -r

# Apply some conda settings, update conda and print info about the installation (for debugging)
    - conda config --set always_yes yes
# - conda update -q conda  ## issues with 4.4
    - conda info -a

# Install dependencies into the conda root environment.
    - conda env update --name root -f environment.yml
```

here is my `environment.yml`
``` 
name: root
channels:
  - conda-forge
dependencies:
  - python=3.6
  - nose==1.3.7
  - pep8==1.7.0
  - ipython==6.0.0
  - pymysql==0.7.11
  - pandas==0.20.2
  - geopandas==0.3.0
  - requests==2.18.4
  - scipy==0.19.0
  - scikit-learn==0.19.0
  - xlsxwriter==0.9.8
  - pillow==4.2.1
  - matplotlib==2.1.1
  - jsonschema==2.6.0
  - tqdm== 4.19.2
  - aiohttp==2.0.7
  - coverage==4.5.1
  - pytest=3.5.0
  - pytest-cov=2.5.1
  - pip
  - pip:
    - boto3==1.5.22
    - sendgrid==5.2.0
    - snowflake-sqlalchemy==1.0.9
```

Console output:
```
dbus post-link :: /etc/machine-id not found ..
dbus post-link :: .. using /proc/sys/kernel/random/boot_id

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
    class CondaVerificationError(CondaError):
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda_env/cli/main_update.py", line 106, in execute
    # e.g. due to conda_env being upgraded or Python version switched.
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
    args, pip_version = pip_args(prefix)
ValueError: too many values to unpack (expected 2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/miniconda/bin/conda-env", line 11, in <module>
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda_env/cli/main.py", line 76, in main
    
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 644, in conda_exception_handler
    
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
    package_location=package_location,
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 595, in print_unexpected_error_message
    
  File "/home/ubuntu/miniconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
    from .common import print_envs_list, stdout_json
ImportError: cannot import name 'print_envs_list'

conda env update --name root -f environment.yml returned exit code 1

Action failed: conda env update --name root -f environment.yml
```

## Expected Behavior

I didn't change anything in the environment and fails start to occur on two parallel branches today,
which makes me think this is something independent of my code. Before CircleCi was able to successfully mount environment and run all tests.

## Environment Information
- Default Circle Ci ubuntu-14.04 machine

<details open><summary><code>`conda info`</code></summary><p>

```
  active environment : None
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.5.0
    conda-build version : not installed
         python version : 3.6.3.final.0
       base environment : /home/ubuntu/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ubuntu/miniconda/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/miniconda/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.3 Linux/3.13.0-143-generic ubuntu/14.04 glibc/2.19
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/ubuntu/.condarc <==
always_yes: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
 packages in environment at /home/ubuntu/miniconda:
#
# Name                    Version                   Build  Channel
aiohttp                   2.0.7                    py36_0    conda-forge
asn1crypto                0.23.0           py36h4639342_0    defaults
async-timeout             2.0.1                    py36_0    conda-forge
attrs                     17.4.0                     py_0    conda-forge
backports                 1.0                      py36_1    conda-forge
backports.functools_lru_cache 1.5                      py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.11.5        py36hf29ccca_0    defaults
cffi                      1.11.2           py36h2825082_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
conda                     4.5.0                    py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
coverage                  4.5.1                    py36_0    conda-forge
cryptography              2.1.4            py36hd09be54_0    defaults
curl                      7.59.0                        1    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
dbus                      1.10.22                       0    conda-forge
decorator                 4.2.1                    py36_0    conda-forge
descartes                 1.1.0                      py_1    conda-forge
expat                     2.1.0                         3    conda-forge
fiona                     1.7.11                   py36_1    conda-forge
fontconfig                2.12.1                        6    conda-forge
freetype                  2.7                           2    conda-forge
freexl                    1.0.5                         0    conda-forge
gdal                      2.1.3                    py36_7    conda-forge
geopandas                 0.3.0                    py36_0    conda-forge
geos                      3.6.2                         1    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.55.0                        0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6              py36h82fb2a8_1    defaults
ipython                   6.0.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.11.1                   py36_0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
kealib                    1.4.7                         4    conda-forge
krb5                      1.14.6                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 7.2.0                h7cc24e2_2    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.15                          0    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.28                        2    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                       18    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libtiff                   4.0.9                         0    conda-forge
libxcb                    1.13                          0    conda-forge
libxml2                   2.9.8                         0    conda-forge
matplotlib                2.1.1                    py36_0    conda-forge
more-itertools            4.1.0                      py_0    conda-forge
multidict                 4.1.0                    py36_0    conda-forge
munch                     2.3.0                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
nose                      1.3.7                    py36_2    conda-forge
numpy                     1.13.3          py36_blas_openblas_200  [blas_openblas]  conda-forge
olefile                   0.45.1                   py36_0    conda-forge
openblas                  0.2.19                        2    conda-forge
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2n               hb7f436b_0    defaults
pandas                    0.20.2              np113py36_1    conda-forge
parso                     0.1.1                      py_0    conda-forge
pcre                      8.41                          1    conda-forge
pep8                      1.7.0                    py36_0    conda-forge
pexpect                   4.4.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psycopg2                  2.7.4                    py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
py                        1.5.3                      py_0    conda-forge
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pygments                  2.2.0                    py36_0    conda-forge
pymysql                   0.7.11                     py_0    conda-forge
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      5.6.0                    py36_4    conda-forge
pysal                     1.14.3                   py36_0    conda-forge
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pytest                    3.5.0                    py36_0    conda-forge
pytest-cov                2.5.1                    py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.7.2                      py_0    conda-forge
pytz                      2018.3                     py_0    conda-forge
qt                        5.6.2                         6    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
scikit-learn              0.19.0          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     0.19.0          np113py36_blas_openblas_202  [blas_openblas]  conda-forge
setuptools                36.5.0           py36he42e2e1_0    defaults
shapely                   1.6.4                    py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0           py36h372c433_1    defaults
sqlalchemy                1.2.6                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
tqdm                      4.19.2                     py_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22             py36hbe7ace6_0    defaults
util-linux                2.21                          0    defaults
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.30.0           py36hfd4bba0_1    defaults
xerces-c                  3.2.0                         0    conda-forge
xlsxwriter                0.9.8                    py36_0    conda-forge
xorg-libxau               1.0.8                         3    conda-forge
xorg-libxdmcp             1.1.2                         3    conda-forge
xz                        5.2.3                h55aa19d_2    defaults
yaml                      0.1.7                had09818_2    defaults
yarl                      0.10.0                   py36_0    conda-forge
zlib                      1.2.11               ha838bed_2    defaults
```
</p></details>

**Comment by Casyfill** [comment]
resolved by bumping to `Miniconda3-4.4.10-Linux-x86_64.sh`
