### ISSUE TITLE
Anaconda won't open

### ISSUE THREAD

**Issue by bp139** [conda/conda#7169]
I'm submitting a bug report

When I try to open the anaconda navigator, it fails and gives me the following error message:

Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
byte indices must be integers or slices, not str
Traceback
Traceback (most recent call last):
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\Leslie\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

And when I try to open the anaconda prompt, it immediately fails and gives me the following error message:

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\cli\main.py", line 110, in main
        from ..activate import main as activator_main
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\base\context.py", line 234, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\configuration.py", line 723, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\configuration.py", line 729, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\configuration.py", line 371, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\configuration.py", line 346, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\configuration.py", line 334, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\Leslie\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Leslie\.condarc", position 0

`$ C:\Users\Leslie\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\Leslie\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Leslie\Anaconda3
                 HOMEPATH=\Users\Leslie
                     PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS
                          Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WIN
                          DOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1
                          .0\;C:\Program Files\Intel\Intel(R) Management Engine
                          Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine
                          Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine
                          Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine
                          Components\IPT;C:\Program Files (x86)\Intel\OpenCL
                          SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL
                          SDK\2.0\bin\x64;C:\Program Files (x86)\Windows Live\Shared;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessComm
                          on\;C:\Users\Leslie\Documents\Python;C:\Program
                          Files\PuTTY\;C:\Program Files\Git\cmd;C:\Program
                          Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\do
                          tnet\;C:\Users\Leslie\Anaconda3;C:\Users\Leslie\Anaconda3\Library\ming
                          w-w64\bin;C:\Users\Leslie\Anaconda3\Library\usr\bin;C:\Users\Leslie\An
                          aconda3\Library\bin;C:\Users\Leslie\Anaconda3\Scripts;C:\Users\Leslie\
                          AppData\Local\GitHubDesktop\bin;C:\Program Files\Microsoft VS
                          Code\bin;
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Leslie\.condarc
 populated config files :
          conda version : 4.4.10
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : C:\Users\Leslie\Anaconda3  (writable)
           channel URLs : https://repo.continuum.io/pkgs/main/win-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
          package cache : C:\Users\Leslie\Anaconda3\pkgs
                          C:\Users\Leslie\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Leslie\Anaconda3\envs
                          C:\Users\Leslie\AppData\Local\conda\conda\envs
                          C:\Users\Leslie\.conda\envs
               platform : win-64
             user-agent : conda/4.4.10 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

I've tried uninstalling and reinstalling anaconda, and that did not fix the problem.

**Comment by goanpeca** [comment]
The conda configurtion file located at `C:\Users\Leslie\.condarc` seems to have an invalid character, you can open it and see if you find anything that looks out of place, otherwise you will need to remove it.
