### ISSUE TITLE
HTTP 000 error when updating conda in Docker container

### ISSUE THREAD

**Issue by jakirkham** [conda/conda#7193]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

```
$ conda update --all
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

`$ /opt/conda3/bin/conda update --all`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/conda3/bin/conda
             CONDA_PREFIX=/opt/conda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/conda3/bin/python
               CONDA_ROOT=/opt/conda3
              CONDA_SHLVL=1
       DRMAA_LIBRARY_PATH=/usr/lib64/libdrmaa.so.1.0
                     PATH=/opt/conda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbi
                          n:/bin:/root/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda3/.condarc
          conda version : 4.5.1
    conda-build version : 3.8.1
         python version : 3.6.5.final.0
       base environment : /opt/conda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/3.6.5 Linux/4.9.87-linuxkit-aufs centos/6.9 glibc/2.12
                UID:GID : 0:0
             netrc file : None
           offline mode : False


V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V V

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/pro/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

ConnectionError(MaxRetryError("HTTPSConnectionPool(host='repo.anaconda.com', port=443): Max retries exceeded with url: /pkgs/pro/noarch/repodata.json.bz2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f169e6ee748>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',))",),)

A reportable application error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 
```

### Steps to Reproduce

```
docker run --rm -it jakirkham/centos_drmaa_conda
conda activate
conda update --all
```

## Expected Behavior

Update proceeds without a networking error.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /opt/conda3
            shell level : 1
       user config file : /root/.condarc
 populated config files : /opt/conda3/.condarc
          conda version : 4.5.1
    conda-build version : 3.8.1
         python version : 3.6.5.final.0
       base environment : /opt/conda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda3/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.18.4 CPython/3.6.5 Linux/4.9.87-linuxkit-aufs centos/6.9 glibc/2.12
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /opt/conda3/.condarc <==
channels:
  - conda-forge
  - defaults
show_channel_urls: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda3:
#
# Name                    Version                   Build  Channel
anaconda-client           1.6.14                     py_0    conda-forge
apr                       1.6.3                he40df45_0    defaults
asn1crypto                0.24.0                   py36_0    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
conda                     4.5.1                    py36_0    conda-forge
conda-build               3.8.1                    py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
curl                      7.59.0                        1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
drmaa                     0.7.8                      py_0    conda-forge
expat                     2.2.5                         0    conda-forge
filelock                  3.0.4                    py36_0    conda-forge
git                       2.14.2                        3    conda-forge
glob2                     0.5                      py36_0    conda-forge
idna                      2.6                      py36_1    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
krb5                      1.14.6                        0    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libiconv                  1.15                          0    conda-forge
libssh2                   1.8.0                         2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
markupsafe                1.0                      py36_0    conda-forge
nbformat                  4.4.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
openssl                   1.0.2o                        0    conda-forge
patchelf                  0.9                           2    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pkginfo                   1.4.2                    py36_0    conda-forge
psutil                    5.4.5                    py36_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pyopenssl                 17.5.0                   py36_1    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.2                      py_0    conda-forge
pytz                      2018.4                     py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.18.4                   py36_1    conda-forge
ruamel_yaml               0.15.35                  py36_0    conda-forge
serf                      1.3.9                hb3b5fc1_0    defaults
setuptools                39.0.1                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.20.1                        2    conda-forge
svn                       1.9.7                h30a3245_0    defaults
tini                      0.17.0                        0    conda-forge
tk                        8.6.7                         0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.22                     py36_0    conda-forge
wheel                     0.31.0                   py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```
</p></details>

**Comment by jakirkham** [comment]
Should add this doesn't seem to be unique to any of the channels. This just happens any time a channel beginning with `https://repo.anaconda.com/pkgs` is used. Have tested the `defaults` channel URLs and `conda-forge` independently. All of them have this issue.

**Comment by kalefranz** [comment]
> Temporary failure in name resolution

means a DNS issue somewhere I think.  Unfortunately, these network issues are almost impossible to debug without being on the actual network that's having a problem.

All I can basically do is look for something anomalous going on from our end, which I have, and I don't see anything.

**Comment by jakirkham** [comment]
So this is kind of interesting. If I run, the following I don't experience the issue.

```bash
docker run --rm -it --init --entrypoint=/bin/bash jakirkham/centos_drmaa_conda
conda activate
conda update --all
```

Meaning that something about what we do in the entry point script disagrees with `conda`. Not sure exactly what it doesn't like though. 😕

**Comment by jakirkham** [comment]
Ran into this issue using `condaforge/linux-anvil` locally. Just ran `CONFIG="linux_" ./.circleci/run_docker_build.sh` on https://github.com/conda-forge/holoviews-feedstock/commit/f302fe5051fc0ed07142f01b5f93d4fce6191346 and got the following traceback.

```
$ conda build /home/conda/recipe_root -m /home/conda/feedstock_root/.ci_support/linux_.yaml --quiet
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 6, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 199, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 2105, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1167, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 586, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 1872, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/metadata.py", line 682, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 284, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/render.py", line 264, in get_upstream_pins
    pfe.execute()
  File "/opt/conda/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 604, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/linux-64/python-2.7.14-5.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

**Comment by jakirkham** [comment]
Have also seen this without VPN in Docker images build as recently as yesterday.

**Comment by jakirkham** [comment]
Also we saw a similar issue in `yt`'s [CI build]( https://travis-ci.org/conda-forge/yt-feedstock/jobs/371652159 ) of PR ( https://github.com/conda-forge/yt-feedstock/pull/26 ) recently. Log attached as a [text file](https://github.com/conda/conda/files/1952228/log.txt) just in case. :)

cc @ngoldbaum

**Comment by jakirkham** [comment]
Here's one that I saw in a Docker container build as part of our CI.

ref: https://circleci.com/gh/nanshe-org/docker_nanshe_notebook/79

**Comment by kalefranz** [comment]
The first error in this issue was

    Temporary failure in name resolution

I don't know how to track down the details of the error for commit https://github.com/conda-forge/holoviews-feedstock/commit/f302fe5051fc0ed07142f01b5f93d4fce6191346.

The third from yt is

    [Errno 8] nodename nor servname provided, or not known

The fourth for docker_nanshe_notebook is

    Read timed out.

These are all different errors.

**Comment by jakirkham** [comment]
Recent HTTP 000 Error from `llvmlite`.

ref: https://circleci.com/gh/conda-forge/llvmlite-feedstock/34

**Comment by jxshi** [comment]
Hi,

I recently encountered ```HTTP 000``` error.

Here is the error message:
```Collecting package metadata: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/r/linux-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

ConnectionError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/r/linux-64/repodata.json.bz2 (Caused by ReadTimeoutError("HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Read timed out. (read timeout=9.15)",))',),)
```

Do you guys have any idea to solve this problem? TIA!

Best,
Jianxiang
