### ISSUE TITLE
Conda Not Running

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7242]
_From @sanghaisubham on May 2, 2018 8:24_

### Actual Behavior
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\Subham\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 73, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 56, in __init__
        Reader.__init__(self, stream)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 98, in __init__
        self.determine_encoding()
      File "C:\Users\Subham\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 149, in determine_encoding
        self.update(1)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 189, in update
        self.check_printable(data)
      File "C:\Users\Subham\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 160, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\Subham\.condarc", position 0

`$ C:\Users\Subham\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\Subham\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Subham\Anaconda3
                 HOMEPATH=\Users\Subham
                     PATH=C:\Users\Subham\Anaconda3\Library\bin;C:\Program Files
                          (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\oracle
                          xe\app\oracle\product\11.2.0\server\bin;C:\ProgramData\Oracle\Java\jav
                          apath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDO
                          WS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows
                          Live\Shared;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program
                          Files\MATLAB\R2017a\runtime\win64;C:\Program
                          Files\MATLAB\R2017a\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program
                          Files\Common Files\Intel\WirelessCommon\;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Users\Subham\
                          AppData\Local\Programs\Python\Python35-32\Scripts\;C:\Users\Subham\App
                          Data\Local\Programs\Python\Python35-32\;C:\Users\Subham\AppData\Local\
                          Microsoft\WindowsApps;C:\Users\Subham\AppData\Local\GitHubDesktop\bin;
                          C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\texlive\2015\bin\win32
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\Subham\.condarc
 populated config files :
          conda version : 4.5.1
    conda-build version : not installed
         python version : 3.6.1.final.0
       base environment : C:\Users\Subham\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Subham\Anaconda3\pkgs
                          C:\Users\Subham\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Subham\Anaconda3\envs
                          C:\Users\Subham\AppData\Local\conda\conda\envs
                          C:\Users\Subham\.conda\envs
               platform : win-64
             user-agent : conda/4.5.1 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

##### `conda info`

```

```

##### `conda list --show-channel-urls`

```

```

_Copied from original issue: ContinuumIO/anaconda-issues#9284_

**Comment by kalefranz** [comment]
You have incorrect yaml in one of your configuration files.  Probably `C:\Users\Subham\.condarc`.

Edit: Yes, it's `C:\Users\Subham\.condarc`.  You'll need to manually fix the yaml syntax in that file.

**Comment by kalefranz** [comment]
Moved here as an open issue so that we can give a proper user error instead of the stack trace.
