### ISSUE TITLE
assertion error when elevating privileges on Windows with conda init

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7256]
```
error: AssertionError()
command: C:\Anaconda3\Scripts\conda-script.py init cmd.exe
user_agent: conda/4.6.0a2 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.16299
_messageid: -9223372036773824142
_messagetime: 1525486849596 / 2018-05-04 21:20:49

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 875, in __call__
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 83, in _main
    exit_code = do_call(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 97, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_init.py", line 51, in execute
    anaconda_prompt)
  File "C:\Anaconda3\lib\site-packages\conda\core\initialize.py", line 70, in initialize
    run_plan_elevated(plan2)
  File "C:\Anaconda3\lib\site-packages\conda\core\initialize.py", line 487, in run_plan_elevated
    assert rc == 0
AssertionError
```

**Comment by goanpeca** [comment]
Isn't this fixed by the other elevation [PR](https://github.com/conda/conda/pull/7426)
