### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'replace'

### ISSUE THREAD

**Issue by asmeurer** [conda/conda#726]
``` pytb
$conda update --all --alt-hint
Fetching package metadata: ..........
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/utils.py", line 98, in __call__
    res = cache[key]
KeyError: (<function Resolve.get_pkgs at 0x10078f0d0>, (MatchSpec('sphinx-bootstrap-theme >=0.3.5'),), frozenset({('max_only', False)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aaronmeurer/anaconda3/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/cli/install.py", line 256, in install
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/plan.py", line 265, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 658, in solve
    for pkg in self.get_pkgs(ms, max_only=max_only):
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/utils.py", line 100, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 251, in get_pkgs
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 251, in <listcomp>
    pkgs = [Package(fn, self.index[fn]) for fn in self.find_matches(ms)]
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 165, in __init__
    self.norm_version = normalized_version(self.version)
  File "/Users/aaronmeurer/anaconda3/lib/python3.4/site-packages/conda/resolve.py", line 24, in normalized_version
    version = version.replace('rc', '.dev99999')
AttributeError: 'dict' object has no attribute 'replace'
```

**Comment by athiradas** [comment]
I am getting this error for pdfquery.

AttributeError: 'dict' object has no attribute 'resolve'

**Comment by asmeurer** [comment]
@athiradas please open a new issue with the full traceback and the command you ran, as well as the output of `conda info`.
