### ISSUE TITLE
Conda solving envrionment failed

### ISSUE THREAD

**Issue by yunyundong** [conda/conda#7280]
The error things are listed following.

(tensorflow) dler@amax:~$ conda install scipy
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 438, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 179, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 560, in _prepare
        self.subdirs, prepared_specs)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 94, in query
        self.load()
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 148, in load
        _internal_state = self._load()
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 216, in _load
        mod_etag_headers.get('_mod'))
      File "/home/dler/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 416, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/dler/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 640, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "/home/dler/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 640, in <listcomp>
        history = [resp for resp in gen] if allow_redirects else []
      File "/home/dler/anaconda3/lib/python3.6/site-packages/requests/sessions.py", line 140, in resolve_redirects
        raise TooManyRedirects('Exceeded %s redirects.' % self.max_redirects, response=resp)
    requests.exceptions.TooManyRedirects: Exceeded 30 redirects.

`$ /home/dler/anaconda3/bin/conda install scipy`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=tensorflow
                CONDA_EXE=/home/dler/anaconda3/bin/conda
             CONDA_PREFIX=/home/dler/anaconda3/envs/tensorflow
    CONDA_PROMPT_MODIFIER=(tensorflow)
         CONDA_PYTHON_EXE=/home/dler/anaconda3/bin/python
               CONDA_ROOT=/home/dler/anaconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/usr/local/cuda/lib64/:
                     PATH=/home/dler/anaconda3/envs/tensorflow/bin:/home/dler/bin:/home/dler/.lo
                          cal/bin:/usr/local/cuda-9.0/bin:/home/dler/anaconda3/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/
                          games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : tensorflow
    active env location : /home/dler/anaconda3/envs/tensorflow
            shell level : 1
       user config file : /home/dler/.condarc
 populated config files : /home/dler/.condarc
          conda version : 4.5.2
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /home/dler/anaconda3  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/dler/anaconda3/pkgs
                          /home/dler/.conda/pkgs
       envs directories : /home/dler/anaconda3/envs
                          /home/dler/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/3.6.4 Linux/4.13.0-39-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: 
No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

**Comment by yunyundong** [comment]
@scw @brentp @tswicegood @blindgaenger  Can you help me?

**Comment by yunyundong** [comment]
how do I fixed the problem?

**Comment by 6868CraigYoung** [comment]
i meet the same problem.how you fixed it ?
