### ISSUE TITLE
Raspberry Pi run issue

### ISSUE THREAD

**Issue by daytondude** [conda/conda#730]
After installing conda and updatin the PATH in .bashrc on raspberry pi, most conda functions fail. For example, running
$conda search
returns the following:
user@rpi:~/anaconda/bin$ conda update
An unexpected exceptional error has occurred, please consider sending the following traceback to the conda GitHub issue tracker at https://github.com/ContinuumIO/conda/issues

Traceback (most recent call last):
  File "/home/user/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/user/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 119, in main
    args.func(args, p)
  File "/home/user/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 36, in execute
    conda = Anaconda()
  File "/home/user/anaconda/lib/python2.7/site-packages/conda/anaconda.py", line 43, in **init**
    self._index = PackageIndex(fetch_index(self.channel_urls))
  File "/home/user/anaconda/lib/python2.7/site-packages/conda/package_index.py", line 42, in __init__
    pkg = Package(pkg_info)
  File "/home/user/anaconda/lib/python2.7/site-packages/conda/package.py", line 58, in **init**
    for spec_string in self._info['requires'])
KeyError: 'requires'

Running
$conda info
returns:
Current conda install:

```
         platform : linux-armv6l
```

conda command version : 1.5.0
       root directory : /home/user/anaconda
       default prefix : /home/user/anaconda
         channel URLs : http://repo.continuum.io/pkgs/free/linux-armv6l/
                        http://repo.continuum.io/pkgs/pro/linux-armv6l/
environment locations : /home/user/anaconda/envs
          config file : None

**Comment by pelson** [comment]
I have a more up to date version of conda build on the raspberrypi binstar channel. This is not endorsed by the maintainers of conda (of which I am not one), but you can give it a try if you like:

``conda update -c raspberrypi conda``

Feel free to let me know how much mileage you get from it (I'm pretty actively working on RPi recipes at the minute). Any problems, drop me an issue on https://github.com/pelson/raspberrypi-conda-recipes which is where all the recipes will live.
