### ISSUE TITLE
install/update error

### ISSUE THREAD

**Issue by mrjeffs** [conda/conda#7304]
**I'm submitting a...**
  - [ x] bug report
  - [ ] feature request

## Current Behavior

this seems to be known issue resolved by later conda versions. however clean install starts at 

### Steps to Reproduce

```
conda clean --all

# or
conda install anaconda-clean
anaconda-clean --all
bash Anaconda2-5.1.0-Linux-x86_64.sh
conda upgrade conda
conda upgrade --all
conda list | grep conda
# yeilds this version (4.5.3) different from Current conda install below. why mismatch?:
conda                     4.5.3                    py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
# but the upgrade crashes with this message half way thru with either clean method
# conda seems stuck on lower than functioning version
```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /home/toddr/Software/anaconda2  (writable)
    default environment : /home/toddr/Software/anaconda2
       envs directories : /home/toddr/Software/anaconda2/envs
                          /home/toddr/.conda/envs
          package cache : /home/toddr/Software/anaconda2/pkgs
                          /home/toddr/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/toddr/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.13 Linux/4.4.0-124-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1001

`$ /home/toddr/Software/anaconda2/bin/conda upgrade --all`

    Traceback (most recent call last):
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 89, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
Update conda.  Use `conda install conda=4.3` or `conda update conda`.  If the issue persists, file a new issue.

**Comment by mrjeffs** [comment]
will do thx

**Comment by mrjeffs** [comment]
sorry same issue.
