### ISSUE TITLE
@kalefranz install/update error persists from #7304

### ISSUE THREAD

**Issue by mrjeffs** [conda/conda#7305]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### Steps to Reproduce

```
conda install conda=4.3
conda update --all
```

## Expected Behavior

update all packages

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.13.0
       root environment : /home/toddr/Software/anaconda2  (writable)
    default environment : /home/toddr/Software/anaconda2
       envs directories : /home/toddr/Software/anaconda2/envs
                          /home/toddr/.conda/envs
          package cache : /home/toddr/Software/anaconda2/pkgs
                          /home/toddr/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/toddr/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.13.0 CPython/2.7.13 Linux/4.4.0-124-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1001



`$ ~/Software/anaconda2/bin/conda update --all`




    Traceback (most recent call last):
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/cli/install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/plan.py", line 823, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/core/link.py", line 123, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/core/link.py", line 123, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 89, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 152, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/toddr/.local/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.


```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
conda config --show-sources
==> /home/toddr/.condarc <==
channels:
  - conda-forge
  - defaults



```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/toddr/Software/anaconda2:
#
_license                  1.1                      py27_1    defaults
alabaster                 0.7.10                   py27_0    defaults
anaconda                  custom                   py27_0    defaults
anaconda-client           1.6.3                    py27_0    defaults
anaconda-navigator        1.6.4                    py27_0    defaults
anaconda-project          0.6.0                    py27_0    defaults
apptools                  4.4.0                     <pip>
argcomplete               1.0.0                    py27_1    defaults
asn1crypto                0.22.0                   py27_0    defaults
astroid                   1.5.3                    py27_0    defaults
astropy                   2.0.1               np113py27_0    defaults
babel                     2.5.0                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.5                      py27_0    defaults
beautifulsoup4            4.6.0                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
bkcharts                  0.2                      py27_0    defaults
blaze                     0.10.1                   py27_0    defaults
bleach                    1.5.0                    py27_0    defaults
bokeh                     0.12.7                   py27_0    defaults
boto                      2.48.0                   py27_0    defaults
bottleneck                1.2.1               np113py27_0    defaults
cairo                     1.14.8                        0    defaults
cdecimal                  2.3                      py27_2    defaults
certifi                   2016.2.28                py27_0    defaults
cffi                      1.10.0                   py27_0    defaults
chardet                   3.0.4                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.7                      py27_0    defaults
cloud                     2.8.5                     <pip>
cloudpickle               0.4.0                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.9                    py27_0    defaults
conda                     4.3.34                   py27_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
contextlib2               0.5.5                    py27_0    defaults
coverage                  4.3.4                     <pip>
cryptography              1.8.1                    py27_0    defaults
curl                      7.52.1                        0    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.26                     py27_0    defaults
cytoolz                   0.8.2                    py27_0    defaults
dask                      0.15.2                   py27_0    defaults
data                      0.4                       <pip>
datashape                 0.5.4                    py27_0    defaults
dbus                      1.10.20                       0    defaults
decorator                 4.1.2                    py27_0    defaults
dill                      0.2.6                    py27_0    defaults
distributed               1.18.1                   py27_0    defaults
docutils                  0.14                     py27_0    defaults
entrypoints               0.2.3                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py27_1    defaults
flake8                    3.4.1                     <pip>
flask                     0.12.2                   py27_0    defaults
flask-cors                3.0.3                    py27_0    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         2    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
functools_lru_cache       1.4                      py27_0    defaults
future                    0.16.0                    <pip>
futures                   3.1.1                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.2.2                    py27_0    defaults
glib                      2.50.2                        1    defaults
gpgme                     1.5.5                         1    dfroger
greenlet                  0.4.12                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.7.0               np113py27_0    defaults
harfbuzz                  0.9.39                        2    defaults
hdf5                      1.8.17                        2    defaults
heapdict                  1.0.0                    py27_1    defaults
html5lib                  0.9999999                py27_0    defaults
hupper                    0.4.2                     <pip>
icu                       54.1                          0    defaults
idna                      2.6                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
ipaddress                 1.0.18                   py27_0    defaults
ipykernel                 4.6.1                    py27_0    defaults
ipython                   5.3.0                    py27_0    defaults
ipython_genutils          0.2.0                    py27_0    defaults
ipyvolume                 0.4.5                     <pip>
ipywebrtc                 0.3.0                     <pip>
ipywidgets                7.1.2                    py27_0    conda-forge
isort                     4.2.15                   py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3                      py27_0    defaults
jedi                      0.10.2                   py27_2    defaults
jinja2                    2.9.6                    py27_0    defaults
jpeg                      9b                            0    defaults
jsonschema                2.6.0                    py27_0    defaults
jupyter                   1.0.0                    py27_0    conda-forge
jupyter_client            5.2.3                    py27_0    conda-forge
jupyter_console           5.2.0                    py27_0    defaults
jupyter_core              4.4.0                      py_0    conda-forge
latex                     0.6.4                     <pip>
lazy-object-proxy         1.3.1                    py27_0    defaults
libassuan                 2.2.1                         0    dfroger
libffi                    3.2.1                         1    defaults
libgcc                    5.2.0                         0    defaults
libgfortran               3.0.0                         1    defaults
libgpg-error              1.19                          0    dfroger
libiconv                  1.14                          0    defaults
libpng                    1.6.30                        1    defaults
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         3    defaults
libtool                   2.4.2                         0    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        0    defaults
llvmlite                  0.20.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.8.0                    py27_0    defaults
Mako                      1.0.6                     <pip>
markupsafe                1.0                      py27_0    defaults
matlabengineforpython     R2017a                    <pip>
matplotlib                2.0.2               np113py27_0    defaults
mayavi                    4.5.0                     <pip>
mccabe                    0.6.1                     <pip>
mistune                   0.7.4                    py27_0    defaults
mkl                       2017.0.3                      0    defaults
mkl-service               1.1.2                    py27_3    defaults
mock                      2.0.0                     <pip>
mpmath                    0.19                     py27_1    defaults
msgpack-python            0.4.8                    py27_0    defaults
multipledispatch          0.4.9                    py27_0    defaults
navigator-updater         0.1.0                    py27_0    defaults
nbconvert                 5.2.1                    py27_0    defaults
nbformat                  4.4.0                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nilearn                   0.4.0                     <pip>
niprov                    0.5                       <pip>
niwidgets                 0.1.4                     <pip>
nltk                      3.2.4                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
nose-timer                0.7.0                     <pip>
notebook                  5.0.0                    py27_0    defaults
numba                     0.35.0              np113py27_0    defaults
numexpr                   2.6.2               np113py27_0    defaults
numpy                     1.13.1                   py27_0    defaults
numpydoc                  0.7.0                    py27_0    defaults
odo                       0.5.1                    py27_0    defaults
olefile                   0.44                     py27_0    defaults
openpyxl                  2.4.8                    py27_0    defaults
openssl                   1.0.2l                        0    defaults
ordereddict               1.1                       <pip>
packaging                 16.8                     py27_0    defaults
pandas                    0.20.3                   py27_0    defaults
pandocfilters             1.4.2                    py27_0    defaults
pango                     1.40.3                        1    defaults
partd                     0.3.8                    py27_0    defaults
PasteDeploy               1.5.2                     <pip>
path.py                   10.3.1                   py27_0    defaults
pathlib                   1.0.1                     <pip>
pathlib2                  2.3.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pbr                       2.0.0                     <pip>
pcre                      8.39                          1    defaults
pdfminer                  20140328                  <pip>
pep8                      1.7.0                    py27_0    defaults
petname                   2.0                       <pip>
pexpect                   4.2.1                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    4.2.1                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
pixman                    0.34.0                        0    defaults
ply                       3.10                     py27_0    defaults
prompt_toolkit            1.0.15                   py27_0    defaults
prov                      1.5.0                     <pip>
prov                      1.5.1                     <pip>
psutil                    5.2.2                    py27_0    defaults
ptyprocess                0.5.2                    py27_0    defaults
py                        1.4.34                   py27_0    defaults
pyasn1                    0.2.3                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycodestyle               2.3.1                    py27_0    defaults
pycodestyle               2.3.1                     <pip>
pycosat                   0.6.3                    py27_0    conda-forge
pycparser                 2.18                     py27_0    defaults
pycrypto                  2.6.1                    py27_6    defaults
pycurl                    7.43.0                   py27_2    defaults
pydicom                   0.9.9                     <pip>
pyface                    5.1.0                     <pip>
pyflakes                  1.6.0                    py27_0    defaults
pygments                  2.2.0                    py27_0    defaults
pygpgme                   0.3                      py27_0    dfroger
pylint                    1.7.2                    py27_0    defaults
pynrrd                    0.2.1                     <pip>
pyodbc                    4.0.17                   py27_0    defaults
pyopenssl                 17.0.0                   py27_0    defaults
pyparsing                 2.2.0                    py27_0    defaults
pyqt                      5.6.0                    py27_2    defaults
pyramid                   1.8.2                     <pip>
pyramid-mako              1.0.2                     <pip>
pysurfer                  0.8.0                     <pip>
pytables                  3.4.2               np113py27_0    defaults
pytest                    3.2.1                    py27_0    defaults
python                    2.7.13                        0    defaults
python-dateutil           2.6.1                    py27_0    defaults
pytz                      2017.2                   py27_0    defaults
pywavelets                0.5.2               np113py27_0    defaults
pyyaml                    3.12                     py27_0    defaults
pyzmq                     16.0.2                   py27_0    defaults
qgrid                     1.0.2                    py27_1    conda-forge
qt                        5.6.2                         5    defaults
qtawesome                 0.4.4                    py27_0    defaults
qtconsole                 4.3.1                    py27_0    defaults
qtpy                      1.3.1                    py27_0    defaults
rdflib                    4.2.2                     <pip>
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
repoze.lru                0.6                       <pip>
requests                  2.14.2                   py27_0    defaults
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_1    defaults
scandir                   1.5                      py27_0    defaults
scikit-image              0.13.0              np113py27_0    defaults
scikit-learn              0.19.0              np113py27_0    defaults
scipy                     0.19.1              np113py27_0    defaults
seaborn                   0.8                      py27_0    defaults
setuptools                36.4.0                   py27_1    defaults
sh                        1.12.14                   <pip>
shell                     1.0.1                     <pip>
shortuuid                 0.5.0                     <pip>
shutilwhich               1.1.0                     <pip>
simplegeneric             0.8.1                    py27_1    defaults
simplejson                3.11.1                    <pip>
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sortedcollections         0.5.3                    py27_0    defaults
sortedcontainers          1.5.7                    py27_0    defaults
sphinx                    1.5.6                    py27_0    defaults
sphinxcontrib             1.0                      py27_0    defaults
sphinxcontrib-websupport  1.0.1                    py27_0    defaults
spyder                    3.2.3                    py27_0    defaults
sqlalchemy                1.1.13                   py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.5.0.1                  py27_0    defaults
statsmodels               0.8.0               np113py27_0    defaults
subprocess32              3.2.7                    py27_0    defaults
sympy                     1.1.1                    py27_0    defaults
tblib                     1.3.2                    py27_0    defaults
tempdir                   0.7.1                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.6                      py27_0    defaults
testpath                  0.3.1                    py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.2                    py27_0    defaults
tornado                   4.5.2                    py27_0    defaults
traitlets                 4.3.2                    py27_0    defaults
traits                    4.6.0                     <pip>
traitsui                  5.1.0                     <pip>
translationstring         1.3                       <pip>
typing                    3.6.2                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
unixodbc                  2.3.4                         0    defaults
venusian                  1.0                       <pip>
vtk                       6.3.0                    py27_1    defaults
waitress                  1.0.2                     <pip>
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.12.2                   py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        3.1.4                    py27_0    conda-forge
wrapt                     1.10.11                  py27_0    defaults
xlrd                      1.1.0                    py27_0    defaults
xlsxwriter                0.9.8                    py27_0    defaults
xlwt                      1.3.0                    py27_0    defaults
xz                        5.2.3                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.5                         0    defaults
zict                      0.1.2                    py27_0    defaults
zlib                      1.2.11                        0    defaults
zope.deprecation          4.2.0                     <pip>
zope.interface            4.3.3                     <pip>

```
</p></details>

**Comment by kalefranz** [comment]
It looks like you're still on conda 4.3.13.  For whatever reason, `conda install conda=4.3` apparently had no effect.  If you really need to stay on conda 4.3, I'd at least like to figure out if we've resolved this for you in the latest 4.3.

So... I guess try `conda install conda=4.3.27`, and then if that succeeds, `conda install conda=4.3.34`.  Then show me the output of `conda info`.

**Comment by kalefranz** [comment]
Wait. How did you end up with conda in `~/.local`?  I guess you did `pip install --user conda` at some point?  You're going to have to unwind that mess.  And if there is documentation *anywhere* on the internet saying `pip install --user conda`, please tell me where it is.  That needs to be killed off.

**Comment by kalefranz** [comment]
You're at least going to want

    rm -rf /home/toddr/.local/lib/python2.7/site-packages/conda*

and, if it were me,

    rm -rf /home/toddr/.local/lib/python*

**Comment by mrjeffs** [comment]
solved. legacy hrdware headache over. thx.
