### ISSUE TITLE
after installing anaconda is not able to open

### ISSUE THREAD

**Issue by gurumail10** [conda/conda#7315]
**I'm submitting a...**
  - [ ] bug report
  - [ ] feature request

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by gurumail10** [comment]
Navigator Error

An unexpected error occurred on Navigator start-up

Report

Please report this issue in the anaconda  issue tracker  


Main Error

byte indices must be integers or slices, not str


Traceback

Traceback (most recent call last):
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\app\start.py", line 120, in start_app
    window = run_app(splash)
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\app\start.py", line 63, in run_app
    window = MainWindow(splash=splash)
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2004, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 88, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1690, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\api\conda_api.py", line 347, in __init__
    self.set_conda_prefix()
  File "C:\Users\guru1_000\Anaconda33\lib\site-packages\anaconda_navigator\api\conda_api.py", line 496, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
TypeError: byte indices must be integers or slices, not str

**Comment by gurumail10** [comment]
plz tell me how I can remove this
