### ISSUE TITLE
Failing to install mkl

### ISSUE THREAD

**Issue by tcosmo** [conda/conda#7317]
**I'm submitting a...**
  - [X] bug report
  - [ ] feature request

## Current Behavior

Conda fails to install 'mkl' in a new empty environment. Fails with Exception:
`KeyError: Dist(channel='<unknown>', dist_name='mkl-2018.0.2-1', name='mkl', version='2018.0.2', build_string='1', build_number=1, base_url='file:///usr/pkgs', platform=None)
`

### Steps to Reproduce

```
conda install mkl                                                                                                                      :(
Solving environment: done

## Package Plan ##

  environment location: /home/cosmo/.conda/envs/envX

  added / updated specs: 
    - mkl


The following packages will be downloaded:


# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/usr/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/usr/lib/python3.6/site-packages/conda/cli/install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/usr/lib/python3.6/site-packages/conda/cli/install.py", line 269, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "/usr/lib/python3.6/site-packages/conda/core/link.py", line 735, in print_transaction_summary
        specs_to_remove=stp.remove_specs, specs_to_add=stp.update_specs)
      File "/usr/lib/python3.6/site-packages/conda/plan.py", line 97, in display_actions
        info = index[dist]
    KeyError: Dist(channel='<unknown>', dist_name='mkl-2018.0.2-1', name='mkl', version='2018.0.2', build_string='1', build_number=1, base_url='file:///usr/pkgs', platform=None)

`$ /usr/bin/conda install mkl`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=envX
                CONDA_EXE=/usr/bin/conda
             CONDA_PREFIX=/home/cosmo/.conda/envs/envX
    CONDA_PROMPT_MODIFIER=(envX)
         CONDA_PYTHON_EXE=/usr/bin/python
               CONDA_ROOT=/usr
              CONDA_SHLVL=1
        DYLD_LIBRARY_PATH=/home/cosmo/torch/install/lib:/home/cosmo/torch/install/lib:/home/cosm
                          o/torch/install/lib:
       GLADE_CATALOG_PATH=:
        GLADE_MODULE_PATH=:
        GLADE_PIXMAP_PATH=:
          LD_LIBRARY_PATH=/home/cosmo/torch/install/lib:/home/cosmo/torch/install/lib:/home/cosm
                          o/torch/install/lib:
                LUA_CPATH=/home/cosmo/torch/install/lib/?.so;/home/cosmo/.luarocks/lib/lua/5.1/?
                          .so;/home/cosmo/torch/install/lib/lua/5.1/?.so;./?.so;/usr/local/lib/l
                          ua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so
                 LUA_PATH=/home/cosmo/.luarocks/share/lua/5.1/?.lua;/home/cosmo/.luarocks/share/
                          lua/5.1/?/init.lua;/home/cosmo/torch/install/share/lua/5.1/?.lua;/home
                          /cosmo/torch/install/share/lua/5.1/?/init.lua;./?.lua;/home/cosmo/torc
                          h/install/share/luajit-2.1.0-beta1/?.lua;/usr/local/share/lua/5.1/?.lu
                          a;/usr/local/share/lua/5.1/?/init.lua
          MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
                     PATH=/home/cosmo/.conda/envs/envX/bin:/home/cosmo/anaconda3/bin:/home/cosmo
                          /torch/install/bin:/home/cosmo/.cargo/bin:/usr/local/bin:/usr/bin:/bin
                          :/usr/local/sbin:/opt/android-sdk/tools:/opt/android-sdk/tools/bin:/us
                          r/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin
                          /core_perl:/home/cosmo/.gem/ruby/2.4.0/bin
               PYTHONPATH=:/home/cosmo/util
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : envX
    active env location : /home/cosmo/.conda/envs/envX
            shell level : 1
       user config file : /home/cosmo/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/pkgs
                          /home/cosmo/.conda/pkgs
       envs directories : /home/cosmo/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.4 Linux/4.15.12-1-ARCH arch/ glibc/2.26
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```

## Expected Behavior

It should have installed the mkl package.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : envX
    active env location : /home/cosmo/.conda/envs/envX
            shell level : 1
       user config file : /home/cosmo/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.4.final.0
       base environment : /usr  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/pkgs
                          /home/cosmo/.conda/pkgs
       envs directories : /home/cosmo/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.4 Linux/4.15.12-1-ARCH arch/ glibc/2.26
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Empty
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/cosmo/.conda/envs/envX:
#
# Name                    Version                   Build  Channel
```
</p></details>

**Comment by mingwandroid** [comment]
Have your really installed conda to /usr?

That is a very brave step!

**Comment by tcosmo** [comment]
Ahah Im not so familiar with conda, why is this bad practice?

**Comment by mingwandroid** [comment]
Because that folder is exclusively meant to be controlled by type Linux distribution.

**Comment by tcosmo** [comment]
hm you mean  its going to mess with pacman? (im on archlinux)

**Comment by mingwandroid** [comment]
Yes, it absolutely will. Both distros will assume they have exclusive control of the management of all files in `/usr` and installing two distros there will violate those assumptions in an OS breaking way.

I would suggest you reinstall your OS here and start again to be honest with you. Even if nothing seems broken at present it'll be a submarine issue waiting to strike at any point.

**Comment by tcosmo** [comment]
!!!

Thank you for the info and advice!
