### ISSUE TITLE
Error in install_keras()

### ISSUE THREAD

**Issue by Arhamabidi** [conda/conda#7318]
Current conda install:

               platform : osx-64
          conda version : 4.3.27
       conda is private : False
      conda-env version : 4.3.27
    conda-build version : 3.0.22
         python version : 3.6.2.final.0
       requests version : 2.18.4
       root environment : /Users/arham/anaconda3  (writable)
    default environment : /Users/arham/anaconda3
       envs directories : /Users/arham/anaconda3/envs
                          /Users/arham/.conda/envs
          package cache : /Users/arham/anaconda3/pkgs
                          /Users/arham/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /Users/arham/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.27 requests/2.18.4 CPython/3.6.2 Darwin/17.5.0 OSX/10.13.4    
                UID:GID : 501:20

`$ /Users/arham/anaconda3/bin/conda create --yes --name r-tensorflow python`

    Traceback (most recent call last):
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 261, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 473, in install_actions_list
        linked_in_root = linked_data(context.root_prefix)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 115, in linked_data
        load_linked_data(prefix, dist_name, ignore_channels=ignore_channels)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/core/linked_data.py", line 68, in load_linked_data
        linked_data_[prefix][dist] = rec = IndexRecord(**rec)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/Users/arham/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Invalid value 1506080276.026 for timestamp

Error: Error 1 occurred creating conda environment r-tensorflow

**Comment by VanitarNordic** [comment]
if you use Anaconda, you can use  `conda install -c hesi_m tensorflow ` to install tensorflow 1.9.0 for CPU 

if you specifically use Keras also, you can use  `conda install -c hesi_m keras` which installs Keras 2.2.0 in accompany with everything including tensorflow 1.9.0

It is better to make a fresh anaconda environment for your experiments
