### ISSUE TITLE
failure conda install --yes --quiet scipy==0.13.2

### ISSUE THREAD

**Issue by eepstein** [conda/conda#733]
```pytb
sudo: conda install --yes --quiet scipy==0.13.2
out: Fetching package metadata: An unexpected error has occurred, please consider sending the
out: following traceback to the conda GitHub issue tracker at:
out: 
out:     https://github.com/conda/conda/issues
out: 
out: Include the output of the command 'conda info' in your report.
out: 
out: 
out: Traceback (most recent call last):
out:   File "/usr/local/bin/conda", line 5, in <module>
out:     sys.exit(main())
out:   File "/usr/local/lib/python2.7/dist-packages/conda/cli/main.py", line 179, in main
out:     args.func(args, p)
out:   File "/usr/local/lib/python2.7/dist-packages/conda/cli/main_install.py", line 45, in execute
out:     install.install(args, parser, 'install')
out:   File "/usr/local/lib/python2.7/dist-packages/conda/cli/install.py", line 184, in install
out:     unknown=args.unknown)
out:   File "/usr/local/lib/python2.7/dist-packages/conda/api.py", line 40, in get_index
out:     unknown=unknown)
out:   File "/usr/local/lib/python2.7/dist-packages/conda/utils.py", line 77, in __call__
out:     value = self.func(*args, **kw)
out:   File "/usr/local/lib/python2.7/dist-packages/conda/fetch.py", line 111, in fetch_index
out:     session = CondaSession()
out:   File "/usr/local/lib/python2.7/dist-packages/conda/connection.py", line 64, in __init__
out:     http_adapter = requests.adapters.HTTPAdapter(max_retries=retries)
out: TypeError: __init__() got an unexpected keyword argument 'max_retries'
out: 


Fatal error: sudo() received nonzero return code 1 while executing!

```

Requested: conda install --yes --quiet scipy==0.13.2

$ conda info
Current conda install:

             platform : linux-64
        conda version : 3.5.0
       python version : 2.7.4.final.0
     root environment : /usr  (read only)
  default environment : /usr
     envs directories : /home/ubuntu/envs
                        /usr/envs
        package cache : /home/ubuntu/envs/.pkgs
                        /usr/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/linux-64/
                        http://repo.continuum.io/pkgs/pro/linux-64/
          config file : None
    is foreign system : True

**Comment by zwass** [comment]
An old version of requests installed on my system caused this error for me today. Something should be done to check for this condition and provide a more friendly error message.

**Comment by soapy1** [comment]
Conda currently depends on requests >=2.5.3 as specified in https://github.com/conda/conda/blob/master/conda.recipe/meta.yaml.
