### ISSUE TITLE
RFE: Support FIPS mode - do not use md5 hash

### ISSUE THREAD

**Issue by opoplawski** [conda/conda#7335]
**I'm submitting a...**
  - [ ] bug report
  - [X] feature request

md5 hashes are unsafe and are disabled in FIPS mode.

See also #5282 

### Steps to Reproduce
Boot with fips=1 
```
# /usr/bin/conda create -y -n scipy35-anaconda -c anaconda  python=3.5 astropy basemap h5py jupyter matplotlib mkl mysql-connector-python netcdf4 notebook numba pandas pip scikit-learn scipy seaborn sunpy sympy xarray nbbrowserpdf tensorflow                            
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/lib/python3.4/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/usr/lib/python3.4/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/usr/lib/python3.4/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/lib/python3.4/site-packages/conda/cli/main_create.py", line 11, in execute
        install(args, parser, 'create')
      File "/usr/lib/python3.4/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/usr/lib/python3.4/site-packages/conda/core/solve.py", line 505, in solve_for_transaction
        force_remove, force_reinstall)
      File "/usr/lib/python3.4/site-packages/conda/core/solve.py", line 438, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/usr/lib/python3.4/site-packages/conda/core/solve.py", line 179, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/usr/lib/python3.4/site-packages/conda/core/solve.py", line 560, in _prepare
        self.subdirs, prepared_specs)
      File "/usr/lib/python3.4/site-packages/conda/core/index.py", line 174, in get_reduced_index
        subdir_datas = tuple(SubdirData(Channel(url)) for url in channel_urls)
      File "/usr/lib/python3.4/site-packages/conda/core/index.py", line 174, in <genexpr>
        subdir_datas = tuple(SubdirData(Channel(url)) for url in channel_urls)
      File "/usr/lib/python3.4/site-packages/conda/core/subdir_data.py", line 68, in __call__
        subdir_data_instance = super(SubdirDataType, cls).__call__(channel)
      File "/usr/lib/python3.4/site-packages/conda/core/subdir_data.py", line 131, in __init__
        splitext(cache_fn_url(self.url_w_credentials))[0])
      File "/usr/lib/python3.4/site-packages/conda/core/subdir_data.py", line 606, in cache_fn_url
        md5 = hashlib.md5(ensure_binary(url)).hexdigest()
    ValueError: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
```

## Expected Behavior
conda should work

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /root/.condarc
 populated config files : /etc/conda/condarc.d/nwra.yml
                          /usr/share/conda/condarc.d/defaults.yaml
          conda version : 4.5.1
    conda-build version : not installed
         python version : 3.4.8.final.0
       base environment : /usr  (read only)
           channel URLs : http://conda.cora.nwra.com/main/linux-64
                          http://conda.cora.nwra.com/main/noarch
                          http://condaorg.cora.nwra.com/ncar/linux-64
                          http://condaorg.cora.nwra.com/ncar/noarch
                          http://condaorg.cora.nwra.com/OpenAstronomy/linux-64
                          http://condaorg.cora.nwra.com/OpenAstronomy/noarch
          package cache : /var/cache/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /root/conda/envs
                          /root/.conda/envs
                          /usr/envs
               platform : linux-64
             user-agent : conda/4.5.1 requests/2.12.5 CPython/3.4.8 Linux/3.10.0-862.3.2.el7.x86_64 rhel/7.5 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False


```
</p></details>

**Comment by lilmatt** [comment]
@kalefranz Could this be handled by changing to sha256 here, or is there more to it?
https://github.com/conda/conda/blob/master/conda/core/subdir_data.py#L634

**Comment by msarahan** [comment]
seems like it.  This really isn't a cryptographic application of md5, though.  It's just a short name.  Perhaps we should just base64 encode it instead of md5?

**Comment by opoplawski** [comment]
Presumably this still needs to get addressed

**Comment by travishathaway** [comment]
@chenghlee and @jezdez,

Has this been resolved? I couldn't help but notice the usage of `usedforsecurity=False` in our usage of `hashlib` here: https://github.com/conda/conda/blob/8faf745567b93e8112003b934bbe4b9191c16506/conda/gateways/repodata/__init__.py#L917-L928

**Comment by jezdez** [comment]
This is unresolved so far, we haven't come to a conclusion if we should support running on FIPS enabled system due to a lack of access for testing.

@chenghlee Do you know more off the top of your head?

**Comment by travishathaway** [comment]
I had the chance to talk with @chenghlee, and he said that FIPS is something that we still do not officially support, but it is an ongoing discussion.

**Comment by xnox** [comment]
I can test on FIPS systems as containers as github actions. Is that something that is needed to support conda in fips mode?
