### ISSUE TITLE
conda init cmd.exe fails (conda 4.6.0a2)

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#7345]
I see the below error when trying to initialise my shell (apparently required for `conda-build`)
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 875, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 83, in _main
        exit_code = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 97, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_init.py", line 51, in execute
        anaconda_prompt)
      File "C:\Miniconda3\lib\site-packages\conda\core\initialize.py", line 70, in initialize
        run_plan_elevated(plan2)
      File "C:\Miniconda3\lib\site-packages\conda\core\initialize.py", line 487, in run_plan_elevated
        assert rc == 0
    AssertionError

`$ C:\Miniconda3\Scripts\conda-script.py init cmd.exe`
<snip>
```
<details>

```
          conda version : 4.6.0a2
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/numba/win-64
                          https://conda.anaconda.org/numba/noarch
                          https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://conda.anaconda.org/dhirschfeld/win-64
                          https://conda.anaconda.org/dhirschfeld/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\dhirschf\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\dhirschf\AppData\Local\conda\conda\envs
                          C:\Users\dhirschf\.conda\envs
               platform : win-64
             user-agent : conda/4.6.0a2 requests/2.18.4 CPython/3.6.5 Windows/7 Windows/6.1.7601
          administrator : True
             netrc file : None
           offline mode : False
```
</details>

Sorry for the brevity - too busy to go into much detail (at the moment) but figured an imperfect bug report was better than no bug report.

**Comment by kalefranz** [comment]
fixed in #7426
