### ISSUE TITLE
image not found error when launching Spyder and JupyterNotebook 

### ISSUE THREAD

**Issue by userofgithub1** [conda/conda#7346]
I'm new to python and the virtual environment stuff. I'm facing issues opening jupyter notebook and Spyder after updating conda.

Here are some info about the versions I have:
```
$ conda info

     active environment : None
       user config file : /Users/AMAL/.condarc
 populated config files : /Users/AMAL/.condarc
          conda version : 4.5.4
    conda-build version : 3.0.27
         python version : 2.7.14.final.0
       base environment : /Users/AMAL/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/AMAL/anaconda2/pkgs
                          /Users/AMAL/.conda/pkgs
       envs directories : /Users/AMAL/anaconda2/envs
                          /Users/AMAL/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/2.7.14 Darwin/15.5.0 OSX/10.11.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False


JupyerNotebook version : 5.5.0
Jupyter version : 4.4.0
Spyder version : 3.2.8
```
Spyder fails to launch and When trying to launch spyder from anaconda navigator I get this error:

```
Traceback (most recent call last):
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3208, in main
mainwindow = run_spyder(app, options, args)
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 3084, in run_spyder
main.setup()
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/spyder/app/mainwindow.py", line 848, in setup
from spyder.plugins.editor import Editor
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/spyder/plugins/editor.py", line 41, in 
from spyder.utils.introspection.manager import IntrospectionManager
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/spyder/utils/introspection/manager.py", line 21, in 
from spyder.utils.introspection.plugin_client import PluginClient
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/spyder/utils/introspection/plugin_client.py", line 18, in 
import zmq
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/__init__.py", line 47, in 
from zmq import backend
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in 
reraise(*exc_info)
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in 
_ns = select_backend(first)
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
mod = __import__(name, fromlist=public_api)
File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in 
from . import (constants, error, message, context,
ImportError: dlopen(/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/error.so, 2): Library not loaded: @rpath/libsodium.23.dylib
Referenced from: /Users/AMAL/anaconda2/lib/libzmq.5.dylib
Reason: image not found
```

Trying to launch jupyter notebook from anaconda throws the same image not found error:

```
Traceback (most recent call last):
  File "/Users/AMAL/anaconda2/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/notebook/notebookapp.py", line 45, in <module>
    from zmq.eventloop import ioloop
  File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/select.py", line 26, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: dlopen(/Users/AMAL/anaconda2/lib/python2.7/site-packages/zmq/backend/cython/error.so, 2): Library not loaded: @rpath/libsodium.23.dylib
  Referenced from: /Users/AMAL/anaconda2/lib/libzmq.5.dylib
  Reason: image not found
```

Everything was working smoothly but after following anaconda instructions and recommendations to update I started getting those errors. How can I resolve this issue? I'm new to all this and still learning so any help will be much appreciated.

Thank you in advance,

**Comment by niranjanreddy891** [comment]
@userofgithub1, which operating system are you using?

**Comment by kalefranz** [comment]
@userofgithub1 Please use the issue template.  Specifically, you failed to include the output of `conda config --show-sources` and `conda list --show-channel-urls`.

> after following anaconda instructions and recommendations to update

That's also vague. Please include a pointer to the instructions you followed, or just reproduce the instructions in the issue for us.

**Comment by userofgithub1** [comment]
Thank you for your help, but this was a problem with the installationf of zermq. From stackoverflow https://stackoverflow.com/questions/50584217/launching-spyder-and-jupyternotebook-causese-importerror-when-image-not-found/50587074#50587074 

The issue was solved by doing:
conda remove zeromq
conda install  zeromq

And updating conda build. 

Best,

**Comment by hallben4** [comment]
I
