### ISSUE TITLE
conda build local package  no arch

### ISSUE THREAD

**Issue by bioinfo-dirty-jobs** [conda/conda#7348]
I have this version of conda:
```
 conda --version
conda 4.5.4
circleci  --version
0.0.4705-deba4df
```
I would like to prepare my local version of vcf2maf file with the last version of this package.
Here I change the previous recipes with the new links. (https://github.com/bioinfo-dirty-jobs/conda_vcf2maf)
I Have this error:

```
conda-build  .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
BUILD START: [u'vcf2maf-1.6.16-pl5.22.0_1.tar.bz2']
Traceback (most recent call last):
  File "/home/maurizio/miniconda2/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 420, in main
    execute(sys.argv[1:])
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/cli/main_build.py", line 411, in execute
    verify=args.verify)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/api.py", line 200, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 2168, in build_tree
    notest=notest,
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/build.py", line 1255, in build
    add_upstream_pins(m, False, exclude_pattern)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 333, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 321, in _read_upstream_pin_files
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/render.py", line 124, in get_env_dependencies
    channel_urls=tuple(m.config.channel_urls))
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/environ.py", line 695, in get_install_actions
    locking=locking, timeout=timeout)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda_build/index.py", line 104, in get_build_index
    platform=subdir)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 65, in get_index
    index = fetch_index(channel_urls, use_cache=use_cache)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/index.py", line 83, in fetch_index
    index = collect_all_repodata_as_index(use_cache, channel_urls)
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 598, in collect_all_repodata_as_index
    index.update(sd.iter_dists_records())
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 164, in iter_dists_records
    self.load()
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 148, in load
    _internal_state = self._load()
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 216, in _load
    mod_etag_headers.get('_mod'))
  File "/home/maurizio/miniconda2/lib/python2.7/site-packages/conda/core/subdir_data.py", line 550, in fetch_repodata_remote_request
    caused_by=e)
conda.exceptions.CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/bioconda./noarch/repodata.json>
Elapsed: 00:00.143995
CF-RAY: 42311b43785f7105-FCO

The remote server could not find the noarch directory for the
requested channel with url: https://conda.anaconda.org/bioconda.

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

```

**Comment by mcg1969** [comment]
It looks like you have a stray period `.` at the end of your channel name for `bioconda` ...

**Comment by bioinfo-dirty-jobs** [comment]
Thanks so much @mcg1969   
this is 
```
 /home/maurizio/.condarc <==
channels:
  - bioconda
  - conda-forge
  - r
  - https://conda.anaconda.org/dranew
  - BioBuilds
  - bioconda.
  - defaults
```

It is strange..
