### ISSUE TITLE
Running conda commands results in spinner producing an IOError

### ISSUE THREAD

**Issue by wagnerpeer** [conda/conda#7349]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

If I try to install or update a package using the command line (cmd.exe) the known spinner appears.
```Solving environment: \ ```
However after a few seconds in which the spinner rotates, an error message is printed to the screen. The actual operation runs unaffected in the background and proceeds to print on the screen once the environment was found and I get asked if I want to proceed with the suggested modifications.

### Steps to Reproduce

```
E:\Repos\PythonPackages>conda install -n FT1 jsonschema
Solving environment: /Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\PWagner\miniconda2\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\PWagner\miniconda2\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Users\PWagner\miniconda2\lib\site-packages\conda\common\io.py", line 339, in _start_spinning
    self.fh.write(next(self.spinner_cycle) + ' ')
IOError: [Errno 0] Error

done

## Package Plan ##

  environment location: C:\Users\PWagner\miniconda2\envs\FT1

  added / updated specs:
    - jsonschema


The following packages will be UPDATED:

    jsonschema: 2.6.0-py27_0 http://condamirror-lin/conda/anaconda --> 2.6.0-py27haaf3834_0 http://condamirror-lin/conda/anaconda

Proceed ([y]/n)? n
```

## Expected Behavior

I expect the spinner to rotate as long as the operation of resolving the environment needs and afterwards present me suggestions for modifications without any error message.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
E:\Repos\PythonPackages>conda info

     active environment : None
       user config file : C:\Users\PWagner\.condarc
 populated config files : C:\Users\PWagner\.condarc
          conda version : 4.5.2
    conda-build version : not installed
         python version : 2.7.14.final.0
       base environment : C:\Users\PWagner\miniconda2  (writable)
           channel URLs : http://condamirror-lin/conda/ROSEN/win-64
                          http://condamirror-lin/conda/ROSEN/noarch
                          file://condamirror-lin/ROSEN-private/win-64
                          file://condamirror-lin/ROSEN-private/noarch
                          http://condamirror-lin/conda/anaconda/win-64
                          http://condamirror-lin/conda/anaconda/noarch
                          http://condamirror-lin/conda/conda-forge/win-64
                          http://condamirror-lin/conda/conda-forge/noarch
          package cache : C:\Users\PWagner\miniconda2\pkgs
                          C:\Users\PWagner\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\PWagner\miniconda2\envs
                          C:\Users\PWagner\AppData\Local\conda\conda\envs
                          C:\Users\PWagner\.conda\envs
               platform : win-64
             user-agent : conda/4.5.2 requests/2.18.4 CPython/2.7.14 Windows/10 Windows/10.0.16299
          administrator : False
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
E:\Repos\PythonPackages>conda config --show-sources
==> C:\Users\PWagner\.condarc <==
channels:
  - http://condamirror-lin/conda/ROSEN
  - file://\\condamirror-lin\ROSEN-private
  - http://condamirror-lin/conda/anaconda
  - http://condamirror-lin/conda/conda-forge

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
E:\Repos\PythonPackages>conda list --show-channel-urls
# packages in environment at C:\Users\PWagner\miniconda2:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py27_0    defaults
ca-certificates           2018.03.07                    0    http://condamirror-lin/conda/anaconda
certifi                   2018.4.16                py27_0    http://condamirror-lin/conda/anaconda
cffi                      1.11.5           py27hdb016f4_0    defaults
chardet                   3.0.4            py27h56c3b73_1    defaults
conda                     4.5.2                    py27_0    http://condamirror-lin/conda/anaconda
conda-env                 2.6.0                h36134e3_1    defaults
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.2.2            py27h0c8e037_0    defaults
enum34                    1.1.6            py27h2aa175b_1    defaults
futures                   3.2.0            py27h8b2aecd_0    defaults
idna                      2.6              py27h1ea29d3_1    defaults
ipaddress                 1.0.22                   py27_0    defaults
menuinst                  1.4.11           py27h0c8e037_0    defaults
openssl                   1.0.2o               h2c51139_0    http://condamirror-lin/conda/anaconda
pip                       9.0.3                    py27_0    defaults
pycosat                   0.6.3            py27hcd410c5_0    defaults
pycparser                 2.18             py27hb43d16c_1    defaults
pyopenssl                 17.5.0           py27h59156d7_0    defaults
pysocks                   1.6.8                    py27_0    defaults
python                    2.7.14              h4a10d90_31    defaults
pywin32                   223              py27h0c8e037_0    defaults
requests                  2.18.4           py27h3159eba_1    defaults
ruamel_yaml               0.15.35          py27h0c8e037_1    defaults
setuptools                39.0.1                   py27_0    defaults
six                       1.11.0           py27ha5e1701_1    defaults
urllib3                   1.22             py27hb9f5a07_0    defaults
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.00.30729.1         hfaea7d5_1    defaults
wheel                     0.31.0                   py27_0    defaults
win_inet_pton             1.0.1            py27hf41312a_1    defaults
wincertstore              0.2              py27hf04cefb_0    defaults
yaml                      0.1.7             vc9heb3852e_1  [vc9]  http://condamirror-lin/conda/anaconda

```
</p></details>

**Comment by mbargull** [comment]
A quick search for `IOError: [Errno 0] Error` came up with this:
https://github.com/robotframework/robotframework/issues/2709#issuecomment-350676922
Which means this is likely a bug in Windows 10.
I didn't look further how to mitigate it, though.

**Comment by niranjanreddy891** [comment]
@wagnerpeer, I was facing many issues on win-10, so i switched to win-7. Try switching your o.s if possible. :)

**Comment by wagnerpeer** [comment]
Thanks for the answers.

@niranjanreddy891: I regret, but this is not an option. There are circumstances which make me switch to Windows 10.

@mbargull: You are right, I am experiencing this issue since I am using Windows 10. Do I understand correctly that there is nothing we can do about this error popping up as long as MS don't fix it?

**Comment by niranjanreddy891** [comment]
@wagnerpeer, its an issue with the o.s. So, Microsoft has to fix this issue on win-10. Try posting the same issue on Microsoft forum. :)

**Comment by wagnerpeer** [comment]
This issue seems to no longer be present on a Windows 10 Build 1809.

Therefore closing it.
