### ISSUE TITLE
An unexpected error occurred on Navigator start-up

### ISSUE THREAD

**Issue by angelsuryavanshi** [conda/conda#7374]
Navigator Error
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\ANGEL\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\ANGEL\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by irvanseptiar** [comment]
that problem also hit me. please help

**Comment by rdebnath93** [comment]
Did anyone find the solution yet? Thanks in advance.

**Comment by Ylunio** [comment]
I'm having the exact same problem. Everything was working fine, and all of a sudden this...

**Comment by goanpeca** [comment]
Please open the `Anaconda Prompt` and provide any information regarding: 

- Do you see an error when opening the anaconda prompt?
- If you try to activate the `base` environment. `conda activate base` do you see a problem?
- Try running `anaconda-navigator` from this prompt and provide feedback on any stacktrace.

**Comment by iaggocapitanio2** [comment]
i have the same problem, i tried everything!

**Comment by iaggocapitanio2** [comment]
the conda command doesn't work

**Comment by goanpeca** [comment]
@iaggocapitanio2 what is the error traceback?

**Comment by rdebnath93** [comment]
@goanpeca
This is the error traceback basically everytime when the conda command is executed.



 # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\hp\AppData\Local\Continuum\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\hp\.condarc", position 0

`$ C:\Users\hp\AppData\Local\Continuum\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

**Comment by rdebnath93** [comment]
@goanpeca and yes, there is an error at the start of anaconda prompt.

**Comment by goanpeca** [comment]
@rdebnath93 please remove this file

`C:\Users\hp\.condarc` and try again

**Comment by hidayetcetin** [comment]
thanks goanpeca :)

**Comment by lavilad** [comment]
thanks goanpeca !!!

**Comment by prefect12** [comment]
thanks, you save my ass bro

**Comment by jayDevaney** [comment]
Thanks Gonzalo!

**Comment by suryajith082** [comment]
This error was ruining my day Thankz goanpeca

**Comment by ashirhanif** [comment]
I am also having the same problem and couldn't resolve it by the guidlines provided up in this coversation. Please help me.
