### ISSUE TITLE
Environment creation fails when running from a docker container without root access

### ISSUE THREAD

**Issue by thiagocrepaldi** [conda/conda#7391]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
I am trying to create an environment for CNTK inside a docker container running with UID 1000 (not root). When I do that, I get the following error all the time:

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    HTTPError('400 Client Error: Bad Request for url: https://conda.anaconda.org/conda-forge/linux-64/repodata.json',)

If I try to wget https://conda.anaconda.org/conda-forge/linux-64/repodata.json, it will work. network is working 

### Steps to Reproduce
/usr/local/miniconda3/bin/conda env create --file Scripts/install/linux/conda-linux-cntk-py27-environment.yml --prefix /home/ubuntu/anaconda-envs/cntk-py27 -vv --debug

conda-linux-cntk-py27-environment.yml can be found at https://raw.githubusercontent.com/Microsoft/CNTK/master/Scripts/install/linux/conda-linux-cntk-py27-environment.ym

## Expected Behavior
The environment should be created. It does work if I run docker container as root (e.g. passing the -u0 to the docker run command).

## Environment Information
Note that the folder of miniconda is read-only and I am creating the environment in a different prefix (using the --prefix arg).

The docker container can be any with the following basic image: 
FROM nvidia/cuda@sha256:33add9c50ab76b8f3a92187c0418ed600d5bea27690fda40711122fdc28ce2f4

<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /usr/local/miniconda3  (read only)
    default environment : /usr/local/miniconda3
       envs directories : /usr/local/miniconda3/envs
                          /home/ubuntu/.conda/envs
          package cache : /usr/local/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/ubuntu/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Linux/4.13.0-1018-azure debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/ubuntu/.condarc <==
ssl_verify: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /usr/local/miniconda3:
#
cffi                      1.9.1                    py36_0    defaults
conda                     4.3.13                   py36_0    defaults
conda-env                 2.6.0                         0    defaults
cryptography              1.7.1                    py36_0    defaults
idna                      2.2                      py36_0    defaults
libffi                    3.2.1                         1    defaults
openssl                   1.0.2k                        0    defaults
pip                       9.0.1                    py36_1    defaults
pyasn1                    0.1.9                    py36_0    defaults
pycosat                   0.6.1                    py36_1    defaults
pycparser                 2.17                     py36_0    defaults
pyopenssl                 16.2.0                   py36_0    defaults
python                    3.6.0                         0    defaults
readline                  6.2                           2    defaults
requests                  2.12.4                   py36_0    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
setuptools                27.2.0                   py36_0    defaults
six                       1.10.0                   py36_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py36_0    defaults
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.8                         3    defaults

```
</p></details>

**Comment by kalefranz** [comment]
Latest conda version is 4.5.4.  Any reason you're working with something so outdated?

**Comment by thiagocrepaldi** [comment]
Yes. Newer versions of pytest break our tests due to changes on pytest behavior.We plan on migrating to the latest, but that should take some time

**Comment by kalefranz** [comment]
Oh that's interesting.  How is the pytest version coupled to the version of conda required?

**Comment by thiagocrepaldi** [comment]
Not sure. But when I installed the latest Anaconda and installed pytest, the version diverged

**Comment by kalefranz** [comment]
Oh I see. The coupling of conda and pytest here is through the Anaconda installer. You can update conda independently of the anaconda metapackage. Either way, I guess we need the output of the failing command with `-vv` so we can see more details of the failing HTTP request.

**Comment by jeffkpayne** [comment]
Well, I'm seeing cert related errors while trying to access our private channel's repo:
```
$ wget https://conda.anaconda.org/t/****/bombora/osx-64/repodata.json                                   (base)
--2018-06-06 17:18:09--  https://conda.anaconda.org/t/****/bombora/osx-64/repodata.json
Resolving conda.anaconda.org... 104.16.192.233, 104.16.193.233
Connecting to conda.anaconda.org|104.16.192.233|:443... connected.
ERROR: cannot verify conda.anaconda.org's certificate, issued by 'CN=COMODO RSA Domain Validation Secure Server CA,O=COMODO CA Limited,L=Salford,ST=Greater Manchester,C=GB':
  Issued certificate has expired.
To connect to conda.anaconda.org insecurely, use `--no-check-certificate'.
```

**Comment by thiagocrepaldi** [comment]
I am still getting the error. Here is the output with --vv --debug

ubuntu@b8d7b681abfe:~/workspace$ /usr/local/miniconda3/bin/conda env create --file Scripts/install/linux/conda-linux-cntk-py27-environment.yml --prefix /home/ubuntu/anaconda-envs/cntk-py27 -vv --debug
Fetching package metadata .........An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.13
       conda is private : False
      conda-env version : 4.3.13
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /usr/local/miniconda3  (read only)
    default environment : /usr/local/miniconda3
       envs directories : /usr/local/miniconda3/envs
                          /home/ubuntu/.conda/envs
          package cache : /usr/local/miniconda3/pkgs
                          /home/ubuntu/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/ubuntu/.condarc
           offline mode : False
             user-agent : conda/4.3.13 requests/2.12.4 CPython/3.6.0 Linux/4.13.0-1018-azure debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000



`$ /usr/local/miniconda3/bin/conda-env create --file Scripts/install/linux/conda-linux-cntk-py27-environment.yml --prefix /home/ubuntu/anaconda-envs/cntk-py27 -vv --debug`




    Traceback (most recent call last):
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 137, in fetch_repodata_remote_request
        resp.raise_for_status()
      File "/usr/local/miniconda3/lib/python3.6/site-packages/requests/models.py", line 893, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://conda.anaconda.org/conda-forge/linux-64/repodata.json

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 591, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 29, in install
        prefix=prefix)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 70, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 459, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 459, in <listcomp>
        for url, schan, pri in tasks]
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 105, in func
        res = f(*args, **kwargs)
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 436, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/usr/local/miniconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 299, in fetch_repodata_remote_request
        e.response)
    conda.exceptions.CondaHTTPError: HTTP 400 BAD REQUEST for url <https://conda.anaconda.org/conda-forge/linux-64/repodata.json>
    Elapsed: 00:00.377355
    CF-RAY: -

    An HTTP error occurred when trying to retrieve this URL.
    HTTP errors are often intermittent, and a simple retry will get you on your way.
    HTTPError('400 Client Error: Bad Request for url: https://conda.anaconda.org/conda-forge/linux-64/repodata.json',)

**Comment by kalefranz** [comment]
For the cert issue that just hit, we had a cert expiring today.  We had the new cert in place, but the expired cert was being prioritized over the new cert.  That issue has now been resolved.

**Comment by kalefranz** [comment]
I need more than the traceback.  Using `-vv` will give you headers for the request and the response.  Please provide the full details.

**Comment by thiagocrepaldi** [comment]
The output I sent previously was created by the -vv argument. Maybe that is a log bug on older versions of conda

**Comment by jeffkpayne** [comment]
I'm still seeing the cert issue, but maybe there's some caching in between the hops, etc.  Will try again in a bit...

**Comment by kalefranz** [comment]
Yeah, I am too in places.  Might be some caching issues somewhere...

**Comment by kalefranz** [comment]
> The output I sent previously was created by the -vv argument. Maybe that is a log bug on older versions of conda

What you posted was the *entire* output?

**Comment by thiagocrepaldi** [comment]
Yes, it was

I don't know if that helps, but if I run conda create not using the --file argument, it seems to work

**Comment by thiagocrepaldi** [comment]
There might be some clue here: https://raw.githubusercontent.com/Microsoft/CNTK/master/Scripts/install/linux/conda-linux-cntk-py27-environment.ym

**Comment by kalefranz** [comment]
![image](https://user-images.githubusercontent.com/1418419/41072095-53f925a0-69c1-11e8-9330-903fd134b3cf.png)

Just now for https://conda.anaconda.org/conda-forge/noarch/repodata.json

**Comment by kalefranz** [comment]
@thiagocrepaldi What if you make the contents of your file

```
name: cntk-py27
channels:
- defaults
- conda-forge
dependencies:
- enum34=1.1.6=py27_0
- h5py=2.6.0=np111py27_2
- imageio=2.2.0=py27_0
- jupyter=1.0.0=py27_3
- matplotlib=1.5.3=np111py27_0
- mock=2.0.0=py27_0
- numpy=1.11.2=py27_0
- pandas=0.19.1=np111py27_0
- pandas-datareader=0.2.1=py27_0
- pandoc=1.15.0.6
- pillow=3.4.2=py27_0
- pip=8.1.2=py27_0
- python=2.7.11=5
- pyyaml=3.12=py27_0
- scikit-image=0.12.3=np111py27_1
- scikit-learn=0.18.1=np111py27_0
- scipy=0.18.1=np111py27_0
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- six=1.10.0=py27_0
- wheel=0.29.0=py27_0
- pip:
  - gym[atari]==0.8.1
  - keras==2.0.6
  - pydot-ng==1.0.0
  - pygame==1.9.3
  - pytest==3.0.3
  - sphinx-rtd-theme==0.2.4
  - sphinx==1.5.4
  - nbsphinx==0.2.14
  - twine==1.8.1
  - protobuf==3.2.0
```

**Comment by kalefranz** [comment]
If that doesn't work, try `conda update conda`.  It'll update conda independently of the pytest you need.

**Comment by thiagocrepaldi** [comment]
Changing the yml didn't fix, but installing a brand new miniconda 3.6 from https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh worked.

**Comment by thiagocrepaldi** [comment]
But why the old version works if executed as root and doesn't work as regular user is still unknown.

**Comment by thiagocrepaldi** [comment]
Thanks for the help :)
