### ISSUE TITLE
ModuleNotFoundError: No module named '_socket'

### ISSUE THREAD

**Issue by fepegar** [conda/conda#7405]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I get a `ModuleNotFoundError: No module named '_socket'` error when trying to run `conda`.

### Steps to Reproduce

Just run `conda`:
```
C:\Users\fernando
λ conda
Traceback (most recent call last):
  File "C:\Users\fernando\Anaconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\fernando\Anaconda3\lib\site-packages\conda\cli\main.py", line 181, in main
    from ..exceptions import conda_exception_handler
  File "C:\Users\fernando\Anaconda3\lib\site-packages\conda\exceptions.py", line 16, in <module>
    from .common.url import maybe_unquote
  File "C:\Users\fernando\Anaconda3\lib\site-packages\conda\common\url.py", line 8, in <module>
    import socket
  File "C:\Users\fernando\Anaconda3\lib\socket.py", line 49, in <module>
    import _socket
ModuleNotFoundError: No module named '_socket'
```

Since `conda` itself doesn't work, I can't provide the environment information. I'm using `conda` installed by Anaconda 3 on Windows 10. It worked fine one hour ago. Stuff I have done since then:
1. Install Visual Studio 2015
2. `pip install nipype`, which needed VS for some compiling
3. Build and install [NiftyReg](http://cmictig.cs.ucl.ac.uk/wiki/index.php/NiftyReg_install)

**Comment by fepegar** [comment]
"Solved" by uninstalling Anaconda and installing Miniconda.

**Comment by Toshevska** [comment]
I tried all the miniconda 3 versions, and I seem to have the same problem with all of them. Which version did you install?
