### ISSUE TITLE
conda update fail

### ISSUE THREAD

**Issue by kmonsoor** [conda/conda#743]
initially, was having problem with beautifulsoup4. So, tried to update conda. failed for several time.

Environment:
----------------
Windows 8.1 64-bit
IPython : Python 2.7.6 | Anaconda 1.9.2 (64-bit)
conda : 3.5.0
net connectivity : ok  

Traceback:
--------------

```pytb
C:\Users\k>conda update conda
Fetching package metadata: ..An unexpected error has occurred, please consider s
ending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 184, in instal
l
    unknown=args.unknown)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 40, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 77, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 122, in fetch_index
    use_cache=use_cache, session=session)), reversed(channel_urls))
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 122, in <lambda>
    use_cache=use_cache, session=session)), reversed(channel_urls))
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 76, in fetch_repodat
a
    resp = session.get(url + 'repodata.json.bz2', headers=headers)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 468, in get
    return self.request('GET', url, **kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 456, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda\lib\site-packages\requests\sessions.py", line 596, in send
    r.content
  File "C:\Anaconda\lib\site-packages\requests\models.py", line 694, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes
()
  File "C:\Anaconda\lib\site-packages\requests\models.py", line 632, in generate

    raise ContentDecodingError(e)
requests.exceptions.ContentDecodingError: ('Received response with content-encod
ing: gzip, but failed to decode it.', error('Error -3 while decompressing: incor
rect header check',))
```

**Comment by csoja** [comment]
@asmeurer Can we close this issue?
