### ISSUE TITLE
ruamel_yaml 0.15.40 windows py27 error

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#7461]
```
Traceback (most recent call last):
  File "C:\projects\conda\tests\common\test_configuration.py", line 346, in test_list_merges
    raw_data = load_from_string_data('file5', 'file3')
  File "C:\projects\conda\tests\common\test_configuration.py", line 156, in load_from_string_data
    for f in seq)
  File "C:\Miniconda\lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "C:\Miniconda\lib\_abcoll.py", line 571, in update
    for key, value in other:
  File "C:\projects\conda\tests\common\test_configuration.py", line 155, in <genexpr>
    return odict((f, YamlRawParameter.make_raw_parameters(f, yaml_load(test_yaml_raw[f])))
  File "C:\projects\conda\conda\common\serialize.py", line 56, in yaml_load
    return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\main.py", line 637, in load
    loader = Loader(stream, version, preserve_quotes=preserve_quotes)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
    Reader.__init__(self, stream, loader=self)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\reader.py", line 81, in __init__
    self.stream = stream  # type: Any  # as .read is called
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\reader.py", line 113, in stream
    self.check_printable(val)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\reader.py", line 234, in check_printable
    non_printable_match = self._get_non_printable(data)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\reader.py", line 230, in _get_non_printable
    return cls._get_non_printable_regex(data)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\reader.py", line 219, in _get_non_printable_regex
    match = cls.NON_PRINTABLE.search(data)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\util.py", line 40, in __getattribute__
    return getattr(lazy_self(), name)
  File "C:\Miniconda\lib\site-packages\ruamel_yaml\util.py", line 31, in lazy_self
    return_value = func(*args, **kwargs)
  File "C:\Miniconda\lib\re.py", line 194, in compile
    return _compile(pattern, flags)
  File "C:\Miniconda\lib\re.py", line 251, in _compile
    raise error, v # invalid expression
error: bad character range
```

see, e.g. https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda/build/1.0.6452/job/bvlfuyof4d4htk2u#L677

I believe this is present in 0.15.40 but not present in 0.15.37 (the timing of when it showed up coincides with the 0.15.40 conda package release).

@mbargull Was this by chance something you might have influenced?

**Comment by mbargull** [comment]
F.... yes, my bad. Thankfully got my hands on a Windows machine so could debug. Will fix it upstream

**Comment by mbargull** [comment]
@kalefranz, do you have any possibility to try out the change from https://bitbucket.org/ruamel/yaml/pull-requests/31/fix-issue-204/diff?

**Comment by mbargull** [comment]
Fixed with `ruamel.yaml 0.15.42` and https://github.com/AnacondaRecipes/ruamel_yaml-feedstock/pull/2.

**Comment by mbargull** [comment]
Apparently `0.15.42` only fixes CPython 2 builds on Linux/macOS...
The changes from https://bitbucket.org/ruamel/yaml/pull-requests/33/fix-204-on-windows-py2/diff will also fix it on Windows.
