### ISSUE TITLE
Error with conda -env update

### ISSUE THREAD

**Issue by acwooding** [conda/conda#7475]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

### Steps to Reproduce

```
`$ //anaconda/bin/conda-env update --name dimension_reduction -f environment.yml`

    Traceback (most recent call last):
      File "//anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "//anaconda/lib/python2.7/site-packages/conda_env/cli/main_update.py", line 106, in execute
        installer.install(prefix, specs, args, env, prune=args.prune)
      File "//anaconda/lib/python2.7/site-packages/conda_env/installers/pip.py", line 8, in install
        pip_cmd = pip_args(prefix) + ['install', ] + specs
    TypeError: can only concatenate list (not "NoneType") to list
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : osx-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.14.1
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : //anaconda  (writable)
    default environment : //anaconda/envs/dimension_reduction
       envs directories : //anaconda/envs
                          ~/.conda/envs
          package cache : //anaconda/pkgs
                          ~/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.12.4 CPython/2.7.13 Darwin/17.4.0 OSX/10.13.3    
                UID:GID : 501:20
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
_nb_ext_conf              0.4.0                    py36_1    defaults
alabaster                 0.7.11                   py36_2    conda-forge
anaconda-client           1.6.14                     py_0    conda-forge
appnope                   0.1.0                    py36_0    defaults
asn1crypto                0.24.0                   py36_0    conda-forge
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
awscli                    1.15.48                  py36_0    conda-forge
babel                     2.6.0                    py36_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backcall                  0.1.0                     <pip>
blas                      1.1                    openblas    conda-forge
bleach                    2.1.3                      py_0    conda-forge
bleach                    2.1.3                     <pip>
botocore                  1.10.48                    py_0    conda-forge
bzip2                     1.0.6                         3    defaults
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
clyent                    1.2.2                    py36_0    conda-forge
colorama                  0.3.9                    py36_0    conda-forge
coverage                  4.5.1                    py36_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    defaults
decorator                 4.3.0                      py_0    conda-forge
decorator                 4.3.0                     <pip>
docutils                  0.14                     py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
ffmpeg                    3.2.4                         3    conda-forge
flake8                    3.5.0                    py36_0    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
gitdb2                    2.0.3                      py_0    conda-forge
gitpython                 2.1.10                     py_0    conda-forge
glib                      2.55.0                        0    conda-forge
graphite2                 1.3.11               h7d4d677_0    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  1.0.1                     <pip>
html5lib                  1.0.1                      py_0    conda-forge
hypothesis                3.61.0           py36h24bf2e0_0    conda-forge
icu                       58.1                          0    conda-forge
idna                      2.7                      py36_0    conda-forge
imageio                   2.3.0                    py36_0    conda-forge
imagesize                 1.0.0                    py36_0    conda-forge
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.3.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                7.2.1                    py36_1    conda-forge
jasper                    1.900.1                       4    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter-core              4.4.0                     <pip>
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    defaults
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.32.1                    <pip>
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.0                         1    defaults
libiconv                  1.15                 h470a237_1    conda-forge
libpng                    1.6.34                        0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libtiff                   4.0.9                         0    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxml2                   2.9.8                         0    conda-forge
markupsafe                1.0                      py36_0    defaults
matplotlib                2.2.2                    py36_1    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mkl                       2017.0.3                      0    defaults
more-itertools            4.2.0                      py_0    conda-forge
nb_anacondacloud          1.4.0                    py36_0    conda-forge
nb_conda                  2.2.1                    py36_0    conda-forge
nb_conda_kernels          2.1.0                    py36_0    defaults
nbconvert                 5.3.1                     <pip>
nbconvert                 5.3.1                      py_1    conda-forge
nbdime                    1.0.1                    py36_0    conda-forge
nbformat                  4.4.0                    py36_0    defaults
nbpresent                 3.0.2            py36hef4c988_1    defaults
nbval                     0.9.1                      py_0    conda-forge
ncurses                   5.9                          10    conda-forge
notebook                  5.5.0                    py36_0    conda-forge
numpy                     1.13.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
olefile                   0.45.1                   py36_0    conda-forge
openblas                  0.2.20                        8    conda-forge
opencv                    3.4.1           py36_blas_openblas_200  [blas_openblas]  conda-forge
openssl                   1.0.2l                        0    defaults
packaging                 17.1                       py_0    conda-forge
pandas                    0.20.3                   py36_0    defaults
pandoc                    2.2                  hde52d81_0    conda-forge
pandocfilters             1.4.2                    py36_0    defaults
parso                     0.2.0                     <pip>
parso                     0.2.0                      py_0    conda-forge
path.py                   11.0.1                     py_0    conda-forge
patsy                     0.4.1                    py36_0    defaults
pcre                      8.41                          1    conda-forge
pexpect                   4.5.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    defaults
pillow                    5.1.0                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
pluggy                    0.6.0                      py_0    conda-forge
prompt_toolkit            1.0.15                   py36_0    defaults
ptyprocess                0.5.2                    py36_0    defaults
py                        1.5.4                      py_0    conda-forge
pyasn1                    0.4.3                      py_0    conda-forge
pycodestyle               2.3.1                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pyflakes                  1.6.0                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    defaults
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    defaults
pyqt                      5.6.0                    py36_2    defaults
pysocks                   1.6.8                    py36_1    conda-forge
pytest                    3.6.2                    py36_0    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.2                      py_0    conda-forge
python-dateutil           2.7.3                     <pip>
python-dotenv             0.8.2                    py36_0    conda-forge
pytz                      2017.2                   py36_0    defaults
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     17.0.0                   py36_4    conda-forge
qt                        5.6.2                h9e3eb04_4    conda-forge
qtconsole                 4.3.1                    py36_0    defaults
readline                  7.0                           0    conda-forge
requests                  2.19.1                   py36_0    conda-forge
rsa                       3.4.2                    py36_0    conda-forge
s3transfer                0.1.13                   py36_0    conda-forge
scikit-learn              0.19.1          py36_blas_openblas_201  [blas_openblas]  conda-forge
scipy                     1.0.0           py36_blas_openblas_201  [blas_openblas]  conda-forge
seaborn                   0.8.1                    py36_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
Send2Trash                1.5.0                     <pip>
setuptools                36.4.0                   py36_1    defaults
simplegeneric             0.8.1                    py36_1    defaults
sip                       4.18                     py36_0    defaults
six                       1.11.0                   py36_1    conda-forge
smmap2                    2.0.3                    py36_0    conda-forge
snowballstemmer           1.2.1                    py36_0    conda-forge
sphinx                    1.7.5                    py36_0    conda-forge
sphinxcontrib-websupport  1.1.0                    py36_0    conda-forge
sqlite                    3.20.1                        0    conda-forge
statsmodels               0.8.0               np113py36_0    defaults
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    defaults
tk                        8.6.6                         0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    defaults
urllib3                   1.23                     py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    defaults
webencodings              0.5.1                    py36_0    conda-forge
wheel                     0.29.0                   py36_0    defaults
widgetsnbextension        3.2.1                    py36_0    conda-forge
x264                      20131218                      0    conda-forge
xz                        5.2.3                         0    defaults
yaml                      0.1.7                         0    conda-forge
zeromq                    4.2.5                         1    conda-forge
zlib                      1.2.11                        0    defaults
```
</p></details>

**Comment by acwooding** [comment]
This seems to be caused by having an empty 
```
  - pip:
```
at the end of `requirements.yml` (happened after I removed the last pip dependency)
