### ISSUE TITLE
I don't know what is wrong. But, conda is completely broken.

### ISSUE THREAD

**Issue by whereistejas** [conda/conda#7490]
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 336, in make_raw_parameters_from_file
        return cls.make_raw_parameters(filepath, ruamel_yaml) or EMPTY_MAP
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 325, in make_raw_parameters
        for key in from_map)
      File "/home/tsanap/anaconda3/lib/python3.6/site-packages/conda/common/configuration.py", line 325, in <genexpr>
        for key in from_map)
    TypeError: string indices must be integers

`$ /home/tsanap/anaconda3/bin/conda update`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/tsanap/anaconda3
               MODULEPATH=/etc/scl/modulefiles:/etc/scl/modulefiles:/usr/share/Modules/modulefil
                          es:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/home/tsanap/anaconda3/bin:/home/tsanap/anaconda3/bin:/usr/share/Modul
                          es/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/tsanap/
                          .i3ass:/home/tsanap/repos/squash:/home/tsanap/scripts:/home/tsanap/.lo
                          cal/bin:/home/tsanap/bin:/home/tsanap/.i3ass:/home/tsanap/repos/squash
                          :/home/tsanap/scripts
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : None
       user config file : /home/tsanap/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/tsanap/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/tsanap/anaconda3/pkgs
                          /home/tsanap/.conda/pkgs
       envs directories : /home/tsanap/anaconda3/envs
                          /home/tsanap/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Linux/4.17.3-200.fc28.x86_64 fedora/28 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by kalefranz** [comment]
What is the output of

    cat /home/tsanap/.condarc

**Comment by sanaptejas** [comment]
`cat: /home/tsanap/.condarc: No such file or directory`

**Comment by kalefranz** [comment]
You have a bad configuration file that conda is seeing.  You've not included the output of `conda config --show-sources`. It seems you have configured a parameter that should be a list, but as a string.
