### ISSUE TITLE
AttributeError: '_NamespacePath' object has no attribute 'sort'

### ISSUE THREAD

**Issue by melissakly** [conda/conda#7521]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I'm trying to create a python 3.6 conda environment with the full set of packages specified in environment.yml (a package made for a class https://raw.githubusercontent.com/DS-100/sp18/gh-pages/environment.yml). Conda did successfully create a python 3.6 environment and I am able to use the environment and work on assignments but I'm worried about the error I received on my terminal.

### Steps to Reproduce

```
curl https://repo.continuum.io/miniconda/Miniconda3-4.3.31-MacOSX-x86_64.sh  > miniconda.sh
```
```
bash miniconda.sh
```
```
curl https://raw.githubusercontent.com/DS-100/sp18/gh-pages/environment.yml > environment.yml
```
```
conda env create -f environment.yml
```

## Expected Behavior

The environment should have successfully installed. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
platform : osx-64
          conda version : 4.3.31
       conda is private : False
      conda-env version : 4.3.31
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /Users/melissaly/miniconda3  (writable)
    default environment : /Users/melissaly/miniconda3
       envs directories : /Users/melissaly/miniconda3/envs
                          /Users/melissaly/.conda/envs
          package cache : /Users/melissaly/miniconda3/pkgs
                          /Users/melissaly/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/osx-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/osx-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/osx-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/osx-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : /Users/melissaly/.netrc
           offline mode : False
             user-agent : conda/4.3.31 requests/2.18.4 CPython/3.6.3 Darwin/15.6.0 OSX/10.11.6    
                UID:GID : 501:20
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
A blank line? 
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/melissaly/miniconda3:
#
asn1crypto                0.23.0           py36h782d450_0    defaults
ca-certificates           2017.08.26           ha1e5d58_0    defaults
certifi                   2017.11.5        py36ha569be9_0    defaults
cffi                      1.11.2           py36hd3e6348_0    defaults
chardet                   3.0.4            py36h96c241c_1    defaults
conda                     4.3.31                   py36_0    defaults
conda-env                 2.6.0                h36134e3_0    defaults
cryptography              2.1.4            py36h842514c_0    defaults
idna                      2.6              py36h8628d0a_1    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1                  hb4e282d_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.0                  hd04f020_2    defaults
openssl                   1.0.2n               hdbc3d79_0    defaults
pip                       9.0.1            py36h1555ced_4    defaults
pycosat                   0.6.3            py36hee92d8f_0    defaults
pycparser                 2.18             py36h724b2fc_1    defaults
pyopenssl                 17.5.0           py36h51e4350_0    defaults
pysocks                   1.6.7            py36hfa33cec_1    defaults
python                    3.6.3                h47c878a_7    defaults
python.app                2                py36h54569d5_7    defaults
readline                  7.0                  hc1231fa_4    defaults
requests                  2.18.4           py36h4516966_1    defaults
ruamel_yaml               0.11.14          py36h9d7ade0_2    defaults
setuptools                36.5.0           py36h2134326_0    defaults
six                       1.11.0           py36h0e22d5e_1    defaults
sqlite                    3.20.1               h7e4c145_2    defaults
tk                        8.6.7                h35a86e2_3    defaults
urllib3                   1.22             py36h68b9469_0    defaults
wheel                     0.30.0           py36h5eb2c71_1    defaults
xz                        5.2.3                h0278029_2    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

Thanks for all the help! Here's the traceback I get if that helps.
<img width="1137" alt="screen shot 2018-07-10 at 12 53 37 am" src="https://user-images.githubusercontent.com/21248091/42496835-285f420a-83dc-11e8-984f-3bb8fa655946.png">

**Comment by melissakly** [comment]
Thanks! Should I just run `curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh > miniconda.sh` and it will update the package or do I need to uninstall everything and reinstall?

**Comment by melissakly** [comment]
Hello, I still got an `AttributeError: '_NamespacePath' object has no attribute 'sort'`. I uninstalled miniconda and ran `curl https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh`and wasn't able to send in the error report but here is its output:

'>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/melissaly/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/Users/melissaly/miniconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/melissaly/miniconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/Users/melissaly/miniconda3/lib/python3.6/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
        args, pip_version = pip_args(prefix)
      File "/Users/melissaly/miniconda3/lib/python3.6/site-packages/conda_env/pip_util.py", line 33, in pip_args
        pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
      File "/Users/melissaly/miniconda3/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/Users/melissaly/miniconda3/lib/python3.6/subprocess.py", line 418, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['/Users/melissaly/miniconda3/envs/data100/bin/python', '/Users/melissaly/miniconda3/envs/data100/bin/pip', '-V']' returned non-zero exit status 1.

`$ /Users/melissaly/miniconda3/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/Users/melissaly/miniconda3
                 GEM_PATH=/Users/melissaly/.rvm/gems/ruby-2.3.0:/Users/melissaly/.rvm/gems/ruby-
                          2.3.0@global
                     PATH=/Users/melissaly/miniconda3/bin:/Users/melissaly/miniconda3/bin:/Users
                          /melissaly/anaconda3/bin:/Library/Frameworks/Python.framework/Versions
                          /3.5/bin:/Users/melissaly/.rvm/gems/ruby-2.3.0/bin:/Users/melissaly/.r
                          vm/gems/ruby-2.3.0@global/bin:/Users/melissaly/.rvm/rubies/ruby-2.3.0/
                          bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Frameworks/M
                          ono.framework/Versions/Current/Commands:/Users/melissaly/.rvm/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
             rvm_bin_path=/Users/melissaly/.rvm/bin
                 rvm_path=/Users/melissaly/.rvm

     active environment : None
       user config file : /Users/melissaly/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /Users/melissaly/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/melissaly/miniconda3/pkgs
                          /Users/melissaly/.conda/pkgs
       envs directories : /Users/melissaly/miniconda3/envs
                          /Users/melissaly/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : /Users/melissaly/.netrc
           offline mode : False
'
<img width="809" alt="screen shot 2018-07-14 at 1 06 32 pm" src="https://user-images.githubusercontent.com/21248091/42728072-e863c912-8766-11e8-943f-528323e462b9.png">

**Comment by melissakly** [comment]
Here's the traceback I get when I try to pip install in Jupyter Notebook
<img width="1014" alt="screen shot 2018-07-14 at 1 13 28 pm" src="https://user-images.githubusercontent.com/21248091/42728113-cbb5019a-8767-11e8-8089-a757ff935f22.png">
