### ISSUE TITLE
Error while trying to parse a version number cascaded

### ISSUE THREAD

**Issue by CJ-Wright** [conda/conda#7532]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior
It seems that one of the conda-forge recipes upstream has a very weird version number. I expect conda to fall over trying to parse the version (I have a `except Exception as e` clause to prevent us from falling over in these situations). What I didn't expect was `__str__` in the top level init to fall over.

### Steps to Reproduce
Wait an hour and watch the bot fall over again? :smile: (I'll try to do a better job figuring out what the upstream is)
```
class: CondaValueError
message:
Malformed version string 'CMIP6_CVs.6.2.8.23%2FDREQ.01.00.24%2FCMOR.3.3.3': invalid character(s).
kwargs:
{}

class: CondaValueError
message:
Malformed version string 'CMIP6_CVs.6.2.8.23%2FDREQ.01.00.24%2FCMOR.3.3.3': invalid character(s).
kwargs:
{}

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 195, in get_latest_version
    ver = source.get_version(url)
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 67, in get_version
    return max(vers, key=lambda x: VersionOrder(x.replace("-", ".")))
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 67, in <lambda>
    return max(vers, key=lambda x: VersionOrder(x.replace("-", ".")))
  File "/opt/conda/lib/python3.6/site-packages/conda/models/version.py", line 163, in __new__
    raise CondaValueError(message + "invalid character(s).")
conda.exceptions.CondaValueError: <unprintable CondaValueError object>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 218, in update_upstream_versions
    attrs['new_version'] = f.result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
conda.exceptions.CondaValueErrorclass: CondaValueError
message:
Malformed version string 'CMIP6_CVs.6.2.8.23%2FDREQ.01.00.24%2FCMOR.3.3.3': invalid character(s).
kwargs:
{}

: <exception str() failed>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/conda-forge-tick", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/root/repo/cf-scripts/scripts/conda-forge-tick", line 3, in <module>
    main()
  File "/root/repo/cf-scripts/conda_forge_tick/cli.xsh", line 21, in main
    int_script_dict[script]()
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 252, in main
    update_upstream_versions(gx)
  File "/root/repo/cf-scripts/conda_forge_tick/update_upstream_versions.py", line 221, in update_upstream_versions
    "Error getting uptream version of {}: {}".format(node, e))
  File "/opt/conda/lib/python3.6/site-packages/conda/__init__.py", line 48, in __str__
    return text_type(self.message % self._kwargs)
TypeError: must be real number, not dict

```

## Expected Behavior
Ideally conda wouldn't fall over twice when confronted with an odd upstream version.

## Environment Information
I'm working on these (I'm waiting on circle to try this again).
<details open><summary><code>`conda info`</code></summary><p>

```
    active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.5.8
    conda-build version : 3.10.9
         python version : 3.6.5.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.5 Linux/4.4.0-130-generic debian/9 glibc/2.24
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /root/.condarc <==
channels:
  - conda-forge
  - defaults
always_yes: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                     py_1    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                      py_1    conda-forge
conda                     4.5.8                    py36_0    conda-forge
conda-build               3.10.9                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-forge-pinning       2018.07.01                    0    conda-forge
conda-smithy              3.1.6                      py_0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
decorator                 4.3.0                      py_0    conda-forge
doctr                     1.7.3                    py36_0    conda-forge
feedparser                5.2.1                    py36_0    defaults
filelock                  3.0.4                    py36_0    conda-forge
gitdb2                    2.0.3                      py_0    conda-forge
github3.py                1.1.0                      py_1    conda-forge
gitpython                 2.1.10                     py_0    conda-forge
glob2                     0.6                        py_0    conda-forge
idna                      2.7                        py_1    conda-forge
jinja2                    2.10                       py_1    conda-forge
lazyasd                   0.1.4                      py_1    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
markupsafe                1.0                      py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
ndg-httpsclient           0.4.4                    py36_0    conda-forge
networkx                  2.1                        py_1    conda-forge
openssl                   1.0.2o                        0    conda-forge
patchelf                  0.9                           2    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pkginfo                   1.4.2                      py_1    conda-forge
ply                       3.11                       py_1    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
pyasn1                    0.4.3                      py_0    conda-forge
pycosat                   0.6.3                    py36_0    conda-forge
pycparser                 2.18                       py_1    conda-forge
pycrypto                  2.6.1                    py36_1    conda-forge
pygithub                  1.39                     py36_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyjwt                     1.6.4                      py_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
python                    3.6.5                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.19.1                   py36_1    conda-forge
rever                     0.2.8                    py36_0    conda-forge
ruamel.yaml               0.15.42                  py36_0    conda-forge
ruamel_yaml               0.15.42          py36h470a237_0    conda-forge
setproctitle              1.1.10           py36h470a237_1    conda-forge
setuptools                40.0.0                   py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
smmap2                    2.0.3                    py36_0    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.7                         0    conda-forge
uritemplate.py            3.0.2                      py_1    conda-forge
urllib3                   1.23                     py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
wheel                     0.31.1                   py36_0    conda-forge
xonsh                     0.6.9                    py36_0    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</p></details>

relevent circle jobs (https://circleci.com/gh/regro/circle_worker/tree/master).
Please note that I'm going to wrap the exception so the autotick bot can keep going.

**Comment by justcalamari** [comment]
Upstream is https://github.com/PCMDI/cmor. [This](https://github.com/PCMDI/cmor/releases/tag/CMIP6_CVs-6.2.8.23%2FDREQ-01.00.24%2FCMOR-3.3.3) is the release.
