### ISSUE TITLE
PermissionError, cannot update and install new packages 

### ISSUE THREAD

**Issue by wwang2** [conda/conda#7565]
I tried to install a package on  all the environments from an administrator's account, but always get the following PermissionError: 

`Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : /opt/anaconda3  (writable)
    default environment : /opt/anaconda3/envs/test
       envs directories : /opt/anaconda3/envs
                          /home/softmatter/.conda/envs
          package cache : /opt/anaconda3/pkgs
                          /home/softmatter/.conda/pkgs
           channel URLs : https://conda.anaconda.org/mingfeima/linux-64
                          https://conda.anaconda.org/mingfeima/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/softmatter/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.6.2 Linux/4.13.0-43-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000`

'`$ /opt/anaconda3/envs/test/bin/conda install -c mingfeima mkldnn`

    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 231, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 101, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 120, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 75, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 485, in <listcomp>
        for url, schan, pri in tasks]
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 115, in func
        res = f(*args, **kwargs)
      File "/opt/anaconda3/lib/python3.6/site-packages/conda/core/repodata.py", line 473, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: '/opt/anaconda3/pkgs/cache/6846611e.json''

Some hints would be much appreiciated, Thanks!

**Comment by wwang2** [comment]
similar issue as https://github.com/conda/conda/issues/5833
