### ISSUE TITLE
In Windows 10, cannot use environment created in folder containing non-English character

### ISSUE THREAD

**Issue by RegisC** [conda/conda#7577]
**I'm submitting a...**
  - [x] bug report

## Current Behavior

Under Windows 10, I am unable to use an environment created under my home directory, the path of which contains an e-acute character (**"&eacute;"**, ASCII code 233). That character is legal in Windows and supported by other applications (including Python). 

The environment gets created correctly, as far as I can tell, but when I attempt to use it I get an error message suggesting that conda is unable to handle the e-acute character: "EnvironmentLocationNotFound: Not a conda environment: C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip". Notice that the e-acute is mangled and displayed as 2 characters : "Ã©".

### Steps to Reproduce

```
(base) C:\Users\Régis>conda create --name env_pip pip
Solving environment: done

## Package Plan ##

  environment location: C:\Users\Régis\AppData\Local\conda\conda\envs\env_pip

  added / updated specs:
    - pip

The following NEW packages will be INSTALLED:

    certifi:        2018.4.16-py37_0
    pip:            10.0.1-py37_0
    python:         3.7.0-hea74fb7_0
    setuptools:     39.2.0-py37_0
    vc:             14.1-h0510ff6_3
    vs2015_runtime: 15.5.2-3
    wheel:          0.31.1-py37_0
    wincertstore:   0.2-py37_0

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate env_pip
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\Régis>conda activate env_pip

(env_pip) C:\Users\Régis>conda list

EnvironmentLocationNotFound: Not a conda environment: C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
```

## Expected Behavior

```conda list``` should not fail.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
    active env location : C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
            shell level : 2
       user config file : C:\Users\Régis\.condarc
 populated config files : C:\Users\Régis\.condarc
          conda version : 4.5.8
    conda-build version : 3.11.0
         python version : 3.6.6.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Régis\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Régis\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\Régis\.conda\envs
               platform : win-64
             user-agent : conda/4.5.8 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Régis\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
EnvironmentLocationNotFound: Not a conda environment: C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
```
</p></details>

**Comment by kalefranz** [comment]
Instead of

```
(env_pip) C:\Users\Régis>conda list

EnvironmentLocationNotFound: Not a conda environment: C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
```

Can you provide the output of `conda list -vv`?

**Comment by kalefranz** [comment]
Also, with your `env_pip` environment active, the output of `set` (i.e. the environment variables that are currently set in your shell).

**Comment by RegisC** [comment]
There you go - sorry for the late reply:
```
(env_pip) C:\Users\Régis>conda list -vv
DEBUG conda.gateways.logging:set_verbosity(148): verbosity set to 2
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 125, in execute
    raise EnvironmentLocationNotFound(prefix)
conda.exceptions.EnvironmentLocationNotFound: Not a conda environment: C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
```
```
(env_pip) C:\Users\Régis>set
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\Régis\AppData\Roaming
asl.log=Destination=file
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=GODFATHER2
ComSpec=C:\WINDOWS\system32\cmd.exe
CONDA_DEFAULT_ENV=env_pip
CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe
CONDA_PREFIX=C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip
CONDA_PREFIX_1=C:\ProgramData\Anaconda3
CONDA_PROMPT_MODIFIER=(env_pip)
CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
CONDA_SHLVL=2
DriverData=C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\Régis
LOCALAPPDATA=C:\Users\Régis\AppData\Local
LOGONSERVER=\\GODFATHER2
NUMBER_OF_PROCESSORS=8
OneDrive=D:\OneDrive
OS=Windows_NT
Path=C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip;C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip\Library\mingw-w64\bin;C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip\Library\usr\bin;C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip\Library\bin;C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip\Scripts;C:\Users\RÃ©gis\AppData\Local\conda\conda\envs\env_pip\bin;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Library\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files\IDM Computer Solutions\UltraCompare;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\Boxcryptor\bin\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Users\Râ”œÂ®gis\AppData\Local\Microsoft\WindowsApps;C:\Users\Râ”œÂ®gis\AppData\Local\atom\bin
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=3c03
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=(env_pip) $P$G
PSModulePath=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
PUBLIC=C:\Users\Public
PYTHONIOENCODING=1252
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\RGIS~1\AppData\Local\Temp
TMP=C:\Users\RGIS~1\AppData\Local\Temp
USERDOMAIN=GODFATHER2
USERDOMAIN_ROAMINGPROFILE=GODFATHER2
USERNAME=Régis
USERPROFILE=C:\Users\Régis
windir=C:\WINDOWS
```

```

**Comment by mingwandroid** [comment]
This is fixed.
