### ISSUE TITLE
Error While cloning the environment

### ISSUE THREAD

**Issue by sdeshpande** [conda/conda#7587]
Hi Guys,

I am running into an issue while executing conda clone command. Can you please assist. See below for the output when I execute that command. 

C:\miniconda\Scripts>conda create --name py35 --clone py3test --offline
Source:      C:\miniconda\envs\py3test
Destination: C:\miniconda\envs\py35
Packages: 9
Files: 139
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.4.5.final.0
       requests version : 2.14.2
       root environment : C:\miniconda  (writable)
    default environment : C:\miniconda
       envs directories : C:\miniconda\envs
                          C:\Users\username\AppData\Local\conda\conda\envs
                          C:\Users\username\.conda\envs
          package cache : C:\miniconda\pkgs
                          C:\Users\username\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/win-64  (offline)
                          https://repo.continuum.io/pkgs/main/noarch  (offline)
                          https://repo.continuum.io/pkgs/free/win-64  (offline)
                          https://repo.continuum.io/pkgs/free/noarch  (offline)
                          https://repo.continuum.io/pkgs/r/win-64  (offline)
                          https://repo.continuum.io/pkgs/r/noarch  (offline)
                          https://repo.continuum.io/pkgs/pro/win-64  (offline)
                          https://repo.continuum.io/pkgs/pro/noarch  (offline)
                          https://repo.continuum.io/pkgs/msys2/win-64  (offline)
                          https://repo.continuum.io/pkgs/msys2/noarch  (offline)
            config file : C:\Users\username\.condarc
             netrc file : None
           offline mode : True
             user-agent : conda/4.3.30 requests/2.14.2 CPython/3.4.5 Windows/10 Windows/10.0.17134
          administrator : False

`$ C:\miniconda\Scripts\conda create --name py35 --clone py3test --offline`

    Traceback (most recent call last):
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\cli\main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\cli\install.py", line 221, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\cli\install.py", line 74, in clone
        index_args=index_args)
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\misc.py", line 312, in clone_env
        force_extract=False, index_args=index_args)
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\misc.py", line 96, in explicit
        _supplement_index_with_cache(index, ())
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\core\index.py", line 65, in _supplement_index_with_cache
        index_json_record = read_index_json(pkg_dir)
      File "C:\miniconda\lib\site-packages\conda-4.3.30-py3.4.egg\conda\gateways\disk\read.py", line 101, in read_index_json
        record = IndexRecord(**json.load(fi))  # TODO: change to LinkedPackageData
      File "C:\miniconda\lib\json\__init__.py", line 268, in load
        parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
      File "C:\miniconda\lib\json\__init__.py", line 318, in loads
        return _default_decoder.decode(s)
      File "C:\miniconda\lib\json\decoder.py", line 343, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "C:\miniconda\lib\json\decoder.py", line 361, in raw_decode
        raise ValueError(errmsg("Expecting value", s, err.value)) from None
    ValueError: Expecting value: line 1 column 1 (char 0)

Regards

**Comment by kalefranz** [comment]
You have a corrupt package in your package cache.  Try `conda clean --packages`.  If that doesn't work, you might have to just remove your package cache.  Also, `conda update conda`.

**Comment by sdeshpande** [comment]
This is it. Thank you guys.
