### ISSUE TITLE
Package install

### ISSUE THREAD

**Issue by tinomwadeyi** [conda/conda#7610]
Fetching package metadata ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\tmwadeyi\AppData\Local\conda\conda\envs
                          C:\Users\tmwadeyi\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\tmwadeyi\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-32
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-32
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\tmwadeyi\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install -p C:/ProgramData/Anaconda3 nltk -y`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 390, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 290, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 194, in proxy_manager_for
        **proxy_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\poolmanager.py", line 363, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\poolmanager.py", line 308, in __init__
        proxy = parse_url(proxy_url)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\url.py", line 195, in parse_url
        raise LocationParseError(url)
    requests.packages.urllib3.exceptions.LocationParseError: Failed to parse: <proxy_server>:port
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 222, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 92, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 111, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 463, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 463, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 442, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 159, in fetch_repodata_remote_request
        raise CondaRuntimeError("Invalid index file: {0}: {1}".format(join_url(url, filename), e))
    conda.exceptions.CondaRuntimeError: Runtime error: Invalid index file: https://conda.anaconda.org/anaconda-fusion/win-32/repodata.json: Failed to parse: <proxy_server>:port

**Comment by kalefranz** [comment]
`Failed to parse: <proxy_server>:port`

You have a proxy configuration problem somewhere.  It could be in a condarc file.  It could be in a netrc file.  It could be in an environment variable.  It could be in your registry.  There's no real way to tell from the conda side.  You're running into requests behavior here.  Definitely recommend updating conda once you get the proxy issue resolved though.
