### ISSUE TITLE
Runtime error: HTTPError: 404 Client Error

### ISSUE THREAD

**Issue by pdeperio** [conda/conda#7615]
Trying to clone an existing environment like this:
```
conda create --name pax_v6.8.0.1 --clone pax_v6.8.0
```
<details open><summary>results in the following error:</summary><p>

```
    Traceback (most recent call last):
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 395, in download
        resp.raise_for_status()
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/requests/models.py", line 909, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/pyzmq-16.0.2-py34_0.tar.bz2
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/exceptions.py", line 485, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/main.py", line 158, in _main
        exit_code = args.func(args, p)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 228, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 90, in clone
        index_args=index_args)
      File "/project/lgrandi/anaconda3/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/common.py", line 573, in json_progress_bars
        yield
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/cli/install.py", line 90, in clone
        index_args=index_args)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/misc.py", line 392, in clone_env
        force_extract=False, index_args=index_args)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/misc.py", line 192, in explicit
        execute_actions(actions, index=index, verbose=verbose)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 353, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "/project/lgrandi/anaconda3/lib/python3.5/site-packages/conda/fetch.py", line 399, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: HTTPError: 404 Client Error: NOT FOUND for url: https://conda.anaconda.org/t/<TOKEN>/conda-forge/linux-64/pyzmq-16.0.2-py34_0.tar.bz2: https://conda.anaconda.org/conda-forge/linux-64/pyzmq-16.0.2-py34_0.tar.bz2
```
</p></details>

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.2.16
       conda is private : False
      conda-env version : 4.2.16
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.13.0
       root environment : /project/lgrandi/anaconda3  (writable)
    default environment : /project/lgrandi/anaconda3
       envs directories : /project/lgrandi/anaconda3/envs
          package cache : /project/lgrandi/anaconda3/pkgs
           channel URLs : http://conda.anaconda.org/NLeSC/linux-64
                          http://conda.anaconda.org/NLeSC/noarch
                          http://conda.anaconda.org/XENON1T/linux-64
                          http://conda.anaconda.org/XENON1T/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
            config file : /home/tunnell/.condarc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
channels:
  - http://conda.anaconda.org/NLeSC
  - http://conda.anaconda.org/XENON1T
  - defaults
  - conda-forge
  - anaconda
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /project/lgrandi/anaconda3:
#
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.3.0                    py35_0    defaults
alabaster                 0.7.9                    py35_0    defaults
anaconda                  4.2.0               np111py35_0    defaults
anaconda-clean            1.0.0                    py35_0    defaults
anaconda-client           1.5.1                    py35_0    defaults
anaconda-navigator        1.3.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astor                     0.6.2                     <pip>
astroid                   1.4.7                    py35_0    defaults
astropy                   1.2.1               np111py35_0    defaults
auditwheel                1.9.0                     <pip>
babel                     2.3.4                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.5.1                    py35_0    defaults
bitarray                  0.8.1                    py35_0    defaults
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.2                   py35_0    defaults
boto                      2.42.0                   py35_0    defaults
bottleneck                1.1.0               np111py35_0    defaults
bumpversion               0.5.3                     <pip>
cairo                     1.14.6                        4    conda-forge
cax                       4.11.2                    <pip>
cax                       5.0.4                     <pip>
cax                       5.0.12                    <pip>
cffi                      1.7.0                    py35_0    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
conda                     4.2.16                   py35_0    anaconda
conda-build               2.0.2                    py35_0    defaults
conda-env                 2.6.0                         0    conda-forge
configobj                 5.0.6                    py35_0    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.5                      py35_0    defaults
curl                      7.49.0                        1    defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24.1                   py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.11.0                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
dbus                      1.10.10                       0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py35_1    defaults
filelock                  2.0.6                    py35_0    defaults
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
future                    0.16.0                    <pip>
get_terminal_size         1.0.0                    py35_0    defaults
gettext                   0.19.7                        1    conda-forge
gevent                    1.1.2                    py35_0    defaults
gitdb2                    2.0.3                     <pip>
GitPython                 2.1.8                     <pip>
glib                      2.51.4                        0    conda-forge
greenlet                  0.4.10                   py35_0    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.6.0               np111py35_2    defaults
harfbuzz                  0.9.39                        1    defaults
hax                       2.1.0                     <pip>
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py35_1    defaults
icu                       58.1                          1    conda-forge
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
iminuit                   1.2                       <pip>
ipykernel                 4.5.0                    py35_0    defaults
ipython                   5.1.0                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                5.2.2                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.2                      py35_1    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
jpeg                      9b                            0    conda-forge
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter_client            4.4.0                    py35_0    defaults
jupyter_console           5.0.0                    py35_0    defaults
jupyter_core              4.2.0                    py35_0    defaults
lazy-object-proxy         1.2.1                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libffi                    3.2.1                         0    defaults
libgcc                    4.8.5                         2    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          4    conda-forge
libpng                    1.6.28                        0    conda-forge
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         7    conda-forge
libxcb                    1.12                          0    defaults
libxml2                   2.9.2                         0    defaults
libxslt                   1.1.28                        0    defaults
llvmlite                  0.13.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.4                    py35_0    defaults
markupsafe                0.23                     py35_2    defaults
matplotlib                2.0.2                    py35_2    conda-forge
mccabe                    0.6.1                     <pip>
mistune                   0.7.3                    py35_0    defaults
mkl                       11.3.3                        0    defaults
mkl-service               1.1.2                    py35_2    defaults
mock                      2.0.0                     <pip>
mpmath                    0.19                     py35_1    defaults
msgpack-python            0.4.8                     <pip>
multihist                 0.5.1                     <pip>
multipledispatch          0.4.8                    py35_0    defaults
nb_anacondacloud          1.2.0                    py35_0    defaults
nb_conda                  2.0.0                    py35_0    defaults
nb_conda_kernels          2.0.0                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbdime                    0.4.1                     <pip>
nbformat                  4.1.0                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.3                    py35_0    defaults
numba                     0.28.1              np111py35_0    defaults
numexpr                   2.6.1               np111py35_0    defaults
numpy                     1.14.3                    <pip>
numpy                     1.11.1                   py35_0    defaults
odo                       0.5.0                    py35_1    defaults
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2j                        0    defaults
pagerduty-api             0.3                       <pip>
pandas                    0.18.1              np111py35_0    defaults
partd                     0.3.6                    py35_0    defaults
patchelf                  0.9                           0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pax                       6.9.0                     <pip>
pbr                       1.10.0                    <pip>
pcre                      8.39                          0    conda-forge
pep8                      1.7.0                    py35_0    defaults
pexpect                   4.2.1                     <pip>
pexpect                   4.0.1                    py35_0    defaults
pickleshare               0.7.4                    py35_0    defaults
pillow                    3.3.1                    py35_0    defaults
pip                       10.0.1                    <pip>
pip                       8.1.2                    py35_0    defaults
pixman                    0.34.0                        0    conda-forge
pkginfo                   1.3.2                    py35_0    defaults
ply                       3.9                      py35_0    defaults
prompt_toolkit            1.0.3                    py35_0    defaults
protobuf                  3.5.2.post1               <pip>
psutil                    4.3.1                    py35_0    defaults
ptyprocess                0.5.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycodestyle               2.3.1                     <pip>
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyelftools                0.24                      <pip>
pyflakes                  1.5.0                     <pip>
pyflakes                  1.3.0                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pylint                    1.5.4                    py35_1    defaults
pymongo                   3.4.0                     <pip>
pyopenssl                 16.2.0                   py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      5.6.0                    py35_0    conda-forge
pytables                  3.2.3.1             np111py35_0    defaults
pytest                    2.9.2                    py35_0    defaults
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
python-snappy             0.5                       <pip>
pytz                      2016.6.1                 py35_0    defaults
pyyaml                    3.12                     py35_0    defaults
pyzmq                     15.4.0                   py35_0    defaults
qt                        5.6.2                         1    conda-forge
qtawesome                 0.3.3                    py35_0    defaults
qtconsole                 4.2.1                    py35_1    defaults
qtpy                      1.1.2                    py35_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py35_0    defaults
requests                  2.13.0                   py35_0    conda-forge
requirements-parser       0.2.0                     <pip>
ripa                      0.2.0                     <pip>
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.11.14                  py35_0    defaults
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.17.1              np111py35_2    defaults
scipy                     0.18.1              np111py35_0    defaults
setuptools                27.2.0                   py35_0    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
smmap2                    2.0.3                     <pip>
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.6                    py35_0    defaults
spyder                    3.0.0                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
sqlite                    3.13.0                        0    defaults
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
terminado                 0.6                      py35_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.4.1                    py35_0    defaults
tqdm                      4.11.2                    <pip>
tqdm                      4.15.0                   py35_0    defaults
traitlets                 4.3.0                    py35_0    defaults
typing                    3.6.4                     <pip>
unicodecsv                0.14.1                   py35_0    defaults
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.11                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
wrapt                     1.10.6                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.3                    py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
xz                        5.2.2                         0    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.4                         0    defaults
zlib                      1.2.8                         3    defaults
```
</p></details>

**Comment by kalefranz** [comment]
‘conda update conda’, then let us know how it goes.

**Comment by tunnell** [comment]
@kalefranz That command does nothing as 4.2.16 is the latest allowed (I assume due to the 'anaconda' version?).  I assume that @pdeperio needs to update then also `conda update anaconda`?

**Comment by kalefranz** [comment]
`conda` is not in the `anaconda` metapackage. If you're updating from `4.2.16`, make sure the root environment is active, or just `conda update -n root conda`.  Could also try `conda install -n root conda=4.5`.

**Comment by tunnell** [comment]
@kalefranz Thanks.  This is the output:
`
$ conda install -n root conda=4.5
Fetching package metadata ...............
Solving package specifications: ....


UnsatisfiableError: The following specifications were found to be in conflict:
  - conda 4.5*
  - conda ==4.2.16
Use "conda info <package>" to see the dependencies for each package.
`

Is there a way to see what's pinning the version of conda to 4.2.16?

**Comment by kalefranz** [comment]
`conda config --show-sources`
