### ISSUE TITLE
Issue install pandas-datareader

### ISSUE THREAD

**Issue by tkj80** [conda/conda#7635]
Hi,

I ran the following to install pandas-datareader

C:\Program Files\Anaconda3>conda install -c anaconda pandas-datareader

however, I got the following error message:
Could not connect to https://conda.anaconda.org/anaconda/win-32/conda-env-2.6.0-h36134e3_1tar.bz2

I'm posting the details below:

------------------------------------------------------------------------------------------------------------------

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Windows\system32>cd C:\Program Files\Anaconda3

C:\Program Files\Anaconda3>conda install -c anaconda pandas-datareader
Fetching package metadata ...........
Solving package specifications: ..........

Package plan for installation in environment C:\Program Files (x86)\Anaconda3:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |       h36134e3_1           3 KB  anaconda
    vc-14                      |       h0510ff6_3           3 KB  anaconda
    pycosat-0.6.3              |   py35he3cbb3d_0          94 KB  anaconda
    requests-2.14.2            |           py35_0         705 KB  anaconda
    requests-file-1.4.3        |           py35_0           8 KB  anaconda
    requests-ftp-0.3.1         |           py35_0          13 KB  anaconda
    pandas-0.20.3              |   py35h4717d7f_2         7.7 MB  anaconda
    pandas-datareader-0.6.0    |           py35_0         135 KB  anaconda
    pyopenssl-16.2.0           |           py35_0          70 KB  anaconda
    conda-4.5.9                |           py35_0         1.0 MB  anaconda
    ------------------------------------------------------------
                                           Total:         9.8 MB

The following NEW packages will be INSTALLED:

    conda-env:         2.6.0-h36134e3_1   anaconda
    pandas-datareader: 0.6.0-py35_0       anaconda
    requests-file:     1.4.3-py35_0       anaconda
    requests-ftp:      0.3.1-py35_0       anaconda
    vc:                14-h0510ff6_3      anaconda

The following packages will be UPDATED:

    conda:             4.2.9-py35_0                --> 4.5.9-py35_0          ana
conda
    pandas:            0.18.1-np111py35_0          --> 0.20.3-py35h4717d7f_2 ana
conda
    pycosat:           0.6.1-py35_1                --> 0.6.3-py35he3cbb3d_0  ana
conda
    pyopenssl:         16.0.0-py35_0               --> 16.2.0-py35_0         ana
conda
    requests:          2.11.1-py35_0               --> 2.14.2-py35_0         ana
conda

Proceed ([y]/n)? y

Fetching packages ...
Could not connect to https://conda.anaconda.org/anaconda/win-32/conda-env-2.6.0-
h36134e3_1.tar.bz2
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Program Files (x86)\Anaconda3  (writable)
    default environment : C:\Program Files (x86)\Anaconda3
       envs directories : C:\Program Files (x86)\Anaconda3\envs
          package cache : C:\Program Files (x86)\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-32/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Program Files (x86)\Anaconda3\Scripts\conda-script.py install -c anaconda
pandas-datareader`

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\packages
\urllib3\connectionpool.py", line 595, in urlopen
        chunked=chunked)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\packages
\urllib3\connectionpool.py", line 352, in _make_request
        self._validate_conn(conn)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\packages
\urllib3\connectionpool.py", line 831, in _validate_conn
        conn.connect()
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\packages
\urllib3\connection.py", line 289, in connect
        ssl_version=resolved_ssl_version)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\packages
\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
        return context.wrap_socket(sock, server_hostname=server_hostname)
      File "C:\Program Files (x86)\Anaconda3\lib\ssl.py", line 377, in wrap_sock
et
        _context=self)
      File "C:\Program Files (x86)\Anaconda3\lib\ssl.py", line 752, in __init__
        self.do_handshake()
      File "C:\Program Files (x86)\Anaconda3\lib\ssl.py", line 988, in do_handsh
ake
        self._sslobj.do_handshake()
      File "C:\Program Files (x86)\Anaconda3\lib\ssl.py", line 633, in do_handsh
ake
        self._sslobj.do_handshake()
    ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_s
sl.c:645)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\adapters
.py", line 423, in send
        timeout=timeout
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\packages
\urllib3\connectionpool.py", line 621, in urlopen
        raise SSLError(e)
    requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAIL
ED] certificate verify failed (_ssl.c:645)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\fetch.py",
line 377, in download
        resp = session.get(url, stream=True, proxies=session.proxies, timeout=(3
.05, 27))
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\sessions
.py", line 488, in get
        return self.request('GET', url, **kwargs)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\sessions
.py", line 475, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\sessions
.py", line 617, in send
        history = [resp for resp in gen] if allow_redirects else []
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\sessions
.py", line 617, in <listcomp>
        history = [resp for resp in gen] if allow_redirects else []
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\sessions
.py", line 177, in resolve_redirects
        **adapter_kwargs
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\sessions
.py", line 596, in send
        r = adapter.send(request, **kwargs)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\requests\adapters
.py", line 497, in send
        raise SSLError(e, request=request)
    requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate v
erify failed (_ssl.c:645)

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\cli\install
.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\plan.py", l
ine 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\instruction
s.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\instruction
s.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\fetch.py",
line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\fetch.py",
line 403, in download
        raise CondaRuntimeError(msg)
    conda.exceptions.CondaRuntimeError: Runtime error: Connection error: [SSL: C
ERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645): https://conda.
anaconda.org/anaconda/win-32/conda-env-2.6.0-h36134e3_1.tar.bz2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\exceptions.
py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\cli\main.py
", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\cli\main_in
stall.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\cli\install
.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "C:\Program Files (x86)\Anaconda3\lib\contextlib.py", line 77, in __e
xit__
        self.gen.throw(type, value, traceback)
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\cli\common.
py", line 573, in json_progress_bars
        yield
      File "C:\Program Files (x86)\Anaconda3\lib\site-packages\conda\cli\install
.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime err
or: Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed
 (_ssl.c:645): https://conda.anaconda.org/anaconda/win-32/conda-env-2.6.0-h36134
e3_1.tar.bz2

**Comment by kalefranz** [comment]
This is a cert error.  Need to keep your conda up-to-date.  `conda update conda`
