### ISSUE TITLE
Specifications found to be in conflict--but only one package.

### ISSUE THREAD

**Issue by abalter** [conda/conda#7646]
## Current Behavior

When I try to install `r-phangorn` I am told that packages are in conflict. But I'm only trying to install one package. 

### Steps to Reproduce

```
balter@spectre:~$ conda install r-phangorn
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-phangorn
Use "conda info <package>" to see the dependencies for each package.

```

## Expected Behavior

Either `r-phangorn` should install or conda should tell me which package it is in conflict with.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
balter@spectre:~$ conda info

     active environment : None
       user config file : /home/balter/.condarc
 populated config files : /home/balter/.condarc
          conda version : 4.5.9
    conda-build version : not installed
         python version : 3.6.2.final.0
       base environment : /home/balter/biotest  (writable)
           channel URLs : https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/balter/biotest/pkgs
                          /home/balter/.conda/pkgs
       envs directories : /home/balter/biotest/envs
                          /home/balter/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.14.2 CPython/3.6.2 Linux/4.4.0-17134-Microsoft ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
balter@spectre:~$ conda config --show-sources
==> /home/balter/.condarc <==
channels:
  - bioconda
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
balter@spectre:~$ conda list --show-channel-urls
# packages in environment at /home/balter/biotest:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.0               anacondar_1    defaults
asn1crypto                0.22.0                   py36_0    defaults
bioconductor-biobase      2.34.0                 r3.3.2_0    bioconda
bioconductor-biocgenerics 0.22.0                 r3.3.2_0    bioconda
bioconductor-biocinstaller 1.24.0                 r3.3.2_0    bioconda
bioconductor-biocparallel 1.6.6                  r3.3.2_1    bioconda
bioconductor-biocstyle    2.0.3                  r3.3.2_1    bioconda
bioconductor-biomformat   1.2.0                  r3.3.2_1    bioconda
bioconductor-biostrings   2.42.1                 r3.3.2_0    bioconda
bioconductor-dada2        1.4.0                  r3.3.2_0    bioconda
bioconductor-decipher     2.8.1                  r3.3.2_0    cramjaco
bioconductor-genomeinfodb 1.10.3                 r3.3.2_0    bioconda
bioconductor-genomicalignments 1.10.0                 r3.3.2_0    bioconda
bioconductor-genomicranges 1.26.4                 r3.3.2_0    bioconda
bioconductor-iranges      2.8.2                  r3.3.2_0    bioconda
bioconductor-multtest     2.28.0                 r3.3.2_1    bioconda
bioconductor-phyloseq     1.19.1                 r3.3.2_0    bioconda
bioconductor-rhdf5        2.16.0                 r3.3.2_1    bioconda
bioconductor-rsamtools    1.26.1                 r3.3.2_0    bioconda
bioconductor-s4vectors    0.12.2                 r3.3.2_0    bioconda
bioconductor-shortread    1.32.0                 r3.3.2_0    bioconda
bioconductor-summarizedexperiment 1.4.0                  r3.3.2_2    bioconda
bioconductor-xvector      0.14.1                 r3.3.2_0    bioconda
bioconductor-zlibbioc     1.20.0                 r3.3.2_1    bioconda
bzip2                     1.0.6                h14c3975_5    defaults
ca-certificates           2018.03.07                    0    defaults
cairo                     1.14.8                        0    defaults
certifi                   2018.4.16                py36_0    defaults
cffi                      1.10.0                   py36_0    defaults
conda                     4.5.9                    py36_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              1.8.1                    py36_0    defaults
curl                      7.55.1               hcb0b314_2    defaults
fontconfig                2.12.1                        3    defaults
freetype                  2.5.5                         2    defaults
glib                      2.50.2                        1    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gsl                       2.4                  h14c3975_4    defaults
harfbuzz                  0.9.39                        2    defaults
icu                       54.1                          0    defaults
idna                      2.6                      py36_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
libffi                    3.2.1                         1    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.2.0                hdf63c60_3    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.34               hb9fc6fc_0    defaults
libssh2                   1.8.0                h8c220ad_2    defaults
libstdcxx-ng              7.2.0                hdf63c60_3    defaults
libtiff                   4.0.9                he85c1e1_1    defaults
libxml2                   2.9.4                         0    defaults
ncurses                   5.9                          10    defaults
openssl                   1.0.2o               h14c3975_1    defaults
packaging                 16.8                     py36_0    defaults
pango                     1.40.3                        1    defaults
pcre                      8.39                          1    defaults
pip                       9.0.1                    py36_1    defaults
pixman                    0.34.0               hceecf20_3    defaults
pycosat                   0.6.3            py36h14c3975_0    defaults
pycparser                 2.18                     py36_0    defaults
pyopenssl                 17.0.0                   py36_0    defaults
pyparsing                 2.2.0                    py36_0    defaults
python                    3.6.2                         0    defaults
r-ade4                    1.7_2                  r3.3.2_0    bioconda
r-ape                     4.0                    r3.3.2_0    defaults
r-assertthat              0.1                    r3.3.2_4    defaults
r-base                    3.3.2                         1    defaults
r-bh                      1.60.0_2               r3.3.2_0    bioconda
r-bitops                  1.0_6                  r3.3.2_2    defaults
r-cluster                 2.0.5                  r3.3.2_0    defaults
r-codetools               0.2_15                 r3.3.2_0    defaults
r-colorspace              1.3_1                  r3.3.2_0    defaults
r-data.table              1.10.4                 r3.3.2_0    bioconda
r-dbi                     0.5_1                  r3.3.2_0    defaults
r-dichromat               2.0_0                  r3.3.2_2    defaults
r-digest                  0.6.12                 r3.3.2_0    bioconda
r-doparallel              1.0.10                 r3.3.2_0    defaults
r-evaluate                0.10                   r3.3.2_0    defaults
r-foreach                 1.4.3                  r3.3.2_0    defaults
r-formatr                 1.4                    r3.3.2_0    defaults
r-futile.logger           1.4.1                  r3.3.2_0    bioconda
r-futile.options          1.0.0                  r3.3.2_0    bioconda
r-ggplot2                 2.2.1                  r3.3.2_0    bioconda
r-gridbase                0.4_7                  r3.3.2_0    defaults
r-gridextra               2.2.1                  r3.3.2_0    defaults
r-gtable                  0.2.0                  r3.3.2_0    defaults
r-highr                   0.6                    r3.3.2_0    defaults
r-hwriter                 1.3.2                  r3.3.2_0    bioconda
r-igraph                  1.0.1                  r3.3.2_0    defaults
r-irlba                   2.1.2                  r3.3.2_0    defaults
r-iterators               1.0.8                  r3.3.2_0    defaults
r-jsonlite                0.9.19                 r3.3.2_1    bioconda
r-knitr                   1.12.3                 r3.3.2_0    bioconda
r-labeling                0.3                    r3.3.2_2    defaults
r-lambda.r                1.1.7                  r3.3.2_0    bioconda
r-lattice                 0.20_34                r3.3.2_0    defaults
r-latticeextra            0.6_28                 r3.3.2_0    defaults
r-lazyeval                0.2.0                  r3.3.2_0    defaults
r-magrittr                1.5                    r3.3.2_2    defaults
r-markdown                0.7.7                  r3.3.2_2    defaults
r-mass                    7.3_45                 r3.3.2_0    defaults
r-matrix                  1.2_7.1                r3.3.2_0    defaults
r-memoise                 1.0.0                  r3.3.2_0    defaults
r-mgcv                    1.8_16                 r3.3.2_0    defaults
r-mime                    0.5                    r3.3.2_0    defaults
r-munsell                 0.4.3                  r3.3.2_0    defaults
r-nlme                    3.1_128                r3.3.2_0    defaults
r-nmf                     0.20.6                 r3.3.2_0    defaults
r-permute                 0.8_4                  r3.3.2_0    bioconda
r-pkgmaker                0.22                   r3.3.2_0    defaults
r-plogr                   0.1_1                  r3.3.2_0    defaults
r-plyr                    1.8.4                  r3.3.2_0    defaults
r-rcolorbrewer            1.1_2                  r3.3.2_3    defaults
r-rcpp                    0.12.8                 r3.3.2_0    defaults
r-rcppparallel            4.3.20                 r3.3.2_1    bioconda
r-rcurl                   1.95_4.8               r3.3.2_0    defaults
r-registry                0.3                    r3.3.2_0    defaults
r-reshape2                1.4.2                  r3.3.2_0    defaults
r-rngtools                1.2.4                  r3.3.2_0    defaults
r-rsqlite                 1.1_1                  r3.3.2_0    defaults
r-scales                  0.4.1                  r3.3.2_1    bioconda
r-snow                    0.4_1                  r3.3.2_0    bioconda
r-stringi                 1.1.2                  r3.3.2_0    defaults
r-stringr                 1.1.0                  r3.3.2_0    defaults
r-survival                2.40_1                 r3.3.2_0    defaults
r-tibble                  1.2                    r3.3.2_1    bioconda
r-vegan                   2.3_4                  r3.3.2_2    bioconda
r-xtable                  1.8_2                  r3.3.2_0    defaults
r-yaml                    2.1.13                 r3.3.2_1    bioconda
readline                  6.2                           2    defaults
requests                  2.14.2                   py36_0    defaults
ruamel_yaml               0.11.14                  py36_1    defaults
setuptools                36.4.0                   py36_1    defaults
six                       1.10.0                   py36_0    defaults
sqlite                    3.13.0                        0    defaults
tk                        8.5.18                        0    defaults
wheel                     0.29.0                   py36_0    defaults
xz                        5.2.3                         0    defaults
yaml                      0.1.6                         0    defaults
zlib                      1.2.11                        0    defaults

```
</p></details>

**Comment by kalefranz** [comment]
reproduced on osx in master branch

```
$ conda install r-phangorn
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - r-phangorn

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Full stack details from `conda install r-phangorn -v`:

```
Traceback (most recent call last):
  File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 250, in install
    force_reinstall=context.force_reinstall or context.force,
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 454, in _run_sat
    conflicting_specs = ssc.r.get_conflicting_specs(tuple(final_environment_specs))
  File "/Users/kfranz/continuum/conda/conda/resolve.py", line 766, in get_conflicting_specs
    reduced_index = self.get_reduced_index(specs)
  File "/Users/kfranz/continuum/conda/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/Users/kfranz/continuum/conda/conda/resolve.py", line 321, in get_reduced_index
    specs, features = self.verify_specs(specs)
  File "/Users/kfranz/continuum/conda/conda/resolve.py", line 223, in verify_specs
    raise ResolvePackageNotFound(bad_deps)
conda.exceptions.ResolvePackageNotFound:
  - r-phangorn

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kfranz/continuum/conda/conda/exceptions.py", line 962, in __call__
    return func(*args, **kwargs)
  File "/Users/kfranz/continuum/conda/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/kfranz/continuum/conda/conda/cli/conda_argparse.py", line 81, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/kfranz/continuum/conda/conda/cli/main_install.py", line 21, in execute
    install(args, parser, 'install')
  File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 260, in install
    raise PackagesNotFoundError(e._formatted_chains, channels_urls)
conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

  - r-phangorn

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/osx-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by kalefranz** [comment]
Erm, scratch that.  Didn't have bioconda in the channels list for that stack trace, and that was just a normal package not found exception.

**Comment by kalefranz** [comment]
Reproduced on macOS via

```
$ conda install -c bioconda r-phangorn -v
Collecting package metadata: ...working... done
Solving environment: ...working... failed
Traceback (most recent call last):
  File "/Users/kfranz/continuum/conda/conda/exceptions.py", line 962, in __call__
    return func(*args, **kwargs)
  File "/Users/kfranz/continuum/conda/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/kfranz/continuum/conda/conda/cli/conda_argparse.py", line 81, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/kfranz/continuum/conda/conda/cli/main_install.py", line 21, in execute
    install(args, parser, 'install')
  File "/Users/kfranz/continuum/conda/conda/cli/install.py", line 250, in install
    force_reinstall=context.force_reinstall or context.force,
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 107, in solve_for_transaction
    force_remove, force_reinstall)
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 145, in solve_for_diff
    force_remove)
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 242, in solve_final_state
    ssc = self._run_sat(ssc)
  File "/Users/kfranz/continuum/conda/conda/core/solve.py", line 489, in _run_sat
    ssc.solution_precs = ssc.r.solve(tuple(final_environment_specs))
  File "/Users/kfranz/continuum/conda/conda/common/io.py", line 85, in decorated
    return f(*args, **kwds)
  File "/Users/kfranz/continuum/conda/conda/resolve.py", line 938, in solve
    self.find_conflicts(specs)
  File "/Users/kfranz/continuum/conda/conda/resolve.py", line 295, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - r-phangorn
Use "conda search <package> --info" to see the dependencies for each package.
```

The failure here happens in 

https://github.com/conda/conda/blob/d244111820ba73df5802f6283b4f4e625ab024bf/conda/resolve.py#L393-L402

We shouldn't be resetting the filter there.  Instead, we should be raising an appropriately descriptive error message at that point, rather than letting the unsatisfiable condition leak through in the output of `Resolve.get_reduced_index()` and then expect later code to know what to do with it.

**Comment by kalefranz** [comment]
@abalter FWIW, I am able to get a solution via

    conda create --dry-run -qnx -c bioconda -c conda-forge --override-channels r-phangorn

I guess that was on master, but I wouldn't expect a different result on 4.5.x.

**Comment by kalefranz** [comment]
I believe the bioconda channel is moving toward the assumption that you'll be supplementing it with conda-forge, if they haven't made that explicit already.

**Comment by abalter** [comment]
@mbargull -- you made [this suggestion](https://github.com/conda/conda/issues/7684#issuecomment-415588307) on a different issue I raised, and it solved the problem. It also solved other problems I was having with building environments with `bioconda` bioconductor packages. I should probably raise the issue with bioconda.

> The current state of the Bioconda docs still says to give bioconda the higher priority. In reality (due to the issue you just encountered) in often makes sense to use
```
channels:
  - conda-forge
  - bioconda
  - defaults
```
>though. (defaults has to be in the mix because conda-forge is not yet self-contained and depends on packages only available in defaults.)

**Comment by mbargull** [comment]
> I should probably raise the issue with bioconda.

IIRC, we (bioconda/core) only ever talked about this casually and I guess I never opened an issue for this on `bioconda-utils` -- I'll do that right away.

**Comment by mbargull** [comment]
xref: https://github.com/bioconda/bioconda-utils/issues/330
