### ISSUE TITLE
I get an error message when opening Anaconda Prompt and can't open Anaconda Navigator since update to newest version

### ISSUE THREAD

**Issue by FlorianBleichenbacher** [conda/conda#7652]
## Current Behavior

Whenever I open the Anaconda Prompt or try to open the Anaconda Navigator, I get the error message as below. It started to happen when I updated to the newest Anaconda version. I tried reinstalling two times already.

### Steps to Reproduce

```
**When I open the Anaconda Prompt I get:**

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\cli\main.py", line 97, in main
        from ..activate import main as activator_main
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\activate.py", line 12, in <module>
        context.__init__()  # oOn import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\fblei\.condarc", position 0

`$ C:\Users\fblei\Anaconda3\Scripts\conda shell.cmd.exe activate activate C:\Users\fblei\Anaconda3`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\fblei\Anaconda3
                 HOMEPATH=\Users\fblei
                     PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\TXE
                          Components\TCS\;C:\Program Files\Intel\TXE Components\TCS\;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0\;C:\Program Files\Intel\TXE
                          Components\DAL\;C:\Program Files (x86)\Intel\TXE
                          Components\DAL\;C:\Program Files\Intel\TXE Components\IPT\;C:\Program
                          Files (x86)\Intel\TXE Components\IPT\;C:\Program Files
                          (x86)\Calibre2\;C:\Program
                          Files\Git\cmd;C:\PostgreSQL\pg10\bin;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\
                          Users\fblei\Anaconda3;C:\Users\fblei\Anaconda3\Library\mingw-w64\bin;C
                          :\Users\fblei\Anaconda3\Library\usr\bin;C:\Users\fblei\Anaconda3\Libra
                          ry\bin;C:\Users\fblei\Anaconda3\Scripts;C:\Users\fblei\AppData\Local\M
                          icrosoft\WindowsApps;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\fblei\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\fblei\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\fblei\Anaconda3\pkgs
                          C:\Users\fblei\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\fblei\Anaconda3\envs
                          C:\Users\fblei\AppData\Local\conda\conda\envs
                          C:\Users\fblei\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:


**When I try to open the Anaconda Navigator I get the following message:**

Navigator Error
An unexpected error occurred on Navigator start-up
Report
Please report this issue in the anaconda issue tracker 
Main Error

expected str, bytes or os.PathLike object, not NoneType

Traceback

Traceback (most recent call last):
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 150, in start_app
    window = run_app(splash)
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2185, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1714, in CondaAPI
    CONDA_API = _CondaAPI()
  File "C:\Users\fblei\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "C:\Users\fblei\Anaconda3\lib\ntpath.py", line 76, in join
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

## Expected Behavior

I think both programs should start without an error message.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\cli\main.py", line 74, in _main
        context.__init__(argparse_args=args)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\base\context.py", line 236, in __init__
        argparse_args=argparse_args)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 722, in __init__
        self._set_search_path(search_path)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 728, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 369, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 344, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\configuration.py", line 332, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\conda\common\serialize.py", line 54, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 637, in load
        loader = Loader(stream, version, preserve_quotes=preserve_quotes)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\loader.py", line 59, in __init__
        Reader.__init__(self, stream, loader=self)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 80, in __init__
        self.stream = stream  # type: Any  # as .read is called
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 125, in stream
        self.determine_encoding()
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 180, in determine_encoding
        self.update(1)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 241, in update
        self.check_printable(data)
      File "C:\Users\fblei\Anaconda3\lib\site-packages\ruamel_yaml\reader.py", line 208, in check_printable
        'unicode', "special characters are not allowed")
    ruamel_yaml.reader.ReaderError: unacceptable character #x0000: special characters are not allowed
      in "C:\Users\fblei\.condarc", position 0

`$ C:\Users\fblei\Anaconda3\Scripts\conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
usage: conda config [-h] [--json] [--debug] [--verbose]
                    [--system | --env | --file FILE]
                    (--show [SHOW [SHOW ...]] | --show-sources | --validate | --describe [DESCRIBE [DESCRIBE ...]] | --write-default | --get [KEY [KEY ...]] | --append KEY VALUE | --prepend KEY VALUE | --set KEY VALUE | --remove KEY VALUE | --remove-key KEY | --stdin)
conda config: error: one of the arguments --show --show-sources --validate --describe --write-default --get --append --prepend/--add --set --remove --remove-key --stdin is required
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
 environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\fblei\Anaconda3
                 HOMEPATH=\Users\fblei
                     PATH=C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\TXE
                          Components\TCS\;C:\Program Files\Intel\TXE Components\TCS\;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0\;C:\Program Files\Intel\TXE
                          Components\DAL\;C:\Program Files (x86)\Intel\TXE
                          Components\DAL\;C:\Program Files\Intel\TXE Components\IPT\;C:\Program
                          Files (x86)\Intel\TXE Components\IPT\;C:\Program Files
                          (x86)\Calibre2\;C:\Program
                          Files\Git\cmd;C:\PostgreSQL\pg10\bin;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;C:\Program Files\Microsoft VS Code\bin;C:\
                          Users\fblei\Anaconda3;C:\Users\fblei\Anaconda3\Library\mingw-w64\bin;C
                          :\Users\fblei\Anaconda3\Library\usr\bin;C:\Users\fblei\Anaconda3\Libra
                          ry\bin;C:\Users\fblei\Anaconda3\Scripts;C:\Users\fblei\AppData\Local\M
                          icrosoft\WindowsApps;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : C:\Users\fblei\.condarc
 populated config files :
          conda version : 4.5.4
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : C:\Users\fblei\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\fblei\Anaconda3\pkgs
                          C:\Users\fblei\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\fblei\Anaconda3\envs
                          C:\Users\fblei\AppData\Local\conda\conda\envs
                          C:\Users\fblei\.conda\envs
               platform : win-64
             user-agent : conda/4.5.4 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.15063
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```
</p></details>

**Comment by goanpeca** [comment]
Please delete this file `C:\Users\fblei\.condarc` and try again
