### ISSUE TITLE
conda After install eroor

### ISSUE THREAD

**Issue by rushike** [conda/conda#7657]
conda install statsmodels matplotlib ipython -y

### Steps to Reproduce

```
conda install statsmodels matplotlib ipython -y
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Traceback (most recent call last):
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\main.py", line 106, in _main
    p, sub_parsers = generate_parser()
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\main.py", line 55, in generate_parser
    from ..cli import conda_argparse
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ModuleNotFoundError: No module named 'pycosat'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python37-32\Scripts\conda-script.py", line 11, in <module>
    load_entry_point('conda==4.2.7', 'console_scripts', 'conda')()
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main)
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\exceptions.py", line 488, in conda_exception_handler
    print_unexpected_error_message(e)
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\exceptions.py", line 436, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\exceptions.py", line 395, in get_info
    from conda.cli import conda_argparse
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\conda_argparse.py", line 15, in <module>
    from .common import add_parser_help
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\cli\common.py", line 16, in <module>
    from ..resolve import MatchSpec
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\resolve.py", line 14, in <module>
    from .logic import minimal_unsatisfiable_subset, Clauses
  File "c:\users\rushi\appdata\local\programs\python\python37-32\lib\site-packages\conda\logic.py", line 31, in <module>
    import pycosat
ModuleNotFoundError: No module named 'pycosat'
<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
You've corrupted your install somehow. Best just to start over.
