### ISSUE TITLE
I cannot  install qt 5.6.2

### ISSUE THREAD

**Issue by lunaplush** [conda/conda#7668]
Hi!

Now I try to install opencv on python:
I have python 3.5 Anaconda (4.2.0) installed.
When I receive this error, I try to install new last Anaconda, but have the same error.
I see problem with qt-5.6.2-vc15 installation

C:\Users\Inspiron\Downloads>conda install -c conda-forge opencv

An unexpected error has occurred.####################                    |  61%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 2.6.0
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\Inspiron\Anaconda3  (writable)
    default environment : C:\Users\Inspiron\Anaconda3
       envs directories : C:\Users\Inspiron\Anaconda3\envs
          package cache : C:\Users\Inspiron\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

`$ C:\Users\Inspiron\Anaconda3\Scripts\conda-script.py install -c conda-forge op
encv`

    Traceback (most recent call last):
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\exceptions.py",
line 473, in conda_exception_handler
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\cli\main.py", li
ne 144, in _main
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\cli\main_install
.py", line 80, in execute
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\cli\install.py",
 line 405, in install
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\plan.py", line 6
43, in execute_actions
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\instructions.py"
, line 134, in execute_instructions
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\instructions.py"
, line 78, in LINK_CMD
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\install.py", lin
e 989, in link
      File "C:\Users\Inspiron\Anaconda3\lib\site-packages\conda\install.py", lin
e 491, in run_script
      File "C:\Users\Inspiron\Anaconda3\lib\subprocess.py", line 576, in check_c
all
        retcode = call(*popenargs, **kwargs)
      File "C:\Users\Inspiron\Anaconda3\lib\subprocess.py", line 557, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Users\Inspiron\Anaconda3\lib\subprocess.py", line 947, in __init_
_
        restore_signals, start_new_session)
      File "C:\Users\Inspiron\Anaconda3\lib\subprocess.py", line 1224, in _execu
te_child
        startupinfo)
    FileNotFoundError: [WinError 2] Не удается найти указанный файл

**Comment by mingwandroid** [comment]
Any reason not to use default's opencv?

**Comment by mingwandroid** [comment]
Closing, please file at `conda-forge`.
