### ISSUE TITLE
FEniCS package returns - ValidationError: Value for sha256 cannot be None.

### ISSUE THREAD

**Issue by nyue** [conda/conda#7681]
## Current Behavior

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/nicholas/anaconda2  (writable)
    default environment : /home/nicholas/anaconda2
       envs directories : /home/nicholas/anaconda2/envs
          package cache : /home/nicholas/anaconda2/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-693.17.1.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 1000:1000

`$ /home/nicholas/anaconda2/bin/conda create -n fenicsproject -c conda-forge fenics`

    Traceback (most recent call last):
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/nicholas/anaconda2/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.

### Steps to Reproduce

```
conda create -n fenicsproject -c conda-forge fenics

```

## Expected Behavior

FEniCS install successfully

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/nicholas/anaconda2  (writable)
    default environment : /home/nicholas/anaconda2
       envs directories : /home/nicholas/anaconda2/envs
          package cache : /home/nicholas/anaconda2/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-693.17.1.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 1000:1000

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
NOTE : Nothing was printed out on the console
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/nicholas/anaconda2:
#
_license                  1.1                      py27_1    defaults
alabaster                 0.7.9                    py27_0    defaults
anaconda                  4.3.0               np111py27_0    defaults
anaconda-client           1.6.0                    py27_0    defaults
anaconda-navigator        1.4.3                    py27_0    defaults
argcomplete               1.0.0                    py27_1    defaults
astroid                   1.4.9                    py27_0    defaults
astropy                   1.3                 np111py27_0    defaults
babel                     2.3.4                    py27_0    defaults
backports                 1.0                      py27_0    defaults
backports_abc             0.5                      py27_0    defaults
beautifulsoup4            4.5.3                    py27_0    defaults
bitarray                  0.8.1                    py27_0    defaults
blaze                     0.10.1                   py27_0    defaults
bokeh                     0.12.4                   py27_0    defaults
boto                      2.45.0                   py27_0    defaults
bottleneck                1.2.0               np111py27_0    defaults
cairo                     1.14.8                        0    defaults
cdecimal                  2.3                      py27_2    defaults
cffi                      1.9.1                    py27_0    defaults
chardet                   2.3.0                    py27_0    defaults
chest                     0.2.3                    py27_0    defaults
click                     6.7                      py27_0    defaults
cloudpickle               0.2.2                    py27_0    defaults
clyent                    1.2.2                    py27_0    defaults
colorama                  0.3.7                    py27_0    defaults
conda                     4.3.8                    py27_0    defaults
conda-env                 2.6.0                         0    defaults
configobj                 5.0.6                    py27_0    defaults
configparser              3.5.0                    py27_0    defaults
contextlib2               0.5.4                    py27_0    defaults
cryptography              1.7.1                    py27_0    defaults
curl                      7.52.1                        0    defaults
cycler                    0.10.0                   py27_0    defaults
cython                    0.25.2                   py27_0    defaults
cytoolz                   0.8.2                    py27_0    defaults
dask                      0.13.0                   py27_0    defaults
datashape                 0.5.4                    py27_0    defaults
dbus                      1.10.10                       0    defaults
decorator                 4.0.11                   py27_0    defaults
dill                      0.2.5                    py27_0    defaults
docutils                  0.13.1                   py27_0    defaults
entrypoints               0.2.2                    py27_0    defaults
enum34                    1.1.6                    py27_0    defaults
et_xmlfile                1.0.1                    py27_0    defaults
expat                     2.1.0                         0    defaults
fastcache                 1.0.2                    py27_1    defaults
flask                     0.12                     py27_0    defaults
flask-cors                3.0.2                    py27_0    defaults
fontconfig                2.12.1                        2    defaults
freetype                  2.5.5                         2    defaults
funcsigs                  1.0.2                    py27_0    defaults
functools32               3.2.3.2                  py27_0    defaults
futures                   3.0.5                    py27_0    defaults
get_terminal_size         1.0.0                    py27_0    defaults
gevent                    1.2.1                    py27_0    defaults
glib                      2.50.2                        1    defaults
greenlet                  0.4.11                   py27_0    defaults
grin                      1.2.1                    py27_3    defaults
gst-plugins-base          1.8.0                         0    defaults
gstreamer                 1.8.0                         0    defaults
h5py                      2.6.0               np111py27_2    defaults
harfbuzz                  0.9.39                        2    defaults
hdf5                      1.8.17                        1    defaults
heapdict                  1.0.0                    py27_1    defaults
icu                       54.1                          0    defaults
idna                      2.2                      py27_0    defaults
imagesize                 0.7.1                    py27_0    defaults
ipaddress                 1.0.18                   py27_0    defaults
ipykernel                 4.5.2                    py27_0    defaults
ipython                   5.1.0                    py27_0    defaults
ipython_genutils          0.1.0                    py27_0    defaults
ipywidgets                5.2.2                    py27_1    defaults
isort                     4.2.5                    py27_0    defaults
itsdangerous              0.24                     py27_0    defaults
jbig                      2.1                           0    defaults
jdcal                     1.3                      py27_0    defaults
jedi                      0.9.0                    py27_1    defaults
jinja2                    2.9.4                    py27_0    defaults
jpeg                      9b                            0    defaults
jsonschema                2.5.1                    py27_0    defaults
jupyter                   1.0.0                    py27_3    defaults
jupyter_client            4.4.0                    py27_0    defaults
jupyter_console           5.0.0                    py27_0    defaults
jupyter_core              4.2.1                    py27_0    defaults
lazy-object-proxy         1.2.2                    py27_0    defaults
libffi                    3.2.1                         1    defaults
libgcc                    4.8.5                         2    defaults
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          0    defaults
libpng                    1.6.27                        0    defaults
libsodium                 1.0.10                        0    defaults
libtiff                   4.0.6                         3    defaults
libxcb                    1.12                          1    defaults
libxml2                   2.9.4                         0    defaults
libxslt                   1.1.29                        0    defaults
llvmlite                  0.15.0                   py27_0    defaults
locket                    0.2.0                    py27_1    defaults
lxml                      3.7.2                    py27_0    defaults
markupsafe                0.23                     py27_2    defaults
matplotlib                2.0.0               np111py27_0    defaults
mistune                   0.7.3                    py27_0    defaults
mkl                       2017.0.1                      0    defaults
mkl-service               1.1.2                    py27_3    defaults
mpmath                    0.19                     py27_1    defaults
multipledispatch          0.4.9                    py27_0    defaults
nbconvert                 4.2.0                    py27_0    defaults
nbformat                  4.2.0                    py27_0    defaults
networkx                  1.11                     py27_0    defaults
nltk                      3.2.2                    py27_0    defaults
nose                      1.3.7                    py27_1    defaults
notebook                  4.3.1                    py27_0    defaults
numba                     0.30.1              np111py27_0    defaults
numexpr                   2.6.1               np111py27_2    defaults
numpy                     1.11.3                   py27_0    defaults
numpydoc                  0.6.0                    py27_0    defaults
odo                       0.5.0                    py27_1    defaults
openpyxl                  2.4.1                    py27_0    defaults
openssl                   1.0.2k                        0    defaults
pandas                    0.19.2              np111py27_1    defaults
partd                     0.3.7                    py27_0    defaults
path.py                   10.0                     py27_0    defaults
pathlib2                  2.2.0                    py27_0    defaults
patsy                     0.4.1                    py27_0    defaults
pcre                      8.39                          1    defaults
pep8                      1.7.0                    py27_0    defaults
pexpect                   4.2.1                    py27_0    defaults
pickleshare               0.7.4                    py27_0    defaults
pillow                    4.0.0                    py27_0    defaults
pip                       9.0.1                    py27_1    defaults
pixman                    0.34.0                        0    defaults
ply                       3.9                      py27_0    defaults
prompt_toolkit            1.0.9                    py27_0    defaults
psutil                    5.0.1                    py27_0    defaults
ptyprocess                0.5.1                    py27_0    defaults
py                        1.4.32                   py27_0    defaults
pyasn1                    0.1.9                    py27_0    defaults
pycairo                   1.10.0                   py27_0    defaults
pycosat                   0.6.1                    py27_1    defaults
pycparser                 2.17                     py27_0    defaults
pycrypto                  2.6.1                    py27_4    defaults
pycurl                    7.43.0                   py27_2    defaults
pyflakes                  1.5.0                    py27_0    defaults
pygments                  2.1.3                    py27_0    defaults
pylint                    1.6.4                    py27_1    defaults
pyopenssl                 16.2.0                   py27_0    defaults
pyparsing                 2.1.4                    py27_0    defaults
pyqt                      5.6.0                    py27_2    defaults
pytables                  3.3.0               np111py27_0    defaults
pytest                    3.0.5                    py27_0    defaults
python                    2.7.13                        0    defaults
python-dateutil           2.6.0                    py27_0    defaults
pytz                      2016.10                  py27_0    defaults
pyyaml                    3.12                     py27_0    defaults
pyzmq                     16.0.2                   py27_0    defaults
qt                        5.6.2                         3    defaults
qtawesome                 0.4.3                    py27_0    defaults
qtconsole                 4.2.1                    py27_1    defaults
qtpy                      1.2.1                    py27_0    defaults
readline                  6.2                           2    defaults
redis                     3.2.0                         0    defaults
redis-py                  2.10.5                   py27_0    defaults
requests                  2.12.4                   py27_0    defaults
rope                      0.9.4                    py27_1    defaults
ruamel_yaml               0.11.14                  py27_1    defaults
scandir                   1.4                      py27_0    defaults
scikit-image              0.12.3              np111py27_1    defaults
scikit-learn              0.18.1              np111py27_1    defaults
scipy                     0.18.1              np111py27_1    defaults
seaborn                   0.7.1                    py27_0    defaults
setuptools                27.2.0                   py27_0    defaults
simplegeneric             0.8.1                    py27_1    defaults
singledispatch            3.4.0.3                  py27_0    defaults
sip                       4.18                     py27_0    defaults
six                       1.10.0                   py27_0    defaults
snowballstemmer           1.2.1                    py27_0    defaults
sockjs-tornado            1.0.3                    py27_0    defaults
sphinx                    1.5.1                    py27_0    defaults
spyder                    3.1.2                    py27_0    defaults
sqlalchemy                1.1.5                    py27_0    defaults
sqlite                    3.13.0                        0    defaults
ssl_match_hostname        3.4.0.2                  py27_1    defaults
statsmodels               0.6.1               np111py27_1    defaults
subprocess32              3.2.7                    py27_0    defaults
sympy                     1.0                      py27_0    defaults
terminado                 0.6                      py27_0    defaults
tk                        8.5.18                        0    defaults
toolz                     0.8.2                    py27_0    defaults
tornado                   4.4.2                    py27_0    defaults
traitlets                 4.3.1                    py27_0    defaults
unicodecsv                0.14.1                   py27_0    defaults
wcwidth                   0.1.7                    py27_0    defaults
werkzeug                  0.11.15                  py27_0    defaults
wheel                     0.29.0                   py27_0    defaults
widgetsnbextension        1.2.6                    py27_0    defaults
wrapt                     1.10.8                   py27_0    defaults
xlrd                      1.0.0                    py27_0    defaults
xlsxwriter                0.9.6                    py27_0    defaults
xlwt                      1.2.0                    py27_0    defaults
xz                        5.2.2                         1    defaults
yaml                      0.1.6                         0    defaults
zeromq                    4.1.5                         0    defaults
zlib                      1.2.8                         3    defaults

```
</p></details>

**Comment by kalefranz** [comment]
Indeed, this error was long ago fixed in a conda update.
