### ISSUE TITLE
Cannot install matplotlib

### ISSUE THREAD

**Issue by melaniefp** [conda/conda#7685]
### Steps to Reproduce

```
$  conda install -c conda-forge matplotlib 
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x  (read only)
    default environment : /n/home11/mfernandezpradier/.conda/envs/bnn
       envs directories : /n/home11/mfernandezpradier/.conda/envs
                          /n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/envs
          package cache : /n/home11/mfernandezpradier/.conda/envs/.pkgs
                          /n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-693.21.1.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 11822:403036



`$ /n/home11/mfernandezpradier/.conda/envs/bnn/bin/conda install -c conda-forge matplotlib`




    Traceback (most recent call last):
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/cli/install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 141, in func
        res = f(*args, **kwargs)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 385, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/index.py", line 204, in fetch_repodata_remote_request
        fetched_repodata = json.loads(json_str) if json_str else {}
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/json/__init__.py", line 339, in loads
        return _default_decoder.decode(s)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/json/decoder.py", line 364, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/json/decoder.py", line 380, in raw_decode
        obj, end = self.scan_once(s, idx)
    MemoryError

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by kalefranz** [comment]
Your machine ran out of memory 🤷‍♂️

**Comment by kalefranz** [comment]
Operation in memory-constrained environments is a known issue, but it also hasn't generally been that big of a problem in practice.  Other issues that discuss memory usage are https://github.com/conda/conda/issues/1197 and https://github.com/conda/conda/issues/5003.
