### ISSUE TITLE
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_apple_darwin13_4_0'

### ISSUE THREAD

**Issue by jolespin** [conda/conda#7687]
## Current Behavior
I've tried creating a fresh new `python 3.6` environment but I'm getting the following error after I run it:
`ModuleNotFoundError: No module named '_sysconfigdata_x86_64_apple_darwin13_4_0'`

### Steps to Reproduce
```
(python3) Joshs-MacBook-Pro: mu$ conda create --name py3_devel python=3.6 --yes
Solving environment: done

## Package Plan ##

  environment location: /Users/mu/anaconda/envs/py3_devel

  added / updated specs:
    - python=3.6


The following NEW packages will be INSTALLED:

    bzip2:           1.0.6-1              conda-forge
    ca-certificates: 2018.8.24-ha4d7672_0 conda-forge
    certifi:         2018.8.24-py36_1     conda-forge
    libffi:          3.2.1-hfc679d8_4     conda-forge
    ncurses:         6.1-hfc679d8_1       conda-forge
    openssl:         1.0.2o-h470a237_1    conda-forge
    pip:             18.0-py36_1          conda-forge
    python:          3.6.6-h5001a0f_0     conda-forge
    readline:        7.0-haf1bffa_1       conda-forge
    setuptools:      40.2.0-py36_0        conda-forge
    sqlite:          3.24.0-h2f33b56_0    conda-forge
    tk:              8.6.8-0              conda-forge
    wheel:           0.31.1-py36_1        conda-forge
    xz:              5.2.4-h470a237_1     conda-forge
    zlib:            1.2.11-h470a237_3    conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py3_devel
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(python3) Joshs-MacBook-Pro: mu$ source activate py3_devel
(py3_devel) Joshs-MacBook-Pro: mu$ python
Failed to import the site module
Traceback (most recent call last):
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/site.py", line 535, in <module>
    main()
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/site.py", line 521, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/sysconfig.py", line 601, in get_config_var
    return get_config_vars().get(name)
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/sysconfig.py", line 550, in get_config_vars
    _init_posix(_CONFIG_VARS)
  File "/Users/mu/anaconda/envs/py3_devel/lib/python3.6/sysconfig.py", line 421, in _init_posix
    _temp = __import__(name, globals(), locals(), ['build_time_vars'], 0)
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_apple_darwin13_4_0'
```

## Expected Behavior
There should not be the `ModuleNotFoundError` when running Python

## Environment Information

```
(py3_devel) Joshs-MacBook-Pro: mu$ conda info

     active environment : py3_devel
    active env location : /Users/mu/anaconda/envs/py3_devel
            shell level : 2
       user config file : /Users/mu/.condarc
 populated config files : /Users/mu/.condarc
          conda version : 4.5.11
    conda-build version : 3.4.1
         python version : 3.6.4.final.0
       base environment : /Users/mu/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/mu/anaconda/pkgs
                          /Users/mu/.conda/pkgs
       envs directories : /Users/mu/anaconda/envs
                          /Users/mu/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.4 Darwin/16.7.0 OSX/10.12.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(py3_devel) Joshs-MacBook-Pro: mu$ conda config --show-sources
==> /Users/mu/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(py3_devel) Joshs-MacBook-Pro: mu$ conda list --show-channel-urls
# packages in environment at /Users/mu/anaconda/envs/py3_devel:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
certifi                   2018.8.24                py36_1    conda-forge
libffi                    3.2.1                hfc679d8_4    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
openssl                   1.0.2o               h470a237_1    conda-forge
pip                       18.0                     py36_1    conda-forge
python                    3.6.6                h5001a0f_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
tk                        8.6.8                         0    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</p></details>

**Comment by smcinerney** [comment]
Which version of Xcode (and Macos) do you have installed, and was it Xcode Command-Line Tools only, or full? Try restarting your environment and rerunning.

**Comment by smcinerney** [comment]
I got this too. I think it's a duplicate of #6648 , and the solution is to `conda deactivate` to get down to the base environment containing python and compilers.

**Comment by daniel-karl** [comment]
@smcinerney thanks, this worked for me after the latest mac os catalina update, which broke my whole environment. i could solve all the other items following: https://www.anaconda.com/how-to-restore-anaconda-after-macos-catalina-update/
