### ISSUE TITLE
conda update "all installed packages" eats alot of resources

### ISSUE THREAD

**Issue by marscher** [conda/conda#777]
if one wants to update all installed packages (without pip installed ones), conda grants itself 40% of 8 GB of RAM, which is totally unacceptable. Conda is version 3.5.5.

This command passes all installed packages to "conda update", which then hangs in a "solving package specifications" step.

```
 marscher@marscher-laptop:~/$ conda list --no-pip |cut -f1 -d ' ' |grep -v '#'| xargs conda update
Fetching package metadata: ..
Solving package specifications: .......................^C
Traceback (most recent call last):
  File "/home/marscher/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main args.func(args, p)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 259, in install
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/plan.py", line 265, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 672, in solve
    minimal_hint=minimal_hint)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 496, in solve2
    version_constraints, evaluate_func=evaluate_func)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/logic.py", line 517, in bisect_constraints
    constraints = func(*rhs)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 491, in version_constraints
    return set(generate_constraints(eq, m, [lo, hi], alg=alg))
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/logic.py", line 472, in generate_constraints
    additional_clauses.add((C.build_BDD(l, polarity=True),))
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/logic.py", line 282, in build_BDD
    ret[call_stack.pop()] = self.ITE(abs(LA), hi, lo, polarity=polarity)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/utils.py", line 100, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/home/marscher/anaconda/lib/python2.7/site-packages/conda/logic.py", line 156, in ITE
    (-c, t, -x),
KeyboardInterrupt
```

**Comment by VelizarVESSELINOV** [comment]
I'm surprised that the issue is closed, as it is not working as expected for me taking a lot of time, resources even noise my Mac start to make noise as the CPU is for so long time without be able to:

Last login: Thu Mar  5 16:48:54 on ttys000
VV@Velizars-MacBook-Pro:~$ conda update --all
Fetching package metadata: ..
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
WARNING: This could take a while. Type Ctrl-C to exit.
[      COMPLETE      ] |##################################################| 100%


Hint: pykit >=0.1.0 and gevent_zeromq >=0.2.5 has a conflict with the remaining packages
VV@Velizars-MacBook-Pro:~$ conda update --all
Fetching package metadata: ..
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: 
WARNING: This could take a while. Type Ctrl-C to exit.
[96/156              ] |##############################                    |  60%

**Comment by asmeurer** [comment]
You aren't running the latest version of conda. Try running `conda update conda`.

**Comment by marscher** [comment]
with conda-3.14 it is still very memory demanding

**Comment by marscher** [comment]
I wonder how apt for instance handle this problem (apt-get upgrade takes seconds solving essentially the same problem). Which algorithms do they use?

**Comment by marscher** [comment]
This is fixed
