### ISSUE TITLE
conda env create from yaml error

### ISSUE THREAD

**Issue by MeeMaster** [conda/conda#7872]
I'm setting up a docker image with miniconda and an environment i specified in a file.
I'm using nvidia/cuda base image:
`FROM nvidia/cuda:9.0-devel`
my env.yaml looks like this:
```
name: cadd 
channels: 
- rdkit 
- conda-forge 
- openbabel 
- anaconda 
- mordred-descriptor 
dependencies: 
- h5py 
- xlrd 
- hdf5 
- python=3 
- rdkit 
- openbabel 
- yaml 
- seaborn 
- mordred
```
And my error looks like:
```
Solving environment: ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/opt/conda/lib/python3.7/site-packages/conda_env/installers/conda.py", line 35, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 246, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /opt/conda/bin/conda-env create -f /tmp/cadd_setup.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/opt/conda
          LD_LIBRARY_PATH=/usr/local/nvidia/lib:/usr/local/nvidia/lib64
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sb
                          in:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Linux/4.15.0-36-generic ubuntu/16.04 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```
I'm at a complete loss. Earlier, the exact same set of commands run just fine, producing images without any error.

**Comment by rentiak** [comment]
Looks like the same issue with upstream data as #7870

**Comment by weiji14** [comment]
@MeeMaster In the meantime, you can try changing your environment.yml to point to the `defaults` channel instead of `anaconda` so that it looks like below:

```
name: cadd 
channels: 
- rdkit 
- conda-forge 
- openbabel 
- defaults
- mordred-descriptor 
dependencies: 
- h5py 
- xlrd 
- hdf5 
- python=3 
- rdkit 
- openbabel 
- yaml 
- seaborn 
- mordred
```

I remember seeing somewhere that the `anaconda` channel was replaced/renamed/deprecated in favour of `defaults`, but a quick search only points me to this [blog post](https://www.anaconda.com/blog/company-blog/announcing-the-release-of-anaconda-distribution-5-0/) and this [anaconda 5.0 release note](http://docs.anaconda.com/anaconda/release-notes/#what-s-new-in-anaconda-5-0) which mentions the new channel.

**Comment by MeeMaster** [comment]
I later tried to set up the environment package by package, and I managed to do it.
So I checked the channels that were added, and it seems that in fact, the "anaconda" channel crashes the dependencies. So I guess this can be closed.
