### ISSUE TITLE
conda issues ?

### ISSUE THREAD

**Issue by teakian** [conda/conda#7874]
conda upgrade conda
Fetching package metadata ...........
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.20.0
         python version : 2.7.11.final.0
       requests version : 2.14.2
       root environment : /opt/cloudera/parcels/Anaconda  (writable)
    default environment : /opt/cloudera/parcels/Anaconda
       envs directories : /opt/cloudera/parcels/Anaconda/envs
                          /root/.conda/envs
          package cache : /opt/cloudera/parcels/Anaconda/pkgs
                          /root/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/2.7.11 Linux/2.6.32-573.22.1.el6.x86_64 CentOS/6.7 glibc/2.12
                UID:GID : 0:0

`$ /opt/cloudera/parcels/Anaconda/bin/conda upgrade conda`

    Traceback (most recent call last):
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 261, in install
        channel_priority_map=_channel_priority_map, is_update=isupdate)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/plan.py", line 489, in install_actions_list
        for specs_by_prefix in required_solves]
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/plan.py", line 631, in get_actions_for_dists
        pkgs = r.install(specs, installed, update_deps=update_deps)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 812, in install
        specs, preserve = self.install_specs(specs, installed or [], update_deps)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 793, in install_specs
        limit, preserve = self.bad_installed(installed, specs)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 771, in bad_installed
        for q in (C.from_index(s) for s in solution)
      File "/opt/cloudera/parcels/Anaconda/lib/python2.7/site-packages/conda/resolve.py", line 772, in <genexpr>
        if q and q[0] != '!' and '@' not in q)
    KeyError: Dist(_Dist__initd=True, channel=u'https://file', dist_name=u'linux-64-sas7bdat-2.0.7-py27_0', name=u'linux-64-sas7bdat', version=u'2.0.7', build_string=u'py27_0', build_number=0, with_features_depends=None, base_url=u'file:///', platform=u'linux-64')

**Comment by teakian** [comment]
nvm - updated linux-64-sas7bdat-2.0.7-py27_0 manually to 2.1.1xxx and it resolved.
