### ISSUE TITLE
Conda install fetch_index failing for all packages

### ISSUE THREAD

**Issue by GrierPhillips** [conda/conda#7875]
## Current Behavior

When trying to install any package `fetch_index` is failing as the info for some packages is not a dictionary as expected. See https://github.com/conda/conda/blob/4.1.6/conda/fetch.py#L303-L310. When there is no information for a given package a `TypeError` is raised and the install fails. In my case the first offending package is https://conda.anaconda.org/anaconda/linux-64/biopython-1.67-np111py27_0.tar.bz2. However, this package does have information available online at https://anaconda.org/anaconda/biopython/files?page=2 so I'm a little lost at to why conda install isn't getting the info.

### Steps to Reproduce

```
conda install pandas
```

## Expected Behavior

Package should be found and request permission to install.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Using Anaconda Cloud api site https://api.anaconda.org
Current conda install:

             platform : linux-64
        conda version : 4.1.6
    conda-env version : 2.5.1
  conda-build version : 1.21.3
       python version : 2.7.12.final.0
     requests version : 2.10.0
     root environment : /home/hdfsf4/anaconda2  (writable)
  default environment : /home/hdfsf4/anaconda2/envs/fdcorr
     envs directories : /home/hdfsf4/anaconda2/envs
        package cache : /home/hdfsf4/anaconda2/pkgs
         channel URLs : https://conda.anaconda.org/anaconda/linux-64/
                        https://conda.anaconda.org/anaconda/noarch/
                        https://repo.continuum.io/pkgs/free/linux-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/linux-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : /home/hdfsf4/.condarc
         offline mode : False
    is foreign system : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
 conda config --get
--set channel_alias https://conda.anaconda.org
--add channels 'defaults'   # lowest priority
--add channels 'anaconda'   # highest priority
--set ssl_verify False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
conda list --show-channel-urls
# packages in environment at /home/hdfsf4/anaconda2/envs/fdcorr:
#
libgcc-ng                 7.2.0                hdf63c60_3    anaconda
libstdcxx-ng              7.2.0                hdf63c60_3    anaconda
pandas                    0.22.0           py36hf484d3e_0    anaconda
argparse                  1.4.0                     <pip>
asn1crypto                0.24.0                    <pip>
attrs                     15.2.0                   py36_0    defaults
attrs                     18.1.0                    <pip>
automat                   0.5.0                    py36_0    defaults
Automat                   0.7.0                     <pip>
bitarray                  0.8.3                     <pip>
certifi                   2016.2.28                py36_0    defaults
cffi                      1.11.5                    <pip>
Click                     7.0                       <pip>
colorlog                  2.10.0                    <pip>
constantly                15.1.0                   py36_0    defaults
coverage                  4.4.1                    py36_0    defaults
coverage                  4.5.1                     <pip>
cryptography              2.3.1                     <pip>
decorator                 4.1.2                    py36_0    defaults
docopt                    0.6.2                     <pip>
docutils                  0.14                      <pip>
fdcorr                    4.0.0a0                   <pip>
future                    0.16.0                    <pip>
hs2client                 0.1.1                     <pip>
hyperlink                 17.1.1                   py36_0    defaults
idna                      2.7                       <pip>
impyla                    0.14.0                    <pip>
incremental               16.10.1                  py36_0    defaults
ipython                   6.1.0                    py36_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
jedi                      0.10.2                   py36_2    defaults
joblib                    0.12.2                    <pip>
libgfortran               3.0.0                         1    defaults
lockfile                  0.12.2                    <pip>
mkl                       2017.0.3                      0    defaults
more-itertools            4.1.0                     <pip>
nox-automation            0.19.0                    <pip>
numpy                     1.13.1                   py36_0    defaults
openssl                   1.0.2l                        0    defaults
path.py                   10.3.1                   py36_0    defaults
pexpect                   4.2.1                    py36_0    defaults
pickleshare               0.7.4                    py36_0    defaults
pip                       9.0.1                    py36_1    defaults
pluggy                    0.6.0                     <pip>
ply                       3.11                      <pip>
prompt_toolkit            1.0.15                   py36_0    defaults
protobuf                  3.5.2.post1               <pip>
ptyprocess                0.5.2                    py36_0    defaults
pure-sasl                 0.5.1                     <pip>
py                        1.4.34                   py36_0    defaults
py                        1.5.3                     <pip>
py4j                      0.10.4                    <pip>
py4j                      0.10.6                   py36_0    defaults
pycparser                 2.19                      <pip>
pygments                  2.2.0                    py36_0    defaults
pykerberos                1.2.1                     <pip>
pyodbc                    4.0.17                   py36_0    defaults
pyspark                   2.1.2                     <pip>
pyspark                   2.2.0                    py36_0    defaults
pytest                    3.2.1                    py36_0    defaults
pytest                    3.5.1                     <pip>
pytest-cov                2.5.1                     <pip>
python                    3.6.2                         0    defaults
python-daemon             2.2.0                     <pip>
python-dateutil           2.6.1                    py36_0    defaults
pytz                      2017.2                   py36_0    defaults
pywebhdfs                 0.4.1                     <pip>
readline                  6.2                           2    defaults
requests                  2.14.2                   py36_0    defaults
requests-kerberos         0.12.0                    <pip>
sasl                      0.2.1                     <pip>
scikit-learn              0.19.0              np113py36_0    defaults
scipy                     0.19.1              np113py36_0    defaults
setuptools                36.4.0                   py36_1    defaults
simplegeneric             0.8.1                    py36_1    defaults
six                       1.10.0                   py36_0    defaults
six                       1.11.0                    <pip>
sqlite                    3.13.0                        0    defaults
teradata                  15.10.0.21                <pip>
thrift                    0.11.0                    <pip>
thrift-sasl               0.2.1                     <pip>
thriftpy                  0.3.9                     <pip>
tk                        8.5.18                        0    defaults
traitlets                 4.3.2                    py36_0    defaults
twisted                   17.5.0                   py36_0    defaults
unixodbc                  2.3.4                         0    defaults
virtualenv                16.0.0                    <pip>
wcwidth                   0.1.7                    py36_0    defaults
wheel                     0.29.0                   py36_0    defaults
xz                        5.2.3                         0    defaults
zlib                      1.2.11                        0    defaults
zope                      1.0                      py36_0    defaults
zope.interface            4.4.2                    py36_0    defaults
```
</p></details>

**Comment by ssidorenko** [comment]
related to #7870

**Comment by vatsan** [comment]
What's the recommended fix/workaround here? I too am running into this issue with conda 4.5.9
The offending package for me was "bazel-0.11.1-hf484d3e_0.tar.bz2", whose "info" section is "null".

This seems to be happening only since the last two days, i am confused.
______
DEBUG conda.core.subdir_data:_read_local_repdata(266): Loading raw json for https://conda.anaconda.org/anaconda/linux-64 at /home/user/pkgs/cache/c484148c.json
failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 108, in execute
        installer.install(prefix, pkg_specs, args, env)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda_env/installers/conda.py", line 35, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 218, in _load
        mod_etag_headers.get('_mod'))
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/usr/local/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 370, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /usr/local/anaconda3/bin/conda-env create -f requirements.yml --force --debug`
______

**Comment by vatsan** [comment]
In case anyone else is interested, the workaround for me was to remove "anaconda" from my channels in the requirements.yml file. "conda-forge" and "defaults" take care of the dependencies.

**Comment by mingwandroid** [comment]
To real pay myself for the hundredth time!

No one should ever use the anaconda channel. We have never suggested that anyone use this channel and I have no idea why people to.

**Comment by mingwandroid** [comment]
> Could you point me to some resource on why we shouldn't use the anaconda channel?

We have never documented that it should be used AFAIK. We don't put negative documentation out around which channels to avoid. Yes it's a shame that the name matches with our company name and that people therefore seem to have randomly decided to use it presumably just because they found it and "anaconda==anaconda". The problem is they then write issues such as this one with this incorrect `-c anaconda` text in it and people see that without reading qualifying comments such as this and so this misinformation propagates.

I don't see that there's much we can do to prevent this. Suggestions are welcome. Maybe some messages in the installers, but I hate that it would have to come to that. Where does that course of action end?

The thing is, there's no reason at all to specify `-c anaconda` since `defaults` in already in your `~/.condarc` (unless you removed it for some reason).

To give the techincal issues around this (intended for internal-use only) `anaconda` channel, it aggregates all of the legacy `free` channel with the new `main` channel in a way that ignores channel priorities (for there is only one `anaconda` channel). The `defaults` channel is a metachannel the defintion of which `conda` is in charge of. The solver is then prone to install old packages you definitely do not want at this point.

**Comment by mingwandroid** [comment]
> because I couldn't find it anywhere else

Everything on anaconda is also in defaults. If you're trying to install something really old into an enviornment where channel priorities and package pinning conspire to prevent this you are best off finding that package elsewhere or building it from source because installing that old package from `free` is unlikely to result in a happy experience (depending on which package it is, pure-python will be ok, things that need compilation, probably less so).

We've been making sure that packages that are currently only in `free` are updated (if applicable) rebuilt and added to `main`, however these tend to be *very* old packages and I'd be surprised if anyone was still using them.

**Comment by solalsabbah** [comment]
> I must repeat myself for the Nth time!
> 
> No one should ever use the anaconda channel. We have never suggested or documented that anyone use it and I have no idea why people do!
> 
> Can anyone commenting here point to where you read to use this channel. I need to correct it if possible.

Hello @mingwandroid  I don't get it. On official link they say to use anaconda channel 
I also have issue recently installing with conda 

https://anaconda.org/anaconda/postgresql

**Comment by mingwandroid** [comment]
It's a website. It's not documentation, clearly.

**Comment by upandacross** [comment]
@mingwandroid, if I see https://anaconda.org, I make a huge assumption that this is the official anaconda source for installation instructions among other things. On the other hand, I could believe you rather than my lyin' eyes.
