### ISSUE TITLE
UnicodeEncodeError while activating environments (started with Cython install)

### ISSUE THREAD

**Issue by chaturv3di** [conda/conda#7876]
## Current Behavior

I created a new environment and installed a bunch of packages, and started to run into this error as soon as I installed Cython.

```shell
Downloading and Extracting Packages
cython-0.29          | 2.1 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/namit/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 98, in main
        return activator_main()
      File "/Users/namit/anaconda3/lib/python3.6/site-packages/conda/activate.py", line 632, in main
        print(activator.execute(), end='')
    UnicodeEncodeError: 'ascii' codec can't encode character '\u2718' in position 66: ordinal not in range(128)

`$ /Users/namit/anaconda3/bin/conda shell.posix reactivate`
```
However, Cython is successfully installed. Without closing the shell, I could even install more packages like numpy, pandas etc. I get the same error after each installation but the package is successfully installed. I can verify this by importing the package and doing some elementary stuff. But essentially, conda is having trouble reactivating the environment.

In a new shell terminal, I cannot activate any environment. The command `conda activate my_env` fails for all the environments that I have and produces the same error report [pasted in full in the Expected Behaviour section below].

### Steps to Reproduce

FWIW, these are the contents of my `.condarc`.
```shell
channels:
  - anaconda
  - defaults
  - conda-forge

channel_priority: True

update_dependencies: False
```
I had created a new environment with `python=3.6`. This is the exact order of installation of packages.

```shell
# Elpy related
conda install jedi
conda install -c anaconda flake8
conda install autopep8
conda install yapf

# Add env to Jupyter
conda install -c anaconda ipykernel
python -m ipykernel install --user --name $env_name --display-name "Python3.6 ($env_name)"

# Finally
conda install cython
```

## Expected Behavior

You should see this.

```shell
$ conda install cython
Solving environment: done

## Package Plan ##

  environment location: /Users/namit/anaconda3/envs/hdbscan

  added / updated specs: 
    - cython


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cython-0.29                |   py36h0a44026_0         2.1 MB  anaconda

The following NEW packages will be INSTALLED:

    cython: 0.29-py36h0a44026_0 anaconda

Proceed ([y]/n)? 


Downloading and Extracting Packages
cython-0.29          | 2.1 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/namit/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 98, in main
        return activator_main()
      File "/Users/namit/anaconda3/lib/python3.6/site-packages/conda/activate.py", line 632, in main
        print(activator.execute(), end='')
    UnicodeEncodeError: 'ascii' codec can't encode character '\u2718' in position 66: ordinal not in range(128)

`$ /Users/namit/anaconda3/bin/conda shell.posix reactivate`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=hdbscan
                CONDA_EXE=/Users/namit/anaconda3/bin/conda
             CONDA_PREFIX=/Users/namit/anaconda3/envs/hdbscan
           CONDA_PREFIX_1=/Users/namit/anaconda3
    CONDA_PROMPT_MODIFIER=(hdbscan)
         CONDA_PYTHON_EXE=/Users/namit/anaconda3/bin/python
               CONDA_ROOT=/Users/namit/anaconda3
              CONDA_SHLVL=2
                     PATH=/Users/namit/anaconda3/envs/hdbscan/bin:/usr/local/git/bin:/Users/nami
                          t/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/
                          TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : hdbscan
    active env location : /Users/namit/anaconda3/envs/hdbscan
            shell level : 2
       user config file : /Users/namit/.condarc
 populated config files : /Users/namit/.condarc
          conda version : 4.5.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /Users/namit/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/osx-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/namit/anaconda3/pkgs
                          /Users/namit/.conda/pkgs
       envs directories : /Users/namit/anaconda3/envs
                          /Users/namit/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```
Without closing the shell, you should be able to install and use new packages albeit with the same error message every time. 

In a new shell, you will be unable to activate any environment, as is clear from exact source of the error.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : hdbscan
    active env location : /Users/namit/anaconda3/envs/hdbscan
            shell level : 2
       user config file : /Users/namit/.condarc
 populated config files : /Users/namit/.condarc
          conda version : 4.5.11
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : /Users/namit/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/osx-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/namit/anaconda3/pkgs
                          /Users/namit/.conda/pkgs
       envs directories : /Users/namit/anaconda3/envs
                          /Users/namit/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.3 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/namit/.condarc <==
channel_priority: True
channels:
  - anaconda
  - defaults
  - conda-forge
update_dependencies: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/namit/anaconda3/envs/hdbscan:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0            py36hf537a9a_0    anaconda
autopep8                  1.4                      py36_0    anaconda
backcall                  0.1.0                    py36_0    anaconda
blas                      1.0                         mkl    anaconda
ca-certificates           2018.03.07                    0    anaconda
certifi                   2018.10.15               py36_0    anaconda
cython                    0.29             py36h0a44026_0    anaconda
decorator                 4.3.0                    py36_0    anaconda
flake8                    3.5.0                    py36_1    anaconda
intel-openmp              2019.0                      118    anaconda
ipykernel                 5.0.0            py36h39e3cac_0    anaconda
ipython                   7.0.1            py36h39e3cac_0    anaconda
ipython_genutils          0.2.0            py36h241746c_0    anaconda
jedi                      0.13.1                   py36_0    defaults
jupyter_client            5.2.3                    py36_0    anaconda
jupyter_core              4.4.0                    py36_0    anaconda
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    anaconda
libsodium                 1.0.16               h3efe00b_0    anaconda
mccabe                    0.6.1                    py36_1    anaconda
mkl                       2019.0                      118    anaconda
mkl_fft                   1.0.6            py36hb8a8100_0    anaconda
mkl_random                1.0.1            py36h5d10147_1    anaconda
ncurses                   6.1                  h0a44026_0    defaults
numpy                     1.15.2           py36h6a91979_1    anaconda
numpy-base                1.15.2           py36h8a80b8c_1    anaconda
openssl                   1.0.2p               h1de35cc_0    anaconda
pandas                    0.23.4           py36h6440ff4_0    anaconda
parso                     0.3.1                    py36_0    defaults
pexpect                   4.6.0                    py36_0    anaconda
pickleshare               0.7.5                    py36_0    anaconda
pip                       10.0.1                   py36_0    defaults
prompt_toolkit            2.0.6                    py36_0    anaconda
ptyprocess                0.6.0                    py36_0    anaconda
pycodestyle               2.3.1            py36h83e8646_0    anaconda
pyflakes                  1.6.0            py36hea45e83_0    anaconda
pygments                  2.2.0            py36h240cd3f_0    anaconda
python                    3.6.6                hc167b69_0    defaults
python-dateutil           2.7.3                    py36_0    anaconda
pytz                      2018.5                   py36_0    anaconda
pyzmq                     17.1.2           py36h1de35cc_0    anaconda
readline                  7.0                  h1de35cc_5    defaults
setuptools                40.4.3                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    anaconda
six                       1.11.0                   py36_1    anaconda
sqlite                    3.25.2               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tornado                   5.1.1            py36h1de35cc_0    anaconda
traitlets                 4.3.2            py36h65bd3ce_0    anaconda
wcwidth                   0.1.7            py36h8c6ec74_0    anaconda
wheel                     0.32.1                   py36_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yapf                      0.24.0                   py36_0    anaconda
zeromq                    4.2.5                h0a44026_1    anaconda
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

**Comment by mingwandroid** [comment]
Why have you added anaconda to your channels list? No one should do that, the correct (meta-)channel is called defaults which you also have anyway.

**Comment by chaturv3di** [comment]
Ignorance. Thanks for calling that out. I'll remove that, but that seems to be just a misconfiguration. Do you believe that that's what is causing this problem?

**Comment by chaturv3di** [comment]
Okay, I figured out what's creating this problem. The offending characters, `\u2714` and `\u2718`, that are causing the UnicodeEncodeErrors come from my bash git-prompt. These are the "heavy checkmark" and the "heavy ballot box X" characters. E.g.
<img width="608" alt="screen shot 2018-10-20 at 1 08 57 pm" src="https://user-images.githubusercontent.com/22843902/47252904-8d2d2200-d469-11e8-91da-0e54dd9efe32.png">
and
<img width="599" alt="screen shot 2018-10-20 at 1 09 47 pm" src="https://user-images.githubusercontent.com/22843902/47252905-95855d00-d469-11e8-82ed-220a80d3d788.png">

So it seems that `activate.py` is reading the entire prompt and crashing out on these non-ascii characters. Apart from disabling git-prompt, which I really like, what are the options?

**Comment by mingwandroid** [comment]
I've sourced git-prompt and changed PS1,  but I cannot seem to get the fancy ticks etc when using `Terminal`. Do I need to use something fancier to reproduce this?

**Comment by chaturv3di** [comment]
I've added this in my `.bash_profile`

```shell
# Git-bash-prompt
GIT_PROMPT_ONLY_IN_REPO=1
if [ -f "/usr/local/opt/bash-git-prompt/share/gitprompt.sh" ]; then
  __GIT_PROMPT_DIR="/usr/local/opt/bash-git-prompt/share"
  source "/usr/local/opt/bash-git-prompt/share/gitprompt.sh"
fi
```

**Comment by philippjfr** [comment]
I'm currently in a sprint with a few people and just saw the same error (with a different character) in someone's PyCharm terminal, specifically it was erroring on https://www.fileformat.info/info/unicode/char/231a/index.htm

**Comment by LANRRI** [comment]
so，anyone solved this problem？ i've met this problem yesterday...

**Comment by IanStokesRees-Zoetis** [comment]
git-bash on Windows + Powerline causes this.

**Comment by boaarmpit** [comment]
Conda 4.9.2  with Powerlevel10k for zsh on mac also has this issue. Setting [changeps1](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#change-command-prompt) to `False` as suggested [here](https://github.com/conda/conda/issues/3982#issuecomment-425672922) solved the issue for me. Powerlevel10k still displays the conda environment name.

**Comment by Ka-lip** [comment]
> Conda 4.9.2 with Powerlevel10k for zsh on mac also has this issue. Setting [changeps1](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#change-command-prompt) to `False` as suggested [here](https://github.com/conda/conda/issues/3982#issuecomment-425672922) solved the issue for me. Powerlevel10k still displays the conda environment name.

This way solved my problem.

**Comment by morags** [comment]
On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.

**Comment by browneye1826** [comment]
> On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.

How do I do that please Morag?

**Comment by browneye1826** [comment]
> > On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.
> 
> How do I do that please Morag?

![New System Variable   Environment Variables   1 2022-02-01 at 1 37 22 PM py - lo1 - Visual Studio Code](https://user-images.githubusercontent.com/59311049/152030278-c191f8cf-caea-4cc8-9424-458fadec56a6.jpeg)
Like this, right?

**Comment by morags** [comment]
Exactly. Did it work?

**Comment by browneye1826** [comment]
> Exactly. Did it work?

It did! Thanks so much. You are the best :)

**Comment by ArkURL** [comment]
> On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.

That solved my problem, thanks!

**Comment by AgeeLuo** [comment]
Thanks, it also solved my problem TOT!

**Comment by sdhutchins** [comment]
> Conda 4.9.2 with Powerlevel10k for zsh on mac also has this issue. Setting [changeps1](https://conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html#change-command-prompt) to `False` as suggested [here](https://github.com/conda/conda/issues/3982#issuecomment-425672922) solved the issue for me. Powerlevel10k still displays the conda environment name.

Currently having this issue on my mac, but this command did not help.

**Comment by rebornsick** [comment]
> On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.

OMG YOU ARE MY HERO! My problem is similar. When I set it to `utf_8_sig` , powershell shows new errors, so I set it to `uft_8` and fixed perfectly!

**Comment by okdewit** [comment]
Not stale. 

Using macOS, conda 23.7.4.
Using a Unicode emoji in my PS1.

`source ~/anaconda3/bin/activate` displayed same error as original post.
I resolved this by removing the emoji from my prompt, but I think that's a workaround and this contingency should ideally be accounted for in conda itself, as it's not exactly uncommon to use unicode in PS1 these days.

**Comment by enteryfx** [comment]
> On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.

After I do this , a new issue is coming .
![image](https://github.com/conda/conda/assets/100504675/05246a79-ad42-4020-aefb-3b4d4375c1b8)
Could you tell me how to solve this problem?

**Comment by duan-hong-yi** [comment]
> > On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.
> 
> OMG YOU ARE MY HERO! My problem is similar. When I set it to `utf_8_sig` , powershell shows new errors, so I set it to `uft_8` and fixed perfectly!

peak

**Comment by satyrmipt** [comment]
> On Windows, setting an environment variable `PYTHONIOENCODING` to `utf_8_sig` solves it.

Still solves the problem in 2025.
