### ISSUE TITLE
Unable to create conda env in pycharm

### ISSUE THREAD

**Issue by Poonamjo** [conda/conda#7901]
Executed command:
Conda C:\Program Files\Anaconda3\Scripts\conda.exe create -p C:\Program Files\Anaconda3\envs\TensorFlow -y python=3.5

Error occurred:

Invalid data stream

Command Output:
Fetching package metadata ...
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\Program Files\Anaconda3  (read only)
    default environment : C:\Program Files\Anaconda3
       envs directories : C:\Users\555374\.conda\envs
                          C:\Program Files\Anaconda3\envs
          package cache : C:\Users\555374\.conda\envs\.pkgs
                          C:\Program Files\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\555374\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063

`$ C:\Program Files\Anaconda3\Scripts\conda-script.py create -p C:\Program Files\Anaconda3\envs\TensorFlow -y python=3.5`

    Traceback (most recent call last):
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 385, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 203, in fetch_repodata_remote_request
        json_str = maybe_decompress(filename, resp.content)
      File "C:\Program Files\Anaconda3\lib\site-packages\conda\core\index.py", line 201, in maybe_decompress
        if filename.endswith('.bz2')
      File "C:\Program Files\Anaconda3\lib\bz2.py", line 350, in decompress
        res = decomp.decompress(data)
    OSError: Invalid data stream

Please help to resolve this asap

**Comment by swayson** [comment]
I get the same error. Other colleagues of mine get the same error.
