### ISSUE TITLE
Error report when creating environment from yams file

### ISSUE THREAD

**Issue by Mahmoudhallal** [conda/conda#7908]
This is used to create an environment for snakemake, I can create the environment but I am unable to add the yams file:

## Current Behaviour
```

conda env create --name snakemake_General4 --file environment.yaml
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda_env/cli/main_create.py", line 79, in execute
        directory=os.getcwd())
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda_env/specs/__init__.py", line 20, in detect
        if spec.can_handle():
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda_env/specs/yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda_env/env.py", line 84, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda_env/env.py", line 72, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/conda/common/serialize.py", line 74, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 194, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/composer.py", line 106, in compose_node
        if self.parser.check_event(AliasEvent):
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 144, in check_event
        self.current_event = self.state()
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/parser.py", line 577, in parse_block_mapping_value
        if self.scanner.check_token(ValueToken):
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 160, in check_token
        self.fetch_more_tokens()
      File "/Users/Mahmoud.Hallal/miniconda3/lib/python3.7/site-packages/ruamel_yaml/scanner.py", line 310, in fetch_more_tokens
        % utf8(ch), self.reader.get_mark())
    ruamel_yaml.scanner.ScannerError: while scanning for the next token
    found character '\t' that cannot start any token
      in "<unicode string>", line 2, column 1:
        	- conda-forge
        ^ (line: 2)

`$ /Users/Mahmoud.Hallal/miniconda3/bin/conda-env create --name snakemake_General4 --file=environment.yaml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/Users/Mahmoud.Hallal/miniconda3
              CONDA_SHLVL=0
                     PATH=/Users/Mahmoud.Hallal/miniconda3/bin:/Users/Mahmoud.Hallal/miniconda3/
                          bin:/Library/Frameworks/R.framework/Resources:/usr/local/opt/libxml2/b
                          in:/usr/local/ncbi/blast/bin:/Library/Frameworks/Python.framework/Vers
                          ions/2.7/bin:/Users/Mahmoud.Hallal/miniconda3/bin:/Users/Mahmoud.Halla
                          l/.rbenv/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/
                          sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr
                          /local/Cellar/openssl/1.0.2j/bin/openssl  #add colors to terminal
                          #PS1=[u@h
          PKG_CONFIG_PATH=/usr/local/opt/libxml2/lib/pkgconfig
                   PYTHON=/Library/Frameworks/Python.framework/Versions/3.5/bin:/opt/local/bin:/
                          opt/local/sbin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:
                          /sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/Mahmoud.Hallal/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /Users/Mahmoud.Hallal/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/Mahmoud.Hallal/miniconda3/pkgs
                          /Users/Mahmoud.Hallal/.conda/pkgs
       envs directories : /Users/Mahmoud.Hallal/miniconda3/envs
                          /Users/Mahmoud.Hallal/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.


```

## Expected Behaviour
A normal environment with the packages

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : None
            shell level : 0
       user config file : /Users/Mahmoud.Hallal/.condarc
 populated config files : 
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : /Users/Mahmoud.Hallal/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /Users/Mahmoud.Hallal/miniconda3/pkgs
                          /Users/Mahmoud.Hallal/.conda/pkgs
       envs directories : /Users/Mahmoud.Hallal/miniconda3/envs
                          /Users/Mahmoud.Hallal/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Darwin/15.6.0 OSX/10.11.6
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
empty
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.8.24                py37_1    defaults
cffi                      1.11.5           py37h6174b99_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.5.11                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.3.1            py37hdbc3d79_0    defaults
idna                      2.7                      py37_0    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.1                  h0a44026_0    defaults
openssl                   1.0.2p               h1de35cc_0    defaults
pip                       10.0.1                   py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.18                     py37_1    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.0                hc167b69_0    defaults
python.app                2                        py37_8    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.19.1                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
setuptools                40.2.0                   py37_0    defaults
six                       1.11.0                   py37_1    defaults
sqlite                    3.24.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
urllib3                   1.23                     py37_0    defaults
wheel                     0.31.1                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults

```
</p></details>

**Comment by JapinderSandhu** [comment]
im having the same problem

**Comment by kenodegard** [comment]
Unfortunately, we will need to see the `environment.yaml` file that caused this error in order to debug this. I will close this given the age of this ticket. Please open a new issue with the applicable information if this occurs again.

**Comment by pajucon** [comment]
```
    found character '\t' that cannot start any token
      in "<unicode string>", line 2, column 1:
        	- conda-forge
        ^ (line: 2)

```
I had this error when creating a environment.yaml from a sessionInfo() dump. I was using '\t' for formatting the .yaml. 

Changing all '\t' (tabs)  to "  " (two spaces) resolved the issue.
