### ISSUE TITLE
Unable to install cudatoolkit in miniconda environment

### ISSUE THREAD

**Issue by priftisg** [conda/conda#7912]
I have an error report when I am trying to install the cudatoolkit on a  linux machine under Miniconda3.

(dsig) [gpriftis@matrix ~]$ conda install -n dsig -c anaconda cudatoolkit
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 227, in _load
        mod_etag_headers.get('_mod'))
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 574, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 233, in _load
        mod_etag_headers.get('_mod'))
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/rhome/gpriftis/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

`$ /rhome/gpriftis/miniconda3/bin/conda install -n dsig -c anaconda cudatoolkit`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=dsig
                CONDA_EXE=/rhome/gpriftis/miniconda3/bin/conda
             CONDA_PREFIX=/rhome/gpriftis/miniconda3/envs/dsig
    CONDA_PROMPT_MODIFIER=(dsig)
         CONDA_PYTHON_EXE=/rhome/gpriftis/miniconda3/bin/python
               CONDA_ROOT=/rhome/gpriftis/miniconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/rhome/gpriftis/gsl/lib:/common/pkgs/ncl_ncarg/v6.3_mpi-
                          pgi16.3_gcc_EL7/lib:/common/pkgs/netcdf/v4.4-f4.4.4-cxx4.2_mpi-
                          pgi16.3_gcc_EL7/lib:/common/pkgs/hdf4/v2.11_mpi-pgi16.3_gcc_EL7/lib:/c
                          ommon/pkgs/pgi/linux86-64/16.3/lib:/common/pkgs/itt/idl85/bin/bin.linu
                          x.x86_64/
              LD_RUN_PATH=/common/pkgs/itt/idl85/bin/bin.linux.x86_64/
                  MANPATH=/common/pkgs/ncl_ncarg/v6.3_mpi-
                          pgi16.3_gcc_EL7/man:/common/pkgs/netcdf/v4.4-f4.4.4-cxx4.2_mpi-
                          pgi16.3_gcc_EL7/share/man:/common/pkgs/hdf4/v2.11_mpi-pgi16.3_gcc_EL7/
                          share/man:/common/pkgs/mpich2/3.2-pgi16.3-gcc/share/man:/common/pkgs/p
                          gi/linux86-64/16.3/man:/common/pkgs/itt/idl85/man:/usr/local/share/man
                          :/usr/share/man/overrides:/usr/share/man
               MODULEPATH=/common/Env_Modules/EL7/Modules/versions:/common/Env_Modules/EL7/Modul
                          es/$MODULE_VERSION/modulefiles:/common/Env_Modules/EL7/Modules/modulef
                          iles
               MPICH_PATH=/common/pkgs/mpich2/3.2-pgi16.3-gcc
                     PATH=/rhome/gpriftis/miniconda3/envs/dsig/bin:/rhome/gpriftis/gsl/bin:/nas/
                          rhome/gpriftis/ASCAT_UHR2/uhr:/nas/rhome/gpriftis/linuxbrew/.linuxbrew
                          /bin:/rhome/gpriftis/bck/models/BoxModel/boxmox/bin:/rhome/gpriftis/bc
                          k/models/BoxModel/boxmox/boxmox/bin:/common/pkgs/solo3/20140219-EL6/bi
                          n:/rhome/gpriftis/bin:/common/pkgs/ncl_ncarg/v6.3_mpi-
                          pgi16.3_gcc_EL7/bin:/common/pkgs/netcdf/v4.4-f4.4.4-cxx4.2_mpi-
                          pgi16.3_gcc_EL7/bin:/common/pkgs/hdf5/v1.8.17_mpi-
                          pgi16.3_gcc_EL7/bin:/common/pkgs/hdf4/v2.11_mpi-pgi16.3_gcc_EL7/bin:/c
                          ommon/pkgs/mpich2/3.2-pgi16.3-gcc/bin:/common/pkgs/pgi/linux86-64/16.3
                          /bin:/common/pkgs/itt/idl85/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/
                          usr/bin:/common/pkgs/uahcommon/bin:/usr/X11R6/bin:/usr/local/sbin:/usr
                          /sbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            UDUNITS2_PATH=/common/pkgs/ncl_ncarg/v6.3_mpi-pgi16.3_gcc_EL7

     active environment : dsig
    active env location : /rhome/gpriftis/miniconda3/envs/dsig
            shell level : 1
       user config file : /rhome/gpriftis/.condarc
 populated config files : /rhome/gpriftis/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /rhome/gpriftis/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /rhome/gpriftis/miniconda3/pkgs
                          /rhome/gpriftis/.conda/pkgs
       envs directories : /rhome/gpriftis/miniconda3/envs
                          /rhome/gpriftis/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.0 CPython/3.6.6 Linux/3.10.0-862.9.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 3802:3802
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

Any suggestions concerning the error?
Thank you.

**Comment by mingwandroid** [comment]
Why have you used -c anaconda?
