### ISSUE TITLE
Repeated downgrades/upgrades of numpy result in broken numpy

### ISSUE THREAD

**Issue by mwcraig** [conda/conda#7913]
## Current Behavior

Repeated upgrade/downgrade of numpy results in a broken numpy install. More details are in the steps to reproduce below, but an example of a command that fails is `python -c "import numpy as np; print(np.__version__); np.integer"` which results in (after the odd sequence of upgrade/downgrade below)

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'numpy' has no attribute '__version__'
```

### Steps to Reproduce

Run this (admittedly convoluted) set of commands:

```
conda create -n oh-no --yes numpy=1.15.2
conda activate oh-no
python -c "import numpy as np; print(np.__version__)"
conda install --yes numpy=1.13
python -c "import numpy as np; print(np.__version__)"
conda install --yes numpy=1.15.2
python -c "import numpy as np; print(np.__version__)"
conda install --yes numpy=1.13
python -c "import numpy as np; print(np.__version__)"
conda install --yes numpy=1.15.2
python -c "import numpy as np; print(np.__version__)"
```

and you eventually get, from the last statement:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'numpy' has no attribute '__version__'
```

All of the earlier `python -c...` print the numpy version as expected.

The full terminal session is at the bottom of this report. Note that there is one really odd bit along the way. At the first `conda install --yes numpy=1.13`, which forces a change in python version from 3.7 to 3.6,  the package `numpy-base` is changed like this:

```
numpy-base: 1.15.2-py37h8a80b8c_1 --> 1.15.3-py36h8a80b8c_0
```

which is odd, since numpy 1.13 is being installed.

## Expected Behavior

The output of `python -c "import numpy as np; print(np.__version__); np.integer"` after the last of the steps to reproduce should be `1.15.2`.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : oh-no
    active env location : /Users/mattcraig/anaconda3/anaconda/envs/oh-no
            shell level : 1
       user config file : /Users/mattcraig/.condarc
 populated config files : /Users/mattcraig/.condarc
          conda version : 4.5.11
    conda-build version : 3.2.0
         python version : 3.6.3.final.0
       base environment : /Users/mattcraig/anaconda3/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/osx-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/osx-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/astropy/osx-64
                          https://conda.anaconda.org/astropy/noarch
          package cache : /Users/mattcraig/anaconda3/anaconda/pkgs
                          /Users/mattcraig/.conda/pkgs
       envs directories : /Users/mattcraig/anaconda3/anaconda/envs
                          /Users/mattcraig/.conda/envs
               platform : osx-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/3.6.3 Darwin/18.0.0 OSX/10.14
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/mattcraig/.condarc <==
ssl_verify: True
channels:
  - anaconda-fusion
  - defaults
  - conda-forge
  - astropy
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/mattcraig/anaconda3/anaconda/envs/oh-no:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.10.15               py36_0    defaults
intel-openmp              2019.0                      118    defaults
libcxx                    4.0.1                h579ed51_0    defaults
libcxxabi                 4.0.1                hebd6815_0    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
mkl                       2019.0                      118    defaults
mkl_fft                   1.0.6            py36hb8a8100_0    defaults
mkl_random                1.0.1            py36h5d10147_1    defaults
ncurses                   6.1                  h0a44026_0    defaults
numpy                     1.15.2           py36h6a91979_1    defaults
numpy-base                1.15.2           py36h8a80b8c_1    defaults
openssl                   1.1.1                h1de35cc_0    defaults
pip                       10.0.1                   py36_0    defaults
python                    3.6.7                haf84260_0    defaults
readline                  7.0                  h1de35cc_5    defaults
setuptools                40.4.3                   py36_0    defaults
sqlite                    3.25.2               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
wheel                     0.32.2                   py36_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
zlib                      1.2.11               hf3cbc9b_2    defaults
```
</p></details>

#### Really long terminal output from running the steps to reproduce

```shell
~/d/astronomy $ conda create -n oh-no --yes numpy=1.15.2
Solving environment: done

## Package Plan ##

  environment location: /Users/mattcraig/anaconda3/anaconda/envs/oh-no

  added / updated specs:
    - numpy=1.15.2


The following NEW packages will be INSTALLED:

    blas:            1.0-mkl
    ca-certificates: 2018.03.07-0
    certifi:         2018.10.15-py37_0
    intel-openmp:    2019.0-118
    libcxx:          4.0.1-h579ed51_0
    libcxxabi:       4.0.1-hebd6815_0
    libedit:         3.1.20170329-hb402a30_2
    libffi:          3.2.1-h475c297_4
    libgfortran:     3.0.1-h93005f0_2
    mkl:             2019.0-118
    mkl_fft:         1.0.6-py37hb8a8100_0
    mkl_random:      1.0.1-py37h5d10147_1
    ncurses:         6.1-h0a44026_0
    numpy:           1.15.2-py37h6a91979_1
    numpy-base:      1.15.2-py37h8a80b8c_1
    openssl:         1.1.1-h1de35cc_0
    pip:             10.0.1-py37_0
    python:          3.7.1-haf84260_3
    readline:        7.0-h1de35cc_5
    setuptools:      40.4.3-py37_0
    sqlite:          3.25.2-ha441bb4_0
    tk:              8.6.8-ha441bb4_0
    wheel:           0.32.2-py37_0
    xz:              5.2.4-h1de35cc_4
    zlib:            1.2.11-hf3cbc9b_2

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate oh-no
#
# To deactivate an active environment, use
#
#     $ conda deactivate

~/d/astronomy $ conda activate oh-no
~/d/astronomy $ python -c "import numpy as np; print(np.__version__)"                                                                                               (oh-no)
1.15.2
~/d/astronomy $ conda install --yes numpy=1.13                                                                                                                      (oh-no)
Solving environment: done

## Package Plan ##

  environment location: /Users/mattcraig/anaconda3/anaconda/envs/oh-no

  added / updated specs:
    - numpy=1.13


The following packages will be UPDATED:

    certifi:    2018.10.15-py37_0     --> 2018.10.15-py36_0
    mkl_fft:    1.0.6-py37hb8a8100_0  --> 1.0.6-py36hb8a8100_0
    mkl_random: 1.0.1-py37h5d10147_1  --> 1.0.1-py36h5d10147_1
    numpy-base: 1.15.2-py37h8a80b8c_1 --> 1.15.3-py36h8a80b8c_0
    pip:        10.0.1-py37_0         --> 10.0.1-py36_0
    setuptools: 40.4.3-py37_0         --> 40.4.3-py36_0
    wheel:      0.32.2-py37_0         --> 0.32.2-py36_0

The following packages will be DOWNGRADED:

    numpy:      1.15.2-py37h6a91979_1 --> 1.13.3-py36ha9ae307_4
    python:     3.7.1-haf84260_3      --> 3.6.7-haf84260_0

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
~/d/astronomy $ python -c "import numpy as np; print(np.__version__)"                                                                                               (oh-no)
1.13.3
~/d/astronomy $ conda install --yes numpy=1.15.2                                                                                                                    (oh-no)
Solving environment: done

## Package Plan ##

  environment location: /Users/mattcraig/anaconda3/anaconda/envs/oh-no

  added / updated specs:
    - numpy=1.15.2


The following packages will be UPDATED:

    numpy:      1.13.3-py36ha9ae307_4 --> 1.15.2-py36h6a91979_1

The following packages will be DOWNGRADED:

    numpy-base: 1.15.3-py36h8a80b8c_0 --> 1.15.2-py36h8a80b8c_1

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
~/d/astronomy $ python -c "import numpy as np; print(np.__version__)"                                                                                               (oh-no)
1.15.2
~/d/astronomy $ conda install --yes numpy=1.13                                                                                                                      (oh-no)
Solving environment: done

## Package Plan ##

  environment location: /Users/mattcraig/anaconda3/anaconda/envs/oh-no

  added / updated specs:
    - numpy=1.13


The following packages will be DOWNGRADED:

    numpy: 1.15.2-py36h6a91979_1 --> 1.13.3-py36ha9ae307_4

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
~/d/astronomy $ python -c "import numpy as np; print(np.__version__)"                                                                                               (oh-no)
1.13.3
~/d/astronomy $ conda install --yes numpy=1.15.2                                                                                                                    (oh-no)
Solving environment: done

## Package Plan ##

  environment location: /Users/mattcraig/anaconda3/anaconda/envs/oh-no

  added / updated specs:
    - numpy=1.15.2


The following packages will be UPDATED:

    numpy: 1.13.3-py36ha9ae307_4 --> 1.15.2-py36h6a91979_1

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
~/d/astronomy $ python -c "import numpy as np; print(np.__version__)"                                                                                               (oh-no)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'numpy' has no attribute '__version__'
```

**Comment by mwcraig** [comment]
FWIW, running this fixes the environment (in the sense that the numpy version is printed afterwards): `conda install --force numpy-base=1.15.2`
