### ISSUE TITLE
conda install ripgrep triggers auxlib ValidationError on None version

### ISSUE THREAD

**Issue by msarahan** [conda/conda#7914]
conda 4.6.0b1

I suspect that ripgrep is a little "special" because it is in an somewhat odd namespace situation.

```
    Traceback (most recent call last):
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 21, in execute
        install(args, parser, 'install')
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 250, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
        force_remove, force_reinstall)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 145, in solve_for_diff
        force_remove)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 206, in solve_final_state
        self.prefix, update_modifier, deps_modifier, prune, ignore_pinned, force_remove
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 729, in __init__
        self.solution_precs = tuple(self.prefix_data.iter_records())
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 115, in iter_records
        return itervalues(self._prefix_records)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 144, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 68, in load
        self._load_site_packages()
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 257, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 298, in read_python_record
        constrains=constrains,
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 736, in __init__
        setattr(self, key, kwargs[key])
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 427, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, instance.__class__, val))
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 470, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for version cannot be None.
```

**Comment by mingwandroid** [comment]
Very odd. Any clue as to why it thinks its different from other packages? Do we have any special casing for rust already?

**Comment by jjhelmus** [comment]
I'm not able to replicate this on `linux-64` or `osx-64` using the current master, 4.6.0b1.post6+95a1d48) or 4.6.0b1.

```
$ conda install -n test_ripgrep ripgrep
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/workspace/conda/devenv/envs/test_ripgrep

  added / updated specs:
    - ripgrep


The following NEW packages will be INSTALLED:

  ripgrep            pkgs/main/linux-64::ripgrep-0.10.0-hc07d326_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
@msarahan Can you try replicating this and see if it is still an issue?

**Comment by kalefranz** [comment]
This stack trace is coming through `PrefixData`

```
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 257, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
```

I suspect there's a corrupt json file in the target environment's `conda-meta` directory where the `version` key got dropped somehow?
