### ISSUE TITLE
conda install -c anaconda  raise Response304ContentUnchanged()

### ISSUE THREAD

**Issue by yafeng** [conda/conda#7915]
### Steps to Reproduce

```
conda install -c anaconda netcdf4
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 227, in _load
        mod_etag_headers.get('_mod'))
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 574, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 235, in install
        force_reinstall=context.force,
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 95, in query
        self.load()
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 233, in _load
        mod_etag_headers.get('_mod'))
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 280, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 369, in _process_raw_repodata_str
        info['fn'] = fn
    TypeError: 'NoneType' object does not support item assignment

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
conda info

     active environment : None
       user config file : /home/zhuyafeng/.condarc
 populated config files : /home/zhuyafeng/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : /hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/pkgs
                          /home/zhuyafeng/.conda/pkgs
       envs directories : /hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3/envs
                          /home/zhuyafeng/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.0 CPython/3.6.5 Linux/2.6.32-696.30.1.el6.x86_64 centos/6.9 glibc/2.12
                UID:GID : 31072:805
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

``` 
conda config --show-sources
==> /home/zhuyafeng/.condarc <==
channels:
  - conda-forge
  - bioconda
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
conda list --show-channel-urls
# packages in environment at /hwfssz1/ST_CANCER/POL/SHARE/tools/miniconda3:
#
# Name                    Version                   Build  Channel
anaconda                  custom           py36hbbc8b67_0    defaults
asn1crypto                0.24.0                py36_1003    conda-forge
biopython                 1.72                     py36_0    conda-forge
blas                      1.1                    openblas    conda-forge
blast                     2.5.0                hc0b0e79_3    bioconda
blat                      36                            0    bioconda
boost                     1.68.0           py36h3e44d54_1    conda-forge
boost-cpp                 1.68.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cairo                     1.14.10                       0    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
coinmp                    1.8.3                         0    conda-forge
conda                     4.5.11                py36_1000    conda-forge
conda-env                 2.6.0                         1    conda-forge
coreutils                 8.30                 h470a237_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.61.1               h74213dd_2    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
eigen                     3.3.5                h2d50403_1    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.12.6                        0    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
glpk                      4.65                 h16a7912_1    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gnutls                    3.5.19               h2a4e5f8_1    conda-forge
graphite2                 1.3.12               hfc679d8_1    conda-forge
gsl                       2.4             blas_openblashddceaf2_2  [blas_openblas]  conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
harfbuzz                  1.7.6                         0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
intel-openmp              2019.0                      118    defaults
java-jdk                  8.0.92                        1    bioconda
jpeg                      9c                   h470a237_1    conda-forge
krb5                      1.16.1               hbb41f41_0    conda-forge
libboost                  1.67.0               h46d08c1_4    defaults
libcurl                   7.61.1               hbdb9355_2    conda-forge
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libnetcdf                 4.6.1               h9cd6fdc_11    conda-forge
libopenblas               0.2.20               h9ac9557_7    defaults
libpng                    1.6.34               ha92aebf_2    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libsvm                    323                           0    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h88dbc4e_2    conda-forge
lxml                      4.2.5            py36hc9114bc_0    conda-forge
mkl                       2019.0                      118    defaults
mkl_fft                   1.0.6                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
msgf_plus                 2017.07.21                    1    bioconda
msstitch                  2.8              py36h24bf2e0_0    bioconda
ncurses                   5.9                          10    conda-forge
nettle                    3.3                           0    conda-forge
nextflow                  18.10.1              ha4d7672_1    bioconda
numpy                     1.15.3          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
numpy-base                1.14.3           py36h0ea5e3f_1    defaults
openblas                  0.3.3                ha44fe06_1    conda-forge
openjdk                   8.0.144          zulu8.23.0.3_2    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
pango                     1.40.14                       0    conda-forge
pcre                      8.39                          0    conda-forge
percolator                3.1                 boost_1.624    bioconda
perl                      5.26.2               h470a237_0    conda-forge
perl-archive-tar          2.18                    pl526_3    bioconda
perl-carp                 1.38                    pl526_1    bioconda
perl-compress-raw-bzip2   2.074           pl526hfc679d8_0    bioconda
perl-compress-raw-zlib    2.081           pl526h2d50403_0    bioconda
perl-data-dumper          2.161                   pl526_2    bioconda
perl-encode               2.88                    pl526_1    bioconda
perl-exporter             5.72                    pl526_1    bioconda
perl-exporter-tiny        1.000000                pl526_0    bioconda
perl-extutils-makemaker   7.34                    pl526_2    bioconda
perl-io-compress          2.069           pl526hfc679d8_5    bioconda
perl-io-zlib              1.10                    pl526_2    bioconda
perl-list-moreutils       0.428                   pl526_1    bioconda
perl-list-moreutils-xs    0.428                   pl526_0    bioconda
perl-parent               0.236                   pl526_1    bioconda
perl-pathtools            3.73                 h470a237_2    bioconda
perl-scalar-list-utils    1.45            pl526h470a237_3    bioconda
perl-test-more            1.001002                pl526_1    bioconda
perl-xsloader             0.24                    pl526_0    bioconda
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
py-boost                  1.67.0           py36h04863e7_4    defaults
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.5                         1    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
qt                        5.6.2                         7    conda-forge
r                         3.4.1                  r3.4.1_0    conda-forge
r-base                    3.4.1                         4    conda-forge
r-boot                    1.3_20                   r341_0    conda-forge
r-class                   7.3_14           r341hc070d10_2    conda-forge
r-cluster                 2.0.7_1          r341h364d78e_0    conda-forge
r-codetools               0.2_15           r341h6115d3f_1    conda-forge
r-foreign                 0.8_71           r341hc070d10_2    conda-forge
r-kernsmooth              2.23_15          r341h364d78e_2    conda-forge
r-lattice                 0.20_35          r341hc070d10_0    conda-forge
r-mass                    7.3_50           r341hc070d10_2    conda-forge
r-matrix                  1.2_14           r341hc070d10_2    conda-forge
r-mgcv                    1.8_24           r341hc070d10_2    conda-forge
r-nlme                    3.1_137          r341h364d78e_0    conda-forge
r-nnet                    7.3_12           r341hc070d10_2    conda-forge
r-recommended             3.4.1                  r3.4.1_0    conda-forge
r-rpart                   4.1_13           r341hc070d10_2    conda-forge
r-spatial                 7.3_11           r341hc070d10_2    conda-forge
r-survival                2.42_6           r341hc070d10_1    conda-forge
readline                  7.0                           0    conda-forge
requests                  2.20.0                py36_1000    conda-forge
ruamel_yaml               0.15.71          py36h470a237_0    conda-forge
setuptools                40.5.0                   py36_0    conda-forge
six                       1.11.0                py36_1001    conda-forge
sqlite                    3.20.1                        2    conda-forge
tk                        8.6.8                ha92aebf_0    conda-forge
tokyocabinet              1.4.48               h96824bc_3    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wheel                     0.32.2                   py36_0    conda-forge
xerces-c                  3.1.2                         0    defaults
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xsd                       4.0.0_dep                     0    bioconda
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge

```
</p></details>

**Comment by yafeng** [comment]
I found the solution. Problem fixed by using the following command instead.
`conda install -c conda-forge netcdf4=1.4.2`
