### ISSUE TITLE
config appears to not pick up conda_build/matrix_base_dir in 4.6.0b1

### ISSUE THREAD

**Issue by msarahan** [conda/conda#7917]
In my .condarc:

```
conda_build:
  matrix_base_dir: ~/code/automated-build/c3i_configurations/anaconda_public
```

This is for c3i.  Somehow this isn't getting loaded properly:

```
c3i one-off py36_win python-3.6-feedstock -p "win*"
Traceback (most recent call last):
  File "/Users/msarahan/miniconda3/bin/c3i", line 11, in <module>
    load_entry_point('conda-concourse-ci', 'console_scripts', 'c3i')()
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/cli.py", line 240, in main
    execute.submit_one_off(pass_throughs=pass_throughs, **args.__dict__)
  File "/Users/msarahan/code/conda-concourse-ci/conda_concourse_ci/execute.py", line 802, in submit_one_off
    config_root_dir = os.path.expanduser(config_root_dir)
  File "/Users/msarahan/miniconda3/lib/python3.6/posixpath.py", line 235, in expanduser
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

The code that loads this setting is at https://github.com/conda/conda-concourse-ci/blob/master/conda_concourse_ci/cli.py#L43

**Comment by msarahan** [comment]
I isolated this to https://github.com/conda/conda/commit/1418be0fc7368ddbbfdae5994168b98f01b0c190#diff-b48dce471b4b8aed241c3b09306aa176

That commit causes the conda_build key to not be loaded at all.  I am investigating.
