### ISSUE TITLE
dev install of c3i appears to prevent conda downgrade

### ISSUE THREAD

**Issue by msarahan** [conda/conda#7918]
With conda 4.6.0b1, I can no longer downgrade to conda 4.5.  Here's the error report:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 21, in execute
        install(args, parser, 'install')
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 250, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
        force_remove, force_reinstall)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 145, in solve_for_diff
        force_remove)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 206, in solve_final_state
        self.prefix, update_modifier, deps_modifier, prune, ignore_pinned, force_remove
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/solve.py", line 729, in __init__
        self.solution_precs = tuple(self.prefix_data.iter_records())
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 115, in iter_records
        return itervalues(self._prefix_records)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 144, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 68, in load
        self._load_site_packages()
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/core/prefix_data.py", line 257, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 245, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/common/pkg_formats/python.py", line 76, in init
        return PythonEggLinkDistribution(prefix_path, anchor_file, python_version)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/common/pkg_formats/python.py", line 415, in __init__
        anchor_full_path = get_dist_file_from_egg_link(anchor_file, prefix_path)
      File "/Users/msarahan/miniconda3/lib/python3.6/site-packages/conda/common/pkg_formats/python.py", line 914, in get_dist_file_from_egg_link
        assert len(egg_info_fnames) == 1, (egg_link_file, egg_info_fnames)
    AssertionError: ('lib/python3.6/site-packages/conda-concourse-ci.egg-link', ['conda_gitlab_ci.egg-info', 'conda_concourse_ci.egg-info'])

`$ /Users/msarahan/miniconda3/bin/conda install conda=4.5`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=/Users/msarahan/miniconda3/bin/conda
               CONDA_ROOT=/Users/msarahan/miniconda3
              CONDA_SHLVL=0
                     PATH=/Users/msarahan/miniconda3/condabin:/Users/msarahan/miniconda3/bin:/us
                          r/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/domino:/Librar
                          y/TeX/texbin:/opt/X11/bin:/usr/local/git/bin:/usr/local/krb5/bin:/usr/
                          local/ossh/bin
  PYTHONDONTWRITEBYTECODE=1
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/msarahan/.condarc
 populated config files : /Users/msarahan/.condarc
          conda version : 4.6.0b1
    conda-build version : 3.16.1+10.g7687de5e.dirty
         python version : 3.6.6.final.0
       base environment : /Users/msarahan/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/msarahan/miniconda3/pkgs
                          /Users/msarahan/.conda/pkgs
       envs directories : /Users/msarahan/miniconda3/envs
                          /Users/msarahan/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.0b1 requests/2.19.1 CPython/3.6.6 Darwin/18.0.0 OSX/10.14
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by msarahan** [comment]
This looks like it's probably a problem in c3i's code, but it's an error that hasn't been an error up to now.

**Comment by miraculixx** [comment]
This is a bug in conda code introduced by  ef5e0284c467f4ace0644f5379d69d4ac08a8714, specifically 
https://github.com/conda/conda/blob/ef5e0284c467f4ace0644f5379d69d4ac08a8714/conda/core/python_dist.py#L365

This match expression incorrectly returns all packages that start with the same name, e.g. `['conda_gitlab_ci.egg-info', 'conda_concourse_ci.egg-info'])`when in fact it should only return one (the one for the package being looked up).
