### ISSUE TITLE
When trying to upgrade pandas, the following error occurs

### ISSUE THREAD

**Issue by shumrussia** [conda/conda#7945]
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 115, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 51, in execute
    conda = Anaconda()
  File "C:\Anaconda\lib\site-packages\conda\anaconda.py", line 43, in __init__
    self._index = PackageIndex(fetch_index(self.channel_urls))
  File "C:\Anaconda\lib\site-packages\conda\remote.py", line 46, in fetch_index
    repodata = fetch_repodata(url)
  File "C:\Anaconda\lib\site-packages\conda\remote.py", line 29, in fetch_repodata
    fi = urllib2.urlopen(url + fn)
  File "C:\Anaconda\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Anaconda\lib\urllib2.py", line 392, in open
    protocol = req.get_type()
  File "C:\Anaconda\lib\urllib2.py", line 254, in get_type
    raise ValueError, "unknown url type: %s" % self.__original
ValueError: unknown url type: defaults/win-64/repodata.json.bz2

**Comment by wulmer** [comment]
Could you please post the output of `conda info` ? I would like to check your channel configuration.

**Comment by kalefranz** [comment]
Wow that is a really old conda.

https://github.com/conda/conda/tree/1.4.4

March 9, 2013
