### ISSUE TITLE
conda update crashed

### ISSUE THREAD

**Issue by jayendra13** [conda/conda#796]
My Anaconda version is 1.9.1 (64-bit) which is installed on windows Machine

While trying to update the conda to current version using following command

conda update conda

I got this error

Fetching package metadata: An unexpected error has occurred, please consider sen
ding the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 184, in instal
l
    unknown=args.unknown)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 40, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 77, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 152, in fetch_index
    session = CondaSession()
  File "C:\Anaconda\lib\site-packages\conda\connection.py", line 60, in __init__

    self.proxies = get_proxy_servers()
  File "C:\Anaconda\lib\site-packages\conda\config.py", line 250, in get_proxy_s
ervers
    return requests.utils.getproxies()
AttributeError: 'module' object has no attribute 'getproxies'

C:\algorithms>conda update conda
Fetching package metadata: An unexpected error has occurred, please consider sen
ding the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_update.py", line 39, in exe
cute
    install.install(args, parser, 'update')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 184, in instal
l
    unknown=args.unknown)
  File "C:\Anaconda\lib\site-packages\conda\api.py", line 40, in get_index
    unknown=unknown)
  File "C:\Anaconda\lib\site-packages\conda\utils.py", line 77, in __call__
    value = self.func(*args, **kw)
  File "C:\Anaconda\lib\site-packages\conda\fetch.py", line 152, in fetch_index
    session = CondaSession()
  File "C:\Anaconda\lib\site-packages\conda\connection.py", line 60, in __init__

    self.proxies = get_proxy_servers()
  File "C:\Anaconda\lib\site-packages\conda\config.py", line 250, in get_proxy_s
ervers
    return requests.utils.getproxies()
AttributeError: 'module' object has no attribute 'getproxies'

**Comment by csoja** [comment]
@jayendra13  Can this issue be closed?  If not, can you please provide the output of  conda info -a and conda list?

**Comment by asmeurer** [comment]
I'm going to close this. If you still have issues, please comment here and it can be reopened.

**Comment by jayendra13** [comment]
@csoja  and @asmeurer thanks for your concerns, I was able to resolve this issue after re-installation of anaconda
