### ISSUE TITLE
conda fails if python package metadata is missing

### ISSUE THREAD

**Issue by jjhelmus** [conda/conda#7963]
A follow on to #7948.  Conda 4.6.x will fail if certain files are missing which are needed to determine python package prefix information.  I have no examples of this occurring using traditional tooling (pip, conda, etc) but the following can be used as a test case:

```
$ conda create -y -n example python=3.6 pip
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/jhelmus/workspace/conda/devenv/envs/example

  added / updated specs:
    - pip
    - python=3.6


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/linux-64::ca-certificates-2018.03.07-0
  certifi            pkgs/main/linux-64::certifi-2018.10.15-py36_0
  libedit            pkgs/main/linux-64::libedit-3.1.20170329-h6b74fdf_2
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  ncurses            pkgs/main/linux-64::ncurses-6.1-hf484d3e_0
  openssl            pkgs/main/linux-64::openssl-1.1.1-h7b6447c_0
  pip                pkgs/main/linux-64::pip-18.1-py36_0
  python             pkgs/main/linux-64::python-3.6.7-h0371630_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-40.5.0-py36_0
  sqlite             pkgs/main/linux-64::sqlite-3.25.2-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.32.2-py36_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-ha838bed_2


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate example
#
# To deactivate an active environment, use
#
#     $ conda deactivate
$ conda activate example
$ pip install imagesize
Collecting imagesize
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Installing collected packages: imagesize
Successfully installed imagesize-1.1.0
$ conda list imagesize
# packages in environment at /home/jhelmus/workspace/conda/devenv/envs/example:
#
# Name                    Version                   Build  Channel
imagesize                 1.1.0                    pypi_0    pypi
$ rm devenv/envs/example/lib/python3.6/site-packages/imagesize-1.1.0.dist-info/METADATA
$ conda list imagesize

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/jhelmus/workspace/conda/conda/exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "/home/jhelmus/workspace/conda/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/jhelmus/workspace/conda/conda/cli/conda_argparse.py", line 81, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/jhelmus/workspace/conda/conda/cli/main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "/home/jhelmus/workspace/conda/conda/cli/main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "/home/jhelmus/workspace/conda/conda/cli/main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/home/jhelmus/workspace/conda/conda/core/prefix_data.py", line 116, in iter_records
        return itervalues(self._prefix_records)
      File "/home/jhelmus/workspace/conda/conda/core/prefix_data.py", line 145, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/home/jhelmus/workspace/conda/conda/core/prefix_data.py", line 69, in load
        self._load_site_packages()
      File "/home/jhelmus/workspace/conda/conda/core/prefix_data.py", line 258, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/home/jhelmus/workspace/conda/conda/gateways/disk/read.py", line 245, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "/home/jhelmus/workspace/conda/conda/common/pkg_formats/python.py", line 78, in init
        return PythonInstalledDistribution(prefix_path, anchor_file, python_version)
      File "/home/jhelmus/workspace/conda/conda/common/pkg_formats/python.py", line 382, in __init__
        super(PythonInstalledDistribution, self).__init__(anchor_full_path, python_version)
      File "/home/jhelmus/workspace/conda/conda/common/pkg_formats/python.py", line 106, in __init__
        self._check_files()
      File "/home/jhelmus/workspace/conda/conda/common/pkg_formats/python.py", line 116, in _check_files
        assert isfile(fpath)
    AssertionError
`$ /home/jhelmus/workspace/conda/devenv/bin/conda list imagesize`

  environment variables:
                 CIO_TEST=<not set>
          COMPIZ_BIN_PATH=/usr/bin/
        CONDA_DEFAULT_ENV=example
                CONDA_EXE=/home/jhelmus/workspace/conda/devenv/bin/conda
             CONDA_PREFIX=/home/jhelmus/workspace/conda/devenv/envs/example
           CONDA_PREFIX_1=/home/jhelmus/workspace/conda/devenv
    CONDA_PROMPT_MODIFIER=(example)
         CONDA_PYTHON_EXE=/home/jhelmus/workspace/conda/devenv/bin/python
               CONDA_ROOT=/home/jhelmus/workspace/conda/devenv
              CONDA_SHLVL=2
            DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
           MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
                     PATH=/home/jhelmus/workspace/conda/devenv/envs/example/bin:/home/jhelmus/wo
                          rkspace/conda/devenv/condabin:/home/jhelmus/anaconda3/envs/example/bin
                          :/home/jhelmus/workspace/conda/devenv/condabin:/home/jhelmus/anaconda3
                          /bin:/home/jhelmus/workspace/conda_recipe_tools:/home/jhelmus/bin:/hom
                          e/jhelmus/anaconda3/condabin:/home/jhelmus/anaconda3/bin:/home/jhelmus
                          /workspace/conda_recipe_tools:/home/jhelmus/bin:/usr/local/sbin:/usr/l
                          ocal/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/sn
                          ap/bin
           PYTHONHASHSEED=2686490414
     PYTHON_MAJOR_VERSION=3
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
            XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
         XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0

     active environment : example
    active env location : /home/jhelmus/workspace/conda/devenv/envs/example
            shell level : 2
       user config file : /home/jhelmus/.condarc
 populated config files : /home/jhelmus/.condarc
          conda version : 4.6.0b1.post878+21a2a60
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/jhelmus/workspace/conda/devenv  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/jhelmus/workspace/conda/devenv/pkgs
                          /home/jhelmus/.conda/pkgs
       envs directories : /home/jhelmus/workspace/conda/devenv/envs
                          /home/jhelmus/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.0b1.post878+21a2a60 requests/2.20.0 CPython/3.7.1 Linux/4.13.0-45-generic ubuntu/16.04.4 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

```
$ conda info

     active environment : /home/jhelmus/workspace/conda/devenv
    active env location : /home/jhelmus/workspace/conda/devenv
            shell level : 1
       user config file : /home/jhelmus/.condarc
 populated config files : /home/jhelmus/.condarc
          conda version : 4.5.11
    conda-build version : 3.16.1
         python version : 3.6.6.final.0
       base environment : /home/jhelmus/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/jhelmus/anaconda3/pkgs
                          /home/jhelmus/.conda/pkgs
       envs directories : /home/jhelmus/anaconda3/envs
                          /home/jhelmus/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.18.4 CPython/3.6.6 Linux/4.13.0-45-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by alfredaita** [comment]
This may be my issue see#7960.  conda is unable to discover my pkgs in the base(rooot) mode. conda-meta is empty. If I switch to one of my other environments, [ which are about a year old]  , conda list etc work fine. my conda-meta directory is full with .json files for that enviornment.

So can I create these files from my packages in my base and load them into conda-meta ?
