### ISSUE TITLE
Conda, Solving Environment Failed, InvalidProxyURLs

### ISSUE THREAD

**Issue by peraponf** [conda/conda#7969]
Conda failed when trying to install a package. It shows environment failed due to invalid proxy urls. appreciate for any suggestion how to work around the issue.

(base) C:\windows\system32>conda install -c conda-forge/label/gcc7 python-docx
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 11, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 235, in install
        force_reinstall=context.force,
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 518, in solve_for_transaction
        force_remove, force_reinstall)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 451, in solve_for_diff
        final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 180, in solve_final_state
        index, r = self._prepare(prepared_specs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\solve.py", line 592, in _prepare
        self.subdirs, prepared_specs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 215, in get_reduced_index
        new_records = query_all(spec)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 184, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 95, in query
        self.load()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 227, in _load
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 437, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 525, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 512, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 622, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 410, in send
        conn = self.get_connection(request.url, proxies)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 306, in get_connection
        raise InvalidProxyURL("Please check proxy URL. It is malformed"
    requests.exceptions.InvalidProxyURL: Please check proxy URL. It is malformed and could be missing the host.

`$ C:\ProgramData\Anaconda3\Scripts\conda install -c conda-forge/label/gcc7 python-docx`

  environment variables:
                  AD_PATH=OU=User Accounts,OU=User Directory,DC=americas,DC=shell,DC=com
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\ProgramData\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\ProgramData\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\P.Anan
              HTTPS_PROXY=<set>
                 NO_PROXY=<set>
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\SIMULIA\Commands;C:\Program Files\Microsoft MPI\Bin\;C:\ProgramDa
                          ta\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\Syst
                          em32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files\Intel\WiFi\bin\;C:\Program Files\Common
                          Files\Intel\WirelessCommon\;c:\Program
                          Files\1E\NomadBranch\;C:\Program
                          Files\MATLAB\R2017b\runtime\win64;C:\Program
                          Files\MATLAB\R2017b\bin;C:\Program Files\MATLAB\MATLAB Compiler Runtim
                          e\v84\runtime\win64;C:\Oracle\InstantClient_x64\12.2.0;C:\Oracle\Insta
                          ntClient_x64\12.2.0\bin;C:\Oracle\InstantClient_x86\12.2.0;C:\Oracle\I
                          nstantClient_x86\12.2.0\bin;C:\Users\P.Anan\AppData\Local\Mi
                          crosoft\WindowsApps;C:\Users\P.Anan\AppData\Local\atom\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\windows\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
         SSF_LIBRARY_PATH=C:\Program Files (x86)\SAP\FrontEnd\SecureLogin\lib\sapcrypto.dll
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\P.Anan\.condarc
 populated config files : C:\Users\P.Anan\.condarc
          conda version : 4.5.11
    conda-build version : 3.15.1
         python version : 3.7.0.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/label/gcc7/win-64
                          https://conda.anaconda.org/conda-forge/label/gcc7/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\P.Anan\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\P.Anan\AppData\Local\conda\conda\envs
                          C:\Users\P.Anan\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.16299
          administrator : True
             netrc file : None
           offline mode : False

**Comment by nehaljwani** [comment]
@peraponf Instead of setting HTTPS_PROXY and NO_PROXY to empty strings, could you try [un-setting](https://stackoverflow.com/a/17106863/1005215) them instead?
```
set "HTTPS_PROXY="
set "NO_PROXY="
```

**Comment by peraponf** [comment]
thanks @nehaljwani after setting proxy to the company proxy, it works.
