### ISSUE TITLE
Error logging can hide real issue

### ISSUE THREAD

**Issue by tswicegood** [conda/conda#797]
Consider this line for a minute: https://github.com/conda/conda/blob/master/conda/cli/conda_argparse.py#L78

I got into a state where `p` was not defined because `subprocess.Popen` had failed.  I got to that state by setting up miniconda with Python 3.4, installing `conda-build`, then downgrading to Python 2.7.  `conda-build` was still installed, but with the wrong version of Python which caused the `Popen` to not work.

In this case there didn't seem to be any exit code, as `p` was never assigned.

Here's the traceback I was seeing:

```
Traceback (most recent call last):
  File "/opt/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 166, in main
    args = p.parse_args()
  File "/opt/anaconda/lib/python2.7/argparse.py", line 1690, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/opt/anaconda/lib/python2.7/argparse.py", line 1729, in parse_known_args
    self.error(str(err))
  File "/opt/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 78, in error
    sys.exit(p.returncode)
UnboundLocalError: local variable 'p' referenced before assignment
```

**Comment by kalefranz** [comment]
Outdated. Closing.
