### ISSUE TITLE
error when "source activate py36" is done on Windows Git-Bash

### ISSUE THREAD

**Issue by yashpatel21** [conda/conda#7983]
## Current Behavior

```
λ source activate py36

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 98, in main
        return activator_main()
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 632, in main
        print(activator.execute(), end='')
      File "C:\Miniconda3\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\u03bb' in position 113: character maps to <undefined>

`$ C:\Miniconda3\Scripts\conda shell.posix activate py36`

  environment variables:
             ACLOCAL_PATH=C:\Program Files\Git\mingw64\share\aclocal;C:\Program
                          Files\Git\usr\share\aclocal
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Miniconda3
              CONDA_SHLVL=0
                  EXEPATH=C:\Program Files\Git\bin
                 HOMEPATH=\Users\patel_223gv41
                 INFOPATH=C:\Program Files\Git\usr\local\info;C:\Program
                          Files\Git\usr\share\info;C:\Program Files\Git\usr\info;C:\Program
                          Files\Git\share\info
                  MANPATH=C:\Program Files\Git\mingw64\local\man;C:\Program
                          Files\Git\mingw64\share\man;C:\Program
                          Files\Git\usr\local\man;C:\Program Files\Git\usr\share\man;C:\Program
                          Files\Git\usr\man;C:\Program Files\Git\share\man
            ORIGINAL_PATH=C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users
                          \patel_223gv41\bin;C:\Yash\Cmder\vendor\conemu-
                          maximus5\ConEmu\Scripts;C:\Yash\Cmder\vendor\conemu-
                          maximus5;C:\Yash\Cmder\vendor\conemu-maximus5\ConEmu;C:\Miniconda3;C:\
                          Miniconda3\Library\mingw-w64\bin;C:\Miniconda3\Library\usr\bin;C:\Mini
                          conda3\Library\bin;C:\Miniconda3\Scripts;C:\Program Files
                          (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\nodejs;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common
                          Files\Intel\WirelessCommon;C:\Program Files\Java\jdk-10.0.2\bin;C:\Use
                          rs\patel_223gv41\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\Microsoft VS Code\bin;C:\Yash\Cmder;C:\Users\patel_223gv41\AppDa
                          ta\Local\Microsoft\WindowsApps;C:\Users\patel_223gv41\AppData\Roaming\
                          npm;C:\Users\patel_223gv41\AppData\Local\hyper\app-2.0.0\resources\bin
                          ;C:\Program Files\Java\jdk-10.0.2\bin;C:\Users\patel_223gv41\AppData\L
                          ocal\Programs\Microsoft VS Code\bin;C:\Users\patel_223gv41
                     PATH=C:\Users\patel_223gv41\bin;C:\Program Files\Git\mingw64\bin;C:\Program
                          Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program
                          Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Gi
                          t\usr\bin;C:\Users\patel_223gv41\bin;C:\Yash\Cmder\vendor\conemu-
                          maximus5\ConEmu\Scripts;C:\Yash\Cmder\vendor\conemu-
                          maximus5;C:\Yash\Cmder\vendor\conemu-maximus5\ConEmu;C:\Miniconda3;C:\
                          Miniconda3\Library\mingw-w64\bin;C:\Miniconda3\Library\usr\bin;C:\Mini
                          conda3\Library\bin;C:\Miniconda3\Scripts;C:\Program Files
                          (x86)\Intel\iCLS Client;C:\Program Files\Intel\iCLS Client;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
                          (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program
                          Files\Git\cmd;C:\ProgramData\chocolatey\bin;C:\Program
                          Files\nodejs;C:\Program Files\Intel\WiFi\bin;C:\Program Files\Common
                          Files\Intel\WirelessCommon;C:\Program Files\Java\jdk-10.0.2\bin;C:\Use
                          rs\patel_223gv41\AppData\Local\Microsoft\WindowsApps;C:\Program
                          Files\Microsoft VS Code\bin;C:\Yash\Cmder;C:\Users\patel_223gv41\AppDa
                          ta\Local\Microsoft\WindowsApps;C:\Users\patel_223gv41\AppData\Roaming\
                          npm;C:\Users\patel_223gv41\AppData\Local\hyper\app-2.0.0\resources\bin
                          ;C:\Program Files\Java\jdk-10.0.2\bin;C:\Users\patel_223gv41\AppData\L
                          ocal\Programs\Microsoft VS Code\bin;C:\Users\patel_223gv41;C:\Program
                          Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
          PKG_CONFIG_PATH=C:\Program Files\Git\mingw64\lib\pkgconfig;C:\Program
                          Files\Git\mingw64\share\pkgconfig
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : C:\Users\patel_223gv41\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\patel_223gv41\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\patel_223gv41\AppData\Local\conda\conda\envs
                          C:\Users\patel_223gv41\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```

## Expected Behavior

Instead of giving an error, It should be just activating the conda environment.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
λ conda info

     active environment : None
            shell level : 0
       user config file : C:\Users\patel_223gv41\.condarc
 populated config files :
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\patel_223gv41\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\patel_223gv41\AppData\Local\conda\conda\envs
                          C:\Users\patel_223gv41\.conda\envs
               platform : win-64
             user-agent : conda/4.5.11 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by yash-1337** [comment]
Ok I figure something out. It is causing an error because the activate script doesn't like the lambda "λ" in my bash prompt. If I change the lambda to the regular dollar sign "$" it works because the activate script recognizes it. However, I like my custom bash prompt just the way it is. My question is why does the activate script need to run through and scan my bash prompt anyway? Is there a way I can keep the lambda and not make it output an error?

**Comment by yash-1337** [comment]
Yes I just saw that, too. So when I use regular Cmder and not Git-Bash, Cmder still has the lambda:

```
C:\
λ activate py36

C:\
(py36) λ
```

But, as you can see, activate script works fine with regular Cmder prompt. So I think it might have to do something with the encoding of the Cmder prompt vs the encoding of the Git-Bash prompt. If anyone could help figure this out, I'd really appreciate it.

**Comment by sbmueller** [comment]
Same with Cygwin and Conda 4.8.0.

**Comment by agutierad08** [comment]
Setting PYTHONIOENCODING and PYTHONLEGACYWINDOWSSTDIO environment variables to UTF-8 solved my issue. I am using Git bash terminal in windows 10.
