### ISSUE TITLE
conda with requests 2.0.0 fails to run: import charade

### ISSUE THREAD

**Issue by ijstokes** [conda/conda#799]
I have a conda env with requests v2.0.0.  I cannot run `conda info` because this command triggers the following stact trace:

``` python
Traceback (most recent call last):
  File "/Users/ijstokes/anaconda/envs/wakari-server/bin/conda", line 3, in <module>
    from conda.cli import main
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/__init__.py", line 8, in <module>
    from conda.cli.main import main
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 47, in <module>
    from conda.cli import main_create
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 11, in <module>
    from conda.cli import common, install
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 17, in <module>
    import conda.plan as plan
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/plan.py", line 21, in <module>
    from conda.fetch import fetch_pkg
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 23, in <module>
    from conda.connection import CondaSession, unparse_url
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/conda/connection.py", line 22, in <module>
    import requests
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/requests/utils.py", line 23, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/Users/ijstokes/anaconda/lib/python2.7/site-packages/requests/compat.py", line 7, in <module>
    from .packages import charade as chardet
ImportError: cannot import name charade
```

**Comment by duozmo** [comment]
I had the same, and `pip uninstall requests` cleared out version 2.0.0 for me. I had manually installed requests 2.0.0 in late 2013, probably because it came out in [July 2013](https://github.com/kennethreitz/requests/releases/tag/2.0) but Anaconda didn’t get it until [February 2014](http://docs.continuum.io/anaconda/changelog.html#id8).
