### ISSUE TITLE
Incomplete value in default_channels throws traceback

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#8006]
```➜  ~ conda config --show-sources
==> /Users/nwani/.condarc <==
default_channels:
  - http://repo.anaconda.com/
```
```
➜  ~ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main_info.py", line 317, in execute
        info_dict = get_info_dict(args.system)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main_info.py", line 145, in get_info_dict
        channels = list(all_channel_urls(context.channels))
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/models/channel.py", line 491, in all_channel_urls
        channel = Channel(chn)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/models/channel.py", line 41, in __call__
        c = Channel._cache_[value] = Channel.from_value(value)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/models/channel.py", line 119, in from_value
        if _stripped in context.custom_multichannels:
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/_vendor/auxlib/decorators.py", line 265, in new_fget
        cache[inner_attname] = func(self)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/base/context.py", line 527, in custom_multichannels
        ) for name, urls in iteritems(reserved_multichannel_urls)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/base/context.py", line 527, in <genexpr>
        ) for name, urls in iteritems(reserved_multichannel_urls)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/base/context.py", line 526, in <genexpr>
        Channel.make_simple_channel(self.channel_alias, url) for url in urls)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/models/channel.py", line 138, in make_simple_channel
        name=name.strip('/'))
    AttributeError: 'NoneType' object has no attribute 'strip'

`$ /Users/nwani/m3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:
```

**Comment by nehaljwani** [comment]
Fixed by https://github.com/conda/conda/pull/8021
