### ISSUE TITLE
conda install spyder in venv fails

### ISSUE THREAD

**Issue by silpodx** [conda/conda#8010]
**I'm submitting a...**
  - [*] bug report

## Current Behavior

i was trying to install spyder in a new virtual environment (done it before, same computer) and i got an error, with a note requesting me to post the issue here on gitHub...

### Steps to Reproduce

```
(C:\Users\sipo\Documents\conda_envs\newx) C:\Users\sipo>conda install spyder
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Users\sipo\Documents\conda_envs\newx:

The following NEW packages will be INSTALLED:

    alabaster:                0.7.10-py36_0
    astroid:                  1.5.3-py36_0
    babel:                    2.5.0-py36_0
    bleach:                   1.5.0-py36_0
    certifi:                  2016.2.28-py36_0
    chardet:                  3.0.4-py36_0
    colorama:                 0.3.9-py36_0
    decorator:                4.1.2-py36_0
    docutils:                 0.14-py36_0
    entrypoints:              0.2.3-py36_0
    html5lib:                 0.9999999-py36_0
    icu:                      57.1-vc14_0
    imagesize:                0.7.1-py36_0
    ipykernel:                4.6.1-py36_0
    ipython:                  6.1.0-py36_0
    ipython_genutils:         0.2.0-py36_0
    isort:                    4.2.15-py36_0
    jedi:                     0.10.2-py36_2
    jinja2:                   2.9.6-py36_0
    jpeg:                     9b-vc14_0
    jsonschema:               2.6.0-py36_0
    jupyter_client:           5.1.0-py36_0
    jupyter_core:             4.3.0-py36_0
    lazy-object-proxy:        1.3.1-py36_0
    libpng:                   1.6.30-vc14_1
    markupsafe:               1.0-py36_0
    mistune:                  0.7.4-py36_0
    nbconvert:                5.2.1-py36_0
    nbformat:                 4.4.0-py36_0
    numpydoc:                 0.7.0-py36_0
    openssl:                  1.0.2l-vc14_0
    pandocfilters:            1.4.2-py36_0
    path.py:                  10.3.1-py36_0
    pickleshare:              0.7.4-py36_0
    pip:                      9.0.1-py36_1
    prompt_toolkit:           1.0.15-py36_0
    psutil:                   5.2.2-py36_0
    pycodestyle:              2.3.1-py36_0
    pyflakes:                 1.6.0-py36_0
    pygments:                 2.2.0-py36_0
    pylint:                   1.7.2-py36_0
    pyqt:                     5.6.0-py36_2
    python:                   3.6.2-0
    python-dateutil:          2.6.1-py36_0
    pytz:                     2017.2-py36_0
    pyzmq:                    16.0.2-py36_0
    qt:                       5.6.2-vc14_6
    qtawesome:                0.4.4-py36_0
    qtconsole:                4.3.1-py36_0
    qtpy:                     1.3.1-py36_0
    requests:                 2.14.2-py36_0
    rope:                     0.9.4-py36_1
    setuptools:               36.4.0-py36_1
    simplegeneric:            0.8.1-py36_1
    singledispatch:           3.4.0.3-py36_0
    sip:                      4.18-py36_0
    six:                      1.10.0-py36_0
    snowballstemmer:          1.2.1-py36_0
    sphinx:                   1.6.3-py36_0
    sphinxcontrib:            1.0-py36_0
    sphinxcontrib-websupport: 1.0.1-py36_0
    spyder:                   3.2.3-py36_0
    testpath:                 0.3.1-py36_0
    tornado:                  4.5.2-py36_0
    traitlets:                4.3.2-py36_0
    vc:                       14-0
    vs2015_runtime:           14.0.25420-0
    wcwidth:                  0.1.7-py36_0
    wheel:                    0.29.0-py36_0
    wincertstore:             0.2-py36_0
    wrapt:                    1.10.11-py36_0
    zlib:                     1.2.11-vc14_0

Proceed ([y]/n)? y

zlib-1.2.11-vc 100% |###############################| Time: 0:00:00   2.84 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.19.1
       root environment : C:\Software\Anaconda3  (writable)
    default environment : C:\Users\sipo\Documents\conda_envs\newx
       envs directories : C:\Software\Anaconda3\envs
                          C:\Users\sipo\AppData\Local\conda\conda\envs
                          C:\Users\sipo\.conda\envs
          package cache : C:\Software\Anaconda3\pkgs
                          C:\Users\sipo\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\sipo\.condarc
           offline mode : False
             user-agent : conda/4.3.14 requests/2.19.1 CPython/3.6.0 Windows/7 Windows/6.1.7601



`$ C:\Software\Anaconda3\Scripts\conda-script.py install spyder`




    Traceback (most recent call last):
      File "C:\Software\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Software\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\Software\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Software\Anaconda3\lib\site-packages\conda\cli\install.py", line 359, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Software\Anaconda3\lib\site-packages\conda\plan.py", line 800, in execute_actions
        execute_instructions(plan, index, verbose)
      File "C:\Software\Anaconda3\lib\site-packages\conda\instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "C:\Software\Anaconda3\lib\site-packages\conda\instructions.py", line 108, in UNLINKLINKTRANSACTION_CMD
        txn.execute()
      File "C:\Software\Anaconda3\lib\site-packages\conda\core\link.py", line 262, in execute
        self.verify()
      File "C:\Software\Anaconda3\lib\site-packages\conda\core\link.py", line 241, in verify
        self.prepare()
      File "C:\Software\Anaconda3\lib\site-packages\conda\core\link.py", line 148, in prepare
        for pkg_info in self.packages_info_to_link)
      File "C:\Software\Anaconda3\lib\site-packages\conda\core\link.py", line 148, in <genexpr>
        for pkg_info in self.packages_info_to_link)
      File "C:\Software\Anaconda3\lib\site-packages\conda\core\link.py", line 54, in determine_link_type
        if hardlink_supported(source_test_file, target_prefix):
      File "C:\Software\Anaconda3\lib\site-packages\conda\_vendor\auxlib\decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "C:\Software\Anaconda3\lib\site-packages\conda\gateways\disk\test.py", line 84, in hardlink_supported
        assert not lexists(test_file), test_file
    AssertionError: C:\Users\sipo\Documents\conda_envs\newx\.tmp.index.json


(C:\Users\sipo\Documents\conda_envs\newx) C:\Users\sipo>
```

## Expected Behavior

should install spyder along with all dependent/related packages into the virtual env 'newx'

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
already provided above

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(C:\Users\sipo\Documents\conda_envs\newx) C:\Users\sipo>conda config --show-sources
==> C:\Users\sipo\.condarc <==
ssl_verify: True
channels:
  - anaconda-fusion
  - defaults

(C:\Users\sipo\Documents\conda_envs\newx) C:\Users\sipo>
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(C:\Users\sipo\Documents\conda_envs\newx) C:\Users\sipo>conda list --show-channel-urls
# packages in environment at C:\Users\sipo\Documents\conda_envs\newx:
#

(C:\Users\sipo\Documents\conda_envs\newx) C:\Users\sipo>
```
</p></details>

**Comment by silpodx** [comment]
i installed 1st other packages (numpy, scipy and such) and then tried again spyder and it worked. It crashed when i tried 1st spyder in the new env, if this is of no interest to others, it may be closed.
