### ISSUE TITLE
Jupyter Notebook not starting after updating conda packages

### ISSUE THREAD

**Issue by karthiks** [conda/conda#8035]
I ran a command `conda update --all` and post update I get the follow error on starting jupyter notebook with terminal command `jupyter notebook`:
```
Traceback (most recent call last):
  File "C:\Anaconda3\envs\py36\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Anaconda3\envs\py36\lib\site-packages\notebook\__init__.py", line 25, in <module>
    from .nbextensions import install_nbextension
  File "C:\Anaconda3\envs\py36\lib\site-packages\notebook\nbextensions.py", line 31, in <module>
    from .config_manager import BaseJSONConfigManager
  File "C:\Anaconda3\envs\py36\lib\site-packages\notebook\config_manager.py", line 14, in <module>
    from six import PY3
ModuleNotFoundError: No module named 'six'
```
Now when I try `conda install six`, it says 
```
Solving environment: done
# All requested packages already installed.
```

**Comment by Maltimore** [comment]
You seem to be on windows. I'm just adding that the same happened to me on ubuntu 18.04.

**Comment by simdimdim** [comment]
Same situation here near the end of January.
