### ISSUE TITLE
conda index error:KeyError:  'numpy-1.11.3-py27h28100ab_6.tar.bz2'

### ISSUE THREAD

**Issue by scially** [conda/conda#8037]
i download pkgs from https://repo.anaconda.com/pkgs/main/linux-64/, and i execute `conda index channel`
```
├── channel
│   ├── linux-64

```

```
(base) [root@server1 opt]# conda index channel/
DEBUG:conda_build.index:found 11266 conda packages
DEBUG:conda_build.index:hashing, extracting, and caching /opt/channel/linux-64/_ipyw_jlab_nb_ext_conf-0.1.0-py27_0.tar.bz2
DEBUG:conda_build.index:/opt/channel/linux-64/_ipyw_jlab_nb_ext_conf-0.1.0-py36_0.tar.bz2 has no file info/run_exports.yaml
DEBUG:conda_build.index:/opt/channel/linux-64/cloog-0.18.0-0.tar.bz2 has no file info/about.json
DEBUG:conda_build.index:/opt/channel/linux-64/cloog-0.18.0-0.tar.bz2 has no file info/paths.json
DEBUG:conda_build.index:using patch instructions /opt/channel/linux-64/patch_instructions.json
Traceback (most recent call last):
  File "/opt/anaconda3/bin/conda-index", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 64, in main
    return execute(sys.argv[1:])
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/cli/main_index.py", line 60, in execute
    threads=args.threads, subdir=args.subdir, patch_generator=args.patch_generator)
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/api.py", line 386, in update_index
    update_index(path, check_md5=check_md5, channel_name=channel_name, patch_generator=patch_generator, threads=threads)
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 267, in update_index
    return ChannelIndex(dir_path, channel_name, deep_integrity_check=check_md5, threads=threads).index(patch_generator=patch_generator, verbose=verbose)
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 758, in index
    subdir, repodata_from_packages[subdir], patch_generator)
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 1182, in _patch_repodata
    return _apply_instructions(subdir, repodata, instructions), instructions
  File "/opt/anaconda3/lib/python3.7/site-packages/conda_build/index.py", line 348, in _apply_instructions
    repodata['packages'][fn].update(patch)
KeyError: 'numpy-1.11.3-py27h28100ab_6.tar.bz2'
```
And the i don't find  `numpy-1.11.3-py27h28100ab_6.tar.bz2` in [https://repo.anaconda.com/pkgs/main/linux-64/](https://repo.anaconda.com/pkgs/main/linux-64/), so how do i solve it?

**Comment by scially** [comment]
i delete `patch_instructions.json`, and ok
