### ISSUE TITLE
TCL / TK isn't properly configured

### ISSUE THREAD

**Issue by Bazman76** [conda/conda#8063]
I'm pretty new to R in Ubuntu.

I am running R (3.5.0) in Rstudio 1.1.456 through Anaconda.  
The operating system is Ubuntu 18.04.

In R studio when I select the package Rcmdr I got the following:

   ```
 > library("Rcmdr", lib.loc="~/anaconda3/envs/rstudio/lib/R/library")
    Loading required package: splines
    Loading required package: RcmdrMisc
    Loading required package: car
    Loading required package: carData
    Loading required package: sandwich
    Loading required package: effects
    lattice theme set by effectsTheme()
    See ?effectsTheme for details.
    Error: package or namespace load failed for ‘Rcmdr’:
     .onLoad failed in loadNamespace() for 'tcltk', details:
      call: fun(libname, pkgname)
      error: Can't find a usable init.tcl in the following directories: 
        /builddir/vendor/build/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.5/library ./tcl8.6.5/library
    
    
    
    This probably means that Tcl wasn't installed properly.
```

I then tried package tcltk by itself:

```
   
> library("tcltk", lib.loc="~/anaconda3/envs/rstudio/lib/R/library")
    Error: package or namespace load failed for ‘tcltk’:
     .onLoad failed in loadNamespace() for 'tcltk', details:
      call: fun(libname, pkgname)
      error: Can't find a usable init.tcl in the following directories: 
        /builddir/vendor/build/lib/tcl8.6 ./lib/tcl8.6 ./lib/tcl8.6 ./library ./library ./tcl8.6.5/library ./tcl8.6.5/library
    
    
    
    This probably means that Tcl wasn't installed properly.

```
This poster had a similar issue but I'm unsure how to implement the solution shown:

conda/conda#2299

```
Exception:
Traceback (most recent call last):
File "c:\temp\anaconda_tk_bug\main.py", line 14, in 
main()
File "c:\temp\anaconda_tk_bug\main.py", line 11, in main
co = Controler()
File "c:\temp\anaconda_tk_bug\main.py", line 7, in init
self.root = Tk(className="Name")
File "c:\python\Python_27_64_anaconda\lib\lib-tk\Tkinter.py", line 1814, in init
self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
{c:\dev\programs\system\PyCmd\tcl} c:/dev/programs/system/PyCmd/tcl8.5 c:/python/Python_27_64_anaconda/lib/tcl8.5 c:/python/lib/tcl8.5 c:/lib/tcl8.5 c:/python/library c:/library c:/tcl8.5.15/library c:/tcl8.5.15/library
```
It works if i copy:
\tcl\tcl8.5\
\tcl\tk8.5\
to

\Lib\tcl8.5\
\Lib\tk8.5\

Thing is he doesn't have any paths then end with: "\tcl\tcl8.5" but he does have:  
 c:/dev/programs/system/PyCmd/tcl8.5  
 c:/python/Python_27_64_anaconda/lib/tcl8.5  
Are these the paths for the file that should be copied?

Similarly are these the right paths for the files to be copied to:
c:/python/lib/tcl8.5  
 c:/lib/tcl8.5  

The problem is that my paths are different:

Are these the locations that the file should be copied to?
  /builddir/vendor/build/lib/tcl8.6
 ./lib/tcl8.6 

If so where should they be copied from?

Also I can't see in the files explorer and $ cd "builddir" does not work either!

Can someone please tell me how to resolve this.

**Comment by mingwandroid** [comment]
This is where bugs are reported against conda, the package manager. The issue template should have pointed that out to you:

```
Hi!  Read this; it's important.

This is an issue tracker for conda -- the package manager.  File feature requests
for conda here, as well as bug reports about something conda has messed up.

If your issue is a bug report for:
  * a specific conda package from Anaconda ('defaults' channel):
      ==> file at https://github.com/ContinuumIO/anaconda-issues
  * a specific conda package from conda-forge:
      ==> file at the corresponding feedstock under https://github.com/conda-forge
  * repo.anaconda.com access and service:
      ==> file at https://github.com/ContinuumIO/anaconda-issues
  * anaconda.org access and service:
      ==> file at https://anaconda.org/contact/report
  * commands under 'conda build':
      ==> file at https://github.com/conda/conda-build
  * commands under 'conda env':
      ==> please file it here!
  * all other conda commands that start with 'conda':
      ==> please file it here!
```

.. please file issues related to packages at https://github.com/ContinuumIO/anaconda-issues.git/issues filling in all the reqested details.
