### ISSUE TITLE
Cannot upgrade Python

### ISSUE THREAD

**Issue by Vladimir-Florian** [conda/conda#8065]
## Current Behavior
Error when trying to upgrade python to 3.6

### Steps to Reproduce

```
Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\Scripts\conda-script.py", line 4, in <module>
    import sys
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\cli\main.py", line 194, in main
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\cli\main.py", line 199, in args_func
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 46, in execute
    'install',
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\cli\install.py", line 360, in install
    not context.root_writable)
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\plan.py", line 571, in execute_actions
    #    solution is good
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\plan.py", line 553, in execute_plan
    any(dist for dist in linked_in_root if dist.dist_name.startswith(dist_env.spec))):
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\plan.py", line 509, in link
    if matched_in_root:
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\install.py", line 487, in link
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\install.py", line 211, in update_prefix
OSError: [Errno 22] Invalid argument: 'C:\\Users\\vladimir.florian\\AppData\\Local\\Continuum\\Miniconda3\\"Scripts\\easy_install-3.6-script.py"'

C:\Users\vladimir.florian>conda info
Traceback (most recent call last):
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\common\configuration.py", line 50, in <module>
    from ruamel_yaml.comments import CommentedSeq, CommentedMap
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\ruamel_yaml\__init__.py", line 9, in <module>
    from .cyaml import *
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\ruamel_yaml\cyaml.py", line 5, in <module>
    from ruamel_yaml._ruamel_yaml import CParser, CEmitter
ImportError: No module named 'ruamel_yaml._ruamel_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\cli\main.py", line 103, in _main
    from ..base.context import context
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\base\context.py", line 20, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\common\configuration.py", line 53, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named 'ruamel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\common\configuration.py", line 50, in <module>
    from ruamel_yaml.comments import CommentedSeq, CommentedMap
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\ruamel_yaml\__init__.py", line 9, in <module>
    from .cyaml import *
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\ruamel_yaml\cyaml.py", line 5, in <module>
    from ruamel_yaml._ruamel_yaml import CParser, CEmitter
ImportError: No module named 'ruamel_yaml._ruamel_yaml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\cli\main.py", line 182, in main
    return conda_exception_handler(_main, *args)
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\exceptions.py", line 644, in conda_exception_handler
    return handle_exception(e)
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\exceptions.py", line 579, in print_unexpected_error_message
    from .base.context import context
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\base\context.py", line 20, in <module>
    from ..common.configuration import (Configuration, LoadError, MapParameter, PrimitiveParameter,
  File "C:\Users\vladimir.florian\AppData\Local\Continuum\Miniconda3\lib\site-packages\conda\common\configuration.py", line 53, in <module>
    from ruamel.yaml.comments import CommentedSeq, CommentedMap  # pragma: no cover
ImportError: No module named 'ruamel'
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by dweissner** [comment]
Hi, please post if you have found a resolution as I'm experiencing the same.

**Comment by Vladimir-Florian** [comment]
> Hi, please post if you have found a resolution as I'm experiencing the same.

It seems that the only way is to downgrade, i.e. to install the Python 3.7 version and after that to create an environment with Python 3.6. For me it worked with Anaconda.
