### ISSUE TITLE
Unable to install python 3.5 with conda4.5.2 on Linux

### ISSUE THREAD

**Issue by mukteshkrmishra** [conda/conda#8069]
Hi, 

I am not able to install Python 3.5 with Miniconda 4.5.2 on RHEL7. 
Getting the following error: 

```
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 78, in _main
    exit_code = do_call(args, p)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 11, in execute
    install(args, parser, 'install')
  File "/root/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 235, in install
    force_reinstall=context.force,
  File "/root/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 518, in solve_for_transaction
    force_remove, force_reinstall)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 451, in solve_for_diff
    final_precs = self.solve_final_state(deps_modifier, prune, ignore_pinned, force_remove)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 344, in solve_final_state
    solution = r.solve(tuple(final_environment_specs))  # return value is List[dist]
  File "/root/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 46, in decorated
    return f(*args, **kwds)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 917, in solve
    self.find_conflicts(specs)
  File "/root/miniconda3/lib/python3.7/site-packages/conda/resolve.py", line 244, in find_conflicts
    raise UnsatisfiableError(bad_deps)
conda.exceptions.UnsatisfiableError: The following specifications were found to be in conflict:
  - conda[version='>=4.5.12'] -> enum34 -> python[version='>=2.7,<2.8.0a0']
  - python=3.5
Use "conda info <package>" to see the dependencies for each package.


```

**Conda info:** 

```
    active environment : None
       user config file : /root/.condarc
 populated config files :
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /root/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /root/miniconda3/pkgs
                          /root/.conda/pkgs
       envs directories : /root/miniconda3/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/3.10.0-957.1.3.el7.x86_64 rhel/7.6 glibc/2.17
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by mukteshkrmishra** [comment]
Temporary solution: Had to debug conda to version 4.2.

**Comment by Benatti1991** [comment]
I had the same issue since the last conda update
#8054
