### ISSUE TITLE
unexpected error during installing conda

### ISSUE THREAD

**Issue by leichen218** [conda/conda#807]
Fetching packages ...
An unexpected error has occurred, please consider sending the0:00:00   5.88 MB/s
following traceback to the conda GitHub issue tracker at:

```
https://github.com/conda/conda/issues
```

Include the output of the command 'conda info' in your report.

Traceback (most recent call last):
  File "/usr/local/share/gemini/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/cli/main_install.py", line 39, in execute
    install.install(args, parser, 'install')
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 251, in install
    plan.execute_actions(actions, index, verbose=not args.quiet)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/plan.py", line 391, in execute_actions
    execute_plan(plan, index, verbose)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/plan.py", line 362, in execute_plan
    fetch(index, arg)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/plan.py", line 325, in fetch
    fetch_pkg(index[fn])
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 189, in fetch_pkg
    getLogger('fetch.update').info(n)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/logging/**init**.py", line 1150, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/logging/__init__.py", line 1269, in _log
    self.handle(record)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/logging/__init__.py", line 1279, in handle
    self.callHandlers(record)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/logging/**init**.py", line 1319, in callHandlers
    hdlr.handle(record)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/logging/**init**.py", line 749, in handle
    self.emit(record)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/console.py", line 29, in emit
    fetch_progress.update(n)
  File "/usr/local/share/gemini/anaconda/lib/python2.7/site-packages/conda/progressbar/**init**.py", line 271, in update
    raise ValueError('Value out of range')
ValueError: Value out of range
Traceback (most recent call last):
  File "gemini_install.py", line 310, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 43, in main
    install_conda_pkgs(anaconda)
  File "gemini_install.py", line 118, in install_conda_pkgs
    subprocess.check_call([anaconda["conda"], "install", "--yes", "numpy"])
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/local/share/gemini/anaconda/bin/conda', 'install', '--yes', 'numpy']' returned non-zero exit status 1

**Comment by kalefranz** [comment]
Outdated. Closing.
