### ISSUE TITLE
Getting strang no file Python37\\pkgs\\menuinst-1.4.7-py36_0\\info\\has_prefix error when installing packages

### ISSUE THREAD

**Issue by charesredhat** [conda/conda#8075]
### Steps to Reproduce

```
I installed conda on my window 10 workstation with python 3.7 and Anaconda 3. And I just ran the following command and the following error. 

conda install conda

conda install conda

Package plan for installation in environment C:\Users\######\AppData\Local\Programs\Python\Python37:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-env-2.6.0            |                0          498 B
    vs2015_runtime-14.0.25420  |                0         2.0 MB
    vc-14                      |                0          703 B
    openssl-1.0.2l             |           vc14_0         5.1 MB
    python-3.6.2               |                0        31.5 MB
    asn1crypto-0.22.0          |           py36_0         148 KB
    certifi-2016.2.28          |           py36_0         214 KB
    idna-2.6                   |           py36_0         123 KB
    pycosat-0.6.2              |           py36_0          83 KB
    pycparser-2.18             |           py36_0         168 KB
    pyparsing-2.2.0            |           py36_0          97 KB
    pywin32-220                |           py36_2        12.2 MB
    requests-2.14.2            |           py36_0         703 KB
    ruamel_yaml-0.11.14        |           py36_1         223 KB
    six-1.10.0                 |           py36_0          20 KB
    wheel-0.29.0               |           py36_0         129 KB
    wincertstore-0.2           |           py36_0          14 KB
    cffi-1.10.0                |           py36_0         133 KB
    packaging-16.8             |           py36_0          30 KB
    setuptools-36.4.0          |           py36_1         534 KB
    cryptography-1.8.1         |           py36_0         350 KB
    pip-9.0.1                  |           py36_1         1.7 MB
    pyopenssl-17.0.0           |           py36_0          76 KB
    conda-4.3.30               |   py36h7e176b0_0         535 KB
    ------------------------------------------------------------
                                           Total:        55.9 MB

The following NEW packages will be INSTALLED:

    asn1crypto:     0.22.0-py36_0
    certifi:        2016.2.28-py36_0
    cffi:           1.10.0-py36_0
    conda:          4.3.30-py36h7e176b0_0
    conda-env:      2.6.0-0
    cryptography:   1.8.1-py36_0
    idna:           2.6-py36_0
    menuinst:       1.4.7-py36_0
    openssl:        1.0.2l-vc14_0
    packaging:      16.8-py36_0
    pip:            9.0.1-py36_1
    pycosat:        0.6.2-py36_0
    pycparser:      2.18-py36_0
    pyopenssl:      17.0.0-py36_0
    pyparsing:      2.2.0-py36_0
    python:         3.6.2-0
    pywin32:        220-py36_2
    requests:       2.14.2-py36_0
    ruamel_yaml:    0.11.14-py36_1
    setuptools:     36.4.0-py36_1
    six:            1.10.0-py36_0
    vc:             14-0
    vs2015_runtime: 14.0.25420-0
    wheel:          0.29.0-py36_0
    wincertstore:   0.2-py36_0

Proceed ([y]/n)? y

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.7.2.final.0
       requests version : 2.21.0
       root environment : C:\Users\######\AppData\Local\Programs\Python\Python37  (writable)
    default environment : C:\Users\######\AppData\Local\Programs\Python\Python37
       envs directories : C:\Users\######\AppData\Local\Programs\Python\Python37\envs
          package cache : C:\Users\######\AppData\Local\Programs\Python\Python37\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False



`$ C:\Users\######\AppData\Local\Programs\Python\Python37\Scripts\conda install conda`




    Traceback (most recent call last):
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\install.py", line 201, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\######\\AppData\\Local\\Programs\\Python\\Python37\\pkgs\\menuinst-1.4.7-py36_0\\info\\has_prefix'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\install.py", line 209, in yield_lines
        raise StopIteration
    StopIteration

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\instructions.py", line 78, in LINK_CMD
        link(state['prefix'], dist, lt, index=state['index'])
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\install.py", line 943, in link
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\install.py", line 248, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\install.py", line 248, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\install.py", line 247, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\exceptions.py", line 472, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\######\AppData\Local\Programs\Python\Python37\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
C:\Users\######\Anaconda3\Scripts>conda info
Current conda install:

               platform : win-64
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.7.2.final.0
       requests version : 2.21.0
       root environment : C:\Users\######\AppData\Local\Programs\Python\Python37  (writable)
    default environment : C:\Users\######\AppData\Local\Programs\Python\Python37
       envs directories : C:\Users\######\AppData\Local\Programs\Python\Python37\envs
          package cache : C:\Users\######\AppData\Local\Programs\Python\Python37\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

C:\Users\######\Anaconda3\Scripts>conda config --show-sources


C:\Users\######\Anaconda3\Scripts>

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
C:\Users\######\Anaconda3\Scripts>conda list --show-channel-urls
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64


```
</p></details>

**Comment by SytzeAndr** [comment]
I'm encountering the same issue for any conda package I want to install (f.e. conda itself). Any progress on this?

<details><summary> 

`conda info`
 </summary>
<p>
```
Current conda install:

               platform : win-32
          conda version : 4.2.7
       conda is private : False
      conda-env version : 4.2.7
    conda-build version : not installed
         python version : 3.7.2.final.0
       requests version : 2.22.0
       root environment : C:\Werkplaats\AIDM_project\AIDM_H\env_aidm  (writable)
    default environment : C:\Werkplaats\AIDM_project\AIDM_H\env_aidm
       envs directories : C:\Werkplaats\AIDM_project\AIDM_H\env_aidm\envs
          package cache : C:\Werkplaats\AIDM_project\AIDM_H\env_aidm\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-32/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-32/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : None
           offline mode : False
```

</p>
</details>

**Comment by msarahan** [comment]
This bug report was for a conda version that is approximately 2 years old and definitely not supported. If anyone can reproduce this with a current conda version, maybe we can say more. Cleaning the package cache with "conda clean -a” might help.

**Comment by Vivek1717** [comment]
I am getting the below error when installed anaconda3 with python 3.7.6 on windows10:

conda install -c bioninja gseapy
..
..

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install -c bioninja gseapy`
    Traceback (most recent call last):
      File "C:\Python3.7\lib\site-packages\conda\install.py", line 201, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python3.7\\pkgs\\menuinst-1.4.7-py36_0\\info\\has_prefix'
