### ISSUE TITLE
Error updating numpy: "ValidationError: Value for sha256 cannot be None."

### ISSUE THREAD

**Issue by melaniefp** [conda/conda#8077]
**I'm submitting a...**
  - [X ] bug report
  - [ ] feature request

## Current Behavior

I am trying to update the current version of numpy to the newest available, but get an error, see bug report below.

### Steps to Reproduce

```
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x  (read only)
    default environment : /n/home11/mfernandezpradier/.conda/envs/bnn
       envs directories : /n/home11/mfernandezpradier/.conda/envs
                          /n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/envs
          package cache : /n/home11/mfernandezpradier/.conda/envs/.pkgs
                          /n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/pkgs
           channel URLs : https://conda.anaconda.org/anaconda/linux-64
                          https://conda.anaconda.org/anaconda/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/2.7.13 Linux/3.10.0-693.21.1.el7.x86_64 CentOS Linux/7.4.1708 glibc/2.17
                UID:GID : 11822:403036



`$ /n/home11/mfernandezpradier/.conda/envs/bnn/bin/conda install -c anaconda numpy`




    Traceback (most recent call last):
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/n/sw/fasrcsw/apps/Core/Anaconda/4.3.0-fasrc01/x/lib/python2.7/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    ValidationError: Value for sha256 cannot be None.

```

## Expected Behavior

Should have re-installed numpy successfully.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by wulmer** [comment]
This is an issue with a too old conda version. A few (newer?) packages have a different meta data setup so the old conda version doesn't recognize it properly.
The old `https://repo.continuum.io/pkgs/free/` channel should only contain packages which are recognized correctly by your old conda version whereas the `https://conda.anaconda.org/anaconda/` channel also contains newer packages (of which some might have this kind of metadata).
So either upgrade conda or make sure not to use the `anaconda` channel.

**Comment by melaniefp** [comment]
This is very useful, thanks!
