### ISSUE TITLE
Broken conda-canary conda (Anaconda 2018.12)

### ISSUE THREAD

**Issue by salamanderrake** [conda/conda#8079]
## Current Behavior
Broken conda/anaconda install

### Steps to Reproduce
Update conda to conda-canary

```
conda install -c conda-canary conda
```

## Expected Behavior
Working conda/anaconda inviroment

## Environment Information

<details open><summary><code>`conda info`</code></summary><p>

```
Traceback (most recent call last):
  File "./conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Traceback (most recent call last):
  File "./conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Traceback (most recent call last):
  File "./conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
</p></details>

**Comment by salamanderrake** [comment]
I may need to delete this bug report, as the initial issue may not be related to conda-canary

**Comment by salamanderrake** [comment]
The above command did not break conda, I will make a separate bug, in the proper channel, about my issue.
