### ISSUE TITLE
Anaconda from command prompt cant load package correctly

### ISSUE THREAD

**Issue by erfannariman** [conda/conda#8126]
So I want to run a python script which will be started from an external program, and I want to use python.exe in the Anaconda folder for this.

I have definitely installed `pandas` en `numpy` correctly, since I checked this through the Anaconda Prompt with `conda update pandas` and `conda update numpy`. Both were up to date.

So when I start my command prompt and start python with:
`C:\Users\Username\Anaconda3\python.exe`

It correctly start Python 3.7.1

But when I run `import pandas as pd` it gives me the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Username\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
```

So this is weird part one.

When I try `import numpy as np`, i get the following:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\pandas\__init__.py", line 19, in <module>
    "Missing required dependencies {0}".format(missing_dependencies))
ImportError: Missing required dependencies ['numpy']
>>> import numpy as np
Traceback (most recent call last):
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\Erfan Nariman\Anaconda3\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified module could not be found.
```

Does anyone know whats causing this and how I can solve this?
Because I can load these packages in my `jupyter notebook`

Is this a known issue or a bug?

Plus im curious if I did something wrong while installing packages, so I can avoid this in the future.

Thanks.

**Comment by dla06c** [comment]
Hope you don't mind me hopping on your thread, ErfPy, and also asking for any help in resolving the issue. 

I'm running into the exact same problem for pandas, though I do not get the same error for numpy. 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'numpy'

I've dredged the internet and have not found any solutions. I've gone into Anaconda Command Prompt and checked for any updates pandas or numpy may need. 

I've tried several scripts with pandas in the Spyder, which run flawlessly. 

When I launch the C:\Users\logan\Anaconda3\python.exe and try to manually enter the same script, it falls over at import pandas as pd.

I tried chatting with Spyder about the issue, but they said it is not a Spyder issue and basically refused to entertain the question.

**Comment by msarahan** [comment]
You need to use an activated prompt.  Because Windows depends on PATH to find libraries, and we don't modify PATH by default, python has no idea how to load numpy's libraries.  Spyder and anaconda prompt both work because they are using conda's activation to modify PATH.

**Comment by Pirouz-Nourian** [comment]
@msarahan thanks for sharing your insight. I am running into the same issue continuously. Could you please elaborate on how to 'activate' a python executable (from within python?) or how to modify the PATH variable manually?
