### ISSUE TITLE
Ansible post-installation error

### ISSUE THREAD

**Issue by michaelthomasclark** [conda/conda#8129]
### Steps to Reproduce

After installing Ansible using "conda install -c conda-forge ansible" I try to confirm the Ansible version using "ansible --version" command, but get the following instead:
```
Traceback (most recent call last):
  File "/Applications/anaconda/bin/conda", line 6, in <module>
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 120, in main
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main.py", line 130, in args_func
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/main_install.py", line 69, in execute
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/cli/install.py", line 407, in install
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/plan.py", line 600, in execute_actions
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 136, in execute_instructions
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/instructions.py", line 79, in LINK_CMD
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/install.py", line 1071, in link
  File "/Applications/anaconda/lib/python3.5/site-packages/conda/install.py", line 417, in update_prefix
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/anaconda/lib/python3.5/site-packages/nacl/_sodium.cpython-35m-darwin.so'
```

## Expected Behavior

Ansible version # should be returned.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
"No such file or directory" (even though executed from "anaconda" directory)
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
"No such file or directory" 
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
"No such file or directory" 
```
</p></details>

**Comment by msarahan** [comment]
This seems to be a problem with the conda-forge package.  Conda-forge is a 3rd party organization (which Anaconda, Inc. participates in, but does not own nor administer).  You need to take it up on the issue tracker for that package ("ansible-feedstock")

**Comment by michaelthomasclark** [comment]
Thanks Mike!
