### ISSUE TITLE
ERROR conda.core.link:_execute(507): An error occurred while installing package

### ISSUE THREAD

**Issue by prusse-martin** [conda/conda#8137]
This differs from #8038 `ERROR conda.core.link:_execute(507)` because I suspect it has to do with `noarch`python` packages and the "Current Behavior" is a little different.

## Current Behavior

     On windows the update environment action fails with:
     ```
        00:00:14 Solving environment: ...working... done
        00:00:18 
        00:00:18 # All requested packages already installed.
        00:00:18 
        00:00:20 Solving environment: ...working... done
        00:00:28 Preparing transaction: ...working... done
        00:00:29 Verifying transaction: ...working... done
        00:00:31 Executing transaction: ...working... failed
        00:00:33 ERROR conda.core.link:_execute(507): An error occurred while installing package 'mirror-conda-forge::identify-1.2.0-py_0'.
        00:00:33 PermissionError(13, 'Permission denied')
        00:00:33 Attempting to roll back.
        00:00:33 
        00:00:33 Rolling back transaction: ...working... done
        00:00:37 
        00:00:37 PermissionError(13, 'Permission denied')
     ```

### Steps to Reproduce

```
    1. Create a lot of environments (or a large environment) with lots of "noarch python" packages with entry points (we got 139 environments in the build machine at the time of the error, no info about the "noarch" packages);
    2. Remove the `conda-meta/history` file (not sure if this is necessary, but this is part of our build process);
    3. Try to update the first created environment with a different version of a "noarch python" package with an entry point;
```

    In the first step conda should create a lot of hard links to `conda.exe` (windows 10 has a limit of 1023 hard links per file) then when trying to update then first environment it will try to update the entry point linked and fail.

## Expected Behavior

    The environment is updated without problems (given no package conflict, disk issue, ...).

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
C:\Users\jenkins>conda info

     active environment : None
       user config file : C:\Users\jenkins\.condarc
 populated config files : W:\Miniconda\.condarc
          conda version : 4.5.12
    conda-build version : 3.15.1
         python version : 3.6.5.final.0
       base environment : W:\Miniconda  (writable)
           channel URLs : https://<in-house-mirror-server>/conda-channel/esss/win-64
                          https://<in-house-mirror-server>/conda-channel/esss/noarch
                          https://<in-house-mirror-server>/conda-channel/mirror-main/win-64
                          https://<in-house-mirror-server>/conda-channel/mirror-main/noarch
                          https://<in-house-mirror-server>/conda-channel/mirror-conda-forge/win-64
                          https://<in-house-mirror-server>/conda-channel/mirror-conda-forge/noarch
          package cache : W:\Miniconda\pkgs
                          C:\Users\jenkins\AppData\Local\conda\conda\pkgs
       envs directories : W:\Miniconda\envs
                          C:\Users\jenkins\AppData\Local\conda\conda\envs
                          C:\Users\jenkins\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
C:\Users\jenkins>conda config --show-sources
==> W:\Miniconda\.condarc <==
allow_softlinks: False
create_default_packages:
  - pip
  - python
use_pip: False
channel_alias: https://<in-house-mirror-server>/conda-channel/
channels:
  - https://<in-house-mirror-server>/conda-channel/esss
  - https://<in-house-mirror-server>/conda-channel/mirror-main
  - https://<in-house-mirror-server>/conda-channel/mirror-conda-forge
show_channel_urls: True
always_yes: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
 C:\Users\jenkins>conda list --show-channel-urls
# packages in environment at W:\Miniconda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py36_0    defaults
beautifulsoup4            4.7.1                 py36_1001    mirror-conda-forge
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.4.16                py36_0    defaults
cffi                      1.11.5           py36h945400d_0    defaults
chardet                   3.0.4            py36h420ce6e_1    defaults
conda                     4.5.12                py36_1000    mirror-conda-forge
conda-build               3.15.1                   py36_0    mirror-conda-forge
conda-devenv              1.0.4                      py_1    mirror-conda-forge
conda-env                 2.6.0                h36134e3_1    defaults
conda-execute             0.9.0                      py_0    mirror-conda-forge
console_shortcut          0.1.1                h6bb2dd7_3    defaults
cryptography              2.2.2            py36hfa6e2cd_0    defaults
filelock                  3.0.10                     py_0    mirror-conda-forge
glob2                     0.6                        py_0    mirror-conda-forge
idna                      2.6              py36h148d497_1    defaults
jinja2                    2.10                       py_1    mirror-conda-forge
markupsafe                1.1.0           py36hfa6e2cd_1000    mirror-conda-forge
menuinst                  1.4.11           py36hfa6e2cd_0    defaults
mu_repo                   1.8.0                      py_0    mirror-conda-forge
openssl                   1.0.2o               h8ea7d77_0    defaults
pip                       9.0.3                    py36_0    defaults
pkginfo                   1.5.0.1                    py_0    mirror-conda-forge
psutil                    5.4.8           py36hfa6e2cd_1000    mirror-conda-forge
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18             py36hd053e01_1    defaults
pyopenssl                 17.5.0           py36h5b7d817_0    defaults
pysocks                   1.6.8                    py36_0    defaults
python                    3.6.5                h0c2934d_0    defaults
pytz                      2018.9                     py_0    mirror-conda-forge
pywin32                   223              py36hfa6e2cd_0    defaults
pyyaml                    3.13            py36hfa6e2cd_1001    mirror-conda-forge
requests                  2.18.4           py36h4371aae_1    defaults
ruamel_yaml               0.15.35          py36hfa6e2cd_1    defaults
setuptools                39.0.1                   py36_0    defaults
six                       1.11.0           py36h4db2310_1    defaults
soupsieve                 1.7.1                 py36_1000    mirror-conda-forge
tqdm                      4.29.1                     py_0    mirror-conda-forge
urllib3                   1.22             py36h276f60a_0    defaults
vc                        14                   h0510ff6_3    defaults
virtualenv                16.0.0                py36_1000    mirror-conda-forge
vs2015_runtime            14.0.25123                    3    defaults
wheel                     0.31.0                   py36_0    defaults
win_inet_pton             1.0.1            py36he67d7fd_1    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
yaml                      0.1.7                    vc14_0  [vc14]  mirror-conda-forge
```
</p></details>

<details><summary>This problem have been plaguing us for some time now but just yesterday I have been able to investigate a little.</summary><p>
Running `conda env update -v -v -v > update.out.txt 2>&1` at the end of the output on could find:

```
Traceback (most recent call last):
  File "W:\Miniconda\lib\site-packages\conda\gateways\disk\create.py", line 323, in create_link
    link(src, dst)
  File "W:\Miniconda\lib\site-packages\conda\gateways\disk\link.py", line 62, in win_hard_link
    raise CondaOSError('win32 hard link failed\n  src: %s\n  dst: %s' % (src, dst))
conda.exceptions.CondaOSError: win32 hard link failed
  src: W:\Miniconda\Scripts\conda.exe
  dst: W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\Miniconda\lib\site-packages\conda\core\link.py", line 561, in _execute_actions
    action.execute()
  File "W:\Miniconda\lib\site-packages\conda\core\path_actions.py", line 385, in execute
    force=context.force)
  File "W:\Miniconda\lib\site-packages\conda\gateways\disk\create.py", line 330, in create_link
    copy(src, dst)
  File "W:\Miniconda\lib\site-packages\conda\gateways\disk\create.py", line 272, in copy
    _do_copy(src, dst)
  File "W:\Miniconda\lib\site-packages\conda\gateways\disk\create.py", line 285, in _do_copy
    with open(dst, 'wb') as fdst:
PermissionError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\Miniconda\lib\site-packages\conda\core\link.py", line 498, in _execute
    cls._execute_actions(pkg_idx, axngroup)
  File "W:\Miniconda\lib\site-packages\conda\core\link.py", line 579, in _execute_actions
    reverse_excs,
conda.CondaMultiError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "W:\Miniconda\lib\site-packages\conda\exceptions.py", line 819, in __call__
    return func(*args, **kwargs)
  File "W:\Miniconda\lib\site-packages\conda_env\cli\main.py", line 74, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "W:\Miniconda\lib\site-packages\conda_env\cli\main_update.py", line 126, in execute
    installer.install(prefix, specs, args, env)
  File "W:\Miniconda\lib\site-packages\conda_env\installers\conda.py", line 39, in install
    unlink_link_transaction.execute()
  File "W:\Miniconda\lib\site-packages\conda\core\link.py", line 228, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "W:\Miniconda\lib\site-packages\conda\core\link.py", line 526, in _execute
    rollback_excs,
conda.CondaMultiError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'
```

Given the offending file is `identify-cli.exe` after running `cat update.out.filered.txt | grep -n identify-cli.exe > update.out.grep.txt`:

```
20146:TRACE conda.core.path_actions:execute(1041): renaming Scripts/identify-cli.exe => Scripts/identify-cli.exe.c~
20147:TRACE conda.gateways.disk.delete:rm_rf(34): rm_rf W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe.c~
20148:INFO conda.gateways.disk.delete:_unlink(118): Windows thinks file W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe.c~ is in use.  We have scheduled it for removal at next reboot.
20149:INFO conda.gateways.disk.delete:rm_rf(58): rm_rf failed for W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe.c~
20150:TRACE conda.gateways.disk.update:rename(52): renaming W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe => W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe.c~
21936:TRACE conda.core.path_actions:execute(383): linking W:\Miniconda\Scripts\conda.exe => W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21937:INFO conda.gateways.disk.create:create_link(315): file exists, but clobbering: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'
21938:TRACE conda.gateways.disk.delete:rm_rf(34): rm_rf W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21939:INFO conda.gateways.disk.delete:_unlink(118): Windows thinks file W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe is in use.  We have scheduled it for removal at next reboot.
21940:INFO conda.gateways.disk.delete:rm_rf(58): rm_rf failed for W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21941:TRACE conda.gateways.disk.create:create_link(322): hard linking W:\Miniconda\Scripts\conda.exe => W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21944:  dst: W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21948:  dst: W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21950:  dst: W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21951:TRACE conda.gateways.disk.create:_do_copy(276): copying W:\Miniconda\Scripts\conda.exe => W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21952:DEBUG conda.core.link:_execute_actions(567): Error in action #15 for pkg_idx #14 LinkPathAction(target_prefix='W:\\Miniconda\\envs\\_simbr20gui-win64-py36', target_short_path='Scripts/identify-cli.exe', source_prefix='W:\\Miniconda', source_short_path='Scripts/conda.exe', link_type=<LinkType.hardlink: 1>, _execute_successful=False, source_path_data=PathDataV1(_path='Scripts/identify-cli.exe', path_type='windows_python_entry_point_exe'), prefix_path_data=PathDataV1(_path='Scripts/identify-cli.exe', path_type='windows_python_entry_point_exe'), _verified=True)
21960:  dst: W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
21975:PermissionError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'
23838:TRACE conda.core.path_actions:reverse(1046): reversing rename Scripts/identify-cli.exe.c~ => Scripts/identify-cli.exe
23839:TRACE conda.gateways.disk.delete:rm_rf(34): rm_rf W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
23840:INFO conda.gateways.disk.delete:_unlink(118): Windows thinks file W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe is in use.  We have scheduled it for removal at next reboot.
23841:INFO conda.gateways.disk.delete:rm_rf(58): rm_rf failed for W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
23842:TRACE conda.gateways.disk.update:rename(52): renaming W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe.c~ => W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
42226:  dst: W:\Miniconda\envs\_simbr20gui-win64-py36\Scripts\identify-cli.exe
42241:PermissionError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'
42250:conda.CondaMultiError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'
42268:conda.CondaMultiError: [Errno 13] Permission denied: 'W:\\Miniconda\\envs\\_simbr20gui-win64-py36\\Scripts\\identify-cli.exe'
```

Using `fsutil.exe hardlink list` I found out `identify-cli.exe` is linked to `conda.exe` and the total number of hard links is 1023.
Looks like that when updating `identify-cli.exe` it fails to unlink (the file is open), after rename rm fails and the rename is rolled back, when tring to clobber the file it fails again (can't open for writing).
</p></details>

**Comment by prusse-martin** [comment]
cc @nicoddemus

**Comment by prusse-martin** [comment]
We started to remove the history file since on some conda release the `--prune` flag behavior had changed.
Developers working on different branches in the build servers we reuse the environments, since the branches usually have litle difference between the required environment this account for a few updates (and not a full environment creation).

Given:

```yaml
# environment1.yml
name: foo
dependencies:
- a
- b  # b is not a dependency of "a";
```

```yaml
# environment2.yml
name: foo
dependencies:
- a
```

How `--prune` changed:

- In the old behavior when calling `conda env update --prune -f environment1.yml` then `conda env update --prune -f environment2.yml` would cause the "b" package to be **removed** form the "foo" environment.

- Why we started to remove the history file? When calling `conda env update --prune -f environment1.yml` then `conda env update --prune -f environment2.yml` would cause the "b" package to be **present** in the "foo" environment.

I will try to get a better "Steps to Reproduce" without the "Remove the `conda-meta/history` file".

**Comment by prusse-martin** [comment]
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>


```
λ conda info

     active environment : None
       user config file : C:\Users\prusse\.condarc
 populated config files : W:\test_ww\.condarc
          conda version : 4.5.12
    conda-build version : 3.15.1
         python version : 3.6.5.final.0
       base environment : D:\Miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : W:\test_ww\envs\.pkgs
       envs directories : W:\test_ww\envs
                          D:\Miniconda\envs
                          C:\Users\prusse\AppData\Local\conda\conda\envs
                          C:\Users\prusse\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>


<details open><summary><code>`conda config --show-sources`</code></summary><p>


```
λ conda config --show-sources
==> W:\test_ww\.condarc <==
allow_softlinks: False
notify_outdated_conda: False
create_default_packages:
  - pip
  - python
safety_checks: disabled
rollback_enabled: False
use_pip: False
envs_dirs:
  - W:\test_ww\\envs
pkgs_dirs:
  - W:\test_ww\\envs\.pkgs
channels:
  - conda-forge
  - defaults
show_channel_urls: True
always_yes: True

==> envvars <==
envs_path:
  - W:\test_ww\\envs
```
</p></details>

I failed to reproduce the `PermissionError(13, 'Permission denied')` error locally, but I got other error that is probably related to the hard link limit.
Without deleting history files (*conda.exe* has a low hard link count at the start).

1. Run `FOR /L %a IN (0,1,114) DO conda env update --prune -f environment.yaml -n hard_link_win_%a`;
2. Run `conda env update --prune -f environment_updated.yaml -n hard_link_win_0` (no errors);
3. Run `conda env update --prune -f environment.yaml -n hard_link_win_0` results in error:

    ```
    W:\test_ww\Projects
    λ conda env update --prune -f environment.yaml -n hard_link_win_0
    Solving environment: done
    Preparing transaction: done
    Executing transaction: \ WARNING conda.gateways.disk:exp_backoff_fn(49): Uncaught backoff with errno EEXIST 17
    failed
    ERROR conda.core.link:_execute(507): An error occurred while uninstalling package 'conda-forge::identify-1.1.8-py_0'.
    FileExistsError(17, 'Cannot create a file when that file already exists')
    Attempting to roll back.


    FileExistsError(17, 'Cannot create a file when that file already exists')
    ```
After getting the error I did `conda env update --prune -f environment.yaml -n hard_link_win_0 -v -v -v > update-v3.with-history.txt 2>&1`.


[condarc.zip](https://github.com/conda/conda/files/2797180/condarc.zip)
[environment.zip](https://github.com/conda/conda/files/2797162/environment.zip)
[environment_updated.zip](https://github.com/conda/conda/files/2797164/environment_updated.zip)
[update-v3.with-history.txt.zip](https://github.com/conda/conda/files/2797165/update-v3.with-history.txt.zip)

**Comment by prusse-martin** [comment]
Sorry for letting this thread in the void for so long.
After the conda 4.6.* update along a broken package fixed (could there be more I am not sure).
Errors like the ones I reported here did not show up again.

The broken package I remember was linking a file with the same name as one used as entry point by a `noarch: python`, and while I was investigating the problem with a friend it just started working (they did just released a build without that file).
I can't remember the package's name =)
