### ISSUE TITLE
After `conda install jinja2`, the `conda build` command fails

### ISSUE THREAD

**Issue by certik** [conda/conda#814]
`conda build` used to work, but it was saying
```
There was an error importing jinja2.
Please run `conda install jinja2` to enable jinja template support
```
So I did that. Now it does not work:
```
ondrej@kittiwake:~/repos/conda-recipes(csympy)$ conda build csympy/
Traceback (most recent call last):
  File "/scratch/miniconda/bin/conda-build", line 5, in <module>
    sys.exit(main())
  File "/scratch/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 93, in main
    args.func(args, p)
  File "/scratch/miniconda/lib/python2.7/site-packages/conda_build/main_build.py", line 196, in execute
    m = MetaData(recipe_dir)
  File "/scratch/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 187, in __init__
    self.meta = parse(get_contents(self.meta_path))
  File "/scratch/miniconda/lib/python2.7/site-packages/conda_build/metadata.py", line 164, in get_contents
    loaders = [jinja2.PackageLoader('conda_build'),
  File "/scratch/miniconda/lib/python2.7/site-packages/jinja2/loaders.py", line 212, in __init__
    from pkg_resources import DefaultProvider, ResourceManager, \
ImportError: No module named pkg_resources
```

**Comment by csoja** [comment]
confirmed that jinja2 now depends on setuptools.  Closing issue.
