### ISSUE TITLE
Mayavi installation issue

### ISSUE THREAD

**Issue by RamiGASMI** [conda/conda#8148]
Hi every one, 

I have this message error when installing mayavi, can any one help me with that:

Traceback (most recent call last):
  File "setup.py", line 385, in <module>
    config = configuration().todict()
  File "setup.py", line 351, in configuration
    config.add_subpackage('tvtk')
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\distutils\misc_util.py", line 1036, in add_subpackage
    caller_level = 2)
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\distutils\misc_util.py", line 1005, in get_subpackage
    caller_level = caller_level + 1)
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\distutils\misc_util.py", line 942, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
  File "tvtk\setup.py", line 65, in configuration
    if can_compile_extensions():
  File "tvtk\setup.py", line 27, in can_compile_extensions
    lang='c'
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\distutils\command\config.py", line 227, in try_compile
    self._compile(body, headers, include_dirs, lang)
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\distutils\command\config.py", line 133, in _compile
    self.compiler.compile([src], include_dirs=include_dirs)
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 315, in compile
    self.initialize()
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 208, in initialize
    vc_env = _get_vc_env(plat_spec)
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 81, in _get_vc_env
    vcvarsall, vcruntime = _find_vcvarsall(plat_spec)
  File "C:\Users\33624\AppData\Local\Programs\Python\Python35\lib\distutils\_msvccompiler.py", line 34, in _find_vcvarsall
    access=winreg.KEY_READ | winreg.KEY_WOW64_32KEY
FileNotFoundError: [WinError 2] file not found

**Comment by soapy1** [comment]
could you provide the command you are using as well as the output of `conda info`
