### ISSUE TITLE
conda update -n base conda fails

### ISSUE THREAD

**Issue by roxyboy** [conda/conda#8153]
I've been getting the warning to update conda recently when I update packages through conda:
```
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.9
  latest version: 4.6.1

Please update conda by running

    $ conda update -n base conda
```

However, when I do so, I get the following error:
```
$ conda update -n base conda
Solving environment: done

## Package Plan ##

  environment location: /usr/local/anaconda

  added / updated specs: 
    - conda


The following NEW packages will be INSTALLED:

    libcurl:            7.62.0-h20c2e04_0                  
    libedit:            3.1.20181209-hc058e9b_0            

The following packages will be UPDATED:

    anaconda-navigator: 1.7.0-py27_0                        --> 1.8.4-py27_0        
    ca-certificates:    2018.1.18-0             conda-forge --> 2018.12.5-0         
    certifi:            2018.1.18-py27_0        conda-forge --> 2018.11.29-py27_0   
    conda:              4.5.9-py27_0            conda-forge --> 4.6.1-py27_0        
    cryptography:       2.1.4-py27_0            conda-forge --> 2.4.2-py27h1ba5d50_0
    curl:               7.55.1-0                conda-forge --> 7.62.0-hbc83047_0   
    libgcc-ng:          7.2.0-h7cc24e2_2                    --> 8.2.0-hdf63c60_1    
    libssh2:            1.8.0-2                 conda-forge --> 1.8.0-h1ba5d50_4    
    libstdcxx-ng:       7.2.0-h7a57d05_2                    --> 8.2.0-hdf63c60_1    
    ncurses:            5.9-10                  conda-forge --> 6.1-he6710b0_1      
    openssl:            1.0.2n-0                conda-forge --> 1.1.1a-h7b6447c_0   
    python:             2.7.14-4                conda-forge --> 2.7.15-h9bab390_6   
    readline:           7.0-0                   conda-forge --> 7.0-h7b6447c_5      
    sqlite:             3.20.1-2                conda-forge --> 3.26.0-h7b6447c_0   
    tk:                 8.6.7-0                 conda-forge --> 8.6.8-hbc83047_0    

The following packages will be DOWNGRADED:

    pycurl:             7.43.0.1-py27hb7f436b_0             --> 7.19.0-py27_0       
    pyqt:               5.6.0-py27_4            conda-forge --> 4.11.4-py27_4       
    qt:                 5.6.2-7                 conda-forge --> 4.8.7-2             

Proceed ([y]/n)? y

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 14, in execute
        install(args, parser, 'update')
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 253, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 282, in handle_txn
        unlink_link_transaction.execute()
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 223, in execute
        self.verify()
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/common/io.py", line 46, in decorated
        return f(*args, **kwds)
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 200, in verify
        self.prepare()
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 192, in prepare
        stp.remove_specs, stp.update_specs)
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/core/link.py", line 282, in _prepare
        mkdir_p(transaction_context['temp_dir'])
      File "/usr/local/anaconda/lib/python2.7/site-packages/conda/gateways/disk/__init__.py", line 60, in mkdir_p
        makedirs(path)
      File "/usr/local/anaconda/lib/python2.7/os.py", line 157, in makedirs
        mkdir(name, mode)
    OSError: [Errno 13] Permission denied: '/usr/local/anaconda/.condatmp'

`$ /usr/local/anaconda/bin/conda update -n base conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=uptodate
        CONDA_PATH_BACKUP=/home/takaya/miniconda3/bin:/usr/lib64/qt-3.3/bin:/usr/local/anaconda/
                          bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/takaya/.lo
                          cal/bin:/home/takaya/bin
             CONDA_PREFIX=/home/takaya/miniconda3/envs/uptodate
         CONDA_PS1_BACKUP=[\u@\h \W]\$
               CONDA_ROOT=/usr/local/anaconda
              CONDA_SHLVL=0
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles
                     PATH=/home/takaya/miniconda3/envs/uptodate/bin:/home/takaya/miniconda3/bin:
                          /usr/lib64/qt-3.3/bin:/usr/local/anaconda/bin:/usr/local/bin:/usr/bin:
                          /usr/local/sbin:/usr/sbin:/home/takaya/.local/bin:/home/takaya/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : /home/takaya/miniconda3/envs/uptodate
    active env location : /home/takaya/miniconda3/envs/uptodate
            shell level : 0
       user config file : /home/takaya/.condarc
 populated config files : /home/takaya/.condarc
          conda version : 4.5.9
    conda-build version : 3.7.0
         python version : 2.7.14.final.0
       base environment : /usr/local/anaconda  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /usr/local/anaconda/pkgs
                          /home/takaya/.conda/pkgs
       envs directories : /home/takaya/.conda/envs
                          /usr/local/anaconda/envs
               platform : linux-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/2.7.14 Linux/3.10.0-693.17.1.el7.centos.plus.x86_64 centos/7 glibc/2.17
                UID:GID : 9848:9848
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
```

Is my conda version simply too old to be compatible or is this a conflict between `base` and `conda-forge` that I've using as my channel to update packages?
Thanks in advance for your help.

**Comment by msarahan** [comment]
It looks like you have a permission error on the .condatmp folder.  You need to fix your permissions so that you can write to that folder.

**Comment by djgreen** [comment]
I have the same issue. What should the permissions be for a multiuser environment? I installed using the instructions here: https://www.anaconda.com/rpm-and-debian-repositories-for-miniconda/ and there was no mention of having to adjust any permissions.

**Comment by ffyring** [comment]
I would like to bump this one for Windows 10. On my corporate computer, where I can't elevate privilegies, conda tries to write to
C:\Program Files\Anaconda3\.condatmp
The C:\Program Files directory is read-only though so it does not work.

It's reasonable to keep Progam Files read-only so I think anaconda should create the temporary files in either ProgramData or Temp directory.
