### ISSUE TITLE
Windows issue with Conda 4.6.1 - Path not found

### ISSUE THREAD

**Issue by Dr-Irv** [conda/conda#8156]
## Current Behavior
```
conda list bokeh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 81, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 116, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 145, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records

      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 69, in load
        self._load_site_packages()
      File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 258, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 245, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "C:\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init
        return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
      File "C:\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 400, in __init__
        super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
      File "C:\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__
        raise RuntimeError("Path not found: %s" % anchor_full_path)
    RuntimeError: Path not found: C:\Anaconda3\Lib\site-packages\Sphinx-1.3.1-py3.4.egg\EGG-INFO

`$ C:\Anaconda3\Scripts\conda-script.py list bokeh`
```

This happens with conda 4.6.1.  If I downgrade to conda 4.4.11, the error disappears.

### Steps to Reproduce
See above.

## Expected Behavior
No error message!

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
> conda info

     active environment : None
            shell level : 0
       user config file : C:\Users\irv.PCI\.condarc
 populated config files : C:\Users\irv.PCI\.condarc
          conda version : 4.6.1
    conda-build version : 3.15.1
         python version : 3.6.6.final.0
       base environment : C:\Anaconda3  (writable)
           channel URLs : http://conda.anaconda.org/gurobi/win-64
                          http://conda.anaconda.org/gurobi/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Anaconda3\pkgs
                          C:\Users\irv.PCI\.conda\pkgs
                          C:\Users\irv.PCI\AppData\Local\conda\conda\pkgs
       envs directories : C:\Anaconda3\envs
                          C:\Users\irv.PCI\.conda\envs
                          C:\Users\irv.PCI\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.1 requests/2.19.1 CPython/3.6.6 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
> conda config --show-sources
==> C:\Users\irv.PCI\.condarc <==
ssl_verify: True
channels:
  - http://conda.anaconda.org/gurobi
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

Same runtime error as reported above.

</p></details>

**Comment by msarahan** [comment]
You have some really old cruft lying around that is tripping things up somehow.  We need to improve the error handling here, but in the meantime, you can try to find references to this somewhere in your environment:

```C:\Anaconda3\Lib\site-packages\Sphinx-1.3.1-py3.4.egg\EGG-INFO```

Cleaning up those files or references should clear up the error.

**Comment by Dr-Irv** [comment]
@msarahan Thanks.  I removed that from the lib/site-packages directory, and now conda 4.6.1 is happy.

But, as you said, improving the error handling would be appreciated!

**Comment by kalefranz** [comment]
Conda was expecting `C:\Anaconda3\Lib\site-packages\Sphinx-1.3.1-py3.4.egg\EGG-INFO` here to be a real file.  I'm guessing that `Sphinx-1.3.1-py3.4.egg` is a zipped up egg, and the `EGG-INFO` file is embedded within the zipped egg.  I'm not yet completely sure what we should do here.  I don't like the idea of starting unpack/dig into `.egg` files, especially since they're basically all just legacy.  We should probably just skip .eggs in the conda-pip interop stuff, or maybe just raise warnings about them?

**Comment by Dr-Irv** [comment]
@kalefranz Here is what was in `C:\Anaconda3\Lib\site-packages\Sphinx-1.3.1-py3.4.egg\EGG-INFO`, in case this helps.  It did have the "build" listed as "<pip>" when I did `conda list` with conda 4.4.11, prior to me moving it out.

```
> dir /s Sphinx-1.3.1-py3.4.egg
 Volume in drive C is OS
 Volume Serial Number is B66A-A88B

 Directory of C:\temp\condakeep\Sphinx-1.3.1-py3.4.egg

09/05/2017  05:28 PM    <DIR>          .
09/05/2017  05:28 PM    <DIR>          ..
09/05/2017  05:28 PM    <DIR>          sphinx
               0 File(s)              0 bytes

 Directory of C:\temp\condakeep\Sphinx-1.3.1-py3.4.egg\sphinx

09/05/2017  05:28 PM    <DIR>          .
09/05/2017  05:28 PM    <DIR>          ..
09/05/2017  05:28 PM    <DIR>          pycode
               0 File(s)              0 bytes

 Directory of C:\temp\condakeep\Sphinx-1.3.1-py3.4.egg\sphinx\pycode

09/05/2017  05:28 PM    <DIR>          .
09/05/2017  05:28 PM    <DIR>          ..
12/22/2015  04:01 PM            19,375 Grammar-py3-sphinx1.3.pickle
               1 File(s)         19,375 bytes
```

**Comment by YvesCR** [comment]
Hi guys, stepped in the same error.
There was in my case the error message pointing to a file finishing by .egg for a package.
I deleted that folder and it stopped the error.

**Comment by n00b3rpwn4g3** [comment]
I had the same problem in conda 4.7.5, just to note that it still exists, and deleting the .egg file also worked in this version.

**Comment by AlexSCFraser** [comment]
I got this issue after uninstalling a package I'm developing and trying to run `conda list` to verify correct uninstallation. It appears that the package wasn't quite uninstalled fully because I had created some config files in the installation directory inside site_packages, which were not deleted when I used `conda remove packageName` so the directory still had a folder tree and some JSON files, but conda list seems to see that the the high level install directory in site-packages still exists and tries to read the package info and then crashes. Although this was my fault as a package developer (I have since moved all config files to the user's home directory), it seems common enough that I can think of a couple improvements:

- When `conda remove packageName` is run, it could check for this type of incomplete uninstallation and then notify the user of a broken uninstall process. I think this would help developers recognize their uninstallation method is broken during testing. It also might help users understand that this is a bug to report to the package developer, and not a problem with conda.

- `conda list` could note the package is broken on this error and then report a separate category of broken packages. This preserves the function of conda list with incompletely or incorrectly un/installed packages and lets the user/developer know that they have a broken package to either cleanup or fix the un/install process for.
