### ISSUE TITLE
AttributeError: 'module' object has no attribute 'getproxies'

### ISSUE THREAD

**Issue by MLnick** [conda/conda#817]
Hi

I got this error - I think I mistakenly did `brew upgrade python` instead of going via `conda`. Now things work but when I try to update it breaks. I removed conda comletely and reinstalled from scratch and still getting this error.

Also tried removing existing brew pythons (both 2.7.5 and 2.7.8) so only conda python is left but to no avail.

```
$ conda update scikit-learn
Fetching package metadata: An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "//anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    args.func(args, p)
  File "//anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 39, in execute
    install.install(args, parser, 'update')
  File "//anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 184, in install
    unknown=args.unknown)
  File "//anaconda/lib/python2.7/site-packages/conda/api.py", line 40, in get_index
    unknown=unknown)
  File "//anaconda/lib/python2.7/site-packages/conda/utils.py", line 77, in __call__
    value = self.func(*args, **kw)
  File "//anaconda/lib/python2.7/site-packages/conda/fetch.py", line 152, in fetch_index
    session = CondaSession()
  File "//anaconda/lib/python2.7/site-packages/conda/connection.py", line 60, in __init__
    self.proxies = get_proxy_servers()
  File "//anaconda/lib/python2.7/site-packages/conda/config.py", line 250, in get_proxy_servers
    return requests.utils.getproxies()
AttributeError: 'module' object has no attribute 'getproxies'
```

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.5.5
       python version : 2.7.7.final.0
     root environment : //anaconda  (writable)
  default environment : //anaconda
     envs directories : //anaconda/envs
        package cache : //anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False
```

**Comment by haraldschilly** [comment]
I had the same problem and I think removing my local requests installation `~/.local/lib/python2.7/site-packages/requests*` did solve it. (it was in sys.path)

**Comment by asmeurer** [comment]
@RainerHilscher your error looks like a different one (this issue was about `getproxies`, whereas your error is about `GzipFile`). Can you paste the traceback?
