### ISSUE TITLE
nb_conda_kernels - ImportError: DLL load failed

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8171]
***Update:*** It appears to be `nb_conda_kernels` causing the error
https://github.com/AnacondaRecipes/nb_conda_kernels-feedstock/issues/1

<hr>
I'm trying to install a very large (python 3.7.2) analytics environment on win64 using conda 4.6.1.

When conda gets to the `Executing transaction` part of the install I get a DLL error from `nb_conda_kernels`/`zmq` which then causes conda to roll back the entire install:
```
<SNIP>
Preparing transaction: done
Verifying transaction: done
Executing transaction: | DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Miniconda3\envs\py-dev', env_name: 'py-dev', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(320): Shortcut cmd is %windir%\System32\cmd.exe, args are ['"/K"', 'C:\\Miniconda3\\Scripts\\activate.bat', 'C:\\Miniconda3\\envs\\py-dev']
| DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Miniconda3\envs\py-dev',env_name: 'py-dev', mode: 'system', used_mode: 'system'
DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Miniconda3\python.exe, args are ['C:\\Miniconda3\\cwp.py', 'C:\\Miniconda3\\envs\\py-dev', 'C:\\Miniconda3\\envs\\py-dev\\python.exe', 'C:\\Miniconda3\\envs\\py-dev\\Scripts\\jupyter-notebook-script.py', '"%USERPROFILE%/"']
\ _cffi_ext.c
C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(213): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "C:\Miniconda3\envs\py-dev\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Miniconda3\envs\py-dev\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\nb_conda_kernels\__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\nb_conda_kernels\manager.py", line 13, in <module>
    from jupyter_client.kernelspec import KernelSpecManager, KernelSpec, NoSuchKernel
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.

failed
ERROR conda.core.link:_execute(543): An error occurred while installing package 'anaconda::nb_conda_kernels-2.2.0-py37_0'.
LinkError: post-link script failed for package anaconda::nb_conda_kernels-2.2.0-py37_0
running your command again with `-v` will provide additional information
location of failed script: C:\Miniconda3\envs\py-dev\Scripts\.nb_conda_kernels-post-link.bat
==> script messages <==
_cffi_ext.c
C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(213): fatal error C1083: Cannot open include file: 'sys/un.h': No such file or directory
Traceback (most recent call last):
  File "C:\Miniconda3\envs\py-dev\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Miniconda3\envs\py-dev\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\nb_conda_kernels\__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\nb_conda_kernels\manager.py", line 13, in <module>
    from jupyter_client.kernelspec import KernelSpecManager, KernelSpec, NoSuchKernel
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Miniconda3\envs\py-dev\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: The specified module could not be found.


Attempting to roll back.
<SNIP>
```

This might well be a packaging problem rather than a conda problem.

I'm just posting here for informational purposes and to capture the error. I'll do some more testing and update the issue if I find it's an error in either `nb_conda_kernels` or `zmq`

**Comment by dhirschfeld** [comment]
Note to self - try @mingwandroid's packages:
https://gitter.im/conda-forge/conda-forge.github.io?at=5c4f4a8dca428b0645184fb5

**Comment by dhirschfeld** [comment]
The reason for the DLL error is the incorrect packaging in `AnacondaRecipes` of both `zmq` and `pyzmq`

***xref:***
 - https://github.com/AnacondaRecipes/pyzmq-feedstock/issues/2
 - https://github.com/AnacondaRecipes/zeromq-feedstock/issues/4

**Comment by dhirschfeld** [comment]
## Minimal Reproducer
```
conda create -n test python=3.7* ipython conda-forge::zeromq defaults::pyzmq nb_conda_kernels
```

**Comment by dhirschfeld** [comment]
Closing as I believe this was fixed in https://github.com/conda/conda/pull/8229
