### ISSUE TITLE
conda-pip interop problem with reading .eggs

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#8175]
```
error: RuntimeError('Path not found: c:\\Users\\fabienma\\AppData\\Local\\Continuum\\Anaconda3\\Lib\\site-packages\\Sphinx-1.5.6-py3.6.egg\\EGG-INFO')
command: c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py list
user_agent: conda/4.6.1 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17134
_messageid: -9223372036617369293
_messagetime: 1548786681199 / 2019-01-29 12:31:21

Traceback (most recent call last):
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 81, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
    show_channel_urls=context.show_channel_urls)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
    show_channel_urls=show_channel_urls)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
    installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 116, in iter_records
    return itervalues(self._prefix_records)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 145, in _prefix_records
    return self.__prefix_records or self.load() or self.__prefix_records
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 69, in load
    self._load_site_packages()
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 258, in _load_site_packages
    python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 245, in read_python_record
    pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init
    return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 400, in __init__
    super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
  File "c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__
    raise RuntimeError("Path not found: %s" % anchor_full_path)
RuntimeError: Path not found: c:\Users\fabienma\AppData\Local\Continuum\Anaconda3\Lib\site-packages\Sphinx-1.5.6-py3.6.egg\EGG-INFO
```

My guess is that the `EGG-INFO` file is embedded in the .egg zip.  Not sure how to handle this without spending more time on it.

**Comment by kalefranz** [comment]
Closing. This is the same issue reported in https://github.com/conda/conda/issues/8156
