### ISSUE TITLE
conda 4.6.1 win32file import problems

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#8177]
There were 89 of these over the last 24 hours for 4.6.1.

```
error: ImportError('DLL load failed: The specified module could not be found.')
command: C:\Anaconda3\scripts\conda-script.py install -p C:\Anaconda3 -y scikit-learn==0.20.2
user_agent: conda/4.6.1 requests/2.21.0 CPython/3.7.2 Windows/10 Windows/10.0.17763
_messageid: -9223372036617068541
_messagetime: 1548841320036 / 2019-01-30 03:42:00

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 8, in <module>
    from .install import install
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 18, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 13, in <module>
    from .envs_manager import USER_ENVIRONMENTS_TXT_FILE, register_env, unregister_env
  File "C:\Anaconda3\lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
    from .prefix_data import PrefixData
  File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 22, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 17, in <module>
    from .delete import rm_rf
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 20, in <module>
    import win32file
ImportError: DLL load failed: The specified module could not be found.
```
---

```
error: ImportError('Module use of python36.dll conflicts with this version of Python.')
command: C:\Users\user\Anaconda3\Scripts\conda-script.py list
user_agent: conda/4.6.1 requests/2.18.4 CPython/3.7.1 Windows/10 Windows/10.0.17134
_messageid: -9223372036617068939
_messagetime: 1548834926405 / 2019-01-30 01:55:26

Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\user\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 22, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 17, in <module>
    from .delete import rm_rf
  File "C:\Users\user\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 20, in <module>
    import win32file
ImportError: Module use of python36.dll conflicts with this version of Python.
```

---

```
error: ImportError('Module use of python37.dll conflicts with this version of Python.',)
command: C:\Anaconda3\Scripts\conda-script.py install -p C:/Anaconda3 tensorflow -y
user_agent: conda/4.6.1 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.16299
_messageid: -9223372036617068732
_messagetime: 1548838201551 / 2019-01-30 02:50:01

Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "C:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 8, in <module>
    from .install import install
  File "C:\Anaconda3\lib\site-packages\conda\cli\install.py", line 18, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 13, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 13, in <module>
    from .envs_manager import USER_ENVIRONMENTS_TXT_FILE, register_env, unregister_env
  File "C:\Anaconda3\lib\site-packages\conda\core\envs_manager.py", line 11, in <module>
    from .prefix_data import PrefixData
  File "C:\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 22, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 17, in <module>
    from .delete import rm_rf
  File "C:\Anaconda3\lib\site-packages\conda\gateways\disk\delete.py", line 20, in <module>
    import win32file
ImportError: Module use of python37.dll conflicts with this version of Python.
```

**Comment by msarahan** [comment]
good news!  I'm pretty sure this is all gone in 4.6.2 with the rm_rf rewrite.

**Comment by lunluen** [comment]
Hi, I'm one of the 89.
How to solve this?

I can not upgrade conda to 4.6.2 with conda or Navigator due to this issue: 
`ImportError: DLL load failed: The specified module could not be found.`

**Comment by msarahan** [comment]
@lunluen you've gotten stuck because the wrong DLL's are in place somehow.  This happens when a given DLL is in use when conda tries to install a different version of that DLL.  Windows does not allow DLLs that are in use to be removed.  

The easiest way to recover at this point is to reinstall anaconda or miniconda.  Unfortunately, there's no easy way to do this in-place on Windows that I know of.  You can save any environments you've created - just back up the "envs" folder and put it back in the same place after reinstalling.

The harder way is to try to identify exactly which DLLs are causing problems, and replace them by manually extracting them from conda packages you download by hand.
