### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'mkdir'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#8179]
```
error: AttributeError("'Namespace' object has no attribute 'mkdir'")
command: /Users/michaelrossi/anaconda3/bin/conda update --prefix /Users/michaelrossi/triton anaconda
user_agent: conda/4.6.1 requests/2.21.0 CPython/3.7.2 Darwin/18.2.0 OSX/10.14.2
_messageid: -9223372036617221015
_messagetime: 1548781730950 / 2019-01-29 11:08:50

Traceback (most recent call last):
  File "/Users/michaelrossi/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "/Users/michaelrossi/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/michaelrossi/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/michaelrossi/anaconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 21, in execute
    install(args, parser, 'update')
  File "/Users/michaelrossi/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 163, in install
    if args.mkdir:
AttributeError: 'Namespace' object has no attribute 'mkdir'
```

**Comment by eschellerup** [comment]
Similar error:
```
+ conda update conda -y

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 166, in install
        if args.mkdir:
    AttributeError: 'Namespace' object has no attribute 'mkdir'

`$ /opt/conda/bin/conda update conda -y`

  environment variables:
                 CIO_TEST=<not set>
             CONDA_PREFIX=/opt/conda/envs/app
               CONDA_ROOT=/opt/conda
                     PATH=/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin
                          :/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               http_proxy=<set>
              https_proxy=<set>

     active environment : app
    active env location : /opt/conda/envs/app
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.3.final.0
       base environment : /opt/conda  (writable)
           channel URLs : http://conda.int/pkgs/lbe/linux-64
                          http://conda.int/pkgs/lbe/noarch
                          http://conda.int/pkgs/main/linux-64
                          http://conda.int/pkgs/main/noarch
                          http://conda.int/pkgs/free/linux-64
                          http://conda.int/pkgs/free/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/4.15.0-48-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by jjhelmus** [comment]
@eschellerup Is there a conda environment in `/opt/conda/envs/app`?  If so can you provide provide the output of `conda list -p `/opt/conda/envs/app`?

**Comment by shailensobhee** [comment]
Same issue. `conda list` gives me:
`[user01@testm Downloads]$ conda list

EnvironmentLocationNotFound: Not a conda environment: /home/user01/miniconda3/envs/test
`

It's a fresh machine.

**Comment by Chars-Einstein** [comment]
I have entered a env named 's', but it didn't work either.
