### ISSUE TITLE
conda-env AttributeError object has no attribute 'copy'

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#8180]
```
error: AttributeError("'NoneType' object has no attribute 'copy'",)
command: /Users/Joris/anaconda3/bin/conda-env create --file /Users/Joris/Documents/Research/Code/Anaconda/anaconda3.yml
user_agent: conda/4.6.1 requests/2.21.0 CPython/3.6.8 Darwin/18.2.0 OSX/10.14.2
_messageid: -9223372036617067876
_messagetime: 1548852764680 / 2019-01-30 06:52:44

Traceback (most recent call last):
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/cli/main.py", line 73, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 77, in execute
    directory=os.getcwd())
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 40, in detect
    if spec.can_handle():
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
    self._environment = env.from_file(self.filename)
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 129, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 115, in from_yaml
    data = validate_keys(data, kwargs)
  File "/Users/Joris/anaconda3/lib/python3.6/site-packages/conda_env/env.py", line 32, in validate_keys
    new_data = data.copy()
AttributeError: 'NoneType' object has no attribute 'copy'
```

```
error: AttributeError("'str' object has no attribute 'copy'",)
command: C:\ProgramData\Anaconda3\Scripts\conda-env-script.py update -f=d:/work_folder/orange/conda_envs/base_enviroment.yaml
user_agent: conda/4.6.1 requests/2.18.4 CPython/3.6.4 Windows/10 Windows/10.0.17134
_messageid: -9223372036617070859
_messagetime: 1548799796355 / 2019-01-29 16:09:56

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 73, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_update.py", line 69, in execute
    directory=os.getcwd())
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
    if spec.can_handle():
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
    self._environment = env.from_file(self.filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 129, in from_file
    return from_yaml(yamlstr, filename=filename)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 115, in from_yaml
    data = validate_keys(data, kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 32, in validate_keys
    new_data = data.copy()
AttributeError: 'str' object has no attribute 'copy'
```

**Comment by niharikakrishnan** [comment]
I'm getting the same error via Azure. Has there been any fix?

**Comment by mikehinchey** [comment]
What's in your yml file?  I got this error when my `environment.yml` was empty.
