### ISSUE TITLE
conda init NotImplementedError

### ISSUE THREAD

**Issue by kalefranz** [conda/conda#8183]
```
error: NotImplementedError()
command: /Users/vadimivlev/anaconda3/bin/conda init --all
user_agent: conda/4.6.1 requests/2.21.0 CPython/3.7.1 Darwin/18.2.0 OSX/10.14.2
_messageid: -9223372036617070926
_messagetime: 1548798375941 / 2019-01-29 15:46:15

Traceback (most recent call last):
  File "/Users/vadimivlev/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1001, in __call__
    return func(*args, **kwargs)
  File "/Users/vadimivlev/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/vadimivlev/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 81, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/vadimivlev/anaconda3/lib/python3.7/site-packages/conda/cli/main_init.py", line 52, in execute
    anaconda_prompt)
  File "/Users/vadimivlev/anaconda3/lib/python3.7/site-packages/conda/core/initialize.py", line 105, in initialize
    plan2 = make_initialize_plan(conda_prefix, shells, for_user, for_system, anaconda_prompt)
  File "/Users/vadimivlev/anaconda3/lib/python3.7/site-packages/conda/core/initialize.py", line 459, in make_initialize_plan
    raise NotImplementedError()
NotImplementedError
```

**Comment by soapy1** [comment]
Fixed in 4.7.x
