### ISSUE TITLE
not able to install pytorch using conda

### ISSUE THREAD

**Issue by poornima198m** [conda/conda#8233]
(pytorch-1.0) C:\Users\Vineeth>conda install -n pytorch-1.0 pytorch torchvision cudatoolkit=9.0 -c pytorch
Collecting package metadata: done
Solving environment: done
C:\Users\Vineeth\Anaconda3\pkgs\conda-4.6.2-py36_0\Scripts\conda.exe.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash - Access is denied.
C:\Users\Vineeth\Anaconda3\pkgs\conda-4.6.2-py36_0\Scripts\conda.exe.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash - Access is denied.
C:\Users\Vineeth\Anaconda3\pkgs\conda-4.6.2-py36_0\Scripts\conda.exe.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash.trash - Access is denied.

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 294, in _make_single_record
        repodata_record = read_repodata_json(extracted_package_dir)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 126, in read_repodata_json
        with open(join(extracted_package_directory, 'info', 'repodata_record.json')) as fi:
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\common\compat.py", line 132, in open
        closefd=closefd)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Vineeth\\Anaconda3\\pkgs\\conda-4.6.2-py36_0\\info\\repodata_record.json'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 311, in _make_single_record
        raw_json_record = read_index_json(extracted_package_dir)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 115, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\common\compat.py", line 132, in open
        closefd=closefd)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Vineeth\\Anaconda3\\pkgs\\conda-4.6.2-py36_0\\info\\index.json'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\cli\install.py", line 271, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\cli\install.py", line 287, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\link.py", line 769, in print_transaction_summary
        legacy_action_groups = self._make_legacy_action_groups()
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\link.py", line 753, in _make_legacy_action_groups
        self._pfe.prepare()
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\common\io.py", line 85, in decorated
        return f(*args, **kwds)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 574, in prepare
        for prec in self.link_precs)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 574, in <genexpr>
        for prec in self.link_precs)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 468, in make_actions_for_record
        ), None)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 465, in <genexpr>
        pcrec for pcrec in concat(PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 466, in <genexpr>
        for pkgs_dir in context.pkgs_dirs)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 122, in query
        return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 237, in _package_cache_records
        self.load()
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 88, in load
        package_cache_record = self._make_single_record(base_name)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 333, in _make_single_record
        extract_tarball(package_tarball_full_path, extracted_package_dir)
      File "C:\Users\Vineeth\Anaconda3\lib\site-packages\conda\gateways\disk\create.py", line 166, in extract_tarball
        assert not lexists(destination_directory), destination_directory
    AssertionError: C:\Users\Vineeth\Anaconda3\pkgs\conda-4.6.2-py36_0

`$ C:\Users\Vineeth\Anaconda3\Scripts\conda-script.py install -n pytorch-1.0 pytorch torchvision cudatoolkit=9.0 -c pytorch`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=pytorch-1.0
                CONDA_EXE=C:\Users\Vineeth\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Users\Vineeth\Anaconda3\envs\pytorch-1.0
           CONDA_PREFIX_1=C:\Users\Vineeth\Anaconda3
    CONDA_PROMPT_MODIFIER=(pytorch-1.0)
         CONDA_PYTHON_EXE=C:\Users\Vineeth\Anaconda3\python.exe
               CONDA_ROOT=C:\Users\Vineeth\Anaconda3
              CONDA_SHLVL=2
                 HOMEPATH=\Users\Vineeth
                     PATH=C:\Users\Vineeth\Anaconda3\envs\pytorch-1.0;C:\Users\Vineeth\Anaconda3
                          \envs\pytorch-1.0\Library\mingw-w64\bin;C:\Users\Vineeth\Anaconda3\env
                          s\pytorch-1.0\Library\usr\bin;C:\Users\Vineeth\Anaconda3\envs\pytorch-
                          1.0\Library\bin;C:\Users\Vineeth\Anaconda3\envs\pytorch-1.0\Scripts;C:
                          \Users\Vineeth\Anaconda3\envs\pytorch-1.0\bin;C:\Users\Vineeth\Anacond
                          a3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:
                          \WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\OpenV
                          PN\bin;C:\WINDOWS\System32\OpenSSH\;C:\Users\Vineeth\Anaconda3;C:\User
                          s\Vineeth\Anaconda3\Library\mingw-w64\bin;C:\Users\Vineeth\Anaconda3\L
                          ibrary\usr\bin;C:\Users\Vineeth\Anaconda3\Library\bin;C:\Users\Vineeth
                          \Anaconda3\Scripts;C:\Users\Vineeth\AppData\Local\Microsoft\WindowsApp
                          s;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=1252
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : pytorch-1.0
    active env location : C:\Users\Vineeth\Anaconda3\envs\pytorch-1.0
            shell level : 2
       user config file : C:\Users\Vineeth\.condarc
 populated config files : C:\Users\Vineeth\.condarc
          conda version : 4.6.2
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : C:\Users\Vineeth\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Vineeth\Anaconda3\pkgs
                          C:\Users\Vineeth\.conda\pkgs
                          C:\Users\Vineeth\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Vineeth\Anaconda3\envs
                          C:\Users\Vineeth\.conda\envs
                          C:\Users\Vineeth\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

**Comment by tadeu** [comment]
Might be related to #8155

**Comment by AiLing2014** [comment]
Current conda install:

               platform : linux-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : /home/xiaoling/anaconda3  (writable)
    default environment : /home/xiaoling/anaconda3/envs/torch36
       envs directories : /home/xiaoling/anaconda3/envs
          package cache : /home/xiaoling/anaconda3/pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/xiaoling/.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Linux/4.15.0-45-generic debian/stretch/sid glibc/2.23
                UID:GID : 1000:1000



`$ /home/xiaoling/anaconda3/envs/torch36/bin/conda install pytorch torchvision cudatoolkit=8.0`




    Traceback (most recent call last):
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 347, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/plan.py", line 837, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 258, in execute_instructions
        cmd(state, arg)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/instructions.py", line 118, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 121, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/core/link.py", line 121, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 74, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 137, in read_paths_json
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 581, in box
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 581, in <genexpr>
        return self._type(v if isinstance(v, et) else et(**v) for v in val)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/gateways/disk/read.py", line 137, in <genexpr>
        paths=(PathDataV1(**f) for f in data['paths']),
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 702, in __call__
        instance = super(EntityType, cls).__call__(*args, **kwargs)
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 719, in __init__
        setattr(self, key, kwargs[key])
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 424, in __set__
        instance.__dict__[self.name] = self.validate(instance, self.box(instance, val))
      File "/home/xiaoling/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/entity.py", line 465, in validate
        raise ValidationError(getattr(self, 'name', 'undefined name'), val)
    conda._vendor.auxlib.exceptions.ValidationError: Value for sha256 cannot be None.

**Comment by jjhelmus** [comment]
It appears as the repodata being provided may be corrupt.  Can you remove `https://mirrors.tuna.tsinghua.edu.cn` from your channel list and see if the problem persists.
