### ISSUE TITLE
[conda list, 4.5.x/4.6.x] crash with regex in argument

### ISSUE THREAD

**Issue by nehaljwani** [conda/conda#8245]
```
conda list -n base '*python*'

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main_list.py", line 48, in list_packages
        for prec in get_packages(installed, regex) if regex else installed:
      File "/Users/nwani/m3/lib/python3.7/site-packages/conda/cli/main_list.py", line 28, in get_packages
        pat = re.compile(regex, re.I) if regex else None
      File "/Users/nwani/m3/lib/python3.7/re.py", line 234, in compile
        return _compile(pattern, flags)
      File "/Users/nwani/m3/lib/python3.7/re.py", line 286, in _compile
        p = sre_compile.compile(pattern, flags)
      File "/Users/nwani/m3/lib/python3.7/sre_compile.py", line 764, in compile
        p = sre_parse.parse(p, flags)
      File "/Users/nwani/m3/lib/python3.7/sre_parse.py", line 930, in parse
        p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
      File "/Users/nwani/m3/lib/python3.7/sre_parse.py", line 426, in _parse_sub
        not nested and not items))
      File "/Users/nwani/m3/lib/python3.7/sre_parse.py", line 651, in _parse
        source.tell() - here + len(this))
    re.error: nothing to repeat at position 0

`$ /Users/nwani/m3/bin/conda list -n base *python*`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/Users/nwani/m3
              CONDA_SHLVL=0
                     PATH=/Users/nwani/perl5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/o
                          pt/X11/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
            shell level : 0
       user config file : /Users/nwani/.condarc
 populated config files :
          conda version : 4.6.2
    conda-build version : 3.15.1
         python version : 3.7.2.final.0
       base environment : /Users/nwani/m3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/nwani/m3/pkgs
                          /Users/nwani/.conda/pkgs
       envs directories : /Users/nwani/m3/envs
                          /Users/nwani/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.2 requests/2.19.1 CPython/3.7.2 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]: N

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false
```

**Comment by Spirko** [comment]
The `conda list` subcommand requires a regex, not a shell pattern.  Starting a regex with an asterisk is not allowed.  Instead, run this:  `conda list -n base '.*python.*'`

Maybe instead of a crash, conda should give a more user-friendly error.
