### ISSUE TITLE
NotImplementedError for "conda init tcsh" on Mac OS X

### ISSUE THREAD

**Issue by jbednar** [conda/conda#8256]
conda init lists several shells as being supported, including tcsh, but when I try it with tcsh on Mac OS X it hits a NotImplementedError:

```
(base) 0172-jbednar:~ jbednar$ tcsh -f
> conda init tcsh

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/jbednar/anaconda/lib/python2.7/site-packages/conda/exceptions.py", line 1001, in __call__
        return func(*args, **kwargs)
      File "/Users/jbednar/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/jbednar/anaconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/jbednar/anaconda/lib/python2.7/site-packages/conda/cli/main_init.py", line 52, in execute
        anaconda_prompt)
      File "/Users/jbednar/anaconda/lib/python2.7/site-packages/conda/core/initialize.py", line 105, in initialize
        plan2 = make_initialize_plan(conda_prefix, shells, for_user, for_system, anaconda_prompt)
      File "/Users/jbednar/anaconda/lib/python2.7/site-packages/conda/core/initialize.py", line 466, in make_initialize_plan
        raise NotImplementedError()
    NotImplementedError

`$ /Users/jbednar/anaconda/bin/conda init tcsh`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/jbednar/anaconda/bin/conda
             CONDA_PREFIX=/Users/jbednar/anaconda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/jbednar/anaconda/bin/python
               CONDA_ROOT=/Users/jbednar/anaconda
              CONDA_SHLVL=1
                     PATH=/Users/jbednar/anaconda/bin:/Users/jbednar/anaconda/condabin:/usr/loca
                          l/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/go/
                          bin:/opt/X11/bin:/usr/local/git/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /Users/jbednar/anaconda
            shell level : 1
       user config file : /Users/jbednar/.condarc
 populated config files : /Users/jbednar/.condarc
          conda version : 4.6.2
    conda-build version : 3.0.19
         python version : 2.7.15.final.0
       base environment : /Users/jbednar/anaconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/jbednar/anaconda/pkgs
                          /Users/jbednar/.conda/pkgs
       envs directories : /Users/jbednar/anaconda/envs
                          /Users/jbednar/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.2 requests/2.21.0 CPython/2.7.15 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by mhrzmomeni** [comment]
Hi James,
Did you find any solution for this error?

**Comment by jbednar** [comment]
No, I've just been launching bash when I need to do conda commands instead. :-(

**Comment by msarahan** [comment]
This might be fixed in https://github.com/conda/conda/pull/8400/files#diff-d4157cfe352d0cae6f1e84d45e191751R471 which will be in 4.6.9

**Comment by jbednar** [comment]
I can verify that this problem no longer occurs on conda 4.10.3. Thanks!
