### ISSUE TITLE
"conda create -n <name> python=3.6" creates corrupted environment

### ISSUE THREAD

**Issue by caniko** [conda/conda#8321]
## Current Behavior
Conda loses all access to environment variables on conda environment activation. Python modules don't function properly.

Happens in both Miniconda and Anaconda. Tried to do it with conda/Anaconda in PATH. Tried to reinstall. Thank you for your time 

### Steps to Reproduce
1. Open Anaconda Prompt via start-menu
2. `conda create -n dlc python=3.6`
3. `activate dlc`
4. For example: `conda update conda` -> Error
5. `pip install numpy`
6. type `python`
7. `import numpy` -> Error

## Expected Behavior
Error on 4:
```
PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Miniconda3\envs\dlc
  package name: conda
```
Error on 7:
```
Traceback (most recent call last):
  File "C:\Miniconda3\envs\dlc\lib\site-packages\numpy\core\__init__.py", line 16, in <module>
    from . import multiarray
  File "C:\Miniconda3\envs\dlc\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
    from . import overrides
  File "C:\Miniconda3\envs\dlc\lib\site-packages\numpy\core\overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: DLL load failed: The specified module could not be found.
```

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\envs\dlc\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import core
  File "C:\Miniconda3\envs\dlc\lib\site-packages\numpy\core\__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
Here is how to proceed:
- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.
- If you are simply trying to use the numpy version that you have installed:
  your installation is broken - please reinstall numpy.
- If you have already reinstalled and that did not fix the problem, then:
  1. Check that you are using the Python you expect (you're using C:\Miniconda3\envs\dlc\python.exe),
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy versions you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

     Note: this error has many possible causes, so please don't comment on
     an existing issue about this - open a new one instead.

Original error was: DLL load failed: The specified module could not be found.

```
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : dlc
    active env location : C:\Miniconda3\envs\dlc
            shell level : 2
       user config file : C:\Users\Can\.condarc
 populated config files : C:\Users\Can\.condarc
          conda version : 4.6.4
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\Can\.conda\pkgs
                          C:\Users\Can\AppData\Local\conda\conda\pkgs
       envs directories : C:\Miniconda3\envs
                          C:\Users\Can\.conda\envs
                          C:\Users\Can\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.4 requests/2.19.1 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Can\.condarc <==
ssl_verify: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Miniconda3\envs\dlc:
#
# Name                    Version                   Build  Channel
certifi                   2018.11.29               py36_0    defaults
numpy                     1.16.1                   pypi_0    pypi
pip                       19.0.1                   py36_0    defaults
python                    3.6.8                h9f7ef89_1    defaults
setuptools                40.8.0                   py36_0    defaults
sqlite                    3.26.0               he774522_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wheel                     0.32.3                   py36_0    defaults
wincertstore              0.2              py36h7fe50ca_0    defaults
```
</p></details>

**Comment by csevast** [comment]
I have the same problem. I am using YML files in CMD batch files on Windows for updating and creating CONDA environments. Everything was working perfectly and now they are collapsed. I think that following issues are connected.
#10665 from anaconda-issues
#8308 from conda-issues

**Comment by caniko2** [comment]
Seems like nobody cares enough to look into it. Going to reset my PC for this stupid bug, can't believe it.

**Comment by csevast** [comment]
Try to downgrade conda to version 6.4.1

**Comment by caniko2** [comment]
> Try to downgrade conda to version 6.4.1 and recreate your environment.

Did that work for you?

**Comment by csevast** [comment]
Yes, it worked. Somehow, all the problems I had, e.g. not importint PyQt5, loosing CONDA access in CONDA environments, not deleting trash files in removing CONDA environments, disappeared. I lost more than one week trying out what is going on. We have to wait the problems to be fixed and then to upgrade conda.

**Comment by msarahan** [comment]
> Seems like nobody cares enough to look into it

Actually, we've been working overtime for the past 2 weeks to look into issues like this.  You can try the latest from the conda-canary channel:

conda update conda -c conda-canary

though if you have everything working now, perhaps best to leave it.  We will be putting up an explanation of the recent problems soon.

**Comment by caniko2** [comment]
I was just stating a fact. I am gratefull for the work you are puting in for this project, and wish you and your team the best.

conda update conda -c conda-canary

Reproduces the same bug sadly.

**Comment by caniko2** [comment]
> 
> 
> Try to downgrade conda to version 6.4.1 and recreate your environment.

How did you install 6.4.1 using command prompt? I get this message:

```
(base) C:\Users\Can>conda install conda=6.4
Collecting package metadata: done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - conda=6.4

Current channels:

  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/free/win-64
  - https://repo.anaconda.com/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by csevast** [comment]
I am sorry, I misspelled the version number. But be careful. You have to set the full version number, "conda install conda=4.6.1". Otherwise the higher version of 4.6 will be installed, i.e. 4.6.7. I am not sure but this version is still problematic.

Also, you have to downgrade to a version which is higher or equal of the conda version with which the environment has been created. In an installation I downgraded conda to v. 4.5.12 and now conda refuses to upgrade to any newer version, and probably re-installation of Anaconda/Miniconda is needed.

**Comment by caniko2** [comment]
I did what you said, still not working. You can see every code I executed since I installed miniconda on my PC at the university that has never had anaconda or miniconda below

<details open><summary>Spoil</summary><p>


```
(base) C:\Users\Can> conda install conda=4.6.1
Solving environment: done

  environment location: C:\Users\Can\Miniconda3

  added / updated specs:
    - conda=4.6.1


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.6.1                |           py37_0         1.7 MB
    openssl-1.1.1b             |       he774522_0         5.8 MB
    ------------------------------------------------------------
                                           Total:         7.4 MB

The following packages will be UPDATED:

    ca-certificates: 2018.03.07-0      --> 2019.1.23-0
    conda:           4.5.12-py37_0     --> 4.6.1-py37_0
    openssl:         1.1.1a-he774522_0 --> 1.1.1b-he774522_0

Proceed ([y]/n)? y


Downloading and Extracting Packages
conda-4.6.1          | 1.7 MB    | ############################################################################ | 100%
openssl-1.1.1b       | 5.8 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\Can>conda create -n dlc
Collecting package metadata: done
Solving environment: done

CondaError: KeyboardInterrupt

Terminate batch job (Y/N)? y

(base) C:\Users\Can>conda create -n dlc python=3.6
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.1
  latest version: 4.6.7

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\Can\Miniconda3\envs\dlc

  added / updated specs:
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2018.11.29         |           py36_0         146 KB
    pip-19.0.3                 |           py36_0         1.9 MB
    python-3.6.8               |       h9f7ef89_7        20.3 MB
    setuptools-40.8.0          |           py36_0         664 KB
    wheel-0.33.1               |           py36_0          57 KB
    wincertstore-0.2           |   py36h7fe50ca_0          13 KB
    ------------------------------------------------------------
                                           Total:        23.0 MB

The following NEW packages will be INSTALLED:

  certifi            pkgs/main/win-64::certifi-2018.11.29-py36_0
  pip                pkgs/main/win-64::pip-19.0.3-py36_0
  python             pkgs/main/win-64::python-3.6.8-h9f7ef89_7
  setuptools         pkgs/main/win-64::setuptools-40.8.0-py36_0
  sqlite             pkgs/main/win-64::sqlite-3.26.0-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.15.26706-h3a45250_0
  wheel              pkgs/main/win-64::wheel-0.33.1-py36_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py36h7fe50ca_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-40.8.0    | 664 KB    | ############################################################################ | 100%
certifi-2018.11.29   | 146 KB    | ############################################################################ | 100%
pip-19.0.3           | 1.9 MB    | ############################################################################ | 100%
wincertstore-0.2     | 13 KB     | ############################################################################ | 100%
wheel-0.33.1         | 57 KB     | ############################################################################ | 100%
python-3.6.8         | 20.3 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate dlc
#
# To deactivate an active environment, use
#
#     $ conda deactivate


(base) C:\Users\Can>conda activate dlc

(dlc) C:\Users\Can>conda install
'conda' is not recognized as an internal or external command,
operable program or batch file.

(dlc) C:\Users\Can>

```

</p></details>

**Comment by csevast** [comment]
I followed your code you sent and my conda is activating the dlc environment as expected. Probably your miniconda installation is corrupted. I suggest to you to reinstall Miniconda. Then install conda version 4.6.1 with "conda install conda=4.6.1" and then after to upgrade your base environment with conda version pinned, e.g. "conda update --all conda=4.6.1". Then you should create your conda environments as usual.

Maybe your Miniconda and conda installations are corrupted by installing specific packages from PyPI, with pip command. This is what I observed in my case.

**Comment by caniko2** [comment]
You were right! I don't know what is happening, but when I create the environment WITH python=3.6 it corrupts. When I create environment and then `conda install python=3.6` it is perfect.
