### ISSUE TITLE
R kernel doesnot start in Jupyter

### ISSUE THREAD

**Issue by vikramabhisheksah** [conda/conda#8331]
Hi All,
My R Kernel fails to start, every time I open a new notebook from Jupyter. Please refer to screenshot. 
![screenshot 8](https://user-images.githubusercontent.com/27946181/53295686-c403b200-3826-11e9-821f-09d60ca6caf5.png)

Getting the below kernel error message upon initiating kernel restart:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 67, in post
    model = yield gen.maybe_future(sm.get_session(path=path))
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 170, in get_session
    return self.row_to_model(row)
  File "C:\ProgramData\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 209, in row_to_model
    raise KeyError
KeyError

Kindly help

**Comment by jjhelmus** [comment]
This issue does not seem to be `conda` related but rather a more general package related question.  I'm transfering this issue to `anaconda-issue`.  @vikramabhisheksah Can you provide the information requested in the [issue template](https://raw.githubusercontent.com/ContinuumIO/anaconda-issues/master/.github/issue_template.md) so that we can help debug this issue.

**Comment by jjhelmus** [comment]
Ah, issues cannot be moved between organization.  @vikramabhisheksah Can you open an issues describing your issue in [anaconda-issues](https://github.com/ContinuumIO/anaconda-issues/issues)
