### ISSUE TITLE
error when creating new environment

### ISSUE THREAD

**Issue by steveskrip** [conda/conda#835]
I'm somewhat new to Anaconda.  When attempting to create an environment.  I tested the following:
`conda create -n myenv python`
and
`conda create -n myenv anaconda`

both times I receive the following error:
```
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Anaconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Anaconda\lib\site-packages\conda\cli\main_create.py", line 49, in execute
    install.install(args, parser, 'create')
  File "C:\Anaconda\lib\site-packages\conda\cli\install.py", line 275, in install
    if not pscheck.main(args):
  File "C:\Anaconda\lib\site-packages\conda\cli\pscheck.py", line 65, in main
    while not check_processes():
  File "C:\Anaconda\lib\site-packages\conda\cli\pscheck.py", line 23, in check_processes
    import psutil
  File "C:\Anaconda\lib\site-packages\psutil\__init__.py", line 135, in <module>
    import psutil._psmswindows as _psplatform
  File "C:\Anaconda\lib\site-packages\psutil\_psmswindows.py", line 67, in <module>
    _psutil_mswindows.MIB_TCP_STATE_ESTAB: CONN_ESTABLISHED,
AttributeError: 'module' object has no attribute 'MIB_TCP_STATE_ESTAB'
```

Here is my conda info:
```
Current conda install:

             platform : win-32
        conda version : 3.5.5
       python version : 2.7.5.final.0
     root environment : C:\Anaconda  (writable)
  default environment : C:\Anaconda
     envs directories : C:\Anaconda\envs
        package cache : C:\Anaconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-32/
                        http://repo.continuum.io/pkgs/pro/win-32/
          config file : None
    is foreign system : False
```

Any suggestions would be appreciated.  Thanks!

**Comment by soapy1** [comment]
Closing due to inactivity. If this is still an issue, please reopen
