### ISSUE TITLE
Cannot able to update or install any packages or even create a virtual environment using conda in Windows 10

### ISSUE THREAD

**Issue by Mr-Better** [conda/conda#8356]
When I use the command `conda create -n env` to create a new environment, or use `pip install` to install a package in base environment, or `conda update conda`, or `conda install anaconda-clean`, the following error will show up: 
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Software\Anaconda3\lib\site-packages\conda\exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "D:\Software\Anaconda3\lib\site-packages\conda\cli\main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "D:\Software\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "D:\Software\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 11, in execute
        install(args, parser, 'create')
      File "D:\Software\Anaconda3\lib\site-packages\conda\cli\install.py", line 235, in install
        force_reinstall=context.force,
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\solve.py", line 524, in solve_for_transaction
        self._notify_conda_outdated(link_precs)
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\solve.py", line 544, in _notify_conda_outdated
        SubdirData.query_all(conda_newer_spec, self.channels, self.subdirs),
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 91, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 95, in query
        self.load()
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 149, in load
        _internal_state = self._load()
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 227, in _load
        mod_etag_headers.get('_mod'))
      File "D:\Software\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 437, in fetch_repodata_remote_request
        timeout=timeout)
      File "D:\Software\Anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "D:\Software\Anaconda3\lib\site-packages\requests\sessions.py", line 519, in request
        prep = self.prepare_request(req)
      File "D:\Software\Anaconda3\lib\site-packages\requests\sessions.py", line 462, in prepare_request
        hooks=merge_hooks(request.hooks, self.hooks),
      File "D:\Software\Anaconda3\lib\site-packages\requests\models.py", line 317, in prepare
        self.prepare_auth(auth, url)
      File "D:\Software\Anaconda3\lib\site-packages\requests\models.py", line 548, in prepare_auth
        r = auth(self)
      File "D:\Software\Anaconda3\lib\site-packages\conda\gateways\connection\session.py", line 100, in __call__
        self._apply_basic_auth(request)
      File "D:\Software\Anaconda3\lib\site-packages\conda\gateways\connection\session.py", line 112, in _apply_basic_auth
        auth = get_netrc_auth(request.url)
      File "D:\Software\Anaconda3\lib\site-packages\requests\utils.py", line 203, in get_netrc_auth
        _netrc = netrc(netrc_path).authenticators(host)
      File "D:\Software\Anaconda3\lib\netrc.py", line 30, in __init__
        self._parse(file, fp, default_netrc)
      File "D:\Software\Anaconda3\lib\netrc.py", line 39, in _parse
        toplevel = tt = lexer.get_token()
      File "D:\Software\Anaconda3\lib\shlex.py", line 105, in get_token
        raw = self.read_token()
      File "D:\Software\Anaconda3\lib\shlex.py", line 136, in read_token
        nextchar = self.instream.read(1)
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 52: illegal multibyte sequence

`$ D:\Software\Anaconda3\Scripts\conda create -n t`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=.;D:\Java\jdk1.8.0_191\lib\dt.jar;D:\Java\jdk1.8.0_191\lib\tools.jar
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\Software\Anaconda3\Scripts\conda.exe
             CONDA_PREFIX=D:\Software\Anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\Software\Anaconda3\python.exe
               CONDA_ROOT=D:\Software\Anaconda3
              CONDA_SHLVL=1
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0
                 HOMEPATH=\Users\xy
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=D:\Software\Anaconda3;D:\Software\Anaconda3\Library\mingw-w64\bin;D:\S
                          oftware\Anaconda3\Library\usr\bin;D:\Software\Anaconda3\Library\bin;D:
                          \Software\Anaconda3\Scripts;D:\Software\Anaconda3\bin;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.0\libnvvp;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Sy
                          stem32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\Sys
                          tem32\OpenSSH\;D:\Program Files\Git\cmd;D:\Program
                          Files\Matlab\R2016a\runtime\win64;D:\Program
                          Files\Matlab\R2016a\bin;D:\Program
                          Files\Matlab\R2016a\polyspace\bin;C:\Program Files\Common
                          Files\Materialise\UCRT\10.0.102240\;C:\Program Files\NVIDIA
                          Corporation\NVSMI;C:\Users\xy\.dnx\bin;C:\Program
                          Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn\;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.0;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v9.0\lib\x64;C:\Program Files\TortoiseGit\bin;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\xy\AppD
                          ata\Local\Microsoft\WindowsApps;D:\Java\jdk1.8.0_191\bin;D:\Java\jdk1.
                          8.0_191\jre\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
         PYTHONIOENCODING=936
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
```

And my conda info:
```
active environment : base
    active env location : D:\Software\Anaconda3
            shell level : 1
       user config file : C:\Users\xy\.condarc
 populated config files : C:\Users\xy\.condarc
          conda version : 4.5.12
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : D:\Software\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Software\Anaconda3\pkgs
                          C:\Users\xy\AppData\Local\conda\conda\pkgs
       envs directories : D:\Software\Anaconda3\envs
                          C:\Users\xy\AppData\Local\conda\conda\envs
                          C:\Users\xy\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

**Comment by epogrebnyak** [comment]
How did you solve this?

**Comment by Mr-Better** [comment]
> 
> 
> How did you solve this?

@epogrebnyak I didn't find a suitable solution, so I just reinstall conda simply.

**Comment by methane** [comment]
It seems you have UTF-8 netrc file (e.g. `~/.netrc` or `~/_netrc`).  Do you know who created the netrc?

**Comment by Mr-Better** [comment]
> 
> 
> It seems you have UTF-8 netrc file (e.g. `~/.netrc` or `~/_netrc`). Do you know who created the netrc?

sorry, I don't know.
