### ISSUE TITLE
ImportError: DLL load failed: \u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6a21\u5757\u3002

### ISSUE THREAD

**Issue by Daniellee1990** [conda/conda#8397]
### Steps to Reproduce

```
(tensorflow-gpu) C:\Users\xiaodanli>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: \u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6a21\u5757\u3002

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\xiaodanli\Anaconda3\envs\tensorflow-gpu\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: \u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6a21\u5757\u3002
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by Daniellee1990** [comment]
Anyone has some idea about this? thanks in advance

**Comment by mingwandroid** [comment]
It looks like you have some Unicode characters coming into the process
somehow. Please check your environment variables and try to use only ASCII.

Another option is to try upgrading to python 3.6 or above. This is the
first python version on Windows that really supports Unicode well.

**Comment by Daniellee1990** [comment]
What should I keep in mind when checking my environment variables?

**Comment by mingwandroid** [comment]
Any env. vars whos' name and/or value contains any characters that are not [ASCII](https://en.wikipedia.org/wiki/ASCII).

If you paste the only other clue you have (\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6a21\u5757\u3002) into a [unicode converter](https://www.branah.com/unicode-converter) that might lead to another clue.

**Comment by ShijianXu** [comment]
Hi, I encountered the same(?maybe) problem. Can anyone help me?
Well, the problem is strange and I am not sure whether it is due to conda or pytorch or sublime.
My system is windows10. My editor is Sublime3. I installed the anaconda plug-in so I can run python code in sublime.

**Problem Description:**
> Traceback (most recent call last):
  File "D:\Docs\ML_Course\A2\loadData.py", line 1, in <module>
    import matplotlib
  File "D:\Software\Anaconda3\install\lib\site-packages\matplotlib\__init__.py", line 141, in <module>
    from . import cbook, rcsetup
  File "D:\Software\Anaconda3\install\lib\site-packages\matplotlib\cbook\__init__.py", line 33, in <module>
    import numpy as np
  File "D:\Software\Anaconda3\install\lib\site-packages\numpy\__init__.py", line 140, in <module>
    from . import _distributor_init
  File "D:\Software\Anaconda3\install\lib\site-packages\numpy\_distributor_init.py", line 34, in <module>
    from . import _mklinit
ImportError: DLL load failed: \u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6a21\u5757\u3002
[Finished in 0.1s]

**The code is quite simple:**
`import matplotlib`
Just one line. And then I encounter this error. However, the strange thing is, if I `import torch` first, then there will be no problem. Like this:

> import torch
import matplotlib

The same problem occur to `numpy`. This is strange. I do nothing, just import torch before it, then no error. I installed PyTorch with conda. I don't know what caused this problem. Pytorch? Conda? Or Sublime? Can anyone help me? Thanks in advance.

**Comment by ShijianXu** [comment]
Actually, if I `import torch` first, then no problem will occur and everything is fine. Well, but I do not want to surrender. The problem is so strange and it makes me uncomfortable :(

**Comment by ShijianXu** [comment]
Besides, I also checked the meaning of the unicode symbols: `\u627e\u4e0d\u5230\u6307\u5b9a\u7684\u6a21\u5757\u3002`. It means `can not find the specific module`. I don't understand why it will pop up the error in unicode form since in other occasions, it will normally pop-up the error in utf-8 form. I have checked, there is no env/var/path contain the unicode characters in my system.

Please help me.

**Comment by HatuneMiku** [comment]
#8976, https://github.com/ContinuumIO/anaconda-issues/issues/11141

Same problem in jupyter notebook env kernel.

But if I activate the env in cmd and run ipython, then import numpy it will work.
```
C:\Users\name>conda info -e
# conda environments:
#
base                  *  d:\Programs\Miniconda3
da                       d:\Programs\Miniconda3\envs\da
rasa                     d:\Programs\Miniconda3\envs\rasa
spider                   d:\Programs\Miniconda3\envs\spider


C:\Users\name>conda activate da

(da) C:\Users\name>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>>
```
