### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 9: ordinal not in range(128)

### ISSUE THREAD

**Issue by Guanchang3** [conda/conda#8432]
https://github.com/conda/conda/issues/

C:\Windows\system32>conda
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\cli\main.py", line 112, in main
    from ..exceptions import conda_exception_handler
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\exceptions.py", line 18, in <module>
    from .common.io import timeout
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\common\io.py", line 467, in <module>
    class time_recorder(ContextDecorator):  # pragma: no cover
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\common\io.py", line 469, in time_recorder
    record_file = expand(join('~', '.conda', 'instrumentation-record.csv'))
  File "C:\ProgramData\Anaconda2\lib\site-packages\conda\common\path.py", line 51, in expand
    return abspath(expanduser(expandvars(path)))
  File "C:\ProgramData\Anaconda2\lib\ntpath.py", line 311, in expanduser
    return userhome + path[i:]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb9 in position 9: ordinal not in range(128)

meanwhile my anaconda navigator can't normally start.
Is my conda-script.py broken?

**Comment by mingwandroid** [comment]
No, the problem is that you are trying to use Unicode with Python 2 on Windows. That basically does not work (as you can see the exception happens from the depths of Python 2's Windows code: `ntpath.py` and not from within conda).

Please use Python 3 instead if you can, otherwise you'll need to avoid Unicode. I think your home directory contains non-ascii characters.
