### ISSUE TITLE
Upgrade to python 3.7 breaks imports

### ISSUE THREAD

**Issue by anucapri** [conda/conda#8441]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
>>> conda info
Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```
</p></details>

I upgraded pip with conda by running the below and got the error at the end. Looks like the upgrade to python 3.7 moves the python interpreter to point to a new location and none of the modules seem importable now. **What's the best way to fix this?** Should I just mode the symlink for `/anaconda3/bin/python -> python3.7` back to `python3.6`. Not sure what all other dependencies are on this.

```
conda install pip
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /anaconda3

  added / updated specs:
    - pip


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.3.9           |           py37_0         155 KB
    pip-19.0.3                 |           py37_0         1.8 MB
    python-3.7.2               |       haf84260_0        21.6 MB
    setuptools-40.8.0          |           py37_0         643 KB
    wheel-0.33.1               |           py37_0          39 KB
    ------------------------------------------------------------
                                           Total:        24.2 MB

The following NEW packages will be INSTALLED:

  pip                pkgs/main/osx-64::pip-19.0.3-py37_0

The following packages will be UPDATED:

  python                                   3.6.8-haf84260_0 --> 3.7.2-haf84260_0
  setuptools                          36.5.0-py36h2134326_0 --> 40.8.0-py37_0
  wheel                               0.29.0-py36h3597b6d_1 --> 0.33.1-py37_0

The following packages will be DOWNGRADED:

  certifi                                   2019.3.9-py36_0 --> 2019.3.9-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
setuptools-40.8.0    | 643 KB    | #################################### | 100% 
certifi-2019.3.9     | 155 KB    | #################################### | 100% 
wheel-0.33.1         | 39 KB     | #################################### | 100% 
python-3.7.2         | 21.6 MB   | #################################### | 100% 
pip-19.0.3           | 1.8 MB    | #################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Traceback (most recent call last):
  File "/anaconda3/bin/conda", line 12, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'

```
Other programs that no longer work: jupyter, ipython

```
>>> jupyter
Traceback (most recent call last):
  File "/anaconda3/bin/jupyter", line 7, in <module>
    from jupyter_core.command import main
ModuleNotFoundError: No module named 'jupyter_core'
```

```
>>> ipython
Traceback (most recent call last):
  File "/anaconda3/bin/ipython", line 7, in <module>
    from IPython import start_ipython
ModuleNotFoundError: No module named 'IPython'
```

**Comment by jjhelmus** [comment]
From the update of `pip` I'm fairly certain that the environment was inconsistent which allowed conda to update Python without examining the other dependencies.  This should be fixed by #8444
