### ISSUE TITLE
 conda create failure--RemoveError: 'futures' is a dependency of conda and cannot be removed from conda's operating environment.

### ISSUE THREAD

**Issue by yuanzhenjie** [conda/conda#8454]
Current Behavior :  conda create failure
conda create -n faces python=3.7
```
(base) [root@dl-gpu ~]# conda create -n faces python=3.7
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /data/software/anaconda2/envs/faces

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/linux-64::certifi-2019.3.9-py37_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1b-h7b6447c_1
  pip                pkgs/main/linux-64::pip-19.0.3-py37_0
  python             pkgs/main/linux-64::python-3.7.2-h0371630_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-40.8.0-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.27.2-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.1-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

RemoveError: 'futures' is a dependency of conda and cannot be removed from
conda's operating environment.

```
`conda info`:
```
     active environment : base
    active env location : /data/software/anaconda2
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.6.8
    conda-build version : 3.11.0
         python version : 2.7.15.final.0
       base environment : /data/software/anaconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /data/software/anaconda2/pkgs
                          /root/.conda/pkgs
       envs directories : /data/software/anaconda2/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/2.7.15 Linux/3.10.0-229.el7.x86_64 centos/7.1.1503 glibc/2.22
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

```
(base) [root@dl-gpu ~]# conda config --show-sources
==> /root/.condarc <==
channels:
  - defaults
show_channel_urls: True
```

Environment variable:
```
# packages in environment at /data/software/anaconda2:
#
# Name                    Version                   Build  Channel
futures                   3.2.0                    pypi_0    pypi
```

I try the follow failed solution

```
pip uninstall futures
```
but rise another issue:
```
(base) [root@dl-gpu ~]# conda install futures
Traceback (most recent call last):
  File "/data/software/anaconda2/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/data/software/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 116, in main
    from ..exceptions import conda_exception_handler
  File "/data/software/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 24, in <module>
    from .common.io import dashlist, timeout
  File "/data/software/anaconda2/lib/python2.7/site-packages/conda/common/io.py", line 7, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
ImportError: No module named concurrent.futures

(base) [root@dl-gpu ~]# conda create -n facetest python=3.7
Traceback (most recent call last):
  File "/data/software/anaconda2/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/data/software/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 116, in main
    from ..exceptions import conda_exception_handler
  File "/data/software/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 24, in <module>
    from .common.io import dashlist, timeout
  File "/data/software/anaconda2/lib/python2.7/site-packages/conda/common/io.py", line 7, in <module>
    from concurrent.futures import ThreadPoolExecutor, _base, as_completed
ImportError: No module named concurrent.futures
````
How I fixed it?

**Comment by yuanzhenjie** [comment]
My worried are the same as his.
Just ```conda update conda```  [https://github.com/conda/conda/issues/8149#issuecomment-463193757](url)
It will update python of base(conda) to 3.7 and update same pkg  to  base 3.7 .

It is similar to this one. #8149

**Comment by yuanzhenjie** [comment]
Looks like it's only updated to 3.7.
