### ISSUE TITLE
conda activate broken on >= 4.6.9

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8496]
```
(base) ~\code> conda activate dev

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 138, in main
        return activator_main()
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 940, in main
        print(activator.execute(), end='')
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 173, in execute
        return getattr(self, self.command)()
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 150, in activate
        builder_result = self.build_activate(self.env_name_or_prefix)
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 275, in build_activate
        return self._build_activate_stack(env_name_or_prefix, False)
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 332, in _build_activate_stack
        self._replace_prefix_in_path(old_conda_prefix, prefix))
      File "C:\Miniconda3\lib\site-packages\conda\activate.py", line 550, in _replace_prefix_in_path
        assert last_idx is not None
    AssertionError

`$ C:\Miniconda3\Scripts\conda-script.py shell.powershell activate dev`
```
<details>

```
  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=C:\Miniconda3\Scripts\conda.exe
             CONDA_PREFIX=C:\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=C:\Miniconda3\python.exe
               CONDA_ROOT=C:\Miniconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\dhirschfeld
                     PATH=
                        C:\Miniconda3
                        C:\Miniconda3/Library/mingw-w64/bin
                        C:\Miniconda3/Library/usr/bin
                        C:\Miniconda3/Library/bin
                        C:\Miniconda3/Scripts
                        C:\Miniconda3/bin
                        C:\Miniconda3\condabin
                        C:\Miniconda3
                        C:\Miniconda3\Library\mingw-w64\bin
                        C:\Miniconda3\Library\usr\bin
                        C:\Miniconda3\Library\bin
                        C:\Miniconda3\Scripts
                        C:\Windows\system32
                        C:\Windows
                        C:\Windows\System32\Wbem
                        C:\Windows\System32\WindowsPowerShell\v1.0\
                        C:\Windows\System32\OpenSSH\
                        C:\docker
                        C:\Program Files\dotnet\
                        C:\Program Files\TortoiseGit\bin
                        C:\Program Files\SysInternals
                        C:\Program Files\Microsoft VS Code Insiders\bin
                        C:\oracle\instantclient_18_3
                        C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\
                        C:\blp\DAPI
                        C:\blp\DAPI\DDE
                        C:\Users\dhirschfeld\wsl\ubuntu
                        C:\Users\dhirschfeld\AppData\Local\Microsoft\WindowsApps
                        C:\Users\dhirschfeld\.dotnet\tools
             PSMODULEPATH=C:\Users\dhirschfeld\Documents\WindowsPowerShell\Modules;C:\Program Files
                          \WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\
                          Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : C:\Miniconda3
            shell level : 1
       user config file : C:\Users\dhirschfeld\.condarc
 populated config files : C:\ProgramData\conda\.condarc
                          C:\Miniconda3\.condarc
                          C:\Users\dhirschfeld\.condarc
          conda version : 4.6.10
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       base environment : C:\Miniconda3  (writable)
           channel URLs : http://conda.stanwell.com/anaconda/win-64
                          http://conda.stanwell.com/anaconda/noarch
                          http://conda.stanwell.com/conda-forge/win-64
                          http://conda.stanwell.com/conda-forge/noarch
                          http://conda.stanwell.com/external/win-64
                          http://conda.stanwell.com/external/noarch
                          http://conda.stanwell.com/stanwell/prod/win-64
                          http://conda.stanwell.com/stanwell/prod/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          http://conda.stanwell.com/stanwell/dev/win-64
                          http://conda.stanwell.com/stanwell/dev/noarch
                          https://conda.anaconda.org/pytorch/win-64
                          https://conda.anaconda.org/pytorch/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\dhirschfeld\.conda\pkgs
                          C:\Users\dhirschfeld\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\dhirschfeld\envs
                          C:\Miniconda3\envs
                          C:\Users\dhirschfeld\.conda\envs
                          C:\Users\dhirschfeld\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.10 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : True
             netrc file : None
           offline mode : False
```
</details>

It appears to be looking for a `C:\Miniconda3\bin` folder which isn't on my path.

https://github.com/conda/conda/blob/4d041bba904ac21c57653d240674a3db69de4480/conda/activate.py#L549-L550

i.e. `prefix_dirs[-1] = 'C:\Miniconda3\bin'`

**Comment by dhirschfeld** [comment]
It looks like this is caused by my having the [`shellcheck`](https://github.com/conda-forge/shellcheck-feedstock) package installed which puts `shellcheck.exe` into a `/Miniconda3/bin` directory.

If I remove that package and restart my shell all is well again.

Am I correct in thinking that shellcheck *shouldnt'* be installing anything into `/Miniconda3/bin` and that the appropriate location is `C:\Miniconda3\Library\bin`?

**Comment by dhirschfeld** [comment]
In any case I guess conda should somehow be robust to this.

**Comment by situmaimes** [comment]
I just run into the same problem with you
I just replace the assertion with 
`if last_idx is None:
    last_idx = 0`
It seems work well but i want a more correct way to fix it
