### ISSUE TITLE
conda clean fails while cleaning packages due to "WindowsError: [Error 145] The directory is not empty"

### ISSUE THREAD

**Issue by stahlous** [conda/conda#850]
While attempting to clean packages I usually run into a problem where `conda clean -p` runs into an unexpected error due to "WindowsError: [Error 145] The directory is not empty"

My solution so far has been to just restart `conda clean` and it picks up where it left off.

Is this possibly due to a race condition where one subprocess is attempting to delete the directory before another subprocess has finished deleting all the files? In any event, here is my `conda info`:

```
Current conda install:

             platform : win-64
        conda version : 3.5.5
       python version : 2.7.6.final.0
     root environment : C:\Miniconda  (writable)
  default environment : C:\Miniconda
     envs directories : C:\Miniconda\envs
        package cache : C:\Miniconda\pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/win-64/
                        http://repo.continuum.io/pkgs/pro/win-64/
          config file : C:\Users\<my_username>\.condarc
    is foreign system : False
```

and the traceback:

```
C:\Users\<my_username>\Desktop\msr_parsing\tests>conda clean -p
Cache location: C:\Miniconda\pkgs
Will remove the following packages:

scipy-0.14.0-np18py27_0                    223.7 MB
scipy-0.14.0-np18py34_0                    211.8 MB
setuptools-3.6-py27_0                        840 KB
...
xlsxwriter-0.5.5-py34_0                      931 KB
xlwings-0.1.0-py27_0                          85 KB
xlwt-0.7.5-py27_0                            883 KB
_license-1.1-py27_0                          128 KB
---------------------------------------------
Total:                                     577.7 MB

Proceed ([y]/n)? y

removing scipy-0.14.0-np18py27_0
removing scipy-0.14.0-np18py34_0
removing setuptools-3.6-py27_0
...
removing statsmodels-0.5.0-np18py27_1
removing sympy-0.7.5-py27_0
removing sympy-0.7.5-py34_0
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "C:\Miniconda\Scripts\conda-script.py", line 4, in <module>
    sys.exit(main())
  File "C:\Miniconda\lib\site-packages\conda\cli\main.py", line 179, in main
    args.func(args, p)
  File "C:\Miniconda\lib\site-packages\conda\cli\main_clean.py", line 200, in execute
    rm_pkgs(args)
  File "C:\Miniconda\lib\site-packages\conda\cli\main_clean.py", line 180, in rm_pkgs
    rm_rf(join(pkgs_dir, pkg))
  File "C:\Miniconda\lib\site-packages\conda\install.py", line 143, in rm_rf
    shutil.rmtree(path)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Miniconda\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Miniconda\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: 'C:\\Miniconda\\pkgs\\sympy-0.7.5-py34_0\\Lib\\site-packages\\sympy\\diffgeom'
```

**Comment by rmcgibbo** [comment]
We're still seeing something like this on Appveyor, cc: https://github.com/omnia-md/conda-recipes/issues/242, although I'm not sure if theres anything more conda could conceivably be doing, or if this is just an unavoidable windows issue.
