### ISSUE TITLE
No module named _MD4

### ISSUE THREAD

**Issue by codelh7** [conda/conda#8514]
### Steps to Reproduce

when I run cuckoo in conda environment, I got an error and can't solve it by google！
I think that it is a conda problm,so I seek help here! Hope someone can help me !!! Thanks so much!!!
```
Traceback (most recent call last):
  File "/home/codelh7/miniconda2/envs/python27/bin/cuckoo", line 6, in <module>
    from cuckoo.main import main
  File "/home/codelh7/miniconda2/envs/python27/lib/python2.7/site-packages/cuckoo/__init__.py", line 6, in <module>
    from cuckoo import (
  File "/home/codelh7/miniconda2/envs/python27/lib/python2.7/site-packages/cuckoo/processing/__init__.py", line 10, in <module>
    __file__, "cuckoo.processing", globals(), Processing
  File "/home/codelh7/miniconda2/envs/python27/lib/python2.7/site-packages/cuckoo/core/plugins.py", line 46, in enumerate_plugins
    "review its contents and/or validity!" % (fname, e)
cuckoo.common.exceptions.CuckooOperationalError: Unable to load the Cuckoo plugin at memory.py: No module named _MD4. Please review its contents and/or validity!
```

## Expected Behavior

I excepted It could run normally.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
/home/codelh7/miniconda2/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)

     active environment : python27
    active env location : /home/codelh7/miniconda2/envs/python27
            shell level : 2
       user config file : /home/codelh7/.condarc
 populated config files : /home/codelh7/.condarc
          conda version : 4.6.11
    conda-build version : not installed
         python version : 3.7.2.final.0
       base environment : /home/codelh7/miniconda2  (writable)
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/codelh7/miniconda2/pkgs
                          /home/codelh7/.conda/pkgs
       envs directories : /home/codelh7/miniconda2/envs
                          /home/codelh7/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.2 Linux/4.15.0-47-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/codelh7/.condarc <==
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
show_channel_urls: True

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/codelh7/miniconda2/envs/python27:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
absl-py                   0.7.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
alembic                   0.8.8                    pypi_0    pypi
androguard                3.0.1                    pypi_0    pypi
asn1crypto                0.24.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
astor                     0.7.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
attrs                     19.1.0                   pypi_0    pypi
backports                 1.0                      py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
backports-functools-lru-cache 1.5                      pypi_0    pypi
backports.weakref         1.0.post1                py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
beautifulsoup4            4.5.3                    pypi_0    pypi
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
boto                      2.49.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
boto3                     1.9.111                    py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
botocore                  1.12.112                   py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
bz2file                   0.98                     py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
c-ares                    1.15.0               h7b6447c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ca-certificates           2019.1.23                     0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
capstone                  3.0.5rc2                 pypi_0    pypi
certifi                   2019.3.9                 py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cffi                      1.12.2           py27h2e261b9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
chardet                   3.0.4                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
click                     6.6                      pypi_0    pypi
colorama                  0.3.7                    pypi_0    pypi
crypto                    1.4.1                    pypi_0    pypi
cryptography              2.6.1            py27h1ba5d50_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cuckoo                    2.0.6.2                  pypi_0    pypi
django                    1.8.4                    pypi_0    pypi
django-extensions         1.6.7                    pypi_0    pypi
docutils                  0.14                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dpkt                      1.8.7                    pypi_0    pypi
ecdsa                     0.13                     pypi_0    pypi
egghatch                  0.2.3                    pypi_0    pypi
elasticsearch             5.3.0                    pypi_0    pypi
enum34                    1.1.6                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
flask                     0.12.2                   pypi_0    pypi
flask-sqlalchemy          2.1                      pypi_0    pypi
funcsigs                  1.0.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
functools32               3.2.3.post2              pypi_0    pypi
future                    0.17.1                   pypi_0    pypi
futures                   3.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gast                      0.2.2                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
gensim                    3.4.0            py27h14c3975_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
grpcio                    1.16.1           py27hf8bcb03_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
h5py                      2.9.0            py27h7918eee_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
hdf5                      1.10.4               hb1b8bf9_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
httpreplay                0.2.5                    pypi_0    pypi
idna                      2.8                      py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
intel-openmp              2019.3                      199    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ipaddress                 1.0.22                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
itsdangerous              1.1.0                    pypi_0    pypi
jinja2                    2.9.6                    pypi_0    pypi
jmespath                  0.9.4                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
jsbeautifier              1.6.2                    pypi_0    pypi
jsonschema                3.0.1                    pypi_0    pypi
keras-applications        1.0.7                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
keras-preprocessing       1.0.9                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libedit                   3.1.20181209         hc058e9b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libffi                    3.2.1                hd88cf55_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgcc-ng                 8.2.0                hdf63c60_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libgfortran-ng            7.3.0                hdf63c60_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.6.1                hd408876_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libstdcxx-ng              8.2.0                hdf63c60_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
linecache2                1.0.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mako                      1.0.8                    pypi_0    pypi
markdown                  3.0.1                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
markupsafe                1.1.1                    pypi_0    pypi
mkl                       2019.3                      199    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_fft                   1.0.10           py27ha843d7b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl_random                1.0.2            py27hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mock                      2.0.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
naked                     0.1.31                   pypi_0    pypi
ncurses                   6.1                  he6710b0_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy                     1.16.2           py27h7e9f1db_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.16.2           py27hde5b4d6_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
olefile                   0.43                     pypi_0    pypi
oletools                  0.51                     pypi_0    pypi
openssl                   1.1.1b               h7b6447c_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pbr                       5.1.3                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
peepdf                    0.4.2                    pypi_0    pypi
pefile2                   1.2.11                   pypi_0    pypi
pillow                    3.2.0                    pypi_0    pypi
pip                       19.0.3                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
protobuf                  3.6.1            py27he6710b0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pycparser                 2.19                     py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyelftools                0.24                     pypi_0    pypi
pyguacamole               0.6                      pypi_0    pypi
pymisp                    2.4.54                   pypi_0    pypi
pymongo                   3.0.3                    pypi_0    pypi
pyopenssl                 19.0.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pyrsistent                0.14.11                  pypi_0    pypi
pysocks                   1.6.8                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python                    2.7.16               h9bab390_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.4.2                    pypi_0    pypi
python-editor             1.0.4                    pypi_0    pypi
python-magic              0.4.12                   pypi_0    pypi
pythonaes                 1.0                      pypi_0    pypi
pyyaml                    5.1                      pypi_0    pypi
readline                  7.0                  h7b6447c_5    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
requests                  2.13.0                   pypi_0    pypi
roach                     0.1.2                    pypi_0    pypi
s3transfer                0.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scapy                     2.3.2                    pypi_0    pypi
scipy                     1.2.1            py27h7c811a0_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
setuptools                41.0.0                   pypi_0    pypi
sflock                    0.3.9                    pypi_0    pypi
shellescape               3.4.1                    pypi_0    pypi
six                       1.12.0                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
smart_open                1.8.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
soupsieve                 1.9                      pypi_0    pypi
sqlalchemy                1.0.8                    pypi_0    pypi
sqlite                    3.27.2               h7b6447c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorboard               1.13.1           py27hf484d3e_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow                1.13.1          mkl_py27h74ee40f_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-base           1.13.1          mkl_py27h7ce6ba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tensorflow-estimator      1.13.0                     py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
termcolor                 1.1.0                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tk                        8.6.8                hbc83047_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
tlslite-ng                0.6.0                    pypi_0    pypi
traceback2                1.4.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
unicorn                   1.0.1                    pypi_0    pypi
unittest2                 1.1.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
urllib3                   1.24.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wakeonlan                 0.2.2                    pypi_0    pypi
werkzeug                  0.14.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
wheel                     0.33.1                   py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
xlrd                      1.2.0                    py27_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
yara-python               3.6.3                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
```
</p></details>

**Comment by jjhelmus** [comment]
This appears to be an issue with your install of `cuckoo` not conda.  You should raise this question in a forum associated with that package.
