### ISSUE TITLE
Pip install failing in environment creation doesn't fail environment creation

### ISSUE THREAD

**Issue by RobertKirk** [conda/conda#8537]
## Current Behavior
When I create a environment from a environment.yml file, which has pip dependencies, if the pip dependencies fail to install (for example if I misspelled a package name) then the entire env creation still succeeds and returns a 0 exit code.

This is an issue for me when creating environments in a dockerfile to run jobs, which are meant to run programmatically without user oversight. Obviously the job depends on the pip packages, but docker thinks the container has built successfully, so when the command runs it fails due to packages not being present.

I've looked in the code and can see how this happens, in the pip installer it calls the pip_subprocess function, which on receiving a non-zero exit code just prints out the stderr, but doesn't raise an error or return the status code. I'd be happy to write an MR which fixes this, maybe by having an optional command-line option `fail-fast` which if passed will fail if the pip_subprocess function returns a non-zero exit code. (it'd also have to make the pip_subprocess function return the exit code, which I would check wouldn't break compatibility).

### Steps to Reproduce
create a file environment.yml:
```
name: "test_env"
channels:
  - "defaults"
dependencies:
- pip
- python=3.7
- pip:
    - requests
    - non-existent-package
```
then run:
```
conda env create -f environment.yml
```
this prints:
```
❯ conda env create -f environment.yml
WARNING: The conda.compat module is deprecated and will be removed in a future release.
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/home/robert/anaconda3/envs/test_env/bin/python', '-m', 'pip', 'install', '-r', '/home/robert/testing/condaenv.cxwk7vln.requirements.txt']
Pip subprocess output:
Collecting requests (from -r /home/robert/testing/condaenv.cxwk7vln.requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting non-existent-package (from -r /home/robert/testing/condaenv.cxwk7vln.requirements.txt (line 2))

Pip subprocess error:
  Could not find a version that satisfies the requirement non-existent-package (from -r /home/robert/testing/condaenv.cxwk7vln.requirements.txt (line 2)) (from versions: )
No matching distribution found for non-existent-package (from -r /home/robert/testing/condaenv.cxwk7vln.requirements.txt (line 2))

#
# To activate this environment, use
#
#     $ conda activate test_env
#
# To deactivate an active environment, use
#
#     $ conda deactivate

❯ echo $?
0
```

## Expected Behavior
The environment creation should fail, and the return code should be non-zero. It could also roll back environment creation (as it does if the conda install doesn't work).

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
    active environment : test_env
    active env location : /home/robert/anaconda3/envs/test_env
            shell level : 1
       user config file : /home/robert/.condarc
 populated config files : /home/robert/.condarc
          conda version : 4.6.11
    conda-build version : 3.17.6
         python version : 3.7.1.final.0
       base environment : /home/robert/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/robert/anaconda3/pkgs
                          /home/robert/.conda/pkgs
       envs directories : /home/robert/anaconda3/envs
                          /home/robert/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.1 Linux/4.18.0-16-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

</p></details>
<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/robert/.condarc <==
channels:
  - conda-forge
  - defaults
```

</p></details>
<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
WARNING: The conda.compat module is deprecated and will be removed in a future release.
# packages in environment at /home/robert/anaconda3/envs/test_env:
#
# Name                    Version                   Build  Channel
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1b               h7b6447c_1    defaults
pip                       19.0.3                   py37_0    defaults
python                    3.7.3                h0371630_0    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                40.8.0                   py37_0    defaults
sqlite                    3.27.2               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.33.1                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

</p></details>

**Comment by sobayed** [comment]
I just stumbled across the exact same problem. For me, the pip error message didn't even show up when I ran ``conda env create`` command. In my case, trying to install ``uvloop`` on a Windows machine produces an error which should propagate from pip to conda.

Example environment.yml:

```
name: test-env
channels:
  - defaults
dependencies:
  - python=3
  - pip
  - pip:
      - uvloop==0.11.2
```

Running ``conda env create -f environment.yml`` prints the following output:
```
C:\repos\test
(base) λ conda env create -f environment.yml
Collecting package metadata: done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['C:\\Users\\user\\anaconda3\\envs\\test-env\\python.exe', '-m', 'pip', 'install', '-U', '-r', 'C:\\repos\\test\\condaenv.cs2b2da2.requirements.txt']
Pip subprocess output:
Looking in indexes: https://company-pipy.com/repository/pypi/simple
Collecting uvloop==0.11.2 (from -r C:\repos\test\condaenv.cs2b2da2.requirements.txt (line 1))
  Using cached https://company-pipy.com/repository/pypi/packages/5c/37/6daa39aac42b2deda6ee77f408bec0419b600e27b89b374b0d440af32b10/uvloop-0.11.2.tar.gz

#
# To activate this environment, use
#
#     $ conda activate test-env
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

However, when running the pip command directly, the error occurs as expected (I copied the temporary requirements.txt created by conda for this purpose):
 ```
C:\repos\test
(base) λ C:\\Users\\user\\anaconda3\\envs\\test-env\\python.exe -m pip install -U -r C:\\repos\\test\\condaenv.cs2b2da2.requirements.txt
Looking in indexes: https://company-pipy.com/repository/pypi/simple
Collecting uvloop==0.11.2 (from -r C:\\repos\\test\\condaenv.cs2b2da2.requirements.txt (line 1))
  Using cached https://company-pipy.com/repository/pypi/packages/5c/37/6daa39aac42b2deda6ee77f408bec0419b600e27b89b374b0d440af32b10/uvloop-0.11.2.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-avtqqk21\uvloop\setup.py", line 15, in <module>
        raise RuntimeError('uvloop does not support Windows at the moment')
    RuntimeError: uvloop does not support Windows at the moment
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-avtqqk21\uvloop\
```

If I recall correctly, this did not happen with earlier versions of conda.

## Environment information

<details>
  <summary> conda info </summary>
  <p>

```
       active environment : base
    active env location : C:\Users\user\anaconda3
            shell level : 1
       user config file : C:\Users\user\.condarc
 populated config files : C:\Users\user\.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : C:\Users\user\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\user\anaconda3\pkgs
                          C:\Users\user\.conda\pkgs
                          C:\Users\user\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\user\anaconda3\envs
                          C:\Users\user\.conda\envs
                          C:\Users\user\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</p>
</details>

**Comment by sobayed** [comment]
Update: This still appears to be broken with conda 4.7.5

**Comment by RMeli** [comment]
I have the same problem with `conda 4.7.11`.

**Comment by houssamTrizi** [comment]
I have this same problem with conda 4.8

**Comment by Tanmay-Jaiswal** [comment]
This is painful. I spent half a day trying to understand what was going wrong and why my pip installs were failing inside the environment. Luckily, I stumbled upon this issue and when I checked, many dependencies that should have been installed at the time of env creation were missing.

conda version 4.10.1, installed via miniconda on linux.

**Comment by santiagxf** [comment]
I faced the same issue when automating environment creation. If someone is doing this in the context of bash, then I managed to capture the exception using the following code:

`conda env create -n environment_name -f conda_dependencies.yml 2>&1 | grep -q CondaEnvException`

You can then test if this is true or false. Not ideal, but still a way to catch it.

**Comment by nlhnt** [comment]
Still an issue, any news?  
We'll try what @santiagxf suggested, thanks for this idea.

**Comment by eamonnkenny** [comment]
rm -rf ~/.cache
mangled cache if you use the same environment name again, after deleting it. Took hours to figure this out.

**Comment by jezdez** [comment]
not stale

**Comment by urucoder** [comment]
This is an ancient bug that doesn't seem a priority for the conda team, for anyone suffering from this in docker builds, you can make it fail with this simple script
```bash
conda env update -f environment.yml --prune 2>&1 | tee -a /tmp/conda.log
cat /tmp/conda.log | grep -q CondaEnvException && exit 1
```

**Comment by ALeglessSpider** [comment]
Did anyone find a fix?
