### ISSUE TITLE
Issues when trying to install cvxopt 

### ISSUE THREAD

**Issue by seyi100** [conda/conda#8560]
Hello,

Please I am trying to install cvxopt with in conda. 

Using the following command ' conda install cvxopt '. However I can see the following errors.

conda-4.3.30-p 100% |###############################| Time: 0:00:01 492.37 kB/s
cvxopt-1.1.9-p 100% |###############################| Time: 0:00:01 470.28 kB/s
Extracting packages ...
An unexpected error has occurred.###################                     |  59%
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-32
          conda version : 4.2.13
       conda is private : False
      conda-env version : 4.2.13
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : C:\Users\MUMMY\Anaconda3  (writable)
    default environment : C:\Users\MUMMY\Anaconda3
       envs directories : C:\Users\MUMMY\Anaconda3\envs
          package cache : C:\Users\MUMMY\Anaconda3\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-32
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/pro/win-32
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-32
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False

`$ C:\Users\MUMMY\Anaconda3\Scripts\conda-script.py install cvxopt`

    Traceback (most recent call last):
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\exceptions.py", line 479, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\cli\main.py", line 145, in _main
        exit_code = args.func(args, p)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\instructions.py", line 135, in execute_instructions
        cmd(state, arg)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\instructions.py", line 58, in EXTRACT_CMD
        extract(arg)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\install.py", line 812, in extract
        exp_backoff_fn(os.rename, temp_path, path)
      File "C:\Users\MUMMY\Anaconda3\lib\site-packages\conda\common\disk.py", line 165, in exp_backoff_fn
        result = fn(*args, **kwargs)
    PermissionError: [WinError 5] Access is denied: 'C:\\Users\\MUMMY\\Anaconda3\\pkgs\\scipy-0.19.1-np113py35_0.tmp' -> 'C:\\Users\\MUMMY\\Anaconda3\\pkgs\\scipy-0.19.1-np113py35_0'

**Comment by msarahan** [comment]
Your version of conda is very far out of support.  Please update conda and try again.

**Comment by seyi100** [comment]
Thanks for the help.
