### ISSUE TITLE
can't use conda

### ISSUE THREAD

**Issue by singularity97** [conda/conda#8581]
hello.I used to install anaconda2 and anaconda3 in my computer and it worked well.I didn't install anything or modify anything these days,but it has some error today.I can't use conda and when I open the Anaconda prompt,it shows:

```
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "F:\Anaconda2\Scripts\conda-script.py", line 10, in <module>
    sys.exit(main())
  File "F:\Anaconda2\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "F:\Anaconda2\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "F:\Anaconda2\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "F:\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 161, in get_info_dict
    from ..config import rc_path, sys_rc_path, user_rc_path
  File "F:\Anaconda2\lib\site-packages\conda\config.py", line 92, in <module>
    envs_dirs = context.envs_dirs
  File "F:\Anaconda2\lib\site-packages\conda\base\context.py", line 292, in envs_dirs
    join(self._user_data_dir, 'envs'),
  File "F:\Anaconda2\lib\site-packages\conda\base\context.py", line 327, in _user_data_dir
    return user_data_dir(APP_NAME, APP_NAME)
  File "F:\Anaconda2\lib\site-packages\conda\_vendor\appdirs.py", line 67, in user_data_dir
    path = os.path.join(_get_win_folder(const), appauthor, appname)
  File "F:\Anaconda2\lib\site-packages\conda\_vendor\appdirs.py", line 284, in _get_win_folder_with_pywin32
    from win32com.shell import shellcon, shell
ImportError: Module use of python36.dll conflicts with this version of Python.
```

when I use"python" in cmd,the python version is 2.7.I used to create a python 3.6 environment in anaconda2.
It worked well before and report error suddenly today,I think it's probably because the update of windows yesterday.Except install anaconda again,is there any other way to solve?

**Comment by singularity97** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by singularity97** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
