### ISSUE TITLE
`conda remove` full environment chokes on symlinked package directory

### ISSUE THREAD

**Issue by fbender** [conda/conda#8582]
Below error report was not submitted due to timeout. 

## Current Behavior
Executing `$ /Users/***/miniconda2/bin/conda remove -n craft-legacy --all --verbose` resulted in: 
```
    Traceback (most recent call last):
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/main_remove.py", line 67, in execute
        handle_txn(txn, prefix, args, False, True)
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 304, in handle_txn
        unlink_link_transaction.execute()
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 241, in execute
        self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 592, in _execute
        action.cleanup()
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/core/path_actions.py", line 991, in cleanup
        rm_rf(self.holding_full_path, clean_empty_parents=True)
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 172, in rm_rf
        remove_empty_parent_paths(path)
      File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/gateways/disk/delete.py", line 145, in remove_empty_parent_paths
        rmdir(parent_path)
    OSError: [Errno 20] Not a directory: '/Users/***/miniconda2/envs/craft-legacy/lib/python2.7/site-packages/mpl_toolkits/basemap/data'
```

With relevant environment variables:

```
                 CIO_TEST=<not set>
               CONDA_ROOT=/Users/***/miniconda2
```

### Steps to Reproduce
To save space, I symlinked the respective directory to the same dir in the root env (i.e. `/Users/***/miniconda2/pkgs/basemap-1.0.7-np111py27_0/lib/python2.7/site-packages/mpl_toolkits/basemap/data`): 

```
$ ls -hal /Users/***/miniconda2/envs/craft-legacy/lib/python2.7/site-packages/mpl_toolkits/basemap/data
lrwxr-xr-x  1 ***  staff   105B 14 Mär  2018 /Users/***/miniconda2/envs/craft-legacy/lib/python2.7/site-packages/mpl_toolkits/basemap/data -> ../../../../../../../pkgs/basemap-1.0.7-np111py27_0/lib/python2.7/site-packages/mpl_toolkits/basemap/data
```

## Expected Behavior
Transparently handle symlinks.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /Users/***/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 2.7.12.final.0
       base environment : /Users/***/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/***/miniconda2/pkgs
                          /Users/***/.conda/pkgs
       envs directories : /Users/***/miniconda2/envs
                          /Users/***/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/2.7.12 Darwin/15.6.0 OSX/10.11.6
                UID:GID : ***:**
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```

(empty) 
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/***/miniconda2/envs/craft-legacy:
#
# Name                    Version                   Build  Channel
```

(empty after removal command, as expected)
</p></details>

**Comment by fbender** [comment]
Please also advise on how to continue after this error. It appears the env was deleted only half way, I want to delete it cleanly. Following error appears after rerunning the command `conda remove -n craft-legacy --all --verbose`:

```
Remove all packages in environment /Users/***/miniconda2/envs/craft-legacy:

initializing UnlinkLinkTransaction with
  target_prefix: /Users/***/miniconda2/envs/craft-legacy
  unlink_precs:
    
  link_precs:
    


Traceback (most recent call last):
  File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 1003, in __call__
    return func(*args, **kwargs)
  File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/main_remove.py", line 67, in execute
    handle_txn(txn, prefix, args, False, True)
  File "/Users/***/miniconda2/lib/python2.7/site-packages/conda/cli/install.py", line 282, in handle_txn
    raise PackagesNotFoundError(args.package_names)
PackagesNotFoundError: The following packages are missing from the target environment:
  - 
```

I created an export before running the command initially, i.e. I should be able to re-create the environment if needed.
