### ISSUE TITLE
win10 install pytorch-cpu  in Anaconda, errors.

### ISSUE THREAD

**Issue by gzhengli** [conda/conda#8593]
**I'm submitting a...**
  - [0 ] bug report
  - [ ] feature request

## Current Behavior

When I use the command "conda install pytorch-cpu -c pytorch", an unexpected error has occurred. See below.

 Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 232, in _error_catcher
        yield
      File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 314, in read
        data = self._fp.read(amt)
      File "D:\Anaconda\lib\http\client.py", line 448, in read
        n = self.readinto(b)
      File "D:\Anaconda\lib\http\client.py", line 488, in readinto
        n = self.fp.readinto(b)
      File "D:\Anaconda\lib\socket.py", line 575, in readinto
        return self._sock.recv_into(b)
      File "D:\Anaconda\lib\ssl.py", line 929, in recv_into
        return self.read(nbytes, buffer)
      File "D:\Anaconda\lib\ssl.py", line 791, in read
        return self._sslobj.read(len, buffer)
      File "D:\Anaconda\lib\ssl.py", line 575, in read
        v = self._sslobj.read(len, buffer)
    socket.timeout: The read operation timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 676, in generate
        for chunk in self.raw.stream(chunk_size, decode_content=True):
      File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 357, in stream
        data = self.read(amt=amt, decode_content=decode_content)
      File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 324, in read
        flush_decoder = True
      File "D:\Anaconda\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\Anaconda\lib\site-packages\requests\packages\urllib3\response.py", line 237, in _error_catcher
        raise ReadTimeoutError(self._pool, None, 'Read timed out.')
    requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\fetch.py", line 419, in download
        for chunk in resp.iter_content(2**14):
      File "D:\Anaconda\lib\site-packages\requests\models.py", line 683, in generate
        raise ConnectionError(e)
    requests.exceptions.ConnectionError: HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 405, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "D:\Anaconda\lib\site-packages\conda\plan.py", line 643, in execute_actions
        inst.execute_instructions(plan, index, verbose)
      File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 134, in execute_instructions
        cmd(state, arg)
      File "D:\Anaconda\lib\site-packages\conda\instructions.py", line 47, in FETCH_CMD
        fetch_pkg(state['index'][arg + '.tar.bz2'])
      File "D:\Anaconda\lib\site-packages\conda\fetch.py", line 336, in fetch_pkg
        download(url, path, session=session, md5=info['md5'], urlstxt=True)
      File "D:\Anaconda\lib\site-packages\conda\fetch.py", line 438, in download
        raise CondaRuntimeError("Could not open %r for writing (%s)." % (pp, e))
    conda.exceptions.CondaRuntimeError: Runtime error: Could not open 'D:\\Anaconda\\pkgs\\pytorch-cpu-1.0.1-py3.5_cpu_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Anaconda\lib\site-packages\conda\exceptions.py", line 473, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "D:\Anaconda\lib\site-packages\conda\cli\main.py", line 144, in _main
        exit_code = args.func(args, p)
      File "D:\Anaconda\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 422, in install
        raise CondaSystemExit('Exiting', e)
      File "D:\Anaconda\lib\contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)
      File "D:\Anaconda\lib\site-packages\conda\cli\common.py", line 573, in json_progress_bars
        yield
      File "D:\Anaconda\lib\site-packages\conda\cli\install.py", line 420, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open 'D:\\Anaconda\\pkgs\\pytorch-cpu-1.0.1-py3.5_cpu_1.tar.bz2.part' for writing (HTTPSConnectionPool(host='binstar-cio-packages-prod.s3.amazonaws.com', port=443): Read timed out.).

### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : win-64
          conda version : 4.2.9
       conda is private : False
      conda-env version : 4.2.9
    conda-build version : 2.0.2
         python version : 3.5.2.final.0
       requests version : 2.11.1
       root environment : D:\Anaconda  (writable)
    default environment : D:\Anaconda
       envs directories : D:\Anaconda\envs
          package cache : D:\Anaconda\pkgs
           channel URLs : https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/win-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/noarch/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/win-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/win-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/win-64/
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/free/win-64/
                          https://repo.continuum.io/pkgs/free/noarch/
                          https://repo.continuum.io/pkgs/pro/win-64/
                          https://repo.continuum.io/pkgs/pro/noarch/
                          https://repo.continuum.io/pkgs/msys2/win-64/
                          https://repo.continuum.io/pkgs/msys2/noarch/
            config file : C:\Users\wei\.condarc
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\wei\.condarc <==
show_channel_urls: True
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/peterjc123/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at D:\Anaconda:
#
_license                  1.1                      py35_1    defaults
_nb_ext_conf              0.3.0                    py35_0    defaults
absl-py                   0.6.1                     <pip>
alabaster                 0.7.9                    py35_0    defaults
anaconda                  4.2.0               np111py35_0    defaults
anaconda-clean            1.0.0                    py35_0    defaults
anaconda-client           1.5.1                    py35_0    defaults
anaconda-navigator        1.3.1                    py35_0    defaults
argcomplete               1.0.0                    py35_1    defaults
astor                     0.7.1                     <pip>
astroid                   1.4.7                    py35_0    defaults
astropy                   1.2.1               np111py35_0    defaults
babel                     2.3.4                    py35_0    defaults
backports                 1.0                      py35_0    defaults
beautifulsoup4            4.5.1                    py35_0    defaults
bitarray                  0.8.1                    py35_1    defaults
blaze                     0.10.1                   py35_0    defaults
bokeh                     0.12.2                   py35_0    defaults
boto                      2.42.0                   py35_0    defaults
bottleneck                1.1.0               np111py35_0    defaults
bzip2                     1.0.6                    vc14_3  [vc14]  defaults
cffi                      1.7.0                    py35_0    defaults
chest                     0.2.3                    py35_0    defaults
click                     6.6                      py35_0    defaults
cloudpickle               0.2.1                    py35_0    defaults
clyent                    1.2.2                    py35_0    defaults
colorama                  0.3.7                    py35_0    defaults
comtypes                  1.1.2                    py35_0    defaults
conda                     4.2.9                    py35_0    defaults
conda-build               2.0.2                    py35_0    defaults
configobj                 5.0.6                    py35_0    defaults
console_shortcut          0.1.1                    py35_1    defaults
contextlib2               0.5.3                    py35_0    defaults
cryptography              1.5                      py35_0    defaults
curl                      7.49.0                   vc14_0  [vc14]  defaults
cycler                    0.10.0                   py35_0    defaults
cython                    0.24.1                   py35_0    defaults
cytoolz                   0.8.0                    py35_0    defaults
dask                      0.11.0                   py35_0    defaults
datashape                 0.5.2                    py35_0    defaults
decorator                 4.0.10                   py35_0    defaults
dill                      0.2.5                    py35_0    defaults
docutils                  0.12                     py35_2    defaults
dynd-python               0.7.2                    py35_0    defaults
entrypoints               0.2.2                    py35_0    defaults
et_xmlfile                1.0.1                    py35_0    defaults
fastcache                 1.0.2                    py35_1    defaults
filelock                  2.0.6                    py35_0    defaults
flask                     0.11.1                   py35_0    defaults
flask-cors                2.1.2                    py35_0    defaults
freetype                  2.5.5                    vc14_1  [vc14]  defaults
gast                      0.2.0                     <pip>
get_terminal_size         1.0.0                    py35_0    defaults
gevent                    1.1.2                    py35_0    defaults
greenlet                  0.4.10                   py35_0    defaults
grpcio                    1.16.1                    <pip>
h5py                      2.6.0               np111py35_2    defaults
hdf5                      1.8.15.1                 vc14_4  [vc14]  defaults
heapdict                  1.0.0                    py35_1    defaults
icu                       57.1                     vc14_0  [vc14]  defaults
idna                      2.1                      py35_0    defaults
imagesize                 0.7.1                    py35_0    defaults
ipykernel                 4.5.0                    py35_0    defaults
ipython                   5.1.0                    py35_0    defaults
ipython_genutils          0.1.0                    py35_0    defaults
ipywidgets                5.2.2                    py35_0    defaults
itsdangerous              0.24                     py35_0    defaults
jdcal                     1.2                      py35_1    defaults
jedi                      0.9.0                    py35_1    defaults
jinja2                    2.8                      py35_1    defaults
jpeg                      8d                       vc14_2  [vc14]  defaults
jsonschema                2.5.1                    py35_0    defaults
jupyter                   1.0.0                    py35_3    defaults
jupyter-contrib-core      0.3.3                     <pip>
jupyter-contrib-nbextensions 0.5.0                     <pip>
jupyter-highlight-selected-word 0.2.0                     <pip>
jupyter-latex-envs        1.4.4                     <pip>
jupyter-nbextensions-configurator 0.4.0                     <pip>
jupyter_client            4.4.0                    py35_0    defaults
jupyter_console           5.0.0                    py35_0    defaults
jupyter_core              4.2.0                    py35_0    defaults
Keras-Applications        1.0.6                     <pip>
Keras-Preprocessing       1.0.5                     <pip>
lazy-object-proxy         1.2.1                    py35_0    defaults
libdynd                   0.7.2                         0    defaults
libpng                    1.6.22                   vc14_0  [vc14]  defaults
libtiff                   4.0.6                    vc14_2  [vc14]  defaults
llvmlite                  0.13.0                   py35_0    defaults
locket                    0.2.0                    py35_1    defaults
lxml                      3.6.4                    py35_0    defaults
Markdown                  3.0.1                     <pip>
markupsafe                0.23                     py35_2    defaults
matplotlib                1.5.3               np111py35_0    defaults
menuinst                  1.4.1                    py35_0    defaults
mistune                   0.7.3                    py35_0    defaults
mkl                       11.3.3                        1    defaults
mkl-service               1.1.2                    py35_2    defaults
mpmath                    0.19                     py35_1    defaults
multipledispatch          0.4.8                    py35_0    defaults
nb_anacondacloud          1.2.0                    py35_0    defaults
nb_conda                  2.0.0                    py35_0    defaults
nb_conda_kernels          2.0.0                    py35_0    defaults
nbconvert                 4.2.0                    py35_0    defaults
nbformat                  4.1.0                    py35_0    defaults
nbpresent                 3.0.2                    py35_0    defaults
networkx                  1.11                     py35_0    defaults
nltk                      3.2.1                    py35_0    defaults
nose                      1.3.7                    py35_1    defaults
notebook                  4.2.3                    py35_0    defaults
numba                     0.28.1              np111py35_0    defaults
numexpr                   2.6.1               np111py35_0    defaults
numpy                     1.11.1                   py35_1    defaults
numpy                     1.15.4                    <pip>
odo                       0.5.0                    py35_1    defaults
openpyxl                  2.3.2                    py35_0    defaults
openssl                   1.0.2j                   vc14_0  [vc14]  defaults
pandas                    0.18.1              np111py35_0    defaults
partd                     0.3.6                    py35_0    defaults
path.py                   8.2.1                    py35_0    defaults
pathlib2                  2.1.0                    py35_0    defaults
patsy                     0.4.1                    py35_0    defaults
pep8                      1.7.0                    py35_0    defaults
pickleshare               0.7.4                    py35_0    defaults
pillow                    3.3.1                    py35_0    defaults
pip                       18.1                      <pip>
pip                       8.1.2                    py35_0    defaults
pkginfo                   1.3.2                    py35_0    defaults
ply                       3.9                      py35_0    defaults
prompt_toolkit            1.0.3                    py35_0    defaults
protobuf                  3.6.1                     <pip>
psutil                    4.3.1                    py35_0    defaults
py                        1.4.31                   py35_0    defaults
pyasn1                    0.1.9                    py35_0    defaults
pycosat                   0.6.1                    py35_1    defaults
pycparser                 2.14                     py35_1    defaults
pycrypto                  2.6.1                    py35_4    defaults
pycurl                    7.43.0                   py35_0    defaults
pyflakes                  1.3.0                    py35_0    defaults
pygments                  2.1.3                    py35_0    defaults
pylint                    1.5.4                    py35_1    defaults
pyopenssl                 16.0.0                   py35_0    defaults
pyparsing                 2.1.4                    py35_0    defaults
pyqt                      5.6.0                    py35_0    defaults
pytables                  3.2.2               np111py35_4    defaults
pytest                    2.9.2                    py35_0    defaults
python                    3.5.2                         0    defaults
python-dateutil           2.5.3                    py35_0    defaults
pytz                      2016.6.1                 py35_0    defaults
pywin32                   220                      py35_1    defaults
pyyaml                    3.12                     py35_0    defaults
pyzmq                     15.4.0                   py35_0    defaults
qt                        5.6.0                    vc14_0  [vc14]  defaults
qtawesome                 0.3.3                    py35_0    defaults
qtconsole                 4.2.1                    py35_2    defaults
qtpy                      1.1.2                    py35_0    defaults
requests                  2.11.1                   py35_0    defaults
rope                      0.9.4                    py35_1    defaults
ruamel_yaml               0.11.14                  py35_0    defaults
scikit-image              0.12.3              np111py35_1    defaults
scikit-learn              0.17.1              np111py35_1    defaults
scipy                     0.18.1              np111py35_0    defaults
setuptools                27.2.0                   py35_1    defaults
simplegeneric             0.8.1                    py35_1    defaults
singledispatch            3.4.0.3                  py35_0    defaults
sip                       4.18                     py35_0    defaults
six                       1.10.0                   py35_0    defaults
snowballstemmer           1.2.1                    py35_0    defaults
sockjs-tornado            1.0.3                    py35_0    defaults
sphinx                    1.4.6                    py35_0    defaults
spyder                    3.0.0                    py35_0    defaults
sqlalchemy                1.0.13                   py35_0    defaults
statsmodels               0.6.1               np111py35_1    defaults
sympy                     1.0                      py35_0    defaults
tensorboard               1.12.0                    <pip>
tensorflow                1.12.0                    <pip>
termcolor                 1.1.0                     <pip>
tk                        8.5.18                   vc14_0  [vc14]  defaults
toolz                     0.8.0                    py35_0    defaults
tornado                   4.4.1                    py35_0    defaults
traitlets                 4.3.0                    py35_0    defaults
unicodecsv                0.14.1                   py35_0    defaults
vs2015_runtime            14.0.25123                    0    defaults
wcwidth                   0.1.7                    py35_0    defaults
werkzeug                  0.11.11                  py35_0    defaults
wheel                     0.29.0                   py35_0    defaults
widgetsnbextension        1.2.6                    py35_0    defaults
win_unicode_console       0.5                      py35_0    defaults
wrapt                     1.10.6                   py35_0    defaults
xlrd                      1.0.0                    py35_0    defaults
xlsxwriter                0.9.3                    py35_0    defaults
xlwings                   0.10.0                   py35_0    defaults
xlwt                      1.1.2                    py35_0    defaults
zlib                      1.2.8                    vc14_3  [vc14]  defaults
```
</p></details>

**Comment by gzhengli** [comment]
have solved.
use the command "conda install pytorch-cpu torchvision-cpu -c pytorch"  from the poytorch official website.
