### ISSUE TITLE
When I run `source ./dev/start` (as per the CONTRIBUTING.md), I receive an error

### ISSUE THREAD

**Issue by squidnee** [conda/conda#8607]
## Current Behavior
When I follow the instructions [here](https://github.com/conda/conda/blob/master/CONTRIBUTING.md#development-environment-bash-), step 2 fails for me with ModuleNotFoundError: No module named 'conda_package_handling'.

### Steps to Reproduce
Commands:
```
git remote add upstream git@github.com:conda/conda
source ./dev/start
```

Output:
```
Traceback (most recent call last):
  File "/Users/smaples/Desktop/GitHub/conda/conda/exceptions.py", line 1017, in __call__
    return func(*args, **kwargs)
  File "/Users/smaples/Desktop/GitHub/conda/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/smaples/Desktop/GitHub/conda/conda/cli/conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "/Users/smaples/Desktop/GitHub/conda/conda/cli/main_init.py", line 16, in execute
    from ..core.initialize import initialize, initialize_dev, install
  File "/Users/smaples/Desktop/GitHub/conda/conda/core/initialize.py", line 61, in <module>
    from ..gateways.disk.create import copy, mkdir_p
  File "/Users/smaples/Desktop/GitHub/conda/conda/gateways/disk/create.py", line 16, in <module>
    import conda_package_handling.api
ModuleNotFoundError: No module named 'conda_package_handling'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/smaples/Desktop/GitHub/conda/devenv/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/smaples/Desktop/GitHub/conda/devenv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/smaples/Desktop/GitHub/conda/conda/__main__.py", line 8, in <module>
    sys.exit(main())
  File "/Users/smaples/Desktop/GitHub/conda/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/Users/smaples/Desktop/GitHub/conda/conda/exceptions.py", line 1305, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/smaples/Desktop/GitHub/conda/conda/exceptions.py", line 1020, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/smaples/Desktop/GitHub/conda/conda/exceptions.py", line 1064, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/Users/smaples/Desktop/GitHub/conda/conda/exceptions.py", line 1075, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/Users/smaples/Desktop/GitHub/conda/conda/exceptions.py", line 1145, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/Users/smaples/Desktop/GitHub/conda/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/Users/smaples/Desktop/GitHub/conda/conda/core/index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/smaples/Desktop/GitHub/conda/conda/core/package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/smaples/Desktop/GitHub/conda/conda/core/path_actions.py", line 12, in <module>
    from .envs_manager import get_user_environments_txt_file, register_env, unregister_env
  File "/Users/smaples/Desktop/GitHub/conda/conda/core/envs_manager.py", line 11, in <module>
    from .prefix_data import PrefixData
  File "/Users/smaples/Desktop/GitHub/conda/conda/core/prefix_data.py", line 23, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "/Users/smaples/Desktop/GitHub/conda/conda/gateways/disk/create.py", line 16, in <module>
    import conda_package_handling.api
ModuleNotFoundError: No module named 'conda_package_handling'
```

## Expected Behavior
The dev environment should be activated. It seems that ```./devenv/bin/activate``` works OK.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /Users/smaples/miniconda3
            shell level : 1
       user config file : /Users/smaples/.condarc
 populated config files : /Users/smaples/.condarc
          conda version : 4.6.12
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /Users/smaples/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/smaples/miniconda3/pkgs
                          /Users/smaples/.conda/pkgs
       envs directories : /Users/smaples/miniconda3/envs
                          /Users/smaples/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.12 requests/2.21.0 CPython/3.7.3 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
auto_update_conda: False
ssl_verify: False
channel_alias: https://conda.anaconda.org
channels:
  - defaults
default_channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/r
show_channel_urls: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/smaples/miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   py37_0    defaults
anaconda                  custom                   py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
appnope                   0.1.0                    py37_0    defaults
appscript                 1.1.0            py37h1de35cc_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.1.2            py37h1de35cc_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.8.3            py37h1de35cc_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.15.0               hd9629dc_0    defaults
bokeh                     1.0.4                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.2           py37hb5b8e2f_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
cloudpickle               0.8.0                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.6.12                   py37_1    defaults
conda-build               3.17.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.0.4                    py37_1    defaults
conda-verify              3.1.1                    py37_0    defaults
contextlib2               0.5.5                    py37_0    defaults
coverage                  4.5.3            py37h1de35cc_0    defaults
cryptography              2.6.1            py37ha12b0ac_0    defaults
curl                      7.64.0               ha441bb4_2    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.6           py37h0a44026_0    defaults
cytoolz                   0.9.0.1          py37h1de35cc_1    defaults
dask                      1.1.4                    py37_1    defaults
dask-core                 1.1.4                    py37_1    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.5.0                    py37_1    defaults
distributed               1.26.0                   py37_1    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py37h1de35cc_2    defaults
filelock                  3.0.10                   py37_0    defaults
flake8                    3.7.7                    py37_0    defaults
flake8-polyfill           1.0.2                    py37_0    defaults
flask                     1.0.2                    py37_1    defaults
freetype                  2.9.1                hb4e5f40_0    defaults
future                    0.17.1                   py37_0    defaults
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.4.0            py37h1de35cc_0    defaults
git                       2.20.1          pl526h6951d83_0    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py37_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
greenlet                  0.4.15           py37h1de35cc_0    defaults
h5py                      2.9.0            py37h3134771_0    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.8                      py37_0    defaults
intel-openmp              2019.3                      199    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.4.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
isort                     4.3.16                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.35.4           py37hf63ae98_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.0.1            py37h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py37h1de35cc_2    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.64.0               h051b688_2    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_2    defaults
libpng                    1.6.36               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.10               hcb84e12_2    defaults
libxml2                   2.9.9                hab757c2_0    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
llvmlite                  0.28.0           py37h8c7ce04_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.3.2            py37hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
mando                     0.6.4                      py_0    conda-forge
markupsafe                1.1.1            py37h1de35cc_0    defaults
matplotlib                3.0.3            py37h54f8f79_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2019.3                      199    defaults
mkl-service               1.1.2            py37hfbe908c_5    defaults
mkl_fft                   1.0.10           py37h5e564d8_0    defaults
mkl_random                1.0.2            py37h27c97d8_0    defaults
mock                      2.0.0                    py37_0    defaults
more-itertools            6.0.0                    py37_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37h04f5b5a_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
nbconvert                 5.4.1                    py37_3    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.2                      py37_1    defaults
nltk                      3.4                      py37_1    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.7.8                    py37_0    defaults
numba                     0.43.1           py37h6440ff4_0    defaults
numexpr                   2.6.9            py37h7413580_0    defaults
numpy                     1.16.2           py37hacdab7b_0    defaults
numpy-base                1.16.2           py37h6575580_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.6.1                    py37_1    defaults
openssl                   1.1.1b               h1de35cc_1    defaults
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37h0a44026_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.4                    py37_0    defaults
partd                     0.3.10                   py37_1    defaults
path.py                   11.5.0                   py37_0    defaults
pathlib2                  2.3.3                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pbr                       5.1.3                      py_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py37_0    defaults
perl                      5.26.2               h4e221da_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    5.4.1            py37hb68e598_0    defaults
pip                       19.0.3                   py37_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.9.0                    py37_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
psutil                    5.6.1            py37h1de35cc_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37h1413db1_2    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h1de35cc_9    defaults
pycurl                    7.43.0.2         py37ha12b0ac_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyodbc                    4.0.26           py37h0a44026_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.3.1                    py37_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pyrsistent                0.14.11          py37h1de35cc_0    defaults
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.5.1            py37h5bccee9_0    defaults
pytest                    4.4.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-cov                2.6.1                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-mock               1.10.4                   py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
pytest-timeout            1.3.3                    py37_0    defaults
python                    3.7.3                h359304d_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
python-libarchive-c       2.8                      py37_6    defaults
python.app                2                        py37_9    defaults
pytz                      2018.9                   py37_0    defaults
pywavelets                1.0.2            py37h1d22016_0    defaults
pyyaml                    5.1                      pypi_0    pypi
pyzmq                     18.0.0           py37h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.4.3                    py37_0    defaults
qtpy                      1.7.0                    py37_1    defaults
radon                     3.0.1                      py_0    conda-forge
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py37_0    defaults
responses                 0.10.5                   py37_0    defaults
rope                      0.12.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
scikit-image              0.14.2           py37h0a44026_0    defaults
scikit-learn              0.20.3           py37h27c97d8_0    defaults
scipy                     1.2.1            py37h1410ff5_0    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                40.8.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
sphinx                    1.8.5                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.3                    py37_0    defaults
spyder-kernels            0.4.2                    py37_0    defaults
sqlalchemy                1.3.1            py37h1de35cc_0    defaults
sqlite                    3.27.2               ha441bb4_0    defaults
statsmodels               0.9.0            py37h1d22016_0    defaults
sympy                     1.3                      py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   6.0.2            py37h1de35cc_0    defaults
tqdm                      4.31.1                   py37_1    defaults
traitlets                 4.3.2                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.33.1                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
wrapt                     1.11.1           py37h1de35cc_0    defaults
wurlitzer                 1.0.2                    py37_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.5                    py37_0    defaults
xlwings                   0.15.4                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zict                      0.1.4                    py37_0    defaults
zipp                      0.3.3                    py37_1    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```
</p></details>

**Comment by msarahan** [comment]
we need to update our docs (and probably also the scripts).  You need to conda install conda-package-handling to get that.  It's required for the new package format.
