### ISSUE TITLE
Unable to create virtual Environment

### ISSUE THREAD

**Issue by harishavenue1** [conda/conda#8629]
When tried to create new Virtual Environment using command, "conda create -n TensorflowVirtEnv", below details are displayed. 

(C:\ProgramData\Anaconda3) C:\Users\******\TensorflowObjDet>conda create -n TensorflowVirtEnv
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\******\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\******\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\******\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/admin/win-64
                          https://conda.anaconda.org/admin/noarch
            config file : C:\Users\******\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.17134
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create -n TensorflowVirtEnv`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'
	
Kindly provide a solution for the same.

**Comment by jjhelmus** [comment]
@harishavenue1 Can you try updating conda and requests using `conda update conda requests`.  Other reports of this type of error, e.g. #3962, were caused by misconfigured proxy configurations, the linked issue has more details.  Can you examine your proxy setting and see if there is anything that could be causing an issue.

**Comment by harishavenue1** [comment]
Tried updating conda & request, but resulted with same error.

(C:\ProgramData\Anaconda3) C:\Users\************\TensorflowObjDet>conda update conda requests
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\************\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\************\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\************\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/admin/win-64
                          https://conda.anaconda.org/admin/noarch
            config file : C:\Users\************\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.17134
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py update conda requests`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

//*********************************************************************************************************//
.condarc file is set with below details: 

channels:
  - admin

show_channel_urls: true
allow_other_channels: true

proxy_servers:
  http: http:\userName:password@company.com:8080
  https: https:\userName:password@companycom:8080

ssl_verify: true

//*********************************************************************************************************//
Kindly provide a solution for the same.

**Comment by jjhelmus** [comment]
I believe the proxy servers entry need to have two slashes, `http://` not `http:/`.

**Comment by harishavenue1** [comment]
updated the proxy entries as mentioned in format in .condarc file, but still issue occurs.
//*******************************************************************//
channels:
  - admin

show_channel_urls: true
allow_other_channels: true

proxy_servers:
  http: http:\\userName:passWord@company.com:8080
  https: https:\\userName:passWord@company.com:8080

ssl_verify: true

//*******************************************************************//

Error:
(C:\ProgramData\Anaconda3) C:\Users\userName\TensorflowObjDet>conda update conda requests
Fetching package metadata ...An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.21
       conda is private : False
      conda-env version : 4.3.21
    conda-build version : not installed
         python version : 3.6.1.final.0
       requests version : 2.14.2
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\Users\userName\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\userName\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\userName\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/admin/win-64
                          https://conda.anaconda.org/admin/noarch
            config file : C:\Users\userName\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.21 requests/2.14.2 CPython/3.6.1 Windows/10 Windows/10.0.17134
          administrator : False

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py update conda requests`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 632, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 221, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 93, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 112, in fetch_index
        repodatas = collect_all_repodata(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 74, in collect_all_repodata
        repodatas = _collect_repodatas_serial(use_cache, tasks)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in _collect_repodatas_serial
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 481, in <listcomp>
        for url, schan, pri in tasks]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 109, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 460, in fetch_repodata
        mod_etag_headers.get('_mod'))
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\repodata.py", line 138, in fetch_repodata_remote_request
        timeout=timeout)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 438, in send
        timeout=timeout
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
        self._prepare_proxy(conn)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 810, in _prepare_proxy
        conn.connect()
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 284, in connect
        conn = self._new_conn()
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\connection.py", line 141, in _new_conn
        (self.host, self.port), self.timeout, **extra_kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\requests\packages\urllib3\util\connection.py", line 51, in create_connection
        if host.startswith('['):
    AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by Ashishkumar-hub** [comment]
Having issue creating virtual environment through conda. I am using Pychram can anyone suggest me a fix. Kindly find SS for your pursual  

![image](https://user-images.githubusercontent.com/55132850/180150403-ac36d6ab-8de6-486b-9e18-b277a33796a0.png)
