### ISSUE TITLE
conda install error 

### ISSUE THREAD

**Issue by GavinYin** [conda/conda#8630]
### Steps to Reproduce

```
conda install pandas
Collecting package metadata: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 218, in _load
        mod_etag_headers.get('_mod'))
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 538, in fetch_repodata_remote_request
        raise Response304ContentUnchanged()
    conda.core.subdir_data.Response304ContentUnchanged
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1003, in __call__
        return func(*args, **kwargs)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 257, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 107, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 145, in solve_for_diff
        force_remove)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 235, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 286, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 688, in _prepare
        self.subdirs, prepared_specs)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 213, in get_reduced_index
        new_records = query_all(spec)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/index.py", line 176, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 93, in query
        self.load()
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 147, in load
        _internal_state = self._load()
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 224, in _load
        mod_etag_headers.get('_mod'))
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 271, in _read_local_repdata
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/home/aimaker/anaconda3/lib/python3.6/site-packages/conda/core/subdir_data.py", line 308, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/home/aimaker/anaconda3/lib/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/home/aimaker/anaconda3/lib/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/home/aimaker/anaconda3/lib/python3.6/json/decoder.py", line 355, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Unterminated string starting at: line 261328 column 7 (char 7933950)

`$ /home/aimaker/anaconda3/bin/conda install pandas`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=python279
                CONDA_EXE=/home/aimaker/anaconda3/bin/conda
             CONDA_PREFIX=/home/aimaker/anaconda3/envs/python279
           CONDA_PREFIX_1=/home/aimaker/anaconda3
    CONDA_PROMPT_MODIFIER=(python279)
         CONDA_PYTHON_EXE=/home/aimaker/anaconda3/bin/python
               CONDA_ROOT=/home/aimaker/anaconda3
              CONDA_SHLVL=2
                     PATH=/home/aimaker/anaconda3/bin:/usr/local/lib/nodejs/node-v10.14.2/bin:/h
                          ome/aimaker/anaconda3/envs/python279/bin:/home/aimaker/anaconda3/bin:/
                          home/aimaker/anaconda3/condabin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/
                          usr/bin:/usr/local/sbin:/usr/sbin:/usr/hdp/2.2.0.0-2041/spark/bin:/usr
                          /hdp/2.2.0.0-2041/spark/python:/usr/hdp/2.2.0.0-2041/spark/python/lib:
                          /usr/hdp/2.2.0.0-2041/spark/python/pyspark:/usr/hdp/2.2.0.0-2041/spark
                          :/home/aimaker/.local/bin:/home/aimaker/bin:/usr/java/jdk1.8.0_111/bin
                          :/usr/local/lib/maven3/bin
               PYTHONPATH=/usr/hdp/2.2.0.0-2041/spark/python:/usr/hdp/2.2.0.0-2041/spark/python/
                          lib/py4j-0.9-src.zip:
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               http_proxy=<set>
              https_proxy=<set>

     active environment : python279
    active env location : /home/aimaker/anaconda3/envs/python279
            shell level : 2
       user config file : /home/aimaker/.condarc
 populated config files : /home/aimaker/.condarc
          conda version : 4.6.14
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/aimaker/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aimaker/anaconda3/pkgs
                          /home/aimaker/.conda/pkgs
       envs directories : /home/aimaker/anaconda3/envs
                          /home/aimaker/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.5 Linux/3.10.107-1-tlinux2-0046 tlinux/2.2 glibc/2.17
                UID:GID : 1037:1037
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: 
Timeout reached. No report sent.
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : python279
    active env location : /home/aimaker/anaconda3/envs/python279
            shell level : 2
       user config file : /home/aimaker/.condarc
 populated config files : /home/aimaker/.condarc
          conda version : 4.6.14
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/aimaker/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/aimaker/anaconda3/pkgs
                          /home/aimaker/.conda/pkgs
       envs directories : /home/aimaker/anaconda3/envs
                          /home/aimaker/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.18.4 CPython/3.6.5 Linux/3.10.107-1-tlinux2-0046 tlinux/2.2 glibc/2.17
                UID:GID : 1037:1037
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
conda config --show-sources
==> /home/aimaker/.condarc <==
ssl_verify: False
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/aimaker/anaconda3/envs/python279:
#
# Name                    Version                   Build  Channel
absl-py                   0.7.1                    pypi_0    pypi
aimaker                   1.0                      pypi_0    pypi
argparse                  1.4.0                    pypi_0    pypi
asn1crypto                0.24.0                   py27_0    defaults
astor                     0.7.1                    pypi_0    pypi
backports-abc             0.5                      pypi_0    pypi
backports-functools-lru-cache 1.5                      pypi_0    pypi
backports-shutil-get-terminal-size 1.0.0                    pypi_0    pypi
backports-weakref         1.0.post1                pypi_0    pypi
certifi                   2018.11.29               py27_0    defaults
cffi                      1.11.5           py27he75722e_1    defaults
chardet                   3.0.4                    pypi_0    pypi
chinesecalendar           1.2.0                    pypi_0    pypi
click                     7.0                      pypi_0    pypi
cryptography              2.0.3            py27hea39389_1    defaults
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.3.0                    pypi_0    pypi
enum34                    1.1.6                    pypi_0    pypi
flask                     1.0.2                    pypi_0    pypi
flask-cors                3.0.7                    pypi_0    pypi
funcsigs                  1.0.2                    pypi_0    pypi
future                    0.17.1                   py27_0    defaults
futures                   3.2.0                    pypi_0    pypi
gast                      0.2.2                    pypi_0    pypi
grpcio                    1.19.0                   pypi_0    pypi
gunicorn                  19.9.0                   pypi_0    pypi
h5py                      2.9.0                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
ipaddress                 1.0.22                   py27_0    defaults
ipykernel                 4.10.0                   pypi_0    pypi
ipython                   5.8.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jinja2                    2.10                     pypi_0    pypi
jupyter-client            5.2.4                    pypi_0    pypi
jupyter-core              4.4.0                    pypi_0    pypi
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.6                    pypi_0    pypi
keras-preprocessing       1.0.5                    pypi_0    pypi
kiwisolver                1.0.1                    pypi_0    pypi
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
lightgbm                  2.2.2                    pypi_0    pypi
markdown                  3.0.1                    pypi_0    pypi
markupsafe                1.1.0                    pypi_0    pypi
matplotlib                2.2.4                    pypi_0    pypi
mleap                     0.8.1                    pypi_0    pypi
mock                      2.0.0                    pypi_0    pypi
ncurses                   6.1                  he6710b0_1    defaults
nose                      1.3.7                    pypi_0    pypi
nose-exclude              0.5.0                    pypi_0    pypi
numpy                     1.15.4                   pypi_0    pypi
openssl                   1.0.1k                        1    defaults
pandas                    0.23.4                   pypi_0    pypi
pathlib2                  2.3.3                    pypi_0    pypi
pattern                   2.6                      py27_0    defaults
pbr                       5.1.3                    pypi_0    pypi
pexpect                   4.6.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pip                       18.1                     py27_0    defaults
prompt-toolkit            1.0.15                   pypi_0    pypi
protobuf                  3.7.0                    pypi_0    pypi
psutil                    5.6.1                    pypi_0    pypi
ptyprocess                0.6.0                    pypi_0    pypi
py4j                      0.10.8.1                 pypi_0    pypi
pycparser                 2.19                     py27_0    defaults
pygments                  2.3.1                    pypi_0    pypi
pyhive                    0.6.1                    py27_0    defaults
pymysql                   0.9.3                    pypi_0    pypi
pyopenssl                 17.4.0           py27h3149609_0    defaults
pyparsing                 2.3.1                    pypi_0    pypi
pysocks                   1.6.8                    py27_0    defaults
python                    2.7.9                         3    defaults
python-dateutil           2.7.5                    pypi_0    pypi
pytz                      2018.9                   pypi_0    pypi
pyyaml                    3.13                     pypi_0    pypi
pyzmq                     17.1.2                   pypi_0    pypi
readline                  6.2                           2    defaults
requests                  2.21.0                   py27_0    defaults
sasl                      0.2.1                    py27_0    defaults
scandir                   1.9.0                    pypi_0    pypi
scikit-learn              0.19.0                   pypi_0    pypi
scipy                     1.2.0                    pypi_0    pypi
setuptools                40.6.3                   py27_0    defaults
simplegeneric             0.8.1                    pypi_0    pypi
simplejson                3.16.0                   pypi_0    pypi
singledispatch            3.4.0.3                  pypi_0    pypi
six                       1.12.0                   pypi_0    pypi
spark-sklearn             0.2.3                    pypi_0    pypi
sqlalchemy                1.2.15           py27h7b6447c_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
subprocess32              3.5.3                    pypi_0    pypi
system                    5.8                           2    defaults
tensorboard               1.13.1                   pypi_0    pypi
tensorflow                1.13.1                   pypi_0    pypi
tensorflow-estimator      1.13.0                   pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
thrift                    0.11.0           py27hf484d3e_0    defaults
thrift_sasl               0.3.0                    py27_1    defaults
tk                        8.5.18                        0    defaults
tornado                   5.1.1                    pypi_0    pypi
traitlets                 4.3.2                    pypi_0    pypi
urllib3                   1.24.1                   pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
werkzeug                  0.14.1                   pypi_0    pypi
wheel                     0.32.3                   py27_0    defaults
xgboost                   0.81                     pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by soapy1** [comment]
Try to do a `conda clean --all` and then trying to install pandas

**Comment by GavinYin** [comment]
> Try to do a `conda clean --all` and then trying to install pandas

if i do it, it will clean all packages before I installed?

**Comment by soapy1** [comment]
It will remove index caches, lock files, unused cache packages and tarballs

**Comment by godman2016** [comment]
> It will remove index caches, lock files, unused cache packages and tarballs



> It will remove index caches, lock files, unused cache packages and tarballs

Thanks a lot, it has solved my problem!
