### ISSUE TITLE
once i try to create a new env or install packages or just conda info ,the error arise

### ISSUE THREAD

**Issue by qq1401318558** [conda/conda#8652]
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 789, in __call__
        return func(*args, **kwargs)
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 78, in _main
        exit_code = do_call(args, p)
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 77, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 317, in execute
        info_dict = get_info_dict(args.system)
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/cli/main_info.py", line 186, in get_info_dict
        user_agent=context.user_agent,
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 613, in user_agent
        return _get_user_agent(self.platform)
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/_vendor/auxlib/decorators.py", line 56, in _memoized_func
        result = func(*args, **kwargs)
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/base/context.py", line 907, in _get_user_agent
        from .._vendor.distro import linux_distribution
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 1084, in <module>
        _distro = LinuxDistribution()
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 600, in __init__
        if include_lsb else {}
      File "/home/amax/anaconda3/lib/python3.6/site-packages/conda/_vendor/distro.py", line 943, in _get_lsb_release_info
        raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
    subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 126.

`$ /home/amax/anaconda3/bin/conda info`

An unexpected error has occurred. Conda has prepared the above report.
If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
[y/N]:

**Comment by qq1401318558** [comment]
i have reinstall the anaconda ,but con't solve it
