### ISSUE TITLE
Not able to remove a conda environment

### ISSUE THREAD

**Issue by M-nes** [conda/conda#8678]
## Current Behavior

Hello,

Wanting to start working with julia, I created an environment dedicated for that. First the installation of Julia didn't work, for some reason, but that's ok I can deal with that later it's not even urgent. However, I got a problem when I tried removing that environment I created called myjulia. I also suppose that this problem could be related to the fact I can't install Julia too.

Your help would be very much appreciated, I won't say I'm a new Anaconda user but I am clearly not good enough to understand what's going on here.

### Command used to remove the environment

```
conda remove --name myjulia --all
```
I also tried the following command but I got the same problem:
```
conda remove -n myjulia --all
```
I then tried removing the environment directly from Anaconda-Navigator but nothing happens either.

## Expected Behavior
I've created and removed environment before without facing any issues so I expected this to work as well. I however get an error message and the removal just doesn't work.
The first step seems to be normal:

<details open><summary><code>`normal part`</code></summary><p>

```
conda remove --name myjulia --all

Remove all packages in environment /Users/im/anaconda3/envs/myjulia:


## Package Plan ##

  environment location: /Users/im/anaconda3/envs/myjulia


The following packages will be REMOVED:

  appnope-0.1.0-py37_0
  attrs-19.1.0-py37_1
  backcall-0.1.0-py37_0
  blas-1.0-openblas
  bleach-3.1.0-py37_0
  ca-certificates-2019.1.23-0
  certifi-2019.3.9-py37_0
  dbus-1.13.6-h90a0687_0
  decorator-4.4.0-py37_1
  defusedxml-0.6.0-py_0
  entrypoints-0.3-py37_0
  expat-2.2.6-h0a44026_0
  gettext-0.19.8.1-h15daf44_3
  glib-2.56.2-hd9629dc_0
  icu-58.2-h4b95b61_1
  ipykernel-5.1.0-py37h39e3cac_0
  ipython-7.5.0-py37h39e3cac_0
  ipython_genutils-0.2.0-py37_0
  ipywidgets-7.4.2-py37_0
  jedi-0.13.3-py37_0
  jinja2-2.10.1-py37_0
  jpeg-9b-he5867d9_2
  jsonschema-3.0.1-py37_0
  jupyter-1.0.0-py37_7
  jupyter_client-5.2.4-py37_0
  jupyter_console-6.0.0-py37_0
  jupyter_contrib_core-0.3.3-py_2
  jupyter_contrib_nbextensions-0.5.1-py37_0
  jupyter_core-4.4.0-py37_0
  jupyter_highlight_selected_word-0.2.0-py37_1000
  jupyter_latex_envs-1.4.4-py37_1000
  jupyter_nbextensions_configurator-0.4.1-py37_0
  libcxx-4.0.1-hcfea43d_1
  libcxxabi-4.0.1-hcfea43d_1
  libedit-3.1.20181209-hb402a30_0
  libffi-3.2.1-h475c297_4
  libiconv-1.15-hdd342a3_7
  libpng-1.6.37-ha441bb4_0
  libsodium-1.0.16-h3efe00b_0
  libxml2-2.9.9-hab757c2_0
  libxslt-1.1.33-h33a18ac_0
  lxml-4.3.3-py37hef8c89e_0
  markupsafe-1.1.1-py37h1de35cc_0
  mistune-0.8.4-py37h1de35cc_0
  nbconvert-5.5.0-py_0
  nbformat-4.4.0-py37_0
  ncurses-6.1-h0a44026_1
  notebook-5.7.8-py37_0
  openssl-1.1.1b-h1de35cc_1
  pandoc-2.2.3.2-0
  pandocfilters-1.4.2-py37_1
  parso-0.4.0-py_0
  pcre-8.43-h0a44026_0
  pexpect-4.7.0-py37_0
  pickleshare-0.7.5-py37_0
  pip-19.1.1-py37_0
  prometheus_client-0.6.0-py37_0
  prompt_toolkit-2.0.9-py37_0
  ptyprocess-0.6.0-py37_0
  pygments-2.4.0-py_0
  pyqt-5.9.2-py37h655552a_2
  pyrsistent-0.14.11-py37h1de35cc_0
  python-3.7.3-h359304d_0
  python-dateutil-2.8.0-py37_0
  pyyaml-5.1-py37h1de35cc_0
  pyzmq-18.0.0-py37h0a44026_0
  qt-5.9.7-h468cd18_1
  qtconsole-4.4.4-py_0
  readline-7.0-h1de35cc_5
  send2trash-1.5.0-py37_0
  setuptools-41.0.1-py37_0
  sip-4.19.8-py37h0a44026_0
  six-1.12.0-py37_0
  sqlite-3.28.0-ha441bb4_0
  terminado-0.8.2-py37_0
  testpath-0.4.2-py37_0
  tk-8.6.8-ha441bb4_0
  tornado-6.0.2-py37h1de35cc_0
  traitlets-4.3.2-py37_0
  wcwidth-0.1.7-py37_0
  webencodings-0.5.1-py37_1
  wheel-0.33.2-py37_0
  widgetsnbextension-3.4.2-py37_0
  xz-5.2.4-h1de35cc_4
  yaml-0.1.7-hc338f04_2
  zeromq-4.3.1-h0a44026_3
  zlib-1.2.11-h1de35cc_3


Proceed ([y]/n)? y
```
</p></details>

## Error gotten
And then I get the following lines that I cannot understand at all...
<details open><summary><code>`error part`</code></summary><p>

```
Preparing transaction: done
Verifying transaction: done
Executing transaction: \ b'+ /Users/im/anaconda3/envs/myjulia/bin/jupyter-contrib-nbextension uninstall --sys-prefix\n[I 10:03:34 UninstallContribNbextensionsApp] jupyter contrib nbextension uninstall --sys-prefix\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling jupyter_contrib_nbextensions nbextension files from jupyter data directory\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling rubberband rubberband/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling scroll_down scroll_down/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling hinterland hinterland/hinterland\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling snippets snippets/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling toggle_all_line_numbers toggle_all_line_numbers/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling notify notify/notify\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling runtools runtools/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling tree-filter tree-filter/index\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling table_beautifier table_beautifier/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling freeze freeze/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling exercise2 exercise2/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling execution_dependencies execution_dependencies/execution_dependencies\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling skill skill/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling splitcell splitcell/splitcell\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling autosavetime autosavetime/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling select_keymap select_keymap/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling livemdpreview livemdpreview/livemdpreview\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling gist_it gist_it/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling cell_filter cell_filter/cell_filter\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling scratchpad scratchpad/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling toc2 toc2/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling nbTranslate nbTranslate/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling equation-numbering equation-numbering/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling navigation-hotkeys navigation-hotkeys/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling snippets_menu snippets_menu/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling printview printview/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling export_embedded export_embedded/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling autoscroll autoscroll/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling hide_input hide_input/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling hide_input_all hide_input_all/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling keyboard_shortcut_editor keyboard_shortcut_editor/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling help_panel help_panel/help_panel\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling move_selected_cells move_selected_cells/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling zenmode zenmode/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling skip-traceback skip-traceback/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling python-markdown python-markdown/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling codefolding codefolding/edit\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling codefolding codefolding/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling collapsible_headings collapsible_headings/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling exercise exercise/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling codemirror_mode_extensions codemirror_mode_extensions/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling ruler ruler/edit\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling ruler ruler/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling contrib_nbextensions_help_item contrib_nbextensions_help_item/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling datestamper datestamper/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling init_cell init_cell/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling limit_output limit_output/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling qtconsole qtconsole/qtconsole\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling addbefore addbefore/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling highlighter highlighter/highlighter\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling comment-uncomment comment-uncomment/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling code_font_size code_font_size/code_font_size\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling varInspector varInspector/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling execute_time execute_time/ExecuteTime\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling spellchecker spellchecker/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling code_prettify code_prettify/2to3\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling code_prettify code_prettify/code_prettify\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling code_prettify code_prettify/autopep8\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling code_prettify code_prettify/isort\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling load_tex_macros load_tex_macros/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling hide_header hide_header/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling highlight_selected_word highlight_selected_word/main\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling latex_envs latex_envs/latex_envs\n[I 10:03:34 UninstallContribNbextensionsApp] Uninstalling jupyter_contrib_nbextensions items from config in /Users/im/anaconda3/envs/myjulia/etc/jupyter\n[I 10:03:34 UninstallContribNbextensionsApp] - Disabling contrib_nbextensions_help_item/main\n[I 10:03:34 UninstallContribNbextensionsApp] --  Editing config: /Users/im/anaconda3/envs/myjulia/etc/jupyter/nbconfig/notebook.json\n[I 10:03:34 UninstallContribNbextensionsApp] - Editing config: /Users/im/anaconda3/envs/myjulia/etc/jupyter/jupyter_nbconvert_config.json\n[I 10:03:34 UninstallContribNbextensionsApp] --  Configuring nbconvert template path\n[I 10:03:34 UninstallContribNbextensionsApp] --  Configuring nbconvert preprocessors\n[I 10:03:34 UninstallContribNbextensionsApp] - Writing config: /Users/im/anaconda3/envs/myjulia/etc/jupyter/jupyter_nbconvert_config.json\n[I 10:03:34 UninstallContribNbextensionsApp] --  Removing now-empty config file /Users/im/anaconda3/envs/myjulia/etc/jupyter/jupyter_nbconvert_config.json\n'
\ b'+ /Users/im/anaconda3/envs/myjulia/bin/jupyter-nbextensions_configurator disable --sys-prefix\nDisabling: jupyter_nbextensions_configurator\n- Writing config: /Users/im/anaconda3/envs/myjulia/etc/jupyter\nDisabling notebook nbextension nbextensions_configurator/config_menu/main...\nDisabling tree nbextension nbextensions_configurator/tree_tab/main...\n'
| b'+ /Users/im/anaconda3/envs/myjulia/bin/python -c \'import logging; from jupyter_contrib_core.notebook_compat.nbextensions import uninstall_nbextension_python; uninstall_nbextension_python(\'\\\'\'jupyter_highlight_selected_word\'\\\'\', sys_prefix=True, logger=logging.getLogger())\'\nTraceback (most recent call last):\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 6, in <module>\n    from notebook.extensions import BaseExtensionApp\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/notebook/__init__.py", line 25, in <module>\n    from .nbextensions import install_nbextension\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/notebook/nbextensions.py", line 31, in <module>\n    from .config_manager import BaseJSONConfigManager\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/notebook/config_manager.py", line 14, in <module>\n    from six import PY3\nModuleNotFoundError: No module named \'six\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 10, in <module>\n    from notebook.nbextensions import BaseNBExtensionApp\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/notebook/__init__.py", line 25, in <module>\n    from .nbextensions import install_nbextension\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/notebook/nbextensions.py", line 31, in <module>\n    from .config_manager import BaseJSONConfigManager\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/notebook/config_manager.py", line 14, in <module>\n    from six import PY3\nModuleNotFoundError: No module named \'six\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "<string>", line 1, in <module>\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/jupyter_contrib_core/notebook_compat/nbextensions.py", line 12, in <module>\n    from ._compat.nbextensions import BaseNBExtensionApp\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/jupyter_contrib_core/notebook_compat/_compat/nbextensions.py", line 30, in <module>\n    from jupyter_core.application import JupyterApp\n  File "/Users/im/anaconda3/envs/myjulia/lib/python3.7/site-packages/jupyter_core/application.py", line 30, in <module>\n    from traitlets.config.application import Application, catch_config_error\nModuleNotFoundError: No module named \'traitlets.config.application\'\n'
WARNING conda.core.link:run_script(1098): pre-unlink script failed for package conda-forge::jupyter_highlight_selected_word-0.2.0-py37_1000
consider notifying the package maintainer
failed
ERROR conda.core.link:_execute(568): An error occurred while uninstalling package 'defaults::qt-5.9.7-h468cd18_1'.
PermissionError(1, 'Operation not permitted')
Attempting to roll back.

Rolling back transaction: done

[Errno 1] Operation not permitted: '/Users/im/anaconda3/envs/myjulia/bin/Assistant.app/Contents/PkgInfo' -> '/Users/im/anaconda3/envs/myjulia/bin/Assistant.app/Contents/PkgInfo.c~'
```

With the following lines being the most important I think:
```
WARNING conda.core.link:run_script(1098): pre-unlink script failed for package conda-forge::jupyter_highlight_selected_word-0.2.0-py37_1000
consider notifying the package maintainer
failed
ERROR conda.core.link:_execute(568): An error occurred while uninstalling package 'defaults::qt-5.9.7-h468cd18_1'.
PermissionError(1, 'Operation not permitted')
Attempting to roll back.

Rolling back transaction: done

[Errno 1] Operation not permitted: '/Users/im/anaconda3/envs/myjulia/bin/Assistant.app/Contents/PkgInfo' -> '/Users/im/anaconda3/envs/myjulia/bin/Assistant.app/Contents/PkgInfo.c~'
```
</p></details>

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : myjulia
    active env location : /Users/im/anaconda3/envs/myjulia
            shell level : 1
       user config file : /Users/im/.condarc
 populated config files : /Users/im/.condarc
          conda version : 4.6.12
    conda-build version : 3.0.27
         python version : 3.6.8.final.0
       base environment : /Users/im/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/im/anaconda3/pkgs
                          /Users/im/.conda/pkgs
       envs directories : /Users/im/anaconda3/envs
                          /Users/im/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.12 requests/2.18.4 CPython/3.6.8 Darwin/18.5.0 OSX/10.14.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/im/.condarc <==
add_pip_as_python_dependency: True
create_default_packages:
  - ipykernel
  - jupyter
  - jupyter_contrib_nbextensions
  - pip
  - blas=*=openblas
ssl_verify: True
channel_priority: strict
channels:
  - defaults
  - conda-forge
show_channel_urls: True
sat_solver: pycryptosat
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/im/anaconda3/envs/myjulia:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0                    py37_0    defaults
attrs                     19.1.0                   py37_1    defaults
backcall                  0.1.0                    py37_0    defaults
blas                      1.0                    openblas    defaults
bleach                    3.1.0                    py37_0    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.6.0                      py_0    defaults
entrypoints               0.3                      py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
glib                      2.56.2               hd9629dc_0    defaults
icu                       58.2                 h4b95b61_1    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.5.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10.1                   py37_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.4.0                    py37_0    defaults
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libiconv                  1.15                 hdd342a3_7    defaults
libpng                    1.6.37               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libxml2                   2.9.9                hab757c2_0    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
lxml                      4.3.3            py37hef8c89e_0    defaults
markupsafe                1.1.1            py37h1de35cc_0    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
notebook                  5.7.8                    py37_0    defaults
openssl                   1.1.1b               h1de35cc_1    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.4.0                      py_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pip                       19.1.1                   py37_0    defaults
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
pygments                  2.4.0                      py_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pyrsistent                0.14.11          py37h1de35cc_0    defaults
python                    3.7.3                h359304d_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
pyyaml                    5.1              py37h1de35cc_0    defaults
pyzmq                     18.0.0           py37h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtconsole                 4.4.4                      py_0    defaults
readline                  7.0                  h1de35cc_5    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                41.0.1                   py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.28.0               ha441bb4_0    defaults
terminado                 0.8.2                    py37_0    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tornado                   6.0.2            py37h1de35cc_0    defaults
traitlets                 4.3.2                    py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
wheel                     0.33.2                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```
</p></details>

**Comment by maximlamare** [comment]
I have the same issue as @M-nes, however it seems to depend on the environments I want to remove.

**Comment by TeejIBM** [comment]
I am experiencing this same issue whenever I am trying to install a package from Conda-Forge.  It also appears when I am trying to remove qt.  sudo command does not improve the scenario.  My info:

```     active environment : base
    active env location : /anaconda3
            shell level : 1
       user config file : /Users/teej/.condarc
 populated config files : /Users/teej/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /anaconda3/pkgs
                          /Users/teej/.conda/pkgs
       envs directories : /anaconda3/envs
                          /Users/teej/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False```

I am using MacOS 10.14.5.

Error is:

```Executing transaction: failed
ERROR conda.core.link:_execute(568): An error occurred while uninstalling package 'defaults::qt-5.9.7-h468cd18_1'.
PermissionError(1, 'Operation not permitted')
Attempting to roll back.

Rolling back transaction: done

[Errno 1] Operation not permitted: '/anaconda3/envs/Coursera/bin/Assistant.app/Contents/PkgInfo' -> '/anaconda3/envs/Coursera/bin/Assistant.app/Contents/PkgInfo.c~'```
