### ISSUE TITLE
Cannot create minimal python environment with conda 4.7.0

### ISSUE THREAD

**Issue by rzillman** [conda/conda#8705]
### Steps to Reproduce

```
# conda create -n tmp python=3.7 -v
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... done
initializing UnlinkLinkTransaction with
  target_prefix: C:\Users\rzillman\envs\tmp
  unlink_precs:

  link_precs:
    defaults::ca-certificates-2019.1.23-0
    defaults::vs2015_runtime-14.15.26706-h3a45250_4
    defaults::vc-14.1-h0510ff6_4
    defaults::openssl-1.1.1b-he774522_1
    defaults::sqlite-3.28.0-he774522_0
    defaults::python-3.7.3-h8c8aaf0_1
    defaults::certifi-2019.3.9-py37_0
    defaults::wincertstore-0.2-py37_0
    defaults::setuptools-41.0.1-py37_0
    defaults::wheel-0.33.4-py37_0
    defaults::pip-19.1.1-py37_0



## Package Plan ##

  environment location: C:\Users\rzillman\envs\tmp

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2019.1.23-0
  certifi            pkgs/main/win-64::certifi-2019.3.9-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1b-he774522_1
  pip                pkgs/main/win-64::pip-19.1.1-py37_0
  python             pkgs/main/win-64::python-3.7.3-h8c8aaf0_1
  setuptools         pkgs/main/win-64::setuptools-41.0.1-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.28.0-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.15.26706-h3a45250_4
  wheel              pkgs/main/win-64::wheel-0.33.4-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Proceed ([y]/n)? y

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... ===> LINKING PACKAGE: defaults::ca-certificates-2019.1.23-0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\ca-certificates-2019.1.23-0


===> LINKING PACKAGE: defaults::vs2015_runtime-14.15.26706-h3a45250_4 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\vs2015_runtime-14.15.26706-h3a45250_4


===> LINKING PACKAGE: defaults::vc-14.1-h0510ff6_4 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\vc-14.1-h0510ff6_4


===> LINKING PACKAGE: defaults::openssl-1.1.1b-he774522_1 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\openssl-1.1.1b-he774522_1


===> LINKING PACKAGE: defaults::sqlite-3.28.0-he774522_0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\sqlite-3.28.0-he774522_0


===> LINKING PACKAGE: defaults::python-3.7.3-h8c8aaf0_1 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\python-3.7.3-h8c8aaf0_1


===> LINKING PACKAGE: defaults::certifi-2019.3.9-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\certifi-2019.3.9-py37_0


===> LINKING PACKAGE: defaults::wincertstore-0.2-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\wincertstore-0.2-py37_0


===> LINKING PACKAGE: defaults::setuptools-41.0.1-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\setuptools-41.0.1-py37_0


===> LINKING PACKAGE: defaults::wheel-0.33.4-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\wheel-0.33.4-py37_0


===> LINKING PACKAGE: defaults::pip-19.1.1-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp
  source=C:\Miniconda3\pkgs\pip-19.1.1-py37_0


done
An error occurred while installing package 'None'.
AssertionError()
Attempting to roll back.


Rolling back transaction: ...working... ===> REVERSING PACKAGE LINK: defaults::pip-19.1.1-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::wheel-0.33.4-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::setuptools-41.0.1-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::wincertstore-0.2-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::certifi-2019.3.9-py37_0 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::python-3.7.3-h8c8aaf0_1 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::sqlite-3.28.0-he774522_0 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::openssl-1.1.1b-he774522_1 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::vc-14.1-h0510ff6_4 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::vs2015_runtime-14.15.26706-h3a45250_4 <===
  prefix=C:\Users\rzillman\envs\tmp


===> REVERSING PACKAGE LINK: defaults::ca-certificates-2019.1.23-0 <===
  prefix=C:\Users\rzillman\envs\tmp


done
Traceback (most recent call last):
  File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1013, in __call__
    return func(*args, **kwargs)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Miniconda3\lib\site-packages\conda\cli\main_create.py", line 37, in execute
    install(args, parser, 'create')
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 306, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "C:\Miniconda3\lib\site-packages\conda\cli\install.py", line 335, in handle_txn
    unlink_link_transaction.execute()
  File "C:\Miniconda3\lib\site-packages\conda\core\link.py", line 244, in execute
    self._execute(tuple(concat(interleave(itervalues(self.prefix_action_groups)))))
  File "C:\Miniconda3\lib\site-packages\conda\core\link.py", line 650, in _execute
    rollback_excs,
conda.CondaMultiError:
()

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

     active environment : None
            shell level : 0
       user config file : C:\Users\rzillman\.condarc
 populated config files : C:\ProgramData\conda\.condarc
          conda version : 4.7.0
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       virtual packages :
       base environment : C:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Miniconda3\pkgs
                          C:\Users\rzillman\.conda\pkgs
                          C:\Users\rzillman\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\rzillman\envs
                          C:\Miniconda3\envs
                          C:\Users\rzillman\.conda\envs
                          C:\Users\rzillman\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.0 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
# conda config --show-sources                     
==> C:\ProgramData\conda\.condarc <==             
envs_dirs:                                        
  - ~/envs                                        
channel_priority: disabled                        
                                                  
==> envvars <==                                   
bld_path: C:\Users\rzillman\.home\conda-build     
```

**Comment by msarahan** [comment]
Thanks.  This broke because of some details with the new package format.  We didn't test well enough with those packages in our integration tests.  We're working on fixing it hoping for a new canary release later this week.

If you have broken your root environment and now can't use it, I think you can get back to an older version by installing a package path manually:

``conda install C:\Miniconda3\pkgs\conda-4.6.14-py7_0.tar.bz2`` for example.  Adjust the filename as necessary for whatever you have on your computer.

I have removed 4.7.0 from the conda-canary channel.

**Comment by dhirschfeld** [comment]
Installing seemed to work fine so reverting wasn't a problem for me. It seemed to be just environment creation that was broken.

**Comment by soapy1** [comment]
This is fixed in latest conda
