### ISSUE TITLE
Unable to activate virtual enviroment.. Kindly suggest, changes required if any..

### ISSUE THREAD

**Issue by harishavenue1** [conda/conda#8706]
```
C:\Users\userName\TensorProject\TensorflowObjDet>conda create -n TensorflowVirtEnv
[y/N]: y

C:\Users\userName\TensorProject\TensorflowObjDet>activate TensorflowVirtEnv

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 138, in main
        return activator_main()
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\activate.py", line 926, in main
        context.__init__()  # On import, context does not include SEARCH_PATH. This line fixes that.
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\base\context.py", line 285, in __init__
        argparse_args=argparse_args)
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 762, in __init__
        self._set_search_path(search_path)
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 768, in _set_search_path
        self._set_raw_data(load_file_configs(search_path))
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 391, in load_file_configs
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 391, in <genexpr>
        raw_data = odict(kv for kv in chain.from_iterable(load_paths))
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 366, in _file_yaml_loader
        yield fullpath, YamlRawParameter.make_raw_parameters_from_file(fullpath)
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\configuration.py", line 345, in make_raw_parameters_from_file
        ruamel_yaml = yaml_load(fh)
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\common\serialize.py", line 56, in yaml_load
        return yaml.load(string, Loader=yaml.RoundTripLoader, version="1.2")
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\main.py", line 640, in load        return loader._constructor.get_single_data()  # type: ignore
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 187, in compose_mapping_node
        while not self.parser.check_event(MappingEndEvent):
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 144, in check_event
        self.current_event = self.state()
      File "C:\Users\userName\AppData\Local\Continuum\anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 561, in parse_block_mapping_key
        token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block mapping
      in "C:\Users\userName\.condarc", line 1, column 1
    expected <block end>, but found '<scalar>'
      in "C:\Users\userName\.condarc", line 9, column 3

`$ C:\Users\userName\AppData\Local\Continuum\anaconda3\Scripts\conda-script.py shell.cmd.exe activate TensorflowVirtEnv`

  environment variables:
                 CIO_TEST=<not set>
                CLASSPATH=.;C:\Program Files (x86)\Java\jdk1.6.0_26\lib;C:\Program Files
                          (x86)\Java\jdk1.6.0_26\lib\tools.jar
                CONDA_EXE=C:\Users\userName\AppData\Local\Continuum\anaconda3\condabin\..\Scripts
                          \conda.exe
               CONDA_ROOT=C:\Users\userName\AppData\Local\Continuum\anaconda3
                 HOMEPATH=\Users\userName
                     PATH=C:\Users\userName\AppData\Local\Continuum\anaconda3\condabin\..;C:\User
                          s\userName\AppData\Local\Continuum\anaconda3\condabin\..\Library\mingw-
                          w64\bin;C:\Users\userName\AppData\Local\Continuum\anaconda3\condabin\..
                          \Library\usr\bin;C:\Users\userName\AppData\Local\Continuum\anaconda3\co
                          ndabin\..\Library\bin;C:\Users\userName\AppData\Local\Continuum\anacond
                          a3\condabin\..\Scripts;C:\Users\userName\AppData\Local\Continuum\anacon
                          da3\condabin\..\bin;C:\Oracle\product\11.2.0\client_1\bin;C:\ProgramDa
                          ta\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\Syst
                          em32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program
                          Files\Maven\apache-maven-3.1.1\bin;C:\Program Files\PuTTY\;C:\Program
                          Files (x86)\Java\jdk1.6.0_26\bin;C:\Program Files
                          (x86)\Java\jdk1.6.0_26\jre\bin;C:\Program
                          Files\1E\NomadBranch\;C:\Program Files (x86)\WinMerge\;C:\Program
                          Files (x86)\MySQL\MySQL Utilities 1.3.5\;C:\Program Files\nodejs\;C:\W
                          INDOWS\system32\config\systemprofile\AppData\Roaming\npm;C:\Users\1570
                          130\AppData\Roaming\npm;C:\WINDOWS\System32\OpenSSH\;C:\Program Files
                          (x86)\WhoAmI\;C:\Users\userName\AppData\Local\Continuum\anaconda3;C:\Us
                          ers\userName\AppData\Local\Continuum\anaconda3\Library\mingw-w64\bin;C:
                          \Users\userName\AppData\Local\Continuum\anaconda3\Library\usr\bin;C:\Us
                          ers\userName\AppData\Local\Continuum\anaconda3\Library\bin;C:\Users\157
                          0130\AppData\Local\Continuum\anaconda3\Scripts;C:\Users\userName\AppDat
                          a\Local\Microsoft\WindowsApps;C:\Users\userName\apache-maven-3.1.1\bin;
                          C:\Users\userName\AppData\Roaming\npm;C:\Users\userName\AppData\Local\at
                          om\bin;C:\Users\userName\AppData\Local\Microsoft\WindowsApps;C:\Users\1
                          570130\apache-maven-3.1.1\bin;C:\Program
                          Files\Java\jdk1.7.0_25\bin;C:\Program Files\JetBrains\PyCharm
                          Community Edition 2019.1.1\bin;
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\userName\.condarc
 populated config files :
          conda version : 4.6.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\userName\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\userName\AppData\Local\Continuum\anaconda3\pkgs
                          C:\Users\userName\.conda\pkgs
                          C:\Users\userName\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\userName\AppData\Local\Continuum\anaconda3\envs
                          C:\Users\userName\.conda\envs
                          C:\Users\userName\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

**Comment by soapy1** [comment]
It looks like there is a problem with your .condarc. Could you share that too
