### ISSUE TITLE
Can install but not import packages

### ISSUE THREAD

**Issue by thomasaarholt** [conda/conda#8716]
## Current Behavior
From time to time I encounter packages that are installable by conda in my environment, but when I run `import package` in python in that same environment, I either find myself importing an older version of the package, or not finding any package at all.

As an example, this morning I found that my installation of dask wasn't working:

```bash
python
>>> import dask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dask'
```
I then tried installing dask using conda, where I realise that I *do* have dask installed:

```
conda install dask
...
The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    dask-1.2.2                 |             py_0           4 KB  conda-forge
    dask-core-1.2.2            |             py_0         534 KB  conda-forge
```
But trying to import it again yields the same result:
```bash
python
>>> import dask
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'dask'
```

I am sometimes able to fix this by fully uninstalling the package and then reinstalling (say, by `pip uninstall dask; pip uninstall dask; conda install dask`). However, what if I am updating other packages but still importing the old version of them, without being aware of it? 

Is there any command I can run to make conda "check" that the packages are correctly installed?

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : py37
    active env location : /Users/thomas/miniconda3/envs/py37
            shell level : 1
       user config file : /Users/thomas/.condarc
 populated config files : /Users/thomas/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.7
         python version : 3.7.2.final.0
       base environment : /Users/thomas/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/osx-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/thomas/miniconda3/pkgs
                          /Users/thomas/.conda/pkgs
       envs directories : /Users/thomas/miniconda3/envs
                          /Users/thomas/.conda/envs
               platform : osx-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.2 Darwin/18.6.0 OSX/10.14.5
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/thomas/.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/thomas/miniconda3/envs/py37:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
appnope                   0.1.0                 py37_1000    conda-forge
ase                       3.17.0                     py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
astroid                   2.1.0                 py37_1000    conda-forge
atomap                    0.0.9.dev1                dev_0    <develop>
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
autopep8                  1.4.3                      py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
blas                      1.0                         mkl    defaults
bleach                    3.1.0                      py_0    conda-forge
blosc                     1.16.3               h0a44026_0    conda-forge
bokeh                     1.0.4                 py37_1000    conda-forge
bootstrap                 4.3.1                         0    conda-forge
bzip2                     1.0.6             h1de35cc_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.11.5          py37h342bebf_1001    conda-forge
cftime                    1.0.3.4         py37h917ab60_1000    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
clangdev                  7.0.0             hba662a8_1000    conda-forge
click                     7.0                        py_0    conda-forge
click-completion          0.5.1                    pypi_0    pypi
cloudpickle               0.6.1                      py_0    conda-forge
colorama                  0.4.1                    pypi_0    pypi
crayons                   0.2.0                    pypi_0    pypi
cryptography              2.4.2            py37ha12b0ac_0    defaults
curl                      7.62.0               ha441bb4_0    defaults
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.7           py37h6de7cb9_0    conda-forge
cytoolz                   0.9.0.1          py37h470a237_1    conda-forge
dask                      1.2.2                      py_0    conda-forge
dask-core                 1.2.2                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
dill                      0.2.9                    py37_0    conda-forge
distributed               1.28.1                   py37_0    conda-forge
docutils                  0.14                  py37_1001    conda-forge
electropy                 0.1                       dev_0    <develop>
entrypoints               0.3                   py37_1000    conda-forge
fastcache                 1.0.2           py37h1de35cc_1001    conda-forge
flask                     1.0.2                      py_2    conda-forge
freetype                  2.9.1             h5a5313f_1004    conda-forge
gmp                       6.1.2             h0a44026_1000    conda-forge
gmpy2                     2.0.8           py37h3aece09_1002    conda-forge
h5netcdf                  0.6.2                    pypi_0    pypi
h5py                      2.9.0           py37hafca783_1000    conda-forge
hdf4                      4.2.13            hf3c6af0_1002    conda-forge
hdf5                      1.10.4          nompi_h646315f_1105    conda-forge
heapdict                  1.0.0                 py37_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hyperspy                  1.5.dev0                  dev_0    <develop>
hyperspy-gui-ipywidgets   1.1.1                      py_1    conda-forge
hyperspy-gui-traitsui     1.1.1                 py37_1000    conda-forge
icu                       58.2              h0a44026_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imageio                   2.4.1                 py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.1                      144    defaults
ipydatawidgets            4.0.0                      py_0    conda-forge
ipykernel                 5.1.0           py37h24bf2e0_1001    conda-forge
ipympl                    0.2.1                 py37_1001    conda-forge
ipyparallel               6.2.3                 py37_1000    conda-forge
ipyscales                 0.3.0                      py_0    conda-forge
ipython                   7.2.0           py37h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipyvolume                 0.5.1                 py37_1001    conda-forge
ipywebrtc                 0.4.3                 py37_1000    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py37_1000    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
jsonschema                3.0.0a3               py37_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_contrib_nbextensions 0.5.1                    py37_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py37_1000    conda-forge
jupyter_latex_envs        1.4.4                 py37_1000    conda-forge
jupyter_nbextensions_configurator 0.4.1                    py37_0    conda-forge
jupyterlab                0.35.6                   py37_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
kiwisolver                1.0.1           py37h04f5b5a_1002    conda-forge
krb5                      1.14.6                        0    conda-forge
lazy-object-proxy         1.3.1           py37h1de35cc_1000    conda-forge
libblas                   3.8.0           5_hd44dcd8_netlib    conda-forge
libcblas                  3.8.0           5_hd44dcd8_netlib    conda-forge
libcurl                   7.62.0               h051b688_0    defaults
libcxx                    7.0.0                h2d50403_2    conda-forge
libcxxabi                 4.0.1                hebd6815_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h0a44026_1005    conda-forge
libgfortran               3.0.1                h93005f0_2    anaconda
libgfortran-ng            3.0.1                h93005f0_2    defaults
libiconv                  1.15              h1de35cc_1004    conda-forge
liblapack                 3.8.0           5_hd44dcd8_netlib    conda-forge
libnetcdf                 4.6.2             h6b88ef6_1001    conda-forge
libpng                    1.6.36            ha441bb4_1000    conda-forge
libsodium                 1.0.16            h1de35cc_1001    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.10            h79f4b77_1001    conda-forge
libxml2                   2.9.8             hf14e9c8_1005    conda-forge
libxslt                   1.1.32            h33a18ac_1002    conda-forge
link-traits               1.0.2                 py37_1002    conda-forge
llvm-meta                 7.0.0                         0    conda-forge
llvmdev                   7.0.0             h04f5b5a_1000    conda-forge
llvmlite                  0.28.0           py37hf292337_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.3            py37h08abf6f_0    conda-forge
markupsafe                1.1.0           py37h1de35cc_1000    conda-forge
matplotlib                3.0.2                 py37_1001    conda-forge
matplotlib-base           3.0.2           py37hf043ca5_1001    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mendeleev                 0.4.4                    pypi_0    pypi
mistune                   0.8.4           py37h1de35cc_1000    conda-forge
mkl                       2018.0.3                      1    defaults
mkl_fft                   1.0.6            py37hb8a8100_0    defaults
mkl_random                1.0.1            py37h5d10147_1    defaults
more-itertools            4.3.0                 py37_1000    conda-forge
mpc                       1.1.0             h3aece09_1006    conda-forge
mpfr                      4.0.1             h0a95893_1000    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
mrcz                      0.5.0                    py37_0    conda-forge
msgpack-python            0.6.0           py37h04f5b5a_1000    conda-forge
natsort                   5.5.0                      py_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
netcdf4                   1.4.2           py37hd700958_1001    conda-forge
networkx                  2.2                        py_1    conda-forge
nodejs                    11.6.0            h0a44026_1000    conda-forge
nose                      1.3.7                 py37_1002    conda-forge
notebook                  5.7.8                    py37_0    conda-forge
numba                     0.43.1           py37h051e8ed_0    conda-forge
numexpr                   2.6.9           py37h1702cab_1000    conda-forge
numpy                     1.16.3           py37hdf140aa_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.5             hdc02c5d_1000    conda-forge
openssl                   1.1.1b               h01d97ff_2    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.24.2           py37h0a44026_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
periodictable             1.5.0                    pypi_0    pypi
pexpect                   4.6.0                 py37_1000    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pillow                    5.4.1           py37hbddbef0_1000    conda-forge
pint                      0.9                      py37_2    conda-forge
pip                       18.1                  py37_1000    conda-forge
pluggy                    0.11.0                     py_0    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
psutil                    5.4.8           py37h1de35cc_1000    conda-forge
ptyprocess                0.6.0                 py37_1000    conda-forge
py                        1.7.0                      py_0    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pycycle                   0.0.8                    pypi_0    pypi
pydub                     0.23.0                   pypi_0    pypi
pyface                    6.0.0                      py_1    conda-forge
pyfiglet                  0.8.post1                pypi_0    pypi
pygments                  2.3.1                      py_0    conda-forge
pylint                    2.2.2                 py37_1000    conda-forge
pyopenssl                 18.0.0                py37_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyqt                      5.6.0           py37hc26a216_1008    conda-forge
pyrsistent                0.14.9          py37h1de35cc_1000    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
pytest                    4.5.0                    py37_0    conda-forge
pytest-remotedata         0.3.1                    pypi_0    pypi
python                    3.7.2                haf84260_0    defaults
python-blosc              1.8.1            py37h0a44026_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pythreejs                 2.0.2                 py37_1000    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1           py37h917ab60_1000    conda-forge
pyyaml                    3.13            py37h1de35cc_1001    conda-forge
pyzmq                     17.1.2          py37h111632d_1001    conda-forge
qt                        5.6.2             h822fa55_1011    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
readline                  7.0               hcfe32e1_1001    conda-forge
requests                  2.21.0                py37_1000    conda-forge
scikit-image              0.14.1          py37h0a44026_1004    conda-forge
scikit-learn              0.20.3           py37hca23c92_1    conda-forge
scipy                     1.2.1            py37hbd7caa9_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py37_0    conda-forge
shellingham               1.3.1                    pypi_0    pypi
sim                       0.1                       dev_0    <develop>
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1          py37h0a44026_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sparse                    0.6.0                      py_0    conda-forge
sphinx                    2.0.1                      py_0    conda-forge
sphinx-rtd-theme          0.4.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlalchemy                1.2.18                   pypi_0    pypi
sqlite                    3.26.0            h1765d9f_1000    conda-forge
statsmodels               0.9.0           py37h917ab60_1000    conda-forge
sympy                     1.3                   py37_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                 py37_1001    conda-forge
testpath                  0.4.2                 py37_1000    conda-forge
tk                        8.6.9             ha441bb4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py37h1de35cc_1000    conda-forge
tqdm                      4.30.0                     py_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
traits                    5.1.1            py37h01d97ff_0    conda-forge
traitsui                  6.0.0                      py_1    conda-forge
traittypes                0.2.1                      py_1    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
wrapt                     1.11.0          py37h1de35cc_1000    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.1.7             h1de35cc_1001    conda-forge
zeromq                    4.2.5             h0a44026_1006    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h1de35cc_1004    conda-forge
```
</p></details>

**Comment by msarahan** [comment]
Need more info. Please fill out the rest of the issue template

**Comment by thomasaarholt** [comment]
Apologies, no idea how I missed that. Information has been added.

**Comment by soapy1** [comment]
I wonder if the right python is getting run? when you are in the environment and you have this issue, what is the output of `which -a python`

**Comment by thomasaarholt** [comment]
Looks correct:
```
which -a python
/Users/thomas/miniconda3/envs/py37/bin/python
/Users/thomas/miniconda3/bin/python
/Users/thomas/miniconda3/bin/python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python
/usr/local/bin/python
/usr/local/bin/python
/usr/bin/python
```

**Comment by thomasaarholt** [comment]
A `conda update --all` appears to have fixed the problem, although I'm not sure how, since the packages in question (in addition to `dask`, `dill`, `pytest`, `traits` and `pint` had the same problem) did *not* receive updated.
