### ISSUE TITLE
One more error creating a new environment

### ISSUE THREAD

**Issue by danmoser** [conda/conda#8728]
## Current Behavior

Error creating a new environment.

### Steps to Reproduce

```
conda create -n iraf27 python=2.7 iraf-all pyraf-all stsci
```

## Expected Behavior

Creation of the new environment

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
    Traceback (most recent call last):
      File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/main.py", line 92, in _main
        p, sub_parsers = generate_parser()
      File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/main.py", line 51, in generate_parser
        from ..cli import conda_argparse
      File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 14, in <module>
        from .common import add_parser_help
      File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/common.py", line 21, in <module>
        from ..resolve import MatchSpec
      File "/home/moser/.local/lib/python2.7/site-packages/conda/resolve.py", line 12, in <module>
        from .logic import Clauses, minimal_unsatisfiable_subset
      File "/home/moser/.local/lib/python2.7/site-packages/conda/logic.py", line 32, in <module>
        import pycosat
    ImportError: /home/moser/.local/lib/python2.7/site-packages/pycosat.so: wrong ELF class: ELFCLASS64
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
Traceback (most recent call last):
  File "./conda", line 11, in <module>
    sys.exit(main())
  File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 537, in get_info
    from conda.cli import conda_argparse
  File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 14, in <module>
    from .common import add_parser_help
  File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/common.py", line 21, in <module>
    from ..resolve import MatchSpec
  File "/home/moser/.local/lib/python2.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "/home/moser/.local/lib/python2.7/site-packages/conda/logic.py", line 32, in <module>
    import pycosat
ImportError: /home/moser/.local/lib/python2.7/site-packages/pycosat.so: wrong ELF class: ELFCLASS64
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
Traceback (most recent call last):
  File "./conda", line 11, in <module>
    sys.exit(main())
  File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home/moser/.local/lib/python2.7/site-packages/conda/exceptions.py", line 537, in get_info
    from conda.cli import conda_argparse
  File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 14, in <module>
    from .common import add_parser_help
  File "/home/moser/.local/lib/python2.7/site-packages/conda/cli/common.py", line 21, in <module>
    from ..resolve import MatchSpec
  File "/home/moser/.local/lib/python2.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "/home/moser/.local/lib/python2.7/site-packages/conda/logic.py", line 32, in <module>
    import pycosat
ImportError: /home/moser/.local/lib/python2.7/site-packages/pycosat.so: wrong ELF class: ELFCLASS64
```
</p></details>

**Comment by jjhelmus** [comment]
The backtrace indicates that pycosat is installed in the .local directory, this is not the typical location of this library..  Did you happen to perform a user install of pycosat (`pip install --user pycosat`)?  Removing that file (or even the entire .local directory) may fix this issue.

**Comment by msarahan** [comment]
probably related to https://github.com/ContinuumIO/pycosat/issues/34

**Comment by danmoser** [comment]
Thanks Mike and _jjhelmus_!! Indeed, removing the file solved the issue!
