### ISSUE TITLE
[4.7.3] Not backward-compatible with internal repos

### ISSUE THREAD

**Issue by dhirschfeld** [conda/conda#8803]
Having upgraded to 4.7.3 `conda` can no longer pull packages from our internal repo:

![image](https://user-images.githubusercontent.com/881019/59843497-0768ca00-939c-11e9-88d9-6185dacf7b76.png)

Our internal repo has `repodata.json` and `repodata2.json` but no `current_repodata.json`.

It would be nice if the newer conda would fall back to using one of the older formats if `current_repodata.json` didn't exist.

**Comment by dhirschfeld** [comment]
I guess I just need to re-index with a newer conda-build? I'm hesitant to do so as I need the repo to also work for conda 4.6.8 - it's only the dev environment where I'm testing out the latest conda.

**Comment by dhirschfeld** [comment]
Turns out indexing with the latest conda/build had some nasty issues:
```
> conda index
Subdir: linux-64:   0%|                                                                                                                                      | 0/3 [00:00<?, ?it/s]
Gathering repodata:   0%|                                                                                                                                    | 0/9 [00:00<?, ?it/s]
File format::   0%|                                                                                                                                          | 0/2 [00:00<?, ?it/s]
hash & extract packages for linux-64:   0%|                                                                                                                  | 0/3 [00:00<?, ?it/s]Exception in thread QueueManagerThread:
Traceback (most recent call last):
  File "C:\Miniconda3\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Miniconda3\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Miniconda3\lib\concurrent\futures\process.py", line 354, in _queue_management_worker
    ready = wait(readers + worker_sentinels)
  File "C:\Miniconda3\lib\multiprocessing\connection.py", line 868, in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\Miniconda3\lib\multiprocessing\connection.py", line 800, in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
ValueError: need at most 63 handles, got a sequence of length 65
```
```
> conda list conda*
# packages in environment at C:\Miniconda3:
#
# Name                    Version                   Build  Channel
conda                     4.7.4                    py37_0    https://conda.anaconda.org/conda-canary
conda-build               3.18.2                   py37_0    https://conda.anaconda.org/conda-forge
conda-env                 2.6.0                         1
conda-package-handling    1.3.9                    py37_0    https://conda.anaconda.org/conda-forge
```

**Comment by dhirschfeld** [comment]
***Update:*** The conda index error isn't (necessarily) a conda problem but comes down to the fact that multiprocessing is *broken* on my VM. `os.cpu_count()` returns 64 when in fact there are only 4 vCPUs. I suspect that this is the crux of the problem with conda index.

**Comment by msarahan** [comment]
That's not the intended behavior. It should be falling back. The number of CPUs problem is solvable in the next conda bill he, with a cli argument to limit the number of processes.

**Comment by dhirschfeld** [comment]
The conda index issue is less of a concern because the underlying issue is my broken environment.

I'm a lot more concerned about conda not falling back as that will cause upgrade headaches if it's not resolved before it hits defaults.

**Comment by msarahan** [comment]
There is absolutely a fallback.  Here's what I see with a test for a JSON file that does not exist:

```
Collecting package metadata (nihilism.json): ...working... DEBUG conda.core.package_cache_data:_check_writable(261): package cache directory '/home/msarahan/code/conda/devenv/pkgs' writable: True
DEBUG conda.core.subdir_data:_load(186): No local cache found for https://repo.anaconda.com/pkgs/main/noarch/nihilism.json at /home/msarahan/code/conda/devenv/pkgs/cache/66127c21.json
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(471): 
>>GET /pkgs/main/noarch/nihilism.json HTTPS
> User-Agent: conda/4.7.4 requests/2.21.0 CPython/3.7.3 Linux/4.18.0-21-generic ubuntu/18.04.2 glibc/2.27
> Accept: */*
> Accept-Encoding: gzip, deflate, compress, identity
> Connection: keep-alive
> Content-Type: application/json

<<HTTPS 404 Not Found
< Cache-Control: public, max-age=30
< CF-Cache-Status: MISS
< CF-RAY: 4e9e50c70c099b00-DFW
< Content-Encoding: gzip
< Content-Type: text/html; charset=utf-8
< Date: Thu, 20 Jun 2019 14:08:34 GMT
< Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< Expires: Thu, 20 Jun 2019 14:09:04 GMT
< Server: cloudflare
< Set-Cookie: __cfduid=d6082cfeb287302d2578378865050d7531561039714; expires=Fri, 19-Jun-20 14:08:34 GMT; path=/; domain=.anaconda.com; HttpOnly; Secure
< Transfer-Encoding: chunked
< Vary: Accept-Encoding
< x-amz-id-2: 9o/lAnwhLc9J1wZ03jFrVr7WCr5AmOBULV5eTlJ690sMbCq45FCQH/lZYxtz5JqMxT23SiJvOKo=
< x-amz-request-id: D2025325B9EAC76E
< Connection: keep-alive
< Elapsed: 00:00.259269

<html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: pkgs/main/noarch/nihilism.json</li>
<li>RequestId: D2025325B9EAC76E</li>
<li>HostId: 9

DEBUG conda.core.subdir_data:_load(225): Local cache timed out for https://repo.anaconda.com/pkgs/main/noarch/repodata.json at /home/msarahan/code/conda/devenv/pkgs/cache/b63425f9.json
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(471): 
>>GET /pkgs/main/noarch/repodata.json HTTPS
```

The fallback happens in one of two places:
* https://github.com/conda/conda/blob/master/conda/cli/install.py#L249-L304
* https://github.com/conda/conda/blob/master/conda/core/subdir_data.py#L227-L241

I believe the latter is what should be handling your case.  Can you please provide more information from the error, to help identify what's going wrong here?

**Comment by msarahan** [comment]
FWIW, I tried reproducing this with a local repo, too, by just manually removing the current_repodata.json file and clearing my cache with ``conda clean -iy``

```
DEBUG conda.core.subdir_data:_load(186): No local cache found for file:///home/msarahan/code/conda/devenv/conda-bld/linux-64/current_repodata.json at /home/msarahan/code/conda/devenv/pkgs/cache/64ac5e7c.json
INFO conda._vendor.auxlib.logz:stringify(144): request is 'None' for Response object with url file:///home/msarahan/code/conda/devenv/conda-bld/linux-64/current_repodata.json
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(471): 
<<FILE 404 None
< Elapsed: 00:00.000051


INFO conda.core.subdir_data:fetch_repodata_remote_request(495): Unable to retrieve repodata (404 error) for file:///home/msarahan/code/conda/devenv/conda-bld/linux-64/current_repodata.json
DEBUG conda.core.subdir_data:_load(225): Local cache timed out for file:///home/msarahan/code/conda/devenv/conda-bld/linux-64/repodata.json at /home/msarahan/code/conda/devenv/pkgs/cache/4fa057de.json
INFO conda._vendor.auxlib.logz:stringify(144): request is 'None' for Response object with url file:///home/msarahan/code/conda/devenv/conda-bld/linux-64/repodata.json
```

The fallback appears to be working for me, and I'm really confused on what you're seeing.

**Comment by msarahan** [comment]
same thing on windows...

```
INFO conda._vendor.auxlib.logz:stringify(144): request is 'None' for Response object with url file:///C:/Users/msara/Miniconda3/conda-bld/win-64/current_repodata.json
DEBUG conda.core.subdir_data:fetch_repodata_remote_request(471):
<<FILE 404 None
< Elapsed: 00:00.000801


INFO conda.core.subdir_data:fetch_repodata_remote_request(495): Unable to retrieve repodata (404 error) for file:///C:/Users/msara/Miniconda3/conda-bld/win-64/current_repodata.json
DEBUG conda.core.subdir_data:_load(225): Local cache timed out for file:///C:/Users/msara/Miniconda3/conda-bld/win-64/repodata.json at C:\Users\msara\Miniconda3\pkgs\cache\f59820ed.json
INFO conda._vendor.auxlib.logz:stringify(144): request is 'None' for Response object with url file:///C:/Users/msara/Miniconda3/conda-bld/win-64/repodata.json
```

**Comment by dhirschfeld** [comment]
Thanks for checking - you're correct and conda does seem to be doing the right thing.

I was trying to debug an issue in our CI without proper access to the output logs and the `404 error` jumped out at me. Combined with the fact that the CI was hanging I just jumped to conclusions.

With the right level of verbosity you can see that it's an `INFO` message rather than an actual error, but without that you just see a message with the alarming `404 error` in it. I tend to grep the logs for the word `error` when debugging. Obviously increasing the verbosity so that I could tell it was an `INFO` message would have been sensible but perhaps not using the word `error` in an expected informational message would also help eliminate false positives.
https://github.com/conda/conda/blob/f65d3a1bb12287e5ec005411e1fabd24b378087e/conda/core/subdir_data.py#L494-L495

As it turns out, the CI was hanging because the `always_yes` flag wasn't set and it was hard to debug because the *"Do you want to continue?"* prompt wasn't being displayed.

Sorry for the noise...
