### ISSUE TITLE
Failed to conda install if channel URL doesn't contain path segment /

### ISSUE THREAD

**Issue by twinssbc** [conda/conda#8811]
## Current Behavior
I have set up a custom channel. 
If the channel URL just contains the hostname without path segment, when doing 'conda install', for example, 
```
conda install --override-channels -c http://47.97.207.86:8023 beautifulsoup4
```
It fails with below error.
If I configure the channel URL to contain more levels, for example, http://47.97.207.86:8023/pkgs/main, it doesn't report such error.
I did some debugging, see the **Troubleshooting** section below

> 
>     Traceback (most recent call last):
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\exceptions.py", line 1003, in __call__
>         return func(*args, **kwargs)
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
>         exit_code = do_call(args, p)
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
>         exit_code = getattr(module, func_name)(args, parser)
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
>         install(args, parser, 'install')
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\cli\install.py", line 275, in install
>         handle_txn(unlink_link_transaction, prefix, args, newenv)
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\cli\install.py", line 291, in handle_txn
>         unlink_link_transaction.print_transaction_summary()
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\core\link.py", line 826, in print_transaction_summary
>         change_report_str = self._change_report_str(change_report)
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\core\link.py", line 952, in _change_report_str
>         left_str, right_str = diff_strs(unlink_prec, link_prec)
>       File "C:\Users\bocon\Anaconda3\lib\site-packages\conda\core\link.py", line 909, in diff_strs
>         return ''.join(builder_left), ''.join(builder_right)
>     TypeError: sequence item 0: expected str instance, NoneType found
> 

### Steps to Reproduce

1. Set up a custom channel without extra path segment /, for example, http://47.97.207.86:8023
2. Run conda install
```
conda install --override-channels -c http://47.97.207.86:8023 beautifulsoup4
```

### Troubleshooting
In link.py, I added some lines to try to print out the value inside builder_left and builder_right
``` 
            return ''.join(builder_left), ''.join(builder_right)
```
It turns out builder_right contains a single element 'NoneType'.
This value comes from link_prec.channel.name, which is None.
If I run conda search on the different channel URLs, I can see the Channel column is None if the URL doesn't contain path segment. So I suspect the channel name is deduced from the channel URL. I think the link.py should be able to handle such edge case.
```
(base) C:\Users\bocon>conda search --override-channels -c http://47.97.207.86:8023 beautifulsoup4
Loading channels: done
# Name                       Version           Build  Channel
beautifulsoup4                 4.7.1          py37_1  None

(base) C:\Users\bocon>conda search --override-channels -c http://47.97.207.86:8020/pkgs/main beautifulsoup4
Loading channels: done
# Name                       Version           Build  Channel
beautifulsoup4                 4.7.1          py37_1  pkgs/main
```

### Expected Behavior
It should work with channel URL no matter the URL contains extra path segment or not.

## Environment Information
<code>`conda info`</code>
```
     active environment : base
    active env location : C:\Users\bocon\Anaconda3
            shell level : 1
       user config file : C:\Users\bocon\.condarc
 populated config files : C:\Users\bocon\.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\bocon\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\bocon\Anaconda3\pkgs
                          C:\Users\bocon\.conda\pkgs
                          C:\Users\bocon\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\bocon\Anaconda3\envs
                          C:\Users\bocon\.conda\envs
                          C:\Users\bocon\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

<code>`conda config --show-sources`</code>
```
==> C:\Users\bocon\.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<code>`conda list --show-channel-urls`</code>
```
# packages in environment at C:\Users\bocon\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_tflow_select             2.3.0                       mkl    defaults
absl-py                   0.7.1                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astor                     0.7.1                    py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.1.2            py37he774522_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.8.3            py37hfa6e2cd_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.15.0               h7bd577a_0    defaults
bokeh                     1.0.4                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h452e1ab_1    defaults
bzip2                     1.0.6                hfa6e2cd_5    defaults
ca-certificates           2019.5.15                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.2           py37h7a1dbc1_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
cloudpickle               0.8.0                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
comtypes                  1.1.7                    py37_0    defaults
conda                     4.6.14                   py37_0    defaults
conda-build               3.17.8                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-verify              3.1.1                    py37_0    defaults
console_shortcut          0.1.1                         3    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.6.1            py37h7a1dbc1_0    defaults
curl                      7.64.0               h2a8f88b_2    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.6           py37ha925a31_0    defaults
cytoolz                   0.9.0.1          py37hfa6e2cd_1    defaults
dask                      1.1.4                    py37_1    defaults
dask-core                 1.1.4                    py37_1    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.5.0                    py37_1    defaults
distributed               1.26.0                   py37_1    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
fastcache                 1.0.2            py37hfa6e2cd_2    defaults
filelock                  3.0.10                   py37_0    defaults
flask                     1.0.2                    py37_1    defaults
freetype                  2.9.1                ha9979f8_1    defaults
future                    0.17.1                   py37_0    defaults
gast                      0.2.2                    py37_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.4.0            py37he774522_0    defaults
glob2                     0.6                      py37_1    defaults
greenlet                  0.4.15           py37hfa6e2cd_0    defaults
grpcio                    1.16.1           py37h351948d_1    defaults
h5py                      2.9.0            py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.8                      py37_0    defaults
intel-openmp              2019.3                      203    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.4.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
isort                     4.3.16                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.35.4           py37hf63ae98_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.0.1            py37h6538335_0    defaults
krb5                      1.16.1               hc04afaa_7    defaults
lazy-object-proxy         1.3.1            py37hfa6e2cd_2    defaults
libarchive                3.3.3                h0643e63_5    defaults
libcurl                   7.64.0               h2a8f88b_2    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.9.0                ha925a31_2    defaults
libmklml                  2019.0.3                      0    defaults
libpng                    1.6.36               h2a8f88b_0    defaults
libprotobuf               3.8.0                h7bd577a_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.0                h7a1dbc1_4    defaults
libtiff                   4.0.10               hb898794_2    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
libxslt                   1.1.33               h579f668_0    defaults
llvmlite                  0.28.0           py37ha925a31_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.3.2            py37h1350720_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markdown                  3.1.1                    py37_0    defaults
markupsafe                1.1.1            py37he774522_0    defaults
matplotlib                3.0.3            py37hc8f65d3_0    defaults
mccabe                    0.6.1                    py37_1    defaults
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2019.3                      203    defaults
mkl-service               1.1.2            py37hb782905_5    defaults
mkl_fft                   1.0.10           py37h14836fe_0    defaults
mkl_random                1.0.2            py37h343c172_0    defaults
mock                      3.0.5                    py37_0    defaults
more-itertools            6.0.0                    py37_0    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37h74a9793_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.4.1                    py37_3    defaults
nbformat                  4.4.0                    py37_0    defaults
networkx                  2.2                      py37_1    defaults
nltk                      3.4                      py37_1    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.7.8                    py37_0    defaults
numba                     0.43.1           py37hf9181ef_0    defaults
numexpr                   2.6.9            py37hdce8814_0    defaults
numpy                     1.16.2           py37h19fb1c0_0    defaults
numpy-base                1.16.2           py37hc3f5095_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  2.6.1                    py37_1    defaults
openssl                   1.1.1                he774522_0    defaults
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37ha925a31_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.4                    py37_0    defaults
partd                     0.3.10                   py37_1    defaults
path.py                   11.5.0                   py37_0    defaults
pathlib2                  2.3.3                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pep8                      1.7.1                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    5.4.1            py37hdc69c19_0    defaults
pip                       19.0.3                   py37_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.9.0                    py37_0    defaults
ply                       3.11                     py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
protobuf                  3.8.0            py37h33f27b4_0    defaults
psutil                    5.6.1            py37he774522_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37ha925a31_2    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37hfa6e2cd_9    defaults
pycurl                    7.43.0.2         py37h7a1dbc1_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyodbc                    4.0.26           py37ha925a31_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.3.1                    py37_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyreadline                2.1                      py37_1    defaults
pyrsistent                0.14.11          py37he774522_0    defaults
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.5.1            py37h1da0976_0    defaults
pytest                    4.3.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.3                h8c8aaf0_0    defaults
python-dateutil           2.8.0                    py37_0    defaults
python-libarchive-c       2.8                      py37_6    defaults
pytz                      2018.9                   py37_0    defaults
pywavelets                1.0.2            py37h8c2d366_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
pywinpty                  0.5.5                 py37_1000    defaults
pyyaml                    5.1              py37he774522_0    defaults
pyzmq                     18.0.0           py37ha925a31_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.4.3                    py37_0    defaults
qtpy                      1.7.0                    py37_1    defaults
requests                  2.21.0                   py37_0    defaults
rope                      0.12.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
scikit-image              0.14.2           py37ha925a31_0    defaults
scikit-learn              0.20.3           py37h343c172_0    defaults
scipy                     1.2.1            py37h29ff71c_0    defaults
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                40.8.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
sphinx                    1.8.5                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.3                    py37_0    defaults
spyder-kernels            0.4.2                    py37_0    defaults
sqlalchemy                1.3.1            py37he774522_0    defaults
sqlite                    3.27.2               he774522_0    defaults
statsmodels               0.9.0            py37h452e1ab_0    defaults
sympy                     1.3                      py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
tensorboard               1.13.1           py37h33f27b4_0    defaults
tensorflow                1.13.1          mkl_py37h9463c59_0    defaults
tensorflow-base           1.13.1          mkl_py37hcaf7020_0    defaults
tensorflow-estimator      1.13.0                     py_0    defaults
termcolor                 1.1.0                    py37_1    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   6.0.2            py37he774522_0    defaults
tqdm                      4.31.1                   py37_1    defaults
traitlets                 4.3.2                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
urllib3                   1.24.1                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.33.1                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
win_unicode_console       0.5                      py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.1           py37he774522_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.5                    py37_0    defaults
xlwings                   0.15.4                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zict                      0.1.4                    py37_0    defaults
zipp                      0.3.3                    py37_1    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults
```
</p></details>

**Comment by msarahan** [comment]
While I agree with you that this is a bug, it is not important enough for us to spend time on fixing it.  We would welcome a PR if you have time.

**Comment by twinssbc** [comment]
Sure. I will try to submit a PR.
