### ISSUE TITLE
Navigator Error

### ISSUE THREAD

**Issue by benmuzekari** [conda/conda#8818]
I cannot open anaconda. When i try, it leads me to this google page:
An unexpected error occurred on Navigator start-up

Report
Please report this issue in the anaconda issue tracker

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 151, in start_app
    window = run_app(splash)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/app/start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/widgets/main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "/anaconda3/lib/python3.7/site-packages/anaconda_navigator/api/conda_api.py", line 353, in __init__
    self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
  File "/anaconda3/lib/python3.7/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by msarahan** [comment]
Navigator errors belong on https://github.com/continuumio/anaconda-issues
