### ISSUE TITLE
Erroneous conda-build warning

### ISSUE THREAD

**Issue by fonnesbeck** [conda/conda#8832]
When trying to update packages using conda 4.7.5 (macOS) I get the following warning:

```
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
```

however, when I try to uninstall `conda-build` it shows it as not being installed:

```
PackagesNotFoundError: The following packages are missing from the target environment:
  - conda-build
```

**Comment by fonnesbeck** [comment]
Additionally, going ahead and installing `conda-build` (presumably to the latest version) does not make the warning go away.

**Comment by fonnesbeck** [comment]
I'm going to assume my env is hosed and start from scratch.

**Comment by fonnesbeck** [comment]
I can also confirm that this occurs also on Linux with a clean install of Anaconda 3.

**Comment by msarahan** [comment]
Thanks, we'll try to reproduce this.

**Comment by msarahan** [comment]
This worked fine for me on linux-64:

1. install anaconda from https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
2. update conda: `conda update conda`
3. `conda install hdf5` - see the warning
4. `conda update conda-build` (conda-build is part of anaconda since 2018.12, IIRC)
5. `conda install hdf5` - warning is gone

**Comment by msarahan** [comment]
If you continue to see problems, please post your output from `conda list`, as requested in the issue template.

**Comment by fonnesbeck** [comment]
Those steps solved the problem. Thanks.

**Comment by izm** [comment]
`conda update conda-build` _outside_ of any environment worked for me.  Thanks!

**Comment by motazalfarraj** [comment]
> This worked fine for me on linux-64:
> 
>     1. install anaconda from https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh
> 
>     2. update conda: `conda update conda`
> 
>     3. `conda install hdf5` - see the warning
> 
>     4. `conda update conda-build` (conda-build is part of anaconda since 2018.12, IIRC)
> 
>     5. `conda install hdf5` - warning is gone

This worked for me

**Comment by Mike76b** [comment]
On Windows 10, with:

conda version : 4.7.5
conda-build version : 3.17.8
python version : 3.7.1.final.0

Either if I type `conda update conda-build` or `conda update bokeh`, I'm getting the following:

```(base) C:\Users\Mike>conda update bokeh
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the 
old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or 
remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: /
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - defaults/win-64::anaconda==custom=py37_0
done

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 252, in _topo_sort_handle_cycles
        value = next(t)
      File "D:\ProgramData\Anaconda3\lib\site-packages\conda\models\prefix_graph.py", line 230, in _toposort_raise_on_cycles
        raise CyclicalDependencyError(tuple(graph))
    conda.exceptions.CyclicalDependencyError: Cyclic dependencies exist among these items:
      - defaults::_anaconda_depends-2019.03-py37_0
      - defaults::_ipyw_jlab_nb_ext_conf-0.1.0-py37_0
      - defaults::anaconda-custom-py37_0
      - defaults::anaconda-client-1.7.2-py37_0
      - defaults::anaconda-navigator-1.9.6-py37_0
      - defaults::anaconda-project-0.8.3-py_0
      - defaults::astropy-3.2.1-py37he774522_0
      - defaults::babel-2.7.0-py_0
      - defaults::backports-1.0-py_2
      - defaults::backports.os-0.1.1-py37_0
      - defaults::backports.shutil_get_terminal_size-1.0.0-py37_2
      - defaults::bkcharts-0.2-py37_0
      - defaults::bleach-3.1.0-py37_0
      - defaults::bokeh-1.2.0-py37_0
      - defaults::bottleneck-1.2.1-py37h452e1ab_1
      - defaults::cffi-1.12.3-py37h7a1dbc1_0
      - defaults::cloudpickle-1.2.1-py_0
      - defaults::conda-4.7.5-py37_0
      - defaults::conda-build-3.17.8-py37_0
      - defaults::conda-package-handling-1.3.11-py37_0
      - defaults::conda-verify-3.1.1-py37_0
      - defaults::cryptography-2.7-py37h7a1dbc1_0
...
```

And my `conda list` is:


```(base) C:\Users\Mike>conda list
# packages in environment at D:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                     py_0    conda-forge
altgraph                  0.16.1                   pypi_0    pypi
anaconda                  custom                   py37_0
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.6                    py37_0
anaconda-project          0.8.2                      py_1    conda-forge
appdirs                   1.4.3                    pypi_0    pypi
asn1crypto                0.24.0                   py37_0
astroid                   2.1.0                    py37_0
astropy                   3.1.1            py37he774522_0
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     18.2.0                     py_0    conda-forge
auto-py-to-exe            2.5.3                    pypi_0    pypi
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.7.1                    py37_1
bitarray                  0.8.3            py37hfa6e2cd_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
blaze                     0.11.3                   py37_0
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.14.4               he51fdeb_0
bokeh                     1.0.4                    py37_0
boto                      2.49.0                     py_0    conda-forge
boto3                     1.9.82                     py_0
botocore                  1.12.101                   py_0    conda-forge
bottle                    0.12.16                  pypi_0    pypi
bottleneck                1.2.1            py37h452e1ab_1
bs4                       0.0.1                    pypi_0    pypi
bz2file                   0.98                       py_0    conda-forge
bzip2                     1.0.6                hfa6e2cd_5
ca-certificates           2019.5.15                     0
certifi                   2019.6.16                py37_0
cffi                      1.11.5           py37h74b6da3_1
chardet                   3.0.4                    py37_1
click                     7.0                        py_0    conda-forge
cloudpickle               0.8.0                      py_0    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.1                    pypi_0    pypi
comtypes                  1.1.7                    py37_0
conda                     4.7.5                    py37_0
conda-build               3.17.8                   py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.3.10                   py37_0
conda-verify              3.1.1                    py37_0
console_shortcut          0.1.1                         3
contextlib2               0.5.5                      py_2    conda-forge
cryptography              2.5              py37h7a1dbc1_0
cssselect                 1.0.3                    pypi_0    pypi
cudatoolkit               9.0                           1
curl                      7.63.0            h2a8f88b_1000
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.5           py37ha925a31_0
cytoolz                   0.9.0.1          py37hfa6e2cd_1
dask                      1.1.1                      py_0    conda-forge
dask-core                 1.1.1                      py_0    conda-forge
datashape                 0.5.4                    py37_1
decorator                 4.3.2                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
distributed               1.25.3                   py37_0
docutils                  0.14                     py37_0
entrypoints               0.3                      py37_0
et_xmlfile                1.0.1                    py37_0
fake-useragent            0.1.11                   pypi_0    pypi
fastcache                 1.0.2            py37hfa6e2cd_2
filelock                  3.0.10                     py_0    conda-forge
flask                     1.0.2                      py_2    conda-forge
flask-cors                3.0.7                      py_0    conda-forge
freetype                  2.9.1                ha9979f8_1
future                    0.17.1                   py37_0
gensim                    3.4.0            py37hfa6e2cd_0
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.4.0            py37he774522_0
gevent-websocket          0.10.1                   pypi_0    pypi
glew                      2.0.0             he025d50_1002    conda-forge
glob2                     0.6                        py_0    conda-forge
greenlet                  0.4.15           py37hfa6e2cd_0
h5py                      2.8.0            py37h3bdd7fb_2
hdf5                      1.10.2               hac2f561_1
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                      py_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py37_0
imageio                   2.4.1                    py37_0
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.7                      py37_0
intel-openmp              2019.1                      144
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.2.0            py37h39e3cac_0
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                    py37_0
itsdangerous              1.1.0                      py_0    conda-forge
jdcal                     1.4                        py_1    conda-forge
jedi                      0.13.2                   py37_0
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9b                   hb83a4c4_2
jsonschema                2.6.0                    py37_0
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.3                   py37_0
jupyterlab_server         0.2.0                      py_0    conda-forge
keyring                   18.0.0                   py37_0
kiwisolver                1.0.1            py37h6538335_0
krb5                      1.16.1               hc04afaa_7
lazy-object-proxy         1.3.1            py37hfa6e2cd_2
libarchive                3.3.3                h0643e63_5
libcurl                   7.63.0            h2a8f88b_1000
libiconv                  1.15                 h1df5818_7
liblief                   0.9.0                ha925a31_2
libpng                    1.6.35               h2a8f88b_0
libsodium                 1.0.16               h9d3ae62_0
libssh2                   1.8.0                h7a1dbc1_4
libtiff                   4.0.9                h36446d0_2
libxml2                   2.9.8                hadb2253_1
libxslt                   1.1.32               hf6f1972_0
llvmlite                  0.27.0           py37ha925a31_0
locket                    0.2.0                      py_2    conda-forge
lxml                      4.3.0            py37h1350720_0
lz4-c                     1.8.1.2              h2fa13f4_0
lzo                       2.10                 h6df0209_2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
macholib                  1.11                     pypi_0    pypi
markupsafe                1.1.0            py37he774522_0
matplotlib                3.0.2            py37hc8f65d3_0
mccabe                    0.6.1                      py_1    conda-forge
menuinst                  1.4.14           py37hfa6e2cd_0
mistune                   0.8.4            py37he774522_0
mkl                       2019.1                      144
mkl-service               1.1.2            py37hb782905_5
mkl_fft                   1.0.10           py37h14836fe_0
mkl_random                1.0.2            py37h343c172_0
more-itertools            5.0.0                    py37_0
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.1            py37h74a9793_1
msys2-conda-epoch         20160418                      1
multipledispatch          0.6.0                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0
nbconvert                 5.4.1                         0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.2                        py_1    conda-forge
ninja                     1.9.0            py37h74a9793_0
nltk                      3.2.5                      py_0    conda-forge
nose                      1.3.7                    py37_2
notebook                  5.7.4                    py37_0
numba                     0.42.0           py37hf9181ef_0
numexpr                   2.6.9            py37hdce8814_0
numpy                     1.15.4           py37h19fb1c0_0
numpy-base                1.15.4           py37hc3f5095_0
numpydoc                  0.8.0                      py_1    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openpyxl                  2.6.0                      py_0    conda-forge
openssl                   1.1.1c               he774522_1
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.1           py37ha925a31_0
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2                      py_1    conda-forge
parse                     1.12.0                   pypi_0    pypi
parso                     0.3.4                      py_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
path.py                   11.5.0                     py_0    conda-forge
pathlib2                  2.3.3                    py37_0
patsy                     0.5.1                      py_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pickleshare               0.7.5                    py37_0
pillow                    5.4.1            py37hdc69c19_0
pip                       19.0.1                   py37_0
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.9.0                      py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
psutil                    5.5.0            py37he774522_0
py                        1.8.0                      py_0    conda-forge
py-lief                   0.9.0            py37ha925a31_2
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3            py37hfa6e2cd_0
pycparser                 2.19                       py_0    conda-forge
pycrypto                  2.6.1            py37hfa6e2cd_9
pycurl                    7.43.0.2         py37h7a1dbc1_0
pyee                      6.0.0                    pypi_0    pypi
pyflakes                  2.1.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pyinstaller               3.4                      pypi_0    pypi
pyjwt                     1.7.1                      py_0    conda-forge
pylint                    2.2.2                    py37_0
pymysql                   0.9.3                    pypi_0    pypi
pyodbc                    4.0.25           py37ha925a31_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.1                      py_0    conda-forge
pyppeteer                 0.0.25                   pypi_0    pypi
pyqt                      5.9.2            py37h6538335_2
pyquery                   1.4.0                    pypi_0    pypi
pyreadline                2.1                      py37_1
pysocks                   1.6.8                    py37_0
pytables                  3.4.4            py37he6f6034_0
pytest                    4.2.0                    py37_0
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.4.0                      py_0    conda-forge
pytest-doctestplus        0.1.3                      py_0    conda-forge
pytest-openfiles          0.3.1                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.7.1                h8c8aaf0_6
python-crfsuite           0.9.6            py37h6538335_0
python-dateutil           2.8.0                      py_0    conda-forge
python-libarchive-c       2.8                      py37_6
pytorch                   1.1.0           py3.7_cuda90_cudnn7_1    pytorch
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1            py37h8c2d366_0
pywin32                   223              py37hfa6e2cd_1
pywin32-ctypes            0.2.0                    pypi_0    pypi
pywinpty                  0.5.5                 py37_1000
pyyaml                    3.13             py37hfa6e2cd_0
pyzmq                     17.1.2           py37hfa6e2cd_0
qt                        5.9.7            vc14h73c81de_0  [vc14]
qtawesome                 0.5.6              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.6.0              pyh8a2030e_0    conda-forge
requests                  2.21.0                   py37_0
requests-html             0.10.0                   pypi_0    pypi
requests-oauthlib         1.0.0                      py_1    conda-forge
rope                      0.10.7                     py_1    conda-forge
ruamel_yaml               0.15.46          py37hfa6e2cd_0
s3transfer                0.1.13                   py37_0
scikit-image              0.14.1           py37ha925a31_0
scikit-learn              0.20.2           py37h343c172_0
scipy                     1.2.1            py37h29ff71c_0
sdl2                      2.0.8             h6538335_1001    conda-forge
sdl2_image                2.0.2                         0    conda-forge
sdl2_mixer                2.0.1                h6538335_1    conda-forge
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.8.0                   py37_0
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37h6538335_0
six                       1.12.0                   py37_0
smart_open                1.8.0                      py_0    conda-forge
smpeg2                    2.0.0                h6538335_1    conda-forge
snappy                    1.1.7                h777316e_3
snowballstemmer           1.2.1                      py_1    conda-forge
sortedcollections         1.1.2                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.7.1                    py37_0
sphinx                    1.8.4                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.3                    py37_0
spyder-kernels            0.4.2                    py37_0
sqlalchemy                1.2.18           py37he774522_0
sqlite                    3.26.0               he774522_0
statsmodels               0.9.0            py37h452e1ab_0
sympy                     1.3                      py37_0
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                    py37_1
testpath                  0.4.2                    py37_0
tk                        8.6.8                hfa6e2cd_0
toolz                     0.9.0                      py_1    conda-forge
torchvision               0.3.0               py37_cu90_1    pytorch
tornado                   5.1.1            py37hfa6e2cd_0
tqdm                      4.31.1                     py_0    conda-forge
traitlets                 4.3.2                    py37_0
twython                   3.7.0                      py_0    conda-forge
typed-ast                 1.3.1            py37he774522_0
unicodecsv                0.14.1                     py_1    conda-forge
urllib3                   1.24.1                   py37_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
w3lib                     1.20.0                   pypi_0    pypi
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websockets                7.0                      pypi_0    pypi
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py37_0
whichcraft                0.5.2                    pypi_0    pypi
widgetsnbextension        3.4.2                    py37_0
win_inet_pton             1.0.1                    py37_1
win_unicode_console       0.5                      py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.11.1           py37he774522_0
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.1.5                      py_0    conda-forge
xlwings                   0.15.2                   py37_0
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.2.5                he025d50_1
zict                      0.1.3                      py_0    conda-forge
zipp                      0.3.3                      py_0    conda-forge
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```

**Comment by tymiguel** [comment]
@Mike76b the error message below is tell you that the anaconda package is causing the inconsistency. 

> WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the 
> old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or 
> remove conda-build to get smaller downloads and faster extractions.
> Collecting package metadata (repodata.json): done
> Solving environment: /
> The environment is inconsistent, please check the package plan carefully
> The following packages are causing the inconsistency:
> 
>   - defaults/win-64::anaconda==custom=py37_0

A possible solution would be to `conda install anaconda` . This should fix the issue.

**Comment by Mike76b** [comment]
Well, actually I had to run:

- `conda install anaconda`

- `conda update conda-build`

- `conda update --all`

so now I could install modules again.
