### ISSUE TITLE
After conda update conda, conda does not work

### ISSUE THREAD

**Issue by Okroshiashvili** [conda/conda#8835]
## Current Behavior

Platform: win64

After successfully doing `conda update conda`  conda environment gives me error. I want to run `conda update anaconda` but instead I have the following error:

### The Error I got

```
Traceback (most recent call last):
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_update.py", line 8, in <module>
    from .install import install
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_package_handling\api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_package_handling\tarball.py", line 7, in <module>
    import libarchive
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be str, not None
```

How can I solve this problem? Conda does not respond to any command. Running `conda info` command gives me the following:

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 426, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None

`$ C:\Users\nokroshiashvili\AppData\Local\Continuum\anaconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:




```

**Comment by dkang9503** [comment]
I am also having the same issue. I tried reinstalling conda, and it worked for a while. But after I downloaded some packages (tensorflow, keras specifically), conda started having the above issues

**Comment by msarahan** [comment]
Please see https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed

These errors indicate that Conda's dependency, libarchive, can't find its libraries.  You need to be sure to use activation, or otherwise ensure that the Library/bin folder is on PATH..

**Comment by Okroshiashvili** [comment]
@msarahan  did not find any solution in this link. What was the cause of this problem? Before running `conda update conda`  I installed [dython](https://github.com/shakedzy/dython) by running `git clone https://github.com/shakedzy/dython.git` and `pip install ./dython` in this `C:\Users\nokroshiashvili` directory. I cannot use pip as I have no admin rights for this PC. That and `conda update conda` installation was successful but after that conda does not recognize andy command and right now Anaconda Navigator does not work. I submitted issue a few minutes ago.

**Comment by codetrainee** [comment]
After update to 4.7.5, it failed. Reinstallation of conda (4.6.14) works fine.

**Comment by dkang9503** [comment]
> Please see https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed
> 
> These errors indicate that Conda's dependency, libarchive, can't find its libraries. You need to be sure to use activation, or otherwise ensure that the Library/bin folder is on PATH..

Adding Library/bin to the PATH worked for me

**Comment by Okroshiashvili** [comment]
I already have added `C:\Users\UserName\AppData\Local\Continuum\anaconda3\Library\bin` to the PATH but still getting the same errors. I have no admin rights and I added Library/bin to the environmental variable for my account.

**Comment by albertoperezposada** [comment]
I am also having the same issue. Using conda 4.7.10 on MacOS Mojave. I tried to fix it by adding the UNIX equivalent `~/anaconda3/bin` to the path and it doesn't work either.

**Comment by msarahan** [comment]
Anaconda 2019.07 was released yesterday.  It might be easier to just try to install that, because we know it has a good configuration with libarchive.

**Comment by Okroshiashvili** [comment]
I completely removed Anaconda and installed the new version. Now everything works as expected. It turned out that my case was an extreme one where I tried everything and did not work. The easiest solution in my case was to remove anaconda and install the newer version. That solved all my problem. I close that issue.

**Comment by kuriakinzeng** [comment]
I had the same problem. Adding `<path-to-Anaconda>/Library/bin` works for me.

**Comment by Walter0002** [comment]
using the command "conda.bat install packagename"

**Comment by nikhil02jk** [comment]
Add your anaconda bin path to environment variables. it worked for me.
