### ISSUE TITLE
OSError: libiconv.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by wccropper** [conda/conda#8838]
## Current Behavior

$ conda env list
Traceback (most recent call last):
  File "/data/apps/miniconda/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda_env/cli/main.py", line 39, in <module>
    from . import main_create
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 12, in <module>
    from conda.cli import install as cli_install
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory

### Steps to Reproduce

```
Run any conda commands other than activate/deactivate
```

## Expected Behavior

No errors

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/data/apps/miniconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 678, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "/data/apps/miniconda/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
        from . import ffi
      File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
        return self._dlltype(name)
      File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libiconv.so.2: cannot open shared object file: No such file or directory

`$ /data/apps/miniconda/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /data/apps/miniconda/.condarc <==
auto_update_conda: False
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
Traceback (most recent call last):
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/data/apps/miniconda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/prefix_data.py", line 24, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/gateways/disk/create.py", line 17, in <module>
    import conda_package_handling.api
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/apps/miniconda/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda_package_handling/api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "/data/apps/miniconda/lib/python3.6/site-packages/conda_package_handling/tarball.py", line 7, in <module>
    import libarchive
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/data/apps/miniconda/lib/python3.6/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "/data/apps/miniconda/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
```
</p></details>
Issue can be resolved by installing the rpm found at https://forensics.cert.org/centos/cert/7/x86_64//libiconv-1.15-1.el7.x86_64.rpm. This is not a fix. What is causing this dependency? This object is not offered by any CentOS7 packages from their repos.

**Comment by jjhelmus** [comment]
@wccropper Can you describe the steps before this error occurred? The output of `ls  /data/apps/miniconda/conda-meta` would also be helpful.

**Comment by wccropper** [comment]
Oh I'm so sorry. My first submission lost some of my info (I accidentally removed some of the code for the formatting).

This occurred after updating from 2.6.? to 2.7.5 via 'conda update -n base conda -c defaults'

```
$ ls /data/apps/miniconda/conda-meta
./                                         openssl-1.1.1-h7b6447c_0.json
../                                        pip-9.0.1-py36h6c6f9ce_4.json
asn1crypto-0.23.0-py36h4639342_0.json      pycosat-0.6.3-py36h0a5515d_0.json
bzip2-1.0.6-h14c3975_5.json                pycparser-2.18-py36hf9f622e_1.json
ca-certificates-2019.6.16-hecc5488_0.json  pyopenssl-17.5.0-py36h20ba746_0.json
certifi-2019.6.16-py36_0.json              pysocks-1.6.7-py36hd97a5b1_1.json
cffi-1.11.2-py36h2825082_0.json            python-3.6.7-h0371630_0.json
chardet-3.0.4-py36h0f667ec_1.json          python-libarchive-c-2.8-py36_6.json
conda-4.7.5-py36_0.json                    readline-7.0-ha6073c6_4.json
conda-env-2.6.0-h36134e3_1.json            requests-2.18.4-py36he2e5f8d_1.json
conda-package-handling-1.3.10-py36_0.json  ruamel_yaml-0.11.14-py36ha2fb22d_2.json
cryptography-2.3.1-py36h1ba5d50_2.json     setuptools-36.5.0-py36he42e2e1_0.json
history                                    six-1.11.0-py36h372c433_1.json
idna-2.6-py36h82fb2a8_1.json               sqlite-3.25.2-h7b6447c_0.json
libarchive-3.3.3-hb44662c_1005.json        tk-8.6.8-hbc83047_0.json
libedit-3.1.20170329-h6b74fdf_2.json       tqdm-4.32.2-py_0.json
libffi-3.2.1-hd88cf55_4.json               urllib3-1.22-py36hbe7ace6_0.json
libgcc-ng-8.2.0-hdf63c60_1.json            wheel-0.30.0-py36hfd4bba0_1.json
libstdcxx-ng-8.2.0-hdf63c60_1.json         xz-5.2.4-h14c3975_4.json
libxml2-2.9.9-hea5a465_1.json              yaml-0.1.7-had09818_2.json
lz4-c-1.8.3-he1b5a44_1001.json             zlib-1.2.11-ha838bed_2.json
lzo-2.10-h49e0be7_2.json                   zstd-1.4.0-h3b9ef0a_0.json
ncurses-6.1-hf484d3e_0.json
```

**Comment by jbelyeu** [comment]
I have a very similar error, first with this command and now with any install/uninstall:
<details>

<summary>$ conda uninstall mosdepth</summary>

 ```text
Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1043, in __call__
    return func(*args, **kwargs)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/cli/main_remove.py", line 10, in <module>
    from .install import handle_txn
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1335, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1046, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1090, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1101, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1171, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 7, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 7, in <module>
    import libarchive
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/uufs/chpc.utah.edu/common/HIPAA/u1072557/miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
  ```
</details>

**Comment by jjhelmus** [comment]
@wccropper Thanks for the details.  The issue here is that the `libarchive`, specifically `libarchive-3.3.3-hb44662c_1005` has a dependency on `libiconv` that is not declared in the package metadata.  This package comes from `conda-forge` so it will need to be addressed by that community.  I've opened an issue, conda-forge/libarchive-feedstock#35, for this bug and will work with the maintainers there to implement a fix.

**Comment by epignatelli** [comment]
In the meanwhile, what worked for me on `ubuntu`: 
- Download the `anaconda` installer for Ubuntu. I used the one I originally installed `anaconda` from: `Anaconda3-5.3.1-Linux-x86_64.sh`
- Install anaconda with `-u` option (update):
  - `cd {directory with your Anaconda-*.sh}`
- `bash Anaconda-*.sh -u`

**Comment by dswah** [comment]
I'm seeing the same error with `libiconv` after uninstalling `nb_conda_kernels` in my Miniconda.

Manually updating to the latest Miniconda didn't fix the problem.

**Comment by pzelasko** [comment]
Same error after installing [RAPIDS](https://rapids.ai/start.html#rapids-release-selector) on a fresh Miniconda installation; RAPIDS installed succesfully, but can't use `conda` afterwards.
```
conda activate
conda install -c rapidsai -c nvidia -c numba -c conda-forge -c anaconda \
    cudf=0.9 cuml=0.9 cugraph=0.9 python=3.7 anaconda::cudatoolkit=10.0
```

**Comment by valuat** [comment]
I had the same issue when installing `openslide`. This worked for me:
`conda install -c conda-forge libiconv`
