### ISSUE TITLE
AttributeError: 'module' object has no attribute 'BadZipFile'

### ISSUE THREAD

**Issue by WTarabidopsis** [conda/conda#8864]
Hi!
When I tried to install some softwares, an Errors happened and then the `conda install` seems broken.
I tried to fix this problem by `conda install -f conda`, but it doesn't help. Any ideas how  can I fix it?
Reinstall miniconda may be a simple way, but I have installed lots of softwares by `conda install`, can this problem be fixed without reinstall the miniconda? Thanks in advance.
Here is the Error information and my `conda info`
```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/cli/install.py", line 304, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/cli/install.py", line 320, in handle_txn
        unlink_link_transaction.print_transaction_summary()
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/link.py", line 869, in print_transaction_summary
        legacy_action_groups = self._make_legacy_action_groups()
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/link.py", line 853, in _make_legacy_action_groups
        self._pfe.prepare()
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 617, in prepare
        for prec in self.link_precs)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/_abcoll.py", line 571, in update
        for key, value in other:
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 617, in <genexpr>
        for prec in self.link_precs)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 509, in make_actions_for_record
        ), None)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 506, in <genexpr>
        pcrec for pcrec in concat(PackageCacheData(pkgs_dir).query(pref_or_spec)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 507, in <genexpr>
        for pkgs_dir in context.pkgs_dirs)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 132, in query
        return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 246, in _package_cache_records
        self.load()
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 98, in load
        package_cache_record = self._make_single_record(base_name)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/core/package_cache_data.py", line 339, in _make_single_record
        extract_tarball(package_tarball_full_path, extracted_package_dir)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda/gateways/disk/create.py", line 219, in extract_tarball
        conda_package_handling.api.extract(tarball_full_path, dest_dir=destination_directory)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda_package_handling/api.py", line 49, in extract
        SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda_package_handling/conda_fmt.py", line 55, in extract
        _extract_component(fn, file_id, component, dest_dir)
      File "/lustre/home/jiayuxin/miniconda3/lib/python2.7/site-packages/conda_package_handling/conda_fmt.py", line 38, in _extract_component
        except zipfile.BadZipFile as e:
    AttributeError: 'module' object has no attribute 'BadZipFile'

`$ /lustre/home/jiayuxin/miniconda3/bin/conda install genometools`

  environment variables:
     AUGUSTUS_CONFIG_PATH=/lustre/home/jiayuxin/miniconda3/config/
                 CIO_TEST=<not set>
                CLASSPATH=/usr/java/jre1.8.0_151/lib:/usr/java/jre1.8.0_151/lib:/opt/intel/compi
                          lers_and_libraries_2018.1.163/linux/mpi/intel64/lib/mpi.jar:/opt/intel
                          /compilers_and_libraries_2018.1.163/linux/mpi/intel64/lib/mpi.jar:/opt
                          /intel/compilers_and_libraries_2018.1.163/linux/daal/lib/daal.jar:.
         CONDA_BACKUP_F90=/lustre/home/jiayuxin/miniconda3/bin/x86_64-conda_cos6-linux-gnu-
                          gfortran
        CONDA_BACKUP_HOST=x86_64-conda_cos6-linux-gnu
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/lustre/home/jiayuxin/miniconda3/bin/conda
             CONDA_PREFIX=/lustre/home/jiayuxin/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/lustre/home/jiayuxin/miniconda3/bin/python
               CONDA_ROOT=/lustre/home/jiayuxin/miniconda3
              CONDA_SHLVL=1
                    CPATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/include:/opt/i
                          ntel/compilers_and_libraries_2018.1.163/linux/ipp/include:/opt/intel/c
                          ompilers_and_libraries_2018.1.163/linux/mkl/include:/opt/intel/compile
                          rs_and_libraries_2018.1.163/linux/pstl/include:/opt/intel/compilers_an
                          d_libraries_2018.1.163/linux/tbb/include:/opt/intel/compilers_and_libr
                          aries_2018.1.163/linux/tbb/include:/opt/intel/compilers_and_libraries_
                          2018.1.163/linux/daal/include
                 INFOPATH=/opt/intel/documentation_2018/en/debugger//gdb-
                          ia/info/:/opt/intel/documentation_2018/en/debugger//gdb-igfx/info/
     JAVA_LD_LIBRARY_PATH=/lustre/home/jiayuxin/miniconda3/jre/lib/amd64/server
          LD_LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/intel64/lib:/o
                          pt/intel/compilers_and_libraries_2018.1.163/linux/mpi/mic/lib:/opt/int
                          el/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel64_lin:/
                          opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin
                          :/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/inte
                          l64:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/i
                          ntel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/int
                          el64/lib:/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/mic/l
                          ib:/opt/intel/compilers_and_libraries_2018.1.163/linux/ipp/lib/intel64
                          :/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/inte
                          l64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/in
                          tel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb/lib/
                          intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.1.163/linux/tbb
                          /lib/intel64/gcc4.7:/opt/intel/debugger_2018/iga/lib:/opt/intel/debugg
                          er_2018/libipt/intel64/lib:/opt/intel/compilers_and_libraries_2018.1.1
                          63/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.
                          1.163/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/lustre/home/jiayuxin/b
                          in/gmp-6.1.0/lib:/lustre/home/jiayuxin/bin/gmp-6.1.0/include:/lustre/h
                          ome/jiayuxin/bin/gmp-6.1.0/:/lustre/home/jiayuxin/bin/mpc-1.0.3:/lustr
                          e/home/jiayuxin/bin/mpfr-3.1.4:/lustre/home/jiayuxin/miniconda3/lib/:/
                          lustre/home/jiayuxin/bin/gmp-6.1.0/lib:/lustre/home/jiayuxin/bin/gmp-6
                          .1.0/include
             LIBRARY_PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/lib/intel
                          64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/int
                          el64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/ipp/lib/i
                          ntel64:/opt/intel/compilers_and_libraries_2018.1.163/linux/compiler/li
                          b/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/
                          lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1.163/linux/tb
                          b/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.1.163/lin
                          ux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.1.16
                          3/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.1
                          .163/linux/daal/../tbb/lib/intel64_lin/gcc4.4
                  MANPATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/man:/opt/intel
                          /man/common:/opt/intel/compilers_and_libraries_2018.1.163/linux/mpi/ma
                          n:/opt/intel/documentation_2018/en/debugger//gdb-
                          ia/man/:/opt/intel/documentation_2018/en/debugger//gdb-igfx/man/:/usr/
                          local/share/man:/usr/share/man/overrides:/usr/share/man:/usr/man:
               MODULEPATH=/opt/Modules/modulefiles:/etc/modulefiles
                  NLSPATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_li
                          n/locale/%l_%t/%N:/opt/intel/compilers_and_libraries_2018.1.163/linux/
                          compiler/lib/intel64/locale/%l_%t/%N:/opt/intel/compilers_and_librarie
                          s_2018.1.163/linux/mkl/lib/intel64_lin/locale/%l_%t/%N:/opt/intel/debu
                          gger_2018/gdb/intel64/share/locale/%l_%t/%N
                     PATH=/lustre/home/jiayuxin/miniconda3/bin:/lustre/home/jiayuxin/miniconda3/
                          bin:/lustre/home/jiayuxin/miniconda3/condabin:/opt/software/gatk-4.1.2
                          .0:/opt/software/bin:/opt/software/expat-2.2.6/bin:/usr/java/jre1.8.0_
                          151/bin:/usr/java/jre1.8.0_151/bin:/opt/tsce4/maui/sbin:/opt/tsce4/mau
                          i/bin:/opt/tsce4/torque6/bin:/opt/tsce4/torque6/sbin:/usr/local/bin:/o
                          pt/software/mpich3.2.1/bin:/opt/intel/compilers_and_libraries_2018.1.1
                          63/linux/mpi/intel64/bin:/opt/intel/compilers_and_libraries_2018.1.163
                          /linux/bin/intel64:/opt/intel/compilers_and_libraries_2018.1.163/linux
                          /mpi/intel64/bin:/usr/lib64/qt-3.3/bin:/usr/local/bin:/usr/bin:/usr/lo
                          cal/sbin:/usr/sbin:.:/lustre/home/jiayuxin/.local/bin:/lustre/home/jia
                          yuxin/bin:/lustre/home/jiayuxin/1-softwares/r8s1.81/src:/lustre/home/j
                          iayuxin/1-softwares/NECAT/Linux-amd64/bin:/lustre/home/jiayuxin/1-soft
                          wares/sratoolkit.2.8.2-centos_linux64/bin:/usr/local/mysql/bin:/usr/lo
                          cal/mysql/lib
          PKG_CONFIG_PATH=/opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/bin/pkgconfig:
                          /opt/intel/compilers_and_libraries_2018.1.163/linux/mkl/bin/pkgconfig
           QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /lustre/home/jiayuxin/miniconda3
            shell level : 1
       user config file : /lustre/home/jiayuxin/.condarc
 populated config files : /lustre/home/jiayuxin/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages :
       base environment : /lustre/home/jiayuxin/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /lustre/home/jiayuxin/miniconda3/pkgs
                          /lustre/home/jiayuxin/.conda/pkgs
       envs directories : /lustre/home/jiayuxin/miniconda3/envs
                          /lustre/home/jiayuxin/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/2.7.16 Linux/3.10.0-693.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 1007:1011
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

**Comment by gmnash** [comment]
Ran into same problem.

**Comment by msarahan** [comment]
I think this is bad exception handling on our part regarding py27.  If you can switch to python 3, I recommend that.  Otherwise, we'll have to fix the issue over at conda/conda-package-handling

**Comment by WTarabidopsis** [comment]
Thanks for your reply.
I switched to python3 but it didn't work.
Finally, I reinstalled the miniconda.

**Comment by ffayton** [comment]
Shouldn't BadZipFile be BadZipfile?  https://docs.python.org/2/library/zipfile.html

**Comment by msarahan** [comment]
Changed in py3, but they kept it in for compatibility, though it is deprecated: https://docs.python.org/3.7/library/zipfile.html

**Comment by msarahan** [comment]
fixed in https://github.com/conda/conda-package-handling/pull/37, will be in conda-package-handling 1.3.11, which should be available as a package a little later today.

**Comment by kumine** [comment]
find  the file **conda_fmt.py** 
change `except zipfile.BadZipFile as e:`  to `except zipfile.error as e:`
