### ISSUE TITLE
"conda update --all" seems to be stuck in the "Generating hint" stage

### ISSUE THREAD

**Issue by tebeka** [conda/conda#889]
```
$ ~/anaconda/bin/conda update --all
Fetching package metadata: ..
Solving package specifications: ..
Error: Unsatisfiable package specifications.
Generating hint: .............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^CTraceback (most recent call last):
  File "/Users/mikitebeka/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 199, in args_func
    args.func(args, p)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/cli/main_update.py", line 40, in execute
    install.install(args, parser, 'update')
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/cli/install.py", line 314, in install
    only_names=only_names, pinned=args.pinned, minimal_hint=args.alt_hint)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/plan.py", line 400, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 688, in solve
    minimal_hint=minimal_hint)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 498, in solve2
    sys.exit(self.guess_bad_solve(specs, features))
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 560, in guess_bad_solve
    self.solve2(comb, features, guess=False, unsat_only=True)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 468, in solve2
    dists = self.get_dists(specs)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 419, in get_dists
    dists.update(self.all_deps(pkg.fn, max_only=max_only))
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 314, in all_deps
    add_dependents(root_fn, max_only=max_only)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 300, in add_dependents
    add_dependents(pkg2.fn, max_only=max_only)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 300, in add_dependents
    add_dependents(pkg2.fn, max_only=max_only)
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 293, in add_dependents
    for pkg2 in self.get_pkgs(ms, max_only=max_only):
  File "/Users/mikitebeka/anaconda/lib/python2.7/site-packages/conda/utils.py", line 90, in __call__
    def __call__(self, *args, **kw):
KeyboardInterrupt
```
(I gave up after about 12 minutes).

**Comment by asmeurer** [comment]
`conda update --all` now generates hints much more quickly.
