### ISSUE TITLE
Conda's python 2.7 breaks after giving it capabilities 

### ISSUE THREAD

**Issue by snudler6** [conda/conda#8984]
## Current Behavior

After granting some capabilities to conda's python, internal errors of python occurs -
See steps. 
I've validated everything works as expected before granting capabilities. 
What is actually happening is apparently the python in the conda env is starting the wrong python.

### Steps to Reproduce

```
$ conda create -n test
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/user/miniconda2/envs/test



Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

$ conda activate test
$ conda install python\<3
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/user/miniconda2/envs/test

  added / updated specs:
    - python[version='<3']


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |             main           3 KB
    ca-certificates-2019.5.15  |                0         133 KB
    certifi-2019.6.16          |           py27_0         154 KB
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    libstdcxx-ng-9.1.0         |       hdf63c60_0         4.0 MB
    openssl-1.1.1c             |       h7b6447c_1         3.8 MB
    pip-19.1.1                 |           py27_0         1.8 MB
    setuptools-41.0.1          |           py27_0         640 KB
    sqlite-3.29.0              |       h7b6447c_0         1.9 MB
    wheel-0.33.4               |           py27_0          39 KB
    ------------------------------------------------------------
                                           Total:        20.6 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.5.15-0
  certifi            pkgs/main/linux-64::certifi-2019.6.16-py27_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1c-h7b6447c_1
  pip                pkgs/main/linux-64::pip-19.1.1-py27_0
  python             pkgs/main/linux-64::python-2.7.16-h9bab390_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-41.0.1-py27_0
  sqlite             pkgs/main/linux-64::sqlite-3.29.0-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.4-py27_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? 


Downloading and Extracting Packages
ca-certificates-2019 | 133 KB    | ##################################### | 100% 
wheel-0.33.4         | 39 KB     | ##################################### | 100% 
setuptools-41.0.1    | 640 KB    | ##################################### | 100% 
certifi-2019.6.16    | 154 KB    | ##################################### | 100% 
pip-19.1.1           | 1.8 MB    | ##################################### | 100% 
sqlite-3.29.0        | 1.9 MB    | ##################################### | 100% 
libstdcxx-ng-9.1.0   | 4.0 MB    | ##################################### | 100% 
_libgcc_mutex-0.1    | 3 KB      | ##################################### | 100% 
openssl-1.1.1c       | 3.8 MB    | ##################################### | 100% 
libgcc-ng-9.1.0      | 8.1 MB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ ll `which python`
lrwxrwxrwx 1 user user 9 Jul 24 13:14 /home/user/miniconda2/envs/test/bin/python -> python2.7*
~$ ll `which python2.7`
-rwxrwxr-x 1 user user 19760 Mar 14 14:02 /home/user/miniconda2/envs/test/bin/python2.7*
$ sudo setcap cap_net_raw+ep /home/user/miniconda2/envs/test/bin/python2.7
[sudo] password for user: 
$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.executable
'/home/user/miniconda2/envs/test/bin/python'
>>> sys.version
'2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]'
>>> import weakref
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda2/envs/test/lib/python2.7/weakref.py", line 14, in <module>
    from _weakref import (
ImportError: cannot import name _remove_dead_weakref
```

## Expected Behavior

As you can see, the python version when typing "python" the python version started is changing, between after and before granting the capabilities. That is although python thinks it is the same executable.
Internal parts of python shouldn't change :) 

## Environment Information

I'm writing with my phone and can't copy from my pc, so I'll write some,of the info

We are working with internal conda file server so they are in the channels info

UPDATE: I have recreated this on my home PC with a fresh install of conda: 

<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : test
    active env location : /home/user/miniconda2/envs/test
            shell level : 2
       user config file : /home/user/.condarc
 populated config files : 
          conda version : 4.6.14
    conda-build version : not installed
         python version : 2.7.16.final.0
       base environment : /home/user/miniconda2  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/miniconda2/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda2/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/2.7.16 Linux/4.15.0-45-generic ubuntu/16.04.6 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(test) user@ubuntu:~$ conda config --show-sources

(test) user@ubuntu:~$ 
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(test) user@ubuntu:~$ conda list --show-channel-urls
# packages in environment at /home/user/miniconda2/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2019.5.15                     0    defaults
certifi                   2019.6.16                py27_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
pip                       19.1.1                   py27_0    defaults
python                    2.7.16               h9bab390_0    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                41.0.1                   py27_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.33.4                   py27_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
(test) user@ubuntu:~$ 

```
</p></details>

**Comment by mingwandroid** [comment]
Please provide the details asked for.

I strongly suspect you are not running the python 2.7 binary from Anaconda and are instead running that from your distro which isn't much supported here.

**Comment by snudler6** [comment]
I am working in an offline network, so the channel is local, but it contains only packages downloaded from the anaconda channel. I'll be home soon, and try to reproduce it on my pc.

**Comment by mingwandroid** [comment]
If you're using your own channel we probably cannot do a lot to help you, but please give details anyway.

**Comment by snudler6** [comment]
I have recreated the error on my home PC with a fresh conda install.
I have updated the bug, to include this information now

**Comment by msarahan** [comment]
> '2.7.12 (default, Nov 12 2018, 14:36:49) \n[GCC 5.4.0 20160609]'

That's a signature from your system python.

Your python in your environment appears to be a symlink to only the "python2.7" name:

``lrwxrwxrwx 1 user user 9 Jul 24 13:14 /home/user/miniconda2/envs/test/bin/python -> python2.7*``

It seems like maybe you've tried virtualenv and it has left a mess?  The total lack of output from the conda install command is confusing.  Try creating the environment with python to see if it does any better:

conda create -n test python=2

**Comment by snudler6** [comment]
I know it's symlink, but conda created it. I also printed the `which python2.7` to show it is part of the environment.
I ran this on a newly created ubuntu 16.04 VM, so I never used virtualenv on this machine.
The lack of printing on the conda install, is me lazy again, I'll add it, also I'll try with creating the env with python soon.

**Comment by msarahan** [comment]
Thanks for the update.  You're definitely not picking up our python - it would be 2.7.16 from what the install logs are showing.  Sorry, but you need to sort this out on your end.  We have no idea why your system is saying one thing with `which` but doing seemingly something else.

**Comment by snudler6** [comment]
Also happen when creating the environment with python
```
(base) user@ubuntu:~$ conda create -n test2 python=2
Collecting package metadata: done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.6.14
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/user/miniconda2/envs/test2

  added / updated specs:
    - python=2


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.5.15-0
  certifi            pkgs/main/linux-64::certifi-2019.6.16-py27_0
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1c-h7b6447c_1
  pip                pkgs/main/linux-64::pip-19.1.1-py27_0
  python             pkgs/main/linux-64::python-2.7.16-h9bab390_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-41.0.1-py27_0
  sqlite             pkgs/main/linux-64::sqlite-3.29.0-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.4-py27_0
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test2
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) user@ubuntu:~$ conda activate test2
(test2) user@ubuntu:~$ ll `which python`
lrwxrwxrwx 1 user user 9 Jul 24 13:53 /home/user/miniconda2/envs/test2/bin/python -> python2.7*
(test2) user@ubuntu:~$ ll `which python2.7`
-rwxrwxr-x 1 user user 19760 Mar 14 14:02 /home/user/miniconda2/envs/test2/bin/python2.7*
(test2) user@ubuntu:~$ python
Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
(test2) user@ubuntu:~$ sudo setcap cap_net_raw+ep /home/user/miniconda2/envs/test2/bin/python2.7
[sudo] password for user: 
(test2) user@ubuntu:~$ python
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 

```

As you can see, my system does pick the right python before setting the capabilities, but the wrong one after setting them. With virtualenv, I never had this issue, and I really want to move to conda (although I do need this capability).
As I said, this is a fresh installation of an Ubuntu 16.04, with a fresh install of miniconda :\

**Comment by msarahan** [comment]
I'm not sure if anyone else on the team has ideas, but we can't otherwise dedicate resources to understanding and fixing this.  If you do find a fix that we can apply to our python recipe, https://github.com/anacondarecipes/python-feedstock, let us know.

**Comment by forrestwaters** [comment]
I think this breaks because rpath path replacement doesn't work on executables that have been given additional privileges for security reasons. I don't think there's a way to make this work with conda (perhaps it worked with virtualenv because you were using system python?)

Deeper explanation here: https://unix.stackexchange.com/questions/16656/problem-to-launch-java-at-debian-error-while-loading-shared-libraries-libjli

**Comment by snudler6** [comment]
Wow. Thanks a ton.
After reading the stackexchange you linked, I've got the the next one: https://unix.stackexchange.com/questions/87978/how-to-get-oracle-java-7-to-work-with-setcap-cap-net-bind-serviceep which help me to understand it fully.
Indeed, my problem is because Conda's python is using a relative RPATH to find libpython. after giving capabilities to python, the dynamic loader is ignoring packages in paths not configured "safe". The result is, that the python executable of conda is loading the system's libpython, and this is causing all sort of problems. (Most likely is that in virtualenv, we've just never noticed that because the venv's python is just a copy of the system python)
Because this behavior is unexpected, and is because of the changed RPATH in conda's python, it should be documented in the python installation guide for linux? I could add it myself, if you prefer.
Anyway, I really appreciate your quick responses, and you being so helpful.
