### ISSUE TITLE
No such file or directory: u'/home/drhigh/anaconda2/pkgs/matplotlib-1.5.1-np110py27_0/info/index.json

### ISSUE THREAD

**Issue by r0uen** [conda/conda#8991]
Hello,
I'm running Linux Mint 19.1.
An "unexpected error" occurs when I'm trying to create the environment for anaconda. Packages are being installed until we get to anaconda-4.0.0, there it stops and here is the last error message : 
 IOError: [Errno 2] No such file or directory: u'/home/drhigh/anaconda2/pkgs/matplotlib-1.5.1-np110py27_0/info/index.json'

### Steps to Reproduce

```
$ conda create -n gl-env python=2.7 anaconda=4.0.0

Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /home/drhigh/anaconda2/envs/gl-env:

The following NEW packages will be INSTALLED:

    alabaster:          0.7.7-py27_0      
    anaconda:           4.0.0-np110py27_0 
   [...]   
    zlib:               1.2.8-0           

Proceed ([y]/n)? 

blas-1.0-mkl.t 100% |#########################################################################################################################| Time: 0:00:00   2.14 MB/s
[...]
jupyter-1.0.0- 100% |#########################################################################################################################| Time: 0:00:00   1.76 MB/s
anaconda-4.0.0 100% |#########################################################################################################################| Time: 0:00:00   4.57 MB/s
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/drhigh/anaconda2  (writable)
    default environment : /home/drhigh/anaconda2
       envs directories : /home/drhigh/anaconda2/envs
                          /home/drhigh/.conda/envs
          package cache : /home/drhigh/anaconda2/pkgs
                          /home/drhigh/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.12.4 CPython/2.7.13 Linux/4.15.0-54-generic debian/buster/sid glibc/2.27    
                UID:GID : 1000:1000

`$ /home/drhigh/anaconda2/bin/conda create -n gl-env python=2.7 anaconda=4.0.0`




    Traceback (most recent call last):
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/cli/main.py", line 140, in _main
        exit_code = args.func(args, p)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/cli/install.py", line 326, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/plan.py", line 828, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 125, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/core/link.py", line 125, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 81, in read_package_info
        index_json_record = read_index_json(extracted_package_directory)
      File "/home/drhigh/anaconda2/lib/python2.7/site-packages/conda/gateways/disk/read.py", line 100, in read_index_json
        with open(join(extracted_package_directory, 'info', 'index.json')) as fi:
    IOError: [Errno 2] No such file or directory: u'/home/drhigh/anaconda2/pkgs/matplotlib-1.5.1-np110py27_0/info/index.json'

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : 1.20.0
         python version : 2.7.13.final.0
       requests version : 2.12.4
       root environment : /home/drhigh/anaconda2  (writable)
    default environment : /home/drhigh/anaconda2
       envs directories : /home/drhigh/anaconda2/envs
                          /home/drhigh/.conda/envs
          package cache : /home/drhigh/anaconda2/pkgs
                          /home/drhigh/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.12.4 CPython/2.7.13 Linux/4.15.0-54-generic debian/buster/sid glibc/2.27    
                UID:GID : 1000:1000

**Comment by msarahan** [comment]
Sorry, but that conda is older than what we support outside the context of an Anaconda Enterprise installation.

You might try cleaning up your package cache (`/home/drhigh/anaconda2/pkgs/`).  Good luck.
