### ISSUE TITLE
S3 channels failing with new multi-threaded package metadata retrieval

### ISSUE THREAD

**Issue by hajapy** [conda/conda#8993]
## Current Behavior

Attempting to create an environment when an s3 channel is provided and boto3 is installed results in errors on linux. 

### Steps to Reproduce

```
conda create -n test -c s3://<redacted> python requests numpy <redacted>
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/cli/install.py", line 256, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/solve.py", line 150, in solve_for_diff
        force_remove)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/solve.py", line 249, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/solve.py", line 389, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/solve.py", line 974, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/index.py", line 214, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 91, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/concurrent/futures/thread.py", line 56, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 87, in <lambda>
        package_ref_or_match_spec))
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 96, in query
        self.load()
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 160, in load
        _internal_state = self._load()
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 234, in _load
        repodata_fn=self.repodata_fn)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/core/subdir_data.py", line 471, in fetch_repodata_remote_request
        timeout=timeout)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/requests/sessions.py", line 521, in get
        return self.request('GET', url, **kwargs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
        resp = self.send(prep, **send_kwargs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
        r = adapter.send(request, **kwargs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/gateways/connection/adapters/s3.py", line 30, in send
        return self._send_boto3(boto3, resp, request)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/conda/gateways/connection/adapters/s3.py", line 50, in _send_boto3
        key = boto3.resource('s3').Object(bucket_name, key_string[1:])
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/boto3/__init__.py", line 100, in resource
        return _get_default_session().resource(*args, **kwargs)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/boto3/session.py", line 389, in resource
        aws_session_token=aws_session_token, config=config)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/boto3/session.py", line 263, in client
        aws_session_token=aws_session_token, config=config)
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/botocore/session.py", line 826, in create_client
        credentials = self.get_credentials()
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/botocore/session.py", line 425, in get_credentials
        'credential_provider').load_credentials()
      File "/home/ubuntu/jenkins/workspace/miniconda/lib/python3.6/site-packages/botocore/session.py", line 906, in get_component
        del self._deferred[name]
    KeyError: 'credential_provider'

`$ conda create -n test -c s3://<redacted> python requests numpy <redacted>`

  environment variables:
                 CIO_TEST=<not set>
               CONDA_ROOT=/home/ubuntu/jenkins/workspace/miniconda
                     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/game
                          s:/usr/local/games:/snap/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/ubuntu/.condarc
 populated config files :
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.6.3.final.0
       virtual packages :
       base environment : /home/ubuntu/jenkins/workspace/miniconda  (writable)
           channel URLs : s3://<redacted>/linux-64
                          s3://<redacted>/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ubuntu/jenkins/workspace/miniconda/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/jenkins/workspace/miniconda/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-1062-aws ubuntu/16.04.2 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

## Expected Behavior

The environment should get created without error.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : /home/ubuntu/.condarc
 populated config files :
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.6.3.final.0
       virtual packages :
       base environment : /home/ubuntu/jenkins/workspace/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/ubuntu/jenkins/workspace/miniconda/pkgs
                          /home/ubuntu/.conda/pkgs
       envs directories : /home/ubuntu/jenkins/workspace/miniconda/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-1062-aws ubuntu/16.04.2 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/ubuntu/jenkins/workspace/miniconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
argcomplete               1.10.0                   py36_0    defaults
asn1crypto                0.23.0           py36h4639342_0    defaults
boto3                     1.9.162                    py_0    defaults
botocore                  1.12.163                   py_0    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2017.08.26           h1d4fec5_0    defaults
certifi                   2017.11.5        py36hf29ccca_0    defaults
cffi                      1.11.2           py36h2825082_0    defaults
chardet                   3.0.4            py36h0f667ec_1    defaults
conda                     4.7.10                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.11                   py36_0    defaults
cryptography              2.1.4            py36hd09be54_0    defaults
docutils                  0.14                     py36_0    defaults
idna                      2.6              py36h82fb2a8_1    defaults
jmespath                  0.9.4                      py_0    defaults
libarchive                3.3.3                h7d0bbab_1    defaults
libedit                   3.1                  heed3624_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              7.2.0                h7a57d05_2    defaults
libxml2                   2.9.9                hea5a465_1    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
ncurses                   6.0                  h9df7e31_2    defaults
openssl                   1.0.2s               h7b6447c_0    defaults
pip                       9.0.1            py36h6c6f9ce_4    defaults
psutil                    5.6.3            py36h7b6447c_0    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pysocks                   1.6.7            py36hd97a5b1_1    defaults
python                    3.6.3                h6c0c0dc_5    defaults
python-dateutil           2.8.0                    py36_0    defaults
python-libarchive-c       2.8                     py36_11    defaults
readline                  7.0                  ha6073c6_4    defaults
requests                  2.18.4           py36he2e5f8d_1    defaults
ruamel_yaml               0.11.14          py36ha2fb22d_2    defaults
s3transfer                0.2.0                    py36_0    defaults
setuptools                36.5.0           py36he42e2e1_0    defaults
six                       1.11.0           py36h372c433_1    defaults
sqlite                    3.20.1               hb898158_2    defaults
tk                        8.6.7                hc745277_3    defaults
tqdm                      4.32.1                     py_0    defaults
urllib3                   1.22             py36hbe7ace6_0    defaults
wheel                     0.30.0           py36hfd4bba0_1    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               ha838bed_2    defaults
zstd                      1.3.3                h84994c4_0    defaults
```
</p></details>

Relevant issues in botocore/boto3 suggest this is a multithreading issue. 

https://github.com/boto/boto3/issues/1592
https://github.com/boto/botocore/issues/1246

```
uname -a
Linux ip-###-###-###-### 4.4.0-1062-aws #71-Ubuntu SMP Fri Jun 15 10:07:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

I cannot reproduce this issue on macOS high sierra.

**Comment by hajapy** [comment]
Also to add another possible avenue to explore/reproduce. I did not see this problem on machines that had aws config files and were outside ec2, but the Jenkins machine where it shows up is in ec2 and uses an IAM role, so the cases are not exactly identical and the os difference could be a red herring.

**Comment by hajapy** [comment]
I did some testing replicating the s3 adapter in conda but simplifying it to a minimal example:

**Broken case**
```
(aws-testing) pi@raspberrypi:~/workspace/boto-threading $ cat broken.py 
# coding: utf-8
from concurrent.futures import ThreadPoolExecutor
import boto3

def f(x):
     key = boto3.resource('s3').Object('mybucket', 'mykey')
     val = key.get()

with ThreadPoolExecutor() as e:
    _ = list(e.map(f, range(20)))

print('done!')

(aws-testing) pi@raspberrypi:~/workspace/boto-threading $ python broken.py 
Traceback (most recent call last):
  File "broken.py", line 10, in <module>
    _ = list(e.map(f, range(20)))
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "broken.py", line 6, in f
    key = boto3.resource('s3').Object('mybucket', 'mykey')
  File "/home/pi/.envs/aws-testing/lib/python3.7/site-packages/boto3/__init__.py", line 100, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/home/pi/.envs/aws-testing/lib/python3.7/site-packages/boto3/session.py", line 389, in resource
    aws_session_token=aws_session_token, config=config)
  File "/home/pi/.envs/aws-testing/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/home/pi/.envs/aws-testing/lib/python3.7/site-packages/botocore/session.py", line 828, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/home/pi/.envs/aws-testing/lib/python3.7/site-packages/botocore/session.py", line 695, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/home/pi/.envs/aws-testing/lib/python3.7/site-packages/botocore/session.py", line 907, in get_component
    del self._deferred[name]
KeyError: 'endpoint_resolver'
```
Note this is a different error than reported above, but it is one of the two errors reported on the linked upstream issues in boto3/botocore. 

After introducing a main-thread initialization of a client, the same code executes without issue:


**Fixed case**
```
(aws-testing) pi@raspberrypi:~/workspace/boto-threading $ cat fixed.py 
# coding: utf-8

from concurrent.futures import ThreadPoolExecutor
import boto3

def f(x):
     key = boto3.resource('s3').Object('mybucket', 'mykey')
     val = key.get()

boto3.client('s3')   # <== called on main thread to make boto3 happy
with ThreadPoolExecutor() as e:
    _ = list(e.map(f, range(20)))

print('done!')

(aws-testing) pi@raspberrypi:~/workspace/boto-threading $ python fixed.py 
done!
```
