### ISSUE TITLE
Conda 4.7.x `conda.exe info` broken, breaking nb_conda_kernels / jupyter notebook

### ISSUE THREAD

**Issue by bollard** [conda/conda#9018]
Hi,

Have just updated from Conda 4.6.14 to 4.7.10. Tried to run `jupyter notebook` and received the following error

```
C:\Users\user.name>jupyter notebook
[E 09:07:02.430 NotebookApp] [nb_conda_kernels] couldn't call conda:
    Command '['D:\\Miniconda3\\Scripts\\conda.exe', 'info', '--json']' returned non-zero exit status 1.
[I 09:07:02.431 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 09:07:02.661 NotebookApp] [nb_conda] enabled
```

Digging in a little, I i run the command manually I see

```
C:\>D:\Miniconda3\Scripts\conda.exe info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "D:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "D:\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "D:\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "D:\Miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "D:\Miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "D:\Miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "D:\Miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "D:\Miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "D:\Miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "D:\Miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "D:\Miniconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None

`$ D:\Miniconda3\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(research) C:\Users\user.name>conda info

     active environment : research
    active env location : D:\Miniconda3\envs\research
            shell level : 2
       user config file : C:\Users\user.name\.condarc
 populated config files : C:\Users\user.name\.condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.1
       base environment : D:\Miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Miniconda3\pkgs
                          C:\Users\user.name\.conda\pkgs
                          C:\Users\user.name\AppData\Local\conda\conda\pkgs
       envs directories : D:\Miniconda3\envs
                          C:\Users\user.name\.conda\envs
                          C:\Users\user.name\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by zlhcsm** [comment]
no idea

**Comment by bollard** [comment]
So presume the behaviour of `conda.exe info` has changed - but I can't see it documented anywhere. Perhaps its now required to go through an activated shell, instead of calling the `.exe` directly?

**Comment by bollard** [comment]
Any guidance on the supported way to call `conda.exe info`?

**Comment by heegd** [comment]
From what I could tell there was something changed with the way conda is setting the system paths in the new version.  It couldn't find a library that was in \env\Library\lib.  I tried adding that path to the conda activate.bat which got nb_conda_kernels working again but it messed up conda after activating environments.  

I eventually ended up downgrading to conda 4.6 with:
`conda install conda=4.6`

And everything is working again.

**Comment by zlhcsm** [comment]
I can't do anything with conda.
`
conda install conda=4.6
Traceback (most recent call last):
  File "D:\Users\Alan\Anaconda2\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "D:\Users\Alan\Anaconda2\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "D:\Users\Alan\Anaconda2\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "D:\Users\Alan\Anaconda2\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "D:\Users\Alan\Anaconda2\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "D:\Users\Alan\Anaconda2\lib\ctypes\__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "D:\Users\Alan\Anaconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: LoadLibrary() argument 1 must be string, not unicode`

**Comment by zlhcsm** [comment]
you can try another method to add a kernel to jupyter_notebook by 

> conda install ipykernel
