### ISSUE TITLE
Package installed via binstar does not uninstall

### ISSUE THREAD

**Issue by michaelaye** [conda/conda#902]
I installed `seaborn` via binstar like so:

```
conda install -c asmeurer seaborn
```

Then I realised how old that version is and wanted to remove it. Trying so throws an unexpected error:

``` bash
± conda remove seaborn
Fetching package metadata: ..
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/Users/maye/anaconda/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/Users/maye/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/Users/maye/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 199, in args_func
    args.func(args, p)
  File "/Users/maye/anaconda/lib/python2.7/site-packages/conda/cli/main_remove.py", line 135, in execute
    actions = plan.remove_actions(prefix, specs, index=index, pinned=args.pinned)
  File "/Users/maye/anaconda/lib/python2.7/site-packages/conda/plan.py", line 460, in remove_actions
    if r and r.track_features(fn):
  File "/Users/maye/anaconda/lib/python2.7/site-packages/conda/utils.py", line 102, in __call__
    res = cache[key] = self.func(*args, **kw)
  File "/Users/maye/anaconda/lib/python2.7/site-packages/conda/resolve.py", line 257, in track_features
    return set(self.index[fn].get('track_features', '').split())
KeyError: 'seaborn-0.2.1-py27_0.tar.bz2'
-> [1]
```

conda info:

``` bash
 conda info
Current conda install:

             platform : osx-64
        conda version : 3.6.3
  conda-build version : not installed
       python version : 2.7.8.final.0
     requests version : 2.4.0
     root environment : /Users/maye/anaconda  (writable)
  default environment : /Users/maye/anaconda
     envs directories : /Users/maye/anaconda/envs
        package cache : /Users/maye/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False
```

**Comment by denfromufa** [comment]
i had similar problem with latest anaconda, conda, seaborn:

http://stackoverflow.com/questions/28588776/python-net-name-must-not-be-empty

please note that pip installs/uninstalls correctly, not conda.
