### ISSUE TITLE
Encountering attribute error when cloning environment on 4.17.5

### ISSUE THREAD

**Issue by carkar7** [conda/conda#9035]
## Current Behavior

I am attempting to clone an environment and update dask, however I keep encountering problems. Even if I simply try to update dask via 'conda update dask' i get an assertion error. 

### Steps to Reproduce

```
(base) MBP-ENG-008:~ krobles$ conda activate py36_imblearn
(py36_imblearn) MBP-ENG-008:~ krobles$ conda create --name dask_env --clone py36_imblearn
WARNING: A directory already exists at the target location '/Users/krobles/anaconda3/envs/dask_env'
but it is not a conda environment.
Continue creating environment (y/[n])? y

WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Source:      /Users/krobles/anaconda3/envs/py36_imblearn
Destination: /Users/krobles/anaconda3/envs/dask_env
Packages: 307
Files: 1298

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/entity.py", line 411, in __get__
        val = instance.__dict__[self.name]
    KeyError: 'size'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 244, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 74, in clone
        index_args=index_args)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/misc.py", line 286, in clone_env
        force_extract=False, index_args=index_args)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/misc.py", line 84, in explicit
        pfe.execute()
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 632, in execute
        self.prepare()
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 617, in prepare
        for prec in self.link_precs)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 617, in <genexpr>
        for prec in self.link_precs)
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 532, in make_actions_for_record
        size=pcrec_from_writable_cache.size or size,
      File "/Users/krobles/anaconda3/lib/python3.7/site-packages/conda/_vendor/auxlib/entity.py", line 417, in __get__
        raise AttributeError("A value for {0} has not been set".format(self.name))
    AttributeError: A value for size has not been set

`$ /Users/krobles/anaconda3/bin/conda create --name dask_env --clone py36_imblearn`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_BACKUP_HOST=x86_64-apple-darwin13.4.0
      CONDA_BUILD_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
        CONDA_DEFAULT_ENV=py36_imblearn
                CONDA_EXE=/Users/krobles/anaconda3/bin/conda
             CONDA_PREFIX=/Users/krobles/anaconda3/envs/py36_imblearn
           CONDA_PREFIX_1=/Users/krobles/anaconda3
    CONDA_PROMPT_MODIFIER=(py36_imblearn)
         CONDA_PYTHON_EXE=/Users/krobles/anaconda3/bin/python
               CONDA_ROOT=/Users/krobles/anaconda3
              CONDA_SHLVL=2
                     PATH=/Users/krobles/anaconda3/bin:/Users/krobles/anaconda3/envs/py36_imblea
                          rn/bin:/Users/krobles/anaconda3/bin:/Users/krobles/anaconda3/condabin:
                          /Users/anaconda3/bin:/Users/krobles/anaconda3/bin:/usr/local/bin:/usr/
                          bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : py36_imblearn
    active env location : /Users/krobles/anaconda3/envs/py36_imblearn
            shell level : 2
       user config file : /Users/krobles/.condarc
 populated config files : /Users/krobles/.condarc
          conda version : 4.7.5
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
       virtual packages : 
       base environment : /Users/krobles/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/krobles/anaconda3/pkgs
                          /Users/krobles/.conda/pkgs
       envs directories : /Users/krobles/anaconda3/envs
                          /Users/krobles/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.1 Darwin/17.7.0 OSX/10.13.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

```

## Expected Behavior

Should be able to create a cloned env

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
          conda version : 4.7.5
    conda-build version : 3.17.8
         python version : 3.7.1.final.0
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/krobles/.condarc <==
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/krobles/anaconda3/envs/py36_imblearn:
#
# Name                    Version                   Build  Channel
_py-xgboost-mutex         2.0                       cpu_0    conda-forge
alabaster                 0.7.12                   py36_0    defaults
anaconda                  custom           py36ha4fed55_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-project          0.8.2                    py36_0    defaults
appnope                   0.1.0            py36hf537a9a_0    defaults
appscript                 1.0.1            py36h1de35cc_1    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   2.1.0                    py36_0    defaults
astropy                   3.1              py36h1de35cc_0    defaults
atomicwrites              1.2.1                    py36_0    defaults
attrs                     18.2.0           py36h28b3542_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                      py36_1    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
bcrypt                    3.1.4            py36h470a237_0    conda-forge
beautifulsoup4            4.6.3                    py36_0    defaults
bitarray                  0.8.3            py36h1de35cc_0    defaults
bkcharts                  0.2              py36h073222e_0    defaults
blas                      2.10                   openblas    conda-forge
blaze                     0.11.3                   py36_0    defaults
bleach                    3.0.2                    py36_0    defaults
blosc                     1.14.4               hd9629dc_0    defaults
bokeh                     1.0.2                    py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cctools                   895                           1    defaults
certifi                   2019.6.16                py36_0    conda-forge
cffi                      1.11.5           py36h6174b99_1    defaults
chardet                   3.0.4                    py36_1    defaults
clang                     4.0.1                         1    defaults
clang_osx-64              4.0.1               h1ce6c1d_11    conda-forge
clangxx                   4.0.1                         1    defaults
clangxx_osx-64            4.0.1               h22b1bf0_11    defaults
click                     7.0                      py36_0    defaults
cloudpickle               0.6.1                    py36_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.1                    py36_0    defaults
compiler-rt               4.0.1                hcfea43d_1    defaults
contextlib2               0.5.5            py36hd66e5e7_0    defaults
convertdate               2.1.3                   py_1000    conda-forge
cryptography              2.4.2            py36ha12b0ac_0    defaults
curl                      7.63.0            ha441bb4_1000    defaults
cycler                    0.10.0           py36hfc81398_0    defaults
cymem                     2.0.2            py36h04f5b5a_0    defaults
cython                    0.29.2           py36h0a44026_0    defaults
cython-blis               0.2.4            py36h01d97ff_0    conda-forge
cytoolz                   0.9.0.1          py36h1de35cc_1    defaults
dask                      1.0.0                    py36_0    defaults
dask-core                 1.0.0                    py36_0    defaults
datashape                 0.5.4                    py36_1    defaults
dbus                      1.13.2               h760590f_1    defaults
decorator                 4.3.0                    py36_0    defaults
defusedxml                0.5.0                    py36_1    defaults
distributed               1.25.1                   py36_0    defaults
docutils                  0.14             py36hbfde631_0    defaults
en-core-web-sm            2.1.0                    pypi_0    pypi
entrypoints               0.2.3                    py36_2    defaults
ephem                     3.7.6.0         py36h1de35cc_1001    conda-forge
et_xmlfile                1.0.1            py36h1315bdc_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py36h1de35cc_2    defaults
fbprophet                 0.4.post2        py36h0a44026_0    conda-forge
filelock                  3.0.10                   py36_0    defaults
flask                     1.0.2                    py36_1    defaults
flask-cors                3.0.7                    py36_0    defaults
flatbuffers               1.10                     pypi_0    pypi
freetype                  2.9.1                hb4e5f40_0    defaults
funcsigs                  1.0.2                    pypi_0    pypi
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.3.7            py36h1de35cc_1    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py36_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py36h6ef4df4_2    defaults
greenlet                  0.4.15           py36h1de35cc_0    defaults
h5py                      2.8.0            py36h878fce3_3    defaults
hdbscan                   0.8.22           py36h1e5eb4f_1    conda-forge
hdf5                      1.10.2               hfa1e0ec_1    defaults
heapdict                  1.0.0                    py36_2    defaults
holidays                  0.9.9                      py_0    conda-forge
html5lib                  1.0.1                    py36_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py36_0    defaults
imageio                   2.4.1                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
imbalanced-learn          0.4.3                      py_0    conda-forge
importlib_metadata        0.6                      py36_0    defaults
intel-openmp              2019.1                      144    defaults
ipykernel                 5.1.0            py36h39e3cac_0    defaults
ipython                   7.2.0            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
ipywidgets                7.4.2                    py36_0    defaults
isort                     4.3.4                    py36_0    defaults
itsdangerous              1.1.0                    py36_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py36_0    defaults
jedi                      0.13.2                   py36_0    defaults
jinja2                    2.10                     py36_0    defaults
joblib                    0.13.2                   py36_0    defaults
jpeg                      9b                   he5867d9_2    defaults
jsonschema                2.6.0            py36hb385e00_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.2.4                    py36_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_core              4.4.0                    py36_0    defaults
jupyterlab                0.35.3                   py36_0    defaults
jupyterlab_server         0.2.0                    py36_0    defaults
keyring                   17.0.0                   py36_0    defaults
kiwisolver                1.0.1            py36h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lazy-object-proxy         1.3.1            py36h1de35cc_2    defaults
ld64                      274.2                         1    defaults
libarchive                3.3.3                h786848e_5    defaults
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libcurl                   7.63.0            h051b688_1000    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20170329         hb402a30_2    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblapack                 3.8.0               10_openblas    conda-forge
liblapacke                3.8.0               10_openblas    conda-forge
liblief                   0.9.0                h2a1bed3_0    defaults
libopenblas               0.3.3                hdc02c5d_3    defaults
libpng                    1.6.35               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.9                hcb84e12_2    defaults
libxgboost                0.81              h0a44026_1000    conda-forge
libxml2                   2.9.8                hab757c2_1    defaults
libxslt                   1.1.32               hb819dd2_0    defaults
llvm                      4.0.1                         1    defaults
llvm-lto-tapi             4.0.1                         1    defaults
llvm-openmp               4.0.1                hcfea43d_1    defaults
llvmlite                  0.26.0           py36h8c7ce04_0    defaults
locket                    0.2.0            py36hca03003_1    defaults
lunardate                 0.2.0                      py_0    conda-forge
lxml                      4.2.5            py36hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.1.0            py36h1de35cc_0    defaults
matplotlib                3.0.2            py36h54f8f79_0    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36h1de35cc_0    defaults
mkl                       2019.1                      144    defaults
more-itertools            4.3.0                    py36_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py36_0    defaults
msgpack-python            0.5.6            py36h04f5b5a_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
murmurhash                1.0.0            py36h0a44026_0    conda-forge
mysql-connector-c         6.1.11               hccea1a4_0    defaults
mysqlclient               1.3.14           py36h1de35cc_0    defaults
nb_conda                  2.2.1                    py36_0    defaults
nb_conda_kernels          2.2.0                    py36_1    defaults
nbconvert                 5.4.0                    py36_1    defaults
nbformat                  4.4.0            py36h827af21_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
networkx                  2.2                      py36_1    defaults
nltk                      3.4                      py36_1    defaults
nomkl                     3.0                           0    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  5.7.4                    py36_0    defaults
numba                     0.41.0           py36h6440ff4_0    defaults
numexpr                   2.6.9            py36hafae301_0    defaults
numpy                     1.15.0                   pypi_0    pypi
numpy-base                1.16.2           py36ha711998_0    defaults
numpydoc                  0.8.0                    py36_0    defaults
odo                       0.5.1            py36hc1af34a_0    defaults
olefile                   0.46                     py36_0    defaults
openblas                  0.3.6                hd44dcd8_2    conda-forge
openpyxl                  2.5.12                   py36_0    defaults
openssl                   1.1.1b               h01d97ff_2    conda-forge
packaging                 18.0                     py36_0    defaults
pandas                    0.24.1           py36h0a44026_0    defaults
pandas-profiling          1.4.1                    py36_0    defaults
pandoc                    1.19.2.1             ha5e8f32_1    defaults
pandocfilters             1.4.2                    py36_1    defaults
paramiko                  2.4.2                 py36_1000    conda-forge
parso                     0.3.1                    py36_0    defaults
partd                     0.3.9                    py36_0    defaults
path.py                   11.5.0                   py36_0    defaults
pathlib2                  2.3.3                    py36_0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.42                 h378b8a2_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.6.0                    py36_0    defaults
phonenumbers              8.10.10                    py_0    conda-forge
pickleshare               0.7.5                    py36_0    defaults
pillow                    5.3.0            py36hb68e598_0    defaults
pip                       18.1                     py36_0    defaults
pkginfo                   1.4.2                    py36_1    defaults
plac                      0.9.6                      py_1    conda-forge
pluggy                    0.8.0                    py36_0    defaults
ply                       3.11                     py36_0    defaults
preshed                   2.0.1            py36h0a44026_0    defaults
prometheus_client         0.5.0                    py36_0    defaults
prompt_toolkit            2.0.7                    py36_0    defaults
psutil                    5.4.8            py36h1de35cc_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
py                        1.7.0                    py36_0    defaults
py-lief                   0.9.0            py36hd4eaf27_0    defaults
py-xgboost                0.81            py36h0a44026_1000    conda-forge
pyasn1                    0.4.4                      py_1    conda-forge
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36h1de35cc_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36h1de35cc_9    defaults
pycurl                    7.43.0.2         py36ha12b0ac_0    defaults
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.3.1                    py36_0    defaults
pylint                    2.2.2                    py36_0    defaults
pynacl                    1.3.0           py36h1de35cc_1000    conda-forge
pyodbc                    4.0.25           py36h0a44026_0    defaults
pyopenssl                 18.0.0                   py36_0    defaults
pyparsing                 2.3.0                    py36_0    defaults
pyqt                      5.9.2            py36h655552a_2    defaults
pysocks                   1.6.8                    py36_0    defaults
pystan                    2.17.1.0        py36h1702cab_1003    conda-forge
pytables                  3.4.4            py36h13cba08_0    defaults
pytest                    4.0.2                    py36_0    defaults
pytest-arraydiff          0.3              py36h39e3cac_0    defaults
pytest-astropy            0.5.0                    py36_0    defaults
pytest-doctestplus        0.2.0                    py36_0    defaults
pytest-openfiles          0.3.1                    py36_0    defaults
pytest-remotedata         0.3.1                    py36_0    defaults
python                    3.6.7                haf84260_0    defaults
python-dateutil           2.7.5                    py36_0    defaults
python-libarchive-c       2.8                      py36_6    defaults
python.app                2                        py36_9    defaults
pytz                      2018.7                   py36_0    defaults
pywavelets                1.0.1            py36h1d22016_0    defaults
pyyaml                    3.13             py36h1de35cc_0    defaults
pyzmq                     17.1.2           py36h1de35cc_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.3                    py36_0    defaults
qtconsole                 4.4.3                    py36_0    defaults
qtpy                      1.5.2                    py36_0    defaults
ray                       0.6.2                    pypi_0    pypi
readline                  7.0                  h1de35cc_5    defaults
redis                     3.2.0                    pypi_0    pypi
requests                  2.21.0                   py36_0    defaults
rope                      0.11.0                   py36_0    defaults
ruamel_yaml               0.15.46          py36h1de35cc_0    defaults
scikit-image              0.14.1           py36h0a44026_0    defaults
scikit-learn              0.21.1           py36hebd9d1a_0    defaults
scipy                     1.2.1            py36h1a1e112_0    defaults
seaborn                   0.9.0                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
setuptools                40.6.3                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36hf20db9d_0    defaults
sip                       4.19.8           py36h0a44026_0    defaults
six                       1.12.0                   py36_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1            py36h6c7b616_0    defaults
sortedcollections         1.0.1                    py36_0    defaults
sortedcontainers          2.1.0                    py36_0    defaults
spacy                     2.1.4            py36h770b8ee_0    conda-forge
sphinx                    1.8.2                    py36_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.3.2                    py36_0    defaults
spyder-kernels            0.3.0                    py36_0    defaults
sqlalchemy                1.2.15           py36h1de35cc_0    defaults
sqlite                    3.26.0               ha441bb4_0    defaults
srsly                     0.0.5            py36h0a44026_0    conda-forge
sshtunnel                 0.1.3                      py_1    conda-forge
statsmodels               0.9.0            py36h1d22016_0    defaults
sympy                     1.3                      py36_0    defaults
tblib                     1.3.2            py36hda67792_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.4.2                    py36_0    defaults
textblob                  0.15.3                     py_0    conda-forge
thinc                     7.0.4            py36h770b8ee_0    conda-forge
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py36_0    defaults
tornado                   5.1.1            py36h1de35cc_0    defaults
tqdm                      4.28.1           py36h28b3542_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
typed-ast                 1.1.0            py36h1de35cc_0    defaults
typing                    3.6.6                    pypi_0    pypi
unicodecsv                0.14.1           py36he531d66_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                   py36_0    defaults
wasabi                    0.2.2                      py_0    conda-forge
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.32.3                   py36_0    defaults
widgetsnbextension        3.4.2                    py36_0    defaults
wrapt                     1.10.11          py36h1de35cc_2    defaults
wurlitzer                 1.0.2                    py36_0    defaults
xgboost                   0.81            py36h0a44026_1000    conda-forge
xlrd                      1.2.0                    py36_0    defaults
xlsxwriter                1.1.2                    py36_0    defaults
xlwings                   0.15.1                   py36_0    defaults
xlwt                      1.2.0            py36h5ad1178_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.2.5                h0a44026_1    defaults
zict                      0.1.3                    py36_0    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```
</p></details>

**Comment by denfromufa** [comment]
@carkar7 did you resolve this?
