### ISSUE TITLE
Ipython notebook launch from Anaconda launcher : Error launching application

### ISSUE THREAD

**Issue by soumilj** [conda/conda#905]
Traceback (most recent call last):
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/cli/main.py", line 199, in args_func
    args.func(args, p)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/cli/main_run.py", line 64, in execute
    for pkg in get_package_versions(args.package):
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/api.py", line 166, in get_package_versions
    index = get_index()
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/api.py", line 40, in get_index
    unknown=unknown)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/utils.py", line 79, in __call__
    value = self.func(*args, **kw)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 193, in fetch_index
    reversed(channel_urls))
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 192, in 
    use_cache=use_cache, session=session)),
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/conda/fetch.py", line 87, in fetch_repodata
    verify=config.ssl_verify)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 460, in get
    return self.request('GET', url, **kwargs)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 448, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/sessions.py", line 554, in send
    r = adapter.send(request, **kwargs)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/adapters.py", line 359, in send
    timeout=timeout
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 308, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Users/soumiljain1/anaconda/lib/python2.7/httplib.py", line 995, in request
    self._send_request(method, url, body, headers)
  File "/Users/soumiljain1/anaconda/lib/python2.7/httplib.py", line 1029, in _send_request
    self.endheaders(body)
  File "/Users/soumiljain1/anaconda/lib/python2.7/httplib.py", line 991, in endheaders
    self._send_output(message_body)
  File "/Users/soumiljain1/anaconda/lib/python2.7/httplib.py", line 844, in _send_output
    self.send(msg)
  File "/Users/soumiljain1/anaconda/lib/python2.7/httplib.py", line 806, in send
    self.connect()
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 146, in connect
    conn = self._new_conn()
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connection.py", line 125, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/Users/soumiljain1/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/util/connection.py", line 64, in create_connection
    for res in socket.getaddrinfo(host, port, 0, socket.SOCK_STREAM):
ProtocolError: ('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))

Close

**Comment by soapy1** [comment]
@soumilj is this still an issue?
