### ISSUE TITLE
conda 4.7.10 is broken in git bash 2.18.0

### ISSUE THREAD

**Issue by KamarajuKusumanchi** [conda/conda#9055]
## Current Behavior

conda is broken after upgrading from 4.6.14 to 4.7.10 . In git bash (2.18.0), even simple commands such as "conda info" crash with the error
```
TypeError: expected string or Unicode object, NoneType found
```

### Steps to Reproduce

I upgraded conda to version 4.7.10 using
```
conda update -n base -c defaults conda
```
After the upgrade, "conda info" fails.
```
$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\ProgramData\Continuum\Anaconda\lib\importlib\__init__.py", line 37, in import_module
        __import__(name)
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\ProgramData\Continuum\Anaconda\lib\ctypes\__init__.py", line 444, in LoadLibrary
        return self._dlltype(name)
      File "C:\ProgramData\Continuum\Anaconda\lib\ctypes\__init__.py", line 366, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: expected string or Unicode object, NoneType found

`$ C:\ProgramData\Continuum\Anaconda\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:
```

## Expected Behavior

The "conda info" command should not fail.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\ProgramData\Continuum\Anaconda\lib\importlib\__init__.py", line 37, in import_module
        __import__(name)
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\ProgramData\Continuum\Anaconda\lib\ctypes\__init__.py", line 444, in LoadLibrary
        return self._dlltype(name)
      File "C:\ProgramData\Continuum\Anaconda\lib\ctypes\__init__.py", line 366, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: expected string or Unicode object, NoneType found

`$ C:\ProgramData\Continuum\Anaconda\Scripts\conda-script.py info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:


$ git --version
git version 2.18.0.windows.1
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> C:\Users\kkusuman\.condarc <==
ssl_verify: True
channels:
  - anaconda-fusion
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls
Traceback (most recent call last):
  File "C:\ProgramData\Continuum\Anaconda\Scripts\conda-script.py", line 12, in <module>
    sys.exit(main())
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\core\index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
    from libarchive.exception import ArchiveError as _LibarchiveArchiveError
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\entry.py", line 6, in <module>
    from . import ffi
  File "C:\ProgramData\Continuum\Anaconda\lib\site-packages\libarchive\ffi.py", line 48, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "C:\ProgramData\Continuum\Anaconda\lib\ctypes\__init__.py", line 444, in LoadLibrary
    return self._dlltype(name)
  File "C:\ProgramData\Continuum\Anaconda\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
TypeError: expected string or Unicode object, NoneType found
```
</p></details>

**Comment by stuarteberg** [comment]
+1

Indeed, it looks like conda is currently broken on Windows.  Presumably #9055 is the same error, in slightly different form.  (But this is the nicer bug report.  :wink:)

FWIW, here's an example Appveyor build that fails with the same error:
https://ci.appveyor.com/project/jbms/neuroglancer/builds/26488201

cc @neomorphic

**Comment by piyuranjan** [comment]
### Similar behavior with conda on WSL with Ubuntu 18.
```
(base)$ conda -V
conda 4.7.10
```
<details>
<summary>Simple commands like `conda list` fail.</summary>

```
(base)$ conda list
Traceback (most recent call last):
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1062, in __call__
    return func(*args, **kwargs)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/home/pr/.Miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/main_list.py", line 14, in <module>
    from ..core.prefix_data import PrefixData
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/core/prefix_data.py", line 24, in <module>
    from ..gateways.disk.create import write_as_json_to_file
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/gateways/disk/create.py", line 17, in <module>
    import conda_package_handling.api
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 12, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2, libarchive_enabled
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 11, in <module>
    import libarchive
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/home/pr/.Miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/pr/.Miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pr/.Miniconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1354, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1065, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1109, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1120, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1190, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
    from .package_cache_data import PackageCacheData
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from conda_package_handling.api import InvalidArchiveError
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 12, in <module>
    from .tarball import CondaTarBZ2 as _CondaTarBZ2, libarchive_enabled
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 11, in <module>
    import libarchive
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
    libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
  File "/home/pr/.Miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
    return self._dlltype(name)
  File "/home/pr/.Miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libiconv.so.2: cannot open shared object file: No such file or directory
```
</details>

<details>
<summary>Info command fails with reporting option as previously shared.</summary>

```
(base) pr@MSL00332:~$ conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/home/pr/.Miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda_package_handling/api.py", line 12, in <module>
        from .tarball import CondaTarBZ2 as _CondaTarBZ2, libarchive_enabled
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 11, in <module>
        import libarchive
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/entry.py", line 6, in <module>
        from . import ffi
      File "/home/pr/.Miniconda3/lib/python3.7/site-packages/libarchive/ffi.py", line 27, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "/home/pr/.Miniconda3/lib/python3.7/ctypes/__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "/home/pr/.Miniconda3/lib/python3.7/ctypes/__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: libiconv.so.2: cannot open shared object file: No such file or directory

`$ /home/pr/.Miniconda3/bin/conda info`


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true
```
</details>

**Activating an environment works.**
```
(base)$ conda activate envBlast
(envBlast)$
```

**Comment by msarahan** [comment]
4.7 adds a new library dependency, libarchive.  These errors indicate that libarchive is not being loaded successfully.  We'll try to shuffle around imports to avoid this as much as we can.  Ultimately, though, this might be a bad interaction between PATH as perceived by the bash shell, and PATH as perceived by the python process that runs conda.  We're already doing some pretty hacky things to help ensure that libarchive gets loaded correctly - https://github.com/AnacondaRecipes/python-libarchive-c-feedstock/blob/master/recipe/0002-prefer-to-load-libarchive-from-conda-pkg-path.patch - I'm not sure there's much more we can do, short of replacing python-libarchive-c with something that has libarchive statically linked into it (which we would like to do, but that's on a longer timeline).

The WSL error is completely different.  That's likely related to this: https://github.com/conda-forge/libxml2-feedstock/pull/48#issuecomment-518331253

**Comment by stuarteberg** [comment]
Ok, if this error is bash-specific, then is #9050 unrelated?  It can be triggered with out git-bash.

For example, the following [Appveyor log][1] does not use git-bash, and ends with this error:

[1]: https://ci.appveyor.com/project/jbms/neuroglancer/builds/26488201

```
      File "C:\Miniconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None
```

<details>

<summary>Click for full log</summary>

Build started
ECHO %PYTHON_VERSION% %MINICONDA%
3.5 C:\Miniconda3
git clone -q https://github.com/google/neuroglancer.git C:\projects\neuroglancer
git fetch -q origin +refs/pull/153/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
set PATH=%MINICONDA%;%MINICONDA%\Scripts;%PATH%
conda config --set always_yes yes --set changeps1 no
conda update -q conda
Solving environment: ...working... done
## Package Plan ##
  environment location: C:\Miniconda3
  added / updated specs: 
    - conda
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    certifi-2019.6.16          |           py37_1         156 KB
    libarchive-3.3.3           |       h0643e63_5         1.4 MB
    conda-package-handling-1.3.11|           py37_0         279 KB
    zstd-1.3.7                 |       h508b16e_0         436 KB
    openssl-1.1.1c             |       he774522_1         5.1 MB
    xz-5.2.4                   |       h2fa13f4_4         782 KB
    zlib-1.2.11                |       h62dcd97_3         112 KB
    libiconv-1.15              |       hc4a7105_7         654 KB
    libxml2-2.9.9              |       h464c3ec_0         2.5 MB
    tqdm-4.32.1                |             py_0          48 KB
    bzip2-1.0.8                |       he774522_0         131 KB
    ca-certificates-2019.5.15  |                0         166 KB
    lzo-2.10                   |       h00ab751_2         136 KB
    conda-4.7.10               |           py37_0         3.0 MB
    lz4-c-1.8.1.2              |       h2fa13f4_0         213 KB
    python-libarchive-c-2.8    |          py37_11          23 KB
    ------------------------------------------------------------
                                           Total:        15.1 MB
The following NEW packages will be INSTALLED:
    bzip2:                  1.0.8-he774522_0  
    conda-package-handling: 1.3.11-py37_0     
    libarchive:             3.3.3-h0643e63_5  
    libiconv:               1.15-hc4a7105_7   
    libxml2:                2.9.9-h464c3ec_0  
    lz4-c:                  1.8.1.2-h2fa13f4_0
    lzo:                    2.10-h00ab751_2   
    python-libarchive-c:    2.8-py37_11       
    tqdm:                   4.32.1-py_0       
    xz:                     5.2.4-h2fa13f4_4  
    zlib:                   1.2.11-h62dcd97_3 
    zstd:                   1.3.7-h508b16e_0  
The following packages will be UPDATED:
    ca-certificates:        2018.03.07-0       --> 2019.5.15-0      
    certifi:                2018.11.29-py37_0  --> 2019.6.16-py37_1 
    conda:                  4.5.12-py37_0      --> 4.7.10-py37_0    
    openssl:                1.1.1a-he774522_0  --> 1.1.1c-he774522_1
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
conda info -a
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<
    Traceback (most recent call last):
      File "C:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Miniconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Miniconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Miniconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Miniconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\Miniconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <module>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\Miniconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\Miniconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\Miniconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\Miniconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\Miniconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: LoadLibrary() argument 1 must be str, not None
`$ C:\Miniconda3\Scripts\conda-script.py info -a`
An unexpected error has occurred. Conda has prepared the above report.
Upload successful.
Command exited with code 1

<details>

**Comment by msarahan** [comment]
https://github.com/conda/conda/issues/8836#issuecomment-506423013

**Comment by stuarteberg** [comment]
Doh.  Sorry I didn't [find that myself](https://www.google.com/search?q=conda+TypeError%3A+LoadLibrary%28%29+argument+1+must+be+str%2C+not+None).  Next time I'll try a little harder...

Thanks @msarahan!

PS -- Whoa, that guy is a serious prick, isn't he?  Hang in there...

**Comment by msarahan** [comment]
Thanks.  I definitely understand why people are frustrated - it is no fun to waste time fixing things that already "work" (though they may be too slow, missing features, or buggy in other ways).  It would be nice if people were a bit less entitled and angry, but it is what it is.  We'll keep working to make things better.

**Comment by msarahan** [comment]
I think one good fix for git bash might be to run `conda init bash` from anaconda prompt.  That should hopefully put the right stuff into place for conda to load itself correctly.

**Comment by andrew-schweitzer-analog** [comment]
I'm getting a similar error on windows. I don't *think* I have any PATH modifications, but I'm going to re-install miniconda to prove it. I have tox & tox-conda installed in both base and another dev env.

* When I run ` tox` from the dev-env I get `TypeError: LoadLibrary() argument 1 must be str, not None`. 
* When I run `conda run -n base tox` from dev env, the error was _gone_. 
* `conda init` did not remove the error. 
* `conda install conda=4.6.14` in base did not remove the error


- Should I be installing from here: https://repo.continuum.io/pkgs/misc/previews/miniconda/4.7.10/? 
- Do I need to run `conda init` after installing miniconda? 
- Should I be cleaning my system more aggressively than running the miniconda uninstaller? 
- Is there something else I should do to better diagnose what's happening on my system? 

Thanks,

Andy

**Comment by msarahan** [comment]
I don't have any experience with tox or tox-conda, so I can't make any guesses there.

* `conda run` is specially written to add PATH entries before calling conda at all.  `conda` is generally $PREFIX/condabin/conda.bat, not actually conda.exe.  People have trouble when they call $PREFIX/scripts/conda.exe because it does not do any PATH addition.
* conda init alone doesn't remove the error.  It sets up registry entries or .profile/.bashrc stuff.  You would need to restart the shell or source the file to update it.  Have you done that?
* miniconda 4.7.10 is officially released, and you need not download it from the preview link.  The installers are identical, though.
* Running `conda init` is not mandatory.  It depends on your use case.  If you only use Anaconda Prompt, Anaconda Powershell Prompt, Navigator, or the other start menu shortcuts, you don't need it at all.  If you want to open cmd.exe, powershell, or git bash, and have conda "just work" without sourcing or calling anything else, then yes.  Bear in mind that `conda init` takes an argument - see its help dialog.  If you run only `conda init` on windows, it defaults to only setting up cmd.exe, which might be why you think it isn't doing anything.
* The uninstaller should remove registry entries that the installer creates, but it isn't always 100% effective.  Since `conda init` is so global, we have seen old installations' registry entries pointing at conda that doesn't exist.  This shows an error when cmd.exe is started up about "path not found."  This is easy to fix - run Anaconda Prompt for your current installation, and run `conda init` from that prompt.  It will overwrite the old registry entry.
* We'll better document this stuff, but the fact that PATH is affecting us so badly is really an indicator that we need a better way to do things.  I think as long as you are aware of PATH as a potential source of problems, you can make much more sense of errors.  The $PREFIX/Library/bin folder on windows is where almost all of our libraries (except the msys2 stuff) live.  When that folder is not on PATH, things probably won't work.  That folder mostly should be added to PATH by activation, not manually.

**Comment by msarahan** [comment]
The latest build of python-libarchive-c improves a patch that helps it load libarchive on windows: https://github.com/AnacondaRecipes/python-libarchive-c-feedstock/pull/3

If you update to python-libarchive-c build 12, you should no longer see any problems.  I'll close this issue, but we can reopen it if it is still a problem.

**Comment by andrew-schweitzer-analog** [comment]
Thanks! `conda update python-libarchive-c` made problem go away. 

What should I tell users about how to achieve this blessed state? Will a new install from default installer (https://docs.conda.io/en/latest/miniconda.html) work? Does everyone need to run `conda update python-libarchive-c` or just existing installs? Is there a guess (very approximate is fine) on when this would be rolled into new conda version? 

I can/will do at least one of those experiments myself, but several might be required and you might just know, so I thought I'd ask.

Thanks,

Andy

**Comment by msarahan** [comment]
New miniconda will include it.  This is not a change to conda, except that it is an (indirect) dependency of conda, via conda-package-handling.  We'll be releasing a new conda version for other bugs soon.

`conda update python-libarchive-c` should hopefully fix existing installs.

**Comment by andrew-schweitzer-analog** [comment]
FYI, I just ran installs from https://repo.continuum.io/pkgs/misc/previews/miniconda/4.7.10/ and https://docs.conda.io/en/latest/miniconda.html. Neither had the updated `py37_12` version of `python-libarchive-c`. I will recommend windows users just update that package for now. 

Thanks

Andy

**Comment by msarahan** [comment]
That's correct.  Miniconda 4.7.10 was released prior to this patch being developed.
