### ISSUE TITLE
Failed to recognize wheels in ubuntu xenial when python=3.7.4

### ISSUE THREAD

**Issue by wjsi** [conda/conda#9085]
When running tests under Travis CI with miniconda (https://travis-ci.org/mars-project/mars/jobs/570692953), we discover that when python version is 3.7.4, installation of ``coverage`` via PyPI failed. The error never occurs under python=3.7.3.

Firstly, ``coverage`` has its ``manylinux1`` wheels for ``x86_64``, however, ``pip`` in anaconda seems to skip this wheel and install from the source package. Secondly, when trying to install from the source package, the same error as #9084 occurs.

Install script for conda:
```bash
curl -s -o miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash miniconda.sh -b -p $HOME/miniconda && rm miniconda.sh
$HOME/miniconda/bin/conda create --quiet --yes -n test python=3.7 virtualenv gevent psutil \
    pyyaml nomkl libopenblas lz4
```

Error log
```
$ if [[ "$PYTHON" =~ "2" ]]; then pip install --upgrade pip\<19 setuptools\<40.7 wheel coverage; else pip install --upgrade pip\<19.2.2 setuptools wheel coverage; fi
20160609
Collecting pip<19.2.2
  Downloading https://files.pythonhosted.org/packages/62/ca/94d32a6516ed197a491d17d46595ce58a83cbb2fca280414e57cd86b84dc/pip-19.2.1-py2.py3-none-any.whl (1.4MB)
     |████████████████████████████████| 1.4MB 1.3MB/s 
Requirement already up-to-date: setuptools in /home/travis/miniconda/envs/test/lib/python3.7/site-packages (41.0.1)
Requirement already up-to-date: wheel in /home/travis/miniconda/envs/test/lib/python3.7/site-packages (0.33.4)
Collecting coverage
  Downloading https://files.pythonhosted.org/packages/85/d5/818d0e603685c4a613d56f065a721013e942088047ff1027a632948bdae6/coverage-4.5.4.tar.gz (385kB)
     |████████████████████████████████| 389kB 37.6MB/s 
Building wheels for collected packages: coverage
  Building wheel for coverage (setup.py) ... error
  ERROR: Complete output from command /home/travis/miniconda/envs/test/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-5pc4_6l3/coverage/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-5bjbanpb --python-tag cp37:
  ERROR: 20160609
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/coverage
  copying coverage/backunittest.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/report.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/cmdline.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/python.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/xmlreport.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/summary.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/annotate.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/misc.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/plugin.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/pytracer.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/parser.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/pickle2json.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/__main__.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/debug.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/multiproc.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/config.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/files.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/version.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/execfile.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/data.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/templite.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/env.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/collector.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/bytecode.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/control.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/plugin_support.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/__init__.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/html.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/results.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/backward.py -> build/lib.linux-x86_64-3.7/coverage
  copying coverage/phystokens.py -> build/lib.linux-x86_64-3.7/coverage
  creating build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/jquery.tablesorter.min.js -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/keybd_open.png -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/jquery.min.js -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/jquery.ba-throttle-debounce.min.js -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/keybd_closed.png -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/jquery.hotkeys.js -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/index.html -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/style.css -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/coverage_html.js -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/jquery.isonscreen.js -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  copying coverage/htmlfiles/pyfile.html -> build/lib.linux-x86_64-3.7/coverage/htmlfiles
  creating build/lib.linux-x86_64-3.7/coverage/fullcoverage
  copying coverage/fullcoverage/encodings.py -> build/lib.linux-x86_64-3.7/coverage/fullcoverage
  running build_ext
  building 'coverage.tracer' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/coverage
  creating build/temp.linux-x86_64-3.7/coverage/ctracer
  gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/envs/test/include/python3.7m -c coverage/ctracer/datastack.c -o build/temp.linux-x86_64-3.7/coverage/ctracer/datastack.o
  gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/envs/test/include/python3.7m -c coverage/ctracer/filedisp.c -o build/temp.linux-x86_64-3.7/coverage/ctracer/filedisp.o
  gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/envs/test/include/python3.7m -c coverage/ctracer/module.c -o build/temp.linux-x86_64-3.7/coverage/ctracer/module.o
  gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/travis/miniconda/envs/test/include/python3.7m -c coverage/ctracer/tracer.c -o build/temp.linux-x86_64-3.7/coverage/ctracer/tracer.o
  gcc -pthread -shared -L/home/travis/miniconda/envs/test/lib -Wl,-rpath=/home/travis/miniconda/envs/test/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/coverage/ctracer/datastack.o build/temp.linux-x86_64-3.7/coverage/ctracer/filedisp.o build/temp.linux-x86_64-3.7/coverage/ctracer/module.o build/temp.linux-x86_64-3.7/coverage/ctracer/tracer.o -o build/lib.linux-x86_64-3.7/coverage/tracer.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/backunittest.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/report.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/cmdline.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/python.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/xmlreport.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/summary.py -> build/bdist.linux-x86_64/wheel/coverage
  creating build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/jquery.tablesorter.min.js -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/keybd_open.png -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/jquery.min.js -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/jquery.ba-throttle-debounce.min.js -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/keybd_closed.png -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/jquery.hotkeys.js -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/index.html -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/style.css -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/coverage_html.js -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/jquery.isonscreen.js -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/htmlfiles/pyfile.html -> build/bdist.linux-x86_64/wheel/coverage/htmlfiles
  copying build/lib.linux-x86_64-3.7/coverage/annotate.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/misc.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/plugin.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/pytracer.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/tracer.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/parser.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/pickle2json.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/__main__.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/debug.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/multiproc.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/config.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/files.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/version.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/execfile.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/data.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/templite.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/env.py -> build/bdist.linux-x86_64/wheel/coverage
  creating build/bdist.linux-x86_64/wheel/coverage/fullcoverage
  copying build/lib.linux-x86_64-3.7/coverage/fullcoverage/encodings.py -> build/bdist.linux-x86_64/wheel/coverage/fullcoverage
  copying build/lib.linux-x86_64-3.7/coverage/collector.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/bytecode.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/control.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/plugin_support.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/__init__.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/html.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/results.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/backward.py -> build/bdist.linux-x86_64/wheel/coverage
  copying build/lib.linux-x86_64-3.7/coverage/phystokens.py -> build/bdist.linux-x86_64/wheel/coverage
  running install_egg_info
  running egg_info
  writing coverage.egg-info/PKG-INFO
  writing dependency_links to coverage.egg-info/dependency_links.txt
  writing entry points to coverage.egg-info/entry_points.txt
  writing top-level names to coverage.egg-info/top_level.txt
  reading manifest file 'coverage.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files found matching 'ci/appveyor.token'
  no previously-included directories found matching 'doc/_build'
  no previously-included directories found matching 'tests/eggsrc/build'
  no previously-included directories found matching 'tests/eggsrc/dist'
  no previously-included directories found matching 'tests/eggsrc/*.egg-info'
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  writing manifest file 'coverage.egg-info/SOURCES.txt'
  Copying coverage.egg-info to build/bdist.linux-x86_64/wheel/coverage-4.5.4-py3.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-5pc4_6l3/coverage/setup.py", line 213, in <module>
      main()
    File "/tmp/pip-install-5pc4_6l3/coverage/setup.py", line 203, in main
      setup(**setup_args)
    File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/travis/miniconda/envs/test/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/travis/miniconda/envs/test/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/travis/miniconda/envs/test/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/travis/miniconda/envs/test/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 179, in get_tag
      assert tag == supported_tags[0], "%s != %s" % (tag, supported_tags[0])
  AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for coverage
  Running setup.py clean for coverage
Failed to build coverage
Installing collected packages: pip, coverage
  Found existing installation: pip 19.1.1
    Uninstalling pip-19.1.1:
      Successfully uninstalled pip-19.1.1
  Running setup.py install for coverage ... done
Successfully installed coverage-4.5.4 pip-19.2.1
```

**Comment by jjhelmus** [comment]
There are some issues with our build of Python 3.7.4.  We will be fixing the issue and releasing updated packages shortly.  Sorry for any inconveniences this has caused.

**Comment by jjhelmus** [comment]
Thanks for the report.  The root of this issue was also reported in ContinuumIO/anaconda-issues#11195.  I'm closing this issue so that there is a single issue tracking the problem.  Updates on the fix will be posted to that issue.
