### ISSUE TITLE
Environment creation broken for Python 3.7.4 on Linux

### ISSUE THREAD

**Issue by jlafon** [conda/conda#9089]
### Current Behavior

An error occurs when creating a new environment with pip requirements.

### Steps to Reproduce
Using this environment.yml file:
```
dependencies:
- python=3.7.4
- pip:
  - django==2.2.4
name: user_env
```

Run the command: ```conda env create -f environment.yml --force```

```
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/testuser/miniconda/lib/python3.7/site-packages/conda/exceptions.py", line 819, in __call__
        return func(*args, **kwargs)
      File "/home/testuser/miniconda/lib/python3.7/site-packages/conda_env/cli/main.py", line 74, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/testuser/miniconda/lib/python3.7/site-packages/conda_env/cli/main_update.py", line 126, in execute
        installer.install(prefix, specs, args, env)
      File "/home/testuser/miniconda/lib/python3.7/site-packages/conda_env/installers/pip.py", line 40, in _pip_install_via_requirements
        args, pip_version = pip_args(prefix)
      File "/home/testuser/miniconda/lib/python3.7/site-packages/conda_env/pip_util.py", line 35, in pip_args
        if int(major_ver) >= 6:
    ValueError: invalid literal for int() with base 10: 'pip'

`$ /home/testuser/miniconda/bin/conda-env update -f /home/testuser/environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/home/testuser/miniconda
                     PATH=/home/testuser/miniconda/envs/user_env/bin:/home/testuser/miniconda/bi
                          n:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /home/testuser/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/testuser/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/testuser/miniconda/pkgs
                          /home/testuser/.conda/pkgs
       envs directories : /home/testuser/miniconda/envs
                          /home/testuser/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.9.119-44.140.amzn1.x86_64 ubuntu/14.04 glibc/2.19
                UID:GID : 502:502
             netrc file : None
           offline mode : False

```

Note: It looks like the problem is a print() statement in `lib/python3.7/_sysconfigdata_m_linux_x86_64-linux-gnu.py`. 

## Expected Behavior

A new environment should be created

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
  active environment : None
       user config file : /home/testuser/.condarc
 populated config files : 
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : /home/testuser/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/testuser/miniconda/pkgs
                          /home/testuser/.conda/pkgs
       envs directories : /home/testuser/miniconda/envs
                          /home/testuser/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.21.0 CPython/3.7.1 Linux/4.9.119-44.140.amzn1.x86_64 ubuntu/14.04 glibc/2.19
                UID:GID : 502:502
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/testuser/miniconda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2018.03.07                    0    defaults
certifi                   2018.11.29               py37_0    defaults
cffi                      1.11.5           py37he75722e_1    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.5.12                   py37_0    defaults
conda-env                 2.6.0                         1    defaults
cryptography              2.4.2            py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1a               h7b6447c_0    defaults
pip                       18.1                     py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 18.0.0                   py37_0    defaults
pysocks                   1.6.8                    py37_0    defaults
python                    3.7.1                h0371630_7    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.21.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                40.6.3                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.26.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
urllib3                   1.24.1                   py37_0    defaults
wheel                     0.32.3                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by soapy1** [comment]
The newest version of conda 4.7.11. Please update as this problem is probably solved in the newer release
