### ISSUE TITLE
Conda craps out on fresh install

### ISSUE THREAD

**Issue by ozooha** [conda/conda#9094]
I did a fresh install on Win 7 of Anaconda3 2019.7 64 bit and opened the prompt and did a "conda info" and got this:
`
(base) C:\>conda info

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 80, in do_call

        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\cli\main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 9, in <module>
        from .package_cache_data import PackageCacheData
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <m
odule>
        from conda_package_handling.api import InvalidArchiveError
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_package_handling\api.py", line 3, in <modul
e>
        from libarchive.exception import ArchiveError as _LibarchiveArchiveError
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\__init__.py", line 1, in <module>
        from .entry import ArchiveEntry
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\entry.py", line 6, in <module>
        from . import ffi
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\site-packages\libarchive\ffi.py", line 48, in <module>
        libarchive = ctypes.cdll.LoadLibrary(libarchive_path)
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 434, in LoadLibrary
        return self._dlltype(name)
      File "C:\Users\rx95082\AppData\Local\Continuum\anaconda3\lib\ctypes\__init__.py", line 356, in __init__
        self._handle = _dlopen(self._name, mode)
    OSError: [WinError 193] %1 is not a valid Win32 application

`$ C:\Users\rx95082\AppData\Local\Continuum\anaconda3\Scripts\conda-script.py info`

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]:

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false

`

**Comment by soapy1** [comment]
It seems like maybe you have a win 32 system from this error message `OSError: [WinError 193] %1 is not a valid Win32 application`. Could you verify if your system is win32 or win64. If it is indeed win32, please use the windows 32 bit installers.

**Comment by ozooha** [comment]
> It seems like maybe you have a win 32 system from this error message `OSError: [WinError 193] %1 is not a valid Win32 application`. Could you verify if your system is win32 or win64. If it is indeed win32, please use the windows 32 bit installers.

Below are my screen shots:

- Jupyter python terminal

![Capture](https://user-images.githubusercontent.com/16407660/63111299-63466e00-bf5b-11e9-9168-e6c625366c9a.PNG)

- MS Win7 Specs

![Capture2](https://user-images.githubusercontent.com/16407660/63111324-6fcac680-bf5b-11e9-9250-6bc75ee1aa6c.PNG)

So overall its a 64-bit installation and I do not get it as to why it gives me a 32-bit error.
I hope this help.
Thanks.

**Comment by flflow** [comment]
Same issue! Windows 10 1903 x64, fresh installation - conda is completely broken on all versions of anaconda distribution! Before conda 4.7 I have this error
![2019-08-20 16 54 20](https://user-images.githubusercontent.com/32948829/63337521-4fd84000-c36b-11e9-8d06-8f37f24779ab.png)
In conda 4.7 i have error same as op.

**Comment by stevenvariend** [comment]
I'm currently having the same issue - saw the link below on google groups - have tried different versions, 32 bit and 64 bit along with mini conda - all throwing the same issue - Can this be resolved by Anaconda?

https://groups.google.com/a/continuum.io/g/anaconda/c/ditYAgIVVUc?pli=1
