### ISSUE TITLE
Anaconda navigator doesn't want to launch

### ISSUE THREAD

**Issue by Mohamedebouguerra** [conda/conda#9103]
Whenever  want to launch the Anaconda navigator an error shows up as the fellowing

Traceback (most recent call last):
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 138, in start_app
    window = run_app(splash)
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 64, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 163, in __init__
    self.api = AnacondaAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2127, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 90, in __init__
    self._client_api = ClientAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 638, in ClientAPI
    CLIENT_API = _ClientAPI()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 93, in __init__
    self.reload_binstar_client()
  File "C:\Users\hp\Anaconda3\lib\site-packages\anaconda_navigator\api\client_api.py", line 312, in reload_binstar_client
    log_level=logging.NOTSET
TypeError: get_server_api() got an unexpected keyword argument 'config'

What should i do please ?

**Comment by xiaoxiaozhangx** [comment]
ME TOO ,SO WHAT SHOULD I DO/

**Comment by xiaoxiaozhangx** [comment]
uninstall----
install,chooose just for me user,and do not choose auto configure path.so after install ,you should set the path ,add 3 colums, then , it will be ok
