### ISSUE TITLE
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

### ISSUE THREAD

**Issue by KelSolaar** [conda/conda#9117]
## Current Behavior

Hi,

I'm experiencing certificate verification failures on _Azure_ since a little while as per this issue: https://github.com/imageio/imageio/issues/461 and now on _Travis-ci_ . I created a minimal repo that reproduces the issue: https://github.com/KelSolaar/CertificateRamblings

I'm not exactly sure if it is 100% Conda related but changing to Pip based installation fixed the issue on _Azure_ so I guess there is currently something wrong with Conda on Python 2.7.

### Steps to Reproduce

The code to reproduce the issue is here: https://github.com/KelSolaar/CertificateRamblings, it really boils down to using `urlretrieve` with a secure url resulting in the following output:

```
======================================================================
ERROR: test_certificate_issues (test_certificate_issues.TestCertificateIssues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/KelSolaar/CertificateRamblings/certificate_ramblings/test_certificate_issues.py", line 11, in test_certificate_issues
    filename=tempfile.mktemp())
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/httplib.py", line 1055, in endheaders
    self._send_output(message_body)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/httplib.py", line 893, in _send_output
    self.send(msg)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/httplib.py", line 855, in send
    self.connect()
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/httplib.py", line 1280, in connect
    server_hostname=server_hostname)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/ssl.py", line 369, in wrap_socket
    _context=self)
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/ssl.py", line 599, in __init__
    self.do_handshake()
  File "/home/travis/miniconda/envs/certificate-ramblings-test/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
```

The full build job log is here: https://travis-ci.com/KelSolaar/CertificateRamblings/builds/123585083

## Expected Behavior

Being able to download from secure urls without certificate verification failure.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:
               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 2.7.13.final.0
       requests version : 2.14.2
       root environment : /home/travis/miniconda  (writable)
    default environment : /home/travis/miniconda/envs/certificate-ramblings-test
       envs directories : /home/travis/miniconda/envs
                          /home/travis/.conda/envs
          package cache : /home/travis/miniconda/pkgs
                          /home/travis/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.14.2 CPython/2.7.13 Linux/4.15.0-1028-gcp debian/stretch/sid glibc/2.23    
                UID:GID : 2000:2000
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
No Output
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/travis/miniconda/envs/certificate-ramblings-test:
#
_libgcc_mutex             0.1                        main    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py27_1    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
nose                      1.3.7                    py27_2    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
pip                       19.1.1                   py27_0    defaults
python                    2.7.16               h8b3fad2_3    defaults
readline                  7.0                  h7b6447c_5    defaults
setuptools                41.0.1                   py27_0    defaults
six                       1.12.0                    <pip>
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
wheel                     0.33.4                   py27_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```
</p></details>

**Comment by mingwandroid** [comment]
Closed. This is really old software so you should expects certificates to be out of date. Please update to the latest versus if everything

**Comment by KelSolaar** [comment]
@mingwandroid : Why are you closing the issue, it is certainly not fixed and you could have at least waited for an update from my end.

I forgot to update Miniconda when building the reproduction repository but the certificate verification still fails with recent Conda versions: https://travis-ci.com/KelSolaar/CertificateRamblings/builds/123617117

```
$ conda info
     active environment : certificate-ramblings-test
    active env location : /home/travis/miniconda/envs/certificate-ramblings-test
            shell level : 1
       user config file : /home/travis/.condarc
 populated config files : 
          conda version : 4.7.11
    conda-build version : not installed
         python version : 2.7.16.final.0
       virtual packages : 
       base environment : /home/travis/miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/travis/miniconda/pkgs
                          /home/travis/.conda/pkgs
       envs directories : /home/travis/miniconda/envs
                          /home/travis/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/2.7.16 Linux/4.15.0-1028-gcp ubuntu/16.04.5 glibc/2.23
                UID:GID : 2000:2000
             netrc file : None
           offline mode : False
```

**Comment by almarklein** [comment]
@mingwandroid could this please be re-opened? @KelSolaar put in quite some effort to trace the issue down to conda, so this deserves attention IMO.

**Comment by mingwandroid** [comment]
This is fixed. Please update to python 2.7.16 build #4.

**Comment by KelSolaar** [comment]
Thanks @mingwandroid, I just re-kicked the build and it went through by picking-up `python-2.7.16 - h8b3fad2_4`.

**Comment by mingwandroid** [comment]
Thanks for the confirmation and sorry about the bug!

**Comment by mingwandroid** [comment]
We will more aggressively close bugs when we have little time guys, sorry! When I see really old versions of stuff being used I *will* close them without prejudice until our workload reduces.

**Comment by KelSolaar** [comment]
All good @mingwandroid, felt rough :) Might be worth adding a visible disclaimer in the issue template: https://github.com/conda/conda/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md
