### ISSUE TITLE
'<' not supported between instances of 'NoneType' and 'str'

### ISSUE THREAD

**Issue by jadhosn** [conda/conda#9141]
### Steps to Reproduce

```
conda create env -n azureml python=3.6 anaconda
conda activate azureml
pip install --upgrade azureml-sdk[notebooks,contrib]
conda list
```

## Expected Behavior

I would expect a list of all the environment libraries. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
  active environment : azureml
    active env location : C:\ProgramData\Anaconda3\envs\azureml
            shell level : 1
       user config file : C:\Users\jaboulhosn\.condarc
 populated config files : C:\Users\jaboulhosn\.condarc
          conda version : 4.7.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.2
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\jaboulhosn\.conda\pkgs
                          C:\Users\jaboulhosn\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\jaboulhosn\.conda\envs
                          C:\Users\jaboulhosn\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\jaboulhosn\.condarc <==
ssl_verify: False
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
>>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 133, in iter_records
        return itervalues(self._prefix_records)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 162, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 72, in load
        self._load_site_packages()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 277, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 257, in read_python_record
        paths_tups = pydist.get_paths()
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 269, in get_paths
        records = sorted(concatv(records, ((pf, None, None) for pf in missing_pyc_files)))
    TypeError: '<' not supported between instances of 'NoneType' and 'str'

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py list --show-channel-urls`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_BAT=C:\ProgramData\Anaconda3\condabin\conda.bat
        CONDA_DEFAULT_ENV=azureml
                CONDA_EXE=C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\ProgramData\Anaconda3\condabin\..\Scripts\conda.exe"
             CONDA_PREFIX=C:\ProgramData\Anaconda3\envs\azureml
    CONDA_PROMPT_MODIFIER=(azureml)
         CONDA_PYTHON_EXE=C:\ProgramData\Anaconda3\python.exe
               CONDA_ROOT=C:\ProgramData\Anaconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\jaboulhosn
                     PATH=C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Library\mingw-w64\bi
                          n;C:\ProgramData\Anaconda3\Library\usr\bin;C:\ProgramData\Anaconda3\Li
                          brary\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\bi
                          n;C:\ProgramData\Anaconda3\envs\azureml;C:\ProgramData\Anaconda3\envs\
                          azureml\Library\mingw-w64\bin;C:\ProgramData\Anaconda3\envs\azureml\Li
                          brary\usr\bin;C:\ProgramData\Anaconda3\envs\azureml\Library\bin;C:\Pro
                          gramData\Anaconda3\envs\azureml\Scripts;C:\ProgramData\Anaconda3\envs\
                          azureml\bin;C:\ProgramData\Anaconda3\condabin;C:\Program Files
                          (x86)\Common
                          Files\Oracle\Java\javapath;C:\ProgramData\DockerDesktop\version-
                          bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program
                          Files\Microsoft MPI\Bin;C:\Informatica\10.1.0\clients\tools\datadirect
                          ;C:\Informatica\10.1.0\clients\tools\odbcdrv;C:\Informatica\10.1.0\cli
                          ents\tools\jdbcdrv;C:\Informatica\10.1.0\clients\tools\sharedlibs;C:\w
                          indows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System3
                          2\WindowsPowerShell\v1.0;C:\Program Files (x86)\IBM\Client
                          Access\Emulator;C:\Program Files (x86)\IBM\Client
                          Access\Shared;C:\Program Files (x86)\IBM\Client Access;C:\Program
                          Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Microsoft
                          SQL Server\120\DTS\Binn;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\120\Tools\Binn\ManagementStudio;C:\Program Files
                          (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft
                          SQL Server\120\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\120\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\Client
                          SDK\ODBC\130\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\140\Tools\Binn;C:\Program Files (x86)\Microsoft SQL
                          Server\140\DTS\Binn;C:\Program Files (x86)\Microsoft SQL Server\140\To
                          ols\Binn\ManagementStudio;C:\Users\jaboulhosn\.dnx\bin;C:\Program
                          Files\Microsoft DNX\Dnvm;C:\Program Files\Microsoft SQL
                          Server\130\Tools\Binn;C:\Program Files\Git\cmd;C:\Program
                          Files\Intel\WiFi\bin;C:\Program Files\Common Files\Intel\WirelessCommo
                          n;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\S
                          ystem32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\ProgramD
                          ata\Anaconda3\Scripts;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda
                          3\Library\bin;C:\Users\jaboulhosn\AppData\Local\Microsoft\WindowsApps;
                          C:\Users\jaboulhosn\AppData\Local\GitHubDesktop\bin;C:\Users\jaboulhos
                          n\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64;C:\Users\jaboulhosn
                          \AppData\Local\Microsoft\WindowsApps;C:\scripts;C:\Microsoft VS
                          Code\bin
             PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                          PowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL
                          Server\120\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : azureml
    active env location : C:\ProgramData\Anaconda3\envs\azureml
            shell level : 1
       user config file : C:\Users\jaboulhosn\.condarc
 populated config files : C:\Users\jaboulhosn\.condarc
          conda version : 4.7.11
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       virtual packages : __cuda=9.2
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\jaboulhosn\.conda\pkgs
                          C:\Users\jaboulhosn\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\jaboulhosn\.conda\envs
                          C:\Users\jaboulhosn\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by soapy1** [comment]
Fixed by https://github.com/conda/conda/pull/9132
