### ISSUE TITLE
conda-env example environment.yml file doesn't work

### ISSUE THREAD

**Issue by mjarosie** [conda/conda#9161]
## Current Behavior
conda-env [README](https://github.com/conda/conda/tree/master/conda_env#environment-file-example) specifies an example `environment.yml` file:

```
name: stats
channels:
  - javascript
dependencies:
  - python=3.4   # or 2.7 if you are feeling nostalgic
  - bokeh=0.9.2
  - numpy=1.9.*
  - nodejs=0.10.*
  - flask
  pip:
    - Flask-Testing
```

after copying it to a file `test.yml` and running `conda env create -f test.yml` the output is:

```
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main.py", line 73, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\cli\main_create.py", line 77, in execute
        directory=os.getcwd())
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\__init__.py", line 40, in detect
        if spec.can_handle():
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\specs\yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 144, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda_env\env.py", line 129, in from_yaml
        data = yaml_load_standard(yamlstr)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\common\serialize.py", line 76, in yaml_load_standard
        return yaml.load(string, Loader=yaml.Loader, version="1.2")
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\main.py", line 640, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\constructor.py", line 102, in get_single_data
        node = self.composer.get_single_node()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 75, in get_single_node
        document = self.compose_document()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 96, in compose_document
        node = self.compose_node(None, None)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 132, in compose_node
        node = self.compose_mapping_node(anchor)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 194, in compose_mapping_node
        item_value = self.compose_node(node, item_key)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 130, in compose_node
        node = self.compose_sequence_node(anchor)
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\composer.py", line 162, in compose_sequence_node
        while not self.parser.check_event(SequenceEndEvent):
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 144, in check_event
        self.current_event = self.state()
      File "C:\ProgramData\Anaconda3\lib\site-packages\ruamel_yaml\parser.py", line 500, in parse_block_sequence_entry
        token.id, token.start_mark)
    ruamel_yaml.parser.ParserError: while parsing a block collection
      in "<unicode string>", line 5, column 3:
          - python=3.4   # or 2.7 if you a ...
          ^ (line: 5)
    expected <block end>, but found '?'
      in "<unicode string>", line 10, column 3:
          pip:
          ^ (line: 10)
```

## Expected Behavior
I'd expect the environment to be created. I have spend quite a while figuring out what's wrong with my .yml file which was based on the example.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\macie\.condarc
 populated config files : C:\Users\macie\.condarc
          conda version : 4.7.11
    conda-build version : 3.17.6
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.1
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\macie\.conda\pkgs
                          C:\Users\macie\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\macie\.conda\envs
                          C:\ProgramData\Anaconda3\envs
                          C:\Users\macie\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.6.8 Windows/10 Windows/10.0.18362
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

**Comment by mjarosie** [comment]
Made it work by making `pip` an element of the list:

```
name: stats
channels:
  - javascript
dependencies:
  - python=3.4   # or 2.7 if you are feeling nostalgic
  - bokeh=0.9.2
  - numpy=1.9.*
  - nodejs=0.10.*
  - flask
  - pip: # Note the hyphen here.
    - Flask-Testing
```
