### ISSUE TITLE
Conda is messed up

### ISSUE THREAD

**Issue by Arktius** [conda/conda#9237]
Hi! I've somehow messed up my conda system. I get this warning when working with conda:

```
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
```

I then wanted to update conda as it was suggested in the console with this command 
`conda update -n base -c defaults conda`
but I got this error:

```
PackagesNotFoundError: The following packages are not available from current channels:

  - pkgs/free/win-64::numba==0.34.0=np112py35_0 -> llvmlite=0.19
  - pkgs/free/win-64::tensorflow-gpu==1.1.0=np112py35_0 -> cudnn=6.0
```
When I try to update either numba or tensorflow, I'll get the same errors. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
   active environment : None
       user config file : C:\Users\Admin\.condarc
 populated config files : C:\Users\Admin\.condarc
          conda version : 4.7.5
    conda-build version : 2.0.2
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\Admin\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Admin\Anaconda3\pkgs
                          C:\Users\Admin\.conda\pkgs
                          C:\Users\Admin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Admin\Anaconda3\envs
                          C:\Users\Admin\.conda\envs
                          C:\Users\Admin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda update --all`</code></summary><p>

```
  C:\WINDOWS\system32>conda update --all
WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - pkgs/free/win-64::numba==0.34.0=np112py35_0 -> llvmlite=0.19
  - pkgs/free/win-64::tensorflow-gpu==1.1.0=np112py35_0 -> cudnn=6.0

Current channels:

  - https://conda.anaconda.org/anaconda-fusion/win-64
  - https://conda.anaconda.org/anaconda-fusion/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\Admin\.condarc <==
ssl_verify: True
channels:
  - anaconda-fusion
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 142, in execute
        show_channel_urls=context.show_channel_urls)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 80, in print_packages
        show_channel_urls=show_channel_urls)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\cli\main_list.py", line 45, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 130, in iter_records
        return itervalues(self._prefix_records)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 159, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 72, in load
        self._load_site_packages()
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\core\prefix_data.py", line 274, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\gateways\disk\read.py", line 249, in read_python_record
        pydist = PythonDistribution.init(prefix_path, anchor_file, python_version)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 90, in init
        return PythonEggInfoDistribution(anchor_full_path, python_version, sp_reference)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 401, in __init__
        super(PythonEggInfoDistribution, self).__init__(anchor_full_path, python_version)
      File "C:\Users\Admin\Anaconda3\lib\site-packages\conda\common\pkg_formats\python.py", line 104, in __init__
        raise RuntimeError("Path not found: %s" % anchor_full_path)
    RuntimeError: Path not found: C:\Users\Admin\Anaconda3\Lib\site-packages\Sphinx-1.4.6-py3.5.egg\EGG-INFO

`$ C:\Users\Admin\Anaconda3\Scripts\conda-script.py list --show-channel-urls`

  environment variables:
                AMDRMPATH=C:\Program Files\AMD\RyzenMaster\
                 CIO_TEST=<not set>
               CONDA_ROOT=C:\Users\Admin\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
                 HOMEPATH=\Users\Admin
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\mic
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.0\libnvvp;C:\Program Files (x86)\Microsoft Visual
                          Studio 14.0\VC\bin\x86_amd64;F:\ImageMagick-7.0.8-Q16;C:\Program Files
                          (x86)\Common Files\Intel\Shared Libraries\redist\intel64\compiler;C:\P
                          rogramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Wind
                          ows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Progr
                          am Files (x86)\Common Files\Acronis\SnapAPI\;E:\Matlab\runtime\win64;E
                          :\Matlab\bin;C:\Program Files (x86)\Calibre2\;C:\Program Files
                          (x86)\EaseUS\Todo Backup\bin;E:\Matlab\polyspace\bin;C:\Program
                          Files\doxygen\bin;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\
                          system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\Windo
                          wsPowerShell\v1.0\;C:\Program Files\Microsoft SQL
                          Server\120\Tools\Binn\;C:\Program Files (x86)\Skype\Phone\;C:\Windows\
                          System32\OpenSSH\;P:\Scala_SBT\bin;C:\Program Files (x86)\Windows
                          Live\Shared;C:\Program Files\NVIDIA Corporation\NVIDIA NGX;C:\Program
                          Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA
                          Corporation\NVIDIA NvDLISR;P:\CMake\bin;C:\WINDOWS\system32;C:\WINDOWS
                          ;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
                          C:\WINDOWS\System32\OpenSSH\;D:\Tesseract_OCR;C:\Users\Admin\Anaconda3
                          ;C:\Users\Admin\Anaconda3\Scripts;C:\Users\Admin\Anaconda3\Library\bin
                          ;C:\Program
                          Files\smartmontools\bin;C:\Users\Admin\AppData\Local\Programs\MiKTeX 2
                          .9\miktex\bin\x64\;C:\Users\Admin\AppData\Local\Microsoft\WindowsApps;
                          C:\Users\Admin\AppData\Local\GitHubDesktop\bin;M:\Studium\Data_Science
                          _Master\S3_WS1819\Advanced Softwareengineering\sonar-scanner-
                          cli-3.2.0.1227-windows\sonar-scanner-3.2.0.1227-windows\bin
             PSMODULEPATH=C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=P:\VirtualBox\

     active environment : None
       user config file : C:\Users\Admin\.condarc
 populated config files : C:\Users\Admin\.condarc
          conda version : 4.7.5
    conda-build version : 2.0.2
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.1
       base environment : C:\Users\Admin\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\Admin\Anaconda3\pkgs
                          C:\Users\Admin\.conda\pkgs
                          C:\Users\Admin\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\Admin\Anaconda3\envs
                          C:\Users\Admin\.conda\envs
                          C:\Users\Admin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.6.8 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: n

No report sent. To permanently opt-out, use

    $ conda config --set report_errors false


```
</p></details>

How can I get rid of this? I have to mention that I'm primarily using this env:

<details open><summary><code>`conda list`</code></summary><p>

```
 (docupars) C:\WINDOWS\system32>conda list
# packages in environment at C:\Users\Admin\Anaconda3\envs\docupars:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl
absl-py                   0.7.1                    py36_0
array2gif                 1.0.4              pyh24bf2e0_0    conda-forge
asn1crypto                0.24.0                   py36_0
astor                     0.8.0                    py36_0
attrs                     19.1.0                   py36_1
beautifulsoup4            4.8.0                    py36_0
blas                      1.0                         mkl
bleach                    3.1.0                    py36_0
bottleneck                1.2.1            py36h452e1ab_1
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cachetools                2.1.0                      py_0    conda-forge
certifi                   2019.6.16                py36_1
cffi                      1.7.0                    pypi_0    pypi
chardet                   3.0.4                 py36_1003
cloudpickle               1.2.1                      py_0
cryptography              2.7              py36h7a1dbc1_0
cudatoolkit               10.0.130                      0
cycler                    0.10.0           py36h009560c_0
cymem                     2.0.2            py36h74a9793_0
cytoolz                   0.9.0.1          py36hfa6e2cd_1
dask-core                 2.3.0                      py_0
dataclasses               0.6                        py_0    fastai
decorator                 4.4.0                    py36_1
defusedxml                0.6.0                      py_0
dill                      0.2.9                    py36_0
entrypoints               0.3                   py36_1000    conda-forge
fastai                    1.0.55                        1    fastai
fastprogress              0.1.21                     py_0    fastai
ffmpeg                    4.2                  h6538335_0    conda-forge
ffmpy                     0.2.2                    pypi_0    pypi
freetype                  2.9.1                ha9979f8_1
gast                      0.2.2                    py36_0
google-api-core           1.14.2           py36h21ff451_0    conda-forge
google-auth               1.6.3                      py_0    conda-forge
google-cloud-bigquery     1.17.0                   py36_0    conda-forge
google-cloud-core         1.0.3                      py_0    conda-forge
google-cloud-storage      1.17.0                     py_0    conda-forge
google-resumable-media    0.3.2                      py_0    conda-forge
googleapis-common-protos  1.6.0            py36h21ff451_0
grpcio                    1.16.1           py36h351948d_1
h5py                      2.9.0            py36h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                      py36_0
imageio                   2.4.1                    pypi_0    pypi
imageio-ffmpeg            0.3.0                    pypi_0    pypi
importlib_resources       1.0.2                 py36_1000    conda-forge
imutils                   0.5.2                    pypi_0    pypi
intel-openmp              2019.4                      245
ipython_genutils          0.2.0                      py_1    conda-forge
jinja2                    2.10.1                   py36_0
joblib                    0.13.2                   py36_0
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonform                  0.0.2                    pypi_0    pypi
jsonschema                3.0.2                    py36_0
jsonsir                   0.0.2                    pypi_0    pypi
jupyter_core              4.5.0                      py_0
keras                     2.2.4                         0
keras-applications        1.0.8                      py_0
keras-base                2.2.4                    py36_0
keras-preprocessing       1.1.0                      py_1
kiwisolver                1.1.0            py36ha925a31_0
libblas                   3.8.0                    12_mkl    conda-forge
libcblas                  3.8.0                    12_mkl    conda-forge
libiconv                  1.15             vc14h29686d3_5  [vc14]  anaconda
liblapack                 3.8.0                    12_mkl    conda-forge
liblapacke                3.8.0                    12_mkl    conda-forge
libmklml                  2019.0.5                      0
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.9.1                h7bd577a_0
libsodium                 1.0.16               h9d3ae62_0
libtiff                   4.0.10               hb898794_2
libwebp                   1.0.2                hfa6e2cd_1    conda-forge
libxml2                   2.9.9                h464c3ec_0    anaconda
libxslt                   1.1.33               h579f668_0    anaconda
lxml                      4.4.1            py36h1350720_0
markdown                  3.1.1                    py36_0
markupsafe                1.1.1            py36he774522_0
matplotlib                3.1.1            py36hc8f65d3_0
matplotlib-base           3.1.1            py36h2852a4a_1    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.4                      245
mkl-service               2.3.0            py36hb782905_0
mkl_fft                   1.0.14           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
mock                      3.0.5                    py36_0
moviepy                   0.2.3.5                    py_0    conda-forge
msgpack-numpy             0.4.3.2                  py36_0
msgpack-python            0.6.1            py36h74a9793_1
murmurhash                1.0.2            py36h33f27b4_0
nbconvert                 5.5.0                      py_0
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.3                        py_0
ninja                     1.9.0            py36h74a9793_0
numexpr                   2.7.0            py36hdce8814_0
numpy                     1.16.4           py36h19fb1c0_0
numpy-base                1.16.4           py36hc3f5095_0
nvidia-ml-py3             7.352.0                    py_0    fastai
olefile                   0.46                     py36_0
opencv                    4.1.1            py36h6afde12_1    conda-forge
opencv-contrib-python     4.1.1.26                 pypi_0    pypi
openssl                   1.1.1d               he774522_0
packaging                 19.1                     py36_0
pandas                    0.25.1           py36ha925a31_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py36_1
pillow                    6.1.0            py36hdc69c19_0
pip                       19.2.2                   py36_0
plac                      0.9.6                    py36_0
preshed                   2.0.1            py36h33f27b4_0
protobuf                  3.9.1            py36he025d50_0    conda-forge
pyasn1                    0.4.6                      py_0    conda-forge
pyasn1-modules            0.2.6                    py36_0
pycparser                 2.19                     py36_1    conda-forge
pydensecrf                1.0rc3           py36h830ac7b_1    conda-forge
pygments                  2.4.2                      py_0
pyopenssl                 19.0.0                   py36_0
pyparsing                 2.4.2                      py_0
pypdf2                    1.26.0                     py_2    conda-forge
pyqt                      5.9.2            py36h6538335_2
pyreadline                2.1                      py36_1
pyrsistent                0.15.3           py36hfa6e2cd_0    conda-forge
pysocks                   1.7.0                    py36_0
pytesseract               0.3.0                    pypi_0    pypi
python                    3.6.9                h5500b2f_0
python-dateutil           2.8.0                    py36_0
python-easyconfig         0.1.7                    pypi_0    pypi
python-libmagic           0.4.0                    pypi_0    pypi
python-magic              0.4.13                   pypi_0    pypi
python-magic-bin          0.4.14                   pypi_0    pypi
python-magic-win64        0.4.13                   pypi_0    pypi
pytorch                   1.1.0           py3.6_cuda100_cudnn7_1    pytorch
pytz                      2019.2                     py_0
pywavelets                1.0.3            py36h8c2d366_1
pyyaml                    5.1.1                    pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
regex                     2018.01.10      py36hfa6e2cd_1000    fastai
requests                  2.22.0                   py36_0
resource                  0.2.1                    pypi_0    pypi
rsa                       3.4.2                      py_1    conda-forge
scikit-image              0.15.0           py36he350917_2    conda-forge
scikit-learn              0.21.2           py36h6288b17_0
scipy                     1.3.1            py36h29ff71c_0
setuptools                41.0.1                   py36_0
sip                       4.19.8           py36h6538335_0
six                       1.12.0                py36_1000    conda-forge
soupsieve                 1.9.2                    py36_0
spacy                     2.0.18          py36h6538335_1000    fastai
sqlite                    3.29.0               he774522_0
tensorboard               1.13.1           py36h33f27b4_0
tensorflow                1.13.1          mkl_py36hd212fbe_0
tensorflow-base           1.13.1          mkl_py36hcaf7020_0
tensorflow-estimator      1.13.0                     py_0
termcolor                 1.1.0                    py36_1
testpath                  0.4.2                    py36_0
thinc                     6.12.1          py36h830ac7b_1000    fastai
tk                        8.6.9             hfa6e2cd_1000    conda-forge
toolz                     0.10.0                     py_0
torchsummary              1.5.1                    pypi_0    pypi
torchvision               0.3.0              py36_cu100_1    pytorch
tornado                   6.0.3            py36he774522_0
tqdm                      4.32.1                     py_0
traitlets                 4.3.2                 py36_1000    conda-forge
typing                    3.6.4                    py36_0
ujson                     1.35             py36hfa6e2cd_0
urllib3                   1.24.2                   py36_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_0
webencodings              0.5.1                    py36_1
werkzeug                  0.15.5                     py_0
wheel                     0.33.4                   py36_0
win_inet_pton             1.1.0                    py36_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36hfa6e2cd_2
xz                        5.2.4                h2fa13f4_4
yaml                      0.1.7                hc54c509_2
zeromq                    4.3.1                h33f27b4_3
zlib                      1.2.11               h62dcd97_3
zstd                      1.3.7                h508b16e_0
```
</p></details>

Thanks for your help! =)

I'm sorry if I forgot some needed details. Just tell me and I'll add them!

**Comment by jjhelmus** [comment]
Re-adding the `free` channel should allow you to update `numba` and `tensorflow-gpu` and in turn update `conda-build`.  `free` can be added by adjusting the configuration file or using `conda config --set restore_free_channel true`.  More details on why free was removed and how to add it back can be found in the [blog post](https://www.anaconda.com/why-we-removed-the-free-channel-in-conda-4-7/) on the topic.
