### ISSUE TITLE
Cannot create environment from yml with pip dependencies on macOS

### ISSUE THREAD

**Issue by fzalkow** [conda/conda#9271]
## Current Behavior

I want to create a new environment with a yml file, containing some pip dependencies. Here is a minimal example:
```
name: test

dependencies:
  - python==3.6.5
  - pip
  - pip:
    - numpy
```
Currently this fails on my macOS system. However, I also tried with Ubuntu as well as Windows, where it works. I have no idea, why it doesn't work on macOS. When removing the Python version specification, it works.

A possibly related issue is #8404, where a similar problem was reported for Windows instead of macOS.

### Steps to Reproduce

```
$ conda env create -f environment.yml 
Collecting package metadata (repodata.json): done
Solving environment: done
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Ran pip subprocess with arguments:
['/Users/fzalkow/miniconda3/envs/test/bin/python', '-m', 'pip', 'install', '-U', '-r', '/Users/fzalkow/Downloads/condaenv.frv2a3qh.requirements.txt']
Pip subprocess output:

Pip subprocess error:
Failed to import the site module
Traceback (most recent call last):
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/Users/fzalkow/miniconda3/envs/test/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
ValueError: source code string cannot contain null bytes


CondaEnvException: Pip failed
```

## Expected Behavior
It should create a new environment with the specifications given in the yml file.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : base
    active env location : /Users/fzalkow/miniconda3
            shell level : 1
       user config file : /Users/fzalkow/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/fzalkow/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/fzalkow/miniconda3/pkgs
                          /Users/fzalkow/.conda/pkgs
       envs directories : /Users/fzalkow/miniconda3/envs
                          /Users/fzalkow/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
# no output
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
$ conda list --show-channel-urls 
# packages in environment at /Users/fzalkow/miniconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py37_0    defaults
ca-certificates           2019.5.15                     1    defaults
certifi                   2019.6.16                py37_1    defaults
cffi                      1.12.3           py37hb5b8e2f_0    defaults
chardet                   3.0.4                 py37_1003    defaults
conda                     4.7.12                   py37_0    defaults
conda-package-handling    1.6.0            py37h1de35cc_0    defaults
cryptography              2.7              py37ha12b0ac_0    defaults
idna                      2.8                      py37_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.1.1d               h1de35cc_1    defaults
pip                       19.2.2                   py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.7.0                    py37_0    defaults
python                    3.7.3                h359304d_0    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
setuptools                41.0.1                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.29.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
tqdm                      4.32.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wheel                     0.33.4                   py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```
</p></details>

**Comment by soapy1** [comment]
This seems to be a particularly a python 3.6.5 issue, this environment.yaml works:

```
name: test
dependencies:
  - python=3.6
  - pip
  - pip:
    - numpy

```

**Comment by francopiccolo** [comment]
I'm having the same issue with Python 3.6.5, any idea how to work around it?

**Comment by fragofer** [comment]
[Here](https://github.com/conda/conda/issues/9298#issuecomment-644041306) is a workaround that worked for me 

cheers
