### ISSUE TITLE
problem with ipython in python=3.6.5 

### ISSUE THREAD

**Issue by aerijman** [conda/conda#9298]
## Current Behavior

`conda create --name python365 python=3.6.5`
`conda activate python365`   
`ipython`

Python **3.7.3** (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.8.0 -- An enhanced Interactive Python. Type '?' for help.

`conda install ipython`
`ipython` 

```
Failed to import the site module
Traceback (most recent call last):
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/Users/aerijman/miniconda3/envs/python365/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
ValueError: source code string cannot contain null bytes

```

### Steps to Reproduce

```
conda create --name python365 python=3.6.5
conda activate python365
conda install ipython   
ipython
```

## Expected Behavior

```
Python 3.6.5 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython XXXX -- An enhanced Interactive Python. Type '?' for help.

```
## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : python365
    active env location : /Users/aerijman/miniconda3/envs/python365
            shell level : 2
       user config file : /Users/aerijman/.condarc
 populated config files : 
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/aerijman/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/aerijman/miniconda3/pkgs
                          /Users/aerijman/.conda/pkgs
       envs directories : /Users/aerijman/miniconda3/envs
                          /Users/aerijman/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 503:20
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /Users/aerijman/miniconda3/envs/python365:
#
# Name                    Version                   Build  Channel
appnope                   0.1.0            py36hf537a9a_0    defaults
backcall                  0.1.0                    py36_0    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2019.9.11                py36_0    defaults
decorator                 4.4.0                    py36_1    defaults
ipython                   7.8.0            py36h39e3cac_0    defaults
ipython_genutils          0.2.0            py36h241746c_0    defaults
jedi                      0.15.1                   py36_0    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
ncurses                   6.1                  h0a44026_1    defaults
openssl                   1.0.2t               h1de35cc_1    defaults
parso                     0.5.1                      py_0    defaults
pexpect                   4.7.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pip                       19.2.3                   py36_0    defaults
prompt_toolkit            2.0.9                    py36_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
pygments                  2.4.2                      py_0    defaults
python                    3.6.5                hc167b69_1    defaults
readline                  7.0                  h1de35cc_5    defaults
setuptools                41.2.0                   py36_0    defaults
six                       1.12.0                   py36_0    defaults
sqlite                    3.29.0               ha441bb4_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
traitlets                 4.3.2            py36h65bd3ce_0    defaults
wcwidth                   0.1.7            py36h8c6ec74_0    defaults
wheel                     0.33.6                   py36_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
zlib                      1.2.11               h1de35cc_3    defaults
```
</p></details>

**Comment by jjhelmus** [comment]
@aerijman I tried to replicate this issue on my macbook and was able to run ipython successfully without any errors using:

```
conda create -n test python=3.6.5
conda activate test
conda install ipython
ipython
```

Are there any environment variables or files in your `$HOME/.local` directory that may be causing issues with ipython?  Does the python shell work as expected?

**Comment by aerijman** [comment]
```
$ ls -lta ~/.local/
total 0
drwxr-xr-x+ 75 aerijman  staff  2400 Sep 30 11:45 ..
drwx------   3 aerijman  staff    96 Sep 27 13:00 share
drwx------   3 aerijman  staff    96 Sep 27 12:59 .
```

I re-installed miniconda3 yesterday (just in case this could tell something).

**Comment by KeNJiKunG** [comment]
I found that file lib/python3.6/re.py itself is corrupted. The python package filename is python-3.6.5-hc167b69_1.conda. For some reason the file got from the repository is corrupted but the file on the site is not.

For now, I fix the issue by run

`conda install https://repo.anaconda.com/pkgs/main/osx-64/python-3.6.5-hc167b69_1.tar.bz2
`
