### ISSUE TITLE
conda activate or conda init invalid choice ~/anaconda3/bin/conda

### ISSUE THREAD

**Issue by charlesritchea** [conda/conda#9324]
## Current Behavior

Activating base environment with 

```
    eval "$(/home/charlesritchea/anaconda3/bin/conda shell.bash hook)"
```

Results in:

```
    usage: conda [-h] [-V] command ...
    conda: error: argument command: invalid choice: '/home/charlesritchea/anaconda3/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
```

```
    conda update --all
```

Rsults in:

```
NoPackagesFoundError: Dependencies missing in current linux-64 channels: 
  - libcurl -> krb5 >=1.16.1,<1.17.0a0
  - libcurl -> libgcc-ng >=7.3.0
  - libcurl -> libssh2 >=1.8.2,<2.0a0
  - libcurl -> openssl >=1.1.1c,<1.1.2a
  - pluggy -> importlib_metadata >=0.12
  - conda-package-handling -> libarchive >=3.3.3
  - conda-package-handling -> python >=3.7,<3.8.0a0
  - conda-package-handling -> python-libarchive-c
  - python-libarchive-c -> libarchive
  - python-libarchive-c -> python >=3.7,<3.8.0a0
  - spyder-kernels -> ipykernel >4.9.0
  - spyder-kernels -> python >=3.7,<3.8.0a0
  - spyder-kernels -> pyzmq >=17
  - spyder-kernels -> wurlitzer
  - jupyterlab (target=https://repo.anaconda.com/pkgs/main::jupyterlab-1.0.2-py37hf63ae98_0) -> python >=3.7,<3.8.0a0
```

Attempt to create 3.6 environment:
```
`$ /home/charlesritchea/anaconda3/bin/conda create -n pv python=3.6 anaconda`
```
Results In: 
```
    Traceback (most recent call last):
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 44, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/charlesritchea/anaconda3/pkgs/expat-2.1.0-0/info/no_link'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 52, in yield_lines
        raise StopIteration
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/plan.py", line 809, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/core/link.py", line 124, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/core/link.py", line 124, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 84, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 151, in read_paths_json
        no_link = read_no_link(info_dir)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 221, in read_no_link
        yield_lines(join(info_dir, 'no_softlink'))))
    RuntimeError: generator raised StopIteration
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/charlesritchea/.local/lib/python3.7/site-packages/conda/cli/install.py", line 372, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration
```

### Steps to Reproduce

On Ubuntu 19.04:
Download latest Anaconda3 from <https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh>
Run it, accept license, use default answers for everything else

```
    bash ~/Downloads/Anaconda3-2019.07-Linux-x86_64.sh 
```
Results in:

```
    ...
    You have chosen to not have conda modify your shell scripts at all.
    To activate conda's base environment in your current shell session:

    eval "$(/home/charlesritchea/anaconda3/bin/conda shell.YOUR_SHELL_NAME hook)" 
    ...
``` 

Attempt to activate conda's base environment  

```
    eval "$(/home/charlesritchea/anaconda3/bin/conda shell.bash hook)"
```

```
    usage: conda [-h] [-V] command ...
    conda: error: argument command: invalid choice: '/home/charlesritchea/anaconda3/bin/conda' (choose from 'info', 'help', 'list', 'search', 'create', 'install', 'update', 'upgrade', 'remove', 'uninstall', 'config', 'clean', 'package')
```

## Expected Behavior

I can run `conda update --all` without error
I can create a Python3.6 environment without error
I can activate an environment without error

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 3.18.8
         python version : 3.7.3.final.0
       requests version : 2.22.0
       root environment : /home/charlesritchea/anaconda3  (writable)
    default environment : /home/charlesritchea/anaconda3
       envs directories : /home/charlesritchea/anaconda3/envs
                          /home/charlesritchea/.conda/envs
          package cache : /home/charlesritchea/anaconda3/pkgs
                          /home/charlesritchea/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.22.0 CPython/3.7.3 Linux/5.3.5-050305-generic debian/buster/sid glibc/2.29
                UID:GID : 1000:1000
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /home/charlesritchea/anaconda3:
#
anaconda                  2019.07                  py37_0    https://repo.anaconda.com/pkgs/main
anaconda-navigator        1.9.7                    py37_0    https://repo.anaconda.com/pkgs/main
anaconda-project          0.8.3                      py_0    https://repo.anaconda.com/pkgs/main
babel                     2.7.0                      py_0    https://repo.anaconda.com/pkgs/main
backports                 1.0                        py_2    https://repo.anaconda.com/pkgs/main
backports.functools_lru_cache 1.5                        py_2    https://repo.anaconda.com/pkgs/main
backports.tempfile        1.0                        py_1    https://repo.anaconda.com/pkgs/main
backports.weakref         1.0.post1                  py_1    https://repo.anaconda.com/pkgs/main
bzip2                     1.0.8                h7b6447c_0    https://repo.anaconda.com/pkgs/main
cloudpickle               1.2.1                      py_0    https://repo.anaconda.com/pkgs/main
conda                     4.7.10                   py37_0    https://repo.anaconda.com/pkgs/main
conda-build               3.18.8                   py37_0    https://repo.anaconda.com/pkgs/main
conda-package-handling    1.3.11                   py37_0    https://repo.anaconda.com/pkgs/main
conda-verify              3.4.2                      py_1    https://repo.anaconda.com/pkgs/main
curl                      7.65.2               hbc83047_0    https://repo.anaconda.com/pkgs/main
cython                    0.29.12          py37he6710b0_0    https://repo.anaconda.com/pkgs/main
cytoolz                   0.10.0           py37h7b6447c_0    https://repo.anaconda.com/pkgs/main
dask                      2.1.0                      py_0    https://repo.anaconda.com/pkgs/main
dask-core                 2.1.0                      py_0    https://repo.anaconda.com/pkgs/main
defusedxml                0.6.0                      py_0    https://repo.anaconda.com/pkgs/main
distributed               2.1.0                      py_0    https://repo.anaconda.com/pkgs/main
filelock                  3.0.12                     py_0    https://repo.anaconda.com/pkgs/main
flask                     1.1.1                      py_0    https://repo.anaconda.com/pkgs/main
glob2                     0.7                        py_0    https://repo.anaconda.com/pkgs/main
ipython                   7.6.1            py37h39e3cac_0    https://repo.anaconda.com/pkgs/main
ipywidgets                7.5.0                      py_0    https://repo.anaconda.com/pkgs/main
jdcal                     1.4.1                      py_0    https://repo.anaconda.com/pkgs/main
json5                     0.8.4                      py_0    https://repo.anaconda.com/pkgs/main
jupyter_client            5.3.1                      py_0    https://repo.anaconda.com/pkgs/main
jupyter_core              4.5.0                      py_0    https://repo.anaconda.com/pkgs/main
jupyterlab                1.0.2            py37hf63ae98_0    https://repo.anaconda.com/pkgs/main
jupyterlab_server         1.0.0                      py_0    https://repo.anaconda.com/pkgs/main
libcurl                   7.65.2               h20c2e04_0    https://repo.anaconda.com/pkgs/main
nbconvert                 5.5.0                      py_0    https://repo.anaconda.com/pkgs/main
networkx                  2.3                        py_0    https://repo.anaconda.com/pkgs/main
nltk                      3.4.4                    py37_0    https://repo.anaconda.com/pkgs/main
notebook                  6.0.0                    py37_0    https://repo.anaconda.com/pkgs/main
numpydoc                  0.9.1                      py_0    https://repo.anaconda.com/pkgs/main
openpyxl                  2.6.2                      py_0    https://repo.anaconda.com/pkgs/main
parso                     0.5.0                      py_0    https://repo.anaconda.com/pkgs/main
partd                     1.0.0                      py_0    https://repo.anaconda.com/pkgs/main
path.py                   12.0.1                     py_0    https://repo.anaconda.com/pkgs/main
pillow                    6.1.0            py37h34e0f95_0    https://repo.anaconda.com/pkgs/main
pluggy                    0.12.0                     py_0    https://repo.anaconda.com/pkgs/main
prometheus_client         0.7.1                      py_0    https://repo.anaconda.com/pkgs/main
pygments                  2.4.2                      py_0    https://repo.anaconda.com/pkgs/main
pyparsing                 2.4.0                      py_0    https://repo.anaconda.com/pkgs/main
pytest                    5.0.1                    py37_0    https://repo.anaconda.com/pkgs/main
python-libarchive-c       2.8                     py37_11    https://repo.anaconda.com/pkgs/main
pytz                      2019.1                     py_0    https://repo.anaconda.com/pkgs/main
qtconsole                 4.5.1                      py_0    https://repo.anaconda.com/pkgs/main
qtpy                      1.8.0                      py_0    https://repo.anaconda.com/pkgs/main
rope                      0.14.0                     py_0    https://repo.anaconda.com/pkgs/main
scipy                     1.3.0            py37h7c811a0_0    https://repo.anaconda.com/pkgs/main
snowballstemmer           1.9.0                      py_0    https://repo.anaconda.com/pkgs/main
sphinx                    2.1.2                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-applehelp   1.0.1                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-devhelp     1.0.1                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-htmlhelp    1.0.2                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-jsmath      1.0.1                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-qthelp      1.0.2                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-serializinghtml 1.1.3                      py_0    https://repo.anaconda.com/pkgs/main
sphinxcontrib-websupport  1.1.2                      py_0    https://repo.anaconda.com/pkgs/main
spyder                    3.3.6                    py37_0    https://repo.anaconda.com/pkgs/main
spyder-kernels            0.5.1                    py37_0    https://repo.anaconda.com/pkgs/main
sqlite                    3.29.0               h7b6447c_0    https://repo.anaconda.com/pkgs/main
tblib                     1.4.0                      py_0    https://repo.anaconda.com/pkgs/main
toolz                     0.10.0                     py_0    https://repo.anaconda.com/pkgs/main
tqdm                      4.32.1                     py_0    https://repo.anaconda.com/pkgs/main
werkzeug                  0.15.4                     py_0    https://repo.anaconda.com/pkgs/main
widgetsnbextension        3.5.0                    py37_0    https://repo.anaconda.com/pkgs/main
xlsxwriter                1.1.8                      py_0    https://repo.anaconda.com/pkgs/main
zict                      1.0.0                      py_0    https://repo.anaconda.com/pkgs/main
zipp                      0.5.1                      py_0    https://repo.anaconda.com/pkgs/main
```
</p></details>

**Comment by msarahan** [comment]
Conda 4.3 is not current and didn't have the "conda activate" command. Please fill in the issue template as requested.

**Comment by charlesritchea** [comment]
@msarahan hopefully that is adequate

**Comment by msarahan** [comment]
Thanks.  I don't know how you ended up with such an old version of conda.  Please run

`conda update conda`

It should bring you possibly first to 4.3.27, and then if you run it again, you should get to 4.7.12.  Then you should try your activate command.

**Comment by charlesritchea** [comment]
That is the version that comes with the latest Anaconda3
if I run
```
conda update conda
```
I get
```
PackageNotFoundError: Dependencies missing in current linux-64 channels: 
  - python-libarchive-c (target=https://repo.anaconda.com/pkgs/main::python-libarchive-c-2.8-py37_11) -> libarchive
  - python-libarchive-c (target=https://repo.anaconda.com/pkgs/main::python-libarchive-c-2.8-py37_11) -> python >=3.7,<3.8.0a0
  - conda-package-handling (target=https://repo.anaconda.com/pkgs/main::conda-package-handling-1.3.11-py37_0) -> libarchive >=3.3.3
  - conda-package-handling (target=https://repo.anaconda.com/pkgs/main::conda-package-handling-1.3.11-py37_0) -> python >=3.7,<3.8.0a0
  - conda-package-handling (target=https://repo.anaconda.com/pkgs/main::conda-package-handling-1.3.11-py37_0) -> python-libarchive-c

(and similarly for the other packages)
```

**Comment by msarahan** [comment]
What anaconda installer did you use?  Again, 4.3.16 is absolutely not current.  The latest release of anaconda, 2019.07, has conda 4.7.10. You're starting from a very weird place.

**Comment by charlesritchea** [comment]
@msarahan I said which one I used in the issue report https://repo.anaconda.com/archive/Anaconda3-2019.07-Linux-x86_64.sh

**Comment by charlesritchea** [comment]
I can see that the installer says it is installing 4.7.10, but the version that is actually in anaconda3/bin/conda is 4.3.16 for some reason. I really don't know what I'm doing wrong. I'm doing the most obvious stuff possible.

**Comment by charlesritchea** [comment]
I think I figure out what is going on. The older version of conda (and who knows what else) was located in ~/.local/lib/python3.7 I don't know how it got in there. Maybe IntelliJ? Once I removed the ~/.local/lib/python3.7 folder then reinstalled Anaconda. Things seem to be working now. Still seems like a bug that it would pull the old version from ~/.local/lib though

**Comment by msarahan** [comment]
It is the way that python works.  Like it or not, it is fact. https://www.python.org/dev/peps/pep-0370/
