### ISSUE TITLE
datarace on pkg directory creation

### ISSUE THREAD

**Issue by s22chan** [conda/conda#9339]
## Current Behavior

When specifying a package cache directory that does not yet exist, conda can datarace between testing existance/creating the cache directory without making the two operations atomic.

### Steps to Reproduce

a `.conda.rc` file
```
always_yes: true
changeps1: false
quiet: true
auto_update_conda: false
pkgs_dirs:
  - /root/.conda/pkgs
  - /opt/conda/pkgs
channels:
  - conda-forge
  - defaults
  - bioconda
```

running
```
conda create -p ~/.conda/envs/build \
    anaconda-client \
    conda=4.7.10 \
    conda-build \
    conda-verify \
    coverage \
    make \
    sphinx \
    sphinx_rtd_theme 
```

randomly produces

```
Collecting package metadata (current_repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 107, in touch
        mkdir_p_sudo_safe(dirpath)
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
        os.mkdir(path)
    FileExistsError: [Errno 17] File exists: '/root/.conda/pkgs'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 185, in _load
        mtime = getmtime(self.cache_path_json)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 153, in cache_path_json
        return self.cache_path_base + '.json'
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 144, in cache_path_base
        create_cache_dir(),
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 645, in create_cache_dir
        cache_dir = join(PackageCacheData.first_writable(context.pkgs_dirs).pkgs_dir, 'cache')
      File "/opt/conda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 162, in first_writable
        created = create_package_cache_directory(package_cache.pkgs_dir)
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/create.py", line 435, in create_package_cache_directory
        touch(join(pkgs_dir, PACKAGE_CACHE_MAGIC_FILE), mkdir=True, sudo_safe=sudo_safe)
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/update.py", line 125, in touch
        raise NotWritableError(path, e.errno, caused_by=e)
    conda.exceptions.NotWritableError: The current user does not have write permissions to a required path.
      path: /root/.conda/pkgs/urls.txt
      uid: 0
      gid: 0
    
    If you feel that permissions on this path are set incorrectly, you can manually
    change them by executing
    
      $ sudo chown 0:0 /root/.conda/pkgs/urls.txt
    
    In general, it's not advisable to use 'sudo conda'.
    
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 256, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 150, in solve_for_diff
        force_remove)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 249, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 389, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/solve.py", line 974, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/index.py", line 214, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 91, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 425, in result
        return self.__get_result()
      File "/opt/conda/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/opt/conda/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 87, in <lambda>
        package_ref_or_match_spec))
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 96, in query
        self.load()
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 160, in load
        _internal_state = self._load()
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 188, in _load
        self.cache_path_json)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 153, in cache_path_json
        return self.cache_path_base + '.json'
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 144, in cache_path_base
        create_cache_dir(),
      File "/opt/conda/lib/python3.7/site-packages/conda/core/subdir_data.py", line 646, in create_cache_dir
        mkdir_p_sudo_safe(cache_dir)
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/__init__.py", line 84, in mkdir_p_sudo_safe
        os.mkdir(path)
    FileExistsError: [Errno 17] File exists: '/root/.conda/pkgs/cache'

`$ /opt/conda/bin/conda create -p /root/.conda/envs/build anaconda-client conda=4.7.10 conda-build conda-verify coverage make sphinx sphinx_rtd_theme`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/conda/bin/conda
             CONDA_PREFIX=/opt/conda
    CONDA_PROMPT_MODIFIER=
         CONDA_PYTHON_EXE=/opt/conda/bin/python
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=1
                 NO_PROXY=<set>
                     PATH=/opt/conda/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr
                          /local/bin:/usr/sbin:/usr/bin:/sbin:/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /root/.conda/pkgs
                          /opt/conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-1043-aws debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
Exited with code 1
```

## Expected Behavior

Either the `query_all` is linear, or the directory test and creation are under a mutual exclusion lock, or test+create is extracted outside of the thread pools such that the package directory creation always succeeds.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
always_yes: true
changeps1: false
quiet: true
auto_update_conda: false
pkgs_dirs:
  - /root/.conda/pkgs
  - /opt/conda/pkgs
channels:
  - https://conda.anaconda.org/t//deepgenomics
  - conda-forge
  - defaults
  - bioconda
(base) root@6fa958d717a2:/# conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.7.10
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
          package cache : /root/.conda/pkgs
                          /opt/conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.10 requests/2.22.0 CPython/3.7.3 Linux/4.9.184-linuxkit debian/10 glibc/2.28
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /root/.condarc <==
auto_update_conda: False
changeps1: False
pkgs_dirs:
  - /root/.conda/pkgs
  - /opt/conda/pkgs
channels:
  - conda-forge
  - defaults
  - bioconda
always_yes: True
quiet: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                0.24.0                   py37_0    defaults
bzip2                     1.0.8                h7b6447c_0    defaults
ca-certificates           2019.8.28                     0    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.12.3           py37h2e261b9_0    defaults
chardet                   3.0.4                    py37_1    defaults
conda                     4.7.10                   py37_0    defaults
conda-package-handling    1.3.11                   py37_0    defaults
cryptography              2.7              py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
libarchive                3.3.3                h5d8350f_5    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libxml2                   2.9.9                hea5a465_1    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1d               h7b6447c_2    defaults
pip                       19.1.1                   py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.7.0                    py37_0    defaults
python                    3.7.3                h0371630_0    defaults
python-libarchive-c       2.8                     py37_11    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                41.0.1                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.29.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.32.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wheel                     0.33.4                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```
</p></details>

**Comment by s22chan** [comment]
already closed by #9073 but 4.7.12 has other issues with `conda_build_config.yaml`
