### ISSUE TITLE
CondaError: Cannot link a source that does not exist. Error during Seaborn update has broken conda.

### ISSUE THREAD

**Issue by ehbaker** [conda/conda#9374]
## Current Behavior

After erroring out while updating Seaborn, I'm unable to run any conda commands, e.g. `conda info`

### Steps to Reproduce

```
conda info produces the following:
```
`Traceback (most recent call last):
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 171, in main
    activate.main()
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\activate.py", line 181, in main
    from ..install import symlink_conda
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 9, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\__init__.py", line 44, in <module>
    import chardet
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\chardet\__init__.py", line 20, in <module>
    from .universaldetector import UniversalDetector
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\chardet\universaldetector.py", line 43, in <module>
    from .charsetgroupprober import CharSetGroupProber
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\chardet\charsetgroupprober.py", line 28, in <module>
    from .enums import ProbingState
ModuleNotFoundError: No module named 'chardet.enums'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 179, in main
    return handle_exception(e)
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 634, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 596, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\__init__.py", line 44, in <module>
    import chardet
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\chardet\__init__.py", line 20, in <module>
    from .universaldetector import UniversalDetector
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\chardet\universaldetector.py", line 43, in <module>
    from .charsetgroupprober import CharSetGroupProber
  File "C:\Users\ehbaker\AppData\Local\Continuum\Anaconda3\lib\site-packages\chardet\charsetgroupprober.py", line 28, in <module>
    from .enums import ProbingState
ModuleNotFoundError: No module named 'chardet.enums'`

## Expected Behavior

I would expect to get normal conda info output

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
I'm not able to run conda info. Broke during package update of Seaborn.
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by ehbaker** [comment]
I'm not able to fix with:

`conda clean --packages` or `conda update conda`; these both give the same error message shown above. I broke conda!! Any suggestions beyond a full uninstall and reinstall? d'oh!

**Comment by mfansler** [comment]
@ehbaker you can download [a standalone binary of Conda](https://repo.anaconda.com/pkgs/misc/conda-execs/) and attempt to repair your **base** env. There are some details in [this StackOverflow post](https://stackoverflow.com/a/54563455/570918).

**Comment by ehbaker** [comment]
Thank you; I re-installed Anaconda to fix. My base environment had gotten way too complicated. Learned my lesson on that, will avoid making any changes to the base envionment the future! Thanks for the reply.
