### ISSUE TITLE
ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by agnesbao** [conda/conda#9387]
Get this failure in Jenkins build inconsistently. It will fail half of the time, and then might pass with a rebuild:

```
 ++ /miniconda/bin/conda ..checkenv bash uptakeio_ci
 An unexpected error has occurred.
 Please consider posting the following information to the
 conda GitHub issue tracker at:
 
     https://github.com/conda/conda/issues
 
 
 
 Traceback (most recent call last):
   File "/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 171, in main
     activate.main()
   File "/miniconda/lib/python3.6/site-packages/conda/cli/activate.py", line 181, in main
     from ..install import symlink_conda
   File "/miniconda/lib/python3.6/site-packages/conda/install.py", line 37, in <module>
     from .core.package_cache import rm_fetched  # NOQA
   File "/miniconda/lib/python3.6/site-packages/conda/core/package_cache.py", line 9, in <module>
     from .path_actions import CacheUrlAction, ExtractPackageAction
   File "/miniconda/lib/python3.6/site-packages/conda/core/path_actions.py", line 33, in <module>
     from ..gateways.download import download
   File "/miniconda/lib/python3.6/site-packages/conda/gateways/download.py", line 10, in <module>
     from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
   File "/home/ci_home/.local/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
     import urllib3
 ModuleNotFoundError: No module named 'urllib3'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/miniconda/bin/conda", line 11, in <module>
     sys.exit(main())
   File "/miniconda/lib/python3.6/site-packages/conda/cli/main.py", line 179, in main
     return handle_exception(e)
   File "/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 634, in handle_exception
     print_unexpected_error_message(e)
   File "/miniconda/lib/python3.6/site-packages/conda/exceptions.py", line 596, in print_unexpected_error_message
     stderrlogger.info(get_main_info_str(get_info_dict()))
   File "/miniconda/lib/python3.6/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
     from ..connection import user_agent
   File "/miniconda/lib/python3.6/site-packages/conda/connection.py", line 12, in <module>
     from requests import Session, __version__ as REQUESTS_VERSION
   File "/home/ci_home/.local/lib/python3.6/site-packages/requests/__init__.py", line 43, in <module>
     import urllib3
 ModuleNotFoundError: No module named 'urllib3'
```

**Comment by kalefranz** [comment]
Can you provide step-by-step instructions on how to independently reproduce your issue?

**Comment by agnesbao** [comment]
Hi Kale, thank you for the response. I think this might be our internal issue due to the different Jenkins environment depending one which container it landed on during CI. I'm closing this issue since I have left that job and am not able to reproduce it anymore.
