### ISSUE TITLE
Issue installing pythonocc

### ISSUE THREAD

**Issue by HalfManHalfChicken** [conda/conda#9390]
Thank you very much for your help. As shown below:

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : not installed
         python version : 3.7.3.final.0
       requests version : 2.21.0
       root environment : /usr  (read only)
    default environment : /usr
       envs directories : /home/david/.conda/envs
                          /usr/envs
          package cache : /usr/pkgs
                          /home/david/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/tpaviot/linux-64
                          https://conda.anaconda.org/tpaviot/noarch
                          https://conda.anaconda.org/dlr-sc/linux-64
                          https://conda.anaconda.org/dlr-sc/noarch
                          https://conda.anaconda.org/pythonocc/linux-64
                          https://conda.anaconda.org/pythonocc/noarch
                          https://conda.anaconda.org/oce/linux-64
                          https://conda.anaconda.org/oce/noarch
                          https://conda.anaconda.org/3dhubs/linux-64
                          https://conda.anaconda.org/3dhubs/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/david/.condarc
           offline mode : False
             user-agent : conda/4.3.16 requests/2.21.0 CPython/3.7.3 Linux/4.19.0-6-amd64 debian/10.0 glibc/2.28
                UID:GID : 1000:1000

`$ conda create -n pythonocc -c conda-forge -c tpaviot -c dlr-sc -c pythonocc -c oce pythonocc-core==0.18.2 python=3.7`

    Traceback (most recent call last):
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 44, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/david/.conda/pkgs/freeimageplus-3.17.0-0/info/has_prefix'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 52, in yield_lines
        raise StopIteration
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/david/.local/lib/python3.7/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/david/.local/lib/python3.7/site-packages/conda/plan.py", line 809, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/david/.local/lib/python3.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/david/.local/lib/python3.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/david/.local/lib/python3.7/site-packages/conda/core/link.py", line 124, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/david/.local/lib/python3.7/site-packages/conda/core/link.py", line 124, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 84, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 200, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 200, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "/home/david/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 199, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/david/.local/lib/python3.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/david/.local/lib/python3.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/david/.local/lib/python3.7/site-packages/conda/cli/main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "/home/david/.local/lib/python3.7/site-packages/conda/cli/install.py", line 372, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration

**Comment by soapy1** [comment]
conda 4.3.16 is very old. Please try updating.
