### ISSUE TITLE
Only get: conda.CondaMultiError: [WinError 182] The operating system cannot run %1

### ISSUE THREAD

**Issue by notatallshaw** [conda/conda#9394]
On Windows 10 upon installing Anaconda 5.3.0 (Python 3.7), running `conda install conda=4.7` or `conda install anaconda=2019.10` in to the base environment I am only getting the error in the title when using create, install, or update.

Conda version is 4.7.12.

I have tried using verbose mode and reading the code where the exception is thrown but it has not given me any clues as to why it might be happening.

Please advise what further debugging I can do to track down the problem.

Here is a sample output with verbose on:

```
C:\>conda create -n test python --no-deps -vvv
 
## Package Plan ##
 
  environment location: C:\PF\Anaconda3\envs\test
 
  added / updated specs:
    - python
 
 
The following packages will be downloaded:
 
    package                    |            build
    ---------------------------|-----------------
    python-3.8.0               |       hff0d562_0        19.5 MB  http://mycompany.domain/artifactory/continuum.io/pkgs/main
    ------------------------------------------------------------
                                           Total:        19.5 MB
 
The following NEW packages will be INSTALLED:
 
  python             artifactory/continuum.io/pkgs/main/win-64::python-3.8.0-hff0d562_0
 
 
Proceed ([y]/n)? y
 
DEBUG conda.core.package_cache_data:execute(644): prepared package cache actions:
  cache_actions:
    CacheUrlAction<url='http://mycompany.domain/artifactory/continuum.io/pkgs/main/win-64/python-3.8.0-hff0d562_0.tar.bz2', target_full_path='C:\\Users\\myuser\\.conda\\pkgs\\python-3.8.0-hff0d562_0.tar.bz2'>
  extract_actions:
    ExtractPackageAction<source_full_path='C:\\Users\\myuser\\.conda\\pkgs\\python-3.8.0-hff0d562_0.tar.bz2', target_full_path='C:\\Users\\myuser\\.conda\\pkgs\\python-3.8.0-hff0d562_0'>
 
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGABRT
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGINT
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGTERM
DEBUG conda.common.signals:signal_handler(45): registering handler for SIGBREAK
TRACE conda.core.path_actions:execute(1122): caching url http://mycompany.domain/artifactory/continuum.io/pkgs/main/win-64/python-3.8.0-hff0d562_0.tar.bz2 => C:\Users\myuser\.conda\pkgs\python-3.8.0-hff0d562_0.tar.bz2
TRACE conda.gateways.disk.delete:rm_rf(160): rm_rf C:\Users\myuser\.conda\pkgs\python-3.8.0-hff0d562_0
TRACE conda.gateways.disk.delete:rm_rf(166): rm_rf failed. Not a link, file, or directory: C:\Users\myuser\.conda\pkgs\python-3.8.0-hff0d562_0
DEBUG conda.core.package_cache_data:execute(651): b'OSError(22, 'The operating system cannot run %1', None, 182, None)'
NoneType: None
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGABRT
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGINT
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGTERM
DEBUG conda.common.signals:signal_handler(58): de-registering handler for Signals.SIGBREAK
Traceback (most recent call last):
  File "C:\PF\Anaconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
    return func(*args, **kwargs)
  File "C:\PF\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "C:\PF\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\PF\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 37, in execute
    install(args, parser, 'create')
  File "C:\PF\Anaconda3\lib\site-packages\conda\cli\install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  File "C:\PF\Anaconda3\lib\site-packages\conda\cli\install.py", line 342, in handle_txn
    unlink_link_transaction.download_and_extract()
  File "C:\PF\Anaconda3\lib\site-packages\conda\core\link.py", line 194, in download_and_extract
    self._pfe.execute()
  File "C:\PF\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 655, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: [WinError 182] The operating system cannot run %1

```

**Comment by notatallshaw** [comment]
I was able to insert a breakpoint in to conda to investigate the traceback (would be better if conda printed it out directly):

```
  File "C:\PF\Anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 689, in _execute_actions
    cache_axn.execute(progress_update_cache_axn)
  File "C:\PF\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 1138, in execute
    self._execute_channel(target_package_cache, progress_update_callback)
  File "C:\PF\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 1199, in _execute_channel
    **kwargs
  File "C:\PF\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
    return f(*args, **kwds)
  File "C:\PF\Anaconda3\lib\site-packages\conda\gateways\connection\download.py", line 80, in download
    preload_openssl()
  File "C:\PF\Anaconda3\lib\site-packages\conda\gateways\connection\download.py", line 70, in preload_openssl
    ctypes.WinDLL(libssl_path)
  File "C:\PF\Anaconda3\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
```

I was then able to add a print statement to the libssl_path and find this is the DLL it is giving the error it gives the error for: C:\PF\Anaconda3\Library\bin\ssleay32.dll

When I try the same ctypes.WinDLL on this dll I get the same error. So clearly SSL wasn't provided or updated on a way that Anaconda expected.

I'm going to try reinstalling Anaconda 4.3.0, making sure OpenSSL is updated, and then trying to before install 2019.10

Again though it's annoying I had to manually insert a breakpoint to expand the underlying traceback, I feel like it should be printed out to the debug information so you can figure out yourself what the problem is.

**Comment by notatallshaw** [comment]
I was able to workaround this bug by upgrading Anaconda to each individual version:

    conda install anaconda=2018.12
    conda install anaconda=2019.03
    conda install anaconda=2019.07
    conda install anaconda=2019.10

I'm going to close this issue as it isn't something I'm going to follow up on but it seems there are 2 bugs here:

1. conda does not show underlying tracebacks on `CondaMultiError`
2. conda does not upgrade Anaconda correctly from 5.3.0 -> 2019.10 Python 3.7 Windows 10 64-bit, the SSL DLL Anaconda distributes fail to work.
