### ISSUE TITLE
Intermittent segfault when installing packages

### ISSUE THREAD

**Issue by alanhdu** [conda/conda#9414]
## Current Behavior

Over the last couple of weeks, I've noticed periodic segfaults when using conda (usually with `conda install` or `conda update`). These are usually intermittent -- rerunning the command I haven't been able to reliably reproduce this, but I finally managed to grab a core dump.

This is with `conda 4.7.12` on Ubuntu 18.04 with Python 3.7.3

### Steps to Reproduce

Unfortunately, I have not been able to reproduce this -- I managed to reproduce it once in gdb (and grabbed a core dump), but when I ran it a third time everything mysteriously worked!

The core dump is at [core1.zip](https://github.com/conda/conda/files/3817735/core1.zip)

From GDB, it seems like this is calling `PyBytes_FromString` on a null pointer somewhere in  from `conda_package_handling.archive_utils.extract_file`:

```
>>> down
#1  0x000055555568ac9d in PyBytes_FromString () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/bytesobject.c:141
141	in /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/bytesobject.c
>>> info args
str = 0x0
>>> info locals
size = <optimized out>
op = <optimized out>
```

The furthest python stack I could reconstruct was

```
>>> py-bt
Traceback (most recent call first):
  <built-in function extract_file>
  (frame information optimized out)
  (frame information optimized out)
  File "/opt/anaconda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 135, in extract
    _tar_xf(fn, dest_dir)
```

where the relevant C stack is:
```
>>> bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:62
#1  0x000055555568ac9d in PyBytes_FromString () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/bytesobject.c:141
#2  0x00007ffff4a4587f in __pyx_pw_22conda_package_handling_16archive_utils_cy_1extract_file () from /opt/anaconda/lib/python3.7/site-packages/conda_package_handling/archive_utils_cy.cpython-37m-x86_64-linux-gnu.so
#3  0x00005555556bc59c in _PyMethodDef_RawFastCallKeywords () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/call.c:644
#4  0x00005555556bc891 in _PyCFunction_FastCallKeywords (func=<built-in function extract_file>, args=<optimized out>, nargs=<optimized out>, kwnames=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/call.c:730
#5  0x0000555555729fce in call_function (kwnames=0x0, oparg=1, pp_stack=<synthetic pointer>) at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Python/ceval.c:4568
#6  _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Python/ceval.c:3093
#7  0x00005555556bbcfb in function_code_fastcall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/call.c:283
#8  _PyFunction_FastCallKeywords () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/call.c:408
#9  0x0000555555729c59 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Python/ceval.c:4616
#10 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Python/ceval.c:3093
#11 0x00005555556bbcfb in function_code_fastcall (globals=<optimized out>, nargs=2, args=<optimized out>, co=<optimized out>) at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/call.c:283
#12 _PyFunction_FastCallKeywords () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Objects/call.c:408
#13 0x0000555555725506 in call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>) at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Python/ceval.c:4616
#14 _PyEval_EvalFrameDefault () at /home/conda/feedstock_root/build_artifacts/python_1562015400360/work/Python/ceval.c:3124
```

<details>
<summary> full py-bt </summary>

```
Traceback (most recent call first):
  <built-in function extract_file>
  (frame information optimized out)
  (frame information optimized out)
  File "/opt/anaconda/lib/python3.7/site-packages/conda_package_handling/tarball.py", line 135, in extract
    _tar_xf(fn, dest_dir)
  File "/opt/anaconda/lib/python3.7/site-packages/conda_package_handling/api.py", line 58, in extract
    SUPPORTED_EXTENSIONS[ext].extract(fn, dest_dir, components=components)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/gateways/disk/create.py", line 219, in extract_tarball
    conda_package_handling.api.extract(tarball_full_path, dest_dir=destination_directory)
  (frame information optimized out)
  (frame information optimized out)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 244, in _package_cache_records
    self.load()
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 130, in query
    return (pcrec for pcrec in itervalues(self._package_cache_records) if pcrec == param)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 501, in <genexpr>
    for pkgs_dir in context.pkgs_dirs)
  (frame information optimized out)
  <built-in method next of module object at remote 0x7ffff7fb4c28>
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 503, in make_actions_for_record
    ), None)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 612, in <genexpr>
    for prec in self.link_precs)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 612, in prepare
    for prec in self.link_precs)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
    return f(*args, **kwds)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/core/link.py", line 901, in _make_legacy_action_groups
    self._pfe.prepare()
  (frame information optimized out)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/cli/install.py", line 333, in handle_txn
    unlink_link_transaction.print_transaction_summary()
  File "/opt/anaconda/lib/python3.7/site-packages/conda/cli/install.py", line 317, in install
    handle_txn(unlink_link_transaction, prefix, args, newenv)
  (frame information optimized out)
  (frame information optimized out)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/exceptions.py", line 1074, in __call__
    return func(*args, **kwargs)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/exceptions.py", line 1366, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/opt/anaconda/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/opt/anaconda/condabin/conda", line 13, in <module>
    sys.exit(main())
```

where

```
>>> py-print fn
local 'fn' = '/opt/anaconda/pkgs/python-3.6.7-h357f687_1006.tar.bz2'
>>> py-print dest_dir
local 'dest_dir' = '/opt/anaconda/pkgs/python-3.6.7-h357f687_1006'
```

</details>

## Expected Behavior

Hopefully, the `conda` would not segfault. If it does, then it should at deterministically segfault!

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /opt/anaconda
            shell level : 2
       user config file : /home/alan/.condarc
 populated config files : /home/alan/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /opt/anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/anaconda/pkgs
                          /home/alan/.conda/pkgs
       envs directories : /opt/anaconda/envs
                          /home/alan/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Linux/5.0.0-23-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /home/alan/.condarc <==
channel_priority: strict
channels:
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/anaconda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                1.2.0                    py37_0    conda-forge
astor                     0.8.0                    pypi_0    pypi
bzip2                     1.0.8                h516909a_1    conda-forge
ca-certificates           2019.9.11            hecc5488_0    conda-forge
certifi                   2019.9.11                py37_0    conda-forge
cffi                      1.13.2           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                      pypi_0    pypi
conda                     4.7.12                   py37_0    conda-forge
conda-package-handling    1.6.0            py37h516909a_0    conda-forge
cryptography              2.7              py37h72c5cf5_0    conda-forge
idna                      2.8                   py37_1000    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
pip                       19.3.1                   py37_0    conda-forge
pur                       5.2.2                    pypi_0    pypi
pycosat                   0.6.3           py37h516909a_1002    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pysocks                   1.7.1                    py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.22.0                   py37_1    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
setuptools                41.6.0                   py37_1    conda-forge
six                       1.12.0                py37_1001    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tk                        8.6.9             hed695b0_1003    conda-forge
tqdm                      4.36.1                     py_0    conda-forge
urllib3                   1.25.6                   py37_0    conda-forge
wheel                     0.33.6                   py37_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</p></details>

**Comment by alanhdu** [comment]
Hm okay -- I think I actually have a quasi reproducer here -- it has to do with *interrupting* a download.

```
docker run -it continuumio/miniconda3:4.7.12 /bin/bash
(base) root@f6779eaa53e5:/# conda create -n test --yes python=3.6  
# Type Control-C repeatedly when conda starts download and extracting packages
(base) root@36259a25c1bc:/# conda create -n test python=3.5
```

About 1 every 3 times I do this results in a segmentation fault.
