### ISSUE TITLE
Preprocessing selector not reflected in installed dependencies

### ISSUE THREAD

**Issue by langmm** [conda/conda#9440]
## Current Behavior

Installing the `importlib_metadata` package in a Python 2.7 env does not install those dependencies  marked as Python 2 only with the `[py2k]` preprocessor selector in the [recipe](https://github.com/conda-forge/importlib_metadata-feedstock/blob/master/recipe/meta.yaml). I don't think this is an issue with the particular package recipe or `conda-build` as the tests of the recipe did not fail.

### Steps to Reproduce

```
> conda create -n test27 python=2.7
> conda activate test27
> conda install importlib_metadata
> python
Python 2.7.15 (default, Jul  2 2019, 00:55:11) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib_metadata
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\meaga\AppData\Local\Continuum\miniconda3\envs\test27\lib\site-packages\importlib_metadata\__init__.py", line 6, in <module>
    from . import _common
  File "C:\Users\meaga\AppData\Local\Continuum\miniconda3\envs\test27\lib\site-packages\importlib_metadata\_common.py", line 18, in <module>
    from contextlib2 import suppress  # noqa
ImportError: No module named contextlib2
>>>
```

## Expected Behavior

All of the required dependencies should be installed.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : test27
    active env location : C:\Users\meaga\AppData\Local\Continuum\miniconda3\envs\test27
            shell level : 2
       user config file : C:\Users\meaga\.condarc
 populated config files : C:\Users\meaga\.condarc
          conda version : 4.7.12
    conda-build version : 3.18.11
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\Users\meaga\AppData\Local\Continuum\miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\meaga\AppData\Local\Continuum\miniconda3\pkgs
                          C:\Users\meaga\.conda\pkgs
                          C:\Users\meaga\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\meaga\AppData\Local\Continuum\miniconda3\envs
                          C:\Users\meaga\.conda\envs
                          C:\Users\meaga\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\meaga\.condarc <==
channel_priority: flexible
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at C:\Users\meaga\AppData\Local\Continuum\miniconda3\envs\test27:
#
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0    conda-forge
certifi                   2019.9.11                py27_0    conda-forge
functools32               3.2.3.2                    py_3    conda-forge
importlib_metadata        0.5                        py_0    conda-forge
jsonschema                3.1.1                    py27_0    conda-forge
pip                       19.3.1                   py27_0    conda-forge
pyrsistent                0.15.5           py27h0c8e037_0    conda-forge
python                    2.7.15            h2880e7c_1009    conda-forge
setuptools                41.6.0                   py27_1    conda-forge
six                       1.13.0                   py27_0    conda-forge
vc                        9                    h7299396_1    defaults
vs2008_runtime            9.0.30729.6161                0    conda-forge
wheel                     0.33.6                   py27_0    conda-forge
wincertstore              0.2                   py27_1003    conda-forge
```
</p></details>

**Comment by soapy1** [comment]
I can't seem to reproduce this issue. What is the output after you run `conda install importlib_metadata`? Can you check which python is getting invoked `which -a python`?

**Comment by kalefranz** [comment]
Is `[py2k]` even a valid selector??? I thought it was `[py2]` or `[py27]` or `[py<3]`. I didn't know `[py2k]` was ever a thing...

**Comment by kalefranz** [comment]
Regardless, this is a conda-build issue, not a conda issue.

**Comment by langmm** [comment]
I am going to close this as the py2k is doubly deprecated at this point.
