### ISSUE TITLE
Solving environment: failed with current_repodata.json, will retry with next repodata source.

### ISSUE THREAD

**Issue by samiarshad** [conda/conda#9451]
## Current Behavior

Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1062, in __call__
        return func(*args, **kwargs)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/cli/install.py", line 256, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 150, in solve_for_diff
        force_remove)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._run_sat(ssc)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/core/solve.py", line 780, in _run_sat
        repodata_fn=self._repodata_fn)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 1220, in solve
        self.find_conflicts(specs, specs_to_add, history_specs)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 336, in find_conflicts
        bad_deps = self.build_conflict_map(specs, specs_to_add, history_specs)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/resolve.py", line 418, in build_conflict_map
        bad_deps.extend(g.depth_first_search_by_name(spec, dep, sdeps[spec]))
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/models/prefix_graph.py", line 450, in depth_first_search_by_name
        matchspecs_for_chain.append(MatchSpec.merge(matchspecs_to_merge)[0])
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 467, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 467, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 498, in _merge
        final = this_component.merge(that_component)
      File "/home/mxa4183xx/anaconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 751, in merge
        % (self.raw_value, other.raw_value))
    ValueError: Incompatible component merge:
      - 'py27he6673a0_3'
      - 'py36h8fa1ad8_3'

`$ /home/mxa4183xx/anaconda3/bin/conda install opencv`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/home/mxa4183xx/anaconda3/bin/conda
             CONDA_PREFIX=/home/mxa4183xx/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/home/mxa4183xx/anaconda3/bin/python
               CONDA_ROOT=/home/mxa4183xx/anaconda3
              CONDA_SHLVL=1
          LD_LIBRARY_PATH=/usr/local/cuda-9.0/lib64:
                     PATH=/home/mxa4183xx/anaconda3/bin:/home/mxa4183xx/anaconda3/bin:/home/mxa4
                          183xx/anaconda3/condabin:/usr/local/cuda-9.0/bin:/usr/local/sbin:/usr/
                          local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/s
                          nap/bin
               PYTHONPATH=/media/mxa4183xx/e3c39b5c-e318-4e91-9e0d-20e57d5ca51d/Work/:/media/mxa
                          4183xx/e3c39b5c-e318-4e91-9e0d-20e57d5ca51d/shapenet_python:
       REQUESTS_CA_BUNDLE=<not set>
       SHAPENET_CORE_PATH=/media/mxa4183xx/e3c39b5c-e318-4e91-9e0d-20e57d5ca51d/shapenet_python/
                          data/ShapeNetCore.v1
            SSL_CERT_FILE=<not set>
               WINDOWPATH=2

     active environment : base
    active env location : /home/mxa4183xx/anaconda3
            shell level : 1
       user config file : /home/mxa4183xx/.condarc
 populated config files : 
          conda version : 4.7.9
    conda-build version : 3.18.8
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.2
       base environment : /home/mxa4183xx/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mxa4183xx/anaconda3/pkgs
                          /home/mxa4183xx/.conda/pkgs
       envs directories : /home/mxa4183xx/anaconda3/envs
                          /home/mxa4183xx/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.9 requests/2.22.0 CPython/3.6.8 Linux/4.18.0-25-generic ubuntu/18.10 glibc/2.28
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

### Steps to Reproduce

```
 conda install opencv

```

## Expected Behavior

install packages

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
active environment : base
    active env location : /home/mxa4183xx/anaconda3
            shell level : 1
       user config file : /home/mxa4183xx/.condarc
 populated config files : 
          conda version : 4.7.9
    conda-build version : 3.18.8
         python version : 3.6.8.final.0
       virtual packages : __cuda=10.2
       base environment : /home/mxa4183xx/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mxa4183xx/anaconda3/pkgs
                          /home/mxa4183xx/.conda/pkgs
       envs directories : /home/mxa4183xx/anaconda3/envs
                          /home/mxa4183xx/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.9 requests/2.22.0 CPython/3.6.8 Linux/4.18.0-25-generic ubuntu/18.10 glibc/2.28
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py36_0    defaults
_libgcc_mutex             0.1                        main    defaults
_tflow_select             2.1.0                       gpu    defaults
absl-py                   0.7.1                    py36_0    defaults
alabaster                 0.7.12                   py36_0    defaults
anaconda-client           1.7.2                    py36_0    defaults
anaconda-navigator        1.9.7                    py36_0    defaults
anaconda-project          0.8.3                      py_0    defaults
apptools                  4.4.0                    py36_1    defaults
asn1crypto                0.24.0                   py36_0    defaults
astor                     0.7.1                    py36_0    defaults
astroid                   2.2.5                    py36_0    defaults
astropy                   3.2.1            py36h7b6447c_0    defaults
atomicwrites              1.3.0                    py36_1    defaults
attrs                     19.1.0                   py36_1    defaults
babel                     2.7.0                      py_0    defaults
backcall                  0.1.0                    py36_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.5                        py_2    defaults
backports.os              0.1.1                    py36_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py36_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.7.1                    py36_1    defaults
bitarray                  0.9.3            py36h7b6447c_0    defaults
bkcharts                  0.2                      py36_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py36_0    defaults
blosc                     1.15.0               hd408876_0    defaults
bokeh                     1.2.0                    py36_0    defaults
boto                      2.49.0                   py36_0    defaults
bottleneck                1.2.1            py36h035aef0_1    defaults
bzip2                     1.0.6                h14c3975_5    defaults
c-ares                    1.15.0               h7b6447c_1    defaults
ca-certificates           2019.5.15                     0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2019.6.16                py36_0    defaults
cffi                      1.12.3           py36h2e261b9_0    defaults
chardet                   3.0.4                    py36_1    defaults
click                     7.0                      py36_0    defaults
cloudpickle               1.2.1                      py_0    defaults
clyent                    1.2.2                    py36_1    defaults
colorama                  0.4.1                    py36_0    defaults
conda                     4.7.9                    py36_0    defaults
conda-build               3.18.8                   py36_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.11                   py36_0    defaults
conda-verify              3.4.2                      py_1    defaults
configobj                 5.0.6                    py36_1    defaults
contextlib2               0.5.5                    py36_0    defaults
cryptography              2.7              py36h1ba5d50_0    defaults
cudatoolkit               9.2                           0    defaults
cudnn                     7.6.0                 cuda9.2_0    defaults
cupti                     9.2.148                       0    defaults
curl                      7.64.0               hbc83047_2    defaults
cycler                    0.10.0                   py36_0    defaults
cython                    0.29.12          py36he6710b0_0    defaults
cytoolz                   0.10.0           py36h7b6447c_0    defaults
dask                      2.1.0                      py_0    defaults
dask-core                 2.1.0                      py_0    defaults
dbus                      1.13.6               h746ee38_0    defaults
decorator                 4.4.0                    py36_1    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               2.1.0                      py_0    defaults
docutils                  0.14                     py36_0    defaults
entrypoints               0.3                      py36_0    defaults
envisage                  4.7.2                      py_0    defaults
et_xmlfile                1.0.1                    py36_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fastcache                 1.1.0            py36h7b6447c_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.1.1                      py_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
fribidi                   1.0.5                h7b6447c_0    defaults
future                    0.17.1                   py36_0    defaults
gast                      0.2.2                    py36_0    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.4.0            py36h7b6447c_0    defaults
glib                      2.56.2               hd408876_0    defaults
glob2                     0.7                        py_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py36h10f8cd9_2    defaults
graphite2                 1.3.13               h23475e2_0    defaults
greenlet                  0.4.15           py36h7b6447c_0    defaults
grpcio                    1.16.1           py36hf8bcb03_1    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.9.0            py36h7918eee_0    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf4                      4.2.13               h3ca952b_2    defaults
hdf5                      1.10.4               hb1b8bf9_0    defaults
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1                    py36_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      py36_0    defaults
imageio                   2.5.0                    py36_0    defaults
imagesize                 1.1.0                    py36_0    defaults
importlib_metadata        0.17                     py36_1    defaults
intel-openmp              2019.3                      199    defaults
ipykernel                 5.1.1            py36h39e3cac_0    defaults
ipython                   7.6.1            py36h39e3cac_0    defaults
ipython_genutils          0.2.0                    py36_0    defaults
ipywidgets                7.5.0                      py_0    defaults
isort                     4.3.21                   py36_0    defaults
itsdangerous              1.1.0                    py36_0    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.13.3                   py36_0    defaults
jeepney                   0.4                      py36_0    defaults
jinja2                    2.10.1                   py36_0    defaults
joblib                    0.13.2                   py36_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
json5                     0.8.4                      py_0    defaults
jsoncpp                   1.8.4                hfd86e86_0    defaults
jsonschema                3.0.1                    py36_0    defaults
jupyter                   1.0.0                    py36_7    defaults
jupyter_client            5.3.1                      py_0    defaults
jupyter_console           6.0.0                    py36_0    defaults
jupyter_core              4.5.0                      py_0    defaults
jupyterlab                1.0.2            py36hf63ae98_0    defaults
jupyterlab_server         1.0.0                      py_0    defaults
keras-applications        1.0.8                      py_0    defaults
keras-preprocessing       1.1.0                      py_1    defaults
keyring                   18.0.0                   py36_0    defaults
kiwisolver                1.1.0            py36he6710b0_0    defaults
krb5                      1.16.1               h173b8e3_7    defaults
lazy-object-proxy         1.4.1            py36h7b6447c_0    defaults
libarchive                3.3.3                h5d8350f_5    defaults
libcurl                   7.64.0               h20c2e04_2    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
liblief                   0.9.0                h7725739_2    defaults
libnetcdf                 4.6.1                h11d0813_2    defaults
libogg                    1.3.2                h7b6447c_0    defaults
libpng                    1.6.36               hbc83047_0    defaults
libprotobuf               3.8.0                hd408876_0    defaults
libsodium                 1.0.16               h1bed415_0    defaults
libssh2                   1.8.0                h1ba5d50_4    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtheora                 1.1.1                h5ab3b9f_1    defaults
libtiff                   4.0.10               h2733197_2    defaults
libtool                   2.4.6                h7b6447c_5    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libvorbis                 1.3.6                h7b6447c_0    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                he19cac6_0    defaults
libxslt                   1.1.33               h7d1a2b0_0    defaults
llvmlite                  0.29.0           py36hd408876_0    defaults
locket                    0.2.0                    py36_1    defaults
lxml                      4.3.4            py36hefd8a0e_0    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
markdown                  3.1.1                    py36_0    defaults
markupsafe                1.1.1            py36h7b6447c_0    defaults
matplotlib                3.0.3            py36h5429711_0    defaults
mayavi                    4.6.2            py36hcf37d21_4    defaults
mccabe                    0.6.1                    py36_1    defaults
mistune                   0.8.4            py36h7b6447c_0    defaults
mkl                       2019.3                      199    defaults
mkl-service               2.0.2            py36h7b6447c_0    defaults
mkl_fft                   1.0.12           py36ha843d7b_0    defaults
mkl_random                1.0.2            py36hd81dba3_0    defaults
more-itertools            7.0.0                    py36_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.1                hdf1c602_3    defaults
mpmath                    1.1.0                    py36_0    defaults
msgpack-python            0.6.1            py36hfd86e86_1    defaults
multipledispatch          0.6.0                    py36_0    defaults
navigator-updater         0.2.1                    py36_0    defaults
nbconvert                 5.5.0                      py_0    defaults
nbformat                  4.4.0                    py36_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.3                        py_0    defaults
nltk                      3.4.4                    py36_0    defaults
nose                      1.3.7                    py36_2    defaults
notebook                  6.0.0                    py36_0    defaults
numba                     0.44.1           py36h962f231_0    defaults
numexpr                   2.6.9            py36h9e4a6bb_0    defaults
numpy                     1.16.4           py36h7e9f1db_0    defaults
numpy-base                1.16.4           py36hde5b4d6_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py36_0    defaults
open3d                    0.7.0.0                  py36_0    open3d-admin
openpyxl                  2.6.2                      py_0    defaults
openssl                   1.1.1c               h7b6447c_1    defaults
packaging                 19.0                     py36_0    defaults
pandas                    0.24.2           py36he6710b0_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py36_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.5.0                      py_0    defaults
partd                     1.0.0                      py_0    defaults
patchelf                  0.9                  he6710b0_3    defaults
path.py                   12.0.1                     py_0    defaults
pathlib2                  2.3.4                    py36_0    defaults
patsy                     0.5.1                    py36_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.7.0                    py36_0    defaults
pickleshare               0.7.5                    py36_0    defaults
pillow                    6.1.0            py36h34e0f95_0    defaults
pip                       19.1.1                   py36_0    defaults
pixman                    0.38.0               h7b6447c_0    defaults
pkginfo                   1.5.0.1                  py36_0    defaults
pluggy                    0.12.0                     py_0    defaults
ply                       3.11                     py36_0    defaults
progress                  1.5                      py36_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py36_0    defaults
protobuf                  3.8.0            py36he6710b0_0    defaults
psutil                    5.6.3            py36h7b6447c_0    defaults
ptyprocess                0.6.0                    py36_0    defaults
py                        1.8.0                    py36_0    defaults
py-lief                   0.9.0            py36h7725739_2    defaults
pycodestyle               2.5.0                    py36_0    defaults
pycosat                   0.6.3            py36h14c3975_0    defaults
pycparser                 2.19                     py36_0    defaults
pycrypto                  2.6.1            py36h14c3975_9    defaults
pycurl                    7.43.0.2         py36h1ba5d50_0    defaults
pyface                    6.0.0                    py36_0    defaults
pyflakes                  2.1.1                    py36_0    defaults
pygments                  2.4.2                      py_0    defaults
pylint                    2.3.1                    py36_0    defaults
pyodbc                    4.0.26           py36he6710b0_0    defaults
pyopenssl                 19.0.0                   py36_0    defaults
pyparsing                 2.4.0                      py_0    defaults
pyqt                      5.9.2            py36h05f1152_2    defaults
pyrsistent                0.14.11          py36h7b6447c_0    defaults
pysocks                   1.7.0                    py36_0    defaults
pytables                  3.5.1            py36h71ec239_0    defaults
pytest                    5.0.1                    py36_0    defaults
pytest-arraydiff          0.3              py36h39e3cac_0    defaults
pytest-astropy            0.5.0                    py36_0    defaults
pytest-doctestplus        0.3.0                    py36_0    defaults
pytest-openfiles          0.3.2                    py36_0    defaults
pytest-remotedata         0.3.1                    py36_0    defaults
python                    3.6.8                h0371630_0    defaults
python-dateutil           2.8.0                    py36_0    defaults
python-libarchive-c       2.8                     py36_11    defaults
pytz                      2019.1                     py_0    defaults
pywavelets                1.0.3            py36hdd07704_1    defaults
pyyaml                    5.1.1            py36h7b6447c_0    defaults
pyzmq                     18.0.0           py36he6710b0_0    defaults
qt                        5.9.7                h5867ecd_1    defaults
qtawesome                 0.5.7                    py36_1    defaults
qtconsole                 4.5.1                      py_0    defaults
qtpy                      1.8.0                      py_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py36_0    defaults
rope                      0.14.0                     py_0    defaults
ruamel_yaml               0.15.46          py36h14c3975_0    defaults
scikit-image              0.15.0           py36he6710b0_0    defaults
scikit-learn              0.21.1           py36hd81dba3_0    defaults
scipy                     1.2.1            py36h7c811a0_0    defaults
seaborn                   0.9.0                    py36_0    defaults
secretstorage             3.1.1                    py36_0    defaults
send2trash                1.5.0                    py36_0    defaults
setuptools                41.0.1                   py36_0    defaults
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3                  py36_0    defaults
sip                       4.19.8           py36hf484d3e_0    defaults
six                       1.12.0                   py36_0    defaults
snappy                    1.1.7                hbae5bb6_3    defaults
snowballstemmer           1.9.0                      py_0    defaults
sortedcollections         1.1.2                    py36_0    defaults
sortedcontainers          2.1.0                    py36_0    defaults
soupsieve                 1.8                      py36_0    defaults
sphinx                    2.1.2                      py_0    defaults
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.3.6                    py36_0    defaults
spyder-kernels            0.5.1                    py36_0    defaults
sqlalchemy                1.3.5            py36h7b6447c_0    defaults
sqlite                    3.27.2               h7b6447c_0    defaults
statsmodels               0.10.0           py36hdd07704_0    defaults
sympy                     1.4                      py36_0    defaults
tbb                       2019.4               hfd86e86_0    defaults
tblib                     1.4.0                      py_0    defaults
tensorboard               1.12.2           py36he6710b0_0    defaults
tensorflow                1.12.0          gpu_py36he74679b_0    defaults
tensorflow-base           1.12.0          gpu_py36had579c0_0    defaults
tensorflow-gpu            1.12.0               h0d30ee6_0    defaults
termcolor                 1.1.0                    py36_1    defaults
terminado                 0.8.2                    py36_0    defaults
testpath                  0.4.2                    py36_0    defaults
tflearn                   0.3.2            py36he51c03d_0    contango
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.3            py36h7b6447c_0    defaults
tqdm                      4.32.1                     py_0    defaults
traitlets                 4.3.2                    py36_0    defaults
traits                    5.1.1            py36h7b6447c_0    defaults
traitsui                  6.1.1                      py_0    defaults
typed-ast                 1.3.4            py36h7b6447c_0    defaults
unicodecsv                0.14.1                   py36_0    defaults
unixodbc                  2.3.7                h14c3975_0    defaults
urllib3                   1.24.2                   py36_0    defaults
vtk                       8.2.0           py36haa4764d_200    defaults
wcwidth                   0.1.7                    py36_0    defaults
webencodings              0.5.1                    py36_1    defaults
werkzeug                  0.15.4                     py_0    defaults
wget                      1.20.1               h20c2e04_0    defaults
wheel                     0.33.4                   py36_0    defaults
widgetsnbextension        3.5.0                    py36_0    defaults
wrapt                     1.11.2           py36h7b6447c_0    defaults
wurlitzer                 1.0.2                    py36_0    defaults
xlrd                      1.2.0                    py36_0    defaults
xlsxwriter                1.1.8                      py_0    defaults
xlwt                      1.3.0                    py36_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.3.1                he6710b0_3    defaults
zict                      1.0.0                      py_0    defaults
zipp                      0.5.1                      py_0    defaults
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults

```
</p></details>

**Comment by Idodox** [comment]
Any update on this? can confirm it is still happening.

**Comment by samiarshad** [comment]
I have found a workaround. Create a new environment for your work. The issue seems to be in the base environment only.

**Comment by Idodox** [comment]
Unfortunately in my case it seems to sporadically happen in regular env's as well. Recreating the env. from scratch and reinstalling everything fixed the issue.

**Comment by fouerghi** [comment]
Also getting this... any updates?

**Comment by Psp29onetwo** [comment]
conda config --append channels conda-forge

worked for me even for .yml or .yaml file

**Comment by kskollepara** [comment]
still facing this issue

**Comment by newptcai** [comment]
I got this when I try to install sage in base by
```
conda install -c conda-forge sage
```

**Comment by haldar55** [comment]
Sitting here in 2023, still facing the issue..

**Comment by akhiljalan** [comment]
Happens for me as well, even when I create a fresh environment with Python 3.9.7 and try to install sage with conda.
