### ISSUE TITLE
Intermittent failures due to `OSError: [Errno 22] Invalid argument` when installing packages

### ISSUE THREAD

**Issue by DanielFEvans** [conda/conda#9459]
## Current Behavior
`conda install ...` intermittently fails with "OSError: [Errno 22] Invalid argument" when "Collecting package metadata (repodata.json)". This causes the entire installation to fail. I don't have exact numbers on the frequency, but on a build server doing a couple of dozen Conda-related runs per day, the issue occurs at least daily.

### Steps to Reproduce

```
conda env update -p c:\jenkins2\env\Farmcat_commit_windows -f requirements/environment.yml

ollecting package metadata (repodata.json): ...working... failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "C:\bin\Miniconda3\lib\site-packages\conda\exceptions.py", line 1074, in __call__
        return func(*args, **kwargs)
      File "C:\bin\Miniconda3\lib\site-packages\conda_env\cli\main.py", line 78, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "C:\bin\Miniconda3\lib\site-packages\conda_env\cli\main_update.py", line 124, in execute
        result[installer_type] = installer.install(prefix, specs, args, env)
      File "C:\bin\Miniconda3\lib\site-packages\conda_env\installers\conda.py", line 27, in install
        unlink_link_transaction = solver.solve_for_transaction(prune=getattr(args, 'prune', False))
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "C:\bin\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\solve.py", line 1004, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\index.py", line 214, in get_reduced_index
        repodata_fn=repodata_fn)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 97, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "C:\bin\Miniconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "C:\bin\Miniconda3\lib\concurrent\futures\_base.py", line 425, in result
        return self.__get_result()
      File "C:\bin\Miniconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "C:\bin\Miniconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 90, in <lambda>
        package_ref_or_match_spec))
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 102, in query
        self.load()
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 166, in load
        _internal_state = self._load()
      File "C:\bin\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 261, in _load
        with io_open(self.cache_path_json, 'w') as fh:
    OSError: [Errno 22] Invalid argument: 'C:\\bin\\Miniconda3\\pkgs\\cache\\9fea5de8.json'

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
                CONDA_BAT=C:\bin\Miniconda3\condabin\conda.bat
        CONDA_DEFAULT_ENV=c:\jenkins2\env\Farmcat_commit_windows
                CONDA_EXE=C:\bin\Miniconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="C:\bin\Miniconda3\condabin\..\Scripts\conda.exe"
               CONDA_PATH=C:\bin\Miniconda3
             CONDA_PREFIX=c:\jenkins2\env\Farmcat_commit_windows
           CONDA_PREFIX_1=C:\bin\Miniconda3
          CONDA_PROD_REPO=file://\\rml-service01/Development/conda_packages
    CONDA_PROMPT_MODIFIER=(c:\jenkins2\env\Farmcat_commit_windows)
         CONDA_PYTHON_EXE=C:\bin\Miniconda3\python.exe
               CONDA_ROOT=C:\bin\Miniconda3
              CONDA_SHLVL=2
          CONDA_TEST_REPO=file://\\rml-service01/Development/conda_packages_test
                 ENV_PATH=c:\jenkins2\env\Farmcat_commit_windows
         GDAL_DRIVER_PATH=c:\jenkins2\env\Farmcat_commit_windows\Library\bin
                     PATH=C:\bin\Miniconda3;C:\bin\Miniconda3\Library\mingw-w64\bin;C:\bin\Minic
                          onda3\Library\usr\bin;C:\bin\Miniconda3\Library\bin;C:\bin\Miniconda3\
                          Scripts;C:\bin\Miniconda3\bin;c:\jenkins2\env\Farmcat_commit_windows;c
                          :\jenkins2\env\Farmcat_commit_windows\Library\mingw-w64\bin;c:\jenkins
                          2\env\Farmcat_commit_windows\Library\usr\bin;c:\jenkins2\env\Farmcat_c
                          ommit_windows\Library\bin;c:\jenkins2\env\Farmcat_commit_windows\Scrip
                          ts;c:\jenkins2\env\Farmcat_commit_windows\bin;C:\bin\Miniconda3\condab
                          in;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program
                          Data\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\Sy
                          stem32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\bin\arcanist
                          \bin;c:\bin\php;C:\bin\Git\cmd;C:\OSGeo4W64\bin;.
             PSMODULEPATH=C:\Windows\system32\WindowsPowerShell\v1.0\Modules\
            PYTHON_27_EXE=/usr/bin/python2
            PYTHON_36_EXE=/usr/bin/python36
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : c:\jenkins2\env\Farmcat_commit_windows
    active env location : c:\jenkins2\env\Farmcat_commit_windows
            shell level : 2
       user config file : C:\Windows\system32\config\systemprofile\.condarc
 populated config files : C:\bin\Miniconda3\.condarc
                          C:\Windows\system32\config\systemprofile\.condarc
                          c:\jenkins2\env\Farmcat_commit_windows\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : C:\bin\Miniconda3  (writable)
           channel URLs : file://rml-service01/Development/conda_packages_test/win-64
                          file://rml-service01/Development/conda_packages_test/noarch
                          file://rml-service01/Development/conda_packages/win-64
                          file://rml-service01/Development/conda_packages/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          http://rml-dev02:85/prod/win-64
                          http://rml-dev02:85/prod/noarch
          package cache : C:\bin\Miniconda3\pkgs
                          C:\Windows\system32\config\systemprofile\.conda\pkgs
                          C:\Windows\system32\config\systemprofile\AppData\Local\conda\conda\pkgs
       envs directories : C:\bin\Miniconda3\envs
                          C:\Windows\system32\config\systemprofile\.conda\envs
                          C:\Windows\system32\config\systemprofile\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```

## Expected Behavior
Conda should not fail as regularly as we observe while reading package metadata. A more helpful error should be given if the problem is caused by external issues (e.g. bad downloads), allowing the user to diagnose the problem.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : c:\jenkins2\env\Farmcat_commit_windows
    active env location : c:\jenkins2\env\Farmcat_commit_windows
            shell level : 2
       user config file : C:\Windows\system32\config\systemprofile\.condarc
 populated config files : C:\bin\Miniconda3\.condarc
                          C:\Windows\system32\config\systemprofile\.condarc
                          c:\jenkins2\env\Farmcat_commit_windows\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : C:\bin\Miniconda3  (writable)
           channel URLs : file://rml-service01/Development/conda_packages_test/win-64
                          file://rml-service01/Development/conda_packages_test/noarch
                          file://rml-service01/Development/conda_packages/win-64
                          file://rml-service01/Development/conda_packages/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          http://rml-dev02:85/prod/win-64
                          http://rml-dev02:85/prod/noarch
          package cache : C:\bin\Miniconda3\pkgs
                          C:\Windows\system32\config\systemprofile\.conda\pkgs
                          C:\Windows\system32\config\systemprofile\AppData\Local\conda\conda\pkgs
       envs directories : C:\bin\Miniconda3\envs
                          C:\Windows\system32\config\systemprofile\.conda\envs
                          C:\Windows\system32\config\systemprofile\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.3 Windows/2012ServerR2 Windows/6.3.9600
          administrator : True
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
(c:\jenkins2\env\Farmcat_commit_windows) c:\jenkins2\workspace\Farmcat_commit_windows>conda config --show-sources 
==> C:\bin\Miniconda3\.condarc <==
channels:
  - file://\\rml-service01\Development\conda_packages_test
  - file://\\rml-service01\Development\conda_packages
  - conda-forge
  - defaults

==> C:\Windows\system32\config\systemprofile\.condarc <==
local_repodata_ttl: 3600
channels:
  - http://rml-dev02:85/prod
  - conda-forge
  - defaults
report_errors: True

==> c:\jenkins2\env\Farmcat_commit_windows\.condarc <==
channels:
  - file://\\rml-service01\Development\conda_packages_test
  - file://\\rml-service01\Development\conda_packages
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by jontwo** [comment]
+1 we're seeing this happen quite often as well (and are uploading error reports every time it happens. You're welcome).

We can work around it by running `conda clean --all -y`, but it breaks the build when it happens and it's a pain. Conda should fail more gracefully when there is a problem in the cache.

**Comment by jontwo** [comment]
We're still regularly having this problem on our CI server and it is still frequently breaking the build. If we rerun with the same parameters, the build is fine.

I think it is a race condition where one job is writing to the repodata.json file while another build is trying to read it. Could you add a retry if the file cannot be read? It may be incomplete because it is in the middle of being updated.
