### ISSUE TITLE
Unable to install PyTorch on Macbook Pro

### ISSUE THREAD

**Issue by meelanc** [conda/conda#9470]
**I'm submitting a...**
  - [ X] bug report
  - [ ] feature request

### Steps to Reproduce

```
Traceback (most recent call last):
  File "/Users/mchoudha/anaconda/bin/conda-env", line 6, in <module>
    sys.exit(main())
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda_env/cli/main.py", line 65, in main
    return args_func(args, parser)
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda/cli/main.py", line 208, in args_func
    args.func(args, p)
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda_env/cli/main_create.py", line 89, in execute
    installer.install(prefix, pkg_specs, args, env)
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda_env/installers/conda.py", line 14, in install
    actions = plan.install_actions(prefix, index, specs)
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda/plan.py", line 397, in install_actions
    config.track_features, minimal_hint=minimal_hint):
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 739, in solve
    minimal_hint=minimal_hint)
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 507, in solve2
    clauses = set(self.gen_clauses(v, dists, specs, features))
  File "/Users/mchoudha/anaconda/lib/python3.4/site-packages/conda/resolve.py", line 342, in gen_clauses
    assert len(clause) > 1, '%s %r' % (fn1, ms)
AssertionError: numpy-base-1.14.6-py36ha711998_5.tar.bz2 MatchSpec('blas * openblas')
```

## Expected Behavior

Was trying to install PyTorch

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
% conda info
Current conda install:

             platform : osx-64
        conda version : 3.14.1
  conda-build version : 1.14.1
       python version : 3.4.3.final.0
     requests version : 2.7.0
     root environment : /Users/mchoudha/anaconda  (writable)
  default environment : /Users/mchoudha/anaconda
     envs directories : /Users/mchoudha/anaconda/envs
        package cache : /Users/mchoudha/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
onda config --show-sources
usage: conda config [-h] [--json] [--system | --file FILE]
                    (--get [KEY [KEY ...]] | --add KEY VALUE | --set KEY BOOL_VALUE | --remove KEY VALUE | --remove-key KEY)
                    [-f]
conda config: error: one of the arguments --get --add --set --remove --remove-key is required

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>
=
```
conda list --show-channel-urls
usage: conda [-h] [-V] [--debug] command ...
conda: error: unrecognized arguments: --show-channel-urls
```
</p></details>

**Comment by jjhelmus** [comment]
Currently pytorch is not available for macOS from the default channel.  The PyTorch project does provide packages on the `pytorch` channel.

Note that  the version of conda you are using in extremely old as is the Python version.  You will need to update both to be able to install pytorch.
