### ISSUE TITLE
libkea.so.1.4.7: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxB5cxx11Ey

### ISSUE THREAD

**Issue by parrenin** [conda/conda#9475]
### Steps to Reproduce

```
$ python -c "from osgeo import gdalconst"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/parrenif/anaconda3/lib/python3.7/site-packages/osgeo/__init__.py", line 26, in <module>
    _gdal = swig_import_helper()
  File "/home/parrenif/anaconda3/lib/python3.7/site-packages/osgeo/__init__.py", line 22, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/parrenif/anaconda3/lib/python3.7/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/parrenif/anaconda3/lib/python3.7/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/parrenif/anaconda3/lib/python3.7/site-packages/osgeo/../../.././libkea.so.1.4.7: undefined symbol: _ZNK2H510H5Location15getObjnameByIdxB5cxx11Ey
```

## Expected Behavior

There should be no error.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
$ conda info

     active environment : base
    active env location : /home/parrenif/anaconda3
            shell level : 1
       user config file : /home/parrenif/.condarc
 populated config files : /home/parrenif/.condarc
          conda version : 4.7.12
    conda-build version : 3.18.11
         python version : 3.7.0.final.0
       virtual packages : 
       base environment : /home/parrenif/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/intel/linux-64
                          https://conda.anaconda.org/intel/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/parrenif/anaconda3/pkgs
                          /home/parrenif/.conda/pkgs
       envs directories : /home/parrenif/anaconda3/envs
                          /home/parrenif/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.0 Linux/4.19.0-6-amd64 debian/10 glibc/2.28
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
$ conda config --show-sources
==> /home/parrenif/.condarc <==
channels:
  - intel
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
_libgcc_mutex             0.1                        main    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  custom                   py37_1    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.4                      py_0    defaults
asn1crypto                1.2.0                    py37_0    defaults
astroid                   2.3.3                    py37_0    defaults
astropy                   3.2.3            py37h7b6447c_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.3.0                     py_0    defaults
babel                     2.7.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
basemap                   1.2.0            py37h705c2d8_0    defaults
beautifulsoup4            4.8.1                    py37_0    defaults
bitarray                  1.1.0            py37h7b6447c_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.15.0               hd408876_0    defaults
bokeh                     1.4.0                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.3.1            py37hdd07704_0    defaults
bzip2                     1.0.6                        18    intel
ca-certificates           2019.10.16                    0    defaults
cairo                     1.14.12              h8948797_3    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.13.2           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.0                      py37_0    defaults
cloudpickle               1.2.2                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.1                    py37_0    defaults
conda                     4.7.12                   py37_0    defaults
conda-build               3.18.11                  py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py37h7b6447c_0    defaults
conda-verify              3.4.2                      py_1    defaults
contextlib2               0.6.0.post1                py_0    defaults
cryptography              2.3.1            py37hc365091_0    defaults
curl                      7.55.1               h78862de_4    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.14          py37he6710b0_0    defaults
cytoolz                   0.10.1           py37h7b6447c_0    defaults
dask                      2.8.1                      py_0    defaults
dask-core                 2.8.1                      py_0    defaults
dbus                      1.13.12              h746ee38_0    defaults
decorator                 4.4.1                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               2.8.1                      py_0    defaults
docutils                  0.15.2                   py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                he6710b0_0    defaults
fastcache                 1.1.0            py37h7b6447c_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.1.1                      py_0    defaults
fontconfig                2.13.0               h9420a91_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
freexl                    1.0.5                h14c3975_0    defaults
fribidi                   1.0.5                h7b6447c_0    defaults
fsspec                    0.6.0                      py_0    defaults
future                    0.18.2                   py37_0    defaults
gdal                      2.3.2            py37h2924dbc_0    defaults
geos                      3.6.2                heeff764_2    defaults
get_terminal_size         1.0.0                haa9412d_0    defaults
gevent                    1.4.0            py37h7b6447c_0    defaults
giflib                    5.1.4                h14c3975_1    defaults
glib                      2.63.1               h5a9c865_0    defaults
glob2                     0.7                        py_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py37h10f8cd9_2    defaults
graphite2                 1.3.13               h23475e2_0    defaults
greenlet                  0.4.15           py37h7b6447c_0    defaults
gst-plugins-base          1.14.0               hbbd80ab_1    defaults
gstreamer                 1.14.0               hb453b48_1    defaults
h5py                      2.8.0            py37h989c5e5_3    defaults
harfbuzz                  1.8.8                hffaf4a1_0    defaults
hdf4                      4.2.13               h3ca952b_2    defaults
hdf5                      1.10.2                        2    intel
heapdict                  1.0.1                      py_0    defaults
html5lib                  1.0.1                    py37_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.6.1                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.23                     py37_0    defaults
intel-openmp              2019.5                intel_281    intel
intelpython               2019.5                        0    intel
ipykernel                 5.1.3            py37h39e3cac_0    defaults
ipython                   7.9.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.15.1                   py37_0    defaults
jeepney                   0.4.1                      py_0    defaults
jinja2                    2.10.3                     py_0    defaults
joblib                    0.14.0                     py_0    defaults
jpeg                      9b                   h024ee3a_2    defaults
json-c                    0.13.1               h1bed415_0    defaults
json5                     0.8.5                      py_0    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.6.1                    py37_0    defaults
jupyterlab                1.2.3              pyhf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    defaults
kealib                    1.4.7                h77bc034_6    defaults
keyring                   19.2.0                   py37_0    defaults
kiwisolver                1.1.0            py37he6710b0_0    defaults
krb5                      1.16.1               hc83ff2d_6    defaults
lazy-object-proxy         1.4.3            py37h7b6447c_0    defaults
libarchive                3.3.3                h7d0bbab_1    defaults
libboost                  1.67.0               h46d08c1_4    defaults
libcurl                   7.61.1               heec0ca6_0    defaults
libdap4                   3.19.1               h6ec2957_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                        11    intel
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgdal                   2.3.2                h9d4a965_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libkml                    1.3.0                h590aaf7_4    defaults
liblief                   0.9.0                h7725739_2    defaults
libnetcdf                 4.6.1                h10edf3e_2    defaults
libpng                    1.6.36                        2    intel
libpq                     10.5                 h1ad7b7a_0    defaults
libsodium                 1.0.16                        3    intel
libspatialite             4.3.0a              he475c7f_19    defaults
libssh2                   1.8.0                h9cfc8f7_4    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
libtiff                   4.0.9                he85c1e1_2    defaults
libtool                   2.4.6                h7b6447c_5    defaults
libuuid                   1.0.3                h1bed415_2    defaults
libxcb                    1.13                 h1bed415_1    defaults
libxml2                   2.9.9                hea5a465_1    defaults
libxslt                   1.1.33               h7d1a2b0_0    defaults
llvmlite                  0.30.0           py37hd408876_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.4.1            py37hefd8a0e_0    defaults
lz4-c                     1.8.1.2              h14c3975_0    defaults
lzo                       2.10                 h49e0be7_2    defaults
markupsafe                1.1.1            py37h7b6447c_0    defaults
matplotlib                3.0.3            py37h5429711_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h7b6447c_0    defaults
mkl                       2019.5                intel_281    intel
mkl-service               2.3.0            py37he904b0f_0    defaults
mkl_fft                   1.0.15           py37ha843d7b_0    defaults
mkl_random                1.1.0            py37hd6b4f25_0    defaults
more-itertools            7.2.0                    py37_0    defaults
mpc                       1.1.0                h10f8cd9_1    defaults
mpfr                      4.0.1                hdf1c602_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37hfd86e86_1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
networkx                  2.4                        py_0    defaults
nltk                      3.4.5                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.2                    py37_0    defaults
numba                     0.46.0           py37h962f231_0    defaults
numexpr                   2.7.0            py37h9e4a6bb_0    defaults
numpy                     1.17.4           py37hc1035e2_0    defaults
numpy-base                1.17.4           py37hde5b4d6_0    defaults
numpydoc                  0.9.1                      py_0    defaults
olefile                   0.46                     py37_0    defaults
openjpeg                  2.3.0                h05c96fa_1    defaults
openpyxl                  3.0.1                      py_0    defaults
openssl                   1.0.2s                        0    intel
packaging                 19.2                       py_0    defaults
pandas                    0.25.3           py37he6710b0_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
pango                     1.42.4               h049681c_0    defaults
parso                     0.5.1                      py_0    defaults
partd                     1.1.0                      py_0    defaults
patchelf                  0.10                 he6710b0_0    defaults
path.py                   12.0.2                     py_0    defaults
pathlib2                  2.3.5                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pcre                      8.43                 he6710b0_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.7.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    5.4.1            py37h34e0f95_0    defaults
pip                       19.3.1                   py37_0    defaults
pixman                    0.38.0               h7b6447c_0    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.13.1                   py37_0    defaults
ply                       3.11                     py37_0    defaults
poppler                   0.65.0               h581218d_1    defaults
poppler-data              0.4.9                         0    defaults
proj4                     5.0.1                h14c3975_0    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
psutil                    5.6.5            py37h7b6447c_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37h7725739_2    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h14c3975_9    defaults
pycurl                    7.43.0.2         py37hb7f436b_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.4.2                      py_0    defaults
pylint                    2.4.4                    py37_0    defaults
pyodbc                    4.0.27           py37he6710b0_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.4.5                      py_0    defaults
pyproj                    1.9.5.1          py37h7b21b82_1    defaults
pyqt                      5.9.2            py37h05f1152_2    defaults
pyrsistent                0.15.6           py37h7b6447c_0    defaults
pyshp                     2.1.0                      py_0    defaults
pysocks                   1.7.1                    py37_0    defaults
pytables                  3.4.4            py37ha205bf6_0    defaults
pytest                    5.3.0                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.6.0                      py_0    defaults
pytest-astropy-header     0.1.1                      py_0    defaults
pytest-doctestplus        0.5.0                      py_0    defaults
pytest-openfiles          0.4.0                      py_0    defaults
pytest-remotedata         0.3.2                    py37_0    defaults
python                    3.7.0                h6e4f718_3    defaults
python-dateutil           2.8.1                      py_0    defaults
python-libarchive-c       2.8                     py37_13    defaults
pytz                      2019.3                     py_0    defaults
pywavelets                1.1.1            py37h7b6447c_0    defaults
pyyaml                    5.1.2            py37h7b6447c_0    defaults
pyzmq                     18.1.0           py37he6710b0_0    defaults
qt                        5.9.6                h8703b6f_2    defaults
qtawesome                 0.6.0                      py_0    defaults
qtconsole                 4.6.0                      py_0    defaults
qtpy                      1.9.0                      py_0    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_0    defaults
ripgrep                   0.10.0               hc07d326_0    defaults
rope                      0.14.0                     py_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
scikit-image              0.15.0           py37he6710b0_0    defaults
scikit-learn              0.21.3           py37hd81dba3_0    defaults
scipy                     1.3.1            py37h7c811a0_0    defaults
seaborn                   0.9.0              pyh91ea838_1    defaults
secretstorage             3.1.1                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                42.0.1                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37hf484d3e_0    defaults
six                       1.13.0                   py37_0    defaults
snappy                    1.1.7                hbae5bb6_3    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.9.5                    py37_0    defaults
sphinx                    2.2.1                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.2                    py37_0    defaults
sqlalchemy                1.3.11           py37h7b6447c_0    defaults
sqlite                    3.28.0                        0    intel
statsmodels               0.10.1           py37hdd07704_0    defaults
sympy                     1.4                      py37_0    defaults
tables                    3.5.2                    pypi_0    pypi
tbb                       2019.8                intel_281    intel
tblib                     1.5.0                      py_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.8                hbc83047_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.3            py37h7b6447c_0    defaults
tqdm                      4.39.0                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h14c3975_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.16.0                     py_0    defaults
wheel                     0.33.6                   py37_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
wrapt                     1.11.2           py37h7b6447c_0    defaults
wurlitzer                 2.0.0                    py37_0    defaults
xerces-c                  3.2.2                h780794e_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.2.6                      py_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                         5    intel
yaml                      0.1.7                         2    intel
zeromq                    4.3.1                he6710b0_3    defaults
zict                      1.0.0                      py_0    defaults
zipp                      0.6.0                      py_0    defaults
zlib                      1.2.11                        5    intel
zstd                      1.3.3                h84994c4_0    defaults
```
</p></details>

**Comment by parrenin** [comment]
I solved my problem by replacing the packages from the intel channel by the packages from the defaults channel.
Sorry to have bothered you.

**Comment by msarahan** [comment]
Yes, that's a c++ ABI incompatibility. Intel builds their software differently from defaults. Mixing channels is unfortunately pretty spotty much of the time.
