### ISSUE TITLE
conda 4.7.12 ProxyError - proxy server settings that work with conda 4.3 fail with conda 4.7.12

### ISSUE THREAD

**Issue by johngergely** [conda/conda#9497]
## Current Behavior

I am using conda behind a firewall. The repositories have been whitelisted and proxy server access is authorized for my desktop. I have used this configuration successfully for a long time with conda 4.3. In helping a new colleague configure his Anaconda installation with conda v 4.7.12, I have come to find out that the same proxy server settings fail with the new version.

### Steps to Reproduce

using conda 4.7.12
```
(base) PS C:\> conda update conda --verbose
Collecting package metadata (current_repodata.json): ...working... Retrying (Ret
ry(total=2, connect=None, read=None, redirect=None, status=None)) after connecti
on broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection
failed: 403 Forbidden'))': /pkgs/r/noarch/current_repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) a
fter connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunne
l connection failed: 403 Forbidden'))': /pkgs/msys2/win-64/current_repodata.json


Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) a
fter connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunne
l connection failed: 403 Forbidden'))': /pkgs/main/noarch/current_repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) a
fter connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunne
l connection failed: 403 Forbidden'))': /pkgs/r/win-64/current_repodata.json

Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) a
fter connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunne
l connection failed: 403 Forbidden'))': /pkgs/main/win-64/current_repodata.json


Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) a
fter connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunne
l connection failed: 403 Forbidden'))': /pkgs/msys2/noarch/current_repodata.json

Traceback (most recent call last):
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connectionpool
.py", line 594, in urlopen
    self._prepare_proxy(conn)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connectionpool
.py", line 805, in _prepare_proxy
    conn.connect()
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connection.py"
, line 308, in connect
    self._tunnel()
  File "C:\Users\gerg\Anaconda_test\lib\http\client.py", line 921, in _tunne
l
    message.strip()))
OSError: Tunnel connection failed: 403 Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\requests\adapters.py",
 line 449, in send
    timeout=timeout
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connectionpool
.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connectionpool
.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connectionpool
.py", line 667, in urlopen
    **response_kw)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\connectionpool
.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\urllib3\util\retry.py"
, line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='repo.anaconda.com',
port=443): Max retries exceeded with url: /pkgs/main/win-64/current_repodata.jso
n (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection f
ailed: 403 Forbidden')))
Traceback (most recent call last):
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\exceptions.py",
line 1074, in __call__
    return func(*args, **kwargs)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\cli\main.py", li
ne 84, in _main
    exit_code = do_call(args, p)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\cli\conda_argpar
se.py", line 82, in do_call
    exit_code = getattr(module, func_name)(args, parser)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\cli\main_update.
py", line 20, in execute
    install(args, parser, 'update')
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\cli\install.py",
 line 265, in install
    should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1
]),
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\solve.py",
line 117, in solve_for_transaction
    should_retry_solve)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\solve.py",
line 158, in solve_for_diff
    force_remove, should_retry_solve)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\solve.py",
line 262, in solve_final_state
    ssc = self._collect_all_metadata(ssc)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\common\io.py", l
ine 88, in decorated
    return f(*args, **kwds)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\solve.py",
line 415, in _collect_all_metadata
    index, r = self._prepare(prepared_specs)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\solve.py",
line 1004, in _prepare
    self.subdirs, prepared_specs, self._repodata_fn)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\index.py",
line 214, in get_reduced_index
    repodata_fn=repodata_fn)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\subdir_data
.py", line 97, in query_all
    result = tuple(concat(executor.map(subdir_query, channel_urls)))
  File "C:\Users\gerg\Anaconda_test\lib\concurrent\futures\_base.py", line 5
98, in result_iterator
    yield fs.pop().result()
  File "C:\Users\gerg\Anaconda_test\lib\concurrent\futures\_base.py", line 4
35, in result
    return self.__get_result()
  File "C:\Users\gerg\Anaconda_test\lib\concurrent\futures\_base.py", line 3
84, in __get_result
    raise self._exception
  File "C:\Users\gerg\Anaconda_test\lib\concurrent\futures\thread.py", line
57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\subdir_data
.py", line 90, in <lambda>
    package_ref_or_match_spec))
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\subdir_data
.py", line 102, in query
    self.load()
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\subdir_data
.py", line 166, in load
    _internal_state = self._load()
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\subdir_data
.py", line 240, in _load
    repodata_fn=self.repodata_fn)
  File "C:\Users\gerg\Anaconda_test\lib\site-packages\conda\core\subdir_data
.py", line 483, in fetch_repodata_remote_request
    raise ProxyError()   # see #3962
conda.exceptions.ProxyError: Conda cannot proceed due to an error in your proxy
configuration.
Check for typos and other configuration errors in any '.netrc' file in your home
 directory,
any environment variables ending in '_PROXY', and any other system-wide proxy
configuration settings.
```

## Expected Behavior

```
C:\Anaconda3>conda update conda --verbose
Fetching package metadata .............
Solving package specifications: .

# All requested packages already installed.
# packages in environment at C:\Anaconda3:
#
conda                     4.3.30           py34h3ba59da_0
```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
(base) PS C:\> conda info

     active environment : base
    active env location : C:\Users\gerg\Anaconda_test
            shell level : 1
       user config file : C:\Users\gerg\.condarc
 populated config files : C:\Users\gerg\.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages :
       base environment : C:\Users\gerg\Anaconda_test  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\gerg\Anaconda_test\pkgs
                          C:\Users\gerg\.conda\pkgs
                          C:\Users\gerg\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\gerg\Anaconda_test\envs
                          C:\Users\gerg\.conda\envs
                          C:\Users\gerg\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Windows/7 W
indows/6.1.7601
          administrator : False
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\gerg\.condarc <==
ssl_verify: True
channels:
  - defaults

proxy server settings are set as Windows environment variables
(base) PS C:\> Get-ChildItem env:

Name                           Value
----                           -----
_CONDA_EXE                     C:/Users/gerg/Anaconda_test\Scripts\conda...
_CONDA_ROOT                    C:/Users/gerg/Anaconda_test
CONDA_DEFAULT_ENV              base
CONDA_EXE                      C:\Users\gerg\Anaconda_test\Scripts\conda...
CONDA_PREFIX                   C:\Users\gerg\Anaconda_test
CONDA_PROMPT_MODIFIER          (base)
CONDA_PYTHON_EXE               C:\Users\gerg\Anaconda_test\python.exe
CONDA_SHLVL                    1
http_proxy                     http://10.XXX.XX.XXX:3128
https_proxy                    https://10.XX.XX.XXx:3128

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
(base) PS C:\> conda list --show-channel-urls
# packages in environment at C:\Users\gerg\Anaconda_test:
#
# Name                    Version                   Build  Channel
asn1crypto                1.2.0                    py37_0    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.13.0           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
conda                     4.7.12                   py37_0    defaults
conda-package-handling    1.6.0            py37h62dcd97_0    defaults
console_shortcut          0.1.1                         3    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
idna                      2.8                      py37_0    defaults
menuinst                  1.4.16           py37he774522_0    defaults
openssl                   1.1.1d               he774522_3    defaults
pip                       19.3.1                   py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
pycosat                   0.6.3            py37hfa6e2cd_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.4                h5263a28_0    defaults
pywin32                   223              py37hfa6e2cd_1    defaults
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37hfa6e2cd_0    defaults
setuptools                41.4.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.30.0               he774522_0    defaults
tqdm                      4.36.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_0    defaults
wheel                     0.33.6                   py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
wincertstore              0.2                      py37_0    defaults
yaml                      0.1.7                hc54c509_2    defaults

```
</p></details>

**Comment by codebraker** [comment]
Any updates to this issue? I have been using conda updates so far using same .condarc file behind work proxy. It used to work fine so far. Now I am not able to update/install using conda/pip either.

I have configured HTTP(s)_Proxy in system variables and also configured the settings in .condarc file for anaconda.

**Comment by ProntyGoanna** [comment]
Any updates to this issue? I have a similar problem. By the way, Anaconda's / python proxy handling sucks!

**Comment by TerrySnow1963** [comment]
Any updates on this issue. Same issues have happened to me. The proxy settings in .condarc were fine, now getting same error as original post.

**Comment by raduromaniuc** [comment]
Having the same issue. Proxy was working fine and then it just started failing. Also tried the following, but with no success:

https://github.com/ContinuumIO/anaconda-issues/issues/553

**Comment by Pfesi** [comment]
Hi, I was getting the same issues and then when i reset my proxy it worked well after that. Might be worth a try if you are still experiencing issues.

**Comment by vukien95** [comment]
I am getting same issue, anyone has update ?

**Comment by Det7** [comment]
same issues and I can't figure out how to make it work. any updates on this?

**Comment by alienzj** [comment]
same issues and I can't figure out how to make it work. any updates on this?

**Comment by trenogind** [comment]
Had the same issue, with proxy in .condarc file. The solution was to replace backslash `\` (if you have any, which I had) in proxy url with its code `%5C` using url encoding (percent encoding). I suppose, some other symbols also need to be encoded the same way.

**Comment by SalahBelila** [comment]
changing proxy_servers to {} in .condarc solved the problem.
proxy_servers: {}

**Comment by SjnPutina** [comment]
> Had the same issue, with proxy in .condarc file. The solution was to replace backslash `\` (if you have any, which I had) in proxy url with its code `%5C` using url encoding (percent encoding). I suppose, some other symbols also need to be encoded the same way.
It helped for me

**Comment by sexroute** [comment]
Had the same issue, with proxy in .condarc file. The solution was to add ssl_verify: False. The modified setting is as the following.
proxy_servers:
    http: http://user:pass@corp.com:8080
    https: http://user:pass@corp.com:8080
ssl_verify: False

**Comment by EBenkler** [comment]
In my case, none of the above suggestions help. 

I think there are only two options to recover your Anaconda / Miniconda installation:

First option is a  complete reinstallation of Anaconda / Miniconda.
Second option is to temporarily disable internet access in .condarc and revert to previous version. Here is a step-by-step guide for the second option:

1. Locate your .condarc file and add / change `offline: True` line in order to avoid that conda tries to access the internet, which would fail due to the above discussed proxy bug.
2. In a conda prompt, base environment, list the previous revisions with `conda list --revisions`
3. Note the revision number of the second last revision, which should be the revision you had before you issued `conda update conda`
4. `conda install --revision <rev-number>`, e.g. if <revision number> is 14, `conda install --revision 14`
5. Reset your .condarc to the state before step 1 (e.g. by commenting or deleting the offline:True line)

You should now have reverted to the state before you issued `conda update conda`

I am rather sure that this is a conda bug, and is not related to the proxy settings, because everything works before issuing `conda update conda`. Does anybody have an idea how this bug could be fixed in conda source code? Where should I start to look in the conda source code?

**Comment by EBenkler** [comment]
I narrowed this down a bit further.

The problem results from updating urllib3 to a version >= 1.26.0

An excerpt from the urllib3 changelog (taken from [here](https://pypi.org/project/urllib3/), PR numbers are those for urllib3 repo, not conda/conda repo):

### 1.26.0 (2020-11-10)

-    NOTE: urllib3 v2.0 will drop support for Python 2. Read more in the v2.0 Roadmap.
-    Added support for HTTPS proxies contacting HTTPS servers (Pull #1923, Pull #1806)
-    Deprecated negotiating TLSv1 and TLSv1.1 by default. Users that still wish to use TLS earlier than 1.2 without a deprecation warning should opt-in explicitly by setting ssl_version=ssl.PROTOCOL_TLSv1_1 (Pull #2002) Starting in urllib3 v2.0: Connections that receive a ``DeprecationWarning`` will fail
-    Deprecated Retry options Retry.DEFAULT_METHOD_WHITELIST, Retry.DEFAULT_REDIRECT_HEADERS_BLACKLIST and Retry(method_whitelist=...) in favor of Retry.DEFAULT_ALLOWED_METHODS, Retry.DEFAULT_REMOVE_HEADERS_ON_REDIRECT, and Retry(allowed_methods=...) (Pull #2000) Starting in urllib3 v2.0: Deprecated options will be removed
-    Added default User-Agent header to every request (Pull #1750)
-    Added urllib3.util.SKIP_HEADER for skipping User-Agent, Accept-Encoding, and Host headers from being automatically emitted with requests (Pull #2018)
-    Collapse transfer-encoding: chunked request data and framing into the same socket.send() call (Pull #1906)
-    Send http/1.1 ALPN identifier with every TLS handshake by default (Pull #1894)
-    Properly terminate SecureTransport connections when CA verification fails (Pull #1977)
-    Don’t emit an SNIMissingWarning when passing server_hostname=None to SecureTransport (Pull #1903)
-    Disabled requesting TLSv1.2 session tickets as they weren’t being used by urllib3 (Pull #1970)
-    Suppress BrokenPipeError when writing request body after the server has closed the socket (Pull #1524)
-    Wrap ssl.SSLError that can be raised from reading a socket (e.g. “bad MAC”) into an urllib3.exceptions.SSLError (Pull #1939)

Hence, I searched the urllib3 issue tracker and found [this](https://github.com/urllib3/urllib3/issues/2101) and [this](https://github.com/pypa/pip/issues/9216) issue, which both seem to be related to our issue here. 

However, I am unsure how to proceed. Do we have to change something in the conda code, or should I open an issue in the urllib3 repo?

**Comment by samuelchodur** [comment]
> As already reported in [the comment from 22nd January 2021](https://github.com/conda/conda/issues/9497#issuecomment-765213481), two settings must be made in your .condarc file:
> 
>     1. for the https proxy, use `https: http://...`  (NOT `https: https://...`)
> 
>     2. `ssl_verify: False`
> 
> 
> This seems to be the intended behaviour expected by urllib3, see the discussion [here](https://github.com/pypa/pip/issues/9216)
> Hence, there is no need to change anything in the conda code or to report to urllib3. Sorry for the confusion, I had overloooked to use http instead of https prefix.

This fixed my issue. Thanks for making it clear, although this information is tough to find right now.

**Comment by JiceJames** [comment]
I've just installed Anaconda (conda 4.10.1) and i'm experiencing this same issue.
my env variables were not mentionned in the .condarc so I've tried to update my .condarc as mentionned (ssl_verify: false, http and https proxies with and without user:pwd@ - and http:// for https proxy) but nothing to do, i still have the error :

`Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required'))': /pkgs/main/win-64/current_repodata.json`

My settings usually works so i don't understand what's happening.

**Comment by agmeyer4** [comment]
> As already reported in [the comment from 22nd January 2021](https://github.com/conda/conda/issues/9497#issuecomment-765213481), two settings must be made in your .condarc file:
> 
>     1. for the https proxy, use `https: http://...`  (NOT `https: https://...`)
> 
>     2. `ssl_verify: False`
> 
> 
> This seems to be the intended behaviour expected by urllib3, see the discussion [here](https://github.com/pypa/pip/issues/9216)
> Hence, there is no need to change anything in the conda code or to report to urllib3. Sorry for the confusion, I had overloooked to use http instead of https prefix.

This also fixed my issue after hours of banging my head. Thanks!

**Comment by QsingHuan** [comment]
> ssl_verify: False

very useful, thx

**Comment by QsingHuan** [comment]
> As already reported in [the comment from 22nd January 2021](https://github.com/conda/conda/issues/9497#issuecomment-765213481), two settings must be made in your .condarc file:
> 
> 1. for the https proxy, use `https: http://...`  (NOT `https: https://...`)
> 2. `ssl_verify: False`
> 
> This seems to be the intended behaviour expected by urllib3, see the discussion [here](https://github.com/pypa/pip/issues/9216) Hence, there is no need to change anything in the conda code or to report to urllib3. Sorry for the confusion, I had overloooked to use http instead of https prefix.

very useful, thx!

**Comment by Bangash514** [comment]
The reason is that Conda cannot continue due to proxy configuration errors.

The solutions are as follows:
Open "Internet Options" in the Internet -> Connection -> LAN Settings -> uncheck the "Use a proxy server for Lan".

**Comment by thulasis** [comment]
I got the similar issue with conda. I did the following to solve the issue after researching the possible solutions for hours. I am using linux and miniconda (Conda 4.11.0)
1. Open command prompt/terminal
`env | grep -i "_PROXY"`

Output:
https_proxy=http://proxy.xxx.xxx:0000
http_proxy=http://proxy.xxx.xxx:0000

copy the output

2. edit the .condarc file by 
`nano ~/.condarc`

3. at the end of condarc file add the following lines in yaml format
`proxy_servers:
   http: http://proxy.smwed.edu:3128/
   https: http://proxy.swmed.edu:3128/`

Note: Give only three spaces - not tab in the new line i.e. before http: & https:

4. If still not working - add 'ssl_verify: False' to the .condarc file

Hope it helps.

Thanks

**Comment by Bangash514** [comment]
Sent from Mail for Windows From: Tulasi_RaoSent: 10 May 2022 04:22To: conda/condaCc: Bangash; CommentSubject: Re: [conda/conda] conda 4.7.12 ProxyError - proxy server settings that work with conda 4.3 fail with conda 4.7.12 (#9497) I got the similar issue with conda. I did the following to solve the issue after researching the possible solutions for hours. I am using linux and miniconda (Conda 4.11.0)Open command prompt/terminalenv | grep -i "_PROXY"Output:https_proxy=http://proxy.xxx.xxx:0000http_proxy=http://proxy.xxx.xxx:0000copy the outputedit the .condarc file bynano ~/.condarcat the end of condarc file add the following lines in yaml formatproxy_servers: http: http://proxy.smwed.edu:3128/ https: http://proxy.swmed.edu:3128/Note: Give only three spaces - not tab in the new line i.e. before http: & https:If still not working - add 'ssl_verify: False' to the .condarc fileHope it helps.Thanks—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by SteveScott** [comment]
I have conda v4.12 running on a computer successfully. I copy and paste the .condarc file in the new machine and install conda v4.13. Same exact file. Not working

**Comment by Zhaopudark** [comment]
> As already reported in [the comment from 22nd January 2021](https://github.com/conda/conda/issues/9497#issuecomment-765213481), two settings must be made in your .condarc file:
> 
> 1. for the https proxy, use `https: http://...`  (NOT `https: https://...`)
> 2. `ssl_verify: False`
> 
> This seems to be the intended behaviour expected by urllib3, see the discussion [here](https://github.com/pypa/pip/issues/9216) Hence, there is no need to change anything in the conda code or to report to urllib3. Sorry for the confusion, I had overloooked to use http instead of https prefix.

Thanks. It works when I follow the key point "https proxy, use `https: http://...`  (NOT `https: https://...`)". 

But, this is very interesting. Because in [conda doc](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/use-condarc.html?highlight=proxy#configure-conda-for-use-behind-a-proxy-server-proxy-servers), there are examples with`https: https://...`  instead of `https: http://...` and the sentence  `Be careful not to use http when you mean https or https when you mean http.`  is even  emphasized.😊

**Comment by SimonKurz** [comment]
Took me a couple of hours of debugging to find the solution here. I guess the conda doc should be fixed.

**Comment by Dengda98** [comment]
> As already reported in [the comment from 22nd January 2021](https://github.com/conda/conda/issues/9497#issuecomment-765213481), two settings must be made in your .condarc file:
> 
> 1. for the https proxy, use `https: http://...`  (NOT `https: https://...`)
> 2. `ssl_verify: False`
> 
> This seems to be the intended behaviour expected by urllib3, see the discussion [here](https://github.com/pypa/pip/issues/9216) Hence, there is no need to change anything in the conda code or to report to urllib3. Sorry for the confusion, I had overloooked to use http instead of https prefix.

Saved my life......... Millions of Thanks

**Comment by Gerry-j** [comment]
我把代理服务器关掉就好了
