### ISSUE TITLE
conda broken after python update

### ISSUE THREAD

**Issue by nopria** [conda/conda#9520]
Yesterday I updated python with the command

    conda update python

and noticed python upgraded from 3.6 to 3.7
After such update conda is broken and almost any commad I try, such as

    conda update conda
    conda update --all
    conda install --revision 83
    conda install python=3.6

gives errors.

Here is the error I get with `conda update conda`:

    Collecting package metadata (current_repodata.json): failed

    # >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

        Traceback (most recent call last):
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 654, in urlopen
            conn = self._get_conn(timeout=pool_timeout)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 274, in _get_conn
            return conn or self._new_conn()
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _new_conn
            "Can't connect to HTTPS URL because the SSL module is not available."
        urllib3.exceptions.SSLError: Can't connect to HTTPS URL because the SSL module is not available.

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\requests\adapters.py", line 449, in send
            timeout=timeout
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
            **response_kw
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
            **response_kw
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
            **response_kw
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
            method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 436, in increment
            raise MaxRetryError(_pool, url, error or ResponseError(cause))
        urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 485, in fetch_repodata_remote_request
            timeout=timeout)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\requests\sessions.py", line 546, in get
            return self.request('GET', url, **kwargs)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
            resp = self.send(prep, **send_kwargs)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
            r = adapter.send(request, **kwargs)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\requests\adapters.py", line 514, in send
            raise SSLError(e, request=request)
        requests.exceptions.SSLError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available."))

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\exceptions.py", line 1078, in __call__
            return func(*args, **kwargs)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
            exit_code = do_call(args, p)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
            exit_code = getattr(module, func_name)(args, parser)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\cli\main_update.py", line 20, in execute
            install(args, parser, 'update')
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\cli\install.py", line 265, in install
            should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
            should_retry_solve)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
            force_remove, should_retry_solve)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
            ssc = self._collect_all_metadata(ssc)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
            return f(*args, **kwds)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
            index, r = self._prepare(prepared_specs)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\solve.py", line 1004, in _prepare
            self.subdirs, prepared_specs, self._repodata_fn)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\index.py", line 229, in get_reduced_index
            repodata_fn=repodata_fn)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
            result = tuple(concat(executor.map(subdir_query, channel_urls)))
          File "C:\Users\NUC-W10\Miniconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
            yield fs.pop().result()
          File "C:\Users\NUC-W10\Miniconda3\lib\concurrent\futures\_base.py", line 432, in result
            return self.__get_result()
          File "C:\Users\NUC-W10\Miniconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
            raise self._exception
          File "C:\Users\NUC-W10\Miniconda3\lib\concurrent\futures\thread.py", line 57, in run
            result = self.fn(*self.args, **self.kwargs)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
            package_ref_or_match_spec))
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
            self.load()
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
            _internal_state = self._load()
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
            repodata_fn=self.repodata_fn)
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 587, in fetch_repodata_remote_request
            """) % maybe_unquote(repr(e))
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\common\url.py", line 368, in maybe_unquote
            return unquote_plus(remove_auth(url)) if url else url
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\common\url.py", line 372, in remove_auth
            url_parts = parse_url(url)._asdict()
          File "C:\Users\NUC-W10\Miniconda3\lib\site-packages\conda\_vendor\urllib3\util\url.py", line 196, in parse_url
            raise LocationParseError(url)
        conda._vendor.urllib3.exceptions.LocationParseError: Failed to parse: SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.anaconda.org\', port=443): Max retries exceeded with url:

    `$ C:\Users\NUC-W10\Miniconda3\Scripts\conda-script.py update conda`

      environment variables:
                     CIO_TEST=<not set>
                   CONDA_ROOT=C:\Users\NUC-W10\Miniconda3
                     HOMEPATH=\Users\NUC-W10
                         PATH=C:\Program Files\Haskell\bin;C:\Program Files\Haskell
                              Platform\8.4.3\lib\extralibs\bin;C:\Program Files\Haskell
                              Platform\8.4.3\bin;C:\Program Files (x86)\Common
                              Files\Oracle\Java\javapath;C:\Program Files\ImageMagick-7.0.7-Q16;C:\P
                              rogramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporat
                              ion\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wb
                              em;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files
                              (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common
                              Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common
                              Files\Acronis\SnapAPI\;C:\Program Files\Crucial\Crucial Storage
                              Executive;C:\Program Files (x86)\AOMEI Backupper;C:\WINDOWS\System32\O
                              penSSH\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\
                              perl\bin;C:\Program Files\Haskell Platform\8.4.3\mingw\bin;C:\Program
                              Files (x86)\Smart Projects\IsoBuster;C:\Program
                              Files\Intel\WiFi\bin\;C:\Program Files\Common
                              Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program
                              Files\Calibre2\;C:\Program Files\Liquid Technologies\Liquid Studio
                              2019\XmlDataBinder17\Redist17\cpp\win32\bin;C:\Program Files\Liquid
                              Technologies\Liquid Studio 2019\XmlDataBinder17\Redist17\cpp\win64\bin
                              ;C:\Ruby26-x64\bin;C:\Users\NUC-W10\AppData\Roaming\cabal\bin;C:\Users
                              \NUC-W10\AppData\Roaming\local\bin;C:\Users\NUC-W10\AppData\Local\Prog
                              rams\MiKTeX 2.9\miktex\bin\x64\;C:\Users\NUC-W10\AppData\Local\Pandoc\
                              ;C:\Users\NUC-W10\Miniconda3;C:\Users\NUC-W10\Miniconda3\Scripts;C:\Pr
                              ogram Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\Wirele
                              ssCommon\;C:\Users\NUC-W10\AppData\Local\atom\bin;C:\Users\NUC-W10\Min
                              iconda3\lib\site-packages\pywin32_system32
                 PSMODULEPATH=C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\Windows
                              PowerShell\v1.0\Modules;C:\Program Files\Intel\;C:\Program
                              Files\Intel\Wired Networking\
           REQUESTS_CA_BUNDLE=<not set>
                SSL_CERT_FILE=<not set>
        VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

         active environment : None
           user config file : C:\Users\NUC-W10\.condarc
     populated config files : C:\Users\NUC-W10\.condarc
              conda version : 4.8.0
        conda-build version : not installed
             python version : 3.7.3.final.0
           virtual packages :
           base environment : C:\Users\NUC-W10\Miniconda3  (writable)
               channel URLs : https://conda.anaconda.org/conda-forge/win-64
                              https://conda.anaconda.org/conda-forge/noarch
                              https://conda.anaconda.org/anaconda/win-64
                              https://conda.anaconda.org/anaconda/noarch
                              https://repo.anaconda.com/pkgs/main/win-64
                              https://repo.anaconda.com/pkgs/main/noarch
                              https://repo.anaconda.com/pkgs/r/win-64
                              https://repo.anaconda.com/pkgs/r/noarch
                              https://repo.anaconda.com/pkgs/msys2/win-64
                              https://repo.anaconda.com/pkgs/msys2/noarch
              package cache : C:\Users\NUC-W10\Miniconda3\pkgs
                              C:\Users\NUC-W10\.conda\pkgs
                              C:\Users\NUC-W10\AppData\Local\conda\conda\pkgs
           envs directories : C:\Users\NUC-W10\Miniconda3\envs
                              C:\Users\NUC-W10\.conda\envs
                              C:\Users\NUC-W10\AppData\Local\conda\conda\envs
                   platform : win-64
                 user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
              administrator : False
                 netrc file : None
               offline mode : False

    An unexpected error has occurred. Conda has prepared the above report.

    Upload did not complete.

Thanks in advance for any clue.

**Comment by Acribbs** [comment]
Not sure if `conda update urllib3` will help?

Iv had this issue before and my fix was to reinstall because It ended up being the quickest. Before doing so I exported all of my most important environments and reinstalled them (see https://stackoverflow.com/questions/41274007/anaconda-export-environment-file)

**Comment by nopria** [comment]
I ended up reainstalling all from stratch.
