### ISSUE TITLE
Can't create new environments or install/update packages

### ISSUE THREAD

**Issue by jralfonsog** [conda/conda#9546]
Hello there.

Whenever I try to create a new env or install/update packages, I get the following error report:

`Collecting package metadata (current_repodata.json): failed

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\urllib3\connection.py", line 157, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "D:\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 84, in create_connection
        raise err
      File "D:\Miniconda3\lib\site-packages\urllib3\util\connection.py", line 74, in create_connection
        sock.connect(sa)
    socket.timeout: timed out

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 662, in urlopen
        self._prepare_proxy(conn)
      File "D:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 948, in _prepare_proxy
        conn.connect()
      File "D:\Miniconda3\lib\site-packages\urllib3\connection.py", line 334, in connect
        conn = self._new_conn()
      File "D:\Miniconda3\lib\site-packages\urllib3\connection.py", line 164, in _new_conn
        % (self.host, self.timeout),
    urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F867DAE2E8>, 'Connection to 172.31.219.30 timed out. (connect timeout=9.15)')

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\requests\adapters.py", line 449, in send
        timeout=timeout
      File "D:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
        **response_kw
      File "D:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
        **response_kw
      File "D:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 760, in urlopen
        **response_kw
      File "D:\Miniconda3\lib\site-packages\urllib3\connectionpool.py", line 720, in urlopen
        method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
      File "D:\Miniconda3\lib\site-packages\urllib3\util\retry.py", line 436, in increment
        raise MaxRetryError(_pool, url, error or ResponseError(cause))
    urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F867DAE2E8>, 'Connection to 172.31.219.30 timed out. (connect timeout=9.15)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "D:\Miniconda3\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "D:\Miniconda3\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "D:\Miniconda3\lib\site-packages\requests\sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "D:\Miniconda3\lib\site-packages\requests\adapters.py", line 504, in send
        raise ConnectTimeout(e, request=request)
    requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /conda-forge/win-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001F867DAE2E8>, 'Connection to 172.31.219.30 timed out. (connect timeout=9.15)'))

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "D:\Miniconda3\lib\site-packages\conda\exceptions.py", line 1078, in __call__
        return func(*args, **kwargs)
      File "D:\Miniconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\Miniconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "D:\Miniconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "D:\Miniconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "D:\Miniconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "D:\Miniconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "D:\Miniconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\Miniconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "D:\Miniconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\Miniconda3\lib\site-packages\conda\core\solve.py", line 1004, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "D:\Miniconda3\lib\site-packages\conda\core\index.py", line 229, in get_reduced_index
        repodata_fn=repodata_fn)
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\Miniconda3\lib\concurrent\futures\_base.py", line 586, in result_iterator
        yield fs.pop().result()
      File "D:\Miniconda3\lib\concurrent\futures\_base.py", line 432, in result
        return self.__get_result()
      File "D:\Miniconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "D:\Miniconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
        self.load()
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "D:\Miniconda3\lib\site-packages\conda\core\subdir_data.py", line 587, in fetch_repodata_remote_request
        """) % maybe_unquote(repr(e))
      File "D:\Miniconda3\lib\site-packages\conda\common\url.py", line 368, in maybe_unquote
        return unquote_plus(remove_auth(url)) if url else url
      File "D:\Miniconda3\lib\site-packages\conda\common\url.py", line 372, in remove_auth
        url_parts = parse_url(url)._asdict()
      File "D:\Miniconda3\lib\site-packages\conda\_vendor\urllib3\util\url.py", line 196, in parse_url
        raise LocationParseError(url)
    conda._vendor.urllib3.exceptions.LocationParseError: Failed to parse: ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url:

`$ D:\Miniconda3\Scripts\conda-script.py install anaconda-clean`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=D:\Miniconda3\Scripts\conda.exe
             CONDA_PREFIX=D:\Miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=D:\Miniconda3\python.exe
               CONDA_ROOT=D:\Miniconda3
              CONDA_SHLVL=1
                 HOMEPATH=\Users\jralfonso
              JUNORC_PATH=D:\Julia\JuliaPro-1.2.0-1\.atom
                     PATH=D:\Miniconda3;D:\Miniconda3\Library\mingw-w64\bin;D:\Miniconda3\Librar
                          y\usr\bin;D:\Miniconda3\Library\bin;D:\Miniconda3\Scripts;D:\Miniconda
                          3\bin;D:\Miniconda3;D:\Miniconda3\Library\mingw-w64\bin;D:\Miniconda3\
                          Library\usr\bin;D:\Miniconda3\Library\bin;D:\Miniconda3\Scripts;D:\Min
                          iconda3\bin;D:\Miniconda3\condabin;C:\Program Files (x86)\Common
                          Files\Oracle\Java\javapath;C:\Python\Python--
                          3-7-5\Scripts;C:\Python\Python--3-7-5;C:\ProgramData\Oracle\Java\javap
                          ath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS
                          \System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Progra
                          m Files\Microsoft VS
                          Code\bin;C:\hadoop\bin;C:\spark\bin;C:\hadoop\bin;C:\Program Files\Git
                          \cmd;C:\Users\jralfonso\AppData\Local\Microsoft\WindowsApps;D:\Minicon
                          da3\lib\site-packages\pywin32_system32
             PSMODULEPATH=D:\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerSh
                          ell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : D:\Miniconda3
            shell level : 1
       user config file : C:\Users\jralfonso\.condarc
 populated config files : C:\Users\jralfonso\.condarc
          conda version : 4.8.0
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : D:\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Miniconda3\pkgs
                          C:\Users\jralfonso\.conda\pkgs
                          C:\Users\jralfonso\AppData\Local\conda\conda\pkgs
       envs directories : D:\Miniconda3\envs
                          C:\Users\jralfonso\.conda\envs
                          C:\Users\jralfonso\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.0 requests/2.22.0 CPython/3.7.3 Windows/10 Windows/10.0.18362
          administrator : True
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?`

I have even tried to install anaconda-clean to perform a clean reinstallation, but when I try to install it I get the same error. I wouldn't be able to sugest a probably source for the problem, as it just "started to happen", as far as I can see.

Please, let me know if there is any other info you need.

Thanks for your time.

**Comment by jralfonsog** [comment]
I had my .condarc setup to work behind a proxy, and I wasn't behind it at the moment...

I'll close this issue inmediately. Thanks por your time.
