### ISSUE TITLE
conda update, create, and install broken after upgrade to catalina (JSON decoding error)

### ISSUE THREAD

**Issue by smgroves** [conda/conda#9568]
### Steps to Reproduce

```
(base) Sarahs-MBP-2:~ sarahmaddox$ conda install velocyto
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1043, in __call__
        return func(*args, **kwargs)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 280, in install
        force_reinstall=context.force_reinstall or context.force,
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 112, in solve_for_transaction
        force_remove, force_reinstall)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 150, in solve_for_diff
        force_remove)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 240, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 300, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/solve.py", line 878, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 203, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 90, in query_all
        return tuple(concat(future.result() for future in as_completed(futures)))
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 94, in query
        self.load()
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 158, in load
        _internal_state = self._load()
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 260, in _load
        _internal_state = self._process_raw_repodata_str(raw_repodata_str)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 333, in _process_raw_repodata_str
        json_obj = json.loads(raw_repodata_str or '{}')
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/Users/sarahmaddox/anaconda3/lib/python3.7/json/decoder.py", line 353, in raw_decode
        obj, end = self.scan_once(s, idx)
    json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 177 (char 176)

`$ /Users/sarahmaddox/anaconda3/bin/conda install velocyto`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/Users/sarahmaddox/anaconda3/bin/conda
             CONDA_PREFIX=/Users/sarahmaddox/anaconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/Users/sarahmaddox/anaconda3/bin/python
               CONDA_ROOT=/Users/sarahmaddox/anaconda3
              CONDA_SHLVL=1
                     PATH=/Users/sarahmaddox/anaconda3/bin:/usr/local/bin:/Users/sarahmaddox/ana
                          conda2/bin:/Users/sarahmaddox/opt/miniconda3/bin:/Users/sarahmaddox/an
                          aconda3/bin:/Users/sarahmaddox/anaconda3/condabin:/opt/anaconda3/bin:/
                          Users/sarahmaddox/opt/anaconda3/bin:/opt/anaconda3/bin:/anaconda3/bin:
                          /Library/Frameworks/Python.framework/Versions/3.7/bin:/Users/sarahmadd
                          ox/.rbenv/shims:/Users/sarahmaddox/.rbenv/shims:/Users/sarahmaddox/.rb
                          env/shims:/usr/local/sbin:/usr/local/sbin:/anaconda3/bin:/opt/local/bi
                          n:/opt/local/sbin:/Library/Frameworks/Python.framework/Versions/2.7/bi
                          n:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Librar
                          y/TeX/texbin:/opt/X11/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

  
```

## Expected Behavior

conda should update or install packages without this json decoding error. 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
  active environment : base
    active env location : /Users/sarahmaddox/anaconda3
            shell level : 1
       user config file : /Users/sarahmaddox/.condarc
 populated config files : /Users/sarahmaddox/.condarc
          conda version : 4.7.5
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /Users/sarahmaddox/anaconda3  (writable)
           channel URLs : https://git.skewed.de/count0/graph-tool.git/osx-64
                          https://git.skewed.de/count0/graph-tool.git/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://conda.anaconda.org/r/osx-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/sarahmaddox/anaconda3/pkgs
                          /Users/sarahmaddox/.conda/pkgs
       envs directories : /Users/sarahmaddox/anaconda3/envs
                          /Users/sarahmaddox/.conda/envs
               platform : osx-64
             user-agent : conda/4.7.5 requests/2.21.0 CPython/3.7.3 Darwin/19.2.0 OSX/10.15.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> /Users/sarahmaddox/.condarc <==
allow_conda_downgrades: True
ssl_verify: True
channels:
  - https://git.skewed.de/count0/graph-tool.git
  - bioconda
  - r
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  2019.03                  py37_0    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.2                    py37_0    defaults
anndata                   0.6.19                   pypi_0    pypi
appnope                   0.1.0                    py37_0    defaults
appscript                 1.1.0            py37h1de35cc_0    defaults
asn1crypto                0.24.0                   py37_0    defaults
astroid                   2.2.5                    py37_0    defaults
astropy                   3.1.2            py37h1de35cc_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.1.0                   py37_1    defaults
babel                     2.6.0                    py37_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                      py37_1    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
bbknn                     1.3.3                      py_0    bioconda
beautifulsoup4            4.7.1                    py37_1    defaults
bitarray                  0.8.3            py37h1de35cc_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.15.0               hd9629dc_0    defaults
bokeh                     1.0.4                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.2.1            py37h1d22016_1    defaults
bzip2                     1.0.6                h1de35cc_5    defaults
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cairo                     1.14.12           h9d4d9ac_1005    conda-forge
certifi                   2019.6.16                py37_0    conda-forge
cffi                      1.12.2           py37hb5b8e2f_1    defaults
chardet                   3.0.4                    py37_1    defaults
click                     7.0                      py37_0    defaults
cloog                     0.18.0                        0    https://repo.anaconda.com/pkgs/free
cloudpickle               0.8.0                    py37_0    defaults
clyent                    1.2.2                    py37_1    defaults
cmake                     3.14.4                   pypi_0    pypi
colorama                  0.4.1                    py37_0    defaults
conda                     4.7.5                    py37_0    conda-forge
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.3.11                   py37_0    conda-forge
conda-verify              3.1.1                    py37_0    defaults
contextlib2               0.5.5                    py37_0    defaults
cryptography              2.6.1            py37ha12b0ac_0    defaults
curl                      7.64.0               ha441bb4_2    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.6           py37h0a44026_0    conda-forge
cytoolz                   0.9.0.1          py37h1de35cc_1    defaults
dask                      1.1.4                    py37_1    defaults
dask-core                 1.1.4                    py37_1    defaults
dbus                      1.13.6               h90a0687_0    defaults
decorator                 4.4.0                    py37_1    defaults
defusedxml                0.5.0                    py37_1    defaults
distributed               1.26.0                   py37_1    defaults
docutils                  0.14                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
expat                     2.2.6                h0a44026_0    defaults
fastcache                 1.0.2            py37h1de35cc_2    defaults
ffmpeg                    4.1.3                h5c2b479_0    conda-forge
filelock                  3.0.10                   py37_0    defaults
flask                     1.0.2                    py37_1    defaults
fontconfig                2.13.1            h1027ab8_1000    conda-forge
freetype                  2.9.1                hb4e5f40_0    defaults
future                    0.17.1                   py37_0    defaults
gcc                       4.8.5                         8    conda-forge
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1             h15daf44_3    defaults
gevent                    1.4.0            py37h1de35cc_0    defaults
glib                      2.56.2               hd9629dc_0    defaults
glob2                     0.6                      py37_1    defaults
gmp                       6.1.2                hb37e062_1    defaults
gmpy2                     2.0.8            py37h6ef4df4_2    defaults
gnutls                    3.6.5             h53004b3_1002    conda-forge
greenlet                  0.4.15           py37h1de35cc_0    defaults
h5py                      2.9.0            py37h3134771_0    defaults
hdf5                      1.10.4               hfa1e0ec_0    defaults
heapdict                  1.0.0                    py37_2    defaults
html5lib                  1.0.1                    py37_0    defaults
icu                       58.2                 h4b95b61_1    defaults
idna                      2.8                      py37_0    defaults
igraph                    0.7.1             h0a67f88_1005    conda-forge
imageio                   2.5.0                    py37_0    defaults
imagesize                 1.1.0                    py37_0    defaults
importlib_metadata        0.8                      py37_0    defaults
intel-openmp              2019.3                      199    defaults
ipykernel                 5.1.0            py37h39e3cac_0    defaults
ipython                   7.4.0            py37h39e3cac_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.4.2                    py37_0    defaults
isl                       0.12.2                        1    conda-forge
isort                     4.3.16                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jbig                      2.1                  h4d881f8_0    defaults
jdcal                     1.4                      py37_0    defaults
jedi                      0.13.3                   py37_0    defaults
jinja2                    2.10                     py37_0    defaults
joblib                    0.13.2                   pypi_0    pypi
jpeg                      9b                   he5867d9_2    defaults
jsonschema                3.0.1                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.2.4                    py37_0    defaults
jupyter_console           6.0.0                    py37_0    defaults
jupyter_core              4.4.0                    py37_0    defaults
jupyterlab                0.35.4           py37hf63ae98_0    defaults
jupyterlab_server         0.2.0                    py37_0    defaults
keyring                   18.0.0                   py37_0    defaults
kiwisolver                1.0.1            py37h0a44026_0    defaults
krb5                      1.16.1               hddcf347_7    defaults
lame                      3.100             h1de35cc_1001    conda-forge
lazy-object-proxy         1.3.1            py37h1de35cc_2    defaults
libarchive                3.3.3                h786848e_5    defaults
libcurl                   7.64.0               h051b688_2    defaults
libcxx                    4.0.1                hcfea43d_1    defaults
libcxxabi                 4.0.1                hcfea43d_1    defaults
libedit                   3.1.20181209         hb402a30_0    defaults
libffi                    3.2.1                h475c297_4    defaults
libgfortran               3.0.1                h93005f0_2    defaults
libiconv                  1.15                 hdd342a3_7    defaults
liblief                   0.9.0                h2a1bed3_2    defaults
libpng                    1.6.36               ha441bb4_0    defaults
libsodium                 1.0.16               h3efe00b_0    defaults
libssh2                   1.8.0                ha12b0ac_4    defaults
libtiff                   4.0.10               hcb84e12_2    defaults
libxml2                   2.9.9                hab757c2_0    defaults
libxslt                   1.1.33               h33a18ac_0    defaults
llvmlite                  0.28.0           py37h8c7ce04_0    defaults
locket                    0.2.0                    py37_1    defaults
loompy                    2.0.17                   pypi_0    pypi
louvain                   0.6.1            py37h0a44026_2    conda-forge
lxml                      4.3.2            py37hef8c89e_0    defaults
lz4-c                     1.8.1.2              h1de35cc_0    defaults
lzo                       2.10                 h362108e_2    defaults
markupsafe                1.1.1            py37h1de35cc_0    defaults
matplotlib                3.0.3            py37h54f8f79_0    defaults
mccabe                    0.6.1                    py37_1    defaults
mistune                   0.8.4            py37h1de35cc_0    defaults
mkl                       2019.3                      199    defaults
mkl-service               1.1.2            py37hfbe908c_5    defaults
mkl_fft                   1.0.10           py37h5e564d8_0    defaults
mkl_random                1.0.2            py37h27c97d8_0    defaults
mock                      3.0.5                    pypi_0    pypi
more-itertools            6.0.0                    py37_0    defaults
mpc                       1.1.0                h6ef4df4_1    defaults
mpfr                      4.0.1                h3018a27_3    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37h04f5b5a_1    defaults
multicoretsne             0.1                      pypi_0    pypi
multipledispatch          0.6.0                    py37_0    defaults
natsort                   6.0.0                    pypi_0    pypi
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.4.1                    py37_3    defaults
nbformat                  4.4.0                    py37_0    defaults
ncurses                   6.1                  h0a44026_1    defaults
nettle                    3.4.1             h3efe00b_1002    conda-forge
networkx                  2.2                      py37_1    defaults
nltk                      3.4                      py37_1    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  5.7.8                    py37_0    defaults
numba                     0.43.1           py37h6440ff4_0    defaults
numexpr                   2.6.9            py37h7413580_0    defaults
numpy                     1.16.2           py37hacdab7b_0    defaults
numpy-base                1.16.2           py37h6575580_0    defaults
numpydoc                  0.8.0                    py37_0    defaults
olefile                   0.46                     py37_0    defaults
openh264                  1.8.0             hd9629dc_1000    conda-forge
openpyxl                  2.6.1                    py37_1    defaults
openssl                   1.1.1c               h01d97ff_0    conda-forge
packaging                 19.0                     py37_0    defaults
pandas                    0.24.2           py37h0a44026_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.3.4                    py37_0    defaults
partd                     0.3.10                   py37_1    defaults
path.py                   11.5.0                   py37_0    defaults
pathlib2                  2.3.3                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pcre                      8.43                 h0a44026_0    defaults
pep8                      1.7.1                    py37_0    defaults
pexpect                   4.6.0                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    5.4.1            py37hb68e598_0    defaults
pip                       19.3.1                   pypi_0    pypi
pixman                    0.34.0            h1de35cc_1003    conda-forge
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.9.0                    py37_0    defaults
ply                       3.11                     py37_0    defaults
prometheus_client         0.6.0                    py37_0    defaults
prompt_toolkit            2.0.9                    py37_0    defaults
psutil                    5.6.1            py37h1de35cc_0    defaults
ptyprocess                0.6.0                    py37_0    defaults
py                        1.8.0                    py37_0    defaults
py-lief                   0.9.0            py37h1413db1_2    defaults
pycairo                   1.18.0          py37ha54c0a8_1000    conda-forge
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37h1de35cc_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37h1de35cc_9    defaults
pycurl                    7.43.0.2         py37ha12b0ac_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.3.1                    py37_0    defaults
pylint                    2.3.1                    py37_0    defaults
pyodbc                    4.0.26           py37h0a44026_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pyparsing                 2.3.1                    py37_0    defaults
pyqt                      5.9.2            py37h655552a_2    defaults
pyrsistent                0.14.11          py37h1de35cc_0    defaults
pysam                     0.15.2                   pypi_0    pypi
pysocks                   1.6.8                    py37_0    defaults
pytables                  3.5.1            py37h5bccee9_0    defaults
pytest                    4.3.1                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.5.0                    py37_0    defaults
pytest-doctestplus        0.3.0                    py37_0    defaults
pytest-openfiles          0.3.2                    py37_0    defaults
pytest-remotedata         0.3.1                    py37_0    defaults
python                    3.7.3                h359304d_0    defaults
python-annoy              1.15.2           py37h6de7cb9_0    conda-forge
python-dateutil           2.8.0                    py37_0    defaults
python-igraph             0.7.1.post7      py37h01d97ff_0    conda-forge
python-libarchive-c       2.8                      py37_6    defaults
python.app                2                        py37_9    defaults
pytz                      2018.9                   py37_0    defaults
pywavelets                1.0.2            py37h1d22016_0    defaults
pyyaml                    5.1              py37h1de35cc_0    defaults
pyzmq                     18.0.0           py37h0a44026_0    defaults
qt                        5.9.7                h468cd18_1    defaults
qtawesome                 0.5.7                    py37_1    defaults
qtconsole                 4.4.3                    py37_0    defaults
qtpy                      1.7.0                    py37_1    defaults
readline                  7.0                  h1de35cc_5    defaults
requests                  2.21.0                   py37_0    defaults
rope                      0.12.0                   py37_0    defaults
rpy2                      3.0.4                    pypi_0    pypi
ruamel_yaml               0.15.46          py37h1de35cc_0    defaults
scanpy                    1.4.3                    pypi_0    pypi
scikit-image              0.14.2           py37h0a44026_0    defaults
scikit-learn              0.20.3           py37h27c97d8_0    defaults
scipy                     1.2.1            py37h1410ff5_0    defaults
scvelo                    0.1.17                   pypi_0    pypi
seaborn                   0.9.0                    py37_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                40.8.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h0a44026_0    defaults
six                       1.12.0                   py37_0    defaults
snappy                    1.1.7                he62c110_3    defaults
snowballstemmer           1.2.1                    py37_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.8                      py37_0    defaults
sphinx                    1.8.5                    py37_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-websupport  1.1.0                    py37_1    defaults
spyder                    3.3.3                    py37_0    defaults
spyder-kernels            0.4.2                    py37_0    defaults
sqlalchemy                1.3.1            py37h1de35cc_0    defaults
sqlite                    3.27.2               ha441bb4_0    defaults
statsmodels               0.9.0            py37h1d22016_0    defaults
sympy                     1.3                      py37_0    defaults
tblib                     1.3.2                    py37_0    defaults
terminado                 0.8.1                    py37_1    defaults
testpath                  0.4.2                    py37_0    defaults
tk                        8.6.8                ha441bb4_0    defaults
toolz                     0.9.0                    py37_0    defaults
tornado                   6.0.2            py37h1de35cc_0    defaults
tqdm                      4.31.1                   py37_1    defaults
traitlets                 4.3.2                    py37_0    defaults
umap-learn                0.3.8                    pypi_0    pypi
unicodecsv                0.14.1                   py37_0    defaults
unixodbc                  2.3.7                h1de35cc_0    defaults
urllib3                   1.24.1                   py37_0    defaults
velocyto                  0.17.17                  pypi_0    pypi
wcwidth                   0.1.7                    py37_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.14.1                   py37_0    defaults
wheel                     0.33.1                   py37_0    defaults
widgetsnbextension        3.4.2                    py37_0    defaults
wrapt                     1.11.1           py37h1de35cc_0    defaults
wurlitzer                 1.0.2                    py37_0    defaults
x264                      1!152.20180806       h1de35cc_0    conda-forge
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.1.5                    py37_0    defaults
xlwings                   0.15.4                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h1de35cc_4    defaults
yaml                      0.1.7                hc338f04_2    defaults
zeromq                    4.3.1                h0a44026_3    defaults
zict                      0.1.4                    py37_0    defaults
zipp                      0.3.3                    py37_1    defaults
zlib                      1.2.11               h1de35cc_3    defaults
zstd                      1.3.7                h5bba6e5_0    defaults
```
</p></details>

**Comment by soapy1** [comment]
Looks like the issue probably has to do with the `https://git.skewed.de/count0/graph-tool.git` in your list of channels. When I removed that channel it worked for me. Also, it seems like the package is `velocyto.py`. So, I got this to work by running `conda install velocyto.py`.

Conda should probably give a more useful error message here though

**Comment by smgroves** [comment]
Thanks! That seemed to solve the JSON error!
