### ISSUE TITLE
No module named tqdm

### ISSUE THREAD

**Issue by moorepants** [conda/conda#9583]
## Current Behavior

With no recent changes to my conda create command on a Travis CI build it is now failing with:

```
$ conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION numpy cython ipopt future six setuptools sphinx numpydoc pkg-config

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/exceptions.py", line 1078, in __call__

        return func(*args, **kwargs)

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main.py", line 84, in _main

        exit_code = do_call(args, p)

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call

        exit_code = getattr(module, func_name)(args, parser)

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/main_create.py", line 37, in execute

        install(args, parser, 'create')

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/cli/install.py", line 116, in install

        if context.use_only_tar_bz2:

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda/base/context.py", line 668, in use_only_tar_bz2

        import conda_package_handling.api

      File "/home/travis/miniconda/lib/python2.7/site-packages/conda_package_handling/api.py", line 7, in <module>

        import tqdm as _tqdm

    ImportError: No module named tqdm

`$ /home/travis/miniconda/bin/conda create -q -n test-env python=3.7 numpy cython ipopt future six setuptools sphinx numpydoc pkg-config`

  environment variables:

                 CIO_TEST=<not set>

               CONDA_ROOT=/home/travis/miniconda

                 GEM_PATH=/home/travis/.rvm/gems/ruby-2.5.3:/home/travis/.rvm/gems/ruby-2.5.3@gl

                          obal

                   GOPATH=/home/travis/gopath

                  MANPATH=/home/travis/.nvm/versions/node/v8.12.0/share/man:/home/travis/.rvm/ru

                          bies/ruby-2.5.3/share/man:/usr/local/cmake-3.12.4/man:/usr/local/clang

                          -7.0.0/share/man:/usr/local/man:/usr/local/share/man:/usr/share/man:/h

                          ome/travis/.rvm/man

                     PATH=/home/travis/miniconda/bin:/home/travis/virtualenv/python3.7.1/bin:/ho

                          me/travis/bin:/home/travis/.local/bin:/usr/local/lib/jvm/openjdk11/bin

                          :/opt/pyenv/shims:/home/travis/.phpenv/shims:/home/travis/perl5/perlbr

                          ew/bin:/home/travis/.nvm/versions/node/v8.12.0/bin:/home/travis/.rvm/g

                          ems/ruby-2.5.3/bin:/home/travis/.rvm/gems/ruby-2.5.3@global/bin:/home/

                          travis/.rvm/rubies/ruby-2.5.3/bin:/home/travis/gopath/bin:/home/travis

                          /.gimme/versions/go1.11.1.linux.amd64/bin:/usr/local/maven-3.6.0/bin:/

                          usr/local/cmake-3.12.4/bin:/usr/local/clang-7.0.0/bin:/usr/local/sbin:

                          /usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.r

                          vm/bin:/home/travis/.phpenv/bin:/opt/pyenv/bin:/home/travis/.yarn/bin

            PYTHON_CFLAGS=-g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror

                          =format-security

    PYTHON_CONFIGURE_OPTS=--enable-unicode=ucs4 --with-wide-unicode --enable-shared --enable-

                          ipv6 --enable-loadable-sqlite-extensions --with-computed-gotos

       REQUESTS_CA_BUNDLE=<not set>

            SSL_CERT_FILE=<not set>

         TRAVIS_APT_PROXY=<set>

             rvm_bin_path=/home/travis/.rvm/bin

                 rvm_path=/home/travis/.rvm

     active environment : None

       user config file : /home/travis/.condarc

 populated config files : /home/travis/.condarc

          conda version : 4.8.0

    conda-build version : not installed

         python version : 2.7.15.final.0

       virtual packages : __glibc=2.23

       base environment : /home/travis/miniconda  (writable)

           channel URLs : https://conda.anaconda.org/conda-forge/linux-64

                          https://conda.anaconda.org/conda-forge/noarch

                          https://repo.anaconda.com/pkgs/main/linux-64

                          https://repo.anaconda.com/pkgs/main/noarch

                          https://repo.anaconda.com/pkgs/r/linux-64

                          https://repo.anaconda.com/pkgs/r/noarch

          package cache : /home/travis/miniconda/pkgs

                          /home/travis/.conda/pkgs

       envs directories : /home/travis/miniconda/envs

                          /home/travis/.conda/envs

               platform : linux-64

             user-agent : conda/4.8.0 requests/2.22.0 CPython/2.7.15 Linux/4.15.0-1028-gcp ubuntu/16.04.5 glibc/2.23

                UID:GID : 2000:2000

             netrc file : None

           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

Upload successful.

The command "conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION numpy cython ipopt future six setuptools sphinx numpydoc pkg-config" failed and exited with 1 during .
```

Python version 3.7.

Build log: https://travis-ci.org/matthias-k/cyipopt/builds/635004783

### Steps to Reproduce

```

```

## Expected Behavior

Packages should install.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by matthias-k** [comment]
@moorepants I had the same issue in another library and it turned out I was using an outdated way to install miniconda. I think the most relevant difference was that I was using `https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh` instead of `https://repo.continuum.io/miniconda/Miniconda{2,3}-latest-Linux-x86_64.sh`.
I updated the travis file to what's suggested [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html) and now it works again.

**Comment by moorepants** [comment]
Thanks, I'll give it a try. Crazy that they'd change this URL being that it is so widely used.

**Comment by moorepants** [comment]
Changing the URL worked. Thanks.
