### ISSUE TITLE
NAVIGATION ERROR WHEN TRYING TO OPEN

### ISSUE THREAD

**Issue by EdidiongEsu** [conda/conda#9618]
This error shows up when I try to load my anaconda. It started when my computer went off during a power outage. I have uninstalled it but the error still shows. I'm in the middle of a project, PLEASE HELP!!! 
This is what shows:

Main Error
expected str, bytes or os.PathLike object, not NoneType
Traceback
Traceback (most recent call last):
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
return_value = func(*args, **kwargs)
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
window = run_app(splash)
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
window = MainWindow(splash=splash, tab_project=False)
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in init
self.api = AnacondaAPI()
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
ANACONDA_API = _AnacondaAPI()
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in init
self._conda_api = CondaAPI()
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
CONDA_API = _CondaAPI()
File "C:\Users\ru\Anaconda3\lib\site-packages\anaconda_navigator\api\conda_api.py", line 353, in init
self.sys_rc_path = join(self.ROOT_PREFIX, '.condarc')
File "C:\Users\ru\Anaconda3\lib\ntpath.py", line 76, in join
path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not NoneType

![Capture](https://user-images.githubusercontent.com/54672202/72815898-a8d43900-3c67-11ea-93f1-af925285030d.JPG)

**Comment by EdidiongEsu** [comment]
solved this by deleting the `C:\Users\ru\.condarc` file
