### ISSUE TITLE
Error in importing numpy after installing anaconda3

### ISSUE THREAD

**Issue by neuronphysics** [conda/conda#9620]
I installed anaconda3 on my macos laptop and I get this error 

```
>>> import numpy
Traceback (most recent call last):
  File "/Users/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/Users/Library/Python/3.7/lib/python/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/Users/Library/Python/3.7/lib/python/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ImportError: dlopen(/Users/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Library/Python/3.7/lib/python/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/Users/Library/Python/3.7/lib/python/site-packages/numpy/core/__init__.py", line 54, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.7 from "/usr/local/opt/python/bin/python3.7",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.18.0" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: dlopen(/Users/Library/Python/3.7/lib/python/site-packages/numpy/core/_multiarray_umath.cpython-37m-darwin.so, 2): Symbol not found: ___addtf3
  Referenced from: /Users/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Library/Python/3.7/lib/python/site-packages/numpy/core/../.dylibs/libquadmath.0.dylib

>>> quit()
(base) cscf-adms-MacBook-Pro:softwares zsheikhb$ conda update numpy
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(base) cscf-adms-MacBook-Pro:softwares zsheikhb$ 

```
I also added anaconda's path to my ~/.bash_profile. Any suggestion why is breaking down?

**Comment by forrestwaters** [comment]
Per the issue template, this issue should be created in https://github.com/ContinuumIO/anaconda-issues
Based on your output, it looks like you're using system python and not anaconda python, but please fill out all information requested in the issue template for us to be able to attempt to help you.
