### ISSUE TITLE
root prefix

### ISSUE THREAD

**Issue by erencgul** [conda/conda#9652]
I get this error page when I try to open navigator on conda prompt. Nothing shows up when I try to launch navigator from exe.

Main Error

'root_prefix'

Traceback

Traceback (most recent call last):
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\exceptions.py", line 75, in exception_handler
    return_value = func(*args, **kwargs)
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\app\start.py", line 151, in start_app
    window = run_app(splash)
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\app\start.py", line 65, in run_app
    window = MainWindow(splash=splash, tab_project=False)
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\widgets\main_window.py", line 168, in __init__
    self.api = AnacondaAPI()
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 2337, in AnacondaAPI
    ANACONDA_API = _AnacondaAPI()
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\api\anaconda_api.py", line 89, in __init__
    self._conda_api = CondaAPI()
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 1767, in CondaAPI
    CONDA_API = _CondaAPI()
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 350, in __init__
    self.set_conda_prefix(info=get_conda_info())
  File "D:\pyhtonconda\lib\site-packages\anaconda_navigator\api\conda_api.py", line 505, in set_conda_prefix
    self.ROOT_PREFIX = info['root_prefix']
KeyError: 'root_prefix'

**Comment by kalefranz** [comment]
I believe you have a very old version of Anaconda Navigator. The easiest thing to do is download the latest Anaconda and just do a fresh install.
