### ISSUE TITLE
Order of dependency installation

### ISSUE THREAD

**Issue by susheelbhanu** [conda/conda#9658]
Hi, 

Is there a way to specify the order in which dependencies are installed from a '.yml' file? 

I have the following dependencies in a **AMR.yml** file:
```
name: AMR_test.yml
channels:
  - defaults
dependencies:
  - ca-certificates=2019.5.15=0
  - certifi=2019.3.9=py27_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.1=he6710b0_1
  - openssl=1.1.1c=h7b6447c_1
  - pip=19.1.1=py27_0
  - python=2.7.16=h9bab390_0
  - readline=7.0=h7b6447c_5
  - setuptools=41.0.1=py27_0
  - sqlite=3.28.0=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.4=py27_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - gdbn==0.1
    - gnumpy==0.2
    - joblib==0.9.3
    - nolearn==0.6.0
    - numpy==1.10.4
    - scikit-learn==0.17
    - scipy==0.16.1
    - six==1.12.0
    - tabulate==0.7.5
    - theano==0.8.0
    - tqdm==4.32.2
```

Everytime I try to install **(conda env create -f AMR.yml)** the environment, it is failing with the following error:
```
Ran pip subprocess with arguments:
['/home/users/sbusi/apps/miniconda3/envs/AMR_test.yml/bin/python', '-m', 'pip', 'install', '-U', '-r', '/mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt']
Pip subprocess output:
Collecting gdbn==0.1 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 1))
Collecting gnumpy==0.2 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 2))
Collecting joblib==0.9.3 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/d4/de/3ac3ffb6eee086b23da2d27aecc318b9c08889fb8313e22fdf5a5de1ec3c/joblib-0.9.3-py2.py3-none-any.whl
Collecting nolearn==0.6.0 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 4))
Collecting numpy==1.10.4 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/4b/06/c7df438b7b89e16161e4cc2183b5d7f36d0e5ceb46aa0adc4df12a8e8268/numpy-1.10.4-cp27-cp27mu-manylinux1_x86_64.whl
Collecting scikit-learn==0.17 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/60/b8/c420dce3f72d95e06f7c1e50a6e705f4e8b6078d7d6db38425ac77ae3fab/scikit-learn-0.17.tar.gz
Collecting scipy==0.16.1 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/11/72/838cbee2404fad56002e0160bf9028e9dbc71c95c66d8093b70b19df0e35/scipy-0.16.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting six==1.12.0 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting tabulate==0.7.5 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 9))
Collecting theano==0.8.0 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 10))
Collecting tqdm==4.32.2 (from -r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/9f/3d/7a6b68b631d2ab54975f3a4863f3c4e9b26445353264ef01f465dc9b0208/tqdm-4.32.2-py2.py3-none-any.whl
Collecting Lasagne (from nolearn==0.6.0->-r /mnt/lscratch/users/sbusi/pathofact/PathoFact/conda_environments/condaenv.ck9mc8za.requirements.txt (line 4))
Building wheels for collected packages: scikit-learn
  Building wheel for scikit-learn (setup.py): started
  Building wheel for scikit-learn (setup.py): finished with status 'error'
  Running setup.py clean for scikit-learn
Failed to build scikit-learn
Installing collected packages: gnumpy, gdbn, joblib, scikit-learn, numpy, scipy, six, theano, tabulate, Lasagne, nolearn, tqdm
  Running setup.py install for scikit-learn: started
    Running setup.py install for scikit-learn: finished with status 'error'

Pip subprocess error:
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  ERROR: Complete output from command /home/users/sbusi/apps/miniconda3/envs/AMR_test.yml/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-Go5F7u/scikit-learn/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mRpvoM --python-tag cp27:
  ERROR: Partial import of sklearn during the build process.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-Go5F7u/scikit-learn/setup.py", line 247, in <module>
      setup_package()
    File "/tmp/pip-install-Go5F7u/scikit-learn/setup.py", line 227, in setup_package
      .format(numpy_req_str, instructions))
  ImportError: Numerical Python (NumPy) is not installed.
  scikit-learn requires NumPy >= 1.6.1.
  Installation instructions are available on the scikit-learn website: http://scikit-learn.org/stable/install.html
```
For some reason, scikit-learn is being installed prior to numpy. Also, shouldn't scikit-learn first install all the required dependencies such as numpy in the first place? 

Thanks for your help!
-Susheel

**Comment by kalefranz** [comment]
This is a pip issue, not a conda issue. If you let conda install `numpy` and `scikit-learn` instead of pip, then you won't have this problem.
