### ISSUE TITLE
Unexpected error in conda update conda command

### ISSUE THREAD

**Issue by Corxrew** [conda/conda#9659]
I have installed Anaconda3 for 64 bit system on Ubuntu properly but whenever I execute conda update conda command on terminal this following error is produced. I have tried everything from clearing cache to freshly installing Anaconda3 a couple of times. I even thought of installling miniconda instead only to find a similar error 

Current conda install:

               platform : linux-64
          conda version : 4.3.16
       conda is private : False
      conda-env version : 4.3.16
    conda-build version : 3.18.9
         python version : 3.7.4.final.0
       requests version : 2.22.0
       root environment : /home/ayush/anaconda3  (writable)
    default environment : /home/ayush/anaconda3
       envs directories : /home/ayush/anaconda3/envs
                          /home/ayush/.conda/envs
          package cache : /home/ayush/anaconda3/pkgs
                          /home/ayush/.conda/pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.16 requests/2.22.0 CPython/3.7.4 Linux/5.3.0-29-generic debian/buster/sid glibc/2.30
                UID:GID : 1000:1000

`$ /home/ayush/anaconda3/bin/conda update conda`

    Traceback (most recent call last):
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 44, in yield_lines
        with open(path) as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/ayush/anaconda3/pkgs/conda-env-2.6.0-0/info/has_prefix'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 52, in yield_lines
        raise StopIteration
    StopIteration
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/cli/install.py", line 357, in install
        execute_actions(actions, index, verbose=not context.quiet)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/plan.py", line 809, in execute_actions
        execute_instructions(plan, index, verbose)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/instructions.py", line 247, in execute_instructions
        cmd(state, arg)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/instructions.py", line 107, in UNLINKLINKTRANSACTION_CMD
        txn = UnlinkLinkTransaction.create_from_dists(index, prefix, unlink_dists, link_dists)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/core/link.py", line 124, in create_from_dists
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/core/link.py", line 124, in <genexpr>
        for dist, pkg_dir in zip(link_dists, pkg_dirs_to_link))
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 84, in read_package_info
        paths_data = read_paths_json(extracted_package_directory)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 150, in read_paths_json
        has_prefix_files = read_has_prefix(join(info_dir, 'has_prefix'))
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 200, in read_has_prefix
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 200, in <dictcomp>
        return {pr.filepath: (pr.placeholder, pr.filemode) for pr in parsed_lines}
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 199, in <genexpr>
        parsed_lines = (parse_line(line) for line in yield_lines(path))
    RuntimeError: generator raised StopIteration
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/cli/main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/cli/main_update.py", line 65, in execute
        install(args, parser, 'update')
      File "/home/ayush/.local/lib/python3.7/site-packages/conda/cli/install.py", line 372, in install
        raise CondaRuntimeError('RuntimeError: %s' % e)
    conda.exceptions.CondaRuntimeError: Runtime error: RuntimeError: generator raised StopIteration

**Comment by Corxrew** [comment]
Figured it out, the problem was because I have installed coda through "pip install conda" which waas causing issues. Just deleting the former package did the job
