### ISSUE TITLE
'Collecting package metadata (current_repodata.json)': failed due to proxy error

### ISSUE THREAD

**Issue by 2403772980ygy** [conda/conda#9670]
## Current Behavior

Conda can't collect package data(seems to be a proxy error)

### Steps to Reproduce

```
conda install python=#
```

It outputs:

```plain
# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "D:\Anaconda3\lib\site-packages\conda\exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "D:\Anaconda3\lib\site-packages\conda\cli\conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "D:\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "D:\Anaconda3\lib\site-packages\conda\cli\install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "D:\Anaconda3\lib\site-packages\conda\common\io.py", line 88, in decorated
        return f(*args, **kwds)
      File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "D:\Anaconda3\lib\site-packages\conda\core\solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "D:\Anaconda3\lib\site-packages\conda\core\index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "D:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "D:\Anaconda3\lib\concurrent\futures\_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "D:\Anaconda3\lib\concurrent\futures\_base.py", line 435, in result
        return self.__get_result()
      File "D:\Anaconda3\lib\concurrent\futures\_base.py", line 384, in __get_result
        raise self._exception
      File "D:\Anaconda3\lib\concurrent\futures\thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "D:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "D:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 110, in query
        self.load()
      File "D:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "D:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "D:\Anaconda3\lib\site-packages\conda\core\subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "D:\Anaconda3\lib\site-packages\requests\adapters.py", line 199, in proxy_manager_for
        **proxy_kwargs)
      File "D:\Anaconda3\lib\site-packages\urllib3\poolmanager.py", line 470, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "D:\Anaconda3\lib\site-packages\urllib3\poolmanager.py", line 420, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

`$ D:\Anaconda3\Scripts\conda-script.py install python=#`

  environment variables:
                 CIO_TEST=<not set>
                CONDA_EXE=D:\Anaconda3\condabin\..\Scripts\conda.exe
               CONDA_EXES="D:\Anaconda3\condabin\..\Scripts\conda.exe"
               CONDA_ROOT=D:\Anaconda3
                CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2
       FR_CUSTOMDATA_PATH=D:\FaceRig\Mod\VP\PC_CustomData"
                 HOMEPATH=\Users\ygy
              HTTPS_PROXY=<set>
               HTTP_PROXY=<set>
      MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared
                          Libraries\compiler\lib\mic
          NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
                     PATH=D:\Anaconda3;D:\Anaconda3\Library\mingw-w64\bin;D:\Anaconda3\Library\u
                          sr\bin;D:\Anaconda3\Library\bin;D:\Anaconda3\Scripts;D:\Anaconda3\bin;
                          C:\Program Files\PowerShell\7-preview;C:\Program Files\NVIDIA GPU
                          Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing
                          Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\Common
                          Files\Intel\Shared Libraries\redist\intel64\compiler;C:\Program Files
                          (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS
                          ;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
                          C:\WINDOWS\System32\OpenSSH\;C:\Program
                          Files\dotnet\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft
                          SQL Server\130\Tools\Binn\;D:\Git\cmd;C:\Program Files\NVIDIA
                          Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA
                          Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program
                          Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\P
                          rogramData\chocolatey\lib\mpv.install\tools;C:\Strawberry\perl\site\bi
                          n;C:\Strawberry\perl\bin;D:\composer;C:\Program Files\Microsoft SQL
                          Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files
                          (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft
                          SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL
                          Server\120\DTS\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows
                          Performance Toolkit\;C:\Program Files\Microsoft SQL Server\Client
                          SDK\ODBC\170\Tools\Binn\;C:\ProgramData\chocolatey\lib\maven\apache-
                          maven-3.6.3\bin;D:\FPC\3.0.4\bin\i386-Win32;C:\Program
                          Files\PowerShell\7-preview\preview;C:\Program Files\Docker\Docker\reso
                          urces\bin;C:\ProgramData\DockerDesktop\version-
                          bin;D:\SlikSvn\bin;C:\Program Files\TortoiseSVN\bin;C:\Program
                          Files\NVIDIA Corporation\Nsight Compute 2019.5.0\;C:\WINDOWS\system32;
                          C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerSh
                          ell\v1.0\;C:\WINDOWS\System32\OpenSSH\;D:\Anaconda3;D:\Anaconda3\Libra
                          ry\mingw-w64\bin;D:\Anaconda3\Library\usr\bin;D:\Anaconda3\Library\bin
                          ;D:\Anaconda3\Scripts;C:\Users\ygy\scoop\shims;D:\Ruby26-x64\bin;C:\Us
                          ers\ygy\AppData\Local\Microsoft\WindowsApps;C:\Users\ygy\AppData\Local
                          \Pandoc\;C:\Program Files\CMake\bin;D:\ffmpeg\bin;C:\Users\ygy\AppData
                          \Roaming\npm;C:\Program Files\Bandizip\;C:\LLVM\bin;D:\php-7.4.0-nts-W
                          in32-vc15-x64;C:\Users\ygy\AppData\Roaming\Composer\vendor\bin;C:\User
                          s\ygy\AppData\Local\atom-beta\bin;D:\texlive\2019\bin\win32;C:\Users\y
                          gy\AppData\Local\Microsoft\WindowsApps;C:\Users\ygy\AppData\Local\GitH
                          ubDesktop\bin;C:\Users\ygy\AppData\Local\Programs\Microsoft VS Code In
                          siders\bin;C:\Users\ygy\AppData\Local\video2x\waifu2x-caffe;D:\aria2-1
                          .35.0-win-64bit-build1;D:\electron;
             PSMODULEPATH=C:\Users\ygy\Documents\PowerShell\Modules;C:\Program
                          Files\PowerShell\Modules;c:\program
                          files\powershell\7-preview\Modules;C:\Program Files\WindowsPowerShell\
                          Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program
                          Files (x86)\Microsoft SQL Server\120\Tools\PowerShell\Modules\
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
    VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\

     active environment : None
       user config file : C:\Users\ygy\.condarc
 populated config files : C:\Users\ygy\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\ygy\.conda\pkgs
                          C:\Users\ygy\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\ygy\.conda\envs
                          C:\Users\ygy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19559
          administrator : False
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

Upload successful.
```

Note: my environment have the proxy set as follows

![image](https://user-images.githubusercontent.com/40046418/74084981-542a1e00-4aaf-11ea-9ab6-6ae3eaa8a0b8.png)

## Expected Behavior

install the latest version of python, which is 3.8.1

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : None
       user config file : C:\Users\ygy\.condarc
 populated config files : C:\Users\ygy\.condarc
          conda version : 4.8.2
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __cuda=11.0
       base environment : D:\Anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : D:\Anaconda3\pkgs
                          C:\Users\ygy\.conda\pkgs
                          C:\Users\ygy\AppData\Local\conda\conda\pkgs
       envs directories : D:\Anaconda3\envs
                          C:\Users\ygy\.conda\envs
                          C:\Users\ygy\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Windows/10 Windows/10.0.19559
          administrator : False
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
proxy_servers:
  http: 127.0.0.1:1080
  https: 127.0.0.1:1080
channels:
  - defaults
report_errors: True
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at D:\Anaconda3:
#
# Name                    Version                   Build  Channel
_anaconda_depends         2019.03                  py37_0    defaults
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0    defaults
alabaster                 0.7.12                   py37_0    defaults
anaconda                  custom                   py37_1    defaults
anaconda-client           1.7.2                    py37_0    defaults
anaconda-navigator        1.9.7                    py37_0    defaults
anaconda-project          0.8.4                      py_0    defaults
asn1crypto                1.3.0                    py37_0    defaults
astroid                   2.3.3                    py37_0    defaults
astropy                   4.0              py37he774522_0    defaults
atomicwrites              1.3.0                    py37_1    defaults
attrs                     19.3.0                     py_0    defaults
babel                     2.8.0                      py_0    defaults
backcall                  0.1.0                    py37_0    defaults
backports                 1.0                        py_2    defaults
backports.functools_lru_cache 1.6.1                      py_0    defaults
backports.os              0.1.1                    py37_0    defaults
backports.shutil_get_terminal_size 1.0.0                    py37_2    defaults
backports.tempfile        1.0                        py_1    defaults
backports.weakref         1.0.post1                  py_1    defaults
beautifulsoup4            4.8.2                    py37_0    defaults
bitarray                  1.2.1            py37he774522_0    defaults
bkcharts                  0.2                      py37_0    defaults
blas                      1.0                         mkl    defaults
bleach                    3.1.0                    py37_0    defaults
blosc                     1.16.3               h7bd577a_0    defaults
bokeh                     1.4.0                    py37_0    defaults
boto                      2.49.0                   py37_0    defaults
bottleneck                1.3.1            py37h8c2d366_0    defaults
bzip2                     1.0.8                he774522_0    defaults
ca-certificates           2020.1.1                      0    defaults
certifi                   2019.11.28               py37_0    defaults
cffi                      1.13.2           py37h7a1dbc1_0    defaults
chardet                   3.0.4                 py37_1003    defaults
click                     7.0                      py37_0    defaults
cloudpickle               1.2.2                      py_0    defaults
clyent                    1.2.2                    py37_1    defaults
colorama                  0.4.3                      py_0    defaults
comtypes                  1.1.7                    py37_0    defaults
conda                     4.8.2                    py37_0    defaults
conda-build               3.18.11                  py37_0    defaults
conda-env                 2.6.0                         1    defaults
conda-package-handling    1.6.0            py37h62dcd97_0    defaults
conda-verify              3.4.2                      py_1    defaults
console_shortcut          0.1.1                         3    defaults
contextlib2               0.6.0.post1                py_0    defaults
cryptography              2.8              py37h7a1dbc1_0    defaults
curl                      7.68.0               h2a8f88b_0    defaults
cycler                    0.10.0                   py37_0    defaults
cython                    0.29.14          py37ha925a31_0    defaults
cytoolz                   0.10.1           py37he774522_0    defaults
dask                      2.10.1                     py_0    defaults
dask-core                 2.10.1                     py_0    defaults
decorator                 4.4.1                      py_0    defaults
defusedxml                0.6.0                      py_0    defaults
distributed               2.10.0                     py_0    defaults
docutils                  0.16                     py37_0    defaults
entrypoints               0.3                      py37_0    defaults
et_xmlfile                1.0.1                    py37_0    defaults
fastcache                 1.1.0            py37he774522_0    defaults
filelock                  3.0.12                     py_0    defaults
flask                     1.1.1                      py_0    defaults
freetype                  2.9.1                ha9979f8_1    defaults
fsspec                    0.6.2                      py_0    defaults
future                    0.18.2                   py37_0    defaults
get_terminal_size         1.0.0                h38e98db_0    defaults
gevent                    1.4.0            py37he774522_0    defaults
glob2                     0.7                        py_0    defaults
greenlet                  0.4.15           py37hfa6e2cd_0    defaults
h5py                      2.10.0           py37h5e291fa_0    defaults
hdf5                      1.10.4               h7ebc959_0    defaults
heapdict                  1.0.1                      py_0    defaults
html5lib                  1.0.1                    py37_0    defaults
hypothesis                5.4.1                      py_0    defaults
icc_rt                    2019.0.0             h0cc432a_1    defaults
icu                       58.2                 ha66f8fd_1    defaults
idna                      2.8                      py37_0    defaults
imageio                   2.6.1                    py37_0    defaults
imagesize                 1.2.0                      py_0    defaults
importlib_metadata        1.5.0                    py37_0    defaults
inflect                   4.1.0                    py37_0    defaults
intel-openmp              2020.0                      166    defaults
ipykernel                 5.1.4            py37h39e3cac_0    defaults
ipython                   7.12.0           py37h5ca1d4c_0    defaults
ipython_genutils          0.2.0                    py37_0    defaults
ipywidgets                7.5.1                      py_0    defaults
isort                     4.3.21                   py37_0    defaults
itsdangerous              1.1.0                    py37_0    defaults
jaraco.itertools          5.0.0                      py_0    defaults
jdcal                     1.4.1                      py_0    defaults
jedi                      0.16.0                   py37_0    defaults
jinja2                    2.11.1                     py_0    defaults
joblib                    0.14.1                     py_0    defaults
jpeg                      9b                   hb83a4c4_2    defaults
json5                     0.8.5                      py_0    defaults
jsonschema                3.2.0                    py37_0    defaults
jupyter                   1.0.0                    py37_7    defaults
jupyter_client            5.3.4                    py37_0    defaults
jupyter_console           6.1.0                      py_0    defaults
jupyter_core              4.6.1                    py37_0    defaults
jupyterlab                1.2.6              pyhf63ae98_0    defaults
jupyterlab_server         1.0.6                      py_0    defaults
keyring                   21.1.0                   py37_0    defaults
kiwisolver                1.1.0            py37ha925a31_0    defaults
krb5                      1.17.1               hc04afaa_0    defaults
lazy-object-proxy         1.4.3            py37he774522_0    defaults
libarchive                3.3.3                h0643e63_5    defaults
libcurl                   7.68.0               h2a8f88b_0    defaults
libiconv                  1.15                 h1df5818_7    defaults
liblief                   0.9.0                ha925a31_2    defaults
libpng                    1.6.37               h2a8f88b_0    defaults
libsodium                 1.0.16               h9d3ae62_0    defaults
libssh2                   1.8.2                h7a1dbc1_0    defaults
libtiff                   4.1.0                h56a325e_0    defaults
libxml2                   2.9.9                h464c3ec_0    defaults
libxslt                   1.1.33               h579f668_0    defaults
llvmlite                  0.31.0           py37ha925a31_0    defaults
locket                    0.2.0                    py37_1    defaults
lxml                      4.5.0            py37h1350720_0    defaults
lz4-c                     1.8.1.2              h2fa13f4_0    defaults
lzo                       2.10                 h6df0209_2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
markupsafe                1.1.1            py37he774522_0    defaults
matplotlib                3.1.3                    py37_0    defaults
matplotlib-base           3.1.3            py37h64f37c6_0    defaults
mccabe                    0.6.1                    py37_1    defaults
menuinst                  1.4.16           py37he774522_0    defaults
mistune                   0.8.4            py37he774522_0    defaults
mkl                       2020.0                      166    defaults
mkl-service               2.3.0            py37hb782905_0    defaults
mkl_fft                   1.0.15           py37h14836fe_0    defaults
mkl_random                1.1.0            py37h675688f_0    defaults
mock                      3.0.5                    py37_0    defaults
more-itertools            8.2.0                      py_0    defaults
mpmath                    1.1.0                    py37_0    defaults
msgpack-python            0.6.1            py37h74a9793_1    defaults
msys2-conda-epoch         20160418                      1    defaults
multipledispatch          0.6.0                    py37_0    defaults
navigator-updater         0.2.1                    py37_0    defaults
nbconvert                 5.6.1                    py37_0    defaults
nbformat                  5.0.4                      py_0    defaults
networkx                  2.4                        py_0    defaults
nltk                      3.4.5                    py37_0    defaults
nose                      1.3.7                    py37_2    defaults
notebook                  6.0.3                    py37_0    defaults
numba                     0.48.0           py37h47e9c7a_0    defaults
numexpr                   2.7.1            py37h25d0782_0    defaults
numpy                     1.18.1           py37h93ca92e_0    defaults
numpy-base                1.18.1           py37hc3f5095_1    defaults
numpydoc                  0.9.2                      py_0    defaults
olefile                   0.46                     py37_0    defaults
openpyxl                  3.0.3                      py_0    defaults
openssl                   1.1.1d               he774522_3    defaults
packaging                 20.1                       py_0    defaults
pandas                    1.0.0            py37h47e9c7a_0    defaults
pandoc                    2.2.3.2                       0    defaults
pandocfilters             1.4.2                    py37_1    defaults
parso                     0.6.0                      py_0    defaults
partd                     1.1.0                      py_0    defaults
path                      13.1.0                   py37_0    defaults
path.py                   12.4.0                        0    defaults
pathlib2                  2.3.5                    py37_0    defaults
patsy                     0.5.1                    py37_0    defaults
pep8                      1.7.1                    py37_0    defaults
pickleshare               0.7.5                    py37_0    defaults
pillow                    7.0.0            py37hcc1f983_0    defaults
pip                       20.0.2                   py37_1    defaults
pkginfo                   1.5.0.1                  py37_0    defaults
pluggy                    0.13.1                   py37_0    defaults
ply                       3.11                     py37_0    defaults
powershell_shortcut       0.0.1                         2    defaults
prometheus_client         0.7.1                      py_0    defaults
prompt_toolkit            3.0.3                      py_0    defaults
psutil                    5.6.7            py37he774522_0    defaults
py                        1.8.1                      py_0    defaults
py-lief                   0.9.0            py37ha925a31_2    defaults
pycodestyle               2.5.0                    py37_0    defaults
pycosat                   0.6.3            py37he774522_0    defaults
pycparser                 2.19                     py37_0    defaults
pycrypto                  2.6.1            py37hfa6e2cd_9    defaults
pycurl                    7.43.0.5         py37h7a1dbc1_0    defaults
pyflakes                  2.1.1                    py37_0    defaults
pygments                  2.5.2                      py_0    defaults
pylint                    2.4.4                    py37_0    defaults
pyodbc                    4.0.28           py37ha925a31_0    defaults
pyopenssl                 19.1.0                   py37_0    defaults
pyparsing                 2.4.6                      py_0    defaults
pyqt                      5.9.2            py37h6538335_2    defaults
pyreadline                2.1                      py37_1    defaults
pyrsistent                0.15.7           py37he774522_0    defaults
pysocks                   1.7.1                    py37_0    defaults
pytables                  3.6.1            py37h1da0976_0    defaults
pytest                    5.3.5                    py37_0    defaults
pytest-arraydiff          0.3              py37h39e3cac_0    defaults
pytest-astropy            0.7.0                      py_0    defaults
pytest-astropy-header     0.1.2                      py_0    defaults
pytest-doctestplus        0.5.0                      py_0    defaults
pytest-openfiles          0.4.0                      py_0    defaults
pytest-remotedata         0.3.2                    py37_0    defaults
python                    3.7.6                h60c2a47_2    defaults
python-dateutil           2.8.1                      py_0    defaults
python-libarchive-c       2.8                     py37_13    defaults
pytz                      2019.3                     py_0    defaults
pywavelets                1.1.1            py37he774522_0    defaults
pywin32                   227              py37he774522_1    defaults
pywin32-ctypes            0.2.0                 py37_1000    defaults
pywinpty                  0.5.7                    py37_0    defaults
pyyaml                    5.3              py37he774522_0    defaults
pyzmq                     18.1.1           py37ha925a31_0    defaults
qt                        5.9.7            vc14h73c81de_0    defaults
qtawesome                 0.6.1                      py_0    defaults
qtconsole                 4.6.0                      py_1    defaults
qtpy                      1.9.0                      py_0    defaults
requests                  2.22.0                   py37_1    defaults
rope                      0.16.0                     py_0    defaults
ruamel_yaml               0.15.87          py37he774522_0    defaults
scikit-image              0.16.2           py37h47e9c7a_0    defaults
scikit-learn              0.22.1           py37h6288b17_0    defaults
scipy                     1.4.1            py37h9439919_0    defaults
seaborn                   0.10.0                     py_0    defaults
send2trash                1.5.0                    py37_0    defaults
setuptools                45.1.0                   py37_0    defaults
simplegeneric             0.8.1                    py37_2    defaults
singledispatch            3.4.0.3                  py37_0    defaults
sip                       4.19.8           py37h6538335_0    defaults
six                       1.14.0                   py37_0    defaults
snappy                    1.1.7                h777316e_3    defaults
snowballstemmer           2.0.0                      py_0    defaults
sortedcollections         1.1.2                    py37_0    defaults
sortedcontainers          2.1.0                    py37_0    defaults
soupsieve                 1.9.5                    py37_0    defaults
sphinx                    2.3.1                      py_0    defaults
sphinxcontrib             1.0                      py37_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    defaults
sphinxcontrib-devhelp     1.0.1                      py_0    defaults
sphinxcontrib-htmlhelp    1.0.2                      py_0    defaults
sphinxcontrib-jsmath      1.0.1                      py_0    defaults
sphinxcontrib-qthelp      1.0.2                      py_0    defaults
sphinxcontrib-serializinghtml 1.1.3                      py_0    defaults
sphinxcontrib-websupport  1.1.2                      py_0    defaults
spyder                    3.3.6                    py37_0    defaults
spyder-kernels            0.5.2                    py37_0    defaults
sqlalchemy                1.3.13           py37he774522_0    defaults
sqlite                    3.31.1               he774522_0    defaults
statsmodels               0.11.0           py37he774522_0    defaults
sympy                     1.5.1                    py37_0    defaults
tbb                       2020.0               h74a9793_0    defaults
tblib                     1.6.0                      py_0    defaults
terminado                 0.8.3                    py37_0    defaults
testpath                  0.4.4                      py_0    defaults
tk                        8.6.8                hfa6e2cd_0    defaults
toolz                     0.10.0                     py_0    defaults
tornado                   6.0.3            py37he774522_1    defaults
tqdm                      4.42.0                     py_0    defaults
traitlets                 4.3.3                    py37_0    defaults
unicodecsv                0.14.1                   py37_0    defaults
urllib3                   1.25.8                   py37_0    defaults
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.16.27012          hf0eaf9b_1    defaults
wcwidth                   0.1.8                      py_0    defaults
webencodings              0.5.1                    py37_1    defaults
werkzeug                  0.16.1                     py_0    defaults
wheel                     0.34.2                   py37_0    defaults
widgetsnbextension        3.5.1                    py37_0    defaults
win_inet_pton             1.1.0                    py37_0    defaults
win_unicode_console       0.5                      py37_0    defaults
wincertstore              0.2                      py37_0    defaults
winpty                    0.4.3                         4    defaults
wrapt                     1.11.2           py37he774522_0    defaults
xlrd                      1.2.0                    py37_0    defaults
xlsxwriter                1.2.7                      py_0    defaults
xlwings                   0.17.1                   py37_0    defaults
xlwt                      1.3.0                    py37_0    defaults
xz                        5.2.4                h2fa13f4_4    defaults
yaml                      0.1.7                hc54c509_2    defaults
zeromq                    4.3.1                h33f27b4_3    defaults
zict                      1.0.0                      py_0    defaults
zipp                      2.1.0                      py_0    defaults
zlib                      1.2.11               h62dcd97_3    defaults
zstd                      1.3.7                h508b16e_0    defaults
```
</p></details>

**Comment by 2403772980ygy** [comment]
solved by adding `http://` before the proxy address.

**Comment by Divyarajvs** [comment]
how and where to edit the proxy as mentioned above?
