### ISSUE TITLE
Some unexpected downgrades with conda on appveyor

### ISSUE THREAD

**Issue by rebeccabilbro** [conda/conda#9711]
Howdy!  Fellow OSS maintainer ([scikit-yellowbrick](https://github.com/districtdatalabs/yellowbrick)) here, and experiencing some unexpected behavior when our tests are trying to run with conda in CI on Appveyor.

## Current Behavior
Here's what I'm seeing
```bash
Build started
git clone -q https://github.com/DistrictDataLabs/yellowbrick.git C:\projects\yellowbrick
git fetch -q origin +refs/pull/1045/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
IF '%MINICONDA_VERSION%'=='' ( 
    python -m pip install -U pip && 
    python -m pip install -U wheel && 
    python -m pip install -U -r requirements.txt && 
    python -m pip install -U -r tests/requirements.txt 
) ELSE ( 
    conda update -n base conda --yes && 
    conda config --add channels conda-forge && 
    conda config --show-sources && 
    conda env create -f tests/requirements.txt -n yellowbrick && 
    call activate yellowbrick 
)
Solving environment: ...working... done
==> WARNING: A newer version of conda exists. <==
  current version: 4.5.4
  latest version: 4.8.2
Please update conda by running
    $ conda update -n base conda
wheel-0.29.0         |  129 KB | ########## | 100% 
requests-2.14.2      |  703 KB | ########## | 100% 
pycparser-2.19       |   89 KB | ########## | 100% 
chardet-3.0.4        |  201 KB | ########## | 100% 
certifi-2016.2.28    |  214 KB | ########## | 100% 
python-3.6.2         | 31.5 MB | ########## | 100% 
win_inet_pton-1.0.1  |    5 KB | ########## | 100% 
wincertstore-0.2     |   14 KB | ########## | 100% 
pysocks-1.6.6        |   21 KB | ########## | 100% 
pywin32-220          | 12.2 MB | ########## | 100% 
menuinst-1.4.7       |  115 KB | ########## | 100% 
urllib3-1.21.1       |  155 KB | ########## | 100% 
openssl-1.0.2p       |  5.4 MB | ########## | 100% 
setuptools-36.4.0    |  534 KB | ########## | 100% 
pip-9.0.1            |  1.7 MB | ########## | 100% 
idna-2.6             |  123 KB | ########## | 100% 
asn1crypto-0.22.0    |  148 KB | ########## | 100% 
packaging-20.1       |   34 KB | ########## | 100% 
conda-4.3.25         |  527 KB | ########## | 100% 
pyopenssl-17.0.0     |   76 KB | ########## | 100% 
cffi-1.10.0          |  133 KB | ########## | 100% 
six-1.10.0           |   20 KB | ########## | 100% 
cryptography-1.8.1   |  350 KB | ########## | 100% 
pycosat-0.6.2        |   83 KB | ########## | 100% 
ca-certificates-2020 |  165 KB | ########## | 100% 
ruamel_yaml-0.11.14  |  223 KB | ########## | 100% 
pyparsing-2.4.6      |   64 KB | ########## | 100% 
## Package Plan ##
  environment location: C:\Miniconda36-x64
  added / updated specs: 
    - conda
The following packages will be downloaded:
    package                    |            build
    ---------------------------|-----------------
    wheel-0.29.0               |           py36_0         129 KB
    requests-2.14.2            |           py36_0         703 KB
    pycparser-2.19             |             py_0          89 KB
    chardet-3.0.4              |           py36_0         201 KB
    certifi-2016.2.28          |           py36_0         214 KB
    python-3.6.2               |                0        31.5 MB
    win_inet_pton-1.0.1        |           py36_0           5 KB
    wincertstore-0.2           |           py36_0          14 KB
    pysocks-1.6.6              |           py36_0          21 KB
    pywin32-220                |           py36_2        12.2 MB
    menuinst-1.4.7             |           py36_0         115 KB
    urllib3-1.21.1             |           py36_0         155 KB
    openssl-1.0.2p             |       hfa6e2cd_0         5.4 MB
    setuptools-36.4.0          |           py36_1         534 KB
    pip-9.0.1                  |           py36_1         1.7 MB
    idna-2.6                   |           py36_0         123 KB
    asn1crypto-0.22.0          |           py36_0         148 KB
    packaging-20.1             |             py_0          34 KB
    conda-4.3.25               |           py36_0         527 KB
    pyopenssl-17.0.0           |           py36_0          76 KB
    cffi-1.10.0                |           py36_0         133 KB
    six-1.10.0                 |           py36_0          20 KB
    cryptography-1.8.1         |           py36_0         350 KB
    pycosat-0.6.2              |           py36_0          83 KB
    ca-certificates-2020.1.1   |                0         165 KB
    ruamel_yaml-0.11.14        |           py36_1         223 KB
    pyparsing-2.4.6            |             py_0          64 KB
    ------------------------------------------------------------
                                           Total:        54.7 MB
The following NEW packages will be INSTALLED:
    packaging:       20.1-py_0             
    pyparsing:       2.4.6-py_0            
The following packages will be UPDATED:
    ca-certificates: 2018.03.07-0           --> 2020.1.1-0       
    openssl:         1.0.2o-h8ea7d77_0      --> 1.0.2p-hfa6e2cd_0
    pycparser:       2.18-py36hd053e01_1    --> 2.19-py_0        
    wincertstore:    0.2-py36h7fe50ca_0     --> 0.2-py36_0       
The following packages will be DOWNGRADED:
    asn1crypto:      0.24.0-py36_0          --> 0.22.0-py36_0    
    certifi:         2018.4.16-py36_0       --> 2016.2.28-py36_0 
    cffi:            1.11.5-py36h945400d_0  --> 1.10.0-py36_0    
    chardet:         3.0.4-py36h420ce6e_1   --> 3.0.4-py36_0     
    conda:           4.5.4-py36_0           --> 4.3.25-py36_0    
    cryptography:    2.2.2-py36hfa6e2cd_0   --> 1.8.1-py36_0     
    idna:            2.6-py36h148d497_1     --> 2.6-py36_0       
    menuinst:        1.4.14-py36hfa6e2cd_0  --> 1.4.7-py36_0     
    pip:             10.0.1-py36_0          --> 9.0.1-py36_1     
    pycosat:         0.6.3-py36h413d8a4_0   --> 0.6.2-py36_0     
    pyopenssl:       18.0.0-py36_0          --> 17.0.0-py36_0    
    pysocks:         1.6.8-py36_0           --> 1.6.6-py36_0     
    python:          3.6.5-h0c2934d_0       --> 3.6.2-0          
    pywin32:         223-py36hfa6e2cd_1     --> 220-py36_2       
    requests:        2.18.4-py36h4371aae_1  --> 2.14.2-py36_0    
    ruamel_yaml:     0.15.37-py36hfa6e2cd_2 --> 0.11.14-py36_1   
    setuptools:      39.2.0-py36_0          --> 36.4.0-py36_1    
    six:             1.11.0-py36h4db2310_1  --> 1.10.0-py36_0    
    urllib3:         1.22-py36h276f60a_0    --> 1.21.1-py36_0    
    wheel:           0.31.1-py36_0          --> 0.29.0-py36_0    
    win_inet_pton:   1.0.1-py36he67d7fd_1   --> 1.0.1-py36_0     
Downloading and Extracting Packages
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
==> C:\Users\appveyor\.condarc <==
channels:
  - conda-forge
  - defaults
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:
    https://github.com/conda/conda/issues
Current conda install:
               platform : win-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : C:\Miniconda36-x64  (writable)
    default environment : C:\Miniconda36-x64
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\appveyor\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.2 Windows/10 Windows/10.0.14393    
          administrator : True
`$ C:\Miniconda36-x64\Scripts\conda-env-script.py create -f tests/requirements.txt -n yellowbrick`
    Traceback (most recent call last):
      File "C:\Miniconda36-x64\lib\site-packages\conda\exceptions.py", line 640, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\cli\main_create.py", line 78, in execute
        directory=os.getcwd())
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\specs\__init__.py", line 20, in detect
        if spec.can_handle():
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\specs\yaml_file.py", line 14, in can_handle
        self._environment = env.from_file(self.filename)
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\env.py", line 80, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "C:\Miniconda36-x64\lib\site-packages\conda_env\env.py", line 68, in from_yaml
        data = yaml.load(yamlstr)
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\main.py", line 75, in load
        return loader.get_single_data()
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\constructor.py", line 60, in get_single_data
        node = self.get_single_node()
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\composer.py", line 56, in get_single_node
        if not self.check_event(StreamEndEvent):
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\parser.py", line 116, in check_event
        self.current_event = self.state()
      File "C:\Miniconda36-x64\lib\site-packages\ruamel_yaml\parser.py", line 194, in parse_document_start
        self.peek_token().start_mark)
    ruamel_yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
      in "<unicode string>", line 9, column 1:
        pytest>=4.2.0,!=4.6.0
        ^
Command exited with code 1
```

### Steps to Reproduce
Here's the conda recipe we have in our Appveyor test matrix:
```bash
        - PYTHON: "C:\\Miniconda36-x64"
          PYTHON_VERSION: "3.6"
          MINICONDA_VERSION: "4.5.4"
          PYTHON_ARCH: "64"
```
And the install recipe:
```bash
install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - cmd: "IF '%MINICONDA_VERSION%'=='' (
            python -m pip install -U pip &&
            python -m pip install -U wheel &&
            python -m pip install -U -r requirements.txt &&
            python -m pip install -U -r tests/requirements.txt
          ) ELSE (
            conda update -n base conda --yes &&
            conda config --add channels conda-forge &&
            conda config --show-sources &&
            conda env create -f tests/requirements.txt -n yellowbrick &&
            call activate yellowbrick
          )"
```

## Expected Behavior
We haven't changed anything recently with conda or any deps or anything that we can figure would cause the failure to install the requirements. Our test builds looked ok up through the end of last week. Did some digging this but couldn't suss it myself, though it looked like the [yt project](https://github.com/yt-project/yt/pull/2463) might be experiencing something similar? 

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
Current conda install:
               platform : win-64
          conda version : 4.3.25
       conda is private : False
      conda-env version : 4.3.25
    conda-build version : not installed
         python version : 3.6.2.final.0
       requests version : 2.14.2
       root environment : C:\Miniconda36-x64  (writable)
    default environment : C:\Miniconda36-x64
       envs directories : C:\Miniconda36-x64\envs
                          C:\Users\appveyor\AppData\Local\conda\conda\envs
                          C:\Users\appveyor\.conda\envs
          package cache : C:\Miniconda36-x64\pkgs
                          C:\Users\appveyor\AppData\Local\conda\conda\pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\appveyor\.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.25 requests/2.14.2 CPython/3.6.2 Windows/10 Windows/10.0.14393    
          administrator : True

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
==> C:\Users\appveyor\.condarc <==
channels:
  - conda-forge
  - defaults

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
```
</p></details>

It looks like `ruamel_yaml` is getting downgraded from `0.15.37` to `0.11.14`, and then it isn't able to parse our `requirements.txt` file anymore?

Thank you for reading and for your OSS contributions and please let us know if you need any other info or if this is an issue for conda-forge or Appveyor instead! 🙂

**Comment by forrestwaters** [comment]
@rebeccabilbro Thanks for the report and apologies for the unexpected issues. This was a problem that affected older versions of conda only and we have rolled back the changes responsible. Could you please retry your CI system and let us know if you have any further issues?
https://github.com/conda/conda/issues/9715 has a few more details.

**Comment by rebeccabilbro** [comment]
`Build success`!! Thank you very much @forrestwaters & conda team! Closing & marking resolved!
