### ISSUE TITLE
Anaconda does not launch after I tried to install tk

### ISSUE THREAD

**Issue by SkyHopeFashion** [conda/conda#9774]
I tried to install tk on anaconda using the following command. 
conda install -c anaconda tk

Afterwards, I got the following error and my anaconda is not working. 
=================================================
Traceback (most recent call last):
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 168, in main
    activate.main()
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\activate.py", line 174, in main
    from ..install import symlink_conda
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\install.py", line 37, in <module>
    from .core.package_cache import rm_fetched  # NOQA
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\package_cache.py", line 10, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\core\path_actions.py", line 33, in <module>
    from ..gateways.download import download
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\gateways\download.py", line 10, in <module>
    from requests.exceptions import ConnectionError, HTTPError, InvalidSchema, SSLError
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\utils.py", line 24, in <module>
    from . import certs
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\Scripts\conda-script.py", line 5, in <module>
    sys.exit(conda.cli.main())
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main.py", line 176, in main
    return handle_exception(e)
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\cli\main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\conda\connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\__init__.py", line 112, in <module>
    from . import utils
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\utils.py", line 24, in <module>
    from . import certs
  File "C:\Users\abcdefghijk\AppData\Local\Continuum\Anaconda3\lib\site-packages\requests\certs.py", line 15, in <module>
    from certifi import where
ModuleNotFoundError: No module named 'certifi'

**Comment by kalefranz** [comment]
Can't really help without the contents of the `conda-meta/history` file.
