### ISSUE TITLE
anaconda3 on raspberry Pi 4 (4Gb ram) - 'conda list' not working

### ISSUE THREAD

**Issue by Didou09** [conda/conda#9777]
## Current Behavior
Hi, I recently got a raspberry Pi 4, with 4 Gb of memory.
I installed an anaconda distribution on it.
After creating a 'base' conda environment, I activate it and try to list all libraries installed, but conda list does not seem to work.
The error message mentions that Python 3.5 is required, and apparently only Python 3.4 is avbailable for Raspberry Pi 4, but does that mean I can't use conda at all ? Shall I expect the anaconda installation to be corrupt ? Shouln't conda have detected that it cannot be installed on a system with python 3.4 only ?

```
python --version
Python 3.4.3 :: Continuum Analytics, Inc.

which conda
/home/pi/miniconda3/bin/conda

conda --version
conda 3.16.0

conda info --envs
# conda environments:
#
base                     /home/pi/miniconda3/envs/base
root                  *  /home/pi/miniconda3

source activate base
discarding /home/pi/miniconda3/bin from PATH
prepending /home/pi/miniconda3/envs/base/bin to PATH

conda list
# packages in environment at /home/pi/miniconda3/envs/base:
#
Traceback (most recent call last):
  File "/home/pi/miniconda3/envs/base/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_internal/cli/cmdoptions.py", line 28, in <module>
    from pip._internal.models.target_python import TargetPython
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_internal/models/target_python.py", line 4, in <module>
    from pip._internal.utils.misc import normalize_version_info
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_internal/utils/misc.py", line 20, in <module>
    from pip._vendor import pkg_resources
  File "/home/pi/miniconda3/envs/base/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Include the output of the command 'conda info' in your report.


Traceback (most recent call last):
  File "/home/pi/miniconda3/envs/base/bin/conda", line 5, in <module>
    sys.exit(main())
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 194, in main
    args_func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main.py", line 201, in args_func
    args.func(args, p)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 203, in execute
    exitcode = print_packages(prefix, regex, format, piplist=args.pip, json=args.json)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/cli/main_list.py", line 161, in print_packages
    add_pip_installed(prefix, installed, json=json)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/pip.py", line 108, in add_pip_installed
    for pip_pkg in installed(prefix, output=output):
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/pip.py", line 49, in installed
    args = pip_args(prefix)
  File "/home/pi/miniconda3/lib/python3.4/site-packages/conda/pip.py", line 28, in pip_args
    pip_version = subprocess.check_output(ret + ['-V']).decode('utf-8').split()[1]
  File "/home/pi/miniconda3/lib/python3.4/subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['/home/pi/miniconda3/envs/base/bin/python', '/home/pi/miniconda3/envs/base/bin/pip', '-V']' returned non-zero exit status 1
```

**Comment by kalefranz** [comment]
Unfortunately this is issue is for conda 3.16.0, which is around five years old. There's not much we can do at this point.

**Comment by Didou09** [comment]
Ok, thanks for the info,

Any chance to install a newer anaconda / conda on a Raspberry 4 (i.e.: 64 bits) ?

**Comment by kalefranz** [comment]
Looks like the last berryconda was built with conda 4.3.29?
https://github.com/jjhelmus/berryconda
