### ISSUE TITLE
Conda wan't update or do anything

### ISSUE THREAD

**Issue by bizonmwk** [conda/conda#9780]
Hello i installed fresh Miniconda3 but i can;t do anything. Miniconda gets error all times.
I tried to make `conda clean` but it doesn't work.
Example:

I try to : `conda update conda`

Output:
`Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 20, in execute
        install(args, parser, 'update')
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/cli/install.py", line 265, in install
        should_retry_solve=(_should_retry_unfrozen or repodata_fn != repodata_fns[-1]),
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 117, in solve_for_transaction
        should_retry_solve)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 158, in solve_for_diff
        force_remove, should_retry_solve)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 262, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 415, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/solve.py", line 1011, in _prepare
        self.subdirs, prepared_specs, self._repodata_fn)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 228, in get_reduced_index
        repodata_fn=repodata_fn)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 105, in query_all
        result = tuple(concat(executor.map(subdir_query, channel_urls)))
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 598, in result_iterator
        yield fs.pop().result()
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 435, in result
        return self.__get_result()
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
        raise self._exception
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
        result = self.fn(*self.args, **self.kwargs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 98, in <lambda>
        package_ref_or_match_spec))
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 110, in query
        self.load()
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 174, in load
        _internal_state = self._load()
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 248, in _load
        repodata_fn=self.repodata_fn)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/conda/core/subdir_data.py", line 485, in fetch_repodata_remote_request
        timeout=timeout)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 546, in get
        return self.request('GET', url, **kwargs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 533, in request
        resp = self.send(prep, **send_kwargs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/requests/sessions.py", line 646, in send
        r = adapter.send(request, **kwargs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/requests/adapters.py", line 412, in send
        conn = self.get_connection(request.url, proxies)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/requests/adapters.py", line 309, in get_connection
        proxy_manager = self.proxy_manager_for(proxy)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/requests/adapters.py", line 199, in proxy_manager_for
        **proxy_kwargs)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 470, in proxy_from_url
        return ProxyManager(proxy_url=url, **kw)
      File "/mnt/plkra/users/xj9xcc/miniconda3/lib/python3.7/site-packages/urllib3/poolmanager.py", line 420, in __init__
        raise ProxySchemeUnknown(proxy.scheme)
    urllib3.exceptions.ProxySchemeUnknown: Not supported proxy scheme None

`$ /mnt/plkra/users/xj9xcc/miniconda3/bin/conda update conda`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/mnt/plkra/users/xj9xcc/miniconda3/bin/conda
             CONDA_PREFIX=/mnt/plkra/users/xj9xcc/miniconda3
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/mnt/plkra/users/xj9xcc/miniconda3/bin/python
               CONDA_ROOT=/mnt/plkra/users/xj9xcc/miniconda3
              CONDA_SHLVL=1
               MODULEPATH=/cm/local/modulefiles:/cm/shared/modulefiles
                     PATH=/mnt/plkra/users/xj9xcc/miniconda3/bin:/mnt/plkra/users/xj9xcc/minicon
                          da3/bin:/mnt/plkra/users/xj9xcc/miniconda3/condabin:/usr/local/bin:/bi
                          n:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/sbin:/usr/sbin:/mnt/plkra/
                          users/xj9xcc/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
                ftp_proxy=<set>
               http_proxy=<set>
              https_proxy=<set>

     active environment : base
    active env location : /mnt/plkra/users/xj9xcc/miniconda3
            shell level : 1
       user config file : /mnt/plkra/users/xj9xcc/.condarc
 populated config files :
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.12
       base environment : /mnt/plkra/users/xj9xcc/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /mnt/plkra/users/xj9xcc/miniconda3/pkgs
                          /mnt/plkra/users/xj9xcc/.conda/pkgs
       envs directories : /mnt/plkra/users/xj9xcc/miniconda3/envs
                          /mnt/plkra/users/xj9xcc/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.6 Linux/2.6.32-696.el6.x86_64 centos/6.9 glibc/2.12
                UID:GID : 644831:513
             netrc file : None
           offline mode : False
`

**Comment by chloecwy** [comment]
I'm having the same issue, except that my conda does not return any output at all. Hoping someone that would rectify this issue.

**Comment by kalefranz** [comment]
Please provide the output of `conda config --show-sources`

**Comment by bizonmwk** [comment]
There is no output from this command. Nothing happens

**Comment by nikolasbasler** [comment]
I am having the same issue. Any news? It appeared after a `conda update`. `conda config --show-sources` doesn't produce any output for me either. Just a blank line.
