### ISSUE TITLE
Conda fails to create some envs when installed on /opt/conda

### ISSUE THREAD

**Issue by marcelotrevisani** [conda/conda#9790]
## Current Behavior
Failing to create an environment when conda is installed in ``/opt/conda``

### Steps to Reproduce
Conda is installed on ``/opt/conda`` and it seems to be something related to it 

```
wget -q -O miniconda.sh http://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash miniconda.sh -b -p /opt/conda
source /opt/conda/bin/activate
conda update -y conda
conda config --add channels conda-forge
conda init

conda create -n  tfc5 pytest pytest-json-report pytest-replay
```

## Result
```
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/tfc5

  added / updated specs:
    - pytest
    - pytest-json-report
    - pytest-replay


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-0_gnu
  attrs              conda-forge/noarch::attrs-19.3.0-py_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.11.28-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.11.28-py38h32f6830_1
  importlib-metadata conda-forge/linux-64::importlib-metadata-1.5.2-py38h32f6830_0
  importlib_metadata conda-forge/noarch::importlib_metadata-1.5.2-0
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.34-h53a641e_0
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1007
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.2.0-h24d8f2e_2
  libgomp            conda-forge/linux-64::libgomp-9.2.0-h24d8f2e_2
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.2.0-hdf63c60_2
  more-itertools     conda-forge/noarch::more-itertools-8.2.0-py_0
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  openssl            conda-forge/linux-64::openssl-1.1.1e-h516909a_0
  packaging          conda-forge/noarch::packaging-20.1-py_0
  pip                conda-forge/noarch::pip-20.0.2-py_2
  pluggy             conda-forge/linux-64::pluggy-0.13.1-py38_0
  py                 conda-forge/noarch::py-1.8.1-py_0
  pyparsing          conda-forge/noarch::pyparsing-2.4.6-py_0
  pytest             conda-forge/linux-64::pytest-5.4.1-py38h32f6830_0
  pytest-json-report conda-forge/noarch::pytest-json-report-1.2.1-pyh9f0ad1d_0
  pytest-metadata    conda-forge/noarch::pytest-metadata-1.8.0-py_0
  pytest-replay      conda-forge/noarch::pytest-replay-1.2.0-py_0
  python             conda-forge/linux-64::python-3.8.2-h8356626_5_cpython
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0
  setuptools         conda-forge/linux-64::setuptools-46.1.3-py38h32f6830_0
  six                conda-forge/noarch::six-1.14.0-py_1
  sqlite             conda-forge/linux-64::sqlite-3.30.1-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.10-hed695b0_0
  wcwidth            conda-forge/noarch::wcwidth-0.1.9-pyh9f0ad1d_0
  wheel              conda-forge/noarch::wheel-0.34.2-py_1
  xz                 conda-forge/linux-64::xz-5.2.4-h516909a_1002
  zipp               conda-forge/noarch::zipp-3.1.0-py_0
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1006


Proceed ([y]/n)? y

Preparing transaction: failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/opt/conda/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/main_create.py", line 37, in execute
        install(args, parser, 'create')
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 317, in install
        handle_txn(unlink_link_transaction, prefix, args, newenv)
      File "/opt/conda/lib/python3.7/site-packages/conda/cli/install.py", line 346, in handle_txn
        unlink_link_transaction.execute()
      File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 244, in execute
        self.verify()
      File "/opt/conda/lib/python3.7/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 221, in verify
        self.prepare()
      File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 213, in prepare
        stp.neutered_specs)
      File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 288, in _prepare
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/opt/conda/lib/python3.7/site-packages/conda/core/link.py", line 288, in <genexpr>
        for prec, pcrec in zip(link_precs, pkg_cache_recs_to_link))
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 99, in read_package_info
        package_metadata = read_package_metadata(epd)
      File "/opt/conda/lib/python3.7/site-packages/conda/gateways/disk/read.py", line 154, in read_package_metadata
        data = json.loads(f.read())
      File "/opt/conda/lib/python3.7/json/__init__.py", line 348, in loads
        return _default_decoder.decode(s)
      File "/opt/conda/lib/python3.7/json/decoder.py", line 337, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/opt/conda/lib/python3.7/json/decoder.py", line 355, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`$ /opt/conda/bin/conda create -n tfc5 pytest pytest-json-report pytest-replay`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=base
                CONDA_EXE=/opt/conda/bin/conda
             CONDA_PREFIX=/opt/conda
    CONDA_PROMPT_MODIFIER=(base)
         CONDA_PYTHON_EXE=/opt/conda/bin/python
               CONDA_ROOT=/opt/conda
              CONDA_SHLVL=1
                     PATH=/opt/conda/bin:/opt/conda/bin:/opt/conda/bin:/opt/conda/condabin:/usr/
                          local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/us
                          r/local/games
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/conda  (writable)
           channel URLs : http://vision-executor-01.hh.imgtec.org/conda/linux-64
                          http://vision-executor-01.hh.imgtec.org/conda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-55-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

```

## Expected Behavior
Create the environment properly

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /opt/conda  (writable)
           channel URLs : http://vision-executor-01.hh.imgtec.org/conda/linux-64
                          http://vision-executor-01.hh.imgtec.org/conda/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-55-generic ubuntu/18.04.4 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
conda config --show-sources
==> /root/.condarc <==
channels:
  - conda-forge
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       0_gnu    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cffi                      1.14.0           py37hd463f26_0    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
conda                     4.8.3            py37hc8dfbb8_1    conda-forge
conda-package-handling    1.6.0            py37h8f50634_2    conda-forge
cryptography              2.8              py37hb09aad4_2    conda-forge
idna                      2.9                        py_1    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1e               h516909a_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pycosat                   0.6.3           py37h8f50634_1004    conda-forge
pycparser                 2.20                       py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
python                    3.7.6                h0371630_2    defaults
python_abi                3.7                     1_cp37m    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
ruamel_yaml               0.15.80         py37h8f50634_1001    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.31.1               h7b6447c_0    defaults
tk                        8.6.10               hed695b0_0    conda-forge
tqdm                      4.43.0                     py_0    conda-forge
urllib3                   1.25.7           py37hc8dfbb8_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.4             h516909a_1002    conda-forge
yaml                      0.2.2                h516909a_1    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge

```
</p></details>

**Comment by kalefranz** [comment]
I guess one of those packages has a corrupt json file in the `info/` directory?
