### ISSUE TITLE
"ascii" codec cannot decode a byte

### ISSUE THREAD

**Issue by timonoko** [conda/conda#9792]
$ conda create –-name synsin_env –-file requirements.txt -p /home/tnoko/synsin

Traceback (most recent call last):
  File "/home/tnoko/.local/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home/tnoko/.local/lib/python2.7/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home/tnoko/.local/lib/python2.7/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home/tnoko/.local/lib/python2.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home/tnoko/.local/lib/python2.7/site-packages/conda/exceptions.py", line 575, in print_unexpected_error_message
    command = ' '.join(sys.argv)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by kalefranz** [comment]
Did you `pip install conda`? Please _do_ answer the questions in the issue template. They’re especially important here.

**Comment by timonoko** [comment]
"pip install conda" did not work for some totally uncomprehensible reason and it suggested  "miniconda" from some website. I have alrady forgotten most of the details.
