### ISSUE TITLE
url as channel name breaks splitting channel_subdir_str by slash

### ISSUE THREAD

**Issue by croth1** [conda/conda#9814]
https://github.com/conda/conda/blob/125413caa9384ae5e9e3e2dfcb4616ec33b7aadb/conda/models/match_spec.py#L186

I have a weird issue where `channel_subdir_str` is an url instead of a simple channel name (https://repo.continuum.io/pkgs/main/osx-64). The split then fails with

```
Traceback (most recent call last):
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/cli/conda_argparse.py", line 82, in do_call
        return getattr(module, func_name)(args, parser)
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/cli/install.py", line 250, in install
        index)
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 289, in revert_actions
        target_state = {MatchSpec.from_dist_str(dist_str) for dist_str in h.get_state(revision)}
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/plan.py", line 289, in <setcomp>
        target_state = {MatchSpec.from_dist_str(dist_str) for dist_str in h.get_state(revision)}
      File "/Users/christian/miniconda3/lib/python3.6/site-packages/conda/models/match_spec.py", line 186, in from_dist_str
        channel_str, subdir = channel_subdir_str.split('/', 2)
    ValueError: too many values to unpack (expected 2)
```

**Comment by kalefranz** [comment]
Steps to reproduce the issue? Also the output of `conda info`, `conda config --show-sources`, and `conda list --show-channel-urls`?

**Comment by croth1** [comment]
I do not understand the problem enough to give a reproducible example from the scratch, but I will collect some hints - maybe it helps you or others to figure out what's going on.

I got the problem during trying to revert a conda environment with `conda install --revision 103`


The revision contains a a full url as channel, which *may*  be the origin of the problem. 
```
2019-11-22 09:29:42  (rev 103)
     get_terminal_size  {1.0.0 (https://repo.continuum.io/pkgs/main/osx-64) -> 1.0.0}
    -importlib_metadata-0.23 (conda-forge)
```

<details><summary>conda info</summary>

```
     active environment : base
    active env location : /Users/christian/miniconda3
            shell level : 3
       user config file : /Users/christian/.condarc
 populated config files : /Users/christian/.condarc
          conda version : 4.8.3
    conda-build version : 3.19.2
         python version : 3.6.10.final.0
       virtual packages : __osx=10.15.4
       base environment : /Users/christian/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/osx-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/christian/miniconda3/pkgs
                          /Users/christian/.conda/pkgs
       envs directories : /Users/christian/miniconda3/envs
                          /Users/christian/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.6.10 Darwin/19.4.0 OSX/10.15.4
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>
<details><summary>conda config --show-sources</summary>

```
==> /Users/christian/.condarc <==
allow_conda_downgrades: True
ssl_verify: True
channel_priority: strict
channels:
  - conda-forge
  - bioconda
  - defaults
show_channel_urls: False
```
</details>
<details><summary>conda list --show-channel-urls</summary>

```
# packages in environment at /Users/christian/miniconda3/envs/sci36:
#
# Name                    Version                   Build  Channel
_anaconda_depends         5.1.0                    py36_2    defaults
alabaster                 0.7.12                     py_0    conda-forge
amqp                      2.5.2                      py_0    conda-forge
anaconda                  custom                   py36_1    defaults
anaconda-client           1.7.2                      py_0    conda-forge
anaconda-navigator        1.9.7                    py36_1    defaults
anaconda-project          0.8.3                      py_0    conda-forge
appnope                   0.1.0                 py36_1000    conda-forge
appscript                 1.1.0            py36h0b31af3_0    conda-forge
arrow-cpp                 0.15.1           py36h244f18e_5    conda-forge
asgiref                   3.2.3                      py_0    conda-forge
asn1crypto                1.2.0                    py36_0    conda-forge
astroid                   2.3.3                    py36_0    conda-forge
astropy                   4.0              py36h0b31af3_0    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
beautifulsoup4            4.8.1                    py36_0    conda-forge
billiard                  3.6.0.0          py36h0b31af3_0    conda-forge
biopython                 1.75             py36h0b31af3_0    conda-forge
bitarray                  1.1.0            py36h0b31af3_0    conda-forge
bkcharts                  0.2                      py36_0    conda-forge
blas                      2.14                        mkl    conda-forge
blaze                     0.11.3                   py36_0    conda-forge
blosc                     1.17.0               h6de7cb9_1    conda-forge
bokeh                     1.4.0                    py36_0    conda-forge
boost-cpp                 1.70.0               h75728bb_2    conda-forge
boto                      2.49.0                     py_0    conda-forge
bottleneck                1.3.1            py36h3b54f70_0    conda-forge
brotli                    1.0.7             h6de7cb9_1000    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
c-ares                    1.15.0            h01d97ff_1001    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
celery                    4.4.0rc1                   py_0    conda-forge
certifi                   2019.11.28               py36_0    conda-forge
cffi                      1.13.2           py36h33e799b_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
clang                     8.0.1                h770b8ee_1    conda-forge
clang-tools               8.0.1                h770b8ee_1    conda-forge
clangdev                  8.0.1                h770b8ee_1    conda-forge
clangxx                   8.0.1                         1    conda-forge
click                     7.0                        py_0    conda-forge
cloud_sptheme             1.10.0                     py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
clyent                    1.2.2                      py_1    conda-forge
colorama                  0.4.3                      py_0    conda-forge
commonmark                0.9.1                      py_0    conda-forge
contextlib2               0.6.0.post1                py_0    conda-forge
coverage                  4.5.4            py36h0b31af3_0    conda-forge
cryptography              2.8              py36hafa8578_1    conda-forge
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.14          py36h4a8c4bd_0    conda-forge
cytoolz                   0.10.1           py36h0b31af3_0    conda-forge
dask                      2.9.0                      py_0    conda-forge
dask-core                 2.9.0                      py_0    conda-forge
dataclasses               0.7                      py36_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
dbus                      1.13.6               h2f22bb5_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
distributed               2.9.0                      py_0    conda-forge
django                    3.0.1                    py36_0    conda-forge
django-fsm                2.7.0                      py_0    conda-forge
djangorestframework       3.11.0                     py_0    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
double-conversion         3.1.5                h4a8c4bd_2    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.5             h4a8c4bd_1004    conda-forge
fastcache                 1.1.0            py36h0b31af3_0    conda-forge
feather-format            0.4.0                   py_1003    conda-forge
filelock                  3.0.10                     py_0    conda-forge
flake8                    3.7.9                    py36_0    conda-forge
flask                     1.1.1                      py_1    conda-forge
flask-cors                3.0.8                      py_0    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
fsspec                    0.6.2                      py_0    conda-forge
get_terminal_size         1.0.0                h7520d66_0    defaults
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gevent                    1.4.0            py36h0b31af3_0    conda-forge
gflags                    2.2.2             h4a8c4bd_1002    conda-forge
glib                      2.58.3          py36h577aef8_1002    conda-forge
glob2                     0.7                        py_0    conda-forge
glog                      0.4.0                h6de7cb9_1    conda-forge
gmp                       6.1.2             h0a44026_1000    conda-forge
gmpy2                     2.1.0b1          py36h4160ff4_0    conda-forge
greenlet                  0.4.15           py36h0b31af3_0    conda-forge
grpc-cpp                  1.25.0               h00d9e76_2    conda-forge
h5py                      2.10.0          nompi_py36h106b333_101    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
hypothesis                4.55.4                   py36_0    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.6.1                    py36_0    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        1.3.0                    py36_0    conda-forge
intel-openmp              2019.4                      233    defaults
ipykernel                 5.1.3            py36h5ca1d4c_0    conda-forge
ipython                   7.10.2           py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.5.1                      py_0    conda-forge
isort                     4.3.21                   py36_0    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jbig                      2.1               h1de35cc_2001    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jinja2                    2.10.3                     py_0    conda-forge
joblib                    0.14.1                     py_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.2.0                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.3.3                    py36_1    conda-forge
jupyter_console           5.1.0                    py36_0    conda-forge
jupyter_core              4.6.1                    py36_0    conda-forge
jupyterlab                1.2.4                      py_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
keyring                   20.0.0                   py36_0    conda-forge
kiwisolver                1.1.0            py36ha1b3eb9_0    conda-forge
kombu                     4.6.7                    py36_1    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
latexcodec                1.0.7                      py_0    conda-forge
lazy-object-proxy         1.4.3            py36h0b31af3_0    conda-forge
libblas                   3.8.0                    14_mkl    conda-forge
libcblas                  3.8.0                    14_mkl    conda-forge
libclang                  8.0.1                h770b8ee_1    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.0                h89e68fa_1    conda-forge
libcxxabi                 4.0.1                hcfea43d_1    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libevent                  2.1.10               hafa8578_0    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
liblapack                 3.8.0                    14_mkl    conda-forge
liblapacke                3.8.0                    14_mkl    conda-forge
libllvm8                  8.0.1                h770b8ee_0    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libprotobuf               3.11.0               hd174df1_0    conda-forge
libsodium                 1.0.17               h01d97ff_0    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                ha78913b_1    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
libxslt                   1.1.33               h320ff13_0    conda-forge
llvm-openmp               8.0.1                h770b8ee_0    conda-forge
llvm-tools                8.0.1                         0    conda-forge
llvmdev                   8.0.1                h770b8ee_0    conda-forge
llvmlite                  0.30.0           py36h05045ef_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.4.2            py36he54a443_0    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
lzo                       2.10              h1de35cc_1000    conda-forge
markupsafe                1.1.1            py36h0b31af3_0    conda-forge
matplotlib                3.1.2                    py36_1    conda-forge
matplotlib-base           3.1.2            py36h11da6c2_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36h0b31af3_1000    conda-forge
mkl                       2019.4                      233    defaults
mkl-service               2.3.0            py36h0b31af3_0    conda-forge
mock                      3.0.5                    py36_0    conda-forge
more-itertools            8.0.2                      py_0    conda-forge
mpc                       1.1.0             h4160ff4_1006    conda-forge
mpfr                      4.0.2                h44b798e_0    conda-forge
mpmath                    1.1.0                      py_0    conda-forge
msgpack-python            0.6.2            py36ha1b3eb9_0    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
nb_conda_kernels          2.2.2                    py36_0    conda-forge
nbconvert                 5.6.1                    py36_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nltk                      3.4.4                      py_0    conda-forge
nose                      1.3.7                 py36_1003    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
nspr                      4.20              h0a44026_1000    conda-forge
nss                       3.47                 hcec2283_0    conda-forge
numba                     0.46.0           py36h4f17bb1_1    conda-forge
numexpr                   2.7.0            py36h4f17bb1_0    conda-forge
numpy                     1.17.3           py36hde6bac1_0    conda-forge
numpydoc                  0.9.1                      py_0    conda-forge
odo                       0.5.1                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openmp                    8.0.1                         0    conda-forge
openpyxl                  3.0.1                      py_0    conda-forge
openssl                   1.1.1d               h0b31af3_0    conda-forge
oset                      0.1.3                      py_1    conda-forge
packaging                 19.2                       py_0    conda-forge
pandas                    0.25.3           py36h4f17bb1_0    conda-forge
pandoc                    2.9                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.5.2                      py_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
path                      13.1.0                   py36_0    conda-forge
path.py                   12.4.0                        0    conda-forge
pathlib2                  2.3.5                    py36_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.43                 h4a8c4bd_0    conda-forge
pep8                      1.7.1                      py_0    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    6.2.1            py36h43b43f3_1    conda-forge
pip                       19.3.1                   py36_0    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
plotly                    4.4.1                      py_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
ply                       3.11                       py_1    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            3.0.2                      py_0    conda-forge
psutil                    5.6.7            py36h0b31af3_0    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyarrow                   0.15.1           py36hdca360a_1    conda-forge
pybtex                    0.22.2                   py36_0    conda-forge
pybtex-docutils           0.2.2                    py36_0    conda-forge
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py36h0b31af3_1002    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pycrypto                  2.6.1           py36h0b31af3_1003    conda-forge
pycurl                    7.43.0.3         py36h75a5311_1    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.5.2                      py_0    conda-forge
pylint                    2.4.4                    py36_0    conda-forge
pyodbc                    4.0.27           py36h4a8c4bd_0    conda-forge
pyopenssl                 19.1.0                   py36_0    conda-forge
pyparsing                 2.4.5                      py_0    conda-forge
pyqt                      5.12.3           py36he22c54c_1    conda-forge
pyrsistent                0.15.6           py36h0b31af3_0    conda-forge
pysocks                   1.7.1                    py36_0    conda-forge
pytables                  3.6.1            py36h6f8395a_0    conda-forge
pytest                    5.3.2                    py36_0    conda-forge
pytest-arraydiff          0.3                        py_0    conda-forge
pytest-astropy            0.7.0                      py_0    conda-forge
pytest-astropy-header     0.1.2                      py_0    conda-forge
pytest-doctestplus        0.4.0                      py_0    conda-forge
pytest-openfiles          0.4.0                      py_0    conda-forge
pytest-remotedata         0.3.1                      py_0    conda-forge
python                    3.6.7             h4285619_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-levenshtein        0.12.0          py36h0b31af3_1001    conda-forge
python.app                1.2             py36h0b31af3_1201    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py36h3b54f70_0    conda-forge
pyyaml                    5.2              py36h0b31af3_0    conda-forge
pyzmq                     18.1.1           py36h4bf09a9_0    conda-forge
qt                        5.12.5               h1b46049_0    conda-forge
qtawesome                 0.6.0                      py_0    conda-forge
qtconsole                 4.6.0                      py_0    conda-forge
qtpy                      1.9.0                      py_0    conda-forge
re2                       2019.12.01           h4a8c4bd_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
recommonmark              0.6.0                      py_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rope                      0.14.0                     py_0    conda-forge
ruamel.yaml               0.16.5           py36h0b31af3_1    conda-forge
ruamel.yaml.clib          0.2.0            py36h0b31af3_0    conda-forge
ruamel_yaml               0.15.80         py36h0b31af3_1000    conda-forge
scikit-image              0.16.2           py36h4f17bb1_0    conda-forge
scikit-learn              0.21.3           py36hd4ffd6c_0    conda-forge
scipy                     1.4.0            py36h82752d6_0    conda-forge
seaborn                   0.9.0                      py_2    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                42.0.2                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3               py36_1000    conda-forge
sip                       4.19.18          py36h4a8c4bd_1    conda-forge
six                       1.13.0                   py36_0    conda-forge
snappy                    1.1.7             h6de7cb9_1002    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
sortedcollections         1.1.2                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.4                    py36_0    conda-forge
sphinx                    2.3.0                      py_0    conda-forge
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib             1.0                      py36_1    defaults
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-bibtex      1.0.0                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-fulltoc     1.2.0                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.3                      py_0    conda-forge
sphinxcontrib-websupport  1.1.2                      py_0    conda-forge
spyder                    3.3.6                    py36_1    conda-forge
spyder-kernels            0.5.2                    py36_0    conda-forge
sqlalchemy                1.3.12           py36h0b31af3_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
sqlparse                  0.3.0                      py_0    conda-forge
statsmodels               0.10.2           py36h3b54f70_0    conda-forge
sympy                     1.5                      py36_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
terminado                 0.8.3                    py36_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thrift-cpp                0.12.0            h874095a_1004    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py36h0b31af3_0    conda-forge
tox                       2.8.1                    py36_0    conda-forge
traitlets                 4.3.3                    py36_0    conda-forge
typed-ast                 1.4.0            py36h0b31af3_0    conda-forge
typing                    3.6.4                    py36_0    conda-forge
unicodecsv                0.14.1                     py_1    conda-forge
unixodbc                  2.3.7             hea208f4_1000    conda-forge
uriparser                 0.9.3                h6de7cb9_1    conda-forge
urllib3                   1.25.7                   py36_0    conda-forge
vine                      1.3.0                      py_0    conda-forge
virtualenv                16.7.5                     py_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.16.0                     py_0    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
widgetsnbextension        3.5.1                    py36_0    conda-forge
wrapt                     1.11.2           py36h0b31af3_0    conda-forge
wurlitzer                 1.0.3                    py36_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.6                      py_0    conda-forge
xlwings                   0.16.4                   py36_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yaml                      0.2.2                h0b31af3_1    conda-forge
zeromq                    4.3.2                h6de7cb9_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                he7fca8b_1    conda-forge
```
</details>

Unfortunately, this environment is currently completely broken:
-  conda reports inconsistencies
- conda revert fails due to missing packages, or this crash
-  any conda update or install command  (including 
`conda update --all`) leads to solver failure and never ending conflict analysis.

Do you have any pointers what else to try to get it back alive again?

**Comment by kalefranz** [comment]
Since we're now dealing with the history file (i.e. `conda install --revision`), can you also provide the contents of `/Users/christian/miniconda3/conda-meta/history`? It will be long; that's ok.

It's my guess that `allow_conda_downgrades: True` created a problem somewhere along the way with that history file, but I'd still like to understand how you got to this place.

**Comment by croth1** [comment]
👍  I added the history to the previous post.

**Comment by kalefranz** [comment]
The history file you provided was actually incredibly interesting and useful, although not for the top-line issue of this ticket, which is `ValueError: too many values to unpack (expected 2)`.

The stack trace that you're running into is just a flat-out coding error introduced at 

https://github.com/conda/conda/pull/9418/files#diff-39ec17febc24e90aa82fc8390d50ec87R186

I guess that line didn't end up with test coverage.  Needs to be changed to

```
channel_str, subdir = channel_subdir_str.split('/', 1)
```

In your second comment you raised some separate issues

> * conda reports inconsistencies
> * any conda update or install command (including conda update --all) leads to solver failure and never ending conflict analysis.

that need to be addressed as well, but I'm guessing are also pretty extensively discussed in other tickets.
