### ISSUE TITLE
OSError: [Errno 40] Message too long

### ISSUE THREAD

**Issue by patrickfuller** [conda/conda#986]
Trying to add an OSX version of [openbabel](https://binstar.org/patrickfuller/openbabel). Appears to build fine, but I get this error message on upload:

```
▶ binstar upload /Users/pat/miniconda3/conda-bld/osx-64/openbabel--py34_0.tar.bz2
Using binstar api site https://api.binstar.org
detecting package type ...
conda
extracting package attributes for upload ...
done
[NotFound] Not Found: Nothing matches the given URI ([POST] https://api.binstar.org/release/patrickfuller/openbabel/ -> 404)
--- Logging error ---
Traceback (most recent call last):
  File "/Users/pat/miniconda3/lib/python3.4/logging/handlers.py", line 899, in emit
    self.socket.send(msg)
OSError: [Errno 40] Message too long

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pat/miniconda3/lib/python3.4/logging/handlers.py", line 903, in emit
    self.socket.send(msg)
OSError: [Errno 40] Message too long
Call stack:
  File "/Users/pat/miniconda3/lib/python3.4/site-packages/clyent/logs/__init__.py", line 13, in excepthook
    logger.error('', exc_info=exc_info)
Message: ''
Arguments: ()
```

**Comment by csoja** [comment]
If this is still an issue - should be opened in the anaconda-client repo (formally the binstar-client repository). https://github.com/Anaconda-Server/anaconda-client/issues
