### ISSUE TITLE
Permission errors installing mini-conda

### ISSUE THREAD

**Issue by msingh00** [conda/conda#9881]
## Current Behavior
Download Miniconda3 4.8.2 (64-bit) installer.  
Install for: Just me (as i don't have permission to run elevated)
Destination folder: C:\test\Miniconda3 (as my user path has spaces in it and the installer warns against spaces)
Other options: use defaults

After installation completes, i am unable to run conda, nor do i see any Ananconda command shortcut from Windows-Start menu.
During installation i see the following errors:
....
Extract: conda-4.8.2-py37_0.tar.bz2
                                      [16908] Failed to execute script entry_point
Traceback (most recent call last):
  File "entry_point.py", line 69, in <module>
  File "concurrent\futures\process.py", line 671, in map
  File "concurrent\futures\_base.py", line 587, in map
  File "concurrent\futures\_base.py", line 587, in <listcomp>
  File "concurrent\futures\process.py", line 641, in submit
  File "concurrent\futures\process.py", line 583, in _start_queue_management_thread
  File "concurrent\futures\process.py", line 607, in _adjust_process_count
  File "multiprocessing\process.py", line 112, in start
  File "multiprocessing\context.py", line 322, in _Popen
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 82, in __init__
  File "multiprocessing\popen_spawn_win32.py", line 89, in __init__
  File "multiprocessing\reduction.py", line 60, in dump
  File "multiprocessing\connection.py", line 948, in reduce_pipe_connection
  File "multiprocessing\reduction.py", line 107, in __init__
PermissionError: [WinError 5] Access is denied
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00000248 (most recent call first):
Collecting package metadata (current_repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - cffi==1.14.0=py37h7a1dbc1_0
  - conda==4.8.2=py37_0
  - chardet==3.0.4=py37_1003
  - pycparser==2.19=py37_0
  - yaml==0.1.7=hc54c509_2
  - asn1crypto==1.3.0=py37_0
  - ruamel_yaml==0.15.87=py37he774522_0
  - python==3.7.6=h60c2a47_2
  - six==1.14.0=py37_0
  - cryptography==2.8=py37h7a1dbc1_0
  - setuptools==45.2.0=py37_0
  - pycosat==0.6.3=py37he774522_0
  - pyopenssl==19.1.0=py37_0
  - pip==20.0.2=py37_1
  - wincertstore==0.2=py37_0
  - menuinst==1.4.16=py37he774522_0
  - powershell_shortcut==0.0.1=3
  - sqlite==3.31.1=he774522_0
  - wheel==0.34.2=py37_0
  - urllib3==1.25.8=py37_0
  - vs2015_runtime==14.16.27012=hf0eaf9b_1
  - openssl==1.1.1d=he774522_4
  - ca-certificates==2020.1.1=0
  - conda-package-handling==1.6.0=py37h62dcd97_0
  - idna==2.8=py37_0
  - certifi==2019.11.28=py37_0
  - pywin32==227=py37he774522_1
  - tqdm==4.42.1=py_0
  - vc==14.1=h0510ff6_4
  - requests==2.22.0=py37_1
  - pysocks==1.7.1=py37_0
  - win_inet_pton==1.1.0=py37_0
  - console_shortcut==0.1.1=4

### Steps to Reproduce

Download Miniconda3 4.8.2 (64-bit) installer.  Run with following options/changes to default:
Install for: Just me (as i don't have permission to run elevated)
Destination folder: C:\test\Miniconda3 (as my user path has spaces in it and the installer warns against spaces)
Other options: use defaults

## Expected Behavior

I expect it to install properly?

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>
Windows 10 x64

**Comment by dizzy0ny** [comment]
Right...shouldn't that have been installed with this installer?
