### ISSUE TITLE
ModuleNotFoundError: No module named 'conda' after update

### ISSUE THREAD

**Issue by trilbytim** [conda/conda#9907]
This seems to be a re-run of #2463 
I tried to update Python and it has resulted in conda crippling itself. Looking back through this, I now see that it did prompt me to update conda but I didn't notice and carried on to try to update Python first (I wandered off while it was "Solving environment", when I came back the warning had scrolled off the top of the screen so I just pressed y).
Now conda is dead I can't update it.

```
mt1tjs@mt1tjs-Precision-M4600:~$ conda update python

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/mt1tjs/anaconda3

  added / updated specs: 
    - python


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    openssl-1.1.1g             |       h7b6447c_0         3.8 MB
    certifi-2020.4.5.1         |           py38_0         159 KB
    libgcc-ng-9.1.0            |       hdf63c60_0         8.1 MB
    zlib-1.2.11                |       h7b6447c_3         120 KB
    python-3.8.2               |       hcf32534_0        57.8 MB
    libedit-3.1.20181209       |       hc058e9b_0         188 KB
    pip-20.0.2                 |           py38_1         1.9 MB
    wheel-0.34.2               |           py38_0          49 KB
    sqlite-3.31.1              |       h62c20be_1         2.0 MB
    ncurses-6.2                |       he6710b0_1         1.1 MB
    _libgcc_mutex-0.1          |             main           3 KB
    setuptools-46.1.3          |           py38_0         656 KB
    xz-5.2.5                   |       h7b6447c_0         438 KB
    ca-certificates-2020.1.1   |                0         132 KB
    ld_impl_linux-64-2.33.1    |       h53a641e_7         645 KB
    readline-8.0               |       h7b6447c_0         428 KB
    ------------------------------------------------------------
                                           Total:        77.4 MB

The following NEW packages will be INSTALLED:

    _libgcc_mutex:    0.1-main               
    ld_impl_linux-64: 2.33.1-h53a641e_7      

The following packages will be UPDATED:

    ca-certificates:  2018.03.07-0            --> 2020.1.1-0             
    certifi:          2018.8.24-py37_1        --> 2020.4.5.1-py38_0      
    libedit:          3.1.20170329-h6b74fdf_2 --> 3.1.20181209-hc058e9b_0
    libgcc-ng:        8.2.0-hdf63c60_1        --> 9.1.0-hdf63c60_0       
    ncurses:          6.1-hf484d3e_0          --> 6.2-he6710b0_1         
    openssl:          1.0.2p-h14c3975_0       --> 1.1.1g-h7b6447c_0      
    pip:              10.0.1-py37_0           --> 20.0.2-py38_1          
    python:           3.7.0-hc3d631a_0        --> 3.8.2-hcf32534_0       
    readline:         7.0-h7b6447c_5          --> 8.0-h7b6447c_0         
    setuptools:       40.2.0-py37_0           --> 46.1.3-py38_0          
    sqlite:           3.24.0-h84994c4_0       --> 3.31.1-h62c20be_1      
    wheel:            0.31.1-py37_0           --> 0.34.2-py38_0          
    xz:               5.2.4-h14c3975_4        --> 5.2.5-h7b6447c_0       
    zlib:             1.2.11-ha838bed_2       --> 1.2.11-h7b6447c_3      

Proceed ([y]/n)? y


Downloading and Extracting Packages
openssl-1.1.1g       | 3.8 MB    | ##################################### | 100% 
certifi-2020.4.5.1   | 159 KB    | ##################################### | 100% 
libgcc-ng-9.1.0      | 8.1 MB    | ##################################### | 100% 
zlib-1.2.11          | 120 KB    | ##################################### | 100% 
python-3.8.2         | 57.8 MB   | ##################################### | 100% 
libedit-3.1.20181209 | 188 KB    | ##################################### | 100% 
pip-20.0.2           | 1.9 MB    | ##################################### | 100% 
wheel-0.34.2         | 49 KB     | ##################################### | 100% 
sqlite-3.31.1        | 2.0 MB    | ##################################### | 100% 
ncurses-6.2          | 1.1 MB    | ##################################### | 100% 
_libgcc_mutex-0.1    | 3 KB      | ##################################### | 100% 
setuptools-46.1.3    | 656 KB    | ##################################### | 100% 
xz-5.2.5             | 438 KB    | ##################################### | 100% 
ca-certificates-2020 | 132 KB    | ##################################### | 100% 
ld_impl_linux-64-2.3 | 645 KB    | ##################################### | 100% 
readline-8.0         | 428 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
Traceback (most recent call last):
  File "/home/mt1tjs/anaconda3/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
mt1tjs@mt1tjs-Precision-M4600:~$ conda update -n base -c defaults conda
Traceback (most recent call last):
  File "/home/mt1tjs/anaconda3/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

`

**Comment by IgorKasianenko** [comment]
Did you find the way to fix it? :)
I am having same issue with conda `__version__ = "4.5.11"` that I got from `/usr/local/anaconda3$ cat lib/python3.7/site-packages/conda/__init__.py` after try to upgrade from python37 to 38.
How do you reinstall if [official uninstall guide](https://docs.anaconda.com/anaconda/install/uninstall/) requires to run `conda` and it crashes? :)
