### ISSUE TITLE
spyder is not opening

### ISSUE THREAD

**Issue by dharmendra49** [conda/conda#9914]
Traceback (most recent call last):
  File "C:\Users\Dharmendra\Anaconda3\Scripts\spyder-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\app\start.py", line 205, in main
    mainwindow.main()
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3734, in main
    mainwindow = run_spyder(app, options, args)
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 3590, in run_spyder
    main.setup()
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\app\mainwindow.py", line 977, in setup
    'spyder.plugins.{}'.format(plugin_name))
  File "C:\Users\Dharmendra\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\plugins\pylint\__init__.py", line 14, in <module>
    from .plugin import Pylint as PLUGIN_CLASS
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\plugins\pylint\plugin.py", line 29, in <module>
    from spyder.plugins.pylint.confpage import PylintConfigPage
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\plugins\pylint\confpage.py", line 16, in <module>
    from spyder.plugins.pylint.widgets.pylintgui import PylintWidget
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\plugins\pylint\widgets\pylintgui.py", line 37, in <module>
    from spyder.plugins.pylint.utils import get_pylintrc_path
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\spyder\plugins\pylint\utils.py", line 16, in <module>
    import pylint.config
  File "C:\Users\Dharmendra\Anaconda3\lib\site-packages\pylint\config.py", line 54, in <module>
    import toml
ModuleNotFoundError: No module named 'toml'
[4016:9792:0504/073115.115:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)
[9032:7600:0504/073115.115:ERROR:broker_win.cc(59)] Error reading broker pipe: The pipe has been ended. (0x6D)

**Comment by cjmartian** [comment]
Hey @dharmendra49, thank you for opening this issue. Can you please fill out the rest of the issue template? It helps the community diagnose the issue and come more quickly to a resolution.
