### ISSUE TITLE
I am getting the error while installing a new package in created environment.   

### ISSUE THREAD

**Issue by GRADADIYA** [conda/conda#9915]
I am getting this error while installing a package into created environment. your help would be appreciated 

(_plearn) C:\Users\hari>conda install aftair
Traceback (most recent call last):
  File "S:\Python Books\Code\Python\envs\_plearn\Scripts\conda-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "S:\Python Books\Code\Python\envs\_plearn\lib\site-packages\pkg_resources\__init__.py", line 3259, in <module>
    def _initialize_master_working_set():
  File "S:\Python Books\Code\Python\envs\_plearn\lib\site-packages\pkg_resources\__init__.py", line 3242, in _call_aside
    f(*args, **kwargs)
  File "S:\Python Books\Code\Python\envs\_plearn\lib\site-packages\pkg_resources\__init__.py", line 3271, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "S:\Python Books\Code\Python\envs\_plearn\lib\site-packages\pkg_resources\__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "S:\Python Books\Code\Python\envs\_plearn\lib\site-packages\pkg_resources\__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "S:\Python Books\Code\Python\envs\_plearn\lib\site-packages\pkg_resources\__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pycosat>=0.6.1' distribution was not found and is required by conda

**Comment by cjmartian** [comment]
Hello @GRADADIYA, thank you for opening this issue! Could you please fill out the rest of the issue template? It helps the community find a quick resolution!

Thank you again!
