### ISSUE TITLE
Installing Anaconda3 on TACC's Lonestar5: ImportError: libimf.so: cannot open shared object file

### ISSUE THREAD

**Issue by henrymj** [conda/conda#9937]
## Current Behavior

When attempting to install Anaconda3 on lonestar5 of TACC, the install fails at the step of `conda init` with the error `ImportError: libimf.so: cannot open shared object file: No such file or directory`. Full traceback is below - you can see that my .local lives in my $HOME directory.

```
installation finished.
Do you wish the installer to initialize Anaconda3
by running conda init? [yes|no]
[no] >>> yes
An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Traceback (most recent call last):
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/exceptions.py", line 626, in conda_exception_handler
    return_value = func(*args, **kwargs)
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/main.py", line 92, in _main
    p, sub_parsers = generate_parser()
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/main.py", line 51, in generate_parser
    from ..cli import conda_argparse
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 14, in <module>
    from .common import add_parser_help
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/common.py", line 21, in <module>
    from ..resolve import MatchSpec
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/logic.py", line 32, in <module>
    import pycosat
ImportError: libimf.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/06914/henrymj/lonestar/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/main.py", line 162, in main
    return conda_exception_handler(_main, *args)
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/exceptions.py", line 630, in conda_exception_handler
    return handle_exception(e)
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/exceptions.py", line 620, in handle_exception
    print_unexpected_error_message(e)
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/exceptions.py", line 578, in print_unexpected_error_message
    info_stdout, info_stderr = get_info()
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/exceptions.py", line 537, in get_info
    from conda.cli import conda_argparse
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 14, in <module>
    from .common import add_parser_help
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/cli/common.py", line 21, in <module>
    from ..resolve import MatchSpec
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/resolve.py", line 12, in <module>
    from .logic import Clauses, minimal_unsatisfiable_subset
  File "/home1/06914/henrymj/.local/lib/python3.7/site-packages/conda/logic.py", line 32, in <module>
    import pycosat
ImportError: libimf.so: cannot open shared object file: No such file or directory
```

I have read online that this can be an issue of `/usr/local/bin` missing on LD_LIBRARY_PATH.

My current LD_LIBRARY_PATH is 

```
/opt/apps/intel18/python3/3.7.0/lib:/opt/cray/udreg/default/lib64:/opt/cray/ugni/default/lib64:/opt/cray/pe/pmi/default/lib64:/opt/cray/dmapp/default/lib64:/opt/cray/xpmem/default/lib64:/opt/cray/pe/mpt/7.7.3/gni/mpich-intel/16.0/lib:/opt/intel/debugger_2018/libipt/intel64/lib:/opt/intel/debugger_2018/iga/lib:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/../tbb/lib/intel64_lin/gcc4.4:/opt/intel/compilers_and_libraries_2018.2.199/linux/daal/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/tbb/lib/intel64/gcc4.7:/opt/intel/compilers_and_libraries_2018.2.199/linux/mkl/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/ipp/lib/intel64:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64_lin:/opt/intel/compilers_and_libraries_2018.2.199/linux/compiler/lib/intel64:/opt/apps/gcc/6.3.0/lib64:/opt/apps/gcc/6.3.0/lib
```
However, when I've tried this process after `export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/bin`, the error log did not change. I have since removed /usr/local/bin from LD_LIBRARY_PATH, but I can add it back!

### Steps to Reproduce

```
$ unset PYTHONPATH
$ wget "https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh"
$ bash Anaconda3-2020.02-Linux-x86_64.sh
-Enter work directory when prompted for installation location: $WORK/anaconda3
-Enter 'yes' to init
```

## Expected Behavior

I expect conda to install and initialize.

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```
If 'conda' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf conda
```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
If 'conda' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf conda
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```
If 'conda' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf conda
```
</p></details>

**Comment by chenghlee** [comment]
Can you try `unset LD_LIBRARY_PATH`, then running the installation again?

**Comment by henrymj** [comment]
Hi @chenghlee ,

Thank you for your suggestion. That did not resolve or change the error unfortunately! 

(On a related note, I fear I am not fully removing the failed installation - I usually run rm -r on the directory that was created ($WORK/anaconda3), but am not sure if additional steps need to be taken.)

**Comment by gurpreet-ai** [comment]
I just encountered this error. Has there been an resolutions to this error?
