### ISSUE TITLE
juyper lab and notebook broken after trying to update

### ISSUE THREAD

**Issue by brauliobarahona** [conda/conda#9950]
I tried to update jupyter lab with `conda update juypterlab` however this resulted in jupyter lab, jupyter notebook and conda broken.

conda is broken (tried these instructions in #9899) but however I guess the jupyter dependencies are still broken?

Here the error log:

```
Traceback (most recent call last):
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
    return func(*args, **kwargs)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
    exit_code = do_call(args, p)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
    module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
  File "/Users/my_user_name/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/cli/main_update.py", line 8, in <module>
    from .install import install
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/cli/install.py", line 19, in <module>
    from ..core.index import calculate_channel_urls, get_index
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
    import ctypes
  File "/Users/my_user_name/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/my_user_name/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/my_user_name/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/my_user_name/anaconda3/bin/conda", line 13, in <module>
    sys.exit(main())
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 150, in main
    return conda_exception_handler(_main, *args, **kwargs)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1371, in conda_exception_handler
    return_value = exception_handler(func, *args, **kwargs)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1082, in __call__
    return self.handle_exception(exc_val, exc_tb)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1126, in handle_exception
    return self.handle_unexpected_exception(exc_val, exc_tb)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1137, in handle_unexpected_exception
    self.print_unexpected_error_report(error_report)
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1207, in print_unexpected_error_report
    from .cli.main_info import get_env_vars_str, get_main_info_str
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
    from ..core.index import _supplement_index_with_system
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "/Users/my_user_name/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
    import ctypes
  File "/Users/my_user_name/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: dlopen(/Users/my_user_name/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
  Referenced from: /Users/my_user_name/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
  Reason: image not found

```

**Comment by janosh** [comment]
same problem

**Comment by discdiver** [comment]
See issue #9038. The solutions there should solve your problem. 

The most recent conda version seems to have a problem.

**Comment by janosh** [comment]
I downgraded to `conda` 4.8.2. No more issues. I think I'll just wait for the fix.
