### ISSUE TITLE
conda update breaks conda with ImportError: libffi.so.6: cannot open shared object file

### ISSUE THREAD

**Issue by gerazov** [conda/conda#9957]
### Current Behavior
Updating conda from 4.7.12 to 4.8.3 makes it unusable with the following error:
```
    Traceback (most recent call last):
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/home/user/miniconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "/home/user/miniconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
        import ctypes
      File "/home/user/miniconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

### Steps to Reproduce
Update conda v4.7:
```
$ conda update conda

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/user/miniconda3

  added / updated specs:
    - conda


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2020.1.1   |                0         125 KB
    certifi-2020.4.5.1         |           py37_0         155 KB
    cffi-1.14.0                |   py37he30daa8_1         224 KB
    conda-4.8.3                |           py37_0         2.8 MB
    conda-package-handling-1.6.1|   py37h7b6447c_0         798 KB
    cryptography-2.9.2         |   py37h1ba5d50_0         552 KB
    idna-2.9                   |             py_1          49 KB
    libffi-3.3                 |       he6710b0_1          50 KB
    ncurses-6.2                |       he6710b0_1         817 KB
    openssl-1.1.1g             |       h7b6447c_0         2.5 MB
    pycosat-0.6.3              |   py37h7b6447c_0          82 KB
    pycparser-2.20             |             py_0          92 KB
    pyopenssl-19.1.0           |           py37_0          87 KB
    requests-2.23.0            |           py37_0          92 KB
    ruamel_yaml-0.15.87        |   py37h7b6447c_0         256 KB
    setuptools-46.4.0          |           py37_0         514 KB
    six-1.14.0                 |           py37_0          27 KB
    sqlite-3.31.1              |       h62c20be_1         1.1 MB
    tqdm-4.46.0                |             py_0          60 KB
    urllib3-1.25.8             |           py37_0         169 KB
    xz-5.2.5                   |       h7b6447c_0         341 KB
    ------------------------------------------------------------
                                           Total:        10.8 MB

The following packages will be REMOVED:

  asn1crypto-1.2.0-py37_0
  pip-19.3.1-py37_0
  wheel-0.33.6-py37_0

The following packages will be UPDATED:

  ca-certificates                              2019.10.16-0 --> 2020.1.1-0
  certifi                                  2019.9.11-py37_0 --> 2020.4.5.1-py37_0
  cffi                                1.13.0-py37h2e261b9_0 --> 1.14.0-py37he30daa8_1
  conda                                       4.7.12-py37_0 --> 4.8.3-py37_0
  conda-package-han~                   1.6.0-py37h7b6447c_0 --> 1.6.1-py37h7b6447c_0
  cryptography                           2.8-py37h1ba5d50_0 --> 2.9.2-py37h1ba5d50_0
  idna                  pkgs/main/linux-64::idna-2.8-py37_0 --> pkgs/main/noarch::idna-2.9-py_1
  libffi                                   3.2.1-hd88cf55_4 --> 3.3-he6710b0_1
  ncurses                                    6.1-he6710b0_1 --> 6.2-he6710b0_1
  openssl                                 1.1.1d-h7b6447c_3 --> 1.1.1g-h7b6447c_0
  pycparser          pkgs/main/linux-64::pycparser-2.19-py~ --> pkgs/main/noarch::pycparser-2.20-py_0
  pyopenssl                                   19.0.0-py37_0 --> 19.1.0-py37_0
  requests                                    2.22.0-py37_0 --> 2.23.0-py37_0
  ruamel_yaml                        0.15.46-py37h14c3975_0 --> 0.15.87-py37h7b6447c_0
  setuptools                                  41.4.0-py37_0 --> 46.4.0-py37_0
  six                                         1.12.0-py37_0 --> 1.14.0-py37_0
  sqlite                                  3.30.0-h7b6447c_0 --> 3.31.1-h62c20be_1
  tqdm                                          4.36.1-py_0 --> 4.46.0-py_0
  urllib3                                     1.24.2-py37_0 --> 1.25.8-py37_0
  xz                                       5.2.4-h14c3975_4 --> 5.2.5-h7b6447c_0

The following packages will be DOWNGRADED:

  pycosat                              0.6.3-py37h14c3975_0 --> 0.6.3-py37h7b6447c_0

Proceed ([y]/n)? 

Downloading and Extracting Packages
...
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ conda info                 
```
This gives the error at the top.

<details open><summary><code>
`conda info`
</code></summary><p>

```
     active environment : base
    active env location : /home/user/miniconda3
            shell level : 1
       user config file : /home/user/.condarc
 populated config files : /home/user/.condarc
          conda version : 4.7.12
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __cuda=10.2
       base environment : /home/user/miniconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/user/miniconda3/pkgs
                          /home/user/.conda/pkgs
       envs directories : /home/user/miniconda3/envs
                          /home/user/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.12 requests/2.22.0 CPython/3.7.4 Linux/5.4.35-1-MANJARO manjaro/20.0.1 glibc/2.31
                UID:GID : 1001:1001
             netrc file : None
           offline mode : False
```
</p></details>

<details open><summary><code>
`conda config --show-sources`
</code></summary><p>

```
==> /home/user/.condarc <==
auto_activate_base: False
```

</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

# packages in environment at /home/user/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main    defaults
asn1crypto                1.2.0                    py37_0    defaults
ca-certificates           2019.10.16                    0    defaults
certifi                   2019.9.11                py37_0    defaults
cffi                      1.13.0           py37h2e261b9_0    defaults
chardet                   3.0.4                 py37_1003    defaults
conda                     4.7.12                   py37_0    defaults
conda-package-handling    1.6.0            py37h7b6447c_0    defaults
cryptography              2.8              py37h1ba5d50_0    defaults
idna                      2.8                      py37_0    defaults
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
openssl                   1.1.1d               h7b6447c_3    defaults
pip                       19.3.1                   py37_0    defaults
pycosat                   0.6.3            py37h14c3975_0    defaults
pycparser                 2.19                     py37_0    defaults
pyopenssl                 19.0.0                   py37_0    defaults
pysocks                   1.7.1                    py37_0    defaults
python                    3.7.4                h265db76_1    defaults
readline                  7.0                  h7b6447c_5    defaults
requests                  2.22.0                   py37_0    defaults
ruamel_yaml               0.15.46          py37h14c3975_0    defaults
setuptools                41.4.0                   py37_0    defaults
six                       1.12.0                   py37_0    defaults
sqlite                    3.30.0               h7b6447c_0    defaults
tk                        8.6.8                hbc83047_0    defaults
tqdm                      4.36.1                     py_0    defaults
urllib3                   1.24.2                   py37_0    defaults
wheel                     0.33.6                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yaml                      0.1.7                had09818_2    defaults
zlib                      1.2.11               h7b6447c_3    defaults
```

</p></details>

A clean install from the new `Miniconda3-latest-Linux-x86_64.sh` (v4.8.2) does work after updating to v4.8.3.

**Comment by discdiver** [comment]
See other solutions in #9038. 9038 needs reopened, I believe. This problem and using pip with Anaconda are now breaking things for many users with 4.8.3.

**Comment by vk0st** [comment]
I have the same problem after updating conda.
I created a symbolic link: `ln -s libffi.so.7.1.0 libffi.so.6` and now it's work. 

Find a simular [solution](https://github.com/conda/conda/issues/9038#issuecomment-634796463) but in my case `conda install` is working well

**Comment by jeames00** [comment]
Same issue for me (running Void Linux). Has this not been officially acknowledged, after all the replies in #9038? A comment there notes that packages still don't install properly with the symlinking workaround.

**Comment by TobiasJu** [comment]
I use miniconda3 for me this worked:

```
cd ~/miniconda3/lib/
ln -s libffi.so.7.1.0 libffi.so.6
```

thanks vK0st for the hint

**Comment by akug** [comment]
The suggestions of TobiasJu and vk0st also fixed it for me, with one small difference: I did not have a libffi.so.7.1.0 in the lib directory. I searched with `locate libffi.so.7` and found one in `~/miniconda3/pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7`. Symlinking this against version 6 or 7 worked, i.e.
```
cd ~/miniconda3/lib/
ln -s /home/${USER}/miniconda3/pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7 libffi.so.6
# OR
ln -s /home/${USER}/miniconda3/pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7 libffi.so.7
```
both seemed to fix the problem. At least I can use conda again. When trying to update conda again, I get
`The environment is inconsistent, please check the package plan carefully`.

**Comment by ikojcic** [comment]
I had the same issue on Fedora 27 after updating conda to 4.8.3 with:
`conda update -n base -c defaults conda`
Which gave me a similar error as  @gerazov, except that I got the following at the end of the error report:
`ImportError: libffi.so.7: cannot open shared object file: No such file or directory`

Since in my lib directory I had the file libffi.so.6.0.4 I did:
```
cd ~/miniconda3/lib/
ln -s libffi.so.6.0.4 libffi.so.7
```
so making a symbolic link also solved the problem for me.

**Comment by Sieboldianus** [comment]
> The suggestions of TobiasJu and vk0st also fixed it for me, with one small difference: I did not have a libffi.so.7.1.0 in the lib directory. I searched with `locate libffi.so.7` and found one in `~/miniconda3/pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7`. Symlinking this against version 6 or 7 worked, i.e.
> 
> ```
> cd ~/miniconda3/lib/
> ln -s /home/${USER}/miniconda3/pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7 libffi.so.6
> # OR
> ln -s /home/${USER}/miniconda3/pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7 libffi.so.7
> ```
> 
> both seemed to fix the problem. At least I can use conda again. When trying to update conda again, I get `The environment is inconsistent, please check the package plan carefully`.

The last one solved it for me. Thanks!

**Comment by akherlan** [comment]
It happens to me too just recently. I was upgrading miniconda3 with command `conda update -n base -c defaults conda`. Then every `conda` commands were broken due to libffi.so.6 cannot be found. I tried to create a symlink to libffi.so.8 in the same directory (`miniconda3/lib/`) because all libffi.so.* files are linked to this file. No luck! I look for libffi.so.7.1.0 and found it under `miniconda3/pkgs/libffi-3.3-h58526e2_2/lib/`, use it, and seems everything is working now. Hopefully.

**Comment by simonbogh** [comment]
> I have the same problem after updating conda. 
> I created a symbolic link: `ln -s libffi.so.7.1.0 libffi.so.6` and now it's work.
> 
> Find a simular [solution](https://github.com/conda/conda/issues/9038#issuecomment-634796463) but in my case `conda install` is working well

I had to do something very similar on macOS Ventura and now it is working again.

```sh
cd ~/miniconda3/lib
ln -s libffi.8.dylib libffi.6.dylib
```

**Comment by anranh97** [comment]
The above didn't work for me so I tried this. Fixed:
https://stackoverflow.com/questions/68127805/importerror-libffi-so-6-cannot-open-shared-object-file-no-such-file-or-direct

`cd ~/miniconda2/lib
# this would list all libffi and no libffi.so.6 there
ls -lsah libffi*
# there might be different libffi versions, you can delete a link if not working
# I had libffi.so.6 in this folder
ls ../pkgs/libffi-3.3-he6710b0_2/lib/
# created a symlink
ln -s ../pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.6 libffi.so.6
# or you could try creating symlink from libffi.so.7.1.0, both libffi.so.7 and libffi.so.6 were symlinks to it
ln -s ../pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7.1.0 libffi.so.6`

(if you get
`ln: failed to create symbolic link 'libffi.so.6': File exists`
just do a forced one
`ln -sf ../pkgs/libffi-3.3-he6710b0_2/lib/libffi.so.7.1.0 libffi.so.6`

**Comment by GGDRriedel** [comment]
> ls -lsah libffi*

I did this but now basically conda update conda does nothing at all
