### ISSUE TITLE
Conda install failed completely: Reports image not found everytime

### ISSUE THREAD

**Issue by DLWCMD** [conda/conda#9977]
### Steps to Reproduce

```

```

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>

```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```

```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

```

```
</p></details>

**Comment by DLWCMD** [comment]
Every conda function, install, info and all others, fails. Below is the result of entering "conda info"
Install fails every time with "image not found"

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/cli/main.py", line 84, in _main
        exit_code = do_call(args, p)
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/cli/conda_argparse.py", line 80, in do_call
        module = import_module(relative_mod, __name__.rsplit('.', 1)[0])
      File "/Users/david/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 728, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/cli/main_info.py", line 19, in <module>
        from ..core.index import _supplement_index_with_system
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/core/index.py", line 10, in <module>
        from .package_cache_data import PackageCacheData
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/core/package_cache_data.py", line 15, in <module>
        from .path_actions import CacheUrlAction, ExtractPackageAction
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/core/path_actions.py", line 30, in <module>
        from ..gateways.connection.download import download
      File "/Users/david/anaconda3/lib/python3.7/site-packages/conda/gateways/connection/download.py", line 13, in <module>
        import ctypes
      File "/Users/david/anaconda3/lib/python3.7/ctypes/__init__.py", line 7, in <module>
        from _ctypes import Union, Structure, Array
    ImportError: dlopen(/Users/david/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libffi.6.dylib
      Referenced from: /Users/david/anaconda3/lib/python3.7/lib-dynload/_ctypes.cpython-37m-darwin.so
      Reason: image not found

`$ /Users/david/anaconda3/bin/conda info`
