### ISSUE TITLE
Why does 'conda env list' look up the proxy server?

### ISSUE THREAD

**Issue by falconair** [conda/conda#9994]
**I'm submitting a...**
  - [x] bug report
  - [ ] feature request

## Current Behavior

I normally use my laptop with a work vpn connection. This evening I was disconnected form the VPN (but still on the internet) and I tried to lookup which conda environments I had installed. Surprisingly `conda env list` throws this error:

```
botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "http://myusername:mypassword@proxy.mycompany.com:8080"
```

Full stack trace:
```
(base) C:\>conda env list
Traceback (most recent call last):
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\awsrequest.py", line 92, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <botocore.awsrequest.AWSHTTPConnection object at 0x0000021E58AF4F08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\httpsession.py", line 263, in send
    chunked=self._chunked(request.headers),
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\util\retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\awsrequest.py", line 92, in _send_request
    method, url, body, headers, *args, **kwargs)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\awsrequest.py", line 119, in _send_output
    self.send(msg)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\awsrequest.py", line 203, in send
    return super(AWSConnection, self).send(str)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.ProxyError: ('Cannot connect to proxy.', NewConnectionError('<botocore.awsrequest.AWSHTTPConnection object at 0x0000021E58AF4F08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\Scripts\conda-env-script.py", line 5, in <module>
    from conda_env.cli.main import main
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda_env\cli\main.py", line 13, in <module>
    import conda.exports  # noqa
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\plan.py", line 25, in <module>
    from .core.index import LAST_CHANNEL_URLS, _supplement_index_with_prefix
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\index.py", line 10, in <module>
    from .package_cache_data import PackageCacheData
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\package_cache_data.py", line 15, in <module>
    from .path_actions import CacheUrlAction, ExtractPackageAction
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\core\path_actions.py", line 30, in <module>
    from ..gateways.connection.download import download
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\gateways\connection\download.py", line 18, in <module>
    from .session import CondaSession
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\gateways\connection\session.py", line 13, in <module>
    from .adapters.s3 import S3Adapter
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\conda\gateways\connection\adapters\s3.py", line 14, in <module>
    boto3.client('s3')  # https://github.com/conda/conda/issues/8993
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\boto3\__init__.py", line 91, in client
    return _get_default_session().client(*args, **kwargs)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\boto3\session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\session.py", line 823, in create_client
    credentials = self.get_credentials()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\session.py", line 428, in get_credentials
    'credential_provider').load_credentials()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\credentials.py", line 1948, in load_credentials
    creds = provider.load()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\credentials.py", line 1001, in load
    metadata = fetcher.retrieve_iam_role_credentials()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\utils.py", line 397, in retrieve_iam_role_credentials
    token = self._fetch_metadata_token()
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\utils.py", line 296, in _fetch_metadata_token
    response = self._session.send(request.prepare())
  File "C:\Users\my.username\AppData\Local\Continuum\anaconda3\lib\site-packages\botocore\httpsession.py", line 285, in send
    raise ProxyConnectionError(proxy_url=proxy_url, error=e)
botocore.exceptions.ProxyConnectionError: Failed to connect to proxy URL: "http://my.username:mypassword@proxy.mycompany.com:8080"
```

### Steps to Reproduce
```
conda env list
```

## Expected Behavior
I expected to be shown a list of locally installed environments

## Environment Information
<details open><summary><code>`conda info`</code></summary><p>
While doing `conda info` to get more information for this ticket, I received the _same_ error!!

I'm on windows 10, conda 4.8.3
```

```
</p></details>

<details open><summary><code>`conda config --show-sources`</code></summary><p>

```
ssl_verify: True
channels:
  - defaults
```
</p></details>

<details><summary><code>`conda list --show-channel-urls`</code></summary><p>

A bunch of packages which probably aren't relevant to this ticket
```

```
</p></details>

**Comment by Polanict** [comment]
Same exact situation happened to me today. Windows 10, conda 4.9.2, requests 2.26.0. 

.condarc file has a channel_alias (internal proxy). However this has always been the case for years. I note that this is a boto package traceback...why?
